<a href="https://colab.research.google.com/github/minyi-k03/Large-Language-Model-LLM-/blob/Fine-Tuning/Llama3_1_%ED%8A%B9%ED%97%88_%EC%B9%B4%ED%85%8C%EA%B3%A0%EB%A6%AC_%EB%B6%84%EB%A5%98_%ED%94%84%EB%A1%AC%ED%94%84%ED%8A%B8_%ED%8A%9C%EB%8B%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Llama 3.1을 이용해서 특허 카테고리 자동 분류하기 - 프롬프트 튜닝을 통한 성능 개선
## 작성자 : AISchool ( http://aischool.ai/%ec%98%a8%eb%9d%bc%ec%9d%b8-%ea%b0%95%ec%9d%98-%ec%b9%b4%ed%85%8c%ea%b3%a0%eb%a6%ac/ )
## Reference : https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct
## [특허 분야 자동분류 데이터] 데이터 : https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&dataSetSn=547

In [1]:
!nvidia-smi

Sun Jan 25 06:35:57 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   60C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

# 라이브러리 설치

In [2]:
import torch

# 1. GPU 확인 (잘 잡혀있는지 체크)
if torch.cuda.is_available():
    print(f"GPU Detected: {torch.cuda.get_device_name(0)}")
else:
    print("GPU가 없습니다. 상단 메뉴 [런타임] -> [런타임 유형 변경]에서 T4 GPU를 선택하세요.")

print("\nInstalling Libraries for Llama-3.1...")

# 2. 필수 라이브러리 설치
!pip install -U "transformers>=4.43.0" "accelerate>=0.26.0" "bitsandbytes>=0.42.0" "huggingface_hub"

print("\nSetup Completed.")

GPU Detected: Tesla T4

Installing Libraries for Llama-3.1...
Requirement already satisfied: transformers>=4.43.0 in /usr/local/lib/python3.12/dist-packages (4.57.6)
Requirement already satisfied: accelerate>=0.26.0 in /usr/local/lib/python3.12/dist-packages (1.12.0)
Collecting bitsandbytes>=0.42.0
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.0)
Collecting huggingface_hub
  Downloading huggingface_hub-1.3.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (3.20.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.43.0) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.26.0) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.26.0) (2.9.0+cu126)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=0.26.0) (3.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.43.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.43.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.43.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.43.0) (2026.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=0.26.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate>=0.26.0) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 14.3 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

Setup Completed.

In [3]:
import json
import pandas as pd

## [특허 분야 자동분류 데이터] 데이터 불러오기

In [4]:
!unzip Patent_AutoMatic_Regression.zip

Archive:  Patent_AutoMatic_Regression.zip
   creating: 라벨링데이터/
   creating: 라벨링데이터/A_농업_임업및어업_01_03/
   creating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/
   creating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01110_곡물및기타식량작물재배업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01121_채소작물재배업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01122_화훼작물재배업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01123_종자및묘목생산업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01131_과실작물재배업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01132_음료용및향신용작물재배업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01140_기타작물재배업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01151_콩나물재배업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01159_기타시설작물재배업.json
   creating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01211_젖소사육업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01212_육우사육업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01220_양돈업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01231_양계업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01239_기타가금류및조류사육업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01299_그외기타축산업.json
   creating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/013_작물재배및축산복합농업/
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/013_작물재배및축산복합농업/01300_작물재배및축산복합농업.json
   creating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01411_작물재배지원서비스업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01412_농산물건조_선별및기타수확후서비스업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01420_축산관련서비스업.json
   creating: 라벨링데이터/A_농업_임업및어업_01_03/02_임업/
   creating: 라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02011_임업용종묘생산업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02012_육림업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02030_임산물채취업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02040_임업관련서비스업.json
   creating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/
   creating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03111_원양어업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03112_연근해어업.json
   creating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03211_해수면양식어업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03212_내수면양식어업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03213_수산물부화및수산종자생산업.json
  inflating: 라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03220_어업관련서비스업.json
   creating: 라벨링데이터/B_광업_05_08/
   creating: 라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/
   creating: 라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/051_석탄광업/
  inflating: 라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/051_석탄광업/05100_석탄광업.json
   creating: 라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/052_원유및천연가스채굴업/
  inflating: 라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/052_원유및천연가스채굴업/05200_원유및천연가스채굴업.json
   creating: 라벨링데이터/B_광업_05_08/06_금속광업/
   creating: 라벨링데이터/B_광업_05_08/06_금속광업/061_철광업/
  inflating: 라벨링데이터/B_광업_05_08/06_금속광업/061_철광업/06100_철광업.json
   creating: 라벨링데이터/B_광업_05_08/06_금속광업/062_비철금속광업/
  inflating: 라벨링데이터/B_광업_05_08/06_금속광업/062_비철금속광업/06200_비철금속광업.json
   creating: 라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/
   creating: 라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/
  inflating: 라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07110_석회석및점토광업.json
  inflating: 라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07121_건설용석재채굴및쇄석생산업.json
  inflating: 라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07122_모래및자갈채취업.json
   creating: 라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/072_기타비금속광물광업/
  inflating: 라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/072_기타비금속광물광업/07220_천일염생산및암염채취업.json
   creating: 라벨링데이터/B_광업_05_08/08_광업지원서비스업/
   creating: 라벨링데이터/B_광업_05_08/08_광업지원서비스업/080_광업지원서비스업/
  inflating: 라벨링데이터/B_광업_05_08/08_광업지원서비스업/080_광업지원서비스업/08000_광업지원서비스업.json
   creating: 라벨링데이터/C_제조업_10_34/
   creating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/
   creating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/101_도축_육류가공및저장처리업/
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/101_도축_육류가공및저장처리업/10121_가금류가공및저장처리업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/101_도축_육류가공및저장처리업/10122_육류포장육및냉동육가공업_가금류제외.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/101_도축_육류가공및저장처리업/10129_육류기타가공및저장처리업_가금류제외.json
   creating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/102_수산물가공및저장처리업/
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/102_수산물가공및저장처리업/10211_수산동물훈제_조리및유사조제식품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/102_수산물가공및저장처리업/10212_수산동물건조및염장품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/102_수산물가공및저장처리업/10213_수산동물냉동품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/102_수산물가공및저장처리업/10220_수산식물가공및저장처리업.json
   creating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/103_과실_채소가공및저장처리업/
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/103_과실_채소가공및저장처리업/10301_김치류제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/103_과실_채소가공및저장처리업/10302_과실및그외채소절임식품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/103_과실_채소가공및저장처리업/10309_기타과실ㆍ채소가공및저장처리업.json
   creating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/105_낙농제품및식용빙과류제조업/
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/105_낙농제품및식용빙과류제조업/10501_액상시유및기타낙농제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/106_곡물가공품_전분및전분제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/106_곡물가공품_전분및전분제품제조업/10612_곡물제분업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/106_곡물가공품_전분및전분제품제조업/10613_곡물혼합분말및반죽제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/106_곡물가공품_전분및전분제품제조업/10619_기타곡물가공품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/106_곡물가공품_전분및전분제품제조업/10620_전분제품및당류제조업.json
   creating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10712_빵류제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10713_과자류및코코아제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10720_설탕제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10730_면류_마카로니및유사식품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10741_식초_발효및화학조미료제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10742_천연및혼합조제조미료제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10743_장류제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10749_기타식품첨가물제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10751_도시락류제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10759_기타식사용가공처리조리식품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10791_커피가공업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10793_수프및균질화식품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10796_건강보조용액화식품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10797_건강기능식품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/107_기타식품제조업/10799_그외기타식료품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/108_동물용사료및조제식품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/108_동물용사료및조제식품제조업/10801_배합사료제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/10_식료품제조업/108_동물용사료및조제식품제조업/10802_단미사료및기타사료제조업.json
   creating: 라벨링데이터/C_제조업_10_34/11_음료제조업/
   creating: 라벨링데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/
  inflating: 라벨링데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11111_탁주및약주제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11121_주정제조업.json
   creating: 라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/
  inflating: 라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11201_얼음제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11202_생수생산업.json
  inflating: 라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11209_기타비알코올음료제조업.json
   creating: 라벨링데이터/C_제조업_10_34/12_담배제조업/
   creating: 라벨링데이터/C_제조업_10_34/12_담배제조업/120_담배제조업/
  inflating: 라벨링데이터/C_제조업_10_34/12_담배제조업/120_담배제조업/12000_담배제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/
   creating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/131_방적및가공사제조업/
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/131_방적및가공사제조업/13101_면방적업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/131_방적및가공사제조업/13102_모방적업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/131_방적및가공사제조업/13103_화학섬유방적업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/131_방적및가공사제조업/13104_연사및가공사제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/131_방적및가공사제조업/13109_기타방적업.json
   creating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/132_직물직조및직물제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/132_직물직조및직물제품제조업/13211_면직물직조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/132_직물직조및직물제품제조업/13212_모직물직조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/132_직물직조및직물제품제조업/13213_화학섬유직물직조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/132_직물직조및직물제품제조업/13219_특수직물및기타직물직조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/132_직물직조및직물제품제조업/13221_침구및관련제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/132_직물직조및직물제품제조업/13223_커튼및유사제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/132_직물직조및직물제품제조업/13229_기타직물제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/134_섬유제품염색_정리및마무리가공업/
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/134_섬유제품염색_정리및마무리가공업/13401_솜및실염색가공업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/134_섬유제품염색_정리및마무리가공업/13402_직물_편조원단및의복류염색가공업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/134_섬유제품염색_정리및마무리가공업/13409_섬유제품기타정리및마무리가공업.json
   creating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/139_기타섬유제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/139_기타섬유제품제조업/13921_끈및로프제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/139_기타섬유제품제조업/13992_부직포및펠트제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/139_기타섬유제품제조업/13994_표면처리및적층직물제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/13_섬유제품제조업;의복제외/139_기타섬유제품제조업/13999_그외기타분류안된섬유제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/
   creating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/141_봉제의복제조업/
  inflating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/141_봉제의복제조업/14111_남자용겉옷제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/141_봉제의복제조업/14120_속옷및잠옷제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/141_봉제의복제조업/14193_가죽의복제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/141_봉제의복제조업/14194_유아용의복제조업.json
   creating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/144_의복액세서리제조업/
  inflating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/144_의복액세서리제조업/14411_스타킹및기타양말제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/144_의복액세서리제조업/14419_기타편조의복액세서리제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/144_의복액세서리제조업/14491_모자제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/14_의복_의복액세서리및모피제품제조업/144_의복액세서리제조업/14499_그외기타의복액세서리제조업.json
   creating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/
   creating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/151_가죽_가방및유사제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/151_가죽_가방및유사제품제조업/15110_모피및가죽제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/151_가죽_가방및유사제품제조업/15121_핸드백및지갑제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/151_가죽_가방및유사제품제조업/15129_가방및기타보호용케이스제조업.json
   creating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/152_신발및신발부분품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/152_신발및신발부분품제조업/15211_구두류제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/152_신발및신발부분품제조업/15219_기타신발제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/15_가죽_가방및신발제조업/152_신발및신발부분품제조업/15220_신발부분품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/
   creating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16101_일반제재업.json
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16102_표면가공목재및특정목적용제재목제조업.json
   creating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16211_박판_합판및유사적층판제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16221_목재문및관련제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16229_기타건축용나무제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16231_목재깔판류및기타적재판제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16291_목재도구및주방용나무제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16292_장식용목제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16299_그외기타나무제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/163_코르크및조물제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/163_코르크및조물제품제조업/16300_코르크및조물제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/
   creating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17110_펄프제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17121_신문용지제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17122_인쇄용및필기용원지제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17129_기타종이및판지제조업.json
   creating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17211_골판지제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17212_골판지상자및가공제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17221_종이포대및가방제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17222_판지상자및용기제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17223_식품위생용종이상자및용기제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17229_기타종이상자및용기제조업.json
   creating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17901_문구용종이제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17902_위생용종이제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17903_벽지및장판지제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17909_그외기타종이및판지제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/
   creating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/
  inflating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18111_경인쇄업.json
  inflating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18112_스크린인쇄업.json
  inflating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18113_오프셋인쇄업.json
  inflating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18119_기타인쇄업.json
  inflating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18121_제판및조판업.json
  inflating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18129_기타인쇄관련산업.json
   creating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/182_기록매체복제업/
  inflating: 라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/182_기록매체복제업/18200_기록매체복제업.json
   creating: 라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/
   creating: 라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/191_코크스및연탄제조업/
  inflating: 라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/191_코크스및연탄제조업/19101_코크스및관련제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19210_원유정제처리업.json
  inflating: 라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19229_기타석유정제물재처리업.json
   creating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/
   creating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20111_석유화학계기초화학물질제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20112_천연수지및나무화학물질제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20119_석탄화학계화합물및기타기초유기화학물질제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20121_산업용가스제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20129_기타기초무기화학물질제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20131_무기안료용금속산화물및관련제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20132_염료_조제무기안료_유연제및기타착색제제조업.json
   creating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20201_합성고무제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20202_합성수지및기타플라스틱물질제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20203_혼성및재생플라스틱소재물질제조업.json
   creating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20313_유기질비료및상토제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20321_화학살균ㆍ살충제및농업용약제제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20322_생물살균ㆍ살충제및식물보호제제조업.json
   creating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20411_일반용도료및관련제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20412_요업용도포제및관련제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20413_인쇄잉크및회화용물감제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20421_계면활성제제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20422_치약_비누및기타세제제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20423_화장품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20424_표면광택제및실내가향제제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20491_감광재료및관련화학제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20492_가공및정제염제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20493_접착제및젤라틴제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20495_바이오연료및혼합물제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20499_그외기타분류안된화학제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20501_합성섬유제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20502_재생섬유제조업.json
   creating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/
   creating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/211_기초의약물질및생물학적제제제조업/
  inflating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/211_기초의약물질및생물학적제제제조업/21101_의약용화합물및항생물질제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/211_기초의약물질및생물학적제제제조업/21102_생물학적제제제조업.json
   creating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/212_의약품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/212_의약품제조업/21210_완제의약품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/212_의약품제조업/21220_한의약품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/212_의약품제조업/21230_동물용의약품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/213_의료용품및기타의약관련제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/21_의료용물질및의약품제조업/213_의료용품및기타의약관련제품제조업/21300_의료용품및기타의약관련제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/
   creating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22111_타이어및튜브제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22112_타이어재생업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22191_고무패킹류제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22192_산업용그외비경화고무제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22193_고무의류및기타위생용비경화고무제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22199_그외기타고무제품제조업.json
   creating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22211_플라스틱선_봉_관및호스제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22212_플라스틱필름제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22213_플라스틱시트및판제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22221_벽및바닥피복용플라스틱제품제조업.json
  inflating: 라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22222_설치용및위생용플라스틱제품제조업.json

## 원천 데이터 불러오기

In [5]:
# 파일 경로
file_path = '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01110_곡물및기타식량작물재배업.json'

# 파일 열기 및 JSON 읽기
with open(file_path, 'r', encoding='utf-8') as file:
    raw_data = json.load(file)
raw_data = raw_data['dataset']

In [6]:
raw_data

[{'application_year': '2021',
  'invention_title': '기능성이 향상된 메밀싹 및 새싹채소의 재배방법',
  'ipc_section': 'A',
  'register_date': '20210927',
  'abstract': '본 발명은 약용식물을 선별하고 가공하는 단계; 상기 가공한 약용식물을 혼합한 후 추출 및 희석하여 약용식물 희석액을 제조하는 단계; 및 메밀종자를 파종한 후, 파종 상토에 상기 제조한 약용식물 희석액을 분무하면서 특정 온도 및 광조건에서 재배하는 단계를 포함하는 메밀싹의 재배방법 및 상기 방법으로 재배한 메밀싹에 관한 것이다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-022/20',
  'register_year': '2021',
  'ipc_all': 'A01G-022/20||A01G-007/06||A01N-025/02||A01N-065/08||A01N-065/30||A01N-065/34||A23L-033/00',
  'ipc_class': 'A01',
  'claims': '(1) 녹차, 짚신나물, 마디풀 및 소리쟁이를 각각 증열처리하고 건조하여 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이를 제조하는 단계;(2) 상기 (1)단계의 제조한 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이와 커피 분말을 혼합하여 약용식물 혼합물을 제조하는 단계;(3) 상기 (2)단계의 제조한 약용식물 혼합물에 물을 첨가하여 추출한 후 여과하여 약용식물 혼합 추출액을 제조하는 단계;(4) 상기 (3)단계의 제조한 약용식물 혼합 추출액에 물을 첨가하여 약용식물 희석액을 제조하는 단계; 및(5) 메밀종자를 파종한 후, 파종 상토에 상기 (4)단계의 제조한 약용식물 희석액을 분무하면서 재배하는 단계를 포함하는 메밀싹의 재배방법.제1항 내지 제3항 중 어느 한 항의 방법으로 재배된 메밀싹.',
  'application_date': '20210823',
  'register_number': '102308123',
  'documentId': 'kr20210110983b1',
  'application_number': '1020210110983'},
 {'application_year': '2021',
  'invention_title': '수경재배 베드 및 뿌리 생장 정보를 이용한 수경재배 방법',
  'ipc_section': 'A',
  'register_date': '20210928',
  'abstract': '본 발명은 수경재배 베드에 관한 것으로, 수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어한다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-031/02',
  'register_year': '2021',
  'ipc_all': 'A01G-031/02||A01G-024/40||A01G-007/00||G06Q-050/02',
  'ipc_class': 'A01',
  'claims': '수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어하고, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 1]을 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 수경재배 베드. [수식 1] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.) 수경재배 장치에서 식물이 수용되는 베드로 양액을 공급하는 단계; 및 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 베드의 측면 상부에 형성된 제1 배출구 또는 상기 베드의 하단에 형성된 제2 배출구를 통해 배출되도록 밸브를 제어하는 단계;를 포함하되, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 2]를 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 뿌리 생장 정보를 이용한 수경재배 방법. [수식 2] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.)',
  'application_date': '20210331',
  'register_number': '102308623',
  'documentId': 'kr20210041526b1',
  'application_number': '1020210041526'},
 {'application_year': '2021',
  'invention_title': '새싹보리순 자동 수확장치',
  'ipc_section': 'A',
  'register_date': '20210802',
  'abstract': '본 발명은 적어도 하나의 휠(112)이 장착되며, 구동모듈(114)이 내장되는 베이스프레임(110); 상기 베이스프레임(110) 상에 위치되는 수확모듈(120)로서, 전방을 향해 소정의 기울기를 갖도록 형성된 컨베이어부(122) 및 상기 컨베이어부(122)의 전단부 측에 위치되어 하방의 예취대상물을 예취시키는 예취부(124)를 포함하며, 상기 컨베이어부(122)의 전단부 측으로부터 후단부 측으로 예취물을 이송시키는, 수확모듈(120); 상기 베이스프레임(110) 상에 위치되되, 상기 컨베이어부(122)의 후단부 측에 형성되며, 수거수단이 위치되는 공간을 제공하는 포집공간부(130)로서, 상기 컨베이어부(122)에 의해 이송된 예취물을 상기 수거수단으로 포집시키는, 포집공간부(130); 및 상기 베이스프레임(110)의 후단에 위치되며, 상기 휠(112) 및 수확모듈(120)의 동작을 제어하는 제어모듈(140); 을 포함하는, 자동 수확장치를 제공한다.',
  'ipc_subclass': 'A01D',
  'ipc_main': 'A01D-034/03',
  'register_year': '2021',
  'ipc_all': 'A01D-034/03||A01D-034/00||A01D-034/30||A01D-041/16',
  'ipc_class': 'A01',
  'claims': '폭 방향으로 한 쌍의 휠(112)이 장착되며, 유압펌프(114b) 및 상기 유압펌프(114b)와 연결된 한 쌍의 유압모터(114a)를 구비하는 구동모듈(114)이 내장되는 베이스프레임(110); 상기 베이스프레임(110) 상에 위치되는 수확모듈(120)로서, 전방을 향해 소정의 기울기를 갖도록 형성된 컨베이어부(122) 및 상기 컨베이어부(122)의 전단부 측에 위치되어 하방의 예취대상물을 예취시키는 예취부(124)를 포함하며, 상기 컨베이어부(122)의 전단부 측으로부터 후단부 측으로 예취물을 이송시키는, 수확모듈(120); 상기 베이스프레임(110) 상에 위치되되, 상기 컨베이어부(122)의 후단부 측에 형성되며, 수거수단이 위치되는 공간을 제공하는 포집공간부(130)로서, 상기 컨베이어부(122)에 의해 이송된 예취물을 상기 수거수단으로 포집시키는, 포집공간부(130); 및 상기 베이스프레임(110)의 후단에 위치되며, 상기 휠(112) 및 수확모듈(120)의 동작을 제어하는 제어모듈(140);을 포함하고,상기 베이스프레임(110)에서 포집공간부(130)의 전단에 결합되되, 상기 베이스프레임(110)의 폭방향을 기준으로, 양측 단부에서, 수직방향으로 소정의 길이만큼 연장되는 트러스프레임(150)을 더 포함하고, 상기 트러스프레임(150)의 상부에는, 상기 컨베이어부(122)가 결합되며,상기 컨베이어부(122)는,상기 예취부(124)가 전단 측에서 지면과 인접한 부위에 구비되고, 상기 예취부(124)로부터 후방을 향해 상향 경사로 형성되는 경사컨베이어(122a) 및 상기 경사컨베이어(122a)의 후단으로부터 후방을 향해 수평방향으로 연장 형성되고 상기 트러스프레임(150)에 결합되는 수평컨베이어(122b)로 구분되고,상기 경사컨베이어(122a) 및 상기 수평컨베이어(122b)는 단일의 컨베이어벨트로 형성되며, 상기 단일의 컨베이어벨트는 상기 구동모듈(114)과 연결된 롤러모듈의 회전에 의해 동작되며,상기 베이스프레임(110)의 전방 측은,상기 경사컨베이어(122a)의 경사에 대응되는 경사부(110a)가 형성되며, 상기 경사부(110a)의 상부에는 상기 경사컨베이어(122a)가 위치되되, 상기 경사부(110a)의 전단부 및 상기 경사컨베이어(122a)의 전단부 사이에는 완충장치가 결합된 유압실린더 구조로 형성되고 상기 유압펌프(114b)에 연결되어 동력을 전달받는 리프팅부(116)가 구비되어 지면으로부터 상기 예취부(124)의 높이를 조절하는,자동 수확장치.',
  'application_date': '20210115',
  'register_number': '102287228',
  'documentId': 'kr20210005654b1',
  'application_number': '1020210005654'},
 {'application_year': '2020',
  'invention_title': '뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치',
  'ipc_section': 'A',
  'register_date': '20210722',
  'abstract': '실시예들은 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치에 관련된 것이다. 구체적으로 이 장치는, 작물의 하부에 위치하여 작물을 지지하며, 상부에서 하부로 갈수록 내측 단면적이 증가하는 형태의 지지체를 포함하고, 상기 지지체는 적어도 부분적으로 투명 재질로 구성된다. 본 장치에 의하면 작물의 뿌리 전체에 대한 이미지 데이터를 효과적으로 획득하여 최적의 생장환경을 위한 인공지능 학습 데이터로 활용할 수 있는 이점이 있다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-031/02',
  'register_year': '2021',
  'ipc_all': 'A01G-031/02||G06N-020/00||G06T-001/00||H04N-007/18',
  'ipc_class': 'A01',
  'claims': '뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치로서,상기 장치는,작물의 하부에 위치하여 작물을 지지하며, 상부에서 하부로 갈수록 내측 단면적이 증가하는 형태의 지지체를 포함하고,상기 지지체는 적어도 부분적으로 투명 재질로 구성되고,상기 지지체 위에 위치하며, 상기 작물의 줄기를 고정시키는 줄기 고정부; 및상기 지지체 아래에 위치하며, 상기 지지체의 내측면을 향해 촬영함으로써 작물의 줄기에 대한 영상을 획득하는 센싱부를 포함하고,상기 지지체는,상단 지지체;상기 상단 지지체 아래에 배치되는 하단 지지체; 및상기 상단 지지체와 상기 하단 지지체사이에 양액이 통과할 수 있는 양액 급수 공간을 포함하고,상기 상단 지지체와 하단 지지체를 연결하고, 상기 양액 급수 공간에 양액을 공급하는 연결부재를 더 포함하되,상기 연결부재는, 상기 상단 지지체에 체결되는 제1 연결부;상기 하단 지지체에 체결되는 제2 연결부; 및상기 제1 연결부와 제2 연결부 사이에 형성되며, 제1 연결부 또는 제2 연결부의 내측에 형성된 급수관을 통해 유입된 양액을 상기 양액 급수 공간으로 가이드하는 가이드부를 포함하는 것을 특징으로 하는 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치.',
  'application_date': '20201124',
  'register_number': '102282826',
  'documentId': 'kr20200158820b1',
  'application_number': '1020200158820'},
 {'application_year': '2020',
  'invention_title': '감초 및 뿌리식물 재배용 컨테이너',
  'ipc_section': 'A',
  'register_date': '20210407',
  'abstract': '본 발명은 감초 및 뿌리식물 재배용 컨테이너에 관한 것으로, 보다 상세하게는 대량의 뿌리식물을 효과적으로 재배할 수 있도록 함은 물론 토양이 채워져 뿌리식물이 재배되는 공간부로 유입된 물이나 약액의 배출을 용이하게 이뤄 뿌리식물이 썩게 되는 것을 방지할 수 있도록 하는 감초 및 뿌리식물 재배용 컨테이너에 관한 것이다. 본 발명은 다수개의 격판이 격자상으로 배치되게 조립되어 각각의 격판 사이에 토양이 채워지는 공간부(130)가 형성된 격판부(100); 상기 격판부(100)를 감싸도록 형성되되 각각의 격판 상단이 끼워질 수 있도록 하는 조립끼움공(210)이 형성되고, 길이방향 측면 하부에 메인배수공(220)이 형성된 메인바디부(200); 상기 메인바디부(200)의 내부 하측에 길이방향을 따라 설치되되 다수개의 이너배수공(410)이 일정간격으로 형성되어 상기 공간부(130)로 유입된 물이나 약액이 상기 이너배수공(410)을 통해 내부로 유입된 후, 상기 메인배수공(220)을 통해 외부로 배출될 수 있도록 하는 배수가이드유닛(400);을 포함하여 구성되는 것을 특징으로 한다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-009/02',
  'register_year': '2021',
  'ipc_all': 'A01G-009/02||A01G-022/35||A01G-027/00||A01G-009/00',
  'ipc_class': 'A01',
  'claims': '다수개의 격판이 격자상으로 배치되게 조립되어 각각의 격판 사이에 토양이 채워지는 공간부(130)가 형성된 격판부(100); 상기 격판부(100)를 감싸도록 형성되되 각각의 격판 상단이 끼워질 수 있도록 하는 조립끼움공(210)이 형성되고, 길이방향 측면 하부에 메인배수공(220)이 형성된 메인바디부(200); 상기 메인바디부(200)의 내부 하측에 길이방향을 따라 설치되되 다수개의 이너배수공(410)이 일정간격으로 형성되어 상기 공간부(130)로 유입된 물이나 약액이 상기 이너배수공(410)을 통해 내부로 유입된 후, 상기 메인배수공(220)을 통해 외부로 배출될 수 있도록 하는 배수가이드유닛(400);을 포함하여 구성되고, 상기 격판부(100)의 상측에는 물이나 약액이 유동하는 유동배관유닛(300)이 안착되게 설치되어 상기 유동배관유닛(300)에서 배출되는 물이나 약액이 상기 공간부(130)로 유입될 수 있도록 이루어지며, 상기 유동배관유닛(300)은 물이나 약액이 수용되는 안착바디(310)와, 상기 안착바디(310)의 폭방향 양측으로 연장된 상태로 상기 공간부(130)로 물이나 약액이 배출될 수 있도록 가이드하는 배출가이드구(320)를 포함하여 구성되고, 상기 배출가이드구(320)에는 물이나 약액이 상기 공간부(130)의 상측방향으로 배출될 수 있도록 하는 상방분출공(321)과 물이나 약액이 상기 공간부(130)의 하측방향으로 유동할 수 있도록 하는 하방분출튜브(322)가 마련된 것을 특징으로 하는 감초 및 뿌리식물 재배용 컨테이너.',
  'application_date': '20201012',
  'register_number': '102239559',
  'documentId': 'kr20200130915b1',
  'application_number': '1020200130915'},
 {'application_year': '2020',
  'invention_title': '고구마 재배 방법',
  'ipc_section': 'A',
  'open_number': '1020200105772',
  'abstract': '본 발명은 비닐하우스에서 키운 길이가 25 cm보다 크거나 같고 45 cm보다 작거나 같은 고구마 종묘를 뿌리로부터 첫 번째 마디를 45 도의 각도로 잘라낸 고구마 종묘를 준비하는 고구마 종묘 준비 단계; 상기 고구마 종묘의 줄기 부분을 21 ℃ 온도에서 36 시간 동안 물에 침지시키는 침지 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 고구마 종묘를 심기 전 10일에서 12일 전에 제초제를 살포하여 제초하는 제 1 제초 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 1 ha당 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료 250 ~ 350 kg을 공급하는 복합비료 공급 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 두둑폭 50 ~ 70 ㎝, 두둑높이 50 ~ 60 ㎝ 의 두둑을 형성하는 두둑 형성 단계; 상기 두둑의 상부에 물 또는 영양제를 공급할 수 있는 점적 테이프를 설치하고 상기 두둑 중 인접한 두 개의 두둑과 가운데 고랑을 비닐로 멀칭하고 상기 멀칭된 비닐에 고구마 종묘를 심기 위한 구멍을 뚫는 멀칭 단계; 상기 구멍에 물에 침지시킨 고구마 종묘의 줄기 세 번째 마디에서 다섯 번째 마디까지 삽입하여 고구마 종묘를 심는 정식 단계; 상기 고구마 종묘를 심은 후 제초제를 살포하는 제 2 제초 단계; 및 상기 고구마 종묘를 심은 토양에 1 ha당 150 ~ 250 kg 의 질산암모늄과 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료를 70 ~ 150 kg을 혼합한 혼합비료를 생육기간 중 3회 내지 6회 공급하는 혼합 비료 공급 단계;를 포함하는 사질 토양에서 고구마 재배 방법에 관한 것이다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-022/25',
  'ipc_all': 'A01G-022/25||A01G-013/02||A01G-002/10||A23L-019/10||C05G-001/00',
  'ipc_class': 'A01',
  'claims': '비닐하우스에서 키운 길이가 25 cm보다 크거나 같고 45 cm보다 작거나 같은 고구마 종묘를 뿌리로부터 첫 번째 마디를 45 도의 각도로 잘라낸 고구마 종묘를 준비하는 고구마 종묘 준비 단계;상기 고구마 종묘의 줄기 부분을 21 ℃ 온도에서 36 시간 동안 물에 침지시키는 침지 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 고구마 종묘를 심기 전 10일에서 12일 전에 제초제를 살포하여 제초하는 제 1 제초 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 1 ha당 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료 250 ~ 350 kg을 공급하는 복합비료 공급 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 두둑폭 50 ~ 70 ㎝, 두둑높이 50 ~ 60 ㎝ 의 두둑을 형성하는 두둑 형성 단계;상기 두둑의 상부에 물 또는 영양제를 공급할 수 있는 점적 테이프를 매립하여 설치하고 상기 두둑 중 인접한 두 개의 두둑과 가운데 고랑을 비닐로 멀칭하고 상기 멀칭된 비닐에 고구마 종묘를 심기 위한 구멍을 뚫는 멀칭 단계;상기 구멍에 물에 침지시킨 고구마 종묘의 줄기 세 번째 마디에서 다섯 번째 마디까지 삽입하여 고구마 종묘를 심는 정식 단계;상기 고구마 종묘를 심은 후 제초제를 살포하는 제 2 제초 단계; 및상기 고구마 종묘를 심은 토양에 1 ha당 150 ~ 250 kg 의 질산암모늄과 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료를 70 ~ 150 kg을 혼합한 혼합비료를 생육기간 중 3회 내지 6회 공급하는 혼합 비료 공급 단계;를 포함하되, 상기 멀칭 단계에서 멀칭하는 방법은 상기 두둑의 상부를 투명한 폴리에틸렌 재질의 비닐로 멀칭하고, 상기 두둑의 양옆면은 불투명한 폴리에틸렌 재질의 비닐로 멀칭하는 것을 특징으로 하고,상기 정식 단계의 고구마 종묘 1 ha당 40,000 ~ 50,000 개로 심는 것을 특징으로 하며, 상기 고구마 종묘의 종류는 호박고구마 또는 밤고구마인 것을 특징으로 하는,사질 토양에서 고구마 재배 방법.',
  'application_date': '20200824',
  'documentId': 'kr20200106506a',
  'application_number': '1020200106506'},
 {'application_year': '2020',
  'invention_title': '식물 재배 장치',
  'ipc_section': 'A',
  'register_date': '20210503',
  'abstract': '본 발명은 식물 재배 장치에 관한 것으로, 전기 분사 모듈을 이용하여 양액을 미세 액적 상태로 분사 공급함으로써, 양액 입자의 크기가 매우 미세하고 이온화된 상태로 형성되어 배지에서 재배되는 식물의 뿌리에 대한 흡수량 및 흡수율이 증가하며, 양액 입자의 부유 시간이 증가하여 식물의 뿌리에 지속적으로 흡수되고 이에 따라 외부로 배출되어 버려지는 양을 최소화할 수 있어 더욱 효율적으로 사용 관리될 수 있고, 이온화된 미세 액적에 의한 살균 기능을 통해 메인 케이스 내부 공간에 대한 살균 기능을 수행하여 세균 번식을 억제하고 이끼 및 녹조 발생을 방지하며, 별도의 압력 분사 모듈을 추가하여 이들을 다양한 방식으로 작동 제어함으로써, 양액 공급 기능 및 살균 기능을 동시에 최적의 상태로 수행할 수 있는 식물 재배 장치를 제공한다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-031/02',
  'register_year': '2021',
  'ipc_all': 'A01G-031/02||A01C-023/00||A01G-027/00||A61L-009/22||B05B-001/10||B05B-011/00||B05B-012/02||B05B-005/08',
  'ipc_class': 'A01',
  'claims': '상부에 식물을 재배할 수 있는 배지가 고정 장착되는 메인 케이스;양액 저장 챔버로부터 양액을 공급받고, 공급받은 양액을 전위차에 의한 전기력을 이용하여 상기 메인 케이스의 내부 공간에 미세 액적 상태로 분사하는 전기 분사 모듈;상기 양액 저장 챔버로부터 양액을 공급받고, 공급받은 양액을 압력을 통해 상기 메인 케이스 내부 공간에 분사하는 압력 분사 모듈; 및상기 전기 분사 모듈 및 압력 분사 모듈의 작동 상태를 동작 제어하는 제어부를 포함하고, 상기 제어부는 상기 전기 분사 모듈이 제 1 주기마다 작동하도록 동작 제어하고, 상기 압력 분사 모듈은 상기 제 1 주기와는 다른 제 2 주기마다 작동하도록 동작 제어하며,사용자가 제 1 작동 모드, 제 2 작동 모드 및 제 3 작동 모드를 선택할 수 있도록 별도의 선택 조작부가 구비되고,상기 제 1 작동 모드가 선택된 경우, 상기 제어부에 의해 상기 제 1 주기가 상기 제 2 주기보다 더 길게 설정되고, 상기 제 2 작동 모드가 선택된 경우, 상기 제어부에 의해 상기 제 2 주기가 상기 제 1 주기보다 더 길게 설정되며,상기 제 3 작동 모드가 선택된 경우, 상기 제어부는 상기 제 3 작동 모드가 선택된 시간 동안 상기 전기 분사 모듈이 상기 제 1 주기마다 작동하고 상기 압력 분사 모듈은 작동 정지하도록 동작 제어하는 것을 특징으로 하는 식물 재배 장치.',
  'application_date': '20200730',
  'register_number': '102249679',
  'documentId': 'kr20200095347b1',
  'application_number': '1020200095347'},
 {'application_year': '2020',
  'invention_title': '식물재배시스템의 차폐지지장치',
  'ipc_section': 'A',
  'open_number': '1020200074937',
  'abstract': '본 발명은 실내에서 식물재배에 필요한 공간의 제약을 해결하고 아울러, 미적감각을 고조하기 위하여, 식물을 천장에 매달아 아래를 향해 자라도록 하는 방법으로 재배 공간을 확보하는 식물재배시스템과 관련한다. 더욱 구체적으로, 식물재배시스템의 쳄버는 식물의 몸체가 수직방향으로 배치될 수 있도록 수직으로 형성된 개구부를 갖고, 상기 개구부에는 식물 줄기가 통과하여 안착될 차폐지지부가 부착되고, 상기 차폐지지부는 차폐지지몸체 및 차폐지지슬롯을 포함하고, 상기 차폐지지부에의 차폐지지몸체에는 조임수단이 구비된다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-009/02',
  'ipc_all': 'A01G-009/02||A01G-009/08',
  'ipc_class': 'A01',
  'claims': '식물재배시스템에 구비되는 것으로서, 상기 식물재배시스템은 식물 뿌리를 가두는 쳄버를 포함하고, 상기 쳄버의 개구부에는 식물 줄기가 통과하여 안착될 차폐지지부가 서로 대응하는 형태를 취해서 마주보게 복수 배치되며,상기 차폐지지부는 차폐지지몸체 및 차폐지지슬롯을 포함하되,상기 차폐지지부의 차폐지지몸체에는 조임수단이 구비되고,상기 조임수단은 조임용 돌기 및 조임용 밴드를 포함하고,상기 상기 조임용 돌기는 상기 차폐지지몸체 위에 수직으로 돌출되어 제공되고,상기 조임용 밴드는 탄성력을 갖는 고리 형태로 제공되어서,상기 조임용 돌기에 상기 조임용 밴드가 걸림이 되어 탄성력으로 조일 수 있도록 설치되는 것을 특징으로 하는 식물재배시스템의 차폐지지장치.',
  'application_date': '20200618',
  'documentId': 'kr20200074550a',
  'application_number': '1020200074550'},
 {'application_year': '2020',
  'invention_title': '탄화 코르크를 이용한 인삼 재배장치',
  'ipc_section': 'A',
  'register_date': '20201020',
  'abstract': '본 발명은 인삼 재배장치에 관한 것으로서 특히 탄화코르크를 소재로 재배장치를 성형함으로써, 여러 세균의 감염으로부터 인삼을 보호하고, 적정한 습도를 유지하면서 인삼을 대량으로 건강하고 빠르게 수경 재배할 수 있는 인삼 재배 장치에 관한 것이다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-031/02',
  'register_year': '2020',
  'ipc_all': 'A01G-031/02||A01G-022/35||B27K-005/00||B27K-007/00',
  'ipc_class': 'A01',
  'claims': '일면에 개방된 측방향으로 인삼종묘가 삽입되어 인삼종묘 전체가 수납되도록 상부와 측부가 개방된 수직의 재배홈(102)이 소정 간격마다 연속 형성된 코르크 소재로 성형된 몸체(101); 상기 재배홈(102)의 하부 위치에서 각 재배홈(102) 하부와 연통되도록 형성된 수평의 연장홈(103);상기 몸체(101)의 측면에 체결되어 인삼종묘의 뿌리가 덮이도록 재배홈(102)의 개방된 측부를 밀폐함으로써, 인삼종묘가 재배홈(102)에 수납된 상태에서 상부만 개방되고 나머지는 밀폐되도록 하는 코르크를 소재로 하여 판 형태로 성형된 덮개(104); 및상기 덮개(104)를 몸체(101)에 체결하는 체결수단;으로 구성된 것을 특징으로 하는 탄화 코르크를 이용한 인삼 재배장치.',
  'application_date': '20200529',
  'register_number': '102169934',
  'documentId': 'kr20200065170b1',
  'application_number': '1020200065170'},
 {'application_year': '2020',
  'invention_title': '산양산삼 재배방법',
  'ipc_section': 'A',
  'register_date': '20200812',
  'abstract': '본 발명은 산양산삼 재배방법에 관한 것으로, 보다 구체적으로는 멧돼지, 고라니, 노루, 너구리, 오소리, 들쥐 또는 조류로부터 작물을 보호하기 위한 산양산삼 재배방법에 관한 것으로 본 발명의 실시예는 하부금속그물망에 의해 땅 속에서 침입하는 유해조수로부터 작물의 뿌리를 보호하고 상부금속그물망에 의해 땅 위로 침입하는 유해조수로부터 씨앗과 작물을 보호하며, 하부금속그물망과 상부금속그물망의 연결을 탈부착고리를 이용하여 수확시에는 보호장치를 쉽게 분리하여 편리하게 수확할 수 있으며, 금속선재가 포함된 금속그물망을 이용하여 장기간 별도의 유지보수 없이 사용이 가능하고, 작물이 재배되는 토양공간을 금속그물망으로 폐쇄하므로 경사지의 토사와 작물의 유실을 방지할 수 있고, 금속그물망을 이용하므로 면적에 따라 금속그물망의 크기를 쉽게 적용하여 작물재배할 수 있으므로 소량의 작물재배부터 대량의 작물재배까지 모두 적용이 가능한 효과가 있다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-013/10',
  'register_year': '2020',
  'ipc_all': 'A01G-013/10||A01G-013/02||A01G-022/35||B21F-027/12',
  'ipc_class': 'A01',
  'claims': '토양에 작물재배장치를 설치하여 산삼종자를 파종하거나 묘삼을 이식하여 생장시켜 재배하고 수확하는 산양산삼의 재배 방법에 있어서,상기 작물재배장치는 금속선재를 포함하여 쉽게 구부릴 수 있는 피복된 금속그물망으로 형성된 상부금속그물망과 하부금속그물망을 포함하며,상기 하부금속그물망을 토양 아래에 오목하게 설치하여 토양공간을 형성하는 하부금속그물망설치단계와;상기 하부금속그물망 위에 흙을 덮어서 상기 토양공간에 흙을 채우는 제1차복토단계와;상기 제1차복토단계에서 채워진 흙의 표면에 산삼종자를 파종하거나 묘삼을 이식하는 식재단계와;상기 하부금속그물망의 가장자리에 연결되고 토양공간 위를 덮어서 토양공간을 폐쇄하는 판형의 상기 상부금속그물망을 설치하는 상부금속그물망설치단계와;상기 상부금속그물망 위에 흙을 덮는 복토단계와;상기 씨앗의 발아에 의해 발생한 산삼이나 식재된 산삼묘를 재배하는 재배단계와;상기 산양산삼의 재배가 종료된 후 상부금속그물망을 분리하는 분리단계와;상기 산양산삼을 수확하는 수확단계를 포함하며,상기 하부금속그물망설치단계에서 상부금속그물망에 연결되지 않은 말단부인 하부날개를 토양 표면에 배치하고;상기 상부금속그물망설치단계에서 하부금속그물망에 연결되지 않은 말단부인 상부날개를 상기 하부날개위를 덮으며,상기 상부금속그물망과 하부금속그물망이 안쪽의 토양을 폐쇄하는 것을 특징으로 하는 산양산삼 재배방법.',
  'application_date': '20200326',
  'register_number': '102145752',
  'documentId': 'kr20200036679b1',
  'application_number': '1020200036679'},
 {'application_year': '2020',
  'invention_title': '스마트기기를 이용한 식물재배시스템',
  'ipc_section': 'A',
  'register_date': '20210621',
  'abstract': '본 발명은 스마트 수단을 이용하여 자동으로 식물재배가 가능하며, 일상생활에 필요한 조명까지 종합적으로 함께 이루어질 수 있는 시스템에 관한 것으로서,천장에 고정되며 식물이 배치되는 재배유닛; 및 식물에 양액을 공급하는 공급유닛;을 포함하여 이루어지되,상기 재배유닛은,복수로 구비되며, 식물 뿌리가 위를 향하고 식물 잎이 아래를 향하여 재배될 수 있도록 지지를 하며, 설치 및 교환이 가능하도록 모듈화된 셀 단위로 제공되는 단위모듈; 및 식물에 광에너지를 공급하여 식물재배를 촉진하며, 일상생활에 필요한 조명까지 동시에 제공할 광원설비;를 포함하고,상기 공급유닛은,식물재배를 위한 양액을 저장하는 메인탱크; 및 저장된 양액을 상기 단위모듈에 이송하는 이송관;을 포함하여 이루어진다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-009/02',
  'register_year': '2021',
  'ipc_all': 'A01G-009/02||A01G-027/00||A01G-031/02||A01G-007/04||F21S-008/04||F21W-131/109',
  'ipc_class': 'A01',
  'claims': '스마트기기를 이용하여 자동으로, 역전된 상태로 재배되는 식물(pl)을 관리하며 동시에, 사무실 및 주거시설에 있어서 필요한 조명까지 함께 제공할 수 있는 스마트기기를 이용한 식물재배시스템으로서 재배유닛(100); 및 공급유닛(200);을 포함하고,재배유닛(100)은 단위모듈(110); 및 광원설비(120);를 포함하여서, 식물이 배치되며 빛을 공급하고,공급유닛(200)은 메인탱크(210); 및 이송관(220);을 포함하여서 식물재배를 위한 양액을 공급하고,단위모듈(110)은 하우징(111); 쳄버(112); 양액통(113); 포그발생장치(114); 기류발생팬(115); 및 재배유닛측 제어계측수단(116);를 포함하고,하우징(111)은 내부를 밀폐하며, 저면에 광원설비(120)의 빛을 반사시킬 반사판(111a)을 함께 구비하고,쳄버(112)는 하우징(111)의 저면에 배치되고, 수직방향으로 개구되어 식물을 고정하고,양액통(113)은 단위모듈(110)의 내부에 구비되어서 메인탱크(210)에 저장된 양액을 이송관(220)을 통하여 전달받아 일시 저장하고,포그발생장치(114)는 단위모듈(110)에 배치된 식물에 양액을 공급하기 위하여, 양액통(113)에 일시 저장된 양액을 양액포그(wa3) 형태로 만들고,기류발생팬(115)은 모터팬으로 제공되고, 외부의 공기를 양액통(113)에 불어넣어 기류를 발생하고, 기류를 따라 양액포그(wa3)가 이동하여 식물 뿌리(pl1)에 양액을 공급하도록 작동하고, 기류발생팬(115)의 강약 조절로 양액포그(wa3)의 공급량이 조절되고,재배유닛측 제어계측수단(116)은 단위모듈(110)에 배치된 식물재배가 용이하도록 온습도를 감지하여 무선네트워크를 통하여 모니터링하고, 식물재배에 필요한 기능제어를 수행하고,광원설비(120)는 광원프레임(121); 및 LED 전등 램프;를 포함하고,광원프레임(121)은 격자 형태를 취해서 단위모듈(110)의 저면과 떨어져 위치되며, 고정대(121a)를 통하여 천장에 고정되고, 광원프레임(121)에 단위모듈(110)이 고정되고,LED 전등 램프는 단위모듈(110)을 향하여 아래에서 위로 빛을 조사하여 식물에 광에너지를 제공하도록 설치되고,메인탱크(210)는 탱크몸체(211); 이송펌프(212); 및 공급유닛측 제어계측수단(213)을 포함하고,탱크몸체(211)는 내부를 밀폐하며 양액을 저장하는 탱크 형태를 취하고,이송펌프(212)는 이송관 일단(222)에 구비되어서 탱크몸체(211)에 저장된 양액을 이송관(220)으로 보내는 동력원의 역할을 수행하고,공급유닛측 제어계측수단(213)은 메인탱크(210)의 기능 상태을 제어하고 메인탱크(210)의 내측벽에 수위 수준을 감지하도록 설치된 센서를 포함하고,이송관(220)은 이송관 몸체(221); 이송관 일단(222); 이송관 타단(223);을 포함하여, 저장된 양액을 단위모듈(110)에 이송하며, 이송관(220)은 건물벽체에 고정브라킷으로 고정되고,이송관 몸체(221)는 파이프 형태를 취하여, 이송펌프(212)의 작동에 의하여 양액을 양액통(113)으로 이송하고,이송관 일단(222)은 파이프 형태의 일단으로서 메인탱크(210)에 위치되어, 이송펌프(212)가 작동하면 저장된 양액이 인입되는 입구의 역할을 수행하고,이송관 타단(223)은 파이프 형태의 타단으로서 단위모듈(110)에 위치되고 이송된 양액이 배출되는,것을 특징으로 하는 스마트기기를 이용한 식물재배시스템.',
  'application_date': '20200310',
  'register_number': '102269651',
  'documentId': 'kr20200029298b1',
  'application_number': '1020200029298'},
 {'application_year': '2020',
  'invention_title': '식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법',
  'ipc_section': 'A',
  'open_number': '1020210107206',
  'abstract': '본 발명은 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법에 관한 것으로, 보다 구체적으로는 용수의 pH 조절, LED 광조사 조절, 자극제 처리를 통한 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법에 관한 것이다.본 발명의 일 실시예에 따른 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법은 보리 종자를 종자 트레이 상에 준비하는 제 1단계; 상기 트레이 상에 위치된 보리 종자에 pH 6 내지 7의 용수를 이용하여 수분을 공급하는 제 2단계; 상기 수분이 공급된 보리 종자를 암처리 및 적색 LED 광처리를 실시하며 발아시키는 제 3단계; 상기 발아된 보리를 청색 LED 광처리를 실시하고, 자극제를 공급하며 재배하는 제 4단계; 상기 LED 광처리 및 자극제의 공급을 수행한 다음 1 내지 3일 이후 보리를 수확하는 제 5단계;를 포함하는 것을 특징으로 한다.',
  'ipc_subclass': 'A01G',
  'ipc_main': 'A01G-031/06',
  'ipc_all': 'A01G-031/06||A01G-022/20||A01G-007/06||A01G-009/24||A01N-037/42||A01N-049/00||C05F-011/10',
  'ipc_class': 'A01',
  'claims': '보리 종자를 종자 트레이 상에 준비하는 제 1단계;상기 트레이 상에 위치된 보리 종자에 pH 6 내지 7의 용수를 이용하여 수분을 공급하는 제 2단계;상기 수분이 공급된 보리 종자를 암처리 및 적색 LED 광처리를 실시하며 발아시키는 제 3단계;상기 발아된 보리를 청색 LED 광처리를 실시하고, 자극제를 공급하며 재배하는 제 4단계;상기 LED 광처리 및 자극제의 공급을 수행한 다음 1 내지 3일 이후 보리를 수확하는 제 5단계;를 포함하는 것을 특징으로 하는 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법',
  'application_date': '20200221',
  'documentId': 'kr20200021705a',
  'application_number': '1020200021705'},
 {'application_year': '2020',
  'invention_title': '뿌리 식물 재배 장치',
  'ipc_section': 'A',
  'open_number': '1020210105157',

In [7]:
len(raw_data)

50

In [8]:
raw_data[0]

{'application_year': '2021',
 'invention_title': '기능성이 향상된 메밀싹 및 새싹채소의 재배방법',
 'ipc_section': 'A',
 'register_date': '20210927',
 'abstract': '본 발명은 약용식물을 선별하고 가공하는 단계; 상기 가공한 약용식물을 혼합한 후 추출 및 희석하여 약용식물 희석액을 제조하는 단계; 및 메밀종자를 파종한 후, 파종 상토에 상기 제조한 약용식물 희석액을 분무하면서 특정 온도 및 광조건에서 재배하는 단계를 포함하는 메밀싹의 재배방법 및 상기 방법으로 재배한 메밀싹에 관한 것이다.',
 'ipc_subclass': 'A01G',
 'ipc_main': 'A01G-022/20',
 'register_year': '2021',
 'ipc_all': 'A01G-022/20||A01G-007/06||A01N-025/02||A01N-065/08||A01N-065/30||A01N-065/34||A23L-033/00',
 'ipc_class': 'A01',
 'claims': '(1) 녹차, 짚신나물, 마디풀 및 소리쟁이를 각각 증열처리하고 건조하여 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이를 제조하는 단계;(2) 상기 (1)단계의 제조한 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이와 커피 분말을 혼합하여 약용식물 혼합물을 제조하는 단계;(3) 상기 (2)단계의 제조한 약용식물 혼합물에 물을 첨가하여 추출한 후 여과하여 약용식물 혼합 추출액을 제조하는 단계;(4) 상기 (3)단계의 제조한 약용식물 혼합 추출액에 물을 첨가하여 약용식물 희석액을 제조하는 단계; 및(5) 메밀종자를 파종한 후, 파종 상토에 상기 (4)단계의 제조한 약용식물 희석액을 분무하면서 재배하는 단계를 포함하는 메밀싹의 재배방법.제1항 내지 제3항 중 어느 한 항의 방법으로 재배된 메밀싹.',
 'application_date': '20210823',
 'register_number': '102308123',
 'documentId': 'kr20210110983b1',
 'application_number': '1020210110983'}

In [9]:
raw_data[0].keys()

dict_keys(['application_year', 'invention_title', 'ipc_section', 'register_date', 'abstract', 'ipc_subclass', 'ipc_main', 'register_year', 'ipc_all', 'ipc_class', 'claims', 'application_date', 'register_number', 'documentId', 'application_number'])

In [10]:
def extract_fields(data):
    # 필요한 필드를 추출
    invention_title = data.get('invention_title', '')
    abstract = data.get('abstract', '')
    claims = data.get('claims', '')

    # 추출한 내용을 하나의 문자열로 연결
    result = f"invention_title: {invention_title} abstract: {abstract} claims: {claims}"

    return result

In [11]:
data_0 = extract_fields(raw_data[0])
data_0

'invention_title: 기능성이 향상된 메밀싹 및 새싹채소의 재배방법 abstract: 본 발명은 약용식물을 선별하고 가공하는 단계; 상기 가공한 약용식물을 혼합한 후 추출 및 희석하여 약용식물 희석액을 제조하는 단계; 및 메밀종자를 파종한 후, 파종 상토에 상기 제조한 약용식물 희석액을 분무하면서 특정 온도 및 광조건에서 재배하는 단계를 포함하는 메밀싹의 재배방법 및 상기 방법으로 재배한 메밀싹에 관한 것이다. claims: (1) 녹차, 짚신나물, 마디풀 및 소리쟁이를 각각 증열처리하고 건조하여 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이를 제조하는 단계;(2) 상기 (1)단계의 제조한 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이와 커피 분말을 혼합하여 약용식물 혼합물을 제조하는 단계;(3) 상기 (2)단계의 제조한 약용식물 혼합물에 물을 첨가하여 추출한 후 여과하여 약용식물 혼합 추출액을 제조하는 단계;(4) 상기 (3)단계의 제조한 약용식물 혼합 추출액에 물을 첨가하여 약용식물 희석액을 제조하는 단계; 및(5) 메밀종자를 파종한 후, 파종 상토에 상기 (4)단계의 제조한 약용식물 희석액을 분무하면서 재배하는 단계를 포함하는 메밀싹의 재배방법.제1항 내지 제3항 중 어느 한 항의 방법으로 재배된 메밀싹.'

## 라벨링 데이터 불러오기

In [12]:
# 파일 경로
file_path = '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01110_곡물및기타식량작물재배업.json'

# 파일 열기 및 JSON 읽기
with open(file_path, 'r', encoding='utf-8') as file:
    label_data = json.load(file)
label_data = label_data['dataset']

In [13]:
label_data

[{'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-022/20',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20210110983b1',
  'application_number': '1020210110983',
  'Ltext': '농업',
  'keyword': '노지재배/메밀노지재배/메밀/파종/특정온도/약용식물/방법/증열/커피분말/추출액',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20210041526b1',
  'application_number': '1020210041526',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/수경재배/양액/밸브/배출/방법/이온/흡수율/괴리율',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01D-034/03',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20210005654b1',
  'application_number': '1020210005654',
  'Ltext': '농업',
  'keyword': '노지재배/보리노지재배/수확장치/예취물/제어모듈/컨베이어/장치/트러스프레임/완충장치/리프팅부',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200158820b1',
  'application_number': '1020200158820',
  'Ltext': '농업',
  'keyword': '노지재배/식량작물재배/수경재배/지지체/투명재질/양액급수공간/장치/줄기/연결부재/급수관',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200130915b1',
  'application_number': '1020200130915',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/재배용컨테이너/대량/공간부/약액/장치/배수공/분출공/배출',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-022/25',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200106506a',
  'application_number': '1020200106506',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/고구마/영양제/점적테이프/혼합비료/방법/정식/폴리에틸렌/침지',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200095347b1',
  'application_number': '1020200095347',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/재배장치/양액/이온화/세균억제/장치/전위차/저장챔버/압력분사',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200074550a',
  'application_number': '1020200074550',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/차폐지지/미적감각/공간확보/부착/장치/쳄버/조임/탄성력',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200065170b1',
  'application_number': '1020200065170',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/인삼/성형/보호/대량재배/장치/재배홈/밀폐/체결',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-013/10',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200036679b1',
  'application_number': '1020200036679',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/산양산삼/금속그물망/유해조수/보호/방법/복토/발아/폐쇄',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200029298b1',
  'application_number': '1020200029298',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/재배시스템/조명/무듈화/광에너지/시스템/역전/반사판/포그',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/06',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200021705a',
  'application_number': '1020200021705',
  'Ltext': '농업',
  'keyword': '노지재배/보리노지재배/새싹보리/광조사/자국제/PH조절/방법/트레이/암처리/발아',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-022/25',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200019766a',
  'application_number': '1020200019766',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/뿌리식물/양액/고정/상품성/방법/지지/수경/용기',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200019765a',
  'application_number': '1020200019765',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/뿌리식물/육묘/파이프/재배기간단축/장치/배양토/개방/용기',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'B62B-001/10',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200018010b1',
  'application_number': '1020200018010',
  'Ltext': '농업',
  'keyword': '노지재배/콩노지재배/드럼형수레/드럼바퀴/보관용이/좁은공간사용/장치/가이드부/투입구/분배구',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01F-012/10',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200005340a',
  'application_number': '1020200005340',
  'Ltext': '농업',
  'keyword': '노지재배/콩노지재배/콩콤바인/수거포켓/역회전/가압/장치/순환경로/탈곡/예취',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-022/20',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20200005354b1',
  'application_number': '1020200005354',
  'Ltext': '농업',
  'keyword': '노지재배/보리노지재배/새싹보리/수용액/한약재/천연항균제/방법/불림/발아/생육',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190178145a',
  'application_number': '1020190178145',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/재배장치/재배판/상품성저하/방지/장치/재배홀/관통홀/플레이트',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190166976b1',
  'application_number': '1020190166976',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/뿌리작물/배수홀/재배통/결합/장치/토양/토압/관거치부',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-022/15',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190159695a',
  'application_number': '1020190159695',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/쓴잎/발효유황/폴리페놀/대량재배/방법/마사토/모종/피트모스',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190151156b1',
  'application_number': '1020190151156',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/뿌리식물/플레이트/일정각도/종결부/방법/엠보싱/합성수지/이격',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-022/40',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190136074b1',
  'application_number': '1020190136074',
  'Ltext': '농업',
  'keyword': '노지재배/콩노지재배/콩/항바이러스/관주액/침장/방법/농축액/양파/정식',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01C-007/18',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190127935a',
  'application_number': '1020190127935',
  'Ltext': '농업',
  'keyword': '노지재배/벼노지재배/점파식파종기/십자형절개/회동/커터/장치/구름이동/톱니형/멀칭비닐',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/14',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190127444b1',
  'application_number': '1020190127444',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/수직재배장치/프레임/롤러/작업속도향상/장치/지지부재/이격/브라켓',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/14',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190125748a',
  'application_number': '1020190125748',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/연무재배장치/프로그램/콘트롤장치/수분공급/장치/물리/힘/제어',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190125613b1',
  'application_number': '1020190125613',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/양액공급장치/하우징/분무경/분사/장치/셀/노출/노즐',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/14',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190122774a',
  'application_number': '1020190122774',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/뿌리식물/받침패드/U자/효율적/장치/프레임/단/승강부',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-007/06',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190122985a',
  'application_number': '1020190122985',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/금화규/이식/천연액비/베레젠시스/방법/천연/혼합/바실러스',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-007/06',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190117864a',
  'application_number': '1020190117864',
  'Ltext': '농업',
  'keyword': '노지재배/벼노지재배/벼/이화학/분석/시비/방법/녹비/영양생장기/미네랄',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-022/20',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190117867b1',
  'application_number': '1020190117867',
  'Ltext': '농업',
  'keyword': '노지재배/벼노지재배/가바벼/미생물/미네랄/비료/방법/이화학/파종/엽분석',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190116152b1',
  'application_number': '1020190116152',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/뿌리식물/고품질/조립/바디부/장치/격자/격판/유체가이드',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01C-005/04',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190115067b1',
  'application_number': '1020190115067',
  'Ltext': '농업',
  'keyword': '노지재배/벼노지재배/수동식파종기/깊이조절/스토퍼/신뢰성극대화/장치/승강블록/육각구멍/스톱돌기',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/04',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190107445b1',
  'application_number': '1020190107445',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/작물재배/이송/이동체인/장력/장치/배출/하강/밀폐',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'G06Q-050/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190098998a',
  'application_number': '1020190098998',
  'Ltext': '농업',
  'keyword': '노지재배/식량용뿌리작물노지재배/스마트작물재배/온도센서/양액공급/급수/시스템/공기순환/화재감지/카메라부',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/04',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20217005861a',
  'application_number': '1020217005861',
  'Ltext': '농업',
  'keyword': '노지재배/식량작물재배/수경재배/수평트랙/수평부재/구동유닛/시스템/안내로/트레이/지지탈것',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190097827a',
  'application_number': '1020190097827',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/식물재배/방근시트/침습시트/미관향상/장치/연통/양수분/일측',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190093677b1',
  'application_number': '1020190093677',
  'Ltext': '농업',
  'keyword': '노지재배/식량작물재배/포트장치/통수공/고정공/연장돌기/장치/고정관/안내홈/보조지지대',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-022/00',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190092866b1',
  'application_number': '1020190092866',
  'Ltext': '농업',
  'keyword': '노지재배/보리노지재배/새싹보리/광원/챔버/원심분리/방법/아임계/추출/수소수',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-031/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190088012a',
  'application_number': '1020190088012',
  'Ltext': '농업',
  'keyword': '노지재배/뿌리작물노지재배/새싹재배/보일러/가습기/청정수확/장치/정화/분무관/매직테이프',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01D-017/02',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190081411b1',
  'application_number': '1020190081411',
  'Ltext': '농업',
  'keyword': '노지재배/식량용뿌리작물노지재배/채굴장치/굴취삽/제토컨베이어/경사/장치/분리/하부/돌출',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/14',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190080160b1',
  'application_number': '1020190080160',
  'Ltext': '농업',
  'keyword': '노지재배/곡물작물노지재배/컨테이너팜/레일/이동부재/운용편리/방법/폐곡선/전자코드/카메라',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-009/029',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190079446b1',
  'application_number': '1020190079446',
  'Ltext': '농업',
  'keyword': '노지재배/보리노지재배/새싹보리재배/보리/머드/유효성분섭취/방법/염분/정제수/솔잎분말',
  'document_type': 'B1'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',
  'ipc_main': 'A01G-007/00',
  'Mno': '011',
  'country_code': 'KR',
  'Sno': '0111',
  'LLtext': '농업, 임업 및 어업(01~03)',
  'documentId': 'kr20190076890a',
  'application_number': '1020190076890',
  'Ltext': '농업',
  'keyword': '노지재배/곡물작물노지재배/작물용재배장치/하우징/토압조절부/공간확보/방법/영양공급관/연결부재/공기조절관',
  'document_type': 'A'},
 {'updateDate': '20220608',
  'LLno': 'A',
  'SSno': '01110',
  'Stext': '곡물 및 기타 식량작물 재배업',
  'SStext': '곡물 및 기타 식량작물 재배업',
  'Mtext': '작물 재배업',
  'Lno': '01',

In [14]:
len(label_data)

50

In [15]:
label_data[0]

{'updateDate': '20220608',
 'LLno': 'A',
 'SSno': '01110',
 'Stext': '곡물 및 기타 식량작물 재배업',
 'SStext': '곡물 및 기타 식량작물 재배업',
 'Mtext': '작물 재배업',
 'Lno': '01',
 'ipc_main': 'A01G-022/20',
 'Mno': '011',
 'country_code': 'KR',
 'Sno': '0111',
 'LLtext': '농업, 임업 및 어업(01~03)',
 'documentId': 'kr20210110983b1',
 'application_number': '1020210110983',
 'Ltext': '농업',
 'keyword': '노지재배/메밀노지재배/메밀/파종/특정온도/약용식물/방법/증열/커피분말/추출액',
 'document_type': 'B1'}

In [16]:
label_data[0].keys()

dict_keys(['updateDate', 'LLno', 'SSno', 'Stext', 'SStext', 'Mtext', 'Lno', 'ipc_main', 'Mno', 'country_code', 'Sno', 'LLtext', 'documentId', 'application_number', 'Ltext', 'keyword', 'document_type'])

In [17]:
label_data[0]['Ltext']

'농업'

# Llama 3.1 모델 불러오기

In [18]:
import os
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig


# 1. Hugging Face Token 설정
os.environ['HF_TOKEN'] = "Input Your Token"


# 2. 모델 설정 및 로드
model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"

# [수정 1] T4 GPU 메모리(16GB) 초과 방지를 위한 4-bit 설정
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16 # T4는 float16 권장
)

print(f" Loading Model: {model_id}...")

# 토크나이저 로드
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Llama 모델 에러 방지용 설정 (Padding Token)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# [수정 2] 모델 로드 (bfloat16 제거 -> float16 & 4bit 적용)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config, # 4-bit 양자화 적용
    device_map="auto",
    torch_dtype=torch.float16       # T4 호환성 맞춤
)

print(f"Model Loaded Successfully on {model.device}")

 Loading Model: meta-llama/Meta-Llama-3.1-8B-Instruct...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

Model Loaded Successfully on cuda:0

In [20]:
def generate_response(system_message, user_message, tokenizer, model):
    messages = [
        {"role": "system", "content": system_message},
        {"role": "user", "content": user_message},
    ]

    input_ids = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to(model.device)

    terminators = [
        tokenizer.eos_token_id,
        tokenizer.convert_tokens_to_ids("<|eot_id|>")
    ]

    outputs = model.generate(
        input_ids,
        max_new_tokens=256,
        eos_token_id=terminators,
        do_sample=False,   # 항상 가장 확률이 높은 값으로 예측
        temperature=0.6,
        top_p=0.9
    )
    response = outputs[0][input_ids.shape[-1]:]

    return tokenizer.decode(response, skip_special_tokens=True)

In [21]:
print(model.device)

cuda:0

# 특허 카테고리 분류 테스트

In [ ]:
# 특허_카테고리_list = ['임업',
#  '어업',
#  '농업',
#  '자동차 및 트레일러 제조업',
#  '인쇄 및 기록매체 복제업',
#  '펄프, 종이 및 종이제품 제조업',
#  '비금속 광물제품 제조업',
#  '고무 및 플라스틱제품 제조업',
#  '코크스, 연탄 및 석유정제품 제조업',
#  '음료 제조업',
#  '의복, 의복 액세서리 및 모피제품 제조업',
#  '가구 제조업',
#  '기타 운송장비 제조업',
#  '전기장비 제조업',
#  '의료용 물질 및 의약품 제조업',
#  '기타 제품 제조업',
#  '산업용 기계 및 장비 수리업',
#  '화학 물질 및 화학제품 제조업; 의약품 제외',
#  '목재 및 나무제품 제조업; 가구 제외',
#  '전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업',
#  '섬유제품 제조업; 의복 제외',
#  '담배 제조업',
#  '의료, 정밀, 광학 기기 및 시계 제조업',
#  '금속 가공제품 제조업; 기계 및 가구 제외',
#  '기타 기계 및 장비 제조업',
#  '가죽, 가방 및 신발 제조업',
#  '1차 금속 제조업',
#  '식료품 제조업',
#  '금속 광업',
#  '광업 지원 서비스업',
#  '석탄, 원유 및 천연가스 광업',
#  '비금속광물 광업; 연료용 제외']

In [23]:
특허_카테고리_list = ['임업',
 '어업',
 '농업']

In [ ]:
len(특허_카테고리_list)

3

In [24]:
#System Prompt Prompt Tuning 전 기본 프롬프트
system_prompt = f"너는 특허 카테고리를 분류하는 전문가야. \
아래 내용을 다음 특허 카테고리 중 하나로 분류해줘. 가능한 특허 카테고리 : {특허_카테고리_list}. \
최종 출력 결과는 다른말은 하지말고 분류한 카테고리만 출력해줘."
system_prompt

"너는 특허 카테고리를 분류하는 전문가야. 아래 내용을 다음 특허 카테고리 중 하나로 분류해줘. 가능한 특허 카테고리 : ['임업', '어업', '농업']. 최종 출력 결과는 다른말은 하지말고 분류한 카테고리만 출력해줘."

In [25]:
data_0

'invention_title: 기능성이 향상된 메밀싹 및 새싹채소의 재배방법 abstract: 본 발명은 약용식물을 선별하고 가공하는 단계; 상기 가공한 약용식물을 혼합한 후 추출 및 희석하여 약용식물 희석액을 제조하는 단계; 및 메밀종자를 파종한 후, 파종 상토에 상기 제조한 약용식물 희석액을 분무하면서 특정 온도 및 광조건에서 재배하는 단계를 포함하는 메밀싹의 재배방법 및 상기 방법으로 재배한 메밀싹에 관한 것이다. claims: (1) 녹차, 짚신나물, 마디풀 및 소리쟁이를 각각 증열처리하고 건조하여 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이를 제조하는 단계;(2) 상기 (1)단계의 제조한 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이와 커피 분말을 혼합하여 약용식물 혼합물을 제조하는 단계;(3) 상기 (2)단계의 제조한 약용식물 혼합물에 물을 첨가하여 추출한 후 여과하여 약용식물 혼합 추출액을 제조하는 단계;(4) 상기 (3)단계의 제조한 약용식물 혼합 추출액에 물을 첨가하여 약용식물 희석액을 제조하는 단계; 및(5) 메밀종자를 파종한 후, 파종 상토에 상기 (4)단계의 제조한 약용식물 희석액을 분무하면서 재배하는 단계를 포함하는 메밀싹의 재배방법.제1항 내지 제3항 중 어느 한 항의 방법으로 재배된 메밀싹.'

In [27]:
#Prompt-Tuning 전에 대한 답
llama3_1_inference_result = generate_response(system_message=system_prompt,
                              user_message=data_0,
                              tokenizer=tokenizer,
                              model=model)
print(llama3_1_inference_result)
# 정답 : 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

임업

In [28]:
raw_data[1]

{'application_year': '2021',
 'invention_title': '수경재배 베드 및 뿌리 생장 정보를 이용한 수경재배 방법',
 'ipc_section': 'A',
 'register_date': '20210928',
 'abstract': '본 발명은 수경재배 베드에 관한 것으로, 수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어한다.',
 'ipc_subclass': 'A01G',
 'ipc_main': 'A01G-031/02',
 'register_year': '2021',
 'ipc_all': 'A01G-031/02||A01G-024/40||A01G-007/00||G06Q-050/02',
 'ipc_class': 'A01',
 'claims': '수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어하고, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 1]을 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 수경재배 베드. [수식 1] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.) 수경재배 장치에서 식물이 수용되는 베드로 양액을 공급하는 단계; 및 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 베드의 측면 상부에 형성된 제1 배출구 또는 상기 베드의 하단에 형성된 제2 배출구를 통해 배출되도록 밸브를 제어하는 단계;를 포함하되, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 2]를 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 뿌리 생장 정보를 이용한 수경재배 방법. [수식 2] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.)',
 'application_date': '20210331',
 'register_number': '102308623',
 'documentId': 'kr20210041526b1',
 'application_number': '1020210041526'}

In [29]:
data_1 = extract_fields(raw_data[1])
data_1

'invention_title: 수경재배 베드 및 뿌리 생장 정보를 이용한 수경재배 방법 abstract: 본 발명은 수경재배 베드에 관한 것으로, 수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어한다. claims: 수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어하고, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 1]을 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 수경재배 베드. [수식 1] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.) 수경재배 장치에서 식물이 수용되는 베드로 양액을 공급하는 단계; 및 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 베드의 측면 상부에 형성된 제1 배출구 또는 상기 베드의 하단에 형성된 제2 배출구를 통해 배출되도록 밸브를 제어하는 단계;를 포함하되, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 2]를 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 뿌리 생장 정보를 이용한 수경재배 방법. [수식 2] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.)'

In [30]:
label_data[1]

{'updateDate': '20220608',
 'LLno': 'A',
 'SSno': '01110',
 'Stext': '곡물 및 기타 식량작물 재배업',
 'SStext': '곡물 및 기타 식량작물 재배업',
 'Mtext': '작물 재배업',
 'Lno': '01',
 'ipc_main': 'A01G-031/02',
 'Mno': '011',
 'country_code': 'KR',
 'Sno': '0111',
 'LLtext': '농업, 임업 및 어업(01~03)',
 'documentId': 'kr20210041526b1',
 'application_number': '1020210041526',
 'Ltext': '농업',
 'keyword': '노지재배/뿌리작물노지재배/수경재배/양액/밸브/배출/방법/이온/흡수율/괴리율',
 'document_type': 'B1'}

In [31]:
#Prompt-Tuning 전에 프롬프트에 대한 답변
llama3_1_inference_result = generate_response(system_message=system_prompt,
                              user_message=data_1,
                              tokenizer=tokenizer,
                              model=model)
print(llama3_1_inference_result)
# 정답 : 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

임업

# 전체 데이터 불러오기

In [32]:
def list_all_files_in_directory(directory_path):
    # 파일 경로를 저장할 리스트 초기화
    all_files = []

    # directory_path 하위 폴더의 모든 파일들의 경로를 리스트에 저장
    for root, dirs, files in os.walk(directory_path):
        for file in files:
            # 파일 경로를 리스트에 추가
            all_files.append(os.path.join(root, file))

    # 전체 파일 경로 리스트 반환
    return all_files

In [33]:
directory_path = '/content/원천데이터'
raw_file_list = list_all_files_in_directory(directory_path)
raw_file_list

['/content/원천데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02012_육림업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02030_임산물채취업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02040_임업관련서비스업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02011_임업용종묘생산업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03111_원양어업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03112_연근해어업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03211_해수면양식어업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03212_내수면양식어업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03220_어업관련서비스업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03213_수산물부화및수산종자생산업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01239_기타가금류및조류사육업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01231_양계업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01299_그외기타축산업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01211_젖소사육업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01212_육우사육업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01220_양돈업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01412_농산물건조_선별및기타수확후서비스업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01420_축산관련서비스업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01411_작물재배지원서비스업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/013_작물재배및축산복합농업/01300_작물재배및축산복합농업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01123_종자및묘목생산업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01122_화훼작물재배업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01140_기타작물재배업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01131_과실작물재배업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01159_기타시설작물재배업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01151_콩나물재배업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01121_채소작물재배업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01110_곡물및기타식량작물재배업.json',
 '/content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01132_음료용및향신용작물재배업.json',
 '/content/원천데이터/B_광업_05_08/05_석탄_원유및천연가스광업/051_석탄광업/05100_석탄광업.json',
 '/content/원천데이터/B_광업_05_08/05_석탄_원유및천연가스광업/052_원유및천연가스채굴업/05200_원유및천연가스채굴업.json',
 '/content/원천데이터/B_광업_05_08/08_광업지원서비스업/080_광업지원서비스업/08000_광업지원서비스업.json',
 '/content/원천데이터/B_광업_05_08/06_금속광업/061_철광업/06100_철광업.json',
 '/content/원천데이터/B_광업_05_08/06_금속광업/062_비철금속광업/06200_비철금속광업.json',
 '/content/원천데이터/B_광업_05_08/07_비금속광물광업;연료용제외/072_기타비금속광물광업/07220_천일염생산및암염채취업.json',
 '/content/원천데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07122_모래및자갈채취업.json',
 '/content/원천데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07110_석회석및점토광업.json',
 '/content/원천데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07121_건설용석재채굴및쇄석생산업.json',
 '/content/원천데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34019_기타일반기계및장비수리업.json',
 '/content/원천데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34011_건설ㆍ광업용기계및장비수리업.json',
 '/content/원천데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34020_전기ㆍ전자및정밀기기수리업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20412_요업용도포제및관련제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20422_치약_비누및기타세제제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20491_감광재료및관련화학제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20492_가공및정제염제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20495_바이오연료및혼합물제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20413_인쇄잉크및회화용물감제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20499_그외기타분류안된화학제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20493_접착제및젤라틴제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20424_표면광택제및실내가향제제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20411_일반용도료및관련제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20421_계면활성제제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20423_화장품제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20203_혼성및재생플라스틱소재물질제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20201_합성고무제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20202_합성수지및기타플라스틱물질제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20111_석유화학계기초화학물질제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20129_기타기초무기화학물질제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20112_천연수지및나무화학물질제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20119_석탄화학계화합물및기타기초유기화학물질제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20121_산업용가스제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20132_염료_조제무기안료_유연제및기타착색제제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20131_무기안료용금속산화물및관련제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20321_화학살균ㆍ살충제및농업용약제제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20313_유기질비료및상토제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20322_생물살균ㆍ살충제및식물보호제제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20501_합성섬유제조업.json',
 '/content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20502_재생섬유제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26129_기타반도체소자제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26112_비메모리용및기타전자집적회로제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26111_메모리용전자집적회로제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26121_발광다이오드제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/266_마그네틱및광학매체제조업/26600_마그네틱및광학매체제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26219_기타표시장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26295_전자감지장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26212_유기발광표시장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26223_연성및기타인쇄회로기판제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26211_액정표시장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26224_전자부품실장기판제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26299_그외기타전자부품제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26293_전자카드제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26294_전자코일_변성기및기타전자유도자제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26221_인쇄회로기판용적층판제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26292_전자저항기제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26222_경성인쇄회로기판제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26291_전자축전기제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26521_라디오_녹음및재생기기제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26511_텔레비전제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26519_비디오및기타영상기기제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26529_기타음향기기제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26410_유선통신장비제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26422_이동전화기제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26429_기타무선통신장비제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26421_방송장비제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26321_기억장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26329_기타주변기기제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26310_컴퓨터제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26322_컴퓨터모니터제조업.json',
 '/content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26323_컴퓨터프린터제조업.json',
 '/content/원천데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19229_기타석유정제물재처리업.json',
 '/content/원천데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19210_원유정제처리업.json',
 '/content/원천데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/191_코크스및연탄제조업/19101_코크스및관련제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22193_고무의류및기타위생용비경화고무제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22111_타이어및튜브제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22192_산업용그외비경화고무제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22112_타이어재생업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22191_고무패킹류제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22199_그외기타고무제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22232_포장용플라스틱성형용기제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22211_플라스틱선_봉_관및호스제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22299_그외기타플라스틱제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22251_폴리스티렌발포성형제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22292_플라스틱적층_도포및기타표면처리제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22212_플라스틱필름제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22221_벽및바닥피복용플라스틱제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22223_플라스틱창호제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22222_설치용및위생용플라스틱제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22249_기타기계ㆍ장비조립용플라스틱제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22291_플라스틱접착처리제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22229_기타건축용플라스틱조립제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22231_플라스틱포대_봉투및유사제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22259_기타플라스틱발포성형제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22213_플라스틱시트및판제조업.json',
 '/content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22241_운송장비조립용플라스틱제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30310_자동차엔진용신품부품제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30392_자동차용신품제동장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30391_자동차용신품조향장치및현가장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30331_자동차용신품동력전달장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30399_그외자동차용신품부품제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30320_자동차차체용신품부품제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30393_자동차용신품의자제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30332_자동차용신품전기장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/304_자동차재제조부품제조업/30400_자동차재제조부품제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30121_승용차및기타여객용자동차제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30122_화물자동차및특수목적용자동차제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30110_자동차용엔진제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30201_차체및특장차제조업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30202_자동차구조및장치변경업.json',
 '/content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30203_트레일러및세미트레일러제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31999_그외기타달리분류되지않은운송장비제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31991_자전거및환자용차량제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31920_모터사이클제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/312_철도장비제조업/31202_철도차량부품및관련장치물제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/312_철도장비제조업/31201_기관차및기타철도차량제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31111_강선건조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31113_기타선박건조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31120_오락및스포츠용보트건조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31114_선박구성부분품제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31112_합성수지선건조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31321_항공기용엔진제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31312_무인항공기및무인비행장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31311_유인항공기_항공우주선및보조장치제조업.json',
 '/content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31322_항공기용부품제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16211_박판_합판및유사적층판제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16229_기타건축용나무제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16221_목재문및관련제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16292_장식용목제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16291_목재도구및주방용나무제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16231_목재깔판류및기타적재판제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16299_그외기타나무제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16101_일반제재업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16102_표면가공목재및특정목적용제재목제조업.json',
 '/content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/163_코르크및조물제품제조업/16300_코르크및조물제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17211_골판지제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17223_식품위생용종이상자및용기제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17212_골판지상자및가공제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17221_종이포대및가방제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17229_기타종이상자및용기제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17222_판지상자및용기제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17901_문구용종이제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17909_그외기타종이및판지제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17902_위생용종이제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17903_벽지및장판지제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17129_기타종이및판지제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17110_펄프제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17121_신문용지제조업.json',
 '/content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17122_인쇄용및필기용원지제조업.json',
 '/content/원천데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11121_주정제조업.json',
 '/content/원천데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11111_탁주및약주제조업.json',
 '/content/원천데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11209_기타비알코올음료제조업.json',
 '/content/원천데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11202_생수생산업.json',
 '/content/원천데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11201_얼음제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23211_정형내화요업제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23212_부정형내화요업제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23232_타일및유사비내화요업제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23222_위생용및산업용도자기제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23231_점토벽돌_블록및유사비내화요업제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23229_기타일반도자기제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23239_기타건축용비내화요업제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23221_가정용및장식용도자기제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23993_비금속광물분쇄물생산업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23911_건설용석제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23999_그외기타분류안된비금속광물제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23994_암면및유사제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23992_연마재제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23995_탄소섬유제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23991_아스팔트콘크리트및혼합제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23919_기타석제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23111_판유리제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23199_그외기타유리제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23122_디스플레이장치용유리제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23192_포장용유리용기제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23121_1차유리제품_유리섬유및광학용유리제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23191_가정용유리제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23112_안전유리제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23129_기타산업용유리제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23119_기타판유리가공품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23322_레미콘제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23312_석회및플라스터제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23321_비내화모르타르제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23325_콘크리트관및기타구조용콘크리트제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23323_플라스터혼합제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23311_시멘트제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23324_콘크리트타일_기와_벽돌및블록제조업.json',
 '/content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23329_그외기타콘크리트제품및유사제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18129_기타인쇄관련산업.json',
 '/content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18119_기타인쇄업.json',
 '/content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18112_스크린인쇄업.json',
 '/content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18121_제판및조판업.json',
 '/content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18111_경인쇄업.json',
 '/content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18113_오프셋인쇄업.json',
 '/content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/182_기록매체복제업/18200_기록매체복제업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/252_무기및총포탄제조업/25200_무기및총포탄제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25130_핵반응기및증기보일러제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25114_수상금속골조구조재제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25123_압축및액화가스용기제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25113_육상금속골조구조재제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25112_구조용금속판제품및공작물제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25111_금속문_창_셔터및관련제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25119_기타구조용금속제품제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25122_금속탱크및저장용기제조업.json',
 '/content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25121_산업용난방보일러및방열기제조업.json',

In [34]:
len(raw_file_list)

461

In [35]:
def load_json_dataset(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = json.load(file)

    return data.get('dataset')

In [36]:
dataframes = []
for idx, file in enumerate(raw_file_list):
    print(idx, file)
    data = load_json_dataset(file)
    df = pd.DataFrame(data)
    dataframes.append(df)  # 리스트에 DataFrame 추가

raw_df = pd.concat(dataframes, ignore_index=True)

0 /content/원천데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02012_육림업.json
1 /content/원천데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02030_임산물채취업.json
2 /content/원천데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02040_임업관련서비스업.json
3 /content/원천데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02011_임업용종묘생산업.json
4 /content/원천데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03111_원양어업.json
5 /content/원천데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03112_연근해어업.json
6 /content/원천데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03211_해수면양식어업.json
7 /content/원천데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03212_내수면양식어업.json
8 /content/원천데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03220_어업관련서비스업.json
9 /content/원천데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03213_수산물부화및수산종자생산업.json
10 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01239_기타가금류및조류사육업.json
11 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01231_양계업.json
12 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01299_그외기타축산업.json
13 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01211_젖소사육업.json
14 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01212_육우사육업.json
15 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01220_양돈업.json
16 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01412_농산물건조_선별및기타수확후서비스업.json
17 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01420_축산관련서비스업.json
18 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01411_작물재배지원서비스업.json
19 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/013_작물재배및축산복합농업/01300_작물재배및축산복합농업.json
20 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01123_종자및묘목생산업.json
21 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01122_화훼작물재배업.json
22 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01140_기타작물재배업.json
23 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01131_과실작물재배업.json
24 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01159_기타시설작물재배업.json
25 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01151_콩나물재배업.json
26 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01121_채소작물재배업.json
27 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01110_곡물및기타식량작물재배업.json
28 /content/원천데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01132_음료용및향신용작물재배업.json
29 /content/원천데이터/B_광업_05_08/05_석탄_원유및천연가스광업/051_석탄광업/05100_석탄광업.json
30 /content/원천데이터/B_광업_05_08/05_석탄_원유및천연가스광업/052_원유및천연가스채굴업/05200_원유및천연가스채굴업.json
31 /content/원천데이터/B_광업_05_08/08_광업지원서비스업/080_광업지원서비스업/08000_광업지원서비스업.json
32 /content/원천데이터/B_광업_05_08/06_금속광업/061_철광업/06100_철광업.json
33 /content/원천데이터/B_광업_05_08/06_금속광업/062_비철금속광업/06200_비철금속광업.json
34 /content/원천데이터/B_광업_05_08/07_비금속광물광업;연료용제외/072_기타비금속광물광업/07220_천일염생산및암염채취업.json
35 /content/원천데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07122_모래및자갈채취업.json
36 /content/원천데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07110_석회석및점토광업.json
37 /content/원천데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07121_건설용석재채굴및쇄석생산업.json
38 /content/원천데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34019_기타일반기계및장비수리업.json
39 /content/원천데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34011_건설ㆍ광업용기계및장비수리업.json
40 /content/원천데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34020_전기ㆍ전자및정밀기기수리업.json
41 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20412_요업용도포제및관련제품제조업.json
42 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20422_치약_비누및기타세제제조업.json
43 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20491_감광재료및관련화학제품제조업.json
44 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20492_가공및정제염제조업.json
45 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20495_바이오연료및혼합물제조업.json
46 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20413_인쇄잉크및회화용물감제조업.json
47 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20499_그외기타분류안된화학제품제조업.json
48 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20493_접착제및젤라틴제조업.json
49 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20424_표면광택제및실내가향제제조업.json
50 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20411_일반용도료및관련제품제조업.json
51 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20421_계면활성제제조업.json
52 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20423_화장품제조업.json
53 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20203_혼성및재생플라스틱소재물질제조업.json
54 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20201_합성고무제조업.json
55 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20202_합성수지및기타플라스틱물질제조업.json
56 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20111_석유화학계기초화학물질제조업.json
57 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20129_기타기초무기화학물질제조업.json
58 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20112_천연수지및나무화학물질제조업.json
59 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20119_석탄화학계화합물및기타기초유기화학물질제조업.json
60 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20121_산업용가스제조업.json
61 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20132_염료_조제무기안료_유연제및기타착색제제조업.json
62 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20131_무기안료용금속산화물및관련제품제조업.json
63 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20321_화학살균ㆍ살충제및농업용약제제조업.json
64 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20313_유기질비료및상토제조업.json
65 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20322_생물살균ㆍ살충제및식물보호제제조업.json
66 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20501_합성섬유제조업.json
67 /content/원천데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20502_재생섬유제조업.json
68 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26129_기타반도체소자제조업.json
69 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26112_비메모리용및기타전자집적회로제조업.json
70 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26111_메모리용전자집적회로제조업.json
71 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26121_발광다이오드제조업.json
72 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/266_마그네틱및광학매체제조업/26600_마그네틱및광학매체제조업.json
73 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26219_기타표시장치제조업.json
74 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26295_전자감지장치제조업.json
75 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26212_유기발광표시장치제조업.json
76 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26223_연성및기타인쇄회로기판제조업.json
77 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26211_액정표시장치제조업.json
78 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26224_전자부품실장기판제조업.json
79 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26299_그외기타전자부품제조업.json
80 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26293_전자카드제조업.json
81 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26294_전자코일_변성기및기타전자유도자제조업.json
82 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26221_인쇄회로기판용적층판제조업.json
83 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26292_전자저항기제조업.json
84 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26222_경성인쇄회로기판제조업.json
85 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26291_전자축전기제조업.json
86 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26521_라디오_녹음및재생기기제조업.json
87 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26511_텔레비전제조업.json
88 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26519_비디오및기타영상기기제조업.json
89 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26529_기타음향기기제조업.json
90 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26410_유선통신장비제조업.json
91 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26422_이동전화기제조업.json
92 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26429_기타무선통신장비제조업.json
93 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26421_방송장비제조업.json
94 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26321_기억장치제조업.json
95 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26329_기타주변기기제조업.json
96 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26310_컴퓨터제조업.json
97 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26322_컴퓨터모니터제조업.json
98 /content/원천데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26323_컴퓨터프린터제조업.json
99 /content/원천데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19229_기타석유정제물재처리업.json
100 /content/원천데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19210_원유정제처리업.json
101 /content/원천데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/191_코크스및연탄제조업/19101_코크스및관련제품제조업.json
102 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22193_고무의류및기타위생용비경화고무제품제조업.json
103 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22111_타이어및튜브제조업.json
104 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22192_산업용그외비경화고무제품제조업.json
105 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22112_타이어재생업.json
106 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22191_고무패킹류제조업.json
107 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22199_그외기타고무제품제조업.json
108 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22232_포장용플라스틱성형용기제조업.json
109 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22211_플라스틱선_봉_관및호스제조업.json
110 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22299_그외기타플라스틱제품제조업.json
111 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22251_폴리스티렌발포성형제품제조업.json
112 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22292_플라스틱적층_도포및기타표면처리제품제조업.json
113 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22212_플라스틱필름제조업.json
114 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22221_벽및바닥피복용플라스틱제품제조업.json
115 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22223_플라스틱창호제조업.json
116 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22222_설치용및위생용플라스틱제품제조업.json
117 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22249_기타기계ㆍ장비조립용플라스틱제품제조업.json
118 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22291_플라스틱접착처리제품제조업.json
119 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22229_기타건축용플라스틱조립제품제조업.json
120 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22231_플라스틱포대_봉투및유사제품제조업.json
121 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22259_기타플라스틱발포성형제품제조업.json
122 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22213_플라스틱시트및판제조업.json
123 /content/원천데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22241_운송장비조립용플라스틱제품제조업.json
124 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30310_자동차엔진용신품부품제조업.json
125 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30392_자동차용신품제동장치제조업.json
126 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30391_자동차용신품조향장치및현가장치제조업.json
127 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30331_자동차용신품동력전달장치제조업.json
128 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30399_그외자동차용신품부품제조업.json
129 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30320_자동차차체용신품부품제조업.json
130 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30393_자동차용신품의자제조업.json
131 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30332_자동차용신품전기장치제조업.json
132 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/304_자동차재제조부품제조업/30400_자동차재제조부품제조업.json
133 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30121_승용차및기타여객용자동차제조업.json
134 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30122_화물자동차및특수목적용자동차제조업.json
135 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30110_자동차용엔진제조업.json
136 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30201_차체및특장차제조업.json
137 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30202_자동차구조및장치변경업.json
138 /content/원천데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30203_트레일러및세미트레일러제조업.json
139 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31999_그외기타달리분류되지않은운송장비제조업.json
140 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31991_자전거및환자용차량제조업.json
141 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31920_모터사이클제조업.json
142 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/312_철도장비제조업/31202_철도차량부품및관련장치물제조업.json
143 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/312_철도장비제조업/31201_기관차및기타철도차량제조업.json
144 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31111_강선건조업.json
145 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31113_기타선박건조업.json
146 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31120_오락및스포츠용보트건조업.json
147 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31114_선박구성부분품제조업.json
148 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31112_합성수지선건조업.json
149 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31321_항공기용엔진제조업.json
150 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31312_무인항공기및무인비행장치제조업.json
151 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31311_유인항공기_항공우주선및보조장치제조업.json
152 /content/원천데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31322_항공기용부품제조업.json
153 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16211_박판_합판및유사적층판제조업.json
154 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16229_기타건축용나무제품제조업.json
155 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16221_목재문및관련제품제조업.json
156 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16292_장식용목제품제조업.json
157 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16291_목재도구및주방용나무제품제조업.json
158 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16231_목재깔판류및기타적재판제조업.json
159 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16299_그외기타나무제품제조업.json
160 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16101_일반제재업.json
161 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16102_표면가공목재및특정목적용제재목제조업.json
162 /content/원천데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/163_코르크및조물제품제조업/16300_코르크및조물제품제조업.json
163 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17211_골판지제조업.json
164 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17223_식품위생용종이상자및용기제조업.json
165 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17212_골판지상자및가공제품제조업.json
166 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17221_종이포대및가방제조업.json
167 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17229_기타종이상자및용기제조업.json
168 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17222_판지상자및용기제조업.json
169 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17901_문구용종이제품제조업.json
170 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17909_그외기타종이및판지제품제조업.json
171 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17902_위생용종이제품제조업.json
172 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17903_벽지및장판지제조업.json
173 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17129_기타종이및판지제조업.json
174 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17110_펄프제조업.json
175 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17121_신문용지제조업.json
176 /content/원천데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17122_인쇄용및필기용원지제조업.json
177 /content/원천데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11121_주정제조업.json
178 /content/원천데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11111_탁주및약주제조업.json
179 /content/원천데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11209_기타비알코올음료제조업.json
180 /content/원천데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11202_생수생산업.json
181 /content/원천데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11201_얼음제조업.json
182 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23211_정형내화요업제품제조업.json
183 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23212_부정형내화요업제품제조업.json
184 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23232_타일및유사비내화요업제품제조업.json
185 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23222_위생용및산업용도자기제조업.json
186 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23231_점토벽돌_블록및유사비내화요업제품제조업.json
187 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23229_기타일반도자기제조업.json
188 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23239_기타건축용비내화요업제품제조업.json
189 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23221_가정용및장식용도자기제조업.json
190 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23993_비금속광물분쇄물생산업.json
191 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23911_건설용석제품제조업.json
192 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23999_그외기타분류안된비금속광물제품제조업.json
193 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23994_암면및유사제품제조업.json
194 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23992_연마재제조업.json
195 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23995_탄소섬유제조업.json
196 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23991_아스팔트콘크리트및혼합제품제조업.json
197 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23919_기타석제품제조업.json
198 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23111_판유리제조업.json
199 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23199_그외기타유리제품제조업.json
200 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23122_디스플레이장치용유리제조업.json
201 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23192_포장용유리용기제조업.json
202 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23121_1차유리제품_유리섬유및광학용유리제조업.json
203 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23191_가정용유리제품제조업.json
204 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23112_안전유리제조업.json
205 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23129_기타산업용유리제품제조업.json
206 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23119_기타판유리가공품제조업.json
207 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23322_레미콘제조업.json
208 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23312_석회및플라스터제조업.json
209 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23321_비내화모르타르제조업.json
210 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23325_콘크리트관및기타구조용콘크리트제품제조업.json
211 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23323_플라스터혼합제품제조업.json
212 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23311_시멘트제조업.json
213 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23324_콘크리트타일_기와_벽돌및블록제조업.json
214 /content/원천데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23329_그외기타콘크리트제품및유사제품제조업.json
215 /content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18129_기타인쇄관련산업.json
216 /content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18119_기타인쇄업.json
217 /content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18112_스크린인쇄업.json
218 /content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18121_제판및조판업.json
219 /content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18111_경인쇄업.json
220 /content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18113_오프셋인쇄업.json
221 /content/원천데이터/C_제조업_10_34/18_인쇄및기록매체복제업/182_기록매체복제업/18200_기록매체복제업.json
222 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/252_무기및총포탄제조업/25200_무기및총포탄제조업.json
223 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25130_핵반응기및증기보일러제조업.json
224 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25114_수상금속골조구조재제조업.json
225 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25123_압축및액화가스용기제조업.json
226 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25113_육상금속골조구조재제조업.json
227 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25112_구조용금속판제품및공작물제조업.json
228 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25111_금속문_창_셔터및관련제품제조업.json
229 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25119_기타구조용금속제품제조업.json
230 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25122_금속탱크및저장용기제조업.json
231 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25121_산업용난방보일러및방열기제조업.json
232 /content/원천데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/259_기타금속가공제품제조업/25911_분말야금제품제조업.json

In [37]:
raw_df

,application_year,invention_title,ipc_section,register_date,abstract,ipc_subclass,ipc_main,register_year,ipc_all,ipc_class,claims,application_date,register_number,documentId,application_number,open_number,open_date,open_year,applicant_name
0,2021,수목 보호 지지대,A,20210609,"본 발명은 수목 보호 지지대에 관한 것으로, 지면에 하단이 고정되는 다수의 버팀부재...",A01G,A01G-017/14,2021,A01G-017/14||A01G-017/10||A01G-009/12,A01,"수목(100)의 둘레 면에 접촉되는 다수의 밀착부재(2)와, 상기 밀착부재(2)를 ...",20210316,102265472,kr20210033985b1,1020210033985,NaN,NaN,NaN,NaN
1,2021,나무보호장치,A,NaN,강풍에 나무들이나 전봇대들이 뽑히거나 부러지고 넘어져서 피해를 입는 사고가 많다. ...,A01G,A01G-017/14,NaN,A01G-017/14||A01G-009/12,A01,'기초보호대' 와 '땅속지지대' 를 땅속에 설치하여 강풍에 나무가 옆으로 기울거나 ...,20210309,NaN,kr20210000760u,2020210000760,2020210000706,NaN,NaN,NaN
2,2021,수목 관리 장치 및 시스템,A,20210423,"본 발명은 수목 관리 장치 및 시스템에 관한 것으로, 더욱 상세하게는 수목을 안정적...",A01G,A01G-017/14,2021,A01G-017/14||A01G-027/00||F21S-008/08||F21S-00...,A01,"수목(1)을 감싸도록 주변에 설치되어 수목(1)을 지지하고, 유수를 집수하여 수목(...",20210118,102246082,kr20210006694b1,1020210006694,NaN,NaN,NaN,NaN
3,2021,휴대용 나무 안정지지대,A,20210601,"본 발명은 휴대용 나무 안정지지대에 관한 것으로서, 회동축(A)을 중심으로 크로스 ...",A01G,A01G-023/04,2021,A01G-023/04||A01G-017/14,A01,"회동축(A)을 중심으로 크로스 결합된 것으로서, 땅(E)에 지지되어 이식 대기중인 ...",20210106,102261923,kr20210001336b1,1020210001336,NaN,NaN,NaN,NaN
4,2020,수목보호용 블록,A,20210611,본 발명은 블록의 조립에 의해 이루어진 식재 공간 내부에 식재되는 수목의 위치에 맞...,A01G,A01G-013/02,2021,A01G-013/02||C04B-020/00||C04B-028/02||E01C-00...,A01,수목의 주위에 설치되어 수목이 설치된 지반의 흙이 외부로 흩어지는 것을 방지하는 수...,20201113,102266293,kr20200152106b1,1020200152106,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23045,2019,"버클, 벨트 및 벨트 부품",A,NaN,"피복의 흘러내림을 억제하는 벨트 버클로서, 벨트의 일단이 고정된 버클 본체와, 버클...",A41F,A41F-009/00,NaN,A41F-009/00||A41F-017/02||A44B-011/00||A44B-01...,A41,"피복의 흘러내림을 억제하는 벨트 버클에 있어서,상기 벨트의 일단이 고정되는 버클 본...",20190807,NaN,kr20207036302a,1020207036302,1020210009371,NaN,NaN,NaN
23046,2019,히든 벨트,A,NaN,"본 발명은 히든벨트에 대한 것으로서, 본 발명의 일실시예에 따른 벨트는 고정부와 긴...",A41F,A41F-009/02,NaN,A41F-009/02||A41F-009/00,A41,"벨트에 있어서,길이를 조절하고 고정할 수 있는 고정부;벨트에 몸통이 되는 긴 띠;바...",20190730,NaN,kr20190092477a,1020190092477,1020210014419,NaN,NaN,NaN
23047,2019,버클 전자 장치를 포함하는 스마트 벨트,A,NaN,"본 발명의 실시 예에 따른 스마트 벨트는, 착용 부위의 복부 압력 및 자세 기울기를...",A41F,A41F-009/00,NaN,A41F-009/00||A44B-011/00||A61B-005/00||A61B-00...,A41,착용 부위의 복부 압력 및 자세 기울기를 감지하기 위한 버클 전자 장치를 포함하는 ...,20190716,NaN,kr20190085948a,1020190085948,1020200053397,NaN,NaN,NaN
23048,2019,앞 쳐짐을 방지하는 작업용 조끼,A,20200602,"본 발명은 작업용조끼에 관한 것으로, 특히 작업용조끼의 전면에 공구 등의 중량체를 ...",A41D,A41D-001/04,2020,A41D-001/04||A41D-027/20,A41,개폐수단에 의하여 착용이 가능하게 개폐되어지며 다양한 도구 등의 수납을 위한 복수의...,20190712,102120590,kr20190084129b1,1020190084129,NaN,NaN,NaN,NaN
23049,2019,업기용 장갑,A,NaN,"본 고안에 따른 업기용 장갑은, 엄지손가락이 들어갈 수 있는 제1 공간과, 나머지 ...",A41D,A41D-019/00,NaN,A41D-019/00||A41D-019/01||A41D-019/015||A47D-0...,A41,"엄지손가락이 들어갈 수 있는 제1 공간과, 나머지 4개의 손가락이 들어갈 수 있는 ...",20190702,NaN,kr20190002754u,2020190002754,2020210000065,NaN,NaN,NaN

In [38]:
raw_df.shape

(23050, 19)

In [39]:
directory_path = '/content/라벨링데이터'
label_file_list = list_all_files_in_directory(directory_path)
label_file_list

['/content/라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02012_육림업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02030_임산물채취업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02040_임업관련서비스업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02011_임업용종묘생산업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03111_원양어업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03112_연근해어업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03211_해수면양식어업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03212_내수면양식어업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03220_어업관련서비스업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03213_수산물부화및수산종자생산업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01239_기타가금류및조류사육업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01231_양계업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01299_그외기타축산업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01211_젖소사육업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01212_육우사육업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01220_양돈업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01412_농산물건조_선별및기타수확후서비스업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01420_축산관련서비스업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01411_작물재배지원서비스업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/013_작물재배및축산복합농업/01300_작물재배및축산복합농업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01123_종자및묘목생산업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01122_화훼작물재배업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01140_기타작물재배업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01131_과실작물재배업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01159_기타시설작물재배업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01151_콩나물재배업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01121_채소작물재배업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01110_곡물및기타식량작물재배업.json',
 '/content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01132_음료용및향신용작물재배업.json',
 '/content/라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/051_석탄광업/05100_석탄광업.json',
 '/content/라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/052_원유및천연가스채굴업/05200_원유및천연가스채굴업.json',
 '/content/라벨링데이터/B_광업_05_08/08_광업지원서비스업/080_광업지원서비스업/08000_광업지원서비스업.json',
 '/content/라벨링데이터/B_광업_05_08/06_금속광업/061_철광업/06100_철광업.json',
 '/content/라벨링데이터/B_광업_05_08/06_금속광업/062_비철금속광업/06200_비철금속광업.json',
 '/content/라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/072_기타비금속광물광업/07220_천일염생산및암염채취업.json',
 '/content/라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07122_모래및자갈채취업.json',
 '/content/라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07110_석회석및점토광업.json',
 '/content/라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07121_건설용석재채굴및쇄석생산업.json',
 '/content/라벨링데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34019_기타일반기계및장비수리업.json',
 '/content/라벨링데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34011_건설ㆍ광업용기계및장비수리업.json',
 '/content/라벨링데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34020_전기ㆍ전자및정밀기기수리업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20412_요업용도포제및관련제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20422_치약_비누및기타세제제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20491_감광재료및관련화학제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20492_가공및정제염제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20495_바이오연료및혼합물제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20413_인쇄잉크및회화용물감제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20499_그외기타분류안된화학제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20493_접착제및젤라틴제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20424_표면광택제및실내가향제제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20411_일반용도료및관련제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20421_계면활성제제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20423_화장품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20203_혼성및재생플라스틱소재물질제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20201_합성고무제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20202_합성수지및기타플라스틱물질제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20111_석유화학계기초화학물질제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20129_기타기초무기화학물질제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20112_천연수지및나무화학물질제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20119_석탄화학계화합물및기타기초유기화학물질제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20121_산업용가스제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20132_염료_조제무기안료_유연제및기타착색제제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20131_무기안료용금속산화물및관련제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20321_화학살균ㆍ살충제및농업용약제제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20313_유기질비료및상토제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20322_생물살균ㆍ살충제및식물보호제제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20501_합성섬유제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20502_재생섬유제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26129_기타반도체소자제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26112_비메모리용및기타전자집적회로제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26111_메모리용전자집적회로제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26121_발광다이오드제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/266_마그네틱및광학매체제조업/26600_마그네틱및광학매체제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26219_기타표시장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26295_전자감지장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26212_유기발광표시장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26223_연성및기타인쇄회로기판제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26211_액정표시장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26224_전자부품실장기판제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26299_그외기타전자부품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26293_전자카드제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26294_전자코일_변성기및기타전자유도자제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26221_인쇄회로기판용적층판제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26292_전자저항기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26222_경성인쇄회로기판제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26291_전자축전기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26521_라디오_녹음및재생기기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26511_텔레비전제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26519_비디오및기타영상기기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26529_기타음향기기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26410_유선통신장비제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26422_이동전화기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26429_기타무선통신장비제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26421_방송장비제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26321_기억장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26329_기타주변기기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26310_컴퓨터제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26322_컴퓨터모니터제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26323_컴퓨터프린터제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19229_기타석유정제물재처리업.json',
 '/content/라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19210_원유정제처리업.json',
 '/content/라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/191_코크스및연탄제조업/19101_코크스및관련제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22193_고무의류및기타위생용비경화고무제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22111_타이어및튜브제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22192_산업용그외비경화고무제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22112_타이어재생업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22191_고무패킹류제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22199_그외기타고무제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22232_포장용플라스틱성형용기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22211_플라스틱선_봉_관및호스제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22299_그외기타플라스틱제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22251_폴리스티렌발포성형제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22292_플라스틱적층_도포및기타표면처리제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22212_플라스틱필름제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22221_벽및바닥피복용플라스틱제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22223_플라스틱창호제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22222_설치용및위생용플라스틱제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22249_기타기계ㆍ장비조립용플라스틱제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22291_플라스틱접착처리제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22229_기타건축용플라스틱조립제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22231_플라스틱포대_봉투및유사제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22259_기타플라스틱발포성형제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22213_플라스틱시트및판제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22241_운송장비조립용플라스틱제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30310_자동차엔진용신품부품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30392_자동차용신품제동장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30391_자동차용신품조향장치및현가장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30331_자동차용신품동력전달장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30399_그외자동차용신품부품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30320_자동차차체용신품부품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30393_자동차용신품의자제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30332_자동차용신품전기장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/304_자동차재제조부품제조업/30400_자동차재제조부품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30121_승용차및기타여객용자동차제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30122_화물자동차및특수목적용자동차제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30110_자동차용엔진제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30201_차체및특장차제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30202_자동차구조및장치변경업.json',
 '/content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30203_트레일러및세미트레일러제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31999_그외기타달리분류되지않은운송장비제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31991_자전거및환자용차량제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31920_모터사이클제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/312_철도장비제조업/31202_철도차량부품및관련장치물제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/312_철도장비제조업/31201_기관차및기타철도차량제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31111_강선건조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31113_기타선박건조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31120_오락및스포츠용보트건조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31114_선박구성부분품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31112_합성수지선건조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31321_항공기용엔진제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31312_무인항공기및무인비행장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31311_유인항공기_항공우주선및보조장치제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31322_항공기용부품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16211_박판_합판및유사적층판제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16229_기타건축용나무제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16221_목재문및관련제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16292_장식용목제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16291_목재도구및주방용나무제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16231_목재깔판류및기타적재판제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16299_그외기타나무제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16101_일반제재업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16102_표면가공목재및특정목적용제재목제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/163_코르크및조물제품제조업/16300_코르크및조물제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17211_골판지제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17223_식품위생용종이상자및용기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17212_골판지상자및가공제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17221_종이포대및가방제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17229_기타종이상자및용기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17222_판지상자및용기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17901_문구용종이제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17909_그외기타종이및판지제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17902_위생용종이제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17903_벽지및장판지제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17129_기타종이및판지제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17110_펄프제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17121_신문용지제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17122_인쇄용및필기용원지제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11121_주정제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11111_탁주및약주제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11209_기타비알코올음료제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11202_생수생산업.json',
 '/content/라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11201_얼음제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23211_정형내화요업제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23212_부정형내화요업제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23232_타일및유사비내화요업제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23222_위생용및산업용도자기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23231_점토벽돌_블록및유사비내화요업제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23229_기타일반도자기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23239_기타건축용비내화요업제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23221_가정용및장식용도자기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23993_비금속광물분쇄물생산업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23911_건설용석제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23999_그외기타분류안된비금속광물제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23994_암면및유사제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23992_연마재제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23995_탄소섬유제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23991_아스팔트콘크리트및혼합제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23919_기타석제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23111_판유리제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23199_그외기타유리제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23122_디스플레이장치용유리제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23192_포장용유리용기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23121_1차유리제품_유리섬유및광학용유리제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23191_가정용유리제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23112_안전유리제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23129_기타산업용유리제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23119_기타판유리가공품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23322_레미콘제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23312_석회및플라스터제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23321_비내화모르타르제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23325_콘크리트관및기타구조용콘크리트제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23323_플라스터혼합제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23311_시멘트제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23324_콘크리트타일_기와_벽돌및블록제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23329_그외기타콘크리트제품및유사제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18129_기타인쇄관련산업.json',
 '/content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18119_기타인쇄업.json',
 '/content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18112_스크린인쇄업.json',
 '/content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18121_제판및조판업.json',
 '/content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18111_경인쇄업.json',
 '/content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18113_오프셋인쇄업.json',
 '/content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/182_기록매체복제업/18200_기록매체복제업.json',
 '/content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/252_무기및총포탄제조업/25200_무기및총포탄제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25130_핵반응기및증기보일러제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25114_수상금속골조구조재제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25123_압축및액화가스용기제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25113_육상금속골조구조재제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25112_구조용금속판제품및공작물제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25111_금속문_창_셔터및관련제품제조업.json',
 '/content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25119_기타구조용금속제품제조업.json',

In [40]:
len(label_file_list)

461

In [41]:
dataframes = []
for idx, file in enumerate(label_file_list):
    print(idx, file)
    data = load_json_dataset(file)
    df = pd.DataFrame(data)
    dataframes.append(df)  # 리스트에 DataFrame 추가

label_df = pd.concat(dataframes, ignore_index=True)

0 /content/라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02012_육림업.json
1 /content/라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02030_임산물채취업.json
2 /content/라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02040_임업관련서비스업.json
3 /content/라벨링데이터/A_농업_임업및어업_01_03/02_임업/020_임업/02011_임업용종묘생산업.json
4 /content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03111_원양어업.json
5 /content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/031_어로어업/03112_연근해어업.json
6 /content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03211_해수면양식어업.json
7 /content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03212_내수면양식어업.json
8 /content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03220_어업관련서비스업.json
9 /content/라벨링데이터/A_농업_임업및어업_01_03/03_어업/032_양식어업및어업관련서비스업/03213_수산물부화및수산종자생산업.json
10 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01239_기타가금류및조류사육업.json
11 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01231_양계업.json
12 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01299_그외기타축산업.json
13 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01211_젖소사육업.json
14 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01212_육우사육업.json
15 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/012_축산업/01220_양돈업.json
16 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01412_농산물건조_선별및기타수확후서비스업.json
17 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01420_축산관련서비스업.json
18 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/014_작물재배및축산관련서비스업/01411_작물재배지원서비스업.json
19 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/013_작물재배및축산복합농업/01300_작물재배및축산복합농업.json
20 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01123_종자및묘목생산업.json
21 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01122_화훼작물재배업.json
22 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01140_기타작물재배업.json
23 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01131_과실작물재배업.json
24 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01159_기타시설작물재배업.json
25 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01151_콩나물재배업.json
26 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01121_채소작물재배업.json
27 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01110_곡물및기타식량작물재배업.json
28 /content/라벨링데이터/A_농업_임업및어업_01_03/01_농업/011_작물재배업/01132_음료용및향신용작물재배업.json
29 /content/라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/051_석탄광업/05100_석탄광업.json
30 /content/라벨링데이터/B_광업_05_08/05_석탄_원유및천연가스광업/052_원유및천연가스채굴업/05200_원유및천연가스채굴업.json
31 /content/라벨링데이터/B_광업_05_08/08_광업지원서비스업/080_광업지원서비스업/08000_광업지원서비스업.json
32 /content/라벨링데이터/B_광업_05_08/06_금속광업/061_철광업/06100_철광업.json
33 /content/라벨링데이터/B_광업_05_08/06_금속광업/062_비철금속광업/06200_비철금속광업.json
34 /content/라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/072_기타비금속광물광업/07220_천일염생산및암염채취업.json
35 /content/라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07122_모래및자갈채취업.json
36 /content/라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07110_석회석및점토광업.json
37 /content/라벨링데이터/B_광업_05_08/07_비금속광물광업;연료용제외/071_토사석광업/07121_건설용석재채굴및쇄석생산업.json
38 /content/라벨링데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34019_기타일반기계및장비수리업.json
39 /content/라벨링데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34011_건설ㆍ광업용기계및장비수리업.json
40 /content/라벨링데이터/C_제조업_10_34/34_산업용기계및장비수리업/340_산업용기계및장비수리업/34020_전기ㆍ전자및정밀기기수리업.json
41 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20412_요업용도포제및관련제품제조업.json
42 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20422_치약_비누및기타세제제조업.json
43 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20491_감광재료및관련화학제품제조업.json
44 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20492_가공및정제염제조업.json
45 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20495_바이오연료및혼합물제조업.json
46 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20413_인쇄잉크및회화용물감제조업.json
47 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20499_그외기타분류안된화학제품제조업.json
48 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20493_접착제및젤라틴제조업.json
49 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20424_표면광택제및실내가향제제조업.json
50 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20411_일반용도료및관련제품제조업.json
51 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20421_계면활성제제조업.json
52 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/204_기타화학제품제조업/20423_화장품제조업.json
53 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20203_혼성및재생플라스틱소재물질제조업.json
54 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20201_합성고무제조업.json
55 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/202_합성고무및플라스틱물질제조업/20202_합성수지및기타플라스틱물질제조업.json
56 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20111_석유화학계기초화학물질제조업.json
57 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20129_기타기초무기화학물질제조업.json
58 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20112_천연수지및나무화학물질제조업.json
59 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20119_석탄화학계화합물및기타기초유기화학물질제조업.json
60 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20121_산업용가스제조업.json
61 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20132_염료_조제무기안료_유연제및기타착색제제조업.json
62 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/201_기초화학물질제조업/20131_무기안료용금속산화물및관련제품제조업.json
63 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20321_화학살균ㆍ살충제및농업용약제제조업.json
64 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20313_유기질비료및상토제조업.json
65 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/203_비료_농약및살균ㆍ살충제제조업/20322_생물살균ㆍ살충제및식물보호제제조업.json
66 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20501_합성섬유제조업.json
67 /content/라벨링데이터/C_제조업_10_34/20_화학물질및화학제품제조업;의약품제외/205_화학섬유제조업/20502_재생섬유제조업.json
68 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26129_기타반도체소자제조업.json
69 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26112_비메모리용및기타전자집적회로제조업.json
70 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26111_메모리용전자집적회로제조업.json
71 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/261_반도체제조업/26121_발광다이오드제조업.json
72 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/266_마그네틱및광학매체제조업/26600_마그네틱및광학매체제조업.json
73 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26219_기타표시장치제조업.json
74 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26295_전자감지장치제조업.json
75 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26212_유기발광표시장치제조업.json
76 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26223_연성및기타인쇄회로기판제조업.json
77 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26211_액정표시장치제조업.json
78 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26224_전자부품실장기판제조업.json
79 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26299_그외기타전자부품제조업.json
80 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26293_전자카드제조업.json
81 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26294_전자코일_변성기및기타전자유도자제조업.json
82 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26221_인쇄회로기판용적층판제조업.json
83 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26292_전자저항기제조업.json
84 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26222_경성인쇄회로기판제조업.json
85 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/262_전자부품제조업/26291_전자축전기제조업.json
86 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26521_라디오_녹음및재생기기제조업.json
87 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26511_텔레비전제조업.json
88 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26519_비디오및기타영상기기제조업.json
89 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/265_영상및음향기기제조업/26529_기타음향기기제조업.json
90 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26410_유선통신장비제조업.json
91 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26422_이동전화기제조업.json
92 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26429_기타무선통신장비제조업.json
93 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/264_통신및방송장비제조업/26421_방송장비제조업.json
94 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26321_기억장치제조업.json
95 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26329_기타주변기기제조업.json
96 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26310_컴퓨터제조업.json
97 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26322_컴퓨터모니터제조업.json
98 /content/라벨링데이터/C_제조업_10_34/26_전자부품_컴퓨터_영상_음향및통신장비제조업/263_컴퓨터및주변장치제조업/26323_컴퓨터프린터제조업.json
99 /content/라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19229_기타석유정제물재처리업.json
100 /content/라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/192_석유정제품제조업/19210_원유정제처리업.json
101 /content/라벨링데이터/C_제조업_10_34/19_코크스_연탄및석유정제품제조업/191_코크스및연탄제조업/19101_코크스및관련제품제조업.json
102 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22193_고무의류및기타위생용비경화고무제품제조업.json
103 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22111_타이어및튜브제조업.json
104 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22192_산업용그외비경화고무제품제조업.json
105 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22112_타이어재생업.json
106 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22191_고무패킹류제조업.json
107 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/221_고무제품제조업/22199_그외기타고무제품제조업.json
108 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22232_포장용플라스틱성형용기제조업.json
109 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22211_플라스틱선_봉_관및호스제조업.json
110 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22299_그외기타플라스틱제품제조업.json
111 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22251_폴리스티렌발포성형제품제조업.json
112 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22292_플라스틱적층_도포및기타표면처리제품제조업.json
113 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22212_플라스틱필름제조업.json
114 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22221_벽및바닥피복용플라스틱제품제조업.json
115 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22223_플라스틱창호제조업.json
116 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22222_설치용및위생용플라스틱제품제조업.json
117 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22249_기타기계ㆍ장비조립용플라스틱제품제조업.json
118 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22291_플라스틱접착처리제품제조업.json
119 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22229_기타건축용플라스틱조립제품제조업.json
120 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22231_플라스틱포대_봉투및유사제품제조업.json
121 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22259_기타플라스틱발포성형제품제조업.json
122 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22213_플라스틱시트및판제조업.json
123 /content/라벨링데이터/C_제조업_10_34/22_고무및플라스틱제품제조업/222_플라스틱제품제조업/22241_운송장비조립용플라스틱제품제조업.json
124 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30310_자동차엔진용신품부품제조업.json
125 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30392_자동차용신품제동장치제조업.json
126 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30391_자동차용신품조향장치및현가장치제조업.json
127 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30331_자동차용신품동력전달장치제조업.json
128 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30399_그외자동차용신품부품제조업.json
129 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30320_자동차차체용신품부품제조업.json
130 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30393_자동차용신품의자제조업.json
131 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/303_자동차신품부품제조업/30332_자동차용신품전기장치제조업.json
132 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/304_자동차재제조부품제조업/30400_자동차재제조부품제조업.json
133 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30121_승용차및기타여객용자동차제조업.json
134 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30122_화물자동차및특수목적용자동차제조업.json
135 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/301_자동차용엔진및자동차제조업/30110_자동차용엔진제조업.json
136 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30201_차체및특장차제조업.json
137 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30202_자동차구조및장치변경업.json
138 /content/라벨링데이터/C_제조업_10_34/30_자동차및트레일러제조업/302_자동차차체및트레일러제조업/30203_트레일러및세미트레일러제조업.json
139 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31999_그외기타달리분류되지않은운송장비제조업.json
140 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31991_자전거및환자용차량제조업.json
141 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/319_그외기타운송장비제조업/31920_모터사이클제조업.json
142 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/312_철도장비제조업/31202_철도차량부품및관련장치물제조업.json
143 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/312_철도장비제조업/31201_기관차및기타철도차량제조업.json
144 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31111_강선건조업.json
145 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31113_기타선박건조업.json
146 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31120_오락및스포츠용보트건조업.json
147 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31114_선박구성부분품제조업.json
148 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/311_선박및보트건조업/31112_합성수지선건조업.json
149 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31321_항공기용엔진제조업.json
150 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31312_무인항공기및무인비행장치제조업.json
151 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31311_유인항공기_항공우주선및보조장치제조업.json
152 /content/라벨링데이터/C_제조업_10_34/31_기타운송장비제조업/313_항공기_우주선및부품제조업/31322_항공기용부품제조업.json
153 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16211_박판_합판및유사적층판제조업.json
154 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16229_기타건축용나무제품제조업.json
155 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16221_목재문및관련제품제조업.json
156 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16292_장식용목제품제조업.json
157 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16291_목재도구및주방용나무제품제조업.json
158 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16231_목재깔판류및기타적재판제조업.json
159 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/162_나무제품제조업/16299_그외기타나무제품제조업.json
160 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16101_일반제재업.json
161 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/161_제재및목재가공업/16102_표면가공목재및특정목적용제재목제조업.json
162 /content/라벨링데이터/C_제조업_10_34/16_목재및나무제품제조업;가구제외/163_코르크및조물제품제조업/16300_코르크및조물제품제조업.json
163 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17211_골판지제조업.json
164 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17223_식품위생용종이상자및용기제조업.json
165 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17212_골판지상자및가공제품제조업.json
166 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17221_종이포대및가방제조업.json
167 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17229_기타종이상자및용기제조업.json
168 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/172_골판지_종이상자및종이용기제조업/17222_판지상자및용기제조업.json
169 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17901_문구용종이제품제조업.json
170 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17909_그외기타종이및판지제품제조업.json
171 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17902_위생용종이제품제조업.json
172 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/179_기타종이및판지제품제조업/17903_벽지및장판지제조업.json
173 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17129_기타종이및판지제조업.json
174 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17110_펄프제조업.json
175 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17121_신문용지제조업.json
176 /content/라벨링데이터/C_제조업_10_34/17_펄프_종이및종이제품제조업/171_펄프_종이및판지제조업/17122_인쇄용및필기용원지제조업.json
177 /content/라벨링데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11121_주정제조업.json
178 /content/라벨링데이터/C_제조업_10_34/11_음료제조업/111_알코올음료제조업/11111_탁주및약주제조업.json
179 /content/라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11209_기타비알코올음료제조업.json
180 /content/라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11202_생수생산업.json
181 /content/라벨링데이터/C_제조업_10_34/11_음료제조업/112_비알코올음료및얼음제조업/11201_얼음제조업.json
182 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23211_정형내화요업제품제조업.json
183 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23212_부정형내화요업제품제조업.json
184 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23232_타일및유사비내화요업제품제조업.json
185 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23222_위생용및산업용도자기제조업.json
186 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23231_점토벽돌_블록및유사비내화요업제품제조업.json
187 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23229_기타일반도자기제조업.json
188 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23239_기타건축용비내화요업제품제조업.json
189 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/232_내화_비내화요업제품제조업/23221_가정용및장식용도자기제조업.json
190 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23993_비금속광물분쇄물생산업.json
191 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23911_건설용석제품제조업.json
192 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23999_그외기타분류안된비금속광물제품제조업.json
193 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23994_암면및유사제품제조업.json
194 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23992_연마재제조업.json
195 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23995_탄소섬유제조업.json
196 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23991_아스팔트콘크리트및혼합제품제조업.json
197 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/239_기타비금속광물제품제조업/23919_기타석제품제조업.json
198 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23111_판유리제조업.json
199 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23199_그외기타유리제품제조업.json
200 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23122_디스플레이장치용유리제조업.json
201 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23192_포장용유리용기제조업.json
202 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23121_1차유리제품_유리섬유및광학용유리제조업.json
203 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23191_가정용유리제품제조업.json
204 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23112_안전유리제조업.json
205 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23129_기타산업용유리제품제조업.json
206 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/231_유리및유리제품제조업/23119_기타판유리가공품제조업.json
207 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23322_레미콘제조업.json
208 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23312_석회및플라스터제조업.json
209 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23321_비내화모르타르제조업.json
210 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23325_콘크리트관및기타구조용콘크리트제품제조업.json
211 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23323_플라스터혼합제품제조업.json
212 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23311_시멘트제조업.json
213 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23324_콘크리트타일_기와_벽돌및블록제조업.json
214 /content/라벨링데이터/C_제조업_10_34/23_비금속광물제품제조업/233_시멘트_석회_플라스터및그제품제조업/23329_그외기타콘크리트제품및유사제품제조업.json
215 /content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18129_기타인쇄관련산업.json
216 /content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18119_기타인쇄업.json
217 /content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18112_스크린인쇄업.json
218 /content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18121_제판및조판업.json
219 /content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18111_경인쇄업.json
220 /content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/181_인쇄및인쇄관련산업/18113_오프셋인쇄업.json
221 /content/라벨링데이터/C_제조업_10_34/18_인쇄및기록매체복제업/182_기록매체복제업/18200_기록매체복제업.json
222 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/252_무기및총포탄제조업/25200_무기및총포탄제조업.json
223 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25130_핵반응기및증기보일러제조업.json
224 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25114_수상금속골조구조재제조업.json
225 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25123_압축및액화가스용기제조업.json
226 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25113_육상금속골조구조재제조업.json
227 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25112_구조용금속판제품및공작물제조업.json
228 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25111_금속문_창_셔터및관련제품제조업.json
229 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25119_기타구조용금속제품제조업.json
230 /content/라벨링데이터/C_제조업_10_34/25_금속가공제품제조업;기계및가구제외/251_구조용금속제품_탱크및증기발생기제조업/25122_금속탱크및저장용기제조업.json

In [42]:
label_df

,updateDate,LLno,SSno,Stext,SStext,Mtext,Lno,ipc_main,Mno,country_code,Sno,LLtext,documentId,application_number,Ltext,keyword,document_type
0,20220608,A,02012,영림업,육림업,임업,02,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210033985b1,1020210033985,임업,산림관리/임야수목관리/수목보호지지대/버팀부재/밀착부재/고정위치를용이하게조정/장치/중...,B1
1,20220608,A,02012,영림업,육림업,임업,02,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210000760u,2020210000760,임업,산림관리/산림조림/나무보호장치/땅속과나무에설치/미관상문제해결/사고예방/장치/기초보호...,U
2,20220608,A,02012,영림업,육림업,임업,02,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210006694b1,1020210006694,임업,산림관리/임야수목관리/수목관리장치/안정적지지/유수공급/수목효율적관리/장치/입수부/조...,B1
3,20220608,A,02012,영림업,육림업,임업,02,A01G-023/04,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210001336b1,1020210001336,임업,산림관리/산림조림/안정지지대/지지바아/각도구속부/휴대용안정지지대/장치/제1지지바아/...,B1
4,20220608,A,02012,영림업,육림업,임업,02,A01G-013/02,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20200152106b1,1020200152106,임업,산림관리/임야수목관리/블록/천연골재로제작/식재공간변형/물고임방지/장치/결합홈/결합돌...,B1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23045,20220608,C,14499,기타 의복 액세서리 제조업,그 외 기타 의복 액세서리 제조업,의복 액세서리 제조업,14,A41F-009/00,144,KR,1449,제조업(10~34),kr20207036302a,1020207036302,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//벨트/피복/고정/억제/조성물/버클본체/계지부/계합부,A
23046,20220608,C,14499,기타 의복 액세서리 제조업,그 외 기타 의복 액세서리 제조업,의복 액세서리 제조업,14,A41F-009/02,144,KR,1449,제조업(10~34),kr20190092477a,1020190092477,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//벨트/고정부/긴띠/고정/조성물/조절/고리/스프링클립,A
23047,20220608,C,14499,기타 의복 액세서리 제조업,그 외 기타 의복 액세서리 제조업,의복 액세서리 제조업,14,A41F-009/00,144,KR,1449,제조업(10~34),kr20190085948a,1020190085948,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//스마트벨트/접촉부/압력/자세교정/장치/버클/밴드/경고신호,A
23048,20220608,C,14499,기타 의복 액세서리 제조업,그 외 기타 의복 액세서리 제조업,의복 액세서리 제조업,14,A41D-001/04,144,KR,1449,제조업(10~34),kr20190084129b1,1020190084129,"의복, 의복 액세서리 및 모피제품 제조업",의류액세서리제조//조끼/견갑골/무게하중/착용감/장치/등판부/개구홈/측면오목부,B1
23049,20220608,C,14499,기타 의복 액세서리 제조업,그 외 기타 의복 액세서리 제조업,의복 액세서리 제조업,14,A41D-019/00,144,KR,1449,제조업(10~34),kr20190002754u,2020190002754,"의복, 의복 액세서리 및 모피제품 제조업",공업용장갑제조//장갑/파지/보형물/유지/장치/공간/쥠봉/밴드,U

In [43]:
label_df.shape

(23050, 17)

In [44]:
특허_카테고리_list = label_df['Ltext'].unique().tolist()
특허_카테고리_list

['임업',
 '어업',
 '농업',
 '석탄, 원유 및 천연가스 광업',
 '광업 지원 서비스업',
 '금속 광업',
 '비금속광물 광업; 연료용 제외',
 '산업용 기계 및 장비 수리업',
 '화학 물질 및 화학제품 제조업; 의약품 제외',
 '전자 부품, 컴퓨터, 영상, 음향 및 통신장비 제조업',
 '코크스, 연탄 및 석유정제품 제조업',
 '고무 및 플라스틱제품 제조업',
 '자동차 및 트레일러 제조업',
 '기타 운송장비 제조업',
 '목재 및 나무제품 제조업; 가구 제외',
 '펄프, 종이 및 종이제품 제조업',
 '음료 제조업',
 '비금속 광물제품 제조업',
 '인쇄 및 기록매체 복제업',
 '금속 가공제품 제조업; 기계 및 가구 제외',
 '의료용 물질 및 의약품 제조업',
 '의료, 정밀, 광학 기기 및 시계 제조업',
 '기타 제품 제조업',
 '담배 제조업',
 '기타 기계 및 장비 제조업',
 '가구 제조업',
 '식료품 제조업',
 '1차 금속 제조업',
 '전기장비 제조업',
 '섬유제품 제조업; 의복 제외',
 '가죽, 가방 및 신발 제조업',
 '의복, 의복 액세서리 및 모피제품 제조업']

In [45]:
len(특허_카테고리_list)

32

# 중복된 값 제거

In [46]:
# raw_df에서 중복된 application_number 확인
print(raw_df['application_number'].duplicated().sum())

# label_df에서 중복된 application_number 확인
print(label_df['application_number'].duplicated().sum())

3538
3538

In [47]:
# 중복된 application_number 찾기
duplicate_application_numbers = raw_df[raw_df['application_number'].duplicated()]['application_number'].unique()
duplicate_application_numbers

array(['1020210033985', '1020200152106', '1020200088844', ...,
       '1020190109607', '1020190106033', '2020190002754'], dtype=object)

In [48]:
duplicate_rows = raw_df[raw_df['application_number'].isin(['1020190179476'])]

In [49]:
duplicate_rows

,application_year,invention_title,ipc_section,register_date,abstract,ipc_subclass,ipc_main,register_year,ipc_all,ipc_class,claims,application_date,register_number,documentId,application_number,open_number,open_date,open_year,applicant_name
1617,2019,회처리 설비용 철편 분리 장치,B,NaN,"본 발명은 회처리 설비용 철편 분리 장치에 관한 것으로, 석탄회(비회, 저회)의 이...",B03C,B03C-001/28,NaN,B03C-001/28||B03C-001/30||F16B-005/02||G08B-00...,B03,석탄회를 이송하는 관로에 외부가 통하도록 개방되는 철편 분리공간을 밀폐하며 상기 관...,20191231,NaN,kr20190179476a,1020190179476,1020210085907,NaN,NaN,NaN
1618,2019,회처리 설비용 철편 분리 장치,B,20211014,"본 발명은 회처리 설비용 철편 분리 장치에 관한 것으로, 석탄회(비회, 저회)의 이...",B03C,B03C-001/28,2021,B03C-001/28||B03C-001/30||F16B-005/02||G08B-00...,B03,석탄회를 이송하는 관로에 외부가 통하도록 개방되는 철편 분리공간을 밀폐하며 상기 관...,20191231,102315240,kr20190179476b1,1020190179476,NaN,NaN,NaN,NaN
1814,2019,회처리 설비용 철편 분리 장치,B,NaN,"본 발명은 회처리 설비용 철편 분리 장치에 관한 것으로, 석탄회(비회, 저회)의 이...",B03C,B03C-001/28,NaN,B03C-001/28||B03C-001/30||F16B-005/02||G08B-00...,B03,석탄회를 이송하는 관로에 외부가 통하도록 개방되는 철편 분리공간을 밀폐하며 상기 관...,20191231,NaN,kr20190179476a,1020190179476,1020210085907,NaN,NaN,NaN

In [50]:
# raw_df에서 application_number 기준으로 중복된 행 제거
raw_df_unique = raw_df.drop_duplicates(subset='application_number', keep='first')

# label_df에서 application_number 기준으로 중복된 행 제거
label_df_unique = label_df.drop_duplicates(subset='application_number', keep='first')

In [51]:
raw_df_unique.shape

(19512, 19)

In [52]:
label_df_unique.shape

(19512, 17)

In [53]:
merged_df = pd.merge(raw_df_unique, label_df_unique, on='application_number', how='inner')
merged_df

,application_year,invention_title,ipc_section,register_date,abstract,ipc_subclass,ipc_main_x,register_year,ipc_all,ipc_class,...,Lno,ipc_main_y,Mno,country_code,Sno,LLtext,documentId_y,Ltext,keyword,document_type
0,2021,수목 보호 지지대,A,20210609,"본 발명은 수목 보호 지지대에 관한 것으로, 지면에 하단이 고정되는 다수의 버팀부재...",A01G,A01G-017/14,2021,A01G-017/14||A01G-017/10||A01G-009/12,A01,...,02,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210033985b1,임업,산림관리/임야수목관리/수목보호지지대/버팀부재/밀착부재/고정위치를용이하게조정/장치/중...,B1
1,2021,나무보호장치,A,NaN,강풍에 나무들이나 전봇대들이 뽑히거나 부러지고 넘어져서 피해를 입는 사고가 많다. ...,A01G,A01G-017/14,NaN,A01G-017/14||A01G-009/12,A01,...,02,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210000760u,임업,산림관리/산림조림/나무보호장치/땅속과나무에설치/미관상문제해결/사고예방/장치/기초보호...,U
2,2021,수목 관리 장치 및 시스템,A,20210423,"본 발명은 수목 관리 장치 및 시스템에 관한 것으로, 더욱 상세하게는 수목을 안정적...",A01G,A01G-017/14,2021,A01G-017/14||A01G-027/00||F21S-008/08||F21S-00...,A01,...,02,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210006694b1,임업,산림관리/임야수목관리/수목관리장치/안정적지지/유수공급/수목효율적관리/장치/입수부/조...,B1
3,2021,휴대용 나무 안정지지대,A,20210601,"본 발명은 휴대용 나무 안정지지대에 관한 것으로서, 회동축(A)을 중심으로 크로스 ...",A01G,A01G-023/04,2021,A01G-023/04||A01G-017/14,A01,...,02,A01G-023/04,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210001336b1,임업,산림관리/산림조림/안정지지대/지지바아/각도구속부/휴대용안정지지대/장치/제1지지바아/...,B1
4,2020,수목보호용 블록,A,20210611,본 발명은 블록의 조립에 의해 이루어진 식재 공간 내부에 식재되는 수목의 위치에 맞...,A01G,A01G-013/02,2021,A01G-013/02||C04B-020/00||C04B-028/02||E01C-00...,A01,...,02,A01G-013/02,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20200152106b1,임업,산림관리/임야수목관리/블록/천연골재로제작/식재공간변형/물고임방지/장치/결합홈/결합돌...,B1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19461,2019,운동용 파워 벨트부재의 제조방법 및 이를 이용한 운동용 허리벨트,A,NaN,본 발명은 운동용 파워 벨트부재의 제조방법 및 이를 이용한 운동용 허리벨트에 관한 ...,A41F,A41F-009/00,NaN,A41F-009/00||A41D-013/05||A41D-027/06,A41,...,14,A41F-009/00,144,KR,1449,제조업(10~34),kr20190112005a,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//벨트/메쉬/압박대/운동/방법/원단/중첩부/재봉부,A
19462,2019,"버클, 벨트 및 벨트 부품",A,NaN,"피복의 흘러내림을 억제하는 벨트 버클로서, 벨트의 일단이 고정된 버클 본체와, 버클...",A41F,A41F-009/00,NaN,A41F-009/00||A41F-017/02||A44B-011/00||A44B-01...,A41,...,14,A41F-009/00,144,KR,1449,제조업(10~34),kr20207036302a,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//벨트/피복/고정/억제/조성물/버클본체/계지부/계합부,A
19463,2019,히든 벨트,A,NaN,"본 발명은 히든벨트에 대한 것으로서, 본 발명의 일실시예에 따른 벨트는 고정부와 긴...",A41F,A41F-009/02,NaN,A41F-009/02||A41F-009/00,A41,...,14,A41F-009/02,144,KR,1449,제조업(10~34),kr20190092477a,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//벨트/고정부/긴띠/고정/조성물/조절/고리/스프링클립,A
19464,2019,버클 전자 장치를 포함하는 스마트 벨트,A,NaN,"본 발명의 실시 예에 따른 스마트 벨트는, 착용 부위의 복부 압력 및 자세 기울기를...",A41F,A41F-009/00,NaN,A41F-009/00||A44B-011/00||A61B-005/00||A61B-00...,A41,...,14,A41F-009/00,144,KR,1449,제조업(10~34),kr20190085948a,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//스마트벨트/접촉부/압력/자세교정/장치/버클/밴드/경고신호,A
19465,2019,앞 쳐짐을 방지하는 작업용 조끼,A,20200602,"본 발명은 작업용조끼에 관한 것으로, 특히 작업용조끼의 전면에 공구 등의 중량체를 ...",A41D,A41D-001/04,2020,A41D-001/04||A41D-027/20,A41,...,14,A41D-001/04,144,KR,1449,제조업(10~34),kr20190084129b1,"의복, 의복 액세서리 및 모피제품 제조업",의류액세서리제조//조끼/견갑골/무게하중/착용감/장치/등판부/개구홈/측면오목부,B1

In [54]:
merged_df.shape

(19466, 35)

In [55]:
def extract_fields(row):
    # 각 행(row)에서 필요한 필드를 추출
    invention_title = row.get('invention_title', '')
    abstract = row.get('abstract', '')
    claims = row.get('claims', '')

    # 추출한 내용을 하나의 문자열로 연결
    result = f"invention_title: {invention_title} abstract: {abstract} claims: {claims}"

    return result

# apply 함수를 사용하여 merged_df의 각 행에 대해 extract_fields 함수를 적용
merged_df['combined_string'] = merged_df.apply(extract_fields, axis=1)

# 결과 출력 (예시로 첫 5개의 결과 출력)
merged_df[['invention_title', 'abstract', 'claims', 'combined_string']].head()

,invention_title,abstract,claims,combined_string
0,수목 보호 지지대,"본 발명은 수목 보호 지지대에 관한 것으로, 지면에 하단이 고정되는 다수의 버팀부재...","수목(100)의 둘레 면에 접촉되는 다수의 밀착부재(2)와, 상기 밀착부재(2)를 ...",invention_title: 수목 보호 지지대 abstract: 본 발명은 수목 ...
1,나무보호장치,강풍에 나무들이나 전봇대들이 뽑히거나 부러지고 넘어져서 피해를 입는 사고가 많다. ...,'기초보호대' 와 '땅속지지대' 를 땅속에 설치하여 강풍에 나무가 옆으로 기울거나 ...,invention_title: 나무보호장치 abstract: 강풍에 나무들이나 전봇...
2,수목 관리 장치 및 시스템,"본 발명은 수목 관리 장치 및 시스템에 관한 것으로, 더욱 상세하게는 수목을 안정적...","수목(1)을 감싸도록 주변에 설치되어 수목(1)을 지지하고, 유수를 집수하여 수목(...",invention_title: 수목 관리 장치 및 시스템 abstract: 본 발명...
3,휴대용 나무 안정지지대,"본 발명은 휴대용 나무 안정지지대에 관한 것으로서, 회동축(A)을 중심으로 크로스 ...","회동축(A)을 중심으로 크로스 결합된 것으로서, 땅(E)에 지지되어 이식 대기중인 ...",invention_title: 휴대용 나무 안정지지대 abstract: 본 발명은 ...
4,수목보호용 블록,본 발명은 블록의 조립에 의해 이루어진 식재 공간 내부에 식재되는 수목의 위치에 맞...,수목의 주위에 설치되어 수목이 설치된 지반의 흙이 외부로 흩어지는 것을 방지하는 수...,invention_title: 수목보호용 블록 abstract: 본 발명은 블록의 ...

In [56]:
merged_df

,application_year,invention_title,ipc_section,register_date,abstract,ipc_subclass,ipc_main_x,register_year,ipc_all,ipc_class,...,ipc_main_y,Mno,country_code,Sno,LLtext,documentId_y,Ltext,keyword,document_type,combined_string
0,2021,수목 보호 지지대,A,20210609,"본 발명은 수목 보호 지지대에 관한 것으로, 지면에 하단이 고정되는 다수의 버팀부재...",A01G,A01G-017/14,2021,A01G-017/14||A01G-017/10||A01G-009/12,A01,...,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210033985b1,임업,산림관리/임야수목관리/수목보호지지대/버팀부재/밀착부재/고정위치를용이하게조정/장치/중...,B1,invention_title: 수목 보호 지지대 abstract: 본 발명은 수목 ...
1,2021,나무보호장치,A,NaN,강풍에 나무들이나 전봇대들이 뽑히거나 부러지고 넘어져서 피해를 입는 사고가 많다. ...,A01G,A01G-017/14,NaN,A01G-017/14||A01G-009/12,A01,...,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210000760u,임업,산림관리/산림조림/나무보호장치/땅속과나무에설치/미관상문제해결/사고예방/장치/기초보호...,U,invention_title: 나무보호장치 abstract: 강풍에 나무들이나 전봇...
2,2021,수목 관리 장치 및 시스템,A,20210423,"본 발명은 수목 관리 장치 및 시스템에 관한 것으로, 더욱 상세하게는 수목을 안정적...",A01G,A01G-017/14,2021,A01G-017/14||A01G-027/00||F21S-008/08||F21S-00...,A01,...,A01G-017/14,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210006694b1,임업,산림관리/임야수목관리/수목관리장치/안정적지지/유수공급/수목효율적관리/장치/입수부/조...,B1,invention_title: 수목 관리 장치 및 시스템 abstract: 본 발명...
3,2021,휴대용 나무 안정지지대,A,20210601,"본 발명은 휴대용 나무 안정지지대에 관한 것으로서, 회동축(A)을 중심으로 크로스 ...",A01G,A01G-023/04,2021,A01G-023/04||A01G-017/14,A01,...,A01G-023/04,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20210001336b1,임업,산림관리/산림조림/안정지지대/지지바아/각도구속부/휴대용안정지지대/장치/제1지지바아/...,B1,invention_title: 휴대용 나무 안정지지대 abstract: 본 발명은 ...
4,2020,수목보호용 블록,A,20210611,본 발명은 블록의 조립에 의해 이루어진 식재 공간 내부에 식재되는 수목의 위치에 맞...,A01G,A01G-013/02,2021,A01G-013/02||C04B-020/00||C04B-028/02||E01C-00...,A01,...,A01G-013/02,020,KR,0201,"농업, 임업 및 어업(01~03)",kr20200152106b1,임업,산림관리/임야수목관리/블록/천연골재로제작/식재공간변형/물고임방지/장치/결합홈/결합돌...,B1,invention_title: 수목보호용 블록 abstract: 본 발명은 블록의 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19461,2019,운동용 파워 벨트부재의 제조방법 및 이를 이용한 운동용 허리벨트,A,NaN,본 발명은 운동용 파워 벨트부재의 제조방법 및 이를 이용한 운동용 허리벨트에 관한 ...,A41F,A41F-009/00,NaN,A41F-009/00||A41D-013/05||A41D-027/06,A41,...,A41F-009/00,144,KR,1449,제조업(10~34),kr20190112005a,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//벨트/메쉬/압박대/운동/방법/원단/중첩부/재봉부,A,invention_title: 운동용 파워 벨트부재의 제조방법 및 이를 이용한 운동...
19462,2019,"버클, 벨트 및 벨트 부품",A,NaN,"피복의 흘러내림을 억제하는 벨트 버클로서, 벨트의 일단이 고정된 버클 본체와, 버클...",A41F,A41F-009/00,NaN,A41F-009/00||A41F-017/02||A44B-011/00||A44B-01...,A41,...,A41F-009/00,144,KR,1449,제조업(10~34),kr20207036302a,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//벨트/피복/고정/억제/조성물/버클본체/계지부/계합부,A,"invention_title: 버클, 벨트 및 벨트 부품 abstract: 피복의 ..."
19463,2019,히든 벨트,A,NaN,"본 발명은 히든벨트에 대한 것으로서, 본 발명의 일실시예에 따른 벨트는 고정부와 긴...",A41F,A41F-009/02,NaN,A41F-009/02||A41F-009/00,A41,...,A41F-009/02,144,KR,1449,제조업(10~34),kr20190092477a,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//벨트/고정부/긴띠/고정/조성물/조절/고리/스프링클립,A,invention_title: 히든 벨트 abstract: 본 발명은 히든벨트에 대...
19464,2019,버클 전자 장치를 포함하는 스마트 벨트,A,NaN,"본 발명의 실시 예에 따른 스마트 벨트는, 착용 부위의 복부 압력 및 자세 기울기를...",A41F,A41F-009/00,NaN,A41F-009/00||A44B-011/00||A61B-005/00||A61B-00...,A41,...,A41F-009/00,144,KR,1449,제조업(10~34),kr20190085948a,"의복, 의복 액세서리 및 모피제품 제조업",벨트제조//스마트벨트/접촉부/압력/자세교정/장치/버클/밴드/경고신호,A,invention_title: 버클 전자 장치를 포함하는 스마트 벨트 abstrac...
19465,2019,앞 쳐짐을 방지하는 작업용 조끼,A,20200602,"본 발명은 작업용조끼에 관한 것으로, 특히 작업용조끼의 전면에 공구 등의 중량체를 ...",A41D,A41D-001/04,2020,A41D-001/04||A41D-027/20,A41,...,A41D-001/04,144,KR,1449,제조업(10~34),kr20190084129b1,"의복, 의복 액세서리 및 모피제품 제조업",의류액세서리제조//조끼/견갑골/무게하중/착용감/장치/등판부/개구홈/측면오목부,B1,invention_title: 앞 쳐짐을 방지하는 작업용 조끼 abstract: 본...

In [57]:
test_data_df = merged_df[['application_number', 'combined_string', 'Ltext']]
test_data_df

,application_number,combined_string,Ltext
0,1020210033985,invention_title: 수목 보호 지지대 abstract: 본 발명은 수목 ...,임업
1,2020210000760,invention_title: 나무보호장치 abstract: 강풍에 나무들이나 전봇...,임업
2,1020210006694,invention_title: 수목 관리 장치 및 시스템 abstract: 본 발명...,임업
3,1020210001336,invention_title: 휴대용 나무 안정지지대 abstract: 본 발명은 ...,임업
4,1020200152106,invention_title: 수목보호용 블록 abstract: 본 발명은 블록의 ...,임업
...,...,...,...
19461,1020190112005,invention_title: 운동용 파워 벨트부재의 제조방법 및 이를 이용한 운동...,"의복, 의복 액세서리 및 모피제품 제조업"
19462,1020207036302,"invention_title: 버클, 벨트 및 벨트 부품 abstract: 피복의 ...","의복, 의복 액세서리 및 모피제품 제조업"
19463,1020190092477,invention_title: 히든 벨트 abstract: 본 발명은 히든벨트에 대...,"의복, 의복 액세서리 및 모피제품 제조업"
19464,1020190085948,invention_title: 버클 전자 장치를 포함하는 스마트 벨트 abstrac...,"의복, 의복 액세서리 및 모피제품 제조업"
19465,1020190084129,invention_title: 앞 쳐짐을 방지하는 작업용 조끼 abstract: 본...,"의복, 의복 액세서리 및 모피제품 제조업"

In [58]:
# '농업', '임업', '어업' 데이터만 추출
filtered_df = test_data_df[test_data_df['Ltext'].isin(['농업', '임업', '어업'])]
filtered_df

,application_number,combined_string,Ltext
0,1020210033985,invention_title: 수목 보호 지지대 abstract: 본 발명은 수목 ...,임업
1,2020210000760,invention_title: 나무보호장치 abstract: 강풍에 나무들이나 전봇...,임업
2,1020210006694,invention_title: 수목 관리 장치 및 시스템 abstract: 본 발명...,임업
3,1020210001336,invention_title: 휴대용 나무 안정지지대 abstract: 본 발명은 ...,임업
4,1020200152106,invention_title: 수목보호용 블록 abstract: 본 발명은 블록의 ...,임업
...,...,...,...
1145,1020200133095,invention_title: 수경재배기 abstract: 본 발명은 수경재배기에 ...,농업
1146,1020200133158,invention_title: 분무식 수경 재배장치 abstract: 본 발명은 본...,농업
1147,1020200133159,invention_title: 재배용 포트 abstract: 본 발명은 상하가 개방...,농업
1148,1020200121174,invention_title: 거치용 식물 재배 장치 abstract: 본 발명에 ...,농업
1149,1020200111002,invention_title: 떡차 및 그의 제조 방법 abstract: 본 발명은...,농업

In [59]:
import csv

# 1. 기존 CSV 파일을 읽어서 application_number 목록을 추출
try:
    existing_df = pd.read_csv('test_output.csv', encoding='utf-8')
    existing_app_numbers = set(existing_df['application_number'].astype(str))
except FileNotFoundError:
    # 파일이 없을 경우 빈 set으로 초기화
    existing_app_numbers = set()

In [ ]:
total_num = len(filtered_df)

# 2. 새 데이터를 추가할 CSV 파일을 연다
with open('test_output.csv', mode='a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file, quoting=csv.QUOTE_MINIMAL)

    # 3. 데이터프레임 순회하면서 application_number가 중복되지 않으면 추가
    for i, (index, row) in enumerate(filtered_df.iterrows()):
        app_number = str(row['application_number'])  # 문자열로 변환하여 비교
        if app_number not in existing_app_numbers:
            llama3_1_inference_result = generate_response(system_message=system_prompt,
                                          user_message=row['combined_string'],
                                          tokenizer=tokenizer,
                                          model=model)

            writer.writerow([i, row['application_number'], row['combined_string'], row['Ltext'], llama3_1_inference_result])
            print(f"{i}/{total_num} Row {i}: application_number: {row['application_number']}, combined_string: {row['combined_string']}, Ltext: {row['Ltext']}, prediction: {llama3_1_inference_result}")
            existing_app_numbers.add(app_number)  # 새로 추가된 번호는 추적
        else:
            print(f"Skipping Row {i}: application_number {row['application_number']} already exists.")

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

0/1059 Row 0: application_number: 1020210033985, combined_string: invention_title: 수목 보호 지지대 abstract: 본 발명은 수목 보호 지지대에 관한 것으로, 지면에 하단이 고정되는 다수의 버팀부재의 상단을 용이하게 고정시키는 본체 및 수목의 둘레 면에 접하여 지지하는 다수의 밀착부재 그리고 상기 버팀부재 및 밀착부재를 안정적으로 본체에 장착될 수 있도록 개량한 구조가 간결하게 이루어짐으로써 생산성 향상과 간편하게 설치할 수 있는 작업의 효율성을 높일 수 있고, 안정적으로 수목이 성장되도록 지지함은 물론 수목의 성장에 따른 굵기(체적)의 변화에 따른 밀착부재의 고정위치를 용이하게 조정할 수 있도록 이루어지는 수목 보호 지지대에 관한 것이다. claims: 수목(100)의 둘레 면에 접촉되는 다수의 밀착부재(2)와, 상기 밀착부재(2)를 안착시키면서 수목(100)을 중앙에 위치시키도록 일측이 개방된 중공부(11)를 갖는 본체(1)와, 상기 본체(1)의 개방부분을 폐쇄하는 고정편(3) 및 상기 본체(1)에 상단이 고정되고 하단이 지면에 고정되는 다수의 버팀부재(4)로 이루어진 수목 보호 지지대에 있어서,상기 본체(1)는 수목(100)이 위치하는 중공부(11)를 기준으로 3~4개소에 상기 버팀부재(4)의 상단이 돌출되면서 끼워지도록 천공된 다수의 끼움구멍(12)과, 이 끼움구멍(12)과 끼움구멍(12) 사이에 형성되어 상기 밀착부재(2)를 고정하는 고정볼트가 체결되는 나사공(13) 및 이탈을 방지하면서 수목(100)의 중심으로 직선 이동할 수 있도록 밀착부재(2)를 안내하는 가이드편(14)이 돌출 형성되어 이루어지고;상기 고정편(3)은 고정볼트에 의해 장착되어 본체(1)의 개방부분을 폐쇄하면서 내구성을 증대시키고 상기 밀착부재(2)를 고정하는 고정볼트가 체결되는 나사공(31) 및 이탈을 방지하면서 수목(100)의 중심으로 직선 이동할 수 있도록 밀착부재(2)를 안내하는 가이드편(32)이 돌출 형성되어 이루어지며;상기 밀착부재(2)는 수목(100)의 둘레 면에 접하여 지지하는 수직부(21)와, 상기 본체(1)의 나사공(13) 및 가이드편(14) 그리고 상기 고정편(3)의 나사공(31) 및 가이드편(32) 위치에 안착되면서 고정볼트에 의해 본체(1) 상부면에 고정되도록 장공(23)이 천공된 수평부(22)로 이루어지고;상기 본체(1)에 형성된 다수의 끼움구멍(12) 하측으로 지지편(15)이 하향 돌출 형성되고, 이 지지편(15)에 상기 다수의 버팀부재(4)의 상단이 접촉된 상태로 고정되도록 이루어진 것을 특징으로 하는 수목 보호 지지대., Ltext: 임업, prediction: 임업
1/1059 Row 1: application_number: 1020210012264, combined_string: invention_title: 스마트 캠핑장 관리 시스템 abstract: 본 발명은 스마트 캠핑장 관리 시스템에 관한 것으로, 보다 상세하게는 캠핑장마다 무선인터넷 환경을 구축하여 캠핑장마다 고유의 컨텐츠를 제공하며, 캠핑장의 방역과 안전을 위해 비대면 출입통제 및 동선관리가 가능한 스마트 캠핑장 관리 시스템을 제공하는 것이다. claims: 원격지에 설치된 복수의 스마트 캠핑장을 관리하는 시스템으로,복수의 스마트 캠핑장 식별정보와 각 스마트 캠핑장 내부에 서로 이격되게 설치되는 복수의 액세스 포인트(AP) 식별정보를 저장하며, 사용자통신단말에서 와이파이 접속 앱(APP)을 실행하여 생성한 일회용 패스워드 정보를 캠핑장 PC로부터 수신하면 상기 일회용 패스워드 정보의 유효성을 인증하고 인증 결과를 캠핑장 PC로 전송하는 인증서버; 관리자의 조작에 따라 복수의 스마트 캠핑장 내부에 설치된 복수의 액세스 포인트(AP) 식별정보를 입력받아 저장하며 이를 상기 인증서버로 전송하고, 캠핑장 PC로부터 스마트 캠핑장 식별정보와 액세스 포인트(AP) 식별정보와 접속된 사용자정보와 시간정보를 입력받아 저장하며, 상기 스마트 캠핑장 식별정보와 액세스 포인트(AP) 식별정보와 사용자정보 및 시간정보를 수집 및 분석하여 각 스마트 캠핑장의 사용빈도에 관한 통계정보를 생성하여 저장하는 관리서버;스마트 캠핑장 식별정보를 포함하는 복수의 스마트 캠핑장 정보와 각 스마트 캠핑장별 컨텐츠정보를 생성, 저장 또는 편집하고, 상기 생성, 저장 또는 편집된 복수의 스마트 캠핑장 정보와 스마트 캠핑장별 컨텐츠정보를 해당 캠핑장 PC로 전송하는 컨텐츠 제공서버;스마트 캠핑장 식별정보를 포함하는 복수의 스마트 캠핑장 정보와 광고 정보를 저장하고, 상기 관리서버에 저장된 각 스마트 캠핑장의 사용빈도에 관한 통계정보를 이용하여 광고 송출 기준을 만족하는 스마트 캠핑장이 있는지를 판단하고, 판단결과 긍정인 해당 캠핑장 PC로 광고 정보를 전송하는 광고서버; 및복수의 스마트 캠핑장 식별정보와 예약 정보를 저장하고, 사용자통신단말로 예약안내정보를 전송하고 사용자가 선택한 스마트 캠핑장정보와 예약날짜와 전체 이용자정보가 입력되면 이를 저장하고, 사용자가 선택한 스마트 캠핑장에 대응하는 와이파이 접속 앱(APP)을 다운받도록 안내하는 연결정보를 사용자통신단말로 전송하는 예약서버를 포함하며,상기 컨텐츠정보는, 각 스마트 캠핑장의 일교차, 지리적 정보, 유해 동물 및 유해 곤충이 출몰하는 위험지역에 대한 정보 및 캠핑장 시설에 대한 정보를 포함하는 캠핑장 정보와, 캠핑 장비들의 설치 방법과 사용 방법을 포함하는 캠핑 장비 이용 정보와, 캠핑장에서 먹을 수 있는 요리의 정보를 포함하는 캠핑 조리 정보 및 스마트 캠핑장에서 제작한 게임정보를 포함하는 것을 특징으로 하는,스마트 캠핑장 관리시스템., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

2/1059 Row 2: application_number: 1020210012672, combined_string: invention_title: 컨테이너 조경수 생산 및 유통 관리를 위한 ERP 시스템과 그 방법 abstract: 본 발명은 컨테이너 조경수 생산 및 유통 관리를 위한 ERP 시스템과 그 방법을 개시한다. 즉, 본 발명은 컨테이너에서 재배되는 수목인 컨테이너 조경수의 생육 데이터, 환경 데이터 등을 근거로 딥러닝 또는 기계 학습을 통해 생육 데이터를 예측하고, 생산성 환경을 분석하여, 최적의 조경수 생산을 위한 생산성 환경을 추천함으로써, 데이터 기반의 표준화된 조경수 데이터베이스를 구축하고, 조경수 생산을 위한 스마트 재배 시스템의 전체 운영 효율을 향상시킬 수 있다. claims: 앱 실행 결과 화면 중에서 미리 설정된 생육 예측 데이터 메뉴가 선택될 때, 조경수에 대한 생육과 관련한 예측 데이터를 확인하기 위한 생육 예측 데이터 화면을 표시하고, 썸네일 형태로 표시되는 복수의 조경수 중에서 어느 하나의 특정 조경수가 선택될 때, 상기 선택된 특정 조경수에 대응하는 생육 예측 데이터를 표시하는 단말;상기 단말의 요청에 따라 복수의 조경수의 고유 식별 정보별 생육 예측 데이터 중에서 상기 조경수의 고유 식별 정보에 대응하는 생육 예측 데이터를 확인하고, 상기 확인된 상기 조경수의 고유 식별 정보에 대응하는 생육 예측 데이터를 상기 단말에 제공하는 ERP 서버; 특정 조경수와 관련한 영상 정보, 생육 데이터 및 환경 데이터를 수집하는 데이터 수집부; 및복수의 조경수로 구성된 농장의 환경을 제어하는 스마트 재배 시스템을 포함하며,상기 ERP 서버는,상기 데이터 수집부로부터 전송되는 특정 조경수와 관련한 영상 정보, 생육 데이터 및 환경 데이터를 수신하고, 상기 영상 정보에 포함된 특정 조경수를 미리 설정된 수형 이미지 분류 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 영상 정보에 포함된 특정 조경수의 수형, 높이, 너비 및 생태학적 분류와 이용상의 분류와 생육 환경에 따른 분류를 포함하는 상기 특정 조경수의 분류를 확인하고, 상기 스마트 재배 시스템과 연동하여 상기 특정 조경수와 관련한 고유 식별 정보 및 조경수 관리 데이터를 수집하고, 상기 영상 정보, 생육 데이터 및 환경 데이터를 표준화하고, 표준화된 규격의 조경수 데이터베이스를 구축하고, 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생육 데이터 예측 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생육과 관련한 생육 예측 데이터를 생성하고, 상기 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생산성 환경 분석 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생산 환경과 관련한 분석 결과를 생성하고, 상기 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생산성 환경 추천 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생산 환경과 관련한 추천 결과를 생성하며,상기 단말은,상기 표시되는 앱 실행 결과 화면 중에서 미리 설정된 스마트 재배 제어 메뉴가 선택될 때, 특정 조경수에 대한 생장에 필요한 단계별 작업 관리를 위한 스마트 재배 제어 화면을 표시하고, 상기 ERP 서버 및 상기 스마트 재배 시스템과 연동하여, 상기 단말에 표시되는 스마트 재배 제어 화면에서 관리자 입력에 따라 상기 농장에 구성된 하나 이상의 관리 장치의 작동을 제어하며,상기 표준화된 규격은,생태학적 분류, 이용상의 분류 및 생육 환경에 따른 분류를 포함하는 조경수의 분류와, 조경수목 사진과, 높이와, 너비를 포함하며,상기 농장에 구성된 하나 이상의 관리 장치는,온도 관리 장치, 수분 관리 장치, 차광 관리 장치, 관수 관리 장치, 시비 관리 장치, 제초 관리 장치, 병충해 관리 장치, 수형 관리 장치, 풍해 관리 장치 및 월동 관리 장치를 포함하는 것을 특징으로 하는 컨테이너 조경수 생산 및 유통 관리를 위한 ERP 시스템.단말에 의해, 앱 실행 결과 화면에서 미리 설정된 영상 확인 메뉴가 선택될 때, 농장에 설치된 복수의 카메라를 통해 실시간으로 조경수의 상태를 확인하기 위한 영상 확인 화면을 표시하는 단계;상기 단말의 영상 확인 화면 내의 농장의 지도상에 표시되는 복수의 카메라 중에서 어느 하나의 카메라가 선택될 때, 상기 단말에 의해, 상기 선택된 카메라로부터 획득되는 실시간 영상 정보를 표시하는 단계;상기 앱 실행 결과 화면 중에서 미리 설정된 생육 예측 데이터 메뉴가 선택될 때, 상기 단말에 의해, 조경수에 대한 생육과 관련한 예측 데이터를 확인하기 위한 생육 예측 데이터 화면을 표시하는 단계;상기 단말의 생육 예측 데이터 화면 내의 농장의 지도상에 표시되는 복수의 조경수 중에서 어느 하나의 특정 조경수가 선택될 때, 상기 단말에 의해, ERP 서버와 연동하여, 상기 선택된 특정 조경수에 대응하는 생육 예측 데이터를 표시하는 단계; 데이터 수집부에 의해, 특정 조경수와 관련한 영상 정보, 생육 데이터 및 환경 데이터를 수집하는 단계;상기 ERP 서버에 의해, 상기 데이터 수집부로부터 전송되는 특정 조경수와 관련한 영상 정보, 생육 데이터 및 환경 데이터를 수신하는 단계;상기 ERP 서버에 의해, 상기 영상 정보에 포함된 특정 조경수를 미리 설정된 수형 이미지 분류 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 영상 정보에 포함된 특정 조경수의 수형, 높이, 너비 및 분류를 확인하는 단계;상기 ERP 서버에 의해, 복수의 조경수로 구성된 농장의 환경을 제어하는 스마트 재배 시스템과 연동하여, 상기 특정 조경수와 관련한 고유 식별 정보 및 조경수 관리 데이터를 수집하는 단계;상기 ERP 서버에 의해, 상기 영상 정보, 생육 데이터 및 환경 데이터를 표준화하고, 표준화된 규격의 조경수 데이터베이스를 구축하는 단계;상기 ERP 서버에 의해, 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생육 데이터 예측 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생육과 관련한 생육 예측 데이터를 생성하는 단계;상기 ERP 서버에 의해, 상기 특정 조경수와 관련한 고유 식별 정보와 상기 생성된 생육 예측 데이터를 매핑하여 저장하는 단계;상기 ERP 서버에 의해, 상기 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생산성 환경 분석 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생산 환경과 관련한 분석 결과를 생성하는 단계;상기 ERP 서버에 의해, 상기 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생산성 환경 추천 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생산 환경과 관련한 추천 결과를 생성하는 단계;상기 ERP 서버에 의해, 상기 특정 조경수와 관련한 고유 식별 정보와 상기 생성된 분석 결과와 상기 생성된 추천 결과를 매핑하여 저장하는 단계;상기 표시되는 앱 실행 결과 화면 중에서 미리 설정된 스마트 재배 제어 메뉴가 선택될 때, 상기 단말에 의해, 특정 조경수에 대한 생장에 필요한 단계별 작업 관리를 위한 스마트 재배 제어 화면을 표시하는 단계; 및상기 단말에 의해, 상기 ERP 서버 및 상기 스마트 재배 시스템과 연동하여, 상기 단말에 표시되는 스마트 재배 제어 화면에서 관리자 입력에 따라 상기 농장에 구성된 하나 이상의 관리 장치의 작동을 제어하는 단계를 포함하며,상기 영상 정보에 포함된 특정 조경수의 수형, 높이, 너비 및 분류를 확인하는 단계는,상기 기계 학습 수행에 따라 생태학적 분류, 이용상의 분류 및 생육 환경에 따른 분류를 포함하는 상기 특정 조경수의 분류를 확인하며,상기 표준화된 규격은,생태학적 분류, 이용상의 분류 및 생육 환경에 따른 분류를 포함하는 조경수의 분류와, 조경수목 사진과, 높이와, 너비를 포함하며,상기 농장에 구성된 하나 이상의 관리 장치는,온도 관리 장치, 수분 관리 장치, 차광 관리 장치, 관수 관리 장치, 시비 관리 장치, 제초 관리 장치, 병충해 관리 장치, 수형 관리 장치, 풍해 관리 장치 및 월동 관리 장치를 포함하는 것을 특징으로 하는 컨테이너 조경수 생산 및 유통 관리를 위한 ERP 방법., Ltext: 임업, prediction: 임업
3/1059 Row 3: application_number: 1020200178788, combined_string: invention_title: 음파 및 IoT 기반의 농작물 생장 제어 및 병해충 방제 시스템 abstract: 본 발명은 시설재배지의 농작물의 생장 환경 정보를 생성하는 온습도센서, 조도 센서, 진동 센서, 적외선 센서, 초음파 센서 및 이산화탄소(CO2) 측정센서 및 재배농작물의 영상을 촬영하여 촬영영상을 생성하는 영상 센서를 포함하는 멀티 센서 모듈(10); 상기 멀티 센서 모듈로부터 생성된 농작물의 생장 환경 정보 및 촬영 영상에 기초하여 판단된 상기 농작물의 생장 단계 또는 병해충의 종류에 따라 상이한 주파수를 갖는 음파를 방사시키는 음파 방사 모듈(20); 상기 생장 환경 정보를 선택적으로 수신하고 상기 영상센서의 촬영 영상으로부터 영상데이터를 생성하는 주제어모듈(30); 및 상기 생장 환경 정보 또는 상기 영상 데이터를 상기 주 제어모듈(30)로부터 관리 서버(50)에 유선 또는 무선으로 전송하는 통신 모듈(40)을 포함할 수 있다. claims: 시설재배지의 농작물의 생장 환경 정보를 생성하는 온습도센서, 조도 센서, 진동 센서, 적외선 센서, 초음파 센서 및 이산화탄소(CO2) 측정센서 및 재배농작물의 영상을 촬영하여 촬영영상을 생성하는 영상 센서를 포함하는 멀티 센서 모듈(10); 멀티 센서 모듈로부터 생성된 농작물의 생장 환경 정보 및 촬영 영상에 기초하여 판단된 농작물의 생장 단계 및 농장물의 생육 단계에 따라 주파수 및 음압에 대한 데이터와 병해충의 종류에 따른 방제 특성을 가진 음파에 대한 데이터가 저장된 방사 음파 데이터베이스에 기초하여 병해충의 종류에 따라 상이한 주파수를 갖는 음파를 방사시키는 음파 방사 모듈(20);생장 환경 정보를 선택적으로 수신하고 영상센서의 촬영 영상으로부터 영상데이터를 생성하는 주제어모듈(30); 및 생장 환경 정보 또는 영상 데이터를 상기 주 제어모듈(30)로부터 관리 서버(50)에 유선 또는 무선으로 전송하는 통신 모듈(40)을 포함하고, 음파는 주파수 범위가 20Hz 내지 40kHz이고 음압은 1m 이내에서 80 내지 90dB이며, 영상데이터의 특징 벡터를 추출하여 미리 저장된 병해충 데이터 베이스를 탐색하여 특정 병해충 이미지 데이터의 존재를 확인하여 후보 병해충 이미지 데이터로부터 농작물의 병해충의 발생 여부 또는 발생된 병해충의 종류를 판단하고,멀티 센서 모듈(10)에 의해 생성된 농작물의 생장 환경 정보는 멀티 센서 모듈(10)에 포함된 초음파 센서에서 발사된 초음파 펄스가 농작물의 잎이나 줄기의 표면에서 반사되어 초음파 센서로 되돌아올 때까지의 시간을 측정하여 획득한 농작물의 크기 및 도달 거리에 관한 정보를 포함하는 것을 특징으로 하는 음파 및 IoT기반의 농작물 생장 제어 및 병해충 방제 시스템., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

4/1059 Row 4: application_number: 1020200152106, combined_string: invention_title: 수목보호용 블록 abstract: 본 발명은 블록의 조립에 의해 이루어진 식재 공간 내부에 식재되는 수목의 위치에 맞추어 식재공간을 변형할 수 있을 뿐만 아니라 투수성이 우수하여 물이 고이는 것을 방지할 수 있고, 조립성이 우수하여 시공을 용이하게 할 수 있을 뿐만 아니라 천연 골재로 제작됨에 따라 다양한 색상과 변색을 방지하여 보다 미려한 수목보호용 블록에 관한 것이다. claims: 수목의 주위에 설치되어 수목이 설치된 지반의 흙이 외부로 흩어지는 것을 방지하는 수목보호용 블록(10)으로, 직육면체 형상을 이루되, 일측단부에는 단부 결합홈(10g) 또는 단부 결합돌기(10d)가 형성되고, 일측단부의 측벽에는 상기 단부 결합홈 또는 단부 결합돌기와 결합되는 측벽 결합돌기 또는 측벽 결합홈이 형성되어 네 개의 블록의 서로 다른 결합돌기와 결합홈이 서로 결합됨에 의해 사각 틀을 이루고,설치되었을 때 수목이 식재된 식재공간을 향한 부분의 상면에 커팅홈(10c)이 종횡으로 형성되어, 커팅홈이 미관을 미려하게 할 수 있을 뿐만 아니라, 고인 물을 일측으로 배출시킬 수 있고, 필요에 따라 커팅홈을 따라 일부를 뜯어내어 사용할 수 있게 한 수목보호용 블록에 있어서,상기 커팅홈(10c)이 서로 만나는 부분에는 블록을 상하로 관통하도록 관통홀(10h)이 형성되고,상기 블록의 일측에는 지지목이 끼워져 고정되는 지지목고정홈(10s)이 더 형성되고, 상기 지지목고정홈이 형성된 부분의 하부 양측에는 지지목을 관통한 고정핀이 끼워져 고정되는 핀고정홈(10p)이 형성된 것을 특징으로 하는 수목보호용 블록., Ltext: 임업, prediction: 임업
5/1059 Row 5: application_number: 1020200135202, combined_string: invention_title: 공간정보를 이용한 확률지도와 정사영상의 이미지 학습을 연계한 고사목 및 병해충 모니터링 시스템 abstract: 본 발명은 공간정보를 이용한 확률지도와 정사영상의 이미지 학습을 연계한 고사목 및 병해충 모니터링 시스템에 관한 것으로서, 본 발명은 병해충 피해목을 모니터링하기 위한 모니터링부; 및 상기 고사목 및 병해충 모니터링부로부터 제공되는 데이터를 저장하거나, 상기 고사목 및 병해충 모니터링부에 데이터를 제공하는 공간 DBMS를 포함하고, 상기 고사목 및 병해충 모니터링부는, 정사이미지와 제1 위치정보를 갖는 고사목 및 병해충 분포도를 기반으로 고사목 및 병해충 발생확률을 나타내는 제1 확률지도를 생성하는 제1 모니터링부; 및 공간 DBMS의 공간정보 및 상기 제1 위치정보를 갖는 고사목 및 병해충 분포도를 기반으로 고사목 및 병해충 발생확률을 나타내는 제2 확률지도를 생성하는 제2 모니터링부를 포함한다. claims: 고사목 및 병해충을 모니터링하기 위한 모니터링부; 및 상기 모니터링부로부터 제공되는 데이터를 저장하거나, 상기 모니터링부에 데이터를 제공하는 공간 DBMS; 및확률지도 조합부를 포함하여 구성되고, 상기 모니터링부는, 정사이미지와 제1 위치정보를 갖는 고사목 및 병해충 분포도를 기반으로 인공지능 학습방법을 이용하여 고사목 및 병해충 발생확률을 나타내는 제1 확률지도를 생성하는 제1 모니터링부; 및공간 DBMS의 공간정보 및 상기 제1 위치정보를 갖는 고사목 및 병해충 분포도를 기반으로 고사목 및 병해충 발생확률을 나타내는 제2 확률지도를 생성하는 제2 모니터링부를 포함하며,상기 확률지도 조합부는 상기 제1 확률지도 및 상기 제2 확률지도에서 동일지점의 병해충 발생확률을 미리 설정된 가중치로 연산하여 제3 확률지도를 생성하고,상기 제1모니터링부는 상기 공간DBMS에 저장된 정사이미지를 복수의 타일링 이미지로 분할하고, 분할된 타일링 이미지 각각에 대한 속성정보를 공간DBMS에 저장하며, 상기 속성정보는 병해충 발생확률 정보 및 병해충 발생영역 여부에 대한 샘플링 정보를 포함하고, 상기 샘플링 정보는 제1 위치정보에 대응하며 검출모델을 생성하는데 사용되는 제1-1 타일링 이미지, 제1 위치정보에 대응하며 검출모델을 검증하는데 사용되는 제1-2 타일링 이미지 및 제1 위치정보에 대응하지 않는 제2 타일링 이미지로 분류되고,상기 제1모니터링부의 검출모델 생성부는,제1-2 타일링 이미지에 대해 검출모델을 적용하여 병해충 발생확률을 계산하고, 병해충 발생확률이 설정값 이상일때 병해충 피해목이 위치하는 것으로 판단하며, 상기 설정값 이상의 발생확률을 갖는 제1-2 타일링 이미지의 개수 대비 제1-2 타일링 이미지의 전체 개수를 비율로 계산하고, 상기 비율이 설정값을 넘는지 비교하여 검출모델의 적합성을 판단하는 공간정보를 이용한 확률지도와 정사영상의 이미지 학습을 연계한 고사목 및 병해충 모니터링 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

6/1059 Row 6: application_number: 1020200127585, combined_string: invention_title: 패턴을 갖는 조류 충돌방지용 필름 제조방법 abstract: 본 발명은 조류 충돌방지용 필름 제조방법에 관한 것으로, 더욱 상세하게는 베이스층을 형성하는 베이스층형성단계, 상기 베이스층의 일측면에 일정 간격으로 패턴을 형성하는 패턴형성단계, 상기 패턴이 형성된 베이스층의 일측면에 접착제를 도포하는 접착제도포단계, 상기 접착제가 도포된 베이스층의 일측으로 보호층을 형성하는 보호층형성단계, 상기 베이스층의 타측면에 스크래치방지층을 형성하는 스크래치방지층형성단계, 상기 보호층의 일측면에 점착제를 도포하여 점착층을 형성하는 점착층형성단계, 및 상기 점착층이 형성된 보호층의 일측면에 커버층을 형성하는 커버층형성단계,를 포함한다.상기한 바와 같이, 조류의 시야에 장애물이 확인되어 충돌을 방지할 수 있어 안전사고를 방지함은 물론, 설치하고자 하는 면에 쉽게 부착시킬 수 있어 작업효율을 향상시킬 수 있을 뿐만 아니라 여러 자연 환경에도 변형이 거의 없어 유지 보수가 용이한 매우 유용하고 효과적인 발명이다. claims: 베이스층을 형성하는 베이스층형성단계;상기 베이스층의 일측면에 일정 간격으로 패턴을 형성하는 패턴형성단계;상기 패턴이 형성된 베이스층의 일측면에 접착제를 형성하는 접착제형성단계;상기 접착제가 형성된 베이스층의 일측으로 보호층을 형성하는 보호층형성단계;상기 베이스층의 타측면에 스크래치방지층을 형성하는 스크래치방지층형성단계;상기 보호층의 일측면에 점착제를 형성하여 점착층을 형성하는 점착층형성단계; 및상기 점착층이 형성된 보호층의 일측면에 커버층을 형성하는 커버층형성단계;를 포함하고,상기 베이스층형성단계의 베이스층은 투명한 수지재로 형성되며,상기 패턴형성단계의 패턴은 알루미늄, 은, 세라믹, 진주펄 중 어느 하나 이상이고,상기 각 패턴의 간격은 세로 5cm 및 가로 5cm로 형성되는 것을 특징으로 하는 패턴을 갖는 조류 충돌방지용 필름 제조방법.제1항 내지 제2항 중 어느 한 항의 조류 충돌방지용 필름 제조방법에 의해 제조되는 조류 충돌방지용 필름., Ltext: 임업, prediction: 임업
7/1059 Row 7: application_number: 1020200104661, combined_string: invention_title: 동작 및 온도 감지 기반의 해충 퇴치용 LED 조명장치 abstract: 본 발명에 따른 동작 및 온도 감지 기반의 해충 퇴치용 LED 조명장치는 550 내지 700nm의 광파장을 발광하는 복수의 LED가 행렬 구조로 배치된 기판; 상기 기판에 설치된 것으로, 해충의 움직임을 감지하는 동작감지센서; 상기 기판에 설치된 것으로, 15 내지 25kHz 대역의 음파를 발생하는 음파 발생기; 상기 기판을 감싸는 하우징; 상기 하우징에서 상기 LED의 대향 측에 설치된 방열판; 상기 LED와 방열판에서 이격된 상기 하우징의 일 측에 형성된 것으로서, 외부 온도를 측정하는 온도감지센서; 상기 기판에 장착된 것으로서, 상기 동작감지센서의 동작 감지 및 상기 온도감지센서의 온도 감지로 상기 LED 및 음파 발생기를 구동하는 컨트롤러;를 포함하는 것을 특징으로 한다. claims: 동작 및 온도 감지 기반의 해충 퇴치용 LED 조명장치로서,550 내지 700nm의 광파장을 발광하는 복수의 LED가 행렬 구조로 배치된 기판;상기 기판에 설치된 것으로, 해충의 움직임을 감지하는 동작감지센서; 상기 기판에 설치된 것으로, 15 내지 25kHz 대역의 음파를 발생하는 음파 발생기;상기 기판을 감싸는 하우징;상기 하우징에서 상기 LED의 대향 측에 설치된 방열판;상기 LED와 방열판에서 이격된 상기 하우징의 일 측에 형성된 것으로서, 외부 온도를 측정하는 온도감지센서;상기 기판에 장착된 것으로서, 상기 동작감지센서의 동작 감지 및 상기 온도감지센서의 온도 감지로 상기 LED 및 음파 발생기를 구동하는 컨트롤러;를 포함하되,상기 컨트롤러는,상기 동작감지센서 및 상기 온도감지센서를 통해 해충 개체수의 고저를 파악하는 개체수 파악모듈과, 상기 해충 개체수의 고저에 따라 상기 LED의 광파장과 상기 음파 발생기의 주파수 대역 및 작동 시간을 차등 조절하는 차등 제어모듈을 포함하고,상기 차등 제어모듈은,다음의 수학식 1을 통해 상기 주파수 대역을 차등 조절하는 것을 특징으로 하는, LED 조명장치.수학식 1.(여기서, 은 기준 주파수(23 내지 25 kHz), 는 상기 음파 발생기의 주파수(kHz), T는 상기 온도감지센서에서 측정한 온도(℃), L은 상기 해충 개체수의 고저에 따른 레벨()로서, 개체수가 많을수록 증가), Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

8/1059 Row 8: application_number: 1020200088844, combined_string: invention_title: 수목보호 매트 어셈블리 abstract: 본 발명은 수목의 하부와 상기 수목이 식재된 지면을 덮는 것으로, 천연섬유 소재로 이루어져 복수의 경사(經絲)와 복수의 위사(緯絲)로 직조하여 일정 면적과 일정 형상을 가지도록 형성됨과 동시에, 상기 복수의 경사 또는 상기 복수의 위사 각각의 사이에 일정 간격의 삽입 공극을 형성하는 보호 매트; 및 복수의 상기 삽입 공극에 결합되어 상기 지면과 상기 보호 매트 사이에 배치되는 것으로, 보행자의 답압(踏壓)에 상기 보호 매트의 압착을 방지하며 통기와 통수를 유지시키는 브라켓을 포함하는 것을 특징으로 하여, 보행자의 답력에도 압착되고 경화되어 통기 및 통수가 이루어지지 못하는 것을 미연에 방지할 수 있도록 하며 수목의 하부 및 뿌리 노출 부분을 확실하게 보호할 수 있도록 하는 수목보호 매트 어셈블리에 관한 것이다. claims: 수목의 하부와 상기 수목이 식재된 지면을 덮는 것으로, 천연섬유 소재로 이루어져 복수의 경사(經絲)와 복수의 위사(緯絲)로 직조하여 일정 면적과 일정 형상을 가지도록 형성됨과 동시에, 상기 복수의 경사 또는 상기 복수의 위사 각각의 사이에 일정 간격의 삽입 공극을 형성하는 보호 매트; 및복수의 상기 삽입 공극에 결합되어 상기 지면과 상기 보호 매트 사이에 배치되는 것으로, 보행자의 답압(踏壓)에 상기 보호 매트의 압착을 방지하며 통기와 통수를 유지시키는 브라켓을 포함하며,상기 브라켓은, 상기 보호 매트의 사면과 상기 지면 사이에 배치되는 몸체와, 상기 몸체의 상면으로부터 돌출되어 복수로 이격하여 배치되고, 상기 삽입 공극에 끼움 결합되는 연통 리브와, 상기 몸체의 상면으로부터 하면까지 관통되어 통기와 통수를 허용하는 복수의 연통공과, 상기 연통 리브로부터 상기 몸체의 하면까지 관통 형성되어 통기와 통수를 허용하는 복수의 연통슬롯을 포함하는 것을 특징으로 하는 수목보호 매트 어셈블리., Ltext: 임업, prediction: 임업
9/1059 Row 9: application_number: 1020200056830, combined_string: invention_title: 충격 보호 기능이 구비된 수목 보호대 abstract: 본 발명은 충격 보호 기능이 구비된 수목 보호대에 관한 것으로서, 보행자 또는 자전거 등의 이동수단의 충돌로 인한 충격으로 부터 수목을 보호함과 함께 보행자, 자전거 이용자의 부상 발생을 방지하기 위한 것이다.이를 실현하기 위한 본 발명은, 판형태를 이루어 수목 주변으로 지면에 설치가 이루어지는 수목 보호판(10)과; 상기 수목 보호판(10)의 상부에 수직으로 일정 높이를 이루어 세워지도록 연결 구성되는 지주(20)와; 상기 지주(20) 상단부에 연결 구성되어 수목 주변을 감싸는 형태로 구비되되, 복수개가 쌍을 이루어 상호 간격의 가변이 가능하도록 탄성 지지가 이루어지는 완충대(30)와; 상기 지주(20)와 완충대의 연결부위에 구성되는 제1힌지핀(21)과; 상기 지주(20)와 수목 보호판 연결부위에 구성되는 제2힌지핀(22);을 포함하는 구성을 이루는 것을 특징으로 한다. claims: 판형태를 이루어 수목 주변으로 지면에 설치가 이루어지는 수목 보호판(10)과;상기 수목 보호판(10)의 상부에 수직으로 일정 높이를 이루어 세워지도록 연결 구성되는 지주(20)와;상기 지주(20) 상단부에 연결 구성되어 수목 주변을 감싸는 형태로 구비되되, 복수개가 쌍을 이루어 상호 간격의 가변이 가능하도록 탄성 지지가 이루어지는 완충대(30)와;상기 지주(20)와 완충대(30)의 연결부위에 구성되는 제1힌지핀(21)과;상기 지주(20)와 수목 보호판(10) 연결부위에 구성되는 제2힌지핀(22);을 포함하되,상기 완충대(30)는 제1완충대(31)와 제2완충대(32)가 상호 쌍을 이루는 대칭형 구조를 이루되, 상기 제1완충대(31)에는 제2완충대(32)의 일단부가 삽입되는 삽입홈(31a)이 형성되고, 내부에는 제2완충대(32)를 탄성 지지하는 탄성스프링(31b)이 구성됨과 함께 탄성스프링(31b)을 지지하기 위한 지지격벽(31c)이 일체로 구성되며,상기 제2완충대(32)에는 삽입홈(31a)으로의 삽입 길이를 제한하기 위한 걸림턱(32a)이 돌출 구성되고, 단부에는 삽입홈(31a)의 내벽면과 마찰력 증대를 위한 마찰브러시(32b)가 구성된 것을 특징으로 하는 충격 보호 기능이 구비된 수목 보호대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

10/1059 Row 10: application_number: 1020200016831, combined_string: invention_title: 식물성 유지가 포함된 친환경 방제소재를 이용한 플로팅 방제장치 abstract: 본 발명은 식물성 유지기반 플로팅 방제장치에 관한 것으로서, 농작물의 오염과 환경교란 등 경제적, 사회적 문제로 심각하게 대두되는 농약을 사용을 저감할 수 있고, 온실의 내부로 휘산되는 식물성 유지를 이용하여 병해충을 높은 효율로 제충할 수 있는 식물성 유지기반 플로팅 방제장치에 관한 것이다. claims: 상부가 개방된 수용홈이 형성된 휘산용기와;식물성유지가 포함된 친환경 병충해 방제소재가 수용되는 수용용기와;상기 수용용기에 수용된 식물성유지가 포함된 친환경 병충해 방제소재를 일정량 상기 휘산용기의 수용홈으로 공급하는 식물성유지 공급부와;상기 식물성유지공급부에 의해 상기 휘산용기의 수용홈에 공급된 친환경 병충해 방제소재를 식물성유지의 휘산온도로 가열시키는 히터부와;상기 휘산용기 및 히터부가 내부에 수용되는 수용몸체와;상기 수용몸체와 연통된 상태로 상기 수용몸체의 상부에 상하각도조절가능하도록 하부가 축결합되고, 내부로 유입된 상기 히터부에 의해 휘산된 식물성 유지를 외부로 안내하는 가이드몸체와;상기 가이드몸체의 일측에 구비되어 상기 가이드몸체의 내부로 유입된 상기 히터부에 의해 휘산된 식물성 유지를 상기 가이드몸체의 타측 외부방향으로 배기시키는 팬부재;를 포함하고,상기 수용몸체의 하부 측면에 상기 수용몸체 주변의 외부공기를 상기 수용몸체의 내부로 안내하는 가이드슬릿이 형성되며,상기 수용몸체의 상부와 상기 팬부재 사이의 상기 가이드몸체의 내부 하측에 상기 가이드몸체의 하부 타측방향으로 볼록한 호형상으로 구비되어 상기 팬부재에 의해 상기 가이드몸체의 외부로 유입된 외부공기를 상기 수용몸체의 상부방향의 상기 가이드몸체의 내부 상측으로 안내하는 가이드판;이 구비되는 것을 특징으로 하는 식물성 유지가 포함된 친환경 방제소재를 이용한 플로팅 방제장치.식물성유지가 포함된 친환경 병충해 방제소재를 휘산온도로 가열하여 외부로 휘산시키는 히터부와;상기 히터부가 내부에 수용되는 수용몸체와;상기 수용몸체와 연통된 상태로 상기 수용몸체의 상부에 상하각도조절가능하도록 하부가 축결합되고, 내부로 유입된 상기 히터부에 의해 휘산된 식물성 유지를 외부로 안내하는 가이드몸체와;상기 가이드몸체의 일측에 구비되어 상기 가이드몸체의 내부로 유입된 상기 히터부에 의해 휘산된 식물성 유지를 상기 가이드몸체의 타측 외부방향으로 배기시키는 팬부재;가 구비되고,상기 수용몸체의 하부 측면에 상기 수용몸체 주변의 외부공기를 상기 수용몸체의 내부로 안내하는 가이드슬릿이 형성되며,상기 수용몸체의 상부와 상기 팬부재 사이의 상기 가이드몸체의 내부 하측에 상기 가이드몸체의 하부 타측방향으로 볼록한 호형상으로 구비되어 상기 팬부재에 의해 상기 가이드몸체의 외부로 유입된 외부공기를 상기 수용몸체의 상부방향의 상기 가이드몸체의 내부 상측으로 안내하는 가이드판;이 구비되는 것을 특징으로 하는 식물성 유지가 포함된 친환경 방제소재를 이용한 플로팅 방제장치., Ltext: 임업, prediction: 농업
11/1059 Row 11: application_number: 1020200014121, combined_string: invention_title: 딸기 흰가루병 방제 약제 및 이의 제조방법과 용도 abstract: 본 발명은 살균제와 신고지막 500배액 내지 800배액을 복합함으로써 살균제의 약 효과를 향상하고 농약의 사용 횟수를 줄여 약물 사용 안전성을 향상하는 딸기 흰가루병 방제 약제를 제공한다. 상기 방제 약제를 딸기에 응용함으로써 딸기 과일 또는 딸기 식물체 표면에 한 층의 고분자 막을 형성할 수 있어 식물의 수분 흡수, 통기성 및 광 투과 품질을 최적화하며, 병충 포식 신호를 차단하고 전파 매체를 약화시킬 수 있어 딸기 흰가루병에 대하여 보다 양호한 방제 효과을 구비하여 딸기의 안전생산에 기술보장을 제공함으로써 높은 실제의 응용가치를 구비한다. claims: 신고지막과 살균제를 포함하며 여기서, 신고지막은 신고지막 500배액 내지 800배액인 것을 특징으로 하는 딸기 흰가루병 방제 약제.제 1 항 내지 제 4 항 중 임의의 한 항에 따른 딸기 흰가루병 방제 약제의 제조방법에 있어서,단계 (1) 500배 내지 800배의 사용량으로 희석된 신고지막을 일부분 물에 용해하여 용액 A를 얻으며;단계 (2) 살균제를 다른 일부분 물에 용해하여 용액 B를 얻으며;단계 (3) 상기 용액 A와 상기 용액 B를 혼합하고 나머지 물을 첨가한 후 균일하게 혼합하여 신고지막의 500배 내지 800배 희석액과 살균제 희석액을 얻음으로써 딸기 흰가루병 방제 약제를 조제하는 단계를 포함하는 것을 특징으로 하는 딸기 흰가루병 방제 약제의 제조방법.제 1 항 내지 제 4 항 중 임의의 한 항에 따른 딸기 흰가루병 방제 약제를 포함하는 것을 특징으로 하는 분무액.제 1 항 내지 제 4 항 중 임의의 한 항에 따른 방제 약제가 딸기 과일 및/또는 딸기 식물체에 적용되는 방법.제 1 항 내지 제 4 항 중 임의의 한 항에 따른 방제 약제가 딸기 흰가루병 방제에 적용되는 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

12/1059 Row 12: application_number: 1020200009227, combined_string: invention_title: 나무심기 입지 분석 장치 및 방법 abstract: 본 발명은 나무심기 입지 분석 장치 및 방법에 관한 것으로, 상기 장치는 특정 지역에 관한 연속지적도를 기준으로 이용현황, 도시계획 및 특정지목과 연관된 식재 불가 지역을 순차적으로 반영하여 식재 가능 지역을 결정하는 식재 가능 지역 결정부, 상기 식재 가능 지역에 대해 물리적 또는 비물리적 요인으로 분류되는 토지 특성 요인들에 따라 토지 특성을 도출하는 토지 특성 도출부 및 상기 토지 특성을 고려하여 상기 식재 가능 지역에 관한 적합 수종을 결정하는 적합 수종 결정부를 포함한다. claims: 특정 지역에 관한 연속지적도를 기준으로 이용현황, 도시계획 및 특정지목과 연관된 식재 불가 지역을 순차적으로 반영하여 식재 가능 지역을 결정하는 식재 가능 지역 결정부;상기 식재 가능 지역에 대해 물리적 또는 비물리적 요인으로 분류되는 토지 특성 요인들에 따라 토지 특성을 도출하는 토지 특성 도출부; 및상기 토지 특성을 고려하여 상기 식재 가능 지역에 관한 적합 수종을 결정하는 적합 수종 결정부를 포함하는 나무심기 입지 분석 장치.나무심기 입지 분석 장치에서 수행되는 방법에 있어서,특정 지역에 관한 연속지적도를 기준으로 이용현황, 도시계획 및 특정지목과 연관된 식재 불가 지역을 순차적으로 반영하여 식재 가능 지역을 결정하는 단계;상기 식재 가능 지역에 대해 물리적 또는 비물리적 요인으로 분류되는 토지 특성 요인들에 따라 토지 특성을 도출하는 단계;상기 토지 특성을 고려하여 상기 식재 가능 지역에 관한 적합 수종을 결정하는 단계; 및상기 식재 가능 지역의 식재가능 면적을 고려하여 상기 적합 수종의 식재 효과를 산출하는 단계를 포함하는 나무심기 입지 분석 방법., Ltext: 임업, prediction: 임업
13/1059 Row 13: application_number: 1020200004448, combined_string: invention_title: 수목 정보 제공 시스템 abstract: 본 발명은 수목 정보 제공 시스템에 관한 것으로, 해결하고자 하는 기술적 과제는 온라인 상에서 위치에 제약 없이 사용자가 필요할 때 특정 지역이나 위치에 식재된 수목에 대한 병충해 등의 상태나 이를 위한 관리 또는 진료 정보를 열람할 수 있도록 하는데 있다.일례로, 사용자 통신단말에 설치되고, 지도 서비스를 기반으로 사용자로부터 식재된 수목의 상태정보를 입력 받아 서버에 등록하고, 사용자의 열람요청에 따른 수목 별 상태정보를 지도 상에 표시하여 제공하는 수목 정보 어플리케이션; 및 상기 수목 정보 어플리케이션을 통해 수신되는 수목의 위치정보 및 상태정보를 저장하고, 상기 열람요청에 따른 위치정보를 기반으로 수목 상태정보를 상기 수목 정보 어플리케이션으로 제공하는 수목 정보 서버를 포함하는 수목 정보 제공 시스템을 개시한다. claims: 사용자 통신단말에 설치되고, 지도 서비스를 기반으로 사용자로부터 식재된 수목의 상태정보를 입력 받아 서버에 등록하고, 사용자의 열람요청에 따른 수목 별 상태정보를 지도 상에 표시하여 제공하는 수목 정보 어플리케이션; 및 상기 수목 정보 어플리케이션을 통해 수신되는 수목의 위치정보 및 상태정보를 저장하고, 상기 열람요청에 따른 위치정보를 기반으로 수목 상태정보를 상기 수목 정보 어플리케이션으로 제공하는 수목 정보 서버; 및수목 식별정보에 각각 대응되는 마커를 포함하고, 수목 별로 부착 또는 설치된 수목 마커정보 표시부를 포함하고,상기 수목 정보 어플리케이션은, 상기 수목 식별정보에 대하여 수목 진료기록정보를 입력 받고, 입력된 상기 수목 진료기록정보를 상기 수목 정보 서버에 등록 요청하는 수목 진료기록정보 등록 요청부;사용자 통신단말의 위치정보 또는 사용자에 의해 지정된 위치정보에 따른 상기 열람요청을 상기 수목 정보 서버에 전달하고, 사용자 통신단말의 위치정보 또는 사용자에 의해 지정된 위치정보를 기반으로 지도 상에 표시되는 아이콘 별로 상기 수목 진료기록정보를 각각 제공하는 수목 진료기록정보 검색 제공부;사용자 통신단말의 위치정보를 기반으로 상기 수목 식별정보를 입력하고, 입력된 수목 식별정보와 사용자 통신단말의 위치정보를 매칭하고, 위치정보가 매칭된 수목 식별정보를 상기 수목 정보 서버에 등록 요청하는 수목 식별정보 등록 요청부;상기 수목 식별정보에 대하여 다수의 수목 상태정보 중 적어도 하나를 선택 또는 입력 받고, 입력된 상기 수목 상태정보에 따라 미리 설정된 아이콘을 생성하여 상기 수목 식별정보에 대한 상기 수목 상태정보를 상기 수목 정보 서버에 등록 요청하는 수목 상태정보 등록 요청부;사용자 통신단말의 위치정보 또는 사용자에 의해 지정된 위치정보에 따른 상기 열람요청을 상기 수목 정보 서버에 전달하고, 사용자 통신단말의 위치정보 또는 사용자에 의해 지정된 위치정보를 기반으로 지도 상에 상기 아이콘을 표시하여 상기 수목 상태정보를 각각 제공하는 수목 상태정보 검색 제공부;사용자 통신단말의 카메라와 연동하여 현장에 식재된 상기 마커를 인식하고, 인식된 마커 정보를 상기 수목 정보 서버에 전송하며, 상기 수목 정보 서버로부터 상기 마커 정보에 따른 상기 수목 상태정보와 상기 수목 진료기록정보를 수신하여 사용자 통신단말의 카메라를 통한 촬영 영상 내 해당 수목 상에 오버랩 된 증강현실 그래픽으로 표시하되, 수목의 건강 상태에 따라 상이한 색상의 가상 이미지로 이루어진 증강현실 그래픽을 촬영 영상 내 해당 수목 상에 오버랩 하여 표시하는 증강현실 실행부; 및 상기 수목 상태정보와 상기 수목 진료기록정보에 따라 수목병이 발생된 경우 수목병 발생 경로 및 원인정보를 상기 수목 정보 서버에 요청하고, 요청에 대한 응답을 수신하여 상기 아이콘을 통해 표시하는 수목병 정보 요청 표시부를 포함하는 것을 특징으로 하는 수목 정보 제공 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

14/1059 Row 14: application_number: 1020190177700, combined_string: invention_title: 수목생육관리장치 및 이를 포함하는 생태 모니터링 시스템 abstract: 본 발명의 수목생육관리장치는, 내부에 공간부가 형성되어 수분을 저장하며, 상기 토양에 수분을 제공하는 집수블록과, 상기 수목의 뿌리와 인접한 토양의 상태를 측정하는 센서부와, 상기 센서부에 의해 생성된 측정 정보와 상기 수목에 할당된 식별번호를 포함하는 생태 정보를 생성하는 제어부와, 외부와 통신을 수행하는 통신부을 포함한다. claims: 내부에 공간부가 형성되어 수분을 저장하며, 상기 토양에 수분을 제공하는 집수블록;상기 수목의 뿌리와 인접한 토양의 상태를 측정하는 센서부;상기 센서부에 의해 생성된 측정 정보와 상기 수목에 할당된 식별번호를 포함하는 생태 정보를 생성하는 제어부; 및외부와 통신을 수행하는 통신부을 포함하는 수목생육관리장치.지표면의 하부에 매립되어 내부에 형성된 공간부에 수분을 저장하고 상기 수분을 인접한 수목의 뿌리를 둘러싼 토양에 제공하는 집수블록과, 상기 토양의 상태를 측정하는 센서부와, 상기 센서부에 의해 측정된 센싱 결과와 상기 수목에 할당된 식별번호를 포함하는 토양 정보를 생성하는 제어부와, 외부와 통신을 수행하는 통신부를 포함하는 수목생육관리장치; 및상기 통신부로부터 제공된 상기 식별번호에 대응하는 지도상 위치에 상기 센싱 결과에 대응하는 단계별 색상, 수치, 및 기호 중 적어도 하나를 표기하여 토양생태지도를 생성하는 생태 관리 서버를 포함하는 생태 모니터링 시스템., Ltext: 임업, prediction: 임업
15/1059 Row 15: application_number: 1020190177214, combined_string: invention_title: GIS를 이용한 수목 관리 시스템 abstract: 본 발명은 수목 관리 시스템에 관한 것으로, 보다 상세하게는 GIS(Geographic Information System)을 이용하여 실시간으로 수목을 관리할 수 있는 시스템에 관한 것이다. claims: GIS로부터 다수의 환경 인자를 포함하는 지리 정보 데이터를 추출하는 데이터 추출부;광을 조사한 후 수목으로부터 반사되는 광을 취득하여 상기 수목의 3차원 정보를 획득하기 위한 광조사부;수목의 분광 정보를 수집하여 수목의 분광 특성을 측정하기 위한 분광 영상 처리부; 및상기 추출부, 상기 광조사부, 상기 분광 영상 처리부로부터 획득된 데이터를 처리하는 데이터 처리부;를 포함하는, GIS를 이용한 수목 관리 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

16/1059 Row 16: application_number: 1020190176224, combined_string: invention_title: 야생동물 및 유해조류 퇴치기 abstract: 본 발명은 야생동물 및 유해조류 퇴치기에 관한 것으로, 지면에 고정하는 지주부; 상기 지주부 상단에 결합되며, 내부에 레이저모듈부를 구비하는 본체부: 상기 지주부 일측에 결합 고정되는 제어부; 및 상기 본체부 상단부에 결합하여 유입되는 이물질을 차단하는 보호부;를 포함하되, 상기 레이저모듈부는 녹색 또는 적색 레이저 광을 발사하는 제1 및 제2 레이저발생부와, 상기 제1 및 제2 레이저모듈 각각을 상하로 슬라이드 시키는 필렛부, 및 상기 필렛부를 상하로 롤링 및 수평으로 회전시키는 제1 및 제2 모터를 포함하는 것을 특징으로 한다. claims: 지면에 고정하는 지주부;상기 지주부 상단에 결합되며, 내부에 레이저모듈부를 구비하는 본체부:상기 지주부 일측에 결합 고정되는 제어부; 및상기 본체부 상단부에 결합하여 유입되는 이물질을 차단하는 보호부;를 포함하되, 상기 레이저모듈부는,녹색 또는 적색 레이저 광을 발사하는 제1 및 제2 레이저발생부와,상기 제1 및 제2 레이저발생부 각각을 상하로 슬라이드 시키는 필렛부, 및상기 필렛부를 상하로 롤링 및 수평으로 회전시키는 제1 및 제2 모터를 포함하며,상기 필렛부는 중앙에 구동축이 결합되고, 상기 구동축을 중심으로 소정 길이로 획정된 제1 및 제2 홈이 형성되며, 상기 제1 및 제2 홈에 제1 및 2 레이저발생부의 일측이 제1 및 제2 핀으로 각각 결합되며,상기 제1 모터로 밸트를 통해 구동축을 회전시키면서 제2 모터로 롤링캠을 통해 구동축을 상하로 동작시키면, 상기 구동축 중앙에 결합된 필렛부의 제1 및 제2 홈을 따라 제1 및 제2 핀과 결합된 제1 및 2 레이저발생부가 회전하면서 상하로 로링하여 레이저 광이 360도 회전하면서 상하로 방출되는 것을 특징으로 하는 야생동물 및 유해조류 퇴치기., Ltext: 임업, prediction: 임업
17/1059 Row 17: application_number: 1020190173691, combined_string: invention_title: 투-웨이 유인기작 유인등 트랩 abstract: 본 발명은 노린재류의 효과적인 유인 과 포획이 가능하도록 시각 및 후각적인 유인기작을 동시에 사용한 투-웨이 유인기작 유인등 트랩에 관한 것으로, 상단에 행거 고리(110)가 구비된 몸체(100)와; 상기 몸체(100)의 하단부에 설치되고, 하단에 포획통(210)이 분리가능하게 결합되며 내측에 유인제인 집합페로몬이 설치된 깔때기 형태의 유인부(200)와; 상기 유인부(200)의 상측에 설치되는 유인등(300)과; 상기 유인등(300)의 외곽에 설치되는 전기충격부(400)와; 상기 몸체(100)에 설치되어 상기 유인등(300)과 전기충격부(400)의 동작을 제어하는 제어부(500);를 포함하여 이루어져 있다. claims: 상단에 행거 고리(110)가 구비된 몸체(100)와;상기 몸체(100)의 하단부에 설치되고, 하단에 포획통(210)이 분리가능하게 결합되며 내측에 유인제인 집합페로몬이 설치된 깔때기 형태의 유인부(200)와;상기 유인부(200)의 상측에 설치되는 유인등(300)과;상기 유인등(300)의 외곽에 설치되는 전기충격부(400)와;상기 몸체(100)에 설치되어 상기 유인등(300)과 전기충격부(400)의 동작을 제어하는 제어부(500);를 포함하여 이루어진 것을 특징으로 하는 투-웨이 유인기작 유인등 트랩., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

18/1059 Row 18: application_number: 1020190170987, combined_string: invention_title: 재선충 감지와 제거를 위한 스마트 방제 시스템 abstract: 재선충 감지와 제거를 위한 스마트 방제 시스템는 소나무에 존재하는 재선충을 감지하고, 재선충의 매개충인 솔수염 하늘소와 북방수염하늘소를 유인성 조성물에 의해 유인하여 포획한다.본 발명은 재선충의 매개충인 솔수염 하늘소와 북방수염하늘소의 유충 및 성충의 소리 신호를 수집하여 유충과 성충을 유인하기 적합한 유인성 조성물을 발산하여 솔수염 하늘소와 북방수염하늘소를 빠르게 제거할 수 있어 재선충병의 확산을 미연히 예방할 수 있으며, 각 세부 구역의 재선충 탐지와 솔수염 하늘소와 북방수염하늘소의 유충 및 성충의 개체수를 파악하여 조기에 빠른 대처와 확산 방지 및 신속한 방제 업무가 가능한 효과가 있다. claims: 관리하고자 하는 영역에 존재하는 대표 지표 소나무에 부착하여 재선충에 따른 소나무의 고유 진동을 통해 소나무 내부의 수분 및 양분 이동 통로에 대한 밀도 변화를 측정하여 재선충을 감지하는 각 세부 구역에 설치된 하나 이상의 재선충 감시 장치;상기 재선충 감시 장치로부터 재선충 감지 신호를 수신하고, 상기 수신한 재선충 감지 신호를 외부로 전송하는 하나 이상의 센서 통신 중계기; 및상기 각각의 센서 통신 중계기로부터 수신한 재선충 감지 신호에서 식별자를 분석하여 상기 재선충 감시 장치의 위치와, 재선충병이 발생한 것으로 예측되는 세부 구역을 판단하는 데이터 분석 서버를 포함하는 것을 특징으로 하는 스마트 방제 시스템.관리하고자 하는 영역에 존재하는 대표 지표 소나무에 부착되고, 상부가 개방되어 솔수염하늘소나 북방수염하늘소의 성충이나 유충이 유입되는 개방구를 형성한 하우징과 상기 하우징의 하단에 결합되어 상기 성충이나 유충이 상기 하우징을 거쳐 하강하여 포획되는 재선충 수집부를 구비하고, 각 세부 구역에 설치된 하나 이상의 재선충 제거 장치;상기 재선충 제거 장치로부터 포획된 유충 개수와 성충 개수를 포함한 재선충 정보를 수신하고, 상기 수신한 재선충 정보를 외부로 전송하는 하나 이상의 센서 통신 중계기; 및상기 각각의 센서 통신 중계기로부터 수신한 재선충 정보에서 식별자를 분석하여 상기 재선충 제거 장치의 위치를 판단하는 데이터 분석 서버를 포함하는 것을 특징으로 하는 스마트 방제 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

19/1059 Row 19: application_number: 1020190169582, combined_string: invention_title: 온열 가압에 의한 하수관로 내의 모기 방제 시스템 abstract: 본 발명은 온열 가압에 의한 하수관로 내의 모기 방제 시스템에 관한 것으로서, 뜨거운 공기를 일정한 압력으로 공급하는 콤프레서; 상기 콤프레서와 연결되되 약제를 포함하는 약제 탱크; 상기 약제 탱크와 연결되되 실질적으로 하수관로 내에 배치되어 상기 하수관로 내부를 향해 초미세 상태의 약제를 분사하는 약제 분사장치; 및 운전 시 상기 콤프레서에서 발생하는 고온 공기가 상기 약제 탱크로 공급되어 상기 약제 탱크 내의 약제가 가열되게 한 후, 상기 약제 분사장치를 통해 상기 하수관로 내부를 향해 분사되게 하되 분사되는 약제가 소정의 압력에 의하여 초미세 입자의 스팀 스모그(steam smoke) 상태로 분사될 수 있도록 상기 콤프레서, 상기 약제 탱크 및 상기 약제 분사장치의 동작을 컨트롤하는 컨트롤러를 포함한다. claims: 뜨거운 공기를 일정한 압력으로 공급하는 콤프레서;상기 콤프레서와 연결되되 약제를 포함하는 약제 탱크;상기 약제 탱크와 연결되되 실질적으로 하수관로 내에 배치되어 상기 하수관로 내부를 향해 초미세 상태의 약제를 분사하는 약제 분사장치; 및운전 시 상기 콤프레서에서 발생하는 고온 공기가 상기 약제 탱크로 공급되어 상기 약제 탱크 내의 약제가 가열되게 한 후, 상기 약제 분사장치를 통해 상기 하수관로 내부를 향해 분사되게 하되 분사되는 약제가 소정의 압력에 의하여 초미세 입자의 스팀 스모그(steam smoke) 상태로 분사될 수 있도록 상기 콤프레서, 상기 약제 탱크 및 상기 약제 분사장치의 동작을 컨트롤하는 컨트롤러를 포함하고,상기 약제 탱크는,탱크 본체;상기 탱크 본체에 결합하는 가압 파이프;상기 가압 파이프와는 별개로 마련되는 열기 공급 파이프;상기 탱크 본체 내에 배치되되 상기 열기 공급 파이프를 둘러싸게 배치되는 보일러 코일;상기 탱크 본체의 일측에 마련되며, 상기 탱크 본체 내로 약제를 투입하는 약제 투입부;상기 탱크 본체의 상부 일측에 마련되는 안전밸브;상기 탱크 본체의 하부 일측에 마련되며, 상기 탱크 본체 내의 잔류 약제를 배출하는 잔류량 배출밸브;상기 탱크 본체의 일측에 결합하는 컨트롤 박스; 및일단부가 상기 컨트롤 박스에 결합하고 타단부는 상기 약제 분사장치와 연결되며, 상기 약제 탱크 측의 약제 및 공기를 공급하는 약제 및 공기 공급호스를 포함하며,상기 콤프레서에서 상기 약제 탱크로 공기를 전달하되 상기 약제 탱크에 압력을 가하는 제1 공기 전달호스; 및상기 제1 공기 전달호스와는 다른 경로를 통해 상기 콤프레서에서 상기 약제 탱크로 공기를 전달하되 상기 약제 분사장치에 풍량을 제공하는 제2 공기 전달호스를 더 포함하며,상기 제1 공기 전달호스는 상기 약제 탱크의 가압 파이프에 연결되고, 상기 제2 공기 전달호스는 상기 약제 탱크의 열기 공급 파이프에 연결되는 것을 특징으로 하는 온열 가압에 의한 하수관로 내의 모기 방제 시스템.뜨거운 공기를 일정한 압력으로 공급하는 콤프레서;상기 콤프레서와 연결되되 약제를 포함하는 약제 탱크;상기 약제 탱크와 연결되되 실질적으로 하수관로 내에 배치되어 상기 하수관로 내부를 향해 초미세 상태의 약제를 분사하는 약제 분사장치; 및운전 시 상기 콤프레서에서 발생하는 고온 공기가 상기 약제 탱크로 공급되어 상기 약제 탱크 내의 약제가 가열되게 한 후, 상기 약제 분사장치를 통해 상기 하수관로 내부를 향해 분사되게 하되 분사되는 약제가 소정의 압력에 의하여 초미세 입자의 스팀 스모그(steam smoke) 상태로 분사될 수 있도록 상기 콤프레서, 상기 약제 탱크 및 상기 약제 분사장치의 동작을 컨트롤하는 컨트롤러를 포함하고,,상기 약제 분사장치는,내부에 약제와 공기가 공급되는 공간이 형성되는 분사장치 본체;상기 분사장치 본체 내외에 연결되며, 상기 약제 탱크 측에서 공급되는 약제와 공기가 공급되는 약제 및 공기 공급관;상기 분사장치 본체 내에 마련되며, 상기 약제 및 공기 공급관에서 공급되는 공기를 필터링하는 필터;상기 분사장치 본체 내에 마련되며, 상기 약제 및 공기 공급관에서 공급되는 약제와 공기 중 액체 상태와 기체 상태를 분리하는 분리막;상기 분사장치 본체의 하단부에 결합하며, 상기 분사장치 본체 내의 하부 영역으로 모이는 액체 상태의 약제가 모이는 액상 약제 저장부;상기 분사장치 본체의 측벽에 결합하는 복수의 플랜지;상기 플랜지에 결합하며, 약제를 분사하는 분사노즐;양단부가 상기 분사장치 본체 내의 상부 영역에 마련되는 에어 니플과 상기 분사노즐에 연결되며, 상기 분사장치 본체 내의 공기를 상기 분사노즐로 공급하는 공기 공급라인; 및양단부가 상기 액상 약제 저장부과 상기 분사노즐에 연결되며, 상기 액상 약제 저장부 내의 액상 약제를 상기 분사노즐로 공급하는 약재 공급라인을 포함하고,상기 약제 분사장치는,상기 분사장치 본체의 하부에 연결되며, 상기 분사장치 본체를 지지하는 복수의 장치 지지대;상기 분사장치 본체의 상부에 결합하는 고리;상기 고리에 결합하는 현수 와이어; 및상기 분사장치 본체에 결합하며, 상기 분사장치 본체 내의 압력을 감지하는 압력계를 더 포함하는 것을 특징으로 하는 온열 가압에 의한 하수관로 내의 모기 방제 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

20/1059 Row 20: application_number: 1020190166460, combined_string: invention_title: 산림빅데이터 플랫폼에 기반하여 데이터 상품을 제공하는 장치 및 방법 abstract: 본 발명은 산림빅데이터 플랫폼을 구축하고, 산림빅데이터 플랫폼에 기반하여 다양한 데이터 상품을 제공하는 기술적 사상에 관한 것으로서, 보다 상세하게는 산림빅데이터 플롯폼에 기반하여 산림자원관리 서비스, 산림휴양 복지 서비스, 산림재해안전 서비스를 도출하고, 도출된 서비스와 관련된 데이터 상품을 소비자들에게 제공하는 기술에 관한 것이다. claims: 산림 자원과 관련된 정보 데이터를 수집하고, 상기 수집된 정보 데이터와 관련된 수집 데이터 DB(database)를 구축하는 데이터 수집부;상기 구축된 수집 데이터 DB(database)를 통해 상기 수집된 정보 데이터를 분석, 가공 및 매쉬업(mash-up)하여 산림 휴양 및 복지 서비스, 산림자원관리 서비스 및 산림 재해안전 서비스와 관련된 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하는 데이터 상품 결정부; 및상기 구축된 빅데이터 DB(database)에 기반하여 상기 결정된 적어도 하나 이상의 데이터 상품을 제공하기 위한 오픈 마켓 플레이스를 생성하고, 상기 생성된 오픈 마켓 플레이스를 통해 소비자에게 상기 결정된 적어도 하나 이상의 데이터 상품을 제공하는 데이터 상품 제공부를 포함하고,상기 데이터 상품 결정부는 상기 산림 자원과 관련된 정보 데이터를 가공하여 상기 산림자원관리 서비스와 관련된 활용 자원 데이터를 결정하고, 상기 결정된 활용 자원 데이터를 이용하여 산지관리법에 기반하여 필지의 경사를 레벨 별로 구분하여 표시된 맵 데이터를 생성하고, 상기 생성된 맵 데이터에 기반하여 상기 레벨과 관련된 상기 필지 별 개발 용이성에 따라 상기 필지 내에서 개발 가능한 영역을 안내하는 데이터 상품을 결정하며, 상기 산림 재해안전 서비스와 관련된 상기 결정된 재해 대응 데이터 또는 산림 재해 데이터를 이용하여 도시 숲 대비 기온 분석이 표시된 그래프 데이터를 생성하고, 상기 생성된 그래프 데이터에 기반하여 도시의 분할 구역의 면적과 1인당 도시 숲의 면적 그리고 상기 도시의 분할 구역의 면적과 1인당 도시 숲의 면적에 따른 낮 온도, 저녁 온도 및 온도 변화를 표시함에 따라 도시 숲 조성 지역 선정을 보조하는 데이터 상품을 결정하며, 상기 산림자원관리 서비스와 관련된 상기 결정된 임산물 생산 유통 데이터를 이용하여 임산물 가격 예측 데이터, 월별 도매시장 별 임산물 거래 현황 데이터, 월별도매시장 임산물 시장 점유율 데이터 및 월별 임산물 거래량 증감현황 데이터를 생성하고, 상기 생성된 임산물 가격 예측 데이터, 월별 도매시장 별 임산물 거래 현황 데이터, 월별도매시장 임산물 시장 점유율 데이터 및 월별 임산물 거래량 증감현황 데이터에 기반하여 월별 거래단량과 전체 거래단량에 따른 임산물 거래 현황 정보, 전국도매시장 일별 정산 경락 가격과 수출입정보의 적용에 따라 구현된 가격 예측 알고리즘 및 최근 5년간 추세분석에 기반한 거래량의 변화와 관련된 임산물 거래량 증강 정보를 제공하는 데이터 상품을 결정하고,상기 데이터 상품 결정부는, 상기 산림 자원과 관련된 정보 데이터를 가공하여, 상기 결정된 적어도 하나 이상의 데이터 상품과 관련된 트랙킹 활용증대 데이터, 휴양 자원 데이터 또는 산림 소비자 요건 데이터를 결정하여 상기 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하고, 상기 산림 휴양 및 복지 서비스와 관련된 상기 결정된 휴양 자원 데이터를 이용하여 피톤치드 예측발생량이 표시된 맵 데이터를 생성하고, 상기 생성된 맵 데이터에 기반하여 피톤치드에 특화된 관광코스를 제공하는 데이터 상품을 결정하며, 상기 산림 휴양 및 복지 서비스와 관련된 상기 결정된 트랙킹 활용증대 데이터 또는 휴양 자원 데이터를 이용하여 휴양지 관련 대중교통 접근성 평가 데이터를 생성하고, 상기 생성된 대중교통 접근성 평가 데이터에 기반하여 대중교통의 타입, 개수 또는 빈도 중 적어도 하나를 결정 또는 변경하도록 지원하는 데이터 상품을 결정하는산림빅데이터 플랫폼에 기반하여 데이터 상품을 제공하는 장치.데이터 수집부에서, 산림 자원과 관련된 정보 데이터를 수집하고, 상기 수집된 정보 데이터와 관련된 수집 데이터 DB(database)를 구축하는 단계;데이터 상품 결정부에서, 상기 구축된 수집 데이터 DB(database)를 통해 상기 수집된 정보 데이터를 분석, 가공 및 매쉬업(mash-up)하여 산림 휴양 및 복지 서비스, 산림자원관리 서비스 및 산림 재해안전 서비스와 관련된 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하는 단계; 및데이터 상품 제공부에서, 상기 구축된 빅데이터 DB(database)에 기반하여 상기 결정된 적어도 하나 이상의 데이터 상품을 제공하기 위한 오픈 마켓 플레이스를 생성하고, 상기 생성된 오픈 마켓 플레이스를 통해 소비자에게 상기 결정된 적어도 하나 이상의 데이터 상품을 제공하는 단계를 포함하고,상기 적어도 하나 이상의 데이터 상품을 결정하는 단계는,상기 산림 자원과 관련된 정보 데이터를 가공하여 상기 산림자원관리 서비스와 관련된 활용 자원 데이터를 결정하고, 상기 결정된 활용 자원 데이터를 이용하여 산지관리법에 기반하여 필지의 경사를 레벨 별로 구분하여 표시된 맵 데이터를 생성하고, 상기 생성된 맵 데이터에 기반하여 상기 레벨과 관련된 상기 필지 별 개발 용이성에 따라 상기 필지 내에서 개발 가능한 영역을 안내하는 데이터 상품을 결정하는 단계;상기 산림 재해안전 서비스와 관련된 상기 결정된 재해 대응 데이터 또는 산림 재해 데이터를 이용하여 도시 숲 대비 기온 분석이 표시된 그래프 데이터를 생성하고, 상기 생성된 그래프 데이터에 기반하여 도시의 분할 구역의 면적과 1인당 도시 숲의 면적 그리고 상기 도시의 분할 구역의 면적과 1인당 도시 숲의 면적에 따른 낮 온도, 저녁 온도 및 온도 변화를 표시함에 따라 도시 숲 조성 지역 선정을 보조하는 데이터 상품을 결정하는 단계; 및상기 산림자원관리 서비스와 관련된 상기 결정된 임산물 생산 유통 데이터를 이용하여 임산물 가격 예측 데이터, 월별 도매시장 별 임산물 거래 현황 데이터, 월별도매시장 임산물 시장 점유율 데이터 및 월별 임산물 거래량 증감현황 데이터를 생성하고, 상기 생성된 임산물 가격 예측 데이터, 월별 도매시장 별 임산물 거래 현황 데이터, 월별도매시장 임산물 시장 점유율 데이터 및 월별 임산물 거래량 증감현황 데이터에 기반하여 월별 거래단량과 전체 거래단량에 따른 임산물 거래 현황 정보, 전국도매시장 일별 정산 경락 가격과 수출입정보의 적용에 따라 구현된 가격 예측 알고리즘 및 최근 5년간 추세분석에 기반한 거래량의 변화와 관련된 임산물 거래량 증강 정보를 제공하는 데이터 상품을 결정하는 단계를 포함하고,상기 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하는 단계는 상기 산림 자원과 관련된 정보 데이터를 가공하여, 상기 결정된 적어도 하나 이상의 데이터 상품과 관련된 트랙킹 활용증대 데이터, 휴양 자원 데이터 또는 산림 소비자 요건 데이터를 결정하여 상기 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하는 단계를 포함하고,상기 적어도 하나 이상의 데이터 상품을 결정하는 단계는 상기 산림 휴양 및 복지 서비스와 관련된 상기 결정된 휴양 자원 데이터를 이용하여 피톤치드 예측발생량이 표시된 맵 데이터를 생성하고, 상기 생성된 맵 데이터에 기반하여 피톤치드에 특화된 관광코스를 제공하는 데이터 상품을 결정하는 단계 및 상기 산림 휴양 및 복지 서비스와 관련된 상기 결정된 트랙킹 활용증대 데이터 또는 휴양 자원 데이터를 이용하여 휴양지 관련 대중교통 접근성 평가 데이터를 생성하고, 상기 생성된 대중교통 접근성 평가 데이터에 기반하여 대중교통의 타입, 개수 또는 빈도 중 적어도 하나를 결정 또는 변경하도록 지원하는 데이터 상품을 결정하는 단계를 포함하는산림빅데이터 플랫폼에 기반하여 데이터 상품을 제공하는 방법., Ltext: 임업, prediction: 임업
21/1059 Row 21: application_number: 1020190164761, combined_string: invention_title: 갈색날개매미충 포획용 트랩 abstract: 본 발명은 갈색날개매미충과 같은 외래 해층을 효과적으로 포획할 수 있도록 한 포획용 트랩으로, 대체로 원통형으로 이루어지며, 내부에 유인제가 설치되고, 측면과 하면에 외광내협의 형태로 이루어진 복수의 해충 유입구(110)가 형성된 포획통(100)과; 상기 포획통(100) 상부 내측에 분리가능하게 안치되며, 상부에서 유입된 해충을 포획통(100)으로 빠지도록 하고 외부에서 유입된 바람에 회전기류를 일으켜 포획통(100) 내의 유인제가 상기 모든 복수의 해충 유입구(110)를 통해 외부로 배출되도록 하기 위한 깔대기 형태로 이루어진 분리체(200)와; 상기 포획통(100)의 상부에 분리가능하게 결합되며, 외부로부터 바람이 유입되도록 하기 위한 바람유입구(310)가 외곽에 형성된 뚜껑(300);을 포함하여 이루어진다. claims: 내부에 유인제가 설치되고, 측면과 하면에 복수의 해충 유입구(110)가 형성된 포획통(100)과;상기 포획통(100) 상부 내측에 분리가능하게 안치되며, 상부에서 유입된 해충을 포획통(100)으로 빠지도록 하고 외부에서 유입된 바람에 회전기류를 일으켜 포획통(100) 내의 유인제가 상기 모든 복수의 해충 유입구(110)를 통해 외부로 배출되도록 하기 위한 깔대기 형태로 이루어진 분리체(200)와;상기 포획통(100)의 상부에 분리가능하게 결합되며, 외부로부터 바람이 유입되도록 하기 위한 바람유입구(310)가 외곽에 형성된 뚜껑(300);을 포함하여 이루어진 것을 특징으로 하는 갈색날개매미충 포획용 트랩.청구항 5에 있어서.상기 철(凸)형 유입구(110b)에는 유인 길(120)에서 연장되어 45° 각도로 오름길(130)이 만들어진 것을 특징으로 하는 갈색날개매미충 포획용 트랩., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

22/1059 Row 22: application_number: 1020190162420, combined_string: invention_title: 수목용 지지구 abstract: 본 발명은 수목의 하부에서 수목을 지지하는 지지구의 길이를 용이하게 조절할 수 있도록 하는 구조물에 대한 것으로, 지지부재를 형성하는 제 2 지지관에, 제 1 지지관의 진퇴작용을 물리적으로 구속하는 스토핑 구조를 형성하되, 제1지지관을 구속하는 고정요소를 해제하기 위한 과도한 힘을 가하지 않고, 회전동작에 의해 고정요소를 해제할 수 있도록 하여, 사용의 편의성을 극대화할 수 있다. claims: 안착부재의 하부에 지지부재가 설치된 형태로 구성되고, 상기 지지부재는, 제 1 지지관(10)이 제 2 지지관(20)의 중공부에 삽입된 형태로 이루어져 제 1 지지관의 진퇴거리에 따라 총 길이가 변경하여 설정되도록 구성되고, 제 2 지지관(20)에는 제 1 지지관(10)의 진퇴작용을 구속하는 스토핑 구조물(S)이 형성된 수목용 지지구에 있어서,상기 스토핑 구조물(S)은,제1지지관(10)이 관통하는 중공부를 구비하는 제1브라켓몸체(100);상기 제1브라켓몸체(100)와 끼움결합 형식으로 결합되며, 제2지지관(20)의 중공부와 연통하는 중공부를 가지는 관상의 제2브라켓몸체(210);상기 제1브라켓몸체(100) 내에 안착되며, 상기 제1지지관(10)이 관통하는 중공이 형성되며, 상기 제1브라켓몸체(100)의 내벽에 형성되는 가이드홈(G1, G2)에 테두리부가 밀착하는 고정부재(120); 를 포함하며,상기 제2브라켓몸체(210)의 상부는 경사구조의 받침구조물(230)이 구현되며, 상기 제2브라켓몸체(210)의 회전동작에 따라 상기 받침구조물(230)이 상기 고정부재(120)의 일측을 상승 또는 하강하게 하여, 상기 제1지지관의 구속 및 해제 동작을 구현하는,수목용 지지구조물.안착부재의 하부에 지지부재가 설치된 형태로 구성되고, 상기 지지부재는, 제 1 지지관(10)이 제 2 지지관(20)의 중공부에 삽입된 형태로 이루어져 제 1 지지관의 진퇴거리에 따라 총 길이가 변경하여 설정되도록 구성되고, 제 2 지지관(20)에는 제 1 지지관(10)의 진퇴작용을 구속하는 스토핑 구조물(S)이 형성된 수목용 지지구에 있어서,상기 스토핑 구조물(S)은,제1지지관(10)이 관통하는 중공부를 구비하는 제1브라켓몸체(100);상기 제1브라켓몸체(100)의 전면부 하단에 하측은 개구되며, 상측으로 요입된 형상으로 구현되는 가이드홈(110B);상기 제1브라켓몸체(100)와 끼움결합 형식으로 결합되며, 제2지지관(20)의 중공부와 연통하는 중공부를 가지는 관상의 제2브라켓몸체(210);상기 브라켓몸체(210)의 상에 안착되며, 좌우 회전동작이 가능하도록 상기 브라켓몸체(210) 상에 결합되는 회전몸체(240);상기 제1브라켓몸체(100) 내에 안착되며, 상기 제1지지관(10)이 관통하는 중공이 형성되며, 상기 제1브라켓몸체(100)의 내벽에 상기 고정부재(120)의 테두리부가 밀착하며, 상기 고정부재의 테두리부의 일단에 돌출구조로 형성되는 제2각도조절편(126)이 형성되는 고정부재(120);를 포함하며,상기 회전몸체(240)의 상부 테두리부 상에 돌출구조 받침구조물(250)이 구현되며, 상기 돌출구조 받침구조물(250)은 상기 가이드홈(110B)의 좌우폭에 대응되도록 이동하며,상기 회전몸체(240)0)의 회전동작에 따라 상기 돌출구조 받침구조물(250)이 상기 고정부재(120)의 일측을 상승 또는 하강하게 하여, 상기 제1지지관의 구속 및 해제 동작을 구현하는,수목용 지지구조물., Ltext: 임업, prediction: 임업
23/1059 Row 23: application_number: 1020190162669, combined_string: invention_title: 해충 포획장치 abstract: 해충 포획장치를 제공한다. 본 발명은, 유인제가 용해된 일정량의 유인액이 저장된 내부박스를 교체가능하도록 내부수용하는 외부박스 ; 전원인가시 회전구동되는 회전날개를 갖추어 상기 외부박스의 상부면에 관통형성된 배출구를 통하여 상기 유인제를 상향 배출유도시키는 송풍팬 ; 상기 외부박스의 상부면에 올려지는 지지체를 매개로 상기 외부박스와 결합되고, 상기 배출구를 통해 상향 배출되는 유인제를 측방향으로 확산시키는 확산구를 관통형성하는 외부면에 상기 유인제에 의해서 유인되는 곤충을 내부로 진입유도시키는 진입유도로를 구비하는 유도체 ; 상기 진입유도로를 통하여 상기 유도체의 내부공간으로 진입된 곤충이 탈출하는 탈출공을 관통형성하여 상기 유도체의 개방된 상부를 덮도록 결합되는 덮개체 ; 상기 탈출공에 일단이 연통연결되는 연결관체의 타단과 연통연결되어 상기 연결관체를 따라 유도되는 곤충을 포획하여 수거하는 포집체;를 포함한다. claims: 유인제가 용해된 일정량의 유인액이 저장된 내부박스를 교체가능하도록 내부수용하는 외부박스 ;전원인가시 회전구동되는 회전날개를 갖추어 상기 외부박스의 상부면에 관통형성된 배출구를 통하여 상기 유인제를 상향 배출유도시키는 송풍팬 ;상기 외부박스의 상부면에 올려지는 지지체를 매개로 상기 외부박스와 결합되고, 상기 배출구를 통해 상향 배출되는 유인제를 측방향으로 확산시키는 확산구를 관통형성하는 외부면에 상기 유인제에 의해서 유인되는 곤충을 내부로 진입유도시키는 진입유도로를 구비하는 유도체 ;상기 진입유도로를 통하여 상기 유도체의 내부공간으로 진입된 곤충이 탈출하는 탈출공을 관통형성하여 상기 유도체의 개방된 상부를 덮도록 결합되는 덮개체 ;상기 탈출공에 일단이 연통연결되는 연결관체의 타단과 연통연결되어 상기 연결관체를 따라 유도되는 곤충을 포획하여 수거하는 포집체;를 포함하는, 해충 포획장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

24/1059 Row 24: application_number: 1020190161324, combined_string: invention_title: 수목 지지대 abstract: 본 발명에 따른 수목을 지지하는 수목 지지대는, 일단이 지면에 삽입 고정되고, 상기 수목을 중심으로 복수개로 배치되는 지지프레임과, 상기 지지프레임의 일측에 구비되며, 전면에는 함몰부가 형성되는 한편, 후면에는 'T'자형으로 형성되는 결합부가 마련되되, 상기 결합부의 측면에는 체결볼트가 관통되는 관통공이 형성되고, 상기 결합부의 측부에는 로프를 고정하는 고정홈이 형성되는 리브와, 상기 관통공에 볼트 결합되어 회동 가능하게 설치되고, 단부에는 삽입공이 형성되어 상기 지지프레임의 타단이 삽입고정되는 브라켓 및 상기 리브의 함몰부에 결합되고, 상기 수목의 외주면에 탄력적으로 밀착되는 완충부재를 포함하는 것을 특징으로 한다. claims: 수목을 지지하는 수목 지지대에 있어서,일단이 지면에 삽입 고정되고, 상기 수목을 중심으로 복수개로 배치되는 지지프레임; 상기 지지프레임의 일측에 구비되며, 전면에는 함몰부가 형성되는 한편, 후면에는 'T'자형으로 형성되는 결합부가 마련되되, 상기 결합부의 측면에는 체결볼트가 관통되는 관통공이 형성되고, 상기 결합부의 측부에는 로프를 고정하는 고정홈이 형성되는 리브;상기 관통공에 볼트 결합되어 회동 가능하게 설치되고, 단부에는 삽입공이 형성되어 상기 지지프레임의 타단이 삽입고정되는 브라켓; 및상기 리브의 함몰부에 결합되고, 상기 수목의 외주면에 탄력적으로 밀착되는 완충부재;를 포함하는 것을 특징으로 하는 수목 지지대., Ltext: 임업, prediction: 임업
25/1059 Row 25: application_number: 1020190156768, combined_string: invention_title: 벤질옥시알코올계 화합물을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충을 방제하는 방법 abstract: 본 발명은 벤질옥시알코올계 화합물을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충을 방제하는 방법에 관한 것이다. claims: 벤질옥시알코올계 화합물을 포함하는 소나무재선충 방제용 조성물.제 1항 내지 제 5항 중 어느 하나의 조성물을 식물 또는 토양에 처리하여 소나무재선충을 방제하는 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

26/1059 Row 26: application_number: 1020190156769, combined_string: invention_title: 나프토퀴논계 화합물을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나 무재선충을 방제하는 방법 abstract: 본 발명은 나프토퀴논을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충을 방제하는 방법에 관한 것이다. claims: 나프토퀴논계 화합물을 포함하는 소나무재선충 방제용 조성물.제 1항 내지 제 5항 중 어느 하나의 조성물을 식물 또는 토양에 처리하여 소나무재선충을 방제하는 방법., Ltext: 임업, prediction: 임업
27/1059 Row 27: application_number: 2020190004549, combined_string: invention_title: 멧돼지 퇴치 장치 abstract: 본 고안은 멧돼지 퇴치 장치에 관한 것으로 일단이 지면에 삽입되는 지지부, 일단이 상기 본체의 타단에서 상측으로 연장되어 형성되는 일직선형의 본체, 상기 본체의 타단에 끼움 결합되며, 내측면에 건전지가 설치된 상단 캡, 일단이 상기 상단 캡에 수직하게 결합되며, 타단이 하측으로 절곡되는 한 쌍의 스프링, 상기 스프링의 타단에 부착되는 눈 형상의 야광패치, 상기 야광패치의 후측에 설치되는 발광수단 및 상기 건전지와 상기 발광수단을 전기적으로 연결하는 전선을 포함한다. claims: 일단이 지면에 삽입되는 지지부;일단이 상기 본체의 타단에서 상측으로 연장되어 형성되는 일직선형의 본체;상기 본체의 타단에 끼움 결합되며, 내측면에 건전지가 설치된 상단 캡;일단이 상기 상단 캡에 수직하게 결합되며, 타단이 하측으로 절곡되는 한 쌍의 스프링; 상기 스프링의 타단에 부착되는 눈 형상의 야광패치;상기 야광패치의 후측에 설치되는 발광수단; 및 상기 건전지와 상기 발광수단을 전기적으로 연결하는 전선;을 포함하는 것을 특징으로 하는 멧돼지 퇴치 장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

28/1059 Row 28: application_number: 1020190142717, combined_string: invention_title: 수목 보호판 abstract: 본 발명에 따른 수목 보호판은, 수목을 둘러싸도록 배치되고 물과 양분은 수목 뿌리로 통과시키고 태양광은 차단할 수 있도록 천연 소재를 엮어서 제작되는 제1 천연소재 보호대, 상기 제1 천연소재 보호대의 상부에 놓이고 상기 제1 천연소재 보호대와 동일한 소재로 제작되며, 상기 제1 천연소재 보호대와 상하 방향으로 일부 중첩되도록 배치되는 제2 천연소재 보호대, 및 상기 제1 천연소재 보호대의 하부에 설치되어 양분은 수목 뿌리로 통과시키고 태양광은 차단하는 천연 부직포를 포함하는 것을 특징으로 한다. claims: 수목을 둘러싸도록 배치되고 물과 양분은 수목 뿌리로 통과시키고 태양광은 차단할 수 있도록 천연 소재를 엮어서 제작되는 제1 천연소재 보호대;상기 제1 천연소재 보호대의 상부에 놓이고 상기 제1 천연소재 보호대와 동일한 소재로 제작되며, 상기 제1 천연소재 보호대와 상하 방향으로 일부 중첩되도록 배치되는 제2 천연소재 보호대; 및상기 제1 천연소재 보호대의 하부에 설치되어 양분은 수목 뿌리로 통과시키고 태양광은 차단하는 천연 부직포를 포함하는 것을 특징으로 하는 수목 보호판., Ltext: 임업, prediction: 임업
29/1059 Row 29: application_number: 1020190141698, combined_string: invention_title: 드론용 연무연막 방제장치 abstract: 본 발명에 따른 드론용 연무연막 방제장치는: 드론의 무게 중심 하부에 착탈 가능하게 결합 되는 본체 프레임; 상기 본체 프레임의 중심부에 착탈 가능하게 결합 되는 본체 케이싱; 상기 본체 케이싱의 내부에 구비되고, 내부에는 물, 방제 약제, 바이오 디젤유가 혼합된 혼합물이 내부에 수용되는 약제 탱크; 상기 본체 케이싱의 내부에서 외부로 노출되게 구비되고, 상기 약제 탱크에 연결되어 상기 약제 탱크의 내부에 수용된 혼합물이 외부로 분사되도록 하는 기화 유닛; 및, 상기 약제 탱크와 상기 기화 유닛의 사이에 구비되어 상기 약제 탱크의 내부에 수용된 혼합물이 상기 기화 유닛으로 이동되어 분사되도록 하는 분사 펌프;를 포함하는 것을 특징으로 한다. 이에 의하여, 드론에 연무연막 방제장치를 간편하게 탈부착하여 손쉽게 적용할 수 있고, 무선 조종을 통해 공중을 비행하는 드론에서 방제 약제를 가열하여 연막 또는 연무 상태로 산림과 해안가 등지에서 농작물이나 나무 등에 방제 약제를 살포하여 방제하도록 함으로써, 연막의 넓은 확산력과 연무에 의해 방제 약제의 침투력을 높이고 광범위한 지역을 손쉽고 용이하게 방제하도록 할 수 있는 드론용 연무연막 방제장치를 제공할 수 있다. claims: 드론의 무게 중심 하부에 착탈 가능하게 결합 되는 본체 프레임;상기 본체 프레임의 중심부에 착탈 가능하게 결합 되는 본체 케이싱;상기 본체 케이싱의 내부에 구비되고, 내부에는 물, 방제 약제, 바이오 디젤유가 혼합된 혼합물이 내부에 수용되는 약제 탱크;상기 본체 케이싱의 내부에서 외부로 노출되게 구비되고, 상기 약제 탱크에 연결되어 상기 약제 탱크의 내부에 수용된 혼합물이 외부로 분사되도록 하는 기화 유닛; 및상기 약제 탱크와 상기 기화 유닛의 사이에 구비되어 상기 약제 탱크의 내부에 수용된 혼합물이 상기 기화 유닛으로 이동되어 분사되도록 하는 분사 펌프;를 포함하는 것을 특징으로 하는 드론용 연무연막 방제장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

30/1059 Row 30: application_number: 1020190140576, combined_string: invention_title: 수목관리용 IoT 밴드 및 이를 이용한 수목관리 시스템 abstract: 본 발명은 수목관리용 IoT 밴드 및 이를 이용한 수목관리 시스템에 관한 것이다. 좀 더 상세하게로는 산림관리 등을 목적으로 수목의 생장상황을 측정 및 관찰하기 위해, 수목의 상태를 식별하여 정보를 취득하거나, 수목병해충에 감염된 것으로 의심되는 수목 등에 대한 식별, 시료채취 등을 함에 있어 스마트폰 등 스마트기기를 이용하여 관리대상 수목에 대한 정보를 자동으로 식별하여 수집할 수 있도록 하는, 수목관리용 IoT 밴드와 이를 이용한 수목관리시스템에 관한 것이다. 이를 위하여 본 발명은, 관리대상 수목의 나무줄기를 두를 수 있고, 스마트기기에 의하여 상기 관리대상 수목에 대한 정보가 인식될 수 있는 띠 모양의 밴드로서, 고유코드와 관리정보를 디지털형식으로 포함하고 있는 제1식별수단, 상기 띠의 길이방향을 따라 일련의 숫자가 연속적으로 표시되는 제1표시수단 및 상기 제1표시수단과 평행하게 일련의 숫자가 연속적으로 표시되는 제2표시수단을 상기 띠 모양의 전면에 포함하는 것을 특징으로 하는 것이 바람직하다. claims: 정보시스템을 이용하여 관리대상 수목에 대한 정보를 관리하는 수목관리 시스템으로서,수목관리용 IoT 밴드;상기 수목관리용 IoT 밴드를 인식할 수 있는 스마트기기;통신망을 통하여 상기 스마트기기와 정보를 주고받는 수목관리 서버; 및 상기 관리대상 수목에 대한 정보를 저장하는 수목정보DB; 를 포함하며,상기 수목관리용 IoT 밴드는, 상기 관리대상 수목의 나무줄기를 두를 수 있고, 상기 스마트기기에 의하여 상기 관리대상 수목에 대한 정보가 인식될 수 있는 띠 모양의 밴드로서,- 고유코드와 관리정보를 디지털형식으로 포함하고 있으며, 큐알코드로 이루어진 제1식별수단,- 상기 띠의 길이방향을 따라 일련의 숫자가 연속적으로 표시되는 제1표시수단 및 - 상기 제1표시수단과 평행하게 일련의 숫자가 연속적으로 표시되는 제2표시수단을 상기 띠 모양의 전면에 포함하고,- 상기 띠를 상기 나무줄기에 둘러싸서 고정시킬 수 있는 고정수단을 상기 띠 모양의 후면에 포함하며,- 상기 제1식별수단은 상기 띠의 시작부분에 위치하며,- 상기 고정수단을 이용하여 상기 띠를 상기 나무줄기에 둘러싸서 고정시켰을 때, 상기 제1식별수단 옆에 상기 나무줄기의 지름 및 둘레가 표시되되, 상기 제1식별수단에 가장 근접하게 위치하는 숫자 중, 상기 제1표시수단의 숫자는 상기 나무줄기의 지름이고, 상기 제2표시수단의 숫자는 상기 나무줄기의 둘레이며,상기 스마트기기는, 상기 관리대상 수목을 둘러싸며 고정되어 있는 상기 수목관리용 IoT 밴드 중 상기 제1식별수단이 포함된 특정부분이 촬영되면, 상기 관리대상 수목 대한 고유코드, 관리정보 및 크기를 한꺼번에 식별하되,- 상기 제1식별수단으로부터 상기 고유코드 및 상기 관리정보를 식별해내고,- 상기 특정부분 중에서 상기 제1식별수단에 가장 근접하게 위치한 숫자를 OCR기능을 통하여 읽어 들인 후, 읽어 들인 숫자 중 상기 제1표시수단의 숫자를 상기 관리대상 수목의 지름으로 인식하고, 상기 제2표시수단의 숫자를 상기 관리대상 수목의 둘레로 인식하며,- 상기 지름 또는 상기 둘레를 포함하는 상기 관리대상 수목의 크기정보를 생성한 후, 상기 고유코드, 상기 관리정보, 상기 크기정보, 상기 수목관리용 IoT 밴드가 촬영된 장소에 대한 GPS좌표, 촬영일시 및 담당자정보를 포함하는 관리대상 수목정보를 생성하여 상기 수목관리 서버에 전송하며,상기 수목관리 서버는,- 상기 관리대상 수목정보를 수신하는 경우, 상기 수목정보DB에 저장하고- 상기 스마트기기 또는 단말기로부터 정보제공 요청 시 상기 수목정보DB에 저장된 정보를 제공하는; 것을 특징으로 하는, 수목관리용 IoT 밴드를 이용한 수목관리 시스템, Ltext: 임업, prediction: 임업
31/1059 Row 31: application_number: 1020190138634, combined_string: invention_title: 분광라이브러리와 무인기의 다중분광영상을 이용한 산불 피해 등급 분석 장치 및 방법 abstract: 본 발명의 실시예에 따른 산불 피해 등급 분석 장치는, 산불 피해 지역을 촬영한 적어도 하나의 다중분광영상을 입력받는 입력부, 상기 적어도 하나의 다중분광영상을 전처리하는 전처리부, 상기 전처리된 적어도 하나의 다중분광영상을 하나의 영상으로 집성하여 모자이크(Mosaic) 반사율 영상으로 변환하는 모자이크 반사율 영상 생성부 및 상기 모자이크 반사율 영상을 기반으로 산불 피해 등급별 분광반사율과 상기 모자이크 반사율 영상 화소 각각에 대한 분광반사율의 유사도를 산출하여 산불 피해 등급을 검출하는 산불 피해 등급 검출부를 포함할 수 있다. claims: 산불 피해 등급 분석 장치에 있어서,산불 피해 지역을 촬영한 적어도 하나의 다중분광영상을 입력받는 입력부;상기 적어도 하나의 다중분광영상을 전처리하는 전처리부;상기 전처리된 적어도 하나의 다중분광영상을 하나의 영상으로 집성하여 모자이크(Mosaic) 반사율 영상으로 변환하는 모자이크 반사율 영상 생성부; 및상기 모자이크 반사율 영상을 기반으로 산불 피해 등급별 분광반사율과 상기 모자이크 반사율 영상의 화소 각각에 대한 분광반사율의 유사도를 산출하여 산불 피해 등급을 검출하는 산불 피해 등급 검출부를 포함하는 것을 특징으로 하는 산불 피해 등급 분석 장치.산불 피해 등급 분석 방법에 있어서,산불 피해 지역을 촬영한 적어도 하나의 다중분광영상을 입력받는 단계;상기 적어도 하나의 다중분광영상을 기하 보정과 복사 보정을 수행하는 전처리 단계;상기 전처리된 적어도 하나의 다중분광영상을 하나의 영상으로 집성하여 모자이크(Mosaic) 반사율 영상으로 변환하는 단계; 및상기 모자이크 반사율 영상을 기반으로 산불 피해 등급별 분광반사율과 상기 모자이크 반사율 영상의 화소 각각에 대한 분광반사율의 유사도를 산출하여 산불 피해 등급을 검출하는 단계를 포함하는 것을 특징으로 하는 산불 피해 등급 분석 방법.제12항에 있어서,상기 분광반사율 유사도 산출 단계는,n차원(상기 n은 1보다 큰 자연수)에서 상기 선택된 분광반사율 데이터와 상기 모자이크 반사율 영상의 화소 각각에 대한 분광반사율 데이터 사이의 각도인 분광각을 구하고, 상기 분광각을 기반으로 분광반사율 유사도를 산출하는 것을 특징으로 하는 산불 피해 등급 분석 장치.제13항에 있어서,상기 산불 피해 등급 부여 단계는,상기 분광각 중 최소값에 대응되는 산불 피해 등급 분광반사율 데이터를 상기 모자이크 반사율 영상에 부여하는 것을 특징으로 하는 산불 피해 등급 분석 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

32/1059 Row 32: application_number: 1020190136254, combined_string: invention_title: 소나무재선충병 매개하늘소용 유인제와 살충제의 혼합 사용을 통한 소나무재선충병의 방제방법 abstract: 본 발명은 소나무재선충병 매개하늘소용 유인제와 소나무재선충병 매개하늘소용 살충제를 함께 살포하는 것을 특징으로 하는 소나무재선충병의 방제방법에 관한 것이다.본 발명의 방법은 소나무재선충병 매개하늘소를 유인하는 유인제를 소나무 재선충 매개하늘소를 살충하는 살충제와 함께 살포함으로써 소나무재선충병 매개하늘소 유인트랩의 장점인 우수한 유인력에 의해 유인된 매개하늘소를 살충제로 살충함으로써 살충제의 살충효율을 높여 소나무재선충병을 효과적으로 방제할 수 있다. claims: 소나무재선충병 매개하늘소용 유인제와 소나무재선충병 매개하늘소용 살충제를 함께 살포하는 것을 특징으로 하는 소나무재선충병의 방제방법., Ltext: 임업, prediction: 임업
33/1059 Row 33: application_number: 1020190129296, combined_string: invention_title: 친환경재를 이용한 수목용 다기능 생육매트 및 그 제조방법 abstract: 본 발명은 친환경재를 이용한 수목용 다기능 생육매트 및 그 제조방법에 관한 것으로, 더욱 상세하게는 매트 본체(100);와 상기 매트 본체(100)의 중앙에 형성되어 수목이 위치되는 개구부(200);를 포함하되, 상기 매트 본체(100)는, 버개스, 코코칩 및 코코섬유를 포함하는 것을 특징으로 한다. 본 발명의 친환경재를 이용한 수목용 다기능 생육매트 및 그 제조방법에 의하면, 내구연한의 경과시 자연 부식되어 환경피해가 전혀 없으며, 친환경 유기질 비료로 작용할 수 있고, 우수한 보수력으로 인해 수목 생장기에 가뭄 피해를 예방할 수 있으며, 동절기 동해방지의 효과가 있어 수목의 고사율을 낮출 수 있다는 장점이 있다. 아울러, 잡초억제 효과, 발근촉진 효과는 물론, 미관적 향상 효과가 있으며, 제조비용이 낮아 상용화가 가능하다는 장점이 있다. claims: 버개스, 코코칩 및 코코섬유를 혼합하는 단계와,상기 혼합된 혼합물을 압축 및 니들펀칭하여 매트로 성형하는 단계와,상기 성형된 매트의 상부 및 하부에 수용성 수지 접착제를 살포하는 단계와,상기 수용성 수지 접착제가 살포된 매트를 건조하는 단계와,상기 건조된 매트를 재단하여 매트 본체(100)를 제조하고, 상기 매트 본체(100)의 중앙에 개구부(200)를 형성하는 단계를 포함하며,상기 수용성 수지 접착제를 살포하는 단계 시,상기 수용성 수지 접착제에 발근촉진제 및 친환경 살균살충제를 혼합하여 살포하며,상기 수용성 수지 접착제는 폴리비닐알코올(PVA)이고,상기 코코섬유, 버개스 및 코코칩의 사용량은, 상기 코코섬유 60~80중량%, 상기 버개스 10~20중량% 및 상기 코코칩 10~20중량%인 것을 특징으로 하는 친환경재를 이용한 수목용 다기능 생육매트의 제조방법.버개스를 포설하여 버개스층(110)을 형성하는 단계와,상기 버개스층(110)의 상부에 코코칩을 포설하여 코코칩층(120)을 형성하는 단계와,상기 코코칩층(120)의 상부에 코코섬유를 포설하여 코코섬유층(130)을 형성하는 단계와,상기 버개스층(110)의 하부 및 코코섬유층(130)의 상부에 수용성 수지 접착제를 살포하여 상기 버개스층(110), 상기 코코칩층(120) 및 상기 코코섬유층(130)이 상호 접착되도록 하는 단계와, 상기 수용성 수지 접착제가 살포된 매트를 건조 및 압축하는 단계와,상기 건조된 매트를 재단하여 매트 본체(100)를 제조하고, 상기 매트 본체(100)의 중앙에 개구부(200)를 형성하는 단계를 포함하며,상기 수용성 수지 접착제를 살포하는 단계 시,상기 수용성 수지 접착제에 발근촉진제 및 친환경 살균살충제를 혼합하여 살포하며,상기 수용성 수지 접착제는 폴리비닐알코올(PVA)이고, 상기 코코섬유, 버개스 및 코코칩의 사용량은, 상기 코코섬유 60~80중량%, 상기 버개스 10~20중량% 및 상기 코코칩 10~20중량%인 것을 특징으로 하는 친환경재를 이용한 수목용 다기능 생육매트의 제조방법.제6항 또는 제7항의 제조방법으로 제조되는 것을 특징으로 하는 수목용 다기능 생육매트., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

34/1059 Row 34: application_number: 1020190127989, combined_string: invention_title: 고정밀 측량 기법을 활용하는 산림 조사 방법 및 장치 abstract: 산림 조사를 위한 작업 타입을 설정하고, 산림 조사에 있어서 요구되는 측량의 정밀도를 일반/정밀 측량 방식 중 어느 하나로 설정하고, 산림 내의 조사지에서, 설정된 정밀도에 기반하여 조사지의 위치 정보를 획득하고, 해당 조사지와 관련하여 사용자로부터 입력된 정보를 획득하여 조사지에 대한 산림 조사 데이터를 생성하는, 측량 기법을 활용하고 모바일 단말을 이용하여 산림을 조사하는 산림 조사 방법이 제공된다. claims: 측량 기법을 활용하고 모바일 단말을 이용하여 산림을 조사하는 산림 조사 방법에 있어서, 상기 산림 조사 방법은 상기 모바일 단말에 의해 수행되고,상기 모바일 단말에 의해, 상기 산림을 조사하는 산림 조사를 위한 작업 타입을 설정하는 단계; 상기 모바일 단말에 의해, 상기 산림 조사에 있어서 요구되는 측량의 정밀도를 설정하는 단계;상기 모바일 단말에 의해, 상기 산림 내의 조사지에서, 상기 설정된 정밀도에 기반하여 상기 조사지의 위치 정보를 획득하는 단계;상기 모바일 단말에 의해, 상기 조사지와 관련하여 사용자로부터 입력된 정보를 획득하는 단계; 및상기 모바일 단말에 의해, 상기 획득된 위치 정보 및 상기 입력된 정보에 기반하여 상기 조사지에 대한 산림 조사 데이터를 생성하는 단계를 포함하고,상기 측량의 정밀도를 설정하는 단계는, 상기 측량의 정밀도를 설정하기 위한 복수의 옵션들을 제공하는 단계 - 상기 복수의 옵션들은 일반 측량 방식을 설정하기 위한 제1 옵션, 정밀 측량 방식을 설정하기 위한 제2 옵션 및 고정밀 측량 방식을 설정하기 위한 제3 옵션을 포함함 -; 및 상기 제1 옵션 내지 상기 제3 옵션 중 어느 하나로 상기 측량의 정밀도를 설정하는 단계를 포함하고, 상기 위치 정보를 획득하는 단계는, 상기 측량의 정밀도가 상기 제1 옵션으로 설정되면, 상기 모바일 단말의 GPS 장치를 사용하여 상기 위치 정보를 획득하고, 상기 측량의 정밀도가 상기 제2 옵션으로 설정되면, 상기 모바일 단말의 GPS 장치를 사용하여 획득된 상기 조사지에 대한 복수의 위치 값들 중 평균 값 또는 상기 복수의 위치 값들에 기반한 보간법에 따라 획득된 위치 값을 상기 위치 정보로서 획득하고, 상기 측량의 정밀도가 상기 제3 옵션으로 설정되면, 상기 모바일 단말과 통신하는 DGPS 장치로부터 획득된 위치 값을 상기 위치 정보로서 획득하고,상기 산림 조사 방법은,상기 모바일 단말에 의해, 상기 설정된 작업 타입 별로, 상기 사용자가 상이한 정보를 입력 가능하도록 하는 입력 항목을 포함하는 사용자 인터페이스를 제공하는 단계를 더 포함하고,상기 산림 조사는, 상기 산림을 복수의 표준지들로 분할하여 각각의 표준지를 조사하는 표준지 조사이고, 상기 표준지들의 각각은 형태 및 면적이 미리 설정되어 있고, 상기 사용자 인터페이스를 제공하는 단계는, 상기 표준지들 중 조사의 대상이 되는 표준지에 포함된 나무들의 각 나무의 상태를 입력 가능하도록 하는 상기 각 나무에 대응하는 입력 항목을 포함하는 사용자 인터페이스를 제공하고,상기 각 나무에 대응하는 입력 항목은 상기 표준지에 대한 조사점에 대응하고,상기 각 나무에 대해 입력된 상기 각 나무의 상태에 따라 상기 각 나무에 대응하는 입력 항목은 상이하게 표시되는, 산림 조사 방법.제1항 내지 제7항 및 제10항 중 어느 한 항의 방법을 수행하는 컴퓨터 판독 가능 기록매체에 저장된 컴퓨터 프로그램., Ltext: 임업, prediction: 임업
35/1059 Row 35: application_number: 1020190126958, combined_string: invention_title: 표고버섯균사체를 포함하는 탄저병 방제용 조성물 및 이를 이용하여 탄저병을 방제하는 방법 abstract: 본 발명은 표고버섯균사체를 유효성분으로 포함하는 바이러스병 및 탄저병 방제용 조성물 및 이를 이용하여 원예식물의 바이러스병 및 탄저병을 방제하는 방법에 관한 것으로, 본 발명에 따른 표고버섯 균사체를 포함하는 조성물은 탄저병 및 바이러스병으로 인해 발생되는 농작물의 포자점질물 및 진물 형성을 완전하고 빠르게 억제하고 병의 치료 속도가 월등하게 증진되는 장점이 있다. 또한, 상기 조성물은 실내 및 실외 농작물 모두 효과가 탁월하며, 1회 살포만으로도 충분한 방제 효과를 나타내어 경제적인 장점이 있다. 더욱이, 본 발명의 조성물은 중금속을 함유하지 아니한 의약품으로 조성되므로 농약공해를 피할 수 있으며 효과가 탁월하여 농사의 병충해를 획기적으로 구제할 수 있게 될 것이다. claims: 원예작물의 탄저병 방제용 조성물로서,표고버섯 균사체를 유효성분으로 포함하고,표고버섯 균사체를 10 내지 50 중량% 포함하며,상기 원예작물은 고추, 피망, 사과, 감, 참외, 토마토, 방울토마토, 참깨 및 들깨로 이루어진 군에서 선택된 것임을 특징으로 하는 원예작물의 탄저병 방제용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

36/1059 Row 36: application_number: 1020190124490, combined_string: invention_title: 해충 제거 장치 abstract: 본 발명은 교대로 배치되며 상호 이격된 제1와이어와 제2와이어를 포함하는 포집부; 상기 제1와이어 및 상기 제2와이어 각각에 고전압의 교류전류를 인가하는 고전압 공급부; 및 상기 포집부에 일단이 연결되며 길이 조절이 가능한 손잡이부; 를 포함하고, 상기 고전압 공급부에서 상기 제1와이어 및 제2와이어에 고전압을 인가 시, 상기 제1와이어와 제2와이어 사이에서 아크 방전이 발생하는 해충 제거 장치를 개시한다. claims: 절연성의 플레이트, 상기 플레이트 상부에 이격되어 배치된 절연성의 링부재, 상기 플레이트와 상기 링부재를 연결하며, 교대로 배치되며 상호 이격된 제1와이어 및 제2와이어를 포함하고, 상기 플레이트, 링부재, 제1와이어 및 제2와이어로 형성된 포집 공간을 갖는 포집부;상기 제1와이어 및 상기 제2와이어 각각에 고전압의 교류전류를 인가하는 고전압 공급부;상기 포집부에 일단이 연결되며 길이 조절이 가능한 손잡이부; 및상기 손잡이부의 타단 영역에 배치되며, 상기 고전압 공급부의 동작을 제어하는 제어부; 를 포함하고,상기 고전압 공급부에서 상기 제1와이어 및 제2와이어에 고전압을 인가 시, 상기 제1와이어와 제2와이어 사이에서 아크 방전이 발생하고,상기 제어부는,상기 고전압 공급부의 온/오프를 제어하는 온/오프 스위치 및 상기 제1와이어 및 상기 제2와이어 각각에 인가되는 고전압의 세기를 조절하는 전압 세기 조절 스위치를 포함하고,고전압의 세기를 조절함으로써, 해충 또는 야생동물에 가해지는 충격 정도를 조절하는 것이 가능하고,상기 제1와이어와 제2와이어 사이에 해충이나 말벌집과 같은 도체가 배치되는 경우 도체를 통해 고온의 전기 스파크가 흘러, 상기 포집 공간에 위치하여 고온의 전기 스파크가 흐른 해충이나 말벌집은 전소시키는 해충 제거 장치., Ltext: 임업, prediction: 임업
37/1059 Row 37: application_number: 1020190124863, combined_string: invention_title: 기온완화를 위한 기온저감활동의 효과분석 시스템 abstract: 본 발명은 기온 상승 현상에 대한 기온완화 대응책으로 실시되는 기온저감활동의 효과를 분석하는 기온저감활동 효과분석 시스템으로서, 복사에너지 정보를 포함하는 조사대상 지역의 위성영상을 획득하는 위성영상 획득부; 상기 복사에너지 정보와 절대온도의 관계를 통해 밝기온도를 산출하고, 상기 밝기온도와 지표피복에 따른 방출률의 관계를 통해 지표면 온도를 산출하는 지표면 온도 산출부; 상기 조사대상 지역의 지형 및 지물적 특징을 반영하고, 상기 조사대상 지역에서 상기 기온저감활동의 시뮬레이션을 위한 모델을 산출하는 기온저감활동 모델링부; 상기 모델에 상기 기온저감활동을 적용하며, 상기 기온저감활동의 성능 실험을 위한 조건을 설정하고 적용되는 프로그램을 설계하는 프로그래밍부; 및 상기 프로그램을 통해 상기 조사대상 지역에서의 상기 기온저감활동의 성능을 분석하는 분석부를 포함하고, 상기 기온저감활동 모델링부는, 종관기상관측시스템(ASOS) 및 자동기상관측시스템(AWS)에서 측정된 기상정보를 획득하고, 상기 지표면 온도와 상기 기상정보를 이용하여 기상자료를 생성하는 기상자료 구축부; 상기 기상자료에 따른 기상 현상에서 발생하는 유체 또는 난류의 흐름을 방정식을 이용하여 분석 및 반영하는 정보처리부; 상기 지표면 온도 및 상기 기상자료를 반영하고, 상기 조사대상 지역의 복수의 구조물을 포함하는 지형지물의 특징을 반영함으로써 실제 환경과 유사한 환경을 구현하는 변환 알고리즘을 수행하는 지형지물 설계부; 상기 조사대상 지역의 수평 및 연직 에너지 평형을 분석하고, 상기 지형지물 및 상기 구조물의 열플럭스, 현열플럭스의 난류플럭스의 특성을 반영하여 상기 조사대상 지역의 표면온도를 산출하는 표면온도 산출부; 및 상기 기상자료 구축부, 상기 정보처리부, 상기 지형지물 설계부 및 상기 표면온도 산출부를 통해 상기 조사대상 지역의 특성이 반영된 모델을 산출하는 결과산출부를 포함하여, 조사대상 지역에서의 기온저감활동의 효과 및 활용성을 판단할 수 있고, 폭염관련 대응정책과 연계하여 효과적인 관리방향을 제시할 수 있는 것을 특징으로 한다. claims: 기온 상승 현상에 대한 기온완화 대응책으로 실시되는 기온저감활동의 효과를 분석하는 기온저감활동 효과분석 시스템으로서,복사에너지 정보를 포함하는 조사대상 지역의 위성영상을 획득하는 위성영상 획득부;상기 복사에너지 정보와 절대온도의 관계를 통해 밝기온도를 산출하고, 상기 밝기온도와 지표피복에 따른 방출률의 관계를 통해 지표면 온도를 산출하는 지표면 온도 산출부; 상기 조사대상 지역의 지형 및 지물적 특징을 반영하고, 상기 조사대상 지역에서 상기 기온저감활동의 시뮬레이션을 위한 모델을 산출하는 기온저감활동 모델링부;상기 모델에 상기 기온저감활동을 적용하며, 상기 기온저감활동의 성능 실험을 위한 조건을 설정하고 적용되는 프로그램을 설계하는 프로그래밍부; 및상기 프로그램을 통해 상기 조사대상 지역에서의 상기 기온저감활동의 성능을 분석하는 분석부를 포함하고,상기 기온저감활동 모델링부는,종관기상관측시스템(ASOS) 및 자동기상관측시스템(AWS)에서 측정된 기상정보를 획득하고, 상기 지표면 온도와 상기 기상정보를 이용하여 기상자료를 생성하는 기상자료 구축부;상기 기상자료에 따른 기상 현상에서 발생하는 유체 또는 난류의 흐름을 방정식을 이용하여 분석 및 반영하는 정보처리부; 상기 지표면 온도 및 상기 기상자료를 반영하고, 상기 조사대상 지역의 복수의 구조물을 포함하는 지형지물의 특징을 반영함으로써 실제 환경과 유사한 환경을 구현하는 변환 알고리즘을 수행하는 지형지물 설계부;상기 조사대상 지역의 수평 및 연직 에너지 평형을 분석하고, 상기 지형지물 및 상기 구조물의 열플럭스, 현열플럭스의 난류플럭스의 특성을 반영하여 상기 조사대상 지역의 표면온도를 산출하는 표면온도 산출부; 및상기 기상자료 구축부, 상기 정보처리부, 상기 지형지물 설계부 및 상기 표면온도 산출부를 통해 상기 조사대상 지역의 특성이 반영된 모델을 산출하는 결과산출부를 포함하는 기온저감활동 효과분석 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

38/1059 Row 38: application_number: 1020190117677, combined_string: invention_title: 말레이즈 트랩, 비행간섭 트랩 및 피트폴 트랩기능을 갖는 곤충류 복합 포충장치 abstract: 본 발명은, 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ; 상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및 상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함한다. claims: 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 중앙연결부는 상기 중앙바, 전,후방 수직바 및 제1,2,3 및 4수평바에 접해지는 한쌍의 상부연결판과, 상기 제1,2,3 및 4수평바에 접해지는 하부연결판을 포함하고, 상기 한쌍의 상부연결판은 상기 중앙바의 외면에 접하도록 연장되는 고정편과, 상기 전,후방 수직바의 외면에 접하도록 연장되는 수직편 및 상기 제1,2,3 및 4수평바의 외면에 접하도록 연장되는 수평편을 포함하는 것을 특징으로 하는 곤충류 복합 포충장치. 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 프레임부는 상기 전,후방 수직바의 수직상태를 유지하는 제1바홀더를 포함하고, 상기 제1바홀더는 상기 전,후방 수직바의 각 하단이 회동가능하게 조립되는 한쌍의 상부연결판의 수직편을 덮도록 상기 전,후방 수직바에 힌지핀을 매개로 일단이 회동가능하게 조립되는 ㄷ단면상의 덮개판을 포함하는 것을 특징으로 하는 곤충류 복합 포충장치. 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 프레임부는 상기 제1,2,3 및 4수평바의 수평상태를 유지하는 제2바홀더를 포함하고 상기 제2바홀더는 상기 제1,2,3 및 4수평바의 각 일단이 회동가능하게 조립되는 한쌍의 상부연결판의 수평편과 하부연결판의 단부를 덮도록 상기 제1,2,3 및 4수평바에 힌지핀을 매개로 일단이 회동가능하게 조립되는 ㄷ단면상의 덮개판을 포함하는 것을 특징으로 하는 곤충류 복합 포충장치. 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 전방 수직바는 상기 포집부가 상단에 고정설치되는 상부수직바와, 상기 중앙연결부와 하단이 연결되는 하부수직바와, 상기 상부수직바의 하단에 구비되는 상부경첩과 회동가능하게 조립되는 하부경첩을 상기 하부수직바의 상단에 구비하는 경첩부 및 상기 하부수직바의 상단을 덮도록 상부수직바의 하단에 힌지핀을 매개로 일단이 회동가능하게 조립되는 ㄷ단면상의 덮개판으로 이루어지는 제4바홀더를 포함하여, 상기 후방 수직바보다 상대적으로 높은 높이를 갖도록 상대적으로 길게 구비되는 것을 특징으로 하는 곤충류 복합 포충장치. 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 중앙바는 상기 전방 수직바와 중앙연결부를 매개로 일단이 조립되는 제1중앙바와, 상기 후방 수직바와 다른 중앙연결부를 매개로 일단이 조립되는 제2중앙바와, 상기 제1,2중앙바와 양단이 힌지핀을 매개로 하여 회동가능하게 조립되는 한쌍의 중앙연결판 및 상기 제1중앙바의 타단을 덮도록 제2중앙바의 타단에 힌지핀을 매개로 회동가능하게 조립되는 ㄷ단면상의 덮개판으로 이루어지는 제5바홀더를 포함하는 것을 특징으로 하는 곤충류 복합 포충장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

39/1059 Row 39: application_number: 1020190111217, combined_string: invention_title: 산불 재해 감시 서버 abstract: 본 발명은 산불 재해 감시 서버에 관한 것이다. 본 발명은, 송수신부(410), 제어부(420) 및 데이터베이스(430)를 포함하며, 제어부(420)는, LoRa 화재 센서 장치 그룹(100g)을 구성하는 각 LoRa 화재 센서 장치(100)의 연기량 정보, 온도 정보, 열온도 정보 중 적어도 하나 이상을 LoRa 수신장치(200)를 통해 IoT 네트워크(300)를 통해 수신하도록 송수신부(410)를 제어하며, 수신시 LoRa 수신장치(200)로부터 각 LoRa 화재 센서 장치(100)의 식별번호도 함께 수신하도록 송수신부(410)를 제어하는 것을 특징으로 하는 정보 수집 모듈(421); 을 포함하는 것을 특징으로 한다.이에 의해, 화재 원점의 위치, 화재의 강도, 화재의 방향 정보를 포함하는 화재 정보를 화재 구호 요원은 모니터링된 화면으로 제공받음으로써, 화재로부터 산림 자원을 보다 효율적으로 보호하도록 하는 효과를 제공한다. claims: 송수신부(410), 제어부(420) 및 데이터베이스(430)를 포함하며, 제어부(420)는, LoRa 화재 센서 장치 그룹(100g)을 구성하는 각 LoRa 화재 센서 장치(100)의 연기량 정보, 온도 정보, 열온도 정보 중 적어도 하나 이상을 LoRa 수신장치(200)를 통해 IoT 네트워크(300)를 통해 수신하도록 송수신부(410)를 제어하며, 수신시 LoRa 수신장치(200)로부터 각 LoRa 화재 센서 장치(100)의 식별번호도 함께 수신하도록 송수신부(410)를 제어하며, 각 LoRa 화재 센서 장치(100)의 식별번호를 메타데이터로 연기량 정보, 온도 정보, 열온도 정보 중 수신된 정보를 데이터베이스(430)에 저장하는 정보 수집 모듈(421);적어도 하나 이상의 LoRa 화재 센서 장치(100)에서 연기량 정보가 수신되는 경우, 연기량 정보가 수신된 LoRa 화재 센서 장치(100)의 식별번호와 매칭되는 위치정보를 데이터베이스(430)에서 추출한 뒤, 추출된 위치정보가 이웃하는지 여부를 분석하고, 이웃하는 LoRa 화재 센서 장치(100)를 추출한 뒤, 이웃하는 적어도 2개 이상의 LoRa 화재 센서 장치(100)의 연기량 정보가 미리 설정된 연기량 오차 범위 이내이고, 이웃하는 2개의 LoRa 화재 센서 장치(100)의 각 연기량 정보가 수신된 시간 정보가 이웃하는 2개의 LoRa 화재 센서 장치(100)의 거리에 비례하는 미리 설정된 시간 오차 범위 이내인 경우 이웃하는 LoRa 화재 센서 장치(100)가 설치된 커버리지 전체를 1차의 화재 확산 지점으로 분석하여 데이터베이스(430)에 저장하고, 이웃하는 LoRa 화재 센서 장치(100) 중 가장 연기량 정보의 정량적 수치가 큰 LoRa 화재 센서 장치(100)가 설치된 커버리지를 화재 원점으로 분석하여 LoRa 화재 센서 장치(100)의 위치정보와 커버리지 정보를 데이터베이스(430)에 LoRa 화재 센서 장치(100)의 식별번호를 메타데이터로 저장하며,다른 LoRa 화재 센서 장치(100)에 의해 연기량 정보가 수신됨이 없는 하나의 LoRa 화재 센서 장치(100)에 의해 연기량 정보가 수신되는 경우 LoRa 화재 센서 장치(100)의 위치정보와 커버리지 정보를 데이터베이스(430)에 화재 원점 주의 대상으로 데이터베이스(430)에 저장하고, 하나의 LoRa 화재 센서 장치(100)를 중심으로 이웃하는 다른 적어도 하나 이상의 LoRa 화재 센서 장치(100)에 의해 연기량 정보가 수신되는지 여부를 모니터링하도록 하기 위해 이웃하는 다른 적어도 하나 이상의 LoRa 화재 센서 장치(100)의 위치 정보와 커버리지 정보를 데이터베이스(430)에서 추출한 뒤, 화재 원점 주의 대상인 LoRa 화재 센서 장치(100)의 위치정보와 커버리지 정보와 함께, 화재 원점 주의 대상인 LoRa 화재 센서 장치(100)의 식별번호를 메타데이터로 데이터베이스(430)에 저장할 뿐만 아니라, IoT 네트워크(300)를 통해 화재 구호 요원 단말(600)로 제공하는 화재 원점 분석 모듈(422);화재 원점 분석 모듈(422)에 의해 화재 원점으로 분석된 LoRa 화재 센서 장치(100)의 식별번호를 메타데이터로 데이터베이스(430)에 저장된 온도 정보, 열온도 정보를 제 1 화재 강도 예비 정보로 추출하고, 화재 원점 분석 모듈(422)에 의해 1차로 분석된 화재 지점으로 분석된 화재 원점으로 분석된 LoRa 화재 센서 장치(100)를 포함하되 화재 원점으로 분석된 LoRa 화재 센서 장치(100)와 이웃하여 임계 범위 내로 연기량이 발생된 것으로 분석된 모든 LoRa 화재 센서 장치(100)가 설치된 커버리지 전체 정보를 제 2 화재 강도 예비 정보로 추출하고, 그리고 각 LoRa 화재 센서 장치(100)에 의해 제공된 온도 정보, 열온도 정보를 데이터베이스(430)에서 제 3 화재 강도 예비 정보로 추출하고, 제 1 화재 강도 예비 정보, 제 2 화재 강도 예비 정보, 제 3 화재 강도 예비 정보를 분석하여 화재 강도를 생성하며, 제 2 화재 강도 예비 정보에 해당하는 커버리지가 미리 설정된 제 1 면적 미만의 산림 면적을 파괴하는 경우 경미한 산불, 미리 설정된 제 1 면적 이상에서 미리 설정된 제 2 면적 미만인 경우보통 산불, 미리 설정된 제 2 면적 이상에서 미리 설정된 제 3 면적 미만인 경우 무서운 산불, 미리 설정된 제 3 면적 이상인 경우 극한의 산불로 분석하여 화상 데이터로 생성하고, 4 단계의 화재 강도인 경미한 산불, 보통 산불, 무서운 산불, 극한의 산불에 대해서 각 커버리지의 변동에 따라 화재 강도를 재설정하며, 4 단계의 화재 강도를 위한 제 2 화재 강도 예비 정보의 단계별 정량적 수치에 제 1 화재 강도 예비 정보의 온도 정보에 대한 제 1 가중치에 따른 정량적 수치와 제 1 화재 강도 예비 정보의 열온도 정보에 대한 제 2 가중치에 따른 정량적 수치, 그리고 제 3 화재 강도 예비 정보를 구성하는 복수의 LoRa 화재 센서 장치(100)에 대한 온도 정보에 대한 화재 원점으로부터의 거리에 비례하는 제 3 가중치에 따른 정량적 수치와 열온도 정보에 대한 화재 원점으로부터의 거리에 비례하는 제 4 가중치에 따른 정량적 수치를 모두 합산한 전체의 정량적 수치를 통해 향후 화재가 현재의 4 단계의 화재 강도에서 얼마나 퍼질 것이라는 화재 예측 정보를 생성하여, 생성된 화재 예측 정보는 데이터베이스(430)에 저장하며, 제 1 내지 제 4 가중치에 대해서는 제 1 가중치에서 제 4 가중치로 갈수록 낮아지도록 설정한 값을 활용하는 화재 강도 분석 모듈(423); 을 포함하는 것을 특징으로 하는 산불 재해 감시 서버., Ltext: 임업, prediction: 임업
40/1059 Row 40: application_number: 1020190110085, combined_string: invention_title: 천적류의 지속 방사형 구조체 abstract: 천적류의 지속 방사형 구조체로서, 내부에 하측으로 개방된 공간부가 형성되며 천적류 방사를 위하여 형성되는 하나 이상의 방사구를 포함하는 용기부; 및 상기 용기부의 하단부에 분리 가능하게 결합되는 뚜껑부;를 포함하며, 상기 공간부에는 먹이 응애가 포함된 배지와 상기 천적류가 수용되는 구성을 마련함으로써, 농업 토양 해충의 천적류를 토양에 장기간 지속 방사시켜 천적류의 작물 정착도를 향상시키고 해충 방제 효율을 향상시키며 천적 활용 비용 및 노동력을 절감할 수 있게 된다. claims: 내부에 하측으로 개방된 공간부가 형성되며 천적류 방사를 위하여 형성되는 하나 이상의 방사구를 포함하는 용기부;상기 용기부의 하단부에 분리 가능하게 결합되는 뚜껑부;상기 공간부의 하측에 수용되는 수분 처리된 왕겨배지;상기 공간부 내에서 상기 왕겨배지 위에 배치되는 왕겨, 먹이 응애 및 상기 천적류의 혼합물; 및상기 공간부 내에서 상기 혼합물 위에 배치되는 상기 먹이 응애의 먹이원;을 포함하는 것을 특징으로 하는, 천적류의 지속 방사형 구조체., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

41/1059 Row 41: application_number: 1020190110176, combined_string: invention_title: 작물 이미지의 병해충 검출 방법 및 장치 abstract: 본 발명은 작물 이미지의 병해충 검출 방법 및 장치에 관한 것으로서, 본 발명의 일 실시 예에 따른 병해충 검출 방법은, 이미지 처리부가 작물 이미지를 수퍼픽셀(superpixel) 단위로 분할하는 단계, 이미지 처리부가 수퍼픽셀의 윤곽(outline)에 외접하는 경계박스를 생성하는 단계, 필터링부가 경계박스에 포함된 수퍼픽셀 이외의 배경영역을 제거하는 단계, 데이터 분석부가 합성곱신경망(Convolutional Neural Network, CNN)을 이용하여 특정 작물의 병해충 종류를 기준으로 배경영역이 제거된 경계박스를 분류하는 단계 및 병해충 진단부가 분류된 경계박스 별로 병해충을 검출하는 단계를 포함할 수 있다. claims: 작물 이미지의 병해충 검출 방법에 있어서,이미지 처리부가 작물 이미지를 수퍼픽셀(superpixel) 단위로 분할하는 단계;상기 이미지 처리부가 상기 수퍼픽셀의 윤곽(outline)에 외접하는 경계박스를 생성하는 단계;필터링부가 상기 경계박스에 포함된 수퍼픽셀 이외의 배경영역을 제거하는 단계;데이터 분석부가 합성곱신경망(Convolutional Neural Network, CNN)을 이용하여 특정 작물의 병해충 종류를 기준으로 상기 배경영역이 제거된 경계박스를 분류하는 단계; 및병해충 진단부가 상기 분류된 경계박스 별로 병해충을 검출하는 단계를 포함하는 것을 특징으로 하는 병해충 검출 방법.작물 이미지의 병해충 검출 장치에 있어서,작물 이미지를 수퍼픽셀(superpixel) 단위로 분할하고, 상기 수퍼픽셀의 윤곽(outline)에 외접하는 경계박스를 생성하는 이미지 처리부;상기 경계박스에 포함된 수퍼픽셀 이외의 배경영역을 제거하는 필터링부;합성곱신경망(Convolutional Neural Network, CNN)을 이용하여 특정 작물의 병해충 종류를 기준으로 상기 배경영역이 제거된 경계박스를 분류하는 데이터 분석부; 및상기 분류된 경계박스 별로 병해충을 검출하는 병해충 진단부를 포함하는 것을 특징으로 하는 병해충 검출 장치.제 1 항 내지 제 4 항 중 어느 한 항의 방법을 구현하기 위한 프로그램이 기록된 컴퓨터로 판독 가능한 기록 매체., Ltext: 임업, prediction: 농업
42/1059 Row 42: application_number: 1020190109783, combined_string: invention_title: 자가 충전식 모기 기피 장치 abstract: 본 발명은 자가 충전식 모기 기피 장치에 관한 것으로, 사용자가 장치를 흔들면 내부 충전부에 의해 베터리가 충전되어 외부 전력의 공급없이 모기 기피 장치의 사용이 가능하다. 또한, 모기와 같은 해충이 싫어하는 고주파를 발생하여, 인체에 무해하면서도 해충 퇴치 효과가 우수하다. claims: 본체;상기 본체부의 일면에 구성된 해충 퇴치를 위한 고주파 발생 스피커; 상기 본체부의 내부에 구성된 베터리; 및상기 본체 내부에 구성된 충전부를 포함하며, 상기 베터리는 본체 내부의 충전부와 전기적으로 연결되며,사용자가 본체를 흔들게 되면, 충전부에 의해 발생된 전압이 유도되어 베터리를 충전할 수 있는자가 충전식 모기 기피 장치.해충 퇴치를 위한 고주파 발생부; 베터리부; 및충전부를 포함하며, 상기 베터리부는 충전부와 전기적으로 연결되며,사용자가 본체부를 흔들게 되면, 충전부에 의해 발생된 전압이 유도되어 베터리부를 충전하여 외부 전력 공급 없이 사용이 가능하고,상기 고주파 발생부에서 발생된 15 내지 25kHz의 소음에 의해 암컷 모기의 접근을 방지할 수 있는자가 충전식 모기 기피 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

43/1059 Row 43: application_number: 1020190105359, combined_string: invention_title: 드론을 이용한 수목소독 시스템 abstract: 본 발명의 드론을 이용한 수목소독 시스템은 드론에 설치된 방제호스를 지면에 대하여 길이 및 각도를 병행 조절할 수 있어 다양한 지형의 수목지역에 대하여 근접 살포 및 광역 살포가 상황별로 적합하게 적용될 수 있도록 하는데 목적이 있다. 이에 따라, 본 발명의 실시예에 따른 드론을 이용한 수목소독 시스템은, 드론, 드론의 하부에 위치하며 약제통이 구비되고 선단에 노즐이 구비된 복수의 방제호스를 포함하는 방제부, 및 방제부의 하부에 위치하며 방제호스와 결합되어 방제호스의 분사각도를 조절하는 각도조절부를 포함하여 구성되며, 드론은 본체와 복수의 드론암과 복수의 프로펠러 및 드론레그;를 포함하여 구성되고, 방제부는, 본체의 하부에 위치하며 내부에 약제통을 수용하는 회전실린더; 및 상부로는 본체와 결합하고 하부로는 회전실린더와 결합하여 고정시키되 회전축을 포함하여 구성되는 프레임;을 더 포함하되, 방제호스는 약제통에 연결되고 회전실린더의 외측면에 권취된 후 복수의 드론암에 각각 분기되어 연결되어 노즐을 통해 소독약을 분사하는 것을 포함하여 구성되고, 각도조절부는, 프레임에 연결되어 방제부의 하부에 위치하는 것을 포함하고, 헬륨과 같은 공기보다 가벼운 가스를 보관하는 가스탱크; 가스탱크와 연결되어 가스를 압축하며 공급하고 흡입하는 압축기; 압축기와 임의의 방제호스를 연결하며 압축기에 의해 가스가 공급되고 흡입되는 통로를 형성하는 가스공급관; 측면에 인접한 방제호스 간을 연결하며 복수의 방제호스에 모두 연결되고 확장과 수축이 가능한 주름관; 및 방제호스를 압축기 및 주름관과 결합시키는 주름관고정유닛;을 포함하여 구성되는 것을 특징으로 한다. claims: 드론;드론의 하부에 위치하며, 약제통이 구비되고, 선단에 노즐이 구비된 복수의 방제호스를 포함하는 방제부; 및방제부의 하부에 위치하며, 방제호스와 결합되어 방제호스의 분사각도를 조절하는 각도조절부;를 포함하고,드론은, 중앙에 위치하며 회전모터와 분사모터와 제어유닛을 포함하여 구성되는 본체;본체를 중심으로 방사형으로 연결된 복수의 드론암;드론암의 선단에 각각 구비되는 복수의 프로펠러; 및본체의 하단에 지면 착지를 위해 구비되는 드론레그;를 포함하여 구성되고, 방제부는, 본체의 하부에 위치하며 내부에 약제통을 수용하는 회전실린더; 및상부로는 본체와 결합하고 하부로는 회전실린더와 결합하여 고정시키되 회전축을 포함하여 구성되는 프레임;을 더 포함하되, 방제호스는 약제통에 연결되고 회전실린더의 외측면에 권취된 후 복수의 드론암에 각각 분기되어 연결되어 노즐을 통해 소독약을 분사하는 것을 포함하여 구성되고,각도조절부는, 프레임에 연결되어 방제부의 하부에 위치하는 것을 포함하고, 헬륨과 같은 공기보다 가벼운 가스를 보관하는 가스탱크;가스탱크와 연결되어 가스를 압축하며 공급하고 흡입하는 압축기;압축기와 임의의 방제호스를 연결하며 압축기에 의해 가스가 공급되고 흡입되는 통로를 형성하는 가스공급관;측면에 인접한 방제호스 간을 연결하며 복수의 방제호스에 모두 연결되고 확장과 수축이 가능한 주름관; 및방제호스를 압축기 및 주름관과 결합시키는 주름관고정유닛;을 포함하여 구성되되,드론의 본체는, 제어유닛과 분사모터와 회전모터를 포함하며, 제어유닛은 회전모터 및 분사모터의 구동과 프로펠러를 회전시키며 비행 조종을 하는 제어모듈, 통신기능을 구비하며 조종명령을 수신하여 제어부에 연계하는 통신모듈, 동력원을 제공하고 동력 정보를 표시하는 동력모듈,을 포함하여 구성되고, 분사모터는 약제통의 소독약을 방제호스와 노즐을 통해 분사시키며, 회전모터는 회전실린더를 회전시키는 것을 더 포함하며, 방제부는, 노즐이 소정의 무게를 갖도록 구비되어 드론암의 선단으로부터 하부 수직방향으로 향하도록 구성되며, 회전실린더가 프레임에 연결된 채 회전함에 따라 방제호스의 감김과 풀림이 이루어져, 회전실린더를 일방향으로 회전시키면 방제호스가 풀어지면 노즐의 무게로 인해 하부로 길게 늘어뜨려지고, 회전실린더를 타방향으로 회전시키면 방제호스가 감겨지면서 상부로 상승하게 되어 드론암의 외측으로 이격되는 방제호스의 길이를 조절할 수 있는 것을 더 포함하는 것을 특징으로 하는 드론을 이용한 수목소독 시스템., Ltext: 임업, prediction: 임업
44/1059 Row 44: application_number: 1020190100760, combined_string: invention_title: 해충 포획용 유아등 abstract: 본 발명은 본체(100), 램프부(200), 포집부(300) 및 전원부(400)를 포함하여 이루어지되, 상기 본체(100)는 전원부(400)가 설치된 상부체(120)와 포집부(300)가 설치된 하부체(130)로 구성되고, 상기 상,하부체(120,130) 사이에는 320~430nm 파장의 자외선을 방출하는 자외선 램프(210)로 구성된 램프부(200)가 설치되되 초기 점등시 등대효과를 갖도록 깜빡이면서 점차 밝아져 점등되도록 하고, 상기 본체(100)의 외측에는 자외선 램프(210)의 빛이 어느 방향으로도 가려지지 않도록 투명 커버(140)가 씌워지고, 상기 투명 커버(140)의 내측에는 본체(100)의 상,하부체(120,130)를 연결하는 지지기둥(150)이 연결되며, 상기 투명 커버(140)의 사방으로는 자외선 램프(210)로 유인된 해충이 본체(100) 내측으로 진입하도록 개구(142)가 형성되어 사각지대 없이 해충의 유인이 가능하고, 포집부(300)의 흡입팬(340)은 난기류가 발생하지 않도록 수직통로(320)내에 설치되어 해충이 포집망으로 딸려들러가도록 되어 있다. claims: 복수의 지지다리(110)를 갖는 본체(100)와, 상기 본체(100)에 구비되어 해충을 유인하도록 자외선을 방출하는 램프부(200)와, 상기 본체(10)의 하부측에 구비되고 상기 램프부(200)에 의해 유인된 해충을 포집하는 포집부(300)와, 상기 램프부(200)와 포집부(300)에 전원을 공급하는 전원부(400)를 포함하여 이루어지는 해충 포획용 유아등으로; 상기 본체(100)는 전원부(400)가 설치된 상부체(120)와 포집부(300)가 설치된 하부체(130)로 이루어지고, 상기 상,하부체(120,130) 사이에는 램프부(200)가 설치되되 상기 램프부(200)는 320~430nm 파장의 자외선을 방출하는 자외선 램프(210)를 사용하고, 상기 자외선 램프(210)가 설치된 본체(100)의 외측에는 자외선 램프(210)의 빛이 어느 방향으로도 가려지지 않도록 투명 커버(140)가 씌워지고, 상기 투명 커버(140)의 내측에는 본체(100)의 상,하부체(120,130)를 연결하는 지지기둥(150)이 연결되며, 상기 투명 커버(140)의 사방으로는 자외선 램프(210)로 유인된 해충이 본체(100) 내측으로 진입하도록 개구(142)가 형성된 것을 특징으로 하는 해충 포획용 유아등., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

45/1059 Row 45: application_number: 1020190088935, combined_string: invention_title: 공간빅데이터를 활용한 LULUCF 분야 토지이용변화 매트릭스 처리 장치 및 방법 abstract: 공간빅데이터를 활용한 LULUCF 분야 토지이용변화 매트릭스 처리 장치 및 방법이 제공된다. DB는 지표면 상태를 자연생태적 기준으로 분류한 토지피복지도, 산림 여부를 보여주는 임상도 및 농경지 정보를 보여주는 농경지 전자지도를 저장하고, 메모리는 토지피복지도, 임상도 및 농경지 전자지도를 분석하여 LULUCF 분야에 대한 토지 매트릭스를 구축하는 토지 매트릭스 구축 프로그램을 저장하고, 프로세서는 메모리에 저장된 토지 매트릭스 구축 프로그램을 실행하여 DB에 저장된 토지피복지도, 임상도 및 농경지 전자지도를 중첩하여 GIS 레이어를 생성하고, GIS 레이어를 6개의 토지이용범주 별로 분류한 후, 분류된 6개의 토지이용범주와 사전에 분류된 6개의 토지이용범주를 비교하여 유지된 토지 및 전용된 토지를 추출하고, 추출된 유지된 토지 및 전용된 토지의 면적을 이용하여 토지 매트릭스를 구축할 수 있다. claims: 지표면 상태를 자연생태적 기준으로 분류한 토지피복지도, 산림 여부를 보여주는 임상도 및 농경지 정보를 보여주는 농경지 전자지도를 저장하는 DB;상기 토지피복지도, 임상도 및 농경지 전자지도를 분석하여 토지 이용, 토지이용변화 및 임업(LULUCF: LAND USE, LAND USE CHANGE AND FOREST) 분야에 대한 토지 매트릭스를 구축하는 토지 매트릭스 구축 프로그램을 저장하는 메모리; 및상기 메모리에 저장된 토지 매트릭스 구축 프로그램을 실행하여 상기 DB에 저장된 토지피복지도, 임상도 및 농경지 전자지도를 중첩하여 GIS 레이어를 생성하고, GIS 레이어를 6개의 토지이용범주 별로 분류한 후, 분류된 6개의 토지이용범주와 사전에 분류된 6개의 토지이용범주를 비교하여 유지된 토지 및 전용된 토지를 추출하고, 상기 추출된 유지된 토지 및 전용된 토지의 면적을 이용하여 토지 매트릭스를 구축하는 프로세서;를 포함하고,상기 프로세서는,상기 토지피복지도, 임상도 및 농경지 전자지도를 중첩하여 임시 GIS 레이어를 생성하고, 상기 임시 GIS 레이어에서 토지피복지도, 임상도 및 농경지 전자지도 간의 이격이 발생하는 경우, 경계 조정 작업을 수행하여 이격을 보정하여 상기 GIS 레이어를 생성하는 레이어 생성부;를 포함하며,상기 레이어 생성부는 상기 생성된 임시 GIS 레이어에서 이격이 발생한 지역을 판단하고, 상기 이격이 발생한 지역에 해당하는 지역의 속성을 상기 토지피복지도로부터 추출하여 상기 이격이 발생한 지역의 속성으로 설정하는 경계 조정 작업을 수행하여 이격을 보정하며,상기 6개의 토지이용범주는 산림지, 농경지, 초지, 습지, 정주지 및 기타토지를 포함하는 것을 특징으로 하는 공간빅데이터를 활용한 LULUCF 분야 토지이용변화 매트릭스 처리 장치.(A) 전자장치가, 지표면 상태를 자연생태적 기준으로 분류한 토지피복지도, 산림 여부를 보여주는 임상도 및 농경지 정보를 보여주는 농경지 전자지도를 중첩하여 GIS 레이어를 생성하는 단계;(B) 상기 전자장치가, 상기 GIS 레이어를 6개의 토지이용범주 별로 분류하는 단계;(C) 상기 전자장치가, 상기 (B) 단계에서 분류된 6개의 토지이용범주와 사전에 분류된 6개의 토지이용범주를 비교하여 유지된 토지 및 전용된 토지를 추출하는 단계; 및(D) 상기 (C) 단계에서 추출된 유지된 토지 및 전용된 토지의 면적을 이용하여 토지 매트릭스를 구축하는 단계;를 포함하고,상기 (A) 단계는,(A1) 상기 전자장치가, 토지피복지도, 임상도 및 농경지 전자지도를 중첩하여 임시 GIS 레이어를 생성하는 단계; 및(A2) 상기 전자장치가, 상기 임시 GIS 레이어에서 토지피복지도, 임상도 및 농경지 전자지도 간의 이격이 발생하는 경우, 경계 조정 작업을 수행하여 이격을 보정하여 상기 GIS 레이어를 생성하는 단계;를 포함하고,상기 (A2) 단계는,상기 생성된 임시 GIS 레이어에서 이격이 발생한 지역을 판단하고, 상기 이격이 발생한 지역에 해당하는 지역의 속성을 상기 토지피복지도로부터 추출하여 상기 이격이 발생한 지역의 속성으로 설정하는 경계 조정 작업을 수행하여 이격을 보정하며,상기 6개의 토지이용범주는 산림지, 농경지, 초지, 습지, 정주지 및 기타토지를 포함하는 것을 특징으로 하는 공간빅데이터를 활용한 LULUCF 분야 토지이용변화 매트릭스 처리 방법., Ltext: 임업, prediction: 임업
46/1059 Row 46: application_number: 1020190083977, combined_string: invention_title: 수목장용 식별장치와 이를 이용한 수목장 관리 시스템 abstract: 본 발명은 수목장의 특정 지면 하부로 삽입되어 영역을 인식시키는 식별장치로서, 상기 특정 지면의 식별정보를 저장하고 있는 식별 칩과, 내부에 상기 식별 칩을 수용할 수 있는 공간이 형성된 식별 칩 수용부와, 상기 식별 칩 수용부의 하부에 연결되고, 소정의 길이를 가지고 지면에 삽입될 수 있는 지면 삽입부를 포함한다. claims: 수목장의 특정 지면 하부로 삽입되어 영역을 인식시키는 식별장치에 있어서,상기 특정 지면의 식별정보를 저장하고 있는 식별 칩;내부에 상기 식별 칩을 수용할 수 있는 공간이 형성된 식별 칩 수용부; 및상기 식별 칩 수용부의 하부에 연결되고, 소정의 길이를 가지고 지면에 삽입될 수 있는 지면 삽입부;를 포함하며,상기 식별 칩 수용부에는 흡수성 고분자가 물을 흡수한 상태로 충진되어 열기로부터 식별칩을 보호하는 수목장용 식별장치.수목장에 매장된 고인들을 구분할 수 있도록 분획된 수목장의 특정 지점에 매립되고, 상기 특정 지점에 매장된 고인을 식별할 수 있는 정보가 저장되며, 근거리 무선통신 수단이 구비되어 상기 매장된 고인을 식별할 수 있는 정보를 전송할 수 있는 식별 칩;상기 식별 칩에서 전송된 고인의 식별 정보를 수신하기 위한 근거리 무선통신 수단을 구비하고, 수목장 관리 서버 및 이벤트 컨텐츠 서버와 통신이 가능하며, 상기 수목장 관리 서버 및 이벤트 컨텐츠 서버에서 전송받은 정보를 표시하는 어플리케이션이 설치된 모바일 단말기;수목장 내 추모목의 위치, 상기 추모목에 매칭된 고인의 성명, 가족관계, 매장일시 또는 유족의 방문기록이 저장되고, 상기 모바일 단말기의 요청에 의하여 상기 추모목에 매칭된 고인의 성명, 가족관계, 매장일시 또는 유족의 방문기록에 관한 정보를 모바일 단말기로 전송하는 수목장 관리서버; 및고인의 생전 모습 사진 또는 동영상이 저장되고, 모바일 단말기의 요청에 의하여 상기 고인의 생전 모습 사진 또는 동영상에 관한 정보를 모바일 단말기로 제공하는 이벤트 컨텐츠 서버;를 포함하고,특정 고인의 식별 칩에 매칭되어 할당된 로그인 정보로 상기 모바일 단말기의 어플리케이션에 로그인하고, 근거리 무선통신에 의하여 감지된 상기 특정 고인의 식별 칩과 로그인 정보가 매칭되는 것으로 판단되면, 상기 어플리케이션이 수목장 관리 서버에 저장된 특정 고인의 성명, 가족관계, 매장일시 또는 유족의 방문기록에 관한 정보를 모바일 단말기에 전송할 것을 요청하고, 수목장 관리 서버는 모바일 단말기로 수목장 관리 서버에 저장된 특정 고인의 성명, 가족관계, 매장일시 또는 유족의 방문기록에 관한 정보를 전송하고, 근거리 무선통신에 의하여 감지된 상기 특정 고인의 식별 칩과 로그인 정보가 매칭되는 것으로 판단되면, 상기 어플리케이션에 이벤트 컨텐츠 서버에 저장된 고인의 생전 모습 사진 또는 동영상에 관한 정보를 모바일 단말기에 전송할 것을 요청할 수 있는 요청 버튼이 활성화되고, 상기 활성화된 요청 버튼이 실행되면 이벤트 컨텐츠 서버에 저장된 고인의 생전 모습 사진이 모바일 단말기에 표시되거나 동영상이 재생되며, 상기 수목장 관리 서버 및 이벤트 컨텐츠 서버는 모바일 단말기로 정보를 전송한 기록을 저장하며, 상기 식별 칩의 수용부에는 흡수성 고분자가 물을 흡수한 상태로 충진되어 열기로부터 식별칩을 보호하는 것을 특징으로 하는 수목장 관리 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

47/1059 Row 47: application_number: 1020210077868, combined_string: invention_title: 천연물 복합 추출물을 함유하는 모발 건강 개선용 식품 또는 화장료 조성물 abstract: 본 발명은 건조 조성물 중량 기준으로 구절초 추출물 5~25%, 페퍼민트 추출물 65~85% 및 감초 추출물 5~15%를 포함하는 복합 생약 추출물을 유효성분으로 함유하는 모발 건강 개선용 조성물에 관한 것이다. claims: 구절초 추출물 5~25 중량%, 페퍼민트 추출물 65~85 중량% 및 감초 추출물 5~15 중량%를 포함하는 복합 생약 추출물을 유효성분으로 함유하고,여기서, 상기 생약 추출물은 물, C1~C4의 저급알코올 또는 이들의 혼합물로 40 내지 100℃의 온도에서 1시간 이상 추출되고,당귀 추출물, 은행잎 추출물 및 병풀잎 추출물 중 하나 이상을 함유하지 않는 것인, 탈모 방지 또는 발모 개선용 조성물., Ltext: 임업, prediction: 농업
48/1059 Row 48: application_number: 1020210059871, combined_string: invention_title: 천연물질의 선택적 추출 방법 abstract: 비극성 천연물질의 추출 방법이 개시된다. 본 발명의 일 실시예에 따른 비극성 천연물질의 추출 방법은, 중대가리풀(Centipeda minima), 삼푸트리(Litsea glutinous), Arnica 속 식물 및 Helenium 속 식물로 이루어진 그룹에서 선택된 어느 하나 이상을 포함하는 천연물 원료를 추출하여 1차 추출액을 제조하는 단계, 1차 추출액에 친유성 가용화제를 포함하는 상분리 조성물을 혼합하여 상기 1차 추출액 내 Brevilin A 또는 이의 유도체들을 용해 및 가용화시켜 고농축된 상분리 2차 추출액을 제조하는 단계 및 상분리된 용액의 상층을 분리하여 Brevilin A 또는 이의 유도체들을 수득하는 단계를 포함한다. 따라서, 비극성 천연물질을 용해-유화 추출법(Dissolution-Emulsion Extract, DEE)을 이용하여 고효율로 비교적 용이하게 추출할 수 있다. claims: 중대가리풀(Centipeda minima), 삼푸트리(Litsea glutinous), Arnica 속 식물 및 Helenium 속 식물로 이루어진 그룹에서 선택된 어느 하나 이상을 포함하는 천연물 원료를 추출하여 1차 추출액을 제조하는 단계; 1차 추출액에 친유성 가용화제를 포함하는 상분리 조성물을 혼합하여 상기 1차 추출액 내 Brevilin A 또는 이의 유도체들을 용해 및 가용화시켜 고농축된 상분리 2차 추출액을 제조하는 단계; 및 상분리된 용액의 상층을 분리하여 Brevilin A 또는 이의 유도체들을 수득하는 단계를 포함하는 비극성 천연물질의 추출 방법.친유성 가용화제를 포함하는 상분리 조성물을 이용하여 중대가리풀(Centipeda minima), 삼푸트리(Litsea glutinous), Arnica 속 식물 및 Helenium 속 식물로 이루어진 그룹에서 선택된 어느 하나 이상을 포함하는 천연물 원료로부터 Brevilin A 또는 이의 유도체들을 용해 및 가용화시켜 고농축된 상분리된 추출액을 제조하는 단계; 및 상분리된 용액의 상층을 분리하여 Brevilin A 또는 이의 유도체들을 수득하는 단계를 포함하는 비극성 천연물질의 추출 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

49/1059 Row 49: application_number: 1020210054372, combined_string: invention_title: 천연 추출물을 포함하는 패드용 화장료 조성물 abstract: 본 발명은 어성초 잎 추출물, 실크 피브로인, 상백피 추출물, 및 당근 추출물을 유효성분으로 포함하는 패드용 화장료 조성물 및 상기 화장료 조성물이 함침된 화장용 패드에 관한 것이다.본 발명의 어성초 잎 추출물, 실크 피브로인, 상백피 추출물, 및 당근 추출물을 포함하는 조성물은 여드름균에 대한 항균 활성 및 피부 미백 활성이 우수할 뿐만 아니라, 이를 화장 패드에 적용함으로써 사용 편의성을 높이고, 각질 제거 등의 피부 개선 효과를 가짐을 확인하였다. claims: 어성초 잎 추출물 4 내지 7 중량부, 실크 피브로인 10 중량부, 상백피 추출물 0.1 내지 3 중량부, 당근 추출물 0.1 내지 3 중량부, 익모초 추출물 1 중량부, 및 창이자 추출물 1 중량부를 포함하는 패드용 화장료 조성물로서,상기 패드용 화장료 조성물은 화장용 패드에 함침시켜 사용되는 것이며,상기 조성물은 프로피오니박테리움 아크네스(Propionibacterium acnes) 균주 및 스태필로코커스 에피더미스(Staphylococcus epidermidis) 균주에 대한 항균 활성, 미백 활성 및 각질 제거 효과를 나타내는 것을 특징으로 하는, 패드용 화장료 조성물.제1항의 화장료 조성물이 함침된 화장용 패드., Ltext: 임업, prediction: 어업
50/1059 Row 50: application_number: 1020210048957, combined_string: invention_title: 복합 세라마이드 및 천연 추출물을 포함하는 피부개선용 화장료 조성물 abstract: 본 발명은 5종의 복합 세라마이드 및 천연 추출물을 포함하는 피부 개선용 화장료 조성물에 관한 것으로, 구체적으로 5종의 복합 세라마이드 및 서양민들레잎 추출물이 피부 내 마이크로바이옴 균형 유지 및 피부장벽강화 효능을 가지는 피부 개선용 화장료 조성물 및 이의 제조방법에 관한 것이다. claims: 세라마이드이오피(EOP), 세라마이드엔에스(NS), 세라마이드엔피(NP), 세라마이드에이에스(AS) 및 세라마이드에이피(AP)가 1~1.5 : 1~1.5 : 1~3 : 1~1.5 : 1~1.5의 비율로 이루어진 세라마이드; 서양민들레잎 추출물; 및락토바실러스 발효용해물;을 포함하는 피부 내 마이크로바이옴 균형 유지용 화장료 조성물., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

51/1059 Row 51: application_number: 1020210046402, combined_string: invention_title: 천연 공융용매로 추출한 쓴풀, 서양고추나물 및 하늘타리 혼합추출물을 함유하는 피부 미백용 화장료 조성물 abstract: 본 발명은 천연 공융용매로 추출한 쓴풀, 서양고추나물 및 하늘타리 혼합추출물을 함유하는 피부 미백용 화장료 조성물에 관한 것으로, 구체적으로는 쓴풀, 서양고추나물 및 하늘타리를 천연 공융용매를 이용하여 추출하고, 이를 다시 아임계 추출하여 제조되는 쓴풀, 서양고추나물 및 하늘타리 혼합추출물을 함유하여 우수한 피부 미백 효능을 나타내는 화장료 조성물에 관한 것이다. claims: 쓴풀, 서양고추나물 및 하늘타리가 각각 1 : 3 : 2의 중량비로 혼합되어 이루어지는 쓴풀, 서양고추나물 및 하늘타리 혼합물을 비테인(Betaine)과 사카로즈(Saccharose)로 이루어지는 천연 공융용매와 물을 용매로 하여 추출하고, 다시 추출용매를 가하여 아임계 조건인 120~200℃, 압력 0.1~15MPa에서 10~30분간 아임계 추출하여 제조되는 쓴풀, 서양고추나물 및 하늘타리 혼합추출물을 유효성분으로서 조성물 전체 중량에 대하여 0.1~10 중량% 함유하는 피부 미백용 화장료 조성물., Ltext: 임업, prediction: 농업
52/1059 Row 52: application_number: 1020210043862, combined_string: invention_title: 천연 오일 및 천연 추출물을 포함하는 화장료 조성물 abstract: 본 발명은 식물 오일 및 천연 추출물을 함유하는 피부 외용제에 관한 것으로, 구체적으로 파인 오일을 아미노 알코올과 효소 반응을 통해 세라마이드와 유사한 피부 보습 및 피부장벽 강화 효과를 가지면서 유화 안정제로 작용할 수 있는 피부 외용제에 관한 것이다. 나아가, 할미꽃 식물세포 또는 부정근 배양 추출물 및 후박나무껍질 추출물과 혼합하여 항균 및 항염 용도로 활용할 수 있다. 나아가, 본 발명의 피부 외용제는 복수의 유효성분을 포함함으로써, 피부 열감 개선 및 쿨링 효과를 나타냄과 동시에 체내 독소 배출 효과를 기대할 수 있다. claims: a) 파인(Pinus sylvestris) 잎 및 가지에서 각각 추출한 오일을 1 : 1의 중량비로 혼합한 오일 및 3-아미노부탄-1,2-디올(3-aminobutane-1,2-diol)을 혼합하고 리파아제인 리포자임 TL IM(Lipozyme TL IM)를 반응시켜 파인발효 오일을 제조하는 단계; b) 할미꽃 식물세포 또는 부정근 배양 추출물 및 후박나무껍질 추출물을 포함하는 식물 복합 추출물을 제조하는 단계; 및c) 상기 a) 단계의 파인발효 오일 및 b) 단계의 식물 복합 추출물을 혼합하는 단계;를 포함하는, 항균 및 항염용 피부 외용제 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

53/1059 Row 53: application_number: 1020210042561, combined_string: invention_title: 매스틱 및 천연물 유래 추출물을 포함하는 헬리코박터균 억제용 제품 abstract: 본 발명은 매스틱 및 천연물 유래의 추출물을 포함하여 제조된 식품 및 구강 케어 제품에 관한 것으로서, 헬리코박터 파일로리(Helicobacter pylori)균의 억제 효과를 갖는 것을 특징으로 한다. claims: 매스틱(Mastic, Pistacia lentiscus LINNE) 에센셜 오일 1 내지 10 중량부;금은화(Lonicera japonica) 10 내지 15 중량부, 감초(Glycyrrhiza uralensis) 10 내지 15 중량부, 인삼(Panax ginseng) 3 내지 9 중량부, 계피(Cinnamomum japonicum SIEB.) 3 내지 7 중량부, 차조기(Perilla frutescens) 2 내지 5 중량부 및 유카(Yucca gloriosa) 1 내지 5 중량부로 이루어진 군에서 하나 이상 선택된 천연물의 혼합 추출물을 포함하는 수상;을 혼합 후 고압 유화장치(microfluidizer)로 분산시켜 고압 분산 에멀젼화 하여 제조한 중심물질; 및상기 중심물질을, 오일상으로서 MCT:매스틱 오일:올리브 오일: 솔잣나무 잎 오일을 47:22:4:8의 중량비로 혼합한 피복물질;로 피복하여 제조한 미세캡슐을 포함하고,소세지, 육류, 빵, 초콜릿류, 스넥류, 캔디류, 과자류, 라면, 피자, 면류, 껌류, 아이스크림류를 포함한 낙농제품, 스프, 음료수, 차, 드링크제, 알코올 음료 및 비타민 복합제로 구성된 군에서 하나 이상 선택된 제형을 가진, 헬리코박터 파일로리균(Helicobacter pyroli) 억제용 식품 조성물.매스틱(Mastic, Pistacia lentiscus LINNE) 에센셜 오일 1 내지 10 중량부;금은화(Lonicera japonica) 10 내지 15 중량부, 감초(Glycyrrhiza uralensis) 10 내지 15 중량부, 인삼(Panax ginseng) 3 내지 9 중량부, 계피(Cinnamomum japonicum SIEB.) 3 내지 7 중량부, 차조기(Perilla frutescens) 2 내지 5 중량부 및 유카(Yucca gloriosa) 1 내지 5 중량부로 이루어진 군에서 하나 이상 선택된 천연물의 혼합 추출물을 포함하는 수상;을 혼합 후 고압 유화장치(microfluidizer)로 분산시켜 고압 분산 에멀젼화 하여 제조한 중심물질; 및상기 중심물질을, 오일상으로서 MCT:매스틱 오일:올리브 오일: 솔잣나무 잎 오일을 47:22:4:8의 중량비로 혼합한 피복물질;로 피복하여 제조한 미세캡슐을 포함하고,구강 세척제 및 치과용 세척제, 치약, 가글 용액, 패취 및 스프레이로 구성된 군으로부터 하나 이상 선택된 제형을 가진, 헬리코박터 파일로리균(Helicobacter pyroli) 억제용 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

54/1059 Row 54: application_number: 1020210040231, combined_string: invention_title: 천연물 추출장치 abstract: 본 발명은 천연물 추출장치에 관한 것으로, 본 발명의 실시예에 의하면, 추출부를 진동 및 타격하고 추출액을 적하시키며 반복 추출하여 천연물의 유효성분 추출 효율을 향상시키는 효과가 있다. claims: 내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및상기 추출부의 상측에 연결되고, 상기 용매가 투입되며, 상기 원물에 상기 용매를 분사하는 용매분사부;를 포함하고,상기 용매분사부의 하측에 연결되고, 상기 용매분사부에 의해 분사된 상기 용매를 더 확산시키기 위한 회전판; 및상기 회전판을 회전시키는 회전모듈;을 더 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및상기 추출부에 연결되고, 상기 용매와 상기 원물이 잘 섞이도록 상기 추출부에 진동을 가함으로써 추출 효율을 향상시키는 진동부;를 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및일측이 상기 저장부에 연결되고, 타측이 상기 추출부에 연결되며, 상기 유효성분의 추출 효율을 높이도록 상기 추출액을 상기 추출부로 재공급하는 순환부;를 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부; 및상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부;를 포함하고,상기 추출부는,상부가 개구되고, 하부가 메쉬로 형성되며, 내측에 상기 원물을 수용하는 원물트레이; 및상부가 개구되어 상기 용매가 투입되고, 내측에 상기 원물트레이를 수용할 수 있는 공간이 형성되며, 상기 원물로부터 상기 유효성분을 추출하여 상기 추출액을 생성하고, 상기 추출액이 통과할 수 있도록 하부에 홀이 형성된 추출하우징;을 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부; 및상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부;를 포함하고,상기 저장부는,상기 추출부의 하측에 연결되고, 상기 추출부에서 추출된 상기 추출액을 저장하는 저장탱크;상기 저장탱크에 연결되어 저장된 상기 추출액을 배출하는 배출파이프; 및상기 배출파이프에 구비되어 상기 배출파이프를 선택적으로 개방 또는 폐쇄하는 배출밸브;를 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및상기 추출부의 상측에 연결되고, 상기 용매가 투입되며, 상기 원물에 상기 용매를 분사하는 용매분사부;를 포함하고,상기 용매분사부는,상기 추출부의 상측에 연결되고, 용매투입구가 형성되어 용매가 투입되는 용매탱크; 및상기 용매탱크 하부에 구비되어 상기 원물에 상기 용매를 분사하는 용매분사체;를 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및상기 추출부와 상기 저장부 사이에 구비되고, 상기 추출부에서 추출된 상기 추출액을 저장하며, 상기 저장부로 낙하하는 상기 추출액의 유량을 제어하는 적하부;를 포함하고상기 적하부는,상측이 상기 추출부의 하측에 연결되고, 하측이 상기 저장부와 적하파이프로 연결되며, 상기 추출부에서 추출된 상기 추출액을 저장하는 이너탱크;상기 이너탱크 내부에 구비되고, 상기 이너탱크 내부에 저장되는 상기 추출액의 수위를 측정하는 수위센서;상기 적하파이프에 구비되고, 상기 저장부로 낙하하는 상기 추출액의 유량을 조절하는 유량조절밸브; 및상기 수위센서로부터 수위값을 전송받아 상기 추출액이 기설정된 수위에 도달하면 상기 유량조절밸브를 개방하도록 제어하는 수위제어부;를 포함하는 것을 특징으로 하는 천연물 추출장치., Ltext: 임업, prediction: 임업
55/1059 Row 55: application_number: 1020210010474, combined_string: invention_title: 천연소재 추출물 함유 약학적 조성물 및 그의 제조 방법 abstract: 본 발명은 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물을 포함하는 약학적 조성물 및 그의 제조 방법에 관한 것이다. claims: 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물로 이루어진 군에서 선택되는 적어도 하나의 추출물을 포함하는 피부 관련 질환의 예방 또는 치료용 약학적 조성물.청구항 1의 약학적 조성물을 이를 필요로 하는 개체에 투여하는 단계를 포함하는 피부 관련 질환의 예방 또는 치료 방법.황금, 맥문동, 고삼, 백선피 및 황백으로 이루어진 군에서 선택되는 적어도 하나의 천연소재를 추출하는 단계를 포함하는 피부 관련 질환의 예방 또는 치료용 약학적 조성물의 제조 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

56/1059 Row 56: application_number: 1020210010482, combined_string: invention_title: 천연소재 추출물 함유 식품 조성물 및 그의 제조 방법 abstract: 본 발명은 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물을 포함하는 식품 조성물 및 그의 제조 방법에 관한 것이다. claims: 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물로 이루어진 군에서 선택되는 적어도 하나의 추출물을 포함하는 피부 관련 질환의 예방 또는 개선용 식품 조성물.청구항 1의 식품 조성물을 이를 필요로 하는 개체에게 섭취시키는 단계를 포함하는 피부 관련 질환의 예방 또는 개선 방법.황금, 맥문동, 고삼, 백선피 및 황백으로 이루어진 군에서 선택되는 적어도 하나의 천연소재를 추출하는 단계를 포함하는 피부 관련 질환의 예방 또는 개선용 식품 조성물의 제조 방법., Ltext: 임업, prediction: 임업
57/1059 Row 57: application_number: 1020210007584, combined_string: invention_title: 천연물 유래 추출물을 포함하는 피부 개선용 화장료 조성물 및 이의 제조방법 abstract: 본 발명은 천연물 유래 추출물 및 허브 파우더를 함유하는 화장료 조성물에 관한 것으로서, 구체적으로는 로즈마리, 라벤더, 페퍼민트 추출물 및 이들의 허브 파우더를 함유함으로써 피부 노폐물 제거, 피부장벽 개선, 피부 탄력 부여, 피부 보습, 각질제거 및 영양공급 효과를 갖는 것을 특징으로 한다. claims: 페퍼민트(Mentha piperita) 잎 추출물 100 중량부 대비, 로즈마리(Salvia rosmarinus) 잎 추출물 100 중량부, 라벤더(Lavandula) 꽃 추출물 100 중량부, 마조람(Origanum majorana) 잎 추출물 40 중량부, 모란(Paeonia suffruticosa) 뿌리 추출물 35 중량부, 들깨(Perilla frutescens) 잎 추출물 27 중량부, 연꽃(Nelumbo nucifera) 추출물 22 중량부, 목련나무(Magnolia) 껍질 추출물 15 중량부 및 목화(Gossypium indicum) 씨 추출물 8 중량부; 및 페퍼민트 파우더 30 중량부, 로즈마리 파우더 25 중량부, 라벤더 파우더 25 중량부 및 살구씨 파우더 35 중량부를 포함하여 제조된 화장료 조성물로서,상기 추출물은 페퍼민트 잎, 로즈마리 잎, 라벤더 꽃, 마조람, 모란 뿌리, 들깨 잎, 연꽃, 목련나무 껍질 및 목화 씨를 -60℃ 내지 -80℃ 조건에서 동결 건조하고, 각 재료의 2배 중량의 정제수를 혼합하여 수분을 흡수시키고, 70%(v/v) 에탄올을 용매로 하여 2시간 동안 환류 추출한 후, 250 메쉬 및 0.5μm 필터로 여과하고 40℃에서 감압 농축하여 수득한 것이며,상기 화장료 조성물은 피부 노폐물 제거, 피부장벽 개선, 피부 탄력 부여, 피부 보습, 각질제거 및 영양공급 효과를 갖는 것인, 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

58/1059 Row 58: application_number: 1020210005266, combined_string: invention_title: 천연 쌀눈 추출물을 포함하는 칠곡 삼계죽의 제조방법 abstract: 본 발명은 천연 쌀눈 추출물을 포함하는 칠곡 삼계죽의 제조방법에 관한 것으로, 본 발명에 따른 천연 쌀눈 추출물을 포함하는 칠곡 삼계죽의 경우, 쌀눈을 원물 그대로 첨가한 것이 아닌 증류수만을 이용한 천연 추출방법으로 추출하여 쌀눈에 첨가된 GABA 함량과 쌀눈의 향을 증가시킬 수 있으며, 삼계죽에 멥쌀, 찹쌀, 현미, 귀리, 기장 및 보리를 포함하는 곡물과 채소를 첨가하여 영양적 가치가 높은 삼계죽을 제조할 수 있는 장점이 있다. claims: 쌀눈 추출물, 기장, 멥쌀, 찹쌀, 귀리, 녹두, 현미, 닭가슴살, 양파, 당근, 마늘, 인삼, 천일염, 대파, 치킨스톡, 찹쌀가루 및 감자전분을 포함하는 칠곡 삼계죽 재료를 준비하는 단계;정제수에 쌀눈추출물, 기장, 멥쌀, 찹쌀, 귀리, 녹두, 현미, 닭가슴살, 양파, 당근, 마늘, 인삼 및 천일염을 첨가하여 5 내지 15분간 가열하여 1차 육수를 제조하는 단계;상기 1차 육수에 대파 및 치킨스톡을 넣고 3 내지 7분간 가열하여 2차 육수를 제조하는 단계; 및상기 2차 육수에 상기 찹쌀가루 및 감자전분을 넣고 1 내지 3분간 가열하여 칠곡 삼계죽을 제조하는 단계;를 포함하는 칠곡 삼계죽 제조 방법.제1항 내지 제6항의 방법으로 제조된 칠곡 삼계죽., Ltext: 임업, prediction: 농업
59/1059 Row 59: application_number: 1020210004132, combined_string: invention_title: 천연 식물 추출물을 포함하는 화장품용 PLGA 나노입자 및 이의 제조방법 abstract: 본 발명은 PLGA 입자 내에 마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 유효 성분을 포함하는 화장품용 PLGA 나노입자 및 이의 제조방법에 관한 것으로, 유효 성분을 단계적이고 집약적으로 피부로 흡수시켜 흡수율과 지속력을 높일 수 있는 효과를 제공한다. claims: PLGA(poly(lactic-co-glycolic acid)) 고분자가 유기 용매에 용해된 유기용액과 포스파티딜콜린(phosphatidyl choline)을 혼합한 용액을 클로로포름(chloroform)으로 용해시키고, 여기에 안정화제를 혼합하여 1차 혼합물을 제조하는 제1 단계;상기 1차 혼합물에 마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 천연 식물 추출물을 포함하는 수용액을 첨가한 후 1℃ 내지 5℃에서 초음파 처리 및 교반하여 2차 혼합물을 제조하는 제2 단계;상기 2차 혼합물에 키토산(chitosan)을 혼합 및 교반하여 키토산 코팅된 1차 입자를 제조하는 제3 단계;마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 천연 식물 추출물과 상기 1차 입자를 포함하는 수용액에 PLGA(poly(lactic-co-glycolic acid)) 고분자가 유기 용매에 용해된 유기용액을 혼합하여 3차 혼합물을 제조하는 제4 단계;상기 3차 혼합물에 계면활성제를 첨가한 후 10℃ 이하에서 초음파 처리 및 교반하여 4차 혼합물을 제조하는 제5 단계; 및상기 4차 혼합물에 알긴산 나트륨(sodium alginate)을 혼합 및 교반하여 알긴산 코팅된 2차 입자를 제조하는 제6 단계;를 포함하고,상기 1차 혼합물에 포함되는 PLGA(poly(lactic-co-glycolic acid)) 고분자는 PLA(poly(lactic acid)):PGA(poly(glycolic acid)) 의 몰비가 3:2 내지 4:1 이고,상기 3차 혼합물에 포함되는 PLGA(poly(lactic-co-glycolic acid)) 고분자는 PLA(poly(lactic acid)):PGA(poly(glycolic acid)) 의 몰비가 1:4 내지 2:3 인 것을 특징으로 하는 화장품용 PLGA 나노입자 제조방법. 마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 유효 성분을 포함하고, PLA(poly(lactic acid)):PGA(poly(glycolic acid)) 의 몰비가 3:2 내지 4:1인 PLGA(poly(lactic-co-glycolic acid)) 고분자로 형성되는 PLGA 코어; 및상기 PLGA 코어 표면에 형성되는 키토산 코팅;상기 키토산 코팅 표면에 마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 유효 성분을 포함하고, PLA(poly(lactic acid)):PGA(poly(glycolic acid)) 의 몰비가 1:4 내지 2:3 인 PLGA(poly(lactic-co-glycolic acid)) 고분자로 형성되는 PLGA 쉘; 및상기 PLGA 쉘 표면에 형성되는 알긴산 코팅;을 포함하는 화장품용 PLGA 나노입자., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

60/1059 Row 60: application_number: 1020200179652, combined_string: invention_title: 천연 복합 추출물을 함유하는 치주질환 개선용 구강 조성물 abstract: 본 발명은 치은염 또는 치주염 개선용 구강 조성물에 관한 것으로, 황련 추출물 및 고삼 추출물을 유효성분으로 포함하는 구강 조성물을 제공한다. claims: 황련 추출물, 감초 추출물, 녹차 추출물 및 고삼 추출물을 3:3:2:2의 중량비로 포함하고, 진지발리스균(P. Gingivitis)에 대한 항균 용도를 포함하고, 항염증, 치석 방지 및 구취 억제 용도를 포함하고,상기 추출물은 60 내지 80%(v/v) 농도의 에탄올 추출물인, 치주질환 개선용 구강 조성물., Ltext: 임업, prediction: 임업
61/1059 Row 61: application_number: 1020200178119, combined_string: invention_title: 위 건강 개선 및 헬리코박터균 억제를 위한 매스틱 및 천연물 유래 추출물을 포함하는 조성물 및 그 용도 abstract: 본 발명은 헬리코박터 파일로리(Helicobacter pyroli)균의 억제 효과를 갖는 매스틱 및 천연물 유래의 추출물을 포함하여 제조된 헬리코박터 파일로리 억제용 조성물과 상기 조성물의 용도 및 그 제조 방법에 관한 것이다. claims: 매스틱(Mastic, Pistacia lentiscus LINNE) 에센셜 오일 1 내지 10 중량부;금은화(Lonicera japonica) 10 내지 15 중량부, 감초(Glycyrrhiza uralensis) 10 내지 15 중량부, 인삼(Panax ginseng) 3 내지 9 중량부, 계피(Cinnamomum japonicum SIEB.) 3 내지 7 중량부, 차조기(Perilla frutescens) 2 내지 5 중량부 및 유카(Yucca gloriosa) 1 내지 5 중량부로 이루어진 군에서 하나 이상 선택된 천연물의 혼합 추출물을 포함하는 수상;을 혼합 후 고압 유화장치(microfluidizer)로 분산시켜 고압 분산 에멀젼화 하여 제조한 중심물질; 및상기 중심물질을, 오일상으로서 MCT:매스틱 오일:올리브 오일: 솔잣나무 잎 오일을 47:22:4:8의 중량비로 혼합한 피복물질;로 피복하여 제조한 미세캡슐을 포함하는, 헬리코박터 파일로리균(Helicobacter pyroli) 억제용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

62/1059 Row 62: application_number: 1020200170347, combined_string: invention_title: 천연 추출물 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 조성물 abstract: 본 발명은 천연물 기반인 녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 화장료 조성물에 관한 것이다. 본 발명의 조성물은 다양한 원인에 기한 피부의 비정상적 상태(아토피, 염증, 홍반, 산화, 피부 내 세포 독성물질, 수분의 소실, 기미, 가려움, 거칠어짐, 주름 등)를 효과적으로 진정시킬 수 있다. claims: 녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 화장료 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 염증 및 주름 개선인 것을 특징으로 하는 피부 진정용 화장료 조성물.제 1 항의 화장료 조성물을 포함하는 마스크팩.녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 식품 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 염증 및 주름 개선인 것을 특징으로 하는 피부 진정용 식품 조성물.녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 약제학적 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 염증 및 주름 개선인 것을 특징으로 하는 피부 진정용 약제학적 조성물., Ltext: 임업, prediction: 임업
63/1059 Row 63: application_number: 1020200166551, combined_string: invention_title: 천연 식물 혼합발효추출물을 유효성분으로 함유하는 피부 개선용 화장료 조성물 abstract: 본 발명은 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물을 함유하는 화장료 조성물에 관한 것으로, 본 발명에 따르면 유산균으로 발효된 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물을 유효성분으로 함유하는 화장료 조성물이 제공된다. 상기 유산균으로 발효된 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물을 유효성분으로 함유하는 화장료 조성물은 우수한 항산화, 피부주름 개선, 피부 탄력 개선, 피부보습 개선, 염증 완화 효과를 나타낸다. claims: 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물을 유효성분으로 조성물 전체 중량에 대하여 0.01~90 중량% 함유하는 화장료 조성물.(A) 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화를 각각 1~2: 1~2: 1~2: 1~2: 1~2: 1~2의 중량비로 혼합하여 혼합물을 제조하는 단계; (B) 상기 혼합물에 물, 에탄올, 메탄올, 부탄올, 프로판올, 부틸렌글리콜, 글리세린, 클로로포름, 에틸아세테이트, 디클로로메탄, 헥산, 아세톤, 아세토나이트릴, 페트로레움에테르 및 디에틸에테르로 이루어진 군으로부터 선택되는 적어도 하나의 용매를 가하고 추출하여 혼합추출물을 제조하는 단계; (C) 제조된 상기 혼합추출물에 바실루스 서브틸리스, 락토바실루스 브레비스, 페디오코커스 매시디락티스, 류코노스톡 메센테로이데스, 스트렙토코커스 써모필러스, 락토바실러스 카제이, 락토코코스 락티스, 락토바실러스 델부르키 및 엔테로코쿠스 페슘으로 이루어지는 군으로부터 선택되는 적어도 하나의 유산균을 접종하여 발효시키는 단계; 및 (D) 멸균 후 여과하는 단계를 포함하는 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물의 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

64/1059 Row 64: application_number: 1020200163928, combined_string: invention_title: 비타민나무 추출물의 비타민 안정성 증진을 위한 천연 소재 및 이의 제조 방법 abstract: 본 발명은 비타민 C와 복합체를 이룰 수 있는 펩티드에 관한 것으로서, 비타민 C가 외부의 산화 환경에 노출되는 것을 차단하여 비타민 C의 안정성을 증가시킬 수 있다. claims: 하기의 일반식 1의 아미노산 서열을 포함하는 펩티드:[일반식 1]X1-A-A-X2-X3상기 식에서 X1, X2, 및 X3는 각각 독립적으로 세린(Serine; S), 트레오닌(Threonine; T), 아스파라긴(Asparagine; N), 및 글루타민(Glutamine; Q)으로 이루어진 군으로부터 선택되는 어느 하나인 아미노산이고,상기 펩티드는 서열번호 1, 서열번호 2, 서열번호 3, 서열번호 4, 및 서열번호 5로 이루어진 군으로부터 선택된 아미노산 서열로 구성되는 것인 펩티드.제1항의 펩티드 및 비타민 C를 포함하는 복합체.제6항의 복합체를 포함하는 건강기능식품.제6항의 복합체를 포함하는 식품 첨가제.제6항의 복합체를 포함하는 화장료 조성물., Ltext: 임업, prediction: 임업
65/1059 Row 65: application_number: 1020200161492, combined_string: invention_title: 천연 추출물을 유효성분으로 하는 화장료 조성물 abstract: 본 발명은 천연 추출물을 유효성분으로 하는 화장료 조성물에 관한 것으로, 본 발명에 따른 화장료 조성물은 인체에 대한 부작용이 적을 뿐만 아니라 우수한 항노화 및 미백 효과를 가져 화장품, 피부 의약품 등에 유용하게 사용될 수 있다. claims: 천연 추출물을 유효성분으로 함유하는 화장료 조성물에 있어서,상기 천연 추출물은 꽃송이버섯 10~20 중량%, 함초 5~15 중량%, 알로에 5~15 중량%, 버드나무껍질 5~15 중량%, 노근 5~15 중량%, 콩뿌리 5~15 중량%, 무궁화잎 5~15 중량%, 매화 1~10 중량%, 수선화 1~10 중량%, 허브 1~10 중량%, 황칠나무잎 1~10 중량% 및 사과나무잎 1~10 중량% 비율의 혼합물을, 이산화탄소 분위기, 300 기압 및 60℃ 온도에서 초임계 추출하여 얻어진 복합 추출물이고,상기 화장료 조성물은 용액, 현탁액, 유탁액, 페이스트, 겔, 크림, 로션, 파우더, 비누, 클렌징, 오일, 분말파운데이션, 유탁액 파운데이션, 왁스 파운데이션, 팩, 마사지크림, 스프레이 및 미용팩으로 구성된 군으로부터 선택되는 제형이며,상기 크림은 초임계 추출물 0.1 내지 30중량%, 마유 1~5 중량%, 동백 오일 1~5 중량%, 코코넛 오일 1~5 중량%, 알라토닌 1~5 중량%, 스쿠알렌 1~5 중량%, 세라마이드 1~5 중량%, 히알루론산 1~10 중량%, 전분 1~10 중량%, 트라칸트 1~10 중량%, 실리콘 1~10 중량%, 벤토나이트 1~10 중량%, 폴리솔베이트 1~10 중량%, 폴리에틸렌글라이콜 스테아레이트 1~10 중량%, 글리세릴 스테아레이트 1~10 중량%, 폴리프로필렌글라이콜 1~10 중량%, 탈크 1~5 중량%, 산화아연 1~5 중량%, 글리세롤 1~5 중량% 및 정제수 0.5~3 중량%를 포함하는 것을 특징으로 하는 화장료 조성물., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

66/1059 Row 66: application_number: 1020200159140, combined_string: invention_title: 천연소재추출물을 포함하는 피부 개선용 식품 조성물 abstract: 본 발명은 천연소재추출물을 포함하는 피부 개선용 식품 조성물에 관한 것으로, 기존의 피부 외용제가 가지는 한계를 극복하고, 경구 섭취에 따라 표피층 전체와 진피층의 피부 조직에 피부 개선 효과가 전달되는 먹는 화장품을 제공한다. claims: 도라지추출물, 배추출물, 석류추출물 및 자소엽추출물을 모두 포함하며,상기 도라지추출물은 51~55 ℃에서 25~29 시간 추출한 것이고,상기 배추출물은 94~98 ℃에서 18~22 시간 추출한 것이고,상기 석류추출물은 94~98 ℃에서 12~16 시간 추출한 것이고,상기 자소엽추출물은 51~55 ℃에서 25~29 시간 추출한 것이며,도라지추출물, 배추출물, 석류추출물 및 자소엽추출물은 1:1:1:1의 중량비, 1:2:1:1의 중량비 또는 1:2:1:2의 중량비로 혼합되는 것을 특징으로 하는 폴리페놀이 강화된 피부 주름 개선용 식품 조성물.도라지추출물, 배추출물, 석류추출물 및 자소엽추출물을 모두 포함하며,상기 도라지추출물은 51~55 ℃에서 25~29 시간 추출한 것이고,상기 배추출물은 94~98 ℃에서 18~22 시간 추출한 것이고,상기 석류추출물은 94~98 ℃에서 12~16 시간 추출한 것이고,상기 자소엽추출물은 51~55 ℃에서 25~29 시간 추출한 것이며,도라지추출물, 배추출물, 석류추출물 및 자소엽추출물은 1:1:1:1의 중량비, 2:1:1:2의 중량비 또는 1:1:2:2의 중량비로 혼합되는 것을 특징으로 하는 폴리페놀이 강화된 피부 미백용 식품 조성물.도라지추출물, 배추출물, 석류추출물 및 자소엽추출물을 모두 포함하며,상기 도라지추출물은 51~55 ℃에서 25~29 시간 추출한 것이고,상기 배추출물은 94~98 ℃에서 18~22 시간 추출한 것이고,상기 석류추출물은 94~98 ℃에서 12~16 시간 추출한 것이고,상기 자소엽추출물은 51~55 ℃에서 25~29 시간 추출한 것이며,도라지추출물, 배추출물, 석류추출물 및 자소엽추출물은 1:1:1:1의 중량비, 1:1:2:1의 중량비, 2:2:1:1의 중량비 또는 1:2:2:1의 중량비로 혼합되는 것을 특징으로 하는 폴리페놀이 강화된 피부 보습용 식품 조성물., Ltext: 임업, prediction: 농업
67/1059 Row 67: application_number: 1020200154338, combined_string: invention_title: 혈액순환 개선 및 면역력 증진 효능을 가지는 천연 추출물을 포함하는 식품 조성물 abstract: 본 발명은 혈액순환 개선 및 면역력 증진 효능을 가지는 천연 추출물을 함유하는 조성물에 관한 것으로, 본 발명의 해조칼슘, 갈랑갈 추출분말, 홍삼 농축분말, 황기 추출분말, 백출 추출분말, 삼채 추출분말, 유산균 및 모링가 추출분말을 유효성분으로 포함하는 조성물은 혈소판 응집을 억제하여 혈전생성을 저해하는 효능이 있으며, 혈관의 수축을 억제하여 혈관 이완을 유도하는 효능이 있다. 또한, 콜레스테롤의 증가를 억제하여 혈액과 간의 지질을 감소시키는 효능이 인정된다. 따라서, 이러한 효능을 통해, 혈액 순환 개선에 효과적이며, 혈관 건강을 증진시킬 뿐만 아니라, 비만, 당뇨 및 고지혈증 등의 치료 또는 예방에 효과적으로 사용될 수 있다. 또한, 본 발명의 조성물은 면역력 증진에 매우 효과적이며, 피로회복, 소화기능 개선효과가 있을 뿐만 아니라, 항비만 및 항염증 효능을 가진다. claims: 해조칼슘 100 중량부에 대하여 갈랑갈 추출분말 12 내지 18 중량부, 홍삼 농축분말 20 내지 25 중량부, 황기 추출분말 12 내지 18 중량부, 백출 추출분말 5 내지 8 중량부, 삼채 추출분말 2 내지 3 중량부, 유산균 2 내지 3 중량부 및 모링가 추출분말 2 내지 3 중량부의 양으로 혼합되는 것을 특징으로 하는 식품 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

68/1059 Row 68: application_number: 1020200119183, combined_string: invention_title: 천연소재 추출물을 포함하는 피부 개선용 조성물 abstract: 본 발명은 몰식자, 소목, 대황, 오수유, 오필초, 향춘자 또는 가와 추출물을 유효성분으로 포함하는 화장료 조성물, 식품 조성물 또는 의약외품 조성물에 관한 것이다. 구체적으로, 상기 추출물을 유효성분으로 포함하는 항산화용; 피부 보습용; 피부 미백용; 피부 트러블 개선용; 주름 개선용; 피부 탄력 증진용; 또는 피부 재생용 조성물에 관한 것이다. 본 발명의 조성물은 항당화, 멜라닌 감소, 항염증, 콜라겐 합성 촉진, 엘라스타제 활성 저해, 세포 증식 효과가 우수하여, 항산화, 피부 보습, 피부 미백, 피부 트러블 개선, 주름 개선, 피부 탄력 증진, 피부 재생 용도로 유용하게 사용될 수 있다. 따라서, 본 발명의 조성물은 피부에 안전하면서도 피부 상태 개선 효과가 우수한 화장료 조성물, 식품 조성물, 의약외품 조성물로 이용될 수 있다. claims: 몰식자, 소목, 대황, 오수유, 오필초, 향춘자 또는 가와 추출물을 유효성분으로 포함하는 항당화용 화장료 조성물., Ltext: 임업, prediction: 농업
69/1059 Row 69: application_number: 1020200118754, combined_string: invention_title: 견운모 추출물의 제조 방법, 상기 방법에 의해 제조되는 견운모 용매 추출물 및 상기 견운모 용매 추출물을 이용한 천연 미네랄 이온수의 제조 방법 abstract: 본 발명은 견운모 추출물의 제조 방법, 상기 방법에 의해 제조되는 견운모 용매 추출물 및 상기 견운모 용매 추출물을 이용한 천연 미네랄 이온수의 제조 방법에 관한 것으로서, 더욱 상세하게는 국내에서 다량 생산되는 고급 견운모로부터 유효성분을 추출하여 이를 이용해 탈취제, 항균제 또는 화장품 원료 등으로 사용하는 기술을 제공한다. 본 발명에 따르면, 견운모를 활용하여 천연 미네랄 이온수를 제조함에 있어서, 견운모 표면에 존재하는 이물질을 완전 제거하고, 용매 추출을 이용해 고순도의 천연 미네랄 이온수를 제조함으로써 식품첨가물 뿐만 아니라, 탈취제, 항균제, 화장품 원료 등의 다양한 용도로 활용할 수 있는 기술을 제공할 수 있다. 따라서 자연 상태로 존재하는 많은 견운모를 단지 분말화하여 타 성분의 보조성분으로만 활용하는 것이 아니라 식품첨가물, 탈취제, 항균제, 화장물 원료 등의 주성분으로 재활용함으로써 부가가치 높은 제품을 제조할 수 있는 방안이 될 수 있다. claims: (1) 견운모를 산성 용액에 침지하여 교반한 후 세척하는 제1단계;(2) 상기 제1단계에서 얻어진 견운모를 전기로에 투입하여 800~1200℃의 온도로 12 내지 36 시간 동안 직접 소성하고 냉각시키는 제2단계;(3) 상기 제2단계에서 얻어진 다공질화된 견운모를 100~300 메쉬 크기로 분말화하는 제3단계;(4) 상기 제3단계에서 얻어진 견운모 분말을 내열성 용기에 넣은 후 밀봉하고, 이를 다시 350~ 500 kHz의 고주파로에 넣어 1400~1800℃의 온도로 0.5~2 시간 동안 간접 소성하고 냉각시키는 제4단계;(5) 상기 제4단계에서 얻어진 분말을 400~700 메쉬 크기로 분말화하는 제5단계;(6) 상기 제5단계에서 얻어진 분말을 용매 처리하여 추출물을 얻고 석출물을 여과시킨 후 액상 성분만을 분리하는 제6단계; 및(7) 상기 제6단계에서 얻어진 액상 성분을 농축기에 넣고 농축하는 제7단계;를 포함하여 구성되는 것을 특징으로 하며, 상기 제6단계에서 상기 용매 처리하여 추출물을 얻는 것은 상기 제5단계에서 얻어진 견운모 분말 중량의 10 내지 20배에 해당하는 부피의 에탄올에 24 시간 동안 가압 침지하여 이온 상태의 미네랄 성분을 추출하고 이온화되지 않은 금속 물질 부유물을 여과포를 이용하여 여과시켜 액상 성분만을 분리하는 것을 특징으로 하며, 상기 제7단계에서 액상 성분을 농축기에 넣고 농축함으로써 이온수의 순도가 97~99.9 중량%에 해당하는 이온수를 얻는 것을 특징으로 하는 견운모 추출물의 제조 방법.청구항 6에 따른 방법으로 제조되며, 탈취제 또는 화장품 원료로 이용되는 것을 특징으로 하는 견운모 추출물을 이용한 천연 미네랄 이온수., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

70/1059 Row 70: application_number: 1020200116667, combined_string: invention_title: 유산균주, 유산균 발효물 및 천연 추출물을 함유하는 항노화 화장료 조성물 및 그 제조방법 abstract: 본 발명은 유산균주, 유산균 발효물 및 천연 추출물을 함유하여 피부 광택이 뛰어난 피부 항노화 화장료 조성물을 제공한다. 항노화 화장료 조성물은 락토바실러스 카제이(Lactobacillus casei, 기탁번호:KCTC3110)와 락토바실러스 람노서스(Lactobacillus rhamnosers, 기탁번호:KCTC3237)를 사용하는 유산균주, 락토바실러스 발효물(Lactobacillus sakei subsp. Sakei), 비피다발효여과물(Bifidobacterium bifidum) 및 락토코쿠스 발효물(Lactococcus lactis subsp. lactis)을 사용하는 유산균 발효물 및 천연추출물을 유효성분으로 함유하여 피부 광택 기능을 부여한다. claims: 락토바실러스 카제이(Lactobacillus casei, 기탁번호:KCTC3110)와 락토바실러스 람노서스(Lactobacillus rhamnosers, 기탁번호:KCTC3237)를 사용하는 유산균주, 락토바실러스 발효물(Lactobacillus sakei subsp. Sakei), 비피다발효여과물(Bifidobacterium bifidum) 및 락토코쿠스 발효물(Lactococcus lactis subsp. lactis)을 사용하는 유산균 발효물 및 천연추출물을 유효성분으로 함유하여 피부 광택 기능을 부여하는 항노화 화장료 조성물.락토바실러스 카제이(Lactobacillus casei, 기탁번호:KCTC3110) 균주와 락토바실러스 람노서스(Lactobacillus rhamnosers, 기탁번호:KCTC3237) 균주를 배양한 배양액을 가열 멸균 처리하여 유산균주 사균체액을 제조하는 제1 단계;상기 유산균주 사균체액과 유산균 발효물을 1:3의 배합비로 혼합하여 혼합액을 제조하는 제2 단계; 및상기 혼합액에 흰목이버섯에서 추출한 베타-글루칸, 사케에서 추출하여 동결건조시킨 쌀발효여과물 및 요엽후박나무껍질추출물을 포함하는 천연 추출물을 2:1의 배합비로 혼합하는 제3 단계를 포함하는 유산균주, 유산균 발효물 및 천연 추출물을 함유하는 항노화 화장료 조성물 제조 방법., Ltext: 임업, prediction: 임업
71/1059 Row 71: application_number: 1020200114285, combined_string: invention_title: 돌콩 추출물을 포함하는 천연 화장료 조성물 abstract: 본 발명은 돌콩 추출물을 포함하는 천연 화장료 조성물로 특히, 돌콩 추출물을 포함하여, 피부 흡수율 및 제형 안정성이 우수한 천연 화장료 조성물에 관한 것이다.구체적으로, 본 발명은 디우탄검을 포함하는 천연 점증제; 탄소수 5 내지 6의 탄소사슬을 포함하는 폴리올; 및 돌콩 추출물;을 포함하는 천연 화장료 조성물로서, 천연 유래 성분들로 구성되어 피부에 저자극이면서도 피부 흡수율 및 제형 안정성이 우수할 수 있다. claims: 디우탄검을 포함하는 천연 점증제;탄소수 5 내지 6의 탄소사슬을 포함하는 폴리올; 및돌콩 추출물;을 포함하되,조성물 총 중량 기준으로 상기 천연 점증제 0.01 ~ 5 중량%, 상기 폴리올 2 ~ 10 중량%, 상기 돌콩 추출물 0.001 ~ 10 중량% 및 잔량의 물을 포함하는 것을 특징으로 하는, 돌콩 추출물을 포함하는 천연 화장료 조성물., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

72/1059 Row 72: application_number: 1020200114757, combined_string: invention_title: 천연물 유래 추출물을 포함하는 탈모 방지용 외용제 조성물 및 그 제조방법 abstract: 본 발명은 천연물 유래 추출물을 포함하는 탈모방지용 외용제 조성물과 이의 제조방법에 관한 것이다.구체적으로, 본 발명의 조성물은 또한, 본 발명은 천연물 유래 추출물을 포함함으로써, 피부에 적용시 우수한 보습효과를 보여 두피 생장을 촉진하기 위한 최적의 환경을 조성할 수 있으며, 두피의 열을 내리고, 모유두세포의 분화를 촉진하며, 모발의 굵기가 굵어지는 복합적인 효과를 동시에 나타내는 것을 특징으로 한다. claims: 발효 균주를 접종하여 발효한 천연물 유래 혼합 추출물을 포함하는 탈모 방지 및 육모 촉진용 조성물에 있어서,상기 천연물 유래 혼합 추출물은 도둑놈의지팡이 뿌리 추출물 28 중량부, 고추 열매 추출물 17 중량부, 구기자 추출물 19 중량부, 녹차 추출물 15 중량부, 참당귀 뿌리 추출물 20 중량부, 구릿대 뿌리 추출물 25 중량부, 뽕나무 열매 추출물 22 중량부, 뽕나무 뿌리 추출물 10 중량부, 대왕송잎 추출물 15 중량부, 지치 뿌리 추출물 12 중량부, 하수오 뿌리 추출물 10 중량부, 라벤더 추출물 5 중량부, 베르가못 잎 추출물 5 중량부, 페퍼민트 잎 추출물 7 중량부, 프리지아 추출물 3 중량부, 마트리카리아 꽃 추출물 3 중량부 및 로즈마리 잎 추출물 3 중량부를 포함하고,상기 발효는 발효 균주로서 락토바실러스 애시도필러스(Lactobacillus acidophilus), 락토바실러스 헬베티커스(Lactobacillus helveticus), 락토바실러스 람노서스(Lactobacillus rhamnosus), 비피도박테리움 롱검(Bifidobacterium longum), 비피도박테리움 락티스(Bifidobacterium lactis), 비피도박테리움 애니말리스(Bifidobacterium animalis), 비피도박테리움 비피덤(Bifidobacterium bifidum), 락토바실러스 카제이(Lactobacillus casei) 및 엔테로코커스 패시움(Enterococcus faecium)을 이용한 것인, 탈모 방지 및 육모 촉진용 조성물., Ltext: 임업, prediction: 임업
73/1059 Row 73: application_number: 1020200112986, combined_string: invention_title: 천연물 유래 추출물을 포함하는 혈당 강하용 조성물 abstract: 본 발명은 황기, 도라지, 칡, 진피, 구기자, 둥굴레, 맥문동 및 마를 포함하는 혈당 강하용 조성물과 이를 포함하는 기능성 식품 조성물에 관한 것이다.인체에 무해한 천연 원료만을 포함하여 제조되는 것으로서, 혈당 상승과 관련이 있는 α-아밀라아제(α-amylase) 및 α-글루코시다아제(α-glucosidase)의 저해활성을 가지고, 꾸준히 복용하는 경우 식후 혈당 상승을 억제하는 효과가 있음을 확인하였다. claims: 황기 50 중량부, 도라지 50 중량부, 칡 50 중량부, 진피 50 중량부, 구기자 100 중량부, 둥굴레 50 중량부, 맥문동 50 중량부 및 마 100 중량부의 추출물을 포함하고,상기 황기 및 도라지는 각 50 중량부에 정제수 50 중량부씩 첨가한 후 100℃에서 6시간동안 열수 추출하였고, 상기 칡 및 진피는 각 50 중량부에 정제수 50 중량부를 첨가한 후 98℃에서 4시간동안 열수 추출하였으며, 상기 구기자 100 중량부 및 50 중량부에 같은 중량부의 정제수를 첨가한 후 95℃에서 6시간동안 열수 추출하였고, 상기 맥문동 50 중량부 및 마 100 중량부에 같은 중량부의 정제수를 첨가한 후 92℃에서 6시간동안 추출하여 제조한 것인, 혈당 강하용 조성물.황기 및 도라지 각 50 중량부에 정제수 50 중량부씩 첨가한 후 100℃에서 6시간동안 열수 추출하는 단계;칡 및 진피 각 50 중량부에 정제수 50 중량부를 첨가한 후 98℃에서 4시간동안 열수 추출하는 단계;구기자 100 중량부 및 50 중량부에 같은 중량부의 정제수를 첨가한 후 95℃에서 6시간동안 열수 추출하는 단계; 및맥문동 50 중량부 및 마 100 중량부에 같은 중량부의 정제수를 첨가한 후 92℃에서 6시간동안 추출하는 단계;를 포함하는, 혈당 강하용 조성물의 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

74/1059 Row 74: application_number: 1020200106207, combined_string: invention_title: 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법 및 이를 함유하는 화장료 조성물 abstract: 본 발명은 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법 및 이를 함유하는 화장료 조성물에 관한 것으로서, 더욱 상세하게는 각종 생약 추출물을 가온 마이크로버블 추출 방법을 활용하여 추출 효율을 극대화시킬 수 있는 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법 및 이를 함유하는 화장료 조성물에 관한 것이다. claims: 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법에 있어서,가온마이크로버블시스템(1000)의 천연추출물공급자켓(100)의 내부 공간에 천연 화장품 원료를 투입하기 위한 천연화장품원료투입단계(S100);와가온마이크로버블시스템(1000)의 용매공급용펌프(200)를 동작시켜 용매탱크(300)에 저장된 용매를 천연추출물공급자켓(100)으로 공급하기 위한 용매투입단계(S200);와가온마이크로버블시스템(1000)에서 용매투입선감지센서(950)로부터 제공된 이벤트 신호를 획득할 경우에 용매공급용펌프(200)로 동작 정지 신호를 제공하여 용매 공급을 차단하기 위한 용매공급차단단계(S300);와가온마이크로버블시스템(1000)의 마이크로버블발생기(600)를 동작시키고, 일정 시간 경과 후, 마이크로버블공급용펌프(500)를 동작시켜 마이크로버블발생기(600)에 의해 발생된 마이크로 버블을 천연추출물공급자켓(100)으로 공급하여 마이크로 버블에 의해 천연 화장품 원료와 용매가 지속적으로 접촉하고, 용존 산소 및 OH 라디칼의 증가를 통해 유용 성분의 추출을 수행하기 위한 마이크로버블공급단계(S400);와가온마이크로버블시스템(1000)의 가온수단(800)을 동작시켜 천연추출물공급자켓(100) 내부의 온도를 높이고, 이를 통해 공급된 용매를 가열시켜 천연 화장품 원료의 유용 성분의 추출을 극대화시키기 위한 가온단계(S500);와가온마이크로버블시스템(1000)에서 용매수위상한선감지센서(970)로부터 제공된 이벤트 신호를 획득할 경우에 마이크로버블공급용펌프(500)의 토출량을 줄여주기 위하여 마이크로버블공급용펌프(500)로 토출량 감소 신호를 제공하여 추출 진행에 따른 거품 발생을 축소시키기 위한 거품발생축소단계(S510);와가온마이크로버블시스템(1000)이 설정된 시간 경과 후, 마이크로버블공급용펌프(500) 및 마이크로버블발생기(600)로 동작 정지 신호를 제공하여 동작을 종료시키며, 일정 시간 경과 후, 가온수단(800)에 동작 정지 신호를 제공하여 천연 화장품 원료의 추출 공정을 마무리하기 위한 가온마이크로버블공정마무리단계(S600);와가온마이크로버블시스템(1000)에서 용매배출구(905)에 형성된 용매배출밸브(915)에 개방 신호를 송출하여 용매배출구(905)를 개방시켜 천연추출물공급자켓(100)의 내부 공간에 추출 후 존재하는 용매를 외부로 배출하는 용매배출단계(S700);를 포함하여 구성되되,상기 단계를 수행하기 위하여, 가온마이크로버블시스템(1000)은,내부에 일정한 체적 공간을 가지고 있으며, 상측에 화장료 조성물로 이용되는 천연 화장품 원료를 투입하기 위한 천연재료투입구(110)가 형성되어 있는 천연추출물공급자켓(100);과상기 천연추출물공급자켓(100)의 어느 일측에 형성시켜 천연추출물공급자켓(100)으로 용매탱크에 보관된 용매를 공급하게 되는 용매공급용펌프(200);와상기 용매공급용펌프(200)에 연결되어 용매공급용펌프(200)가 동작할 경우에 저장된 용매를 천연추출물공급자켓(100)으로 공급하게 되는 용매탱크(300);와상기 천연추출물공급자켓(100)에 일측이 설치 구성하여 용매공급용펌프(200)로부터 공급받은 용매를 공급하기 위한 용매공급수단(400);과상기 천연추출물공급자켓(100)의 하측에 구성하여 천연추출물공급자켓(100)에 마이크로버블발생기로부터 발생된 마이크로 버블을 공급하게 되는 마이크로버블공급용펌프(500);와상기 마이크로버블공급용펌프(500)에 연결하여 마이크로버블공급용펌프(500)가 동작할 경우에 발생된 마이크로 버블을 천연추출물공급자켓(100)으로 공급하게 되는 마이크로버블발생기(600);와상기 천연추출물공급자켓(100)의 일측에 설치 구성하여 마이크로버블공급용펌프(500)로부터 공급받은 마이크로 버블을 공급하기 위한 마이크로버블공급수단(700);과천연추출물공급자켓(100)의 외면을 따라 설치 구성하여 전원이 공급될 경우에 가온되어 상기 천연추출물공급자켓(100) 내부의 온도를 높이고, 이를 통해 공급된 용매를 가열시켜 천연 화장품 원료의 유용 성분의 추출을 더욱 극대화시키게 되는 가온수단(800);을 특징으로 하며,상기 가온수단(800)은,상기 천연추출물공급자켓(100)의 중심축을 기준으로 원통 모양으로 권취되어 나선형을 형성하는 열에너지생성코일부(810);상기 열에너지생성코일부(810)로 주파수를 발진하는 주파수발진부(820);를 포함하여 구성하는 것을 특징으로 하며,상기 천연추출물공급자켓(100)에는 용매투입선감지센서(950)보다 높은 위치에 용매수위상한선감지센서(970)를 설치 구성하는 것을 특징으로 하며,상기 가온마이크로버블시스템(1000)에는컨트롤러(900);가 형성되게 되는데,상기 컨트롤러(900)는,용매공급수단(400)에 형성된 용매공급밸브(925)에 개방 신호를 제공하고, 개방될 경우에 용매공급용펌프(200)에 동작 신호를 제공하여 동작시켜 용매탱크(300)에 저장된 용매를 천연추출물공급자켓(100)으로 공급하기 위한 용매공급처리부(910);와용매투입선감지센서(950)에서 용매를 감지하게 되면 임계치에 도달함을 알리기 위한 이벤트 신호를 생성하여 용매공급용펌프(200)로 동작 정지 신호를 제공하기 위한 용매공급용펌프동작정지처리부(920);와마이크로버블발생기(600)를 동작시키기 위한 동작 신호를 제공하고, 설정된 시간만큼 경과 후, 마이크로버블공급용펌프(500)를 동작시키기 위한 동작 신호를 제공하고, 마이크로버블발생기(600)에 의해 발생된 마이크로 버블을 천연추출물공급자켓(100)으로 공급하기 위하여 마이크로버블공급밸브(935)로 동작 신호를 제공하기 위한 마이크로버블공급처리부(930);와가온수단(800)을 동작시키기 위하여 가온수단으로 동작 신호를 제공하기 위한 가온수단동작처리부(940);와설정된 시간 경과 후, 마이크로버블공급용펌프(500) 및 마이크로버블발생기(600)로 동작 정지 신호를 제공하여 동작을 종료시키며, 일정 시간 경과 후, 가온수단(800)에 동작 정지 신호를 제공하여 천연 화장품 원료의 추출 공정을 마무리하기 위한 추출공정마무리처리부(950);와용매수위상한선감지센서(970)로부터 제공된 이벤트 신호, 즉, 수위 감지 신호를 획득할 경우에 마이크로버블공급용펌프(500)의 토출량을 줄여주기 위하여 마이크로버블공급용펌프(500)로 토출량 감소 신호를 제공하여 추출 진행에 따른 거품 발생을 축소시키기 위한 거품발생축소처리부(960);와용매배출밸브(915)에 개방 신호를 송출하여 용매배출구(905)를 개방시켜 천연추출물공급자켓(100)의 내부 공간에 추출 후 존재하는 용매를 외부로 배출하기 위한 용매배출처리부(970);를 특징으로 하며,상기 마이크로버블발생기(600)는 5 ~ 50um 의 포어사이즈, 1.0 ~ 1.2 Ton / hr 의 토출량을 가진 것을 특징으로 하는 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법.제 1항의 제조방법으로 제조된 천연 추출물을 유효성분으로 함유하는 화장료 조성물., Ltext: 임업, prediction: 임업
75/1059 Row 75: application_number: 1020200103058, combined_string: invention_title: 천연 추출물을 이용한 기능성 마스크 제조공법 및 이의 제조공법으로 제조된 마스크 abstract: 본 발명은 천연 추출물을 이용한 기능성 마스크 제조공법 및 이의 제조공법으로 제조된 마스크에 관련되며, 이는 마스크원단 생지에 녹차 추출물, 편백 추출물, 치자 추출물, 청미래덩굴 추출물을 포함하는 천연염료를 염색처리하여 마스크원단 생지 고유의 이취를 제거함과 더불어 살균작용으로 마스크 착용자 입냄새 구취 제거 및 비말로 인한 세균번식을 차단하여 장시간 쾌적한 착용감을 제공할 수 있도록 천연염색단계(S10), 가재단단계(S20), 천연분말 합성공정(S30), 정재단단계(S40), 성형공정(S50), 접합공정(S60)을 포함하여 주요구성으로 한다. claims: 마스크원단 생지(10)를 평탄화처리 후, 녹차 추출물, 편백 추출물, 치자 추출물, 청미래덩굴 추출물 중 어느 1종 이상의 추출물을 포함하는 천연염료를 이용하여 염색하는 천연염색단계(S10);상기 천연염색단계(S10)를 거친 염색원단(20)을 평탄화처리 후, 소정의 사이즈로 가재단하는 가재단단계(S20);상기 가재단단계(S20)를 거친 가재단원단(30)을 평탄화처리 후, 녹차, 편백, 쑥, 생강, 솔잎 중 어느 1종 이상의 천연분말을 첨가하는 천연분말 합성공정(S30);상기 천연분말이 첨가된 가재단원단(30)을 마스크모양으로 정재단하는 정재단단계(S40);정재단원단(40)을 마스크 모양으로 봉제 및 프레스 가공하는 성형공정(S50); 및상기 성형공정(S50)을 거친 마스크본체(50) 양측에 끈(52)을 부착하는 접합공정(S60);을 포합하고,상기 천연염색단계(S10)에서 천연염료는 물 100% 중량부 기준 녹차, 편백, 치자, 청미래덩굴 중 어느 1종 이상의 천연분말을 5~10 중량부를 혼합한 후, 5~15℃ 온도에서 1~3일 동안 우려내는 방식으로 추출한 후, 여과처리하여 준비되며,상기 천연염료는 염색조(100)에 저장되고, 상기 마스크원단 생지(10)는 복수의 상, 하부 피딩롤러(120)(140)를 경유하여 지그재그방향으로 횡형 이동되며, 상기 하부 피딩롤러(140)는 염색조(100)에 저장된 천연염료에 잠기도록 배치되고, 상기 마스크원단 생지(10)가 상, 하부 피딩롤러(120)(140)를 타고 피딩되는 중에 하부 피딩롤러(140)와 대응하는 위치에서 천연염료에 일시적으로 잠기면서 염색이 이루어지며, 상부 피딩롤러(120) 내부에 내부히터(122)가 설치되거나 상부 피딩롤러(120)와 대응하는 외측에 외부히터(124)가 설치되어 염색처리된 마스크원단 생지(10)를 건조하도록 구비되며, 상기 하부 피딩롤러(140)를 경유하는 중에 수행되는 염색과정과 상부 피딩롤러(120)를 경유하는 중에 수행되는 건조과정을 수회 반복하여 천연염료에 의핸 염색농도가 조절되도록 구비되는 것을 특징으로 하는 천연 추출물을 이용한 기능성 마스크 제조공법.상기 제 1항, 제 2항, 제 5항 내지 제 12항 중 어느 한 항의 천연 추출물을 이용한 기능성 마스크 제조공법을 이용하여,녹차 추출물, 편백 추출물, 치자 추출물, 청미래덩굴 추출물 중 어느 1종 이상의 추출물을 포함하는 천연염료에 염색하여 형성되는 마스크본체(50) 양측에 끈(52)을 부착하여 형성되는 것을 특징으로 하는 천연 추출물을 이용한 기능성 마스크 제조공법으로 제조된 마스크., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

76/1059 Row 76: application_number: 1020200096555, combined_string: invention_title: 천연 추출물을 함유하는 면역력 증강용 조성물 abstract: 본 발명은 천연 추출물을 유효성분으로 포함하는 혈액순환 개선 및 면역력 증진 효능을 가지는 조성물에 관한 것으로, 노니, 사과, 양파, 가지, 대두, 생강 및 카카오 추출물을 유효성분으로 포함하는 본 발명의 조성물은 혈액순환을 개선하고 면역기능을 강화한다. 또한 본 발명의 천연 추출물은 세포 독성이 없어 약학적 및 식품 조성물에 안전하게 사용할 수 있다. claims: 노니, 사과, 양파, 가지, 대두, 생강 및 카카오 추출물을 유효성분으로 포함하는 천연 추출물을 함유하는 면역력 증강용 조성물.제 1 항 내지 제 3 항 중 어느 한 항에 있어서.상기 조성물이 약학적 조성물인 것을 특징으로 천연 추출물을 함유하는 면역력 증강용 조성물.제 1 항 내지 제 3 항 중 어느 한 항에 있어서.상기 조성물이 식품 조성물인 것을 특징으로 천연 추출물을 함유하는 면역력 증강용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

77/1059 Row 77: application_number: 1020200095495, combined_string: invention_title: 천연발효 추출물 혼합 조성물 abstract: 본 발명은 한국에서 자생하는 천연식물들을 열수추출한 열수 추출물을 농축과 증류수를 일정비율로 혼합한 혼합물을 다단 발효시킨 복합발효물을 숙성시킨 숙성물을 농축시켜 제조한 천연 발효 추출물 혼합 조성물 및 이를 화장품 원료, 건강기능식품 원료, 바이오 천연 약물 원료 등으로 적용할 수 있는 발명에 관한 것이다. claims: 천연식물 복합 열수 추출물을 다단 발효시킨 발효물의 숙성물을 농축시킨 농축물을 포함하며,상기 천연식물 복합 열수 추출물은 천연식물 혼합 건조물을 열수 추출시켜서 수득한 열수 추출물이고,상기 천연식물 혼합 건조물은 쇠뜨기 100 중량부에 대하여, 어성초 1 ~ 5 중량부, 쇠비름 5 ~ 10 중량부, 붉나무 1 ~ 10 중량부, 비누나무 1 ~ 5 중량부, 함초 5 ~ 10 중량부, 백작약 1 ~ 5 중량부, 숙지황 20 ~ 30 중량부, 목단피 20 ~ 30 중량부, 백부근 30 ~ 50 중량부, 섬가시오가피 20 ~ 40 중량부, 황칠 1 ~ 10 중량부, 사상자 1 ~ 10 중량부, 형개 1 ~ 10 중량부, 지부자 10 ~ 20 중량부, 백두옹 0.5 ~ 5 중량부, 금화규 1 ~ 5 중량부, 당귀 5 ~ 20 중량부 및 꾸지뽕의 잎과 줄기 20 ~ 30 중량부를 포함하며,상기 발효물은 혐기성균을 이용한 1차 발효, 호기성균을 이용한 2차 발효 및 토양 미생물을 이용한 3차 발효를 포함하는 다단 발효 공정을 수행한 발효물을 포함하고,상기 혐기성균은 바실러스 속균 및 누룩균을 1 : 0.1 ~ 0.2 비율(CFU 비율)로 혼합한 혐기성 혼합 균주를 포함하며,상기 호기성균은 마리노박터균과 효모균을 1 : 1 ~ 2 비율(CFU 비율)로 혼합한 호기성 혼합 균주를 포함하고,상기 토양 미생물은 버섯균 및 유산균 중에서 선택된 1종 또는 2종을 포함하는 것을 특징으로 하는 천연발효 추출물 혼합 조성물.제3항의 천연발효 추출물 혼합 조성물을 포함하는 화장료.제3항의 천연발효 추출물 혼합 조성물을 포함하는 건강기능식품.천연식물 혼합 건조물을 열수 추출하여 열수 추출물을 제조하는 1단계;상기 천연식물 복합 열수 추출물 및 증류수를 혼합한 혼합액을 다단 발효를 수행하여 발효물을 수득하는 2단계;상기 발효물을 3 ~ 10℃ 하에서 24 ~ 48 시간 동안 숙성시켜서 숙성물을 수득하는 3단계; 및상기 숙성물을 농축시켜서 농축액을 제조하는 4단계;를 포함하는 공정을 수행하며,상기 다단 발효는 1단계에서 제조한 상기 천연식물 복합 열수 추출물 및 증류수를 1 : 1 ~ 3 부피비로 혼합한 혼합액에 혐기성균을 접종한 후, 40 ~ 50℃에서 15~20일간 1차 발효를 수행하여 1차 발효액을 수득하는 2-1 단계;1차 발효액을 필터링한 후, 필터링된 1차 발효액에 호기성균을 접종한 후, pH 5.5 ~ 6.5 및 15~40℃에서 3~5일간 2차 발효를 수행하여 2차 발효액을 수득하는 2-2단계; 및2차 발효액을 필터링한 후, 필터링된 2차 발효액에 광합성 미생물과 토양미생물을 접종한 후, 3차 발효를 수행하여 3차 발효액을 수득한 후, 필터링하여 다단 발효공정을 수행한 발효물을 제조하는 2-3단계;를 포함하는 공정을 수행하고,상기 천연식물 혼합 건조물은 쇠뜨기 100 중량부에 대하여, 어성초 1 ~ 5 중량부, 쇠비름 5 ~ 10 중량부, 붉나무 1 ~ 10 중량부, 비누나무 1 ~ 5 중량부, 함초 5 ~ 10 중량부, 백작약 1 ~ 5 중량부, 숙지황 20 ~ 30 중량부, 목단피 20 ~ 30 중량부, 백부근 30 ~ 50 중량부, 섬가시오가피 20 ~ 40 중량부, 황칠 1 ~ 10 중량부, 사상자 1 ~ 10 중량부, 형개 1 ~ 10 중량부, 지부자 10 ~ 20 중량부, 백두옹 0.5 ~ 5 중량부, 금화규 1 ~ 5 중량부, 당귀 5 ~ 20 중량부 및 꾸지뽕의 잎과 줄기 20 ~ 30 중량부를 포함하며,상기 발효물은 혐기성균을 이용한 1차 발효, 호기성균을 이용한 2차 발효 및 토양 미생물을 이용한 3차 발효를 포함하는 다단 발효 공정을 수행한 발효물을 포함하고,상기 혐기성균은 바실러스 속균 및 누룩균을 1 : 0.1 ~ 0.2 비율(CFU 비율)로 혼합한 혐기성 혼합 균주를 포함하며,상기 호기성균은 마리노박터균과 효모균을 1 : 1 ~ 2 비율(CFU 비율)로 혼합한 호기성 혼합 균주를 포함하고,상기 토양 미생물은 버섯균 및 유산균 중에서 선택된 1종 또는 2종을 포함하는 것을 특징으로 하는 천연발효 추출물 혼합 조성물의 제조방법., Ltext: 임업, prediction: 임업
78/1059 Row 78: application_number: 1020200081542, combined_string: invention_title: 천연 식물추출물을 함유하는 탈취제 조성물 abstract: 본 발명은 천연 식물추출물을 함유하는 탈취제 조성물에 관한 것으로, 보다 구체적으로는 밤부사 불가리스잎/줄기 추출물, 삼나무잎 추출물, 편백잎 추출물, 나한백가지 추출물 및 분비나무 오일로 이루어진 혼합물을 함유하는 탈취제 조성물에 관한 것이다. 본 발명에 따른 탈취제 조성물은 악취를 유발하는 주요성분인 암모니아, 초산, 포름알데히드, 황화수소, 트리메틸아민에 대한 소취효과가 우수하므로 탈취제로 유용하게 사용될 수 있다. claims: 밤부사 불가리스잎/줄기 추출물, 삼나무잎 추출물, 편백잎 추출물, 나한백가지 추출물 및 분비나무 오일이 동일한 중량비로 혼합되어 이루어지는 혼합물을 탈취제 조성물 전체 중량에 대하여 2.0~5.0중량% 함유하여 암모니아, 초산, 포름알데히드, 황화수소 및 트리메틸아민에 대한 소취효과를 나타내는 탈취제 조성물., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

79/1059 Row 79: application_number: 1020200074790, combined_string: invention_title: 천연물 유래 추출물 및 이를 포함하는 화장료 조성물 및 이의 제조방법 abstract: 본 발명은 천연물 유래 추출물 및 에센셜 오일을 함유하는 화장료 조성물에 관한 것으로서, 상기 화장료 조성물은 피부장벽 개선, 피부 보습, 피부 진정, 각질제거, 블랙헤드 케어, 피부결 정돈, 광채감 부여 및 영양공급 효과를 갖는 것을 특징으로 한다. claims: 육두구(Nutmeg) 20 내지 50 중량부, 하늘타리(Chinese cucumber) 뿌리 20 내지 50 중량부, 흰무늬엉겅퀴(Silybum marianum) 씨 10 내지 40 중량부, 엘더플라워(Elder flower) 10 내지 40 중량부, 다마스크장미(Rosa Damascena) 꽃 10 내지 30 중량부, 라벤더꽃 10 내지 30 중량부, 클레리(Salvia Sclarea) 10 내지 30 중량부, 히아신스(Hyacinthus) 전초 1 내지 30 중량부, 마트리카리아(Matricaria chamomilla) 꽃 1 내지 30 중량부, 보리지(Borago officinalis) 1 내지 30 중량부 및 수레국화(Centaurea cyanus) 꽃 1 내지 30 중량부로부터 수득한 추출물; 및 베르가못(citrus aurantium bergamia, bergamot) 오일 1 내지 5 중량부, 티트리(Melaleuca alternifolia) 오일 1 내지 5 중량부, 오렌지(Citrus Aurantium Dulcis) 오일 1 내지 5 중량부 및 해바라기씨 오일 1 내지 30 중량부를 포함하여 제조된 것인, 화장료 조성물., Ltext: 임업, prediction: 임업
80/1059 Row 80: application_number: 1020200064776, combined_string: invention_title: 오미자, 백리향 및 꽃향유의 추출 혼합물을 유효성분으로 함유하는 천연 방부대체제 및 이의 용도 abstract: 본 발명은 오미자, 백리향 및 꽃향유의 추출 혼합물을 유효성분으로 함유하는 천연 방부대체제 및 이의 용도에 관한 것으로, 본 발명의 오미자, 백리향 및 꽃향유의 추출 혼합물은 스타필로코커스 아우레우스(Staphlyococcus aureus), 슈도모나스 에루지노사(Pseudomonas aeruginosa), 대장균(Escherichia coli), 칸디다 알비칸스(Candida albicans) 및 아스퍼질러스 브라실리엔시스(Aspergillus brasiliensis)에 대해 우수한 항균 효과를 나타내며, 이를 함유한 화장료 조성물은 항균력, 방부력 및 보존력이 우수하므로, 합성 방부제를 대체할 수 있는 천연 방부제로서 화장료 조성물 제조에 매우 유용하게 이용될 수 있다. claims: 칸디다 알비칸스(Candida albicans) 및 아스퍼질러스 브라실리엔시스(Aspergillus brasiliensis)에 대한 항균 활성을 가지는, 4:1:1의 중량비로 혼합한 오미자, 백리향 및 꽃향유 에탄올 추출물의 혼합물을 유효성분으로 포함하는 방부제 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

81/1059 Row 81: application_number: 1020200060133, combined_string: invention_title: 액화 천연 가스(LNG)로부터 천연 가스액(NGL)을 추출하는 추출 시스템 abstract: 소비지에 가깝기 때문에 상정되는 LNG 새틀라이트 기지로부터 아임계 압력으로 공급되는 액화 천연 가스를 사용하여 천연 가스액을 추출하는 시스템을 제공하는 것이다.천연 가스액 추출 시스템은, 소정 압력의 액화 천연 가스가 원료로서 공급되는 제1 탑정부(11)와, 제1 증류부(12)와, 제1 리보일러(131)를 구비하는 제1 탑저부(13)를 갖는 제1 탑(1)과, 제1 콘덴서(211)를 구비하는 제2 탑정부(21)와, 제1 탑저부(13)로부터 도출되는 제1 증류 유체가 그 중간단에 공급되는 제2 증류부(22)와, 제2 리보일러(231)를 구비하는 제2 탑저부(23)를 갖는 제2 탑(2)을 구비한다. claims: 소정 압력의 액화 천연 가스가 원료로서 공급되는 제1 탑정부(11)와, 제1 증류부(12)와, 제1 리보일러(131)를 구비하는 제1 탑저부(13)를 갖는 제1 탑(1)과,제1 콘덴서(211)를 구비하는 제2 탑정부(21)와, 상기 제1 탑저부(13)로부터 도출되는 제1 증류 유체가 그 중간단에 공급되는 제2 증류부(22)와, 제2 리보일러(231)를 구비하는 제2 탑저부(23)를 갖는 제2 탑(2)을 구비하는 천연 가스액 추출 시스템.내부 펌프(502)를 구비하는 LNG 탱크(501)와,상기 LNG 탱크(501)로부터 도출되는 소정 압력의 액화 천연 가스가 원료로서 공급되는 제1 탑정부(11)와, 제1 증류부(12)와, 제1 리보일러(131)를 구비하는 제1 탑저부(13)를 갖는 제1 탑(1)과,제1 콘덴서(211)를 구비하는 제2 탑정부(21)와, 상기 제1 탑저부(13)로부터 도출되는 제1 증류 유체가 그 중간단에 공급되는 제2 증류부(22)와, 제2 리보일러(231)를 구비하는 제2 탑저부(23)를 갖는 제2 탑(2)과,상기 메탄 부화 가스와 상기 에탄 부화 가스를 포함하는 연료 가스와, LNG 탱크(501)로부터 취출된 BOG의 혼합 가스를 승압시키는 컴프레서(503)와,상기 내부 펌프(502)에 의해 보내진 LNG의 전부 또는 그 일부를 승압시키는 승압 장치(505)와,상기 승압 장치(505)에서 승압된 승압 LNG의 일부를 증발시켜 천연 가스로 하는 증발기(506)와,상기 승압 장치(505)에서 승압된 승압 LNG의 일부를 냉열원으로 하여, 랭킨 사이클(60)의 작동 유체를 액화시키는 작동 유체 열교환기(61)와,상기 작동 유체 열교환기(61)에서 액화된 작동 유체를 승압시키는 작동 유체 승압 장치(62)와,작동 유체 승압 장치(62)에서 승압된 작동 유체를 증발시키는 작동 유체 증발기(63)와,상기 작동 유체 증발기(63)에서 증발된 작동 유체를 팽창시시키는 팽창 터빈(64)과,상기 제2 탑저부(23)로부터 회수된 프로판 부화 유체가 도입되는, 상기 작동 유체의 랭킨 사이클(60)의 작동 유체 라인(L60)을 구비하는, 랭킨 사이클을 구비하는 천연 가스액 추출 시스템.내부 펌프(502)를 구비하는 LNG 탱크(501)와,상기 LNG 탱크(501)로부터 도출되는 소정 압력의 액화 천연 가스가 원료로서 공급되는 제1 탑정부(11)와, 제1 증류부(12)와, 제1 리보일러(131)를 구비하는 제1 탑저부(13)를 갖는 제1 탑(1)과,제1 콘덴서(211)를 구비하는 제2 탑정부(21)와, 상기 제1 탑저부(13)로부터 도출되는 제1 증류 유체가 그 중간단에 공급되는 제2 증류(칼럼)부(22)와, 제2 리보일러(231)를 구비하는 제2 탑저부(23)를 갖는 제2 탑(탈에탄탑)(2)과,제2 콘덴서(312)를 구비하는 제3 탑정부(31)와, 상기 제2 탑저부(23)로부터 도출되는 제2 증류 유체가 그 중간단에 공급되는 제3 증류(칼럼)부(32)와, 제3 리보일러(331)를 구비하는 제3 탑저부(33)를 갖는 제3 탑(3)과,상기 메탄 부화 가스와 상기 에탄 부화 가스를 포함하는 연료 가스와, LNG 탱크(501)로부터 취출된 BOG의 혼합 가스를 승압시키는 컴프레서(503)와,상기 LNG 탱크(501)로부터 도출되는 LNG의 전부 또는 그 일부를 승압시키는 승압 장치(505)와,상기 승압 장치(505)에서 승압된 승압 LNG의 일부를 증발시켜 천연 가스로 하는 증발기(506)와,상기 승압 장치(505)에서 승압된 승압 LNG의 일부를 냉열원으로 하여, 랭킨 사이클(60)의 작동 유체를 액화시키는 작동 유체 열교환기(61)와,상기 작동 유체 열교환기(61)에서 액화된 작동 유체를 승압시키는 작동 유체 승압 장치(62)와,작동 유체 승압 장치(62)에서 승압된 작동 유체를 증발시키는 작동 유체 증발기(63)와,상기 작동 유체 증발기(63)에서 증발된 작동 유체를 팽창시시키는 팽창 터빈(64)과,상기 제1 탑정부(11)로부터 회수되는 메탄 부화 가스의 일부, 상기 제2 탑정부(21)로부터 회수되는 에탄 부화 가스의 일부, 상기 제3 탑정부(31)로부터 회수되는 프로판 부화 유체의 일부, 상기 제3 탑저부(33)로부터 회수되는 부탄 부화 유체의 일부 중, 1종 또는 1종 이상의 혼합 유체가 도입되는, 상기 작동 유체의 랭킨 사이클(60)의 작동 유체 라인(L60)을 구비하는 랭킨 사이클을 구비하는 천연 가스액 추출 시스템., Ltext: 임업, prediction: 임업
82/1059 Row 82: application_number: 1020200055124, combined_string: invention_title: 드라이아이스를 이용한 천연물의 추출방법 및 이에 따라 수득된 추출물을 함유하는 조성물 abstract: 본 발명은 드라이아이스를 이용한 천연물의 추출방법 및 이에 따라 수득된 추출물을 함유하는 조성물에 관한 것이다. 본 발명에 따른 추출방법은 천연물로부터 추출되는 활성성분의 양을 현저하게 증가시켜줄 수 있다. 특히, 본 발명에 따른 추출방법이 적용될 수 있는 천연물에는 제한이 없으며, 활성성분 또는 추출물이 나타내는 효과에 따라 화장품, 식품, 의약외품, 의약품 등 다양한 분야에서 활용이 가능하다. claims: 식물, 과일, 광물, 동물, 및 이로부터 생성되는 분비물 및 대사산물 중에서 선택되는 하나 이상인 천연물의 추출방법으로서, 하기 단계를 포함하는 추출방법:a) 천연물에 용매 물을 첨가하는 단계;b) 상기 a) 단계의 생성물에 드라이아이스를 첨가하여 추출하는 단계; 및c) 상기 b) 단계에서 수득된 추출물을 분리하여 여과하는 단계.제1항에 있어서,상기 b) 단계에서 수득된 추출물 또는 상기 c) 단계에서 수득된 여과물을 농축하는 d) 단계를 더 포함하는 것을 특징으로 하는 추출방법.제1항에 따라 수득된 추출물을 포함하는 화장품 조성물.제1항에 따라 수득된 추출물을 포함하는 식품 조성물.제1항에 따라 수득된 추출물을 포함하는 의약외품 조성물.제1항에 따라 수득된 추출물을 포함하는 의약품 조성물., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

83/1059 Row 83: application_number: 1020200052371, combined_string: invention_title: 천연 추출물 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 조성물 abstract: 본 발명은 천연물 기반인 녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 화장료 조성물에 관한 것이다. 본 발명의 조성물은 다양한 원인에 기한 피부의 비정상적 상태(아토피, 염증, 홍반, 산화, 피부 내 세포 독성물질, 수분의 소실, 기미, 가려움, 거칠어짐, 주름 등)를 효과적으로 진정시킬 수 있다. claims: 녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 화장료 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 항염증 또는 아토피 피부염의 개선인 것을 특징으로 하는 피부 진정용 화장료 조성물.제 1 항의 화장료 조성물을 포함하는 마스크팩.녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 식품 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 항염증 또는 아토피 피부염의 개선인 것을 특징으로 하는 피부 진정용 식품 조성물.녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 약제학적 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 항염증 또는 아토피 피부염의 개선인 것을 특징으로 하는 피부 진정용 약제학적 조성물., Ltext: 임업, prediction: 임업
84/1059 Row 84: application_number: 1020200050675, combined_string: invention_title: 백합조개의 패각분말과 천연추출물이 함유된 치약조성물 abstract: 본 발명은 백합조개의 패각분말 1~3 중량%, 쓴쑥 추출물 0.2 중량%, 두송열매 추출물 0.2 중량%, 페퍼민트잎 추출물 0.2 중량%, 참당귀 추출물 0.2 중량%, 어성초 추출물 0.2 중량%, 고본 추출물 0.2 중량%, 인삼 추출물 0.5 중량%, 목향 추출물 0.3 중량%, 황금 추출물 0.2 중량%, 오미자 추출물 0.3 중량%, 캐모마일 추출물 0.5 중량%, 라타니아 추출물 0.7 중량%, 염장된 올리브열매 추출물 0.6 중량%가 함유된 것임을 특징으로 하는 치약조성물을 제공함으로써, 구강 내 탁월한 항균작용에 의해 각종 치과 질환 치료에 우수한 효과를 발휘할 수 있고, 치아 연마세정작용도 동시에 병행하게 하는 효과가 있다. claims: 백합조개의 패각분말 1~3 중량%, 쓴쑥 추출물 0.2 중량%, 두송열매 추출물 0.2 중량%, 페퍼민트잎 추출물 0.2 중량%, 참당귀 추출물 0.2 중량%, 어성초 추출물 0.2 중량%, 고본 추출물 0.2 중량%, 인삼 추출물 0.5 중량%, 목향 추출물 0.3 중량%, 황금 추출물 0.2 중량%, 오미자 추출물 0.3 중량%, 캐모마일 추출물 0.5 중량%, 라타니아 추출물 0.7 중량%, 염장된 올리브열매 추출물 0.6 중량%가 함유된 것임을 특징으로 하는 치약조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

85/1059 Row 85: application_number: 1020200049051, combined_string: invention_title: 피부노화방지 및 피부주름개선용 천연추출물을 함유한 화장품 및 이의 제조방법 abstract: 본 발명은 일정기간 식물성추출물을 발효 피부주름개선 비타민이 풍부한 균주를 원료로 하여 피부 노화방지 및피부 주름 개선용 천연추출물 숙성 발효 조성물 및 이를 이용한 화장품에 관한 것으로서, 좀 더 구체적으로 설명하면, 인공향료, 인공색소, 메틸 파라벤 등의 인공적인 합성 또는 화학성분을 주성분으로 사용하지 않으면서, 부작용을 일으키지 않고 장기간 동안 사용 가능 하면서도, 피부 흡수력이 우수하여 피부 주름개선 및 피부 노화방지력이 우수한 천연 영양성분의 화장료 조성물, 이를 포함하는 화장품에 관한 것이다. claims: 54 ~ 56Hz 클러스터의 전해환원수;잣나무잎 액상 발효 추출물, 편백잎 액상 발효 추출물, 녹차잎 액상 발효 추출물 및 병풀 액상 발효 추출물을포함하는 숙성 발효 추출물; 및감식초 및 벌꿀을 포함하는 보존제;를 포함하는 것을 특징으로 하는 피부노화방지 및 피부주름개선용 천연추출, Ltext: 임업, prediction: 농업
86/1059 Row 86: application_number: 1020200047157, combined_string: invention_title: 천연추출물을 포함하는 피부 미백 및 보습용 화장료 조성물 abstract: 본 발명은 천연추출물을 포함하는 피부 미백 및 보습용 화장료 조성물에 관한 것이다.본 발명에 따른 천연추출물을 포함하는 피부 미백 및 보습용 화장료 조성물은 병풀 추출물, 매생이 추출물, 오레가노 오일, 브링그라즈 오일, 호호바씨 오일, 누에 숙성분말 가공유, 셀레늄 및 옥파우더를 포함한다.상기한 구성에 의해 본 발명에 따른 화장료 조성물은 천연추출물을 유효성분으로 포함함으로써, 피부 미백 및 보습 효과가 있고 피부의 건강을 향상시킬 수 있다. claims: 병풀 추출물, 매생이 추출물, 오레가노 오일, 브링그라즈 오일, 호호바씨 오일, 누에 숙성분말 가공유, 셀레늄 및 옥파우더를 포함하되,상기 병풀 추출물 1 내지 3 중량부, 매생이 추출물 0.1 내지 1.5 중량부, 오레가노 오일 0.1 내지 0.5 중량부, 브링그라즈 오일 0.05 내지 0.15 중량부, 호호바씨 오일 0.05 내지 0.15 중량부, 누에 숙성분말 가공유 0.1 내지 0.5 중량부, 셀레늄 0.01 내지 0.1 중량부 및 옥파우더 0.005 내지 0.015 중량부의 중량 비율로 포함되고,상기 매생이 추출물은, 매생이를 준비한 후 상기 매생이를 15 내지 25℃ 온도의 정제수로 제1 세척하고, 상기 제1 세척된 매생이를 숙성액에 침지시켜 제2 세척하되, 상기 제2 세척은 녹차 잎, 월계수 잎 및 정제수를 0.5:1.5:8의 중량 비율로 혼합하고, 상기 녹차 잎 및 월계수 잎이 혼합된 정제수를 70 내지 75℃의 온도에서 20 내지 60분 동안 가열한 후 녹차 잎 및 월계수 잎을 제거하고 여과하여 여과액을 제조하며, 상기 여과액에 오징어 먹물을 9.5:0.5의 중량비로 혼합하고 10 내지 15℃의 온도에서 3 내지 6시간 동안 숙성시켜 숙성액을 제조하며, 상기 정제수로 세척된 매생이를 상기 숙성액에 침지시킨 후 5 내지 7℃의 온도에서 10 내지 20분 동안 보관하고, 상기 숙성액에 침지된 매생이를 분리한 후 15 내지 20℃ 온도의 정제수로 세척하는 과정으로 진행되며, 상기 제2 세척된 매생이를 45 내지 50℃의 온도에서 20 내지 40시간 동안 보관하여 건조시키고, 상기 건조된 매생이 100 중량부에 대해 진피 발효액 1 내지 5 중량부의 중량 비율로 혼합한 후 8 내지 12℃의 온도에서 20 내지 40시간 동안 보관함으로써 상기 매생이를 숙성 발효시키며, 상기 숙성 발효된 매생이를 -20 내지 -30℃의 온도에서 동결 건조하고, 상기 동결 건조된 매생이를 분쇄하여 매생이 분말을 제조한 후, 상기 매생이 분말 100 중량부에 대해 정제수 2,000 내지 2,500 중량부의 중량 비율로 혼합하고, 90 내지 95℃의 온도에서 5 내지 10시간 동안 열수 추출하여 매생이 열수 추출물을 제조하며, 상기 매생이 열수 추출물을 -40 내지 -50℃의 온도에서 동결 건조하여 동결 건조된 매생이 열수 추출물을 제조하고, 상기 동결 건조된 매생이 열수 추출물을 환류 추출하는 과정을 거쳐 제조된 것을 특징으로 하는 천연추출물을 포함하는 피부 미백 및 보습용 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

87/1059 Row 87: application_number: 1020200044781, combined_string: invention_title: 천연물 추출수를 포함한 세탁 세제, 섬유 유연제, 주방 세제, 샴푸, 바디 클렌져 등 세정용 조성물 및 그 제조 방법 abstract: 천연물 추출수를 포함한 세정용 조성물 및 그 제조 방법이 제공된다. claims: 천연물 추출수를 포함한 세정용 조성물의 제조 방법으로서,붉나무, 오배자, 무환자 및 노니 중에서 선택된 1종 이상의 천연물을 열수 추출하여 천연물 추출수를 제조하는 단계를 포함한, 세정용 조성물의 제조 방법.천연물 추출수를 포함하고,상기 천연물 추출수는 붉나무, 오배자, 무환자 및 노니 중에서 선택된 1종 이상의 천연물로부터 유래된, 세정용 조성물., Ltext: 임업, prediction: 임업
88/1059 Row 88: application_number: 1020210053129, combined_string: invention_title: 편백향 확산 기능을 강화한 편백재의 제조방법 abstract: 본 발명에 따른 편백향 확산 기능을 강화한 편백재의 제조방법은,건조 처리된 편백나무를 절단하여 편백 목재를 수득하는, 절단 단계; 상기 편백 목재를 재단하고 세공하여 편백재를 제작하는, 편백재 제작 단계; 제작된 상기 편백재의 표면을 가공 처리하여 거칠기를 부여하는, 표면 가공 처리 단계; 가공 처리된 상기 편백재의 표면을 아크릴계 수지를 포함하는 기능성 코팅제로 코팅 처리하는, 코팅 단계;를 포함하는 것을 특징으로 한다. claims: 편백향 확산 기능을 강화한 편백재의 제조방법으로서,건조 처리된 편백나무를 절단하여 편백 목재를 수득하는, 절단 단계;상기 편백 목재를 재단하고 세공하여 편백재를 제작하는, 편백재 제작 단계;제작된 상기 편백재의 표면을 가공 처리하여 거칠기를 부여하는, 표면 가공 처리 단계;가공 처리된 상기 편백재의 표면에 아크릴계 수지를 포함하는 기능성 코팅제를 분사하는, 코팅 단계;를 포함하되,상기 기능성 코팅제는,우레탄 아크릴레이트 20 내지 50 중량부, 폴리옥시에틸렌 솔비탄 지방산 에스테르(polyoxyethylene sorbitan fatty acid ester) 10 내지 30 중량부, 메틸에틸케톤 20 내지 40 중량부, 폴리에틸렌글라이콜(Polyethylene glycol) 및 2-하이드록시-2-메틸프로피오페논(2-Hydroxy-2-methylpropiophenone)을 포함하는 표면 개질제 1 내지 10 중량부를 포함하고,상기 표면 개질제는,알파-피넨(α-pinene) 30 내지 50 중량부, 세스퀴테르펜 10 내지 30 중량부, 에탄올 20 내지 40 중량부를 혼합하여 제 1 혼합액을 제조하는 단계;상기 제 1 혼합액 60 내지 90 중량부와, 실리카 파우더 15 내지 30 중량부, n-부틸아크릴레이트(n-butyl acrylate) 5 내지 10 중량부를 혼합하여 제 2 혼합액을 제조하는 단계;상기 제 2 혼합액 70 내지 85 중량부와, 폴리에틸렌글라이콜(Polyethylene glycol) 10 내지 25 중량부 및, 1-도데카놀 5 내지 10 중량부를 혼합하여 제 3 혼합액을 제조하는 단계;상기 제 3 혼합액 90 내지 95 중량부와, 2-하이드록시-2-메틸프로피오페논(2-Hydroxy-2-methylpropiophenone) 1 내지 10 중량부 및, 테트라에틸암모늄 하이드록사이드(tetraethylammonium hydroxide) 1 내지 3 중량부를 혼합하여 표면 개질제를 완성하는 단계;를 통해 제조되는 것을 특징으로 하는, 편백재의 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

89/1059 Row 89: application_number: 1020210047469, combined_string: invention_title: 동충하초의 대량 증식 종균 획득 방법과 이를 이용한 대량 배양방법 abstract: 동충하초의 대량 증식 종균 획득 방법과 이를 이용한 대량 배양방법이 개시된다. 동충하초의 대량 증식 종균 획득 방법은 a) 다양한 기주로부터 동충하초 종균을 자연 채취하여 소독하고 포자분리 검색단계; b) 검색된 종균을 포자분리를 위한 아가(Aga) 사면 배지에 배양하는 단계; c) 포자 증식을 하기 위한 고체배지, 액상 영양원 제조 단계; d) 용기에 선발 영양원을 충진한 후 고압멸균하고, 멸균 제조된 용기 안의 영양원에 액상 균사를 증식하는 단계; e) 액상 영양원 용기에서 균사를 대량 증식하는 단계; 및 f) 균사 대량 증식 영양원 용기를 멸균한 후 하온시키는 단계로 구성됨을 특징으로 한다.상기와 같이 구성되는 본 발명의 동충하초의 대량 증식 종균 획득 방법과 이를 이용한 대량 배양방법은 야생 동충하초 채취에서부터 얻어진 포자분리 대량 증식 종균 획득 방법과, 이를 이용하여 특정한 방법에 의해 동충하초의 대량 재배 생산, 생산된 동충하초의 가공 및 가공된 동충하초 완성제품을 획득하는 방법을 제공하여, 동충하초를 배양하여 생육재배 수확하는 기간 동안 멸균된 상태로 유지 수확하여 인체에 해로운 오염원을 막을 수 있으며, 인위적인 수분 공급 과정을 생략함으로써 노동력 절감과 청결한 순수 동충하초 상품을 대량으로 수확할 수 있게 하여 종래의 문제점을 해결하면서 인류의 건강에 이바지할 수 있는 발명을 제공한다. claims: a) 소독한 다양한 기주로부터 동충하초 종균을 채취하여 포자를 분리하기 위한 종균을 검색하는 단계; b) 검색된 종균을 포자분리를 위한 아가(Aga) 사면 배지에 배양하는 단계; c) 포자 증식을 하기 위한 고체배지, 액상 영양원 제조 단계; d) 용기에 선발 영양원을 충진한 후 고압멸균하고, 멸균 제조된 용기 안의 영양원에 액상 균사를 증식하는 단계로, 본 단계는 액상 균사를 121℃, 1.5기압에서 20분간 처리하고 25℃로 냉각한 뒤에 여기에 동충하초의 원균을 접종하여 25℃ 배양실에서 7일간 배양하고, 그 다음 여기에 액상 종균을 15 내지 30ml를 접종하여, 25±1℃의 온도로 유지된 배양실에서 7일간 균사 배양하는 단계; e) 상기 단계에 의해 종균 접종 후 균사 배양된 동충하초 배지를 실내온도 17℃ 내지 24℃±1℃의 균상 발아실로 옮겨 45일간 용기 속의 자실체 생육 (수확)시까지 습도조절을 위해 물을 주지 않고 온도와 빛의 조절만으로 생육 용기 내에서 온도 충격에 인하여 결로 수 (水)가 발생하여 자실체 생육에 영양과 수분이 원활하게 공급하여 수확시까지 뚜껑을 열지 않고 증식하는 단계에 의해 동충하초의 대량 증식 종균을 획득한 후, 추가로; f) 균사 대량 증식 영양원용 용기를 멸균한 후 하온시키는 단계;g) 상기 멸균된 용기 안의 영양원에, 잘 소독된 멸균 크린벤치 내에서 우량 포자를 대량 증식한 종균을 접종하는 단계; h) 생육 배지 용기 안에 영양원을 충진하고 고압멸균 후 하온시키는 단계;i) 상기 멸균 하온된 용기 안의 영양 배지에, 잘 소독된 크린벤치 내에서 상기 g) 단계의 우량 대량 증식 종균을 접종한 후에, 동충하초의 대량배양을 위한 배지를 조제하기 위한 단계로서 곡물인 현미, 율무쌀, 보리, 수수, 찹쌀, 백미, 밀, 조 중에서 택일한 1종 이상의 곡물을 발아시키고 임의로 기주 곤충의 4령 유충에서 종영 유충을 깨끗하게 세척 후 채반에 건져 수분을 제거하고 솥에 넣고 100℃에 쪄서 수증기를 날려 버리고 건조기에 넣어 완전히 건조하여 자연에서의 기주곤충 동충하초의 성분을 그대로 유지되게 한 다음, 상기 곡물 20~50g: 상기 기주곤충 분말 5~10g; 게르마늄과 셀레늄 각 0.2g 비율로 혼합한 혼합물을 용기 안에 넣고, 상기 용기에 물 60ml 내지 70ml에 펩타이드를 물 중량 대비 10 내지 50 중량%로 혼합한 혼합물을 생육 병 용기에 충진하는 단계;j) 상기 우량 종균 접종 영양 배지를 22 내지 24℃의 항온실에 옮겨서 45일간 빛과, 온도 관리로 생육하는 단계; 및k) 상기 단계에서 재배된 동충하초를 무균실에서 자실체와 배지를 분리 균일하게 수확하는 단계를 포함함을 특징으로 하는 동충하초의 대량 증식 종균 획득 방법을 이용한 대량 배양방법. 청구항 1 및 2 중 어느 한 항에 따라 제조된 동충하초를 포함하는 것을 특징으로 하는 식품., Ltext: 임업, prediction: 임업
90/1059 Row 90: application_number: 1020210006694, combined_string: invention_title: 수목 관리 장치 및 시스템 abstract: 본 발명은 수목 관리 장치 및 시스템에 관한 것으로, 더욱 상세하게는 수목을 안정적으로 지지하고, 유수를 수목에 공급하여 수목을 효율적으로 관리할 수 있는 수목 관리 장치 및 시스템에 관한 것이다. claims: 수목(1)을 감싸도록 주변에 설치되어 수목(1)을 지지하고, 유수를 집수하여 수목(1)에 수분을 공급하며, 수목(1)의 토양수분을 측정하는 수목 관리 장치(100)에 있어서,상기 수목 관리 장치(100)는,서로 마주보게 설치될 경우 `ㅁ` 형상을 갖는 제1금형(110) 및 제2금형(120);을 포함하되,상기 제1금형(110) 및 제2금형(120)은,`ㄷ` 형상을 갖는 몸체부(111, 121);상기 몸체부(111, 121)의 수목(1) 측에 `ㄷ` 형상으로 형성되어 유수를 유입시키는 입수부(112, 122);상기 입수부(112, 122)를 통해 유입되는 유수를 저장하는 저수부(113, 123);상기 입수부(112, 122)에 적어도 하나 이상 형성되어 상기 저수부(113, 123)에 저장된 유수를 펌프모터(M)를 통해 수목으로 분사해주는 물분사부(114, 124);상기 몸체부(111, 121)의 상단 외주면에 형성되는 조명부(115, 125);상기 조명부(115, 125)의 측면에 형성되어 전력을 생산하는 쏠라셀모듈(116, 126);상기 쏠라셀모듈(116, 126)로부터 생성된 전기가 저장되는 배터리부(117, 127);상기 몸체부(111, 121)의 상단에 버튼형태로 설치되는 긴급구조부(B); 상기 몸체부(111, 121)의 모서리 일측에 버튼형태로 설치되어 장치를 ON/OFF 할 수 있는 전원부(119, 129);상기 몸체부(111, 121)의 모서리 타측에 형성되어 경고음을 발생시키는 알람부(A); 및상기 물분사부(114, 124), 조명부(115, 125) 및 알람부(A)를 제어하는 제어부(118, 128);를 포함하는 것을 특징으로 하는 수목 관리 장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

91/1059 Row 91: application_number: 1020200156857, combined_string: invention_title: 수정조성물을 이용한 체리 꽃 수정 방법 및 그와 같이 수정된 체리 열매 abstract: 본 발명은 현저하게 낮은 국내 체리 결실률을 탁월하게 증진시키고, 체리의 품질을 향상시키며, 계획적으로 생산량을 조절할 수 있는 수정조성물을 이용한 체리 꽃 수정 방법에 관한 것으로, 더욱 상세하게는 3 내지 5년생 이상 묘목의 체리 꽃이 50 내지 100% 개화한 시기에 수정조성물을 2 내지 3일 간격으로 1 내지 3회 분무살포하는 방법으로 체리를 수정한다. 상기 수정 조성물은 질소화합물 7 내지 8 중량부, 수용성인산 2 내지 3 중량부, 수용성칼륨 4 내지 5 중량부, 수용성붕소 0.05 내지 0.2 중량부, 식용알콜 10 내지 15 중량부, 물 100 중량부 및 정제화분은 0.5 내지 1.5 중량부를 혼합하여 제조한다. claims: 수정조성물을 이용한 체리 꽃 수정 방법에 있어서, 상기 수정조성물을 이용한 체리 꽃 수정 방법은 3 내지 5년생 묘목의 꽃이 50 내지 100% 개화한 시기에 수정조성물을 2 내지 3일 간격으로 1 내지 3회 분무살포하며, 상기 수정조성물을 개화한 체리나무의 꽃에 분무살포할 때 수정조성물은 470 내지 520배의 물에 희석하여 분무살포하되,상기 수정조성물은 물 100중량부에 질소화합물 7 내지 8 중량부, 수용성인산 2 내지 3 중량부, 수용성칼륨 4 내지 5 중량부, 수용성붕소 0.05 내지 0.2 중량부, 식용알콜 10 내지 15 중량부를 혼합하여 조성물용액을 제조하고, 상기 조성물용액에 정제화분은 0.5 내지 1.5 중량부를 혼합하여 제조하며, 체리 결실율을 향상시키기 위하여 상기 정제화분을 혼합하는 단계에서 정제화분이 조성물용액에 충분히 희석될 수 있도록 20 내지 30분 동안 저속으로 교반시켜 수정조성물을 제조하며,체리 꽃 수정을 촉진하기 위하여 상기 수정조성물의 조성물용액에 미량원소로 수용성 아연(Zn), 수용성 구리(Cu), 수용성 망간(Mn), 수용성 몰리브덴(Mo) 또는 수용성 철(Fe) 성분을 각각 또는 하나 이상의 성분을 0.05 ~1.5중량부 더 혼합하는 것을 특징으로 하는 수정조성물을 이용한 체리 꽃 수정 방법., Ltext: 임업, prediction: 임업
92/1059 Row 92: application_number: 1020200135185, combined_string: invention_title: 조형목을 단기간 내에 대량 제조하는 방법 abstract: 본 발명은 조형목을 단기간 내에 대량 제조하는 방법에 관한 것으로, (S1) 묘목 단계의 수목을 철사를 이용하여 기본 수형을 잡는 단계; (S2) 수목의 한 가지에서 희생지를 선택하고 희생지 외에 나머지 가지들은 전지시키는 단계; (S3) 수목의 성장을 유지시키면서 상기 단계 (S2)에서와 동일하게 수목의 나머지 가지들에서 희생지를 선택하고 희생지 외에 나머지 가지들은 전지시키는 단계; (S4) 수목의 성장을 유지시키면서 수형을 만들어 가면서 원하는 수고까지 생장시키는 단계; (S5) 수목 가지의 서열을 정하여 원하는 굴곡으로 유도하는 단계; 및 (S6) 수목 가지를 원하는 생장으로 높인 후 수목 출하 직전에 희생지를 절지하는 단계를 포함하는 본 발명에 따른 조형목의 제조방법은 조형목을 기본 재목을 가지고 출하하던 기존 방식과 달리 묘목부터 시작하기 때문에 기본 재목 수급이 용이하고 낮은 단가의 묘목으로도 충분히 고품질의 조형목 및 가로수를 공급할 수 있어 많은 시간과 인건비를 절감할 수 있을 뿐만 아니라 대량 생산이 가능하다. 또한, 기존의 고가의 조형목을 가로수로 사용하기에 부적절하였던 점을 보완하여 보다 외관이 화려한 조형목을 낮은 단가로 가로수에 사용할 수 있게 되는 장점을 가진다. 따라서, 현재 수목의 가치를 높게 평가하고 관심이 높아지고 있는 시점에서 시간의 단축과 비용절감으로 인해 대량 생산을 가능하게 하고 고품질의 수목을 상대적으로 낮은 단가에 많이 식재할 수 있다. claims: (S1) 묘목 단계의 수목을 철사를 이용하여 기본 수형을 잡는 단계;(S2) 수목의 한 가지에서 희생지를 선택하고 희생지 외에 나머지 가지들은 전지시키는 단계;(S3) 수목의 성장을 유지시키면서 상기 단계 (S2)에서와 동일하게 수목의 나머지 가지들에서 희생지를 선택하고 희생지 외에 나머지 가지들은 전지시키는 단계;(S4) 수목의 성장을 유지시키면서 수형을 만들어 가면서 원하는 수고까지 생장시키는 단계;(S5) 상술한 단계에서 전지나 절지되지 않고 남아 있는 수목 가지의 서열을 정하여 원하는 굴곡으로 유도하는 단계; 및(S6) 원하는 형태를 갖는 수목 가지를 원하는 만큼 생장시킨 후 수목 출하 직전에 희생지를 절지하는 단계를 포함하여 조형목을 생산하되,상기 조형목은 가로수이며,상기 단계 (S5) 이후 2m 이내의 가지는 절지하여 지하고를 높이는 단계를 추가로 포함하는 것을 특징으로 하는 조형목의 대량 생산방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

93/1059 Row 93: application_number: 1020200125759, combined_string: invention_title: 컨테이너를 이용한 조경수 생산방법 abstract: 본 발명은 컨테이너를 이용한 조경수 생산방법에 관한 것으로서, 더욱 상세하게는 수목의 강한 뿌리시스템을 창출하는 특수 컨테이너를 모든 단계에서 사용함으로써, 보다 뿌리 발달이 향상되어 현장의 토양에 잘 적응하기 때문에 활착률과 생장률이 향상되고, 생산방법에 적용된 컨테이너는 수목의 이식 성공률을 높이기 위하여 단순한 용기가 아닌 세근발달을 촉진시키는 특수 컨테이너이고, 각각의 단계는 종전의 세근발달을 기반으로 다음 단계를 준비하며, 세근발달은 보다 큰 용적의 컨테이너에서 확장되어 수분ㆍ양분의 흡수, 생장률, 생존률 등의 효율성을 증대시키는 특징이 있다. claims: 조경수를 생산하는 방법에 있어서,(1) 묘목을 4L 용적용 제 1 컨테이너에 이식하여 생장시키는 단계;(2) 상기 (1) 단계에서 생장시킨 수목을 12L 용적용 제 2 컨테이너에 이식하여 중간 수목으로 생장시키는 단계;(3) 상기 (2) 단계에서 생장시킨 중간 수목을 50L 용적용 제 3 컨테이너에 이식하여 소형 수목을 생산하는 단계;를 포함하고,상기 4L 용적용 제 1 컨테이너와 12L 용적용 제 2 컨테이너는 지상재배 방식으로써 컨테이너와 컨테이너의 간격을 두지 않는 조밀배치방법과 수목의 수관을 고려하여 소정 간격을 이격하여 배치하는 이격배치방법을 사용하는데, 상기 조밀배치방법 또는 이격배치방법에 의해 배치된 다수개의 컨테이너를 전도방지용 연결 고정구를 통해 고정하고,상기 전도방지용 연결 고정구는 하측에 컨테이너와 컨테이너 또는 컨테이너와 와이어를 상호 연결시켜 고정시키는 2개의 고정홈이 형성되고, 상측에는 수평으로 파이프가 결합되도록 결합홈이 형성되고,상기 2개의 고정홈 사이에는 컨테이너 또는 와이어가 고정홈에서 이탈되지 않도록 압착돌기가 고정홈 내측으로 돌출 형성되고, 상기 압착돌기는 끝단부가 상측으로 라운드지게 형성되어 컨테이너 또는 와이어가 고정홈에 용이하게 삽입시키는 동시에 삽입 후에는 쉽게 이탈되지 않는 것을 특징으로 하는 컨테이너를 이용한 조경수 생산방법., Ltext: 임업, prediction: 임업
94/1059 Row 94: application_number: 1020200117100, combined_string: invention_title: 산삼배양근의 제조방법 abstract: 본 발명은 본 발명은 산삼배양근의 제조방법에 관한 것이며, 천연 산삼을 절단하여 천연산삼 조각을 준비하는 단계(S100); 상기 천연산삼 조각을 산삼배양용 배지에 접종하고 1차 배양하여 산삼 세포괴로 성장시키는 단계(S200); 상기 산삼 세포괴를 더욱 성장시켜 부정근을 유도하는 단계(S300); 상기 부정근 중에서 형질이 우수한 뿌리를 선별하고 이를 2차 배양하여 산삼세근을 얻는 단계(S400); 상기 산삼세근을 생물반응기에 넣고 3차 배양시키는 단계(S500); 및 생물반응기에서 자란 산삼세근을 대형 배양탱크에 넣고 4차 배양하는 단계(S600);를 포함하며, 이는 제조되는 산삼배양근에 함유되는 아연 (Zn), 칼슘 (Ca) 및 황(S)의 비율을 효과적으로 향상시킬 수 있음과 동시에 높은 수율로 천연산삼과 성분이 동일한 배양산삼을 수득할 수 있는 장점을 갖는다. claims: 천연 산삼을 절단하여 천연산삼 조각을 준비하는 단계(S100);상기 천연산삼 조각을 산삼배양용 배지에 접종하고 1차 배양하여 산삼 세포괴로 성장시키는 단계(S200);상기 산삼 세포괴를 더욱 성장시켜 부정근을 유도하는 단계(S300);상기 부정근 중에서 형질이 우수한 뿌리를 선별하고 이를 2차 배양하여 산삼세근을 얻는 단계(S400);상기 산삼세근을 생물반응기에 넣고 3차 배양시키는 단계(S500); 및생물반응기에서 자란 산삼세근을 대형 배양탱크에 넣고 4차 배양하는 단계(S600);를 포함하며,상기 1차 배양 내지 4차 배양은 각각질산암모늄 (NH4NO3, ammonium nitrate), 질산칼슘사수화물 ([CaNO3]2·4H20, calcium nitrate tetrahydrate), 제1인산칼륨 (KH2PO4, potassium phosphate monobasic), 황산칼륨 (K2SO4, potassium sulfate), 황산마그네슘7수화물 (MgSO4·7H2O, magnesium sulfate heptahydrate), 무수염화칼슘 (CaCl2, calcium chloride anhydrous), 붕산 (H3BO3, boric acid), 황산아연7수화물 (ZnSO4·7H2O, zinc sulfate heptahydrate), 몰리브덴산나트륨2수화물 (Na2Mo04·2H20, sodium molybdate dihydrate), 황산구리오수염 (CuS04·5H2O, copper(I) sulfate pentahydrate), 나트륨에데트산제2철 (EDTA ferric sodium salt trihydrate), 3-인돌부틸산 (IBA(C12H13NO2), 3-indolebutyric acid), 수산화칼륨 (KOH), 이노시톨 (inositol), 피리독신염산염 (C8H11NO3HCl, pyridoxine hydrochloride), 티아민염산염 (thiamine hydrochloride), 아연(Zn) 및 칼슘(Ca)을 포함하는 산삼배양용 액상 배지를 이용하여 수행되는 것을 특징으로 하는 산삼배양근 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

95/1059 Row 95: application_number: 1020200115667, combined_string: invention_title: 편백 오일의 제조방법 및 이를 함유하는 항균 조성물 abstract: 본 발명은 편백 오일의 제조방법, 이를 함유하는 항균 조성물, 화장료 조성물 및 의약외품 조성물에 관한 것으로, 상세하게는 편백나무 심재를 원료로 하며 분쇄 단계; 전처리 단계; 추출 단계; 수증기 배출 단계; 냉각 단계; 분리 단계; 및 숙성단계를 포함하여 수행됨으로써 항균 효과가 우수한 고품질의 편백나무 오일을 높은 생산성으로 생산할 수 있는, 편백 오일의 제조방법 및 그를 이용하여 제조되는 항균 조성물, 화장료 조성물 및 의약외품 조성물에 관한 것이다. claims: 벌목후 24시간이 지나지 않은 수령 30년 이상 편백나무 유래 심재를 분쇄하여 분쇄물을 얻는 단계;상기 분쇄물을 용기에 투입하는 단계;상기 용기에 100 내지 200℃ 온도의 건증기를 10 내지 30분 공급하는 전처리 단계;상기 용기에 150 내지 230℃ 온도의 증기를 1 내지 2kgf/cm2의 압력조건으로 1 내지 3시간 동안 공급하는 추출 단계;상기 용기 내부온도가 100 내지 120℃이고 내부압력이 1 내지 1.5kgf/cm2이 되면 수증기를 배출시키는 수증기 배출 단계;상기 용기에서 배출되는 수증기를 2차에 걸쳐 냉각하여 응축시키는 냉각 단계;상기 냉각 단계에서 얻어지는 응축수에서 편백수 및 편백오일을 분리하는 분리 단계; 및분리된 편백오일을 10 내지 15 ℃ 온도에서 7 내지 90일간 숙성시키는 숙성 단계;를 포함하되,상기 분리 단계는 편백수와 편백오일의 경계면에서 먼 하층의 편백수 및 상층의 편백오일을 먼저 분리하는 제 1단계; 상기 경계면 부근의 편백수 및 편백오일을 탈크에 흘려보내 오일 성분을 탈크에 고정시키는 제 2단계; 상기 탈크에 에테르를 처리하여 오일 성분을 용해시키는 제 3단계; 및 상기 에테르를 증발시켜 오일 성분만을 남기는 제 4단계를 포함하고,상기 숙성 단계에서 숙성된 편백오일은 숙성된 편백오일 총 100중량%에 대하여 알파피넨(α-pinene) 10 내지 15중량% 및 보닐아세테이트(bornyl acetate) 5 내지 15중량%으로 함유하는, 편백오일 제조방법.청구항 1 또는 4의 제조방법으로 제조되는 편백오일을 유효성분으로 함유하는, 항균용 조성물., Ltext: 임업, prediction: 농업
96/1059 Row 96: application_number: 1020200097400, combined_string: invention_title: 생태복원용 식생매트 및 이를 이용한 시공방법 abstract: 본 발명은 본 발명은 하천 및 산림의 훼손지의 식생기반을 형성하기 위한 식생매트에 관한 것으로, 복원 대상지별 특성에 따라 식생매트의 구조 및 식생배합을 구분하여 적용할 수 있도록 해, 다양한 식물을 사용하여 복원사업의 용도 및 목표에 따라 조기피복 및 장기적인 용도의 생태복원을 구현할 수 있도록 한다. claims: 복원사업의 대상이 되는 적용대상지를 하천형(ERS), 도로형(ERR), 산지형(ERF) 중 어느 하나로 구분하여, 복원목표와 식생완성 목표시기 및 식생배합비율을 결정하는 1단계; 상기 1단계 이후, 상기 적용대상지의 현장여건을 고려하여, 식생매트의 설계 구성을 종자부착형 또는 완성형 중 어느 하나로 결정하는 2단계; 상기 1단계 및 2단계에 따른 결정조건에 부합하는 식생매트를 다층구조로 적층하여 제작하는 3단계; 상기 적용대상지의 하부에 유기물재료로 형성되는 근계 유도형 식생블럭을 매립하고, 상기 식생블럭을 매립한 대상지의 상부 토양표면에 식생매트를 배치하는 4단계;를 포함하며,상기 1단계는, 상기 하천형(ERS)은 복원목표를 조기녹화로 하고, 식생배합 비율은 초본 : 관목 : 교목 = 100 : 0 : 0으로 배합하고, 상기 도로형(ERR)은 복원목표를 중기녹화로 하고, 초본 : 관목 : 교목 = 50~70 : 30~50 : 0으로 배합하며,상기 산지형(ERF)은 복원목표를 장기녹화로 하고, 초본 : 관목 : 교목 = 10~30 : 40~60 : 20~40으로 배합하는 단계인, 생태복원용 식생매트를 이용한 시공방법.청구항 1의 시공방법에 적용되는, 생태복원용 식생매트., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

97/1059 Row 97: application_number: 1020200089274, combined_string: invention_title: 대나무를 이용한 임산물 및 수목 생장촉진 구조를 갖는 유공관, 이의 제조 방법 및 이의 시공 방법 abstract: 본 발명은 임산물 및 수목 식재시 뿌리 주위를 따라 설치되어 물과 영양분을 공급함으로써 환경보호와 함께 통기성 및 관수성을 향상시킬 수 있도록 구현한 대나무를 이용한 임산물 및 수목 생장촉진 구조를 갖는 유공관, 이의 제조 방법 및 이의 시공 방법에 관한 것으로, 대나무를 원형 파이프 형태로 가공하여 제작되며, 둘레를 따라 다수 개의 관통홀이 일정한 간격으로 열을 지어 타공 형성되며, 식재된 임산물 및 수목의 생장촉진을 위해 토양에 삽입된 뒤 내부 공간으로 공급되는 물을 상기 관통홀을 통해 토양으로 배출하는 기둥부; 상기 기둥부의 외주면을 덮는 커버부; 및 식재된 임산물 및 수목의 생장촉진을 위한 영양제 성분이 내측에 수용되며, 상기 커버부의 외측에 설치되는 영양 공급부;을 포함한다. claims: 대나무를 원형 파이프 형태로 가공하여 제작되며, 물이 토양으로 배출되게 상기 대나무의 둘레를 따라 다수 개의 관통홀이 일정한 간격으로 열을 지어 타공 형성되고, 상부는 지상방향으로 일정 높이로 돌출되게 형성하며 하부는 경사면으로 절개된 기둥부;상기 기둥부는 외측 표면을 강화시키고 내구성을 향상시킬 수 있도록 150℃ 내지 200℃의 온도로 1차 열처리된 후, 표면강화를 위한 광택작업이 70℃ 내지 90℃로 2차로 이루어지며 천연 방부, 방청 및 방수 기능이 있는 도료를 이용하여 3차 작업이 이루어지고,상기 기둥부의 상부 입구를 덮는 덮개부;상기 덮개부는 덮개 본체를 개폐하는 대나무 또는 목재재질로 된 보강판, 상기 보강판에 형성된 다수 개의 배출홀, 상기 덮개 본체와 상기 보강판을 체결하는 체결수단을 포함하며, 상기 기둥부의 외주면을 하부 방향으로 덮는 생분해성 부직포인 PLA(Poly Lactic Acid), 코코넛 섬유, 화장지, 마 또는 광목 무명천 중 어느 하나의 재질로 이루어진 커버부;식재된 임산물 및 수목의 생장촉진을 위한 영양제 성분이 내측에 수용되며 상기 커버부의 외측에 설치하고, 영양제 성분이 분리되어 수용되기 위한 독립된 공간을 열을 지어 구비하는 줄(wire) 형태로 형성된 영양 공급부; 및 상기 기둥부 내부에 전등을 더 포함하는, 대나무를 이용한 임산물 및 수목 생장촉진 구조를 갖는 유공관., Ltext: 임업, prediction: 임업
98/1059 Row 98: application_number: 1020200083993, combined_string: invention_title: 스마트 산림재해대응 상황관제차량 abstract: 본 발명은 스마트 산림재해대응 상황관제차량에 관한 것으로, 드론을 현장까지 운반하면서 충전을 할 수도 있고, 산불, 산사대, 산림병해충 등을 비롯한 산림의 각종 재해상황을 모니터링할 수 있는 스마트 산림재해대응 상황관제차량에 관한 것으로, 더욱 상세히는 드론과 연계한 산불지휘차량을 현장에서 운용하고, 드론으로 촬영된 산불진화영상 등을 실시간으로 확인하면서 소화작전이나 언론 브리핑 등을 실시할 수 있도록 한 것인바, 상부에 드론이 적재되고 레일을 따라 차량의 후방도어 외측으로 슬라이드방식으로 인출가능하게 설치되는 드론 적재대(100)와; 상기 적재대 하부의 하부 수납공간(200)과; 상기 적재대 좌측 또는 우측 공간에 형성되는 모니터 수납공간(300)과; 상기 모니터 수납공간에 수납되며 레일을 따라 모니터 수납공간의 외부로 인출되는 모니터(400)와; 차량의 2열 위치에 설치되는 PC용 데스크(500)와; 상기 PC용 데스크에 설치되는 워크스테이션(600)과; 상기 모니터(400)와 워크스테이션(600)의 구동 및 드론의 충전을 위한 전원부(700);를 포함하여 이루어진다. claims: 상부에 드론이 적재되고 레일을 따라 차량의 후방도어 외측으로 슬라이드방식으로 인출가능하게 설치되는 드론 적재대(100)와; 상기 적재대 하부의 하부 수납공간(200)과; 상기 드론 적재대 좌측 또는 우측 공간에 형성되는 모니터 수납공간(300)과; 상기 모니터 수납공간에 수납되며 레일을 따라 모니터 수납공간의 외부로 인출되는 모니터(400)와; 차량의 2열 위치에 설치되는 PC용 데스크(500)와; 상기 PC용 데스크에 설치되는 워크스테이션(600)과; 상기 모니터(400)와 워크스테이션(600)의 구동 및 드론의 충전을 위한 전원부(700);를 포함하여 이루어지며,상기 모니터 수납공간(300)에는 내부에 대형 모니터400)가 수납되고 외부로 인출하여 현장에서 상황브리핑이나 교육에 사용되며, 상기 모니터 수납공간(300)은 차량의 내부공간 일측에 형성되고, 측벽에 부착된 2중 레일(R)에 의해 중량이 무거운 모니터(400)를 안정적으로 지지하면서도 외부로 인출이 가능하고, 상기 모니터(400)는 외부로 인출된 상태에서 후방의 힌지(H)에 의해 수평회동되어 차량의 후방을 향하는 것을 특징으로 하는 스마트 산림재해대응 상황관제차량., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

99/1059 Row 99: application_number: 1020200074403, combined_string: invention_title: 광질 조절에 의한 뿌리 생육이 증진된 차나무 기내배양묘의 배양방법 abstract: 본 발명은 광질 조절에 의한 뿌리 생육이 증진된 차나무 기내배양묘의 배양방법에 관한 것으로, 기내(in vitro)에서, 차나무 유묘에 적색광, 청색광 및 백색광이 혼합된 LED(Light-emitting diode) 인공광원을 조사(irradiation)하며 배양하는 단계를 포함하는, 뿌리 생육이 증진된 차나무(Camellia sinensis L.) 기내배양묘의 재배방법에 관한 것이다. claims: (a) 종피를 제거한 차나무(Camellia sinensis L.) 종자를 멸균하는 단계;(b) 상기 (a) 단계에서 멸균한 차나무 종자로부터 유근을 적출하는 단계;(c) 상기 (b) 단계에서 적출한 유근을 기내(in vitro)에서 배지에 치상하여 신초를 유도하고 1.5~2.5주간 배양하여 차나무 유묘를 생장시키는 단계; 및(d) 상기 (c) 단계의 차나무 유묘에 적색광, 청색광 및 백색광이 동일한 광량비율로 혼합되어 이루어진 LED 인공광원을 조사하며 40~50일 동안 재배하는 단계;를 포함하는 것인, 뿌리 수 및 뿌리 길이가 증진된 차나무 기내배양묘의 재배방법.제1항의 방법에 의해 재배된, 뿌리 수 및 뿌리 길이가 증진된 차나무(Camellia sinensis L.) 기내배양묘., Ltext: 임업, prediction: 임업
100/1059 Row 100: application_number: 1020200066300, combined_string: invention_title: 인삼재배용 보온덮개 겸용 차광막 및 그 제조방법 abstract: 본 발명은 인삼재배용 보온덮개 겸용 차광막 및 그 제조방법에 관한 것으로, 알루미늄 호일층(10)과; 상기 알루미늄 호일층(10)의 상하 양면에 도포되는 접착제층(20, 70)과; 상기 접착제층(20) 상에 접착되는 폴리에스터 필름층(30)과; 상기 폴리에스터 필름층(30) 상에 도포되는 접착제층(40)과; 상기 접착제층(40) 상에 T다이 압출작업으로 샌드위치 방식으로 접착되는 폴리에틸렌 압출코팅층(50) 및 자외선(UV) 차단 폴리에틸렌 필름층(60) 및; 상기 접착제층(70) 상에 T다이 압출작업으로 샌드위치 방식으로 접착되는 폴리에틸렌 압출코팅층(80) 및 폴리에틸렌 마대지층(90)으로 구성되어 야간의 보온덮개 효율 및 주간의 차광 효율을 동시에 탁월하게 증진시켜 인삼식물의 성장에 적합한 재배 환경을 최적화할 수 있고, 접합면이 쉽게 벗겨지지 않아 알루미늄 포일의 물리적으로 나 빗물이나 겨울철 눈이 내릴 경우 강수에 의해 산화 부식이 용이하지 않으므로 장기간 안정되게 사용할 수 있는 수명이 종래 2 내지 3년에서 3년 이상 5년 이내 사용이 가능할 뿐만 아니라 구조가 단순하여 간단한 제조방법으로 제조할 수 있어 제품의 가격 저렴화로 경제성이 탁월한 각별한 장점이 있는 유용한 발명이다. claims: 6㎛ ∼ 7㎛ 두께의 알루미늄 호일층(10)을 프레스롤을 통해 접착제에 통과시켜 알루미늄 호일층(10)에 접착제층(20)을 도포하여 형성하는 제 1 접착제 도포공정(S1공정)과; 상기 접착제층(20)과 11㎛ ∼ 13㎛의 폴리에스터 필름층(30)을 프레스롤을 통과시켜 접착한 후 안내롤을 거쳐 덕터를 통과시켜 90℃ ∼ 110℃에서 경화시키는 폴리에스터 필름층 형성공정(S2공정)과; 상기 폴리에스터 필름층(30)이 형성된 알루미늄 호일층(10)을 1급지로 공급하고 접착제와 용제가 혼합된 용액을 도포한 후 건조 챔버에서 40 ∼ 80℃로 용제를 건조시켜 접착제층(40)을 형성하는 제 2 접착제 도포공정(S3공정)과; 상기 접착제층(40)이 형성된 폴리에스터 필름층(30)에 T다이를 통해 폴리에틸렌 압출코팅층(50)을 압출 코팅하여 형성하면서 2급지에 자외선(UV) 차단 폴리에틸렌 필름층(60)을 공급하여 샌드위치 방식으로 18㎛ ∼ 22㎛ 두께의 폴리에틸렌 압출코팅층(50)과 28㎛ ∼ 38㎛ 두께의 자외선(UV) 차단 폴리에틸렌 필름층(60)을 적층시킨 후 숙성실에서 48시간 동안 보관하여 접착제층(40)을 경화시키는 폴리에틸렌 압출코팅층 및 자외선(UV) 차단 폴리에틸렌 필름층 형성공정(S4공정)과; 상기 자외선(UV) 차단 폴리에틸렌 필름층(60)이 형성된 알루미늄 호일층(10)을 1급지로 공급하고 접착제와 용제가 혼합된 용액을 도포한 후 건조 챔버에서 40 ∼ 80℃로 용제를 건조시켜 접착제층(70)을 형성하는 제 3 접착제 도포공정(S5공정) 및; 상기 접착제층(70)이 형성된 상기 알루미늄 호일층(10)에 T다이를 통해 폴리에틸렌 압출코팅층(80)을 압출 코팅하여 형성하면서 2급지에 폴리에틸렌 마대지를 공급하여 샌드위치 방식으로 15㎛ ∼ 20㎛ 두께의 폴리에틸렌 압출코팅층(80)과 20㎛ ∼ 25㎛ 두께의 폴리에틸렌 마대지층(90)을 적층시킨 후 숙성실에서 48시간 동안 보관하여 접착제층(70)을 경화시키는 폴리에틸렌 압출코팅층 및 폴리에틸렌 마대지층 형성공정(S6공정)으로 이루어지는 인삼재배용 보온덮개 겸용 차광막의 제조방법.제 1항의 방법으로 제조된 인삼재배용 보온덮개 겸용 차광막., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

101/1059 Row 101: application_number: 1020200049726, combined_string: invention_title: 다목적 미세먼지 방재숲 조성 방법 abstract: 본 발명은 미세먼지 방재숲 조성 방법에 있어서, 도심지역, 대기 오염 발생원이 설치된 오염원지역, 해안지역에 미세먼지를 저감시킬 수 있는 방재숲을 조성하되, 상기 방재숲은 각 지역별로 수목을 일정패턴으로 식재하고, 상기 방재숲에 다목적 방재 및 생육조절 장치를 일정높이로 설치하여 식재된 수목의 방재와 생육을 조절하고, 상기 방재숲에 토양 정화설비를 설치하여 방재숲의 토양에 오염수를 정화한 정화수를 공급하도록 조성하는 다목적 미세먼지 방재숲 조성 방법에 관한 발명이다. claims: 도심지역, 대기 오염 발생원이 설치된 오염원지역, 해안지역에 미세먼지를 저감시킬 수 있는 방재숲을 조성하되,상기 방재숲(100)은 각 지역별로 수목을 일정패턴으로 식재하고,상기 방재숲에 방재 및 생육조절 장치(101)를 일정높이로 설치하여 식재된 수목의 다목적 방재와 생육을 조절하고,상기 방재숲에 토양 정화설비(102)를 설치하여 방재숲의 토양에 오염수를 정화한 정화수를 수목에 공급하도록 조성하는 미세먼지 방재숲 조성 방법에 있어서,상기 방재숲의 수목 식재패턴은 바람길을 고려한 유입존(103), 미세먼지 저감을 위한 저감존(104), 미세먼지 차단을 위한 차단존(105)으로 구분하여 조성하되,유입존은 3~5m, 저감존은 8~10m, 차단존은 12~15m의 폭으로 조성하여 미세먼지 영역의 전체 폭이 최소 23m에서 최대 30m가 되도록 조성하고,상기 유입존과 저감존 및 차단존 각각에 식재하는 수목은 3열로 식재하되,1열은 상록수, 낙엽수, 상록수 순서로 대교목을 식재하여 상층림을 조성하고,2열은 낙엽수, 상록수, 낙엽수 순서로 소교목을 식재하여 중층림을 조성하며,3열은 상록수, 낙엽수, 상록수 순서로 관목을 식재하여 하층림을 조성하며,상기 방재 및 생육조절장치(101)와 토양 정화설비(102)는 미세먼지 전체영역 최대 폭 30m, 길이 30m의 900m2의 면적을 기준으로 상기 방재 및 생육조절 장치(101) 4개를 상기 기준의 가로와 세로 단부로부터 각각 10m 간격으로 이격시켜 설치하고, 상기 방재 및 생육조절 장치(101)는 상단부에 고압살수용 스프링클러(101a)를 형성하고, 그 하부에 미스트를 분무하는 다수개의 분무노즐(101b)을 형성하며, 상기 분무노즐 형성부위에 LED등 또는 레이저빔 장치로 이루어지는 조명장치(101c)를 설치하고,상기 토양 정화설비(102)는 오염된 물을 정화하는 여과장치가 설치된 집수정화조(102a)와 정수조(102b)를 연결하고 정수조에 다수개의 코어로프를 결합하여 일정길이로 형성되는 워터서코어로프(102c)를 연결하여 토양에 일정깊이로 매설하며, 워터서코어로프를 통해 정수조에 저장되는 물이 토양에 공급되도록 하는 것을 특징으로 하는 다목적 미세먼지 방재숲 조성 방법., Ltext: 임업, prediction: 임업
102/1059 Row 102: application_number: 1020200044560, combined_string: invention_title: 사카린을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충 방제 방법 abstract: 본 발명은 사카린을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충을 방제하는 방법에 관한 것이다. claims: 사카린을 포함하는 소나무재선충 방제용 조성물.제 1항 내지 제 4항 중 어느 하나의 조성물을 식물 또는 토양에 처리하여 소나무재선충을 방제하는 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

103/1059 Row 103: application_number: 1020200043339, combined_string: invention_title: 토마토 혼성체 HN5003 및 부모 계통 SENG9234 abstract: 본 발명은 신규한 토마토 혼성체 HN5003 또는 계통 SENG9234 및 이로부터 유래하는 식물 부분, 종자 및 조직 배양을 제공한다. 또한, 본 발명은 본 발명의 토마토 식물을 그 자신 또는 다른 토마토 식물과 교배함으로써 토마토 식물을 생산하는 방법을 제공한다. 또한, 본 발명은 이 같은 교배로부터 생산되는 토마토 식물뿐만 아니라 이로부터 유래하는 식물 부분, 종자 및 조직 배양을 제공한다. claims: 각각 NCIMB 기탁 번호 제43380호 및 NCIMB 기탁 번호 제43381호로 기탁되어 있는 대표적인 종자 시료인 토마토 혼성체 HN5003 또는 계통 SENG9234를 생산하는 종자.제8항의 상기 조직 배양으로부터 재생되는 토마토 식물 또는 이의 자가 수분된 자손으로서,상기 토마토 식물은 토마토 혼성체 HN5003 또는 계통 SENG9234의 생리학적 및 형태학적 특징을 모두 포함하는 것인 토마토 식물 또는 이의 자가 수분된 자손.토마토 종자를 생산하는 방법으로서,제2항의 상기 식물을 그 자신 또는 제2 토마토 식물과 교배하는 단계; 및얻어진 종자를 수확하는 단계를 포함하는 것인 토마토 종자를 생산하는 방법.접목된 토마토 식물을 생산하는 방법으로서,(a) 제2항의 상기 식물로부터 어린 가지를 제공하는 단계; 및(b) 상이한 토마토 식물에서 유래하는 근경에 상기 어린 가지를 접목하는 단계를 포함하는 것인 접목된 토마토 식물을 생산하는 방법.토마토 혼성체 HN5003 또는 계통 SENG9234에서 유래하는 토마토 식물의 종자를 생산하는 방법으로서,(a) 제2항의 상기 식물을 상이한 토마토 식물과 교배하는 단계;(b) 종자를 형성하도록 하는 단계;(c) 단계 (b)의 상기 종자로부터 식물을 재배하여 토마토 혼성체 HN5003 또는 계통 SENG9234에서 유래하는 식물을 생산하는 단계;(d) 단계 (c)의 상기 식물을 자가 수분시키거나 이를 제2 토마토 식물과 교배하여 토마토 혼성체 HN5003 또는 계통 SENG9234에서 유래하는 부가적인 토마토 종자를 형성하는 단계; 및(e) 선택적으로는 단계 (c) 및 단계 (d)를 1회 이상 반복하여 토마토 혼성체 HN5003 또는 계통 SENG9234로부터 유래하는 추가의 토마토 종자를 생성하는 단계를 포함하며,이때, 단계 (c)에서는 단계 (b)의 상기 종자로부터 식물을 재배하는 대신에 단계 (d)의 상기 부가적인 토마토 종자로부터 식물을 재배하는 것인 토마토 식물의 종자를 생산하는 방법.토마토 혼성체 HN5003 또는 계통 SENG9234를 영양 번식하는 방법으로서,(a) 제2항의 상기 식물로부터 번식될 수 있는 조직을 수집하는 단계;(b) 상기 조직을 배양하여 증식된 새싹을 수득하는 단계;(c) 증식된 새싹을 발근(rooting)시켜 발근된 묘목(plantlet)을 수득하는 단계; 및(d) 선택적으로는 상기 발근된 묘목으로부터 식물을 재배하는 단계를 포함하는 것인 토마토 혼성체 HN5003 또는 계통 SENG9234를 영양 번식하는 방법.제17항의 상기 방법에 의해 수득되는 토마토 묘목 또는 식물로서,상기 토마토 묘목 또는 식물은 토마토 혼성체 HN5003 또는 계통 SENG9234의 생리학적 및 형태학적 특징을 모두 포함하는 것인 토마토 묘목 또는 식물.토마토 혼성체 HN5003 또는 계통 SENG9234에 목적하는 부가 형질을 도입하는 방법으로서,(a) 반복친(recurrent parent)으로서의 제2항의 상기 식물을 목적하는 부가 형질을 포함하는 상이한 토마토 식물과 교배하여 F1 자손을 생산하는 단계;(b) 상기 목적하는 부가 형질을 포함하는 F1 자손을 선별하는 단계;(c) 상기 선별된 F1 자손을 단계 (a)에서와 동일한 반복친과 교배하여 역교배 자손을 생산하는 단계;(d) 상기 목적하는 부가 형질을 포함하는 역교배 자손을 선별하는 단계; 및(e) 선택적으로는 단계 (c) 및 단계 (d)를 1회 이상 반복하여, 상기 목적하는 부가 형질을 포함하고, 그렇지 않는 경우 토마토 혼성체 HN5003 또는 계통 SENG9234의 생리학적 및 형태학적 특징을 모두 포함하는 토마토 혼성체 HN5003 또는 계통 SENG9234에서 유래한 식물을 생산하는 단계를 포함하며,이때, 단계 (c)에서는 단계 (d)에서 생산된 상기 선별된 역교배 자손을 단계 (b)의 상기 선별된 F1 자손 대신에 사용하는 것인 토마토 혼성체 HN5003 또는 계통 SENG9234에 목적하는 부가 형질을 도입하는 방법.제22항의 상기 방법에 의해 생산되는 토마토 식물 또는 이의 자가 수분된 자손으로서,상기 토마토 식물은 상기 목적하는 부가 형질을 갖는 것인 토마토 식물 또는 이의 자가 수분된 자손.목적하는 부가 형질을 포함하는 토마토 혼성체 HN5003 또는 계통 SENG9234의 식물을 생산하는 방법으로서,제2항의 상기 식물에 상기 목적하는 형질을 부여하는 이식 유전자를 도입하는 단계를 포함하는 것인 토마토 혼성체 HN5003 또는 계통 SENG9234의 식물을 생산하는 방법.제26항의 상기 방법에 의해 생산되는 토마토 식물 또는 이의 자가 수분된 자손으로서,상기 토마토 식물은 상기 이식 유전자를 포함하고 상기 목적하는 부가 형질을 갖는 것인 토마토 식물 또는 이의 자가 수분된 자손.토마토 열매를 생산하는 방법으로서,(a) 제2항에 따른 상기 토마토 식물을 재배하여 토마토 열매를 생산하는 단계; 및(b) 상기 토마토 열매를 수확하는 단계를 포함하는 것인 토마토 열매를 생산하는 방법.토마토 가공 산물을 생산하는 방법으로서,(a) 제2항의 상기 식물의 열매를 수득하는 단계; 및(b) 상기 열매를 가공하여 가공 산물을 생산하는 단계를 포함하는 것인 토마토 가공 산물을 생산하는 방법., Ltext: 임업, prediction: 임업
104/1059 Row 104: application_number: 1020200037928, combined_string: invention_title: 탄소복합소재 적재함을 가진 다목적 드론 abstract: 본 발명은 탄소복합소재 적재함을 가진 다목적 드론에 관한 것이다. 본 발명에 의한 탄소복합소재 적재함을 가진 다목적 드론은, 복수의 프로펠러들이 회전 가능하게 설치되고, 드론 구동을 위한 회로기판 및 전자부품들이 수용되는 캐노피; 드론 랜딩시 랜딩면에 접촉되는 한 쌍의 랜딩부들과, 각각 일측은 상기 각 랜딩부에 연결되고 타측은 상기 상기 캐노피에 연결되는 연결프레임부들을 구비하는 스키드; 및 비료와 같은 농업에 사용되는 재료 또는 묘목과 같은 임업 수확물 수용을 위한 것으로, 탄소복합소재를 포함한 재질로 이루어지고, 상기 연결프레임부의 일측과 타측 사이의 부분에 지지가능하게 설치되는 적재함;을 포함하여 이루어지는 것을 특징으로 한다. claims: 복수의 프로펠러들이 회전 가능하게 설치되고, 드론 구동을 위한 회로기판 및 전자부품들이 수용되는 캐노피;드론 랜딩시 랜딩면에 접촉되는 한 쌍의 랜딩부들과, 각각 일측은 상기 각 랜딩부에 연결되고 타측은 상기 상기 캐노피에 연결되는 연결프레임부들을 구비하는 스키드; 및비료와 같은 농업에 사용되는 재료 또는 묘목과 같은 임업 수확물 수용을 위한 것으로, 탄소복합소재를 포함한 재질로 이루어지고, 상기 연결프레임부의 일측과 타측 사이의 부분에 지지가능하게 설치되는 적재함;을 포함하여 이루어지는 것을 특징으로 하는 탄소복합소재 적재함을 가진 다목적 드론., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

105/1059 Row 105: application_number: 1020200037943, combined_string: invention_title: 규조토, 일라이트를 함유하고 편백추출액으로 코팅된 건축용 마감재 abstract: 본 발명은 규조토, 일라이트를 함유하고 편백추출액으로 코팅된 건축용 마감재에 관한 것으로서, 그 구성은 살균하여 분쇄 및 압착된 알갱이 형태의 왕겨, 황토분말, 규조토 분말, 숯 분말 및 게르마늄 분말이 혼합된 제 1 혼합물과 일라이트, 맥반석, 흑운모 및 연옥을 분쇄하여 각각 5mm 내지 20mm 크기의 석재가 혼합된 제 2 혼합물을 교반기 통해 혼합하고, 미강, 찹쌀 및 물을 혼합하여 95℃로 일정시간 가열하여 냉각시켜 준비된 천연 접착제를 제 1 혼합물과 제 2 혼합물과 혼합하여 고형화를 위해 건축용 마감재의 비중에 맞춰 압축 로울러로 압착하여 성형하고, 성형된 마감재 표면을 편백추출액으로 코팅한 후 120℃ ∼ 140℃의 온도로 가열하여 성형된 건축용 마감재의 접착성분에 의해 압축상태를 유지하기 위해 가열하여 바닥, 벽, 천정, 실외 벽재를 위한 건축용 마감재의 형태를 구성되는 것을 특징으로 한다. 이에 의해, 왕겨, 황토, 규조토, 숯의 성분을 통해 자연습도조절은 물론 총휘발성 유기화합물, 포름알데히드 등 유해요소의 제거, 탈취기능 및 항균기능 등을 함께 가지는 것은 물론 일라이트, 흑운모, 연옥를 통해 도막의 변색이나 변형이 거의 없어 건축 마감재뿐만 아니라, 내 외장용 마감재로도 사용할 수 있는 쾌적하면서도 친환경적인 건축마감재를 제공한다. claims: 살균하여 분쇄 및 압착된 알갱이 형태의 왕겨, 황토분말, 규조토 분말, 숯 분말 및 게르마늄 분말이 혼합된 제 1 혼합물과 일라이트, 맥반석, 흑운모 및 연옥을 분쇄하여 각각 5mm 내지 20mm 크기의 석재가 혼합된 제 2 혼합물을 교반기 통해 혼합하고, 미강, 찹쌀 및 물을 혼합하여 95℃로 일정시간 가열하여 냉각시켜 준비된 천연 접착제를 제 1 혼합물과 제 2 혼합물과 혼합하여 고형화를 위해 건축용 마감재의 비중에 맞춰 압축 로울러로 압착하여 성형하고, 성형된 마감재 표면을 편백추출액으로 코팅한 후 120℃ ∼ 140℃의 온도로 가열하여 성형된 건축용 마감재의 접착성분에 의해 압축상태를 유지하기 위해 가열하여 바닥, 벽, 천정, 실외 벽재를 위한 건축용 마감재의 형태를 이루어지는 것을 특징으로 하는 규조토, 일라이트를 함유하고 편백추출액으로 코팅된 건축용 마감재., Ltext: 임업, prediction: 임업
106/1059 Row 106: application_number: 1020200033916, combined_string: invention_title: 소나무재선충 신속 검출용 재조합효소-중합효소 증폭 프라이머 프로브 세트 abstract: 본 발명은 소나무재선충(Bursaphelenchus xylophilus) 신속 검출용 재조합효소-중합효소 증폭 프라이머 프로브 세트에 관한 것이다. 본 발명의 소나무재선충 검출용 RPA 프라이머 프로브 세트는 어리소나무재선충(B. mucronatus)을 포함한 근연관계의 부식성 선충류(B. doui, B. thailandae, B. hylobianum)로부터 소나무재선충(B. xylophilus)을 특이적으로 구별할 수 있기 때문에 소나무재선충병 감염이 의심되는 목편 시료에서 신속하고 정확하게 소나무재선충병 감염 여부를 진단할 수 있으므로, 소나무재선충 검출 및 소나무재선충병 진단 방법에 효과적이다. claims: 서열번호 1의 염기서열로 이루어진 정방향 프라이머 및 서열번호 2의 염기서열로 이루어진 역방향 프라이머로 이루어진 프라이머 세트; 및 서열번호 3의 염기서열로 이루어진 증폭산물을 확인하는 프로브를 포함하는, 소나무재선충(Bursaphelenchus xylophilus) 신속 검출용 재조합효소-중합효소 반응 (Recombinase Polymerase Amplification; RPA) 프라이머 프로브 세트.(a) 소나무 시료로부터 DNA를 분리하는 단계;(b) 상기 (a) 단계에서 분리한 DNA를 주형으로 하고 제 1항의 프라이머 세트를 이용하여 재조합효소-중합효소 반응(RPA)을 수행하는 단계; 및(c) 상기 (b) 단계의 반응 산물을 분석하는 단계를 포함하는 소나무재선충병 진단 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

107/1059 Row 107: application_number: 1020200024958, combined_string: invention_title: 농업 및 임업용 드론 abstract: 본 발명은 농업 및 임업용 드론에 관한 것으로, 예컨대 농업용에 사용되는 비료들 중 입상 비료와 액상 비료의 체적이 달라 케이스의 규격이 다른 경우 그 케이스가 탑재되는 스키드의 규격이 달라 교체가 요구되는 경우에, 드론 구동을 위한 전자부품과 프로펠라가 설치된 캐노피는 그대로 두고 스키드를 캐노피에 결합시키되, 결합 유닛의 레일부와 레일홈부 간의 슬라이딩 동작에 의한 결합 및 분리가 가능하여 교체 작업의 편리성을 향상시킬 수 있게 하는 효과와, 나사나 볼트에 의한 반복적인 드릴링 과정이 요구되지 않게 됨으로써 제품의 내구성을 높일 수 있게 하는 효과를 기대할 수 있게 한다. claims: 복수의 프로펠러들이 회전 가능하게 설치되고, 드론 구동을 위한 회로기판 및 전자부품들이 수용되는 캐노피; 비료와 같은 농업에 사용되는 재료 또는 묘목과 같은 임업 수확물 수용을 위한 케이스를 상기 캐노피에 지지시켜 주기 위한 것으로, 랜딩시 랜딩면에 접촉되는 한 쌍의 랜딩부들과, 일측은 상기 각 랜딩부에 연결되고 타측은 상기 상기 캐노피에 연결되며, 상기 일측과 타측 사이의 부분에 상기 케이스가 지지가능하게 설치되며, 상기 랜딩부의 길이방향을 따라 간격을 두고 배치되는 한 쌍의 연결프레임부들을 구비하는 스키드; 및 상기 캐노피와 스키드가 서로 상대이동 과정에서 끼움결합될 수 있도록, 상기 캐노피와 스키드 중 어느 하나에 일방향 축선을 따라 길게 형성된 레일부와 다른 하나에 마련되고 상기 레일부가 끼워지는 레일홈부와 상기 캐노피와 스키드의 끼움 결합이 완료된 상태에서 임의 분리를 방지하기 위한 록킹부를 포함하는 결합 유닛;을 포함하여 이루어지고,상기 케이스는, 상기 각 연결프레임부에 고정되는 고정케이스; 및 상기 고정케이스에 상대이동 가능하게 설치되고, 상기 묘목과 같은 임업 수확물이 수용되는 공간을 가지며, 묘목이 놓이는 바닥면의 중심부에 형성되는 것으로 흙과 같은 이물질이 상기 고정케이스 측으로 배출될 수 있게 하는 이물질 배출부와, 상기 바닥면의 중심부를 사이에 두고 반대측에 형성되는 것으로 상기 중심부측으로 갈수록 높이가 낮게 형성되는 한 쌍의 경사부들을 구비하는 인출케이스;를 포함하여 이루어지는 것을 특징으로 하는 농업 및 임업용 드론., Ltext: 임업, prediction: 농업
108/1059 Row 108: application_number: 1020200016784, combined_string: invention_title: 신규 스트렙토마이세스 속 균주 또는 이로부터 분리된 화합물을 함유하는 소나무재선충병 방제용 조성물 abstract: 본 발명은 신규한 스트렙토마이세스 속(Streptomyces sp.) 균주 및 상기 균주 또는 상기 균주로부터 분리된 화합물을 유효성분으로 함유하는 소나무재선충병 방제용 조성물에 관한 것으로, 본 발명의 스트렙토마이세스 속 균주 및 이로부터 분리한 화합물은 소나무재선충병 방제에 효과적인 환경친화형 생물농약을 제공할 수 있어 관련 산업에 매우 유용할 것으로 기대된다. claims: 기탁번호가 KCTC13792BP인 스트렙토마이세스 속(Streptomyces sp.) AE170020 균주.하기 화학식 1로 표시되는 화합물, 이의 입체이성질체 또는 이의 농약학적으로 허용가능한 염을 유효성분으로 함유하는 소나무재선충병 방제용 조성물.[화학식 1]상기 화학식 1에서,R1 및 R2는 각각 독립적으로 수소, C1~4 알킬 또는 C1~4 알콕시이고;R3은 C1~4 알킬이고;R4 및 R5는 각각 독립적으로 수소, C1~4 알킬, C1~4 알콕시, 히드록시 또는 할로이고;R6 내지 R8은 각각 독립적으로 수소, 또는 C1~4 알킬이고;n은 1, 2 또는 3의 정수이다.기탁번호가 KCTC13792BP인 스트렙토마이세스 속(Streptomyces sp.) AE170020 균주 배양액을 유효성분으로 함유하는 소나무재선충병 방제용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

109/1059 Row 109: application_number: 1020200017233, combined_string: invention_title: 다양한 소나무에 저항성을 유도하는 바실러스 서린지엔시스 JCK-1233 균주 및 이를 이용한 소나무재선충병 방제용 조성물 abstract: 본 발명은 다양한 소나무에 저항성을 유도하는 바실러스 서린지엔시스(Bacillus thuringiensis) JCK-1233 균주(수탁번호 KCTC 14085BP) 및 이로부터 분리된 다이케토피페라진(Diketopiperazine) 화합물, 및 이를 유효성분으로 포함하는 살선충제 조성물 및 식물병 방제용 조성물에 관한 것으로, 본 발명의 바실러스 서린지엔시스(Bacillus thuringiensis) JCK-1233 균주 및 이로부터 분리된 다이케토피페라진(Diketopiperazine) 화합물은 소나무에 저항성을 유도함으로써 식물병 원인 선충에 대한 방제 활성을 가지는 것을 실험적으로 확인하였다. 따라서, 본 발명의 바실러스 서브틸리스 JCK-1233 균주는 관련 식물병 방제 용도로 유용하게 사용될 수 있으며, 엽면살포를 통한 광범위 지역 살포가 가능하므로, 낮은 비용으로 소나무재선충병의 확산을 방지할 수 있을 것으로 기대된다. claims: 병해충에 대한 식물의 유도저항성 (induced resistance)을 활성화하는 수탁번호 KCTC 14085BP의 바실러스 서린지엔시스 (Bacillus thuringiensis) JCK-1233 균주.제1항 내지 제3항 중 어느 한 항의 균주, 상기 균주의 배양물, 상기 배양물의 농축물, 상기 배양물의 건조물 및 상기 균주의 배양 상등액으로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물.하기 화학식 1 내지 화학식 6으로 표시되는 화합물 및 이의 유도체(derivative)로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물:[화학식 1][화학식 2][화학식 3][화학식 4][화학식 5][화학식 6].제6항에 있어서, 상기 화학식 1 내지 화학식 6으로 표시되는 화합물은 수탁번호 KCTC 14085BP의 바실러스 서린지엔시스 (Bacillus thuringiensis) JCK-1233 균주로부터 분리된 것인, 조성물.제6항에 있어서, 상기 식물병은 소나무재선충병인, 조성물., Ltext: 임업, prediction: 임업
110/1059 Row 110: application_number: 1020200017234, combined_string: invention_title: 다양한 식물에 저항성을 유도하는 바실러스 메가테리움 JCK-758-1 균주, 이를 이용한 소나무재선충병 방제용 조성물 및 방제방법 abstract: 본 발명은 소나무 및 다양한 식물에 유도저항성 활성을 갖는 바실러스 메가테리움 (Bacillus megaterium) JCK-758-1 균주 (수탁번호 KCTC 14083BP) 및 이로부터 분리된 화합물, 및 이를 유효성분으로 포함하는 살선충제 또는 항균제 조성물, 식물병 방제용 조성물 및 이를 이용한 방제방법에 관한 것으로, 본 발명의 바실러스 메가테리움 JCK-758-1 균주 및 이로부터 분리된 화합물은 기주에 저항성을 유도함으로써 식물병 원인 선충 및 균에 대한 방제 활성을 가지는 것을 실험적으로 확인하였다. 따라서, 본 발명의 바실러스 메가테리움 JCK-758-1 균주는 관련 식물병 방제 용도로 유용하게 사용될 수 있으며, 엽면살포를 통한 광범위 지역 살포가 가능하므로, 낮은 비용으로 소나무재선충병의 확산을 방지할 수 있을 것으로 기대된다. claims: 병해충에 대한 식물의 유도저항성 (induced resistance)을 활성화하는 수탁번호 KCTC 14083BP의 바실러스 메가테리움 (Bacillus megaterium) JCK-758-1 균주.제1항 내지 제3항 중 어느 한 항의 균주, 상기 균주의 배양물, 상기 배양물의 농축물, 상기 배양물의 건조물 및 상기 균주의 배양 상등액으로 이루어진 군으로부터 선택된 1종 이상을 포함하는 살선충제 또는 항균제 조성물.제1항 내지 제3항 중 어느 한 항의 균주, 상기 균주의 배양물, 상기 배양물의 농축물, 상기 배양물의 건조물 및 상기 균주의 배양 상등액으로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물.하기 화학식 1 내지 화학식 5로 표시되는 화합물 및 이의 유도체로 이루어진 군으로부터 선택된 1종 이상을 포함하는 살선충제 또는 항균제 조성물:[화학식 1][화학식 2][화학식 3][화학식 4][화학식 5].제9항에 있어서, 상기 화학식 1 내지 화학식 5로 표시되는 화합물은 수탁번호 KCTC 14083BP의 바실러스 메가테리움 (Bacillus megaterium) JCK-758-1 균주로부터 분리된 것인, 조성물.제9항에 있어서, 상기 선충은 소나무재선충 (Bursaphelenchus xylophilus)인 것인, 조성물.제9항에 있어서, 상기 균은 크산토모나스 유베시카토리아 (Xanthomonas euvesicatoria)인 것인, 조성물.하기 화학식 1 내지 화학식 5로 표시되는 화합물 및 이의 유도체로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물:[화학식 1][화학식 2][화학식 3][화학식 4][화학식 5].제13항에 있어서, 상기 화학식 1 내지 화학식 5로 표시되는 화합물은 수탁번호 KCTC 14083BP의 바실러스 메가테리움 (Bacillus megaterium) JCK-758-1 균주로부터 분리된 것인, 조성물.제13항에 있어서, 상기 식물병은 소나무재선충병 및 고추세균성점무늬병으로 이루어진 군으로부터 선택된 것인, 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

111/1059 Row 111: application_number: 1020200017232, combined_string: invention_title: 다양한 식물에 저항성을 유도하는 바실러스 서브틸리스 JCK-1398 균주, 이를 이용한 소나무재선충병 방제용 조성물 및 방제방법 abstract: 본 발명은 소나무 및 다양한 식물에 유도저항성 활성을 갖는 바실러스 서브틸리스 (Bacillus subtilis) JCK-1398 균주 (수탁번호 KCTC 14084BP) 및 이를 유효성분으로 포함하는 살충제 또는 항균제 조성물, 식물병 또는 해충 방제용 조성물 및 이를 이용한 방제방법에 관한 것으로, 본 발명의 바실러스 서브틸리스 (Bacillus subtilis) JCK-1398 균주는 기주에 저항성을 유도함으로써 다양한 식물병 원인 해충, 선충 및 균에 대한 방제 활성을 가지는 것을 실험적으로 확인하였다. 따라서, 본 발명의 바실러스 서브틸리스 JCK-1398 균주는 관련 식물병 방제 용도로 유용하게 사용될 수 있으며, 엽면살포를 통한 광범위 지역 살포가 가능하므로, 낮은 비용으로 소나무재선충병의 확산을 방지할 수 있을 것으로 기대된다. claims: 식물병에 대한 소나무, 고추, 잔디 및 토마토로 이루어진 군으로부터 선택되는 1종 이상의 유도저항성 (induced resistance)을 활성화하는 수탁번호 KCTC 14084BP의 바실러스 서브틸리스 (Bacillus subtilis) JCK-1398 균주.수탁번호 KCTC 14084BP의 바실러스 서브틸리스 (Bacillus subtilis) JCK-1398 균주, 상기 균주의 배양물, 상기 배양물의 농축물, 상기 배양물의 건조물 및 상기 균주의 배양 상등액으로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물에 관한 것으로서,상기 식물병은 소나무재선충병, 고추세균성점무늬병 및 잔디동전마름병으로 이루어진 군으로부터 선택된 것인, 조성물., Ltext: 임업, prediction: 임업
112/1059 Row 112: application_number: 1020200015543, combined_string: invention_title: 국내산 낙엽송과 잣나무 탄화건조 가로등 지주목 abstract: 본 발명은 국내산 낙엽송과 잣나무 탄화건조 가로등 지주목에 관한 것으로서, 더욱 상세하게는 국내산 낙엽송, 잣나무 등과 같은 원목을 가로등 지주에 사용 가능하도록 탄화건조방식으로 처리하여, 내구성뿐만 아니라 친환경적이면서 친자연적인 아름다움을 극대화함에 따라 도시화된 거리에 자연적인 이미지를 부각시켜줌에 따라 불특정 다수인들에게 편안하고 안락한 친밀감을 제공하는 가로등 지주의 제품경쟁력을 강화하는 국내산 낙엽송과 잣나무 탄화건조 가로등지주목에 관한 것이다.이를 위해 본 발명의 가로등지주목(1)는 길이방향으로 관통하는 중심홀(2)이 형성되고; 상기 중심홀(2)이 형성된 가로등지주목(1)를 150 ~ 350(℃)의 온도에서 2 내지 7(일) 동안 간접 가열로 숙성 건조하는 탄화건조법으로 상기 가로등지주목(1)를 방부처리하며; 상기 탄화건조법으로 방부처리된 가로등지주목(1)의 중심홀(2)에는 금속재이면서 일정두께를 가지는 파이프(10)를 억지 끼움으로 삽입하여;된 것을 특징으로 하는 한다. claims: 가로등과 같이 일정높이 세워지는 지주로 사용 가능한 가로등지주목에 있어서, 상기 가로등지주목(1)은길이방향으로 관통하는 중심홀(2)이 형성되고;상기 중심홀(2)이 형성된 가로등지주목(1)을 150 ~ 350(℃)의 온도에서 1 내지 7(일) 동안 간접 가열로 숙성 건조하는 탄화건조법으로 상기 가로등지주목(1)의 내구성 및 방부기능을 가지도록 하는 것을 특징으로 하는 국내산 낙엽송과 잣나무 탄화건조 가로등 지주목.가로등과 같이 일정높이 세워지는 지주로 사용 가능한 가로등지주목에 있어서, 상기 가로등지주목(1)은길이방향으로 관통하는 중심홀(2)이 형성되고;상기 중심홀(2)에는 일정두께를 가지는 파이프(10)를 삽입하며;상기 파이프(10)가 삽입된 가로등지주목(1)을 150 ~ 350(℃)의 온도에서 1 내지 7(일) 동안 간접 가열로 숙성 건조하는 탄화건조법으로 상기 가로등지주목(1)의 내구성 및 방부기능을 가지도록 하며;상기 탄화건조법에 의해 수축되는 가로등지주목(1)에 의해 상기 중심홀(2)에 삽입된 파이프(10)가 수축력에 의한 압박으로 상기 중심홀(2)에 고정되도록;하는 것을 특징으로 하는 국내산 낙엽송과 잣나무 탄화건조 가로등 지주목., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

113/1059 Row 113: application_number: 1020200015705, combined_string: invention_title: 시맨틱 분할을 이용한 소나무 재선충 확산 방지 시스템 및 방법 abstract: 본 발명의 일 실시예에 따른 시맨틱 분할을 이용한 소나무 재선충 확산 방지 시스템은 소나무가 분포한 지역에 관한 촬영 이미지를 데이터 세트로서 수집하고, 상기 수집된 데이터 세트에 대하여 픽셀 단위로 레이블을 지정하여 훈련 세트를 생성하는 전처리부; 및 상기 데이터 세트 및 상기 훈련 세트를 바탕으로 시맨틱 분할 딥러닝을 수행하여 객체를 분류하고, 상기 객체의 분류 결과에 기초하여 소나무 재선충병 관련 정보를 제공하는 학습부를 포함한다. claims: 소나무가 분포한 지역에 관한 촬영 이미지를 데이터 세트로서 수집하고, 상기 수집된 데이터 세트에 대하여 픽셀 단위로 레이블을 지정하여 훈련 세트를 생성하는 전처리부; 및상기 데이터 세트 및 상기 훈련 세트를 바탕으로 시맨틱 분할 딥러닝을 수행하여 객체를 분류하고, 상기 객체의 분류 결과에 기초하여 소나무 재선충병 관련 정보를 제공하는 학습부를 포함하는 것을 특징으로 하는 시맨틱 분할을 이용한 소나무 재선충 확산 방지 시스템.시맨틱 분할을 이용한 소나무 재선충 확산 방지 시스템을 이용한 소나무 재선충 확산 방지 방법에 있어서,상기 소나무 재선충 확산 방지 시스템의 전처리부가 소나무 분포 지역에 관한 촬영 이미지를 데이터 세트로서 수집하는 단계;상기 전처리부가 상기 수집된 데이터 세트에 대하여 픽셀 단위로 레이블을 지정하여 훈련 세트를 생성하는 단계;상기 소나무 재선충 확산 방지 시스템의 학습부가 상기 데이터 세트 및 상기 훈련 세트를 바탕으로 시맨틱 분할 딥러닝을 수행하여 객체를 분류하는 단계; 및상기 학습부가 상기 객체의 분류 결과에 기초하여 소나무 재선충병 관련 정보를 제공하는 단계를 포함하는 것을 특징으로 하는 시맨틱 분할을 이용한 소나무 재선충 확산 방지 방법., Ltext: 임업, prediction: 임업
114/1059 Row 114: application_number: 1020200010979, combined_string: invention_title: 산림용 묘목 보호 시트 abstract: 본 발명은 산림용 묘목 보호 시트에 관한 것으로서, 더욱 상세하게는, 산에 식재된 어린 묘목의 위치표시 및 보호를 위해 설치하여 외부의 피해를 방지하고 묘목의 생장을 방해하는 잡초의 생장을 방지하는 산림용 묘목 보호 시트에 관한 것이다. claims: 조림목이 내부에 수용되며, 지면에 설치되는 산림용 묘목 보호 시트에 있어서,상기 조림목(100)의 하단부분을 수용하도록 설치된 본체(10);상기 본체(10)의 양측단으로 연장되며, 절곡선(BL)을 기준으로 절곡되어 지면을 지지하는 절곡부(20)로 이루어지되,상기 본체(10)는,중앙에 상기 조림목(100)을 수용하는 수용홈(11)과, 상기 수용홈(11)에서 전면을 향해 형성되어 상기 조림목(100)이 유입되는 절개홈(12)의 형상을 따라 절취선(PL)이 형성되어 절취되는 절취부(14)가 포함되되,상기 절취부(14)는,상기 수용홈(11)의 형상을 따라 절취되어 중앙부분에는 상기 조림목(100)의 상단에 고정되는 걸이홈(15a)이 형성된 걸이부(15)와,상기 절개홈(12)의 형상의 따라 절취되며, 길이방향을 따라 중앙이 절취되어 외부로 노출된 인식부(16)로 이루어지는 것을 특징으로 하는 산림용 묘목 보호 시트., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

115/1059 Row 115: application_number: 1020200003149, combined_string: invention_title: 고로쇠 수액 출수량 예측 시스템 abstract: 개시된 본 발명에 따른 고로쇠 수액 출수량 예측 시스템은, 복수의 센서가 설치되어 복수의 환경정보를 얻으며 고로쇠 수액이 저장되는 스마트 집수조(100)와, 스마트 집수조에서 보내온 복수의 환경정보와 고로쇠 수액 출수량 정보및 기상청의 기상환경 정보가 입력되는 데이터 입력부(200)와, 데이터 입력부에 입력된 정보들을 머신러닝 알고리즘의 학습 데이터로 활용하기 위해 전처리를 수행하는 데이터 전처리부(300)와, 고로쇠 수액 출수량을 예측하기 위해 복수의 인공신경망 트리 모델을 구성하며, 구축된 복수의 인공신경망 트리 모델은 상기 데이터 전처리부의 데이터를 입력값으로 하여 상기 환경정보와 고로쇠 수액 출수량의 상관관계를 분석하여 각각의 예측을 진행하고, 예측 수액 출수량을 출력값으로 하여 예측 결과를 도출하는 수액 출수량 예측모델 생성부(400), 및 수액 출수량 예측모델 생성부의 복수의 예측 결과를 다수결의 원칙으로 처리하여 최종 고로쇠 수액의 예측 출수량을 산출하는 수액 출수량 산출부를 포함한다. 본 발명에 의하면 머신러닝에 기반하여 학습 시간, 예측 시간, 정확도를 기준으로 가장 정확하고 효율적인 고로쇠나무 수액 출수량을 예측할 수 있고, 이러한 고로쇠나무 수액의 생산량 예측으로 산간 농가들의 효율적인 노동력 활용과 고로쇠 수액의 품질관리를 개선할 수 있는 효과가 있다. claims: 복수의 센서가 설치되어 복수의 환경정보를 얻으며 고로쇠 수액이 저장되는 스마트 집수조;상기 스마트 집수조에서 보내온 복수의 환경정보와 고로쇠 수액 출수량 정보및 기상청의 기상환경 정보가 입력되는 데이터 입력부;상기 데이터 입력부에 입력된 정보들을 머신러닝 알고리즘의 학습 데이터로 활용하기 위해 전처리를 수행하는 데이터 전처리부;고로쇠 수액 출수량을 예측하기 위해 복수의 인공신경망 트리 모델을 구성하며, 구축된 복수의 인공신경망 트리 모델은 상기 데이터 전처리부의 데이터를 입력값으로 하여 상기 환경정보와 고로쇠 수액 출수량의 상관관계를 분석하여 각각의 예측을 진행하고, 예측 수액 출수량을 출력값으로 하여 예측 결과를 도출하는 수액 출수량 예측모델 생성부; 및,상기 수액 출수량 예측모델 생성부의 복수의 예측 결과를 다수결의 원칙으로 처리하여 최종 고로쇠 수액의 예측 출수량을 산출하는 수액 출수량 산출부;를 포함하는 것을 특징으로 하는 고로쇠 수액 출수량 예측 시스템., Ltext: 임업, prediction: 임업
116/1059 Row 116: application_number: 1020200000111, combined_string: invention_title: 생산성이 현저히 증진된 일본잎갈나무 조직배양 묘목의 생산방법 abstract: 본 발명에서는 체세포배의 발아 및 재분화 촉진 공정 및 순화묘 생장 촉진 공정을 통하여 생산성이 현저히 증진된 일본잎갈나무 조직배양 묘목의 생산방법이 개시된다. 본 발명에 따른 일본잎갈나무 조직배양 묘목의 생산방법은 산림조림용 일본잎갈나무 조직배양묘 대량생산 시스템으로 효율적인 적용이 가능하다. 또한 본 발명에 따른 일본잎갈나무 묘목은 생장이 양호한 건전 순화묘이어서 대량 산지조림용에 활용성이 높다. claims: i) 일본잎갈나무 체세포배를 준비하는 단계; ii) 발아배지 상에 필터페이퍼를 올려놓은 후 일본잎갈나무 체세포배를 치상하여 배양하여 발아시키는 단계; iii) 발아체를 필터페이퍼가 없는 발아배지 상에 옮겨서 배양하여 재분화하여 유식물체를 얻는 단계; 및 iv) 유식물체를 80~90%의 습도가 유지되는 순화용기 내 인공토양에 이식하여 하이포넥스를 처리하여 배양하여 순화묘를 얻는 단계;를 포함하는 일본잎갈나무 조직배양 묘목의 생산방법.제 1항 내지 제 11항 중 어느 한 항에 따른 방법에 의해 생산된 일본잎갈나무 묘목., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

117/1059 Row 117: application_number: 1020190166857, combined_string: invention_title: 배 대목의 증식을 위한 조직배양 배지 조성물 및 이의 이용 abstract: 본 발명은 배 대목, 구체적으로 배 왜화성 대목의 증식을 위한 조직배양 배지 조성물 및 이의 이용에 관한 것이다. 본 발명에 따른 조직배양 배지 조성물은 배의 왜화성 대목 계통에서 92%의 뿌리 형성을 나타낼 뿐만 아니라, 배양묘의 순화 과정에서 식물체의 높이 및 크기가 50% 이상 향상되는 등 전반적인 식물체 활력을 개선하고 우량 개체의 비율이 높아지는 효과가 있다. 이에, 본 발명은 묘목의 대량증식 및 순화에 적용시 경제적으로 유리하며, 뿌리가 발생하지 않아 어려움을 겪었던 유전자원의 증식 및 보존에 적용할 수 있다. claims: 배 왜화성 대목의 조직배양 배지 조성물로서,상기 배지 조성물은 배지 조성물 1리터당 MS(Murashige and Skoog) 배지 또는 LS(Linsmaier and Skoog) 배지 중 어느 하나인 배지 0.9 내지 1.3g, IBA(Indole-3-butyric acid) 0.4 내지 0.6ml, NAA(Naphthalene acetic acid) 0.4 내지 0.6ml, 수크로스(sucrose) 10 내지 20g 및 아가(agar) 7 내지 11g을 포함하는, 배지 조성물.제1항 내지 제5항 중 어느 한 항의 배지 조성물에서 배 왜화성 대목을 배양하는 단계를 포함하는, 조직배양 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

118/1059 Row 118: application_number: 1020190162916, combined_string: invention_title: 편백나무 내장판넬을 구비한 수면캡슐장치 abstract: 편백나무 내장판넬을 구비한 수면캡슐장치가 개시된다. 개시된 편백나무 내장판넬을 구비한 수면캡슐장치는, 사용자의 신장 길이보다 수평방향으로 긴 사각박스형태로 이루어지며 일측면에 개방부를 구비한 캡슐본체와, 상기 캡슐본체와 힌지에 의해 연결되어 상방 회동동작 또는 하방회동동작에 의해 상기 개방부를 개폐하는 플랩도어로 구성된 수면캡슐; 상기 수면캡슐의 내부로 냉풍을 공급하는 냉풍기; 상기 수면캡슐의 내부로 온풍을 공급하는 온풍기;를 포함하며, 상기 냉풍기와 상기 온풍기의 구동에 따라, 상기 수면캡슐 내부의 온도가 일정하게 유지되도록 구성되며, 상기 캡슐본체는, 외관을 형성하는 금속판넬로 이루어진 골격프레임; 상기 골격프레임의 내측에 설치되어 단열이 이루어지도록 단열재; 상기 단열재의 내측에 설치되어 상기 수면캡슐의 내장재로서 기능하며, 피톤치드가 다량 함유된 편백나무 내장판넬;을 포함하는 것을 특징으로 한다. claims: 사용자의 신장 길이보다 수평방향으로 긴 사각박스형태로 이루어지며, 4개의 측면 중 사용자의 신장보다 길도록 구성된 일측면에 개방부를 구비한 캡슐본체와, 상기 캡슐본체와 힌지에 의해 연결되어 상방 회동동작 또는 하방회동동작에 의해 상기 개방부를 개폐하는 플랩도어로 구성되어 적층가능하도록 구성된 수면캡슐;상기 수면캡슐의 내부로 냉풍을 공급하는 냉풍기;상기 수면캡슐의 내부로 온풍을 공급하는 온풍기;를 포함하며, 상기 냉풍기와 상기 온풍기의 구동에 따라, 상기 수면캡슐 내부의 온도가 일정하게 유지되도록 구성되며, 상기 캡슐본체는, 외관을 형성하는 금속판넬로 이루어진 골격프레임;상기 골격프레임의 내측에 설치되어 단열이 이루어지도록 단열재;상기 단열재의 내측에 설치되어 상기 수면캡슐의 내장재로서 기능하며, 피톤치드가 다량 함유된 편백나무 내장판넬;을 포함하며, 상기 캡슐본체에는 외부공기와 내부공기가 교환되어 상기 캡슐본체 내부의 환기가 이루어지도록 하는 환풍구가 구비되며, 상기 환풍구는 상기 골격프레임과 상기 단열재에 형성된 통기공이 구성되고, 상기 캡슐본체의 외면에는 통기그릴이 설치되며, 상기 편백나무 내장판넬에는 전체영역에 다수의 환기공이 형성되도록 구성되며, 상기 편백나무 내장판넬과 상기 단열재는 서로 이격되게 설치되되, 상기 편백나무 내장판넬과 상기 단열재의 이격공간에는 상기 통기공과 상기 다수의 환기공을 연결하는 덕트부재가 설치되도록 구성되며, 상기 덕트부재는 일면에 상기 통기공과 일치하는 제1통공이 구비되고, 타면에는 상기 편백나무 내장판넬에 형성된 상기 다수의 환기공을 모두 커버하는 제2통공을 포함하도록 구성되어, 상기 통기공을 통해 상기 제1통공으로 유입된 공기가 상기 제2통공을 통해 퍼져 상기 다수의 환기공으로 전달되도록 구성되며, 상기 플랩도어의 외면에는 사용자가 파지하여 상기 플랩도어를 회동시키기 위한 손잡이부가 설치되도록 구성되며, 상기 손잡이부는 상기 플랩도어의 외면에 고정설치되는 회전지지부와, 상기 회전지지부에 대해 힌지핀에 의해 힌지가능하게 설치되며 사용자가 파지하도록 구성된 손잡이부재를 포함하도록 구성되며, 상기 손잡이부는 상기 수면캡슐을 복수개 상하로 적층하여 복수층으로 구성하는 경우, 사용자가 하층의 수면캡슐의 플랩도어에 설치된 손잡이부를 딛고 상층의 수면캡슐로 올라 입실할 수 있도록 상기 손잡이부재가 상기 플랩도어에 대해 직각되게 90도 펼쳐진 다음 더 이상 회동되지 않게 상기 손잡이부재를 지지하는 회전규제부를 더 포함하도록 구성되는 것을 특징으로 하는 수면캡슐장치., Ltext: 임업, prediction: 임업
119/1059 Row 119: application_number: 1020190160618, combined_string: invention_title: 비부착성 패류의 고밀도 인공종묘 생산용 채묘수조 abstract: 본 발명에 따른 하단부가 교체 가능한 채묘수조는 비부착성 패류의 인공종묘 생산을 위한 채묘수조에 있어서, 상기 채묘수조의 상단부가 하단부 보다 넓게 형성되고, 상기 채묘수조의 외주면은 지지대에 대응되게 형성되고, 상기 하단부에 메쉬가 위치하는 복수의 프레임이 구비될 수 있다. claims: 비부착성 패류의 인공종묘 생산을 위한 채묘수조에 있어서,상기 채묘수조의 상단부가 하단부 보다 넓게 형성되고,상기 채묘수조의 외주면은 지지대에 대응되게 형성되고,상기 하단부에 메쉬가 위치하는 복수의 프레임이 구비된, 하단부가 교체 가능한 채묘수조., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

120/1059 Row 120: application_number: 1020190160940, combined_string: invention_title: 비부착성 패류의 고밀도 인공종묘 생산용 채묘수조 abstract: 본 발명에 따른 하단부가 교체 가능한 채묘수조는 비부착성 패류의 인공종묘 생산을 위한 채묘수조에 있어서, 상기 채묘수조의 상단부가 하단부 보다 넓게 형성되고, 상기 채묘수조의 외주면은 지지대에 대응되게 형성되고, 상기 하단부에 메쉬가 위치하는 복수의 프레임이 구비될 수 있다. claims: 비부착성 패류의 인공종묘 생산을 위한 채묘수조에 있어서,상기 채묘수조의 상단부가 하단부 보다 넓게 형성되고,상기 채묘수조의 외주면은 지지대에 대응되게 형성되고,상기 하단부에 메쉬가 위치하는 복수의 프레임이 구비된, 하단부가 교체 가능한 채묘수조., Ltext: 임업, prediction: 임업
121/1059 Row 121: application_number: 1020190160436, combined_string: invention_title: 고로쇠수액 염수 제조방법 abstract: 본 발명은 고로쇠수액의 제조방법에 관한 것으로, (a) 고로쇠수액을 저장조에 충전한 후 1 ~ 10일간 정치하는 단계와; (b) 상기 정치된 고로쇠수액을 자외선 살균 및 필터링하는 단계와; (c) 상기 필터링된 고로쇠수액에 천일염 첨가하여 숙성하는 단계로 구성됨으로써, 고로쇠수액 염수를 활용하여 일반 된장, 간장에 부족한 칼슘, 칼륨, 마그네슘, 나트륨 등 각종 영양소와 미네랄을 보충하고 풍미가 개선된 고로쇠 된장, 고로쇠 간장을 대량 생산할 수 있는 효과가 있다. claims: (a) 고로쇠수액을 저장조에 충전한 후 1 ~ 10일간 정치하는 단계와;(b) 상기 정치된 고로쇠수액을 자외선 살균 및 필터링하는 단계와;(c) 상기 필터링된 고로쇠수액에 천일염 첨가하여 숙성하는 단계로 이루어지되,상기 (a)단계는 직경 10 ~ 50㎜의 세라믹 볼과 직경 3 ~ 5㎜의 마그네슘 볼을 고로쇠수액이 충전된 저장조에 충전하는 (a)-1 단계를 더 포함하되,상기 세라믹 볼은 고로쇠수액 1㎥에 대하여 세라믹 볼 50 ~ 75개를 충전하고, 마그네슘 볼은 고로쇠수액 1㎥에 대하여 1 ~ 10개를 충전하고,상기 세라믹 볼은 항균 세라믹 볼 100 중량부에 대하여, 맥반석 세라믹 볼 30 ~ 45 중량부 및 화산석 세라믹 볼 10 ~ 20 중량부로 구성되고,상기 (c)단계는,(c)-1 필터링된 고로쇠수액에 염도 21.5 ~ 23.5 보메가 되도록 천일염을 첨가한 후 교반한 다음 12 ~ 18일간 0 ~ 15℃에서 정치하여 1차 고로쇠수액 염수를 제조하는 단계와;(c)-2 상기 1차 고로쇠수액 염수의 상등액을 염도 19.5 ~ 20.8 보메가 되도록 필터링한 후 12 ~ 18일간 0 ~ 15℃에서 정치하여 2차 고로쇠수액 염수를 제조하는 단계와;(c)-3 상기 2차 고로쇠수액 염수의 상등액을 염도 17.5 ~ 18.5 보메가 되도록 필터링하여 최종 고로쇠수액 염수를 제조하는 단계로 이루어지는 것을 특징으로 하는 고로쇠수액 염수 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

122/1059 Row 122: application_number: 1020190151636, combined_string: invention_title: 커피 추출물 및 부산물에 기반한 생분해성 육묘 포트 제작 방법 및 이에 의해 제작된 생분해성 육묘 포트 abstract: 본 발명은 커피 부산물과 커피 추출물의 원료를 활용하여 육묘 포트를 형성함과 아울러 육묘 식물의 영양 성분으로 제공할 수 있어 친환경성과 경제성을 확보할 수 있고, 별도의 상토 사용 없이도 파종과 발아가 가능하며, 식재 후 생분해되어 토양에 영양분으로서 기능할 수 있는, 커피 추출물 및 부산물에 기반한 생분해성 육묘 포트 제작 방법 및 이에 의해 제작된 생분해성 육묘 포트에 관한 것이다. 본 발명에 따르면, 제1 원료로서 커피부산물 및 코코피트 중 적어도 하나, 및 제2 원료로서 펄프를 마련하는 육묘포트 원료 마련 단계; 상기 제1 및 제2 원료를 물에 투입하여 교반하고 유동화(liquefaction)하여 유동성 재료로 제조하는 유동화 단계; 상기 유동화 된 유동성 재료를 육묘 포트 형상으로 성형하기 위한 성형 단계; 및 커피 부산물로부터 추출한 상토대체물을 물과 혼합하여 상기 성형 단계에서 성형된 육묘 포트에 충전하는 상토대체물 충전 단계;를 포함하는 것을 특징으로 하는 생분해성 육묘 포트 제작 방법이 제공된다. claims: 생분해가 가능한 육모 포트(pot) 제작 방법으로서,제1 원료로서 커피부산물 및 코코피트 중 적어도 하나, 및 제2 원료로서 펄프를 마련하는 육묘포트 원료 마련 단계;상기 제1 및 제2 원료를 물에 투입하여 교반하고 유동화(liquefaction)하여 유동성 재료로 제조하는 유동화 단계;상기 유동화 된 유동성 재료를 육묘 포트 형상으로 성형하기 위한 성형 단계; 및커피 부산물로부터 추출한 상토대체물을 물과 혼합하여 상기 성형 단계에서 성형된 육묘 포트에 충전하는 상토대체물 충전 단계;를 포함하는 것을 특징으로 하는생분해성 육묘 포트 제작 방법.청구항 1 내지 청구항 5중 어느 한 항에 따른 생분해성 육묘 포트 제작 방법에 의해 제작된 생분해성 육묘 포트.커피부산물과 코코피트 중 적어도 하나 및 펄프로 이루어지는 단일 또는 트레이형의 육묘 포트 본체; 및커피부산물에서 추출한 섬유질을 포함하여 상기 육묘 포트 본체에 충전되는 상토대체물;을 포함하는 것을 특징으로 하는생분해성 육묘 포트., Ltext: 임업, prediction: 임업
123/1059 Row 123: application_number: 1020190144596, combined_string: invention_title: 건조한 지역에서 친환경적인 급수를 위한 조림장치 abstract: 본 발명은 건조한 지역에서 친환경적인 급수를 위한 조림장치에 관한 것으로서, 더 상세하게는 가뭄이 계속되거나 사막과 같은 건조지역의 들판과 연계된 경사지 등에서 초목 등의 조림을 위한 작업에서 초목에서 비산되는 수분을 친환경적으로 토지로 유도시켜 주도록 구상되는 급수장치에 관한 것이다. 일반적으로 사막화가 진행되는 지역이나, 초지 또는 준 사막화 진행되는 들판에서 극심한 가뭄이 진행되는 지역에서는 강우량의 부족으로 초목이 말라죽는 현상이 일어나고 있는 것이다. 고로 본 발명은 건조한 지역에서 친환경적인 조림을 위한 급수장치에 관한 것으로서, 건조지역이나 미세먼지가 발생되는 사막지역의 토양(65)에 매설되면서 소정의 유휴공간(다)으로 이격된 기둥(91)으로 심어진 나무(85)로 조성된 조림수(90)와, 상기 토양에 고착된 뿌리(94)에서 돌출되는 기둥(91)과, 기둥에서 성장되는 가지(97)가 다수개의 가지(97)(97a)(97b)의 잔가지(97')에서 돋아나는 잎사귀(92)와, 상기 뿌리(94)가 매설로 구비되는 조림지역에 있어서, 상기 다수개의 가지(97)(97a)(97b) 중에서 일측의 가지(97a)에 돋아나는 잎사귀뭉치(92)의 외측을 감싸주도록 내측공간(가)을 형성되는 포집포대(95)의 하측으로 돌출되는 유입부에 가지(97a)를 감싸주는 결속밴드(88)와, 상기 포집포대(95)와 결속밴드(88)의 결속하는 유입부에 결합된 지퍼(89)와, 상기 포집포대(95)의 하측으로 연결된 수분공급관(86)을, 뿌리(94)가 착토된 토양(65)에 매설되는 부숙대(80)으로 공급되도록 제공되는 발명이다.또한 상기 응축수응축관(86)에 구비되는 차단밸브(82)와,상기 토양(65)이 경사지는 구간으로 형성된 조림지역(98)에 연속 반복적으로 지지기둥(53)과 태양광발전판(50)으로 구축된 태양광발전장치(60)과, 상기 태양광발전판(50)의 하측단에 결합되도록 조립대(72)로 구비된 빗물받이(79)으로 부숙대(80)가 매설된 토양에 용수를 공급시켜 주도록 제공되는 발명이다. claims: 건조지역이나 미세먼지가 발생되는 사막지역의 토양(65)에 매설되면서 소정의 유휴공간(다)으로 이격된 기둥(91)으로 심어진 나무(85)로 조성된 조림수(90)과, 상기 조림수(90)에서 돌출되는 기둥(91)과, 기둥(91)에 분기로 성장하는 가지(97)가 다수개의 가지(97)(97a)(97b)의 잔가지(97')에서 돋아나는 잎사귀(92)가 구비됨으로서 조성된 조림지역(98)과, 상기 조림지역(98)에 형성된 유휴공간(다)의 토양(65)에는 키가 작은 관목(77)이 성장되도록 심어진 조림지역에 있어서, 상기 다수개의 가지(97)(97a)(97b) 중에서 일측의 가지(97a)에 돋아나는 잎사귀(92)의 외측을 감싸주도록 내측공간(가)을 형성되는 포집포대(95)의 하측으로 돌출되는 유입부에 가지(97a)를 감싸서 결속되는 결속밴드(88)와, 상기 포집포대(95)와 결속밴드(88)의 결속하는 유입부에 결합된 지퍼(89)와,상기 뿌리(94)가 착토된 토양(65)에 매설되는 부숙대(80)와, 상기 포집포대(95)의 하측으로 연결된 수분공급관(86)과, 상기 수분공급관(86)이 토양(65)애 매설된 구간에 급수구(89)가 천공된 용수공급관(96)으로 부숙대(80)에 용수를 공급시켜 주고, 상기 관목(77)의 잎사귀 뭉치(92)의 높이(h)에서 고정되도록 받침빔(72)으로 고정된 공기흡입관(81')을 흡입펌프(75)의 흡입력으로 토양(65)에 심어진 조림수(90)와 관목(77)의 뿌리(94)가 매설된 토양(65)에 수분공급관(96)으로 연결시켜 주도록 제공되는 건조한 지역에서 친환경적인 급수를 위한 조림장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

124/1059 Row 124: application_number: 1020190143087, combined_string: invention_title: 건조지역에서 친환경적인 조림을 위한 급수장치 abstract: 본 발명은 건조한 지역에서 친환경적인 조림을 위한 급수장치에 관한 것으로서, 더 상세하게는 가뭄이 계속되는 건조지역의 토양에서 식생되는 과수 또는 초목 등에서 비산되는 수분을 친환경적으로 포집과 아울러 급수를 위한 포집장치에 관한 발명으로서, 토양(65)에서 돌출된 지지기둥으로 조립되는 태양광발전판(50)과, 토양에 고착된 뿌리(94)에서 돌출되는 기둥(91)과, 기둥에서 성장되는 가지(97)가 다수개의 가지(97)(97a)(97b)의 잔가지(97')에서 돋아나는 잎사귀(92)와, 상기 뿌리(94)가 매설로 구비되는 초목(조림목)(85)에 있어서, 상기 다수개의 가지(97)(97a)(97b) 중에서 일측의 가지(97a)에 돋아나는 잎사귀(92)의 외측을 감싸주도록 내측공간(가)을 형성되는 포집포대(95)의 하측으로 돌출되는 유입부에 가지(97a)를 감싸시켜 주는 결속밴드(88)와, 상기 포집포대(95)와 결속밴드(88)의 결속하는 유입부에 결합된 지퍼(89)와, 상기 포집포대(95)의 하측으로 연결된 응축수응축관(86)을 부숙대(80)으로 공급되도록 제공되는 발명이다.또한 상기 큰조림수(190)의 기둥(191)에서 뻗어나는 장뿌리(194)에서 흡입된 깊숙한 토지(165)에 흐르는 지하수를, 기둥(191)에 삽입되는 흡입관(146)으로 이동시켜 주는 암거배수관(78)과, 상기 응축수응축관(86)에 구비되는 차단밸브(82)와,상기 조림수(90)용 뿌리(94)가 뻗어있는 토사에는 부숙대(80)을 암거배수관(78)으로 연결로 매설된 별도의 부숙대(80')와, 상기 부숙대(80')에 연결된 암거배수관(78)에 공급시켜 주도록, 태양광발전판(50)의 배면에다 교호상의 응축관(75')으로 구성된 응축수응축대(75)에 연결관(64)으로 연결된 암거배수관(78)으로 응축수를 공급시켜 주도록 제공되는 발명이다. claims: 배수관(76)이 매설된 토양(65)에서 돌출된 지지기둥으로 조립되는 태양광발전판(50)과, 토양에 고착되면서 기둥에 분기로 성장하는 조림수(90)의 뿌리(94)에서 돌출되는 기둥(91)에서, 가지(97)가 다수개의 가지(97)(97a)(97b)의 잔가지(97')에서 돋아나는 잎사귀(92)와, 큰조림수(90)의 기둥(191)에서 깊숙한 토지(165)에 뻗어준 장뿌리(194)와, 상기 뿌리(94)가 매설된 토사에 부숙대(80)의 매설로 구비되는 조림지역에 있어서,상기 다수개의 가지(97)(97a)(97b) 중에서 일측의 가지(97a)에 돋아나는 잎사귀(92)의 외측을 감싸주도록 내측공간(가)을 형성되는 포집포대(95)의 하측으로 돌출되는 유입부에 가지(97a)를 감싸서 결속시켜 주는 결속밴드(88)와, 상기 포집포대(95)와 결속밴드(88)의 결속하는 유입부에 결합된 지퍼(89)와, 상기 포집포대(95)의 하측으로 연결된 응축수응축관(86)을 부숙대(80)으로 공급되도록 제공되는 건조지역에서 조림을 위한 친환경적인 급수장치., Ltext: 임업, prediction: 임업
125/1059 Row 125: application_number: 1020190141644, combined_string: invention_title: ＩＣＴ 및 ＩｏＴ를 이용한 스마트 양묘 시스템, 그리고 이를 위한 하이브리드 양묘장 abstract: 본 발명은 ICT 및 IoT를 이용한 스마트 양묘 시스템, 그리고 이를 위한 하이브리드 양묘장에 관한 것이다. 본 발명은, 양묘장(10) 상단에 형성됨으로써 양묘장(10) 내부의 트레이(200)에 파종된 식물에 대해서 1년 이후 훈련장으로 옮기지 않고 위치 변동 없이 온실에 해당하는 양묘장(10)을 외부 환경으로 변경시켜 훈련시킬 수 있도록 양묘장(10)의 천장을 개방하도록 하기 위해 차양 비닐막(110)과 포켓부(120)로 구성되는 롤러장치(100); 및 포켓부(120) 내부의 권치 장치에 대한 제어를 통해 포켓부(120) 내부로 차양 비닐막(110)이 롤업 되거나 포켓부(120) 외부로 차양 비닐막(110)이 롤다운 하도록 제어하되, 양묘장(10)의 천장 개폐 구간을 비닐을 권치 장치를 이용하여 감아올린 후 양묘장(10) 탑부의 포켓부(120)로 삽입된 천장을 오픈시킴으로써, 야외 조건처럼 조성할 수 있어서 파종된 식물을 옮겨심지 않아도 노지 적응훈련시키는 것이 가능하도록 하는 제어부(460); 를 포함하는 것을 특징으로 한다.본 발명의 실시예에 따른 ICT 및 IoT를 이용한 스마트 양묘 시스템, 그리고 이를 위한 양묘장은, 천창개폐구간을 비닐을 롤업 및 롤다운을 수행하는 권취장치를 이용하여 감아올린 후 탑부의 홈부에 삽입하여 끼움으로써 완전 오픈시킴으로써, 야외 조건처럼 조성할 수 있어 파종된 식물을 옮겨심지 않아도 노지 적응훈련시키는 것이 가능하도록 하는 효과가 있고, 100% 완전 오픈 상태에서도 ICT 관리를 통해 생존율을 더 높일 수 있을 뿐만 아니라, 혹서, 동파 등의 비상 상황이 발생하는 경우 야외 노지 조건을 완화시켜 생존율을 높일 수 있도록 하며, 양묘장 내부에 파종을 위한 트레이에 RF 태그를 통해 각 트레이별 관리가 가능하고, 개개 묘목이 아니라 트레이 단위로 관리를 수행할 수 있는 효과가 있다. claims: 양묘장(10) 상단에 형성됨으로써 양묘장(10) 내부의 트레이(200)에 파종된 식물에 대해서 1년 이후 훈련장으로 옮기지 않고 위치 변동 없이 온실에 해당하는 양묘장(10)을 외부 환경으로 변경시켜 훈련시킬 수 있도록 양묘장(10)의 천장을 개방하도록 하기 위해 차양 비닐막(110)과 포켓부(120)로 구성되는 롤러장치(100); 및포켓부(120) 내부의 권치 장치에 대한 제어를 통해 포켓부(120) 내부로 차양 비닐막(110)이 롤업 되거나 포켓부(120) 외부로 차양 비닐막(110)이 롤다운 하도록 제어하되, 양묘장(10)의 천장 개폐 구간을 비닐을 권치 장치를 이용하여 감아올린 후 양묘장(10) 탑부의 포켓부(120)로 삽입된 천장을 오픈시킴으로써, 야외 조건처럼 조성할 수 있어서 파종된 식물을 옮겨심지 않아도 노지 적응훈련시키는 것이 가능하도록 하는 제어부(460); 를 포함하는 것을 특징으로 하며, 제어부(460)는, 상하로 구분된 수평/수직 유동팬(420)의 상부 수평/수직 유동팬(420-1) 및 하부 수평/수직 유동팬(420-2)에 대해서 작동 온(On) 명령을 제공함으로써 풍향이 방향이 반대 방향으로 형성된 상부 수평/수직 유동팬(420-1) 및 하부 수평/수직 유동팬(420-2)이 상부 수직 격벽 장치(420a) 및 하부 수직 격벽 장치(430b)에 의해 하나의 미리 설정된 구역에 대해서만 수평 및 수직 방향의 바람을 형성할 수 있도록 제어하고, 이후, 피드백 정보로 제 2 습도 센서(483)에 의해 측정된 습도 센싱정보가 미리 설정된 습도 미만이거나 제 2 온도 센서(484)에 의해 측정된 온도 센싱정보가 미리 설정된 온도 미만에 해당하는 경우 상부 수평/수직 유동팬(420-1) 및 하부 수평/수직 유동팬(420-2)에 대한 동작 오프(OFF)를 제어하도록 구성되는 것을 특징으로 하는 ICT를 이용한 스마트 양묘 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

126/1059 Row 126: application_number: 1020190140209, combined_string: invention_title: 새싹삼 판매 전용 쇼케이스 와 유통 시스템 abstract: 본 발명은 가전형 다기능 새싹삼 재배기를 일반 가정집이나 국내는 물론 해외의 영업 매장에 설치하고 현재 유통 되고 있는 1~2년생 새싹삼은 물론이고 깊은 산속에서나 볼 수있는 5년근 10년근 등 고가의 다년근 새싹 산양삼을 추가하여 줄기와 뿌리가 활기차게 살아 있는 새싹 산양삼을 계절에 관계없이 소비자에게 제공하는 새로운 새싹 산양삼 유통 시스템애 관한 것이다. claims: 가전형 새싹산삼 다기능 재배기와 새싹삼 유통 시스템으로서, 다기능 재배기는 재배실과 보관실을 온도 차이로 나누어 각 사용하는 기능도 있고 재배실 온도(25℃)와 보관실 온도(12℃)조절만으로 재배나 보관의 한가지 기능으로 재배실 전체를 사용할 수도 있는 복합 다기능 재배기로 일반 가정이나 국내, 해외 영업장 매장에 설치하는 단계:새싹삼을 재배하는 농장(100)에서 재배한 새싹삼이 심어진 재배틀 박스와 씨눈이 싹튼 산양삼 종묘를 식재한 재배틀 박스를 유통 업자에게 납품(200)하는 단계:유통업자는 냉장장치 자동차에 12℃ 전후의 안전한 온도로 이동하여 다기능 재배기가 설치된 가정집이나 국내 영업장, 수출업체에 납품하는 단계로 이루어지는 가전형 새싹산삼 다기능 재배기와 새싹삼 유통 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

127/1059 Row 127: application_number: 1020190139435, combined_string: invention_title: 편백오일 추출장치 및 추출방법 abstract: 본 발명은 편백오일 추출장치 및 이를 이용한 편백오일 추출방법에 관한 것으로, 그 구성은, 파쇄한 편백나무 원목을 적재할 공간이 마련되는 원료통; 상기 원료통의 상단에 구비되어 원료통 내부의 온도를 감지하는 온도계; 상기 원료통 하방으로 스팀을 공급하는 스팀발생기; 상기 원료통에서 생성된 수증기를 응축시킬 다수개의 제 1 수증기관과, 제 1 수증기관 주변에 마련되는 제 1 냉각부로 구성되는 제 1 냉각기; 상기 제 1 냉각기에 의해 생성된 제 1 응축수를 한번 더 응축시킬 나선형의 제 2 수증기관과, 제 2 수증기관 주변에 마련되는 제 2 냉각부와, 일측 하단에 냉각부를 채울 액체 또는 기체를 공급하는 공급부로 구성되는 제 2 냉각기; 상기 제 2 냉각기에서 생성된 제 2 응축수를 물과 오일로 분리시키는 오일분리기; 상기 원료통과 상기 스팀발생기를 연결하며, 일측에 제 1 밸브가 마련되는 제 1 유로; 상기 원료통과 상기 제 1수증기관을 연결하며, 일측에 제 2 밸브가 마련되는 제 2유로; 상기 제 1 수증기관과 상기 제 2 수증기관을 내부로 연결하고 상기 제 1 냉각부와 상기 제 2 냉각부를 외부로 연결하는 제 3 유로; 상기 제 2 냉각기와 상기 오일분리기를 연결하는 제 4 유로;를 포함하여 구성되는 것을 특징으로 하며, 상기 제 2 밸브는 원료통의 온도가 110 내지 115℃에 도달하면 개방하는 것을 특징으로 한다. claims: 파쇄한 편백나무 원목을 적재할 공간이 마련되는 원료통;상기 원료통의 상단에 구비되어 원료통 내부의 온도를 감지하는 온도계;상기 원료통 하방으로 스팀을 공급하는 스팀발생기;상기 원료통에서 생성된 수증기를 응축시킬 다수개의 제 1 수증기관과, 제 1 수증기관 주변에 마련되는 제 1 냉각부로 구성되는 제 1 냉각기;상기 제 1 냉각기에 의해 생성된 제 1 응축수를 한번 더 응축시킬 나선형의 제 2 수증기관과, 제 2 수증기관 주변에 마련되는 제 2 냉각부와, 일측 하단에 냉각부를 채울 액체 또는 기체를 공급하는 공급부로 구성되는 제 2 냉각기;상기 제 2 냉각기에서 생성된 제 2 응축수를 물과 오일로 분리시키는 오일분리기;상기 원료통과 상기 스팀발생기를 연결하며, 일측에 제 1 밸브가 마련되는 제 1 유로;상기 원료통과 상기 제 1수증기관을 연결하며, 일측에 제 2 밸브가 마련되는 제 2 유로;상기 제 1 수증기관과 상기 제 2 수증기관을 내부로 연결하고 상기 제 1 냉각부와 상기 제 2 냉각부를 외부로 연결하는 제 3 유로;상기 제 2 냉각기와 상기 오일분리기를 연결하는 제 4 유로;를 포함하여 구성되며,상기 제 2 냉각부가 8℃일 때, 상기 제 1 응축수를 상기 제 2 수증기관으로 이송하고,상기 제 2 밸브는 원료통의 온도가 110 내지 115℃에 도달하면 개방하는 것을 특징으로 하는 편백오일 추출장치를 이용하는 방법에 있어서,당일 벌목한 편백나무 원목을 밀봉하여 이동시키는 제 1단계;상기 밀봉하여 이동시킨 편백나무 원목을 일정한 크기로 파쇄한 뒤, 밀봉하여 이동시키는 제 2단계;상기 밀봉하여 이동시킨 파쇄된 편백나무 원목을 원료통에 적재하는 제 3단계;상기 원료통에 스팀을 공급하는 제 4단계;공급부에 냉각부를 채울 액체 또는 기체를 공급하는 제 5 단계;상기 원료통이 일정 온도에 도달하면, 원료통에서 생성된 수증기를 제 1 수증기관으로 이송하여 제 1 응축수를 제조하는 제 6 단계;상기 제 1 응축수를 제 2 수증기관으로 이송하여 제 2 응축수를 제조하는 제 7단계;상기 제 2 응축수를 오일분리기로 이송하여 물과 오일로 분리하는 제 8단계;상기 분리된 오일을 곧바로 밀봉하는 제 9단계를 포함하여 구성되며,상기 제 2단계에서, 상기 편백나무 원목은 1cm 크기로 파쇄하고,상기 제 3단계에서, 상기 원료통에 넣는 편백나무 원목은 200 내지 300Kg 를 적재하고,상기 제 4단계에서, 상기 스팀은 편백나무 원목 1중량부에 대하여 0.4 내지 0.6중량부를 공급하는 것을 특징으로 하는 편백오일 추출방법., Ltext: 임업, prediction: 임업
128/1059 Row 128: application_number: 2020210000760, combined_string: invention_title: 나무보호장치 abstract: 강풍에 나무들이나 전봇대들이 뽑히거나 부러지고 넘어져서 피해를 입는 사고가 많다. 이러한 문제들을 예방하고자 보호 장치를 땅속과 나무에 설치하여 피해를 입는 사고를 예방하고 미관상 문제도 해결하고자 한다. claims: '기초보호대' 와 '땅속지지대' 를 땅속에 설치하여 강풍에 나무가 옆으로 기울거나 뿌리가 뽑혀서 넘어지는 것의 위험으로부터 보호하는 장치.'추가보호대' 를 '기초보호대' 위에 연결 설치하여 나무 꼭대기까지 부러지지 않게 보호하는 장치.'뚜껑겸연결핀' 을 이용하여 '기초보호대' 와 '추가보호대' 를 연결하면 성장에 방해가 되지 않으면서 나무 전체가 보호되는 장치.'15도연결대' 를 옆으로 구부러졌거나 휘어진 나무에 설치하여 부러지는 것의 위험으로부터 보호하는 장치.청구항 1에 있어서, '기초보호대' 의 구조는 둥근 파이프 구조로 되어 있으며, 상단부는 3개, 혹은 4개의 통로가 중간부까지 관통할 수 있게 뚫려 있는데, 이 3개, 혹은 4개의 통로 역할로 인하여 '땅속지지대' 가 3각형, 혹은 4각형의 각도와 간격을 정확하게 잡혀서 땅속에 비스듬하게 사선으로 설치되므로 강풍이 어느 방향으로 불어오더라도 견딜 수 있게 된다.청구항 1에 있어서, '기초보호대' 하단부 끝부위는 땅속에 잘 들어갈 수 있게 뾰족하게 되어 있어서 이미 기존에 심어진 나무에는 땅을 파지 않고 말뚝처럼 박아서 설치할 수 있다.청구항 1과 청구항 2에 있어서, '기초보호대' 와 '땅속지지대' 의 길이와 넓이 사이즈는 '나무보호장치용도' 와 '전봇대보호장치' 두 종류가 있는데, 길이와 굵기만 다를 뿐 구조와 모양은 동일하다.청구항 3에 있어서, 뚜껑겸연결핀' 은 상단부는 봉해져 있어서 빗물 유입도 막아주면서 연결도 가능한 구조이고, 상단부의 면에는 식재할 때 나무의 이름과 연월일을 기록할 수도 있으며, 중간부는 '벨트' 혹은 '반도' 등으로 조여서 고정시킬 때 밑으로 처지지 않는 구조이고, 하단부는 파이프처럼 끼울 수 있는 구조이다.청구항 5에 있어서, '추가보호대' 는 스테인리스강, 강철 등과 같은 금속 종류의 재질도 되고, 또 가볍지만 부러지지 않는 PVC, 플라스틱과 같은 재질도 된다., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

129/1059 Row 129: application_number: 1020210001336, combined_string: invention_title: 휴대용 나무 안정지지대 abstract: 본 발명은 휴대용 나무 안정지지대에 관한 것으로서, 회동축(A)을 중심으로 크로스 결합된 것으로서, 땅(E)에 지지되어 이식 대기중인 나무기둥(W)을 비스듬하게 지지하는 제1지지바아(10) 및 제2지지바아(20)와; 제2지지바아(20)의 후방측에 설치되어 제1,2지지바아(10)(20)와 삼각형을 이루며 땅(E)에 지지되는 제3지지바아(30)와; 제1지지바아(10)와 제2지지바아(20) 사이에 설치되어 제1,2지지바아(10)(20) 사이의 벌어지는 각도를 구속하기 위한 각도구속부(40)와; 회동축(A) 상부측의 제1,2지지바아(10)(20)에 결합된 것으로서 나무기둥(W)의 하부면을 지지하는 기둥지지부(50);를 포함하는 것을 특징으로 한다. claims: 회동축(A)을 중심으로 크로스 결합된 것으로서, 땅(E)에 지지되어 이식 대기중인 나무기둥(W)을 비스듬하게 지지하는 제1지지바아(10) 및 제2지지바아(20);상기 제2지지바아(20)의 후방측에 설치되어 상기 제1,2지지바아(10)(20)와 삼각형을 이루며 땅(E)에 지지되는 제3지지바아(30);상기 제1지지바아(10)와 제2지지바아(20) 사이에 설치되어 상기 제1,2지지바아(10)(20) 사이의 벌어지는 각도를 구속하기 위한 각도구속부(40); 및상기 회동축(A) 상부측의 제1,2지지바아(10)(20)에 결합된 것으로서 나무기둥(W)의 하부면을 지지하는 기둥지지부(50);를 포함하는 것을 특징으로 하는, 휴대용 나무 안정지지대., Ltext: 임업, prediction: 임업
130/1059 Row 130: application_number: 1020200097407, combined_string: invention_title: 수목 보호용 밴드 abstract: 본 발명은 수목의 외주면에 설치되어 수목을 보호하기 위한 밴드로서, 보다 상세하게는 수피에 밴드를 고정하고 밴드의 외측면에 해충 기피물질이 코팅되어 해충의 접근을 막고, 밴드의 내측면에 수목에 필요한 영양성분, 살균성분, 살충성분 등의 약물이 저장되어, 상기 약물을 지속적으로 수피내로 방출함으로써 수목의 성장을 도우며 기생 및 잠복하는 해충을 퇴치하고, 약물이 수목의 형성층에 효과적으로 도달하도록 니들을 이용해 수피내로 공급하며, 지지목에 의한 수피를 보호할 수 있는 효과가 있다. claims: 수피에 부착되는 수목 보호용 밴드에 있어서,수피를 감싸도록 판형으로 형성되며 길이 방향으로 신축성을 갖는 밴드바디와,상기 밴드바디의 수목과 접하는 내측면인 제1 면에 형성되어 수피에 약물을 공급하는 약물공급부와, 상기 밴드바디의 외측면인 제2 면에 형성되며 방충 물질이 함유된 미세캡슐을 포함하는 해충기피부와,상기 밴드바디의 양끝단에 구비되어 상기 밴드바디가 수목의 외주면에 고정되도록 하는 체결부를 포함하며,상기 약물공급부는, 상기 제1 면에 적층되는 방수통기성시트와, 상기 방수통기성시트 상에 적층되고 흡수성 패드로 형성되며 적어도 하나의 약물이 수용되는 약물수용부와, 상기 제2 면으로부터 상기 밴드바디와 상기 방수통기성시트와 상기 약물수용부를 관통하고 상기 제2 면에 부착되는 지지체 상에 일정 간격으로 배열되고 상기 지지체로부터 수직으로 돌출되게 형성되어 첨단이 상기 약물수용부의 표면으로 돌출되는 적어도 하나의 니들을 구비하는 니들부를 포함하고,상기 약물은, 수목에 영양을 공급하기 위한 제1 약물, 수목에 해가 되는 균이나 바이러스를 퇴치하기 위한 제2 약물 또는 수목에 해가 되는 해충을 퇴치하기 위한 제3 약물을 포함하여 수목에 니들을 이용해 약물을 전달하는 수목 보호용 밴드., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

131/1059 Row 131: application_number: 1020200069704, combined_string: invention_title: 빗물활용 일체형 수목생장 및 보호시스템 abstract: 본 발명은 중앙에 수목이 놓이는 중공부가 형성된 빗물활용 일체형 수목생장 및 보호시스템에 있어서, 빗물이 투입되는 홈이 형성된 상판부; 상기 상판부의 하부에 부착되며, 투입된 빗물을 여과하여 여과수를 수목에 공급하기 위한 빗물여과용 여재 및 상기 여재를 수용하는 수용부를 포함하는 빗물여과모듈; 상기 빗물여과모듈의 하부에 결합되며, 여과수를 저장하는 빗물저장조, 상기 저장조의 일측에 장착되어 상기 여과수를 수목의 뿌리에 공급하기 위한 관수펌프 및 빗물공급관을 포함하는 빗물저장모듈; 및 대기정보를 획득하기 위한 대기센서부 및 토양정보를 획득하기 위한 토양센서부로 이루어진 센서부;를 포함하는 것을 특징으로 하는 빗물활용 일체형 수목생장 및 보호시스템을 제공한다. claims: 중앙에 수목이 놓이는 중공부가 형성된 빗물활용 일체형 수목생장 및 보호시스템에 있어서,빗물이 투입되는 홈이 형성된 상판부;상기 상판부의 하부에 부착되며, 투입된 빗물을 여과하여 여과수를 수목에 공급하기 위한 빗물여과용 여재 및 상기 여재를 수용하는 수용부를 포함하는 빗물여과모듈;상기 빗물여과모듈의 하부에 결합되며, 여과수를 저장하는 빗물저장조, 상기 저장조의 일측에 장착되어 상기 여과수를 수목의 뿌리에 공급하기 위한 관수펌프 및 빗물공급관을 포함하는 빗물저장모듈; 및대기정보를 획득하기 위한 대기센서부 및 토양정보를 획득하기 위한 토양센서부로 이루어진 센서부;를 포함하되,상기 빗물여과모듈의 일측에 양액공급홀이 형성되고,상기 빗물저장모듈에 상기 양액공급홀을 통해 공급되는 양액을 저장하는 양액저장조가 포함되며,상기 대기센서부 및 토양센서부는 빗물저장모듈에 형성되고,상기 빗물저장모듈은 중앙이 빈 사각형상의 이중벽으로 이루어지되, 빗물저장조, 양액저장조 및 IoT제어부로 구획되고, 상기 구획은 내벽과 외벽 및 격벽에 의해 이루어지고, 상기 대기센서부 및 토양센서부는 내벽의 일측에 부착되어지며,상기 빗물저장모듈은 빗물저장조의 내측면에 압력센서가 설치되고, 바닥면에는 발열선이 설치되어, 상기 압력센서가 빗물저장조에 저장된 여과수가 겨울철에 얼어 팽창시, 팽창과정에서 발생하는 압력을 감지하고 IoT 제어부로 신호를 전송하도록 하고, IoT 제어부는 여과수가 얼은 것으로 판단하여, 상기 빗물저장조 바닥면에 설치된 발열선을 발열시켜 얼음을 녹이고, 얼음이 녹아 감소된 압력센서로부터의 신호를 전송받아 즉시 혹은 일정시간 경과 후 관수펌프를 가동시키는 것을 특징으로 하는 빗물활용 일체형 수목생장 및 보호시스템., Ltext: 임업, prediction: 임업
132/1059 Row 132: application_number: 1020200066770, combined_string: invention_title: 수목 지지대 abstract: 본 발명은 수목 지지대에 관한 것으로서, 수목이 식수 후 뿌리를 토착할 때까지 수목이 쓰러지지 않게 안정적으로 지지할 수 있도록 함을 목적으로 한 것이다.즉, 본 발명은 수목 지지대에 있어서, 수목의 지지를 위하여 클램핑 구속할 수 있게 구비되는 수목클램프와 상기 수목클램프의 상단과 하단에 나무의 외면과 탄성 접촉되어 수목의 클램핑절단홈이 방지되게 구비되는 클램핑완충밴드, 수목의 크기에 따라 수목클램프를 조여주는 클램핑조임부 및 상기 수목클램프의 외측에 등 간격으로 3 개 내지 4 개로 결속되어 수목을 지지하는 수목지지발로 구성한 것을 특징으로 하는 것이다.따라서, 본 발명은 수목클램프에 의하여 수목지지대의 설치가 신속하게 이루어지고 작업자의 숙련도에 영향을 받지 않고 견고하게 설치되어 수목이 뿌리를 토착할 때까지 수목을 안정적으로 지지하는 효과를 갖는 것이다. claims: 수목 지지대에 있어서;수목의 지지를 위하여 클램핑 구속할 수 있게 구비되는 수목클램프와 상기 수목클램프의 상단과 하단에 나무의 외면과 탄성 접촉되어 수목의 클램핑절단홈이 방지되게 구비되는 클램핑완충밴드, 수목의 크기에 따라 수목클램프를 조여주는 클램핑조임부 및 상기 수목클램프의 외측에 등 간격으로 3 개 내지 4 개로 결속되어 수목을 지지하는 수목지지발로 구성하고;수목클램프가 수목의 성장에 따라 자동으로 벌어지게 상기 수목클램프는 수목지지발에 대응하여 3 개 내지 4 개의 판으로 분할된 분할클램프판으로 구성하고, 상기 분할클램프판은 외면에 일단으로 지지발힌지부가 결합되는 힌지결합부로 구성하고, 상기 힌지결합부의 반대 측에는 연장 형성되어 다른 분할클램프판의 힌지결합부 내면으로 끼워 결합되어 수목의 신축을 흡수할 수 있게 한 신축가동판을 형성하며, 상기 신축가동판에는 다른 분할클램프판과의 결속을 위한 신축결속핀을 형성하고, 상기 힌지결합부에는 다른 분할클램프판의 신축결속핀을 구속하고 신축가동을 가이드하는 신축가이드공을 형성하며, 상기 신축가동판의 외면과 힌지결합부의 내면에는 팽창제한마찰접속부를 형성하고;바람에 의하여 수목의 한 방향으로 작용되는 힘에 의하여 수목클램프가 신축팽창되지 않게 수목클램프의 상단과 하단에 신축제한공을 등 간격으로 형성하고, 수목지지발의 힌지부 측 상단과 하단에 수목지지발의 지지발힌지부를 지점으로한 회전에 대하여 신축제한공에 키 결합되는 신축제한키돌기를 형성한 것을 특징으로 하는 한 것을 특징으로 하는 수목 지지대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

133/1059 Row 133: application_number: 1020200059563, combined_string: invention_title: 수목용 보호덮개 조립체 abstract: 본 발명은 수목용 보호덮개 조립체에 관한 것으로서, 특히 가로수 등의 수목의 하부를 덮어 보호하는 수목용 보호덮개 조립체에 관한 것이다.본 발명의 수목용 보호덮개 조립체는, 중공 사각형상의 프레임부재와; 상기 프레임부재의 안쪽에 장착되고, 안쪽에 반원형상의 장착공이 각각 형성된 한 쌍의 외측커버와; 원호형상으로 이루어져 상기 장착공에 결합되고, 안쪽에 수목이 관통하는 반원형상의 관통공이 형성된 한 쌍의 내측커버;를 포함하여 이루어지되, 상기 외측커버의 내주부의 하부에는 제1받침돌기가 돌출 형성되어 상기 장착공이 장착되는 상기 내측커버의 하부를 지지하고, 상기 내측커버의 외주부의 상부에는 제2받침돌기가 돌출 형성되고 상기 제2받침돌기는 상기 외측커버의 상면에 걸려 상기 내측커버의 하방향 이동을 저지시키며, 상기 내측커버의 외주부의 하부에는 제3받침돌기가 돌출 형성되고 상기 제3받침돌기는 상기 외측커버의 하면에 걸려 상기 내측커버의 상방향 이동을 저지시키는 것을 특징으로 한다. claims: 중공 사각형상의 프레임부재와;상기 프레임부재의 안쪽에 장착되고, 안쪽에 반원형상의 장착공이 각각 형성된 한 쌍의 외측커버와;원호형상으로 이루어져 상기 장착공에 결합되고, 안쪽에 수목이 관통하는 반원형상의 관통공이 형성된 한 쌍의 내측커버;를 포함하여 이루어지되,상기 외측커버의 내주부의 하부에는 제1받침돌기가 돌출 형성되어 상기 장착공이 장착되는 상기 내측커버의 하부를 지지하고,상기 내측커버의 외주부의 상부에는 제2받침돌기가 돌출 형성되고 상기 제2받침돌기는 상기 외측커버의 상면에 걸려 상기 내측커버의 하방향 이동을 저지시키며,상기 내측커버의 외주부의 하부에는 제3받침돌기가 돌출 형성되고 상기 제3받침돌기는 상기 외측커버의 하면에 걸려 상기 내측커버의 상방향 이동을 저지시키고,상기 장착공의 양끝단에는 외측방향으로 걸림홈이 하방향으로 오목하게 형성되고, 상기 걸림홈은 상기 장착공의 내측방향과 이와 직교되는 수평방향 및 상방향으로 개방 형성되며,상기 내측커버의 양끝단에는 상기 걸림홈에 삽입되는 걸림돌기가 외측방향으로 돌출 형성되어,상기 걸림홈에 삽입된 걸림돌기에 의해 상기 외측커버에 대한 상기 내측커버의 수평방향 회전이 저지되며,상기 제3받침돌기는,상기 내측커버의 양끝단의 하부에서 외측방향으로 돌출 형성된 한 쌍의 제3-1받침돌기와;한 쌍의 상기 제3-1받침돌기 사이에 배치되고, 상기 내측커버의 외주부의 하부에서 외측방향으로 돌출 형성된 제3-2받침돌기;로 이루어지되,상기 제3-1받침돌기는 상기 내측커버의 양끝단 하부에 장착되면서 측면에 수평방향으로 지지면을 형성하고,한 쌍의 상기 내측커버는 상기 장착공에 장착된 상태에서 상기 제3-1받침돌기의 지지면이 서로 인접하게 대면하여 한 쌍의 상기 내측커버가 수평방향으로 서로 지지되면서 회전되거나 흔들리는 것을 방지하며,상기 외측커버는 안쪽에 반원형상의 상기 장착공이 형성되면서 수평방향으로 배치되어 상호 결합되는 제1외측커버와 제2외측커버로 이루어지며,상기 제1외측커버에는 상기 제2외측커버 방향으로 결합돌기가 돌출 형성되고,상기 제2외측커버의 상면에는 상기 결합돌기가 안착되는 결합홈이 형성되며,상기 결합돌기에는 상하방향으로 제1관통공이 형성되고, 상기 결합홈에는 상하방향으로 제2관통공이 형성되며,상기 제1관통공은 상기 제2관통공보다 큰 직경을 갖고,상기 결합돌기의 상면에는 끼움부재가 배치되고, 상기 끼움부재에는 상기 제1관통공에 안착되는 끼움돌기부가 하방향으로 돌출 형성되며,상기 끼움돌기부에는 상기 제1관통공 및 제2관통공과 연통되는 장공형상의 제3관통공이 형성되고,머리부가 상기 끼움돌기부의 안쪽에 안착되면서 끝단이 상기 제3관통공, 제1관통공 및 제2관통공을 관통하는 볼트에 의해 상기 제1외측커버와 제2외측커버는 상호 결합되는 것을 특징으로 하는 수목용 보호덮개 조립체., Ltext: 임업, prediction: 임업
134/1059 Row 134: application_number: 1020200047680, combined_string: invention_title: 조경 자생환경 시스템 abstract: 본 발명은 조경 자생환경 시스템에 관한 것으로서, 보다 상세하게는 지중에 매립되어 조경수의 뿌리의 하부에 위치하는 열발생모듈과 열발생모듈을 둘러싸되 소정의 경사를 이루는 측벽으로 형성된 단열반사막과 조경수의 하부에 설치되어 열발생모듈의 열을 지중으로 반사시키는 보온커버부 및 지중의 온도를 감지하여 열발생모듈의 작동을 제어하는 토양온도센서가 구비된 제어부를 포함하는 조경 자생환경 시스템에 관한 것이다. claims: 내부에 전열선이 매립되는 판으로 형성되고 상기 판을 둘러싸는 고정틀이 형성되어 지중에 매립되며, 조경수의 뿌리의 하부에 위치하는 열발생장치와 상기 열발생장치의 하부에 단열재를 구비한 보온층과 상기 열발생장치의 상부와 상기 보온층의 하부에 각 위치하는 금속보호판 및 상기 지중으로 유입되는 수분을 상기 열발생장치의 하부로 배수시키는 배수부를 포함하여 형성된 열발생모듈;상기 열발생모듈을 둘러싸되 소정의 경사를 이루는 측벽으로 형성되어 상기 조경수의 뿌리의 크기에 대응하여 상기 측벽의 경사를 조절하는 단열반사막;상기 조경수의 하부에 설치되어 상기 열발생모듈의 열을 지중으로 반사시키는 보온커버부; 및지중의 온도를 감지하여 상기 열발생모듈의 작동을 제어하는 토양온도센서가 구비된 제어부를 포함하고,상기 배수부는상기 열발생장치와 상기 보온층과 상기 금속보호판의 일면을 관통하여 서로 연통하는 홀을 복수개로 형성한 배수홀;상기 배수홀에 삽입되는 관으로 형성되어 상기 열발생장치의 상부에 위치한 상기 금속보호판의 일면으로 유입된 수분을 하부로 이동시키고, 상기 관의 상부에 플랜지가 형성된 배수관; 및상기 배수관의 하부에 나선 결합되어 상기 배수관이 상기 열발생장치에 견고하게 위치시키는 볼트를 포함하는 것을 특징으로 하는조경 자생환경 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

135/1059 Row 135: application_number: 1020200041251, combined_string: invention_title: 수목 보호 구조물 abstract: 본 발명은 특히 수목 주변 토양의 급격한 온도 변화를 완화하고 토양 내 보습력을 향상시킬 수 있는 수목 보호 구조물에 관한 것으로, 복수의 지지대; 및 상기 복수의 지지대에 의해 지지되어 상기 복수의 지지대를 둘러싸는 차광망을 포함한다. claims: 복수의 지지대; 및상기 복수의 지지대에 의해 지지되어 상기 복수의 지지대를 둘러싸는 차광망을 포함하는 수목 보호 구조물., Ltext: 임업, prediction: 임업
136/1059 Row 136: application_number: 2020200001006, combined_string: invention_title: 수목의 지주목 abstract: 개시된 본 고안에 따른 수목의 지주목은, 수목의 둘레를 따라 받칠 수 있게 방사상으로 배치되며, 상단에 적어도 하나의 지주 구멍이 형성되고, 땅속에 묻히는 지주 받침이 하단에 구비되는 지주부; 및 상기 지주 구멍에 삽입되어 상기 지주부의 상단을 연결하는 연결부;를 포함한다. 본 고안에 따른 수목의 지주목은, 지주부의 상단 및 중간 부분마다 지주 구멍이 형성되어 대향 배치된 지주부를 연결부를 통해 견고하게 연결 가능하고, 하단에 땅속에 묻히는 지주 받침이 지주부와 교차 구비되어 바람이 강하게 불면서 지주목이 지면에서 솟아오르거나 이탈됨을 방지 가능하고, 수피에 햇빛이 잘 들고 물관의 흐름을 좋게 하고, 뿌리 쪽으로 오는 빗물의 도달을 도우며, 시공이 간편하고 경제적인 효과가 있다. claims: 수목(10)의 둘레를 따라 받칠 수 있게 방사상으로 배치되며, 상단에 적어도 하나의 지주 구멍이 형성되고, 땅속에 묻히는 지주 받침(116)이 하단에 구비된 지주부(110); 및상기 지주 구멍에 삽입되어 상기 지주부(110)의 상단을 연결하는 연결부(120);를 포함하며,상기 지주 받침(116)의 중앙에는 상부에 반원홈(1162)이 형성된 몸체(1160)가 삽입결합되고,상기 몸체(1160)의 반원홈(1162) 내주면에는 다수의 반구홈(1164)이 일정 간격으로 이격되어 형성되며,상기 지주부(110)의 하단 단면은 상기 지주부(110)의 하단에 구비된 힌지(H)를 중심으로 상기 반원홈(1162) 내부에서 회동 가능하도록 상기 반원홈(1162)과 대응되는 반원형으로 형성되고,상기 지주부(110) 하단에는 홈부(G)가 형성되며,상기 홈부에는 탄성부재(118b)가 삽입 구비되고, 상기 탄성부재(118b)는 끝단에 구비된 구부재(118a)를 가압하여 상기 반구홈(1164) 내부로 삽입되도록 하며,상기 구부재(118a)는 각도가 변경되도록 상기 힌지(H)를 중심으로 상기 지주부(110)를 회동작동시 상기 반구홈(1164) 중 하나의 반구홈(1164)로부터 상기 탄성부재(118b)에 의하여 가압되는 상태로 이탈되어 이동한 후 상기 탄성부재(118b)의 가압에 의하여 이웃하는 반구홈(1164)에 삽입되는 것을 특징으로 하는 수목의 지주목., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

137/1059 Row 137: application_number: 1020190177295, combined_string: invention_title: 수목 생물적 방제를 위한 다목적 천적 방사기 abstract: 본 발명은 용기 본체의 전면부에 제1 천적의 알을 산란할 수 있는 천적유지식물을 배치하여 제1 천적이 지속적으로 산란함으로서 당해 수목으로 지속적으로 천적이 유입될 수 있도록 하며, 이와 더불어 하단부에 개폐가 용이한 비가림 구조의 제2 천적인 포식성 응애류 천적을 수납할 수 있는 공간을 구성하여 다양한 해충발생시 선택적으로 천적을 운영할 수 있도록 하며, 방사된 천적이 안정적으로 생존하고 수목으로 이동할 수 있도록 하는 물리적 특성을 가진 수목 부착형 다목적 천적방사기에 관한 것이다. claims: 천적유지식물를 포함한 수목에 부착 가능한 용기 본체;상기 용기 본체의 전면부에 배치되고, 제1 천적의 알을 산란할 수 있는 천적유지식물이 함께 제공되며 천적유지 식물의 상단부와 연결된 제1 천적을 수납할 수 있는 비가림 구조의 방사장치 및,상기 용기 본체의 하부측에 배치되어 비가림 기능이 있고 손쉽게 개폐가 가능한 제2 천적의 수납공간으로 여러 가지 해충 방제에 효과가 있는 포식성 응애류 천적과 그 먹이곤충을 수시로 공급할 수 있는 방사장치. 상기 용기 본체의 제1 천적과 제2 천적을 안정적으로 수납할 수 있는 수목 부착형 방사장치., Ltext: 임업, prediction: 임업
138/1059 Row 138: application_number: 1020190171077, combined_string: invention_title: 접합식물체 생산방법 및 이에 의해 생산된 접합식물체 abstract: 본 발명은 최소한 하나의 나무 개체가 다른 하나의 나무 개체 줄기를 관통한 관계인 접합식물체의 생산방법 및 이에 의해 생산된 접합식물체에 관한 것으로서, 보다 상세하게는 제1나무 개체의 줄기 또는 가지에 관통공을 형성하는 관통공형성단계; 및 제2나무 개체의 줄기 또는 가지를 제1나무 개체의 관통공으로 통과시키는 관통배치단계;를 포함하는 접합식물체 생산방법 및 이에 의해 생산된 접합식물체에 관한 것이다. claims: 제1나무 개체의 줄기 또는 가지에 관통공을 형성하는 관통공형성단계;제2나무 개체의 줄기 또는 가지를 제1나무 개체의 관통공으로 통과시키는 관통배치단계;를 포함하는 것을 특징으로 하는 접합식물체 생산방법.청구항 1 내지 3 중 어느 한 항에 의한 생산방법에 의해 생산된 접합식물체., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

139/1059 Row 139: application_number: 1020190137139, combined_string: invention_title: 수목지지구조와 그 방법 abstract: 본 발명은 수목지지구조와 그 방법에 관한 것으로, 수목의 뿌리분을 감싸는 그물망과, 상기 뿌리분이 안착되는 평판 형태의 지지판 및 상기 지지판과 상기 그물망을 연결, 고정하는 로프를 포함하여 수목지지수단이 지중에 매설됨으로써 수목 주위의 경관을 향상시키고 보행자의 통행이 용이할 뿐 아니라 수목지지수단의 철거 작업이 불필요하여 인력과 비용을 절감할 수 있는 수목지지구조와 그 방법을 제공한다. claims: 수목의 뿌리분을 감싸는 그물망과;상기 뿌리분이 안착되는 평판 형태의 지지판; 및상기 지지판과 상기 그물망을 연결, 고정하는 로프;를 포함함으로써 상기 지지판이 상기 뿌리분과 함께 지중에 매립되어 상기 수목을 지지하도록 한 것을 특징으로 하는 수목지지구조.(a) 수목의 뿌리분을 그물망으로 감싸는 단계와;(b) 그물망으로 감싼 뿌리분을 평판 형태의 지지판에 안착시키는 단계와;(c) 상기 지지판과 상기 그물망을 로프로 연결, 고정하는 단계; 및(d) 상기 지지판을 상기 뿌리분과 함께 지중에 매립하는 단계;를 포함하는 수목지지방법., Ltext: 임업, prediction: 임업
140/1059 Row 140: application_number: 1020190129091, combined_string: invention_title: 친환경적인 조림장치 abstract: 본 발명은 친환경적인 조림장치에 관한 것으로서, 더 상세하게는 가뭄이 계속되거나 겨울철이나 혹한지역에서 조림을 위한 동파반지 또는 사막과 같은 건조지역 등에서 비산되는 수분을 친환경적으로 산림에 대한 성장을 보강시켜 주는 조림장치에 관한 것이다. 일반적으로 사막화와 같은 건조지역에서도 새벽녘에는 이슬과 같은 응축수가 형성되는 것이다. 이는 사막화가 진행되는 지역이나, 혹한지에서 초지 또는 야산과 같은 들판에서 극심한 추위가 진행되는 지역에서는, 식생하는 초목(나무)의 냉해로 많은 손실이 발생하는 것이다. 고로 지중의 토양(70)에 깊숙이 뿌리(83)로 고정하면서 지상으로 성장되는 나무용 기둥(81)과, 상기 기둥(81)의 일측으로 구비된 태양광발전판(42)과, 상기 토양(70)에 깊숙이 뿌리(83)로 고정하면서 지상으로 성장되는 나무용 기둥(81)의 가지에 돋아나는 잎사귀(87)와, 상기 잎사귀(87)을 둘러싸여서 내측공간(55)이 형성되도록 다수개의 원주형 고정링(66)과, 상기 원주형 고정링(66)을 지지되는 지지대(68)으로 구비되는 원통형의 포집포대(60)과, 상기 포집블럭(40)의 외측면을 감싸주는 포집블럭(40)으로 형성되는 내측공간(55)에 있어서, 상기 토양(70)에 고정되는 뿌리(83) 부근에 매설되는 부숙재(49)와, 상기 뿌리(83)와 부숙재(49)를 감싸주는 보온망태(74)와,상기 태양광발전판(42)의 배면에 일체되는 응축수 포집판(51)과, 상기 응축수 포집판(51)에서 파이프(46)로 연결되는 부숙탱크(78)과, 상기 부숙탱크(78)에서 공급되는 가열공기를 토양(70)으로 감싸주는 보온망태(74)로 공급시켜 주도록 이송관(48)이 제공되는 발명이다. claims: 지중의 토양(70)에 깊숙이 뿌리(83)로 고정하면서 지상으로 성장되는 나무용 기둥(81)과, 상기 기둥(81)의 일측으로 구비된 태양광발전판(42)과, 상기 나무용 기둥(81)에서 자라나는 가지에서 돋아나는 잎사귀(87)와, 상기 잎사귀(87)을 둘러싸여 주는 포집포대(60)의 내측공간(55)이 형성되도록 다수개의 원주형 고정링(66)과, 상기 원주형 고정링(66)을 지지되는 지지대(68)으로 구비되는 원통형의 포집포대(60)과, 상기 포집포대(60)의 외측면을 감싸주는 포집블럭(40)으로 형성되는 친환경적인 조림장치에 있어서, 상기 토양(70)에 고정되는 뿌리(83) 부근에 매설되는 부숙재(49)와, 상기 뿌리(83)와 부숙재(49)를 감싸주는 보온망태(74)와,상기 태양광발전판(42)의 배면에 이동간격(47)이 구비되도록 응축수 포집판(51)으로 일체된 태양광발전장치(53)와, 상기 응축수 포집판(51)에서 파이프(46)로 연결되는 부숙탱크(78)과, 상기 부숙탱크(78)에서 공급되는 가열공기를 토양(70)으로 감싸주는 보온망태(74)로 공급시켜 주도록 이송관(48)이 제공되는 친환경적인 조림장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

141/1059 Row 141: application_number: 1020190125967, combined_string: invention_title: 연결관이 구비되는 유공관 abstract: 본 발명은 연결관이 구비되는 유공관에 관한 것으로, 일반적인 토양이나, 배수가 불량한 혐기성 토양에 설치되어 수목 뿌리의 호흡작용을 돕고, 호기성 토양으로의 변환을 도와 수목에게 유리한 미생물들의 생육 환경을 조성하여 수목의 발육을 촉진하도록 수목의 주변 토양 내에 수직방향으로 설치되는 유공관의 외주연에 다수개의 결합편을 하나의 군 단위로 돌출형성하고, 하나의 군 단위로 돌출형성된 결합편에 연결관의 결합홈이 탈착가능하게 결합됨으로써 유공관에 설치된 연결관의 위치 변경이 자유로울 뿐만 아니라, 별도의 이음관이 요구됨이 없이 유공관에 다수개의 연결관의 연결설치가 가능하며, 하나의 군 단위로 돌출형성되는 결합편들의 중심부에 동심원 상으로 투수공이 형성되어 유공관에 연결관의 연결 시 동심원 상으로 관통형성되는 투수공을 통해 유공관의 물 및 공기가 연결관으로 유입 및 순환되도록 하는 연결관이 구비되는 유공관을 제공하기 위한 것이다. claims: 식재된 수목 주변의 토양 내에 수직방향으로 적어도 하나 이상으로 설치되되, 내부에 중공을 갖는 관 형상체로서, 외주연에 돌출형성되는 적어도 하나 이상의 결합부, 및 외주연에 관통형성되는 적어도 하나 이상의 투수공을 포함하는 유공관; 및상기 각 유공관 사이에 배치되되, 그 일측 및 타측이 각 유공관에 결합되어 각 유공관을 상호 연결하며, 외주연에 적어도 하나 이상의 투수공이 관통형성되고, 내부에 중공을 갖는 관 형상체로서, 중심부에 일정 길이를 갖되, 원통형상으로 형성되는 본체와, 상기 본체의 양 단부에 구비되되, 자바라 형태의 주름진 관으로 형성되는 신축관, 및 상기 신축관의 각 단부에 플랜지 형태로 형성되되, 일측면 단부에 상기 유공관의 결합부가 삽입결합되도록 적어도 하나 이상의 결합홈을 갖는 결합관을 포함하는 연결관;을 포함하여 구성되고,상기 결합부는 핀 형태로 형성되되, 상기 유공관의 외주연에 형성되는 연결편, 및 상기 연결편의 단부에 형성되되, 연결편의 직경보다 큰 직경을 갖는 결합편을 포함하고, 상기 결합홈은 ㅓ자 형태로 형성되되, 입구측 직경이 상기 결합부의 연결편 직경과 동일 또는 약간 크게 형성되고, 상기 결합홈의 내부측 직경이 상기 결합부의 결합편 직경에 대응되게 형성되며,상기 결합편은 그 길이방향 양 단부 가장자리가 라운드 형태로 형성되고, 상기 결합홈 내의 입구측에서 내측을 향하여 직경의 크기가 달라지도록 라운드 형태로 형성되며, 상기 결합편을 결합홈에 인입 또는 인출 시 라운드 형태로 형성되는 결합편의 양 단부가 결합홈의 입구측에 맞닿아 슬라이딩하면서 변형되어 결합홈의 입구측을 통과하도록 이루어지며,상기 유공관의 외주연에 돌출형성되는 결합부는 마름모꼴 형태를 이루는 상, 하, 좌, 우 4개를 하나의 군으로 형성하고, 상기 하나의 군으로 형성되는 4개의 결합부 중심부에 원호를 그리면서 동심원 형태로 다수개의 투수공이 배치되며, 상기 결합홈은 연결관의 결합관 단부 상, 하, 좌, 우에 각각 형성되며,상기 연결관의 결합관 단부에 형성되는 각 결합홈 사이에는 1/4 원호 형태의 밀폐홈이 각각 형성되고, 상기 각 밀폐홈에는 밀폐부재가 삽입설치되되, 상기 밀폐부재는 합성수지재질로 이루어지되, 단면이 H자 형상으로 형성되고, 상기 밀폐홈은 상기 밀폐부재의 형상에 대응되도록 형성되되, 입구의 크기가 그 내부의 크기보다 작게 형성되며,상기 밀폐부재의 일측 단부는 밀폐홈의 입구 및 내부에 결합되고, 그 타측 단부는 밀폐홈의 외부로 노출 및 돌출되게 결합되되, 유공관의 외주연에 맞닿게 설치되는 것을 특징으로 하는 연결관이 구비되는 유공관., Ltext: 임업, prediction: 임업
142/1059 Row 142: application_number: 1020190123699, combined_string: invention_title: 왜성 체리나무 재배방법 abstract: 본 발명은 재배 관리 및 과실 수확이 용이한 왜성 체리나무 재배방법에 관한 것으로, 흙 10~30 중량부와, 마사토 20~40중량부와, 소나무톱밥 35~55중량부와, 미강 40~60중량부를 혼합한 배양토를 상향 개방의 부직포 화분(2)에 채운 다음 대목에 접목된 체리나무(3)를 심어 관수 재배 및 전지함으로써 1.6~2.2m 수고(樹高)의 왜성 체리나무(3)로 재배되어 사다리나 받침대 없이도 재배 관리가 쉬울 뿐 아니라 과실(39)을 쉽게 수확할 수 있으며, 관상수로 키울 수도 있다.상기 전지는, a) 식재 후 10월~11월 무렵 접목 부위에서 20~40㎝ 올라간 접수 부분을 전지하고, b) 식재 1년 후 5~8개의 원 가지를 받아 기른 다음 가을이나 이듬해 봄에 20~40㎝ 남기고 전지하고, c) 식재 후 2년차에 원 가지에서 새로 나온 가지 20~40㎝ 위를 전지하고 곁가지 나온 것을 정리하고, d) 원 가지에서 새로 나온 가지의 20~40㎝ 위를 전지하고 곁가지도 전지하여 최종 수고가 1.6~2.2m가 되는 와인잔 형상의 체리나무(3)를 재배할 수 있다. 본 발명은 노지 또는 시설재배지에 대목에 접목된 체리나무(3)를 심어 관수 재배 및 전지함으로써 1.6~2.2m 수고(樹高)의 왜성 체리나무(3)로 재배할 수도 있다. claims: 부직포 화분에 배양토를 채워 넣고 대목에 접목된 체리나무를 식재하여 전지 재배하되, 상기 배양토는, 흙 10~30 중량부와 마사토 20~40중량부와 톱밥 35~55중량부와 미강 40~60중량부를 혼합한 것이고, 상기 전지는, a) 식재 후 10월~11월에 접목 부위에서 20~40㎝ 올라간 접수 부분을 전지하고, b) 식재 1년 후 5~8개의 원 가지를 기른 다음 가을이나 이듬해 봄에 20~40㎝ 남기고 전지하고, c) 식재 후 2년차에 원 가지에서 새로 나온 가지 20~40㎝ 위를 전지하고 곁가지 나온 것을 정리하고,d) 원 가지에서 새로 나온 가지의 20~40㎝ 위를 전지하고 곁가지도 전지하여 최종 수고가 1.6~2.2m인 왜성 체리나무 재배방법.노지 또는 시설재배지에 대목에 접목된 체리나무를 식재하여 전지 재배하되, 상기 노지 또는 시설재배지에 구덩이를 판 다음 구덩이에 부직포 화분을 투입한 다음 흙 10~30중량부와 마사토 20~40중량부와 톱밥 35~55중량부와 미강 40~60중량부를 혼합한 배양토를 넣으면서 대목이 접목된 체리나무를 식재하여 재배하고,상기 전지는,a) 식재 후 10월~11월에 접목 부위에서 20~40㎝ 올라간 접수 부분을 전지하고, b) 식재 1년 후 5~8개의 원 가지를 기른 다음 가을이나 이듬해 봄에 20~40㎝ 남기고 전지하고, c) 식재 후 2년차에 원 가지에서 새로 나온 가지 20~40㎝ 위를 전지하고 곁가지 나온 것을 정리하고,d) 원 가지에서 새로 나온 가지의 20~40㎝ 위를 전지하고 곁가지도 전지하여 최종 수고가 1.6~2.2m인 왜성 체리나무 재배방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

143/1059 Row 143: application_number: 1020190122985, combined_string: invention_title: 토양미생물 발효수를 이용한 금화규 재배방법 abstract: 본 발명은 토양미생물 발효수를 이용한 금화규 재배방법에 관한 것으로, (a) 금화규의 노지 이식후부터 개화 5일전까지 3일 간격으로 토양미생물 발효수를 하루 한 번씩 금화규 줄기에 분무하는 단계와; (b) 금화규의 꽃잎 채취 다음날부터 20일간 3일 간격으로 하루 복수 회 금화규 씨방에 토양미생물 발효수를 분무하는 단계와; (c) 씨방 채취 10일후부터 토양미생물 발효수를 5일 간격으로 하루 한 번씩 금화규 줄기에 분무하는 단계로 구성됨으로써, 토양미생물인 바실러스 베레젠시스를 이용하여 유기물을 발효한 천연 액비를 활용하여 인체에 무해한 친환경 농법으로 금화규를 대량 생산할 수 있는 효과가 있다. claims: 금화규의 줄기에 토양미생물 발효수를 분무하여 금화규를 재배하되,상기 토양미생물 발효수는,(A) 천연 유기물 100 중량부에 대하여, 정제수 100 ~ 500 중량부, 토양미생물 0.01 ~ 15 중량부를 밀폐용기에 충전 혼합한 후 30 ~ 42℃에서 2 ~ 6개월 발효한 다음 여과하여 1차 발효물을 제조하는 단계와;(B) 상기 1차 발효물 100 중량부에 대하여, 정제수 50 ~ 30,000 중량부를 첨가한 후 45 ~ 55℃에서 5 ~ 8시간 가열하여 2차 발효물을 제조하는 단계로 제조되고,상기 천연 유기물은 풀, 나무잎, 볏짚, 과일, 채소 및 음식 찌꺼기 중 어느 하나 이상이고,상기 토양미생물은 바실러스 서브틸리스 아종 서브틸리스, 바실러스 벨레젠시스, 바실러스 베레젠시스 중 어느 하나인 것을 특징으로 하는 토양미생물 발효수를 이용한 금화규 재배방법.(a) 금화규의 노지 이식후부터 개화 5일전까지 3일 간격으로 토양미생물 발효수를 하루 한 번씩 금화규 줄기에 분무하는 단계와;(b) 금화규의 꽃잎 채취 다음날부터 20일간 3일 간격으로 하루 복수 회 금화규 씨방에 토양미생물 발효수를 분무하는 단계와;(c) 씨방 채취 10일후부터 토양미생물 발효수를 5일 간격으로 하루 한 번씩 금화규 줄기에 분무하는 단계로 이루어진 토양미생물 발효수를 이용한 금화규 재배방법., Ltext: 임업, prediction: 임업
144/1059 Row 144: application_number: 1020190122229, combined_string: invention_title: 튜브형 수목 물주머니 abstract: 본 발명은 튜브형 수목 물주머니에 관한 것으로, 내부에 물을 채우기 위한 공간이 형성되고, 내부에 물이 채워지는 경우 수목을 감싸도록 튜브 형상을 갖도록 마련되되, 일부가 끊어진 반 튜브 형상을 갖도록 마련된 반 튜브 팩과; 상기 반 튜브 팩의 끊어진 양측 가장자리를 연결하며, 상기 반 튜브 팩이 수목에 감길 때 수목의 두께에 따라 길이를 조절하기 위한 길이 조절 유닛과; 상기 반 튜브 팩으로부터 연장되어 수목에 물을 공급하기 위한 물 공급 튜브를 포함하는 것을 특징으로 한다. 이에 따라, 튜브 형상의 반 튜브 팩에 물이 채워진 상태에서 수목의 둘레를 감싸듯이 반 튜브 팩이 수목에 설치되어, 무게 중심의 분산으로 인해 수목의 생장에 끼치는 영향을 최소화할 수 있게 된다. 또한, 수목을 감싸는 형태로 수목에 설치되어 단순히 거치하거나 일측에 묶어놓은 형태의 종래의 물주머니와 대비할 때 미관이 끼치는 영향을 최소화할 수 있게 된다. claims: 튜브형 수목 물주머니에 있어서,내부에 물을 채우기 위한 공간이 형성되고, 내부에 물이 채워지는 경우 수목을 감싸도록 튜브 형상을 갖도록 마련되되, 일부가 끊어진 반 튜브 형상을 갖도록 마련된 반 튜브 팩과;상기 반 튜브 팩의 끊어진 양측 가장자리를 연결하며, 상기 반 튜브 팩이 수목에 감길 때 수목의 두께에 따라 길이를 조절하기 위한 길이 조절 유닛과;상기 반 튜브 팩으로부터 연장되어 수목에 물을 공급하기 위한 물 공급 튜브를 포함하는 것을 특징으로 하는 튜브형 수목 물주머니., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

145/1059 Row 145: application_number: 1020190116673, combined_string: invention_title: 친환경적인 식물 세척, 식물 영양 공급 및 토양 오염물질 제거용 영양 크리너 조성물 및 이의 제조방법 abstract: 본 발명의 일 예에 따른 영양 크리너 조성물은 락토바실러스 플란타럼(Lactobacillus plantarum) 배양액, 질소 함유 물질, 칼륨 함유 물질, 닥나무 잿물, 식물의 생장에 필요한 미량 원소 함유 물질, 닥나무 농축액, 식물 생장 조절제, 양이온계 중화제 및 음이온계 중화제를 포함한다. 본 발명의 일 예에 따른 영양 크리너 조성물은 구성성분으로 통상적으로 사용되는 계면활성제나 인산 등과 같은 산도 조절제 대신 한지의 제조 공정 중에 버려지는 부산물의 가공에 의해 수득한 닥나무 잿물 및 닥나무 농축액을 포함하기 때문에 경제성과 환경성을 동시에 충족시킬 수 있다. 또한, 본 발명의 일 예에 따른 영양 크리너 조성물은 공해에 오염된 식물체의 세척, 식물에 필요한 영양분의 공급, 토양 내에 과다 축적된 염분, 제설제 등과 같은 토양 오염 원인 물질의 제거, 산도 교정 효과가 우수할 뿐만 아니라 토양의 물리화학적 성질을 변경하여 식물의 생장에 유리하도록 토양을 개량할 수 있는 효과 또한 뛰어나다. claims: 전체 중량을 기준으로 락토바실러스 플란타럼(Lactobacillus plantarum) 배양액 35~55 중량%, 질소 함유 물질 15~35 중량%, 칼륨 함유 물질 6~20 중량%, 닥나무 잿물 0.5~6 중량%, 식물의 생장에 필요한 미량 원소 함유 물질 1~6 중량%, 닥나무 농축액 3~16 중량%, 식물 생장 조절제 0.2~3 중량%, 양이온계 중화제 0.1~2 중량% 및 음이온계 중화제 0.1~2 중량%를 포함하는 조성물로서,상기 닥나무 잿물은 수피(樹皮)가 제거된 닥나무 줄기를 건조시키고 900~1300℃의 가열로에서 연소시켜 재(ash) 형태의 연소물을 수득하고, 상기 연소물을 물(water) 1L를 기준으로 0.05~0.2L의 양으로 첨가하고 물(water)의 온도를 50~80℃로 유지하면서 2~10 hr 동안 교반한 후 여과하여 잔사를 제거한 것이고,상기 닥나무 농축액은 닥나무 1L를 기준으로 물(water) 1.2~2.5L와 함께 밀폐된 상태에서 400~700℃의 온도를 유지하며 12~24 hr 동안 삶은 후 닥나무를 건져서 분리하고 삶은 물을 12~24 hr동안 가열하여 물을 증발시키고 최초 물(water) 부피의 1/10 내지 1/2 수준으로 농축시킨 것이며,상기 조성물은 살아있는 식물체의 표면에 존재하는 오염물질의 세척, 식물의 생장에 필요한 영양분의 공급, 토양 내에 과다 축적된 제설제의 중화 및 토양의 산도 조정을 통해 토양을 개량하고 식물의 생장을 향상시키는 것을 특징으로 하는, 영양 크리너 조성물.(a) 락토바실러스 플란타럼(Lactobacillus plantarum) 배양액을 1차 기초물질로 하여, 여기에 질소 함유 물질, 칼륨 함유 물질 및 닥나무 잿물을 첨가하고 혼합하여 2차 기초물질을 제조하는 단계;(b) 상기 2차 기초물질에 식물의 생장에 필요한 미량 원소 함유 물질을 첨가하고 혼합하여 3차 기초물질을 제조하는 단계; 및(c) 상기 3차 기초물질에 닥나무 농축액, 식물 생장 조절제, 양이온계 중화제 및 음이온계 중화제를 첨가하고 혼합하여 최종 조성물을 제조하는 단계를 포함하는 방법으로서,상기 닥나무 잿물은 수피(樹皮)가 제거된 닥나무 줄기를 건조시키고 900~1300℃의 가열로에서 연소시켜 재(ash) 형태의 연소물을 수득하고, 상기 연소물을 물(water) 1L를 기준으로 0.05~0.2L의 양으로 첨가하고 물(water)의 온도를 50~80℃로 유지하면서 2~10 hr 동안 교반한 후 여과하여 잔사를 제거한 것이고,상기 닥나무 농축액은 닥나무 1L를 기준으로 물(water) 1.2~2.5L와 함께 밀폐된 상태에서 400~700℃의 온도를 유지하며 12~24 hr 동안 삶은 후 닥나무를 건져서 분리하고 삶은 물을 12~24 hr동안 가열하여 물을 증발시키고 최초 물(water) 부피의 1/10 내지 1/2 수준으로 농축시킨 것이며,상기 최종 조성물은 전체 중량을 기준으로 락토바실러스 플란타럼(Lactobacillus plantarum) 배양액 35~55 중량%, 질소 함유 물질 15~35 중량%, 칼륨 함유 물질 6~20 중량%, 닥나무 잿물 0.5~6 중량%, 식물의 생장에 필요한 미량 원소 함유 물질 1~6 중량%, 닥나무 농축액 3~16 중량%, 식물 생장 조절제 0.2~3 중량%, 양이온계 중화제 0.1~2 중량% 및 음이온계 중화제 0.1~2 중량%를 포함하고 살아있는 식물체의 표면에 존재하는 오염물질의 세척, 식물의 생장에 필요한 영양분의 공급, 토양 내에 과다 축적된 제설제의 중화 및 토양의 산도 조정을 통해 토양을 개량하고 식물의 생장을 향상시키는 것을 특징으로 하는, 영양 크리너 조성물의 제조방법., Ltext: 임업, prediction: 임업
146/1059 Row 146: application_number: 1020190115945, combined_string: invention_title: 수목 보호대 abstract: 본 발명은 수목 보호대에 관한 것으로, 수목의 기설정된 높이의 바깥 둘레를 감싸고 있으며, 한쪽 면으로 중첩되어 결착 고정되는 보호몸체; 및 상기 보호몸체의 중첩된 한쪽면에 배치되어 있으며, 상기 보호몸체의 중첩된 위치에 복수 위치로 관통 삽입된 상태에서 열변형에 의해 단면적이 확대되면서 상기 보호몸체의 바깥 면에 융착되는 삽입결착부;를 포함한다. claims: 수목의 기설정된 높이의 바깥 둘레를 감싸고 있으며, 한쪽 면으로 중첩되어 결착 고정되는 보호몸체; 및상기 보호몸체의 중첩된 한쪽면에 배치되어 있으며, 상기 보호몸체의 중첩된 위치에 복수 위치로 관통 삽입된 상태에서 열변형에 의해 단면적이 확대되면서 상기 보호몸체의 바깥 면에 융착되는 삽입결착부;및상기 보호몸체에 설치된 상기 삽입결착부가 삽입 결착된 상태에서 상기 삽입결착부의 상기 보호몸체의 중첩된 부분에서 관통 돌출된 부분을 가열하여 열변형하는 가열변형부;를 포함하되,상기 가열변형부는,상기 보호몸체의 중첩부분에 배치되어 있으며, 상기 삽입결착부의 상기 보호몸체에 삽입 관통한 후에 상부에서 하부로 돌출된 복수 위치로 각각 접촉되는 홈 형태의 변형홈을 가지면서 가열한 상태로 압력을 가하여 열변형 시키는 가열변형몸체; 및상기 가열변형몸체에 일측에 배치되어 있으며, 상기 삽입결착부를 열변형하는 상기 변형홈으로 열기를 발산하도록 상기 가열변형몸체를 가열하는 가열체;를 포함하며,상기 가열체는 상기 가열변형몸체의 내부에 배치되어 있으며, 전력의 공급으로 상기 변형홈 위치에서 가열되는 열선 형태인 가열열선;으로 구비된수목 보호대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

147/1059 Row 147: application_number: 1020190104203, combined_string: invention_title: 식물 생육 관리장치 abstract: 본 발명은 화분에 식립되어 화분에 담긴 흙의 습도, 주변 조도 등을 측정하여 표시하고 화분에 식재된 식물이 실제 자연환경과 유사한 환경에서 생육될 수 있도록 식물에 바람을 제공하여 식물이 생육되는 최적의 환경을 조성하는데 기여하는 식물 생육 관리장치에 관한 것이다. claims: 내부에 흙이 담기고 식물이 심어지는 화분의 흙으로 일부 삽입된 상태에서 화분의 상단 외주 둘레에 거치되는 식물 생육 관리장치에 있어서,식물을 향해 바람을 제공하도록 내부에 송풍팬이 내장되며 송풍팬에 의해 흡입되는 공기가 통과되는 유입부와 흡입된 공기가 바람으로서 배출되는 배출구가 형성되는 토출하우징;상기 토출하우징의 배면에 회동 가능하게 마련되는 클립;상기 클립에 슬라이딩 가능하게 결합되며 흙으로 삽입되어 흙의 습도를 측정하는 습도측정센서; 및상기 토출하우징에 내장되며 식물 주변의 조도를 측정하는 조도측정센서;를 포함하며,상기 토출하우징에는 상기 습도측정센서와 조도측정센서에서 측정한 습도와 조도가 도시되는 디스플레이창이 마련되는 것을 특징으로 하는 식물 생육 관리장치., Ltext: 임업, prediction: 농업
148/1059 Row 148: application_number: 1020190098620, combined_string: invention_title: 내절단성이 강화된 섬유사를 이용하는 망 구조의 해충 방제용 수목 보호대 abstract: 본 발명은 내절단성이 강화된 섬유사를 이용하는 망 구조의 해충 방제용 수목 보호대에 관한 것으로, 상세하게는 HPPE 또는 UHMWPE 섬유사 단독으로 제조된 망, HPPE와 UHMWPE 섬유사에 합성수지 사를 복합하여 제조한 망, 상기 망에 타포린으로 코팅한 망을 평직 또는 라셀형으로 제조한 것이다. 본 발명에 따른 해충 방제용 수목 보호대는 하늘소류의 절단이 불가능하여 탈출을 저지시킴으로써, 소나무재선충병의 방제효과가 우수하다는 것을 확인하였다. claims: HPPE(high-pressure polyethylene) 또는 UHMWPE(Ultra High Molecular Weight Polyethylene) 섬유사를 이용하여 제조된 망 구조의 해충 방제용 수목 보호대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

149/1059 Row 149: application_number: 2020190003133, combined_string: invention_title: 수목점적관수장치 abstract: 본 고안은 수목점적관수장치에 관한 것으로 보다 상세하게는 수목에 개별적으로 설치하여 생육에 필요한 물 또는 영양제 등을 공급하기 위한 수목점적관수장치는 물을 담수할 수 있도록 내부에 공간부가 형성되고 상부에는 수목에 걸 수 있는 걸이연결구멍이 형성되며, 상측 양측단에는 공간부로 물을 공급할 수 있는 유입공이 형성되고, 상기 공간부 하단면부에는 관통공이 중심부에 형성된 강화패드가 융착되고 상기 강화패드의 관통공과 대응되는 외주면부에는 주입표시부가 형성된 물주머니와 상기 물주머니의 주입표시부를 관통하여 강화패드의 관통공으로 삽입되어 상기 물주머니에 담수된 물을 수목에 공급하도록 하는 주사부를 포함하여 이루어진 구조이다. claims: 물을 담수할 수 있도록 내부에 공간부가 형성되고 상부에는 수목에 걸 수 있는 걸이연결구멍이 형성되며, 상측 양측단에는 공간부로 물을 공급할 수 있는 유입공이 형성되고, 상기 공간부 하단면부에는 관통공이 중심부에 형성된 강화패드가 융착되고 상기 강화패드의 관통공과 대응되는 외주면부에는 주입표시부가 형성된 물주머니와;상기 물주머니의 주입표시부를 관통하여 강화패드의 관통공으로 삽입되어 상기 물주머니에 담수된 물을 수목에 공급하도록 하는 주사부를 포함하여 이루어진 것이며,상기 주사부는; 상기 물주머니의 공간부에 담수된 물이 유입될 수 있도록 일측단에 유입공이 형성되고 중심부에는 유입공과 연통된 통공이 형성된 바늘부와; 상기 바늘부의 하단에는 상기 바늘부의 통공와 연통된 통공이 중심부에 형성되며 상부에는 물주머니의 외주면을 지지하는 날개편이 형성된 몸체부와; 상기 몸체부의 하부결착되어 상기 몸체부의 통공으로 부터 유입되는 물을 담수하는 담수공간부가 형성되고 상기 담수공간부의 하단에는 담수공간부의 물을 수목에 공급하도록 소정의 길이로 형성된 공급호스가 구비된 공급부를 포함하여 이루어진 것을 특징으로 하는 수목점적관수장치., Ltext: 임업, prediction: 임업
150/1059 Row 150: application_number: 1020190085071, combined_string: invention_title: 잡초 생장 억제 구조물 abstract: 본 발명은 잡초생성억제, 재배지 보온 및 습도 유지 구조물에 관한 것으로서, 보다 상세하게는 합성 수지 또는 플렉서블한 재질로 만들어져 설치 및 철거작업이 용이하고, 요철 결합으로 철거 후 재사용이 가능한 잡초생성억제, 재배지 보온 및 습도 유지 구조물에 관한 것이다. claims: 재배식물의 크기에 따라 크기가 정해지는 관통 홀(12-1)을 포함하는 생장보호판(12); 및상기 한쌍의 생장보호판(12) 사이에 결합되며, 핀홀(11-1)을 포함하는 사이드고정판(11);를 포함하는 잡초생성억제, 재배지 보온 및 습도 유지 구조물.폴리에틸렌 필름로 이루어지고, 복수개가 열융착 결합 가능하며, 재배식물의 크기에 따라 크기가 정해지는 관통 홀을 포함하는 조립식 생장 억제 시트(12);상기 생장 억제 시트에, 물이 재배식물에 공급되도록 형성되는 수로(12-2);상기 수로(12-2)와 호스(22)로 연결되어 물을 공급하는 물저장부(21);를 포함하는 잡초생성억제, 재배지 보온 및 습도 유지 구조물.일정 재질로 이루어지고, 복수개가 분리 결합 가능하며, 재배식물의 크기에 따라 크기가 정해지는 관통 홀 또는 고정 핀홀이 형성된 멀칭패널;상기 멀칭패널의 관통 홀과 일정 간격 이격되어 형성되고 상기 관통 홀에 연장된 연장호스에 외부의 물을 공급하는 수로(12-2);를 포함하는 잡초생성억제, 재배지 보온 및 습도 유지 구조물.플렉서블한 일정 재질로 이루어지고, 복수개가 열융착으로 결합 가능하며, 재배식물의 크기에 따라 크기가 정해지는 관통 홀 또는 고정 핀홀이 형성된 멀칭패널;상기 멀칭패널의 관통 홀과 일정 간격 이격되어 형성되고 상기 관통 홀에 연장된 연장호스에 외부의 물을 공급하는 수로(12-2);를 포함하는 잡초생성억제, 재배지 보온 및 습도 유지 구조물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

151/1059 Row 151: application_number: 1020190084597, combined_string: invention_title: 과실나무의 생장 촉진을 위한 토양조성방법 abstract: 본 발명은 과실나무의 생장 촉진을 위한 토양조성방법에 관한 것으로서, 보다 상세하게는 과실나무가 심겨진 밭에 과실나무를 둘러싸고 부직포층과 자갈층을 형성시켜 잡초성장을 억제함과 동시에, 자갈층에 반사되는 햇빛이 과실나무에 효과적으로 도달되게 함으로써 과실나무의 생장을 촉진시키는 토양조성방법에 관한 것이다.본 발명에 따르면, 과실나무 주위에 있는 잡초의 생장이 억제될 뿐만 아니라, 자갈층에 반사된 햇빛이 과실나무에 전달됨으로써, 과실나무의 생장이 촉진되는 효과가 있다. claims: 과실나무(1)를 둘러싸는 지면(F) 아래 소정영역의 토양(G)을 파내어 과실나무(1)의 기둥을 지나는 직선 위에 위치한 구의 중심(M1)으로부터 소정 반경(r1)을 가진 구면 형상으로 반사곡면(R)을 형성시키는 단계(S110);과실나무(1)를 둘러싸고 원통형의 자갈차단틀(10)을 형성시키는 단계(S120);반사곡면(R)에 자갈차단틀(10)을 소정 깊이(d1) 삽입하여 반사곡면(R)으로부터 소정 높이(d2) 돌출형성시키는 단계(S130);상기 자갈차단틀(10)의 바깥쪽에 위치한 반사곡면(R)에 부직포를 펼쳐 깔고 고정수단(t)을 이용하여 반사곡면(R)에 고정하여 부직포층(20)을 형성시키는 단계(S140);상기 부직포층(20)의 상부면에 자갈을 깔고 골라서 반사곡면(R)으로부터 동일한 높이(h1)를 가지는 자갈층(30)을 형성시키되, 상기 자갈층(30)의 높이(h1)는 반사곡면(R)으로부터 돌출형성된 자갈차단틀(10)의 높이(d2)보다 작게 되도록 고르는 단계(S150);를 포함하되,상기 S120 단계에서는,원통으로 상호 결합되는 한 쌍의 제1,2반원통부재(11,12)를 준비하는 단계(S121)와,과실나무(1)를 둘러싸고 상기 제1,2반원통부재(11,12)를 서로 마주보게 결합하여 원통형의 자갈차단틀(10)을 형성시키는 단계(S122)를 포함하는 것을 특징으로 하는 과실나무의 생장 촉진을 위한 토양조성방법., Ltext: 임업, prediction: 임업
152/1059 Row 152: application_number: 1020190083524, combined_string: invention_title: 수목과 식물 보호 및 잡초 생장 제한장치 abstract: 본 발명은 수목과 식물들을 보호하는 동시에 수목과 식물들의 밑동 주위에 서 잡초들이 생장하는 것을 제한할 수 있는 장치에 관한 것으로 특히, 물을 모아 뿌리 방향의 지층으로 공급하는 상광하협 형상의 집수판을 구비하여 우천시나 급수시 공급되는 물이 수목이나 식물의 뿌리에 집중 공급될 수 있도록 하고 집수판의 상측부에 내측절곡홈으로 연결되는 안내플랜지를 구비하여 집수판 중앙으로 물이 모일 수 있도록 안내하도록 하며 집수판의 하측부에 외측절곡홈으로 연결되어 지층으로 박혀 지지되는 지지판에 의해 집수판을 안정된 상태로 지지시킨 다음 집수판의 중앙부에 삽입공을 형성하여 지지판이 수목이나 식물의 외곽부를 감싸면서 설치될 수 있도록 하고 조립수단에 의해 집수판을 평면상의 필름 재질로 프레싱하여 형상을 제작한 다음 집수판을 입체적으로 조립할 수 있도록 된 수목과 식물 보호 및 잡초 생장 제한장치를 제공한다. claims: 우천시나 급수시 공급되는 물이 수목이나 식물(142)의 뿌리에 집중 공급될 수 있도록 물을 모아 뿌리 방향의 지층으로 공급하는 상광하협 형상의 집수판(101)과,상기 집수판(101) 중앙으로 물이 모일 수 있도록 안내하기 위해 집수판(101)의 상측부에 내측절곡홈(104)으로 연결되는 안내플랜지(105)와,상기 집수판(101)을 안정된 상태로 지지시키기 위해 집수판(101)의 하측부에 외측절곡홈(102)으로 연결되어 지층으로 박혀 지지되는 지지판(103)과,상기 지지판(103)이 수목이나 식물(142)의 외곽부를 감싸면서 설치될 수 있도록 집수판(101)의 중앙부에 형성되는 삽입공(106)과,상기 집수판(101)을 평면상의 필름 재질로 프레싱하여 형상을 제작한 다음 집수판(101)을 입체적으로 조립하기 위한 조립수단을 구비한 것을 특징으로 하는 수목과 식물 보호 및 잡초 생장 제한장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

153/1059 Row 153: application_number: 1020190080692, combined_string: invention_title: 전자 지도상의 위치 정보를 이용하여 수목을 관리하는 시스템 및 그 방법 abstract: 본 발명은 전자 지도상의 위치 정보를 이용하여 수목을 관리하는 시스템 및 그 방법에 관한 것으로서, 산림조사지역내의 개별목의 정보를 입력하여 서버로 업로딩하는 적어도 하나의 단말기; 및 상기 적어도 하나의 단말기로부터 입력되는 상기 개별목의 정보를 수신하여 다른 단말기로 전송하는 서버; 를 포함한다.또한, 본 발명은 2018년 7월 4일 특허출원한 &amp;quot;전자 지도상의 위치 정보를 이용하여 나무의 병충해를 조사하고 방제하는 시스템 및 그 방법&amp;quot;(한국특허 출원번호 10-2018-0077616호)을 기본으로 하여 국내우선권 주장으로 특허출원한다. 본 발명은 인용된 특허출원 10-2018-0077616호에 비하여 전자 지도상의 위치 정보를 이용하여 수목을 관리하고 산림생장량, 산림자원량, 탄소배출권 중 적어도 하나를 산출할 수 있는 장점을 제공한다. claims: 산림조사지역내의 개별목의 정보를 입력하여 서버로 업로딩하는 적어도 하나의 단말기; 및상기 적어도 하나의 단말기로부터 입력되는 상기 개별목의 정보를 수신하여 다른 단말기로 전송하는 서버; 를 포함하는 전자 지도상의 위치 정보를 이용하여 수목을 관리하는 시스템.제1 또는 제2 사용자 인터페이스에 표시되는 전자 지도상에서 산림조사지역을 선정하는 제1 단계;제1 사용자 인터페이스에서 상기 제1 단계에서 선정된 상기 산림조사지역내의 개별목의 정보를 입력하는 제2 단계; 상기 제2 단계에서 입력된 상기 산림조사지역내의 개별목의 정보를 서버로 업로딩하는 제3 단계; 및 상기 서버는 적어도 하나의 사용자 단말기로부터 상기 업로딩된 상기 개별목의 정보를 다른 사용자 단말기에 전송하는 제4 단계; 를 포함하는 전자 지도상의 위치 정보를 이용하여 수목을 관리하는 방법., Ltext: 임업, prediction: 임업
154/1059 Row 154: application_number: 1020190080343, combined_string: invention_title: 수목 보호용 방초 매트 abstract: 본 발명은 수목 보호용 방초 매트에 관한 것으로, 보다 상세하게는 끝단 둘레가 사선방향으로 절곡된 제1절곡부와, 상기 제1절곡부와 연장되어 측면으로 연장된 제2절곡부가 형성된 방초 매트;와, 상기 방초 매트 중앙에 원형의 제1절취부가 형성되고, 상기 제1절취부를 절취하여 형성된 개구부;와, 상기 개구부 일측 끝단에서 방초 매트 끝단까지 연장된 제2절취부가 형성되고, 상기 제2절취부를 절취하여 형성된 절개부;를 포함하되, 상기 방초 매트 상부면에는 수목 이력사항이 기재된 수목안내부가 더 설치되고, 상기 절개부 양측에 벨크로를 설치하여 상호 고정시켜 수목 밑둥을 감싸 고정시키고, 상기 개구부 끝단 둘레에 제1삽입홈이 형성되고, 상기 제1삽입홈에 와이어가 삽설되어 상기 와이어가 수목 밑둥 둘레를 감싸고 조인 후 고정하여 방초 매트가 미끄러지는 것을 방지하는 것을 특징으로 한다. claims: 끝단 둘레가 사선방향으로 절곡된 제1절곡부(101)와, 상기 제1절곡부(101)와 연장되어 측면으로 연장된 제2절곡부(102)가 형성된 방초 매트(100)와, 상기 방초 매트(100) 중앙에 원형의 제1절취부(11)가 형성되고, 상기 제1절취부(11)를 절취하여 형성된 개구부(10)와, 상기 개구부(10) 일측 끝단에서 방초 매트(100) 끝단까지 연장된 제2절취부(21)가 형성되고, 상기 제2절취부(21)를 절취하여 형성된 절개부(20);를 포함하는 수목용 방초 매트에 있어서,상기 방초 매트(100) 상부면에는 수목 이력사항이 기재된 수목안내부(30)가 더 설치되고, 상기 절개부(20) 양측에 벨크로(40)를 설치하여 수목 밑둥을 감싸서 상호 고정되고, 상기 개구부(10) 끝단 둘레에 제1삽입홈(51)이 형성되며 상기 제1삽입홈(51)에 와이어(50)가 삽설되어 상기 와이어(50)가 수목 밑둥 둘레를 감싸고 조임으로서 방초 매트(100)가 미끄러지는 것을 방지하고, 상기 제1절취부(11)는 방초 매트(100) 중앙 둘레에 크기별로 다수개 설치되어 수목 밑둥의 크기에 맞도록 선택적으로 절취하도록 이루어지며, 상기 제2절곡부(102) 하부면에 미끄럼 방지 패드(12)를 설치하여 방초 매트(100)의 유동을 방지하도록 이루어지되,상기 제1삽입홈(51)에는 제1고정삽입부(53)가 삽설되되, 상기 제1고정삽입부(53) 양측에 하방으로 절곡되고 끝단에 돌기(55)가 형성되어 상기 돌기(55)가 지면에 삽입되어 방초 매트(100)를 고정하는 제3절곡부(103)와;상기 방초 매트(100) 끝단 둘레에는 제2삽입홈(52)이 형성되고,상기 제2삽입홈(52)에는 제2고정삽입부(54)가 삽설되되, 상기 제2고정삽입부(54) 양측에 하방으로 절곡된 제4절곡부(104)가 형성되며, 상기 제4절곡부(104) 끝단에 돌기(55)가 형성되어 상기 돌기(55)가 지면에 삽입되어 방초 매트(100)를 견고히 고정하는 것을 특징으로 하는 수목 보호용 방초 매트., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

155/1059 Row 155: application_number: 1020190075485, combined_string: invention_title: 평형함수율을 이용한 산림연료습도의 추정방법 및 시스템 abstract: 본 발명은 산악기상관측망 기상자료를 이용하여 평형함수율을 산출하는 단계; 평형함수율을 이용하여 10시간 사연료습도와의 선형회귀식을 얻는 단계; 상기 선형회귀식을 이용하여 10시간 사연료습도를 산출하는 단계; 및 상기 10시간 사연료습도를 이용하여 산림연료습도를 추정하는 단계를 포함하는 평형함수율을 이용한 산림연료습도의 추정방법 및 시스템을 제공한다. claims: 산악기상관측망 기상자료를 이용하여 평형함수율을 산출하는 단계;평형함수율을 이용하여 10시간 사연료습도와의 선형회귀식을 얻는 단계;상기 선형회귀식을 이용하여 10시간 사연료습도를 산출하는 단계; 및상기 10시간 사연료습도를 이용하여 산림연료습도를 추정하는 단계를 포함하는 평형함수율을 이용한 산림연료습도의 추정방법. 산악기상관측망(AMOS) 기상자료를 제공하는 기상자료제공수단; 산악기상관측망 기상자료를 이용하여 평형함수율을 산출하는 평형함수율산출수단; 평형함수율을 이용하여 10시간 사연료습도와의 선형회귀식을 얻는 선형회귀식도출수단; 상기 선형회귀식을 이용하여 10시간 사연료습도를 산출하는 사연료습도산출수단; 및 상기 10시간 사연료습도를 이용하여 산림연료습도를 추정하는 산림연료습도추정수단;을 포함하는 평형함수율을 이용한 산림연료습도의 추정시스템., Ltext: 임업, prediction: 임업
156/1059 Row 156: application_number: 1020190074709, combined_string: invention_title: 보행자 안전과 지중 시설물 보호를 위한 수목뿌리 보호 생장 유도 장치 abstract: 본 발명은 수목 뿌리 생장방향을 유도하는 장치에 관한 것으로 더욱 상세하게는 하부 내주면 지름이 상부 내주면 지름보다 소폭 큰 형상을 이루고, 수평수공 및 수직수공이 형성되는 식재측벽체와 자갈채움층이 형성되도록 식재측벽체 외방으로 형성되는 지반측벽체 등으로 인위적 조성 및 물리적으로 수목 뿌리 생장방향을 이루어 수분 및 산소 공급등의 생장환경을 최적화시키는 것이며, 그에 따라서 수목의 생장을 돕고, 수목 식재 후 수목 뿌리가 지면 상부 또는 도로 하부나 시설물 하부로 자라는 것을 방지하여 수목의 고사를 억제하는 보행자 안전과 지중 시설물 보호를 위한 수목뿌리 보호 생장 유도 장치에 관한 것이다.이상에서 설명한 바와 같이 본 발명에 의한 보행자 안전과 지중 시설물 보호를 위한 수목뿌리 보호 생장 유도 장치는 단지, 도로 및 공원등에 식재되는 수목 뿌리의 생장방향을 하방으로 하여 뿌리가 지면 상방으로 노출되거나 지중 시설물로 생장되는 것을 방지하여 차량 및 보행자의 통행 방해를 방지하고, 뿌리로 인한 시설물 파손을 방지하며, 자갈채움층을 형성하고, 복수개의 수평수공과 수직수공을 구성하여 뿌리로 수분 및 산소공급과 뿌리에서 발생되는 이산화탄소 배출을 원활히 하여 수목 생장을 원활히 실시하며, 자갈채움층을 형성하고, 공극을 가지는 현무암 재질의 잔자갈을 충진하며, 공극사이로 유용미생물을 주입하여 수목 생장에 도움을 준다. claims: 수목 뿌리의 생장방향을 유도하는 장치에 있어서,상기 장치는 평면상 원형 또는 다각형으로 중앙이 개방되어 식재공간을 가지고, 하부 내주면 지름이 상부 내주면 지름보다 소폭 큰 형상을 이루며, 수목 뿌리에 수분과 산소를 공급하고, 수목 뿌리로부터 발생되는 이산화탄소의 배출를 위해 측면에 복수개의 수평수공이 형성된 식재측벽체; 및상기 식재측벽체와 동일한 형상으로 식재측벽체의 하단이 하단돌출부로 연결되고, 식재측벽체의 외방을 감싸되 식재측벽체와 소정거리 떨어져 자갈을 채울수 있는 공간인 자갈채움층이 형성되며, 상기 자갈은 현무암으로 잔자갈로 이루어 충진되는 지반측벽체;를 포함하여 이루어지고,상기 하단돌출부는 자갈채움층이 형성된 하부면에 사용자에 의하여 공급되는 수분 또는 우수등이 원지반으로 침투시키기 위해 복수개의 수직수공을 형성하고, 상기 지반측벽체는 상부 끝단에 외방으로 돌출된 상단돌출부가 지면상방으로 형성되어 지면에 설치되되 표층블럭의 상방에 위치시켜 보행자 및 차량으로부터 수목을 보호하며,상기 상단돌출부와 지반측벽체 외방으로 돌출된 하단돌출부는 각각 복수개의 상단천공과 하단천공이 구비되고, 상기 상단천공 통해 수목의 줄기 또는 가지를 고정 및 지지하는 케이블이 통과되고 하단천공을 통해 지중에 고정설치되는 지중스크류의 상부에 상기 케이블이 고정되고,상기 자갈은 현무암 재질로 외면에 복수개의 공극을 가지고, 공극사이에 유용미생물(EM, Effective Microorgani는)이 주입되는 보행자 안전과 지중 시설물 보호를 위한 수목뿌리 보호 생장 유도 장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

157/1059 Row 157: application_number: 1020190070705, combined_string: invention_title: 수목 식재용 대나무 유공관과 이를 이용한 수목의 식재방법 abstract: 본 발명은 수목 식재용 대나무 유공관과 이를 이용한 수목의 식재방법에 관한 것으로서, 더욱 상세하게는 수목의 식재시 뿌리 주위에 설치되는 플라스틱 유공관을 천연 소재인 대나무로 대체함으로써 환경보호와 함께 통기성 및 배수성을 향상시킬 수 있는 수목 식재용 대나무 유공관과 이를 이용한 수목의 식재방법에 관한 것이다. 본 발명의 수목 식재용 대나무 유공관은 마디들에 의해 내부가 다수의 공간으로 구획된 대나무를 일정 길이로 자른 후 상기 마디들 전부 또는 일부를 제거하여 형성한 대통과, 대통의 측면을 관통하여 형성시킨 다수의 타공홀들을 구비한다. claims: 마디들에 의해 내부가 다수의 공간으로 구획된 대나무를 일정 길이로 자른 후 상기 마디들 일부를 제거하여 적어도 2개의 마디가 남아있고, 수목의 뿌리방향을 향하도록 하부를 비스듬하게 절단하여 하부가 뾰족한 대통과;상기 대통의 측면을 관통하여 형성시킨 다수의 타공홀들;을 구비하고,상기 대통의 뾰족한 하부에는 상기 타공홀이 미형성되며, 상기 대통에 남아있는 마디들 사이에 양분이 저장된 양분실이 형성되고, 상기 대통에 남아있는 마디들에는 상하로 관통된 연통홀이 형성되며,상기 양분실로 양분을 주입할 수 있도록 상기 대통의 측면에는 주입구가 형성되고, 상기 주입구는 천연수지 또는 황토로 밀폐되고,길이가 서로 다른 대롱들을 상기 대통의 내부에 삽입하여 유체가 통과하는 다수의 유로를 상기 대통의 내부에 상하로 길게 형성하며 상기 대롱들의 하단 위치는 상하방향으로 서로 엇갈리게 형성된 것을 특징으로 하는 수목 식재용 대나무 유공관. 수목을 식재하고자 하는 위치에 일정한 깊이로 구덩이를 파는 굴토단계와;상기 구덩이에 수목의 뿌리분을 안착시키는 뿌리안착단계와;상기 구덩이의 바닥에 대나무 유공관을 박아서 고정시키는 유공관고정단계와;상기 구덩이에 흙을 채워 상기 뿌리분을 매립하되 상기 대나무 유공관의 상부는 지상으로 노출되도록 매립하는 매립단계;를 포함하고,상기 대나무 유공관은 마디들에 의해 내부가 다수의 공간으로 구획된 대나무를 일정 길이로 자른 후 상기 마디들 일부를 제거하여 적어도 2개의 마디가 남아있고 상기 뿌리분을 향하도록 하부를 비스듬하게 절단하여 하부가 뾰족한 대통과, 상기 대통의 측면을 관통하여 형성시킨 다수의 타공홀들을 구비하고,상기 대통의 뾰족한 하부에는 상기 타공홀이 미형성되며, 상기 대통에 남아있는 마디들 사이에 양분이 저장된 양분실이 형성되고, 상기 대통에 남아있는 마디들에는 상하로 관통된 연통홀이 형성되며,상기 양분실로 양분을 주입할 수 있도록 상기 대통의 측면에는 주입구가 형성되고, 상기 주입구는 천연수지 또는 황토로 밀폐되고, 상기 유공관고정단계는 상기 대나무 유공관이 상기 뿌리분을 비스듬하게 관통하도록 고정시켜 상기 대나무 유공관에 의해 상기 뿌리분이 지지되는 것을 특징으로 하는 대나무 유공관을 이용한 수목의 식재방법., Ltext: 임업, prediction: 임업
158/1059 Row 158: application_number: 1020190062936, combined_string: invention_title: 자립식 수목관수용 물통 abstract: 본 발명은 자립식 수목 관수용 물통에 관한 것으로, 상세하게는, 자립식으로 수목이 지면과 교차하는 수간부에 그 수간을 에워싸도록 수목에 고정 설치되고, 관수량을 조절하는 밸브를 일체형으로 구비하여 상기 밸브를 매개로 내부에 채워져 있는 물을 점적관수 방식으로 수목으로 공급하는 자립식 수목관수용 물통에 관한 것이다. claims: 각각 물이 저장되는 물 저장공간이 마련되어 있고, 일단부가 서로 접철 가능하게 결합되어 수목(1)의 수간을 에워싼 상태로 결속부(15)에 의해 결속되는 제1 및 제2 물탱크(11, 12);상기 제1 및 제2 물탱크(11, 12)를 상호 연결하여 상기 제1 물탱크(11)에 마개(16)에 의해 밀폐되도록 형성된 주입구(11a)를 통해 주입되어 상기 제1 물탱크(11)에 저장된 물을 상기 제2 물탱크(12)로 공급하는 연결관(13);상기 제1 물탱크(11)의 하부에 형성된 배수구(11c)에 설치되고, 상기 제1 물탱크(11)의 배수구(11c)를 통해 배출되는 물을 수목으로 급수하는 급수밸브(14);상기 제1 및 제2 물탱크(11, 12)의 상단 내측에는 상기 수목(1)의 수간부에 묶음끈을 이용하여 안정적으로 고정하기 위해 일정 간격으로 설치된 복수 개의 고리(18);를 포함하며,상기 제1 및 제2 물탱크(11, 12)의 내측 하부에는 상기 제1 및 제2 물탱크(11, 12)를 상호 결속할 때 상기 연결관(13)이 간섭되지 않도록 상기 연결관(13)이 내부로 매입되는 매입홈(11b, 12a)이 형성되어 있고, 상기 제1 및 제2 물탱크(11, 12)의 타측부 하단에는 상기 급수밸브(14)를 외부에서 조작할 수 있도록 상기 제1 및 제2 물탱크(11, 12)가 상호 결합된 상태에서 상기 급수밸브(14)가 외부로 노출되도록 급수밸브 조작용 홈(10a)이 형성되어 있으며,상기 제1 및 제2 물탱크(11, 12)는 상기 결속부(15)에 의해 상기 수목(1)의 수간을 에워싸도록 상호 결속된 상태에서 상단부에서 하단부로 갈수록 균일하게 지름이 증가하는 원추형 구조로 이루어지고, 각각의 내측면에는 상기 수목(1)의 수간부 외주면에 대응하여 오목한 반호 형상을 갖도록 형성되고,상기 연결관(13)은 상기 제1 및 제2 물탱크(11, 12)의 전개시 당겨지는 힘에 의해 길이가 늘어나고, 결속시에는 원상태로 복귀하여 상기 제1 및 제2 물탱크(11, 12)의 전개 및 결속시 방해가 되지 않도록 길이가 가변되는 주름관으로 이루어지는 것을 특징으로 하는 자립식 수목관수용 물통., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

159/1059 Row 159: application_number: 1020190058973, combined_string: invention_title: 캄포 나무의 수액 추출 방법 abstract: 본 발명은 캄포 나무 수액 추출 방법을 개시한다. 이러한 본 발명은 벌목된 캄포 나무를 가공한 것을 가열하여 수액 증류수를 추출하는 것이고, 이를 통해 생육 상태의 나무로부터 수액 추출시 초래되는 종래의 각종 문제점을 개선하고, 추출된 수액 증류수를 미용 제품에 도포 또는 함유시키면서 화학 원료 사용없이 안전한 친환경적인 미용 제품을 제공하는 것이다. claims: (a) 벌목된 캄포 나무 원목을 일정크기로 제재기로 가공하는 공정;(b) 상기 (a)공정으로부터 가공되는 일정크기의 캄포 나무 원목을 가열하여 수액 증류수를 추출하는 공정; 및,(c) 상기 (b)공정으로부터 추출되는 수액 증류수를 필터를 이용하여 불순물을 제거하는 공정; 을 포함하는 것을 특징으로 하는 캄포 나무의 수액 추출 방법., Ltext: 임업, prediction: 임업
160/1059 Row 160: application_number: 1020210067226, combined_string: invention_title: 어류의 질병여부를 판단하고 포획할 수 있는 어류질병 감지장치 abstract: 어류질병 감지장치 및 그 감지방법이 개시된다. 본 발명에 따른 어류질병 감지장치는, 어류에 대한 질병의 종류와 각각의 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 움직임패턴 저장부; 가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 영상신호 수신부; 영상신호 수신부에 의해 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 움직임패턴 분석부; 움직임 분석부에 의해 분석되는 각각의 어류의 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 어류 추출부; 어류 추출부에 의해 추출된 어류에 대응하는 움직임패턴을 움직임패턴 저장부에 저장된 움직임패턴과 비교하는 움직임패턴 비교부; 및 움직임패턴 비교부에 의해 비교되는 결과에 따라 어류 추출부에 의해 추출된 어류에 대한 질병 여부를 판단하는 어류질병 판단부;를 포함하는 것을 특징으로 한다. claims: 어류에 대한 질병의 종류와 각각의 상기 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 움직임패턴 저장부;가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 영상신호 수신부; 상기 영상신호 수신부에 의해 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 움직임패턴 분석부;상기 움직임 분석부에 의해 분석되는 각각의 어류의 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 어류 추출부;상기 어류 추출부에 의해 추출된 어류에 대응하는 움직임패턴을 상기 움직임패턴 저장부에 저장된 움직임패턴과 비교하는 움직임패턴 비교부;상기 움직임패턴 비교부에 의해 비교되는 결과에 따라 상기 어류 추출부에 의해 추출된 어류에 대한 질병 여부를 판단하는 어류질병 판단부;상기 어류 추출부에 의해 추출된 어류의 위치를 확인하는 어류위치 확인부; 및상기 어류위치 확인부에 의해 확인되는 위치에 대응하여 어류를 포획하는 어류 포획부;를 포함하는 것을 특징으로 하는, 어류의 질병여부를 판단하고 포획할 수 있는, 어류질병 감지장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

161/1059 Row 161: application_number: 1020200106869, combined_string: invention_title: 지중작물 수확 및 비닐수거 겸용장치 abstract: 본 발명은 트랙터 등 견인수단에 견인되어 지중작물을 수확할 수 있으며, 이에 더하여 밭두둑에 덮어 놓은 비닐을 수거하도록 구성되는 지중작물 수확 및 비닐수거 겸용장치에 관한 것으로, 견인수단에 연결되는 연결부, 하부에 수확공간이 형성되도록 상호 이격되는 한 쌍의 측판 및 상기 측판과 직교하는 방향으로 상기 한 쌍의 측판 간을 연결하는 하나 이상의 지지대를 포함하는 본체; 상기 수확공간에 구성되어 땅속 작물을 수확하도록 구성되는 수확부; 및 상기 본체의 후단부에 배치되는 것으로, 상기 측판 또는 지지대 중 하나 이상에 결합되며 지중에 고정된 비닐을 수거하도록 구성되는 비닐수거부;를 포함하여 트랙터 등 견인수단에 견인되어 지중작물을 수확하는 과정에서 지중작물로부터 이물질이 자동으로 분리되도록 구성되고, 이에 더하여 밭두둑에 덮여 고정된 비닐을 순차적으로 굴착하면서 동시에 권취되도록 하는 수거방식이 적용되어 비닐 수거에 대한 노동력이 절감되고 생산성이 향상되며 또한, 수거된 비닐을 자동으로 지면에 투척하도록 구성하여 별도의 인력소보가 배제될 수 있으며 작업의 연속성이 확보되어 작업효율이 크게 향상되는 효과가 있는 지중작물 수확 및 비닐수거 겸용장치에 관한 것이다. claims: 견인수단에 연결되는 연결부, 하부에 수확공간이 형성되도록 상호 이격되는 한 쌍의 측판 및 상기 측판과 직교하는 방향으로 상기 한 쌍의 측판 간을 연결하는 하나 이상의 지지대를 포함하는 본체;상기 수확공간에 구성되어 땅속 작물을 수확하도록 구성되는 수확부; 및상기 본체의 후단부에 배치되는 것으로, 상기 측판 또는 지지대 중 하나 이상에 결합되며 지중에 고정된 비닐을 수거하도록 구성되는 비닐수거부;를 포함하고,상기 수확부는상기 수확공간의 전방 하부에서 선단측으로 갈수록 하향되는 경사구조로 구성되며 상기 본체가 전방으로 이동함에 따라 지중작물을 채굴하도록 구성되는 채굴판; 및상기 채굴판의 후단과 연계되도록 구성되어 상기 채굴판에 의해 채굴된 지중작물을 후방으로 배출시키되, 지중작물로부터 이물을 분리시키는 배출부재;를 포함하며,상기 비닐수거부는상기 지지대로부터 후방을 향해 회전 가능한 구조로 연장되며 후단에는 한 쌍이 상호 나란하게 이격되는 제 1샤프트;한 쌍의 상기 제 1샤프트의 후단에 각각 고정되되, 상기 제 1샤프트와는 수직 구조로 배치되는 한 쌍의 제 2샤프트;한 쌍의 상기 제 2샤프트의 사이에 배치되며, 일단 보다 타단의 직경이 큰 콘 형태로 마련되고, 각 타단부가 상기 제 2샤프트에 각각 회전가능하게 결합되며 비닐이 권취되는 한 쌍의 수거부재;한 쌍의 상기 수거부재 중 하나 이상에 회전력을 제공하는 동력수단; 및한 쌍의 상기 제 1샤프트를 서로 반대되는 방향으로 회전제어하는 회전제어부;를 포함하여 구성되는 것을 특징으로 하는 지중작물 수확 및 비닐수거 겸용장치., Ltext: 어업, prediction: 임업
162/1059 Row 162: application_number: 1020200104288, combined_string: invention_title: 어업용 로프 abstract: 본 발명은 외부에 결합된 무게추 없이 물속으로 가라앉을 수 있도록 된 새로운 구조의 어업용 로프에 관한 것이다.본 발명에 따른 어업용 로프는 합성수지재질로 구성된 복수개의 와이어(1)를 꼬아서 제작된 로프의 내부에 무게추(2)가 구비되며, 특히, 상기 무게추(2)는 길이가 긴 바형상으로 구성되고, 상기 와이어(1)는 상기 무게추(2)의 둘레부를 감싸도록 무게추(2)의 둘레부에 나선형으로 배치됨으로, 어업용 로프의 비중이 바닷물의 비중에 비해 높아져, 바닷속으로 가라앉게 된다.따라서, 로프의 둘레면에 외부에 별도로 무게추(2)를 결합할 필요가 없어서, 사용이 더욱 편리할 뿐 아니라, 둘레부에 외측으로 돌출되는 부분이 없어서, 기계를 이용하여 어업용 로프를 감아올릴 때, 로프가 기계에 걸리게 되는 것을 방지할 수 있는 장점이 있다. claims: 합성수지재질로 구성된 복수개의 와이어(1)를 꼬아서 제작된 어업용 로프에 있어서, 상기 로프의 내부에는 납재질로 구성된 무게추(2)가 구비되고,상기 무게추(2)는 길이가 긴 바형상으로 구성되고, 상기 와이어(1)는 상기 무게추(2)의 둘레부를 감싸도록 무게추(2)의 둘레부에 나선형으로 배치되고, 상기 무게추(2)의 중간부에는 무게추(2)를 관통하며 양단이 상기 와이어(1)의 외측으로 연장된 복수개의 고정철사(3)가 무게추(2)의 길이방향으로 상호 이격되도록 구비되며, 상기 고정철사(3)의 외측단은 어업용 로프의 원주방향으로 벤딩되어 상기 와이어(1)가 무게추(2)의 둘레면에 밀착되도록 가압고정하도록 하는 것을 특징으로 하는 어업용 로프., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

163/1059 Row 163: application_number: 1020200104290, combined_string: invention_title: 어업용 로프 abstract: 본 발명은 손쉽게 통발이나 주낙의 목줄을 일정한 간격으로 연결할 수 있도록 된 새로운 구조의 어업용 로프에 관한 것이다.본 발명에 따른 어업용 로프는 일정 거리마다 눈금(2)이 표시됨으로, 작업자가 로프(1)에 목줄을 연결할 때, 정확한 간격으로 목줄을 연결할 수 있는 장점이 있다.특히, 상기 눈금(2)은 표시장치(10)를 이용하여 자동으로 일정간격으로 로프(1)에 표시됨으로, 로프(1)에 눈금(2)을 표시하는 작업이 매우 용이한 장점이 있다. claims: 합성수지재질로 구성된 복수개의 로프(1)를 꼬아서 제작된 어업용 로프에 있어서, 상기 로프(1)의 중간부에는 일정한 간격으로 눈금(2)이 표시되고,상기 눈금(2)은 표시장치(20)를 이용하여 상기 로프(1)의 둘레면에 합성수지를 사출하여 형성되며, 상기 표시장치(20)는 지지대(21)와, 상기 지지대(21)에 구비되며 구동모터에 의해 구동되어 상기 로프(1)를 전방에서 후방으로 이송하는 이송로울러(22)와, 상기 지지대(21)에 구비되며 상기 로프(1)의 중간부 외주면에 합성수지를 사출하여 눈금(2)을 형성하는 사출장치(23)와, 상기 사출장치(23)의 후방에 위치되도록 상기 지지대(21)에 전후방향으로 위치조절가능하게 구비되어 상기 로프(1)의 외주면에 사출된 합성수지를 감지하는 감지센서(24)와, 상기 감지센서(24)의 신호를 수신하며 상기 이송로울러(22)와 사출장치(23)의 작동을 제어하는 제어수단(25)을 포함하며, 상기 제어수단(25)은 상기 사출장치(23)를 이용하여 로프(1)의 중간부에 합성수지가 사출되어 눈금(2)이 표시되도록 한 후, 상기 구동모터를 구동시켜 이송로울러(22)에 의해 로프(1)가 후방으로 이송되도록 하면서 상기 감지센서(24)의 신호를 감시하여, 상기 감지센서(24)에 이송로울러(22)의 외주면에 사출된 합성수지가 감지되면 상기 이송로울러(22)를 정지시키고 상기 사출장치(23)를 이용하여 로프(1)의 중간부에 합성수지를 사출하는 작업을 반복하도록 된 것을 특징으로 하는 어업용 로프., Ltext: 어업, prediction: 어업
164/1059 Row 164: application_number: 1020200062751, combined_string: invention_title: 드론을 이용한 고기잡이장치 abstract: 본 발명은 드론을 이용한 고기잡이장치에 관한 것으로, 호수, 강 또는 바다의 수면에 부유하면서 어군 탐지, 집어, 최적의 어군 밀집 지점에 그물망 투하 및 인양, 위치이동, 수면에서의 드론 이/착륙이 가능하게 하기 위한 것이다.이를 위하여 본 발명은 그물망에 연결된 인양줄을 감거나 풀 수 있는 권취기가 설치되고 원격 제어신호 또는 미리 설정된 제어신호에 따라 권취기의 동작을 제어하는 제어부를 구비하여 원격 제어신호 또는 미리 설정된 제어신호에 의해 상기 권취기를 제어하는 드론부, 부력에 의해 호수, 강 또는 바다의 수면에 부유하여 그물망의 부표 및 수상에서의 드론 이/착륙을 위한 도킹 플랫폼을 제공하고 드론부의 권취기에서 풀리거나 감기는 인양줄의 승강 동작을 안내하는 수상 랜딩부, 및 접거나 펼침 가능한 다수 개의 탄성바와 각 탄성바 사이의 봉돌이 중심부에서부터 방사상으로 균등하게 이격되어 분산 배치되는 그물망 몸체로서 인양줄에 의해 드론부에 매달리는 형태로 승강 가능하게 설치되어 수상 랜딩부의 하부에서 수중으로 투하 또는 견인되는 절첩식 그물부를 포함하여, 현장에 직접 배를 출항시키지 않고도 최적의 어군 밀집 지점에서 효율적인 고기잡이가 가능하게 하여 배의 출항에 따른 유류비와 인건비를 획기적으로 줄일 수 있게 한다. claims: 드론몸체(11)를 바닥면에서 상부로 일정 높이 이격시켜 지지하기 위한 다수 개의 다리(12)가 구비되고, 그물망에 연결된 인양줄(13)을 감거나 풀어줄 수 있는 권취기(14)가 드론몸체(11)의 하부 중심부에 설치되고 외부에서 무선 수신되는 원격 제어신호 또는 미리 설정된 제어신호에 따라 상기 권취기(14)의 동작을 제어하는 제어부(15)를 구비하여 원격 제어신호 또는 미리 설정된 제어신호에 의해 상기 권취기(14)를 제어하는 드론부(10);공기를 주입 또는 배출하여 부피가 팽창 또는 축소되는 튜브형 몸체(21)로서 부력에 의해 호수, 강 또는 바다의 수면에 부유하여 그물망의 부표 및 수상에서의 드론 이/착륙을 위한 도킹 플랫폼을 제공하고, 수밀 구조의 전원공급장치(22)와 무선 송수신부(23)를 구비하여 상기 드론부(10)와의 무선 통신으로 데이터를 송수신하며 상기 튜브형 몸체(21)의 중앙부 빈 공간(21a)으로 상기 드론부(10)의 권취기(14)에서 풀리거나 감기는 다수 개의 인양줄(13)을 통과시켜 상기 인양줄(13)의 종단부에 연결되는 절첩식 그물부(30) 또는 어군 탐지기(41) 또는 집어등(42) 또는 영상 표출부(43)의 승강 동작을 안내하는 수상 랜딩부(20); 및 접거나 펼침 가능한 다수 개의 탄성바(31)와 각 탄성바 사이의 봉돌(32)이 중심부에서부터 방사상으로 균등하게 이격되어 분산 배치되는 그물망 몸체로서, 상기 드론부(10)에 연결된 다수 개의 인양줄(13)이 상기 수상 랜딩부(20)의 튜브형 몸체(21)의 중앙부 빈 공간(21a)을 통과하여 그물망 몸체의 둘레에 일정 간격마다 이격되게 연결되되 상기 다수 개의 인양줄(13)에 의해 상기 드론부(10)에 매달리는 형태로 승강 가능하게 설치되어 상기 드론부(10)의 비행 동작에 따라 상기 인양줄(13)을 상부로 당기거나 놓는 동작에 의해 그물망 몸체의 탄성바(31)가 접히거나 펼쳐져 상기 수상 랜딩부(20)의 하부에서 수중으로 투하 또는 견인되는 절첩식 그물부(30);를 포함하여 구성되는 것을 특징으로 하는 드론을 이용한 고기잡이장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

165/1059 Row 165: application_number: 1020200063253, combined_string: invention_title: 기포발생기 일체형 집어등 abstract: 기포발생기 일체형 집어등이 개시된다. 본 발명의 실시예에 따른 기포발생기 일체형 집어등은, 빛을 발생하여 수면 상에 조사함으로써 빛으로 물고기를 집어함과 동시에 수중에 기포를 발생시킬 수 있는 기포발생기 일체형 집어등에 관한 것으로서, 내부에 제어부 및 에어펌프를 탑재할 수 있는 수용공간이 마련되고, 분해조립이 가능한 박스형 구조의 하우징; 상기 하우징의 상부 일측에 힌지 구조에 의해 장착되는 조명제공부; 상기 하우징의 내부에 탑재되는 에어펌프, 에어펌프로부터 제공되는 압축공기를 외부로 제공하기위해 하우징의 일측면으로부터 외부로 노출되도록 장착되는 에어공급 노즐을 포함하는 기포제공부; 및 상기 하우징 내부에 장착되고, 조명제공부 및 기포제공부를 제어하는 제어부;를 포함하는 것을 을 구성의 요지로 한다.본 발명에 따르면, 빛을 발생하여 수면 상에 조사하여 빛으로 물고기를 집어함과 동시에 수중에 기포를 발생시켜 집어 효과를 극대화시킬 수 있는 기포발생기 일체형 집어등을 제공할 수 있다. claims: 빛을 발생하여 수면 상에 조사함으로써 빛으로 물고기를 집어함과 동시에 수중에 기포를 발생시킬 수 있는 기포발생기 일체형 집어등에 관한 것으로서,내부에 제어부(140) 및 에어펌프(150)를 탑재할 수 있는 수용공간이 마련되고, 분해조립이 가능한 박스형 구조의 하우징(110);상기 하우징(110)의 상부 일측에 힌지 구조(121)에 의해 장착되는 조명제공부(120);상기 하우징(110)의 내부에 탑재되는 에어펌프(150), 에어펌프(150)로부터 제공되는 압축공기를 외부로 제공하기 위해 하우징(110)의 일측면으로부터 외부로 노출되도록 장착되는 에어공급 노즐(131)을 포함하는 기포제공부(130); 및상기 하우징(110) 내부에 장착되고, 조명제공부(120) 및 기포제공부(130)를 제어하는 제어부(140);를 포함하고,상기 제어부(140)는,상기 하우징(110)의 일측면에 장착되어, 조명제공부(120) 및 기포제공부(130)에 전원을 인가하거나 차단하는 전원스위치(141);상기 하우징(110)의 일측면에 장착되어, 조명제공부(120)를 통해 발생되는 조명의 밝기를 제어하는 조명제어스위치(142);상기 하우징(110)의 일측면에 장착되어, 에어펌프(150)의 작동 및 발생되는 기포량을 제어하는 기포제어스위치(143); 및상기 하우징(110)의 일측면에 장착되고, 조명제공부(120)로부터 발생되는 빛의 색상을 변경하는 조명색상 변경스위치(144);를 포함하고,상기 조명제어스위치(142)는, 기설정된 어종에 따른 광 조사 패턴 및 광 조사 유지시간에 따라 조명제공부(120)를 제어하고,상기 기포제어스위치(143)는, 기설정된 어종에 따른 기포 발생 유량, 기포 분사 속도, 기포 크기, 기포 발생 패턴, 기포 발생 유지시간에 따라 기포제공부(130)를 제어하는 것을 특징으로 하는 기포발생기 일체형 집어등., Ltext: 어업, prediction: 임업
166/1059 Row 166: application_number: 1020200041426, combined_string: invention_title: 초고속 갈치낚시 방법 abstract: 본 발명은 초고속 갈치낚시 방법에 관한 것으로, 더욱 상세히는 낚시바늘을 미끼에 연결시 낚시줄이 연결되는 낚시바늘의 고리부분부터 미끼에 삽입시키는 방식으로 낚시바늘을 미끼에 연결하여 갈치의 입걸림을 빠르게 할 수 있는 초고속 갈치낚시 방법에 관한 것이다.본 발명의 초고속 갈치낚시 방법은 후크형 낚시바늘(10)의 상단에 낚시줄(20)을 연결할 수 있는 고리(11)가 형성되고 타단에 바늘코(12)가 형성된 갈치낚시용 낚시바늘을 이용한 갈치낚시 방법에 있어서,일정크기로 잘라 미끼(30)를 준비하는 단계;상기 낚시바늘(10)의 고리(11)부터 상기 미끼(30)에 삽입시켜 고리(11)는 미끼(30)를 관통하여 외부로 노출되고 낚시바늘(10)은 미끼(30)에 삽입된 상태가 되게 미끼(30)에 낚시바늘(10)을 연결하는 단계;상기 고리(11)에 낚시줄(20)을 연결하는 단계로 이루어지는 것을 특징으로 한다. claims: 후크형 낚시바늘(10)의 상단에 낚시줄(20)을 연결할 수 있는 고리(11)가 형성되고 타단에 바늘코(12)가 형성된 갈치낚시용 낚시바늘을 이용한 갈치낚시 방법에 있어서,일정크기로 잘라 미끼(30)를 준비하는 단계;상기 낚시바늘(10)의 고리(11)부터 상기 미끼(30)에 삽입시켜 고리(11)는 미끼(30)를 관통하여 외부로 노출되고 낚시바늘(10)은 미끼(30)에 삽입된 상태가 되게 미끼(30)에 낚시바늘(10)을 연결하는 단계;상기 고리(11)에 낚시줄(20)을 연결하는 단계로 이루어지는 것을 특징으로 하는 초고속 갈치낚시 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

167/1059 Row 167: application_number: 1020190168833, combined_string: invention_title: 오징어낚시용 축광루어 abstract: 본 발명은 오징어낚시용 루어에 관한 것으로서, 구체적으로 축광기능이 구비한 루어를 형성함에 있어서 오징어가 느끼는 이물감을 제거하여 효율적인 오징어낚시를 가능하게 하는 오징어낚시용 축광루어에 관한 것이다.본 발명은 물고기 또는 새우형상을 가지는 루어몸체(100); 상기 루어몸체(100)의 외면을 감싸는 메시상의 섬유재(110); 상기 루어몸체(100)의 후부에 구비되어 오징어가 낚이도록 하는 후크(300)부:를 포함하는 오징어낚시용 루어에 있어서, 상기 루어몸체(100)의 외면과 상기 섬유재(110) 사이에는 몸체(100)의 길이방향으로 축광필름(130)이 적어도 하나이상 부착되되 상기 루어몸체(100)의 길이방향을 따라 형성된 그루브(120)에 부착되도록 하며, 특히 축광필름(130)과 루어몸체(100) 경계에 단차가 없어서 매끄럽게 형성된 것을 특징으로 하는 오징어낚시용 루어이다. claims: 물고기 또는 새우형상을 가지는 루어몸체(100);상기 루어몸체(100)의 외면을 감싸는 메시상의 섬유재(110);상기 루어몸체(100)의 후부에 구비되어 오징어가 낚이도록 하는 후크(300)부:를 포함하는 오징어낚시용 루어에 있어서, 상기 루어몸체(100)의 외면과 상기 섬유재(110) 사이에 축광필름(130)이 구비되되, 상기 축광필름(130)은 상기 루어몸체(100)의 표면에 적어도 하나 이상 부착된 것을 특징으로 하는 오징어낚시용 축광루어., Ltext: 어업, prediction: 어업
168/1059 Row 168: application_number: 1020190143633, combined_string: invention_title: 음향 센서를 이용한 3차원 어구 위치 추적 시스템 및 방법 abstract: 본 발명은 음향 센서를 이용한 3차원 어구 위치 추적 시스템 및 방법에 관한 것으로, 물고기 등의 대상물을 포획하기 위해 해상 또는 해저에 위치하는 자망이나 통발과 같은 어구에서 송출되는 음향신호를 3척의 선박에서 수신하여 개별 선박으로 부터 어구에 설치된 수중 음향센서와의 거리를 산출하고 위경도 좌표값을 이용해 어구의 위치를 3차원적으로 해석 및 추출하여 어구의 위치를 확인하고 신속하고 쉽게 추적 회수가 가능하도록 하는 3차원 어구 위치 추적 시스템 및 방법을 제공한다. claims: 해상 또는 해저에 위치하는 어구(1)에 설치되어 음향신호를 송출하는 수중 음향센서(100)와, 제1 내지 제3 선박(2a,2b,2c)에 구비되어 상기 수중 음향센서(100)로부터 음향신호가 수신되면 거리값을 추출하고 위도 및 경도값을 수집하고 상기 거리값과 위도 및 경도값을 포함하는 선박수집정보를 생성하는 제1 내지 제3 선박용 추적장치(200a,200b,200c)와, 상기 제1 내지 제3 선박용 추적장치(200a,200b,200c)로부터 선박수집정보가 수신되면 3차원 좌표변환을 통해 어구(1)에 설치된 수중 음향센서(100)의 위치를 포함하는 추적정보를 도출하는 관제센터(3)의 추적서버(300)를 포함하는 것을 특징으로 하는 음향 센서를 이용한 3차원 어구 위치 추적 시스템.제1 내지 제3 선박(2a,2b,2c)에 구비되는 제1 내지 제3 선박용 추적장치(200a,200b,200c)로부터 어구(1)에 설치된 음향수신기(210)의 음향신호로부터 산출된 수중 음향센서(100)의 거리값과 GPS수신기(220)에서 수신되는 GPS정보에서 추출된 위도 및 경도값을 을 포함하는 선박수집정보를 수신하여 3차원 좌표계로 변환하는 제1단계; 및 상기 3차원 좌표계로 변환한 선박수집정보를 이용해 상기 수중 음향센서(100)의 위치에 관한 3차원 좌표값(위도, 경도, 수심) 형태의 추적정보를 도출하는 제2단계;를 포함하는 것을 특징으로 하는 음향 센서를 이용한 3차원 어구 위치 추적 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

169/1059 Row 169: application_number: 2020190004280, combined_string: invention_title: 낚시바늘 교정기 abstract: 본 고안은 주로 오징어 낚시 등에 사용되는 두족류 낚시바늘 등을 매우 간편히 교정할 수 있도록 한 낚시바늘 교정기에 관한 것이다.본 고안은 두족류 낚시바늘의 바늘(10)을 바르게 펴서 교정하는 바늘 교정기(1)를 구성함에 있어서, 휘어진 바늘을 바르게 펼 수 있는 교정부(2)와, 상기 교정부(2)를 사용하기위해 교정기(1)를 파지할 수 있도록 하는 파지부(3)로 이루어지며, 상기 교정부(2)는 바깥로 벌어진 바늘(10)을 문질러 마찰시키면서 이와 동시에 안쪽으로 강제로 밀어서 바깥으로 휘어진 바늘(10)이 안쪽으로 다시 휘어지면서 교정될 수 있도록 수정벽(4)으로 형성하고, 상기 수정벽(4)에는 바늘(10)이 제 위치에서 고정되어 이동되도록 요철(41)을 형성하여 낚시바늘 교정기를 구성한 것에 요지가 있다. claims: 두족류 낚시바늘의 바늘(10)을 바르게 펴서 교정하는 바늘 교정기(1)를 구성함에 있어서,휘어진 바늘을 바르게 펼 수 있는 교정부(2)와, 상기 교정부(2)를 사용하기위해 교정기(1)를 파지할 수 있도록 하는 파지부(3)로 이루어진 것을 특징으로 하는 낚시바늘 교정기., Ltext: 어업, prediction: 어업
170/1059 Row 170: application_number: 1020190131568, combined_string: invention_title: 낚시 abstract: 본 발명은 오징어가 프리미끼(60)를 먹잇감으로 인식하여 덥석 물면서 요동치거나 어선의 롤링이 발생될 경우, 오징어는 바늘(62)에 더욱 깊게 낚이면서 저항 및 반항하게 되는데, 이 과정에서 어퍼고정판(41)으로부터 프리미끼(60)가 센터스프링(63)의 탄성에 의해 순간적으로 이격 및 복원되면서 위성수직홀(61b)들 속에 채워진 공기들이 순식간에 수중으로 퍼지면서 공기방울에 의한 주변 오징어의 유인을 극대화시킬 수 있도록 하고, 구체적으로 오징어가 바늘(62)에 낚이면서 빠져나오려고 요동치는 순간 바늘(62)과 함께 움직이는 프리승강봉(61)이 낚싯줄(10)을 타고 센터스프링(63)의 탄성과 더불어 하강 후 복원하면서, 즉 어퍼고정판(41)으로부터 이격 후 다시 맞닿는 과정에서 위성수직홀(61b)들 속에 채워진 공기가 수중으로 퍼져[무수히 많은 공기방울로 퍼져] 주변 오징어의 유인을 극대화시킬 수 있도록 하는 낚시에 관한 발명이다. claims: 낚싯줄(10)에 서로 이격 고정된 어퍼스토퍼(40) 및 언더스토퍼(50)와, 바늘(62)을 지니며 상기 어퍼스토퍼(40) 및 언더스토퍼(50) 사이에서 상기 낚싯줄(10)을 통과시키는 센터수직홀(61a)을 가진 프리미끼(60)를 포함하는 낚시에 있어서,상기 어퍼스토퍼(40)에 마련된 어퍼고정판(41)을 구비하고,상기 프리미끼(60)는 상기 바늘(62)을 지니면서 상기 센터수직홀(61a)로부터 방사상으로 이격 뚫려져 공기가 채워지는 위성수직홀(61b)들을 구비한 프리승강봉(61)과, 상기 어퍼고정판(41) 및 프리승강봉(61)에 상하 고정되면서 상기 낚싯줄(10)을 중심에 두고 상기 센터수직홀(61a) 속으로 끼워져 상기 프리승강봉(61)을 탄성적으로 승강시키되 상기 프리승강봉(61)의 탄성적 상승시 상기 어퍼고정판(41)으로 하여금 상기 위성수직홀(61b)들의 상단을 실링시키도록 하는 반면 상기 프리승강봉(61)의 탄성적 하강시 상기 위성수직홀(61b)들 속의 공기를 수중으로 순식간에 퍼뜨리도록 하는 센터스프링(63)을 포함하는 것을 특징으로 하는 낚시., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

171/1059 Row 171: application_number: 1020190129747, combined_string: invention_title: 낚시바늘 복원장치 abstract: 본 발명은, 사용되어 훼손된 낚시바늘을 원상태로 복원하여 재사용할 수 있도록;낚시몸체와, 상기 낚시몸체에 평면상 중앙을 중심으로 원주방향으로 둘러서 방사상방향으로 고정되는 다수의 갈고리 형상의 낚시바늘들을 가지는 낚시바늘조립체에서, 외측으로 벌어진 상기 낚시바늘을 오므리어 원상태로 복원하도록 된 낚시바늘 복원장치에 있어서; 길이를 가지며 내측에 상기 낚시바늘들이 수용되면서 길이방향으로 이동운동하도록 된 복원공간을 가지는 복원본체;를 포함하여 이루어지되; 상기 복원공간은, 중앙를 중심으로 복원하고자 하는 상기 낚시바늘들의 외측단부들을 각각 연결하는 '원(圓;circle)' 형상의 내벽을 가지는 낚시바늘 복원장치를 제공한다. claims: 낚시몸체와, 상기 낚시몸체에 평면상 중앙을 중심으로 원주방향으로 둘러서 방사상방향으로 고정되는 다수의 갈고리 형상의 낚시바늘들을 가지는 낚시바늘조립체에서, 외측으로 벌어진 상기 낚시바늘을 오므리어 원상태로 복원하도록 된 낚시바늘 복원장치에 있어서;길이를 가지며 내측에 상기 낚시바늘들이 수용되면서 길이방향으로 이동운동하도록 된 복원공간을 가지는 복원본체;를 포함하여 이루어지되;상기 복원공간은,중앙를 중심으로 복원하고자 하는 상기 낚시바늘들의 외측단부들을 각각 연결하는 '원(圓;circle)' 형상의 내벽을 가지는 것을 특징으로 하는 낚시바늘 복원장치., Ltext: 어업, prediction: 어업
172/1059 Row 172: application_number: 1020190123586, combined_string: invention_title: 어류질병 감지장치 및 그 감지방법 abstract: 어류질병 감지장치 및 그 감지방법이 개시된다. 본 발명에 따른 어류질병 감지장치는, 어류에 대한 질병의 종류와 각각의 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 움직임패턴 저장부; 가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 영상신호 수신부; 영상신호 수신부에 의해 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 움직임패턴 분석부; 움직임 분석부에 의해 분석되는 각각의 어류의 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 어류 추출부; 어류 추출부에 의해 추출된 어류에 대응하는 움직임패턴을 움직임패턴 저장부에 저장된 움직임패턴과 비교하는 움직임패턴 비교부; 및 움직임패턴 비교부에 의해 비교되는 결과에 따라 어류 추출부에 의해 추출된 어류에 대한 질병 여부를 판단하는 어류질병 판단부;를 포함하는 것을 특징으로 한다. claims: 어류에 대한 질병의 종류와 각각의 상기 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 움직임패턴 저장부;가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 영상신호 수신부; 상기 영상신호 수신부에 의해 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 움직임패턴 분석부;상기 움직임 분석부에 의해 분석되는 각각의 어류의 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 어류 추출부;상기 어류 추출부에 의해 추출된 어류에 대응하는 움직임패턴을 상기 움직임패턴 저장부에 저장된 움직임패턴과 비교하는 움직임패턴 비교부; 및상기 움직임패턴 비교부에 의해 비교되는 결과에 따라 상기 어류 추출부에 의해 추출된 어류에 대한 질병 여부를 판단하는 어류질병 판단부;를 포함하는 것을 특징으로 하는 어류질병 감지장치.어류질병 감지장치에 의해 수행되는 어류질병 감지방법에 있어서,어류에 대한 질병의 종류와 각각의 상기 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 단계;가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 단계; 상기 카메라로부터 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 단계;분석되는 상기 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 단계;추출된 상기 어류에 대응하는 움직임패턴을 저장된 상기 움직임패턴과 비교하는 단계; 및비교되는 결과에 따라 추출된 상기 어류에 대한 질병 여부를 판단하는 단계;를 포함하는 것을 특징으로 하는 어류질병 감지방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

173/1059 Row 173: application_number: 1020190122208, combined_string: invention_title: 무게조절이 가능한 통발 abstract: 본 발명의 일 실시예에 따른 무게조절이 가능한 통발은, 어류를 포획하는 무게조절이 가능한 통발에 있어서, 아릿줄과 체결되는 체결부, 상기 체결부와 연결되며, 내부에 포획공간이 형성되는 원통형 통발부, 상기 통발부의 하부측에 착탈 가능하도록 연결되며, 상기 어류의 상기 포획공간으로의 통로를 제공하는 어류통로부를 포함하며, 상기 통발부는, 외주면을 따라 함입되어 형성된 채, 자연석 또는 인공석이 삽입되는 함입부를 구비하며, 상기 함입부에 삽입된 상기 자연석 또는 인공석에 의해 수중에서의 침강이 용이하게 할 수 있다. claims: 어류를 포획하는 무게조절이 가능한 통발에 있어서,아릿줄과 체결되는 체결부;상기 체결부와 연결되며, 내부에 포획공간이 형성되는 원통형 통발부;상기 통발부의 하부측에 착탈 가능하도록 연결되며, 상기 어류의 상기 포획공간으로의 통로를 제공하는 어류통로부;를 포함하며,상기 통발부는,외주면을 따라 함입되어 형성된 채, 자연석 또는 인공석이 삽입되는 함입부를 구비하며, 상기 함입부에 삽입된 상기 자연석 또는 인공석에 의해 수중에서의 침강이 용이하게 하고, 상기 통발부는,내부에 포획공간이 형성되는 원통형 통발내피부 및 상기 통발내피부의 외측면을 커버하고, 상기 통발내피부의 외측면과 접촉되는 내측면이 형성되는 원통형 통발외피부를 구비하고,상기 함입부는,상기 통발외피부의 외주면으로부터 함입되어 형성되며, 탄성 재질로 형성되어, 상기 자연석 또는 인공석이 삽입되는 경우, 팽창 탄성 변형되고, 상기 자연석 또는 인공석이 삽입 완료되면, 복원력에 의해 상기 자연석 또는 인공석을 압착하여 이탈을 방지하는 것을 특징으로 하는 무게조절이 가능한 통발., Ltext: 어업, prediction: 어업
174/1059 Row 174: application_number: 1020190120702, combined_string: invention_title: 탐지 영역 스캔 장치 abstract: 탐지 영역 스캔 장치 및 방법이 개시된다. 본 발명은 현재 레이더의 위치 정보와 표적 정보를 포함하는 신호를 수신 받아 탐지 영역 및 스캔 설정 정보에 대한 데이터를 획득하는 데이터 획득부, 스캔 설정 정보를 이용하여 기계적 빔을 조향하는 서보 제어 신호를 생성하는 서보 제어부 및 스캔 설정 정보를 이용하여 전자적 빔을 조향하는 위상 변환 제어 신호를 생성하는 위상 변위기 제어부를 포함함으로써, 좁은 빔폭으로 탐지 영역을 빠르게 스캔할 수 있다. claims: 탐지 영역 스캔 장치에 있어서,현재 레이더의 위치 정보와 표적 정보를 포함하는 신호를 수신 받아 탐지 영역 및 스캔 설정 정보에 대한 데이터를 획득하는 데이터 획득부;상기 스캔 설정 정보를 이용하여 기계적 빔을 조향하는 서보 제어 신호를 생성하는 서보 제어부; 및상기 스캔 설정 정보를 이용하여 전자적 빔을 조향하는 위상 변환 제어 신호를 생성하는 위상 변위기 제어부를 포함하며,상기 스캔 설정 정보는, 표적 탐지를 위한 최소 조사 시간(Dwell Time), 방위각 방향 풋프린트(Foot-print) 값, 고각 방향 풋프린트 값, 김발 조향각 및 김발 스캔 속도를 포함하는 것을 특징으로 하는 탐지 영역 스캔 장치.전자기파를 송수신하는 안테나;상기 안테나에 연결되며 현재 레이더의 위치 정보와 표적 정보를 포함하는 신호를 수신 받아 탐지 영역 및 스캔 설정 정보에 대한 데이터를 획득하는 데이터 획득부;상기 스캔 설정 정보를 이용하여 기계적 빔을 조향하는 서보 제어 신호를 생성하는 서보 제어부; 및상기 스캔 설정 정보를 이용하여 전자적 빔을 조향하는 위상 변환 제어 신호를 생성하는 위상 변위기 제어부를 포함하며,상기 안테나는, 상기 탐지 영역을 스캔하도록 방위각 방향 및 고각 방향 회전 동작하는 김발을 더 포함하며,상기 김발은 서보 제어 신호에 의해 제어되는 것을 특징으로 하는 레이더 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

175/1059 Row 175: application_number: 1020190116681, combined_string: invention_title: 비접촉식 어류 계수 장치 및 계수 방법 abstract: 본 발명은 비접촉식 어류 계수 장치에 관한 것으로, 보다 상세하게는 어류가 유입될 수 있도록 일측면은 입구가 구비되고 상기 입구와 마주 보는 타측면에는 출구가 형성된 내부가 비어 있는 몸체부; 및 상기 몸체부를 통과하는 어류의 크기 및/또는 개체수를 측정하기 위한 측정수단이 상기 몸체부 소정 영역에 구비된 것을 특징으로 하는 비접촉식 어류 계수 장치에 관한 것이다. claims: 어류가 유입될 수 있도록 일측면은 입구(111)가 구비되고 상기 입구(111)와 마주 보는 타측면에는 출구(112)가 형성된 내부가 비어 있는 몸체부(100); 및상기 몸체부(100)를 통과하는 어류의 크기 및/또는 개체수를 측정하기 위한 측정수단이 상기 몸체부(100) 소정 영역에 구비되되,상기 몸체부(100)는 입구(111) 및 상기 입구(111)와 마주 보는 타측면에 출구(112)가 구비되고, 천정면과 바닥면의 소정 영역이 개구되어 있으며, 높이 조절이 가능하도록 측면이 주름진 형상인 통로 본체부(110); 상기 통로 본체부(110)의 상면에 위치하는 상판부(120); 및 하면 외부에 위치하는 하판부(130)를 포함하되, 상기 상판부(120)에는 천정면 개구부와 대응되는 상판 개구부(121), 상기 하판부(130)에는 바닥면 개구부와 대응되는 하판 개구부(131)가 형성되고,상기 상판 개구부(121)와 하판 개구부(131)에 각각 안착되는 1개 이상의 센싱부(200)를 포함하는 것을 특징으로 하는 비접촉식 어류 계수 장치.청구항 제1항에 기재된 비접촉식 어류 계수 장치를 이용한 어류 계수 방법에 있어서,어류의 종류와 크기를 고려하여 어류 계수 장치의 통로 본체부(110) 높이를 조절하는 단계;통로 본체부(110) 상부와 하부에 센싱부(200)를 고정한 후, 케이지(C)에 어류 계수 장치를 설치하는 단계; 및센싱부(200)에 전원을 공급하여 통로 본체부(110)를 이동하는 어류를 계수하는 단계를 포함하는 것을 특징으로 하는 비접촉식 어류 계수 장치를 이용한 어류 계수 방법., Ltext: 어업, prediction: 어업
176/1059 Row 176: application_number: 1020190110239, combined_string: invention_title: 휴대용 수중 집어등 abstract: 본 발명은 수중에서 양의 주광성을 갖는 어종을 효과적으로 유인할 수 있도록 구성된 휴대용 수중 집어등에 관한 것으로, 상세하게는 평판 형상을 갖는 둘 이상의 단위 발광면이 상호 연결된 본체; 상기 단위 발광면에 장착되어 빛을 조사하는 광원부재; 및 상기 본체의 상단에 결합되는 부력구;를 포함하는 것이 특징이다. claims: 평판 형상을 갖는 둘 이상의 단위 발광면이 상호 연결된 본체;상기 단위 발광면에 장착되어 빛을 조사하는 광원부재; 및상기 본체의 상단에 결합되는 부력구;를 포함하는 것을 특징으로 하는 휴대용 수중 집어등., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

177/1059 Row 177: application_number: 1020190104059, combined_string: invention_title: 문어 낚시용 어구 abstract: 본 발명은 각 바늘의 각각의 연결고리가 봉돌의 후면으로 동시에 같이 돌출되어 각 바늘의 유동성을 방지하면서 봉돌에 크랙(crack)이 발생하지 않도록 봉돌에 매설되는 중앙 바늘, 측면 바늘 및 상부 바늘의 각 연결고리는 봉돌의 후면으로 각각 돌출되게 형성되되, 상기 각 연결고리는 하부에 상부 바늘의 연결고리가, 상기 상부 바늘의 연결고리 상부에 측면 바늘의 연결고리가, 상기 측면 바늘의 연결고리 상부에 중앙 바늘의 연결고리가 순차적으로 배치되도록 형성되는 문어 낚시용 어구를 제공한다. 그에 따라 낚싯줄 또는 맨도래와 연결되는 각 연결고리의 높은 강성으로 인해 분실을 최소화함은 물론 오랜 사용기간을 확보할 수 있는 효과와 함께 어구에 대한 높은 신뢰성을 확보할 수 있는 효과 또한 가진다. claims: 각 선단이 후크 형태로 절곡 형성되며, 각 중앙을 절곡하여 각각의 연결고리가 형성되는 중앙 바늘과, 측면 바늘 및 상부 바늘의 일부가 중량체인 봉돌에 매설되어 형성되는 문어 낚시용 어구로서, 상기 중앙 바늘, 측면 바늘 및 상부 바늘의 각 연결고리는 봉돌의 후면으로 각각 돌출되게 형성되되, 상기 각 연결고리는 하부에 상부 바늘의 연결고리가, 상기 상부 바늘의 연결고리 상부에 측면 바늘의 연결고리가, 상기 측면 바늘의 연결고리 상부에 중앙 바늘의 연결고리가 순차적으로 배치되도록 형성되는 문어 낚시용 어구., Ltext: 어업, prediction: 어업
178/1059 Row 178: application_number: 1020190097614, combined_string: invention_title: 낚시대 바늘 고정판 abstract: 나의 발명은 낚시대에 달려 있는 알루미늄으로 만들어진 제품이고 그곳에 구멍이 뚫려 있다. 그곳에 바늘을 꼽아 바람에 날리지 않게 한다. claims: 알루미늄 판이 구부러져 있고 알루미늄 판에 구멍이 5매가 뚫려 있다. 또 구멍이 휘어져 있어 구멍에 일치한다. 이 알루미늄 판은 바늘이 바람에 날리지 않도록 방지하고 바늘이 사람에게 꼽히지 않는 것을 도와준다., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

179/1059 Row 179: application_number: 1020190092782, combined_string: invention_title: 낚시바늘 미늘추가장치 abstract: 기존 낚시바늘의 미늘(20)에 미끼를 고정할수 있는 미늘장치(50)을 설치하여 바다낚시, 민물낚시, 루어낚시등 다양하게 이용중인 낚시의 바늘에 미끼를 더욱 더 견고하게 고정하고 어류의 입질을 더 강력하게 유도하기 위한 장치 claims: 기존 낚시바늘의 구성에서 바다낚시, 민물낚시, 루어낚시등 모든 낚시에서 미늘이 사용중인 각각의 바늘(감성돔용, 벵에돔용, 참돔용, 부시리용, 농어용, 방어용, 우럭용, 볼락용, 학꽁치용, 메가리,전갱이용, 전어용,고등어용 카드채비, 가물치용, 붕어용, 잉어용, 향어용, 루어낚시용 싱글훅, 더블훅, 트레블훅등)에 추가된 미끼고정용 낚시바늘 미늘장치(50)청구항 2청구항 1에 있어서 때에 따라 여러개의 미늘(50)장치를 낚시바늘의 안쪽으로 추가하는 장치, Ltext: 어업, prediction: 어업
180/1059 Row 180: application_number: 1020190084217, combined_string: invention_title: 집어등 abstract: 본 발명은 집어등에 관한 것으로, 상부플레이트, 하부플레이트, 조명유닛, 상부 고정유닛을 포함하되 하부 고정유닛을 더 포함함으로써 하부 고정유닛을 통하여 선박의 흔들림에도 상단과 함께 하단부분이 안정적으로 고정될 수 있도록 하여 집어등의 상단은 물론 하단부분의 유동 발생을 방지할 수 있도록 하는 한편, 상단과 함께 하단부분의 유동 발생을 방지함으로써 집어를 위한 조명이 해수면 측으로 안정적으로 비추어지도록 함과 동시에 이웃하는 집어등과의 충돌 및 충돌로 인한 파손을 방지할 수 있도록 하는 한편, 조명유닛 자체 및 조명유닛의 점등상태를 제어하는 컨트롤패널에 대한 방수기능을 한층 강화시킬 수 있도록 하며, 조명빛에 유인되어 날아든 불나방 등의 곤충의 사체가 아랫쪽으로 손쉽게 배출될 수 있도록 하고, 각각의 조명유닛으로부터 발생되는 열이 보다 신속하게 강제 배출되도록 하여 단위 시간당 열방출효율을 극대화시킬 수 있도록 하는 것이다. claims: 어업용 선박의 둘레부분 상, 하부에 상하방향으로 일정간격을 가지고 상호 평행이 되도록 설치된 상, 하부 장착 와이어(10, 20)에 대하여 상부 장착 와이어(10)에 상단이 고정설치되며 하부 장착 와이어(20)에 하단이 고정설치되는 집어등(100)에 있어서, 원판 상으로 제공되며, 중앙부분에 양측으로 일정간격을 가지고 설치공(113)이 관통형성되는 상부플레이트(110)와; 상기 상부플레이트(110)의 하부에 일정거리 떨어져 배치되되 상기 상부플레이트(110)와 대응되는 원판 상으로 제공되며, 중앙부분에 일정지름을 가지고 상기 상부플레이트(110)와의 사이 공간내로 외부의 찬 공기가 유입될 수 있도록 하는 흡기공(121)이 관통형성되고, 상기 흡기공(121)의 양측에 설치공(123)이 관통형성되는 하부플레이트(120)와; 조명을 비추기 위한 일면이 호형으로 돌출형성되는 바 타입으로 제공되며, 상기 상부플레이트(110)와 하부플레이트(120) 사이의 둘레방향을 따라 다수 개로 연이어 배치되어 상단이 상기 상부플레이트(110)의 하면에 고정설치되고 하단이 상기 하부플레이트(120)의 상면에 고정설치되는 조명유닛(130)과; 상기 하부플레이트(120)상의 흡기공(121) 상부에 배치되어 둘레부분이 상기 흡기공(121) 상면 둘레부분에 고정설치되는 모터팬(140); 하단의 절곡된 단부가 상기 상부플레이트(110)의 설치공(113)을 관통하여 상기 상부플레이트(110) 하면에 밀착된 상태로 연결부재를 통해 연결고정되고, 상부에 상기 상부 장착 와이어(10)의 단면 1/2과 대응되게 상부 설치홈(153)이 절곡형성되는 상부 고정편(151)이 한 쌍으로 대향되어 밀착된 후 결합부재를 통해 밀착설치되는 상부 고정유닛(150); 및 상단이 상기 하부플레이트(120) 하측으로부터 상향 관통하여 연결부재를 통해 연결고정되며, 하부에 상기 하부 장착 와이어(20)가 삽입고정되도록 하는 하부 고정유닛(160)을 포함하여 이루어진 집어등., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

181/1059 Row 181: application_number: 1020190082851, combined_string: invention_title: 물김처리장치 abstract: 본 발명은 물김처리장치이다. 양식장의 김발에서 채취된 물김을 다수개의 물김포대(30)에 직접 낙하되어 모아지도록 한다. 상기 물김포대(30)는 물김채취선(10)의 갑판에 설치된 프레임(20)의 포대공간(207)에 안착된다. 물김이 채워진 물김포대(30)를 크레인(40)이 인양하는데, 크레인(40)의 인양라인(41)에 설치된 로드셀(43)은 물김의 무게를 측정하여 외부의 단말기(49,50,51)들로 전송한다. 상기 포대공간(207)은 입출구(208)쪽의 횡단면적이 상대적으로 넓고 바닥쪽이 상대적으로 좁게 되어 크레인(40)으로 물김포대(40)를 쉽게 들어올 릴 수 있다. claims: 물김채취선 상에 설치되고 포대공간이 다수개의 행과 열을 가지도록 배치되는 프레임과,상기 포대공간에 위치되고 내부에 물김이 채워지는 물김포대와,상기 프레임에 설치된 레일을 따라 이동하면서 상기 각각의 포대공간의 행의 위치에서 물김을 채취하여 포대공간에 설치된 물김포대에 낙하시키는 채취이동유닛을 포함하는 물김처리장치., Ltext: 어업, prediction: 임업
182/1059 Row 182: application_number: 1020190080012, combined_string: invention_title: 부표 abstract: 본 발명은 이너수평층간뭉치(100) 및 아우터수직층간뭉치(200)에 의한 쿠션력의 극대화는 물론이거니와 수평방향 및 수직방향으로의 견고함을 동시에 보장하여 로프로 묶을 때 특히 수평방향으로의 찌그러짐[쉽게 찌그러질 경우 최외곽표면융착층(200a)의 파손으로 바닷물이 침투되어 수명이 단축됨]을 방지토록 함으로써 해양시설물과의 설치시 더욱 강도 높은 결합을 가능케 한 부표에 관한 발명이다. claims: 1차 발포된 합성수지발포원판(111)들을 수평층간갭(111d)이 형성되도록 적층시킨 원판뭉치(110)를 제1히팅금형 속에 넣어 2차 발포시키면서 외곽표면융착층(100a)을 지니도록 한 이너수평층간뭉치(100)와,상기 이너수평층간뭉치(100)의 외연을 따라 1차 발포된 합성수지발포시트(211)를 와인딩시켜 상기 수평층간갭(111d)과 직교되는 수직층간갭(211d)이 형성되도록 와인딩시킨 와인딩뭉치를 제2히팅금형 속에 넣어 3차 발포시키면서 최외곽표면융착층(200a)을 지니도록 한 아우터수직층간뭉치(200)를 포함하는 것을 특징으로 하는 부표., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

183/1059 Row 183: application_number: 1020190079468, combined_string: invention_title: 해류에 능동적 대응하는 수중 집어등 abstract: 본 발명은 용기 형태의 프레임 표면에 LED를 부착하여 수중에서 광선의 조사범위를 넓히고, 안정적으로 해류의 흐름에 대응할 수 있도록 평판을 수직으로 설치해 물의 저항을 최소화하여 어종을 보다 효과적으로 유인할 수 있도록 한 수중 집어등에 관한 것으로, 수중에 조명을 투광하여 어류를 조획하기 위한 집어등에 있어서, 속이 빈 용기 형상으로 개구면이 구비된 프레임부; 상기 프레임부의 중심에 위치하는 무게추부; 및 상기 프레임부의 외면에 장착되어 광을 조사하는 조명부;를 포함하는 것이 특징이다. claims: 수중에 조명을 투광하여 어류를 조획하기 위한 집어등에 있어서,속이 빈 용기 형상으로 개구면이 구비된 프레임부;상기 프레임부의 중심에 위치하는 무게추부; 및상기 프레임부의 외면에 장착되어 광을 조사하는 조명부;를 포함하는 것을 특징으로 하는 해류에 능동적 대응하는 수중 집어등., Ltext: 어업, prediction: 어업
184/1059 Row 184: application_number: 1020190077433, combined_string: invention_title: 수압으로 램프를 작동시키는 집어등 abstract: 본 발명은 심해용 집어등에 관한 것으로, 더욱 상세하게는 공기가 들어 있는 폐쇄 용기를 물속에 넣으면 수압을 받아 부피가 줄어들면서 압착되는 힘을 이용하여 전원스위치를 ON 시켜서 램프를 점등하고, 물 밖으로 나오면 수압이 0으로 낮아지면서 수축되었던 폐쇄 용기가 원래 형상으로 복원되는 힘으로 전원스위치를 OFF 시켜서 램프를 소등하는 수압으로 램프를 작동하는 집어등에 관한 것이다 본 고안에 의한 수압으로 램프를 작동하는 집어등은, 램프와 스위치 등 내부회로와 건전지로 구성된 모듈에서 램프의 - 단자와 건전지의 - 단자를 직결하고, 램프의 + 단자와 건전지의 + 단자는 수평으로 배치하여 상기 단자 중에서 어느 하나가 수압을 받아 상대 단자가 있는 방향으로 힘을 받으면 접속되는 스위치, 상기 스위치가 포함된 모듈을 연질의 통형상 케이스에 넣고 수밀되게 밀봉하되, 스위치가 있는 부분은 공기방이 형성된 케이스로 구성되는 특징이 있다. 이와 같은 본 고안에 의하면, 램프를 작동하기 위한 별도의 조작이 필요 없고, 자동으로 물속에서 점등시키고 물 밖에서는 소등시킬 수 있으므로 전원을 효율적으로 사용할 수 있을 뿐만 아니라, 구조를 간단하게 변형하여 수동으로 작동 가능하게 할 수 있고, 소형으로 제작 가능하므로 바늘에 근접 사용이 가능하며, 원과 같은 인조미끼에 삽입하여 집어 기능을 극대화할 수 있는 기능을 제공할 수 있는 특징을 가진 수압에 의해 램프를 작동하는 집어등이다. claims: 램프와 건전지와 스위치 등으로 구성된 모듈과 상기 모듈을 수압으로부터 보호하기 위한 케이스로 구성된 집어등에 관한 것으로, 램프와 건전지의 +, - 전원단자 중에서 어느 하나 이상이 상대 전원단자 방향으로 힘을 받아 움직이면 접속되는 스위치로 구성된 모듈과; 상기 모듈이 삽입되는 투명한 연질의 재료를 사용한 통형상 케이스와; 상기 연질의 통형상 케이스에 있어서 램프와 건전지의 전원단자가 스위치로 기능하는 부분에 공기방(13)을 형성한 것을 특징으로 하는 수압으로 램프를 작동시키는 집어등, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

185/1059 Row 185: application_number: 1020190072936, combined_string: invention_title: 미케니컬 조인트방식으로 제조된 어업용 부표 abstract: 본 발명은 어업용 부표에 관한 것으로, 구체적으로는 몸체를 좌, 우로 별도 형성시키어 각각의 끝단을 미케니컬 조인트방식으로 접합시킨 구조의 어업용 부표에 관한 것이다.본 발명은 두 개의 몸체를 조인트접합방식을 통해 결합시킴으로써 내부가 중공상태인 부표를 제공함으로써 기밀을 유지하고 좌우 고리형상으로 밀폐되어 접합된 부분이 분리되지 않는 형상의 부표를 제공함으로써 불량률이 개선되는 효과가 있다. 또한 본 발명의 부표를 알루미늄으로 제조함으로써 내구성 강화 및 경량강화가 가능한 효과가 있다. claims: 일측이 개방된 형태로 내부공간이 형성되는 제1몸체부(110)와,상기 제1몸체부(110)와 접합되도록 제1몸체부(110)와 대응된 형태로 형성되되, 일측이 개방된 형태로 내부공간을 포함하여 형성되는 제2몸체부(120)와,제1몸체부(110)의 제1접합부(111)와 제2몸체부(120)의 제2접합부(121) 사이에 위치하는 실링부(130)와,상기 제1몸체부(110)의 일측에 형성되는 공기주입부(140)를 포함하되,상기 제1몸체부(110)는제1몸체부(110)의 끝단을 둘러싸되 바깥방향으로 돌출되어 형성되는 제1접합부(111)를 포함하고,상기 제2몸체부(120)는제2몸체부(120)의 끝단을 둘러싸되 바깥방향으로 돌출되어 형성되며, 상기 제1접합부(111)와 실링부(130)가 삽입되도록 제2몸체부(120)의 내부 방향으로 ‘ㄷ’자 형태로 구부러져서 형성되는 제2접합부(121)를 포함하는 것을 특징으로 하는 어업용 부표.일측이 개방된 형태로 내부공간이 형성되되, 몸체가 원통으로 이루어지고 끝단이 반구형태로 형성되는 제1몸체부(110)와, 일측이 개방된 형태로 내부공간이 형성되되, 몸체가 원통으로 이루어지고 끝단이 반구형태로 형성되되 제2몸체부(120)와,제1몸체부(110)의 제1접합부(111)와 제2몸체부(120)의 제2접합부(121) 사이에 위치하는 실링부(130)와,상기 제2몸체부(120)의 공기주입부보호홈(123)에 위치하되 공기가 주입되도록 형성되는 공기주입부(140)를 포함하되,상기 제1몸체부(110)는상기 제1몸체부(110)의 끝단에 바깥방향으로 돌출되어 형성되는 제1접합부(111)와, 제1몸체부(110)의 일측에 형성되되, 양식로프체결줄이 형성되기 위한 제1홈(112)을 포함하고,상기 제2몸체부(120)는상기 제1접합부(111)가 삽입되도록 제2몸체부(120)의 내부 방향으로 ‘ㄷ’자로 구부러진 형태로 형성되는 제2접합부(121)와,제2몸체부(120)의 일측에 형성되되, 양식로프체결줄이 형성되기 위한 제2홈(122)와,공기주입부(140)가 위치하기 위해 제2몸체부(120)의 일측에 함몰되어 형성되는 공기주입부보호홈(123)를 포함하되,상기 제1몸체부(110)의 제1접합부(111)와 제2몸체부(120)의 제2접합부(121)는 미케니컬 조인트 방식으로 접합되는 것을 특징으로 하는 어업용 부표., Ltext: 어업, prediction: 어업
186/1059 Row 186: application_number: 1020190056960, combined_string: invention_title: 탈착식 미노우 에깅 훅 abstract: 본 발명은 육식어종(농어,우럭,광어)낚시에 사용되는 루어(lure=모형 물고기),혹은 미노우에 오징어 낚시등에 주로 사용되는 두족류 낚시바늘을 간편하게 연결하여,한가지 루어로 육식어종과 오징어 낚시를 동시에 즐길수 있게 하기 위한 탈부착식 두족류 낚시바늘에 관한 것이다. claims: 끝부분에 축광 에폭시(06)를 삽입하여 완성하는 두족류 전용바늘(01)과 이를 다른 두족류 전용바늘(02)에 연결 고정시키는 유리섬유(03)와;상기 두족류 전용바늘(02)과 결합하여 스냅(05)과 연결 시켜주는 롤링스위벨(04) 로 구성되는 탈착식 자유형 미노우 에깅훅(100)에 있어서;상기 두족류 전용바늘(02) 내부에 공간을 확보하여 롤링스위벨(04)을 삽입.고정하고;스냅(05)은 분해한여 롤링스위벨(04)과 연결한 후 다시 체결하여;루어의 뒤쪽 바늘을 제거한 상태의 루어(10)에 손쉽게 탈착과 부착이 가능하도록 구성하여 물속에서 자유롭게 움직일수 있도록 하는 특징의 탈착식 자유형 미노우 에깅훅(100).끝부분에 축광 에폭시(06)를 삽입하여 완성하는 바깥쪽 두족류 전용바늘(01)과 이를 다른 안쪽 두족류 전용바늘(02)에 연결 고정시키는 유리섬유(03)로 구성되는 두족류 전용 바늘묶음(07)과;상기 두족류 전용 바늘묶음(07)을 루어의 뒤쪽 바늘을 제거한 상태의 루어(10)에 움직이지 않도록 고정시켜 연결하기 위하여 발명된 축광 플라스틱(08)과 고정핀(09)으로 구성되는 탈착식 고정형 미노우 에깅훅(101)에 있어서;상기 축광 플라스틱(06)은 상기 두족류 전용 바늘묶음(07)의 유리섬유가 삽입될수 있는 구멍을 내어 삽입하고 에폭시로 고정하며; 상기 축광 플라스틱(08)은 루어의 뒤쪽 바늘을 제거한 상태의 루어(10)의 쇠고리 부분이 삽입되어 고정될수 있도록 홈을 내고 고정핀(09)이 들어갈 구멍을 내어 결속할수 있도록 하여; 루어의 뒤쪽 바늘을 제거한 상태의 루어(10)에 손쉽게 탈착과 부착이 가능하도록 구성하고 루어에 단단하게 고정되어 움직일수 있도록 하는 특징의 탈착식 고정형 미노우 에깅훅(101)., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

187/1059 Row 187: application_number: 1020190030417, combined_string: invention_title: 집어등 빛 그림자 조절장치 abstract: 본 발명은 집어등(L)이 장착된 파이프(80)를 어선(S)의 현(H)방향으로 근접시켜 현(H)에 의한 바다 속 그림자 영역을 작게 형성함과 더불어 집어등(L)의 빛 영역을 더 근접하게 형성시킬 수 있도록 하는 반면 집어등(L)이 장착된 파이프(80)를 갑판(G)의 중심방향으로 근접시켜 현(H)에 의한 바다 속 그림자 영역을 크게 형성함과 더불어 집어등(L)의 빛 영역을 더 멀리 형성시킬 수 있도록 하여, 즉 집어등(L)의 명암의 영역을 현(H)을 기점으로 한 횡바(70)들을 따라 파이프(80)의 신속 간단한 이동으로 일거에 조절 가능하게 하여, 야간 달빛의 영향이나 배의 크기 및 높이 또는 어류의 각 특성에 맞는 조업활동을 보다 적극적으로 대응케 하여 어획량을 극대화시킬 수 있도록 한 집어등 빛 그림자 조절장치에 관한 발명이다. claims: 어선(S)의 현(H)으로부터 평행하게 이격되는 갑판(G) 위에 수직으로 병렬 세워진 제1열서포터(41) 및 제2열서포터(42)와,상기 제1열서포터(41) 및 제2열서포터(42)의 상부를 가로질러 고정된 횡바(70)들과,집어등(L)을 등간격으로 장착하여 상기 횡바(70)들을 따라 상기 어선(S)의 현(H)방향으로 또는 상기 갑판(G)의 중심방향으로 이동하면서 상기 현(H)을 기점으로 바다를 향한 상기 집어등(L)의 빛과 그림자를 조절하는 파이프(80)와,상기 파이프(80)를 상기 횡바(70)들에 착탈 가능하게 고정시키는 착탈수단(90)을 포함하는 것을 특징으로 하는 집어등 빛 그림자 조절장치., Ltext: 어업, prediction: 임업
188/1059 Row 188: application_number: 1020190028232, combined_string: invention_title: 사각통그물망을 구비한 정치어망 abstract: 정치어망용 사각통그물망에 관한 것으로, 회유성 어류가 통그물로 유인되도록 육지에서 바다를 향해 일직선상으로 설치되는 유도망; 상기 유도망과 함께 회유성 어류가 유인되도록 상기 유도망의 좌우 양측에 소정의 각도로 경사지게 설치되는 보조유도망; 상기 유도망과 상기 보조유도망으로 유인된 회유성 어류가 머물 수 있도록 상기 유도망 및 상기 보조유도망으로부터 소정의 거리만큼 이격되어 설치되는 통그물; 회유성 어류가 사각통그물망으로 이동되도록 상기 통그물의 일측에 설치되는 노부리; 상기 사각통그물망으로 이동된 어류가 상기 통그물로의 이동을 제한하도록 상기 노부리의 일측에 설치되는 조구; 회유성 어류를 포획하도록 상기 조구의 일측에 설치되는 사각통그물망;을 마련하여 사각통그물망의 길이를 선박의 길이보다 길게 설치할 수 있고, 길이가 길게 설치된 사각통그물망에 대량의 어류를 수용할 수 있으며, 사각통그물망의 상면그물망에 의해 수면을 따라 이동하는 회유성 어류를 포획할 수 있다는 효과가 얻어진다. claims: 회유성 어류가 통그물로 유인되도록 육지에서 바다를 향해 일직선상으로 설치되는 유도망;상기 유도망과 함께 회유성 어류가 유인되도록 상기 유도망의 좌우 양측에 소정의 각도로 경사지게 설치되는 보조유도망;상기 유도망과 상기 보조유도망으로 유인된 회유성 어류가 머물 수 있도록 상기 유도망 및 상기 보조유도망으로부터 소정의 거리만큼 이격되어 설치되는 통그물;회유성 어류가 사각통그물망으로 이동되도록 상기 통그물의 일측에 설치되는 노부리;상기 사각통그물망으로 이동된 어류가 상기 통그물로의 이동을 제한하도록 상기 노부리의 일측에 설치되는 조구;회유성 어류를 포획하도록 상기 조구의 일측에 설치되는 사각통그물망;을 포함하며,상기 사각통그물망은 수면에 접하는 상면그물망이 일체로 이루어지는 것을 특징으로 하는 정치어망용 사각통그물망., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

189/1059 Row 189: application_number: 1020190028222, combined_string: invention_title: 보조유도망이 구비된 정치어망 abstract: 보조유도망이 구비된 정치어망에 관한 것으로, 어류의 유입을 안내하도록 일직선상으로 설치되는 유도망; 상기 유도망의 선단에 유입된 어류가 자유로이 움직일 수 있게 공간을 제공하도록 상기 유도망의 선단에 설치되는 통그물; 상기 통그물의 어류가 원통으로 이동하도록 상기 통그물의 일측에 설치되는 노부리; 상기 노부리를 통과한 어류가 상기 통그물로 이탈되지 않도록 상기 노부리의 일측에 설치되는 조구; 상기 조구를 통과한 어류가 포획되도록 상기 조구의 일측에 설치되는 원통;을 포함하며, 회유성 어류가 상기 유도망을 거쳐 상기 통그물 내부로의 이동을 안내하도록 상기 통그물의 양측에 각각 소정 거리만큼 이격되게 설치되는 보조유도망;을 마련하여 유도망의 좌우 양측에 보조유도망을 설치하여 선회하는 어류의 이동을 통그물로 유도하게 되고, 유도망과 보조유도망을 고정로프로 안정적으로 고정시켜 둠으로써 어류의 이동 경로를 확보할 수 있으며, 보조유도망이 유도망의 선단으로부터 보다 길게 연장 형성되어 어류의 유인을 확보할 수 있다는 효과가 얻어진다. claims: 어류의 유입을 안내하도록 일직선상으로 설치되는 유도망;상기 유도망의 선단에 유입된 어류가 자유로이 움직일 수 있게 공간을 제공하도록 상기 유도망의 선단에 설치되는 통그물;상기 통그물의 어류가 원통으로 이동하도록 상기 통그물의 일측에 설치되는 노부리;상기 노부리를 통과한 어류가 상기 통그물로 이탈되지 않도록 상기 노부리의 일측에 설치되는 조구;상기 조구를 통과한 어류가 포획되도록 상기 조구의 일측에 설치되는 원통;회유성 어류가 상기 유도망을 거쳐 상기 통그물 내부로의 이동을 안내하도록 상기 유도망의 양측에 각각 소정 거리만큼 이격되게 설치되는 보조유도망;을 포함하며,상기 보조유도망은 상기 유도망의 일측에 설치되는 제1 보조유도망과 상기 유도망의 타측에 설치되는 제2 보조유도망으로 이루어지고,상기 제1 보조유도망 및 상기 제2 보조유도망 각각의 일단은 상기 유도망의 선단으로부터 육지 방향으로 보다 돌출되게 설치되고,상기 제1 보조유도망 및 상기 제2 보조유도망 각각의 타단은 상기 통그물의 입구로부터 소정의 거리만큼 이격되게 설치되어 회유성 어류가 상기 유도망 및 상기 보조유도망 사이를 통해 회유되면서 상기 통그물의 내측으로 이동되게 설치되는 것을 특징으로 하는 보조유도망이 구비된 정치어망., Ltext: 어업, prediction: 어업
190/1059 Row 190: application_number: 1020190021312, combined_string: invention_title: 어업용 부구 abstract: 본 발명은, 내부에 빈공간을 가지도록 일측이 개방되며, 내주면에는 개방 단부의 모서리 방향과 직각 방향으로 복수개의 보강 리브가 상호 소정 간격 이격된 채로 돌출 형성되며, 상기 개방 단부가 맞닿아 상호 접합되도록 구성된 제1 및 제2 반구형 몸체; 및 상기 제1 및 제2 반구형 몸체의 개방 단부의 내주면과 접촉하여 이를 보강 지지하는 보강 프레임을 포함하는 어업용 부구를 개시한다. claims: 내부에 빈공간을 가지도록 일측이 개방되며, 내주면에는 개방 단부의 모서리 방향과 직각 방향으로 복수개의 보강 리브가 상호 소정 간격 이격된 채로 돌출 형성되며, 상기 개방 단부가 맞닿아 상호 접합되도록 구성된 제1 및 제2 반구형 몸체; 및상기 제1 및 제2 반구형 몸체의 개방 단부의 내주면과 접촉하여 이를 보강 지지하는 보강 프레임을 포함하는 것을 특징으로 하는 어업용 부구., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

191/1059 Row 191: application_number: 1020190021335, combined_string: invention_title: 김 채취기용 분배장치 abstract: 본 발명은 중간부는 높고 양쪽으로 갈 수록 경사가 낮아지는 경사판과, 상기 경사판의 양쪽에 절곡되어 김의 이탈을 방지하기 위한 차단판과, 경사판의 일측에는 선박의 갑판 중간부에 배치되는 저장통의 입구와 일치하도록 통공이 통공되고, 상기 통공의 양측에 형성된 슬라이드부를 따라 이동가능하면서 통공을 막기위한 슬라이드판으로 구성되는 김 채취기용 분배장치를 제공하기 위한 것으로, 본 발명의 효과로는 본 발명의 효과로는 김 채취기용 분배장치는, 중간부는 높고 양쪽으로 갈 수록 경사가 낮아지는 경사판이 김채취기 하부에 부착되므로 상기 김채취기에 의해 절단된 김이 아래로 쏟아질 때 경사판을 타고 흐르게 되는데, 이때 슬라이드판에 의해 통공의 넓이가 조절가능하게 되어 작업자가 중앙에 배치된 저장통에 적당한 양의 김이 쏟아지도록 하고, 또 통공을 지나친 김들은 경사판의 양쪽으로 배출되어 가장자리 저장통에 저장되도록 함으로써 모든 저장통에 균일한 양의 김을 채울 수 있어 김 수확량을 늘일 수 있는 매우 유용한 발명인 것이다. claims: 중간부는 높고 양쪽으로 갈 수록 경사가 낮아지는 경사판과, 상기 경사판의 양쪽에 절곡되어 김의 이탈을 방지하기 위한 차단판과, 경사판의 일측에는 선박의 갑판 중간부에 배치되는 저장통의 입구와 일치하도록 통공이 통공되고, 상기 통공의 양측에 형성된 슬라이드부를 따라 이동가능하면서 통공을 막기위한 슬라이드판으로 구성됨을 특징으로 하는 김 채취기용 분배장치., Ltext: 어업, prediction: 임업
192/1059 Row 192: application_number: 2020190000251, combined_string: invention_title: 수중 집어등을 수용하는 낚시추 조립체 abstract: 본 고안은 낚시추 조립체에 관한 것으로서, 보다 구체적으로는 수중 집어등을 수용하는 낚시추 조립체에 관한 것이다. 본 고안의 일 실시예에 따르면, 복수의 리브(22) 및 복수의 리브(22) 각 사이에 형성되는 윈도우(32)를 포함하는 상부 하우징(2); 및 상부 하우징(2)과 분리 가능하게 결합되고 내부에 공간(14)을 포함하며 기 설정된 무게로 구성되는 하부 하우징(4);을 포함하는 낚시추 조립체가 제공된다. claims: 복수의 리브 및 상기 복수의 리브 각 사이에 형성되는 윈도우를 포함하고, 상기 복수의 리브 중 각 리브의 일 측을 일체로 결합하는 접합부 및 상기 복수의 리브 중 각 리브의 타 측을 결합하는 결합부를 포함하는 상부 하우징; 상기 상부 하우징과 상기 결합부에 의해 분리 가능하게 결합되고 내부에 공간을 포함하며 기 설정된 무게로 구성되는 하부 하우징;상기 상부 하우징 및 하부 하우징 내부에 수용되고, 내측에 램프가 장착되고 빛이 투과하도록 형성되며 상기 상부 하우징 내에 배치되는 상부 구조체 및 상기 상부 구조체와 수밀하게 결합하고 램프에 전원을 공급하는 전원공급부가 배치되는 하부 구조체를 포함하는 집어등 구조체; 상기 하부 하우징의 내측에 고정 형성되고 상기 하부 구조체를 고정하는 인서트; 및상기 접합부, 상부 구조체 및 하부 구조체를 관통하는 로드;를 포함하고, 상기 로드의 일 측에는 수평방향으로 관통 형성되는 홀이 형성되고, 상기 로드의 타 측에는 상기 인서트와 분리가능하게 결합하는 고정부가 형성되는 것인 수중 집어등을 수용하는 낚시추 조립체., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

193/1059 Row 193: application_number: 1020190002961, combined_string: invention_title: 낚시바늘 결합구 제작방법 abstract: 본발명은 낚시바늘 결합구 제작방법에 관한 것으로, 다수개의 낚시바늘에 인조미끼를 꿰어서 낚시를 하기 위하여, 다수개의 낚시바늘이 하부에 각각 연결되는 다수개의 걸이부(100)와, 상기 다수개의 걸이부(100)가 같이 결합되는 몸체부(200)로 이루어지는 것으로,본발명은 다수개의 낚시바늘에 인조미끼를 꿰어서 낚시를 하기 위하여 상기 낚시바늘이 하부에 연결되는 걸이부들이 몸체부에 결합되되 몸체부가 다수의 몸체로 철선에 의해 연결되어 있어서, 미끼를 메단 걸이부들이 회전되더라도 서로 엉키지 않는 등 사용이 편리하며 제작이 간단한 현저한 효과가 있다. claims: 다수개의 낚시바늘에 인조미끼를 꿰어서 낚시를 하기 위하여, 다수개의 낚시바늘이 하부에 각각 연결되는 다수개의 걸이부(100)와, 상기 다수개의 걸이부(100)가 같이 결합되는 몸체부(200)로 이루어지는 낚시바늘 결합구 제작방법에 있어서,상기 몸체부(200)는 다수 개의 몸체(210)로 이루어지는 것으로 상기 몸체(210)은 원통형의 양단에 경사부가 형성되어 지름이 축소된 것이며,상기 몸체부(200)와 걸이부(100)는 직각을 이루는 것으로, 몸체부에 대하여 걸이부가 회전되더라도 엉키지 않게 되며, 상기 몸체부(200)와 걸이부(100)는 녹이 쓸지 않는 금속을 사용하여 제작하는 것이며,상기 걸이부(100)는 원통형의 양단에 경사부가 형성되어 지름이 축소된 것으로, 파이프를 일정길이로 절단한 후 내부에 양 끝단에 멈춤부가 형성되는 상하부 고리를 제작한 후, 상하부 멈춤부를 파이프 내부에 삽입한 후, 디스크 형상의 롤러로 파이프 양단을 롤포밍하여 멈춤부가 파이프 내부에서 밖으로 이탈되지 않게 하되, 회전 롤러로 파이프 양단을 눌러서 압착할시 파이프 내부에 철선 멈춤부가 삽입된 상태에서 가공하는 것이며,상기 걸이부(100)의 상부고리(101)를 몸체부(200)에 결합하는 것으로, 상기 몸체부(200)는 원통형의 양단에 경사부가 형성되어 지름이 축소된 다수 개의 파이프가 각각의 몸체(210)가 되어 일직선으로 결합되고, 중간의 몸체들 간의 결합은 철선(1)을 파이프 내부에 넣고 롤러로 양단을 압입하여 상기 철선 양단이 파이프 밖으로 나오지 못하게 한 것이며, 양단에 위치하는 몸체는 철선 양 끝단에 형성된 반원형의 멈춤부를 파이프 내부에 삽입한 후 롤러로 파이프 양단을 압입하여 지름을 작게 하여 멈춤부가 파이프 내부에서 밖으로 이탈되지 않게 하는 것이되, 회전 롤러로 파이프 양단을 눌러서 압착할시 파이프 내부에 철선이 삽입된 상태에서 가공하는 것이며, 판재 모양의 금속재질의 금형을 사용하는 것으로, 상기 금형 표면에는 몸체 모양의 홈이 다수개가 간격을 두고 형성되어 있고 몸체홈 사이에는 철선에 해당되는 홈이 형성되어 있어서, 상기 파이프와 철선을 해당 홈에 넣고 롤러로 파이프 양단을 압입하고, 몸체부 양 끝단의 몸체의 좌우측으로서, 몸체부의 좌우양끝단에는 좌측고리부와 우측고리부가 형성되는 것이며,상기 걸이부(100)의 하부고리(102)와 인조미끼는 철선을 둥글게 말아서 둥근 양단을 철선 중앙부에 걸치게 한 체결고리(300)에 의해 착탈되는 것이며, 양단부분을 눌러서 철선 중앙부에서 착탈할 수 있는 것이며,상기 걸이부(100)와 몸체(210)는 동일형상으로 제작가능한 것을 특징으로 하는 낚시바늘 결합구 제작방법, Ltext: 어업, prediction: 어업
194/1059 Row 194: application_number: 1020190002000, combined_string: invention_title: 오징어낚시용 조립체 abstract: 오징어낚시용 조립체에 있어서, 경심에 묶이는 유인구고리(11)의 하단에 순차적으로 오징어를 유인하는 유인구(12), 상기 유인구(12)와 낚싯바늘(14) 사이의 간격을 유지하는 간격유지구(13), 오징어가 걸리는 상기 낚싯바늘(14), 상기 낚싯바늘(14)의 지름보다 큰 안내구(15), 경심에 묶이는 안내구고리(16)가 구성되는 것을 특징으로 한다.또한 경심에 묶이는 유인구고리(11)의 하단에 순차적으로 오징어를 유인하는 유인구(12), 상기 유인구(12)와 낚싯바늘(14) 사이의 간격을 유지하는 간격유지구(13), 오징어가 걸리는 상기 낚싯바늘(14), 중간고리(18)와 결합하는 낚시고리(17), 상기 낚시고리(17)와 결합하는 중간고리(18), 상기 낚싯바늘(14)의 지름보다 큰 안내구(15), 경심에 묶이는 안내구고리(16)가 구성되는 것을 특징으로 한다.본 발명에 따른 오징어낚시용 조립체에 의하면, 경심이 낚싯바늘에 걸리지 않으므로 낚싯바늘을 풀지 않을 뿐만 아니라 여러 대의 물레를 관리하므로 어획량을 증가시키는 이점이 있다. claims: 오징어낚시용 조립체에서, 경심(20)에 묶이는 유인구고리(11)의 하단에 순차적으로 오징어를 유인하는 유인구(12), 상기 유인구(12)와 낚싯바늘(14) 사이의 간격을 유지하는 간격유지구(13), 오징어가 걸리는 상기 낚싯바늘(14), 상기 낚싯바늘(14)의 지름보다 큰 안내구(15), 경심(20에 묶이는 안내구고리(16)가 구성되는 것을 특징으로 하는 오징어낚시용 조립체.오징어낚시용 조립체에서, 경심(20)에 묶이는 유인구고리(11)의 하단에 순차적으로 오징어를 유인하는 유인구(12), 상기 유인구(12)와 낚싯바늘(14) 사이의 간격을 유지하는 간격유지구(13), 오징어가 걸리는 상기 낚싯바늘(14), 중간고리(18)와 결합하는 낚시고리(17), 상기 낚시고리(17)와 결합하는 상기 중간고리(18), 상기 낚싯바늘(14)의 지름보다 큰 안내구(15), 경심(20)에 묶이는 안내구고리(16)가 구성되는 것을 특징으로 하는 오징어낚시용 조립체., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

195/1059 Row 195: application_number: 1020180140208, combined_string: invention_title: 원격제어가 가능한 집어등을 부착한 어업용 스마트 부표 abstract: 본 발명을 어업에서 사용하는 부표에 관한 것으로 주로 원양 어업에서 트랜스듀서가 탑재되어 어군 탐지가 가능한 부표에 집어등 기능을 부착한 것이다. 또한 집어등의 켜짐과 꺼짐을 위성 통신을 통해 원격으로 확인하고 제어하도록 하여 집어 기능에 대한 관리를 수월하게 하도록 제공하는 것이다. claims: 원격으로 집어등의 켜짐과 꺼짐의 상태확인이 가능하고 켜짐과 꺼짐의 제어가 가능한 집어등을 부착한 어군 탐지가 가능한 어업용 부표원격지에서 부표에 부착된 집어등의 켜짐과 꺼짐에 대한 시간 설정이 가능하도록 한다. 집어등이 켜지고 어군형성이 되어 있는지 어탐을 통해 확인이 가능하므로 특정 시간 동안 어군이 형성 되지 않을 경우 배터리 소모를 줄이기 위해 집어등이 자동으로 꺼지도록 설정이 가능한 어업용 부표, Ltext: 어업, prediction: 어업
196/1059 Row 196: application_number: 1020180137855, combined_string: invention_title: 편리한 낚시 abstract: 본 발명의 편한낚시는 낚시하는 낚시 바늘에 높낮이를 간단하게 조정할 수 있어 낚시인이 어떠한 환경에 있더라도 여려가지 낚시기법을 쉽게 조정하여 낚시를 할 수 있다 낚시인이 낚시기법을 바꾼다면 채비교한에 번거로움이 생긴다 이것을 해소 하는데 중점을 두였다 claims: 원줄(1)을 원통(4-1 4-2)를 통콰 한후 철심(4-1 4-2)를 이용하는방법목줄(7)을 돌출부(5-2)에 고정한후 돌출부(5-1)로 사용하는방법, Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

197/1059 Row 197: application_number: 1020180131838, combined_string: invention_title: 어류 선별기 abstract: 본 발명은 어류 선별기에 관한 것으로서, 물과 함께 투입된 어류를 크기별로 간편하게 선별할 수 있을 뿐만 아니라 어류의 이동 및 어류와 함께 투입된 물의 흐름이 원활해질 수 있음은 물론 선별된 어류가 이탈되는 것을 방지할 수 있고, 나아가, 어류의 정밀한 선별을 위해 어류의 이동을 일시적으로 차단할 수 있는 효과가 있다. claims: 선별된 어류가 배출되는 배출공이 형성되고 상부가 개방형성된 상태로 연속적으로 배치되는 복수의 배출조와;복수의 상기 배출조의 상부에 각각 배치되어 상측으로 투입된 어류 중 일정한 크기의 어류에 한해 복수의 상기 배출조 내부로 각각 낙하시키는 복수의 선별망과;복수의 상기 배출조의 양측벽에 상측으로 연장되는 일측 연장판 및 타측 연장판으로 구성되어, 복수의 상기 선별망상으로 공급되는 어류의 이동을 안내하는 어류이동안내부와;복수의 상기 배출조 중 인접한 배출조 사이에 배치되는 격벽과, 상기 격벽을 상승시켜 상기 어류이동안내부의 이동공간을 폐쇄시키는 승강부재로 구성되는 어류이동차단부와;상기 어류이동안내부의 일측 연장판의 내면 및 타측 연장판의 내면에 형성되어 상기 격벽의 상하이동을 안내하는 가이드홈내에 구비되고, 상기 격벽의 일측과 타측에 밀착된 상태로 상기 격벽의 일측과 타측을 탄성지지하여 상기 격벽이 상승된 상태로 위치고정될 수 있도록 하는 탄성판;을 포함하여 이루어지는 것을 특징으로 하는 어류 선별기.선별된 어류가 배출되는 배출공이 형성되고 상부가 개방형성된 상태로 연속적으로 배치되는 복수의 배출조와;복수의 상기 배출조의 상부에 각각 배치되어 상측으로 투입된 어류 중 일정한 크기의 어류에 한해 복수의 상기 배출조 내부로 각각 낙하시키는 복수의 선별망과;복수의 상기 배출조의 양측벽에 상측으로 연장되는 일측 연장판 및 타측 연장판으로 구성되어, 복수의 상기 선별망상으로 공급되는 어류의 이동을 안내하는 어류이동안내부와;복수의 상기 배출조 중 인접한 배출조 사이에 배치되는 격벽과, 상기 격벽을 상승시켜 상기 어류이동안내부의 이동공간을 폐쇄시키는 승강부재로 구성되는 어류이동차단부와;복수의 상기 배출조를 일정높이로 지지하는 지지프레임과;상기 지지프레임의 전측과 후측에 각각 수직구비되는 수직가이드관과, 상기 수직가이드관의 내부에 상하이동가능하게 구비되는 상하이동관과, 상기 상하이동관을 상하이동시키는 상하이동부재와, 복수의 상기 선별망의 상부로 공급된 물이 복수의 상기 배출조의 전측에서 후측방향으로 원활히 흐를 수 있도록 상기 지지프레임의 전측 높낮이와 후측 높낮이가 서로 상이하게 조절되어 복수의 상기 배출조와 함께 상기 지지프레임이 하향경사질 경우 지면과 안정적으로 면접촉된 상태를 유지하여 복수의 상기 배출조가 안정적으로 하향경사진 상태를 유지할 수 있도록 상기 상하이동관의 하부에 상하각도조절가능하게 결합되는 바닥판부재로 구성되어 상기 지지프레임의 일측 높낮이와 타측 높낮이를 각각 조절하는 높낮이 조절부;를 포함하여 이루어지는 것을 특징으로 하는 어류 선별기., Ltext: 어업, prediction: 어업
198/1059 Row 198: application_number: 2020180004832, combined_string: invention_title: 두족류 낚시도구 abstract: 미끼형상을 가지는 낚시도구 본체와, 낚시도구 본체의 후단에 설치되며 복수의 바늘을 포함하는 바늘군 및 바늘군의 후단으로 돌출되어 연장되도록 설치되는 지지대를 포함하는 것을 특징으로 하는 두족류 낚시도구가 개시된다. claims: 미끼형상을 가지는 낚시도구 본체;상기 낚시도구 본체의 후단에 설치되며, 복수의 바늘을 포함하는 바늘군; 및상기 바늘군의 후단으로 돌출되어 연장되도록 설치되는 지지대;를 포함하는 것을 특징으로 하는 두족류 낚시도구., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

199/1059 Row 199: application_number: 1020180119834, combined_string: invention_title: 매생이 채취장치 abstract: 본 발명은 매생이에 물을 공급하여 건조된 매생이를 축축하게 적시기 위한 물공급수단과, 상기 물에 적셔진 매생이발을 견인하기 위해 프레임의 일측에 형성되는 견인수단과, 상기 견인된 매생이발을 지지하기 위해 프레임의 상부에 형성되는 매생이발 지지수단과, 상기 견인수단의 뒤쪽에 형성되고 매생이발 지지수단에 의해 지지된 매생이발의 상하에 회전타격을 가해 매생이를 떼어내기 위한 회전타격수단으로 구성되는 매생이 채취장치를 제공하기 위한 것으로, 본 발명의 효과로는 바다에서 매생이 발을 수거하고 운반하는 과정 중에 일부는 말라붙어 덩어리지고, 가닥이 매우 가늘고 연해서 서로 잘 들러붙고 잘 엉키는 매생이를 수작업이 아닌 기계에 의해 매생이발로 부터 매생이만을 손쉽고 빠르게 분리시켜 채취할 수 있는 매우 유용한 발명인 것이다. claims: 매생이에 물을 공급하여 건조된 매생이를 축축하게 적시기 위한 물공급수단과, 상기 물에 적셔진 매생이발을 견인하기 위해 프레임의 일측에 형성되는 견인수단과, 상기 견인된 매생이발을 지지하기 위해 프레임의 상부에 형성되는 매생이발 지지수단과, 상기 견인수단의 뒤쪽에 형성되고 매생이발 지지수단에 의해 지지된 매생이발의 상하에 회전타격을 가해 매생이를 떼어내기 위한 회전타격수단으로 구성됨을 특징으로 하는 매생이 채취장치., Ltext: 어업, prediction: 어업
200/1059 Row 200: application_number: 1020180105073, combined_string: invention_title: 집어등 기능을 가지는 두족류 낚시용 인조 미끼 abstract: 본 발명은 해저를 유영하는 오징어 또는 주꾸미 등의 두족류 어종 가까이 빛을 제공할 수 있게 함으로써, 두족류 어종을 효과적으로 유인할 수 있게 하여 어획량을 늘릴 수 있게 하는 집어등 기능을 가지는 두족류 낚시용 인조 미끼에 관한 것으로, 본 발명은 몸통부와, 몸통부의 상단 측에 하단 측에 결합되는 커버부를 가지되, 몸통부 및 커버부는 빛이 투과되는 몸체; 및 상호 결합된 몸통부와 커버부의 내부에 수용되어 빛을 발광시키는 집어수단;을 포함한다. claims: 몸통부와, 상기 몸통부의 상단 측에 하단 측에 결합되는 커버부를 가지되, 상기 몸통부 및 상기 커버부는 빛이 투과되는 몸체; 및상호 결합된 상기 몸통부와 상기 커버부의 내부에 수용되어 빛을 발광시키는 집어수단;을 포함하되,상기 몸통부의 하단에는 하나 이상의 낚싯바늘이 장착되며, 상기 커버부의 상단에는 낚싯줄이 결속되는 고리가 형성되고,상기 집어수단은 인쇄회로기판, 상기 인쇄회로기판에 실장되는 다수의 발광다이오드, 및 배터리가 끼워지는 배터리 연결단자를 포함하되, 상기 배터리 연결단자에 상기 배터리가 연결되면 상기 발광다이오드가 발광하여 빛을 외부로 발산시키는 집어등 기능을 가지는 두족류 낚시용 인조 미끼., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

201/1059 Row 201: application_number: 1020180097412, combined_string: invention_title: 어류 포획 시스템 abstract: 본 발명은 어류 포획 시스템에 관한 것으로서, 더욱 상세하게는해상에서 어군(魚群)을 탐지하고, 탐지된 어군에 대해 다방면에서 광(光)을 조사함과 동시에 음향(音響)을 방사하여 특정 영역 또는 포획장치로 몰아서 한 번에 손쉽게 어군을 이루는 어류들을 대량 포획할 수 있도록 하는 어류 포획 시스템에 관한 것이다. claims: 어군의 위치와 양 및 종류를 포함한 어군정보를 음파 또는 시각정보로 수집하여 사전에 프로그램화된 알고리즘에 따라 분석하고, 분석된 데이터에 따라 생성된 운항신호를 토대로 어군 위치로 이동하여, 해당 어군에 대한 기피신호를 출력하면서 어군을 포획장치 방향으로 몰아가는 주어군유도장치 및 상기 주어군유도장치에서 송출되는 운항신호 및 기피신호에 따라 주어군유도장치의 양 측면 방향에서 간격을 유지하면서 어군을 상기 포획장치 방향으로 몰아가는 복수의 보조어군유도장치를 포함하는 어군유도장치; 상기 어군유도장치와 통신 연결된 상태로, 특정 영역에 유입구를 갖는 어망형태로 마련되어, 송신되는 제어신호하에 유도되는 타깃 어군을 수용하여 포획하는 포획장치; 상기 어군유도장치 및 포획장치와 통신 연결된 상태로 상기 포획장치의 어군이 유입되는 개방부 측에 마련되어, 포획된 어군이 기설정된 포획량에 도달하면, 자체 제어 알고리즘 또는 어군유도장치에서 송신되는 제어신호에 따라, 상기 포획장치로 동작신호를 전송하여 포획장치의 개방부를 차단하는 차단장치;를 포함하는 것을 특징으로 하는 어류 포획 시스템., Ltext: 어업, prediction: 어업
202/1059 Row 202: application_number: 2020180003789, combined_string: invention_title: 다운샷 및 외줄낚시 채비용 낚시 바늘 abstract: 본 고안은 주로 바닥에서 서식하는 광어와 같은 어종을 낚시 할때 사용하는 다운샷 및 외줄낚시 채비용 낚시 바늘에 관한 것으로서 보다 상세하게는,낚시대에 연결되어 있는 원줄의 일측 끝단부에 체결되는 것으로, 원줄 끝단부에 연결되는 목줄(100)과 상기 목줄(100) 일단부에 체결되는 바늘부(200)와 상기 목줄(100)의 타측 끝단부에 연결되는 봉돌(300)을 포함하고,상기 바늘부(200)는 목줄(100) 일단부에 연결되는 수직연결부(211)와 상기 수직연결부(211) 하측에서 절곡 연장되는 절곡부(212)와 상기 절곡부(212) 하측으로 절곡 연장되는 바늘(213)로 형성된 와이드훅바늘(210)과, 상기 와이드훅바늘(210)의 절곡부(212)에 삽입 연결되기 위한 고리(223)가 슬리브(222)의 결속에 의해 보조목줄(221)의 상단에 형성되어 있고 상기 보조목줄(221) 하측으로는 3개의 바늘로 이루어진 훅킹바늘(224)이 슬리브(222)에 의해 연결되어 있는 훅킹부재(220)로 포함되며,상기 와이드훅바늘(210)의 절곡부(212)는 경사진 형태로 이루어져 있으며 일측에 걸림턱(214)을 구비하여 상기 훅킹부재(220)의 고리(223)가 절곡부(212)에 삽입된 후 제차 이탈하는 것을 방지할 수 있도록 한 것을 특징으로 하여,본 고안은 통으로 된 미끼의 측면만 먹고 낚시 바늘은 물지 않아 발생하는 훅킹의 어려움을 해결하기 위해 별도의 훅킹부재를 구비하여 물고기가 통으로 된 미끼의 측면부터 먹더라도 훅킹이 용이해 우수한 조과를 기대할 수 있는 다운샷 및 외줄낚시 채비용 낚시 바늘에 관한 것이다. claims: 낚시대에 연결되어 있는 원줄의 일측 끝단부에 체결되는 것으로, 원줄 끝단부에 연결되는 목줄(100)과 상기 목줄(100) 일단부에 체결되는 바늘부(200)와 상기 목줄(100)의 타측 끝단부에 연결되는 봉돌(300)을 포함하고,상기 바늘부(200)는 목줄(100) 일단부에 연결되는 수직연결부(211)와 상기 수직연결부(211) 하측에서 절곡 연장되는 절곡부(212)와 상기 절곡부(212) 하측으로 절곡 연장되는 바늘(213)로 형성된 와이드훅바늘(210)과, 상기 와이드훅바늘(210)의 절곡부(212)에 삽입 연결되기 위한 고리(223)가 슬리브(222)의 결속에 의해 보조목줄(221)의 상단에 형성되어 있고 상기 보조목줄(221) 하측으로는 3개의 바늘로 이루어진 훅킹바늘(224)이 슬리브(222)에 의해 연결되어 있는 훅킹부재(220)로 포함되며,상기 와이드훅바늘(210)의 절곡부(212)는 경사진 형태로 이루어져 있으며 일측에 걸림턱(214)을 구비하여 상기 훅킹부재(220)의 고리(223)가 절곡부(212)에 삽입된 후 제차 이탈하는 것을 방지할 수 있도록 한 것을 특징으로 하는 다운샷 및 외줄낚시 채비용 낚시 바늘., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

203/1059 Row 203: application_number: 2020180003729, combined_string: invention_title: 원활한 김발 이송을 위한 물공급 수단을 갖는 물김 자동 채취장치 abstract: 본 고안은 원활한 김발 이송을 위한 물공급 수단을 갖는 물김 자동 채취장치에 있어서, 특히 동력장치를 이용하여 물김을 채취하되 물김을 절단칼날로 인입하는 과정에서 보다 용이하게 인입되면서 자연스럽게 절단작업이 이루어지도록하고, 더불어 이송되는 김발에 물을 공급하여 김발이 뻑뻑하지 않고 원활하게 이송되도록함으로서 생산효율을 극대화시키도록 구성한 것을 특징으로 하는 물김 자동 채취장치에 관한 것으로,김발(B)에 매달려있는 물김(A)을 절단하여 하부로 배출하기 위한 절단유닛(110)과; 상기 절단유닛(110)의 전후 각도를 조절할 수 있도록 형성하는 조절유닛(120)과; 상기 절단유닛(110)을 회전시키기 위한 구동유닛(130)을 포함하고; 상기 절단유닛(110)은 회전축(111)과; 상기 회전축(111)의 양측에 형성하는 한 쌍의 지지부(112)와; 상기 지지부(112)의 사이를 연결하되 하부에 길이방향을 따라서 절단된 물김(C)을 배출하기 위한 배출공간(10)을 형성하는 배출부(113)와; 상기 회전축(111)의 외측에 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 보강부(114)와; 다수개의 상기 보강부(114)를 연결하여 물김을 절단하기 위한 다수개의 절단날(115)과; 다수개의 상기 절단날(115)의 외측에 빙둘러 형성하여 상기 배출부(113)와 연결하되 상기 절단날(115)의 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 유도부(116)와; 상기 배출부(113)의 후방에서 전방으로 빙둘러 마련하여 김발이 통과하면서 상기 절단날(115)이 물김을 절단할 수 있도록 절단공간(20)을 형성하는 마감부(117)로 구성하는 것이 특징이다. claims: 김발을 통해 이동되는 물김을 절단하기 위한 절단수단(100)과; 상기 절단수단(100)의 전면에 위치하여 김발이 절단수단(100)으로 인입하는 과정에서 회전하면서 가이드하여 김발이 원활하게 절단수단(100)으로 인입되도록 유도하는 회전용 롤러수단(200)을 포함하고;상기 절단수단(100)은,김발(B)에 매달려있는 물김(A)을 절단하여 하부로 배출하기 위한 절단유닛(110)과; 상기 절단유닛(110)의 전후 각도를 조절할 수 있도록 형성하는 조절유닛(120)과; 상기 절단유닛(110)을 회전시키기 위한 구동유닛(130)을 포함하며;상기 절단유닛(110)은,회전축(111)과; 상기 회전축(111)의 양측에 형성하는 한 쌍의 지지부(112)와; 상기 지지부(112)의 사이를 연결하되 하부에 길이방향을 따라서 절단된 물김(C)을 배출하기 위한 배출공간(10)을 형성하는 배출부(113)와; 상기 회전축(111)의 외측에 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 보강부(114)와; 다수개의 상기 보강부(114)를 연결하여 물김을 절단하기 위한 다수개의 절단날(115)과; 다수개의 상기 절단날(115)의 외측에 빙둘러 형성하여 상기 배출부(113)와 연결하되 상기 절단날(115)의 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 유도부(116)와; 상기 배출부(113)의 후방에서 전방으로 빙둘러 마련하여 김발이 통과하면서 상기 절단날(115)이 물김을 절단할 수 있도록 절단공간(20)을 형성하는 마감부(117)로 구성하고;상기 조절유닛(120)은,상기 절단유닛(110)의 지지부(112)를 감싸도록 형성하는 고정부(121)와; 상기 고정부(121)의 일측을 절단하고 그 사이에 개방공간(122a)을 형성하는 개방부(122)와; 상기 개방부(122)를 내측 또는 외측으로 이동시켜 상기 고정부(121)가 지지부(112)를 밀착시켜 고정하기 위한 고정부재(123)와; 상기 개방부(122)의 내측에 형성하여 상기 지지부(112)의 외측에 밀착하는 밀착부(124)와; 상기 고정부(121)의 하부에 형성하여 선박에 고정하는 고정몸체(125)로 구성하고;상기 회전용 롤러수단(200)은,상기 고정몸체에 일단이 결합되며 내측에 공간부를 형성한 원통형 파이프 형태로 이루어지되, 파지하기에 용이한 형태로 이루어지는 지지몸체(210)와;상기 지지몸체에 일정간격을 두고 형성되며, 회전용 롤러수단의 결합위치를 자유롭게 선택할 수 있도록 유도하는 결합홀(211)과;상기 지지몸체에 일체형으로 연결하되 기억자 형태로 이루어지고, 내측에 공간부를 형성하며, 수직방향으로 위치되는 지지몸체와 수평방향으로 위치되는 회전봉을 상호 연결하는 연결몸체(220)와;상기 연결몸체의 상부 끝단 내부에 위치하며 다수개의 구형태로 이루어져 자유회전이 가능하도록하여 회전봉이 자체 회전이 이루어지도록 유도하는 베어링(221)과;상기 연결몸체의 양측에 결합하되 자유회전이 가능하여 김발을 이송시에 회전봉의 자유회전에 따라서 슬라이딩 이동이 가능하게 하는 회전봉(230)과; 상기 회전봉으로부터 일정길이 돌출 성형되며, 베어링과 외주연이 맞물려서 상기 베어링과 섭동되면서 회전봉의 회전을 유도하는 결합축(231)과;상기 고정몸체에 일측이 고정되며, 원통형 파이프 형상의 가이드봉을 구비하고, 상기 가이드봉에 지지몸체를 수납하여 체결시키는 체결수단(250)과;상기 체결수단을 통해 지지몸체를 고정시키되 지지몸체의 결합홀을 통과하면서 고정시키는 체결볼트(251)와;상기 회전봉의 몸체에 다수개 형성되어 김발에 물을 공급하여 자연스러운 김발의 이동을 유도하는 물배출용 홀(240)을 포함하여 구성함을 특징으로 하는 원활한 김발 이송을 위한 물공급 수단을 갖는 물김 자동 채취장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

204/1059 Row 204: application_number: 1020180094071, combined_string: invention_title: 물김 자동 채취장치 abstract: 본 발명은 물김 자동 채취장치에 있어서, 특히 동력장치를 이용하여 물김을 채취하되 물김을 절단칼날로 인입하는 과정에서 보다 용이하게 인입되면서 자연스럽게 절단작업이 이루어지도록하고, 더불어 이송되는 김발에 물을 공급하여 김발이 뻑뻑하지 않고 원활하게 이송되도록함으로서 생산효율을 극대화시키도록 구성한 것을 특징으로 하는 물김 자동 채취장치에 관한 것으로,김발(B)에 매달려있는 물김(A)을 절단하여 하부로 배출하기 위한 절단유닛(110)과; 상기 절단유닛(110)의 전후 각도를 조절할 수 있도록 형성하는 조절유닛(120)과; 상기 절단유닛(110)을 회전시키기 위한 구동유닛(130)을 포함하고; 상기 절단유닛(110)은 회전축(111)과; 상기 회전축(111)의 양측에 형성하는 한 쌍의 지지부(112)와; 상기 지지부(112)의 사이를 연결하되 하부에 길이방향을 따라서 절단된 물김(C)을 배출하기 위한 배출공간(10)을 형성하는 배출부(113)와; 상기 회전축(111)의 외측에 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 보강부(114)와; 다수개의 상기 보강부(114)를 연결하여 물김을 절단하기 위한 다수개의 절단날(115)과; 다수개의 상기 절단날(115)의 외측에 빙둘러 형성하여 상기 배출부(113)와 연결하되 상기 절단날(115)의 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 유도부(116)와; 상기 배출부(113)의 후방에서 전방으로 빙둘러 마련하여 김발이 통과하면서 상기 절단날(115)이 물김을 절단할 수 있도록 절단공간(20)을 형성하는 마감부(117)로 구성하는 것이 특징이다. claims: 김발을 통해 이동되는 물김을 절단하기 위한 절단수단(100)과; 상기 절단수단(100)의 전면에 위치하여 김발이 절단수단(100)으로 인입하는 과정에서 회전하면서 가이드하여 김발이 원활하게 절단수단(100)으로 인입되도록 유도하는 회전용 롤러수단(200)을 포함하고;상기 절단수단(100)은,김발(B)에 매달려있는 물김(A)을 절단하여 하부로 배출하기 위한 절단유닛(110)과; 상기 절단유닛(110)의 전후 각도를 조절할 수 있도록 형성하는 조절유닛(120)과; 상기 절단유닛(110)을 회전시키기 위한 구동유닛(130)을 포함하며;상기 절단유닛(110)은,회전축(111)과; 상기 회전축(111)의 양측에 형성하는 한 쌍의 지지부(112)와; 상기 지지부(112)의 사이를 연결하되 하부에 길이방향을 따라서 절단된 물김(C)을 배출하기 위한 배출공간(10)을 형성하는 배출부(113)와; 상기 회전축(111)의 외측에 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 보강부(114)와; 다수개의 상기 보강부(114)를 연결하여 물김을 절단하기 위한 다수개의 절단날(115)과; 다수개의 상기 절단날(115)의 외측에 빙둘러 형성하여 상기 배출부(113)와 연결하되 상기 절단날(115)의 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 유도부(116)와; 상기 배출부(113)의 후방에서 전방으로 빙둘러 마련하여 김발이 통과하면서 상기 절단날(115)이 물김을 절단할 수 있도록 절단공간(20)을 형성하는 마감부(117)로 구성하고;상기 조절유닛(120)은,상기 절단유닛(110)의 지지부(112)를 감싸도록 형성하는 고정부(121)와; 상기 고정부(121)의 일측을 절단하고 그 사이에 개방공간(122a)을 형성하는 개방부(122)와; 상기 개방부(122)를 내측 또는 외측으로 이동시켜 상기 고정부(121)가 지지부(112)를 밀착시켜 고정하기 위한 고정부재(123)와; 상기 개방부(122)의 내측에 형성하여 상기 지지부(112)의 외측에 밀착하는 밀착부(124)와; 상기 고정부(121)의 하부에 형성하여 선박에 고정하는 고정몸체(125)로 구성하고;상기 회전용 롤러수단(200)은,상기 고정몸체에 일단이 결합되며 내측에 공간부를 형성한 원통형 파이프 형태로 이루어지되, 파지하기에 용이한 형태로 이루어지는 지지몸체(210)와;상기 지지몸체에 일정간격을 두고 형성되며, 회전용 롤러수단의 결합위치를 자유롭게 선택할 수 있도록 유도하는 결합홀(211)과;상기 지지몸체에 일체형으로 연결하되 기억자 형태로 이루어지고, 내측에 공간부를 형성하며, 수직방향으로 위치되는 지지몸체와 수평방향으로 위치되는 회전봉을 상호 연결하는 연결몸체(220)와;상기 연결몸체의 상부 끝단 내부에 위치하며 다수개의 구형태로 이루어져 자유회전이 가능하도록하여 회전봉이 자체 회전이 이루어지도록 유도하는 베어링(221)과;상기 연결몸체의 양측에 결합하되 자유회전이 가능하여 김발을 이송시에 회전봉의 자유회전에 따라서 슬라이딩 이동이 가능하게 하는 회전봉(230)과; 상기 회전봉으로부터 일정길이 돌출 성형되며, 베어링과 외주연이 맞물려서 상기 베어링과 섭동되면서 회전봉의 회전을 유도하는 결합축(231)과;상기 고정몸체에 일측이 고정되며, 원통형 파이프 형상의 가이드봉을 구비하고, 상기 가이드봉에 지지몸체를 수납하여 체결시키는 체결수단(250)과;상기 체결수단을 통해 지지몸체를 고정시키되 지지몸체의 결합홀을 통과하면서 고정시키는 체결볼트(251)와;상기 회전봉의 몸체에 다수개 형성되어 김발에 물을 공급하여 자연스러운 김발의 이동을 유도하는 물배출용 홀(240)을 포함하여 구성하며;상기 회전봉에 외주연에 설치되어 김발에 의해서 가해지는 압력값을 채크하는 압력센싱수단(400)과;상기 압력센싱수단(400)에 의해서 채크된 압력값에 의해서 외부 물공급수단의 물공급량을 조절하는 제어부(500)와;상기 제어부의 제어에 의해서 외부 물공급수단(300)의 물을 회전봉으로 펌핑하여 물배출용 홀을 통해 물을 출력시키는 펌프(310)를 포함하여 구성함을 특징으로 하는 물김 자동 채취장치., Ltext: 어업, prediction: 임업
205/1059 Row 205: application_number: 1020180091406, combined_string: invention_title: 부류식 물김 자동 채취장치 abstract: 본 개시는 부류식 김양식에서 장치를 이용해 자동으로 김발을 뒤집거나 또는 채취를 위해 어선으로 건져 올릴 수 있고, 노출과 침수를 번갈아가며 김발을 효율적으로 뒤집을 수 있어 우수한 품질의 김 생산이 가능하고, 이로 인한 사업 증대가 도모되며, 파고, 풍량, 바람, 해수 등의 기상적인 요인 및 어선내 바닥의 미끄러움, 각종 장비와 구조상의 요인 등에 따른 문제점으로 인한 작업의 어려움없이 안전하게 김발로부터 김을 채취할 수 있고, 비교적 간단한 구성을 가져 제작 및 설치가 용이하고, 이를 통해 김양식 어선에 접목이 쉬워 보급 활성화가 도모되며, 사용성과 경제성이 우수한 장점을 갖는 부류식 물김 자동 채취장치에 관한 것이다.본 개시의 실시예에 따른 부류식 물김 자동 채취장치는, 부류식 김 양식을 위해 사용되는 선박의 측면 일측에 결합되는 어선결합몸체부와, 상기 어선결합몸체부에 회전 가능하게 결합되어 상기 선박의 내측 상부면과 외측 하부면의 사이에서 상하로 회동되는 회동암부 및 상기 회동암부에 설치되어 상기 회동암부의 회전에 의해 상하로 회동되며, 상기 어선의 외측 하부면에 위치되면 김 양식을 위한 김발을 걸어 상기 회동암부의 회동으로 상기 어선의 내측 상부면으로 상기 김발을 건져 올리는 걸이부를 포함하여 이루어지는 것을 특징으로 한다. claims: 부류식 김 양식을 위해 사용되는 선박의 측면 일측에 결합되는 어선결합몸체부;상기 어선결합몸체부에 회전 가능하게 결합되어 상기 선박의 내측 상부면과 외측 하부면의 사이에서 상하로 회동되는 회동암부; 및상기 회동암부에 설치되어 상기 회동암부의 회전에 의해 상하로 회동되며, 상기 어선의 외측 하부면에 위치되면 김 양식을 위한 김발을 걸어 상기 회동암부의 회동으로 상기 어선의 내측 상부면으로 상기 김발을 건져 올리는 걸이부;를 포함하여 이루어지는 것을 특징으로 하는 부류식 물김 자동 채취장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

206/1059 Row 206: application_number: 1020180087454, combined_string: invention_title: 가압부상방식을 이용한 미세조류 수확장치 abstract: 본 발명은 가압부상방식을 이용한 미세조류 수확장치에 관한 것으로서, 본 발명에 따른 가압부상방식을 이용한 미세조류 수확장치는, 상측이 개방되고 평면이 장방형으로 형성되는 박스형상의 부상조 하우징(100); 상기 부상조 하우징의 일측 전단면을 관통하게 설치되어 배양이 완료된 스피루리나 미세조류와 부상용수를 상기 부상조 하우징의 내부로 공급하는 미세조류 공급부(200)와; 상기 미세조류 공급부(200)와 인접하게 설치되어 미세기포를 발생시키고 상기 부상조 하우징의 내부로 공급되는 스피루리나 미세조류에 미세기포를 함침시키는 미세기포 발생부(300)와; 상기 부상조 하우징(100)의 수면위로 부상하는 부상용수의 흐름에 변화를 주기 위하여 상기 부상용수의 흐름방향을 제어하는 플레이트 패널을 상기 부상조 하우징의 횡방향 수직으로 설치하여 구비하며 상기 플레이트 패널의 각도 조절이 가능한 배플 플레이트부(400)와; 상기 배플 플레이트부(400)를 통과하여 부상하는 스피루리나 미세조류를 상기 부상조 하우징(100)의 수면위에서 채집하기 위하여 상기 부상조 하우징(100)의 내측에서 높낮이 조절이 가능한 격벽으로 설치되는 부상조 웨어 패널부(500)와; 상기 부상조 웨어 패널부(500)에 의해 채집되는 스피루리나 미세조류를 상기 부상조 하우징(100)의 수면위에서 걷어내기 위한 스키머 장치(600); 및 상기 부상조 하우징(100)의 타측 후단면을 관통하게 설치되며 스피루리나 미세조류를 채집하고 남은 부상용수를 배출하기 위한 배출구(700);를 포함할 수 있다.따라서, 본 발명은, 부상용수의 속도 및 방향을 조절할 수 있는 수류가변형 배플 플레이트부와 수면위로 부상되는 스피루리나를 효율적으로 채집할 수 있도록 높이조절이 가능한 부상조웨어를 구비하여 스피루리나 미세조류의 수확효율을 높일 수 있는 가압부상방식을 이용한 미세조류 수확장치를 제공하는 효과가 있다. claims: 상측이 개방되고 평면이 장방형으로 형성되는 박스형상의 부상조 하우징(100);상기 부상조 하우징의 일측 전단면을 관통하게 설치되어 배양이 완료된 스피루리나 미세조류와 부상용수를 상기 부상조 하우징의 내부로 공급하는 미세조류 공급부(200)와;상기 미세조류 공급부(200)와 인접하게 설치되어 미세기포를 발생시키고 상기 부상조 하우징의 내부로 공급되는 스피루리나 미세조류에 미세기포를 함침시키는 미세기포 발생부(300)와;상기 부상조 하우징(100)의 수면위로 부상하는 부상용수의 흐름에 변화를 주기 위하여 상기 부상용수의 흐름방향을 제어하는 플레이트 패널을 상기 부상조 하우징의 횡방향 수직으로 설치하여 구비하며 상기 플레이트 패널의 각도 조절이 가능한 배플 플레이트부(400)와;상기 배플 플레이트부(400)를 통과하여 부상하는 스피루리나 미세조류를 상기 부상조 하우징(100)의 수면위에서 채집하기 위하여 상기 부상조 하우징(100)의 내측에서 높낮이 조절이 가능한 격벽으로 설치되는 부상조 웨어 패널부(500)와;상기 부상조 웨어 패널부(500)에 의해 채집되는 스피루리나 미세조류를 상기 부상조 하우징(100)의 수면위에서 걷어내기 위한 스키머 장치(600); 및상기 부상조 하우징(100)의 타측 후단면을 관통하게 설치되며 스피루리나 미세조류를 채집하고 남은 부상용수를 배출하기 위한 배출구(700);를 포함하는 것을 특징으로 하는 가압부상방식을 이용한 미세조류 수확장치, Ltext: 어업, prediction: 임업
207/1059 Row 207: application_number: 1020180077554, combined_string: invention_title: 낚시용 미끼 보조장치 abstract: 본 발명은 낚시 미끼와 함께 발광하거나 움직이는 미끼 보조장치에 관한 것이다. 보다 상세하게는 낚시 바늘에 끼워지는 미끼부와 제어부가 분리되어 미끼가 끼워진 상태에서 낚시 바늘과 미끼가 발광하여 움직여서 물고기를 잘 유인할 수 있도록 하는 미끼 보조장치에 관한 것이다. claims: 전원, 회로부, 및 스위치를 구비한 제어전원부;발광체와 모터 중 어느 하나 또는 둘을 구비한 미끼부; 및상기 제어전원부와 상기 미끼부를 연결하는 전선;을 포함하며상기 제어전원부, 미끼부, 및 전선은 모두 방수처리되며, 그리고상기 제어전원부에 의해서 상기 발광체와 모터이 작동되는 것,을 특징으로 하는 미끼 보조장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

208/1059 Row 208: application_number: 1020210071286, combined_string: invention_title: 그물 구조물 abstract: 그물 구조물을 제공한다. 그물 구조물은 이웃하는 곶들 사이의 만 지형에 그 하단부가 고정되도록 설치된 그물 및 상기 그물 상단부와 결합되어 상기 그물을 상하부로 이동시키는 이동 유닛을 포함한다. 상기 이동 유닛은 상기 그물의 상단부에 연결되는 도르래, 상기 도르래에 연결되는 윈치, 및 상기 그물의 상단부, 상기 도르래, 및 상기 윈치를 연결하는 와이어를 포함하고, 상기 만으로 바닷물이 유입될 때 상기 그물의 하단부는 고정되되 상기 그물의 상단부를 상기 이동 유닛을 이용하여 상부로 끌어 올려 상기 그물을 커튼 형식으로 펼쳐 상기 만의 일 측을 덮는다. claims: 이웃하는 곶들 사이의 너비와 만의 바닥에 곶의 상부까지의 거리에 따라 크기가 결정되는 그물;상기 그물의 상단에 설치되고, 상기 이웃하는 곶들 사이의 너비에 따라 크기가 결정되는 그물 상단부;상기 그물의 하단에 설치되고, 상기 만의 바닥에 고정되도록 설치되는 그물 하단부;상기 이웃하는 곶들 사이의 만 지형에 상기 그물 하단부가 고정되도록 설치되는 고정 유닛; 및상기 그물 상단부와 결합되어 상기 그물을 상하부로 이동시키는 이동 유닛을 포함하되,상기 이동 유닛은 상기 그물 상단부의 양단에 각각 연결되어 상기 이웃하는 곶들에 두 개가 각각 설치되는 그물 구조물., Ltext: 어업, prediction: 어업
209/1059 Row 209: application_number: 1020210015930, combined_string: invention_title: 부유성 산란어류의 산란장 조성시스템 abstract: 본 발명은 부유성 산란어류의 산란장 조성시스템에 관한 것으로서, 보다 상세하게는 해저면에 구비되는 복수의 제1수중와이어와, 이 제1수중와이어의 어느 한 지점을 서로 연결하는 제2수중와이어를 통하여 중층에서 산란하는 어류나 어패류의 산란장을 조성하고, 상기 제1수중와이어 및 제2수중와이어를 연결유닛을 통해 고정함에 따라 수중 작업을 보다 손쉽게 하며, 해수면에 위치하는 제1부구와 수중에 위치하는 제2부구를 통하여 조류 등에 의한 해수면의 높이 변화가 있더라도 제1수중와이어의 텐션을 유지할 수 있도록 고안된 부유성 산란어류의 산란장 조성시스템에 관한 것이다. claims: 해저면에 서로 이격되어 구비되는 복수의 제1수중와이어;상기 각각의 제1수중와이어의 어느 한 지점을 서로 연결하도록 구비되는 제2수중와이어;상기 제1수중와이어에 구비되어, 상기 제1수중와이어에 연결되는 제2수중와이어를 부상시키는 부구;상기 제1수중와이어의 특정 위치에 고정되어, 상기 제2수중와이어를 결합하는 연결유닛;을 포함하여 이루어지되,상기 연결유닛은제2수중와이어가 체결되는 체결부와, 상기 체결부로부터 절곡형성되어, 상기 제1수중와이어가 안착되는 와이어결합부 및 상기 제1수중와이어를 일방향에서 끼워 상기 와이어결합부에 안착시키도록 상기 와이어결합부에 형성되는 끼움공을 포함하여 이루어지는 것을 특징으로 하고,상기 끼움공은상기 와이어결합부에 둘 이상으로 일단이 개방된 개방부를 갖도록 구비되어, 상기 와이어를 개방부를 통해 끼움결합시키되, 상기 와이어가 지그재그형상으로 결합되도록 이루어지는 것을 특징으로 하는 부유성 산란어류의 산란장 조성시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

210/1059 Row 210: application_number: 1020200181923, combined_string: invention_title: 인공 수초형 어류산란장 조성용 구조물 abstract: 본 발명은 저수지, 강, 댐 등에 별도의 프레임을 구성하지 않고 어류가 산란 및 서식할 수 있는 공간을 간편하고 신속하게 설치 및 철거할 수 있고 구조가 간단한 인공 수초형 어류산란장 조성용 구조물에 관한 것이다.즉, 본 발명은 일정 길이의 지지로프와, 상기 지지로프에 매달림 형태로 등간격 구비되어 있는 다수의 인공수초와, 상기 인공수초가 설치된 범위내의 지지로프에 일정 간격으로 무게추 및 제2부구가 각각 연결되어 지지로프가 수중 부유할 수 있도록 한 것을 포함하며, 상기 인공수초가 설치된 범위의 외측에 위치한 지지로프에 연결되는 제1부구와, 상기 제1부구와 연결된 지지로프의 양끝단에 설치되어 수중 바닥면에 고정되는 앵커부재로 이루어진 것인공 수초형 어류산란장 조성용 구조물을 특징으로 한다. claims: 일정 길이의 지지로프(10)와, 상기 지지로프(10)에 매달림 형태로 등간격 구비되어 있는 다수의 인공수초(20)와, 상기 인공수초(20)가 설치된 범위내의 지지로프(10)가 일정한 잠수깊이로 수중 부유할 수 있도록 한 수중유도부재(30)와, 상기 인공수초(20)가 설치된 범위의 외측에 위치한 지지로프(10)에 연결되는 제1부구(40)와, 상기 제1부구(40)와 연결된 지지로프(10)의 양끝단에 설치되어 수중 바닥면에 고정되는 앵커부재(50)를 길이가 조절되는 가변형 지지로프(10a)로 연결하되 제1부구(40)에 가이드로울(60)을 구비하여 가변형 지지로프(10a)를 슬라이딩 안내되게 연결한 다음 가변형 지지로프(10a)의 상부 끝단은 장력유지용 무게추(70)가 연결된 구성으로 이루어지며,상기 수중유도부재(30)는 인공수초(20)가 설치된 범위내의 지지로프(10)에 일정 간격으로 무게추(36) 및 제2부구(32)가 각각 연결되고, 상기 제2부구(32)의 하부에 수직으로 일정 길이의 지지대(38) 상단이 연결되고, 지지대(38) 하단은 지지로프(10)와 연결되어 지지로프(10)가 수중 부유할 수 있도록 한 것을 특징으로 하는 인공 수초형 어류산란장 조성용 구조물., Ltext: 어업, prediction: 어업
211/1059 Row 211: application_number: 1020200127923, combined_string: invention_title: 수산 질병 관리 시스템, 방법 및 프로그램 abstract: 본 발명의 일 실시예에 따른 수산 질병 관리 시스템은 주기적인 모니터링이 필요한 양식장을 포함한 수산질병 관리 장소에 설치된 카메라 및 센서로부터 각각 영상 데이터, 센싱 데이터를 수집하고, 통신망과 연결되어 관리서버로 데이터를 전송하는 데이터수집장치; 및 상기 데이터수집장치로부터 수집된 데이터를 기반으로 어류의 질병 원인을 분석 및 질병 진단을 하고, 진단 결과에 따라 처방을 생성하고, 관리단말기로 분석 데이터, 진단 결과 및 처방을 전송하는 상기 관리서버를 포함한다. claims: 주기적인 모니터링이 필요한 양식장을 포함한 수산질병 관리 장소에 설치된 카메라 및 센서로부터 각각 영상 데이터, 센싱 데이터를 수집하고, 통신망과 연결되어 관리서버로 데이터를 전송하는 데이터수집장치;상기 데이터수집장치로부터 수집된 데이터를 기반으로 어류의 질병 원인을 분석 및 질병 진단을 하고, 진단 결과에 따라 처방을 생성하고, 관리단말기로 분석 데이터, 진단 결과 및 처방을 전송하는 상기 관리서버를 포함하는 수산 질병 관리 시스템.데이터수집장치는 수산질병 관리 장소에 설치된 카메라의 영상 데이터 또는 센서의 센싱 데이터를 수집하고, 관리서버로 수집된 데이터를 전송하는 단계;상기 관리서버는 수집된 데이터 기반으로 질병원인을 통하여 질병 분석 및 예측을 수행하는 단계;상기 관리서버는 분석 및 진단 결과를 보고서 또는 통계 자료 형태로 생성하고, 분석 및 진단 결과에 따라 미리 설정된 처방을 생성하는 단계;상기 관리서버는 진단 결과 및 처방을, 연동되는 관리 프로그램을 통하여 관리자가 소지한 관리단말기로 전송하는 단계를 포함하는 수산 질병 관리 방법.제6항 내지 제9항 중 어느 한 항의 수산 질병 관리 방법을 수행하는 컴퓨터로 읽을 수 있는 저장매체에 저장된 컴퓨터 프로그램., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

212/1059 Row 212: application_number: 1020200116246, combined_string: invention_title: 갑오징어 수정란 부착용 인공조초 abstract: 본 발명의 해저면 상에 고정 설치되는 산란초 고정부; 상기 산란초 고정부에는 산란초의 하부 말단부가 일정간격으로 하나 이상 연결 고정되어 이루어지는 갑오징어 산란장치를 제공함으로써, 서식과 산란 장소를 동시에 제공하는 한편, 자연상태의 갑오징어 개체수를 증가시킬 수 있는 효과가 있다. claims: 일정 길이와 너비를 가지는 가로 및 세로부재 말단이 연결되어 상부틀을 형성하고, 상기 상부틀 내측에는 가로 또는 세로 부재가 하나 이상 이격되어 설치되는 고정부재부와 상부틀 하부에는 상부틀이 해저면과 일정 높이로 이격 설치될 수 있도록 지지부가 형성되어 이루어지는 산란초 고정부가 해저면 상에 고정되고;일정 길이를 갖는 직경 5-10mm의 폴리에틸렌 재질의 로프 복수개를 반으로 접어 접힌 하단부를 고정하여 묶음형태를 이루는 부착부와 상기 부착부 상단부에는 로프를 매개로 일단에 부자가 연결된 부력부를 형성한 산란초가 상기 상부틀과 고정부재부 상면에 일정간격으로 이격되어 복수개 설치되며; 상기 산란초가 설치된 상부틀과 고정부재부 상면의 이격공간에는 일정길이를 갖는 직경 2-3mm의 로프가 무작위 다발형상으로 얽혀지도록 이루어진 부착기질부가 형성되는 것을 특징으로 하는 갑오징어 수정란 부착용 인공조초, Ltext: 어업, prediction: 어업
213/1059 Row 213: application_number: 1020200110703, combined_string: invention_title: 뻘 바닥 또는 모래 바닥에 묻혀 움직이지 않도록 하는 패각용 주꾸미 포획어구 abstract: 본 발명은 뻘 바닥 또는 모래 바닥에 위치하는 상부몸체 또는 하부몸체가 바닷물의 흐름(조류)이 심할 경우에 패각용 주꾸미 포획어구의 상부몸체와 하부몸체의 외측면에 형성된 다수개의 돌출부 사이로 뻘 또는 모래가 침투하여 하부몸체의 일부가 뻘 바닥 또는 모래 바닥에 묻히어 패각용 주꾸미 포획어구가 조류에 유동하지 않고 고정되어 있게 하므로써 주꾸미가 자신의 몸을 완전히 은폐시켜 은신을 위한 안전한 서식처 또는 산란처로 인식하여 패각용 주꾸미 포획어구에 숨어 있는 상태에서 포획어구를 끌어 올려 어획량을 증대시키며, 끌어 올려진 상, 하부몸체의 표면에 형성되어 있는 미끄럼이 없는 돌기부를 손바닥으로 눌러 비틀어서 주꾸미를 용이하게 꺼낼수 있도록 하는 패각용 주꾸미 포획어구에 관한 것이다.본 발명은 조개껍질형상으로 형성된 상부몸체(2)와, 상부몸체(2)와 상하대칭을 이루는 조개껍질형상으로 형성되는 하부몸체(3)로 이루어지고, 상기 상부몸체(2)와 하부몸체(3)의 후단부에는 끈삽입공(4a)(4b)이 각각 관통 형성되거나 결속용 고리부(5a)(5b)가 각각 돌출 형성되며, 상기 상부몸체(2)와 하부몸체(3)는 후단부에 형성된 끈삽입공(4a)(4b) 또는 결속용 고리부(5a)(5b)에 삽입되는 결속용 끈(6)에 의하여 결합되는 주꾸미 포획용 어구에 있어서, 상기 상부몸체(2)와 하부몸체(3)의 외측 표면에는 5 ~ 10mm의 높이로 소뿔 형태의 타원형으로 형성된 다수개의 돌출부(7)가 일정한 간격을 두고 분포 형성되며, 상기 다수개의 돌출부(7)는, 상부몸체(2)와 하부몸체(3)의 외측 표면에 일정 간격을 두고 30개 내지 50개가 골고루 분포 형성되고, 상기 상,하부몸체(2)(3)와, 결속용 고리부(5a)(5b)와, 다수개의 돌출부(7)는, 25 ~ 35중량%의 ABS수지 또는 HIPS수지와 65 ~ 75중량%의 칼페트가 혼합되는 물보다 비중이 큰 합성수지재질로 이루어져 뻘 바닥 또는 모래 바닥에 묻혀 움직이지 않도록 하는 것을 특징으로 한다. claims: 조개껍질형상으로 형성된 상부몸체(2)와, 상부몸체(2)와 상하대칭을 이루는 조개껍질형상으로 형성되는 하부몸체(3)로 이루어지고,상기 상부몸체(2)와 하부몸체(3)의 후단부에는 끈삽입공(4a)(4b)이 각각 관통 형성되거나 결속용 고리부(5a)(5b)가 각각 돌출 형성되며,상기 상부몸체(2)와 하부몸체(3)는 후단부에 형성된 끈삽입공(4a)(4b) 또는 결속용 고리부(5a)(5b)에 삽입되는 결속용 끈(6)에 의하여 결합되는 주꾸미 포획용 어구에 있어서,상기 상부몸체(2)와 하부몸체(3)의 외측 표면에는 5 ~ 10mm의 높이로 소뿔 형태의 타원형으로 형성된 돌출부(7)가 일정한 간격을 두고 30개 내지 50개가 골고루 분포 형성되고,상기 상,하부몸체(2)(3)와, 결속용 고리부(5a)(5b)와, 다수개의 돌출부(7)는, 25 ~ 35중량%의 ABS수지 또는 HIPS수지와 65 ~ 75중량%의 칼페트가 혼합되는 물보다 비중이 큰 합성수지재질로 이루어진 것을 특징으로 하는 뻘 바닥 또는 모래 바닥에 묻혀 움직이지 않도록 하는 패각용 주꾸미 포획어구., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

214/1059 Row 214: application_number: 1020200109318, combined_string: invention_title: 어선용 그물 자동정리장치 및 이를 포함하는 그물 자동정리시스템 abstract: 본 발명은 어선용 그물 자동정리장치 및 이를 포함하는 그물 자동정리시스템에 관한 것으로서, 보다 상세하게는 어선용 그물 자동정리장치를 통해 어선에서 사용된 그물을 사용이 가능한 상태로 정리하기 위한 것이다.또한, 본 발명은 그물이 안내되는 안내활의 중앙부에 취합통과부를 형성하여 그물의 그물망이 해당 취합통과부로 취합되도록 구성함으로써, 안내활로 안내되는 그물이 한 쪽으로 쏠리지 않고, 중앙부로 뭉쳐 지나가게 할 수 있는 어선용 그물 자동정리장치 및 이를 포함하는 그물 자동정리시스템을 제공하는데 목적이 있다.특히, 본 발명은 그물 정리 작업 중 그물이 한 쪽으로 쏠려 발생하는 부하를 감지하여 측정값에 따라 그물을 끌어당기는 롤러의 동작을 제어함으로써, 그물의 정리 작업 중 발생하는 부하를 방지할 수 있는 장점이 있다. claims: 유입된 그물을 펼쳐서 배출하는 어선용 그물 자동정리장치에 있어서,좌우측에 마련되는 양측프레임;상기 그물과 상기 그물의 양측 가장자리에 구성된 그물와이어의 유입을 가이드하며 상기 그물와이어 사이의 그물망을 펼치는 안내활;상기 안내활로 유입된 그물을 회전력에 의하여 끌어당기는 롤러;상기 롤러에 유입된 그물을 상기 롤러 방향으로 압박하는 압박휠; 및상기 그물와이어가 상기 양측프레임측으로 이동하는 것을 제한하는 그물이탈방지구;를 포함하고,상기 안내활은,상기 양측프레임에 설치되는 고정바; 및상기 고정바의 일측 및 타측에 각각 이격되어 한 쌍으로 구성되는 가이드구;및상기 한 쌍으로 구성된 가이드구의 사이에 형성되는 취합통과부;를 포함하고,상기 각각의 가이드구는,상기 고정바에서 상부방향으로 경사지게 구성되고, 하부보다 상부가 넓게 형성되며,상기 가이드구의 하부에는,상기 그물와이어가 통과되는 로프통과부;가 형성된 것을 특징으로 하는 어선용 그물 자동정리장치.제 1항에 따른 어선용 그물 자동정리장치를 포함하는 어선용 그물정리시스템에 있어서,어선에 고정 설치되는 거치장치;를 포함하며,상기 어선용 그물 자동정리장치는 상기 거치장치에서 평면상 이동 및 회동 중 적어도 하나의 동작이 가능하도록 구성되는 것을 특징으로 하는 그물 자동정리시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

215/1059 Row 215: application_number: 1020200079342, combined_string: invention_title: 낙지의 탈출을 방지하는 통발용 진입구 및 그것이 적용된 통발 abstract: 본 발명은 낙지의 탈출을 방지하는 통발용 진입구 및 그것이 적용된 통발에 관한 것으로, 특히 통발의 내부로 포획된 낙지의 외부 탈출을 방지하고, 낙지의 진입을 원활하게 하여 포획량을 향상함은 물론 어업인의 소득을 대폭 증대하는 신개념의 기술에 관한 것이다.종래에 개시된 통발용 진입구는 망체를 구성하는 망살의 단면이 사각형으로 이루어짐으로써 입구에서 출구 쪽으로 유속이 작용할 때 저항을 많이 받으면서 출구가 벌어져 통발의 내부로 포획된 낙지가 외부로 탈출하여 포획량이 줄어드는 문제점이 야기된다.본 발명은 이러한 문제점을 일소하기 위한 방안으로 반분할 된 한 쌍의 상부 진입구 및 하부 진입구의 조립구성으로 이루어진 통발용 진입구의 망체를 구성하는 망살을 원형 단면으로 형성하여 유속에 따른 저항을 줄여 출구의 벌어짐을 방지할 수 있도록 하는 기술을 강구함을 특징으로 한다. claims: 하부가 개방된 망체(11)로 형성되고, 입구(13)에서 출구(14) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(12)가 형성되며, 상기 입구(13)의 양단에 지지살 파지부(15)가 형성됨과 아울러 상단에 링 밀착부(16)가 형성된 상부 진입구(10)와;상기 상부 진입구(10)과 일체로 맞대어 결합되되, 상부가 개방된 망체(21)로 형성되고, 입구(23)에서 출구(24) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(22)가 형성되며, 상기 입구(23)의 양단에 지지살 파지부(25)가 형성됨과 아울러 하단에 링 밀착부(26)가 형성된 하부 진입구(20)로 이루어지는 한편;상기 하부 진입구(20)의 양측 상단에 형성된 맞댐부(28)에 간격을 두고 다수의 결합돌기(28a)가 돌출 형성되고, 상기 상부 진입구(10)의 양측 하단에 형성된 맞댐부(18)에는 상기 결합돌기(28a)가 끼움 결합되는 다수의 결합홀(18a)이 형성된 것을 특징으로 하는 낙지의 탈출을 방지하는 통발용 진입구.하부가 개방된 망체(11)로 형성되고, 입구(13)에서 출구(14) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(12)가 형성되며, 상기 입구(13)의 양단에 지지살 파지부(15)가 형성됨과 아울러 상단에 링 밀착부(16)가 형성된 상부 진입구(10)와;상기 상부 진입구(10)과 일체로 맞대어 결합되되, 상부가 개방된 망체(21)로 형성되고, 입구(23)에서 출구(24) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(22)가 형성되며, 상기 입구(23)의 양단에 지지살 파지부(25)가 형성됨과 아울러 하단에 링 밀착부(26)가 형성된 하부 진입구(20)로 이루어지는 한편;상기 하부 진입구(20)의 양측 상단에 형성된 맞댐부(28)에 한 쌍의 결합돌기(28a)가 돌출 형성되고, 상기 상부 진입구(10)의 양측 하단에 형성된 맞댐부(18)에는 상기 결합돌기(28a)가 끼움 결합되는 다수의 결합홀(18a)이 형성되며, 상기 결합돌기(28a)의 사이 맞댐부(18)(28)는 상호 미싱으로 박음질 결합되는 것을 특징으로 하는 낙지의 탈출을 방지하는 통발용 진입구.하부가 개방된 망체(11)로 형성되고, 입구(13)에서 출구(14) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(12)가 형성되며, 상기 입구(13)의 양단에 지지살 파지부(15)가 형성됨과 아울러 상단에 링 밀착부(16)가 형성된 상부 진입구(10)와;상기 상부 진입구(10)과 일체로 맞대어 결합되되, 상부가 개방된 망체(21)로 형성되고, 입구(23)에서 출구(24) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(22)가 형성되며, 상기 입구(23)의 양단에 지지살 파지부(25)가 형성됨과 아울러 하단에 링 밀착부(26)가 형성된 하부 진입구(20)의 조립구성으로 이루어진 통발용 진입구(E)를 구비하는 한편;상기 하부 진입구(20)의 양측 상단에 형성된 맞댐부(28)에 간격을 두고 다수의 결합돌기(28a)가 돌출 형성되고, 상기 상부 진입구(10)의 양측 하단에 형성된 맞댐부(18)에는 상기 결합돌기(28a)가 끼움 결합되는 다수의 결합홀(18a)이 형성되며;상부링(1) 및 하부링(2)의 사이에 다수의 지지살(3)이 연결되어 형성된 원통형 지지골조(4)의 외측면에 상기 통발용 진입구(E)가 설치되는 부위를 제외한 전체 부위를 그물망(5)이 둘러싸고;상기 통발용 진입구(E)는 지지살 파지부(15)(25)가 한 쌍의 지지살(3)을 파지함과 아울러 링 밀착부(16)(26)가 상, 하부링(1)(2)에 각각 밀착된 상태에서 그물망 보호구(30)를 이용하여 상기 링 밀착부(16)(26) 및 상, 하부링(1)(2)을 함께 감싸는 원터치 조작으로 상기 통발용 진입구(E)를 편리하게 설치하는 것을 특징으로 하는 낙지의 탈출을 방지하는 통발용 진입구가 적용된 통발., Ltext: 어업, prediction: 어업
216/1059 Row 216: application_number: 1020200074042, combined_string: invention_title: 모터 내입형 다기능 양망기. abstract: 본 발명은 원통형의 모터 하우징에 모터가 장착되고, 외경에 회동드럼이 형성되어 있어 설치시 공간적인 제약이 거의 없으며, 취부용 브라켓을 이용하여 선체에 고정할 수 있음에 따라 선체에 별도로 조립공(고정홀)을 별도로 형성하지 않아도 됨에 따라 선박의 내구성 저하를 최소화할 수 있으며, 양망기에 함께 그물 가이드가 구비되어 별도로 안내 가이드를 구매할 필요가 없으며, 양망기 컨트롤 박스를 선내 또는 유선 리코컨으로 조작이 가능함에 따라 최소 인원으로 양승작업을 할 수 있으며, 양망기인 경우 일반적으로 사용되는 차량용 배터리를 사용함에 따라 충전 및 방전이 효율적이고 굳이 선박의 엔진을 가동할 필요가 없어 연료비를 절감할 수 있으며, 그물을 수리시에 기존은 인력을 이용하여 외부에 펼친후 수리하였으나, 양망기를 이용하여 손쉽게 외부에서 그물수리 작업을 할 수 있어 과도한 인력낭비를 최소화하여 경제적으로 사용할 수 있다. claims: 선박 내측에 고정할 수 있도록 사각형상의 취부용 브라켓이 형성되고, 취부용 브라켓 중앙에는 원통형의 모터 하우징이 구비되며, 모터 하우징 내경에는 다수개의 모터 고정 지지대가 형성되며, 모터를 작동할 수 있도록 선박 내부에 컨트롤 박스가 형성되며, 상기 모터 고정 지지대에는 모터가 구비되며, 모터의 샤프트에는 내입홈부가 형성되며, 샤프트가 관통될 수 있도록 중앙에 제 1 관통공이 형성된 샤프트 고정 하우징이 구비되며, 상기 샤프트는 회동드럼을 관통한 후 전면 브라켓의 중앙에 형성된 브라켓 통공에 거치된 후 브라켓 통공 상부에 형성된 걸림부에 샤프트의 내입홈부가 거치되는 모터 내입형 다기능 양망기에 있어서, 상기 회동드럼은 중앙에 제 2 관통공이 형성된 배면 브라켓이 형성되며, 배면 브라켓 전면에는 중앙에 제 3 관통공이 구비된 제 1 타원부가 구비 되며, 제 1 타원부의 전면에는 중앙에 제 4 관통공이 형성된 원통형의 연결 부재가 형성되며, 상기 연결부재의 외경에는 등 간격으로 다수개의 완충부재가 구비되며, 내경에는 다수개의 베어링 부재가 형성되며, 베어링 부재는 베어링 지지대 전면과 배면에 각각 제 1 돌출부와 제 2 돌출부가 구비되며, 상기 제 1 돌출부에는 제 1 와셔와 롤러 및 제 2 와셔가 순차적으로 결합되며, 제 2 돌출부는 제 2 타원부의 조립공에 결합되며, 제 2 타원부는 연결 부재의 전면에 용접결합되며, 제 2 타원부의 중앙에는 타원부 통공이 형성되며, 타원부 통공에 면접될 수 있도록 중앙에 브라켓 통공이 구비된 전면 브라켓이 형성되며, 상기 브라켓 통공 상부는 걸림부가 구비되며, 상기 전면 브라켓 전면에는 전면 커버가 형성됨을 특징으로 하는 모터 내입형 다기능 양망기., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

217/1059 Row 217: application_number: 1020200036288, combined_string: invention_title: 암반해역 수산자원 포획용 저층트롤어구 abstract: 해양에서 이동하고 사이드 또는 선미에서 그물의 수거가 가능한 선체; 상기 선체와 연결되는 하나 이상의 끌줄; 상기 끌줄과 연결되는 전개판과; 상기 전개판과 앞 끝에 연결한 후 타 끝에는 자루형상의 그물 좌우 앞 끝에 연결되는 후릿줄과; 상기 후릿줄과 연결되어 해저의 골재를 채취되며 몸통그물과 끝자루를 포함하는 그물감으로 이루어지는 암반용 저층트롤어구를 제공함으로써, 골재채취해역의 급격한 암반지형에 타이어부가 바퀴처럼 굴러서 지나가게 트롤어구가 예인됨으로 트롤어구의 손상을 최소화할 수 있으므로 기존의 다양한 암반지형에서 발생하는 어구가 파손되는 것을 줄일 수 있다. claims: 해양에서 추진력으로 이동되며 사이드 또는 선미에서 양망 가능한 선체 및 선체와 한 쌍의 전개판을 연결하는 끌줄 및 한 쌍의 전개판과 자루형상의 그물을 연결하는 후릿줄 및 상기 후릿줄과 연결되어 몸통그물과 끝자루를 포함하는 그물 어구로 이루어지는 저층트롤 어구에 있어서, 상기 그물어구는 날개그물과 몸통그물 끝자루로 구분되고, 날개그물은 밑날개와 윗날개로 구분되어 결합되며, 상기 몸통그물은 날개 삼각망, 자루 삼각망, 천정망, 자루등판, 자루옆판, 자루밑판, 밑판 삼각망으로 이루어지고,상기 날개그물의 밑날개와 몸통그물의 자루밑판과 밑판 삼각망은 PEUC 네트(Polyethylene Ultra Cross Netting)로 이루어지며,상기 밑날개와 자루밑판에는 발줄이 연결되고 발줄에는 복수개의 타이어 결합으로 이루어지는 타이어부가 연결되어 급격한 암반지형에서 타이어부가 바퀴처럼 굴러서 지나가도록 그물어구가 예인됨으로 암반해역에서 그물어구의 손상을 방지할 수 있도록 한 것을 특징으로 하는 암반해역 수산자원 포획용 저층트롤 어구, Ltext: 어업, prediction: 어업
218/1059 Row 218: application_number: 1020200027689, combined_string: invention_title: 동·식물 인공어초 abstract: 동·식물 인공어초가 개시된다. 상기 동·식물 인공어초는 다각형 블록 형태의 동식물 인공어초로서, 다각형 블록의 중심부에 형성되는 제1 해양동물서식공간; 상기 제1 해양동물서식공간의 둘레 주변에 고리형상으로 형성되고, 다각형 블록의 상면으로부터 소정 깊이를 갖도록 형성되는 제2 해양동물서식공간; 다각형 블록의 서로 이웃하는 측면을 사선으로 관통하여 형성되는 복수의 제3 해양동물서식공간; 및 상기 제1 해양동물서식공간의 둘레에 배치되도록 다각형 블록의 내부에 구비되고, 다각형 블록의 측면 및 상기 제1 해양동물서식공간의 내면에 소통되고, 다각형 블록의 측면에 소통하는 방향이 입출구를 형성하며, 단지 형상을 갖는 복수의 제4 해양동물서식공간을 포함하고, 상기 제1 해양동물서식공간 에는 사석이 채워지며, 상기 제1 내지 제4 해양동물서식공간(110, 120, 130, 140)을 통해 다양한 어종, 문어류, 해조류, 해삼, 전복 및 갑각류의 서식이 가능하다. claims: 다각형 블록 형태의 동·식물 인공어초로서,다각형 블록의 중심부에 형성되는 제1 해양동물서식공간(110);상기 제1 해양동물서식공간(110)의 둘레 주변에 고리형상으로 형성되고, 다각형 블록의 상면으로부터 소정 깊이를 갖도록 형성되는 제2 해양동물서식공간(120);다각형 블록의 서로 이웃하는 측면을 사선으로 관통하여 형성되는 복수의 제3 해양동물서식공간(130); 및상기 제1 해양동물서식공간(110)의 둘레에 배치되도록 다각형 블록의 내부에 구비되고, 다각형 블록의 측면 및 상기 제1 해양동물서식공간(110)의 내면에 소통되고, 다각형 블록의 측면에 소통하는 방향이 입출구를 형성하며, 단지 형상을 갖는 복수의 제4 해양동물서식공간(140)을 포함하고,상기 제1 해양동물서식공간(110) 에는 사석(150)이 채워지며,상기 제1 내지 제4 해양동물서식공간(110, 120, 130, 140)을 통해 다양한 어종, 문어류, 해조류, 해삼, 전복 및 갑각류의 서식이 가능하도록 구비되고;상기 제1 해양동물서식공간(110)의 내면에 밀착할 수 있는 고리 형상을 가지며, 상기 제1 해양동물서식공간(110)의 높이에 대응하는 높이를 갖고, 내면에 상기 고리 형상을 따라 형성되고 상기 고리 형상의 높이 방향으로 다수 배열되며 상기 고리 형상의 내측 방향으로 소정 형상으로 돌출되는 복수의 볼륨부(211)를 포함하는, 제1 사석구속부재(210);상기 각각의 볼륨부(211) 내에 채워져서 상기 각각의 볼륨부(211)의 볼륨을 유지시키는 볼륨유지탄성부재(220); 및상기 제1 해양동물서식공간(110)의 바닥면으로부터 수직하게 세워지는 지주부(231) 및 상기 지주부(231)의 전체 길이를 덮는 실리콘 재질의 지주커버부(232)를 포함하고, 상기 제1 해양동물서식공간(110) 내에 랜덤하게 배치되는 복수의 제2 사석구속부재(230)를 더 포함하며,상기 제1 내지 제4 해양동물서식공간(110, 120, 130, 140)을 통해 다양한 어종, 문어류, 해조류, 해삼, 전복 및 갑각류의 서식이 가능하도록 구비된 것을 특징으로 하는 동·식물 인공어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

219/1059 Row 219: application_number: 1020200007239, combined_string: invention_title: 선망 어업에 사용되는 그물 조립체 abstract: 이 발명은 선박에 의해 견인되어 어류를 포위하여 앙망함으로써 어류를 포획하는 선망 어업에서 사용하는 그물 조립체에 관한 것으로서, 해수면에 부유하여 그물 조립체에 부력을 제공하고, 복수 개가 그물 조립체의 길이 방향으로 서로 인접하게 배치되는 복수 개의 부력체; 해수면으로부터 침강하여 전개되어 어류를 포위 및 포획하는 그물; 그물 조립체의 길이 방향으로 연장되며, 그물 조립체를 견인하는 견인력을 받는 메인 로프; 부력체를 관통하여 연장되고 메인 로프에 결합되어 부력체를 메인 로프에 지지하여 주는 부력체 결합용 로프; 및 메인 로프를 따라 연장되고 그물이 결합되어 그물을 메인 로프에 지지하여 주는 그물 결합용 로프를 포함하고, 부력체 결합용 로프는 부력체를 관통하여 부력체와 결합되되, 하나의 부력체를 관통한 위치로부터 메인 로프를 관통하여 다시 인접한 부력체의 위치로 복귀함으로써 메인 로프에 대하여 부력체의 반대 위치에 고리를 형성하고, 그물 결합용 로프는 부력체 결합용 로프가 이루는 고리들을 관통하여 연장되는 것이다. claims: 선박에 의해 견인되어 어류를 포위하여 앙망함으로써 어류를 포획하는 선망 어업에서 사용하는 그물 조립체로서, 해수면에 부유하여 그물 조립체에 부력을 제공하고, 복수 개가 그물 조립체의 길이 방향으로 서로 인접하게 배치되는 복수 개의 부력체; 해수면으로부터 침강하여 전개되어 어류를 포위 및 포획하는 그물; 그물 조립체의 길이 방향으로 연장되며, 그물 조립체를 견인하는 견인력을 받는 메인 로프; 부력체를 관통하여 연장되고 메인 로프에 결합되어 부력체를 메인 로프에 지지하여 주는 부력체 결합용 로프; 및 메인 로프를 따라 연장되고 그물이 결합되어 그물을 메인 로프에 지지하여 주는 그물 결합용 로프를 포함하고,부력체 결합용 로프는 부력체를 관통하여 부력체와 결합되되, 하나의 부력체를 관통한 위치로부터 메인 로프를 관통하여 다시 인접한 부력체의 위치로 복귀함으로써 메인 로프에 대하여 부력체의 반대 위치에 고리를 형성하고, 그물 결합용 로프는 부력체 결합용 로프가 이루는 고리들을 관통하여 연장되며, 2개 이상의 부력체 결합용 로프가 마련되어 서로 평행하게 부력체를 관통하도록 배치되고, 메인 로프의 서로 다른 위치를 관통하여 상기 고리를 형성하고, 그물 결합용 로프는 부력체 결합용 로프가 형성하는 고리들을 함께 관통하는 것인, 그물 조립체., Ltext: 어업, prediction: 어업
220/1059 Row 220: application_number: 1020200006666, combined_string: invention_title: 다단층 재순환여과 빌딩양식 시스템 abstract: 본 발명은 물의 수조내 순환방식을 적용하여 해수 환수비율을 줄이면서 활어의 생육에 유리한 환경을 조성함과 동시에 전체 에너지를 저감하고 활어 양식을 통합적으로 관리할 수 있도록 구성된 다단층 재순환여과 빌딩양식 시스템을 제공함을 제공하고자 한 것이다.이를 위해, 본 발명은 다층으로 이루어지되 각층마다 각각 물과 활어가 수용되는 복수 개의 수조모듈이 설치되며, 상기 수조모듈 각각에 물을 공급하는 물공급모듈과 상기 각 수조모듈로부터 배출되는 물을 공급받아 상기 물공급모듈로 재공급하는 수처리모듈을 포함하는 다단층 재순환여과 빌딩양식 시스템을 제공한다. claims: 다층으로 이루어지되 각층마다 각각 물과 활어가 수용되는 복수 개의 수조모듈이 설치되며,상기 수조모듈 각각에 물을 공급하는 물공급모듈과 상기 각 수조모듈로부터 배출되는 물을 공급받아 상기 물공급모듈로 재공급하는 수처리모듈을 포함하며,상기 수조모듈은 전체적으로 폐루프 형태로 이루어져 물이 순환하도록 구성되는 수조부와, 상기 수조부 내측에 설치되어 상기 수조부를 따라 유동하는 물의 유속을 조절하는 유속조절모듈을 포함하며,상기 유속조절모듈은 상기 수조부의 바닥부에 선택된 위치로 적용되는 배출홀과, 상기 배출홀을 통하여 배출되는 물이 유동하는 배출유동관과, 상기 배출유동관에 수직 상향으로 연결되며 상부가 개구된 수직관과, 상기 수직관의 상측에 연결되며 상기 수조부로 물을 재배출하는 절곡관과, 상기 수직관의 하측에 연결되어 외부로부터 공기를 공급받아 상기 배출유동관으로 배출된 물을 공기압을 이용하여 상기 수직관으로 공기와 함께 이동시키는 에어공급관과, 상기 수직관의 상부에 상기 수직관 외부를 둘러 감싸는 형태로 설치되는 버켓부를 포함하며,상기 배출홀 주변으로 상기 수조부 바닥부에는 상기 배출홀로부터 멀어지는 측으로 경사진 형태로 플렉시블한 재질로 이루어진 돌출리브부가 상기 배출홀 주변 둘레를 따라서 소정 이격된 간격마다 구비되는, 다단층 재순환여과 빌딩양식 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

221/1059 Row 221: application_number: 1020200000662, combined_string: invention_title: 어망의 독살 abstract: 조수가 심한 일정한 장소에 기둥관의 어망을 조수를 이용, 자동으로 어망을 상승 하강하여 고기를 잡고 해수욕장 등은 보호구역 내에 독해파리등의 침투를 방지하고 어촌의 바다에 떠다니는 오물, 쓰레기, 장마철의 해파리 떼를 수거 또는 제거하는 것이다. 타 어업에는 전혀 지장이 없는 것이다. claims: 본 발명은 조수차이가 심한 곳의 일정한 장소에 태풍에도 견딜 수 있게 도3과 같이 구성한 기둥관(1) 밖으로 링(8)에 어망줄(29),(31)을 결합, 지렛대(5) 하단의 어망줄구(21)에 결합하고 기둥관(1) 내부에는 부력공(2) 하단에 부력공줄(9)을 하단도르레(6)를 통과, 기둥관(1) 외부 상단도르레(7)를 통과하여 지렛대(5)의 중간 부력줄구(20)를 결합하면 지렛대(5)는 부력공줄구(9)의 당기는 힘으로 지탱이 되어 어망(8)은 해수면(25) 보다 높이 올라 나르는 고기 탈출을 방지하는 것이다. 이리하여 어망줄(31) 중간요소에 어망추(24)를 장착한 하중과 링(4)의 하중으로 퇴수구밸브(13)를 열면 배수와 동시에 어망(8)과 부력공(2)은 하강, 지면에 안착한다. 이리하여 반복으로 어망(8)은 상승, 하강하고 있는 것이다.해수욕장 같은 장소에서는 퇴수구(13)를 열어 놓으면 어망(8)은 물속에서 항상 펴져있는 어망의 독살1항에 있어서 어망(8) 상단에 지렛대(5)를 구성하여 나르는 고기의 탈출을 방지하는 어망의 독살, Ltext: 어업, prediction: 어업
222/1059 Row 222: application_number: 1020190175271, combined_string: invention_title: 무척추동물 유생 사육장치 abstract: 본 발명은 유생 사육장치(1)에 관한 것이다. 그러한 유생 사육장치(1)는, 사육수가 저장되어 무척추 생물을 사육하는 사육조(3)와; 사육조(3)의 내부에 배치되어 무척추 생물의 성장에 맞추어 가변적으로 회전함으로써 사육하는 회전부(5)와; 회전부(5)를 구동시키는 구동부(7)와; 무척추 생물을 외측으로 분산시키는 과밀 방지틀(25)과; 사육조(3)의 물을 외부로 배출하는 배수관(27)과; 그리고 배수관(27)의 상측에 장착되어 배출되는 유수에 함유된 이물질을 제거하는 스크린(9)을 포함한다. claims: 사육수가 저장되어 무척추 생물을 사육하는 사육조(3)와;사육조(3)의 내부에 배치되어 무척추 생물의 성장에 맞추어 가변적으로 회전함으로써 사육하는 회전부(5)와; 회전부(5)를 구동시키는 구동부(7)와; 무척추 생물을 외측으로 분산시키는 과밀 방지틀(25)과; 사육조(3)의 물을 외부로 배출하는 배수관(27)과; 그리고배수관(27)의 상측에 장착되어 배출되는 유수에 함유된 이물질을 제거하는 스크린(9)을 포함하는 유생 사육장치(1)., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

223/1059 Row 223: application_number: 1020190170807, combined_string: invention_title: 적조 및 해양환경 오염방지를 위한 양식장 abstract: 본 발명은 적조 및 해양환경오염방지 양식장의 구조에 관한 것으로서, 더욱 상세하게는 적조 발생시 적조 미생물이 양식장 내부로 침입하는 것을 차단하여 어패류의 폐사를 막고, 해상 양식시 파생되는 사료찌꺼기와 배설물, 폐어구 등이 해저에 바로 침적되지 않고 본 발명의 수족관구조물의 수족관부 내부 바닥에 침적되게 하여 해양환경오염 및 생태계 파괴로 이어지지 않도록 예방하며, 해상원유사고 발생시 유발되는 어패류의 폐사를 막을 수 있도록 양식장구조물, 그물구조물, 수족관구조물이 유기적으로 결합 구성되며, 그물구조물과 수족관구조물이 상하작동이 가능하도록 구성된 적조 및 해양환경 오염방지 양식장 구조물에 관한 것이다. claims: 해상에서 양식작업이 가능하도록 일정한 통로의 형태로 형성된 작업로와 상기 작업로의 상부에 다수개의 수평프레임 및 수직프레임을 포함한 다수의 프레임의 결합으로 이루어지는 프레임구조물로 구성되는 양식장구조물; 어류를 수용할 수 있는 그물망과 상기 그물망의 상부에는 둘레를 따라 그물망을 지탱하도록 상부테두리가 형성되는 그물구조물; 다수개의 수평프레임 및 수직프레임을 포함하여 구성된 상부프레임과, 상기 상부프레임의 하부에 외부 해수의 출입을 차단하는 통형태의 수족관부로 이루어진 수족관구조물; 상기 수족관구조물을 들어 올릴 수 있도록 상기 프레임구조물의 일정위치에 설치된 제1승강수단; 및 상기 그물구조물을 들어 올릴수 있도록 상기 프레임구조물의 일정위치에 설치된 제2승강수단을 포함하여 구성되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장에서, 상기 그물구조물의 상부테두리에는 상기 제2승강수단과 결합하는 결합부가 형성되고, 상기 양식장구조물의 상단에 결합되어 아랫방향으로 형성된 가이드프레임이 관통할 수 있도록 가이드프레임 결합구멍이 형성되며, 상기 가이드프레임결합구멍에는 상기 가이드프레임이 원활하게 움직일수 있도록 지지롤러가 형성되고, 상기 그물구조물의 하단에는 상기 그물망을 개방할수 있는 개방수단이 구비되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장.해상에서 양식작업이 가능하도록 일정한 통로의 형태로 형성된 작업로와 상기 작업로의 상부에 다수개의 수평프레임 및 수직프레임을 포함한 다수의 프레임의 결합으로 이루어지는 프레임구조물로 구성되는 양식장구조물; 어류를 수용할 수 있는 그물망과 상기 그물망의 상부에는 둘레를 따라 그물망을 지탱하도록 상부테두리가 형성되는 그물구조물; 다수개의 수평프레임 및 수직프레임을 포함하여 구성된 상부프레임과, 상기 상부프레임의 하부에 외부 해수의 출입을 차단하는 통형태의 수족관부로 이루어진 수족관구조물; 상기 수족관구조물을 들어 올릴수 있도록 상기 프레임구조물의 일정위치에 설치된 제1승강수단; 및 상기 그물구조물을 들어 올릴수 있도록 상기 프레임구조물의 일정위치에 설치된 제2승강수단을 포함하여 구성되는 것을 특징으로 하는 적조 및 해양환경오염방지를 위한 양식장에서, 상기 수족관구조물은 상기 수족관부의 하부에 형성되어 내부가 빈 상태로 밀폐된 부기통부와, 상기 상부프레임의 상부에 형성되어 제1승강수단과 결합하는 상부고리를 더 포함하여 형성되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장.해상에서 양식작업이 가능하도록 일정한 통로의 형태로 형성된 작업로와 상기 작업로의 상부에 다수개의 수평프레임 및 수직프레임을 포함한 다수의 프레임의 결합으로 이루어지는 프레임구조물로 구성되는 양식장구조물; 어류를 수용할 수 있는 그물망과 상기 그물망의 상부에는 둘레를 따라 그물망을 지탱하도록 상부테두리가 형성되는 그물구조물; 다수개의 수평프레임 및 수직프레임을 포함하여 구성된 상부프레임과, 상기 상부프레임의 하부에 외부 해수의 출입을 차단하는 통형태의 수족관부로 이루어진 수족관구조물; 상기 수족관구조물을 들어 올릴 수 있도록 상기 프레임구조물의 일정위치에 설치된 제1승강수단; 및 상기 그물구조물을 들어 올릴수 있도록 상기 프레임구조물의 일정위치에 설치된 제2승강수단을 포함하여 구성되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장에서, 제1승강수단과 제2승강수단은 각각 도르래와 와이어를 포함하여 구성하되, 상기와이어의 일단에는 갈고리가 결합되어 각각 상기 수족관구조물과 그물구조물에 결합 및 해지될 수 있으며, 나머지 일단에는 하나 이상의 결합링이 결합되어 상기 프레임구조물의 일정위치에 형성된 고정수단에 걸어, 상기 수족관구조물과 상기 그물구조물을 일정위치에 고정할 수 있도록 구성되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장., Ltext: 어업, prediction: 어업
224/1059 Row 224: application_number: 1020190170131, combined_string: invention_title: 홈이 없는 방오어망 및 그 제조방법 abstract: 본 발명은 어망 소재 섬유의 내열성 여부와 관계없이 2종의 방오물질이 첨가된 열가소성수지를 용융 침적 후 냉각 또는 열경화성수지를 상온에서 침적 후, 열 경화하여 어망에 피복하되, 어망용 섬유의 열 손상 방지를 위해, 섬유의 물성 변화 온도 이하, 합성수지의 용융 또는 경화온도 범위에서 최단 시간 피복을 위해서, 연속적인 제망공정을 분리하여, 1차로, 스트랜드를 피복한 후, 2차로, 제망한 어망을 재피복해서 어망 로프의 홈을 메워 표면을 매끄럽게 하고, 윤활성, 항균성, 전기전도성을 가지며, 슈퍼 섬유에 피복하여 굵기가 가는 어망 및 동합금어망 보다 저중량, 저가로 제조하며, 피복된 합성수지는 상온건조형 방오도료 보다 내구성이 우수한 친환경 방오어망이 특징이다. claims: 홈이 없는 전기전도성 방오어망에 있어서,전기전도성이 있는 자기윤활성물질과 무기항균제가 첨가된 합성수지로 어망을 피복하되,상기 합성수지는 어망용 소재 섬유와 같이 유연성이 있는 합성수지로써 열가소성이면 용융상태의 수지에 침적하여 일체형 성형을 위해서 탈포, 급냉하여 피복하고, 열경화성이면 상온에서 액상 수지에 침적, 탈포, 가열 경화하여 피복하며, 열가소성수지의 용융열 또는 열경화성수지의 경화열에 의해 어망용 소재 섬유의 물성이 변화하는 온도 이하 및 열가소성수지의 용융온도 또는 열경화성수지의 경화온도 이상으로써 피복이 가능한 온도 범위, 즉 온도차(△t)에서 피복함으로써 어망용 소재 섬유에 대한 열 손상 없이 피복이 가능하고,상기 어망의 로프 외주면에 피복된 합성수지(360)가 로프에 형성된 섬유 올의 미세 홈(130)과 나선형 홈(330)을 메우고, 위사와 경사 로프(310, 320)의 교차부위에 형성된 홈(340)은 교차부위에 형성된 합성수지(350)가 메워 로프(100)의 전체 표면을 매끄럽게 하여 해양생물이 착상하는 홈을 제거하고, 자기윤활성물질에 의해 로프 표면을 미끄럽게 하는 물리적 방오 기능, 무기항균제에 의한 항균기능과 전기전도성을 가지는 것을 특징으로 하는 홈이 없는 전기전도성 방오어망., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

225/1059 Row 225: application_number: 1020190168559, combined_string: invention_title: 어류양식장의 순환여과를 위한 차세대 스마트 여과시스템 abstract: 본 발명에 따른 어류양식장의 순환여과용 차세대 스마트 여과시스템은 시스템 내부에 기능성 여과 챔버를 구비하여 오염원별로 이를 여과할 수 있도록 함으로서 여과 효율을 증대시키고 또한 설비의 유지보수 비용을 대폭 절감하기 위해 각 여과챔버의 운정 상황을 감시하고 제어하는 기능을 전자동으로 가능하게하며, 이를 인터넷 등 통신망과 연결하여 컴퓨터나 모바일 기기등을 활용하여 원격으로 감시 및 제어할 수 있도록 설게된 차세대 맞춤형 스마트 여과장치이다.일반적인 여과장치는 단순히 유량의 흐름만을 감시하며 이를 통해 설비유지 및 보수의 필요성을 작업자가 판단하도록 하여 불편함이 있었으나 이를 자동화하고 자동 전송시킴으로서 운영의 편리성을 증대시켜 원가절감을 극대화 할 수 있다.또한 이를통해 미세 오염물, 항생물질 등의 문제적 오염물질 등을 여과함으로서 어류양식장의 배출수에 의한 오염을 줄이고, 물의 재사용율을 높임으로서 첨단 순환여과 방식의 확산에 기여하여 환경적 측면과 양식어가의 수익성 증대 등 양측면에 기여할 수 있는 장점이 있다. claims: 오염물질을 선택적으로 여과해주는 필터 카트리지의 제조 및 조립방법과 필터 카트리지 내부의 필터간 빈 공간에 활성탄 비드를 채운 필터카트리지필터 카트리지가 내부에 카트리지 두께만큼의 간격으로 5개 ~20개 이내로 장착되어 오염수의 흐름을 원활하게 유지하며 여과 챔버의 처리량을 증대시킨 여과 챔버여과챔버의 양측면 상단과 하단에 입수부에 한개의 입수구가 장치되고, 배수부에 상,하로 두개의 배수구가 장치되고 이를 제어형밸브로 선택적으로 배수 경로를 결정할 수 있도록 설계 및 조립된 여과 챔버 각 여과 챔버별로 각각의 여과 기능을 달리하여 선택적으로 오염물질을 여과함으로서 필터카트리지의 교체 및 교환과 설비유지보수의 편리성을 증대시킴.정상운전시 배수부의 상단에 위치한 배수구를 통하여 배수되도록 설계되어 최소 7분 이상의 접촉 및 반응 시간동안 정체 시켜 여과 효율을 증대시킨 여과챔버금속프로파일 구조물에 여과챔버를 장치시킴에 있어서 입수부의 위치를 수평에서 각도로 1~3도 정도 높게 위치하여 여과 챔버내에 잔류 오염수가 남지 않도록 하는 점여과 시스템의 자동과 수동 조작을 위한 운전조작반에 있어서 통신기법을 이용한 원격감시제어 기능을 구비하여 인터넷 또는 모바일기기 등으로 감시 및 제어가 가능한 기능의 부가, Ltext: 어업, prediction: 어업
226/1059 Row 226: application_number: 1020190156831, combined_string: invention_title: 다단형 경량화 구조를 갖는 고순환 여과방식 이미패류 관리시스템 abstract: 본 발명은 사육 수조의 수위를 극도로 낮추어 패류가 공기 중에 노출되지 않는 범위에서 수심을 결정할 수 있고, 기존 순환여과 시스템의 사육 수조보다 수량이 극도로 작기 때문에 동일동력에서 환수율을 증가시킬 수 있으며, 순환율을 높여 먹이생물 유실을 최소화시킬 수 있도록 한 다단형 경량화 구조를 갖는 고순환 여과방식 이미패류 관리시스템에 관한 것이다. claims: 사육수조, 물리여과조, 생물학적 여과조, 디지털순환펌프(사육수의 온도조절 및 해수공급 기능), 히트펌프(펌프와 연동해서 작동), 컨트롤 판넬을 포함하는 다단형 경량화 구조를 갖는 고순환 여과방식 이미패류 관리시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

227/1059 Row 227: application_number: 1020190151885, combined_string: invention_title: 유해 외래어종 산란장 abstract: 본 발명은 유해 외래어종 산란장에 관한 것으로 본 발명의 일면에 따른 유해 외래어종 산란장은 수중 바닥에 안착되는 산란틀, 산란틀의 상부에 탈착가능하게 설치되고 산란틀의 상부에 입구와 출구를 마련하는 가림막, 산란틀의 일측에 연결된 상태에서 하단이 수중 바닥에 고정되고 상단이 수면위로 노출되는 지지대, 지지대의 상단에 설치되는 태양전지, 지지대에 설치되고, 태양전지로부터 전원을 공급받아, 입구와 출구를 촬영하는 카메라를 포함한다. claims: 수중 바닥에 안착되는 산란틀;상기 산란틀의 상부에 탈착가능하게 설치되고 상기 산란틀의 상부에 입구와 출구를 마련하는 가림막;상기 산란틀의 일측에 연결된 상태에서 하단이 수중 바닥에 고정되고 상단이 수면위로 노출되는 지지대;상기 지지대의 상단에 설치되는 태양전지; 및상기 지지대에 설치되고, 상기 태양전지로부터 전원을 공급받아, 상기 입구와 출구를 촬영하는 카메라;를 포함하는 유해 외래어종 산란장., Ltext: 어업, prediction: 임업
228/1059 Row 228: application_number: 1020190147376, combined_string: invention_title: 폭기설비를 활용한 사육조 유속 조절장치 abstract: 순환형 수산양식장의 순환시스템에서 순환되는 사육수의 운동성 및 목적 용존산소 용해도까지 올리고 효율성을 높이기 위해 발명하는 시스템으로서 폭기설비와 순환수 통합하는 장치와 이의 분사노즐의 위치와 각도 등을 조절하여 사육수의 운동성 및 용해도를 높이는 방식으로 발명의 목적을 구현한다. claims: 순환형 수산양식장의 순환시스템에서 순환되는 사육수의 운동성 및 목적 용존산소 용해도까지 올리고 효율성을 높이기 위해 발명하는 시스템으로서 폭기설비와 순환수 통합하는 장치와 이의 분사노즐의 위치와 각도 등을 조절하여 사육수의 운동성 및 용해도를 높이는 방식의 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

229/1059 Row 229: application_number: 1020190142790, combined_string: invention_title: 스마트 양식 수조용 히트펌프 시스템 abstract: 본 발명은, 양식을 위한 양식장 수조; 해수를 공급받아 상기 양식장 수조에 사용하는 해수를 공급하는 해수조; 상기 양식장 수조에서 사용한 오폐수가 배출되는 배수라인에 설치된 오폐수 열교환부; 상기 오폐수를 순환시키는 순환부; 상기 해수조로부터 해수를 공급받아 상기 오폐수 열교환부에 거쳐서 상기 해수보다 승온된 해수를 상기 양식장 수조로 공급하는 제 1 공급라인; 상기 해수조로부터 해수를 공급받아 상기 오폐수 열교환부에 거쳐서 상기 해수보다 승온된 해수를 저장하고, 보일러를 통해서 추가로 승온하는 것이 가능한 온수조; 상기 온수조로부터 해수를 공급받아 상기 양식장 수조로 공급하는 제 2 공급라인; 상기 해수조로부터 해수를 공급받아 상기 해수를 상기 양식장 수조로 공급하는 제 3 공급라인; 및 상기 온수부 앞의 위치에서 제 1 공급라인에서 상기 해수조로 해수를 회수시키는 회수부;를 포함하고, 상기 양식장 수조 및 상기 해수조의 온도 및 저수량를 각각 검출하는 제 1 센서부 및 제 2 센서부, 그리고 제 1 공급라인, 제 2 공급라인, 및 제 3 공급라인의 해수 온도를 검출하는 제 3 센서부, 제 4 센서부, 및 제 5 센서부; 및 상기 양식장 수조에서 필요로 하는 온도의 해수량을 최저의 에너지 소비로 공급하기 위하여 계산하는 제어부;를 더 구비하고, 상기 제어부의 제어에 따라서, 제 1 공급라인, 제 2 공급라인, 및 제 3 공급라인을 통한 해수의 공급량이 조절되는 것을 특징으로 하는, 양식 수조용 히트펌프 시스템을 개시한다. claims: 양식을 위한 양식장 수조; 해수를 공급받아 상기 양식장 수조에 사용하는 해수를 공급하는 해수조; 상기 양식장 수조에서 사용한 오폐수가 배출되는 배수라인에 설치된 오폐수 열교환부; 상기 오폐수를 순환시키는 순환부; 상기 해수조로부터 해수를 공급받아 상기 오폐수 열교환부에 거쳐서 상기 해수보다 승온된 해수를 상기 양식장 수조로 공급하는 제 1 공급라인; 상기 해수조로부터 해수를 공급받아 상기 오폐수 열교환부에 거쳐서 상기 해수보다 승온된 해수를 저장하고, 보일러를 통해서 추가로 승온하는 것이 가능한 온수조; 상기 온수조로부터 해수를 공급받아 상기 양식장 수조로 공급하는 제 2 공급라인; 상기 해수조로부터 해수를 공급받아 상기 해수를 상기 양식장 수조로 공급하는 제 3 공급라인; 및상기 온수부 앞의 위치에서 제 1 공급라인에서 상기 해수조로 해수를 회수시키는 회수부;를 포함하고, 상기 오폐수 열교환부는, 쉘과 상기 쉘 내에 위치한 다수의 튜브로 이루어진 히트 펌프를 포함하며, 상기 다수의 튜브를 일일이 한 개씩 청소하지 않고 복수 개의 노즐을 회전시키면서 세척하는 것이 가능하도록 랙앤 피니언 기어를 이용한 기구에 부착될 수 있는 구조를 채택한 것을 특징으로 하는, 양식 수조용 히트펌프 시스템., Ltext: 어업, prediction: 임업
230/1059 Row 230: application_number: 1020190142292, combined_string: invention_title: 선박용 그물 로프 양망장치 abstract: 본 발명은 선박용 그물 로프 양망장치에 관한 것으로, 상부 로터 하우징과 하부 로터 하우징으로 구성되는 로터 하우징; 상기 상부 로터 하우징에 결합되는 감속기와, 상기 감속기의 하부에 결합되는 모터와, 상기 하부 로터 하우징에 내장되며, 상기 모터의 구동 및 속도 제어를 위한 유압을 공급하는 유압 공급부로 구성되며, 상기 상부 로터 하우징을 회전시키는 회전수단; 상기 상부 로터 하우징에 결합되며, 상기 상부 로터 하우징으로부터 소정의 회전력을 전달받는 회전축; 상기 회전축과 결합되고, 상기 회전력을 전달받아 회전 작동하면서 그물 로프의 권취가 이루어지는 권취롤러; 및 상기 회전수단의 회전 여부 및 회전 속도를 제어하는 제어장치;를 포함하는 것을 특징으로 한다. claims: 상부 로터 하우징과 하부 로터 하우징으로 구성되는 로터 하우징; 상기 상부 로터 하우징에 결합되는 감속기와, 상기 감속기의 하부에 결합되는 모터와, 상기 하부 로터 하우징에 내장되며, 상기 모터의 구동 및 속도 제어를 위한 유압을 공급하는 유압 공급부로 구성되며, 상기 상부 로터 하우징을 회전시키는 회전수단; 상기 상부 로터 하우징에 결합되며, 상기 상부 로터 하우징으로부터 소정의 회전력을 전달받는 회전축; 상기 회전축과 결합되고, 상기 회전력을 전달받아 회전 작동하면서 그물 로프의 권취가 이루어지는 권취롤러; 및 상기 회전수단의 회전 여부 및 회전 속도를 제어하는 제어장치;를 포함하고, 상기 상부 로터 하우징은, 상기 감속기가 결합되는 상부 연결 플랜지와, 상부 중앙에 돌출되게 형성되며, 상기 회전축의 하단부가 결합되는 체결홈과, 상기 회전축의 회전 작동을 지지하도록 베어링이 안착되는 안착홈으로 구성되는 축 결합부와, 상기 축 결합부의 외주면을 따라 소정 간격 이격되게 다수개의 지지리브로 구성되는 것을 특징으로 하는 선박용 그물 로프 양망장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

231/1059 Row 231: application_number: 1020190136560, combined_string: invention_title: 바지락 유생 및 치패 중간육성장치 abstract: 본 발명은 바지락 유생 및 치패의 중간육성장치에 관한 것으로 가상식 구조물 구조로 일정 직경의 파이프가 파이프 클램프를 매개로 하나 이상 이격고정되고, 상기 마주하는 파이프는 코팅 와이어로 연결되며, 코팅 와이어 상부에는 안전망이 수평으로 설치되는 와류시설과, 상기 와류 시설에는 복수개의 채묘기가 설치되어 와류시설 내 와류를 일으켜 바지락 유생 및 치패를 채묘기내로 유도가 가능하고 바지락 채묘기를 신속하게 중간 육성장으로 이동 및 양성하기 용이한 잠입성 패류의 종묘육성장치 및 이를 이용한 채묘방법을 제공함으로써, 불안정한 국내 바지락 바지락 종패 수급문제 해결을 기대해 볼 수 있고, 자연채묘 된 바지락 유생 및 치패를 신속하게 중간육성장으로 이동 및 양성이 가능하도록 하여 생존율을 극대화 할 수 있을 뿐만 아니라 잠입성 패류의 자연채묘가능성 확보로 바지락이외의 다른 잠입성 패류에도 적용할 수 있는 효과가 있다. claims: 가상식 구조물 형태로 일정 직경의 파이프가 파이프 클램프를 매개로 바닥과 수직으로 하나 이상 이격 고정되어 평단면상 직사각형 구조를 이루고, 평행하는 파이프는 코팅와이어로 연결되며, 상기 코팅와이어 상부에는 안전망이 수평으로 설치되는 와류시설;상기 와류시설 안전망 상부 또는 하부의 갯벌에는 일정 크기의 다각형 구조로 형성되는 패류 채묘기가 설치되며,상기 패류 채묘기는 일정한 다각형의 외측을 구성하는 외측틀과 상기 외측틀의 내측에는 무결절 망지로 이루어진 그물망으로 이루어진 침착판과, 상기 그물망의 망사가 십자로 교차하는 부분에 일정한 인공잔디가 일정 간격으로 결합되며, 상기 침착판 하부에는 바닥판이 착탈 가능하도록 부착되며, 상기 인공잔디가 만드는 잔디와 잔디 사이의 공극에 잠입성 패류 유생이 착저될 수 있도록 한 것을 특징으로 하는 바지락 유생 및 치패의 중간육성장치가상식 구조물 형태로 일정 직경의 파이프가 파이프 클램프를 매개로 바닥과 수직으로 하나 이상 이격 고정되고 이격된 파이프 내측 양단을 연승줄이 연결되며, 연승줄에는 일정 크기의 다각형 구조로 형성되는 패류 채묘기가 설치되며,상기 패류 채묘기는 일정한 다각형의 외측을 구성하는 외측틀과 상기 외측틀의 내측에는 무결절 망지로 이루어진 그물망으로 이루어진 침착판과, 상기 그물망의 망사가 십자로 교차하는 부분에 일정한 인공잔디가 일정 간격으로 결합되며, 상기 침착판 하부에는 바닥판이 착탈 가능하도록 부착되며, 상기 인공잔디가 만드는 잔디와 잔디 사이의 공극에 잠입성 패류 유생이 착저될 수 있도록 한 것을 특징으로 하는 바지락 유생 및 치패의 중간육성장치일정한 다각형의 외측을 구성하는 외측틀과 상기 외측틀의 내측에는 무결절 망지로 이루어진 그물망으로 이루어진 침착판과, 상기 그물망의 망사가 십자로 교차하는 부분에 일정한 인공잔디가 일정 간격으로 결합되며, 상기 침착판 하부에는 바닥판이 착탈 가능하도록 부착되며, 상기 인공잔디가 만드는 잔디와 잔디 사이의 공극에 잠입성 패류 유생이 착저될 수 있도록 한 것을 특징으로 하는 바지락 유생 및 치패의 중간육성장치, Ltext: 어업, prediction: 임업
232/1059 Row 232: application_number: 1020190135812, combined_string: invention_title: 꼬막 종패 분리 및 세척 장치 abstract: 본 발명은 꼬막 종패 분리 및 세척 장치에 관한 것으로서, 더욱 상세하게는 그물망 이동방향에 반대방향으로 회전되는 브러쉬 롤러로 물을 분사하여 부착된 꼬막 종패를 분리시키는 꼬막 종패 분리 및 세척 장치에 관한 것이다.본 발명의 꼬막 종패 분리 및 세척장치는 그물망 이송방향에 반대방향으로 회전되는 제1브러쉬 롤러에 의해 그물망에 부착된 꼬막종패를 분리시키면서, 제1브러쉬 롤러의 상방에 위치에서 물을 분사하는 물 분사관을 통해 동시에 그물망을 세척할 수 있어 작업 효율이 향상될 수 있는 이점이 있다. claims: 선박의 갑판 상에 설치되며 상방으로 꼬막 종패가 부착된 그물망이 이동되는 제1프레임과,상기 제1프레임 상에 상기 그물망의 이동방향에 반대방향으로 회전가능하게 설치되어 상기 그물망에 부착된 꼬막 종패를 분리시키는 제1브러쉬롤러와,상기 제1브러쉬 롤러의 상방에 위치되게 상기 제1프레임의 상단에 설치되고 상기 제1브러쉬 롤러의 길이방향에 나란하게 연장되어 상기 제1브러쉬 롤러 방향으로 상기 그물망 세척 및 꼬막 종패 분리를 위한 물을 분사하는 물 분사관과,상기 제1브러쉬 롤러를 회전시키는 위한 구동부와,상기 물분사관에 물 공급을 위한 제1물 공급펌프를 구비하는 것을 특징으로 하는 꼬막 종패 분리 및 세척장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

233/1059 Row 233: application_number: 1020190135967, combined_string: invention_title: 소형어선용그물망인출장 abstract: 본 고안의 소형 어선용 그물 인출장치는, 어선 본체의 상판 일측에 고정 설치된그물 인출장치를 전개하고자 하는 방향 또는 인양하고자 하는 방향으로 회전시켜 어선 본체의 외부로 돌출시킬 수 있기 때문에 그물의 전개 및 인양 작업이 용이함에 따라 작업 능률을 향상시킴과 아울러 인양시 그물에 일정 이상의 부하가 발생될 때 유압 모우터에 공급되는 오일을 제어하는 릴리이프 밸브가 마련되어 있기 때문에 장비의 고정 발생 및 그물이 찢어지는 현상을 방지할 수 있는 이점이 있다. claims: 어선 본체(1)의 상판(3)에 고정 설치된 하부 지지대(7)와; 상기한 하부 지지대(7)에 회전 가능하게 설치된 상부 지지대(9)와; 상기한 상부 지지대(9)에 고정 설치됨과 아울러 유압의 공급 방향에 따라 정, 역회전 가능한 유압 모우터(23)와; 상기한 유압 모우터(23)의 축상에 제공된 드럼(27)과; 상기한 유압 모우터(23)에 오일을 공급하도록 어선의 기관 작동에 연동하여 저장탱크(39)에 저장된 오일을 펌핑하는 오일펌프(41)와 연통설치되어 유로를 선택적으로 절환시키는 방향 전환 밸브(37)를 포함하여 이루어진 소형 어선용 그물 인출장치., Ltext: 어업, prediction: 임업
234/1059 Row 234: application_number: 1020190129184, combined_string: invention_title: 개량형 사각어초 abstract: 본 발명은 개량형 사각어초에 관한 것으로서, 더욱 상세하게는 종래의 사각어초 구조를 개량하여 연약지반에서 침하를 방지함과 동시에 어패류가 서식할 수 있는 공간을 제공하고 해중림을 조성함으로써 수산자원을 보호하고 육성할 수 있는 사각어초에 관한 것이다. 본 발명의 개량형 사각어초는 어패류의 서식 및 해중림 조성을 위한 사각어초에 있어서, 내부가 비어있는 육면체 형태의 본체와, 본체를 전후 방향 및 좌우 방향, 상하 방향으로 관통할 수 있도록 본체의 각 면마다 형성된 개구부와, 본체의 전후면을 제외한 사면에 일정 간격으로 돌출되어 형성된 돌출부를 구비한다. claims: 어패류의 서식 및 해중림 조성을 위한 사각어초에 있어서, 내부가 비어있는 육면체 형태의 본체와;상기 본체를 전후 방향 및 좌우 방향, 상하 방향으로 관통할 수 있도록 상기 본체의 각 면마다 형성된 개구부와;상기 본체의 전후면을 제외한 사면에 일정 간격으로 돌출되어 형성된 돌출부;를 구비하는 것을 특징으로 하는 개량형 사각어초., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

235/1059 Row 235: application_number: 1020190129185, combined_string: invention_title: 침선 어초 abstract: 본 발명은 폐선박을 해저에 가라앉혀 설치하는 침선 어초에 관한 것으로서, 어패류가 서식하거나 은신할 수 있는 공간을 제공하여 바다 환경을 개선시킴과 동시에 강한 해류에도 전도되지 않고 불법어업을 방지할 수 있는 기능성이 부가된 침선 어초에 관한 것이다. 본 발명의 침선 어초는 상부구조물과 갑판 및 하부선체를 포함하는 폐선박을 개조하여 형성시킨 본체부와, 본체부의 내부로 해수가 유통될 수 있도록 하부선체의 측면에 일정 간격으로 형성된 출입구들과, 본체부의 내부에 설치되어 어패류의 서식공간 및 은신공간을 제공하는 단위어초들과, 본체부가 해저면에 안착된 경우 본체부의 전도를 방지하기 위해 본체부에 설치되는 전도방지수단을 구비한다. claims: 상부구조물과 갑판 및 하부선체를 포함하는 폐선박을 개조하여 형성시킨 본체부와; 상기 본체부의 내부로 해수가 유통될 수 있도록 상기 하부선체의 측면에 일정 간격으로 형성된 출입구들과; 상기 본체부의 내부에 설치되어 어패류의 서식공간 및 은신공간을 제공하는 단위어초들과;상기 본체부가 해저면에 안착된 경우 상기 본체부의 전도를 방지하기 위해 상기 본체부에 설치되는 전도방지수단;을 구비하는 것을 특징으로 하는 침선 어초., Ltext: 어업, prediction: 어업
236/1059 Row 236: application_number: 1020190127066, combined_string: invention_title: 연체동물용 인공어초 abstract: 본 발명은, 연체동물용 인공어초로서, 사다리꼴 형태를 가지며, 전면과 후면에 연체동물이 유입될 수 있는 서식홈이 마련된 제1블록체; 및 상기 제1블록체의 면적보다 작은 면적을 가지는 사다리꼴 형태를 가지며, 상기 제1블록체의 측면과 결합되는 제2블록체;를 포함하며, 상기 제1블록체와 상기 제2블록체는 다수개로 마련된채 서로 교대로 결합되어 수평방향으로 연장된 방벽의 구조체를 형성하는 것을 특징으로 한다. claims: 연체동물용 인공어초로서,사다리꼴 형태를 가지며, 전면과 후면에 연체동물이 유입될 수 있는 서식홈이 마련된 제1블록체; 및상기 제1블록체의 면적보다 작은 면적을 가지는 사다리꼴 형태를 가지며, 상기 제1블록체의 측면과 결합되는 제2블록체;를 포함하며,상기 제1블록체와 상기 제2블록체는 다수개로 마련된채 서로 교대로 결합되어 수평방향으로 연장된 방벽의 구조체를 형성하는 연체동물용 인공어초에 있어서,상기 제2블록체는 상기 제1블록체의 측면에서 상기 서식홈의 개방된 측부를 차단하는 것을 특징으로 하는 연체동물용 인공어초., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

237/1059 Row 237: application_number: 1020190112375, combined_string: invention_title: 문어 산란용 어초 abstract: 본 발명은 문어 산란용 어초에 관련되며, 이때 문어 산란용 어초는 일체형 콘크리트 성형물로 형성되어 제작이 간편하면서 시공성이 우수하고, 출입구와 연통되는 산란공간부 상부영역이 가림블록에 의해 비노출되도록 차폐되어 문어 산란에 최적화된 서식환경을 조성함과 더불어 경사바닥면 및 퇴적물배출구에 의해 산란공간부로 유입되는 모래를 포함하는 이물질이 신속하게 배출처리되므로 산란공간부 내의 서식환경이 장기적으로 쾌적하게 유지되도록 하기 위해 본체블록(10), 산란공간부(20), 가림블록(30), 해수홀(40)을 포함하여 주요구성으로 이루어진다. claims: 제강슬래그골재 50~60 중량부, 전기로산화슬래그 20~30 중량부, 모래 10~20 중량부, 슬래그시멘트 10~15 중량부를 포함하는 혼합물로 형성되고, 받침다리(12)에 의해 저면이 해저바닥과 이격되어 하부해수통로(14)가 형성되도록 설치되는 본체블록(10);상기 본체블록(10) 일측으로 개방되는 출입구(22)와 연결되고, 천장에 평탄면(24)이 형성되는 산란공간부(20);상기 출입구(22) 상부에서 하향 돌출되어, 출입구(22)를 통하여 산란공간부(20) 상부영역이 비노출되도록 차폐하는 가림블록(30); 및상기 본체블록(10) 측면 및 상면에서 산란공간부(20) 내부로 관통되어 해수를 순환하도록 구비되는 해수홀(40);을 포함하여 이루어지고,상기 출입구(22)는 산란공간부(20) 대비 축소된 사이즈로 형성되어, 출입구(22) 바닥면이 산란공간부(20) 바닥면 연장선상에 일치되도록 편심 위치에 구비되며,상기 산란공간부(20) 바닥면과 출입구(22) 바닥면은 본체블록(10) 외부로 갈수록 하향 경사각을 이루는 경사바닥면(50)으로 형성되어, 산란공간부(20) 내부로 유입되는 모래를 포함하는 이물질이 경사바닥면(50)을 타고 본체블록(10) 외부로 배출되도록 구비되는 것을 특징으로 하는 문어 산란용 어초., Ltext: 어업, prediction: 어업
238/1059 Row 238: application_number: 1020190104996, combined_string: invention_title: 인공어초 abstract: 본 발명은 콘크리트 재질의 박스형상의 프레임으로 각면에 유로가 형성된 유닛의 조립에 의해 형성되는 인공어초에 관한 것이다. claims: 콘크리트 재질의 박스형상의 프레임으로 각면에 유로가 형성된 유닛의 조립에 의해 형성되고,상기 유닛은 백태방지층이 외연에 도포되고,상기 백태방지층은, 수지 100중량부에 대해 다공성세라믹볼 20 내지 80중량부, 실리카퓸 20 내지 40중량부, 이산화티탄 10 내지 30중량부, 부틸카비톨 5 내지 10중량부, 부틸셀로솔브 5 내지 10중량부, 수용성증점제 1 내지 3중량부, 탄산수소칼륨 0.1 내지 2중량부를 포함하는 것을 특징으로 하는 인공어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

239/1059 Row 239: application_number: 1020190104200, combined_string: invention_title: 바이오플락 발효조와 아쿠아포닉스를 이용한 순환여과식 양식시스템 abstract: 물의 효과적인 순환을 가능하게 하는 생물사육수조; 유기물을 배출하지 않고 이를 다시 이용하여 바이오플락의 영양분을 이용하는 발효조; 또한 잔여 유기고형물을 자동으로 수세 및 역세를 통해 순환여과조 및 발효조로 이동이 가능한 유기고형물 제거 장치; 식물재배수조로 구성된 순환여과식 양식시스템(Recirculating aquaculture system; RAS)에서 발생한 유기물을 바이오플락(Biofloc Technology; BFT)으로 재활용하는 아쿠아포닉스 시스템을 제공함으로서, 양식생물과 재배식물의 생산성 증대로 이루어지며 또한 잔여 유기물의 세척을 통해 더욱 효과적인 수질관리를 통해 완전한 물 순환으로 매우 친환경적이며, 경비를 절감할 수 있는 시스템으로 친환경 양식 산업화에 기여한다. claims: 양식어종을 사육하는 순환여과식 양식시스템; 순환여과식 양식시스템에서 배수된 사육수를 필터링하는 드럼필터;상기 드럼필터의 필터링된 사육수가 이동되어 정화되는 순환여과시스템;상기 드럼필터의 역세수가 이동되어 정화되는 자동여과시스템; 상기 자동여과시스템의 역세수에 산소를 공급 및 혼합하는 바이오플락 발효시스템; 상기 바이오플락 발효시스템에서 이동된 고농도 산소가 혼합된 사육수로 식물 재배가 가능한 식물재배시스템;을 포함하여 이루어지는 것을 특징으로 하는 바이오플락 발효조와 아쿠아포닉스를 이용한 순환여과식 양식시스템양식어종을 사육하는 순환여과식 양식시스템; 순환여과식 양식시스템에서 배수된 사육수를 바이오플락 발효시스템에서 식물재배용 사육수로 정화하여 식물재배시스템으로 공급하여 사용한 후, 순환여과식 양식시스템으로 공급하는 순환구조를 갖는 포함하여 이루어지는 것을 특징으로 하는 바이오플락 발효조와 아쿠아포닉스를 이용한 순환여과식 양식시스템, Ltext: 어업, prediction: 어업
240/1059 Row 240: application_number: 1020190104030, combined_string: invention_title: 안전한 서식환경이 구비된 어류 서식처 및 시공방법 abstract: 본 발명은 안전한 서식환경이 구비된 어류 서식처 및 시공방법에 관한 것으로서, 강이나 바다에서 물고기 등과 같은 어류의 안전한 서식환경 및 산란처를 제공함으로써 수상 생태계 복원에 효과를 나타내기 위한 것이다.이를 실현하기 위한 본 발명의 어류 서식처는, 어류의 출입이 가능하도록 일측에 출입공간(11)이 형성된 육면체 형상의 철망 하우징(10)과; 상기 철망 하우징(10) 상부에 안착 되는 다수의 조경석(20)과; 상기 철망 하우징(10)과 조경석(20) 사이에 배치되어 식물의 성장이 이루어지는 식생매트(30);를 포함하는 구성을 이루는 것을 특징으로 한다. claims: 어류의 출입이 가능하도록 일측에 출입공간(11)이 형성된 육면체 형상의 철망 하우징(10)과;상기 철망 하우징(10) 상부에 안착 되는 다수의 조경석(20)과;상기 철망 하우징(10)과 조경석(20) 사이에 배치되어 식물의 성장이 이루어지는 식생매트(30);를 포함하되,상기 철망 하우징(10)은 내부에 자갈이 채워진 상태에서 개별 제작된 다수개가 중앙에 출입공간(11)을 형성하도록 연결 조립된 구조를 이루되, 상호간의 대응 부위에는 볼트 체결을 위한 연결플레이트(10a)가 구성되며, 철망 하우징(10)에는 내부의 수류 유동을 제한하기 위하여 측벽 둘레를 따라 일정 높이로 방수시트(12)가 구성됨과 함께 측압을 지지하기 위한 지지핀(13)이 구성되고, 상부에 형성된 출입공간(11)에는 조경석(20)의 중량을 지지하기 위한 강봉(14)이 격자 형태로 구비된 것을 특징으로 하는 안전한 서식 환경이 구비된 어류 서식처.어류의 출입이 가능하도록 일측에 출입공간(11)이 형성된 육면체 형상의 철망 하우징(10)과;상기 철망 하우징(10) 상부에 안착 되는 다수의 조경석(20)과;상기 철망 하우징(10)과 조경석(20) 사이에 배치되어 식물의 성장이 이루어지는 식생매트(30);를 포함하되,상기 철망 하우징(10)의 내부 바닥면 일측에는 산란환경 조성을 위한 맥반석(15)을 구성하되, 상기 맥반석(15)의 유동을 방지하기 위한 유동방지벽(16)이 일측에 구비되고, 상기 맥반석(15)에는 일정 점성을 유지하는 코팅층(15a)이 형성되며, 상기 코팅층(15a)은 코코넛 활성탄, 굴패각 분말, 실리콘, 폴리글리콜, 이산화티탄, 클로브 오일, 벤토나이트 분말, 나노은의 혼합 조성을 이루는 것을 특징으로 하는 어류 서식처.어류의 출입이 가능하도록 일측에 출입공간(11)이 형성된 육면체 형상의 철망 하우징(10)과;상기 철망 하우징(10) 상부에 안착 되는 다수의 조경석(20)과;상기 철망 하우징(10)과 조경석(20) 사이에 배치되어 식물의 성장이 이루어지는 식생매트(30);를 포함하되,상기 철망 하우징(10) 내부에는 조경석(20)의 하중을 탄성 지지하기 위한 탄성스프링(17)이 구성되고, 상기 탄성스프링(17)의 상부와 하부에는 각각 안정적인 지지력 유지를 위한 지지플레이트(18)가 연결 구성된 것을 특징으로 하는 어류 서식처.청구항1 또는 청구항3 또는 청구항4 또는 청구항5의 어류 서식처를 설치함에 있어서,조립형 구조를 이루는 철망 하우징(10)의 상부에 식생매트(30)와 조경석(20)을 순차적으로 안착시킨 후, 식생매트(30)에 식물을 식재하여 시공이 이루어짐을 특징으로 하는 어류 서식처 시공방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

241/1059 Row 241: application_number: 1020190100847, combined_string: invention_title: 어업도구 상태정보 제공 시스템 및 그 제어방법. abstract: 본 발명은 원격 어구 모니터링 시스템에 관한 것이며, 구체적으로 개별 어구의 위치 및 상태정보를 모니터링할 수 있는 원격 어구 모니터링 시스템에 관한 것이다. 특히 수중에 설치된 어구의 상태정보까지 감시하는 기술을 제공한다.구성은 다음과 같다.수면아래에 설치되는 어구(40)의 길이방향 상하단에 서로 일정간격 이격시켜 설치한 복수의 기울기센서(50)와,상기 복수의 기울기센서(50)와 유선으로 통신되도록 연결하여 수면에 떠 있는 부표(51)에 설치하는 무선통신부(52)를 포함한 상태에서, 바다에 어구(40) 투척으로 수면아래로 안착된 어구의 기울기가 기 설정된 기울기 범위에 있는 경우 어구(40)에 어류가 유입(포획)될 수 있는 상태에 있는 것으로 판단하고 무선통신부(52)를 통해 관리자측에 어구상태를 송신하고,수중에 설치한 어구(40)의 기울기가 기 설정된 기울기 범위를 벗어나는 경우 어구(40)가 뒤죽박죽되어 어류를 포획할 수 없는 것으로 판단하고 무선통신부(52)를 통해 관리자측에 어구상태를 송신하는 구성이다. claims: 수면아래에 설치되는 어구(40)의 길이방향 상하단에 서로 일정간격 이격시켜 설치한 복수의 기울기센서(50)와,상기 복수의 기울기센서(50)와 유선으로 통신되도록 연결하여 수면에 떠 있는 부표(51)에 설치하는 무선통신부(52)를 포함한 상태에서, 바다에 어구(40) 투척으로 수면아래로 안착된 어구의 기울기가 기 설정된 기울기 범위에 있는 경우 어구(40)에 어류가 유입(포획)될 수 있는 상태에 있는 것으로 판단하고 무선통신부(52)를 통해 관리자측에 어구상태를 송신하고,수중에 설치한 어구(40)의 기울기가 기 설정된 기울기 범위를 벗어나는 경우 어구(40)가 뒤죽박죽되어 어류를 포획할 수 없는 것으로 판단하고 무선통신부(52)를 통해 관리자측에 어구상태를 송신하는 구성을 특징으로 하는 어업도구 상태정보 제공 시스템 및 그 제어방법., Ltext: 어업, prediction: 어업
242/1059 Row 242: application_number: 1020190099346, combined_string: invention_title: 어로용 통발 abstract: 본 발명은 어로용 통발에 관한 것으로서, 그 목적은 유인구의 출구 또는 포획구의 포획부가 탄성력이 아닌 어류의 추진력에 의해 개방되고, 자중에 의해 닫혀지도록 함으로서, 출구 또는 포획부를 헐거워짐이 전혀 발생됨이 개폐될 수 있도록 할 수 었어 반영구적으로 통발의 유효수명을 연장될 수 있어 어로단가를 현저히 낮출 수 있을 뿐만 아니라 어획량도 크게 증대시킬 수 있도록 하는 것이며, 그 구성은 상, 하부링의 사이에 등간격으로 다수의 지지바가 연결된 통발 몸체와, 상기 통발 몸체의 외부를 그물망이 감사게 설치되되, 상기 그물망의 상부에 개폐가능한 배출구가 형성되고, 입구가 넓고 출구가 좁게 형성된 사각깔대기 형상의 망체로서 상기 그물망의 측면에 형성된 개방부에 결합 설치된 유인구로 구성된 어로용 통발에 있어서, 상기 유인구는 출구의 상단부 및 하단부에 각각 회동가능하게 힌지결합되고, 출구를 개폐하는 2개의 차단부재를 구비한 것을 특징으로 한다. claims: 상, 하부링의 사이에 등간격으로 다수의 지지바가 연결된 통발 몸체와, 상기 통발 몸체의 외부를 그물망이 감사게 설치되되, 상기 그물망의 상부에 개폐가능한 배출구가 형성되고, 입구가 넓고 출구가 좁게 형성된 사각깔대기 형상의 망체로서 상기 그물망의 측면에 형성된 개방부에 결합 설치된 유인구로 구성된 어로용 통발에 있어서,상기 유인구(10)는,출구(10a)의 상단부 및 하단부에 각각 회동가능하게 힌지결합되고, 출구(10b)를 개폐하는 2개의 탈출방지 차단부재(20)를 구비한 것을 특징으로 하는 어로용 통발., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

243/1059 Row 243: application_number: 1020190099382, combined_string: invention_title: 어로용 통발의 제조방법 abstract: 본 발명은 어로용 통발의 제조방법에 관한 것으로서, 그 목적은 액상 코팅재과 코팅틀을 사용하여 그물망을 통발본체상에 견고하게 장착시키는 동시에 그물망을 확실하게 보호할 수 있으면서도 작업생산성을 현저히 향상시킬 수 있도록 하는 것이며, 그 구성은 상부링 및 하부링를 각각 가로지르도록 상부링 및 하부링의 내측에 가로대를 설치하고, 가로대가 설치된 상부링 및 하부링 사이에 다수개의 지지바를 설치하여 통발 프레임인 통발본체를 제작하는 통발본체 제작단계와; 상기 통발본체 제작단계를 통해 완성된 통발본체의 외측에 그물망을 덮어 감싼 미완성 통발을 제작하는 그물망 설치단계와; 코팅액이 채워진 코팅틀 내에 상기 그물망 설치단계를 통해 제작된 미완성 통발의 하부링 및 하부링과 접하고 있는 그물망 부분까지 함께 완전히 잠기도록 미완성 통발을 코팅틀 상에 배치시키고, 코팅액이 완전히 경화되어 코팅체가 하부링의 외측을 따라 형성되도록 하는 하부 코팅체 형성단계와; 상기 하부코팅체 형성단계가 완료되면, 코팅액이 채워진 코팅틀 내에 상기 그물망 설치단계를 통해 제작된 미완성 통발의 상부링 및 상부링과 접하고 있는 그물망 부분까지 함께 완전히 잠기도록 미완성 통발을 코팅틀 상에 배치시키고, 코팅액이 완전히 경화되어 코팅체가 상부링의 외측을 따라 형성되도록 하는 상부 코팅체 형성단계를 포함하는 것을 특징으로 한다. claims: 상, 하부링의 사이에 등간격으로 다수의 지지바가 설치된 통발 몸체와, 상기 통발 몸체의 외부를 그물망이 감싸게 설치되되, 상기 그물망의 상부에 개폐가능한 배출구가 형성되고, 입구가 넓고 출구가 좁게 형성된 사각깔대기 형상의 망체로서 상기 그물망의 측면에 형성된 개방부에 결합 설치된 유인구로 구성되고, 내측에 미끼를 놓은 상태로 물속에 배치하여 미끼에 의해 유인된 어류를 포획하는 어로용 통발을 제조하기 위한 어로용 통발의 제조방법에 있어서,상기 제조방법은,상부링(21) 및 하부링(22)를 각각 가로지르도록 상부링(21) 및 하부링(22)의 내측에 가로대(21a)(22a)를 설치하고, 가로대(21a)(22a)가 설치된 상부링(21) 및 하부링(22) 사이에 다수개의 지지바(23)를 설치하여 통발 프레임인 통발본체(20)를 제작하는 통발본체 제작단계(S100)와;상기 통발본체 제작단계(S100)를 통해 완성된 통발본체(20)의 외측에 그물망(30)을 덮어 감싼 미완성 통발(10a)을 제작하는 그물망 설치단계(S200)와;코팅액이 채워진 코팅틀 내에 상기 그물망 설치단계(S200)를 통해 제작된 미완성 통발(10a)의 하부링(22) 및 하부링(22)과 접하고 있는 그물망 부분까지 함께 완전히 잠기도록 미완성 통발(10)을 코팅틀 상에 배치시키고, 코팅액이 완전히 경화되어 코팅체(40)가 하부링(22)의 외측을 따라 형성되도록 하는 하부 코팅체 형성단계(S300)와;상기 하부코팅체 형성단계(S300)가 완료되면, 코팅액이 채워진 코팅틀 내에 상기 그물망 설치단계(S100)를 통해 제작된 미완성 통발(10a)의 상부링(21) 및 상부링(21)과 접하고 있는 그물망 부분까지 함께 완전히 잠기도록 미완성 통발(10)을 코팅틀 상에 배치시키고, 코팅액이 완전히 경화되어 코팅체(41)가 상부링(21)의 외측을 따라 형성되도록 하는 상부 코팅체 형성단계(S400)를 포함하는 것을 특징으로 하는 어로용 통발의 제조방법., Ltext: 어업, prediction: 어업
244/1059 Row 244: application_number: 1020190095341, combined_string: invention_title: 외해 수중 가두리 장치 abstract: 본 발명과 관련된 외해 수중 가두리 장치는, 수중에 설치되는 그물의 상부 테두리를 형성하며, 부력을 가질 수 있게 형성된, 상부림; 상기 그물의 하부 테두리를 형성하는 하부림; 및 상기 하부림에 연결되는 복수의 무게추를 포함하고, 상기 상부림은, 고정된 부력을 제공할 수 있도록 공기가 채워져 밀봉된 제1림; 상기 제1림과 동심 형태로 배치되며, 가변 부력을 제공하는, 제2림; 상기 제2림의 일측에 설치되며, 공기가 상기 제2림의 내부로 유출입될 수 있게 설치되는 공기 연결부; 및 상기 제2림의 다른 일측에 설치되며, 상기 공기 연결부를 통하여 공기가 상기 제2림으로 유입될 때 내부의 해수가 유출되도록 하고, 상기 공기 연결부를 통하여 공기가 상기 제2림으로부터 유출될 때 해수가 유입되도록 하는, 해수 연결부를 포함하고, 상기 해수 연결부는 상기 제2림으로부터 상기 하부림으로 연장된 형태로 형성될 수 있다. claims: 수중에 설치되는 그물의 상부 테두리를 형성하며, 부력을 가질 수 있게 형성된, 상부림;상기 그물의 하부 테두리를 형성하는 하부림; 및상기 하부림에 연결되는 복수의 무게추를 포함하고,상기 상부림은,고정된 부력을 제공할 수 있도록 공기가 채워져 밀봉된 제1림;상기 제1림과 동심 형태로 배치되며, 가변 부력을 제공하는, 제2림;상기 제2림의 일측에 설치되며, 공기가 상기 제2림의 내부로 유출입될 수 있게 설치되는 공기 연결부; 및상기 제2림의 다른 일측에 설치되며, 상기 공기 연결부를 통하여 공기가 상기 제2림으로 유입될 때 내부의 해수가 유출되도록 하고, 상기 공기 연결부를 통하여 공기가 상기 제2림으로부터 유출될 때 해수가 유입되도록 하는, 해수 연결부를 포함하고,상기 해수 연결부는 상기 제2림으로부터 상기 하부림으로 연장된 형태로 형성되며,상기 해수 연결부의 단부는 상기 하부림으로 연장되어 상기 하부림에 고정부재에 의하여 고정된 형태로 설치되고,상기 상부림의 상기 해수 연결부가 위치된 쪽에 보조 무게추가 설치되며,상기 상부림의 상기 공기 연결부가 위치된 쪽에 보조 부력체가 설치된, 외해 수중 가두리 장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

245/1059 Row 245: application_number: 1020190080025, combined_string: invention_title: 꽁치 부산물을 이용한 갈치 낚시용 인공미끼 및 이의 제조방법 abstract: 본 발명은 꽁치 부산물을 이용한 갈치 낚시용 인공미끼 및 이의 제조방법에 관한 것으로, 본 발명의 갈치 낚시용 인공미끼는 꽁치를 처리하는 과정에서 발생되는 부산물을 활용하여 인공미끼를 제조함으로써 꽁치 특유의 향과 집어제 및 형광색소로 인해 갈치를 시각적 및 후각적으로 유인하여 갈치 집어능력을 향상시키는 효과가 있다. claims: 꽁치 부산물 100 중량부;젤라틴 60 내지 70중량부;집어제 1.5 내지 2.5 중량부; 및비타민 B2 5 내지 15 중량부;를 포함하며,15,000 내지 30,000 gf의 경도를 갖는, 갈치 낚시용 인공미끼.꽁치 부산물을 분쇄하고, 물과 혼합하여 가열 후 꽁치 부산물 건더기와 꽁치 부산물 추출액을 분리하는 단계(단계 1);상기 단계 1의 꽁치 부산물 추출액에 젤라틴을 혼합하고 젤라틴을 녹이는 단계(단계 2); 및상기 단계 2의 혼합액에 상기 단계 1의 꽁치 건더기, 집어제 및 비타민 B2를 첨가하고 틀에 넣어 굳히는 단계(단계 3);를 포함하며,상기 꽁치 부산물 100 중량부 기준 젤라틴은 60 내지 70중량부, 집어제는 1.5 내지 2.5 중량부, 비타민 B2를 5 내지 15 중량부를 사용하고, 15,000 내지 30,000 gf의 경도를 갖도록 하는 것인, 갈치 낚시용 인공미끼의 제조방법., Ltext: 어업, prediction: 어업
246/1059 Row 246: application_number: 1020210016858, combined_string: invention_title: 인공어초단지 및 해조 바다목장 모니터링 방법 및 장치 abstract: 해저의 촬영 영역을 촬영하는 카메라; 상기 카메라 하부에 설치되어 360도방향으로 설정 시간에 따라 일정 각도로 회전 하는 타임랩스 회전부; 상기 회전부의 하부에는 카메라와 타임랩스 회전부를 지지하는 베이스부가 설치되며; 상기 카메라, 타임랩스 회전부, 베이스부는 방수케이스 내부에 내장되며; 상기 방수케이스 내부에는 카메라의 촬영과 타임랩스 회전부의 구동을 설정 및 제어하는 제어부가 설치되며;상기 방수케이스 외측 하부면에는 고정장치 체결부가 형성되어 고정장치를 매개로 설치하고자 하는 해저 지역에 고정되어 이루어지는 인공어초단지 및 해조장 모니터링장치를 제공함으로써, 시간에 따라 360도 평면상을 포함하는 영상촬영이 가능하여 조식동물(성게류, 고둥류)구제와 같은 조성지 환경개선과 인공어초단지나 해중림 조성지의 조성 후 사후 모니터링이 가능하여 보다 효율적인 관리가 가능한 효과가 있고 해저에 설치되는 파이프라인, 해저 배수관, 돌핀 구조물등의 해저구조물의 모니터링까지 가능한 효과가 있다. claims: 수중 영역을 촬영하는 카메라; 상기 카메라 하부에 설치되어 360도방향으로 설정 시간에 따라 일정 각도 만큼 회전하는 타임랩스 회전부; 상기 회전부의 하부에는 카메라와 타임랩스 회전부를 지지하는 베이스부가 설치되며; 상기 타임랩스 회전부의 상부에는 카메라를 고정하는 고정홀더가 형성되고, 카메라의 촬영과 타임랩스 회전부의 구동을 설정, 제어하는 제어부로 이루어지고,상기 카메라와 타임랩스 회전부 및 베이스부를 내장하여 둘러싸는 방수케이스로 이루어지며, 상기 방수케이스의 내측 투명부에는 카메라의 초점고정 및 거리측정용 초점판(450) 격자가 인쇄되어 이루어지며, 방수케이스 외측 하부면에는 고정장치 체결부가 형성되어 수중의 일정 면에 고정되어 이루어지는 것을 특징으로 하는 인공어초단지 및 해조 바다목장 모니터링 장치청구항 1의 인공어초단지 및 해조 바다목장 모니터링 장치를 설정된 수역에 고정장치를 이용하여 고정 및 설치하고, 일정기간 모니터링한 후, 방수케이스와 고정장치를 분리하여 회수하고 수집된 데이터 영상을 분석하는 단계로 이루어진 것을 특징으로 하는 인공어초단지 및 해조 바다목장 모니터링 방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

247/1059 Row 247: application_number: 1020210014213, combined_string: invention_title: 어류 양식장용 사료공급시스템 및 이를 이용한 사료공급방법 abstract: 본 발명은 어류 양식장용 사료공급시스템 및 이를 이용한 사료공급방법에 관한 것으로, 보다 상세하게는 요구하는 분사방향으로 사료분사수단이 회전될 수 있을 뿐만 아니라, 사료의 분사량이 자동으로 조절될 수 있는 어류 양식장용 사료공급시스템 및 이를 이용한 사료공급방법에 관한 것이다. 본 발명은 다음과 같은 효과를 발휘한다.즉, 본 발명에 따르면, 육상의 양식장이나 해상의 가두리 양식장과 같이 제한된 공간에서도 그 설치 및 운용이 편리하도록 소형으로 제작이 가능하고, 하나의 사료공급장치로 여러 개의 양식수조나 가두리그물에 대한 선택적 자동급이가 가능하며, 필요시 여러 대의 사료공급장치를 서로 연결하여 일괄 제어토록 할 수도 있는 등, 양식장의 정량토출식 급이관리와 현장제어 및 원격제어에 의한 급이작업의 자동화 측면에 최적화된 시스템을 제공하는 효과가 있으며, 보다 더 나아가서는 사료공급량의 정확한 측정과 체계적인 데이터 관리 및 이를 기초로 한 피드백 제어를 통하여 급이작업의 편의성과 능률성을 극대화시킴으로서, 양식업자들의 수익 향상과 양식산업의 대외경쟁력 확보 측면에도 크게 이바지할 수 있는 등의 매우 유용한 효과가 있다. claims: 수조(10)에 사료를 공급하는 사료공급부재(100);상기 사료공급부재(100)에 의해 수조(10)에 사료가 공급될 때 물고기가 사료를 섭취하는 과정에서 발생되는 수면의 출렁거림을 촬영하는 영상촬영수단(200);상기 영상촬영수단(200)에서 촬영된 영상에서 수면의 출렁거림의 정도를 분석하여, 사료공급부재(100)에서 공급될 사료의 목표량을 수치화하는 연산부(300);상기 연산부(300)에서 수치화된 목표량에 부합되도록 사료공급부재(100)를 제어하여 사료의 공급량을 조절하는 제어부(400);를 포함하고,상기 사료공급부재(100)는사료가 저장되는 사료저장통(110)과,상기 사료저장통(110)의 하부에 형성되되, 배출제어부(410)에 의해 제어되어 사료저장통(110)에서 배출되는 사료의 양이 조절되는 배출조절수단(120)과,상기 배출조절수단(120)의 하부에 형성되어, 배출조절수단(120)에서 이동된 사료를 수조(10)에 분사하는 사료분사수단(130)과,상기 사료분사수단(130)의 하부에 형성되어, 사료분사수단(130)을 회전시키되, 회전제어부(420)에 의해 회전속도 및 회전방향이 제어되는 회전수단(140)을 포함하고,상기 영상촬영수단(200)은배출조절수단(120)의 일측에 형성되되, 사료분사수단(130)의 출구를 향하여 형성되는 것을 특징으로 하고,상기 제어부(400)는연산부(300)에서 수치화된 목표량을 기준으로 배출조절수단(120)의 사료 배출량을 제어하는 배출제어부(410)와,연산부(300)에서 수치화된 목표량을 기준으로 회전수단(140)의 회전속도 및 회전방향을 제어하는 회전제어부(420)를 포함하는 것을 특징으로 하는어류 양식장용 사료공급시스템.제1항 내지 제3항 중 어느 한 항의 어류 양식장용 사료공급시스템을 이용하여 사료를 공급하는 방법에 있어서,수조(10)에 소정량의 사료를 공급하는 단계(S100);상기 공급된 사료를 물고기가 섭취하는 과정에서 발생되는 수면의 출렁거림을 촬영하는 단계(S200);상기 촬영된 영상에서 수면의 출렁거림의 정도를 분석하여, 사료공급부재(100)에서 공급될 사료의 목표량을 수치화하는 단계(S300);상기 수치화된 목표량에 부합되도록 사료공급부재(100)를 제어하여, 사료의 공급량을 조절하면서 수조(10)에 사료를 공급하는 단계(S400);를 포함하는 것을 특징으로 하는어류 양식장용 사료공급시스템을 이용한 사료공급방법., Ltext: 어업, prediction: 어업
248/1059 Row 248: application_number: 1020200106674, combined_string: invention_title: 순환 여과식 새우양식장 abstract: 본 발명은 양식생물이 입식되어 사육되는 양식수조가 하나 이상 설치되고; 상기 양식수조의 사육수가 배수되어 저장되는 집수조; 상기 집수조에 저장된 사육수가 이동되어 정화되는 정화수조;로 이루어지는 순환 여과식 새우 양식장을 제공함으로써, 정화수조 전단에 설치되는 제1분리부에서 고정상여재부를 매개로 하는 여과 효과가 발휘되고, 후단의 제2분리부에는 전단의 제1분리부에서 탈리된 슬러지 및 미처리된 물질들을 제거하는 효과가 발휘됨으로써 전체적으로 안정적인 정화효과를 확보할 수 있어 양식수조에서 사육수의 즉각적인 배수에도 정화효율이 떨어지지 않고, 기존의 새우 양식장과 같이 사육수 분사장치마다 모터 및 산소공급장치를 여러개 설치하지 않고도 이동라인에 모터부 및 산소공급장치를 설치하여 정화가 완료된 사육수에 산소를 용해시킴과 동시에 수압을 공급할 수 있어 양식장 설치비용을 절감할 수 있는 효과가 있다. claims: 양식생물이 입식되어 사육되는 양식수조가 하나 이상 설치되고; 상기 양식수조의 사육수가 배수되어 저장되는 집수조; 상기 집수조에 저장된 사육수가 이동되어 정화되는 정화수조로 이루어지는 순환 여과식 양식장에 있어서;상기 정화수조는 다각형의 수조바닥을 수조외벽이 둘러싸고 상부는 개구되어 내부에는 저장공간이 형성되며, 상기 저장공간에는 전, 후 방향으로 하나 이상의 격벽으로 분리되어, 정화수조 내부가 하나 이상의 사육수 저장공간으로 형성되고;상기 정화수조 전, 후단 어느 한 측면에는 집수조에 저장된 사육수를 공급하는 배수라인이 설치되고, 상기 배수라인과 최단 거리에 형성되는 저장공간의 순서로 고정상 여과재로 이루어진 제1분리부, 유동상 여과재로 이루어진 제2분리부, 필터판으로 이루어진 제3분리부 및 수집부의 순서로 정화수조가 형성되며; 상기 제1분리부의 상부 개구부에는 전, 후 방향으로 고정로프가 좌, 우방향으로 이격되어 복수개 설치되고, 상기 고정로프에는 하나 이상의 고정상 여재부가 일정간격 이격되어 수직으로 고정되며, 상기 제2분리부에는 망사주머니에 유동상 여과재가 충전되고, 제3분리부에는 필터판이 설치되어 이루어지는 것을 특징으로 하는 순환 여과식 양식장, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

249/1059 Row 249: application_number: 1020200089283, combined_string: invention_title: 분리가 가능한 일체형 관상어부화기 및 치어수조 abstract: 본 발명에 의한 수조의 상부에 부착하여 기포를 이용해 스폰지를 통과하여 부유물을 여과한 물이 부화기로 유입되고 조절밸브로 유입된 물을 조절해 안전하게 알을 부화시키고 부화한 치어는 자연스럽게 치어수조로 이동하며 이동한 치어수조에 바닥의 스펀지를 통해 출수되는 물에 의한 데미지를 없애고 여과기와 부화기, 치어수조를 상황에 맞게 자석을 이용해서 탈착 및 부착 할 수 있게끔 제작하여 알과 치어사육에 있어서 건강함을 유지시킬수 있으며 그동안 수조안에서 사용하던 부화기의 불편함과 위험성을 줄임으로써 사육환경의 개선과 원가절감 및 사육의 편리성등을 얻을수 있는 효과가 있다. claims: 수조의 상부에서 사용하는 분리가 가능한 일체형 부화기 및 치어사육수조청구항1에 있어서 자석을 이용해서 여과기와 부화기를 붙이는 방식 및 제작법., Ltext: 어업, prediction: 임업
250/1059 Row 250: application_number: 1020200079209, combined_string: invention_title: LED 유도 통발 abstract: 본 발명은 LED 유도 통발에 관한 것으로, 양측으로 링부재가 이격배치된 본체; 상기 본체를 감싸도록 형성되고, 양측에 내측으로 갈수록 좁아지는 유도공이 형성된 메쉬망; 및 상기 본체의 테두리를 따라 상기 메쉬망을 고정시키도록 결합된 발광로프;를 포함한다. 이러한 구성으로, 본체에 발광로프를 결합함으로써, 발광을 통해 어류를 유인하는 것은 물론, 어류를 유인함에 따라 어획량을 증대시킬 수 있는 효과를 얻을 수 있다. claims: 양측으로 링부재가 이격배치된 본체;상기 본체를 감싸도록 형성되고, 양측에 내측으로 갈수록 좁아지는 유도공이 형성된 메쉬망; 및상기 본체의 테두리를 따라 상기 메쉬망을 고정시키도록 결합된 발광로프;를 포함하고,상기 발광로프의 내부에는 길이 방향으로 일측에 구비된 전원부로부터 전원이 공급되는 전원선이 매립되고, 상기 전원선에 일정간격으로 연결된 LED램프가 구비되며,상기 발광로프의 내부에는 상기 LED램프가 유동 가능하도록 유동홈이 형성되어, 외부 충격 시 상기 LED램프가 유동되고,상기 LED램프의 하단에는 상기 LED램프가 양측으로 유동 가능하도록 볼록하게 형성된 볼록편이 형성된 것을 특징으로 하는 LED 유도 통발., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

251/1059 Row 251: application_number: 1020200072721, combined_string: invention_title: 상시 개구부를 갖는 개체굴 양성장치 abstract: 일정크기의 격자망을 갖는 판프레임이 수평으로 상, 하 일정거리 이격되어 설치되고, 수직방향으로 판프레임이 하나 이상 상기 상, 하 판프레임의 가장자리를 둘러싸며 이루어지는 케이스부와; 상기 수직방향으로 설치된 판프레임 어느 한 측면에는 케이스부 내부로 개체굴의 저장과 방출이 가능한 개체굴 상시 개구부가 형성되며; 상기 케이스부는 고정장치를 매개로 상, 하로 하나 이상 적층 결합되어 이루어지는 개체굴 양성장치를 제공함으로써 상시 개구부를 통해 사용자가 보다 개체굴의 출입을 용이하게 하여 선별 및 분리작업 또는 수확 시에 작업시간이 감소될 수 있으며 다단으로 설치된 단일의 양성장치를 분리하지 않고 결합된 상태에서도 개체굴의 저장 및 방출이 가능하여 사용자가 수중에서 작업이 가능한 효과가 있다. claims: 일정크기의 격자망을 갖는 다각형 판프레임이 수평으로 상, 하 일정거리 이격되어 천정면과 바닥면을 형성하고, 상기 천정면과 바닥면의 가장자리를 판프레임이 둘러싸며 연결되어 일정 체적을 갖는 내부 수용공간을 이루는 케이스부; 상기 케이스부를 이루는 판프레임 어느 한 측면에는 개체굴의 투입과 방출이 가능한 개체굴 상시 개구부가 형성되고;상기 개체굴 상시 개구부는 개체굴이 안착되는 바닥면으로부터 일정 길이로 이격된 케이스부 일 측면에 상시 개방된 형태로 이루어지는 것을 특징으로 하는 상시 개구부를 갖는 개체굴 양성장치, Ltext: 어업, prediction: 임업
252/1059 Row 252: application_number: 1020200071698, combined_string: invention_title: 양식수조내 어류의 먹이활동성 측정 장치 및 이를 이용한 먹이 공급 방법 abstract: 본 발명과 관련된 양식수조내 어류의 먹이활동성 측정 장치는, 수면 상에서 부유하며 파동에 따라 흔들릴 수 있게 형성된 함체; 상기 함체 내에 설치되는 센서모듈; 상기 함체를 양식수조 상에 지지시키는 지지부; 상기 센서모듈에 의해 감지된 신호를 전송할 수 있게 형성된 통신모듈; 및 상기 통신모듈을 통하여 수신된 감지신호를 통하여 양식수조 내 어류의 먹이활동 및 양식수조의 상태를 모니터링할 수 있게 형성된 제어부를 포함할 수 있다. claims: 수면 상에 부유하는 함체 내에 지지되는 가속도센서에 의하여 파동을 측정하는 단계;측정된 상기 가속도센서의 신호를 통신모듈에 의하여 제어부에 전송하는 단계;상기 가속도센서의 신호를 기초로 양식수조 내의 어류의 먹이활동의 강도를 산정하는 단계; 및상기 어류의 먹이활동의 강도에 따라 급이장치를 통해 공급되는 먹이를 조절하는 단계를 포함하고,상기 가속도센서의 신호를 기초로 양식수조 내의 어류의 먹이활동의 강도를 산정하는 단계는,재귀필터를 활용하여 데이터 잡음을 제거하는 과정을 포함하며,상기 가속도센서의 신호를 기초로 양식수조 내의 어류의 먹이활동의 강도를 산정하는 단계는,일정 시간간격으로 측정된 3축 방향의 가속도벡터값들을 수신하는 단계;상기 3축 방향의 가속도벡터의 합을 n개(n은 2이상의 자연수)의 참조갯수만큼 취하여 평균을 구하는 단계; 및특정 구간에서 먹이활동 측정 이벤트가 발행하였을 때 상기 특정 구간 이전의 값을 기준값으로 하여 상기 기준값과 실시간 측정되는 이동평균값 사이의 상대오차값을 비율로 환산하여 먹이활동성을 추정하는 단계를 포함하는, 양식수조내 어류의 먹이활동성 측정 장치를 이용한 먹이 공급방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

253/1059 Row 253: application_number: 1020200064056, combined_string: invention_title: 큰징거미새우의 종묘 생육 장치 abstract: 큰징거미새우의 종묘 생육 장치가 소개된다.이를 위해 본 발명은 복수개로 일렬로 배치되고 외부에서 공급되는 해수와 담수가 혼합되는 수조하우징(100); 유생이 입식되고 유생의 먹이생물이 포함되도록 상기 복수개의 수조하우징(100) 내부에 각각 위치하고 그 상방이 개방되며 둘레를 따라 상기 유생과 상기 먹이생물의 크기보다 작은 다수개의 메쉬로 이루어진 케이지(200); 상기 복수개의 수조하우징(100) 내부로 해수공급관(310)과 담수공급관(410)을 통해 각각 해수와 담수와 공급될 수 있도록 상기 복수개의 수조하우징(100)의 일측에 마련된 해수탱크(300)와 담수탱크(400); 상기 복수개의 수조하우징(100) 내부에 설치되어 수조 내의 수질 환경을 센싱하는 센서부; 및 상기 센서부에 의해 센싱된 수조 내의 수질 환경 정보를 입력받아 상기 수조 하우징 내의 물의 온도와 염분을 설정된 온도와 염분으로 유지할 수 있도록 상기 수조 하우징 내부에 위치한 히터와 상기 해수공급관(310)과 상기 담수공급관(410)의 개폐를 제어하는 제어부(600)를 포함한다. claims: 복수개로 일렬로 배치되고 외부에서 공급되는 해수와 담수가 혼합되는 수조하우징;유생이 입식되고 유생의 먹이생물이 포함되도록 상기 복수개의 수조하우징 내부에 각각 위치하고 그 상방이 개방되며 둘레를 따라 상기 유생과 상기 먹이생물의 크기보다 작은 다수개의 메쉬로 이루어진 케이지;상기 복수개의 수조하우징 내부로 해수공급관과 담수공급관을 통해 각각 해수와 담수와 공급될 수 있도록 상기 복수개의 수조하우징의 일측에 마련된 해수탱크와 담수탱크;상기 복수개의 수조하우징 내부에 설치되어 수조 내의 수질 환경을 센싱하는 센서부; 및상기 센서부에 의해 센싱된 수조 내의 수질 환경 정보를 입력받아 상기 수조 하우징 내의 물의 온도와 염분을 설정된 온도와 염분으로 유지할 수 있도록 상기 수조 하우징 내부에 위치한 히터와 상기 해수공급관과 상기 담수공급관의 개폐를 제어하는 제어부를 포함하는, 큰징거미새우의 종묘 생육 장치., Ltext: 어업, prediction: 임업
254/1059 Row 254: application_number: 1020200046137, combined_string: invention_title: 황금색 체색 발현율을 향상시키기 위한 양식 황금넙치의 육종방법 abstract: 본 발명은 황금 넙치 선별을 위해 표본 넙치를 영상 촬영장치를 이용하여 촬영하는 넙치 촬영단계(가); 상기 (가) 단계로 촬영된 표본 넙치 이미지를 소프트웨어 상에서 배경보정 및 어체 이미지의 RGB값과 CMYK값을 분석하는 단계를 포함하는 이미지 보정 및 분석단계(나); 상기 (나)단계로 분석된 CMKY값 중 Y값의 비율이 45.00 이상인 것을 선별하는 넙치 선별 단계(다); 상기 (다)단계로 선별된 넙치 암,수를 교배하는 교배단계(라)로 이루어진 황금넙치 육종방법을 제공함으로써, 세대를 거듭할수록 발현시점이 빨라지고, 발현크기는 작아지며, 최종 발현율은 높아질 뿐만 아니라 상품성이 높은 개체가 늘어나는 육종 황금넙치 개발이 가능하다. claims: 황금색을 갖는 넙치를 수집하여 선별된 GF0세대의 암, 수 황금넙치를 교배하여 발생한 GF1세대 넙치자손 교배단계(A);상기 (A)단계의 GF1세대 넙치자손을 다시 선별하여 교배하는 GF2세대 넙치자손 교배단계(B);상기 (B)단계의 GF2세대 넙치자손을 다시 선별하여 교배하는 GF3세대 넙치자손을 교배단계(C)를 포함하며,상기 어느 하나의 교배단계에서 넙치의 선별은 이미지 촬영장치를 이용하여 넙치의 체표면을 촬영하고, 상기 촬영된 넙치 이미지를 소프트웨어 상에서 보정하여 넙치 이미지의 색채값을 RGB값과 CMYK값으로 분석하고, 분석된 CMKY값 중 Y값의 비율이 43% 이상인 넙치를 선별하는 것을 특징으로 하는 황금넙치 육종방법넙치의 체표면을 이미지 촬영장치로 촬영하고, 상기 촬영된 넙치 이미지를 소프트웨어 상에서 보정하여 넙치 이미지의 색채값을 RGB값과 CMYK값으로 분석하고, 상기 분석된 CMKY값 중, Y값의 비율이 43% 이상인 넙치를 선별하여 상기 선별된 넙치 암, 수를 교배하는 것을 특징으로 하는 황금넙치 육종방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

255/1059 Row 255: application_number: 1020200022623, combined_string: invention_title: 어미 해삼 육상관리를 통한 해삼 인공종묘의 조기생산방법 abstract: 본 발명은 모삼의 사육수온을 12주간 8℃ 까지 낮추었다가 14주간 18℃ 까지 올려 관리하는 단계(가), (가)단계의 모삼을 수온자극, 표면자극, 건조자극을 통해산란자극으로 산란과 방정시키는 단계(나), (나)단계에서 얻은 수정란을 수조에서 발생시키는 단계(다), (다)단계에서 발생된 치삼이 0.5 g으로 성장할 때까지 파판에서 사육하는 단계(라), 및 (라)단계에서 치삼이 0.5 g으로 성장하면 치삼을 특수망지에서 사육하는 단계(마)로 이루어진 어미 해삼 육상관리를 통한 조기생산 및 생산시기 조절방법을 제공함으로써, 우량의 해삼종묘를 안정적으로 확보하고, 해삼 종묘생산이 가능한 기간을 확대할 뿐만 아니라, 해삼의 양식기간을 단축시킬 수 있어 해삼양식 어가의 소득증대에 기여할 수 있다. claims: (가) 육상수조에서 사료를 공급하면서 다년간 관리되는 모삼을 이용한 인공종묘생산은 저온 관리 기간의 사육수온을 자연수온에서 12주간 8℃ 까지 낮추는 단계로 관리하고, (나) 산란유발 전까지 사육수온을 8℃에서 11 내지 12주간 사육수온 17.5℃ 내지 18℃로 단계별로 승온하여 산란유도까지 18℃로 유지하는 단계로 관리하며, (다) 상기 (나)단계의 관리되는 모삼을 산란자극으로 산란과 방정시켜 얻은 수정란을 사육수조에서 발생시키며, (라) 상기 (다)단계에서 발생된 치삼이 0.5g으로 성장할 때까지는 육상수조의 해삼 양식장치에서 사육시키고, 치삼이 0.5g으로 성장하면 망사를 여러겹 묶어서 형성한 특수망지로 옮겨서 사육하는 단계로 이루어지며, 상기 해삼 양식장치는 해삼이 부착하여 성장하는 복수개의 파판이 바닥면과 수직하게 형성될 수 있도록 하는 상부 파판 홀더부의 하부에 양식장 바닥면과 수평하게 하나 이상의 파판이 수납될 수 있도록 한 수용부를 갖는 하부 파판 홀더부가 상기 상부 파판홀더부와 일체로 결합되어 이루어지며; 상기 상부 파판 홀더부는 가로 및 세로 부재가 연결되어 상부가 개구된 사각틀 형상의 상부면과 상부면을 이루는 가로 및 세로 부재와 연결되는 일정 길이의 수직부재가 하부 파판 홀더부와 일체로 결합되어 상광하협의 내부 공간부를 갖는 구조를 이루며, 상기 상부 파판 홀더부의 좌측 및 우측면의 수직부재는 서로 마주하는 방향을 향해 65 내지 75도 사이각으로 경사를 이루며 상광하협의 하향 수렴 구조를 갖고 하부 파판 홀더부의 상부 내측면에 일체로 결합되며 상기 하부 파판 홀더부는 수직부재와 수평부재의 결합으로 직육면체 형상을 이루고, 전면 또는 후면에는 하부 파판이 바닥면과 수평으로 수납될 수 있도록 파판 수용부가 형성되며, 상기 하부 파판 홀더부 하부 모서리에는 받침대가 형성되어 이루어지는 것을 특징으로 하는 어미 해삼 육상관리를 통한 해삼 인공종묘 조기생산방법, Ltext: 어업, prediction: 어업
256/1059 Row 256: application_number: 1020190172634, combined_string: invention_title: 어로용 통발의 미끼통 abstract: 본 발명은 어로용 통발의 미끼통에 관한 것으로서, 그 목적은 별도의 고정로프를 사용하지 않고 미끼통을 통발의 내측 중앙에 통발의 배치상태와 상관 없이 유동 없이 확실하게 위치되도록 간편하게 착탈가능하게 고정설치할 수 있으면서도, 각종 어류 유입기능을 구비하여 충분한 시간(어류를 포획하기 위해 통발을 바닷물에 투척한 후 투척된 통발 내에 어획물을 획득하기 위해 통발을 수거하는 시간 동안) 어류유인효과가 지속적으로 유인되도록 하여 어획량 증대에 기여할 수 있도록 하는 것이며, 그 구성은 내부에 미끼가 채워진 상태로 어로용 통발의 내측에 설치되어 어류를 통발 내로 유인하기 위한 어로용 통발의 미끼통으로서, 상기 미끼통은 내부중공에 미끼가 충전되고, 충전된 미끼를 서서히 외부로 배출시켜 어류를 유지하는 미끼통 본체와; 일정 높이를 갖는 지지봉으로서, 하단부는 하단부에 통발의 하부 프레임 중 하면을 중심을 가로지르는 종대와 착탈가능하게 체결되고, 상단부에 상기 미끼통 본체가 착탈가능하게 체결되고, 상기 미끼통 본체를 통발의 내측 중앙위치에 고정지지하는 미끼통 본체 지지대로 구성되는 것을 특징으로 한다. claims: 내부에 미끼가 채워진 상태로 어로용 통발의 내측에 설치되어 어류를 통발 내로 유인하기 위한 어로용 통발의 미끼통으로서,상기 미끼통(10)은,내부중공에 미끼(100)가 충전되고, 충전된 미끼를 서서히 외부로 배출시켜 어류를 유인하는 미끼통 본체(20)와;일정 높이를 갖는 지지봉으로서, 하단부는 하단부에 통발(200)의 하부 프레임 중 하면을 중심을 가로지르는 종대(211)와 착탈가능하게 체결되고, 상단부에 상기 미끼통 본체(20)가 착탈가능하게 체결되고, 상기 미끼통 본체(20)를 통발(200)의 내측 중앙위치에 고정지지하는 미끼통 본체 지지대(30)로 구성되는 것을 특징으로 하는 어로용 통발의 미끼통., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

257/1059 Row 257: application_number: 1020190170378, combined_string: invention_title: 공압을 이용한 양식 자동화 장치 abstract: 다각형의 수조바닥을 일정높이의 수조외벽이 둘러싸며 내부 사육공간과 상부 개구부가 형성되는 양식수조; 상기 수조바닥에는 사육수 및 양식 슬러지가 배수될 수 있는 배수장치가 설치되며; 상기 배수장치와 연결되는 배수관을 매개로 배수된 사육수 및 양식 슬러지가 상기 양식수조의 어느 한 모서리부에 설치되는 수집부로 이동하며; 상기 양식수조에는 자동적으로 먹이공급과 사육수의 pH를 조절할 수 있는 공압식 자동사료 공급장치 및 공압식 자동 pH조절장치, 바이오플락 수질 조절에 필요한 미생물, 배양액, 수질조절제 자동공급장치, 자동환수장치중에서 선택되는 하나 이상의 장치가 설치되며; 상기 수집부에 저장된 바이오플락 사육수 및 양식 슬러지는 수처리시스템 이동관을 통해 수처리시스템으로 이동하여 정화 및 슬러지가 제거되며; 상기 수처리시스템에는 인라인 UV살균시스템이 장착된 재공급관이 설치되어 미생물 밀도가 조절된 사육수가 상기 양식수조로 재공급되도록 이루어진 공압식 자동화 양식장을 제공함으로써, 양식장 운영비용을 줄일 수 있으면서 동시에 자동적으로 양식장 관리를 할 수 있는 효과가 있다. claims: 다각형의 수조바닥을 일정높이의 수조외벽이 둘러싸며 내부 사육공간과 상부 개구부가 형성되는 양식수조; 상기 수조바닥에는 사육수 및 양식 슬러지가 배수될 수 있는 배수장치가 설치되며; 상기 배수장치와 연결되는 배수관을 매개로 배수된 사육수 및 양식 슬러지가 상기 양식수조에 설치된 수집부로 이동하며; 상기 양식수조에는 하나의 공압 라인에서 분지된 하나 이상의 공압 자동제어장치가 설치되며;상기 수집부에 저장된 바이오플락 사육수 및 양식 슬러지는 수처리시스템 이동관을 통해 수처리시스템으로 이동하여 정화 및 슬러지가 제거되며; 상기 수처리시스템에는 인라인 UV살균시스템이 장착된 재공급관이 설치되어 미생물 밀도가 조절된 사육수가 상기 양식수조로 재공급되도록 이루어진 것을 특징으로 하는 공압을 이용한 양식 자동화 장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

258/1059 Row 258: application_number: 1020190170477, combined_string: invention_title: 자동 어류 계수 시스템 abstract: 본 발명은 자동 어류 계수 시스템에 관한 것이다. 본 발명은, CMOS 카메라(110) 및 적외선 카메라(120)로 이루어진 카메라 모듈(100), 적어도 하나 이상의 카메라 모듈(100)과 유/무선 통신 라인으로 신호 및 데이터 송수신을 수행하는 SBC(Single Board Computer)(200), 네크워크(300), 자동 계수 서버(400)를 포함하는 자동 어류 계수 시스템(1)에 있어서, 카메라 모듈(100)은, CMOS 카메라(110)를 통해 어도의 미리 설정된 낮 시간동안의 영상 정보를 획득하고 적외선 카메라(120)를 통해 어도의 미리 설정된 저녁시간동안의 영상 정보를 획득하여 네트워크(200)를 통해 SBC(200)로 제공하며, SBC(200)는, 미리 설정된 어도에 설치되어 설치된 어도를 지나가는 물체에 대해서 적어도 하나 이상의 카메라 모듈(100)을 통해 촬영되는 영상 정보에서 인식을 수행하고, 물체가 인식된 영상 정보를 네트워크(300)를 통해 자동 계수 서버(400)로 전송하여 저장하도록 할 뿐만 아니라, 영상 정보에서 감시하는 대상 어종 정보에 해당하는 인식을 수행하고, 인식된 대상 어종에 대한 마킹을 설정하고, 설정된 마킹 ID를 저장부(240) 상에 저장하고 개체수에 대한 추적을 수행하는 것을 특징으로 할 수 있다. 이에 의해, 인공지능 학습과 분류를 통해 필요한 자료를 수집하고 분류하여 수집한 데이터를 통해 어떤 결과를 얻을 것인지를 예측할 수 있으므로, 영상 정보의 수집을 통해 충분한 양의 데이터를 확보하고, 수집한 데이터에서 관심 있는 영역을 자동 마킹을 통해 얻고자하는 어종의 갯수를 포함하는 계수 결과를 정확하게 도출가능한 효과를 제공할 수 있다. claims: CMOS 카메라(110) 및 적외선 카메라(120)로 이루어진 카메라 모듈(100); 적어도 하나 이상의 카메라 모듈(100)과 유선 및 무선 통신 라인으로 신호 및 데이터 송수신을 수행하는 SBC(Single Board Computer)(200); 네크워크(300); 복수의 관리자 단말(500); 그리고 SBC(200)를 통해 수집된 영상 정보를 빅데이터 기반으로 저장할 뿐만 아니라 네트워크(300)를 통해 액세스하는 관리자 단말(500)에 대한 인증 과정을 통해 관리자 단말(500)에게 제공하는 자동 계수 서버(400); 를 포함하는 자동 어류 계수 시스템(1)에 있어서, 카메라 모듈(100)은, CMOS 카메라(110)를 통해 어도의 미리 설정된 낮 시간동안의 영상 정보를 획득하고 적외선 카메라(120)를 통해 어도의 미리 설정된 저녁시간동안의 영상 정보를 획득하여 네트워크(200)를 통해 SBC(200)로 제공하며, SBC(200)는,I/O 인터페이스(210); 송수신부(230); 저장부(240); 경고 출력부(250); 외에, 미리 설정된 어도에 설치되어 설치된 어도를 지나가는 물체에 대해서 적어도 하나 이상의 카메라 모듈(100)을 통해 촬영되는 영상 정보에서 인식을 수행하고, 물체가 인식된 영상 정보를 네트워크(300)를 통해 자동 계수 서버(400)로 전송하여 저장하도록 할 뿐만 아니라, 영상 정보에서 감시하는 대상 어종 정보에 해당하는 인식을 수행하고, 인식된 대상 어종에 대한 마킹을 설정하고, 설정된 마킹 ID를 저장부(240) 상에 저장하고 개체수에 대한 추적을 수행하는 제어부(220); 를 포함하며, 제어부(220)는,SBC(220)가 관리하는 어도에 설치된 적어도 하나 이상의 카메라모듈(100)의 카메라 식별 ID, 그리고 어도 영역 정보, 감시하는 대상 어종 정보를 포함하는 카메라 수집 단위 정보에 대해서 네트워크(300)를 통해 자동 계수 서버(400) 또는 관리자 단말(500)로부터 수신하도록 송수신부(210)를 제어한 뒤, 저장부(240) 상에 카메라 수집 단위 정보를 저장하고, 카메라 모듈(100)이 설치된 영역에는 조도 센서(100a)가 구비되는 경우 카메라 수집 단위 정보에 실시간으로 카메라모듈(100)로부터 I/O 인터페이스(210)를 통해 수신되는 영상 정보를 미리 설정된 조도 이상의 낮 시간 동안과 미리 설정된 조도 미만의 저녁 시간 동안으로 분류하여 저장부(240) 상에 함께 저장하는 정보수집 모듈(221);영상 정보에서 감시하는 대상 어종 정보에 해당하는 인식을 수행하고, 인식된 대상 어종에 대한 마킹을 설정하고, 설정된 마킹 ID를 저장부(240) 상에 저장하기 위해, 영상 정보에서 대상 어종 정보에 대한 인식시 네트워크(300)를 통해 자동 계수 서버(400)에 대한 요청을 통해 복수의 대상 어종 정보에 대한 치어와 성어에 대해 구분된 낮 시간대 및 밤 시간대의 형상 패턴, 그리고 각 형상 패턴에 대해서 미리 설정된 각도 범위로 기울어진 것, 각 형상 패턴에 대해서 축소 또는 확대된 것, 각 형상 패턴에 대해서 역으로 된 것, 일부 가려진 패턴을 포함하는 형상 패턴과 영상 정보를 비교하여 영상 정보 속의 대상 어종 정보에 대한 판별을 수행하며, 판별된 대상 어종에 대해서 대상 어종 정보, 치어/성어 정보를 포함하는 마킹 ID를 설정한 뒤, 마킹 ID를 메타데이터로 대상 어종 정보 및 치어/성어 정보를 마킹 단위 정보로 저장부(240)에 저장하며, 대상 어종에 대한 패턴 인식시 인공지능 기반의 학습을 통해 정보를 처리하기 위해, 네트워크(300)를 통해 자동 계수 서버(400)로 액세스하여 빅데이터 기반의 학습 정보를 활용하여 대상 어종과 치어 및 성어에 대한 인식을 수행하는 전처리 모듈(222);네트워크(300)를 통해 카메라 수집 단위 정보 및 마킹 단위 정보를 실시간으로 자동 계수 서버(400)로 전송하도록 송수신부(210)를 제어함으로써, 자동 계수 서버(400)에 의해 어도의 연속성에 따른 대상 어종의 증감이 예측될 수 있도록 하되, 자동 계수 서버(400)에 의해 어도의 연속성에 따른 대상 어종의 증감이 예측시 자동 계수 서버(400)가 카메라 수집 단위 정보와 마킹 단위 정보를 각 SBC(200)의 SBC 식별 ID 별로 데이터베이스 상에 저장하고 SBC 식별 ID 간에 미리 설정된 거리 내에 물의 흐름 방향에서 전방 또는 후방에 해당하는 위치 정보를 데이터베이스에서 추출한 뒤, SBC 식별 ID 별로 저장된 마킹 단위 정보에서 대상 어류 별로 수를 계측하고, 계측된 대상 어류에 대해서 전방으로 진입하는 대상 어류의 증감을 다시 계측함으로써, 각 SBC 식별 ID를 중심으로 모든 대상 어류의 증감 정보를 생성하고, 대상 어류의 증감 정보를 기초로 미리 설정된 임계치 이상의 감소 정보가 발생하는 두 개의 SBC(200)의 식별 ID를 추출하고, 추출된 SBC(200)의 식별 ID 중 물의 흐름 방향에서 후순위에 해당하는 SBC(200)의 식별 ID를 추출하도록 하는 인공지능 기반 분류 모듈(223);자동 계수 서버(400)로부터 추출된 두 개의 SBC(200)의 식별 ID에 해당하는 경우 제 1 경고 출력 명령을 수신하고, 후순위에 해당하는 SBC(200)의 식별 ID에 해당하는 경우 제 2 경고 출력 명령을 네트워크(300)를 통해 수신하도록 송수신부(310)를 제어하고, 제 1 경고 출력 명령을 수신함에 따라 경고 출력부(250)를 통해 제 1 경고 신호를 출력하고, 제 2 경고 출력 명령을 수신함에 따라 경고출력부(250)를 통해 제 2 경고 신호를 출력하고, 제 1 경고 신호와 제 2 경고 신호로 서로 구분되는 음향 또는 영상 신호로 출력하며, 경고 신호에 따라 복수로 구비되는 관리자 단말(500) 중 카메라 모듈(100)이 설치된 어구에 대해 근접시 대상 어류에 대한 문제(보에 의해 이동 제한 포함)가 발생함을 인식할 수 있도록 하며, 제 2 경고 신호를 출력하기 전에 SBC(200)가 어도 출구부에 형성된 것인 경우 닫힌 하구로 분석하고, 미리 설정된 임계치 이상의 감소치를 보인 어류 정보에 대한 치어 또는 성어 여부, 그리고 영상 인식된 각 개체의 평균 면적 정보를 생성한 뒤, 네트워크(300)를 통해 위치 기반의 관리자 단말(500)로 전송하는 서비스 제공 모듈(224); 및 네트워크(300)를 통한 관리자 단말(500)에 의한 VR 콘텐츠를 제공 요청에 따라 2차원 영상에 해당하는 영상 정보에 대해서 VR 영상 정보를 생성하고, 생성된 VR 영상 정보를 네트워크(300)를 통해 관리자 단말(500)로 전송함으로써, 관리자 단말(500)와 근거리 무선통신 방식으로 신호 및 데이터 송수신을 수행하는 HMD에 형성된 자이로 센서에 의해 인식된 각 우 시차각 및 좌 시차각에 다른 VR 영상 정보가 출력되도록 하는 VR 영상 제공 모듈(225); 을 포함하며, 관리자 단말(500)은, VR 영상 정보에 포함된 각 마킹 ID, 그리고 카메라 식별 ID를 네트워크(300)를 통해 서비스 제공 모듈(224)에 대한 요청을 통해 수신한 뒤 근거리 무선통신 방식으로 VR 영상 정보와 함께 HMD 상으로 출력하도록 하며, 각 마킹 ID에 해당하는 대상 어류에 대해서 VR 영상 정보 상의 영시차로 미리 설정된 시간 이상 응시가 되는 것으로 HMD로부터 신호를 수신하는 경우, 마킹 ID를 네트워크(300)를 통해 정보수집 모듈(221)로 제공함으로써, 정보수집 모듈(221)에 의해 마킹 ID와 매칭되는 마킹 단위 정보가 추출되어 네트워크(300)를 통해 마킹 단위 정보를 수신하는 경우 마킹 단위 정보에서 대상 어종 정보 및 치어/성어 정보를 추출하여 마킹 ID에 해당하는 인식된 대상 어류의 좌표 정보에 매칭하여 출력하도록 제어하며, 마킹 ID에 해당하는 영상 정보를 제공한 카메라 식별 ID를 네트워크(300)를 통해 정보수집 모듈(221)로 제공함으로써, 정보수집 모듈(221)에 의해 카메라 식별 ID에 해당하는 카메라모듈(100)에 의해 의해 수집된 카메라 수집 단위 정보가 추출되는 경우, 정보수집 모듈(221)로부터 카메라 수집 단위 정보를 네트워크(300)를 통해 수신한 뒤, 카메라 수집 단위 정보에 포함된 카메라 식별 ID, 뿐만 아니라, 어도 영역 정보, 감시하는 대상 어종 정보를 HMD로 출력하도록 제어하며, 관리, Ltext: 어업, prediction: 어업
259/1059 Row 259: application_number: 2020190004777, combined_string: invention_title: 가자미목 어류용 개체 식별표 abstract: 가자미목 어류용 개체 식별표로서, 개체 식별번호가 부여되어 있고 무선 인식이 가능한 전자칩이 내장된 태그; 및 일측은 아가미에 형성된 관통공을 관통하고 타측은 상기 태그에 형성된 관통공을 관통하도록 설치되는 링 타입의 연결부재;를 포함하는 구성을 마련함으로써, 가자미목 어류의 경골조직인 아가미에 천공한 후 부착할 수 있어 횟감으로 사용되는 근육 부분에 전혀 손상을 주지 않고 2차 감염 등의 위험 없이 어류 개체의 이력을 추적할 수 있게 된다. claims: 개체 식별번호가 부여되어 있고 무선 인식이 가능한 전자칩이 내장된 태그; 및일측은 아가미 뚜껑에 형성된 관통공을 관통하고 타측은 상기 태그에 형성된 관통공을 관통하도록 설치되는 링 타입의 연결부재;를 포함하는 것을 특징으로 하는, 가자미목 어류용 개체 식별표., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

260/1059 Row 260: application_number: 1020190150523, combined_string: invention_title: 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초 abstract: 본 발명은 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초에 관한 것이다.더욱 구체적으로는, 어류의 생활환경을 조성해주는 인공어초에 있어서 사각형의 형태를 이루되 내부에 여덟 개의 날개판이 소정의 형상을 가지도록 구성됨으로써, 해양 저면에 안착된 인공어초가 침하되는 것을 방지하고, 조류의 흐름을 결정해서 먹이 활동에 의한 어류의 유집 효과를 가지며, 유체 흐름(오름흐름) 방향과 속도에 변화를 주는 구조를 가짐으로써 어류의 먹이활동의 장을 제공할 수 있도록 구성된것과 내부공간이 연결되어 어류의 이동이 자유롭도록, 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초에 관한 것이다. claims: 사각바 형상을 가지는 프레임(10)이 결합되어 사각형을 이뤄 내부공간(20)이 형성되고, 상기 사각형이 6개의 면을 이뤄 육면체형의 형상을 이뤄, 사각 인공어초를 형성하되,각 면을 이루는 프레임(10)의 일측에서부터는 인공어초의 내부 방향으로 소정의 경사각을 가지면서 연장된 날개판(30)이 총 8개 형성되는, 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초에 있어서,상기 날개판(30)은 인접한 것들 간에 일측이 연결된 구조를 가지되,제1 날개판①의 하방의 프레임 중 일측에서 연장되고, 제2 날개판②은 상기 제1 날개판①에 대하여 개구부가 수직된 방향으로 제1 날개판①에 연결되며,제3 날개판③은 상기 제2 날개판②에 대하여 개구부가 수직된 방향으로 제2 날개판②에 연결됨으로써, 상방의 프레임 중 일측에서 연장되고,제4 날개판④ 역시 제3 날개판③에 대하여 개구부가 수직된 방향으로 연결되며, 제5 날개판⑤은 제4 날개판④에 대하여 개구부가 수직된 방향으로 연결됨에 따라 하방의 프레임 중 일측에서 연장되고,제6 날개판⑥은 제5 날개판⑤에 대하여 개구부가 수직된 방향으로, 제7 날개판⑦은 제6 날개판⑥에 대하여 개구부가 수직된 방향으로 연결되되, 상방의 프레임 중 일측에서 연장되고, 제8 날개판⑧은 상기 제7 날개판⑦에 대하여 개구부가 수직된 방향으로 연결되고, 다른 방향이 상기 제1 날개판①에 대하여 개구부가 수직된 방향으로 연결되는 것을 특징으로 하는, 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초., Ltext: 어업, prediction: 어업
261/1059 Row 261: application_number: 1020190143553, combined_string: invention_title: 양식장 순환수의 분산형 처리장치 abstract: 양식장 순환수의 분산형 처리장치가 개시된다. 개시되는 양식장 순환수의 분산형 처리장치는, 양식장 수조(1); 및 상기 양식장 수조에 대응되게 배치되며, 상기 양식장 수조로부터 물을 유입시켜 상기 양식장 수조로부터의 물에 포함된 부유물질을 기포를 이용하여 부상 분리시켜 제거하고, 부유물질 제거 이후의 처리수를 상기 양식장 수조 내로 배출하는, 부유물질 제거부(110)를 포함하여, 각 양식장 수조 내에서 수질을 안정적으로 유지하면서도 바이러스 등으로 인한 질병의 발생시 양식장 수조 전체에 피해를 줄이고, 고농도의 산소를 용해하여 유기물질을 효과적으로 제거할 뿐만 아니라, 처리장 면적이 줄어 공사비용도 줄고 공간활용도를 높일 수 있다. claims: 양식장 순환수의 분산형 처리장치로서,양식장 수조(1); 및상기 양식장 수조에 대응되게 배치되며, 상기 양식장 수조로부터 물을 유입시켜 상기 양식장 수조로부터의 물에 포함된 부유물질을 기포를 이용하여 부상 분리시켜 제거하고, 부유물질 제거 이후의 처리수를 상기 양식장 수조 내로 배출하는, 부유물질 제거부(110)를 포함하는 것을 특징으로 하는, 양식장 순환수의 분산형 처리장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

262/1059 Row 262: application_number: 1020190137804, combined_string: invention_title: 붉바리 등 어류 치어 선별작업장치 abstract: 본 발명은 붉바리 등 어류 치어 선별작업 장치에 대하여 개시한다. 본 발명의 붉바리 등 어류 치어 선별작업장치는 치어 선별분리작업을 이루는 작업대가 바닥에서 소정의 높이로 형성되고 치어선별을 위한 일정크기의 수조가 구비되는 작업부재와, 상기 작업부재의 수조 상단에 설치되어 선별을 위한 치어가 공급되는 분리하는 선별부재와, 상기 선별부재 상부에 크기별로 분리된 치어와 용수가 공급되는 유도홀이 구비된 가이드대가 설치되며 상기 가이드대의 출구에는 크기별로 분리 선별된 치어가 각각 수집되는 집어함이 구비된 분리부재를 포함하여 이루어져 있어 작업자의 이동이 없고 치어의 크기 선별작업 시 작업자의 자세 또한 허리를 편안한 자세로 하게 되므로 육체적 고통이 없으며, 선별된 치어는 크기별로 자동으로 수집되어 작업인력과 소요 경비가 절감되 이점이 있는 것이다. claims: 치어 선별분리작업을 이루는 작업대가 바닥에서 소정의 높이로 형성되고 치어선별을 위한 일정크기의 수조가 구비되는 작업부재;상기 작업부재의 수조 상단에 설치되어 선별을 위한 치어가 공급되는 분리하는 선별부재;상기 선별부재 상부에 크기별로 분리된 치어와 용수가 공급되는 유도홀이 구비된 가이드대가 설치되며 상기 가이드대의 출구에는 크기별로 분리 선별된 치어가 각각 수집되는 집어함이 구비된 분리부재;를 포함하여 이루어진 붉바리 등 어류 치어 선별작업장치., Ltext: 어업, prediction: 어업
263/1059 Row 263: application_number: 1020190121866, combined_string: invention_title: 어류에 대한 바이러스성 출혈성 패혈증 예방 방법 및 바이러스성 출혈성 패혈증 바이러스에 대한 감염 내성을 갖는 어류의 생산 방법 abstract: 본 발명의 바이러스성 출혈성 패혈증 예방 방법은 넙치에서 발생하는 바이러스성 출혈성 패혈증을 효과적으로 예방할 수 있으므로, 넙치의 양식 산업 등에 유용하게 사용될 수 있다. 또한, 침지를 통해 주사 기반 백신과 유사하게 바이러스성 출혈성 패혈증에 대한 방어 효과를 나타내기 때문에 성어 뿐 아니라 치어에서도 간편하게 바이러스성 출혈성 패혈증을 예방할 수 있고, 이를 통해 바이러스성 출혈성 패혈증 바이러스에 대하여 내병성을 가진 넙치를 생산할 수 있다. claims: 바이러스성 출혈성 패혈증 바이러스(Viral hemorrhagic septicemia virus, VHSV)를 포함하는 17 내지 23℃의 수온의 수조에 어류를 침지하는 단계를 포함하는 어류에 대한 바이러스성 출혈성 패혈증 예방 방법. 다음 단계를 포함하는 바이러스성 출혈성 패혈증 바이러스에 대한 감염 내성을 갖는 어류의 생산 방법:바이러스성 출혈성 패혈증 바이러스(Viral hemorrhagic septicemia virus, VHSV)를 포함하는 17 내지 23℃의 수온의 수조에 어류를 침지하는 단계; 5 내지 25℃의 수온의 수조에서 3주 내지 5주 동안 상기 어류를 사육하여 바이러스성 출혈성 패혈증 바이러스에 대한 면역반응을 유도하는 단계; 및바이러스성 출혈성 패혈증 바이러스 감염 내성을 갖는 어류를 수득하는 단계., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

264/1059 Row 264: application_number: 1020190115427, combined_string: invention_title: 효율적인 공간 활용을 위한 양식장용 다층 수조 시스템 abstract: 본 발명은 양식장용 다층 수조 시스템에 관한 것으로, 넙치, 가자미 등의 편평어를 양식하는 양식장에서 공간을 효율적으로 활용하면서 물고기의 관리와 반입 및 반출이 편리하도록 한 것이다. 이러한 본 발명은, 상하로 이격을 두고 다층 설치된 다수의 베이스 패널을 구비한 본체 프레임; 각 층에 위치한 베이스 패널의 상측에서 전후방향으로 슬라이딩 가능하도록 설치되며 상면이 개방된 사각의 용기 형태로 형성되어 해수를 담을 수 있도록 한 다수의 서랍형 수조; 및 상기 본체 프레임에 설치되어 각 층에 위치한 상기 수조에 해수를 공급할 수 있도록 한 다수의 공급관;을 포함하는 것을 특징으로 한다. claims: 상하로 이격을 두고 다층 설치된 다수의 베이스 패널을 구비한 본체 프레임; 각 층에 위치한 베이스 패널의 상측에서 전후방향으로 슬라이딩 가능하도록 설치되며 상면이 개방된 사각의 용기 형태로 형성되어 해수를 담을 수 있도록 한 다수의 서랍형 수조; 및 상기 본체 프레임에 설치되어 각 층에 위치한 상기 수조에 해수를 공급할 수 있도록 한 다수의 공급관;을 포함하며, 상기 수조의 전면 벽에는 물고기의 반출을 위한 개구부가 형성되고, 상기 개구부를 개폐 가능한 차단판이 더 설치되며, 상기 차단판은 상기 본체 프레임의 탑 플레이트에 설치된 제1전동윈치에 제1와이어로 연결되어 상기 제1전동윈치가 제1와이어를 감아주면 상기 차단판이 상승하면서 상기 수조의 개구부를 개방하고 상기 제1전동윈치가 제1와이어를 풀어주면 상기 차단판이 하강하면서 상기 수조의 개구부를 폐쇄하도록 한 것을 특징으로 하는 양식장용 다층 수조 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

265/1059 Row 265: application_number: 1020190112359, combined_string: invention_title: 수산물 양식 및 태양광 발전 복합단지 abstract: 본 발명은 수산물 양식 및 태양광 발전 복합단지에 관한 것으로서, 수산물 양식을 위한 해수가 수용된 양식장(10)(10')(10)과; 양식장(10)(10')(10)의 전후방에서 작업자가 양식중인 수산물을 수확하기 위한 작업공간을 제공하는 작업존(20)(20')(20)과; 양식장(10)(10')(10)의 상부측을 덮도록 설치되는 것으로서 태양광을 통하여 상기 양식장(10)(10')(10)을 운영하기 위한 전력을 생산하는 복수의 태양광어레이(30)(30')(30);를 포함한다. claims: 수산물 양식을 위한 해수가 수용된 양식장(10)(10')(10);상기 양식장(10)(10')(10)의 전후방에서 작업자가 양식중인 수산물을 수확하기 위한 작업공간을 제공하는 작업존(20)(20')(20); 상기 양식장(10)(10')(10)의 상부측을 덮도록 설치되는 것으로서 태양광을 통하여 상기 양식장(10)(10')(10)을 운영하기 위한 전력을 생산하는 복수의 태양광어레이(30)(30')(30);상기 태양광어레이(30)(30')(30)를 구성하는 태양광모듈에서 출력되는 직류전력을 병합하여 출력하는 다수의 단위접속반(70)(70')(70);상기 단위접속반(70)(70')(70)에서 출력되는 직류전력을 교류전력으로 변환하는 다수의 단위인버터(80)(80')(80); 및 상기 다수의 단위인버터(80)(80')(80)에서 출력되는 전력중, 상기 양식장(10)(10')(10)을 운영하는 과정에서 남은 잉여전력을 한전과 연계된 계통으로 공급하는 계통제어반(90);을 포함하고;상기 계통제어반(90)은, 전방측에 점검을 위한 도어(91a) 및 전장품(P)을 지지하는 다수의 선반(91b)을 가지는 함체(91)와; 상기 함체(91)의 마주보는 4 개의 모서리측에 설치되어 그 함체(91)를 수직 방향으로 지지하는 것으로서, 각각의 내부에 유로(92a)가 형성되고, 마주보는 면에 그 유로(92a)와 연통되는 다수의 통기구멍(92b)이 형성된 프로파일(92)과; 상기 함체(91)의 내부 상부측에 4 개의 프로파일(92)에 지지되는 것으로서 상기 유로(92a)와 연통되게 설치되는 흡배기공간(98)과; 상기 함체(91) 외부에 설치되어 상기 흡배기공간(98)을 흡입압을 형성하는 흡배기팬(99)과; 상기 단위접속반(70)(70')(70)에서 비정상적인 상황이 발생할 때 접속반이상신호(S1)를 발생하는 접속반이상신호발생부(93)와; 상기 단위인버터(80)(80')(80)에서 비정상적인 상황이 발생할 때 인버터이상신호(S2)를 발생하는 인버터이상신호발생부(94)와; 상기 프로파일(92)에 설치되는 것으로서, 상기 전장품(P), 접속반이상신호발생부(93), 인버터이상신호발생부(94)에서 발생되는 아크를 감지하여 아크경고신호(AS)를 발생하는 아크감지부(96);을 포함하고; 상기 프로파일(92)은, 단면이 직각 삼각형을 이루는 것으로서 내부에 상기 유로(92a) 및 상기 통기구멍(92b)이 형성되는 경사면을 가지는 프로파일몸체(92c)와; 상기 경사면에 형성되는 것으로서 상기 아크감지부(96)가 끼어지는 끼움슬릿(92d)과; 상기 경사면의 배면에 형성된 것으로서 끼움슬릿(92d)을 상기 유로(92a) 및 통기공(92b)과 차단하는 슬릿배면(92e)을 포함하고;상기 아크감지부(96)는, 상기 끼움슬릿(92d) 및 슬릿배면(92e) 사이에 끼어지는 기판(96a)과, 상기 기판(96a)에 설치되는 자외선센서(96b)와, 아크발생시 발생되는 특정 자외선 파장 영역을 상기 자외선센서(96b)로 투과시키는 투과필터(96c)와, 상기 자외선센서(96b)에서 감지된 자외선 광량이 설정된 광량값 이상이 될 때 아크경고신호(AS)를 발생하는 아크경고신호발생부(96d)를 포함하는 것을 특징으로 하는 수산물 양식 및 태양광 발전 복합단지., Ltext: 어업, prediction: 어업
266/1059 Row 266: application_number: 2020190003614, combined_string: invention_title: 산호 양식용 지지대 및 이를 포함하는 산호 양식용 수조 abstract: 본 고안은 산호 양식용 수조 및 산호 양식용 지지대를 제공한다. 본 고안은 상부가 개방된 수조와, 상기 수조의 상부에 설치되는 조명과, 상기 수조의 내부공간에 배치되고, 복수개의 플레이트가 각각 서로 다른 높이의 계단식으로 배치되는 산호 지지대, 및 상기 산호 지지대에 설치되는 복수개의 양식용 지그;를 포함하고, 상기 플레이트는 상기 양식용 지그가 삽입되며 복수개로 구비되는 삽입홀, 및 상기 플레이트의 가장자리를 따라 배치되는 돌출벽을 구비한다. claims: 상부가 개방된 수조;상기 수조의 상부에 설치되는 조명;상기 수조의 내부공간에 배치되고, 복수개의 플레이트가 각각 서로 다른 높이의 계단식으로 배치되는 산호 지지대; 및상기 산호 지지대에 설치되는 복수개의 양식용 지그;를 포함하고,상기 플레이트는상기 양식용 지그가 삽입되며 복수개로 구비되는 삽입홀; 및상기 플레이트의 가장자리를 따라 배치되는 돌출벽;을 구비하는, 산호 양식용 수조.제1 지지판;상기 제1 지지판의 후방에 배치되고, 상기 제1 지지판 보다 높게 배치된 제2 지지판;상기 제2 지지판의 후방에 배치되고, 상기 제2 지지판 보다 높게 배치된 제3 지지판;상기 제1 지지판, 상기 제2 지지판 및 상기 제3 지지판에 각각 배치되고, 양식용 지그가 삽입되는 복수개의 삽입홀; 및상기 제1 지지판, 상기 제2 지지판 및 상기 제3 지지판의 가장자리를 따라 기 설정된 높이로 돌출된 돌출벽;을 포함하는, 산호 양식용 지지대., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

267/1059 Row 267: application_number: 1020217007179, combined_string: invention_title: 불임 및 단성 자손을 생성하는 방법 abstract: 본 개시는 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 방법을 제공한다. 상기 방법은 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위해 (i) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물과 (ii) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계를 포함하고, 상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키고, 상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키며, 상기 가임 동형접합인 암컷 어류, 갑각류, 또는 연체동물 및 가임 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물의 가임성은 회복됐다. 또한 본 개시는 친어 그 자체뿐만 아니라, 불임 및 성 결정된 담수 및 해수 생명체를 생성하는 데 사용하기 위한 담수 및 해수 생명체로 친어를 생성하는 방법을 제공한다. claims: 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, 상기 방법은: (i) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 반접합(hemizygous) 돌연변이된 암컷 어류, 갑각류, 또는 연체동물과 (ii) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계; 및유전자형 선발을 통해, 불임 및 성 결정된 어류, 갑각류, 또는 연체동물인 동형접합인 전구체를 선발하는 단계;를 포함하고,상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키며,상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키는 것인, 방법.불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, 상기 방법은: 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위해 (i) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 동형접합(homozygous) 돌연변이된 암컷 어류, 갑각류, 또는 연체동물과 (ii) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계를 포함하고,상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키고,상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키며,상기 가임 동형접합인 암컷 어류, 갑각류, 또는 연체동물 및 가임 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물의 가임성은 회복된 것인, 방법. 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, 상기 방법은: 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위해 (i) 동형접합 돌연변이를 가지고 있는 가임 암컷 어류, 갑각류, 또는 연체동물과 (ii) 동형접합 돌연변이를 가지고 있는 가임 수컷 어류, 갑각류, 또는 연체동믈을 교배시키는 단계를 포함하고,상기 돌연변이는 직접 또는 간접적으로 정자형성을 결손시키거나, 및/또는 직접 난황형성을 결손시키며,상기 가임 암컷 어류, 갑각류, 또는 연체동물 및 가임 수컷 어류, 갑각류, 또는 연체동물의 가임성은 회복된 것인, 방법.불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위한 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물로서, 상기 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물은 적어도 첫 번째 및 두 번째 돌연변이를 가지고, 상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키고, 상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키며, 상기 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물의 가임성은 회복된 것인, 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물.불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위한 동형접합 돌연변이를 가지고 있는 가임 어류, 갑각류, 또는 연체동물로서, 상기 돌연변이는 직접 또는 간접적으로 정자형성을 결손시키거나, 및/또는 직접 난황형성을 결손시키고, 상기 가임 어류, 갑각류, 또는 연체동물의 가임성은 회복된 것인, 가임 어류, 갑각류, 또는 연체동물.불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, 상기 방법은: (i) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 반접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물과 (ii) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계; 유전자형 선발을 통해, 동형접합인 전구체를 선발하는 단계; 및상기 동형접합인 전구체의 가임성을 회복시키는 단계;를 포함하고,상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키며,상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키는 것인, 방법., Ltext: 어업, prediction: 어업
268/1059 Row 268: application_number: 1020190095119, combined_string: invention_title: 풀무치의 인공 부화방법 abstract: 본 발명은 풀무치의 인공 부화방법에 관한 것이다. 본 발명에 따른 풀무치의 인공 부화방법은 풀무치 알을 최적 온도, 광주기, 조도 조건에서 부화시킴에 따라 상기 풀무치 알의 부화율을 현저히 증가시킬 수 있어, 계획적으로 풀무치를 대량 생산 및 출하할 수 있다. claims: (a) 부화온도 30 내지 38℃;(b) 습도 55 내지 80%;(c) 광주기 9L/15D 내지 12L/12D;(d) 조도 3,000 내지 6,000Lux의 조건 하에서 풀무치의 알을 부화시키는 단계; 를 포함하는, 풀무치의 인공 부화방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

269/1059 Row 269: application_number: 1020190089348, combined_string: invention_title: 어류털이장치 abstract: 어류털이장치가 개시된다. 어류털이장치는 그물에 걸린 어류를 터는 어류털이장치에 있어서, 하측이 좌측 회전체의 돌기에 고정되어, 좌측 회전체의 회전에 따라 움직이는 좌측 하부축, 하측이 우측 회전체의 돌기에 고정되어, 우측 회전체의 회전에 따라 움직이는 우측 하부축, 하측이 좌측 하부축의 상측과 힌지결합되고, 좌측 하부축의 움직임에 따라 상하부로 움직이는 좌측 상부축, 하측이 우측 하부축의 상측와 힌지결합되고, 우측 하부축의 움직임에 따라 상하부로 움직이는 우측 상부축, 일측이 좌측 상부축 상부에 고정되고, 타측이 우측 상부축 상부에 고정되며, 그물을 하부에서 받히고, 좌측 상부축 및 우측 상부축의 움직임에 따라 상부로 이동하여 그물을 아래에서 위로 치는 받침 털이대, 메인 프레임부에 고정되어 받침 털이대 및 좌측 하부축 사이에 위치하며, 좌측 상부축이 상하부로 직선 운동하게 가이드 하는 좌측 가이드부, 및 메인 프레임부에 고정되어 받침 털이대 및 우측 하부축 사이에 위치하며, 우측 상부축이 상하부로 직선 운동하게 가이드 하는 우측 가이드부를 포함할 수 있다. claims: 그물에 걸린 어류를 터는 어류털이장치에 있어서,회전력을 제공하는 모터;판형으로 형성된 몸체 및 상기 몸체 일면에서 돌출되어 형성된 돌기를 포함하는 좌측 회전체;판형으로 형성된 몸체 및 상기 몸체 일면에서 돌출되어 형성된 돌기를 포함하는 우측 회전체;상기 모터의 회전력을 전달받아 상기 좌측 회전체 및 상기 우측 회전체를 회전시키는 동력전달부;상기 동력전달부를 지지하는 메인 프레임부;하측이 상기 좌측 회전체의 돌기에 고정되어, 상기 좌측 회전체의 회전에 따라 움직이는 좌측 하부축;하측이 상기 우측 회전체의 돌기에 고정되어, 상기 우측 회전체의 회전에 따라 움직이는 우측 하부축;하측이 상기 좌측 하부축의 상측과 힌지결합되고, 상기 좌측 하부축의 움직임에 따라 상하부로 수직하게 움직이는 좌측 상부축;하측이 상기 우측 하부축의 상측와 힌지결합되고, 상기 우측 하부축의 움직임에 따라 상하부로 수직하게 움직이는 우측 상부축;일측이 상기 좌측 상부축 상부에 고정되고, 타측이 상기 우측 상부축 상부에 고정되며, 상기 그물을 하부에서 받히고, 상기 좌측 상부축 및 상기 우측 상부축의 움직임에 따라 상부로 이동하여 상기 그물을 아래에서 위로 치는 받침 털이대;상기 메인 프레임부에 고정되어 상기 받침 털이대 및 상기 좌측 하부축 사이에 위치하며, 상기 좌측 상부축이 상하부로 직선 운동하게 가이드 하는 좌측 가이드부; 및상기 메인 프레임부에 고정되어 상기 받침 털이대 및 상기 우측 하부축 사이에 위치하며, 상기 우측 상부축이 상하부로 직선 운동하게 가이드 하는 우측 가이드부를 포함하는 것을 특징으로 하는 어류털이장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

270/1059 Row 270: application_number: 1020217005050, combined_string: invention_title: 불임 자손을 생성하는 방법 abstract: 본 개시는 불임 어류,　갑각류,　또는 연체동물을 생성하는 방법을 제공한다.　상기 방법은　(i)　가임 반접합 돌연변이된(fertile hemizygous mutated)　암컷 어류,　갑각류,　또는 연체동물과　(ii)　가임 반접합 돌연변이된 수컷 어류,　갑각류,　또는 연체동물을 교배시키는 단계,　유전자형 선발(genotypic selection)을 통해 동형접합인(homozygous)　암컷 전구체(progenitor)를 선발하는 단계,　불임 어류,　갑각류,　또는 연체동물을 생성하기 위해 상기 동형접합인 암컷 전구체를 교배시키는 단계를 포함한다.　상기 돌연변이는 원시생식세포(PGC)　발달 유전자의 모계영향을 결손시키고,　동형접합인 전구체의 생존율,　성 결정,　가임성,　또는 이들의 조합을 손상하지 않는다.　또한 본 개시는 불임화된 담수 및 해양 생명체들을 생성하는데 사용하기 위한 담수 및 해양 생명체로 친어(broodstock)를 생성하는 방법, 및 상기 친어를 제공한다. claims: 불임 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, (i) 가임 반접합 돌연변이된(fertile hemizygous mutated) 암컷 어류, 갑각류, 또는 연체동물과 (ii) 가임 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배(breeding)시키는 단계; 유전자형 선발(genotypic selection)을 통해 동형접합인(homozygous) 암컷 전구체(progenitor)를 선발하는 단계; 및불임 어류, 갑각류, 또는 연체동물을 생성하기 위해 상기 동형접합인 암컷 전구체를 교배시키는 단계를 포함하고,상기 돌연변이는 원시생식세포(primordial germ cell, PGC) 발달 유전자(development gene)의 모계영향(maternal-effect)을 결손시키며(disrupt), PGC 발달 유전자의 모계영향을 결손시키는 상기 돌연변이는 동형접합인 전구체의 생존율(viability), 성 결정(sex determination), 가임성(fertility), 또는 이들의 조합에 손상을 주지 않는 것인, 방법.불임 어류, 갑각류, 또는 연체동물을 생성하기 위한 가임 동형접합 돌연변이된(fertile homozygous mutated) 암컷 어류, 갑각류, 또는 연체동물로서, 상기 돌연변이는 원시생식세포 발달 유전자의 모계영향을 줄이기 위해 원시생식세포 발달 유전자의 전사 후 조절을 결손시키고,상기 원시생식세포 발달 유전자의 전사 후 조절을 결손시키는 돌연변이는 상기 유전자의 체세포 기능(somatic function)을 손상하지 않는 것인, 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물.불임 어류, 갑각류, 또는 연체동물을 생성하기 위해, 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물을 교배시키는 방법으로서, 상기 방법은 불임 어류, 갑각류, 또는 연체동물을 생성하기 위해, 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물을, 야생형의 수컷 어류, 갑각류, 또는 연체동물, 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물, 또는 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물과 교배시키는 단계를 포함하고,상기 돌연변이는 원시생식세포 발달 유전자의 모계영향을 결손시키며, PGC 발달 유전자의 모계영향을 결손시키는 상기 돌연변이는 동형접합인 전구체의 생존율, 성 결정, 가임성, 또는 이들의 조합에 손상을 주지 않는 것인, 방법.불임 어류, 갑각류, 또는 연체동물을 생성하는 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, (i) 가임 반접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물 암컷과 (ii) 가임 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계; 및유전자형 선발을 통해 동형접합인 암컷 전구체를 선발하는 단계를 포함하고,상기 돌연변이는 원시생식세포 발달 유전자의 모계영향을 결손시키며, PGC 발달 유전자의 모계영향을 결손시키는 상기 돌연변이는 동형접합인 전구체의 생존율, 성 결정, 가임성, 또는 이들의 조합에 손상을 주지 않는 것인, 방법., Ltext: 어업, prediction: 어업
271/1059 Row 271: application_number: 1020190076063, combined_string: invention_title: 큰징거미새우 전용 부화 수조 abstract: 큰징거미새우에게 스트레스를 주지 않고 모패와 치패를 분리할 수 있는 큰징거미새우 전용 부화 수조가 개시된다. 본 발명은 상면이 개방되고, 모패부 및 치패부를 포함하는 본체; 상기 본체의 내측 양측면 중앙부에 설치되고, 상기 모패부 및 상기 치패부를 구획하는 제1칸막이; 상기 치패부의 상면 모서리에 횡방향으로 설치된 집어등; 및 상기 본체의 전단벽에 형성된 모임조;를 포함하는 큰징거미새우 전용 부화 수조를 제공한다. claims: 상면이 개방되고, 모패부 및 치패부를 포함하는 본체;상기 본체의 내측 양측면 중앙부에 설치되고, 상기 모패부 및 상기 치패부를 구획하는 제1칸막이;상기 치패부의 상면 모서리에 횡방향으로 설치된 집어등; 및상기 본체의 전단벽에 형성된 모임조;를 포함하는 큰징거미새우 전용 부화 수조로서,상기 치패부는 하면에 제1배수구가 형성되고, 상기 제1배수구 상면에 차단망이 설치되고,상기 모임조는 상면이 개방되고, 상기 모임조는 하면에 제2배수구, 순환여과구 및 수위조절구가 형성되고, 상기 수위조절구 상면은 수위조절 파이프와 연결되고, 상기 수위조절구 하면은 상기 제1배수구의 하면과 파이프를 통해 연결된 것을 특징으로 하는 큰징거미새우 전용 부화 수조., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

272/1059 Row 272: application_number: 1020190073873, combined_string: invention_title: 부유식 해상구조물을 활용한 어류 양식 설비 abstract: 본 발명은 부유식 선박, 바지선, 해양철구조물과 같이 해상에서 이동이 가능한 해상구조물의 내부에 사료, 해수 및 산소를 공급하며, 배설물, 사료찌꺼기 등과 같은 폐기물을 외부로 배출시킴으로써 항시 청결한 양식 환경이 유지되도록 하고, 특히 양식조에 공급되는 해수의 흡입관의 심도를 조절하여 어류의 양식에 필요한 적절한 양식수의 온도 조정이 가능하며, 해상구조물의 평형수 조절을 통해 양식조 내의 수위 조절이 가능하도록 하는 부유식 해상구조물을 활용한 어류 양식 설비에 관한 것이다. claims: 해상구조물의 내부에 마련되며, 내측으로 치어를 공급하기 위한 치어 공급 파이프를 포함하는 양식조; 및상기 해상구조물의 외측에서 외부의 물을 흡입하여 상기 양식조 내로 물을 공급하며, 상기 해상구조물의 외측면에 마련되는 흡입 펌프, 상기 흡입 펌프와 연결되며 하측 방향으로 연장됨에 따라 상기 해상구조물 외부의 물을 흡입하는 흡입관, 상기 흡입관과 흡입펌프가 연결되며 상기 양식조 내로 물을 배출하는 배출관 및 상기 흡입 펌프를 감싸며 상기 해상구조물 외측의 물이 상기 흡입 펌프에 유입되는 것을 방지하는 밀폐 박스를 포함하는 물 공급부;를 포함하며,상기 양식조의 하측에는 다수의 물 배출용 관통홀이 형성됨에 따라, 상기 해상구조물의 평형수 변화에 의해 상기 양식조 내의 수위가 조절되고,상기 흡입관의 하측 말단부에는 물 흡입구가 위치하며, 상기 흡입관 중간에 물을 흡입하여 양식조에 공급되는 수온을 조절하는 개폐형 흡입개구부가 형성되는 것을 특징으로 하는, 부유식 해상구조물을 활용한 어류 양식 설비., Ltext: 어업, prediction: 어업
273/1059 Row 273: application_number: 1020190068918, combined_string: invention_title: 수조순환장치 abstract: 본 발명은 수조 내부의 수조수를 순환시켜 어류생식조건을 형성하며, 수조수 오염 방지를 목적으로 한다. 구체적으로 상부가 개방되며, 수조수를 수용하는 수조와 상기 수조 내부에 위치하며, 수조수를 순환시키는 추진장치와 수조 내부에 위치하며, 수조수 를 흡입하는 흡입장치와 추진장치 및 흡입장치 사이에 위치하여 수조수를 유동하는 순환장치를 구비한다. claims: 상부가 개방되며, 수조수(20)를 수용하는 수조(10);상기 수조(10) 내부에 위치하며, 수조수(20)를 순환시키는 추진장치(100);상기 수조(10) 내부에 위치하며, 수조수(20)를 흡입하는 흡입장치(200);상기 추진장치(100) 및 흡입장치(200) 사이에 위치하여 수조수(20)를 유동하는 순환장치(300);를 포함하고,상기 추진장치(100)는 복수로 형성되며, 수조(10) 내부에 수용되며, 수조수(20)를 분사시키는 추진부(120);상기 순환장치(300) 및 상기 복수의 추진부(120) 사이를 연통하는 분배부(130);상기 복수의 추진부(120)를 상기 수조(10)에 일체로 고정하는 고정부(160);를 포함하고,상기 추진부(120)는 내부에 고압의 수조수(20)가 채워지며, 일면에 내부배출개구가 형성되며, 나선형으로 형성된 케이스(121);상기 케이스(121)와 이격 설치되고, 상기 내부배출개구 위치에 중첩된 판재로 형성되며, 상단에서 하단으로 향할수록 상기 케이스(121)와 이격 간격이 상이 하게 형성된 추진판(122);상기 추진판(122) 단부 및 상기 케이스(121)에 결합되며, 상기 추진판(122)을 회동시키는 회전축(140);상기 회전축(140) 및 추진판(122)을 회동시키는 엑츄에이터;상기 케이스(121) 내부에 형성되며, 수조수(20)의 방출 방향을 조절하는 복수의 조절판(150);을 포함하는 수조순환장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

274/1059 Row 274: application_number: 1020190068027, combined_string: invention_title: 홍해삼 수정란 생산방법 abstract: 홍해삼 어미관리의 체계화를 통해 종묘생산자가 원하는 시기에 양질의 수정란을 계획생산이 가능하여 양식산업 및 종묘산업화로서 견인 가능하다. 또한 조기 수정란 생산을 통하여 당해 연도에 필요한 방류 및 중간육성용 대형종묘를 생산함으로서 방류효과를 증대시키고, 마을어장 자원조성량 증대를 통해 가공산업, 수출, 관광, 미용 및 건강식품 등의 관련산업 유발효과를 통해 시너지 효과를 기대할 수 있다. claims: 수조에서 사육수를 뺀 후, 해삼이 공기중에 노출된 채로 1시간 방치하는 간출자극을 진행한 후, 모삼이 수용된 수조에 해수를 가득 채운 후 배합사료의 농도를 100-150ppm으로 조절한 사료현탁액을 공급하는 사료현탁액 자극의 순서로 이루어지는 것을 특징으로 하는 홍해삼 수정란 생산방법수조에서 사육수를 뺀 후, 해삼이 공기중에 노출된 채로 1시간 방치하는 간출자극을 진행한 후, 모삼이 수용된 수조에 해수를 가득 채운 후, 배합사료의 농도를 100-150ppm으로 조절한 사료 현탁액을 공급하는 사료현탁액 자극 후, 모삼이 수용된 수조내에 공기주입과 해수주입을 중단하고 3 - 5시간 동안 방치하는 무에어, 무환수자극의 순서로 이루어지는 것을 특징으로 하는 홍해삼 수정란 생산방법, Ltext: 어업, prediction: 어업
275/1059 Row 275: application_number: 1020190068095, combined_string: invention_title: 바이오플락을 이용한 새우 양식장 abstract: 본 발명은 바이오플락을 이용한 새우 양식장에 관한 것으로, 본 발명이 해결하고자 하는 과제는 수조에 새우와 함께 양식되는 미생물이 뭉쳐서 가라앉지 않게 컨트롤 할 수 있으며, 양식장의 확장 없이 새우의 탈피할 수 있는 공간과 탈피 후 쉴 수 있는 공간을 마련하는데 있다.일례로, 바이오플락 양식을 위한 미생물 및 양식수를 수용하고, 면적이 서로 다르며 서로 분리된 다수의 양식수조; 및 상기 양식수조 사이에 형성되고, 상기 양식수조와의 격벽 일부가 개방되어 연결되고, 상기 양식수조보다 깊게 형성되며, 잉여 양식수를 상기 양식수조로 공급하기 위한 다수의 침전조를 포함하는 바이오플락을 이용한 새우 양식장을 개시한다. claims: 바이오플락 양식을 위한 미생물 및 양식수를 수용하고, 면적이 서로 다르며 서로 분리된 다수의 양식수조; 및상기 양식수조 사이에 형성되고, 상기 양식수조와의 격벽 일부가 개방되어 연결되고, 상기 양식수조보다 깊게 형성되며, 잉여 양식수를 상기 양식수조로 공급하기 위한 다수의 침전조를 포함하고,상기 양식수조와 상기 침전조 간의 격벽 상단이 개방되어 상기 격벽 상단에 단차부가 형성되고, 상기 단차부를 통해 상기 침전조가 상기 양식수조와 연결되고,상기 양식수조의 내측벽은 상기 양식수조의 바닥면을 향해 45° 내지 75°의 경사각으로 기울어진 경사면을 갖도록 형성된 것을 특징으로 하는 바이오플락을 이용한 새우 양식장., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

276/1059 Row 276: application_number: 1020217000447, combined_string: invention_title: 동일한 경쇄 I을 갖는 다양한 항체를 생산하기 위한 트랜스제닉 동물 abstract: 본원은 무엇보다도 항체 다양화를 위해 유전자 전환을 사용하는 트랜스제닉 동물에서 항체 다양화를 최소화하기위한 전략을 제공한다. 일부 실시양태에서, 상기 동물은 내인성 면역 글로불린 경쇄 유전자 좌위(endogenous immunoglobulin light chain locus)를 포함하는 게놈(genome)을 포함한다: (a) 경쇄 가변 영역을 인코딩하는 핵산을 포함하는 기능성 면역글로블린 경쇄 유전자; 및 (b) 상기 기능성 면역글로불린 경쇄 유전자에 작동가능하게 연결되고, 유전자 전환에 의해, 경쇄 가변 영역을 인코딩하는 상기 핵산에 뉴클레오티드 서열을 기증하는 다수의 유사 유전자(pseudogenes)를 포함하며, 상기 유사 유전자가 상기 기능성 면역글로불린 경쇄 유전자의 상류(upstream) 또는 하류(downstream)에 있으며, 각각의 상기 유사 유전자는 (a)의 기능성 면역글로불린 경쇄 유전자의 경쇄 가변 영역과 동일한 아미노산을 인코딩한다. 다른 실시양태에서, 상기 유전자좌는 상기 경쇄에 대한 코딩 서열이 직렬 어레이를 가질 수 있다. claims: 내인성 면역 글로불린 경쇄 유전자 좌위(endogenous immunoglobulin light chain locus)를 포함하는 게놈(genome)을 포함하는 항체 다양화를 위해 유전자 변환을 사용하는 트랜스제닉 동물로서, (a) 경쇄 가변 영역을 인코딩하는 핵산을 포함하는 기능성 면역글로블린 경쇄 유전자; 및(b) 상기 기능성 면역글로불린 경쇄 유전자에 작동가능하게 연결되고, 유전자 전환에 의해, 경쇄 가변 영역을 인코딩하는 상기 핵산에 뉴클레오티드 서열을 기증하는 다수의 유사 유전자(pseudogenes)를 포함하며, 상기 유사 유전자가 상기 기능성 면역글로불린 경쇄 유전자의 상류(upstream) 또는 하류(downstream)에 있으며, 각각의 상기 유사 유전자는 (a)의 기능성 면역글로불린 경쇄 유전자의 경쇄 가변 영역과 동일한 아미노산을 인코딩하는, 트랜스제닉 동물.(a) 제1항 내지 제15항 중 어느 한 항의 트랜스제닉 동물을 항원으로 면역화하는 단계;(b) 상기 항원에 특이적으로 결합하는 항체를 상기 동물로부터 수득하는 단계를 포함하는 방법.제1항 내지 제15항 중 어느 한 항의 트랜스제닉 동물에 의해 생성된 폴리클로날 항체로서, 상기 항혈청(antiserum) 내 항체의 적어도 50% 이상이 실질적으로 동일한 경쇄 서열을 갖는 폴리클로날 항체.제1항 내지 제15항 중 어느 한 항의 트랜스제닉 동물에 의해 생성된 적어도 1000개 이상의 B 세포 집단으로서, 상기 B 세포의 적어도 50% 이상이 실질적으로 동일한 경쇄 서열을 갖는 항체를 생성하는 집단.제1항 내지 제15항 중 어느 한 항의 동물로부터 분리된 B 세포.제1항 내지 제15항 어느 한 항의 동물로 생성된 모노클로날 항체., Ltext: 어업, prediction: 임업
277/1059 Row 277: application_number: 1020217001018, combined_string: invention_title: 유전자 변환에 의한 자율 중쇄 가변 도메인의 수정에 의한 항체 생산 abstract: 본원은 무엇보다도 B 세포(B cell)를 포함하는, 항체 다양화를 위해 유전자 변환을 사용하는 트랜스제닉 동물을 제공하며, 내인성 면역 글로불린 중쇄 유전자 좌위는 다음을 포함한다: (a) 자율 중쇄(autonomous heavy chain, AHC) 가변 도메인을 인코딩하는 핵산을 포함하는 기능성 면역 글로불린 중쇄 유전자; 및 (b)　상기 기능성 면역글로불린 중쇄 유전자에 작동가능하게 연결되고, 유전자 전환에 의해 (a)의 AHC 가변 도메인을 인코딩하는 핵산에 뉴클레오티드 서열을 제공하는 복수의 유사 유전자(pseudogenes)로서, 상기 유사 유전자는 상기 기능성 면역글로불린 중쇄 유전자의 상류(upstream) 또는 하류(downstream)에 존재한다. claims: B 세포(B cell)를 포함하는 항체 다양화를 위해 유전자 변환을 사용하는 트랜스제닉 동물로서, 내인성 면역 글로불린 중쇄 유전자 좌위(endogenous immunoglobulin heavy chain locus)는:(a) 자율 중쇄(autonomous heavy chain, AHC) 가변 도메인을 인코딩하는 핵산을 포함하는 기능성 면역 글로불린 중쇄 유전자; 및(b)　상기 기능성 면역글로불린 중쇄 유전자에 작동가능하게 연결되고, 유전자 전환에 의해 (a)의 AHC 가변 도메인을 인코딩하는 핵산에 뉴클레오티드 서열을 제공하는 복수의 유사 유전자(pseudogenes)를 포함하며, 상기 유사 유전자는 상기 기능성 면역글로불린 중쇄 유전자의 상류(upstream) 또는 하류(downstream)에 존재하는 것인, 트랜스제닉 동물.(a) 제1항 내지 제23항 중 어느 한 항의 트랜스제닉 동물을 항원으로 면역화하는 단계;(b) 상기 항원에 특이적으로 결합하는 항체를 상기 동물로부터 수득하는 단계를 포함하는 방법.제1항 내지 제23항 중 어느 한 항의 트랜스제닉 동물에 의해 생산된 모노클로날 또는 폴리클로날 항체로서, 상기 항체가 자율 중쇄 (autonomous heavy chain, AHC) 가변 도메인 항체인 모노클로날 또는 폴리클로날 항체.제1항 내지 제23항 중 어느 한 항의 동물로부터 분리된 B 세포., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

278/1059 Row 278: application_number: 1020190062035, combined_string: invention_title: 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초 제조방법 및 그 세라믹 인공어초 abstract: 본 발명은 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초 제조방법 및 그 세라믹 인공어초에 관한 것으로 인공어초의 표면에 해조류 등의 활착성이 우수하면서도 성장성을 도모하며, 어류 등의 산란장 및 휴식장을 마련하도록 하며, 인공어초의 적층 및 연결이 용이한 구조를 갖도록 하기 위하여, 세라믹파우더 100중량부를 기준으로 칼슘, 인, 칼륨, 나트륨, 염소, 마그네슘, 철, 아이오딘, 구리, 아연, 코발트, 망간 중 어느 하나 또는 어느 하나 이상의 미네랄파우더를 5∼8중량부 첨가하여 혼합파우더를 제조 하는 단계(S1); 상기 혼합파우더를 배합기에 투입하고 가수하여 함수율 19∼20％의 상태로 배합하는 단계(S2); 상기 배합된 혼합파우더를 진공토련기에 투입하여 공기를 뽑아내고, 상기 진공토련기의 압출구 전단에 설치된 어초형상의 사출금형을 통하여 인공어초 반제품을 사출성형하는 1차성형단계(S3); 절단기를 이용하여 상기 1차성형된 인공어초 반제품을 요구되는 길이로 절단하는 2차성형단계(S4); 직립기를 이용하여 상기 2차성형된 인공어초 반제품을 건조판의 상부로 일으켜 세워 직립시킨 다음, 상기 인공어초 반제품을 건조대차에 적재하는 단계(S5); 상기 인공어초 반제품이 적재된 건조대차를 건조실로 이송하여 건조하는 단계(S6); 상기 건조된 인공어초 반제품을 소성컨테이너에 적재한 후, 상기 적재된 소성컨테이너를 가마에 이송하고 이를 950∼1030℃ 사이에서 산화소성하여 인공어초를 완성하는 단계(S7);를 포함하여 이루어짐을 특징으로 한다. claims: 세라믹 파우더를 포함한 혼합파우더를 제조하는 단계(S1); 상기 혼합파우더를 배합기에 투입하고 가수하여 함수율 19∼20％의 상태로 배합하는 단계(S2); 상기 배합된 혼합파우더를 진공토련기에 투입하여 공기를 뽑아내고, 상기 진공토련기의 압출구 전단에 설치된 어초형상의 사출금형을 통하여 인공어초 반제품을 사출성형하는 1차성형단계(S3); 절단기를 이용하여 상기 1차성형된 인공어초 반제품을 400~600mm의 길이로 절단하는 2차성형단계(S4); 상기 2차성형된 인공어초 반제품을 적재하는 단계(S5); 상기 인공어초 반제품이 적재된 건조대차를 건조실로 이송하여 건조하는 단계(S6); 상기 건조된 인공어초 반제품을 소성컨테이너에 적재한 후, 상기 적재된 소성컨테이너를 가마에 이송하고 이를 산화소성하여 인공어초를 완성하는 단계(S7);를 포함하여 이루어지는 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초 제조방법에 있어서,상기 혼합파우더를 제조 하는 단계(S1)는 세라믹파우더 100중량부를 기준으로 인, 나트륨, 염소, 아이오딘, 구리, 아연, 코발트, 망간 중 어느 하나 또는 어느 하나 이상의 미네랄파우더를 5∼8중량부 첨가하여 혼합파우더를 제조한 후, 상기 혼합파우더 100중량부를 기준으로 바인더를 9~12중량부 혼합하되, 상기 바인더는 점토와 산청토를 혼합하고,상기 적재하는 단계(S5)는, 상기 2차성형된 인공어초 반제품을 건조판의 상부로 일으켜 세워 직립시킨 다음, 상기 인공어초 반제품을 건조대차에 적재하며,상기 건조하는 단계(S6)는 상기 인공어초 반제품이 적재된 건조대차를 1차건조실에서 6일간 숙성한 다음 건조하고, 2차건조실에서 6일간 온도 70℃, 습도 15%에서 건조하고,상기 완성하는 단계(S7)는 950∼1030℃ 사이에서 25시간 산화소성한 후, 상온까지 냉각하여 요출하며,상기 인공어초는 단면이 6각관 형태로 형성되며, 상기 6각관 형태로 형성된 인공어초의 적층 시 상호간에 돌부(17) 및 홈부(19) 결합구조로 결합되도록 구성되고,상기 인공어초의 내외측 표면에 다수의 정형 또는 비정형의 홈형태로 된 스크래치홈부(92)를 형성하여, 상기 스크래치홈부(92) 내에서 해조류가 활착되도록 구성하는 것을 특징으로 하는 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초 제조방법.세라믹파우더 100중량부를 기준으로 칼슘, 인, 나트륨, 염소, 아이오딘, 구리, 아연, 코발트, 망간 중 어느 하나 또는 어느 하나 이상의 미네랄파우더를 5∼8중량부 첨가하여 혼합파우더를 제조 하고, 상기 혼합파우더를 배합기에 투입하고 가수하여 함수율 19∼20％의 상태로 배합하며, 상기 배합된 혼합파우더를 진공토련기에 투입하여 공기를 뽑아내고, 상기 진공토련기의 압출구 전단에 설치된 어초형상의 사출금형을 통하여 인공어초 반제품을 사출성형하여 1차성형하고, 절단기를 이용하여 상기 1차성형된 인공어초 반제품을 요구되는 길이로 절단하는 2차성형하며, 직립기를 이용하여 상기 2차성형된 인공어초 반제품을 건조판의 상부로 일으켜 세워 직립시킨 다음, 상기 인공어초 반제품을 건조대차에 적재하고, 상기 인공어초 반제품이 적재된 건조대차를 건조실로 이송하되, 1차건조실에서 6일간 숙성한 다음 건조하고, 2차건조실에서 6일간 온도 70℃, 습도 15%에서 건조하며, 상기 건조된 인공어초 반제품을 소성컨테이너에 적재한 후, 상기 적재된 소성컨테이너를 가마에 이송하고 이를 950∼1030℃ 사이에서 25시간 산화소성한 다음 상온까지 냉각하여 요출하여 구성되고,상기 혼합파우더 100중량부를 기준으로 바인더를 9~12중량부 혼합하되, 상기 바인더는 점토와 산청토를 혼합하여 구성되며,상기 인공어초는 단면이 6각관 형태로 형성되며, 상기 6각관 형태로 형성된 인공어초의 적층 시 상호간에 돌부(17) 및 홈부(19) 결합구조로 결합되도록 구성되고,상기 인공어초의 내외측 표면에 다수의 정형 또는 비정형의 홈형태로 된 스크래치홈부(92)를 형성하여, 상기 스크래치홈부(92) 내에서 해조류가 활착되도록 구성하는 것을 특징으로 하는 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초., Ltext: 어업, prediction: 임업
279/1059 Row 279: application_number: 1020190053290, combined_string: invention_title: 패류 부유기 인공종묘 양식설비 abstract: 본 발명은 바다와 인접한 육상의 실내 공간에 설치되는 것으로, 바다로부터 해수를 공급받아 패류의 부유기(400㎛ 이하의 길이) 유생을 양성하는 인공종묘 양식설비에 있어서, 해수를 수용하기 위한 공간부를 갖는 통형상으로 이루어지며, 상기 공간부 외벽의 일측에 관통형성된 배수관을 갖는 수조부; 상기 수조부의 상부에 길이방향을 따라 복수열로 설치되어 바다로부터 공급된 해수를 상기 수조부에 공급하되, 저면에는 길이방향을 따라 일정 간격으로 복수개의 배수공이 관통형성되어 하방으로 상기 해수가 배수되도록 하는 해수공급부; 및 상기 해수공급부의 배수공과 대응하는 위치에 배치되도록 상기 수조부의 내부에 수용되되, 저면에는 상기 유생보다 작은 면적의 구멍을 갖는 그물망이 형성되어 일정 개체수의 유생을 수용하는 유생수용유닛;을 포함하는 것을 기술적 요지로 한다. claims: 바다와 인접한 육상의 실내 공간에 설치되는 것으로, 바다로부터 해수를 공급받아 패류의 부유기(400㎛ 이하의 길이) 유생을 양성하는 인공종묘 양식설비에 있어서,해수를 수용하기 위한 공간부를 갖는 통형상으로 이루어지며, 상기 공간부 외벽의 일측에 관통형성된 배수관을 갖는 수조부;상기 수조부의 상부에 길이방향을 따라 복수열로 설치되어 바다로부터 공급된 해수를 상기 수조부에 공급하되, 저면에는 길이방향을 따라 일정 간격으로 복수개의 배수공이 관통형성되어 하방으로 상기 해수가 배수되도록 하는 해수공급부; 및상기 해수공급부의 배수공과 대응하는 위치에 배치되도록 상기 수조부의 내부에 수용되되, 저면에는 상기 유생보다 작은 면적의 구멍을 갖는 그물망이 형성되어 일정 개체수의 유생을 수용하는 유생수용유닛;을 포함하는 것을 특징으로 하는 패류 부유기 인공종묘 양식설비., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

280/1059 Row 280: application_number: 1020190053060, combined_string: invention_title: 3D 프린터에 의해 제조되는 인공어초 abstract: 본 발명은 3D 프린터에 의해 제조되는 인공어초에 관한 것으로, 3D 프린터에 의해 제조되며, 하부로 갈수록 면적이 증가하는 하광상협의 기둥형태를 갖는 몸체와, 상기 몸체의 내부에 형성되는 중공부와, 상기 중공부와 몸체의 외부를 연통시키는 상기 몸체의 측면에 형성된 다수의 관통 홀 및 상기 중공부에 형성되고 상기 몸체의 내측면을 지지하는 보강 지지체를 포함하는 것을 특징으로 하는 3D 프린터에 의해 제조되는 인공어초가 개시된다. claims: 3D 프린터에 의해 제조되며,하부로 갈수록 면적이 증가하는 하광상협의 기둥형태를 갖는 몸체;상기 몸체의 내부에 형성되는 중공부;상기 중공부와 몸체의 외부를 연통시키는 상기 몸체의 측면에 형성된 다수의 관통 홀; 및상기 중공부에 형성되고 상기 몸체의 내측면을 지지하는 보강 지지체;를 포함하며,상기 몸체는 표면에 다수의 요철부가 형성되고,상기 몸체는 다각 기둥형태를 갖되, 상기 보강 지지체는 몸체의 면과 면이 만나는 경계로부터 몸체의 하부를 향해 형성되며,상기 보강 지지체는 상기 몸체의 무게중심이 몸체의 하부에 위치하도록 형성되고,상기 몸체는해저면에 안치되는 평판형의 바닥부;상기 바닥부의 가장자리 둘레에 일정 간격을 두고 상부로 연장되는 메인 지지체; 및상기 메인 지지체의 양측면에 형성되어 상기 메인 지지체의 상단을 이웃한 메인 지지체의 상단 및 상기 바닥부와 일체로 연결하는 측면 지지체;를 포함하며,상기 측면 지지체는수산생물 및 해류가 출입하며 상기 측면 지지체의 상하방향에 걸쳐 형성되는 제1관통 홀; 및상기 제1관통 홀의 주변에 형성되며 상기 제1관통 홀에 비해 작은 개구 면적을 형성하는 제2관통 홀;을 포함하고,상기 제2관통 홀은 타원형, 원형, 삼각형 중 적어도 어느 하나로 형성되며,상기 바닥부는 해저면과 상기 중공부를 연통시키는 제3관통 홀이 형성되고,상기 몸체와 보강 지지체는 혼합물 전체 부피의 2.8 ~ 4.9%의 결합재와, 혼합물 전체 부피의 70.0 ~ 78.5%의 산업부산물과, 혼합물 전체 부피의 0.28 ~ 0.49 %의 콘크리트용 섬유와, 혼합물 전체 부피의 0.02 ~ 0.05 %의 혼화제와, 혼합물 전체 부피의 15.7 ~ 21.0%의 물과 잔량으로서 공기를 포함하여 구성되고,상기 혼화제는 조강제, 수축저감제, 고유동화제가 1 : 1 : 1의 중량비로 혼합된 것을 특징으로 하는 3D 프린터에 의해 제조되는 인공어초., Ltext: 어업, prediction: 어업
281/1059 Row 281: application_number: 1020210131235, combined_string: invention_title: 큰징거미새우의 다칸 다단 양식 장치 abstract: 본 발명은 상방으로 개방되고, 저수를 위한 수조; 상기 수조의 내측에서 링형태의 경로를 따라 순환 이동하도록 다수로 배치되고, 상기 수조의 내측에서 큰징거미새우의 양식을 위한 공간을 분할 형성하도록 하는 분리칸; 및 상기 분리칸 각각이 상기 경로를 따라 이동하도록 하는 칸이송부;를 포함하도록 한 큰징거미새우의 다칸 다단 양식 장치에 관한 것이다.본 발명에 따르면, 큰징거미새우가 서로 잡아먹는 특성을 고려하여, 개별 양식을 강화시킬 수 있고, 개별 양식에도 불구하고 사육 밀도를 높임으로써 대량 양식을 도모할 수 있으며, 칸별 이송 뿐만 아니라 단별 이송을 가능하도록 함으로써, 큰징거미새우의 양식에 필요한 작업을 정해진 장소에서 편리하게 수행하도록 할 수 있고, 이로 인해 양식에 소요되는 노력과 인원을 최소화하도록 하는 효과를 가진다. claims: 상방으로 개방되고, 저수를 위한 수조;상기 수조의 내측에서 링형태의 경로를 따라 순환 이동하도록 다수로 배치되고, 상기 수조의 내측에서 물에 잠기어 큰징거미새우의 양식을 위한 공간을 분할 형성하도록 하는 분리칸; 및상기 분리칸 각각이 상기 경로를 따라 이동하도록 하는 칸이송부;를 포함하는, 큰징거미새우의 다칸 다단 양식 장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

282/1059 Row 282: application_number: 1020210101310, combined_string: invention_title: 어군용 재활용 냉동습식사료 가공방법 abstract: 본 발명은 최근에 식생활이 상향되어 먹는 부위보다 버리는 부위가 많아져 이로 인한 음식찌꺼기가 폐기물로 버려지는데 외식업조합의 노력으로 수거는 되지만 재활용도 어렵고 폐기장소도 막혀가며 더구나 비료로 활용하고자 하나 염도도 높아 사용하기 어렵고 처리하기도 어려운 상황인데 대량으로 발생되는 수산물가공공장에서 발생하는 폐기수산물까지 발생하지만 이는 가두리양식장이나 축양어장에서 활용할 수 있는 수준이므로 어군용 습식사료로 재활용하고자 개발한 어류사료에 속하는 재활용사업 가공분야에 관한 사료분야의 연구개발 사업이다,예전에는 양식어장에서 신선한 활어를 사료용으로 사용하였으나 어족자원보호와 연근해 어획통제로 활어를 구하기 어려워 이제는 사료가공 산업에도 다양한 품목과 기술이 향상되어 웬만한 신선도만 유지할 수 있게 가공한다면 폐기물에서도 재활용을 위한 선별과 가공이 가능하여 이를 새로운 재활용사업으로 이끌려는 연구가 개시되므로 재활용분야에서 새로운 과제로 전개되어 뜨는 기술개발분야이다,비록 폐기수산물만이라 하지만 모두 재활용이 가능하며 본 발명에서 어군용 재활용 냉동습식사료로 가공하여 어류습식사료로 제공되므로 인해 늘어만 가던 수산업계에 분리수거 가공으로 폐기물처리의 발생량을 저감 할 수 있고 사료사업에서도 저가의 재활용사료로 인해 사육원가도 줄일 수 있는 양대 효과는 물론 어류사료 부족문제까지 해결되는 효과가 기대된다,[색인어]폐기수산물, 분리어유, 냉동습식사료, 파쇄어죽,재활용사료, 생어사료, 가두리양식, 축양어장, claims: 가두리 또는 축양양식장양식어군에 수산물가공부산물사료로 제공되는 재활용 어군용 냉동습식사료의 가공방법에 있어서,참치수산물가공공장에서 폐기되는 참치가공부산물을 원료수집(제1공정)하여 파쇄어죽(제2공정)으로 가공하여 용기에 담고, 상기 파쇄어죽과 상기 파쇄어죽의 동량의 물로 가수교반(제3공정)한 후 가온분리(제4공정)로 상기 파쇄어죽에서 어유가 물에 용해되면 드럼여과(제5공정)로 여과어육(제6-1공정)만 수거하여 수지용기에 담아 컨베이어벨트에 올려 자외선조사(제8공정)를 하여 냉동어육(제9-1공정)으로 가공되는 것이 특징인 재활용 어군용 냉동습식사료의 가공방법, Ltext: 어업, prediction: 어업
283/1059 Row 283: application_number: 1020210062227, combined_string: invention_title: 동애등에 공급을 통한 넙치 양식방법 및 사료조성물 abstract: 본 발명은 넙치 유수식 양식방법에 관한 것으로, 유수식 양식에서 사용되는 넙치 사료를 어분을 대신하여 동애등에로 이루어진 곤충분이 포함하거나, 어유의 일부를 대신하여 동애등에로부터 얻어진 곤충유를 포함하여 공급함으로서 유수식 수산 양식 시스템에서 양식 넙치의 성장 및 장내 소화 활성을 증가시킬 수 있도록한 넙치 유수식 양식방법를 제공함으로써, 낮은 원료 가격과 안정된 생산량으로 사료를 제조할 수 있는 효과를 얻을 수 있다. claims: 넙치 양식방법에 있어서 넙치 양식용 사료에 포함된 성분중 동물성 단백질의 일부를 곤충으로 대체하여 급이하며,상기 넙치 양식용 사료 조성물은 탈피대두박 2중량%, 밀가루 10중량%, 비타민C 와 E 각각 0.5중량%, 비타민프리믹스와 미네랄프리믹스 각각 1중량%, 인산칼슘, 염화콜린 및 타우린이 각각 0.5중량%, 어유 3중량%로 고정되며, 동물성 단백질원인 어분이 56 내지 63중량%로 포함될 때, 동애등에로 이루어진 곤충분말은 7 내지 14중량%의 범위값으로 포함하고, 소맥글루텐 6.2~8.1중량%, 전분 2.02~4.17중량% 및 셀룰로오스 0.13~0.38중량%의 범위 값으로 포함하여 이루어지며;상기 사료조성물 100중량부에 대하여 물 30~40중량부를 더 첨가하여 펠렛 제조기로 사료를 성형하되 , 익스트루더의 스크류 속도를 885 rpm/min로 조절하여 사료 입도를 181um이하 크기로 제조한 사료를 급이하는 것을 특징으로 하는 넙치 양식방법탈피대두박 2중량%, 밀가루 10중량%, 비타민C 와 E 각각 0.5중량%, 비타민프리믹스와 미네랄프리믹스 각각 1중량%, 인산칼슘, 염화콜린 및 타우린이 각각 0.5중량%, 어유 3중량%로 고정되며, 동물성 단백질원인 어분이 56 내지 63중량%로 포함될 때, 동애등에로 이루어진 곤충분말은 7 내지 14중량%의 범위값으로 포함하고, 소맥글루텐 6.2~8.1중량%, 전분 2.02~4.17중량% 및 셀룰로오스 0.13~0.38중량%의 범위값으로 포함하여 이루어지는 것을 특징으로 하는 넙치 양식용 사료, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

284/1059 Row 284: application_number: 1020210062239, combined_string: invention_title: 동애등에 공급을 통한 무지개송어 양식방법 및 사료조성물 abstract: 본 발명은 무지개송어 순환여과식 양식방법에 관한 것으로, 순환여과식 양식에서 사용되는 무지개송어 사료의 어분을 대신하여 동애등에로 이루어진 곤충분이 포함하거나, 어유의 일부를 대신하여 동애등에로 이루어진 곤충유를 포함하여 급이함으로서 순환여과식 양식 시스템에서 양식 무지개 송어의 성장 및 장내 미생물 활성을 증가시킬수 있도록한 무지개송어 순환여과식 양식방법를 제공함으로써, 낮은 원료 가격과 안정된 생산량으로 사료를 제조할 수 있는 효과를 얻을 수 있고, 어분 및 곤충분에 의한 충실한 동물성 단백질 공급이 가능하여, 무지개송어의 성장, 비만도 저하, 생존율 및 장내 미생물 다양성 확보로 인한 항병력이 증가될 수 있는 효과가 있다. claims: 무지개송어 양식방법에 있어서 무지개송어 양식용 사료에 포함된 성분중 동물성 단백질의 일부를 곤충으로 대체하여 급이하며, 상기 무지개송어 양식용 사료는 동물성 단백질원인 어분 16중량%, 동애등에 분말 4중량%, 탈피대두박 19중량%, 소맥글루텐 10중량%, 전분 5중량%, 밀가루 14.03중량%, 비타민믹스, 미네랄믹스 각각 1중량%, 비타민 C 0.2중량%, 비타민 E 0.1중량%, 인산칼슘 0.5중량%, 염화콜린 2.5중량%, 라이신 0.07중량%, 메치오닌, 트레오닌 각각 0.04중량%, 타우린 0.52중량%, 어유11중량%를 포함하여 이루어지는 사료 조성물을 혼합하여,상기 혼합물 100중량부에 대하여 물 30~40중량부를 더 첨가하여 익스트루더로 사료를 성형하며, 상기 사료의 성형은 압출성형기의 압력조건을 619.5~708 rpm/min의 범위에서 실시하며, 사료원료의 입자도는 사료원료의 입자도는 평균 직경 180μm의 소립자로 성형한 사료를 급이하는 것을 특징으로 하는 무지개송어 양식방법동물성 단백질원인 어분 16중량%, 동애등에 분말 4중량%, 탈피대두박 19중량%, 소맥글루텐 10중량%, 전분 5중량%, 밀가루 14.03중량%, 비타민믹스, 미네랄믹스 각각 1중량%, 비타민 C 0.2중량%, 비타민 E 0.1중량%, 인산칼슘 0.5중량%, 염화콜린 2.5중량%, 라이신 0.07중량%, 메치오닌, 트레오닌 각각 0.04중량%, 타우린 0.52중량%, 어유 11중량%를 포함하여 이루어지는 것을 특징으로 하는 무지개송어 양식용 사료, Ltext: 어업, prediction: 임업
285/1059 Row 285: application_number: 1020210044001, combined_string: invention_title: 유용미생물을 포함하는 사료 첨가제 조성물 및 이의 제조방법 abstract: 본 발명은 EM(Effective microorganisms) 발효액 및 천일염을 포함하는 장어용 사료 첨가제 조성물 및 상기 장어용 사료 첨가제의 제조방법에 관한 것이다.본 발명의 장어용 사료 첨가제 조성물은 EM 발효액 및 천일염 등의 천연 성분을 포함함으로써 우수한 항균 및 항산화 활성을 나타내어 합성 항생제의 사용을 대체할 수 있으며, 상기 사료 첨가제를 급여하여 양식된 장어는 뛰어난 맛과 향을 가지는 것을 확인하였다. claims: EM(Effective microorganisms) 발효액, 천일염, 톳 분말, 비타민 C 및 비타민 E를 포함하는 장어용 사료 첨가제 조성물로서,상기 조성물은 EM 발효액 100 중량부를 기준으로, 천일염 5 중량부, 톳 분말 10 중량부, 비타민 C 1 중량부, 및 비타민 E 1 중량부를 포함하는 것이며,상기 EM 발효액은 EM 원액, 매실 열수 추출물, 및 설탕을 1:7:2의 중량비로 혼합하여 10 내지 15일 간 발효하여 제조된 것인, 장어용 사료 첨가제 조성물.제1항의 EM(Effective microorganisms) 발효액, 천일염, 톳 분말, 비타민 C 및 비타민 E를 혼합하는 단계;를 포함하는, 제1항 장어용 사료 첨가제의 제조방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

286/1059 Row 286: application_number: 1020210033912, combined_string: invention_title: 자율주행 기반의 양식장 관리 로봇 및 그 운영 시스템 abstract: 본 명세서는 스마트 양식장을 위한 양식장 관리 로봇의 메인 컨트롤러에 의한 먹이충전 방법에 있어서, 탐지된 먹이 공급 이벤트에 근거하여 : 1) 먹이 공급이 요구되는 수조의 식별자, 먹이 종류 및 먹이 공급량 정보를 판단하고, 2) 사료 공급장치의 호퍼에 포함된 잔여 사용량을 판단하는 단계; 상기 잔여 사료량이 상기 먹이 공급량보다 적을 경우, 자율주행 구동부를 통해, 먹이 충전을 위한 충전장치로 상기 양식장 관리 로봇을 이동시키는 단계; 및 상기 충전장치로 이동이 완료된 경우, 상기 충전장치로 먹이 충전을 요청하는 충전 요청 메시지를 전송하는 단계;를 포함할 수 있다. claims: 스마트 양식장을 위한 양식장 관리 로봇의 메인 컨트롤러에 의한 먹이 공급 방법에 있어서,탐지된 먹이 공급 이벤트에 근거하여 :1) 먹이 공급이 요구되는 수조의 식별자, 먹이 종류 및 먹이 공급량 정보를 판단하고, 2) 사료 공급장치의 호퍼에 포함된 잔여 사료량을 판단하는 단계;상기 잔여 사료량이 상기 먹이 공급량보다 많거나 같은 경우 :상기 수조의 식별자 및 기설정된 순서 리스트에 근거하여, 자율주행 구동부를 통해, 상기 수조의 식별자와 대응되는 제1 수조로 상기 양식장 관리 로봇을 이동시키는 단계;상기 먹이 종류 및 상기 먹이 공급량 정보에 근거하여, 토출구를 확장시켜, 상기 제1 수조에 급이하는 단계로서, 상기 토출구는 텔레스코픽(Telescopic) 구조를 갖음; 및상기 수조의 식별자 및 기설정된 순서 리스트에 근거하여, 상기 자율주행 구동부를 통해, 제2 수조로 상기 양식장 관리 로봇을 이동시키는 단계;를 포함하는, 먹이 공급 방법.스마트 양식장을 위한 먹이를 공급하는 양식장 관리 로봇에 있어서,전기 신호를 송수신하기 위한 송수신부;디스플레이부;자율주행 구동부;수조에 먹이를 공급하고, 충전장치로부터 먹이를 충전받기 위한 사료 공급 장치; 및상기 디스플레이부; 상기 송수신부, 상기 자율주행 구동부 및 상기 사료 공급장치를 제어하는 메인 컨트롤러;를 포함하며,상기 메인 컨트롤러는탐지된 먹이 공급 이벤트에 근거하여 :1) 먹이 공급이 요구되는 수조의 식별자, 먹이 종류 및 먹이 공급량 정보를 판단하고, 2) 상기 사료 공급장치의 호퍼에 포함된 잔여 사료량을 판단하며,상기 잔여 사료량이 상기 먹이 공급량보다 많거나 같은 경우 :상기 수조의 식별자 및 기설정된 순서 리스트에 근거하여, 상기 자율주행 구동부를 통해, 상기 수조의 식별자와 대응되는 제1 수조로 상기 양식장 관리 로봇을 이동시키고,상기 먹이 종류 및 상기 먹이 공급량 정보에 근거하여, 토출구를 확장시켜, 상기 제1 수조에 급이하며, 상기 토출구는 텔레스코픽(Telescopic) 구조를 갖고,상기 수조의 식별자 및 기설정된 순서 리스트에 근거하여, 상기 자율주행 구동부를 통해, 제2 수조로 상기 양식장 관리 로봇을 이동시키는, 로봇., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

287/1059 Row 287: application_number: 1020210013676, combined_string: invention_title: 관상어 양식 시스템 abstract: 물을 지속적으로 순환시키면서 불순물의 여과 및 정제를 수행하며, 용존산소량을 대폭 상승시켜 주는 것과 더불어 수위를 일정하게 유지하는 것으로 관상어를 안정적으로 양식할 수 있는 관상어 양식 시스템을 개시한다.본 발명의 목적은 어항의 물을 지속적으로 순환시키면서 불순물의 여과 및 정제를 수행할 수 있으며, 용존산소량을 늘릴 수 있는 관상어 양식 시스템을 제공하는 것이다. claims: 4면과 바닥면으로 구성되는 관상어 양식조;상기 양식조에 물을 공급하는 물 공급수단; 및상기 물 공급수단의 말단에 연결되어 상기 양식조의 수위를 일정하게 유지하는 수위조절수단;을 포함하는 관상어 양식 시스템에 있어서,상기 양식조는,상기 양식조의 4면과 바닥면으로 형성되며, 내부에 상단의 높이는 상기 양식조의 4면보다 낮고 전, 후단은 양식조의 전, 후면에, 하단은 바닥면에 각각 고정되어 상기 양식조의 일측에 양식실을 형성하며 타측에 격실을 형성하는 제1격벽;상단의 높이는 상기 양식조의 상단에 근접하고 상기 양식조의 좌면과 제1격벽의 사이에 위치하여 상기 격실을 제1 격실과 제2격실로 분할하는 제2격벽;상기 제2격벽의 하단과 바닥면의 사이에 형성되는 유통로;작은 구멍이 무수하게 천공된 다공성으로 제작되며 상기 유통로에 대응하는 높이로 상기 제1격실 및 제2격실의 바닥에 설치되는 유통판;상기 제1격실의 유통판 상부에 적층되는 밀도가 높은 스펀지;상기 제2격실의 유통판 상부에 적층하는 밀도가 낮은 스펀지; 및상기 양식실의 바닥과 상기 스펀지의 상부에 설치되는 광물질을 구비하며;상기 물 공급수단은,외부에서 공급되는 물을 일정기간 동안 저장하는 저장조;상기 저장조에서 공급되는 물에 미네랄, 영양성분 및 관상어용 약제를 자동으로 투입하는 약품 투입수단;상기 약품투입수단을 거쳐 공급되는 물을 상기 양식조로 운송하는 파이프; 및상기 저장조의 물을 상기 양식조로 공급하기 위하여 가압하는 물공급 펌프;를 포함하며,상기 수위조절수단은,상기 파이프의 말단에 연결되는 연결부;상기 연결부에서 공급되는 물을 개폐하는 벨브; 및상기 벨브에 연결되며, 수위를 감지하여 상기 벨브의 개폐를 제어하는 수위감지수단;을 포함하며,상기 수위감지수단은,상기 벨브에 일측이 연결되며, 타측이 부력볼과 연결되어 상기 부력볼이 상승할 때 상기 벨브를 폐쇠하는 작동암; 및상기 작동암의 타측에 연결되어 일정한 부력을 가지고 있어 수위의 상승에 따라 상승하는 부력볼;을 포함하며,상기 양식 시스템은 여과조 및 광생물 반응기를 추가로 포함하며;상기 여과조는 호기조 및 혐기조를 포함하며;상기 호기조는,4면벽과 바닥으로 형성되는 내부에 상단이 상기 4면벽의 상단과 동일한 높이로 되며 전단이 4면벽 중 전면벽의 내면 중간에 고정되는 전측부와 전측부의 후단에서 좌측으로 직각연장되며 4면벽 중 후면벽의 내면과 격리되게 좌단이 4면벽 중 좌면벽의 내면 후측에 고정되는 후측부와 후측부의 하단에 천공되는 유통구를 구비하는 제1격판에 의해 구획형성되는 침전실과, 상단의 높이가 상기 제1격판보다 낮으며 좌단은 전측부의 우면 후단에 고정하고 우단은 4면벽 중 우면벽의 후측에 밀착고정하는 제2격판에 의해 침전실의 후방에 위치하게 구획형성되는 제1여과실과, 상단의 높이가 상기 제1격판보다는 낮고 제2격판보다는 높으며 제2격판과 4면벽 중 전면벽의 우측부 사이에서 좌단은 제1격판의 전측부 우면에 밀착고정하고 우단은 4면벽중 우면벽에 고정하며 하단부는 바닥과 격리되게 설치되어 하단부와 바닥 사이에 유통부가 형성되게 하는 제3격판에 의해 제1여과실 우측부 전방에 구획형성되는 제2여과실과, 상기 제3격판에 의해 제2여과실의 전방에 구획형성되는 제3여과실과, 상단이 상기 4면벽 중 전면벽의 우측부 상측에 천공되는 구멍에 결합고정되어 제3여과실의 물을 혐기조로 공급하는 공급관과, 상기 침전실에 하부로부터 차례로 적층되는 광물질과 스펀지필터 및 부직포필터와, 상기 제1~3여과실의 바닥에 깔아주는 광물질을 구비하여 구성되며;상기 혐기조는,4면벽, 상부 및 바닥으로 형성되는 혐기조 본체;상기 본체의 상부에 결합되어 상기 본체 내부의 임펠러를 일정 속도로 회전시키는 회전축;상기 회전축의 일단에 연결되어 상기 본체 내부의 물을 혼합하는 임펠러;상기 회전축의 타단에 연결되어 상기 회전축을 회전시키는 모터;상기 혐기조 4면벽 중 좌측면 벽 하단에 연결되어 상기 제3여과실에서 공급되는 물을 상기 혐기조 내부로 주입하는 공급부;상기 혐기조 4면벽중 우측벽 상단이 연결되어 혐기반응이 완료된 물을 배출하여 광생물 반응기로 공급하는 배출부; 및상기 혐기조에 유기성분을 공급하는 유기성분 공급부;를 포함하며,상기 광생물 반응기는,상기 혐기조에서 공급되는 물을 각 광생물반응기 본체로 공급하는 분배관;내부에 미세조류 및 물을 포함하며, 상기 분배관에서 공급되는 물을 이용하여 광생물반응을 수행하는 1~30개의 광생물반응기 본체; 및상기 광생물반응기 본체에서 배출되는 물을 상기 양식조로 공급하는 물 공급부;를 포함하며,상기 광생물 반응기 본체는,고분자 필름으로 제조되어 내부에 반응공간을 형성하는 필름형 본체;상기 반응공간에 위치하며, 광생물반응을 수행하는 미세조류;상기 필름형 본체를 프레임에 고정시키는 고정수단;상기 필름형 본체의 하부에 연결되어 상기 반응공간의 내부로 상기 분배관에서 공급되는 물을 주입할 수 있는 주입부; 및상기 필름형 본체의 상부에 연결되며, 상기 반응공간 내부의 물을 상기 물공급부로 공급하는 배출부;를 포함하는 것을 특징으로 하는 관상어 양식 시스템., Ltext: 어업, prediction: 어업
288/1059 Row 288: application_number: 1020200168018, combined_string: invention_title: 육상수조식 양식장 육성기 넙치용 배합사료의 물성조절 제조방법 abstract: 본 발명은 사료원료의 입자도 조절, 압출펠렛(Extruded pellet; EP) 제조기의 압력 조절 및 알파전분에 의해 제조된 EP사료가 양식 넙치의 성장, 사료효율 및 성장인자 호르몬이 증가될 수 있도록 하는 넙치용 고품질 배합사료 제조방법에 관한 것으로, 품질 개선된 사료는 넙치의 성장 및 비만도가 증가될 수 있는 효과 및 본 발명의 기술을 적용하기 위해서 추가적인 설비 없이 양어사료회사의 기존 분쇄기, 익스트루더를 이용하여 적용 가능하여, 비용 상승 없이 품질 개선된 넙치용 배합사료 생산이 가능하다. claims: 사료원료는 어분 69중량%, 보조 단백질원으로 소맥글루텐 1.5중량%, 지질원으로 어유 3.0중량% 및 전분을 8중량%로 포함하며, 사료원료의 입자도는 평균 직경은 180μm의 소입자로 분쇄하며, 익스트루전 가공 압력은 1062~1079rpm/min의 고압력 가공조건으로 설정하여 제조된 배합사료를 1일 2회 8주간 공급하여 사육하는 것을 특징으로 하는 육상수조식 양식장의 육성기 넙치 양식방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

289/1059 Row 289: application_number: 1020200162515, combined_string: invention_title: 흰다리 새우 양식용 사료 및 이를 이용한 흰다리 새우 양식 시스템 abstract: 본 발명은 녹차, 녹차, 유청, 채종박, 채종유, 어유, 스테비아, 스피룰리나, 타우린, 모자반, 호밀 및 녹말을 포함하여 제조된 흰다리 새우 양식용 사료를 이용한 흰다리 새우 양식 시스템에 관련된 것으로서, 흰다리 새우 치어가 배양되는 치어 배양 수조; 바이오플락 양식을 위해 미생물을 증식시킨 사육수가 저장되고, 치어 배양부에서 배양된 흰다리 새우 치어를 입식시켜 기 설정된 주기마다 흰다리 새우 양식용 사료를 급여함으로써 흰다리 새우 치어를 성체로 양식하는 양식 수조; 양식 수조에서 수질 샘플을 채취하여, 채취된 수질 샘플에서 검출된 수질 정보를 수집하는 센서부; 및 센서부에서 수집되는 수질 정보를 이용하여 양식 수조의 양식 환경을 제어하는 양식 환경 제어부;를 포함하는 것을 특징으로 한다. claims: 녹차, 유청, 채종박, 채종유, 어유, 스테비아, 스피룰리나, 타우린, 모자반, 호밀 및 녹말을 포함하여 제조된 흰다리 새우 양식용 사료를 이용한 흰다리 새우 양식 시스템에 있어서,흰다리 새우 치어가 배양되는 치어 배양 수조;바이오플락 양식을 위해 미생물을 증식시킨 사육수가 저장되고, 상기 치어 배양 수조에서 배양된 흰다리 새우 치어를 입식시켜 기 설정된 주기마다 상기 흰다리 새우 양식용 사료를 급여함으로써 상기 흰다리 새우 치어를 성체로 양식하는 양식 수조; 상기 양식 수조에서 수질 샘플을 채취하여, 채취된 상기 수질 샘플에서 검출되는 수질 정보를 수집하는 센서부; 및상기 센서부에서 수집된 수질 정보를 이용하여 상기 양식 수조의 양식 환경을 제어하는 양식 환경 제어부;를 포함하되,상기 흰다리 새우 양식용 사료는,전체 흰다리 새우 양식용 사료 100중량%에 대하여, 상기 녹차 4.3 내지 5.8중량%, 상기 유청 17 내지 23중량%, 상기 채종박 10.2 내지 13.8중량%, 상기 채종유 6 내지 8.1중량%, 상기 어유 11.9 내지 16.1중량%, 상기 스테비아 8.5 내지 11.5중량%, 상기 스피룰리나 2.6 내지 3.5중량%, 상기 타우린 4.3 내지 5.8중량%, 상기 모자반 4.3 내지 5.8중량%, 상기 호밀 6 내지 8.1중량% 및 상기 녹말 10.2 내지 13.8중량%를 포함하고,상기 흰다리 새우 양식 시스템은,상기 양식 수조의 내부를 촬영하는 제1 카메라 모듈이 구비되어, 상기 제1 카메라 모듈을 통해 수집되는 제1 영상 데이터와 데이터베이스에 기 저장된 흰다리 새우의 기준 영상 데이터를 비교하여, 상기 양식 수조에서 양식되는 상기 흰다리 새우 치어의 활동성을 이동 속도, 이동 범위 및, 먹이 반응성 중 적어도 어느 하나를 포함하는 행동 패턴으로 분석함으로써 모니터링하는 제1 모니터링부; 및,상기 양식 수조에 저장된 사육수 표면을 촬영하는 제2 카메라 모듈이 구비되어, 상기 제2 카메라 모듈을 통해 수집되는 제2 영상 데이터에서, 기 학습된 부유물에 대응되는 색상이 검출될 시, 사육수 면적에서 부유물에 대응되는 색상이 검출된 면적을 연산하여 상기 사육수에 현탁하여 있는 고형 부유물의 발생량을 추정하는 제2 모니터링부;를 더 포함하는 것을 특징으로 하는 흰다리 새우 양식 시스템., Ltext: 어업, prediction: 임업
290/1059 Row 290: application_number: 1020200159150, combined_string: invention_title: 사료 급이 장치 abstract: 사료 급이 장치가 제공된다. 상기 사료 급이 장치는 사료가 저장된 저장부; 상기 저장부에 저장된 사료를 자동 배출하는 급이부;를 포함할 수 있다. claims: 양식장에 적용되는 사료 급이 장치에 있어서,사료가 저장된 저장부;상기 저장부에 저장된 사료를 자동 배출하는 급이부;를 포함하고,단말기와 통신하는 통신부가 마련되고,상기 급이부는 상기 통신부를 통해 제어 신호가 입수되면, 상기 사료를 배출하며,용존 산소량을 측정하는 측정부, 상기 급이부를 제어하는 조절부가 마련되고,상기 조절부는 상기 측정부에서 측정된 용존 산소량이 설정값을 만족하면, 상기 통신부를 통해 상기 제어 신호가 입수되더라도 상기 사료를 배출하지 못하도록 상기 급이부를 제어하는 사료 급이 장치., Ltext: 어업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

291/1059 Row 291: application_number: 1020200137539, combined_string: invention_title: 전복용 치패 양식판의 조립장치 abstract: 본 발명은 전복용 치패 양식판의 조립장치에 관한 것으로, 보다 상세하게는 다수 개의 양식판과 이격링을 삽입하고 조립봉으로 체결, 조립되도록 형성함으로써, 일정 간격으로 삽입, 정렬되어 고정된 상태의 다수 개의 양식판을 조립봉으로 용이하게 체결, 조립하기 때문에, 양식판의 조립 체결작업이 신속하고 간편할 수 있을 뿐만 아니라, 다수 개의 양식판이 일정 간격으로 정렬된 상태에서 조립봉을 이용하여 삽입, 고정되도록 함으로써, 양식판의 조립 및 결합 오차가 낮고 그 조립과정에서의 파손 및 손상을 미연에 방지할 수 있기 때문에, 불량률이 낮은 양식판 조립체에서 전복 치패의 안정적인 서식 및 양식 효율을 향상시킬 수 있도록 한 것이다. claims: 다수 개의 양식판을 연결, 조립하도록 하는 본체(10)와;다수 개의 양식판을 일정 간격으로 삽입, 지지하도록 상부 지지부와 하부 지지부로 구비된 조립부재(20)와;조립부재(20)의 상부 지지부(21)를 회동시키도록 하는 회동부재(30);로 형성하도록 구성되되,상기 조립부재(20)는 양식판이 일정 간격으로 삽입, 정렬되도록 형성하되, 양식판의 상부를 삽입하여 지지되도록 하는 상부 지지부(21)와, 양식판의 하부를 삽입하여 지지되도록 하는 하부 지지부(22)를 형성하도록 구성되고,상기 상부 지지부(21)와 하부 지지부(22)는,다수 개의 이격판(23)을 일정 간격으로 연결, 결합되도록 구비하여, 각 이격판 사이의 간격으로 양식판이 삽입되도록 형성하여 구성되며,상기 이격판(23)은 각 양식판의 간격을 유지하도록 하는 이격링이 요입되는 요입홈(23a)을 형성하되,양식판의 크기에 따라 조립할 수 있도록 다 수개의 요입홈(23a)을 구비하도록 형성하여 구성되는 것을 특징으로 하는 전복용 치패 양식판의 조립장치., Ltext: 어업, prediction: 임업
292/1059 Row 292: application_number: 1020200083233, combined_string: invention_title: 항공 수송용 활어 컨테이너 abstract: 항공기 내부 공간에 적재될 수 있는 규격의 다각형상의 바닥부를 일정 높이의 외벽이 둘러싸며 내부에는 사육수와 활어가 입식되는 내부 공간이 형성되는 수조본체; 상기 수조본체 어느 한 측면부에는 수조본체 환경을 조절하는 구동장치부가 설치되는 항공 수송용 활어 컨테이너를 제공함으로써, 환경에 민감한 살아있는 활어를 항공기로 수송이 가능하여 장거리의 지역에서도 높은 신선도의 수산 식품을 제공할 수 있을 뿐만 아니라 국내 수산물의 수출량을 증가시킬 수 있고, 항공수송시 피칭이 크고 빈도수가 많아 수조본체 내부에 저장된 사육수가 이동관을 따라 지그재그 형상으로 따라 흐르면서 피칭으로 생성된 사육수압이 이동하는 힘으로 전환됨에 따라 수압이 소산되어 수조본체 외부로 누수되는 것을 방지할 수 있는 효과가 있다. claims: 항공기 내부 공간에 적재될 수 있는 규격의 다각형상의 바닥부를 일정 높이의 외벽이 둘러싸며 내부에는 사육수와 활어가 입식되는 내부 공간이 형성되는 수조본체; 상기 수조본체 어느 한 측면부에는 수조본체 환경을 조절하는 구동장치부가 설치되어 이루어지는 것인 항공 수송용 활어 컨테이너, Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

293/1059 Row 293: application_number: 1020200046565, combined_string: invention_title: 스마트양식장 사료공급장치 및 이의 제어 방법 abstract: 스마트양식장 사료공급장치 및 이의 제어 방법이 개시된다. 이에 의하면, 양식 수조의 수면 영상과 내부환경정보 및 상기 양식 수조내의 서식 어류의 정보를 수신하는 입력부; 와, 어종별 사료섭취패턴 및 소화 기능을 학습하여 어종별 사료공급모델을 생성하는 학습부; 와, 상기 수면 영상을 분석하여 서식 어류가 사료 공급 개시 후 양식 수조에 최초로 투입되는 초기사료공급량을 소비하는 먹이행동패턴을 분석하는 분석부; 와, 양식 수조내에 소정량의 사료를 공급할 수 있도록, 사료 저장고에 밸브 개방 신호를 전송하는 사료 공급부; 및 어종별 사료공급모델 중에서 서식 어류에 대응하는 소정 사료공급모델을 선택하고, 소정 사료공급모델을 참조하여 초기사료공급량을 설정한 후, 사료 공급이 개시되면 초기사료공급량을 양식 수조내에 투입하도록 사료 공급부를 제어하고, 소정 사료공급모델 및 먹이행동패턴을 참조하여 서식 어류에의 단계별 공급 사료량을 결정한 후, 단계별 공급 사료량을 순차적으로 상기 양식 수조내에 투입하도록 사료 공급부를 제어하는 제어부를 포함한다. claims: 스마트양식장 사료공급장치에 있어서,양식 수조의 수면 영상과 내부환경정보 및 상기 양식 수조내의 서식 어류의 정보를 수신하는 입력부;어종별 사료섭취패턴 및 소화 기능을 학습하여 어종별 사료공급모델을 생성하는 학습부;상기 수면 영상을 분석하여, 상기 서식 어류가 사료 공급 개시 후 상기 양식 수조에 최초로 투입되는 초기사료공급량을 소비하는 먹이행동패턴을 분석하는 분석부;상기 양식 수조내에 소정량의 사료를 공급할 수 있도록, 사료 저장고에 밸브 개방 신호를 전송하는 사료 공급부; 및 상기 어종별 사료공급모델 중에서 상기 서식 어류에 대응하는 소정 사료공급모델을 선택하고, 상기 소정 사료공급모델을 참조하여 상기 초기사료공급량을 설정한 후, 사료 공급이 개시되면 상기 초기사료공급량을 상기 양식 수조내에 투입하도록 상기 사료 공급부를 제어하고, 상기 소정 사료공급모델 및 상기 먹이행동패턴을 참조하여 상기 서식 어류에의 단계별 공급 사료량을 결정한 후, 상기 단계별 공급 사료량을 순차적으로 상기 양식 수조내에 투입하도록 상기 사료 공급부를 제어하는 제어부를 포함하고,상기 학습부는,어류의 소화기관의 외부형태 및 조직학성 특성 중 적어도 하나에 기초하여 상기 어종별 사료섭취패턴 및 상기 소화 기능을 학습하는, 스마트양식장 사료공급장치., Ltext: 어업, prediction: 임업
294/1059 Row 294: application_number: 1020200040248, combined_string: invention_title: 자동 생먹이 공급기 abstract: 본 발명은 일정한 내부공간을 구비하여 상기 내부공간에 생물 먹이가 수용되도록 하는 몸통부와; 상기 생물 먹이의 공급량을 일정하게 조절하여 지속적으로 공급할 수 있도록 적정량의 물을 상기 몸통부의 상기 내부공간으로 공급하는 물 주입부와; 상기 몸통부의 상기 내부공간에 냉동 혹은 살아있는 생물 먹이를 균일한 밀도로 용해 혹은 각반시킬 수 있도록 하는 에어공급부와; 용해 또는 각반된 상기 생물 먹이를 사육조로 내보내는 먹이 배출구를; 포함하여 구성됨으로써, 대규모의 수중동물의 양식 산업시설에서 초기 부화 자어에서 상품이 성어가 되기 전까지의 양식 과정에서 생물 먹이(냉동생물 먹이 포함)를 안전하게 적정량으로 지속 공급하기 위한 장치를 개발하여 먹이의 절감과 노동력이 부족한 양식 현장의 생력화를 기하며 수질환경을 안정시켜 사육어를 건강하게 사육시켜 생존율을 높임으로서 경제적 양식을 실현할 수 있는 효과가 있다. claims: 일정한 내부공간(110)을 구비하여 상기 내부공간에 생물 먹이(1)이 수용되도록 하는 몸통부(100)와; 상기 생물 먹이(1)의 공급량을 일정하게 조절하여 지속적으로 공급할 수 있도록 적정량의 물을 상기 몸통부(100)의 상기 내부공간(110)으로 공급하는 물 주입부(200)와;상기 몸통부(100)의 상기 내부공간(110)에 냉동 혹은 살아있는 생물 먹이(1)을 균일한 밀도로 용해 혹은 각반시킬 수 있도록 하는 에어공급부(300)와;용해 또는 각반된 상기 생물 먹이(1)를 사육조로 내보내는 먹이 배출구(400)를; 포함한 것을 특징으로 하는 자동 생먹이 공급기., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

295/1059 Row 295: application_number: 1020200036815, combined_string: invention_title: 버블을 이용한 양식장의 적조방제 및 고수온 억제 장치 abstract: 본 발명은 버블을 이용한 양식장의 적조방제 및 고수온 억제 장치에 관한 것으로, 보다 상세하게는 양식장의 외측에 설치된 버블 생성부를 통해 버블막을 형성하여 양식장 내로 적조가 유입되는 현상을 방지할 수 있으면서 양식장의 하측에 설치된 버블 생성부에서 배출된 버블을 이용하여 수면에 비해 상대적으로 저온인 바닷물을 수면으로 상승시켜 양식장의 수온 상승을 억제할 수 있는 양식장의 적조방제 및 고수온 억제장치에 관한 것이다.이러한 본 발명은, 공기를 압축하는 압축공기 생성부(10); 양식장의 외측을 둘러싸는 형태로 수중에 설치되고, 상기 압축공기 생성부(10)에서 생성된 압축공기를 수중으로 배출하며 수면을 향해 부상하는 버블을 양식장(60) 외측을 둘러 생성하여 양식장(60) 내로 적조의 유입을 방지하는 제1버블 생성부(20a); 상기 양식장(60) 하측으로 수면보다 수온이 3℃ 이하 낮은 수심상에 배치되고, 상기 압축공기 생성부(10)에서 생성된 압축공기를 배출하여 양식장(60)을 향해 부상하는 버블을 생성하고 수면보다 상대적으로 낮은 온도의 바닷물을 수면으로 상승시켜 수면의 온도를 낮추는 제2버블 생성부(20b);를 포함하여 이루어진다. claims: 복수의 부표(61)와, 상기 부표(61)를 연결하며 결합되는 파이프(62)와, 수중에 설치되는 그물(64)을 포함하여 이루어지는 양식장(60)에 설치되는 적조방제 및 고수온 억제 장치에 있어서,공기를 압축하는 압축공기 생성부(10);상기 양식장(60)의 외측을 둘러싸는 형태로 수중에 설치되고, 상기 압축공기 생성부(10)에서 생성된 압축공기를 수중으로 배출하며 수면을 향해 부상하는 버블을 양식장(60) 외측을 둘러 생성하여 양식장(60) 내로 적조의 유입을 방지하는 제1버블 생성부(20a);상기 양식장(60) 하측으로 수면보다 수온이 3℃ 이하 낮은 수심상에 배치되고, 상기 압축공기 생성부(10)에서 생성된 압축공기를 배출하여 양식장(60)을 향해 부상하는 버블을 생성하고 수면보다 상대적으로 낮은 온도의 바닷물을 수면으로 상승시켜 수면의 온도를 낮추는 제2버블 생성부(20b);를 포함하고,상기 압축공기 생성부(10)에서 상기 제1버블 생성부(20a)와 제2버블 생성부(20b) 중 하나 이상으로 압축공기의 공급은 각각의 경로를 선택적으로 개폐함에 의해 제어되는 것을 특징으로 하는 버블을 이용한 양식장의 적조방제 및 고수온 억제 장치., Ltext: 어업, prediction: 어업
296/1059 Row 296: application_number: 1020200036300, combined_string: invention_title: 픽티바실러스 속 균주 또는 이의 배양액을 유효성분으로 포함하는 적조 방제용 조성물 abstract: 본 발명은 코클로디니움 폴리크리코이데스 (Cochlodinium polykrikoides)를 포함하는 와편모조류에 대해 살조 활성을 가지는 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주, 배양액 또는 이로부터 분리한 화합물 및 이의 용도에 관한 것으로, 보다 상세하게는 본 발명의 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주는 유해 적조생물인 코클로디니움 폴리크리코이데스 (Cochlodinium polykrikoides)를 포함하는 와편모조류에 대해서만 선택적으로 살조 활성을 나타내기 때문에 적조 제어시 수생태계의 교란을 최소화할 수 있으며, 균주를 직접 처리하지 않고 배양액을 처리하더라도 비교적 안정적으로 살조 활성을 유지하므로, 국내 양식장에 큰 피해를 입히는 코클로디니움 폴리크리코이데스 (Cochlodinium polykrikoides)를 포함하는 와편모조류를 살조하는데 더욱 유용하게 사용될 수 있다. claims: 살조 활성을 가지는 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주.제1항 내지 제4항 중 어느 한 항의 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주, 이의 배양액 또는 이의 배양여액을 유효성분으로 포함하는 적조 방제용 조성물픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주로부터 분리한 L-페닐알라닌 또는 안트라닐산을 유효성분으로 포함하는 적조 방제용 조성물제1항 내지 제4항 중 어느 한 항의 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주, 이의 배양액 또는 이의 배양여액의 유효량을 적조 발생 지역에 처리하는 단계를 포함하는 적조를 방제하는 방법픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주로부터 분리한 L-페닐알라닌 또는 안트라닐산의 유효량을 적조 발생 지역에 처리하는 단계를 포함하는 적조를 방제하는 방법픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주를 배양하는 단계를 포함하는 적조 방제용 조성물의 제조 방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

297/1059 Row 297: application_number: 1020200034466, combined_string: invention_title: 부유형 공기 공급장치 abstract: 호수나 양식장 등의 수중에 공기를 공급하여 수중 생물의 서식환경을 개선시킬 수 있는 부유형 공기 공급장치가 개시된다. 이를 위하여 공기탱크의 기능을 제공하도록 내부에 공기가 수용되는 중공이 구비된 블록형 구조로 형성되고, 내부에 수용된 공기를 외부로 배출하는 연통구가 표면에 형성되며, 수면 위를 부유하는 부유체와, 상기 부유체에 설치되어 공기를 흡입하는 공기펌프, 및 상기 공기펌프에 연결되어 부유체의 내부로 공기를 주입하는 흡기관을 포함하는 공기흡입부와, 상기 부유체의 측면에 설치되어 부유체에 부력을 보조하는 부력체, 및 상기 부유체의 내부와 수중을 연결하여 부유체의 내부에 수용된 공기를 수중으로 배출시키는 공기배출부를 포함하는 부유형 공기 공급장치를 제공한다. 본 발명에 의하면, 산소가 필요한 지점에 바로 설치하여 불필요한 배관을 설치할 필요가 없기 때문에 공기 공급장치의 제작비용을 절감할 수 있으며, 공기의 이동경로를 제공하는 배관의 총 길이가 기존 공기 공급장치보다 짧아지므로 공기의 이동에 따른 마찰손실이 줄어들어 에너지 효율을 극대화시킬 수 있다. claims: 공기탱크의 기능을 제공하도록 내부에 공기가 수용되는 중공이 구비된 블록형 구조로 형성되고, 내부에 수용된 공기를 외부로 배출하는 연통구가 표면에 형성되며, 수면 위를 부유하는 부유체; 상기 부유체에 설치되어 공기를 흡입하는 공기펌프, 및 상기 공기펌프에 연결되어 부유체의 내부로 공기를 주입하는 흡기관을 포함하는 공기흡입부;상기 부유체의 측면에 설치되어 부유체에 부력을 보조하는 부력체; 및상기 부유체의 연통구에 결합되어 부유체의 내부에 수용된 공기를 수중으로 배출시키는 공기배출부를 포함하는 부유형 공기 공급장치., Ltext: 어업, prediction: 임업
298/1059 Row 298: application_number: 1020200033484, combined_string: invention_title: 미생물을 활용한 양식방법 abstract: 본 발명의 일 실시예에 따른 미생물을 활용한 양식방법은, 양식수조, 상기 양식수조 내에 수용된 사육수를 정화하는 정화장치 및 상기 정화장치에서 정화된 사육수에 공기를 혼합하여 용해하는 용해장치를 포함하는 미생물 양식시스템에 적용된 미생물을 활용한 양식방법에 관한 것이다. claims: 양식수조, 상기 양식수조 내에 수용된 사육수를 정화하는 정화장치 및 상기 정화장치에서 정화된 사육수에 공기를 혼합하여 용해하는 용해장치를 포함하며,상기 양식수조는 상부가 개구되고 바닥과 외벽이 구비된 수용부; 상기 수용부의 중심에 회전 가능하도록 배치되고 내부에 재공급 유로가 형성되는 회전로드; 일측이 상기 회전로드의 외주면과 연통되도록 결합되되, 내부에는 상기 재공급 유로와 연결된 서브유로가 형성되고, 측면에는 복수 개의 공급공이 형성되는 적어도 하나의 정화수 재공급유닛; 상기 수용부의 외벽 내측에 부착된 이물질을 제거하기 위하여 상기 정화수 재공급유닛의 타측에 배치된 브러시유닛;을 포함하며,상기 수용부 측벽에는 투명창부가 구비되되, 상기 투명창부의 수용부 내측으로는 격자망 형태의 메시부가 구비되며,상기 투명창부에 대응되는 위치로 상기 수용부 내부에는 램프부가 구비되며,상기 정화장치는 상기 양식수조에서 배출된 사육수의 고형 이물질을 제거하는 가압부상모듈; 고형 이물질이 제거된 사육수에 포함된 질소성분을 제거하는 탈질모듈; 질소성분이 제거된 사육수를 중공사막필터를 이용하여 정화하는 중공사막모듈; 중공사막모듈을 통과한 사육수를 여과막을 이용하여 여과하는 막정화모듈; 및 상기 탈질모듈의 탈질과정에서 발생된 오염공기를 탈취하는 탈취모듈;을 포함하고,상기 탈취모듈은 내부 중공된 박스 형태의 외부케이스와, 상기 외부케이스의 일측 하부에 상기 탈질모듈과 연결되게 구비되는 연결관과, 상기 외부케이스 타측 상부에 구비되는 공기배출부를 포함하며,상기 외부케이스는 내측에 상하로 다수 개의 격벽부가 구비되되, 상기 격벽부는 각각 일측과 타측이 상기 외부케이스로부터 이격된 상태를 이루어 하부로부터 상측 상기 공기배출부까지 지그재그방식으로 공기가 유동 가능하도록 구성되며,최하단에 구비된 격벽부는 상기 외부케이스와 이격된 부위를 개폐하는 경로차단부가 구비되며, 상기 각 격벽부는 소정 이격된 간격마다 탈취유닛이 설치되는,미생물 양식시스템에 적용된 미생물을 활용한 양식방법에 있어서,상기 양식수조 내에 양식생물, 사료, 미생물 및 사육수를 공급하는 단계;상기 사육수의 오염정도에 기초하여 상기 양식수조 내에 수용된 사육수를 배출하는 단계;상기 정화장치가 상기 양식수조에서 배출된 사육수를 정화하는 단계;상기 용해장치가 상기 정화장치에 의하여 정화된 정화수에 공기를 혼합하여 용해하는 단계; 및상기 공기가 용해된 사육수를 상기 양식수조에 재공급하는 단계;를 포함하는 미생물을 활용한 양식방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

299/1059 Row 299: application_number: 1020200024803, combined_string: invention_title: 수생물 보호블럭을 이용한 양식장의 모니터링 관리시스템 및 그 방법 abstract: 본 발명은 친환경적인 수생물 보호블럭을 적용하여 수중 식물 및 어류의 서식 활동을 돕고, 각종 센서들이 보호블럭 수생군락에 설치되어 서식 온도, 해류 및 일조량의 조건에 따른 개체수의 증감 변화를 쉽게 파악할 수 있도록 하고, 자가발전을 통해 각종 센서들의 센싱구동이 가능하여 측정 오차를 줄일 수 있고, 수중중계기에 의해 외부에서 안전하게 어류의 생태 환경을 감시 개량해 나갈 수 있도록 한 수생물 보호블럭을 이용한 양식장의 모니터링 관리시스템 및 그 방법을 제공한다. 본 발명의 적절한 실시 형태에 따른 수생물 보호블럭을 이용한 양식장의 모니터링 관리시스템은, 다수의 수생물 보호블럭들이 상호 결합되어져 연결수단을 통해 양식장에 분포 배치된 보호블럭 수생군락과; 해당 보호블럭 수생군락에 각기 배치되어 수온, 해류, 일조량, 어군을 감지하여 해당 감지 신호를 출력하는 서식환경 감지부와; 양식장의 수면에 부상되어 상기 환경감지부로부터 검출된 신호를 수신하고 데이타 처리하여 양식장의 관리자 또는 운영자의 외부 단말기로 송신하는 수중중계기와; 상기 수중중계기에 장착되어 자가 발전으로 수중중계기를 구동시키는 발전유닛;을 포함한 것을 특징으로 한다. claims: 다수의 수생물 보호블럭(20)들이 상호 결합되어져 연결수단(5)을 통해 양식장에 분포 배치된 보호블럭 수생군락(201~207)과;해당 보호블럭 수생군락(201~207)에 각기 배치되어 수온, 해류, 일조량, 어군을 감지하여 해당 감지 신호를 출력하는 서식환경 감지부(300)와;양식장의 수면에 부상되어 상기 환경감지부(300)로부터 검출된 신호를 수신하고 데이타 처리하여 양식장의 관리자 또는 운영자의 외부 단말기(600)로 송신하는 수중중계기(400)와;상기 수중중계기(400)에 장착되어 자가 발전으로 수중중계기(400)를 구동시키는 발전유닛(500);을 포함한 것을 특징으로 하는 수생물 보호블럭을 이용한 양식장의 모니터링 관리시스템.다수의 수생물 보호블럭(20)들이 상호 결합되어져 보호블럭 수생군락(201~207)을 이루도록 한 후, 연결수단(5)을 통해 양식장에 보호블럭 수생군락(201~207)을 분포 배치시키는 단계와;부양체(420), 부양체(420)에 고정되어 있는 수중중계기 함체(410), 수중중계기 함체(410)에 탑재된 측정검출부(430), 측정검출부(430)에서 검출된 데이타를 실시간으로 처리하여 송신모듈(450)로 전송시키기 위한 수중중계기 제어부(440)를 포함한 수중중계기(400)를 수상에 배치시켜 놓는 단계와;상기 보호블럭 수생군락(201~207)에 배치된 온도 감지센서(310), 해류 감지센서(320), 일조량 감지센서(330), 어군 감지센서(340)로부터 해당 감지 신호를 수중중계기(400)의 측정검출부(430)로 송출시키는 단계와;상기 측정검출부(430)에 의해 검출된 온도, 해류, 일조량 및 어군 데이타를 실시간으로 송신모듈(450)을 통해 외부 단말기(600)로 송출시키는 단계;를 포함한 것을 특징으로 하는 수생물 보호블럭을 이용한 양식장의 모니터링 관리 방법., Ltext: 어업, prediction: 임업
300/1059 Row 300: application_number: 1020200021150, combined_string: invention_title: 상황버섯 추출액을 이용한 장어 사료 제조방법 abstract: 본 발명은 상황버섯 추출액을 이용한 장어 사료 제조방법에 관한 것으로서, 장어의 양식에 있어서 면역력을 증대시켜 항생제를 사용하지 않고 양식할 수 있도록 함을 목적으로 한 것이다.즉, 본 발명은 장어 사료 제조방법에 있어서, 상황버섯을 분쇄가 용이하게 건조하는 상황버섯건조과정과 상기 상황버섯건조과정을 통하여 건조된 상황버섯을 270매쉬 이상의 크기로 상황버섯분말로 분쇄하는 상황버섯분쇄과정, 상황버섯분말을 90℃의 온도로 열처리하는 상황버섯분말열처리과정, 상기 상황버섯분말열처리과정을 통하여 열처리되어 열이 축열된 상황버섯분말을 상온의 온도로 냉각하는 상황버섯분말냉각과정, 상기 상황버섯분말에 90℃의 물과 혼합하여 상황믹싱수를 제조하는 상황버섯온수믹싱과정, 상기 상황믹싱수를 100℃의 온도로 6시간 가열하는 상황믹싱수가열과정, 상기 상황믹싱수를 270매쉬의 여과지를 통과시켜 상황수추출물을 추출하는 상황수추출과정, 상기 상황수추출물을 이용하여 어육과 대맥분말 또는 소맥분말을 믹싱하여 장어사료반죽제조과정, 상기 장어사료장어사료반죽제조과정을 제조된 장어사료반죽을 일정크기로 압출하는 장어사료알갱이제조과정, 상기 장어사료알갱이제조과정을 건조하는 알갱이건조과정을 이루어진 것을 특징으로 하는 것이다.따라서, 본 발명은 장어의 양식에 있어서 장어의 면역력을 증대시켜 항생제를 사용하지 않고 양식할 수 있는 효과를 갖는 것이다. claims: 장어 사료 제조방법에 있어서;상황버섯을 분쇄가 용이하게 건조하는 상황버섯건조과정과 상기 상황버섯건조과정을 통하여 건조된 상황버섯을 270매쉬 이상의 크기로 상황버섯분말로 분쇄하는 상황버섯분쇄과정, 상황버섯분말을 90℃의 온도로 열처리하는 상황버섯분말열처리과정, 상기 상황버섯분말열처리과정을 통하여 열처리되어 열이 축열된 상황버섯분말을 상온의 온도로 냉각하는 상황버섯분말냉각과정, 상기 상황버섯분말에 90℃의 물과 혼합하여 상황믹싱수를 제조하는 상황버섯온수믹싱과정, 상기 상황믹싱수를 100℃의 온도로 6시간 가열하는 상황믹싱수가열과정, 상기 상황믹싱수를 270매쉬의 여과지를 통과시켜 상황수추출물을 추출하는 상황수추출과정, 상기 상황수추출물을 이용하여 어육과 대맥분말 또는 소맥분말을 믹싱하여 장어사료반죽제조과정, 상기 장어사료장어사료반죽제조과정을 제조된 장어사료반죽을 일정크기로 압출하는 장어사료알갱이제조과정, 상기 장어사료알갱이제조과정을 건조하는 알갱이건조과정을 이루어진 것을 특징으로 하는 상황버섯 추출액을 이용한 장어 사료 제조방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

301/1059 Row 301: application_number: 1020200010429, combined_string: invention_title: 관상어 치어의 입식을 위한 수질환경 조성방법 abstract: 본 발명은 비단잉어 및 금붕어 관상어 치어를 양식장에 입식 하기 전처리하여 치어의 안정적인 성장을 위한 양식장 수질환경을 조성하는 방법에 관한 것으로 더욱 상세하게는 치어의 먹이원인 물벼룩을 채집하여 수조에 투입하는 물벼룩 투입단계, 물벼룩을 배양시키기 위해 건조된 배양재료를 수조에 투입하는 준비단계, 상기 준비단계 후 산소용존량과 pH와 수온을 측정하면서 물벼룩을 배양하는 배양단계 및 상기 배양단계를 마친 후 관상어 치어를 입식하는 입식단계로 이루어지는 관상어 치어의 입식을 위한 수질환경 조성방법에 관한 것이다.이상에서 설명한 바와 같이 본 발명에 의한 관상어 치어의 입식을 위한 수질환경 조성방법은 관상어 치어 입식 전 치어의 먹이원인 물벼룩을 배양시켜 안정적으로 물벼룩을 제공함으로써 치어의 생장을 돕고, 수질 측정과 물벼룩 배양시 사용되는 배양재료에 따라 관상어 치어의 입식시기를 결정하여 관상어 치어의 성장률을 높이며, 해외에 의존하고 있는 사료를 사용하지 않아 치어 생장에 드는 비용을 절감시키고, 그 과정도 단순화하여 치어 생육이 간단히 이루어질 수 있다. claims: 관상어 치어를 입식하기 전 수질환경 조성방법에 있어서,상기 수질환경 조성방법은 a) 치어의 먹이원인 물벼룩을 채집하여 수조에 투입하는 물벼룩 투입단계;b) 물벼룩을 배양시키기 위해 건조된 배양재료를 수조에 투입하는 준비단계;c) 상기 준비단계 후 산소용존량과 pH와 수온을 측정하면서 물벼룩을 배양하는 배양단계; 및d) 상기 배양단계를 마친 후 관상어 치어를 입식하는 입식단계;로 이루어지는 것을 특징으로 하는 관상어 치어의 입식을 위한 수질환경 조성방법., Ltext: 어업, prediction: 임업
302/1059 Row 302: application_number: 1020217023207, combined_string: invention_title: 수산양식용 프로바이오틱 먹이 abstract: 본 발명은 양식된 수생 동물에게 먹이원으로서 비브리오 미대 SY9를 공급하는 단계를 포함하는 수산양식 방법을 제공한다. 또한 비브리오 미대 SY9를 포함하는 먹이 조성물이 제공된다. 상기 수생 동물은 전형적으로 조류를 먹는 해양 동물이다. 이들은 전복 및 극피동물, 예컨대 성게, 해삼, 불가사리, 거미 불가사리, 연잎 성게류 및 바다나리류를 포함한다. 상기 비브리오 미대 SY9는 지지체 상에 형성된 알긴산염 막 상에 또는 내에 제공될 수 있다. claims: 수생 동물의 수산양식 방법으로서, 수생 동물에게 먹이원으로서 적어도 비브리오 미대 SY9를 공급하는 단계를 포함하는 방법.수생 동물의 사료용으로 제제화된 먹이 조성물로서, 주요 먹이원으로서 비브리오 미대 SY9를 포함하는 먹이 조성물., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

303/1059 Row 303: application_number: 1020190168422, combined_string: invention_title: 디지털 트윈 스마트 어항 플랫폼 서비스 기술 abstract: 본 발명은 디지털트윈 기술(현실세계 제품의 형상, 기능, 운전조건(센서와 연계) 등을 실제와 완전히 동일한 디지털(사이버) 모델로 구현하고 지능형 통합시뮬레이션(Intelligent Multi-Physics Simulation)을 통해 제품 거동, 결함, 수명 등의 복잡한 미래 특성을 정밀 예측·분석하기 위한 차세대 제품개발 기술 및 확장 기술)을 이용하여 고가의 열대어 양식 사업자 또는 집에서 열대어를 키우는 사용자들이 이용 가능한 스마트 어항에 대한 플랫폼 서비스를 제공하는 것을 특징으로 한다. claims: 열대어를 키우는 어항에 여과기, 조명, 히터, 온도측정기, 조명, 카메라 및 센서가 연결되어 조건이 변화됨에 따른 변화를 인지하고 디지털 트윈으로 정보를 전달하는 것을 특징으로 한다., Ltext: 어업, prediction: 어업
304/1059 Row 304: application_number: 1020190164300, combined_string: invention_title: 다영양 입체양식을 이용한 해조류와 우렁쉥이의 복합양식방법 abstract: 우렁쉥이와 해조류를 복합적으로 양성하는 생태통합양식장치를 이용한 복합양식방법을 제공함으로써 동물과 식물양식의 수질개선 기반의 복합양식으로 상부의 해조류양식을 통해 수질개선과 해조류생산을 유도하고, 하부의 우렁쉥이 양식은 개선된 수질양식의 효과를 통해 동물양식에서 발생하기 쉬운 질병발생 및 오염과부하를 감소시킬 수 있어 친환경적인 양식이 가능함으로 양식어장의 오염저감, 안전, 안심 수산물의 안정적 생산 공급과 양식수산물의 부가가치 극대화 및 수산업의 미래 산업화를 통한 신성장 동력을 창출할 수 있는 효과가 있다. claims: 설정된 해역 해저면에 고정 설치되는 다수개의 계류장치; 상기 계류장치 일단과 연결 설치되고 타단은 우렁쉥이 양성로프와 연결되는 계류로프; 상기 계류로프 일단과 양단이 연결되어 해중에 수평하게 설치되는 우렁쉥이 양성로프; 상기 우렁쉥이 양성로프에는 수하식으로 하나 이상의 우렁쉥이 채묘장치가 일정 간격 이격되어 설치되며; 상기 우렁쉥이 양성로프 및 계류로프와 연결되는 해조류 고정로프; 상기 해조류 고정로프와 수평으로 연결되는 해조류 양성장치; 상기 해조류 고정로프에는 복수개의 부력장치가 코너플래이트를 매개로 연결되어 이루어지는 것인 생태통합양식장치생태통합양식을 실시할 해역을 정하고 생태통합양식장치 설치를 준비하는 단계(가); 부화한 우렁쉥이 유생이 입식된 채묘 수조에 유생을 우렁쉥이 채묘장치에 부착시킨 후, 상기 (가)단계의 생태통합양식장치의 우렁쉥이 양성로프에 4월 내지 6월까지 연결 설치하는 우렁쉥이 채묘장치 설치단계(나);상기 (나)단계를 거친 후, 수온이 22℃ 이하로 하강하는 시기에 해조류 양성로프 설치를 시작하여 이듬해 2월까지 로프 설치를 실시하는 해조류 양성로프 설치단계(다);상기 (다)단계를 거친 후 상기 (나)단계를 기준으로 3년차까지 우렁쉥이와 해조류를 복합적으로 양성하는 복합양성단계(라)로 이루어진 것인 생태통합양식장치를 이용한 복합양식방법, Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

305/1059 Row 305: application_number: 1020190149264, combined_string: invention_title: 통합 컨트롤 및 실시간 모니터링이 가능한 비바리움 유리 사육장 abstract: 본 발명은 파충류나 양서류를 사육하는 사육장에 있어서, 애완동물이 사육하지 좋은 환경을 제공하는 것을 목적으로 하는 것으로서 즉, 사육공간을 갖는 몸체케이스, 외부 일측에 부착되어 몸체케이스 내부로 물을 순환공급하는 순환물공급장치, 상부덮개부로 구성하고, 상기 상부덮개부 하단에 UV램프부, 순환물공급장치의 물을 사육공간으로 안개로 분사하는 안개분사부, 쿨링팬부 및 사육공간을 측정하는 환경감지센서부와 상기 몸체케이스 내부 사육환경을 조절하는 제어장치부, 상기 제어장치부를 조작하는 모니터링조작장치부로 구비하고, 상기 순환물공급장치는 조절된 온도의 물을 공급하는 수중펌프부와 일측에 물을 정화하는 물정화장치부를 구비하며, 상기 복수의 사육장을 원격으로 관리하는 사육장원격조작시스템을 구비하여, UV램프부, 쿨링팬부 및 안개분사구로 인하여 사육장내부에 온도, 공기, 습도를 조절하며, 특히 상기 안개분사구의 경우 상기 순환물공급장치로 인하여 여과된 물을 분사하여 가습시 오염을 방지하며, 상기 순환물공급장치와 물정화장치부로 인하여 물을 여과하며 순환시키며, 적정한 온도의 물을 공급하여 사육장내부에 물의 관리에 편리성이 증대되며, 복수의 사육장을 사육장원격조작시스템으로 원격으로 관리하여 사육환경의 관리를 손쉽게 하는 효과를 갖는 통합 컨트롤 및 실시간 모니터링이 가능한 비바리움 유리사육장에 관한 것이다. claims: 파충류 및 양서류를 사육하는 유리사육장에 있어서,내부에 사육공간을 갖는 몸체케이스(1), 상기 몸체케이스(1) 외부 일측에 부착되어 몸체케이스(1) 내부로 물을 순환공급하는 순환물공급장치(100), 상기 몸체케이스(1) 상단에 몸체케이스(1)를 덮는 상부덮개부(300), 상기 상부덮개부(300) 하단에 발광하여 열을 공급하는 UV램프부(310), 습도를 조절하는 습기를 공급하는 안개분사부(320), 환기 및 쿨링하는 쿨링팬부(330), 사육공간의 온습도를 측정하는 환경감지센서부(340), 상기 몸체케이스(1) 내부 사육환경을 조절하는 제어장치부(400), 상기 제어장치부(400)를 조작하는 모니터링조작장치부(500)로 구비하고,상기 순환물공급장치(100)는 몸체케이스(1) 하부내부와 공급통로(251)로 연결되어 공급되는 물을 저장하는 보관수조구(110), 상기 보관수조구(110) 내부에 수온을 조절하는 수중히터구(120) 및 수온을 측정하는 수온측정구(130)를 구비하고,상기 안개분사부(320)는 상기 보관수조구(110)의 물을 끌어 분사하도록 일단이 보관수조구(110)에 연결된 관형으로 구비하고, 상부덮개부(300)측에 안개가 분사되는 분사노즐(321)을 구비하고,상기 제어장치부(400)는 무선으로 정보를 송수신하는 외부통신구(410)를 구비하고,PC 또는 스마트 기기에 상기 외부통신구(410)의 신호를 통신장치로 송수신하여 사육환경을 모니터링하며, 제어장치부(400)를 원격으로 조작하는 사육장원격조작시스템(600)을 구비하고,상기 사육장원격조작시스템(600)은 복수의 유리사육장을 통합하여 연결관리하는 멀티통합관리시스템을 구비하는 통합 컨트롤 및 실시간 모니터링이 가능한 비바리움 유리사육장., Ltext: 어업, prediction: 임업
306/1059 Row 306: application_number: 1020190149510, combined_string: invention_title: 경사배양대를 이용한 민물김의 양식 방법 abstract: 본 발명은 민물김을 성숙시켜 포자를 얻고 상기 포자를 생장시켜 민물김을 얻을 수 있는 민물김의 양식 방법에 대한 것으로, 더욱 상세하게는 포자생장시 특정 단계에서 유속의 부여시 경사배양대를 이용하여 용이하게 대량으로 민물김을 얻을 수 있는 민물김의 양식 방법에 대한 것이다. claims: 민물김을 성숙시켜 포자 방출을 유도하여 포자를 얻는 포자수득단계와, 상기 포자수득단계에서 얻은 포자를 생장시켜 민물김을 얻는 포자생장단계를 포함하며,상기 포자생장단계에서는 특정 시기에 유속을 부여하여야 포자를 생장시켜 민물김을 얻을 수 있으며, 상기 포자생장단계에서 유속의 부여시 경사배양대를 이용하는 것을 특징으로 하는 민물김의 양식 방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

307/1059 Row 307: application_number: 1020190143552, combined_string: invention_title: 양식장 순환수 처리장치 abstract: 양식장 순환수 처리장치가 개시된다. 개시되는 양식장 순환수 처리장치는, 양식장에서 배출되는 양식장 배출수를 유입시켜 상기 양식장 배출수 내에 존재하는 인 및 질소를 스트루바이트(struvite) 결정화시켜 배출하고, 스트루바이트 결정화 이후의 처리수를 배출하는, 스트루바이트 결정화부(110), 상기 스트루바이트 결정화부에서 배출되는 상기 스트루바이트 결정화 이후의 처리수를 유입시켜 상기 스트루바이트 결정화 이후의 처리수 내에 포함된 부유물질을 기포를 이용하여 부상 분리시켜 제거하고, 부유물질 제거 이후의 처리수를 배출하는, 부유물질 제거부(120), 및 상기 부유물질 제거부에서 배출되는 상기 부유물질 제거 이후의 처리수를 유입시켜 상기 부유물질 제거 이후의 처리수 내에 포함된 유기물을 제거하고, 유기물 제거 이후의 최종 처리수를 양식장으로 다시 공급하여 순환시키는 생물막 반응부(130)를 포함하여, 영양염류(N, P), 부유물질 및 유기물들을 효율적으로 처리할 수 있다. claims: 양식장 순환수 처리장치로서,양식장에서 배출되는 양식장 배출수를 유입시켜 상기 양식장 배출수 내에 존재하는 인 및 질소를 스트루바이트(struvite) 결정화시켜 배출하고, 스트루바이트 결정화 이후의 처리수를 배출하는, 스트루바이트 결정화부(110);상기 스트루바이트 결정화부에서 배출되는 상기 스트루바이트 결정화 이후의 처리수를 유입시켜 상기 스트루바이트 결정화 이후의 처리수 내에 포함된 부유물질을 기포를 이용하여 부상 분리시켜 제거하고, 부유물질 제거 이후의 처리수를 배출하는, 부유물질 제거부(120); 및상기 부유물질 제거부에서 배출되는 상기 부유물질 제거 이후의 처리수를 유입시켜 상기 부유물질 제거 이후의 처리수 내에 포함된 유기물을 제거하고, 유기물 제거 이후의 최종 처리수를 양식장으로 다시 공급하여 순환시키는 생물막 반응부(130);를 포함하는 것을 특징으로 하는 양식장 순환수 처리장치., Ltext: 어업, prediction: 임업
308/1059 Row 308: application_number: 1020217012550, combined_string: invention_title: 활어 선별 장치 (SORTING DEVICE FOR LIVE FISH) abstract: 알려진 선별 장치(sorting device)는 복수의 슬릿 구멍(slit opening)들을 포함하는 수직의 그리드 유닛(grid unit)으로 구성되고, 그 크기는 어류에 적합하고 그리고 어류가 자발적으로 헤엄칠 수 있다. 가능한 적은 스트레스를 유발하는 슬릿 구멍들(07)의 크기 조정을 위해, 본 발명에 따른 선별 장치(01)는 슬릿 구멍들(07)의 배열 및 크기를 동일하게 가지는 최소의 캐리어 플레이트(carrier plate)(15) 및 조정 플레이트(adjustment plate)(16)을 가진다. 조정 플레이트(16)는 조정 플레이트(16) 상의 수평 또는 수직의 웹들(08, 09)이 덮이거나 또는 드러나도록, 유효 슬릿 구멍(effective slit opening)들(07e)이 형성되는 캐리어 플레이트(15) 상의 슬릿 구멍들(07)이 그들의 위치 상에 있도록 하기 위해 캐리어 플레이트(15)상에 이동 가능한 방식으로 배열된다. 측면 이동성이 있는 경우, 유효 슬릿 구멍들(07e)의 폭만 조정되고, 그리고 높이는 변함없이 유지된다. 청구된 선별 장치(01)는 고정된 그리드 유닛(03)에서의 스트레스 없는 자발적인 자체 선별, 또는 양식의 넙치류 생선의 물 탱크(02)에서 움직이는 그리드 유닛(03)에서의 낮은 스트레스의 능동적인 선별에 특히 적합하다. claims: 활어(live fish)의 선별 장치(sorting device)(01)에 있어서, 상기 선별 장치는,위쪽을 향해 열리는 물 탱크(02); 및주변의(circumferential) 밀봉 엘리먼트(sealing element)(06)를 통해 상기 물 탱크(02)의 내부에 연결되고, 상기 물 탱크(02)를 2개의 분리된 영역들(04,05)로 나누고, 복수의 슬릿 구멍(slit opening)들(07)을 가지는 수직의 그리드(grid) 유닛(03) -상기 복수의 슬릿 구멍들은 수평 및 수직의 웹(web)들(08, 09)로 범위가 정해지고, 선별되는 상기 활어의 모양 및 사이즈로 조절되고, 이들에 대해 폐쇄됨-; 을 포함하고,상기 그리드 유닛(03)은 적어도 하나의 캐리어 플레이트(carrier plate)(15) 및 적어도 하나의 조정 플레이트(adjustment plate)(16)로 구성되고 -상기 적어도 하나의 캐리어 플레이트(15) 및 상기 적어도 하나의 조정 플레이트(16)는 동일한 디자인과 배열의 상기 슬릿 구멍들(07) 및 상기 수평 및 수직의 웹들(08,09)을 가짐-,상기 캐리어 플레이트(15)는 상기 물 탱크(02)를 상기 2개의 영역들(04, 05)로 나누고,상기 조정 플레이트(16)는 상기 캐리어 플레이트(15) 상에서 옮길 수 있게(displaceably) 배열되고, 그리고상기 조정 플레이트(16)의 위치에 따라, 상기 캐리어 플레이트(15)의 상기 슬릿 구멍들(07)은 상기 조정 플레이트(16)의 상기 수평 및 수직의 웹들(08, 09)로 커버되고(covered), 최대값(MAX)과 최소값(MIN) 사이의 유효(effective) 슬릿 구멍들(07e)이 형성되고,상기 캐리어 플레이트(15) 상의 상기 유효 슬릿 구멍들(07e)은 상기 최대값에서 완전히 열리고, 선별되는 상기 활어가 사이로 헤엄치지는 것을 방지하는 정도까지 상기 최소값으로 닫히는,선별 장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

309/1059 Row 309: application_number: 1020217016436, combined_string: invention_title: 동물 세포 증식 촉진제, 동물 세포 배양용 배지 및 동물 세포 배양 장치 abstract: 본 발명은, 신규한 동물 세포 증식 촉진제를 제공하는 것을 목적으로 한다. 구체적으로는, 조류 또는 파충류 알의 배아막의 배양 상등액을 동물 세포 증식 촉진제로 사용한다. 예를 들어, 동물 세포 배양용 배지에 조류 또는 파충류 알의 배아막의 배양 상등액을 유효성분으로 함유하는 세포 증식제를 첨가함으로써. 동물 세포의 증식을 촉진할 수 있다. claims: 새 또는 파충류의 유정란 유래 배아막의 배양 상등액을 유효성분으로 함유하는 동물 세포 배양 증식 촉진제.제1항 내지 제5항 중 어느 한 항에 기재된 세포 증식 촉진제를 함유하는 세포 배양용 배지.조류 또는 파충류 알의 배아막 유래의 세포를 배양하는 제 1 배양조와,증식을 목적으로 하는 동물 세포를 배양하는 제 2 배양조와,제 1 배양조에서 제 2 배양조로 배지를 흐르게 하는 제 1 유로와, 제 2 배양조에서 제 1 배양조로 배지를 흐르게 하는 제 2 유로와,제 1 배양조, 제 1 유로, 제 2 배양조, 제 2 유로의 순서로 세포 배양용 배지를 환류시키고, 상기 동물 세포 및/또는 상기 세포 배양용 배지의 상태에 따라, 제 1 유로 및 제 2 유로에 있어서의 상기 세포 배양용 배지의 흐름을 제어하는 배지 유량 제어부를 구비하는 동물 세포 배양 장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

310/1059 Row 310: application_number: 1020190137573, combined_string: invention_title: 수산 양식장 IOT 관리 시스템 abstract: 본 발명은 양식장에 설치된 설비의 작동정보와 센서들에서 측정된 센싱정보를 제공받아 관리하면서 센싱정보에 따라 예약된 설비의 작동을 작동시키며 센싱정보가 기준 범위를 벗어나면 양식업체에게 알려주고, 양식업체가 설비의 작동을 변경시킬 수 있도록 하는 수산 양식장 IOT 관리 시스템에 관한 것이다.본 발명에 따른 수산 양식장 IOT 관리 시스템은 단일보드 컴퓨터(200)에서 양식장에 설치된 센서들에서 측정된 센싱정보와 양식장에 설치된 설비의 작동시키는 설비 제어장치(100)와 통신하면서 설비의 작동정보를 제공받아 관리센터(300)로 제공하고, 관리센터(300)는 양식업체가 확인할 수 있도록 설비작동정보와 센싱정보를 인터넷 또는 양식업체 단말기(400)로 제공하고, 센싱정보가 등록된 설비작동기준을 확인하여 변경되는 설비의 작동변경정보를 단일보드 컴퓨터(200)로 제공하게 된다. claims: 양식장에 설치된 설비를 작동시키는 설비 제어장치(100), 양식장에 설치된 센서들에서 측정된 센싱정보와 설비 제어장치(100)로부터 설비의 작동상태를 제공받으며 유동아이피를 사용하는 단일보드 컴퓨터(200), 관리센터(300), 양식업체 단말기(400)를 포함하되, 단일보드 컴퓨터(200)는 관리센터(300)에 각종 정보를 제공하고 수신받을 수 있도록 인증키, 고유식별코드를 제공하고 인증받아 유동아이피를 사용하는 단일보드 컴퓨터(200)를 관리센터(300)에 정기적 또는 비정기적으로 접속하는 관리센터 호출부(202)와; 양식장에 설치된 설비의 작동을 제어하는 설비 제어장치(100)로부터 설비의 작동상태를 제공받는 실시간 설비작동상태 확인부(204)와; 양식장에 설치된 센서로부터 실시간으로 측정된 센싱정보를 제공받는 실시간 센싱정보 확인부(206)와; 실시간 설비작동상태 확인부(204)에서 수신된 양식장 설비의 작동정보와 실시간 센싱정보 확인부(206)에서 수신된 양식장 센서의 센싱정보를 관리센터(300)로 제공하는 양식장정보 제공부(208)와; 관리센터(300)로부터 양식장 설비의 작동을 변경하는 변경정보를 수신받는 설비작동변경 수신부(210)와; 설비작동변경 수신부(210)로 수신된 설비의 변경정보를 양식장의 설비에 매칭된 설비 제어장치(100)로 제공하는 설비작동변경 요청부(212);를 포함하고, 관리센터(300)는 양식장에 대한 정보를 단말기로 제공받아 관리하는 양식업체에 대한 정보를 등록받아 관리하는 양식업체 등록부(302)와; 등록된 단일보드 컴퓨터(200)의 접속을 확인하는 단일보드 컴퓨터 접속확인부(304)와; 접속된 단일보드 컴퓨터(200)로부터 실시간으로 제공되는 센싱정보를 제공받아 저장하면서 업데이트하는 센싱정보 관리부(306)와; 접속된 단일보드 컴퓨터(200)로부터 실시간으로 양식장의 설비 작동상태를 제공받아 저장하면서 업데이트하는 설비상태 관리부(308)와; 양식장의 센싱정보에 따라 대응되는 설비작동기준을 등록받아 관리하는 양식장 설비작동기준 등록부(310)와; 단일보드 컴퓨터(200)로부터 제공받은 양식장의 센싱정보와 양식장의 설비상태를 등록된 설비작동기준과 비교하여 센싱정보에 따라 설정된 설비작동기준을 확인하는 양식장 센싱정보 비교부(312)와; 양식장 센싱정보 비교부(312)에서 확인된 센싱정보에 대응되는 설비작동기준을 접속된 단일보드 컴퓨터(200)로 제공하는 양식장 설비작동 조작부(314)와; 실시간 설비작동상태 확인부(204)에서 수신된 양식장의 실시간 설비의 작동상태를 등록된 양식업체가 확인할 수 있도록 제공하는 양식장 설비상태 전송부(316)와; 실시간 센싱정보 확인부(206)에서 수신된 양식장의 센싱정보를 등록된 양식업체가 확인할 수 있도록 제공하는 실시간 양식장 센싱정보 전송부(318)와; 실시간 센싱정보 확인부(206)에서 수신된 양식장 주변정보와 수질정보에 대한 센싱정보가 등록된 기준 정상범위를 벗어나면 등록된 양식업체에게 긴급알림정보로 제공하는 설비 이상작동 경고부(320)와; 등록된 양식업체로부터 설비의 작동을 변경하기 위한 설비작동 변경정보를 제공받으면 접속된 단일보드 컴퓨터(200)로 제공하는 양식업체 설비작동 전송부(322)와; 등록된 양식업체로부터 다른 양식업체에 대한 고유식별정보를 등록받고, 다른 양식업체로부터 등록승인을 받으면 제휴 양식장으로 등록하여 관리하는 제휴 양식장 등록부(324)와; 제휴 양식장에 대한 실시간 센싱정보를 제휴 양식장으로 등록한 양식업체에게 제공하는 제휴 양식장 센싱정보 확인부(326)와; 등록된 양식장의 센싱정보를 제공받아 활용하는 기관을 등록받고, 센싱정보를 제공하는 양식업체로부터 등록승인을 받으면 제휴된 타기관으로 관리하는 타기관 등록부(328)와; 등록된 타기관에게 단일보드 컴퓨터(200)로부터 제공받은 센싱정보를 제공하는 타기관 센싱정보 제공부(330);를 포함하고, 양식업체 단말기(400)는 관리센터(300)로부터 제공받은 양식장의 실시간 설비의 작동상태를 화면에 표시하는 실시간 양식장 설비상태 표시부(402)와; 관리센터(300)로부터 제공받은 양식장의 실시간 주변정보 및 양식장 수질정보를 화면에 표시하는 실시간 양식장 센싱정보 표시부(404)와; 관리센터(300)의 양식장 설비작동기준 등록부(310)에 등록되는 설비의 예약기준을 변경하는 설비작동 예약 변경부(406)와; 관리센터(300)로부터 긴급알림정보가 수신되면 해당 센싱정보를 화면에 표시하는 긴급 알림표시부(408)와; 양식장에 설치된 설비의 작동이 변경되도록 조작하여 관리센터(300)로 제공하는 설비 조작부(410)와; 양식장의 센싱정보를 제공받는 다른 양식장에 정보를 관리센터(300)로 제공하는 이웃 양식장 등록부(412)와; 관리센터(300)로부터 제공받은 등록된 다른 양식장의 실시간 센싱정보를 표시하는 이웃 양식장 센싱정보 표시부(414);를 포함하며, 센싱정보는 온도, 습도, 조도를 포함하는 양식장의 주변정보와, 물의 온도, 염도, DO, pH, 적조, 녹조 수치를 포함하는 양식장의 수질정보로 이루어지고, 타기관은 관공소, 연구기관, 양식장 설비 수리업체 중의 어느 하나인 것을 특징으로 하는 수산 양식장 IOT 관리 시스템., Ltext: 어업, prediction: 어업
311/1059 Row 311: application_number: 1020190134984, combined_string: invention_title: 양식장 고수온 및 적조 방재 시스템 abstract: 본 발명은 수조로 전달되는 물의 온도와 수질을 조절하여 외부 수질 변화에 능동적으로 대처하여 어류를 양식할 수 있는 최적의 조건을 제공할 수 있는 양식장 고수온 및 적조 방재 시스템을 제공하는데 그 목적이 있다.상기한 목적을 이루기 위해 본 발명의 양식장 고수온 및 적조 방재 시스템은 양식장의 물을 관리하는 시스템에 있어서, 어류 및 물이 수용되는 수조, 외부의 물을 전달받아, 상기 수조에 물을 공급하고, 기포를 발생시키는 탱크 기포발생장치가 형성된 물 공급부, 상기 물 공급부의 물을 상기 수조로 전달하는 물 공급관에 형성되어, 상기 물 공급관의 물을 냉각시키는 냉각부, 냉각된 공기를 생성하고, 상기 물 공급부와 연결된 공기 공급관을 통해, 상기 탱크 기포발생장치에 냉각된 공기를 공급하는 공기 공급부 및 상기 수조, 상기 탱크 기포발생장치, 상기 물 공급부, 상기 물 공급관, 상기 냉각부, 상기 공기 공급관 및 상기 공기 공급부의 작동을 제어하고, 외부와 통신이 가능한 제어부를 포함하여 이루어지는 것을 특징으로 한다. claims: 양식장의 물을 관리하는 시스템에 있어서,어류 및 물이 수용되는 수조;외부의 물을 전달받아, 상기 수조에 물을 공급하고, 기포를 발생시키는 탱크 기포발생장치가 형성된 물 공급부;상기 물 공급부의 물을 상기 수조로 전달하는 물 공급관에 형성되어, 상기 물 공급관의 물을 냉각시키는 냉각부;냉각된 공기를 생성하고, 상기 물 공급부와 연결된 공기 공급관을 통해, 상기 탱크 기포발생장치에 냉각된 공기를 공급하는 공기 공급부; 및상기 수조, 상기 탱크 기포발생장치, 상기 물 공급부, 상기 물 공급관, 상기 냉각부, 상기 공기 공급관 및 상기 공기 공급부의 작동을 제어하고, 외부와 통신이 가능한 제어부;를 포함하여 이루어지는 것을 특징으로 하는 양식장 고수온 및 적조 방재 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

312/1059 Row 312: application_number: 1020190131088, combined_string: invention_title: 육상 양식장용 청소장치 abstract: 본 발명은 육상 양식장용 청소장치를 제공한다. 이와 같은 본 발명에 따른 육상 양식장용 청소장치는 육상 양식장의 수조 내 어패류와 물을 이동시키거나 드레인(drain)하지 않고 그대로 둔 상태에서 수조의 바닥이나 측벽에 위치한 이물질/오물질의 제거와 오수(汚水)의 배출이 진행될 수 있는 장치구성을 제공함으로써 육상 양식장의 운용 효율 증대와 수조 청소작업의 편의성과 능률 증대가 도모될 수 있고, 작업자가 간편하게 수동 조작하면서 이동시킬 수 있는 단순화되고 컴팩트화된 구성을 제공함으로써 수조 청소를 위한 비용이 절감되는 한편 필요에 따라 수시로 수조를 청소할 수 있는 기술적 특징을 갖는다. claims: 전복, 넙치 등을 포함하는 어패류를 기르는 육상 양식장을 구성하는 하나 이상의 수조(2)를 청소하기 위한 육상 양식장용 청소장치에 있어서,상기 수조(2)의 물 내부에 배치되며, 저면이 개방된 캡 형상으로 이루어져 물 유입공간(110)을 형성하게 되고, 경사지게 배치되는 설정길이의 핸들(120)이 상향 돌출되게 형성되는 회전체 케이싱(100);상기 회전체 케이싱(100)의 물 유입공간(110)에 설정패턴으로 배치되어 고정되고, 수조(2)의 바닥면(3)을 따라 이동하면서 상기 바닥면(3)에 부착된 이물질을 제거하게 되는 복수의 회전 스위퍼 유닛(200);상기 회전체 케이싱(100)을 통과하여 상기 회전 스위퍼 유닛(200)과 연결되고, 상기 회전 스위퍼 유닛(200)의 회전을 유도하게 되는 회전 스위퍼용 액추에이터(600);상기 물 유입공간(110)과 연통되게 상기 회전체 케이싱(100)과 연결되는 배출관체(700);상기 수조(2) 외부에 배치되며, 상기 배출관체(700)가 연결되는 진공탱크(800);상기 진공탱크(800)와 연결되고, 진공탱크(800)의 내부공간(810)을 진공압으로 만들어 상기 수조(2)의 물이 상기 회전체 케이싱(100)의 물 유입공간(110)과 배출관체(700)를 거쳐 진공탱크(800)로 유입되도록 하는 진공펌프(900); 및상기 회전 스위퍼용 액추에이터(600)와 진공펌프(900)의 동작을 제어하는 컨트롤러(1300);를 포함하는 구성으로 이루어져,상기 진공펌프(900)의 구동에 따라 상기 회전체 케이싱(100)의 물 유입공간(110), 배출관체(700), 진공탱크(800), 진공펌프(900)를 상기 수조(2)의 물이 통과하여 외부로 배출되는 한편, 상기 회전 스위퍼용 액추에이터(600)에 의해 상기 회전 스위퍼 유닛(200)의 회전이 유도되는 과정에서 상기 수조(2)의 청소가 수행되도록 하는 것을 특징으로 하는 육상 양식장용 청소장치.전복, 넙치 등을 포함하는 어패류를 기르는 육상 양식장을 구성하는 하나 이상의 수조(2)를 청소하기 위한 육상 양식장용 청소장치에 있어서,회전가능하게 수평 배치되는 판체 형상으로 이루어지고, 수조(2)의 바닥면(3)을 따라 이동하면서 상기 바닥면(3)에 부착된 이물질을 제거하게 되는 회전 스위퍼(300);상기 회전 스위퍼(300)의 상부면 중앙에 연결되어 상향 연장 형성되는 회전축(400);상기 회전축(400)과 일체로 결합되고, 상기 회전축(400)과 동일한 축선을 가지면서 상기 회전축(400)의 반경방향으로 돌출형성되며, 상기 수조(2)의 물이 통과하면서 회전하게 되는 수차용 임펠러(1100);저면이 개방된 캡 형상으로 이루어져 물 유입공간(110)을 형성하게 되며, 상기 물 유입공간(110) 내에 배치되는 상기 회전 스위퍼(300)의 측방 부위와 상단 부위를 감싸게 되는 회전스위퍼 커버(100');상기 회전스위퍼 커버(100')의 상부면 중앙으로부터 상향 연장 형성되고, 상기 물 유입공간(110)과 연통되는 이동채널(1210)이 상하 관통형성되며, 상기 이동채널(1210)에 상기 회전축(400)과 수차용 임펠러(1100)가 배치되되, 상기 회전축(400)을 베어링(410)을 매개로 고정시키게 되는 핸들 겸용 연결대(1200);상기 핸들 겸용 연결대(1200)의 이동채널(1210) 상단과 연통되고, 상기 이동채널(1210)에 진공압을 부여하게 되는 진공펌프(900); 및상기 진공펌프(900)의 동작을 제어하는 컨트롤러(1300);를 포함하는 구성으로 이루어져,상기 진공펌프(900)의 구동에 따라, 상기 회전스위퍼 커버(100')의 물 유입공간(110), 핸들 겸용 연결대(1200)의 이동채널(1210), 진공펌프(900)를 상기 수조(2)의 물이 통과하여 외부로 배출되는 한편, 상기 핸들 겸용 연결대(1200)의 이동채널(1210)을 통과하는 물에 의해 상기 수차용 임펠러(1100)가 회전하여 상기 회전 스위퍼(300)의 회전이 유도되는 과정에서 상기 수조(2)의 청소가 수행되도록 하는 것을 특징으로 하는 육상 양식장용 청소장치., Ltext: 어업, prediction: 임업
313/1059 Row 313: application_number: 1020190109828, combined_string: invention_title: 게 껍질 함유 사료를 이용한 뱀장어 치어의 양성방법 abstract: 본 발명은 미성어(未成魚) 단계의 새끼장어(치어, 稚魚)와 성어(成魚) 단계의 식용장어에 게 껍질 분말이 함유된 사료를 급여하여 성장률과 생존율을 향상시킬 수 있는 어류, 특히 뱀장어의 양성방법에 관한 것이다.본 발명의 게 껍질 함유 사료를 급여하는 뱀장어 치어의 양성방법은 일반 분말사료를 급여하는 양식방법에 비하여 뱀장어의 체장과 체중의 성장률이 증가하고 어체의 비필수 아미노산 함량이 증가하며, 면역력이 강화되어 별도의 항생제를 사용하지 않아도 생존율이 높고 사료효율이 우수하며 폐기처분되는 게 껍질 수산부산물을 단순 분쇄하여 재활용하므로 뱀장어 양식의 경제성을 높일 수 있으며, 또한 게 껍질에 함유된 키틴, 키토산뿐만 아니라 각종 유기물과 미네랄 성분들이 분말사료에 더하여지므로 영양과 미네랄이 조합된 고효율의 사료를 저비용으로 뱀장어에 공급할 수 있다. claims: 체중 4~7 g의 새끼장어를 수온 25~32 ℃의 순환여과식 시스템에 입식하는 단계;상기 입식된 새끼장어에 분말사료를 2~4일간 급여하는 단계; 및상기 분말사료 급여 후 게 껍질 분말이 5~12 중량% 함유된 분말사료를 어체 총중량의 2~5 중량%/일의 양으로 급여하는 단계;를 포함하는, 게 껍질 함유 사료를 이용한 뱀장어 치어의 양성방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

314/1059 Row 314: application_number: 1020190106424, combined_string: invention_title: 양식장용 산소공급장치 abstract: 본 발명에 의하면, 양식장의 수면에 부력을 이용하여 부상하는 부력부; 부력부의 양측부에 회전 가능하게 구성되어 부력부가 양식장을 이동하도록 하고 양식장 상층 수위의 물을 퍼올려 물이 포말로 부서진 후 낙하되도록 하여 상층 수위에 산소가 공급되도록 하는 제1산소공급부; 및 부력부의 하측에 벤츄리 구조를 제공하고 양식장의 물이 양식장 하층 수위에 펌핑시 대기 중의 공기가 분사되도록 하여 하층 수위에 산소가 공급되도록 하는 제2산소공급부를 포함하는 양식장용 산소공급장치가 제공된다. claims: 양식장의 수면에 부력을 이용하여 부상하는 부력부(110);부력부(110)의 양측부에 회전 가능하게 구성되어 부력부(110)가 양식장을 이동하도록 하고 양식장 상층 수위의 물을 퍼올려 물이 포말로 부서진 후 낙하되도록 하여 상층 수위에 산소가 공급되도록 하는 제1산소공급부(120); 및부력부(110)의 하측에 벤츄리 구조를 제공하고 양식장의 물이 양식장 하층 수위에 펌핑시 대기 중의 공기가 분사되도록 하여 하층 수위에 산소가 공급되도록 하는 제2산소공급부(130)를 포함하는 것을 특징으로 하는 양식장용 산소공급장치., Ltext: 어업, prediction: 임업
315/1059 Row 315: application_number: 1020190106425, combined_string: invention_title: 공기가열부를 가지는 양식장용 산소공급장치 abstract: 본 발명에 의하면, 양식장의 수면에 부력을 이용하여 부상하는 부력부; 부력부의 양측부에 회전 가능하게 구성되어 부력부가 양식장을 이동하도록 하고 양식장 상층 수위의 물을 퍼올려 물이 포말로 부서진 후 낙하되도록 하여 상층 수위에 산소가 공급되도록 하는 제1산소공급부; 부력부의 하측에 벤츄리 구조를 제공하고 양식장의 물이 양식장 하층 수위에 펌핑시 대기 중의 공기가 분사되도록 하여 하층 수위에 산소가 공급되도록 하는 제2산소공급부; 및 부력부에 소정의 공간을 제공하고 상기 공간의 공기가 가열되도록 한 후 제2산소공급부를 통해 양식장 하층 수위에 가열 공가기 공급되도록 하여 대류를 통한 수온 상승을 가능하게 하는 공기가열부를 포함하는 양식장용 산소공급장치가 제공된다. claims: 양식장의 수면에 부력을 이용하여 부상하는 부력부(110);부력부(110)의 양측부에 회전 가능하게 구성되어 부력부(110)가 양식장을 이동하도록 하고 양식장 상층 수위의 물을 퍼올려 물이 포말로 부서진 후 낙하되도록 하여 상층 수위에 산소가 공급되도록 하는 제1산소공급부(120);부력부(110)의 하측에 벤츄리 구조를 제공하고 양식장의 물이 양식장 하층 수위에 펌핑시 대기 중의 공기가 분사되도록 하여 하층 수위에 산소가 공급되도록 하는 제2산소공급부(130); 및 부력부(110)에 소정의 공간을 제공하고 상기 공간의 공기가 가열되도록 한 후 제2산소공급부(130)를 통해 양식장 하층 수위에 가열 공가기 공급되도록 하여 대류를 통한 수온 상승을 가능하게 하는 공기가열부(140)를 포함하는 것을 특징으로 하는 양식장용 산소공급장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

316/1059 Row 316: application_number: 1020190097865, combined_string: invention_title: 행동 패턴 인식을 이용한 소의 발정 탐지 시스템 abstract: 본 발명은 소의 발정 탐지 시스템에 관한 것으로서, 보다 구체적으로는 행동 패턴 인식을 이용한 소의 발정 탐지 시스템으로서, 소에 부착되어 소의 움직임 및 행동을 감지하는 행동탐지 센서; 상기 행동탐지 센서에서 감지된 데이터를 수신받아 저장하고, 기저장된 축우 관련 사육정보와 함께 데이터베이스를 구축하는 DB 서버; 및 상기 DB 서버에 저장된 데이터를 분석하여 소의 행동 패턴을 인식하고 발정을 탐지하는 분석 서버를 포함하여 구성되며, 상기 분석 서버는, 상기 DB 서버에 저장된 움직임 데이터를 기초로 분석하여, 소의 휴식상태, 활동상태, 및 고활동상태를 포함하는 행동 유형의 특징적 패턴을 찾아내고, 소의 행동 유형을 판단하는 행동분석 모듈; 및 상기 행동분석 모듈에서 판단된 상기 소의 행동 유형 정보를 통해 승가 정보를 분석하고 소의 발정 여부를 탐지하는 발정탐지 모듈을 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 행동 패턴 인식을 이용한 소의 발정 탐지 시스템에 따르면, 부착된 행동탐지 센서에서 감지한 소의 움직임 및 행동 정보를 토대로, 소의 행동 유형 패턴을 판단하고 소의 발정 여부를 탐지하는 분석 서버 및 발정탐지 모듈을 포함함으로써, 소의 발정기를 보다 정확하고 용이하게 판단할 수 있어, 소의 번식 효율을 증가시키고 발정 미감지로 인한 피해를 줄여, 궁극적으로는 한우 농가의 생산성 및 수익성에 이바지하고 농가의 소득 증대에 이바지할 수 있다.또한, 본 발명에서 제안하고 있는 행동 패턴 인식을 이용한 소의 발정 탐지 시스템에 따르면, 가속도 센서에서 감지된 3축 가속도 신호의 drift 발생으로 인해 생길 수 있는 오차를 보정 및 전처리하고, 감지된 3축 가속도 신호를 통계적, 수학적 방법으로 분석함으로써, 소의 행동 유형 패턴을 보다 정교하게 판단할 수 있으며, 특히, 인공지능 기술 중 딥러닝 알고리즘을 이용하여 소의 행동 유형을 판단함으로써, 같은 유형의 행동이 개체에 따라 다양한 신호 패턴을 보여 그 신호의 편차가 크더라도 오류를 줄일 수 있고, 한우 개체별로 상이한 행동 양식, 성격, 생활 습성, 건강상태, 우방에서의 서열 등을 고려한 판단이 가능하여, 소의 발정기 탐지적중률을 제고시킬 수 있다.뿐만 아니라, 본 발명에서 제안하고 있는 행동 패턴 인식을 이용한 소의 발정 탐지 시스템에 따르면, 분석 서버에서 분석한 소의 행동 유형 정보 및 발정 탐지 정보와 관찰카메라부에서 촬영한 영상을 기초로, 소의 생애 주기에 따른 생체정보 제공 및 축사 모니터링이 가능한 스마트기기의 애플리케이션을 구축함으로써, 궁극적으로는 종합적인 축사 사육현황 및 번식관리 솔루션을 제공하고, ICT 융복합 관련 핵심기술인 무선통신기술, 통합제어기술, 센싱기술, 알고리즘 기술을 활용하여, 우리나라 축산에 대한 소비자의 인식전환을 유도하고 축산업 경쟁력을 상승시킬 수 있다. claims: 소의 발정 탐지 시스템(10)으로서,소에 부착되어 소의 움직임 및 행동을 감지하는 행동탐지 센서(100);상기 행동탐지 센서(100)에서 감지된 데이터를 수신받아 저장하고, 기저장된 축우 관련 사육정보와 함께 데이터베이스를 구축하는 DB 서버(200);상기 DB 서버(200)에 저장된 데이터를 분석하여 소의 행동 패턴을 인식하고 발정을 탐지하는 분석 서버(300);축사를 24시간 촬영하고 촬영된 영상을 상기 DB 서버(200)로 송신하는 관찰카메라부(400); 및상기 분석 서버(300)에서 분석한 행동 유형 정보 및 발정 탐지 정보와 상기 관찰카메라부(400)에서 촬영된 영상을 시각화시켜 보여주는 스마트기기(500)를 포함하며,상기 행동탐지 센서(100)는,소의 귀에 부착되는 것을 특징으로 하며,개체의 머리, 귀, 입놀림 및 몸 전체의 움직임에 의한 귀의 떨림을 이용하여, 기울기 값을 측정하는 3축 가속도 센서(110);개체의 머리, 귀, 입놀림 및 몸 전체의 움직임에 의한 귀의 떨림을 이용하여, 방향값을 측정하는 자력계(120); 및상기 3축 가속도 센서(110) 및 상기 자력계(120)에서 측정된 소의 움직임 및 행동 데이터를 상기 DB 서버(200)로 송신하는 송신부(130)를 포함하여 구성되고,상기 3축 가속도 센서(110)는,감지된 3축 가속도 신호의 drift 발생으로 인한 오차를 보정 및 전처리하되, state-space 기반의 방식으로 sensor fusion 혹은 state-space model을 사용함으로써 drift 누적으로 인한 오차 및 발생하는 에러를 보상하며,상기 행동탐지 센서(100)에서 사용되는 통신은, 동적으로 무선 자원을 할당하여 배터리 소모를 줄이는 알고리즘을 이용하되, 데이터양과 변화율을 측정하여 Beacon Interval을 조절해 채널 경쟁을 하는 노드 수를 줄이고 데이터 전달 지연시간을 최소화하며, 보장 전송 구간 할당 요청으로 가중치를 계산하여 우선도에 따라 보장 전송 구간을 할당하거나 공정한 분배를 통해 보장 전송 구간 요청 처리율을 높이고 지연시간을 감소시키며,상기 분석 서버(300)는,상기 DB 서버(200)에 저장된 움직임 데이터를 기초로 분석하여, 소의 휴식상태, 활동상태, 및 고활동상태를 포함하는 행동 유형의 특징적 패턴을 찾아내고, 소의 행동 유형을 판단하는 행동분석 모듈(310); 및상기 행동분석 모듈(310)에서 판단된 상기 소의 행동 유형 정보를 통해 승가 정보를 분석하고 소의 발정 여부를 탐지하는 발정탐지 모듈(320)을 포함하며,상기 행동분석 모듈(310)은,통계적 분석 방법으로서, 단위 시간 동안의 평균/분산/표준편차(RMS), 평균 편차 비교 분석법, 기울기 변화량 적분법, 변량 도수 분포 분석법, 및 퓨리에 주파수 변환(FFT) 분석법 중 적어도 하나 이상을 이용하며, 딥러닝 기술을 기반으로 상기 DB 서버(200)에 저장된 움직임 데이터로부터 행동 유형을 분석하여, 같은 행동의 패턴이더라도 개체에 따라서 3축 가속도 센서의 신호 패턴의 편차가 크게 나오는 경우를 보완하며,상기 발정탐지 모듈(320)은,기설정된 일정 시간 단위로 행동 유형별 시간 점유율 및 분포를 계산하여 승가 정보를 분석하고 소의 발정 여부를 탐지하며, 상기 DB 서버(200)에 저장된 움직임 데이터로부터 개체별 습성 및 상태 정보를 취득하여, 소의 발정 여부 판단을 보완하며,소의 엉덩이에 부착되어, 접점검출 방식으로 승가 허용 여부를 감지하고, 감지된 승가 허용 정보를 상기 DB 서버(200)로 송신하는 승가 허용 탐지 센서(600)를 더 포함하여, 상기 승가 허용 탐지 센서(600)에서 감지된 소의 승가 허용 정보를 함께 이용하여 소의 발정 여부를 탐지하는 것을 특징으로 하는, 행동 패턴 인식을 이용한 소의 발정 탐지 시스템(10)., Ltext: 어업, prediction: 임업
317/1059 Row 317: application_number: 1020217023134, combined_string: invention_title: 여과기 부착 수조 셋트 abstract: 수조 본체(1) 내에 여과기(F)를 구비한 여과기 부착 수조 셋트에 있어서, 수조 본체(1)는, 저류수가 저류되고 상면이 개방된 그릇형으로 형성되고, 그 내부에 여과기(F)가 설치되고, 수조 본체(1)와 여과기(F)의 여과 케이스(10)가, 모두 동색으로 불투명하게 형성된다. 이것에 의해, 관상어를 관상하는 관상자에게 있어서, 수조 내에 설치되는 여과기가, 수조의 밖에서 잘 보이지 않도록 하여 관상어의 관상 효과를 높이도록 했다. claims: 수조 본체(1) 내에, 상기 수조 본체(1) 내의 저류수를 순환 여과하는 여과기(F)를 구비한 여과기 부착 수조 셋트로서, 상기 수조 본체(1)는, 관상어를 사육하기 위해 저류수가 저류되고 상면이 개방된 그릇형으로 형성되고, 그 내부에 상기 여과기(F)가 설치되고, 상기 수조 본체(1)와 상기 여과기(F)의 여과 케이스(10)는 모두 동색(同色)으로 불투명하게 형성되는 것을 특징으로 하는 여과기 부착 수조 셋트., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

318/1059 Row 318: application_number: 1020210136681, combined_string: invention_title: 빅데이터를 이용한 인공지능 기술 기반 이상징후 표적 감지 방법 및 그 시스템 abstract: 본 개시(disclosure)의 다양한 실시 예들에 따르면, 바다를 항해하는 표적의 이상징후를 감지하기 위한 이상징후표적 감지 시스템은, 항해 표적을 탐지하여 항해 표적 정보를 출력하는 레이더, 서버로부터 미리 등록된 표적들에 대한 저장 표적 정보를 선박식별장치에게 전달하는 서버, 상기 항해 표적 정보와 상기 저장 표적 정보를 융합하여 상기 항해 표적의 이상징후 여부를 결정하고, 상기 이상징후 여부를 표시하는 선박식별장치를 포함할 수 있다. claims: 바다를 항해하는 표적의 이상징후를 감지하기 위한 이상징후표적 감지 시스템에 있어서,항해표적을 탐지하여 항해표적 정보를 출력하는 레이더;기등록된 복수의 항해표적 각각에 대하여, 복수의 시각 각각에 대응하는 표적크기 정보, 표적위치 정보, 계획된 이동경로 정보 및 이동속도 정보를 포함하는 저장표적 정보를 선박식별장치에게 전달하는 서버; 및상기 레이더로부터 탐지된 항해표적에 대한 항해표적 정보를 수신하고, 상기 탐지된 항해표적이 상기 저장표적 정보에 기등록된 복수의 표적에 포함되어 있지 않은 표적인 경우 상기 항해표적을 제1 이상징후 표적으로 결정하고, 상기 탐지된 항해표적이 상기 저장표적 정보에 기등록된 복수의 표적에 포함된 표적인 경우 상기 항해표적 정보를 상기 저장표적 정보와 융합하여 표적크기 정보, 표적위치 정보, 이동경로 정보 및 이동속도 정보를 포함하는 빅데이터 분석정보를 생성하고, 상기 생성된 빅데이터 분석정보를 상기 서버로 전송하는 선박식별장치; 를 포함하고,상기 서버는, 상기 선박식별장치로부터 수신된 빅데이터 분석정보를, 제1 가중치가 부여된 표적크기 정보, 제2 가중치를 부여된 표적위치 정보, 제3 가중치가 부여된 이동경로 정보 및 제4 가중치가 부여된 이동속도 정보를 포함하는 분석정보를 학습 정보로 하여 이동 경로를 출력하도록 학습된 인공지능 모델에 입력하고, 상기 인공지능 모델을 통해 출력된 출력 정보를 기초로 상기 항해표적의 과거 이동경로 및 상기 항해표적의 미래 예측경로를 획득하고, 상기 항해표적의 과거 이동경로 및 상기 항해표적의 미래 예측경로를 상기 선박식별장치로 전송하고, 상기 선박식별장치는, 상기 서버로부터 수신한 과거 이동경로와 상기 저장표적 정보에 포함된 계획된 이동경로 정보 간의 오차에 대응하는 제1 오차 값 및 상기 서버로부터 수신한 미래 예측경로와 상기 저장표적 정보에 포함된 계획된 이동경로 정보 간의 오차에 제5 가중치가 부여된 제2 오차값을 획득하고, 상기 제1 오차값 및 상기 제2 오차값 중 적어도 하나가 기설정된 임계 값 이상인 것으로 판단되면, 상기 항해표적을 제2 이상징후 표적으로 결정하는 것을 특징으로 하는, 이상징후표적 감지 시스템., Ltext: 어업, prediction: 어업
319/1059 Row 319: application_number: 1020210058941, combined_string: invention_title: 슬러지 고착방지기구를 구비한 양식장용 산소용해장치 abstract: 본 발명은 양식장에 공급되는 해수에 산소를 투입하여 용존산소율을 향상하기 위해 양식장에 공급되는 해수가 유입되는 유입파이프(100)와, 상기 유입파이프로 유입되는 해수에 기화된 산소를 공급하는 산소공급구(200)와, 상기 유입파이프에 연결되어 산소와 해수가 혼합되어 공급되는 혼합공급구(300)를 구비하고, 상기 양식장용 산소용해장치는 상부에는 공급된 기체 산소와 해수가 혼합되는 혼합공간부(A)와 상기 혼합공간부(A)에서 혼합된 해수를 배출하는 해수배출구(600)가 부착된 산소용해통체(400)를 구비한 양식장용 산소용해장치에 있어서,상기 해수배출구(600) 와 산소용해통체(400)의 바닥면(410) 사이에 상기 바닥면에 모여지는 슬러지의 고착되는 것을 방지하고, 고착된 슬러지를 바닥면(410)에서 분리할 수 있는 슬러지 고착방지구(700)를 구비하며, 상기 슬러지 고착방지구(700)는 고압공기구(800)에서 공급되는 고압공기를 바닥면을 향하여 분사하는 다수개의 분사구(710)를 구비하는 것을 특징으로 하는 슬러지 고착방지기구를 구비한 양식장용 산소용해장치를 제공한다. claims: 양식장에 공급되는 해수에 산소를 투입하여 용존산소율을 향상하기 위해 양식장에 공급되는 해수가 유입되는 유입파이프(100)와, 상기 유입파이프로 유입되는 해수에 기화된 산소를 공급하는 산소공급구(200)와, 상기 유입파이프에 연결되어 산소와 해수가 혼합되어 공급되는 혼합공급구(300)를 구비하고,상부에는 공급된 기체 산소와 해수가 혼합되는 혼합공간부(A)와 혼합공간부(A)에서 산소가 혼합되어 산소가 용해된 해수로 이루어진 해수공간(B)로 이루어지고, 산소가 용해된 해수를 배출하는 해수배출구(600)가 부착된 산소용해통체(400)를 구비한 양식장용 산소용해장치에 있어서,상기 해수배출구(600)와 산소용해통체(400)의 바닥면(410) 사이에 상기 바닥면에 모여지는 슬러지의 고착되는 것을 방지하고, 고착된 슬러지를 바닥면(410)에서 분리할 수 있는 슬러지 고착방지구(700)를 구비하며,상기 슬러지 고착방지구(700)는 고압공기구(800)에서 공급되는 고압공기를 바닥면을 향하여 분사하는 다수개의 분사구(710)를 구비하며, 또한, 상기 슬러지 고착방지구(700)는 원통 형상의 산소용해통체(400) 내부에 내부공간을 가진 파이프로 원형 링 형상으로 형성된 고착방지구 몸체(720)와,상기 고착방지구 몸체(720)에 일정한 간격으로 분사구(710)가 구비되되,상기 분사구(710)의 분사 방향은 바닥면으로 향하되, 고착방지구 몸체(720)의 중심원주와 수직보다 작은 각도(α1〈 90)로 형성되어 고착방지구 몸체(720)의 내경쪽으로 향하는 동시에 원주방향으로 일정한 각도(α2)로 기우려져, 상기 분사구(710)에서 분사된 압축공기에 의하여 바닥면의 해수가 회전할 수 있도록 이루어진 것을 특징으로 하는 슬러지 고착방지기구를 구비한 양식장용 산소용해장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

320/1059 Row 320: application_number: 1020210053987, combined_string: invention_title: 오픈형 난로겸 온수공급 시스템 abstract: 본 발명은 본 발명은 오픈형 난방장치겸 온수공급 시스템에 관한 것으로, 가스버너에 의해 발생되는 불꽃에 의해 열전도율이 우수한 동파이프가열관을 통과하면서 가열하고 내부에 설치된 순환되어 보일러나 난방 파이프 역할을 수행하는 나선형 온수동관을 시속하게 뎁히는 것을 특징으로하는 다용도 고열효율 오픈형 난방장치겸 온수공급 시스템을 제공한다.이에 의해, 본 발명은 높은 열전도율을 보이는 동파이프를 이용하여 실내공기를 빠른 속도로 상승시킬 뿐만아니라, 완전연소로 클린 실내 환경이 가능토록하고 온수 또한 급속하게 가열하여 공급함으로써 열감절감 및 에너지 효율을 극대화할 수 있는 효과가 있다. 따라서 식물원, 온실, 가축사육장, 어류양식장에 사용할 수 있고, 또한 온수탱크를 설치하면 식당, 휴게소, 아파트 연립주택 실내 난로 겸 온수공급시스템으로 광범위한 용도로 편리하게 사용할 수 있다. claims: 동선으로 된 나선형 형상의 온수관으로 하부의 버너(130)에 대한 제어장치부(200)에 대한 제어에 따라 내부 온수 가열시, 순환되어 보일러나 난방 파이프 역할을 수행하는 나선형 온수동관(110); 및나선형 온수동관(110)의 상부에 동으로 된 파이프형가열관이 나선형을 따라 N개(N은 2 이상의 자연수)가 설치됨으로써, 나선형 온수관(110)에서 전달된 열원을 상부로 제공하는 역할을 수행할 뿐만 아니라, LNG 또는 LPG 가스를 이용해 버너(130)를 가열을 하면 동심원 형태의 나선형 온수관(110) 사이 공간인 관 공간부(110a)로 불꽃이 올라오면 불꽃에 의해 가열되어서 달궈져서 열 저장 공간으로 작용할 뿐만 아니라, 버너(130)에서 발생된 가스의 불완전 연소를 완전 연소로 바꿔주는 역할을 수행하는 동파이프가열관(120); 을 포함하는 것을 특징으로 하는 실내공기를 뎁히는 난로 겸 온수 공급 방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

321/1059 Row 321: application_number: 1020210053579, combined_string: invention_title: 침몰방지 시스템 abstract: 본 발명은 침몰방지 시스템으로서, 레이저 절단기, 플라즈마 절단기, 드릴링 머신 및 탭핑 머신을 이용하여 최적화된 선박 구조물을 제조한다. claims: 레이저 절단기, 플라즈마 절단기, 드릴링 머신 및 탭핑 머신을 이용하여 최적화된 선박 구조물을 제조하는, 침몰방지 시스에 있어서.상기 선박 구조물은,상기 선박의 격벽에 일정한 간격으로 다수 개 구비되어 상기 선박을 용이하게 인양하는 격벽고리;를 포함하고,상기 격벽고리는,가로 방향으로 위치하는 인양가이드;상기 인양가이드의 상단에 일정한 거리를 가지며 직각으로 위치하고, 상단이 상기 선박의 격벽에 고정 연결되어 있는 상단고정부;상기 상단고정부의 하단에 고정 연결되어 있으며, '∩'와 같은 형상으로 형성되되 서로 마주보는 상단의 간격이 하단의 간격보다 넓은 너비를 갖는 형상으로 형성되고, 양단 중앙에는 상기 인양가이드가 관통 가능한 크기를 가지며 상기 인양가이드의 형상에 맞추어 형성된 관통홈이 형성되어 있으며, 양하단에는 원형의 체결홈이 형성되어 있는 고정고리부;원기둥의 형상으로 형성되며 외측면은 나선형의 홈이 형성되어 있고, 상기 고정고리부의 양하단에 형성된 상기 체결홈으로 삽입하여 위치하는 하단고정부; 및외측면은 상기 고정고리부의 상기 체결홈보다 넓은 너비로 형성되되 각진 형상으로 형성되고, 비어 있는 내측면은 상기 하단고정부가 삽입 가능한 너비와 형상으로 형성되되, 상기 하단고정부의 외측면과 대응되도록 나선형의 돌기가 형성되어 있고, 상기 하단고정부의 외측면에 형성된 나선형의 홈을 따라 맞닿아 회전하는 회전고정부;를 포함하되,,상기 선박 구조물은,상기 선박의 양측 및 후방에 일정한 간격으로 다수 개 마련되며, 부력을 발생시키고, 상기 선박의 기울기에 따라 부력을 다르게 발생시키는 에어백;을 더 포함하고,상기 선박 구조물은,내부가 비어 있는 직육면체의 형상으로 형성되며, 일단면이 개폐 가능하도록 구성되어 에어백 또는 히팅부를 비어 있는 내부에 내장하여 보관하고, 상기 선박의 내측면 또는 외측면에 고정 가능한 후면으로 형성되는 케이스부;를 포함하고,상기 케이스부는,하나의 일측면이 제거된 육면체의 형상으로 형성되며 내부가 비어 있도록 형성된 내장보관부; 및일단이 상기 내장보관부의 일측면이 제거된 하단에 회전 가능하도록 연결 고정되어 있으며, 상하로 회전 구동하여 상기 내장보관부의 일측면을 개폐하는 회전개폐부;를 포함하고,상기 내장보관부는,내측면 일단에 적어도 하나 마련되어 있으며, 상기 에어백 또는 상기 히팅부를 고정시키는 내측고정부;내측면 양단에 마련되어 있으며, 상하로 회전 구동하는 상기 회전개폐부를 지지하도록 수축 및 이완 구동하고, 상기 회전개폐부가 상단 방향으로 구동하여 닫히는 경우 수축하고, 상기 회전개폐부가 하단 방향으로 구동하여 열리는 경우 이완하는 개폐지지부;하나의 일측면이 제거된 입구의 외곽 부분으로 돌출되어 형성되고, 외측면 상단 중앙으로부터 내측면 상단 중앙으로 관통한 채 위치하는 상단잠금부가 구비된 외곽돌출부; 및상기 외곽돌출부의 일측면 하단에 마련되어 있으며, 상기 회전개폐부와 고정 연결되고 상기 회전개폐부의 회전 구동을 가능하게 하는 회전연결부;를 포함하고,상기 회전개폐부는,상기 내장보관부 측을 향하는 타단면에 잠금모듈이 마련되어 있고,상기 잠금모듈은,내부가 비어 있는 'П'와 같은 형상으로 형성되며, 양하단은 상기 회전개폐부의 타단면과 맞닿을 수 있도록 직각으로 굽어지게 형성되고, 직각으로 형성된 양하단에 일정한 간격으로 원형의 고정홈이 형성되어 있으며 상기 고정홈으로 너트가 삽입하여 타단면에 고정 연결되는 잠금보호부; 및상기 잠금보호부의 내측에 위치하며, 상기 외곽돌출부에 구비된 상단잠금부와 맞닿아 고정되도록 형성되고, 상기 상단잠금부가 외측면으로부터 내측면 방향으로 외부의 압력에 의하여 이동하는 경우, 하단으로 이동하여 잠금을 해제하는 하단잠금부;를 포함하고,상기 케이스부는,외측면에 마련되어 있는 탄성모듈을 포함하고,상기 탄성모듈은,상기 케이스부의 모서리에 체결되는 중앙프레임;상기 선박에 충격을 주는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 상기 케이스부의 진행 방향에 대응하여 회동 가능한 다수의 합성수지재로 형성되고, 상기 중앙프레임의 전면에 결속되는 회전롤러;상기 각 회전롤러의 중앙에 길이 방향으로 관통 삽입하여 고정되고, 상기 회전롤러를 지지하며 상기 회전롤러의 원활한 회동을 도모하는 롤러지지부;상기 중앙프레임의 상, 하부 내측에 삽입되며, 상기 케이스부의 충돌 시 상기 회전롤러에 가해진 압력에 따라 수축 또는 팽창하여 상기 회전롤러의 수평 위치를 조절하는 탄성부;상기 중앙프레임의 상면 일측에 체결되며, 물체의 접근 여부를 감지하여 경고음을 발생하는 감지센서부; 및다수의 상기 중앙프레임을 관통하여 결속되는 고정스트랩;을 포함하고,상기 중앙프레임은,직각으로 형성되어 있는 벽이나 기둥의 구조물의 모서리 형상에 대응하여 안정적인 체결이 가능하도록 단면이 ㄴ자 형상으로 절곡되어 있는 제1 프레임;전면에 상기 회전롤러가 삽입되어 고정된 상기 롤러지지부가 결속됨과 동시에 상기 케이스부가 바다에 존재하여 상기 선박에 충격을 가하는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 상기 케이스부에 가해지는 충격을 완화하는 완충 공간을 형성하도록 상기 제1 프레임의 전면 상, 하단에 각각 외향 돌출 성형되어 있는 W 형상의 제2 프레임; 및 전면에 상기 회전롤러가 삽입되어 고정된 상기 롤러지지부가 결속됨과 동시에 상기 케이스부가 바다에 존재하여 상기 선박에 충격을 가하는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 상기 케이스부에 가해지는 충격을 완화하는 완충 공간을 형성하도록 상기 제1 프레임의 전면 상, 하단에 각각 외향 돌출 성형되어 있는 W 형상의 제3 프레임;을 포함하고,상기 제1 프레임은,상기 중앙프레임 간의 결속력을 향상시키는 상기 고정스트랩이 관통하도록 전면 상, 하부에 장공형의 스트랩고정홈이 천공되어 있고,상기 제1 프레임은,상기 스트랩고정홈과 나사의 결속에 의해 단일의 상기 중앙 프레임이 상기 케이스부의 모서리에 체결되도록 상기 스트랩고정홈 사이에 천공홈이 각각 천공되어 있고,상기 제2 프레임은,상면 일측에 상향 돌출 성형되어 있으며, 물체의 접근 여부를 감지하여 경고음을 발생하는 상기 감지센서부가 상기 중앙프레임의 상부에 체결되도록 체결홈이 형성되어 있고,상기 나사는,나사삽입홈에 삽결되어 상기 탄성모듈이 상기 케이스부의 외측면에 안정적으로 체결되고,상기 제2 프레임은,저면에 장방형의 제2 프레임 고정부와 하단고정부가 각각 함몰 성형되어 있어 상기 롤러지지부의 상, 하단부가 삽입하여 고정되고, 삽결된 상기 롤러지지부의 원활한 수평 이동을 도모하고,상기 제3 프레임은,상면에 장방형의 제2 프레임 고정부와 하단고정부가 각각 함몰 성형되어 있어 상기 롤러지지부의 상, 하단부가 삽입하여 고정되고, 삽결된 상기 롤러지지부의 원활한 수평 이동을 도모하고,상기 제2 프레임 고정부는,일측에 상기 케이스부가 바다에 존재하여 상기 선박에 충격을 가하는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 수축 또는 팽창하는 상기 탄성부가 상기 중앙프레임의 내측에 삽입 고정되는 탄성체가 함몰 성형되어 있고,상기 프레임 고정부는,타측에 상기 하단고정부와 상이하게 상기 제2 프레임의 전면으로부터 중심축의 상단이 삽입 고정 가능하도록 개방되어 있고,상기 제2 프레임 고정부는,개방되어 있는 개방면의 내측에 프레임보호부가 내향 돌출 성형되어 있어 삽결된 상기 중심축의 상단이 이탈하는 것을 방지하고,상기 회전롤러는,상기 케이스부가 바다에 존재하여 상기 선박에 충격을 줄 수 있는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 상기 케이스부의 진행 방향에 대응하여 회동함으로써 상기 케이스부와의 접촉 면적을 최소화하여 상기 케이스부에 가해지는 충격을 완화할 수 있도록 원통형으로 성형되어 있고,상기 회전롤러는,상기 롤러지지부가 삽입 고정되도록 상면 중앙에 길이 방향으로 관통홈이 천공되어 있고,상기 감지센서부는,물체의 접근 여부를 감지할 수 있는 감지센서를 포함하고,상기 감지센서부는,일측에 작동 유무를 제어하는 것이 가능한 스위치가 형성되어 있고,상기 고정스트랩은,상기 중앙프레임의 상기 제1 프레임에 천공되어 있는 상기 스트랩고정홈에 삽입 고정되어 다수의 상기 중앙프레임을 결속하고,상기 고정스트랩은,일체화된 다수의 상기 중앙프레임을 상기 케이스부의 외측면에 안정적으로 고정 가능하도록 양측 단부의 전, 후면에 상호 부착 가능한 고정부착부가 각각 구비되어 있고,상기 케이스부의 모서기에 단일의 상기 중앙프레임이 체결되는 경우,상기 제1 프레임의 전면에 천공되어 있는 상기 천공홈에 상기 나사가 삽입 고정되어 상기 케이스부의 외측면에 결속되고,상기 롤러지지부는,상기 케이스부의 외측면에 체결된 상기 중앙프레임의 상기 제2 프레임 및 상기 제3 프레임의 사이에 상, 하단부가 삽입 고정되어 상기 중앙프레임의 전면에 결속되고,상기 롤러지지부는,하단부가 상기 제3 프레임의 상면에 함몰 성형되어 있는 상기 하단고정부에 먼저 삽입 고정된 후, 상단부가 상기 제2 프레임의 저면에 함몰 성형되어 있는 상기 제2 프레임 고정부의 개방된 일측면으로 삽입 고정되어 상기 중앙프레임의 전면에 결속되는, 침몰방지 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

322/1059 Row 322: application_number: 1020210046922, combined_string: invention_title: 어군 생태계의 이상 여부를 감지하기 위한 어군 생태계 모니터링 시스템 장치 및 그 동작 방법 abstract: 어군 생태계의 이상 여부를 감지하기 위한 어군 생태계 모니터링 시스템 장치 및 그 동작 방법이 개시된다. 본 발명은 SONAR(SOund Navigation And Ranging) 모듈이 탑재되어 있는 부이(buoy) 장치로부터, SONAR 모듈에 의해 촬영된 SONAR 이미지를 사전 설정된 획득 시간 간격으로 수신하고, SONAR 이미지들 각각을 어군 객체 식별 모델에 입력으로 인가하여, SONAR 이미지들 각각에서 어군 객체를 식별한 후, SONAR 이미지들 각각에서 식별된 어군 객체의 수를 기초로, 어군 생태계의 이상 여부를 판단하여, 어군 생태계의 이상이 있는 것으로 판단되면, 경고 메시지를 생성하여 관리자의 단말로 전송하는 어군 생태계 모니터링 시스템 장치 및 그 동작 방법에 대한 것이다. claims: 어군 생태계의 이상 여부를 감지하기 위한 어군 생태계 모니터링 시스템 장치에 있어서,수중에서 SONAR(SOund Navigation And Ranging) 이미지를 획득하기 위한 SONAR 모듈이 탑재되어 있는 부이(buoy) 장치로부터, 상기 SONAR 모듈에 의해 촬영된 SONAR 이미지를 매일 k(k는 2이상의 자연수임)개의 사전 설정된 획득 시간마다 수신함으로써, 매일 k개의 SONAR 이미지들을 획득하는 이미지 획득부;매일 k개의 SONAR 이미지들이 획득 완료될 때마다, k개의 SONAR 이미지들 각각을, 이미지에서 어군 객체를 식별하기 위한 사전 학습 완료된 어군 객체 식별 모델에 입력으로 인가하여, k개 SONAR 이미지들 각각에서 어군 객체를 식별하고, k개의 SONAR 이미지들 각각에서 식별된 어군 객체의 수를 성분으로 갖는 k차원의 객체 벡터를 생성한 후, k차원의 객체 벡터와 k차원의 객체 벡터가 생성된 날짜에 대한 정보를 서로 대응시켜 벡터 데이터베이스에 저장하는 벡터 생성부;상기 벡터 데이터베이스에 저장되어 있는 객체 벡터의 수를 확인하여 상기 벡터 데이터베이스에 저장되어 있는 객체 벡터의 수가 사전 설정된 기준 개수인 n(n은 3이상의 자연수임)개가 되면, 어군 생태계의 이상 여부를 판단하기 위한 판단 이벤트를 발생시키는 이벤트 발생부; 상기 판단 이벤트가 발생되면, 상기 벡터 데이터베이스에 저장되어 있는 n개의 객체 벡터들을 기초로, 어군 객체의 수가 감소 추세인지 여부를 판단하는 판단부;상기 n개의 객체 벡터들을 기초로, 어군 객체의 수에 대한 일별 변화 정도를 표상하는 변화 수치를 연산한 후, 상기 변화 수치를 사전 설정된 기준치와 비교하여 상기 변화 수치가 상기 기준치를 초과하는지 여부를 확인하는 수치 확인부; 및어군 객체의 수가 감소 추세인 것으로 판단되고, 상기 변화 수치가 사전 설정된 기준치를 초과하는 것으로 확인되는 경우, 어군 생태계에 이상이 있는 것으로 판단한 후, 어군 생태계에 이상이 있음을 지시하는 경고 메시지를 생성하여 관리자의 단말로 전송하는 메시지 전송부를 포함하는 어군 생태계 모니터링 시스템 장치.어군 생태계의 이상 여부를 감지하기 위한 어군 생태계 모니터링 시스템 장치의 동작 방법에 있어서,수중에서 SONAR(SOund Navigation And Ranging) 이미지를 획득하기 위한 SONAR 모듈이 탑재되어 있는 부이(buoy) 장치로부터, 상기 SONAR 모듈에 의해 촬영된 SONAR 이미지를 매일 k(k는 2이상의 자연수임)개의 사전 설정된 획득 시간마다 수신함으로써, 매일 k개의 SONAR 이미지들을 획득하는 단계;매일 k개의 SONAR 이미지들이 획득 완료될 때마다, k개의 SONAR 이미지들 각각을, 이미지에서 어군 객체를 식별하기 위한 사전 학습 완료된 어군 객체 식별 모델에 입력으로 인가하여, k개 SONAR 이미지들 각각에서 어군 객체를 식별하고, k개의 SONAR 이미지들 각각에서 식별된 어군 객체의 수를 성분으로 갖는 k차원의 객체 벡터를 생성한 후, k차원의 객체 벡터와 k차원의 객체 벡터가 생성된 날짜에 대한 정보를 서로 대응시켜 벡터 데이터베이스에 저장하는 단계;상기 벡터 데이터베이스에 저장되어 있는 객체 벡터의 수를 확인하여 상기 벡터 데이터베이스에 저장되어 있는 객체 벡터의 수가 사전 설정된 기준 개수인 n(n은 3이상의 자연수임)개가 되면, 어군 생태계의 이상 여부를 판단하기 위한 판단 이벤트를 발생시키는 단계; 상기 판단 이벤트가 발생되면, 상기 벡터 데이터베이스에 저장되어 있는 n개의 객체 벡터들을 기초로, 어군 객체의 수가 감소 추세인지 여부를 판단하는 단계;상기 n개의 객체 벡터들을 기초로, 어군 객체의 수에 대한 일별 변화 정도를 표상하는 변화 수치를 연산한 후, 상기 변화 수치를 사전 설정된 기준치와 비교하여 상기 변화 수치가 상기 기준치를 초과하는지 여부를 확인하는 단계; 및어군 객체의 수가 감소 추세인 것으로 판단되고, 상기 변화 수치가 사전 설정된 기준치를 초과하는 것으로 확인되는 경우, 어군 생태계에 이상이 있는 것으로 판단한 후, 어군 생태계에 이상이 있음을 지시하는 경고 메시지를 생성하여 관리자의 단말로 전송하는 단계를 포함하는 어군 생태계 모니터링 시스템 장치의 동작 방법.제6항 내지 제10항 중 어느 한 항의 방법을 컴퓨터와의 결합을 통해 실행시키기 위한 컴퓨터 프로그램을 기록한 컴퓨터 판독 가능 기록 매체.제6항 내지 제10항 중 어느 한 항의 방법을 컴퓨터와의 결합을 통해 실행시키기 위한 저장매체에 저장된 컴퓨터 프로그램., Ltext: 어업, prediction: 어업
323/1059 Row 323: application_number: 1020200160427, combined_string: invention_title: 해상 무선 통신 시스템 및 그 방법 abstract: 본 발명은 해상 무선 통신 시스템 및 그 방법에 관한 것으로서, 부이, 어선용 단말 장치, 관리선박용 단말 장치 또는 육상 관제 센터 간에 무선 통신을 수행하는 해상 무선 통신 시스템에 있어서, 상기 부이에 설치되어 적어도 하나 이상의 센서를 이용한 센싱 정보, 자신의 식별 정보와 위치 정보를 제공하고, 어구 유실을 포함한 이벤트 상황 발생시 통신 연결성을 보장하는 통신옵션을 변경하는 통신 모듈; 및 상기 어선용 단말 장치와 관리 선박용 단말 장치에 각각 설치되고, 적어도 하나 이상의 부이 및 육상 관제 센터와 LoRa(Long Range Low Power) 기반의 통신망을 통해 통신을 수행하여 어선 및 어구의 위치와 상황, 유실 어구의 위치를 포함한 각종 어업 정보를 제공하며, 정상 상황에서의 통신 옵션과 이벤트 상황에서의 통신 옵션을 다르게 설정하여 통신 연결 기능을 수행하는 게이트웨이 장치를 포함하되, 상기 부이의 통신 모듈, 어선 및 관리 선박에 설치된 게이트웨이 장치는 저전력 장거리 통신을 위해 상용(Public) 로라망을 통해 메인 통신 채널을 형성하고, 전파 음영 지역에서 상기 상용 로라망과의 메인 통신 연결을 해제한 후 사설 로라망(Private LoRa)을 통해 서브 통신 채널을 형성하는 것이다. claims: 부이, 어선용 단말 장치, 관리선박용 단말 장치 또는 육상 관제 센터 간에 무선 통신을 수행하는 해상 무선 통신 시스템에 있어서,상기 부이에 설치되어 적어도 하나 이상의 센서를 이용한 센싱 정보, 자신의 식별 정보와 위치 정보를 제공하고, 어구 유실을 포함한 이벤트 상황 발생시 통신 연결성을 보장하는 통신옵션을 변경하는 통신 모듈; 및상기 어선용 단말 장치와 관리 선박용 단말 장치에 각각 설치되고, 적어도 하나 이상의 부이 및 육상 관제 센터와 LoRa(Long Range Low Power) 기반의 통신망을 통해 통신을 수행하여 어선 및 어구의 위치와 상황, 유실 어구의 위치를 포함한 각종 어업 정보를 제공하며, 정상 상황에서의 통신 옵션과 이벤트 상황에서의 통신 옵션을 다르게 설정하여 통신 연결 기능을 수행하는 게이트웨이 장치를 포함하되,상기 부이의 통신 모듈, 어선 및 관리 선박에 설치된 게이트웨이 장치는 저전력 장거리 통신을 위해 상용(Public) 로라망을 통해 메인 통신 채널을 형성하고, 전파 음영 지역에서 상기 상용 로라망과의 메인 통신 연결을 해제한 후 사설 로라망(Private LoRa)을 통해 서브 통신 채널을 형성하고,상기 게이트웨이 장치는, 상기 부이의 통신 품질에 기반하여 부이별 적용되는 기준 확산계수를 설정하고, 상기 이벤트 상황 발생시 상기 기준 확산 계수보다 높은 확산계수로 변경하여 상기 부이와 통신을 수행하도록 통신 옵션을 변경하는 것인, 해상 무선 통신 시스템.부이, 어선용 단말 장치, 관리 선박용 단말 장치 또는 육상 관제 센터 간에 무선 통신을 수행하는 해상 무선 통신 방법에 있어서,a) 상기 어선용 단말 장치 또는 관리 선박용 단말 장치에 설치된 게이트웨이 장치는 상기 부이의 통신 품질에 기반하여 부이별 적용되는 기준 확산계수를 설정하는 단계;b) 상기 설정된 기준 확산계수를 이용하여 상기 부이와 통신을 수행하여, 상기 부이로부터 적어도 하나 이상의 센서를 이용한 센싱 정보, 자신의 식별 정보와 위치 정보를 수신하는 단계; 및 c) 상기 부이로부터 수신한 정보를 분석하여 상기 부이의 도난 또는 유실을 포함한 이벤트 상황이 감지되면, 상기 기준 확산 계수보다 높은 확산계수로 변경하여 상기 부이와 통신을 수행하는 단계를 포함하는 것인, 해상 무선 통신 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

324/1059 Row 324: application_number: 1020200160489, combined_string: invention_title: 어업 도구의 유실 모니터링 시스템 및 그 방법 abstract: 본 발명은 어업 도구의 유실 모니터링 시스템 및 그 방법에 관한 것으로서, 수중에 설치되는 어구에 탈착 가능하게 설치되고, 적어도 하나 이상의 센서를 이용하여 센싱 정보를 제공하며, 자신의 식별 정보와 위치 정보를 제공하는 부이(Buoy); 적어도 하나 이상의 부이에 자신의 어구 식별 정보를 등록하고, 상기 부이와 통신하여 자신의 부이 위치 정보를 확인하며, 자신의 어선 식별 정보, 자기 어선 위치 정보, 자기 어구 식별 정보 및 자기 부이 위치 정보를 포함한 어선 정보를 제공하는 어선용 단말장치; 및 기 설정된 관할 지역 내 어구 또는 어선에 대한 관리 기능을 수행하고, 상기 어선용 단말장치 또는 부이와 통신망을 통해 정보를 송수신하여, 상기 부이 위치 정보를 이용하여 부이 속도를 측정하고, 측정된 부이 속도가 기 설정된 기준 속도 범위를 벗어나면 예비 부이 유실 정보를 발생하고, 상기 예비 부이 유실 정보의 발생에 따라 상기 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경을 벗어난 경우에 최종 부이 유실 정보를 제공하는 육상 관제 센터를 포함하는 시스템일 수 있다. claims: 수중에 설치되는 어구에 탈착 가능하게 설치되고, 적어도 하나 이상의 센서를 이용하여 센싱 정보를 제공하며, 자신의 식별 정보와 위치 정보를 제공하는 부이(Buoy);적어도 하나 이상의 부이에 자신의 어구 식별 정보를 등록하고, 상기 부이와 통신하여 자신의 부이 위치 정보를 확인하며, 자신의 어선 식별 정보, 자기 어선 위치 정보, 자기 어구 식별 정보 및 자기 부이 위치 정보를 포함한 어선 정보를 제공하는 어선용 단말장치; 및기 설정된 관할 지역 내 어구 또는 어선에 대한 관리 기능을 수행하고, 상기 어선용 단말장치 또는 부이와 통신망을 통해 정보를 송수신하여, 상기 부이로부터 기설정시간 동안 수중 온도 정보와 수상 온도 정보를 포함한 센싱 정보를 수집하고, 상기 수중 온도 정보와 수상 온도 정보의 각 평균값의 차이가 기설정된 오차범위를 벗어나는 경우에 상기 부이 위치 정보를 이용하여 부이 속도를 측정하고, 측정된 부이 속도가 기 설정된 기준 속도 범위를 벗어나면 예비 부이 유실 정보를 발생하고, 상기 예비 부이 유실 정보의 발생에 따라 상기 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경을 벗어난 경우에 부이 또는 어구의 유실 정보를 제공하는 육상 관제 센터를 포함하되,상기 육상 관제 센터는, 상기 예비 부이 유실 정보가 발생된 이후에, 상기 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경 이내인 경우에 상기 예비 부이 유실 정보의 발생을 해제하고, 조류에 따른 부이 위치 변화 정보를 제공하는 것인, 어업 도구의 유실 모니터링 시스템. 부이를 이용하여 부이 또는 어구의 유실을 모니터링하기 위한 어업 도구의 유실 모니터링 방법에 있어서, a) 기 설정된 관할 지역 내 부이 위치 정보와 어선 정보를 주기적으로 획득하여 육상에서 부이 또는 어구의 유실 여부를 감지하여 알려주는 육상 관제 센터는 적어도 하나 이상의 부이에 자신의 어구 식별 정보를 등록 및 관리하는 어선용 단말 장치, 관할 지역 내 어업 지도 또는 어업 단속을 포함한 어업 관리 기능을 수행하면서 부이 또는 어구의 유실 정보에 따라 어구 스캐닝을 통해 유실된 어구를 회수하는 동작을 수행하기 위해 관리 선박에 설치된 관리 선박용 단말 장치, 및 어구에 설치되어 적어도 하나 이상의 센서를 이용한 센싱 정보를 제공하는 부이와 LoRa 기반의 통신 채널을 형성하는 단계; b) 상기 육상 관제 센터는 상기 통신 채널을 통해 부이 위치 정보 또는 센싱 정보를 주기적으로 획득하고, 기 설정된 시간 동안에 상기 부이로부터 수중 온도 정보와 수상 온도 정보를 포함한 센싱 정보를 수집하여, 상기 수중 온도 정보와 수상 온도 정보의 각 평균값의 차이가 기설정된 오차범위를 벗어나는 경우에, 상기 부이 위치 정보를 이용하여 부이 속도를 측정하여, 상기 측정된 부이 속도가 기 설정된 기준 속도 범위를 벗어나면 예비 부이 유실 정보를 발생하는 단계; 및 c) 상기 육상 관제 센터는 상기 예비 부이 유실 정보의 발생에 따라 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경을 벗어난 경우에 부이 또는 어구의 유실 정보를 생성하여 상기 어선용 단말 장치 또는 상기 관리 선박용 단말 장치로 전송하는 단계를 포함하되,상기 c) 단계는, 상기 예비 부이 유실 정보가 발생된 이후에, 상기 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경 이내인 경우에 상기 예비 부이 유실 정보의 발생을 해제하고, 조류에 따른 부이 위치 변화 정보를 제공하는 것인, 어업 도구의 유실 모니터링 방법., Ltext: 어업, prediction: 어업
325/1059 Row 325: application_number: 1020200158475, combined_string: invention_title: 어선용 웨어러블 선원 안전관리 시스템 abstract: 본 발명은 어선의 운항시나 조업시 발생할 수 있는 선원들의 안전사고를 예방하기 위한 안전관리 시스템에 관한 것으로서, 더욱 상세하게는 어선의 운항으로부터 조업작업에 이르기까지의 전과정에 걸쳐 사고의 위험에 처한 선원 당사자 또는 이를 발견한 다른 선원이 자신의 신체에 착용한 웨어러블 송수신기의 신호버튼을 이용하여 어선의 중앙통제장치로 사고위험신호를 즉시 전송시킬 수 있도록 하고, 상기 중앙통제장치에서는 선원들이 바다에 빠지는 안전사고가 주로 발생하는 운항모드와 선원들이 조업기계에 의하여 부상을 당하는 안전사고가 주로 발생하는 조업모드에 맞추어, 운항모드시에는 어선의 운항속도를 감속시키거나 어선의 운항을 일시 정지시키는 한편, 조업모드시에는 특정 조업기계 또는 갑판상에 설치된 모든 조업기계의 작동을 일시 중지시킨 다음, 나머지 선원들에게 사고위험의 발생상황을 일괄적으로 신속히 전달시키는 관리조치를 수행함에 따라, 안전사고에 의한 인명피해가 발생하기 이전에 해당 피해를 유발시키는 가장 큰 위험요소를 어선 내부에서 선원들과 중앙통제장치간의 직접적이며 빠른 정보교환을 거쳐 신속하고 안전하게 무마시킬 수 있는 동시에, 사고위험신호를 전송한 선원 이외의 다른 모든 선원들이 즉시 집결하여 현장수습과 후속처리에 협력함으로서 정상작업으로의 조기복귀가 가능토록 한 어선용 웨어러블 선원 안전관리 시스템에 관한 것이다. claims: 어선(10)의 운항으로부터 조업작업을 수행하는 과정에 이르기까지 어선(10)에 승선한 선원의 안전사고를 예방하는 어선용 안전관리 시스템에 있어서,사고의 위험에 처한 선원 당사자 또는 상기 선원을 발견한 다른 선원이 자신의 신체에 착용한 웨어러블(Wearable) 송수신기(11)의 신호버튼(15)을 이용하여 사고위험신호를 어선(10)의 중앙통제장치(20)로 전송시키는 신호전송단계와, 어선(10)의 중앙통제장치(20)로 수신된 사고위험신호를 선원별로 부여된 송수신기(11)의 고유번호에 맞추어 구분하는 신호판단단계와, 어선(10)의 운항모드시에는 중앙통제장치(20)에서 어선(10)의 운항속도를 감속시키거나 어선(10)의 운항을 정지시키고, 어선(10)의 조업모드시에는 중앙통제장치(20)에서 갑판(2)상에 설치된 조업기계의 작동을 중지시키는 관리조치단계를 포함하여서 이루어지며,상기 운항모드시의 관리조치단계에서는 중앙통제장치(20)에서 어선(10)의 운항속도를 감속시키거나 어선(10)의 운항을 정지시키는 단계를 거친 직후, 상기 신호판단단계에서 사고위험신호가 발신된 것으로 판단된 선원의 송수신기(11)를 제외한 나머지 선원의 송수신기(11)로 알람신호를 송출하는 단계와, 알람신호를 수신받은 선원들에 의한 후속처리 이후의 시스템 리셋 단계가 추가로 수행되는 것을 특징으로 하는 어선용 웨어러블 선원 안전관리 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

326/1059 Row 326: application_number: 1020200128506, combined_string: invention_title: 양식장용 산소 용해 장치 abstract: 본 발명은 양식장에 공급되는 해수에 산소를 투입하여 용존산소율을 향상하기 위해 양식장에 공급되는 해수가 유입되는 유입파이프(100)와, 상기 유입파이프로 유입되는 해수에 기화된 산소를 공급하는 산소공급구(200)와, 상기 유입파이프에 연결되어 산소와 해수가 혼합되어 공급되는 혼합공급구(300)를 구한 양식장용 산소용해장치에 있어서,상기 혼합공급구(300)가 상부에 설치되고, 혼합공급구(300)를 통해 유입된 해수에 혼합 유입된 기체산소가 용해되는 산소용해통체(400)와, 상기 산소용해통체(400) 내부에 설치되어 공급되는 산소의 압력에 따라 수위가 조절될 수 있도록 해수 유출면적이 조절되는 산소용해파이프(500)를 구비하며, 상기 산소용해파이프(500)의 단부에 연결되어 산소용해통체(400)의 외부로 해수가 배출되는 배출구(600)를 구비하여 형성된 것을 특징으로 하는 양식장용 산소용해장치를 제공한다. claims: 양식장에 공급되는 해수에 산소를 투입하여 용존산소율을 향상하기 위해 양식장에 공급되는 해수가 유입되는 유입파이프(100)와, 기화된 산소를 공급하는 산소공급구(200)와, 상기 유입된 산소와 해수가 혼합되면서 공급된 산소가 해수에 용해되는 양식장용 산소용해장치에 있어서,상기 양식장용 산소용해장치는 상부에는 공급된 기체 산소와 해수가 혼합되는 혼합공간부(A)와 상기 혼합공간부(A) 하부에는 해수가 일정한 해수 수위(410)를 가지는 해수공간부(B)와, 상기 해수공간부(B) 하부에 배출구(600)를 구비한 산소용해통체(400)로 이루어지며,또한, 상기 산소용해통체(400) 내부에서 배출구(600)와 연결되는 산소용해파이프(500)를 더 구비하며,상기 산소용해파이프(500)는 상기 배출구(600)와 수평방향으로 연결되는 수평파이프(510)와,상기 수평파이프(510)와 수직 방향으로 연결되는 수직파이프(520)로 이루어지며,상기 산소용해파이프(500)에는 일정한 간격으로 통공되어 형성된 해수 유출홀(530)이 구비되고,상기 해수공간부(B)의 해수가 해수 유출홀(530)을 통하여 산소용해파이프(500)에 연결된 상기 배출구(600)로 배출되되,상기 혼합공간부(A) 내의 압력을 일정하게 유지될 수 있도록 상기 혼합공간부(A) 압력에 따라 해수가 산소용해파이프(500)로 배출되는 해수유출 면적(M3)이 변경되며,상기 해수유출 면적(M3)의 변경은 혼합공간부(A)의 압력에 의하여 해수공간부(B)의 해수 수위(410)가 변화되고, 상기 해수 수위(410)의 변화에 의하여 해수공간부(B)에서 수직파이프(520)에 형성된 해수가 유입되는 해수 유출홀(530)의 개수가 변경됨에 따라 해수가 유출되는 면적이 변경되는 것을 특징으로 하는 양식장용 산소용해장치., Ltext: 어업, prediction: 임업
327/1059 Row 327: application_number: 1020200125213, combined_string: invention_title: 생태교란 어종의 생태 조사 및 포획시스템 abstract: 본 발명은 댐이나 저수지 등 생태교란 어종의 서식이 예상되는 구역에 배치되어, 상기 구역에 수중을 원격으로 탐사하여 생태 교란 어종의 생태 여부와 생태 현황의 실시간 분석을 도모하여, 효율성 높은 생태교란 어종의 퇴치가 가능하도록 하는 생태교란 어종의 생태 조사 및 포획시스템에 관한 것으로,본 발명에서는 수면에 부양된 탐색정에 탑재되어, 탐색지역의 수중에 초음파를 조사하여 수중지형과 수중에 생태하는 어군들이 표식된 초음파 탐색지역 영상을 수득하는 초음파 어군 탐지부와; 상기 초음파 어군 탐색부를 통해 탐색되는 초음파 영상을 분석하여 어군 패턴을 추출하고 상기 추출된 어군 패턴들을 분석하여서, 생태교란 어종의 군집구역을 판독하는 생태교란 어종 군집구역 판독부와; 상기 생태교란 어종 군집구역 판독부에 의해 판독된 생태교란 어종 군집구역에 입수하여 탑재된 카메라 모듈을 통해 해당 군집구역의 지형과 생태교란 어종을 촬영하여서, 생태교란 어종 군집구역의 생태 영상을 수득하는 입수형 군집 영상 수득부를 포함하여 구성된 것을 특징으로 한다. claims: 수면에 부양된 탐색정에 탑재되어, 탐색지역의 수중에 초음파를 조사하여 수중지형과 수중에 생태하는 어군들이 표식된 초음파 탐색지역 영상을 수득하는 초음파 어군 탐지부와; 상기 초음파 어군 탐색부를 통해 탐색되는 초음파 영상을 분석하여 어군 패턴을 추출하고 상기 추출된 어군 패턴들을 분석하여서, 생태교란 어종의 군집구역을 판독하는 생태교란 어종 군집구역 판독부와; 상기 생태교란 어종 군집구역 판독부에 의해 판독된 생태교란 어종 군집구역에 입수하여 탑재된 카메라 모듈을 통해 해당 군집구역의 지형과 생태교란 어종을 촬영하여서, 생태교란 어종 군집구역의 생태 영상을 수득하는 입수형 군집 영상 수득부를 포함하고,상기 입수형 군집 영상 수득부는 수밀형 함체와; 상기 수밀형 함체에 수밀구조로 배치되어 수중 영상을 수득하는 카메라 모듈과; 상기 수밀형 함체에 탑재되어 수밀형 함체의 유형에 따른 추력을 생성하는 추력모듈과; 상기 수밀형 함체에 탑재되어, 초음파 어군 탐지부를 통해 조사되는 초음파에 의해 수중에서의 위치가 식별되도록 하는 초음파 식별모듈을 포함하되,상기 초음파 식별모듈은, 수밀형 함체의 외부에 노출되는 팽창튜브와; 상기 팽창튜브를 탄지하여 팽창되도록 하는 탄지 스프링과; 상기 탄지 스프링과 결속된 와이어를 와인딩, 또는 언와인딩하여 탄지 스프링의 수축상태를 조절하여 팽창튜브의 부피를 조절하는 권취부재를 포함하여 구성된 부피 증감형인 것을 특징으로 하는 생태교란 어종의 생태 조사 및 포획시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

328/1059 Row 328: application_number: 1020200108976, combined_string: invention_title: 수상드론을 이용한 양식장 감시 방법 abstract: 본 발명에 따른 수상드론을 이용한 양식장 감시 방법은, 양식장 주위를 운항하며 영상을 획득하는 제1단계와, 획득한 영상 데이터를 임시 저장하는 제2단계와, 기준 이미지와 현재 프레임 이미지를 비교하여 그 변화량을 산출하는 제3단계와, 상기 변화량이 임계값보다 큰 경우 이상 상태로 판단하여 단말에 알람을 송출하는 제4단계와, 이상이 감지된 프레임의 일정 프레임 이전부터 영상 데이터를 영구 저장하는 제5단계를 포함하여 구성된다. claims: 수상드론을 이용한 양식장 감시 방법으로서,양식장 주위를 운항하며 영상을 획득하는 단계와,획득한 영상 데이터를 임시 저장하는 단계와,기준 이미지와 현재 프레임 이미지를 비교하여 그 변화량을 산출하는 단계와,상기 변화량이 임계값보다 큰 경우 이상 상태로 판단하여 단말에 알람을 송출하는 단계와,이상이 감지된 프레임의 일정 프레임 이전부터 영상 데이터를 영구 저장하는 단계와,상기 수상드론의 제1센서부가 측정한 수온 및 제2센서부가 측정한 대기 환경 데이터를 입력받아 목표 수심의 수온을 추정하는 단계를 포함하며,상기 제1센서부는 상기 수상드론의 선저부에 위치하며, 상기 제2센서부는 해수면 위로 노출되도록 상기 수상드론의 선체부에 설치되며,상기 목표 수심 수온 추정 단계는, 상기 제1센서부에 의해 측정된 센서 위치 수심의 수온과 상기 제2센서부에 의해 측정된 대기 온도, 조도, 습도, 풍량 및 각 목표 수심의 수온과 측정 시각을 가지고 학습된 인공지능 신경망을 이용하는 것인수상드론을 이용한 양식장 감시 방법., Ltext: 어업, prediction: 어업
329/1059 Row 329: application_number: 1020200108148, combined_string: invention_title: 플랑크톤 채집장치 abstract: 본 발명은 플랑크톤 채취장치에 관한 것으로, 유체가 통과되도록 유로가 상하로 관통되는 본체와, 상기 유로의 내부에 상하로 길이를 갖도록 설치되는 지지대 및, 하부의 체결관이 상기 지지대의 측면을 감싸는 상태로 결합되고, 다수의 메쉬홀이 형성된 상부의 메쉬망이 상기 지지대의 측면을 감싸는 채집부를 포함하며, 상기 메쉬망은 상기 본체가 수중으로 하강시 수압에 의해 상단이 상기 지지대의 측면 방향으로 축소되고, 상기 본체가 수중에서 상승시 수압에 의해 상단이 상기 지지대의 측면과 이격되는 방향으로 확장되는 것을 특징으로 한다. claims: 유체가 통과되도록 유로가 상하로 관통되는 본체;상기 유로의 내부에 상하로 길이를 갖도록 설치되는 지지대; 및하부의 체결관이 상기 지지대의 측면을 감싸는 상태로 결합되고, 다수의 메쉬홀이 형성된 상부의 메쉬망이 상기 지지대의 측면을 감싸는 채집부;를 포함하며,상기 메쉬망은 상기 본체가 수중으로 하강시 수압에 의해 상단이 상기 지지대의 측면 방향으로 축소되고, 상기 본체가 수중에서 상승시 수압에 의해 상단이 상기 지지대의 측면과 이격되는 방향으로 확장되는 것을 특징으로 하는 플랑크톤 채집장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

330/1059 Row 330: application_number: 1020200100373, combined_string: invention_title: 스마트양식장을 위한 방법 및 장치 abstract: 본 명세서는 스마트양식을 위한 제어장치의 스마트양식 시스템을 제어하는 제어방법에 있어서, 사용자로부터 수신받은 입력값을 통해, 수조에 대응하는 ID(identification) 별로 사육정보를 등록하는 단계; 상기 등록된 ID와 대응되는 수조로부터, 상기 수조에 포함된 센서를 통해 생성되는 제1 센싱데이터를 수신하는 단계; 상기 제1 센싱데이터를 이용하여, 상기 수조의 상태를 모니터링하는 단계; 상기 모니터링의 결과값을 디스플레이부에 디스플레이하는 단계; 상기 모니터링을 통해, 제어 이벤트를 감지하는 단계; 및 상기 제어 이벤트에 근거하여, 상기 수조로, 상기 수조의 동작모듈을 제어하기 위한 제1 제어메시지를 전송하는 단계; 를 포함하며, 상기 센서는 수온 센서, 용존산소 센서, ph 센서, 수위 센서 및 먹이활동성 센서를 포함할 수 있다. claims: 제어장치가 스마트 양식장을 제어하는 제어방법에 있어서,사용자로부터 수신받은 입력값을 통해, 수조에 대응하는 ID(identification) 별로 사육정보를 등록하는 단계;상기 등록된 ID와 대응되는 수조로부터, 상기 수조에 포함된 센서를 통해 생성되는 제1 센싱데이터를 수신하는 단계;상기 제1 센싱데이터를 이용하여, 상기 수조의 상태를 모니터링하는 단계;상기 모니터링의 결과값을 디스플레이부에 디스플레이하는 단계;상기 모니터링을 통해, 제어 이벤트를 감지하는 단계;상기 제어 이벤트에 근거하여, 상기 수조로, 상기 수조의 동작모듈을 제어하기 위한 제1 제어메시지를 전송하는 단계;상기 제어 이벤트가 먹이 공급을 지시하는 이벤트인 경우, 먹이 공급부 및 상기 수조로 상기 먹이 공급을 지시하는 이벤트와 관련된 수조에 먹이를 공급하기 위한 제2 제어메시지를 전송하는 단계;상기 수조로부터, 먹이활동성 센서로부터 생성된 센싱데이터가 포함된 제2 센싱데이터를 수신하는 단계;상기 제2 센싱데이터를 이용하여, 상기 수조의 먹이활동성을 측정하는 단계; 및상기 측정된 먹이활동성에 근거하여, 상기 수조로 제3 제어메시지를 전송하는 단계;를 포함하며,상기 센서는 수온 센서, 용존산소 센서, ph 센서, 수위 센서 및 상기 먹이활동성 센서를 포함하고,상기 먹이활동성 센서는 상기 수조의 수면 상에 부유하여, 상기 수면의 움직임을 측정하며,상기 제2 센싱데이터는 상기 먹이활동성 센서를 통해, 생성되는 3축 가속도의 벡터값을 포함하고,상기 수조의 먹이활동성을 측정하는 단계는기설정된 1) 상기 센싱데이터의 센싱주기, 및 2) 상기 센싱데이터의 참조갯수에 근거하여:상기 먹이가 공급되기 전에, 센싱된 상기 3축 가속도의 벡터값에 근거하여, 재귀적으로 이동평균의 기준값을 계산하는 단계;상기 먹이가 공급된 이후에, 센싱된 상기 3축 가속도의 벡터값에 근거하여, 재귀적으로 이동평균의 현재값을 계산하는 단계; 및상기 이동평균의 기준값 및 상기 이동평균의 현재값에 근거하여, 상기 먹이활동성을 측정하는 단계;를 포함하는, 제어방법.스마트 양식장을 제어하는 제어장치에 있어서,메모리;송수신부;디스플레이부; 및상기 메모리, 상기 송수신부 및 상기 디스플레이부를 기능적으로 제어하는 프로세서;를 포함하고,상기 프로세서는사용자로부터 수신받은 입력값을 통해, 수조에 대응하는 ID(identification) 별로 사육정보를 상기 메모리에 등록하고,상기 송수신부를 통해, 상기 등록된 ID와 대응되는 수조로부터, 상기 수조에 포함된 센서를 통해 생성되는 제1 센싱데이터를 수신하며,상기 제1 센싱데이터를 이용하여, 상기 수조의 상태를 모니터링하고,상기 모니터링의 결과값을 상기 디스플레이부에 디스플레이하고,상기 모니터링을 통해, 제어 이벤트를 감지하며,상기 송수신부를 통해, 상기 제어 이벤트에 근거하여, 상기 수조로, 상기 수조의 동작모듈을 제어하기 위한 제1 제어메시지를 전송하며,상기 제어 이벤트가 먹이 공급을 지시하는 이벤트인 경우, 먹이 공급부 및 상기 수조로 상기 먹이 공급을 지시하는 이벤트와 관련된 수조에 먹이를 공급하기 위한 제2 제어메시지를 전송하고,상기 수조로부터, 먹이활동성 센서로부터 생성된 센싱데이터가 포함된 제2 센싱데이터를 수신하며,상기 제2 센싱데이터를 이용하여, 상기 수조의 먹이활동성을 측정하고,상기 측정된 먹이활동성에 근거하여, 상기 수조로 제3 제어메시지를 전송하며,상기 센서는 수온 센서, 용존산소 센서, ph 센서, 수위 센서 및 상기 먹이활동성 센서를 포함하고,상기 먹이활동성 센서는 상기 수조의 수면 상에 부유하여, 상기 수면의 움직임을 측정하며,상기 제2 센싱데이터는 상기 먹이활동성 센서를 통해, 생성되는 3축 가속도의 벡터값을 포함하고,상기 프로세서는상기 먹이활동성을 측정하기 위해,기설정된 1) 상기 센싱데이터의 센싱주기, 및 2) 상기 센싱데이터의 참조갯수에 근거하여:상기 먹이가 공급되기 전에, 센싱된 상기 3축 가속도의 벡터값에 근거하여, 재귀적으로 이동평균의 기준값을 계산하고,상기 먹이가 공급된 이후에, 센싱된 상기 3축 가속도의 벡터값에 근거하여, 재귀적으로 이동평균의 현재값을 계산하며,상기 이동평균의 기준값 및 상기 이동평균의 현재값에 근거하여, 상기 먹이활동성을 측정하는, 제어장치., Ltext: 어업, prediction: 임업
331/1059 Row 331: application_number: 1020200100615, combined_string: invention_title: 돌망태를 이용한 해삼 양식장 및 그 시공방법 abstract: 본 발명은 돌망태를 이용한 해삼 양식장 및 그 시공방법에 관한 것으로서, 파도의 영향으로 인한 해삼의 유실을 방지하는 가운데 친환경 돌망태를 이용하여 해삼의 생장에 필요한 다양한 요소를 구비한 생태환경을 제공하기 위한 것이다.이를 실현하기 위한 본 발명은, 그물망(11)의 내부에 다수의 골재(20)가 채워져 구성되는 돌망태(10)를 이용하여 해삼 양식장을 조성함에 있어서, 해삼의 양식이 이루어지는 양식공간(A)을 일정 면적으로 형성시키기 위해 다수의 돌망태를 선형으로 배치하는 양식공간 형성구간(100)과; 상기 양식공간 형성구간(100) 주변을 둘러싸는 형태로 다수의 돌망태(10)를 다층의 선형으로 배치하여 파도의 영향을 차단하는 쇄파 상쇄구간(200, 300, 400);을 포함하는 구성을 이루는 것을 특징으로 한다. claims: 그물망(11)의 내부에 다수의 골재(20)가 채워져 구성되는 돌망태(10)를 이용하여 해삼 양식장을 조성함에 있어서,해삼의 양식이 이루어지는 양식공간(A)을 일정 면적으로 형성시키기 위해 다수의 돌망태를 선형으로 배치하는 양식공간 형성구간(100)과;상기 양식공간 형성구간(100) 주변을 둘러싸는 형태로 다수의 돌망태(10)를 다층의 선형으로 배치하여 파도의 영향을 차단하는 쇄파 상쇄구간(200, 300, 400);을 포함하고,상기 쇄파 상쇄구간(200, 300, 400)은 최 외곽에 형성되는 1차 쇄파 상쇄라인(400)과, 그 내측에 일정 간격을 이루어 순차적으로 형성되는 2차 쇄파 상쇄라인(300) 및 3차 쇄파 상쇄라인(200)으로 이루어지며, 그중 1차 쇄파 상쇄라인(400)은 돌망태(10)를 2단~4단으로 쌓아서 일정 높이로 적층 시키고, 상기 각각의 쇄파 상쇄구간(200, 300, 400) 사이에는 멸치, 다시마, 미역을 갯벌, 흙과 섞어서 열을 가하지 아니하고 압축한 형상으로 제작한 시비재(30)가 구비됨을 특징으로 하는 돌망태를 이용한 해삼 양식장.그물망(11)의 내부에 다수의 골재(20)가 채워져 구성되는 돌망태(10)를 이용하여 해삼 양식장을 조성함에 있어서,해삼의 양식이 이루어지는 양식공간(A)을 일정 면적으로 형성시키기 위해 다수의 돌망태를 선형으로 배치하는 양식공간 형성구간(100)과;상기 양식공간 형성구간(100) 주변을 둘러싸는 형태로 다수의 돌망태(10)를 다층의 선형으로 배치하여 파도의 영향을 차단하는 쇄파 상쇄구간(200, 300, 400);을 포함하고,상기 양식공간(A)에는 멸치, 다시마, 미역을 갯벌, 흙과 섞어서 육면체 형상으로 제작한 시비재(30) 및 어린 치삼의 생장공간(41)이 반원의 동굴 형태로 형성된 해삼전용 어초(40)가 구비됨을 특징으로 하는 돌망태를 이용한 해삼 양식장.청구항 1 또는 청구항 3의 해삼 양식장을 시공함에 있어서,수중에 돌망태를 배치하여 해삼의 양식이 이루어지는 양식공간을 일정 면적으로 형성시키기 위해 다수의 돌망태를 선형으로 배치하여 양식공간 형성구간을 시공한 후, 상기 양식공간 형성구간 주변을 둘러싸는 형태로 다수의 돌망태를 선형으로 배치하여 파도의 영향을 차단하는 쇄파 상쇄구간을 시공하는 것을 특징으로 하는 돌망태를 이용한 해삼 양식장 시공방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

332/1059 Row 332: application_number: 1020200077973, combined_string: invention_title: 빅데이터를 이용한 인공지능 기술 기반 이상징후 표적 감지 방법 및 그 시스템 abstract: 본 개시(disclosure)의 다양한 실시 예들에 따르면, 바다를 항해하는 표적의 이상징후를 감지하기 위한 이상징후표적 감지 시스템은, 항해 표적을 탐지하여 항해 표적 정보를 출력하는 레이더, 서버로부터 미리 등록된 표적들에 대한 저장 표적 정보를 선박식별장치에게 전달하는 서버, 상기 항해 표적 정보와 상기 저장 표적 정보를 융합하여 상기 항해 표적의 이상징후 여부를 결정하고, 상기 이상징후 여부를 표시하는 선박식별장치를 포함할 수 있다. claims: 바다를 항해하는 표적의 이상징후를 감지하기 위한 이상징후표적 감지 시스템에 있어서,항해 표적을 탐지하여 항해 표적 정보를 출력하는 레이더;미리 등록된 표적들에 대한 저장 표적 정보를 선박식별장치에게 전달하는 서버; 및상기 레이더로부터 상기 항해 표적 정보가 수신될 때마다 상기 항해 표적 정보의 수신 시간 및 상기 표적의 표적 위치 정보를 획득하고, 상기 표적 위치 정보를 상기 수신 시간에 동기화시켜 상기 표적의 예측 위치 정보를 획득하고, 상기 예측 위치 정보와 상기 저장 표적 정보를 융합하여 선박의 위치 정보, 크기 정보, 이동 경로 정보, 예측 경로 정보 중 적어도 하나 이상을 포함하는 빅데이터 분석 정보를 생성하고, 상기 빅데이터 분석 정보와 상기 항해 표적 정보를 비교하고, 상기 비교에 기반하여 상기 항해 표적의 이상징후 여부를 결정하고, 상기 이상징후 여부를 표시하는 선박식별장치;를 포함하고,상기 선박식별장치는, 상기 항해 표적이 상기 저장 표적 정보가 포함하는 기등록된 표적들에 포함되어 있는지 여부를 결정하고, 포함되어 있으면, 상기 항해 표적 정보를 상기 저장 표적 정보와 융합하고, 포함되어 있지 않으면, 상기 항해 표적을 제1 이상징후 표적으로 결정하고, 상기 제1 이상징후 표적을 표시하고, 상기 제1 이상징후 표적의 항해 표적 정보와 상기 저장 표적 정보를 융합하여 상기 제1 이상징후 표적의 과거 이동 경로를 나타내는 이동 경로 정보를 생성하고, 상기 생성된 과거 이동 경로와 상기 제1 이상징후 표적의 실제 경로를 비교하고, 상기 제1 이상징후 표적의 과거 이동 경로와 상기 제1 이상징후 표적의 실제 경로가 일치하지 않으면 상기 제1 이상징후 표적을 제2 이상징후 표적으로 결정하고, 상기 제2 이상징후 표적을 표시하는 시스템., Ltext: 어업, prediction: 어업
333/1059 Row 333: application_number: 1020200072507, combined_string: invention_title: 어구를 식별하는 스마트부이 abstract: 본 발명은 어구를 식별하는 스마트부이에 관한 것으로서, 더욱 상세하게는 스마트부이를 소형화 하여 스마트부이의 파손을 방지하고, 외부전원 없이도 스마트부이의 충전이 용이한 어구를 식별하는 스마트부이에 관한 것이다. claims: 스마트부이로서,투명재질의 상부케이스;안테나기판 및 상기 안테나기판 상에 형성되어 있는 안테나패턴을 포함하는 안테나모듈;제1PCB기판, 상기 제1PCB기판 상에 배치되는 MCU, 상기 안테나패턴을 통하여 통신을 수행하는 통신모듈, GNSS안테나, 및 GNSS모듈을 포함하는 제1PCB부;상기 안테나모듈의 위치를 고정시키고, 상기 제1PCB부를 내부에서 보호하는 보호케이스;전력관리를 수행하는 제2PCB부;배터리모듈;상기 배터리를 충전하는 충전모듈; 및하부케이스를 포함하고,상기 상부케이스와 상기 하부케이스에 의하여 형성되는 공간에 상기 안테나모듈, 제1PCB부, 보호케이스, 제2PCB부, 배터리모듈, 및 충전모듈이 배치되고,상기 보호케이스의 상면에는 안테나모듈고정슬롯이 형성되어 있고,상기 안테나모듈고정슬롯은 상기 안테나기판의 일부를 지지하고,상기 안테나기판과 상기 제1PCB기판은 서로 수직하는 형태로 접합되어 있는,스마트부이., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

334/1059 Row 334: application_number: 1020200066527, combined_string: invention_title: 유해 조류 퇴치 시스템 abstract: 본 발명은 유해 조류 퇴치 시스템을 개시한다. 이러한 본 발명은 감시영역내에서 레이저 광원을 조사하는 위치 고정형의 메인 조류 퇴치기, 그리고 상기 메인 조류 퇴치기와 연동되는 위치 이동형의 타겟 조류 퇴치기를 구성한 것이고, 이에따라 음영지역없이 감시영역 전체에 대한 조류 퇴치의 효율성을 높이면서, 공항이나 공군 비행장에서 비행기의 이착륙시 충돌로 인한 인적, 경제적 피해, 과수원이나 양식장 등에서의 농작물이나 양식 어류 피해, 그리고 축산, 양계, 가금 농가에 조류 인플루엔자(Al) 바이러스 전파 피해와 대형 공장이나 물류 창고 건물의 조류 배설물 피해 등을 방지하는 것이다. claims: 케이블을 통해 공급되는 전원을 분배하는 전원 분배부와, 상기 전원분배부와 전기적으로 연결되는 하나 또는 복수의 격납부를 가지는 고정대; 상기 고정대의 상단에 설치되어 상기 전원분배부로부터 구동전원을 공급받으며 제 1 팬틸트 구동부에 의해 회전되는 것으로 설정된 감시영역내에서 조류 출몰 여부를 감지한 후 그 감지신호와 방위각을 전송하는 조류 감지기; 상기 고정대의 상단에 고정 설치되어 상기 전원분배부로부터 구동전원을 공급받는 것으로 상기 조류 감지기에 의해 감지된 조류 감지 정보와 방위각 정보가 입력시 조류 감지 위치로 레이저 광원을 자동 조사하는 위치 고정형의 메인 조류 퇴치기; 및, 상기 고정대의 상기 격납부에 분리 가능하게 장착되면서 상기 메인 조류 퇴치기와 통신 연결되어 조류 감지 정보와 방위각 정보를 공유받으며 상기 격납부로부터 분리된 후 조류 감지 위치로 이동시 상기 메인 조류 퇴치기에서 레이저 광원이 조사되지 못하는 음영지역에 수동 또는 자동으로 레이저 광원을 타겟 조사하는 위치 이동형의 타겟 조류 퇴치기; 를 포함하고,상기 조류감지기는 조류 감지정보와 방위각 정보를 전송하기 위한 제 1 통신부와 감시 제어부 및, 상기 감시 제어부의 제어에 따라 상기 제 1 팬틸트 구동부가 팬틸트 구동시 그 팬틸트 구동에 따른 회전량으로 방위각을 산출한 후 이를 상기 제 1 통신부를 통해 상기 메인 조류 퇴치기로 전송하는 방위각 산출부를 포함하는 레이더 감지기인 것을 특징으로 하는 유해 조류 퇴치 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

335/1059 Row 335: application_number: 1020200060255, combined_string: invention_title: 양식장용 파이프 및 그 제조방법 abstract: 본 발명은 사용수명, 강도, 복원력 등이 우수하며, 해양 유래 부착 생물에 대해 방오 효과를 발휘하도록 한 양식장용 파이프 및 그 제조방법에 관한 것으로, 그 구성은 a) 폴리카보네이트 수지(polycarbonate resin) 60 - 80중량%와, 유리섬유(glass fiber) 20 - 40중량%를 혼합하여 수지 조성물을 수득하는 단계; b) 상기 a)단계의 수지 조성물을 인발가공 또는 압출가공 중에서 선택된 어느 하나의 가공방법을 통해 내경이 원형 또는 육각형상을 이루는 원형파이프 또는 육각파이프의 형태로서, 내부에 일정간격마다 구획 벽이 형성되게 성형하여 성형물을 형성하는 단계; c) 천연무기도료 80 - 90중량%와, 해중 생물이 달라붙는 것을 방지하기 위한 해중생물기피 조성물 10 - 20중량%를 혼합하여 혼합 도료를 수득하는 단계; d) 상기 c)단계의 혼합 도료를 상기 b)단계의 성형물에 도포하는 단계; 및 e) 상기 d)단계를 거친 성형물을 건조시킨 후, 원하는 길이로 절단하는 단계;를 포함하여 구성된다. claims: a) 폴리카보네이트 수지(polycarbonate resin) 60 - 80중량%와, 유리섬유(glass fiber) 20 - 40중량%를 혼합하여 수지 조성물을 수득하는 단계;b) 상기 a)단계의 수지 조성물을 인발가공 또는 압출가공 중에서 선택된 어느 하나의 가공방법을 통해 내경이 원형 또는 육각형상을 이루는 원형파이프 또는 육각파이프의 형태로서, 내부에 일정간격마다 구획 벽이 형성되게 성형하여 성형물을 형성하는 단계;c) 천연무기도료 80 - 90중량%와, 해중 생물이 달라붙는 것을 방지하기 위한 해중생물기피 조성물 10 - 20중량%를 혼합하여 혼합 도료를 수득하는 단계;d) 상기 c)단계의 혼합 도료를 상기 b)단계의 성형물에 도포하는 단계; 및e) 상기 d)단계를 거친 성형물을 건조시킨 후, 원하는 길이로 절단하는 단계;를 포함하여 구성되고,상기 c)단계의 천연무기도료는 제올라이트 분말, 순지트 분말, 토르말린 분말, 운모 분말, 맥반석 분말, 황토 분말, 현무암 분말, 화산송이 분말 중에서 선택된 어느 하나의 분말 또는 둘 이상의 분말을 배합하여 광물분말을 형성한 후, 그 광물분말을 800 - 900℃ 온도에서 소성한 다음 무기질 바인더 100중량부에 대하여 소성된 상기 광물분말 10 - 40중량부 및 물 20 - 80중량부를 혼합하여 제조된 것이며,상기 c)단계의 해중생물기피 조성물은 천연유황분말 40 - 60중량%, 고추분말 5 - 15중량% 및 잉글리쉬 아이비 잎, 투구꽃 뿌리, 피마자 씨앗, 묵주완두 씨, 협죽도 잎, 디펜바키아 잎, 포인세티아 잎, 크로톤 뿌리, 란타나 잎, 두루미천남성 줄기, 독미나리 뿌리, 미치광이풀 뿌리, 디기탈리스 잎, 사람주나무 뿌리 중에서 선택된 어느 하나 이상의 독성식물 추출물 35 - 45중량%를 포함하는 것을 특징으로 하는 양식장용 파이프 제조방법.양식장용 파이프에 있어서,내경이 원형 또는 육각형상을 이루는 원형파이프 또는 육각파이프의 형태로서, 내부에 일정한 간격으로 구획 벽이 형성된 성형물과;상기 성형물에 도포되는 혼합 도료;로 구성되고,상기 성형물은 폴리카보네이트 수지(polycarbonate resin) 60 - 80중량%와, 유리섬유(glass fiber) 20 - 40중량%를 혼합하여 된 수지 조성물을 인발가공 또는 압출가공 중에서 선택된 어느 하나의 가공방법을 통해 형성된 것이고,상기 혼합 도료는 제올라이트 분말, 순지트 분말, 토르말린 분말, 운모 분말, 맥반석 분말, 황토 분말, 현무암 분말, 화산송이 분말 중에서 선택된 어느 하나의 분말 또는 둘 이상의 분말을 배합하여 광물분말을 형성한 후, 그 광물분말을 800 - 900℃ 온도에서 소성한 다음 무기질 바인더 100중량부에 대하여 소성된 상기 광물분말 10 - 40중량부 및 물 20 - 80중량부를 혼합하여 제조된 천연무기도료 80 - 90중량%와, 천연유황분말 40 - 60중량%, 고추분말 5 - 15중량% 및 잉글리쉬 아이비 잎, 투구꽃 뿌리, 피마자 씨앗, 묵주완두 씨, 협죽도 잎, 디펜바키아 잎, 포인세티아 잎, 크로톤 뿌리, 란타나 잎, 두루미천남성 줄기, 독미나리 뿌리, 미치광이풀 뿌리, 디기탈리스 잎, 사람주나무 뿌리 중에서 선택된 어느 하나 이상의 독성식물 추출물 35 - 45중량%를 포함하는 해중생물기피 조성물 10 - 20중량%가 혼합된 것임을 특징으로 하는 양식장용 파이프., Ltext: 어업, prediction: 어업
336/1059 Row 336: application_number: 1020200053175, combined_string: invention_title: 유입과 배출 방출수의 효율적 활용이 가능한 양식장용 소수력 발전장치 abstract: 본 발명은 양식장의 방출수를 통해 발현되는 수력에너지를 통해 전기에너지로 얻기 위한 양식장용 소수력 발전장치를 구성함에 있어서: 양식장의 방출수를 수용하면서 배출이 가능하게끔 방출파이프와 배출파이프가 상호 연결되는 수용부; 수용부의 일 측편에 연통되어 발전파이프로 배출되는 방출수를 통해 발전기로부터 발전이 가능하도록 구현하는 발전부; 수용부의 배출파이프에 근접 형성되어 방출수의 외부 방출 및 차단을 위해 개폐가 가능하면서도 방출수의 역류 방지를 상시적으로 조절이 가능하게끔 차단판을 구비하는 조절수단; 및 발전파이프에 근접 형성되어 방출수의 발전을 위한 방출과 차단을 조절하는 개방판을 구비하고, 방출 시에 발생되는 강한 수압으로부터 개방판의 개방이 용이하도록 구성하는 개방수단을 포함함을 특징으로 한다.이러한 본 발명에 따르면, 양식장으로 24시간 내내 유입 · 방출되는 바닷물 등을 이용안 소수력 발전이 가능토록 하면서도, 기존에 설치된 양식장의 방출수 설비를 대폭 교체하지 않고도 설치가 가능하게끔 하며, 방출수의 배출을 통해 발전을 도모할 시 방출수를 차단하고 있던 개방판에 강한 수압이 발생할 경우 쉽게 개방되도록 하면서도 양식장으로 유입되는 방출수의 양과 배출되는 방출수의 양이 다를 경우에 발생되는 역류도 효율적으로 방지할 수 있도록 하는 효과를 제공한다. claims: 양식장에서 외부로 방출되는 방출수(1)를 통해 발현된 수력에너지를 전기에너지로 얻기 위한 양식장용 소수력 발전장치를 구성함에 있어서:상기 양식장으로부터 방출수(1)를 수용하면서 배출이 가능하게끔 방출파이프(11)와 배출파이프(12)가 상호 연결되는 수용부(10); 상기 수용부(10)의 일측에 연통되어 발전파이프(21)로 방출되는 방출수(1)를 통하여 발전기(22)로부터 발전이 가능하도록 구현하고, 수용부(10)로부터 유입되는 방출수(1)에 포함되어 있는 이물질을 제거하도록 메쉬망(23)을 구비하는 발전부(20);상기 수용부(10)의 배출파이프(12) 상에 근접 형성되어 방출수(1)의 외부 방출과 차단하도록 개폐가 가능하면서도 방출수(1)의 역류 방지를 상시적으로 조절이 가능하도록 차단판(31)을 구비하는 조절수단(30); 및상기 발전부(20)의 발전파이프(21)에 근접 형성되어 방출수(1)의 발전을 위한 방출과 차단을 조절하는 개방판(41)을 구비하고, 방출 시에 발생되는 수압으로부터 개방판(41)의 개방이 용이하도록 구성하는 개방수단(40);을 포함하여 이루어지되,상기 조절수단(30)의 차단판(31)은 방출수(1)의 외부 방출을 차단하면서도 개폐가 가능하도록 제1가이드(32)의 제1수직홈(33)에 삽설되어 개폐되도록 하고, 발전파이프(21)로 방출수(1)를 방출할 경우에는 방출수(1)의 역류방지 조절이 가능하도록 하기 위해 배출파이프(12)의 전체를 막지 않도록 구성하고,상기 개방수단(40)은 힌지(45)에 의해 개방판(41)의 회전이 가능하도록 형성되는 회전대(46)와, 회전대(46)의 일 측편에 좌우로의 회전에 의해 가이드홈(47)을 가압하여 개방판(41)이 기울어지도록 함으로써 작은 틈(C)이 발생되도록 하는 가압부(48)와, 타 측편에 연결되어 있는 회전대(46)에 회전조절용 핸들(49)을 구비한 뒤 작업자가 파지한 상태에서 방출수(1)의 배출 시에 발생되는 강한 수압으로부터 개방판(41)의 개방이 용이하도록 구성함을 특징으로 하는 유입과 배출 방출수의 효율적 활용이 가능한 양식장용 소수력 발전장치., Ltext: 어업, prediction: 임업

Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

337/1059 Row 337: application_number: 1020200052002, combined_string: invention_title: 양식장 슬러지 배출장치 abstract: 본 발명은 양식장 슬러지 배출장치에 관한 것으로, 더욱 상세하게는 배출관 내에 공기의 주입 조절이 가능한 에어백을 삽입하여 배출관에 형성된 배출공을 통한 슬러지 및 양식수의 배출을 조절하도록 함으로써, 양식장 내 슬러지와 배수관 내 슬러지의 배출이 효과적으로 이루어지도록 하고, 배출에 대한 제어가 용이하게 이루어질 수 있도록 하는 양식장 슬러지 배출장치에 관한 것이다. claims: 양식장 바닥에 매입되어 외부로 양식수를 배출하는 배수관과; 양식장 내에 삽입되어 배수관과 연결되며, 배출공이 관통되어 양식장 내의 슬러지를 배수관으로 배출하는 배출관과; 상기 배수관 및 배출관을 연결하는 배수연결부와; 상기 배출관을 통한 슬러지의 배출을 조절하는 배출조절부와; 상기 배출조절부의 작동을 조절하는 제어부;를 포함하고, 상기 배출조절부는 상기 배출관 내에 삽입되어 공기의 주입에 따라 배출공을 개폐하는 에어백과, 상기 배출관 내에 형성되어 에어백을 지지하는 받침지지대와, 상기 에어백에 대한 공기의 주입을 조절하는 공기주입수단을 포함하며, 상기 공기주입수단은 상기 배출관 상단으로 인입되어 에어백에 공기를 주입하는 주입관과, 상기 주입관에 대한 공기의 주입 및 배출을 조절하는 주입조절밸브와, 양식장 내에 연결되어 주입관으로 주입되는 공기를 순환시키는 공기순환관을 포함하고, 상기 배수연결부는, 상기 배출관의 둘레를 따라 끼워지며, 양식장 바닥에 포설되는 차수시트와 동일한 소재로 형성되어 차수시트와 부착되는 부착어댑터와; 상기 부착어댑터의 내측 둘레를 따라 접착되며, 상기 배출관과 동일한 소재로 형성되어 배출관에 부착되는 연결소켓과; 상기 부착어댑터에 차수시트를 고정시키는 시트고정수단;을 포함하고, 상기 시트고정수단은 상기 부착어댑터에 부착되어  형상으로 형성되는 지지프레임과, 상기 지지프레임에 삽입되어 탄성에 의해 차수시트를 관통·고정시키는 탄성고정체를 포함하며, 상기 탄성고정체는 상기 지지프레임 및 차수시트를 관통하는 관통부재와, 상기 관통부재의 상단에 형성되어 지지프레임 상부에 걸리는 걸림단과, 상기 관통부재의 둘레를 따라 돌출되어 차수시트를 누르는 누름단과, 상기 지지프레임 및 누름단 사이에 삽입되어 누름단을 하측으로 누르는 누름탄성부재를 포함하고, 상기 제어부는 상기 에어백에 대한 압력을 조절하는 압력조절부와, 상기 배수관 바닥에 쌓이는 슬러지의 양에 따라 자동으로 배출조절부를 작동시키는 배출작동부와, 슬러지의 처리 정도에 따라 배출조절부의 작동 상태를 진단하는 처리진단부를 포함하고, 상기 압력조절부는 상기 배출조절부의 작동개시정보를 수신하는 작동정보수신모듈과, 상기 주입조절밸브를 조작하여 에어백에 설정된 양의 공기를 주입하는 밸브조절모듈과, 상기 배출관의 배출공 주위에 형성되는 압력측정센서로부터 에어백의 접촉에 의한 압력정보를 수신하는 압력정보수신모듈과, 수신된 압력정보에 따라 주입조절밸브를 미세조절하는 미세조절모듈과, 상기 압력측정센서에 의해 측정된 압력과 초기 설정된 압력의 차를 산출하는 압력차산출모듈과, 산출된 압력차를 설정된 경계값과 비교하는 경계값비교모듈과, 압력차가 경계값을 초과하는 경우 에어백의 교체 필요를 알리는 교체알림모듈을 포함하며, 상기 배출작동부는 상기 배수관 내에 형성되어 배수관에 쌓이는 슬러지를 감지하는 슬러지센싱모듈과, 상기 슬러지센싱모듈에 의한 감지정보에 따라 슬러지의 양을 산출하는 슬러지양산출모듈과, 산출된 슬러지양을 복수의 구간으로 설정된 값과 비교하는 설정값비교모듈과, 슬러지양에 따른 구간에 따라 배출조절부의 작동시간을 설정하는 작동시간설정모듈과, 상기 배출조절부의 작동을 개시하는 작동개시모듈과, 상기 배출조절부의 작동개시 후 상기 슬러지센싱모듈에 의해 슬러지의 양을 감시하는 슬러지감시모듈과, 슬러지의 양이 일정값 이하로 줄어드는 경우 배출조절부의 작동을 중단하는 자동중단모듈과, 작업시간의 종료에도 슬러지의 양이 일정값 이하로 줄지 않는 경우 일정값이 될 때까지 배출조절부를 추가 작동시키는 추가작동모듈을 포함하고, 상기 처리진단부는 상기 슬러지센싱모듈에 의해 감지되는 초기 슬러지 양과 작동시간의 종료후 감지되는 슬러지의 양을 비교하여 처리율이 기준값 이하인 경우 배출조절부의 결함으로 판단하는 결함확정부와, 슬러지의 처리율이 결함으로 확정되는 기준값을 초과하는 근접범위에서 연속되는 경우 처리율의 저하정도와 연속정도에 따라 결함이 발생되는 시기를 예측하는 결함예측부와, 결함으로 확정되거나 결함시기가 예측되지 않더라도 슬러지의 처리율이 급격하게 떨어지는 경우 배출조절부에 대한 점검을 요청하는 점검요청부를 포함하며, 상기 결함확정부는 상기 작동시간설정모듈에 의해 설정된 작동시간의 종료정보를 수신하는 시간만료정보수신모듈과, 종료시점에 상기 슬러지센싱모듈에 의해 측정되는 슬러지의 양을 산출하는 잔여량산출모듈과, 초기 슬러지 양 및 잔여 슬러지양의 비율에 따라 처리율을 산정하는 처리율산정모듈과, 산정된 처리율을 기준값과 비교하는 기준값비교모듈과, 처리율이 기준값 이하인 경우 배출조절부의 결함으로 판정하여 이를 알리는 결함판정모듈을 포함하고, 상기 결함예측부는 슬러지의 처리율이 설정된 근접범위에 도달하는 것을 감지하는 근접범위감지모듈과, 근접범위에서 연속되는 경우 그 횟수를 산정하는 연속횟수산정모듈과, 처리율이 설정된 정상값에서 벗어나는 정도를 합산하여 결함지수를 산출하는 결함지수산출모듈과, 결함지수에 따라 결함으로 확정되는 시기를 예측하는 결함시기예상모듈을 포함하며, 상기 점검요청부는 슬러지 처리율이 저하 정도를 산정하는 저하율산정모듈과, 산정된 저하율을 임계값과 비교하는 임계값비교모듈과, 저하율이 임계값을 초과하는 경우 그 연속횟수를 산출하는 지속횟수산출모듈과, 연속횟수가 설정된 횟수를 초과하는 경우 점검을 지시하는 점검지시모듈을 포함하는 것을 특징으로 하는 양식장 슬러지 배출장치., Ltext: 어업, prediction: 임업
338/1059 Row 338: application_number: 1020200030101, combined_string: invention_title: 인공지능을 활용하여 생육 환경 복사가 가능한 바이오 플락 양식 시스템 abstract: 본 발명은 스마트 양식장 관리 시스템에 관한 것으로서, 대상 어류의 생육 데이터에 기반하여 하나 이상의 배양조와, 각 배양조에 설치되어 사육 환경과 어류 상태를 감지하여 센서 데이터를 제공하는 하나 이상의 센서를 포함하는 마스터 양식장에 대한 사육환경 데이터를 제공하고, 상기 센서로부터 전송되는 센서 데이터를 이용하는 인공 지능 기반의 양식 모델을 통해 각 배양조에 적용하기 위한 사료, 산소, 온도, 염분을 포함한 사육환경 변수를 조절하는 환경 제어 데이터를 제공하는 마스터 장치; 및 상기 마스터 장치와 통신망을 통해 연결되어 상기 마스터 장치의 사육환경 데이터를 이용하여 슬레이브 양식장에 적합한 사육환경 복제 데이터를 제공하고, 상기 사육환경 복제 데이터에 따른 상기 슬레이브 양식장이 완료됨을 알리는 양식장 완료 데이터가 수신되면 상기 환경 제어 데이터에 기반하여 상기 슬레이브 양식장에 적용하기 위한 환경 제어 복제 데이터를 제공하는 하나 이상의 슬레이브 장치를 포함할 수 있다. claims: 양식조에 설치된 복수의 센서를 통해 양식장을 관리하는 스마트 양식장 관리 시스템에 있어서, 대상 어류의 생육 데이터에 기반하여 하나 이상의 배양조와, 각 배양조에 설치되어 사육 환경과 어류 상태를 감지하여 센서 데이터를 제공하는 하나 이상의 센서를 포함하는 마스터 양식장에 대한 사육환경 데이터를 제공하고, 상기 센서로부터 전송되는 센서 데이터를 이용하는 인공 지능 기반의 양식 모델을 통해 각 배양조에 적용하기 위한 사료, 산소, 온도, 염분을 포함한 사육환경 변수를 조절하는 환경 제어 데이터를 제공하는 마스터 장치; 및상기 마스터 장치와 통신망을 통해 연결되어 상기 마스터 장치의 사육환경 데이터를 이용하여 슬레이브 양식장에 적합한 사육환경 복제 데이터를 제공하고, 상기 사육환경 복제 데이터에 따른 상기 슬레이브 양식장이 완료됨을 알리는 양식장 완료 데이터가 수신되면 상기 환경 제어 데이터에 기반하여 상기 슬레이브 양식장에 적용하기 위한 환경 제어 복제 데이터를 제공하는 하나 이상의 슬레이브 장치를 포함하되,상기 마스터 장치는 네트워크를 통해 상기 대상 어류에 관련된 먹이 및 행동 데이터들을 수집하여 빅데이터 분석을 통해 생육 데이터를 제공하고, 상기 인공 지능 기반의 양식 모델을 통해 상기 생육 데이터와 상기 센서데이터에 기반한 사육환경의 변수에 따라 사료 공급, 상기 대상 어류의 크기와 무게의 추정, 수온 및 용존 산소의 공급 조절을 포함한 환경 제어 데이터를 지속적으로 업그레이드하는 것인, 스마트 양식장 관리 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

339/1059 Row 339: application_number: 1020200025366, combined_string: invention_title: 생명 보호 장치 시스템 abstract: 본 발명은 생명 보호 장치 시스템에 관한 것으로서, 보다 구체적으로는 생명 보호 장치 시스템으로서, 이동체의 추락이나 충돌 시에 탑승자의 생명을 보호할 수 있도록 충격을 완화시킬 수 있도록 이동체에 장착되는 충격완화부와 쇼크업 쇼바 및 에어백을 구비하는 충격완화 장치; 상기 이동체에 가해지는 충격을 감지하기 위한 측정기; 상기 측정기의 감지되는 충격에 따라 미리 설정된 구동제어 신호를 발생시키는 제어기; 및 상기 제어기의 구동제어 신호에 대응하여 미리 설정된 재난센터로 재난발생을 알리고 도움을 요청하기 위한 인공지능부를 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 생명 보호 장치 시스템에 따르면, 이동체의 추락이나 충돌 시에 탑승자의 생명을 보호할 수 있도록 충격을 완화시킬 수 있도록 이동체에 장착되는 충격완화부와 쇼크업 쇼바 및 에어백을 구비하는 충격완화 장치와, 이동체에 가해지는 충격을 감지하기 위한 측정기와, 측정기의 감지되는 충격에 따라 미리 설정된 구동제어 신호를 발생시키는 제어기와, 제어기의 구동제어 신호에 대응하여 미리 설정된 재난센터로 재난발생을 알리고 도움을 요청하기 위한 인공지능부를 포함하여 구성함으로써, 드론이나 자율비행체 및 자율주행 자동차를 포함하는 이동체가 추락이나 충돌 시 또는 강이나 바다에 빠질 때에도 이동체의 탑승자에 가해지는 충격을 최소화하고, 그에 따른 긴급한 상황에서의 생명을 보호할 수 있도록 할 수 있다.또한, 본 발명의 생명 보호 장치 시스템에 따르면, 자율주행을 위한 이동체에 충격완화 장치의 충격완화부와 쇼크업 쇼바와 에어백 등을 장착함으로써, 이동체의 추락이나 충돌 시, 또는 강이나 바다에 빠질 때에도 체계적이고 종합적인 단계별 충격완화를 통해 탑승자의 부상을 최소화함과 동시에 위급한 상황에서 재난센터에 알려 도움을 요청하고, 그에 따른 긴급 구호가 가능하도록 할 수 있다. claims: 생명 보호 장치 시스템(10)으로서,이동체의 추락이나 충돌 시에 탑승자의 생명을 보호할 수 있도록 충격을 완화시킬 수 있도록 이동체에 장착되는 충격완화부(110)와 쇼크업 쇼바(120) 및 에어백(130)을 구비하는 충격완화 장치(100);상기 이동체에 가해지는 충격을 감지하기 위한 측정기(200);상기 측정기(200)의 감지되는 충격에 따라 미리 설정된 구동제어 신호를 발생시키는 제어기(300); 및상기 제어기(300)의 구동제어 신호에 대응하여 미리 설정된 재난센터로 재난발생을 알리고 도움을 요청하기 위한 인공지능부(400)를 포함하는 것을 특징으로 하는, 생명 보호 장치 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

340/1059 Row 340: application_number: 1020200023942, combined_string: invention_title: 양식장용 수차 발전장치 abstract: 본 발명은 양식장용 수차 발전장치에 관한 것으로, 그 구성은 양식장에서 회수되는 물을 공급받아 하방으로 자유 낙하시키는 수직 안내관;과, 상기 수직 안내관의 내부 하부에 형성되어 상기 수직 안내관을 통해 자유 낙하하는 물과 접촉되면서 수압에 의해 회전되는 것으로, 상기 수직 안내관에 대하여 상대회동 가능하게 형성되는 회전 팬;과, 일단은 상기 회전 팬과 연결되어 상기 회전 팬과 함께 회전되되, 타단은 제1발전기와 연결되어 상기 제1발전기로 회전력을 공급하는 제1공급축;과, 상기 제1공급축과 연결되어 상기 제1공급축으로부터 공급되는 회전력을 기반으로 발전하는 제1발전기;와, 상기 수직 안내관과 제1발전기를 지지 고정하는 지지대;로 구성된 것을 특징으로 하는 것으로서, 양식장에서 회수되는 물을 수직 안내관을 통해 하방으로 자유 낙하시켜 수직 안내관 하부에 위치되는 회전 팬이 물과 접촉 마찰되면서 회전되게 유도하고, 그 회전되는 회전 팬과 연결되는 제1공급축이 회전되면서 제1발전기로 회전력이 공급되어 전기가 1차적으로 발전되게 하며 동시에, 수직 안내관을 통과한 물은 수평 안내관으로 유입 유통되면서 발전수단을 통해 2차적으로 전기의 발전이 유도되는 방식으로 매우 효율적인 전기의 발전을 유도할 뿐만 아니라, 그 발전된 전기를 양식장에서 전기 사용처(각종 장비 및 장치)로 공급 사용함으로 양식장 운영에 전기 사용으로 인해 소요되는 금전적인 부담을 대폭 절감하여 양식장의 경제적인 운영을 유도할 수 있는 효과가 있다.또한, 발전수단의 수평 안내관을 통해 유통되는 물은 정제수단을 통해 정화된 상태로 배출되므로 양식장에 매우 깨끗한 물이 공급될 수 있어 양식장 어류의 용이한 양식을 유도할 수 있을 뿐만 아니라, 정제수단은 반 영구적인 사용이 유도되어 장치의 편리한 사용 운영이 유도될 수 있는 효과가 있다. claims: 양식장에서 회수되는 물을 공급받아 하방으로 자유 낙하시키는 수직 안내관(10);상기 수직 안내관(10)의 내부 하부에 형성되어 상기 수직 안내관(10)을 통해 자유 낙하하는 물과 접촉되면서 수압에 의해 회전되는 것으로, 상기 수직 안내관(10)에 대하여 상대회동 가능하게 형성되는 회전 팬(20);일단은 상기 회전 팬(20)과 연결되어 상기 회전 팬(20)과 함께 회전되되, 타단은 제1발전기(40)와 연결되어 상기 제1발전기(40)로 회전력을 공급하는 제1공급축(30);상기 제1공급축(30)과 연결되어 상기 제1공급축(30)으로부터 공급되는 회전력을 기반으로 발전하는 제1발전기(40); 및상기 수직 안내관(10)과 제1발전기(40)를 지지 고정하는 지지대(50);를 포함하여 구성되며,상기 수직 안내관(10)에 설치된 상기 회전 팬(20)을 통과한 물을 이용하여 발전하는 발전수단(60);을 더 포함하여 구성되되,상기 발전수단(60)은 상기 수직 안내관(10)과 연결되어 상기 수직 안내관(10)을 통해 배출되는 물을 회전판(62)으로 안내하는 수평 안내관(61)과, 상기 수평 안내관(61)의 내부에 경사(θ2)지게 형성되는 것으로, 전면 가장자리 부분에 등각 간격으로 형성되어 상기 수평 안내관(61)으로 흐르는 물과 접촉 마찰되는 다수의 회전날개(62a)가 형성되어 상기 수평 안내관(61)에 대하여 상대회동 되는 회전판(62)과, 일단은 상기 회전판(62)과 연결되어 상기 회전판(62)과 함께 회전되되, 타단은 제2발전기(64)와 연결되어 상기 제2발전기(64)로 회전력을 공급하는 제2공급축(63)과, 상기 제2공급축(63)과 연결되어 상기 제2공급축(63)으로부터 공급되는 회전력을 기반으로 발전하는 제2발전기(64)를 포함하여 구성되는 것을 특징으로 하는 양식장용 수차 발전장치., Ltext: 어업, prediction: 임업
341/1059 Row 341: application_number: 1020200020631, combined_string: invention_title: 양식어류의 질병 감시를 위한 스마트 지원시스템 abstract: 본 발명은 양식어류의 질병 감시를 위한 스마트 지원시스템에 대한 것으로, 더욱 상세하게는 양식어류 질병 진단 및 확산 방지 활동에 대한 양어관련자의 행위를 기설정된 기준에 따라 차등 분류하여 이에 따라 양어업에서만 사용할 수 있는 가상화폐인 양어코인을 지급함으로써, 시스템 및 양어산업 활성화를 동시에 도모할 수 있는 양식어류의 질병 감시를 위한 스마트 지원시스템에 대한 것이다. claims: 양식어류에 관한 정보를 센싱하여 관리서버에 전송하는 센서부와; 상기 센서부에서 출력된 정보를 분석하여 양식어류 질병 진단 및 확산 방지 활동에 대한 양어관련자의 참여 정보를 파악하여 상기 양어관련자에게 지급하여야 할 보상을 산정하는 보상산정부를 가지는 관리서버;를 포함하는 것을 특징으로 하는 양식어류의 질병 감시를 위한 스마트 지원시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

342/1059 Row 342: application_number: 1020200017241, combined_string: invention_title: 드론을 이용한 양식장 관리 시스템 및 관리 방법 abstract: 본 발명은 드론을 이용한 양식장 관리 시스템 및 관리 방법에 관한 것이다. 본 발명은, 양식장 관리서버(400)가 드론(300)과 신호 및 데이터 송수신을 통해 자율비행 기반으로 이동 경로 정보에 맞는 비행이 이루어지는지를 실시간으로 드론(300)의 GPS 위치 정보를 수신하여 확인함으로써, 드론(300)에 대해서 오차 범위 내에서 이동 경로 정보에 맞는 드론 영상 정보가 획득되도록 제어하는 제 1 단계; 및 양식장 관리서버(400)가 드론 영상 정보에 대한 영상 분석을 통해 해조류/패류 양식장의 수면에 떠 있는 부이의 상태, 부이를 연결하는 라인의 간격 등의 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 부이의 가라앉은 정보와 가라 앉은 위치 정보가 포함된 제 1 이벤트 정보를 생성하며, 드론 영상 정보에 대한 영상 분석을 통해 라인의 엉킴, 라인 주위의 다른 객체의 발견 등과 같은 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 라인 엉킴 및 다른 객체가 발견된 장소에 대한 엉킨 정보와 다른 객체의 크기 정보, 그 밖의 각 위치 정보를 포함하는 제 2 이벤트 정보를 생성하는 제 2 단계; 를 포함할 수 있다.이에 의해, 해양 상의 양식장을 드론에 의해 촬영한 영상 정보를 무선통신에 의해 수집한 뒤, 영상 정보에서 수면에 떠 있는 부이의 상태, 라인의 간격 등의 설정 기준을 벗어나서 양식장의 부이가 가라앉은 정도 또는 줄 엉킴 등 이상이 발생한 장소 및 현장 상황을 관리자에게 실시간 또는 주기적으로 통지할 수 있는 효과를 제공할 수 있다. claims: 양식장 관리서버(400)가 드론(300)과 신호 및 데이터 송수신을 통해 자율비행 기반으로 이동 경로 정보에 맞는 비행이 이루어지는지를 실시간으로 드론(300)의 GPS 위치 정보를 수신하여 확인함으로써, 드론(300)에 대해서 오차 범위 내에서 이동 경로 정보에 맞는 드론 영상 정보가 획득되도록 제어하는 제 1 단계; 및 양식장 관리서버(400)가 드론 영상 정보에 대한 영상 분석을 통해 해조류/패류 양식장의 수면에 떠 있는 부이의 상태, 부이를 연결하는 라인의 간격 등의 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 부이의 가라앉은 정보와 가라 앉은 위치 정보가 포함된 제 1 이벤트 정보를 생성하며, 드론 영상 정보에 대한 영상 분석을 통해 라인의 엉킴, 라인 주위의 다른 객체의 발견 등과 같은 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 라인 엉킴 및 다른 객체가 발견된 장소에 대한 엉킨 정보와 다른 객체의 크기 정보, 그 밖의 각 위치 정보를 포함하는 제 2 이벤트 정보를 생성하는 제 2 단계; 를 포함하는 것을 특징으로 하는 드론을 이용한 양식장 관리 방법.모바일 단말(100), 네트워크(200), 드론(300), 양식장 관리서버(400)를 포함하는 드론을 이용한 양식장 관리 시스템(1)에 있어서, 양식장 관리서버(400)는,드론(300)과 신호 및 데이터 송수신을 통해 자율비행 기반으로 이동 경로 정보에 맞는 비행이 이루어지는지를 실시간으로 드론(300)의 GPS 위치 정보를 수신하여 확인함으로써, 드론(300)에 대해서 오차 범위 내에서 이동 경로 정보에 맞는 드론 영상 정보가 획득되도록 제어하는 드론 관리/제어모듈(423); 및 드론 영상 정보에 대한 영상 분석을 통해 해조류/패류 양식장의 수면에 떠 있는 부이의 상태, 부이를 연결하는 라인의 간격 등의 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 부이의 가라앉은 정보와 가라 앉은 위치 정보가 포함된 제 1 이벤트 정보를 생성하는 영상정보 분석모듈(424); 을 포함하는 것을 특징으로 하는 드론을 이용한 양식장 관리 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

343/1059 Row 343: application_number: 1020200016470, combined_string: invention_title: 스마트 팜과, 그 관리 방법 및 장치 abstract: 스마트 팜과, 그 관리 방법 및 시스템이 개시된다. 본 개시의 일 실시 예에 따른 스마트 팜 관리 방법은, 미생물에 의해 분해된 어류로부터의 배설물이나 수조 잔존물을 포함한 수조의 물을 식물 재배부에 공급하는 어류 양식부의 수조 환경을 감지하는 단계와, 어류 양식부의 상단 측에 구비되어 어류 양식부로부터 공급 받은 물이 식물들에 의해 정화된 물을 어류 양식부에 공급하는 식물 재배부의 식물 재배 환경을 감지하는 단계와, 식물 재배부에 광원을 제공하는 조명부의 조명 정보를 감지하는 단계와, 수조 환경, 식물 재배 환경 및 조명 정보 중 적어도 하나 이상에 기초하여, 어류 양식부 및 식물 재배부의 환경이 설정 조건으로 유지되도록 제어하는 단계를 포함할 수 있다. claims: 내부에 어류가 서식할 수 있는 수조를 포함하여, 미생물에 의해 분해된 어류로부터의 배설물이나 수조 잔존물을 포함한 상기 수조의 물을 식물 재배부에 공급하는 어류 양식부;식물들 각각이 지지되도록 형성된 지지대를 포함하여 식물 재배가 가능하도록 설치되고, 상기 어류 양식부의 상단 측에 구비되어 상기 어류 양식부로부터 공급 받은 물이 상기 식물들에 의해 정화된 물을 상기 어류 양식부에 공급하는 식물 재배부; 및상기 식물 재배부의 상단 측에 상하 이동 가능하도록 구비되어 상기 식물 재배부에 광원을 제공하고, 조명 각도, 높낮이, 밝기 및 색상이 조절되는 조명부를 포함하고,상기 어류 양식부의 물을 상기 식물 재배부에 이송하기 위한 펌프를 구비한 제 1 순환라인 및 상기 식물 재배부에서 상기 어류 양식부로의 물 공급을 조절하기 위한 개폐 밸브를 구비한 제 2 순환라인을 통해 물이 순환되도록 하는,스마트 팜.스마트 팜을 관리하는 방법으로서,내부에 어류가 서식할 수 있는 수조를 포함하여, 미생물에 의해 분해된 어류로부터의 배설물이나 수조 잔존물을 포함한 상기 수조의 물을 식물 재배부에 공급하는 어류 양식부의 수조 환경을 감지하는 단계; 식물들 각각이 지지되도록 형성된 지지대를 포함하여 식물 재배가 가능하도록 설치되고, 상기 어류 양식부의 상단 측에 구비되어 상기 어류 양식부로부터 공급 받은 물이 상기 식물들에 의해 정화된 물을 상기 어류 양식부에 공급하는 식물 재배부의 식물 재배 환경을 감지하는 단계;상기 식물 재배부의 상단 측에 상하 이동 가능하도록 구비되어 상기 식물 재배부에 광원을 제공하는 조명부의 조명 정보를 감지하는 단계; 및상기 어류 양식부의 수조 환경, 상기 식물 재배부의 식물 재배 환경 및 상기 조명부의 조명 정보 중 적어도 하나 이상에 기초하여, 상기 어류 양식부 및 상기 식물 재배부의 환경이 설정 조건으로 유지되도록 제어하는 단계를 포함하고,상기 제어하는 단계는, 상기 어류 양식부의 물을 상기 식물 재배부에 이송하기 위한 펌프를 구비한 제 1 순환라인 및 상기 식물 재배부에서 상기 어류 양식부로의 물 공급을 조절하기 위한 개폐 밸브를 구비한 제 2 순환라인을 통해 물이 순환되도록 하는 물 순환부의 펌프 구동 및 개폐 밸브 제어를 수행하거나 상기 조명부의 조명 각도, 높낮이, 밝기 및 색상 중 적어도 하나 이상을 조절하는 단계를 포함하는,스마트 팜 관리 방법.스마트 팜을 관리하는 장치로서,스마트 팜과 통신하는 통신 인터페이스;하나 이상의 프로세서; 및상기 하나 이상의 프로세서와 연결되는 메모리를 포함하고,상기 메모리는, 상기 프로세서에 의해 실행될 때, 상기 프로세서로 하여금,내부에 어류가 서식할 수 있는 수조를 포함하여, 미생물에 의해 분해된 어류로부터의 배설물이나 수조 잔존물을 포함한 상기 수조의 물을 식물 재배부에 공급하는 어류 양식부의 수조 환경을 감지하고,식물들 각각이 지지되도록 형성된 지지대를 포함하여 식물 재배가 가능하도록 설치되고, 상기 어류 양식부의 상단 측에 구비되어 상기 어류 양식부에 정화된 물을 공급하는 식물 재배부의 식물 재배 환경을 감지하며,상기 식물 재배부의 상단 측에 상하 이동 가능하도록 구비되어 상기 식물 재배부에 광원을 제공하는 조명부의 조명 정보를 감지하고,상기 어류 양식부의 수조 환경, 상기 식물 재배부의 식물 재배 환경 및 상기 조명부의 조명 정보 중 적어도 하나 이상에 기초하여, 상기 어류 양식부 및 상기 식물 재배부의 환경이 설정 조건으로 유지되도록 제어하며, 상기 어류 양식부의 물을 상기 식물 재배부에 이송하기 위한 펌프를 구비한 제 1 순환라인 및 상기 식물 재배부에서 상기 어류 양식부로의 물 공급을 조절하기 위한 개폐 밸브를 구비한 제 2 순환라인을 통해 물이 순환되도록 하는 물 순환부의 펌프 구동 및 개폐 밸브 제어를 수행하거나 상기 조명부의 조명 각도, 높낮이, 밝기 및 색상 중 적어도 하나 이상을 조절하도록 야기하는(cause) 코드들을 저장하는,스마트 팜 관리 장치., Ltext: 어업, prediction: 임업
344/1059 Row 344: application_number: 1020200013755, combined_string: invention_title: 양식장용 슬러지 제거장치 abstract: 본 발명은 양식장용 슬러지 제거장치에 관한 것으로서, 보다 상세하게는 선회류에 따라 침전성 슬러지가 발생하는 수조본체와, 이 수조본체 저면에 구비되어 선회류에 의해 침전되는 슬러지를 수거하는 수집홈 및 수집된 슬러지를 배출하는 배출수단을 포함하되, 상기 수집홈을 유체가 흐르는 방향과 교차되는 방향으로 형성된 장홈으로 구성하여 보다 빠르고 효과적으로 슬러지를 수거할 수 있도록 고안된 양식장용 슬러지 제거장치에 관한 것이다. claims: 선회류가 형성시켜 유체가 일방향으로 회전하도록 이루어지는 수조 본체;상기 본체 저면에 구비되어 침전되는 슬러지가 유입되는 수집홈;상기 수집홈에 구비되어 수집홈으로 유입된 슬러지를 배출시키는 배출수단;을 포함하여 이루어지되,상기 수집홈은 상기 본체 내에서 유체가 흐르는 방향과 교차되는 방향으로 형성된 장홈인 것을 특징으로 하는 양식장용 슬러지 제거장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

345/1059 Row 345: application_number: 1020217025673, combined_string: invention_title: 근해 자유 부유식 거대 조류 양식을 위한 장치 및 방법 abstract: 본 발명은 수역, 더 구체적으로 바다/근해에서 거대 조류를 양식하기 위한 신규한 장치, 시스템 및 방법을 제공한다. claims: 수역(body-of-water), 바람직하게 바다/근해에서 거대 조류를 성장/양식시키기 위한 장치로서,(a) 수역으로부터 성장 케이지로 그리고 그 반대로 물, 가스 및 영양소의 자유로운 흐름을 가능하게 하는 투과성 벽 및 바닥을 갖는, 수역에 위치시키기 위한 성장/양식 케이지/반응기; 및(b) 가스 흐름 출구(gas flow outlet)를 통해 케이지 바닥으로부터 가스를 스트리밍(streaming)함으로써, 케이지 내의 물 및 결과적으로 그 내부에서 성장하는 거대 조류을 바닥으로부터 상부로 혼합/텀블링/현탁하도록 설계된 거대 조류 현탁 및 혼합 시스템을 포함하며;상기 장치는 상기 거대 조류의 자유 부유식 성장을 위해 설계되는,수역, 바람직하게 바다/근해에서 거대 조류를 성장/양식시키기 위한 장치.수역, 바람직하게 바다/근해에서 거대 조류를 성장시키기 위한 장치로서,a) 수역에 위치시키고, 수역으로부터 성장 케이지로 그리고 그 반대로 물, 가스 및 영양소의 자유로운 흐름을 가능하게 하는 투과성 벽과 바닥을 가지는 성장/양식 케이지/반응기;b) 가스 흐름 출구를 통해 케이지의 바닥으로부터 가스를 스트리밍함으로써, 바닥으로부터 상부로 케이지 내의 물 및 결과적으로 그 내부에서 성장한 거대 조류를 혼합/텀블링/현탁하도록 설계된 거대 조류 현탁 및 혼합 시스템;c) 수면에 또는 케이지 내의 물의 상부 표면이 여전히 햇빛에 노출되는 원하는 깊이에 상기 케이지를 부유 상태로 유지하기 위한 부유 장치/메커니즘;d) 성장 케이지에서 물 교환 및 선택적으로 난류 향상을 위한 적어도 하나의 외부 에어리프트; 및e) 성장 케이지에서 물 교환을 위한 워터-펌프를 포함하며;상기 장치는 상기 거대 조류의 자유로운 부유식 성장을 위해 설계되는,수역, 바람직하게 바다/근해에서 거대 조류를 성장시키기 위한 장치.수역, 바람직하게 바다/근해에서 거대 조류를 성장/양식시키는 방법으로서,(i) 제 1 항 내지 제 16 항 중 어느 한 항에 따른 장치를 수역에 위치시키는 단계;(ii) 성장/양식 케이지/저수조 케이지에 거대 조류 접종물을 배치하는 단계; 및(iii) 케이지 내의 물의 상이한 부분 및 결과적으로 그 내부에서 성장한 거대 조류를 주기적 방식으로 햇빛에 노출시킴으로써 바닥으로부터 상부로 양식 케이지 내의 물을 텀블링/현탁시키기 위한 거대 조류 현탁 및 혼합 시스템을 활성화하는 단계를 포함하며;(1) 상기 현탁 및 혼합 시스템에 의해 양식 케이지 내로 스트리밍된 가스의 양, 세기 및 속도는 상기 거대 조류의 유형, 밀도 및 성장 단계에 따라 결정되며; (2) 상기 텀블링은 양식 케이지 내의 거대 조류의 원하는 밀도/양이 달성될 때까지 연속적으로 수행되는,수역, 바람직하게 바다/근해에서 거대 조류를 성장/양식시키는 방법., Ltext: 어업, prediction: 임업
346/1059 Row 346: application_number: 1020200008035, combined_string: invention_title: 해양 쓰레기 수거 및 재생 처리용 다기능 선박 abstract: 본 발명에 따른 해양 쓰레기 수거 및 재생 처리용 다기능 선박은, 해상에 부유하거나 해저에 침적된 해양 쓰레기를 탐지하여 선체로 수거하는 부유물수거선박, 부유물수거선박에서 수거되어 수분이 제거된 해양 쓰레기를 넘겨받아 성상별로 선별하고 재활용 가능하게 가공 및 처리하는 가공및재활용선박 및 해양 쓰레기의 가공 및 처리 작업에 필요한 작업자들이 거주하는 작업자거주선박 을 포함하며, 부유물수거선박과 가공및재활용선박 및 작업자거주선박은, 해양 쓰레기가 있는 해수면 상의 위치까지 이동하는 동안에는 결합하여 이동하고, 해양 쓰레기가 있는 해수면 상의 위치에 이르러 해양 쓰레기 수거 및 재생 처리 작업을 개시할 때 분리되어 해양 쓰레기가 중심이 되는 삼각형으로 둘러싸며, 중심 방향으로 정상파 파동의 파도를 발생시켜 해양 쓰레기가 중심으로 모이도록 한 후, 부유물수거선박이 중심 근방에 모인 해양 쓰레기를 수거하는 것을 특징으로 한다. 이와 같은 구성을 가지는 본 발명에 의하면, 해상에 부유하는 오염물과 쓰레기를 모아서 수거 및 처리하여 재생유를 생산하거나 재활용 처리할 수 있는 해양 쓰레기 수거 및 재생 처리용 다기능 선박을 제공하는 것과 같은 이점이 있다. claims: 해상에 부유하거나 해저에 침적된 해양 쓰레기를 탐지하여 선체로 수거하는 부유물수거선박; 상기 부유물수거선박에서 수거되어 수분이 제거된 해양 쓰레기를 넘겨받아 성상별로 선별하고 재활용 가능하게 가공 및 처리하는 가공및재활용선박; 및 해양 쓰레기의 가공 및 처리 작업에 필요한 작업자들이 거주하는 작업자거주선박; 을 포함하며, 상기 부유물수거선박과 상기 가공및재활용선박 및 상기 작업자거주선박은, 해양 쓰레기가 있는 해수면 상의 위치까지 이동하는 동안에는 결합하여 이동하고, 해양 쓰레기가 있는 해수면 상의 위치에 이르러 상기 해양 쓰레기 수거 및 재생 처리 작업을 개시할 때 분리되어 상기 해양 쓰레기가 중심이 되는 삼각형으로 둘러싸며, 상기 중심 방향으로 정상파 파동의 파도를 발생시켜 해양 쓰레기가 상기 중심으로 모이도록 한 후, 상기 부유물수거선박이 상기 중심 근방에 모인 해양 쓰레기를 수거하고, 상기 부유물수거선박에서 해양 쓰레기를 수거하는 동안, 상기 가공및재활용선박 및 상기 작업자거주선박이 각각 다시 상기 부유물수거선박과 결합하며, 상기 작업자거주선박의 작업자들이 상기 가공및재활용선박으로 이동하고, 상기 부유물수거선박에서 수거된 해양 쓰레기는 상기 가공및재활용선박으로 이송되며, 상기 부유물수거선박은, 해상에 부유하거나 해저에 침적된 해양 쓰레기를 탐지하도록 선체 또는 상부데크에 구비되는 탐지장치; 및 상기 탐지장치에 의해 탐지된 해양 쓰레기를 선체로 수거하도록 선체 또는 상부데크에 설치되는 수거장치; 를 포함하며, 해양 쓰레기를 수거하여 상기 가공및재활용선박으로 이송하는 것을 특징으로 하는 해양 쓰레기 수거 및 재생 처리용 다기능 선박., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

347/1059 Row 347: application_number: 1020200005260, combined_string: invention_title: 에너지제로 생태순환형 농수축산 통합생산시스템 abstract: 양식어류 및 바이오플락 사육수가 저장되는 공간이 마련된 양식수조를 갖는 바이오플락 양식시스템; 일정 면적의 철망바닥부가 지면에 설치되고, 철망 바닥부 가장자리를 둘러싸며 일정 높이의 축사외벽이 형성되며, 축사외벽 상부에는 지붕이 설치되어 내부에 가축 사육공간이 형성되는 축사; 재배식물이 안착된 재배분 및 재배수를 저장할 수 있는 프레임구조의 재배조가 복층 또는 다층구조로 설치되는 식물재배시스템; 상기 바이오플락사육수 공급라인을 매개로 상기 축사 및 식물재배시스템과 연결되어 배수된 바이오플락 사육수가 공급되고, 상기 축사와 식물 재배시스템은 축사분뇨 공급라인으로 연결되며, 상기 식물재배시스템은 바이오플락 양식시스템과 식물재배수 공급라인으로 연결되어 생태순환시스템을 형성하며; 상기 시스템의 가동은 신재생에너지 발전에서 신재생에너지를 에너지 공급원으로 하여 전기에너지를 생산하여 공급되는 것인 에너지제로 생태순환형 농수축산 통합생산시스템을 제공한다. claims: 양식어류 및 바이오플락 사육수가 저장되는 공간이 마련된 양식수조와 상기 양식수조 내부에는 바이오플락 사육수에 공기 공급 및 수류를 형성하는 벤추리장치가 설치되는 바이오플락 양식시스템;일정 면적의 철망바닥부가 지면에 설치되고, 상기 철망 바닥부 가장자리를 둘러싸며 일정 높이의 축사외벽이 형성되며, 상기 축사외벽 상부에는 지붕이 설치되어 내부에 가축 사육공간이 형성되는 축사;재배식물이 안착된 재배분 및 재배수를 저장할 수 있는 프레임구조의 재배조가 복층 또는 다층구조로 설치되는 식물재배시스템;상기 바이오플락 양식시스템은 바이오플락사육수 공급라인을 매개로 상기 축사 및 식물재배시스템과 연결되어 배수된 바이오플락 사육수가 공급되고, 상기 축사와 식물 재배시스템은 축사분뇨 공급라인으로 연결되며, 상기 식물재배시스템은 바이오플락 양식시스템과 식물재배수 공급라인으로 연결되어 생태순환시스템을 형성하며;상기 시스템의 가동은 신재생에너지 발전에서 신재생에너지를 에너지 공급원으로 하여 전기에너지를 생산하여 공급되는 것인 에너지제로 생태순환형 농수축산 통합생산시스템, Ltext: 어업, prediction: 농업
348/1059 Row 348: application_number: 1020200005269, combined_string: invention_title: 양식장 사육수 산소공급을 위한 산소용해장치 abstract: 일정길이의 산소용해 파이프라인이 나선형구조를 이루며 케이싱내부에 설치되고; 상기 산소용해 파이프라인 일측 말단은 산소공급장치와 연결되고, 타측 말단은 사육수 살균장치와 연결되어 이루어지는 고효율 산소용해장치 및 살균장치를 제공함으로써, 기존의 산소용해장치와 동일한 수압을 제공하는 것으로 미세버블을 제조가 가능할 뿐만 아니라 용존산소량의 증가 및 지속이 가능하여 대용량의 산소용해수의 제조가 가능할 뿐만 아니라 설치비용 및 가동부담을 줄일 수 있는 효과가 있다. claims: 일정길이의 산소용해 파이프라인이 나선형구조를 이루며 케이싱내부에 설치되고; 상기 산소용해 파이프라인 일측 말단은 산소공급장치와 연결되고, 타측 말단은 사육수 살균장치와 연결되어 이루어지는 것인 고효율 산소용해장치 및 살균장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

349/1059 Row 349: application_number: 1020200002003, combined_string: invention_title: 어군 탐지 시스템 및 어군 탐지 방법 abstract: 본 발명은 어군 탐지 시스템 및 어군 탐지 방법에 관한 것으로, 본 발명의 일 실시예에 따른 어군 탐지 방법은, 수중에 음파를 송출하고, 송출된 음파를 수신하는 어군 탐지기 및 상기 어군 탐지기를 설정하고 제어하는 관리 단말기를 이용하여 어군을 탐지하기 위해, 상기 어군 탐지기의 통신을 개방하는 단계; 상기 관리 단말기에서 통신 속도 및 수중 음속을 이용하여 BIN 개수 당 거리를 계산하는 단계; 상기 어군 탐지기에서 수중에 대한 수심을 탐지하는 단계; 탐지된 상기 수심을 이용하여 수심에 따른 상기 BIN 개수를 산정하는 단계; 산정된 상기 BIN 개수에 따라 상기 어군 탐지기 및 관리 단말기 중 하나 이상의 화면에 출력하기 위해 상기 BIN 개수에 대한 화면표시 비율을 산정하는 단계; 및 상기 화면표시 비율에 따라 수중의 어군을 상기 어군 탐지기 및 관리 단말기 중 하나 이상의 화면에 표시하는 단계를 포함하고, 상기 수중에 대한 수심을 탐지하는 단계는, 수중에 어군이 있는 경우, 어군까지의 수심을 탐지할 수 있다. 본 발명에 의하면, 어군 탐지기와의 통신을 위한 프로그램에 대한 설계를 변경하고, 탐지된 어군을 화면에 표시하기 위한 방식을 BIN 개수를 이용함으로써, 어군의 위치를 보다 정확하고 명확하게 실시간으로 확인할 수 있는 효과가 있다. claims: 수중에 음파를 송출하고, 송출된 음파를 수신하는 어군 탐지기; 및상기 어군 탐지기를 설정하고 제어하는 관리 단말기를 포함하며,상기 관리 단말기는, 통신 속도 및 수중 음속을 이용하여 BIN 개수 당 거리를 계산하고, 상기 어군 탐지기에서 탐지된 수심에 따른 BIN 개수를 산정하며, 산정된 BIN 개수에 따라 화면에 출력하기 위해 BIN 개수에 대한 화면표시 비율을 산정하여 산정된 화면표시 비율에 따라 수중의 어군을 표시하고,상기 화면은 상기 어군 탐지기 및 관리 단말기 중 하나 이상에 포함된 디스플레이 장치를 통해 표시되는 화면인 어군 탐지 시스템이고,상기 어군 탐지시스템은 수중에 음파를 송출하고, 송출된 음파를 수신하는 어군 탐지기 및 상기 어군 탐지기를 설정하고 제어하는 관리 단말기를 이용하여 어군을 탐지하기 위해, 상기 어군 탐지기의 통신을 개방하는 단계; 상기 관리 단말기에서 통신 속도 및 수중 음속을 이용하여 BIN 개수 당 거리를 계산하는 단계; 상기 어군 탐지기에서 수중에 대한 수심을 탐지(수중에 어군이 있는 경우, 어군까지의 수심을 탐지)하는 단계; 탐지된 상기 수심을 이용하여 수심에 따른 상기 BIN 개수를 산정하는 단계; 산정된 상기 BIN 개수에 따라 상기 어군 탐지기 및 관리 단말기 중 하나 이상의 화면에 출력하기 위해 상기 BIN 개수에 대한 화면표시 비율을 산정하는 단계; 및 상기 화면표시 비율에 따라 수중의 어군을 상기 어군 탐지기 및 관리 단말기 중 하나 이상의 화면에 표시하는 단계를 포함하고, 상기 통신을 개방하는 단계 이전에, 상기 어군 탐지기와 통신하기 위한 상기 관리 단말기에 포함된 통신 포트를 통해 설정하는 단계를 더 포함하고, 상기 화면표시 비율의 산정이 이루어지면, 픽셀의 중복 출력 회수를 산정하는 단계를 더 포함하고, 상기 수중의 어군을 상기 어군 탐지기의 화면에 표시하는 단계는, 상기 픽셀의 중복 출력 회수에 따라 화면에 표시하며, 상기 통신을 개방하는 단계 이전에, 상기 어군 탐지기에 대한 암호를 해제하는 단계를 더 포함하는 방식으로 어군을 탐지하며,상기 어군 탐지기의 외부면에는 오염 방지도포용 조성물로 이루어진 오염방지도포층이 도포되되, 상기 오염 방지 도포용 조성물은 메르캅토벤조씨아졸 및 아미도알킬 베타인이 1:0.01 ~ 1:2 몰비로 포함되어 있고, 메르캅토벤조씨아졸과 아미도알킬 베타인의 총함량은 전체 수용액에 대해 1 ~10 중량%이고,상기 관리 단말기가 금속재인 경우에 표면 상에 부식 방지 도포층을 도포하고, 상기 부식 방지 도포층에 포함된 표면 도포 재료는 벤즈트리아졸 15중량%, 에틸렌 글리콜 부틸 에테르 25중량%, 하프늄 20중량%, 유화몰리브덴(MoS2) 10중량%, 산화티타늄(TiO2) 15중량%, 페놀 노블락형 글리시딜에테르 15중량%로 구성되며, 코팅두께는 8㎛로 형성되며,상기 관리 단말기의 하단에는 고무재의 진동흡수방지부가 더 설치되되, 상기 진동흡수방지부의 원료 함량비는 고무 58 중량%, 카아본블랙 32중량%, 산화방지재 5 중량%, 촉진재인 유황 3중량%, 레소르시놀 수지 2 중량%를 혼합하는, 어군 탐지 시스템., Ltext: 어업, prediction: 어업
350/1059 Row 350: application_number: 1020190172658, combined_string: invention_title: 가두리양식장용 적조차단장치 abstract: 본 발명은 가두리양식장용 적조차단장치에 관한 것으로서, 바닷물에서 번식하는 미생물의 영향으로 생기는 적조현상을 차단할 수 있도록 한 것이다. 본원 발명은 구체적으로 해양에 발생하는 적조 현상으로 인한 가두리양식장의 피해를 없애기 위한 것으로서, 특히 가두리양식장의 테두리를 따라서 해저에 목기장치를 설치함으로써 조류를 따라서 흘러들어오는 적조의 유입을 사전에 차단하며, 더불어 양식장의 해저의 낮은 수온을 표층으로 순환시킴으로써 여름철 고온수로 인한 양식장의 피해를 줄이는 것을 특징으로 하는 가두리양식장용 적조차단장치에 관한 것이다. claims: 격자형의 형상을 가지도록 수면위에 떠 있는 부유수단(100); 상기 부유수단(100)의 상면에 배치된 격자형의 작업통로(200);상기 작업통로(200)를 따라서 수중으로 배치되어 어류의 양식공간을 형성하는 그물망(300)을 구비하는 가두리양식장에 있어서, 압축공기를 제공하는 공기압축기(500):상기 부유수단(100) 하부의 수중에 배치되되 상기 부유수단(100)의 가장자리를 따라서 장방형으로 결합되고 로프에 의해서 수직하방향으로 달아내려져서 적조의 외부유입을 차단하는 공기방울 보호벽을 형성하도록 수중에 배치되는 제1폭기파이프(400);장방형의 상기 제1폭기파이프(400)들의 내부에 배치되는 제2폭기파이프(800);상기 공기압축기(500)와 상기 제1폭기파이프(400) 및 제2폭기파이프(800)를 연결하는 압축공기공급관(510); 및 상기 제1폭기파이프(400)와 상기 제2폭기파이프(800)는 상기 압축공기공급관(510)으로부터 공급되는 압축공기를 수중에서 분사할 수 있도록 길이방향으로 다수의 노즐(410)이 구비되는 것을 특징으로 하는 가두리양식장용 적조차단장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

351/1059 Row 351: application_number: 1020190172105, combined_string: invention_title: 수소 생산 및 양식장 수온 관리 통합 시스템 및 그 운용 방법 abstract: 본 발명은 해수를 전기분해하여 수소 및 차아염소산 나트륨을 생산하고, 생산된 수소의 일부를 수소연료전지로 공급하여 전기를 생산하며, 생산된 수소의 나머지 일부를 양식장으로 공급하여 물을 냉각시켜 수온을 일정한 온도로 관리할 수 있는 수소 생산 및 양식장 수온 관리 통합 시스템 및 방법에 관한 것으로, 본 발명에 따른 수소 생산 및 양식장 수온 관리 통합 시스템은 해수를 전기분해하여 수소 기체와 차아염소산 나트륨(NaOCl)을 생산하는 해수전기분해부; 상기 해수전기분해부에서 생산된 수소 기체의 일부와, 상기 해수전기분해부에서 생성된 산소 기체 또는 외부에서 공급되는 산소 기체를 공급받아 전기에너지를 생산하는 수소 연료전지; 상기 수소 연료전지에서 생산된 전기에너지를 저장하는 축전지; 상기 해수전기분해부에서 생산된 수소 기체의 나머지 일부와, 외부의 액화질소공급원에서 공급되는 액화질소의 열교환을 통해 수소를 액화시켜 액화수소를 생성하는 수소액화부; 상기 수소액화부에서 생성된 액화수소를 공급받아, 상기 액화수소와 양식장의 수온을 조절하기 위한 냉각수와의 열교환을 통해 냉각수를 냉각시키는 양식장수온관리부; 상기 양식장수온관리부를 통과하여 이송된 수소 기체를 흡수하여 저장하는 수소저장합금을 포함하는 수소저장부;를 포함한다. claims: 해수를 전기분해하여 수소 기체와 차아염소산 나트륨(NaOCl)을 생산하는 해수전기분해부;상기 해수전기분해부에서 생산된 수소 기체의 일부와, 상기 해수전기분해부에서 생성된 산소 기체 또는 외부에서 공급되는 산소 기체를 공급받아 전기에너지를 생산하는 수소 연료전지;상기 수소 연료전지에서 생산된 전기에너지를 저장하는 축전지;상기 해수전기분해부에서 생산된 수소 기체의 나머지 일부와, 외부의 액화질소공급원에서 공급되는 액화질소의 열교환을 통해 수소를 액화시켜 액화수소를 생성하는 수소액화부;상기 수소액화부에서 생성된 액화수소를 공급받아, 상기 액화수소와 양식장의 수온을 조절하기 위한 냉각수와의 열교환을 통해 냉각수를 냉각시키는 양식장수온관리부;상기 양식장수온관리부를 통과하여 이송된 수소 기체를 흡수하여 저장하는 수소저장합금을 포함하는 수소저장부;를 포함하는 수소 생산 및 양식장 수온 관리 통합 시스템.제1항 내지 제5항 중 어느 한 항에 따른 수소 생산 및 양식장 수온 관리 통합 시스템의 운용 방법으로서, (S1) 해수전기분해부에서 해수를 전기분해하여 수소 기체와 차아염소산 나트륨(NaOCl)을 생산하는 단계;(S2) 상기 해수전기분해부에서 생산된 수소 기체의 일부를 수소 연료전지로 공급하여 전기에너지를 생산하고, 생산된 전기에너지를 축전지에 저장하는 단계;(S3) 상기 해수전기분해부에서 생산된 수소 기체의 나머지 일부를 수소액화부로 공급하고, 상기 수소액화부에 액화질소공급원에서 공급되는 액화질소를 공급하여 상기 수소기체와 액화질소 간의 열교환을 통해 수소를 액화시켜 액화수소를 생성하는 단계;(S4) 상기 수소액화부에서 생성된 액화수소를 양식장수온관리부로 공급하여 양식장의 수온을 조절하기 위한 냉각수를 냉각시키는 단계; 및,(S5) 상기 양식장수온관리부를 통과하여 이송된 수소 기체를 수소저장부에 저장하는 단계;를 포함하는 수소 생산 및 양식장 수온 관리 통합 시스템의 운용 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

352/1059 Row 352: application_number: 1020190171379, combined_string: invention_title: 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표 및 이를 이용한 센싱 시스템 abstract: 본 발명의 일 실시예는 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표 및 이를 이용한 센싱 시스템에 관한 것으로, 해결하고자 하는 기술적 과제는 환경보호와 저전력 시스템, 청정 에너지 사용이 가능하게 하는데 있다.이를 위해 본 발명의 일 실시예는 어구 또는 어망에 장착되는 LoRaWAN 통신 기반 IoT 부표고, 몸체부; 상기 몸체부에 구비되고, GPS 신호를 수신하는 GPS 모듈; 상기 몸체부에 구비되고, 상기 몸체부 주변의 해수 온도 및 파도 정보를 감지하는 센서부; 및 상기 몸체부에 구비되고, 상기 GPS 모듈 및 센서부에 의하여 감지되는 위치정보, 해수 온도 및 파도 정보를 LoRaWAN 통신 망을 통하여 외부로 전송하는 통신부를 포함하는 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표를 개시한다. claims: 어구 또는 어망에 장착되는 LoRaWAN 통신 기반 IoT 부표이고,몸체부;상기 몸체부에 구비되고, GPS 신호를 수신하는 GPS 모듈;상기 몸체부에 구비되고, 상기 몸체부 주변의 해수 온도 및 파도 정보를 감지하는 센서부; 및상기 몸체부에 구비되고, 상기 GPS 모듈 및 센서부에 의하여 감지되는 위치정보, 해수 온도 및 파도 정보를 LoRaWAN 통신 망을 통하여 외부로 전송하는 통신부를 포함하고,상기 몸체부는 IP7 이상의 방수기능을 가지고,상기 몸체부의 상면과 내부 하부 영역에는 상기 몸체부의 내부에 구비되는 배터리에 전원을 공급하는 태양광 충전부와 충전포트가 구비되며,상기 통신부는 일대 다자간 통신프로토콜을 위하여 IoT 부표의 식별정보 및 위치정보와, 해수 온도 및 파도 정보와, 배터리의 전원량 정보 및 전원 공급 정보를 LoRaWAN 방식으로 주기적으로 송신하고,상기 IoT부표의 내외부면에는 오염 방지 도포용 조성물로 이루어진 오염방지도포층이 도포되되, 상기 오염 방지 도포용 조성물은 코카미도프로필베타인 및 암포 글리시네이트가 1:0.01 ~ 1:2 몰비로 포함되어 있고, 코카미도프로필베타인과 암포 글리시네이트의 총함량은 전체 수용액에 대해 1 ~10 중량%이며,상기 센서부 표면에는 부식방지도포층이 도포되되, 상기 부식방지도포층의 도포 재료는 벤즈이미다졸 20중량%, 프로필렌 글리콜 메틸 에테르 30중량%, 하프늄 15중량%, 유화몰리브덴(MoS2) 10중량%, 산화알루미늄 15중량%, 비스페놀 F형 디글리시딜에테르 10중량%로 구성되며, 코팅두께는 8㎛로 형성되고,상기 태양광충전부를 몸체부에 장착할 때 태양광충전부와 몸체부간의 접착력을 높이기 위해 접착 향상재를 통하여 접착시키되, 상기 접착 향상재는 물 50중량부와, 에틸 아크릴레이트 25중량부와, 스티렌 10중량부와, 메타 아크릴산 5중량부와, 계면활성제 5중량부와, 첨가제 2중량부와, 과황산암모늄 2중량부와, 완충제 1중량부를 포함하여 이루어진 것을 특징으로 하는 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표.제1항에 기재된 적어도 하나의 LoRaWAN 통신 기반 IoT 부표;상기 IoT 부표로부터 수신한 상기 IoT 부표의 식별정보 및 위치정보와, 해수 온도 및 파도 정보와, 배터리의 전원량 정보 및 전원 공급 정보를 LoRaWAN 통신 망을 통하여 선박 또는 육상에 구비된 중앙관제서버로 송신하는 게이트웨이부; 및상기 IoT 부표의 식별정보 및 위치정보를 수신하여, 미리 설치된 위치 표시 프로그램을 이용하여 미리 설정된 연동 형식이나 AIS 표준 신호로 변환후 IoT 부표의 식별정보 및 위치정보를 표시하고, 상기 해수 온도 및 파도 정보와, 배터리의 전원량 정보 및 전원 공급 정보를 수신하여 상기 IoT 부표의 동작 상태를 모니터링하고, 이상 발생시 외부로 알림 신호를 출력하는 중앙관제서버를 포함하고,상기 IoT 부표가 상기 게이트웨이부에게 업링크(Up-Link) 전송을 수행한 이후 두번의 다운링크(Down-Link) 수신이 가능하며, 상기 IoT 부표는 Tx를 하기 전에 Tx와 Rx를 모두 꺼두었다가 Tx이후 미리 설정된 시간에 Rx신호를 감지하여 저전력 LoRaWAN 통신을 수행하며,상기 중앙관제서버는 서버 내부의 오작동으로 인한 화재 분석이 가능한 에너지 저장 시스템을 더 구비하되, 상기 에너지 저장 시스템은 배터리; 상기 배터리의 충방전 상태를 감시하는 배터리 모니터링 시스템(BMS), 배터리의 충방전 상태를 제어하는 파워 컨디셔닝 시스템(PCS), BMS로부터 배터리 모니터링 데이터를 감시하고 PCS를 제어하는 에너지 모니터링 시스템(EMS), 및 BMS로부터 배터리의 전압, 전류, 온도의 데이터와 외부 통신 데이터를 수신하고, PCS로부터 전압, 전류의 데이터를 수신하며, EMS로부터 감시 및 제어 데이터를 수신하여 저장하는 블랙박스를 포함하고, 또한, 상기 에너지 저장 시스템은 내부를 촬영하는 카메라, 에너지 저장 시스템의 온도를 센싱하는 온도 센서, 에너지 저장 시스템의 습도를 센싱하는 습도 센서, 및 에너지 저장 시스템의 오프 가스를 센싱하는 오프 가스 센서를 포함하는 것을 특징으로 하는 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표를 이용한 센싱 시스템., Ltext: 어업, prediction: 어업
353/1059 Row 353: application_number: 1020190170368, combined_string: invention_title: 바이오플락 양식 사육수를 이용한 군체 형성 미세조류 및 동물 플랑크톤 자동 생산 및 회수장치 abstract: 다각형의 수조바닥을 일정높이의 수조외벽이 둘러싸며 상부가 개구되고 내부공간이 형성되는 회수 수조; 상기 회수 수조의 수조외벽 어느 한 측면에는 바이오플락 사육수조와 연결되어 배수된 바이오플락 사육수가 이동하는 바이오플락 사육수 공급관; 상기 사육수조 중심부에는 회전장치가 수조바닥과 수직하게 설치되며; 상기 회전장치의 최상단에 설치되어, 회전장치의 설치방향을 중심축으로 회전하는 수집장치; 상기 회수 수조 내부에 설치되어 저장된 바이오플락 사육수의 수류를 형성하는 수류형성장치로 이루어진 바이오플락 양식 사육수를 이용한 군체형성 미세조류 및 동물 플랑크톤 자동 생산 및 회수장치를 제공함으로써, 고부가 가치를 지니는 바이오플락 사육수를 미세조류와 동물 플랑크톤의 배양수로 공급하여 배양 시에 무기염류 및 영양성분을 별도로 공급할 필요가 없고, 배양수로 이용된 바이오플락 사육수에 포함되어 있는 질소 및 무기염류 성분이 제거되어 사육 수조로 재공급이 가능함으로 친환경적일 뿐만 아니라 경제적인 효과가 있다. claims: 다각형의 수조바닥을 일정높이의 수조외벽이 둘러싸며 상부가 개구되고 내부공간이 형성되는 회수 수조; 상기 회수 수조의 수조외벽 어느 한 측면에는 바이오플락 사육수조와 연결되어 배수된 바이오플락 사육수가 이동하는 바이오플락 사육수 공급관; 상기 회수수조 중심부에는 회전장치가 수조바닥과 수직하게 설치되며; 상기 회전장치의 최상단에 설치되어, 회전장치의 설치방향을 중심축으로 회전하는 수집장치; 상기 회수 수조 내부에 설치되어 저장된 바이오플락 사육수의 수류를 형성하는 수류형성장치로 이루어진 것을 특징으로 하는 바이오플락 양식 사육수를 이용한 군체형성 생물 자동 생산 회수장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

354/1059 Row 354: application_number: 1020190169285, combined_string: invention_title: 블럭형 자가발전 어구 표시 부이 abstract: 본 발명에 의한 블럭형 자가발전 어구 표시 부이는, 무선통신이 가능한 본체부, 상기 본체부 하측에 구비되며, 상기 본체부가 구동되도록 전기 에너지를 생산하고, 공급하는 자가 발전부를 포함하며, 상기 자가 발전부는, 외부로부터 충격력을 인가받았을 때 전기 에너지를 생산하는 자가 전력 나노발전기와, 파도에 의해 움직여 상기 자가 전력 나노발전기에 충격력을 인가하는 기계적 운동 에너지 장치와, 상기 자가 전력 나노발전기에서 생산된 전기 에너지를 저장하고 상기 저장된 전기 에너지를 상기 본체부에 공급하는 충전용 배터리가 순차적으로 적층된 것을 특징으로 한다. claims: 자가발전부와 전기적으로 연결되어 해중 어구의 위치를 표시하는 부이에 있어서,무선통신이 가능한 본체부 및상기 본체부 하측에 구비되며, 상기 본체부가 구동되도록 전기 에너지를 생산하고, 공급하는 자가 발전부를 포함하며,상기 자가 발전부는, 외부로부터 충격력을 인가받았을 때 전기 에너지를 생산하는 자가 전력 나노발전기와, 파도에 의해 움직여 상기 자가 전력 나노발전기에 충격력을 인가하는 기계적 운동 에너지 장치와, 상기 자가 전력 나노발전기에서 생산된 전기 에너지를 저장하고 상기 저장된 전기 에너지를 상기 본체부에 공급하는 충전용 배터리가 순차적으로 적층된 것이고,상기 기계적 운동에너지 장치는,상기 자가 전력 나노발전기의 상면을 덮도록 결합되고, 내부에 공간이 구비된 하우징, 상기 하우징 내부에 배치되어 상기 자가 전력 나노발전기의 상면에 충격력을 가하는 가압부를 포함하며,상기 가압부는,상기 하우징의 내부공간 천장에 고정되는 고정바,중단이 상기 고정바에 힌지결합되어 길이방향 양측이 상기 자가 전력 나노발전기의 상면에 충격력을 가하는 누름바를 포함하는 것을 특징으로 하는 블럭형 자가발전 어구 표시 부이.제1항 내지 제3항, 제7항 및 제8항 중 어느 한 항의 블럭형 자가발전 어구 표시 부이를 포함하는 어구 표시 부이 모니터링 시스템., Ltext: 어업, prediction: 어업
355/1059 Row 355: application_number: 1020200065835, combined_string: invention_title: 에너지 저감 수로 유수식 친환경 축제식 양식장 abstract: 본 발명은 육상의 축제식 양식장을 제공하면서 해안가의 산비탈면 또는 육지의 산이나 폐광산의 경사면 암반을 굴착하여 양식장을 제공함으로써 에너지 사용을 줄일 수 있는 친환경적인 축제식 양식장에 관한 발명이다.본 발명은 산의 경사면에 수조를 계단식으로 다단으로 형성하고, 상기 수조의 바닥에는 소정의 두께로 모래가 구비되며, 상기 수조의 내부에는 모래를 일측으로 이동시키기 위한 모래이동부가 더 구비되며, 상기 수조의 일측에는 수조의 모래를 배출시켜 이동시키기 위한 모래배출관이 연결되며, 상기 모래배출관의 끝단에는 배출되는 모래에 부착된 이물질을 세척하기 위한 모래세척부가 결합되고, 상기 모래세척부에서 세척된 모래가 수조로 공급되도록 하는 것을 특징으로 한다.본 발명은 산의 경사면에 다단으로 수조를 형성하여 육상 양식장을 제공함으로써, 어류의 양식 생산성을 높이고 어업인의 소득을 증대시킬 수 있는 효과가 있다. claims: 산의 경사면에 수조를 계단식으로 다단으로 형성하고,상기 수조의 바닥에는 소정의 두께로 모래가 구비되며,상기 수조의 내부에는 모래를 일측으로 이동시키기 위한 모래이동부가 더 구비되며, 상기 모래이동부는 상기 수조의 내부를 횡방향을 가로지르며 회전하는 회전축과, 상기 회전축에 설치되어 수조의 바닥에 깔린 모래를 모래배출관 측으로 이동시키기 위한 밀대를 포함하며,상기 수조의 외측에는 상기 모래이동부를 회전시키기 위한 구동부가 더 구비되며, 상기 구동부는 구동모터와 구동축 및, 상기 모래이동부의 회전축과 치합되어 구동축의 회전력을 회전축에 전달하는 베벨기어를 포함하며,상기 수조의 일측에는 수조의 모래를 배출시켜 이동시키기 위한 모래배출관이 연결되고, 상기 모래배출관의 끝단에는 배출되는 모래에 부착된 이물질을 세척하기 위한 모래세척부가 결합되고,상기 모래세척부의 타측에서 수조의 타측 사이에는 모래공급관이 연결되어, 상기 모래세척부에서 세척된 모래가 수조로 재 공급되도록 하며,상기 수조는 모래의 이동이 용이하도록 모래공급관 측 바닥면이 모래배출관 측 바닥면 보다 더 높도록 경사지게 형성되고, 모래이동부도 모래공급관 측에서 모래배출관 측으로 갈수록 점차 위치가 낮게 위치하도록 형성되며,상기 수조의 일측면에는 양식수유입관이 구비되고, 고압의 펌프에 의해 공급되는 양식수가 상기 양식수유입관을 통해 최상단의 수조 일측으로 공급되며,상기 최상단 수조부터 최하단 수조 사이를 연통배수로가 일측 또는 타측 끝단에 지그재그 형태로 연통되도록 형성되어, 상기 최상단 수조로 공급된 양식수가 최하단의 수조로 유입되는 것을 특징으로 하는 축제식 양식장., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

356/1059 Row 356: application_number: 1020200024101, combined_string: invention_title: 철갑상어의 육질을 향상시키는 방법 abstract: 본 발명이 제공하는 어육의 품질을 향상시키는 방법은 저온, 청정 및 부영양화 특성을 갖춘 심층 해수를 이용해 담수로 염도를 10-20ppt까지 조정하고, 수온을 20℃ 미만으로 낮추어 철갑상어를 적어도 2주 동안 양식 처리하면, 그 맛과 풍미를 분명하게 향상시킬 수 있고, 제품의 가치를 높일 수 있다. claims: 철갑상어를 담수 환경에서 적어도 1kg 무게의 성년 철갑상어까지 양식하며,염도 10ppt~20ppt의 범위, 수온이 20℃ 미만으로 유지되는 혼합 염수 중에서, 상기 성년 철갑상어를 적어도 2주간 귀화시키며,상기 혼합 염수는 심층 해수와 담수를 혼합해서 만들며,상기 단계를 포함하는 것을 특징으로 하는 철갑상어 육질을 향상시키는 방법., Ltext: 어업, prediction: 어업
357/1059 Row 357: application_number: 2020190005015, combined_string: invention_title: 양어장용 수차 abstract: 본 발명에 따른 양어장용 수차는, 수면에 떠 있도록 부력을 제공하는 좌,우측 부구; 상기 좌,우측 부구위에 서로 마주보는 2개의 측변이 결합수단에 의해 고정 설치되는 사각프레임; 상기 사각프레임상에 설치되어 모터를 지지하는 수직프레임; 동력을 제공하는 모터; 상기 모터의 회전축에 설치된 웜; 상기 웜으로부터 치합 연결되어 동력을 전달받는 웜기어; 상기 웜기어의 중심을 관통하여 회전가능하도록 상기 사각프레임상에 구비되는 &amp;quot;U&amp;quot;자 형태를 갖는 두 개 이상의 합성수지재 지지부에 의해 지지되는 종동축; 및 상기 사각프레임 및 수직프레임을 포함하고, 상기 종동축의 양측에 구비되는 좌,우측 프로펠러가 수면 위에 있도록 지지하는 지지 프레임을 포함한다. claims: 수면에 떠 있도록 부력을 제공하는 좌,우측 부구(10,11);상기 좌,우측 부구(10,11) 위에 서로 마주보는 2개의 측변이 결합수단에 의해 고정 설치되는 사각프레임(21);상기 사각프레임(21)상에 설치되어 모터(30)를 지지하는 수직프레임(22);동력을 제공하는 모터(30);상기 모터의 회전축에 설치된 웜(40);상기 웜(40)으로부터 치합 연결되어 동력을 전달받는 웜기어(50);상기 웜기어(50)의 중심을 관통하여 회전가능하도록 상기 사각프레임(21)상에 구비되는 &amp;quot;U&amp;quot;자 형태를 갖는 두 개 이상의 합성수지재 지지부(70)에 의해 지지되는 종동축(60); 및상기 사각프레임(21) 및 수직프레임(22)을 포함하고, 상기 종동축(60)의 양측에 구비되는 좌,우측 프로펠러(80)가 수면 위에 있도록 지지하는 지지 프레임(20)을포함하는 양어장용 수차., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

358/1059 Row 358: application_number: 1020190164247, combined_string: invention_title: 해삼 또는 전복 양식용 패널 및 이의 시공 방법 abstract: 본 발명은 해삼 또는 전복 양식용 패널 및 이의 시공 방법에 관한 것으로, 외주면에 다공질 홀(10a)이 다수 형성되어 있는 다공성 콘크리트 재질로 이루어져 있으며, 직선으로 이루어진 일측변부(11)와, 상기 일측변부(11)로부터 일정 거리 이격되어 일측변부(11)와 평행을 이루는 타측변부(12)와, 일측변부(11)와 타측변부(12)의 양측 끝단으로부터 각각 타측변부(12)와 일측변부(11)를 향해 직선으로 형성되어 있는 연결변부(13)와, 양측 연결변부(13)의 끝단으로부터 중앙을 향해 경사지게 형성되어 있는 경사변부(14)와, 양측의 경사변부(14)를 서로 연결하는 직선형의 경사연결변부(15)로 이루어진 평면 형상을 취하고, 일측변부(11)와 타측변부(12)의 양측 끝단에 형성된 두 연결변부(13)를 연결하는 가상의 선과 경사변부(14) 및 경사연결변부(15)에 의해 둘러쌓인 공간인 연결홈부(16)가 형성되어 있고, 경사연결변부(15)를 연장한 가상의 선, 경사변부(14), 일측변부(11) 타측변부(12)에 의해 둘러쌓인 공간인 돌출부(17)가 형성되어 있으며, 인접한 본체(10)들의 일측변부(11) 측 돌출부(17) 및 타측변부(12) 측 돌출부(17)가 상기 연결홈부(16)에 끼워져 서로 연결 조립되고, 상면 중앙에는 저면까지 관통된 용기삽입홀(18)이 형성되어 있으며, 상기 용기삽입홀(18)의 주변에는 벽면에 다수의 걸림홈(19a)이 형성된 다수 개의 핀삽입홈(19)이 형성되어 있고, 일측변부(11)와 타측변부(12)의 저부 모서리에는 길이방향을 따라 각각 &amp;quot;ㄴ&amp;quot;자 단면 형상의 외곽홈(20)이 형성되어 있으며, 양측의 외곽홈(20)과 이격되어 저부 중앙에는 상기 용기삽입홀(18)과 연통되며, 외곽홈(20)과 평행한 방향으로 &amp;quot;∪&amp;quot;자 단면 형상의 중앙홈(21)이 형성되어 있고, 일측 끝단이 외곽홈(20)과 연통되어 있으며, 타측 끝단은 중앙홈(21)과 연통되어 있고, &amp;quot;∪&amp;quot;자 단면 형상의 교차홈(22)이 다수 형성되어 있으며, 상기 외곽홈(20), 중앙홈(21), 교차홈(22)에 의해 둘러쌓이며 저부로 돌출된 다수 개의 저부돌출부(23)가 형성되어 있는 본체(10)와 하부 둘레에 측면개구부(31)가 형성되어 있으며, 내부에 양식용 해삼 또는 전복 종묘가 저장되는 저장공간(32)이 형성되어 있고, 상기 용기삽입홀(18)에 삽입되되, 측면개구부(31)가 위치한 하부가 본체(10) 저부의 중앙홈(21)으로 돌출되어 저장공간(32)이 중앙홈(21)과 연통되도록 이루어져 있으며, 상부에는 덮개(33)가 설치되어 저장공간(32)을 개폐시키도록 이루어져 있으며, 토기 재질로 이루어진 저장용기(30)를 포함하여 구성되며, 전후로 인접한 본체(10)의 일측변부(11)와 타측변부(12)가 서로 맞닿아 각각 저부에 형성되어 있는 외곽홈(20)이 접하여 &amp;quot;∪&amp;quot;자형 단면의 통로를 이루면서 좌우로 인접한 본체(10)의 중앙홈(21)이 상기 통로와 연통되도록 이루어져 있는 것을 특징으로 하며, 상면에는 핀삽입홈이 형성되어 있어 해중림을 조성할 수 있도록 하며, 본체의 저부에는 해삼 및 전복 종묘가 인접한 본체의 저부 사이로 이동 가능하도록 통로를 형성하는 한편, 본체 중앙에는 해삼 또는 전복 종묘가 저장되는 저장공간이 구비된 저장용기가 삽입되되, 저장용기의 내부가 본체 저부의 통로와 연통되도록 함으로써 본체의 저부에 외부와 최대한 격리된 성장 공간을 제공할 수 있게 된다. claims: 청구항 1은 본 발명의 해삼 또는 전복 양식용 패널의 상측 부분을 나타낸 분해 사시도.청구항 2는 본 발명의 해삼 또는 전복 양식용 패널의 저부측을 나타낸 분해 사시도.청구항 3은 본 발명의 해삼 또는 전복 양식용 패널이 다수 연결된 상태를 저부측에서 나타낸 사시도.청구항 4는 본 발명에서 상측에 로프삽입홈이 형성된 예를 나타낸 분해 사시도., Ltext: 어업, prediction: 어업
359/1059 Row 359: application_number: 1020190157770, combined_string: invention_title: 수하식 양식 구조물 abstract: 본 발명은 수하식으로 양식이 가능한 구조물에 관한 것으로서, 본 발명의 일 실시예에 따르면, 다수 개의 부력체; 다수 개의 부력체 간을 연결하는 제1연결라인; 제1연결라인으로부터 하방으로 연장된 다수개의 제2연결라인; 및 다수 개의 제2연결라인과 연결되고, 양식물이 성장되는 하나 이상의 수하라인이 하방으로 배치되도록 하는 제3연결라인;을 포함하고, 양식물의 자중은 제3연결라인, 제2연결라인, 제1연결라인 및 다수 개의 부력체로 순차적으로 전달되는, 수하식 양식 구조물이 제공된다. claims: 다수 개의 부력체;상기 다수 개의 부력체 간을 연결하는 제1연결라인;상기 제1연결라인으로부터 하방으로 연장된 다수개의 제2연결라인; 및상기 다수 개의 제2연결라인과 연결되고, 양식물이 성장되는 하나 이상의 수하라인이 하방으로 배치되도록 하는 제3연결라인;을 포함하고,상기 양식물의 자중은 상기 제3연결라인, 상기 제2연결라인, 상기 제1연결라인 및 상기 다수 개의 부력체로 순차적으로 전달되는, 수하식 양식 구조물., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

360/1059 Row 360: application_number: 1020190154068, combined_string: invention_title: 해상풍력을 이용한 굴 양식 장치 abstract: 본 발명은 굴 양식 장치에 관한 것으로서, 더욱 상세하게는 해수면에서 풍력을 이용하여 별도의 전기 에너지 없이 굴 양식 케이지를 수면위와 수면아래로 순환시키는 굴 양식 장치에 관한 것이다.본 발명은 해상풍력을 이용한 굴 양식 장치에 있어서, 부력을 가져 해수면에 부유하는 부력체; 상기 부력체의 일측에 형성되어, 해상풍력을 이용하여 동력이 발생하는 동력발생부; 상기 동력발생부 하부에 설치되어, 상기 동력발생부에서 발생한 동력을 웜과 웜기어에 의해 수직방향으로 동력전달부에 전달하는 기어부; 상기 기어부를 감싸면서 상기 기어부를 외부요인으로부터 보호하는 기어박스; 상기 기어박스 일측 또는 양측에 설치되며, 상기 윔기어의 회전축 끝단에 설치된 구동 풀리(Pulley)와 굴 양식부에 연결된 종동 풀리가 타이밍 벨트(Timing belt)에 의해 연결되어, 상기 기어부에서 전달된 동력을 굴 양식부로 전달하는 동력전달부; 상기 동력전달부로부터 전달되는 동력에 의해 굴이 수납되는 굴 양식 케이지를 수면위와 수면아래로 순환시키는 굴 양식부;를 포함하는 해상풍력을 위한 굴 양식 장치를 제공할 수 있다. claims: 해상풍력을 이용한 굴 양식 장치에 있어서, 부력을 가져 해수면에 부유하는 부력체;상기 부력체의 일측에 형성되어, 해상풍력을 이용하여 동력이 발생하는 동력발생부;상기 동력발생부 하부에 설치되어, 상기 동력발생부에서 발생한 동력을 웜과 웜기어에 의해 수직방향으로 동력전달부에 전달하는 기어부;상기 기어부를 감싸면서 상기 기어부를 외부요인으로부터 보호하는 기어박스;상기 기어박스 일측 또는 양측에 설치되며, 상기 윔기어의 회전축 끝단에 설치된 구동 풀리(Pulley)와 굴 양식부에 연결된 종동 풀리가 타이밍 벨트(Timing belt)에 의해 연결되어, 상기 기어부에서 전달된 동력을 굴 양식부로 전달하는 동력전달부;상기 동력전달부로부터 전달되는 동력에 의해 굴이 수납되는 굴 양식 케이지를 수면위와 수면아래로 순환시키는 굴 양식부;를 포함하는 굴 양식 장치., Ltext: 어업, prediction: 어업
361/1059 Row 361: application_number: 1020190152982, combined_string: invention_title: 굴 양식 장치 abstract: 본 발명은 해상에서 수산양식 동물, 특히 조개, 더 구체적으로는 굴을 양육하기 위한 굴 양식 장치에 관한 것으로, 해상의 바닥면에 일정 간격으로 이격되어 복수 개로 배치되는 고정부와, 복수 개의 상기 고정부에 연결되되, 단부에는 부표가 결합되는 연결부와, 상기 연결부에 연결되는 양육망과, 상기 양육망의 하단에 결합되며, 상기 양육망과 상기 연결부가 연결되는 각도를 변경시키는 터빈부 및 상기 양육망과 터빈부 사이에 결합되며, 상기 터빈부와 양육망을 체결시키는 체결부를 포함하는 것을 특징으로 한다. claims: 해상의 바닥면에 일정 간격으로 이격되어 복수 개로 배치되는 고정부;복수 개의 상기 고정부에 연결되되, 단부에는 부표가 결합되는 연결부;상기 연결부에 연결되는 양육망;상기 양육망의 하단에 결합되며, 상기 양육망과 상기 연결부가 연결되는 각도를 변경시키는 터빈부; 및상기 양육망과 터빈부 사이에 결합되며, 상기 터빈부와 양육망을 체결시키는 체결부;를 포함하는 것을 특징으로 하는 굴 양식 장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

362/1059 Row 362: application_number: 1020190153062, combined_string: invention_title: 회전 부력체를 이용한 가두리 양식장 abstract: 회전 부력체를 이용한 가두리 양식장이 개시된다. 개시되는 일 실시예에 따른 가두리 양식장은, 내부에 길이 방향으로 관통부가 마련되는 복수 개의 부력체, 복수 개의 부력체의 상단에 마련되는 고정바, 고정바와 연결되고, 고정바 상에 마련되는 이동 통로, 관통부를 통해 복수 개의 부력체를 연결하는 제1 로프, 및 일단이 제1 로프에 연결되고, 타단이 고정바에 연결되는 제2 로프를 포함한다. claims: 내부에 길이 방향으로 관통부가 마련되는 복수 개의 부력체;상기 복수 개의 부력체의 상단에 마련되는 고정바;상기 고정바와 연결되고, 상기 고정바 상에 마련되는 이동 통로;상기 관통부를 통해 상기 복수 개의 부력체를 연결하는 제1 로프; 및일단이 상기 제1 로프에 연결되고, 타단이 상기 고정바에 연결되는 제2 로프를 포함하고, 상기 부력체는, 내부에 상기 관통부가 길이 방향으로 마련되는 바디; 상기 바디의 외주면에 마련되고 유체의 흐름에 의해 상기 바디가 회전하도록 하는 회전 유도부; 및상기 바디의 내부에서 상기 관통부와 상기 바디를 연결하며 마련되는 복수 개의 지지 리브를 포함하는, 가두리 양식장., Ltext: 어업, prediction: 어업
363/1059 Row 363: application_number: 1020190145410, combined_string: invention_title: 해상풍력발전기를 이용한 가두리 양식장 abstract: 해상풍력발전기를 이용한 가두리 양식장이 제시된다. 본 발명의 실시예에 따른 해상풍력발전기를 이용한 가두리 양식장은, 해상에 수직으로 세워져 하부는 해저면에 고정되고, 상부는 해수면 위로 노출되는 해상기초시설물; 상기 해상기초시설물의 외면에 설치되는 가두리 양식장; 상기 해상기초시설물의 내부에 설치되어 가두리 양식장에 공급될 사료를 저장하는 저장탱크; 상기 저장탱크의 출구로 배출되는 사료를 이송하는 사료 이송장치; 상기 사료 이송장치에 의해 이송된 사료를 해수와 혼합하여 가두리 양식장에 공급하는 사료 공급장치; 상기 해상기초시설물 내부에 설치되어 상기 사료 이송장치와 사료 공급장치의 동작을 제어하는 컨트롤러; 및 상기 가두리 양식장에 설치되어 가두리 양식장 내부를 비추어줌으로써 양식어류가 어망에 충돌하여 폐사되는 것을 방지하는 조명장치;를 포함하는 것을 구성의 요지로 한다.본 발명에 따르면, 기상조건에 관계없이 수중에 위치하는 가두리 양식장에 자동으로 먹이를 공급할 수 있는 구성을 포함하는 해상풍력발전기를 이용한 가두리 양식장을 제공할 수 있다. claims: 해상에 수직으로 세워져 하부는 해저면에 고정되고, 상부는 해수면 위로 노출되는 해상기초시설물;상기 해상기초시설물의 외면에 설치되는 가두리 양식장;상기 해상기초시설물의 내부에 설치되어 가두리 양식장에 공급될 사료를 저장하는 저장탱크;상기 저장탱크의 출구로 배출되는 사료를 이송하는 사료 이송장치;상기 사료 이송장치에 의해 이송된 사료를 해수와 혼합하여 가두리 양식장에 공급하는 사료 공급장치;상기 해상기초시설물 내부에 설치되어 상기 사료 이송장치와 사료 공급장치의 동작을 제어하는 컨트롤러; 및상기 가두리 양식장에 설치되어 가두리 양식장 내부를 비추어줌으로써 양식어류가 어망에 충돌하여 폐사되는 것을 방지하는 조명장치;를 포함하는 것을 특징으로 하는 해상풍력발전기를 이용한 가두리 양식장.해상에 수직으로 세워져 하부는 해저면에 고정되고, 상부는 해수면 위로 노출되는 해상기초시설물;상기 해상기초시설물에서 수십에서 수천미터 떨어진 수중에 설치되는 가두리 양식장;상기 해상기초시설물의 내부에 설치되어 가두리 양식장에 공급될 사료를 저장하는 저장탱크;상기 저장탱크의 출구로 배출되는 사료를 이송하는 사료 이송장치;상기 사료 이송장치에 의해 이송된 사료를 해수와 혼합하여 가두리 양식장에 공급하는 사료 공급장치;상기 해상기초시설물 내부에 설치되어 상기 사료 이송장치와 사료 공급장치의 동작을 제어하는 컨트롤러; 및상기 가두리 양식장에 설치되어 가두리 양식장 내부를 비추어줌으로써 양식어류가 어망에 충돌하여 폐사되는 것을 방지하는 조명장치;를 포함하는 것을 특징으로 하는 해상풍력발전기를 이용한 가두리 양식장., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

364/1059 Row 364: application_number: 1020190140933, combined_string: invention_title: 해상지주를 활용한 4차산업혁명 해상주거관광생태통합 사물인터넷, 무인 로봇 양식장 abstract: 일 실시예에 따른 사물인터넷 기반의 무인 로봇 양식장 시스템은, 수면 상에 부유하도록 부력을 가지며, 해수의 유출입으로 부력을 조절하는 사물인터넷 기반의 부유식 구조물을 구성하는 부유 조정식 구조체; 상기 부유 조정식 구조체의 상부에 로봇 작업대가 설치되고, 상기 설치된 로봇 작업대를 이용하여 로봇의 작업이 가능한 이동식 로봇 운행 레일; 및 상기 부유 조정식 구조체의 하부에 설치되며, 상기 부유 조정식 구조물에 구성된 부유식 구조물의 제어를 통하여 해수의 유출입이 조절됨에 따라 승하강되는 양식장을 포함하고, 상기 양식장 시스템은, 통신 칩이 장착됨에 따라 구성된 통신 환경을 통하여 상기 양식장의 생태 환경을 자동으로 계측하고, 상기 양식장 시스템에 구성된 각각의 구성 요소와 데이터를 송수신하며, 상기 송수신된 데이터를 원격의 서버와 통신할 수 있다. claims: 사물인터넷 기반의 무인 로봇 양식장 시스템에 있어서, 수면 상에 부유하도록 부력을 가지며, 해수의 유출입으로 부력을 조절하는 사물인터넷 기반의 부유식 구조물을 구성하는 부유 조정식 구조체; 상기 부유 조정식 구조체의 상부에 로봇 작업대가 설치되고, 상기 설치된 로봇 작업대를 이용하여 로봇의 작업이 가능한 이동식 로봇 운행 레일; 및상기 부유 조정식 구조체의 하부에 설치되며, 상기 부유 조정식 구조체에 구성된 부유식 구조물의 제어를 통하여 해수의 유출입이 조절됨에 따라 승강되는 양식장 을 포함하고, 상기 양식장 시스템은, 통신 칩이 장착됨에 따라 구성된 통신 환경을 통하여 상기 양식장의 생태 환경을 자동으로 계측하고, 상기 양식장 시스템에 구성된 각각의 구성 요소와 데이터를 송수신하며, 상기 송수신된 데이터를 원격의 서버와 통신하는 사물인터넷 기반의 무인 로봇 양식장 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

365/1059 Row 365: application_number: 1020190134489, combined_string: invention_title: 양식장용 스크류식 사료공급유닛 abstract: 본 발명은 사료저장통으로부터 투입호퍼를 거쳐 스크류피더의 내부로 투입된 사료를 스크류피더의 이송스크류를 이용하여 스크류케이싱을 따라 양식수조로 공급시키도록 한 양식장용 스크류식 사료공급유닛에 관한 것으로서, 더욱 상세하게는 투입호퍼의 직전방에 해당하는 스크류케이싱의 내주면 상측부에 소정의 길이만큼 하방으로 돌출되는 차단판을 설치하거나, 투입호퍼의 전방측에서 스크류케이싱을 따라 위치하는 전방측 이송스크류의 스크류 피치를 투입호퍼의 하부측에 위치하는 후방측 이송스크류의 스크류 피치보다 크게 되도록 하거나, 상기 전방측 이송스크류의 피치가 스크류케이싱의 길이 방향을 따라 점차 증대되도록 하거나, 투입호퍼의 직전방에 해당하는 부분을 제외한 나머지 스크류케이싱 부분의 내경이 이송스크류의 스크류날개 직경보다 크게 되도록 함으로서, 이송스크류의 축회전에 의하여 사료저장통의 투입호퍼로부터 스크류케이싱을 거쳐 공급되는 사료가 이송스크류와 스크류케이싱의 사이에서 과도하게 압착되지 않고 이송스크류에 의하여 부드럽게 밀려 나갈 수 있도록 하며, 이를 통하여 이송스크류의 과도한 압착력으로 사료의 입자가 뭉개짐에 따라 사료의 기능을 제대로 수행하지 못하는 현상과, 사료의 압착에 따른 스크류모터의 과부하 및 스크류피더의 고장이나 오작동을 미연에 방지할 수 있도록 한 양식장용 스크류식 사료공급유닛에 관한 것이다. claims: 하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(3)를 포함하여서 이루어지며, 상기 스크류피더(3)는 선단부가 개구된 원통 파이프 형상의 스크류케이싱(4)과, 상기 스크류케이싱(4)의 내부에 삽입 설치되어 스크류모터(7)의 동력으로 축회전하는 이송스크류(5)를 포함하여서 이루어지는 양식장용 스크류식 사료공급유닛(10)에 있어서,상기 투입호퍼(2)의 직전방에 해당하는 스크류케이싱(4)의 내주면 상측부에는 사료(8)의 이송량을 제한하는 차단판(9)이 하측 방향으로 돌출 형성되고, 상기 차단판(9)은 스크류케이싱(4) 직경의 1/15 내지 2/5에 해당하는 길이로 돌출 형성되며,상기 이송스크류(5)의 축회전시 차단판(9)이 걸리게 되는 스크류 부분은 일정 피치 만큼이 잘려 나간 형태를 이루거나, 해당 스크류 부분에 차단판(9)의 통과홈이 절개 형성되는 것을 특징으로 하는 양식장용 스크류식 사료공급유닛.하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(3)를 포함하여서 이루어지며, 상기 스크류피더(3)는 선단부가 개구된 원통 파이프 형상의 스크류케이싱(4)과, 상기 스크류케이싱(4)의 내부에 삽입 설치되어 스크류모터(7)의 동력으로 축회전하는 이송스크류(5)를 포함하여서 이루어지는 양식장용 스크류식 사료공급유닛(10)에 있어서,상기 이송스크류(5)는 투입호퍼(2)의 출구 하측에 위치하는 스크류의 피치를 기준으로 하여 투입호퍼(2)의 전방측에 위치하는 나머지 스크류의 피치가 10~50%의 비율로 크게 형성된 것임을 특징으로 하는 양식장용 스크류식 사료공급유닛.하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(3)를 포함하여서 이루어지며, 상기 스크류피더(3)는 선단부가 개구된 원통 파이프 형상의 스크류케이싱(4)과, 상기 스크류케이싱(4)의 내부에 삽입 설치되어 스크류모터(7)의 동력으로 축회전하는 이송스크류(5)를 포함하여서 이루어지는 양식장용 스크류식 사료공급유닛(10)에 있어서,상기 이송스크류(5)는 투입호퍼(2)의 출구 하측에 위치하는 스크류의 피치를 기준으로 하여 투입호퍼(2)의 전방측에 위치하는 나머지 스크류의 피치가 스크류케이싱(4)의 길이 방향을 따라가면서 5~20%의 비율로 점차 크게 형성된 것임을 특징으로 하는 양식장용 스크류식 사료공급유닛.하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(3)를 포함하여서 이루어지며, 상기 스크류피더(3)는 선단부가 개구된 파이프 형상의 스크류케이싱(4)과, 상기 스크류케이싱(4)의 내부에 삽입 설치되어 스크류모터(7)의 동력으로 축회전하는 이송스크류(5)를 포함하여서 이루어지는 양식장용 스크류식 사료공급유닛(10)에 있어서,상기 투입호퍼(2)의 직전방에 해당하는 스크류케이싱(4) 부분은 이송스크류(5)의 스크류날개 가장자리와 밀착되는 압출케이싱(4a)이 되고, 상기 압출케이싱(4a) 부분을 제외한 나머지 스크류케이싱(4) 부분은 이송스크류(5)의 스크류날개 직경보다 소정의 길이(d)만큼 큰 내경을 가지는 확장케이싱(4b)으로 형성되는 것을 특징으로 하는 양식장용 스크류식 사료공급유닛., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

366/1059 Row 366: application_number: 1020190134492, combined_string: invention_title: 양식장용 스크류식 사료공급장치 abstract: 본 발명은 사료저장통으로부터 그 하단측의 투입호퍼를 거쳐 스크류피더의 내부로 투입된 사료를 스크류모터의 동력으로 축회전하는 스크류피더의 이송스크류를 이용하여 스크류케이싱을 따라 양식수조로 공급시키도록 하되, 상기 사료저장통의 하부에는 사료저장통을 지지하는 받침통이 설치되고, 상기 스크류케이싱은 받침통의 벽체를 관통하여 소정의 길이만큼 전방측으로 연장 형성된 양식장용 스크류식 사료공급장치에 관한 것으로서, 더욱 상세하게는 상기 스크류케이싱을 받침통의 내부에 배치되는 후방케이싱과 받침통의 전방면에 착탈 가능하게 조립 설치되는 전방케이싱으로 분할 형성시키고, 상기 이송스크류의 스크류축은 스크류모터의 구동축과 나사체결식으로 착탈 가능하게 조립 설치함으로서, 스크류피더의 청소나 수리 및 유지보수 작업을 매우 손쉽고 간단하게 수행할 수 있도록 하며, 상기 투입호퍼의 직전방에 해당하는 스크류케이싱의 내주면 상측부에 사료의 이송량을 제한하는 차단판을 돌출 형성시킴으로서, 스크류케이싱을 거쳐 공급되는 사료가 이송스크류와 스크류케이싱의 사이에서 과도하게 압착되지 않고 이송스크류에 의하여 부드럽게 밀려 나갈 수 있도록 하며, 스크류케이싱의 선단 배출구에 설치되는 사료살포기의 비산플랩을  ） 형태의 곡면판으로 하여 사료의 확산범위를 보다 더 폭넓게 확보할 수 있도록 한 양식장용 스크류식 사료공급장치에 관한 것이다. claims: 하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)와 연결 설치되어 사료저장통(1)을 하부에서 지지하는 받침통(6)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 받침통(6)의 벽체 부분을 관통하여 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(7)를 포함하여서 이루어지며, 상기 스크류피더(7)는 투입호퍼(2)의 하단 출구측으로부터 받침통(6)의 벽체 부분을 관통하여 연장되는 원통 파이프 형상의 스크류케이싱(11)과, 상기 스크류케이싱(11)의 내부에 삽입 설치되어 스크류모터(30)의 동력으로 축회전하는 이송스크류(12)를 포함하여서 이루어지고, 상기 스크류케이싱(11)의 선단측에는 사료의 배출구(11a)가 제공된 양식장용 스크류식 사료공급장치(10)에 있어서,상기 스크류케이싱(11)은 투입호퍼(2)의 하단 출구로부터 받침통(6)의 벽체측에 이르기까지의 길이를 가지는 후방케이싱(22)과, 상기 후방케이싱(22)의 선단측으로부터 받침통(6)의 외부로 연장되는 전방케이싱(21)으로 분할 형성되고, 상기 전방케이싱(21)은 케이싱조립부(17)를 개재시킨 상태로 받침통(6)과 탈,부착 가능하게 연결 설치되며,상기 케이싱조립부(17)는 전방케이싱(21)의 후단부측 외주면상에서 전방케이싱(21)과 일체로 연결 설치되는 장착플랜지(24)와, 상기 받침통(6)의 외측면상에 조립 설치된 상태로 전방케이싱(21)의 장착플랜지(24)와 맞대어지는 받침플랜지(25)와, 상기 장착플랜지(24)와 받침플랜지(25)의 외주면을 따라 회전 가능하게 설치되는 원통형 결착노브(7a)를 포함하여서 이루어지고,상기 장착플랜지(24)의 후단부측 외주면에는 일정한 각도범위를 두고 쐐기프레임(24a)이 돌출 형성되며, 상기 받침플랜지(25)의 선단부측 외주면에는 일정한 각도범위를 두고 결착노브(7a)용 가이드프레임(25a)이 돌출 형성되고, 상기 결착노브(7a)의 선단부측 내주면에는 장착플랜지(24)의 쐐기프레임(24a)이 제공하는 쐐기홈(24b)을 따라 돌려 끼워지는 결착프레임(7b)이 돌출 형성되며,상기 이송스크류(12)의 스크류축(13) 후단부는 스크류모터(30)의 동력으로 축회전하는 구동축(28)과 나사체결식으로 조립 설치되고, 상기 이송스크류(12)의 조립 방향은 구동축(28)의 회전이 정 방향과 반대 방향이 되는 것을 특징으로 하는 양식장용 스크류식 사료공급장치., Ltext: 어업, prediction: 임업
367/1059 Row 367: application_number: 1020190117264, combined_string: invention_title: 가리비 양식 방법 abstract: 본 발명은 가리비 양식 방법에 관한 것으로서, 고무판이 다수 개 구비된 채롱에 가리비 치패를 상기 고무판에 부착시켜 해수에서 수하식으로 소정 기간 양식할 때에, 상기 고무판은 구멍이 형성되어 있고, 에틸렌 아크릴 고무, 게르마늄 및 아민계 가류제를 포함한 고무 조성물로 이루어진 것을 특징으로 한다. 본 발명에 따르면, 채롱의 고무판에서 게르마늄이 높은 함량으로 존재하므로 가리비가 안칙된 고무판에서 게르마늄에 의해 산소의 발생량이 증가하므로 치패가 산소의 결핍에 의해 폐사하는 비율이 저감된다. 또한, 고무판이 향상된 내염수성과 내수성을 가지므로 다년간 채롱을 해수에서 사용하더라도 세척할 때에 변형과 깨짐이 발생하지 않아 채롱의 내구성이 향상된다. claims: 고무판이 다수 개 구비된 채롱에 가리비 치패를 상기 고무판에 부착시켜 해수에서 수하식으로 소정 기간 양식하는 가리비 양식방법에 있어, 상기 고무판은 구멍이 형성되어 있고, 에틸렌 아크릴 고무 100 중량부 대비 10 ~ 500 ㎛의 분말의 게르마늄 30 ~ 100 중량부, 아민계 가류제 및 이소티오시아네이트류를 포함하고, 상기 아민계 가류제는 헥사메틸렌디아민카바메이트 또는 N, N´-디신나밀리덴-1,6-헥산 디아민이고, 상기 이소티오시아네이트류는 2,4-디클로로페닐이소티오시아네이트 또는 3,4-디클로로페닐이소티오시아네이트인, 고무 조성물로 제조된 것을 특징으로 하는 가리비 양식 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

368/1059 Row 368: application_number: 1020190115420, combined_string: invention_title: 해삼 양식장치 abstract: 양식장에 설치되어 해삼이 표면에 부착하여 생육할 수 있는 파판이 바닥과 수직하게 설치될 수 있도록 고정하는 상부 파판 홀더부; 상기 상부 파판 홀더부 하부에는 바닥과 수평하게 하나 이상의 파판이 수납될 수 있는 수용부가 마련되는 하부 파판 홀더부가 형성되며; 상기 하부 파판 홀더부 하부 모서리에는 받침대가 설치되는 해삼 양식장치를 제공함으로써 수직 설치된 파판에 부착된 양식 해삼은 중력의 영향으로 일정한 부착력을 유지하지 않아도 되고, 부착력이 약해지면 탈락하여 양식 해삼이 하부 파판에 다수가 서식하게 됨으로 성장 불균형을 방지할 수 있을 뿐만 아니라 상부 파판의 먹이 안착률이 우수하여 해삼 성장량 증가 및 먹이효율을 증가시킬 수 있는 효과가 있다. claims: 해삼이 부착하여 성장하는 복수개의 파판이 바닥면과 수직하게 형성될 수 있도록 하는 상부 파판 홀더부의 하부에 양식장 바닥면과 수평하게 하나 이상의 파판이 수납될 수 있도록 한 수용부를 갖는 하부 파판 홀더부가 상기 상부 파판홀더부와 일체로 결합되어 이루어지며;상기 상부 파판 홀더부는 가로 및 세로 부재가 연결되어 상부가 개구된 사각틀 형상의 상부면과 상부면을 이루는 가로 및 세로 부재와 연결되는 일정 길이의 수직부재가 하부 파판 홀더부와 일체로 결합되어 상광 하협의 내부 공간부를 갖는 구조를 이루며,상기 상부 파판 홀더부의 좌측 및 우측면의 수직부재는 서로 마주하는 방향을 향해 65 내지 75도 사이각으로 경사를 이루며 상광하협의 하향 수렴 구조를 갖고 하부 파판 홀더부의 상부 내측면에 일체로 결합되며, 상기 하부 파판 홀더부는 수직부재와 수평부재의 결합으로 직육면체 형상을 이루고, 전면 또는 후면에는 파판이 바닥면과 수평으로 수납될 수 있도록 파판 수용부가 형성되며, 상기 하부 파판 홀더부 하부 모서리에는 받침대가 형성되어 이루어지는 것을 특징으로 하는 해삼 양식장치, Ltext: 어업, prediction: 어업
369/1059 Row 369: application_number: 1020190111376, combined_string: invention_title: 전복양식장치 abstract: 본 발명은 전복양육장치에 관한 것으로, 부구(11)들에 의해 해상에 떠 있는 작업대(1), 상기 작업대(1)의 저면측에 거치되어 수중에 잠겨 유지되는 전복 쉘터(2), 상기 쉘터(2)로 유입된 뻘이 해수 흐름에 의해 제거되도록 작업대(1)의 양측에서 각각 해저에 고정된 닻(31)에 연결된 로프(32)들을 선택적으로 견인하고 풀어주어 작업대의 좌우측을 쉘터(2)들과 함께 상하좌우로 요동치게 하는 요동장치를 포함하여 구성됨으로써, 작업대를 요동장치에 의해 상하좌우로 요동시킴으로써 그 하측에 설치되어 요동되는 쉘터들에서 종패와 전복 먹이에 유입된 뻘과 슬러리를 제거하고 새로운 해수가 유입되므로, 전복이 폐사되지 않고 건강하게 양식할 수 있게 되어 생산성이 증대되는 효과가 있으며, 상기 요동장치는 기존의 양식장치에도 간편하게 설치할 수 있으며, 단순화된 구조로 설치비용을 절감할 수 있는 효과가 있다 claims: 부구(11)들에 의해 해상에 떠 있는 작업대(1), 상기 작업대(1)의 저면측에 거치되어 수중에 잠겨 유지되는 전복 쉘터(2),상기 쉘터(2)로 유입된 뻘이 해수 흐름에 의해 제거되도록 작업대(1)의 양측에서 각각 해저에 고정된 닻(31)에 연결된 로프(32)들을 선택적으로 견인하고 풀어주어 작업대의 좌우측을 쉘터(2)들과 함께 상하좌우로 요동치게 하는 요동장치를 포함하는 전복양육장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

370/1059 Row 370: application_number: 1020190104343, combined_string: invention_title: 양식장용 부구 abstract: 본 발명은 양식장용 부구에 관한 것으로서, 더욱 상세하게는 굴이나 따개비 등의 해양생물이 부구 표면에 부착되는 것을 방지함으로써 해양생물에 의해 부구가 손상되거나 양식망이 손상되는 것을 예방할 수 있는 양식장용 부구에 관한 것이다.본 발명에 따른 양식장용 부구는 파도나 해류에 의해 양식장용 부구가 자동으로 회전되므로 수중에 일정 시간 침지되어 있던 부구의 표면을 공기중 및 태양광에 노출시킬 수 있어 부구 표면에 녹조류 및 해조류, 굴이나 따개비 등과 같은 해양 부착생물이 부착 및 서식하는 것을 사전에 예방 및 차단할 수 있고, 해양 부착 생물이 부착될 시 이를 쉽게 제거할 수 있는 장점이 있다.또한, 본 발명에 따른 양식장용 부구는 그 표면에 굴이나 따개비가 부착되는 것을 미연에 차단함으로써 부구의 내구성을 높여 사용 기간을 늘리고, 양식망이 손상되는 것을 예방할 수 있는 장점이 있다. claims: 부력을 갖고, 원통형으로 형성되며, 부구 고정용 브라켓에 길이방향 양측이 회전 가능하게 설치되는 부구본체와;상기 부구본체의 길이방향 양측에 구비되고, 파도에 의해 상기 부구본체에 돌림힘을 발생시키는 회전유도부;를 구비하고,상기 회전유도부는 상기 부구본체의 길이방향 양측 전면 및 후면으로부터 각각 돌출되고, 상기 부구본체의 전면 및 후면 중심 측에서 상기 부구본체의 전면 및 후면 가장자리 측으로 각각 연장되며, 상기 부구본체의 원주방향을 따라 일정 간격 이격되게 배치되는 복수의 간섭날개를 포함하는 것을 특징으로 하는 양식장용 부구.상판을 설치할 수 있도록 형성된 상판부와, 상기 상판부의 길이방향 양측 단부로부터 하방으로 각각 연장되고 내부에는 수평방향으로 중공부가 형성된 회전지지부를 포함하는 부구 고정용 브라켓과;부력을 갖고 원통형으로 형성되며 길이방향 양측 단부가 각각 상기 회전지지부의 중공부에 삽입된 상태로 상기 회전지지부에 회전 가능하게 설치되는 부구본체와, 상기 부구본체의 길이방향 양측에 구비되고 파도에 의해 상기 부구본체에 돌림힘을 발생시키는 회전유도부를 포함하는 양식장용 부구;를 구비하고,상기 회전유도부는 상기 부구본체의 길이방향 양측 전면 및 후면으로부터 각각 돌출되고, 상기 부구본체의 전면 및 후면 중심 측에서 상기 부구본체의 전면 및 후면 가장자리 측으로 각각 연장되며, 상기 부구본체의 원주방향을 따라 일정 간격 이격되게 배치되는 복수의 간섭날개를 포함하고,상기 부구 고정용 브라켓은 상기 부구본체가 회전될 때, 상기 부구본체의 외주면에 마찰되면서 상기 부구본체의 외주면에 부착된 이물질을 제거하기 위한 이물질 제거부를 더 구비하며,상기 이물질 제거부는 일 측의 상기 회전지지부로부터 타 측의 상기 회전지지부로 연장되고, 상기 부구본체의 외주면에 접하도록 설치되는 스크래퍼를 포함하는 것을 특징으로 하는 양식장용 부유체., Ltext: 어업, prediction: 임업
371/1059 Row 371: application_number: 1020190101539, combined_string: invention_title: 양식장 용수의 살균장치 abstract: 본 발명은 양식장 용수의 살균장치에 관한 것으로서, 더욱 상세하게는 해양생물, 담수생물 등의 양식장 용수의 살균성분 농도를 필요한 농도로 정확하게 맞출 수 있는 양식장 용수의 살균장치에 관한 것이다. 본 발명에 따른 양식장 용수의 살균장치는 원수 공급 라인을 통해 공급되는 원수가 저장되고 염소농도가 조정되는 조정조; 상기 조정조에서 배출되는 양식장 용수를 전기분해를 통해 살균성분을 생성시키는 차아염소산 생성장치; 상기 조정조에서 배출되는 양식장 용수의 잔류 염소를 제거하는 잔류염소 처리장치; 상기 잔류염소 처리장치에서 배출되는 양식장 용수가 공급되는 양식 수조; 및 장치내에 설치된 각종 밸브, 상기 차아염소산 생성장치를 온오프시키는 콘트롤패널을 포함하되, 상기 조정조의 원수를 상기 차아염소산 생성장치로 용수 공급라인을 통해 유입시킨 후, 상기 차아염소산 생성장치에서 생성된 살균성분을 함유하는 전해수를 차아염소산 공급라인을 통해 상기 조정조로 다시 유입시킨다. claims: 원수 공급 라인을 통해 공급되는 원수가 저장되고 염소농도가 조정되는 조정조;상기 조정조에서 배출되는 양식장 용수를 전기분해를 통해 살균성분을 생성시키는 차아염소산 생성장치;상기 조정조에서 배출되는 양식장 용수의 잔류 염소를 제거하는 잔류염소 처리장치; 상기 잔류염소 처리장치에서 배출되는 양식장 용수가 공급되는 양식 수조; 및 장치내에 설치된 각종 밸브, 상기 차아염소산 생성장치를 온오프시키는 콘트롤패널을 포함하되, 상기 조정조의 원수를 상기 차아염소산 생성장치로 용수 공급라인을 통해 유입시킨 후, 상기 차아염소산 생성장치에서 생성된 살균성분을 함유하는 전해수를 차아염소산 공급라인을 통해 상기 조정조로 다시 유입시키는 것을 특징으로 하는 양식장 용수의 살균장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

372/1059 Row 372: application_number: 1020190099689, combined_string: invention_title: 양식장용 부유 구조물 abstract: 해수면에 부유할 수 있는 부력을 포함하는 부체가 일정 간격으로 복수개 배치되고; 상기 부체의 상부에 설치되어 작업자가 가두리 양식장에서 작업하는 공간을 제공하는 발판부로 이루어지는 양식장용 부유 구조물을 제공함으로써 상기 부체는 성형제작이 용이하여 제작에 소요되는 시간과 수고 및 비용을 감소시킴은 물론 부력은 감소되지 않으면서 내구력은 향상되어 발판부의 하중이 증가해도 부체구조의 변형이 거의 없어 장치 교환에 소비되는 비용을 줄일 수 있다. claims: 해수면에 부유할 수 있도록 부력을 갖는 양식장용 부유구조물에 있어서, 부유구조물의 내부는 빈공간을 갖고, 외측면 하부는 반원형상으로 이루어지며, 외측면 상부는 작업 공간을 제공하는 발판부를 형성하도록 평평한 형상으로 이루어지고, 상기 부유구조물의 내부 중심부 상, 하면에는 지지프레임의 상단 및 하단이 삽입 고정되도록 끼움부가 형성되어, 지지프레임이 수직방향으로 삽입 고정되며,내부 중심부에 고정되는 지지프레임은 직사면체의 판 형상으로 내부가 빈 공간을 이루고 좌, 우면을 관통하는 하나 이상의 통공이 형성되어 수직으로 구분된 좌우 공간의 압력평형을 이루도록하며, 전, 후면은 개구 또는 폐쇄되어 이루어지는 것을 특징으로 하는 양식장용 부유 구조물, Ltext: 어업, prediction: 임업
373/1059 Row 373: application_number: 1020190098983, combined_string: invention_title: 개체굴 양식장치 abstract: 본 발명은 굴 치패가 부착되어 생육하는 채묘부재를 포함하는 개체굴 양식장치로서, 상기 채묘부재는 바닷물 속에서 소정 시간이 경과 하면 녹는 플라스틱 재질로 이루어지는 것을 특징으로 하는 개체굴 양식장치를 제공한다. 본 발명은 상기 구성에 의해서, 개체굴이 부착되는 채묘부재의 표면을 물에 녹는 소재로 함으로써 일정 시간이 지난 후 굴 치패가 자동으로 양식장 바닥으로 떨어지고, 바닥으로 떨어진 굴은 특성상 다시는 어떤 곳에도 부착하지 않게 되어 개체굴로 성장하게 된다. claims: 굴 치패가 부착되어 생육하는 채묘부재를 포함하는 개체굴 양식장치로서,상기 채묘부재는 물 속에서 소정 시간이 경과 하면 녹는 소재로 이루어지는 것을 특징으로 하는 개체굴 양식장치.굴 치패가 부착하여 생육하는 채묘부재를 포함하는 개체굴 양식장치로서,상기 채묘부재는,플레이트 형상의 제1부재; 및상기 제1부재의 일측면 또는 양측면에 구비되고 굴 치패가 부착하여 먹이활동을 하는 제2부재;로 이루어지고,상기 제2부재는 물 속에서 소정 시간이 경과 하면 녹는 소재인 것을 특징으로 하는 개체굴 양식장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

374/1059 Row 374: application_number: 1020190095324, combined_string: invention_title: 해삼 전복전용 참나무 어초 abstract: 본 발명은 해삼 전복전용 참나무 어초에 관한 것이다. 본 발명은 중량물인 무게중심구조물 상에 다수의 참나무가 배열된 참나무유닛을 다층으로 마련함과 동시에 최상단의 참나무유닛에서 그 하부의 참나무유닛으로 갈수록 넓어지는 피라미드형상으로 마련함으로써 참나무유닛에 전복의 주된 먹이인 미역 등과 같은 해조류와 규조류의 부착, 발생 및 생장이 지속적으로 이루어지고 다층의 참나무유닛 전체에 걸쳐 골고루 서식되며, 특히 음지와 양지를 주야로 이동하는 전복 및 해삼의 생태특성을 고려하여 참나무유닛의 참나무들 사이에 트랙형상의 홈과 통로를 통해 전복 및 해삼의 은신처 내지 대피통로를 확보하고자 하는 어초분야에 유용하게 이용할 수 있다. claims: 중량물로 이루어진 무게중심구조물; 이 무게중심구조물 위에 복수의 층을 이루도록 서로 이격되어 수평으로 설치되는 다층프레임; 이 다층프레임의 각 층마다 소정간격으로 다수의 참나무가 배열 설치되는 다층참나무유닛; 을 포함하여 구성되는 것을 특징으로 하는 해삼 전복전용 참나무 어초., Ltext: 어업, prediction: 어업
375/1059 Row 375: application_number: 1020190095403, combined_string: invention_title: 복합배치 펌프 기반 육상양식장 해수공급시스템 abstract: 본 발명은 복합배치 펌프 기반 육상양식장 해수공급시스템을 제공한다. 이와 같은 본 발명에 따른 복합배치 펌프 기반 육상양식장 해수공급시스템은 육상 양식장의 규모 확장에 따라 요구되는 공급해수 유량의 확대가 육상 양식장으로 해수를 공급하는 해수공급배관의 해수면 아래 부위에 수중 보조펌프를 추가적으로 설치하는 것으로 가능해지도록 함으로써 육상 양식장과 해수공급배관 등의 현재 시설을 그대로 유지한 상태에서 보조펌프의 단순 설치를 통해서 공급해수의 유량 확대가 안정되고 원활하게 수행될 수 있게 되고, 수중 보조펌프의 추가 배치에 따른 공급해수의 유속증대와 유량확대를 통해 육상 양식장으로의 해수공급 안정성이 증대될 수 있으며, 특히 수중 보조펌프가 육상 양식장으로 해수를 공급하는 수역의 조수간만에 따른 최소 해수위 아래의 수심 위치에 설치되도록 함으로써 수중 보조펌프가 상시적으로 해수면 아래 잠긴 상태를 유지하면서 원활한 해수 강제 압송구동을 수행하게 되어 해수공급을 위한 시스템의 운용 안정성이 극대화될 수 있는 기술적 특징을 갖는다. claims: 육상 양식장(2)의 기계실(4)에 배치되는 메인 펌프(100);상기 메인 펌프(100)에 연결되어 해수면 아래로 연장형성되고, 설정된 해수유입 수심(H) 위치에 유입구(210)가 배치되는 해수공급배관(200);해수면 아래 잠긴 상태로 배치되고, 설정된 펌프설치 수심(h) 위치의 해수공급배관(200)에 설치되는 수중 보조펌프(300);육상 양식장(2)의 수조(3)와 연결되어 상기 수조(3)로 해수를 공급하는 양식장 연결배관(400);상기 해수공급배관(200)이 배치되는 수역(5)의 조수간만 정보에 맞추어 상기 메인 펌프(100)와 수중 보조펌프(300)의 동작을 제어하는 컨트롤러(500);를 포함하는 구성으로 이루어지는 것을 특징으로 하는 복합배치 펌프 기반 육상양식장 해수공급시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

376/1059 Row 376: application_number: 1020190095045, combined_string: invention_title: 해삼용 쉘터 abstract: 본 발명은 해삼용 쉘터에 관한 것으로, 더욱 상세하게는 유속에 의해 쉘터가 이동되는 것을 방지하여 해삼의 서식환경이 균일하게 유지될 수 있는 해삼용 쉘터에 관한 것이다.본 발명의 해삼용 쉘터는 해수가 유입 및 배출됨에 따라 길이방향으로 해수가 흐르는 해수조부 내에 상하방향으로 일정한 폭을 형성하며, 해수의 흐름 방향으로 연장되어 양측면에 해삼이 부착되는 생장공간을 형성하는 해삼생장부와; 상기 해삼생장부가 펼쳐진 상태를 유지하고, 유속에 의해 움직이는 것을 방지하도록, 상기 해삼생장부의 하부에 상기 해삼생장부의 길이방향을 따라 다수개가 상호 이격되게 설치되며, 상기 해삼생장부의 길이방향으로 양단부가 개방된 내부수용공간을 형성하여 내부에 해수가 흐름에 따라 상기 해삼생장부에 장력을 제공하고, 개방된 양단부를 통해 상기 내부수용공간에 해삼이 유입되어 해삼이 하면 또는 동면을 하거나 생장할 수 있는 해삼휴면유닛;을 구비한다. claims: 해수가 유입 및 배출됨에 따라 길이방향으로 해수가 흐르는 해수조부 내에 상하방향으로 일정한 폭을 형성하며, 해수의 흐름 방향으로 연장되어 양측면에 해삼이 부착되는 생장공간을 형성하는 해삼생장부와;상기 해삼생장부가 펼쳐진 상태를 유지하고, 유속에 의해 움직이는 것을 방지하도록, 상기 해삼생장부의 하부에 상기 해삼생장부의 길이방향을 따라 다수개가 상호 이격되게 설치되며, 상기 해삼생장부의 길이방향으로 양단부가 개방된 내부수용공간을 형성하여 내부에 해수가 흐름에 따라 상기 해삼생장부에 장력을 제공하고, 개방된 양단부를 통해 상기 내부수용공간에 해삼이 유입되어 해삼이 하면 또는 동면을 하거나 생장할 수 있는 해삼휴면유닛;을 구비하는 것을 특징으로 하는 해삼용 쉘터., Ltext: 어업, prediction: 어업
377/1059 Row 377: application_number: 1020190095046, combined_string: invention_title: 육상용 해삼 양식장 abstract: 본 발명은 육상용 해삼 양식장에 관한 것으로서, 더욱 상세하게는 육상에 해수가 흐르는 방향으로 해삼이 부착되어 생장하는 쉘터가 연장되게 설치될 수 있는 양식공간을 갖는 육상용 해삼 양식장에 관한 것이다.본 발명의 육상용 해삼 양식장은 다수의 쉘터가 수조부의 길이방향으로 각각 나란하게 연장되어 있어 수조부 공간대비 해삼이 부착되어 생장되는 다수의 부착공간이 확보되므로 해삼의 생산량을 증대시킬 수 있는 이점이 있다.그리고, 본 발명의 육상용 해삼 양식장은 쉘터의 하부에 형성된 다수의 해삼채집부에 의해 쉘터가 해수의 유속에 의해 움직이는 것이 방지되므로 쉘터 간 균일한 서식환경을 지속적으로 제공하여 다수의 해삼의 생장이 균일하게 이루어질 수 있는 이점이 있다. claims: 육상에 상방으로 개방되며 일정한 폭으로 제1방향으로 길게 연장된 양식공간이 형성되게 설치되며 해수가 유입되어 배출되는 수조부와;상기 수조부의 상부에 상기 수조부의 길이방향에 교차하는 방향으로 각각 연장되며 상기 수조부의 길이방향으로 상호 이격되게 배치되는 복수의 쉘터거치바를 포함하는 쉘터거치유닛과;상기 수조부 내에 양측면에 해삼이 부착되어 생장될 수 있는 부착공간을 제공할 수 있도록 상하방향으로 연장되고, 상기 제1방향으로 각각 길이 연장되며 상기 양식공간의 폭 방향으로 일정간격 이격되어 상호 나란하도록 상단에 상기 쉘터거치바에 거치되는 다수의 쉘터;를 구비하고,상기 쉘터는 상기 수조부의 하부에 양측이 상기 제1방향으로 개방되어, 상기 수조부 내에 흐르는 해수의 온도 상승 또는 하강에 따라 해삼이 상부에서 내려와 하면 또는 동면을 하거나 생장할 수 있는 유입공간을 각각 형성하여 해삼이 모일 수 있도록 유도하며, 해삼이 개방된 양측으로 유입되게 상기 제1방향으로 상호 이격되는 다수의 해삼채집부를 구비하는 것을 특징으로 하는 육상용 해삼 양식장., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

378/1059 Row 378: application_number: 1020190095047, combined_string: invention_title: 가두리 해삼 양식장치와 이를 이용한 가두리 양식장 abstract: 본 발명은 가두리 해삼 양식장치와 이를 이용한 가두리 양식장에 관한 것으로서, 더욱 상세하게는 가두리망 내에 수용되어 해삼이 생장할 수 있는 공간을 형성하는 가두리 양식장용 해삼 양식장치와 이를 이용한 가두리 양식장에 관한 것이다.본 발명의 가두리 해삼 양식장치와 이를 이용한 가두리 양식장은 격자형태로 배열된 다수 생육공간 중 일부를 해삼양식에 적용할 수 있어 이종의 해양생물의 양식이 가능하므로 양식공간 형성을 위한 별도의 설치비용을 절감할 수 있으며 공간활용을 효율을 높일 수 있어 경제적인 이점이 있다. 또한, 본 발명의 가두리 해삼 양식장치는 중심측에서 방사방향으로 다수의 쉘터부가 설치되어 구획된 다수의 해삼생장공간이 확보되므로 해삼의 생산량을 증대시킬 수 있는 이점이 있다. claims: 수상에 부유하는 가두리 양식장의 가두리망 내에 수용 가능하게 형성되며 각 면이 개방된 내부공간을 갖는 프레임과;상방으로 개방된 내부공간이 각각 형성되되 폭과 높이가 다른 다수의 쉘터부가 방사상 및 상하방향으로 상호 이격되게 중첩되어 상기 제1프레임의 중심측에서 외측 방향으로 구획된 다수의 해삼생장공간을 형성하는 쉘터유닛과;다수의 상기 쉘터부가 상기 프레임 내에서 상호 방사 방향 및 상하방향으로 이격되게 다수의 상기 쉘터부를 위치되게 고정하는 선형부재;를 구비하는 것을 특징으로 하는 가두리 해삼 양식장치.격자형태로 배열되어 다수의 생육공간을 형성하며 부력을 제공하는 다수의 부구와;상기 부구를 연결하는 파이프와; 상기 부구의 배열된 방향으로 연장되며 상기 부구에 설치되는 발판과;상기 파이프 또는 상기 발판에 설치되어 상기 생육공간에 수면 아래로 펼쳐저 해양생물을 가두는 다수의 가두리망과;상기 가두리 망내에 수용되며, 수상에 부유하는 가두리 양식장의 가두리망 내에 수용 가능하게 형성되며 각 면이 개방된 내부공간을 갖는 프레임과, 상방으로 개방된 내부공간이 각각 형성되되 폭과 높이가 다른 다수의 쉘터부가 방사상 및 상하방향으로 상호 이격되게 중첩되어 상기 프레임의 중심측에서 외측 방향으로 구획된 다수의 해삼생장공간을 형성하는 쉘터유닛과, 다수의 상기 쉘터부가 상기 프레임 내에서 상호 방사 방향 및 상하방향으로 이격되게 다수의 상기 쉘터부를 위치되게 고정하는 선형부재;를 구비하는 가두리 해삼 양식장치;를 구비하고,상기 가두리 해삼 양식장치는수온이 기준 온도보다 높게 상승되면 수저면에 인접하게 위치되게 설치되며 수온이 기준온도보다 낮은 경우에는 수상에 인접하게 위치되게 상기 가두리망 내에 설치되며, 상기 가두리망은 수온 상승 시 상기 가두리양식장용 다수의 상기 쉘터부가 수저면에 인접하게 설치될 수 있도록 다수의 상기 쉘터부의 높이보다 길고 하부가 수저면에 인접하게 상하방향으로 길이 연장형성되는 것을 특징으로 하는 가두리양식장., Ltext: 어업, prediction: 어업
379/1059 Row 379: application_number: 1020190090707, combined_string: invention_title: 부력변동형 가두리 양식장치 abstract: 본 발명은 부력변동형 가두리 양식장치에 관한 것으로서, 수중에 구비되는 가두리 구조체와, 수면에 부상하여 상기 가두리 구조체와 연결되는 고정부표와, 상기 가두리 구조체의 상측 중앙에 설치되고 외부에서 에어를 공급받아 부력을 발생시킴으로써 상기 가두리 구조체를 부상시키거나 에어를 배기하여 물을 흡입함으로써 상기 가두리 구조체를 침강시키는 메인부력체와, 상기 가두리 구조체의 바닥 중심에 고정되어 상기 가두리 구조체의 무게중심을 잡아주는 센터링고정추와, 상기 메인부력체와 센터링고정추를 연결하는 연결수단을 포함하여 이루어지는 부력변동형 가두리 양식장치에 있어서, 상기 가두리 구조체의 상단 가장자리에는 상기 메인부력체의 요동을 최소화하기 위하여 상기 메인부력체를 향하면서 상기 메인부력체에 근접하도록 설치되는 수평밸런싱수단이 구비되어, 상기 가두리 구조체가 침하 또는 부상시 일측으로 기울어지지 않고 수평 밸런스를 유지하게 하는 것을 특징으로 한다. claims: 수중에 구비되는 가두리 구조체와, 수면에 부상하여 상기 가두리 구조체와 연결되는 고정부표와, 상기 가두리 구조체의 상측 중앙에 설치되고 외부에서 에어를 공급받아 부력을 발생시킴으로써 상기 가두리 구조체를 부상시키거나 에어를 배기하여 물을 흡입함으로써 상기 가두리 구조체를 침강시키는 메인부력체와, 상기 가두리 구조체의 바닥 중심에 고정되어 상기 가두리 구조체의 무게중심을 잡아주는 센터링고정추와, 상기 메인부력체와 센터링고정추를 연결하는 연결수단을 포함하여 이루어지는 부력변동형 가두리 양식장치에 있어서,상기 가두리 구조체의 상단 가장자리에는 상기 메인부력체의 기울어짐을 최소화하기 위하여 상기 메인부력체를 향하면서 상기 메인부력체에 근접하도록 설치되는 수평밸런싱수단이 구비되어,상기 가두리 구조체가 침하 또는 부상시 일측으로 기울어지지 않고 수평 밸런스를 유지하게 하는 것을 특징으로 하는 부력변동형 가두리 양식장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

380/1059 Row 380: application_number: 1020190090838, combined_string: invention_title: 에너지절감을 위한 저전력 고효율의 양식장 abstract: 양식장이 개시된다. 양식장은 내부에 온수 또는 냉수를 저장하도록 구성되는 물저장부; 내부에 물을 저장하도록 구성되며, 또한 물 속에서 살수 있는 생물체를 수용하도록 구성되는 수조부; 물이 순환하기 위한 코일이 마련되며, 상기 물저장부와 배관으로 연결되어 상기 물저장부로부터 공급된 물이 상기 양식장 내부를 순환되도록 구성되는 물순환부; 상기 양식장에서 배출되는 배기의 공기열을 회수하여 상기 물저장부에 저장된 물의 온도를 상승시키도록 구성되는 공기열회수부; 상기 물저장부에 저장된 물이 상기 물순환부 또는 상기 수조부로 전달되도록 구성되는 펌프부; 및 상기 물 저장부에서 물이 상기 물순환부로 또는 상기 수조부로 전달되도록 상기 펌프부의 동작을 제어하도록 구성되는 제어부를 포함한다. 본 발명에 따르면 전력을 사용하여 물의 온도를 높이이거나 낮추는 보일러와 칠러가 사용되지 않거나 사융개수가 줄어듬으로써 오랜 기간 양식장을 가동하더라도 소모비용의 부담이 덜어진다. claims: 양식장에 있어서,내부에 온수 또는 냉수를 저장하도록 구성되는 물저장부;내부에 물을 저장하도록 구성되며, 또한 물 속에서 살수 있는 생물체를 수용하도록 구성되는 수조부;물이 순환하기 위한 코일이 마련되며, 상기 물저장부와 배관으로 연결되어 상기 물저장부로부터 공급된 물이 상기 양식장 내부를 순환되도록 구성되는 물순환부;상기 양식장에서 배출되는 배기의 공기열을 회수하여 상기 물저장부에 저장된 물의 온도를 상승시키도록 구성되는 공기열회수부;상기 물저장부에 저장된 물이 상기 물순환부 또는 상기 수조부로 전달되도록 구성되는 펌프부; 및상기 물저장부에서 물이 상기 물순환부로 또는 상기 수조부로 전달되도록 상기 펌프부의 동작을 제어하도록 구성되는 제어부를 포함하는 양식장., Ltext: 어업, prediction: 임업
381/1059 Row 381: application_number: 1020210079993, combined_string: invention_title: 모듈형 다품종 식물 재배를 위한 농장 시스템 및 그 방법 abstract: 본 발명의 일 실시예에 따른 모듈형 다품종 식물 재배를 위한 농장 시스템은, 재배될 식물이 수용되는 재배함, 재배함이 놓여지는 다층의 재배 데스크, 식물의 재배함으로 광을 제공하기 위한 광 제공부, 재배 데스크가 위치한 공간의 온도 및 습도를 유지하기 위한 항온항습부, 식물로 양액을 공급하기 위한 양액공급부, 시스템의 동작을 제어하기 위한 제어부 및 식물의 재배와 관련된 정보가 수집되고 처리되는 서버가 포함되고, 서버는 네트워크를 통하여 타 디바이스와 연결되어 연동 가능하고, 재배함에 수용된 다품종의 식물에 따라 미리 설정된 광이 광 제공부를 통하여 식물로 제공되며, 제어부에서는 재배함별로 통신을 통하여 재배함 내의 식물의 생장 상태정보를 체크하고, 광 제공부, 항온항습부 및 양액공급부 중 적어도 하나를 동작시킬 수 있다. claims: 모듈형 다품종 식물 재배를 위한 농장 시스템으로서, 재배될 식물이 수용되는 복수의 재배함;상기 복수의 재배함이 놓여지는 다층의 재배 데스크;상기 복수의 재배함 중 대응하는 재배함의 상측에 각각 배치되는 복수의 광 제공부;상기 재배 데스크가 위치한 공간의 온도 및 습도를 유지하기 위한 항온항습부;양액을 수용하는 양액탱크, 상기 양액탱크와 연결되고 상기 복수의 재배함 각각에 대응하는 복수의 양액펌프, 상기 복수의 양액펌프에 연결되는 복수의 양액수로관, 및 상기 복수의 양액수로관의 단부에 연결되고 상기 복수의 재배함 각각의 내부에 위치하는 양액노즐을 포함하는 양액공급부;상기 시스템의 동작을 제어하기 위한 제어부; 및상기 복수의 재배함 각각에 대응하는 복수의 서브 제어 모듈을 포함하고,상기 복수의 서브 제어 모듈은, 방수의 함체 내부에 수용되어, 대응하는 재배함에 인접 배치되고,적어도 일부가 데이지 체인 구조로 연결되어 상기 제어부와 신호를 송수신하고, 식물의 생장 상태정보에 기초하여 상기 제어부로부터 수신되는 제어 신호에 기초하여, 인접 배치된 재배함에 대응하는 광 제공부 및 양액펌프의 동작을 제어하고,상기 제어부는,상기 식물의 생장 상태정보에 기초하여 상기 항온항습부의 동작을 제어하는,모듈형 다품종 식물 재배를 위한 농장 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

382/1059 Row 382: application_number: 1020210040846, combined_string: invention_title: 간헐적 양액공급방식을 이용한 수경재배장치 abstract: 본 발명은 양액을 이용한 수경재배장치에 관한 것으로, 양액을 간헐적으로 공급되도록 하여 식물의 뿌리가 주기적으로 소정의 시간동안에 공기 중에 노출되도록 하되, 양액의 소비를 줄일 수 있도록 하고, 다양한 식물을 재배할 수 있도록 하고, 양액 공급에 따른 에너지 소비를 최소화 하는 등의 장점을 가질 수 있도록 이루어진 간헐적 양액공급방식을 이용한 수경재배장치이다.이러한, 본 발명의 간헐적 양액공급방식을 이용한 수경재배장치는 양액을 간헐적으로 공급하도록 이루어진 간헐식 수경재배장치에 있어서, 수경재배용 재배베드의 상부에 설치되도록 양측에 재배베드의 상부단과 결합되는 결합부가 형성되고, 재배식물에 따라 베드밑면의 높이를 조절할 수 있는 높이조절형 재배베드덮개와; 상기 수경재배용 재배베드에 공급되는 양액이 설정된 고수위에 도달시 하측에 위치한 다른 수경재배용 재배베드로 설정된 저수위까지 배출하도록 이루어진 양액배출장치를 포함하여, 가장 상부에 위치하는 수경재배용 재배베드에 양액을 간헐적으로 공급하여 하측에 위치하는 다른 수경재배용 재배베드에 순차적으로 양액이 간헐적으로 공급되도록 이루어진 것이다. claims: 양액을 간헐적으로 공급하도록 이루어진 간헐식 수경재배장치에 있어서,소정의 간격을 가지고 다단의 형태로 배치되는 가터(Gutter)형의 수경재배용 재배베드(20, 20')와; 상기 수경재배용 재배베드(20, 20')의 상부에 설치되며 베드밑면(31)의 위치를 조절할 수 있도록 이루어진 높이조절형 재배베드덮개(30)와; 상기 높이조절형 재배베드덮개(30)의 베드밑면(31)에 형성된 다수의 홀더 공(33)에 삽입되어 설치되는 다수의 재배홀더(50)와; 상기 수경재배용 재배베드(20)에 공급되는 양액이 설정된 고수위에 도달시 하측에 위치한 다른 수경재배용 재배베드(20')로 설정된 저수위까지 배출하도록 이루어진 양액배출장치(60)와; 양액탱크(80)에 저장된 양액을 가장 상부에 위치하는 수경재배용 재배베드(20)에 공급하는 양액공급장치(70)와; 상기 양액공급장치(70)의 제어를 포함하는 제어장치(100)를 포함하여,상기 양액공급장치(70)로 가장 상부에 위치하는 수경재배용 재배베드(20)에 양액을 간헐적으로 공급하여 하측에 위치하는 다른 수경재배용 재배베드(20')에 순차적으로 양액이 간헐적으로 공급되도록 이루어지는 한편,상기 높이조절형 재배베드덮개(30)는 단면이 '┎┑' 형태로 형성되고 양측부분에 수경재배용 재배베드(20, 20')의 상부단(22)과 결합되는 결합부(32)가 형성되고, 상기 결합부(32)는 상측과 하측에는 각각 대응되게 상부단(22)이 삽입되는 상측 결합홈(32-1)과 하측 결합홈(32-2)로 형성되어 있어 상기 상부단(22)에 결합되는 상측 결합홈(32-1)과 하측 결합홈(32-2)에 따라 베드밑면(31)의 위치가 조절됨을 특징으로 하는 간헐적 양액공급방식을 이용한 수경재배장치., Ltext: 농업, prediction: 임업
383/1059 Row 383: application_number: 1020210040849, combined_string: invention_title: 간헐적 수경재배장치 및 이를 구비한 간헐적 양액공급방식을 이용한 수경재배시스템 abstract: 본 발명은 양액을 이용한 수경재배장치에 관한 것으로, 양액을 간헐적으로 공급되도록 하여 식물의 뿌리가 주기적으로 소정의 시간동안에 공기 중에 노출되도록 하되, 양액의 소비를 줄일 수 있도록 하고, 다양한 식물을 재배할 수 있도록 하고, 양액 공급에 따른 에너지 소비를 최소화 하는 등의 장점을 가질 수 있도록 이루어진 간헐적 양액공급방식을 이용한 수경재배장치이다.이러한, 본 발명의 간헐적 양액공급방식을 이용한 수경재배장치는 양액을 간헐적으로 공급하도록 이루어진 간헐식 수경재배장치에 있어서, 수경재배용 재배베드의 상부에 설치되도록 양측에 재배베드의 상부단과 결합되는 결합부가 형성되고, 재배식물에 따라 베드밑면의 높이를 조절할 수 있는 높이조절형 재배베드덮개와; 상기 수경재배용 재배베드에 공급되는 양액이 설정된 고수위에 도달시 하측에 위치한 다른 수경재배용 재배베드로 설정된 저수위까지 배출하도록 이루어진 양액배출장치를 포함하여, 가장 상부에 위치하는 수경재배용 재배베드에 양액을 간헐적으로 공급하여 하측에 위치하는 다른 수경재배용 재배베드에 순차적으로 양액이 간헐적으로 공급되도록 이루어진 것이다. claims: 양액을 이용하여 식물을 재배하는 수경재배장치에 있어서,가터(Gutter)형의 수경재배용 재배베드(20)와; 상기 수경재배용 재배베드(20)의 상측에 설치되되 베드밑면(31)의 위치가 변경될 수 있도록 이루어진 높이조절형 재배베드덮개(30)와; 상기 높이조절형 재배베드덮개(30)에 형성된 재배판용 홀(33)에 설치되는 다양한 형태의 홀더 공(41, 41', 41)을 제공하도록 하는 재배판(40, 40', 40)과; 상기 재배판(40, 40', 40)에 형성된 홀더 공(41, 41', 41)에 설치되는 재배홀더(50, 50', 50)와; 상기 수경재배용 재배베드(20)에 공급되는 양액이 설정된 고수위에 도달시 하측에 위치한 다른 수경재배용 재배베드로 설정된 저수위까지 배출하도록 이루어진 양액배출장치(60)를 포함하고,상기 높이조절형 재배베드덮개(30)는, 단면이 '┎┑' 형태로 형성되고 양측부분에 상기 수경재배용 재배베드(20)의 상부단(22)과 결합되는 결합부(32)가 형성되고, 상기 결합부(32)는 상측과 하측에는 각각 대응되게 상부단(22)이 삽입되는 상측 결합홈(32-1)과 하측 결합홈(32-2)로 형성되어 있어 상기 상부단(22)에 결합되는 상측 결합홈(32-1)과 하측 결합홈(32-2)에 따라 베드밑면(31)의 위치가 조절되도록 하며,상기 수경재배용 재배베드(20)를 다단으로 설치하여 가장 상부에 위치하는 수경재배용 재배베드(20)에 양액을 고수위까지 공급시 하측에 위치하는 다른 수경재배용 재배베드에 순차적으로 양액이 공급될 수 있도록 함을 특징으로 하는 간헐적 수경재배장치.제1항 또는 제2항으로 이루어진 간헐적 수경재배장치와,상기 간헐적 수경재배장치가 다단으로 설치할 수 있는 재배베드용 프레임(10)과;양액탱크(80)에 저장된 양액을 가장 상부에 위치하는 간헐적 수경재배장치에 공급하는 양액공급장치(70)와;상기 양액배출장치(60)와 양액공급장치(70)를 제어할 수 있는 제어장치(100)를 포함하여,상기 양액공급장치(70)를 이용하여 가장 상부에 위치하는 간헐적 수경재배장치에 양액을 간헐적으로 공급하고, 공급된 양액이 하측에 위치하는 다른 간헐적 수경재배장치에 순차적으로 이동하여 양액이 간헐적으로 공급되도록 이루어짐을 특징으로 하는 간헐적 수경재배장치를 구비한 간헐적 양액공급방식을 이용한 수경재배시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

384/1059 Row 384: application_number: 1020210025496, combined_string: invention_title: 수경 재배 포트 abstract: 본 실시예들은 수경 재배 포트에 관한 것이다. 수경 재배 포트는 액체를 유통시키는 본체부, 본체부의 위에 위치하고, 제 1 홀을 포함하는 덮개부; 및 덮개부에 포함된 제 1 홀의 아래에 위치하는 필터를 결합하는 필터 결합부를 포함할 수 있다. claims: 황토, 폴리프로필렌(polypropylene) 및 송진을 포함하는 물질로 형성되는 수경 재배 포트로서,액체를 유통시키는 본체부;상기 본체부의 위에 위치하고, 제 1 홀을 포함하는 덮개부; 및상기 덮개부에 포함된 제 1 홀의 아래에 위치하는 필터를 결합하는 필터 결합부를 포함하되,상기 필터 결합부는,상기 덮개부의 아래에 위치하는 필터 결합부의 상부;상기 필터 결합부의 상부로부터 일정 간격 이격된 필터 결합부의 하부;상기 필터 결합부의 상부와 상기 필터 결합부의 하부 사이에 위치하는 필터 결합부의 측부;상기 필터 결합부의 상부, 상기 필터 결합부의 측부 및 상기 필터 결합부의 하부를 관통하는 제 4 홀; 및 상기 필터 결합부의 측부와 상기 제 4 홀을 연결하는 적어도 하나의 제 5 홀을 포함하고,상기 제 5 홀은,필터 결합부의 측부 일부분과 제 4 홀 일부분을 수평 방향으로 관통하여 형성된 관통홀이고, 상기 필터 결합부의 상부에서 상기 필터 결합부의 하부까지 연장되어 형성되며,상기 필터 결합부의 측부는, 테이퍼 형상이고,상기 황토, 폴리프로필렌 및 송진은, 수분이 없는 상태에서 혼합되며,상기 황토는 80 중량%이고, 상기 폴리프로필렌은 15 중량%이며, 상기 송진은 5 중량%인 수경 재배 포트., Ltext: 농업, prediction: 농업
385/1059 Row 385: application_number: 2020210000600, combined_string: invention_title: 자동급수, 회전식 공중 식물재배장치 abstract: 자동급수, 회전형 공중식물재배장치에 관한 것으로 두개의 기둥에 톱니바퀴를 설치하고 이에 연결된 체인에 다수의 지지봉을 달고 이에 재배상자를 매달아서 회전재배하며 하단에 물 및 양액을 공급하는 통을 설치하여서 회전시 양액통을 통과하여서 양액을 의 낭비를 방지하고 필요한 온도,이산화탄소 농도,생육에 유익한 연풍효과등을 유발하게 하며 좁은 면적에 많은 재배를 하게하는 장치이다. claims: 자동 급수,회전형 공중 식물재배장치로서 재배용기는 공중에 메달려 모터의 구동으로 체인이 움직이고 이 체인을 연결한 봉에 재배상자가 매달려 재배하는 것과 회전 시 급수 통을 통과하여 양액이 자동으로 공급되는 것., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

386/1059 Row 386: application_number: 1020210007302, combined_string: invention_title: 식물 수경재배 시스템 abstract: 본 발명은 식물 수경재배 시스템에 관한 것으로, 컨테이너 하우징; 상기 컨테이너 하우징의 내부에 배치되되, 가로방향, 세로방향 및 높이방향으로 배치되어 상호 연결되는 복수 개의 프레임들에 의해 식물을 재배할 수 있는 하나 또는 복수 개의 재배영역을 형성하는 재배 랙 유닛; 상기 재배 랙 유닛의 길이방향을 따라 연속적으로 배치되도록 복수 개 구비되며, 상기 재배 랙 유닛에 인입되어 상기 재배영역에 배치되거나 상기 재배 랙 유닛에서 인출할 수 있는 팔레트 유닛; 상기 팔레트 유닛에 배치되며, 상기 식물이 성장할 수 있는 공간이 형성된 식물 성장 파우치; 상기 재배 랙 유닛의 일측 또는 타측에 구비되어 상기 팔레트 유닛과 연결되며, 상기 팔레트 유닛으로 물을 공급하여 상기 팔레트의 온도를 조절하는 팔레트 온도조절 유닛; 및 상기 재배 랙 유닛의 일측 또는 타측에 구비되어 상기 팔레트 유닛의 상측에서 상기 팔레트 유닛에 배치된 상기 식물 성장 파우치로 양액을 공급하는 양액 공급 유닛을 포함한다. claims: 컨테이너 하우징;상기 컨테이너 하우징의 내부에 배치되되, 가로방향, 세로방향 및 높이방향으로 배치되어 상호 연결되는 복수 개의 프레임들에 의해 식물을 재배할 수 있는 하나 또는 복수 개의 재배영역을 형성하는 재배 랙 유닛;상기 재배 랙 유닛의 길이방향을 따라 연속적으로 배치되도록 복수 개 구비되며, 상기 재배 랙 유닛에 인입되어 상기 재배영역에 배치되거나 상기 재배 랙 유닛에서 인출할 수 있는 팔레트 유닛;상기 팔레트 유닛에 배치되며, 상기 식물이 성장할 수 있는 공간이 형성된 식물 성장 파우치;상기 재배 랙 유닛의 일측 또는 타측에 구비되어 상기 팔레트 유닛과 연결되며, 상기 팔레트 유닛으로 물을 공급하여 상기 팔레트의 온도를 조절하는 팔레트 온도조절 유닛; 및상기 재배 랙 유닛의 일측 또는 타측에 구비되어 상기 팔레트 유닛의 상측에서 상기 팔레트 유닛에 배치된 상기 식물 성장 파우치로 양액을 공급하는 양액 공급 유닛을 포함하되,상기 재배 랙 유닛은, 상기 재배 랙 유닛의 길이방향을 따라 상기 재배영역을 관통하며 배치되는 레일 프레임과, 상기 레일 프레임 상에 설정 간격 이격되게 설치되어 상기 팔레트 유닛이 상기 재배 랙 유닛의 길이방향을 따라 왕복 슬라이딩 이동할 수 있게 하는 복수 개의 롤러를 포함하고; 상기 팔레트 유닛은, 평면의 플레이트 형태이며, 상기 식물 성장 파우치가 배치될 수 있도록 가로방향 및 세로방향을 따라 설정 간격만큼 이격되는 복수 개의 홀들이 형성된 배치 플레이트와, 상기 배치 플레이트의 상면 또는 하면에 구비되며, 상기 팔레트 유닛으로 공급되는 상기 양액 또는 물을 흡수하여 저장하는 방수 패브릭과, 상기 배치 플레이트의 가로방향 및 세로방향을 따라 배치되어 상기 배치 플레이트를 둘러싸며 상기 배치 플레이트와 연결되는 다수 개의 팔레트 프레임과, 상기 배치 플레이트의 가로방향을 따라 배치되는 상기 팔레트 프레임의 내부에 구비되며, 상기 팔레트 유닛이 설정 온도 범위를 유지할 수 있도록 상기 팔레트 온도조절 유닛에서 공급되는 물이 유동되는 유로 파이프 및, 상기 배치 플레이트의 세로방향을 따라 배치되는 상기 팔레트 프레임에 하나 또는 복수 개 구비되며, 상기 재배 랙 유닛의 길이방향을 따라 연속적으로 상기 팔레트 유닛이 배치될 때 이웃하는 팔레트 유닛들을 서로 연결시키는 자성부재를 포함하며;상기 식물 성장 파우치는, 물 또는 양액을 흡수할 수 있는 소재로 이루어지고, 일측은 차폐되고 타측은 개방되어 있으며, 상기 식물 또는 상기 식물의 씨앗이 저장될 수 있도록 공간을 형성하고 상기 배치 플레이트에 형성된 홀에 삽입되는 식물 저장부와, 상기 식물 저장부의 타측으로부터 연장되어 상기 식물 성장 파우치가 상기 팔레트 유닛에 배치될 때 상기 식물 저장부를 지지하는 날개부를 포함하는 것을 특징으로 하는 식물 수경재배 시스템., Ltext: 농업, prediction: 임업
387/1059 Row 387: application_number: 1020200165414, combined_string: invention_title: 수중 재배 및 토양 재배가 가능한 스마트 식물 재배기 abstract: 본 발명에 따르면, 수경재배가 가능하도록 물을 저장할 수 있는 수조를 포함하는 수경재배부 및 토경재배가 가능하도록 내부에 토사를 적재할 수 있는 수용공간을 포함하는 토경재배부를 포함하는 재배부, 재배 작물이 생장할 수 있도록 재배부 일측에 배치되어 재배부 내 재배중인 작물의 광합성에 필요한 광을 조사하는 조명부, 재배부 내 재배중인 식물의 생장에 필요한 수분을 공급하는 토출부, 재배부 내부의 온도, 습도 및 토지의 양분 등을 측정할 수 있는 센서부, 센서부에 의해 측정된 정보를 사용자에게 알릴 수 있도록 측정 정보를 표시하는 디스플레이부, 재배부 내부의 공기를 순환시키는 순환팬 및 스마트 식물 재배기에 필요한 전력을 공급하는 전력부를 포함하는 수경 재배 및 토경 재배가 가능한 스마트 식물 재배기를 제공한다. claims: 수경재배가 가능하도록 물을 저장할 수 있는 수조를 포함하는 수경재배부 및 토경재배가 가능하도록 내부에 토사를 적재할 수 있는 수용공간을 포함하는 토경재배부를 포함하는 재배부; 재배 작물이 생장할 수 있도록 상기 재배부 일측에 배치되어 상기 재배부 내 재배중인 작물의 광합성에 필요한 광을 조사하는 조명부; 상기 재배부 내 재배중인 식물의 생장에 필요한 수분을 공급하는 토출부; 상기 재배부 내부의 온도, 습도 및 토지의 양분을 측정할 수 있는 센서부; 상기 센서부에 의해 측정된 정보를 사용자에게 알릴 수 있도록 측정 정보를 표시하는 디스플레이부;상기 재배부 내부의 공기를 순환시키는 순환팬; 및 스마트 식물 재배기에 필요한 전력을 공급하는 전력부;를 포함하며, 상기 조명부는 재배중인 식물의 종류에 따라 상기 재배부에 조사되는 광량을 조절할 수 있는 광(光)조절부 ; 및 재배중인 식물의 종류에 따라 상기 재배부에 공급되는 수량을 조절할 수 있는 수(水)조절부를 포함하고상기 광조절부 또는 상기 수조절부는유체가 통과할 수 있도록 제1천공홈, 상기 제1천공홈보다 큰 직경을 가지는 제2천공홈 및 상기 제2천공홈보다 큰 직경을 가지는 제3천공홈을 포함하는 천공홈; 및 상기 천공홈 일측에 배치되어 상기 천공홈을 선택적으로 개폐할 수 있도록 패널형상으로 형성되는 개폐부재 를 포함하는 것을 특징으로 하는 수경 재배 및 토경 재배가 가능한 스마트 식물 재배기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

388/1059 Row 388: application_number: 1020200162171, combined_string: invention_title: 생육 주기 확인을 통한 스마트팜 양액 제어 시스템 abstract: 본 발명은 생육 주기 확인을 통한 스마트팜 양액 제어 시스템에 관한 것이다. 보다 구체적으로는, 양액을 수용하여 식물을 재배하는 재배수조(20); 원수를 공급받아 저장하는 원수조(12); 상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14); 상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15); 상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16); 상기 재배수조(20)내의 식물의 영상을 획득하는 영상 촬영 장치(23); 및 상기 획득된 영상을 기반으로 상기 LED 조명(21)을 제어하는 조명 제어부(33)를 포함한다. claims: 양액을 수용하여 식물을 재배하는 재배수조(20);원수를 공급받아 저장하는 원수조(12);상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14);상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15);상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);상기 재배수조(20)내의 식물의 영상을 획득하는 영상 촬영 장치(23); 및상기 획득된 영상을 기반으로 상기 LED 조명(21)을 제어하는 조명 제어부(33)를 포함하는 생육 주기 확인을 통한 스마트팜 양액 제어 시스템., Ltext: 농업, prediction: 농업
389/1059 Row 389: application_number: 1020200162931, combined_string: invention_title: 셀레늄 함유 백화고의 재배 방법 abstract: 본 발명은 셀레늄 함유 백화고의 재배 방법에 관한 것이고, 구체적으로 재배 과정에서 셀레늄을 흡수하여 백화고 고유의 맛과 셀레늄의 효능이 유지되도록 하는 셀레늄 함유 백화고의 재배 방법에 관한 것이다. 셀레늄 함유 백화고의 재배 방법은 버섯 종균의 접종을 위한 원료를 배합하여 배지를 형성하는 단계; 배지를 멸균하고 접종을 하는 단계; 종균을 배양시키면서 균사의 성장에 따라 배지에 적어도 하나의 구멍을 형성하는 단계; 배지를 가습시키면서 수직 방향의 층에 따라 서로 다른 온도 조건을 설정하는 단계; 및 배지의 포장을 제거하여 습도를 조절하면서 생육시켜 수확하는 단계를 포함한다. claims: 버섯 종균의 접종을 위한 원료를 배합하여 배지를 형성하는 단계; 배지를 멸균하고 접종을 하는 단계; 종균을 배양시키면서 균사의 성장에 따라 배지에 적어도 하나의 구멍을 형성하는 단계; 배지를 가습시키기 위해 배지가 물에 감긴 상태에서 수직 방향의 층에 따라 서로 다른 온도 조건을 설정하는 단계; 및 배지의 포장을 제거하여 습도를 조절하면서 생육시켜 수확하는 단계를 포함하고, 배지는 10 내지 30 wt%의 밀기울; 0.1 내지 15 wt%의 목화씨 껍질; 1 내지 5 wt%의 석고; 10 내지 5000 ppm의 셀레늄 복합체; 및 전체를 100 wt%로 만드는 톱밥 형태의 잡목 부스러기를 포함하고, 가습은 배지 위쪽으로 수면이 형성되도록 하면서 서로 다른 층을 형성하는 위층의 온도가 아래층에 비하여 높은 온도로 유지되는 것을 특징으로 하는 셀레늄 함유 백화고의 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

390/1059 Row 390: application_number: 1020200156367, combined_string: invention_title: 식물 재배 전용 대형 수경 재배 박스 abstract: 본 발명에 따른 식물 재배 전용 대형 수경 재배 박스는 전면과 후면에 출입구가 형성되고, 실내에 식물을 재배하기 위한 재배실과, 상기 재배실의 온도와 습도를 조정하고 상기 재배실로 공급되는 급수량과 광량을 조정하는 제어 장치가 설치된 제어실이 갖추어진 메인 박스와; 상기 재배실 내부 좌우측에 중앙 복도를 사이에 끼고 복층으로 세워지되 각층에는 식물 재배판이 올려지는 복층 선반; 상기 제어실 내부에 설치된 물탱크; 상기 물탱크에 채워진 양액 또는 물을 상기 재배실 내부에서 재배되고 있는 식물로 공급하는 물 공급 수단; 상기 제어실 내부에 설치되되 상기 물 공급 수단을 통해 상기 식물로 공급되는 급수량을 제어하는 급수량 제어 수단; 상기 재배실안으로 수분 미스트를 살포하는 수분 미스트 공급 수단; 상기 수분 미스트 공급 수단을 제어하여 재배실 내 습도를 조정하는 습도 조정 수단; 상기 재배실 천장과, 상기 복층 선반에 구성된 각층 선반 밑면에 설치되어 식물 재배판에 설치된 식물로 빛을 공급하는 빛 공급 수단; 상기 빛 공급 수단을 제어하여 상기 식물에 공급되는 광량을 조절하는 광량 조정 수단; 상기 재배실 내부의 온도를 조정하는 온도 조정 수단; 및 상기 제어실 내부에 설치되되 상기 온도 조정 수단을 제어하여 상기 재배실 내부의 온도를 조정하는 온도 제어 수단을 포함한다. claims: 전면과 후면에 출입구(D)가 형성되고, 실내에 식물을 재배하기 위한 재배실(GR)과, 상기 재배실(GR)의 온도와 습도를 조정하고 상기 재배실(GR)로 공급되는 급수량과 광량을 조정하는 제어 장치가 설치된 제어실(CR)이 갖추어진 메인 박스(1)와;상기 재배실(GR) 내부 좌우측에 중앙 복도를 사이에 끼고 복층으로 세워지되 각층에는 식물 재배판(GP)이 올려지는 복층 선반(2);상기 제어실(CR) 내부에 설치된 물탱크(3);상기 물탱크(3)에 채워진 양액 또는 물을 상기 재배실(GR) 내부에서 재배되고 있는 식물로 공급하는 물 공급 수단(4); 상기 제어실(CR) 내부에 설치되되 상기 물 공급 수단(4)을 통해 상기 식물로 공급되는 급수량을 제어하는 급수량 제어 수단(5);상기 재배실(GR)안으로 수분 미스트를 살포하는 수분 미스트 공급 수단(6);상기 수분 미스트 공급 수단(6)을 제어하여 재배실(GR) 내 습도를 조정하는 습도 조정 수단(7); 상기 재배실(GR) 천장과, 상기 복층 선반(2)에 구성된 각층 선반(21) 밑면에 설치되어 식물 재배판(GP)에 설치된 식물로 빛을 공급하는 빛 공급 수단(8);상기 빛 공급 수단(8)을 제어하여 상기 식물에 공급되는 광량을 조절하는 광량 조정 수단(9);상기 재배실(GR) 내부의 온도를 조정하는 온도 조정 수단(T1);및 상기 제어실(CR) 내부에 설치되되 상기 온도 조정 수단(T1)을 제어하여 상기 재배실(GR) 내부의 온도를 조정하는 온도 제어 수단(T2)을 포함하며,상기 물 공급 수단(4)은 양수기(51)를 통해 물탱크(3)에 채워진 양액 또는 물을 공급받는 물 공급 메인 배관(41)과, 상기 복층 선반(2)을 구성하는 각층 선반(21)에 각각 설치되고 상기 물 공급 메인 배관(41)으로부터 분기 설치되어 상기 물 공급 메인 배관(41)으로부터 전달된 양액 또는 물을 전달받는 물 공급 분기 배관(42), 상기 물 공급 분기 배관(42)의 측부 둘레면에 형성되어 물 공급 분기 배관(42)을 통해 전달된 양액 또는 물을 상기 물 공급 분기 배관(42) 바깥으로 내보내는 물 배출구(43), 및 상기 물 배출구(43)에 1 대 1로 설치되어 상기 물 배출구(43)의 통로를 개방하거나 폐쇄하여 상기 물 배출구(43)를 통해 양액 또는 물이 배출되도록 하거나 배출되지 않도록 하는 물 공급 밸브(44)를 포함하고,상기 물 공급 분기 배관(42)은 상기 식물 재배판(GP)안으로 물이나 양액을 전달하는 하부 물 공급 분기 배관과, 상기 식물 재배판(GP) 상부에서 상기 식물 재배판(GP)에서 재배되고 있는 식물로 물이나 양액을 공급하는 상부 물 공급 분기 배관을 포함하며,상기 급수량 제어 수단(5)은 상기 물탱크(3)에 채워진 양액 또는 물을 퍼올려 토출구를 통해 상기 물 공급 메인 배관(41)으로 전달하는 양수기(51)와;상기 물 공급 분기 배관(42)의 입구에 각각 설치되어 중앙 급수 제어반(54)의 제어 신호에 따라 상기 물 공급 분기 배관(42)의 입구를 개방하거나 폐쇄하여 상기 물 공급 메인 배관(41)을 통해 전달된 양액 또는 물을 물 공급 분기 배관(42)으로 전달하거나 차단하는 솔레노이드 밸브(52);상기 양수기(51)가 작동되는 시간 간격과 양수기(51) 구동시 양수기(51)가 구동되는 시간을 설정하는 타이머(53)(Timer);및 상기 타이머(53)에 설정된 시간 간격으로 일정 시간동안 양수기(51)를 구동시키고 각각의 물 공급 분기 배관(42)에 설치된 솔레노이드 밸브(52)를 선택적으로 개폐하는 중앙 급수 제어반(54)을 포함하는 것을 특징으로 하는 식물 재배 전용 대형 수경 재배 박스., Ltext: 농업, prediction: 농업
391/1059 Row 391: application_number: 1020200137536, combined_string: invention_title: 복합 제어 스마트팜 시스템 abstract: 본 발명은 복합 제어 스마트팜 시스템에 관한 것이다. 본 발명에 따른 복합 제어 스마트팜 시스템은 스마트팜 운영에 필요한 장치 및 센서로 구성되며, 장치 구역 및 센서 구역으로 독립적으로 분리되는 MCU 클라이언트 및 MCU 클라이언트에 대한 통합 관리를 수행하는 웹 서버를 포함한다. claims: 스마트팜 운영에 필요한 장치 및 센서로 구성되며, 장치 구역 및 센서 구역으로 독립적으로 분리되는 MCU 클라이언트; 및상기 MCU 클라이언트에 대한 통합 관리를 수행하는 웹 서버를 포함하고, 상기 장치 구역으로는 동일한 장치 제어 기능을 수행하지만 장치 장애 극복 시에만 작동하는 구역이 등록되어, 해당 MCU 보드는 평상시 대기 상태의 명령을 받다가 1차 장비에 장애가 발생 시, 2차 장비를 구동시키고,상기 MCU 클라이언트는 상기 장치 구역의 경우, 상기 웹 서버로 농장 ID, 농장 앱키, 장치 구역 ID, 맥 어드레스를 포함하는 장치 구역 정보 요청을 전송하고, 상기 웹 서버로부터 장치 구동에 필요한 장치 ID, 장치 타입, 작동값, 개폐량, 증감치를 포함한 장치 구역 정보 응답을 수신하면 상기 장치 구역 정보 응답을 필터링하여 장치 개수를 판정하고, 장치 ID 일치 여부 확인에 따라 장치 타입 별로 기설정된 스펙에 따라 구동을 수행하고, 농장 ID, 농장 앱키, 장치 구역 ID, 장치 ID, 작동 결과값을 포함하는 상태 정보를 상기 웹 서버의 객체관계형 데이터베이스로 전송하여 업데이트하고,상기 웹 서버는 제1 장비를 제1 시간 이내에 완전 개방시키는 제1 구동 액추에이터와, 제2 장비를 상기 제1 시간보다 긴 시간인 제2 시간 이내에 완전 개방시키는 제2 구동 액추에이터의 구동 여부를 결정함에 있어서, 상기 제1 구동 액추에이터 및 제2 구동 액추에이터의 장비 구동에 관한 능력 정보를 고려하여, 상기 MCU 클라이언트로 목표 완수를 위한 명령 신호를 전송하여 상기 능력 정보가 상대적으로 높은 상기 제1 구동 액추에이터를 구동시키고, 예비적으로 상기 제2 구동 액추에이터를 대기시키며, 상기 제1 구동 액추에이터의 구동 시점으로부터 기설정 시간이 지난 시점에서의 기설정된 목표 달성 추이를 확인하여, 목표 달성 추이가 원만한 것으로 확인하면 상기 제1 구동 액추에이터의 구동을 유지시키고, 상기 제2 구동 액추에이터의 대기를 유지하며, 목표 달성 추이가 원만하지 않은 것으로 확인하면 상기 제1 구동 액추에이터의 구동을 유지시키고, 상기 제2 구동 액추에이터를 구동시키며,상기 웹 서버는 기준 환경값과의 허용되는 차이값인 여유값의 적용 여부에 따라 작동 조건의 만족 여부를 확인한 결과에 따라 장치의 작동 및 대기를 결정하되, 상기 여유값의 적용 여부가 선택되지 않은 경우 상기 기준 환경값을 고려하여 상기 작동 조건의 만족 여부를 확인하는 것인 복합 제어 스마트팜 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

392/1059 Row 392: application_number: 1020200128258, combined_string: invention_title: 푸른곰팡이 발생 저감형 버섯 양압재배사 abstract: 본 발명은 푸른곰팡이 발생 저감형 버섯 양압재배사에 관한 것으로, 보다 상세하게는 내부 환경을 제어하여 푸른곰팡이의 발생을 억제함으로써 버섯의 재배가 용이한 푸른곰팡이 발생 저감형 버섯 양압재배사에 관한 것이다.본 발명의 푸른곰팡이 발생 저감형 버섯 양압재배사는, 냉각수조 및 난방수조가 설치되는 준비실과 재배대가 설치되는 재배실로 구획되는 본체; 상기 재배실 바닥에 설치되고, 상기 냉각수조에 저장되어 있는 냉수에 의해 냉각되는 냉풍 또는 상기 난방수조에 저장되어 있는 온수에 의해 가열된 온풍이 토출되어 상기 재배실의 온도를 조절하는 송풍관; 상기 재배실에 설치되어 상기 재배실 내부공기가 외부로 배출되는 배기구; 상기 배기구에 설치되어 상기 재배실로 외부공기가 유입되는 것을 차단하는 체크밸브; 상기 재배실의 양측 벽면에 설치되고, 상기 재배실 상부 공기를 흡입하여 상기 재배실 하부로 배출시키는 씨형(C-type) 순환장치; 상기 재배실의 습도를 조절하는 복수의 습도조절장치; 상기 재배실 상부에 설치되는 유브이램프를 포함하여 이루어지고, 상기 재배실 내부는 압력 10Pa이상, 온도 20~30℃, 습도 70~90%RH로 유지되는 것을 특징으로 한다. claims: 냉각수조 및 난방수조가 설치되는 준비실과 재배대가 설치되는 재배실로 구획되는 본체;상기 재배실 바닥에 설치되고, 상기 냉각수조에 저장되어 있는 냉수에 의해 냉각되는 냉풍 및 상기 난방수조에 저장되어 있는 온수에 의해 가열된 온풍이 선택적으로 토출되어 상기 재배실의 온도를 조절하는 송풍관;상기 재배실에 설치되어 상기 재배실 내부공기가 외부로 배출되는 배기구;상기 배기구에 설치되어 상기 재배실로 외부공기가 유입되는 것을 차단하는 체크밸브;상기 재배실의 양측 벽면에 설치되고, 상기 재배실 상부 공기를 흡입하여 상기 재배실 하부로 배출시키는 씨형(C-type) 순환장치; 상기 재배실의 습도를 조절하는 복수의 습도조절장치; 및상기 재배실 상부에 설치되는 유브이램프를 포함하며,상기 준비실과 상기 재배실 사이에는 출입을 위한 도어가 설치되어 있고,상기 재배실의 내부는 압력 10Pa이상, 온도 20~30℃, 습도 70~90%RH로 유지되는 것을 특징으로 하는 푸른곰팡이 발생 저감형 버섯 양압재배사., Ltext: 농업, prediction: 임업
393/1059 Row 393: application_number: 1020200123708, combined_string: invention_title: 심지를 이용한 관상용 수경식물 재배 키트 abstract: 본 발명은 관상 식물을 수경재배 방식으로 키울 수 있는 수경식물 재배 키트에 관한 것이다. 본 발명은 흡수심지와 흡수원판을 사용하여 흡수성 섬유에 삽입된 씨앗으로 충분한 물이 공급될 수 있는 조건 및 씨앗의 안정적인 고정상태를 유지할 수 있는 구조 개선등을 하였고, 다공성 인공토을 사용하여 건습 및 다습에 상관없이 씨앗의 발아 및 식물이 성장하는데 최적의 환경을 만들어줄 수 있는 새로운 식물 재배 키트를 구현함으로써, 초보자도 쉽고 간편하게 식물을 건강하게 재배할 수 있다. claims: 식물재배부로 물을 공급하는 물공급부(120)와 식물을 지탱하고 생장할 수 있도록 하는 식물 재배부(110)로 구성되며,식물 재배부(110)와 탈부착이 가능하도록 고정틀(115)이 부착되어 있는 물저장부(140)식물 재배부(110)는 상부에서 하부로 갈수록 넓어지는 구조;식물 재배부(110)의 내부에 삽입되어 씨앗에 물을 공급하는 물공급부(120)와 다공성 인공토(130);물공급부(120)의 일부로서, 아크릴섬유 또는 합성섬유 등의 재질을 압축 성형한 것으로 일부분이 식물 재배부(110)의 하부로 노출되어 수분을 흡수하는 천 재질의 흡수심지(121);식물 재배부(110)의 내부에 삽입된 물공급부(120)의 일부로서, 아크릴섬유 또는 합성섬유 등의 재질을 압축 성형한 것으로 흡수심지(121)에 연결된 납작한 원판의 형태의 흡수원판(122);을 포함하는 심지를 이용한 관상용 수경식물 재배 키트, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

394/1059 Row 394: application_number: 1020200120453, combined_string: invention_title: 수경 재배 블록 abstract: 본 발명은 수생 식물을 생육할 수 있는 수경 재배 블록에 관한 것이다. 본 발명에 따른 수경 재배 블록은 바닥판 및 상기 바닥판과 수직하게 형성되며 개구가 형성된 복수의 측면판을 포함하여 내부에 수납 공간이 형성되는 블록 몸체, 블록 몸체의 내부 공간에 바닥판과 수직하게 형성되며, 바닥판을 관통하여 형성되는 복수의 홀을 수용하여, 블록 몸체에 오버플로우된 유체를 복수의 홀로 균등하게 배출하도록 하는 오버플로우 격벽을 포함한다. claims: 바닥판 및 상기 바닥판과 수직하게 형성되며 개구가 형성된 복수의 측면판을 포함하여 내부에 수납 공간이 형성되는 블록 몸체;상기 블록 몸체의 내부 공간에 상기 바닥판과 수직하게 형성되며, 상기 바닥판을 관통하여 형성되는 복수의 홀을 수용하여, 상기 블록 몸체에 오버플로우된 유체를 상기 복수의 홀로 균등하게 배출하도록 하는 오버플로우 격벽; 을 포함하고,상기 바닥판의 하부면에는 상기 복수의 홀로부터 연장되는 중공이 형성되고, 하부로 각각 돌출되어 형성되는 복수의 분배관이 형성되고,상기 복수의 분배관에 결합되어 적어도 하나의 다른 수경 재배 블록에 오버플로우된 유체를 분배하는 배관;을 포함하는 것을 특징으로 하는 수경 재배 블록., Ltext: 농업, prediction: 임업
395/1059 Row 395: application_number: 1020200120454, combined_string: invention_title: 수경 재배 장치 abstract: 본 발명은 수생 식물을 생육할 수 있는 수경 재배 장치에 관한 것이다. 본 발명에 따른 수경 재배 장치는 바닥판 및 상기 바닥판과 수직하게 형성되며 개구가 형성된 복수의 측면판을 포함하여 내부에 수납 공간이 형성되는 적어도 하나의 블록 몸체, 블록 몸체로부터 오버플로우된 유체를 공급받아 저장하고, 최상부에 배치된 블록 몸체에 유체를 공급하는 수조, 블록 몸체의 하부에 결합되며, 수조가 배치될 공간을 형성하는 받침대를 포함한다. claims: 바닥판 및 상기 바닥판과 수직하게 형성되며 개구가 형성된 복수의 측면판을 포함하여 내부에 수납 공간이 형성되는 적어도 하나의 블록 몸체;상기 블록 몸체로부터 오버플로우된 유체를 공급받아 저장하고, 최상부에 배치된 블록 몸체에 유체를 공급하는 수조;상기 블록 몸체의 하부에 결합되며, 상기 수조가 배치될 공간을 형성하는 받침대; 를 포함하고,상기 블록 몸체는 하부면에 상기 받침대와 결합되는 결합부가 형성되고,상기 받침대는 상부면에 상기 결합부와 대응되는 형상으로 제1 결합홈과, 측면 및 저면에는 다른 받침대와의 결합을 위한 제2 결합홈 및 제3 결합홈이 형성되어 상기 블록 몸체에 결합되고,상기 제2 결합홈 또는 상기 제3 결합홈에 결합되어 서로 다른 받침대를 연결하는 연결구;를 포함하는 것을 특징으로 하는 수경 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

396/1059 Row 396: application_number: 1020200119701, combined_string: invention_title: 시설 운영 이력을 저장할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 스마트팜 운영 시스템은, 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서를 포함하고 상기 환경정보를 포함하는 경작지정보를 생성하는 센서박스; 경작자가 상기 경작지정보를 기반으로 상기 재배환경을 조절하기위해 상기 시설장비를 작동시키는 제어정보를 포함하는 경작정보를 입력하는 경작자 단말기; 상기 제어정보를 기반으로 상기 시설장비를 작동시키는 제어박스; 및, 상기 경작지정보 및 상기 경작정보를 상기 작물의 생육단계에 매칭하여 저장하는 저장부를 가지는 정보서버;를 포함한다. claims: 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서를 포함하고 상기 환경정보를 포함하는 경작지정보를 생성하는 센서박스;경작자가 상기 경작지정보를 기반으로 상기 재배환경을 조절하기위해 상기 시설장비를 작동시키는 제어정보를 포함하는 경작정보를 입력하는 경작자 단말기;상기 제어정보를 기반으로 상기 시설장비를 작동시키는 제어박스; 및,상기 경작지정보 및 상기 경작정보를 상기 작물의 생육단계에 매칭하여 저장하는 저장부를 가지는 정보서버;를 포함하는 시설 운영 이력을 저장할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: 임업
397/1059 Row 397: application_number: 1020200119716, combined_string: invention_title: 재배 이력을 추적할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 재배 이력을 추적할 수 있는 스마트팜 운영 시스템은, 작목이 재배되고 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 감지하여 환경정보를 생성하는 환경센서를 포함하는 센서부; 상기 환경정보를 기반으로 상기 시설장비를 작동시키는 제어정보와 상기 작목의 재배정보 및 상기 경작자의 이력정보를 포함하는 경작자정보를 상기 경작자가 입력하는 경작자 단말기; 상기 환경정보와 상기 제어정보와 상기 재배정보 및 상기 경작자정보를 수신하여 생산이력정보로 저장하는 저장부를 가지고 클라우드(cloud) 컴퓨팅을 기반으로 운영되는 정보서버; 상기 작목에서 재배된 농산품을 판매하는 판매처; 및 상기 농산품의 생산이력정보를 상기 정보서버로부터 수신하여 구매자에게 표시하는 구매자 단말기;를 포함한다. claims: 작목이 재배되고 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 감지하여 환경정보를 생성하는 환경센서를 포함하는 센서부;상기 환경정보를 기반으로 상기 시설장비를 작동시키는 제어정보와 상기 작목의 재배정보 및 상기 경작자의 이력정보를 포함하는 경작자정보를 상기 경작자가 입력하는 경작자 단말기;상기 환경정보와 상기 제어정보와 상기 재배정보 및 상기 경작자정보를 수신하여 생산이력정보로 저장하는 저장부를 가지고 클라우드(cloud) 컴퓨팅을 기반으로 운영되는 정보서버;상기 작목에서 재배된 농산품을 판매하는 판매처; 및 상기 농산품의 생산이력정보를 상기 정보서버로부터 수신하여 구매자에게 표시하는 구매자 단말기;를 포함하는 재배 이력을 추적할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

398/1059 Row 398: application_number: 1020200119103, combined_string: invention_title: 다년생 수삼 수경재배장치 abstract: 본 발명은 3~5년생의 다년생 수삼(뿌리)을 묘삼으로 하고, 이를 양액을 사용하여 다량의 유용한 성분을 함유하고 있는 줄기와 잎사귀 키워낼 수 있도록 하기 위한 다년생 수삼 수경재배장치에 관한 것이다.이러한 본 발명인 다년생 수삼 수경재배장치는 소정의 거리로 이동하여 작업자의 이동통로(R)를 변경할 수 있도록 하측에 수조용 프레임 이동수단이 구비된 다수의 수경수조용 프레임과; 상기 수경수조용 프레임에 소정의 간격으로 설치되는 다수의 수삼재배용 수조와, 상기 수삼재배용 수조 상측에 설치되어 다년생 수삼이 재식되는 슬라이더형 수삼재배판과, 상기 수삼재배용 수조 내에 구비되어 재식된 수삼의 뿌리에 양액을 분사하는 양액분사장치를 포함하되, 상기 슬라이더형 수삼재배판이 수삼재배용 수조의 일측으로 슬라이드하여 일부분이 배출될 수 있도록 이루어진 수삼 수경재배용 수조장치와; 상기 양액분사장치에서 양액이 분사될 수 있도록 소정의 압력으로 양액을 공급하도록 이루어진 양액공급장치와; 상기 수삼 수경재배용 수조장치에 재직된 수삼의 성장에 보조역할을 하는 성장보조장치와; 상기 양액공급장치와 성장보조장치를 제어할 수 있는 제어장치를 포함하도록 이루어진다. claims: 소정의 거리로 이동하여 작업자의 이동통로(R)를 변경할 수 있도록 하측에 수조용 프레임 이동수단(120)이 구비된 다수의 수경수조용 프레임(100)과; 상기 수경수조용 프레임(100)에 소정의 간격으로 설치되는 다수의 수삼재배용 수조(240)와, 상기 수삼재배용 수조(240) 상측에 설치되어 다년생 수삼이 재식되는 슬라이더형 수삼재배판(220)과, 상기 수삼재배용 수조(240) 내에 구비되어 재식된 수삼의 뿌리에 양액을 분사하는 양액분사장치(250)를 포함하되, 상기 슬라이더형 수삼재배판(220)이 수삼재배용 수조(240)의 일측으로 슬라이드하여 일부분이 배출될 수 있도록 이루어진 수삼 수경재배용 수조장치(200)와; 상기 양액분사장치(250)에서 양액이 분사될 수 있도록 소정의 압력으로 양액을 공급하도록 이루어진 양액공급장치(300)와; 상기 수삼 수경재배용 수조장치(200)에 재직된 수삼의 성장에 보조역할을 하는 성장보조장치(400)와; 상기 양액공급장치(300)와 성장보조장치(400)를 제어할 수 있는 제어장치(500)를 포함하는 한편,상기 수삼 수경재배용 수조장치(200)는,다년생 수삼(G)을 고정할 수 있는 수삼홀더장치(210)와; 상기 수삼홀더장치에 각각 고정된 다수의 수삼을 소정의 간격을 유지할 수 있도록 다수의 수삼용 재식홀(221a)이 형성된 슬라이더형 수삼재배판(220)과; 상기 슬라이더형 수삼재배판의 양측부분을 이동할 수 있게 지지하도록 이루어진 수삼재배판용 가이드대(230)와; 상기 수삼재배판용 가이드대가 소정의 간격으로 상측에 구비되며, 일측으로 수삼재배판용 가이드대(230)를 따라 이동하는 슬라이더형 수삼재배판의 일부분이 외측으로 출입할 수 있도록 출입용 개구부(241)가 일측면에 형성되어 있는 수삼재배용 수조(240)와; 상기 수삼재배용 수조 내에 위치하여 양액을 분사하여 수삼에 양액을 공급하도록 이루어진 양액분사장치(250)와; 상기 슬라이더형 수삼재배판(220)의 일부분이 출입할 수 있도록 형성된 출입용 개구부(241)를 덮는 한편, 감시창 기능을 하는 측면 덮개판(260)을 포함함을 특징으로 하는 다년생 수삼 수경재배장치., Ltext: 농업, prediction: 임업
399/1059 Row 399: application_number: 1020200119108, combined_string: invention_title: 수경재배용 이산화탄소 공급장치를 구비하는 다년생 수삼 수경재배장치 abstract: 본 발명은 수경재배가 이루어지는 수경재배실 내에 수경재배시 이산화탄소(CO2) 농도가 낮아짐으로써 발생하는 문제점을 해결하고자 적절한 이산화탄소(CO2) 농도가 유지될 수 있도록 이산화탄소(CO2)를 공급할 수 있도록 이루어진 수경재배용 이산화탄소 공급장치 및 이를 구비하는 다년생 수삼 수경재배장치에 관한 것이다.이러한 본 발명인 수경재배용 이산화탄소 공급장치는 탄산솔을 수용할 수 있도록 내부공간을 가지는 외부몸체와; 상기 내부공간에 교체가능하도록 삽설되는 탄산솔을 저장하며, 열전도율이 높도록 금속재질로 이루어지며, 상부가 개구된 형태로 이루어진 탄산솔 저장용기와; 상기 탄산솔 저장용기의 하측부분을 감싸도록 이루어지며, 일측부분에 발열을 위한 발열장치가 형성되어 있는 탄산솔 저장용기 가열부재와; 상기 내부공간의 상부에 설치되어 탄산솔에 태양광을 대신하는 빛을 조사할 수 있도록 이루어진 탄산솔 조명장치를 포함하는 성장보조용 이산화탄소 공급장치로 이루어진다. claims: 수경재배실에 설치되는 다수의 수경수조용 프레임(100)과;상기 수경수조용 프레임(100)에 소정의 간격으로 설치되는 다수의 수삼재배용 수조(240)와, 상기 수삼재배용 수조(240) 상측에 설치되어 다년생 수삼이 재식되는 슬라이더형 수삼재배판(220)과, 상기 수삼재배용 수조(240) 내에 구비되어 재식된 수삼의 뿌리에 양액을 분사하는 양액분사장치(250)를 포함하되, 상기 슬라이더형 수삼재배판(220)이 수삼재배용 수조(240)의 일측으로 슬라이드하여 일부분이 배출될 수 있도록 이루어진 수삼 수경재배용 수조장치(200)와;상기 양액분사장치(250)에서 양액이 분사될 수 있도록 소정의 압력으로 양액을 공급하도록 이루어진 양액공급장치(300)와;상기 수삼 수경재배용 수조장치(200)에 재직된 수삼의 성장에 보조역할을 하는 성장보조장치(400)와;상기 양액공급장치(300)와 성장보조장치(400)를 제어할 수 있는 제어장치(500)를 포함하는 한편,상기 성장보조장치(400)는 탄산솔(422)을 수용할 수 있도록 내부공간(421a)을 가지는 외부몸체(421)와; 상기 내부공간(421a)에 교체가능하도록 삽설되는 탄산솔(422)을 저장하며, 열전도율이 높도록 금속재질로 이루어지며, 상부가 개구된 형태로 이루어진 탄산솔 저장용기(423)와; 상기 탄산솔 저장용기(423)의 하측부분을 감싸도록 이루어지며, 일측부분에 발열을 위한 발열장치(424a)가 형성되어 있는 탄산솔 저장용기 가열부재(424)와; 상기 내부공간(421a)의 상부에 설치되어 탄산솔(422)에 태양광을 대신하는 빛을 조사할 수 있도록 이루어진 탄산솔 조명장치(425)를 포함하는 성장보조용 이산화탄소 공급장치(420)로 이루어지는 수경재배용 이산화탄소 공급장치를 포함함을 특징으로 하는 수경재배용 이산화탄소 공급장치를 구비하는 다년생 수삼 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

400/1059 Row 400: application_number: 1020200095347, combined_string: invention_title: 식물 재배 장치 abstract: 본 발명은 식물 재배 장치에 관한 것으로, 전기 분사 모듈을 이용하여 양액을 미세 액적 상태로 분사 공급함으로써, 양액 입자의 크기가 매우 미세하고 이온화된 상태로 형성되어 배지에서 재배되는 식물의 뿌리에 대한 흡수량 및 흡수율이 증가하며, 양액 입자의 부유 시간이 증가하여 식물의 뿌리에 지속적으로 흡수되고 이에 따라 외부로 배출되어 버려지는 양을 최소화할 수 있어 더욱 효율적으로 사용 관리될 수 있고, 이온화된 미세 액적에 의한 살균 기능을 통해 메인 케이스 내부 공간에 대한 살균 기능을 수행하여 세균 번식을 억제하고 이끼 및 녹조 발생을 방지하며, 별도의 압력 분사 모듈을 추가하여 이들을 다양한 방식으로 작동 제어함으로써, 양액 공급 기능 및 살균 기능을 동시에 최적의 상태로 수행할 수 있는 식물 재배 장치를 제공한다. claims: 상부에 식물을 재배할 수 있는 배지가 고정 장착되는 메인 케이스;양액 저장 챔버로부터 양액을 공급받고, 공급받은 양액을 전위차에 의한 전기력을 이용하여 상기 메인 케이스의 내부 공간에 미세 액적 상태로 분사하는 전기 분사 모듈;상기 양액 저장 챔버로부터 양액을 공급받고, 공급받은 양액을 압력을 통해 상기 메인 케이스 내부 공간에 분사하는 압력 분사 모듈; 및상기 전기 분사 모듈 및 압력 분사 모듈의 작동 상태를 동작 제어하는 제어부를 포함하고, 상기 제어부는 상기 전기 분사 모듈이 제 1 주기마다 작동하도록 동작 제어하고, 상기 압력 분사 모듈은 상기 제 1 주기와는 다른 제 2 주기마다 작동하도록 동작 제어하며,사용자가 제 1 작동 모드, 제 2 작동 모드 및 제 3 작동 모드를 선택할 수 있도록 별도의 선택 조작부가 구비되고,상기 제 1 작동 모드가 선택된 경우, 상기 제어부에 의해 상기 제 1 주기가 상기 제 2 주기보다 더 길게 설정되고, 상기 제 2 작동 모드가 선택된 경우, 상기 제어부에 의해 상기 제 2 주기가 상기 제 1 주기보다 더 길게 설정되며,상기 제 3 작동 모드가 선택된 경우, 상기 제어부는 상기 제 3 작동 모드가 선택된 시간 동안 상기 전기 분사 모듈이 상기 제 1 주기마다 작동하고 상기 압력 분사 모듈은 작동 정지하도록 동작 제어하는 것을 특징으로 하는 식물 재배 장치., Ltext: 농업, prediction: 농업
401/1059 Row 401: application_number: 1020200085173, combined_string: invention_title: 에너지 절약 및 작물 발육 보조를 위한 수경재배용 설비 시스템 abstract: 본 발명은 작물을 토양없이 배양액을 이용하여 재배하는 수경재배시설에 관한 것으로, 상세하게는, 농가에서 수경재배농법을 이용한 수경재배시설을 통해 작물을 재배할 때 지하자원(수자원)의 고갈로 인한 자연환경의 파괴를 방지하고, 항온과 항습을 위해 소모되는 많은 전기 사용량으로 인한 농가의 경제적인 부담을 줄일 수 있는 에너지 절약 및 작물 발육 보조를 위한 수경재배용 설비 시스템에 관한 것이다. claims: 온실;상기 온실의 내부에 'ㄹ'자 형상으로 수평으로 번갈아가면서 설치되고, 작물이 생육되는 수평배관을 포함하는 수경재배설비;심정용 모터를 통해 수자원으로부터 끌어올려진 물을 집수하여 저장하고, 저장된 물을 메인배관을 통해 상기 수경재배설비의 수평배관으로 공급하는 집수용 물탱크;상기 수평배관의 종단부 배관에 길이 방향으로 복수 개로 배치되어 상기 수평배관의 종단부로 배수되는 물의 수력을 이용하여 전기를 생산하는 발전기;상기 발전기를 통한 전기 생산시 사용되고 남은 잉여수를 저장하는 보조 물탱크;상기 온실에 설치되고, 항습용 모터에 의해 상기 보조 물탱크로부터 끌어올려진 잉여수를 상기 수평배관에서 생육되는 작물을 포함하여 상기 온실의 내부로 분사하는 스프링 쿨러;상기 온실의 내부에 항온 유지용으로 설치된 복수 개의 라디에이터; 상기 라디에이터와 배관을 통해 연결되고, 상기 보조 물탱크에 저장된 잉여수를 공급받고, 상기 발전기에서 생산된 전기를 공급받아 가동하여 공급받은 잉여수를 가열한 후 상기 라디에이터로 공급하여 상기 온실의 항온을 유지하는 보일러; 및상기 온실의 바닥 지면에 매립 설치되어 상기 스프링 쿨러에서 분사된 물을 지면으로 배수하여 자연환원시키는 잡석;을 포함하고,상기 발전기는, 상기 수평배관의 종단부로 배수되는 물의 수력을 이용하여 전기를 생산하는 수차 발전기;상기 수차 발전기로부터 생산된 교류전압을 승압하는 승압기;상기 승압기로부터 승압된 교류전압을 직류전압으로 변환하는 컨버터;상기 컨버터에 의해 변환된 직류전압을 저장하는 축전지;상기 축전지의 직류전압을 교류전압으로 변환하는 인버터; 및 상기 승압기와 상기 인버터로부터 공급되는 교류전압 중 어느 하나를 선택하여 상기 보일러와 배선을 통해 전기적으로 접속된 분전반으로 공급하는 자동 절환 스위치;를 포함하는에너지 절약 및 작물 발육 보조를 위한 수경재배용 설비 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

402/1059 Row 402: application_number: 1020200071098, combined_string: invention_title: 타워형 수경재배장치 abstract: 본 발명은 하는 타워형 수경재배장치에 간한 것으로서, 베이스박스(11)의 상부측으로 연장된 다수의 기둥(12)에 지지되는 루프(13)를 가지는 타워케이스(10)와; 베이스박스(11)에 착탈 가능하게 지지되는 것으로서, 측부에 작물을 재배하기 위한 포트(P)가 끼어지는 다수의 포트홀(22)(22')(22)이 형성된 하나 이상의 재배타워(20)와; 베이스박스(11)에 내장되는 것으로서 재배타워(20)로 공급되는 물이 저장되는 물저장부(30)와; 루프(13)에 설치되어 상기 재배타워(20) 하부측으로 물을 분사하는 분사캡(40)과; 물저장부(30)의 물을 상기 분사캡(40)로 공급한 후 상기 재배타워(20)를 통하여 상기 물저장부(30)로 순환시키는 물순환공급부(50);를 포함하는 것을 특징으로 한다. claims: 베이스박스(11)의 모서리에서 상부측으로 연장된 4 개의 기둥(12)에 지지되는 루프(13)를 가지는 타워케이스(10);상기 4 개의 기둥(12) 내측에서 베이스박스(11)에 착탈 가능하게 지지되는 것으로서, 측부에 작물을 재배하기 위한 포트(P)가 끼어지는 다수의 포트홀(22)(22')(22)이 형성된 하나 이상의 재배타워(20);상기 4 개의 기둥(12) 각각에 지지되어 상기 재배타워(20)로 광을 입체적으로 조사하는 광조사부(70);상기 베이스박스(11)에 내장되는 것으로서 상기 재배타워(20)로 공급되는 물이 저장되는 물저장부(30);상기 루프(13)에 설치되어 상기 재배타워(20) 하부측으로 물을 분사하는 분사캡(40);상기 물저장부(30)의 물을 상기 분사캡(40)로 공급한 후 상기 재배타워(20)를 통하여 상기 물저장부(30)로 순환시키는 물순환공급부(50); 및 상기 재배타워(20)와 물저장부(30) 사이의 결합관(32)에 끼어져 결합되는 것으로서, 상기 재배타워(20)를 통하여 순환되는 물의 부패 및 오염을 방지하기 위하여 구리메쉬(61)(62), 모래층(63) 및 활성탄층(64)으로 이루어지는 필터부(60);를 포함하고;상기 기둥(12)은 L 형태의 단면 구조를 가지며 마주보는 내측면에 확산판끼움홈(12a)이 길게 형성되고;상기 광조사부(70)는, 상기 기둥(12)에 내측에 설치되는 것으로서 다수의 LED(71)가 일정한 간격으로 식립되는 PCB(72)와, 상기 다수의 LED(71)를 덮도록 상기 확산판끼움홈(12a)에 끼어져 결합되어 상기 LED(71)에서 조사되는 광을 확산하는 확산판(73)을 포함하는 것;을 특징으로 하는 타워형 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

403/1059 Row 403: application_number: 1020200071099, combined_string: invention_title: 베드형 수경재배장치 abstract: 본 발명은 베드형 수경재배장치에 관한 것으로서, 베이스박스(11)의 후방측에 지지된 측벽(12)을 가지는 케이스(10)와; 측벽(12)에 지지되는 것으로서, 상부측에 작물을 재배하기 위한 포트(P)가 끼어지는 다수의 포트홀이 형성된 제1,2재배선반(20)(20')과; 베이스박스(11)에 내장되는 것으로서 제1,2재배선반(20)(20')으로 공급되는 물이 저장되는 물저장부(30)와; 물저장부(30)에 저장된 물을 압송하기 위한 압송펌프(40)와; 제1,2재배선반(20)(20') 일측과 연결되는 것으로서 압송펌프(40)에서 압송되는 물이 유입되는 유입관부(50)와; 제1,2재배선반(20)(20') 타측과 물저장부(30)를 연결하는 것으로서 제1,2재배선반(20)(20')을 경유한 물을 상기 물저장부(30)로 배수시키는 배수관부(60);를 포함하는 것을 특징으로 한다. claims: 베이스박스(11)의 후방측에 지지된 측벽(12) 및 상기 측벽(12)의 상부측에 설치되는 루프(14)를 가지는 케이스(10);상기 측벽(12)에 지지되는 것으로서, 상부측에 작물을 재배하기 위한 포트(P)가 끼어지는 다수의 포트홀이 형성된 제1,2재배선반(20)(20');상기 베이스박스(11)에 내장되는 것으로서 상기 제1,2재배선반(20)(20')으로 공급되는 물이 저장되는 물저장부(30);상기 물저장부(30)에 저장된 물을 압송하기 위한 압송펌프(40);상기 제1,2재배선반(20)(20') 일측과 연결되는 것으로서 상기 압송펌프(40)에서 압송되는 물이 유입되는 유입관부(50);상기 제1,2재배선반(20)(20') 타측과 상기 물저장부(30)를 연결하는 것으로서 상기 제1,2재배선반(20)(20')을 경유한 물을 상기 물저장부(30)로 배수시키는 배수관부(60);상기 배수관부(60)와 물저장부(30) 사이에 설치되어 상기 제1,2재배선반(20)(20')을 경유한 물의 부패 및 오염을 방지하는 필터부(70); 및 상기 베이스박스(11)의 모서리측에 지지되어 상기 루프(14)까지 연장된 것으로서, 상기 제1,2재배선반(20)(20')으로 광을 입체적으로 조사하는 4 개의 광조사부(80)를 포함하고;상기 광조사부(80)는, 상기 베이스박스(11)에 모서리측에 지지되는 것으로서 단면이 L 형태이고 마주보는 내측면에 확산판끼움홈(81a)이 형성된 기둥(81)과, 상기 기둥(81)의 내측에 설치되는 것으로서 다수의 LED(82)가 일정한 간격으로 식립되는 PCB(83)와, 상기 다수의 LED(82)를 덮도록 상기 확산판끼움홈(81a)에 끼어지는 것으로서 상기 LED(82)에서 조사되는 광을 확산하는 확산판(84)을 포함하고;상기 물저장부(30)의 물탱크(31)의 상부측에 상기 물탱크(31) 내부와 연통되는 필터수납홈(31a)이 형성되고;상기 필터수납홈(31a)에는 상기 제1,2재배선반(20)(20')을 순환한 후 물저장부(30)로 순환 회수되는 물의 부패 및 오염을 방지하기 위하여 정화시키기 위한 필터부(70)가 착탈 가능하게 설치되고;상기 필터부(70)는 상기 필터수납홈(31a)에 착탈 가능하게 결합되는 것으로서 상부측으로 상기 배수관부(60)의 배수관헤드(63)가 결합되는 헤드결합공(71a)이 형성되고 하방측으로 배수공(71b)이 형성된 필터박스(71)와, 상기 필터박스(71) 내측에 배치되는 필터엘레먼트(72)를 포함하고;상기 필터엘레먼트(72)는, 상기 배수관부(60)를 통하여 순환되는 물의 부패 및 오염을 방지하기 위하여 제1,2구리메쉬(72a)(72b), 상기 제1,2구리메쉬(72a)(72b) 사이에 설치되는 모래층(72c) 및 활성탄층(72d)을 포함하는 것;을 특징으로 하는 베드형 수경재배.제1항에 있어서, 상기 물저장부(30)는, 상기 베이스박스(11)에 설치되는 물탱크(31)와, 상기 물탱크(31)에 저장된 물 온도를 측정하여 대응되는 온도신호(T)를 발생하는 온도센서(32)와,상기 물탱크(31)에 설치되어 물을 가온시키기 위한 히터(33)와, 상기 온도센서(32)에서 발생되는 온도신호(T)에 연동되어 상기 히터(33)의 작동을 제어하는 히터작동부(34)를 포함하는 것을 특징으로 하는 베드형 수경재배장치.제1항에 있어서, 상기 물저장부(30)로 비료성분을 공급하는 비료공급부(90)를 더 포함하는 것을 특징으로 하는 베드형 수경재배장치.제1항에 있어서, 상기 제1,2재배선반(20)(20')은,상기 측벽(12)에 고정된 제1,2선반브라켓(13)(13') 지지되는 것으로서 내부에 물이 수용되는 저수공간이 형성된 제1,2선반박스(21)(21')와, 상기 제1,2선반박스(21)(21')의 상부측에 덮여지는 것으로서 다수의 포트홀(22)(22')이 형성된 제1,2박스커버(23)(23')와,상기 제1,2선반박스(21)(21')의 일측에 형성되어 상기 유입관부(50)와 연결되는 제1,2유입공(24)(24')와, 상기 제1,2선반박스(21)(21')의 타측에 형성되어 배수관부(60)와 연결되는 제1,2배수공(25)(25')를 포함하는 것을 특징으로 하는 베드형 수경재배장치.제1항에 있어서, 상기 제1,2재배선반(120)(120')은,상호 이격되게 배치되는 제1,2,3파이프(121)(122)(123)와; 상기 제1,2,3파이프(121)(122)(123) 각각의 양단에 결합되는 것으로서 관통되는 구멍이 형성되는 제1,2,3캡(124)(125)(126)과;상기 제1,2,3파이프(121)(122)(123)가 지그재그로 연결될 수 있도록, 상기 제1,2,3파이프(121)(122)(123) 일측의 제1,2캡(124)(125)을 연결하는 제1연결관(127) 및 상기 제1,2,3파이프(121)(122)(123) 타측의 제2,3캡(125)(126)을 연결하는 제2연결관(128);를 포함하는 것을 특징으로 하는 베드형 수경재배장치., Ltext: 농업, prediction: 농업
404/1059 Row 404: application_number: 1020200063983, combined_string: invention_title: 투명 수조를 포함하는 작물 재배 장치 abstract: 투명 수조를 포함하는 작물 재배 장치가 개시된다. 개시된 투명 수조를 포함하는 작물 재배 장치는, 어류 서식을 위한 수조; 및 상기 수조 아래에 배치되며, 상기 수조로부터 각각 유입되는 물을 배양액으로 하여 작물을 재배하는 복수의 재배모듈;을 포함하되, 상기 복수의 재배모듈을 거친 물은 상기 수조로 재유입되어 어류 서식에 이용될 수 있다. claims: 어류 서식을 위한 수조; 및상기 수조 아래에 배치되며, 상기 수조로부터 각각 유입되는 물을 배양액으로 하여 작물을 재배하는 복수의 재배모듈;을 포함하되, 상기 복수의 재배모듈을 거친 물은 상기 수조로 재유입되어 어류 서식에 이용되고,상기 복수의 재배모듈은, 버티컬파밍 방식의 재배모듈, 에어로포닉 방식의 재배모듈, 포그포닉 방식의 재배모듈 및 하이드로포닉 방식의 재배모듈 중 2 이상을 포함하되,상기 복수의 재배모듈은,상기 수조 바로 아래에 나란히 배치되는 버티컬파밍 방식의 재배모듈과 에어로포닉 방식의 재배모듈을 포함하는 제1 재배모듈;상기 제1 재배모듈 바로 아래에 배치되는 포그포닉 방식의 제2 재배모듈;상기 제2 재배모듈 바로 아래에 배치되는 하이드로포닉 방식의 제3 재배모듈을 포함하고,상기 수조와 상기 제1 재배모듈을 연결하여 상기 수조로부터의 물을 상기 제1 재배모듈로 이송하는 제1 유출라인; 상기 수조와 상기 제2 재배모듈을 연결하여 상기 수조로부터의 물을 상기 제2 재배모듈로 이송하는 제2 유출라인;상기 수조와 상기 제3 재배모듈을 연결하여 상기 수조로부터의 물을 상기 제3 재배모듈로 이송하는 이송하는 제3 유출라인; 및 상기 제1 내지 제3 재배모듈들과 상기 수조를 연결하여 상기 제1 내지 제3 재배모듈로부터의 물을 상기 수조로 이송하는 순환라인;을 더 포함하고,상기 제3 재배모듈 바로 아래에 배치되는 순환부;를 더 포함하되, 상기 제1 유출라인은 길이 방향을 따라 일정 간격을 두고 복수의 홈이 형성되고, 상기 홈에 각각 작물이 거치되며, 상기 제1 유출라인 내에 배양액을 머금을 수 있는 부재가 구비되고,상기 순환라인은, 상기 버티컬파밍 방식의 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제1 순환라인;상기 에어로포닉 방식의 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제2 순환라인;상기 제2 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제3 순환라인;상기 제3 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제4 순환라인; 및상기 순환부와 상기 수조를 연결하여 이들간 물을 이송하는 제5 순환라인;을 포함하고,상기 순환부는, 상기 복수의 재배모듈을 거친 물을 상기 수조로 유입시키는 펌프;를 더 포함하며,상기 펌프는 상기 순환라인상에 배치되고,외부로부터 상기 순환부로 물을 유입받는 유입라인;을 더 포함하되,상기 펌프는 상기 유입라인으로부터 유입된 물을 상기 복수의 재배모듈을 거친 물과 함께 상기 수조로 유입시키며,상기 수조의 수위를 감지하는 감지부;를 더 포함하되, 상기 감지 결과 기준치를 미달하는 경우 상기 유입라인에 배치된 밸브의 개폐에 따라 상기 유입라인을 통해 외부로부터 물이 상기 순환부로 유입되는, 투명 수조를 포함하는 작물 재배 장치., Ltext: 농업, prediction: 임업

Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

405/1059 Row 405: application_number: 1020200063982, combined_string: invention_title: 복수의 재배모듈을 포함하는 작물 재배 장치 abstract: 복수의 재배모듈을 포함하는 작물 재배 장치가 개시된다. 개시된 작물 재배 장치는, 어류 서식을 위한 수조; 및 상기 수조 아래에 배치되며, 상기 수조로부터 유입되는 물을 배양액으로 하여 작물을 재배하는 복수의 재배모듈;을 포함하되, 상기 복수의 재배모듈을 거친 물은 상기 수조로 재유입되어 어류 서식에 이용될 수 있다. claims: 어류 서식을 위한 수조; 및상기 수조 아래에 배치되며, 상기 수조로부터 유입되는 물을 배양액으로 하여 작물을 재배하는 복수의 재배모듈;을 포함하되, 상기 복수의 재배모듈을 거친 물은 상기 수조로 재유입되어 어류 서식에 이용되고,상기 복수의 재배모듈은,상기 수조 바로 아래에 배치되는 제1 재배모듈, 상기 제1 재배모듈 바로 아래에 배치되는 제2 재배모듈, 및 상기 제2 재배모듈 바로 아래에 배치되는 제3 재배모듈을 포함하고,상기 제1 재배모듈은 버티컬파밍 방식의 재배모듈과 에어로포닉 방식의 재배모듈을 포함하되, 상기 버티컬파밍 방식의 재배모듈과 상기 에어로포닉 방식의 재배모듈은 서로 좌우측에 나란히 배치되고,상기 제2 재배모듈은 포그포닉 방식의 재배모듈이며,상기 제3 재배모듈은 하이드로포닉 방식의 재배모듈이고,상기 수조와, 상기 제1 재배모듈을 연결하여 이들간 물을 이송하는 제1 유출라인; 상기 제1 재배모듈과 상기 제2 재배모듈을 연결하여 이들간 물을 이송하는 제2 유출라인;상기 제2 재배모듈과 상기 제3 재배모듈을 연결하는 제3 유출라인;상기 제3 재배모듈과 상기 수조를 연결하여 이들간 물을 이송하는 순환라인;상기 제3 재배모듈 바로 아래에 배치되는 순환부;을 더 포함하고,상기 순환라인은, 상기 제3 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제1 순환라인;상기 순환부와 상기 수조를 연결하여 이들간 물을 이송하는 제2 순환라인;을 포함하며,상기 순환부는, 상기 복수의 재배모듈을 거친 물을 상기 수조로 유입시키는 펌프;를 더 포함하고,상기 제2 유출라인은, 상기 물이 흐를 수 있는 배관으로 구성되고, 상기 제2 유출라인 중 상기 제1 재배모듈과 연결되는 상기 배관의 유입구는, 상기 제1 재배모듈 내 채워져야할 상기 물의 수위를 고려하여 상기 제1 재배모듈의 바닥으로부터 기설정된 높이에 설치되며,외부로부터 상기 순환부로 물을 유입받는 유입라인;을 더 포함하되,상기 펌프는 상기 유입라인으로부터 유입된 물을 상기 복수의 재배모듈을 거친 물과 함께 상기 수조로 유입시키고,상기 수조의 수위를 감지하는 감지부;를 더 포함하되, 상기 감지 결과 기준치를 미달하는 경우 상기 유입라인에 배치된 밸브의 개폐에 따라 상기 유입라인을 통해 외부로부터 상기 순환부로 물이 유입되는, 복수의 재배모듈을 포함하는 작물 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

406/1059 Row 406: application_number: 1020200061185, combined_string: invention_title: 작물 생육정보 모니터링 시스템 abstract: 본발명은 작물을 생산하는 곳에서 작물의 이미지를 촬영하여 생육과정 정보를 모니터링하는 것으로, 로봇기구부(100), 로봇제어부(200), 전원공급부(300), 로봇레일부(400)를 포함하여 형성된 생육측정 주행로봇(1000)과; 싱글보드(500), 3D깊이카메라(600)와 디스플레이(700), 초소형PC(800)가 포함되어 구비되되, 상기 생육측정 주행로봇에 장착되어 자동으로 작물을 촬영하거나 또는 주행로봇에서 분리하여 농업인이 수동으로 작물을 촬영할 수 있도록 형성된 생육관리 싱글보드PC(2000)와; 생육측정 주행로봇(1000)과 농업인이 3D깊이카메라(600)로 촬영된 생육정보를 데이타베이스하는 생육관리PC(3000)를 포함하여 형성되어 전문지식이 없는 농업인이 간편하게 자동 또는 수동으로 간편하게 작물의 생육과정을 측정할 수 있는 현저한 효과가 있다. claims: 작물을 생산하는 곳에서 작물의 이미지를 촬영하여 생육과정 정보를 모니터링하는 것으로, 로봇기구부(100), 로봇제어부(200), 전원공급부(300), 로봇레일부(400)를 포함하여 형성된 생육측정 주행로봇(1000)과; 싱글보드(500), 3D깊이카메라(600), 디스플레이(700), 소형PC(800)가 포함되어 구비되되, 상기 생육측정 주행로봇(1000)에 장착되어 자동으로 작물을 촬영하거나 또는 주행로봇에서 분리하여 농업인이 수동으로 작물을 촬영할 수 있도록 형성된 생육관리 싱글보드PC(2000)와; 상기 생육측정 주행로봇(1000)과 농업인이 3D깊이카메라(600)로 촬영된 생육정보를 데이타베이스화하는 생육관리PC(3000)를 포함하여 형성되는 작물 생육정보 모니터링 시스템에 있어서,상기 로봇기구부(100) 하부에는 하부플랫폼(110)이 형성되고, 상기 하부플랫폼 하부에는 난방용 파이프를 레일로 이용해 이동하는 주행축(120)이 구비되며, 상부에는 상하이동축(130) 그리고 암회전축(140), 로봇의 암 역할을 하는 매니퓰레이터(150), 카메라회전축(160), 카메라 상하틸트축(170)이 순차적으로 연결되며,상기 생육측정 주행로봇(1000)은 로봇운용PC(230)로부터 원점복귀, 위치이동, 자율주행의 지령을 받아 해당 명령을 수행하면서 작물의 측정부위를 촬영을 하는 것이며,상기 로봇제어부(200)는 주위 환경상태를 감지하는 온습도센서, 마그넷센서, 라이다센서, CCTV가 구비된 감지부(210)와, 상기 감지부로 측정된 주위 환경상태에 따라 생육측정 대상작물로 생육측정 주행로봇(1000)이 이동하여 촬영하도록 제어하는 제어부(220)와, 생육측정 주행로봇의 운용을 계획하고 조정하는 로봇운용PC(230)로 구성되고 상기 제어부는 로봇이 메인(main)명령을 수행하게 제어하는 로봇메인제어, 설정치를 추종(servo)하게 제어되는 서보제어, 제어를 단계적(step)으로 하게 하는 스텝제어, 입출력(input, output)을 제어하는 I/O제어를 통하여 로봇동작을 제어하며,로봇운용PC(230)를 통하여 로봇기구부(100)에 이동명령을 주기 위해서 상기 로봇운용PC의 데이타베이스와 생육관리PC(3000) 사이에 데이타베이스를 송수신 가능하게 구비하여, 생육측정 주행로봇(1000)을 현장에 설치 후 이상 발생시 원격에서 컨트롤하고 원격제어하여 정상운행이 가능하게 하며,상기 생육측정 주행로봇(1000)의 자세와 위치 방향 및 주변환경을 모니터링하기 위한 CCTV를 로봇기구부(100)에 설치하여 원격모니터링하며, 로봇운용PC(230)에 스케쥴링시스템을 적용하여 로봇이 예약된 일자에 매일, 매주, 정해진 시간에 무인 자동 운행이 가능하게 구비하며, 또한 온실마다 온실의 폭, 높이가 차이가 나기 때문에 주행로봇 각축의 환경설정을 하여 각축의 이동반경 설정이 가능하게 하고 영상이미지명을 정하여 영상이미지만으로 농장, 온실, 온실동, 작물위치를 알 수 있게 하며,상기 로봇레일부(400)는 온실난방용 파이프를 레일로 사용하여 로봇기구부(100)가 이동되며, 로봇기구부(100)와 로봇제어부(200)의 구동 및 제어에 있어서 레일주행휠(121) 및 보조주행휠(122) 외에 보조휠(123)을 구비하여 라인이설 및 설치작업을 수동으로 조작이 가능하게 하며, 작물라인의 시작점 및 최종점 인식을 위한 근접센서 및 추돌예방을 위한 라이다센서가 형성되고, 또한 모터구동 제어기를 로봇제어부(200) 내에 구비하여 제어하며생육관리 싱글보드PC(2000)는 싱글보드(500)와, 영상을 촬영하는 3D깊이카메라(600)와; 화면을 터치하는 디스플레이와(700); 프로그램을 내장할 수 있는 소형PC(800)가 포함되어 형성되되, 상기 싱글보드(500) 일면 일정부위에는 3D깊이카메라가 형성되고, 타면에는 화면을 터치하여 촬영을 조정하는 디스플레이(700)가 형성되며, 또한 내부에는 PC(800)가 내장되되, 상기 생육측정 주행로봇(1000)의 매니퓰레이터(150)에 장착되어 자동으로 작물을 촬영하거나 또는 주행로봇에서 분리하여 농업인이 수동으로 작물을 촬영할 수 있게 하며, 또한 의복에 센서를 착용한 농업인이 수동으로 온실의 임의위치에서 작물을 촬영한 후 로봇이 촬영할 경우,로봇은 농업인이 촬영한 지점을 온실내의 GPS에 의한 위치인식기반시스템에 의해 인지하여 로봇이 정해진 위치외에도 농업인이 임의로 촬영한 지점도 중복 촬영하여 생육정보를 서로 비교분석할 수 있도록 하고, 또한 촬영한 시간에 의한 빛의 광량에 따라 비교시 차이가 있으므로 사진을 촬영할시의 시각과 나아가 온도도 측정하여 로봇제어부(200)는 기후 및 온도에 따라 사진의 색상을 보정하게 하며,상기 생육관리 싱글보드PC(2000)로 작물을 측정하는 방법은 로봇제어부(200)가 먼저 측정대상 작물의 유인줄 끝에 번호인식표를 붙이고 시각적으로 번호표를 인식하여 대상작물을 찾고 번호표를 좌표 중앙에 위치시킨후 수직으로 내려와 작물 시작점을 찾은 후, 작물의 시작점부터 배지까지 내려오면서 작물의 측정부위의 좌표를 자동설정하고, 설정된 좌표에 의해 생육측정 주행로봇(1000)이 자동 주행하면서 영상 촬영을 하는 것을 특징으로 하는 작물 생육정보 모니터링 시스템, Ltext: 농업, prediction: 농업
407/1059 Row 407: application_number: 1020200053600, combined_string: invention_title: 동식물 생태 순환형 아쿠아포닉스 시스템 abstract: 본 발명은 수생동물의 생육하는 수조의 물을 재배조에 순환 공급하여, 재배조의 식물이 수조의 물에 혼합된 유기물에서 영양을 섭취하여 수조의 물을 정확하게 하는 동식물 생태 순환형 아쿠아포닉스 시스템에 관한 것으로서, 보다 상세하게는 재배조를 수조의 상하에 다단으로 배치하여도 수조 물을 정량으로 연속 순화시키고, 재배조에서의 영양 섭취량을 최대한 늘리도록 각 재배조에 유로를 형성하고, 관상하기에 적합한 높이에 수조를 배치할 수 있고, 재배조를 인입 인출에 무관하게 순환 생태계를 연속적 및 안정적으로 유지하여, 협소한 공간에 많은 식물을 키울 수 있고, 가정용으로도 적합하며, 식생 관리도 편리하고, 수조의 물을 깨끗하게 유지할 수 있는 동식물 생태 순환형 아쿠아포닉스 시스템에 관한 것이다 claims: 복수 수납공간이 수직 방향으로 배열되어 있는 지지프레임(100); 복수 수납공간 중에 최상단 수납공간을 제외한 어느 하나의 수납공간에 수용되며, 물이 채워진 부분을 갖게 하여 수생동물의 생육 환경을 조성한 수조(200); 나머지 수납공간에 하나씩 수용되어 상하로 다단 배치되며, 바닥면보다는 상대적으로 높은 위치에 유입구(313) 및 배출구(314)를 구비하고 바닥면에 도출시킨 벽체(311)에 의해서 유입구(313)부터 배출구(314)까지 지그재그 형태의 유로(312)를 형성한 저수 상자(310)와, 벽체(311)에 걸쳐지며 유로(312)를 따라 포트홀(321)이 조성된 포트 거치판(320)과, 각 포토홀(321)에 삽입되며 식재한 식물 뿌리가 유로(312) 물에 잠기게 하는 포트(330)를 포함하게 구성되어서, 식물의 수경재배 환경을 조성한 재배조(300-1, 300-2, 300-3); 및 상기 수조(200)의 물을 워터펌프(410)로 취수하여 최상단 재배조(300-1)의 유입구(313)를 통해 공급하고, 최상단 재배조(300-1)에 공급한 물이 최하단 재배조(300-3)까지 순차적으로 흐르도록 배출구(314)와 유입구(313)를 통해 배관 연결되게 하고, 최하단 재배조(300-3)의 물을 배출구(314)를 통해 워터펌프로 취수하여 상기 수조(200)로 회수하되 상기 수조(200)에서의 취수 유량과 동일한 유량으로 회수하는 순환수단(400); 을 포함하되, 상기 워터펌프(410)는 전동 모터(411)와, 전동 모터(411)의 동력으로 회전하여 물을 동일 양수량으로 펌핑하는 2개 펌프(412, 413)로 구성되어, 상기 수조(200)의 물을 어느 하나의 펌프(412)로 취수하여 최상단 재배조(300-1)에 공급되게 하고, 최하단 재배조(300-3)의 물을 다른 하나의 펌프(413)로 취수하여 상기 수조(200)로 회수되게 하는 아쿠아포닉스 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

408/1059 Row 408: application_number: 1020200053266, combined_string: invention_title: 작물 재배 또는 육묘용 포트 어셈블리 abstract: 본 발명은 포트플레이트(60)의 포트(61)들 사이의 길이방향으로 뚫려져 연속하여 이어지는 어퍼홈라인(62)에 선형조립수단(70)을 끼워 포트플레이트(60)들을 연속하여 누르면서 일체화시킬 수 있도록 함으로써 바람에 의한 영향이나 작업자의 부딪힘에 의한 영향을 최소화시켜 포트플레이트(60)들을 견고하게 안정될 수 있도록 함과 동시에 작물 재배 완료 후 또는 작물 육묘 완료 후 포트플레이트(60)들을 적층시켜 보관하고자 밧줄로 묶고자 할 때 어퍼홈라인(62)을 경유시킬 수 있도록 함으로써 보관시 묶음처리 상태 역시 더욱 견고하게 실현케 할 수 있고, 특히, 선형조립수단(70)이 어퍼홈라인(62)에 끼워진 상태로 포트플레이트(60)들을 누를 수 있도록 하여 어퍼홈라인(62)으로부터 선형조립수단(70)의 분리현상을 극소화시켜 선형조립수단(70)의 무단이탈에 의한 작물로의 악영향(상처나 훼손)을 철저히 방지하고, 나아가 선형조립수단(70) 및 받침파이프(F1) 상호간의 양끝단의 직접적인 묶음처리로서 프레임(F)에서부터 포트플레이트(60)들에 이르기까지 일체화된 상태를 보장하여 보다 안정감 있게 작물을 재배 및 육묘할 수 있는 특유의 작용을 발휘하는 작물 재배 또는 육묘용 포트 어셈블리에 관한 발명이다. claims: 배수구멍(61a)이 뚫린 포트(61)들을 지니면서 직선상으로 연속하여 이웃하는 포트플레이트(60)들을 포함하는 작물 재배 또는 육묘용 포트 어셈블리에 있어서,상기 포트플레이트(60)들은 상기 포트(61)들 사이의 길이방향으로 뚫려져 연속하여 이어지는 어퍼홈라인(62)을 각각 구비하고,상기 어퍼홈라인(62)들을 따라 끼워져 상기 포트플레이트(60)들을 연속하여 누르면서 일체화시키는 선형조립수단(70)을 포함하고,상기 선형조립수단(70)은 누름파이프(71) 또는 로프(72)인 것을 특징으로 하는 작물 재배 또는 육묘용 포트 어셈블리., Ltext: 농업, prediction: 임업
409/1059 Row 409: application_number: 1020200044337, combined_string: invention_title: 식물 재배장치 abstract: 본 발명에 따른 식물 재배장치는 여러 개를 온실의 폭 방향으로 병렬로 배치하여 식물을 재배할 수 있으면서도 재배식물이 햇빛이나 외부조명을 골고루 받을 수 있도록 할 수 있다. 상기 식물 재배장치는 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임, 한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체, 한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되는 복수의 행거바 및 복수의 상기 행거바에 각각 매달린 복수의 식물재배용기를 포함하는 구성을 한다. claims: 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임;한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체; 및한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고,상기 프레임은 상기 순환지지구의 하부위치로 이동한 상기 행거바에 상기 식물재배용기가 매달린 상태에서 순환되는 것을 허용하는 높이 이상의 높이로 한 쌍의 상기 순환지지구를 지지하는 지지프레임을 가지는 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

410/1059 Row 410: application_number: 1020200043029, combined_string: invention_title: 수경재배용 배드 조립체 abstract: 본 발명은 길이 방향으로 연장 설치되어 강직도와 물높이를 균일하게 형성할 수 있도록 구현한 수경재배용 배드 조립체에 관한 것으로, 정식판이 안착되기 위한 배양액이 수용될 수 있도록 길이 방향으로 연결 형성되는 적어도 하나 이상의 연결부;를 포함한다. claims: 정식판이 안착되기 위한 배양액이 수용될 수 있도록 길이 방향으로 연결 형성되는 적어도 하나 이상의 연결부;상기 연결부의 전단에 연결 설치되는 제1 마감부; 및 상기 연결부의 후단에 연결 설치되는 제2 마감부;를 포함하며,상기 연결부는,사각 평판 형태로 형성되는 바닥면;내부 공간에 배양액을 수용할 수 있도록 상기 바닥면의 일측 및 다른 일측으로부터 상측 직각 방향으로 절곡되어 연장 형성되는 측면;상기 바닥면의 전단 상측에 형성되어 다른 연결부의 후단 하측에 체결되거나, 상기 제1 마감부의 후단 하측에 체결되는 전단 체결부; 및상기 바닥면의 후단 하측에 형성되어 다른 연결부의 전단 체결부에 체결되거나, 상기 제2 마감부의 전단 상측에 체결되는 후단 체결부;를 포함하며,상기 제1 마감부는,상기 전단 체결부에 체결될 수 있도록 상기 전단 체결부와 대향하는 후단 하측에 상기 후단 체결부와 동일할 형태의 체결 구조를 형성하며,상기 제2 마감부는,상기 후단 체결부에 체결될 수 있도록 상기 후단 체결부와 대향하는 후단 상측에 상기 전단 체결부와 동일할 형태의 체결 구조를 형성하며,상기 전단 체결부는,상기 바닥면의 전단 상측면을 따라 좌우 방향으로 하측으로 단차지도록 연장 형성되는 상부 안착턱;상기 상부 안착턱을 따라 좌우 방향으로 서로 이격되어 다수 개가 형성되는 상부 체결홈; 및상기 상부 체결홈과 다른 상부 체결홈 사이에 상측으로 둔턱 형태로 돌출 형성되는 상부 체결턱;을 포함하며,상기 상부 체결홈은,골과 이랑이 반복하여 형성되는 요철부; 및상기 요철부의 후단을 따라 좌우 방향으로 상기 요철부보다 하측으로 함몰되어 연장 형성되는 걸림부;를 포함하며,상기 후단 체결부는,다른 연결부의 전단 체결부에 안착되어 체결될 수 있도록 다른 연결부의 전단 체결부의 형태에 대응하는 형상으로 상기 바닥면의 후단 하측면이 형성되며, 상기 연결부는,일정한 간격으로 좌우 방향으로 서로 이격되어 다수 개가 형성되며, 상기 바닥면을 따라 전후 방향으로 연장 형성되는 유도홈;일정한 간격으로 전후 방향으로 서로 이격되어 다수 개가 형성되며, 상기 유도홈의 하측면을 통해 상측이 노출될 수 있도록 상측이 상기 유도홈의 하측면과 대향하는 깊이로 상기 바닥면을 좌우 수평 방향으로 관통하고 형성되는 수평 관통홈; 및사각 각관 형태로 형성되어 상기 수평 관통홈 마다 삽입되며, 상측면을 따라 절개홈이 좌우 수평 방향으로 연장 형성되어 상기 유도홈의 하측면을 통해 개방된 상기 수평 관통홈의 상측을 통해 외부 공기 공급 장치를 공해 공급되는 공기를 배출하는 공기 공급관;을 더 포함하며,상기 유도홈의 상측을 따라 다수 개가 설치되며, 상기 공기 공급관을 통해 배출되는 공기를 통해 구동되어 상기 유도홈을 따라 상기 연결부에 수용된 배양액이 흘러가도록 유속을 형성시키는 유속 형성부;를 더 포함하며,상기 유속 형성부는,상기 공기 공급관으로부터 후단으로 이격되어 상기 유도홈의 일측 및 다른 일측 벽체의 상측에서 쌍을 이루며 형성되는 두 개의 체결홈;상기 체결홈에 삽입 체결되는 두 개의 체결블록; 및상기 두 개의 체결블록 사이에 회전 가능하도록 연결 설치되며, 상기 유도홈에 수용되어 있는 배양액이 상기 유도홈을 따라 흐를 수 있도록 상기 공기 공급관을 통해 배출되는 공기를 통해 회전하면서 상기 유도홈에 수용되어 있는 배양액을 저어 주는 물레방아;를 포함하며,상기 제1 마감부 또는 상기 제2 마감부는,상기 유도홈으로부터 연장 형성되는 추가 유도홈; 및상기 유도홈으로부터 상기 추가 유도홈으로 흘러 유입되는 배양액을 상측 방향으로 승강시켜 줄 수 있도록 회전하는 승강 유도 물레방아;를 포함하는, 상기 공기 공급관으로부터 전단으로 이격되어 상기 유도홈의 일측 및 다른 일측 벽체에 각각 설치되며, 상기 물레방아가 회전함에 따라 발생되는 구동력을 이용하여 회전하여 상기 유속 형성부에 의해 상기 유도홈을 따라 흐르는 배양액의 유속을 증가시켜 주는 유속 가속부;를 더 포함하는, 수경재배용 배드 조립체., Ltext: 농업, prediction: 임업
411/1059 Row 411: application_number: 1020200025697, combined_string: invention_title: 새싹땅콩 수경재배 장치 abstract: 본 발명은 재배단계를 구분하여 각 단계마다 온도 및 양액 분사량을 최적 조건으로 조절하여 성장률과 품질을 향상시킬 수 있는 새싹땅콩 수경재배 방법 및 그 장치에 관한 것이다.개시된 수경재배장치는, 땅콩씨앗을 파종하여 재배실에 실장하기 위한 다수의 재배모판과, 상기 재배모판에 파종된 땅콩씨앗을 소정 재배조건으로 재배하기 위한 재배실을 제공하는 재배챔버와, 상기 재배챔버의 전면에 장착되어 재배챔버를 조작하고 동작상태를 표시하기 위한 프론트 패널과, 상기 재배실에 양액을 공급하기 위한 양액 공급부와, 상기 재배실의 공기 온도를 조절하기 위한 공기온도 조절부와, 상기 프론트 패널의 조작에 따라 상기 공기온도 조절부를 제어하여 재배실의 온도를 조절하고, 상기 양액 공급부를 제어하여 재배실에 양액을 미스트 분사방식으로 공급하며, 동작 상태를 상기 프론트 패널에 표시하기 위한 컨트롤러를 포함한다. claims: 땅콩씨앗을 파종하여 재배실에 실장하기 위한 다수의 재배모판;양 측벽과 후벽, 천정, 바닥, 및 도어로 구성되고, 양 측벽에는 상기 재배모판을 지지하기 위한 지지 가이드가 다단으로 배치되어 발아실과 촉진실, 성숙실의 재배공간을 제공하는 재배챔버;상기 재배챔버의 전면에 장착되어 재배챔버를 조작하고 동작상태를 표시하기 위한 프론트 패널;상기 재배공간에 양액을 공급하기 위한 양액 공급부;상기 재배공간의 온도를 조절하기 위한 공기온도 조절부;상기 프론트 패널의 조작에 따라 상기 공기온도 조절부를 제어하여 상기 재배공간의 온도를 조절하고, 상기 양액 공급부를 제어하여 상기 재배공간에 양액을 공급하며, 동작 상태를 상기 프론트 패널에 표시하기 위한 컨트롤러를 포함하고,상기 양액 공급부는양액을 저장하기 위한 양액 탱크와, 상기 양액 탱크의 양액 온도를 감지하기 위한 온도센서와,제어신호에 따라 양액의 온도를 일정하게 유지하기 위한 히터와,상기 발아실의 양 측벽에 설치되어 미스트방식으로 양액을 분사하기 위한 발아실 분사노즐과,상기 촉진실의 양 측벽에 설치되어 미스트방식으로 양액을 분사하기 위한 촉진실 분사노즐과,상기 성숙실의 양 측벽에 설치되어 미스트방식으로 양액을 분사하기 위한 성숙실 분사노즐과,상기 양액 탱크의 양액을 재배공간의 분사노즐에서 미스트 방식으로 분사시킬 수 있도록 제어신호에 따라 양액을 가압시키기 위한 분사펌프와,상기 분사펌프에 의해 가압된 양액을 제어신호에 따라 상기 발아실 노즐측으로 개폐하기 위한 발아실 분사밸브와,상기 분사펌프에 의해 가압된 양액을 제어신호에 따라 상기 촉진실 노즐측으로 개폐하기 위한 촉진실 분사밸브와,상기 분사펌프에 의해 가압된 양액을 제어신호에 따라 상기 성숙실 노즐측으로 개폐하기 위한 성숙실 분사밸브로 구성되어새싹땅콩을 배양하기 위한 양액의 온도를 조절할 수 있음과 동시에 온도조절된 양액을 재배모판 위로 미스트방식으로 분사할 수 있는 것을 특징으로 하는 새싹땅콩 수경재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

412/1059 Row 412: application_number: 1020200023077, combined_string: invention_title: 분무경재배용 분무화 수단 및 이를 포함하는 분무경재배 시스템 abstract: 본 발명은 분무경재배에 필요한 양액 및 관수의 액상 물질을 분무화하여 분무경재배 작물의 근부에 안정적이고 지속적이며 효율적으로 제공할 수 있도록 하고, 이에 따라 건강하고 균질한 분무경재배 작물을 양산할 수 있어 농가 소득 향상을 도모할 수 있는 분무경재배용 분무화 수단 및 이를 포함하는 분무경재배 시스템에 관한 것이다. 본 발명에 따르면, 분무경재배 작물이 식재되는 하나 이상의 분무경재배작물 식재부재; 상기 분무경재배작물 식재부재에 식재되는 분무경재배 작물의 근부에 양액 및 수분 중 적어도 하나의 액상 물질을 분무화하여 제공하도록 구성되는 분무화 수단; 상기 분무화 수단에 상기 액상 물질을 공급하도록 구성되는 양액 및 수분 공급 수단; 상기 분무경재배작물 식재부재에 구비되어 분무경재배 작물의 생육에 영향을 미치는 인자를 검출하도록 구성되는 센서 모듈; 및 상기 센서 모듈로부터의 검출 신호를 제공받아 관련 제어를 실행하며, 상기 분무화 수단과 상기 양액 및 수분 공급 수단의 작동을 제어하도록 구성되는 제어반;을 포함하는 것을 특징으로 하는 분무경재배 시스템이 제공된다. claims: 분무경재배용 분무화 장치로서,양액 및 수분 중 적어도 하나의 분무화 할 액상 물질이 공급되는 관형 라인;상기 관형 라인에 소정 간격을 갖고 구비되며, 상기 액상 물질을 분무화하는 진동자를 포함하여 상기 관형 라인 외측으로 분무화하는 초음파 모듈; 및상기 관형 라인 내의 액상 물질을 상기 초음파 모듈의 진동자 측으로 제공하도록 구성되는 양액-수분 전달 수단;을 포함하고,상기 관형 라인은 일단부가 폐쇄되고 타단부는 상기 액상 물질이 공급되는 공급 라인에 연결되는 플렉시블한 튜브형 라인으로 형성되며,상기 양액-수분 전달 수단은 상기 초음파 모듈의 진동자를 구성하되 환형으로 형성되는 환형부 및 상기 환형부의 중앙부를 형성하며 미세 기공이 복수 형성되는 액적 형성부로 이루어지며,상기 액적 형성부는 상기 환형부보다 상대적으로 얇은 다이아프램(diaphragm) 형태로 이루어지는 것을 특징으로 하는분무경재배용 분무화 장치.청구항 제1항에 따른 분무경재배용 분무화 장치를 포함하는 것을 특징으로 하는분무경재배 시스템.분무경재배 작물이 식재되는 하나 이상의 분무경재배작물 식재부재;상기 분무경재배작물 식재부재에 식재되는 분무경재배 작물의 근부에 양액 및 수분 중 적어도 하나의 액상 물질을 분무화하여 제공하도록 구성되는 분무화 수단;상기 분무화 수단에 상기 액상 물질을 공급하도록 구성되는 양액 및 수분 공급 수단;상기 분무경재배작물 식재부재에 구비되어 분무경재배 작물의 생육에 영향을 미치는 인자를 검출하도록 구성되는 센서 모듈; 및상기 센서 모듈로부터의 검출 신호를 제공받아 관련 제어를 실행하며, 상기 분무화 수단과 상기 양액 및 수분 공급 수단의 작동을 제어하도록 구성되는 제어반;을 포함하고,상기 분무경재배작물 식재부재는 원형 또는 다각형의 단면을 갖는 관형 바디, 및 상기 관형 바디에 소정 간격을 갖고 형성되어 분무경재배 작물이 식재되는 식재 구멍으로 이루어지고,상기 분무화 수단은 상기 분무경재배작물 식재부재의 관형 바디 내부를 통과하며 상기 양액 및 수분 공급 수단로부터 공급되는 액상물질을 제공받는 양액 및 수분 공급 관형 라인과, 상기 양액 및 수분 공급 관형 라인에 소정 간격을 갖고 구비되어 상기 액상 물질을 분무화하되, 진동자가 외부로 노출되게 구비되는 초음파 모듈, 및 상기 양액 및 수분 공급 관형 라인 내의 액상 물질을 상기 초음파 모듈의 진동자 측으로 제공하도록 구성되는 양액-수분 전달 수단을 포함하고,상기 양액 및 수분 공급 관형 라인은, 일단부가 폐쇄되고 타단부는 상기 양액 및 수분 공급 수단의 공급 라인에 연결되는 플렉시블한 튜브형 라인으로 형성되며,상기 양액-수분 전달 수단은 상기 초음파 모듈의 진동자를 구성하되 환형으로 형성되는 환형부 및 상기 환형부의 중앙부를 형성하며 미세 기공이 복수 형성되는 액적 형성부로 이루어지며,상기 액적 형성부는 상기 환형부보다 상대적으로 얇은 다이아프램(diaphragm) 형태로 이루어지는 것을 특징으로 하는분무경재배 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

413/1059 Row 413: application_number: 1020200020605, combined_string: invention_title: IoT 기술을 이용하여 농산물을 생산하는 방법 및 이를 위한 장치 abstract: 본 발명은 농장 관리 서버가 농산물을 생산하기 위해 IoT (Internet of Things)를 이용한 스마트 농장을 제어하는 방법을 개시한다. 특히, 상기 방법은, 상기 스마트 농장에서 생산하는 농산물에 대한 정보를 추출하고, 상기 스마트 농장에 설치된 온습도 센서를 통해 상기 스마트 농장의 온습도 정보를 획득하고, 상기 농산물에 대한 정보를 기반으로, 상기 스마트 농장의 목표 온습도를 설정하고, 상기 목표 온습도를 기반으로, 상기 스마트 농장의 조명 장치 및 가습 장치를 제어하는 것을 특징으로 한다. claims: 농장 관리 서버가 농산물을 생산하기 위해 IoT (Internet of Things)를 이용한 스마트 농장을 제어하는 방법에 있어서,상기 스마트 농장에서 생산하는 농산물에 대한 정보를 추출하고,상기 스마트 농장에 설치된 온습도 센서를 통해 상기 스마트 농장의 온습도 정보를 획득하고,상기 농산물에 대한 정보를 기반으로, 상기 스마트 농장의 목표 온습도를 설정하고,상기 목표 온습도를 기반으로, 상기 스마트 농장의 조명 장치 및 가습 장치를 제어하고,상기 스마트 농장 내부에 설치된 카메라를 이용하여 상기 농산물의 크기를 측정하고,상기 농산물의 크기를 기반으로, 상기 농산물로 방출되는 조성물의 양 및 상기 조성물의 농도를 결정하고,상기 양 및 농도에 따라 상기 조성물을 방출할 것을 상기 스마트 농장에 명령하고,상기 농산물에 대한 정보를 기반으로, 상기 농산물에 대응하는 시간 별 목표 조도 및 추천 조명 색상을 획득하고,현재 시각, 목표 조도 및 추천 조명 색상을 기반으로, 상기 스마트 농장에 설치된 조명 장치를 제어하고,상기 조명 장치는,조명, 상기 조명의 아래에 설치되어 상기 조명의 명암을 조절하는 개폐 장치 및 상기 조명과 상기 개폐 장치 사이에 설치되어 상기 조명의 색상을 변경하기 위한 광색 조절 장치를 포함하고,상기 조명 장치를 제어하는 것은,현 시간에 대응하는 상기 농산물을 위한 광색에 대한 정보를 RGB 값으로 획득하고,상기 광색 조절 장치에 포함된 복수의 광색판들 중, 상기 RGB 값과 가장 가까운 RGB 값을 가지는 제 1 광색판을 상기 조명의 아래쪽으로 위치시키고, 상기 제 1 광색판을 제외한 나머지 제 2 광색판들은 상기 조명으로부터 일정 거리 이상 떨어져 위치하도록 제어하며,상기 농산물의 크기를 측정하는 것은,상기 카메라가 제 1 시점에서 상기 농산물을 촬영한 제 1 이미지와 상기 카메라가 상기 제 1 시점 이후인 제 2 시점에서 상기 농산물을 촬영한 제 2 이미지를 비교하여, 상기 제 1 이미지에서 상기 농산물이 차지하는 제 1 비율과 상기 제 2 이미지에서 상기 농산물이 차지하는 제 2 비율 간의 차이 값을 계산하고,상기 제 1 이미지에서의 상기 농산물의 제 1 크기를 산출하고,상기 차이 값 및 상기 제 1 크기를 기반으로, 상기 제 2 시점에서의 상기 농산물의 제 2 크기를 결정하는 것을 포함하고,상기 제 1 크기를 산출하는 것은,상기 카메라의 중심선을 기준으로 2개의 측정선들을 생성하고, 상기 2개의 측정선들 각각이 상기 농산물을 만나는 교차점들을 결정하고, 상기 교차점들을 잇는 선과 상기 중심선이 만나는 지점으로부터 카메라까지의 길이를 측정하고, 상기 측정된 카메라까지의 길이와, 상기 중심선과 상기 2개의 측정선 사이의 각도를 이용하여 상기 농산물의 세로 길이를 측정하고, 상기 세로 길이 및 상기 농산물의 가로 방향의 양 끝점을 기반으로 상기 농산물의 제 1 크기를 산출하는 것을 포함하며,상기 농산물은 복수의 재배 영역들에서 재배되고,상기 복수의 재배 영역들은 세로 길이는 동일하되, 가로 길이는 서로 상이하고,상기 복수의 재배 영역들은 각 라인 별로 설치된 가로 이동 레일들 위에 설치되어, 가로 방향으로 이동하며,상기 가로 이동 레일들의 가장 우측 방향으로 이동하여, 세로 이동 레일에 옮겨지면, 상기 세로 이동 레일에 따라 세로 방향으로 이동하는,스마트 농장 제어 방법.농산물을 생산하기 위해 IoT (Internet of Things)를 이용한 스마트 농장을 제어하는 농장 관리 서버에 있어서,스마트 농장과 데이터를 송수신하기 위한 통신 모듈;상기 데이터를 저장하는 저장 모듈; 및상기 통신 모듈 및 상기 저장 모듈과 연동되어, 상기 농장 관리 서버의 동작을 제어하는 제어 모듈;을 포함하고,상기 제어 모듈은,상기 저장 모듈로부터 상기 스마트 농장에서 생산하는 농산물에 대한 정보를 추출하고,상기 통신 모듈을 이용하여 상기 스마트 농장에 설치된 온습도 센서를 통해 상기 스마트 농장의 온습도 정보를 획득하고,상기 농산물에 대한 정보를 기반으로, 상기 스마트 농장의 목표 온습도를 설정하고,상기 통신 모듈을 이용하여 상기 목표 온습도를 기반으로, 상기 스마트 농장의 조명 장치 및 가습 장치를 제어하고,상기 스마트 농장 내부에 설치된 카메라를 이용하여 상기 농산물의 크기를 측정하고,상기 농산물의 크기를 기반으로, 상기 농산물로 방출되는 조성물의 양 및 상기 조성물의 농도를 결정하고,상기 양 및 농도에 따라 상기 조성물을 방출할 것을 상기 스마트 농장에 명령하고,상기 농산물에 대한 정보를 기반으로, 상기 농산물에 대응하는 시간 별 목표 조도 및 추천 조명 색상을 획득하고,현재 시각, 목표 조도 및 추천 조명 색상을 기반으로, 상기 스마트 농장에 설치된 조명 장치를 제어하고,상기 조명 장치는,조명, 상기 조명의 아래에 설치되어 상기 조명의 명암을 조절하는 개폐 장치 및 상기 조명과 상기 개폐 장치 사이에 설치되어 상기 조명의 색상을 변경하기 위한 광색 조절 장치를 포함하고,상기 조명 장치를 제어하는 것은,현 시간에 대응하는 상기 농산물을 위한 광색에 대한 정보를 RGB 값으로 획득하고,상기 광색 조절 장치에 포함된 복수의 광색판들 중, 상기 RGB 값과 가장 가까운 RGB 값을 가지는 제 1 광색판을 상기 조명의 아래쪽으로 위치시키고, 상기 제 1 광색판을 제외한 나머지 제 2 광색판들은 상기 조명으로부터 일정 거리 이상 떨어져 위치하도록 제어하며,상기 농산물의 크기를 측정하는 것은,상기 카메라가 제 1 시점에서 상기 농산물을 촬영한 제 1 이미지와 상기 카메라가 상기 제 1 시점 이후인 제 2 시점에서 상기 농산물을 촬영한 제 2 이미지를 비교하여, 상기 제 1 이미지에서 상기 농산물이 차지하는 제 1 비율과 상기 제 2 이미지에서 상기 농산물이 차지하는 제 2 비율 간의 차이 값을 계산하고,상기 제 1 이미지에서의 상기 농산물의 제 1 크기를 산출하고,상기 차이 값 및 상기 제 1 크기를 기반으로, 상기 제 2 시점에서의 상기 농산물의 제 2 크기를 결정하는 것을 포함하고,상기 제 1 크기를 산출하는 것은,상기 카메라의 중심선을 기준으로 2개의 측정선들을 생성하고, 상기 2개의 측정선들 각각이 상기 농산물을 만나는 교차점들을 결정하고, 상기 교차점들을 잇는 선과 상기 중심선이 만나는 지점으로부터 카메라까지의 길이를 측정하고, 상기 측정된 카메라까지의 길이와, 상기 중심선과 상기 2개의 측정선 사이의 각도를 이용하여 상기 농산물의 세로 길이를 측정하고, 상기 세로 길이 및 상기 농산물의 가로 방향의 양 끝점을 기반으로 상기 농산물의 제 1 크기를 산출하는 것을 포함하며,상기 농산물은 복수의 재배 영역들에서 재배되고,상기 복수의 재배 영역들은 세로 길이는 동일하되, 가로 길이는 서로 상이하고,상기 복수의 재배 영역들은 각 라인 별로 설치된 가로 이동 레일들 위에 설치되어, 가로 방향으로 이동하며,상기 가로 이동 레일들의 가장 우측 방향으로 이동하여, 세로 이동 레일에 옮겨지면, 상기 세로 이동 레일에 따라 세로 방향으로 이동하는,농장 관리 서버., Ltext: 농업, prediction: 농업
414/1059 Row 414: application_number: 1020200014021, combined_string: invention_title: 태양의 일출과 일몰을 재현한 재배 장치 abstract: 태양의 일출과 일몰을 재현하기 위한 재배 장치가 제공된다. 실내 수직형 농장에 이용되는 재배 장치는 식물이 배치되어 생장하는 바닥 영역; 상기 바닥 영역에 대면하도록 형성된 천정 영역; 상기 바닥 영역에 대면하도록 상기 천정 영역에 부착된 레일; 상기 레일 상에 부착된 상태로 미리 정해진 방향을 따라 이동하는 광원 어레이; 및 상기 재배 장치를 제어하는 컨트롤러로서, 상기 광원 어레이가 상기 레일 상에서 이동하도록 제어하는 것인, 컨트롤러를 포함하고, 상기 광원 어레이가 상기 레일 상에서 이동함에 따라 상기 광원 어레이로부터 상기 바닥 영역까지의 거리 또는 상기 광원 어레이와 상기 바닥 영역이 이루는 각도 중 적어도 하나가 변경된다. claims: 실내 수직형 농장에 이용되는 재배 장치에 있어서,식물이 배치되어 생장하는 바닥 영역;상기 바닥 영역에 대면하도록 형성된 천정 영역;상기 천정 영역과 상기 바닥 영역 사이에 배치되어 일 방향으로 연장되고, 적어도 일부에 굴곡이 형성되는 레일;상기 천정 영역과 상기 레일 사이를 연결하는 방향으로 연장되어 양 단이 상기 천정 영역과 상기 레일 사이에 각각 결합되고, 그 연장길이가 가변 가능하게 구성되며, 상기 레일의 연장방향 따라 배치되는 복수의 리프터; 상기 레일 상에 부착된 상태로 미리 정해진 방향을 따라 이동하는 광원 어레이; 상기 천정 영역에 인접하게 위치하여 상기 바닥 영역 상의 상기 식물을 촬용하는 카메라 및 상기 식물과의 거리를 측정하는 거리 센서; 및상기 재배 장치를 제어하는 컨트롤러로서, 상기 광원 어레이가 상기 레일 상에서 이동하도록 제어하고, 복수의 상기 리프터 각각의 연장길이를 개별적으로 제어하는 컨트롤러를 포함하고,상기 레일에 형성된 굴곡으로 인하여, 상기 광원 어레이가 상기 레일 상에서 이동함에 따라 상기 광원 어레이로부터 상기 바닥 영역까지의 거리 또는 상기 광원 어레이와 상기 바닥 영역이 이루는 각도 중 적어도 하나가 변경되며,상기 컨트롤러는 상기 카메라의 촬영 결과 또는 상기 거리 센서의 측정된 거리에 기초하여 상기 식물의 생장 정도를 산출하여, 상기 식물의 생장 정도에 따라 상기 레일의 굴곡이 조절되거나 상기 바닥 영역으로부터 상기 레일이 위치한 높이가 조절되도록 복수의 상기 리프터 각각의 연장길이를 개별적으로 제어하고,상기 컨트롤러는 상기 카메라의 촬영 결과에 기초하여 상기 식물의 종류를 파악하여, 상기 파악된 식물의 종류에 따라 상기 광원 어레이의 RGB값을 변경하는 것인, 재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

415/1059 Row 415: application_number: 1020200010172, combined_string: invention_title: 작물 재배 또는 육묘용 포트 어셈블리 abstract: 본 발명은 포트플레이트(60)의 포트(61)들 사이의 길이방향으로 뚫려져 연속하여 이어지는 어퍼홈라인(62)에 선형조립수단(70)을 끼워 포트플레이트(60)들을 연속하여 누르면서 일체화시킬 수 있도록 함으로써 바람에 의한 영향이나 작업자의 부딪힘에 의한 영향을 최소화시켜 포트플레이트(60)들을 견고하게 안정될 수 있도록 함과 동시에 작물 재배 완료 후 또는 작물 육묘 완료 후 포트플레이트(60)들을 적층시켜 보관하고자 밧줄로 묶고자 할 때 어퍼홈라인(62)을 경유시킬 수 있도록 함으로써 보관시 묶음처리 상태 역시 더욱 견고하게 실현케 할 수 있고, 특히, 선형조립수단(70)이 어퍼홈라인(62)에 끼워진 상태로 포트플레이트(60)들을 누를 수 있도록 하여 어퍼홈라인(62)으로부터 선형조립수단(70)의 분리현상을 극소화시켜 선형조립수단(70)의 무단이탈에 의한 작물로의 악영향(상처나 훼손)을 철저히 방지하고, 나아가 선형조립수단(70) 및 받침파이프(F1) 상호간의 양끝단의 직접적인 묶음처리로서 프레임(F)에서부터 포트플레이트(60)들에 이르기까지 일체화된 상태를 보장하여 보다 안정감 있게 작물을 재배 및 육묘할 수 있는 특유의 작용을 발휘하는 작물 재배 또는 육묘용 포트 어셈블리에 관한 발명이다. claims: 배수구멍(61a)이 뚫린 포트(61)들을 지니면서 직선상으로 연속하여 이웃하는 포트플레이트(60)들을 포함하는 작물 재배 또는 육묘용 포트 어셈블리에 있어서,상기 포트플레이트(60)들은 상기 포트(61)들 사이의 길이방향으로 뚫려져 연속하여 이어지는 어퍼홈라인(62)을 각각 구비하고,상기 어퍼홈라인(62)들을 따라 끼워져 상기 포트플레이트(60)들을 연속하여 누르면서 일체화시키는 선형조립수단(70)을 포함하고,상기 포트플레이트(60)는 상기 어퍼홈라인(62)을 따라 하향 돌출되는 언더볼륨라인(63)을 더 포함하고,상기 포트플레이트(60)의 길이방향의 전측으로부터 폭방향을 따라 돌출된 전측어퍼돌출턱(64)과, 상기 포트플레이트(60)의 길이방향의 후측으로부터 폭방향을 따라 돌출된 후측언더돌출턱(65)을 더 포함하고,상기 포트플레이트(60)들은 직선상으로 연속하여 이웃할 때 상기 후측언더돌출턱(65) 위에 상기 전측어퍼돌출턱(64)이 포개어져 합치되고,상기 전측어퍼돌출턱(64)은 상기 포트플레이트(60)의 길이방향의 전측으로부터 폭방향을 따라 돌출되면서 상기 언더볼륨라인(63)에 대응되는 부분에서 오픈되는 수직홀(64a)을 구비하고,상기 후측언더돌출턱(65)은 상기 포트플레이트(60)의 길이방향의 후측으로부터 폭방향을 따라 상기 언더볼륨라인(63)과 함께 돌출되어 상기 수직홀(64a)을 리커버링하면서 상기 어퍼홈라인(62)들을 연속하여 이어주는 것을 특징으로 하는 작물 재배 또는 육묘용 포트 어셈블리., Ltext: 농업, prediction: 임업
416/1059 Row 416: application_number: 1020200001487, combined_string: invention_title: 수경재배용 나노복합체 배지 및 이의 제조방법 abstract: 본 발명은 다공성 배지에 수소처리된 광촉매가 코팅된 것을 특징으로 하는 수경재배용 나노복합체 배지 및 제조방법에 관한 것이다. claims: 다공성 배지에 수소처리된 광촉매가 코팅된 것을 특징으로 하는 수경재배용 나노복합체 배지.다공성 배지를 준비하는 단계;광촉매 나노분말을 수소처리하는 단계; 및상기 다공성 배지에 상기 수소처리된 광촉매를 코팅하는 단계를 포함하는 수경재배용 나노복합체 배지의 제조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

417/1059 Row 417: application_number: 1020190178964, combined_string: invention_title: 조립구조를 갖는 실내용 스마트 수경재배시스템 abstract: 본 발명은 조립구조를 갖는 실내용 스마트 수경재배시스템에 관한 것으로, 보다 상세하게는, 고정수단(10), 광원공급부(20), 수경재배기(30), 고임물통(40), 양액통(50), 연결관(60), 팬(70), 제어부(80), 솔라패널(90)로 구성되어, 실내에 설치하여 식물을 수경재배하되, 제어부를 통해 광원공급, 수분공급, 팬의 작동을 자동적으로 제어함으로써, 스마트하게 식물재배가 가능한 한편, 솔라패널이 보조적인 전력을 공급하도록 하여 주전력원으로부터 전력공급이 되지 않는다고 하더라도 상기 솔라패널을 통해 제어부로 전력을 공급토록 하여, 사용상의 편리성을 극대화할 수 있음은 물론, 수경재배기(30)가 분할된 구조로 상호 결합됨에 따라서 다양하게 가변하여 사용할 수가 있는 유용한 발명이다. claims: 벽면 또는 지면에 설치되어 수경재배기(30)를 고정하기 위한 고정수단(10);상기 고정수단(10)의 상부에 수평 또는 측면에 수직방향으로 설치되어 식물로 광원을 공급하는 광원공급부(20);상기 고정수단(10)의 전면에 설치되고, 다수개로 구성되어 상호 조립 구성되되, 일측이 개방된 형태로 4개의 식재공간(31)이 경사지게 형성되고, 각각의 식재공간(31)의 상측과 하측에 물의 이동을 위해 각각의 홀(33)이 형성되며, 외부 양측에 연결관이 인입되어 고정하기 위한 연결관걸림홀(35)가 각각 형성되는 수경재배기(30);상기 수경재배기(30)의 하부에 구성되어 상기 수경재배기(30)로 공급되어 식물이 먹고 남은 물이 고이도록 하는 고임물통(40);상기 고임물통(40)의 하부에 구성되며 내부에 상기 수경재배기(30)로 물을 공급하기 위한 수중펌프(51)가 구성되는 양액통(50);상기 수경재배기(30)의 식재공간(31)에 식재된 식물로 양액통(50)의 물이 공급될 수 있도록 연결하는 연결관(60);상기 수경재배기(30)의 상부 일측에 설치되어 식재된 식물로부터 발산되는 허브향을 이동시키기 위한 하나 이상의 팬(70);전력원으로부터 전원을 공급받아 작동하되, 누전 발생 시 이를 차단하는 누전차단기(81)와, 상기 광원공급부(20)의 광원공급시간, 양액통(50)의 수분공급시간, 팬(70)의 작동시간을 제어하는 타이머(83)를 포함하며, 상기 광원공급부(20)의 광량, 양액통(50)의 수분공급량을 제어하는 제어부(80); 로 구성되는 것을 특징으로 하는 조립구조를 갖는 실내용 스마트 수경재배시스템., Ltext: 농업, prediction: 농업
418/1059 Row 418: application_number: 1020190179376, combined_string: invention_title: 심지를 이용한 수경재배장치 abstract: 본 발명은 심지를 이용한 수경재배장치에 관한 것으로, 더욱 상세하게는 심지를 이용한 대량 수경재배에서, 다수의 화분에 손쉽게 심지를 꽂을 수 있도록 하고, 배지에 대해 최적의 수분함량을 일정하게 유지시킬 수 있도록 구조 개선된 심지를 이용한 수경재배장치에 관한 것이다. claims: 양액이 순환 가능하게 저수되는 베드(11); 상기 베드(11) 내부 바닥에 간격을 두고 다열로 배치되는 심지브래킷(12); 상기 양액에 침지된 상태로 하나의 열에 배치되는 각 심지브래킷(12) 상부에 거치되는 하나의 띠 형태로 이루어진 심지(13); 상기 베드(11) 상부에 다열로 안치되는 식물 생장용 화분(14); 을 포함하는 것,을 특징으로 하는 심지를 이용한 식물 수경재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

419/1059 Row 419: application_number: 1020190178756, combined_string: invention_title: 생장프로파일(Growth Profiles) 기반의 공장형 버섯재배사 원격 자동 생육제어 방법 및 장치 abstract: 본 발명은 공장형 버섯재배사 냉난방기, 가습기, 급배기팬 등 구동기를 제어하는 생장프로파일을 구성, 궁극적으로 무인 자동제어 환경상태에서 최적의 작물 재배 환경을 구현하기 위한 것이다.최근 버섯 재배환경은 노동 집약적 소규모 재배환경에서 기계화 설비를 통해 품질을 균일화하는 공장형 생산방식으로 변모하고 있다. 특히 ICT 기술을 활용하여 온도, 습도, 이산화탄소(CO2) 농도 등 환경을 비교 분석하여 버섯 성장에 가장 적합한 환경 요건을 조성하는 생장프로파일 제어 방식은 버섯 생산량과 품질 향상의 전환점이 될 것으로 기대되고 있다. 버섯 재배의 수율 극대화를 위해서는 검증된 생장프로파일을 기반으로 버섯재배사를 운영하는 것이 필요하다. 버섯재배사 운영자의 작물재배에 대한 개별 편차를 인정하더라도 적어도 전문가 의해 도출된 최적의 생장 프로파일을 참조하는 것은 작물 수율 극대화에 큰 기여를 할 수 있다. claims: 버섯재배사 관리자의 개별 경험에 따라 작물수확량 편차가 발생하는 경험 위주 재배방식의 비정량화 문제를 해결하기 위해 버섯의 최적 생장을 유도하기 위한 생장 프로파일을 도출한 후 이를 다수의 공장형 버섯재배사에 적용하여 버섯의 생육환경을 원격 자동제어 하기 위한 '생장프로파일 (Growth Profiles) 기반의 공장형 버섯재배 원격 자동 생육제어 방법 및 장치'에 있어서상기 원격장치부 생장프로파일생성부가;작물의 최적 생장을 유도하기 위해 품종별, 재배기간별로 온도, 습도, 이산화탄소(CO2) 등 버섯 생장에 가장 적합한 생육 환경 요건을 정의한 데이터의 집합인 생장프로파일(Growth Profiles)을 생성하는 기능을;로컬장치부 다운로드요청부가;인터넷 등 원격 통신망을 통해 원격장치부 생장프로파일생성부가 생성한 생장프로파일을 다운로드 받는 기능을;로컬장치부 생장프로파일실행부가;원격 다운로드 받은 생장프로파일이 로컬장치부에서 작동될 수 있도록 로컬장치부의 센서, 제어기, 제어로직을 생장프로파일과 연동하는 기능을; 로컬장치부 장치시계부가;인터넷시간서버를 주기적으로 참조하여 시간오류를 수정하며, 이를 기반으로 생장 프로파일 제어 시작 및 종료 시간을 체크하여 제어 시간대를 관리해주는 기능을;로컬장치부 센서수집부가;로컬장치부에 연동된 센서를 주기적으로 체크하여 제어부에 센서값을 전달하는 기능을;로컬장치부 제어부가;센서수집부에서 전달받은 센서값을 기반으로 제어여부를 판단하여 해당 제어 조건일 경우 히팅방식 또는 쿨링 방식 등 해당 제어로직을 통해 구동기를 자동제어하는 기능을;특징으로 하는 생장프로파일(Growth Profiles) 기반의 공장형 버섯재배 원격 자동 생육제어 방법 및 장치, Ltext: 농업, prediction: 임업
420/1059 Row 420: application_number: 1020190174308, combined_string: invention_title: 식물 재배 장치 abstract: 개시되는 내용의 일 실시예에 따른 식물 재배 장치는 본체, 선반, 재배베드 및 재배용기를 포함한다. 본체 내부에 형성되는 재배공간에 선반이 형성되고, 선반위에 재배베드가, 재배베드의 내측에 재배용기가 안착된다.재배베드는 일정량의 물이 수용되는 급수부를 포함한다. 그리고, 선반은 급수부 연직하방에 위치해 급수부 내부에 수용된 물의 양을 계측하는 수위센서를 포함한다. claims: 내부에 재배공간을 형성하고 적어도 일면에 결합된 도어를 통해 상기 재배공간이 열리거나 닫히는 본체;상기 재배공간에 가로놓여 배치되며 수위센서가 구비되는 선반;상기 선반에 올려 놓이고, 내부에 수용공간이 형성되는 상면이 개방된 용기로서, 바닥면에 물이 고여 저장되는 급수부가 형성되는 재배베드; 및상기 재배배드의 급수부 상부에 배치되는 재배용기;를 포함하고,상기 급수부가 상기 수위센서 상부에 위치해 상기 수위센서는 상기 급수부에 저장된 물의 양을 계측하는,식물 재배 장치.제9항에 있어서,상기 재배용기는,하단이 상기 개방구와 인접하게 배치되고, 상단이 상기 재배용기 내부에서 위쪽을 향하도록 배치되며, 다공성 재질로 이루어져 물을 흡수하는 심지;를 포함하는,식물 재배 장치.내부에 재배공간을 형성하고 적어도 일면에 결합된 도어를 통해 상기 재배공간이 열리거나 닫히는 본체;상기 재배공간에 가로놓여 배치되며 수위센서가 구비되는 선반;상기 선반에 올려 놓이고, 내부에 수용공간이 형성되는 상면이 개방된 용기로서, 바닥면에 물이 고여 저장되는 급수부가 형성되는 재배베드; 및상기 재배배드의 급수부 상부에 배치되는 재배용기;를 포함하고,상기 수위센서는 상기 급수부에 저장된 물의 양을 계측하고, 상기 수위센서를 통해 계측된 상기 급수부에 저장된 물의 양이 미리 정해진 양보다 작을 경우 상기 급수부에 물을 공급하는,식물 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

421/1059 Row 421: application_number: 1020190174321, combined_string: invention_title: 염분차 발전에 기반한 에너지 자립형 스마트 팜 시스템 abstract: 염분차 발전에 기반한 스마트 팜 시스템이 개시된다. 스마트 팜 시스템은 농작물 재배가 이루어지는 농장 시설과 여과 오폐수, 음식물 폐기물 산 발효액, 이산화탄소 흡수액, 및 여과액비로 이루어진 그룹에서 선택된 적어도 하나를 포함하는 고농도 용액과 상기 고농도 용액보다 농도가 낮은 저농도 용액을 공급받아 상기 고농도 용액과 상기 저농도 용액의 농도차를 이용하여 전기를 생성하고, 상기 농작물의 생장에 사용되는 생장원료를 공급하는 염분차 발전장치를 포함한다. claims: 농작물 재배가 이루어지며, 상기 농작물 재배를 위한 적어도 하나 이상의 농작물 재배용 센서와 전자기계 장치를 포함하는 농장 시설; 음식물 폐기물 산 발효액, 이산화탄소 흡수액, 여과액비 및 비료액으로 이루어진 그룹에서 선택된 적어도 하나를 포함하는 고농도 용액과 상기 고농도 용액보다 농도가 낮은 저농도 용액을 공급받아 상기 고농도 용액과 상기 저농도 용액의 농도차를 이용하여 전기를 생성하고, 상기 농작물의 생장에 사용되는 생장원료를 배출하여 상기 농작물에 공급하는 염분차 발전장치; 상기 염분차 발전장치와 상기 농장 시설 사이에 설치된 생장 원료 희석 공급부로, 상기 생장 원료 희석 공급부는 상기 염분차 발전장치와 상기 농장 시설에 연결 설치된 배관, 상기 배관에 설치된 농도 측정기, 및 상기 농도 측정기에서 농도가 측정된 생장원료가 유입되는 입구, 상기 농장 시설에 연결된 제1 출구와 상기 염분차 발전장치 전단에 상기 고농도 용액의 경로에 연결된 제2 출구를 포함하는 밸브를 포함하고, 상기 농도 측정기의 측정 결과가 설정 범위를 만족하면 상기 제1 출구를 개방하여 상기 생장 원료를 상기 농장 시설에 공급하고, 상기 농도 측정기의 측정 결과가 설정 범위를 만족하지 않으면 상기 제2 출구를 개방하여 상기 생장 원료를 상기 고농도 용액과 섞어 상기 염분차 발전장치로 다시 공급하는 생장 원료 희석 공급부; 및상기 염분차 발전장치에서 생산된 상기 전기를 저장하고, 상기 센서와 상기 전자기계 장치에 상기 전기를 공급하는 에너지 저장 시스템을 포함하는 염분차 발전장치에 기반한 에너지 자립형 스마트 팜 시스템.농작물 재배가 이루어지며, 상기 농작물 재배를 위한 적어도 하나 이상의 농작물 재배용 센서와 전자기계 장치를 포함하는 농장 시설; 음식물 폐기물 산 발효액, 이산화탄소 흡수액, 여과액비 및 비료액으로 이루어진 그룹에서 선택된 적어도 하나를 포함하는 고농도 용액과 상기 고농도 용액보다 농도가 낮은 저농도 용액을 공급받아 상기 고농도 용액과 상기 저농도 용액의 농도차를 이용하여 전기를 생성하고, 상기 농작물의 생장에 사용되는 생장원료를 배출하여 상기 농작물에 공급하는 염분차 발전장치; 고농도 염수와 상기 고농도 용액 중 어느 하나와 상기 저농도 용액을 공급받아 전기를 생성하는 대용량 염분차 발전장치; 및 상기 염분차 발전장치 및 상기 대용량 염분차 발전장치에서 생성된 전기를 저장하고, 상기 센서와 상기 전자기계 장치에 상기 전기를 공급하는 에너지 저장 시스템을 포함하고, 상기 대용량 염분차 발전장치는 수광부를 갖는 제1 면 및 제1 면의 반대방향의 제2 면을 갖는 태양전지 패널; 및 상기 저농도 용액으로 이루어진 제1 용액과 상기 고농도 염수와 상기 고농도 용액 중 어느 하나로 이루어진 제2 용액이 유입하여 염도차 발전을 통해 전기를 생산하기 위한 염도차 발전 유닛을 포함하며,상기 염도차 발전 유닛은, 제1 용액 유입포트 및 유출포트, 제2 용액 유입포트 및 유출포트를 갖는 하우징;하우징 내에 배치되고, 소정간격 떨어져 마련된 애노드 및 캐소드 전극; 및애노드 및 캐소드 전극 사이에 제1 용액이 유동하는 제1 유로 및 제2 용액이 유동하는 제2 유로를 구획하도록 배열된 복수 개의 이온교환막을 포함하고,상기 하우징은, 제1 용액 유입포트 및 제1 유로를 유체 이동 가능하게 연결하는 제1 용액 유입부를 갖고,상기 제1 용액 유입부는 유입된 제1 용액 및 태양전지 패널의 상기 제2 면 사이에 열 교환이 이루어지도록 마련된 에너지 자립형 스마트 팜 시스템., Ltext: 농업, prediction: 임업
422/1059 Row 422: application_number: 1020190173519, combined_string: invention_title: 계층적 구조를 갖는 무선 네트워크를 통한 스마트팜 제어 방법 abstract: 사용하는 상기 온도, 습도, 풍량, 조도 센서 등의 동작 전압과 출력전압 등에 차이가 있어, 사용하는 센서마다 다른 제어프로그램 또는 다른 설정값을 사용한다. 또한, 재배 작물이 달라지면 상기 설정값도 다른 설정값을 사용하여야 한다. claims: 온도, 습도, 풍량, 조도 센서에서 측정된 센서 값을 스마트팜 센서제어기에서 아날로그-디지털 변환하여 디지털 센서 값을 온도, 습도, 풍량, 조도로 변환하지 않고, 상기 디지털 센서 값을 그대로 클라우드 컴퓨팅 서버로 전송하며, 상기 클라우드 컴퓨팅 서버에는 상기 스마트팜 센서제어기에 부여된 코드를 색인으로 하여, 상기 클라우드 컴퓨팅 서버에 구축된 환경센서 데이터베이스로부터 상기 온도, 습도, 풍량, 조도 센서의 메이커와 모델명을 기준으로 상기 온도, 습도, 풍량, 조도 교정데이터를 읽어와, 상기 디지털 센서 값을 온도, 습도, 풍량, 조도를 표시하는 실제 환경변수 값으로 변환하며, 상기 실제 환경변수 값은 온도 센서의 경우 ℃, 습도의 경우 상대습도 %, 조도의 경우 Lux, 풍량의 경우 m/s로 변환된 값이고, 상기 온도, 습도, 풍량, 조도 센서 중 어느 하나 이상의 센서가 바뀌어도 상기 클라우드 컴퓨팅 서버에 구축된 상기 환경 센서 데이터 베이스의 교정된 실제 환경 변수 값을 받아 설정된 설정 값과 비교하여 상기 스마트팜 센서제어기를 동작할 수 있기 때문에, 상기 온도, 습도, 풍량, 조도 센서 중 어느 하나 이상의 센서가 바뀌어도 상기 클라우드 컴퓨팅 서버의 환경 센서 데이터베이스에 센서의 종류를 업데이트하기만 하면 상기 스마트팜 센서제어기의 내장 프로그램의 수정 없이 사용할 수 있고, 상기 스마트팜 센서제어기와 연동된 구동장치의 동작을 위한 상기 설정 값도 재배시기, 작물의 종류, 외기 온도와 습도, 기후의 변화 양상에 따라 상기 클라우드 컴퓨팅 서버에서 설정 값을 바꾸어 상기 스마트팜 센서제어기에 전송할 수도 있고, 상기 스마트팜 센서제어기와 연동된 구동장치의 구동을 위한 센싱 값과 상기 설정 값과의비교를 상기 클라우드 컴퓨팅 서버에서 처리하도록 함으로써 상기 스마트팜 센서제어기에서는 센서 값의 전송과 그 결과로써 구해진 상기 스마트팜 센서제어기와 연동된 구동장치의 구동 동작을 상기 클라우드 컴퓨팅 서버에서 전송받아 구동하는 역할만을 할 수 있으며, 상기 스마트팜 센서제어기에 연결되는 보일러 온오프 또는 온도조절, 조명 온오프, 광조절 차광막, 환기창 개폐, 환풍기 온오프 또는 풍량조절, 내부 순환팬 온오프 또는 회전속도조절 장치의 제어명령은 상기 클라우드 컴퓨팅 서버에 제조사별, 모델별로 제어장치 데이터베이스에 저장하고, 상기 저장된 데이터를 이용하여 상기 스마트팜 센서제어기의 인덱싱번호를 이용하여 제조사와 모델을 상기 스마트팜 센서제어기와 연동함으로써 새로운 출력장치도 상기 스마트팜 센서제어기의 내장프로그램 수정 없이도 구동가능하게 할 수 있으며, 상기 클라우드 컴퓨팅 서버는 태풍, 폭설, 폭우 상황에서 측창의 개폐, 보일러의 온오프, 전원 차단의 원격지원을 제공함으로써 농작물의 피해를 최소화하는 것을 특징으로 하는 클라우드 컴퓨팅과 원격 센서를 이용한 스마트팜 제어방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

423/1059 Row 423: application_number: 1020190171766, combined_string: invention_title: 식물재배기 abstract: 본 발명은 식물재배기에 관한 것이다.본 발명에 따른 식물재배기는, 베이스; 상기 베이스의 상면에 평행한 면을 형성하고, 상기 베이스의 상면으로부터 상측으로 일정간격 이격배치되는 상부커버; 상기 베이스의 상면 둘레를 따라 배치되고, 상기 베이스와 상기 상부커버에 회전가능하게 배치되는 복수의 재배판넬; 상기 베이스의 상면 중심에서 상기 상부커버까지 상측으로 수직하게 연장되며, 상기 복수의 재배판넬이 배치되는 방향으로 빛을 조사하는 조명바를 포함하고, 상기 복수의 재배판넬 각각의 일측면에는, 식물이 삽입되는 복수의 재배홀더가 배치되고, 상기 복수의 재배홀더가 배치되는 상기 복수의 재배판넬 각각의 일측면은, 상기 조명바를 향하는 제1위치 또는 상기 제1위치에 반대방향을 향하는 제2위치로 배치된다. claims: 베이스;상기 베이스의 상면에 평행한 면을 형성하고, 상기 베이스의 상면으로부터 상측으로 일정간격 이격배치되는 상부커버;상기 베이스의 상면 둘레를 따라 배치되고, 상기 베이스와 상기 상부커버에 회전가능하게 배치되는 복수의 재배판넬;상기 베이스의 상면 중심에서 상기 상부커버까지 상측으로 수직하게 연장되며, 상기 복수의 재배판넬이 배치되는 방향으로 빛을 조사하는 조명바를 포함하고,상기 복수의 재배판넬 각각의 일측면에는, 식물이 삽입되는 복수의 재배홀더가 배치되고, 상기 복수의 재배홀더가 배치되는 상기 복수의 재배판넬 각각의 일측면은, 상기 조명바를 향하는 제1위치 또는 상기 제1위치에 반대방향을 향하는 제2위치로 배치되는 식물재배기., Ltext: 농업, prediction: 임업
424/1059 Row 424: application_number: 1020190170371, combined_string: invention_title: 바이오플락 사육수를 이용한 자동식물 생산장치 abstract: 일정높이의 수조외벽이 둘러싸며 상부가 개구되고 내부공간이 형성되는 사육수조; 상기 사육 수조의 수조 외벽 어느 한 측면에는 바이오플락 사육수조와 연결되거나 바이오플락 사육수를 공급할 수 있는 바이오플락 사육수 공급관이 설치되며; 상기 사육수조 중심부에는 회전장치가 수조바닥과 수직하게 설치되며; 상기 회전장치의 최상단에는 상부 배양장치가 설치되고 하단부에는 하부 배양장치가 설치되어 회전장치의 설치방향을 중심축으로 회전하며; 상기 사육수조 내부에 설치되어 저장된 바이오플락 사육수의 수류를 형성하는 수류형성장치로 이루어진 바이오플락 사육수를 이용한 자동식물 생산장치를 제공함으로써, 고부가 가치를 지닌 바이오플락 사육수를 이용하여 자동으로 식물을 재배할 수 있어 기존의 수경재배 시 공급되는 양액의 제공이 필요하지 않고, 바이오플락 양식과 식물 동시에 실시 가능하여 양식 효율성을 높일 수 있는 효과가 있다. claims: 일정높이의 수조외벽이 둘러싸며 상부가 개구되고 내부공간이 형성되는 사육수조의 수조 외벽 어느 한 측면에는 바이오플락 사육수조와 연결되거나 바이오플락 사육수를 공급할 수 있는 바이오플락 사육수 공급관이 설치되며; 상기 사육수조 중심부에는 회전장치가 수조바닥과 수직하게 설치되며; 상기 회전장치의 최상단에는 상부 배양장치가 설치되고 하단부에는 하부 배양장치가 설치되어 회전장치의 설치방향을 중심축으로 회전하며; 상기 사육수조 내부에 설치되어 저장된 바이오플락 사육수의 수류를 형성하는 수류형성장치로 이루어진 것을 특징으로 하는 바이오플락 사육수를 이용한 자동식물 생산장치, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

425/1059 Row 425: application_number: 1020190171246, combined_string: invention_title: 수경재배용 흡수 배지 및 이를 이용한 재배장치 abstract: 수경재배용 흡수 배지 및 이를 이용한 재배장치가 개시된다. 본 발명의 일 실시예에 따른 수경재배용 흡수 배지 및 이를 이용한 재배장치는 수직프레임 사이에 다수의 수평프레임이 일정 간격을 두고 다단으로 설치되는 지지프레임; 상기 각 단의 수평프레임 상단에 고정되며, 식물의 재배공간이 마련되는 재배 트레이; 상기 수직프레임에 일정 간격을 두고 설치되어 상기 재배 트레이의 식물에 광량을 조사하는 조명부; 상기 각 단의 수평프레임 하단에 설치되어 상기 재배 트레이에 물안개를 분사하는 급수부를 포함하며, 상기 재배 트레이는 상기 급수부에서 분사되는 물을 흡수하는 흡수 배지를 더 포함한다. claims: 수직프레임 사이에 다수의 수평프레임이 일정 간격을 두고 다단으로 설치되는 지지프레임;상기 각 단의 수평프레임 상단에 고정되며, 식물의 재배공간이 마련되는 재배 트레이;상기 수직프레임에 일정 간격을 두고 설치되어 상기 재배 트레이의 식물에 광량을 조사하는 조명부;상기 각 단의 수평프레임 하단에 설치되어 상기 재배 트레이에 물안개를 분사하는 급수부를 포함하며,상기 재배 트레이는,상기 급수부에서 분사되는 물을 흡수하는 흡수 배지를 더 포함하는, 수경재배용 흡수 배지를 이용한 재배장치.식물을 재배하기 위한 흡수 배지로서,수분이 흡수 또는 투과되는 1차 흡수지;상기 1차 흡수지 하단에 결합되는 고흡수성 폴리머 수지; 및상기 고흡수성 폴리머 수지 하단에 결합되어 상기 수분이 흡수 또는 투과되는 2차 흡수지를 포함하는, 흡수 배지., Ltext: 농업, prediction: 농업
426/1059 Row 426: application_number: 1020190169743, combined_string: invention_title: 식물 재배 장치 abstract: 개시되는 내용의 일 실시예에 따른 식물 재배 장치는 본체, 선반 및 재배용기를 포함하고, 재배용기는 내부에 배지가 형성되며 선반으로부터 물을 공급받는다.구체적으로 본체는 내부에 미리 정해진 크기의 재배공간이 형성되고 재배공간을 열거나 닫는 도어를 포함한다. 선반은 재배공간에 급수 및 배수가 되도록 형성된다. 재배용기는 선반에 놓여 지지되고, 선반으로부터 물을 공급받거나 선반으로 물을 배출할 수 있으며, 내부에 배지가 수용된다.상기 재배용기는 저면에 아래쪽을 향해 돌출되며, 하단에 아래쪽으로 개방되는 개방구를 포함하는 유로가이드 및 유로가이드 내부에 수용되고, 개방구로 유입된 물을 내부로 흡수해 머금는 심지를 포함한다 claims: 내부에 미리 정해진 크기의 재배공간이 형성되고, 상기 재배공간을 열거나 닫는 도어가 형성되는 본체;상기 재배공간에 급수 및 배수가 되도록 형성되는 선반; 및상기 선반에 놓여 지지되고, 상기 선반으로부터 물을 공급받거나 상기 선반으로 물을 배출할 수 있도록 형성되며, 내부에 배지가 수용되는 재배용기;를 포함하고,상기 재배용기는,저면에 아래쪽을 향해 돌출되며, 하단에 아래쪽으로 개방되는 개방구를 포함하는 유로가이드; 및상기 유로가이드 내부에 수용되고, 상기 개방구로 유입된 물을 내부로 흡수해 머금는 심지;를 포함하고,상기 심지는 상기 선반으로부터 공급되는 물을 상기 배지로 전달하는,식물 재배 장치.재배공간을 형성하고 상기 재배공간의 온도 및 습도를 조절하는 본체; 및상기 본체에 수용되는 재배용기;를 포함하고,상기 재배용기는,내측에 제1배지;상기 제1배지의 상면을 덮고 상기 제1배지보다 얇은 두께로 형성되는 파종부; 및상기 파종부의 상면을 덮고 상기 파종부보다 얇은 두께로 형성되는 제2배지;를 포함하는,식물 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

427/1059 Row 427: application_number: 1020190169837, combined_string: invention_title: 관수스탠드형 수경재배장치 abstract: 본 발명은 바닥면에 대해 수직으로 입설되는 지지체에 트레이고정구를 복수개 구비하고 복수개 구비된 트레이고정구에 복수개 재배트레이를 구비하여 지지체가 설치되는 공간에 많은 양의 식물을 식재하여 재배할 수 있기 때문에 공간활용성을 크게 향상시킬 수 있으며, 복수개 재배트레이에 식물의 성장에 필요한 양액을 순환 공급할 수 있어 식물 재배에 따른 편의성과 재배성을 향상시킬 수 있으며 식물측으로 공기를 공급하여 식물성장에 도움을 줌은 물론 공기 실내 정화작용을 어을 수 있으며 재배되는 식물이 그대로 외부로 노출됨에 따라 실내 인테리어 효과는 물론 실내 거주자들로 하여금 심신 안정과 스트레스 해소를 유도할 수 있으며 간단하고 용이한 설치에 의해 설치작업성을 크게 향상시킴은 물론 구성이 간단하여 설치에 따른 비용부담을 최소화 할 수 있는 관수스탠드형 수경재배장치가 개시된다. claims: 지지체와 상기 지지체에 다단으로 구비되는 복수개 재배트레이와 상기 복수개 재배트레이 중 최상단에 위치되는 재배트레이에 양액을 공급하는 양액공급체를 포함하여 이루어진 수경재배장치에 있어서, 상기 지지체(10)는, 바닥면에 대해 수직 입설되는 제1베이스(11a) 및 상기 제1베이스(11a) 일측 상단으로부터 수직연장되는 제1지지벽(11b)을 갖는 제1스탠드(11)와;상기 제1스탠드(11)와 마주보도록 위치되어 바닥면에 대해 수직입설되는 제2베이스(12a) 및 상기 제2베이스(12a) 일측 상단으로부터 수직연장되는 제2지지벽(12b)을 갖는 제2스탠드(12)와;상기 제1지지벽(11b) 상단과 제2지지벽(12b) 상단을 가로방향으로 연결하는 가로지지구(13)와;상기 제1지지벽(11b)과 제2지지벽(12b)을 가로방향으로 연결하되 제1지지벽(11b)과 제2지지벽(12b) 상부에서 하부측으로 다단으로 연결되어 복수개 재배트레이(20)가 각각 거치되어 연결되는 복수개 트레이고정구(14)와;상기 제1베이스(11a)와 제2베이스(12a)를 연결하여 제1베이스(11a)와 제2베이스(12a) 내측에 수용부(15a)를 구비하는 마감부(15)로 구비되고, 상기 양액공급체(30)는,상기 제1베이스(11a)와 제2베이스(12a) 내측에 구비된 수용부(15a)에 수용되는 양액저장부(31)와;상기 양액저장부(31) 상단에 안착되고 호스관통구멍(32a)과 회수구멍(32b)을 갖는 상판(32)과;상기 상판(32)에 구비된 호스관통구멍(32a)측으로 하단이 관통되고 상단은 상기 복수개 트레이고정구(14) 중 최상단에 위치되는 트레이고정구(14a)에 위치되는 공급호스(33)와;상기 공급호스(33)와 연결되어 복수개 트레이고정구(14)에 고정되는 복수개 재배트레이(20) 중 최상단 재배트레이(20a)와 연결되는 분배호스(34)와;상기 양액저장부(31)에 수용되어 상기 호스관통구멍(32a)측으로 관통된 공급호스(33)의 하단이 연결되고 양액저장부(31)에 저장된 양액을 공급호스(33)를 통해 분배호스(34)측으로 공급하는 순환펌프(35)와;상기 상판(32)의 회수구멍(32b)에 일측이 연결되고 상기 복수개 트레이고정구(14)에 고정되는 복수개 재배트레이(20) 중 최하단에 위치되는 재배트레이(20b)와 연결되는 회수호스(36a)가 구비된 회수관(36)으로 구비되어 이루어지는 것을 특징으로 하는 관수스탠드형 수경재배장치., Ltext: 농업, prediction: 임업
428/1059 Row 428: application_number: 1020190168414, combined_string: invention_title: 식물재배장치 및 그 제어방법 abstract: 본 발명의 일 실시예에 따른 식물재배장치에 있어서, 재배할 식물을 수용할 수 있는 공간을 가지는 식물수용부; 상기 식물을 재배하기 위한 적어도 하나의 환경 요소를 제공할 수 있는 환경제공부; 사용자입력부; 및 상기 식물수용부에 수용된 식물의 재배 가용 특성을 식별하고, 상기 사용자입력부를 통해 수신되는 사용자 입력에 따라 상기 식별된 재배 가용 특성의 범위 내의 목표 특성값을 지정하고, 상기 적어도 하나의 환경 요소 중에서 상기 지정된 목표 특성값에 대응하는 환경 요소값을 가지는 환경 요소가 제공되도록 상기 환경제공부를 제어하는 프로세서를 포함할 수 있다. claims: 식물재배장치에 있어서,재배할 식물을 수용할 수 있는 공간을 가지는 식물수용부;상기 식물을 재배하기 위한 적어도 하나의 환경 요소를 제공할 수 있는 환경제공부; 사용자입력부; 및상기 식물수용부에 수용된 식물의 재배 가용 특성을 식별하고,상기 사용자입력부를 통해 수신되는 사용자 입력에 따라 상기 식별된 재배 가용 특성의 범위 내의 목표 특성값을 지정하고,상기 적어도 하나의 환경 요소 중에서 상기 지정된 목표 특성값에 대응하는 환경 요소값을 가지는 환경 요소가 제공되도록 상기 환경제공부를 제어하는프로세서를 포함하는 식물재배장치.식물재배장치의 제어방법에 있어서,재배할 식물을 수용할 수 있는 공간을 가지는 식물수용부에 수용된 식물의 재배 가용 특성을 식별하는 단계;사용자입력부를 통해 수신되는 사용자 입력에 따라 상기 식별된 재배 가용 특성의 범위 내의 목표 특성값을 지정하는 단계; 및식물을 재배하기 위한 적어도 하나의 환경 요소 중에서 상기 지정된 목표 특성값에 대응하는 환경 요소값을 가지는 환경 요소가 제공되도록 환경제공부를 제어하는 단계를 포함하는 식물재배장치의 제어방법.컴퓨터가 읽을 수 있는 코드로서, 전자장치의 제어방법을 수행하는 코드를 포함하는 컴퓨터 프로그램이 저장된 기록매체에 있어서, 상기 식물재배장치의 제어방법은, 재배할 식물을 수용할 수 있는 공간을 가지는 식물수용부에 수용된 식물의 재배 가용 특성을 식별하는 단계;사용자입력부를 통해 수신되는 사용자 입력에 따라 상기 식별된 재배 가용 특성의 범위 내의 목표 특성값을 지정하는 단계; 및식물을 재배하기 위한 적어도 하나의 환경 요소 중에서 상기 지정된 목표 특성값에 대응하는 환경 요소값을 가지는 환경 요소가 제공되도록 환경제공부를 제어하는 단계를 포함하는 것을 특징으로 하는 컴퓨터가 읽을 수 있는 프로그램이 기록된 기록매체., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

429/1059 Row 429: application_number: 1020210110983, combined_string: invention_title: 기능성이 향상된 메밀싹 및 새싹채소의 재배방법 abstract: 본 발명은 약용식물을 선별하고 가공하는 단계; 상기 가공한 약용식물을 혼합한 후 추출 및 희석하여 약용식물 희석액을 제조하는 단계; 및 메밀종자를 파종한 후, 파종 상토에 상기 제조한 약용식물 희석액을 분무하면서 특정 온도 및 광조건에서 재배하는 단계를 포함하는 메밀싹의 재배방법 및 상기 방법으로 재배한 메밀싹에 관한 것이다. claims: (1) 녹차, 짚신나물, 마디풀 및 소리쟁이를 각각 증열처리하고 건조하여 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이를 제조하는 단계;(2) 상기 (1)단계의 제조한 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이와 커피 분말을 혼합하여 약용식물 혼합물을 제조하는 단계;(3) 상기 (2)단계의 제조한 약용식물 혼합물에 물을 첨가하여 추출한 후 여과하여 약용식물 혼합 추출액을 제조하는 단계;(4) 상기 (3)단계의 제조한 약용식물 혼합 추출액에 물을 첨가하여 약용식물 희석액을 제조하는 단계; 및(5) 메밀종자를 파종한 후, 파종 상토에 상기 (4)단계의 제조한 약용식물 희석액을 분무하면서 재배하는 단계를 포함하는 메밀싹의 재배방법.제1항 내지 제3항 중 어느 한 항의 방법으로 재배된 메밀싹., Ltext: 농업, prediction: 임업
430/1059 Row 430: application_number: 1020210041526, combined_string: invention_title: 수경재배 베드 및 뿌리 생장 정보를 이용한 수경재배 방법 abstract: 본 발명은 수경재배 베드에 관한 것으로, 수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어한다. claims: 수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어하고, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 1]을 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 수경재배 베드. [수식 1] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.) 수경재배 장치에서 식물이 수용되는 베드로 양액을 공급하는 단계; 및 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 베드의 측면 상부에 형성된 제1 배출구 또는 상기 베드의 하단에 형성된 제2 배출구를 통해 배출되도록 밸브를 제어하는 단계;를 포함하되, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 2]를 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 뿌리 생장 정보를 이용한 수경재배 방법. [수식 2] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.), Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

431/1059 Row 431: application_number: 1020210005654, combined_string: invention_title: 새싹보리순 자동 수확장치 abstract: 본 발명은 적어도 하나의 휠(112)이 장착되며, 구동모듈(114)이 내장되는 베이스프레임(110); 상기 베이스프레임(110) 상에 위치되는 수확모듈(120)로서, 전방을 향해 소정의 기울기를 갖도록 형성된 컨베이어부(122) 및 상기 컨베이어부(122)의 전단부 측에 위치되어 하방의 예취대상물을 예취시키는 예취부(124)를 포함하며, 상기 컨베이어부(122)의 전단부 측으로부터 후단부 측으로 예취물을 이송시키는, 수확모듈(120); 상기 베이스프레임(110) 상에 위치되되, 상기 컨베이어부(122)의 후단부 측에 형성되며, 수거수단이 위치되는 공간을 제공하는 포집공간부(130)로서, 상기 컨베이어부(122)에 의해 이송된 예취물을 상기 수거수단으로 포집시키는, 포집공간부(130); 및 상기 베이스프레임(110)의 후단에 위치되며, 상기 휠(112) 및 수확모듈(120)의 동작을 제어하는 제어모듈(140); 을 포함하는, 자동 수확장치를 제공한다. claims: 폭 방향으로 한 쌍의 휠(112)이 장착되며, 유압펌프(114b) 및 상기 유압펌프(114b)와 연결된 한 쌍의 유압모터(114a)를 구비하는 구동모듈(114)이 내장되는 베이스프레임(110); 상기 베이스프레임(110) 상에 위치되는 수확모듈(120)로서, 전방을 향해 소정의 기울기를 갖도록 형성된 컨베이어부(122) 및 상기 컨베이어부(122)의 전단부 측에 위치되어 하방의 예취대상물을 예취시키는 예취부(124)를 포함하며, 상기 컨베이어부(122)의 전단부 측으로부터 후단부 측으로 예취물을 이송시키는, 수확모듈(120); 상기 베이스프레임(110) 상에 위치되되, 상기 컨베이어부(122)의 후단부 측에 형성되며, 수거수단이 위치되는 공간을 제공하는 포집공간부(130)로서, 상기 컨베이어부(122)에 의해 이송된 예취물을 상기 수거수단으로 포집시키는, 포집공간부(130); 및 상기 베이스프레임(110)의 후단에 위치되며, 상기 휠(112) 및 수확모듈(120)의 동작을 제어하는 제어모듈(140);을 포함하고,상기 베이스프레임(110)에서 포집공간부(130)의 전단에 결합되되, 상기 베이스프레임(110)의 폭방향을 기준으로, 양측 단부에서, 수직방향으로 소정의 길이만큼 연장되는 트러스프레임(150)을 더 포함하고, 상기 트러스프레임(150)의 상부에는, 상기 컨베이어부(122)가 결합되며,상기 컨베이어부(122)는,상기 예취부(124)가 전단 측에서 지면과 인접한 부위에 구비되고, 상기 예취부(124)로부터 후방을 향해 상향 경사로 형성되는 경사컨베이어(122a) 및 상기 경사컨베이어(122a)의 후단으로부터 후방을 향해 수평방향으로 연장 형성되고 상기 트러스프레임(150)에 결합되는 수평컨베이어(122b)로 구분되고,상기 경사컨베이어(122a) 및 상기 수평컨베이어(122b)는 단일의 컨베이어벨트로 형성되며, 상기 단일의 컨베이어벨트는 상기 구동모듈(114)과 연결된 롤러모듈의 회전에 의해 동작되며,상기 베이스프레임(110)의 전방 측은,상기 경사컨베이어(122a)의 경사에 대응되는 경사부(110a)가 형성되며, 상기 경사부(110a)의 상부에는 상기 경사컨베이어(122a)가 위치되되, 상기 경사부(110a)의 전단부 및 상기 경사컨베이어(122a)의 전단부 사이에는 완충장치가 결합된 유압실린더 구조로 형성되고 상기 유압펌프(114b)에 연결되어 동력을 전달받는 리프팅부(116)가 구비되어 지면으로부터 상기 예취부(124)의 높이를 조절하는,자동 수확장치., Ltext: 농업, prediction: 임업
432/1059 Row 432: application_number: 1020200158820, combined_string: invention_title: 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치 abstract: 실시예들은 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치에 관련된 것이다. 구체적으로 이 장치는, 작물의 하부에 위치하여 작물을 지지하며, 상부에서 하부로 갈수록 내측 단면적이 증가하는 형태의 지지체를 포함하고, 상기 지지체는 적어도 부분적으로 투명 재질로 구성된다. 본 장치에 의하면 작물의 뿌리 전체에 대한 이미지 데이터를 효과적으로 획득하여 최적의 생장환경을 위한 인공지능 학습 데이터로 활용할 수 있는 이점이 있다. claims: 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치로서,상기 장치는,작물의 하부에 위치하여 작물을 지지하며, 상부에서 하부로 갈수록 내측 단면적이 증가하는 형태의 지지체를 포함하고,상기 지지체는 적어도 부분적으로 투명 재질로 구성되고,상기 지지체 위에 위치하며, 상기 작물의 줄기를 고정시키는 줄기 고정부; 및상기 지지체 아래에 위치하며, 상기 지지체의 내측면을 향해 촬영함으로써 작물의 줄기에 대한 영상을 획득하는 센싱부를 포함하고,상기 지지체는,상단 지지체;상기 상단 지지체 아래에 배치되는 하단 지지체; 및상기 상단 지지체와 상기 하단 지지체사이에 양액이 통과할 수 있는 양액 급수 공간을 포함하고,상기 상단 지지체와 하단 지지체를 연결하고, 상기 양액 급수 공간에 양액을 공급하는 연결부재를 더 포함하되,상기 연결부재는, 상기 상단 지지체에 체결되는 제1 연결부;상기 하단 지지체에 체결되는 제2 연결부; 및상기 제1 연결부와 제2 연결부 사이에 형성되며, 제1 연결부 또는 제2 연결부의 내측에 형성된 급수관을 통해 유입된 양액을 상기 양액 급수 공간으로 가이드하는 가이드부를 포함하는 것을 특징으로 하는 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

433/1059 Row 433: application_number: 1020200130915, combined_string: invention_title: 감초 및 뿌리식물 재배용 컨테이너 abstract: 본 발명은 감초 및 뿌리식물 재배용 컨테이너에 관한 것으로, 보다 상세하게는 대량의 뿌리식물을 효과적으로 재배할 수 있도록 함은 물론 토양이 채워져 뿌리식물이 재배되는 공간부로 유입된 물이나 약액의 배출을 용이하게 이뤄 뿌리식물이 썩게 되는 것을 방지할 수 있도록 하는 감초 및 뿌리식물 재배용 컨테이너에 관한 것이다. 본 발명은 다수개의 격판이 격자상으로 배치되게 조립되어 각각의 격판 사이에 토양이 채워지는 공간부(130)가 형성된 격판부(100); 상기 격판부(100)를 감싸도록 형성되되 각각의 격판 상단이 끼워질 수 있도록 하는 조립끼움공(210)이 형성되고, 길이방향 측면 하부에 메인배수공(220)이 형성된 메인바디부(200); 상기 메인바디부(200)의 내부 하측에 길이방향을 따라 설치되되 다수개의 이너배수공(410)이 일정간격으로 형성되어 상기 공간부(130)로 유입된 물이나 약액이 상기 이너배수공(410)을 통해 내부로 유입된 후, 상기 메인배수공(220)을 통해 외부로 배출될 수 있도록 하는 배수가이드유닛(400);을 포함하여 구성되는 것을 특징으로 한다. claims: 다수개의 격판이 격자상으로 배치되게 조립되어 각각의 격판 사이에 토양이 채워지는 공간부(130)가 형성된 격판부(100); 상기 격판부(100)를 감싸도록 형성되되 각각의 격판 상단이 끼워질 수 있도록 하는 조립끼움공(210)이 형성되고, 길이방향 측면 하부에 메인배수공(220)이 형성된 메인바디부(200); 상기 메인바디부(200)의 내부 하측에 길이방향을 따라 설치되되 다수개의 이너배수공(410)이 일정간격으로 형성되어 상기 공간부(130)로 유입된 물이나 약액이 상기 이너배수공(410)을 통해 내부로 유입된 후, 상기 메인배수공(220)을 통해 외부로 배출될 수 있도록 하는 배수가이드유닛(400);을 포함하여 구성되고, 상기 격판부(100)의 상측에는 물이나 약액이 유동하는 유동배관유닛(300)이 안착되게 설치되어 상기 유동배관유닛(300)에서 배출되는 물이나 약액이 상기 공간부(130)로 유입될 수 있도록 이루어지며, 상기 유동배관유닛(300)은 물이나 약액이 수용되는 안착바디(310)와, 상기 안착바디(310)의 폭방향 양측으로 연장된 상태로 상기 공간부(130)로 물이나 약액이 배출될 수 있도록 가이드하는 배출가이드구(320)를 포함하여 구성되고, 상기 배출가이드구(320)에는 물이나 약액이 상기 공간부(130)의 상측방향으로 배출될 수 있도록 하는 상방분출공(321)과 물이나 약액이 상기 공간부(130)의 하측방향으로 유동할 수 있도록 하는 하방분출튜브(322)가 마련된 것을 특징으로 하는 감초 및 뿌리식물 재배용 컨테이너., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

434/1059 Row 434: application_number: 1020200106506, combined_string: invention_title: 고구마 재배 방법 abstract: 본 발명은 비닐하우스에서 키운 길이가 25 cm보다 크거나 같고 45 cm보다 작거나 같은 고구마 종묘를 뿌리로부터 첫 번째 마디를 45 도의 각도로 잘라낸 고구마 종묘를 준비하는 고구마 종묘 준비 단계; 상기 고구마 종묘의 줄기 부분을 21 ℃ 온도에서 36 시간 동안 물에 침지시키는 침지 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 고구마 종묘를 심기 전 10일에서 12일 전에 제초제를 살포하여 제초하는 제 1 제초 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 1 ha당 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료 250 ~ 350 kg을 공급하는 복합비료 공급 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 두둑폭 50 ~ 70 ㎝, 두둑높이 50 ~ 60 ㎝ 의 두둑을 형성하는 두둑 형성 단계; 상기 두둑의 상부에 물 또는 영양제를 공급할 수 있는 점적 테이프를 설치하고 상기 두둑 중 인접한 두 개의 두둑과 가운데 고랑을 비닐로 멀칭하고 상기 멀칭된 비닐에 고구마 종묘를 심기 위한 구멍을 뚫는 멀칭 단계; 상기 구멍에 물에 침지시킨 고구마 종묘의 줄기 세 번째 마디에서 다섯 번째 마디까지 삽입하여 고구마 종묘를 심는 정식 단계; 상기 고구마 종묘를 심은 후 제초제를 살포하는 제 2 제초 단계; 및 상기 고구마 종묘를 심은 토양에 1 ha당 150 ~ 250 kg 의 질산암모늄과 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료를 70 ~ 150 kg을 혼합한 혼합비료를 생육기간 중 3회 내지 6회 공급하는 혼합 비료 공급 단계;를 포함하는 사질 토양에서 고구마 재배 방법에 관한 것이다. claims: 비닐하우스에서 키운 길이가 25 cm보다 크거나 같고 45 cm보다 작거나 같은 고구마 종묘를 뿌리로부터 첫 번째 마디를 45 도의 각도로 잘라낸 고구마 종묘를 준비하는 고구마 종묘 준비 단계;상기 고구마 종묘의 줄기 부분을 21 ℃ 온도에서 36 시간 동안 물에 침지시키는 침지 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 고구마 종묘를 심기 전 10일에서 12일 전에 제초제를 살포하여 제초하는 제 1 제초 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 1 ha당 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료 250 ~ 350 kg을 공급하는 복합비료 공급 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 두둑폭 50 ~ 70 ㎝, 두둑높이 50 ~ 60 ㎝ 의 두둑을 형성하는 두둑 형성 단계;상기 두둑의 상부에 물 또는 영양제를 공급할 수 있는 점적 테이프를 매립하여 설치하고 상기 두둑 중 인접한 두 개의 두둑과 가운데 고랑을 비닐로 멀칭하고 상기 멀칭된 비닐에 고구마 종묘를 심기 위한 구멍을 뚫는 멀칭 단계;상기 구멍에 물에 침지시킨 고구마 종묘의 줄기 세 번째 마디에서 다섯 번째 마디까지 삽입하여 고구마 종묘를 심는 정식 단계;상기 고구마 종묘를 심은 후 제초제를 살포하는 제 2 제초 단계; 및상기 고구마 종묘를 심은 토양에 1 ha당 150 ~ 250 kg 의 질산암모늄과 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료를 70 ~ 150 kg을 혼합한 혼합비료를 생육기간 중 3회 내지 6회 공급하는 혼합 비료 공급 단계;를 포함하되, 상기 멀칭 단계에서 멀칭하는 방법은 상기 두둑의 상부를 투명한 폴리에틸렌 재질의 비닐로 멀칭하고, 상기 두둑의 양옆면은 불투명한 폴리에틸렌 재질의 비닐로 멀칭하는 것을 특징으로 하고,상기 정식 단계의 고구마 종묘 1 ha당 40,000 ~ 50,000 개로 심는 것을 특징으로 하며, 상기 고구마 종묘의 종류는 호박고구마 또는 밤고구마인 것을 특징으로 하는,사질 토양에서 고구마 재배 방법., Ltext: 농업, prediction: 임업
435/1059 Row 435: application_number: 1020200074550, combined_string: invention_title: 식물재배시스템의 차폐지지장치 abstract: 본 발명은 실내에서 식물재배에 필요한 공간의 제약을 해결하고 아울러, 미적감각을 고조하기 위하여, 식물을 천장에 매달아 아래를 향해 자라도록 하는 방법으로 재배 공간을 확보하는 식물재배시스템과 관련한다. 더욱 구체적으로, 식물재배시스템의 쳄버는 식물의 몸체가 수직방향으로 배치될 수 있도록 수직으로 형성된 개구부를 갖고, 상기 개구부에는 식물 줄기가 통과하여 안착될 차폐지지부가 부착되고, 상기 차폐지지부는 차폐지지몸체 및 차폐지지슬롯을 포함하고, 상기 차폐지지부에의 차폐지지몸체에는 조임수단이 구비된다. claims: 식물재배시스템에 구비되는 것으로서, 상기 식물재배시스템은 식물 뿌리를 가두는 쳄버를 포함하고, 상기 쳄버의 개구부에는 식물 줄기가 통과하여 안착될 차폐지지부가 서로 대응하는 형태를 취해서 마주보게 복수 배치되며,상기 차폐지지부는 차폐지지몸체 및 차폐지지슬롯을 포함하되,상기 차폐지지부의 차폐지지몸체에는 조임수단이 구비되고,상기 조임수단은 조임용 돌기 및 조임용 밴드를 포함하고,상기 상기 조임용 돌기는 상기 차폐지지몸체 위에 수직으로 돌출되어 제공되고,상기 조임용 밴드는 탄성력을 갖는 고리 형태로 제공되어서,상기 조임용 돌기에 상기 조임용 밴드가 걸림이 되어 탄성력으로 조일 수 있도록 설치되는 것을 특징으로 하는 식물재배시스템의 차폐지지장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

436/1059 Row 436: application_number: 1020200036679, combined_string: invention_title: 산양산삼 재배방법 abstract: 본 발명은 산양산삼 재배방법에 관한 것으로, 보다 구체적으로는 멧돼지, 고라니, 노루, 너구리, 오소리, 들쥐 또는 조류로부터 작물을 보호하기 위한 산양산삼 재배방법에 관한 것으로 본 발명의 실시예는 하부금속그물망에 의해 땅 속에서 침입하는 유해조수로부터 작물의 뿌리를 보호하고 상부금속그물망에 의해 땅 위로 침입하는 유해조수로부터 씨앗과 작물을 보호하며, 하부금속그물망과 상부금속그물망의 연결을 탈부착고리를 이용하여 수확시에는 보호장치를 쉽게 분리하여 편리하게 수확할 수 있으며, 금속선재가 포함된 금속그물망을 이용하여 장기간 별도의 유지보수 없이 사용이 가능하고, 작물이 재배되는 토양공간을 금속그물망으로 폐쇄하므로 경사지의 토사와 작물의 유실을 방지할 수 있고, 금속그물망을 이용하므로 면적에 따라 금속그물망의 크기를 쉽게 적용하여 작물재배할 수 있으므로 소량의 작물재배부터 대량의 작물재배까지 모두 적용이 가능한 효과가 있다. claims: 토양에 작물재배장치를 설치하여 산삼종자를 파종하거나 묘삼을 이식하여 생장시켜 재배하고 수확하는 산양산삼의 재배 방법에 있어서,상기 작물재배장치는 금속선재를 포함하여 쉽게 구부릴 수 있는 피복된 금속그물망으로 형성된 상부금속그물망과 하부금속그물망을 포함하며,상기 하부금속그물망을 토양 아래에 오목하게 설치하여 토양공간을 형성하는 하부금속그물망설치단계와;상기 하부금속그물망 위에 흙을 덮어서 상기 토양공간에 흙을 채우는 제1차복토단계와;상기 제1차복토단계에서 채워진 흙의 표면에 산삼종자를 파종하거나 묘삼을 이식하는 식재단계와;상기 하부금속그물망의 가장자리에 연결되고 토양공간 위를 덮어서 토양공간을 폐쇄하는 판형의 상기 상부금속그물망을 설치하는 상부금속그물망설치단계와;상기 상부금속그물망 위에 흙을 덮는 복토단계와;상기 씨앗의 발아에 의해 발생한 산삼이나 식재된 산삼묘를 재배하는 재배단계와;상기 산양산삼의 재배가 종료된 후 상부금속그물망을 분리하는 분리단계와;상기 산양산삼을 수확하는 수확단계를 포함하며,상기 하부금속그물망설치단계에서 상부금속그물망에 연결되지 않은 말단부인 하부날개를 토양 표면에 배치하고;상기 상부금속그물망설치단계에서 하부금속그물망에 연결되지 않은 말단부인 상부날개를 상기 하부날개위를 덮으며,상기 상부금속그물망과 하부금속그물망이 안쪽의 토양을 폐쇄하는 것을 특징으로 하는 산양산삼 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

437/1059 Row 437: application_number: 1020200029298, combined_string: invention_title: 스마트기기를 이용한 식물재배시스템 abstract: 본 발명은 스마트 수단을 이용하여 자동으로 식물재배가 가능하며, 일상생활에 필요한 조명까지 종합적으로 함께 이루어질 수 있는 시스템에 관한 것으로서,천장에 고정되며 식물이 배치되는 재배유닛; 및 식물에 양액을 공급하는 공급유닛;을 포함하여 이루어지되,상기 재배유닛은,복수로 구비되며, 식물 뿌리가 위를 향하고 식물 잎이 아래를 향하여 재배될 수 있도록 지지를 하며, 설치 및 교환이 가능하도록 모듈화된 셀 단위로 제공되는 단위모듈; 및 식물에 광에너지를 공급하여 식물재배를 촉진하며, 일상생활에 필요한 조명까지 동시에 제공할 광원설비;를 포함하고,상기 공급유닛은,식물재배를 위한 양액을 저장하는 메인탱크; 및 저장된 양액을 상기 단위모듈에 이송하는 이송관;을 포함하여 이루어진다. claims: 스마트기기를 이용하여 자동으로, 역전된 상태로 재배되는 식물(pl)을 관리하며 동시에, 사무실 및 주거시설에 있어서 필요한 조명까지 함께 제공할 수 있는 스마트기기를 이용한 식물재배시스템으로서 재배유닛(100); 및 공급유닛(200);을 포함하고,재배유닛(100)은 단위모듈(110); 및 광원설비(120);를 포함하여서, 식물이 배치되며 빛을 공급하고,공급유닛(200)은 메인탱크(210); 및 이송관(220);을 포함하여서 식물재배를 위한 양액을 공급하고,단위모듈(110)은 하우징(111); 쳄버(112); 양액통(113); 포그발생장치(114); 기류발생팬(115); 및 재배유닛측 제어계측수단(116);를 포함하고,하우징(111)은 내부를 밀폐하며, 저면에 광원설비(120)의 빛을 반사시킬 반사판(111a)을 함께 구비하고,쳄버(112)는 하우징(111)의 저면에 배치되고, 수직방향으로 개구되어 식물을 고정하고,양액통(113)은 단위모듈(110)의 내부에 구비되어서 메인탱크(210)에 저장된 양액을 이송관(220)을 통하여 전달받아 일시 저장하고,포그발생장치(114)는 단위모듈(110)에 배치된 식물에 양액을 공급하기 위하여, 양액통(113)에 일시 저장된 양액을 양액포그(wa3) 형태로 만들고,기류발생팬(115)은 모터팬으로 제공되고, 외부의 공기를 양액통(113)에 불어넣어 기류를 발생하고, 기류를 따라 양액포그(wa3)가 이동하여 식물 뿌리(pl1)에 양액을 공급하도록 작동하고, 기류발생팬(115)의 강약 조절로 양액포그(wa3)의 공급량이 조절되고,재배유닛측 제어계측수단(116)은 단위모듈(110)에 배치된 식물재배가 용이하도록 온습도를 감지하여 무선네트워크를 통하여 모니터링하고, 식물재배에 필요한 기능제어를 수행하고,광원설비(120)는 광원프레임(121); 및 LED 전등 램프;를 포함하고,광원프레임(121)은 격자 형태를 취해서 단위모듈(110)의 저면과 떨어져 위치되며, 고정대(121a)를 통하여 천장에 고정되고, 광원프레임(121)에 단위모듈(110)이 고정되고,LED 전등 램프는 단위모듈(110)을 향하여 아래에서 위로 빛을 조사하여 식물에 광에너지를 제공하도록 설치되고,메인탱크(210)는 탱크몸체(211); 이송펌프(212); 및 공급유닛측 제어계측수단(213)을 포함하고,탱크몸체(211)는 내부를 밀폐하며 양액을 저장하는 탱크 형태를 취하고,이송펌프(212)는 이송관 일단(222)에 구비되어서 탱크몸체(211)에 저장된 양액을 이송관(220)으로 보내는 동력원의 역할을 수행하고,공급유닛측 제어계측수단(213)은 메인탱크(210)의 기능 상태을 제어하고 메인탱크(210)의 내측벽에 수위 수준을 감지하도록 설치된 센서를 포함하고,이송관(220)은 이송관 몸체(221); 이송관 일단(222); 이송관 타단(223);을 포함하여, 저장된 양액을 단위모듈(110)에 이송하며, 이송관(220)은 건물벽체에 고정브라킷으로 고정되고,이송관 몸체(221)는 파이프 형태를 취하여, 이송펌프(212)의 작동에 의하여 양액을 양액통(113)으로 이송하고,이송관 일단(222)은 파이프 형태의 일단으로서 메인탱크(210)에 위치되어, 이송펌프(212)가 작동하면 저장된 양액이 인입되는 입구의 역할을 수행하고,이송관 타단(223)은 파이프 형태의 타단으로서 단위모듈(110)에 위치되고 이송된 양액이 배출되는,것을 특징으로 하는 스마트기기를 이용한 식물재배시스템., Ltext: 농업, prediction: 농업
438/1059 Row 438: application_number: 1020200021705, combined_string: invention_title: 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법 abstract: 본 발명은 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법에 관한 것으로, 보다 구체적으로는 용수의 pH 조절, LED 광조사 조절, 자극제 처리를 통한 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법에 관한 것이다.본 발명의 일 실시예에 따른 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법은 보리 종자를 종자 트레이 상에 준비하는 제 1단계; 상기 트레이 상에 위치된 보리 종자에 pH 6 내지 7의 용수를 이용하여 수분을 공급하는 제 2단계; 상기 수분이 공급된 보리 종자를 암처리 및 적색 LED 광처리를 실시하며 발아시키는 제 3단계; 상기 발아된 보리를 청색 LED 광처리를 실시하고, 자극제를 공급하며 재배하는 제 4단계; 상기 LED 광처리 및 자극제의 공급을 수행한 다음 1 내지 3일 이후 보리를 수확하는 제 5단계;를 포함하는 것을 특징으로 한다. claims: 보리 종자를 종자 트레이 상에 준비하는 제 1단계;상기 트레이 상에 위치된 보리 종자에 pH 6 내지 7의 용수를 이용하여 수분을 공급하는 제 2단계;상기 수분이 공급된 보리 종자를 암처리 및 적색 LED 광처리를 실시하며 발아시키는 제 3단계;상기 발아된 보리를 청색 LED 광처리를 실시하고, 자극제를 공급하며 재배하는 제 4단계;상기 LED 광처리 및 자극제의 공급을 수행한 다음 1 내지 3일 이후 보리를 수확하는 제 5단계;를 포함하는 것을 특징으로 하는 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

439/1059 Row 439: application_number: 1020200019765, combined_string: invention_title: 뿌리 식물 재배 장치 abstract: 본 발명에 따른 뿌리 식물 재배 장치는, 내부에 배양토가 채워지고, 바닥에 배수공이 형성된 바닥 있는 통모양의 육묘 용기; 및 상하 양단부가 개방되어, 상단부는 육묘 용기에 채워진 배양토 위로 노출되고, 하단부는 배양토에 소정 깊이로 박혀서, 상단부로부터 공급되는 물 또는 양액이 하단부로부터 소정 깊이의 배양토 안으로 공급되도록 구성된 급수 파이프를 구비하는 육묘 재배기를 포함한다. 본 발명에 따르면 뿌리 식물의 상품성(뿌리의 직근성과 굵기)을 현저하게 향상시키고, 재배 기간을 획기적으로 단축시킬 수 있다. claims: 내부에 배양토가 채워지고, 바닥에 배수공이 형성된 바닥 있는 통모양의 육묘 용기; 및상하 양단부가 개방되어, 상단부는 상기 육묘 용기에 채워진 상기 배양토 위로 노출되고, 하단부는 상기 배양토에 소정 깊이로 박혀서, 상기 상단부로부터 공급되는 물 또는 양액이 상기 하단부로부터 상기 소정 깊이의 배양토 안으로 공급되도록 구성된 급수 파이프를 구비하는 육묘 재배기를 포함하는 뿌리 식물 재배 장치.내부에 양액이 채워지고, 바닥 있는 통모양의 수경 용기; 및 상기 수경 용기의 상부에 배치되고, 뿌리 식물의 뿌리가 아래로 늘어뜨려져 상기 뿌리의 하단부가 상기 수경 용기에 채워지는 양액에 잠기도록 상기 뿌리의 상단부를 고정하여 지지하는 지지부를 구비하는 수경 재배기를 포함하는 뿌리 식물 재배 장치., Ltext: 농업, prediction: 임업
440/1059 Row 440: application_number: 1020200019766, combined_string: invention_title: 뿌리 식물 재배 방법 abstract: 본 발명에 따른 뿌리 식물 재배 방법은, 소정 길이의 뿌리를 가지는 뿌리 식물을 재배하는 방법으로서, 뿌리 식물의 뿌리가 아래로 늘어뜨려져 뿌리 식물의 뿌리의 하단부가 수경 용기에 채워지는 양액에 잠기도록 뿌리 식물의 뿌리 상단부를 고정하여 지지한 상태에서, 수경 용기에 양액을 공급함으로써 뿌리 식물의 뿌리를 굵기 성장시키는 수경 재배 단계를 포함한다. 본 발명에 따르면 뿌리 식물의 상품성(뿌리의 굵기)을 현저하게 향상시키고, 재배 기간을 획기적으로 단축시킬 수 있다. claims: 소정 길이의 뿌리를 가지는 뿌리 식물을 재배하는 방법으로서,상기 뿌리 식물의 뿌리가 아래로 늘어뜨려져 상기 뿌리의 하단부가 수경 용기에 채워지는 양액에 잠기도록 상기 뿌리의 상단부를 고정하여 지지한 상태에서, 상기 수경 용기에 양액을 공급함으로써 상기 뿌리를 굵기 성장시키는 수경 재배 단계를 포함하는 뿌리 식물 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

441/1059 Row 441: application_number: 1020200018010, combined_string: invention_title: 커피콩 수확용 드럼형 수레 abstract: 본 발명은 내부에 제1수용공간(110)이 형성된 제1드럼바퀴(100); 일면이 상기 제1드럼바퀴(100)의 일면과 마주보도록 이격 배치되되, 내부에 제2수용공간(210)이 형성된 제2드럼바퀴(200); 상기 제1드럼바퀴(100) 및 제2드럼바퀴(200) 사이를 연결하는 연결부(300); 및 상기 연결부(300) 상에 고정되되, 커피콩이 투입되도록 투입구(420)가 형성된 가이드부(400);를 포함하며, 제1드럼바퀴(100) 및 제2드럼바퀴(200)는 상기 연결부(300) 상에서 회전 가능하게 결합되되, 상기 연결부(300)는, 상기 가이드부(400)의 투입구(420)로 투입된 커피콩이 상기 제1드럼바퀴(100)의 제1수용공간(110) 또는 제2드럼바퀴(200)의 제2수용공간(120)으로 이송되도록 분배구(330)가 형성되어, 전체 부피가 줄어 좁은 공간에서도 사용가능하고, 커피콩을 보다 용이하게 보관할 수 있으면서, 많은 양의 커피콩을 수용하는 커피콩 수확용 드럼형 수레(1000)에 관한 것이다. claims: 내부에 제1수용공간(110)이 형성된 제1드럼바퀴(100);일면이 상기 제1드럼바퀴(100)의 일면과 마주보도록 이격 배치되되, 내부에 제2수용공간(120)이 형성된 제2드럼바퀴(200);상기 제1드럼바퀴(100) 및 제2드럼바퀴(200) 사이를 연결하는 연결부(300); 및상기 연결부(300) 상에 고정되되, 커피콩이 투입되도록 투입구(420)가 형성된 가이드부(400);를 포함하며,제1드럼바퀴(100) 및 제2드럼바퀴(200)는 상기 연결부(300) 상에서 회전 가능하게 결합되되,상기 연결부(300)는,상기 가이드부(400)의 투입구(420)로 투입된 커피콩이 상기 제1드럼바퀴(100)의 제1수용공간(110) 또는 제2드럼바퀴(200)의 제2수용공간(210)으로 이송되도록 분배구(330)가 형성되는 커피콩 수확용 드럼형 수레(1000)., Ltext: 농업, prediction: 임업
442/1059 Row 442: application_number: 1020200005340, combined_string: invention_title: 콩 콤바인의 수확물 이송장치 abstract: 본 발명은 예취장치의 수거포켓에 구비되는 오거드럼의 회전을 통해 유입되는 수확물을 탈곡공간으로 이송시 과도한 수확물의 유입에 따른 이송작업의 중단시에도 상기 과도하게 유입된 작물을 상기 수거포켓의 수거공간으로 역배출하여 이송공간에서 작물의 과도한 수용상태를 해제하도록 함에 따라 안정적으로 수확물의 이송작업을 수행할 수 있도록 함은 물론 수확 과정에서 안전사고의 위험성이 낮아지도록 한 것이다,이를 위해 본 발명은, 콤바인 본체 내부에 시설되는 예취장치의 수거공간과 탈곡장치의 탈곡공간을 공간적으로 연결하는 이송공간이 구비된 이송몸체와; 상기 이송몸체의 이송공간에서 상기 수거공간과 상기 탈곡공간을 경유하는 순환경로를 형성하도록 된 순환수단과; 상기 순환수단을 통해 상기 순환경로를 순환하면서 상기 수거공간에서 투입되는 수확물을 포집하여 상기 탈곡공간으로 가압하면서 이송시키도록 된 이송체들과; 상기 순환수단으로 회전력을 전달하도록 된 주회전축을 선택적으로 역회전시키도록 된 역회전수단;을 포함하여 이루어지는 것을 특징으로 하는 콩 콤바인의 수확물 이송장치를 제공한다. claims: 콤바인 본체 내부에 시설되는 예취장치의 수거공간과 탈곡장치의 탈곡공간을 공간적으로 연결하는 이송공간이 구비된 이송몸체와;상기 이송몸체의 이송공간에서 상기 수거공간과 상기 탈곡공간을 경유하는 순환경로를 형성하도록 된 순환수단과;상기 순환수단을 통해 상기 순환경로를 순환하면서 상기 수거공간에서 투입되는 수확물을 포집하여 상기 탈곡공간으로 가압하면서 이송시키도록 된 이송체들과;상기 순환수단으로 회전력을 전달하도록 된 주회전축을 선택적으로 역회전시키도록 된 역회전수단;을 포함하여 이루어지는 것을 특징으로 하는 콩 콤바인의 수확물 이송장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

443/1059 Row 443: application_number: 1020200005354, combined_string: invention_title: 새싹보리 재배방법 및 그에 의해 재배된 새싹보리 abstract: 본 발명은 새싹 보리 재배방법에 관한 것으로서, 발아에 적합한 보리를 선별하고 세척하는 선별 및 세척단계와, 상기 선별 및 세척된 보리를 기능성 수용액에 침지시킨 후 불리는 불림단계와, 상기 불린 보리를 발아시키는 발아단계와, 상기 발아된 보리를 식재하여 생육하는 생육단계와, 상기 생육된 새싹 보리를 채취하고 포장하는 채취 및 포장단계를 포함하여 이루어지는 것을 특징으로 한다. 상기의 방법으로 재배된 새싹보리는 한약재, 법제 유황, 천연 항균제가 포함된 기능성 수용액, 기능성 상토를 보리의 발아 및 생육과정에서 사용함에 따라 한약재, 법제 유황 및 천연 항균제의 유효한 성분이 자연스럽게 흡수되어, 새싹 보리를 섭취하는 것만으로도 새싹보리의 유효한 성분과 더불어 한약재, 법제 유황 및 천연 항균제의 유효한 성분을 함께 섭취할 수 있는 장점이 있다. claims: 발아에 적합한 보리를 선별하고 세척하는 선별 및 세척단계(S10); 상기 선별 및 세척된 보리를 기능성 수용액에 침지시킨 후, 15~22℃의 온도에서 60~72시간 동안 불리는 불림단계(S20);상기 불린 보리를 온도 28~30℃, 습도 75~80%의 범위를 유지시키면서, 20~30시간 동안 발아시키는 발아단계(S30);상기 발아된 보리를 식재하여 생육하는 생육단계(S40); 상기 생육된 새싹 보리를 채취하고 포장하는 채취 및 포장단계(S50);를 포함하여 이루어지되, 상기 불림단계(S20)의 기능성 수용액은, 물 100중량부에, 한약재 추출물 20~30중량부, 법제 유황분말 2~3중량부, 천연 항균제 5~7중량부를 혼합하여 제조하되,상기 한약재 추출물은, 가시오가피, 두충, 천궁, 황기, 황궁, 당귀, 작약, 감초, 계피, 갈근, 숙지황, 복령, 백출, 칡, 더덕, 인삼, 홍삼 중에서 선택된 하나 이상을 70~80℃의 온도에서 48~72시간 동안 건조하여 150~200mesh의 크기로 분쇄한 후, 상기 건조 및 분쇄된 혼합물 100중량부에 물 800~1,000중량부를 혼합하고 80~100℃의 온도에서 2~4시간 가열하여 여과한 것이고,상기 법제 유황분말은,(i) 유황을 120~160℃의 온도에서 30~50분 동안 가열하여 용융시키는 용융단계;(ii) 상기 용융된 유황 100중량부에 지장수 300~700중량부, 무즙 10~20중량부, 엄나무 추출물 3~5중량부, 제올라이트 분말 30~50중량부를 혼합하고 100~120℃의 온도에서 1~2시간 동안 가열한 후, 냉각시켜 제독하는 제독단계;(iii) 상기 제독된 유황을 분리하여 건조기에 넣고 함수율이 5% 이하가 되도록 건조하는 분리 및 건조단계;(iv) 상기 i) 용융단계, (ii) 제독단계, (iii) 분리 및 건조단계를 5~10회 반복하는 반복단계;(v) 상기 반복단계를 거쳐 분리 및 건조된 유황을 250~300mesh의 크기로 분쇄하는 분쇄단계;를 포함하여 제조되며,상기 천연 항균제는,백리향 추출물 100중량부, 비자나무 오일추출물 30~50중량부를 혼합한 것이고,상기 생육단계(S40)는, 상기 발아된 보리를 기능성 상토가 수용된 모종판에 식재하여 7~10일 동안 생육하되, 상기 기능성 상토는, 원예용 상토 100중량부에, 상기 불림단계(S20)에서 한약재 추출물 제조시 여과후 남은 한약재 찌꺼기 7~10중량부, 상기 불림단계(S20)에서 제조된 법제 유황분말 2~3중량부, 상기 불림단계(S20)에서 제조된 천연항균제 3~5중량부를 혼합하여 제조되는 것을 특징으로 하는 새싹보리 재배방법., Ltext: 농업, prediction: 임업
444/1059 Row 444: application_number: 1020190178145, combined_string: invention_title: 격리부재가 구비된 식물 재배장치 abstract: 본 발명은 식물을 재배하는 재배판이 구비된 장치에 관한 것으로 옆으로 퍼지는 성격의 식물을 재배판에서 키우는 경우에 식물의 줄기가 엉키는 문제를시켜주어 작물의 상품성 저하를 방지할 수 있는 효과를 달성할 수 있다. claims: 복수개의 재배홀을 가지는 재배플레이트와 상기 재배홀에 삽입되어 고정되는 복수의 화분을 포함하는 식물 재배 장치에 있어서,상기 화분은,재배 식물의 뿌리와 상기 뿌리를 고정하는 흙이 위치하여 생장하도록 공간을 제공하는 본체부; 및상기 본체부로부터 하방으로 연장 형성되고 측벽과 바닥면에는 상기 식물의 뿌리가 관통할 수 있는 복수의 관통홀이 형성되며 외벽면의 적어도 일부가 상기 재배홀의 내벽면의 적어도 일부와 이격되며 상기 재배홀로 삽입되어 위치되는 삽입부를 포함하고,상기 식물 재배 장치는, 상기 화분들의 상부 공간을 각 화분마다 구분하여 서로 격리시키는 격리부재를추가로 더 포함하는 것을 특징으로 하는 식물 재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

445/1059 Row 445: application_number: 1020190166976, combined_string: invention_title: 뿌리작물 재배기 abstract: 본 발명은 뿌리작물 재배기에 관한 것으로, 본 발명에 따르면, 물을 배수시킬 수 있도록 배수홀을 포함하는 하판 및 상기 하판에 결합되되, 하나 이상이 적층될 수 있는 재배통을 포함하되, 상기 재배통은 내부가 관통된 통 형상으로 형성된 몸체; 상기 몸체 상부에 형성된 상부 결합부 및 상기 몸체 하부에 형성되어, 다른 재배통의 상부 결합부 또는 상기 하판과 결합되는 하부 결합부를 포함하는 뿌리작물 재배기를 제공할 수 있다. claims: 물을 배수시킬 수 있도록 배수홀을 포함하는 하판 및상기 하판에 결합되되, 하나 이상이 적층될 수 있는 재배통을 포함하되,상기 재배통은,내부가 관통된 통 형상으로 형성된 몸체;상기 몸체 상부에 형성된 상부 결합부 및상기 몸체 하부에 형성되어, 다른 재배통의 상부 결합부 또는 상기 하판과 결합되는 하부 결합부를 포함하고,상기 재배통에 설치되어 토양에서 공간을 확보하고, 뿌리가 성장함에 따라 토압을 조절할 수 있도록 하는 토압 조절부를 포함하며,상기 토압 조절부는,상기 재배통 상측에 설치되는 관거치부 및상기 관거치부에 거치되어 상기 재배통 내부로 설치되는 토압 조절관을 포함하는 뿌리작물 재배기., Ltext: 농업, prediction: 농업
446/1059 Row 446: application_number: 1020190159695, combined_string: invention_title: 폴리페놀 고함유 쓴 잎 재배방법 abstract: 본 발명은 쓴 잎 재배 시에 발효유황을 사용하여 폴리페놀 함량이 현저히 증가된 쓴 잎 대량재배방법에 관한 것이다. claims: 쓴 잎 줄기를 18 내지 22cm 크기로 잘라 물에 1/3 잠기도록 한 후 실온에서 25일 내지 35일간 정치하여 흰 뿌리가 3-5개 내리도록 하는 쓴 잎 모종 전처리 단계;상기 전처리 단계에서 흰 뿌리가 3-5개 나온 쓴 잎 모종을, 상토:마사토:황토가 1:1:1로 배합된 모종판에 9-11 cm 간격으로 이식하여 물을 충분히 주면서 20~30℃의 온도에서 25 내지 35일간 생육시키는 모종재배단계; 모종재배단계에서 뿌리 내린 쓴 잎을 참나무껍질과 피트모스로 객토된 토양에 30-40cm 간격으로 심은 후, 2-3일 간격으로 25-35일간 지하 80-100cm에서 pH 5.5-6.5인 물을 사용하여 관수하고 그 이후부터는 1개월 간격으로 풀브산을 혼합한 물을 관수하면서 온도 15~25℃로 조절하여 쓴잎을 생육시키는 성장단계로 구성되는 쓴 잎 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

447/1059 Row 447: application_number: 1020190151156, combined_string: invention_title: 뿌리 식물의 다수확 재배용 케이스 및 이를 이용한 뿌리 식물의 다수확 재배방법 abstract: 본 발명은 뿌리 식물의 다수확 재배용 케이스 및 이를 이용한 뿌리 식물의 다수확 재배방법에 관한 것으로, 본 발명은 경사진 경작지에 평행하도록 기울어져 경작지에 매설되고, 뿌리 식물이 길게 성장할 수 있도록 길게 형성되어 뿌리식물의 길이 방향 성장을 가이드하는 저면 플레이트부; 저면 플레이트부의 양 측면에 형성되어 뿌리 식물의 측면 방향 성장을 가이드하는 측면 플레이트부; 경작지의 지면을 향하도록 저면 플레이트부의 일단에서 일정각도만큼 기울어져 형성되어 경작지의 상부에 배치되고, 뿌리 식물의 뿌리가 저면 플레이트부에 닿도록 저면 플레이트부의 길이방향을 따라 뿌리 식물이 배치되어 성장을 시작하는 슬라이드부; 및 저면 플레이트부의 타단에 형성되어 경작지의 하부에 배치되고, 뿌리 식물의 길이 방향 성장을 제한하는 종결부를 포함할 수 있다. claims: 경사진 경작지에 평행하도록 기울어져 상기 경작지에 매설되고, 마, 인삼, 더덕, 칡, 도라지 또는 무인 뿌리 식물이 길게 성장할 수 있도록 길게 형성되어 상기 뿌리 식물의 길이 방향 성장을 가이드하는 저면 플레이트부;상기 저면 플레이트부의 일측면에 형성되는 제1측면 플레이트부와, 상기 저면 플레이트부의 타측면에 형성되는 제2측면 플레이트부로 이루어져 상기 뿌리 식물의 측면 방향 성장을 가이드하는 측면 플레이트부;상기 경작지의 지면을 향하도록 상기 저면 플레이트부의 일단에서 일정각도만큼 기울어져 형성되어 상기 경작지의 상부에 배치되고, 상기 뿌리 식물의 뿌리가 상기 저면 플레이트부에 닿도록 상기 저면 플레이트부의 길이방향을 따라 상기 뿌리 식물이 배치되어 성장을 시작하는 슬라이드부; 및상기 저면 플레이트부의 타단에 형성되어 상기 경작지의 하부에 배치되고, 상기 뿌리 식물의 길이 방향 성장을 제한하는 종결부;를 포함하고,상기 저면 플레이트부, 측면 플레이트부, 슬라이드부 및 종결부는 합성수지로 형성되고,복수 개의 제1엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 저면 플레이트부와 슬라이드부의 일측에 상호 일정간격 이격되어 형성되고,복수 개의 제2엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 저면 플레이트부와 슬라이드부의 타측에 상호 일정간격 이격되어 상기 제1엠보싱에 평행하게 형성되고,복수 개의 제3엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 측면 플레이트부와 저면 플레이트부에 상호 일정간격 이격되어 상기 저면 플레이트부의 길이방향에 수직으로 형성되되, 각각의 상기 제3엠보싱은 상기 제1측면 플레이트부의 단부로부터 한 쌍의 상기 제1엠보싱 사이를 통과하여 상기 제2엠보싱 인근까지 연장되고,복수 개의 제4엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 측면 플레이트부와 저면 플레이트부에 상호 일정간격 이격되어 상기 저면 플레이트부의 길이방향에 수직으로 형성되되, 각각의 상기 제4엠보싱은 상기 제2측면 플레이트부의 단부로부터 한 쌍의 상기 제2엠보싱 사이를 통과하여 상기 제1엠보싱 인근까지 연장되고,복수 개의 제5엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 제1측면 플레이트부에 상호 일정간격 이격되어 상기 제3엠보싱에 평행하게 형성되고,복수 개의 제6엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 제2측면 플레이트부에 상호 일정간격 이격되어 상기 제4엠보싱에 평행하게 형성되고,상기 제1엠보싱, 제2엠보싱, 제3엠보싱 및 제4엠보싱에 둘러싸여 사각형태로 구획되는 복수 개의 분할면이 상기 저면 플레이트부의 길이방향을 따라 순차적으로 상기 저면 플레이트부에 형성되고,상기 뿌리 식물의 잔뿌리가 관통할 수 있는 복수 개의 홀이 상기 저면 플레이트부의 길이방향을 따라 상호 일정간격 이격되어 상기 분할면에 형성되는 뿌리 식물의 다수확 재배용 케이스., Ltext: 농업, prediction: 임업
448/1059 Row 448: application_number: 1020190136074, combined_string: invention_title: 플라보노이드를 함유하는 기능성 콩의 재배방법 abstract: 항바이러스 작용 등을 하는 플라보노이드 성분이 함유된 기능성 콩 및 그 재배방법을 개시한다. 본 발명은 기능성 콩의 재배방법으로서 15~20v%의 혼합농축액, 20~35v%의 양파농축액, 그리고 나머지 콩두유를 혼합한 혼합농축액과 물을 부피비로 1:1로 희석한 희석농축액에 콩을 침장한 후, 침장된 콩을 정식한 다음 상기 희석농축액과 물을 혼합한 관주액으로 관주하여 재배한, 플라보노이드 성분을 160mg/kg 함유하는 것을 특징으로 하는 기능성 콩에 대한 것이다. claims: 기능성 콩의 재배방법으로서,15~20v%의 홍삼농축액, 20~35v%의 양파농축액, 그리고 나머지 콩두유를 혼합한 혼합농축액과 물을 부피비로 1:1로 희석한 희석농축액에 콩을 침장한 후, 침장된 콩을 정식한 다음 상기 희석농축액과 물을 혼합한 관주액으로 관주하여 재배하는 것을 특징으로 하는, 기능성 콩의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

449/1059 Row 449: application_number: 1020190127935, combined_string: invention_title: 비닐 천공과 파종작업을 동시에 수행할 수 있는 점파식 파종기 abstract: 본 발명은 점파식 파종기에 관한 것으로, 특히 종자공급통(11)의 공급관(12)을 통하여 공급되는 종자를 내부 공간(22)에 수용하고, 지면위를 구름이동하도록 공급관(12)의 선단에 회전가능하게 연결되어 종자 일정량 만큼씩 외부로 배출하는 종자통(20)과, 상기 종자통(20)의 원통형 몸체(21)의 외측벽을 따라 일정한 간격으로 복수개가 구비되고 종자통(20)이 비닐(3)로 멀칭된 두둑(1)을 구름이동할 때, 외측면에 구비된 커터로써 멀칭 비닐(3)을 절개하는 동시에 두둑(1)에 파종홈(1a)을 형성하는 파종구(30)를 구비한 상기 파종구(30)는 파종통(20)의 원통형 몸체(21)에 탈착가능하게 결합되어 고정된 파종구 몸체(31)와, 상기 파종구 몸체(31)의 상측 선단에 힌지핀(38)을 중심으로 회동가능하게 결합되고, 파종통(20) 내부에 구비된 개폐작동기구에 의해 힌지핀(38)을 중심으로 회동하여 파종구 몸체(31)의 종자 수용홈을 개폐하는 파종구 덮개(32)를 포함하고, 상기 커터는, 상기 파종구 몸체(31)에 구비된 전방 커터(34)와, 후방 커터(35)와, 상기 파종구 덮개(32)의 좌측 커터(36)와, 상기 파종구 몸체(31)에 구비된 우측 커터(37)로 이루어져, 파종통(20)이 비닐(3)로 멀칭된 두둑(1)위를 구름이동할 때, 파종구(30)와 파종구(30)에 구비된 4개의 커터(34-37)들이 멀칭 비닐(3)을 '십자형'으로 절개하고 확개하여, 파종된 종자에서 싹이 원활하게 자라날 수 있게 된다. claims: 비닐 천공과 파종작업을 동시에 수행할 수 있는 점파식 파종기로서, 종자공급통(11)의 공급관(12)을 통하여 공급되는 종자를 내부 공간(22)에 수용하고, 지면위를 구름이동하도록 공급관(12)의 선단에 회전가능하게 연결되어 종자 일정량 만큼씩 외부로 배출하는 종자통(20)과, 상기 종자통(20)의 원통형 몸체(21)의 외측벽을 따라 일정한 간격으로 복수개가 구비되고 종자통(20)이 비닐(3)로 멀칭된 두둑(1)을 구름이동할 때, 외측면에 구비된 커터로써 멀칭 비닐(3)을 절개하는 동시에 두둑(1)에 파종홈(1a)을 형성하는 파종구(30)를 구비하고, 상기 파종구(30)는 파종통(20)의 원통형 몸체(21)에 탈착가능하게 결합되어 고정된 파종구 몸체(31)와, 상기 파종구 몸체(31)의 상측 선단에 힌지핀(38)을 중심으로 회동가능하게 결합되고, 파종통(20) 내부에 구비된 개폐작동기구에 의해 힌지핀(38)을 중심으로 회동하여 파종구 몸체(31)의 종자 수용홈을 개폐하는 파종구 덮개(32)를 포함하고, 상기 커터는, 상기 파종구 몸체(31)에 파종방향에 대하여 전방으로 돌출되게 구비되고, 톱니형 날(34a)을 가진 전방 커터(34)와, 상기 파종구 몸체(31)에 파종방향에 대하여 후방으로 돌출되게 구비되고, 톱니형 날(35a)을 가진 후방 커터(35)와, 상기 파종구 덮개(32)에 파종방향에 대하여 좌측으로 돌출되게 구비되고, 톱니형 날(36a)을 가진 좌측 커터(36)와, 상기 파종구 몸체(31)에 파종방향에 대하여 우측으로 돌출되게 구비되고, 톱니형 날(37a)을 가진 우측 커터(37)를 포함하고, 상기 커터(34-37)는 전체적으로 상단에서 하단으로 갈수록 하향 경사지게 형성되며, 상기 커터(34-37)의 날(34a-37a)은 하향 경사진 날부와 상향 경사진 날부가 교대로 형성된 톱니형 날로 구성되며, 상기 파종구(30)의 파종구 덮개(32)는, 파종구(30)가 두둑(1)위의 멀칭 비닐(3)과 접촉하기 시작하는 위치(P1)에서 두둑(1)의 멀칭 비닐(3)을 통과하여 두둑(1)안으로 침입할 때, 상기 커터(34-37)의 날(34a-37a)로써 멀칭 비닐(3)을 '십자(+)형'으로 절개하고, 두둑(1) 안 최대 깊이로 침입한 위치(P2)에서 최대로 개방되어 파종하고, 파종구(30)가 두둑(1)아래에서 외부로 빠져나올 때, 상기 커터(34-37)의 날(34a-37a)로써 '십자(+)형'으로 절개된 멀칭 비닐의 절개부(4)를 외측으로 확개하고, 멀칭 비닐(3)에서 빠져 나온 위치(P3)에서 파종구 덮개(32)가 파종구 몸체(31)의 수용홈을 폐쇄하도록 된 것을 특징으로 하는 비닐 천공과 파종작업을 동시에 수행할 수 있는 점파식 파종기., Ltext: 농업, prediction: 임업
450/1059 Row 450: application_number: 1020190127444, combined_string: invention_title: 이동식 수직재배 장치 abstract: 본 발명은 하우스 내에서 재배되는 과일 중 특히 수박을 수직으로 재배할 수 있도록 하는 이동식 수직재배 장치에 관한 것으로, 복수의 가로프레임 및 세로프레임이 상호 결합 가능하여 네 개의 면으로 형성된 측면골조를 이룰 수 있으며, 상기 측면골조의 상부에 복수의 활형프레임이 동일 간격으로 이격 배치되어 결합 가능한 하우스프레임; 및 상기 하우스프레임의 내측에 구비 가능한 재배부를 포함하며, 상기 재배부는 양단이 상기 측면골조의 상부 양측에 각각 결합 가능하고, 상기 하우스프레임의 길이 방향을 따라 등간격으로 상호 이격되도록 구비 가능한 복수의 가이드프레임; 상기 가이드프레임에 결합 가능하여 상기 가이드프레임의 길이 방향을 따라 좌우 이동이 가능한 복수의 가이드롤러; 상기 가이드롤러의 일측에 결합 가능하며, 지면을 향해 수직으로 연장 형성 가능한 제1지지프레임; 및 상기 하우스프레임의 길이 방향으로 복수개가 구비 가능한 상기 제1지지프레임의 일측에 연속되도록 결합 가능하고, 상부에 하우스에서 재배되는 과일이 올려질 수 있는 받침대를 포함하는 것을 특징으로 하여 과일을 지면으로부터 이격시켜 공중에서 재배할 수 있도록 하여, 노동 강도를 저하시켜 작업속도를 향상시키고, 병원균으로부터 감염 확률을 낮춰 고품질의 과일을 생산할 수 있으며, 한정된 하우스 면적으로 밀식재배를 가능하게 하여 과일의 수확량을 증가시키고, 하우스 내의 작업 공간을 자유롭게 활용할 수 있는 이동식 수직재배 장치에 관한 것이다 claims: 복수의 가로프레임 및 세로프레임이 상호 결합 가능하여 네 개의 면으로 형성된 측면골조를 이룰 수 있으며, 상기 측면골조의 상부에 복수의 활형프레임이 동일 간격으로 이격 배치되어 결합 가능한 하우스프레임; 및상기 하우스프레임의 내측에 구비 가능한 재배부를 포함하고,상기 재배부는,양단이 상기 측면골조의 상부 양측에 각각 결합 가능하고, 상기 하우스프레임의 길이 방향을 따라 등간격으로 상호 이격되도록 구비 가능한 복수의 가이드프레임;상기 가이드프레임에 결합 가능하여 상기 가이드프레임의 길이 방향을 따라 좌우 이동이 가능한 복수의 가이드롤러;상기 가이드롤러의 일측에 결합 가능하며, 지면을 향해 수직으로 연장 형성 가능한 제1지지프레임; 및상기 하우스프레임의 길이 방향으로 복수개가 구비 가능한 상기 제1지지프레임의 일측에 연속되도록 결합 가능하고, 상부에 하우스에서 재배되는 과일이 올려질 수 있는 받침대를 포함하며,상기 제1지지프레임에는,상기 받침대를 지지 가능한 지지부재를 더 포함하고,상기 받침대는,상기 하우스프레임의 길이 방향을 따라 동일 선상으로 구비 가능한 상기 제1지지프레임의 일측에 연속 되도록 결합 가능한 제1받침프레임;상기 제1받침프레임과 동일한 길이를 가지며, 상기 제1받침프레임과 일정 간격 이격되도록 구비 가능한 제2받침프레임; 및상기 제1받침프레임 및 제2받침프레임의 사이에 구비 가능하여 양단이 상기 제1받침프레임 및 제2받침프레임의 일측에 각각 수직으로 결합 가능하고, 상기 제1받침프레임 및 제2받침프레임의 길이 방향을 따라 동일 간격 이격되어 결합 가능한 복수의 보조프레임을 포함하며,상기 제1받침프레임은 회전이 가능하도록 상기 제1지지프레임과 제3브라켓(244)에 의해 결합 가능한 것을 특징으로 하는 이동식 수직재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

451/1059 Row 451: application_number: 1020190125748, combined_string: invention_title: 커넥터블 연무 재배장치 abstract: 본 발명은 연무를 이용하여 식물을 재배할 수 있도록 하는 커넥터블 연무 재배장치에 관한 것으로, 내부에 마련된 식물이 성장하도록 연무를 발생시켜 공급하는 연무재배기; 및 외부로부터 가해지는 물리적인 힘 또는 식물재배 프로그램에 따라 상기 연무재배기가 연무를 발생시키도록 제어하는 콘트롤장치를 포함한다. 이에, 재배장치를 통해 재배되는 식물의 뿌리에 골고루 수분을 공급하여 재배장치 내의 식물들의 성장이 균일하게 이루어지도록 하는 효과가 있다. claims: 내부에 마련된 식물이 성장하도록 연무를 발생시켜 공급하는 연무재배기; 및외부로부터 가해지는 물리적인 힘 또는 식물재배 프로그램에 따라 상기 연무재배기가 연무를 발생시키도록 제어하는 콘트롤러;를 포함하는 커넥터블 연무 재배장치., Ltext: 농업, prediction: 농업
452/1059 Row 452: application_number: 1020190125613, combined_string: invention_title: 작물 재배용 양액 공급장치 abstract: 본 발명의 일 실시예에 따른 작물 재배용 양액 공급장치는, 복수의 작물이 배치될 수 있도록, 종 방향 및 횡 방향으로 복수의 셀(cell)로 구획된 프레임과 복수의 작물뿌리가 노출된 상기 프레임 하부를 감싸 설치된 하우징으로 이루어진 분무경 양액재배 시스템에 있어서, 배양액을 분사하는 분사부; 상기 프레임 하방으로 노출된 각각의 작물뿌리에 배양액을 공급할 수 있도록, 상기 프레임 하부에 설치되어 상기 분사부를 종 방향 또는 횡 방향으로 이동시키는 이동부; 각각의 작물에 서로 다른 배양액을 분사할 수 있도록, 서로 다른 양액을 상기 분사부에 공급하는 복수 개의 양액 공급부; 및 사전에 입력된 각각의 상기 셀에 배치된 작물정보에 따라, 상기 양액 공급부, 분사부 빛 이동부의 작동을 제어하는 제어부;를 포함한다. claims: 복수의 작물이 배치될 수 있도록, 종 방향 및 횡 방향으로 복수의 셀(cell)로 구획된 프레임과 복수의 작물뿌리가 노출된 상기 프레임 하부를 감싸 설치된 하우징으로 이루어진 분무경 양액재배 시스템에 있어서,배양액을 분사하는 분사부;상기 프레임 하방으로 노출된 각각의 작물뿌리에 배양액을 공급할 수 있도록, 상기 프레임 하부에 설치되어 상기 분사부를 종 방향 또는 횡 방향으로 이동시키는 이동부;각각의 작물에 서로 다른 배양액을 분사할 수 있도록, 서로 다른 양액을 상기 분사부에 공급하는 복수 개의 양액 공급부; 및사전에 입력된 각각의 상기 셀에 배치된 작물정보에 따라, 상기 양액 공급부, 분사부 빛 이동부의 작동을 제어하는 제어부;를 포함하며, 상기 분사부는,복수의 상기 양액 공급부로부터 양액을 공급받아, 하나 이상의 양액이 혼합된 배양액이 수용되는 내부공간이 형성된 분사바디;상기 내부공간에 수용된 배양액을 작물뿌리에 분사하도록, 상기 분사바디에 결합된 분사노즐; 및실시간으로, 현재 위치한 셀에 배치된 작물뿌리의 형상정보를 취득하여 상기 제어부로 전송하는 스캐너;를 포함하고,상기 양액 공급부는,양액 탱크;양단이 각각 상기 양액 탱크와 상기 분사바디에 연통되는 양액 공급라인; 및상기 양액 공급라인 상에 설치되어 상기 분사바디에 공급되는 양액의 량을 조절하는 양액밸브;를 포함하고,상기 제어부는 상기 작물정보에 따라 각각의 상기 양액 공급부를 개별 제어하여, 각각의 작물에 최적의 양액비에 따라 각각의 상기 양액밸브의 작동을 제어하여 배양액을 제조하며,상기 분사노즐은 각각의 작물에 따라 분사되는 배양액의 분사각 및 입도 조절이 가능한 이류체 노즐인 것을 특징으로 하며,상기 제어부는 상기 스캐너로부터 실시간으로 수신되는 작물뿌리의 형상정보에 대응하도록, 상기 분사노즐의 분사각도를 조절하여, 상기 작물뿌리의 형상정보가 폭이 좁고 길이가 길다고 판단된 경우, 상기 분사노즐을 하방으로 이동시키면서 분사각도가 좁아지도록 제어하고, 상기 작물뿌리의 형상정보가 폭이 넓고 길이가 짧다고 판단된 경우, 상기 분사노즐을 상방으로 이동시키면서 분사각도가 증가되도록 제어하는 것을 특징으로 하는, 작물 재배용 양액 공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

453/1059 Row 453: application_number: 1020190122774, combined_string: invention_title: 뿌리식물 공중 재배 장치 abstract: 본 발명에 따른 뿌리식물 공중 재배 장치는 지면으로부터 일정 높이에 고정적으로 설치되는 제1 프레임, 제1 프레임과 평행하게 배치되는 제2 프레임, 제1 프레임과 제2 프레임에 의해 양 단이 지지되어 재배공간을 형성하는 받침패드부, 제2 프레임을 상/하 방향으로 이동시키는 프레임 승강부를 포함하여 이루어진다. 받침패드부는 비닐류 등 유연한 소재로 구성될 수 있으며, 제1 프레임과 제2 프레임의 사이에서 'U' 자 형태의 재배공간을 형성한다. 본 발명에 따르면, 고구마, 감자 등 일정 깊이의 흙 속에서 재배하는 각종 뿌리식물을 땅에서 이격된 공중의 공간에서 재배할 수 있고, 그 아래의 지면도 자유롭게 이용할 수 있으므로, 시설의 공간을 더욱 효율적으로 이용할 수 있다. 특히, 고구마와 감자 등 뿌리식물의 수확이 매우 쉽게 이루어질 수 있다. claims: 지면으로부터 일정 높이에 고정적으로 설치되는 제1 프레임;상기 제1 프레임과 평행하게 배치되는 제2 프레임;상기 제1 프레임과 제2 프레임에 의해 양 단이 지지되고, 뿌리식물을 재배할 재배공간을 형성하는 받침패드부; 및상기 제2 프레임을 상/하 방향으로 이동시키는 프레임 승강부를 포함하는, 뿌리식물 공중 재배 장치., Ltext: 농업, prediction: 임업
454/1059 Row 454: application_number: 1020190117864, combined_string: invention_title: 벼의 친환경 재배방법과 이를 이용한 벼 종자의 채종방법 abstract: 본 발명은 자연순환농법과 미생물을 이용한 유기농법을 이용하여 친환경적으로 벼를 재배할 수 있는 벼의 친환경 재배방법과, 친환경 재배방법을 통해 재배하기에 적합한 벼 종자를 채종할 수 있는 벼 종자의 채종방법에 관한 것이다. 본 발명에 따른 벼의 친환경 재배방법 및 벼 종자의 채종방법은 벼를 수확 후 농지에 녹비작물을 파종하는 녹비작물 파종 단계와, 농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계, 벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계, 상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계, 토양에 모를 이앙하는 모 이앙 단계, 벼의 영양 생장기에 벼의 잎에 존재하는 미네랄 성분을 분석하는 벼의 엽분석 단계, 상기 벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및, 벼를 수확하는 벼 수확 단계를 포함하고, 상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하는 것을 특징으로 한다. claims: 벼를 친환경적으로 재배하는 방법에 있어서,벼를 수확 후 농지에 녹비작물을 파종하는 녹비작물 파종 단계와,농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계,벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계,상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계,토양에 모를 이앙하는 모 이앙 단계,벼의 영양 생장기에 벼의 잎에 존재하는 미네랄 성분을 분석하는 벼의 엽분석 단계,상기 벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및,벼를 수확하는 벼 수확 단계를 포함하고,상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하는 것을 특징으로 하는 벼의 친환경 재배방법.벼를 친환경적으로 재배하는 방법에 있어서,벼를 수확 후 농지에 녹비작물을 파종하는 녹비작물 파종 단계와,농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계,상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계,벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계,벼의 영양 생장기에 벼의 잎에 존재하는 미네랄 성분을 분석하는 벼의 엽분석 단계,상기 벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및,벼를 수확하는 벼 수확 단계를 포함하고,상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하는 것을 특징으로 하는 벼의 친환경 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

455/1059 Row 455: application_number: 1020190117867, combined_string: invention_title: 혈당강하와 치매예방 효과가 있는 가바벼의 친환경 재배방법 abstract: 본 발명은 자연순환농법과 미생물을 이용한 유기농법을 이용하여 혈당강하와 치매예방 효과가 있는 가바벼를 효율적으로 재배하기 위한 가바벼의 친환경 재배방법에 관한 것이다. 본 발명의 가바벼 재배방법은 가바벼를 수확 후 농지에 녹비작물을 파종하는 녹비작물 파종 단계와, 농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계, 가바벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계, 상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계, 토양에 모를 이앙하는 모 이앙 단계, 가바벼의 영양 생장기에 가바벼의 잎에 존재하는 미네랄 성분을 분석하는 가바벼의 엽분석 단계, 상기 가바벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및, 가바벼를 수확하는 가바벼 수확 단계를 포함하고, 상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하며, 상기 생물학적 비료는 물과, 가바벼의 볏짚, 어류, 당밀 및 미생물제를 혼합하고 발효시켜 제조하는 것을 특징으로 한다. claims: 가바벼를 친환경적으로 재배하는 방법에 있어서,가바벼를 수확 후 농지를 갈아엎고 써레질을 한 후 녹비작물을 파종하는 녹비작물 파종 단계와,농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계,가바벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계,상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계,토양에 모를 이앙하는 모 이앙 단계,가바벼의 영양 생장기에 가바벼의 잎에 존재하는 미네랄 성분을 분석하는 가바벼의 엽분석 단계,상기 가바벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및,가바벼를 수확하는 가바벼 수확 단계를 포함하고,상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하며,상기 생물학적 비료는 물과, 가바벼의 볏짚, 어류, 당밀 및 미생물제를 포함하는 혼합물을 발효시켜 제조하고,상기 미생물제는 부엽토와 찰밥 및 볏짚을 포함하는 재료를 혼합하고 발효시켜 제조하는 것을 특징으로 하는 혈당강하와 치매예방 효과가 있는 가바벼의 친환경 재배방법.가바벼를 친환경적으로 재배하는 방법에 있어서,가바벼를 수확 후 농지를 갈아엎고 써레질을 한 후 녹비작물을 파종하는 녹비작물 파종 단계와,농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계,상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계,가바벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계,가바벼의 영양 생장기에 가바벼의 잎에 존재하는 미네랄 성분을 분석하는 벼의 엽분석 단계,상기 가바벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및,가바벼를 수확하는 벼 수확 단계를 포함하고,상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하며,상기 생물학적 비료는 물과, 가바벼의 볏짚, 어류, 당밀 및 미생물제를 포함하는 혼합물을 발효시켜 제조하고,상기 미생물제는 부엽토와 찰밥 및 볏짚을 포함하는 재료를 혼합하고 발효시켜 제조하는 것을 특징으로 하는 혈당강하와 치매예방 효과가 있는 가바벼의 친환경 재배방법., Ltext: 농업, prediction: 임업
456/1059 Row 456: application_number: 1020190116152, combined_string: invention_title: 뿌리식물재배용 조립식 컨테이너 abstract: 본 발명은 뿌리식물재배용 조립식 컨테이너에 관한 것으로, 보다 상세하게는 대량의 뿌리식물을 효과적으로 재배할 수 있도록 함은 물론 뿌리식물의 재배에 필요한 물이나 약액을 효율적으로 공급하여 고품질의 뿌리식물의 재배를 이룰 수 있도록 하는 뿌리식물재배용 조립식 컨테이너에 관한 것이다. 본 발명은 상호 일정간격 이격되게 배치되되 하측단에서 상측방향으로 절개조립라인(110)이 형성된 다수개의 쇼트격판(100); 상기 다수개의 쇼트격판(100)을 가로지르도록 결합되되 상기 절개조립라인(110)에 대응되어 끼워맞춤결합되는 대응조립라인(210)이 일정간격으로 형성된 롱격판(200); 격자상으로 배치되게 조립된 상기 쇼트격판(100)과 롱격판(200)을 수용하도록 이루어지되 보관시에는 접어 보관하다가 상기 쇼트격판(100)과 롱격판(200)을 수용하는 경우에는 펼쳐 직육면체 형상을 갖도록 이루어진 수용바디부(400);를 포함하여 구성되되, 상기 쇼트격판(100)의 길이방향 양측과 상기 롱격판(200)의 길이방향 양측은 걸림안착편(300)을 매개로 상기 수용바디부(400)에 분리가능하게 걸림조립되어 격자상으로 배치된 형태가 유지될 수 있도록 이루어진 것을 특징으로 한다. claims: 상호 일정간격 이격되게 배치되되 하측단에서 상측방향으로 절개조립라인(110)이 형성된 다수개의 쇼트격판(100); 상기 다수개의 쇼트격판(100)을 가로지르도록 결합되되 상기 절개조립라인(110)에 대응되어 끼워맞춤결합되는 대응조립라인(210)이 일정간격으로 형성된 롱격판(200); 격자상으로 배치되게 조립된 상기 쇼트격판(100)과 롱격판(200)을 수용하도록 이루어지되 보관시에는 접어 보관하다가 상기 쇼트격판(100)과 롱격판(200)을 수용하는 경우에는 펼쳐 직육면체 형상을 갖도록 이루어진 수용바디부(400);를 포함하여 구성되되, 상기 쇼트격판(100)의 길이방향 양측과 상기 롱격판(200)의 길이방향 양측은 걸림안착편(300)을 매개로 상기 수용바디부(400)에 분리가능하게 걸림조립되어 격자상으로 배치된 형태가 유지될 수 있도록 이루어지고, 상기 쇼트격판(100)과 상기 수용바디부(400)의 상단에는, 물이나 약액이 유동하는 유동배관유닛(500)이 안착되어 상기 유동배관유닛(500)에서 분출된 물이나 약액이 토양이 채워진 재배공간으로 낙하될 수 있는 안착홈(130)이 형성되며, 상기 유동배관유닛(500)은, 상기 안착홈(130)에 안착된 상태로 내측에 물이나 약액이 위치하는 안착바디(520)와, 상기 안착바디(520)의 폭방향 양측으로 연장되어 상기 안착바디(520)의 길이방향을 따라 일정간격으로 형성된 상태로 상기 안착바디(520)에 위치한 물이나 약액이 유동하여 토양이 채워진 재배공간(150)으로 분출될 수 있도록 안내하는 유체가이드구(530)를 포함하여 구성되고, 상기 유체가이드구(530)에는, 물이나 약액이 상기 재배공간(150)의 상측방향으로 분출될 수 있도록 하는 상방분출공(540)과 물이나 약액이 상기 재배공간(150)의 하측방향으로 유동할 수 있도록 하는 하방분출튜브(570)가 마련된 것을 특징으로 하는 뿌리식물재배용 조립식 컨테이너., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

457/1059 Row 457: application_number: 1020190115067, combined_string: invention_title: 수동식 파종기 abstract: 본 발명은 수동식 파종기에 관한 것이다.구성에 있어서, 파이프 형태로 된 지주관의 하부에 작동부와 파종부, 그리고 파종홈의 깊이를 조절할 수 있는 스토퍼부로 이루어진 파종홈 성형장치를 구성하여 상기 작동부의 하단 베이스를 지면에 대고 손잡이로 누르면 파종부가 하강하면서 오물어진 상태로 지면에 들어가게 되어 자연스럽게 소정깊이의 파종홈을 형성하게 되고, 파종기를 들면 작동부의 복원력에 의해 자연적으로 파종부가 개방되면서 상기 파종홈에 종자 또는 모종을 파종 또는 식재할 수 있게 한 것이다.따라서 본 발명은 종래 수동식 파종기에 비해 각종 씨앗의 파종이나 모종의 이식이 훨씬 더 편리하게 이루어짐은 물론 사용시 힘이 덜 들어 신뢰성을 극대화시킬 수 있는 등의 효과가 따른다. claims: 지주관(1)의 상단에 깔때기 형태로 된 종자 또는 모종 투입이 가능한 투입부(11)가 구비되고, 상기 투입부(11) 직하부에 손잡이(12)가 구비되며, 지주관(1) 하단에 파종부(2)와 작동부(3), 그리고 스토퍼부(4)로 이루어진 파종홈 성형장치(234)를 장착하여, 상기 작동부(3)의 하단에 구비된 베이스(31)를 지면에 대고 손잡이(12)를 잡은 상태에서 지면 쪽으로 누르기만 하면 간편하면서도 균일하게 소정 크기의 파종홈(5)이 형성되는 수동식 파종기(100)를 구성하되,상기 파종홈 성형장치(234)의 파종부(2)는 지주관(1) 하단에 장착 고정되는 고정형파종삽(21)과, 상기 고정형 파종삽(21)의 일 측 상부에 힌지 조립되는 작동삽(22)으로 구성하는데, 상기 작동삽(22)의 일측 상단에는 예각으로 된 작동간(22')이 일체로 형성되고, 상기 작동간(22') 끝이 후술하는 작동부(3)의 가이드봉(32)에 장착된 승강블록(33)에 연결 구성되어 상기 파종부(2)가 하강할 때는 작동삽(22)이 닫히고 상승할 때는 개방되게 하며,상기 파종홈 성형장치(234)의 작동부(3)는, 파종부(2) 상단에 장착 고정된 지지대(34)와 상기 지지대(34)의 양측 안내관(34')에 관통 설치되며 하단이 베이스(31) 양측에 고정 설치된 가이드봉(32), 그리고 상기 가이드봉(32) 하단에 위치하여 가이드봉(32)이 수직을 유지하도록 지지하는 베이스(31)로 구성되며, 상기 가이드봉(32) 상단은 외향 절곡된 절곡부(32')를 형성하여 상기 절곡부(32')와 지지대(34)를 인장스프링(35)으로 연결 구성하고, 양측 가이드 봉(32) 상측 소정위치에 지지대(34)의 승강거리를 제어하는 스톱돌기(32)를 형성하며, 일 측 가이드봉(32)에는 전술한 작동간(22') 끝이 연결되는 승강블록(33)을 설치하되, 상기 승강블록(33)은 가이드봉(32)에 끼워진 상태에서 상승압력 또는 하강압력을 받았을 때만 승강할 수 있도록 구성한 것이며,스토퍼부(4)는 상기 작동삽(22) 후미에 설치하되, 고정판(41)과 조절판(42)으로 형성하고, 고정판(41)의 외측면에는 짧은 육각축(43')과 나사봉(43)이 일체로 된 결합축(43)을 형성하며, 조절판(42)에는 상기 육각축(43')에 끼워지도록 육각구멍(42')을 형성함으로서 조절판(42)이 다양한 높이로 조절 설치될 수 있게 구성한 것으로, 상기 파종부(2)와 작동부(3), 그리고 스토퍼부(4)가 유기적으로 조절됨에 따라 손잡이(12)를 잡아 누르는 단순한 동작에 의해 종자 파종 및 모종이식이 가능하게 하고, 또 파종홈(5)의 깊이를 간편하게 조절할 수 있게 함을 특징으로 하는 수동식 파종기., Ltext: 농업, prediction: 임업
458/1059 Row 458: application_number: 1020190107445, combined_string: invention_title: 무한궤도형 작물 재배 장치 abstract: 본 발명의 일 실시예에 따른 무한궤도형 작물 재배 장치는, 작물 재배 용기가 무한궤도로 이동하면서 작물이 재배되도록 하는 장치로, 상기 무한궤도를 구현하기 위한 이송궤도; 및 상기 작물 재배 용기가 연결된 채로 상기 이송궤도에 의해 제공되는 내부공간 내에 배치되어 상기 내부공간 내에서 이동되는 이동체인;을 포함하며, 상기 이송궤도는, 상기 이동체인이 높이를 유지한 채 이동하기 위한 수평궤도, 상기 이동체인이 상승하면서 이동하기 위한 상승궤도, 상기 이동체인이 하강하면서 이동하기 위한 하강궤도, 및 상기 이동체인의 이동 방향을 선회시키는 선회궤도를 구비하며, 상기 선회궤도는, 상기 내부공간 내에 배치되는 상기 이동체인의 장력이 느슨해지는 경우, 상기 이동체인의 장력을 증가시켜 상기 이동체인의 이동이 원활하게 되도록, 위치 이동이 가능한 것을 특징으로 할 수 있다. claims: 작물 재배 용기가 무한궤도로 이동하면서 작물이 재배되도록 하는 무한궤도형 작물 재배 장치에 있어서,상기 무한궤도를 구현하기 위한 이송궤도; 및상기 작물 재배 용기가 연결된 채로 상기 이송궤도에 의해 제공되는 내부공간 내에 배치되어 상기 내부공간 내에서 이동되는 이동체인;을 포함하며,상기 이송궤도는,상기 이동체인이 높이를 유지한 채 이동하기 위한 수평궤도, 상기 이동체인이 상승하면서 이동하기 위한 상승궤도, 상기 이동체인이 하강하면서 이동하기 위한 하강궤도, 및 상기 이동체인의 이동 방향을 선회시키는 선회궤도를 구비하며,상기 선회궤도는,상기 내부공간 내에 배치되는 상기 이동체인의 장력이 느슨해지는 경우, 상기 이동체인의 장력을 증가시켜 상기 이동체인의 이동이 원활하게 되도록, 위치 이동이 가능하며,상기 이송궤도는,윤활 기능을 통해 상기 이동체인의 원활한 이동을 구현하기 위한 오일이 상기 내부공간 내에서 정체되는 경우, 외부로 배출되도록 하기 위한 배출홀을 구비하며,상기 배출홀은, 상기 선회궤도와 상기 상승궤도의 경계 부분의 하측 및 상기 선회궤도와 상기 하강궤도의 경계 부분의 하측 중 적어도 하나에 형성되고,상기 배출홀은,커버에 의해 밀폐 가능한 것을 특징으로 하는 무한궤도형 작물 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

459/1059 Row 459: application_number: 1020190098998, combined_string: invention_title: 스마트 작물 재배 관리 시스템 및 스마트 작물 재배 관리 방법 abstract: 본 발명의 일 기술적 측면에 따른 스마트 작물 재배 관리 시스템은 작물 재배용 하우스(이하, '하우스'라 칭함)에 설치되어 상기 하우스 내의 작물에 대한 관리를 제공하는 스마트 작물 재배 관리 시스템으로서, 상기 하우스의 토양 온도, 내부 온도 및 외부 온도를 감지하는 온도 센서, 상기 하우스의 내부 습도 및 외부 습도를 감지하는 습도 센서, 상기 하우스 내에 구비되고, 상기 하우스 내의 작물에 급수 또는 양액을 공급하는 급수부 및 상기 온도 센서 및 상기 습도 센서의 출력을 기초로 상기 하우스의 상태 정보를 저장하고, 상기 상태 정보를 참조하여 기 설정된 관리 시나리오에 따라 상기 급수부를 조절하는 관리 장치를 포함할 수 있다. claims: 하우스에 설치되어 상기 하우스 내의 작물에 대한 관리를 제공하는 스마트 작물 재배 관리 시스템으로서,상기 하우스의 토양 온도, 내부 온도 및 외부 온도를 감지하는 온도 센서;상기 하우스의 내부 습도 및 외부 습도를 감지하는 습도 센서;상기 하우스 내에 구비되고, 상기 하우스 내의 작물에 급수 또는 양액을 공급하는 급수부;상기 하우스에 설치되어 상기 하우스에 공기를 순환시키고, 미리 설정된 분사량, 동작 시간, 정지 시간 및 습도 조건에 따라 동작을 제어하는 적어도 하나의 환풍부;상기 하우스에 대한 화재 발생 여부를 감지하는 화재 감지 센서;상기 스마트 작물 재배 관리 시스템에 대한 정전 여부를 감지하는 정전 감지 센서;상기 하우스 외부의 풍향 및 풍속을 측정하는 풍향 센서;상기 하우스 내의 작물에 대한 영상 데이터를 취득하는 카메라부; 및상기 온도 센서 및 상기 습도 센서의 출력을 기초로 상기 하우스의 상태 정보를 저장하고, 상기 상태 정보를 참조하여 기 설정된 관리 시나리오에 따라 미리 설정된 특정 시간에 물이나 양액을 제공하도록 상기 급수부를 조절하며, 상기 화재 감지 센서에서 화재를 감지하거나 또는 상기 정전 감지 센서에서 정전을 감지할 때 이에 대한 비상 알림을 사용자에게 제공하는 관리 장치;를 포함하며,상기 관리 장치는,상기 상태 정보를 참조하여 기 설정된 관리 시나리오에 따라 미리 설정된 시간 동안 환기하도록 상기 환풍부를 조절하며,상기 풍향 센서의 측정치가 상기 하우스의 파손이 우려되는 임계치 이상일 때 비상 알림을 사용자에게 제공하며,상기 카메라부에서 취득한 영상 데이터에 포함된 작물의 생장 변화에 따른 이미지들을 저장하고, 상기 영상 데이터와 작물의 생장 변화에 따른 이미지들을 비교하여 현재 하우스 내의 작물의 생장 상태를 추정하고, 상기 추정된 작물의 생장 상태에 따라 작물에 대한 급수, 배양, 온도 및 습도 중 적어도 하나의 설정을 변경하여 상기 급수부 또는 상기 환풍부의 관리 시나리오를 변경하며,상기 관리 장치는상기 온도 센서 및 상기 습도 센서의 출력을 제공받아 상기 상태 정보를 생성하여 저장하는 저장부;상기 관리 시나리오를 설정하는 시나리오 관리부; 및사용자 단말과 통신 회선을 형성하고, 상기 사용자 단말을 통하여 상기 저장부 또는 상기 시나리오 관리부에 대한 관리 인터페이스를 제공하는 통신 인터페이스 관리부;를 포함하는 것을 특징으로 하는 스마트 작물 재배 관리 시스템., Ltext: 농업, prediction: 농업
460/1059 Row 460: application_number: 1020217005861, combined_string: invention_title: 수경 재배 성장 시스템 및 방법 abstract: 수경 재배 성장 시스템에서 사용되는 장치(100)가 설명된다. 본 장치는 수직 부재(V) 및 일 세트의 성장 탈것(120)이 장착되는 수평 트랙 또는 안내로를 지지하는 수평 부재(H)를 포함한다. 성장 탈것 각각은, 식물 또는 작물이 성장하는 중에 그 식물 또는 작물이 수용되는 다수의 성장 트레이(127)를 포함한다. 본 장치(100)는 수경 재배 성장 시스템 내의 고 케어 시설 내에 위치된다. claims: 지지 구조물, 복수의 가동 지지 탈것 및 구동 유닛을 포함하는 수경 재배 성장 시스템으로서, 상기 지지 탈것은 상기 지지 구조물 상에 장착될 수 있고 또한 사용시 성장하는 작물을 포함하도록 배치되며, 상기 구동 유닛은 식물의 성장 동안에 상기 지지 탈것을 초기 위치로부터 최종 위치로 이동시키도록 배치되는, 수경 재배 성장 시스템.작물을 수경 재배로 성장시키는 방법으로서, 구동 유닛의 작용 하에서 안내로 상에서 이동하도록 지지 구조물에 장착되는 복수의 지지 탈것에서 작물을 성장시키는 것을 포함하고, 상기 방법은 지지 탈것을 초기 위치에 삽입하고 또한 최종 위치에서 그 지지 탈것을 제거하는 것을 포함하고, 상기 작물은 상기 초기 위치와 최종 위치 사이에서 성장하도록 배치되는, 작물을 수경 재배로 성장시키는 방법.컴퓨터 판독 가능한 매체에 있는 컴퓨터 프로그램 제품으로서, 컴퓨터로 실행되면, 그 컴퓨터가 제 13 항 내지 제 15 항 중 어느 한 항에 따른, 작물을 수경 재배로 성장시키는 방법을 수행하게 하는 지시를 포함하는, 컴퓨터 프로그램 제품.장치가 제 13 항 내지 제 15 항 중 어느 한 항에 따른, 작물을 수경 재배로 성장시키는 방법을 수행하게 하는 프로그램. 미리 정해진 작물을 성장시키기 위한 수경 재배 성장 시스템으로서, 전처리(pre-treatment) 부분과 고 케어(high care) 부분을 더 포함하고, 고 케어 부분은 씨를 뿌리고, 발아시키고 작물을 성장시키기 위한 장치를 포함하고, 또한 씨 뿌리기, 발아 및 식물의 성장 동안에 오염을 줄이기 위한 수단을 더 포함하는, 수경 재배 성장 시스템.고 케어 환경에서 작물을 성장시키는 방법으로서, 성장 매체에 씨를 뿌리는 단계; 씨를 발아시키는 단계; 작물을 성장시키는 단계; 및 작물을 수확하는 단계를 포함하고, 상기 작물은 제 18 항 내지 제 23 항 중 어느 한 항에 따른 수경 재배 성장 시스템 내의 고 케어 환경에서 씨 뿌려지고 발아되고 성장되며 또한 수확되는, 고 케어 환경에서 작물을 성장시키는 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

461/1059 Row 461: application_number: 1020190097827, combined_string: invention_title: 영양액의 안정적 공급과 재사용이 가능한 식물재배용기 abstract: 본 발명은 영양액의 안정적 공급과 재사용이 가능한 식물재배용기에 관한 것으로, 더욱 상세하게는, 심지를 방근시트로 포장하여 식물뿌리가 심지에 부착되는 현상을 방지하고, 심지가 용기 내벽면 고루 설치되어 양수분을 용기 전체에 균일하게 공급함으로써 뿌리를 전 방향으로 발달시킬 수 있도록 하며, 또한, 심지가 용기 외부에 노출되지 않아 미관을 향상시키는 동시에, 자동화 시설에 적합하고 운반 편의성을 향상시킬 수 있도록 개발된 영양액의 안정적 공급과 재사용이 가능한 식물재배용기에 관한 것이다.본 발명은 식물재배용기에 있어서, 내부공간이 마련된 용기본체; 상기 용기본체에 외부와 연통되게 형성된 침습시트설치홀; 및 식물재배에 필요한 양수분을 공급하기 위해, 상기 침습시트설치홀에 일측이 삽입되도록 상기 용기본체 내벽에 배치되는 침습시트;를 포함하는 것을 특징으로 한다. claims: 식물재배용기에 있어서,내부공간이 마련된 용기본체;상기 용기본체에 외부와 연통되게 형성된 침습시트설치홀; 및식물재배에 필요한 양수분을 공급하기 위해, 상기 침습시트설치홀에 일측이 삽입되도록 상기 용기본체 내벽에 배치되는 침습시트;를 포함한 것을 특징으로 하는 식물재배용기., Ltext: 농업, prediction: 농업
462/1059 Row 462: application_number: 1020190093677, combined_string: invention_title: 높이조절이 가능한 수경재배용 포트장치 abstract: 본 발명은, 수경재배용 수조의 수위에 대하여 충수되는 높이를 조절하도록 됨에 따라, 재배물의 육성상태에 적합하게 높이를 조절하여 배치시킬 수 있도록 되어, 재배품질을 극대화하도록;상부가 개구되며 내부에 재배물의 뿌리가 심어진 상토가 수용되고 내외로 관통된 다수의 통수공이 구비된 수용공간을 가지며 수경재배용 물이 충수된 수조의 상부에 배치되어 상기 수조물을 통해 영양분을 상기 통수공들을 통해 인가받아 생육되도록 된 포트본체;를 포함하여 이루어지는 높이조절이 가능한 수경재배용 포트장치에 있어서; 상기 수조의 상부에 구비되는 안치부재의 고정공에 끼움고정되며 상하로 관통된 '관(管;pipe)' 형상의 '관체'로 이루어지고 상단테두리부위에 외측방향으로 연장형성되어 상기 고정공의 테두리부위의 상면에 받침되게 지지되도록 된 지지플랜지부가 형성되며 내주면에 상기 포트본체의 상단테두리부위에 외측방향으로 연장형성된 안치플랜지부가 받침되어 지지되는 지지수단이 구비된 고정관;을 더 포함하여 이루어지되; 상기 지지수단은, 상기 고정관의 내주면에서 수직상 사이간격을 가지면서 내측방향으로 돌출형성된 다수의 지지돌기들과; 상기 안치플랜지부에서 상기 지지돌기들이 관통되면서 안내되도록 된 안내홈;을 포함하여 이루어지는 높이조절이 가능한 수경재배용 포트장치를 제공한다. claims: 상부가 개구되며 내부에 재배물의 뿌리가 심어진 상토가 수용되고 내외로 관통된 다수의 통수공(31)이 구비된 수용공간을 가지며 수경재배용 물이 충수된 수조(11)의 상부에 배치되어 수조물을 통해 영양분을 상기 통수공(31)들을 통해 인가받아 생육되도록 된 포트본체(3)와; 상기 수조(11)의 상부에 구비되는 안치부재(4)의 고정공(41)에 끼움고정되며 상하로 관통된 '관(管;pipe)' 형상의 '관체'로 이루어지고 상단테두리부위에 외측방향으로 연장형성되어 상기 고정공(41)의 테두리부위의 상면에 받침되게 지지되도록 된 지지플랜지부(21)가 형성되며 내주면에 상기 포트본체(3)의 상단테두리부위에 외측방향으로 연장형성된 안치플랜지부(32)가 받침되어 지지되는 지지수단이 구비된 고정관(2);을 포함하여 이루어지는 높이조절이 가능한 수경재배용 포트장치(1)에 있어서;상기 지지수단은,상기 고정관(2)의 내주면에서 수직상 동일한 위치에 형성되는 다수개로 중앙을 중심으로 서로 대칭되는 위치에 각각 배치되어 서로 대면하도록 된 다수의 상기 지지돌기(51)들과; 상기 안치플랜지부(32)에서 상기 지지돌기(51)들이 관통되면서 안내되도록 된 안내홈(52);을 포함하여 이루어지며;상기 고정관(2)의 상단에는,상단에 상기 포트본체(3)의 안치플랜지부(32)가 받침지지되며 상부로 길이를 가지면서 구비되는 보조지지대(6)들이 상기 고정관(2)의 중앙을 중심으로 서로 대칭되는 위치에 각각 구비되고;각각의 상기 보조지지대(6)들의 상단에는,상기 안치플랜지부(32)에 형성된 안내홈(52)이 관통하면서 안내되는 연장돌기(61)가 각각 일체로 형성되는 것을 특징으로 하는 높이조절이 가능한 수경재배용 포트장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

463/1059 Row 463: application_number: 1020190092866, combined_string: invention_title: 유용성분을 향상시키는 새싹보리의 재배방법 및 새싹보리의 유용성분 추출 방법 abstract: 본 발명은 유용성분을 향상시키는 새싹보리의 재배방법 및 새싹보리의 유용성분 추출 방법에 관한 것이다.본 발명은 페드리 디쉬(petri dish)에 새싹보리 씨앗을 담아 배양시키는 배양단계; 상기 배양단계에 의해 배양된 새싹보리 씨앗을 파종하는 파종단계; 새싹보리 씨앗이 파종된 공간의 온도를 일정하게 유지한 후, 영양분이 포함된 수소수를 공급하는 수소수 공급단계; 상기 새싹보리 씨앗이 파종된 공간으로 광원을 제공하는 광원 제공단계; 및 10~15cm로 성장한 새싹보리를 채취하는 단계;를 포함하는 새싹보리의 재배방법을 통해 재배된 유용성분이 향상된 새싹보리와 에탄올을 아임계 챔버에 투입하는 단계; 상기 아임계 챔버를 가열하여 고온 고압의 조건을 형성하는 단계; 상기 아임계 챔버를 회전시켜 원심분리 방식으로 상기 새싹보리로부터 유용성분이 포함된 액상 시료를 추출하는 단계; 및 상기 액상 시료를 추출 시료 수집조로 이송시켜 새싹보리의 유용성분에 대한 추출물을 추출하는 단계;를 포함하는 유용성분을 향상시키는 새싹보리의 재배방법 및 새싹보리의 유용성분 추출 방법을 제공한다. claims: 유용성분이 향상된 새싹보리를 이용한 새싹보리의 유용성분 추출방법에 있어서, 상기 새싹보리와 에탄올을 아임계 챔버에 투입하는 단계; 상기 아임계 챔버를 가열하여 고온 고압의 조건을 형성하는 단계; 상기 아임계 챔버를 회전시켜 원심분리 방식으로 상기 새싹보리로부터 유용성분이 포함된 액상 시료를 추출하는 단계; 및 상기 액상 시료를 추출 시료 수집조로 이송시켜 새싹보리의 유용성분에 대한 추출물을 추출하는 단계;를 포함하되,상기 새싹보리는, Zn 0.001중량%, B 0.0001중량%가 각각 첨가된 수소수(hydrogen Water)를 시간당 400㎖ 공급하고, White LED로 7일, 이후 Blue LED로 2일간 광원을 각각 조사하는 새싹보리 챔버에 의해 제조되는 것을 특징으로 하는 새싹보리의 유용성분 추출방법., Ltext: 농업, prediction: 임업
464/1059 Row 464: application_number: 1020190088012, combined_string: invention_title: 청정 새싹재배장치 abstract: 본 발명은 청정 새싹의 재배장치에 관한 것으로 물을 정화하고 가열하는 다기능성 보일러: 상기 보일러에 의해 멸균되게 가열된 물이 일정한 수위로 채워져 재배의 적정온도를 유지하는, 복수로 배치된 청정 재배조; 상기 재배조의 좌우 양측 가장자리 및 중앙부에 배치되어 가습기에서 생성된 포화안개를 분무(噴霧)하여 가습하는 복수의 분무관(噴霧管); 상기 재배조의 상부 개구부를 외부의 공기와 차단되게 밀폐하여 유해균의 침입(侵入)을 방지하도록 매직테이프로 개폐가능하게 접합된 차광 및 보온성의 덮개막을; 포함하여 구성된 것이다.본 발명에 의하면, 보일러에 의해 100℃로 가열된 온수에 의해 멸균, 또는 미생물의 활성이 억제되게 청정처리 된 상기 재배조에서 식물의 영양과 멸균 또는 미생물의 활동을 억제하는 효능을 가진 양액(Liquid nutrion)을 흡수시킨 재배포(栽培布)를 재배판에 깔고 씨앗을 살포하여 재배조의 물에 떠 있는 부판(浮板)위에 놓고 덮개막에 의해 재배조의 개구부가 밀폐된 청정 환경에서 초음파 가습기에서 생성된 안개를 상기 분무관을 통하여 가습하면서 재배하여, 3 ~ 4일의 극히 단기간에 미생물에 오염되지 않은 청정의 새싹 작물을 수확할 수 있다. claims: 가습기에 의해 가습하는 새싹 재배장치에 있어서,물을 정화하고 가열하는 다기능성 보일러와: 상기 보일러에 의해 가열된 물이 일정한 수위로 채워져 재배의 적정온도를 유지하는 청정 재배조와; 상기 재배조의 좌우 양측 가장자리 및 중앙부에 배치되어 가습기에 의해 생성된 안개를 분무(噴霧)하여 가습하는 복수의 분무관(噴霧管)과 ; 상기 재배조의 상부 개구부를 외부의 공기와 차단되게 밀폐하도록 매직테이프로 개폐가능하게 접합된 차광 및 보온성의 덮개막을; 포함하여 구성된 것을 특징으로 하는 청정 새싹의 재배장치.제2항에 있어서.새싹의 재배판은 재배포에 흡수된 양액에 의해 청정처리 되는 것을 특징으로 하는 청정 새싹의 재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

465/1059 Row 465: application_number: 1020190081411, combined_string: invention_title: 구근류 채굴장치 abstract: 본 발명은 구근류 채굴장치에 관한 것으로, 작업 차량에 연결되어 견인되는 프레임의 전방 하부에 구비되어 두둑 속의 작물을 채굴하는 굴취삽과, 굴취삽에 의해 채굴된 작물과 함께 제공되는 흙을 털어내 제거하여 작물을 이송시키는 제토컨베이어를 포함하는 채굴유니트를 갖는 구근류 채굴장치로서, 굴취삽은 그 선단부가 두둑을 향하도록 하향 경사지게 구비되되, 굴취삽의 후단부는 제토컨베이어의 전방 하부 영역에서 제토컨베이어와 이격된 상태로 제토컨베이어의 하면을 향하는 기울기로 경사지게 구비되어, 굴취삽에 의해 작물과 두둑이 파내어짐과 동시에 제토컨베이어에 접하여 작물과 흙이 분리되도록 한 구근류 채굴장치를 제공한다. claims: 작업 차량에 연결되어 견인되는 프레임의 전방 하부에 구비되어 두둑 속의 작물을 채굴하는 굴취삽과, 굴취삽에 의해 채굴된 작물과 함께 제공되는 흙을 털어내 제거하여 작물을 이송시키는 제토컨베이어를 포함하는 채굴유니트를 갖는 구근류 채굴장치로서, 굴취삽은 그 선단부가 두둑을 향하도록 하향 경사지게 구비되고, 굴취삽의 후단부는 제토컨베이어의 전방 하부 영역 내에서 제토컨베이어와 이격된 상태로 제토컨베이어의 하면을 향하는 기울기인 제토컨베이어의 하면 하단부와 만나는 선을 갖도록 경사지게 구비되어, 굴취삽에 의해 작물과 두둑이 파내어짐과 동시에 제토컨베이어에 접하여 작물과 흙이 분리되도록 하되, 두둑을 향하는 굴취삽의 선단부는 제토컨베이어의 전방 하부 영역을 벗어나 제토컨베이어의 전방으로 돌출되게 구비되는 구근류 채굴장치., Ltext: 농업, prediction: 임업
466/1059 Row 466: application_number: 1020190080160, combined_string: invention_title: 수직 재배대의 수평 순환을 이용하는 컨테이너 팜 abstract: 본 발명은 수직 재배대의 수평 순환을 이용하는 컨테이너 팜에 관한 것으로서, 컨테이너 내부의 천정 부근에 폐곡선을 이루도록 설치되는 레일, 레일에 이동 가능하게 결합되는 다수의 이동부재, 재배 식물이 심긴 포트가 장착되는 포트 장착 홈이 일정 간격으로 복수 개 형성된 수직 재배대, 레일에 결합된 이동부재를 이동시키는 이동조절수단을 포함하여 이루어진다. 이동부재 각각에 수직 재배대가 장착되어, 이동부재가 이동함에 따라 각 수직 재배대가 레일을 따라 수평 경로로 순환한다. 컨테이너의 내부 공간을 순환하는 수직 재배대를 이용하여 식물을 재배함에 따라, 컨테이너의 협소한 내부 공간을 최대한 재배 공간으로 활용할 수 있어서 식물 재배 밀도를 높일 수 있다. 또한, 재배 공간에 진입하지 않고 작업 공간에서 모든 식물을 관리할 수 있어서, 작물의 수확과 관리 등 운용이 편리해지며, 적은 인원으로 작물을 재배할 수 있다. claims: 컨테이너 내부의 천정 부근에 폐곡선을 이루도록 설치되는 레일;상기 레일에 이동 가능하게 결합되는 다수의 이동부재;재배 식물이 심긴 포트가 장착되는 포트 장착 홈이, 일정 간격으로 복수 개 형성된, 수직으로 긴 형상의 수직 재배대;상기 레일에 결합된 이동부재를 이동시키는 이동조절수단; 및상기 컨테이너 내부의 재배 환경을 조절하는 재배환경 조절 수단을 포함하여 이루어지고,상기 이동부재 각각에 상기 수직 재배대가 장착되어, 상기 이동부재가 이동함에 따라 상기 각 수직 재배대가 상기 레일을 따라 수평 경로로 순환하며,상기 레일이 형성하는 폐곡선은 외측을 'ㄷ' 형태로 감싸는 경로와, 이 외측을 감싸는 경로의 내부를 2회 이상 왕복하는 직선 경로를 포함하고,상기 각 수직 재배대에는 적어도 수용된 식물 관련 정보가 기록된 전자 코드가 표시되며,상기 재배환경 조절 수단은,상기 수직 재배대에 수용된 식물에 물과 영양분을 공급하는 영양분 공급부;상기 수직 재배대에 수용된 식물에 빛을 공급하는 조명부;상기 컨테이너 내부의 온도를 조절하는 온도 조절부;상기 컨테이너 내부의 습도를 조절하는 습도 조절부;상기 컨테이너 내부로 신선한 공기를 공급하고,상기 컨테이너 내부의 오염된 공기를 배출시키는 공조부;상기 수직 재배대에 표시된 전자 코드를 촬영하는 제1 카메라부;상기 수직 재배대에 수용된 각 식물을 촬영하는 제2 카메라부; 및상기 제1 카메라부에 의해 촬영된 전자 코드 정보와, 상기 제2 카메라부에 의해 촬영된 식물 상태 정보 중 적어도 하나 이상을 이용하여 재배 환경을 조절하는 제어부를 포함하여 이루어지며,상기 수직 재배대는 속이 빈 통의 형태로 구성되고, 상기 영양분 공급부는 상기 빈 통의 상단에서 물과 영양분을 공급하도록 구성되어, 물과 영양분이 상기 수직 재배대의 내부 공간을 따라 흘러내리면서 각 포트에 형성된 구멍을 통해 식물에 공급되는 것을 특징으로 하는, 컨테이너 팜., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

467/1059 Row 467: application_number: 1020190079446, combined_string: invention_title: 머드 및 솔잎의 유효성분을 함유한 새싹 보리 재배방법 및 이에 의해 재배된 새싹 보리 abstract: 본 발명은 머드 및 솔잎의 유효성분을 함유한 새싹 보리 재배방법에 관한 것으로서, 발아에 적합한 보리를 선별하고 세척하는 선별 및 세척단계와, 머드 및 솔잎추출액을 이용하여 기능성 수용액을 제조하고, 상기 선별 및 세척된 보리를 상기 기능성 수용액에 침지시킨 후 불리는 불림단계와, 상기 기능성 수용액으로 불린 보리를 발아시키는 발아단계와, 상기 발아된 보리를 기능성 상토가 수용된 모종판에 식재하여 생육하는 생육단계 및 상기 생육된 새싹 보리를 채취하고 포장하는 채취 및 포장단계를 포함하여 재배되는 것을 특징으로 한다. 상기의 방법으로 재배된 새싹 보리는 머드 및 솔잎이 포함된 기능성 수용액을 보리의 발아 및 생육과정에서 사용함에 따라 머드 및 솔잎의 유효한 성분이 자연스럽게 흡수되고, 특히, 머드에 함유된 게르마늄이 보리의 발아 및 생육과정에서 자연스럽게 흡수되도록 하여 새싹 보리를 섭취하는 것으로 머드의 유효한 성분을 함께 섭취할 수 있는 장점이 있다. claims: 발아에 적합한 보리를 선별하고 세척하는 선별 및 세척단계(S10);머드 및 솔잎추출액을 이용하여 기능성 수용액을 제조하고, 상기 선별 및 세척된 보리를 상기 기능성 수용액에 침지시킨 후, 15~20℃의 온도를 유지하면서 48~72시간 동안 불리는 불림단계(S20);상기 기능성 수용액으로 불린 보리를 온도 28~30℃, 습도 75~80%의 범위를 유지시키면서, 20~25시간 동안 발아시키는 발아단계(S30);상기 발아된 보리를 기능성 상토가 수용된 모종판에 식재하여 생육하는 생육단계(S40); 및 상기 생육된 새싹 보리를 채취하고 포장하는 채취 및 포장단계(S50);를 포함하여 재배되되, 상기 기능성 수용액은, (i) 머드를 채취하여 이물질을 제거하는 전처리단계;(ii) 상기 전처리된 머드를 세척하여 염분함량을 50% 이하로 낮추는 세척단계;(iii) 상기 세척된 머드를 함수율이 20~30%의 범위가 되도록 건조한 후 입자크기가 0.1~0.2mm가 되도록 분쇄하는 건조 및 분쇄단계;(iv) 상기 건조 및 분쇄된 머드분말을 멸균처리하는 멸균단계; (v) 상기 멸균된 머드분말 100중량부에 정제수 700~800중량부를 혼합하는 혼합단계; 및 (vi) 상기 정제수가 혼합된 머드수 100중량부에 솔잎추출액을 15~20중량부 추가하는 추가단계;를 포함하여 제조되고,상기 솔잎추출액은, 소나무의 잎을 세척 및 건조하고 5~10mm 크기로 분쇄한 후, 상기 분쇄된 솔잎에 물을 중량대비 1 : 3~5의 비율로 혼합하고 90~110℃의 온도에서 2~3시간 동안 가열한 후 여과하여 제조된 것이며,상기 생육단계(S40)의 기능성 상토는,원예용 상토 100중량부에 솔잎분말 5~7중량부, 해조류 추출물 3~5중량부를 혼합하여 제조되되,상기 솔잎분말은 소나무의 잎을 세척 및 건조한 후, 0.5~2mm 크기로 분쇄한 것이고,상기 해조류 추출물은 미역, 다시마, 톳 중 하나 또는 둘 이상을 혼합한 해조류를 세척하고, 수분함량이 5~10%가 되도록 건조한 후, 입자크기가 100~120mesh의 크기로 분쇄한 해조류분말에 정제수를 중량대비 1 : 7~10의 비율로 혼합하여 70~80℃의 온도에서 5~6시간 동안 교반가열하여 액상의 추출물을 수득한 후, 감압농축 및 동결건조한 것이며,상기 생육단계(S40)는,상기 발아된 보리를 생육하는 과정에서 5~7시간 간격으로, 모종판 부피대비 10~15%의 기능성 수용액을 공급하는 것을 특징으로 하는 머드 및 솔잎의 유효성분을 함유한 새싹 보리 재배방법., Ltext: 농업, prediction: 임업
468/1059 Row 468: application_number: 1020190076890, combined_string: invention_title: 작물용 재배장치 및 이를 이용한 재배방법 abstract: 본 발명은 작물용 재배장치 및 이를 이용한 재배방법에 관한 것으로, 토압의 영향을 많이 받는 작물을 재배함에 있어서, 본 발명에 토압 조절부를 포함시킴으로써, 작물용 재배장치에 토양을 채우기 전 토압 조절부에 공기를 주입하여 토양에 공간을 확보하고, 작물이 성장하는 과정에서 토양이 밀려나게 되면 팽창부재에 공기를 유출시켜 팽창부재가 차지하던 공간에 밀려난 토양이 채워질 수 있도록 하여, 작물이 성장하는데 용이하게 공간이 확보될 수 있도록 하는 작물용 재배장치 및 이를 이용한 재배방법을 제공하는데 목적이 있다.상기한 목적을 달성하기 위해 본 발명은, 작물용 재배장치에 있어서, 작물이 재배될 수 있도록 토양이 저장되는 본체 하우징; 상기 본체 하우징에 삽입되는 토압 조절부; 상기 토압 조절부에 공기가 유·출입될 수 있도록 하는 공기 조절부 및 상기 작물에 영양분이 공급될 수 있도록 하는 영양 공급관을 포함하며, 상기 토압 조절부는, 상기 본체 하우징 내부에 삽입되는 다수개의 공기 이동관; 상기 공기 이동관과 공기 이동관이 연결될 수 있도록 하는 연결부재; 상기 다수개의 공기 이동관 중 어느 하나와 결합되는 공기 조절관 및 상기 공기 조절관이 개폐될 수 있도록 하는 밸브를 포함하는 것을 특징으로 하는 작물용 재배장치이다. claims: 작물용 재배장치에 있어서,작물이 재배될 수 있도록 토양이 저장되는 본체 하우징;상기 본체 하우징에 삽입되는 토압 조절부;상기 토압 조절부에 공기가 유·출입될 수 있도록 하는 공기 조절부 및상기 작물에 영양분이 공급될 수 있도록 하는 영양 공급관을 포함하며,상기 토압 조절부는,상기 본체 하우징 내부에 삽입되는 다수개의 공기 이동관;상기 공기 이동관과 공기 이동관이 연결될 수 있도록 하는 연결부재;상기 다수개의 공기 이동관 중 어느 하나와 결합되는 공기 조절관 및상기 공기 조절관이 개폐될 수 있도록 하는 밸브를 포함하는 것을 특징으로 하는 작물용 재배장치.제 1항 내지 제 5항 중 어느 하나인 작물용 재배장치를 이용한 작물 재배방법에 있어서,상기 공기 조절부를 통해 상기 팽창부재에 공기를 유입하는 단계;상기 확장된 팽창부재 사이에 토양을 채우는 단계;상기 채워진 토양에 물을 공급하는 단계;상기 공급된 물은 상기 토양에 흡수되고, 흡수되지 않은 물을 배수하는 단계;상기 팽창부재가 위치된 곳에 작물을 심는 단계 및상기 작물이 성장하는 동안 상기 팽창부재에서 공기를 유출시키는 단계를 포함하는 것을 특징으로 하는 작물 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

469/1059 Row 469: application_number: 1020190072540, combined_string: invention_title: 알곡 선별장치 abstract: 본 발명은 구조가 단순하고 기능적으로 합리적이며, 무동력 자연 낙하방식을 통해 싸라기를 선별스프링의 강선 와이어 사이로 간단하게 낙하시켜 효율적으로 선별할 수 있음은 물론 선별하고자 하는 알곡 및 싸라기의 크기 변화에 적합한 싸라기 낙하 통과 간격을 용이하게 조정 가능하여 매우 편리하고, 제조 및 관리의 편리성과 유지 비용의 경제성을 향상시킬 수 있도록 개량한 알곡 선별장치에 관한 것이다. claims: 알곡(11) 및 싸라기(12)로 이루어지는 도정된 곡물이 유입구(a)로 공급되고, 상기 곡물을 이동시키면서 싸라기(12)를 낙하시키고 알곡(11)만을 배출구(b)로 낙하시켜 분리시키는 단위체인 선별부재(1)를 포함하되;상기 선별부재(1)는 강선 와이어(21)가 나선형으로 권선되어 이루어지는 선별스프링(2)과, 도정된 곡물 유입구(a)가 형성된 전방소켓(3)과, 선별된 알곡(11)을 배출시키는 배출구(b)가 형성된 후방소켓(4) 및 낙하물을 차단하는 차양판(5)으로 이루어지고;상기 선별스프링(2)의 양단은 전방소켓(3) 및 후방소켓(4)에 끼워진 후 고정되면서 강선 와이어(21) 틈새의 간격이 변화될 수 있도록 이루어지며;상기 선별부재(1)는 도정된 곡물이 이동하면서 싸라기(12)를 선별스프링(2)의 강선 와이어(21)의 틈새로 낙하시키고 알곡(11)만이 후방소켓(4)의 배출구(b)로 배출하여 분리 수집할 수 있도록 경사지게 이루어진 것에 있어서,상기 차양판(5)은 상부편(51)과 하부편(52)으로 분할 형성하되, 상부편(51)이 하부편(52)의 상측 일부를 덮을 수 있도록 단차를 이루는 연장부(511)가 형성되어 이루어지고;상기 차양판(5)의 상부편(51)과 하부편(52)에는 걸림돌기(5a, 5b)를 형성하고 전방소켓(3) 및 후방소켓(4)에는 상기 걸림돌기(5a, 5b)가 걸려 고정되도록 걸림홈(31, 41)을 각각 형성하여 고정하거나, 상부편(51)과 하부편(52)이 양단이 전방소켓(3) 및 후방소켓(4)에 나사못(6)의 체결로 고정될 수 있도록 이루어진 것을 특징으로 하는 알곡 선별장치.알곡(11) 및 싸라기(12)로 이루어지는 도정된 곡물이 유입구(a)로 공급되고, 상기 곡물을 이동시키면서 싸라기(12) 및 쭉정이를 낙하시키고 알곡(11)만을 배출구(b)로 낙하시켜 분리시키는 단위체인 선별부재(1')를 포함하여 이루어지는 알곡(11) 선별장치에 있어서,상기 선별부재(1')는 강선 와이어(21)가 나선형 코일스프링 형태로 권선되어 이루어지는 선별스프링(2)과, 도정된 곡물 유입구(a)가 형성된 전방소켓(3)과, 선별된 알곡(11)을 배출시키는 배출구(b)가 형성된 후방소켓(4') 및 낙하물을 차단하는 차양판(5')으로 이루어지고;상기 선별스프링(2)의 일단은 전방소켓(3)에 끼워진 후 고정되며;상기 선별스프링(2)의 타단은 후방소켓(4')으로 유입되어 이동하는 연결관(9)에 끼워진 후 고정되고;상기 차양판(5')은 단일체로 형성되고 양단에 걸림돌기(5c)를 형성하여 전방소켓(3) 및 후방소켓(4')에 형성된 걸림홈(31, 41)에 끼워져 고정되거나, 나사못(6)의 체결로 고정될 수 있도록 이루어지고;상기 연결관(9)의 이동시 선별스프링(2)의 강선 와이어(21)의 틈새가 가변될 수 있도록 이루어지며;상기 선별부재(1')는 도정된 곡물이 자중에 의해 이동하면서 싸라기(12)를 선별스프링(2)의 강선 와이어(21)의 틈새로 낙하시키고 알곡(11)만이 연결관(9)의 배출구(b)로 낙하시키도록 경사를 이루는 것을 특징으로 하는 알곡 선별장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

470/1059 Row 470: application_number: 1020190070019, combined_string: invention_title: 새싹삼 수경재배장치 및 새싹삼 수경재배방법 abstract: 본 발명은 새싹삼 수경재배장치 및 새싹삼 수경재배방법에 관한 것으로,설치구조가 매우 간단하여 시설투자비가 적게 들고, 장소의 구애됨이 없이 설치가 가능하며, 전문 재배기술이나 많은 경험이 없는 초심자라도 누구나 재배가 가능하며, 토양의 관리에 대한 걱정이 없는 등 관리가 매우 용이함은 물론,가장 핵심적인 것은 묘삼을 꽂아 세우는 방식이 아니라 단순히 머리부분이 상측방향을 향하도록 경사지게 안착시켜 주고 뿌리부분을 덮는 방식으로 구성된 것이어서, 묘삼의 가늘고 연약한 뿌리나 외피(표피) 등의 훼손이 전혀 없으므로 묘삼의 생장에 장애가 되는 요소가 완벽하게 차단되며,묘삼에는 재배 중 수분이 항상 충분하게 공급되어야 하는데 본 발명에서는 바닥면을 구성하는 베이스시트부재가 물을 통과시켜 주기는 하나 어느 정도 물기를 머금을 수 있고 특히, 흡습부재가 물을 장시간 머금은 상태를 유지하므로 종래보다 적은 양을 물을 공급하여 주어도 묘삼에 물을 장시간 지속적으로 공급하여 줄 수 있어서 생장이 촉진되며, 워터펌프의 가동시간 및 횟수를 줄여 줄 수 있으므로 운영단가도 매우 저렴하게 되는 등 결과적으로 적은 비용으로 누구나 간편하고 손쉽게 전체적으로 품질이 균일한 양질의 새싹인삼을 안전하게 대량 재배할 수 있는 것을 그 특징으로 한다. claims: 어린 묘삼(10)을 소정기간동안 키워낼 수 있는 수경재배장치를 구성함에 있어서,다단으로 구획되고, 각각의 구획부(100a) 상측에 스프링클러(110)를 구비한 기틀체(100)와;다단으로 구획된 각각의 구획부(100a) 바닥면을 이루도록 설치되며 섬유, 합성수지재 또는 부직포 중 어느 하나 또는 이들의 혼합물로서 물이 용이하게 통과하도록 망 또는 엉성한 조직을 갖도록 만들어진 베이스시트부재(200)와;상기 베이스시트부재 상에 소정간격으로 안착되며 스펀지(sponge)나 면, 합성수지재, 식물줄기를 재직하거나 부직포, 팰트 형태로 만든 적어도 하나 이상으로서 물기를 흡습하는 흡습부재(300)와;그리고 맨 하단의 베이스시트부재(200) 저면에 설치되어 하측으로 낙하하는 물을 스프링클러(110)와 연계설치되는 워터펌프(510)가 구비된 물저장탱크(500)로 회수하는 물받이(400) 및;상기 워터펌프(510)를 수동 또는 설정된 시간 마다 자동으로 동작시켜 주는 제어부를 포함하여 이루어지되,상기 흡습부재(300)의 안착시 먼저 안착시킨 흡습부재(300)에 묘삼(10)의 머리부분을 올려 놓고 뿌리부분은 베이스시트부재(200)에 안착시켜 전체적으로 머리부분이 상측방향을 향하도록 한다음,다음번 흡습부재(300)를 묘삼(10)의 뿌리부분을 덮어주도록 안착시키는 방법을 반복하여 소정간격으로 대량의 묘삼(10)을 경사지게 안착시키고 스프링클러(110)를 이용하여 물을 공급하여 일부는 흡습부재(300)가 머금어 묘삼(10)의 뿌리가 마르지 않도록 지속적으로 수분을 공급하고,일부는 베이스시트부재(200)를 통과하면서 낙하하여 물받이(400)를 통해 물저장탱크(500)로 회수되어 재활용되면서 새싹삼을 재배토록 이루어짐을 특징으로 하는 새싹삼 수경재배장치.소정폭과 길이 및 높이로 구축한 기틀체(100)에 소정높이로 섬유, 합성수지재 또는 부직포 중 어느 하나 또는 이들의 혼합물로서 물이 통과하도록 만들어진 베이스시트부재(200)를 깔아 바닥면을 형성하는 단계(S1)와;상기 베이스시트부재(200) 상면에 소정간격으로 스펀지(sponge)나 면, 합성수지재, 식물줄기를 재직하거나 부직포, 팰트 형태로 만든 적어도 하나 이상으로서 물기를 흡습하는 흡습부재(300)를 안착시키되,먼저 베이스시트부재(200) 상면에 첫번째 흡습부재(300)를 안착시킨 후 안착시킨 흡습부재(300)에 묘삼(10)의 머리부분을 올려 놓고 뿌리부분은 베이스시트부재(200)에 안착시켜 전체적으로 머리부분이 상측방향을 향하도록 하는 단계(S2)와;상기 첫번째 흡습부재(300)에 머리부분이 올려진 묘삼(10)의 뿌리부분을 두번째 흡습부재를 이용하여 덮어 주는 단계(S3)와;상기 단계(S3)에서 묘삼(10)의 뿌리부분을 덮고 있는 흡습부재(300)에 재차 묘삼(10)의 머리부분을 올려 놓고 뿌리부분은 베이스시트부재(200)에 안착시켜 전체적으로 머리부분이 상측방향을 향하도록 한 다음, 그 다음번 흡습부재(300)를 묘삼(10)의 뿌리부분을 덮어 주는 방법을 연속적으로 반복하여 대량의 묘삼(10)을 경사지게 안착 완료하는 단계(S4)와;상기 단계(S4) 수행 후 제어부를 수동 또는 자동으로 제어하여 워터펌프(510)를 작동시켜 물저장탱크(500)내의 물이나 양액을 스프링클러(110)를 통해 묘삼에 공급하여 일부는 흡습부재(300)가 머금어 묘삼(10)의 뿌리가 마르지 않도록 지속적으로 수분을 공급하고,일부는 베이스시트부재(200)를 통과하면서 낙하하여 물받이(400)를 통해 워터펌프(510)가 구비된 물저장탱크(500)로 회수되어 재활용시키는 단계(S5);를 포함하여 새싹삼을 재배토록 이루어짐을 특징으로 하는 새싹삼 수경재배방법., Ltext: 농업, prediction: 임업
471/1059 Row 471: application_number: 1020190068464, combined_string: invention_title: 유기 바나듐을 함유한 벼의 재배방법 abstract: 본 발명은 유기 바나듐을 함유한 벼의 재배방법에 관한 것으로,바나듐 원료를 300메시 이하의 크기로 파쇄하는 과정과,맥반석, 토루말린, 제오라이트, 견운모 및 황토을 각각 300메시 이하의 크기로 파쇄하여 적어도 하나 이상 동일한 비율로 혼합하는 과정과,파쇄한 바나듐 원료 80~90중량%에 300메시 이하의 크기로 파쇄한 맥반석, 토루말린, 제오라이트, 견운모, 황토의 무기물 10~20중량%를 혼합하여 바나듐 혼합물을 제조하는 과정과,상기의 바나듐 혼합물을 물에 500배 정도 희석하여 바나듐 희석액을 제조하는 과정과,상기의 바나듐 희석액을 비료 주듯이 벼의 이삭이 맺히기 시작하는 시기를 전후하여 2-3회 정도 뿌려주는 과정에 의하여 벼의 이삭에 바나듐 물질이 형성되도록 함으로써 쌀에서 강력한 항산화력으로 활성산소 제거하면서 신체 조직의 노화와 변성을 막거나 속도를 지연시키는 효과가 있는 바나듐 성분이 검출되도록 하고, 무기질에 의한 원적외선과 음이온 등을 발생하여 식물의 생장에 도움을 주도록 함은 물론, 미네랄 종류의 영양제로서 벼가 왕성하게 성장하도록 도와주도록 구성됨을 특징으로 한다. claims: 바나듐 원료를 300메시 이하의 크기로 파쇄하는 과정과,맥반석을 300메시 이하의 크기로 파쇄하는 과정과,토루말린을 300메시 이하의 크기로 파쇄하는 과정과,제오라이트를 300메시 이하의 크기로 파쇄하는 과정과,견운모를 300메시 이하의 크기로 파쇄하는 과정과,황토를 300메시 이하의 크기로 파쇄하는 과정과,상기의 맥반석, 토루말린, 제오라이트, 견운모 및 황토의 무기질을 적어도 하나 이상 동일한 비율로 혼합하는 과정과,파쇄한 바나듐 원료 80~90중량%에 300메시 이하의 크기로 파쇄한 맥반석, 토루말린, 제오라이트, 견운모, 황토의 무기물 10~20중량%를 혼합하여 바나듐 혼합물을 제조하는 과정과,상기의 바나듐 혼합물을 물에 500배 정도 희석하여 바나듐 희석액을 제조하는 과정과,상기의 바나듐 희석액을 비료 주듯이 벼의 이삭이 맺히기 시작하는 시기를 전후하여 2-3회 정도 뿌려주는 과정으로 구성한 것을 특징으로 하는 유기 바나듐을 함유한 벼의 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

472/1059 Row 472: application_number: 1020190068465, combined_string: invention_title: 유기 셀레늄을 함유한 벼의 재배방법 abstract: 본 발명은 유기 셀레늄을 함유한 벼의 재배방법에 관한 것으로,셀레늄 원료를 300메시 이하의 크기로 파쇄하는 과정과,맥반석, 토루말린, 제오라이트, 견운모 및 황토을 각각 300메시 이하의 크기로 파쇄하여 적어도 하나 이상 동일한 비율로 혼합하는 과정과,파쇄한 셀레늄 원료 80~90중량%에 300메시 이하의 크기로 파쇄한 맥반석, 토루말린, 제오라이트, 견운모, 황토의 무기물 10~20중량%를 혼합하여 셀레늄 혼합물을 제조하는 과정과,상기의 셀레늄 혼합물을 물에 500배 정도 희석하여 셀레늄 희석액을 제조하는 과정과,상기의 셀레늄 희석액을 비료 주듯이 벼의 이삭이 맺히기 시작하는 시기를 전후하여 2-3회 정도 뿌려주는 과정에 의하여 벼의 이삭에 셀레늄 물질이 형성되도록 함으로써 쌀에서 암의 예방과 치료, 에이즈 증상 완화, 제2형 당뇨병 억제 등에 효과가 있는 셀레늄 성분이 검출되도록 하고, 무기질에 의한 원적외선과 음이온 등을 발생하여 식물의 생장에 도움을 주도록 함은 물론, 미네랄 종류의 영양제로서 벼가 왕성하게 성장하도록 도와주도록 구성됨을 특징으로 한다. claims: 셀레늄 원료를 300메시 이하의 크기로 파쇄하는 과정과,맥반석을 300메시 이하의 크기로 파쇄하는 과정과,토루말린을 300메시 이하의 크기로 파쇄하는 과정과,제오라이트를 300메시 이하의 크기로 파쇄하는 과정과,견운모를 300메시 이하의 크기로 파쇄하는 과정과,황토를 300메시 이하의 크기로 파쇄하는 과정과,상기의 맥반석, 토루말린, 제오라이트, 견운모 및 황토의 무기질을 적어도 하나 이상 동일한 비율로 혼합하는 과정과,파쇄한 셀레늄 원료 80~90중량%에 300메시 이하의 크기로 파쇄한 맥반석, 토루말린, 제오라이트, 견운모, 황토의 무기물 10~20중량%를 혼합하여 셀레늄 혼합물을 제조하는 과정과,상기의 셀레늄 혼합물을 물에 500배 정도 희석하여 셀레늄 희석액을 제조하는 과정과,상기의 셀레늄 희석액을 비료 주듯이 벼의 이삭이 맺히기 시작하는 시기를 전후하여 2-3회 정도 뿌려주는 과정으로 구성한 것을 특징으로 하는 유기 셀레늄을 함유한 벼의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

473/1059 Row 473: application_number: 1020190068702, combined_string: invention_title: 수확기 및 콤바인 abstract: 언로더를 사용한 수확물의 배출 시에 수확물에 과잉의 힘이 가해지지 않는 수확기를 제공한다. 또한, 언로더에 큰 부하가 가해지는 것을 피할 수 있는 수확기를 제공한다. 또한, 운전자의 의도대로 예취 곡간의 긁어 넣기가 가능한 콤바인을 제공한다.수확기는, 엔진으로부터의 동력을 사용하여 수확물을 수확물 탱크로부터 기체의 외부로 배출하는 반송 기구를 갖는 언로더와, 반송 기구를 구동하는 온 위치와 반송 기구를 정지하는 오프 위치를 갖는 배출 클러치와, 클러치 온 명령에 기초하여, 배출 클러치를 온 위치로 전환하는 온 동작 신호를 출력하는 배출 클러치 제어부와, 엔진의 회전수를, 아이들링 회전수와 정격 회전수 사이의 배출 회전수로 조절하는 엔진 제어 유닛을 구비하고 있다. 배출 클러치 제어부는, 클러치 온 명령에 기초하여 엔진 제어 유닛에 배출 회전수로의 조절을 요구하고, 엔진의 회전수가 배출 회전수에 도달한 때에 온 동작 신호를 출력한다. 또한, 수확기는, 수확물 탱크로부터 기체의 외부로 수확물을 배출하는 배출 자세와, 기체에 수납 보유 지지되는 수납 자세 사이에서 자세 변경 가능한 언로더의 자세를 검출하는 자세 검출부와, 주행 장치에 대한 거동 요구를 출력하는 주행 조작구와, 주행 장치의 거동을 제어하는 주행 제어 모드로서, 제1 주행 제어 모드와, 주행 시에 상기 언로더에 미치는 관성 부하가 상기 제1 주행 제어 모드보다 적어지는 제2 주행 제어 모드를 관리하는 주행 제어 모드 관리부와, 자세 검출부가 상기 수납 자세를 검출하고 있는 경우에, 상기 제1 주행 제어 모드를 사용하여 상기 거동 요구에 기초하여 상기 주행 장치를 제어하고, 자세 검출부가 수납 자세 이외를 검출하고 있는 경우에, 제2 주행 제어 모드를 사용하여 거동 요구에 기초하여 주행 장치를 제어하는 주행 제어부를 구비한다. 또한, 엔진의 동력에 의해 구동하는 주행 장치와, 기체에 상하 요동 가능하게 지지되어, 엔진의 동력에 의해 구동하고, 포장의 식립 곡간을 예취하여 반송하는 예취부와, 제1 조작구의 조작에 기초하여, 엔진으로부터의 동력을 예취부로 전달하는 전달 상태와, 엔진으로부터의 동력을 예취부로 전달하지 않는 비전달 상태로 전환되는 클러치 기구(2020)와, 예취부가 미리 정해진 설정 높이 H1 이상으로 상승되면, 클러치 기구(2020)를 비전달 상태로 변경하는 자동 전환부(2032)와, 제2 조작구(2054)의 조작에 기초하여, 주행 장치가 정지하면서 예취부가 구동하는 긁어 넣기 상태를 현출하는 긁어 넣기부가 구비되어 있다. 긁어 넣기부는, 자동 전환부(2032)에 의해 클러치 기구(2020)가 비전달 상태로 되어 있는 상태일 때는, 클러치 기구(2020)를 강제적으로 전달 상태로 변경한다. claims: 수확된 수확물을 저류하는 수확물 탱크와,엔진으로부터의 동력을 사용하여 상기 수확물을 상기 수확물 탱크로부터 기체의 외부로 배출하는 반송 기구를 갖는 언로더와,상기 반송 기구를 구동하는 온 위치와 상기 반송 기구를 정지하는 오프 위치를 갖는 배출 클러치와,클러치 온 명령에 기초하여, 상기 배출 클러치를 상기 온 위치로 전환하는 온 동작 신호를 출력하고, 클러치 오프 명령에 기초하여 상기 배출 클러치를 상기 오프 위치로 전환하는 오프 동작 신호를 출력하는 배출 클러치 제어부와,상기 엔진의 회전수를, 아이들링 회전수와, 정격 회전수와, 상기 아이들링 회전수와 상기 정격 회전수 사이의 배출 회전수로 조절하는 엔진 제어 유닛을 구비하고,상기 배출 클러치 제어부는, 상기 클러치 온 명령에 기초하여 상기 엔진 제어 유닛에 상기 배출 회전수로의 조절을 요구하고, 상기 엔진의 회전수가 상기 배출 회전수에 도달한 때에 상기 온 동작 신호를 출력하는, 수확기.주행 장치와, 수확된 수확물을 저류하는 수확물 탱크와,상기 수확물 탱크로부터 기체의 외부로 상기 수확물을 배출하는 배출 자세와, 상기 기체에 수납 보유 지지되는 수납 자세 사이에서 자세 변경 가능한 언로더와,상기 언로더의 자세를 검출하는 자세 검출부와,상기 주행 장치에 대한 거동 요구를 운전자의 조작에 기초하여 출력하는 주행 조작구와,상기 주행 장치의 거동을 제어하는 주행 제어 모드로서, 제1 주행 제어 모드와, 주행 시에 상기 언로더에 미치는 관성 부하가 상기 제1 주행 제어 모드보다 적어지는 제2 주행 제어 모드를 관리하는 주행 제어 모드 관리부와,상기 자세 검출부가 상기 수납 자세를 검출하고 있는 경우에, 상기 제1 주행 제어 모드를 사용하여 상기 거동 요구에 기초하여 상기 주행 장치를 제어하고, 상기 자세 검출부가 상기 수납 자세 이외를 검출하고 있는 경우에, 상기 제2 주행 제어 모드를 사용하여 상기 거동 요구에 기초하여 상기 주행 장치를 제어하는 주행 제어부를 구비한, 수확기.엔진과,상기 엔진의 동력에 의해 구동하는 주행 장치와,기체에 상하 요동 가능하게 지지되어, 상기 엔진의 동력에 의해 구동하고, 포장의 식립 곡간을 예취하여 반송하는 예취부와,제1 조작구의 조작에 기초하여, 상기 엔진으로부터의 동력을 상기 예취부로 전달하는 전달 상태와, 상기 엔진으로부터의 동력을 상기 예취부로 전달하지 않는 비전달 상태로 전환되는 클러치 기구와,상기 예취부가 미리 정해진 설정 높이 이상으로 상승되면, 상기 클러치 기구를 상기 비전달 상태로 변경하는 자동 전환부와,제2 조작구의 조작에 기초하여, 상기 주행 장치가 정지하면서 상기 예취부가 구동하는 긁어 넣기 상태를 현출하는 긁어 넣기부가 구비되고,상기 긁어 넣기부는, 상기 자동 전환부에 의해 상기 클러치 기구가 상기 비전달 상태로 되어 있는 상태일 때는, 상기 클러치 기구를 강제적으로 상기 전달 상태로 변경하는, 콤바인., Ltext: 농업, prediction: 농업
474/1059 Row 474: application_number: 1020190066519, combined_string: invention_title: 수확기 abstract: 본 발명의 과제는 엔진 보닛의 상방에 배치된 운전 좌석을 가진 수확기에 있어서, 운전부를 대형화하지 않고 배기 가스 정화 장치와 운전 좌석의 기체 상하 방향에서의 겹침을 회피하면서 배기 가스 정화 장치를 엔진 보닛 내의 디젤 엔진의 상방에 설치할 수 있도록 하는 것이다.디젤 엔진(21)의 배기 가스를 도입하여 배기 가스의 정화 처리를 행하는 배기 가스 정화 장치(50)를, 배기 가스 정화 장치(50)의 전체가 운전 좌석(12)에 대해 예취부측으로 치우치고, 또한 배기 가스 정화 장치(50)의 기체 횡방향에서의 일부가 운전부의 예취부측 횡벽(11c)으로부터 예취부측으로 돌출되는 배치로 엔진 보닛(22) 내에 설치하고 있다.본 발명의 과제는 엔진 보닛 내의 디젤 엔진의 상방에 배기 가스 정화 장치를 설치하는 데 있어서, 운전 좌석의 상승을 방지나 억제하면서 설치하는 것을 가능하게 하는 것이다.디젤 엔진(21)의 배기 가스를 도입하여 배기 가스의 정화 처리를 행하는 배기 가스 정화 장치(50)를, 엔진 보닛 내의 디젤 엔진(21)의 상방에 운전 좌석(12)에 대해 기체 횡내측으로 치우치게 하여 설치하고 있다. 엔진 보닛(22)에 있어서의 천장판부(30)의 배기 가스 정화 장치(50)의 상방에 위치하는 정화 장치 상방부(32)가 엔진 보닛(22)에 있어서의 운전 좌석(12)의 하방에 위치하는 좌석 하방부(31)보다 높은 배치 높이에 위치하도록, 천장판부(30)의 형상을 단차 형상으로 하고 있다.본 발명의 과제는 배기 가스 정화 장치에 접속하는 배기관을 유리하게 얻거나 접속 작업하는 것을 가능하게 하면서 배기 가스 정화 장치를 디젤 엔진의 상방에 장비할 수 있도록 하는 것이다.디젤 엔진(21)의 상방에 한 쌍의 지지부(61a, 62a)를 크랭크축 방향과 교차하는 방향으로 나란히 설치하고 있다. 디젤 엔진(21)의 배기 가스를 도입하여 배기 가스의 정화 처리를 행하는 배기 가스 정화 장치(50)를, 길이 방향이 크랭크축 방향과 교차하는 설치 자세로 한 쌍의 지지부(61a, 62a)에 연결하고 있다. claims: 디젤 엔진을 내장하는 엔진 보닛을 구비하고, 상기 엔진 보닛의 상방에 배치된 운전 좌석을 가진 운전부를 구비한 수확기이며,상기 디젤 엔진의 배기 가스를 도입하여 배기 가스의 정화 처리를 행하는 배기 가스 정화 장치를, 상기 엔진 보닛 내의 상기 디젤 엔진의 상방에 상기 운전 좌석에 대해 기체 횡내측으로 치우치게 하여 설치하고,상기 엔진 보닛에 있어서의 천장판부의 상기 배기 가스 정화 장치의 상방에 위치하는 정화 장치 상방부가 상기 엔진 보닛에 있어서의 상기 운전 좌석의 하방에 위치하는 좌석 하방부보다 높은 배치 높이에 위치하도록, 상기 천장판부의 형상을 단차 형상으로 하고 있는, 수확기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

475/1059 Row 475: application_number: 1020190057496, combined_string: invention_title: Ａ자형 버킷 컨베이어식 배종장치를 구비한 파종기 abstract: 본 발명은 작물 파종기에 관한 것으로, 상세하게는, 트랙터 등과 같은 견인장치에 의해 견인되어 밭이랑을 따라 이동하면서 호퍼에 담긴 각종 작물의 종자(예컨대, 통감자 등)를 A자형 버킷 컨베이어 배종장치를 매개로 하나씩 이송한 후 이송된 종자를 좌우로 낙하시켜 밭의 두둑에 심어 파종함으로써 종자 배종시 소요되는 노동력을 최소화할 수 있는 A자형 버킷 컨베이어식 배종장치를 구비한 파종기에 관한 것이다. claims: 견인장치에 견인되는 본체;상기 본체의 후단 상부에 설치되고, 내부에 종자가 수용되는 호퍼; 및상기 호퍼로부터 투입되는 종자를 순차적으로 이송하여 밭이랑에 파종하는 컨베이어식 배종장치;를 포함하고, 상기 컨베이어식 배종장치는, 종자가 수용되는 버킷이 일정 간격으로 설치된 2열의 배종라인을 구비하고, 각 배종라인은 상기 호퍼로부터 공급되는 종자를 차례로 이송한 후 밭이랑에 배출하여 파종하되, 상기 2열의 배종라인은 상부측 사이의 간격은 좁고 하부측 사이의 간격이 벌어지도록 배치되고, 상기 배종라인들의 후단부를 연결하는 연결부재가 구비되어, 후면에서 볼 때 'A'자 형태를 이루도록 하며, 상기 2열의 배종라인의 하부측에 설치된 연결부재는 길이방향으로 길이가 가변되는 구조로 이루어지고, 상기 배종라인의 상부측은 힌지부재 또는 볼 조인트를 매개로 본체에 결합되거나 상호 결합되어 배종라인의 하부 간격이 조정되는 방향으로 회전할 수 있도록 구성되어, 하부측은 상부측을 축으로 하여 서로 멀어지는 방향 또는 서로 근접하는 방향으로 유동하여 배출부 사이의 간격을 조정할 수 있도록 하고,상기 2열의 배종라인은 호퍼가 설치되는 후단부측의 높이가 상대적으로 낮은 경사 구조로 배치되는 것을 특징으로 하는 A자형 버킷 컨베이어식 배종장치를 구비한 파종기., Ltext: 농업, prediction: 임업
476/1059 Row 476: application_number: 1020200173145, combined_string: invention_title: 참외 수경재배 전용 지면매립형 배지용기 abstract: 참외 농사 연작 재배시에 필수적으로 토양 관리비용을 획기적으로 감소시키고 병충해와 병원균으로부터 이를 원천적으로 차단할 수 있는 참외 수경재배 전용 지면매립형 배지용기에 관한 것이다.참외 연작재배시 토양의 병충해 및 병원균의 전파를 차단하고 토양 유지관리를 개별적으로 관리할 수 있도록 토양의 지면에 일부만을 개토 후 방수포를 깐 후 부분 매립시키는 매립설치수단을 구비한다.따라서 본 발명은 위와 같은 본 발명의 참외 수경재배 전용 지면매립형 배지용기는 전술된 바와 같이, 참외재배의 경우 연작농사시 선택적으로 병원균오염 방지와 병충해 방지를 매립설치수단을 통해 효율적으로 할 수 있는 이점이 있고, 또, 토양 주변 잡초나 병충해 등 주변환경의 뿌리 유입을 원천적으로 차단할 수 있는 이점이 있다. claims: 참외 연작재배시 토양의 병충해 및 병원균의 전파를 차단하고 토양 유지관리를 개별적으로 관리할 수 있도록 토양의 지면에 일부만을 개토 후 방수포를 깐 후 부분 매립시키는 매립설치수단(A)을 구비한 지면매립형 배지용기에 있어서,배수가 용이하게 이루어질 수 있는 탈부착형 배지용기 받침대(10)를 지면에 매립시킬 수 있도록 구비한 것과, 상기 배지용기 받침대(10)의 상측에는 참외작물을 흙과 함께 정식할 수 있는 배지용기(20)를 길이방향으로 하나 이상 연결되도록 구비한 것과,상기 배지용기(20)에는 흙의 내부 온도를 외부 조절장치(미도시)에 냉·온수에 의해 조절할 수 있는 지온호스(30)를 구비한 것과,상기 배지용기(20)는,길이 방향으로 상측으로 개방된 몸체(210)를 구비하되, 그 양측에는 받침판(230)을 구비하고,상기 몸체(210)의 길이방향 양측 끝단에는 서로 겹쳐서 연결될 수 있도록 음각 또는 양각 형태를 갖는 음각걸림턱(218)과 양각걸림턱(219)을 구비하며,상기 몸체(210)의 중심 하부에는 편측 또는 양측에 지온호스 고정용 클램프브라켓(220)을 구비하고,상기 클램프브라켓(220)의 전·후측으로 수개의 배수구멍(216)을 구비하며,상기 몸체(210)의 양측에는 상기 몸체(210)의 내면을 따라 돌출되는 격판 가이드레일홈(211)을 구비하고,상기 양측 격판 가이드레일홈(211)에는 지온호스(30)를 통과시키는 수용홈(212)을 구비한 격판(250)을 탈부착형태로 구비하며,상기 몸체(210)의 하부 저면 양측에는 배지용기 받침대(10)의 받침턱(160)을 고정 지지할 수 있도록 걸림브라켓(215)을 구비한 것을 특징으로 한 참외 수경재배 전용 지면매립형 배지용기, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

477/1059 Row 477: application_number: 1020200140095, combined_string: invention_title: 농약 자동 살포장치 abstract: 본 발명은 농약 자동 살포장치에 관한 것으로, 상세하게는, 혼합탱크에 투입된 액상의 농약(또는 물, 사료, 비료 등)을 전기 스위치를 통해 자동으로 개폐되는 분배기를 통해 각각의 고랑을 따라 설치된 메인호스에 자동 공급하고, 메인호스에 각각 'T'자형 분기구를 설치하여 각 농작물(과수 등)을 따라 분기호스를 연결하여 농약을 자동으로 공급함으로써 병충해 방제작업시 작업자의 안전을 도모하고, 농약 사용량을 줄이면서 작업 편의성을 제공하며, 적절한 시기에 병충해 방제작업을 실시하여 병충해 방제작업의 효율성을 향상시킬 수 있는 농약 자동 살포장치에 관한 것이다. claims: 혼합탱크;상기 혼합탱크에 저장된 액상의 농약, 물, 비료 또는 사료를 공급하는 양수기;상기 양수기를 통해 상기 혼합탱크로부터 공급되는 액상의 농약 또는 물을 분배하는 분배기;상기 분배기에 연결되고, 농작물 재배지의 각 고랑을 따라 바닥에 각각 설치되어 상기 분배기로부터 분배된 액상의 농약 또는 물을 각 고랑으로 이송하며, 농작물 재배지에 식재된 각 농작물에 대응하여 복수 개의 'T'자형 분기구가 설치된 메인호스;상기 메인호스에 설치된 'T'자형 분기구에 착탈 가능하게 결합되고, 해당 농작물을 따라 길게 연장 설치되어 상기 메인호스로부터 공급된 액상의 농약 또는 물을 해당 농작물로 이송하며, 해당 농작물의 각 가지에 대응하여 'T'자형 분기구가 형성된 제1 분기호스;상기 제1 분기호스의 'T'자형 분기구에 착탈 가능하게 결합되고, 해당 농작물의 각 가지를 따라 길게 연장 설치되며, 길이방향을 따라 복수 개의 상향식 분사구가 설치되어 상기 제1 분기호스에서 공급되는 액상의 농약 또는 물을 상측으로 분사하는 제2 분기호스; 및상기 제1 분기호스의 상단부에 착탈 가능하게 결합되고, 상기 제1 분기호스를 통해 공급되는 액상의 농약이나 물을 해당 농작물의 상부에서 하부로 분사하는 분사헤드;를 포함하되,해당 농작물의 가지들 중 지면으로부터 1~1.5m 높이에 있는 가지를 따라 길에 연장 설치되고, 상기 제1 분기호스에 설치된 'T'자형 분기구에 착탈 가능하게 결합되며, 길이방향을 따라 복수 개의 하향식 분사구가 설치되어 상기 제1 분기호스에서 공급되는 액상의 농약(잡초제)을 농작물 재배지의 지면에 자라고 있는 잡초로 분사하여 제거하는 제3 분기호스를 더 포함하는 것을 특징으로 하는 농약 자동 살포장치., Ltext: 농업, prediction: 농업
478/1059 Row 478: application_number: 1020200131521, combined_string: invention_title: 영농지에 구축된 태양광, 강풍유도용 태양광발전판 abstract: 본 발명은 영농지에 구축된 태양광, 강풍유도용 태양광발전판에 관한 것으로서, 더 상세하게는 과수원이나 비닐하우스, 벼재배 단지와 같은 농지에서, 태풍이나 냉해에 대한 피해를 방지하도록 태양광발전판의 저측단에 연계되는 강풍유도벽을 연결로서 농작물이나 시설물에 대한 강풍이나 냉해 피해 방지하는 발명이다. 일반적으로 과수원에서 외부로 노출된 과수목이나 원예단지에서는, 기후변화로 더 강력해진 강풍으로 발생되는 피해는 농가에 큰 부담이 되고 있는 것이다.고로 농지(70), 비닐하우스로 형성된 원예단지(65)와 같은 경작지의 가장자리에다 기둥(66)과 고정앵글(68)의 설치되면서 강풍유도용으로 구축되도록 좌우 길이방향이면서 이격간격(라) 유지로 설치되는 복수의 태양광발전장치(80)과, 상기 태양광발전장치(80)에는 경사지게 설치된 태양광발전판(83)와,상기 태양광발전판(83)을 형성하는 발전소자인 모듈(86)의 하측에 연결빔(92)이 연장으로 확대된 구간에 형성되는 연결수단(69)이 구비되면서 이격간격(라) 구간을 연결함으로서, 강풍유도하도록 강풍유도판(91)의 가장자리에 구비된 연결용 조립구(77)와, 상기 태양광발전판(83)의 하측단에서 연결로 강풍유도시켜서 이격간격(라)으로 더 확대하여 주는 제2강풍유도판(191)과, 상기 제2강풍유도판(191)의 양측에 돌출로 이격간격(라)을 연결하는 조립구(77)와, 상기 연결수단(69)과 조립구(77)를 조립으로 걸어줌으로서, 태양광발전판(83)의 하측단에 개구된 통과공간(가)과 이격간격(라)을 카버로서 농지(70)로 유입되는 강풍을 공중으로 유도시켜 주도록 제공되는 발명이다. claims: 농지(70), 비닐하우스로 형성된 원예단지(65)와 같은 경작지역(71)의 가장자리에다, 기후변화와 계절의 변화에 따른 경작지의 폭염, 냉해피해를 감소시켜 주면서 신재생에너지 발전을 증대시켜 주도록, 기둥(66)과 고정앵글(68)의 설치로서 저측에 경작지역(71)인 하측공간이 구비되면서 상측에 강풍유도용으로 경사지게 구축되는 태양광발전판(83)이, 좌우 길이방향이면서 이격간격(라) 유지하면서 기둥(66)과 빔(67)으로 경작지역(71)이 조성되는 복수의 태양광발전판(83)이 각각 경사지게 설치된 고정앵글(68)에 조립되는 태양광발전판에 있어서, 상기 태양광발전판(83)의 상측단에서 고정앵글(68)의 연장으로 설치되는 태양광 유입구(87)과, 상기 유입구(87)을 태양광발전판(83)의 배면공간인 경작지역(71)에 반사로 유도시켜 주기 위하여, 태양광반사공간(90)이 형성되도록 만곡으로 조립된 반사대(110)와, 상기 반사대(110)에서 반사로 굴절되는 태양광 반사공간(90)에다, 태양광발전판(83)의 저면에 공정으로 돌출되는 맞추어서, 태양광굴절용 복수의 보조반사대(111)을 태양광발전판(83)의 저측면에 고정시켜 주어서, 태양광이 경작지역(71)에 비춰주고, 상기 복수의 보조반사대(111)에서 태양광발전판(83)의 저면에 가열공간(107)과 통과구(106)의 관통으로, 폭염기간에 경작지역(71)의 고온을 태양광유입공간(90)으로 엮류로 환기시켜 주도록 제공되는 영농지에 구축되는 태양광, 강풍유도용 태양광발전판., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

479/1059 Row 479: application_number: 2020200003252, combined_string: invention_title: 딸기재배용 국소 냉온패드 abstract: 본 고안은 딸기 재배시 물공급을 필요로 하는 모종단계와 생육단계에 계절별로 공급되는 급수온도를 맞추어서 균일한 지열을 제공함으로써 고품질의 딸기를 수확하고, 다분화가 가능하도록 하여 수확시기를 늘려서 수익성을 우수하게 향상시킬 수 있는 딸기재배용 국소 냉온패드에 관한 것이다.본 고안은 냉수 또는 온수가 공급되는 공급호스부 몸체(10,11)가 형성되고, 상기 공급호스부 몸체(10,11)의 중간부분에 배출호스부(12)가 형성되며, 상기 배출호스부(12)와 공급호스부 몸체(10,11)가 융착되어 융착부(14)가 형성되며 다수의 핀공이 형성된 지열호스부(102)와: 상기 융착부(14)에 안착되어 고정되고, 작물에 관수를 공급하기 위한 다수의 노즐공(32)을 구비한 점적호스부(104)와; 상기 융착부에 안착된 점적호스부(104)가 흔들리거나 이탈되지 않도록 고정하는 고정부재(106)를 포함하는 것을 특징으로 한다.이와 같은, 본 고안의 딸기재배용 국소 냉온패드는, 여름이나 겨울 등 계절에 맞게 관수온도를 공급함으로써 딸기의 기형을 방지하고 상품성을 우수하게 향상시킬 수 있는 효과가 있고, 필요한 시기에 관수를 제공하여 적어도 2회 이상의 다분화가 가능함으로써 수확시기를 늘려서 생산성이 크게 향상되는 효과가 있다. claims: 냉수 또는 온수가 공급되는 공급호스부 몸체(10,11)가 형성되고, 상기 공급호스부 몸체(10,11)의 중간부분에 배출호스부(12)가 형성되며, 상기 배출호스부(12)와 공급호스부 몸체(10,11)가 융착되어 융착부(14)가 형성되며 다수의 핀공이 형성된 지열호스부(102)와: 상기 융착부(14)에 안착되어 고정되고, 작물에 관수를 공급하기 위한 다수의 노즐공(32)을 구비한 점적호스부(104)로 이루어지는 딸기재배용 냉온패드에 있어서,상기 융착부(14)에 안착된 점적호스부(104)가 흔들리거나 이탈되지 않도록 고정하는 고정부재(106)를 포함하되,상기 고정부재(106)는, 디귿자(ㄷ)형상 또는 스테플러의 형상으로 이루어져 있고, 상기 점적호스부(104)를 감싸면서 지반에 고정되도록 형성되고,상기 지열호스부(102)는,상기 공급호스부 몸체(10,11)와 배출호스부(12)가 형성되고, 일끝단부가 공급호스부 몸체(10,11)와 배출호스부(12)가 연결되어 관수가 순환되도록 형성되고, 공급호스부 몸체(10,11)로 공급된 관수가 순환하여 상기 배출호스부(12)를 설치하는 것을 포함하되,상기 공급호스부 몸체(10,11)의 끝단부에는 공급되는 관수가 순환되도록 배출호스부(12)와 각각 연결되어 연결배관부(18,20)가 형성되고, 상기 공급호스부 몸체(10,11)의 전단부에는 관수가 공급되는 연결밸브(108)가 설치되어공급된 관수의 온도와 배출시 관수의 온도의 합이 지열호스부(102)의 전단부와 후단부에 이르기까지 호스 전체에 걸쳐서 동일하게 유지되는 것을 특징으로 하는 딸기재배용 국소 냉온패드., Ltext: 농업, prediction: 임업
480/1059 Row 480: application_number: 1020200091622, combined_string: invention_title: 과수 포장지 abstract: 본 발명은 과수의 열매(과실)을 외부 환경, 농약, 해충, 물리적 접촉 등으로부터 보호하고 성장 및 숙지를 돕기 위해 과실에 씌우는 과실 봉지를 위한 과수 포장지에 관한 것으로서, 펄프 및 에폭시 수지를 포함하는 기재: 및 상기 기재에 코팅된 코팅층을 포함하되, 상기 코팅층은 바인더 및 발수제를 포함하는 것이고, 상기 코팅층은 기재의 양쪽 표면 및 내부에 형성되어 있는 것이다. 본 발명의 과수 포장지는 함침 코팅으로 기재 전체 면적에 형성된 코팅층에 의해 내구성이 향상되어 과실 재배 과정에서 비용 절감이 가능하고, 포름알데히드 성분 잔류 위험성이 제거되어 기존의 과실 봉지를 대체할 수 있을 것으로 기대된다. claims: 펄프 및 에폭시 수지를 포함하는 기재, 및상기 기재에 코팅된 코팅층 포함하는 과수 포장지로서,상기 기재에서 펄프와 에폭시 수지는 99.9:0.1 내지 95.0:5.0의 중량비로 혼합되어 있는 것이며,상기 에폭시 수지는 120℃ 내지 180℃에서 열가교에 의해 펄프와 가교 결합된 것이고,상기 코팅층은 바인더 및 발수제로 이루어진 것이고, 발수제 함량이 바인더 100 중량부에 대하여 0.5 내지 8 중량부이며, 기재에 대해 1.0 g/㎡ 내지 7.0 g/㎡의 양으로 기재의 양쪽 표면 및 내부 기공의 표면에 형성되어 있는 것인과수 포장지., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

481/1059 Row 481: application_number: 1020200083394, combined_string: invention_title: 고설베드 재배 장치 abstract: 본 발명은 고설베드 재배 장치에 관한 것으로, 작물의 재배를 위해 뿌리를 심을 수 있도록 소정의 토양이 수용되는 베드본체와, 상기 베드본체를 지면에서 소정의 높이에 위치시키는 다리를 포함하는 고설베드와; 상기 다리의 바깥쪽에 구비되어 소정의 중량을 갖는 과실을 베드본체로부터 재배위치를 분리하는 과실받침대와; 상기 다리에서 상기 베드본체의 상부 방향으로 연장되어 작물의 재배에 따라 상기 베드본체에서 성장하는 줄기가 지탱하여 위로 뻗어 타고 올라갈 수 있도록 지지하는 줄기유인대를 포함하는 구성으로 충분한 광합성을 통해 과실의 품질 및 생산성이 향상될 수 있는 고설베드 재배 장치에 관한 것이다. claims: 작물의 재배를 위해 뿌리를 심을 수 있는 소정의 토양이 수용되는 베드본체(110)와, 상기 베드본체(110)를 지면에서 소정의 높이에 위치시키는 다리(120)를 포함하여 고설베드(100)로 이루어진 고설베드 재배 장치에 있어서,상기 고설베드 재배 장치는,소정의 중량을 갖는 과실을 베드본체(110)로부터 위치를 분리하여 재배할 수 있도록 상기 다리(120)의 바깥쪽에 착탈 가능하게 구비되는 과실받침대(200)와;상기 다리(120)에서 상기 베드본체(110)의 상부 방향으로 연장되어 작물의 재배 시 줄기를 유인할 수 있도록 상기 다리(120)의 바깥쪽에 착탈 가능하게 구비되는 줄기유인대(300)를 포함하고,상기 과실받침대(200)는 접이식으로 구성되며,상기 베드본체(110)의 수평 길이와 동일한 길이로 과실을 받치는 받침프레임(210)과;상기 받침프레임(210)의 하부를 일체로 지지하며, 상기 베드본체(110)의 다리(120) 상측에 회전 가능하게 구비되는 회전프레임(220)과;상기 다리(120) 하측에 회전 가능하게 구비되어 과실을 받칠 수 있도록 상기 받침프레임(210)을 포함한 회전프레임(220)의 수평 위치 시 회전프레임(220)을 지지하는 받침지지대(230)를 포함하며,상기 받침프레임(210)은 두 개의 파이프로 이루어지고, 과실의 크기에 따라 두 파이프의 간격을 조절할 수 있으며, 상기 받침프레임의 길이를 연장하기 위해 상기 파이프를 서로 연결하는 연결구(211)를 구비하고,상기 줄기유인대(300)는,상기 다리(120)와 평행하게 구비되며, 상기 베드본체(110)의 상부까지 소정의 길이를 갖는 메인포스트(310)와;상기 메인포스트(310)에 출몰 가능하게 구비되며, 상기 메인포스트(310)에서 상단으로 길이 방향을 따라 더 연장되는 보조포스트(320)를 포함하며,상기 메인포스트(310)로부터 보조포스트(320)가 주행하여 선택된 높이에서 메인포스트(310)에 구비된 조절노브(340)를 조여 보조포스트(320)의 높이를 조절가능한 것을 특징을 하는 고설베드 재배 장치., Ltext: 농업, prediction: 임업
482/1059 Row 482: application_number: 2020200001553, combined_string: invention_title: 육묘 포트용 상토 평탄기 abstract: 본 고안은 딸기와 같이 고설 액비 재배를 하는 농작물의 포트내부에 상토를 채움에 있어 신속함은 물론, 포트 외부로 유실되는 상토를 최소화할 수 있는 육묘 포트용 상토 평탄기에 관한 것으로,내부에 상토가 충진되면서 포트(10)의 내부에 상토가 채워질 수 있도록 상, 하면에 개방되며, 4개 면이 플레이트로 일체화된 다각형 형상의 틀(20)이 구비되며, 상기 틀(20)의 상측 끝단부는 틀의 강성유지와 손잡이의 기능을 수행할 수 있도록 적어도 2개소 이상 굽힘가공 처리에 의해 홀더(21)가 형성되고, 진행 방향으로 좌, 우측 플레이트(22,23)의 하단에는 상기 틀(20)이 포트(10)의 상부에서 유동거림 및 이탈을 방지할 수 있도록 리미트 플레이트(24,25)가 형성되고, 상기 좌, 우측 플레이트(22,23)의 하측 내면에는 상기 틀(20)이 포트(10)의 상단면에 안착된 상태에서 프트(10)의 상단을 슬라이딩 할 수 있도록 안착편(26, 27)이 각각 형성되는 한편, 상기 틀(20)의 전, 후면 플레이트(28,29) 하측 끝단부는 진행방향으로 돌출부위가 있는 경우에도 안정적으로 진행이 될 수 있도록 상측 방향으로 1 내지 10°굽힘 가공처리된 가이드플레이트(30,31)가 형성된다. claims: 내부에 상토가 충진되면서 포트(10)의 내부에 상토가 채워질 수 있도록 상, 하면에 개방되며, 4개 면이 플레이트로 일체화된 다각형 형상의 틀(20)이 구비되며, 상기 틀(20)의 상측 끝단부는 틀의 강성유지와 손잡이의 기능을 수행할 수 있도록 적어도 2개소 이상 굽힘가공 처리에 의해 홀더(21)가 형성되고, 진행 방향으로 좌, 우측 플레이트(22,23)의 하단에는 상기 틀(20)이 포트(10)의 상부에서 유동거림 및 이탈을 방지할 수 있도록 리미트 플레이트(24,25)가 형성되고, 상기 좌, 우측 플레이트(22,23)의 하측 내면에는 상기 틀(20)이 포트(10)의 상단면에 안착된 상태에서 포트(10)의 상단을 슬라이딩 할 수 있도록 안착편(26, 27)이 각각 형성되는 한편,상기 틀(20)의 전, 후면 플레이트(28,29) 하측 끝단부는 진행방향으로 돌출부위가 있는 경우에도 안정적으로 진행이 될 수 있도록 상측 방향으로 1 내지 10°굽힘 가공처리된 가이드플레이트(30,31)가 형성되는 것을 특징으로 하는 육묘 포트용 상토 평탄기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

483/1059 Row 483: application_number: 1020200054292, combined_string: invention_title: 포도 화수 정형기 abstract: 본 발명은 포도 재배시 화수의 정형을 신속하고 간편하게 수행할 수 있도록 한 포도 화수 정형기에 관한 것이다.본 발명의 포도 화수 정형기는 이격된 상태로 마주하는 한 쌍의 집게부(110a,110b)와 상기 집게부를 일체로 연결하면서 탄성이격력을 부여하는 탄성손잡이부(120)를 가진 핀셋 형태의 몸체(100)와, 상기 집게부를 합치시킬 경우 원형을 이루면서 포도의 화수 줄기(A)를 감싸도록 각 집게부에 형성된 반구형의 커팅홈(130a,130b)과, 화수 줄기의 손상이 방지되도록 상기 커팅홈의 상단과 하단을 따라 외측을 향해 하향 경사지게 형성된 하는 커팅날(140)과, 재배할 화수(B)의 길이를 측정할 수 있도록 상기 일측의 집게부의 외측면에 형성된 길이측정용 눈금(150)을 포함한다. claims: 이격된 상태로 마주하는 한 쌍의 집게부와, 상기 한 쌍의 집게부를 일체로 연결하면서 탄성이격력을 부여하는 탄성손잡이부를 가진 핀셋 형태의 몸체;상기 한 쌍의 집게부를 합치시킬 경우, 원형을 이루면서 포도의 화수 줄기를 감싸도록 각 집게부에 형성된 반구형의 커팅홈;화수 줄기의 손상이 방지되도록 상기 커팅홈의 상단과 하단을 따라 외측을 향해 하향 경사지게 형성된 커팅날; 및재배할 화수의 길이를 측정할 수 있도록 상기 한 쌍의 집게부 중 일측의 집게부의 외측면에 형성된 길이측정용 눈금;을 포함하되,상기 일측의 집게부의 내측면에는 일정간격을 두고 홈부가 형성되고,상기 일측의 집게부를 따라 전후방향으로 슬라이딩 이동가능하면서 상기 길이측정용 눈금의 위치를 알려주는 지시부재가 상기 일측의 집게부의 상부에 끼워져 결합되며,상기 지시부재는 엄지손가락을 올려 놓을 수 있는 안착부가 형성된 전면부와, 상기 홈부에 끼워지는 위치고정용 돌기가 형성된 후면부와, 상기 전면부와 후면부의 상단을 연결하며 상기 일측의 집게부의 상단에 지지되는 연결부를 구비한포도 화수 정형기., Ltext: 농업, prediction: 임업
484/1059 Row 484: application_number: 1020200052437, combined_string: invention_title: 베타글루칸 성분을 증진시키는 배 재배방법 abstract: 본 발명은 배와 영지, 운지, 상황 버섯, 강황, 와송, 귀리를 특정 조건으로 숙성 및 발효시켜 제조한 조성물을 배나무에 살포하여 배의 베타글루칸 성분을 증진시키는 배 재배방법에 관한 것으로, 더욱 상세하게는 (a) 배 126kg를 3개월 동안 용기 내에서 숙성시키는 제 1차 숙성 단계, (b) 상기 제 1차 숙성 단계에서 숙성된 숙성물의 여과액을 1년 동안 용기 내에서 발효시키는 단계, (c) 상기 발효된 발효물에 각각 영지, 운지, 상황 버섯과 강황, 와송, 귀리를 첨가하여 용기 내에서 5개월 동안 숙성시키는 제 2차 숙성 단계, (d) 상기 제 2차 숙성 단계에서 숙성된 숙성물을 각각 여과하는 단계, (e) 상기 여과된 영지, 운지, 상황 버섯이 포함된 조성물 250ml와 강황, 와송, 귀리가 포함된 조성물 250ml를 물 500L에 혼합하는 단계 및 (f) 상기 혼합된 조성물을 배나무 과수원 1652m2 면적에 살포하는 단계를 포함하는 배 재배방법을 제공한다. claims: 베타글루칸 성분을 증진시키는 배 재배방법에 있어서,(a) 배 126kg를 3개월 동안 용기 내에서 숙성시키는 제 1차 숙성 단계;(b) 상기 제 1차 숙성 단계에서 숙성된 숙성물의 여과액을 1년 동안 용기 내에서 발효시키는 단계;(c) 상기 발효된 발효물에 각각 영지, 운지, 상황 버섯과 강황, 와송, 귀리를 첨가하여 용기 내에서 5개월 동안 숙성시키는 제 2차 숙성 단계;(d) 상기 제 2차 숙성 단계에서 숙성된 숙성물을 각각 여과하는 단계;(e) 상기 여과된 영지, 운지, 상황 버섯이 포함된 조성물 250ml와 강황, 와송, 귀리가 포함된 조성물 250ml를 물 500L에 혼합하는 단계; 및(f) 상기 혼합된 조성물을 배나무 과수원 1652m2 면적에 살포하는 단계;를 포함하는 것을 특징으로 하는 베타글루칸 성분을 증진시키는 배 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

485/1059 Row 485: application_number: 1020200033211, combined_string: invention_title: 혼합 배양균을 이용한 농작물 친환경 재배 방법 abstract: 본 발명은 셀레늄을 이용한 농작물의 재배방법과 관련된다. 구조적 특징에 있어서, 셀레늄(Selenium)과 님 케이크 (NEEM-CAKE :분말)을 1 : 1 혼합하여 토양에 1차 시비하는 단계와 ; 상기 1차 시비된 토양에 야채류 또는 과실류를 파 종 또는 모종하는 단계와 ; 셀레늄(Selenium)과 님오일(NEEM-OIL)을 1 : 1혼합한 혼합물과 물을 1 : 500의 비율로 희석 하는 단계와 ; 상기 희석액을 토양에 1차 엽면시비하는 단계와 ; 1차 엽면시 후5내지 6일간격으로 3 내지 4회 엽면시비하 여 병충해 방지 및 성장촉진시키는 셀레늄 및 님(NEEM)성분을 이용한 유기농작물의 친환경 재배방법을 특징으로 한다.셀레늄과 님오일(NEEMOIL) 혼합액과 죽초액을 10 : 1 ~ 2의 비율로 혼합하여 6일 간격으로 2 내지 3회 엽면시비하여 병 충해를 방제 및 성장을 촉진하는 셀레늄 및 님오일을 이용한 유기농작물의 친환경 재배방법을 특징으로 한다.이에 따라 본 발명은, 셀레늄과 님오일(NEEM-OIL) 혼합물을 물과 희석하여 미나리, 토마토, 쑥갓 등의 채소류와 배, 포 도, 딸기 등의 과실류에 엽면 시비하여 셀레늄의 함유량을 높이고, 농약의 살포없이 유기농산물로 재배하여 세척없이도 먹 을 수 있도록 하여 상품성을 높일 뿐 아니라, 세척과정에서 물에 녹는 셀레늄의 소실을 방지함은 물론, 채소 및 과일의 생 장기간을 크게 단축시켜 출하시기를 앞당겨 상품성을 높일 수 있다. claims: 셀레늄을 이용한 농작물의 재배방법에 있어서 :셀레늄(Selenium)과 님 케이크(NEEM-CAKE :분말)을 1 : 1 혼합하여 토양에 1차 시비하는 단계와 ;상기 1차 시비된 토양에 야채류 또는 과실류를 파종 또는 모종하는 단계와 ;셀레늄(Selenium)과 님오일(NEEMOIL)을 1 : 1혼합한 혼합물과 물을 1 : 500의 비율로 희석하는 단계와 ;상기 희석액을 토양에 1차 엽면시비하는 단계와 ;1차 엽면시 후5내지 6일간격으로 3 내지 4회 엽면시비하여 병충해 방지 및 성장촉진시킴을 특징으로 하는 셀레늄 및 님오 일을 이용한 유기농작물의 친환경 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

486/1059 Row 486: application_number: 1020200029833, combined_string: invention_title: 라이조푸스 속 균주와 키토산 및 사포닌을 포함하는 액상 비료 조성물, 이의 제조방법 및 이를 이용하여 재배된 사과 abstract: 일 양상에 따른 라이조푸스 속 균주 배양물과 키토산 분해 균주 배양물 및 사포닌 액상액을 포함한 액상 비료 조성물, 이의 제조 방법 및 이를 이용하여 재배된 사과를 제공한다. 이에 따르면 키토산 액체 비료를 편리하고 대량으로 생산할 수 있고, 이를 식물 및 토양에 분사하여 식물의 생육을 향상시킬 수 있다. 또한, 농약과 화학비료를 사용하지 않고도 해충이 예방되면서 조사포닌 함량이 증가된 기능성 농작물을 재배할 수 있다. claims: 사과의 조사포닌 함량이 5mg/g 이상 되도록, 사포닌액 0.01 중량부 내지 10 중량부, 0.01 중량부 내지 20 중량부의 라이조푸스 속(Rhizopus species) 균주 배양물, 0.01 중량부 내지 20 중량부의 키토산 분해 균주 배양물의 혼합물을 포함하고,당(sugar), 솔빈산가리(potassium sorbate), 아황산 나트륨(sodium sulfite), EDTA(ethylenediaminetetraacetic acid), 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일 및 아미노산을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물을 이용하여 재배된 사과.사과의 조사포닌 함량이 5mg/g 이상 되도록, 사포닌액 0.01 중량부 내지 10 중량부, 0.01 중량부 내지 20 중량부의 라이조푸스 속(Rhizopus species) 균주 배양물, 0.01 중량부 내지 20 중량부의 키토산 분해 균주 배양물의 혼합물을 포함하고,0.01 중량부 내지 10 중량부의 당(sugar), 0.01 중량부 내지 20 중량부의 솔빈산가리(potassium sorbate), 0.1 중량부 내지 20 중량부의 아황산 나트륨(sodium sulfite), 0.1 중량부 내지 20 중량부의 EDTA(ethylenediaminetetraacetic acid), 0.01 중량부 내지 10 중량부의 붕소, 0.01 중량부 내지 10 중량부의 황산 아연, 0.01 중량부 내지 10 중량부의 피톤치드, 녹차추출물, 천연에센스오일 및 0.5 중량부 내지 60 중량부의 아미노산을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물.키토산, 키토산 분해 균주, 및 곡물의 혼합물을 발효시켜 키토산 분해 균주 배양물을 제조하는 단계;라이조푸스 속 균주를 백색 구균과 복합 면역시킨 곡류를 발효시켜 라이조푸스 균주 배양물을 제조하는 단계;사포닌액을 마련하는 단계;재배하고자 하는 사과의 조사포닌 함량이 5mg/g 이상되도록, 상기 사포닌액을 상기 키토산 분해 균주 배양물, 상기 라이조푸스 균주 배양물 및 당과 혼합하여 마련된 혼합물을 10 분 내지 48 시간 동안 배양하여 배양물을 마련하는 단계; 상기 배양물에 솔빈산가리, 아황산 나트륨, EDTA, 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산을 가하고 10분 내지 48시간 동안 교반하는 단계;를 포함하며, 상기 키토산 분해 균주 배양물을 제조하는 단계는,0.1 중량부 내지 15 중량부의 키토산, 0.1 중량부 내지 15 중량부의 키토산 분해 균주, 0.1 중량부 내지 20 중량부의 당밀, 잔부 미강박 및 기타 불가피한 불순물로 이루어진 키토산 분해 균주 혼합물을 마련하는 키토산 준비과정; 및상기 키토산 분해 균주 혼합물을 발효시키켜 상기 키토산 분해 균주 배양물을 제조하는 키토산 발효과정;을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물을 제조하는 방법.키토산, 키토산 분해 균주, 및 곡물의 혼합물을 발효시켜 키토산 분해 균주 배양물을 제조하는 단계;라이조푸스 속 균주를 백색 구균과 복합 면역시킨 곡류를 발효시켜 라이조푸스 균주 배양물을 제조하는 단계;사포닌액을 마련하는 단계;재배하고자 하는 사과의 조사포닌 함량이 5mg/g 이상되도록, 상기 사포닌액을 상기 키토산 분해 균주 배양물, 상기 라이조푸스 균주 배양물 및 당과 혼합하여 마련된 혼합물을 10 분 내지 48 시간 동안 배양하여 배양물을 마련하는 단계; 상기 배양물에 솔빈산가리, 아황산 나트륨, EDTA, 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산을 가하고 10분 내지 48시간 동안 교반하는 단계;를 포함하며, 상기 라이조푸스 균주 배양물을 제조하는 단계는,0.1 중량부 내지 20 중량부의 당밀과 잔부 미강박 및 기타 불가피한 불순물로 이루어진 라이조푸스 균주 혼합물을 마련하는 라이조푸스 혼합과정; 및상기 라이조푸스 균주 혼합물을 발효시키켜 상기 라이조푸스 균주 혼합물을 제조하는 라이조푸스 발효과정;을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물을 제조하는 방법.쪽파의 조사포닌 함량이 2mg/g 이상 되도록, 사포닌액 0.01 중량부 내지 10 중량부, 0.01 중량부 내지 20 중량부의 라이조푸스 속(Rhizopus species) 균주 배양물, 0.01 중량부 내지 20 중량부의 키토산 분해 균주 배양물의 혼합물을 포함하고,당(sugar), 솔빈산가리(potassium sorbate), 아황산 나트륨(sodium sulfite) EDTA(ethylenediaminetetraacetic acid), 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일 및 아미노산을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물.키토산, 키토산 분해 균주, 및 곡물의 혼합물을 발효시켜 키토산 분해 균주 배양물을 제조하는 단계;라이조푸스 속 균주를 백색 구균과 복합 면역시킨 곡류를 발효시켜 라이조푸스 균주 배양물을 제조하는 단계;사포닌액을 마련하는 단계;재배하고자 하는 쪽파의 조사포닌 함량이 2mg/g 이상되도록, 상기 사포닌액을 상기 키토산 분해 균주 배양물, 상기 라이조푸스 균주 배양물 및 당과 혼합하여 마련된 혼합물을 10 분 내지 48 시간 동안 배양하여 배양물을 마련하는 단계; 상기 배양물에 솔빈산가리, 아황산 나트륨, EDTA, 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산을 가하고 10분 내지 48시간 동안 교반하는 단계;를 포함하며, 상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물을 제조하는 방법., Ltext: 농업, prediction: 임업
487/1059 Row 487: application_number: 1020200029841, combined_string: invention_title: 과수재배용 공기 교반기 abstract: 본 발명은 과수재배용 공기 교반기로서, 이를 보다 상세히 설명하면 작물의 주위에 존재하는 공기를 상하 방향으로 원활하게 교반시켜주므로서 작물의 성장촉진과 개화기(開花期)에 꽃망울의 동해(凍害) 예방 효과를 부여할 수 있도록 한 것으로서, 상기 본 발명은 구체적인 수단으로 교반기 통체(10) 내에 모터 (11)에 구동되는 송풍기(12)가 설치되고, 송풍기(12)의 전방으로 삿갓형의 공기 융기부(14)가 형성된 교반통(13)을 고정지지간(17)에 고정되도록 설치한 구성에 있어서, 교반통(13)의 공기 융기부(14) 측면에 수개의 좌우 높낮이가 상이한 경사유도판(16)을 고정착설하여 송풍공기에 대해 와류운동을 일으키도록 형성하고, 상기 교반통(13)의 상부에는 보조덮개(17)를 설치하여 교반통(13)의 요입실(15)과 교반기 통체(100) 내부에 우수가 유입되지 않도록 구성함을 특징으로 하며, 이러한 본 발명에 의해 종래의 직송교반식 공기 교반장치에 비하여 공기의 순환효과와 교반효과가 크게 향상되는 등 다수의 효과를 기대할 수 있는 발명이다. claims: 교반기 통체(10) 내에 모터(11)에 의해서 구동되는 송풍기(12)를 설치하고,송풍기(12)의 전방으로 삿갓형의 공기 융기부(14)가 형성된 교반통(13)을 고정지지간(17)에 고정되도록 설치하며,교반통(13)의 공기 융기부(14) 측면에 수개의 좌우 높낮이가 상이한 경사유도판(16)을 고정착설하여 송풍공기에 대해 와류운동을 일으키도록 형성하고,상기 교반통(13)의 상부에는 보조덮개(17)를 설치하여 교반통(13)의 내부에 우수가 유입되지 않도록 구성함을 특징으로 하는 과수재배용 공기 교반기.교반기 통체(10) 내에 모터(11)에 의해서 구동되는 송풍기(12)를 설치하고,송풍기(12)의 전방으로 삿갓형의 공기 융기부(14)가 형성된 교반통(13)을 고정지지간(17)에 고정되도록 설치하며,교반통(13)의 공기 융기부(14) 측면에 수개의 좌우 높낮이가 동일한 4각형으로 이루어진 4각유도판(16a)을 고정착설하여 송풍공기를 일정하게 확산운동을 일으키도록 형성하고,상기 교반통(13)의 상부에는 보조덮개(17)를 설치하여 교반통(13)의 내부에 우수가 유입되지 않도록 구성함을 특징으로 하는 과수재배용 공기 교반기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

488/1059 Row 488: application_number: 1020200029860, combined_string: invention_title: 신품종 배 및 이의 육종 방법 abstract: 본 발명은 신품종 배 및 이의 육종 방법에 관한 것으로, 모계 품종인 돌배와 부계 품종인 배를 교배시켜 얻어진 본 발명에 따라 육종된 신품종 배는 돌배의 약효인 감기ㅇ해소ㅇ천식 예방 효과 및 소화기능 개선효과를 가지면서도 신맛은 감소되고 단맛이 증대되고 과육이 말랑말랑하여 기호도를 높일 수 있다. 또한, 본 발명의 신품종 배는 3일 내지 6일 동안 후숙시키면 과육이 더욱 말랑말랑해져서 치아가 약학 노약자도 섭취가 가능하며, 과육 크기가 돌배보다 작아서 식이가 용이하여 학교 급식이나 병원식으로도 유용하게 사용될 수 있을 것으로 기대된다. claims: 기탁번호 KCTC14147BP 또는 KCTC14148BP의 신품종 배로서,모계 품종인 돌배와 부계 품종인 배를 교배시켜 얻어지고, 배 껍질이 황색 또는 적색을 띠며, 신맛은 감소되고 단맛은 증대되고, 당도는 10 내지 14˚Bx이고, 산도는 0.03 내지 0.05%이며, 과육이 말랑말랑한 특성을 가지는 신품종 배.제 1 항에 있어서,하기 특성을 가지는 것을 특징으로 하는 신품종 배:(1) 과형이 둥근 원형으로, 모계 품종인 돌배와 크기가 비슷하거나 조금 큼.(2) 과육 껍질은 황색, 적색 또는 부분적으로 황색 및 적색으로 착색되며, 흰색 내지 황색 점이 껍질 전면에 있음.(3) 잎은 달걀모양 타원형이고, 끝은 뾰족하며, 밑은 둥글거나 심장밑 모양이고, 잎 뒷면은 녹색이며 털이 없고 가장자리에 침 같은 톱니가 있음.(4) 꽃은 4∼5월에 백색으로 핌.(5) 과육의 색은 백색임.(6) 과육은 처음에는 모계 품종과 유사하나 상온에서 1주일정도 경과시 갈변하며 모계 품종 및 부계 품종에 비하여 말랑말랑하며, 갈변시 과즙이 많아지고 표피가 얇아지며 당도가 더 높아져 10 내지 14˚Bx이고, 산도는 0.03 내지 0.05% 임.기탁번호 KCTC14147BP 또는 KCTC14148BP의 신품종 배의 육종방법으로서, 하기 단계를 포함하는 것을 특징으로 하는 신품종 배의 육종방법:(S1) 모계 품종인 돌배 품종을 파종하는 단계; (S2) 부계 품종인 배 품종을 파종하는 단계; (S3) 상기 부계 품종인 배 품종의 착과시기에 열매가 열린 가지를 잘라서 부계 품종인 돌배 품종에 인위적으로 교배시키는 단계;(S4) 교배된 개체의 과실에서 종자를 채종하는 단계; (S5) 상기 채종된 종자를 파종하여 배를 재배하는 단계; 및(S6) 상기 재배한 배 중에서 배 껍질이 황색 또는 적색으로 착색되고, 당도는 10 내지 14˚Bx이고, 산도는 0.03 내지 0.05%이며, 과육이 말랑말랑한 특성을 가지는 신품종 배를 육종하는 단계.제 3 항에 있어서,상기 단계 (S3)에서 부계 품종인 배 품종에 열린 배 중 모계 품종인 돌배의 크기보다 작은 열매가 열린 가지를 잘라서 부계 품종인 돌배 품종에 인위적으로 교배시키는 것을 특징으로 하는 신품종 배의 육종방법.제 3 항에 있어서,상기 신품종 배가 하기 특성을 가지는 것을 특징으로 하는 신품종 배의 육종방법.(1) 과형이 둥근 원형으로, 모계 품종인 돌배와 크기가 비슷하거나 조금 큼.(2) 과육 껍질은 황색 또는 적색으로 착색되며, 흰색 내지 황색 점이 껍질 전면에 있음.(3) 잎은 달걀모양 타원형이고, 끝은 뾰족하며, 밑은 둥글거나 심장밑 모양이고, 잎 뒷면은 녹색이며 털이 없고 가장자리에 침 같은 톱니가 있음.(4) 꽃은 4∼5월에 백색으로 핌.(5) 과육의 색은 백색임.(6) 과육은 처음에는 모계 품종과 유사하나 상온에서 1주일정도 경과시 갈변하며 모계 품종 및 부계 품종에 비하여 말랑말랑하며, 갈변시 과즙이 많아지고 표피가 얇아지며 당도가 더 높아짐., Ltext: 농업, prediction: 임업
489/1059 Row 489: application_number: 1020200021097, combined_string: invention_title: IBA를 이용한 딸기 모주의 측아 발생 억제 및 자묘 생육 증진 방법 abstract: 본 발명은 시설 딸기 육묘시 30~120 mg·L-1의 IBA(indole-3-butyric acid)를 배지관주로 처리하여 딸기 모주의 측아 발생 억제 및 자묘 생육을 향상시키는 방법에 관한 것으로, 본 발명의 방법은 딸기 묘의 생산성 향상에 기여할 수 있을 것이다. claims: 딸기 모주에 IBA(indole-3-butyric acid)를 처리하여 육묘시키는 단계를 포함하는, 딸기 모주의 측아 발생 억제 및 자묘의 생육 증진 방법.30~120 mg·L-1의 IBA(indole-3-butyric acid)를 유효성분으로 함유하는, 시설재배 시 딸기 모주의 측아 발생 억제 및 자묘 생육 증진용 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

490/1059 Row 490: application_number: 1020200016022, combined_string: invention_title: 셀레늄 함유 딸기 재배 방법 및 이를 통해 재배된 딸기를 포함하는 가공식품 abstract: 본 발명은 셀레늄 함유 딸기 재배 방법 및 이를 통해 재배된 딸기를 포함하는 가공식품에 관한 것으로, 상세하게는 EDTA, 수산화물, 산화셀레늄, 및 ATCA를 포함하여 제조된 유기셀레늄 용액을 포함하는 딸기 재배 영양제를 이용한 셀레늄 함유 딸기 재배 방법과 이러한 방법을 통해 재배된 딸기를 이용한 가공식품에 관한 것이다.본 발명은 셀레늄 함유 딸기 재배 방법 및 이를 통해 재배된 딸기를 포함하는 가공식품을 제공함으로써 셀레늄의 함량이 높은 딸기를 재배할 수 있고 딸기 내 항산화, 폴리페놀, 플라보노이드와 같은 생리활성물질이 증가하는 효과를 나타낼 수 있다. 나아가 생리활성물질 및 셀레늄의 함량이 우수한 딸기를 이용하여 다양한 종류의 바이오헬스 식품을 개발할 수 있으며, 이를 쉽게 접할 수 있는 가공식품으로서의 개발이 가능한 효과가 있다. claims: 에틸렌디아민테트라아세트산(ethylendiaminetetracetic acid, EDTA), 수산화물(hydroxide), 산화셀레늄(Selenium oxide, SeO2) 및 아세틸티오프롤린(acetylthioproline, ATCA)를 포함하는 유기셀레늄 용액을 이용하여 딸기 재배 영양제를 형성하는 제 1 단계;상기 딸기 재배 영양제의 시비량 또는 시비횟수를 설정하는 제 2 단계; 및상기 시비량 또는 시비횟수가 설정된 딸기 재배 영양제를 딸기에 시비하는 제 3 단계;를 포함하는 것을 특징으로 하는 셀레늄 함유 딸기 재배 방법.제 1 항에 따른 방법으로 제배된 딸기를 포함하는 것을 특징으로 하는 가공식품., Ltext: 농업, prediction: 임업
491/1059 Row 491: application_number: 1020200015783, combined_string: invention_title: 매실 및 애호박 혼합 발효물을 이용한 기능성이 향상된 애호박의 재배방법 abstract: 본 발명은 (1) 매실 열매와 매실나무 가지를 혼합한 매실 혼합물에 설탕을 혼합한 후 발효하여 매실 발효물을 제조하는 단계; (2) 애호박 순과 애호박 가지를 혼합한 애호박 부산물에 설탕을 혼합한 후 발효하여 애호박 발효물을 제조하는 단계; (3) 상기 (1)단계의 제조한 매실 발효물과 상기 (2)단계의 제조한 애호박 발효물을 혼합한 후 가열한 영양액에 물을 첨가하여 영양 희석액을 제조하는 단계; 및 (4) 애호박 유묘를 식재하고, 상기 (3)단계의 제조한 영양 희석액을 관주 및 엽면처리하는 단계를 포함하는 애호박의 재배방법 및 상기 방법으로 재배된 애호박에 관한 것이다. claims: (1) 매실 열매와 매실나무 가지를 혼합한 매실 혼합물에 설탕을 혼합한 후 발효하여 매실 발효물을 제조하는 단계;(2) 애호박 순과 애호박 가지를 혼합한 애호박 부산물에 설탕을 혼합한 후 발효하여 애호박 발효물을 제조하는 단계;(3) 상기 (1)단계의 제조한 매실 발효물과 상기 (2)단계의 제조한 애호박 발효물을 혼합한 후 가열한 영양액에 물을 첨가하여 영양 희석액을 제조하는 단계; 및(4) 애호박 유묘를 식재하고, 상기 (3)단계의 제조한 영양 희석액을 관주 및 엽면처리하는 단계를 포함하는 애호박의 재배방법.제1항 내지 제3항 중 어느 한 항의 방법으로 재배된 애호박., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

492/1059 Row 492: application_number: 1020200002315, combined_string: invention_title: 플라스틱 복층판 abstract: 본 발명은 플라스틱 복층판에 관한 것으로, 보다 상세하게는 유리창 또는 온실 벽체의 단열성 즉, 복사열과 전도열을 필요에 따라 능동적으로 변화시켜 사계절 내내 실내 냉·난방, 조명 에너지 소비를 최소화하고, 특히 그동안 어려웠던 여름철 고온기 딸기 재배 등도 가능하게 하며, 저온기에도 난방비를 최소화하여 제로에너지에 가까운 온실 구현을 위한 온실 외피시스템, 혹은 그러한 에너지 절감형 건물 외피시스템을 구현할 수 있도록 개선된 플라스틱 복층판에 관한 것이다. claims: 태양광에 직접 노출되는 상판(1), 상기 상판(1)과 간격을 두고 평행하게 배치되는 하판(2) 및 상기 상판(1)과 하판(2)을 연결 고정하도록 수직하게 배치 고정되는 수직격판(3)으로 이루어지고, 상기 수직격판(3)에 의해 상기 상판(1)과 하판(2) 사이의 공간은 다수개의 수로(4)로 형성되며, 상기 수로(4)에는 유체가 순환되도록 구성된 플라스틱 복층판에 있어서;상기 유체는 물, 부동수 또는 차광수이며;상기 부동수는 물에 소금 또는 에틸렌글리콜을 7:3의 부피비로 혼합한 것이고;상기 차광수는 물에 적외선흡수액을 0.2부피%로 혼합하되, 적외선흡수액은 검은색 카본블랙, 먹물, 커피액, 염료 혹은 TiO2, ATO 또는 CTO가 분산되어 있는 안료액 중 어느 하나인 것을 특징으로 하는 플라스틱 복층판., Ltext: 농업, prediction: 임업
493/1059 Row 493: application_number: 1020190173950, combined_string: invention_title: 딸기 전동관리기 전용 멀칭기 abstract: 본 발명은 자동화 농업기계가 없거나, 적절한 형태로 개발되지 않았기 때문에 전적으로 인력에 의하여 작물을 재배하는 고설 재배를 생력화 및 자동화하는 기술을 제공하고자하는 것이다.특히, 재배 초기에는 고설 재배 시설을 설치하는 등의 작업이 많아 일손이 매우 부족하다. 이시기에 사용할 수 있는 고설 재배 전용 관리기에 부착하여 사용할 수 있는 멀칭기를 제공하고자 한다.이를 위하여 전방에 상기 딸기 전동관리기 결합부가 구비된 고정프레임; 및상기 고정프레임의 후단에 구비된 한 쌍의 이동바퀴; 및상기 고정프레임의 중단에 수평으로 구비되어 멀칭필름을 거치하는 멀칭필름 거치부; 및상기 고정프레임의 중단 하부에 구비되어 상기 멀칭필름을 고설 재배 장치에 결합하는 멀칭필름 고정부를 구비하는 것을 특징으로 하는 딸기 전동관리기 전용 멀칭기를 제공한다.상기와 같은 수단에 의하여 고설 재배 시설에서도 사용 가능한 가볍고 성능이 우수한 멀칭 비닐을 설치하는 멀칭기를 제공함으로써, 노동력을 절감할 수 있는 효과가 있다. claims: 딸기 전동관리기 전용 멀칭기에 있어서,전방에 상기 딸기 전동관리기 결합부가 구비된 고정프레임; 및상기 고정프레임의 후단에 구비된 한 쌍의 이동바퀴; 및상기 고정프레임의 중단에 수평으로 구비되어 멀칭필름을 거치하는 멀칭필름 거치부; 및상기 고정프레임의 중단 하부에 구비되어 상기 멀칭필름을 고설 재배 장치에 결합하는 멀칭필름 고정부를 구비하는 것을 특징으로 하는 딸기 전동관리기 전용 멀칭기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

494/1059 Row 494: application_number: 2020190005213, combined_string: invention_title: 유실수 나뭇가지 유인용 클립 abstract: 본 고안은 유실수 나뭇가지 유인용 클립에 관한 것이다.본 고안에 따르면 유실수 나뭇가지의 굵기에 따라 선택적으로 유입할 수 있도록 일체형으로 클립을 구성하여 가지의 균형을 유지시켜 원하는 방향으로 자랄 수 있고, 잎눈 또는 꽃눈의 발생이 용이하고 동시에 작업자의 사용이 편리하도록 하였으며, 과실수의 가지 유인 작업을 매우 손쉽고 정확하며 세밀하게 수행할 수 있게 됨에 따라 과수원의 전체적인 가지유인 작업에 소요되는 시간과 경비를 최대한으로 절감시키게 되었으며, 이로 인하여 과실재배농가의 소득증대와 경영수지의 개선 측면에 한층 더 이바지하게 되었고, 또한 클립 몸체에 형성된 돌출핀의 고정홈에 유입되는 나뭇가지와 유인요홈 사이에 공간이 유지됨에 따라 잎눈 또는 꽃눈 발생에 매우 유리하게 되었으며, 또한 클립 몸체에 가지가 유입되면서 휘어지는 각도를 다르게 함에 따라 과수나무의 전체적인 균형을 유지할 수 있는 효과가 제공된다. claims: 직선형의 내측몸체(12)와, 내측몸체(12)의 중앙 및 전후면에 동일 크기로 내측유인요부(2)(3)가 형성되도록 일체로 형성되고, 상하부면에 나뭇가지(1)의 장착성을 높이면서 가지 탈선방지 기능을 갖도록 내,외측돌기부(14a-1,15a-1,16a-1)를 갖는 고정홈(14a)(15a)(16a)이 형성되며, 내측유인요부(2)(3)의 간격이 넓게 유지되어 굵은 나뭇가지의 유인에 적합한 내측돌출핀(14)(15)(16)으로 이루어진 내측클립(10)과; 상기 내측클립(10)의 내측몸체(12) 외측 전후면에 동일 간격을 유지하여 일체로 형성되는 직선형의 외측몸체(22)와, 외측몸체(22)의 중앙 및 전후면에 동일 크기로 외측유인요부(4)(5)가 형성되도록 일체로 형성되고, 상하부면에 나뭇가지의 장착성을 높이면서 가지 탈선방지 기능을 갖도록 내,외측돌기부(24a-1,25a-1,26a-1)을 갖는 고정홈(24a)(25a)(26a)이 형성되며, 외측유인요부(4)(5)의 간격이 좁게 유지되어 굵기가 작은 나뭇가지의 유인에 적합한 외측돌출핀(24)(25)(26)으로 이루어진 외측클립(20)으로 구성되고,상기 고정홈(14a,15a,16a)(24a,25a,26a)은 유입되는 나뭇가지와 내측유인요부(2)(3) 및 외측유인요부(4)(5) 사이에 공간(1a)이 충분히 유지되도록 내측돌출핀(14)(15)(16) 및 외측돌출핀(24)(25)(26)의 상하부면 각각 형성되는 것을 특징으로 하는 유실수 나뭇가지 유인용 클립., Ltext: 농업, prediction: 임업
495/1059 Row 495: application_number: 1020190169096, combined_string: invention_title: 이미지 기반 작물 생육정보 자동계측 시스템 abstract: 본 발명은 이미지 기반 작물 생육정보를 산출하고 연관된 정보를 제공할 수 있는 기술에 대한 것으로, 재배 작물에 대한 이미지를 도출하여 입력하고, 이에 대한 딥러닝 알고리즘을 활용한 이미지 분석기반 작물의 생육정보, 품질 진단을 통해 생육정보에 따른 작물 양액 및 품질관리 , 수확시기 등의 영농정보 제공할 수 있다. claims: 분석대상의 작물의 이미지를 기관별로 분류하여 촬상하는 이미지촬영부(110)와 촬영된 이미지를 생육정보 산출모듈(200)로 전송하는 이미지전송부(120)를 포함하는 이미지 제공모듈(100); 상기 이미지 제공모듈(100)에서 제공된 이미지를 입력하고, 딥러닝 기반 작물의 기관별 기관 분류를 수행하며, 상기 이미지에 포함되는 작물의 기관별 물리적 계측정보를 도출하여, 상기 작물의 생육정보를 산출하는 생육정보 산출모듈(200); 상기 생육정보산출모듈(200)에서 입력된 상기 이미지에 대한 딥러닝 기반 작물의 기관별 기관 분류를 수행하는 경우 기준이 되는 표준 이미지 정보를 제공하는 기준정보 데이터베이스(300); 및 상기 생육정보 산출모듈(200)에서 산출되는 작물의 생육상태정보와 연계하는 작물의 재배기법 관련한 영농정보를 제공하는 영농정보 데이터베이스(400);을 포함하며,상기 생육정보 산출모듈(200)은, 상기 이미지전송부(120)을 통해 전송되는 이미지를 수신하여 입력하는 이미지 입력부(210); 상기 이미지 입력부(210)에 입력된 이미지를 상기 기준정보 데이터베이스(300)에서 제공하는 표준 이미지 정보와 대비하고, 딥러닝 기반 작물의 기관별 기관 분류를 수행하는 이미지 기반 기관분류부(220); 상기 이미지 기반 기관분류부(220)에서 분류된 기관별 이미지 정보의 물리적 계측을 위해 표준화한 이미지로 보정하는 이미지보정부(230); 상기 표준화한 이미지로 보정된 이미지에 계측대상이 되는 기관에 대한 실측 사이즈를 산출하는 기관별 계측치 산출부(240); 상기 기관별 계측치 산출부(240)에서 산출된 정보를 바탕으로 상기 작물의 과실에 대한 과중을 산출하는 과중산출부(250);를 포함하며,상기 과중산출부(250)는, 하기의 {식 1} 내지 {식 5}에 따른 과실에 대한 과중예측 방정식에 따른 과중의 예측치를 산출하고, 최근접 예측치를 과중 예측치로 선택하도록 구현되는, 이미지 기반 작물 생육정보 자동계측 시스템.{식 1}과장(A)*과폭(B){식 2}과장(A)2*과폭(A){식 3}과장(A)*과폭(B)2{식 4}{식 5}(단, 과장(果長)은 열매의 수직방향의 최장길이로 정의하며, 과폭은 열매의 수평방향의 최장길이로 정의한다.), Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

496/1059 Row 496: application_number: 1020190167540, combined_string: invention_title: 감초재배용 스마트 팜 시스템 abstract: 본 발명의 감초재배용 스마트 팜 시스템은, 고부가가치의 감초를 재배하도록 재배실의 환경을 수집하고 환경조성수단을 이용하여 재배실의 생장조건을 최적으로 조성하여 감초를 재배하는 스마트 팜 시스템이고, 재배실의 건조한 상태가 유지되고 감초가 생장하는 토양을 배수성이 우수한 모래를 이용하여 감초의 생장에 적합한 생장환경이 조성되고, 생장중인 감초의 생장을 촉진시키도록 감초의 생장시기별로 적합하게 조도, 온도, 습도, 통풍을 조절하고, 토양에 공급되는 수분의 적절한 공급량 및 배수성이 유지되도록 하는 발명에 관한 것이다. claims: 감초재배용 스마트 팜 시스템에 있어서,감초를 재배하기 위한 실내공간이 형성되고, 감초의 생장을 위해 필요한 재배 시설물(110)들이 설치되는 재배실(100)과;상기 재배실(100)의 실내공간에 설치되어, 감초 재배에 필요한 환경을 조성하는 환경조성수단(200)과;상기 재배실(100)의 실내공간에 설치되어, 재배실(100)의 환경 상태를 감지하여 환경정보를 생성하고, 재배실(100) 내부를 촬영한 모니터링용 영상정보를 생성하고, 감초 부패를 감지하여 감지정보를 생성하고, 생성된 환경정보, 영상정보, 감지정보를 관리서버(400)로 전송하는 환경수집수단(300)과;상기 환경수집수단(300)이 전송한 환경정보를 이용하여 재배실(100)의 실내공간이 감초 재배에 적합한 환경이 되도록 환경조성수단(200)을 제어하고, 환경수집수단(300)이 전송한 영상정보를 모니터링 화면에 표시하여 관리자가 재배실(100) 내부를 모니터링 할 수 있도록 하고, 환경수집수단(300)이 전송한 감지정보를 이용하여 감초 부패에 관한 이벤트 정보를 생성하여 모니터링 화면에 표시하는 관리서버(400)를 포함하는 것을 특징으로 하는 감초재배용 스마트 팜 시스템., Ltext: 농업, prediction: 임업
497/1059 Row 497: application_number: 2020190005027, combined_string: invention_title: 포도 무핵재배용 복합측정기 abstract: 본 고안의 일실시예에 따른 무핵재배용 복합측정기는 판 형상의 본체와, 본체의 테두리에 형성되어 개화전 꽃송이 길이를 측정하는 꽃송이길이 측정유닛과, 본체의 테두리에 설치되고 포도알의 횡경 크기를 측정하는 복수의 홈을 포함하는 포도알크기 측정유닛을 포함할 수 있다. claims: 판 형상의 본체;상기 본체의 테두리에 형성되어 개화전 꽃송이 길이를 측정하는 꽃송이길이 측정유닛; 및상기 본체의 테두리에 설치되고 포도알의 횡경 크기를 측정하는 복수의 홈을 포함하는 포도알크기 측정유닛을 포함하는 포도 무핵재배용 복합측정기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

498/1059 Row 498: application_number: 1020190161554, combined_string: invention_title: 신품종 딸기 베리퀸 및 이의 육종 방법 abstract: 본 발명은 설향을 모본 품종으로 하고 매향을 부본 품종으로 하여 이를 교배시켜 얻어진 것으로서, 과형이 장원추형이며, 모본 품종인 설향이나 부본 품종인 매향에 비해 당산비가 높고 또한 개화시기와 수확시기가 빨라 촉성 재배에 적합한 딸기 신품종 베리퀸과 그 육종방법을 개시한다. claims: 설향 품종을 모본으로 하고, 매향 품종을 부본으로 하여 이를 교배시켜 얻어진 것으로서, 아래 (1) 내지 (11)의 특성을 가지며, 종자 또는 자묘에 의하여 번식하는 딸기 신품종 베리퀸:(1) 잎 표면의 색은 중간 녹색이다;(2) 잎 반엽은 없다;(3) 정단부 소엽 기부의 모양은 뾰족하다;(4) 정단부 소엽 가장자리의 톱니모양은 예거치-둔거치이다;(5) 꽃 수술은 있다;(6) 과실 너비에 대한 상대적 길이는 너비보다 매우 길다;(7) 과실 모양은 장원추형이다;(8) 과실 색은 중간 적색이다;(9) 과실의 과육색은 중간 적색이다;(10) 과실의 과심색은 옅은 적색이다; 및(11) 결실 유형은 1회 개화 결실이다.(a) 모본 품종인 설향과 부본 품종인 매향을 파종하는 단계, (b) 개화 시기에 모본 품종인 설향과 부본 품종인 매향을 인위적으로 교배시키는 단계, (c) 교배된 개체의 과실에서 종자를 채종하는 단계, (d) 종자를 발아·생육시켜 실생 개체를 얻는 단계, (e) 실생 개체 중 초세와 당산비를 선발 기준으로 하여 4~10 계통을 선발하여 자묘에 의하여 증식시키는 단계, 및 (f) 증식된 계통 중 과형과 당산비를 선발 기준으로 하여 최종 1계통를 선발하는 단계를 포함하되,상기 최종 1계통은 아래 (1) 내지 (11)의 특성을 가지는 것을 특징으로 하는 딸기 신품종 베리퀸의 육종 방법:(1) 잎 표면의 색은 중간 녹색이다;(2) 잎 반엽은 없다;(3) 정단부 소엽 기부의 모양은 뾰족하다;(4) 정단부 소엽 가장자리의 톱니모양은 예거치-둔거치이다;(5) 꽃 수술은 있다;(6) 과실 너비에 대한 상대적 길이는 너비보다 매우 길다;(7) 과실 모양은 장원추형이다;(8) 과실 색은 중간 적색이다;(9) 과실의 과육색은 중간 적색이다;(10) 과실의 과심색은 옅은 적색이다; 및(11) 결실 유형은 1회 개화 결실이다., Ltext: 농업, prediction: 농업
499/1059 Row 499: application_number: 1020190141919, combined_string: invention_title: 이동식 비료 살포장치 abstract: 본 발명은 과수원을 포함하는 각종 작물이 재배되는 농경지의 협소한 곳을 자력으로 이동하며 자동으로 비료를 균일하게 살포할 수 있도록 한 이동식 비료 살포장치에 관한 것으로, 그 구성은, 바퀴가 설치된 본체의 전방에 호퍼가 설치되고 그 호퍼에는 비료배출수단과 비료배출양조절수단이 설치되며 상기 비료배출양조절수단의 하부에는 비료살포수단이 설치되고, 그 비료배출수단에는 비료공급수단이 설치되며, 상기 본체의 후방에는 동력발생수단과 조향장치를 설치하여 된 것으로 이루어진다. claims: 전/후방 양측에 각각의 바퀴(110)가 회전축(120)에 설치되고, 상기 각 바퀴는 동력전달수단(130)의 동력을 전달받아 구동하도록 설치하여 된 본체(100);상기 본체의 전방 설치되고, 후방은 상부에서 하부 전방으로 하향 기울기를 갖는 경사면(210)이 형성되며, 전방 상부에는 덮개(220)를 설치하여 된 호퍼(200);상기 호퍼의 전방 내측 바닥면에 설치되어 호퍼에 수용된 비료를 하부로 배출하도록 비료배출구멍(320)을 형성시켜 된 비료배출수단(300);상기 비료배출구멍의 하부에 설치되어 상기 비료배출구멍의 크기를 조절하며 비료배출양을 가감하도록 하는 비료배출양조절수단(400);상기 비료배출양조절수단의 하부에 복수 개의 비료살포가이드(520)가 방사상으로 설치된 회전원판(510)이 설치되고, 그 회전원판의 외곽에는 전방에 개방부(540)가 형성된 격벽(530)을 설치하여 된 비료살포수단(500);상기 덮개, 비료배출수단, 비료배출양조절구, 비료살포수단을 관통하는 회전축(610)이 설치되고 그 회전 축의 상단에 모터(620)가 설치되며, 상기 비료배출수단의 상부 회전축에는 비료교반부재(630)를 설치하여 된 비료공급수단(600);상기 본체의 후방에 설치되어 상기 제1 내지 제3모터로 동력원을 공급하는 동력발생수단(700);상기 동력발생수단의 상부에 위치하도록 설치되어 본체의 이동을 제어하도록 설치된 조향장치(800); 을 포함하는 구성을 특징으로 하는 이동식 비료 살포장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

500/1059 Row 500: application_number: 1020190140419, combined_string: invention_title: ＩＣＴ 및 ＩｏＴ를 이용한 스마트 양묘장 구축 및 운영시스템, 그리고 제어 방법 abstract: 본 발명은 ICT 및 IoT를 이용한 스마트 양묘장 구축 및 운영시스템, 그리고 제어 방법에 관한 것이다. 본 발명은, 수소발생 시스템(100), 네트워크(200), 양묘 및 스마트팜 관리 서버(300)를 포함하는 ICT 및 IoT를 이용한 스마트 양묘장 구축 및 운영시스템에 있어서, 양묘 및 스마트팜 관리 서버(300)는, 송수신부(310); 및 네트워크(200)를 통해 수소발생 시스템(100)의 온실운영 관리단말(140)과 데이터 세션을 연결한 뒤, 온실운영 관리단말(140)에 대한 제어명령 전송하도록 송수신부(310)를 제어하여 수소발생기(110)에 대해서 외부로부터 도시가스(LNG)가 입력배관을 타고 들어와서 수소발생기(110)를 통해 수소가스(H2)가 발생되면 수소저장탱크로 저장하며,수소발생기(110) 상에서 도시가스(LNG)에 대한 사용에 따라 발전된 전기 에너지와, 태양광발전기(120) 및 풍력발전기(130)에서 각각 발전된 전기 에너지를 충전지에 저장하는 발전 제어 모듈(321); 을 포함하는 것을 특징으로 한다.본 발명에 따르면, 스마트팜, 그 중에서도 특히 스마트 양묘장에 대한 에너지 효율을 고려하기 위해 최근에 각광받고 있는 신재생에너지를 활용할 뿐만 아니라, IoT 기반의 센싱 기술을 이용한 에너지 사용 효율을 극대화시킬 수 있고, 신재생에너지에 대한 가공 및 재판매가 가능할 뿐만 아니라, 신재생에너지의 생산시에 발생되는 부수적인 자원을 재활용 에너지원으로 활용할 수 있는 효과가 있다. claims: 수소발생기(110), 태양광발전기(120), 풍력발전기(130), 온실운영 관리단말(140)을 구비하는 수소발생 시스템(100) 외에, 네트워크(200), 양묘 및 스마트팜 관리 서버(300)를 포함하며, 수소발생기(110)는, 수소 분리 발생기, 이산화탄소(CO2)저장탱크, 전기에너지 발전기, 열에너지 저장탱크를 포함함으로써, 수소 분리 발생기에 의해 도시가스(LNG)에서 탄화수소를 취득하고 취득된 탄화수소를 개질하여 수소가스(H2)를 발생시킬 뿐만 아니라, 도시가스(LNG)를 분해하는 과정에서 수소 1kg당 이산화탄소(CO2) 온실가스 9 내지 12kg를 획득하여 이산화탄소(CO2) 저장탱크에 보관하며, 획득된 수소가스(H2)를 전기에너지 발전기를 통해 직접 연소나 연료전지를 이용해 전기에너지로 전환시키며, 전기에너지 전환시 열에너지도 발생시켜서 열에너지 저장탱크에 보관하는 ICT 및 IoT를 이용한 스마트 양묘장 구축 및 운영시스템에 있어서, 양묘 및 스마트팜 관리 서버(300)는, 송수신부(310); 및 네트워크(200)를 통해 수소발생 시스템(100)의 온실운영 관리단말(140)과 데이터 세션을 연결한 뒤, 온실운영 관리단말(140)에 대한 제어명령을 전송하도록 송수신부(310)를 제어하여 수소발생기(110)에 대해서 외부로부터 도시가스(LNG)가 입력배관을 타고 들어와서 수소발생기(110)를 통해 수소가스(H2)가 발생되면 발생된 수소가스를 수소저장탱크로 저장하며, 수소발생기(110) 상에서 도시가스(LNG)에 대한 사용에 따라 발전된 전기 에너지와, 태양광발전기(120) 및 풍력발전기(130)에서 각각 발전된 전기 에너지를 충전지에 저장하는 발전 제어 모듈(321); 각 수소저장탱크 단위에 대해서 각 수소검침센서가 구비되는 경우, 수소저장탱크에 미리 설정된 임계치 이상의 수소가스(H2)가 저장된 것을 온실운영 관리단말(140)로부터 네트워크(200)를 통해 수신하도록 송수신부(310)를 제어한 뒤, 네트워크(200)를 통해 관리자 단말(400)로 저장이 완료된 각 수소저장탱크의 일련번호를 전송하도록 송수신부(310)를 제어함으로써, 관리자 단말(400)에 의해 수소저장탱크 별로 외부에서 수소가스(H2)를 필요로 하는 업체에 판매를 할 수 있도록 하는 에너지 제공 모듈(322); 수소발생기(110)과 비닐하우스(2) 간에는 CO2 배관, 열 배관이 구비된 상태에서 수소발생기(110) 상에서 발생하는 이산화탄소(CO2)가 이산화탄소 저장탱크에 미리 설정된 CO2 임계치를 초과하는 경우 이산화탄소(CO2)를 비닐하우스(2) 내부로 제공하여 과육의 당도를 높이고, 수소발생기(110) 상에서 발생하는 열을 저장하는 열에너지 저장탱크에 열에너지가 미리 설정된 열에너지 임계치를 초과하는 경우 비닐하우스(2) 내부로 제공하기 위한 비닐하우스(2)의 내부 이산화탄소 농도(CO2) 및 온도에 대한 제어 명령을 네트워크(200)를 통해 온실운영 관리단말(140)로 전송하도록 송수신부(310)를 제어하며, 수소발생기(110) 상에서 발생하는 전기 에너지가 충전지에 미리 설정된 전기 에너지 임계치를 초과하는 경우 수소발생기(110)와 제어부(510) 간에 형성되는 전력배선을 이용해 비닐하우스(2)를 관리하는 제어부(510), 센서부(520), CCTV 그룹(530) 및 제어장치부(540)로 전기 에너지를 제공하도록 제어함으로써, CO2 배관을 통해 제공된 CO2를 활용한 제어부(510)에 의한 센서부(520)를 구성하는 CO2 센서(522)의 센싱 정보에 따라 비닐하우스(2) 내부에 재배되고 있는 농작물의 과육의 당도를 높이기 위한 당도가 제어되도록 하며, 열 배관을 통해 제공된 열에 대한 제어부(510)에 의한 센서부(520)를 구성하는 온/습도 센서(521)의 센싱 정보에 따라 비닐하우스(2) 내부에 재배되고 있는 농작물의 미리 설정된 온도 범위로 제어되도록 하며, 제어부(510)에 의해 제어장치부(540)를 구성하는 관수제어기(543)에 대한 제어를 통해 열 배관으로 들어오는 열기를 제어할 뿐만 아니라, 환기팬(541)을 통한 비닐하우스(2) 내부의 환기를 제어하고, 측천장제어기(544)를 외부 온/습도센서(521)와 내부 온/습도센서(521)에 의해 측정된 내부의 온도 및 습도에 기초하여 미리 설정된 온도 및 습도 범위로 제어가 수행되도록 하며, 제어부(510)에 의해 온/난방기(542)를 통해 비닐하우스(2) 내부의 온/습도센서(521)에 의해 측정된 온도 및 습도에 대한 정보를 통해 온열 또는 난방을 미리 설정된 온도 범위 내에서 제어할 수 있도록 하며, 제어부(510)에 의해 유압 실린더 방식으로 제어되는 채광커튼(545)에 대한 제어를 통해 비닐하우스(2)에 대한 일광조건을 제어하도록 하는 에너지 분배 모듈(323); 네트워크(200)를 통해 통합제어기(700)와 데이터 세션을 연결한 뒤, 통합제어기(700)를 통해 비닐하우스(2)의 전면과 후면에 각각 하나씩 형성된 종합감시센서(600)로부터 감시정보를 수신하되, 비닐하우스(2)의 전면과 후면에 각각 하나씩 형성된 종합감시센서(600) 중 적어도 하나로부터 지진, 화재, 출입 중 적어도 하나 이상을 감지한 뒤, 네트워크(200)를 통해 관리자 단말(500)로 비닐하우스(2)의 전면과 후면 중 적어도 하나 이상에서 발생한 지진 감지 정보, 화재 감지 정보, 출입 감지 정보를 실시간으로 제공하며, 네트워크(200)를 통해 통합제어기(700)와 데이터 세션을 연결한 뒤, 통합제어기(700)를 통해 비닐하우스(2)의 외부 및 내부에 미리 설정된 위치에 설치된 CCTV(310)로 구성된 CCTV 그룹(300)으로부터 영상 정보 수신 요청을 전송하도록 송수신부(310)를 제어하는 종합 감시 모듈(324); 을 포함하며, 종합감시센서(600)는, 하나의 모듈 형태의 센서로 전원이 인가되면 전원을 저장하는 배터리, 배터리로부터의 전원 인가 유무에 따라 점멸하는 점등 램프와, 제어 회로부 이외에도, 스피커, 디스플레이 패널, 지진 감지기, 화재 감지기, 출입 감지기, 이동 통신모듈을 포함함으로써, 비닐하우스(2)의 전방 및 후방에서의 출입 감지기를 통한 사람의 출입을 감지하고, 지진 감지기를 통해 비닐하우스(2)의 전방 및 후방에서의 지진을 감지하며, 화재 감지기를 통해서 비닐하우스(2)의 전방 및 후방에서의 화재를 감지한 뒤, 통합제어기(700)를 통해 네트워크(200)와 연결된 양묘 및 스마트팜 관리 서버(300)로 감지 정보를 전송함으로써, 종합 감시 모듈(324)에 의해 감지 정보가 데이터베이스(330)에 저장하도록 하며, 통합제어기(700)와 각 CCTV(310) 간에는 TVWS(TV White Space) 전파에 해당하는 공중파 전파를 이용하여 CCTV 영상을 전송하며, 통합제어기(700)는 CCTV 영상을 네트워크(200)를 통해 다시 종합 감시 모듈(324)로 제공하며,관리자 단말(400)은, 네트워크(200)를 통해 양묘 및 스마트팜 관리서버(300)로 액세스하여 데이터베이스(330)에 저장된 CCTV 그룹(530)을 구성하는 각 CCTV(531) 중 비닐하우스(2) 내부를 찍은 영상 데이터를 통해 비닐하우스 내부의 영상 데이터를 획득한 뒤, 획득된 영상 데이터를 활용해 비닐하우스 내부의 부지에 대한 형상정보를 획득하고, 비닐하우스를 위한 복수의 비닐하우스 요소(element) 정보{농작물(나무, 꽃, 수생농작물을 포함) 요소(element), 비닐하우스 전기/전자 제어장치 요소(element)(환기팬, 온/난방기, 관수제어기, 측천장제어기, 채광커튼 등)}를 네트워크(200)를 통해 양묘 및 스마트팜 관리서버(300)로부터 수신한 뒤, 수신된 비닐하우스 요소 정보 중 추가로 설치하고자 하는 비닐하우스 요소 정보를 선택하고, 비닐하우스 내부 면적 정보, 각 선택된 비닐하우스 요소(element) 정보에 대한 제곱 센치미터(cm2) 기준의 차지하는 면적 정보, 그리고 내부에 이미 설치된 농작물 요소 정보 및 비닐하우스 전기/전자 제어장치 요소가 이미 차지하고 있는 면적 정보 및 위치 정보를 네트워크(200)를 통해 양묘 및 스마트팜 관리서버(300)로부터 수신한 뒤, 추가로 선택된 비닐하우스 요소 정보를 추가하는 경우 비닐하우스 내부 면적 정보 내에 포함되는지 여부를 분석한 뒤, 모두 포함되는 경우 추가된 비닐 하우스 요소 정보가 추가된 비닐하우스(2) 내부의 모델링 정보를 생성하는 것을 특징으로 하는 ICT 및 IoT를 이용한 스마트 양묘장 구축 및 운영시스템., Ltext: 농업, prediction: 임업
501/1059 Row 501: application_number: 1020190139316, combined_string: invention_title: 온실용 조명장치 abstract: 본 발명은 온실의 일측 영역으로 빛을 조사하여 과수류를 수확한 후 분리하여 타측 영역으로 빛을 조사하여 과수류를 수확하며 빛의 조사 각도를 조절하여 과수류를 용이하게 수확할 수 있는 온실용 조명장치에 관한 것이다.이러한 본 발명은 온실에서 재배되는 과수류로 빛을 조사하는 온실용 조명장치에 있어서, 상기 온실의 상부에 전후 방향으로 연결된 가이드레일, 상기 가이드레일을 따라 이동 가능하게 연결된 슬라이더, 상기 슬라이더의 하부에 연결되어 상기 온실의 전후 방향으로 길게 배치되는 행거바, 상기 행거바에 분리 가능하게 거치되도록 훅을 갖는 거치프레임, 상기 거치프레임에 회전 가능하게 연결된 광원프레임, 상기 광원프레임의 회전 각도를 조절하도록 상기 거치프레임에 연결된 조절부재, 상기 광원프레임에 설치되어 상기 온실의 과수류로 빛을 조사하는 광원을 포함한다. claims: 온실에서 재배되는 과수류로 빛을 조사하는 온실용 조명장치에 있어서,상기 온실의 상부에 전후 방향으로 연결된 가이드레일,상기 가이드레일을 따라 이동 가능하게 연결된 슬라이더,상기 슬라이더의 하부에 연결되어 상기 온실의 전후 방향으로 길게 배치되는 행거바,상기 행거바에 분리 가능하게 거치되도록 훅을 갖는 거치프레임,상기 거치프레임에 외측면 방향으로 회전 가능하게 연결된 광원프레임,상기 광원프레임의 회전 각도를 조절하도록 상기 거치프레임에 연결된 조절부재,상기 광원프레임에 설치되어 상기 온실의 과수류로 빛을 조사하는 광원을 포함하는 온실용 조명장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

502/1059 Row 502: application_number: 1020190134934, combined_string: invention_title: 딸기재배포트를 이용한 실내 체험용 화분딸기 재배방법 및 그로부터 수확한 딸기 abstract: 본 발명은 딸기재배포트를 이용한 실내 체험용 화분딸기 재배방법 및 그로부터 수확한 딸기에 관한 것이다. 본원 발명은 딸기가 심겨진 재배포트를 잡아주는 2~4개의 포트지지부(33), 상기 포트지지부의 끝단에는 포트걸이부(29)가 형성되며, 상기 포트걸이부(29)는 고정봉(28)에 고정되어 재배포트(30)가 낙하되지 않도록 고정시키고, 상기 고정봉(28)은 승강로프(27)에 연결되어 있어 모터(21)의 작동으로 회전되는 회전축(26)의 회전에 따라 순차적으로 모터의 동력이 전달되어 승강로프(27)가 승하강하게되며, 상기 승강로프(27)가 승하강됨에 따라 재배포트(30)는 위 또는 아래로 이동하게 된다.그리고 상기 모터(21)가 구동되면 구동체인(22)이 회전되고, 상기 구동체인은 주기어(23)를 회전시키며, 상기 주기어(23)에 장착된 회전축(26)이 회전하면서 회전축(26)에 끼워진 보조기어(24)가 회전하게되면 상기 보조기어(24)가 승강로프(27)가 고정된 회전봉을 회전시켜 재배포트의 승하강 동력을 전달한다.이처럼 본 발명은 딸기의 꽃이 피거나 딸기 열매가 달린 재배포트를 소비자가 직접 구매할 수 있게 되어 농가의 소득을 크게 증대시킬 수 있다. 그리고 딸기 재배포트를 가정의 거실에서 키울 수 있어 화초처럼 딸기를 관상용으로 재배하거나 실내에서 식물이 자라서 꽃을 피우고 열매가 익어가는 과정을 직접 관찰할 수 잇으며, 건조한 늦겨울이나 봄철에 쾌적한 실내 환경을 제공한다. claims: 딸기 재배포트(30)을 이용한 실내 체험용 화분딸기의 재배방법에 있어서,상기 실내 체험용 화분딸기 재배방법은 유리온실 중앙에 온실내부기둥(40)이 온실의 지붕을 중앙에서 지지하게 되며 온실의 지붕은 천장의 내부골조(46)를 지지하게 되고, 상기 내부골조(46)와 일정간격 이격되어 외부골조(47)가 형성되며, 상기 외부골조와 내부골조 사이에는 외부골조를 지지하는 지지물이 형성되고, 상기 외부골조(47)에는 유리를 포함하는 보온커버(60)로 피복하고,모터(21)의 구동에 의해 구동체인(22)이 회전하면서 주기어(23)를 회전시키고 주기어(23)에 장착된 회전축(26)이 회전하며, 상기 회전축(26)에 끼워진 보조기어(24)는 회전축의 회전에 따라 회전하고, 상기 보조기어(24)는 승강로프(27)가 고정된 회전봉을 회전시키며, 상기 회전축(26)에는 겨울철에 보온을 위하여 부직포(50)를 권취하여 상기 모터의 동력에 의해 감아주거나 풀어주고,상기 딸기 재배포트(30)는 2~4개의 포트지지부(33)로 잡아주고, 상기 포트지지부의 끝단에 포트걸이부(29)가 형성되어 있어 상기 포트걸이부(29)가 고정봉(28)에 고정되어 재배포트(30)가 떨어지지 않도록 고정되어 유리온실의 내부에서 일정한 간격으로 배치되어 재배되며,상기 고정봉(28)은 승강로프(27)에 연결되어 있어 모터(21)의 작동으로 회전되는 회전축(26)의 회전에 따라 순차적으로 모터의 동력이 전달되어 승강로프(27)가 승하강되며, 상기 승강로프(27)가 승하강됨에 따라 딸기 재배포트(30)는 위 또는 아래로 이동되고,상기 딸기 재배포트(30)를 승하강 방식으로 재배할 때 딸기 재배포트(30)의 딸기를 관리하거나 딸기를 수확하는 경우에는 지상에서 50~120cm 높이로 딸기 재배포트를 내려서 관리하고, 관리가 끝난 다음에는 상승시켜 재배하며,상기 딸기 재배포트(30)에는 상토를 채우고 재배포트의 포트하부(35)에는 과도하게 관수된 수분이 제거될 수 있도록 수분배출공이 형성되며, 상기 수분배출공은 관수 후 상토의 수분 함량이 70~85% 정도 유지되도록 구멍을 형성시켜 주며,상기 딸기 재배포트(30)에는 상토의 수분 상태가 일정하게 유지될 수 있도록 1일 2~4회 점적관수하는 하며, 1~3일에 1~2회 양액을 상기 딸기 재배포트에 공급하여 딸기 재배포트에 공급되는 딸기 양액의 1일 공급량은 정식 이후 개화초기 까지는 30~60mL, 수확기에는 120~180mL 정도를 공급하는 것을 특징으로 하는 딸기 재배포트를 이용한 실내 체험용 화분딸기의 재배방법., Ltext: 농업, prediction: 임업
503/1059 Row 503: application_number: 1020190128345, combined_string: invention_title: 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템 abstract: 본 발명은 태양광발전과 과수 작물의 영농 활동을 병행하는 것이 가능하게 하는 것과 함께, 태양광 발전 장치를 설치하기 위해 임야에 대대적인 토목공사를 하는 등의 환경 파괴 및 농작지 파괴를 하지 않음은 물론, 태양광 발전의 발전량을 효율화하는 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템의 구조, 형상, 기능을 제공할 수 있는 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템이 제공된다. 본 발명에 따르면, 태양광 발전과 과수 작물의 영농 활동을 저렴한 비용으로 동시 영위가 가능하며, 농업 병행 발전을 위하여 태양전지 모듈 거치대를 별도로 시공하지 않고 기존의 작물 비가림 하우스 기능을 겸하게 함으로써 경제적인 시스템 구축이 가능하고, 기존의 과수원의 작물이 남향이 아니더라도 태양광 패널의 각도 가변이 가능한 구조물을 통해서 발전량의 최대화가 용이하다. claims: 복수의 태양광 패널(10); 및 상부에 상기 복수의 태양광 패널이 설치되는 시설 구조물;을 포함하는 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템 으로서,상기 시설 구조물은,하단부에 지중 매설용 파일(pile)이 형성되어, 작물 재배지의 면적에 상응하여 행 방향 및 열 방향으로 각각 소정 간격만큼씩 이격되어 수직 설치되는 복수의 파일 지지대(130);상기 파일 지지대(130) 상에 설치되어 상기 작물 재배지의 지붕 역할을 수행하며, 광투과성 재질로 제작되는 복수의 비가림막(140b);상기 복수의 비가림막(140b)이 각각 설치될 영역에 상응하여 마련되어 상기 비가림막(140b)을 안착 지지하는 복수의 비가림막 지지대(114b);상기 비가림막(140b)의 상측에서, 행 방향과 열 방향으로 일렬로 놓인 각각의 파일 지지대(130) 간을 일체로 연결하는 복수의 수평 지지대(110b);일단이 상기 파일 지지대(130)에 결합되고, 타단이 상기 비가림막 지지대(114b)에 결합되어, 각각의 파일 지지대(130)의 좌우 양측에서 사선 방향으로 상기 비가림막 지지대(114b)를 지지하는 복수의 사선 지지대(116);상기 복수의 태양광 패널(10)이 각각 설치될 영역에 상응하여 마련되어 상기 태양광 패널(10)을 안착 지지하며, 상기 수평 지지대(110b)의 상부에 결합되는 복수의 패널 지지대(112b);상기 태양광 패널(10)의 설치 각도의 변경을 수행하는 각도 변경부(50);상기 시설 구조물에 적어도 하나 설치되어, 상기 작물의 식재 공간의 광 세기를 측정하는 조도 센서;를 포함하고,상기 복수의 비가림막(140b)은,상호간에 소정의 경사각을 갖도록 설치되어 지붕 형태를 구성하고, 서로 인접한 비가림막(140b)의 양 끝단 간에 형성되는 소정 간격의 공간에는 빗물받이부(118)가 설치되어, 상기 복수의 비가림막(140b)과 상기 빗물받이부(118)는 상기 작물 재배지를 모두 커버하고,상기 복수의 태양광 패널(10)은,상기 비가림막(140b)의 상부의 복수의 패널 지지대(112b) 상에 안착 지지되며, 상기 각도 변경부(50)에 의해 상기 태양광 패널(10)의 방위각 변경 및 고도각 변경 중 적어도 하나가 실행되어, 상기 작물 재배지의 광 세기를 측정하는 조도 센서의 센싱 결과에 따라, 측정된 광 세기가 작물의 광포화점보다 낮은 값을 갖는 경우, 광차폐 영역이 차지하는 면적 비율을 낮추고, 측정된 광 세기가 작물의 광포화점보다 높은 값을 갖는 경우, 상기 태양광 패널(10)의 광입사면이 태양의 이동 위치를 추적하도록 함과 동시에, 상기 태양광 패널(10)의 고도각을 변경하여 태양의 고도 변화를 추적하도록 제어되는 것을 특징으로 하는, 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

504/1059 Row 504: application_number: 1020190128416, combined_string: invention_title: 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물 abstract: 본 발명은 태양광발전과 과수 작물의 영농 활동을 병행하는 것이 가능하게 하는 것과 함께, 태양광 발전 장치를 설치하기 위해 임야에 대대적인 토목공사를 하는 등의 환경 파괴 및 농작지 파괴를 하지 않음은 물론, 태양광 발전의 발전량을 효율화하는 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물의 구조, 형상, 기능을 제공할 수 있는 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물이 제공된다. 본 발명에 따르면, 태양광 발전과 과수 작물의 영농 활동을 저렴한 비용으로 동시 영위가 가능하며, 암석이 많은 지반에서도 경제적으로 태양광 구조물의 기초 공사 가능 방법을 제공할 수 있고, 기존의 과수원의 작물이 남향이 아니더라도 태양광 패널의 각도 가변이 가능한 구조물을 통해서 발전량의 최대화가 용이하다. claims: 복수의 태양광 패널; 및 상부에 상기 복수의 태양광 패널이 설치되는 시설 구조물;을 포함하는 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물 로서,상기 시설 구조물은,하단부에 지중 매설용 파일(pile) 이 형성되어, 작물 재배지의 면적에 상응하여 행 방향 및 열 방향으로 각각 소정 간격만큼씩 이격되어 수직 설치되는 복수의 파일 지지대(130); 상기 파일 지지대(130) 상에 설치되어 상기 작물 재배지의 지붕 역할을 수행하며, 광투과성 재질로 제작되는 복수의 비가림막(140b);상기 복수의 비가림막(140b)이 각각 설치될 영역에 상응하여 마련되어 상기 비가림막(140b)을 안착 지지하는 복수의 비가림막 지지대(114b);상기 비가림막(140b)의 상측에서, 행 방향과 열 방향으로 일렬로 놓인 각각의 파일 지지대(130) 간을 일체로 연결하는 복수의 수평 지지대(110b);일단이 상기 파일 지지대(130)에 결합되고, 타단이 상기 비가림막 지지대(114b)에 결합되어, 각각의 파일 지지대(130)의 좌우 양측에서 사선 방향으로 상기 비가림막 지지대(114b)를 지지하는 복수의 사선 지지대(116);상기 복수의 태양광 패널의 각각이 설치될 영역에 상응하여 마련되어 상기 태양광 패널을 안착 지지하며, 상기 수평 지지대(110b)의 상부에 결합되는 복수의 패널 지지대(112b);상기 태양광 패널의 설치 각도의 변경을 수행하는 각도 변경부(50);상기 시설 구조물에 적어도 하나 설치되어, 상기 작물의 식재 공간의 광 세기를 측정하는 조도 센서;를 포함하고,상기 복수의 비가림막(140b)은,상호간에 소정의 경사각을 갖도록 설치되어 지붕 형태를 구성하고, 서로 인접한 비가림막(140b)의 양 끝단 간에 형성되는 소정 간격의 공간에는 빗물받이부(118)가 설치되어, 상기 복수의 비가림막(140b)과 상기 빗물받이부(118)는 상기 작물 재배지를 모두 커버하고,상기 복수의 태양광 패널은,상기 비가림막(140b)의 상부의 복수의 패널 지지대(112b) 상에 안착 지지되며, 상기 각도 변경부(50)에 의해 상기 태양광 패널의 방위각 변경 및 고도각 변경 중 적어도 하나가 실행되어, 상기 작물 재배지의 광 세기를 측정하는 조도 센서의 센싱 결과에 따라, 측정된 광 세기가 작물의 광포화점보다 낮은 값을 갖는 경우, 광차폐 영역이 차지하는 면적 비율을 낮추고, 측정된 광 세기가 작물의 광포화점보다 높은 값을 갖는 경우, 상기 태양광 패널의 광입사면이 태양의 이동 위치를 추적하도록 함과 동시에, 상기 태양광 패널의 고도각을 변경하여 태양의 고도 변화를 추적하도록 제어되며,상기 복수의 수평 지지대 각각은, 수평 방향으로 연장되는 상측 지지대(212); 상기 상측 지지대와 평행하게 연장되는 하측 지지대(214); 상기 상측 지지대(212)와 하측 지지대(214) 사이를 수직 방향에서 지지하기 위해 소정 간격 만큼씩 이격되어 고정 설치되는 복수의 수직 보강빔(216); 상기 상측 지지대(212)와 하측 지지대(214) 사이를 사선 방향에서 지지하기 위해 소정 간격만큼씩 이격되어 고정 설치되는 복수의 사선 보강빔(218)를 포함하는 이중 지지 구조를 갖고,상기 지중 매설용 파일(pile) 은 암석 기반의 지중 시공에도 용이하도록 П자 형상을 갖도록 제작되는 것을 특징으로 하는, 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물., Ltext: 농업, prediction: 임업
505/1059 Row 505: application_number: 1020190122401, combined_string: invention_title: 과일의 재배방법. abstract: 본 발명은 과일의 재배방법에 관한 것으로, 과수의 휴면기에 미네랄 분산액을 과수 경작지 토양에 살포하는 단계, 과수의 생육기에 상기 미네랄 분산액을 매월 1회 과수 엽면에 살포하는 단계를 포함하며, 상기 미네랄 분산액은 칼슘염, 마그네슘염, 및 게르마늄염을 함유하는 미네랄 수용액을 제조하는 단계, 상기 미네랄 수용액에 트리에틸아민을 부가하여 미네랄 침전물을 제조하는 단계, 상기 미네랄 침전물에 증류수 및 계면활성제를 부가하고 혼합하여 미네랄 분산액을 제조하는 단계를 포함하여 제조되는 것을 특징으로 한다. claims: 과수의 휴면기에 미네랄 분산액을 과수 경작지 토양에 살포하는 단계;과수의 생육기에 상기 미네랄 분산액을 매월 1회 과수 엽면에 살포하는 단계;를 포함하며,상기 미네랄 분산액은 칼슘염, 마그네슘염, 및 게르마늄염을 함유하는 미네랄 수용액을 제조하는 단계;상기 미네랄 수용액에 트리에틸아민을 부가하여 미네랄 침전물을 제조하는 단계;상기 미네랄 침전물에 증류수 및 계면활성제를 부가하고 혼합하여 미네랄 분산액을 제조하는 단계;를 포함하여 제조되는 것을 특징으로 하는 과일의 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

506/1059 Row 506: application_number: 1020190117314, combined_string: invention_title: 스피루리나를 이용한 딸기 재배용 영양제 또는 비료 조성물 abstract: 본 발명은 스피루리나를 이용한 딸기 재배용 영양제 또는 비료 조성물에 관한 것으로, 더욱 상세하게는 스피루리나의 발효 추출물을 유효성분으로 포함하되, 상기 스피루리나의 발효 추출물은, 스피루리나의 추출물을 바실러스 균주로 발효시킨 것임을 특징으로 한다. 본 발명에 의하면, 딸기의 생장이 촉진되는 것은 물론, 딸기의 콜린, 비타민, 칼슘의 함량이 높으며, 당도가 우수한 딸기의 재배가 가능하다는 장점이 있다. claims: 스피루리나의 발효 추출물을 유효성분으로 포함하되,상기 스피루리나의 발효 추출물은,스피루리나의 추출물을 바실러스 균주로 발효시킨 것임을 특징으로 하는 스피루리나를 이용한 딸기 재배용 조성물., Ltext: 농업, prediction: 임업
507/1059 Row 507: application_number: 1020190109473, combined_string: invention_title: 수목재배지 상의 가림막 설치공법 abstract: 본 발명은 기상이변에 신속하게 대응할 수 있는 과수, 채소 재배 노지에 가림막을 설치하는 공법에 대한 것으로, 본 발명의 실시예에 따르면, 노지에서 재배하는 채소, 과실수 등의 수목이 갑작스런 기상이변으로 우박이나 폭우 등으로 입을 수 있는 피해를 간단한 구조물과 가림막을 설치하여 상시적으로 보호할 수 있도록 해, 노지환경에서 과수재배의 안정성을 확보할 수 있다. claims: 수목이 식재된 노지에 수직프레임(10)을 삽입하는 1단계;상기 수직프레임(10) 상단에 가림막을 설치 및 지지하는 가림막 부설모듈(100)을 결합하는 2단계;상기 가림막 부설모듈(100)의 상부에 횡방향으로 결합하는 수평프레임(20)을 결합하는 3단계;상기 1단계 내지 상기 3단계를 다수회 반복하여 상기 노지 상에 상기 수직프레임 및 가림막 부설모듈(100)의 결합체를 복수개가 행과 열을 이루도록 배치형성하는 4단계; 및상기 결합체의 상부에 상기 수평프레임(20)과 직교하는 방향으로 가림막 가이드 와이어(30)를 설치하고, 상기 가림막 가이드 와이어(W)에 끼움 결합되는 가림막(M)을 부설하는 5단계;를 포함하는,수목재배지 상의 가림막 설치공법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

508/1059 Row 508: application_number: 1020190104097, combined_string: invention_title: 3가지 작물 3배 수확용 입체적 스마트 팜 시설 하우스 abstract: 개시되는 3가지 작물 3배 수확용 입체적 스마트 팜 시설 하우스가 수직 기둥 부재와, 외부 비닐 지붕 부재와, 수평 기둥 부재와, 전후 기둥 부재와, 오버 헤드 이동 발판 부재와, 오버 헤드 이동 발판 레일 부재와, 발판 이동 부재와, 2가지 작물 지상 재배 부재를 포함함에 따라, 포도, 키위 등의 줄기 과수, 딸기 및 쌈 채소 3가지의 다양한 작물이 하나의 상기 3가지 작물 3배 수확용 입체적 스마트 팜 시설 하우스에서도 작물 재배의 휴지기가 최소화되면서 함께 재배될 수 있게 되므로, 종래에 비해 같은 면적 상에서도 3가지의 작물의 3배 이상의 소출이 발생될 수 있게 되는 장점이 있다. claims: 설치면에 대해 수직으로 세워지는 수직 기둥 부재;상기 수직 기둥 부재의 상부와 측면을 덮으면서 상기 수직 기둥 부재에 의해 지지되고, 비닐로 이루어지는 외부 비닐 지붕 부재;상기 수직 기둥 부재에 수직으로 연결되고, 상기 설치면에 대해 수평이 되도록 상기 설치면으로부터 소정 높이의 상공 상에 배치되는 수평 기둥 부재;상기 설치면으로부터 소정 높이의 상공 상에 배치되어, 상기 외부 비닐 지붕 부재와 상기 설치면 사이의 공간 중 상기 외부 비닐 지붕 부재에 상대적으로 근접된 상공에서 재배되는 상공 재배 작물의 재배를 위해 작업자가 올라설 수 있는 오버 헤드 이동 발판 부재;상기 오버 헤드 이동 발판 부재의 이동 방향으로 일정 길이로 길게 형성되는 오버 헤드 이동 발판 레일 부재;상기 오버 헤드 이동 발판 레일 부재를 고정시키고, 상기 오버 헤드 이동 발판 부재의 하중을 견디도록 상기 수직 기둥 부재에 부착되는 돌출 부재;상기 오버 헤드 이동 발판 레일 부재를 따라 상기 오버 헤드 이동 발판 부재를 이동시킬 수 있는 발판 이동 부재; 및상기 설치면에 대해 수직으로 세워지고, 상기 수평 기둥 부재의 하측 공간에서 2가지의 지상 재배 작물이 서로 다른 높이로 재배될 수 있도록 하는 2가지 작물 지상 재배 부재;를 포함하는 3가지 작물 3배 수확용 입체적 스마트 팜 시설 하우스., Ltext: 농업, prediction: 농업
509/1059 Row 509: application_number: 1020190097869, combined_string: invention_title: 딸기육묘 재배포트용 흙 공급기 abstract: 본 발명은 딸기육묘 재배포트용 흙 공급기에 관한 것으로, 그 구성은 적어도 하나 이상의 딸기육묘 재배포트의 상부에 적층 배치되는 것으로, 내부에 상기 딸기육묘 재배포트의 각 포트로 공급될 흙이 수용되는 공간이 형성되며, 상부는 개방되는 공급프레임;과, 상기 공급프레임의 하부에 위치되는 상기 딸기육묘 재배포트의 각 포트와 연통되게 형성되어 상기 공급프레임에 수용되는 흙은 상기 포트로 안내하는 것으로, 상기 공급프레임 상에 형성되는 다수의 공급구멍;으로 구성된 것을 특징으로 하는 것으로서, 다수의 딸기육묘 재배포트의 상부에 공급프레임을 적층 배치하고, 그 적층된 공급프레임으로 흙을 투입하여 공급프레임에 형성되는 공급구멍을 통해 다수의 딸기육묘 재배포트의 각 포트로 흙이 간편히 공급 충진되도록 함으로, 작업자는 다수의 딸기육묘 재배포트에 흙을 충진하는 작업에 소요되는 시간 및 인력을 종래의 작업방식에 대비하여 대폭 절감할 수 있어 딸기의 효율적인 재배를 유도할 뿐만 아니라, 공급프레임 내부로 흙이 수용되는 구조로 인해 고가의 흙이 외부로 이탈 유실되는 것을 최소화하여 고가인 흙의 경제적인 사용을 유도할 수 있는 효과가 있다.또한, 공급프레임에 연장 형성되는 보관프레임과 가이드 편을 통해 다른 딸기육묘 재배포트로 공급프레임의 원활한 이동을 유도하여 공급프레임을 통한 딸기육묘 재배포트의 흙 충진 작업이 연속적으로 용이하게 수행되도록 하는 효과가 있다. claims: 적어도 하나 이상의 딸기육묘 재배포트(1)의 상부에 적층 배치되는 것으로, 내부에 상기 딸기육묘 재배포트(1)의 각 포트(1a)로 공급될 흙이 수용되는 공간이 형성되며, 상부는 개방되는 공급프레임(10); 및상기 공급프레임(10)의 하부에 위치되는 상기 딸기육묘 재배포트(2)의 각 포트(1a)와 연통되게 형성되어 상기 공급프레임(10)에 수용되는 흙은 상기 포트(1a)로 안내하는 것으로, 상기 공급프레임 상에 형성되는 다수의 공급구멍(20);을 포함하여 구성되되,상기 공급구멍(20)의 직경(D1)은 상기 포트(1a)의 직경(D2)보다 작게 형성되는 것을 특징으로 하는 딸기육묘 재배포트용 흙 공급기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

510/1059 Row 510: application_number: 1020190087436, combined_string: invention_title: 과수봉지의 투입구 밀폐용 접착테이프 제조장치 및 그 방법 abstract: 본 발명은 나무에서 생산되는 열매인 배, 사과 등 과수 재배에 사용되는 과수봉지의 투입구 밀폐용 접착테이프 제조장치 및 그 방법에 관한 것으로, 더욱 상세하게는 과수봉지의 투입구에 삽입되는 과수 줄기의 꼭지가 자유롭게 움직일 수 있도록 하여 과수의 성장을 촉진시키도록 하고, 과수 줄기의 외측 둘레의 전면 투입부와 후면 투입부를 밀폐시켜 과수 봉지 내부로 빗물 등의 침입을 방지하여 과수의 부패를 방지함과 동시에 신속하고도 수월하게 과수를 씌울 수 있도록 하는 과수봉지의 투입구의 일측 내 측면에 접착시키는 과수봉지의 투입구 밀폐용 접착테이프의 제조장치 및 그 방법에 관한 것이다. claims: 과수봉지(30)의 상부 투입구(33)의 밀폐용 접착테이프(10) 중간에 비 접착부(11)를 형성하고, 상기 상부 투입구 밀폐용 접착테이프(10)의 표면에 전이되어 접착된 양면테이프(21)(22)의 외측면에 박리지(12)를 점착하되, 상기 박리지(12) 양단에 박리지 손잡이(12A)를 형성하는 과수봉지의 투입구 밀폐용 접착테이프 권취기(100)로서, 상기 권취기(100)는 하부 지지 프레임(110) 상부에 고정 설치된 권취용 지지판(120)과; 상기 권취용 지지판(120) 일측 후방에 설치된 회전 드럼 구동부(130)와; 상기 회전 드럼 구동부(130)를 구성하는 구동모터(131)의 축(131')에 연결되어 권취용 지지판(120) 전방으로 돌출시킨 밀폐용 접착테이프 권취용 회전 드럼(140)과; 상기 회전 드럼 구동부(130)의 상단에 설치된 상부 풀리(132)의 축(132')에 연결되고 권취용 지지판(120) 전방으로 돌출시킨 폐 박리지 권취용 회전 드럼(150)과; 권취용 지지판(120)의 전방 타측 상방에 설치된 제1 및 제2 접착테이프(21A)(22A)를 권취 시키는 제1 및 제2 회전 드럼(160)(170); 및 제1 회전 드럼(160) 직 하방에 설치된 과수봉지의 투입구 밀폐용 접착테이프(10)의 박리지(12)를 권취 시키는 박리지 회전 드럼(180);을 포함하여 구성하고, 상기 박리지 회전 드럼(180)에 권취된 과수봉지의 투입구 밀폐용 접착테이프(10)의 박리지(12)를 접착제 전이용 회전 롤러(190) 및 제1 안내 롤러(R1)를 거쳐 밀폐용 접착테이프 권취용 회전 드럼(140)에 권취 시키되, 제1 및 제2 회전 드럼(160)(170)에 각각 권취된 제1 및 제2 접착테이프(21A)(22A)의 양면테이프(21)(22)를 접착제 전이용 회전 롤러(190)의 전단 안내 롤러부(191)와 후단 안내 롤러부(192)에 통과시키면서 제1 및 제2 접착테이프(21A)(22A) 각각의 양면테이프(21)(22) 일단을 상기 과수봉지의 투입구 밀폐용 접착테이프(10)의 박리지(12)의 표면에 전이시키고, 양면테이프(21)(22)가 각각 전이된 폐 박리지(21A-1)(22A-1)를 제2 및 제3 안내 롤러(R2)(R3)를 거쳐 폐 박리지 권취용 회전 드럼(150)에 권취 하도록 구성함을 특징으로 하는 과수봉지의 투입구 밀폐용 접착테이프 제조장치.박리지 회전 드럼(180)에 권취된 박리지(12)의 일단을 접착제 전이용 회전 롤러(190) 및 제1 안내 롤러(R1)를 거쳐 밀폐용 접착테이프 권취용 회전 드럼(140)에 걸어 연결 시키는 제1 단계(S1)와; 제1 및 제2 회전 드럼(160)(170)에 권취된 제1 및 제2 접착테이프(21A)(22A)의 일단을 제4 및 제5 안내 롤러(R4)(R5)를 거쳐 접착제 전이용 회전 롤러(190)의 전단 안내 롤러부(191)와 후단 안내 롤러부(192)에 통과시키면서 제2 및 제3 안내 롤러(R2)(R3)을 거쳐 폐 박리지 권취용 회전 드럼(150)에 걸어 연결 시키는 제2 단계(S2)와; 회전 드럼 구동부(130)에 전원을 공급하여 동작하게 하는 제3 단계(S3)와; 상기 제3 단계(S3)에 의하여 밀폐용 접착테이프 권취용 회전 드럼(140) 및 폐 박리지 권취용 회전 드럼(150)을 회전시키는 제4 단계(S4)와; 접착제 전이용 회전 롤러(190)에 의하여 제1 및 제2 접착테이프(21A)(22A)의 양면테이프(21)(22)를 박리지(12)의 표면에 전이시켜 과수봉지의 투입구 밀폐용 접착테이프(10)를 생성하는 제5 단계(S5)와; 폐 박리지(21A-1)(22A-1) 및 과수봉지의 투입구 밀폐용 접착테이프(10)를 폐 박리지 권취용 회전 드럼(150) 및 밀폐용 접착테이프 권취용 회전 드럼(140)에 각각 권취 시키는 제6 단계(S6);를 통하여 권취된 과수봉지의 투입구 밀폐용 접착테이프(10)를 제조함을 특징으로 하는 과수봉지의 투입구 밀폐용 접착테이프 제조방법., Ltext: 농업, prediction: 임업
511/1059 Row 511: application_number: 1020190086714, combined_string: invention_title: 기름밤나무 및 각종 유실수 재배 기능성 비료 및 토질 제조방법 abstract: 본 발명은 1차로 기름밤나무 등 유실수를 묘목상태에서 또는 임야 등 토지에 옮겨 심을 때 또는 성장기인 1-2년간에 필요한 양분을 제공하며, 2차로는 주택이나 아파트 및 상가 등 실내에서 또는 옥상 등 외부에서 조경용 꽃이나 일반적 채소류 등을 재배할 경우에 필요한 친환경 기능성 조경토 및 그 제조방법에 관한 것으로서, 미세다공을 가진 다공성 물질인 제오라이트, 펄라이트, 화산모래, 피트모스 분말, 천연 무기질 발포입자 등을 포함한 입자 중에서 하나 또는 그 이상을 선택하고(A군);식물의 영양분 종류로서 전분, 젤라틴, 키토산 등의 영양물질 중 하나 또는 그 이상을 선택하여 겔 상태로 형성된 수용액에 혼합 침지 시킨 후(B군);더불어 적어도 1종의 배양된 유산균, 효모균, 고초균 중 1종을 선택하여 발효 배양물을 준비한다(C군).상기 준비한 A. B. C군의 혼합요소 중 A군중 한종류 이상의 분말을 1:1의 중량비로 혼합하고 이중 25-35 중량부와 B군중 한 종류 이상의 추출물과, 물과, C군 중 한 종류를 선택하여 1:6:1의 중량비로 혼합한 혼합액 3 내지 6중량부를 함유하여 혼합액으로 결착시켜 입상형으로 형성하여 조경토를 제조하고 이를 실내. 외부 옥상 조경토 및 토지 개량제로 사용하도록 하여서 식물의 생장을 촉진시키는 효과를 얻는다.[색인어]다공성 물질.입상형.산화칼슘. claims: 혼합물의 조성과정에 있어서 피트모스 분말 등을 3.5:6.5 내지 4:6의 중량비로 혼합하여 70 내지 80 중량부의 혼합물 조성;무기질 발포입자인 펄라이트, 피트모스, 제오라이트 등을 포함하는 다공성 물질의 구성:기능성 조경토 표면에 키토산을 분해하는 분말상의 키토나제를 도포하여 코팅하는 것을 특징으로 하는 친환경 기능성 조경 토 제조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

512/1059 Row 512: application_number: 1020190074440, combined_string: invention_title: 병충해 피해 방지를 위한 과수봉지용 이산화염소 서방형 키트 abstract: 본원은 과실을 재배하는 과정 중 장기간 병해충으로부터 보호하고, 과실의 외관을 아름답게 하기 위하여 살조력이 우수한 이산화염소(Chlorine dioxide)를 서서히 방충하는 과수봉지 관련 기술이다.본원 기술은 살조력이 우수한 이산화염소(Chlorine dioxide)가 과수봉지 내부에 장기간 방출할 수 있도록 과수봉지용 이산화염소 서방형 키트를 제공하되, 용액상의 아염소산나트륨(NaClO2)이 내장되는 키트인 경우 수용액상의 아염소산나트륨(NaClO2)과 고흡수성수지가 포함되고, 유기산(Organic acid) 공급에 의한 pH 7.0 이하의 산성조건에서 이산화염소의 소스(Source)가 하이드로겔 타입으로 만들어져 적용되므로 이산화염소 가스가 서서히 방출되는 서방형 키트로 적용될 수 있다(A타입), 또는 용액상의 아염소산나트륨(NaClO2)을 포함하는 알칼리의 액상규산염(Liquid silicate)에 유기산(Organic acid)을 공급하여 pH 7.0 이하의 산성조건으로 실리카 졸·겔법을 제공하여 이산화염소 방출 소스(Source)가 실리카의 3차원적 망상구조 타입으로 이루어지도록 구성하여 이산화염소 가스가 천천히 방출되는 서방형 키트로 적용될 수 있다(B타입), 또한, 분말상의 아염소산나트륨(NaClO2)으로 구성되는 키트의 경우에는 세라믹 분말을 100중량부로 기준으로 할 때 아아염소산나트륨(Sodium chlorite, NaClO2)은 50 내지 250 중량%로 혼합되도록 구성되어지고, 유기산(Organic acid)은 알칼리의 아염소산나트륨 pH가 7.0 이하로 제공되는 양이 혼합되도록 구성되어지고, 흡습성 물질은 1.5 ~ 4.5 중량%가 혼합되도록 구성되어지고, 추가로 흡습성 물질의 기능 향상을 위해 하이드로겔 고분자가 0.25 내지는 1.0 중량% 혼합되어 이루어지는 이산화염소 소스의 조성물을 이루고 흡습제에 의한 과수봉지 내부의 습기를 흡수하여 흡습상태의 알칼리 아염소산나트륨과 산(Acid)이 산·염기 반응에 의한 pH 7.0 이하의 산성 분위기로 이루어지도록 구성되어 이산화염소 가스가 서서히 방출되는 서방형 키트(C타입) 중에서 하나가 선택되도록 적용될 수 있는 과수봉지를 통하여 본원의 목적을 달성하고자 하는 기술이다. claims: 과수 재배과정 중 병충해로부터 보호를 받기 위해 과수봉지에 있어서,과수봉지 내부에 장기간 이산화염소 가스를 서서히 배출시키기 위한 서방형 키트(Kit)가 내장되어 과수 재배과정 중 병충해로부터 보호받도록 제공되는 것을 특징으로 하는 과수봉지., Ltext: 농업, prediction: 임업
513/1059 Row 513: application_number: 1020210040803, combined_string: invention_title: 바나듐을 이용한 콩나물의 제조방법 abstract: 본 발명은 바나듐을 이용한 콩나물의 제조방법에 관한 것이다.본 발명의 바나듐 콩나물의 제조방법은, 콩나물용 콩을 유기바나듐 희석액에 18~22℃에서 20~24시간동안 침지시켜 발아한 콩을 제조하는 제1단계, 상기 발아한 콩을 수거한 후 남은 상기 유기바나듐 희석액에 항균활성을 갖는 미생물 배양액을 넣고 혼합하여 혼합액을 제조하는 제2단계, 상기 제1단계에서 발아한 콩을 콩나물 재배통 내부에 안치시킨 후, 상기 제2단계의 혼합액을 살수하는 제3단계 및, 상기 살수처리후 배수되는 혼합액으로 3~4시간마다 5~6일동안 재살수하여 10~15mg/kg의 바나듐 성분을 포함하는 바나듐 콩나물을 제조하는 제4단계를 포함하는 것이 특징이다.본 발명에 의해, 다량의 바나듐 성분을 함유함과 동시에 장기보관이 가능한 바나듐 콩나물의 제조방법이 제공된다. claims: 콩나물용 콩을 물4ℓ당 유기바나듐 20~30㎖를 넣고 제조된 유기바나듐 희석액에 18~22℃에서 20~24시간동안 침지시켜 발아한 콩을 제조하는 제1단계;상기 발아한 콩을 수거한 후 남은 상기 유기바나듐 희석액에 항균활성을 갖는 미생물 배양액과 스테비아 발효추출물을 1 : 0.1~0.5 : 0.1~0.5의 중량비로 넣고 혼합하여 혼합액을 제조하는 제2단계;상기 제1단계에서 발아한 콩을 콩나물 재배통 내부에 안치시킨 후, 상기 제2단계의 혼합액을 살수하는 제3단계 및, 상기 살수처리 후 배수되는 혼합액으로 3~4시간마다 5~6일동안 재살수하여 10~15mg/kg의 바나듐 성분을 포함하며, 냉장상태에서 최대 30일까지 장기보관 가능한 바나듐 콩나물을 제조하는 제4단계;를 포함하는, 바나듐 콩나물의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

514/1059 Row 514: application_number: 1020200172543, combined_string: invention_title: 솔잎액 소독을 이용한 콩나물 재배방법 및 상기 방법을 통해 재배된 콩나물 abstract: 본 발명은 솔잎액 소독을 이용한 콩나물 재배방법 및 상기 방법을 통해 재배된 콩나물에 관한 것으로, 보다 구체적으로는, 솔잎 추출물을 포함하는 액상 조성물 및 솔잎 추출물을 물에 희석시켜 포함하는 희석액을 이용하여 콩나물 재배실 및 재배용기를 주기적으로 소독함으로써 콩나물의 생산성을 증가시키고, 생산된 콩나물의 식감을 향상시키며, 콩나물의 재배 과정에서 빈번히 발생하는 짓무름, 부패 등의 문제점을 사전에 방지할 수 있는, 콩나물 재배방법에 관한 것이다. claims: 콩나물 콩을 선별한 후 흐르는 물에 세척하는 단계;상기 세척한 콩나물 콩을 물에 10 분 내지 6 시간 동안 침지하여 불리는 단계;상기 불린 콩나물 콩을 솔잎 추출물을 포함하는 10℃ 내지 25℃의 온도 범위의 액상 조성물에 침지한 뒤 상기 솔잎 추출물을 포함하는 액상 조성물을 반복 분무하여 발아시키는 단계; 및상기 발아한 콩나물 콩을 재배실의 재배용기에 넣고 상기 액상 조성물을 1 시간 내지 4 시간 간격으로 반복 분무하여 3 일 내지 7 일 동안 재배하는 단계; 를 포함하되,상기 액상 조성물은, 상기 액상 조성물 전체 100 중량부를 기준으로, 증류수 50 내지 80 중량부, 솔잎 추출물 1 내지 20 중량부, 오이즙 5 내지 10 중량부, 프락토올리고당 0.01 내지 3 중량부, 및 바나나 농축액 0.1 내지 5 중량부를 포함하며,상기 발아한 콩나물 콩을 재배하는 단계는, 상기 재배하는 중에 상기 재배실의 통풍을 차단한 후 상기 콩나물 콩, 재배용기, 및 재배실에 물과 솔잎 추출물을 1 : 20의 중량비로 혼합하여 제조되는 희석액을 1 일 1 회 간격으로 상기 재배실의 이산화탄소 농도가 1,300 ppm 내지 2,000 ppm이 될 때까지 1 분 내지 60 분 동안 반복 분무하여 소독하는 단계; 및 상기 희석액을 분무한 후 재배실을 환기하는 단계;를 추가 포함하는 것을 특징으로 하는,콩나물 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

515/1059 Row 515: application_number: 1020200091484, combined_string: invention_title: 콩나물 재배 용기 abstract: 본 발명은 콩나물의 재배, 포장 및 출하를 하나의 용기를 이용하여 수행할 수 있도록 구현한 콩나물 재배 용기에 관한 것으로, 콩나물의 원료가 되는 나물콩을 내부 공간에 수용시킨 뒤 재배하기 위한 용기부; 상기 용기부에 수용된 나물콩이 자라 콩나물이 되면 상기 용기부의 내부 공간으로 빛이 들어가는 것을 방지할 수 있도록 빛이 투과되지 않는 암막으로 형성되어 상기 용기부를 덮는 암막 커버부; 및 상기 암막 커버부로 덮인 상기 용기부의 상부 입구를 덮어 상기 용기부를 밀폐시키는 덮개부;를 포함한다. claims: 콩나물의 원료가 되는 나물콩을 내부 공간에 수용시킨 뒤 재배하기 위한 용기부;상기 용기부에 수용된 나물콩이 자라 콩나물이 되면 상기 용기부의 내부 공간으로 빛이 들어가는 것을 방지할 수 있도록 빛이 투과되지 않는 암막으로 형성되어 상기 용기부를 덮는 암막 커버부; 및상기 암막 커버부로 덮인 상기 용기부의 상부 입구를 덮어 상기 용기부를 밀폐시키는 덮개부;를 포함하며,상기 용기부는,나물콩을 수용하기 위한 내부 공간을 형성하며, 상측이 개방된 컵 형태로 형성되는 용기 본체;나물콩의 생육을 위해 상기 용기 본체의 내부 공간으로 투입되는 물이 고이지 아니하고 외부로 배출될 수 있도록 상기 용기 본체의 하부 바닥면을 관통하고 형성되는 다수 개의 물빠짐홀; 및상기 덮개부의 테두리를 따라 하측 방향으로 절곡되어 형성된 걸림턱에 체결될 수 있도록 상기 용기 본체의 상측 입구가 외측 방향으로 둥글게 절곡되어 형성되는 피걸림턱;을 포함하며,콩나물의 출하를 위해 상기 용기부 다수 개를 열을 지어 안착시키기 위한 용기 트레이;를 더 포함하며,상기 용기 트레이는,사각 평판 형태로 형성되는 베이스 플레이트;상기 용기부가 삽입되어 안착될 수 있도록 상기 베이스 플레이트를 상하 방향으로 상기 용기부의 하부 형태에 대응하는 형상으로 관통하고 열을 지어 다수 개가 형성되는 안착홀; 및상기 안착홀에 안착된 상기 용기부의 하부가 거치될 수 있도록 상기 안착홀의 하측 마다 설치되는 다수 개의 거치 프레임;을 포함하며,상기 거치 프레임은,상하 수직 방향으로 연장 형성되어 상기 안착홀을 따라 설치되는 다수 개의 수직 프레임; 및원형의 링 형태로 형성되며, 테두리를 따라 상기 다수 개의 수직 프레임의 각 하부가 설치되어 상기 베이스 플레이트의 하측에서 거치되며, 상기 안착홀에 안착된 상기 용기부의 하부를 지지하는 지지링;을 포함하며,상기 거치 프레임은,상기 지지링의 내측에 연결 설치되며, 상기 지지링의 내측 공간이 상기 용기부의 하측면보다 커 상기 지지링의 내측 공간으로 상기 용기부의 하부가 통과되는 경우 상기 용기부의 하측을 지지하는 보조 지지부;를 더 포함하며,상기 지지링은,신축성 있는 연질의 재질로 형성되며,상기 보조 지지부는,상기 지지링의 내주면을 따라 동일한 간격으로 서로 이격되어 설치되는 다수 개의 밀착 프레임; 및원판 형태로 형성되며, 테두리를 따라 상기 다수 개의 밀착 프레임의 각 일측이 설치되어 지지되는 지지 원판;을 포함하며,상기 다수 개의 밀착 프레임은,각각의 일측이 상측으로 경사지도록 설치되어 상기 지지 원판이 상기 지지링 보다 상측에 위치되도록 지지하고상기 지지 원판은,상기 용기부가 상측에 안착되면, 상기 용기부의 하중에 의해 하강함에 따라 상기 밀착 프레임의 일측이 하측 방향으로 이동하여 상기 지지링의 상측 위치로부터 상기 지지링의 하측 위치로 이동되어 상기 용기부의 하측을 지지하며, 상기 밀착 프레임은,길이 방향으로 연장 형성되어 일측이 상기 지지 원판의 테두리에 설치되고, 다른 일측이 상기 지지링의 내주면에 설치되는 지지 바아;상기 용기부와 대향하는 상기 지지 바아의 상부면을 따라 길이 방향으로 연장 형성되는 안착홈;상기 안착홈의 길이에 대응하는 길이로 연장 형성되어 일측이 상기 안착홈의 일측에 회동 가능하도록 연결 설치되는 회동 바아;상기 회동 바아의 다른 일측 하측과 상기 안착홈의 다른 일측 사이에 설치되어 탄성력을 이용하여 상기 회동 바아의 다른 일측이 상기 안착홈의 다른 일측의 상측으로 노출되도록 지지하는 지지 스프링; 및곡선 형태로 둥글게 절곡되어 형성되어 상기 지지 바아의 다른 일측에 설치되며, 상기 지지 바아의 일측이 하강하여 상기 회동 바아의 상부면과 상기 용기부 사이의 간격이 줄어듦에 따라 상기 용기부에 밀착되어 상기 용기부를 지지하는 밀착 플레이트;를 포함하는, 콩나물 재배 용기., Ltext: 농업, prediction: 임업
516/1059 Row 516: application_number: 1020200085005, combined_string: invention_title: 아스파라긴산 함량이 증진된 기능성 느타리버섯 재배용 배지조성물 abstract: 본 발명은 느타리버섯 병재배용 배지조성물에 관한 것으로서 보다 상세하게는 배지조성물에 콩나물분말을 혼합함으로써 아스파라긴산의 함량이 증진된 기능성 느타리버섯을 생산하는 배지조성물에 관한 것이다. 본 발명에서는 톱밥 100중량부에 대해서,비트펄프 40~60중량부와, 콩나물분말 20~40중량부를 혼합하여 콩나물혼합배지를 형성하는 것을 특징으로 하며, 일반재배 느타리버섯에 비해서 약 100배이상 아스파라긴산 함량이 증진된 기능성 느타리버섯 재배용 배지조성물을 제공한다. claims: 톱밥 100중량부에 대해서,비트펄프 40~60중량부와, 콩나물분말 20~40중량부를 혼합하여 콩나물혼합배지를 형성하되,상기 콩나물분말은, 콩나물폐기물로부터 수거 후 세척되어 오염물질을 제거시키는 단계(S1);80~100℃에서 1~2시간 가열되어 삶아지고, 콩나물 특유의 냄새가 제거되는 단계(S2);50~60℃에서 5~6시간 교반되어 수분량이 8.5~9.5%가 되는 단계(S3);110-121℃에서 80~90분간 고압 살균되는 단계(S4); 효모균을 접종한 후에 50~55℃에서 2~4일간 발효하는 단계(S5);2~10℃ 상태에서 24시간 냉각되는 상태(S6);평균 입자크기가 3~50메쉬가 되도록 분쇄되어 분말형태로 생성되는 단계(S7);환기시설에서 24시간동안 T-C함량 38~50%, T-N함량 6~8%가 되도록 가스 및 암모니아를 배출하는 단계(S8);에 의해서 제조되며, 상기 콩나물혼합배지 100중량부에 대해서 물 10~15중량부 또는 pH산도조절제 0.3~0.5중량부를 더 포함함으로써, 느타리버섯의 종균을 접종하고 병재배하여 재배된 버섯에서 아스파라긴산 3000 ~ 4000mg/kg이 함유된 것을 특징으로 하는 아스파라긴산 함량이 증진된 기능성 느타리버섯 재배용 배지조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

517/1059 Row 517: application_number: 1020200052439, combined_string: invention_title: 수생식물 재배장치 abstract: 본 발명은 수생식물 재배장치에 관한 것이다.보다 구체적으로는, 콩나물 등 수중에 뿌리를 내려 생육되는 수생식물을 재배하기 위한 재배장치에 관한 것으로서, 일측에 수통을 거꾸로 세워 결합할 수 있는 영역과 상기 영역으로 유입된 물을 공급받아 수생식물을 재배하는 영역을 포함하여 구성된, 수생식물 재배장치에 관한 것이다. claims: 상면 일측에 하방으로 오목하게 형성된 수통삽입부(11)와,상면 다른 일측에 하방으로 오목하게 형성된 재배부(12)를 포함하는 재배장치(10)에 있어서,상기 수통삽입부(11)와 재배부(12)는 상호 연통된 연통영역을 가지고,상기 수통삽입부(11), 재배부(12) 및 연통영역은 바닥에 바닥판(10a)이 구비되며,상기 수통삽입부(11)는 하면 일측에 돌출되도록 형성된 수통고정구(13)가 구비되어, 수통을 거꾸로 세워 결합시켜 고정할 수 있도록 하되,(a) 상기 재배부(12)는,재배부(12)의 바닥판(10a)의 상면에서부터 통 형식으로 구성된 재배통(14)이 구비되되, 상기 재배통(14)의 외면과 재배부(12)의 내면은 일정 간격 이격되도록 형성되어 이격공간을 포함하고,(b) 상기 재배통(14)은,재배부(12)의 바닥판(10a)의 상면에서부터 통 형식으로 구성되고 상면이 개방된 통(14a)과, 상기 통(14a)의 상면을 마감하는 커버(14b)를 포함하여 구성되되,상기 통(14a)의 하단 일측에는 통(14a)의 원주방향을 따라 일정간격 형성되는 복수 개의 홀(14a')이 형성되며,상기 통(14a)의 내면에는 통(14a)을 가로막는 재배판이 구비되되, 상기 재배판은, 다수의 천공을 포함하고, 상기 홀(14a')보다 높은 위치에 구비되며,(c) 상기 수통고정구(13)는,수통삽입부(11)의 바닥판(10a)의 상면에 구비된 베이스(13a)와, 상기 베이스(13a)의 상방으로 돌출된 돌기(13b)와, 상기 베이스(13a)의 일측에서부터 돌기(13b)의 일측까지 연결된 제1 턱(13c) 및 제2 턱(13d)을 포함하되,상기 제1 턱(13c) 및 제2 턱(13d)은,각각 돌기(13b)의 원주 방향을 따라 일정 간격으로 복수 개 형성되고,상호 다른 높이를 가지도록 구성되되, 턱진 영역의 폭이 제1 턱(13c) 및 제2 턱(13d) 간에 다르도록 구성하며, (d) 수통삽입부(11)와 재배부(12)를 연통하는 연통영역에는 수통삽입부(11)와 재배부(12)의 연통된 구조를 차단하고, 재배부(12)에 고인 물을 재배장치(10) 외측으로 배출하는 기능을 수행하는 배출단속장치가 구성되되,상기 배출단속장치는,수통삽입부(11)와 재배부(12)를 연통하는 연통영역의 바닥판(10a)에 재배장치(10)의 하부 외측으로 관통된 홀을 포함하고,상기 홀에는 홀의 크기에 대응되는 크기를 가지는 누름부가 홀에 삽입되며, 상기 홀의 내면에는 2개가 1쌍으로 마주하는 가이드홈이 형성되고,상기 누름부의 가이드홈에 대응되는 일면에는 돌기가 형성되며,상기 돌기는 가이드홈보다 짧은 길이로 형성되어, 상기 돌기가 가이드홈에 삽입된 후, 가이드홈을 따라 돌기가 가이드될 수 있도록 하고,상기 홀의 상측은 뚜껑에 의해 폐쇄되되, 상기 뚜껑은 뚜껑의 측벽이 홀의 내부에 삽입되며, '┌┐'의 형상을 가지고, 측벽이 형성되지 않은 방향으로 경첩을 통해 뚜껑과 바닥판(10a)을 연결하여, 상기 뚜껑이 수직방향으로 개방될 수 있도록 함으로써,상기 누름부가 상승하는 경우, 뚜껑의 하면을 누르면서 상승하여, 뚜껑이 개방될 수 있도록 하고, 상기 누름부는 상방으로 이동되지 않았을 때, 뚜껑을 폐쇄할 수 있는 정도의 길이를 가지도록 하며, 별도의 구조물을 대거나, 손으로 누르는 경우, 누름부가 상승하면서 뚜껑을 개방시키게 되는 것을 특징으로 하는, 수생식물 재배장치., Ltext: 농업, prediction: 임업
518/1059 Row 518: application_number: 1020200050316, combined_string: invention_title: 무전력 자동 콩나물 재배기 abstract: 본 발명은 무전력 자동 콩나물 재배기에 관한 것으로, 최상부에 배치되는 제1용기 및 제1용기의 하부에 배치되는 제2용기를 포함하는 복수의 용기를 포함하며, 제1용기 및 제2용기 각각은 상부가 개방되고 하부는 밀폐된 용기로서, 각 용기의 하부에는 관통공이 형성되며, 제1용기 및 제2용기 각각의 내부에는 공통적으로 배수관 및 배수캡이 설치되고, 배수관은 상부와 하부가 각각 개방된 수직관으로서, 배수관의 하부 외주면에는 나사산이 형성되며, 배수관의 하부가 용기의 관통공을 관통한 후 너트로 고정되고, 배수캡은 용기의 하부에 배치되는 수평부재 및 수평부재의 상부와 결합하는 수직부재를 포함하며, 수평부재는 상부가 밀폐되고 하부가 개방되며, 수직부재는 상부가 밀폐되고 하부가 개방된 수직관으로서, 배수관보다 큰 직경을 가져서 배수관을 내부에 수용하며, 제1용기의 수위가 배수캡의 수직부재를 초과하면, 물은 배수캡의 수평부재 및 수직부재를 거쳐 배수관의 상부로 유입된 후, 배수관의 하부를 통해 제1용기 외부로 배출된 다음, 제2용기로 유입되는 콩나물 재배기를 제공한다. claims: 최상부에 배치되는 제1용기 및 제1용기의 하부에 배치되는 제2용기를 포함하는 복수의 용기를 포함하며,제1용기 및 제2용기 각각은 상부가 개방되고 하부는 밀폐된 용기로서, 각 용기의 하부에는 관통공이 형성되며,제1용기 및 제2용기 각각의 내부에는 공통적으로 배수관 및 배수캡이 설치되고,배수관은 상부와 하부가 각각 개방된 수직관으로서, 배수관의 하부 외주면에는 나사산이 형성되며, 배수관의 하부가 용기의 관통공을 관통한 후 너트로 고정되고,배수캡은 용기의 하부에 배치되는 수평부재 및 수평부재의 상부와 결합하는 수직부재를 포함하며,수평부재는 상부가 밀폐되고 하부가 개방되며,수직부재는 상부가 밀폐되고 하부가 개방된 수직관으로서, 배수관보다 큰 직경을 가져서 배수관을 내부에 수용하며,제1용기의 수위가 배수캡의 수직부재 상단 또는 배수관 상단을 초과하면, 수직부재의 수위가 배수관 상단을 초과하면서 물이 배수관 쪽으로 흘러 넘쳐 배수관의 상부로 유입된 후, 배수관의 하부를 통해 제1용기 외부로 배출된 다음, 제2용기로 유입되는 콩나물 재배기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

519/1059 Row 519: application_number: 1020200022063, combined_string: invention_title: 재배용수 절감을 위한 무농약 친환경 콩나물 재배방법 abstract: 본 발명은 재배용수 절감을 위한 무농약 친환경 콩나물 재배방법에 관한 것으로, 더욱 상세하게는 재배용수 절감을 위한 오존수를 활용한 무농약 친환경 콩나물 재배방법에 있어서, 갈근 및 섬쑥부쟁이를 혼합한 식물 원료를 발효시켜 제조한 재배용수로 콩나물을 재배함으로써 콩나물의 비린내와 저장성을 현저히 개선할 수 있는 재배용수 절감을 위한 무농약 친환경 콩나물 재배방법에 관한 것이다. claims: 콩을 물에 침지시켜 24시간 동안 불린 다음, 상기 불린 콩을 건져내어 4 ~ 6시간 동안 방치하여 발아시키는 단계(S10);갈근 및 섬쑥부쟁이를 동일 비율로 혼합한 후 열수로 추출한 열수 추출액을 제조하는 단계(S20);미생물 배양 배지를 멸균하는 단계(S30);상기 단계에서 얻은 배지를 냉각 후 류코노스톡 메센테로이데스(Leuconostoc mesenteroides) 및 엔테로코커스 패시움(Enterococcus faecium)으로 이루어지는 미생물 복합균을 접종 후 진탕 배양하여 미생물 복합균 배양액을 제조하는 단계(S40);상기 열수 추출액에 효모추출물(yeast extract) 및 포도당을 첨가하여 멸균 후 상기 미생물 복합균 배양액을 첨가 후 진탕배양하여 미생물 복합균 발효액을 제조하는 단계(S50);상기 미생물 복합균 발효액을 물로 희석하여 재배용수를 제조하는 단계(S60);상기 재배용수를 저장탱크에 저장하고, 오존 폭기에 의해 상기 재배용수를 살균 및 정화처리하는 단계(S70);용존 오존이 소량 잔류되어 있는 상태의 상기 재배용수를 노즐을 이용하여 발아된 콩에 살수하는 단계(S80);살수된 상기 재배용수를 물받이를 통하여 집수하고 침전탱크로 회수하는 단계(S90);상기 침전탱크로 회수된 재배용수를 순환펌프에 의해 상기 저장탱크로 이동시키는 단계(S100);상기 저장탱크로 이동된 재배용수를 오존으로 살균하는 단계(S110); 및콩나물의 재배가 완료될 때까지 상기 재배용수를 계속해서 순환시키고 재배를 완료한 후의 재배용수를 용존 오존으로 정화시켜 외부로 배출시키는 단계(S120);를 포함하는 것을 특징으로 하는 재배용수 절감을 위한 무농약 친환경 콩나물 재배방법., Ltext: 농업, prediction: 농업
520/1059 Row 520: application_number: 1020200009607, combined_string: invention_title: 콩나물을 생산하는 장치 abstract: 본원 발명은 합성수지, 방습 내수성 재질로서 발아가 되는 선별된 두류(콩, 녹두 등; 260)가 넣어진 봉투 형상의 재배봉투(200)를 이용하는 콩나물을 생산하는 장치로서, 상기 재배봉투(200)의 상부면은 상부에서 살수되는 배양수가 상기 재배봉투(200)의 내부로 입수(入水)될 수 있도록 천공(穿孔)된 평탄면을 구비하며, 상기 재배봉투(200)의 하부 일부면에는 상부에서 입수된 배양수를 배출할 수 있는 배출구가 형성된 콩나물을 생산하는 장치에 관한 것이다. claims: 합성수지, 방습 내수성 재질로서 발아가 되는 선별된 두류(콩, 녹두 등; 260)가 넣어진 봉투 형상의 재배봉투(200)를 이용하는 콩나물을 생산하는 장치로서,상기 재배봉투(200)의 상부면은 상부에서 살수되는 배양수가 상기 재배봉투(200)의 내부로 입수(入水)될 수 있도록 천공(穿孔)된 평탄면을 구비하며,상기 재배봉투(200)의 하부 일부면에는 상부에서 입수된 배양수를 배출할 수 있는 배출구가 형성된 것을 특징으로 하는 콩나물을 생산하는 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

521/1059 Row 521: application_number: 1020200005871, combined_string: invention_title: 땅콩나물 재배방법 abstract: 본 발명은 땅콩나물 재배방법에 관한 것으로, 보다 상세하게는 수소수와 액상 황, 이산화염소수를 설정량 포함하는 설정수를 땅콩나물의 재배 시 설정에 따라 분무함으로써 성장과정 중 곰팡이 발생을 억제하고 땅콩나물의 생산성 향상과 면역력을 증대시킬 수 있도록 이루어진 땅콩나물 재배방법에 관한 것이다. 이를 위해, 땅콩 선별단계, 재배판 치상단계, 음용수 살수과정과 설정수 안개분무과정을 갖는 새싹 재배단계, 땅콩나물 수확단계를 포함하여 이루어진다. claims: 땅콩을 발아시켜 성장시킨 땅콩나물을 재배하는 방법에 있어서, 발아시킬 땅콩을 선별하는 땅콩 선별단계(S1)와, 선별한 땅콩을 배수가 잘되도록 다수개의 통공(31)을 가진 재배판(30)에 치상하는 재배판 치상단계(S2)와, 상기 재배판(30)에 설정 환경의 암실에서 음용수를 설정 시간 간격으로 살수하는 음용수 살수과정(S31)과, 상기 음용수 살수과정(S31)에 이어서 곰팡이 발생을 억제하도록 수소수와 액상 황과 이산화염소수를 설정의 비율로 포함한 설정수(A)를 설정 시간 간격으로 나노분사기(20)를 이용해 분무하는 설정수 안개분무과정(S32)을 포함하는 새싹 재배단계(S3)와; 상기 새싹 재배단계(S3)를 거치면서 설정 크기로 성장한 땅콩나물(10)을 수확하는 땅콩나물 수확단계(S4);를 포함하여 이루어진 것을 특징으로 하는 땅콩나물 재배방법., Ltext: 농업, prediction: 농업
522/1059 Row 522: application_number: 1020190171580, combined_string: invention_title: 이산화염소를 이용한 유통기한이 연장된 콩나물의 재배 방법 abstract: 본 발명의 이산화염소를 이용한 유통기한이 연장된 콩나물의 재배 방법은, 콩나물의 배양 초기부터 미생물의 증식을 억제하는 것을 확인할 수 있었으며, 재배된 콩나물의 조직감 및 색감을 저해시키지 않는 효과를 확인하였다. 또한 수확된 콩나물은 저장 7일까지, 기존의 방법으로 재배된 콩나물보다 10배 가량 낮은 표면 미생물이 확인되어, 기존 콩나물 대비 약 7 내지 10일 이상의 저장성을 증대시켜 관련 산업에 유용하게 이용될 수 있다. claims: 1) 콩을 10 내지 18시간 동안 수화하는 단계;2) 상기 수화된 콩을 16 내지 19℃의 조건으로 발아시키는 단계;3) 상기 발아된 콩에 1 내지 3시간 동안 이산화염소를 주입하는 단계;4) 상기 이산화염소가 주입된 콩에 30분 내지 2시간 동안 이산화염소를 비주입 하는 단계; 및 5) 상기 3) 단계 및 4) 단계를 5 내지 7일 동안 반복하는 단계;를 포함하는, 콩나물의 재배 방법.1) 콩을 10 내지 18시간 동안 수화하는 단계;2) 상기 수화된 콩을 16 내지 19℃의 조건으로 발아시키는 단계;3) 상기 발아된 콩에 1 내지 3시간 동안 이산화염소를 주입하는 단계;4) 상기 이산화염소가 주입된 콩에 30분 내지 2시간 동안 이산화염소를 비주입 하는 단계; 및5) 상기 3) 단계 및 4) 단계를 5 내지 7일 동안 반복하는 단계;를 포함하는, 콩나물의 미생물 억제 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

523/1059 Row 523: application_number: 1020190146323, combined_string: invention_title: 프로폴리스 콩나물 제조 방법 abstract: 본 발명은 기능성 콩나물 제조 방법에 관한 것으로서, 재배 완료된 콩나물을 채반에 투입하는 침지준비단계(S10); 콩나물이 담긴 채반을 기능성용액이 담긴 제1저수조에 소정 시간 투입하는 제1침지단계(S20); 제1저수조에서 배출된 콩나물을 저온에서 소정 시간 냉장 건조하는 제1건조단계(S30); 건조된 콩나물이 담긴 채반을 염수가 담긴 제2저수조에 넣고 빼기를 반복하는 제2침지단계(S40); 제2저수조에서 배출된 콩나물을 저온에서 소정 시간 냉장 건조하는 제2건조단계(S50); 를 포함한다.본 발명에 따르면, 재배 완료된 콩나물에 기능성 성분을 효과적으로 흡수시켜 다양한 기능성을 가진 콩나물의 신속하고 효율적인 제조가 가능케 되는 효과가 있다. claims: 재배 완료된 콩나물을 채반에 투입하는 침지준비단계(S10);상기 콩나물이 담긴 채반을 기능성용액이 담긴 제1저수조에 소정 시간 투입하는 제1침지단계(S20);상기 제1저수조에서 배출된 콩나물을 저온에서 소정 시간 냉장 건조하는 제1건조단계(S30);상기 건조된 콩나물이 담긴 채반을 염수가 담긴 제2저수조에 넣고 빼기를 반복하는 제2침지단계(S40);상기 제2저수조에서 배출된 콩나물을 저온에서 소정 시간 냉장 건조하는 제2건조단계(S50); 를 포함하는 기능성 콩나물 제조 방법., Ltext: 농업, prediction: 임업
524/1059 Row 524: application_number: 1020190142050, combined_string: invention_title: 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법 abstract: 본 발명은 (a) 볏짚, 어성초 및 익모초를 태운 재에 황토와 분쇄 볏짚을 혼합한 다음과 물을 넣고 반죽을 한 후에 건조한 후 분쇄하여 볏짚 재 황토 볼을 제조하는 단계; (b) 콩을 불리는 단계; (c) 바닥면에 다수의 통공이 형성되어 있는 콩나물 재배를 위한 옹기 시루에 상기 볏짚 재 황토 볼을 깔고 그 위에 상기 불린 콩을 넣고 다시 콩 위에 볏짚 재 항토 볼로 덮어 콩나물 재배를 준비하는 단계; 및 (d) 재배수을 살수하여 콩나물을 재배하는 단계를 포함하는 것을 특징으로 하는 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법을 제공한다. 상술한 바와 같이 본 발명의 콩나물의 재배 방법은 각종 유효성분을 콩나물을 재배하는 과정에서 지속적으로 콩에 침투시킴으로써 유효성분들이 콩나물에 흡수되어 인체에 유익한 여러 가지 영양을 함유한 영양식 콩나물을 재배할 수 있다. 또한, 발아율을 촉진시킴으로써 미 발아된 썩은 콩으로 인한 비린내, 부패취를 방지할 수 있을 뿐만 아니라, 농약이나 방부제의 사용없이 콩나물 재배시 발생될 수 있는 비린내, 부패취, 썩음병, 검은 반점, 붉은 반점, 갈반 현상, 줄기의 무름병 및 줄무늬 현상 등을 개선하여 질적으로 우수한 콩나물을 재배할 수 있는 효과가 있다. claims: (a) 볏짚, 어성초 및 익모초를 태운 재에 황토와 분쇄 볏짚을 혼합한 다음과 물을 넣고 반죽을 한 후에 건조한 후 분쇄하여 볏짚 재 황토 볼을 제조하는 단계;(b) 콩을 불리는 단계;(c) 바닥면에 다수의 통공이 형성되어 있는 콩나물 재배를 위한 옹기 시루에 상기 볏짚 재 황토 볼을 깔고 그 위에 상기 불린 콩을 넣고 다시 콩 위에 볏짚 재 항토 볼로 덮어 콩나물 재배를 준비하는 단계; 및(d) 재배수을 살수하여 콩나물을 재배하는 단계를 포함하는 것을 특징으로 하는 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

525/1059 Row 525: application_number: 1020190142059, combined_string: invention_title: 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법 abstract: 본 발명은 (a) 볏짚, 소라 껍질 및 우뭇가사리를 태운 재에 황토와 분쇄 볏짚을 혼합한 다음과 물을 넣고 반죽을 한 후에 건조한 후 분쇄하여 볏짚 재 황토 볼을 제조하는 단계; (b) 콩을 불리는 단계; (c) 바닥면에 다수의 통공이 형성되어 있는 콩나물 재배를 위한 옹기 시루에 상기 볏짚 재 황토 볼을 깔고 그 위에 상기 불린 콩을 넣고 다시 콩 위에 볏짚 재 항토 볼로 덮어 콩나물 재배를 준비하는 단계; 및 (d) 재배수을 살수하여 콩나물을 재배하는 단계를 포함하는 것을 특징으로 하는 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법을 제공한다. 상술한 바와 같이 본 발명의 콩나물의 재배 방법은 각종 유효성분을 콩나물을 재배하는 과정에서 지속적으로 콩에 침투시킴으로써 유효성분들이 콩나물에 흡수되어 인체에 유익한 여러 가지 영양을 함유한 영양식 콩나물을 재배할 수 있다. 또한, 발아율을 촉진시킴으로써 미 발아된 썩은 콩으로 인한 비린내, 부패취를 방지할 수 있을 뿐만 아니라, 농약이나 방부제의 사용없이 콩나물 재배시 발생될 수 있는 비린내, 부패취, 썩음병, 검은 반점, 붉은 반점, 갈반 현상, 줄기의 무름병 및 줄무늬 현상 등을 개선하여 질적으로 우수한 콩나물을 재배할 수 있는 효과가 있다. claims: (a) 볏짚, 소라 껍질 및 우뭇가사리를 태운 재에 황토와 분쇄 볏짚을 혼합한 다음과 물을 넣고 반죽을 한 후에 건조한 후 분쇄하여 볏짚 재 황토 볼을 제조하는 단계;(b) 콩을 불리는 단계;(c) 바닥면에 다수의 통공이 형성되어 있는 콩나물 재배를 위한 옹기 시루에 상기 볏짚 재 황토 볼을 깔고 그 위에 상기 불린 콩을 넣고 다시 콩 위에 볏짚 재 항토 볼로 덮어 콩나물 재배를 준비하는 단계; 및(d) 재배수을 살수하여 콩나물을 재배하는 단계를 포함하는 것을 특징으로 하는 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법., Ltext: 농업, prediction: 농업
526/1059 Row 526: application_number: 1020190122497, combined_string: invention_title: 토양에서의 콩나물 재배 방법. abstract: 본 발명은 토양에서 콩나물을 재배하는 방법에 관한 것으로, 상토 조성물을 채워 토양층을 형성한 트레이를 준비하는 단계, 물에 불린 콩을 상기 트레이에 살포하는 단계, 상기 트레이를 25 내지 30℃의 흑암 조건에 두고 2일 1회 상수하는 단계를 포함하며, 상기 상토 조성물은 축분, 대두박, 톱밥, 왕겨, 부엽토 및 황토로 이루어지는 것을 특징으로 한다. claims: 상토 조성물을 채워 토양층을 형성한 트레이를 준비하는 단계;콩을 상기 트레이에 살포하는 단계;상기 트레이를 25 내지 30℃의 흑암 조건에 두고 2일 1회 상수하는 단계;를 포함하며,상기 상토 조성물은,돈분 100 중량부에 대하여, 대두박 60 중량부, 톱밥 5 중량부, 왕겨 5 중량부, 부엽토 150 중량부, 질석 250 중량부 및 황토 60 중량부를 혼합하여 혼합물을 제조하는 단계;상기 혼합물을 30 내지 40℃에서 4주 동안 근권미생물인 슈도모나스 프로테겐스(Pseudomonas protegens)를 이용하여 발효함으로써 발효물을 제조하는 단계;로 제조되며,상기 돈분은 28±2℃의 건조로에서 7일 동안 건조한 후 이를 분쇄 및 살균하여 얻어진 돈분 입자이며,상기 부엽토는 낙엽 및 목분을 1:1 내지 1:0.1의 중량비로 혼합한 후 30℃에서 1개월 간 썩혀 제조된 부엽토이며,상기 발효 전 또는 발효 후에 상기 상토 조성물을 100 내지 300℃로 가열하면서 혼련하여 상기 상토 조성물 내에 분포하는 유해 세균을 제거하며,상기 콩을 상기 트레이에 살포하는 단계는 상기 콩을 토양층 표면에 살포한 후 2 내지 3㎝의 두께로 상기 상토 조성물을 도포하는 것을 특징으로 하는 콩나물 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

527/1059 Row 527: application_number: 1020190120245, combined_string: invention_title: 구기자를 이용한 고품질 콩나물의 재배방법. abstract: 본 발명은 구기자를 이용한 고품질 콩나물의 재배방법에 관한 것으로 (a) 구기자를 수분함유율 15% 이내로 건조하는 단계; (b) 상기(a)의 구기자를 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 식용수1L당 상기(f)단계의 구기자혼합물을 10g~200g을 혼합하여 80~100℃온도에서 1시간~3시간동안 가열하여 추출하여 여과하는 단계; (h) 상기(g)단계의 구기자추출물에 콩나물재배용 콩을 투입하여 5시간~10시간동안 침지하는 단계; (i) 상기(g)단계의 구기자추출물 : 콩나물재배용수를 1~20 : 80~99를 혼합하여 콩나물재배수를 제조하는 단계; (j)상기(h)단계의 침지완료된 콩을 콩나물재배기에 투입하는 단계; (k) 상기(j)단계의 콩나물재배기에 상기(i)단계의 콩나물재배수를 공급하여 콩나물을 재배하는 단계; (l) 상기(k)단계의 재배가 완료된 콩나물을 포장하여 제품화하는 단계를 포함하여 이루어진다. claims: (a) 구기자를 수분함유율 15% 이내로 건조하는 단계; (b) 상기(a)의 구기자를 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 식용수1L당 상기(f)단계의 구기자혼합물을 10g~200g을 혼합하여 80~100℃온도에서 1시간~3시간동안 가열하여 추출하여 여과하는 단계; (h) 상기(g)단계의 구기자추출물에 콩나물재배용 콩을 투입하여 5시간~10시간동안 침지하는 단계; (i) 상기(g)단계의 구기자추출물 : 콩나물재배용수를 1~20 : 80~99를 혼합하여 콩나물재배수를 제조하는 단계; (j)상기(h)단계의 침지완료된 콩을 콩나물재배기에 투입하는 단계; (k) 상기(j)단계의 콩나물재배기에 상기(i)단계의 콩나물재배수를 공급하여 콩나물을 재배하는 단계; (l) 상기(k)단계의 재배가 완료된 콩나물을 포장하여 제품화하는 단계를 포함하는 것을 특징으로 하는 구기자를 이용한 고품질 콩나물의 재배방법.제1항의 재배방법에 의하여 생산된 콩나물., Ltext: 농업, prediction: 임업
528/1059 Row 528: application_number: 1020190104695, combined_string: invention_title: 긴 뿌리 초록 콩나물 재배방법 abstract: 본 발명에 따른 긴뿌리 콩나물 재배방법은 콩나물 재배용 콩을 물에 담가 일정시간 동안 불리는 불림 단계; 상기 불린 콩을 바닥면에 콩은 통과하지 않고 콩나물의 뿌리가 통과하여 자랄 수 있는 크기를 갖는 다수의 통공이 형성되어 있는 재배용기에 두 층 이하로 담는 적층 단계; 상기 콩이 적층된 재배용기를 재배실의 틀에 적층하고 틀 상부에서 3~4일 동안 일정시간마다 물을 살수하여 상기 재배용기의 통공을 통하여 뿌리가 길게 자라도록 긴뿌리 콩나물로 기르는 살수재배 단계; 상기 각 살수재배된 재배용기를 바닥면의 통공을 통하여 자란 뿌리가 물에 잠기도록 수조에 적재하여 하여 2~3일간 광합성에 필요한 빛을 받을 수 있는 조건하에서 수경 재배하여 초록 콩나물로 재배하는 수경재배 단계; 및 상기 수경재배한 긴뿌리 초록 콩나물을 수확하여 세척한 후 포장하는 포장 단계;를 포함하는 것을 특징으로 하는 긴뿌리 초록 콩나물 재배방법을 개시한다. claims: 콩나물 재배용 콩을 물에 담가 일정시간 동안 불리는 불림 단계;상기 불린 콩을 바닥면에 콩은 통과하지 않고 콩나물의 뿌리가 통과하여 자랄 수 있는 크기를 갖는 다수의 통공이 형성되어 있는 재배용기(10)에 두 층 이하로 담는 적층 단계;상기 콩이 적층된 재배용기를 재배실의 틀(20)에 적층하고 틀 상부에서 3~4일 동안 일정시간마다 물을 살수하여 상기 재배용기의 통공을 통하여 뿌리가 길게 자라도록 긴뿌리 콩나물로 기르는 살수재배 단계;상기 각 살수재배된 재배용기를 바닥면의 통공을 통하여 자란 뿌리가 물에 잠기도록 수조(40)에 적재하여 하여 2~3일간 광합성에 필요한 빛을 받을 수 있는 조건하에서 수경 재배하여 초록 콩나물로 재배하는 수경재배 단계; 및 상기 수경재배한 긴뿌리 초록 콩나물을 수확하여 세척한 후 포장하는 포장 단계;를 포함하는 것을 특징으로 하는 긴뿌리 초록 콩나물의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

529/1059 Row 529: application_number: 1020190080029, combined_string: invention_title: 세척 효과가 향상된 콩나물 재배 방법 abstract: 본 발명은 콩나물 재배 방법에 관한 것으로, 특히 세척 효과가 향상된 콩나물 재배 방법에 관한 것이다.이러한 본 발명은 콩을 물에 제1시간동안 불리는 1차 불림 단계, 그리고 첨가물을 투입하여 상기 콩을 물에 상기 제1시간보다 긴 제2시간동안 불리는 2차 불림 단계, 그리고 상기 콩을 재배실에서 재배하여 콩나물을 생성하는 재배 단계, 그리고 상기 콩나물을 투입부에 적재하는 단계, 상기 콩나물이 상기 투입부의 후단에 구비된 제1세척부로 이동되어 와류에 의해 세척되면서 껍질이 분리되는 단계 및 상기 콩나물이 상기 제1세척부의 후단에 구비된 제2세척부로 이동되어 와류에 의해 세척되면서 잔존 껍질이 분리되는 단계를 포함하는 세척 단계, 그리고 상기 콩나물을 소정 시간 동안 숙성시키는 숙성 단계, 그리고 상기 콩나물을 포장하는 포장 단계를 포함한다. claims: 콩을 물에 제1시간동안 불리는 1차 불림 단계(S1); 첨가물을 투입하여 상기 콩을 물에 상기 제1시간보다 긴 제2시간동안 불리는 2차 불림 단계(S2); 상기 콩을 재배실에서 재배하여 콩나물을 생성하는 재배 단계(S3); 상기 콩나물을 투입부에 적재하는 단계, 상기 콩나물이 상기 투입부의 후단에 구비된 제1세척부로 이동되어 와류에 의해 세척되면서 껍질이 분리되는 단계 및 상기 콩나물이 상기 제1세척부의 후단에 구비된 제2세척부로 이동되어 와류에 의해 세척되면서 잔존 껍질이 분리되는 단계를 포함하는 세척 단계(S4); 상기 콩나물을 소정 시간 동안 숙성시키는 숙성 단계(S5); 및 상기 콩나물을 포장하는 포장 단계(S6);를 포함하는 콩나물 재배 방법., Ltext: 농업, prediction: 농업
530/1059 Row 530: application_number: 1020190080028, combined_string: invention_title: 포장 작업이 개선된 콩나물 재배 방법 abstract: 본 발명은 콩나물을 재배하는 방법에 관한 것으로, 특히 포장 작업이 개선된 콩나물 재배 방법에 관한 것이다.이러한 본 발명은 콩을 물에 제1시간동안 불리는 1차 불림 단계, 그리고 첨가물을 투입하여 상기 콩을 물에 상기 제1시간보다 긴 제2시간동안 불리는 2차 불림 단계, 그리고 상기 콩을 재배실에서 재배하여 콩나물을 생성하는 재배 단계, 그리고 상기 콩나물을 세척부에 투입하고 세척과 동시에 껍질을 분리하는 세척 단계, 그리고 상기 콩나물을 소정 시간 동안 숙성시키는 숙성 단계(S5), 그리고 상기 콩나물을 공급부에 적재하는 단계, 상기 콩나물이 상향 경사를 갖는 이송부를 따라 이송되는 단계, 상기 이송부의 단부에서 상기 콩나물이 낙하하여 계량부에 적재되는 단계, 상기 계량부에 적재된 상기 콩나물의 하중이 기 설정된 임계치에 도달하면 상기 계량부의 하부 배출구가 개방되어 포장부로 낙하되는 단계를 포함하는 포장 단계를 포함한다. claims: 콩을 물에 제1시간동안 불리는 1차 불림 단계(S1); 첨가물을 투입하여 상기 콩을 물에 상기 제1시간보다 긴 제2시간동안 불리는 2차 불림 단계(S2); 상기 콩을 재배실에서 재배하여 콩나물을 생성하는 재배 단계(S3); 상기 콩나물을 세척부에 투입하고 세척과 동시에 껍질을 분리하는 세척 단계(S4); 상기 콩나물을 소정 시간 동안 숙성시키는 숙성 단계(S5); 및 상기 콩나물을 공급부에 적재하는 단계, 상기 콩나물이 상향 경사를 갖는 이송부를 따라 이송되는 단계, 상기 이송부의 단부에서 상기 콩나물이 낙하하여 계량부에 적재되는 단계, 상기 계량부에 적재된 상기 콩나물의 하중이 기 설정된 임계치에 도달하면 상기 계량부의 하부 배출구가 개방되어 포장부로 낙하되는 단계를 포함하는 포장 단계(S6);를 포함하고, 상기 포장부는 상기 계량부에서 낙하된 콩나물이 초기 진입되는 호퍼 및 상기 호퍼 하부에 구비되고 공급된 원통 형태의 포장지의 하단을 밀봉하고 개구된 상부를 상기 호퍼의 하단에 배치하는 포장기를 포함하고, 상기 호퍼는 외면에 구비된 보호막을 포함하되, 상기 보호막은 상기 호퍼의 외면에 접하는 침투층, 상기 침투층의 상부에 구비된 발열층 및 상기 발열층의 상부에 구비된 보호층을 포함하고, 상기 침투층은 폴리에틸렌 100 중량부 대비, 폴리비닐 아세테이트계 저수축제 20 중량부 및 수소첨가 로젠이스테르 수지와 폴리브텐을 포함하는 점착제 50 중량부를 포함하고, 상기 발열층은 이산화루테늄 100 중량부 대비, 은 200 중량부 및 이산화티타늄과 이규화몰리브덴을 포함하는 기능성 결착제 200 중량부를 포함하고, 상기 보호층은 부틸 합성고무 100 중량부 대비, 탄산칼슘과 벤토나이트를 포함하는 충진제 300 중량부, 나프텐 오일 100중량부 및 바륨알루미네이트와 지르코니아를 포함하는 내열제 50 중량부를 포함하는 것을 특징으로 하는 콩나물 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

531/1059 Row 531: application_number: 1020190050661, combined_string: invention_title: 콩나물을 이용한 숙취해소음료 abstract: 본 발명은 콩나물을 이용한 숙취해소음료에 관한 것으로, 콩나물 추출물 및 목이버섯 추출물을 포함하는 복합 추출물을 유효성분으로 포함하고, 상기 콩나물 추출물은 황톳물을 이용하여 재배한 것을 특징으로 한다.이에 따라, 별도의 첨가제 없이 천연재료만을 이용하여 콩나물의 비린향을 잡아주고, 숙취해소에 효과적인 콩나물을 효율적으로 활용하여 뛰어난 숙취해소 효과를 가진다. claims: 콩나물 추출물 및 목이버섯 추출물을 포함하는 복합 추출물을 유효성분으로 포함하고,상기 콩나물 추출물은 황톳물을 이용하여 재배한 것을 특징으로 하는 콩나물을 이용한 숙취해소음료., Ltext: 농업, prediction: 임업
532/1059 Row 532: application_number: 1020190022785, combined_string: invention_title: 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 무공해 콩나물과, 그 재배방법 abstract: 본 발명은 펩타이드 결합 용액을 이용한 칼슘 및 영양성분이 향상된 무공해 콩나물과 그 재배방법에 관한 것으로, 본 발명에 따르면, 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 콩나물을 재배하는 방법에 있어서, 콩나물 콩을 선별한 후 세척하고 물기를 제거하는 세척 단계; 세척된 콩나물 콩을 펩타이드 결합 용액에 침지시켜 불리는 콩불리기 단계 및 불린 콩나물 콩을 재배용기에 넣고 물과 펩타이드 결합용액을 혼합한 희석액을 살포 및 회수하는 방식으로 재배하는 재배 단계를 포함하는 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 무공해 콩나물 재배방법을 제공할 수 있다.이에 따라 재배된 칼슘 및 영양성분이 향상된 무공해 콩나물을 제공할 수 있다. claims: 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 콩나물을 재배하는 방법에 있어서,콩나물 콩을 선별한 후 세척하고 물기를 제거하는 세척 단계;세척된 콩나물 콩을 펩타이드 결합 용액에 침지시켜 불리는 콩불리기 단계; 및불린 콩나물 콩을 재배용기에 넣고 물과 펩타이드 결합 용액을 혼합한 희석액을 살포 및 회수하는 방식으로 재배하는 재배 단계;를 포함하되,상기 펩타이드 결합 용액은,물, 산화칼슘 및 아미노산을 혼합하고 가열교반하여 제1 혼합액을 제조하는 단계;산화칼슘을 정제된 물에 침지시킨 후 여과하여 여과액을 얻는 단계;여과액에 비타민 D를 혼합하고 가열교반하여 제2 혼합액을 제조하는 단계;상기 제2 혼합액에 초음파를 인가하여 입자를 분쇄하는 단계; 및상기 제1 혼합액과 초음파가 인가된 제2 혼합액을 혼합하여 펩타이드 결합 용액을 제조하는 단계;를 통해 제조되는 것을 특징으로 하는 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 무공해 콩나물 재배방법.제2항의 재배방법에 의해 재배된 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 무공해 콩나물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

533/1059 Row 533: application_number: 1020190021754, combined_string: invention_title: 재배실과 연통된 외부에 수조가 형성된 하우징, 및 이것을 이용한 콩나물 재배장치 abstract: 본 발명은 재배실과 연통된 외부에 수조가 형성된 하우징을 이용한 콩나물 재배장치에 관한 것으로, 이의 구성은 재배실(3)을 갖는 하우징(1), 상기 재배실(3) 하부에 설치되어 재배통(미도시)을 탑재하여 받침 지지하는 바닥프레임(11), 이 바닥프레임(11) 하부에 배관되고 보일러(14)에서 가열된 온수를 재배실(3)로 안내하여 재배실(3) 바닥에 저장된 재배수(W)의 온도를 높이는 온수파이프(12), 상기 바닥프레임(11) 하부에 배관되고 원수를 재배실(3)로 안내하여 재배실(3) 바닥에 저장된 재배수(W)의 온도를 낮추는 냉수파이프(13), 상기 온수파이프(12)에 온수를 제공하는 보일러(14), 보일러(14)와 재배실(3)에 원수를 공급하는 원수파이프(15), 재배수(W)를 재배통에 분사하는 분사노즐(16), 원수를 재배실(3)에 공급하는 보급파이프(17), 재배실(3) 바닥에 저장된 재배수(W)를 분사노즐(16)로 이송 안내하는 급수파이프(18), 재배실(3) 바닥에 저장된 물을 외부로 배출시키는 배수파이프(19), 재배실(3)에 저장된 물의 수위를 감지하는 수위감지센서(20), 및 재배실(3)에 저장된 재배수(W)의 온도를 감지하는 온도감지센서(21)를 포함한다. claims: 조립된 벽체(2) 내부에 밀폐된 재배실(3)이 구비되고, 이 재배실(3)을 개폐할 수 있도록 벽체(2)에 도어(4)가 장착되며, 재배실(3) 바닥에 저장된 재배수(W)와 연통될 수 있도록 벽체(2) 외부에 외부수조(5)가 형성되는 것을 특징으로 하는 재*실과 연통된 외부에 수조가 형성된 하우징.콩, 녹두를 포함한 재배나물의 원료를 보관하여 재배할 수 있도록 조립된 벽체(2) 내부에 밀폐된 재배실(3)이 구비되고, 이 재배실(3)을 개폐할 수 있도록 벽체(2)에 도l어가 장착되며, 재배실(3) 바닥에 저장된 재배수(W)와 연통될 수 있도록 벽체(2) 외부에 외부수조(5)가 형성되는 하우징(1);재배나물의 원료가 담긴 재배통을 탑재할 수 있도록 상기 하우징(1)의 바닥면 상부에 수평으로 설치되는 바닥프레임(11);상기 바닥프레임(11) 하부에 고르게 배관되고, 그 양단부가 보일러(14)와 연결되어 나물 재배시 하우징(1)의 바닥면상에 저장된 재배수(W)에 잠긴상태에서 이 재배수(W)의 온도를 높일 수 있도록 펌프에 의해 보일러(14)에서 가열된 온수를 순환 안내하는 온수파이프(12); 상기 바닥프레임(11) 하부에 고르게 배관되고 그 양단부가 원수탱크(T)와 연결되어, 나물 재배시 하우징(1)의 바닥면에 저장된 재배수(W)에 잠긴상태에서 이 재배수(W)의 온도를 낮출 수 있도록 펌프에 의해 원수를 순환 안내하는 냉수파이프(13);상기 온수파이프(12)의 양단부와 연결되어 되고, 제어부(22)의 신호에 따라 저장된 물을 가열하여 온수로 만들고 이 온수를 펌프에 의해 상기 온수파이프에 공급하는 순환시키는 보일러(14);상기 원수탱크(T), 보일러(14) 및 재배실(3)과 배관으로 연결되고, 제어부(22)의 신호에 따라 보일러(14)와 재배실(3)에 원수를 공급하는 원수파이프(15);재배실(3)의 천장에 설치되고, 재배실(3) 바닥에 저장된 재배수(W)를 재배나물의 원료가 담긴 재배통에 분사하여 공급하는 분사노즐(16);상기 원수파이프(15)와 재배실(3) 사이에 배관되어 원수를 재배실(3)에 공급하는 보급파이프(17);상기 재배실(3)과 분사노즐(16)에 연결되고, 제어부(22)의 신호에 따라 구동하는 펌프에 의해 재배실(3) 바닥에 저장된 재배수(W)를 분사노즐(16)로 이송 안내하는 급수파이프(18);상기 재배실(3)과 연결되고, 재배실(3) 바닥에 저장된 물을 외부로 배출시키는 배수파이프(19);재배실(3)에 저장된 물이 설정된 수위에 도달하면 제어부(22)의 신호에 의해 펌프의 구동이 정지되어 재배실(3)로 공급된 물을 차단할 수 있도록 재배실(3)에 저장된 물의 수위를 감지하는 수위감지센서(20); 및재배실(3)에 저장된 재배수(W)의 온도를 감지하는 온도감지센서(21);를 포함하는 것을 특징으로 하는 재배실과 연통된 외부에 수조가 형성된 하우징을 이용한 콩나물 재배장치., Ltext: 농업, prediction: 농업
534/1059 Row 534: application_number: 1020190000074, combined_string: invention_title: 만두피에 콩나물 원액 즙을 첨가한 만두 abstract: 우리음식 중에는 만두가 있다. 만두는 만두피 속에 든 내용물에 따라 각기 다른 이름으로 군만두, 물만두, 고기만두, 김치만두, 새우만두, 야채만두 등 다양한 만두가 있다.본 발명은 밀을 빻아 만든 분말가루인 밀가루를 반죽 시 만두피에 다양한 영양성분이 풍부하고 효능이 많은 식재료로 부드럽고 달콤한 맛을 내는콩나물 원액 즙을 적당하게 골고루 첨가하여 만두를 만드는 기술 분야의 발명이다.콩나물과 밀에 포함되어 있는 다양한 영양성분의 효능이 첨가한 만두를 접할 수 있는 기회를 소홀하게 다룰 수 있는 문제점을 해결하고이를 개선하고자 만두피에 콩나물 원액 즙을 첨가한 만두에 대해 연구한 결과 해결하는 수단으로 기술을 발명하게 되였다.다양한 영양성분의 효능이 많은 콩나물 원액 즙을 만두피에 첨가한 만두 제조방법으로콩나물을 깨끗이 통째로 세척한 후에 물기를 제거하고 잘게 분쇄하여 추출기 등을 이용하여 양질의 콩나물 원액 즙을 얻는다.밀을 빻아 만든 분말가루인 밀가루를 만두피를 만들기 위해 반죽에 콩나물 원액 즙을 골고루 적당하게 첨가하여 반죽을 만든다.콩나물 원액 즙을 첨가한 밀가루 반죽을 얇게 적당한 규격으로 만두피를 만든다.콩나물 원액 즙을 첨가한 밀가루 반죽을 얇게 밀어서 만든 만두피에 고기, 야채 등 내용물을 넣어 만든 만두를 접할 수 있는 기회가 주어지는 기술이 포함된 발명이다.농산물인 콩나물과 밀가루 소비증가로 농촌에서 콩나물과 밀을 재배하시는 농민에게 많은 소득을 올릴 수 있으며만두피에 콩나물 원액 즙이 첨가한 만두의 수요증가에 따라 종사자에게 일자리 제공으로 고용창출에 크게 도움이 되는 방법을 제공함으로서산업상 이용가능성이 매우 높은 기술 분야의 발명이다.국민 모두에게 콩나물과 밀에 함유되어 있는 다양한 영양성분의 효능이 포함된 만두피에 콩나물 원액 즙을 첨가한 만두를 편리하게 구입하여 취식할 수 있도록 함으로서국민건강강화에 크게 기여가 매우 높은 기술 분야의 발명이다. claims: 본 발명은 다양한 영양성분이 풍부하고 효능이 많은 식재료로 그늘에서 발아시킨 대두의 뿌리를 자라게 한 콩나물에서 추출한 콩나물 원액 즙을 가장 오래되고 중요한 작물 중의 하나인 밀을 빻아 만든 분말가루인 밀가루에 적당하게 골고루 첨가하여반죽으로 만든 만두피에 콩나물 원액 즙을 첨가한 만두로 만드는 기술 분야의 발명이다.본 발명은 밀을 빻아 만든 분말가루인 밀가루를 반죽 시 다양한 영양성분의 효능을 골고루 갖춘 콩나물 원액 즙을 첨가한 만두를일상생활에서 편리하게 구입하여 취식함으로서 국민건강강화를 유지하는데 크게 기여하는 효과를 가지는 기술이 포함되어 있는 발명이다.다양한 영양성분의 효능이 포함되어 있는 콩나물과 밀로 만든 만두의 소비증가에 따라 콩나물과 밀을 재배하는 농민에게 많은 소득을 올릴 수 있으며만두피에 콩나물 원액 즙을 첨가한 만두의 수요증가에 따라 종사자에게 일자리 제공으로 고용창출에 크게 도움이 되는 방법을 제공함으로서산업상 이용가능성이 매우 높은 기술의 발명이다., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

535/1059 Row 535: application_number: 1020180128861, combined_string: invention_title: 콩나물, 숙주나물, 및 수경식물 재배용 재순환항온챔버 장치 abstract: 본 발명은 항온챔버, EM(Effective Microorganisms, 유용미생물군) 배양장치, 바이오 흡수·유출 필터를 포함하여 구성되는 콩나물, 숙주나물 또는 수경식물 재배용 재순환 항온챔버 장치에 관한 것이다.본 발명에 따른 콩나물, 숙주나물 또는 수경식물 재배용 재순환 항온챔버 장치는 소량의 용수를 재순환하여 반복적으로 이용할 수 있기 때문에 수자원을 효율적으로 이용할 수 있고, 싹기름 식물의 발아 또는 재배 중 분비되는 유기 분비물이 살수액과 함께 EM(Effective Microorganisms, 유용미생물군) 배양수조로 모여 EM(Effective Microorganisms, 유용미생물군)의 배양에 유용하게 이용될 수 있기 때문에 지표수 또는 지하수의 오염을 획기적으로 감소시킬 수 있으며, EM(Effective Microorganisms, 유용미생물군) 배양액 또는 바이오미네랄 복합체와 숯가루, 규석 또는 망간 등을 사용하여 제조한 바이오 흡수·유출 필터를 사용하기 때문에 별도의 성장촉진제, 농약 또는 영양제 등을 처리하지 않고도 순수 유기 재배법으로 위생적으로 우리 국민들의 다소비 식품인 콩나물, 숙주나물 등을 재배할 수 있으므로, 국민건강증진상 매우 유용한 발명이다. claims: EM(Effective Microorganisms, 유용미생물군) 배양액을 이용한 콩나물, 숙주나물, 및 수경재배식물의 재배 방법에 있어서,(1) 항온, 조명, 기폭장치가 부착된 EM(Effective Microorganisms, 유용미생물군) 배양수조 내에 EM(Effective Microorganisms, 유용미생물군) 배양액을 넣고 다시 배양하는 단계;(2) 상기 EM(Effective Microorganisms, 유용미생물군) 배양수조 내의 EM(Effective Microorganisms, 유용미생물군) 배양액을 EM(Effective Microorganisms, 유용미생물군) 배양수조와 항온챔버를 연결하는 이동 파이프를 통하여 항온챔버의 상부로 끌어 올린 다음 콩나물, 숙주나물, 및 수경재배식물에 살수하는 단계; 및(3) 상기 살수액을 항온챔버 하단의 EM(Effective Microorganisms, 유용미생물군) 배양수조로 회수하여 다시 EM(Effective Microorganisms, 유용미생물군)를 배양하는데 이용하는 단계;를 포함하는 과정을 반복하는 것을 특징으로 하는 EM(Effective Microorganisms, 유용미생물군) 배양액을 이용한 콩나물, 숙주나물, 및 수경재배식물의 재배 방법., Ltext: 농업, prediction: 임업
536/1059 Row 536: application_number: 1020180121941, combined_string: invention_title: 숨쉬는 콩나물 통 abstract: 이상과 같이 콩나물재배하는데 사시도 제1도 내부와 제2도 내부모양과 같이 하면 (E)에 공기유통과 원통파이프(B)상,하, 옆에 많은 구멍으로 신선한 공기가 통하여 씽씽한 콩나물을 재배하고 장시간 보관하는데 효과가 있은 숨쉬는 콩나물 통임. claims: 청구항 1콩나물 통에 공기유통을 많이 시키는데 하면 터널(H)와 하중앙원통(D)에 원통파이프(B)을 연결하고 콩나물통 하면과 터널 (H)와 원통(D)와 연결한 원통파이프(B)상,하,옆 많은 구멍으로 많은 공기를 제공한 숨쉬는 콩나물통., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

537/1059 Row 537: application_number: 1020180117507, combined_string: invention_title: 칼라만시를 이용한 콩나물의 재배방법 abstract: 본 발명은 칼라만시를 이용한 콩나물의 재배방법에 관한 것으로서, 보다 구체적으로는 콩나물을 재배하는 과정에 있어서, 적정 수소이온농도를 가진 칼라만시를 재배수로 하여 재배함으로써 칼라만시에 함유된 유효성분을 공급함과 아울러 미생물의 성장을 억제하여 콩나물의 수율을 증대하도록 하는 칼라만시를 이용한 콩나물의 재배방법에 관한 것이다. claims: ⒜ 칼라만시의 과육과 껍질을 가공하여 pH 5.5~6.5의 칼라만시 재배수를 얻는 재배수 제조 단계; 및 ⒝ 정선된 콩에 상기 칼라만시 재배수를 공급하여 온도 18~22℃에서 콩나물을 재배하는 콩나물 재배 단계;를 포함함을 특징으로 하는 칼라만시를 이용한 콩나물의 재배방법., Ltext: 농업, prediction: 농업
538/1059 Row 538: application_number: 2020180003688, combined_string: invention_title: 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기 abstract: 본 고안은 가정에서 새싹채소를 재배할 때 사용되는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 관한 것으로써 보다 상세하게는 유통과 포장, 보관이 용이하고 무게가 매우 가볍고 크기가 작은 일회용 새싹용기를 이용하여 적정 용량의 새싹채소를 부력과 모세관현상을 이용한 간단한 방법으로 재배하여 가정에서 저렴한 가격으로 새싹채소를 직접 키워 먹을 수 있도록 하는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 관한 것이다.본 고안은 유통과 구입 및 보관이 용이하도록 콤팩트형 1회용 용기로 제작하여 개당 가격이 수백원에 불과하도록 용기의 제작 단가와 부피를 줄인다. 이러한 용기의 본체는 일반적으로 1회용 용기에 사용되는 얇은 플라스틱 소재로 빛을 차단하기 위한 검정색 소재이며. 본체안에 결합되는 솜 또는 부직포 등 물을 잘 흡수하는 소재의 패드가 물을 흡수 할 수 있도록 하단에 여러개의 구멍(흡수공)이 뚫린 원통의 형태이다. 본체에 원형 링 형상의 스치로폼을 끼우면 본체를 물에 띄울 수 있게 된다. 이러한 본체 안에 물을 잘 흡수하는 소재인 솜 또는 부직포로 된 패드를 결합하고 그 위에 씨앗을 담는다. 이러한 방법으로 스치로폼의 부력을 이용하여 본체를 물위에 띄우면 본체 하단의 흡수공을 통해 본체내부의 솜 또는 부직포로 된 패드가 모세관현상으로 인해 물을 흡수하여 그 위에 담긴 씨앗에 수분이 공급되는 것이다. 또한, 상기 씨앗이 담긴 솜 또는 부직포는 검정색의 충분한 길이를 가진 아주 얇은 염화비닐로 덮여있어 콩나물과 같이 빛을 차단해야 하는 경우 빛을 차단하는 역할을 하며, 씨앗이 자라는 힘에 의해 얇은 염화비닐을 밀고 올라가며 자라도록 한다. 이 염화비닐은 공기구멍을 타공하여 씨앗이 발아하는데 공기가 효율적으로 작용하도록 한다. 보리와 같이 빛이 차단되면 안되는 경우에는 염화비닐이 포함되어 있지 않다.본체의 상단부를 덮는 본 고안의 덮개는 일반적으로 사용되는 비닐로 이루어진 스티커 형식의 비닐캡으로 불투명하여, 유통과정에서 씨앗이 쏟아지지 않도록 하는 역할과 제품의 명칭과 유통기한 및 사용법등을 기재할 수 있도록 하며, 발아 이후 빛이 차단되면 안되는 경우 씨앗발아 과정에서 빛을 차단하는 역할을 하여 씨앗이 발아하고 빛이 유입돼야하는 경우 비닐캡 형태의 덮개를 떼어내서 빛을 유입시키는 것이다. claims: 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 있어서 기존의 다양한 새싹재배기와 달리 1인가구나 1회용 식재료에 적합하도록 용기안에 재배가능한 씨앗을 포함한 콤팩트한 1회용 용기로 제작하여 유통하는 것을 특징으로 하는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

539/1059 Row 539: application_number: 2020180003689, combined_string: invention_title: 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기 abstract: 본 고안은 가정에서 새싹채소를 재배할 때 사용되는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 관한 것으로써 보다 상세하게는 유통과 포장, 보관이 용이하고 무게가 매우 가볍고 크기가 작은 일회용 새싹용기를 이용하여 적정 용량의 새싹채소를 부력과 모세관현상을 이용한 간단한 방법으로 재배하여 가정에서 저렴한 가격으로 새싹채소를 직접 키워 먹을 수 있도록 하는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 관한 것이다.본 고안은 유통과 구입 및 보관이 용이하도록 콤팩트형 1회용 용기로 제작하여 개당 가격이 수백원에 불과하도록 용기의 제작 단가와 부피를 줄인다.이러한 용기의 본체는 물에 띄울 수 있고, 가벼운 스치로폼이며, 본체위에 결합되는 솜 또는 부직포 등 물을 잘 흡수하는 소재의 패드가 물을 흡수 할 수 있도록 중앙에 구멍이 뚫린 원형의 형태이다. 이러한 스치로폼 본체 위에 물을 잘 흡수하는 소재인 솜 또는 부직포를 결합하고 그 위에 씨앗을 담는다. 이러한 방법으로 스치로폼의 부력을 이용하여 물위에 띄우면 솜 또는 부직포가 모세관현상으로 인해 물을 흡수하여 그 위에 담긴 씨앗에 수분이 공급되는 것이다. 또한, 상기 씨앗이 담긴 솜 또는 부직포는 검정색의 충분한 길이를 가진 아주 얇은 염화비닐로 덮여있어 콩나물과 같이 빛을 차단해야 하는 경우 빛을 차단하는 역할을 하며, 씨앗이 자라는 힘에 의해 얇은 염화비닐을 밀고 올라가며 자라도록 한다. 이 염화비닐은 공기구멍을 타공하여 씨앗이 발아하는데 공기가 효율적으로 작용하도록 하며, 이러한 방식으로 보리와 같이 빛이 차단되면 안되는 경우에는 빛이 통과하는 투명한 염화비닐로 구성된다. 본 고안의 덮개는 일반적으로 사용되는 비닐로 이루어진 스티커 형식의 비닐캡으로 불투명하여, 유통과정에서 씨앗이 쏟아지지 않도록 하는 역할과 제품의 명칭과 유통기한 및 사용법등을 기재할 수 있도록 하며, 발아 이후 빛이 차단되면 안되는 경우 씨앗발아 과정에서 빛을 차단하는 역할을 하여 씨앗이 발아하고 빛이 유입돼야하는 경우 비닐캡 형태의 덮개를 떼어내서 빛을 유입시키는 것이다. claims: 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 있어서 기존의 다양한 새싹재배기와 달리 1인가구나 1회용 식재료에 적합하도록 용기안에 재배가능한 씨앗을 미리 담아서 콤팩트한 1회용 용기로 제작하여 유통하는 것을 특징으로 하는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기, Ltext: 농업, prediction: 임업
540/1059 Row 540: application_number: 1020180078162, combined_string: invention_title: 땅콩나물을 이용한 건강기능성 식품의 제조 방법 abstract: 본 발명은 땅콩나물을 이용한 건강기능식품 제조방법에 관한 것으로서, 보다 상세하게는 1) 땅콩을 수경 재배하여 땅콩나물(새싹땅콩)을 수확하고 세척하는 단계; 2) 상기 세척된 땅콩나물을 1차 건조한 후 증숙하는 단계; 3) 상기 증숙된 땅콩나물을 2차 건조한 후 로스팅하는 단계; 4) 상기 로스팅된 땅콩나물을 분말로 분쇄하는 단계; 및 5) 상기 땅콩나물 분말을 아카시아 꿀로 환 또는 단 형태로 제조하는 단계;를 포함하는 땅콩나물을 이용한 건강기능성 식품의 제조 방법 및 상기 방법에 의해 제조된 땅콩나물을 이용한 건강기능성 식품 조성물에 관한 것이다. 본 발명은 물 없이 씹어서 취식할 때 잘 부서지도록 함과 더불어 씹을 때 맛과 향에 대한 거부감을 줄일 수 있으며, 휴대하면서 손쉽게 복용할 수 있으며 전립선 기능을 강화해줌으로서 휴대하면서 필요시 소변 배출을 원활하게 돕는 건강기능성 식품으로, 전립선이 약한 분들에게서 많은 수요를 창출될 것으로 기대된다. claims: 1) 땅콩을 수경 재배하여 땅콩나물(새싹땅콩)을 수확하고 세척하는 단계;2) 상기 세척된 땅콩나물을 1차 건조한 후 증숙하는 단계;3) 상기 증숙된 땅콩나물을 2차 건조한 후 로스팅하는 단계;4) 상기 로스팅된 땅콩나물을 분말로 분쇄하는 단계; 및5) 상기 땅콩나물 분말을 아카시아 꿀로 환 또는 단 형태로 제조하는 단계;를 포함하는 땅콩나물을 이용한 건강기능성 식품의 제조 방법.제 1항 내지 제 6항 중 어느 한 항의 방법으로 제조된 땅콩나물을 이용한 건강기능성 식품 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

541/1059 Row 541: application_number: 1020170162825, combined_string: invention_title: 작두콩나물의 재배방법 및 상기 방법으로 재배된 작두콩나물을 이용한 장아찌 abstract: 본 발명은 (a) 작두콩을 물에 침종시켜 발아시킨 후 재배하여 작두콩나물을 준비하는 단계; (b) 매실, 참당귀, 다래순 및 설탕을 혼합한 후 발효한 발효물을 여과한 후 숙성시켜 약초 발효액을 제조하는 단계; (c) 상기 (b)단계의 제조한 약초 발효액에 물, 간장 및 설탕을 혼합한 간장 혼합물을 졸인 간장 혼합 농축액을 숙성시켜 약초 간장을 제조하는 단계; (d) 간장 및 된장을 혼합한 혼합장에 상기 (a)단계의 준비한 작두콩나물을 넣어 염장한 후 건져내 염장 작두콩나물을 준비하는 단계; (e) 상기 (d)단계의 준비한 염장 작두콩나물에 상기 (c)단계의 제조한 약초 간장을 넣어 1차 숙성시키는 단계; 및 (f) 상기 (e)단계의 1차 숙성시킨 작두콩나물 숙성물에 상기 (b)단계의 제조한 약초 발효액을 추가로 첨가한 후 2차 숙성시키는 단계를 포함하여 제조하는 것을 특징으로 하는 작두콩나물 장아찌의 제조방법 및 상기 방법으로 제조된 작두콩나물 장아찌에 관한 것이다. claims: (a) 작두콩을 물에 침종시켜 발아시킨 후 재배하여 작두콩나물을 준비하는 단계;(b) 매실, 참당귀, 다래순 및 설탕을 혼합한 후 발효한 발효물을 여과한 후 숙성시켜 약초 발효액을 제조하는 단계;(c) 상기 (b)단계의 제조한 약초 발효액에 물, 간장 및 설탕을 혼합한 간장 혼합물을 졸인 간장 혼합 농축액을 숙성시켜 약초 간장을 제조하는 단계;(d) 간장 및 된장을 혼합한 혼합장에 상기 (a)단계의 준비한 작두콩나물을 넣어 염장한 후 건져내 염장 작두콩나물을 준비하는 단계;(e) 상기 (d)단계의 준비한 염장 작두콩나물에 상기 (c)단계의 제조한 약초 간장을 넣어 1차 숙성시키는 단계; 및(f) 상기 (e)단계의 1차 숙성시킨 작두콩나물 숙성물에 상기 (b)단계의 제조한 약초 발효액을 추가로 첨가한 후 2차 숙성시키는 단계를 포함하여 제조하는 것을 특징으로 하는 작두콩나물 장아찌의 제조방법.제1항 내지 제4항 중 어느 한 항의 방법으로 제조된 작두콩나물 장아찌., Ltext: 농업, prediction: 농업
542/1059 Row 542: application_number: 1020170135519, combined_string: invention_title: 땅콩나물 재배방법 및 재배기 abstract: 본 발명은 땅콩나물 재배방법 및 재배기에 관한 것으로서 더욱 상세하게는 일반 가정에서 톱밥이나 부토,왕겨혼합발효물 등 을 사용하지 않고 인위적인 금속물질,키토산 첨가나 과다한 살수 없이 손 쉽게 친환경 유기농 땅콩나물을 재배하는 방법 및 재배기에 관한 것이다. claims: 땅콩나물 재배방법은 탈피,건조된 땅콩종자를 불림박스(104)에 담긴 자화기(207)에서 생성된 자화수에 침수하여 불림하는 불림단계(S100),상기 불림단계에서 불려진 땅콩을 재배프라스틱박스(300)에 담고 8시간 한번씩 자화수를 살수 하면서 24시간 동안 발아 시키는 발아단계(S110),발아된 땅콩을 펄라이트(301 )가 2cm 두께로 깔린 상기 재배박스(300)에 파종한후 다시 그 위에 펄라이트를 8cm 높이로 편후 25-28℃ 온도에서 재배하는 생장단계(S120),를 포함하는 것을 특징으로 한다.본 발명의 땅콩나물 재배기는 정면에 여닫이문(110)이 설치 되여 있고 상부의 손잡이(111)로 앞으로 당겨 열수 있으며 재배기 오른 쪽에는 온도조절스위치(112),기능조절스위치(113),시간조절스위치(114),사용지시등(115),저수위지시등(116),온도알림판(117),시간알림판(118),재배기받침대(119)로 구성된 본체100)를 특징으로 한다상기 본체(100) 내측 좌우 양면에 단턱(101)이 형성되여 펄라이트(301)가 담긴 전용박스(300)를 얹어 놓을수 있고 상단에는 물이송관(103)과 연결된 물분사관(102)이 설치 된것을 특징으로 하는 재배기.재배기 밑 바닥에는 물저장 겸용으로 사용되는 땅콩나물종자불림박스(104)가 있으며 그 위에는 자동공제부(200)에 연결된 히터(201 Heater)와 온도센서(202),저수위센서(203),온도알림판(115),시간알림판(116),물흡수관(204)에 연결된 물순환펌프(205),자화수이송관(206)에 연결된 자화기(207),수도공급관(208)과 연결된 수도공급연결나트(209)로 이루어 지는 것을 특징으로 하는 재배기상기 재배기에 있어서 자동공제부(200)가 설치되여 있고 본체 외부에 있는 기능조절스위치(113),시간조절스위치(114),온도조절스위치(112)를 통하여 불림기능,발아기능.생장기능을 선택하고 재배온도와 살수시간간격을 자동공제하는 것을 특징으로하는 재배기 이다, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

543/1059 Row 543: application_number: 1020170107990, combined_string: invention_title: 채소 재배용기 이동용 캐스터바퀴 abstract: 본 발명은 채소 재배용기 이동용 캐스터바퀴에 관한 것으로서, 숙주, 콩나물 등과 같은 채소 재배용기로 부터 흘러내려오는 물이 유입됨으로 인한 캐스터바퀴 연결부의 부식방지를 방지토록 하기 위한 것이다.이를 실현하기 위한 본 발명은, 채소 재배용기(100)의 저면 다리부(10)에 고정플레이트(21)에 의해 결합되는 캐스터프레임(20)과, 상기 고정플레이트(21)와 360도 회전이 가능하게 연결되도록 캐스터프레임(20)의 상부에 구성된 베어링부(22)와, 상기 캐스터프레임(20)의 하단부에 구성되는 이동바퀴(30)로 구성되는 채소 재배용기 이동용 캐스터바퀴에 있어서, 상기 다리부(10)에는 고정플레이트(21) 및 베어링부(22)가 삽입 결합되어질 수 있는 삽입홈(11)이 형성되고; 상기 삽입홈(11) 내에는 고정플레이트(21)의 지지를 위한 지지격벽(12)이 구성되며; 상기 삽입홈(11) 내벽면에는 고정플레이트(21)의 이탈 방지를 위한 지지돌기(13)가 돌출 구비되고; 상기 삽입홈(11)의 입구측에는 고정플레이트(21) 및 베어링부(22)의 외부 노출을 방지하기 위한 마감판(40)이 결합 구성된 것을 특징으로 한다. claims: 채소 재배용기(100)의 저면 다리부(10)에 고정플레이트(21)에 의해 결합되는 캐스터프레임(20)과, 상기 고정플레이트(21)와 360도 회전이 가능하게 연결되도록 캐스터프레임(20)의 상부에 구성된 베어링부(22)와, 상기 캐스터프레임(20)의 하단부에 구성되는 이동바퀴(30)로 구성되는 채소 재배용기 이동용 캐스터바퀴에 있어서,상기 다리부(10)에는 고정플레이트(21) 및 베어링부(22)가 삽입 결합되어질 수 있는 삽입홈(11)이 형성되고;상기 삽입홈(11) 내에는 고정플레이트(21)의 지지를 위한 지지격벽(12)이 구성되며;상기 삽입홈(11) 내벽면에는 고정플레이트(21)의 이탈 방지를 위한 지지돌기(13)가 돌출 구비되고;상기 삽입홈(11)의 입구측에는 고정플레이트(21) 및 베어링부(22)의 외부 노출을 방지하기 위한 마감판(40)이 결합 구성된 것을 특징으로 하는 채소 재배용기 이동용 캐스터바퀴.채소 재배용기(100)의 저면 다리부(10)에 고정플레이트(21)에 의해 결합되는 캐스터프레임(20)과, 상기 고정플레이트(21)와 360도 회전이 가능하게 연결되도록 캐스터프레임(20)의 상부에 구성된 베어링부(22)와, 상기 캐스터프레임(20)의 하단부에 구성되는 이동바퀴(30)로 구성되는 채소 재배용기 이동용 캐스터바퀴에 있어서,상기 다리부(10)에는 고정플레이트(21) 및 베어링부(22)가 삽입 결합되어질 수 있는 삽입홈(11)이 형성되고;상기 다리부(10) 내에는 고정플레이트(21)의 이탈 방지를 위한 지지격벽(12)이 구성되며;상기 다리부(10) 내벽면에는 고정플레이트(21)의 유동을 방지하기 위한 지지돌기(13')가 돌출 구비되고;상기 삽입홈(11)의 입구측에는 베어링부(22)의 외부 노출에 따른 이물질 유입을 방지하기 위한 마감판(40)이 결합 구성된 것을 특징으로 하는 채소 재배용기 이동용 캐스터바퀴., Ltext: 농업, prediction: 임업
544/1059 Row 544: application_number: 1020170094658, combined_string: invention_title: 면역 증강 효과를 갖는 콩나물 혼합물 abstract: 본 발명은 면역 증강 효과를 갖는 콩나물 혼합물에 관한 것으로, 보다 상세하게는 콩을 발아시킨 후 고농도의 산소수로 재배한 고농도 산소수 콩나물에 표고버섯과 건굴을 혼합하여 동결건조시킴으로써 세포독성을 가지지 않으면서 면역 관련 사이토카인들과 유전자 및 단백질들을 유도하고, 면역세포들을 증식시킴으로써 면역 증진 효능을 갖는 면역 증강 효과를 갖는 콩나물 혼합물에 관한 것이다.본 발명에 따른 면역 증강 효과를 갖는 콩나물 혼합물은, 산소수를 발아된 콩에 살포하여 재배된 콩나물에 표고버섯과 건굴을 혼합하여 동결건조시킨 것을 특징으로 한다. claims: 산소수를 발아된 콩에 살포하여 재배된 콩나물에 표고버섯과 건굴을 혼합하여 동결건조시키되,콩나물 : 표고버섯 : 건굴은 10 : 1 : 1의 중량 비율로 혼합되고,상기 콩나물은 20~30 ℃ 암실에서 2~6시간 간격으로 5~15분씩 용존산소 농도가 10 ppm ~ 20 ppm인 산소수를 발아콩에 5~7일간 살수하여 재배된 것을 특징으로 하는 면역 증강 효과를 갖는 콩나물 혼합물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

545/1059 Row 545: application_number: 2020170003646, combined_string: invention_title: 일회용 콩나물 재배용기 abstract: 본 고안의 목적은 기존 재배기의 한계(고가의 제조 비용, 보관 공간의 필요성, 청결 유지 등)을 극복하여, 가정에서 누구나 저가로 간편하게 콩나물 혹은 숙주나물을 용이하게 재배하여 무공해 상태로 먹을 수 있게 한 일회용 콩나물 재배용기를 제공한다. 이러한 본 고안은 일회용 콩나물 재배용기로서, 내부에 콩나물을 재배할 수 있는 수용공간이 마련되도록 상부만이 개구되게 형성됨과 아울러 상부 개구를 개폐할 수 있도록 덮개가 구비되고, 상기 수용공간의 바닥면에는 다수 개의 배수구멍들이 형성된 용기 몸체; 상기 용기 몸체의 수용공간에 마련되어 콩나물을 재배할 수 있는 콩이 안착되는 부직포; 및 상기 부직포에 안착되는 콩을 덮도록 설치되어, 콩나물의 재배를 위해 수용공간에 물이 살수(撒水)될 때 그 살수되는 물에 의해 콩이 움직이지 않도록 하여 콩나물이 곱실거리지 않고 직선상으로 성장하게 하는 천;을 포함한다. claims: 일회용 콩나물 재배용기에 있어서, 내부에 콩나물을 재배할 수 있는 수용공간이 마련되도록 상부만이 개구되게 형성됨과 아울러 상부 개구를 개폐할 수 있도록 덮개가 구비되고, 상기 수용공간의 바닥면에는 다수 개의 배수구멍들이 형성된 용기 몸체; 상기 용기 몸체의 수용공간에 마련되어 콩나물을 재배할 수 있는 콩이 안착되는 부직포; 및 상기 부직포에 안착되는 콩을 덮도록 설치되어, 콩나물의 재배를 위해 수용공간에 물이 살수(撒水)될 때 그 살수되는 물에 의해 콩이 움직이지 않도록 하여 콩나물이 곱실거리지 않고 직선상으로 성장하게 하는 천;을 포함하고, 상기 용기 몸체는: 종이 재질로 컵 형상을 이루게 형성된 종이층; 및 상기 종이층의 내측면에 형성된 코팅층;으로 이루어지되, 상기 코팅층은: 원적외선이 방출되고 항균력이 있는, 은 나노 입자가 함유된 금속으로 상기 종이층의 0.05중량% 이상에서 10중량% 이하의 비율로 코팅되는 것을 특징으로 하는 일회용 콩나물 재배용기. 제1항에 있어서, 상기 배수구멍은: 원형, 장방형, 타원, 삼각형, 사각형, 십자형 중 어느 하나의 형상으로 16~20개의 개수로 형성되는 것을 특징으로 하는 일회용 콩나물 재배용기., Ltext: 농업, prediction: 농업
546/1059 Row 546: application_number: 1020170076512, combined_string: invention_title: 땅콩나물 재배트레이 abstract: 본 발명은 배수가 원활하게 이루어질 수 있고, 또 재배가 완료된 땅콩나물을 수확할 때 뿌리가 절단되지 않고 수확할 수 있는 땅콩나물 재배트레이에 관한 것이다.본 발명의 땅콩나물 재배트레이는 땅콩이 거치되어 생육되는 다수의 관통홀이 형성된 바닥판과, 상기 바닥판에서 상부로 연장되는 측판을 포함하는 땅콩나물 재배트레이에 있어서, 상기 관통홀 주변으로는 연장홀이 형성된 땅콩나물 재배트레이를 제공한다. claims: 땅콩이 거지되어 생육되는 다수의 관통홀이 형성된 바닥판과, 상기 바닥판에서 상부로 연장되는 측판을 포함하는 땅콩나물 재배트레이에 있어서,상기 관통홀 주변으로는 연장홀이 형성된 땅콩나물 재배트레이., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

547/1059 Row 547: application_number: 1020170074571, combined_string: invention_title: 양파추출물을 이용한 콩나물 재배 방법 abstract: 본 발명에 따른 방법으로 재배된 콩나물은 특유의 비린내를 제거하여 일반 콩나물에 비해 선호도가 높고 다양한 조리 방법을 적용할 수 있으며, 발육 과정에서 양파추출물에 포함된 페쿠친, 퀘르세틴 등의 플라보노이드 성분을 흡수하여 혈액순환 및 당뇨병 개선의 효과가 있다. 또한 상기 양파추출물 이외에도 쇠무릎, 피막이풀, 섬쑥부쟁이 및 해란초 등의 약초나 감태, 돌미역, 꼬시래기, 모자반, 다시마 등의 해조류를 더 첨가함으로써 콩나물이 가지는 비린내의 원인인 리폭시게나아제의 활성을 저하시켜 특유의 비린내를 더욱 효과적으로 제거할 수 있다. claims: a) 콩을 물에 12 내지 36시간 동안 침지시켜 물에 불린 후, 5 내지 20 농도%의 소금물에 콩을 넣고 2 내지 3분간 교반하여 콩을 선별하고 이를 세척하는 단계;b) 물 100 중량부에 대해 양파 10 내지 50 중량부, 쇠무릎, 피막이풀, 섬쑥부쟁이 및 해란초에서 선택되는 어느 하나 또는 둘 이상의 약초 1 내지 10 중량부 및 감태, 돌미역, 꼬시래기, 모자반 및 다시마에서 선택되는 어느 하나 또는 둘 이상을 포함하는 해조류 1 내지 10 중량부를 투입한 후, 70 내지 100℃에서 1 내지 5시간 동안 가열하며, 가열 중간에 물 10 내지 50 중량부를 1 내지 3회 더 첨가하여 양파추출물을 수득하고, 1 내지 3회 여과하는 단계;c) 상기 양파추출물을 10 내지 15℃, 95 rH%의 습도에서 1 내지 3일간 숙성한 후, 상기 양파추출물 100 중량부에 소금 1 내지 10 중량부를 투입하여 재배액을 제조하는 단계;d) 상기 세척한 콩을 15 내지 25℃의 물에 1 내지 5시간 동안 침윤시킨 후, 15 내지 25℃의 암실에서 1 내지 5시간 동안 건조하는 것을 2 내지 5회 반복한 후, 재배용기에 투입하는 단계; 및e) 상기 재배용기에 상기 재배액을 3 내지 4시간 간격으로 공급한 후, 20 내지 25℃의 암실에서 5 내지 10일간 콩나물을 생육시키는 단계;를 포함하는 양파추출물을 이용한 콩나물 재배 방법., Ltext: 농업, prediction: 농업
548/1059 Row 548: application_number: 1020170073214, combined_string: invention_title: 땅콩나물 재배장치 abstract: 본 발명은 생장의 효율성을 높일 수 있는 땅콩나물 재배장치에 관한 것이다.본 발명의 땅콩나물 재배장치는 땅콩이 수용되어 생육 가능하도록 형성된 재배트레이; 상기 재배트레이가 다단으로 적재될 수 있도록 이루어진 프레임; 상기 재배트레이에 수용된 땅콩에 물을 공급하기 위한 급수탱크; 상기 급수탱크의 물을 펌프의 구동으로 이송하여 재배트레이의 땅콩에 공급하는 분사부; 상기 급수탱크에 설치되어 분사부를 통하여 재배트레이의 땅콩에 물을 공급할 때 미세한 기포를 같이 공급하는 스파클링 생성장치; 상기 급수탱크에 저장된 급수의 배출 및 상기 스파클링 생성장치를 제어하는 제어부; 를 포함하는 땅콩나물 재배장치를 제공한다. claims: 땅콩이 수용되어 생육 가능하도록 형성된 재배트레이;상기 재배트레이가 다단으로 적재될 수 있도록 이루어진 프레임;상기 재배트레이에 수용된 땅콩에 물을 공급하기 위한 급수탱크;상기 급수탱크의 물을 펌프의 구동으로 이송하여 재배트레이의 땅콩에 공급하는 분사부;상기 급수탱크에 설치되어 분사부를 통하여 재배트레이의 땅콩에 물을 공급할 때 미세한 기포를 같이 공급하는 스파클링 생성장치;상기 급수탱크에 저장된 급수의 배출 및 상기 스파클링 생성장치를 제어하는 제어부;를 포함하는 땅콩나물 재배장치, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

549/1059 Row 549: application_number: 1020170036590, combined_string: invention_title: 다목적 팬 핸들링시스템 abstract: 본 발명은 다목적 팬 핸들링시스템에 관한 것으로 하부에 팬이송용콘베이어가 구비된 기틀체의 전/후방 상부와 하부에 각각 특수한 형태로 내,외측체인스플라켓을 배열하고, 이에 소정간격으로 내용물이 넣어진 팬(채반, 트레이)을 받쳐주는 팬받침롤러가 구비되는 이너체인과 아웃터체인으로 형성되는 한쌍의 이송체인을 특수한 방법으로 결합하는 등 종래의 체인결합구조의 획기적인 개선으로 그 구조가 간단하면서도 전,후의 폭을 획기적으로 줄여줄 수 있기 때문에 종래에 설치할 수 없었던 협소한 장소에도 간편하게 설치하여 사용할 수 있도록 하고, 작은 공간에서 내용물을 원하는 용도별, 시간조절, 온/습도조절, 생산량 등에 따라 다수개의 팬(채반, 트레이)을 다양한 형태로 배열하여 외형, 크기, 높이 등에 구애됨이 없이 자유롭게 설계할 수 있도록 하며, 이러한 시스템을 사용용도에 따라 빵반죽의 발효 숙성장치는 물론이고 그 밖의 다른 제품들의 숙성기, 식품건조기, 냉장숙성기, 냉동고, 팬적재함, 증삼기, 스마트농법구현장치, 각종 수경재배장치, 콩나물재배장치 등과 같이 다양한 용도로 활용할 수 있도록 함은 물론, 더욱이 이와 같은 다양한 용도로 사용시 자동 및 연속작업이 가능하므로 별도의 대기 작업시간이 없으며, 작업의 효율성이 극대화되고 적은 인원과 시간으로 품질이 고른 양질의 제품을 얻을 수 있도록 할 수 있는 특수한 구조의 다목적 팬 핸들링시스템을 제공함으로써, 좀 더 편리하게 사용할 수 있도록 하여 주고자 함에 그 목적을 둔 것이다.상기와 같은 목적을 달성하기 위한 본 발명의 다목적 팬 핸들링시스템은 기본적으로 팬(10)을 공급 및 배출하는 팬이송용콘베이어(100)와;상기 팬이송용콘베이어(100) 상부로 수직으로 설치되는 기틀체(200)와;상기 기틀체(200)에 수직으로 연계설치되는 것으로 팬(10)의 상승과 하강이 동시에 이루어지도록 팬받침롤러(310a)(320a)를 구비한 한쌍의 이송체인(300)을 구동시키는 동력전달수단(300')과;상기 팬이송용콘베이어(100) 내측으로 형성되어 한쌍의 이송체인(300)에 구비된 팬받침롤러(310a)(320a) 상면에 팬(10)이 정확하게 안착될 수 있도록 정위치에 팬(10)을 정지시키는 스톱퍼(400)와;상기 스톱퍼(400) 앞쪽에 위치되도록 팬이송용콘베이어(100)에 형성되는 것으로 앞쪽의 팬(10)이 스톱퍼(400)에 닿아 정지되면 이를 감지한 센서의 감지신호에 의해 작동하면서 그 다음번 팬(10)을 측면에서 홀딩하여 주는 홀더(500)와;상기 기틀체(200)의 상부에 형성되어 한쌍의 이송체인(300)에 형성된 팬받침롤러(310a)(320a) 상면에 공급되어 최상부에 이송된 팬(10)을 후방으로 수평이송시키는 팬수평이송장치(600);를 포함하여 구성되어져 팬(10)을 순차적으로 공급→수직승강→수평이동→수직하강→배출할 수 있도록 이루어짐에 그 특징이 있는 것이다. claims: 팬(10)을 공급 및 배출하는 팬이송용콘베이어(100)와;상기 팬이송용콘베이어(100) 상부로 수직으로 설치되는 기틀체(200)와;상기 기틀체(200)에 수직으로 연계설치되는 것으로 팬(10)의 상승과 하강이 동시에 이루어지도록 팬받침롤러(310a)(320a)를 구비한 한쌍의 이송체인(300)을 구동시키는 동력전달수단(300')과;상기 팬이송용콘베이어(100) 내측으로 형성되어 한쌍의 이송체인(300)에 구비된 팬받침롤러(310a)(320a) 상면에 팬(10)이 정확하게 안착될 수 있도록 정위치에 팬(10)을 정지시키는 스톱퍼(400)와;상기 스톱퍼(400) 앞쪽에 위치되도록 팬이송용콘베이어(100)에 형성되는 것으로 앞쪽의 팬(10)이 스톱퍼(400)에 닿아 정지되면 이를 감지한 센서의 감지신호에 의해 작동하면서 그 다음번 팬(10)을 측면에서 홀딩하여 주는 홀더(500)와;상기 기틀체(200)의 상부에 형성되어 한쌍의 이송체인(300)에 형성된 팬받침롤러(310a)(320a) 상면에 공급되어 최상부에 이송된 팬(10)을 후방으로 수평이송시키는 팬수평이송장치(600);를 포함하여 구성되어져 팬(10)을 순차적으로 공급→수직승강→수평이동→수직하강→배출할 수 있도록 이루어짐을 특징으로 하는 다목적 팬 핸들링시스템., Ltext: 농업, prediction: 임업
550/1059 Row 550: application_number: 1020170021999, combined_string: invention_title: 꼬불이 콩나물 재배기 abstract: 본 발명은 꼬볼이콩나물 재배기에 관한 것으로 더욱 구체적으로는 현재의 꼬불이 콩나물을 재배할 시 재배 노동력을 현저히 감소시키더라도 꼬불이 콩나물을 효과적이면서 능률적으로 대량 재배할 수 있는 재배기를 제공할 수 있도록 한 것이다.즉, 프레임과; 상기 프레임에 회전가능케 지지되고, 상,하부에는 개방부가 형성된 본체와; 상기 본체의 개방부에 각각 결합/고정되는 받침판과; 상기 본체를 회전시키는 회전수단을 포함하여 구성하고, 상기 본체의 양측에 회전지지축을 형성하여 프레임의 지지프레임에 회전가능케 설치하며, 상기 회전수단을 입력축과 출력축을 가진 감속 기어박스로 하여 상기 출력축을 본체의 일 측 회전지지축에 연결한 것을 특징으로 꼬불이 콩나물 재배기를 제공할 수 있도록 한 것이다. claims: 프레임(10)과;상기 프레임(10)에 회전가능케 지지되고, 상,하부에는 개방부(21)(22)가 형성된 본체(20)와;상기 본체(20)의 개방부(21)(22)에 각각 결합/고정되고, 여러 개의 통수구멍(43)이 일정한 간격으로 천공된 타공판 형태의 받침판(40)과;상기 본체(20)를 회전시키는 회전수단(50)을 포함하여 구성한 것을 특징으로 하는 꼬불이 콩나물재배기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

551/1059 Row 551: application_number: 1020160179954, combined_string: invention_title: 발아율이 높고 상부 생장율이 우수한 땅콩나물의 재배방법 abstract: 본 발명은 발아율이 높고 상부 생장율(vigour index)이 우수한 땅콩나물의 재배방법에 관한 것으로, 보다 상세하게는 땅콩 종자의 배축(hypocotyl) 말단이 아래로 향하게 하며, 수직 방향으로 종자를 파종함으로써 발아율이 매우 높고 상부 생장율이 우수한 땅콩 나물의 재배방법에 관한 것이다.본 발명의 방법에 따라 땅콩 배축 말단이 아래로 향한 수직방향으로 종자를 파종할 경우 종자의 발아율이 매우 우수할 뿐만 아니라, 상부 생장율 및 묘목의 형태학적 특성 또한 매우 우수하여 상품성이 높은 땅콩나물을 생산할 수 있다. claims: 땅콩 종자의 배축(hypocotyl) 말단이 아래로 향하게 하며, 수직 방향으로 종자를 파종하는 것을 특징으로 하는, 발아율(germination rate)이 높고 상부 생장율(vigour index)이 우수한 땅콩나물의 재배방법., Ltext: 농업, prediction: 임업
552/1059 Row 552: application_number: 1020210121664, combined_string: invention_title: 이탈을 방지한 산림용 묘목 보호 시트 abstract: 본 발명은 이탈을 방지한 산림용 묘목 보호 시트에 관한 것으로서, 보다 상세하게는, 산에 식재된 어린 묘목에 설치하여 위치를 표시하여 용이하게 관리가 가능하고, 바람, 비 등에 의한 이탈 및 손상과 동물들에 의한 피해를 방지할 수 있는 이탈을 방지한 산림용 묘목 보호 시트에 관한 것이다. claims: 묘목에 설치하여 묘목을 용이하게 식별할 수 있는 이탈을 방지한 산림용 묘목 보호 시트에 있어서,절취선(PL) 및 절단선(CL)에 의해 인식부(20)가 재단되며, 접이선(FL)을 따라 상기 묘목(100)을 감싸도록 접이되는 시트지(10)로 이루어지되,상기 시트지(10)는,중앙부분에 형성된 상기 절취선(PL)에 의해 재단되어 상기 묘목(100)에 설치하는 제1인식표(30)와,상기 제1인식표(30)의 양측에 일정간격 이격되어 다수개 배치되며, 수직방향으로 형성된 상기 접이선(FL)과,양측단에서 내측으로 일정간격 이격되어 형성된 상기 절취선(PL)에 의해 재단되어 상기 묘목(100)에 설치하는 제2인식표(40)로 이루어지되,상기 제1인식표(30)는,내부 양측에 수직방향으로 상기 절단선(CL)이 재단된 원형의 중앙부분(31)과,상기 중앙부분(31) 보다 작은 크기의 원형이 상기 중앙부분(31)의 상단에 위치하며, 중앙에 삽입홈(34)이 형성되고 상기 삽입홈(34)에서 일측 방향 하단을 향해 지그재그 방향으로 상기 절단선(CL)이 재단된 상단부분(32)과,상기 중앙부분(31) 보다 작은 크기의 원형이 상기 중앙부분(31)의 하단에 위치하며, 중앙에 삽입홈(34)이 형성되고 상기 삽입홈(34)에서 타측 방향 상단을 향해 지그재그 방향으로 상기 절단선(CL)이 재단된 하단부분(33)으로 이루어지며,상기 시트지(10)의 상단에 수직방향으로 재단된 상기 절취선(PL)을 따라 절취하여 상기 제1인식표(30)의 상기 중앙부분(31)에 재단된 상기 절단선(CL)에 삽입되는 제3인식표(50)가 더 포함되는 것을 특징으로 하는 이탈을 방지한 산림용 묘목 보호 시트., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

553/1059 Row 553: application_number: 1020210077898, combined_string: invention_title: 잡초 배출이 용이한 구근 수확기 abstract: 본 발명은 잡초 배출이 용이한 구근 수확기에 관한 것으로, 제토컨베이어가 회전되게 설치되는 프레임에 고정되게 구비되는 연결바; 연결바에서 전방으로 돌출되게 구비되는 한편 제토컨베이어의 전방에서 그 전단부가 하향 경사지게 구비되는 굴취삽; 굴취삽과 프레임 사이에 형성되어 두둑 또는 고랑의 잡초가 걸리지 않고 통과할 수 있는 공간;을 포함하는 구근 수확기를 제공한다. claims: 제토컨베이어가 회전되게 설치되는 프레임에 고정되게 구비되는 연결바; 연결바에서 지지브라켓을 매개로 전방으로 돌출되게 구비되는 한편 제토컨베이어의 전방에서 그 전단부가 하향 경사지게 구비되는 굴취삽; 굴취삽과 프레임 사이에 형성되어 두둑 또는 고랑의 잡초가 걸리지 않고 통과할 수 있는 공간;을 양측 가장자리에 구비하되, 상기 공간은 굴취삽이 연결바보다 짧은 길이를 갖도록 구비되어, 프레임에 굴취삽의 설치시 굴취삽과 프레임 사이에는 일정 면적으로 형성되도록 한 구근 수확기., Ltext: 농업, prediction: 임업
554/1059 Row 554: application_number: 1020210023483, combined_string: invention_title: 시서스의 재배방법 abstract: 본 발명은 시서스의 재배방법에 관한 것으로, 보다 구체적으로는 일정하게 조성된 토양조성물을 사용하여 시서스 모종을 수차례 걸쳐 이식하면서 재배한 후 토양에 정식함으로써 정식 후 농약 살포나 시비 없이도 단기간에 유효성분함량이 높은 시서스를 재배할 수 있는 방법에 관한 것이다. 본 발명의 시서스 재배방법은, 시서스 모종을 준비하는 단계; 시서스 재배용 토양조성물이 담긴 화분에 시서스 모종을 삽목하여 재배하는 화분 삽목 재배 단계; 시서스 재배용 토양조성물이 담긴 더 큰 화분에 1~4차에 걸쳐 이식하면서 재배하는 화분 이식 재배 단계; 화분 이식 재배 단계가 끝난 후 토양에 정식하여 재배하는 토양 재배 단계를 포함한다. claims: 시서스 모종을 준비하는 단계;화산토, 부엽토 발효물 및 팜박 발효물을 포함하는 시서스 재배용 토양조성물이 담긴 화분에 상기 시서스 모종을 이식하여 재배하는 모종 이식 재배 단계;상기 모종 이식 재배한 시서스를 상기 시서스 재배용 토양조성물이 담긴 더 큰 화분에 1회 이상 수차례 이식하면서 재배하는 묘목 이식 재배 단계;상기 묘목 이식 재배 단계가 끝난 후 토양에 정식하여 재배하는 토양 재배 단계를 포함하는 시서스의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

555/1059 Row 555: application_number: 1020200150219, combined_string: invention_title: 플라즈마를 이용한 종자 처리 장치 abstract: 본 발명에 의하면, 수용 공간인 챔버를 제공하는 챔버 하우징; 상기 챔버에 수용되고 플라즈마 방전을 이용하여 종자를 처리하는 복수개의 종자 처리 모듈들; 및 상기 플라즈마 방전을 위하여 상기 복수개의 종자 처리 모듈들 각각으로 전원을 공급하는 전원 공급부를 포함하며, 상기 종자 처리 모듈들 각각은 상기 챔버에 위치하도록 설치되고 상기 플라즈마 방전이 일어나는 플라즈마 방전 유닛과, 상기 플라즈마 방전 유닛과 분리 가능하게 결합되고 처리 대상 종자들이 담기는 트레이 유닛을 구비하는 플라즈마를 이용한 종자 처리 장치가 제공된다. claims: 수용 공간인 챔버를 제공하는 챔버 하우징;상기 챔버에 수용되고 플라즈마 방전을 이용하여 종자를 처리하는 복수개의 종자 처리 모듈들; 및상기 플라즈마 방전을 위하여 상기 복수개의 종자 처리 모듈들 각각으로 전원을 공급하는 전원 공급부를 포함하며,상기 종자 처리 모듈들 각각은 상기 챔버에 위치하도록 설치되고 상기 플라즈마 방전이 일어나는 플라즈마 방전 유닛과, 상기 플라즈마 방전 유닛과 분리 가능하게 결합되고 처리 대상 종자들이 담기는 트레이 유닛을 구비하는,플라즈마를 이용한 종자 처리 장치., Ltext: 농업, prediction: 임업
556/1059 Row 556: application_number: 1020200083976, combined_string: invention_title: 묘목 물공급장치 abstract: 묘목 물 공급장치에 대해 개시된다.본 발명에 따른 묘목 물 공급장치는 상하부가 개구된 하나의 파이프가 길이방향을 따라 동일한 두 개의 부재로 절개된 형상으로 형성되되, 하부가 식재된 묘목 둘레에 소정 깊이로 지면에 삽입되는 제1 부재(100) 및 제2 부재(200);내부에 물을 저장 가능하도록 상기 제1 부재(100)와 제2 부재(200)는 묘목을 둘러싸도록 결합되어 묘목에 물을 공급하는 것을 특징으로 한다. claims: 상하부가 개구된 하나의 파이프가 길이방향을 따라 동일한 두 개의 부재로 절개된 형상으로 형성되되, 하부가 식재된 묘목 둘레에 소정 깊이로 지면에 삽입되는 제1 부재(100) 및 제2 부재(200);내부에 물을 저장 가능하도록 상기 제1 부재(100)와 제2 부재(200)는 묘목을 둘러싸도록 결합되어 묘목에 물을 공급하며,상기 제1 부재(100) 및 제2 부재(200)는,단면이 반원을 이루는 파이프형상으로 형성되되, 동일한 직경으로 수직방향으로 소정의 높이로 형성되며 하단부가 수직 하방향을 향하도록 형성된 원통부(110);상기 원통부(110) 상단에 형성되되, 수직 상방향으로 내경이 점진적으로 증가하는 확관부(120);상기 제1 부재(100)의 일측에는 제1 돌출부(111)가 형성되며 타측에는 제1 결합홈(112)이 형성되고, 상기 제2 부재(200)에는 상기 제1 돌출부(111)에 대향하는 위치에 제2 결합홈(212)이 형성되며, 상기 제1 결합홈(112)에 대향하는 위치에는 제2 돌출부(211)가 형성되어, 상기 제1 돌출부(111)는 제2 결합홈(212)에 결합되고 제2 돌출부(211)는 제1 결합홈(112)에 결합되며,내부에 저장된 물은 수압에 의해 수직 하방향으로 공급됨으로써, 물이 상기 원통부(110)의 외주면 밖으로 유실되지 않아 묘목 뿌리의 수분흡수율을 증가시키는 것을 특징으로 하며,상기 확관부(120)의 상단부에 수평방향으로 절곡되어 형성된 플랜지(140);를 더 포함하며,상기 플랜지(140)는 묘목 물 공급장치를 지면에 삽입하기 위해 가압력을 부가하기 용이하도록 하는 것을 특징으로 하는, 묘목 물 공급장치, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

557/1059 Row 557: application_number: 1020200076397, combined_string: invention_title: 근적외선 흡수스펙트럼을 이용한 식물 종자 생육활성의 비파괴 판별방법 abstract: 본 발명은 저장 및 보관 중인 식물 종자에 대하여 파괴하지 않은 상태로 근적외선 흡수 스펙트럼을 수득한 후 다변량 통계분석을 이용하여 종자의 생육활성을 판별할 수 있으므로 식물 종자의 특별한 전처리가 필요 없고 측정에 사용한 식물 종자의 폐기 없이 종자의 상품성을 평가할 수 있는 장점이 있다. claims: 비파괴 콩 종자 시료에 대하여 1100 내지 2500nm의 범위로 근적외선 흡수 스펙트럼을 얻는 제 1 단계;상기 근적외선 흡수 스펙트럼으로부터 10 내지 100nm 간격으로 흡광도 데이터를 추출하는 제 2 단계;상기 흡광도 데이터를 이용하여 다변량 통계분석(mutivariate statistics analysis)을 수행하여 흡광도에 대한 변동기여도에 따라 주성분 파장을 추출한 로딩 플롯(loading plot)을 수득하고, 상기 로딩 플롯의 주성분 파장을 스코어에 따라 주성분 그룹으로 분리하여 영역으로 표시한 다변량 통계분석 스코어 플롯을 수득하는 제 3 단계; 및상기 비파괴 콩 종자 시료의 다변량 통계분석 결과를 통해 수득한 다변량 통계분석 스코어 플롯의 영역과 비교용 정상 비파괴 콩 종자 시료 및 비교용 비파괴 비정상 콩 종자 시료의 다변량 통계분석 결과를 통해 수득한 다변량 통계분석 스코어 플롯의 영역을 비교하여 상기 비파괴 콩 종자 시료의 생육활성을 판별하는 제 4 단계;를 포함하는 것을 특징으로 하는 식물 종자의 비파괴적 생육활성 판별 방법., Ltext: 농업, prediction: 임업
558/1059 Row 558: application_number: 1020200062470, combined_string: invention_title: 유기산 기체를 이용한 박과 식물 종자의 살균 방법 abstract: 본 발명은 유기산 기체를 이용한 박과 식물 종자의 살균 방법에 관한 것으로, 보다 상세하게는 특정 상대습도와 온도 조건에서 특정 유기산을 자연 기화하도록 유도함으로써 박과 종자의 발아율은 저해하지 않으면서 박과 종자에 존재하는 식물병원균과 식중독균을 멸균시키기 위한 살균 방법에 관한 것이다. claims: 아세트산 기체 또는 프로피온산 기체를 박과 식물 종자에 처리하는 것을 포함하는 박과 식물 종자의 살균 방법.식물병원균 또는 식중독균을 멸균시키는 박과 식물 종자의 살균 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

559/1059 Row 559: application_number: 1020200058048, combined_string: invention_title: 봉투식 버섯종균 자동액체 접종기 abstract: 본 발명은 봉투식 버섯종균 자동액체 접종기에 관한 것으로, 더욱 상세히는 입구측의 형태 유지가 어려운 봉투식 배지용기에 종균액의 자동접종과 뚜껑의 개폐가 용이하도록 상부에 뚜껑이 결합되고 내부에 배지가 충진된 상태인 봉투식 배지용기가 다수 담긴 바구니를 이송하는 이송부(20)와, 이송부에 의해 이송되던 바구니를 종균 접종위치에서 승하강 시키는 바구니승강부(30)와, 상기 바구니승강부의 상측으로 설치되어 다수의 봉투식 배지용기 입구를 고정시키는 용기고정부(40)와, 상기 용기고정부의 상측으로 설치되어 봉투식 배지용기의 뚜껑을 개폐하는 뚜껑개폐부(50)와, 상기 봉투식 배지용기에 종균액을 분사하는 종균분사부(60)와, 상기 이송부, 바구니승하강부, 용기고정부, 뚜껑개폐부, 종균분사부가 설치되는 작업테이블(10)로 구성된다. claims: 상부에 뚜껑이 결합되고 내부에 배지가 충진된 상태인 봉투식 배지용기가 다수 담긴 바구니(2)를 이송하는 이송부(20)와, 이송부에 의해 이송되던 바구니를 종균 접종위치에서 승하강 시키는 바구니승강부(30)와, 상기 바구니승강부의 상측으로 설치되어 다수의 봉투식 배지용기 입구를 고정시키는 용기고정부(40)와, 상기 용기고정부의 상측으로 설치되어 봉투식 배지용기의 뚜껑을 개폐하는 뚜껑개폐부(50)와, 상기 봉투식 배지용기에 종균액을 분사하는 종균분사부(60)와, 상기 이송부, 바구니승강부, 용기고정부, 뚜껑개폐부, 종균분사부가 설치되는 작업테이블(10)로 이루어지는 봉투식 버섯종균 자동액체 접종장치에 있어서,상기 용기고정부(40)는 상부의 승강실린더(40c)에 의해 승하강되고 등간격으로 복수의 용기입구투입공(410)이 형성된 용기고정판(41), ㄴ자로 절곡되며 상기 용기고정판(41)의 상부면에서 각 열의 용기입구투입공(410)을 중심으로 소정간격을 두고 양쪽에 대향하여 설치되고 각 용기입구투입공과 동일 위치에 각 요입홈(420a,420b)이 형성되며 배지용기의 입구를 가압할 수 있게 양측으로 슬라이딩 작동되는 다수의 제1클램프판(42a) 및 제2클램프판(42b)으로 구성되며,상기 뚜껑개폐부(50)는 작업테이블(10)의 양측면에 설치된 승강수단(50c)에 의해 승하강되며 각 용기입구투입공(410)과 대응되는 위치에 통공(510)이 형성되고 통공(510)의 주변으로 다수의 장공(511)이 형성된 뚜껑개폐판(51)과, 상기 뚜껑개폐판(51)의 상측에서 승강실린더(52e)에 의해 승하강되게 설치되며 각 통공(510)으로 수직 관통되고 배지용기의 뚜껑을 가압시키도록 하단부에 원통형의 가압블록(520s)이 구비된 가압봉(520)이 탄성력 있게 설치된 뚜껑가압판(52)과, 상기 뚜껑개폐판(51)과 뚜껑가압판(52)의 사이에 이중구조로 대향되게 설치되며 각 이동실린더(55a,55b)의 작동으로 각각 대향되게 수평이동되어 하단부 ㄴ자 형태의 제1뚜껑클램프(533a)와 제2뚜껑클램프(533b)가 배지용기의 뚜껑을 걸어 개폐시킬 수 있는 제1이동판(53a)과 제2이동판(53b)으로 구성되는 것을 특징으로 하는 봉투식 버섯종균 자동액체 접종기., Ltext: 농업, prediction: 임업
560/1059 Row 560: application_number: 1020200041883, combined_string: invention_title: 플라즈마를 이용한 종자 처리 장치 abstract: 본 발명에 의하면, 수용 공간인 챔버를 제공하는 챔버 하우징; 상기 챔버에 수용되고 플라즈마 방전을 이용하여 종자를 처리하는 복수개의 종자 처리 모듈들; 및 상기 플라즈마 방전을 위하여 상기 복수개의 종자 처리 모듈들 각각으로 전원을 공급하는 전원 공급부를 포함하며, 상기 종자 살균 모듈들 각각은 상기 챔버에 위치하도록 설치되고 상기 플라즈마 방전이 일어나는 플라즈마 방전 유닛과, 상기 플라즈마 방전 유닛과 분리 가능하게 결합되고 처리 대상 종자들이 담기는 트레이 유닛을 구비하는 플라즈마를 이용한 종자 처리 장치가 제공된다. claims: 수용 공간인 챔버를 제공하는 챔버 하우징;상기 챔버에 수용되고 플라즈마 방전을 이용하여 종자를 처리하는 복수개의 종자 처리 모듈들;상기 챔버의 공기를 외부로 배출하여 상기 챔버를 진공 상태로 형성하는 배기 펌프; 및상기 플라즈마 방전을 위하여 상기 복수개의 종자 처리 모듈들 각각으로 전원을 공급하는 전원 공급부를 포함하며,상기 종자 처리 모듈들 각각은 상기 챔버에 위치하도록 설치되고 상기 플라즈마 방전이 일어나는 플라즈마 방전 유닛과, 상기 플라즈마 방전 유닛과 분리 가능하게 결합되고 처리 대상 종자들이 담기는 트레이 유닛을 구비하며,상기 트레이 유닛에는 상기 트레이 유닛이 상기 플라즈마 방전 유닛에 결합된 상태에서 상기 트레이 유닛의 내부와 외부를 연통시키는 연통 유로가 형성되며,상기 챔버의 공기가 외부로 배출되는 과정에서 상기 트레이 유닛 내의 공기도 상기 연통 유로를 통해 배출되어서, 상기 트레이 유닛의 내부에 플라즈마 방전이 용이한 진공 상태가 형성되는,플라즈마를 이용한 종자 처리 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

561/1059 Row 561: application_number: 1020200042302, combined_string: invention_title: 러그컨베이어의 높이 조절이 가능한 구근류 채굴장치 abstract: 본 발명은 러그컨베이어의 높이 조절이 가능한 구근류 채굴장치에 관한 것으로, 작업 차량의 프레임에 회전가능하게 구비되어 두둑에서 채굴된 작물을 이송시키며 흙을 털어내는 제토컨베이어와, 제토컨베어와 같이 회전되게 구비되어 제토컨베이어에 의해 이송되는 작물을 받쳐 낙하를 방지하는 러그컨베이어를 포함하는 채굴유닛을 갖는 구근류 채굴장치로서, 프레임에 고정되는 한편 일측에는 복수의 고정공이 형성돼 있는 고정브라켓이 구비되고, 일측 단부가 고정브라켓에 회전가능하게 결합되는 한편 타측 단부는 러그컨베이어에 연결되고, 그 표면에는 고정공과 체결부재로 결합되는 복수의 결합공이 형성돼 있는 힌지브라켓이 구비되어, 힌지브라켓이 고정브라켓 상에서 회전됨에 따라 러그컨베이어가 상하로 이동되게 구비되는 구근류 채굴장치를 제공한다. claims: 작업 차량의 프레임에 회전가능하게 구비되어 두둑에서 채굴된 작물을 이송시키며 흙을 털어내는 제토컨베이어와, 제토컨베어와 같이 회전되게 구비되어 제토컨베이어에 의해 이송되는 작물을 받쳐 낙하를 방지하는 러그컨베이어를 포함하는 채굴유닛을 갖는 구근류 채굴장치로서, 프레임에 고정되는 한편 일측에는 복수의 고정공이 형성돼 있는 고정브라켓이 구비되고, 일측 단부가 고정브라켓에 회전가능하게 결합되는 한편 타측 단부는 러그컨베이어에 연결되고, 그 표면에는 고정공과 체결부재로 결합되는 복수의 결합공이 형성돼 있는 힌지브라켓이 구비되어, 힌지브라켓이 고정브라켓 상에서 회전됨에 따라 러그컨베이어가 제토컨베이어의 전면에서 러그컨베이어의 길이방향으로 상하 이동되게 구비되는 구근류 채굴장치., Ltext: 농업, prediction: 임업
562/1059 Row 562: application_number: 1020200032500, combined_string: invention_title: 발효 미생물의 분리, 동정, 종균 관리 및 배양 대행서비스 abstract: 본 발명은 발효 미생물의 분리, 동정, 종균 관리 및 배양 대행서비스에 관한 것으로, 더욱 상세하게는 인터넷을 사용하여 업체 담당자가 전문 연구원과 발효 미생물의 분리, 동정, 종균 관리 및 배양에 대하여 실시간으로 비대면 상담을 실시하고 균주증식 및 관리를 도와 발효생산에 대한 중소기업 기술 지원 및 제품 개발, 그리고 품질 향상에 획기적인 도움을 제공하는 서비스이다.전통적인 자연 접종은 미생물 발효 관리를 작업자의 경험으로 실시하기 때문에, 생산단가의 개선과 품질 관리가 어렵고 이로 인해 소규모 발효 생산은 여전히 전문가에 의한 소량생산에 의존하고 있다. 발효에 사용하는 종균은 대부분 외국에서 상업화한 균을 구매하는데, 균의 관리가 미흡하여 구매한 종균을 재사용하지 못하고 일회용으로 사용하는 경우가 많으며, 종균의 증식을 하지 못해 발효 규모를 키우지 못하여 종균 구매에 지나친 비용이 들어가 원가가 상승하여 경쟁력을 갖추지 못하는 요인이 된다. 발효 생산 업체의 균주 국산화 수요가 높으나 이를 이러한 연구를 의뢰할 기관이 없으며, 종균의 증식 및 재사용을 위한 보관을 위탁 역시 불가능한 상황이다.본 발명은 새로운 비즈니스 모델을 개발하여 발효 미생물 관리 대행 웹사이트를 통해 업체 담당자가 전문 연구원과 발효 미생물의 분리, 동정, 종균 관리 및 배양에 대하여 실시간으로 비대면 상담을 실시하고 균주증식 및 관리를 도와 발효생산에 대한 중소기업 기술 지원 및 제품 개발, 그리고 품질 향상에 획기적인 도움을 제공할 수 있다. claims: 발효 미생물의 분리, 동정, 종균 관리 및 증식 대행 서비스, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

563/1059 Row 563: application_number: 1020200030255, combined_string: invention_title: 사계절 모종 채소 재배기 abstract: 본 발명의 목적은 채소 및 특용작물 그리고 꽃 등의 제반 농작물 등의 어린 식물을 소규모로 효과적으로 재배할 수 있고, 필요에 따라 재배 장소를 이동시킨 후, 그 이동된 위치에서 고정시킬 수 있게 함으로서 농작물 재배를 위한 재배 장소에 구애됨이 없이 간편히 재배할 수 있는 사계절 모종 채소 재배기를 제공한다. 이러한 본 본 발명은, 사계절 모종 채소 재배기로서, 재배기의 바닥을 형성하도록 설치되는 소정 면적을 갖는 베이스부; 상기 베이스부의 테두리를 따라 세워지게 설치되어 재배기의 골조를 형성하는 골조부; 및 상기 골조부를 덮도록 상기 골조부에 탈부착 가능하게 설치되는 비닐부;를 포함하고, 상기 베이스부는: 하부로부터 방수합판, 스치로폼, 전기패널 및 냉난방패널이 순차적으로 적층 설치되는 것이 바람직하다. claims: 사계절 모종 채소 재배기에 있어서, 재배기의 바닥을 형성하도록 설치되는 소정 면적을 갖는 베이스부; 상기 베이스부의 테두리를 따라 세워지게 설치되어 재배기의 골조를 형성하는 골조부; 및 상기 골조부를 덮도록 상기 골조부에 탈부착 가능하게 설치되는 비닐부;를 포함하고, 상기 베이스부는: 하부로부터 방수합판, 스치로폼, 전기패널 및 냉난방패널이 순차적으로 적층 설치되는 것을 특징으로 하는 사계절 모종 채소 재배기., Ltext: 농업, prediction: 농업
564/1059 Row 564: application_number: 1020217031148, combined_string: invention_title: 체리모야의 종자 추출물 abstract: 본 발명은 일반적으로 화장품 분야에 관한 것이다. 더욱 구체적으로, 본 발명은 체리모야(Annona cherimola) 식물의 종자 추출물을 포함하는 피부 관리 미용 조성물에 관한 것이다. 본 발명은 이러한 종자 추출물이 피부에 몇가지 이로운 효과를 갖는다는 발견에 기초한다. 이러한 효과로는 체리모야의 종자 추출물이 진정, 완화, 보습 및 가려움 방지 효과를 들 수 있다. 또 다른 측면에서, 본 발명은 따라서, 본 발명의 피부 관리 조성물을 투여하는 것을 포함하는, 대상체에서 피부 외관을 개선시키거나 피부 건조를 감소시키는 방법을 제공한다. 또 다른 측면에서, 본 발명은 본 발명의 피부 관리 조성물을 투여하는 것을 포함하는, 대상체의 자극받은 피부를 진정시키거나(soothing) 자극을 완화하는(calming) 미용 방법을 제공한다. 본 발명은 또한 피부 관리, 특히 자극받은 피부를 진정시키거나 자극을 완화하거나 피부 외양을 개선하거나 피부 건조 및 가려움증을 감소시키기 위한 체리모야의 종자 추출물의 용도에 관한 것이다. claims: 체리모야(Annona cherimola) 식물의 종자 추출물을 포함하는 피부 관리 미용 조성물.대상체에서 피부 외양을 개선하거나 피부 가려움증을 감소시키는 미용 방법으로서, 제1항 내지 제10항 중 어느 하나의 항의 조성물을 상기 대상체의 피부에 투여하는 것을 포함하는, 미용 방법.대상체에서 자극받은 피부를 진정시키거나 자극을 완화하는 미용 방법으로서, 제1항 내지 제10항 중 어느 하나의 항의 조성물을 상기 대상체의 피부에 투여하는 것을 포함하는, 미용 방법.미용 피부 관리를 위한, 제1항 내지 제10항 중 어느 하나의 항의 조성물의 용도.자극받은 피부의 진정, 자극 받은 피부의 자극 완화, 피부 외양 개선 및/또는 피부 건조 감소를 위한, 제1항 내지 제10항 중 어느 하나의 항의 조성물의 용도., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

565/1059 Row 565: application_number: 1020200022611, combined_string: invention_title: 구근류 분류장치 abstract: 본 발명은 제1베이스 프레임; 상기 제1베이스 프레임에 고정되는 구근류 이송부; 상기 구근류 이송부 하부의 제1영역에 위치하고, 상기 구근류 이송부에서 낙하된 제1크기의 제1구근류를 제1측 방향으로 배출하기 위한 제1가이드판; 및 상기 구근류 이송부 하부의 제2영역에 위치하고, 상기 구근류 이송부에서 낙하된 제2크기의 제2구근류를 제2측 방향으로 배출하기 위한 제2가이드판을 포함하는 구근류 분류장치에 관한 것으로, 구근류의 채굴과 동시에 이를 크기별로 분류할 수 있는 구근류 분류장치를 제공할 수 있다. claims: 제1베이스 프레임; 및상기 제1베이스 프레임에 고정되는 구근류 이송부를 포함하고,상기 구근류 이송부는, 제1이송부를 포함하고,상기 제1이송부는, 제1-1이송가이드부; 및 상기 제1-1이송가이드부와 일정 간격 이격하여 배치되는 제1-2이송가이드부를 포함하며,상기 제1이송부는, 상기 제1-1이송가이드부에 배치되는 제1-1지지부; 및 상기 제1-2이송가이드부에 배치되는 제1-2지지부를 더 포함하는 구근류 분류장치., Ltext: 농업, prediction: 임업
566/1059 Row 566: application_number: 1020200018281, combined_string: invention_title: 식물 재배장치 abstract: 본 발명은 종자의 발아는 물론이고 발아된 식물을 한번에 대량으로 재배할 수 있고, 복수개의 층에 각각에서 다수개의 재배판을 용이하게 입출시킬 수 있는 식물 재배장치에 관한 것으로, 종자 또는 식물이 수용되는 재배판(20)이 다수개 수용되어 재배되도록 형성된 재배기본체(10)와, 상기 재배기본체(10) 내부에 다수개의 프레임이 종횡 방향으로 골조를 이루도록 설치되어 복수개의 열을 형성하고, 그 복수개의 열 각각에는 양측 내벽면에 상기 재배판(20)의 양측 하면이 지지된 채로 입출되도록 이동을 안내하는 재배판지지프레임(31)이 다층 구조를 이루도록 설치되며, 각 층에는 상기 재배판(20)이 동일선상에 2개 이상 순차적으로 인입되어 일렬로 배치되도록 재배판인입공간(33)이 형성된 선반(30)과, 상기 재배기본체(10)의 내부 일측에 설치된 물저장탱크(50)로부터 공급받은 물을 상기 재배판(20)의 상면에 분사하도록 형성된 물분사유닛(40)을 포함하고, 상기 선반(30)은 종자를 발아시키기 위한 발아영역(35)과 발아된 식물을 성장시키기 위한 재배영역(36)이 각각 하나 이상 구비되도록 형성되어지되, 상기 발아영역(35)에 형성된 각 재배판지지프레임(31)의 설치높이 간격은 재배영역(36)에 형성된 각각의 재배판지지프레임(31)의 설치높이 간격에 비해 좁게 형성한 것을 특징으로 한다. claims: 종자 또는 식물이 수용되는 재배판(20)이 다수개 수용되어 재배되도록 형성된 재배기본체(10);상기 재배기본체(10) 내부에 다수개의 프레임이 종횡 방향으로 골조를 이루도록 설치되어 복수개의 열을 형성하고, 그 복수개의 열 각각에는 양측 내벽면에 상기 재배판(20)의 양측 하면이 지지된 채로 입출되도록 이동을 안내하는 재배판지지프레임(31)이 다층 구조를 이루도록 설치되며, 각 층에는 상기 재배판(20)이 동일선상에 2개 이상 순차적으로 인입되어 일렬로 배치되도록 재배판인입공간(33)이 형성된 선반(30);상기 재배기본체(10)의 내부 일측에 설치된 물저장탱크(50)로부터 공급받은 물을 상기 재배판(20)의 상면에 분사하도록 형성된 물분사유닛(40);을 포함하고,상기 선반(30)은 종자를 발아시키기 위한 발아영역(35)과 발아된 식물을 성장시키기 위한 재배영역(36)이 각각 하나 이상 구비되도록 형성되어지되, 상기 발아영역(35)에 형성된 각 재배판지지프레임(31)의 설치높이 간격은 재배영역(36)에 형성된 각각의 재배판지지프레임(31)의 설치높이 간격에 비해 좁게 형성된 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

567/1059 Row 567: application_number: 1020200018312, combined_string: invention_title: 고기능성 인삼 속성재배 장치 abstract: 본 발명은 고기능성 인삼 속성재배 장치에 관한 것으로, 뚜껑을 이용하여 밀폐되는 재배조 내에 인삼 씨앗 또는 묘삼을 정식하고, 인삼이 특이점을 가지는 각 생장 기간마다 환경 조건을 다르게 제공함으로써, 인삼이 속성으로 생장할 수 있도록 하는 효과가 있다. claims: 인삼 속성재배 장치로서,인삼 씨앗 또는 묘삼이 정식되는 토양이 수용되는 재배조로서, 상부가 개방되어 있고 상기 토양의 온도를 조절하기 위해 상기 토양에 접하도록 배치된 온도조절 모듈을 포함하는 것인, 재배조;상기 재배조의 상부를 덮어 밀폐 공간을 형성하도록 상기 재배조에 결합 가능한 제1뚜껑으로서, 상기 인삼 씨앗 또는 상기 묘삼에 광을 조사하기 위한 발광 모듈이 장착된 제1뚜껑;상기 재배조의 상부를 덮어 밀폐 공간을 형성하도록 상기 재배조에 결합 가능한 제2뚜껑; 및상기 인삼 속성재배 장치를 제어하는 제어 모듈로서, 상기 재배조에 상기 제1뚜껑이 결합되면 상기 발광 모듈이 발광하도록 제어하고 상기 토양이 제1온도를 유지하도록 상기 온도조절 모듈을 제어하고, 상기 제2뚜껑이 결합되면 상기 토양이 상기 제1온도보다 낮은 제2온도를 유지하도록 상기 온도조절 모듈을 제어하는 것인, 제어 모듈을 포함하는, 인삼 속성재배 장치.뚜껑의 변경없이 인삼을 속성으로 재배하기 위한 장치로서,인삼 씨앗 또는 묘삼이 정식되는 토양이 수용되는 재배조로서, 상부가 개방되어 있고 상기 토양의 온도를 조절하기 위해 상기 토양에 접하도록 배치된 온도조절 모듈을 포함하는 것인, 재배조;상기 재배조의 상부를 덮어 밀폐 공간을 형성하도록 상기 재배조에 결합 가능한 뚜껑으로서, 상기 인삼 씨앗 또는 상기 묘삼에 광을 조사하기 위한 발광 모듈이 장착된 뚜껑;상기 인삼 속성재배 장치를 제어하는 제어 모듈로서, 상기 재배조에 상기 뚜껑이 결합되면 상기 토양이 제1온도를 유지하도록 상기 온도조절 모듈을 제어하는 제어 모듈을 포함하고,상기 제어 모듈은,상기 재배조에 상기 뚜껑이 결합되면 상기 발광 모듈이 백색광을 발광하도록 제어하는 것을 특징으로 하는, 인삼 속성재배 장치., Ltext: 농업, prediction: 임업
568/1059 Row 568: application_number: 1020200016750, combined_string: invention_title: 식물재배용 팩 및 그 제조방법 abstract: 본 발명은 부직포와 부직포 내측면에 고정되는 흡수포가 원통형으로 길게 구성되고 그 내부에 부엽토가 충전되어 뿌리로 양분을 공급하며, 간편하게 사용할 수 있도록 특정 식물의 씨앗이 휴면 상태로 파종되어 있어 발아(germination) 조건이나 발아 환경이 제공되면 발아 및 생육되도록 한 식물재배용 팩 및 그 제조방법에 관한 것으로, 길이가 긴 원통형 부직포(2)와, 부직포 내측면에 고정되는 흡수포(3)와, 부직포의 양측면에 고정되는 측부재(8)(9)와, 부직포(2) 내부에 충전되는 부엽토(10)와, 부직포(2)와 흡수포(3)의 길이 방향으로 위치에 소정 간격으로 형성되는 복수의 재배공(4)(5)과, 부직포(2)와 흡수포(3)에 사이에 고정되는 소정 폭의 씨앗고정봉지(7)와, 씨앗고정봉지(7)에 적어도 하나 이상 포장되고 부직포의 재배공(5)과 흡수포(3)의 재배공(4)(5) 사이에 위치하는 식물 씨앗(6)과, 부직포(2) 외면에 소정 폭으로 가접착되어 재배공(4)(5)을 막는 테이프(11)를 포함한다.상기 측부재(8)(9) 외면에 고정되는 소정 크기의 벨크로테이프(12)(13)를 더 포함한다. 상기 부직포(2)의 외면에 씌워 포장하는 포장지(14)를 더 포함한다. claims: 길이가 긴 자루형태의 부직포;부직포의 내측면에 고정되는 흡수포;흡수포 내부 공간에 충전되는 부엽토;부직포와 흡수포의 길이 방향 같은 위치에 소정 간격으로 형성되는 복수의 재배공;부직포와 흡수포 사이에 고정되는 소정 폭의 씨앗고정봉지;씨앗고정봉지에 적어도 하나 이상 포장되고 부직포와 재배공에 형성되는 재배공과 같은 위치에 위치하는 식물 씨앗;부직포 외면에 가접착되어 부직포의 재배공을 막는 소정 폭의 테이프;를 포함하는 식물재배용 팩.a) 부직포와 흡수포를 같은 평면적으로 재단하는 단계;b) 부직포와 흡수포의 길이방향 같은 위치에 소정 크기의 재배공을 소정 간격으로 형성하는 단계;c) 적어도 1개 이상의 식물 씨앗이 부직포와 흡수포에 형성되는 재배공 간격과 같은 간격으로 포장 고정되는 씨앗고정봉지를 부직포와 흡수포 사이에 위치시키되 식물 씨앗과 재배공이 같은 위치에 위치시키는 단계;d) 부직포와 흡수포를 접합하는 단계;e) 접합된 부직포와 흡수포를 자루 형태로 접합하는 단계;f) 흡수포 내부에 부엽토를 충전하고 접합을 마무리하는 단계;g) 부직포의 재배공이 막히도록 소정 폭의 테이프로 가접착하는 단계;를 포함하는 식물재배용 팩 제조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

569/1059 Row 569: application_number: 1020200016271, combined_string: invention_title: 버섯 재배 시스템 및 버섯 재배 방법 abstract: 본 발명은 버섯 재배 시스템 및 버섯 재배 방법에 관한 것으로, 본 발명의 버섯 재배 시스템은 외부로부터 공급된 톱밥을 반입하는 프론트로더(100), 상기 프론트로더(100)를 거쳐 반입된 톱밥을 공급 받아 배지 원료를 배합하여 배지를 조제하는 배지원료배합기(200), 상기 배지원료배합기(200)에서 조제된 배지를 전달 받아 비닐에 입봉한 후 설정 온도 및 시간으로 살균하는 배지입봉살균부(300), 상기 배지입봉살균부(300)를 거쳐 살균된 배지를 전달 받아 설정 온도까지 배지를 자연 냉각시키는 냉각실(400), 상기 냉각실(400)을 거쳐 자연 냉각된 배지를 전달 받아 종균을 접종하며, 종균이 접종된 배지를 배양하는 종균접종배양부(500), 상기 종균접종배양부(500)를 거쳐 배양된 배지를 전달 받아 비닐을 제거하는 비닐제거기(600), 상기 비닐제거기(600)를 거쳐 비닐이 제거된 배지에 밀랍을 코팅하는 밀랍코팅장치(700), 상기 밀랍코팅장치(700)를 거쳐 밀랍이 코팅된 배지를 전달 받아 보관하며, 버섯을 생육하는 버섯생육실(800), 및 상기 버섯생육실(800)에서 생육된 버섯을 수확하여 출하하는 버섯출하부(900)를 포함한다. claims: 외부로부터 공급된 톱밥을 반입하는 프론트로더(100);상기 프론트로더(100)를 거쳐 반입된 톱밥을 공급 받아 배지 원료를 배합하여 배지를 조제하는 배지원료배합기(200);상기 배지원료배합기(200)에서 조제된 배지를 전달 받아 비닐에 입봉한 후 설정 온도 및 시간으로 살균하는 배지입봉살균부(300);상기 배지입봉살균부(300)를 거쳐 살균된 배지를 전달 받아 설정 온도까지 배지를 자연 냉각시키는 냉각실(400);상기 냉각실(400)을 거쳐 자연 냉각된 배지를 전달 받아 종균을 접종하며, 종균이 접종된 배지를 배양하는 종균접종배양부(500);상기 종균접종배양부(500)를 거쳐 배양된 배지를 전달 받아 비닐을 제거하는 비닐제거기(600);상기 비닐제거기(600)를 거쳐 비닐이 제거된 배지에 밀랍을 코팅하는 밀랍코팅장치(700);상기 밀랍코팅장치(700)를 거쳐 밀랍이 코팅된 배지를 전달 받아 보관하며, 버섯을 생육하는 버섯생육실(800); 및상기 버섯생육실(800)에서 생육된 버섯을 수확하여 출하하는 버섯출하부(900);를 포함하는 버섯 재배 시스템. 제1항 내지 제9항 중 어느 한 항의 버섯 재배 시스템을 이용한 버섯 재배 방법으로서, 상기 프론트로더(100)에서 외부로부터 공급된 톱밥을 반입하는 단계;상기 배지원료배합기(200)에서 상기 프론트로더(100)를 거쳐 반입된 톱밥을 공급 받아 배지 원료를 배합하여 배지를 조제하는 단계;상기 배지입봉살균부(300)에서 상기 배지원료배합기(200)로부터 조제된 배지를 전달 받아 비닐에 입봉한 후 설정 온도 및 시간으로 살균하는 단계;상기 냉각실(400)에서 상기 배지입봉살균부(300)를 거쳐 살균된 배지를 전달 받아 설정 온도까지 배지를 자연 냉각시키는 단계;상기 종균접종배양부(500)에서 상기 냉각실(400)을 거쳐 자연 냉각된 배지를 전달 받아 종균을 접종하며, 종균이 접종된 배지를 배양하는 단계;상기 비닐제거기(600)에서 상기 종균접종배양부(500)를 거쳐 배양된 배지를 전달 받아 비닐을 제거하는 단계;상기 밀랍코팅장치(700)에서 상기 비닐제거기(600)를 거쳐 비닐이 제거된 배지에 밀랍을 코팅하는 단계; 및상기 버섯생육실(800)에서 상기 밀랍코팅장치(700)를 거쳐 밀랍이 코팅된 배지를 전달 받아 보관하며, 버섯을 생육하는 단계;를 포함하는 버섯 재배 방법., Ltext: 농업, prediction: 임업
570/1059 Row 570: application_number: 1020200003783, combined_string: invention_title: 묘목 생장용 전용포트 및 그 전용포트를 이용한 묘목 생장 방법 abstract: 본 발명은 보관의 편익을 제공하면서 수차례 재사용이 용이함은 물론, 환경이 다른 노지에서 성장이 멈추거나 주춤하지 않고 왕성한 발육이 되도록 하는 묘목 생장용 전용포트 및 그 전용포트를 이용한 묘목 생장 방법에 관한 것으로,전용포트를 이용한 묘목 생장 방법은 바닥면(10)을 구비하면서 바닥면의 상측으로 원형 또는 다각형 형상의 벽면(20)이 바닥면과 일체형으로 형성되어 내부 수용공간(30)을 형성하며, 원터치에 의해 결합이 용이하도록 벽면의 접합면(60)에 각각 형성되는 결합돌기(41)와 결합홈(42) 또는 접합면(60)의 플랜지(43)와 볼트/너트(44) 중 선택된 어느 하나로 구성되는 고정수단(40)에 의해 분리 및 결합 고정이 용이한 좌, 우 대칭구조로 구성되되, 상기 바닥면(10)과 벽면(20)에는 수분과 영양분이 유입되도록 하는 유입홈(50)이 다수 개 형성된 전용포트(S)의 수용공간(30)에 토양을 채우는 토양 채움 단계(S100)와, 상기 수용공간(30)의 내부에 채워진 토양에 묘목용 씨앗을 파종하는 씨앗파종단계(S200)와, 상기 씨앗 파종 후 1 내지 3년 생장을 시킨 다음, 전용포트(S)의 고정수단(40)을 해체하여 좌, 우로 분리 후 노지에 옮겨심기를 하고, 재사용을 위해 수거를 하는 분리/수거단계(S300)로 구성된다. claims: 바닥면(10)을 구비하면서 바닥면의 상측으로 원형 또는 다각형 형상의 벽면(20)이 바닥면과 일체형으로 형성되어 내부 수용공간(30)을 형성하며, 고정수단(40)에 의해 분리 및 결합 고정이 용이하도록 좌, 우 대칭구조로 구성되되, 상기 바닥면(10)과 벽면(20)에는 수분과 영양분이 유입되는 유입홈(50)이 다수 개 형성되는 것을 특징으로 하는 묘목 생장용 전용포트.전용포트를 이용한 묘목 생장 방법은 바닥면(10)을 구비하면서 바닥면의 상측으로 원형 또는 다각형 형상의 벽면(20)이 바닥면과 일체형으로 형성되어 내부 수용공간(30)을 형성하며, 원터치에 의해 결합이 용이하도록 벽면의 접합면(60)에 각각 형성되는 결합돌기(41)와 결합홈(42) 또는 접합면(60)의 플랜지(43)와 볼트/너트(44) 중 선택된 어느 하나로 구성되는 고정수단(40)에 의해 분리 및 결합 고정이 용이한 좌, 우 대칭구조로 구성되되, 상기 바닥면(10)과 벽면(20)에는 수분과 영양분이 유입되도록 하는 유입홈(50)이 다수 개 형성된 전용포트(S)의 수용공간(30)에 토양을 채우는 토양 채움 단계(S100); 와,상기 수용공간(30)의 내부에 채워진 토양에 묘목용 씨앗을 파종하는 씨앗파종단계(S200); 와,상기 씨앗 파종 후 1 내지 3년 생장을 시킨 다음, 전용포트(S)의 고정수단(40)을 해체하여 좌, 우로 분리 후 노지에 옮겨심기를 하고, 재사용을 위해 수거를 하는 분리/수거단계(S300);로 구성되는 것을 특징으로 하는 묘목 생장용 전용포트를 이용한 묘목 생장 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

571/1059 Row 571: application_number: 1020190178590, combined_string: invention_title: 식물 종자의 초기 발아속도 증진용 조성물 및 식물 종자의 초기 발아속도를 증진시키는 방법 abstract: 본 발명은 식물 종자의 크기 증진용 조성물, 식물 종자의 크기를 증진시키는 방법, 식물 종자의 초기 발아속도 증진용 조성물 및 식물 종자의 초기 발아속도를 증진시키는 방법에 관한 것으로서, 상기 pPLAIIIα 유전자가 과발현되면 식물 종자의 크기가 커지고 초기 발아속도가 증진되므로, 이를 효과적으로 식물의 생산성 증대 방법으로 이용할 수 있다. claims: 서열번호 1로 표시되는 아미노산 서열을 갖는 pPLAIIIα(Patatin-related phospholipase A) 단백질 또는 pPLAIIIα 단백질을 코딩하는 핵산 서열을 포함하는 식물 종자의 초기 발아속도 증진용 조성물.서열번호 1로 표시되는 아미노산 서열을 갖는 pPLAIIIα(Patatin-related phospholipase A) 단백질을 코딩하는 핵산 서열의 발현을 증가시키는 조절 단계를 포함하는 식물 종자의 초기 발아속도를 증진시키는 방법., Ltext: 농업, prediction: 농업
572/1059 Row 572: application_number: 1020190171001, combined_string: invention_title: 냉각시스템을 이용한 딸기육묘방법 abstract: 본 발명에 따른 냉각시스템을 이용한 딸기육묘방법은, 기존의 비닐하우스와 같은 장소에서소 실현이 가능하게 되어 고가의 설비가 필요없으면서도 딸기의 꽃눈이 빠르게 분화되게 하기 위하여 딸기의 모주(어미묘)를 정식하고 런너(자묘)의 발생을 촉진하여 자묘를 유인하고 개별 또는 연결포트에 상포를 넣고 뿌리발근을 한후에 40일 ~ 60일간의 생장관리 후에 약 15일 ~ 30일간의 암막/저온처리(16시에서 다음날 10시까지 8 ~ 15℃ 여름기간인 7월 8월 동안의 처리)를 수행하고, 이를 다시 정상적인 처리인 주간 25 ~ 30℃ 로 15일 ~ 30일 정도의 생장처리를 수행하여 딸끼의 조속한 생장을 촉진시켜 조속한 출하를 가능하게 하고 시기적으로 딸기의 2모작이 가능하게 되어 농가소득이 증대되는 것이 가능하다 claims: 냉각시스템을 이용한 딸기육묘방법에 있어서, 상기 냉각시스템을 이용한 딸기육묘방법은, 하우스본체(1)의 상부에 빛이 투광되지 않은 암실커튼(2)이 배치되고, 상기 암실커튼(2)을 작동시키는 구동모터(3)가 하우스본체(1)의 상부에 배치되어 상기 암실커튼(2)을 승강구동시키는 구조를 갖고, 상기 하우스본체(1)의 내부에는 냉각시스템(4)이 설치되어 상기 냉각시스템(4)이 하우스본체(1)의 내부의 온도를 16시에서 다음날 10시까지의 8℃~ 16℃의 저온으로 유지시키는 구조를 갖으며,딸기의 꽃눈이 빠르게 분화되게 하기 위하여 딸기의 모주(어미묘)를 정식하는 단계와, 상기 딸기의 모주에서 런너(자묘)의 발생을 촉진하여 자묘를 유인하고 개별포트 또는 서로 연결된 연결포트에 상토를 넣고 뿌리발근 및 발아 준비를 시키는 뿌리발근 및 발아 준비단계와, 상기 뿌리발근 및 발아 준비단계 후에 주간 25 ~ 30℃ 로 40일 ~ 60일간의 생장관리를 수행하여 뿌리발근과 발아되는 딸기육묘성장단계와, 상기 딸기육묘성장단계 후에 15일 ~ 30일간의 16시에서 다음날 10시까지 암막커튼처리하고 16시에서 다음날 10시까지 8 ~ 15℃ 여름기간인 7월 8월 동안의 야간냉온 처리를 수행하여 꽃눈형성을 촉진시키는 단일야냉처리단계와, 상기 단일야냉처리후에 정상적인 처리인 주간 25 ~ 30℃ 로 15일 ~ 60일의 기간에 수정 및 착과후 딸기의 생장이 완료되는 정상생장처리단계를 포함하는 것을 특징으로 하는 냉각시스템을 이용한 딸기육묘방법, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

573/1059 Row 573: application_number: 1020190167428, combined_string: invention_title: 식물 재배용 트레이 abstract: 본 발명은 식물 재배용 트레이에 관한 것으로서, 씨앗이 수납된 복수의 씨앗캡슐이 마련되는 씨앗캡슐용 키트 및 씨앗이 발아한 모종판이 마련되는 새싹재배용 키트가 선택적으로 착탈되는 하나 이상의 키트 착탈부를 갖는 트레이 본체; 및 상기 트레이 본체가 분리가능하게 안착되는 베이스를 포함하는 것을 특징으로 한다. claims: 씨앗이 수납된 복수의 씨앗캡슐이 마련되는 씨앗캡슐용 키트 및 씨앗이 발아한 모종판이 마련되는 새싹재배용 키트가 선택적으로 착탈되는 하나 이상의 키트 착탈부를 갖는 트레이 본체; 및상기 트레이 본체가 분리가능하게 안착되는 베이스를 포함하는, 식물 재배용 트레이., Ltext: 농업, prediction: 농업
574/1059 Row 574: application_number: 1020190167429, combined_string: invention_title: 씨앗캡슐 abstract: 본 발명은 씨앗캡슐에 관한 것으로서, 씨앗이 수납된 배지를 수용하는 수용부와, 상기 수용부와 연통하며 상기 배지가 인출입하는 인출입구를 형성하는 캡슐 본체; 상기 배지로부터 생장된 식물이 통과하는 통과공을 형성하고, 상기 인출입구를 통해 노출되는 상기 배지를 커버하며 상기 인출입구에 착탈가능하게 결합되는 캡; 및 상기 수용부에 마련되어, 상기 배양액의 유동을 안내하며 상기 배양액을 상기 배지에 균등하게 공급하는 배양액 공급 가이드를 포함하는 것을 특징으로 한다. claims: 씨앗이 수납된 배지를 수용하는 수용부와, 상기 수용부와 연통하며 상기 배지가 인출입하는 인출입구를 형성하는 캡슐 본체;상기 배지로부터 생장된 식물이 통과하는 통과공을 형성하고, 상기 인출입구를 통해 노출되는 상기 배지를 커버하며 상기 인출입구에 착탈가능하게 결합되는 캡; 및상기 수용부에 마련되어, 상기 배양액의 유동을 안내하며 상기 배양액을 상기 배지에 균등하게 공급하는 배양액 공급 가이드를 포함하는, 씨앗캡슐., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

575/1059 Row 575: application_number: 1020190167850, combined_string: invention_title: 딸기 조기 생산을 위한 육묘 방법 abstract: 본 발명은, 딸기 조기 생산을 위한 육묘 방법에 관한 것으로, 본 발명의 일 실시예에 따른 딸기 조기 생산을 위한 육묘 방법은, 딸기의 자묘를 생육하여 런너 발생 환경을 제공하는 단계; 상기 런너가 발생한 자묘를 일시 채묘한 후 육모판에 삽식하는 단계; 및 상기 삽식된 자묘에 화아 분화 환경을 제공하는 단계;를 포함한다. claims: 딸기의 자묘를 생육하여 런너 발생 환경을 제공하는 단계; 상기 런너가 발생한 자묘를 일시 채묘한 후 육모판에 삽식하는 단계; 및상기 삽식된 자묘에 화아 분화 환경을 제공하는 단계;를 포함하는,딸기 조기 생산을 위한 육묘 방법., Ltext: 농업, prediction: 임업
576/1059 Row 576: application_number: 1020190166962, combined_string: invention_title: 씨앗 복원성을 갖는 저온건조방법 abstract: 본 발명은 진공실 내에 씨앗을 진공 및 냉각 처리하는 단계; 및 상기 진공실에서 냉각된 씨앗에 원적외선을 조사하는 단계;를 포함하는 것인, 씨앗건조방법에 관한 것으로, 종래보다 저 비용으로 씨앗 복원을 제공하는 효과, 씨앗의 복원성 향상 및 씨앗 보관 기간 동안 소요비용이 들지 않는 효과를 제공할 수 있다. claims: 진공실에서 씨앗을 진공상태를 유지하고 냉각 처리하는 단계; 상기 냉각된 씨앗에 원적외선을 조사하는 단계; 및상기 씨앗을 건조시키는 단계;를 포함하는, 복원력이 향상된 씨앗건조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

577/1059 Row 577: application_number: 1020190164368, combined_string: invention_title: 자란의 종자 발아율 및 배비대율을 증가시키는 방법 abstract: 본 발명은 자란(Bletilla striata)의 종자 발아율 및 배비대율을 증가시키는 방법에 관한 것으로, 자란의 종자활력, 발아 및 배비대에 영향을 미치는 차아염소산나트륨의 최적 처리조건을 확립함으로써, 향후 희귀식물인 자란의 개체증식과 복원에 매우 유용하게 활용될 수 있다. claims: 표면 살균한 자란 속(Bletilla sp.) 식물의 종자에 차아염소산나트륨(sodium hypochlorite)을 처리하는 단계를 포함하는 자란 속 식물의 종자 발아율 및 배비대율을 증가시키는 방법., Ltext: 농업, prediction: 임업
578/1059 Row 578: application_number: 1020190163019, combined_string: invention_title: 고추 묘목 건조 스트레스 경감용 트라이코더마 속 GL02 곰팡이 및 이의 용도 abstract: 본 발명은 식물의 발아율 증가 및 식물의 건조 스트레스 저감 효과를 가지는 트라이코더마 속(Trichoderma sp.) GL02 곰팡이, 상기 곰팡이의 배양액 또는 이들의 혼합물을 유효성분으로 포함하는 미생물 제제 및 이를 이용한 식물 종자의 발아율 증가 방법과 식물의 건조 스트레스 저감 방법에 관한 것이다. claims: 서열번호 1로 표시되는 ITS 염기서열을 갖는 식물 종자의 발아율 증가 및 식물의 건조 스트레스 저감용 트라이코더마 브레비컴팩텀(Trichodermabrevicompactum) GL02 곰팡이(KACC 93331P).제1항 또는 제2 항에 따른 곰팡이, 상기 곰팡이의 배양액 또는 이들의 혼합물 중 적어도 하나를 유효성분으로 포함하는 미생물 제제.제8 항에 따른 미생물 제제 중 적어도 하나를 식물, 식물 주변 영역, 또는 이들 모두에 처리하는 단계를 포함하는 식물 종자의 발아율 증가 방법.제1 항에 따른 곰팡이, 상기 곰팡이의 배양액 중 적어도 하나 이상을 고추, 고추 묘목 주변 영역, 또는 이들 모두에 처리하는 단계를 포함하는 고추의 건조 스트레스 저감 방법.제7 항에 따른 미생물 제제 중 적어도 하나 이상을 고추, 고추 묘목 주변 영역, 또는 이들 모두에 처리하는 단계를 포함하는 고추의 건조 스트레스 저감 방법.제8 항에 따른 미생물 제제 중 적어도 하나 이상을 고추, 고추 묘목 주변 영역, 또는 이들 모두에 처리하는 단계를 포함하는 고추의 건조 스트레스 저감 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

579/1059 Row 579: application_number: 1020190152442, combined_string: invention_title: LED 조명을 이용한 육묘 및 재배 장치 및 이를 이용한 육묘 및 재배 방법 abstract: 본 발명은 식물의 발아, 육묘 및 재배를 한꺼번에 수행하는 것이 가능하다. 보다 상세하게는 발아육묘실과 재배실이 인접하게 배치되고, 상기 발아육묘실 및 재배실 각각에 배양액을 공급하는 것이 가능하며, 잔여 배양액을 회수하여 재사용하는 것이 가능한 재배 장치에 관한 것이다. claims: 서랍형태의 구조로 단일 또는 복수의 층을 구성하며, 식물을 발아 및 육묘하는 제1 육묘트레이, 제1 육묘트레이 손잡이, 배양액을 공급하는 배양액 공급호스, 배양액을 배액하는 배액장치 및 상기 배액장치에서 배액되는 배양액을 운반하는 배액파이프가 구비된 발아육묘실;상기 발아육묘실과 인접하게 배치되고, 단일 또는 복수의 층을 구성하며, 식물이 정식되는 제2 육묘트레이 및 상기 제2 육묘트레이가 장착될 수 있는 장착부를 구비한 재배실;상기 발아육묘실에 광을 제공하는 제1 광원부 및 상기 재배실에 광을 제공하는 제 2광원부; 상기 제1 육묘트레이 및 상기 제2 육묘트레이의 근권부 중 적어도 하나에 상기 배양액을 제공하는 배양액 제공부; 및잔여 배양액을 회수하여 상기 배양액 제공부로 보내는 배양액 회수부;를 포함하는 식물의 육묘 및 재배 장치.식물의 육묘 및 재배 장치를 이용한 식물의 발아 및 육묘 방법에 있어서,발아육묘실 내의 제1 육묘트레이에 상기 식물의 씨를 심는 단계;제1 광원부가 상기 제1 육묘트레이에 광을 제공하는 단계;스위치 온 오프 여부에 따라, 배양액 제공부가 상기 제1 육묘트레이에 배양액을 주입하는 방식으로 상기 배양액을 제공하는 단계;상기 제1 육묘트레이에 과잉 주입된 상기 배양액이 배액장치를 통해 배양액 회수부로 회수되어 상기 배양액 제공부로 보내지는 단계; 및상기 배양액 제공부에서 다시 상기 제1 육묘트레이에 상기 배양액을 주입하는 방식으로 상기 배양액을 제공하는 단계를 포함하는 식물의 발아 및 육묘 방법.식물의 육묘 및 재배 장치를 이용한 식물의 재배 방법에 있어서,발아육묘실과 인접하게 배치된 재배실 내의 제2 육묘트레이에 식물을 정식하는 단계;제2 광원부가 상기 제2 육묘트레이에 광을 제공하는 단계;스위치 온 오프 여부에 따라, 배양액 제공부가 상기 제2 육묘트레이에 정식된 식물의 근권부에 배양액을 분사하는 방식으로 상기 배양액을 제공하는 단계;상기 식물의 근권부에 분사된 후, 재배실 바닥으로 떨어진 상기 배양액이 배양액 회수부로 회수되어 상기 배양액 제공부로 보내지는 단계; 및상기 배양액 제공부에서 다시 상기 제2 육묘트레이에 정식된 식물의 근권부에 상기 배양액을 분사하는 방식으로 상기 배양액을 제공하는 단계를 포함하는 식물의 재배 방법., Ltext: 농업, prediction: 임업
580/1059 Row 580: application_number: 1020190150710, combined_string: invention_title: 동절기 토마토 접목묘 육묘 장치 및 그의 재배 방법 abstract: 본 발명은 동절기 토마토 접목묘 육묘 장치 및 그의 재배 방법에 관한 것으로, 밀폐되어 내부에 공간이 마련되는 시설부; 상기 시설부 내부에 식물을 재배할 수 있는 공간이 마련되는 육묘부; 상기 시설부 내부에 마련되며, 상기 시설부 일측에서 공급되는 이산화탄소를 노즐을 통해 상기 육묘부 상부에 분사하는 공급부; 상기 육묘부 일측에 이산화탄소 농도를 측정하는 센서; 상기 센서와 연결되어, 상기 공급부를 개폐를 조절하는 밸브; 상기 시설부 내부에 마련되며 상기 육묘부 상부에 마련되는 보광부; 상기 센서의 이산화탄소 농도에 따라 상기 밸브를 동작하며, 상기 보광부의 동작을 조절하는 제어부;로 구성되는 것을 특징으로 한다. claims: 밀폐되어 내부에 공간이 마련되는 시설부;상기 시설부 내부에 식물을 재배할 수 있는 공간이 마련되는 육묘부;상기 시설부 내부에 마련되며, 상기 시설부 일측에서 공급되는 이산화탄소를 노즐을 통해 상기 육묘부 상부에 분사하는 공급부;상기 육묘부 일측에 이산화탄소 농도를 측정하는 센서;상기 센서와 연결되어, 상기 공급부를 개폐를 조절하는 밸브;상기 시설부 내부에 마련되며 상기 육묘부 상부에 마련되는 보광부;상기 센서의 이산화탄소 농도에 따라 상기 밸브를 동작하며, 상기 보광부의 동작을 조절하는 제어부;로 구성되는 것을 특징으로 하는 동절기 토마토 접목묘 육묘 장치.제 1항에 의해 제조된 동절기 토마토 접목묘 육묘 장치에 있어서,토마토 접목묘를 시설부 내부에 마련되는 육묘부에서 재배하며, 시설부 내부는 100 μmol·m-2·s-1 PPFD 광도의 메탈할라이드등으로 16시간 동안 보광하는 것을 특징으로 하는 동절기 토마토 접목묘 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

581/1059 Row 581: application_number: 1020190117936, combined_string: invention_title: 저광도의 적색 및 청색 LED를 광원으로 이용하는 마이크로튜버 감자 종자의 생산방법 abstract: 직파 가능한 마이크로튜버 감자 종자의 생산성을 높일 수 있는 방법이 제시된다. 본 발명의 방법에 따르면, 감자 줄기의 조직 배양시에 적색 및 청색 LED 광원을 혼합하여 저광도로 조사함으로써, 감자 줄기의 생육을 좋게 하고 복지형성율을 높혀 최종적으로 크기가 큰 마이크로튜버 감자 종자를 다량 생산할 수 있다. claims: (a) MS 배지를 기준으로, 질산 암모늄 함량이 800 내지 1200 mg/L 및 질산 칼륨의 함량이 3000 내지 4000 mg/L이고, 탄소원이 2 내지 4 중량%으로 조정된 배지에 무균 감자 줄기를 치상하여 LED 광원을 광량 20 내지 48 umol/m2/sec로 조사하면서 10 내지 30일 배양하여 증식 줄기를 배양하는 단계; 및(b) 증식 줄기를 커팅 후 남은 하단의 1~3 마디를 MS 배지를 기준으로, 질산 암모늄 함량이 200 내지 800 mg/L, 질산 칼륨 함량이 2500 내지 3000 mg/L이고, 탄소원이 7 내지 10 중량%로 조정된 배지에서 암조건하 70일 내지 100일 배양하는 단계를 포함하는, 마이크로튜버 감자 종자의 생산방법. 제1항의 방법에 의하여 생산된 마이크로튜버 감자 종자., Ltext: 농업, prediction: 임업
582/1059 Row 582: application_number: 1020207017253, combined_string: invention_title: 다기능 육묘장치 abstract: 본 발명은 식물 식재 재배 설비 기술분야에 관한 것으로, 상세하게는, LED 다층 식물 육묘 장치에 관한 것으로, 다품종 식물의 종묘 재배에 적용하여 수경재배, 토양재배, 기질재배 등 재배방식의 수요를 만족시키는 육묘장치에 관한 것이다. 본 발명은 고정적으로 설치된 육묘 베이스와 이동가능식 육묘 층대 차량을 포함하는 데, 상기 육묘 베이스는 하나의 프레임을 포함하고, 상기 프레임에 광원을 설치하며; 상기 이동가능식 육묘 층대 차량은 층판 프레임을 포함하고, 상기 층판 프레임에 적어도 2개의 층판을 설치하며, 상기 층판에 식재판을 설치하고, 층판 프레임 저부에 이동가능식 장치를 설치하며, 상기 층판 프레임의 층판은 육묘 베이스의 광원 위치와 매칭된다. 본 발명은 모듈화, 스마트화, 고효율과 높은 생산액에 달성할 수 있는 종묘재배를 구현하는 입체화의 다기능 스마트 육묘장치를 제공한다. claims: 고정적으로 설치된 육묘 베이스와 이동가능식 육묘 층대 차량을 포함하는 데, 상기 육묘 베이스는 하나의 프레임을 포함하고, 상기 프레임에 광원이 설치되고;상기 이동가능식 육묘 층대 차량은 층판 프레임을 포함하고, 상기 층판 프레임에 적어도 2개의 층판이 설치되고, 상기 층판에 식재판이 설치되고, 층판 프레임 저부에 이동가능식 장치가 설치되고, 상기 층판 프레임의 층판은 육묘 베이스의 광원 위치와 매칭되는 것을 특징으로 하는 다기능 육묘장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

583/1059 Row 583: application_number: 1020190097903, combined_string: invention_title: 수경 재배 장치 abstract: 두릅 또는 엄 나무의 생산을 균일하게 하기 위하여 묘목 대를 일정 기간 동안 냉동 창고에 보관한 후 18℃ 내지 20℃의 온도 및 60%의 습도로 유지된 삼중 하우스에서 물 안개를 분무하면서 재배하여 상품성이 좋은 두릅을 재배하는 수경 재배 장치가 제공된다. 수경 재배 장치는 일정 길이를 갖는 두릅 묘목 대를 다수 획득하여 일정 온도에서 일정 기간 동안 보관한 다수의 묘목 대를 수용하여 재배하는 다수의 재배 틀; 상기 다수의 재배 틀을 각각 둘러싸서 상기 지면과 사이에 작물 재배 공간을 형성하고 상호 인접하게 위치하는 다수의 기본 비닐 하우스; 상기 다수의 기본 비닐 하우스의 상부를 둘러싸는 적어도 하나의 추가 비닐 하우스; 상기 다수의 기본 비닐 하우스 각각의 상단에 일정 거리 간격으로 설치되어 상기 재배 틀에 수용된 다수의 묘목 대에 물을 안개 분무하는 다수의 제1 물 안개 분무기; 상기 다수의 재배 틀 아래 지면에 위치하여 상기 작물 재배 공간의 온도를 일정 온도로 가열하는 난방부; 및 상기 작물 재배 공간의 온도 및 습도가 일정한 범위로 유지하도록 하는 상기 다수의 제1 분무기 및 상기 난방부의 동작을 제어하는 제어부를 포함한다. claims: 일정 길이를 갖는 두릅 묘목 대를 다수 획득하여 일정 온도에서 일정 기간 동안 보관한 다수의 묘목 대를 수용하여 재배하는 다수의 재배 틀;상기 다수의 재배 틀을 각각 둘러싸서 지면과 사이에 작물 재배 공간을 형성하고 상호 인접하게 위치하는 다수의 기본 비닐 하우스; 상기 다수의 기본 비닐 하우스의 상부를 둘러싸는 적어도 하나의 추가 비닐 하우스;상기 다수의 기본 비닐 하우스 각각의 상단에 일정 거리 간격으로 설치되어 상기 재배 틀에 수용된 상기 다수의 묘목 대에 물을 안개 분무하는 다수의 제1 물 안개 분무기; 및상기 다수의 재배 틀 아래 지면에 위치하여 상기 작물 재배 공간의 온도를 일정 온도로 가열하는 난방부;상기 작물 재배 공간의 온도 및 습도가 18℃ 내지 20℃ 및 60%로 각각 유지하도록 하는 상기 다수의 제1 분무기 및 상기 난방부의 동작을 제어하는 제어부; 및1년 동안 자라 1,500mm 내지 2,000mm 길이의 묘목에서 순이 12개 내지 16개로 순 위로 절단 등분한 길이 100 mm 내지 130 mm의 묘목 대를 다수 획득하여 0℃에서 3일 내지 5일 동안 보관하는 냉동 창고를 포함하며,상기 다수의 재배 틀은 각각하단이 상기 지면에 닿고 일정 간격을 두고서 대면하는 폭 1,000mm이고 높이가 900mm인 한 쌍의 기둥;상기 한 쌍의 기둥을 덮도록 설치되어 묘목 대가 수직으로 관통하여 형성되는 그물망;상기 한 쌍의 기둥의 상단으로부터 90 mm의 아래 위치에 상기 그물망에 대해 수평으로 설치되는 철망; 및상기 철망을 덮는 부직포를 포함하며,상기 난방부는 상기 다수의 재배 틀 아래에 매설되어 내부에 난방수가 순환하는 난방 파이프; 및상기 난방 파이프를 통하여 순환하는 상기 난방수를 가열하여 순환하는 전기 보일러를 포함하는 수경 재배 장치., Ltext: 농업, prediction: 임업
584/1059 Row 584: application_number: 1020190096531, combined_string: invention_title: 모세관작용의 재배판을 가진 새싹의 제베기 abstract: 본 발명은 모세관작용의 재배판을 가진 새싹의 재배기에 관한 것으로 다수의 섬유가닥을 접합제와 함께 압착하여 일정한 두께와 넓이를 가진 판체를 새싹의 재배판으로 하고 상기 재배판에 식물의 영양소와 미생물의 살균기능이 있는 특정 양액(nutrion liqid)을 도포한 다음 재배기의 수조에 담긴 물위에 띄우고 상기 재배판에 재배할 종자를 조밀하게 파종하면 재배판의 모세작용으로 작물에 수분이 공급되어, 별도의 동력을 사용하는 수분의 공급수단이 없이, 파종한 싸앗을 새싹작물로 재배할 수 있게 된 것이다.본 발명에 의하면, 새싹의 재배기에 의해 새싹을 재배할 때 재배판에 식물의 무기질 영양소와 살균기능이 있는 양액을 도포하였기 때문에 상기 재배판에 파종된 씨앗이 청정 환경에서 양호하게 성장하여 3~4일정도 재배하면 수확이 가능하고 청정식품으로 식단에 제공할 수 있을 뿐 아니라, 식물에는 아연이나 바나듐과 같은 특정의 지표성분을 함유할 수 있어 환자의 맞춤형 보조식품으로 유용하게 제공할 수 있다. claims: 작물을 재배할 물이 담기는 수조와 덮개로 된 새싹 재배기에 있어서, 다수의 섬유가닥을 접합제와 함께 압착하여 된 일정한 두께와 넓이를 가진 판체를 새싹의 재배판으로 하고 상기 재배판을 상기 수조에 담긴 물위에 띄우고 상기 재배판 위에 씨앗을 파종하여 재배판의 모세관작용으로 수분이 공급되어 재배하게 구성된 것을 특징으로 하는 모세관작용의 재배판을 가진 새싹의 재배기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

585/1059 Row 585: application_number: 1020190094436, combined_string: invention_title: 종자 살균 장치 abstract: 본 발명은 간단한 구조에 의해 모종삼(묘삼)을 비롯한 각종 식물의 종자에 함유된 이물질을 제거하고 확실하게 살균 처리함으로써 이들 종자가 부패하는 것을 방지하고 장기간 보관이 가능하도록 한 종자 살균 장치에 관한 것이다.본 발명의 종자 살균 장치는 망상 또는 다공상의 벨트로 이루어져서 종자를 탑재한 채로 이동하는 컨베이어 벨트; 컨베이어 벨트의 종자 반입부 측에 설치되고, 세척수, 세척수와 공기 혼합물 또는 공기를 분사하여 종자에 묻은 유해 물질을 제거하는 이물질 제거부; 상온 또는 그 이상의 공기를 송풍하여 이물질 제거부를 거친 종자에 함유된 수분을 건조하는 종자 건조부 및 컨베이어 벨트의 상측 및 하측에 각각 설치되고. 종자 건조부를 거친 종자에 자외선이나 플라즈마를 조사하여 종자에 묻은 세균을 죽이는 종자 살균부를 포함하여 이루어진다.전술한 구성에서, 종자의 종류에 따라 컨베이어 벨트의 속도, 세척수나 공기의 분사 압력을 조절할 수 있다. 상기 종자는 묘삼이다. claims: 망상 또는 다공상의 벨트로 이루어져서 종자를 탑재한 채로 이동하는 컨베이어 벨트;컨베이어 벨트의 종자 반입부 측에 설치되고, 세척수, 세척수와 공기 혼합물 또는 공기를 분사하여 종자에 묻은 유해 물질을 제거하는 이물질 제거부;상온 또는 그 이상의 공기를 송풍하여 이물질 제거부를 거친 종자에 함유된 수분을 건조하는 종자 건조부 및컨베이어 벨트의 상측 및 하측에 각각 설치되고. 종자 건조부를 거친 종자에 자외선이나 플라즈마를 조사하여 종자에 묻은 세균을 죽이는 종자 살균부를 포함하여 이루어진 종자 살균 장치., Ltext: 농업, prediction: 임업
586/1059 Row 586: application_number: 1020190093747, combined_string: invention_title: 육묘 재배장치 abstract: 본 발명은 육묘 재배장치에 대한 것으로서, 더욱 상세하게는 모종을 태양광을 골고루 노출시킬 수 있을 뿐만 아니라 공간활용을 높일 수 있는 육묘 재배장치에 대한 것이다.본 발명에 따른 육묘 재배장치는 재배수단 및 복수의 프레임수단을 포함한다. 상기 재배수단은 복수의 장착바와, 모종을 키울 수 있게 상기 모종을 수용할 수 있으며 상기 장착바에 장착가능한 모종받침대를 구비한다. 복수의 상기 프레임수단은 기초프레임과, 상기 기초프레임에 수직으로 장착된 체인과, 상기 체인을 따라 일정한 간격 이격하여 상기 장착바의 일단을 탈착하게 결합시킬 수 있는 고정부와, 상기 장착바가 상하로 회전되도록 상기 체인을 회전시키기 위한 구동부와, 상기 기초프레임을 이동시킬 수 있게 상기 기초프레임의 하단에 장착된 바퀴를 구비하여 상기 장착바의 양단을 지지하도록 일정 간격 이격하여 서로 마주본다. 이 경우 상기 장착바가 상기 재배수단에서 분리되면 상기 복수의 프레임수단 사이에 이격 간격이 없도록 상기 복수의 프레임수단을 이동하여 붙일 수 있다.본 발명에 의하면 육묘 재배장치가 사용되지 아니할 경우 장착바를 고정부에서 분리하여 복수의 프레임수단을 서로 모을 수 있다. 이 경우 육묘 재배장치의 부피를 줄일 수 있으므로 공간을 덜 차지하므로 공간활용도를 높일 수 있 claims: 복수의 장착바와, 모종을 키울 수 있게 상기 모종을 수용할 수 있으며 상기 장착바에 장착가능한 모종받침대를 구비하는 재배수단과,기초프레임과, 상기 기초프레임에 수직으로 장착된 체인과, 상기 체인을 따라 일정한 간격 이격하여 상기 장착바의 일단을 탈착하게 결합시킬 수 있는 고정부와, 상기 장착바가 상하로 회전되도록 상기 체인을 회전시키기 위한 구동부와, 상기 기초프레임을 이동시킬 수 있게 상기 기초프레임의 하단에 장착된 바퀴를 구비하여 상기 장착바의 양단을 지지하도록 일정 간격 이격하여 마주보는 복수의 프레임수단을 포함하며,상기 장착바가 상기 재배수단에서 분리되면 상기 복수의 프레임수단 사이에 이격 간격이 없도록 상기 복수의 프레임수단을 이동하여 붙일 수 있는 것을 특징으로 하는 육묘 재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

587/1059 Row 587: application_number: 1020190093223, combined_string: invention_title: 스마트 공정육묘 통합관리시스템 abstract: 본 발명의 일 실시 예에 따른 스마트 공정육묘 통합관리시스템은 적어도 하나 이상의 모종이 이송트레이에 담겨진 상태로 육묘 공정이 수행되고, 육묘데이터가 획득되는 스마트팜 및 스마트팜에서 획득된 육묘데이터가 수집되어 처리되는 관리서버가 포함되고, 관리서버에서는 수집된 육묘데이터에 기초하여 이송트레이의 공정 간 이동시점이 예측될 수 있다. claims: 스마트 공정육묘 통합관리시스템에 있어서,적어도 하나 이상의 모종이 이송트레이에 담겨진 상태로 육묘 공정이 수행되고, 육묘데이터가 획득되는 스마트팜; 및상기 스마트팜에서 획득된 육묘데이터가 수집되어 처리되는 관리서버가 포함되고,상기 관리서버에서는 상기 수집된 육묘데이터에 기초하여 상기 이송트레이의 공정 간 이동시점이 예측되는 스마트 공정육묘 통합관리시스템., Ltext: 농업, prediction: 농업
588/1059 Row 588: application_number: 1020190093445, combined_string: invention_title: 열매 씨앗 적출 장치 abstract: 본 발명은 대추나 매실의 씨앗을 손쉽게 적출시키기 위한 장치로서, 보다 구체적으로 본 발명은 열매의 씨앗을 적출하기 위한 장치로서, 몸체부, 상기 몸체부의 일단에 구비되어 열매를 올려놓을 수 있도록 형성된 열매 트레이, 상기 몸체부와 회동결합되는 누름봉, 및 상기 누름봉의 일단에 결합되어 상기 열매로부터 씨앗을 적출하기 위한 적출칼날을 포함하되, 상기 누름봉이 회동됨에 따라 일정 경로를 따라 이동되는 적출칼날이 상기 열매에 꽂히는 형태로 상기 씨앗을 도려내어 적출하는 것을 특징으로 하는, 열매 씨앗 적출 장치에 관한 것이다. claims: 열매의 씨앗을 적출하기 위한 장치로서,몸체부;상기 몸체부의 일단에 구비되어 열매를 올려놓을 수 있도록 형성된 열매 트레이;상기 몸체부와 회동결합되는 누름봉; 및상기 누름봉의 일단에 결합되어 상기 열매로부터 씨앗을 적출하기 위한 적출칼날을 포함하되,상기 누름봉이 회동됨에 따라 일정 경로를 따라 이동되는 적출칼날이 상기 열매에 꽂히는 형태로 상기 씨앗을 도려내어 적출하는 것을 특징으로 하는,열매 씨앗 적출 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

589/1059 Row 589: application_number: 1020200030249, combined_string: invention_title: 병해충 예방 기능의 작물 보호제 및 이를 이용한 작물의 병해충 방제 방법 abstract: 본 발명은 살충, 항균 등의 병해충 예방 기능이 있는 작물보호제에 관한 것으로, 보다 상세하게는 오가노 실란을 함유하는 살충, 항균, 항바이러스 등의 병해충 예방 기능이 있는 작물보호제 및 작물의 병해충 방제 방법에 관한 것이다.본 발명은 오가노실란과 물을 혼합하여 조성한 살충, 항균, 항바이러스 등의 병해충 예방 기능이 있는 작물보호제를 제공한다.또한 본 발명은 오가노실란 100중량부에 물 100~20,000 중량부를 혼합하여 조성한 살충, 항균, 항바이러스 등의 병해충 예방 기능이 있는 작물보호제를 제공한다.또한 본 발명은 과채류 모종의 뿌리를 오가노실란 작물보호제로 적시는 과정(1과정),과채류가 심어질 토양에 상기한 오가노실란 작물보호제를 살포하는 과정(2과정),과채류를 심고 나서 작물의 잎에 오가노실란 작물보호제를 초벌 살포 소독하는 과정(3과정),작물의 잎, 줄기, 토양에 오가노실란 작물보호제에 재배 소독하는 과정(4과정),을 포함하는 작물의 병해충 방제 방법을 제공한다. claims: 오가노실란과 물을 혼합하여 조성한 살충, 항균, 항바이러스 등의 병해충 예방 기능이 있는 작물보호제.과채류 모종의 뿌리를 오가노실란 작물보호제로 적시는 과정(1과정),과채류가 심어질 토양에 오가노실란 작물보호제를 살포하는 과정(2과정),과채류를 심고 나서 작물의 잎에 오가노실란 작물보호제를 초벌 살포 소독하는 과정(3과정),작물의 잎, 줄기, 토양에 오가노실란 작물보호제에 재배 소독하는 과정(4과정),을 포함하는 작물의 병해충 방제 방법., Ltext: 농업, prediction: 임업
590/1059 Row 590: application_number: 1020200023078, combined_string: invention_title: 애플수박 재배방법 abstract: 본 발명은 적당한 과실비대가 이루어지고 높은 당도를 가지는 상품성이 높은 애플수박을 수확할 수 있는 것은 물론이며, 종래의 재배방법에 비해 수확량이 증가되어 수박농가의 수입증대를 꾀할 수 있는 새로운 방식의 애플수박 재배방법에 대한 것이다. claims: 애플수박 모종을 정식하는 정식단계;정식 후 곁가지가 생기면, 원줄기와 2개의 아들줄기만 남기고 나머지 곁가지를 제거하는 곁가지 제거단계;원줄기와 2개의 아들줄기를 9~10마디가 생길 때까지 유인하여 키우는 1차 재배단계;상기 1차 재배단계에서 키운 원줄기와 아들줄기의 9~10번째 마디에 개화한 암꽃을 수정시키는 1차 수정단계;상기 1차 수정단계 이후에 상기 원줄기와 아들줄기를 18~19마디가 생길 때까지 유인하여 키우는 2차 재배단계;상기 2차 재배단계에서 키운 상기 원줄기와 아들줄기의 18~19번째 마디에 개화한 암꽃을 수정시키고, 다른 마디에 개화한 암꽃은 제거하는 2차 수정단계;상기 1차 및 2차 수정단계에서 착과된 애플수박이 성숙되도록 키우는 3차 재배단계;상기 3차 재배단계에서 숙성된 애플수박을 수확하는 1차 수확단계; 상기 1차 수확단계가 끝난 후 상기 원줄기와 아들줄기를 곁가지를 제거하지 않고 키워서 줄기수를 늘리며, 모든 줄기에서 개화한 암꽃을 수정, 착과시켜서 성숙시키는 방목재배단계; 및 상기 방목재배단계에서 성숙된 애플수박을 수확하는 방목수확단계;를 포함하며,상기 1차 수정단계 및 상기 2차 수정단계에서는 각각 1차 수정단계에서 수정되어 착과된 애플수박과 2차 수정단계에서 수정되어 착과된 애플수박을 구별하기 위해 1차 수정단계에서 수정되어 착과된 수박과 2차 수정단계에서 수정되어 착과된 애플수박에 표시를 하는 것을 특징으로 하는 애플수박 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

591/1059 Row 591: application_number: 1020200021914, combined_string: invention_title: 기능성 장도라지의 재배방법 및 그 재배방법을 이용한 기능성 장도라지 abstract: 본 발명은 기능성 장도라지의 재배방법 및 그 재배방법을 이용한 기능성 장도라지에 관한 것으로, 좀 더 상세하게는 도라지의 길이를 길게 자라도록 함과 동시에 고사목을 이용한 기능성 액비를 주입하여 고사목과 동일한 영양을 갖는 기능성 장도라지를 재배할 수 있는 기능성 장도라지의 재배방법 및 그 재배방법을 이용한 기능성 장도라지에 관한 것이다.본 발명은 본 발명은 도라지를 노지에 파종하여 키우는 노지재배단계와; 상기 노지재배단계에서 자란 뿌리 썩음병을 방지하기 위해 화분에 옮겨심는 화분식재단계와; 상기 화분에 옮겨 심은 후, 상기 도라지의 뿌리가 길게 자랄 수 있도록 고사목이 담긴 화분을 추가하는 고사목화분 공급단계와; 상기 고사목 화분을 공급한 후, 상기 고사목 화분의 하단부에 연결하여 도라지 뿌리에 기능성 액비를 공급하기 위해 액비화분을 연결하는 액비화분 공급단계를 포함하는 것을 특징으로 한다. claims: 도라지를 노지에 파종하여 키우는 노지재배단계와;상기 노지재배단계에서 자란 뿌리 썩음병을 방지하기 위해 화분에 옮겨심는 화분식재단계와;상기 화분에 옮겨 심은 후, 상기 도라지의 뿌리가 길게 자랄 수 있도록 고사목이 담긴 화분을 추가하는 고사목화분 공급단계와;상기 고사목 화분을 공급한 후, 상기 고사목 화분의 하단부에 연결하여 도라지 뿌리에 기능성 액비를 공급하기 위해 액비화분을 연결하는 액비화분 공급단계를 포함하는 것을 특징으로 하는 기능성 장도라지의 재배방법.기능성 장도라지 재배방법으로 재배된 식이유황이 함유된 적어도 50Cm 이상의 장도라지를 특징으로 하는 기능성 장도라지., Ltext: 농업, prediction: 임업
592/1059 Row 592: application_number: 1020200000320, combined_string: invention_title: 식물 재배 장치용 파드 및 그 포장재 abstract: 본 발명은 운송 및 관리 중 파손이 방지되고 제조 비용이 절감되고, 효율적인 포장이 가능하게 되는 식물 재배 장치용 파드 및 그 포장재에 관한 것이다. claims: 식물 재배 장치의 베드에 교체 가능하게 장착되는 식물 재배 장치용 파드에 있어서, 내부에 재배를 위한 식물의 씨앗과, 해당 식물의 재배를 위한 양분이 포함된 상토가 수용되는 수용 공간을 형성하며, 상기 베드에 안착되는 용기; 및상기 용기의 상면에 부착되며, 상기 수용 공간을 차폐하는 아웃 커버;를 포함하며, 상기 용기는,상면이 개구되어 상기 수용 공간을 형성하며, 하면 일부가 하방으로 돌출되어 상기 베드에 급수되는 물이 유입되는 돌출부를 포함하는 용기 본체부;상기 용기 본체부의 상단에서 외측으로 연장되며, 상기 아웃 커버가 부착되는 상면을 형성하는 용기 상면부; 및상기 용기 상면부의 외측단에서 하방으로 연장되며, 상기 용기 본체부의 둘레와 이격된 공간을 형성하는 용기 테두리부를 포함하는 식물 재배 장치용 파드.판상의 소재가 절곡되어 상기 제 1 항 내지 제 12 항 중 어느 한 항의 파드가 수용되도록 상방으로 개구된 포장 공간;상기 포장 공간의 바닥면을 형성하는 하면부;상기 하면부의 가로 방향 양측단을 따라 상방으로 절곡되며, 상기 포장 공간의 가로 면을 형성하는 한쌍의 가로 측면부; 및상기 하면부의 세로 방향 양측단을 따라 상방으로 절곡되며, 상기 포장 공간의 세로 면을 형성하는 한쌍의 세로 측면부;을 포함하며,상기 하면부는, 상기 하면부에 한쌍이 서로 이격 배치되는 하면 개구; 및상기 하면 개구의 일단에서 상방으로 절곡되며, 상기 파드의 둘레에 형성된 공간에 삽입되어 상기 파드를 지지하는 한쌍의 지지부를 포함하는 식물 재배 장치용 파드 포장재., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

593/1059 Row 593: application_number: 1020190170799, combined_string: invention_title: 과채류를 이용한 유산균 발효식품 및 이의 제조방법 abstract: 본 발명은 우수한 균주와 이의 최적의 발효 조건을 이용한 유산균 발효식품 및 이의 제조방법, 상기 균주를 함유한 과립형 식품 및 이의 제조방법에 관한 것이다.상기 제조방법을 통해 건강에 유익하고 섭취가 편리한 유산균 함유 발효식품을 효과적으로 제조할 수 있다. 상기 발효식품 제조시, 다양한 과채류를 이용함으로써, 새로운 수요 창출을 일으켜 과채류를 재배하고 있던 농가의 수익 창출에도 도움이 될 수 있다. 또한, 상기 제조방법에 따라 제조된 발효식품은 기능성 성분을 다량 함유하고 언제 어디서나 간편하게 섭취할 수 있어, 건강 증진에 도움이 될 수 있다. claims: 건 과채류 원액을 제조하는 단계;상기 제조된 원액에 물과 당원을 첨가하는 단계; 및락토바실러스 람노서스(Lactobacillus rhamnosus), 락토바실러스 플란타럼(Lactobacillus plantarum), 또는 이의 혼합 유산균을 배지에 접종하여 배양한 후, 상기 물과 당원이 첨가된 원액에 상기 배양된 유산균 균체를 혼합하여 발효시키는 단계;를 포함하는 유산균 발효식품의 제조방법. 제 1 항 내지 제 5 항 중 어느 한 항에 따라 제조된 유산균 발효식품.과채 분말 및 락토바실러스 람노서스(Lactobacillus rhamnosus) 또는 락토바실러스 플란타럼(Lactobacillus plantarum) 유산균, 또는 상기 유산균의 하나 이상을 포함하는 유산균 발효액을 혼합하여 과채 원액을 제조하는 단계; 상기 제조된 과채 원액을 과립화하는 단계; 및상기 과립화된 과채 원액을 건조시키는 단계;를 포함하는 유산균 함유 과립형 식품 제조방법.제 8 항 내지 제 12 항 중 어느 한 항에 따라 제조된 유산균 함유 과립형 식품., Ltext: 농업, prediction: 농업
594/1059 Row 594: application_number: 1020190146445, combined_string: invention_title: 작물 재배 장치 abstract: 본 기술은 작물 재배 장치에 관한 것이다. 본 기술의 작물 재배 장치는, 복수의 재배 공간들을 정의하는 프레임; 및 상기 프레임에 연결되며, 상기 재배 공간에 대해 작물 생육환경을 조성하는 복수의 공급 라인들을 갖는 공급부;를 포함한다. 본 기술은 작물 재배 환경을 조성하는 각 요소들의 효율적인 배치 방식을 통해서 저비용 및 저전력으로 작물 재배 공간을 제공할 수 있는 작물 재배 장치를 제공할 수 있다. claims: 복수의 재배 공간들을 정의하는 프레임; 및 상기 프레임에 연결되며, 상기 재배 공간에 대해 작물 생육환경을 조성하는 복수의 공급 라인들을 갖는 공급부;를 포함하는 것을 특징으로 하는 작물 재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

595/1059 Row 595: application_number: 1020190147061, combined_string: invention_title: 파드 및 파드가 구비된 식물 재배장치 abstract: 본 발명의 파드 및 파드가 구비된 식물 재배장치는 파드를 구성하는 용기의 상부를 덮는 패키지를 분리하여 식물재배장치에 안착시키기만 하면 된다. 따라서, 식물재배에 배경지식이 없는 사용자도 손 쉽게 식물을 재배할 수 있게 되는 효과를 가진다. claims: 식물 재배장치에 사용되고, 식물이 자랄 수 있는 토양을 제공하는 파드에 있어서, 식물생장에 필요한 양분을 포함하는 토양을 공급하고, 씨앗 또는 식물이 안착되는 배지; 일측이 개방된 수용공간 내에 상기 배지가 수용되는 용기; 상기 수용공간의 입구를 차폐시키고, 상기 용기의 내부를 보호하는 패키지;를 포함하는 파드.식물이 재배되는 재배실을 제공함과 더불어 이 재배실의 개폐를 위한 개폐도어를 가지는 캐비넷;상기 캐비넷의 재배실 내에 수납되는 베드;상기 베드에 얹혀 식물이 생장하는 파드;상기 재배실 내의 바닥과 상기 재배실 내의 베드 사이에 구비되면서 상기 베드로 공급수를 공급하는 급수모듈;을 포함하고, 상기 파드는 식물생장에 필요한 양분을 포함하는 토양을 공급하고, 씨앗 또는 식물이 안착되는 배지; 일측이 개방된 수용공간 내에 상기 배지가 수용되는 용기; 상기 수용공간의 입구를 차폐시키고, 상기 용기의 내부를 보호하는 패키지;를 포함하여 구성됨을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 농업
596/1059 Row 596: application_number: 1020190145521, combined_string: invention_title: 율피 발효액 및 이를 이용한 토마토의 재배 방법 abstract: 본 발명은 율피가루 발효액 및 이를 이용한 토마토의 재배 방법에 관한 것이다. 본 발명에 따른 율피가루 발효액은 토마토 재배에 비료로 작용하여 토마토의 기능성을 증진시키는데 큰 도움을 주며 율피가루 발효액 자체가 병원균 등이 없어 인체 안정성이 매우 우수할 뿐만 아니라 자체로 우수한 기능성 성분들을 많이 함유하고 있다는 점에서 우수한 효과를 가진다. claims: (a) 바실러스 서브틸러스(Bacillus subtilis) 균주를 배양하여 바실러스 서브틸러스 균주 배양액을 제조하는 단계; (b) 물 100 중량부에 대해 상기 바실러스 서브틸러스 균주 배양액을 0.6 내지 2.0 중량부 및 율피 6 내지 20 중량부로 하여, 바실러스 서브틸러스 균주 배양액을 물 및 율피와 혼합하여 혼합 용액을 제조하는 단계; (c) 상기 혼합 용액을 20 내지 30 ℃에서 4 내지 14일 동안 배양하여 율피 발효액을 제조하는 단계;(d) 율피 발효액과 물을 1:50 내지 1:150의 부피비로 혼합하여 희석된 율피 발효액을 제조하는 단계; 및 (e) 희석된 율피 발효액을 토마토에 시비하는 단계;를 포함하는 토마토 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

597/1059 Row 597: application_number: 1020190133473, combined_string: invention_title: 배추수확기용 시뮬레이터 abstract: 본 발명은 기존의 수확기, 특히 배추와 같이 수확에 있어서, 충격이나 흠집에 민감한 채소를 노지에서 수확하는 수확장치를 개발함에 있어, 수확기에만 실험을 할 수밖에 없는 시기적인 제약과 상기 배추를 상하지 않고 수확할 수 있는 조건을 정확하게 찾아내기 위한 배추수확 시뮬레이터가 없어 최적의 배추 수확조건을 알아낼 수 없는 문제가 있어왔다. 본 발명은 상기와 같은 문제를 해결하기 위하여 하기의 수단을 제공한다. 배추수확시뮬레이터에 있어서, 예취부를 전방 하단에 구비한 배추이송컨베이어; 및 상기 배추이송컨베이어가 전후로 회전하는 배추이송 컨베이어회전힌지; 및 상기 배추이송 컨베이어회전힌지가 고정되는 시뮬레이터 이송부; 및 상기 시뮬레이터 이송부를 하부에서 지지하는 이송레일을 포함하는 것을 특징으로 하는 배추수확시뮬레이터를 제공한다.상기와 같은 구성에 의하여 수확기 시뮬레이터의 구동부 동작에 의하여 변화되는 여러 센서의 값을 읽어 동작조건을 모두 기록함으로써 가장 좋은 수확 결과가 나타난 수확조건을 찾아 수확기를 개발할 수 있는 효과가 있다. claims: 배추수확시뮬레이터에 있어서,예취부를 전방 하단에 구비한 배추이송컨베이어; 및상기 배추이송컨베이어가 전후로 회전하는 배추이송 컨베이어회전힌지; 및상기 배추이송 컨베이어회전힌지가 고정되는 시뮬레이터 이송부; 및상기 시뮬레이터 이송부를 하부에서 지지하는 이송레일을 포함하는 것을 특징으로 하는 배추수확시뮬레이터.예취부를 전방 하단에 구비한 배추이송컨베이어; 및상기 배추이송컨베이어가 전후로 회전하는 배추이송 컨베이어회전힌지; 및상기 배추이송 컨베이어회전힌지가 고정되는 시뮬레이터 이송부; 및상기 시뮬레이터 이송부를 하부에서 지지하는 이송레일을 구비한,배추수확시뮬레이터에 있어서,상기 시뮬레이터 이송부 바디프레임의 일측에 상하 길이변경이 가능한 바디회전실린더를 구비하여 상기 배추수확시뮬레이터 전체를 좌우로 흔드는 시뮬레이션을 수행하는 것을 특징으로 하는 배추수확시뮬레이터., Ltext: 농업, prediction: 임업
598/1059 Row 598: application_number: 1020190134068, combined_string: invention_title: 농작물 재배용 멀칭매트 천공장치 abstract: 본 발명은 각종 재배작물의 씨앗을 파종하거나 유모를 이식하여 재배할 때에 공기와 빗물이 통하고 잡초발생을 억제하여 재배작물을 건강하게 재배할 할 수 있도록 한 농작물 재배용 멀칭매트 천공장치에 관한 것으로, 그 구성은, 멀칭매트를 공급하는 공급부와, 멀칭매트에 식생구멍을 천공하는 천공부와, 천공부를 승/하강시키는 작동부와, 식생구멍이 천공된 멀칭매트를 회수하는 회수부와, 공급부와 회수부를 연통시키는 구동부와, 상기 구성을 제어하는 제어부로 이루어진다. claims: 합성수지재의 가닥을 복수 층을 형성하도록 적층시켜 실로 엮어 공기와 수분은 통하고 햇빛은 통과하지 못하도록 제조된 멀칭매트(M)를 공급하도록 본체(100)의 일측에 설치된 공급부(200);상기 공급부의 출측 본체의 상부에 길이방향을 따라 장홀(370)이 형성되고, 그 장홀에는 일측단에서 타측단까지 일정가격으로 고정볼트(350)를 설치하여 된 승/하강프레임(310)이 설치되고, 그 승/하강프레임에는 150 - 300℃로 발열되고 클램프(360)로 감싸여진 상태에서 상기 고정볼트의 선단에 고정되는 식생구멍천공구(320)가 등 간격으로 설치되며, 상기 승/하강프레임의 내부에는 상기 등 간격으로 설치된 식생구멍천공구로 전기를 공급하는 전선(340)과 상기 각 식생구멍천공구에 전원을 공급 및 차단에는 스위치(330)가 설치되고, 상기 승/하강프레임에는 상기 등 간격으로 설치된 식생구멍천공구 간의 간격을 조정하기 위한 눈금자(380)을 형성하여 상기 멀칭매트에 열을 가하여 녹이면서 재배작물의 식생구멍(H)을 천공하는 천공부(300);상기 천공부와 연결설치되어 천공부를 일정시간 주기로 승/하강시키도록 본체의 최상부에 양측에 설치된 프레임(120)에 각각의 랙 가이드(410)가 고정 설치되고, 그 랙 가이드에는 상기 승/하강프레임의 단부가 설치되는 각각의 랙(420)이 상향 수직되게 설치되며, 상기 각각의 랙에는 각각의 피니언(430)이 결합 설치되고, 상기 각 피니언 간에는 회전축(440)의 단부가 연결 설치되며, 상기 회전축에는 피니언을 회전시키는 회전수단(450)이 설치되고, 랙의 선택된 위치와 본체의 프레임(120) 일 측에 각각의 수광 또는 투광센서 중 어느 하나를 설치하여 된 작동부(400);상기 작동부에 의해 천공부가 승/하강 작동되면서 상기 식생구멍이 천공된 멀칭매트를 회수하는 회수부(500);공급부에서는 공급되는 멀칭매트의 공급양 만큼 회수부에서 회수되도록 본체의 전후방에 설치되는 각 회전 바(210,510)의 일 측단부에 각각의 회전부재(610)가 설치되고, 그 각 회전부재에는 동력전단부재(620)가 연결 설치되며, 상기 각 회전부재 중 일 측의 회전부재에는 모터(630)를 설치하여 된 구동부(600);상기 공급부, 천공부, 작동부, 회수부, 구동부를 제어하는 제어부(700);를 포함하는 구성을 특징으로 하는 멀칭매트의 식생구멍 천공장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

599/1059 Row 599: application_number: 1020190131343, combined_string: invention_title: 식물 재배장치 및 그의 급수제어 방법 abstract: 본 발명은 식물 재배장치 및 식물 재배장치의 급수제어 방법에 관한 것으로서, 본 발명의 식물 재배장치는 식물을 재배하기 위해 베드에 공급된 공급수의 잔수 여부에 따라 베드로 공급수를 공급하도록 하여 필요 이상의 공급수가 베드로 공급되지 않도록 한다. claims: 적어도 하나 이상의 베드가 수납되면서 식물이 재배되는 재배실을 제공함과 더불어 상기 재배실의 개방된 전면을 개폐하기 위한 개폐도어를 가지는 캐비넷;상기 재배실과는 독립된 공간의 기계실을 제공하는 기계실용 프레임;상기 재배실 내에 구비되며 상기 베드로 공급수를 공급하기 위한 급수모듈;상기 베드로 공급된 공급수의 잔수 여부를 감지하는 잔수감지센서;상기 잔수감지센서에서 수신되는 잔수감지신호에 기초하여 상기 급수모듈을 제어하는 컨트롤러를 포함하는 식물 재배장치.식물재배장치가 동작하면 복수의 베드에 대하여 각각의 잔수감지센서가 상기 각 베드로 공급된 공급수의 잔수 여부를 각각 감지하는 감지단계;컨트롤러가 상기 잔수감지센서에 의해 감지된 잔수여부에 대한 잔수감지신호를 이용하여 잔수 미감지의 베드가 있는지 판단하는 판단단계;상기 컨트롤러는 상기 판단결과 잔수 미감지의 베드가 있으면 상기 베드로 공급수를 급수하는 급수단계;상기 잔수 미감지의 베드로 공급수의 급수가 완료되면 급수를 종료하는 종료단계를 포함하는 식물 재배장치의 급수 제어방법.식물재배장치가 동작하면 잔수감지센서가 베드로 공급된 공급수의 잔수 여부를 감지하는 감지단계;상기 잔수감지센서에 의해 감지된 잔수여부에 대한 잔수감지신호를 이용하여 상기 베드가 잔수 미감지인지를 판단하는 판단단계;상기 잔수 미감지인 베드로 공급수를 급수하는 급수시작단계;상기 공급수를 제1 설정시간 동안 급수한 후 종료하는 급수종료단계;상기 급수가 종료되면 상기 급수의 횟수를 카운트하는 카운트단계;상기 급수에 의해 상기 잔수감지센서에서 제2 설정시간 동안 잔수 감지가 계속 유지되는지를 판단하는 잔수 판단단계;상기 잔수 판단단계에서의 판단결과에 따라 상기 베드의 급수 완료여부를 결정하는 급수완료 결정단계를 포함하는 식물 재배장치의 급수 제어방법.설정시간 동안의 총 급수량 및 1회 급수량을 설정하는 설정단계;컨트롤러가 급수개시요청에 따라 베드로 급수를 개시하는 급수개시단계;상기 설정된 1회 급수량만큼 급수되면 급수를 중단하는 급수중단단계;잔수감지센서에서 상기 베드에서의 잔수를 감지하는 감지단계;상기 잔수가 감지되면 잔수가 감지되지 않을 때까지 대기하고 상기 잔수가 감지되지 않으면 급수량이 상기 총 급수량에 도달했는지를 판단하는 판단단계;상기 총 급수량에 도달하지 않으면 급수량이 상기 총 급수량에 도달할 때까지 상기 급수개시단계부터 반복하는 반복단계를 포함하는 식물 재배장치의 급수 제어방법., Ltext: 농업, prediction: 농업
600/1059 Row 600: application_number: 1020190131607, combined_string: invention_title: 식물 재배장치 abstract: 본 발명의 식물 재배장치는 급수모듈을 이루는 워터탱크가 재배실에 구비되면서 사용자의 필요에 따른 취출이나 물 보충 등의 유지 관리가 용이하게 이루어질 수 있도록 한 것이다. claims: 재배실과 이 재배실의 개폐를 위한 도어를 가지는 캐비넷;캐비넷 내의 바닥에 위치되고, 공급수가 저장되는 워터탱크와, 상기 워터탱크의 후방에 위치되어 워터탱크 내의 공급수를 펌핑하는 워터펌프와, 워터펌프에 의해 펌핑된 공급수를 안내하는 급수호스를 포함하여 이루어진 급수모듈;상기 급수모듈의 상측에 위치되며, 상기 급수모듈로부터 공급수를 공급받는 베드;상기 베드의 상면에 안착되며, 양액물질이 포함된 상토를 가지는 파드;상기 캐비넷 내의 베드의 상측에 위치되면서 식물 재배를 위한 조명을 제공하는 조명모듈;상기 캐비넷의 하측에 설치되며, 기계실을 제공하는 기계실용 프레임;을 포함하며,상기 워터탱크는 워터펌프로부터 분리되면서 전방으로 인출 가능하게 구성됨을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

601/1059 Row 601: application_number: 1020190126949, combined_string: invention_title: 이동식 저온저장 장치 abstract: 채소나 과일을 저온저장하는 저온저장용 컨테이너에 타이어를 갖추고, 이송수단에 연결하여 끌고 다닐 수 있게 구성하므로, 채소나 과일 산지 근처 등 원하는 곳으로 쉽게 이동시켜 편리하게 사용할 수 있다. 특히, 저온저장용 컨테이너에 단열을 위해 사용하는 단열재에 제올라이트를 함유하게 하거나, 패널을 제작할 때 제올라이트를 함께 도포하여 사용할 수 있게 구성하므로, 제올라이트가 가진 다양한 특성, 예를 들어서, 살균·소독·항균·탈취·숙성 그리고 상온 보존 연장 효과를 얻을 수 있다. 또한, 유압 스탠드를 이용하여 저온저장용 컨테이너를 지지할 수 있게 구성하므로, 저온저장용 컨테이너의 수평 상태를 유지하여 안전하게 사용할 수 있고, 특히 지면이 평편하지 않은 곳에서도 쉽게 수평을 맞춰서 편리하게 사용할 수 있다. claims: 패널(110)로 제작하여 내부에 농산물을 저장할 수 있는 저온저장용 컨테이너(100)를 포함하되,상기 저온저장용 컨테이너(100)에는,이송수단에 연결하여 함께 이동하게 하는 견인장치;상기 저온저장용 컨테이너(100)가 움직일 수 있게 안내하는 적어도 두 개의 타이어(120); 및상기 저온저장용 컨테이너(100)의 수평 상태를 유지할 수 있도록 장착한 적어도 2개의 유압 스탠드(130);를 포함하는 것을 특징으로 하는 이동식 저온저장 장치., Ltext: 농업, prediction: 농업
602/1059 Row 602: application_number: 1020190126089, combined_string: invention_title: 농업용 생분해성 토양 멀칭 피복지 제조방법 abstract: 본 발명은 농업용 생분해성 토양 멀칭 피복지 제조방법에 관한 것으로서, 보다 상세하게는 상기 조개껍데기를 소성하여 곱게 분쇄하여 농업용 멀칭 피복지 제조에 사용함으로써, 식물에 Ca의 성분을 충분히 공급할 수 있도록 하고, 이러한 소성된 조개껍데기의 살균력을 통해 채소작물의 신선도를 유지할 수 있도록 함으로써, 기존의 환경문제를 해결하면서, 썩지않는 멀칭비닐의 기존문제점도 해결할 수 있도록 하는 농업용 생분해성 토양 멀칭 피복지 제조방법에 관한 것이다. claims: 크라프트 원지가 준비되는 단계(S100);코팅용 접착제가 제조되는 단계(S200);토질개량 및 광합성 차단제가 제조되는 단계(S300);상기 코팅용 접착제와 토질개량 및 광합성 차단제에, 열이 가해지면서 상호간 1:1 비율로 혼합되어, 기능성 코팅제가 제조되는 단계(S400);상기 크라프트 원지 상면에 기능성 코팅제가 사전설정 도포량 범위로 도포되는 단계(S500);상기 크라프트 원지 저면에 컬방지 및 발수코팅제가 코팅되어 농업용 멀칭 피복지가 제조되는 단계(S600);상기 농업용 멀칭 피복지가 건조 후, 롤에 권취되어 사전설정길이로 소분된 후, 포장출하되는 단계(S700);를 포함하여 이루어지며,상기 S300단계의 토질개량 및 광합성 차단제는칼슘제공 및 작물의 신선도 유지를 위한 소성된 폐조개가루 50중량%,토양개선과 광합성 차단을 위한 활성탄 및 블랙카본 20중량%,음이온 방출을 통한 토양개선효과에 사용되는 광물질 20중량%,붕사 3중량%,목초액 7중량%의 혼합으로 이루어지는 것을 특징으로 하는 농업용 생분해성 토양 멀칭 피복지 제조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

603/1059 Row 603: application_number: 1020190124261, combined_string: invention_title: 송풍 처리에 의한 토마토 접목묘의 도장 억제 방법 abstract: 본 발명은 송풍 처리에 의한 토마토 접목묘의 도장 억제 방법에 관한 것으로, 본 발명은 토마토 접목묘 육묘시 발생하는 도장 현상을 효과적으로 억제할 수 있는 친환경적인 방법으로, 본 발명의 방법을 이용하면 양질의 토마토 접목묘를 대량으로 생산할 수 있을 것으로 기대된다. claims: 토마토 접목묘를 송풍 처리하며 육묘시키는 단계를 포함하는, 토마토 접목묘의 도장을 억제하는 방법.토마토 접목묘를 송풍 처리하며 육묘시키는 단계를 포함하는, 묘소질 변화 없이 도장이 억제된 토마토 접목묘의 재배 방법.제3항 내지 제6항 중 어느 한 항의 재배 방법에 의해 재배된 묘소질 변화 없이 도장이 억제된 토마토 접목묘., Ltext: 농업, prediction: 농업
604/1059 Row 604: application_number: 1020190113145, combined_string: invention_title: 재배 시스템, 재배 박스 및 그 제어 방법 abstract: 하우징 및 식별 정보를 포함하고, 교체 가능한 재배 박스 및 상기 재배 박스로부터 상기 식별 정보를 획득하고, 센서를 이용하여 상기 재배 박스 내부 또는 상기 재배 박스 주변에 대한 상태 정보를 감지하며, 상기 식별 정보 및 상기 상태 정보에 기초하여 상기 재배 박스 내부로 액체를 분사하는 전자 장치를 포함하는 식물 재배 시스템이 개시된다. 이 외에도 명세서를 통해 파악되는 다양한 실시 예가 가능하다. claims: 전자 장치에 있어서,식물 재배를 위한 재배 박스가 안착되는 지지대;상기 지지대에 상기 재배 박스가 안착됨에 따라서 상기 재배 박스 내부로 삽입되는 노즐;상기 노즐을 통해서 상기 재배 박스 내부로 액체를 분사할 수 있도록 구성된 구동부를 포함하는 액체 공급 장치;상기 재배 박스 내부 또는 상기 재배 박스 주변에 대한 상태 정보를 감지하는 센서;상기 지지대에 상기 재배 박스가 안착됨에 따라서 상기 재배 박스로부터 상기 재배 박스를 식별하는 식별 정보를 획득하는 인식기; 및상기 센서, 상기 액체 공급 장치 및 상기 인식기와 연결된 프로세서를 포함하고,상기 프로세서는,상기 재배 박스가 상기 지지대에 안착된 상태에서, 상기 상태 정보 및 상기 식별 정보에 기초하여 상기 구동부의 동작 상태를 결정하고,상기 동작 상태에 기초하여 상기 재배 박스 내부로 액체가 분사되도록 상기 구동부를 제어하는, 전자 장치.식물 재배를 위한 재배 박스에 있어서,배지;상기 재배 박스를 식별하는 식별 정보를 포함하는 식별자 제공부; 및외부로부터 차단되는 내부 공간을 형성하는 하우징을 포함하고,상기 하우징은,상기 하우징 상단에 형성되어 상기 배지를 수용하는 배지 수용부,노즐을 구비하는 전자 장치에 상기 재배 박스가 안착됨에 따라서 상기 노즐을 수용하는 노즐 수용부, 및상기 전자 장치의 센서를 수용하는 센서 수용부를 포함하는, 재배 박스.식물 재배 시스템에 있어서,하우징 및 식별 정보를 포함하고, 교체 가능한 재배 박스; 및상기 재배 박스로부터 상기 식별 정보를 획득하고, 센서를 이용하여 상기 재배 박스 내부 또는 상기 재배 박스 주변에 대한 상태 정보를 감지하며, 상기 식별 정보 및 상기 상태 정보에 기초하여 상기 재배 박스 내부로 액체를 분사하는 전자 장치를 포함하는, 식물 재배 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

605/1059 Row 605: application_number: 1020190102547, combined_string: invention_title: 가바 성분을 강화시킨 토마토의 재배방법 abstract: 본 발명은 가바 성분을 강화시킨 토마토의 재배방법에 관한 것으로서, 토마토의 과실에 함유된 가바(GABA: gamma-ammino butyric acid) 성분의 함량을 크게 증대시킬 수 있는 토마토의 재배방법에 관한 것이다.본 발명의 가바 성분을 강화시킨 토마토의 재배방법은 현미를 발아시켜 발아현미를 수득하는 발아단계와, 발아현미를 물과 함께 갈아서 발아현미액을 수득하는 분쇄단계와, 발아현미액을 꾸지뽕 발효액과 혼합하여 혼합물을 수득하는 혼합단계와, 혼합물을 토마토에 시비하여 재배하는 재배단계를 포함한다. claims: 현미를 발아시켜 발아현미를 수득하는 발아단계와;상기 발아현미를 물과 함께 갈아서 발아현미액을 수득하는 분쇄단계와;상기 발아현미액 100중량부에 대하여 꾸지뽕 발효액 50 내지 150중량부와, 초석잠 발효액 20 내지 80중량부를 혼합하여 혼합물을 수득하는 혼합단계와;상기 혼합물을 토마토에 시비하여 재배하는 재배단계;를 포함하고,상기 초석잠 발효액은 초석잠 100중량부에 대하여 유산균 0.5 내지 10중량부와, 설탕 5 내지 20중량부를 혼합하여 10 내지 30일 동안 발효시킨 것을 특징으로 하는 가바 성분을 강화시킨 토마토의 재배방법., Ltext: 농업, prediction: 임업
606/1059 Row 606: application_number: 1020190100401, combined_string: invention_title: 유기 게르마늄 마늘 재배방법과 그 유기 게르마늄 마늘을 이용한 흑마늘 가공식품 abstract: 본 발명은 백토가 포함된 바이오 퇴비와 백토가 포함된 지장수 및 수용성 게르마늄이 포함된 기능성 재배수로 마늘을 재배하여 다량의 유기 게르마늄이 함유된 유기 게르마늄 마늘을 얻은 다음 흑마늘로 가공하여 다양한 제품으로 제조함으로써 국민건강증진에 많은 도움을 주고 농가수입 향상에 기여할 수 있도록 한 유기 게르마늄 마늘 재배방법과 그 유기 게르마늄 마늘을 이용한 흑마늘 가공식품에 관한 것으로, 유기 게르마늄 마늘 재배방법은, a) 바이오 퇴비로 지력이 배양된 경작지 약 300㎡에 5㎏의 백토를 골고루 뿌린다음 경운쇄토하여 소정 간격으로 마늘을 파종하는 단계와, b) 2~3월부터 1주일에 1~2회 백토 지장수를 마늘 주변 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계와, c) 4~5월부터 주 2회 이상 백토 지장수를 마늘 주변의 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계와, d) 마늘이 6쪽으로 바뀌는 ��부터 수용성 게르마늄 3~10㏄를 주당 2회 ~ 5회 마늘 주변의 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계와, e) 재배된 마늘을 수확하는 단계를 포함한다.본 발명에서 유기 게르마늄 마늘을 이용한 흑마늘 가공식품은, 흑마늘 건강보조식품, 흑마늘 엑기스, 흑마늘 식품 부재료, 흑마늘 소금일 수 있다. claims: a) 바이오 퇴비로 지력이 배양된 경작지 약 300㎡에 5㎏의 백토를 골고루 뿌린다음 경운쇄토하여 소정 간격으로 마늘을 파종하는 단계;b) 2~3월부터 1주일에 1~2회 백토 지장수를 마늘 주변 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계;c) 4~5월부터 주 2회 이상 백토 지장수를 마늘 주변의 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계;d) 마늘이 6쪽으로 바뀌는 ��부터 수용성 게르마늄 3~10㏄를 주당 2회 ~ 5회 마늘 주변의 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계;e) 재배된 마늘을 수확하는 단계;를 포함하는 유기 게르마늄 마늘 재배방법.청구항 1의 재배방법으로 재배 수확된 마늘을 발효 숙성시킨 흑마늘을 건조기에서 60℃ 34~48시간 제리 상태로 건조시켜서 된 유기 게르마늄 마늘을 이용한 흑마늘 가공식품.청구항 1의 재배방법으로 재배 수확된 마늘을 발효 숙성시킨 흑마늘을 발효기에 투입시켜 발효시킨 다음 압착착즙시켜 얻어지는 엑기스를 파우치에 포장하여서 된 유기 게르마늄 마늘을 이용한 흑마늘 가공식품.청구항 1의 재배방법으로 재배 수확된 마늘을 발효 숙성시킨 흑마늘을 70~80% 건조시킨 다음 소정 형상으로 절단 포장하여서 된 유기 게르마늄 마늘을 이용한 흑마늘 가공식품.청구항 1의 재배방법으로 재배 수확된 마늘을 발효 숙성시킨 흑마늘을 분말화한다음 소금을 같은 비율로 혼합시켜서 된 유기 게르마늄 마늘을 이용한 흑마늘 가공식품., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

607/1059 Row 607: application_number: 1020190094818, combined_string: invention_title: 상추 및 치커리를 포함하는 공영식물 재배 키트 및 이를 이용한 공영식물 재배 방법 abstract: 본 발명은 상추 및 치커리를 포함하는 공영식물 재배 키트, 이를 이용한 공영식물 재배 방법, 상추 및 치커리를 포함하는 공영식물 재배방법 및 이에 의해 재배된 상추 또는 치커리를 제공한다.본 발명의 상추 및 치커리를 포함하는 공영식물 재배 키트 및 공영식물 재배 방법은 친환경 도시농업과 식물공장 분야에서 소규모의 기능성 엽채류 생산 기술로 유용하게 사용될 수 있다. claims: 상추 및 치커리를 포함하는 공영식물 재배 키트.제1항 내지 제3항 중 어느 한 항의 공영식물 재배 키트를 이용한 공영식물 재배 방법.상추 및 치커리를 포함하는 공영식물 재배 방법.제9항 내지의 제12항 중 어느 한 항의 공영식물 재배 방법으로 재배된 상추 또는 치커리., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

608/1059 Row 608: application_number: 1020190088536, combined_string: invention_title: 작물 생육 중심의 병해충 및 기상장해 정밀관리 시스템과 그 방법 abstract: 본 발명은 작물의 생물계절(phenology)을 기반으로 병해충과 기상장해 발생위험을 군락 내 기상과 토양환경을 수집하여 수식화된 모델을 포함하고 있는 동적 시스템과 이에 대한 방법에 관한 것이다. 본 발명에 따른 작물 생육 중심의 병해충 및 기상장해 정밀관리 시스템 및 그 방법은 현재 기온으로만 위험기상을 판단하지 않고 현재 작물 생육단계가 해당 위험기상에 위험이 있을 경우에만 위험기상으로 판단함으로써 현재 재배하고 있는 작물에 따라 위험기상을 정확하게 예측할 수 있다. 또한, 본 발명에 따른 작물 생육 중심의 병해충 및 기상장해 정밀관리 시스템 및 그 방법은 현재 발생 가능한 병충해만으로 위험 병충해를 판단하지 않고 현재 작물 생육단계가 현재 발생 가능한 병충해에 위험이 있을 경우에만 위험 병충해로 판단하여 현재 재배하고 있는 작물에 따라 위험 병충해를 정확하게 예측할 수 있다. claims: 작물을 생육하고자 하는 지역의 기상 정보와 토양환경 정보를 수집하는 정보 수집 모듈과,상기 기상 정보와 토양환경 정보를 기반으로 상기 작물의 생육단계를 예측하는 생육단계 예측 모듈,상기 기상 정보와 토양환경 정보를 기반으로 발생 가능한 병해충을 예측하는 병해충 예측 모듈,상기 기상 정보를 기반으로 위험기상을 예측하는 위험기상 예측 모듈, 및상기 발생 가능한 병해충과 상기 생육단계가 매칭되거나, 상기 위험기상과 생육단계가 매칭되면 위험 경고를 수행하는 위험 판단 모듈을 포함하며,상기 정보 수집 모듈은, 상기 기상 정보를 수집하는 기상 정보 수집 모듈과, 상기 토양환경 정보를 수집하는 토양환경 정보 수집 모듈을 포함하고,상기 기상 정보는 작물이 재배되고 있는 지점에 설치된 환경계측장비로부터 수집된 기온과 상대습도, 강우량, 일사량, 일조시간, 결로 정보를 포함하며, 상기 토양환경 정보는 작물이 재배되고 있는 지점에 설치된 환경계측장비로부터 수집된 토양온도와 토양수분을 포함하고,상기 위험기상 예측 모듈은, 상기 작물이 노지에서 재배되고 있는 경우, 상기 작물이 재배되고 있는 지점의 일 최고기온이 고온해 기준 이상이거나, 상기 작물이 재배되고 있는 지점의 일 최저기온이 동해와 저온해 기준 이하이며, 상기 노지에서 재배되고 있는 작물의 생육단계가 상기 고온해, 동해 또는 저온해에 피해를 입을 수 있는 생육단계인지 판단하고,상기 위험 판단 모듈은, 상기 작물이 무가온 하우스 내에서 재배되고 있을 경우, 상기 작물이 재배되고 있는 무가온 하우스의 내부 일 최고기온이 고온해 기준 이상이거나, 상기 작물이 재배되고 있는 무가온 하우스의 내부 일 최저기온이 동해와 저온해 기준 이하이며, 상기 작물의 생육단계가 상기 고온해, 동해 또는 저온해에 피해를 입을 수 있는 생육단계일 경우 위험으로 판단하며,상기 위험기상 예측 모듈은, 상기 작물이 무가온 하우스 내에서 재배되고 있는 경우, 상기 작물이 재배되고 있는 지점에 대해서 기상청에서 제공하는 동네예보와 중기예보를 이용하여 연산하고자 하는 i일의 외부 일 누적 일사량과, 상기 작물이 재배되고 있는 무가온 하우스 내부 일 최고기온 및 일 최저기온을 연산하고,상기 i일의 외부 일 누적 일사량은,이며,상기 는 i일의 추정된 일 누적 일사량(MJ/m2),상기 는 i일의 대기외일사량(MJ/m2),상기 a, b, c, d, e, f, g, h, k는 외부 일 누적 일사량을 연산하고자 하는 지점의 최인접 지점의 모델 변수값,상기 는 i일의 일 최고기온-일 최저기온,상기 는 i일 다음 날의 ,상기 는 i일 전 날의 ,상기 는 i일 다음 날의 ,상기 는 i일 전 날의 , 상기 는 i일의 일 누적 강우량이 0.1mm 이상이면 1이고 0.1mm 미만이면 0인 작물 생육 중심의 병해충 및 기상장해 정밀관리 시스템.작물을 생육하고자 하는 지역의 기상 정보와 토양환경 정보를 정보 수집 모듈이 수집하는 단계와,상기 기상 정보와 토양환경 정보를 기반으로 상기 작물의 생육단계를 생육단계 예측 모듈이 예측하는 단계,상기 기상 정보와 토양환경 정보를 기반으로 발생 가능한 병해충을 병해충 예측 모듈이 예측하는 단계,상기 기상 정보를 기반으로 위험기상을 위험기상 예측 모듈이 예측하는 단계, 및상기 발생 가능한 병해충과 상기 생육단계가 매칭되거나, 상기 위험기상과 생육단계가 매칭되면 위험 판단 모듈이 위험 경고를 수행하는 단계를 포함하며,상기 작물을 생육하고자 하는 지역의 기상 정보와 토양환경 정보를 정보 수집 모듈이 수집하는 단계는,상기 기상 정보를 기상 정보 수집 모듈이 수집하는 단계와, 상기 토양환경 정보를 토양환경 정보 수집 모듈이 수집하는 단계를 포함하고,상기 기상 정보는 작물이 재배되고 있는 지점에 설치된 환경계측장비로부터 수집된 기온과 상대습도, 강우량, 일사량, 일조시간, 결로 정보를 포함하며, 상기 토양환경 정보는 작물이 재배되고 있는 지점에 설치된 환경계측장비로부터 수집된 토양온도와 토양수분을 포함하고,상기 기상 정보를 기반으로 위험기상을 위험기상 예측 모듈이 예측하는 단계는,상기 작물이 노지에서 재배되고 있는 경우, 상기 작물이 재배되고 있는 지점의 일 최고기온이 고온해 기준 이상이거나, 상기 작물이 재배되고 있는 지점의 일 최저기온이 동해와 저온해 기준 이하이며, 상기 노지에서 재배되고 있는 작물의 생육단계가 상기 고온해, 동해 또는 저온해에 피해를 입을 수 있는 생육단계인지 상기 위험기상 예측 모듈이 판단하고,상기 기상 정보를 기반으로 위험기상을 위험기상 예측 모듈이 예측하는 단계는,상기 작물이 무가온 하우스 내에서 재배되고 있을 경우, 상기 작물이 재배되고 있는 무가온 하우스의 내부 일 최고기온이 고온해 기준 이상이거나, 상기 작물이 재배되고 있는 무가온 하우스의 내부 일 최저기온이 동해와 저온해 기준 이하이며, 상기 작물의 생육단계가 상기 고온해, 동해 또는 저온해에 피해를 입을 수 있는 생육단계인지 상기 위험기상 예측 모듈이 판단하고,상기 기상 정보를 기반으로 위험기상을 위험기상 예측 모듈이 예측하는 단계는,상기 위험기상 예측 모듈이 상기 작물이 재배되고 있는 지점에 대해서 기상청에서 제공하는 동네예보와 중기예보를 이용하여 연산하고자 하는 i일의 외부 일 누적 일사량과, 상기 작물이 재배되고 있는 무가온 하우스 내부 일 최고기온 및 일 최저기온을 연산하는 단계를 포함하며,상기 i일의 외부 일 누적 일사량은,이며,상기 는 i일의 추정된 일 누적 일사량(MJ/m2),상기 는 i일의 대기외일사량(MJ/m2),상기 a, b, c, d, e, f, g, h, k는 외부 일 누적 일사량을 연산하고자 하는 지점의 최인접 지점의 모델 변수값,상기 는 i일의 일 최고기온-일 최저기온,상기 는 i일 다음 날의 ,상기 는 i일 전 날의 ,상기 는 i일 다음 날의 ,상기 는 i일 전 날의 , 상기 는 i일의 일 누적 강우량이 0.1mm 이상이면 1이고 0.1mm 미만이면 0인 작물 생육 중심의 병해충 및 기상장해 정밀관리 방법., Ltext: 농업, prediction: 임업
609/1059 Row 609: application_number: 1020190085603, combined_string: invention_title: 수박 일소과 방지 과실덮개 abstract: 본 발명은 하절기 고온기 특히, 수박의 출하를 앞둔 시점에서 수박이 직사광선에 노출되어 일소과로 불리우는 과실데임 현상이 발생하는 문제점과, 과도한 직사광선의 노출에 의한 수박내부의 육질악질변과인 피수박의 발생과 생리장애 수박의 발생을 억제하는 재배방법과 그 재배방법에 사용되는 과실데임 현상 방지를 위한 최적의 과실덮개를 제공하고자 한다.본 발명은 상기와 같은 문제를 해결하기 위하여 하기와 같은 과제해결 수단을 제공한다. 40g/㎡ 또는 50g/㎡의 밀도를 가지는 부직포로 구성된 과실데임 방지를 위한 수박 일소과 방지 과실덮개를 고온기에 수박을 수확 전 10일 간 감싸 재배하는 것을 특징으로 하는 수박의 재배방법을 제공한다.본 발명의 과실데임 현상 방지를 위한 수박 일소과 방지 과실덮개는 노지와 비가림하우스에서 재배하는 수박을 대상으로 고온기에 수박의 직사광선에 의한 일소과 (과실데임)의 발생과 수박 내부의 육질악변과인 피수박과 생리장해 수박의 발생을 억제하는 효과가 있다. 또한, 외부로부터 과실에 영향을 미치는 목화바둑명나방 및 파밤나방 등으로부터 과실을 보호하여 해충의 피해를 줄이는 효과 또한 가지고 있다. claims: 40g/㎡ 또는 50g/㎡ 의 밀도를 가지는 부직포로 구성된 일소과(과실데임) 방지를 위한 수박 일소과 방지 과실덮개를 고온기에 수박을 수확 전 10일 간 감싸 재배하는 것을 특징으로 하는 수박 일소과 방지 과실덮개를 이용한 수박 재배방법일소과(과실데임) 방지를 위한 수박 일소과 방지 과실덮개는 과중이 8~10kg인 대과종 수박생산을 위해 반지름 34~37cm의 40g/㎡ 또는 50g/㎡의 밀도를 가지는 부직포의 가장자리에 주름 만들어 내접원주의 길이가 50~52cm가 되도록 접고, 신축 가능한 고무줄과 바느질로 결합 시키는 것을 특징으로 하는 일소과(과실데임) 방지를 위한 수박 일소과 방지 과실덮개., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

610/1059 Row 610: application_number: 1020217009183, combined_string: invention_title: 육묘블록 abstract: 본 발명은 육묘블록에 관한 것으로, 종자에게 영양을 제공하는 영양블록(1)을 포함하고 영양블록(1)의 꼭대기부에 종자 투입 홀(2)이 개설되며, 종자 투입 홀(2) 내부에 종자 재배 홀(3)이 개설되고 종자 투입 홀(2)은 위가 크고 아래가 작은 구조로 설치되어 종자가 중력 작용하에 종자 투입 홀의 표면을 따라 종자 재배 홀(3) 내에 떨어져 들어가도록 하며, 종자 재배 홀(3) 내부에는 종자 재배 홀과 멀어지는 방향으로 연장되고 종자가 발아해 나온 뿌리에게 생장 경로를 제공하는 절개구(4)가 개설된다. 해당 육묘블록은 파종 효율을 향상시킬 수 있으며, 종자를 안정되게 고정시키고 적셔줄 수 있으며, 종자 전체의 출아율과 출아 균일도를 향상시킬 수 있어 기계화 파종에 편리하다. claims: 육묘블록에 있어서,종자에게 영양을 제공하는 영양블록(1)을 포함하고, 영양블록(1)의 꼭대기부에 종자 투입 홀(2)이 개설되며, 종자 투입 홀(2) 내부에 종자 재배 홀(3)이 개설되고, 종자 투입 홀(2)은 위가 크고 아래가 작은 구조로 설치되어 종자가 중력 작용하에 종자 투입 홀(2)의 표면을 따라 종자 재배 홀(3) 내에 떨어져 들어가도록 하며, 종자 재배 홀(3) 내부에는 종자 재배 홀(3)과 멀어지는 방향으로 연장되고, 종자가 발아해 나온 뿌리에게 생장 경로를 제공하는 절개구(4)가 개설되는 것을 특징으로 하는 육묘블록., Ltext: 농업, prediction: 임업
611/1059 Row 611: application_number: 1020190077873, combined_string: invention_title: 식물 재배장치 abstract: 식물 재배장치에 있어서, 상기 식물재배장치는 상부측에 2개의 가로부재와 2개의 세로부재를 4각형 구조로 결합한 상부프레임과; 상기 상부프레임의 모서리 하면 4곳에 결합되어 상부프레임을 수직으로 지지하는 포스트프레임과; 상기 포스트프레임의 하부측에 상부프레임의 폭보다 좁은 폭의 격자구조를 이루며 결합되는 지지대받침프레임과; 상기 식물 재배장치에 결합되어 식물의 줄기 또는 가지를 묶어서 지지하는 지지대와; 상기 상부프레임의 가로부재와 세로부재의 상면과 상부프레임의 세로부재 중간부에 장착되며 상기 지지대의 상부측이 끼워져 결합되는 지지대결합판을 포함하여 형성하는 식물 재배장치에 관한 발명이다. claims: 상부측에 2개의 가로부재와 2개의 세로부재를 4각형 구조로 결합한 상부프레임(1)과; 상기 상부프레임의 모서리 하면 4곳에 결합되어 상부프레임을 수직으로 지지하는 포스트프레임(2)과; 상기 포스트프레임의 하부측에 상부프레임의 폭보다 좁은 폭의 격자구조를 이루며 결합되는 지지대받침프레임(3)과; 상기 식물 재배장치에 결합되어 식물의 줄기 또는 가지를 묶어서 지지하는 지지대(4)와; 상기 상부프레임의 가로부재와 세로부재의 상면과 상부프레임의 세로부재 중간부에 장착되며 상기 지지대의 상부측이 끼워져 결합되는 지지대결합판(5)을 포함하여 형성하는 식물 재배장치에 있어서,상기 상부프레임과 포스트프레임 및 지지대받침프레임은 모두 4각형관재로 형성하고,상기 지지대받침프레임은 포스트프레임의 양측 단부 전후방 포스트를 연결하는 한쌍의 세로대(6)와 상기 한쌍의 세로대의 양측부에 상기 포스트프레임의 폭보다 좁은 간격으로 한쌍의 가로대(7)를 결합하되, 상기 한쌍의 가로대 중앙부에 하나의 간격재(8)로 칸막이를 형성하여 4각형 모양의 격자구조 2개를 형성하고,또한 상기 지지대받침프레임은 포스트프레임의 하단으로부터 25 ~ 40cm 높이에 설치하여, 높이 20cm로 형성되는 식물재배용기 하나를 하나의 4각형 모양의 격자구조 하부에 배치할 수 있도록 하며, 상기 한 쌍의 가로대와 간격재의 4각형관제 상면에는 지지대를 끼워서 설치하는 지지대삽입홀(9) 복수개를 일정간격으로 형성하여, 지지대의 하부가 상기 지지대삽입홀에 끼워지며 지지대의 하단은 지지대삽입홀의 4각형관재 밑면에 받쳐지도록 하고,상기 지지대결합판은 하단부가 상기 지지대받침프레임의 지지대삽입홀에 끼워져 장착되는 지지대의 상부측을 가압하여 고정할 수 있도록 입구는 지지대의 굵기보다 넓고 내측단부는 지지대의 굵기보다 좁은 지지대걸림구(10) 복수개를 일정간격으로 형성하며,상기 지지대 하부를 상기 지지대삽입홀에 끼우고 상부측을 지지대결합판의 지지대걸림구에 결합하여 지지대가 지지대받침프레임으로부터 상향 경사진 상태로 설치되어 상부가 확개되는 식물의 가지를 결합하거나 덩쿨식물을 상향 경사시켜 생장을 유도할 수 있도록 하는 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

612/1059 Row 612: application_number: 1020190077112, combined_string: invention_title: 토마토 생육촉진 및 황화바이러스 방제를 위한 조성물과 이를 이용한 토마토의 재배방법 abstract: 본 발명은 토마토 생육촉진 및 황화바이러스 방제를 위한 조성물과 이를 이용한 토마토의 재배방법에 관한 것으로서, 더욱 상세하게는 리보플라빈과 백두옹 추출물을 함유하여 토마토의 생육을 촉진시키고 토마토황화바이러스의 방제에 효과가 있는 조성물을 제공함과 동시에 이를 이용하여 토마토를 재배함으로써 토마토의 생육촉진과 함께 과실에 함유된 리보플라빈의 함량을 증대시킬 수 있는 재배방법에 관한 것이다. claims: 리보플라빈 용액 20 내지 80중량%와 백두옹 추출물 20 내지 80중량%를 함유하며,토마토의 생육촉진과 황화바이러스 방제효과를 가지며,상기 황화바이러스는 토마토황화잎말림바이러스(Tomato yellow leaf curl virus; TYLCV)인 것을 특징으로 하는 토마토 생육촉진 및 황화바이러스 방제를 위한 조성물. 제 1항 또는 제 2항의 조성물을 살포하여 토마토를 재배하는 것을 특징으로 하는 토마토의 재배방법., Ltext: 농업, prediction: 농업
613/1059 Row 613: application_number: 1020190066966, combined_string: invention_title: 포트 어셈블리 및 이를 이용한 다단식 재배장치 abstract: 본 발명은 포트마다 식재된 작물의 발근과 활착을 균일하게 하고 우수한 품질의 육묘와 재배를 동시에 구현할 수 있는 포트 어셈블리 및 이를 이용한 다단식 재배장치를 제공함에 있다. 이를 위한 본 발명은 길이를 가지며 상부 및 양단부가 개방되는 트레이; 상기 트레이의 양단부에 결합되며, 상기 트레이의 내부에 채워지는 공급액이 배출되는 배출공이 구비되는 측면커버; 상기 트레이의 상부를 향해 삽입하여 배치되며, 작물이 식재되는 복수의 개별포트가 구비되는 육묘포트; 및 상기 육묘포트의 일측에 배치되도록 상기 트레이와 결합되며, 상기 작물과 연결되는 줄기를 유인 및 고정시키기 위한 줄기가이드;를 포함하는 포트 어셈블리 및 이를 이용한 다단식 재배장치의 특징을 개시한다. claims: 길이를 가지며, 상부 및 양단부가 개방되는 트레이;상기 트레이의 양단부에 결합되며, 상기 트레이의 내부에 채워지는 공급액이 배출되는 배출공이 구비되는 측면커버;상기 트레이의 상부를 향해 삽입하여 배치되며, 작물이 식재되는 복수의 개별포트가 구비되는 육묘포트; 및상기 육묘포트의 일측에 배치되도록 상기 트레이와 결합되며, 상기 작물과 연결되는 줄기를 유인 및 고정시키기 위한 줄기가이드;를 포함하는 것을 특징으로 하는 포트 어셈블리.지면으로부터 이격 배치되는 한 쌍의 수평프레임 및 상기 수평프레임의 하측에 배치되며 지면으로부터 상기 수평프레임을 향해 경사지게 배치되는 한 쌍의 경사프레임을 포함하는 프레임유닛;상기 수평프레임에 안착되는 모판;상기 경사프레임에 결합되는 한 쌍의 지지대유닛; 및상기 지지대유닛에 양단부가 지지되는 제1항에 기재된 포트 어셈블리;를 포함하는 것을 특징으로 하는 다단식 재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

614/1059 Row 614: application_number: 1020190066323, combined_string: invention_title: 식물재배용기를 이용한 재배 시스템 abstract: 본 발명은 순환관을 통해 온수 또는 냉수를 공급하여 용기본체 내부의 온도를 작물에 적합한 온도로 유지되게 제어함으로써, 작물의 생장을 촉진하고 과실의 품질을 향상시킬 수 있는 식물재배용기를 이용한 재배 시스템을 제공하기 위한 것이다.본 발명의 식물재배용기는, 상단이 개방되어 내부에 재배할 식물이 수용되며, 하단 폭이 상단 폭 보다 좁게 형성되는 용기본체(110); 상기 용기본체(110)의 양측 상단에 하향 경사지게 연장 형성된 줄기지지대(120); 상기 용기본체(110)의 하단 중심부에 길이 방향으로 개방 형성되며, 상기 용기본체(110)의 내부에 공급된 수분이 배출되는 배수관(130); 상기 용기본체(110)의 하단 양측에 구비되며, 내부에 냉각수 또는 난방수가 공급되는 순환관(140); 을 포함한다. claims: 상단이 개방되어 내부에 재배할 식물이 수용되며, 하단 폭이 상단 폭 보다 좁게 형성되는 용기본체(110); 상기 용기본체(110)의 양단에 하향 경사지게 연장 형성된 줄기지지대(120); 상기 용기본체(110)의 하단 중심부에 길이 방향으로 개방 형성되며, 상기 용기본체(110)의 내부에 공급된 수분이 배출되는 배수관(130); 상기 용기본체(110)의 하단 양측에 구비되며 내부에 냉각수 또는 난방수가 공급되는 순환관(140); 을 포함하는 식물재배용기(100)를 이용한 재배 시스템에 있어서,상기 용기본체(110)에 일정 시간 간격으로 수분을 공급하는 관수장치(200);상기 배수관(130)에 냉풍 또는 온풍을 공급하는 공기공급장치(300); 상기 용기본체(110)의 내부에 장착되는 온도센서(400); 상기 관수장치(200)와 공기공급장치(300)의 작동을 제어하는 제어장치(600); 를 포함하되, 상기 제어장치(600)는 상기 관수장치(200)의 작동시 상기 공기공급장치(300)를 정지시키고, 상기 관수장치(200)가 수분을 공급하고 일정 시간이 경과한 후 상기 공기공급장치(300)를 작동시키도록 제어하는 것을 특징으로 하는 식물재배용기를 이용한 재배 시스템., Ltext: 농업, prediction: 임업
615/1059 Row 615: application_number: 1020190052910, combined_string: invention_title: 식물 재배 장치 abstract: 본 발명의 일 실시예는 재배상을 수직으로 일괄 적층 거치할 수 있도록 함과 동시에 재배환경 내 광 균일성을 확보하여 최대 효율의 광 조사량을 가지도록 하여 치묘 또는 이끼식물 등의 식물을 효율적으로 재배할 수 있도록, 하부에 위치되는 하부받침부; 상기 하부받침부의 상부에 상하 방향으로 겹침 및 펼침 가능하게 적층되는 다수의 재배상거치대들을 가지는 재배상거치부; 및 상기 재배상거치대(210)들을 겹쳐진 상태로 적층시키거나, 서로 상하로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 및 밀착되어 지그 재그 형상으로 펼쳐지도록 지지하는 지지부;를 포함하여 구성되는 식물 재배 장치를 제공한다. claims: 하부에 위치되는 하부받침부;상기 하부받침부의 상부에 상하 방향으로 겹침 및 펼침 가능하게 적층되는 다수의 재배상거치대들을 가지는 재배상거치부; 및상기 재배상거치대(210)들을 겹쳐진 상태로 적층시키거나, 서로 상하로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 및 밀착되어 지그 재그 형상으로 펼쳐지도록 지지하는 지지부;를 포함하여 구성되는 것을 특징으로 하는 식물 재배 장치.상부면의 모서리들에서 서로 대향하는 방향으로 다수의 도르레가 상방향으로 설치되어 하부에 위치되는 하부받침부;상기 하부받침부의 상부에 상하 방향으로 겹침 및 펼침 가능하게 적층되는 다수의 재배상거치대들을 가지는 재배상거치부;저면의 모서리들에 상기 하부받침부에 설치된 상기 다수의 도르레들과 하 방향으로 대향하도록 다수의 도르레들이 설치되어 상기 재배상거치부의 상부에 위치되는 상부고정부; 및상기 하부받침부의 상기 도르레가 설치된 인접 위치들에 일단부가 고정된 후 상기 재배상거치대들에 형성된 재배상 지지부재 삽입홀들에 삽입된 후 상기 상부고정부에 설치된 도르레를 거쳐 상기 하부받침부에 설치된 도르레들에 걸리어져 상기 재배상거치대들을 지지하는 다수의 지지부재(310)들을 가지는 지지부;를 포함하여 구성되어,상기 지지부재들의 자유단부를 당기는 경우, 상기 재배상거치대들의 서로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 및 밀착되어 지그 재그 형상으로 펼쳐지는 것을 특징으로 하는 식물 재배 장치.하부에 위치되는 하부받침부;상기 하부받침부의 상부에 상하 방향으로 겹침 및 펼침 가능하게 적층되는 다수의 재배상거치대들을 가지는 재배상거치부; 및상기 재배상거치대들을 겹쳐진 상태로 적층시키거나, 서로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 및 밀착되어 지그 재그 형상으로 펼쳐지도록 지지하는 지지부;를 포함하는 다수의 단위 식물 재배장치들이,상기 지지부에 의해 상기 재배상거치대(210)들이 서로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 또는 밀착되어 지그 재그 형상으로 펼쳐짐과 동시에 상기 재배상거치대들이 인접된 상기 단위 식물 재배장치들의 재배상거치대들과 마름모 형상을 이루도록 열을 이루며 배치되도록 구성되는 것을 특징으로 하는 식물 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

616/1059 Row 616: application_number: 1020190051433, combined_string: invention_title: 과실수의 가지유인추 abstract: 본 발명은 가지유인추의 조립이 보다 간편하게 이루어질 수 있고 생산효율을 향상시킬 수 있도록 전체적인 결합구조를 개선한 가지유인추를 제공한다. 본 발명은, 제1중량추 및 제2중량추와, 상기 제1중량추 및 제2중량추의 하단부에 각각 형성된 제1파지부 및 제2파지부와, 상기 제1중량추와 상기 제2중량추의 서로 마주보는 면에 각각 형성되어 서로 접촉결합됨으로써 제1중량추와 제2중량추가 회전하는 중심축의 역할을 하는 제1회전축부 및 제2회전축부와, 탄성스트립 또는 탄성와이어가 절곡되어 형성되는 것으로서, 상기 제1중량추 및 제2중량추의 각 상단부에 양단이 각각 결합되고, 상기 제1중량추와 제2중량추 사이에 상방으로 개방되는 가지수용부가 위치하도록 절곡된 탄성부재를 포함한다. claims: 가지(51)에 걸어 가지(51)가 향하는 방향을 유인하는 과실수의 가지유인추에 있어서,소정의 무게를 가지고 서로 분할된 제1중량추(10) 및 제2중량추(20)와,상기 제1중량추(10)의 하단부와 상기 제2중량추(20)의 하단부에 각각 형성되어 손가락으로 잡는 제1파지부(11) 및 제2파지부(21)와,상기 제1중량추(10)와 상기 제2중량추(20)의 서로 마주보는 면(16,26)에 각각 형성되어 서로 접촉결합됨으로써 상기 제1중량추(10)와 상기 제2중량추(20)가 회전하는 중심축의 역할을 하는 제1회전축부(15) 및 제2회전축부(25)와,탄성스트립 또는 탄성와이어가 절곡되어 형성되는 것으로서, 상기 제1중량추(10)의 상단부와 상기 제2중량추(20)의 상단부에 양단이 각각 결합되고, 상기 제1중량추(10)와 상기 제2중량추(20) 사이에 상방으로 개방되는 가지수용부(31)가 위치하도록 절곡된 탄성부재(30)를 포함하고,상기 탄성부재(30)는, 양 측단에 각각 상하로 연장되도록 형성되어 상기 제1중량추(10)의 상단부와 상기 제2중량추(20)의 상단부의 각 끼움홈(13,23)에 각각 끼워지는 양측 결합부(34a,34b)와, 상기 양측 결합부(34a,34b)로부터 중심부로 각각 연장되어 서로 모이는 양측 연장부(33a,33b)와, 상기 제1회전축부(15) 및 제2회전축부(25)의 상측에 위치하고 중심부에 모인 양측 연장부(33a,33b)가 하측방향으로 연장되어 가지(51)를 둘러싸도록 형성되는 상기 가지수용부(31)를 포함하며,상기 양측 결합부(34a,34b)는 외력이 없는 상태에서 중심부를 향해 모이도록 수직면에 대하여 경사지게 상하방향으로 연장되고, 상기 끼움홈(13,23)은 수직으로 형성되며,상기 제1회전축부(15) 및 제2회전축부(25)는, 그 중 하나가 볼록한 돌출면(15a)을 형성하고 다른 하나가 오목한 수용면(25a)을 형성하여 서로 접촉한 상태로 상기 탄성부재(30)에 의해 결합된 것을 특징으로 하는 과실수의 가지유인추, Ltext: 농업, prediction: 임업
617/1059 Row 617: application_number: 1020190048349, combined_string: invention_title: 곧은 뿌리 식물 재배 시스템 abstract: 본 발명은 곧은 뿌리 식물 재배 시스템에 관한 것으로, 구체적으로는 감초(甘草), 적하수오나 백하수오(何首烏), 당삼(堂參), 당귀(當歸), 황기(黃耆), 길경(桔梗) 또는 그 외의 곧은 뿌리(直根) 식물의 재배 용기를 세워진 채로 조밀하게 배치하여 단위 면적 당 재배량을 증가시키고, 수확시 소요되는 노동력을 최소화할 수 있으며, 재배 용기가 쓰러지지 않도록 하여 유지관리에 편리한 곧은 뿌리 식물 재배 시스템에 관한 것이다.본 발명은 내부에 흙이 수용되고, 상단과 하단이 개방되되 상광하협의 통 형태로 이루어지는 재배 용기; 및 상기 재배 용기가 세워진 채로 끼워지도록 복수의 끼움공이 소정 간격으로 이격되어 관통 형성되어 수평으로 배치되는 지지 플레이트와, 상기 끼움공을 통해 끼워진 재배 용기를 지지하도록 상기 지지 플레이트의 저면에서 상기 끼움공 둘레로부터 세로 방향으로 소정 길이로 연장되되 상기 끼움공 둘레를 따라 상호 간 이격되게 복수로 형성되는 지지 리브와, 상기 복수로 연장 형성된 지지 리브의 하단이 결합되되 상기 지지 플레이트의 저면과 평행하게 수평으로 형성되는 받침 플레이트로 구성되는 단위 지지틀;을 포함하고, 상기 단위 지지틀은 복수로 마련되어 상호 착탈 가능하게 이루어지는 것을 특징으로 하는 곧은 뿌리 식물 재배 시스템을 제공한다. claims: 내부에 흙이 수용되고, 상단과 하단이 개방되되 상광하협의 통 형태로 이루어지는 재배 용기; 및상기 재배 용기가 세워진 채로 끼워지도록 복수의 끼움공이 소정 간격으로 이격되어 관통 형성되어 수평으로 배치되는 지지 플레이트와, 상기 끼움공을 통해 끼워진 재배 용기를 지지하도록 상기 지지 플레이트의 저면에서 상기 끼움공 둘레로부터 세로 방향으로 소정 길이로 연장되되 상기 끼움공 둘레를 따라 상호 간 이격되게 복수로 형성되는 지지 리브와, 상기 복수로 연장 형성된 지지 리브의 하단이 결합되되 상기 지지 플레이트의 저면과 평행하게 수평으로 형성되는 받침 플레이트로 구성되는 단위 지지틀;을 포함하고,상기 재배 용기는,제1상단과 제1하단이 개방되되 상광하협의 통 형태로 이루어지는 상부 용기; 및제2상단과 제2하단이 개방되되 상광하협의 통 형태로 이루어지고, 상기 제2상단을 포함하는 제2상부 외면이 상기 상부 용기의 제1하단을 포함하는 제1하부 내면과 면접촉하면서 결합되도록 이루어진 하부 용기;를 포함하며,상기 상부 용기와 하부 용기가 결합된 상태로 상기 끼움공을 통해 상기 하부 용기와 상부 용기가 끼워지는 경우, 상기 하부 용기의 하단은 상기 받침 플레이트와 접촉하고 상기 끼움공의 직경은 상기 상부용기의 제1상부의 직경보다 작게 이루어져 상기 상부 용기의 제1상부는 상기 지지 플레이트의 상부로 노출되며,상기 단위 지지틀은 복수로 마련되어 상호 착탈 가능하게 이루어지되, 상기 단위 지지틀의 지지 플레이트는 소정 두께를 가지는 육면체 형태로 이루어지고, 상기 지지 플레이트의 네 측면에는 소정 형태로 결합 돌기가 돌출 형성되거나 상기 결합 돌기와 대응되게 결합홈이 형성되는 것을 특징으로 하는 곧은 뿌리 식물 재배 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

618/1059 Row 618: application_number: 1020190048059, combined_string: invention_title: 줄기 작물 재배용 화분 abstract: 본 발명에 따른 줄기 작물 재배용 화분은, 작물이 심어지는 화분 본체와, 상기 화분 본체에 결합되어 작물이 타고 올라올 수 있게 선형 부재를 지지하는 지지대를 포함하여 구성됨으로써, 간단한 구조로 토마토 등 줄기 작물을 용이하게 재배할 수 있는 효과를 제공한다. claims: 작물이 심어지는 화분 본체와, 상기 화분 본체에 결합되어 작물이 타고 올라올 수 있게 선형 부재를 지지하는 지지대를 포함한 것을 특징으로 하는 줄기 작물 재배용 화분., Ltext: 농업, prediction: 농업
619/1059 Row 619: application_number: 1020190033229, combined_string: invention_title: 딸기 재배용 화분 배수 받침대 abstract: 본 발명은 딸기 재배용 화분 배수 받침대에 관한 것으로, 그 구성은 평평한 판 형상을 가지며, 양측 각각에는 제1배수패널이 직립되게 세워져 내부에 중앙 배수로를 형성하되, 상기 제1배수패널이 딸기 작물이 재배되는 화분을 지지 고정하여 화분의 하부를 통해 배수되는 물이 자연스럽게 중앙 배수로로 유통되도록 하는 다수의 받침 배수판;과, 상기 받침 배수판과 인접하는 다른 받침 배수판을 서로 연결하여 상기 받침 배수판의 안정적인 연결을 유도하는 연결수단;으로 구성된 것을 특징으로 하는 것으로서, 내부에 중앙 배수로가 형성된 다수의 받침 배수판을 연결수단을 통해 지면에 간편히 연결 설치하고, 그 설치된 받침 배수판 상부에 딸기 재배를 위한 화분을 적층 안치함으로, 딸기의 성장을 위해 화분으로 뿌려지는 물은 화분의 하부를 통해 자연스럽게 중앙 배수로로 유통 배출되어 농양성분이 물과 함께 토양으로 침투하는 것을 안정적으로 방지할 수 있어 토양의 황폐화 및 오염을 효과적으로 예방할 수 있을 뿐만 아니라, 종래와 같이 지면에 골과 같은 배수로를 구축할 필요가 없어 배수로로 구축된 골이 붕괴되어 발생할 수 있는 다양한 문제점을 미연에 방지하여 딸기 작물의 안정적인 재배를 유도할 수 있는 효과가 있다.또한, 받침 배수판에 형성되는 중앙 배수로와 함께 외곽 배수로를 형성함으로 화분을 관통하여 화분 아래로 배출되는 물은 중앙 배수로에서 수집 배수하고 화분을 넘치는 일부의 물은 외곽 배수로에서 수집 배수하여 매우 안정적인 배수성을 확보할 수 있을 뿐만 아니라, 중앙 배수로를 형성하는 제1배수패널은 화분을 지지 고정하는 기능을 수행함으로 화분의 용이한 배치 및 설치를 유도할 수 있어 작업자에게 딸기 재배의 편의성을 제공할 수 있는 효과가 있다. claims: 평평한 판 형상을 가지며, 양측 각각에는 제1배수패널(11)이 직립되게 세워져 내부에 중앙 배수로(12)를 형성하되, 상기 제1배수패널(11)이 딸기 작물이 재배되는 화분(1)을 지지 고정하여 화분(1)의 하부를 통해 배수되는 물이 자연스럽게 중앙 배수로(12)로 유통되도록 하는 다수의 받침 배수판(10); 및상기 받침 배수판(10)과 인접하는 다른 받침 배수판(10)을 서로 연결하여 상기 받침 배수판(10)의 안정적인 연결을 유도하는 연결수단(20);을 포함하여 구성되는 것을 특징으로 하는 딸기 재배용 화분 배수 받침대., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

620/1059 Row 620: application_number: 1020190033116, combined_string: invention_title: 식물 재배 장치 abstract: 본 발명은 식물 재배 장치에 관한 것이다. 일 측면에 따른 식물 재배 장치는, 내부에 재배실이 구비되며, 일면이 개구되는 몸체; 상기 몸체의 개구된 일면을 차폐하는 도어; 상기 재배실의 하방에 배치되며, 식물이 파종되는 재배 베드; 상기 재배실의 상방에 배치되며, 상기 재배 베드로 광을 조사하는 광원 모듈; 및 상기 재배 베드와 광원 모듈의 사이에서 이동되며, 상기 광원 모듈에서 조사되는 광의 일부가 상기 재배 베드에 파종된 식물의 생장점으로 조사되도록 하는 광 가이드를 포함하는 것을 특징으로 한다. claims: 내부에 재배실이 구비되며, 일면이 개구되는 몸체;상기 몸체의 개구된 일면을 차폐하는 도어;상기 재배실의 하방에 배치되며, 식물이 파종되는 재배 베드;상기 재배실의 상방에 배치되며, 상기 재배 베드로 광을 조사하는 광원 모듈; 및상기 재배 베드와 광원 모듈의 사이에서 이동되며, 상기 광원 모듈에서 조사되는 광의 일부가 상기 재배 베드에 파종된 식물의 생장점으로 전달되도록 하는 광 가이드를 포함하는 식물 재배 장치., Ltext: 농업, prediction: 농업
621/1059 Row 621: application_number: 1020190031025, combined_string: invention_title: 딸기 재배용 접이식 육묘 장치 abstract: 본 발명은 딸기 재배용 접이식 육묘 장치에 관한 것으로, 베드 하방을 지지하는 구조물에 연결되며, 판상으로 마련되며 상부가 후방으로 절곡되고 상부에는 원형의 제 1구멍과 하부에는 장공의 제 2구멍이 마련되는 연결부와, 상기 연결부 끝단에 마련되며, 판상으로 상부가 후방으로 절곡되는 지지부와, 상기 연결부와 상기 지지부 사이에 마련되며, 상기 지지부가 접히도록 회전하는 힌지부로 구성되는 것을 특징으로 한다. claims: 베드 하방을 지지하는 구조물에 연결되며, 판상으로 마련되며 상부가 후방으로 절곡되고 상부에는 원형의 제 1구멍과 하부에는 장공의 제 2구멍이 마련되는 연결부;상기 연결부 끝단에 마련되며, 판상으로 상부가 후방으로 절곡되는 지지부;상기 연결부와 상기 지지부 사이에 마련되며, 상기 지지부가 접히도록 회전하는 힌지부;로 구성되는 것을 특징으로 하며,상기 제 2구멍의 가로축은 상기 제 1구멍의 중심을 기준으로 하방으로 일정거리 떨어지고, 좌측으로 회전시켜 얻은 원형의 자취인 것을 특징으로 하며,상기 연결부와 상기 지지부 하부에는 고정부가 더 마련되며, 균등한 간격으로 갈고리 모양의 홈이 마련되는 것을 특징으로 하며,상기 지지부 끝단 상부에 마련되는 돌출부를 더 포함하는 것을 특징으로 하는 딸기 재배용 접이식 육묘 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

622/1059 Row 622: application_number: 1020190029607, combined_string: invention_title: 딸기모종 분화 촉진방법 abstract: 본 발명은 지하로부터의 지하수를 펌핑하여 지상의 저수통에 보관하는 제1단계와, 지상의 저수통에 보관된 지하수를 냉교반기를 이용하여 냉기를 추출하는 제2단계와, 추출된 냉기를 냉기 공급관을 이용하여 딸기의 모종의 상토에 공급하는 제3단계 및 상토에 구성된 온도 센서의 측정값 일정치 이상이 되면 압력에 의해 냉기가 자동으로 공급되는 제4단계로 이루어지는 것을 특징으로 하며, 딸기 분화촉진을 위하여 상토에 직접 냉풍을 공급하여 상토의 온도를 낮춰주므로 모종의 활력증진으로 딸기의 상품성강화에 따른 농가수확을 증대시킬 수 있는 효과가 있다. claims: 지하로부터의 지하수를 펌핑하여 지상의 저수통에 보관하는 제1단계;지상의 저수통에 보관된 지하수를 냉교반기를 이용하여 냉기를 추출하는 제2단계;추출된 냉기를 냉기 공급관을 이용하여 딸기의 모종의 상토에 공급하는 제3단계;상토에 구성된 온도 센서의 측정값 일정치 이상이 되면 압력에 의해 냉기가 자동으로 공급되는 제4단계로 이루어지는 것을 특징으로 하는 딸기모종 분화 촉진방법., Ltext: 농업, prediction: 농업
623/1059 Row 623: application_number: 1020190026718, combined_string: invention_title: 작물 재배 시스템 abstract: 본 발명은 경작자가 파종에서부터 수확에 이르는 전 과정을 특정한 지점에서 일괄적으로 처리할 수 있는 작물재배용기의 순환이동을 통하여 넓은 면적을 이동하지 않고, 허리를 구부리거나 쭈그려 앉는 등의 일체의 노동 없이 영농이 가능하도록 한 작물 재배 시스템에 관한 것으로서, 전후좌우로 이동가능한 판상의 하부프레임(100)과, 상기 판상의 하부프레임(10)의 사각모퉁이에 세워진 사각 기둥 프레임(200)과, 상기 판상의 하부프레임(10)의 상면에 설치되는 작물 재배장치(300)로 이루어진 것을 특징으로 하고, 상기 작물 재배장치(300)는, 서로 대향되게 세워진 한 쌍의 기어프레임(310)과, 상기 한 쌍의 기어프레임(310) 내의 상부 및 하부에 내장되어 모터(M)에 의해 구동되는 스프로킷(320)과, 상기 상부 및 하부 스프로킷(320)에 감겨진 벨트(330)와, 상기 벨트(330)의 내측면에 서로 대칭되게 부착된 수평힌지부재(340)와, 상기 한 쌍의 수평힌지부재(340)의 사이에 회전 가능하게 설치된 회전봉(350)과, 상기 회전봉(350)의 하단에 각각 연결된 작물재배트레이(360)로 이루어진 것을 특징으로 한다. claims: 전후좌우로 이동가능한 판상의 하부프레임(100)과;상기 판상의 하부프레임(10)의 사각모퉁이에 세워진 사각 기둥 프레임(200)과;상기 판상의 하부프레임(10)의 상면에 설치되는 작물 재배장치(300)로 이루어진 것을 특징으로 하는 작물 재배 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

624/1059 Row 624: application_number: 1020190013436, combined_string: invention_title: 더덕 재배방법 및 장치 abstract: 본 발명은 더덕을 식재할 수 있도록 성장토를 채워넣는 장치바디와; 상기 장치바디의 외면에 피복하여 외부기온이 성장토로 전달되는 것을 방지하는 외기차단체와; 상기 외기차단체의 외부와 장치바디의 상면에 설치하여 식재된 더덕으로 햇빛이 직접 조사되는 것을 방지하면서 더덕 성장에 방해가 되는 잡초의 성장을 억제하는 마감피복체와; 상기 장치바디를 길이방향으로 길게 연결하여 두둑과 같은 형태를 유지하는 재배라인과; 상기 재배라인의 길이방향으로 식재된 더덕으로 성장에 필요한 성장수를 공급하도록 배설하는 관수라인과; 상기 장치바디와 장치바디 사이에 설치하여 더덕 줄기가 위로 뻗어갈 수 있게하는 줄기유도체를 포함하여 더덕재배장치를 구성하고;상기 더덕재배장치를 조성하는 더덕재배장치조성단계와; 더덕재배장치에 재배하고자 하는 더덕의 씨앗을 파종하거나 종묘를 식재하는 식재단게와; 식재된 더덕에 공급할 액비를 만드는 액비제조단계와; 액비와 수분 등을 더덕으로 주기적으로 공급하여 성장시키는 재배단계와; 재배된 더덕을 수확하는 수확단계로 재배하는 것이 특징이다. claims: 지면에 두둑형태를 유지하는 더덕재배장치(100)를 조성하는 더덕재배장치조성단계(S100)와;조성된 더덕재배장치(100)에 재배하고자 하는 더덕(101)의 씨앗을 파종하거나 종묘를 식재하는 식재단게(S200)와;더덕재배장치(100)에 식재된 더덕(101)에 공급할 액비를 만드는 액비제조단계(S300)와;제조된 액비와 수분 등을 더덕(101)으로 주기적으로 공급하여 성장시키는 재배단계(S400)와;재배된 더덕(101)을 수확하는 수확단계(S500)로 이루어지는 것을 특징으로 하는 더덕재배방법.상부에 더덕(101)을 식재할 수 있도록 상부개방부(102)를 두고 하부는 지면과 연통될 수 있는 하부개방부(103)를 가지고 내부에는 더덕(101)의 성장에 필요한 성장토(104)를 채워넣을 수 있도록 성장토공간(105)을 가지는 장치바디(106)와;상기 장치바디(106)의 외면에 피복하여 외부기온이 성장토(104)로 전달되어 장치바디(106)의 가장자리에 식재된 더덕(101)이 하절기에 열사하고 동절기에 동사하는 것을 방지하는 외기차단체(107)와;상기 외기차단체(107)의 외부와 장치바디(106)의 상면에 설치하여 식재된 더덕(101)으로 햇빛이 직접 조사되는 것을 방지하면서 더덕 성장에 방해가 되는 잡초의 성장을 억제하는 마감피복체(108)와;상기 장치바디(106)를 길이방향으로 길게 연결하여 두둑과 같은 형태를 유지하는 재배라인(110)과;상기 재배라인(110)의 길이방향으로 식재된 더덕(101)으로 성장에 필요한 성장수를 공급할 수 있도록 각각의 더덕(101) 방향으로 분사공(111)을 형성하여 배설하는 관수라인(112)과;상기 장치바디(106)와 장치바디(106) 사이에 고정하는 지주목(113)과, 지주목(113)의 상단에 재배라인(110) 방향의 길이로 연결하는 수평바(114)와, 수평바(114)의 양측에 성장하는 더덕(101)의 줄기가 위로 뻗어갈 수 있도록 연결하는 유도와이어(116)로 구성하는 줄기유도체(117)를 포함하는 것을 특징으로 하는 더덕재배장치., Ltext: 농업, prediction: 임업
625/1059 Row 625: application_number: 1020190012593, combined_string: invention_title: 셀레늄 또는 게르마늄 고함유 프리미엄 작물의 재배 방법 abstract: 본 발명은 셀레늄 또는 게르마늄 강화 작물의 재배 방법에 대한 것으로, 셀레늄 또는 게르마늄의 살포 시기를 최적화하여 셀레늄 또는 게르마늄 함량이 강화된 작물을 제공할 수 있다. claims: 셀레늄, 게르마늄 또는 이들의 조합을 작물에 2회 내지 4회 살포하는 것을 포하는 작물의 재배 방법. 제 1 항 내지 제 11 항 중 어느 한 항의 방법에 의해 재배된 셀레늄 또는 게르마늄 강화 작물., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

626/1059 Row 626: application_number: 1020210033039, combined_string: invention_title: 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철,분진발생공장에서 발생시키는 비산먼지 제거기능 및 혐오성 냄새 및 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템 abstract: 상측에는 본체 하우징(2000)이 구성되고;상기 본체 하우징(2000)의 내부에는 유입라인(1002)과 다수개의 이송라인(1001,1012)과 배출라인(3000)이 결합 구성되는 구조;상기 유입라인(1002)의 일측에는 유입펌프(1000)가 결합 구성되는 구조;상기 유입라인(1002)의 상측 부분은 건축물 또는 공장 또는 비행기 또는 버스 또는 차량 또는 공연장을 구성시킨 구조의 하우징(8888) 상측부분과 결합 구성되는 구조;상기 유입라인(1002)에는 비중이 가벼운 오염된 공기들을 유입시켜주는 다수개의 유입구(1003)가 구성되는 구조;상기 본체 하우징(2000)의 하측에는 다수개의 수납용 체결구(1004)가 상기 유입라인(1002)과 다수개의 상기 이송라인(1001,1012)과 상기 배출라인(3000)과 결합 구성되는 구조;상기 배출라인(3000)의 일측은 건축물 또는 공장 또는 비행기 또는 버스 또는 차량 또는 공연장을 구성시킨 하우징(8888)의 하단부 바닥부분에 설치되는 구조; 상기 배출라인(3000)의 상부에는 기체성 물질분자들을 분출시켜주는 다수개의 분출구(3003)가 결합 구성되는 구조;상기 이송라인(1001,1012)의 하단부에는 비중이 무거운 유체성 물질분자들은 하측 방향으로 이동시켜 주도록 작용하면서 비중이 가벼운 기체성 물질분자들은 일측 방향으로 이송시켜주도록 작용하는 중력 유도하우징(1007)이 각각 구성되는 구조;상기 중력 유도하우징(1007)의 하단부에는 중력 유도파이프(1005)가 결합 구성되는 구조;상기 중력 유도파이프(1005)의 하단부에는 유체성 물질분자 수집용 하우징(1006,1009)이 각각 구성되는 구조;상기 유체성 물질분자 수집용 하우징(1006,1009)의 일측에는 유체성물질분자 또는 비중이 가벼운 오염물질성 물질분자들을 외부로 배출하여 주는 하단 배출파이프(1010)가 배출조절밸브(1011)와 결합 구성되는 구조;상기 수납용 체결구(1004)의 하단부에는 배출량 조절밸브(3002)와 배출파이프가 결합 구성되어 있는 액체성 필터부재하우징(1,2,3)이 착탈이 용이하도록 상기 수납용 체결구(1004)와 결합 구성되는 친환경 다기능 공기 정화시스템(888888)을 건축물 또는 공장 또는 비행기 또는 버스 또는 차량 또는 공연장을 구성시킨 하우징(8888)에 설치한 후 상기 액체성 필터부재하우징(1,2,3)의 내부에 물 또는 알콜이나 소금물을 구성하고 있는 유체성 물질분자로 구성되어 지는 필터 부재들을 순차적으로 충진시킨 상태에서 상기 유입라인(1002)과 결합 되어 있는 상기 유입펌프(1000)를 이용하여 상기 하우징(8888)의 내부와 상측 부분에 포진하고 있는 비중이 가벼운 오염된 공기들을 포집하여 상기 액체성 필터부재하우징(1,2,3)의 내부로 이송시켜서 상기 액체성 필터부재하우징(1,2,3)의 내부에 충진되어 있는 물 또는 알콜이나 소금물로 구성되어 지는 필터 부재들이 발생시키는 필터링 기능을 이용하여 비중이 무거운 깨끗한 공기와 결합 되어 있는 비중이 가벼운 오염물질성 물질분자로 구성되어 있는 미세먼지들을 제거시켜주는 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 가지는 다기능 공기정화시스템을 이용하여 사람이 거주하는 건축물, 학교, 군대의 막사, 공장, 동물을 사육하는 축사, 사무실에 존재하는 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 공기 정화시스템에 관한 발명이다 claims: 친환경 다기능 공기 정화시스템의 구조는 상측에는 본체 하우징이 구성되는 구조;상기 본체 하우징의 내부에는 유입라인과 다수개의 이송라인과 배출라인이 결합 구성되는 구조;상기 유입라인의 일측에는 유입펌프가 결합 구성되는 구조;상기 유입펌프의 타측에는 살균시스템하우징을 설치한 후 상기 살균시스템하우징의 내부에 -전극과 +전극을 교차 설치하여 유입라인을 통하여 유입되는 미세균들과 바이러스 균들을 살균하도록 구성되는 구조;상기 이송라인의 하단부에는 비중이 무거운 유체성 물질분자들은 하측 방향으로 이동시켜 주도록 작용하면서 비중이 가벼운 기체성 물질분자들은 일측 방향으로 이송시켜주도록 작용하는 중력 유도하우징이 각각 구성되는 구조; 상기 본체 하우징의 하측에는 다수개의 수납용 체결구가 구성되어 상기 유입라인과 다수개의 상기 이송라인과 상기 배출라인을 상호 결합시킨 구조;상기 중력 유도하우징의 하단부에는 중력 유도파이프가 결합 구성되는 구조;상기 중력 유도파이프의 하단부에는 유체성 물질분자 수집용 하우징이 다수개 구성되는 구조;상기 유체성 물질분자 수집용 하우징의 일측에는 유체성물질분자 또는 비중이 가벼운 오염물질성 물질분자들을 외부로 배출하여 주는 하단 배출파이프가 배출조절밸브와 결합 구성되는 구조;상기 수납용 체결구의 하단부에는 배출량 조절밸브와 배출파이프가 결합 구성되어 액체를 투입하도록 구성되는 액체성 필터부재하우징이 착탈이 용이하도록 상기 수납용 체결구와 결합 구성되는 구조;상기 액체성 필터부재하우징의 내부에는 상기 이송라인이 결합 구성되는 구조;액체성 필터부재하우징과 상기 유체성 물질분자 수집용 하우징의 일측 또는 타측에 전자파발생기를 설치하여 중력의 작용에 의해 상기 액체성 필터부재하우징과 상기 유체성 물질분자 수집용 하우징의 내부로 유입되는 기체성 물질분자 또는 액체성 물질분자 또는 비중이 가벼운 유체성 물질분자들을 타격하여 이들 물질분자가 가지고 있는 분자구조를 변형시키도록 구성되는 친환경 다기능 공기 정화시스템을 사람이 거주하는 아파트 또는 사무실이나 학교 또는 군대의 막사 또는 사람이 거주하는 건축물 또는 가축을 사육하는 농장 또는 공장 또는 발전소 또는 제철소 또는 비행기 또는 버스 또는 차량 또는 식물을 재배하는 재배사 또는 공연장의 구조로 구성되는 하우징에 설치한 후 상기 액체성 필터부재하우징와 상기 유체성 물질분자 수집용 하우징의 내부에 향기를 발산시켜주는 향기 발산 부재 또는 물 또는 알콜이나 소금물 또는 바닷물 또는 숯과 물을 희석하여 만든 숯 혼합물로 구성되어 지는 필터 부재들을 순차적으로 충진시킨 상태에서 상기 유입라인과 결합 되어 있는 상기 유입펌프를 이용하여 상기 하우징에서 발생시키는 오염된 공기 또는 상기 하우징의 내부와 상측 부분에 포진하고 있는 비중이 가벼운 오염된 공기들을 포집하여 상기 액체성 필터부재하우징과 상기 유체성 물질분자 수집용 하우징의 내부로 이송시켜서 상기 액체성 필터부재하우징의 내부와 상기 유체성 물질분자 수집용 하우징에 충진되어 있는 물 또는 알콜이나 소금물로 구성되는 필터 부재들이 발생시키는 필터링 기능을 이용하여 비중이 무거운 깨끗한 공기와 결합 되어 있는 비중이 가벼운 오염물질성 물질분자로 구성되어 있는 미세먼지들을 제거시켜주는 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 주도록 구성되는 친환경 다기능 공기 정화시스템을 이용하여 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철,분진발생공장에서 발생시키는 비산먼지 제거기능 및 혐오성 냄새 및 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템친환경 다기능 공기 정화시스템의 구조는 하측에는 본체 하우징이 구성되는 구조;상기 본체 하우징의 상측에는 공기 주입장치(미도시)와 결합 구성되는 유입라인이 일측의 상단부는 ㄱ자 형태이면서 하단부는 ㄷ자 형태로 구성되는 구조;상기 유입라인의 상부에는 착탈식으로 구성되는 수납용 체결구가 상부에 구성되어 있는 제1 여과하우징이 구성되는 구조;상기 제1 여과하우징의 내부에는 광물성 물질이나 바닷물 또는 소금물 또는 민물 또는 화공약품으로 구성되는 유체성 물질분자로 구성된 여과부재(점선으로 표시하였으나 부호는 미도시)를 상기 유입라인의 상층부분 까지 연결 구성되는 제1배출구가 잠기지 않는 위치까지 투입시킨 구조;상기 제1 여과하우징의 다음 단계에는 공기와 결합되어 있는 수분을 분리시켜주도록 작용하는 제1수분 분리하우징이 구성되는 구조;상기 제1 여과하우징과 상기 제1수분 분리하우징의 사이에는 하단부 제1연결 파이프가 상기 제1 여과하우징 방향으로 경사지게 구성되어 상기 제1수분 분리하우징의 내부로 유입되는 유체성 물질분자들을 상기 제1 여과하우징으로 유입시켜주도록 작용하는 구조;상기 제1 여과하우징의 하단부분과 상기 제1수분 분리하우징의 상단부 사이에는 상기 여과부재에 의해 제1 유입구가 잠수된 상태가 되는 위치를 기준으로 상기 제1수분 분리하우징의 상측 부분까지 ㄷ자 형태로 연결하여 2차 연결 파이프가 연결 구성되는 구조;상기 제1수분 분리하우징의 다음 단계에는 수납용 체결구가 상부에 구성되어 있는 제2 여과하우징을 구성시킨 구조;상기 제2 여과하우징의 내부에는 광물성 물질이나 바닷물 또는 소금물 또는 민물 또는 화공약품으로 구성되는 액체로 구성된 유체성 물질분자를 이용하여 구성되는 여과부재(점선으로 표시하였으나 부호는 미도시)를 투입시킨 구조;상기 제1수분 분리하우징의 상측부분과 제2 여과하우징의 하측 부분 사이에는 2차 연결 파이프가 ㄷ자 형태로 연장되어 상기 제2 여과하우징의 내부에 투입되어 있는 여과부재의 상측 부분까지 연결된후 상측 부분에 구성되는 제2 배출구가 여과부재에 잠기지 않고 노출되는 형태로 구성되는 구조; 상기 제2 여과하우징의 다음 단계에는 제2수분 분리하우징이 구성되는 구조;상기 제2 여과하우징과 상기 제2수분 분리하우징의 사이에는 하단부 제2연결 파이프가 상기 제2 여과하우징 방향으로 경사지게 구성되어 상기 제2수분 분리하우징의 내부로 유입되는 바닷물 또는 민물 또는 소금과 희석시킨 소금물을 구성하고 있는 유체성 물질분자들을 상기 제2 여과하우징으로 유입시켜주도록 작용하는 연결 구조;상기 제2 여과하우징의 하단부와 제2 수분 분리하우징의 상단부 사이에는 상기 여과부재에 의해 제2 유입구가 잠수된 상태가 되는 위치를 기준으로 상기 제2수분 분리하우징의 상측 부분까지 ㄷ자 형태로 연결되는 3차 연결 파이프가 결합 구성되는 구조;제2 수분 분리하우징의 다음 단계에는 수납용 체결구가 상부에 구성되어 있는 제3 여과하우징이 구성되는 구조;제2 수분 분리하우징의 상측부분과 제3 여과하우징의 하측 부분 사이에는 3차 연결 파이프가 ㄷ자 형태로 연장되어 상기 제3 여과하우징의 내부에 투입되어 있는 여과부재의 상측 부분에 제3 배출구가 노출되는 형태로 결합 구성되는 구조;상기 제3 여과하우징의 다음 단계에는 제3 수분 분리 하우징이 구성되는 구조;상기 제3 여과하우징과 상기 제3 수분 분리 하우징의 사이에는 하단부 제3연결 파이프가 상기 제3 여과하우징 방향으로 경사지게 구성되어 상기 제3수분 분리하우징의 내부로 유입되는 바닷물 이나 민물 또는 소금을 희석하여 만든 소금물을 구성하고 있는 유체성 물질분자들을 상기 제3여과 하우징으로 유입시켜 주도록 연결시킨 구조;상기 제3 여과하우징의 하단부와 제3 수분 분리하우징의 상단부 사이에는 상기 여과부재에 의해 제3 유입구가 잠수된 상태가 되는 위치를 기준으로 상기 제3수분 분리하우징의 상측 부분까지 ㄷ자 형태로 연결하여 4차 연결 파이프를 결합 시킨 구조;상기 4차 연결 파이프의 일측에는 배출파이프를 결합시킨 자연친화적인 친환경 공기정화시스템을 특징으로하는 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철,분진발생공장에서 발생시키는 비산먼지 제거기능 및 혐오성 냄새 및 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템, Ltext: 농업, prediction: 임업
627/1059 Row 627: application_number: 1020210029442, combined_string: invention_title: 산마늘의 재배방법 abstract: 본 발명은 산마늘의 재배방법에 관한 것으로, 더욱 상세하게는 산마늘 종구를 상토에 식재하는 식재단계, 상기 식재단계를 통해 상토에 식재된 산마늘 종구를 발근시키는 발근단계, 상기 발근단계를 통해 발근된 산마늘 종구를 저온에 적응시키는 온도적응단계, 상기 온도적응단계를 통해 낮은 온도에 적응된 산마늘 종구가 식재된 상토를 냉동하는 냉동단계, 상기 냉동단계를 통해 냉동된 상토를 산마늘 출하 25 내지 30일 전에 해동하는 해동단계 및 상기 해동단계를 통해 해동된 상토에 함유된 산마늘 종구를 생장시키는 생장단계로 이루어진다.상기의 과정을 통해 이루어지는 산마늘의 재배방법은 각종 영양성분이 풍부하게 함유된 산마늘을 계절에 관계없이 상시 재배할 수 있고, 원하는 시기에 맞게 계획생산 할 수 있어 스파트 팜 시스템에 적용 가능한 효과를 나타내며, 키트형태인 상토상자가 적용되어 일반인들도 베란다나 텃밭과 같이 협소한 공간에서도 산마늘을 손쉽게 재배할 수 있도록 하는 효과를 나타낸다. claims: 산마늘 종구를 상토에 식재하는 식재단계;상기 식재단계를 통해 상토에 식재된 산마늘 종구를 발근시키는 발근단계;상기 발근단계를 통해 발근된 산마늘 종구를 저온에 적응시키는 온도적응단계;상기 온도적응단계를 통해 낮은 온도에 적응된 산마늘 종구가 식재된 상토를 냉동하는 냉동단계;상기 냉동단계를 통해 냉동된 상토를 산마늘 출하 25 내지 30일 전에 해동하는 해동단계; 및상기 해동단계를 통해 해동된 상토에 함유된 산마늘 종구를 생장시키는 생장단계;로 이루어지며,상기 상토는 코코피트 100 중량부, 질석 20 내지 30 중량부, 퍼라이트 50 내지 70 중량부, 제올라이트 5 내지 10 중량부 및 액비 5 내지 10 중량부로 이루어지고,상기 온도적응단계는 -1 내지 2℃의 온도에서 6 내지 8일 동안 이루어지며,상기 냉동단계는 -15 내지 -10℃의 온도로 이루어지고,상기 해동단계는 0 내지 15℃의 온도에서 6 내지 16일 동안 이루어지는 것을 특징으로 하는 산마늘의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

628/1059 Row 628: application_number: 1020210012671, combined_string: invention_title: 용암해수를 활용하여 재배한 병풀을 유효성분으로 포함하는 피부 마이크로바이옴 균형 및 여드름 개선용 조성물 abstract: 본 발명은 용암해수로 활용하여 재배한 병풀(Centella asiatica) 추출물을 포함하는 피부 마이크로바이옴 균형 및 여드름 개선용 조성물 내지 이의 용도에 대한 것이다. 본 발명의 병풀 추출물은 탈염 용암해수로 재배되어 세포독성을 나타내지 않고, 세포 내 NO 생성을 억제하고 항염증 활성을 나타내며, 여드름 피부 개선에서 더 나아가 피부 마이크로바이옴의 균형을 개선하는 효과가 있으므로, 피부 마이크로바이옴 균형 개선용 조성물로서 효과적으로 이용될 수 있다. 특히, 상기 조성물은 작약 추출물을 추가적으로 포함함으로써 피부 마이크로바이옴 균형 개선 효과가 더욱 증가될 수 있다. claims: 탈염 용암해수를 사용하여 재배한 병풀(Centella asiatica) 추출물 및 작약(Paeonia lactiflora) 추출물을 유효성분으로 포함하며, 피부 유해균총의 분포도를 감소시켜 피부 마이크로바이옴 균형을 유지하되, 상기 피부 유해균은 큐티박테리움 아크네스 속(Cutibacterium acnes group) 및 스타필로코커스 아우레우스 속(Staphylococcus aureus group)인 것을 특징으로 하는 여드름 개선용 화장료 조성물.탈염 용암해수를 사용하여 재배한 병풀(Centella asiatica) 추출물 및 작약(Paeonia lactiflora) 추출물을 유효성분으로 포함하며, 피부 유해균총의 분포도를 감소시켜 피부 마이크로바이옴 균형을 유지하되, 상기 피부 유해균은 큐티박테리움 아크네스 속(Cutibacterium acnes group) 및 스타필로코커스 아우레우스 속(Staphylococcus aureus group)인 것을 특징으로 하는 여드름 개선용 건강기능식품 조성물. 탈염 용암해수를 사용하여 재배한 병풀(Centella asiatica) 추출물 및 작약(Paeonia lactiflora) 추출물을 유효성분으로 포함하며, 피부 유해균총의 분포도를 감소시켜 피부 마이크로바이옴 균형을 유지하되, 상기 피부 유해균은 큐티박테리움 아크네스 속(Cutibacterium acnes group) 및 스타필로코커스 아우레우스 속(Staphylococcus aureus group)인 것을 특징으로 하는 여드름 개선용 반려용품 조성물., Ltext: 농업, prediction: 임업
629/1059 Row 629: application_number: 1020210011922, combined_string: invention_title: 나노유기게르마늄 및 나노유기셀레늄을 이용한 기능성 작물의 재배방법 abstract: 본 발명은 나노유기게르마늄 및 나노유기셀레늄을 이용한 기능성 작물의 재배방법에 관한 것으로, 유기 게르마늄과 유기 셀레늄을 물리적인 에너지(열 또는 압력)를 부가하는 방법, 전기적인 폭발에너지를 부가하는 방법, 및 화학적 결합 공정 중에서 선택된 하나 또는 두 가지 이상을 수행하여 나노 크기로 제조한 나노 크기의 유기게르마늄과 나노 크기의 유기셀레늄을 작물의 성장 발육이 가장 왕성하게 되는 싯점과 결실을 이루기 위하여 성숙해 가는 시기에 적어도 2회 이상 관주 또는 엽면시비를 수행하는 것으로서, 제조된 나노 크기의 유기게르마늄과 나노 크기의 유기셀레늄은 나노 크기 상태에서 물을 용매로 수분산이 된 1액형의 물질인 것을 특징으로 한다. claims: 나노유기게르마늄 및 나노유기셀레늄을 이용한 기능성 작물의 재배방법에 있어서,유기 게르마늄과 유기 셀레늄을 물리적인 에너지(열 또는 압력)를 부가하는 방법, 전기적인 폭발에너지를 부가하는 방법, 및 화학적 결합 공정 중에서 선택된 하나 또는 두 가지 이상을 수행하여 나노 크기로 제조한 나노 크기의 유기게르마늄과 나노 크기의 유기셀레늄을 작물의 성장 발육이 가장 왕성하게 되는 싯점과 결실을 이루기 위하여 성숙해 가는 시기에 적어도 2회 이상 관주 또는 엽면시비를 수행하는 것으로서,제조된 나노 크기의 유기게르마늄과 나노 크기의 유기셀레늄은 나노 크기 상태에서 물을 용매로 수분산이 된 1액형의 물질인 것을 특징으로 하는 나노유기게르마늄 및 나노유기셀레늄을 이용한 기능성 작물의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

630/1059 Row 630: application_number: 1020210006688, combined_string: invention_title: 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철에 존재하는 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템 abstract: 본 발명은 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 역사 같이 건축물 형태로 구성되어지는 하우징의 천장에 공기가 유동되도록 구성되는 2중 천장을 추가 구성하여 공기 유통하우징을 구성시킨 구조;상기 2중 천장에는 다수개의 공기 유통구를 구성시킨 구조;상기 공기 유통하우징의 일측에는 공기를 공급하여 주거나 뽑아주도록 작용하는 유입라인과 결합하여 중력의 작용에 의해 하우징의 상층부로 부상하는 오염된 공기를 포집하여 제거하여 주거나 포집시킨 공기를 정화하여 재 주입하도록 구성되는 친환경 다기능 공기 정화시스템에 관한 발명이다 claims: 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 역사 같이 건축물 형태로 구성되어 지는 하우징의 천장에 공기가 유통 되도록 구성되는 2중 천장을 추가 구성하여 공기 유통하우징을 구성시킨 구조;상기 2중 천장에는 다수개의 공기 유통구를 구성시킨 구조;상기 공기 유통하우징의 일측에는 공기를 공급하여 주거나 뽑아주도록 작용하는 유입라인과 결합하여 중력의 작용에 의해 하우징의 상층부로 부상하는 오염된 공기를 포집하여 제거하여 주거나 포집시킨 공기를 정화하여 재 주입하도록 구성되는 친환경 다기능 공기 정화시스템을 특징으로하는 건축물,병원,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 에 존재하는 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 역사 같이 건축물 형태로 구성되어지는 하우징의 상측에 비중이 가벼운 오염된 공기가 비중의 차이와 중력의 작용에 의해 일측 방향에서 타측 방향으로 흐르도록 유도하여 주는 2중 천장을 건축물의 천장 하단부에 경사진 형태로 추가로 구성시킨후 공기가 유통되도록 구성된 공기 유통구가 구성되어 있는 3중 천장을 상기 2중 천장의 하단부에 경사진 형태로 추가로 덧 대어 구성하여 비중이 가벼운 오염된 공기가 중력의 작용에 의해 외부로 자연배출 되도록 작용하는 배출구을 하우징의 일측에 결합 구성시킨 3중 천장의 구조를 이용하여 비중이 가벼운 오염된 공기를 하우징의 외부로 자연배출 시키도록 구성되는 자연친화적인 친환경 다기능 공기 정화시스템을 특징으로하는 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철에 존재하는 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 역사 같이 건축물 형태로 구성되어 지는 하우징의 상측 코너에 비중이 가벼운 오염물질성 물질분자들을 수집하여 주는 수집구와 결합 되어진 수집라인을 건축물의 일측에 구성되는 공기 정화시스템과 결합 구성하여 중력의 작용에 의해 상기 하우징의 상측 방향으로 자동 부상하는 비중이 가벼운 유해물질성 물질분자들을 상기 수집구와 결합 되어진 수집라인과 상기 공기 정화시스템을 이용하여 상기 하우징의 상층부에 포진하고 있는 비중이 가벼운 오염된 공기를 수집하여 정화하는 친환경 다기능 공기 정화시스템을 특징으로 하는 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철에 존재하는 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

631/1059 Row 631: application_number: 1020210005768, combined_string: invention_title: 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치 및 그 재배방법 abstract: 본 발명은 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치 및 그 재배방법에 관한 것으로, 보다 상세하게는 엽채 등과 같은 저온 식용식물을 안정적으로 온도관리하여 계속적으로 엽채를 수확할 수 있는 조건을 조성하므로 수확량을 2~5배 증산할 수 있는 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치 및 그 재배방법에 관한 것이다. 본 식용식물 재배장치는 식용식물의 추대방지를 위한 요구온도의 수분이 일정량 요구되는 높이의 수위에 위치하고 그 과잉분량을 회수하기 위한 유출구를 가지고 있으며, 식용식물이 생육하는 용토환경을 제공하는 재배용기와; 상기 재배용기의 요구되는 높이만큼 수용되고, 상기 식용식물의 추대방지를 위한 요구온도의 수분을 흡수하여 점진적으로 배출하는 수분흡수부재와; 상기 수분흡수부재 상에 수평적으로 균등하게 위치하며, 상기 수분을 수분흡수부재의 평판영역에 균등하게 공급하여 보습상태를 유지하여 근권부의 생장을 촉진시키고, 하측의 수분영역과 상측의 식물 식재영역의 생육용토를 분리시키는 부직포분리부재와; 상기 부직포분리부재의 상측에 상기 식용식물을 식재하여 생육환경을 제공하는 생육용토와; 상기 재배용기의 유출구로 과잉분량의 수분을 회수하여 하기 수분냉각교환기로 이송시키는 회수관과; 상기 회수관으로부터 회수되는 수분을 요구되는 온도이하로 열교환하여 상기 수조용기에 수용된 수분이 상기 식용식물의 추대방지를 위한 요구되는 온도를 유지하기 위한 수분냉각교환기와; 상기 수분냉각교환기로부터 열교환으로 냉각된 수분을 상기 점적관수부재로 순환시키는 수분순환관과; 상기 수분순환관의 냉각된 수분을 상기 재배용기 상측에서 점적으로 공급하고 상기 생육용토를 보습상태로 유지하여 생육용토가 근권부의 생육활성화로 추대방지를 위한 요구되는 온도를 유지하면서 식용식물에게 수분을 공급하기 위한 점적출구부재와; 상기 재배용기의 내측면과 외측면 중 어느 일측에 배치되어 있으며, 점적 공급된 수분의 열손실을 최소화하기 위한 재배단열부재를 포함한다. claims: 바닥면이 소정의 높이만큼 융기된 단차를 갖는 평판 융기부와, 상기 평판 융기부의 주위 원주영역에 재배용기의 원주 내경면에 의해 이격공간을 가지며, 식용식물을 식재하는 재배용기와;상기 재배용기의 이격공간에 상기 융기부의 높이만큼 수용되고, 상기 식용식물의 추대방지를 위한 요구온도의 수분을 흡수하여 점진적으로 배출하는 수분흡수부재와;상기 수분흡수부재와 융기부에 균등하게 위치하며, 상기 수분을 융기부와 수분흡수부재의 평판영역에 균등하게 공급하여 보습상태를 유지하여 근권부의 생장을 촉진시키고, 하측의 수분영역과 상측의 식물 식재영역의 생육용토를 분리시키는 부직포분리부재와;상기 부직포분리부재의 상측에 상기 식용식물을 식재하여 생육환경을 제공하는 생육용토와;상기 재배용기의 바닥영역이 잠기도록 배치되어 있으며, 상기 식용식물의 추대방지를 위한 요구온도의 수분 즉 물을 저장하고 있는 수조용기와;상기 수조용기의 수분이 일정량 요구되는 높이에 위치하고 그 수용된 수분의 과잉분량을 회수하는 회수관과;상기 회수관으로부터 회수되는 수분을 요구되는 온도이하로 열교환하여 상기 수조용기에 수용된 수분이 상기 식용식물의 추대방지를 위한 요구되는 온도를 유지하기 위한 수분냉각교환기와;상기 수분냉각교환기로부터 열교환으로 냉각된 수분을 하기 수분공급구로 순환시키는 수분순환관과;상기 수분순환관의 냉각된 수분을 상기 재배용기 상측에서 공급하고 상기 생육용토를 보습상태로 유지하여 생육용토가 근권부의 생육활성화로 추대방지를 위한 요구되는 온도를 유지하면서 식용식물에게 수분을 공급하기 위한 수분공급구와;상기 수조용기의 내측면과 외측면 중 어느 일측에 배치되어 있으며, 수용된 수분의 온도가 열손실없이 유지되도록 한 수조단열부재와;상기 재배용기의 내측면과 외측면 중 어느 일측에 배치되어 있으며, 점적 공급된 수분의 열손실을 최소화하기 위한 재배단열부재와;상기 수조용기와 재배용기 사이에 노출된 영역에서 열손실을 방지하는 노출단열부재를 포함하는 것을 특징으로 하는 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치.재배용기와 수분흡수부재, 수분흡수패드, 생육용토, 회수관, 수분냉각교환기, 수분순환관을 갖는 식용식물 재배장치를 활용한 수확량 유지 및 수확량 조절을 위한 식용식물 재배방법에 있어서;상기 식용식물 재배장치의 재배용기에 수용된 생육용토에 식재된 식용식물이 기후적으로 근권부 생리장애의 방지온도 20℃ 이하에서 그 20℃ 이하의 기후적 온도에 해당하는 수분을 공급하여 자연기후로 생육재배하는 자연적 생육재배단계와;상기 식용식물 재배장치의 재배용기에 수용된 생육용토에 식재된 식용식물에 근권부 생리장애 방지온도 20℃ 이상에서 발생하는 추대를 방지하기 위하여 상기 생육용토에 공급하는 수분의 요구온도를 상기 수분냉각교환기에 의해 15~20℃범위로 조절하고, 이에 따라 식용식물의 근권부 생리장애를 억제하여 추대방지상태의 생육을 유지하는 추대방지 생육재배단계와;상기 추대방지 생육재배단계가 연속적으로 진행되면서 상기 식용식물의 근권부 생리작용이 정상적으로 생육 활성화되고, 이에 따라 추대를 방지하는 생리적 생장이 정상적으로 이루어져 수확기간을 연장 및 증대하는 수확활성화단계와;상기 식용식물 재배장치의 재배용기에 수용된 생육용토에 식재된 식용식물이 기후적으로 자연재배기간에서 생산량이 극대화되어 생산과잉 상태로 판단되면, 상기 식용식물 근권부의 생육용토에 공급하는 수분의 휴면온도를 조성하여 생리적 생육이 정지되도록 그 휴면온도를 상기 수분냉각교환기에 의해 1~3℃범위로 조절하고, 이에 따라 관리자가 원하는 기간동안 휴면재배상태를 유지하는 휴면 생육재배단계를 포함하는 것을 특징으로 하는 수확량 유지 및 수확량 조절을 위한 식용식물 재배방법.식용식물의 추대방지를 위한 요구온도의 수분이 일정량 요구되는 높이의 수위에 위치하고 그 과잉분량을 회수하기 위한 유출구를 가지고 있으며, 식용식물이 생육하는 용토환경을 제공하는 재배용기와;상기 재배용기의 요구되는 높이만큼 수용되고, 상기 식용식물의 추대방지를 위한 요구온도의 수분을 흡수하여 점진적으로 배출하는 수분흡수부재와;상기 수분흡수부재 상에 수평적으로 균등하게 위치하며, 상기 수분을 수분흡수부재의 평판영역에 균등하게 공급하여 보습상태를 유지하여 근권부의 생장을 촉진시키고, 하측의 수분영역과 상측의 식물 식재영역의 생육용토를 분리시키는 부직포분리부재와;상기 부직포분리부재의 상측에 상기 식용식물을 식재하여 생육환경을 제공하는 생육용토와;상기 재배용기의 유출구로 과잉분량의 수분을 회수하여 하기 수분냉각교환기로 이송시키는 회수관과;상기 회수관으로부터 회수되는 수분을 요구되는 온도이하로 열교환하여 상기 재배용기에 수용된 수분이 상기 식용식물의 추대방지를 위한 요구되는 온도를 유지하기 위한 수분냉각교환기와;상기 수분냉각교환기로부터 열교환으로 냉각된 수분을 상기 생육용토에 수분공급구로 순환시키는 수분순환관과;상기 수분순환관의 냉각된 수분을 상기 재배용기 상측에서 점적으로 공급하고 상기 생육용토를 보습상태로 유지하여 생육용토가 근권부의 생육활성화로 추대방지를 위한 요구되는 온도를 유지하면서 식용식물에게 수분을 공급하기 위한 수분공급구와;상기 재배용기의 내측면과 외측면 중 어느 일측에 배치되어 있으며, 점적 공급된 수분의 열손실을 최소화하기 위한 재배단열부재를 포함하는 것을 특징으로 하는 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치., Ltext: 농업, prediction: 임업
632/1059 Row 632: application_number: 1020200172622, combined_string: invention_title: 라이조푸스 속 균주와 키토산, 사포닌 및 동물성 아미노산을 포함하여 항비만, 항암, 항당뇨 및 면역력 향상 효과를 갖는 농작물 재배가 가능한 액상 비료 조성물 및 이의 제조방법 abstract: 본 발명은 라이조푸스 속 균주 배양물, 키토산 분해 균주 배양물, 동물성 아미노산 발효물 및 사포닌액을 포함하는 액상 비료 조성물 및 이의 제조방법에 관한 것으로, 이를 이용하여 농작물을 재배하는 경우 농작물의 생육 효과 향상, 병충해 방제, 당도 향상, 농작물 내 조사포닌 함량 증진 효과를 제공할 뿐만 아니라 이를 이용하여 재배된 농작물 섭취 시 항비만, 항암, 항당뇨 및 면역력 향상 효과를 제공한다. claims: 라이조푸스 속(Rhizopus) 균주 배양물 0.01 중량부 내지 20 중량부;키토산 분해 균주를 이용하여 키토산을 분해한 분해물 0.01 중량부 내지 20 중량부;동물성 아미노산 발효물 0.01 중량부 내지 20 중량부; 및 사포닌액 0.01 중량부 내지 10 중량부;를 포함하고, 당, 솔빈산가리(potassium sorbate), 아황산나트륨(sodium sulfite), EDTA(ethylenediaminetetraacetic acid), 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산으로 이루어진 군으로부터 선택된 하나 이상을 포함하며, 상기 동물성 아미노산 발효물은 가축 혈액 80 내지 90 중량부, 브로멜라인 4 내지 6 중량부, 키모트립신 3 내지 4 중량부, 파파인 1 내지 3 중량부, 양파 껍질 분말 2.5 내지 3.5 중량부 및 버섯 분말 0.5 내지 1 중량부를 포함하는 액상 비료 조성물.키토산 분해 균주를 이용하여 키토산을 분해한 분해물을 제조하는 단계, 라이조푸스 균주 배양물을 제조하는 단계, 동물성 아미노산 발효물을 제조하는 단계 및 사포닌액을 준비하는 단계를 각각 순서에 무관하게 수행하는 원료를 준비하는 단계; 상기 키토산 분해 균주를 이용하여 키토산을 분해한 분해물, 상기 라이조푸스 균주 배양물, 상기 동물성 아미노산 발효물, 상기 사포닌액 및 당의 혼합물을 배양하여 배양액을 얻는 단계; 및 상기 배양액에 솔빈산가리, 아황산나트륨, EDTA, 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산으로 이루어진 군으로부터 선택된 하나 이상을 첨가하고 교반하는 단계;를 포함하고, 상기 동물성 아미노산 발효물을 제조하는 단계는, 도축 과정에서 얻어지는 가축 혈액 100 중량부에 대하여 3 내지 5 중량부의 1차 단백질분해효소를 첨가하고 1차 발효시켜 1차 발효물을 얻는 단계 및 상기 1차 발효물 100 중량부에 대하여 5 내지 10 중량부의 2차 단백질분해효소 및 3 내지 5 중량부의 첨가제를 첨가하고 2차 발효시켜 2차 발효물을 얻는 단계를 포함하며, 상기 1차 단백질분해효소는 브로멜라인 및 키모트립신을 1:3~5 중량비로 혼합하여 사용하고,상기 2차 단백질분해효소로 브로멜라인 및 파파인을 1:0.3~0.5 중량비로 혼합하여 사용하며, 상기 첨가제로 양파 껍질 분말 및 버섯 분말을 1:0.1~0.3 중량비로 혼합하여 사용하는, 액상 비료 조성물을 제조하는 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

633/1059 Row 633: application_number: 1020200146554, combined_string: invention_title: 인삼 재배방법 abstract: 본 발명은 인삼 재배방법에 관한 것으로, 보다 상세하게는 광 조사를 통해 인삼의 생육을 증대시킬 수 있는 인삼 재배방법에 관한 것이다.본 발명의 인삼 재배방법은, 싹을 틔운 묘삼을 준비하는 제 1단계; 상기 싹을 틔운 묘삼을 수경 재배시설로 정식하는 제 2단계; 및 상기 정식된 인삼을 성장시키는 제 3단계;를 포함하고, 상기 제 3단계의 인삼을 성장시키는 단계에서는, 상기 인삼에 광을 조사하는 단계 포함하는 것을 특징으로 한다. claims: 싹을 틔운 묘삼을 준비하는 제 1단계;상기 싹을 틔운 묘삼을 수경 재배시설로 정식하는 제 2단계; 및상기 정식된 인삼을 성장시키는 제 3단계;를 포함하되,상기 제 1단계에서 싹을 틔운 묘삼 준비 시,묘삼을 15 내지 20℃ 온도에서 뇌두 부분이 10 내지 80도의 경사로 위로 보게 배치하여 3 내지 5일간 싹을 1 내지 3cm 틔운 묘삼을 준비하고,상기 제 2단계에서 상기 수경 재배 시설의 내부에는 미세 비드를 포함하며,상기 미세 비드는 사이즈 100 내지 400㎛, 굴절율 1.9 내지 2.0인 것이며,상기 수경 재배 시설에서 사용되는 배양액은,온도 16 내지 20℃, pH 5.5 내지 6.5이고,상기 제 3단계의 인삼을 성장시키는 단계에서는,상기 인삼에 광을 조사하는 단계 포함하고,상기 광의 조사는 단계적으로 수행되며,원적외선광 30일, 적색광 및 청색광의 혼합광 30 내지 45일, 청색광 14일 순서로 조사되고,상기 적색광 및 청색광의 혼합광 구성 시 7:3의 비율로 조사되며,상기 인삼 성장 시 유묘기 및 생육기의 온도를 16 내지 20℃로 유지하고,상기 인삼 성장 시 메틸자스모네이트를 공급하는 것을 특징으로 하는 인삼 재배방법, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

634/1059 Row 634: application_number: 1020200137060, combined_string: invention_title: 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템 및 그 방법 abstract: 본 발명은 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템에 관한 것으로, 작물 재배 시설의 환경 구성과 실제 작물의 온도를 비교하여 온도 편차값을 연산한 후 온도 편차값에 따라 관수, 스크린, 보일러, 팬 등을 조절함으로써 작물을 재배하는 시설이 최적의 환경을 유지하도록 하는 것이다.본 발명에 의한 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템은 실제 작물을 재배하는 작물 재배 시설에서 실제 작물과 작물 재배 시설의 환경 구성에 대한 온도 데이터를 측정하는 촬영부와, 촬영부를 통해 측정된 온도 데이터를 화면에 출력하는 디스플레이와, 촬영부를 통해 측정된 온도 데이터를 디스플레이로 전송하는 전송 장치를 포함하는 구성을 가지며, 실제 작물과 작물 재배 시설의 환경 구성에 대한 온도 데이터를 비교하여 연산된 온도 편차값에 따라 작물 재배 시설의 환경 구성에 대한 제어를 하는 것을 특징으로 한다.이와 같은 본 발명에 의하면, 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템은 작물 재배 시설 내 실제 작물들의 생육 상태를 편리하게 파악할 수 있으며, 더불어 실제 작물들이 최적의 환경을 유지할 수 있도록 한다는 장점이 있다. claims: 실제 작물을 재배하는 작물 재배 시설에서 북쪽 방향을 바라보게 남쪽에 설치되어 상기 실제 작물과 상기 작물 재배 시설의 환경 구성에 대한 온도 데이터를 측정하는 촬영부와;상기 촬영부를 통해 측정된 상기 온도 데이터를 화면에 출력하는 디스플레이와;상기 촬영부를 통해 측정된 상기 온도 데이터를 상기 디스플레이로 전송하는 전송 장치를 포함하는 구성을 가지며;상기 작물 재배 시설의 토양, 관수, 난방 파이프, 팬, 스크린, 공기, 온실 구조물 또는 인조 작물을 포함하는 상기 작물 재배 시설의 환경 구성과 상기 실제 작물에 대한 상기 온도 데이터를 비교하여 연산된 온도 편차값에 따라 상기 작물 재배 시설의 환경 구성에 대한 제어를 하되,상기 인조 작물은, 상기 실제 작물과 동일한 방사율 수치를 가지며 방수가 가능한 재질로 이루어진 모형물과; 상기 모형물을 지지하는 지지대;를 포함하여 상기 실제 작물의 높이와 동일한 높이를 유지하고, 그 하단에 무게추가 더 구비되어 유동없이 고정되며,상기 촬영부는, 다수개의 픽셀 구조를 가지며 각각의 픽셀에 해당하는 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 온도를 측정하여 측정된 상기 온도 데이터를 다수개의 픽셀 구조에 추출하는 적외선 센서가 내부에 구비되며, 상기 적외선 센서로 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 상기 온도 데이터를 측정하는 카메라와; 상기 카메라를 지지하는 거치대와; 햇빛을 차단하는 차단판;을 포함하는 한편,상기 디스플레이는, 상기 촬영부를 통해 측정된 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 상기 온도 데이터가 소프트웨어를 통해 상기 화면에 출력되도록 이루어지고,상기 소프트웨어는, 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 온도를 측정하기 위한 범위를 다수개 설정하는 설정 프로그램과; 상기 설정 프로그램을 통해 설정한 온도 범위들 중 상기 온도를 비교하고자 하는 범위를 적어도 두 개 이상 선정 가능한 선정 프로그램과; 상기 선정 프로그램을 통해 선정된 범위에 해당하는 상기 온도 데이터를 실시간으로 추출하는 추출 프로그램과; 상기 추출 프로그램을 통해 추출된 상기 실제 작물의 현재 온도와 상기 작물 재배 시설의 상기 환경 구성의 현재 온도를 비교하여 상기 온도 편차값을 연산하는 연산 프로그램과; 추출 또는 연산된 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 상기 온도 데이터와 상기 온도 편차값을 데이터베이스에 누적하는 누적 프로그램과; 측정 및 연산된 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 상기 온도 데이터와 상기 온도 편차값을 상기 화면에 출력하는 출력 프로그램을 포함하되,상기 설정 프로그램은, 온도 측정을 원하는 범위를 추가로 설정 및 지정할 수 있는 추가 프로그램과; 상기 온도 측정을 원하는 범위를 변경할 수 있는 편집 프로그램과; 지정한 범위를 삭제할 수 있는 삭제 프로그램과; 임의로 설정한 범위를 이전 상태로 복구할 수 있는 복구 프로그램을 포함하고,상기 선정 프로그램은, 상기 설정 프로그램에서 지정한 범위 중 상기 실제 작물에 해당하는 범위와 상기 작물 재배 시설의 상기 환경 구성에 해당하는 범위를 각각 선정하며,상기 추출 프로그램은, 상기 선정 프로그램을 통해 선정한 지정 범위의 현재 온도 데이터를 실시간으로 추출함과 동시에 전일, 당일 또는 한달 간 측정된 상기 온도 데이터의 최소값, 최대값 및 평균값을 포함하여 상기 디스플레이 상에 출력하고,상기 누적 프로그램은, 상기 온도 데이터와 상기 온도 편차값을 시간별, 날짜별로 상기 데이터베이스에 누적 및 저장하며,상기 출력 프로그램은, 상기 선정 프로그램을 통해 선정한 지정 범위의 현재 온도 데이터와 상기 연산 프로그램에 의해 연산된 온도 편차값을 일정 범위마다 다른 색상으로 표현하여 상기 실제 작물의 생육 상태를 파악할 수 있는 한편,상기 연산 프로그램에서 연산된 상기 인조 작물과 실제 작물의 온도 편차가 2℃ 미만일 경우 낮에는 실제 작물의 상태를 증산 부족, 밤에는 실제 작물의 상태를 정상으로 판단하여, 낮인 경우 창문을 개폐하거나 관수 작동을 중지시키고, 온도 편차가 2~4℃일 경우 실제 작물의 증산이 감소된 상태로 판단하여 작물이 위치한 방향으로 팬을 작동시키며,온도 편차가 4~8℃일 경우 실제 작물의 증산이 최적의 상태로 판단하며, 온도 편차가 8℃를 초과할 경우 실제 작물이 불안정하거나 높은 증산이 이루어지는 상태로 판단하여, 스크린으로 햇빛을 차단하거나 관수 작동 간격을 빈번하게 설정하는 것을 특징으로 하는 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템.제1항의 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템을 이용한 상기 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 방법에 있어서,상기 작물 재배 시설 내에서 상기 촬영부가 북쪽 방향을 바라보게 남쪽에 설치하는 설치 단계와;소프트웨어의 설정 프로그램을 통해 온도 측정을 위한 범위를 설정하는 설정 단계와;상기 설정 단계에서 설정한 범위 중 온도를 비교하고자 하는 범위를 상기 소프트웨어의 선정 프로그램을 통해 적어도 두 개 이상 선정하는 선정 단계와;상기 선정 단계에서 선정한 범위들로부터 상기 실제 작물과 상기 작물 재배 시설의 환경 구성의 온도 데이터를 출력하는 출력 단계를 포함하되,상기 선정 단계는, 상기 작물 재배 시설의 환경 구성에 해당하는 범위와 그와 비교하고자 하는 상기 실제 작물에 해당하는 범위를 선정하고,상기 출력 단계는, 상기 소프트웨어의 추출 프로그램을 통해 추출된 상기 작물 재배 시설의 환경 구성의 상기 온도 데이터와 상기 실제 작물의 상기 온도 데이터를 출력하며, 상기 소프트웨어의 연산 프로그램을 통해 연산된 온도 편차값을 디스플레이에 출력함과 더불어,상기 연산 프로그램에서 연산된 상기 인조 작물과 실제 작물의 온도 편차가 2℃ 미만일 경우 낮에는 실제 작물의 상태를 증산 부족, 밤에는 실제 작물의 상태를 정상으로 판단하여, 낮인 경우 창문을 개폐하거나 관수 작동을 중지시키는 대응 방법을 제시하고,온도 편차가 2~4℃일 경우 실제 작물의 증산이 감소된 상태로 판단하여 작물이 위치한 방향으로 팬을 작동시키는 대응 방법을 제시하며,온도 편차가 4~8℃일 경우 실제 작물의 증산이 최적의 상태로 판단하며, 온도 편차가 8℃를 초과할 경우 실제 작물이 불안정하거나 높은 증산이 이루어지는 상태로 판단하여, 스크린으로 햇빛을 차단하거나 관수 작동 간격을 빈번하게 설정하는 대응 방법을 제시하는 것을 특징으로 하는 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 방법., Ltext: 농업, prediction: 임업
635/1059 Row 635: application_number: 1020200124869, combined_string: invention_title: 작물 상태 판단 장치 및 이를 포함하는 작물 재배 정보 서비스 플랫폼 abstract: 본 실시예들은 프로세서 및 프로세서에 의해 실행되는 프로그램을 저장하는 메모리를 포함하는 작물 재배 정보 서비스 플랫폼에 있어서, 프로세서는, 기 설정된 지형 정보와 이륙 지점 및 착륙 지점을 고려하여 형성된 필지에 따른 무인 비행체의 비행 경로를 생성하고, 무인 비행체가 획득한 작물 영상을 전달받아 분석하여 비행 경로에 따른 작물 정보를 획득하며, 작물의 종류 및 작물의 상태를 포함하는 작물 정보를 고려하여 비행 경로에 따른 재배 면적 별 수확 현황 및 재해 현황이 표시되는 작물 지도를 생성하는 것을 특징으로 하는 작물 재배 정보 서비스 플랫폼을 제안한다. claims: 프로세서 및 상기 프로세서에 의해 실행되는 프로그램을 저장하는 메모리를 포함하는 작물 재배 정보 서비스 플랫폼에 있어서,상기 프로세서는,기 설정된 지형 정보와 이륙 지점 및 착륙 지점을 고려하여 형성된 필지에 따른 무인 비행체의 비행 경로를 생성하고,상기 무인 비행체가 획득한 작물 영상을 전달받아 분석하여 상기 비행 경로에 따른 작물 정보를 획득하며,작물의 종류 및 작물의 상태를 포함하는 상기 작물 정보를 고려하여 상기 비행 경로에 따른 재배 면적 별 수확 현황 및 재해 현황이 표시되는 작물 지도를 생성하고,상기 프로세서는, 상기 작물의 종류에 따른 복수의 분류 모델 및 상기 작물의 상태에 따른 복수의 상태 모델을 학습하여 상기 작물 영상을 합성곱 신경망(CNN, Convolutional Neural Network)을 통해 분석하여 작물 별로 분류하여 작물의 종류 및 작물의 상태를 포함하는 상기 작물 정보를 획득하며,상기 프로세서는, 1차적으로 기 설정된 작물에 속하는 제1 작물 영역을 학습하는 제1 분류 모델 및 기 설정된 작물에 속하지 않는 제2 작물 영역을 학습하는 제2 분류 모델을 포함하는 상기 학습된 복수의 분류 모델을 적용하여 상기 작물 영상의 시간값을 입력으로 하여 추출된 특징을 분석하여 작물의 종류를 판단하고, 2차적으로 상기 판단된 작물의 종류에 따라 상기 시간값을 입력으로 하여 상기 학습된 복수의 상태 모델을 적용하여 정상, 결핍 및 고온 피해를 포함하는 상기 작물의 상태를 판단하고, 상기 비행 경로를 기반으로 재배 면적 별로 상기 작물의 종류에 따른 상기 작물의 상태를 표시하여 상기 작물 지도를 생성하는 것을 특징으로 하는 작물 재배 정보 서비스 플랫폼.프로세서 및 상기 프로세서에 의해 실행되는 프로그램을 저장하는 메모리를 포함하는 작물 상태 판단 장치에 있어서,상기 프로세서는,작물의 종류에 따른 복수의 분류 모델 및 상기 작물의 상태에 따른 복수의 상태 모델을 학습하고,비행 경로를 따라 이동하는 무인 비행체가 획득한 작물 영상을 전달받아 합성곱 신경망(CNN, Convolutional Neural Network)을 통해 분석하여 작물 별로 분류하여 작물의 종류 및 작물의 상태를 포함하는 작물 정보를 획득하며,상기 프로세서는, 1차적으로 기 설정된 작물에 속하는 제1 작물 영역을 학습하는 제1 분류 모델 및 기 설정된 작물에 속하지 않는 제2 작물 영역을 학습하는 제2 분류 모델을 포함하는 상기 학습된 복수의 분류 모델을 적용하여 상기 작물 영상의 시간값을 입력으로 하여 추출된 특징을 분석하여 작물의 종류를 판단하고, 2차적으로 상기 판단된 작물의 종류에 따라 상기 시간값을 입력으로 하여 상기 학습된 복수의 상태 모델을 적용하여 정상, 결핍, 고온 피해, 병을 포함하는 상기 작물의 상태를 판단하는 것을 특징으로 하는 작물 상태 판단 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

636/1059 Row 636: application_number: 1020200107029, combined_string: invention_title: 이동식 작물 재배 장치 abstract: 본 발명은 이동식 작물 재배 장치에 관한 것이다.보다 구체적으로는, 수분 공급을 통해 생육되는 식물을 재배할 수 있는 하우스 구조의 이동식 작물 재배 장치에 관한 것이다. claims: 이동식 작물 재배 장치는 하우스 구조로서,지붕을 제외한 외관의 뼈대을 형성하는 외관 프레임과; 상기 외관 프레임의 상측에서 지붕의 뼈대를 형성하는 지붕 프레임과; 상기 외관 프레임의 내측으로 마주하는 벽면에 대하여, 마주하는 방향으로 결합된 2개가 1쌍으로, 적어도 1쌍 이상 상, 하 방향으로 형성된 받침 프레임;을 포함하여 구성되고,상기 이동식 작물 재배 장치의 지붕 내면에는 지붕 가이드레일을 더 포함하고, 상기 지붕 가이드레일을 타고 이동하는 이송수단을 더 포함하되,상기 지붕 가이드레일은 ''의 단면형상을 가지고,상기 이송수단은,상기 지붕 가이드레일의 내측에 상기 지붕 가이드레일의 길이방향을 따라 형성된 제1 몸체와;상기 지붕 가이드레일의 개방된 영역에서부터 외측으로 노출되는 높이를 가지고 상기 지붕 가이드레일의 길이방향을 따라 형성되어 상기 제1 몸체 하측에 위치된 제2 몸체와;상기 제2 몸체를 관통하고 제1 몸체에 내삽된 볼트기둥과;상기 볼트기둥의 노출된 단부에 구성되어 볼트기둥을 회전시키도록 조작되는 회전헤드와;상기 볼트기둥의 외면에 결합되어 회전헤드에 의해 이탈이 방지되는 스프링과;상기 제1 몸체에 축으로 결합되고, 전단에 2개 및 후단에 2개로 구성되어 상기 지붕 가이드레일의 개방된 영역에 길이방향으로 형성된 단턱의 상면에 안착되는 상측 휠과;상기 제2 몸체에 축으로 결합되고, 전단에 2개 및 후단에 2개로 구성되어 상기 지붕 가이드레일의 개방된 영역에 길이방향으로 형성된 단턱의 하면에 맞닿는 하측 휠과;어느 일방향의 전단 및 후단에 형성된 하측 휠 각각에 축으로 연결되어 각각 구비된 기어와;상기 전단 및 후단 각각의 기어를 결합하는 체인과;상기 제2 몸체에서부터 연장되어 다수 절곡되되, 다른 일방향의 전단에 형성된 하측 휠의 외측으로 구성된 지지체와;상기 지지체를 관통하며, 상기 지지체 내측에 위치된 하측 휠에 결합된 축으로 연결되어 회전력을 전달하는 모터와;상기 제2 몸체의 일측에 1개의 볼트를 통해 결합된 2개가 1쌍으로 된 연결판;을 포함하여 구성되는 것을 특징으로 하는, 이동식 작물 재배 장치., Ltext: 농업, prediction: 농업
637/1059 Row 637: application_number: 1020200105327, combined_string: invention_title: 저고도 무인 비행체 및 이를 포함하는 작물 재배 정보 획득 시스템 abstract: 본 실시예들은 기 설정된 지형 정보와 이륙 지점 및 착륙 지점을 고려하여 형성된 필지에 따른 비행 경로를 생성하는 관제 센터 및 비행 경로에 따라 저고도 비행을 수행하며 환경 정보 또는 저고도 작물 영상을 획득하는 저고도 무인 비행체를 포함하고, 관제 센터는 저고도 작물 영상을 분석하여 작물 정보를 획득하고, 작물 정보를 좌표에 따라 표시하여 작물 지도를 생성하는 것을 특징으로 하는 작물 재배 정보 획득 시스템을 제안한다. claims: 기 설정된 지형 정보와 이륙 지점 및 착륙 지점을 고려하여 형성된 필지에 따른 비행 경로를 생성하는 관제 센터; 및상기 비행 경로에 따라 저고도 비행을 수행하며 환경 정보 또는 저고도 작물 영상을 획득하는 저고도 무인 비행체를 포함하고,상기 관제 센터는 상기 저고도 작물 영상을 분석하여 작물 정보를 획득하고, 상기 작물 정보를 좌표에 따라 표시하여 작물 지도를 생성하고,상기 저고도 무인 비행체는,상기 저고도 무인 비행체의 비행을 가능하게 하는 구동력을 발생시키는 구동부;상기 비행 경로를 따라 이동하며 상기 저고도 작물 영상을 획득하는 영상 획득부; 및상기 구동부 및 상기 영상 획득부를 제어하고, 상기 환경 정보와 상기 획득된 저고도 작물 영상을 고려하여 상기 비행 경로를 재설정하는 프로세서를 포함하고,상기 프로세서는,직하방을 향하도록 설정된 상기 영상 획득부에서 획득된 제1 저고도 작물 영상을 분석하여 1차 작물 인식을 수행하고,상기 1차 작물 인식을 통해 작물 정보를 획득하지 못한 경우, 상기 직하방을 향하도록 설정된 영상 획득부의 각도를 기 설정된 각도로 조절하여 획득된 제2 저고도 작물 영상을 전달받아 분석하여 2차 작물 인식을 수행하고,상기 2차 작물 인식을 통해 작물 정보를 획득하지 못한 경우, 상기 제1 저고도 작물 영상 및 상기 제2 저고도 작물 영상을 적대적 생성 신경망(GAN)을 통해 합성하여 합성 영상을 생성하고, 상기 생성된 합성 영상을 분석하여 3차 작물 인식을 수행하는 것을 특징으로 하는 작물 재배 정보 획득 시스템.기 설정된 지형 정보를 고려하여 생성된 비행 경로를 따라 비행을 가능하게 하는 구동력을 발생시키는 구동부;주변의 환경 정보를 획득하는 센서부;상기 비행 경로에 따라 저고도 비행을 수행하며 저고도 작물 영상을 획득하는 영상 획득부;상기 저고도 작물 영상을 분석하여 작물 정보를 획득하고, 상기 작물 정보를 좌표에 따라 표시하여 작물 지도를 생성하는 프로세서; 및상기 획득된 저고도 영상 또는 상기 프로세서에서의 연산 결과를 외부의 통신 가능한 장치로 전달하기 위한 통신부를 포함하고,상기 프로세서는,직하방을 향하도록 설정된 상기 영상 획득부에서 획득된 제1 저고도 작물 영상을 분석하여 1차 작물 인식을 수행하고,상기 1차 작물 인식을 통해 작물 정보를 획득하지 못한 경우, 상기 직하방을 향하도록 설정된 영상 획득부의 각도를 기 설정된 각도로 조절하여 획득된 제2 저고도 작물 영상을 전달받아 분석하여 2차 작물 인식을 수행하고,상기 2차 작물 인식을 통해 작물 정보를 획득하지 못한 경우, 상기 제1 저고도 작물 영상 및 상기 제2 저고도 작물 영상을 적대적 생성 신경망(GAN)을 통해 합성하여 합성 영상을 생성하고, 상기 생성된 합성 영상을 분석하여 3차 작물 인식을 수행하는 것을 특징으로 하는 저고도 무인 비행체., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

638/1059 Row 638: application_number: 1020200088428, combined_string: invention_title: 작물 재배용 베드 어셈블리 abstract: 본 발명은 지면에 베드(10)를 직접 설치할 수 있음과 더불어 시설하우스 내에 비교적 좁은 간격을 유지하는 일측파이프(51) 및 타측파이프(52) 나아가 비교적 넓은 간격을 유지하는 일측지지봉(31) 및 타측지지봉(32) 등으로 베드(10)의 위치 및 작업높이를 자유롭게(호환성 있게) 설치할 수 있도록 하여 시설하우스 현장에서의 조립성과 더불어 작업성까지 보장토록 할 수 있는 작물 재배용 베드 어셈블리에 관한 발명이다. claims: 배수구멍이 뚫린 바닥부를 기준으로 가장자리를 따라 상승된 일측벽 및 타측벽 그리고 전측벽 및 후측벽에 의해 상토를 수용하는 채움공간을 마련하는 베드를 포함하는 작물 재배용 베드 어셈블리에 있어서,상기 바닥부는 상기 일측벽 및 타측벽 사이에서 원호형상의 구배부를 지니고,상기 베드는 상기 구배부를 따라 외향 이격 돌출되면서 중간중간에 일측환기터널 및 타측환기터널을 각각 마련하는 일측돌출부 및 타측돌출부를 더 포함하고,상기 베드는 상기 일측벽 및 타측벽의 상단으로부터 외향으로 연장되어 일측지지봉 및 타측지지봉을 각각 받아들이는 일측날개 및 타측날개를 구비하고,상기 일측지지봉 및 타측지지봉에 각각 감겨져 상기 일측벽 및 일측돌출부 그리고 타측벽 및 타측돌출부를 따라 하향되면서 상기 바닥부로부터 이격되는 하부환기터널을 마련하는 방수커버를 더 포함하는 것을 특징으로 하는 작물 재배용 베드 어셈블리., Ltext: 농업, prediction: 농업
639/1059 Row 639: application_number: 1020200078618, combined_string: invention_title: 휴믹물질을 포함하는 인삼의 수경재배용 양액 조성물 및 상기 양액 조성물을 이용한 인삼의 수경재배 방법 abstract: 본 발명은 휴믹물질을 포함하는 인삼의 수경재배용 양액 조성물 및 상기 양액 조성물을 이용한 인삼의 수경재배 방법에 관한 것이다. 구체적으로, 본 발명에 따른 휴믹물질을 이용하여 수경재배된 인삼은 이에 포함된 잔류농약 및 중금속의 함량이 현저히 감소하면서, 유용한 생리활성 성분인 사포닌 및 미네랄의 함량을 유의적으로 증가시킴으로써, 인삼의 수경재배에 유용하게 사용될 수 있다. claims: 휴믹산(humic acid) 및 풀빅산(fulvic acid)을 포함하는 인삼의 수경재배용 양액 조성물로서,상기 양액 조성물은 인삼 내 사포닌 함량을 증가시키는 양액 조성물.제1항의 양액 조성물을 이용하여 인삼을 수경재배하는 단계를 포함하는 인삼의 수경재배 방법.제9항의 수경재배 방법으로 재배된 인삼.제11항의 인삼을 포함하는 조성물.제1항의 양액 조성물을 이용하여 인삼을 수경재배하는 단계를 포함하는 인삼 내에서 잔류농약 및 중금속으로 구성된 군으로부터 선택되는 어느 하나 이상을 감소시키는 방법.제1항의 양액 조성물을 이용하여 인삼을 수경재배하는 단계를 포함하는 인삼 내에서 사포닌 및 미네랄로 구성된 군으로부터 선택되는 어느 하나 이상을 증가시키는 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

640/1059 Row 640: application_number: 1020200047518, combined_string: invention_title: 기능성 작물 재배장치 abstract: 본 발명은 기능성 작물 재배장치에 관한 것으로, 보다 상세하게는, 식물 재배 시 자극을 통해 생리활성 물질을 다량 포함할 수 있도록 하는 기능성 작물 재배장치에 관한 것이다. 본 발명에 따른 기능성 작물 재배장치는 센서를 이용하여 재배 환경을 센싱하는 재배환경부; 작물에 따라 기설정된 조건의 자극을 부여하고 조절하는 자극조절부; 상기 자극에 의해 변화된 재배 상태를 검사하고 그에 따른 데이터를 저장하는 상태관리부; 소비자 또는 공급자에게 현재 상태를 전달하기 위한 모니터링 수단을 구비하는 공급확인부; 상기 재배환경부, 자극조절부, 상태관리부 및 공급확인부에 필요한 전원을 부여하기 위한 전원부;를 포함하는 것을 특징으로 한다. claims: 센서를 이용하여 재배 환경을 센싱하는 재배환경부;작물에 따라 기설정된 조건의 자극을 부여하고 조절하는 자극조절부;상기 자극에 의해 변화된 재배 상태를 검사하고 그에 따른 데이터를 저장하는 상태관리부;소비자 또는 공급자에게 현재 상태를 전달하기 위한 모니터링 수단을 구비하는 공급확인부;상기 재배환경부, 자극조절부, 상태관리부 및 공급확인부에 필요한 전원을 부여하기 위한 전원부;를 포함하는 것을 특징으로 하는 기능성 작물 재배장치, Ltext: 농업, prediction: 농업
641/1059 Row 641: application_number: 1020200046371, combined_string: invention_title: 지능형 특수작물 재배기 abstract: 본 발명은, 작물이 수용되는 챔버부; 및 상기 챔버부의 상측에 설치되며, 상기 챔버부에 존재하는 공기를 흡입하여 상측으로 토출시켜, 상기 챔버부로 공기를 순환시키는 휀부;를 포함하는 지능형 특수작물 재배기를 제공한다.본 발명에 따른 지능형 특수작물 재배기에 의하면, 지구상의 모든 천연 자연물의 인공 재배환경을 구현함으로써, 특수한 자연조건에서 자라는 희귀 천연물자원의 보존과 인공재배법을 위하여 농업기술개발에 적극 활용하고 병충해 및 연작피해와 자연재해 등을 회피하며, 대량생산과 청정재배를 실현할 수 있는 농업기술개발에 활용 될 수 있다. 또한, 이러한 본 발명에 의하면, 스마트팜의 특성인 5G, IOT, DB 등과 연동하여 특수작물 재배기 모듈에 다각도로 활용 될 수 있다. claims: 작물이 수용되는 챔버부; 및상기 챔버부의 상측에 설치되며, 상기 챔버부에 존재하는 공기를 흡입하여 상측으로 토출시켜, 상기 챔버부로 공기를 순환시키는 휀부;를 포함하는 지능형 특수작물 재배기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

642/1059 Row 642: application_number: 1020200046226, combined_string: invention_title: 인삼의 생장 촉진 및 내병성 증진용 조성물 및 이를 이용한 인삼의 재배방법 abstract: 본 발명은 인삼의 생장 촉진 및 내병성 증진용 조성물 및 이를 이용한 인삼의 재배방법에 관한 것이다. 본 발명에 따른 인삼의 생장 촉진 및 내병성 증진용 조성물은 유충(幼蟲) 파우더를 포함하는 것일 수 있다. claims: 갈색거저리(mealworm beetle) 유충 파우더 및 귀뚜라미 성충 파우더를 포함하는인삼의 생장 촉진 및 내병성 증진용 조성물.갈색거저리(mealworm beetle) 유충 파우더, 귀뚜라미 성충 파우더 및 물의 혼합물을 제조하는 단계 및 생육되는 인삼에 상기 혼합물을 분사하는 단계를 포함하는 것인인삼의 생장 촉진 및 내병성 증진용 조성물을 이용한 인삼의 재배방법.제 5항에 따른 재배방법으로 생육된 인삼., Ltext: 농업, prediction: 임업
643/1059 Row 643: application_number: 1020200046229, combined_string: invention_title: 인삼의 생장 촉진 및 내병성 증진용 조성물 및 이를 이용한 인삼의 재배방법 abstract: 본 발명은 인삼의 생장 촉진 및 내병성 증진용 조성물 및 이를 이용한 인삼의 재배방법에 관한 것이다. 본 발명에 따른 인삼의 생장 촉진 및 내병성 증진용 조성물은 곤충 파우더를 포함하고 상기 곤충은 성충인 것일 수 있다. claims: 귀뚜라미 성충 파우더 100 중량부, 갈색거저리 유충 파우더 50 내지 200 중량부를 포함하는인삼의 생장 촉진 및 내병성 증진용 조성물.귀뚜라미 성충 파우더 100 중량부, 갈색거저리 유충 파우더 50 내지 200 중량부를 혼합하는 단계;상기 혼합한 파우더를 10배수의 물에 혼합 및 분산하여 혼합물을 제조하는 단계; 및생육되는 인삼의 뿌리 부분에 상기 혼합물을 분사하는 단계를 포함하는, 인삼의 재배방법.제 5항에 따른 재배방법으로 생육된 인삼., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

644/1059 Row 644: application_number: 1020200040821, combined_string: invention_title: 냉난방 시스템에 의한 에너지 절감형 하우스 작물 재배장치 및 그 하우스 작물 재배방법 abstract: 본 발명은 냉난방 시스템에 의한 에너지 절감형 하우스 작물 재배장치 및 그 하우스 작물 재배방법에 관한 것으로 계절에 상관 없이 각종 작물을 재배하는 하우스 내에 작물 재배에 필요한 적정온도와 영양액 공급을 포함한 실내환경을 제공하도록 함과 아울러, 에너지 절감효과를 가지는 지하물탱크를 사용하여 냉온수를 생성공급하여 하우스 내부의 온도를 조절토록 하고, 냉온수 공급 시 용존산소를 부여토록 하며, 지하물탱크를 사용함으로써 에너지 절감효과를 갖도록 하기 위하여, 작물(3) 재배를 위해 설치되는 하우스(2)의 인근 지하에 매설되는 지하물탱크(10); 상기 지하물탱크(10)의 내부에 충진된 사용수를 외부로 이송시키도록 수중가압펌프(12)가 구비되고, 상기 지하물탱크(10)의 상부에 위치되고, 상기 수중가압펌프(12)에 연결된 이동관(14)에 연결되어 이동되는 사용수의 온도를 조절하도록 쿨냉각기와 히트온수기가 구비되는 수온조절부(20); 상기 수온조절부(20)를 통해 요구하는 온도로 조절된 사용수가 저장되도록 지상에 설치되는 지상물탱크(30); 상기 지상물탱크(30)에 연결되는 제1공급관(31)은 하우스(2) 내에서 하우스(2)의 길이방향을 따라 구비되고, 상기 제1공급관(31) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내에 온도 조절된 사용수를 분사토록 하고, 상기 하우스(2)에서 재배되는 작물(3)에 영양분을 공급하도록 지상물탱크(30) 인근 지상에 설치되는 영양액공급탱크(40); 상기 영양액공급탱크(40)에 연결되는 제2공급관(42)은 하우스(2) 내의 제1공급관(31)과 평행하게 구비되고, 상기 영양액공급탱크(40)에 연결되는 제3공급관(43)은 하우스(2) 내의 상부에 제2공급관(42)과 평행하게 구비되며, 상기 제2공급관(42) 및 제3공급관(43) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내의 작물(3)에 영양액을 분사토록 하며, 상기 하우스(2) 내의 지면에서 이격 구비되어 하우스(2)의 길이방향으로 구비되는 다수의 고설베드(50); 상기 고설베드(50)는 작물(3) 재배를 위한 수용홈부(52)가 구비되고, 상기 수용홈부(52) 내에 상기 제1공급관(31)에 연결된 냉온수파이프(60)이 구비되어 작물(3)에 필요한 냉온기를 전달하도록 구성되는 것을 포함하여 이루어짐을 특징으로 한다. claims: 작물(3) 재배를 위해 설치되는 하우스(2)의 인근 지하에 매설되는 지하물탱크(10); 상기 지하물탱크(10)의 내부에 충진된 사용수를 외부로 이송시키도록 수중가압펌프(12)가 구비되고,상기 지하물탱크(10)의 상부에 위치되고, 상기 수중가압펌프(12)에 연결된 이동관(14)에 연결되어 이동되는 사용수의 온도를 조절하도록 쿨냉각기와 히트온수기가 구비되는 수온조절부(20);상기 수온조절부(20)를 통해 요구하는 온도로 조절된 사용수가 저장되도록 지상에 설치되는 지상물탱크(30); 상기 지상물탱크(30)에 연결되는 제1공급관(31)은 하우스(2) 내에서 하우스(2)의 길이방향을 따라 구비되고, 상기 제1공급관(31) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내에 온도 조절된 사용수를 분사토록 하고,상기 하우스(2)에서 재배되는 작물(3)에 영양분을 공급하도록 지상물탱크(30) 인근 지상에 설치되는 영양액공급탱크(40); 상기 영양액공급탱크(40)에 연결되는 제2공급관(42)은 하우스(2) 내의 제1공급관(31)과 평행하게 구비되고, 상기 영양액공급탱크(40)에 연결되는 제3공급관(43)은 하우스(2) 내의 상부에 제2공급관(42)과 평행하게 구비되며, 상기 제2공급관(42) 및 제3공급관(43) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내의 작물(3)에 영양액을 분사토록 하며, 상기 하우스(2) 내의 지면에서 이격 구비되어 하우스(2)의 길이방향으로 구비되는 다수의 고설베드(50); 상기 고설베드(50)는 작물(3) 재배를 위한 수용홈부(52)가 구비되고, 상기 수용홈부(52) 내에 상기 제1공급관(31)에 연결된 냉온수파이프(60)이 구비되어 작물(3)에 필요한 냉온기를 전달하도록 구성되는 것을 포함하여 이루어짐을 특징으로 하는 냉난방 시스템에 의한 에너지 절감형 하우스 고설베드 작물 재배장치.작물(3) 재배를 위해 설치되는 하우스(2)의 인근 지하에 매설되는 지하물탱크(10)를 마련하고, 상기 지하물탱크(10)의 내부에 충진된 사용수를 외부로 이송시키도록 수중가압펌프(12)를 마련하며, 상기 지하물탱크(10)의 상부에 위치되고, 상기 수중가압펌프(12)에 연결된 이동관(14)에 연결되어 이동되는 사용수의 온도를 조절하도록 쿨냉각기와 히트온수기가 구비되는 수온조절부(20)를 마련하되 상기 이동관(14) 상에 용존산소 발생기(16)를 구비하여 이동관(14)을 통해 수중가압펌프(12)에서 수온조절부(20)로 이동하는 사용수의 용존산소량을 증가시키도록 하고, 상기 수온조절부(20)를 통해 요구하는 온도로 조절된 사용수가 저장되도록 지상에 설치되는 지상물탱크(30)를 마련하되 상기 지상물탱크(30)에 연결되는 제1공급관(31)은 하우스(2) 내에서 하우스(2)의 길이방향을 따라 구비되고, 상기 제1공급관(31) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내에 온도 조절된 사용수를 분사토록 하고, 상기 하우스(2)에서 재배되는 작물(3)에 영양분을 공급하도록 지상물탱크(30) 인근 지상에 설치되는 영양액공급탱크(40)를 마련하되 상기 영양액공급탱크(40)에 연결되는 제2공급관(42)은 하우스(2) 내의 제1공급관(31)과 평행하게 구비되고, 상기 영양액공급탱크(40)에 연결되는 제3공급관(43)은 하우스(2) 내의 상부에 제2공급관(42)과 평행하게 구비되며, 상기 제2공급관(42) 및 제3공급관(43) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내의 작물(3)에 영양액을 분사토록 하며, 상기 하우스(2) 내의 지면에서 이격 구비되어 하우스(2)의 길이방향으로 구비되는 다수의 고설베드(50)를 마련하되 상기 고설베드(50)는 작물(3) 재배를 위한 수용홈부(52)가 구비되고, 상기 수용홈부(52) 내에 상기 제1공급관(31)에 연결된 냉온수파이프(60)이 구비되어 작물(3)에 필요한 냉온기를 전달하도록 하여, 계절에 상관 없이 하우스(2) 내에 작물(3) 재배에 필요한 적정온도와 영양액을 에너지 절감 가능한 구조로 제공하도록 하여 이루어짐을 특징으로 하는 냉난방 시스템에 의한 에너지 절감형 하우스 작물 재배방법., Ltext: 농업, prediction: 임업
645/1059 Row 645: application_number: 1020200039235, combined_string: invention_title: 포그 스프레이 시스템을 구비한 수직형 작물 재배 장치 및 방법 abstract: 본 발명은 포그 스프레이 시스템을 구비한 수직형 작물 재배 장치 및 방법에 관한 것으로서, 보다 상세하게는 작물의 발육 상태에 따라 이온화된 드라이 포그와 미스트 포그로 영양액 및 배양액을 분사하여 작물의 온도 및 습도 환경을 제어하여 최적의 발육 상태를 유지하는 포그 스프레이 시스템을 구비한 수직형 작물 재배 장치 및 방법에 관한 것이다. claims: 수직형 작물 재배 장치에 있어서,재배판을 수직으로 적층 하여 작물을 재배할 수 있는 공간을 제공하는 재배부; 상기 재배부에 구비되어 작물의 잎 또는 뿌리에 드라이 포그 및 미스트 포그 중 적어도 하나를 분사하는 분사부; 및상기 분사부의 분사위치, 분사 압력을 제어하는 단말부를 포함하는 포그 스프레이 시스템을 구비한 수직형 작물 재배 장치.수직형 작물 재배 방법에 있어서,재배부의 온도, 습도, pH중 적어도 하나의 정보를 획득하는 단계;상기 획득한 정보에 따라 분사부 제어신호를 생성하는 단계;상기 생성한 분사부 제어신호에 따라 드라이 포그 및 미스트 포그 중 적어도 하나의 분사위치를 결정하는 단계; 및 상기 생성한 분사부 제어신호에 따라 드라이 포그 및 미스트 포그 중 적어도 하나의 분사압력을 결정하는 단계; 를 포함하는 포그 스프레이 시스템을 구비한 수직형 작물 재배 방법.제 4항의 포그 스프레이 시스템을 구비한 수직형 작물 재배 방법을 실행하는 컴퓨터 프로그램이 저장된 컴퓨터가 판독 가능한 기록매체., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

646/1059 Row 646: application_number: 1020200039485, combined_string: invention_title: 작물 재배용 트레이 abstract: 본 발명은 재배하고자 하는 동일한 종류의 작물을 재배하거나 또는 서로 다른 종류의 작물을 유닛(unit) 형태로 분할하여 하나의 트레이 상에서 병행하여 재배할 수 있도록 상부가 개방된 장방형 형태로 길이 방향의 양측에 걸이 부재가 형성되며, 그 길이 방향의 서로 마주보는 내면에 단턱 진 각각의 받침 턱이 형성되는 본체; 및 상기 본체의 내부에 동일한 작물을 유닛 형태로 분할하여 재배하거나 서로 다른 작물을 병행하여 재배할 수 있도록 마련되는 구획부재;를 포함하는 작물 재배용 트레이를 제공한다. 그에 따라 간단한 기술적 구성에 의해 다양한 종류의 작물을 동시에 원활하게 재배할 수 있는 효과를 가진다. claims: 작물 재배시설에서 현수되어 이송 또는 회전되면서 작물을 재배하기 위해 사용되는 작물 재배용 트레이에 있어서, 상기 작물 재배용 트레이는 상부가 개방된 장방형 형태로 길이 방향의 양측에 걸이 부재가 형성되며, 그 길이 방향의 서로 마주보는 내면에 단턱 진 각각의 받침 턱이 형성되는 본체; 및 상기 본체의 내부에 동일한 작물을 유닛 형태로 분할하여 재배하거나 서로 다른 작물을 병행하여 재배할 수 있도록 마련되는 구획부재;를 포함하는 작물 재배용 트레이., Ltext: 농업, prediction: 농업
647/1059 Row 647: application_number: 1020200039486, combined_string: invention_title: 트레이 회전식 작물 재배용 챔버 abstract: 본 발명은 작은 부피를 가지는 챔버에 의해 소량의 작물 재배는 물론 복수 개를 연속배치하여 대량의 작물 재배 또한 원활하게 이루어질 수 있도록 하면서 챔버 내부 조건을 재배하고자 하는 작물에 따라 최적의 조건으로 유지할 수 있도록 베이스 프레임), 작물 재배부, 챔버 하우징, 물 공급 부재, 양액 공급 부재, 온도 센서 및 습도센서, 온풍 공급수단 및 냉풍 공급수단을 포함하는 트레이 회전식 작물 재배용 챔버를 제공한다. 그에 따라 최소한의 설치면적 대비하여 재배 효율성을 극대화할 수 있는 효과와 함께 작물의 재배 양 또한 최대한 증대시킬 수 있는 효과도 가진다. claims: 바닥면에 인출 가능한 받이 트레이를 포함하는 베이스 프레임; 상기 베이스 프레임의 상부에 양측의 받침 프레임 상에서 구동수단에 의해 회전되는 회전축 상에 장착되는 얼레 형태로 양측 측 프레임 사이에 일정 간격의 각각의 행거(hanger) 바가 형성되어 회전되는 회전 프레임, 상기 각 행거 바에 작물을 재배하기 위해 토양이 채워지고 상단 양측에 상기 행거 바에 걸어지는 각각의 고리 부재가 구비되는 각각의 재배 트레이를 포함하는 작물 재배부; 상기 베이스 프레임의 테두리 측에 작물 재배부가 내부에 위치하여 밀폐되도록 적어도 하나 이상의 출입문과 환기창 또는 점검창이 구비되며, 상면에 적어도 하나 이상의 환기 팬이 구비되는 챔버 하우징; 상기 챔버 하우징의 내부 상부에 작물의 광합성(光合成)을 위해 구비되는 광원수단, 수분 공급을 위한 물 공급 부재 및 양액(nutrient) 공급을 위한 양액 공급 부재;를 포함하며, 상기 챔버 하우징의 내부에 온도와 습도를 감지하기 위해 구비되는 온도 센서 및 습도 센서; 및 상기 챔버 하우징의 일측에 상기 챔버 하우징 내부로 온풍 또는 냉풍을 공급하기 위한 온풍 공급수단 및 냉풍 공급수단;을 포함하는 트레이 회전식 작물 재배용 챔버., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

648/1059 Row 648: application_number: 1020200037245, combined_string: invention_title: 공기 순환식 다종 작물 재배 장치 abstract: 본 발명은 공기 순환식 다종 작물 재배 장치 및 방법에 관한 것으로, 본 발명의 공기 순환식 다종 작물 재배 장치는 생장 시 산소를 사용하고 이산화탄소를 배출하는 제1 작물(10)을 생육하도록 외부와 밀폐 형성된 공간을 구비하는 제1 재배 하우징(100), 상기 제1 재배 하우징(100)과 인접 배치되어, 생장 시 이산화탄소를 사용하고 산소를 배출하는 제2 작물(20)을 생육하도록 외부와 밀폐 형성된 공간을 구비하는 제2 재배 하우징(200), 상기 제1 재배 하우징(100) 내의 이산화탄소농도가 높은 공기를 상기 제2 하우징(200)에 공급하는 탄소공급라인(310); 및 상기 제2 재배 하우징(200) 내의 산소농도가 높은 공기를 상기 제1 하우징(100)에 공급하는 산소공급라인(410)을 포함한다. claims: 생장 시 산소를 사용하고 이산화탄소를 배출하는 제1 작물(10)을 생육하도록 외부와 밀폐 형성된 공간을 구비하는 제1 재배 하우징(100);상기 제1 재배 하우징(100)과 인접 배치되어, 생장 시 이산화탄소를 사용하고 산소를 배출하는 제2 작물(20)을 생육하도록 외부와 밀폐 형성된 공간을 구비하는 제2 재배 하우징(200);상기 제1 재배 하우징(100) 내의 이산화탄소농도가 높은 공기를 상기 제2 하우징(200)에 공급하는 탄소공급라인(310); 및상기 제2 재배 하우징(200) 내의 산소농도가 높은 공기를 상기 제1 하우징(100)에 공급하는 산소공급라인(410);을 포함하는 공기 순환식 다종 작물 재배 장치., Ltext: 농업, prediction: 농업
649/1059 Row 649: application_number: 1020200036631, combined_string: invention_title: 인삼 수경 재배용 배드 및 이를 이용한 수경 재배방법 abstract: 본 발명은 인삼 수경 재배용 배드 및 이를 이용한 수경 재배방법에 관한 것으로서, 항바이러스 특성을 갖게 되어 인삼의 수경재배 과정에서 바이러스 감염을 방지하여 인삼의 폐사율을 감소시킴과 함께 안정적인 배양 환경을 제공하여 포낭 형성율을 향상시키기 위한 것이다.이를 실현하기 위한 본 발명은, 인삼의 수경 재배가 이루어지는 배드본체(10)의 상면에는 항바이러스 기능을 위한 보호층(11)과, 상기 보호층(11)의 배드본체 부착력을 강화하기 위한 하도층(12)이 각각 형성되며; 상기 보호층(11)은 오르가노클로로실란, 필러, 안료, 소포제, 증점제, 레벨링제, 분산제, 흐름방지제 및 항바이러스제의 혼합 조성을 이루고; 상기 하도층(12)은 오르가노클로로실란, 증점제, 레벨링제, 흐름방지제의 혼합 조성을 이루는 것을 특징으로 한다. claims: 인삼의 수경 재배가 이루어지는 배드본체(10)의 상면에는 항바이러스 기능을 위한 보호층(11)과, 상기 보호층(11)의 배드본체 부착력을 강화하기 위한 하도층(12)이 각각 형성되며;상기 보호층(11)은 오르가노클로로실란, 필러, 안료, 소포제, 증점제, 레벨링제, 분산제, 흐름방지제 및 항바이러스제의 혼합 조성을 이루고;상기 하도층(12)은 오르가노클로로실란, 증점제, 레벨링제, 흐름방지제의 혼합 조성을 이루는 것을 특징으로 하는 인삼 수경 재배용 배드.청구항 1 내지 청구항 4 중 어느 한 항의 보호층(11) 및 하도층(12)이 배드본체(10)의 표면에 코팅 형성된 수경 재배용 배드를 이용하여 인삼의 수경 재배가 이루어지는 것을 특징으로 하는 인삼 수경 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

650/1059 Row 650: application_number: 1020200022651, combined_string: invention_title: 열처리된 목재 칩, 질소원 및 발효볏짚을 유효성분으로 함유하는 작물 재배용 인공토양 조성물 abstract: 본 발명은 열처리된 목재 칩, 질소원 및 발효볏짚을 유효성분으로 함유하는 작물 재배용 인공토양 조성물에 관한 것으로, 상기 열처리된 참나무 칩과 질소원으로 이루어진 혼합물 또는 상기 혼합물과 발효볏짚을 유효성분으로 함유하는 조성물은 참외 종자의 발아율 및 엽수를 증가시키고 초장 및 근장의 생장을 향상시키는 효과를 나타내는 것이 확인됨에 따라, 상기 조성물은 일반 토양 및 인공사료를 대체할 수 있는 작물 재배용 인공토양으로 제공될 수 있다. claims: 열처리된 목재 칩과 질소원으로 이루어진 혼합물 및 발효볏짚을 유효성분으로 함유하는 작물 재배용 인공토양 조성물., Ltext: 농업, prediction: 임업
651/1059 Row 651: application_number: 1020200023173, combined_string: invention_title: 공기정화용 식물재배장치가 마련된 에어커튼 시스템 abstract: 공기정화용 식물재배장치가 마련된 에어커튼 시스템이 개시된다. 본 발명의 공기정화용 식물재배장치가 마련된 에어커튼 시스템은, 수직 몸체를 이루며, 측벽에 식물이 식재되며 공기를 흡입하여 흡입된 공기에 포함된 미세먼지 및 초미세먼지를 포함한 오염물질을 걸러내는 공기정화 벽부; 지붕을 이루며, 지붕의 테두리를 따라 공기 배출구가 마련되어 상기 공기정화 벽부를 거쳐 오염물질이 걸러진 공기를 공급받아 상기 공기 배출구를 통해 수직 하부로 배출하는 에어커튼 분사부; 및 바닥을 이루며, 바닥의 테두리를 따라 공기 흡입구가 마련되어 상기 에어커튼 분사부의 공기 배출구에서 배출된 공기를 흡입하는 공기흡입부:를 포함하는 것을 특징으로 한다. claims: 수직 몸체를 이루며, 측벽에 식물이 식재되며 공기를 흡입하여 흡입된 공기에 포함된 미세먼지 및 초미세먼지를 포함한 오염물질을 걸러내는 공기정화 벽부;지붕을 이루며, 지붕의 테두리를 따라 공기 배출구가 마련되어 상기 공기정화 벽부를 거쳐 오염물질이 걸러진 공기를 공급받아 상기 공기 배출구를 통해 수직 하부로 배출하는 에어커튼 분사부;바닥을 이루며, 바닥의 테두리를 따라 공기 흡입구가 마련되어 상기 에어커튼 분사부의 공기 배출구에서 배출된 공기를 흡입하는 공기흡입부;상기 에어커튼 분사부의 지붕 상부면에 마련되는 태양광 패널에 의해 생산된 전기를 저장하고 공급하는 축전지부;상기 공기정화 벽부를 거쳐 오염물질이 걸러진 공기를 공급받아 상기 에어커튼 분사부의 공기 배출구로 고압분사하는 분사펌프; 및 상기 공기흡입부에 마련되며, 에어커튼을 형성한 후 하강하는 공기를 상기 공기 흡입구로 흡입하여 상기 에어커튼 분사부로 순환시키기 위한 송풍기와 상기 송풍기를 구동시키는 송풍모터를 포함하는 흡기장치:를 포함하고, 상기 분사펌프 및 송풍모터는 상기 축전지부로부터 전기를 공급받아 구동되는 것을 특징으로 하는 공기정화용 식물재배장치가 마련된 에어커튼 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

652/1059 Row 652: application_number: 1020200021986, combined_string: invention_title: 작물 재배 환경을 모니터링하는 모니터링 장치, 방법 및 컴퓨터 프로그램 abstract: 작물 재배 환경을 모니터링하는 모니터링 장치는 복수의 센서를 이용하여 획득한 환경 이력을 입력받는 환경 이력 입력부, 구동기 동작 이력을 입력받는 구동기 동작 이력 입력부, 상기 환경 이력 및 상기 구동기 동작 이력에 대하여 퍼지화를 수행함으로써 퍼지화 데이터를 생성하는 퍼지화 데이터 생성부, 기구축된 복수의 작물에 대한 재배 지식에 기초하여 퍼지 규칙을 생성하는 퍼지 규칙 생성부 및 상기 퍼지화 데이터 및 상기 퍼지 규칙에 기초하여 작물 재배 환경의 장해 발생 가능성을 판단하는 장해 판단부를 포함한다. claims: 작물 재배 환경을 모니터링하는 모니터링 장치에 있어서,복수의 센서를 이용하여 획득한 환경 이력을 입력받는 환경 이력 입력부;구동기 동작 이력을 입력받는 구동기 동작 이력 입력부;상기 환경 이력 및 상기 구동기 동작 이력에 대하여 퍼지화를 수행함으로써 퍼지화 데이터를 생성하는 퍼지화 데이터 생성부;기구축된 복수의 작물에 대한 재배 지식에 기초하여 퍼지 규칙을 생성하는 퍼지 규칙 생성부; 및상기 퍼지화 데이터 및 상기 퍼지 규칙에 기초하여 작물 재배 환경의 장해 발생 가능성을 판단하는 장해 판단부를 포함하는 것인, 모니터링 장치.작물 재배 환경을 모니터링하는 모니터링 방법에 있어서,복수의 센서를 이용하여 획득한 환경 이력을 입력받는 단계;구동기 동작 이력을 입력받는 단계;상기 환경 이력 및 상기 구동기 동작 이력에 대하여 퍼지화를 수행함으로써 퍼지화 데이터를 생성하는 단계;기구축된 복수의 작물에 대한 재배 지식에 기초하여 퍼지 규칙을 생성하는 단계; 및상기 퍼지화 데이터 및 상기 퍼지 규칙에 기초하여 작물 재배 환경의 장해 발생 가능성을 판단하는 단계를 포함하는 것인, 모니터링 방법.작물 재배 환경을 모니터링하는 명령어들의 시퀀스를 포함하는 매체에 저장된 컴퓨터 프로그램에 있어서,상기 컴퓨터 프로그램은 컴퓨팅 장치에 의해 실행될 경우,복수의 센서를 이용하여 획득한 환경 이력을 입력받고,구동기 동작 이력을 입력받고,상기 환경 이력 및 상기 구동기 동작 이력에 대하여 퍼지화를 수행함으로써 퍼지화 데이터를 생성하고,기구축된 복수의 작물에 대한 재배 지식에 기초하여 퍼지 규칙을 생성하고,상기 퍼지화 데이터 및 상기 퍼지 규칙에 기초하여 작물 재배 환경의 장해 발생 가능성을 판단하도록 하는 명령어들의 시퀀스를 포함하는 것인, 매체에 저장된 컴퓨터 프로그램., Ltext: 농업, prediction: 농업
653/1059 Row 653: application_number: 1020200021094, combined_string: invention_title: 작물 재배 장치 및 이를 이용한 작물 재배 방법 abstract: 본 발명의 일 실시예에 따른 작물 재배 장치는 작물을 수용 가능하도록 내부 공간이 형성되고, 하부 재배지의 상측에 설치되도록 제공되는 재배 상자; 및 상기 하부 재배지에 대한 상기 재배 상자의 상대 높낮이를 조절하기 위해 제공되는 구동부를 포함할 수 있다. claims: 작물을 수용 가능하도록 내부 공간이 형성되고, 하부 재배지의 상측에 설치되도록 제공되는 재배 상자; 및상기 하부 재배지에 대한 상기 재배 상자의 상대 높낮이를 조절하기 위해 제공되는 구동부를 포함하는 작물 재배 장치.제1 항 내지 제11 항 중 어느 한 항에 따른 작물 재배 장치를 이용한 작물 재배 방법에 있어서,상기 하부 재배지에 아스파라거스가 식재되어 있는 상태로 상기 재배 상자에서 아스파라거스 순을 재배하고 수확하는 단계;상기 하부 재배지에서 아스파라거스 순을 재배하고 수확하는 단계; 및상기 재배 상자를 상기 하부 재배지로부터 이격시켜 상기 재배 상자에서 작물을 재배하는 단계를 포함하는 작물 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

654/1059 Row 654: application_number: 1020200016708, combined_string: invention_title: 대차와 ICT 스마트팜 기술을 이용한 인삼 수경 재배 장치. abstract: 본 발명은 공장 건물 내부에 일정 간격으로 정렬 배치되어, 인삼을 재배하는 셀모듈;상기 셀모듈에 구비된 인삼의 성장을 분석하고, 약액 살포 작업의 자동화를 수행하는 자동화 모듈;상기 셀모듈(100)에서 재배되는 인삼의 생육환경을 측정하는 센서모듈;상기 센서모듈의 측정결과에 근거하여, 상기 셀모듈에서 재배되는 인삼의 생육환경을 자동으로 조절하는 생육환경조절모듈;상기 센서모듈, 생육환경조절모듈 및 상기 자동화 모듈과 무선으로 정보를 송수신하는 ICT 단말기;를 포함하여 구성되는 것을 특징으로 하는 대차와 ICT 스마트팜 기술을 이용한 인삼 수경 재배 장치에 관한 것이다. claims: 공장 건물 내부에 일정 간격으로 정렬 배치되어, 인삼을 재배하는 셀모듈(100);상기 셀모듈(100)에 구비된 인삼의 성장을 분석하고, 약액 살포 작업의 자동화를 수행하는 자동화 모듈(200);상기 셀모듈(100)에서 재배되는 인삼의 생육환경을 측정하는 센서모듈(300);상기 센서모듈(300)의 측정결과에 근거하여, 상기 셀모듈(100)에서 재배되는 인삼의 생육환경을 자동으로 조절하는 생육환경조절모듈(500);상기 센서모듈(300), 생육환경조절모듈(500) 및 상기 자동화 모듈(200)과 무선으로 정보를 송수신하는 ICT 단말기(600);를 포함하여 구성되는 것을 특징으로 하는 대차와 ICT 스마트팜 기술을 이용한 인삼 수경 재배 장치., Ltext: 농업, prediction: 임업
655/1059 Row 655: application_number: 1020200013469, combined_string: invention_title: 수조가 마련되는 가정용 수경재배장치 abstract: 본 발명은, 일정크기의 내부공간이 마련되며 전면부위가 개구되는 몸체(11), 개구된 몸체(11)의 전면부위 하측에 마련되는 가이드레일(12), 몸체(11)의 내부 상면부위에 설치되는 엘이디광원(13), 몸체(11)의 내부 일측부위에 설치되는 온습도기구(14)가 구비되는 하우징부; 상측부위가 개구되되 수위감지수단이 마련되어 몸체(11)의 내부공간 하측부위에 안치되는 수경재배통(21), 복수 개의 생육공(23)이 형성되어 개구된 수경재배통(21)의 상측부위를 밀폐하는 지지판(22)이 구비되는 수경재배부; 상측부위가 개구되되 하면부위가 가이드레일(11)을 따라 전후로 슬라이딩하며 몸체(11)의 전면부위를 개폐하는 수조부(30); 제어보드가 마련되어 몸체(11)의 외면 일측부위에 설치되는 제어박스(41), 제어박스(41)의 일측에 내장되는 모터(42), 모터(42)와 연결되어 제어박스(41)의 타측에 내장되는 펌프(43), 일단부위는 펌프(43)의 일측부위에 연결되고 타측부위는 수조부(30) 내부로 연장되는 배수관(44), 일단부위는 펌프(43)의 타측부위에 연결되고 타측부위는 수경재배통(21) 내부로 연장되는 급수관(45)이 구비되는 제어부:를 포함하는 수조가 마련되는 가정용 수경재배장치를 제공한다. claims: 일정크기의 내부공간이 마련되며 전면부위가 개구되는 몸체(11), 개구된 몸체(11)의 전면부위 하측에 마련되는 가이드레일(12), 몸체(11)의 내부 상면부위에 설치되는 엘이디광원(13), 몸체(11)의 내부 일측부위에 설치되는 온습도기구(14)가 구비되는 하우징부;상측부위가 개구되되 수위감지수단이 마련되어 몸체(11)의 내부공간 하측부위에 안치되는 수경재배통(21), 복수 개의 생육공(23)이 형성되어 개구된 수경재배통(21)의 상측부위를 밀폐하는 지지판(22)이 구비되는 수경재배부;상측부위가 개구되되 하면부위가 가이드레일(11)을 따라 전후로 슬라이딩하며 몸체(11)의 전면부위를 개폐하는 수조부(30);제어보드가 마련되어 몸체(11)의 외면 일측부위에 설치되는 제어박스(41), 제어박스(41)의 일측에 내장되는 모터(42), 모터(42)와 연결되어 제어박스(41)의 타측에 내장되는 펌프(43), 일단부위는 펌프(43)의 일측부위에 연결되고 타측부위는 수조부(30) 내부로 연장되는 배수관(44), 일단부위는 펌프(43)의 타측부위에 연결되고 타측부위는 수경재배통(21) 내부로 연장되는 급수관(45)이 구비되는 제어부:를포함하는 수조가 마련되는 가정용 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

656/1059 Row 656: application_number: 1020200012688, combined_string: invention_title: 액비, 그리고 이를 이용하는 인삼 노지 재배 시스템 abstract: 본 발명은 인삼을 노지에서 재배하는 인삼 노지 재배 시스템에 관한 것이다. 본 발명의 일 실시 예에 따른 인삼 노지 재배 시스템은 인삼이 재배되는 노지에 액비를 분사하는 액비 공급부를 포함하되, 상기 액비는, 식물성 한약재를 발효한 발효액; 및 수용성규소(SiO3/Ge/V)를 포함하는 라바(LAVA)수를 포함한다. claims: 인삼이 재배되는 노지에 액비를 분사하는 액비 공급부; 및상기 노지 및 상기 노지에 인접한 외곽 영역에 미산성 차아염소산수를 분사하는 소독 방제부를 포함하되,상기 액비는, 식물성 한약재를 발효한 발효액; 및 수용성규소(SiO3/Ge/V)를 포함하는 라바(LAVA)수를 포함하는 인삼 노지 재배 시스템.액비를 인삼이 재배되는 노지에 분사하되,상기 액비는,식물성 한약재를 발효한 발효액; 및 수용성규소(SiO3/Ge/V)를 포함하는 라바(LAVA)수를 포함하는 인삼 노지 재배 방법.식물성 한약재를 발효한 발효액; 및 수용성규소(SiO3/Ge/V)를 포함하는 라바(LAVA)수를 포함하는 액비., Ltext: 농업, prediction: 임업
657/1059 Row 657: application_number: 1020200008819, combined_string: invention_title: 수경재배 인삼잎을 이용한 진세노사이드 저배당체 포함 식품 조성물 abstract: 본 발명은 수경재배 인삼잎을 이용한 진세노사이드 저배당체 포함 식품 조성물에 관한 것으로서, 보다 상세하게는 수경재배 인삼잎을 증숙 처리하는 단계를 포함하여 진세노사이드 저배당체 함량이 증가된 인삼잎 농축액을 제조하는 방법, 및 이를 통해 제조된 인삼잎 농축액 및 식품 조성물에 관한 것이다. claims: 물기가 제거된 수경재배 인삼잎을 증숙 처리하는 단계;상기 증숙 처리된 인삼잎을 건조하고 분쇄하는 단계; 및상기 건조 및 분쇄된 인삼잎을 추출하여 농축하는 단계를 포함하는,진세노사이드 1배당체 함량이 증가된 인삼잎 농축액의 제조방법.물기가 제거된 수경재배 인삼잎을 증숙 처리하는 단계;상기 증숙 처리된 인삼잎을 건조하고 분쇄하는 단계; 및상기 건조 및 분쇄된 인삼잎을 추출하여 농축하는 단계를 포함하는,인삼잎 농축액 제조시 진세노사이드 1배당체 함량을 증가시키는 방법.제1항내지 제7항 중 어느 한 항의 방법에 의해 제조된 인삼잎 농축액., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

658/1059 Row 658: application_number: 1020200006549, combined_string: invention_title: 땅콩 나물 재배 방법 abstract: 본 발명은 땅콩 나물 재배 방법에 있어서, 직경이 서로 다른 복수의 톱밥을 혼합 발효한 부토를 재배틀에 담는 단계와, 상기 부토에 땅콩 종자를 파종하는 단계와, 상기 땅콩 종자에 상기 부토를 덮는 단계와, 상기 부토 상에 살수 하는 단계를 포함하는 제1공정과, 상기 제1공정의 시행 이후, 상기 부토에서 생장한 땅콩 나물에 자외선을 일정시간 연속하여 또는 주기적으로 온/오프를 반복하여 조사하는 자외선 조사 단계와, 상기 자외선 조사 단계 이후 상기 땅콩 나물을 수확하는 수확 단계를 포함하는 제2공정으로 이루어지는 땅콩 나물 재배 방법으로서, 본 발명에 따르면 금속성분의 인위적 첨부, 과다한 용수의 사용 및 과다한 시설관리 비용 발생이 없고, 물만으로 재배가 가능하여 무공해 및 유기농이 가능한 땅콩 나물을 높은 수확률로 재배할 수 있으며, 또한, 땅콩의 고유 특성인 레스베라트롤의 함량을 극대화하는 효과를 이룰 수 있다. claims: 땅콩 나물 재배 방법에 있어서,직경이 서로 다른 복수의 톱밥을 혼합 발효한 부토에 땅콩 종자를 파종하는 단계와,상기 땅콩 종자에 상기 부토를 덮는 단계와,상기 부토 상에 살수하는 단계를 포함하는 제1공정과,상기 제1공정의 시행 이후, 생장한 땅콩 나물에 자외선을 일정시간 연속하여 또는 주기적으로 온/오프를 반복하여 조사하는 자외선 조사 단계와,상기 자외선 조사 단계 이후 상기 땅콩 나물을 수확하는 수확 단계를 포함하는 제2공정으로 이루어지는 것을 특징으로 하는 땅콩 나물 재배 방법., Ltext: 농업, prediction: 임업
659/1059 Row 659: application_number: 1020190179745, combined_string: invention_title: 인삼밭을 기반으로 하는 태양광발전장치 및 이를 이용한 인삼의 연작 재배 방법 abstract: 본 발명은 인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법에 관한 것으로서 보다 상세하게는, 인삼을 재배하는 경작지에 최적의 햇볕이 투광할 수 있도록 태양광모듈 사이를 이격시킨 태양광발전장치를 설치하여 발전과 동시에 인삼의 해가림막으로 이용할 수 있고, 태양의 위치 변화에 의해 발생하는 음영부분에 적당량의 햇볕을 전달받거나 반사시킴으로서 적절한 인삼의 생육 환경을 조성할 수 있는 인삼밭을 기반으로 하는 태양광발전장치를 제공하고 이를 이용한 인삼의 연작 재배 방법을 제공하는 것이다. claims: 인삼밭을 기반으로 하는 태양광발전장치에 있어서,상기 인삼밭의 지면위에 경사진 지붕형상으로 일정한 기울기를 갖는 경사프레임(120); 상기 경사프레임(120)의 상부에 설치되는 투명판재(310);상기 투명판재(310)의 상면에 소정의 간격으로 이격시켜 설치되는 복수개의 태양광모듈(200);을 포함하는 것을 특징으로 하는 인삼밭을 기반으로 하는 태양광발전장치.인삼밭을 기반으로 하는 태양광발전장치에 있어서,상기 인삼밭의 지면위에 경사진 지붕형상으로 일정한 기울기를 갖는 경사프레임(120); 상기 경사프레임(120)의 상면에 소정의 간격으로 이격시켜 설치되는 복수개의 태양광모듈(200);이격된 상기 태양광모듈(200)의 사이에 설치되는 투명재질의 투명간격부재(320);를 포함하는 것을 특징으로 하는 인삼밭을 기반으로 하는 태양광발전장치.인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법에 있어서,인삼재배지에서 인삼(400)의 씨앗 또는 묘종을 이용해 재배하는 단계 (S1단계);상기 인삼(400)을 수확하는 단계 (S2단계);상기 인삼(400)의 재배가 끝난 흙을 외부로 걷어내는 단계 (S3단계);새로운 흙에 퇴비 및 비료를 배합하는 단계 (S4단계);상기 새로운 흙을 상기 인삼재배지로 옮긴 후 두둑(410)을 성형하는 단계 (S5단계);를 포함하는 것을 특징으로 하는 인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법.인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법에 있어서,인삼재배지에 인삼(400)의 씨앗 또는 묘종을 이용해 재배하는 단계 (S10단계);상기 인삼(400)을 수확하는 단계 (S20단계);상기 인삼(400)의 재배가 끝난 흙을 외부로 걷어내는 단계 (S30단계);상기 인삼(400)의 재배가 끝난 흙에 인삼 외 타 작물을 재배하여 지력을 회복하는 단계 (S40단계);새로운 흙을 상기 인삼재배지로 옮긴 후 두둑(410)을 성형하는 단계 (S50단계);를 포함하는 것을 특징으로 하는 인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

660/1059 Row 660: application_number: 1020210118072, combined_string: invention_title: 식물포트 이송장치를 가지는 아쿠아포닉스 및 수경 재배 시스템 abstract: 본 발명은 아쿠아포닉스 또는 수경재배를 위한 저수부가 마련되는 수조; 상기 수조 상에서 링형태의 경로를 이동 가능하도록 다수로 배치되고, 식물포트가 상기 저수부의 물이나 양액에 잠기도록 끼워지기 위한 끼움홀이 적어도 하나 이상 형성되는 포트베드; 및 상기 포트베드 각각이 상기 경로를 따라 순차적으로 이동하도록 하는 포트이송부;를 포함하도록 한 식물포트 이송장치를 가지는 아쿠아포닉스 및 수경 재배 시스템에 관한 것이다.본 발명에 따르면, 아쿠아포닉스 및 수경재배에서 식물포트가 장착되는 포트베드가 재배위치로부터 수확위치까지 손쉽게 이동시킬 수 있도록 함으로써, 수확에 소요되는 노력과 인원을 줄여서 인건비 절감 등을 통한 경제적인 재배가 가능하도록 하는 효과를 가진다. claims: 아쿠아포닉스 또는 수경재배를 위한 저수부가 마련되는 수조;상기 수조 상에서 링형태의 경로를 이동 가능하도록 다수로 배치되고, 식물포트가 상기 저수부의 물이나 양액에 잠기도록 끼워지기 위한 끼움홀이 적어도 하나 이상 형성되는 포트베드; 및상기 포트베드 각각이 상기 경로를 따라 순차적으로 이동하도록 하는 포트이송부;를 포함하는, 식물포트 이송장치를 가지는 아쿠아포닉스 및 수경 재배 시스템., Ltext: 농업, prediction: 임업
661/1059 Row 661: application_number: 1020210102742, combined_string: invention_title: LED를 이용한 새싹삼의 재배 또는 사포닌 함량 증진 방법 abstract: 본 발명은 LED를 이용한 새싹삼의 재배 또는 사포닌 함량 증진 방법에 관한 것이다. 구체적으로, 본 발명에 따른 새싹삼 재배 방법은 새싹삼의 지상부 및 지하부의 생체중 및 엽면적, 지상부의 길이 증가, 지상부 및 지하부의 건물중 증가, 및 엽록소 함량 증가를 촉진할뿐만 아니라, 새싹삼에 포함되는 사포닌 함량을 유의적으로 증가시키므로, 새싹삼을 재배하거나 새싹삼에 포함된 사포닌의 함량을 증진시키는데 유용하게 사용될 수 있다. claims: 광원으로 근적외선을 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 배양방법.광원으로 근적외선을 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 사포닌 함량 증진방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

662/1059 Row 662: application_number: 1020210077846, combined_string: invention_title: 새싹 재배 장치 abstract: 본 발명에 따르는 새싹 재배 장치는 물 분사를 위한 노즐이 회전하여 물이 고르게 분사되고, 온도 조절이 신속하게 이루어지며, 약제와 혼합된 물의 펌핑 과정에서 공기가 흡입되지 않아 새싹으로 약제가 원활하게 분사되며, 발아시와 성장시 등 재배 기간을 분할하여, 각 분할된 회수에 대하여 온도를 설정하여 제어할 수 있으므로, 발아율이 높고, 생육이 빠르며, 발아되지 않아 폐기되는 비율을 낮추는 새싹 재배 장치에 관한 것이다. claims: 내부에 전방으로 개구된 재배공간이 형성된 재배기본체(110)와, 상기 재배기본체(110)의 전방에 구비되어 재배공간을 개폐하는 도어(120)와, 상기 재배기본체(110)의 바닥(111) 상부에 구비된 적치부(130)와, 상기 적치부(130)로부터 상향 이격되어 재배공간의 상부에 구비되어 물이 분사되는 분사부(140)와, 일측은 혼합부(160)로 연결되고 타측은 상기 분사부(140)로 연결되며 모터(155)에 의하여 구동되는 공급펌프(153)가 설치된 공급관(150)과, 약제관밸브(173)가 설치된 약제관(171)으로 혼합부(160)에 연결된 하나 이상의 약제통(170)과, 일측이 상기 혼합부(160)로 연결되며 모터(183)에 의하여 구동되는 직수펌프(181)가 설치된 직수관(180)과, 상기 적치부(130)의 하부로 재배기본체(110)에 연결되며 모터에 의하여 구동되는 냉수펌프가 설치되어 냉수가 공급되는 냉수관(191)과, 상기 적치부(130)의 하부로 재배기본체(110)에 연결되며 모터에 의하여 구동되는 온수펌프가 설치되어 온수가 공급되는 온수관(193)과, 일측이 적치부(130)의 하부로 재배기본체(110)에 연결되며 모터에 의하여 구동되는 배수펌프(1951)가 설치되어 바닥(111) 상에 수용된 물이 배출되는 배수관(195)과, 상기 재배기본체(110)에 설치되어 바닥(111) 상에 수용된 물의 온도가 측정되는 수온센서(103)와, 상기 재배기본체(110)에 설치된 수위센서(101)와, 사용자의 명령이 입력되는 입력부와, 정보가 표시되는 디스플레이부와, 운용프로그램이 저장되는 저장부와, 제어부를 포함하며;상기 입력부와, 디스플레이부와, 저장부와, 공급펌프를 구동하는 모터와, 직수펌프를 구동하는 모터와, 냉수펌프를 구동하는 모터와, 온수펌프를 구동하는 모터와, 배수펌프를 구동하는 모터와, 약제관밸브(173)와, 수온센서(103)와, 수위센서(101)는 제어부에 연결되며;재배기간이 복수 회수로 분할되고 각 회수에서의 재배온도가 제어되어 재배되며;상기 입력부를 통하여 분할된 전체회수가 입력되고, 분할된 각 회수가 디스플레이부에 표시되며, 디스플레이부에 표시된 각 회수에 대한 시간과 재배온도가 입력되어 저장부에 저장되며; 입력부를 통하여 재배 시작 명령이 입력되면, 입력된 각 회수의 시간 및 재배온도 정보와, 수온센서(103)에서 센싱된 재배온도 정보와, 수위센서에서 센싱된 수위 정보가 제어부로 전송되고;냉수펌프를 구동하는 모터와, 온수펌프를 구동하는 모터와, 배수펌프를 구동하는 모터의 구동이 제어부로부터의 제어 명령에 의하여 제어됨으로써 각 회수의 재배온도가 제어되어 재배되며;회수가 선택되고 선택된 회수의 순환기동시간과 순환기대기시간이 입력부를 통하여 입력되어 저장부에 저장되며;제어부로 전송된 상기 순환기동시간과 순환기대기시간 정보에 의하여 제어부로부터의 제어 명령에 의하여 순환대기시간 경과 후 순환기동시간 동안 공급펌프를 구동하는 모터 구동이 제어되어, 혼합부(160)에 수용된 물이 공급관(150)과 분사부(140)를 통하여 재배공간으로 분사되는 것을 특징으로 하는 새싹 재배 장치(100)., Ltext: 농업, prediction: 임업
663/1059 Row 663: application_number: 1020210070645, combined_string: invention_title: 스마트 팜 방식의 수경재배장치 abstract: 본 발명은 스마트 팜 방식의 수경재배장치로서, 내측에 배양액이 채워질 수 있는 일정한 공간이 형성되어 있는 외측재배베드; 상기 외측재배베드의 내측에 위치되는 내측재배베드; 상기 외측재배베드의 상부에 식재부가 관통되도록 형성된 외측관통공; 및 상기 내측재배베드에 상기 외측관통공을 관통한 상기 식재부가 관통되도록 형성된 내측관통공을 포함하며, 상기 내측재배베드가 상기 외측재배베드의 내측에서 상하이동이 가능하도록 구성된 수경재배장치에 관한 것이다. claims: 내측에 배양액이 채워질 수 있는 일정한 공간이 형성되어 있는 외측재배베드(100); 상기 외측재배베드(100)의 내측에 위치되는 내측재배베드(200);상기 외측재배베드(100)의 상부에 식재부(500)가 관통되도록 형성된 외측관통공(120); 및상기 내측재배베드(200)에 상기 외측관통공(120)을 관통한 상기 식재부(500)가 관통되도록 형성된 내측관통공(220)을 포함하며,상기 내측재배베드(200)가 상기 외측재배베드(100)의 내측에서 상하이동이 가능하도록 구성되며,상기 내측재배베드(200)는 수평 방향으로 형성된 수평식재부지지판(210); 및 상기 수평식재부지지판(210)의 양단에 수직 방향으로 형성된 배양액배수조절판(240)을 포함하며,상기 외측재배베드(100)는 상기 외측재배베드(100)의 내주면 하부에 상기 외측재배베드(100)의 내주면을 따라 홈 형태로 형성되되, 상기 배양액배수조절판(240)의 일단이 삽입되어 장착되도록 형성된 조절판장착홈(150)을 포함하며,상기 수평식재부지지판(210)의 양단에 형성된 배양액배수조절판(240) 각각이 이에 대응하는 각각의 상기 조절판장착홈(150)에 장착됨에 따라, 상기 배양액배수조절판(240)의 사이에서 형성된 상기 외측재배베드(100)의 내측 공간에 일정한 수위로 배양액이 채워진 상태로 유지되며,상기 내측관통공(220)을 관통한 상기 식재부(500)의 하부가 상기 외측재배베드(100)의 내측 공간에 일정한 수위로 채워진 배양액에 잠긴 상태로 위치되며,상기 외측재배베드(100)의 외측면 상에 위치되는 서보모터(252);상기 서보모터(252)에 결합된 상태에서 상기 외측재배베드(100)의 외측에서 내측으로 관통되는 볼스크류(254); 및상기 볼스크류(254)에 장착되어 상기 볼스크류(254)의 회전에 따라 상하이동되는 너트(256)를 더 포함하며,상기 너트(256)가 상기 배양액배수조절판(240)에 결합된 상태에서, 상기 볼스크류(254)가 회전됨에 따라 상기 내측재배베드(200)가 상하이동되며, 상기 볼스크류(254)의 회전으로 상기 배양액배수조절판(240)이 위로 이동됨에 따라, 상기 배양액배수조절판(240)의 일단이 상기 조절판장착홈(150)에서 벗어나는 경우, 상기 외측재배베드(100)의 내측 공간에 일정한 수위로 채워진 배양액이 외부로 배수되는 수경재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

664/1059 Row 664: application_number: 1020210056152, combined_string: invention_title: 넝쿨작물용 유인 재배장치 abstract: 본 발명은 넝쿨작물용 유인 재배장치에 관한 것으로, 특히 넝쿨작물을 유인줄로 유인 재배하는 과정에서 넝쿨작물의 성장속도에 따라 권취용 드럼에 감긴 유인줄을 하부로 잡아당겨 늘어뜨리는 작업을 매우 용이하게 함은 물론 넝쿨작물용 유인 재배장치의 전체적인 구조를 간소화하여 제조원가를 대폭 절감하는 신개념의 기술에 관한 것이다.종래에 개시된 넝쿨작물용 유인 재배장치는 제조시 초기비용이 많이 들고, 추가부품인 고가의 탄성스프링이 소요되어 조립 공정이 복잡함은 물론 제조원가가 상승하며, 권취용 드럼에 감겨진 유인줄을 풀어 하방으로 늘어뜨리는 작업이 어렵고 불편한 문제점이 야기된다.본 발명은 이러한 문제점을 일소하기 위한 방안으로 권취용 드럼을 회전 가능하게 지지하는 드럼 지지대의 일 측판 내면에 상하로 텐션 가능하게 일체로 돌출 형성된 텐션 락이 상기 권취용 드럼의 락킹을 유지하면서 회전을 방지함과 아울러 상기 텐션 락의 선택적인 누름 조작에 따라 권취용 드럼의 락킹을 일시로 해제하면서 자유롭게 회전할 수 있도록 하는 기술을 강구함을 특징으로 한다. claims: 상, 하판(11)(12)의 양측에 한 쌍의 측판(13)(13a)이 연결됨과 아울러 전후가 개방되고, 상판(11)의 상단에 걸고리(14)가 형성되며, 일 측판(13)(13a)의 하부 내면에 상하로 탄성 가능한 텐션 락(15)이 일체로 돌출 형성된 드럼 지지대(10)와;상기 양 측판(13)(13a)에 형성된 회전축 입출로(16)의 하단에 회전 가능하게 끼움 설치되고, 일측 드럼 플랜지(21)에 돌출 형성된 걸림돌기(24)가 상기 텐션 락(15)에 걸려 회전 정지된 상태를 유지하는 권취용 드럼(20)으로 이루어진 것을 특징으로 하는 넝쿨작물용 유인 재배장치., Ltext: 농업, prediction: 임업
665/1059 Row 665: application_number: 1020210052534, combined_string: invention_title: 녹용유래세포 배양액을 이용한 수경재배 방법 abstract: 본 발명은 녹용유래세포 배양액을 함유하는 재배수에서 식물 또는 식물 종자를 재배하는 것을 특징으로 하는 식물의 수경재배 방법에 관한 것으로, 본 발명에 따라 녹용유래세포 배양액을 재배수로 사용하여 식물을 재배하는 경우, 성장촉진제나 항생제 등의 사용없이도 병해없이 식물을 재배할 수 있어, 안전한 식용작물을 재배할 수 있는 효과가 있다. claims: 식물 수경 재배 방법에 있어서,투관침 또는 외과적 방법으로 획득된 녹용유래세포를 기본배지에서 배양하여 녹용유래세포 배양액을 수득하고, 수득된 배양액을 양액에 첨가하여 식물의 재배 과정에서 주입하는 것을 특징으로 하는 식물 수경 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

666/1059 Row 666: application_number: 1020210033791, combined_string: invention_title: 튜브형 식물재배 시스템 abstract: 본 발명은 구조가 개선된 튜브형 식물재배 시스템에 관한 것으로써, 유연한 소재로 이루어지고, 일측 또는 다측이 구부려져 형성되는 굴곡부에서 연장된 끝부분에 소정의 간극을 유지하며 대칭되는 길이방향 양쪽 내측 표면이 개방되는 밀착부를 구비하고 그 내부에 공간부가 구비되는 튜브부; 상기 밀착부 내측 양족 표면이 포개지며 상호 탈착되는 벨크로 테이프;를 포함함으로써, 상기 공간부에 식물의 뿌리가 내설되고, 식물의 줄기부분은 밀착부 내측 양쪽 표면의 상기 벨크로테이프에 의해 고정되며, 식물을 재배하는 것을 특징으로 하는 튜브형 식물재배 시스템을 제공한다. claims: 유연한 소재로 이루어지고, 일측 또는 다측이 구부려져 형성되는 굴곡부에서 연장된 끝부분에 소정의 간극을 유지하며 대칭되는 길이방향 양쪽 내측 표면이 개방되는 밀착부를 구비하고 그 내부에 공간부가 구비되는 튜브부;상기 밀착부 내측 양족 표면이 포개지며 상호 탈착되는 벨크로테이프;를 포함함으로써,상기 공간부에 식물의 뿌리가 내설되고, 식물의 줄기부분은 밀착부 내측 양쪽 표면의 상기 벨크로테이프에 의해 고정되며, 식물을 재배하는 것을 특징으로 하는 튜브형 식물재배 시스템., Ltext: 농업, prediction: 임업
667/1059 Row 667: application_number: 1020210028625, combined_string: invention_title: 통신 인터페이스와 인공 지능에 기반한 개인용 식물 재배 장치 및 시스템 abstract: 원격 제어가 가능한 개인용 식물 재배 시스템이 개시된다. 개인용 식물 재배 시스템은 식물을 수경 재배하기 위한 식물 재배 장치, 상기 식물 재배 장치와 유선 또는 통신 인터페이스에 기반하여 연결되는 서버, 및 소정의 어플리케이션을 통해 상기 식물 재배 장치와 연결되고 상기 식물 재배 장치를 제어하기 위한 사용자의 개인 단말기를 포함할 수 있다. 상기 식물 재배 장치는, 상기 식물에 공급되는 양액을 저장하기 위한 수조, 상기 식물 재배 장치의 외부의 공기를 흡입하여 상기 양액에 투입하기 위한 에어 펌프, 재배 환경과 관련된 정보들을 감지하기 위한 센서부, 상기 식물을 촬영하여 영상 데이터를 획득하기 위한 카메라, 상기 재배 환경과 관련된 변수를 조절하기 위한 액추에이터, 및 상기 식물 재배 장치의 동작을 제어하고 유선 또는 무선 통신 인터페이스가 포함된 적어도 하나의 프로세서를 포함할 수 있다. claims: 식물을 수경 재배하기 위한 식물 재배 장치;상기 식물 재배 장치와 유선 또는 통신 인터페이스에 기반하여 연결되는 서버; 및소정의 어플리케이션을 통해 상기 식물 재배 장치와 연결되고 상기 식물 재배 장치를 제어하기 위한 사용자의 개인 단말기를 포함하고,상기 식물 재배 장치는, 상기 식물에 공급되는 양액을 저장하기 위한 수조; 상기 식물 재배 장치의 외부의 공기를 흡입하여 에어 라인을 통해 상기 양액에 투입하기 위한 에어 펌프; 재배 환경과 관련된 정보들을 감지하기 위한 센서부; 상기 식물을 촬영하여 영상 데이터를 획득하기 위한 카메라; 상기 재배 환경과 관련된 변수를 조절하기 위한 액추에이터; 및 상기 식물 재배 장치의 동작을 제어하고 유선 또는 무선 통신 인터페이스가 포함된 적어도 하나의 프로세서를 포함하고,상기 에어 펌프를 통해 흡입되어 상기 에어 라인을 통해 상기 양액에 투입된 공기 중의 미세 먼지는 상기 수조 내부에 침전되거나 상기 식물의 뿌리로 흡수되고,상기 센서부는 온도 센서, 습도 센서, 광 센서, 및 EC(Electric Conductivity) 센서를 포함하고,상기 액추에이터는, 광을 조절하기 위한 LED 광원, 양액의 공급을 조절하기 위한 관수 펌프, 온도를 조절하기 위한 팬이나 펠티어를 포함하고,상기 재배 환경과 관련된 정보, 상기 액추에이터의 동작 정보, 및 상기 영상 데이터 각각은 기준 시간마다 획득되어 상기 서버로 전송되고,상기 액추에이터는 상기 재배 환경과 관련된 정보, 상기 액추에이터의 동작 정보, 및 상기 영상 데이터 중 적어도 하나에 기반하여 생성된 제어 신호 하에 동작하거나 상기 개인 단말기로부터 수신되는 제어 신호 하에 동작하고,상기 사용자는 상기 재배 환경과 관련된 정보, 상기 액추에이터의 동작 정보, 및 상기 영상 데이터를 상기 어플리케이션을 통해 확인할 수 있고,상기 식물의 정식 후 경과일, EC정보, 온도 정보, 조도 정보, 습도 정보, 및 상기 관수 펌프의 동작 여부 정보를 포함하는 6개 타입의 입력 데이터들 각각은 상기 식물의 정식 후에 소정의 시간 구간마다 획득되고,상기 서버는 상기 식물의 정식 후 경과일 동안 획득된 상기 6개 타입의 입력 데이터들을 소정의 단위기간 동안 누적시켜 예측 모델에 입력하고, 상기 예측 모델은 상기 식물의 키 또는 잎면적 지수 정보를 출력하고,상기 예측 모델은, 복수의 식물 재배 장치들로부터 획득된 상기 6개 타입의 입력 데이터들을 입력으로 적용하고 상기 카메라에 의해 획득된 영상 데이터로부터 획득되는 상기 식물의 키 또는 잎면적 지수를 출력으로 적용하는 기계 학습에 기반하여 생성되고,상기 복수의 식물 재배 장치들은 상기 식물 재배 장치과 다른 식물 재배 장치를 포함하는 개인용 식물 재배 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

668/1059 Row 668: application_number: 1020210026990, combined_string: invention_title: 식물 재배장치 abstract: 본 발명에 따른 식물 재배장치는 여러 개를 온실의 폭 방향으로 병렬로 배치하여 식물을 재배할 수 있으면서도 재배식물이 햇빛이나 외부조명을 골고루 받을 수 있도록 할 수 있다. 상기 식물 재배장치는 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임, 한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체 및 한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고, 복수의 상기 식물재배용기에 양액을 공급하기 위한 양액공급기를 포함하고, 상기 양액공급기는, 양액 공급용기, 복수의 상기 식물재배용기에 일단이 각각 연결된 복수의 호스 및 복수의 상기 호스의 타단에 연결되어 상기 양액 공급용기의 양액을 복수의 상기 호스를 통해 상기 식물재배용기로 공급하며 상기 순환체의 회전에 따라 회전되는 회전 양액공급관을 포함하는 구성을 한다. claims: 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임;한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체; 및한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고,복수의 상기 식물재배용기에 양액을 공급하기 위한 양액공급기를 포함하고,상기 양액공급기는,양액 공급용기;복수의 상기 식물재배용기에 일단이 각각 연결된 복수의 호스; 및복수의 상기 호스의 타단에 연결되어 상기 양액 공급용기의 양액을 복수의 상기 호스를 통해 상기 식물재배용기로 공급하며 상기 순환체의 회전에 따라 회전되는 회전 양액공급관을 포함하는 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 임업
669/1059 Row 669: application_number: 1020210026999, combined_string: invention_title: 식물 재배장치 abstract: 본 발명에 따른 식물 재배장치는 여러 개를 온실의 폭 방향으로 병렬로 배치하여 식물을 재배할 수 있으면서도 재배식물이 햇빛이나 외부조명을 골고루 받을 수 있도록 할 수 있다. 상기 식물 재배장치는 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임, 한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체 및 한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고, 상기 순환체를 따라 순환하는 복수의 상기 행거바의 내부에 복수의 상기 식물재배용기에서 재배되는 식물을 향해 빛을 쬐기 위한 조명기구가 설치되는 것을 포함하는 구성을 한다. claims: 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임;한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체; 및한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고,상기 순환체를 따라 순환하는 복수의 상기 행거바의 내부에 복수의 상기 식물재배용기에서 재배되는 식물을 향해 빛을 쬐기 위한 조명기구가 설치되는 것을 포함하는 것을 특징으로 하는 식물재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

670/1059 Row 670: application_number: 1020210027000, combined_string: invention_title: 식물 재배장치 abstract: 본 발명에 따른 식물 재배장치는 여러 개를 온실의 폭 방향으로 병렬로 배치하여 식물을 재배할 수 있으면서도 재배식물이 햇빛이나 외부조명을 골고루 받을 수 있도록 할 수 있다. 상기 식물 재배장치는 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임, 한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체 및 한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고, 상기 행거바에 간격을 두고 베어링이 설치되고, 상기 식물재배용기는 상기 베어링에 걸려있는 줄을 통해 상기 행거바에 매달려 있는 것을 포함하는 구성을 한다. claims: 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임;한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체; 및한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고,상기 행거바에 간격을 두고 베어링이 설치되고, 상기 식물재배용기는 상기 베어링에 걸려있는 줄을 통해 상기 행거바에 매달려 있는 것을 포함하는 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 농업
671/1059 Row 671: application_number: 1020210026851, combined_string: invention_title: 농작물용 지주 abstract: 본 발명은 고추, 토마토, 가지와 같은 농작물이 넘어지지 않도록 받치는 지주(支柱)에 관한 것으로 보다 구체적인 것은, 파이프부재로 된 기둥에 결합하여 설치높이를 임의로 조정할 수 있도록 되고, 합성수지로 성형되어 녹슬지 않으며, 지주 사이에 가설되는 지지끈을 쉽게 결속시켜 유지시켜주고, 보조지주를 결합시킬 수 있게 하여 다양하게 활용할 수 있는 편리한 지주가 되게 한 농작물용 지주이다. claims: 금속 또는 합성수지 파이프로 되어 일정길이를 가지는 중심지주(1)와, 중심지주에 상하방향으로 끼워져 위치가 선택되는 지지구(2)와, 지지구(2)를 중심지주(1)에 고정시키는 고정자(3)와, 지지구에 결합되는 보조지주(4)(4a)와, 지지구(2) 및 보조지주(4)(4a) 사이에 설치되는 지지끈(5)으로 이루어지는 농작물용 지주로서, 중심지주(1)는 직경 24mm 되는 아연도강 파이프 또는 합성수지 파이프가 선택되고, 지지구(2)는 합성수지로 성형되어, 중심부에 세로방향으로 중심지주(1)에 끼워지는 중심연결관(20)이 형성되고, 중심연결관(20)은 상단부 직경이 24∼25mm이고, 하단부 직경이 27∼28mm 되는 상협하광형 테이프관체로 형성되며, 중심연결관 양측으로 상단부 폭이 길고, 하단부 폭이 좁아 위가 넓고 하측이 좁은 역사다리꼴의 연결판(21)(22)이 형성되고, 양측 연결판의 좌우측단에는 연결판에 부착되고, 위에서 아래로 경사지며, 중심구멍이 상하로 개방되어 하단 개방부가 중심지주(1) 표면을 향하는 경사연결관(23)(24)이 형성되어 보조지주(4)가 끼워지고, 연결판(21)(22) 상단부와 경사연결관 외주면에는 외측단부에 환상돌출턱(25a)이 형성된 지지끈결속부(25)가 돌출형성되어 지지끈(5)이 결속되며, 연결판(21)(22) 전방에는 관통구멍(26a)(27a)이 횡으로 형성되는 한쌍의 횡연결관(26)(27)을 나란히 형성하여 보조지지대(4a)가 관통되게 끼워지고, 고정자(3)는 합성수지로 성형되는 반분원통체(30)(31)로 형성되어 중심부 직경은 중심지주 외경과 같고, 외경은 위가 좁고 아래가 점차 넓어지는 테이퍼면이 형성되어 중심지주(1)와, 지지구(2)의 중심연결관(20) 사이에 개입되며, 반분원통체(30)(31)의 결합부에 요입홈(30a)(31a)과 돌출편(30b)(31b)이 형성되어 서로 결합하고, 분리할 수 있게 한 구성으로 만든 농작물용 지주., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

672/1059 Row 672: application_number: 1020200184459, combined_string: invention_title: 수직형 수경재배기 abstract: 본 발명은 수직형 수경재배기에 관한 것으로, 보다 상세하게는 재배포트에 일정한 양의 양액을 지속적으로 공급할 수 있는 수직형 수경재배기에 관한 것이다. 본 발명은 다음과 같은 효과를 발휘한다.즉, 본 발명에 따르면, 재배포트에 일정한 양의 양액을 지속적으로 공급할 수 있기 때문에 식물의 안정적인 생장을 도모할 수 있고, 사용자의 스마트기기(스마트폰, 태블릿 PC 등)와 양방향 통신을 통한 데이터의 송수신이 가능하도록 구성하여 실시간 업데이트가 반영되는 장점이 있다. claims: 사용자의 스마트기기와 양방향 통신이 가능하되, 양액자동제어기(900)의 물 및 양액 상태, 물교체 잔여일자, 양액 추가공급 잔여일자, 물 및 양액의 수위정보, 광조사수단(300) 및 펌프(700)의 동작상태를 포함한 데이터가 스마트기기로 송신되고, 재배된 식물정보, 광 조사시간, 현재 시각을 포함한 데이터가 스마트기기로부터 수신되는 수직형 수경재배기에 있어서,사각 형상의 프레임(100);상기 프레임(100)의 상측에 설치되는 나무 형상의 재배관(200);상기 프레임(100)의 양측에 설치되어, 재배관(200)에 광을 조사하는 광조사수단(300);상기 프레임(100)의 하측에 배치되어, 재배관(200)의 하부관(220)을 통과한 양액(m)이 저장되는 양액탱크(400);상기 양액탱크(400)에 저장된 양액(m)이 재배관(200)의 상부관(210)으로 이동되는 양액이동관(500);상기 광조사수단(300)의 양측에서 재배관(200)을 바라보는 방향으로 형성되어, 광조사수단(300)에서 출력되는 광이 재배관(200) 방향으로 모이도록 유도하는 집광판(600);상기 양액탱크(400) 내부에 형성되되, 양액이동관(500)으로 양액(m)을 펌핑하는 펌프(700);상기 양액탱크(400)에 저장된 양액(m)의 상태를 조절하는 양액자동제어기(900);를 포함하되,상기 재배관(200)은프레임(100)의 상측에 설치되되, 양액이동관(500)으로부터 양액(m)을 공급받는 상부관(210)과,상기 상부관(210)의 하단에 연통되어, 상부관(210)으로부터 양액(m)을 공급받는 하부관(220)을 포함하고,상기 상부관(210)은양액이동관(500)으로부터 양액(m)을 공급받는 제1상부관(211)과,상기 제1상부관(211)에 연통되어, 제1상부관(211)으로부터 양액(m)을 공급받는 제2상부관(212)을 포함하고,상기 제1상부관(211)은제1상부관(211)의 단부에 돌출 형성됨으로써 제2상부관(212)으로 양액(m)이 공급될 때 양액(m)이 두 갈래로 갈라지도록 하여, 제2상부관(212)의 제1유로(212a)와 제2유로(212b)로 양액(m)의 분배를 유도하는 양액분배유도부재(211a)를 포함하고,상기 제2상부관(212)의 내부에는양액이동관(500)으로부터 공급받은 양액(m)이 제1포트삽입관(221a)과 연통되는 지점과 인접한 하부관(220)의 내측벽(A)으로 이동되도록 유도하는 제1유로(212a)와,양액이동관(500)으로부터 공급받은 양액(m)이 제2포트삽입관(221b)과 연통되는 지점과 인접한 하부관(220)의 내측벽(B)으로 이동되도록 유도하는 제2유로(212b)를 포함하고,상기 제1유로(212a)는제2상부관(212)의 내측면을 따라 나선형의 미끄럼틀의 형상으로 형성되되, 제1상부관(211)과 연통되는 지점과 인접한 위치에서 제1포트삽입관(221a)과 연통되는 지점과 인접한 상부관(210)의 내측벽(A)까지 연장 형성되는 것을 특징으로 하고,상기 제2유로(212b)는제2상부관(212)의 내측면을 따라 나선형의 미끄럼틀의 형상으로 형성되되, 제1상부관(211)과 연통되는 지점과 인접한 위치에서 제2포트삽입관(221b)과 연통되는 지점과 인접한 상부관(210)의 내측벽(B)까지 연장 형성되는 것을 특징으로 하고,상기 하부관(220)은하부관(220)의 양측에서 광조사수단(300)을 바라보는 방향으로 연통되고, 식물(1)이 재배되는 재배포트(10)가 설치되는 포트삽입관(221)을 포함하고,상부관(210)으로부터 공급받은 양액(m)을 포트삽입관(221)에 공급하되, 포트삽입관(221)에 공급하고 남은 양액(m)은 양액탱크(400)로 배출되는 것을 특징으로 하고,상기 포트삽입관(221)은하부관(220)의 일측에서 제1광조사수단(310)을 바라보는 방향으로 형성되는 제1포트삽입관(221a)과,하부관(220)의 타측에서 제2광조사수단(320)을 바라보는 방향으로 형성되는 제2포트삽입관(221b)을 포함하고,상기 광조사수단(300)은프레임(100)의 일측에 설치되는 제1광조사수단(310)과,상기 제1광조사수단(310)과 대향되는 프레임(100)의 타측에 설치되는 제2광조사수단(320)을 포함하고,상기 집광판(600)은제1광조사수단(310)의 양측에 형성되는 제1집광판(610)과,제2광조사수단(320)의 양측에 형성되는 제2집광판(620)을 포함하는 것을 특징으로 하는수직형 수경재배기., Ltext: 농업, prediction: 임업
673/1059 Row 673: application_number: 1020200182483, combined_string: invention_title: 유효성분이 강화된 엉겅퀴의 재배방법 abstract: 본 발명은 엉겅퀴를 2년에 걸쳐 재배하면서 엉겅퀴에 함유된 생리활성 물질이 가장 많이 함유되는 시기에 맞추어 부위별로 수확하는 엉겅퀴의 재배방법에 관한 것이다.본 발명의 엉겅퀴 재배방법은 노화잎이 발생되지 않는 양호한 품질의 엉겅퀴 잎을 2년에 걸쳐 여러 번 수확하고 엉겅퀴 꽃에 함유된 유용성분까지 이용할 수 있어서 엉겅퀴의 수확량이 증대되고, 엉겅퀴에 함유된 특정 생리활성 물질이 성분에 따라 부위별로 가장 많이 함유된 시기에 맞추어 수확하므로 엉겅퀴로부터 유효성분을 최대한 생산할 수 있으며, 채취한 씨앗의 발아율이 높다. claims: 엉겅퀴 종자를 파종하여 발아 및 생육시키는 단계;5월 중순~7월 중순에 엉겅퀴 잎을 1차 수확하는 단계;9월 중순~11월 초순에 엉겅퀴 잎을 2차 수확하고 일부 엉겅퀴의 뿌리를 수확하는 단계;이듬해 4월 중순~5월 상순의 2년생 엉겅퀴 꽃이 개화되기 전에 뿌리를 수확하지 않은 엉겅퀴로부터 잎을 3차 수확하는 단계;6월 초순~6월 중순에 측지에서 발생하는 2년생 꽃봉오리를 수확하면서 본줄기의 꽃에 맺힌 종자를 채종하는 단계; 및종자 채종 이후 발생하는 2년생 꽃의 꽃봉오리가 형성되기 시작하는 시점에서 꽃봉오리가 개화하기 직전까지의 엉겅퀴 꽃, 잎 및 줄기를 수확하는 단계;를 포함하는 엉겅퀴의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

674/1059 Row 674: application_number: 1020200156417, combined_string: invention_title: 모듈형 식물재배장치 및 식물재배장치의 화분모듈 abstract: 본 발명은 화분모듈을 수직으로 직립하게 쌓아 올림으로써 한정된 공간에서 일체화된 디자인의 구현할 수 있는 다층 구조의 식물재배장치에 관한 것으로, 수조를 포함하는 베이스부와, 베이스부의 상단에 장착되는 설치대와, 상기 설치대에 다층 구조로 적층이 이루어지는 화분모듈을 포함하고, 상기 화분모듈에 식물이 식재된 상태에서 수조로부터 공급된 물 또는 양액이 적층된 화분모듈의 상층부로부터 하층부로 순차적으로 경유하면서 양분 공급이 이루어지게 되는 다층 구조의 모듈형 식물재배장치에 있어서, 상기 화분모듈은 모듈본체에 복수의 식재포트를 장착하되, 식재포트를모듈본체의 둘레를 따라서 방사상으로 배열하고, 상기 화분모듈이 다단으로 적층되는 구조를 가지면서 수직으로 적층된 상태를 유지하도록 하기 위하여 모듈본체의 중앙부가 상부로 돌출된 상태에서 그 둘레를 따라서 복수의 식재포트가 외주연측을 향하여 하부측으로 기울어지게 배열되어 화분모듈이 수직으로 다층 배열이 이루어지면서 협소한 공간에서 일체화된 디자인으로 공간활용을 할 수 있도록 함은 물론, 상기 모듈본체는 상,하단에는 각각 연결부와 하향돌출부가 서로 대응하게 형성하여 모듈본체를 수직으로 적층 조립이 가능하도록 하고, 연결부에는 공급로를 하향돌출부에는 층간배수홀을 각각 형성하되, 식재포트에는 공급로 및 층간배수홀과 연통하게 유입공 및 배수구를 각각 형성하여 화분모듈이 다층 구조로 적층된 상태에서 상층부로부터 하층부측으로 물 또는 양액이 순차적으로 경유하면서 양분 공급이 이루어지도록 함으로써 화분모듈간 상호 조립구조로 순차적으로 간단하게 조립 및 분리가 가능하고, 자중에 의하여 간단하게 조립이 가능하며, 수직공간으로 화분을 적층구성하여 설치장소의 제약없이 다양한 공간연출이 가능하도록 한 것이다. claims: 수조(120)를 포함하는 베이스부(100)와,베이스부(100)의 상단에 장착되는 설치대(200)와,상기 설치대에 다층 구조로 적층이 이루어지는 화분모듈(300)을 포함하고, 상기 화분모듈(300)에 식물이 식재된 상태에서 수조(120)로부터 공급된 물 또는 양액이 적층된 화분모듈의 상층부로부터 하층부로 순차적으로 경유하면서 양분 공급이 이루어지게 되는 다층 구조의 모듈형 식물재배장치에 있어서,상기 화분모듈(300)은 모듈본체(320)에 복수의 식재포트(340)가 장착되되, 식재포트(340)는 모듈본체의 둘레를 따라서 방사상으로 배열되고,상기 화분모듈(300)이 다단으로 적층되는 구조를 가지면서 수직으로 적층된 상태를 유지하기 위하여 모듈본체(320)의 중앙부가 상부로 돌출된 상태에서 그 둘레를 따라서 복수의 식재포트(340)가 외주연측을 향하여 하부측으로 기울어지게 배열되어 수직공간으로 화분모듈의 배열이 이루어지고,상기 화분모듈(300)은 모듈본체(320)의 상,하단에 각각 연결부(322)와 하향돌출부(324)가 서로 대응하게 형성되어 화분모듈(300)의 적층 조립이 이루어지되, 상기 연결부(322)에는 공급로(323)가 상기 하향돌출부(324)에는 층간배수홀(305)이 각각 형성되고,상기 식재포트(340)는 공급로(323) 및 층간배수홀(325)과 연통하게 유입공(343) 및 배수구(345)가 형성되어 화분모듈(300)이 다층 구조로 적층된 상태에서 상층부로부터 하층부측으로 물 또는 양액이 순차적으로 경유하면서 양분 공급이 이루어지며,상기 화분모듈(300)은 모듈본체(320)에 형성된 하향돌출부(324)가 모듈본체(320)의 연결부(322)에 조립될 때 모듈본체(320)의 하부가 하향 경사지게 형성되어 하층부의 모듈본체(320)의 상단에 안착되어 조립부속이 없이도 단순 적층 구조로 조립이 가능하면서 조립부위가 외부로 노출되지 않고 식재포트(340)만 노출되어 협소한 공간에서 일체화된 디자인으로 공간활용을 할 수 있게 되는 모듈형 식물재배장치.수직으로 쌓아서 다층 구조로 식물의 식재가 가능하도록 하는 모듈본체(320)와, 모듈본체의 외주연을 따라서 식물을 생육하기 위한 복수의 식재포트(340)가 구비되고,상기 모듈본체(320)의 상,하단에는 각각 연결부(322)와 하향돌출부(324)가 서로 대응하게 형성되어 모듈본체(320)를 수직으로 적층 조립이 가능하게 되며, 상기 연결부(322)에는 공급로(323)가 상기 하향돌출부(324)에는 층간배수홀(325)이 각각 형성되되, 식재포트(340)에는 상기 공급로(323) 및 층간배수홀(325)과 연통하게 유입공(343) 및 배수구(345)가 각각 형성되어 화분모듈(300)이 다층 구조로 적층된 상태에서 상층부로부터 하층부측으로 물 또는 양액이 순차적으로 경유하면서 양분 공급이 이루어지지고,상기 모듈본체(320)는 중앙부가 상부로 돌출된 상태에서 그 둘레를 따라서 복수의 식재포트(340)가 외주연측을 향하여 하부측으로 기울어지게 배열되어 수직으로 화분모듈의 배열이 이루어지면서 협소한 공간에서 일체화된 디자인 공간연출이 가능하게 되며, 상기 화분모듈(300)은 모듈본체(320)를 구성하는 상부체(320a)와 하부체(320b) 및 모듈본체(320)에 탈착 가능하게 구비되는 식재포트(340)로 3단 구조로 조립이 이루어지고, 상기 상,하부체(320a,320b)는 돌출부(302)와 내입부(304)를 구성하도록 덮개부(321a)와 집수정(321b)이 형성되되 덮개부(321a)에 식재포트(340)의 끼움위치를 설정하는 안착대(327)가 형성되어 안착대(327)가 집수정(321b)에 삽입되어 식재포트(340)의 정위치 조립이 가능하게 됨을 특징으로 하는 식물재배장치의 화분모듈., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

675/1059 Row 675: application_number: 1020200156653, combined_string: invention_title: 분무식 수경 재배장치 abstract: 본 발명은 본체; 식재된 육묘 뿌리가 아래로 통과하는 다수개의 뿌리통과공이 형성된 재배대가 상기 본체에 상하로 이격되게 다단 배치된 트레이부; 상기 본체에 설치되어 다단 배치된 상기 재배대의 하부에 각각 배치되며 상기 재배대에 식재된 육묘 뿌리로 양액을 분무하는 분무노즐을 포함하는 복수개의 양액분무부; 상기 본체에 복수개가 이격되게 설치되며 상기 재배대로 양액을 분무하는 상기 분무노즐을 포함하는 양액분무부를 지지하는 양액분무부 지지대; 상기 본체에 상하로 다단 배치된 상기 재배대의 상부에 각각 배치되어 상기 재배대에 식재된 육묘로 하나 이상의 파장을 갖는 광을 조사하는 조명장치를 포하하는 복수개의 조명장치부; 및 상기 재배대의 하부에 배치되는 각각의 양액분무부의 하부에 각각 설치되며, 상기 양액분무부로부터 분무된 양액을 회수하여 일측에서 타측으로 이동시키는 복수개의 방수패드를 포함하는 양액회수부를 포함하되, 상기 복수개의 양액분무부 지지대는 상기 본체에 상기 재배대와 상기 방수패드의 사이에 위치하며, 상기 양액분무부 지지대는 막대형상을 가지는 지지몸체와, 상기 지지몸체에 구비되며 상기 지지몸체를 상기 본체에 장착하는 장착고리와, 상기 지지몸체의 하부에 구비되며 상기 분무노즐로 양액을 공급하며 이격되게 위치하는 복수개의 분무노즐을 연결하는 연결호스를 지지하는 지지고리를 포함하고, 상기 장착고리는 상기 지지몸체의 양단에서 외측으로 돌출되게 구비되어 상기 본체에 걸림장착되며, 상기 지지고리는 상기 지지몸체의 하부로 복수개가 상기 지지몸체의 길이방향으로 이격되게 구비되고, 상기 방수패드가 사다리꼴 형상을 가짐으로써 상기 방수패드가 상기 본체에 설치 시 상기 방수패드의 윗변과 아랫변의 높이가 달라져 윗변 보다 아래쪽에 위치하는 아랫변 측으로 양액이 이동되는 것을 특징으로 하는 분무식 수경 재배장치를 제공한다.따라서, 재배대의 하부에 설치되는 분무노즐 및 분무노즐을 연결하는 연결호스를 본체의 가로프레임에 장착되는 양액분무부 지지대에 안착시킴으로써 분무노즐 및 연결호스를 재배대의 하부에 손쉽게 고정할 수 있다. claims: 본체;식재된 육묘 뿌리가 아래로 통과하는 다수개의 뿌리통과공이 형성된 재배대가 상기 본체에 상하로 이격되게 다단 배치된 트레이부;상기 본체에 설치되어 다단 배치된 상기 재배대의 하부에 각각 배치되며 상기 재배대에 식재된 육묘 뿌리로 양액을 분무하는 분무노즐을 포함하는 복수개의 양액분무부;상기 본체에 복수개가 이격되게 설치되며 상기 재배대로 양액을 분무하는 상기 분무노즐을 포함하는 양액분무부를 지지하는 양액분무부 지지대;상기 본체에 상하로 다단 배치된 상기 재배대의 상부에 각각 배치되어 상기 재배대에 식재된 육묘로 하나 이상의 파장을 갖는 광을 조사하는 조명장치를 포하하는 복수개의 조명장치부; 및상기 재배대의 하부에 배치되는 각각의 양액분무부의 하부에 각각 설치되며, 상기 양액분무부로부터 분무된 양액을 회수하여 일측에서 타측으로 이동시키는 복수개의 방수패드를 포함하는 양액회수부를 포함하되,상기 복수개의 양액분무부 지지대는 상기 본체에 상기 재배대와 상기 방수패드의 사이에 위치하며,상기 양액분무부 지지대는,막대형상을 가지는 지지몸체와,상기 지지몸체에 구비되며 상기 지지몸체를 상기 본체에 장착하는 장착고리와,상기 지지몸체의 하부에 구비되며 상기 분무노즐로 양액을 공급하며 이격되게 위치하는 복수개의 분무노즐을 연결하는 연결호스를 지지하는 지지고리를 포함하고,상기 장착고리는 상기 지지몸체의 양단에서 외측으로 돌출되게 구비되어 상기 본체에 걸림장착되며,상기 지지고리는 상기 지지몸체의 하부로 복수개가 상기 지지몸체의 길이방향으로 이격되게 구비되고,상기 방수패드가 사다리꼴 형상을 가짐으로써 상기 방수패드가 상기 본체에 설치 시 상기 방수패드의 윗변과 아랫변의 높이가 달라져 윗변 보다 아래쪽에 위치하는 아랫변 측으로 양액이 이동되는 것을 특징으로 하는 분무식 수경 재배장치., Ltext: 농업, prediction: 임업
676/1059 Row 676: application_number: 1020200156867, combined_string: invention_title: 버섯 재배용 배지의 스마트 수분공급장치 abstract: 본 발명은 버섯 재배용 배지의 스마트 수분공급장치에 관한 것으로 내부에 소정공간이 형성되며, 상부에는 하나 이상의 버섯배지를 지지하도록 형성된 배지트레이가 안착될 수 있도록 형성된 몸체유닛과 상기 몸체유닛의 상부에 상하로 승강 가능하게 형성되는 이송프레임을 포함하는 이송유닛과 상기 이송프레임에 장착되어 상기 이송프레임과 함께 승하강 되며, 버섯배지에 수분을 공급는 침봉을 포함하는 침봉유닛과 상기 침봉을 통해서 버섯배지에 수분이 공급되도록 상기 침봉유닛으로 물을 공급하는 물공급유닛을 구비하는 것이다.본 발명에 따르면 재배사 전체의 배지에 정량의 물 공급시간을 획기적으로 감축하게 되고 각각의 배지를 일일이 옮겨가며 침봉하지 않아 노동력을 대폭 절감할 수 있으며, 수확중에도 배지에 필요한 수분을 설치된 시스템을 통해 수시로 공급할 수 있어 고품질의 버섯을 생산하며 동시에 발아시기와 수확시기를 비교적 안정적으로 컨트롤 할 수 있게 된다. claims: 버섯배지를 지지하도록 형성된 배지트레이가 안착되는 안착부와, 상기 안착부에 마련되어서 상기 버섯배지에 유입되는 물의 양을 측정하도록 형성된 무게센서를 포함하는 몸체유닛과;상기 몸체유닛의 상부에 상하로 승강 가능하게 형성되는 이송프레임의 하부에 연결되어 승하강하고, 급수를 위한 침봉이 상기 버섯배지에서 삽입 또는 이탈시 상기 버섯배지가 움직이지 않도록 상기 버섯배지의 상부를 가압하는 배지고정판을 포함하는 이송유닛과;상기 이송프레임에 장착되어 상기 이송프레임과 함께 승하강 되며, 버섯배지에 수분을 공급하는 상기 침봉을 포함하는 침봉유닛과;상기 침봉을 통해서 상기 버섯배지에 수분이 공급되도록 상기 침봉유닛으로 물을 공급하는 물공급유닛과;상기 침봉을 세척하도록 상기 배지고정판에 형성되어, 상기 침봉을 향하여 세척수를 분사하는 세척부를 구비하고;상기 배지고정판은 상기 침봉이 상기 배지고정판의 하부에 위치하는 상기 버섯배지로 삽입 가능하도록 상기 침봉이 관통할 수 있는 관통홀이 형성되어 있고, 상기 배지고정판은 상기 이송프레임의 하부에서 하방으로 연장되는 스프링로드를 따라 승강이 이루어질 수 있도록 형성되고, 상기 스프링로드를 감싸며 상단과 하단이 각각 상기 이송프레임과 상기 배지고정판에 지지되는 스프링에 의해서 상기 이송프레임으로부터 멀어지는 방향으로 탄성지지 되고,상기 세척부는상기 배지고정판에 형성되되, 상기 배지고정판의 내부에서 세척수가 이동할 수 있게 형성된 세척수유로와,상기 관통홀의 내주면에 형성되어 상기 관통홀을 통해 승강 또는 하강하는 상기 침봉의 외주면을 향해 세척수를 분사하는 세척노즐을 포함하고,상기 침봉은 상기 물공급유닛으로부터 물이 공급될 수 있게 연결되어 상기 이송프레임에 설치되고, 단부가 상기 버섯배지에 용이하게 삽입될 수 있게 첨예하게 형성되는 것을 특징으로 하는,버섯 재배용 배지의 스마트 수분공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

677/1059 Row 677: application_number: 1020200151216, combined_string: invention_title: 식물 재배용 유리블럭 abstract: 본 발명은 식물 재배용 유리블럭에 관한 것으로, 보다 상세하게는, 채광이 어려운 실내에서 식물의 광합성을 유도하도록 인위적인 광을 제공하고, 동시에, 식물을 향해 적절한 바람을 제공하여 식물에서 방출되는 음이온, 피톤치드 등의 유효성분을 주변으로 비산시켜 실내 공기질을 개선할 수 있으며, 식물 자체가 바람에 흩날릴 수 있도록 해 식물의 생장 환경을 보다 자연환경에 가깝게 조성할 수 있어 식물의 성장을 보다 촉진시키고 올바른 성장을 유도할 수 있으며, 특히, 야간 시 뛰어난 시인성 확보와 함께 식물의 입체감 및 표현력을 증대시켜 미감 향상, 은은한 실내 분위기 조성 등 실내 인테리어 효과를 누릴 수 있도록 하는 식물 재배용 유리블럭에 관한 것이다. claims: 복수의 열과 행으로 적층 구성되어 벽체 구조물을 형성하는 식물 재배용 유리블럭에 있어서,투명 또는 반투명 유리재질의 사각 틀 형태로 이루어지며 전후 방향으로 거치공이 관통 형성되고, 거치공 주변으로는 서로 수직으로 접하는 4 개의 내벽이 형성되되, 상기 내벽은 각각 거치공의 상부를 구성하는 상벽, 거치공의 하부를 구성하는 하벽, 거치공의 좌우 측면을 구성하는 측벽으로 이루어지는 케이스;상기 거치공 내부에 거치되는 투명 또는 반투명 유리재질의 화분;상기 거치공의 내벽에 착탈 가능하게 설치되는 발광모듈;상기 거치공의 내벽에 착탈 가능하게 설치되는 팬모듈;상기 거치공의 내벽에 착탈 가능하게 설치되며 상기 발광모듈 및 팬모듈에 전원을 공급하는 배터리모듈; 및투명 또는 반투명 유리재질로 이루어지며 상기 케이스의 전면과 후면에 각각 좌우 방향으로 가로질러 장착되는 스트랩부;를 포함하며,상기 상벽, 하벽 및 측벽마다 발광모듈, 팬모듈 및 배터리모듈 중 적어도 어느 하나가 설치되는 장착홈이 함몰 형성되고, 각각의 장착홈과 상호 연결되어 장착홈과 함께 내벽 상에 하나의 채널을 구성하며 발광모듈, 팬모듈 및 배터리모듈로부터 연장 형성되는 전선을 수용하는 전선수용홈이 함몰 형성되며,상기 전선수용홈의 전후 폭은 장착홈의 전후 폭보다 좁게 형성되며,상기 팬모듈은 식물의 직상방에서 바람을 제공하도록 상벽에 형성된 장착홈에 설치되며,상기 케이스의 전면과 후면에는 스트랩부의 좌우 양단이 삽입 고정되는 고정구가 형성되며,상기 스트랩부는,하부에 배치된 다른 유리블럭에서부터 자라나는 넝쿨식물의 줄기가 유도되도록 중앙으로 갈수록 케이스에서 점진적으로 멀어지는 호 형태로 만곡되는 밴드부재; 및상기 밴드부재의 좌우 양단에서 하방으로 연장 형성되는 막대 형태로 이루어지며 상기 고정구에 상하로 슬라이딩하여 체결되는 체결부재;를 포함하며,상기 고정구는 케이스의 전면에 상하 방향으로 길게 연장되는 홈 형태의 고정홈 및 상기 고정홈의 전면 하단 일부를 폐쇄하는 고정판을 포함하며,고정홈에 삽입되는 체결부재는 고정판에 의해 하부로 가이드되어 고정홈의 하부에 끼움되는 것을 특징으로 하는 식물 재배용 유리블럭., Ltext: 농업, prediction: 농업
678/1059 Row 678: application_number: 1020200146580, combined_string: invention_title: 식물기반 바이오약품 제조를 위한 식물형질전환이 이루어진 기주식물의 재배방법 abstract: 본 발명의 식물기반 바이오약품 제조를 위한 식물형질전환이 이루어진 기주식물의 재배방법은 습도와 온도 및 이산화탄소의 농도가 조절된 제1 실내생육공간에서 양액과 인조광원을 이용하여 기주식물을 재배하는 기주식물 재배단계; 생산하고자 하는 유전자가 조합된 식물발현벡터를 기주식물로 운반할 아그로박테리움에 주입하는 유전자 운반 매개체 준비단계와, 상기 식물발현벡터가 포함된 상기 아그로박테리움을 함유하는 액상의 침윤액을 준비하는 침윤액 준비단계와; 재배된 기주식물의 잎을 포함한 줄기부를 상기 침윤조에 담그고, 뿌리를 포함한 배지가 진공분위기에 노출된 상태에서 침윤액 내의 상기 아그로박테리움이 상기 기주식물로 전달될 수 있도록 하는 침윤단계와; 상기 침윤이 이루어진 기주식물을 습도와 온도 및 이산화탄소의 농도가 조절된 제2 실내생육공간에서 양액과 인조광원을 이용하여 기주식물을 회복시키는 기주식물회복재배단계를 포함한다. claims: 습도와 온도 및 이산화탄소의 농도가 조절된 제1 실내생육공간에서 양액과 인조광원을 이용하여 기주식물을 재배하는 기주식물 재배단계: 생산하고자 하는 유전자가 조합된 식물발현벡터를 기주식물로 운반할 아그로박테리움에 주입하는 유전자 운반 매개체 준비단계와, 상기 식물발현벡터가 포함된 상기 아그로박테리움을 함유하는 액상의 침윤액을 준비하는 침윤액 준비단계와; 재배된 기주식물의 잎을 포함한 줄기부를 침윤조에 담그고, 뿌리를 포함한 배지가 진공분위기에 노출된 상태에서 침윤액 내의 상기 아그로박테리움이 상기 기주식물로 전달될 수 있도록 하는 침윤단계와;상기 침윤이 이루어진 기주식물을 습도와 온도 및 이산화탄소의 농도가 조절된 제2 실내생육공간에서 양액과 인조광원을 이용하여 기주식물을 회복시키는 기주식물회복재배단계를 포함하며,상기 침윤단계는상기 기주식물을 상기 침윤액에 침지시키기 전 기주식물을 진공분위기에 노출시키는 기주식물진공노출단계와,상기 기주식물을 상기 침윤액에 침지시키기 후 진공을 해지하여 기주식물에 압력이 작용하도록하는 기주식물가압단계를 구비한 것을 특징으로 하는 식물기반 바이오약품 제조를 위한 식물형질전환이 이루어진 기주식물의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

679/1059 Row 679: application_number: 1020200133095, combined_string: invention_title: 수경재배기 abstract: 본 발명은 수경재배기에 관한 것으로, 보다 상세하게는 양액의 수위를 실시간으로 모니터링할 수 있을 뿐만 아니라, 식물과 광조사부 사이의 거리를 일정하게 유지시킬 수 있는 수경재배기에 관한 것이다.본 발명에 따르면, 양액의 수위를 실시간으로 모니터링할 수 있기 때문에, 사용자의 편의성이 도모되고, 식물과 광조사부 사이의 거리가 일정하게 유지되기 때문에, 광조사부에서 발생되는 열로 인한 식물의 악영향을 미연에 방지할 수 있고, 사용자의 스마트기기(스마트폰, 태블릿 PC 등)와 양방향 통신을 통한 데이터의 송수신이 가능하도록 구성하여 실시간 업데이트가 반영되는 장점이 있다. claims: 사용자의 스마트기기와 양방향 통신이 가능하되, 물교체 잔여일자, 양액 추가공급 잔여일자, 물 및 양액의 수위정보, 광조사부(600) 및 펌프부(300) 동작상태를 포함한 데이터가 스마트기기로 송신되고, 재배된 식물(1) 정보, 광 조사시간, 현재 시각을 포함한 데이터가 스마트기기로부터 수신되는 수경재배기에 있어서,외형을 형성하고 내부를 구획하는 본체부(100);상기 본체부(100)의 상측에 결합되고, 식물(1)이 재배되는 재배포트(10)가 장착되는 덮개부(200);상기 본체부(100)의 내부에 형성되고, 상기 덮개부(200)에 장착된 재배포트(10)로 양액(m)을 공급하는 펌프부(300);상기 본체부(100)의 내부에 형성되고, 재배포트(10)를 통하여 빠져나온 양액(m')의 수위를 감지하는 수위감지부(400);상기 본체부(100)의 일측에 결합되고, 상하로 높이가 조절되는 높이조절부(500);상기 높이조절부(500)의 상측에 결합되고, 재배포트(10)에 재배된 식물(1)에 광을 조사하는 광조사부(600);재배포트(10)에 재배된 식물(1)이 광조사부(600)로부터 기설정된 거리(H) 이내에 접근시 접근을 감지하는 접근감지센서;상기 접근감지센서가 식물(1)을 감지시 식물(1)과 광조사부(600) 사이의 거리를 기설정된 거리(H)만큼 유지되도록 높이조절부(500)의 높이를 조절하는 제어부;를 포함하되,상기 재배포트(10)는하측에서 상측으로 갈수록 외경이 커지는 바스켓 형상을 가지고, 재배부(12)가 거치되는 거치부(11)와,상기 거치부(11)의 내부에 거치되고, 식물씨앗(1')이 수용되는 원기둥 형상의 재배부(12)와,상기 거치부(11)의 상단에서 반경방향 외측으로 돌출형성되는 돌출부(13)와,상기 돌출부(13)의 상측에 결합되는 커버부(14)를 포함하고,상기 거치부(11)는거치부(11)의 하측의 내경(L')이 재배부(12)의 외경(L)과 동일한 크기를 가지도록 형성된 것을 특징으로 하고,상기 거치부(11)는거치부(11)의 측부에 형성되어 양액유로부(222)를 따라 이동된 양액(m)이 재배부(12)로 유입되는 양액유입공(11a)과,거치부(11)의 하단에 형성되어 재배부(12)를 빠져나온 양액(m')이 본체부(100)의 내부로 배출되는 양액배출공(11b)을 포함하고,상기 재배부(12)는재배부(12)의 상단에 형성되고, 식물씨앗(1')이 수용되는 씨앗수용부(12a)를 포함하고,상기 덮개부(200)는덮개부(200)의 상측에 형성되는 상부덮개(210)와,상기 상부덮개(210)의 하측에 결합되는 하부덮개(220)를 포함하고,상기 상부덮개(210)는재배포트(10)의 거치부(11)가 삽입되는 제1포트삽입공(211)과,상기 제1포트삽입공(211)의 외주면에 단턱지게 형성되어 재배포트(10)의 돌출부(13)가 안착되는 단턱부(212)와,상기 단턱부(212)에 함몰형성되어 손가락이 인입되는 손가락인입부(213)를 포함하고,상기 하부덮개(220)는상기 제1포트삽입공(211)에 대응되는 위치에 형성되어 재배포트(10)의 거치부(11)가 삽입되는 제2포트삽입공(221)과,펌프부(300)에서 공급되는 양액(m)이 이동되고, 상기 제2포트삽입공(221)과 연통되는 양액유로부(222)를 포함하고,상기 수위감지부(400)는하측에 양액이동공(411)이 형성되어 양액(m')이 유입되고, 플로터(420)의 수직이동을 가이드하는 가이드부(410)와,상기 가이드부(410)의 내부에 형성되고, 상기 양액이동공(411)으로 유입된 양액(m')의 수위에 따른 부력에 의해 가이드부(410)의 내측면을 따라 승강 가능하게 구비되며, 자기장을 발생시키는 플로터(420)와,상기 가이드부(410)의 하부에 형성되고, 상기 플로터(420)로부터 발생된 자기장을 감지하는 수위센서(430)를 포함하고,상기 플로터(420)는플로터(420)의 하단에 형성되어 자기장을 발생시키는 자석부(421)를 포함하는 것을 특징으로 하는수경재배기., Ltext: 농업, prediction: 임업
680/1059 Row 680: application_number: 1020200133158, combined_string: invention_title: 분무식 수경 재배장치 abstract: 본 발명은 본체; 식재된 육묘 뿌리가 아래로 통과하는 다수개의 뿌리통과공이 형성된 재배대가 상기 본체에 상하로 다단 배치된 트레이부; 상기 본체에 설치되어 다단 배치된 상기 재배대의 하부에 각각 배치되며 상기 재배대에 식재된 육묘 뿌리로 양액을 분무하는 분무노즐을 포함하는 복수개의 양액분무부; 상하로 다단 배치된 상기 재배대의 상부에 각각 배치되어 상기 재배대에 식재된 육묘로 하나 이상의 파장을 갖는 광을 조사하는 조명장치를 포함하는 복수개의 조명장치부; 상기 재배대의 하부에 배치되는 각각의 양액분무부의 하부에 각각 설치되며, 상기 양액분무부로부터 분무된 양액을 회수하여 일측에서 타측으로 이동시키는 복수개의 방수패드를 포함하는 양액회수부; 및 다단 배치된 상기 복수개의 방수패드의 일측에 구비되며 상기 방수패드로 회수되는 양액에 의해 상기 방수패드에 이슬이 맺히는 것을 방지하는 복수개의 송풍부를 포함하되, 상기 복수개의 방수패드는 윗변과 아랫변이 서로 다른 길이를 가지는 사다리꼴 형상을 가지고, 상기 방수패드의 양측변을 각각의 양액분무부의 하부에 설치 시 상기 방수패드의 윗변과 아랫변의 높이가 달라지며, 윗변 보다 아래쪽에 위치하는 아랫변 측으로 양액이 이동하고, 상기 송풍부가 상기 방수패드에 이슬이 맺히는 것을 방지하여 상기 방수패드에 맺혀진 이슬에 의해 양액이 식물로 필요이상으로 공급되는 것을 방지하는 것을 특징으로 하는 분무식 수경 재배장치를 제공한다.따라서, 방수패드가 사다리꼴 형상을 가짐으로써 방수패드를 양액분무부의 하부에 설치 시 방수패드로 포집되는 양액을 별도의 이동수단을 이용하지 않고 중력을 이용하여 원하는 지점으로 원활하게 이동시킬 수 있고, 이동된 양액을 순환시킴으로써 양액의 낭비를 줄일 수 있다. claims: 본체;식재된 육묘 뿌리가 아래로 통과하는 다수개의 뿌리통과공이 형성된 재배대가 상기 본체에 상하로 다단 배치된 트레이부;상기 본체에 설치되어 다단 배치된 상기 재배대의 하부에 각각 배치되며 상기 재배대에 식재된 육묘 뿌리로 양액을 분무하는 분무노즐을 포함하는 복수개의 양액분무부;상하로 다단 배치된 상기 재배대의 상부에 각각 배치되어 상기 재배대에 식재된 육묘로 하나 이상의 파장을 갖는 광을 조사하는 조명장치를 포함하는 복수개의 조명장치부;상기 재배대의 하부에 배치되는 각각의 양액분무부의 하부에 각각 설치되며, 상기 양액분무부로부터 분무된 양액을 회수하여 일측에서 타측으로 이동시키는 복수개의 방수패드를 포함하는 양액회수부; 및다단 배치된 상기 복수개의 방수패드의 일측에 구비되며 상기 방수패드로 회수되는 양액에 의해 상기 방수패드에 이슬이 맺히는 것을 방지하는 복수개의 송풍부를 포함하되,상기 복수개의 방수패드는 윗변과 아랫변이 서로 다른 길이를 가지는 사다리꼴 형상을 가지고, 상기 방수패드의 양측변을 각각의 양액분무부의 하부에 설치 시 상기 방수패드의 윗변과 아랫변의 높이가 달라지며, 윗변 보다 아래쪽에 위치하는 아랫변 측으로 양액이 이동하고,상기 송풍부가 상기 방수패드에 이슬이 맺히는 것을 방지하여 상기 방수패드에 맺혀진 이슬에 의해 양액이 식물로 필요이상으로 공급되는 것을 방지하는 것을 특징으로 하는 분무식 수경 재배장치., Ltext: 농업, prediction: 임업

Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

681/1059 Row 681: application_number: 1020200133159, combined_string: invention_title: 재배용 포트 abstract: 본 발명은 상하가 개방되고, 높이방향의 축을 따라 아래로 갈수록 단면적이 줄어드는 테이퍼진 형상을 가지며, 장기성 작물의 뿌리가 결착된 인공배지가 삽입되고, 둘레면에는 복수개의 절개홈이 상하방향으로 형성되며 장기성 작물의 뿌리가 성장 시 외측으로 벌어지는 배지결합부; 및 상기 배지결합부의 상단에서 외측으로 수평되게 연장되어 재배베드의 구멍에 걸림고정되며, 상기 재배베드의 형성된 구멍의 빈공간으로 복사선이 통과하는 것을 차단하는 차단부를 포함하되, 상기 배지결합부는 상부단이 상기 차단부와 연결되는 전개 본체와, 상기 전개 본체의 하부단과 연결되며 상기 인공배지가 안착되는 안착 본체를 포함하며, 상기 안착 본체는 복수개의 상기 절개홈에 의해 인접하는 복수개의 안착편으로 구획되고, 상기 복수개의 안착편이 장기성 작물의 뿌리가 성장 시 외측으로 벌어지며, 상기 복수개의 절개홈은 상기 안착 본체를 상하로 절개한 후 상기 전개 본체의 하부단을 절개하고, 상기 안착 본체의 하부단에는 상기 인공배지가 안착되는 안착단이 내부로 돌출되게 구비되며, 상기 안착단에 상기 인공배지가 안착되어 상기 인공배지가 상기 안착 본체의 하부로 이탈되는 것이 방지되는 것을 특징으로 하는 재배용 포트를 제공한다.따라서, 장기성 작물의 뿌리가 수용되는 안착 본체가 뿌리의 성장에 대응하여 벌어지는 구조를 가짐으로써 뿌리의 커진 부위에 경맥경화 현상이 발생하여 뿌리가 썩게 되는 것을 방지할 수 있고, 장기성 작물을 양액재배가 아닌 수경으로도 재배가 가능하도록 한다. claims: 상하가 개방되고, 높이방향의 축을 따라 아래로 갈수록 단면적이 줄어드는 테이퍼진 형상을 가지며, 장기성 작물의 뿌리가 결착된 인공배지가 삽입되고, 둘레면에는 복수개의 절개홈이 상하방향으로 형성되며 장기성 작물의 뿌리가 성장 시 외측으로 벌어지는 배지결합부; 및상기 배지결합부의 상단에서 외측으로 수평되게 연장되어 재배베드의 구멍에 걸림고정되며, 상기 재배베드의 형성된 구멍의 빈공간으로 복사선이 통과하는 것을 차단하는 차단부를 포함하되,상기 배지결합부는,상부단이 상기 차단부와 연결되는 전개 본체와,상기 전개 본체의 하부단과 연결되며 상기 인공배지가 안착되는 안착 본체를 포함하며,상기 안착 본체는 복수개의 상기 절개홈에 의해 인접하는 복수개의 안착편으로 구획되고, 상기 복수개의 안착편이 장기성 작물의 뿌리가 성장 시 외측으로 벌어지며, 상기 복수개의 절개홈은 상기 안착 본체를 상하로 절개한 후 상기 전개 본체의 하부단을 절개하고,상기 안착 본체의 하부단에는 상기 인공배지가 안착되는 안착단이 내부로 돌출되게 구비되며,상기 안착단에 상기 인공배지가 안착되어 상기 인공배지가 상기 안착 본체의 하부로 이탈되는 것이 방지되는 것을 특징으로 하는 재배용 포트., Ltext: 농업, prediction: 임업
682/1059 Row 682: application_number: 1020200121174, combined_string: invention_title: 거치용 식물 재배 장치 abstract: 본 발명에 따른 거치 대상물의 외면에 거치될 수 있는 거치용 식물 재배 장치는, 거치 대상물의 외면을 따라 길이 조절 가능하게 형성되는 하우징 및 상기 하우징의 일측에 배치되는 식물이 식재되는 식재부로 구성된다. claims: 거치 대상물의 외면의 적어도 일부에 거치될 수 있는 거치용 식물 재배 장치로서,상기 거치 대상물의 외면을 따라 길이 조절 가능하게 형성되고, 사각형의 거치대상물에 거치될 수 있도록 적어도 한 부분이 'ㄱ'형상으로 절곡 형성되는 중공의 하우징; 및 식물이 상기 하우징의 내부에서 상기 하우징을 따라 생장가능하도록 상기 하우징의 일측에 배치되는 식재부;를 포함하는 거치용 식물 재배 장치.거치 대상물의 외면의 적어도 일부에 거치될 수 있는 거치용 식물 재배 장치로서,상기 거치 대상물의 외면을 따라 길이 조절 가능하게 형성되고, 사각형의 거치대상물에 거치될 수 있도록 형성되며 적어도 두 부분이 'ㄱ'형상으로 절곡 형성되는 중공의 하우징; 및 식물이 상기 하우징의 내부에서 상기 하우징을 따라 생장가능하도록 상기 하우징의 양 단에 배치되는 식재부;를 포함하는 거치용 식물 재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

683/1059 Row 683: application_number: 1020200111002, combined_string: invention_title: 떡차 및 그의 제조 방법 abstract: 본 발명은, 녹차 생엽을 숙성 발효하여 떡처럼 덩어리로 만드는 고형차인 떡차의 제조 방법에 관한 것으로, 녹차 생엽의 채엽 및 선별 단계와, 시들기 위조 단계와, 찌기 단계와, 성형 단계와, 1차 자연 건조 단계와, 황토방 발효 단계와, 2차 자연 건조 단계와, 저장 단계와, 화롯불에 굽는 단계를 포함한다. claims: (a) 녹차 생엽을 채엽하고 선별하는 단계와,(b) 선별된 녹차 생엽을 하룻밤 시들린 후, 찻잎의 막을 벗기는 단계와,(c) 막이 벗겨진 찻잎을 천에 싸서 수증기를 이용하여 찌는 단계와,(d) 쪄낸 찻잎에 감로잎을 혼합한 혼합물을 분쇄하여 차 덩어리로 한 후, 당해 차 덩어리를 떡차 틀을 이용하여 일정한 형태의 떡차로 성형하는 단계와,(e) 성형된 떡차를 하루동안 일광 건조하는 단계와,(f) 일광 건조된 떡차를 볏짚에 접촉시켜 황토방에서 발효시키는 단계와,(g) 황토방에서 발효된 떡차를 통풍이 용이하고 그늘진 곳에서 자연 건조하는 단계와,(h) 상기 자연 건조시킨 떡차를 차 단지에 넣고 한지로 봉하여 저장하는 단계를 포함하고,상기 (d) 단계에 있어서의 상기 혼합물은, 감로잎을 1중량％ 이상 5중량％ 미만으로 배합하고, 또한 죽염을 0.1중량％ 이상 0.5중량％ 미만으로 배합한 것을 특징으로 하는 떡차의 제조 방법.제1항에 기재된 제조 방법으로 제조된 떡차., Ltext: 농업, prediction: 임업
684/1059 Row 684: application_number: 1020210024308, combined_string: invention_title: 식물재배시스템의 지지플레이트 abstract: 본 발명은 재배 환경의 인공적인 제어에서 유지 전력이 감소되고 다품종의 식물 각각에 요구되는 재배 환경을 만족할 수 있는 식물재배시스템의 지지플레이트를 제공하기 위하여, 광을 조사하는 광원의 하측에서 화분을 지지하는 지지플레이트에 있어서, 적어도 하나의 상기 화분이 안착되는 플레이트 본체 및 상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함한다. claims: 광을 조사하는 광원의 하측에서 화분을 지지하는 지지플레이트에 있어서,적어도 하나의 상기 화분이 안착되는 플레이트 본체; 및상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함하는 지지플레이트.제1 항에 있어서,상기 지지플레이트는 온실 내부에 배치되고.상기 광원은 상기 지지플레이트의 상부에서 상기 온실 내부에 지지되는 것을 특징으로 하는 지지플레이트.제5 항에 있어서,상기 온실은상기 화분을 지지하고 있는 지지플레이트를 다층으로 지지하는 다층 생육구조물과,상기 생육구조물의 적어도 일부를 감싸도록 배치되어 상기 온실 내부의 온기 또는 냉기가 온실로부터 배출되는 것을 저지하는 외벽과,상기 온실 내부에 배치되어 상기 온실 내부의 환경을 제어하는 생육환경 유지장치를 포함하는 것을 특징으로 하는 지지플레이트., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

685/1059 Row 685: application_number: 1020210024309, combined_string: invention_title: 식물재배시스템의 온실 abstract: 본 발명은 재배 환경의 인공적인 제어에서 유지 전력이 감소되고 다품종의 식물 각각에 요구되는 재배 환경을 만족할 수 있는 식물재배시스템의 온실을 제공하기 위하여, 적어도 하나의 화분을 지지하는 지지플레이트 및 상기 지지플레이트를 지지하는 다층 생육구조물 및 상기 생육구조물의 적어도 일부를 감싸도록 배치되어 내부의 온기 또는 냉기가 외부로 배출되는 것을 저지하는 외벽 및 상기 지지플레이트 상부에 배치되어 광을 조사하는 광원을 포함하고, 상기 지지플레이트는 상기 화분이 안착되는 플레이트 본체와, 상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함한다. claims: 적어도 하나의 화분을 지지하는 지지플레이트;상기 지지플레이트를 지지하는 다층 생육구조물;상기 생육구조물의 적어도 일부를 감싸도록 배치되어 내부의 온기 또는 냉기가 외부로 배출되는 것을 저지하는 외벽; 및상기 지지플레이트 상부에 배치되어 광을 조사하는 광원을 포함하고,상기 지지플레이트는상기 화분이 안착되는 플레이트 본체와,상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함하는 온실.적어도 하나의 화분을 지지하는 지지플레이트;상기 지지플레이트를 지지하는 다층 생육구조물;상기 생육구조물의 적어도 일부를 감싸도록 배치되어 내부의 온기 또는 냉기가 외부로 배출되는 것을 저지하는 외벽; 및상기 지지플레이트 상부에 배치되어 광을 조사하는 광원을 포함하고,상기 지지플레이트는상기 화분이 안착되는 플레이트 본체와,상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함하는 생육장치., Ltext: 농업, prediction: 임업
686/1059 Row 686: application_number: 1020200185283, combined_string: invention_title: 특수목 재배용 가이드 케이싱 abstract: 본 발명은 특수목이나 정원수(庭園樹) 등으로 재배하는 식물의 줄기를 인위적인 굴절상태로 재배하기 위한 특수목 재배용 가이드 케이싱을 제공코자 하는 것이다.즉, 본 발명은 단면이 반원호 형태이며, 내부에는 굴곡진 유도로(2)가 형성되고, 양 끝단에는 상, 하부 개구부(4)(3)를 갖는 한 쌍의 통체(1)와; 고정클립(21)을 이용하여 분할된 통체(1)를 결속하기 위해 상기 통체(1)의 외측 끝단에 서로 마주보게 형성되는 복수개의 돌출편(5);을 포함하여, 재배식물(T)의 줄기전체를 내부 유도로(2)에 내장한 상태에서 생육재배가 이루어지게 함을 특징으로 한다. 상기 특수목 재배용 가이드 케이싱을 이용하면, 다양한 수형을 갖는 특수목을 신속하고 용이하게 양산 보급할 수 있다는 장점이 있다. claims: 단면이 반원호 형태이며, 내부에는 굴곡진 유도로(2)가 형성되고, 양 끝단에는 상, 하부 개구부(4)(3)를 갖는 한 쌍의 통체(1);고정클립(21)을 이용하여 분할된 통체(1)를 결속하기 위해 상기 통체(1)의 외측 끝단에 서로 마주보게 형성되는 복수개의 돌출편(5);을 포함하여, 재배식물(T)의 줄기전체를 내부 유도로(2)에 내장한 상태에서 생육재배가 이루어지게 하며, 상기 통체(1)는 불투명 합성수지제로 형성하고, 그 길이방향으로 이격되게 배치되는 보조통공(7)을 천공하며, 상기 보조통공(7)에는 온도, 습도, ph, 전기전도도 및 압력 중 어느 하나 이상의 정보를 검출하기 위한 센서를 결합하여 재배식물의 성장 상태를 원격 검출할 수 있도록 구성됨을 특징으로 하는 특수목 재배용 가이드 케이싱., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

687/1059 Row 687: application_number: 1020200129910, combined_string: invention_title: 원예용 친환경 해충 퇴치제의 제조방법 및 이에 의해 제조된 원예용 친환경 해충 퇴치제 abstract: 본 발명은 원예용 친환경 해충 퇴치제의 제조방법 및 이에 의해 제조된 원예용 친환경 해충 퇴치제에 관한 것이다.본 발명에 따른 재료들을 준비하는 천연 재료 준비 단계(S100); 상기 준비된 재료들을 혼합한 후 추출하여 천연 추출액을 제조하고, 상기 천연 추출액 제조시 분리된 고형분을 건조하고 분쇄하여 분말화함으로써 천연 분말을 제조하는 천연 추출액 및 천연 분말 제조 단계(S200); 상기 천연 추출액 및 천연 분말과 혼합되는 토양 개질제를 제조하는 토양 개질제 제조 단계(S300); 및 상기 천연 추출액, 천연 분말 및 토양 개질제를 혼합하여 해충 퇴치제를 제조하는 혼합 단계(S400)를 포함한다.상기한 구성에 의해 본 발명에 따른 원예용 친환경 해충 퇴치제의 제조방법은 인체에 해가 없으면서 해충 기피 효과가 우수하고 원예용 작물과 토양에 영양분을 공급함과 동시에 원예용 작물에 해충이 모이거나 번식하는 것을 방지할 수 있는 원예용 친환경 해충 퇴치제를 제조할 수 있다. claims: 재료들을 준비하는 천연 재료 준비 단계(S100);상기 준비된 재료들을 혼합한 후 추출하여 천연 추출액을 제조하고, 상기 천연 추출액 제조시 분리된 고형분을 건조하고 분쇄하여 분말화함으로써 천연 분말을 제조하는 천연 추출액 및 천연 분말 제조 단계(S200);상기 천연 추출액 및 천연 분말과 혼합되는 토양 개질제를 제조하는 토양 개질제 제조 단계(S300); 및상기 천연 추출액, 천연 분말 및 토양 개질제를 혼합하여 해충 퇴치제를 제조하는 혼합 단계(S400)를 포함하되,상기 천연 추출액 및 천연 분말 제조 단계(S200)에서 상기 준비된 재료들은 편백나무 5 내지 10 중량부, 자귀나무 3 내지 5 중량부, 어성초 2 내지 4 중량부, 박하 1 내지 3 중량부, 제충국 2 내지 4 중량부, 쿠아시아 1 내지 3 중량부, 은행나무 4 내지 6 중량부, 소태나무 0.5 내지 2.5 중량부 및 쇠비름 1 내지 3 중량부의 중량 비율로 혼합되고,상기 천연 추출액은,편백나무, 자귀나무, 어성초, 박하, 제충국, 쿠아시아, 은행나무, 소태나무 및 쇠비름으로 이루어진 재료들을 준비한 후 상기 재료들을 혼합하고, 상기 혼합된 재료들을 130 내지 160℃ 온도의 수증기로 50 내지 100분 동안 가열하여 증숙하며, 상기 증숙된 재료들을 60 내지 80mbar의 압력 및 60 내지 70℃의 온도에서 10 내지 30분 동안 2.0GHz의 마이크로웨이브를 조사함으로써 건조하고, 상기 건조된 재료들 100 중량부에 대해 발효 미생물 배양액 5 내지 10 중량부를 혼합한 후 38 내지 42℃의 온도에서 20 내지 40일 동안 발효를 진행하되, 상기 발효 미생물 배양액은, 세척된 볏짚을 물이 담긴 용기에 넣고 105 내지 110℃의 온도에서 30 내지 50분 동안 삶아 살균하고, 상기 삶아 살균한 후 용기에 남은 물과 볏짚을 자연 냉각하여 고초균 침출수를 얻으며, 상기 볏짚이 침지되어 있는 고초균 침출수를 65 내지 75℃의 온도로 5시간 동안 유지하여 고초균을 증식시키고, 상기 고초균이 증식된 고초균 침출수로부터 볏짚을 분리하여 제거하고, 상기 고초균 침출수만을 105 내지 110℃의 온도에서 30분 동안 삶아 살균한 후 냉각하는 과정을 거쳐 제조되며, 상기 발효된 재료들에서 상기 편백나무, 자귀나무, 어성초, 박하, 제충국, 쿠아시아, 은행나무, 소태나무 및 쇠비름으로 이루어진 재료들에서 생성된 고형분을 제거하여 발효 침출수를 분리하여 제조되고,상기 천연 분말은, 상기 분리된 고형분을 30 내지 40℃의 온도에서 3 내지 5일 동안 건조한 후 분쇄하여 분말화함으로써 제조되며,상기 토양 개질제 제조 단계(S300)에서 상기 토양 개질제는 패각분말 10 내지 20 중량부, 미세 다공체 5 내지 10 중량부, 인산칼륨(K3PO4) 2 내지 6 중량부, 탄산칼륨 3 내지 7 중량부, 마그네사이트 1 내지 5 중량부, 구연산 2 내지 6 중량부, 아인산 1 내지 3 중량부 및 인광석 5 내지 10 중량부의 중량 비율로 혼합한 후 교반하여 제조하며,상기 패각분말은,전복, 굴, 소라, 꼬막, 바지락, 석화 및 조개로 이루어진 군에서 선택된 어느 하나 이상의 패각을 준비한 후 세척하고, 상기 세척된 패각을 제1 분쇄하여 패각 분쇄물을 제조하며, 상기 패각 분쇄물을 10 내지 20분 동안 혼합액에 침지시키되, 상기 혼합액은 질산 0.5 내지 1.5 중량%, 인산염 화합물 1 내지 2 중량% 및 잔량의 정제수로 이루어지고, 상기 인산염 화합물로는 제1 인산나트륨(NaH2PO4), 제2 인산나트륨(Na2HPO4), 제3 인산나트륨(Na3PO4), 제1 인산칼륨(KH2PO4), 제2 인산칼륨(K2HPO4), 제1 인산암모늄((NH4)H2PO4), 제2 인산암모늄((NH4)2HPO4) 및 제3 인산암모늄((NH4)3PO4)으로 이루어진 군에서 선택되는 어느 하나 이상이 사용되며, 상기 패각 분쇄물을 혼합액에서 분리하여 꺼낸 후 상기 패각 분쇄물을 소성로에 투입한 후 1,400 내지 1,600℃의 온도에서 20 내지 60분 동안 가열함으로써 소성하고, 상기 소성된 패각 분쇄물을 입경이 1 내지 10mm가 되도록 제2 분쇄하는 과정을 거쳐 제조되며,상기 미세 다공체는,미연탄소분 10 내지 15 중량부, 플라이애쉬 8 내지 12 중량부, 황토 2 내지 4 중량부 및 준설토 3 내지 7 중량부의 중량 비율로 준비하여 혼합하고, 상기 미연탄소분, 플라이애쉬, 황토 및 준설토 전체 100 중량부에 대하여 물 30 내지 40 중량부의 중량 비율로 준비하며, 상기 미연탄소분, 플라이애쉬, 황토 및 준설토와 물을 혼합하여 혼합물을 제조한 후 성형하여 성형체를 형성하고, 상기 성형체를 가마에서 가열하여 소성하되, 상기 가마는 내부 온도를 400 내지 450℃의 온도로 유지하고, 상기 가마의 내부에 상기 성형체를 투입한 후 1200 내지 1300℃의 온도까지 높이면서 3 내지 5 시간 동안 소성하며, 상기 소성된 성형체를 가마로부터 꺼낸 후 200 내지 250℃의 온도에서 1 내지 3시간 동안 제1 냉각한 후, 30 내지 50℃의 온도에서 10 내지 12시간 동안 제2 냉각하는 과정을 거쳐 제조되고,상기 혼합 단계(S400)에서 상기 해충 퇴치제는 천연 추출액 10 내지 20 중량부, 천연 분말 5 내지 15 중량부 및 토양 개질제 20 내지 30 중량부의 중량 비율로 혼합되어 제조되는 것을 특징으로 하는 원예용 친환경 해충 퇴치제의 제조방법.제 1항의 방법으로 제조된 것을 특징으로 하는 원예용 친환경 해충 퇴치제., Ltext: 농업, prediction: 임업
688/1059 Row 688: application_number: 1020200120640, combined_string: invention_title: 연통홀이 형성된 단위 보호유닛을 포함하는 천연잔디 보호매트 abstract: 본 발명에 따른 연통홀이 형성된 단위 보호유닛을 포함하는 천연잔디 보호매트는, 천연잔디가 심어진 지면에 설치되어 천연잔디를 보호하는 천연잔디 보호매트에 있어서, 지면으로부터 소정 높이만큼 기립된 지지프레임을 포함하며, 상기 지지프레임의 내측에는 지면에 심어진 천연잔디가 통과하도록 상하 개구된 통과공간이 형성된 단위 보호유닛을 포함하고, 상기 지지프레임에는, 상기 통과공간과 상기 지지프레임의 외측을 서로 연통시키는 연통홀이 형성된다. claims: 천연잔디가 심어진 지면에 설치되어 천연잔디를 보호하는 천연잔디 보호매트로서,지면으로부터 소정 높이만큼 기립된 지지프레임을 포함하며, 상기 지지프레임의 내측에는 지면에 심어진 천연잔디가 통과하도록 상하 개구된 통과공간이 형성된 단위 보호유닛을 포함하되,상기 지지프레임에는상기 통과공간과 상기 지지프레임의 외측을 서로 연통시키는 연통홀이 상기 통과공간의 둘레를 따라 복수 개가 형성되되, 서로 인접한 한 쌍의 상기 연통홀 사이에는 지면에 접촉되는 기립부가 구비되고,천연잔디의 생육 환경을 향상시키기 위해, 상기 기립부의 내부에는 상기 통과공간으로부터 넘친 물 또는 공기가 유동되는 보조공간이 형성되고, 상기 기립부의 둘레에는 상기 보조공간과 상기 기립부의 외측을 서로 연통시켜 상기 보조공간 내의 물 또는 공기를 외측으로 배수하는 보조홀이 형성되는 것을 특징으로 하는,천연잔디 보호매트., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

689/1059 Row 689: application_number: 1020200090454, combined_string: invention_title: 생장점 배양을 이용한 사과 왜성대목 M.9 및 M.26의 바이러스 무병주 생산방법 abstract: 본 발명은 사과 왜성대목 품종인 M.9 또는 M.26의 액아(Axillary bud)로부터 생장점을 채취하고, 채취한 생장점을 BAP(6-benzylaminopurine), IBA(Indole-3-Butyric Acid), 글라이신(Glycine) 및 글루코오스(Glucose)를 포함하는 제1 MS(Murashige and Skoog basal) 배지에 치상하여 신초를 생육하는 단계; 상기 생육된 신초를 BAP, IBA, 글라이신 및 글루코오스를 포함하는 제2 MS 배지에서 배양하여 유식물체로 분화시키는 단계; 상기 유식물체를 IBA(Indole-3-Butyric Acid)를 포함하는 제3 MS 배지에서 배양하여 발근을 유도하는 단계; 및 상기 발근이 유도된 유식물체를 기외순화시키는 단계; 를 포함하는 사과 왜성대목 품종인 M.9 또는 M.26의 바이러스 무병주 생산 방법에 관한 것으로, 본 발명의 생장점배양방법을 이용한 사과 왜성대목 M.9 및 M.26 품종 무독묘 생산방법은 각 배양 단계에 적합한 배지 및 배양 조건을 이용함으로써, 기본 배지에서 배양하는 경우보다 신초 형성율, 신초 생장, 발근율이 우수하고 낮은 갈변율을 보이므로, 본 발명의 무독묘 생산 방법은 사과 왜성대목의 기내 대량증식에 유용하게 사용될 수 있다. claims: 사과 왜성대목 품종인 M.9 또는 M.26의 액아(Axillary bud)로부터 생장점을 채취하고, 채취한 생장점을 BAP(6-benzylamino purine) 0.8 내지 1.2 mg/L, IBA(indole-3-butyric acid) 0.1 내지 0.5 mg/L, 글라이신(Glycine) 2 내지 6 mg/L 및 글루코오스(Glucose) 25 내지 35 g/L를 포함하는 제1 MS(Murashige and Skoog basal) 배지에 치상하여 신초를 생육하는 단계;상기 생육된 신초를 BAP, IBA, 글라이신 및 글루코오스를 포함하는 제2 MS 배지에서 배양하여 유식물체로 분화시키는 단계;상기 유식물체를 IBA(Indole-3-Butyric Acid)를 포함하는 제3 MS 배지에서 배양하여 발근을 유도하는 단계; 및상기 발근이 유도된 유식물체를 기외순화시키는 단계; 를 포함하는 사과 왜성대목 생산방법., Ltext: 농업, prediction: 임업
690/1059 Row 690: application_number: 1020200082779, combined_string: invention_title: 제설제로부터 화단을 보호하는 장치 abstract: 본 발명은 도로에 인접한 화단 전방에 설치되어 겨울철에 염화캄슐과 같은 제설제가 화단으로 침투하는 것을 방지하는, 제설제로부터 화단을 보호하는 장치에 관한 것이다. 본 발명은 제설제가 화단으로 침투하는 것을 차단하는 복수 개의 차단벽부(10); 상기 복수 개의 차단벽부 사이에 설치되는 복수 개의 롤부(20)로서, 각기 개구(21)를 통해 상기 차단벽부의 일단부가 삽입되어 탄력적으로 권회되도록 구성되며, 상기 개구와 반대측에는 상기 차단벽부의 타단부가 고정되며, 중심에는 관통구멍이 형성된 복수 개의 롤부(20); 상기 롤부의 관통구멍을 통과하고 있고, 하단부는 지면에 박혀 빠져나오기 어려운 형상을 가진 지면 고정체(30); 및 상기 지면 고정체의 하단으로부터 위로 설정된 길이만큼 이격되어 상기 지면 고정체에 대해 직교하는 방향으로 관통하여 배치되어서, 상기 지면 고정체가 상기 롤부로부터 분리되는 것을 방지하는 분리 방지대(33);를 포함한다. claims: 제설제가 화단으로 침투하는 것을 차단하는 복수 개의 차단벽부(10)로서, 기온, 습도 및 적설량을 감지하여 관리자 단말에 제공하는 기온 센서, 습도 센서 및 적설량 센서가 설치되어 있는 복수 개의 차단벽부;상기 복수 개의 차단벽부 사이에 설치되는 복수 개의 롤부(20)로서, 각기 개구(21)를 통해 상기 차단벽부의 일단부가 삽입되어 탄력적으로 권회되도록 구성되며, 상기 개구와 반대측에는 상기 차단벽부의 타단부가 고정되며, 중심에는 관통구멍이 형성된 복수 개의 롤부(20);상기 롤부의 관통구멍을 통과하고 있고, 하단부는 지면에 박혀 빠져나오기 어려운 형상을 가진 지면 고정체(30); 및상기 지면 고정체의 하단으로부터 위로 설정된 길이만큼 이격되어 상기 지면 고정체에 대해 직교하는 방향으로 관통하여 배치되어서, 상기 지면 고정체가 상기 롤부로부터 분리되는 것을 방지하는 분리 방지대(33);를 포함하는, 제설제로부터 화단을 보호하는 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

691/1059 Row 691: application_number: 1020200075948, combined_string: invention_title: 인조잔디식재 및 조립이 용이한 잔디보호매트 abstract: 본 발명은 인조잔디식재 및 조립이 용이한 잔디보호매트에 관한 것이다. 본 발명의 일실시 예에 따른 인조잔디식재 및 조립이 용이한 잔디보호매트는 상면에 인조잔디가 구비되는 인조잔디용 체결유닛 및 이를 잔디보호매트에 조립하기 위한 홀더를 포함함으로써, 천연잔디의 발육에 도움을 주는 인조잔디를 잔디보호매트에 쉽게 식재 가능하다. 따라서 잔디보호와 관련된 잔디보호매트의 신뢰도를 효과적으로 높일 수 있다. claims: 사각형의 외곽프레임을 통해 형성되는 내부공간에 배열된 수직지지기둥;상기 외곽프레임과 각각의 수직지지기둥을 선택적으로 연결하는 외곽연결리브;상기 각각의 수직지지기둥의 중단을 선택적으로 서로 연결할 수 있도록 각각의 수직지지기둥을 중심으로 수평방향으로 형성된 내부연결리브; 및상기 각각의 수직지지기둥의 하단을 선택적으로 서로 연결할 수 있도록 각각의 수직지지기둥의 하단을 중심으로 수평방향으로 형성된 하부구조체;를 포함하며,각각의 상기 하부구조체가 서로 교차하는 중심부에 선택적으로 형성된 링형의 펙고정유닛;상기 펙고정유닛에 상부에서 하부방향으로 체결되어 지면에 삽입되는 유동방지용 펙;상기 각각의 수직지지기둥의 둘레에 선택적으로 돌출 형성된 제1 돌출부, 상기 제1 돌출부와의 사이에 삽입공간이 형성되도록 제1 돌출부와 이격 배치된 제2 돌출부 및 상기 제1,2 돌출부의 상단에 돌출 형성되어 서로 마주보게 배치된 고리부로 구성된 홀더; 및상기 홀더를 통해 내부공간의 상부에 길이방향으로 조립되며, 상면에 인조잔디가 구비되는 인조잔디용 체결유닛;을 더 포함하는 인조잔디식재 및 조립이 용이한 잔디보호매트., Ltext: 농업, prediction: 임업
692/1059 Row 692: application_number: 1020200052338, combined_string: invention_title: 고설재배용 포트 및 이를 이용한 고설재배 베드 abstract: 본 발명은 사각판 형태의 방수성 경질 플레이트, 상기 플레이트 상면에 부분적으로 만입되고 하부로 길게 연장되어 작물 재배용 공간을 제공하도록 배치되는 복수의 재배공, 복수의 재배공 사이의 플레이트 상면에 일방향으로 길게 형성된 관수로, 플레이트 측방 끝단에 형성된 고정 고리를 포함하며, 재배공의 깊이를 다르게 하여 재배공의 하부면들에 의해 이루어지는 포트 하부 구조가 측면에서 볼 때 반원 또는 호형인 곡면 구조를 이루는 것을 특징으로 하는 고설재배용 포트를 제공하며, 또한 이 포트를 이용하며 지지 구조물과 천막지 배수라인을 더 포함하는 고설재배 베드를 제공한다. claims: 사각판 형태의 방수성 경질 플레이트,상기 플레이트 상면에 부분적으로 만입되고 하부로 길게 연장되어 작물 재배용 공간을 제공하도록 배치되는 복수의 재배공,복수의 재배공 사이의 플레이트 상면에 일방향으로 길게 형성된 관수로, 플레이트 측방 끝단에 형성된 고정 고리를 포함하며, 재배공의 깊이를 다르게 하여 재배공의 하부면들에 의해 이루어지는 포트 하부 구조가 측면에서 볼 때 반원 또는 호형인 곡면 구조를 이루며,상기 복수의 재배공은 상기 플레이트의 전후 방향 및 좌우방향으로 종횡 배열되고 동일한 종적 배열에서는 동일한 깊이를 갖고, 중앙으로부터 각각 좌우측으로 갈수록 재배공의 깊이가 줄어드는 구조로 형성되고,상기 복수의 재배공은 중앙부의 재배공 평면 면적보다 좌우측의 재배공의 평면 면적이 더 크게 형성되는 것을 특징으로 하는 고설재배용 포트.지면 위에 수평적으로 배치되고, 상호 소정 간격으로 평행하게 이격되어 있는 한 쌍의 제1파이프,상기 한 쌍의 제1파이프 하부에서 각각 제1파이프를 수직 방향으로 지지하는 적어도 한 쌍의 제2파이프,상기 한 쌍의 제1파이프 상면에 일부가 걸쳐진 채로 중앙 하부는 한 쌍의 제1파이프 사이 공간에 제1파이프 높이보다 하방으로 반원 또는 호형을 이루도록 늘어지게 배치되어 고설재배 베드의 배수로로 기능하는 천막지, 및상기 천막지 위에 배치되며, 제1파이프에 양단이 걸친 채로 지면으로부터 이격되어 배치되는 작물 재배용 포트를 포함하며,상기 작물 재배용 포트는 토양과 작물이 삽입되는 복수의 재배공과 재배공 사이에 형성되어 재배공으로 물을 공급하는 관수로를 포함하고, 포트 하부면은 중앙에서 죄우 측부로 갈수록 재배공의 깊이가 줄어드는 곡면 구조로 형성되고,상기 복수의 재배공은 플레이트의 전후 방향 및 좌우방향으로 종횡 배열되고 동일한 종적 배열에서는 동일한 깊이를 갖고, 중앙으로부터 각각 좌우측으로 갈수록 재배공의 깊이가 줄어드는 구조로 형성되고,상기 복수의 재배공은 중앙부의 재배공 평면 면적보다 좌우측의 재배공의 평면 면적이 더 크게 형성되는 것을 특징으로 하는고설재배 베드., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

693/1059 Row 693: application_number: 1020207031220, combined_string: invention_title: 공기 흡입식 마늘 배향 배종 장치 abstract: 본 발명은 농업 기계 기술 분야에 관한 것으로, 더욱 상세하게는 공기 흡입식 마늘 배향 배종 장치에 관한 것이며, 여기에는 종자실 하우징, 종자 흡입실 하우징, 종자 흡착판, 밀봉 링, 배향 탄성편, 내부 배향 핀, 외부 배향 핀, 이미지 수집기, 회전 배향 장치, 이미지 식별 제어 유닛, 전동축 및 전동 스프로킷이 포함되고, 종자실 하우징은 종자 흡입실 하우징과 고정 연결되고, 종자 흡착판은 종자실 하우징과 종자 흡입실 하우징 사이에 배치되고, 종자 흡착판과 종자 흡입실 하우징 사이에 밀봉 링이 설치되고, 종자 흡입실 하우징 상에는 흡입관이 설치되고, 종자 흡착판은 원주를 따라 균일하게 복수의 종자 흡입 통공이 설치되고, 종자 흡착판의 배향 영역에서 각 종자 흡입 통공 중심원 시계 반대 방향을 따라 순차적으로 배향 탄성편, 내부 배향 핀, 외부 배향 핀, 이미지 수집기 및 회전 배향 장치가 배치되고, 전동축 일단은 종자 흡착판 중심에 고정 연결되고, 타단은 전동 스프로킷에 고정 연결되고, 중간은 베어링을 거쳐 종자 흡입실 하우징 상에서 지탱된다. 본 발명은 마늘 종자의 단립 배향 배종을 구현할 수 있다. claims: 공기 흡입식 마늘 배향 배종 장치에 있어서, 종자실 하우징(1), 종자 흡입실 하우징(2), 종자 흡착판(3), 밀봉 링(4), 배향 탄성편(7), 내부 배향 핀(8), 외부 배향 핀(9), 이미지 수집기(10), 회전 배향 장치, 이미지 식별 제어 유닛, 전동축(5) 및 전동 스프로킷(6)을 포함하고, 종자실 하우징(1)은 종자 흡입실 하우징(2)과 고정 연결되고, 종자 흡착판(3)은 종자실 하우징(1)과 종자 흡입실 하우징(2) 사이에 배치되고, 종자 흡착판(3)과 종자 흡입실 하우징(2) 사이에 밀봉 링(4)이 설치되고, 밀봉 링(4), 종자 흡착판(3), 종자 흡입실 하우징(2)은 종자 흡입실(11)을 둘러싸고, 종자 흡입실 하우징(2) 상에는 흡입관(13)이 설치되고, 흡입관(13)은 종자 흡입실(11)과 연통하고, 종자 흡착판(3)과 종자실 하우징(1)은 종자실(12)을 둘러싸고, 종자실 하우징(1) 상단에 개구가 설치되고, 종자 흡착판(3)은 원주를 따라 균일하게 복수의 원형 통공이 설치되고, 각 원형 통공 내에는 조합 흡입 블록이 설치되고, 조합 흡입 블록은 원형 통공 갭에 매칭되고, 조합 흡입 블록 중심에는 종자 흡입 통공이 설치되고, 대응하는 종자 흡착판(3)의 비스듬한 상방은 각 종자 흡입 통공 중심원을 따라 반시계 방향으로 배향 탄성편(7), 내부 배향 핀(8), 외부 배향 핀(9), 이미지 수집기(10) 및 회전 배향 장치가 순차적으로 배치되고, 배향 탄성편(7), 내부 배향 핀(8), 외부 배향 핀(9), 이미지 수집기(10)가 종자실 하우징(1) 상에 고정되고, 회전 배향 장치는 종자 흡착판(3)의 타측에서 종자 흡입실 하우징(2) 상에 고정되고, 배향 탄성편(7), 이미지 수집기(10) 및 회전 배향 장치의 중심은 종자 흡입 통공 중심원에 대응하고, 내부 배향 핀(8), 외부 배향 핀(9)은 각각 종자 흡입 통공 중심원의 내측과 외측에 위치하고, 전동축(5) 일단은 종자 흡착판(3) 중심에 고정 연결되고, 타단은 전동 스프로킷(6)에 고정 연결되고, 중간은 베어링을 거쳐 종자 흡입실 하우징(2) 상에서 지탱되는 것을 특징으로 하는 공기 흡입식 마늘 배향 배종 장치., Ltext: 농업, prediction: 임업
694/1059 Row 694: application_number: 1020200041696, combined_string: invention_title: 인조잔디식재 및 조립구조가 개선된 잔디보호매트 abstract: 본 발명은 인조잔디식재 및 조립구조가 개선된 잔디보호매트에 관한 것이다. 본 발명의 일실시 예에 따른 인조잔디식재 및 조립구조가 개선된 잔디보호매트는 천연잔디의 발육에 도움을 주는 인조잔디를 잔디보호매트에 용이하게 식재 가능할 뿐만 아니라 서로 이웃하는 복수의 잔디보호매트를 용이하게 조립할 수 있도록 조립구조를 볼 방식으로 개선함으로써, 숙련자는 물론이고, 초보자도 골프장이나 녹색주차장 또는 공원 등에 잔디보호매트를 쉽게 설치할 수 있다. 따라서 천연잔디를 보호하기 위한 잔디보호매트의 보급률에 크게 기여할 수 있다. claims: 사각형의 외곽프레임;상기 외곽프레임을 통해 형성된 내부공간에 배열된 수직지지기둥;각각의 상기 수직지지기둥과 외곽프레임을 연결하는 외곽연결프레임; 및각각의 상기 수직지지기둥을 중심으로 수평방향으로 형성되는 내부연결프레임;을 포함하며,각각의 상기 내부연결프레임의 상부에 돌출 형성된 제1 돌출부 및 상기 제1 돌출부와의 사이에 삽입공간이 형성되도록 제1 돌출부와 이격 배치된 제2 돌출부로 구성된 홀더; 및상기 홀더를 통해 내부공간의 상부에 길이방향으로 조립되며, 상면에 인조잔디가 식재된 인조잔디용 체결유닛;을 더 포함하는 인조잔디식재 및 조립구조가 개선된 잔디보호매트., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

695/1059 Row 695: application_number: 1020200033640, combined_string: invention_title: 다중의 천연잔디 구장을 분할하여 집중 관제할 수 있는 잔디 관리 시스템 및 방법 abstract: 본 발명의 일 실시예에 따른 잔디 관리 시스템은, 잔디가 마련된 지역에 설치되며, 잔디 상태를 체크하기 위한 다수의 센서와 연결되어 센싱정보를 수집하고, 밸브를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 적어도 하나의 컨트롤러; 상기 컨트롤러와 연결되어 수집된 센싱정보를 전송받아 모니터링하고, 센싱정보를 토대로 상기 컨트롤러 및 밸브를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 중앙관제서버;를 포함할 수 있다. claims: 잔디 관리 시스템에 있어서, 잔디가 마련된 지역에 설치되며, 잔디 상태를 체크하기 위한 다수의 센서와 연결되어 센싱정보를 수집하고, 밸브를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 적어도 하나의 컨트롤러;상기 컨트롤러와 연결되어 수집된 센싱정보를 전송받아 모니터링하고, 센싱정보를 토대로 상기 컨트롤러 및 밸브를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 중앙관제서버;를 포함하되,상기 센서는잔디의 온습도 상태를 확인하기 위하여 잔디가 위치한 지중에 구비된 온습도센서, 강우량을 체크하기 위한 강우센서, 대기센서, 미세먼지센서, 풍향/풍속센서, 낙뢰센서 및 일사량센서를 포함하며,상기 잔디 관리 시스템은,상기 컨트롤러와 연결되어 기상 관측 정보를 체크하기 위해 마련되며, 상기 대기센서, 미세먼지센서, 온습도센서, 강우량센서, 풍향/풍속센서, 낙뢰센서, 일사량센서로부터 센싱정보를 제공받아 기상 관측 정보를 생성하고, 상기 중앙관제서버에 기상 관측 정보를 전송하거나 잔디 주변에 설치된 대형 화면 패널을 통하여 표시하는 기상관측부를 더 포함하며,상기 중앙관제서버는상기 센싱정보를 수집하여 데이터베이스에 저장하여 관리하거나 센싱정보 또는 기상 관측 정보를 로컬 지역에 전송하거나, 스프링클러의 제어신호를 전송하는 역할을 수행하는 관리부;상기 센서의 오차나 오작동에 대한 예측모델을 생성하는 예측부;상기 예측모델을 이용하여 예측 결과를 산출하고, 예측 결과를 토대로 센서의 예측된 허용 오차 범위 내에서 컨트롤러를 통하여 스프링클러의 온/오프 또는 분사량을 제어할 수 있도록 하는 분석부;상기 센싱정보 및 예측결과를 이용하여 학습을 수행하고, 반복된 학습을 통하여 센서의 오차 또는 오작동에 대한 예측모델을 업그레이드하는 학습부를 더 포함하며,상기 분석부는 서포트 벡터 머신을 기반으로 한 예측모델로 예측을 수행하되, 입력변수의 초기값으로 센서의 출하시 제공되는 모델정보를 토대로 설정된 오차 또는 오작동 범위를 입력변수로 하여 예측을 수행하며,상기 중앙관제서버는로컬서버 또는 관리단말에 각각 신분 증명이 가능한, 식별 정보(identification information)를 부여하여, 각 로컬서버 또는 관리단말의 식별 정보를 사설 암호 키(private key)로 활용하는 경량 암호 알고리즘을 수행하여, 상기 로컬서버, 관리단말 및 중앙관제서버 간의 주고받는 센싱정보에 대한 암/복호화를 하며,상기 경량 암호 알고리즘은 상기 관리단말의 환경에서 구현하기 위해 설계된 암호 기술이고, 대칭키 암호 알고리즘인 HIGHT(HIGh security and liht weigHT), LEA(Lightweight Encryption)와 해시함수인 LSH(Lightweight Secure Hash)를 활용하여 암/복호화하는 것을 특징으로 하는 잔디 관리 시스템.잔디 관리 시스템을 이용한 잔디 관리 방법에 있어서,상기 잔디 관리 시스템은 잔디가 마련된 지역에 설치되며 잔디 상태를 체크하기 위한 다수의 센서와 연결된 컨트롤러를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 중앙관제서버에서 상기 센서로부터 센싱정보를 수집하는 단계;상기 중앙관제서버는 상기 센싱정보를 입력변수로 인공지능 기반의 예측모델을 생성하는 단계;상기 중앙관제서버는 상기 예측모델을 이용하여 상기 센서의 오차 또는 오작동 여부를 판단하기 위한 예측을 수행하여, 예측 결과를 산출하는 단계;상기 중앙관제서버는 상기 예측 결과를 토대로 상기 센서의 예측된 허용 오차 범위 내에서 상기 컨트롤러를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 단계;상기 중앙관제서버는 수집된 센싱정보 및 예측 결과를 예측모델 학습을 위한 빅데이터로 활용하기 위해 데이터베이스에 저장하는 단계;를 포함하되,상기 센서는잔디의 온습도 상태를 확인하기 위하여 잔디가 위치한 지중에 구비된 온습도센서, 강우량을 체크하기 위한 강우센서, 대기센서, 미세먼지센서, 풍향/풍속센서, 낙뢰센서 및 일사량센서를 포함하며,상기 잔디 관리 시스템은,상기 컨트롤러와 연결되어 기상 관측 정보를 체크하기 위해 마련되며, 상기 대기센서, 미세먼지센서, 온습도센서, 강우량센서, 풍향/풍속센서, 낙뢰센서, 일사량센서로부터 센싱정보를 제공받아 기상 관측 정보를 생성하고, 상기 중앙관제서버에 기상 관측 정보를 전송하거나 잔디 주변에 설치된 대형 화면 패널을 통하여 표시하는 기상관측부를 더 포함하며,상기 중앙관제서버는상기 센싱정보를 수집하여 데이터베이스에 저장하여 관리하거나 센싱정보 또는 기상 관측 정보를 로컬 지역에 전송하거나, 스프링클러의 제어신호를 전송하는 역할을 수행하는 관리부;상기 센서의 오차나 오작동에 대한 예측모델을 생성하는 예측부;상기 예측모델을 이용하여 예측 결과를 산출하고, 예측 결과를 토대로 센서의 예측된 허용 오차 범위 내에서 컨트롤러를 통하여 스프링클러의 온/오프 또는 분사량을 제어할 수 있도록 하는 분석부;상기 센싱정보 및 예측결과를 이용하여 학습을 수행하고, 반복된 학습을 통하여 센서의 오차 또는 오작동에 대한 예측모델을 업그레이드하는 학습부를 더 포함하며,상기 분석부는 서포트 벡터 머신을 기반으로 한 예측모델로 예측을 수행하되, 입력변수의 초기값으로 센서의 출하시 제공되는 모델정보를 토대로 설정된 오차 또는 오작동 범위를 입력변수로 하여 예측을 수행하며,상기 중앙관제서버는로컬서버 또는 관리단말에 각각 신분 증명이 가능한, 식별 정보(identification information)를 부여하여, 각 로컬서버 또는 관리단말의 식별 정보를 사설 암호 키(private key)로 활용하는 경량 암호 알고리즘을 수행하여, 상기 로컬서버, 관리단말 및 중앙관제서버 간의 주고받는 센싱정보에 대한 암/복호화를 하며,상기 경량 암호 알고리즘은 상기 관리단말의 환경에서 구현하기 위해 설계된 암호 기술이고, 대칭키 암호 알고리즘인 HIGHT(HIGh security and liht weigHT), LEA(Lightweight Encryption)와 해시함수인 LSH(Lightweight Secure Hash)를 활용하여 암/복호화하는 것을 특징으로 하는 잔디 관리 방법., Ltext: 농업, prediction: 임업
696/1059 Row 696: application_number: 1020200029687, combined_string: invention_title: 파종기 abstract: 본 발명은 파종기에 관한 것이다.구성에 있어서, 파이프 형태로 됨과 동시에 종자통의 작용을 하도록 구성된 지주관의 소정위치에 종자공급장치를 장착하고, 그 하부에 작동부와 파종부, 그리고 파종홈의 깊이를 조절할 수 있는 스토퍼부로 이루어진 파종홈 성형장치를 구성하여, 상기 작동부의 하단 베이스를 지면에 대고 손잡이로 누르면 파종부가 하강하면서 오물어진 상태로 지면에 들어가게 되어 자연스럽게 소정깊이의 파종홈을 형성하면서 동시에 종자공급장치도 연동하여 파종부 내부로 종자를 공급할 수 있게 하고, 파종기를 드는 순간 작동부의 복원력에 의해 자연적으로 파종부가 개방되면서 파종부 안으로 낙하된 종자를 파종홈으로 투입할 수 있게 구성함을 특징으로 한다.따라서 본 발명은 각종 종자 파종시 보다 정확하면서도 확실한 파종이 이루어질 수 있으며,구성이 지극히 간단하고 제작이 손쉬워 농가에 저렴하게 공급할 수 있으면서 사용이 편리한 효과가 있다. claims: 상단에 뚜껑(11)과 손잡이(12)가 구비된 파이프 형태로 된 원통형의 종자통(1),상기 종자통(1)의 하부에 장착되며 90°~ 180°로 회전하면서 종자통(1) 내부의 종자를 일정량, 또는 소정 개수만 파종부(2)로 회전 이송시켜 낙하시키는 종자공급장치(6),상기 종자공급장치(6)가 종자를 파종부(2) 안으로 떨어뜨릴 때 통로로 작용하는 지지관(8),상기 지지관(8)의 하부에 장착되어 경운된 지면에 대고 누르면 파종홈(5)을 형성함과 동시에 상기한 종자공급장치(6)를 연동시켜 종자를 파종홈(5)으로 투입시키는 파종홈 성형장치(234)로 이루어진 파종기에 있어서,상기 종자공급장치(6)는상하부에 투입부(60a)와 배출부(60b)가 각각 구비되고 상기 투입부(60a)와 배출부(60b) 사이에 횡방향으로 드럼삽입부(60c)를 형성한 본체(6a)와,상기 드럼삽입부(60c)에 삽입되고, 외주면 상부에 종자홈(67')을 가진 가이드블록(67)를 끼울 수 있도록 가이드 끼움홈(61)이 구비되며, 일 측면에는 피니언(63)이 형성되고, 타 측면에는 본체(6a) 외부에서 측면고정판(66)을 대고 볼트(65)로 체결 조립하여서 된 드럼(6b),그리고 상기 피니언(63)에 치합되어 파종기(100)를 지면에 대고 누를 때 파종부(2)가 파종홈(5)을 형성함과 동시에 드럼(6b)도 회전하여 자동파종이 이루어질 수 있게 한 회전유도부(7)를 포함한 구성으로 이루어지되,상기 회전유도부(7)는 피니언(63)에 치합되는 랙기어(L)와, 상기 랙기어(L) 하부에 길게 연장형성된 연장부(L1), 그리고 상기 연장부(L1)가 지지대(34)를 관통한 뒤 압축스프링(LS)을 개재시키도록 된 스프링받침부(L2)로 이루어지고, 상기 연장부(L1) 하단은 파종부(2)의 승강거리와 드럼(6b)의 회전각도를 감안하여 베이스(31)로부터 소정의 높이만큼 높여 설치 구성함을 특징으로 하는 파종기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

697/1059 Row 697: application_number: 1020200025163, combined_string: invention_title: 식물재배용 조명기구 abstract: 본 발명에 따른 식물재배용 조명기구는 몸체부의 구성이 복잡하지 않고, 제조단가를 낮출 수 있고, 몸체부를 만드는데 필요한 금형의 개수를 줄일 수 있다. 상기 식물재배용 조명기구는 몸체부, 몸체부 내의 장착부에 장착되는 복수의 엘이디 모듈을 가지며, 상기 몸체부는, 바닥부 및 상기 바닥부의 양측 가장자리의 벽부를 가지는 복수의 단위 프레임이 연결수단을 통해 측방으로 서로 연결되되, 이웃하여 배치된 복수의 상기 엘이디 모듈은 상방을 향해 예각으로 꺾이도록 배치된 것을 포함하는 구성을 한다. claims: 제1장착부, 상기 제1장착부의 일측에 형성되는 제2장착부 및 상기 제2장착부의 반대편에 형성되는 제3장착부를 구비하는 몸체부;상기 제1장착부에 장착되어 하방을 향해 제1색깔의 광을 발하는 제1엘이디 모듈;상기 제1엘이디 모듈에 대해 상방을 향해 예각으로 꺾인 상태로 상기 제2장착부에 장착되어 일부만 상기 제1색깔의 광과 중첩되도록 제2색깔의 광을 발하는 제2엘이디 모듈;상기 제1엘이디 모듈에 대해 상방을 향해 예각으로 꺾인 상태로 상기 제3장착부에 장착되어 일부만 상기 제1색깔의 광과 중첩되도록 제3색깔의 광을 발하는 제3엘이디 모듈; 및상기 몸체부에 결합되어 상기 제1엘이디 모듈 내지 제3엘이디 모듈을 보호하는 윈도우를 포함하고,상기 몸체부는,바닥부와 상기 바닥부의 양측 가장자리에서 하방으로 돌출되어 상기 바닥부와 함께 하방으로 개구가 형성된 채널을 형성하며 내면에 상기 제1장착부 내지 상기 제3장착부 중 어느 하나가 형성되는 한 쌍의 벽부를 포함하고, 상기 한 쌍의 벽부의 외면은 상방으로 갈수록 서로 점점 가까워지도록 경사지게 형성되고, 양측 가장자리 상측부에 형성되는 축공을 가지는 회동연결부를 구비하는 단위 프레임 3개가 상기 축공에 결합되는 축을 통해 상호 회동 가능하게 측방으로 연결되어 구성되고,양단이 양측 가장자리의 상기 단위 프레임의 바깥쪽의 상기 벽부에 각각 결합되고 상기 몸체부에 간격을 두고 결합되는 적어도 한 쌍의 결합구;적어도 한 쌍의 상기 결합구의 중앙부에 각각 연결되어 상기 몸체부를 수평 상태로 유지하다가 승강시키기 위한 승강수단; 및상기 축과 적어도 한 쌍의 상기 결합구 사이 또는 양측 가장자리의 상기 단위 프레임의 사이에 설치되어 이웃하는 상기 단위 프레임 간에 꺾임각도를 조절할 수 있도록 하기 위한 각도조절구를 더 포함하고,상기 각도조절구는,ⅰ) 양측 가장자리의 상기 단위 프레임이 상기 축을 중심으로 일정 이상 상방으로 회동되지 않게 상기 축을 상방으로 당겨줄 수 있도록 상기 축에 연결된 축연결부 및 상기 축연결부와 결합되고 상기 결합구의 임의의 위치에 고정될 수 있는 고정구를 구비하여 구성된 것; 및ⅱ) 양측 가장자리의 상기 단위 프레임 사이를 지지하여 양측 가장자리의 상기 단위 프레임이 상기 축을 중심으로 일정 이상 상방으로 회동되지 않도록 하는 회동방지 바를 구비하여 구성된 것; 중 어느 하나를 포함하는 것을 특징으로 하는 식물재배용 조명기구., Ltext: 농업, prediction: 임업
698/1059 Row 698: application_number: 1020200015527, combined_string: invention_title: LED를 이용한 새싹삼의 재배 또는 사포닌 함량 증진 방법 abstract: 본 발명은 LED를 이용한 새싹삼의 재배 또는 사포닌 함량 증진 방법에 관한 것이다. 구체적으로, 본 발명에 따른 새싹삼 재배 방법은 새싹삼의 지상부 및 지하부의 생체중 및 엽면적, 지상부의 길이 증가, 지상부 및 지하부의 건물중 증가, 및 엽록소 함량 증가를 촉진할뿐만 아니라, 새싹삼에 포함되는 사포닌 함량을 유의적으로 증가시키므로, 새싹삼을 재배하거나 새싹삼에 포함된 사포닌의 함량을 증진시키는데 유용하게 사용될 수 있다. claims: 광원으로 적색 및 녹색 LED(light emitting diode)를 7:1 내지 9.5:1의 비율로 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 배양방법.광원으로 적색 및 녹색 LED를 7:1 내지 9.5:1의 비율로 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 사포닌 함량 증진방법.광원으로 근적외선을 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 배양방법.광원으로 근적외선을 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 사포닌 함량 증진방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

699/1059 Row 699: application_number: 1020200009991, combined_string: invention_title: 친환경 물공급 기능을 구비한 화단 abstract: 본 발명은 친환경 물공급 기능을 구비한 화단에 관한 것으로, 더욱 상세하게는 사용자가 휴식을 취할 수 있고 태양광패널(221)이 설치된 접이용 의자를 구비하고 접이용 의자의 회전에 의해 물이 펌핑되어 화단에 자동으로 공급할 수 있으며 태양광패널(221)을 통해 생산된 전력은 조명으로 사용될 수 있고, 내부에 단열재(111b)와 부직포(111a)가 다층 구조로 배치되어 물탱크(120)의 물을 화단에 공급할 수 있고 여름철의 습윤 비산 방지와 겨울철의 동해 방지 효과가 있는 친환경 물공급 기능을 구비한 화단에 관한 것이다.이를 위해 본 발명은, 식물이 식재되는 화분틀(110)과, 상기 화분틀(110)의 하단에 설치되는 물탱크(120)와, 상기 물탱크(120)에 저수된 물을 상기 식물 주변으로 공급하도록 상기 물탱크(120)에 장착되어 상기 화분틀(110) 내부로 연장되는 물공급부(130)를 포함하는 화분(100); 상기 화분틀(110)의 외면에 장착되는 의자틀(210)과, 저면이 상향 경사진 상태에서 상면이 수평인 상태로 회전되도록 상기 의자틀(210)에 장착되고 회전에 의해 상기 물공급부(130)를 펌핑하는 의자밑판(220)과, 태양광 발전을 위하여 상기 의자밑판(220)의 저면에 장착되는 태양광패널(221)을 포함하는 의자부(200);를 포함하여 이루어진다. claims: 식물이 식재되는 화분틀(110)과, 상기 화분틀(110)의 하단에 설치되는 물탱크(120)와, 상기 물탱크(120)에 저수된 물을 상기 식물 주변으로 공급하도록 상기 물탱크(120)에 장착되어 상기 화분틀(110) 내부로 연장되는 물공급부(130)를 포함하는 화분(100);상기 화분틀(110)의 외면에 장착되는 의자틀(210)과, 저면이 상향 경사진 상태에서 상면이 수평인 상태로 회전되도록 상기 의자틀(210)에 장착되고 회전에 의해 상기 물공급부(130)를 펌핑하는 의자밑판(220)과, 태양광 발전을 위하여 상기 의자밑판(220)의 저면에 장착되는 태양광패널(221)을 포함하는 의자부(200);를 포함하고,상기 물공급부(130)는,유입구(136)를 통해 물을 공급받는 실린더(131)와, 일단이 상기 화분틀(110) 내의 토양에 설치되고 타단이 상기 실린더(131)에 형성된 배출구(137)에 연결되는 공급호스(132)와, 일단이 상기 의자밑판(220)의 회전축에 결합되는 연결부(133)와, 상기 연결부(133)의 타단에 결합되고 상기 실린더(131) 안에서 왕복 운동하며 상기 의자밑판(220)의 회전에 의해 상기 실린더(131)에 공급된 물을 일측으로 밀어 상기 공급호스(132)로 배출하는 피스톤(134)과, 상기 피스톤(134)이 초기 위치로 복원되도록 상기 피스톤(134)을 타측으로 밀어줄 수 있는 스프링(135)을 포함하며,상기 의자틀(210)의 내측면에는, 상기 태양광패널(221)이 상면을 향한 상태에서 상기 의자밑판(220)의 회전을 제한하는 돌출부(212)가 더 구비되는 것을 특징으로 하는 친환경 물공급 기능을 구비한 화단., Ltext: 농업, prediction: 임업
700/1059 Row 700: application_number: 1020200004636, combined_string: invention_title: 잔디 식재방법 abstract: 본 발명은 잔디 식재방법에 관한 것으로서, 식재에 적합한 잔디를 선별한 후 세척하고, 천연살균제를 이용하여 살균하는 잔디 전처리단계와, 식재지에 포함된 잡석 및 불순물을 제거한 후, 식재지의 사면을 정리하는 식재지 정리단계와, 상기 잔디 전처리단계에서 전처리된 잔디를 상기 식재지 정리단계에서 정리된 식재지에 산포하는 잔디 산포단계와, 상기 산포된 잔디를 덮도록 상기 식재지에 전체적으로 네트를 설치하는 네트 설치단계와, 상기 네트를 덮도록 상기 식재지에 기능성 상토를 뿌려서 투입하는 기능성 상토 투입단계 및 상기 뿌려진 기능성 상토와 상기 산포된 잔디를 일정하게 다져주는 롤링단계를 포함하여 이루어진 것을 특징으로 한다.본 발명에 따르면, 식재를 위한 최상의 상태를 갖는 잔디 및 식재지를 제공함에 따라 빠른 시간 안에 균질한 잔디 활착을 유도하고, 가장 손쉽고 빠르게 시공할 수 있는 효과가 있다. 또한, 골프장, 각종 경기장, 공원, 조경지, 학교, 유치원, 어린이집 등에 적용하기 위하여 인체에 유해한 소독제, 살균제 대신에, 자체적으로 제조한 천연살균제, 토양개량제, 기능성 상토 등을 최적의 비율로 혼합하여 유해독성이 전혀 없으며, 잔디의 안정적인 활착 및 생육을 촉진시킬 수 있는 효과가 있다. claims: 식재에 적합한 잔디(10)를 선별한 후 세척하고, 천연살균제를 이용하여 살균하는 잔디 전처리단계(S10);식재지(20)에 포함된 잡석 및 불순물을 제거한 후, 식재지(20)의 사면을 정리하는 식재지 정리단계(S20);상기 잔디 전처리단계(S10)에서 전처리된 잔디를 상기 식재지 정리단계(S20)에서 정리된 식재지(20)에 산포하는 잔디 산포단계(S30);상기 산포된 잔디(10)를 덮도록 상기 식재지(20)에 전체적으로 네트(30)를 설치하는 네트 설치단계(S40);상기 네트(30)를 덮도록 상기 식재지(20)에 기능성 상토(40)를 뿌려서 투입하는 기능성 상토 투입단계(S50); 및상기 뿌려진 기능성 상토(40)와 상기 산포된 잔디(10)를 일정하게 다져주는 롤링단계(S60); 를 포함하여 이루어진 것을 특징으로 하는 잔디 식재방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

701/1059 Row 701: application_number: 1020200000666, combined_string: invention_title: 저울형 화분받침대 및 화분 abstract: 저울형 화분받침대 및 화분을 개시한다.개시된 저울형 화분받침대 및 화분은, 화분의 화초에 대한 급수시기를 화분의 토양 수분 변화 에 따른 중량 감소의 표시로 알 수 있게 하여, 급수시기를 빠르고, 정확하게 알려주면서 화분 받침대로 사용할 수 있게 하고, 화초에 대한 급수가 일정 기일 동안 유지될 수 있게 한다. claims: 상,하부 케이스가 분리되게 결합되어 상부로는 화초가 식재된 화분을 올려 놓을수 있는 화분 재치부를 제공하고, 또한 내부로는 소정 넓이의 공간을 제공하는 소정 형태의 본체;상기 공간에 내장되어 상기 재치부에 올려지는 상기 화분의 토양에 함유된 수분의 변화에 따른 상기 화분의 중량변화를 측정할 수 있게 하는 전자저울 혹은 스프링 저울; 및상기 본체의 어느 일측에 외부로 노출되게 설치되어 상기 전자 저울 혹은 스프링 저울로부터 측정된 상기 화분의 중량 변화를 화분 사용자들이 알 수 있게 표시하여, 화분 사용자들로 하여금 상기 화분의 중량 변화 표시에 따라 화분에 급수 여부를 실행하게 하는 화분중량 알림 표시부;를 포함하는 저울형 화분받침대.내외부용기로 이루어지며 하부에는 내부용기 측으로 급수되는 물이 배수공을 통하여 배출되어 저장될 수 있는 저수공간을 형성하는 화분 본체; 상기 내부용기의 개구부에 상기 하부용기의 개구부보다 더 크게 형성되어 상기 내부용기가 상기 하부용기에 걸리는 상태로 결합되게 하여 상기 내외부용기의 하부측 사이에 저수공간을 형성할 수 있게 하는 환형턱부; 및상기 내부용기의 중앙에 설치된 흡수공을 구비하고, 상기 외부용기의 내저부에 돌출 설치된 환형돌출턱의 환형홈에 수용된 상태로 지지되면서 상기 흡수공을 통해 상기 내부용기의 내부로 돌출 설치됨에 의해 상기 저수공간으로부터 상기 흡수공을 통하여 상기 내부용기에 위치되게 하는 흡수천을 고정 지지하는 고정 유지구로 이루어진 흡수부;를 포함하는 화분., Ltext: 농업, prediction: 임업
702/1059 Row 702: application_number: 1020200000264, combined_string: invention_title: 바코드로 식물의 정보 관리가 관리되는 무인원격 식물재배 시스템 abstract: 본 발명에 따른 바코드로 식물의 정보 관리가 관리되는 무인원격 식물재배 시스템는, 체인을 타고 승강되는 다수의 식물재배대가 설치된 식물재배장치와, 각 식물재배대에서 현재 재배하고 있는 식물의 종류, 파종일자, 이식일자, 생산자, 관리자, 높이 등 식물에 관련된 정보를 제목과 함께 날짜, 숫자, 문자, 영상, 이미지 등으로 저장하여 재배 중인 식물 정보를 총괄하여 관리할 수 있게 되고, 식물 정보가 저장되는 온라인 서버인 정보 관리서버와 바코드 또는 QR코드를 생성하고 이미지로 출력하는 바코드 발급부와 상기 바코드 또는 QR코드를 적외선 또는 카메라로 리딩하여 식물 정보에 접속할 수 있도록 하는 바코드 리더부와 식물 정보를 화면으로 표시해주는 식물 정보 표시부를 제공하여서 바코드 또는 QR코드를 이용하여 식물 정보에 사용자가 매우 용이하게 접근할 수 있으며, 사용자가 편리하게 식물 정보를 입력, 수정, 삭제, 열람하는 것이 가능하고, 물과 필요한 영양소를 식물재배대에 공급하는 물영양소공급부와, 식물재배대의 온도 및 습도를 측정하는 측정센서부와, 식물의 생장에 바람직한 온도와 습도를 공급하는 식물재배하우스을 포함하여서 식물을 사람의 노동력으로 재배하지 않고 무인원격으로 재배할 수 있다. claims: 바코드로 식물의 이력 등 정보 관리가 가능한 무인원격 식물재배 시스템(A)에 있어서,상기 바코드로 식물의 이력 등 정보 관리가 가능한 무인원격 식물재배 시스템(A)은, 식물재배장치(1)와, 식물관리장치(2)를 포함하고,상기 식물재배장치(1)는, 바닥에는 한쌍의 수직프레임(10)이 소정 간격을 두고 서로 대칭되게 수직으로 설치되고, 상기 수직프레임(10) 사이의 일단부에 회전 가능하게 구동축(21)이 설치되고, 상기 수직프레임(10) 사이의 타단부에 회전 가능하게 종동축(22)이 설치되고, 상기 수직프레임(10)의 외측에는 외측 프레임(11)이 설치되어 식물재배장치(1)의 전체를 지지하고,상기 구동축(21)과 종동축(22)은 이송체인(30)으로 연결되고,상기 이송체인(30)상에 다수의 식물재배대(50)가 설치되고,상기 식물재배대(50)는 상기 이송체인(30)상에 고정수단(40)에 의하여 고정되고,상기 고정수단(40)은 상기 이송체인(30)에 다수의 식물재배대(50)가 일정간격으로 다단으로 설치되고, 상기 식물재배대(50)는 이송체인(30)의 회전에 의해 승,하강 되게 구동되고, 상기 식물재배대(50)의 상기 고정수단(40)에 힌지고정된 힌지축(42)의 단부면에는 바코드 또는 QR코드(51)가 게시되고,상기 고정수단(4)은, 이송체인(30)의 2개 지점에서 힌지고정된 2개의 링크판(41)과, 상기 2개의 링크판(41)이 외측으로 1개의 지점에서 합류되어 힌지부를 이루는 힌지축(42)과, 상기 힌지축(42)의 외측으로 힌지고정되며 연장된 연장부(43)와, 상기 연장부(43)의 단부에 회전되게 고정된 회전롤러(44)와, 상기 회전롤러(44)가 내부에 삽입되어 회전되며 이동이 안내되는 안내홈레일(45)을 포함하고, 상기 안내홈레일(45)은 만곡안내홈판(45a)과 수직안내홈판(45b)으로 구성되고, 상기 고정수단(4)의 힌지축(42)에는 식물재배대(5)가 고정되어 있는 것을 특징으로 하는 바코드로 식물의 이력 등 정보 관리가 가능한 무인원격 식물재배 시스템, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

703/1059 Row 703: application_number: 1020190178893, combined_string: invention_title: 저칼륨 채소 재배를 위한 수경재배장치 abstract: 본 발명은 LED 램프가 설치된 상부 프레임; 상기 상부 프레임의 하측에 배치되되, 상면이 개방된 하부 프레임; 및 상기 하부 프레임의 상부에 배치되되, 식물이 안착될 수 있는 재배홀이 형성된 안착 플레이트;를 포함하되, 상기 하부 프레임에는, 칼륨이 포함된 양액이 수용되는 제1 수용공간과, 상기 제1 수용공간과 분리되어, 칼륨이 포함되지 않은 양액이 수용되는 제2 수용공간이 형성되는 저칼륨 채소 재배를 위한 수경재배장치를 제공할 수 있다. claims: LED 램프가 설치된 상부 프레임;상기 상부 프레임의 하측에 배치되되, 상면이 개방된 하부 프레임; 및상기 하부 프레임의 상부에 배치되되, 식물이 안착될 수 있는 재배홀이 형성된 안착 플레이트;를 포함하되,상기 하부 프레임에는,칼륨이 포함된 양액이 수용되는 제1 수용공간과,상기 제1 수용공간과 분리되어, 칼륨이 포함되지 않은 양액이 수용되는 제2 수용공간이 형성되는 저칼륨 채소 재배를 위한 수경재배장치., Ltext: 농업, prediction: 임업
704/1059 Row 704: application_number: 1020190178137, combined_string: invention_title: LED 식물재배장치 abstract: 본 발명은 직사광선을 이용하지 않고 LED광원을 통해 식물을 재배 하는 장치에 관한 것으로 LED조명 하부에 있는 식물이 균일한 광량을 조사받음으로써, 식물이 균등하게 생산되어 생산 식물의 전반적인 품질 균일성을 높일 수 있는 효과를 달성할 수 있다. claims: 식물이 재배되는 재배베드;PCB 기판과 상기 PCB 기판에 설치된 복수의 LED 소자를 구비하며, 상기 재배베드 상부에서 상기 재배베드를 향해 광을 조사하는 LED 모듈을 포함하고,상기 복수의 LED 소자에 있어서 소자 사이의 간격은 상기 PCB 기판의 중앙부보다 가장자리에서 더 좁은 것을 특징으로 하는 LED 식물재배장치.식물이 재배되는 재배베드;PCB 기판과 상기 PCB 기판에 설치된 복수의 LED 소자를 구비하며, 상기 재배베드 상부에서 상기 재배베드를 향해 광을 조사하는 LED 모듈을 포함하고,상기 LED 소자는 상기 PCB 기판의 중앙부보다 가장자리에서 광량이 더 큰 것을 특징으로 하는 LED 식물재배장치.식물이 재배되는 재배베드;PCB 기판과 상기 PCB 기판에 설치된 복수의 LED 소자를 구비하며, 상기 재배베드 상부에서 상기 재배베드를 향해 광을 조사하는 LED 모듈을 포함하고,상기 LED 소자는 상기 LED 모듈로부터 이격된 설정 거리에서 단위 면적당 조사되는 광량이 중앙부와 가장자리에서 균일하도록 구비된 것을 특징으로 하는 LED 식물재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

705/1059 Row 705: application_number: 1020200179541, combined_string: invention_title: 농업배수의 비점오염원 저감을 위한 관리 시스템 abstract: 본 발명은 농업배수 수위 상태에 따라 물꼬 장치를 제어하기 위해 사물인터넷과 결합하여 모니터링하며, 물꼬 장치를 실시간 원격으로 제어함으로써, 농업배수의 비점오염이 저감되는 비점오염원 원격 관리 시스템에 관한 것이다. claims: 자동 또는 원격으로 농업배수의 비점오염원 배출이 기계식 또는 전기식 중 어느 하나의 방식으로 구동 제어되는 물꼬 장치(10);수위 변화를 검출하기 위해 내부에 상한 수위 센서선과 하한 수위 센서선이 분리된 2선식 검출센서가 포함되어 수위가 측정되는 측정 장치(20);물꼬 장치(10), 측정 장치(20), 서버(40) 및 단말기(50) 간의 통신을 하도록 하는 통신망(30);통신망(30)을 통하여 물꼬 장치(10), 측정 장치(20) 또는 단말기(50) 중 선택되는 어느 하나 이상으로부터 정보를 제공받아 확인, 비교 또는 저장하거나, 자동 제어 정보를 생성하는 서버(40); 및통신망(30)을 통하여 서버(40)로부터 정보를 제공받아 원격 제어 정보를 생성하여 서버(40)로 제공하는 단말기(50);를 포함하며,물꼬 장치(10)는 농업배수를 외부로 배출하거나, 배출을 막기 위한 수로부(120)가 탈착되기 위해 오목한 홈으로 형성된 제1공간부(111)와, 로프(130)가 걸림 고정 되기 위한 고정부재(112), 및 로프(130)가 연결된 수로부(120)의 열림과 닫힘을 제어하는 구동부(140)가 형성되기 위한 제2공간부(113)가 포함되어 논둑에 고정되는 고정부(110);제1공간부(111)에 탈착되어 비관개기에 분리되어 별도로 보관이 가능하며, 구동부(140)에 의해 로프(130)가 당겨지거나 풀려짐에 따라, 가동부(121)가 접히거나 펼쳐져지는 수로부(120); 고정부재(112)에 고정 및 가동부(121)에 관통되고, 구동부(140)에 결합되어 구동부(140)에 의해 당겨지거나, 풀어지는 로프(130); 제2공간부(113)에 배치되어 연결된 로프(130)의 당김과 풀림을 조절하여 가동부(121)를 접거나, 펼쳐 농업배수의 배출 상태를 조절하는 구동부(140);농업배수에 포함된 토사가 유출되는 것을 방지하기 위해 미로와 같은 형상으로 형성되되, 고정부(110)가 맞닿는 면에 유입구(151)가 형성되고, 유입구(151)와 반대되는 면에 배출구(152)가 형성되는 토사유출방지부(150); 및 농업배수에 포함된 비점오염원이 여과 및 흡착되기 위해 토사유출방지부(150)의 수로 부분에 배치되는 여과재(160);를 포함하고,통신망(30)은 사용자가 현장 방문 없이 원격으로 물꼬 장치(10)를 제어하기 위해 LoRa(Long Range modulation technique)가 사용되고,측정 장치(20)에 의해 측정된 수위 변화에 따라 통신망(30)을 통해 서버(40) 또는 단말기(50)로부터 실시간으로 자동 또는 원격으로 물꼬 장치(10)의 열림과 닫힘을 제어하여 농업배수의 비점오염원 배출을 저감시키는 것을 특징으로 하는, 농업배수의 비점오염원 저감을 위한 관리 시스템., Ltext: 농업, prediction: 농업
706/1059 Row 706: application_number: 1020200162170, combined_string: invention_title: 식물의 생장 촉진 기능의 스마트팜 양액 제어 시스템 abstract: 본 발명은 식물의 생장 촉진 기능을 구비한 스마트팜 양액 제어 시스템에 관한 것이다. 보다 구체적으로는, 양액을 수용하여 식물을 재배하는 재배수조(20); 원수를 공급받아 저장하는 원수조(12); 상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14); 상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15); 상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);를 포함하고, 상기 재배수조(20)는, 상부에 위치하여 식물 생장을 촉진하는 파장대의 빛을 발산하는 LED 조명(21)와, 하부에 위치하여 원적외선을 방출하는 바이오 블록(22)을 더 포함할 수 있다. claims: 양액을 수용하여 식물을 재배하는 재배수조(20);원수를 공급받아 저장하는 원수조(12);상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14);상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15);상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);를 포함하고상기 재배수조(20)는,상부에 위치하여 식물 생장을 촉진하는 파장대의 빛을 발산하는 LED 조명(21)와, 하부에 위치하여 원적외선을 방출하는 바이오 블록(22)을 더 포함하는 것을 특징으로 하는 식물의 생장 촉진 기능의 스마트팜 양액 제어 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

707/1059 Row 707: application_number: 1020200162172, combined_string: invention_title: 스마트팜 양액 공급 장치 abstract: 본 발명은 스마트팜 양액 공급 장치에 관한 것이다. 보다 구체적으로는, 양액을 수용하여 식물을 재배하는 재배수조(20); 원수를 공급받아 저장하는 원수조(12); 상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14); 상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15); 상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16); 상기 재배수조(20)내의 식물의 영상을 획득하는 영상 촬영 장치(23); 및 상기 획득된 영상을 기반으로 상기 LED 조명(21)을 제어하는 조명 제어부(33)를 포함한다. claims: 양액을 수용하여 식물을 재배하는 재배수조(20);원수를 공급받아 저장하는 원수조(12);상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14);상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15);상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);를 포함하는 스마트팜 양액 공급 장치, Ltext: 농업, prediction: 농업
708/1059 Row 708: application_number: 1020200162173, combined_string: invention_title: 생육 주기별 양액 농도 제어가 가능한 스마트팜 제어 시스템 abstract: 본 발명은 식물의 생장 촉진 기능을 구비한 생육 주기별 양액 농도 제어가 가능한 스마트팜 제어 시스템에 관한 것이다. 보다 구체적으로는, 양액을 수용하여 식물을 재배하는 재배수조(20); 원수를 공급받아 저장하는 원수조(12); 상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14); 상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15); 상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16); 상기 재배수조(20)내의 식물의 영상을 획득하는 영상 촬영 장치(23); 및 상기 획득된 영상을 기반으로 상기 LED 조명(21)을 제어하는 조명 제어부(33)를 포함한다. claims: 상부에 위치되는 LED 조명(21)을 통해 식물 생장을 촉진하는 파장대의 빛을 발산하며, 식물 재배를 위한 양액을 수용하는 재배수조(20);원수를 공급받아 저장하는 원수조(12);상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14);상기 양액조(14)에 식물 영양제를 공급하는 영양제 공급부(17);상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15);상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);상기 원수조(12)에서 상기 양액조(14)로 공급되는 원수의 양을 조절하는 원수 공급 펌프 밸브(13); 상기 원수 공급 펌프 밸브(13)를 제어하는 밸브 제어기(31); 및 식물의 생육 주기에 따른 양액의 농도, 필요 영양제의 양, 생육 주기별 식물 사진을 저장하고, 저장 정보에 따라 상기 밸브 제어기(31) 및 상기 영양제 공급부(17)를 수시 제어하는 서버(32);를 포함하는 생육 주기별 양액 농도 제어가 가능한 스마트팜 제어 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

709/1059 Row 709: application_number: 1020200110421, combined_string: invention_title: 농약 정보 알리미 시스템 및 그 방법 abstract: 본 발명은 농약허용물질목록관리제도(Positive List System, PLS)를 대비하여 적용대상 약제정보 및 방제정보, 필수표시사항 및 농약과 관련한 종합정보 제공용 스마트시스템을 개발하여 고령 농업인들이 보다 쉽게 접근이 용이한 정보를 전달하고, 보다 안전하고 스마트한 국내 농업환경을 구축할 수 있도록 구현한 농약 정보 알리미 시스템 및 방법에 관한 것으로, 농약 판매 매장에 배치되며, 농약정보, 병해충방제정보, 농약혼용정보 및 농약 종류별 가격정보 중 적어도 하나 이상의 정보검색의 요청을 사용자로부터 입력받아 정보검색을 요청하며, 정보검색 요청에 대응하여 수신되는 검색결과를 표시하며, 사용자로부터 검색결과에 대한 프린트 요청이 있는 경우 해당 검색결과를 프린트하여 사용자에게 제공하는 정보 제공 키오스크 단말기; 및 상기 정보 제공 키오스크 단말기로부터 수신되는 정보검색 요청에 대응하는 정보를 데이터베이스에서 검색하며, 검색된 검색결과를 상기 정보 제공 키오스크 단말기로 전송하는 농약 정보 제공 서버;를 포함한다. claims: 농약허용물질목록관리제도(Positive List System, PLS)를 대비하여 적용대상 약제정보 및 방제정보, 필수표시사항 및 농약과 관련한 종합 정보를 제공하기 위한 농약 정보 알리미 시스템에 있어서,별도의 데이터베이스와 백업서버에 연결되는 농약 정보 제공 서버;농약 판매 매장에 배치되며 농약정보, 병해충방제정보, 농약혼용정보 및 농약 종류별 가격정보 중 적어도 하나 이상의 정보검색의 요청을 사용자로부터 입력받아 정보검색을 요청하며, 정보검색 요청에 대응하여 수신되는 검색결과를 표시하고, 사용자로부터 검색결과에 대한 프린트 요청이 있는 경우 해당 검색결과를 프린트하여 사용자에게 제공하는 정보 제공 키오스크 단말기;를 포함하되, 상기 정보 제공 키오스크 단말기는 키오스크 본체, 상기 키오스크 본체의 전단에 설치되며 농약정보 검색창, 병해충방제정보 검색창, 농약혼용정보 검색창 및 농약 종류별 가격정보를 표시하며,상기 농약 정보 제공 서버로부터 수신되는 검색결과를 표시하는 터치 스크린, 상기 터치 스크린은 화면 상단에 농약 제품 광고 및 공익 광고 영역을 표시하고, 화면 중단에 농약정보 검색, 병충해 방제정보 검색 및 농약 혼용정보 검색 메뉴 영역을 표시하고,상시적 농약 제품의 가격 정보 영역의 하단에 농약 종류별 가격정보 검색 및 가나다순 초성검색 영역을 더 표시하며,상기 농약정보 검색은 사용자로부터 검색창을 통해 농약 제품의 명칭을 직접 입력받거나 상시적 농약 제품의 가격 정보 영역에 나열된 농약 제품 리스트 중에서 선택 입력받아 상기 농약 정보 제공 서버로 해당 농약 제품의 정보 검색을 요청한 뒤, 상기 농약 정보 제공 서버로부터 수신되는 농약정보 상세 내용 구성을 표시하고,상기 농약정보 상세 내용 구성은 적용대상 및 사용량, 해당제품 혼용정보 및 필수표시사항을 포함하며, 필수표시사항은 주요 특성, 주의사항, 경고문구, 해독 및 응급처치요령 및 취급제한기준을 포함하며,상기 농약정보 검색, 농약 혼용정보 검색, 병충해 방제정보 검색 메뉴 영역은 작물명과 해충명의 입력창 하단에 국가농작물 병해충관리시스템에서 제공하는 월별 농작물 병해충 발생정보를 표시하기 위한 이달의 병충해정보를 표시하고,상기 농약 정보 제공 서버는 각 매장에 설치되어 있는 상기 정보 제공 키오스크 단말기의 관리자에게 해당 매장에 비치되어 있는 농약의 가격 및 종류에 따라 상기 정보 제공 키오스크 단말기에 저장되어 있는 농약 가격 데이터 및 농약판매리스트의 변경을 위한 권한을 부여하며, 상기 키오스크 본체의 전단에 설치되어 사용자가 소지하고 있는 농약의 식별코드를 스캔하는 바코드 리더기를 포함하는, 농약 정보 알리미 시스템., Ltext: 농업, prediction: 농업
710/1059 Row 710: application_number: 1020200086537, combined_string: invention_title: 식물공장 양액관리 제어시스템 abstract: 본발명은 식물공장 양액관리 제어시스템에 관한 것으로, 양액을 공급하는 공급배관(110)과 폐양액을 회수하는 회수배관(120), 그리고 물을 저장하는 원수탱크(130), 물과 폐양액을 혼합하는 혼합탱크(140), 배수하는 배수탱크(150) 및 밸브(160), 그리고 양액탱크(180)에 설치되어 혼합탱크로부터 공급되는 물과 폐양액 혼합액 및 양액을 공급하는 펌프(170)를 포함하여 구비되는 양액공급수단(100)과;작업자가 재배환경 조건을 입력하는 입력수단(200)과;센서에 의해 입력된 신호에 의해 재배환경을 제어하는 제어기(300)와;디스플레이 출력수단(400)을;포함하는 것으로,본발명은 주위 환경변화에 따라 적정한 양의 양액을 자동으로공급할 수 있도록 제어하고, 또한 외부 기상조건에 영향을 받지 않고 작물을 연중으로 생산할 수 있어 생산성 향상과 인건비가 절감되는 현저한 효과가 있다. claims: 양액을 공급하는 공급배관(110)과 폐양액을 회수하는 회수배관(120), 그리고 물을 저장하는 원수탱크(130), 물과 폐양액을 혼합하는 혼합탱크(140), 배수하는 배수탱크(150) 및 밸브(160), 그리고 양액탱크(180)에 설치되어 혼합탱크로부터 공급되는 물과 폐양액 혼합액 및 양액을 공급하는 펌프(170)를 포함하여 구비되는 양액공급수단(100)과;작업자가 재배환경 조건을 입력하는 입력수단(200)과;센서에 의해 입력된 신호에 의해 재배환경을 제어하는 제어기(300)와;디스플레이 출력수단(400)을;포함하는 식물공장 양액관리 제어시스템에 있어서,상기 입력수단(200)의 입력내용에는 초기화면(221), 관수설정(222), 엽면관수설정(223), 간격/시간제어(224), 엘이디제어설정(225), 환풍기설정(226), 유동팬설정(227), 냉난방기설정(228), 가습기설정(229), 수동작동(230), 시간설정(231), 관수보고(232), 기타설정(233)으로 표시되는 화면들에 제어내용을 입력하며,상기 기타설정(233)에 대한 화면의 양액경보설정은 터치를 반복하여 ‘사용함’, ‘사용 안함’으로 설정할 수 있고, EC상한값 설정은 관수가 설정한 EC상한값 이상이면 경보가 발생되며, pH하한값 설정은 관수가 pH하한값 이하이면 경보가 발생되고, 경보발생시간(초)은 경보음 발생시간을 설정하며, 운전정지시간(초)은 경보음 발생 후 운전정지 시간이 되면 시스템이 정지하게 되고, 양액선택은 질산 또는 알카리를 선택하는 것이며,상기 센서들에 의한 측정값이 설정치 이하일 경우인 양액통 내부의 양액품질이 저하한 경우 혼합탱크의 폐양액에 대한 물 비율을 높혀 양액통 내부의 양액품질을 향상하며, 그럼에도 불구하고 양액통 내부의 양액품질이 정상수치로 돌아오지 않으면, 제어기는 UV살균기 성능을 최대로 높이거나 예비로 설치되는 예비 UV살균기도 같이 동작시키며, 동시에 전자밸브를 개도를 좁게 작동하여 시간당 폐양액공급을 줄이게 되며, 엽채베드들에서 배출되는 폐양액의 센서감지에 의한 양액품질을 각각 측정하여 제어기에서는 종합적인 폐양액의 품질을 관리함으로써 양액탱크내부의 양액품질이 나쁠 경우 여러 개 엽체베드들중 가장 나쁜 것의 자동밸브를 닫아서 공급을 막게되어 양액탱크 내부의 품질을 복원 내지 향상시키는 것을 특징으로 하는 식물공장 양액관리 제어시스템, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

711/1059 Row 711: application_number: 1020200055941, combined_string: invention_title: 노지용 스마트팜 제어 시스템 및 방법과 이를 위한 컴퓨터 프로그램 abstract: 노지(露地)용 스마트팜(smart farm) 제어 시스템은, 스마트팜의 미리 설정된 관리 지역에 위치한 하나 이상의 센서 노드 장치에 의해 수집된 센서 데이터를 상기 관리 지역에 상응하는 게이트웨이(gateway) 장치로부터 수신하도록 구성된 데이터베이스 서버; 상기 데이터베이스 서버에 저장된 상기 센서 데이터를 분석하여 분석 정보를 생성하도록 구성된 분석 서버; 및 상기 분석 정보를 상기 스마트팜의 사용자의 사용자 장치에서 확인할 수 있도록 상기 사용자 장치에 제공하도록 구성된 웹 서비스 서버를 포함할 수 있다. 상기 데이터베이스 서버는, 상기 게이트웨이 장치로부터 수신된 상기 센서 데이터를 구독(subscribe) 방식으로 선택적으로 수집하여 저장하도록 구성된 시계열 데이터베이스를 포함한다. 상기 시스템에 의하면, 스마트팜의 각 지역별로 구비된 게이트웨이 장치를 통해 지역별 관제를 실현할 수 있고, 구독 방식의 시계열 데이터베이스 관리를 통하여 효율적인 스마트팜 제어가 실현될 수 있고 서버의 부하를 줄일 수 있는 이점이 있다. claims: 스마트팜의 미리 설정된 관리 지역에 위치한 하나 이상의 센서 노드 장치;상기 하나 이상의 센서 노드 장치에 의해 수집된 센서 데이터를 상기 관리 지역에 상응하는 게이트웨이 장치로부터 수신하도록 구성된 데이터베이스 서버; 상기 데이터베이스 서버에 저장된 상기 센서 데이터를 분석하여 분석 정보를 생성하도록 구성된 분석 서버; 및 상기 스마트팜의 사용자의 사용자 장치로부터 상기 스마트팜의 관수 장치를 제어하기 위한 제어 데이터 및 작황에 관련된 사용자 입력을 수신하고, 상기 분석 정보를 상기 사용자 장치에서 확인할 수 있도록 상기 사용자 장치에 제공하도록 구성된 웹 서비스 서버를 포함하되, 상기 데이터베이스 서버는, 상기 게이트웨이 장치로부터 수신된 상기 센서 데이터를 구독 방식으로 선택적으로 수집하여 저장하도록 구성된 시계열 데이터베이스를 포함하고, 상기 하나 이상의 센서 노드 장치 각각은, 상기 센서 데이터를 획득하기 위한 하나 이상의 센서가 구비된 센서 모듈, 상기 게이트웨이 장치와의 통신을 수행하기 위한 통신 모듈, 및 저장 모듈을 수용하도록 구성된 몸체부를 포함하며, 상기 몸체부는 토양 내의 서로 상이한 깊이에 위치하는 복수 개의 층에 걸쳐 연장되도록 토양 내에 삽입되는 연장부를 포함하고, 상기 하나 이상의 센서는 상기 복수 개의 층에 관련된 상기 센서 데이터를 각각 독립적으로 측정하도록 더 구성되며,상기 센서 모듈은 가속도 센서를 포함하고, 상기 저장 모듈은 농작물의 생육 환경에 관련된 미리 설정된 조건에 대한 정보를 저장하도록 구성되며,상기 통신 모듈은, 상기 하나 이상의 센서에 의해 측정된 상기 센서 데이터가 상기 미리 설정된 조건을 벗어나는 경우, 상기 센서 데이터의 조건 이탈에 관련된 정보를 상기 데이터베이스 서버에 전송하도록 더 구성되고,상기 분석 서버는, 상기 가속도 센서에 의해 측정된 가속도의 크기와 방향으로부터 상기 하나 이상의 센서 노드 장치가 지면에 대해 이루는 각도인 기울기를 산출하고, 기울기가 미리 설정된 각도 이상인 센서 노드 장치가 있을 경우 상기 기울기가 미리 설정된 각도 이상인 센서 노드 장치로부터 수신된 상기 센서 데이터를 오류 데이터로 결정하며, 상기 센서 노드 장치의 기울기를 이용하여 상기 오류 데이터에서 상기 복수 개의 층에 관련된 상기 센서 데이터 각각에 상응하는 감지 깊이를 보정하도록 구성된 오류 탐지부; 및상기 센서 데이터, 상기 제어 데이터 및 상기 사용자 입력의 조합에 의해 정의되는 데이터 레코드들을 군집화함으로써, 농작물의 생육에 관련된 조건 및 생육 결과물에 대한 예측값을 포함하는 작물 모델링 데이터를 생성하되, 상기 오류 탐지부에 의해 상기 감지 깊이가 보정된 상기 센서 데이터를 이용하여 상기 작물 모델링 데이터를 생성하도록 구성된 모델링 생성부를 포함하고, 상기 웹 서비스 서버는, 상기 센서 데이터의 조건 이탈에 관련된 정보를 상기 스마트팜의 사용자에게 통지하도록 더 구성된 노지용 스마트팜 제어 시스템. 노지용 스마트팜 제어 방법으로서,노지용 스마트팜 제어 시스템의 데이터베이스 서버가, 스마트팜의 미리 설정된 관리 지역에 위치한 하나 이상의 센서 노드 장치에 의해 수집된 센서 데이터를 상기 관리 지역에 상응하는 게이트웨이 장치로부터 수신하는 단계; 상기 데이터베이스 서버가, 상기 게이트웨이 장치로부터 수신된 상기 센서 데이터를 구독 방식으로 선택적으로 수집하여 상기 데이터베이스 서버의 시계열 데이터베이스에 저장하는 단계; 상기 노지용 스마트팜 제어 시스템의 웹 서비스 서버가, 스마트팜의 사용자의 사용자 장치로부터 상기 스마트팜의 관수 장치를 제어하기 위한 제어 데이터 및 작황에 관련된 사용자 입력을 수신하는 단계;상기 노지용 스마트팜 제어 시스템의 분석 서버가, 상기 데이터베이스 서버에 저장된 상기 센서 데이터를 분석하여 상기 스마트팜의 사용자에게 제공되기 위한 분석 정보를 생성하는 단계; 및 상기 웹 서비스 서버가, 상기 분석 정보를 상기 사용자 장치에 제공하는 단계를 포함하되, 상기 하나 이상의 센서 노드 장치 각각은, 상기 센서 데이터를 획득하기 위한 하나 이상의 센서가 구비된 센서 모듈, 상기 게이트웨이 장치와의 통신을 수행하기 위한 통신 모듈, 및 저장 모듈을 수용하도록 구성된 몸체부를 포함하며, 상기 몸체부는 토양 내의 서로 상이한 깊이에 위치하는 복수 개의 층에 걸쳐 연장되도록 토양 내에 삽입되는 연장부를 포함하고, 상기 센서 데이터는, 상기 하나 이상의 센서에 의하여 상기 복수 개의 층에 대해 각각 독립적으로 측정된 센서 데이터들을 포함하며, 상기 센서 모듈은 가속도 센서를 포함하고, 상기 저장 모듈은 농작물의 생육 환경에 관련된 미리 설정된 조건에 대한 정보를 저장하도록 구성되며,상기 분석 정보를 생성하는 단계는, 상기 분석 서버가, 상기 가속도 센서에 의해 측정된 가속도의 크기와 방향으로부터 상기 하나 이상의 센서 노드 장치가 지면에 대해 이루는 각도인 기울기를 산출하는 단계;상기 분석 서버가, 기울기가 미리 설정된 각도 이상인 센서 노드 장치가 있을 경우 상기 기울기가 미리 설정된 각도 이상인 센서 노드 장치로부터 수신된 상기 센서 데이터를 오류 데이터로 결정하는 단계; 상기 분석 서버가, 상기 센서 노드 장치의 기울기를 이용하여 상기 오류 데이터에서 상기 복수 개의 층에 관련된 상기 센서 데이터 각각에 상응하는 감지 깊이를 보정하는 단계; 및상기 분석 서버가, 상기 센서 데이터, 상기 제어 데이터 및 상기 사용자 입력의 조합에 의해 정의되는 데이터 레코드들을 군집화함으로써, 농작물의 생육에 관련된 조건 및 생육 결과물에 대한 예측값을 포함하는 작물 모델링 데이터를 생성하는 단계를 포함하되, 상기 작물 모델링 데이터를 생성하는 단계는 상기 감지 깊이가 보정된 상기 센서 데이터를 이용하여 수행되며,상기 노지용 스마트팜 제어 방법은, 상기 하나 이상의 센서에 의해 측정된 상기 센서 데이터가 상기 미리 설정된 조건을 벗어나는 경우, 상기 노지용 스마트팜 제어 시스템이 상기 센서 노드 장치로부터 상기 센서 데이터의 조건 이탈에 관련된 정보를 수신하는 단계; 및 상기 노지용 스마트팜 제어 시스템이, 상기 센서 데이터의 조건 이탈에 관련된 정보를 상기 스마트팜의 사용자에게 통지하는 단계를 더 포함하는 노지용 스마트팜 제어 방법. 하드웨어와 결합되어 제5항 내지 제7항 중 어느 한 항에 따른 노지용 스마트팜 제어 방법을 실행하도록 컴퓨터로 판독 가능한 기록매체에 저장된 컴퓨터 프로그램., Ltext: 농업, prediction: 임업
712/1059 Row 712: application_number: 1020200050746, combined_string: invention_title: 악취제거 가축분뇨 발효비료와 이의 가공방법 abstract: 본 발명의 '악취제거 가축분뇨 발효비료'는 강산성수용액으로 악취를 소멸시키고 발효시켜 유기질비료로 재활용되도록 가공하는 발명인데 그동안은 처리하지 않고 쉽게 해양투기를 해 왔으나 국제법상 투기가 금지되어 국내에서 문제가 되고 있고 특히 돼지분뇨는 악취가 심하여 논밭에 살포도 허가를 받는 등 심히 어려운 처지에 놓인 축산분뇨를 유기질비료로 가공하기 위해 발효를 택하여 실시하는 악취제거와 발효로 어려움에 처한 축산분뇨의 처리방법에 관한 발명이다,가장 먼저 처리할 문제는 악취로서 수거할 때 미리 전처리로 강산성수용액을 살포한 후 축산분뇨처리장으로 운반하여 후처리로 강산성수용액을 추가한 후 악취제거를 확실히 하기 위해 7 내지 10일간 자연발효를 시키면 손으로 만져도 냄새가 없어서 분말로 논밭에 살포하거나 시설재배영농에도 사용할 수 있는 유기질비료로 기공하는 축산분뇨 발효유기질비료 가공에 관한 제조기술에 속하는 분야이다,본 발명에서 재활용 축산분뇨비료로 제공하므로 인하여 악취로 인한 폐기물 처리도 어려운 축산분뇨가 비료로 제조됨은 물론 해양투기도 할 필요 없이 재활용 비료로 제조되어 축산농가의 고민도 해결되고 유기질비료도 얻게 되어 축산농민과 유기질비료를 필요로 하는 영농농민들에게 희소식이 되는 효과가 기대된다, [색인어]유수분리, 가축액비(家畜液肥), 유기질비료, 재활용비료,축산분뇨, 가축구비(家畜), 황화철수용액, 부루-민수용액,계분(鷄糞), 우분(牛糞), claims: 계분, 우분 또는 돼지분뇨를 일정량씩 트럭적재함 또는 탱크로리로 이송하기 직전 황화철수용액(10)으로 전처리(제1공정)하며 처리장소로 이송하고, 상기 돼지분뇨는 유수분리(제2공정)시켜 얻은 액비와 구비 중에 상기 액비는 상기 구비와 분리하여 부루-민수용액(20)으로 액비후처리(제4-1공정)한 후 액비숙성(제6-1공정)과 액비포장(제7-1공정)으로 악취 없는 가축액비로 가공하고,상기 계분과 우분은 상기 전처리를 거치면서 상기 유수분리 없이 수거하여 상기 돼지분뇨에서 분리수거 된 상기 돼지구비와 함께 혼합수집(제3공정)에서 혼합하며 상기 부루-민수용액으로 구비후처리(제4-2공정)를 하고 일정기간의 혼합발효(제5공정)와 구비숙성(제6-2공정)으로 가축구비가 제조되고, 제조된 상기 가축구비를 구비포장(제7-1공정)시켜 유기질비료로 재활용되는 것이 특징인 악취제거 가축분뇨 발효비료 가공방법돼지분뇨를 일정량씩 수거용 차량탱크로리에 담고 상기 돼지분뇨에 1 내지 2중량%의 황화철수용액(10)을 첨가하는 전처리(제1공정)로 가공공장에 이송하고, 이송 시마다 상기 돼지분뇨를 유수분리(제2공정)시키고,상기 유수분리로 수거된 액비를 제외한 돼지구비만 별도 수거하고, 상기 전처리로 별도 수거된 우분과 계분의 구비도 혼합수집(제3공정)하고 구비후처리(제4-2공정)에서 부루-민수용액(20) 1중량%를 10배의 물로 희석시켜 살포하여 3일간은 뒤집고 7일간은 공기만 주입하며 혼합발효(제5공정)로 제조된 발효구비를 구비숙성(제6-2공정)으로 완숙시켜 구비포장(제7-2공정)으로 유기질비료로 재활용되는 것이 특징인 악취제거 가축분뇨 발효비료, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

713/1059 Row 713: application_number: 1020200049113, combined_string: invention_title: 용존산소량 및 양액 농도 조절이 가능한 양액 재배 장치 및 방법 abstract: 본 발명은 층류를 활용한 수경재배용 육묘 장치에 관한 것으로, 양액이 담겨있는 양액통; 하부에 배출구가 형성되어 있고, 상기 배출구로 상기 양액을 배출하는 육묘판; 상기 양액을 상기 육묘판으로 공급하는 공급부; 및 상기 배출구로 배출되는 상기 양액의 레이놀드수가 층류 발생 조건인 2000 이하가 되도록 상기 공급부의 출력을 조절하는 제어부;를 포함한다. claims: 양액이 담겨있는 양액통; 하부에 배출구가 형성되어 있고, 상기 배출구로 상기 양액을 배출하며 식물이 수용되는 재배 베드; 상기 양액통의 양액을 상기 재배 베드로 공급하는 공급부; 상기 양액의 용존산소량에 따라 상기 배출구로 배출되는 상기 양액의 레이놀드수가 층류 발생 조건이 되도록 상기 공급부의 출력을 제어하고, 상기 배출구로 배출되는 상기 양액의 농도와 상기 양액통의 상기 양액의 농도의 농도차에 따라 상기 공급되는 양액의 유량이 늘어나게 상기 공급부의 출력을 제어하는 제어부; 및 상기 제어부가 상기 공급부의 출력을 제어할 때 상기 용존산소량 및 상기 농도차 중 어느 것에 우선순위를 두고 제어해야 하는지 판단하는 판단부;를 포함하는 것 을 특징으로 하는 용존산소량 및 양액 농도 조절이 가능한 양액 재배 장치. 공급부가 양액통의 양액을 재배 베드로 공급하는 제1단계; 용존산소 측정 센서가 상기 재배 베드의 배출구로 배출되는 양액의 용존산소량을 측정하는 제2단계; 양액 농도 측정 센서가 상기 배출구로 배출되는 상기 양액의 농도와 상기 양액통의 상기 양액의 농도를 측정하는 제3단계; 계산부가 상기 배출구로 배출되는 상기 양액의 농도와 상기 양액통의 상기 양액의 농도의 농도차를 계산하는 제4단계; 및 제어부가 상기 측정한 상기 양액의 용존산소량이 저장부에 저장된 용존산소량 기준치 이하일 경우 상기 배출구로 배출되는 상기 양액의 레이놀드수가 층류 발생 조건이 되도록 공급부의 출력을 제어하고, 상기 계산된 농도차가 저장부에 저장된 농도차 기준치 이상일 경우 상기 공급되는 양액의 유량이 늘어나게 상기 공급부의 출력을 제어하는 제5단계;를 포함하되, 상기 제5단계는, 판단부가 상기 측정한 용존산소량이 상기 용존산소량 기준치 대비 이상 또는 이하인지, 상기 계산한 농도차가 상기 농도차 기준치 대비 이상 또는 이하인지 판단하는 제5-1단계; 카메라가 상기 식물의 뿌리를 촬영하는 제5-2단계; 상기 판단부가 상기 제어부가 상기 공급부의 출력을 제어할 때 상기 측정한 용존산소량 및 상기 계산한 농도차 중 어느 것에 우선순위를 두고 제어해야 하는지 판단하는 제5-3단계; 및 상기 판단부가 판단한 우선순위에 따라 상기 제어부가 상기 공급부의 출력을 제어하는 제5-4단계;인 것 을 특징으로 하는 용존산소량 및 양액 농도 조절이 가능한 양액 재배 방법., Ltext: 농업, prediction: 임업
714/1059 Row 714: application_number: 1020200043935, combined_string: invention_title: 식물 뿌리 생육 촉진용 액상비료의 제조방법 및 이에 의해 제조된 액상비료 abstract: 본 발명은 식물 뿌리 생육 촉진용 액상비료의 제조방법 및 이에 의해 제조된 액상비료에 관한 것이다.본 발명에 따른 식물 뿌리 생육 촉진용 액상비료의 제조방법은 물에 메타규산소다, 인산칼륨, 탄산칼륨 및 구연산을 포함하는 재료들을 용해하여 혼합액을 제조하는 혼합액 제조 단계(S100); 버드나무, 도꼬마리, 참쑥, 순비기나무, 소리쟁이, 민들레 및 어성초를 포함하는 천연재료를 준비한 후 혼합하는 천연재료 준비 및 혼합 단계(S200); 상기 혼합된 천연재료를 발효시키는 천연재료 발효 단계(S300); 상기 발효된 천연재료와 상기 혼합액을 혼합한 후 발효를 더 진행시켜 천연추출물을 제조하는 천연추출물 제조 단계(S400); 미생물 활성화제를 제조하는 미생물 활성화제 제조 단계(S500); 및 상기 천연추출물과 미생물 활성화제를 혼합하여 액상비료를 제조하는 액상비료 제조 단계(S600)를 포함한다.상기한 구성에 의해 본 발명에 따른 식물 뿌리 생육 촉진용 액상비료의 제조방법은 원예작물 생산에 중요한 영향을 미치는 규산 및 천연추출물을 이용하여 액상비료를 제조함으로써, 식물의 발근 및 생장 촉진을 유도하고 과실의 비대, 수확량의 증대, 착색 및 당도를 증진시킬 수 있는 액상비료를 제조할 수 있다. claims: 물에 메타규산소다, 인산칼륨, 탄산칼륨 및 구연산을 포함하는 재료들을 용해하여 혼합액을 제조하는 혼합액 제조 단계(S100);버드나무, 도꼬마리, 참쑥, 순비기나무, 소리쟁이, 민들레 및 어성초를 포함하는 천연재료를 준비한 후 혼합하는 천연재료 준비 및 혼합 단계(S200);상기 혼합된 천연재료를 발효시키는 천연재료 발효 단계(S300);상기 발효된 천연재료와 상기 혼합액을 혼합한 후 발효를 더 진행시켜 천연추출물을 제조하는 천연추출물 제조 단계(S400);미생물 활성화제를 제조하는 미생물 활성화제 제조 단계(S500); 및상기 천연추출물과 미생물 활성화제를 혼합하여 액상비료를 제조하는 액상비료 제조 단계(S600)를 포함하는 것을 특징으로 하는 식물 뿌리 생육 촉진용 액상비료의 제조방법.제 2항 또는 제 3항의 제조방법에 의해 제조된 것을 특징으로 하는 식물 뿌리 생육 촉진용 액상비료., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

715/1059 Row 715: application_number: 1020200032510, combined_string: invention_title: 양액 재배 시스템 abstract: 본 발명은 식물의 뿌리 부분에 양액을 에어로졸 형태로 공급하여 양액의 낭비를 줄이고, 양분의 흡수율을 높여 성장 효율을 증가시킨 양액 재배 시스템을 제공하기 위한 것이다.본 발명의 양액 재배 시스템은, 외부에 식물의 줄기 및 잎이 배치되는 수용홈(110)이 형성되고, 내부에 식물의 뿌리부분이 배치되는 공급공간(120)이 형성된 재배대(100); 식물의 성장이 필요한 양액이 저장된 양액통(200); 상기 양액통(200)에 저장된 양액을 상기 재배대(100)의 내부에 공급하는 공급수단(300); 을 포함한다. claims: 외부에 식물의 줄기 및 잎이 배치되는 수용홈(110)이 형성되고, 내부에 식물의 뿌리부분이 배치되는 공급공간(120)이 형성된 재배대(100);식물의 성장이 필요한 양액이 저장된 양액통(200);상기 양액통(200)에 저장된 양액을 상기 재배대(100)의 내부에 에어로졸 형태로 공급하는 공급수단(300); 상기 재배대(100)의 내부 온도를 일정하게 제어하는 제1온도조절수단(400);상기 양액통(200)에 수용된 양액의 온도를 일정하게 제어하는 제2온도조절수단(500); 을 포함하되,수분과 영양분을 일정한 비율로 혼합하여 양액을 생성하여 상기 양액통(200)에 공급하는 양액교반기(600);상기 재배대(100) 내부에 공급된 에어로졸 상태의 양액을 모아 재사용하기 위한 배수장치(700); 를 포함하되,상기 수용홈(110)의 상단 테두리에는 안착부(111)가 돌출 형성되고,상기 수용홈(110)에는 식물이 식재된 모종화분(130)이 삽입 배치되며,상기 모종화분(130)는, 상단 테두리에 상기 안착부(111)에 지지되는 지지부(131)가 돌출 형성되고, 하단이 상기 공급공간(120) 방향으로 하향 경사지게 형성되며,상기 공급수단(300)은 원심형 가습기로 이루어지고,상기 제1온도조절수단(400)은, 상기 재배대(100)의 내부에 구비되는 제1열교환파이프(410);상기 제1열교환파이프(410)에 열교환액을 공급하는 제1냉각기(420); 를 포함하며,상기 제2온도조절수단(500)은,상기 양액통(200)의 내부에 구비되는 제2열교환파이프(510);상기 제2열교환파이프(510)에 열교환액을 공급하는 제2냉각기(520); 를 포함하며,상기 배수장치(700)는 펌프에 의해 상기 재배대(100)의 내부에 모인 액체상태의 양액을 보조양액통(750)으로 인출한 후 영양분을 재혼합한 후 상기 양액통(200)에 공급하는 것을 특징으로 하는 양액 재배 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

716/1059 Row 716: application_number: 1020200020594, combined_string: invention_title: 빅데이터에 기반한 농업 공공 데이터를 수집하는 방법 및 이를 위한 장치 abstract: 본 발명은 농산물 관리 서버가 빅데이터를 기반으로 농산물의 수요를 예측하는 방법을 개시한다. 특히, 상기 방법은 기상 예측 서버로부터 현시점 이후 제 1 기간 동안의 복수의 농업 피해 요소들에 관련된 기상 예측 정보를 수신하고, 현시점부터 제 2 기간 전까지의 상기 농산물의 판매량, 판매 가격 및 상기 복수의 농업 피해 요소들에 대한 정보를 획득하고, 미디어 서버로부터 상기 농산물의 검색량 및 상기 농산물과 관련된 키워드를 획득하여, 상기 농산물의 소비 추이를 분석하고, 상기 기상 예측 정보, 상기 농업 피해 요소들에 대한 정보 및 상기 농산물의 소비 추이를 기반으로, 제 3 기간 이후의 시점에서의 상기 농산물의 가격 및 수요를 예측하는 것을 특징으로 한다. claims: 농산물 관리 서버가 빅데이터를 기반으로 농산물의 수요를 예측하는 방법에 있어서,기상 예측 서버로부터 현시점 이후 제 1 기간 동안의 복수의 농업 피해 요소들에 관련된 기상 예측 정보를 수신하고,현시점부터 제 2 기간 전까지의 상기 농산물의 판매량, 판매 가격 및 상기 복수의 농업 피해 요소들에 대한 정보를 획득하고,미디어 서버로부터 상기 농산물의 검색량 및 상기 농산물과 관련된 키워드를 획득하여, 상기 농산물의 소비 추이를 분석하고,상기 기상 예측 정보, 상기 농업 피해 요소들에 대한 정보 및 상기 농산물의 소비 추이를 기반으로, 제 3 기간 이후의 시점에서의 상기 농산물의 가격 및 수요를 예측하고,상기 농산물의 소비 추이를 분석하는 것은,상기 농산물이 검색되거나 상기 농산물과 관련된 키워드를 획득하는데 기반이 된 미디어 매체들 각각에 대한 서로 다른 가중치를 부여하고,상기 서로 다른 가중치를 기반으로 상기 농산물의 소비 추이를 분석하는 것을 포함하고,상기 농산물과 관련된 병충해 정보를 획득하고,상기 병충해 정보를 기반으로 상기 병충해 정보와 관련된 병충해로 인한 상기 농산물의 피해 규모 및 피해 기간을 추정하고,상기 병충해로 인한 피해 규모 및 피해 기간을 최소화하기 위한 방지책을 결정하는 것을 더 포함하고,상기 병충해 정보는 상기 병충해의 종류, 상기 병충해의 예상 개체 수 및 상기 병충해가 상기 농산물에 입히는 피해 종류를 포함하고,상기 농산물의 가격 및 수요를 기반으로 상기 농산물의 매입 시점 및 상기 농산물의 매도 시점을 결정하고,상기 농산물의 가격 및 수요를 예측하는 것은,상기 농산물이 수입되는 수입량 및 상기 수입되는 농산물의 가격을 더 고려하고,상기 복수의 농업 피해 요소들은 풍수, 침수, 산불, 폭염 및 가뭄에 관련된 피해 요소들 및 야생 동물에 관련된 피해 요소를 포함하고,상기 제 2 기간 전의 상기 복수의 농업 피해 요소들 각각에 의한 농업 피해 규모를 획득하고,상기 농업 피해 규모를 기반으로 상기 복수의 농업 피해 요소들 각각에 서로 다른 가중치를 설정하고,상기 서로 다른 가중치를 기반으로 상기 농산물의 생산량을 예측하는 것을 더 포함하고,상기 농업 피해 규모는 상기 복수의 농업 피해 요소들 각각에 대한 억원 단위의 금액 정보를 포함하고,상기 복수의 농업 피해 요소들 중 상기 농업 피해 규모에 따른 금액 정보 간의 차이가 일정 값 미만인 농업 피해 요소들은 동일한 가중치가 설정되고,동일한 가중치로 설정된 농업 피해 요소들이 3가지 이상이고, 가장 낮은 금액 정보를 가지는 농업 피해 요소 및 가장 높은 금액 정보를 가지는 농업 피해 요소 간의 차이가 상기 일정 값 이상인 경우, 상기 가장 높은 금액 정보를 가지는 농업 피해 요소에 대한 가중치는 상기 동일한 가중치에 1.1배로 설정되고,상기 농산물과 관련된 병충해 정보는,농산물의 특정 부위에 대한 복수 개의 제 1 이미지들을 획득하고,상기 복수 개의 제 1 이미지 들을 기반으로, 상기 농산물이 병충해 피해를 입지 않은 경우의 상기 특정 부위의 제 1 색상 정보를 추출하고, 상기 농산물의 특정 부위가 병충해 피해를 입은 것을 포함하는 복수 개의 제 2 이미지들을 획득하고, 상기 복수 개의 제 2 이미지들에 포함된 상기 특정 부위의 제 2 색상 정보를 추출하고, 상기 제 1 색상 정보 및 상기 제 2 색상 정보를 비교하여, 병충해가 발생한 경우의 이미지 값들을 저장하고, 농장에 설치된 카메라를 통해 수신한 제 3 이미지를 상기 이미지 값과 비교한 것을 기반으로 획득되는,농산물 수요 예측 방법., Ltext: 농업, prediction: 농업
717/1059 Row 717: application_number: 1020200014323, combined_string: invention_title: 토양 상태에 따라 식물의 생장을 예측, 분석하는 방법, 장치 및 프로그램 abstract: 본 발명은 토양 상태에 따라 식물의 생장을 예측, 분석하는 서버에 관한 것으로, 재배 구역 각각의 토양 조건과, 토양의 농작물 재배 이력, 휴경 여부 중 적어도 하나를 포함하는 사용자 조건을 조건 테이블에 시뮬레이션 하여, 각 재배 구역에 대하여 작물 후보군을 도출하고, 재배실력지수와 선호작물 정보를 반영하여 상기 작물 후보군 중 적어도 하나의 추천 작물을 선택해주는 효과가 있다. claims: 복수의 토양 조건과 환경 조건에 따른 농작물 추천 정보가 기록된 조건 테이블이 저장된 데이터베이스;사용자의 토양에 설치된 하나 이상의 센서로부터 센싱된 정보, 및 사용자 단말로부터 입력된 사용자 조건과 토양의 정보를 수집하는 수집부;상기 수집된 정보로부터 토양의 위치별 조건을 체킹하여 사용자의 토양을 구획하고, 사용자 토양의 총 면적을 고려하여 상기 토양을 하나 이상의 재배 구역으로 구획하는 농지 구획부;사용자로부터 입력된 사용자의 농작물 재배 경력, 예산 및 재배 장비를 기초로 하여 사용자의 재배실력지수를 산출하는 산출부; 및상기 구획된 재배 구역 각각의 토양 조건과, 상기 토양의 농작물 재배 이력, 휴경 여부 중 적어도 하나를 포함하는 사용자 조건을 상기 조건 테이블에 시뮬레이션 하여, 상기 각 재배 구역에 대하여 작물 후보군을 도출하고, 재배실력지수와 선호작물 정보를 반영하여 상기 작물 후보군 중 적어도 하나의 추천 작물을 선택하는, 인공지능모듈을 포함하는, 토양 상태에 따라 식물의 생장을 예측, 분석하는 서버.서버에 의해 수행되는 방법으로,사용자의 토양에 설치된 하나 이상의 센서로부터 센싱된 정보, 및 사용자 단말로부터 입력된 사용자 조건과 토양의 정보를 수집하는 단계;상기 수집된 정보로부터 토양의 위치별 조건을 체킹하여 사용자의 토양을 구획하고, 사용자 토양의 총 면적을 고려하여 상기 토양을 하나 이상의 재배 구역으로 구획하는 단계;사용자로부터 입력된 사용자의 농작물 재배 경력, 예산 및 재배 장비를 기초로 하여 사용자의 재배실력지수를 산출하는 단계;상기 구획된 재배 구역 각각의 토양 조건과, 상기 토양의 농작물 재배 이력, 휴경 여부 중 적어도 하나를 포함하는 사용자 조건을 상기 조건 테이블에 시뮬레이션 하여, 상기 각 재배 구역에 대하여 작물 후보군을 도출하는 단계; 및상기 재배실력지수와 선호작물 정보를 반영하여 상기 작물 후보군 중 적어도 하나의 추천 작물을 선택하는 단계를 포함하고,상기 서버는,복수의 토양 조건과 환경 조건에 따른 농작물 추천 정보가 기록된 조건 테이블이 저장된 데이터베이스를 포함하는, 토양 상태에 따라 식물의 생장을 예측, 분석하는 방법.하드웨어인 컴퓨터와 결합되어, 제9항의 방법을 실행시키기 위하여 매체에 저장된, 토양 상태에 따라 식물의 생장을 예측, 분석하는 프로그램., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

718/1059 Row 718: application_number: 1020200000365, combined_string: invention_title: 딥러닝을 이용한 작물 질병 진단 기반 수확량 예측 시스템 및 방법 abstract: 러닝을 이용한 작물 질병 기반 수확량 예측 시스템 및 방법이 개시된다. 리프 이미지(leaf image)를 수집하여 이미지 프로세싱을 수행하는 이미지 프로세싱 모듈(image processing module, IPM); 상기 이미지 프로세싱 모듈에서 이미지 프로세싱이 수행된 리프 이미지를 이용하여 작물 질병을 진단하는 작물 질병 진단 모듈(crop disease diagnosis module, CDDM); 상기 작물 질병 진단 모듈에서 진단된 작물 질병을 기반으로 딥러닝(deep learning)을 수행하여 작물 수확량을 예측하는 작물 수확량 예측 모듈(crop yield prediction module, CYPM)을 구성한다. 상술한 딥러닝을 이용한 작물 질병 기반 수확량 예측 시스템 및 방법에 의하면, 작물의 드론 촬영 이미지를 이용하여 작물의 질병 발병 여부를 파악하도록 구성됨으로써, 작물의 질병 진단과 대처를 신속하고 정확하게 수행할 수 있는 효과가 있다. 또한, 딥러닝을 이용하여 작물 별로 더 많은 종류의 질병을 진단할 수 있게 됨으로써, 질병에 대한 진단의 정확도를 높이고 그에 대한 신속하고 정확한 대처를 가능하게 하는 효과가 있다. 그리고 작물의 질병에 기반하여 수확량을 예측할 수 있도록 구성됨으로써, 기존의 센서 데이터에 기반한 수확량 예측보다 더 정확한 예측을 할 수 있는 효과가 있다. claims: 인터넷 또는 AI 허브 이미지 네트워크(AI hub image network)에서 리프 이미지(leaf image)를 수집하여 이미지 프로세싱을 수행하는 이미지 프로세싱 모듈(image processing module, IPM);상기 이미지 프로세싱 모듈에서 이미지 프로세싱이 수행된 리프 이미지를 이용하여 CNN(convolutional neural network) 모델을 생성하고, 생성된 CNN 모델을 이용하여 작물 질병을 진단하는 작물 질병 진단 모듈(crop disease diagnosis module, CDDM);상기 작물 질병 진단 모듈에서 진단된 작물 질병을 기반으로 ANN(artificial neural network)을 이용하여 단위 면적당 작물 수확량을 예측하는 작물 수확량 예측 모듈(crop yield prediction module, CYPM)을 포함하고,상기 이미지 프로세싱 모듈은,상기 리프 이미지를 수집하거나 별도로 입력받는 이미지 수집/입력부;상기 이미지 수집/입력부에서 수집되거나 입력된 복수의 리프 이미지를 하나의 단일 리프 이미지로 전환하여 정규화하는 리프 이미지 정규화부;상기 리프 이미지 정규화부에서 정규화된 리프 이미지에 대해 질병명이 확실하게 진단된 이미지는 훈련용 이미지(training image)로 분류하고, 질병명이 확실하게 진단되지 않은 이미지는 테스트용 이미지(test image)로 분류하는 리프 이미지 분류부;상기 리프 이미지 분류부에서 분류된 리프 이미지가 저장되는 리프 이미지 저장부;상기 리프 이미지 저장부에 저장된 각 리프 이미지에 대해 R, G, B의 3채널 이미지로 변환하여 각각 출력하는 3채널 이미지 출력부를 포함하도록 구성되고,상기 이미지 수집/입력부는,AI 허브(hub) 이미지 네트워크를 통해 검색하거나 인터넷 상에서 웹 크롤링(web crawling)을 하여 리프 이미지를 수집하는 리프 이미지 수집부;질병 진단이나 수확량 예측을 위해 소정의 농장에서 드론을 통해 촬영되는 리프 이미지를 별도로 입력받는 리프 이미지 입력부를 포함하도록 구성되고,상기 리프 이미지 정규화부는,상기 복수의 리프 이미지에서 구글(Goolge) 사의 비젼 API(vision API)를 이용하여 단일 리프 영역의 좌측 상단, 우측 상단, 좌측 하단, 우측 하단의 좌표를 각각 리턴하여 하나의 영역인 단일 리프 이미지를 추출하는 단일 리프 이미지 추출부;상기 비젼 API에서 리턴한 좌표를 기준으로 단일 리프 이미지를 128*128 크기로 리사이징하여 정규화하는 리프 이미지 리사이징부를 포함하도록 구성되고,상기 리프 이미지 저장부는,상기 리프 이미지 분류부에서 훈련용 이미지로 분류된 리프 이미지가 저장되는 훈련용 리프 이미지 저장부;상기 리프 이미지 분류부에서 테스트용 이미지로 분류된 리프 이미지가 저장되는 테스트용 리프 이미지 저장부를 포함하도록 구성되고,상기 작물 질병 진단 모듈은,상기 3채널 이미지 출력부에서 출력된 R, G, B의 3채널 이미지를 입력받는 3채널 이미지 입력부;각 작물별로 CNN 모델을 생성하는 CNN 모델 생성부;상기 CNN 모델 생성부에 의해 생성된 CNN 모델에 따른 작물 질병 진단 결과를 출력하는 CNN 모델 출력부를 포함하도록 구성되고,상기 CNN 모델 생성부는,상기 3채널 이미지에 대하여 각각 3회의 CNN 모델을 생성하는 컨벌루션 수행부상기 3채널 이미지에 대하여 각각 3회의 서브-샘플링을 수행하는 서브-샘플링 수행부상기 컨벌루션 수행부 및 상기 서브-샘플링 수행부에 의해 산출된 컨벌루셔널 특징 맵을 이용하여 신경망 모델로 바꾸어 계산하는 CNN 모델 변환부를 포함하도록 구성되고,상기 작물 수확량 예측 모듈은,상기 작물 질병 진단 모듈에서 진단된 작물 질병 데이터를 수신하여 입력하는 작물 질병 데이터 수신/입력부;농장 서버로부터 농장 환경 데이터를 수신하여 입력하는 농장 환경 데이터 수신/입력부;기상 정보 제공 서버로부터 현재 날씨 및 재배/수확기의 예상 날씨를 포함하는 날씨 데이터를 수신하여 입력하는 날씨 데이터 수신/입력부;작물 수확 통계 서버로부터 작물별 수확량 통계 데이터를 수신하여 입력하는 작물별 수확량 통계 데이터 수신/입력부;상기 작물 질병 데이터 수신/입력부로부터 입력되는 작물 질병 데이터, 상기 농장 환경 데이터 수신/입력부로부터 입력되는 농장 환경 데이터, 상기 날씨 데이터 수신/입력부로부터 입력되는 날씨 데이터, 상기 작물별 수확량 통계 데이터 수신/입력부로부터 입력되는 통계 데이터에 기반하여 ANN을 이용하여 농장의 단위 면적당 수확량 및 농장의 면적에 따른 수확량을 산출하는 ANN 수확량 예측부;상기 ANN 수확량 예측부에서 예측된 수확량 예측 결과를 출력하는 수확량 예측 결과 출력부;상기 수확량 예측 결과 출력부에서 출력된 수확량 예측 결과를 상기 농장 서버 또는 농장주 단말로 송신하는 수확량 예측 결과 송신부를 포함하도록 구성되고,상기 컨벌루션 수행부는,상기 3채널 이미지를 n*n 정방 행렬을 이용하여 이미지를 스캔하여 이미지의 특징을 추출하고 그 결과물로서 컨벌루셔널 특징 맵(convolutional feature map)을 출력하며, 4*4 필터를 이용하여 이미지의 특징을 추출하되 첫 연산에서는 20개, 두번째 연산에서는 40개, 3번째 연산에서는 60개를 사용하여 총 3회의 컨벌루션 과정에서 스트라이드는 모두 1을 사용하고 이미지와 필터 사이에 ReLU 함수를 사용하여 컨벌루셔널 특징 맵을 산출하도록 구성되며,상기 서브-샘플링 수행부는,상기 컨벌루션 수행부에서 출력된 컨벌루셔널 특징 맵을 서브-샘플링을 통해 간소화하며, 소정 크기의 이미지 픽셀들 중 가장 특징이 강한 영역을 추출하여 하나의 픽셀로 만드는 2*2 맥스 풀링 기법을 이용하여 컨벌루셔널 특징 맵을 간소화하도록 구성되며,상기 CNN 모델 변환부는,16*16*60의 컨벌루셔널 특징 맵을 n 개의 출력 배열로 전환하되, 풀리 커넥티드 신경망을 이용하여 작물의 질병의 수와 같은 크기의 배열을 생성하며, 상기 n은 작물에서 발생할 수 있는 질병의 수로 구성되며,상기 CNN 모델 출력부는,각 작물의 정상 노드 1개와 각 작물이 가질 수 있는 질병의 수에 따른 n개의 질병 노드로 구성되는 출력 노드가 구비되며, 각 출력 노드를 통해 각 질병에 대한 0 내지 1의 값을 출력하고, 각 출력 노드의 값 중에서 가장 큰 값을 갖는 질병을 해당 작물의 질병으로 규정하도록 구성되는 것을 특징으로 하는 딥러닝을 이용한 작물 질병 진단 기반 수확량 예측 시스템., Ltext: 농업, prediction: 임업
719/1059 Row 719: application_number: 1020190177597, combined_string: invention_title: 인공지능 기반 스마트 작물 재배 관리장치, 및 그 방법 abstract: 본 발명은 스마트 작물 재배 관리장치 및 그 방법에 관한 것으로, 본 발명에 따른 스마트 작물 재배 관리장치는 작물이 생육되는 생육환경 정보를 센싱하는 환경센싱부; 상기 작물의 생육환경과 상기 작물이 양액을 흡수하는 양액 흡수량 간의 상관관계를 규정한 양액흡수모델을 저장하는 양액모델 저장부; 상기 생육환경 정보와 상기 양액흡수모델을 기초로 상기 생육환경에서 상기 작물이 흡수하는 양액 흡수량을 예측하는 흡수량 예측부; 및 예측된 상기 양액 흡수량을 기초로 상기 작물에 공급할 양액의 성분량에 관한 양액 가이드 정보를 제공하는 정보제공부를 포함하는 것을 특징으로 한다.이를 통해 작물의 생장환경, 생장단계, 및 작물의 상태에 맞춤화된 양액 조성과 관수량에 관한 가이드 정보를 제공함으로써 작물 생장을 촉진하고, 과다 공급으로 인한 비용 증대 및 환경오염 문제를 효과적으로 방지할 수 있다. claims: 작물이 생육되는 생육환경 정보를 센싱하는 환경센싱부;상기 작물의 생육환경과 상기 작물이 양액을 흡수하는 양액 흡수량 간의 상관관계를 규정한 양액흡수모델을 저장하는 양액모델 저장부;상기 생육환경 정보와 상기 양액흡수모델을 기초로 상기 생육환경에서 상기 작물이 흡수하는 양액 흡수량을 예측하는 흡수량 예측부; 및예측된 상기 양액 흡수량을 기초로 상기 작물에 공급할 양액의 성분량에 관한 양액 가이드 정보를 제공하는 정보제공부를 포함하는 것을 특징으로 하는 스마트 작물 재배 관리장치.작물의 재배를 관리하기 위한 작물 재배 관리장치를 통하여 수행되는 작물 재배 관리방법에 있어서,작물의 생육환경과 상기 작물이 양액을 흡수하는 양액 흡수량 간의 상관관계를 규정한 양액흡수모델을 저장하는 단계;작물이 생육되는 생육환경 정보를 센싱하는 단계;상기 생육환경 정보와 상기 양액흡수모델을 기초로 상기 생육환경에서 상기 작물이 흡수하는 양액 흡수량을 예측하는 단계; 및 예측된 상기 양액 흡수량을 기초로 상기 작물에 공급할 양액의 성분량에 관한 양액 가이드 정보를 제공하는 단계를 포함하는 것을 특징으로 하는 작물 재배 관리방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

720/1059 Row 720: application_number: 1020190170923, combined_string: invention_title: 농업용 무인 비행체 서비스 시스템 및 그 서비스 방법 abstract: 본 발명은 농업용 무인 비행체 서비스 시스템 및 그 서비스 방법으로, 본 발명의 일 실시예에 따른 무인 비행체 서비스 시스템은, 소정의 지역을 비행하여 해당 지역에 대한 정보 수집 또는 방제 임무를 수행하는 무인 비행체; 상기 무인 비행체와 무선통신망을 통해 통신하며, 상기 무인 비행체를 제어하고, 상기 무인 비행체에서 수집된 정보를 저장하는 서비스 서버; 및 상기 무인 비행체를 유지 및 관리하고 대상 지역의 측량 및 항법위성의 지상국 서비스를 제공하는 드론 기지국; 상기 서비스 서버는, 웹서비스를 통해 사용자의 서비스 요청을 접수하고, 이를 분석하여 상기 무인 비행체에 임무를 전송하며, 수집된 정보 및 수행된 임무 내용을 사용자 단말기에 제공할 수 있다. 본 발명에 의하면, 드론과 같은 무인 비행체를 무선통신망을 통해 누구나 무인 비행체를 이용하여 농업에 이용할 수 있어, 다양한 정보를 수집 및 분석하고, 수집 및 분석된 정보를 농업에 활용함으로써, 농업생산성을 극대화할 수 있는 효과가 있다. claims: 소정의 지역을 비행하여 해당 지역에 대한 정보 수집 또는 방제 임무를 수행하는 무인 비행체;상기 무인 비행체와 무선통신망을 통해 통신하며, 상기 무인 비행체를 제어하고, 상기 무인 비행체에서 수집된 정보를 저장하는 서비스 서버; 및상기 무인 비행체를 유지 및 관리하고, 대상 지역의 측량 및 항법위성의 지상국 서비스를 제공하는 드론 기지국을 포함하며,상기 서비스 서버는,웹서비스를 통해 사용자의 서비스 요청을 접수하고, 이를 분석하여 상기 무인 비행체에 임무를 전송하며, 상기 수집된 정보 및 수행된 임무 내용을 사용자 단말기에 제공하며,상기 수집된 정보를 근거로 농작물의 건강상태, 질병 유무 및 분포에 대한 정보와, 토양상태 및 토양의 수분 함량을 분석하며, 해당 지역의 관개나 농작물의 수정시기 및 농작물의 수확시기를 예측하며,빅데이터 분석을 통해 미리 설정된 기간 동안의 평균적인 농작물의 상태 및 해당 지역의 기후 변화에 대한 정보를 상기 사용자 단말기에 제공하며,상기 무인 비행체는,항법센서, 방위센서, 고도센서, 자이로센서, 속도센서 및 근접센서 중 하나 이상을 포함하는 센서부;상기 해당 지역을 촬영하기 위한 한 종류 이상의 카메라를 포함하는 촬영부;상기 센서부에서 감지된 정보 및 상기 촬영부에서 촬영된 데이터를 저장하는 메모리부;상기 서비스 서버와 무선 통신하는 통신부; 및상기 서비스 서버 측에서 수신된 제어 신호에 따라 상기 해당 지역을 비행하도록 제어하고, 상기 센서부, 상기 촬영부, 상기 메모리부 및 상기 통신부를 제어하는 제어부를 포함하며,상기 촬영부에 포함된 카메라는,해당 지역의 농작물 성장 상태에 따라 각기 다른 음영이나 색체로 표현되는 영상을 촬영하는 적외선 카메라 및, 해당 지역의 농작물의 병충해 여부 및 가뭄 상태를 확인할 수 있는 영상을 촬영하는 멀티 스펙트럼 카메라 중 어느 하나 이상을 포함하며,상기 서비스 서버는,상기 사용자 단말기가 접속하여 서비스를 신청하고, 상기 사용자 단말기에 정보를 제공하는 웹 관리부;상기 무인 비행체의 비행 모드를 고정익 또는 가변익으로 설정하여 상기 무인 비행체의 비행을 제어하는 무인 비행체 제어부;상기 무인 비행체에서 수집된 정보를 분석하는 분석부; 및상기 분석부에서 정보화된 정보를 상기 사용자 단말기로 제공하기 위한 정보로 재생산하는 클라우드부를 포함하며,상기 클라우드부는,상기 무인 비행체를 통해 수집된 정보가 누적될 때, 상기 누적된 정보에 대한 빅데이터 분석을 통해 상기 미리 설정된 기간 동안의 평균적인 농작물의 상태 및 해당 지역의 기후 변화에 대한 정보를 상기 사용자 단말기에 제공하는 클라우드 서버부;상기 분석부에서 정보화된 정보를 디렉토리 구조로 계측화하여 저장하는 블록 스토리지부; 및상기 사용자 단말기의 계정 단위로 파일이나 데이터를 저장하며, 그림이나 영상 또는 문서와 같이 형태와 구조가 다른 구조화되지 않은 비정형 데이터에 대해 메타데이터를 자동으로 생성하여 관리하는 오브젝트 스토리지부를 포함하고,상기 드론 기지국은, 상기 무인 비행체 및 상기 서비스 서버와 각각 통신하고, 상기 서비스 서버에서 송출된 제어신호를 상기 무인 비행체에 전송하고, 상기 무인 비행체에서 전송된 신호를 상기 서비스 서버로 전송하는 무인 비행체 서비스 시스템.제1항에 기재된 무인 비행체 서비스 시스템을 이용한 무인 비행체 서비스 방법이고,사용자 단말기에서 서비스 서버로, 무선통신망을 통해 무인 비행체 서비스에 대한 신청이 이루어지는 단계;상기 사용자 단말기에서 신청된 지역에 대한 정보 수집 또는 방제 임무를 수행하기 위해 해당 지역을 비행하는 무인 비행체에 무선통신망을 통해 상기 서비스 서버에서 제어 명령을 전송하는 단계;상기 무인 비행체에서 상기 신청 지역에 대한 정보 수집 또는 방제 임무를 수행하는 단계;상기 무인 비행체에서 수집된 정보 또는 방제 임무 수행 결과를 무선통신망을 통해 상기 서비스 서버로 전송하는 단계; 및상기 서비스 서버로 전송된 상기 수집된 정보가 상기 사용자 단말기에서 확인할 수 있게 분석 및 저장되는 단계를 포함하며,상기 분석 및 저장되는 단계는,상기 수집된 정보를 근거로 농작물의 건강상태, 질병 유무 및 분포에 대한 정보와, 토양상태 및 토양의 수분 함량을 분석하며, 해당 지역의 관개나 농작물의 수정시기 및 농작물의 수확시기를 예측하는 과정; 및빅데이터 분석을 통해 미리 설정된 기간 동안의 평균적인 농작물의 상태 및 해당 지역의 기후 변화에 대한 정보를 상기 사용자 단말기에 제공하는 과정을 포함하며,상기 서비스 서버에서 상기 무인 비행체로 전송되는 명령은, 상기 무인 비행체를 유지 관리하고, 해당 지역의 측량 및 정밀 GPS 지상국 서비스를 운용하는 드론 기지국을 통해 전송되는 무인 비행체 서비스 방법., Ltext: 농업, prediction: 농업
721/1059 Row 721: application_number: 1020190169213, combined_string: invention_title: 스마트팜 데이터 생육연동시스템 abstract: 스마트팜 데이터 생육연동시스템(1)은 미리 설정된 각각의 물리적 통신방식으로 식물의 생장에 관련된 데이터를 수집하는 복수의 내부 통신망과, 데이터 수집을 위해 외부 인터넷 접속을 위한 외부 통신망 사이의 인터페이스 역할을 수행하는 데이터 로거를 포함하는 재배장비 데이터 시스템과, 재배장비 데이터 시스템과 연결되며, 식물의 상태를 모니터링하면서 시계열 모니터링 데이터를 기반으로 생육상태를 자동분석하는 재배영상 데이터 시스템과, 재배장비 데이터 시스템 및 재배영상 데이터 시스템으로부터 데이터를 제공받아 재배장비 데이터 시스템 및 재배영상 데이터 시스템을 제어하는 복합제어시스템을 포함하는 것을 특징으로 한다. claims: 미리 설정된 각각의 물리적 통신방식으로 식물의 생장에 관련된 데이터를 수집하는 복수의 내부 통신망과, 데이터 수집을 위해 외부 인터넷 접속을 위한 외부 통신망 사이의 인터페이스 역할을 수행하는 데이터 로거를 포함하는 재배장비 데이터 시스템; 및상기 재배장비 데이터 시스템과 연결되며, 상기 식물의 상태를 모니터링하면서 시계열 모니터링 데이터를 기반으로 생육상태를 자동분석하는 재배영상 데이터 시스템; 및상기 재배장비 데이터 시스템 및 상기 재배영상 데이터 시스템으로부터 데이터를 제공받아 상기 재배장비 데이터 시스템 및 상기 재배영상 데이터 시스템을 제어하는 복합제어시스템;을 포함하는 스마트팜 데이터 생육연동시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

722/1059 Row 722: application_number: 1020190168130, combined_string: invention_title: 약용작물 재배용 스마트 팜 시스템 abstract: 본 발명은 고부가가치의 약용작물을 재배하도록 재배실의 환경정보를 수집하고 환경조성수단을 이용하여 재배실의 생장조건을 최적으로 조성하여 다양한 약용작물을 재배하는 스마트 팜 시스템에 관한 발명이고, 생장중인 약용작물의 생장을 촉진시키도록 약용작물의 생장시기별로 적합하게 온도, 습도, 통풍을 조절하고, 약용작물별 양분과 수분이 토양에 적절하게 공급되도록 하는 스마트 팜 시스템에 관한발명이며, 약용작물에 대한 생장 시기별 환경정보를 분류 저장하여 약용작물별 최적 생장환경 빅 데이터를 생성하는 스마트 팜 시스템에 관한 발명에 관한 것이다. claims: 약용작물 재배용 스마트 팜 시스템에 있어서,약용작물을 재배하기 위한 실내공간이 형성되고, 약용작물의 생장을 위해 필요한 재배 시설물(110)들이 설치되는 재배실(100)과;상기 재배실(100)의 실내공간에 설치되어, 약용작물 재배에 필요한 환경을 조성하는 환경조성수단(200)과;상기 재배실(100)의 실내공간에 설치되어, 재배실(100)의 환경 상태를 감지하여 환경정보를 생성하고, 재배실(100) 내부를 촬영한 모니터링용 영상정보를 생성하고, 생성된 환경정보, 영상정보를 관리서버(400)로 전송하는 환경수집수단(300)과;상기 환경수집수단(300)이 전송한 환경정보를 이용하여 재배실(100)의 실내공간이 약용작물 재배에 적합한 환경이 되도록 환경조성수단(200)을 제어하고, 환경수집수단(300)이 전송한 영상정보를 모니터링 화면에 표시하여 사용자가 재배실(100) 내부를 모니터링 할 수 있도록 하고, 환경수집수단(300)이 전송한 환경정보를 이용하여 약용작물별 최적 생장환경 데이터를 생성하는 관리서버(400)를 포함하는 것을 특징으로 하는 약용작물재배용 스마트 팜 시스템., Ltext: 농업, prediction: 농업
723/1059 Row 723: application_number: 1020190166912, combined_string: invention_title: 기능성 성분이 증진된 밀싹의 제조방법 abstract: 본 발명은 밀싹을 저온처리하는 단계를 포함하는 기능성 성분이 증진된 밀싹의 제조방법, 상기 방법으로 제조되어 기능성 성분이 증진된 밀싹, 상기 밀싹을 포함하는 식품조성물 및 사료조성물에 관한 것이다. 본 발명에서 제공하는 방법에 의하면, 밀싹의 제조시 특별한 성분을 처리하는 과정 없이도, 밀싹에 포함된 다양한 기능성 성분의 함량을 증진시킬 수 있으므로, 높은 품질의 밀 재배에 널리 활용될 수 있을 것이다. claims: (a) 밀의 종자를 발아시켜서 밀싹을 수득하는 단계; (b) 발아된 밀싹을 저온처리하는 단계; 및, (c) 저온처리된 밀싹을 재배하는 단계를 포함하는, 기능성 성분이 증진된 밀싹의 제조방법.제1항 내지 제5항 중 어느 한 항의 방법으로 제조되어, 기능성 성분이 증진된 밀싹.제6항의 기능성 성분이 증진된 밀싹을 포함하는 식품조성물.제6항의 기능성 성분이 증진된 밀싹을 포함하는 사료조성물., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

724/1059 Row 724: application_number: 1020190165843, combined_string: invention_title: 광추적 시뮬레이션을 이용한 작물의 광합성 속도 분포 계산 장치 및 그 방법 abstract: 본 발명은 광추적 시뮬레이션을 이용한 작물의 광합성 속도 분포 계산 장치 및 그 방법에 관한 것으로, 광합성 속도 분포 계산 장치는 입력받은 작물의 3차원 모델에 광추적 시뮬레이션을 수행하여 작물 표면의 수광 분포를 산출하는 수광 시뮬레이션부, 수집한 작물의 광합성 실측값에 기초하여 광합성 속도 계산 모델을 통해 광합성 속도를 연산하는 광합성 연산부, 그리고 연산된 광합성 속도 계산 모델과 작물 표면의 수광 분포를 이용하여 작물의 수관 위치별 광합성 속도 분포를 제공하는 제어부를 포함한다. claims: 입력받은 작물의 3차원 모델에 광추적 시뮬레이션을 수행하여 작물 표면의 수광 분포를 산출하는 수광 시뮬레이션부, 수집한 상기 작물의 광합성 실측값에 기초하여 광합성 속도 계산 모델을 통해 광합성 속도를 연산하는 광합성 연산부, 그리고 연산된 상기 광합성 속도 계산 모델과 상기 작물 표면의 수광 분포를 이용하여 상기 작물의 수관 위치별 광합성 속도 분포를 제공하는 제어부, 를 포함하는 광합성 속도 분포 계산 장치.입력받은 작물의 성장 단계에 따른 하나 이상의 3차원 모델을 생성하는 단계, 상기 3차원 모델에 광추적 시뮬레이션을 수행하는 작물 표면의 수광 분포를 산출하는 단계, 상기 작물의 수직 위치별, 성장 단계별 중에서 하나 이상의 광합성 실측 값을 수집하는 단계, 상기 작물의 광합성 실측값에 기초하여 광합성 속도 계산 모델을 통해 광합성 속도를 연산하는 단계, 그리고 연산된 상기 광합성 속도 계산 모델과 상기 작물 표면의 수광 분포를 이용하여 상기 작물의 수관 위치별 광합성 속도 분포를 산출하고 제공하는 단계 를 포함하는 광합성 속도 분포 계산 장치의 광합성 속도 계산 방법., Ltext: 농업, prediction: 농업
725/1059 Row 725: application_number: 1020190161961, combined_string: invention_title: 축산용 포유 방지기 abstract: 본 발명은, 아기 가축의 코에 끼워지며 사용자의 쥠동작에 따라 개방되고, 사용자의 해제 동작에 의해 폐쇄되는 이루어지는 코걸림부; 상기 코걸림부의 대향하는 위치에 형성되며, 사용자의 그립 동작에 따라 상기 코걸림부를 개방폐쇄시키는 손잡이부; 및 상기 손잡이부에 형성된 다수의 돌출핀을 포함하는 포유 방지부를 포함하는, 축산용 포유 방지기에 관한 것이다. claims: 아기 가축의 코에 끼워지며 사용자의 쥠동작에 따라 개방되고, 사용자의 해제동작에 의한 복원 탄성력에 의해 자동 폐쇄되도록 이루어지는 코걸림부;상기 코걸림부의 대향하는 위치에 형성되며, 사용자의 그립 동작에 따라 상기 코걸림부를 개방 폐쇄시키는 손잡이부; 상기 손잡이부와 일체로 형성되며 다수의 돌출핀을 포함하는 포유 방지부;상기 코걸림부의 제 1 부와 상기 손잡이부의 제 1 부를 이루는 제 1 본체부;상기 코걸림부의 제 2 부와 상기 손잡이부의 제 2부를 이루는 제 2 본체부;상기 제 1 본체부와 상기 제 2 본체부의 중간에서 회전가능하게 결합시키는 피봇; 및 상기 피봇에 설치되며 상기 손잡이에서의 상기 사용자의 쥠동작시 상기 복원 탄성력을 부여하는 탄성 스프링을 포함하고,상기 제 1 본체부와 상기 제 2 본체부는 X자로 결합되며,상기 제 1 본체부 및 상기 제 2 본체부의 각각의 결합부에는 결합홀이 형성되어서, 상기 피봇이 상기 결합홀에 체결되는, 축산용 포유 방지기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

726/1059 Row 726: application_number: 1020190159920, combined_string: invention_title: 영상 이미지를 이용한 작물 성장 진단 시스템 및 방법 abstract: 본 발명은 영상 이미지를 이용한 작물 성장 진단 시스템에 있어서, 상기 작물이 촬영된 상기 영상 이미지로부터 상기 작물의 크기 정보를 산출하는 영상 처리부; 상기 크기 정보 및 상기 작물의 무게 정보를 저장하는 데이터 베이스부; 및 상기 크기 정보와 상기 무게 정보의 관계를 분석하여 관계 모델을 산출하는 관계 모델 생성부를 포함하여 작물을 촬영한 이미지만으로 작물의 크기 및 무게 정보를 산출할 수 있고, 현재 성장 단계를 진단 및 예측하는 것이 가능한 것을 특징으로 한다. claims: 영상 이미지를 이용한 작물 성장 진단 시스템에 있어서,상기 작물이 촬영된 상기 영상 이미지로부터 상기 작물의 크기 정보를 산출하는 영상 처리부;상기 크기 정보 및 상기 작물의 무게 정보를 저장하는 데이터 베이스부; 및상기 크기 정보와 상기 무게 정보의 관계를 분석하여 관계 모델을 산출하는 관계 모델 생성부를 포함하는 것을 특징으로 하는 작물 성장 진단 시스템.영상 이미지를 이용한 작물 성장 진단 방법에 있어서,(a)복수개 작물의 크기 및 무게 데이터를 저장하며, 기 저장된 데이터로 작물의 크기와 무게의 관계를 다중회귀 분석하여 다중회귀 모델을 산출하는 관계 모델 생성단계;(b)조사대상 작물을 촬영하여 영상 이미지를 생성하는 촬영 단계;(c)상기 영상 이미지를 전처리하고 푸리에 변환하는 이미지 처리 단계;(d)변환된 상기 영상 이미지로부터 상기 작물의 크기 정보를 산출하는 산출 단계;(e)상기 크기 정보를 상기 다중회귀 모델에 입력하여 상기 조사대상 작물의 크기 정보에 대한 무게 정보를 산출하는 출력 단계;를 포함하는 것을 특징으로 하는 성장 작물 성장 진단 방법., Ltext: 농업, prediction: 농업
727/1059 Row 727: application_number: 1020190156664, combined_string: invention_title: 디지털 트윈을 이용한 온라인 수직농장 경영 시스템 abstract: 본 발명에 따른 디지털 트윈을 이용한 온라인 수직농장 경영 시스템은,온라인을 통한 수직농장 경영 시스템으로서, 특정 작물을 재배하기 위해 층별로 구획 처리된 수직농장; 상기한 각 층을 유저에게 분양하고 분양에 대한 대가를 받는 분양 모듈; 작물 경작에 필요한 이론적 경작 정보를 각 작물 별로 유저에게 제공하는 경작 정보 제공 모듈; 유저로부터 작물 재배를 위한 조작 행위를 입력받는 조작부, 상기 입력부를 통해 입력받은 정보를 경작 명령 정보로 저장하는 저장 처리부, 실제 작물의 건강 상태와 성장 현황 및 수직농장의 현재 온, 습도를 입력받아 데이터베이스에 저장하고 가상 농장에 반영하는 생장 데이터 저장부를 포함한 게임 컨트롤 모듈; 센서를 통해 수집한 정보를 처리해 층별 환경 정보 및 작물 상태 정보를 생성, 전달하는 종합 정보 처리부, 수집 및 처리된 모든 상태 정보를 저장하는 데이터베이스; 상기 경작 명령 정보 및 수직농장의 물, 비료, 종자 재고 현황을 파악하여 관리인에게 관리 명령을 내리거나, 유저가 시스템에 대해 오프라인 상태이거나 자동 경작 명령을 내렸을 경우 당시까지의 데이터를 기반으로 자동 경작 시스템을 구동시키는 수직농장 관리 서버;로 구성된 것을 특징으로 한다. claims: 온라인을 통한 수직농장 경영 시스템으로서,특정 작물을 재배하기 위해 층별로 구획 처리된 수직농장;상기한 각 층을 유저에게 분양하고 분양에 대한 대가를 받는 분양 모듈;작물 경작에 필요한 이론적 경작 정보를 각 작물 별로 유저에게 제공하는 경작 정보 제공 모듈;유저로부터 작물 재배를 위한 조작 행위를 입력받는 조작부, 상기 입력부를 통해 입력받은 정보를 경작 명령 정보로 저장하는 저장 처리부, 실제 작물의 건강 상태와 성장 현황 및 수직농장의 현재 온, 습도를 입력받아 데이터베이스에 저장하고 가상 농장에 반영하는 생장 데이터 저장부를 포함한 게임 컨트롤 모듈;센서를 통해 수집한 정보를 처리해 층별 환경 정보 및 작물 상태 정보를 생성, 전달하는 종합 정보 처리부, 수집 및 처리된 모든 상태 정보를 저장하는 데이터베이스;상기 경작 명령 정보 및 수직농장의 물, 비료, 종자 재고 현황을 파악하여 관리인에게 관리 명령을 내리거나, 유저가 시스템에 대해 오프라인 상태이거나 자동 경작 명령을 내렸을 경우 당시까지의 데이터를 기반으로 자동 경작 시스템을 구동시키는 수직농장 관리 서버;로 구성된 것을 특징으로 하는 온라인 수직농장 경영 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

728/1059 Row 728: application_number: 1020190156728, combined_string: invention_title: 축산시설 공기정화 시스템 abstract: 본 발명은 축산시설 공기정화 시스템에 관한 것으로서, 축산시설 내부에서 발생하는 각종 분진 및 악취를 대기중에 배출시키지 않고 공기를 정화하여 재사용할 수 있는 축산시설 공기정화 시스템을 제공하는 것이다.본 발명은 축사로부터 오염된 공기를 수집하여 분진을 제거하는 것으로, 사이클론을 포함하는 분진제거부; 상기 분진제거부를 통해 분진이 제거된 공기에서 습식 세정방식에 의해 악취를 제어하는 것으로, 산성의 세정액으로 악취를 제거하는 세정부와, 염기성 중화액으로 공기중에 함유된 산성 미립자를 중화시키는 중화부를 포함하는 악취제거부;를 포함하여 구성되는 것을 특징으로 한다.또한, 상기 분진제거부는 입자가 큰 분진을 분류하는 사이클론과, 상기 사이클론에서 분류되지 않은 미세분진을 분류하는 백필터집진기를 포함하여 구성되는 것을 특징으로 한다.또한, 상기 중화액은 피톤치드 성분을 포함하는 것을 특징으로 한다. claims: 축사(10) 내부의 오염된 공기를 수집 정화하여 재공급하는 축산시설 공기정화 시스템에 있어서,축사(10)로부터 오염된 공기를 수집하여 분진을 제거하는 것으로, 사이클론(110)을 포함하는 분진제거부(100);상기 분진제거부(100)를 통해 분진이 제거된 공기에서 습식 세정방식에 의해 악취를 제어하는 것으로, 산성의 세정액으로 악취를 제거하는 세정부(210)와, 염기성 중화액으로 공기중에 함유된 산성 미립자를 중화시키는 중화부(220)를 포함하는 악취제거부(200);를 포함하여 구성된 것을 특징으로 하는 축산시설 공기정화 시스템., Ltext: 농업, prediction: 임업
729/1059 Row 729: application_number: 1020190157546, combined_string: invention_title: 가정용 작물재배 장치 abstract: 본 명세서에 개시된 내용은 일반 가정에서 직접 작물을 재배 및 섭취할 수 있음은 물론 인삼과 같은 특용 작물의 생육원리와 재배 과정을 체험할 수 있는 자연친화적 교구로 활용할 수 있는 개량된 가정용 작물재배 장치에 관한 것이며, 전방 수납부와 후방 지지부를 포함하는 로어 베이스; 다수의 조작버튼을 포함하는 제어부와 엘이디 모듈을 포함하며, 상기 로어 베이스의 상부에 형성되는 어퍼 다이; 상기 어퍼 다이의 저면에 인접하게 설치되고, 상기 엘이디 모듈로부터 제공되는 빛을 선택적으로 굴절 및 분산시키는 차양기; 다수의 재배포트를 구비하며, 상기 전방 수납부로부터 인출가능하게 설치되는 베드; 및 상기 어퍼 다이 일측에 형성되는 손잡이부를 포함하여 구성된다. claims: 전방 수납부와 후방 지지부를 포함하는 로어 베이스;다수의 조작버튼을 포함하는 제어부와 엘이디 모듈을 포함하며, 상기 로어 베이스의 상부에 형성되는 어퍼 다이;상기 어퍼 다이의 저면에 인접하게 설치되고, 상기 엘이디 모듈로부터 제공되는 빛을 선택적으로 굴절 및 분산시키는 차양기;다수의 재배포트를 구비하며, 상기 전방 수납부로부터 인출가능하게 설치되는 베드; 및상기 어퍼 다이 일측에 형성되는 손잡이부를 포함하여 구성되는 것을 특징으로 하는 가정용 작물재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

730/1059 Row 730: application_number: 1020190155876, combined_string: invention_title: 농작물의 출하예상가격 산출 시스템 및 방법 abstract: 본 발명은 농작물의 출하예상가격 산출 시스템 및 방법을 제공한다. 상기 농작물 출하예상가격 산출 시스템은, 사용자 단말기를 통해 재배지역, 재배면적, 재배작물 및 재배시기를 입력 받는 인터페이스부, 날씨정보 제공 서버로부터 특정 기간의 날씨정보를 수신하고, 농작물 정보 제공 서버로부터 해당 작물의 수매가격 또는 경매가격에 관한 정보를 수신하는 통신부, 및 특정 작물에 대한 날씨 매칭률 및 재배면적에 대한 정보를 기초로 표준시세를 산출하는 표준시세 산출부를 포함한다. claims: 사용자 단말기를 통해 재배지역, 재배면적, 재배작물 및 재배시기를 입력 받는 인터페이스부; 날씨정보 제공 서버로부터 특정 기간의 날씨정보를 수신하고, 농작물 정보 제공 서버로부터 해당 작물의 수매가격 또는 경매가격에 관한 정보를 수신하는 통신부; 및특정 작물에 대한 날씨 매칭률 및 재배면적에 대한 정보를 기초로 표준시세를 산출하는 표준시세 산출부를 포함하는농작물 출하예상가격 산출 시스템.사용자 단말기를 통해 재배지역, 재배면적, 재배작물 및 재배시기에 대한 데이터를 수신하는 단계; 입력된 상기 재배작물과 상기 재배시기를 기초로 출하시기를 계산하는 단계; 날씨정보 제공 서버로부터 수신된 날씨에 대한 데이터와, 상기 재배지역, 및 상기 재배면적을 기초로 재배작물에 대한 예상 수확량을 산출하는 단계; 농작물 정보 제공 서버로부터 수신된 재배작물의 과거 수확량 및 과거 가격에 대한 데이터를 기초로 수확량과 작물가격에 대한 관계도를 산출하는 단계; 및 산출된 관계도를 기초로 재배작물의 예상 수확량에 따른 표준시세를 계산하는 단계를 포함하는 농작물 출하예상가격 산출 방법.사용자 단말기를 통해 재배지역, 재배면적, 재배작물 및 재배시기에 대한 데이터를 수신하는 단계;상기 재배작물의 최적날씨정보와 상기 날씨정보 사이의 매칭률을 기초로 제1 스코어로 산출하는 단계;상기 재배면적과 미리 정해진 기준면적 간의 차이를 기초로 제2 스코어를 산출하는 단계;상기 재배면적과 상기 재배작물의 전체재배면적 간의 비율을 기초로 제3 스코어를 산출하는 단계; 및,상기 재배작물의 기준가격과 상기 제1 내지 제3 스코어를 기초로 상기 표준시세를 산출하는 단계를 포함하는농작물 출하예상가격 산출 방법., Ltext: 농업, prediction: 농업
731/1059 Row 731: application_number: 1020190155885, combined_string: invention_title: 농작물 추천 정보 제공 시스템 및 방법 abstract: 본 발명은 농작물 추천 정보 제공 시스템 및 방법을 제공한다. 상기 농작물 추천 정보 제공 시스템은, 사용자 단말기를 통해 작물 재배를 위한 지역, 면적, 지난 재배작물 또는 생산시기를 입력 받는 인터페이스부, 날씨정보 제공 서버로부터 특정 기간의 날씨정보를 수신하고, 농작물 정보 제공 서버로부터 각 작물의 수입량, 수매가격 및 저장도에 관한 정보를 수신하는 통신부, 수신된 상기 날씨정보, 상기 수입량, 상기 수매가격 및 상기 저장도에 대한 정보를 기초로, 각 작물에 대한 스코어를 계산하는 스코어 계산부, 및 상기 스코어 계산부에서 계산한 각 작물에 대한 스코어에 가중치를 부여하고, 가장 높은 스코어를 지닌 작물을 추천작물로 선정하는 추천작물 선정부를 포함한다. claims: 사용자 단말기를 통해 작물 재배를 위한 지역, 면적, 지난 재배작물 또는 생산시기를 입력 받는 인터페이스부; 날씨정보 제공 서버로부터 특정 기간의 날씨정보를 수신하고, 농작물 정보 제공 서버로부터 각 작물의 수입량, 수매가격 및 저장도에 관한 정보를 수신하는 통신부; 수신된 상기 날씨정보, 상기 수입량, 상기 수매가격 및 상기 저장도에 대한 정보를 기초로, 각 작물에 대한 스코어를 계산하는 스코어 계산부; 및 상기 스코어 계산부에서 계산한 각 작물에 대한 스코어에 가중치를 부여하고, 가장 높은 스코어를 지닌 작물을 추천작물로 선정하는 추천작물 선정부를 포함하는농산물 추천 정보 제공 시스템.날씨정보 제공 서버로부터 수신된 날씨정보와 각 작물의 최적날씨정보 사이의 날씨매칭률을 기초로 제1 스코어를 산출하는 단계; 농작물 정보 제공 서버로부터 수신된 수입량을 기초로, 각 작물의 제2 스코어를 산출하는 단계; 상기 농작물 정보 제공 서버로부터 수신된 수매가격을 기초로, 각 작물의 제3 스코어를 산출하는 단계; 상기 농작물 정보 제공 서버로부터 수신된 저장도를 기초로 각 작물의 제4 스코어를 계산하는 단계; 및 상기 제1 내지 제4 스코어에 각각의 하고, 가장 높은 스코어를 지닌된 작물을 추천작물로 선정하는 단계를 포함하는 농산물 추천 정보 제공 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

732/1059 Row 732: application_number: 1020190153206, combined_string: invention_title: 식물공장 대여 시스템 abstract: 본 발명은 식물공장 시스템에 관한 것으로, 보다 상세하게는 작물을 선택할 수 있는 작물선택, 상기 작물선택의 현황을 볼 수 있는 마이페이지,그리고, 현재 생장 시키고 있는 작물을 확인하며 관리할 수 있는 농장,상기에서 발생하는 문제점을 질문하는 문의, 상기 내 농장에서 키우고 있는 작물에게 필요한 물품을 구매할 수 있는 상점을 포함하고 있는 식물공장 대여 시스템 claims: 작물을 선택할 수 있는 작물선택;상기 작물선택의 현황을 볼 수 있는 마이페이지; 그리고, 현재 생장 시키고 있는 작물을 확인하며 관리할 수 있는 내 농장 ;상기에서 발생하는 문제점을 질문하는 문의상기 내 농장에서 키우고 있는 작물에게 필요한 물품을 구매할 수 있는 상점;을 포함하고 있는 식물공장 대여 시스템, Ltext: 농업, prediction: 농업
733/1059 Row 733: application_number: 1020190151000, combined_string: invention_title: 시스템 에어 환경 조절 장치 abstract: 본 발명은 실내 환경 조절 장치에 관한 것으로서, 기후조건과 재배작물의 종류를 고려하여 그룹화함으로써 우수한 재배작물의 정보를 서로 공유하는 실내 환경 조절 장치에 관한 것이다. 이를 위해 재배작물의 생육을 제어하도록 각 재배지에 설치 운용되며, 설치된 재배지의 기후조건 정보와 그룹핑된 재배작물의 생육데이터 정보를 상위단으로 전송하는 서브 제어기, 및 각각의 서브 제어기에서 전송된 재배지의 기후조건 정보와 재배작물의 생육데이터 정보를 취합하여 각 지역별로 데이터를 그룹핑하고, 서브 제어기의 정보 요청 메시지에 따라 조건에 맞는 재배작물의 생육데이터 정보를 서브 제어기로 전송하는 주 제어기를 포함하는 것을 특징으로 하는 실내 환경 조절 장치가 개시된다. claims: 실내의 에어 환경 조절을 통해 축산물 또는 재배작물의 생육을 제어하도록 각 생육지에 설치 운용되는 서브 제어기, 및각각의 서브 제어기에서 전송된 축산물 또는 재배작물의 생육데이터 정보를 취합하여 지역별로 데이터를 그룹화하고, 상기 서브 제어기의 정보 요청 메시지에 따라 조건에 맞는 상기 생육데이터 정보를 상기 서브 제어기로 전송하는 주 제어기를 포함하는 것을 특징으로 하는 시스템 에어 환경 조절 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

734/1059 Row 734: application_number: 1020210140795, combined_string: invention_title: 가축의 반추위를 모니터링하는 장치 및 방법 abstract: 가축의 반추위에 삽입된 센서 장치로부터 움직임 데이터를 수집하여 가축의 활동을 분석하고, 활동 정보를 이용하여 가축의 건강 및 질병 관리 정보를 모니터링하는 장치 및 방법에 관한 것이다. 본 발명에 따라 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 장치는, 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하는 데이터 센싱부; 수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 활동 분석부; 및 분석된 활동 정보를 저장하고, 활동 정보가 분석되지 않는 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 모니터링부를 포함한다. claims: 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 장치에 있어서, 상기 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하는 데이터 센싱부; 수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 활동 분석부; 및 분석된 활동 정보를 저장하고, 상기 활동 정보의 분석에 따른 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 모니터링부를 포함하고, 상기 모니터링부는 상기 활동분석부에서 분석된 섭취 활동, 반추 활동 및 휴식 활동을 기 누적 저장된 개체별 및 품종별 패턴 정보와 비교하여 섭취 활동, 반추 활동 및 휴식 활동의 어느 부분에서 문제가 있는지를 관리자에게 통보할 수 있는 것을 특징으로 하는 장치.장치가 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 방법에 있어서, 상기 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하여 센싱하는 단계; 수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 단계; 및 분석된 활동 정보를 저장하고, 상기 활동 정보의 분석에 따른 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 단계를 포함하고, 상기 분석된 섭취 활동, 반추 활동 및 휴식 활동을 기 누적 저장된 개체별 및 품종별 패턴 정보와 비교하여 섭취 활동, 반추 활동 및 휴식 활동의 어느 부분에서 문제가 있는지를 관리자에게 통보할 수 있는 것을 특징으로 하는 방법., Ltext: 농업, prediction: 임업
735/1059 Row 735: application_number: 1020210030455, combined_string: invention_title: 가축 건강상태 면역 지표화 시스템 abstract: 본 발명은 가축 건강상태 면역 지표화 시스템에 관한 것으로서, 보다 구체적으로는 축산농가에서 수집된 데이터를 이용해 가축의 건강상태를 나타내는 면역 관련 지표를 선정하여 가축의 건강상태를 면역 지표화하는, 가축 건강상태 면역 지표화 시스템으로서, 복수의 축산농가에서 수집된 데이터를 저장하는 데이터베이스부; 가축 건강상태와 관련된 변수 중에서 면역학적 건강 정도를 나타내는 후보 지표를 도출하는 후보 도출부; 상기 데이터베이스부에 저장된 검체 정보를 이용해, 상기 후보 지표의 상태 값을 분석하는 데이터 분석부; 상기 후보 지표의 상태 값과 다른 기존 지표 사이의 연관성을 분석하는 연관성 분석부; 상기 연관성 분석 결과 상기 후보 지표를 새로운 지표로 선정할지 결정하는 선정 결정부; 및 상기 선정 결정부에서 선정된 새로운 지표를 평가하되, 가축의 건강상태를 나타내는 정도를 평가하는 지표 평가부; 및 평가 대상 농가에서 수집된 상기 새로운 지표와 관련된 검체 정보를 이용해 상기 평가 대상 농가의 가축의 면역력을 포함하는 건강상태를 추정하는 농가 평가부를 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 가축 건강상태 면역 지표화 시스템에 따르면, 가축 건강상태와 관련된 변수 중에서 면역학적 건강 정도를 나타내는 후보 지표를 도출해, 실제 축산농가에서 수집된 데이터를 이용해 후보 지표의 상태 값을 분석하고, 다른 기존 지표와의 연관성을 분석해 새로운 지표로 선정하고 평가함으로써, 실제 축산농가의 데이터를 이용해 실용성 높은 새로운 지표를 개발 및 확립할 수 있고, 이를 통해 가축의 면역력 정도를 포함하는 건강상태를 쉽고 빠르게 파악하고, 노출 위험성 있는 질병이나 생산성을 예측하여 예방적 수의료 서비스를 위한 가축의 면역력 관리를 할 수 있다. claims: 축산농가에서 수집된 데이터를 이용해 가축의 건강상태를 나타내는 면역 관련 지표를 선정하여 가축의 건강상태를 면역 지표화하는, 가축 건강상태 면역 지표화 시스템(100)으로서,복수의 축산농가에서 수집된 데이터를 저장하는 데이터베이스부(110);가축 건강상태와 관련된 변수 중에서 면역학적 건강 정도를 나타내는 후보 지표를 도출하는 후보 도출부(120);상기 데이터베이스부(110)에 저장된 검체 정보를 이용해, 상기 후보 지표의 상태 값을 분석하는 데이터 분석부(130);상기 후보 지표의 상태 값과 다른 기존 지표 사이의 연관성을 분석하되, 상기 후보 지표의 상태 값과 항체가를 포함하는 기존의 면역지표 및 생리학적 건강 정도를 나타내는 건강 지표와의 연관성을 분석하는 연관성 분석부(140);상기 연관성 분석 결과 상기 후보 지표를 새로운 지표로 선정할지 결정하는 선정 결정부(150); 및상기 선정 결정부(150)에서 선정된 새로운 지표를 평가하되, 가축의 건강상태를 나타내는 정도를 평가하는 지표 평가부(160); 및평가 대상 농가에서 수집된 상기 새로운 지표와 관련된 검체 정보를 이용해 상기 평가 대상 농가의 가축의 면역력을 포함하는 건강상태를 추정하는 농가 평가부(180)를 포함하되,상기 데이터베이스부(110)는, 복수의 축산농가에서 사육하는 가축을 대상으로 수집한 면역 단백질 분석 데이터를 저장하며,상기 후보 지표는, 면역항체 형성력을 나타내는 면역 단백질이며,면역 단백질을 새로운 지표로 선정하여, 예방적 수의료 서비스를 위한 가축의 면역력 관리를 지원하고,상기 연관성 분석부(140)는,면역학적 건강 정도를 나타내는 면역지표인 상기 후보 지표의 상태 값과 생리학적 건강 정도를 나타내는 건강 지표의 상태 값 사이의 연관성을 분석하며,상기 생리학적 건강 정도를 나타내는 건강 지표는,생육 단계별 가축 생체 무게, 폐사율 및 생산성을 포함하는 군에서 선택된 적어도 하나 이상이고,상기 데이터 분석부(130)는, 상기 데이터베이스부(110)에 저장된 상기 후보 지표와 관련된 검체 정보를 이용해 정상범위를 설정하며,상기 연관성 분석부(140)는, 상기 설정한 정상범위를 이용하여, 상기 후보 지표의 상태 값을 미리 정해진 개수의 그룹으로 설정하고, 그룹별로 상태 값과 다른 기존 지표 사이의 연관성을 분석하는 것을 특징으로 하는, 가축 건강상태 면역 지표화 시스템(100)., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

736/1059 Row 736: application_number: 1020210001393, combined_string: invention_title: 정자의 동결보존제 스트레스 저항성 판별용 조성물 abstract: 본 발명은 동결보존제 스트레스 저항성 정자와 민감성 정자간의 NT5C1B, FH, CAPZB, VDAC2, 및 UQCRC1 단백질 발현 수준에 차이가 있음을 확인하여, 상기 단백질을 동결보존제 스트레스 저항성 마커로 제공하고, 상기 마커의 발현을 측정하는 물질을 포함하는 동결보존제 스트레스 저항성 판별용 조성물 등을 제공하는 것으로서, 본 발명의 제공에 의해 가축인공수정시 동결정액의 품질평가에 소요되는 비용 및 시간을 절감할 수 있고, 동결보존제에 의해 운동성, 생존성, 및 수정능획득이 저하되지 않는 고품질의 정자를 선별하여 인공수정의 성공률을 높이고 그 비용을 절감할 수 있을 것으로 기대된다. claims: 동결보존제 스트레스 저항성 마커 FH (Fumarate hydratase), 상기 마커를 코딩하는 유전자, 또는 상기 유전자의 mRNA를 검출하는 물질을 유효성분으로 포함하는 것을 특징으로 하는, 정자의 동결보존제 스트레스 저항성 판별용 조성물.제5항에 있어서,상기 단계 (3)은 동결보존제를 처리한 샘플에서 CAPZB (F-actin-capping protein subunit beta), VDAC2 (Voltage-dependent anion-selective channel protein 2), 및 UQCRC1 (Cytochrome b-c1 complex subunit 1)으로 이루어진 군으로부터 선택되는 하나 이상의 동결보존제 스트레스 저항성 마커, 상기 마커를 코딩하는 유전자, 또는 상기 유전자의 mRNA의 발현 수준을 추가로 측정하는 것을 특징으로 하고,상기 단계 (4)는 상기 샘플에서 측정한 발현 수준과 동결보존제를 처리하지 않은 대조군의 발현 수준을 비교하여 하기의 조건 (a)를 만족하는 경우 샘플의 정자가 동결보존제 스트레스에 저항성이 있는 것으로 추가 판별하는 것을 특징으로 하는, 동결보존제 스트레스 저항성 정자를 판별하기 위한 정보제공방법:(a) UQCRC1, CAPZB, 및 VDAC2로 이루어진 군으로부터 선택되는 하나 이상의 마커, 상기 마커를 코딩하는 유전자, 또는 상기 유전자의 mRNA의 발현 수준이 대조군의 발현 수준보다 낮을 것.제5항에 있어서,상기 동결보존제는 TYB(tris-egg yolk buffer) 및 글리세롤(glycerol); 폼아마이드(fomamide); 프로판디올(propanediol); DMSO(Dimethyl sulfoxide); 및 아도니톨(adonitol)로 이루어지는 군으로부터 선택되는 하나 이상을 포함하는 것을 특징으로 하는, 동결보존제 스트레스 저항성 정자를 판별하기 위한 정보제공방법., Ltext: 농업, prediction: 임업
737/1059 Row 737: application_number: 1020200185962, combined_string: invention_title: 가축의 인공수정 시스템 abstract: 본 발명은 가축의 정액 또는 수정란을 가축의 생식기 내에 주입하기 위한 가축의 인공 수정 시스템에 있어서, 선단에 대상 가축에 정액 또는 수정란을 주입하기 위한 삽입관(110)을 구하는 인공수정용 주입기(100); 상기 인공수정용 주입기(100)와 길이방향으로 결합되고, 선단에 내시경 카메라(210)가 설치되어 상기 대상 가축의 자궁에 삽입되는 내시경 튜브(200); 상기 인공수정용 주입기(100)와 상기 내시경 튜브(200)가 결합되는 손잡이(300); 상기 대상 가축의 생식기 내 감염이 방지되도록 상기 인공수정용 주입기(100)와 상기 내시경 튜브(200)의 외주면을 감싸는 커버 스트로우(400); 및 상기 커버 스트로우(400)의 단부에 착탈가능하도록 결합되는 토출캡(500)을 포함하고, 상기 토출캡(500)은 상기 인공수정용 주입기(100)가 삽입되도록 일측이 개구되고, 타측이 상기 정액 또는 상기 수정란을 토출할 수 있도록 토출부(511)가 형성된 수용부(510); 상기 내시경 카메라(210)에 대응하여 위치하는 카메라용 렌즈(520); 및 일측에 상기 수용부(510) 및 상기 카메라용 렌즈(520)가 연결되고 타측이 상기 커버 스트로우(400)의 단부에 끼워지는 몸체부(530)를 포함하며, 상기 토출부(511)는 90도 간격으로 배치된 4개의 슬릿으로 형성되며, 상기 슬릿은 상기 토출부(511)의 전방 및 측면을 개구한 형태인 것을 특징으로 한다. claims: 가축의 정액 또는 수정란을 가축의 생식기 내에 주입하기 위한 가축의 인공 수정 시스템에 있어서,선단에 대상 가축에 정액 또는 수정란을 주입하기 위한 삽입관(110)을 구하는 인공수정용 주입기(100);상기 인공수정용 주입기(100)와 길이방향으로 결합되고, 선단에 내시경 카메라(210)가 설치되어 상기 대상 가축의 자궁에 삽입되는 내시경 튜브(200);상기 인공수정용 주입기(100)와 상기 내시경 튜브(200)가 결합되는 손잡이(300);상기 대상 가축의 생식기 내 감염이 방지되도록 상기 인공수정용 주입기(100)와 상기 내시경 튜브(200)의 외주면을 감싸는 커버 스트로우(400); 및상기 커버 스트로우(400)의 단부에 착탈가능하도록 결합되는 토출캡(500)을 포함하고,상기 토출캡(500)은상기 인공수정용 주입기(100)가 삽입되도록 일측이 개구되고, 타측이 상기 정액 또는 상기 수정란을 토출할 수 있도록 토출부(511)가 형성된 수용부(510);상기 내시경 카메라(210)에 대응하여 위치하는 카메라용 렌즈(520); 및일측에 상기 수용부(510) 및 상기 카메라용 렌즈(520)가 연결되고 타측이 상기 커버 스트로우(400)의 단부에 끼워지는 몸체부(530)를 포함하며,상기 토출부(511)는 90도 간격으로 배치된 4개의 슬릿으로 형성되며,상기 슬릿은 상기 토출부(511)의 전방 및 측면을 개구한 형태인 것을 특징으로 하는 가축의 인공수정 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

738/1059 Row 738: application_number: 1020200177413, combined_string: invention_title: 반려동물 보험 서비스 제공 방법 abstract: 반려동물 보험 서비스 제공 방법이 개시된다. 본 발명의 일 측면에 따르면, 동물병원 단말기로부터 반려동물이 보험에 가입되어 있는지 여부에 대한 확인 요청을 수신하는 단계; 반려동물이 보험에 가입되어 있는 것으로 확인되는 경우, 동물병원 단말기에 반려동물에 대한 진료 항목마다 수령 가능한 보험금 정보를 포함하는 보험금 테이블을 제공하는 단계; 동물병원 단말기로부터 반려동물의 진료에 따른 진료비를 입력받고 보험금 테이블 중 반려동물의 진료에 따른 보험금을 선택 입력받는 단계; 고객 단말기에 진료비에서 보험금을 차감한 금액을 최종 결제 금액으로 전송하는 단계; 동물병원 단말기로부터 보험금의 지급을 위한 진료 증빙 자료를 수신하는 단계; 보험금 지급 심사를 위하여 진료 증빙 자료를 보험사 서버에 전송하는 단계; 보험사 서버로부터 보험금 지급 결정에 대한 심사 결과를 수신하는 단계; 동물병원 단말기에 심사 결과를 통보하는 단계; 고객 단말기에 심사 결과를 통보하는 단계; 보험금 지급 내역을 동물병원 단말기에 통보하는 단계; 및 보험금 지급 내역을 고객 단말기에 통보하는 단계를 포함하는 반려동물 보험 서비스 제공 방법이 제공된다. claims: 반려동물 보험 서비스 제공 시스템은 고객이 반려동물의 진료에 보험의 적용을 요청하는 경우, 동물병원 단말기로부터 상기 반려동물이 보험에 가입되어 있는지 여부에 대한 확인 요청을 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 반려동물이 보험에 가입되어 있는 것으로 확인되는 경우, 상기 동물병원 단말기에 상기 반려동물에 대한 진료 항목마다 수령 가능한 보험금 정보를 포함하는 보험금 테이블을 제공하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원 단말기로부터 상기 반려동물의 진료에 따른 진료비를 입력받고 상기 보험금 테이블 중 상기 반려동물의 진료에 따른 보험금을 선택 입력받는 단계;상기 반려동물 보험 서비스 제공 시스템은 고객 단말기에 상기 진료비에서 상기 보험금을 차감한 금액을 최종 결제 금액으로 전송하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원 단말기로부터 상기 보험금의 지급을 위한 진료 증빙 자료를 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험금 지급 심사를 위하여 상기 진료 증빙 자료를 보험사 서버에 전송하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 진료 증빙 자료에 기초한 상기 보험금 지급 심사에 따라 상기 보험금의 지급이 결정되는 경우, 상기 보험사 서버로부터 상기 보험금 지급 결정에 대한 심사 결과를 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원 단말기에 상기 심사 결과를 통보하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기에 상기 심사 결과를 통보하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원에 상기 보험금이 지급되는 경우, 상기 보험금 지급 내역을 상기 동물병원 단말기에 통보하는 단계; 및상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원에 상기 보험금이 지급되는 경우, 상기 보험금 지급 내역을 상기 고객 단말기에 통보하는 단계를 포함하고,상기 반려동물이 보험에 가입되어 있는지 여부에 대한 확인 요청을 수신하는 단계는, 상기 동물병원 단말기로부터 상기 반려동물의 동물등록번호를 입력받는 단계를 포함하고,상기 반려동물의 동물등록번호는,상기 반려동물 보험 서비스 제공 시스템은 동물보호관리시스템 서버로부터 동물등록 대행업체로 인증된 업체 정보를 제공받는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원 단말기로부터 상기 동물병원이 상기 동물등록 대행업체로 인증되어 있는지 여부에 대한 확인 요청을 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 인증된 업체 정보에 상기 동물병원이 포함되는 경우, 상기 동물병원이 인증된 상기 동물등록 대행업체임을 확인한 결과를 상기 동물병원 단말기에 통보하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물등록 대행업체로 인증된 상기 동물병원에서 상기 반려동물에 대해 동물등록을 위한 절차가 수행되는 경우, 상기 동물병원 단말기로부터 상기 동물등록을 위한 절차 수행 관련 정보를 입력받는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물보호관리시스템 서버에 상기 동물등록을 위한 절차 수행 관련 정보를 전송하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물등록을 위한 절차 수행 관련 정보에 따라 상기 반려동물의 동물등록이 승인되는 경우, 상기 동물보호관리시스템 서버로부터 상기 반려동물의 동물등록 승인 결과를 수신하는 단계; 및상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기에 상기 반려동물의 동물등록 승인 결과를 통보하는 단계를 통해 획득되고,상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로부터 보험 상품 가입 신청을 받아 보험 상품 가입을 진행하고,상기 보험 상품 가입은,상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로부터 상기 보험 상품 가입 신청을 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험사 서버로 상기 보험 상품 가입 신청 정보를 전송하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험사 서버로부터 승인과 함께 보험료 결제 정보를 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로 보험 승인 결정 및 상기 보험료 결제 정보를 전송하는 단계; 및상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로부터 보험료가 지급되는 경우, 상기 보험사 서버로부터 가입 승인 및 약관 정보를 수신받아 상기 고객 단말기로 전송하는 단계를 통해 진행되고,상기 보험 상품 가입 신청은 상기 반려동물에 대한 상세 정보를 포함하고,상기 반려동물에 대한 상세 정보는 상기 반려동물의 동물등록번호를 포함하고,상기 고객 단말기는 고객의 선택에 따라 직접 보험금을 수령 가능하도록 상기 반려동물 보험 서비스 제공 시스템에 보험금 지급을 요청하는 단계를 더 포함하고,상기 보험금 지급 요청 단계는,상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로부터 보험금 지급 요청 및 상기 반려동물의 진료에 대한 진료 증빙 자료를 전송받는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험금 지급 요청 및 상기 반려동물의 진료에 대한 진료 증빙 자료를 상기 보험사 서버에 제공하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험사 서버로부터 보험금 지급 요청에 대한 심사 결과를 제공받아 상기 고객 단말기에 통보하는 단계; 및상기 보험사 서버는 상기 고객의 계좌로 직접 보험금을 지급하는 단계를 포함하는, 반려동물 보험 서비스 제공 방법., Ltext: 농업, prediction: 임업
739/1059 Row 739: application_number: 1020200166733, combined_string: invention_title: 유전자 정보에 기반한 품종정보 제공 시스템 및 방법 abstract: 본 발명은 애완동물의 혼혈정보를 제공하는 시스템을 개시한다. 상세하게는, 본 발명은 애완동물의 품종 특이적인 유전자 마커를 찾아내어 확정하고, 피검 애완동물의 유전적 품종을 명확하게 판별하는 유전자 정보에 기반한 품종정보 제공 시스템 및 방법에 관한 것이다.본 발명의 실시예에 따르면, 특정 품종의 유전자 정보가 얼마 만큼씩 유사한지를 측정하는 것이 아닌, 해당 품종에만 있는 유전자 마커를 단정적으로 확인하고, 그 품종에 속하는지 아닌지를 명확히 식별함에 따라, 단순 비율을 제공하는 것이 아닌, 실제 각 혼혈동물의 조상중에 어떤 품종들이 있는지를 정확하게 알려주는 효과가 있다. claims: 피검 동물로부터 채취된 시료를 해독하는 게놈 해독장치;상기 게놈 해독장치로부터 시료 해독 결과를 입력받고, 미리 구축된 분자 라이브러리와의 대조를 통해 상기 시료에 대한 유전자 검사를 수행하는 검사 단말기; 및정보통신망을 통해 원격지에 위치한 하나 이상의 검사 단말기와 연결되어 상기 유전자 검사결과를 전송받고, 상기 검사결과로부터 판단된 피검 동물의 품종과 관련된 하나 이상의 유전자 마커 중, 타 품종과의 특이성을 대표하는 비 공통 유전자를 하나 이상 추출하여 어느 품종인지 판단하고, 품종 의뢰에 따른 품종 정보를 제공하는 유전자 센터 서버를 포함하고,상기 유전자 센터 서버는,관리자에 의한 입력 또는 외부 시스템으로부터 전송되는 복수의 동물에 대한 유전자 정보를 수시로 수집하고, 수집된 동물의 유전자 정보의 분석을 수행하는 해독부;품종별 표준게놈지도를 해독, 조립 또는 전장게놈서열을 해독하거나, DNA chip에 기록된 데이터를 로딩하여 상기 유전자 정보에 포함되는 특이적 유전자 마커를 도출하는 특이마커 도출부;도출된 특이적 유전자 마커에 따라, 해당 동물을 품종을 분류하는 개체 분류부;동물 그룹의 특이적인 변이들의 비중복(non-redundant)세트가 정의되며, 해당 세트에 대한 피검 동물의 유전자 정보를 공지의 염기서열 분석 기술인 시퀀싱(sequencing) 및, 개체가 가지는 유전형의 다양성 분석 기술인 제노타이핑(genotyping) 방식으로 생성된 정보가 저장되고, 하나 이상의 동물에 대한 유전자 마커에 따라 분류되는 품종별 유전자 마커를 포함하는 유전자 정보가 저장되는 데이터 베이스;상기 검사 단말기로부터 피검 동물의 시료를 포함하는 유전자 검사결과를 입력받아, 상기 피검 동물의 시료로부터 도출되는 유전자 마커와, 상기 데이터 베이스를 참조하여 저장된 유전자 정보의 유전자 마커를 대조하는 마커 대조부; 및유전자 마커의 대조 결과에 따라, 상기 피검 동물의 유전자 정보에 포함된 하나 이상의 특이적 유전자 마커를 도출하여 상기 피검 동물에 대한 단일품종 또는 혼혈품종 여부를 포함하는 품종정보를 상기 검사 단말기에 회신하되, 상기 피검 동물이 혼혈품종일 경우, 존재하는 모든 특이적 유전자 마커에 해당하는 각 품종을 특정하여 상기 품종정보에 반영하고, 상기 피검 동물이 어느 품종 특이적인 유전자 마커를 보유하고 있는지 확인하여 가장 많은 품종 특이적 유전자 마커를 가진 품종을 상기 피검 동물의 품종으로 1개 이상 지정하고, 상기 피검 동물에 둘 이상의 특이적 유전자 마커의 조합이 존재하되, 상기 데이터 베이스에 존재하지 않는 경우, 상기 피검 동물에 대한 유전자 정보를 상기 데이터 베이스에 반영하는 품종 특정부를 포함하고,상기 품종정보를 판별하는 데 이용되는 유전적 마커는,단일염기 다형성(single nucleotide polymorphism), 삽입-결실(indel), 반복변이(copy number variants) 및 구조변이(structural variant) 중, 적어도 하나 또는 둘 이상을 조합하여 도출한 것인, 유전자 정보에 기반한 품종정보 제공 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

740/1059 Row 740: application_number: 1020200165592, combined_string: invention_title: 반려동물 사체 비대면 처리 통합관리 시스템 및 방법 abstract: 반려동물 사체 비대면 처리 통합관리 시스템 및 방법이 개시된다. 스마트 폰으로부터 동물 사체의 이미지 및 해당 위치 정보를 수신하는 이미지/위치 정보 수신 모듈; 상기 이미지/위치 정보 수신 모듈에서 수신된 이미지 및 위치 정보에 따라 동물 사체 신고를 접수하는 동물 사체 신고 접수 모듈; 동물 사체 수거 업체 단말로 해당 동물 사체에 대한 수거를 요청하는 동물 사체 수거 요청 모듈을 구성한다. 상술한 반려동물 사체 비대면 처리 통합관리 시스템 및 방법에 의하면, 동물 사체의 이미지와 정확한 위치 정보를 스마트 폰으로부터 수신하고, 자동으로 동물 사체 신고를 접수받도록 구성됨으로써, 동물 사체의 처리에 대한 행정적 처리가 명확해지고 체계화되는 효과가 있다. 또한, 이를 동물 수거 업체에 전달하여 즉시 수거하도록 구성됨으로써, 신속한 동물 사체 수거가 가능해지고 2차 사고가 뒤따르는 것을 방지할 수 있는 효과가 있다. claims: 스마트 폰(200)으로부터 동물 사체의 이미지 및 해당 위치 정보를 수신하는 이미지/위치 정보 수신 모듈(101);상기 이미지/위치 정보 수신 모듈(101)에서 수신된 이미지 및 위치 정보에 따라 동물 사체 신고를 접수하는 동물 사체 신고 접수 모듈(103);동물 사체 수거 업체 단말(300)로 해당 동물 사체에 대한 수거를 요청하는 동물 사체 수거 요청 모듈(109)을 포함하고,상기 이미지/위치 정보 수신 모듈(101)에서 수신된 이미지 및 위치 정보가 저장되는 이미지/위치정보 데이터베이스(102)를 더 포함하며,상기 동물 사체 신고 접수 모듈(103)에서 접수된 동물 사체의 이미지로부터 딥러닝을 이용하여 해당 동물을 자동 인식하는 딥러닝 동물 자동 인식 모듈(104),상기 딥러닝 동물 자동 인식 모듈(104)에서 자동 인식된 동물의 동물 사체를 미리 정해진 카테고리에 따라 자동 분류하는 동물 사체 분류 모듈(105)을 더 포함하고,상기 동물 사체 분류 모듈(105)에서 분류된 동물 사체에 대해 상기 카테고리에 따라 동물 사체 처리에 대한 과금을 수행하는 동물 사체 처리 과금 모듈(106),상기 동물 사체 처리 과금 모듈(106)의 과금에 대해 상기 스마트 폰(200)의 결제 처리를 수행하는 과금 결제 모듈(107)을 더 포함하며,상기 과금 결제 모듈(107)에서 결제 처리가 완료된 경우 상기 이미지/위치정보 데이터베이스(102)의 위치 정보를 참조하여 해당 동물 사체를 수거하기 위한 수거 동선을 산출하여 제공하는 동물 사체 수거 동선 산출 모듈(108)을 더 포함하고, 상기 동물 사체 신고 접수 모듈(103)에서 접수된 동물 사체 신고에 따른 동물 사체 처리 결과에 대해 통계 처리를 수행하는 동물 사체 처리 통계 모듈(109),상기 동물 사체 처리 통계 모듈(109)에서 수행된 통계 처리 결과가 저장되는 동물 사체 처리 통계 데이터베이스(111)를 더 포함하며,상기 이미지/위치 정보 수신 모듈(101)은 스마트 폰(200)의 카메라를 이용하여 동물 사체 이미지를 촬영하고,상기 스마트 폰(200)은 동물 사체만 촬영하는 것이 아니라 주변 공간을 포함한 파노라마 촬영을 안내하며,상기 위치 정보는 상기 스마트 폰(200)의 GPS 모듈이나 와이파이 모듈을 통해 자동으로 기록되고,상기 동물 사체 처리 과금 모듈(106)은 상기 동물 사체 분류 모듈(105)에서 분류된 동물 사체에 대한 카테고리에 따른 동물 사체의 평균적인 크기를 참조하여 과금을 수행하며,상기 동물 사체 수거 동선 산출 모듈(108)에 의해 산출된 수거 동선은 미리 알고 있는 동물 사체 수거 업체의 위치로부터 동물 사체까지의 동선이고,상기 동물 사체 처리 통계 모듈(110)의 동물 사체 처리 결과에 대한 통계 처리는 계절, 월, 휴일 여부, 일자, 시간대를 포함하는 시간적 요소를 포함하며,상기 동물 사체 수거 업체 단말(300)은 동물 사체를 수거 완료한 후 동물 장묘 업체 서버(400)에 접속하여 수거 완료된 동물 사체에 대한 장묘를 요청하는 것을 특징으로 하는 반려동물 사체 비대면 처리 통합관리 시스템., Ltext: 농업, prediction: 임업
741/1059 Row 741: application_number: 1020200160404, combined_string: invention_title: ICT 융복합 축산환경 관제시스템 abstract: 개시되는 ICT 융복합 축산환경 관제시스템은, 복수의 축산농가에 각각 설치되는 도징 시스템;으로서, 외부로부터 가축에게 물을 공급하는 펌프;와, 상기 펌프에 의해 공급되는 물의 유량을 감지하는 유량센서;와, 상기 유량센서에 의해 감지된 유량정보에 따라 설정된 비율로 액상 사료첨가제를 공급하는 도징유닛;을 포함하는 도징 시스템; 상기 가축이 배출하는 분뇨 또는 가스로부터 악취를 측정하여 상기 악취정보를 생성하는 악취 측정부; 상기 도징유닛 및 상기 악취 측정부와 통신 가능하게 구비되며, 상기 축산농가 식별정보, 상기 설정된 비율, 누적음수량(L), 순시음 수량(L/hr), 누적 액상 사료첨가제 급이량(L), 도징유닛의 상태(RUN, STOP, ALARM)에 관한 정보를 포함하는 도징 시스템 정보 및 상기 악취정보를 포함하는 악취 측정부 정보를 수집하는 감시정보 수집부; 인터넷에 연결되어 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 송신하는 통신부; 상기 통신부로부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전달받아 저장하는 클라우드 서버; 및 상기 축산농가의 관리자가 인터넷을 통해 상기 클라우드 서버에 접근 가능하게 구비되는 관리자단말;을 포함한다. claims: 복수의 축산농가에 각각 설치되는 도징 시스템;으로서, 외부로부터 가축에게 물을 공급하는 펌프;와, 상기 펌프에 의해 공급되는 물의 유량을 감지하는 유량센서;와, 상기 유량센서에 의해 감지된 유량정보에 따라 설정된 비율로 액상 사료첨가제를 공급하는 도징유닛;을 포함하는 도징 시스템;상기 가축이 배출하는 분뇨 또는 가스로부터 악취를 측정하여 상기 악취정보를 생성하는 악취 측정부;상기 도징유닛 및 상기 악취 측정부와 통신 가능하게 구비되며, 상기 축산농가 식별정보, 상기 설정된 비율, 누적음수량(L), 순시음 수량(L/hr), 누적 액상 사료첨가제 급이량(L), 도징유닛의 상태(RUN, STOP, ALARM)에 관한 정보를 포함하는 도징 시스템 정보 및 상기 악취정보를 포함하는 악취 측정부 정보를 수집하는 감시정보 수집부;인터넷에 연결되고, 상기 감시정보 수집부와 통신가능하도록 연결되어 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 송신하는 통신부;상기 통신부로부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전달받아 저장하는 클라우드 서버; 및상기 축산농가의 관리자가 인터넷을 통해 상기 클라우드 서버에 접근 가능하게 구비되는 관리자단말;을 포함하는 ICT 융복합 축산환경 관제시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

742/1059 Row 742: application_number: 1020200156831, combined_string: invention_title: 반려동물의 훈육을 가이드하는 챗봇 시스템, 방법, 및 컴퓨터 프로그램 abstract: 챗봇 시스템의 반려동물 훈육 가이드 방법이 개시된다. 본 방법은, 반려동물의 훈육에 대한 가이드를 제공하도록 훈련된 복수의 인공지능 모델 중, 사용자 입력에 따라 선택된 반려동물의 행동에 대응되는 인공지능 모델을 식별하는 단계, 식별된 인공지능 모델을 기반으로, 선택된 행동을 수행하는 반려동물의 훈육에 대한 가이드를 제공하는 단계를 포함한다. claims: 챗봇 시스템의 반려동물 훈육 가이드 방법에 있어서,반려동물의 복수의 행동 중 적어도 하나의 행동을 선택하는 사용자 입력을 수신하는 단계;반려동물의 훈육에 대한 가이드를 제공하도록 훈련된 복수의 인공지능 모델 중, 상기 선택된 행동에 대한 훈육 지침을 기반으로 훈련된 인공지능 모델을 식별하는 단계; 및상기 식별된 인공지능 모델을 기반으로, 상기 선택된 행동을 수행하는 반려동물의 훈육에 대한 가이드를 제공하는 단계;를 포함하고,상기 가이드를 제공하는 단계는,상기 식별된 인공지능 모델의 출력을 기반으로 제1 단계의 훈육 가이드를 제공하고,상기 제공된 제1 단계의 훈육 가이드에 대한 사용자의 경과 보고가 수신된 경우, 상기 경과 보고가 입력된 상기 식별된 인공지능 모델의 출력을 기반으로 제2 단계의 훈육 가이드를 제공하고,상기 제공된 제1 단계의 훈육 가이드에 대한 사용자의 질문이 수신된 경우, 상기 질문이 입력된 상기 식별된 인공지능 모델의 출력을 기반으로 상기 질문에 대한 답변을 제공하고,상기 제공된 제1 단계의 훈육 가이드에 대하여 보충 설명을 요청하는 사용자 입력이 수신되면, 상기 제1 단계의 훈육 가이드와 관련된 적어도 하나의 시범 영상을 제공하고,상기 챗봇 시스템의 반려동물 훈육 가이드 방법은,반려동물의 특정한 행동을 교정하기 위한 서로 다른 복수의 훈육 지침 각각을 기반으로, 인공지능 모델들을 각각 독립적으로 훈련시키는 단계; 및상기 인공지능 모델들 각각을 통해 제공된 가이드에 대한 사용자들의 평가에 기초하여, 상기 복수의 훈육 지침 각각에 대한 스코어를 산출하는 단계;를 더 포함하는, 챗봇 시스템의 반려동물 훈육 가이드 방법.하나 이상의 인스트럭션을 저장하는 적어도 하나의 메모리; 및상기 하나 이상의 인스트럭션을 실행함으로써 제1항의 반려동물 훈육 가이드 방법을 수행하는 적어도 하나의 프로세서;를 포함하는, 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

743/1059 Row 743: application_number: 1020200140462, combined_string: invention_title: 반려동물 사료 및 간식 큐레이션 방법, 장치 및 이를 이용한 시스템 abstract: 본 발명은 본 발명은 반려동물 사료 및 간식 큐레이션 방법, 장치 및 이를 이용한 시스템에 관한 것으로서, SNS(Social Network service)로부터 반려동물이 섭취하는 사료 또는 간식과 관련된 비정형 피드 정보를 마이닝하는 단계, 상기 비정형 피드 정보를 가공하여 상기 비정형 피드 정보를 정형 피드 정보로 전처리하는 단계, 상기 구축된 피드 큐레이션 데이터베이스를 이용하여 상기 반려동물 정보에 따른 반려동물에 대한 피드를 매칭하는 단계를 포함할 수 있다. claims: 컴퓨팅 장치에 의해 수행되는 방법에 있어서,SNS(Social Network service)로부터 반려동물이 섭취하는 사료 또는 간식과 관련된 비정형 피드 정보를 마이닝하는 단계;상기 비정형 피드 정보를 가공하여 상기 비정형 피드 정보를 정형 피드 정보로 전처리하는 단계;상기 정형 피드 정보를 취합하여 피드 큐레이션 데이터베이스를 구축하는 단계;사용자 단말로부터 반려동물 정보를 입력받는 단계;상기 구축된 피드 큐레이션 데이터베이스를 이용하여 상기 반려동물 정보에 따른 반려동물에 대한 피드를 매칭하는 단계; 및상기 매칭된 피드를 상기 반려동물에게 추천하는 피드 큐레이션 정보를 상기 사용자 단말로 전송하는 단계를 포함하고,상기 반려동물이 섭취하는 사료 또는 간식과 관련된 비정형 피드 정보를 마이닝하는 단계는,상기 SNS에 접속하는 단계;상기 SNS의 컨텐츠가 이미지 또는 영상인 경우 상기 컨텐츠에 반려동물이 포함되고 상기 컨텐츠 내에서 상기 반려동물의 입 속 또는 입 주변에 물질이 존재하는 경우 상기 피드가 존재하는 것으로 판단하고, 상기 SNS의 컨텐츠가 텍스트인 경우 상기 컨텐츠에 반려동물에 관한 텍스트가 포함되고 상기 컨텐츠 내에서 상기 반려동물에 관한 텍스트에 미리 설정된 단어 간격 이내에 상기 피드가 존재하는 것으로 판단하는 단계;상기 피드가 존재한다는 판단한 결과에 기초하여 상기 SNS의 컨텐츠를 상기 비정형 피드 정보로 결정하는 단계;및상기 비정형 피드 정보로 결정된 상기 SNS의 컨텐츠를 크롤링하는 단계를 포함하며,상기 매칭된 피드를 상기 반려동물에게 추천하는 피드 큐레이션 정보를 상기 사용자 단말로 전송하는 단계는,상기 피드 큐레이션 정보의 신뢰도를 검증하는 단계를 더 포함하되,상기 피드 큐레이션 정보의 신뢰도를 검증하는 단계는,다른 사용자 단말로부터 상기 피드 큐레이션 정보에 대한 평가 정보를 수집하고, 상기 피드 큐레이션 정보에 대한 평가정보에 따라 상기 피드 큐레이션 정보에 대한 신뢰도를 산정하는 단계;상기 반려동물 정보를 입력한 사용자 단말로부터 입력된 희망 신뢰도 정보와 상기 피드 큐레이션 정보에 대한 신뢰도를 비교하는 단계; 및상기 피드 큐레이션 정보의 신뢰도가 상기 희망 신뢰도에 비해 높은 경우에만 상기 피드 큐레이션 정보를 상기 사용자 단말로 전송하는 단계를 포함하고,상기 비정형 피드 정보를 가공하여 상기 비정형 피드 정보를 정형 피드 정보로 전처리하는 단계는,상기 이미지 또는 영상 컨텐츠 및 텍스트로 이루어진 상기 비정형 피드 정보에 대하여 상기 반려동물의 품종, 생년월일, 성별 및 체중과, 관심 질병 및 관심 기능에 해당되는 특징을 라벨링하는 단계;상기 라벨링된 비정형 피드 정보의 속성을 기초로 클러스터링하여 유사도를 기초로 상기 비정형 피드 정보가 카테고라이징된 정형화 피드 정보를 출력하는 단계를 포함하고,상기 사용자 단말로부터 반려동물 정보를 입력받는 단계는,상기 반려동물의 품종, 생년월일, 성별 및 체중에 대한 필수 정보와 상기 반려동물의 관심 질병 및 관심 기능에 대한 선택 정보를 입력받는 단계를 포함하고,상기 구축된 피드 큐레이션 데이터베이스를 이용하여 상기 반려동물에 대한 피드를 매칭하는 단계는,상기 반려동물 정보를 기초로 품종별 유전질환, 필요 기능, 필요 원료/성분 및 급여량을 결정하는 단계;상기 결정된 품종별 유전질환, 필요 기능, 필요 원료/성분 및 급여량 정보와 상기 피드 큐레이션 데이터베이스에 저장된 피드 리스트를 비교하는 단계; 및상기 비교에 의해 매칭되는 데이터의 크기를 기준으로 상기 피드 리스트를 정렬하는 단계를 포함하고,상기 매칭된 피드를 상기 반려동물에게 추천하는 피드 큐레이션 정보를 상기 사용자 단말로 전송하는 단계는,상기 피드에 적합한 연령 정보, 크기 정보, 복수의 기능 정보와 상기 반려동물 정보가 매칭되는 데이터 크기가 가장 큰 피드에서부터 상기 피드에 적합한 연령 정보, 크기 정보, 복수의 기능 정보와 상기 반려동물 정보가 매칭되는 데이터 크기가 작아지는 순서로 상기 피드를 추천하는 단계를 포함하며,상기 반려동물의 정보와 상기 정형 피드 정보를 취합하여 피드 큐레이션 데이터 베이스를 구축하는 단계는,상기 반려동물의 분류, 연령, 견종크기, 희망 주요기능, 희망 주원료와 상기 피드의 브랜드, 상품명, 용량, 공급가, 온라인 평균 판매가, 소비자가, 정가, 프로모션 현황, 주요기능, 주원료, 함유성분, 제조 특징, 원산지, 전체 원료 구성, 급여량, 낱개 속포장 여부, 유통기한, 유사 검색어, 간략 설명으로 데이터를 분류하여 저장하는 단계;상기 연령을, 1년 미만의 퍼피, 1년 이상 7년 미만의 성견, 7년 이상의 노령견으로 분류하는 단계;상기 견종크기를, 품종에 따른 소형, 중형 및 대형으로 분류하는 단계;상기 주요기능을 면역력 향상, 소화력 증진, 치석 예방/제거, 관절/뼈 강화, 피부(모질) 개선, 다이어트, 눈 건강, 장기능 개선 및 호흡기 건강 개선으로 분류하는 단계; 및상기 피드에 적합한 몸무게 및 급여량을, 생년, 체중대비 급여횟수, 기초대사량, 1일 급여칼로리 및 1일 섭취량으로 분류하는 단계를 포함하는,반려동물 사료 및 간식 큐레이션 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

744/1059 Row 744: application_number: 1020200140463, combined_string: invention_title: 반려동물 헬스 케어 큐레이션 방법, 장치 및 이를 이용한 시스템 abstract: 본 발명은 본 발명은 반려동물 헬스 케어 큐레이션 방법, 장치 및 이를 이용한 시스템에 관한 것으로서, SNS(Social Network service)로부터 반려동물의 행동 및 증상과 관련된 비정형 건강 정보를 마이닝하는 단계, 상기 비정형 건강 정보를 가공하여 상기 비정형 건강 정보를 정형 건강 정보로 전처리하는 단계, 상기 구축된 통합 건강 데이터베이스를 이용하여 상기 반려동물 정보에 따른 반려동물에 대한 진단 정보를 매칭하는 단계, 상기 반려동물에 대한 진단 정보를 기초로 상기 반려동물의 건강을 케어하는 관리 방안을 결정하는 단계, 및 상기 진단 정보, 상기 관리 방안, 및 상기 SNS로부터 실시간으로 수집된 상기 관리 방안에 따른 비용 정보가 포함된 헬스 케어 정보를 상기 사용자 단말로 전송하는 단계를 포함할 수 있다. claims: 컴퓨팅 장치에 의해 수행되는 방법에 있어서,SNS(Social Network service)로부터 반려동물의 행동 및 증상과 관련된 비정형 건강 정보를 마이닝하는 단계;상기 비정형 건강 정보를 가공하여 상기 비정형 건강 정보를 정형 건강 정보로 전처리하는 단계;상기 정형 건강 정보를 취합하여 통합 건강 데이터베이스를 구축하는 단계;사용자 단말로부터 반려동물 정보를 입력받는 단계;상기 구축된 통합 건강 데이터베이스를 이용하여 상기 반려동물 정보에 따른 반려동물에 대한 진단 정보를 매칭하는 단계;상기 반려동물에 대한 진단 정보를 기초로 상기 반려동물의 건강을 케어하는 관리 방안을 결정하는 단계; 및상기 진단 정보, 상기 관리 방안, 및 상기 SNS로부터 실시간으로 수집된 상기 관리 방안에 따른 비용 정보가 포함된 헬스 케어 정보를 상기 사용자 단말로 전송하는 단계를 포함하며,상기 반려동물의 행동 및 증상과 관련된 비정형 건강 정보를 마이닝하는 단계는,상기 SNS에 접속하는 단계; 및상기 SNS로부터 상기 반려동물과 상기 반려동물의 건강 상태에 대한 정보가 함께 포함된 미디어 컨텐츠 및 텍스트를 크롤링하는 단계를 포함하며,상기 비정형 건강 정보를 가공하여 상기 비정형 건강 정보를 정형 건강 정보로 전처리하는 단계는,상기 미디어 컨텐츠 및 텍스트로 이루어진 상기 비정형 건강 정보에 대하여 상기 반려동물의 부위 별 행동과, 상기 부위에 대한 증상으로 분류하고, 상기 반려동물의 부위 별 행동에 따른 이상 징후와 및 상기 부위에 대한 증상에 따른 이상 징후를 라벨링하는 단계; 및상기 라벨링된 비정형 건강 정보의 속성을 기초로 이상 징후를 클러스터링하여 상기 이상 징후의 유사도를 기초로 상기 비정형 건강 정보가 카테고라이징된 정형화 건강 정보를 출력하는 단계를 포함하고,상기 사용자 단말로부터 반려동물 정보를 입력받는 단계는,상기 반려동물의 부위 별 행동 및 상기 부위에 대한 증상을 입력받는 단계를 포함하고,상기 구축된 통합 건강 데이터베이스를 이용하여 상기 반려동물에 대한 진단 정보를 매칭하는 단계는,상기 반려동물의 부위 별 행동 및 상기 부위에 대한 증상을 상기 통합 건강 데이터베이스에 포함된 이상 징후와 비교하는 단계;상기 반려동물의 부위 별 행동 및 상기 부위에 대한 증상에 매칭되는 이상 징후 중에서 매칭되는 데이터의 크기를 기초로 이상 징후를 결정하는 단계; 및상기 이상 징후를 기초로 상기 반려동물에 적용되는 예상 질병을 결정하는 단계를 포함하고,상기 반려동물에 대한 진단 정보를 기초로 상기 반려동물의 건강을 케어하는 관리 방안을 결정하는 단계는,상기 예상 질병을 치료하는 지역별 예상 진료비를 제공하는 단계;상기 예상 질병이 예방 접종에 의해 치료되는 것으로 판단되는 경우 상기 예방 접종의 종류에 따른 지역별 예상 접종비 정보를 제공하는 단계; 및상기 반려동물의 상기 예상 질병을 치료한 후의 추천 사료를 제공하는 단계를 포함하고,상기 매칭된 진단 정보를 상기 반려동물에게 추천하는 헬스 케어 정보를 상기 사용자 단말로 전송하는 단계는,상기 반려동물의 부위 별 행동 및 상기 부위에 대한 증상에 매칭되는 이상 징후 중에서 매칭되는 데이터의 크기를 기준으로, 매칭되는 데이터 크기가 가장 큰 이상 징후에 해당되는 예상 질병을 가능성이 높은 예상 질병으로 표시하고, 상기 가능성이 높은 예상 질병보다 매칭되는 이상 징후의 데이터 크기가 작은 예상 질병을 가능성이 낮은 예상 질병으로 표시하는 단계를 포함하는,반려동물 헬스 케어 큐레이션 방법., Ltext: 농업, prediction: 임업
745/1059 Row 745: application_number: 1020200133898, combined_string: invention_title: 가축 유도 시스템 abstract: 본 발명은 가축들을 지정된 장소로 무인으로 유도시켜 줌과 동시에 축사장 바닥을 청소하도록 구현한 가축 유도 시스템에 관한 것으로, 바닥 위에 위치하여 전측으로 이동시 바닥의 이물질을 청소하고, 후측으로 이동시 가축을 지정된 장소로 유도시키는 유도장치; 유도장치 양측에 연결되어 상하방향으로 이동시켜 주는 수직이동장치; 및 수직이동장치 상단에 연결되어 전후방향으로 이동시켜 주는 수평이동장치를 포함한다. claims: 바닥 위에 위치하여 전측으로 이동시 바닥의 이물질을 청소하고, 후측으로 이동시 가축을 지정된 장소로 유도시키는 유도장치;상기 유도장치 양측에 연결되어 상하방향으로 이동시켜 주는 수직이동장치; 및상기 수직이동장치 상단에 연결되어 전후방향으로 이동시켜 주는 수평이동장치를 포함하되,전측에 위치하여 가축이 통로에 들어오기 전 가축의 건강상태를 체크하는 건강체크기;전측 통로 입구에 위치하여 가축을 샤워해주는 샤워기; 및상기 샤워기에서 기 설정된 후측방향에 설치하여 가축을 건조하는 건조기를 포함하는 가축 유도 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

746/1059 Row 746: application_number: 1020200130913, combined_string: invention_title: 반려동물 사료공급장치 및 이를 이용한 반려동물 사료공급방법 abstract: 본 발명은 반려동물 사료공급장치 및 이를 이용한 사료공급방법에 관한 것이다.본 발명의 실시예에 따르면, 반려동물 사료공급장치에 있어서, 외형을 형성하는 하우징부; 상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및 상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함한다. claims: 반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하는 반려동물 사료공급장치.외형을 형성하는 하우징부; 상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되고, 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료가 상기 사료보관공간으로부터 배출되며, 상기 사료를 기설정된 양만큼 상기 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및 상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리를 포함하는 반려동물 사료공급장치를 이용한 반려동물 사료공급방법에 있어서,복수의 트레이유닛 어느 하나의 트레이유닛이 상기 사료공급 어셈블리의 하방에 배치되도록 상기 트레이 어셈블리를 회전시키는 제1 트레이 회전 단계;상기 사료공급 어셈블리의 하방에 배치되는 상기 트레이유닛에 기설정된 양의 사료를 공급하는 사료 분배 단계; 및상기 사료 공급이 완료된 상기 트레이유닛이 상기 하우징부에 형성된 배식홀을 통하여 외부로 노출되도록 상기 트레이 어셈블리를 회전시키는 제2 트레이 회전 단계;를 포함하는 반려동물 사료공급방법., Ltext: 농업, prediction: 임업
747/1059 Row 747: application_number: 1020200129621, combined_string: invention_title: IOT 반려동물용 스마트 식기 abstract: 본 발명의 일 실시예는 내부공간을 형성하며, 내측으로 함몰되는 제 1 수용부를 포함하는 본체부; 상기 제 1 수용부에 지지되며, 내측으로 함몰되는 제 2 수용부를 포함하는 지지부; 상기 제 2 수용부에 지지되며, 반려동물용 사료 또는 물이 수용되는 제 3 수용부를 포함하는 보울부; 상기 본체부의 내부공간에 마련되어, 상기 지지부, 상기 보울부 및 상기 보울부에 수용되는 반려동물용 사료 또는 물의 무게를 측정하는 무게센서부; 유저 단말; 상기 유저 단말과 통신할 수 있는 통신부; 및 상기 무게센서부에서 측정된 무게 정보로부터 반려동물에게 제공된 반려동물용 사료 또는 물의 양 또는 반려동물이 섭취한 사료 또는 물의 양을 산출하여 상기 유저 단말에 전송하는 제어부; 를 포함하고, 상기 보울부에서 유출된 물이 상기 제 1 수용부 내부에 수용될 수 있도록, 상기 제 2 수용부는 상기 제 1 수용부로부터 소정거리 이격되어 지지되는 것을 특징으로 하는, IOT 반려동물용 스마트 식기를 제공한다. claims: 내부공간을 형성하며, 내측으로 함몰되는 제 1 수용부를 포함하는 본체부;상기 제 1 수용부에 지지되며, 내측으로 함몰되는 제 2 수용부를 포함하는 지지부;상기 제 2 수용부에 지지되며, 반려동물용 사료 또는 물이 수용되는 제 3 수용부를 포함하는 보울부;상기 본체부의 내부공간에 마련되어, 상기 지지부, 상기 보울부 및 상기 보울부에 수용되는 반려동물용 사료 또는 물의 무게를 측정하는 무게센서부; 반려동물용 사료 또는 물을 제공하는 유저의 단말과 통신할 수 있는 통신부; 및상기 무게센서부에서 측정된 무게 정보로부터 반려동물에게 제공된 반려동물용 사료 또는 물의 양 또는 반려동물이 섭취한 사료 또는 물의 양을 산출하여 상기 통신부를 통하여 유저의 단말에 전송하는 제어부; 를 포함하고,상기 보울부에서 유출된 물이 상기 제 1 수용부 내부에 수용될 수 있도록, 상기 제 2 수용부는 상기 제 1 수용부로부터 소정거리 이격되어 지지되고,상기 제 1 수용부의 하단에는 상기 본체부의 내부공간과 연통하는 개구가 형성되고,상기 개구의 둘레를 따라 상측으로 돌출되는 제 1 격벽이 형성되고,상기 제 2 수용부의 하단에는 상기 개구를 관통하여 상기 본체부의 내부공간과 연통하는 돌출홈이 형성되고,상기 무게센서부는 상기 돌출홈과 결합하고,상기 제 1 수용부 내부에 수용된 물이 상기 본체부 외측으로 흐를 수 있도록 상기 제 1 수용부에는 상기 본체부를 관통하는 배수구가 형성되고,상기 제 1 수용부는, 그 상단부 둘레를 따라 상측으로 돌출하는 제 2 격벽을 포함하고,상기 보울부에서 유출된 물이 상기 제 1 수용부 내부로 흐를 수 있도록, 상기 제 2 격벽의 외주면 둘레에는 관통유로가 형성되는 것을 특징으로 하는, IOT 반려동물용 스마트 식기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

748/1059 Row 748: application_number: 1020200126788, combined_string: invention_title: 정자의 동결보존제 스트레스 저항성 판별용 조성물 abstract: 본 발명은 동결보존제 스트레스 저항성 정자와 민감성 정자간의 NT5C1B, FH, CAPZB, VDAC2, 및 UQCRC1 단백질 발현 수준에 차이가 있음을 확인하여, 상기 단백질을 동결보존제 스트레스 저항성 마커로 제공하고, 상기 마커의 발현을 측정하는 물질을 포함하는 동결보존제 스트레스 저항성 판별용 조성물 등을 제공하는 것으로서, 본 발명의 제공에 의해 가축인공수정시 동결정액의 품질평가에 소요되는 비용 및 시간을 절감할 수 있고, 동결보존제에 의해 운동성, 생존성, 및 수정능획득이 저하되지 않는 고품질의 정자를 선별하여 인공수정의 성공률을 높이고 그 비용을 절감할 수 있을 것으로 기대된다. claims: NT5C1B (Cytosolic 5’-Nucleotidase 1B), CAPZB (F-actin-capping protein subunit beta), VDAC2 (Voltage-dependent anion-selective channel protein 2), UQCRC1 (Cytochrome b-c1 complex subunit 1), 및 FH (Fumarate hydratase)로 이루어진 군으로부터 선택되는 하나 이상의 동결보존제 스트레스 저항성 마커, 상기 마커를 코딩하는 유전자, 또는 상기 유전자의 mRNA를 검출하는 물질을 유효성분으로 포함하는 것을 특징으로 하는, 정자의 동결보존제 스트레스 저항성 판별용 조성물.제4항에 있어서,상기 동결보존제는 TYB(tris-egg yolk buffer) 및 글리세롤(glycerol); 폼아마이드(fomamide); 프로판디올(propanediol); DMSO(Dimethyl sulfoxide); 및 아도니톨(adonitol)로 이루어지는 군으로부터 선택되는 하나 이상을 포함하는 것을 특징으로 하는, 동결보존제 스트레스 저항성 정자를 판별하기 위한 정보제공방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

749/1059 Row 749: application_number: 1020200127111, combined_string: invention_title: 가축의 발정기 정보 획득 시스템 및 방법 abstract: 본 발명은 개체 정보 획득 및 표시 시스템 및 방법에 관한 것으로서, 센서-통신망 구축을 통하여 광활한 초지에서 방목하는 가축으로부터 각각의 개별 생체정보 및 위치정보를 효과적으로 취득하고, 그 정보를 가축에 부착된 표시부에 표시함으로써 가축의 관리에 효과적으로 활용할 수 있는 개체 정보 획득/표시 시스템 및 방법에 관한 것이다. 또한 본 발명은 가축의 발정기, 수정, 분만에 관한 정보를 효과적으로 취득하고 이를 표시부에 표시하여 육안식별 가능한 장치를 제공한다. claims: 둘 이상의 개체로부터 그 생체정보 및 위치정보를 포함하는 개체 정보를 획득하는 시스템에 있어서,각 개체의 질 내와 외부에 걸쳐 장착되어 개체의 생체정보를 획득하는 제1 식별장치;각 개체의 체외에 부착되어 개체의 위치정보를 획득하고, 상기 제1 식별장치가 획득한 생체정보를 수신하여 개체의 생체정보 및 위치정보를 포함하는 개체 정보를 획득하는 제2 식별장치;상기 제2 식별장치들로부터 개체의 생체정보 및 위치정보를 수신하는 중계기 네트워크;를 포함하여 구성되며,상기 제1 식별장치는,개체의 질 내에 삽입 안착되어, 개체의 발정기, 수정, 분만에 관련된 정보를 수집하는 본체부;개체의 체외에 노출되어 상기 본체부로부터 수집된 생체 정보를 이용하여 상기 개체의 발정기, 수정, 분만에 관련된 정보를 표시하는 표시부;상기 본체부와 표시부를 연결하여 본체부로부터 표시부로 데이터와 전력을 송신하는 연결부;를 포함하여 구성되며,상기 표시부와 본체부는 연결부를 통하여 상호 연결된 상태로, 상기 본체부는 개체의 질 내에 삽입/안착되고, 상기 표시부는 체외로 노출되며,상기 제2 식별장치는 다른 개체의 제2 식별장치로부터 상기 다른 개체의 생체정보 및/또는 위치정보를 추가로 수신하는 것을 특징으로 하며, 상기 생체정보는 개체의 발정, 수정, 분만에 관련된 정보인 것을 특징으로 하는 개체 정보 획득 시스템.가축의 발정기, 수정, 분만에 관련된 생체정보를 수집하는 생체정보 수집장치로서, 가축의 질 내에 삽입 안착되어, 가축의 발정기, 수정, 분만에 관련된 생체 정보를 수집하는 본체부;가축의 체외에 노출되어 상기 본체부로부터 수집된 생체 정보를 이용하여 상기 가축의 발정기, 수정, 분만에 관련된 정보를 표시하는 표시부;상기 본체부와 표시부를 연결하여 본체부로부터 표시부로 데이터와 전력을 송신하는 연결부;를 포함하여 구성되며,상기 표시부와 본체부는 연결부를 통하여 상호 연결된 상태로, 상기 본체부는 가축의 질 내에 삽입/안착되고, 상기 표시부는 체외로 노출되는 것을 특징으로 하고,상기 본체부는,가축의 질 내부의 영상/열영상을 취득하는 센서모듈; 및 상기 센서모듈의 외부에 노출되어 상기 질 내의 온도, 분비물의 PH, 전기 전도도, 농도를 측정하는 센서감지부; 를 포함하여 구성되어, 상기 취득한 질 내부의 영상/열영상과 상기 측정된 질 내의 온도, 분비물의 PH, 전기 전도도, 농도를 기반으로 가축의 발정기, 수정, 분만에 관련된 생체정보를 수집하는 것을 특징으로 하는 생체정보 수집 장치.둘 이상의 개체로부터 그 생체정보 및 위치정보를 포함하는 개체 정보를 획득하는 방법에 있어서,개체의 질 내로 제1 식별장치의 본체부를 삽입 안착하고 안착시켜 개체의 발정기, 수정, 분만에 관련된 체내 생체정보를 획득하는 생체정보 획득단계;수집한 생체정보를 근거로 표시 이벤트를 판정하는 이벤트 판정단계;상기 판정된 이벤트 정보를 상기 제1 식별장치의 본체부로부터 연장되어 개체의 체외로 노출된 표시부로 전송하는 이벤트 정보 전송단계;상기 판정된 이벤트 정보를 상기 개체의 질 내에 삽입 안착된 본체부와 연결되어 체외로 노출된 표시부에서 시각적으로 표시하는 생체정보 표시단계;개체의 체외에 부착되는 제2 식별장치가 개체의 위치정보를 획득하고, 상기 제1 식별장치로부터 개체의 생체정보를 수신 받아, 개체의 생체정보 및 위치정보를 포함하는 개체 정보를 생성하는 개체 정보 생성단계;상기 생성한 개체 정보를 중계기 네트워크로 전송하는 개체 정보 전송단계;를 포함하며,상기 개체 정보 전송단계는, 상기 제2 식별장치가 다른 개체의 제2 식별장치로부터 다른 개체의 개체 정보를 수신하여 이를 전송하는 단계를 추가로 포함하며, 상기 제1 식별장치가 획득하는 생체정보는 개체의 발정, 수정, 분만에 관련된 정보인 것을 특징으로 하는 개체 정보 획득 및 표시 방법.가축의 체내에서 생체정보를 수집하고 이를 시각적으로 표시하는 방법으로서, 가축의 질 내로 제1 식별장치를 삽입하고 상기 제1 식별장치를 통해 질 내부의 영상/열영상 및 온도, 분비물의 PH, 전기 전도도, 농도 데이터를 획득하여 이를 바탕으로 체내 생체정보를 수집하는 생체정보 수집단계;수집한 생체정보를 근거로 표시 이벤트를 판정하는 이벤트 판정 단계;상기 판정된 이벤트 정보를 시각적으로 표시하는 시각표시 단계;상기 생체정보 수집단계에서 수집된 생체정보를 가축의 체외에 부착된 제2 식별장치를 통하여 서버로 전송하는 생체정보 전송단계;를 포함하여 이루어지며,상기 이벤트 판정단계는 제2 식별장치에서 진행되며,상기 시각표시 단계는, 상기 제2 식별장치의 표시부에 상기 판정된 이벤트 정보를 시각적으로 표시하는 것; 을 특징으로 하는 생체정보 수집 및 표시 방법., Ltext: 농업, prediction: 임업
750/1059 Row 750: application_number: 2020200003500, combined_string: invention_title: 폭식방지용 반려동물 식기 abstract: 본 고안은 반려동물, 특히 반려견의 성장속도와 적정 식사량에 맞는 사료를 담을 수 있는 여러 용량(예: 대, 중, 소 용량)의 식기를 키트형으로 제공하고, 이들 식기를 측면 배열, 적층 배열, 삽입 배열 하는 등의 방식으로 다양하게 배열하며, 체결수단에 의하여 배열형태를 고정할 수 있어 반려동물의 관심을 높이고 미감도 향상시킬 수 있으며, 무엇보다도 성장속도 및 적정성에 맞는 식사를 제공하여 폭식방지 효과를 얻을 수 있는 반려동물 식기에 관한 것이다.본 고안에 따른 폭식방지용 반려동물 식기는 대용량 제1보울; 및 상기 제1보울의 측면형상에 상응하는 측면형상을 갖거나, 상기 제1보울의 상면 또는 하면 형상에 상응하는 상면 또는 하면 형상을 가져 측면 또는 상하면 접촉 배열되는 소용량 제2보울;을 포함하여 이루어진다. claims: 대용량 제1보울; 및상기 제1보울의 측면형상에 상응하는 측면형상을 갖거나, 상기 제1보울의 상면 또는 하면 형상에 상응하는 상면 또는 하면 형상을 가져 측면 또는 상하면 접촉 배열되는 소용량 제2보울;을 포함하여 이루어지되,제1보울과 제2보울은 상하면 접촉 배열되고,상하면 인접 배열되는 제1 및 제2 보울, 또는 제2보울 및 제2보울은 상호 체결수단을 갖고,상기 체결수단은 상하 배열된 제2 및 제1 보울의 접면에 구비된 체결유닛으로 구성되고, 이 체결유닛은제2보울에 구비되는 제1블록과, 제1보울에 구비되어 상기 제1블록이 인입되는 인입홀이 형성된 제2블록, 상기 제1블록 내에 구비되어 상기 인입홀에 형성된 끼움홈으로 돌출되어 고정되는 한 쌍의 고정팔 및 상기 제1블록 내부에서 승하강하여, 상기 한 쌍의 고정팔 후퇴를 제한하는 승하강봉돌을 포함하여 이루어지고,상기 제1블록이 상기 인입홀에 인입되면, 상기 승하강봉돌이 하강하여 상기 한 쌍의 고정팔을 양측으로 돌출시킴에 따라, 상기 고정팔이 상기 끼움홈에 내삽 되어 제1블록을 제2블록에 고정하고,상기 하강한 승하강봉돌이 상기 한 쌍의 고정팔 사이에 위치하여 상기 고정팔이 후퇴를 제한하여 상기 제1블록과 제2블록의 고정 상태를 유지하고,상기 제1블록 하부에는 상기 승하강봉돌 하면에 밀착되며 복귀스프링을 포함하는 복귀부재가 구비되어,상기 복귀스프링의 탄성력에 의해 상기 복귀부재가 상기 승하강봉돌의 하면을 타격하여 승하강봉을 상승시키면, 상기 고정팔의 후퇴를 허용하여 상기 제1블록을 제2블록으로부터 분리시킬 수 있도록 이루어지는 것을 특징으로 하는 폭식방지용 반려동물 식기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

751/1059 Row 751: application_number: 1020200121813, combined_string: invention_title: 축사정보에 따른 먹이공급 자동화시스템 abstract: 본 발명은 축사에서 길러지는 가축과 관리자의 이동에 방해를 주지 않고, 축사의 먹이통에 먹이를 공급하는 축사정보에 따른 먹이공급 자동화시스템을 제공하는 것을 목적으로 한다. 본 발명은 축사의 먹이통 위에서 먹이를 공급함으로써 축사에서 길러지는 가축과 관리자의 이동에 방해를 주지 않고, 축사에서 길러지는 가축 종류, 가축 생육에 요구되는 먹이 종류에 맞게 축사의 먹이통에 먹이를 공급함으로써 가축의 생육 조건을 만족시킬 수 있고, 축사의 먹이통에 먹이를 공급하는 이동식 먹이통을 다수 개 구성함으로써 먹이 공급을 끊김 없이 원활하게 하고, 가축 생육에 도움을 주는 효과를 가질 수 있다. claims: 축사(70) 위에 설치되는 레일(40);상기 레일(40)을 따라 이동하면서 상기 축사(70)의 먹이통(60)에 먹이를 공급하는 이동식 먹이통(20);상기 이동식 먹이통(20)을 이동시키는 구동부(30); 및상기 이동식 먹이통(20)에 먹이를 공급하는 호퍼(10);를 포함하고,상기 이동식 먹이통(20)은,상기 이동식 먹이통(20)에 공급되는 먹이의 양을 감지하여 기설정된 먹이양을 저장하는 저장센서(22); 및저장된 먹이양 중 상기 축사(70)의 먹이통(60)에 공급될 먹이양을 감지하여 기설정된 먹이양을 분배하는 분배센서(21);를 포함하고,상기 축사(70)의 먹이통(60)과 연결된 기둥에 표시된 식별 정보를 인식하고, 인식된 식별 정보를 참조하여 상기 먹이통(60)에 먹이를 공급하고,손상된 식별 정보를 인식하지 못하는 경우, 기둥(71)에 설치된 디스플레이(52)에 포함된 통신부와 통신해서 상기 축사(70)의 먹이통(60)에 설정된 정보를 수신하고, 수신된 정보에 따라 상기 축사(70)의 먹이통(60)에 먹이를 공급하고, 식별 정보 인식과 디스플레이(52)의 통신부 연결을 통해 정보 송수신을 이중화하여 상기 축사(70)의 먹이통(60)에 불특정 사유로 인한 먹이 공급 중단 없이 항상 먹이를 공급하고,상기 레일(40)의 전원 공급 장치(41)로부터 전원을 공급받아 동작 전원으로 사용하고, 개별 제어 또는 중앙 통제 제어되고,상기 레일(40)의 전원 공급 장치(41)는 무선 전원 공급 장치이고,상기 구동부(30)는,상기 레일(40) 상에 위치하여 상기 이동식 먹이통(20)을 연결하여 이동시키고,상기 호퍼(10)는,대용량의 먹이를 저장하고, 상기 이동식 먹이통(20)이 먹이 공급을 요청하면 상기 이동식 먹이통(20)에 기설정된 먹이양을 공급하고,기설정된 레벨 미만으로 저장된 먹이양이 줄어들면 외부 먹이 공급차(90)에 먹이 공급을 요청하고,상기 먹이 공급차(90)는,먹이 공급 요청에 응답해서 상기 호퍼(10)에 다량의 먹이를 공급하고,상기 축사(70)의 기둥(71)은,상기 축사(70)에서 양육되는 가축의 종류, 가축 마리수, 생육 정도 및 상기 이동식 먹이통(20)의 먹이 공급 회수를 표시하는 디스플레이(52)를 포함하고,상기 이동식 먹이통(20)과 상기 축사(70)의 먹이통(60)은,먹이 관로(80)로 연결되고,레일(40) 위에는 먹이 종류별로 다수의 이동식 먹이통(20)이 위치하고, 이동식 먹이통(20) 내부에 다수의 이동식 먹이통(20)이 구성되며, 이동식 먹이통(20) 내부에 구성된 다수의 이동식 먹이통(20)은 TMR(Total mixed Ration) 사료로 구성된 먹이가 종류별로 구성되는 것을 특징으로 하는, 축사정보에 따른 먹이공급 자동화시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

752/1059 Row 752: application_number: 1020200112031, combined_string: invention_title: 반려동물 행동 인식 시스템 및 그 제어방법 abstract: 본 발명은 반려동물 행동 인식 시스템 및 그 제어방법에 관한 것으로서, 반려동물 소유주가 반려동물에 행동에 따라 신속한 대응을 할 수 있도록 함을 목적으로 한 것이다.즉, 본 발명은 반려동물의 행동영상을 통하여 반려동물의 특이행동 이유를 반려동물 소유주에게 알려주는 반려동물 행동 인식 시스템을 구비하되, 상기 반려동물 행동 인식 시스템은 반려동물의 행동분석을 위한 어플이 구비되어 있게 구성한 스마트폰과 상기 스마트폰에 구비되어 소유주의 조작에 따라 반려동물의 행동을 분석할 수 있게 실행되는 반려동물행동분석어플 및 상기 스마트폰에 네트워크를 통하여 전송된 반려동물의 행동정보를 분석하여 분석된 결과를 스마트폰에 구비된 반려동물행동분석어플을 통하여 제공하는 반려동물행동분석서버로 구성한 것을 특징으로 하는 것이다.따라서, 본 발명은 반려동물 소유주가 반려동물에 행동에 따라 신속한 대응을 통하여 반려동물이 올바른 생활습관을 가지게 되는 효과와 반려동물과 소유주가 빠른시간 안정된 가족을 이루게 되는 효과를 갖는 것이다. claims: 반려동물의 행동영상을 통하여 반려동물의 특이행동 이유를 반려동물 소유주에게 알려주는 반려동물 행동 인식 시스템을 구비하되,상기 반려동물 행동 인식 시스템은 반려동물의 행동분석을 위한 어플이 구비되어 있게 구성한 스마트폰과 상기 스마트폰에 구비되어 소유주의 조작에 따라 반려동물의 행동을 분석할 수 있게 실행되는 반려동물행동분석어플 및 상기 스마트폰에 네트워크를 통하여 전송된 반려동물의 행동정보를 분석하여 분석된 결과를 스마트폰에 구비된 반려동물행동분석어플을 통하여 제공하는 반려동물행동분석서버로 구성하고;상기 반려동물행동분석어플은 스마트폰의 바탕화면에 디스플레이되어 소유주 반려동물행동분석어플을 실행할 수 있게 구비한 반려동물행동분석아이콘과 상기 반려동물행동분석아이콘의 터치에 따라 소유주가 반려동물행동분석을 진행할 수 있게 팝업되는 반려동물행동촬영창, 상기 반려동물행동촬영창에 반려동물의 행동을 촬영할 수 있게 구비되는 반려동물행동촬영버튼, 상기 반려동물행동촬영창에 반려동물행동촬영버튼의 조작에 따라 반려동물행동영상이 취득되면 소유주가 반려동물행동분석을 위하여 행동분석을 실행하는 행동분석실행버튼, 상기 행동분석실행버튼에 따라 실행되는 반려동물의 행동분석을 위하여 반려동물환경정보를 입력할 수 있게 팝업되는 반려동물환경정보창부, 상기 반려동물환경정보창부를 통한 반려동물환경정보의 입력완료에 따라 반려동물행동영상 및 반려동물환경정보를 네트워크를 통하여 전송받은 반려동물행동분석서버가 반려동물행동에 따라 분석하여 전송한 정보를 표시할 수 있게 팝업되는 반려동물행동분석창, 상기 반려동물행동분석창을 통하여 제공된 분석정보에 따라 소유주가 반려동물에게 조치할 분석정보의 선택에 따라 조치 영상을 촬영할 수 있게 팝업되는 조치영상촬영창 및 상기 조치영상촬영창을 통하여 촬영 취득된 조치영상을 촬영완료에 따라 반려동물행동분석서버로 전송하는 조치영상전송부로 구성하며;상기 반려동물행동분석서버는 네트워크를 통한 소유주의 접속을 관리할 수 있게 구비한 접속관리부와 행동분석대상 반려동물의 소유주로부터 전달된 반려동물의 행동영상정보와 반려동물의 환경정보를 축적된 행동분석데이터와 비교연산하여 반려동물의 행동에 따른 대응정보를 제공할 수 있게 구비한 반려동물행동분석부, 상기 반려동물행동분석부로부터 제공된 행동분석정보를 소유주에게 전달하는 반려동물행동분석정보제공부, 반려동물행동분석서버로부터 제공된 행동분석정보와 현재 반려동물의 행동상태와 일치 여부를 소유주가 체크한 정보를 분석하여 저장할 수 있게 구비한 반려동물행동피드백분석부 및 반려동물행동별 분석정보가 저장되고 소유주로부터 피드백된 데이터가 저장할 수 있게 구비한 반려동물행동분석데이터부로 구성한 것을 특징으로 하는 반려동물 행동 인식 시스템.반려동물 행동 인식 시스템의 제어방법은 스마트폰에 구비된 반려동물행동분석아이콘의 클릭에 따라 반려동물행동분석을 위한 반려동물행동촬영창이 팝업되는 반려동물행동분석실행과정과 상기 반려동물행동분석실행과정을 통하여 팝업된 반려동물행동촬영창의 반려동물행동촬영버튼의 클릭을 통하여 반려동물의 행동을 촬영하는 반려동물행동촬영과정, 반려동물행동촬영과정을 통하여 촬영된 행동영상을 반려동물행동분석서버로 전송하는 반려동물행동분석의뢰과정, 상기 스마트폰으로부터 전송된 영상을 반려동물행동분석데이터부와 비교연산하여 반려동물의 행동을 분석하는 반려동물행동분석과정, 상기 반려동물행동분석과정을 통하여 분석된 3가지 이상의 분석결과를 의뢰자의 스마트폰으로 전송하는 반려동물행동분석결과제공과정, 상기 반려동물행동분석결과제공과정을 통하여 반려동물행동분석창에 표시된 분석결과에 따라 알맞은 조치사항을 반려동물에게 실행하는 반려동물분석조치실행과정, 상기 반려동물분석조치실행과정을 통하여 반려동물에게 알맞은 조치를 실행하는 과정을 촬영하는 반려동물분석조치실행촬영과정, 상기 반려동물분석조치실행과정을 통하여 반려동물행동에 알맞은 조치의 실행항목을 선택표시하는 반려동물분석일치체크과정, 상기 반려동물분석일치체크과정을 통하여 알맞은 조치에 해당하는 조치영상을 반려동물행동분석서버로 제공하는 반려동물조치영상제공과정 및 상기 스마트폰으로부터 전달된 반려동물 조치결과를 반려동물행동분석데이터부에 저장하여 반려동물행동과 그 조치실행을 학습하는 반려동물행동학습과정으로 이루어지고;상기 반려동물행동분석의뢰과정의 실행과 연동하여 반려동물의 환경정보를 반려동물행동분석서버로 제공할 수 있게 반려동물의 환경정보를 입력하는 반려동물행동정보제공과정으로 이루어지며;상기 반려동물행동정보제공과정은 날씨정보입력창을 통하여 현재의 기상정보와 온도 및 습도의 정보를 입력하는 날씨정보입력단계와 사육정보입력창을 통하여 반려동물의 사용장소와 반려동물의 집 종류를 입력하는 사육정보입력단계, 취식입력창을 통하여 반려동물의 취식하는 사료종류와 취식횟수를 입력하는 취식입력단계, 배변습관입력창을 통하여 반려동물의 배변 횟수와 배변장소 정보를 입력하는 배변습관입력단계로 이루어지는 것을 특징으로 하는 반려동물 행동 인식 시스템의 제어방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

753/1059 Row 753: application_number: 1020200108851, combined_string: invention_title: 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 방법과 그 시스템 abstract: [기술분야/해결과제]본 발명은 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 방법과 그 시스템에 관한 것으로, 반려동물의 홍채 이미지 정보와 반려동물정보(소유주, 연락처, 반려동물의 종류, 이름, 나이, 암수, 특징 등)를 데이터화하여 대용량 서버에 등록 및 공개함으로써, 반려동물의 홍채 인식을 통해 반려동물정보를 실시간으로 추적 및 확인이 가능하고 유기를 방지할 수 있다.[해결수단]본 발명에 의한 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 시스템은, 반려동물의 양쪽 눈과 코 부분을 촬영하여 반려동물관리 앱을 통해 반려동물의 홍채 이미지와, 소유주, 연락처, 반려동물의 종류, 이름, 나이, 암수, 특징을 포함하는 반려동물정보를 중앙관제센터의 서버에 전송하여 등록하고, 상기 반려동물관리 앱의 사용자 인터페이스를 통해, 자신이 등록한 반려동물의 정보를 수정 및 삭제하고, 주변의 동물병원, 애견카페, 동물호텔을 검색하고 반려동물 도우미를 호출하며, 반려동물의 분실 및 유기시 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고 분실 또는 유기된 반려동물을 등록하는 회원가입자의 PC 또는 스마트폰; 상기 반려동물관리 앱을 인터넷 망을 통해 제공하고, 상기 회원가입자의 PC 또는 스마트폰으로부터 수신받은, 상기 반려동물의 홍채 이미지와 반려동물정보를 데이터베이스에 등록하고, 상기 반려동물관리 앱을 통해 반려동물의 검색 요청이 들어오면 수신된 반려동물의 홍채 이미지와 데이터베이스에 등록된 반려동물의 홍채 이미지를 종별로 분류된 패턴 알고리즘 분석을 통해 자동으로 비교 분석하여 홍채가 일치한 반려동물의 반려동물정보를 제공하고, 분실 또는 유기된 반려동물의 이미지나 영상 정보, 반려동물정보를 수신받아 유기동물 리스트에 등록하는 중앙관제센터의 서버; 상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 반려동물을 검색하거나, 또는 상기 중앙관제센터의 서버에 반려동물의 양쪽 눈과 코 부분을 촬영한 반려동물의 홍채 이미지를 전송하여 반려동물의 검색을 요청하여 검색 결과를 확인하고, 검색한 반려동물에 대한 병원치료내역을 포함한 부가정보를 입력하여 등록하며, 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고, 분실 또는 유기된 반려동물을 등록하는 동물병원, 동물보호센터, 애견카페를 포함한 관련업체의 PC 또는 스마트폰; 및 상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고, 분실 또는 유기된 반려동물을 등록하는 비회원의 PC 또는 스마트폰;을 포함한다.[기대효과]본 발명에 따르면, 반려동물의 홍채 이미지를 데이터화하여 대용량 서버에 저장하고 데이터를 분산 처리함으로써, 반려동물의 홍채 인식을 통해 반려동물의 소유주와 연락처를 파악할 수 있고 동물의 유기를 방지할 수 있는 효과가 있다. claims: 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 방법에 있어서,(a) 회원가입자의 PC 또는 스마트폰에서 중앙관제센터의 서버로부터 다운로드 받은 반려동물관리 앱을 통해, 반려동물의 양쪽 눈과 코 부분을 촬영한 반려동물의 홍채 이미지와, 소유주, 연락처, 반려동물의 종류, 이름, 나이, 암수, 특징을 포함하는 반려동물정보를 상기 중앙관제센터의 서버에 전송하여 반려동물을 등록하는 단계;(b) 상기 중앙관제센터의 서버에서 상기 회원가입자의 PC 또는 스마트폰으로부터 수신받은, 상기 반려동물의 홍채 이미지와 반려동물정보를 데이터베이스에 등록하여 인터넷으로 정보를 공유하는 단계;(c) 동물병원, 동물보호센터, 애견카페를 포함한 관련업체의 PC 또는 스마트폰에서 상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 반려동물을 검색하거나, 또는 반려동물의 양쪽 눈과 코 부분을 촬영한 반려동물의 홍채 이미지를 전송하여 상기 중앙관제센터의 서버에 등록된 반려동물의 검색을 요청하는 단계;(d) 상기 중앙관제센터의 서버에서 상기 관련업체의 PC 또는 스마트폰으로부터 수신받은 반려동물의 홍채 이미지와 데이터베이스에 등록된 반려동물의 홍채 이미지를 종별로 분류된 패턴 알고리즘 분석을 통해 자동으로 비교 분석하여 홍채가 일치한 반려동물의 반려동물정보를 검색하여 제공하는 단계; 및(e) 상기 관련업체의 PC 또는 스마트폰에서 상기 중앙관제센터의 서버로부터 제공받은 반려동물정보를 확인하고 병원치료내역을 포함한 부가정보를 입력하여 등록하는 단계;를 포함하는 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 방법.반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 시스템에 있어서,반려동물의 양쪽 눈과 코 부분을 촬영하여 반려동물관리 앱을 통해 반려동물의 홍채 이미지와, 소유주, 연락처, 반려동물의 종류, 이름, 나이, 암수, 특징을 포함하는 반려동물정보를 중앙관제센터의 서버에 전송하여 등록하고, 상기 반려동물관리 앱의 사용자 인터페이스를 통해, 자신이 등록한 반려동물의 정보를 수정 및 삭제하고, 주변의 동물병원, 애견카페, 동물호텔을 검색하고 반려동물 도우미를 호출하며, 반려동물의 분실 및 유기시 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고 분실 또는 유기된 반려동물을 등록하는 회원가입자의 PC 또는 스마트폰;상기 반려동물관리 앱을 인터넷 망을 통해 제공하고, 상기 회원가입자의 PC 또는 스마트폰으로부터 수신받은, 상기 반려동물의 홍채 이미지와 반려동물정보를 데이터베이스에 등록하고, 상기 반려동물관리 앱을 통해 반려동물의 검색 요청이 들어오면 수신된 반려동물의 홍채 이미지와 데이터베이스에 등록된 반려동물의 홍채 이미지를 종별로 분류된 패턴 알고리즘 분석을 통해 자동으로 비교 분석하여 홍채가 일치한 반려동물의 반려동물정보를 제공하고, 분실 또는 유기된 반려동물의 이미지나 영상 정보, 반려동물정보를 수신받아 유기동물 리스트에 등록하는 중앙관제센터의 서버;상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 반려동물을 검색하거나, 또는 상기 중앙관제센터의 서버에 반려동물의 양쪽 눈과 코 부분을 촬영한 반려동물의 홍채 이미지를 전송하여 반려동물의 검색을 요청하여 검색 결과를 확인하고, 검색한 반려동물에 대한 병원치료내역을 포함한 부가정보를 입력하여 등록하며, 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고, 분실 또는 유기된 반려동물을 등록하는 동물병원, 동물보호센터, 애견카페를 포함한 관련업체의 PC 또는 스마트폰; 및상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고, 분실 또는 유기된 반려동물을 등록하는 비회원의 PC 또는 스마트폰;을 포함하는 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 시스템., Ltext: 농업, prediction: 임업
754/1059 Row 754: application_number: 1020200105449, combined_string: invention_title: 반려 동물의 정보를 제공하는 방법 및 디바이스 abstract: 반려 동물의 정보를 제공하는 방법에 있어서, 상기 반려 동물의 상태 정보, 특성 정보 및 돌봄 히스토리 정보를 획득하는 단계; 공개 설정에 따라 상기 상태 정보, 상기 특성 정보 및 돌봄 히스토리 정보를 외부 디바이스에 제공하는 단계; 및 상기 상태 정보에 따라 사용자 단말의 위치 정보를 상기 반려 동물의 위치 정보로 상기 외부 디바이스에 제공하는 단계;를 포함하는 방법이 개시된다. claims: 반려 동물의 정보를 제공하는 방법에 있어서,상기 반려 동물의 상태 정보, 특성 정보 및 돌봄 히스토리 정보를 획득하는 단계;공개 설정에 따라 상기 상태 정보, 상기 특성 정보 및 돌봄 히스토리 정보를 외부 디바이스에 제공하는 단계; 및상기 상태 정보에 따라 사용자 단말의 위치 정보를 상기 반려 동물의 위치 정보로 상기 외부 디바이스에 제공하는 단계;를 포함하고,상기 상태 정보가 실종 중임을 나타내는 경우, 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 외부 디바이스에 제공하는 단계;를 더 포함하고,상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 외부 디바이스에 제공하는 단계는분실 시점으로부터 제 1 시간 동안 상기 반려 동물을 찾고 있음을 알리는 메시지를 제 1 영역 내의 동물 병원 및 동물 용품 취급점에 제공할 것을 요청하는 단계;분실 시점으로부터 상기 제 1 시간이 경과하는 경우 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 제 1 영역 내의 일반 회원에게 제공할 것을 요청하는 단계;분실 시점으로부터 상기 제 1 시간보다 큰 제 2 시간이 경과하는 경우 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 제 1 영역보다 큰 제 2 영역 내의 동물 병원, 동물 용품 취급점 및 일반 회원에게 제공할 것을 요청하는 단계;를 포함하는 방법.반려 동물의 정보를 제공하는 디바이스에 있어서,상기 반려 동물의 상태 정보, 특성 정보 및 돌봄 히스토리 정보를 획득하는 수신부; 및공개 설정에 따라 상기 상태 정보, 상기 특성 정보 및 돌봄 히스토리 정보를 외부 디바이스에 제공하고, 상기 상태 정보에 따라 사용자 단말의 위치 정보를 상기 반려 동물의 위치 정보로 상기 외부 디바이스에 제공하는 프로세서;를 포함하고,상기 프로세서는상기 상태 정보가 실종 중임을 나타내는 경우, 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 외부 디바이스에 제공하고,분실 시점으로부터 제 1 시간 동안 상기 반려 동물을 찾고 있음을 알리는 메시지를 제 1 영역 내의 동물 병원 및 동물 용품 취급점에 제공할 것을 요청하고,상기 분실 시점으로부터 상기 제 1 시간이 경과하는 경우 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 제 1 영역 내의 일반 회원에게 제공할 것을 요청하고,상기 분실 시점으로부터 상기 제 1 시간보다 큰 제 2 시간이 경과하는 경우 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 제 1 영역보다 큰 제 2 영역 내의 동물 병원, 동물 용품 취급점 및 일반 회원에게 제공할 것을 요청하는 디바이스., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

755/1059 Row 755: application_number: 1020200104424, combined_string: invention_title: 반려동물 XR 영상 체험 제공 시스템 및 방법 abstract: 반려동물 XR 영상 체험 제공 시스템이 개시된다. 반려동물에 관한 AR/VR 영상을 출력하는 사용자 단말; 상기 AR/VR 영상을 생성하여 상기 사용자 단말로 제공하는 반려동물 XR 제공 서버; 상기 반려동물 XR 제공 서버로부터 상기 AR/VR 영상을 제공받아 출력하는 헤드 마운트 디스플레이(head mount display)를 구성한다. 상술한 반려동물 XR 영상 체험 제공 시스템에 의하면, 3D 반려동물 AR 캐릭터를 다양한 VR배경 장소에 구현하여 사용자가 직접 체험할 수 있도록 구성됨으로써, 반려동물 사후에도 반려동물이 직접 살아있는 것처럼 시각과 청각을 통해 느낄 수 있는 효과가 있다. XR을 통해 다양한 배경 장소와 생전의 유사한 행동 양태를 구현하여 지금 살아 있는 것처럼 영상 체험을 할 수 있으며, 단순히 동영상이나 이미지처럼 고정된 영상이 아니므로, 지금 같이 있는 것처럼 느낄 수 있는 효과가 있다. claims: 반려동물 정보 및 장소 자료를 입력받고, 해당 장소 상의 반려동물에 관한 AR/VR 영상을 제공받아 출력하는 사용자 단말;상기 장소 상의 반려동물에 관한 AR/VR 영상을 제공받아 출력하는 헤드 마운트 디스플레이;상기 사용자 단말에서 입력받은 반려동물 정보 및 장소 자료에 기반하여 해당 장소 상의 반려동물에 관한 AR/VR 영상을 생성하고, 생성된 AR/VR 영상을 상기 사용자 단말 또는 상기 헤드 마운트 디스플레이로 제공하는 반려동물 XR 제공 서버를 포함하고,상기 반려동물 XR 제공 서버는,상기 반려동물 정보를 상기 사용자 단말로부터 수집하는 반려동물 정보 수집 모듈;상기 반려동물 정보 수집 모듈에서 수집된 반려동물 정보 중 반려동물 이미지가 저장되는 반려동물 이미지 데이터베이스;상기 반려동물 정보 수집 모듈에서 수집된 반려동물 정보 중 반려동물 동영상이 저장되는 반려동물 동영상 데이터베이스;상기 반려동물 정보 수집 모듈에서 수집된 반려동물 정보 중 반려동물 행동 정보가 저장되는 반려동물 행동 데이터베이스;상기 반려동물 정보 수집 모듈에서 수집된 반려동물 정보 중 반려동물 경험 정보가 저장되는 반려동물 경험 데이터베이스;상기 반려동물 이미지 데이터베이스에 저장된 반려동물 이미지, 상기 반려동물 동영상 데이터베이스에 저장된 반려동물 동영상, 상기 반려동물 행동 데이터베이스에 저장된 반려동물 행동 정보 및 상기 반려동물 경험 데이터베이스에 저장된 반려동물 경험 정보를 이용하여 해당 반려동물의 3D 반려동물 AR 캐릭터를 생성하는 반려동물 AR 캐릭터 생성 모듈;상기 사용자 단말로부터 특정 장소의 이미지 또는 동영상을 수집하는 장소 자료 수집 모듈;상기 장소 자료 수집 모듈에서 수집된 소정의 장소의 이미지 또는 동영상이 저장되는 특정 장소 데이터베이스;국내 장소의 이미지 또는 동영상이 미리 저장되는 국내 장소 데이터베이스;국외 장소의 이미지 또는 동영상이 미리 저장되는 국외 장소 데이터베이스;상기 특정 장소 데이터베이스에 저장된 특정 장소의 이미지 또는 동영상, 상기 국내 장소 데이터베이스에 저장된 국내 장소의 이미지 또는 동영상, 상기 국외 장소 데이터베이스에 저장된 특정 장소의 이미지 또는 동영상 중 어느 하나를 이용하여 VR 배경 장소를 구현하는 VR 배경 구현 모듈;상기 사용자 단말 또는 상기 헤드 마운트 디스플레이로부터 사용자 명령을 입력받는 사용자 인터페이스 모듈;상기 사용자 인터페이스 모듈에서 입력받는 사용자 명령에 따라 상기 반려동물 AR 캐릭터 생성 모듈이 3D 반려동물 AR 캐릭터를 생성하도록 제어하고, 상기 사용자 명령에 따라 상기 VR 배경 구현 모듈이 VR 배경 장소를 생성하도록 제어하는 AR/VR 제어 모듈;상기 AR/VR 제어 모듈의 제어에 따라 해당 VR 배경 장소에서 해당 3D 반려동물 AR 캐릭터가 생성되어 동작하는 AR/VR 영상을 구현하여 상기 사용자 단말 또는 상기 헤드 마운트 디스플레이로 제공하는 AR/VR 제공 모듈;상기 AR/VR 제어 모듈의 제어에 따라 가상 장례 빈소를 구현하여 온라인을 통해 제공하며, 장례식 배경 화면에 3D 반려동물 AR 캐릭터를 구현하도록 구성되며, 상기 가상 장례 빈소에는 상주의 빈소 구축, 추모록, 조의금, 안내 메시지 보내기의 기능이 구현되고 조문객의 빈소 입장, 추무록 작성, 조의금 보내기 기능이 구현되는 가상 장례 구축 모듈을 포함하고,상기 반려동물 AR 캐릭터 생성 모듈은,상기 3D 캐릭터에 해당 반려동물의 표정, 움직임, 습관 및 성향을 포함하는 정보가 반영된 움직임 및 동작을 반영하도록 구성되는 것을 특징으로 하는 반려동물 XR 영상 체험 제공 시스템., Ltext: 농업, prediction: 임업
756/1059 Row 756: application_number: 1020200101331, combined_string: invention_title: 자동으로 개폐되는 사료배식기 abstract: 본 발명은 사료와 물을 내장하여 반려동물 접근시 내장된 사료와 물을 제공할 수 있도록 자동으로 개폐되는 사료배식기에 관한 것으로서, 보다 상세하게는 반려동물의 접근유무에 따라 배식기 본체프레임을 덮는 커버프레임이 자동으로 구동되며, 반려동물 접근시 커버프레임이 개방되어 내장된 사료와 물을 제공할 수 있도록 자동으로 개방되고, 반려동물이 사료나 물을 섭취하지 않는 경우에는 커버프레임이 자동으로 폐쇄되어 외부 이물질로부터 사료 및 물을 보호할 수 있으며, 이를 통해 사료 및 물과 배식기 내부를 청결하게 유지할 수 있는 자동으로 개폐되는 사료배식기에 관한 것이다. claims: 반려동물 접근유무에 따라 자동으로 개폐되는 사료배식기에 있어서,사료가 구비되는 배식볼이 내장되는 본체프레임과, 상기 본체프레임의 상면에 결합되어 회동을 통해 상기 배식볼을 개방 또는 폐쇄시키는 커버프레임으로 구성되는 배식기; 상기 본체프레임과 상기 커버프레임를 결합시키며, 모터에 의해 구동되어 상기 커버프레임를 회전시키는 기어부; 상기 본체프레임 정면측 상면에 구비되어 반려동물의 접근을 감지하는 감지조작부; 및 상기 감지조작부로부터 전달된 센서값을 통해 상기 기어부를 조작하여 반려동물이 상기 배식기로 접근여부에 따라 상기 배식기를 개폐시키는 제어부;로 구성되며,상기 커버프레임의 하면에는 상기 배식볼의 가장자리와 대응되는 형상을 가진 밀착패킹;이 형성되어 상기 본체프레임과 상기 커버프레임간의 틈새를 마감하고,상기 기어부는, 일단이 상기 본체프레임에 내장되어 결합고정되고, 타단이 상기 커버프레임과 결합되는 결합기어; 상기 본체프레임에 내장된 상기 결합기어의 일단을 관통하는 회전봉; 상기 회전봉을 회전시켜 상기 커버프레임을 회동시키는 모터; 및 상기 회전봉에 수평관통결합되며, 상기 모터와 밀착결합되는 회전가이드;로 구성되고,상기 회전가이드는 내각이 상기 커버프레임의 회동반경에 대응되는 부채꼴 형상을 가지며, 상기 모터의 외측과 상기 회전가이드가 기어결합되어 상기 모터 구동시 상기 회전가이드를 통해 상기 회전봉이 회전되며,상기 감지조작부는, 상기 본체프레임에서 상기 배식볼이 인입되는 측에 구비되어 상기 배식볼의 무게를 감지하는 무게감지센서;가 추가로 포함되며, 상기 무게감지센서는 감지된 사료잔존량을 상기 제어부로 전달하고,상기 제어부는, 상기 기어부의 구동여부를 제어하여 상기 배식기의 개폐여부를 조절할 수 있는 제어모듈; 상기 감지조작부로부터 전달받은 센서값을 통해 상기 배식기의 개폐여부 및 사료섭취량을 판단하는 판단모듈; 사용자 단말기와 연결되며, 상기 감지조작부를 통해 상기 배식볼 내부환경을 상기 사용자 단말기로 전달하는 통신모듈; 및 상기 배식기의 개폐여부를 판단하도록 상기 판단모듈이 상기 감지조작부로부터 전달된 센서값과 비교하는 설정값이 기저장되는 저장모듈;로 구성되고,상기 설정값은 일일사료섭취량 및 일정시간 내 사료섭취량을 포함하고, 상기 판단모듈은 상기 센서값이 상기 설정값을 초과하는 경우 반려동물에 접근에도 상기 배식기가 개방되는 것을 방지하도록 상기 제어모듈을 통해 상기 기어부를 제어하는 것을 특징으로 하는 자동으로 개폐되는 사료배식기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

757/1059 Row 757: application_number: 1020200100415, combined_string: invention_title: 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템 및 방법 abstract: 본 발명은 적어도 하나의 판매자 단말기(300) 및 구매자 단말기(200)와 네트워크망(500)을 통해 연결되는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템(100)으로서, 판매자 정보, 구매자 정보, 가축개량정보 및 가축 유전체 정보를 저장하는 데이터베이스부(120); 상기 판매자 단말기(300)에 의해 등록된 가축에 대한 유전정보, 혈통정보 및 번식정보를 수집하여 유전 능력을 분석하고, 가축의 유전능력을 통한 응찰가를 제시하고, 상기 판매자와 구매자가 가격에 합의하면 거래를 성사시키는 서버(110)를 포함한다. 이러한 본 발명의 실시예에서는, 유전체 기반의 정확한 능력 예측 시스템을 통해 고능력 가축과 저능력 가축은 물론, 가축의 유전적 능력에 따른 개량 솔루션을 농가에 제공할 수 있다. claims: 적어도 하나의 판매자 단말기(300) 및 구매자 단말기(200)와 네트워크망(500)을 통해 연결되는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템(100)의 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 방법으로서,상기 판매자 단말기(300)가 접속하면, 서버(110)가 판매를 원하는 가축 정보를 수신하여 등록하는 단계;서버(110)가 등록 가축에 대한 유전정보, 혈통정보 및 번식정보를 수집하는 단계;서버(110)가 수집된 정보를 이용하여 등록가축의 유전 능력을 분석하여 저장하는 단계를 포함하는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 방법.적어도 하나의 판매자 단말기(300) 및 구매자 단말기(200)와 네트워크망(500)을 통해 연결되는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템(100)으로서,판매자 정보, 구매자 정보, 가축개량정보 및 가축 유전체 정보, 농가정보를 저장하는 데이터베이스부(120);상기 판매자 단말기(300)에 의해 등록된 가축에 대한 유전정보, 혈통정보 및 번식정보, 표현형정보를 수집하여 유전능력을 분석하고, 가축의 유전능력를 통한 응찰가를 제시하고, 상기 판매자와 구매자가 가격에 합의하면 거래를 성사시키는 서버(110)를 포함하는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

758/1059 Row 758: application_number: 1020200098903, combined_string: invention_title: 가축의 건강상태 측정용 가속도 센서의 운용 방법 abstract: 실시예는 가축의 건강상태 측정용 가속도 센서의 운용 방법에 관한 것이다.구체적으로, 이러한 가속도 센서의 운용 방법은 가축의 건강상태 측정장치에 사용되는 제어부가 개체 운동성을 측정하는 가속도 센서와 개체 생체온도를 측정하는 온도 센서와 연동하여 개체 상태를 검출해서 외부의 관리 정보처리장치로 무선 전송함으로써, 가축의 건강상태를 측정할 수 있도록 하는 방법을 전제로 한다.이러한 상태에서, 상기 가속도 센서의 운용 방법은 기준단위 시간 당 고정형태에 따른 횟수의 데이터 수집 여부를 결정하는 샘플링 주기와, 수집된 데이터가 미리 설정된 임계값을 넘는 경우에 알람하도록 하는 인터럽트 값을 미리 설정하는 제 1 단계;초기상태에는 상기 가속도 센서의 절대 위치를 가지고 임계값을 설정하여 고정상태를 확인하고, 고정상태 이후에는 인터럽트 형태를 상대위치 값을 가지고 발생하도록 변경하는 제 2 단계;상기 가속도 센서로부터 인터럽트 값이 감지된 경우에 인터럽트 값이 측정된 상태 이전과 이후의 미리 설정된 시간간격의 값을 상기 가속도 센서로부터 읽어 들여서 유효한 값으로 설정하는 제 3 단계;상기 설정 후에 미리 설정된 시간 경과시마 상기 가속도 센서로부터 각 축의 값을 측정하여 벡터 값으로 변환해서 이전에 측정된 벡터 값과 비교하는 동작을 이후 미리 설정된 시간 동안 인터럽트 값이 연속적으로 발생되지 않을시까지 수행하는 제 4 단계; 및상기 비교 결과를 기반으로 스칼라 값이 가장 큰 벡터를 외부의 관리 정보처리장치로 제공할 데이터로 결정하고, 데이터 수집 주기 내에 다수의 인터럽트가 발생한 경우에는 인터럽트의 발생 횟수와 가장 큰 스칼라 값을 가지는 벡터로 결정함으로써, 개체 운동성을 검출할 수 있도록 하는 제 5 단계; 를 포함하는 것을 특징으로 한다.따라서, 이를 통해 기존에 가축의 건강상태 체크시에 단순히 가속도 센서를 이용해서 가축의 생체 정보를 획득할 경우에 발생하는 여러 문제점을 해결하고(예: 고정상태와 안착상태의 신뢰성 있는 확인, 정확하고 효과적인 개체의 생체정보 획득 등) 보다 효과적으로 가축의 생체 정보를 획득한다. claims: 가축의 건강상태 측정장치에 사용되는 제어부가 개체 운동성을 측정하는 가속도 센서와 개체 생체온도를 측정하는 온도 센서와 연동하여 개체 상태를 검출해서 외부의 관리 정보처리장치로 무선 전송함으로써, 가축의 건강상태를 측정할 수 있도록 하는 방법에 있어서,가축의 위 내에서 캡슐의 고정 상태를 확인하기 위하여 가속도 센서의 기준단위 시간당 데이터 수집 횟수를 결정하는 샘플링 주기와, 수집된 데이터가 미리 설정된 임계값을 넘는 경우에 알람하도록 하는 인터럽트 값을 미리 설정하는 제 1 단계;캡슐이 삽입되는 초기상태에는 상기 가속도 센서의 절대 위치를 가지고 임계값을 설정하여 상기 캡슐이 위 내에 안착한 고정상태를 확인하고, 고정상태 이후에는 인터럽트 형태를 상기 가속도 센서의 상대위치 값을 가지고 발생하도록 변경하는 제 2 단계;상기 가속도 센서로부터 인터럽트 값이 감지된 경우에, 인터럽트 값이 측정된 상태 이전과 이후의 미리 설정된 시간간격의 값을 유효한 값으로서 상기 가속도 센서로부터 읽어 들여 설정하는 제 3 단계;상기 설정 후에 미리 설정된 시간이 경과될 때마다, 상기 가속도 센서로부터 각 축의 값을 측정하여 벡터 값으로 변환해서 이전에 측정된 벡터 값과 비교하는 동작을 미리 설정된 시간 동안 인터럽트 값이 연속적으로 발생되지 않을시까지 수행하는 제 4 단계; 및상기 비교 결과를 기반으로 스칼라 값이 가장 큰 벡터를 외부의 관리 정보처리장치로 제공할 데이터로 결정하고, 데이터 수집 주기 내에 다수의 인터럽트가 발생한 경우에는 상기 관리 정보처리장치로 제공할 데이터를 인터럽트의 발생 횟수와 가장 큰 스칼라 값을 가지는 벡터로 결정함으로써, 개체 운동성을 검출할 수 있도록 하는 제 5 단계; 를 포함하고,상기 제 4 단계 후에,상기 비교 결과를 기반으로 변환된 현재의 벡터 값이 미리 설정된 승가(마운트) 운동에 따른 벡터 값에 해당하는지의 여부를 판별하는 제 5-2 단계; 및상기 판별 결과, 현재의 벡터 값이 상기 승가(마운트) 운동에 따른 벡터 값에 해당하는 경우 발정 상태 알림신호를 관리자 단말기로 제공할 수 있도록 하고, 현재의 벡터 값이 상기 승가(마운트) 운동에 따른 벡터 값에 해당하지 않는 경우 발정 상태 알림신호 자체를 발생하지 않는 제 6 단계; 를 포함하고,상기 제 1 단계 전에,개체에 구비된 자력 센서에 대한 자성체의 근접 여부와, 근접의 지속 시간에 따라 발생하는 상이한 자력 상태를 기반으로 LED램프의 발광 동작을 상이하게 제어함으로써, 측정을 위해 미리 설정된 저전력 대기 모드와 실행 모드를 토글하는 단계; 를 더 포함하고,상기 토글하는 단계는,상기 자력 센서의 신호가 미리 설정된 시간 동안 유지 되는지를 확인하여 유지될 경우, 상기 LED램프를 온시키고, 유지가 되지 않을 경우에는 상기 자력 센서의 신호를 무시하고 다시 대기 모드 상태로 되며,다시 저전력 대기 모드 상태로 변경하기 위해서, 실행 모드에서 상기 자력 센서의 신호를 미리 설정된 시간 동안 유지 시킨 경우에, 상기 LED램프를 깜박이도록 동작시켜서 상기 자력 센서에 의한 파워 오프(Power Off) 절차가 1번 인식되었음을 알리고,다음, 자석을 멀리하여 상기 자력 센서의 신호를 없애고 미리 설정된 시간 이내에 다시 자석을 가까이 하여 상기 자력 센서의 신호를 미리 설정된 시간 동안 유지한 경우에는 상기 LED램프를 깜박이도록 동작시켜서 2번째 절차가 인식되었음을 알리고,상기 절차가 인식되었음을 알리는 동작을 미리 설정된 횟수만큼 반복하여 실행한 경우, 저전력 대기모드 상태로 진입하는 것; 을 특징으로 하는 가축의 건강상태 측정용 가속도 센서의 운용 방법., Ltext: 농업, prediction: 임업
759/1059 Row 759: application_number: 1020200097124, combined_string: invention_title: 축사용 급수장치 abstract: 본 발명은 축사용 급수장치에 관한 것으로서, 가축에게 공급할 물이 유동하도록 구비되는 급수관; 상기 급수관의 내부와 연통되게 결합되면서 상기 급수관 내부의 물이 외부로 배출되도록 상기 급수관의 길이 방향으로 일정 간격마다 형성되는 급수니플; 상기 급수니플이 결합된 급수관의 상부에서 상기 급수관이 견고하게 고정되도록 지지하는 고정관; 상기 급수관의 상기 급수니플들 하부에서 상향 개방되는 관형의 형상으로 형성되어 상기 급수니플을 통해 떨어지는 물을 받을 수 있도록 구비되는 물받이관; 상기 고정관과 상기 급수관과 함께 물받이관을 동시에 축지지하면서 일정 길이의 간격으로 구비되는 밴드 클램프의 결합으로 이루어지게 함으로써 사육장을 보다 위생적으로 유지 관리할 수 있도록 하는 것이다. claims: 가축에게 공급할 물이 유동하도록 구비되는 급수관(10);상기 급수관(10)의 내부와 연통되게 결합되면서 상기 급수관(10) 내부의 물이 외부로 배출되도록 상기 급수관(10)의 길이 방향으로 일정 간격마다 형성되는 급수니플(20);상기 급수니플(20)이 결합된 급수관(10)의 상부에서 상기 급수관(10)이 견고하게 고정되도록 지지하는 고정관(30);상기 급수관(10)의 상기 급수니플(20)들 하부에서 상향 개방되는 원형관 또는 U자형 관형의 형상으로 형성되어 상기 급수니플(20)을 통해 떨어지는 물을 받을 수 있도록 구비되는 물받이관(40);상기 고정관(30)과 상기 급수관(10)과 함께 물받이관(40)을 동시에 축지지하면서 일정 길이의 간격으로 구비되는 밴드 클램프(50);를 포함하되,상기 고정관(30)은 결합되는 상기 밴드 클램프(50)의 회전 방지를 위하여 각형의 관형상으로 이루어지며,상기 밴드 클램프(50)는상단부의 고정관 삽입부(51)와 그 하부의 급수관 삽입부(52) 및 그 하부의 물받이관 삽입부(53)를 형성하고, 물받이관(40)을 감싸는 물받이관 삽입부(53)가 하향 만곡지게 절곡되도록 하면서 상기 물받이관(40)의 주면을 감싸도록 하는 물받이관 삽입부(53)를 기준으로 상기 고정관(30)을 감싸도록 하는 고정관 삽입부(51)의 상호 양측으로 분리되도록 하여 양측이 일정 폭으로 벌어졌다 복원되는 탄성력을 갖도록 하는 것을 특징으로 하는 축사용 급수장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

760/1059 Row 760: application_number: 1020200096506, combined_string: invention_title: 반려 동물 판매 시스템 abstract: 본 발명은 본 발명은 적어도 제1 내지 제6 반려 동물(10, 20, 30, 40, 50, 60)의 실시간 동영상을 전시하는 초기화 화면; 상기 초기화 화면에서 제5 반려 동물(50)을 선택하면, 제5 반려 동물(50))에 대한 동영상(54a) 및 '동영상 확대보기(51aa)', '체험하기(51ab)' 및 '반려 동물 정보 보기(51ac)'를 포함하는 제1 테이블(51a)을 전시하는 제2 페이지(50A); 상기 제1 페이지(50A)에서 동영상 확대 보기(51a)를 선택하면, 전시되는 제5 반려 동물(50)에 대한 확대된 동영상을 전시하는 제2 페이지(50B); 상기 제1 페이지(50A)에서 '체험하기(52a)'를 선택하면 '체험 가능 여부(51Ca)', '현재 체험 상태 정보 (51Cb, 51Cc)', '체험 접수에 대한 정보(51Cd, 51Ce)', '사용자 모드(51Cf)' 및 '구경자 모드'를 포함하는 제2 테이블(51C)이 전시되는 제3 페이지(50C); 제3 페이지(50C)의 상기 제2 테이블(51C)에서 '사용자 모드(51Cf)'가 선택되면, 제5 반려 동물(50)의 특이 사항을 전시하는 제3 테이블(51D), '식사주기', '간식 주기', '산책 요구', '메세지', '장난감 주기' 및 '특별 요청'의 메뉴를 포함하는 제4 테이블(52D) 및 사용자가 직접 기입할 수 있는 블랭크를 구비한 제5 테이블(53D)전시되는 제4 페이지(50D); 를 포함하는 반려 동물 판매 시스템에 관한 것이다. claims: 사용자 단말과 구경자 단말을 포함하는 다수의 구매 예정자 단말이 접속 가능한 반려 동물 판매 시스템에 있어서.상기 반려 동물 판매 시스템은 적어도 제1 내지 제6 반려 동물(10, 20, 30, 40, 50, 60)의 실시간 동영상을 전시하여 상기 접속한 구매 예정자 단말이 상기 적어도 제1 내지 제6 반려 동물(10, 20, 30, 40, 50, 60)중 어느 하나의 선택 신호를 보낼수 있는 초기화 화면을 포함하고,상기 접속한 구매 예정자 단말이 상기 적어도 제1 내지 제6 반려 동물(10, 20, 30, 40, 50, 60)중 어느 하나를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 선택된 반려 동물에 대한 동영상(54a) 및 '동영상 확대보기(51aa)', '체험하기(51ab)' 및 '반려 동물 정보 보기(51ac)'를 포함하는 제1 테이블(51a)을 전시하는 제1 페이지(50A)를 상기 구매 예정자 단말에 전송하고,상기 접속한 구매 예정자 단말이 상기 제1 페이지(50A)에서 '체험하기(51ab)'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 '체험 가능 여부(51Ca)', '현재 체험 상태 정보 (51Cb, 51Cc)', '체험 접수에 대한 정보(51Cd, 51Ce)', '사용자 모드(51Cf)' 및 '구경자 모드'를 포함하는 제2 테이블(51C)을 전시하는 제3 페이지(50C)를 상기 구매 예정자 단말에 전송하고,상기 사용자 단말은 상기 다수의 구매 예정자 단말중 제3 페이지(50C)에서 '체험 접수에 대한 정보(51Cd, 51Ce)'를 통해 사용 예약 신호를 상기 반려 동물 판매 시스템에 보낸 후 상기 반려 동물 판매 시스템에 의해 체험자로 선택된 단말이고, 상기 구경자 단말은 상기 다수의 구매 예정자 단말중 사용자 단말이 아닌 단말이고. 상기 사용자 단말이 상기 반려 동물 판매 시스템에 접속된 경우 상기 '사용자 모드'가 선택가능하게 활성화되고 '구경자 모드'는 비활성화가 되어 선택이 불가능 하고, 상기 구경자 단말이 상기 반려 동물 판매 시스템에 접속된 경우 '사용자 모드'는 비활성화가 되고 '구경자 모드'만 활성화가 되어 선택이 가능하며,상기 사용자 단말이 제3 페이지(50C)의 상기 제2 테이블(51C)에서 '사용자 모드(51Cf)'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 선택된 반려 동물(50)의 특이 사항을 전시하는 제3 테이블(51D), '식사주기', '간식 주기', '산책 요구', '메세지', '장난감 주기' 및 '특별 요청'의 메뉴를 포함하는 제4 테이블(52D) 및 상기 사용자 단말에서 사용자가 직접 기입할 수 있는 블랭크를 구비한 제5 테이블(53D)을 전시하는 제4 페이지(50D)를 상기 사용자 단말에 전송하고,상기 제3 테이블(51D)에는 상기 제5 테이블(53D)의 블랭크를 통해 입력된 정보가 전시되고,상기 사용자 단말이 상기 제4 페이지(50D)의 상기 제4 테이블(52D)에서 '간식 주기'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 제4 테이블(52D), 날짜별로 간식을 준 것과 이에 대한 특이 사항을 전시하는 제6 테이블(51E)과 간식에 관한 사항이 입력될 수 있는 제7 테이블(53E)을 전시하는 제5 페이지(50E)를 상기 사용자 단말에 전송하고,상기 구경자 단말이 제3 페이지(50C)의 상기 제2 테이블(51C)에서 '구경자 모드(51Cg)'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 제4 페이지(50D)의 제3 테이블(51D), '식사 보기', '간식 보기', '산책 보기', '메세지 보내기', '장난감 보기', '관리자 문의'의 메뉴를 구비하는 제15 테이블(152D)을 전시하는 제11 페이지(150D)를 상기 구경자 단말에 전송하고, 상기 구경자 단말은 제15 테이블(152D)에서 '메세지 보내기'를 통해 상기 반려 동물 판매 시스템에 메세지를 전송할 수 있고, 상기 사용자 단말이 상기 제4 페이지(50D)의 제4 테이블(52D)에서 '메세지'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 구경자 단말이 전송한 메세지를 사용자 단말에 전송하고 사용자 단말은 상기 메세지에 대한 답변을 상기 반려 동물 판매 시스템에 전송할 수 있고,상기 구경자 단말이 상기 제15 테이블(152D)에서 '간식 보기'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 제5 페이지(50E)의 제6 테이블(51E), 상기 제15 테이블(152D) 및 나가기(153D) 메뉴를 포함하는 제12 페이지(150E)를 상기 구경자 단말에 전송하는 것을 특징으로 하는 반려 동물 판매 시스템., Ltext: 농업, prediction: 임업
761/1059 Row 761: application_number: 1020207027389, combined_string: invention_title: 스마트 애완동물 사육 장치 abstract: 본 발명의 실시예는 스마트 애완동물 사육 장치에 관한 것이다. 상기 장치는 케이지, 제어 센터, 모터, 소독 장치, 제1 적외선 식별 장치, 제2 적외선 식별 장치 및 음성 플레이 장치를 포함하고; 케이지의 각측벽에는 모두 회전축을 통해 전기 제어 변색 유리판이 설치되며; 제1 적외선 식별 장치는 케이지 내에 동물의 존재여부를 모니터링하고, 케이지 내에 동물이 존재하지 않는 것으로 모니터링될 경우, 소독 장치는 케이지 내부를 소독하며; 제2 적외선 식별 장치는 케이지 외부의 기설정 범위 내에 사람 또는 동물의 존재 여부를 검출한다. 본 발명의 실시예에서의 제1 적외선 식별 장치는 케이지 내에 동물의 존재 여부를 식별할 수 있고, 동물이 케이지에 존재하지 않을 경우, 제어 센터는 소독 장치가 작동되어 케이지를 소독하도록 제어함으로써, 세균, 바이러스의 번식을 방지한다. 제2 적외선 식별 장치는 케이지 주위에 사람 또는 동물의 존재 여부를 식별할 수 있음으로써, 음성 플레이 장치를 작동시켜 설정된 내용을 플레이하여 사육 과정에 교류성 및 취미성를 증가시킨다. claims: 케이지, 제어 센터, 모터를 포함하고,상기 케이지의 윗면 및 밑면은 모두 판체이고, 상기 케이지의 4개의 측벽은 격자판이며, 각측벽과 윗면의 교차 위치에는 모두 회전축이 설치되고, 각 상기 회전축은 하나의 모터에 연결되며, 각 회전축에는 모두 상기 케이지의 측벽을 커버하기 위한 전기 제어 변색 유리판이 설치되고;상기 모터는 케이지의 최상부에 장착되며, 전지 또는 교류 전류를 통해 전원을 제공하며;상기 모터는 상기 케이지에 연결되고 상기 제어 센터는 상기 케이지에 설치되는 것을 특징으로 하는 스마트 애완동물 사육 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

762/1059 Row 762: application_number: 1020200089702, combined_string: invention_title: 스마트 목줄을 이용한 애완동물 관리 시스템 abstract: 본 발명의 실시 예에 따른 스마트 목줄을 이용한 애완동물 관리 시스템은, 애완동물의 신체 움직임과 신체 정보를 측정하여 운동감지신호 및 생체 신호를 생성하고, 생성된 운동감지신호와 생체신호를 분석하여 상기 애완동물의 건강 상태를 판단하는 스마트 목줄과, 애완동물 관리 어플리케이션이 실행되며, 상기 스마트 목줄과의 무선통신을 통해 애완동물 정보를 수신하여 화면상에 표시하는 사용자 단말을 포함한다. claims: 애완동물의 신체 움직임과 신체 정보를 측정하여 운동감지신호 및 생체 신호를 생성하고, 생성된 운동감지신호와 생체신호를 분석하여 상기 애완동물의 건강 상태를 판단하는 스마트 목줄; 및애완동물 관리 어플리케이션이 실행되며, 상기 스마트 목줄과의 무선통신을 통해 애완동물 정보를 수신하여 화면상에 표시하는 사용자 단말을 포함하고,상기 스마트 목줄은,상기 애완동물의 신체의 일부를 감싸도록 착용되는 몸체부;상기 몸체부의 일면에 부착되어 상기 몸체부가 수축 및 팽창되는 정도를 감지하여 상기 운동감지신호를 생성하고, 상기 애완동물의 심박수, 체온, 혈압, 및 심호흡 상태 중 적어도 하나를 측정하여 상기 생체신호를 생성하는 센서부; 상기 운동감지신호를 기초로 상기 몸체부가 수축 및 팽창을 반복하는 경우 상기 애완동물이 운동 상태에 있는 것으로 판단하여 상기 애완동물의 운동량을 판단하고, 상기 생체신호를 분석하여 상기 애완동물의 건강 상태를 판단하는 제어부; 및상기 사용자 단말과 무선통신을 수행하는 통신부를 포함하며, 상기 제어부는 상기 몸체부가 기준 크기 미만의 상태로 기설정된 시간을 유지하는 동안에 상기 애완동물의 심박수, 체온, 혈압, 및 심호흡 상태 중 적어도 하나가 정상 상태를 벗어난 경우 상기 애완동물의 건강상태를 상태이상으로 판단하고, 상기 몸체부가 기준 크기 이상의 상태에서 상기 애완동물의 심박수, 체온, 혈압, 및 심호흡 상태 중 어느 하나가 정상 상태를 벗어난 경우 상기 애완동물의 건강상태를 정상상태로 판단하고,상기 사용자 단말은,상기 애완동물이 운동상태에 있는 경우, 상기 애완동물 정보에 포함된 GPS 정보를 기초로 상기 애완동물이 이동한 산책거리를 계산하고, 기저장된 지도에 상기 애완동물의 이동경로를 표시하는 애완동물 관리 시스템., Ltext: 농업, prediction: 임업
763/1059 Row 763: application_number: 1020200088920, combined_string: invention_title: 실험용 동물 케이지 abstract: 본 발명은 실험용 동물 케이지에 관한 것으로, 폴리카보네이트(Polycarbonate) 재질로 형성되고, 상단이 개방된 내부공간을 가지며, 상단 테두리에 일정 간격으로 결합돌기가 형성된 본체; 상기 본체와 동일한 재질로 형성되고, 상기 본체의 상단에 지지되며, 테두리에 상기 결합돌기가 삽입되도록 삽입공이 형성되고, 상단에 손잡이가 형성된 상판; 및 상기 본체에 결합된 상판을 고정시키기 위해 상기 결합돌기와 체결되는 고정부재;를 포함한다. 이러한 구성으로, 본체 및 상판이 폴리카보네이트(Polycarbonate) 재질로 형성됨으로써, 세척 후 멸균이 가능하여 위색정이며, 견고한 케이지를 제공할 수 있는 효과를 얻을 수 있다. claims: 폴리카보네이트(Polycarbonate) 재질로 형성되고, 상단이 개방된 내부공간을 가지며, 상단 테두리에 일정 간격으로 결합돌기가 형성된 본체;상기 본체와 동일한 재질로 형성되고, 상기 본체의 상단에 지지되며, 테두리에 상기 결합돌기가 삽입되도록 삽입공이 형성되고, 상단에 손잡이가 형성된 상판; 및상기 본체에 결합된 상판을 고정시키기 위해 상기 결합돌기와 체결되는 고정부재;를 포함하고,상기 본체의 상단 각 꼭지점에는 상기 상판의 하단 꼭지점이 지지되고, 상기 상판 둘레의 각 꼭지점에 형성된 걸림홈이 결합되는 걸림턱이 형성되며,상기 본체는 외측벽이 상방으로 갈수록 벌어지는 형상으로 형성되고,상기 본체의 외측면 상면에 상기 상판이 지지되며,상기 본체의 내측 하면에는 먹이통 또는 급수통이 거치 가능하도록 고정포트가 형성되고,상기 고정포트의 일측은 단차가 형성되도록 일부 개방되며,상기 고정포트는 상기 본체의 내측 하면에 탈착 가능하게 구비되고,상기 본체의 내측 하면에는 상기 고정포트가 하방으로부터 삽입 가능하도록 고정홀이 형성되며,상기 본체의 하면 중 상기 고정홀과 인접한 위치에 이동홈이 형성되고, 상기 이동홈에는 이동부재가 이동 가능하게 결합되며, 상기 이동부재에는 암나사산이 형성되고, 상기 이동홈의 내측에는 상기 이동부재와 연결된 스프링이 결합되며,상기 고정포트의 하단에는 상기 고정홀의 직경보다 크게 형성된 고정판이 형성되고, 상기 고정판 상단 중 상기 이동홈과 마주보는 위치에는 제1 홀이 형성되고, 상기 고정판의 일측면에는 상기 제1 홀과 직교되도록 제2 홀이 형성되며,상기 제1 홀에는 제1 핀이 결합되고, 상기 제2 홀에는 제2 핀이 결합되며,상기 제1 핀은 일측이 외부로 돌출되고 돌출된 부분에는 상기 암나사산과 나사 결합되는 수나사산이 형성되며 타측이 상기 제2 홀과 직교되는 부분에 제1 베벨기어가 형성되고,상기 제2 핀은 일측이 외부로 돌출되고 타측이 상기 제1 베벨기어와 맞물리도록 제2 베벨기어가 형성되어,상기 고정포트가 상기 본체에 나사 결합되고,상기 본체의 측벽은 상방으로 갈수록 두꺼워지는 형상을 가지며,상기 본체의 측벽 일측에는 제1 통기공이 형성되고,상기 상판의 상면 양측에는 제2 통기공이 형성되는 것을 특징으로 하는 실험용 동물 케이지., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

764/1059 Row 764: application_number: 1020217001657, combined_string: invention_title: 이중 교반판 사료 투하 구조 및 투하장치 abstract: 본 발명은 애완동물 간식공급장치 부재 기술분야에 속하는 것으로, 기존의 애완동물 간식 투하 효과가 좋지 않고 투하량을 제어할 수 없는 선행기술의 문제점을 해결하는 이중 교반판 사료 투하기구 및 투하장치를 제공하는 바, 상기 이중 교반판 사료 투하기구는 사료 교반 장치 및 구동장치를 포함하고, 상기 사료 교반 장치는 회전축, 상부 사료 교반판 및 하부 사료 교반판을 포함하며; 상기 상부 사료 교반판은 상부 사료 교반편을 포함하고, 상기 하부 사료 교반판은 하부 사료 교반편을 포함하며, 상기 하부 사료 교반편의 개수는 상기 상부 사료 교반편의 개수보다 많으며, 상기 회전축의 외벽에는 장착홈이 설치되고, 상기 하부 사료 교반편에는 장착홈에 적합한 장착 스트립이 설치되며; 상기 투하장치는 사료 저장빈, 트랜지션빈 및 상기 이중 교반판 사료 투하기구를 포함하고; 본 발명은 이중 교반판 사료 투하기구를 통해 애완동물 간식을 효과적으로 투하할 수 있으며, 2단계 투하 방식은 원활한 투하를 확보하는 전제하에 단일 투하량을 효과적으로 제어할 수 있다. claims: 사료 교반 장치 및 구동장치를 포함하되, 여기서,상기 사료 교반 장치는 회전축(322), 상기 회전축(322)에 적층 설치된 상부 사료 교반판(31) 및 하부 사료 교반판(32)을 포함하고, 상기 회전축(322)의 일단은 상기 상부 사료 교반판(31)에 연결되며, 상기 회전축(322)의 타단은 상기 구동장치에 연결되고, 상기 구동 장치는 상기 회전축(322)이 회동하도록 구동시켜 상기 상부 사료 교반판(31)과 상기 하부 사료 교반판(32)이 동기적으로 회동하도록 할 수 있고; 상기 상부 사료 교반판(31)은 적어도 하나의 상부 사료 교반편(311)을 포함하고, 상기 하부 사료 교반판(32)은 적어도 두개의 하부 사료 교반편(321)을 포함하며, 상기 하부 사료 교반편(321)의 개수는 상기 상부 사료 교반편(311)의 개수보다 많고, 상기 회전축(322)의 외벽에는 장착홈(3223)이 설치되며, 상기 하부 사료 교반편(321)의 엣지부에는 장착 스트립(3211)이 설치되고, 상기 장착 스트립(3211)은 상기 장착홈(3223) 내에 삽입 연결된다.는 것을 특징으로 하는 이중 곡물 교반판 배출 기구(3).사료 저장빈(1), 트랜지션빈(2) 및 제 1 항 내지 제 7 항 중 어느 한 항에 따른 이중 교반판 사료 투하기구(3)를 포함하고, 상기 사료 저장빈(1)은 상기 트랜지션빈(2)의 상부에 설치되되, 여기서, 상기 사료 저장빈(1) 내에는 사료 저장 챔버(11)가 설치되고, 상기 트랜지션빈(2)에는 트랜지션 챔버(21)가 설치되며, 상기 사료 저장빈(1)의 바닥부에는 토출구(131)가 설치되고, 상기 사료 저장 챔버(11)는 상기 토출구(131)를 통해 상기 트랜지션 챔버(21)와 연통되며, 상기 트랜지션빈(2)의 바닥부에는 상기 트랜지션 챔버(21)와 연통되도록 가이드구(211)가 설치되고; 상기 상부 사료 교반판(31)은 상기 사료 저장 챔버(11) 내에 설치되어 상기 사료 저장 챔버(11) 내의 애완동물 간식을 상기 토출구(131)를 통해 밀어낼 수 있으며; 상기 하부 사료 교반판(32)은 상기 트랜지션 챔버(21) 내에 설치되고, 상기 하부 사료 교반편(321)은 모두 상기 트랜지션 챔버(21)를 적어도 두개의 트랜지션 유닛으로 분할하며, 상기 토출구(131)를 통해 밀려나온 애완동물 간식은 상기 트랜지션 유닛 내에 떨어져 상기 하부 사료 교반편(321)의 푸시하에 상기 가이드구(211)로부터 밀려 나올 수 있는 것을 특징으로 하는 투하장치.제 6 항에 있어서, 상기 사료 저장빈(1)은 상부 빈 본체(12) 및 하부 빈 본체(13)를 포함하되, 여기서,상기 하부 빈 본체(13)는 상기 상부 빈 본체(12)의 바닥부에 설치되고, 상기 상부 빈 본체(12) 내의 캐비티와 상기 하부 빈 본체(13) 내의 캐비티는 둘러싸여 상기 사료 저장 챔버(11)를 이루며; 상기 하부 빈 본체(13)는 호퍼 형상으로 설치되고, 상기 하부 빈 본체(13)의 구경은 상기 상부 빈 본체(12)로부터 멀어지는 방향을 따라 순차적으로 감소되고; 상기 토출구(131)는 상기 하부 빈 본체(13)의 바닥부에 설치되며, 상기 상부 사료 교반판(31)은 상기 토출구(131)에 근접하는 위치에 설치되는 것을 특징으로 하는 투하장치.제 7 항에 있어서, 상기 트랜지션 챔버(21)의 형상은 원기둥형으로 설치되고, 상기 하부 사료 교반편(321)은 상기 트랜지션 챔버(21)를 적어도 두개의 상기 트랜지션 유닛으로 균등하게 분할하기 위해 모두 상기 회전축(322)에 대해 원주 방향으로 균일하게 설치되는 것을 특징으로 하는 투하장치., Ltext: 농업, prediction: 임업
765/1059 Row 765: application_number: 1020200080374, combined_string: invention_title: 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 방법, 프로그램, 및 시스템 abstract: 본 발명은 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 방법에 관한 것으로, 수집 장치가 동물의 정보를 수집하는 수집 단계; 수신부가 상기 정보를 수신하는 수신 단계; 분석부가 상기 수신된 정보를 분석하여 메시지로 가공하는 가공 단계; 제1 출력 장치가 상기 메시지를 출력하는 제1 출력 단계; 상기 분석부가 상기 제1 출력 장치로 수신된 답변 메시지를 분석하는 분석 단계; 검색부가 상기 분석부의 상기 답변 메시지의 분석에 대응하는 콘텐츠를 검색하는 검색 단계; 및 제2 출력 장치가 상기 검색된 콘텐츠를 출력하는 제2 출력 단계;를 포함한다. claims: 수집 장치가 동물의 정보를 수집하는 수집 단계;수신부가 상기 정보를 수신하는 수신 단계;분석부가 상기 수신된 정보를 분석하여 메시지로 가공하는 가공 단계;제1 출력 장치가 상기 메시지를 출력하는 제1 출력 단계;상기 분석부가 상기 제1 출력 장치로 수신된 답변 메시지를 분석하는 분석 단계;검색부가 상기 분석부의 상기 답변 메시지의 분석에 대응하는 콘텐츠를 검색하는 검색 단계; 및제2 출력 장치가 상기 검색된 콘텐츠를 출력하는 제2 출력 단계;를 포함하는 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 방법.하드웨어인 컴퓨터와 결합되어, 제1항 내지 제7항 중 어느 한 항의 방법을 실행시키기 위하여 매체에 저장된, 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 프로그램. 동물의 정보를 수집하는 수집 장치;상기 수집 장치에서 상기 정보를 제공받는 서버;상기 서버에서 상기 정보에 대응하는 메시지를 제공받아 출력하고, 답변 메시지를 제공받는 제1 출력 장치; 및상기 답변 메시지에 대응하는 콘텐츠를 출력하는 제2 출력 장치;를 포함하고,상기 서버는상기 수집 장치에서 상기 정보를 제공받는 수신부;상기 정보를 분석하여, 상기 메시지로 가공하여, 상기 제1 출력 장치에 제공하고, 상기 제1 출력 장치로 수신된 상기 답변 메시지를 분석하는 분석부; 및상기 답변 메시지의 분석에 대응하는 상기 콘텐츠를 검색하는 검색부;를 포함하는 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

766/1059 Row 766: application_number: 1020200079034, combined_string: invention_title: 반려동물의 성장 관리 시스템 abstract: 본 발명의 반려동물 성장 관리시스템은 반려동물에게 가장 적합한 식이요법을 제공한다. 반려동물의 현재 데이터를 토대로 성장 모델과 비교하여 적절한 목표값을 결정하며, 이를 달성하기 위한 수제 사료를 포함한 정보가 솔루션으로 제공된다. claims: 반려동물을 키우는 사용자의 사용자 기기와 통신하는 반려동물의 성장관리 시스템으로서, 상기 성장 관리 시스템은:사용자가 입력한 반려동물의 종류, 품종, 나이, 성별, 중성화여부, 질병이력 정보, 몸무게, 활동량, 사료급식량 및 물급수량을 저장하는 메모리;메모리의 정보를 토대로 반려동물의 성장 상태를 분석하는 성장상태 분석부; 및성장상태 분석부의 분석 결과를 토대로 성장 관리를 위한 처방을 표시하고 사료를 결정하는 성장관리 처방부;를 포함하며,성장상태 분석부와 성장 상태 처방부는 사료정보 테이블을 참조하고, 사료정보 테이블은 각각의 사료의 이름, 성분, 영양 정보, 적절 연령대의 정보를 포함하며, 사료정보테이블에는 현재 존재하는 상용의 판매 사료 정보가 저장되어 사용자가 사료명을 입력하거나 스캔하는 것으로 현재 동물 상태를 파악할 수 있으며,성장상태 분석부는 메모리의 데이터를 참조로 반려동물의 크기를 분류하고, 입력된 나이를 토대로 성장 단계를 분류하며, 나이, 품종 및 몸무게 데이터를 토대로 해당 반려동물의 성장 곡선과 비교하여 적어도 마름, 정상 및 비만의 어느 한 단계를 표시하고, 사료급식량과 물급수량 데이터를 토대로 반려 동물이 현재 섭취하는 에너지를 계산하여 정상 몸무게 일 경우의 필요 에너지와 비교하며,상기 성장곡선의 모델은 처음에는 동물 별 기초 모델이며, 성장상태 분석부의 분석 데이터 누적에 따라 학습되어 상기 기초 모델을 갱신한 성장 곡선 모델이며,성장관리 처방부는 반려동물 정보, 체형 분석 및 식단 분석을 포함하는 성장관리솔루션리포트를 사용자기기로 전송하고, 성장관리솔류션리포트는 반려동물이 비만인 경우 다이어트 플랜 및 처방전 정보를 포함하는, 성장 관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

767/1059 Row 767: application_number: 1020200079126, combined_string: invention_title: 반려동물 질병진단 정보 기반 구매제품 추천 시스템 abstract: 본 발명은 구매제품 추천 시스템에 관한 것으로서, 보다 구체적으로는 반려동물의 질병이력을 고려하여 반려동물을 키우는데 필수적인 사료, 영양제, 간식, 샴푸 등과 같은 다양한 제품 중에서 전문가에 의해 검증된 제품을 자동 추천함으로써 반려동물을 위한 제품이 질병으로 인해 오히려 유해한 영향을 미쳐 반려동물을 해칠 수 있는 상황을 방지하기 위한 반려동물 질병진단 정보 기반 구매제품 추천 시스템에 관한 것이다.이를 위해 본 발명은, 수신되는 반려동물의 나이를 포함한 질병진단 이력정보를 기초로 구매할 제품을 자동으로 추천하고 추천한 제품을 온라인상에서 구매 가능하도록 하기 위한 구매제품 추천서버와; 상기 구매제품 추천서버로 반려동물 질병진단 이력정보를 송신하여 구매할 제품을 추천받기 위한 고객 단말기와; 상기 질병진단 이력정보에 대응하여 추천 또는 비추천하는 제품에 대한 사유정보를 구매제품 추천서버로 업로드하여 고객 단말기가 확인 가능하도록 하기 위한 동물병원 단말기;를 포함하는 것을 특징으로 한다. claims: 수신되는 반려동물의 나이를 포함한 질병진단 이력정보를 기초로 구매할 제품을 자동으로 추천하고 추천한 제품을 온라인상에서 구매 가능하도록 하기 위한 구매제품 추천서버와;상기 구매제품 추천서버로 반려동물 질병진단 이력정보를 송신하여 구매할 제품을 추천받기 위한 고객 단말기와;상기 질병진단 이력정보에 대응하여 추천 또는 비추천하는 제품에 대한 사유정보를 구매제품 추천서버로 업로드하여 고객 단말기가 확인 가능하도록 하기 위한 동물병원 단말기;를 포함하되,상기 질병진단 이력정보는 영양결핍, 신부전, 심장병, 알러지, 슬개골탈구, 관절염, 치주염, 수술 후 회복, 아토피, 외이도염, 피부병, 디스크, 기관지 협착, 비만, 백내장 및 당뇨 중 적어도 어느 하나 이상을 포함하며,상기 구매제품 추천서버는 반려동물에 대한 나이, 성별, 과거부터 현재까지 진단받은 질병명 및 질병기간을 사전에 마련된 선택란을 통해 고객 단말기가 선택하도록 하여 질병진단 이력정보를 생성하기 위한 질병이력 생성모듈을 구비하며,상기 구매제품 추천서버는 고객 단말기의 요청하에 동물병원 단말기로부터 반려동물의 질병진단서를 수집하고 수집된 문서 형식의 질병진단서를 텍스트 분석모듈을 통해 질병진단 이력정보를 생성하여 고객이 반려동물의 질병진단 이력이 반영된 제품을 추천받도록 하기 위한 질병진단정보 수집모듈을 구비하며,상기 구매제품 추천서버는 고객 단말기가 전송하는 이미지 및 동영상 중 적어도 어느 하나 이상을 CNN(Convolutional Neural Network) 방식을 통한 컨볼루션 레이어들을 통해 특성을 추출하게 되어 추출된 특성을 기반으로 분석하여 반려동물의 질병을 진단하기 위한 영상 분석모듈을 구비하며,상기 구매제품 추천서버는 고객 단말기가 전송하는 반려동물에 대한 텍스트 형식의 질병정보를 분석하여 질병진단 이력정보를 생성하기 위한 텍스트 분석모듈을 구비하며,상기 구매제품 추천서버는 고객 단말기가 전송하는 반려동물에 대한 음성 형식의 질병정보를 인식하여 텍스트화한 다음으로, 텍스트 분석모듈과 연계하여 질병진단 이력정보를 생성하기 위한 음성 분석모듈을 구비하며,상기 텍스트 분석모듈은 형태가 무작위인 텍스트를 형태소 분석, 구문 분석 및 개체명 인식 중 적어도 어느 하나 이상의 방식을 이용한 자연어 처리를 수행한 이후로 질병진단 이력정보만을 미리 정해진 카테고리로 분류, 군집화 및 연관어 분석 중 적어도 어느 하나 이상으로 텍스트를 분석하며,상기 텍스트 분석 중 분류는 질병진단 이력정보를 반려동물 관련한 나이, 성별, 질병명 및 질병에 걸린 기간 중 적어도 어느 하나 이상의 정해진 특정으로 카테고리를 분류하고, 상기 텍스트 분석 중 군집화는 질병진단 이력정보 중 유사한 주제끼리 그룹핑하고, 상기 분류가 학습 과정을 통해 문서를 분류하는 지도 학습에 해당된다면 상기 군집화는 학습 과정 없이 바로 유사 정보끼리 그룹핑을 하는 비지도 학습/자율 학습에 해당되며, 상기 텍스트 분석 중 연관어 분석은 텍스트상에 출현하는 단어 간의 관계를 분석하여 질병진단 이력정보와 관련된 단어 간의 연관성을 찾아내며,상기 구매제품 추천서버는 머신러닝 방식에 의해 상기 질병진단 이력정보를 기초로 반려동물의 과거부터 현재까지의 건강상태가 고려된 사료, 영양제, 간식, 샴푸, 방석, 옷, 장난감, 패드 및 기저귀 중 적어도 어느 하나 이상의 제품을 자동으로 추천하기 위한 제품 추천모듈을 구비하며,상기 구매제품 추천서버는 동일 제품군별 제품 비교정보를 고객 단말기에 제공하기 위한 비교제품정보 제공모듈을 구비하며,상기 구매제품 추천서버는 회원 등록된 수의사 단말기에 교육을 위해 신규제품 정보를 제공하기 위한 신규제품정보 제공모듈을 구비하는 것을 특징으로 하는 반려동물 질병진단 정보 기반 구매제품 추천 시스템., Ltext: 농업, prediction: 임업
768/1059 Row 768: application_number: 1020200079195, combined_string: invention_title: 표준 진료비에 기반한 동물병원 추천 방법 및 시스템 abstract: 표준 진료비에 기반한 동물병원 추천 방법 및 시스템을 개시한다.본 실시예는 복수의 동물병원마다 진료비에 대한 편차가 존재하므로 펫 오너 입장에서 동물병원을 방문하기 전에 표준 진료비를 기준으로 진료비가 높은지 낮은지를 확인할 수 있도록 합리적인 가이드 라인을 제공하는 동시에, 진료비, 위치, 펫의 종류, 질병을 기반으로 동물병원을 추천해주는 표준 진료비에 기반한 동물병원 추천 방법 및 시스템을 제공한다. claims: 자체 조사로 입력된 정보, 동물병원 단말기로부터 입력 받은 정보, 펫 오너 단말기로부터 수신한 정보를 수집하여 표준 진료비를 산정하는 표준 진료비 산정장치;상기 표준 진료비와 상기 동물병원 단말기로부터 입력 받은 각 동물병원별 진료비를 비교하여 임계범위 이내의 편차를 갖는 동물병원만을 추출하여 후보 동물병원으로 선별하고, 상기 후보 동물병원 중 상기 펫 오너 단말기의 위치 및 상기 펫 오너 단말기로부터 수신된 펫 정보를 기반으로 추천 동물병원을 선별하여 상기 펫 오너 단말기로 전송하는 동물병원 추천장치; 및상기 펫 오너 단말기로부터 수신한 상기 추천 동물병원에 대한 예약일자를 기반으로 예약 및 선결제를 진행하는 동물병원 예약장치를 포함하되, 상기 표준 진료비 산정장치는 상기 표준 진료비를 산정할 때,외부로부터 수집된 동물병원의 위치를 기반으로 수도권과 지방으로 구분하고 상기 수도권과 상기 지방에 따른 가중치를 반영하고, 동물병원의 위치를 기반으로 동물병원의 밀집 지역과 비밀집 지역을 구분한 후 동물병원의 밀집 지역에 기 설정된 임계치보다 낮은 가중치, 비밀집 지역에 기 설정된 임계치보다 높은 가중치를 반영하고,동물병원의 위치를 기반으로 지하철에 인접한 위치에 동물병원과 주차장을 보유한 동물병원에 기 설정된 임계치보다 높은 가중치를 반영하고, 지하철로부터 기 설정된 거리 이상으로 이격되어 위치에 동물병원과 주차장을 미보유한 동물병원에 기 설정된 임계치보다 낮은 가중치를 반영하고,펫 종류를 기반으로 펫이 소형, 중형 또는 대형인지를 1차적 판단한 1차 판단 결과를 생성하고, 상기 1차 판단 결과에 상기 펫의 사이즈와 상기 펫의 몸무게를 추가로 반영하여 펫이 소형, 중형 또는 대형인지를 2차적으로 판단한 2차 판단 결과를 생성하며, 상기 2차 판단 결과를 기반으로 펫이 소형으로 판단되면 기 설정된 임계치 보다 낮은 가중치를 반영하고, 상기 2차 판단 결과를 기반으로 펫이 중형으로 판단되면 일반 가중치를 반영하고, 상기 2차 판단 결과를 기반으로 펫이 대형으로 판단되면 기 설정된 임계치 보다 높은 가중치를 반영하고,상기 펫 오너 단말기로부터 수신된 수의사의 평가점수가 기 설정된 임계치보다 높으면 높은 가중치를 반영하고, 상기 수의사의 평가점수가 기 설정된 임계치보다 낮으면 낮은 가중치를 반영하는 것을 특징으로 하는 표준 진료비에 기반한 동물병원 추천 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

769/1059 Row 769: application_number: 1020200075792, combined_string: invention_title: 축산차량 GPS 단말기 개통 시스템 abstract: 본 발명에 따른 GPS 단말기 개통 시스템은 이동통신망을 이용하는 GPS 단말기에 이동통신 서비스를 제공하기 위한 개통을 수행하는 이동통신사 서버; 축산차량의 이동경로를 관리하기 위하여 GPS 단말기에 관리번호를 부여하는 기관단체 서버; 등록 대상자에게 판매되는 상기 GPS 단말기에 대하여 상기 등록 대상자의 등록 대상자 정보를 입력받는 GPS 단말기 판매처 단말기; 및 상기 GPS 단말기 판매처 단말기로부터 상기 GPS 단말기에 대한 정보를 제공받아 개통 및 등록을 수행하는 에이전트 서버;를 포함하고,상기 에이전트 서버는, 상기 GPS 단말기 판매 전 상기 이동통신사 서버에 상기 GPS 단말기의 단말기 정보를 전달하면서 GPS 단말기 관련 개통예정정보를 생성 요청하여 반환받고, 상기 기관단체 서버에 반환된 상기 GPS 단말기의 개통예정정보를 전달하면서 정보 매칭 요청을 하여 매칭 정보를 반환 받아 보유하고, 상기 GPS 단말기 판매처 단말기로부터 상기 GPS 단말기에 대한 개통 요청이 있는 경우 상기 매칭 정보를 반환하고, 상기 이동통신사 서버에 상기 GPS 단말기에 대한 예비 개통 정보를 전달하는 에이전트 서버를 포함한다.본 발명에 따른 축산차량 GPS 단말기 개통 시스템은 축산차량의 단말기 등록과 주관기관에의 등록 절차에 소요되는 시간 및 절차를 최소화함으로써 효율적인 업무의 처리를 가능하도록 하는 효과가 있다. claims: 이동통신망을 이용하는 GPS 단말기에 이동통신 서비스를 제공하기 위한 개통을 수행하는 이동통신사 서버; 축산차량의 이동경로를 관리하기 위하여 GPS 단말기에 관리번호를 부여하는 기관단체 서버;등록 대상자에게 판매되는 상기 GPS 단말기에 대하여 상기 등록 대상자의 등록 대상자 정보를 입력받는 GPS 단말기 판매처 단말기; 및상기 GPS 단말기 판매처 단말기로부터 상기 GPS 단말기에 대한 정보를 제공받아 개통 및 등록을 수행하는 에이전트 서버;를 포함하고,상기 에이전트 서버는,상기 GPS 단말기 판매 전 상기 이동통신사 서버에 상기 GPS 단말기의 단말기 정보를 전달하면서 GPS 단말기 관련 개통예정정보를 전달하여 예비개통을 요청하고, 상기 기관단체 서버에 반환된 상기 GPS 단말기의 개통예정정보를 전달하면서 정보 매칭 요청을 하여 상기 기관단체의 상기 GPS 단말기에 대한 관리번호를 포함하는 매칭 정보를 반환 받아 보유하고, 상기 GPS 단말기 판매처 단말기로부터 상기 GPS 단말기에 대한 개통 요청이 있는 경우 상기 매칭 정보를 반환하고, 상기 이동통신사 서버에 상기 GPS 단말기에 대한 예비개통 정보 및 상기 매칭 정보를 전달하는 에이전트 서버를 포함하는 GPS 단말기 개통 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

770/1059 Row 770: application_number: 1020200071789, combined_string: invention_title: 사물 인터넷 기반의 반려동물 소통기능 제공장치 및 방법, 사용자 단말기 abstract: 본 발명은 반려동물의 욕구를 파악하고 반려동물 욕구를 만족시켜줄 수 있는 기기를 원격 제어하는 사물 인터넷 기반의 반려동물 소통기능 제공장치 및 방법에 관한 것으로 반려동물 욕구 신호를 입력받아 사용자 단말기에서 구동되는 반려동물 소통 전용 앱을 통해 전달하는 욕구신호 전달부, 상기 사용자 단말기에서 구동되는 반려동물소통 전용 앱을 통해 상기 욕구신호 전달부에서 전달한 욕구 신호에 매칭되는 욕구 해소 장치의 원격 제어 신호를 수신하는 원격 제어신호 수신부 및 상기 원격 제어신호 수신부로 수신되는 원격 제어 신호를 욕구 해소 장치로 전달하는 원격 제어신호 전달부를 포함하는 사물 인터넷 기반의 반려동물 소통기능 제공장치. 에 의해 원격지에서도 반려동물의 욕구 내용을 파악하고, 그에 따른 욕구를 충족시켜줄 수 있도록, 사료제공, 간식제공, 놀잇감 제공, 영상 통화와 같은 IoT 기기를 이용한 기능을 제공 가능하여 반려동물과의 친밀감을 더 높일 수 있고, 반려동물의 분리불안해소, 우울증 예방, 운동량 증가 효과를 볼 수 있다는 효과가 도출된다. claims: 욕구해소 장치와 근거리 무선 통신을 수행하는 제어신호 중개장치로부터 반려동물 욕구 신호를 입력받아 사용자 단말기에서 구동되는 반려동물 소통 전용 앱을 통해 전달하는 욕구신호 전달부; 상기 사용자 단말기에서 구동되는 반려동물소통 전용 앱을 통해 상기 욕구신호 전달부에서 전달한 욕구 신호에 매칭되는 욕구 해소 장치의 원격 제어 신호를 수신하는 원격 제어신호 수신부; 및상기 원격 제어신호 수신부로 수신되는 원격 제어 신호를 적어도 하나의 욕구해소 장치와 근거리 무선 통신을 수행하는 제어신호 중개장치를 경유하여 욕구 해소 장치로 전달하는 원격 제어신호 전달부;를 포함하고, 상기 욕구신호 전달부는, 상기 반려동물소통 전용 앱의 채팅 기능을 통해 상기 반려동물 욕구 신호를 구어체로 변환하여 전달하되, 상기 반려동물 욕구신호에 따른 키워드를 파악하고, 기저장된 대화체 문장들 중 상기 키워드를 포함하는 문장을 선별하여 상기 반려동물소통 전용 앱의 채팅 기능을 통해 전달하고, 상기 욕구 해소 장치는 사료 급식기, 간식 급식기, 놀이보조기, 영상통화장치, 스피커 중 적어도 하나이며, 상기 욕구신호 전달부는, 제어신호 중개장치의 칩 인식부로부터 칩 인식 신호를 수신하여 반려 동물의 식별 정보를 함께 사용자 단말기로 전달하고, 상기 반려동물소통 전용 앱의 채팅 기능을 통해 반려 동물의 식별 정보에 따라 해당 반려동물과의 채팅 기능을 제공하는 사물 인터넷 기반의 반려동물 소통기능 제공장치. 제 1 항, 제4항, 제6항 중 어느 한 항에 기재된 사물인터넷 기반의 반려동물소통기능 제공장치가 탑재된 사용자 단말기.욕구 신호 전달부, 제어신호 수신부 및 원격 제어신호 전달부를 포함하는 사물 인터넷 기반의 반려동물 소통기능 제공장치에서 수행되는 사물 인터넷 기반의 반려동물 소통기능 제공방법에 있어서, 욕구 신호 전달부가 반려동물 욕구 신호를 입력받아 사용자 단말기에서 구동되는 반려동물소통 전용 앱을 통해 욕구 신호를 전달하는 단계; 원격 제어신호 수신부가 사용자 단말기에서 구동되는 반려동물소통 전용 앱을 통해 상기 욕구 신호 전달부에서 전달한 욕구 신호에 매칭되는 욕구 해소 장치의 원격 제어 신호를 수신하는 단계; 및원격 제어신호 전달부가 상기 원격 제어신호 수신부로 수신되는 원격 제어 신호를 적어도 하나의 욕구해소 장치와 근거리 무선 통신을 수행하는 제어신호 중개장치를 경유하여 욕구 해소 장치로 전달하는 단계;를 포함하고, 상기 욕구 신호를 전달하는 단계는,상기 반려동물소통 전용 앱의 채팅 기능을 통해 상기 반려동물 욕구 신호를 구어체로 변환하여 전달하되, 상기 반려동물 욕구신호에 따른 키워드를 파악하고, 기저장된 대화체 문장들 중 상기 키워드를 포함하는 문장을 선별하여 상기 반려동물소통 전용 앱의 채팅 기능을 통해 전달하고, 상기 욕구 해소 장치는 사료 급식기, 간식 급식기, 놀이보조기, 영상통화장치, 스피커 중 적어도 하나이며, 상기 욕구 신호를 전달하는 단계는,제어신호 중개장치의 칩 인식부로부터 칩 인식 신호를 수신하여 반려 동물의 식별 정보를 함께 사용자 단말기로 전달하고, 상기 반려동물소통 전용 앱의 채팅 기능을 통해 반려 동물의 식별 정보에 따라 해당 반려동물과의 채팅 기능을 제공하는 사물 인터넷 기반의 반려동물 소통기능 제공방법., Ltext: 농업, prediction: 임업
771/1059 Row 771: application_number: 1020200065966, combined_string: invention_title: 가축 모니터링을 위한 체결 장치 abstract: 본 발명은 가축 모니터링을 위한 체결 장치에 관한 것으로서, 더욱 상세히는 가축의 몸체에 부착되어 가축의 건강 상태를 모니터링하기 위한 체결 장치에 관한 것이다. 본 발명은 가축의 몸체에 안정적으로 고정 부착되어 센서부를 통해 가축의 건강 상태와 관련된 생체 신호를 수집하여 센싱 정보를 생성하고, 해당 센싱 정보를 다수의 가축을 관리하는 외부 장치에 전송하여, 외부 장치에서 해당 센싱 정보에 포함된 식별자를 기초로 가축을 식별할 수 있도록 지원함과 아울러 해당 센싱 정보의 센싱 신호를 통해 가축의 건강 상태를 체크할 수 있도록 지원함으로써, 방목 중인 다수의 가축별로 건강 상태를 용이하게 파악할 수 있도록 지원하여 가축 관리의 효율성을 높일 수 있도록 지원하는 동시에 가축의 몸체의 다양한 부위에 부착된 센서를 통해 가축의 건강 상태에 대한 더욱 정확한 정보를 제공하는 효과가 있다. claims: 소, 양 또는 말 중 어느 하나인 방목 대상 가축의 아래턱을 감싸도록 상기 가축의 하관 중에서 아래턱을 감싸도록 밀착되는 커버판;상기 커버판의 상단부에 구비되어 상기 가축의 주둥이 일부를 감싸지만 음식 섭취나 되새김질은 가능하도록 걸쳐져 고정되는 제 1 스트랩을 포함하는 제 1 벨트부;상기 커버판의 하단부에 구비되어 상기 가축의 목 둘레를 감싸도록 걸쳐져 고정되는 제 2 스트랩을 포함하는 제 2 벨트부;상기 커버판이 상기 아래턱에 밀착된 상태에서 상기 커버판의 하면에 구성되어 상기 가축의 신체 상태를 센싱하는 제 1 센서부;스트랩 형태로 구성되면서 상기 가축의 몸체 상부에 배치되어, 상단부가 상기 제 2 스트랩이 상기 목 둘레에 걸쳐질 때 상기 제 2 스트랩의 하면과 밀착되어 고정되는 본체부;상기 본체부의 하단부에 구비되어 상기 가축의 몸체 중 배 둘레를 감싸도록 걸쳐져 고정되는 제 3 스트랩을 포함하는 제 3 벨트부;상기 제 3 스트랩에서 상기 가축의 배와 마주보는 면과 반대면에 구성되어 가축의 신체 상태를 센싱하는 제 2 센서부; 및상기 본체부에서 상기 가축의 등과 마주보는 면과 반대면에 구비되며, 외부 장치와 통신망을 통신하는 통신 모듈과 상기 제 1 센서부 및 제 2 센서부와 연결되는 제어 모듈을 포함하여 구성되고, 상기 제어 모듈이 상기 제 1 센서부 및 제 2 센서부로부터 수신된 센싱 신호를 기초로 생성된 센싱 정보를 생성하여 상기 통신 모듈을 통해 상기 외부 장치로 전송하도록 구성되는 제어부를 포함하되,상기 제 1 벨트부의 제 1 스트랩 일부에 구성되고, 상기 제어 모듈과 연결되어 상기 제 1 스트랩의 신장 여부를 진동 센서 또는 스트레인 게이지로 감지하여 생성한 감지 신호를 상기 제어 모듈로 전송하는 제 3 센서부를 더 포함하며,상기 제어 모듈은 상기 감지 신호를 기초로 음식 섭취에 대한 감지 정보를 생성 후 상기 통신 모듈을 통해 상기 외부 장치로 전송하는 것을 특징으로 하는 가축 모니터링을 위한 체결 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

772/1059 Row 772: application_number: 1020200059853, combined_string: invention_title: 반려동물 건강 관리 시스템 abstract: 반려동물 건강 관리 시스템이 개시된다. 일 실시예에 따른 반려동물 건강 관리 방법은, 반려동물 건강 관리 장치가 반려동물의 건강을 관리하는 방법에 있어서, 상기 반려동물에게 장착된 센싱 장치로부터 상기 반려동물의 움직임을 측정한 센서 데이터를 수신하는 단계와, 상기 센서 데이터에 기초하여 상기 반려동물의 행동 데이터를 생성하는 단계와, 상기 행동 데이터에 따라 급식량을 결정하는 단계와, 상기 행동 데이터 및 상기 급식량에 따라 급식된 사료에 대한 상기 반려동물의 식사량에 기초하여 상기 반려동물의 건강 상태를 판단하는 단계를 포함한다. claims: 반려동물 건강 관리 장치가 반려동물의 건강을 관리하는 방법에 있어서,상기 반려동물에게 장착된 센싱 장치로부터 상기 반려동물의 움직임을 측정한 센서 데이터를 수신하는 단계;상기 센서 데이터에 기초하여 상기 반려동물의 행동 데이터를 생성하는 단계;상기 행동 데이터에 따라 급식량을 결정하는 단계; 및상기 행동 데이터 및 상기 급식량에 따라 급식된 사료에 대한 상기 반려동물의 식사량에 기초하여 상기 반려동물의 건강 상태를 판단하는 단계를 포함하는 반려동물 건강 관리 방법.반려동물에게 장착된 센싱 장치로부터 상기 반려동물의 움직임을 측정한 센서 데이터를 수신하는 수신기; 및상기 센서 데이터에 기초하여 상기 반려동물의 행동 데이터를 생성하고, 상기 행동 데이터에 따라 급식량을 결정하고, 상기 행동 데이터 및 상기 급식량에 따라 급식된 사료에 대한 상기 반려동물의 식사량에 기초하여 상기 반려동물의 건강 상태를 판단하는 컨트롤러를 포함하는 반려동물 건강 관리 장치., Ltext: 농업, prediction: 임업
773/1059 Row 773: application_number: 1020200052484, combined_string: invention_title: 가축 급이기의 사료배출장치 abstract: 본 발명은 축사 내부를 따라 설치되며 사료를 이송하는 사료이송관에 설치되며 상기 사료이송관으로 이송중인 사료를 축사 바닥에 설치되어 있는 사료저장통으로 배출하는 가축 급이기의 사료 배출장치에 있어서, 상기 사료이송관의 사료배출구멍에 설치되는 연결관, 상기 연결관에 선단이 연결되고 그 끝단은 사료저장통의 일측 가장자리에 근접하게 위치하도록 하되, 내부에 형성되어 있는 유로로 사료가 흘러갈 수 있도록 선단에서 끝단으로 갈수록 하향으로 점차적으로 기울어지게 배치되는 제 1사료배출관, 상기 제 1사료배출관의 반대편에 위치하며 상기 연결관에 선단이 연결되고 그 끝단은 사료저장통의 타측 가장자리에 근접하게 위치하도록 하되, 내부에 형성되어 있는 유로로 사료가 흘러갈 수 있도록 선단에서 끝단으로 갈수록 하향으로 점차적으로 기울어지게 배치되는 제 2사료배출관, 상기 제 1, 2사료배출관의 하면에 일정간격 떨어진 상태로 연결 설치되며 상기 제 1, 2사료배출관의 유로로 공급된 사료를 상기 사료저장통의 전 구역으로 배출시키는 적어도 하나 이상의 분배관으로 구성함을 특징으로 하는 가축 급이기의 사료배출장치를 제공한다. claims: 축사 내부를 따라 설치되며 사료를 이송하는 사료이송관(10)에 설치되며 상기 사료이송관(10)으로 이송중인 사료를 축사 바닥에 설치되어 있는 사료저장통(60)으로 배출하는 가축 급이기의 사료 배출장치에 있어서,상기 사료이송관(10)의 사료배출구멍(12)에 설치되는 연결관(20);상기 연결관(20)에 선단(30a)이 연결되고 그 끝단(30b)은 사료저장통(60)의 일측(60a) 가장자리에 근접하게 위치하도록 하되, 내부에 형성되어 있는 유로(32)로 사료가 흘러갈 수 있도록 선단(30a)에서 끝단(30b)으로 갈수록 하향으로 점차적으로 기울어지게 배치되는 제 1사료배출관(30);상기 제 1사료배출관(30)의 반대편에 위치하며 상기 연결관(20)에 선단(40a)이 연결되고 그 끝단(40b)은 사료저장통(60)의 타측(60b) 가장자리에 근접하게 위치하도록 하되, 내부에 형성되어 있는 유로(42)로 사료가 흘러갈 수 있도록 선단(40a)에서 끝단(40b)으로 갈수록 하향으로 점차적으로 기울어지게 배치되는 제 2사료배출관(40);상기 제 1, 2사료배출관(30, 40)의 하면에 일정간격 떨어진 상태로 연결 설치되며 상기 제 1, 2사료배출관(30, 40)의 유로(32, 42)로 공급된 사료를 상기 사료저장통(60)의 전 구역으로 배출시키는 적어도 하나 이상의 분배관(50)으로 구성함을 특징으로 하는 가축 급이기의 사료 배출장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

774/1059 Row 774: application_number: 1020200050518, combined_string: invention_title: 반려동물 케어 시스템 abstract: 반려동물 케어 시스템은 반려동물의 소음을 감지하여 현재 위치로부터 소음원에 대한 방향을 측정하는 소음원 감지부와, 소음원 감지부로부터 측정된 방향으로 이동하기 위한 구동력을 제공하는 주행부와, 적외선 센서 및 근접 센서를 구비하여 주행부에 의해 소음원을 향해 이동함에 따라 반려동물의 위치 및 근접 상태를 측정하는 반려동물 감지부와, 미리 결정된 조건에 따라 반려동물에게 먹이를 공급하는 먹이 공급부를 포함한다. claims: 반려동물의 소음을 감지하여 현재 위치로부터 소음원에 대한 방향을 측정하는 소음원 감지부;상기 소음원 감지부로부터 측정된 방향으로 이동하기 위한 구동력을 제공하는 주행부;적외선 센서 및 근접 센서를 구비하여 상기 주행부에 의해 소음원을 향해 이동함에 따라 반려동물의 위치 및 근접 상태를 측정하는 반려동물 감지부; 및미리 결정된 조건에 따라 반려동물에게 먹이를 공급하는 먹이 공급부를 포함하는 반려동물 케어 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

775/1059 Row 775: application_number: 1020200051068, combined_string: invention_title: 스마트 가축 관리 시스템 및 그 방법 abstract: 스마트 가축 관리 시스템 및 그 방법이 제공된다. 상기 방법은 가축관리서버가 축사에 위치하는 가축들을 촬영한 가축영상데이터를 획득하는 단계; 상기 가축관리서버가 상기 가축영상데이터에 포함된 상기 가축들을 개별 객체로 각각 분리하는 단계; 상기 가축관리서버가 상기 가축영상데이터으로부터 상기 개별 객체의 객체체온정보 및 객체행동정보가 포함된 객체정보를 추출하는 단계; 상기 가축관리서버가 표준축사관리데이터를 기초로하여 상기 객체정보를 분석하여 상기 가축의 이상징후여부를 판단한 판단결과데이터를 생성하는 단계; 및 상기 가축관리서버가 상기 판단결과데이터를 관리자 단말기로 전송하는 단계;를 포함하되, 상기 가축관리서버는 상기 표준축사관리데이터를 기초로하여 딥러닝 기법을 이용하여 상기 가축의 이상징후여부 판단하고, 상기 이상징후여부를 질병증상, 분만증상 및 승가증상으로 구분할 수 있다. claims: 가축관리서버가 축사에 위치하는 가축들을 촬영한 가축영상데이터를 획득하는 단계;상기 가축관리서버가 상기 가축영상데이터에 포함된 상기 가축들을 개별 객체로 각각 분리하는 단계;상기 가축관리서버가 상기 가축영상데이터로부터 상기 개별 객체의 객체체온정보 및 객체행동정보가 포함된 객체정보를 추출하는 단계;상기 가축관리서버가 표준축사관리데이터를 기초로하여 상기 객체정보를 분석하여 상기 가축의 이상징후여부를 판단한 판단결과데이터를 생성하는 단계; 및상기 가축관리서버가 상기 판단결과데이터를 관리자 단말기로 전송하는 단계;를 포함하고,상기 표준축사관리데이터는, 상기 가축영상데이터로부터 이상징후여부가 발생되지 않은 정상객체 및 상기 정상객체의 주변객체의 최고체온정보 및 최저체온정보를 반복 학습하여 생성된 객체기본온도정보와, 정상축사 및 상기 정상축사의 주변축사의 최고온도정보 및 최저온도정보를 반복 학습하여 생성된 축사기본온도정보, 및 상기 정상객체의 정상행동을 분석하여 생성된 객체기본행동정보를 포함하고,상기 가축관리서버는, 상기 표준축사관리데이터를 기초로 하여 딥러닝 기법을 이용하여 상기 가축의 이상징후여부 판단하고, 상기 이상징후여부를 질병증상, 분만증상 및 승가증상으로 각각 구분하고,상기 판단결과데이터를 생성하는 단계는, 상기 가축관리서버가 상기 객체체온정보와 상기 표준축사관리데이터에 포함된 상기 객체기본온도정보 및 상기 객체행동정보와 상기 표준축사관리데이터에 포함된 상기 객체기본행동정보를 비교 분석하는 단계;상기 비교 분석한 결과로 상기 이상징후여부가 상기 질병증상으로 판단된 경우, 상기 가축관리서버가 질병객체에 대한 상기 객체체온정보를 모니터링하여 질병확산경로를 예측하는 단계;상기 비교 분석한 결과로 상기 이상징후여부가 상기 분만증상으로 판단된 경우, 상기 가축관리서버가 분만객체에 대한 상기 객체행동정보를 모니터링하여 분만상황정보를 예측하는 단계; 및상기 비교 분석한 결과로 상기 이상징후여부가 상기 승가증상으로 판단된 경우, 상기 가축관리서버가 승가객체에 대한 상기 객체행동정보를 모니터링하여 승가상황정보를 예측하는 단계;를 포함하고, 상기 질병확산경로를 예측하는 단계는,상기 가축관리서버가 상기 질병객체의 체온을 측정하여 제1 객체온도정보를 획득하고, 상기 질병객체의 주변객체의 체온을 측정하여 제2 객체온도정보를 획득하는 단계; 및상기 가축관리서버가 상기 표준축사관리데이터에 포함된 상기 객체기본온도정보를 기초로 하여 상기 제1 객체온도정보 및 제2 객체온도정보 간의 제1 온도차이를 산출하여 질병확산경로를 예측하는 단계;를 포함하고,상기 분만상황정보를 예측하는 단계는,상기 가축관리서버가 상기 분만객체의 분만 후에 환경정보를 고려하여 신규객체에 대한 객체체온정보 및 객체행동정보를 모니터링하여 이상징후가 발생한 경우, 상기 관리자 단말기로 알림메시지를 전송하는 단계-상기 환경정보는, 상기 분만객체 및 상기 축사 주변의 날씨정보, 계절정보 및 시간정보를 포함함-;상기 가축관리서버가 상기 환경정보를 기반으로, 상기 분만객체가 기 설정된 계절에 기 설정된 날씨 및 기 설정된 시간대에 상기 신규객체를 분만한 경우, 상기 신규객체의 체온을 지속적으로 모니터링하는 단계;상기 가축관리서버가 상기 모니터링의 결과 상기 신규객체의 체온이 기 설정된 온도 이하인 저체온일 경우에, 상기 신규객체가 저체온임을 알리는 알림 메시지를 상기 관리자 단말기로 전송하는 단계; 및상기 가축관리서버가 상기 모니터링의 결과 상기 신규객체의 체온이 상기 저체온일 경우에, 상기 축사의 내부 기온을 기 설정된 온도로 상승시키며 상기 축사의 조명을 기 설정된 밝기로 밝게 하도록 하는 신호를 생성하여 축사 제어 장치로 전송하는 단계;를 포함하고,상기 승가상황정보를 예측하는 단계는,상기 가축관리서버가 상기 승가상황정보를 실시간으로 업데이트하여 상기 관리자 단말기에게 실시간으로 전송하는 단계-상기 승가상황정보는 발정 전의 객체 수, 발정 예상 시간, 발정 예상 객체 수 및 공태 예상 기간을 포함함-; 및상기 가축관리서버가 상기 승가증상으로 판단된 경우, 상기 승가상황정보를 이용하여 승가 객체와 승가가 예상되는 객체가 합방되도록 하는 신호를 생성하여 상기 축사 제어 장치로 전송하는 단계;를 포함하는, 스마트 가축 관리 방법.축사의 상황을 제어하고, 상기 축사에 위치하는 가축들을 촬영한 가축영상데이터를 실시간으로 획득하는 축사제어장치; 및상기 가축영상데이터에 포함된 상기 가축들을 개별 객체로 각각 분리하고, 상기 가축영상데이터로부터 상기 개별 객체의 객체체온정보 및 객체행동정보가 포함된 객체정보를 추출하고, 표준축사관리데이터를 기초로 상기 추출된 객체정보를 분석하여 상기 가축의 이상징후여부를 판단한 판단결과데이터를 생성하고, 상기 생성된 판단결과데이터를 관리자 단말기로 전송하는 가축관리서버;를 포함하고,상기 표준축사관리데이터는, 상기 가축영상데이터로부터 이상징후여부가 발생되지 않은 정상객체 및 상기 정상객체의 주변객체의 최고체온정보 및 최저체온정보를 반복 학습하여 생성된 객체기본온도정보와, 정상축사 및 상기 정상축사의 주변축사의 최고온도정보 및 최저온도정보를 반복 학습하여 생성된 축사기본온도정보, 및 상기 정상객체의 정상행동을 분석하여 생성된 객체기본행동정보를 포함하고,상기 가축관리서버는, 상기 표준축사관리데이터를 기초로 하여 딥러닝 기법을 이용하여 상기 가축의 이상징후여부 판단하고, 상기 이상징후여부를 질병증상, 분만증상 및 승가증상으로 각각 구분하고,상기 객체체온정보와 상기 표준축사관리데이터에 포함된 상기 객체기본온도정보 및 상기 객체행동정보와 상기 표준축사관리데이터에 포함된 상기 객체기본행동정보를 비교 분석하고,상기 비교 분석한 결과로 상기 이상징후여부가 상기 질병증상으로 판단된 경우 질병객체에 대한 상기 객체체온정보를 모니터링하여 질병확산경로를 예측하고, 상기 비교 분석한 결과로 상기 이상징후여부가 상기 분만증상으로 판단된 경우 분만객체에 대한 상기 객체행동정보를 모니터링하여 분만상황정보를 예측하며, 상기 비교 분석한 결과로 상기 이상징후여부가 상기 승가증상으로 판단된 경우 승가객체에 대한 상기 객체행동정보를 모니터링하여 승가상황정보를 예측하고,상기 질병확산경로를 예측 시에, 상기 질병객체의 체온을 측정하여 제1 객체온도정보를 획득하고 상기 질병객체의 주변객체의 체온을 측정하여 제2 객체온도정보를 획득하고, 상기 표준축사관리데이터에 포함된 상기 객체기본온도정보를 기초로하여 상기 제1 객체온도정보 및 제2 객체온도정보 간의 제1 온도차이를 산출하고,상기 분만상황정보를 예측 시에, 상기 분만객체의 분만 후에 환경정보를 고려하여 신규객체에 대한 객체체온정보 및 객체행동정보를 모니터링하여 이상징후가 발생한 경우 상기 관리자 단말기로 알림메시지를 전송하고-상기 환경정보는, 상기 분만객체 및 상기 축사 주변의 날씨정보, 계절정보 및 시간정보를 포함함-, 상기 환경정보를 기반으로 상기 분만객체가 기 설정된 계절에 기 설정된 날씨 및 기 설정된 시간대에 상기 신규객체를 분만한 경우 상기 신규객체의 체온을 지속적으로 모니터링하고, 상기 모니터링의 결과 상기 신규객체의 체온이 기 설정된 온도 이하인 저체온일 경우에 상기 신규객체가 저체온임을 알리는 알림 메시지를 상기 관리자 단말기로 전송하고, 상기 모니터링의 결과 상기 신규객체의 체온이 기 설정된 온도 이하인 저체온일 경우에 상기 축사의 내부 기온을 기 설정된 온도로 상승시키며 상기 축사의 조명을 기 설정된 밝기로 밝게 하도록 하는 신호를 생성하여 상기 축사 제어 장치로 전송하고,상기 승가상황정보를 예측 시에, 상기 승가상황정보를 실시간으로 업데이트하여 상기 관리자 단말기에게 실시간으로 전송하고-상기 승가상황정보는 발정 전의 객체 수, 발정 예상 시간, 발정 예상 객체 수 및 공태 예상 기간을 포함함-, 상기 승가증상으로 판단된 경우 상기 승가상황정보를 이용하여 승가 객체와 승가가 예상되는 객체가 합방되도록 하는 신호를 생성하여 상기 축사 제어 장치로 전송하는, 스마트 가축 관리 시스템., Ltext: 농업, prediction: 임업
776/1059 Row 776: application_number: 1020200050042, combined_string: invention_title: 반려동물 비문인식 블록체인 플랫폼 abstract: 본 발명은 반려동물 비문인식 블록체인 플랫폼에 관한 것으로서, 보다 상세하게는 동물의 비문 이미지를 촬영하는 촬영부와, 촬영된 이미지로부터 비문데이터를 획득하는 분석부, 획득한 비문데이터를 저장하는 데이터베이스부로 이루어지되, 비문의 조직편을 식별하도록 하여 반려동물의 인식률을 상승시키고, 비문데이터를 ERC-20 기반의 블록체인 네트워크를 이용하여 저장함에 따라 보안성을 향상시키며, 등록 및 검색의 간편화를 기대할 수 있어, 보호자가 손쉽게 데이터를 업로드 및 공유할 수 있도록 고안된 반려동물 비문인식 블록체인 플랫폼에 관한 것이다. claims: 동물의 비문 이미지를 촬영하도록 사용자 단말기(M)에 구비되는 촬영부(SV);촬영된 이미지를 전송받아 비문 데이터를 획득하는 분석부(20);상기 비문 데이터와, 소유주가 입력한 소유주정보가 블록체인 네트워크를 통하여 저장되는 데이터베이스부(10);상기 사용자 단말기를 통해 상기 데이터베이스부에 접속하여, 상기 비문 데이터를 검색 및 출력하는 접속부(40);를 포함하여 이루어지되,상기 데이터베이스부(10)에는비문 데이터를 저장하는 저장하드(H)를 탈착 가능하게 결합 및 연결할 수 있도록 이루어지되,상기 저장하드(H)는 접속단자를 노출시키는 덮개(C1)가 구비되는 케이스(C)에 보관되어 저장하드(H) 내부에 이물질이 유입되는 것을 방지하며,상기 덮개(C1)는 상기 케이스(C)에 탈착수단(70)에 의해 탈착 가능하게 결합되되,상기 탈착수단(70)은상기 케이스(C)에 구비되며 인입부가 구비된 제1블록(71)과, 상기 제1블록(71)의 인입부(713)에 삽입되는 인입바(723)가 구비되어 상기 제1블록(71)에 슬라이딩 결합되도록 덮개(C1)에 구비되는 제2블록(72) 및 상기 제1블록(71)과 제2블록(72)의 결합력을 유지하는 복수의 고정볼(74)을 포함하여 이루어져, 상기 케이스(C)와 덮개(C1)는 원터치 결합 및 분리가 가능하게 이루어지되,상기 케이스(C)의 일단에 구비되는 제1블록(71)은내부에는 수직방향으로 형성되는 낙하공(711A)과, 상기 낙하공의 하부(711Ab)에서 후방 수평방향으로 연통되며 전방에 제1인출공(714)이 연통된 안착공(711B)과, 상기 안착공(711B) 후방과 상기 낙하공(711A) 상부를 연결하는 곡선형의 위치변위공(711D)이 구비되고,상기 제1인출공(714)에는 반구형의 고정체(717)가 인입부(713)로 돌출 가능하게 힌지결합되며,상기 덮개에 구비되는 제2블록(72)의 인입바(723)에는 상기 인입부(713) 방향으로 돌출된 고정체(717)가 삽입되는 고정홈(723A)이 형성되며,상기 복수개의 고정볼(74)이 상기 안착공(711B)에 채워져 상기 고정체(717)의 후단을 지지하여 상기 고정체(717)가 제1블록(71) 내측으로 인입되는 것을 방지하여 제1블록(71)과 제2블록(72)의 고정력을 유지하고,상기 제1블록(71)에는상기 안착공(711B)에 채워진 최후방의 고정볼(74)을 상기 위치변위공(711D)을 통해 낙하공(711A) 상부로 위치이동시켜, 상기 고정체(717)가 제1블록(71) 내측으로 인입되는 것을 허용하여 상기 제1블록(71)과 제2블록(72)을 슬라이딩 결합 및 해정 시킬 수 있도록 하는 위치변위수단(75)이 더 구비되는 것을 특징으로 하는 비문인식 블록체인 플랫폼., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

777/1059 Row 777: application_number: 1020200129601, combined_string: invention_title: 농산물 가공장치 abstract: 농산물 가공장치가 개시된다. 본 발명에 따른 농산물 가공장치는, 일측에 개폐도어가 설치되고, 내부의 바닥면에 한 쌍의 인입레일이 설치되며, 상부에 진공펌프와 가압펌프가 각각 연결되고, 농산물이 내부로 인입된 후, 순서에 따라 상기 진공펌프에 의해 진공 및 해제되고 상기 가압펌프로부터 공급되는 혼합액에 의해 가압 및 해제되도록 마련되는 가공챔버; 상기 농산물을 상기 가공챔버로 운반하도록 형성되고, 상기 인입레일과 대응되는 안내레일이 상부에 설치되도록 마련되는 운반부; 상기 운반부의 상부에 적어도 하나 이상 적재되고, 상기 농산물이 수용되며, 상기 안내레일과 상기 인입레일을 따라 안내되어 상기 가공챔버 내로 인입되도록 마련되는 농산물 수용부; 및 상기 혼합액이 저장되고, 상기 가압펌프와 연결되도록 마련되는 혼합액 저장부;를 포함하는 것을 특징으로 한다. claims: 일측에 개폐도어가 설치되고, 내부의 바닥면에 한 쌍의 인입레일이 설치되며, 상부에 진공펌프와 가압펌프가 각각 연결되고, 농산물이 내부로 인입된 후, 순서에 따라 상기 진공펌프에 의해 진공 및 해제되고 상기 가압펌프로부터 공급되는 혼합액에 의해 가압 및 해제되도록 마련되는 가공챔버;상기 농산물을 상기 가공챔버로 운반하도록 형성되고, 상기 인입레일과 대응되는 안내레일이 상부에 설치되도록 마련되는 운반부;상기 운반부의 상부에 적어도 하나 이상 적재되고, 상기 농산물이 수용되며, 상기 안내레일과 상기 인입레일을 따라 안내되어 상기 가공챔버 내로 인입되도록 마련되는 농산물 수용부; 및상기 혼합액이 저장되고, 상기 가압펌프와 연결되도록 마련되는 혼합액 저장부;를 포함하고상기 운반부는 상기 안내레일의 선단부에 상기 인입레일과 연결되도록 설치되는 이음레일을 더 포함하며, 상기 인입레일은 일측에 고정홈을 갖는 계단형상의 인입레일 연결부가 형성되고, 상기 이음레일은 상기 인입레일과 연결되는 일측에 상기 인입레일 연결부와 대응되도록 고정돌기를 갖는 이음레일 연결부가 형성되며, 상기 운반부는 상기 안내레일과 상기 인입레일을 상기 이음레일로 연결시 상기 이음레일 연결부와 상기 인입레일 연결부 간의 연결구조에 의해 상기 가공챔버에 고정되도록 연결되는 것을 특징으로 하는 농산물 가공장치., Ltext: 농업, prediction: 농업
778/1059 Row 778: application_number: 1020200129602, combined_string: invention_title: 농산물 가공방법 abstract: 농산물 가공방법이 개시된다. 본 발명에 따른 농산물 가공방법은, 토마토가 수용된 적어도 하나 이상의 농산물 수용부를 운반부에 적재하여 가공챔버의 인입 위치까지 운반하고, 상기 운반부에 설치된 안내레일과 이음레일을 상기 가공챔버의 내부에 형성된 인입레일과 연결하는 단계; 상기 농산물 수용부를 상기 안내레일 및 이음레일을 따라 이동시켜 상기 인입레일에 위치되도록 상기 가공챔버 내로 인입시킨 후, 상기 운반부를 상기 가공챔버와 분리하고, 상기 가공챔버를 밀폐시키는 단계; 상기 가공챔버를 진공펌프에 의해 일정시간 동안 진공상태로 유지시켜 토마토 껍질과 내용물 사이에 침투공간을 형성하는 단계; 상기 토마토 껍질과 내용물 사이에 침투공간의 형성 후, 상기 가공챔버의 진공상태를 해제하고, 상기 토마토가 복원되도록 일정시간 동안 안정화시키는 단계; 상기 토마토의 안정화 후, 가압펌프를 동작시켜 혼합액 저장부에 저장된 혼합액을 상기 가공챔버에 공급하여 채우고 일정시간 동안 가압하는 단계; 상기 가압펌프에 의해 상기 가공챔버의 가압상태를 일정시간 동안 해제하고 다시 일정시간 동안 가압하여 상기 가공챔버의 가압을 유지하는 단계; 및 상기 가공챔버에 채워진 혼합액을 상기 혼합액 저장부로 회수하고, 상기 가공챔버를 개방하여 상기 농산물 수용부를 인출하는 단계;를 포함하는 것을 특징으로 한다. claims: 토마토가 수용된 적어도 하나 이상의 농산물 수용부를 운반부에 적재하여 가공챔버의 인입 위치까지 운반하고, 상기 운반부에 설치된 안내레일과 이음레일을 상기 가공챔버의 내부에 형성된 인입레일과 연결하는 단계;상기 농산물 수용부를 상기 안내레일 및 이음레일을 따라 이동시켜 상기 인입레일에 위치되도록 상기 가공챔버 내로 인입시킨 후, 상기 운반부를 상기 가공챔버와 분리하고, 상기 가공챔버를 밀폐시키는 단계;상기 가공챔버를 진공펌프에 의해 일정시간 동안 진공상태로 유지시켜 토마토 껍질과 내용물 사이에 침투공간을 형성하는 단계;상기 토마토 껍질과 내용물 사이에 침투공간의 형성 후, 상기 가공챔버의 진공상태를 해제하고, 상기 농산물이 복원되도록 일정시간 동안 안정화시키는 단계;상기 농산물의 안정화 후, 가압펌프를 동작시켜 혼합액 저장부에 저장된 혼합액을 상기 가공챔버에 공급하여 채우고 일정시간 동안 가압하는 단계;상기 가압펌프에 의해 상기 가공챔버의 가압상태를 일정시간 동안 해제하고 다시 일정시간 동안 가압하여 상기 가공챔버의 가압을 유지하는 단계; 및상기 가공챔버에 채워진 혼합액을 상기 혼합액 저장부로 회수하고, 상기 가공챔버를 개방하여 상기 농산물 수용부를 인출하는 단계;를 포함하고,상기 인입레일은 일측에 고정홈을 갖는 계단형상의 인입레일 연결부가 형성되고, 상기 이음레일은 상기 인입레일과 연결되는 일측에 상기 인입레일 연결부와 대응되도록 고정돌기를 갖는 이음레일 연결부가 형성되며, 상기 운반부는 상기 안내레일과 상기 인입레일을 상기 이음레일로 연결시 상기 이음레일 연결부와 상기 인입레일 연결부 간의 연결구조에 의해 상기 가공챔버와 고정되도록 연결되는 것을 특징으로 하는 농산물 가공방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

779/1059 Row 779: application_number: 1020200090193, combined_string: invention_title: 농산물 매매가격 제시 방법 및 시스템 abstract: 본 개시는 정보 처리 시스템에 의해 수행되는 농산물 매매가격 제시 방법에 관한 것이다. 농산물 매매가격 제시 방법은, 통신부에 의해, 시세 데이터 세트를 수신하는 단계, 프로세서에 의해, 시세 데이터 세트에 주성분 분석(Principal Component Analysis)을 사용하여 시장 수급 상황을 반영한 주성분을 추출하는 단계, 프로세서에 의해, 추출된 주성분에 따라 미리 결정된 생산자 수취 가격의 비율을 적용하여 표준 가격을 산출하는 단계를 포함할 수 있다. claims: 정보 처리 시스템에 의해 수행되는 농산물 매매가격 제시 방법에 있어서,통신부에 의해, 농산물의 출하가, 경매가, 도매가, 소매가 중 적어도 하나를 포함하는 시세 데이터 세트를 수신하는 단계;프로세서에 의해, 상기 시세 데이터 세트에 주성분 분석(Principal Component Analysis)을 사용하여 시장 수급 상황을 반영한 주성분을 추출하는 단계;상기 프로세서에 의해, 상기 추출된 주성분에 미리 결정된 생산자 수취 가격의 비율을 적용하여 표준 가격을 산출하는 단계; 및상기 프로세서에 의해, 상기 산출된 표준 가격에 미리 결정된 스케일링 조정값을 적용하여 제시 가격을 산출하는 단계 - 상기 스케일링 조정값은 상품 대비 파품의 수율의 차이를 반영한 값을 포함하고, 상기 제시 가격은 등급 외 농산물의 제시 가격임 -를 포함하는, 농산물 매매가격 제시 방법.제1항에 따른 정보 처리 시스템에 의해 농산물 매매가격 제시 방법을 컴퓨터에서 실행하기 위한 컴퓨터 프로그램이 기록된, 컴퓨터로 판독 가능한 매체.정보 처리 시스템에 있어서,농산물의 출하가, 경매가, 도매가, 소매가 중 적어도 하나를 포함하는 시세 데이터 세트를 수신하도록 구성된 통신부;상기 시세 데이터 세트 및 하나 이상의 프로그램 명령어를 저장하도록 구성된 저장부; 및상기 저장된 하나 이상의 프로그램 명령어를 실행함으로써, 시세 데이터 세트에 주성분 분석을 사용하여 주성분을 추출하는 주성분 분석부 및 추출된 주성분에 미리 결정된 생산자 수취 가격의 비율을 적용하여 표준 가격을 산출하도록 구성된 가격조정부로 구성된 프로세서를 포함하며,상기 가격조정부는,상기 산출된 표준 가격에 미리 결정된 스케일링 조정값을 적용하여 제시 가격을 산출하도록 더 구성되며, 상기 스케일링 조정값은 상품 대비 파품의 수율의 차이를 반영한 값을 포함하고, 상기 제시 가격은 등급 외 농산물의 제시 가격인,정보 처리 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

780/1059 Row 780: application_number: 1020200045251, combined_string: invention_title: 제습 건조기 abstract: 본 발명은 제습 건조기에 관한 것으로서, 농산물 등의 피건조물을 건조시키기 위한 공기에 포함된 수분의 제습효율이 매우 우수함은 물론 여름철 저온건조 및 겨울철 고온건조가 가능하고, 나아가, 피건조물 전체를 균일하게 건조할 수 있어 건조효율이 크게 향상될 수 있으며, 공기의 저항이 줄어들어 공기의 순환흐름이 크게 향상될 수 있는 효과가 있다. claims: 피건조물이 수용되고, 내부 타측에 격벽이 수직형성되며, 상기 격벽과 타측 내면 사이에 피건조물을 건조시키기 위한 공기가 순환이동하는 순환공간이 형성되는 건조실과;상기 건조실의 순환공간에 구비되고, 상기 건조실의 내부 일측에서 상기 순환공간의 하부로 순환이동하는 공기가 통과 및 공기에 포함된 습기를 제거하는 증발기와;상기 증발기의 상부방향에 위치하도록 상기 건조실의 순환공간에 구비되고, 상기 증발기를 통과한 습기가 제거된 공기가 통과 및 공기를 가열하는 응축기와;상기 건조실의 일측에서 타측방향으로 일정길이로 연장되어 상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 상부에 구비되고, 상기 응축기에 의해 가열된 공기를 통해 피건조물을 건조시키기 위해 내부로 유입된 상기 응축기에 의해 가열된 공기를 상기 건조실의 내부 일측으로 배출하는 배출구가 형성되는 상부덕트와;상기 상부덕트의 내부로 상기 증발기에 의해 습기가 제거 및 상기 응축기에 의해 가열된 공기를 안내하는 송풍기와;상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 하부에 구비되고, 상기 상부덕트의 배출구를 통해 상기 건조실의 내부 일측으로 배출되어 피건조물을 건조시키는 공기가 유입되는 유입구가 형성되며, 상기 유입구를 통해 내부로 유입된 공기를 상기 순환공간으로 안내하는 하부덕트와;상기 건조실의 외부에 설치되고, 상기 건조실의 순환공간에 구비된 증발기 및 응축기와 연결되는 압축기 및 응축기가 구비되는 실외기와;상기 건조실의 순환공간에 구비된 증발기와 상기 실외기의 압축기를 연결하는 제 1연결라인과, 상기 실외기의 압축기와 상기 실외기의 응축기를 연결하는 제 2연결라인과, 상기 실외기의 응축기와 상기 건조실의 순환공간에 구비된 증발기를 연결하는 제 3연결라인과, 상기 제 2연결라인으로부터 분기되어 상기 제 2연결라인과 상기 건조실의 순환공간에 구비된 응축기를 연결하는 제 4연결라인과, 상기 제 4연결라인과 일정간격을 유지한 상태로 상기 제 2연결라인으로부터 분기되어 상기 제 2연결라인과 상기 건조실의 순환공간에 구비된 응축기를 연결하는 제 5연결라인으로 구성되는 연결라인과;상기 제 4연결라인에 구비되는 체크밸브와;상기 제 4연결라인이 분기되는 상기 제 2연결라인의 분기지점과 상기 제 5연결라인이 분기되는 제 2연결라인의 분기지점 사이의 상기 제 2연결라인에 구비되어 상기 제 2연결라인을 개폐하는 제 1개폐밸브와, 상기 제 5연결라인에 구비되어 상기 제 5연결라인을 개폐하는 제 2개폐밸브로 구성되는 개폐밸브와;상기 건조실의 내부의 온도를 설정하는 온도설정부와;상기 건조실의 내부의 온도를 감지하는 온도센서와;상기 응축기의 상부방향에 위치하도록 상기 건조실의 순환공간에 구비되는 보조히터와;상기 온도센서의 온도감지값과 상기 온도설정부의 온도설정값을 비교하여 상기 개폐밸브, 상기 건조실의 순환공간의 증발기와 응축기 및 상기 실외기와 상기 보조히터를 제어하는 제어부;를 포함하여 이루어지는 것을 특징으로 하는 제습 건조기.피건조물이 수용되고, 내부 타측에 격벽이 수직형성되며, 상기 격벽과 타측 내면 사이에 피건조물을 건조시키기 위한 공기가 순환이동하는 순환공간이 형성되는 건조실과;상기 건조실의 순환공간에 구비되고, 상기 건조실의 내부 일측에서 상기 순환공간의 하부로 순환이동하는 공기가 통과 및 공기에 포함된 습기를 제거하는 증발기와;상기 증발기의 일측 하부에 구비되고, 상기 증발기에서 발생되어 상기 증발기의 일측 하부방향으로 낙하하는 물이 내부에 수용되는 물받이부와;상기 물받이부의 내면 일측에 상기 물받이부의 일측에서 타측 하부방향으로 하향경사지게 일정높이로 형성되는 일측 경사판과, 상기 물받이부의 내면 타측에 상기 물받이부의 타측에서 일측 하부방향으로 하향경사지게 일정높이로 형성되고 일측이 상기 일측 경사판의 타측 하부 방향에 위치하는 타측 경사판으로 구성되는 경사판부와;상기 증발기의 상부방향에 위치하도록 상기 건조실의 순환공간에 구비되고, 상기 증발기를 통과한 습기가 제거된 공기가 통과 및 공기를 가열하는 응축기와;상기 건조실의 일측에서 타측방향으로 일정길이로 연장되어 상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 상부에 구비되고, 상기 응축기에 의해 가열된 공기를 통해 피건조물을 건조시키기 위해 내부로 유입된 상기 응축기에 의해 가열된 공기를 상기 건조실의 내부 일측으로 배출하는 배출구가 형성되는 상부덕트와;상기 상부덕트의 내부로 상기 증발기에 의해 습기가 제거 및 상기 응축기에 의해 가열된 공기를 안내하는 송풍기와;상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 하부에 구비되고, 상기 상부덕트의 배출구를 통해 상기 건조실의 내부 일측으로 배출되어 피건조물을 건조시키는 공기가 유입되는 유입구가 형성되며, 상기 유입구를 통해 내부로 유입된 공기를 상기 순환공간으로 안내하는 하부덕트;를 포함하여 이루어지는 것을 특징으로 하는 제습 건조기.피건조물이 수용되고, 내부 타측에 격벽이 수직형성되며, 상기 격벽과 타측 내면 사이에 피건조물을 건조시키기 위한 공기가 순환이동하는 순환공간이 형성되는 건조실과;상기 건조실의 순환공간에 구비되고, 상기 건조실의 내부 일측에서 상기 순환공간의 하부로 순환이동하는 공기가 통과 및 공기에 포함된 습기를 제거하는 증발기와;상기 증발기의 상부방향에 위치하도록 상기 건조실의 순환공간에 구비되고, 상기 증발기를 통과한 습기가 제거된 공기가 통과 및 공기를 가열하는 응축기와;상기 건조실의 일측에서 타측방향으로 일정길이로 연장되어 상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 상부에 구비되고, 상기 응축기에 의해 가열된 공기를 통해 피건조물을 건조시키기 위해 내부로 유입된 상기 응축기에 의해 가열된 공기를 상기 건조실의 내부 일측으로 배출하는 배출구가 전측, 후측 및 하부에 각각 형성되며, 상하간격이 타측에서 일측으로 갈수록 점차 작아지는 상부덕트와;상기 상부덕트의 내부로 상기 증발기에 의해 습기가 제거 및 상기 응축기에 의해 가열된 공기를 안내하는 송풍기와;상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 전측 하부에 상기 건조실의 일측에서 타측방향으로 일정길이로 좌우연장되는 전측 하부덕트와, 상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 후측 하부에 상기 전측 하부덕트를 따라 일정길이로 좌우연장되는 후측 하부덕트와, 상기 전측 하부덕트 및 상기 후측 하부덕트와 연통되도록 상기 건조실의 내부 일측 하부에 상기 건조실의 전측에서 후측방향으로 일정길이로 전후연장되는 일측 하부덕트로 구성되고, 상기 전측 하부덕트, 상기 후측 하부덕트 및 상기 일측 하부덕트에 상기 상부덕트의 배출구를 통해 상기 건조실의 내부 일측으로 배출되어 피건조물을 건조시키는 공기가 유입되는 유입구가 형성되며, 상기 유입구를 통해 내부로 유입된 공기를 상기 순환공간으로 안내하는 하부덕트;를 포함하여 이루어지는 것을 특징으로 하는 제습 건조기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

781/1059 Row 781: application_number: 1020200020618, combined_string: invention_title: 인공지능 기술을 이용한 농산물의 병충해 발생 정보를 획득하는 방법 및 이를 위한 장치 abstract: 본 발명은 농산물 관리 서버가 병충해 정보를 획득하는 방법을 개시한다. 특히, 상기 방법은 농산물의 특정 부위에 대한 N 개의 제 1 이미지들을 획득하고, 상기 N 개의 제 1 이미지들을 기반으로, 상기 농산물이 병충해 피해를 입지 않은 경우의 상기 특정 부위의 제 1 색상 정보를 추출하고, 상기 농산물의 특정 부위가 병충해 피해를 입은 것을 포함하는 X 개의 제 2 이미지들을 획득하고, 상기 X 개의 제 2 이미지들에 포함된 상기 특정 부위의 제 2 색상 정보를 추출하고, 상기 제 1 색상 정보 및 상기 제 2 색상 정보를 비교하여, 병충해가 발생한 경우의 이미지 값들을 저장하고, 농장의 카메라를 통해 수신한 제 3 이미지를 상기 이미지 값과 비교한 것을 기반으로, 상기 병충해 정보를 획득할 수 있다. claims: 농산물 관리 서버가 병충해 정보를 획득하는 방법에 있어서,농산물의 특정 부위에 대한 N 개의 제 1 이미지들을 획득하고,상기 N 개의 제 1 이미지들을 기반으로, 상기 농산물이 병충해 피해를 입지 않은 경우의 상기 특정 부위의 제 1 색상 정보를 추출하고,상기 농산물의 특정 부위가 병충해 피해를 입은 것을 포함하는 X 개의 제 2 이미지들을 획득하고,상기 X 개의 제 2 이미지들에 포함된 상기 특정 부위의 제 2 색상 정보를 추출하고,상기 제 1 색상 정보 및 상기 제 2 색상 정보를 비교하여, 병충해가 발생한 경우의 이미지 값들을 저장하고,농장에 설치된 카메라를 통해 수신한 제 3 이미지를 상기 이미지 값과 비교한 것을 기반으로, 상기 병충해 정보를 획득하고,상기 병충해 정보를 획득하는 것은,상기 제 3 이미지를 상기 이미지 값과 비교한 것을 기반으로, 복수의 후보 병충해들을 선택하고,상기 제 3 이미지가 촬영된 시간, 상기 농장의 온습도, 상기 농장의 토양 성분을 기반으로, 상기 복수의 후보 병충해들 중, 특정 병충해를 결정하고,상기 농장은 상기 농장에 설치된 온습도 센서를 통해 상기 농장의 온습도 정보를 획득하고,상기 농장은 상기 온습도 정보 및 상기 농산물에 따른 목표 온습도를 기반으로 상기 농장에 설치된 조명 장치 및 가습 장치를 제어하고,상기 조명 장치는 조명, 상기 조명의 아래에 설치되어 상기 조명의 명암을 조절하는 개폐 장치 및 상기 조명과 상기 개폐 장치 사이에 설치되어 상기 조명의 색상을 변경하기 위한 광색 조절 장치를 포함하고,상기 조명 장치는 현 시간에 대응하는 상기 농산물을 위한 광색에 대한 정보를 RGB 값으로 획득하고, 상기 광색 조절 장치에 포함된 복수의 광색판들 중, 상기 RGB 값과 가장 가까운 RGB 값을 가지는 제 1 광색판을 상기 조명의 아래쪽으로 위치시키고, 상기 제 1 광색판을 제외한 나머지 제 2 광색판들은 상기 조명으로부터 일정 거리 이상 떨어져 위치하도록 제어되고,상기 농장은 상기 카메라를 통해 상기 농산물의 크기를 측정하고,상기 농산물의 크기에 대한 측정은 상기 카메라가 제 1 시점에서 상기 농산물을 촬영한 제 4 이미지와 상기 카메라가 상기 제 1 시점 이후인 제 2 시점에서 상기 농산물을 촬영한 제 5 이미지를 비교하여, 상기 제 4 이미지에서 상기 농산물이 차지하는 제 1 비율과 상기 제 5 이미지에서 상기 농산물이 차지하는 제 2 비율 간의 차이 값을 계산하고,상기 제 4 이미지에서의 상기 농산물의 제 1 크기를 산출하고,상기 차이 값 및 상기 제 1 크기를 기반으로, 상기 제 2 시점에서의 상기 농산물의 제 2 크기를 결정하는 것을 포함하고,상기 제 1 크기를 산출하는 것은 상기 카메라의 중심선을 기준으로 2개의 측정선들을 생성하고, 상기 2개의 측정선들 각각이 상기 농산물을 만나는 교차점들을 결정하고, 상기 교차점들을 잇는 선과 상기 중심선이 만나는 지점으로부터 상기 카메라까지의 길이를 측정하고, 상기 측정된 카메라까지의 길이와, 상기 중심선과 상기 2개의 측정선 사이의 각도를 이용하여 상기 농산물의 세로 길이를 측정하고, 상기 세로 길이 및 상기 농산물의 가로 방향의 양 끝점을 기반으로 상기 농산물의 제 1 크기를 산출하는 것을 포함하고,상기 농산물은 복수의 재배 영역들에서 재배되고,상기 복수의 재배 영역들은 세로 길이는 동일하되, 가로 길이는 서로 상이하고,상기 복수의 재배 영역들은 각 라인 별로 설치된 가로 이동 레일들 위에 설치되어, 가로 방향으로 이동하며,상기 가로 이동 레일들의 가장 우측 방향으로 이동하여, 세로 이동 레일에 옮겨지면, 상기 세로 이동 레일에 따라 세로 방향으로 이동하는,병충해 정보 획득 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

782/1059 Row 782: application_number: 1020200002465, combined_string: invention_title: 하이브리드 냉온풍 겸용 건조장치 abstract: 본 발명은 하이브리드 냉온풍 겸용 건조장치에 관한 것으로서, 제습기와, 제습기 후단에 열교환기를 설치하고, 이 열교환기 후단에 스팀온풍기를 설치하며, 스팀온풍기 후단에 냉각쿨러를 설치하고, 냉각쿨러에서 토출되는 공기를 공급받는 건조실를 형성하며, 건조실과 제습기 사이에 제1댐퍼를 형성하고, 건조실과 열교환기 사이에 제2댐퍼를 형성함으로써, 제습기에서 수분이 제거된 공기가 열교환기 및 스팀온풍기, 냉각쿨러로 순차 통과되면서 정해진 온도로 냉각 또는 가열된 후, 건조실 내로 공급되어 농산물을 고온의 열기 또는 냉기로 건조하되, 이 건조실 내의 열기 또는 냉기가 제1댐퍼 또는 제2댐퍼를 통해 열교환기를 가열한 후 배출되도록 하거나 혹은 제습기로 재공급된다.본 발명에 따르면, 열교환기, 스팀온풍기, 냉각쿨러의 작동을 제어하여, 건조실 내로 열풍을 공급하거나 또는 냉풍을 선택 공급할 수 있고, 이 열풍 또는 냉풍의 선택 공급으로 건조실 내에서 다양한 종류의 농산물을 건조할 수 있으며, 특히, 건조실 내에서 배출되는 공기중 일부를 건조실 내로 재 공급하되, 일부 공기는 외부로 배출하면서, 외부 공기를 재 공급받아 건조실 내의 공기 오염농도가 감소되고, 이 공기 오염농도가 감소된 공기를 농산물에 마찰시키면서, 농산물을 건조하여 농산물을 청결한 상태로 유지시킬 수 있다. claims: 공기를 공급받아 이 공기에 포함된 수분을 제거하는 제습기(100)와;상기 제습기(100) 후단에 설치되고, 상기 제습기(100)에서 토출되는 공기를 흡입하여, 이 공기를 가열하거나 또는 통과시키는 열교환기(200);상기 열교환기(200) 후단에 설치되고, 상기 열교환기(200)를 통과한 공기를 공급받아, 열풍건조시 이 공기를 가열하거나 또는 통과시키는 스팀온풍기(300);상기 스팀온풍기(300) 후단에 설치되고, 상기 스팀온풍기(300)에서 토출되는 공기를 공급받아, 냉풍건조시 이 공기를 냉각하거나 또는 통과시키는 냉각쿨러(400);중공형상으로, 상기 냉각쿨러(400)에서 토출되는 공기를 공급받고, 내부공간으로 공기를 순환시켜 내부에 수용된 농산물을 건조하는 건조실(500);상기 건조실(500)과 상기 제습기(100) 사이에 설치되고, 개폐작동되어 상기 건조실(500) 내의 공기가 냉풍건조시에는 상기 제습기(100)로 이동하는 것을 허용하고, 열풍건조시에는 차단하는 제1댐퍼(600);상기 건조실(500)과 상기 열교환기(200) 사이에 설치되고, 개폐작동되어 상기 건조실(500) 내의 공기가 열풍건조시에는 상기 열교환기(200)로 이동하는 것을 허용하고, 냉풍건조시에는 차단하는 제2댐퍼(700);로 구성되고,상기 건조실(500)은 내측 상부에 상기 냉각쿨러(400)에서 토출된 공기를 상기 건조실(500)의 양측방향으로 고르게 분산되도록 유도하는 유도관(504)과, 내측 벽면에 고정 설치되고, 회전작동되어 상기 건조실(500) 내의 공기를 순환시키는 순환팬(505)을 더 형성하며,상기 유도관(504)은 일단에 상기 냉각쿨러(400)의 공기를 공급받는 유입구(504a)와, 상기 유입구(504a)와 반대되는 타단에 양측으로 서로 대향되게 한 쌍으로 형성되어 상기 유입구(504a)를 통해 유입되는 공기를 상기 건조실(500) 내부 공간으로 토출하는 배출구(504b), 상기 배출구(504b) 내측 각각에 설치되고, 회전작동되어 한 쌍의 상기 배출구(504b)를 통해 상기 건조실(500) 내로 공기가 강제 배출되도록 하는 배기팬(504c)으로 구성되되,일단이 상기 배출구(504b)에 연결되고, 타단이 상기 건조실(500) 내부 공간을 향하도록 설치되며, 그 내측에 다단구조로 적층되되, 일단에서 타단으로 갈수록 그 사이의 틈새가 상대적으로 점차 넓어지는 복수개의 격자판(511)을 형성하여, 이 격자판(511) 사이의 틈새를 통해 공기가 건조실(500) 내로 분산 토출되도록 안내하는 풍향격자판(510)을 더 형성한 것을 특징으로 하는 하이브리드 냉온풍 겸용 건조장치., Ltext: 농업, prediction: 임업
783/1059 Row 783: application_number: 1020190179260, combined_string: invention_title: 인공지능을 이용한 농산물 분류 장치 abstract: 본 발명은 농산물 분류 장치에 관한 것으로, 더욱 상세하게는 인공지능 기술을 이용하여 농산물의 등급을 자동적으로 판별해줄 수 있도록 하여 농업인들이 농산물을 분류하는 단순 반복노동으로부터 탈피할 수 있도록 해주는 인공지능을 이용한 농산물 분류 장치에 관한 것이다.또한, 본 발명에 따르면, 농산물을 이동시키는 컨베이어 벨트; 컨베이어 벨트 위에 있는 농산물을 촬영해서 촬영된 영상을 인공지능 분류기에 전송하는 카메라; 상기 카메라를 지지하는 지지대; 카메라로부터 전송받은 농산물 이미지를 기존 학습 데이터와 비교하여 등급을 판별하는 인공지능 분류기; 인공지능 분류기가 판별한 등급 정보를 수신하여 모터를 제어하여 농산물을 분류하도록 하는 모터 제어기; 모터제어기에 의해 제어되는 한쌍의 모터; 및 상기 한쌍의 모터의 회전에 따라 각각 회전하는 한쌍의 분류판를 포함하는 인공지능을 이용한 농산물 분류 장치가 제공된다.상기와 같은 본 발명에 따르면, 농업인들이 농산물을 분류하는 단순 반복노동으로부터 탈피할 수 있게 하며, 인건비를 절감할 수 있도록 한다. claims: 농산물을 이동시키는 컨베이어 벨트;컨베이어 벨트 위에 있는 농산물을 촬영해서 촬영된 영상을 인공지능 분류기에 전송하는 카메라; 상기 카메라를 지지하는 지지대; 카메라로부터 전송받은 농산물 이미지를 기존 학습 데이터와 비교하여 등급을 판별하는 인공지능 분류기; 인공지능 분류기가 판별한 등급 정보를 수신하여 모터를 제어하여 농산물을 분류하도록 하는 모터 제어기;모터제어기에 의해 제어되는 한쌍의 모터; 및상기 한쌍의 모터의 회전에 따라 각각 회전하는 한쌍의 분류판를 포함하는 인공지능을 이용한 농산물 분류 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

784/1059 Row 784: application_number: 1020190171765, combined_string: invention_title: 스마트 팜 플랫폼 abstract: 상기 또는 다른 목적을 달성하기 위해 본 발명의 일 측면에 따른 스마트 팜 플랫폼은, 식물재배기로부터 수신한 정보 중에서 농산물의 상태 정보 및 상기 식물재배기의 동작 이력 정보에 기초하여 상기 농산물의 추천 판매 가격을 결정하고, 단말기는, 디스플레이에 상기 농산물의 상기 추천 판매 가격을 표시함으로써, 간편하게 농산물의 가격 결정 및 확인이 가능하다. claims: 농산물(agriculturl products)을 생산하는 식물재배기;상기 식물재배기로부터 상기 농산물 및 상기 식물재배기에 대한 정보를 수신하는 비즈니스 플랫폼; 및,상기 비즈니스 플랫폼에 접속하여, 상기 농산물과 관련된 소정 정보를 요청하고, 상기 요청에 대응하여 상기 비즈니스 플랫폼으로부터 수신되는 응답에 기초하는 화면을 디스플레이에 표시하는 단말기;를 포함하고,상기 비즈니스 플랫폼은, 상기 식물재배기로부터 수신한 정보 중에서 상기 농산물의 상태 정보 및 상기 식물재배기의 동작 이력 정보에 기초하여 상기 농산물의 추천 판매 가격을 결정하고,상기 단말기는, 상기 디스플레이에 상기 농산물의 상기 추천 판매 가격을 표시하는 것을 특징으로 하는 스마트 팜 플랫폼., Ltext: 농업, prediction: 농업
785/1059 Row 785: application_number: 1020190168579, combined_string: invention_title: 글로벌 GAP 인증을 위한 농산물 관리 시스템 및 그 관리 방법 abstract: 본 발명은 글로벌 GAP 인증을 위한 농산물 관리 시스템 및 그 관리 방법에 관한 것으로, 글로벌 GAP를 적용한 농산물 관리 서비스를 제공함에 있어서 현장 관리 서버, 품질 관리 서버 및 생장 관리 서버를 구축하고 각 서버를 상호 연계함으로써 효과적이고 지속적인 농산물 품질관리가 가능하고, 또한 스마트 폰, 태블릿 PC와 같은 스마트기기를 사용하여 농산물 재배 현장에서 직접 글로벌 GAP와 관련된 모든 작업내용을 입력 및 관리할 수 있으며, 또한 농가 시설에 센서를 설치하여 USN에 의한 관리가 가능하도록 함으로써, 통제사항에 따른 상황 발생 시 SMS를 통해 관리자에게 통보하거나 혹은 자동으로 상황에 대응 및 조치할 수 있고, 생장 관리 데이터를 자동으로 수집하며 생산성 향상과 에너지 절감 등 농산물 생산 효율을 향상시킬 수 있는 글로벌 GAP 인증을 위한 농산물 관리 시스템 및 그 관리 방법에 관한 것이다. claims: 농가 현장에서 실시간으로 농산물에 대한 기록 정보를 입력받고, 필요한 정보를 확인할 수 있도록 하는 현장 관리 서버;글로벌 GAP에서 요구하는 각종 기록 정보에 대한 관리 및 농가별 정보 서비스를 제공하는 품질 관리 서버; 및USN 데이터 관리 시스템을 통해 농장의 농산물 생산성을 관리하는 생장 관리 서버;를 포함하며, 상기 현장 관리 서버, 품질 관리 서버 및 생장 관리 서버가 서로 인터랙션 하여 글로벌 GAP 인증 규격에 맞는 정보를 기록 및 관리하고 서비스할 수 있는 것을 특징으로 하는 글로벌 GAP 인증을 위한 농산물 관리 시스템.현장 관리 서버 및 생장 관리 서버를 통해 농가 현장 데이터가 입력되는 단계;품질 관리 서버를 통해 상기 입력된 농가 현장 데이터를 저장하고 농가 별로 관리하는 단계;농가 현장 데이터에 대한 글로벌 GAP 관련 분석 데이터를 전송 받아 관리하는 단계; 및 GAP 기준 정보, 농가별 기록 데이터, 분석 데이터, 농가별 통계 정보 또는 이들의 조합 중 적어도 하나 이상을 포함한 정보 서비스를 제공하는 단계;를 포함하며, 상기 현장 관리 서버, 품질 관리 서버 및 생장 관리 서버가 서로 인터랙션 하여 글로벌 GAP 인증 규격에 맞는 정보를 기록 및 관리하고 서비스할 수 있는 것을 특징으로 하는 글로벌 GAP 인증을 위한 농산물 관리 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

786/1059 Row 786: application_number: 1020190164445, combined_string: invention_title: 인공지능 농산물생산판매추천 시스템 및 그 방법 abstract: 본 발명은 인공지능 농산물생산판매추천 시스템 및 그 방법에 관한 것이다.사용자가 인공지능이 학습하여 추론한 농산물의 추천 지역과 예상 판매 단가 등을 알려주는 앱 인터페이스부와 인공지능이 학습할 빅데이터를 저장하는 저장부, 저장된 빅데이터를 학습하여 추론하는 인공지능부를 포함하는 인공지능 농산물생산판매추천 시스템이다. claims: 사용자가 인공지능이 학습하여 추론한 농산물의 추천 지역과 예상 판매 단가 등을 알려주는 앱 인터페이스부와 인공지능이 학습할 빅데이터를 저장하는 저장부, 저장된 빅데이터를 학습하여 추론하는 인공지능부를 포함하는 인공지능 농산물생산판매추천 시스템.경매를 위해 반입되는 농산물의 생산 이력 정보 입력수단, 및 상기 농산물의 영상 정보 입력수단을 제공하는 입력 수단 제공부;입력된 상기 농산물의 생산 이력 정보와 영상 정보를 저장하는 농산물 정보 저장부;미리 설정된 경매 시스템으로부터 상기 농산물에 대한 낙찰 정보를 전달받아 저장하는 유통 이력 정보 저장부;상기 농산물을 낙찰받은 1차 판매자의 오프라인점포 판매관리시스템에 상기 낙찰받은 농산물의 낙찰 정보를 전송하는 판매자 판매관리시스템 연동부;상기 1차 판매자의 온라인점포 운영시스템에 상기 1차 판매자의 온라인 점포에 대응하여 상기 낙찰받은 농산물을 등록하는 온라인점포 운영시스템 연동부; 및소비자 단말로부터 상기 1차 판매자의 온라인점포 운영시스템에 등록된 농산물이 선택되는 경우 상기 선택된 농산물의 생산 이력 정보, 영상 정보, 및 낙찰 정보를 제공하는 농산물 정보 제공부를 포함하는 농산물 거래 시스템으로서,상기 판매자 판매관리시스템 연동부는 상기 1차 판매자의 온라인 점포 운영 시스템을 통해 상기 농산물이 판매되는 경우, 상기 1차 판매자의 오프라인점포 판매관리시스템으로 상기 농산물의 판매 정보를 더 전송하고, 상기 온라인점포 운영시스템 연동부는 상기 1차 판매자의 오프라인점포 판매관리시스템에 상기 농산물의 판매정보가 입력되는 경우, 상기 온라인 점포 운영 시스템에 상기 판매 정보를 더 전송하며,상기 농산물의 생산 이력 정보는 상기 농산물상에 부착된 정보 저장 수단에 저장되고 상기 부착된 정보 저장 수단에 대응하는 정보 획득 장치에 의해 입력된 정보이고,상기 농산물의 영상 정보는 육안 식별 가능한 상기 정보 저장 수단의 영상 정보를 더 포함하는 것을 특징으로하는 인공지능 농산물생산판매추천 시스템.농산물 거래 시스템이, 경매를 위해 반입되는 농산물의 생산 이력 정보 입력수단, 및 상기 농산물의 영상 정보 입력수단을 제공하는 단계;입력된 상기 농산물의 생산 이력 정보와 영상 정보를 저장하는 단계;미리 설정된 경매 시스템으로부터 상기 농산물에 대한 낙찰 정보를 전달받아 저장하는 단계;상기 농산물을 낙찰받은 1차 판매자의 오프라인점포 판매관리시스템에 상기 낙찰받은 농산물의 낙찰 정보를 전송하는 단계;상기 1차 판매자의 온라인 점포 운영 시스템에 상기 1차 판매자의 온라인 점포에 대응하여 상기 낙찰받은 농산물을 등록하는 단계; 및소비자 단말로부터 상기 1차 판매자의 온라인 점포 운영 시스템에 등록된 농산물이 선택되는 경우 상기 선택된 농산물의 생산 이력 정보, 영상 정보, 및 낙찰 정보를 제공하는 단계를 포함하는 농산물 거래 방법으로서,상기 1차 판매자의 온라인 점포 운영 시스템을 통해 상기 농산물이 판매되는 경우, 상기 1차 판매자의 오프라인 점포 판매관리시스템으로 상기 농산물의 판매 정보를 전송하는 단계; 및상기 1차 판매자의 오프라인점포 판매관리시스템에 상기 농산물의 판매 정보가 입력되는 경우, 상기 온라인 점포 운영 시스템에 상기 판매 정보를 전송하는 단계를 더 포함하며,상기 농산물의 생산 이력 정보는 상기 농산물상에 부착된 정보 저장 수단에 저장되고 상기 부착된 정보 저장 수단에 대응하는 정보 획득 장치에 의해 입력된 정보이고,상기 농산물의 영상 정보는 육안 식별 가능한 상기 정보 저장 수단의 영상 정보를 더 포함하는 것을 특징으로 하는 인공지능 농산물생산판매추천방법., Ltext: 농업, prediction: 농업
787/1059 Row 787: application_number: 1020190164192, combined_string: invention_title: 농산물용 신선도 유지 장치 및 농산물 가스 처리 방법 abstract: 본 발명은 농산물용 신선도 유지 장치 및 농산물 가스 처리 방법에 관한 것으로, 구체적으로 농산물의 미생물, 에틸렌 및 이산화탄소의 민감도에 따라 처리되는 가스를 조절하여 신선도를 유지하며, 농산물의 저장기간을 연장하는 농산물용 신선도 유지 장치 및 농산물 가스 처리 방법에 관한 것이다. claims: 농산물을 인입하고 이산화탄소, 이산화염소 및 에틸렌 분해제 중 하나 이상의 가스처리를 위한 농산물용 신선도 유지 장치에 있어서,내부에 농산물을 적재할 수 있는 공간이 형성된 본체부(10);상기 본체부(10)의 내부에 구비되며, 상기 가스 농도를 감지할 수 있는 센서를 구비하는 센싱부(20); 및상기 본체부(10)의 일측에 구비되며, 상기 센싱부(20)에 의해 감지된 상기 가스 농도에 따라 공급되는 가스의 양을 제어하는 컨트롤부(30);와본체부(10)의 일측에 구비되며, 외부에서 공급되는 상기 가스를 상기 본체부의 내부로 공급하기 위한 가스인입부(40)를 포함하는 것을 특징으로 하는 농산물용 신선도 유지 장치.청구항 1 내지 3 중 어느 한 항의 농산물용 신선도 유지 장치의 본체부(10) 내부에 농산물을 구비하는 단계(S10);상기 구비된 농산물의 품목에 따라 사용자가 컨트롤부(30)의 입력모듈에 농산물 품목을 입력하는 단계(S20);상기 정보처리모듈이 상기 입력된 농산물의 품목과 상기 정보저장모듈에 저장된 제1 정보를 비교하여 이산화탄소, 이산화염소, 에틸렌 분해제 및 이들의 조합으로 구성된 군으로부터 선택된 하나의 가스 중 공급될 가스를 결정하는 단계(S30);상기 본체부 내부로 상기 결정된 가스를 공급하는 단계(S40);상기 센싱부(20)에 감지된 농도에 따라 상기 가스공급을 중단하는 단계(S50);를 포함하는농산물 가스 처리 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

788/1059 Row 788: application_number: 1020190161717, combined_string: invention_title: 종자 코팅 조성물, 항공파종용 코팅 종자, 및 코팅 종자를 이용한 항공파종법 abstract: 본 발명의 일 실시에에 따르면, 장축과 단축을 갖는 타원구형의 종자; 상기 종자 상에 제공되는 코팅층을 포함하고, 상기 코팅층은 증량제 및 접착제를 포함하고, 상기 증량제는 탄산칼슘(CaCO3), 제오라이트(Zeolite), 고령토, 석고, 탈크(Talc)로 이루어진 군으로부터 선택되는 적어도 1종 이상의 물질을 포함하고, 상기 종자의 상기 단축 상에서의 상기 코팅층의 두께는 상기 종자의 상기 단축 상에서의 상기 코팅층의 두께보다 큰, 코팅 종자가 제공된다. claims: 장축과 단축을 갖는 타원구형의 종자;상기 종자 상에 제공되는 코팅층을 포함하고,상기 코팅층은 증량제 및 접착제를 포함하고,상기 증량제는 탄산칼슘(CaCO3), 제오라이트(Zeolite), 고령토, 석고, 탈크(Talc)로 이루어진 군으로부터 선택되는 적어도 1종 이상의 물질을 포함하고,상기 종자의 상기 단축 상에서의 상기 코팅층의 두께는 상기 종자의 상기 단축 상에서의 상기 코팅층의 두께보다 큰, 코팅 종자.비행체를 이용하여 경작지로부터 이격된 곳에서 코팅 종자를 살포하는 단계를 포함하고,상기 코팅 종자는 장축과 단축을 갖는 타원구형의 종자;상기 종자 상에 제공되는 코팅층을 포함하고,상기 코팅층은 증량제 및 접착제를 포함하고,상기 증량제는 탄산칼슘(CaCO3), 제오라이트(Zeolite), 고령토, 석고, 탈크(Talc)로 이루어진 군으로부터 선택되는 적어도 1종 이상의 물질을 포함하고,상기 코팅 종자의 무게는 상기 종자의 무게보다 큰, 항공파종 방법.증량제 및 접착제를 포함하고,상기 증량제는 탄산칼슘(CaCO3), 제오라이트(Zeolite), 고령토, 석고, 탈크(Talc)로 이루어진 군으로부터 선택되는 적어도 1종 이상의 물질을 포함하는, 종자 코팅 조성물., Ltext: 농업, prediction: 임업
789/1059 Row 789: application_number: 1020190158861, combined_string: invention_title: 총체곡물 복합 처리장치 abstract: 본 발명의 실시 예에 따른 총체곡물 복합 처리장치는, 총체곡물을 예취하는 예취부와; 예취된 상기 총체곡물을 베일(bale)로 형성하는 베일링부와; 상기 베일을 비닐로 포장하는 래핑부와; 상기 예취부에 의해 예취된 총체곡물을 상기 베일링부로 이송하는 이송부와; 상기 예취부, 상기 베일링부, 상기 래핑부 및 상기 이송부를 지지하고, 주행하는 주행부를 포함한다. claims: 총체곡물을 예취하는 예취부;예취된 상기 총체곡물을 베일(bale)로 형성하는 베일링부;상기 베일을 비닐로 포장하는 래핑부; 및상기 예취부에 의해 예취된 총체곡물을 상기 베일링부로 이송하는 이송부를 포함하되,상기 베일링부는 상기 이송부에 의해 이송되는 총체곡물이 내부로 유입되는 유입구를 포함하고, 상기 이송부는 상기 예취부와 연결되는 제 1 이송 유닛과 상기 제 1 이송 유닛 및 상기 유입구에 연결되는 제 2 이송 유닛을 포함하는 총체곡물 복합 처리 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

790/1059 Row 790: application_number: 1020190156233, combined_string: invention_title: 식용곤충 분말, 질소고정세균, 황토 및 전분을 포함하는 종자 코팅제 및 상기 종자 코팅제로 코팅된 종자 abstract: 본 발명은 식용곤충 분말, 질소고정세균, 황토 및 전분을 포함하는 종자 코팅제 및 상기 종자 코팅제로 코팅된 종자에 관한 것으로, 본 발명의 식용곤충, 질소고정세균, 황토 및 전분을 포함하는 종자 코팅제를 이용하게 되면 종자 발아율 및 식물의 초장 길이가 현저하게 증가되고 파종 시 종자의 수분유지 및 유실방지 효과가 있을 뿐만 아니라, 종자 발아부터 유묘기까지 별도로 비료를 공급할 필요가 없으며, 화학 비료를 사용하지 않아 친환경농법으로 매우 유용하게 이용될 수 있다. claims: 식용곤충 분말, 질소고정세균 분말, 황토 및 전분을 포함하는 종자 코팅제. 제1항 내지 제5항 중 어느 한 항의 종자 코팅제로 코팅된 종자., Ltext: 농업, prediction: 농업
791/1059 Row 791: application_number: 1020190154966, combined_string: invention_title: 곡물 건조 장치 및 곡물의 비린취 제거 방법 abstract: 본 발명은 밀폐 구조를 구비하며, 곡물을 수용하는 바디; 상기 바디 내부에 구비되어, 상기 바디 내에 수용된 곡물을 슬라이딩시키는 스크류 블레이드; 상기 바디를 가열하는 가열 수단; 및 상기 바디에 연결되어, 상기 바디 내부에 건열을 주입하는 폭기 수단을 포함하는 곡물 건조 장치, 및 이를 이용한 곡물의 비린취 제거 방법에 관한 것이다. claims: 밀폐 구조를 구비하며, 곡물을 수용하는 바디;상기 바디 내부에 구비되어, 상기 바디 내에 수용된 곡물을 슬라이딩시키는 스크류 블레이드;상기 바디를 가열하는 가열 수단; 및상기 바디에 연결되어, 상기 바디 내부에 건열을 주입하는 폭기 수단을 포함하는 곡물 건조 장치.곡물을 바디에 투입하는 곡물 투입 단계;상기 바디에 투입된 곡물을 스크류 블레이드를 이용하여 슬라이딩하는 슬라이딩 단계;상기 곡물에 광선을 조사하는 광선 조사 단계;상기 바디를 밀폐시켜 상기 바디 내부의 공기가 곡물들의 사이를 순환하도록 하는 열 순환 단계; 및상기 바디 내부에 건열을 주입하는 폭기 단계를 포함하는 곡물의 비린취 제거 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

792/1059 Row 792: application_number: 2020190004804, combined_string: invention_title: 슬라이스 형태로 절단된 농산물의 건조틀 abstract: 본 고안은 슬라이스 형태로 절단된 농산물이 서로 겹치지 않도록 수용하여 건조시키기 위한 슬라이스 형태로 절단된 농산물의 건조틀에 관한 것이다. 본 고안의 실시예에 따른 슬라이스 형태로 절단된 농산물의 건조틀은 내부에 농산물을 수용하는 수용공간이 형성되며 복수 개의 통기공이 관통형성된 외통, 상기 외통의 일부를 절개하여 상기 수용공간으로 농산물을 반입하는 반출입구, 상기 반출입구를 개폐하며 복수 개의 통기공이 관통형성된 개폐커버, 상기 수용공간을 복수 개로 분할하며, 분할된 각 수용공간마다 슬라이스 형태로 절단된 농산물을 세워 삽입하도록 상기 수용공간에 복수 개가 서로 이격되어 설치되는 분할격판, 및 상기 외통을 줄에 걸어 거치하도록 상기 외통에 설치되는 걸고리를 포함한다. 따라서, 건조공간을 최소화하고, 통기성을 확보할 수 있으며, 대량의 농산물을 용이하게 건조시킬 수 있는 이점이 있다. claims: 내부에 농산물을 수용하는 수용공간이 형성되며 복수 개의 통기공이 형성된 외통,상기 외통의 일부를 절개하여 상기 수용공간으로 농산물을 반입하는 반출입구,상기 반출입구를 개폐하며 복수 개의 통기공이 형성된 개폐커버,상기 수용공간을 복수 개로 분할하며, 분할된 각 수용공간마다 슬라이스 형태로 절단된 농산물을 세워 삽입하도록 상기 수용공간에 복수 개가 서로 이격되어 설치되는 분할격판, 및상기 외통을 줄에 걸어 거치하도록 상기 외통에 설치되는 걸고리를 포함하는 것을 슬라이스 형태로 절단된 농산물의 건조틀., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

793/1059 Row 793: application_number: 1020190154775, combined_string: invention_title: 전자기파를 이용한 태양초 고추건조기 abstract: 본 발명은 전자기파를 이용하여 고추의 색상을 보정할 수 있으며, 꼭지를 자동으로 분리시킬 수 있는 전자기파를 이용한 태양초 고추건조기에 관한 것이다. 본 발명의 실시예에 따른 전자기파를 이용한 태양초 고추건조기는 고추가 반입되는 건조실이 형성된 외장케이스, 상기 건조실을 개폐하도록 상기 외장케이스에 설치되는 개폐도어, 상기 개폐도어를 중심으로 상기 외장케이스의 양측면에 각각 설치되어 고추를 건조시키기 위한 전자기파를 상기 건조실의 내부로 방출하는 마그네트론, 상기 외장케이스의 하부에 설치되어 상기 건조실로 공기를 공급하는 송풍기, 상기 외장케이스의 상부에 설치되어 상기 송풍기에 의해 상기 건조실의 내부로 공급된 공기를 외부로 방출하는 배기구, 상기 건조실의 내부로 반입된 고추의 온도를 측정하는 온도측정기, 상기 건조실에 반입된 고추의 무게를 측정하고 상기 고추의 건조된 무게를 측정하는 저울부, 및 상기 온도측정기에서 측정되는 온도와 상기 저울부에서 측정되는 고추의 무게를 기초로 상기 마그네트론과 상기 송풍기를 제어하는 건조제어컨트롤러를 포함하고, 상기 건조제어컨트롤러는 상기 저울부에서 측정되는 고추의 변화된 무게를 기초로 상기 고추의 함수율을 측정하고, 상기 고추의 함수율이 50% 이상 55% 이하의 범위에 속하면, 상기 송풍기의 작동을 멈추고 상기 마그네트론를 작동시켜 상기 고추의 온도를 70℃ 이상 75℃ 이하의 범위에 이르도록 미리 설정된 시간동안 상기 고추를 급속가열하여 상기 고추의 갈변된 색상을 탈색하는 색상보정단계, 및 상기 고추의 함수율이 42% 이상 48% 이하의 범위에 속하면, 상기 송풍기의 작동을 멈추고 상기 마그네트론을 작동시켜 상기 고추의 온도를 75℃ 이상 80℃ 이하의 온도 범위에 이르도록 미리 설정된 시간동안 상기 고추를 급속가열하여 고추 내부의 수분을 급속히 팽창시키는 형태로 팽창력에 의해 상기 고추에서 고추꼭지를 분리하는 꼭지분리단계를 포함한다. 따라서, 마치 태양초와 같은 우수한 색상과 품질의 건 고추를 생산할 수 있다. claims: 고추가 반입되는 건조실이 형성된 외장케이스,상기 건조실을 개폐하도록 상기 외장케이스에 설치되는 개폐도어,상기 개폐도어를 중심으로 상기 외장케이스의 양측면에 각각 설치되어 고추를 건조시키기 위한 전자기파를 상기 건조실의 내부로 방출하는 마그네트론,상기 외장케이스의 하부에 설치되어 상기 건조실로 공기를 공급하는 송풍기,상기 외장케이스의 상부에 설치되어 상기 송풍기에 의해 상기 건조실의 내부로 공급된 공기를 외부로 방출하는 배기구,상기 건조실의 내부로 반입된 고추의 온도를 측정하는 온도측정기,상기 건조실에 반입된 고추의 무게를 측정하고 상기 고추의 건조된 무게를 측정하는 저울부,상기 온도측정기에서 측정되는 온도와 상기 저울부에서 측정되는 고추의 무게를 기초로 상기 마그네트론과 상기 송풍기를 제어하는 건조제어컨트롤러를 포함하고,상기 건조제어컨트롤러는상기 저울부에서 측정되는 고추의 변화된 무게를 기초로 상기 고추의 함수율을 측정하고, 상기 고추의 함수율이 50% 이상 55% 이하의 범위에 속하면, 상기 송풍기의 작동을 멈추고 상기 마그네트론를 작동시켜 상기 고추의 온도를 70℃ 이상 75℃ 이하의 범위에 이르도록 미리 설정된 시간동안 상기 고추를 급속가열하여 상기 고추의 갈변된 색상을 탈색하는 색상보정단계, 및상기 고추의 함수율이 42% 이상 48% 이하의 범위에 속하면, 상기 송풍기의 작동을 멈추고 상기 마그네트론을 작동시켜 상기 고추의 온도를 75℃ 이상 80℃ 이하의 온도 범위에 이르도록 미리 설정된 시간동안 상기 고추를 급속가열하여 고추 내부의 수분을 급속히 팽창시키는 형태로 팽창력에 의해 상기 고추에서 고추꼭지를 분리하는 꼭지분리단계를 포함하는 것을 특징으로 하는 전자기파를 이용한 태양초 고추건조기., Ltext: 농업, prediction: 임업
794/1059 Row 794: application_number: 1020190145847, combined_string: invention_title: 식물공장 설립과 농산물 판매를 위한 중개 서비스 장치 및 그 방법 abstract: 본 발명은 식물공장 설립과 농산물 판매를 위한 중개 서비스 장치 및 그 방법이 개시된다. 본 발명의 식물공장 설립과 농산물 판매를 위한 중개 서비스 장치는, 식물공장의 설립에 필요한 부지, 설비, 기자재 및 판매를 위한 농산물 중 적어도 하나를 등록하고, 식물공장의 설립을 위한 부지, 설비, 기자재 및 구매하기 위한 농산물 중 적어도 하나를 검색하여 구매하고 결제하는 사용자 단말기; 식물공장 설립 및 농산물 판매를 위한 정보를 저장하고, 주문정보와 회원정보를 저장하는 서비스 DB; 및 사용자 단말기를 통해 식물공장 설립과 농산물 판매를 위한 정보가 등록되면 서비스 DB에 저장하고, 사용자 단말기로부터 검색요청에 따라 서비스 DB에 저장된 정보를 검색하여 제공하며, 주문 결제가 요청되면 결제서버를 통해 결제를 수행한 후 주문 결제정보를 제공자에게 전달하여 용역 및 재화를 제공할 수 있도록 중개하는 중개서버;를 포함하는 것을 특징으로 한다. claims: 식물공장의 설립에 필요한 부지, 설비, 기자재 및 판매를 위한 농산물 중 적어도 하나를 등록하고, 상기 식물공장의 설립을 위한 부지, 설비, 기자재 및 구매하기 위한 농산물 중 적어도 하나를 검색하여 구매하고 결제하는 사용자 단말기; 상기 식물공장 설립 및 농산물 판매를 위한 정보를 저장하고, 주문정보와 회원정보를 저장하는 서비스 DB; 및 상기 사용자 단말기를 통해 상기 식물공장 설립과 농산물 판매를 위한 정보가 등록되면 상기 서비스 DB에 저장하고, 상기 사용자 단말기로부터 검색요청에 따라 상기 서비스 DB에 저장된 정보를 검색하여 제공하며, 주문 결제가 요청되면 결제서버를 통해 결제를 수행한 후 주문 결제정보를 제공자에게 전달하여 용역 및 재화를 제공할 수 있도록 중개하는 중개서버;를 포함하는 것을 특징으로 하는 식물공장 설립과 농산물 판매를 위한 중개 서비스 장치. 제 1항에 있어서, 상기 중개서버는, 상기 사용자 단말기를 통해 입력되는 상기 식물공장을 설립할 수 있는 부지의 임대 및 매매 정보를 상기 서비스 DB에 등록하고, 상기 사용자 단말기로부터 입력된 부지의 임대 및 매매를 위한 검색조건에 따라 매칭되는 정보를 검색하여 제공하는 부지 중개부; 상기 사용자 단말기를 통해 입력되는 상기 식물공장 설립과 운영을 위한 설비 및 기자재 정보를 상기 서비스 DB에 등록하고, 상기 사용자 단말기로부터 입력된 설비 및 기자재의 구매조건에 따라 매칭되는 정보를 검색하여 제공하는 설비 중개부; 상기 사용자 단말기를 통해 입력되는 상기 식물공장 설립과 운영을 위한 용역 정보를 상기 서비스 DB에 등록하고, 상기 사용자 단말기로부터 입력된 용역조건에 따라 매칭되는 정보를 검색하여 제공하는 용역 중개부; 상기 사용자 단말기를 통해 입력되는 상기 식물공장에서 생산된 농산물의 판매를 위해 상기 서비스 DB에 등록하고, 등록된 농산물을 제공하여 농산물을 구매할 수 있도록 중개하는 판매 중개부; 상기 사용자 단말기로부터 판매와 구매를 위한 주문정보를 입력받아 상기 서비스 DB에 등록하고, 상기 결제서버를 통해 결제를 수행하는 주문 결제부; 및 상기 사용자 단말기로부터 입력된 중개서비스를 이용하고자 하는 회원정보를 상기 서비스 DB에 등록하여 로그인 및 주문 결제를 관리하는 회원 관리부;를 포함하는 것을 특징으로 한다. 중개서버가 사용자 단말기로부터 입력되는 식물공장의 설립에 필요한 부지, 설비, 기자재 및 판매를 위한 농산물 중 적어도 하나를 입력받아 서비스 DB에 등록하는 단계; 상기 중개서버가 상기 사용자 단말기로부터 입력되는 상기 식물공장의 설립을 위한 부지, 설비, 기자재 및 구매하기 위한 농산물 중 적어도 하나를 상기 서비스 DB로부터 검색하여 제공하는 단계; 상기 중개서버가 검색 결과를 기반으로 상기 사용자 단말기로부터 주문정보가 입력되는 경우 상기 서비스 DB에 등록하고 결제서버를 통해 결제를 수행하는 단계; 및 상기 중개서버가 주문정보에 대한 결제를 수행하여 결제가 완료되면 주문 결제정보를 제공자에게 전달하는 단계;를 포함하는 것을 특징으로 하는 식물공장 설립과 농산물 판매를 위한 중개 서비스 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

795/1059 Row 795: application_number: 1020190139975, combined_string: invention_title: 플라즈마 가감압 종자 살균 장치 abstract: 플라즈마 방전을 이용하여 종자를 살균처리 하되 살균이 이루어지는 챔버 내부가 가압과 감압 상태로 제어되며 살균 효과를 극대화할 수 있는 플라즈마 종자 살균 장치가 개시된다. 본 발명에 의한 플라즈마 종자 살균 장치는, 내부에서 플라즈마가 발생되는 플라즈마 챔버; 상기 플라즈마 챔버에 연결되어 플라즈마가 공급되고, 내부에는 종자들이 내장되어 있으며 내부의 기압이 대기압 상태와 저진공 상태를 주기적으로 반복하게 되면서 종자가 살균되는 종자 살균 챔버; 상기 종자 살균 챔버에 연결되어 내부에 진공압을 제공하는 진공 펌프; 상기 플라즈마 챔버와 상기 종자 살균 챔버 사이에 설치되어 상기 종자 살균 챔버로 공급되는 플라즈마의 이동을 제어하는 플라즈마 공급 제어 밸브;를 포함한다. claims: 플라즈마가 발생되는 플라즈마 챔버;상기 플라즈마 챔버에 연결되어 플라즈마가 공급되고, 내부에는 종자들이 내장되어 있으며 내부가 가압 및 감압 상태로 제어되며 종자가 살균되는 종자 살균 챔버;상기 종자 살균 챔버에 연결되어 내부에 진공압을 제공하는 진공 펌프;상기 플라즈마 챔버와 상기 종자 살균 챔버 사이에 설치되어 상기 종자 살균 챔버로 공급되는 플라즈마의 이동을 제어하는 플라즈마 공급 제어 밸브;를 포함하는 플라즈마 종자 살균 장치., Ltext: 농업, prediction: 임업
796/1059 Row 796: application_number: 1020190140179, combined_string: invention_title: 중적외선과 히트펌프를 이용한 농산물 복합 건조장치 abstract: 본 발명에 따른 농산물 복합 건조장치는, 건조실에 배치되어 중적외선을 조사하는 중적외선 조사부, 건조실의 다습한 공기로부터 습기를 제거하여 일정 온도의 건조 공기가 되도록 처리하는 히트펌프부, 건조실의 내부에 배치되는 하나 이상의 덕트, 히트펌프부에서 처리된 일정 온도의 건조 공기를 덕트로 공급하는 하나 이상의 송풍팬, 및 중적외선 조사부와 히트펌프부를 제어하는 제어부를 포함하여 이루어진다. 중적외선과 히트펌프를 복합적으로 이용하여 농산물을 건조함에 따라, 아로니아와 미인고추 등 내외부를 균일하게 건조하기 어려운 농산물을 효율적으로 건조할 수 있다. 자연풍에 가까운 약 35도의 저온에서도 충분히 건조할 수 있어서, 원재료가 지닌 각종 효능이 건조 후에도 지속됨과 아울러 변질 또는 부패가 방지되어 저장성을 향상시킬 수 있다. 또한, 밀폐된 건조실의 내부 공기를 순환시켜 폐열을 재사용함으로써, 건조 효율 및 에너지 효율을 높일 수 있다. claims: 건조실의 농산물을 건조시키는 장치로서,상기 건조실에 배치되어 중적외선을 조사하는 중적외선 조사부;상기 건조실의 다습한 공기로부터 습기를 제거하여 일정 온도의 건조 공기가 되도록 처리하는 히트펌프부;상기 히트펌프부에서 처리된 일정 온도의 건조 공기를 상기 건조실의 내부로 공급하기 위하여, 상기 건조실의 천장 가운데 부분을 따라 서로 나란하게 상기 건조실의 중심 부근까지 연장되고, 상기 건조실의 바닥을 향해 건조 공기를 배출하는 한 쌍의 덕트;상기 건조실의 내부에서 습기를 머금은 다습한 공기를 상기 히트펌프부 측으로 보내기 위하여, 상기 건조실의 천장 양쪽 가장자리를 따라 서로 나란하게 연장되는 한 쌍의 덕트;상기 히트펌프부에서 처리된 일정 온도의 건조 공기가 상기 건조 공기를 배출하는 한 쌍의 덕트를 통해 흐르도록 하는 송풍팬과, 상기 건조실의 내부에서 습기를 머금은 다습한 공기가 상기 서로 나란하게 연장되는 한 쌍의 덕트를 통해 흐르도록 하는 송풍팬을 포함하는 복수의 송풍팬; 및상기 중적외선 조사부와 히트펌프부를 제어하는 제어부를 포함하고,상기 중적외선 조사부는 탄소 필라멘트로 이루어진 복수 개의 카본 램프를 포함하는, 중적외선과 히트펌프를 이용한 농산물 복합 건조장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

797/1059 Row 797: application_number: 1020190138331, combined_string: invention_title: 파종장치 abstract: 본 발명은 파종장치에 관한 것으로서, 베이스프레임 상에 고정 결합되는 호퍼형 몸체의 종자배출부 내에 위치하여 경사지게 안착 배치 및 회전 가능하게 지지 결합되는 종자배출판; 상기 종자배출판에 연결되어 시계방향 또는 반시계방향의 회전력을 제공하기 위한 회전유도수단; 상기 종자배출판의 상측에 위치하여 종자배출판으로 파종용 종자를 공급하여주는 호퍼형 구조의 종자공급통; 상기 종자배출부 내 상부 일측에 고정 결합된 고정브래킷 상에 일단부가 고정된 채로 종자배출판을 향해 볼록형 곡면 구조를 갖는 타단부가 종자배출판 측 어느 한 부분의 종자배출홀 상에 위치하도록 배치되어 종자배출판을 따라 회전 이송되는 종자를 누름 가압함에 의해 종자배출판의 종자배출홀 상에서 종자를 내보내는 역할을 하는 종자누름부재;를 포함하는 것을 특징으로 한다.본 발명에 따르면, 콩이나 팥 또는 서리태 등의 농작물 파종시 사용되는 종자의 크기 및 형상에 따라 종자배출판을 다양한 규격으로 제작하여 사용할 수 있고, 이를 통해 종자공급통으로부터 공급되는 종자에 대해 종자배출판 측 종자배출홀을 쉽게 통과하여 용이하게 파종 처리할 수 있으며 종자배출판에서의 종자 배출을 종래에 비해 보다 원활하게 수행할 수 있어 파종효율을 높일 수 있다. claims: 베이스프레임 상에 고정 결합되는 호퍼형 몸체의 종자배출부 내에 위치하여 경사지게 안착 배치 및 회전 가능하게 지지 결합되는 종자배출판;상기 종자배출판에 연결되어 시계방향 또는 반시계방향의 회전력을 제공하기 위한 회전유도수단;상기 종자배출판의 상측에 위치하여 종자배출판으로 파종용 종자를 공급하여주는 호퍼형 구조의 종자공급통;상기 종자배출부 내 상부 일측에 고정 결합된 고정브래킷 상에 일단부가 고정된 채로 종자배출판을 향해 볼록형 곡면 구조를 갖는 타단부가 종자배출판 측 어느 한 부분의 종자배출홀 상에 위치하도록 배치되어 종자배출판을 따라 회전 이송되는 종자를 누름 가압함에 의해 종자배출판의 종자배출홀 상에서 종자를 내보내는 역할을 하는 종자누름부재; 를 포함하되, 상기 종자누름부재는, 상기 종자배출판 측 종자배출홀에 대해 2열 배치구조로 형성하는 경우, 종자배출부에 고정 결합된 고정브래킷 상에 일단이 고정 결합된 채로 한쌍이 경사지게 분배되는 직선부 및 그 직선부 말단에 형성되어 종자배출홀에 위치하면서 종자를 누름 가압하는 호형부를 포함하는 누름부; 및 직선부가 관통되도록 2개의 간격홀을 갖는 간격유지구;를 포함함으로써, 간격유지구가 직선부 상에서 슬라이딩을 통해 간격이 조절되어 호형부가 종자배출홀 측 2열 배치구조의 간격에 대응하여 종자배출홀 상에 안착됨에 의해 종자가 누름 가압되어 종자배출판을 통과하면서 배출되는 것을 특징으로 하는 파종장치., Ltext: 농업, prediction: 임업
798/1059 Row 798: application_number: 1020190137886, combined_string: invention_title: 농산물 살균 처리 플라즈마 시스템 및 방법 abstract: 농산물 살균 처리 플라즈마 시스템에 관하여 개시한다. 본 발명은, 농산물이 통과하는 임의의 한정된 공간을 형성하는 챔버; 상기 챔버의 베드를 구성하고 농산물이 챔버 안을 경유하도록 챔버의 내부를 가로지르도록 배치된 메인 컨베이어 벨트; 플라즈마 토치의 노즐 방향이 상기 메인 컨베이어 벨트의 상부에서 위치하면서 대면하는 방향을 향하도록 상기 챔버 내부 적소에 배치되는 플라즈마 발생기; 및 상기 챔버내에 생성되는 기체의 순환을 유도하기 위해 상기 챔버의 주변부에 배치된 배기후드;를 포함하여 구성될 수 있다. claims: 농산물이 통과하는 임의의 한정된 공간을 형성하는 챔버;상기 챔버의 베드를 구성하고 농산물이 챔버 안을 경유하도록 챔버의 내부를 가로지르도록 배치된 메인 컨베이어 벨트;플라즈마 토치의 노즐 방향이 상기 메인 컨베이어 벨트의 상부에서 위치하면서 대면하는 방향을 향하도록 상기 챔버 내부 적소에 배치되는 플라즈마 발생기; 및상기 챔버내에 생성되는 기체의 순환을 유도하기 위해 상기 챔버의 주변부에 배치된 배기후드;를 포함하는 농산물 살균 처리 플라즈마 시스템.농산물 선과장의 선과 라인 말단에 농산물 살균 처리 플라즈마 시스템을 배치하고, 선과된 농산물의 박스포장 뚜껑을 닫기 전 단계에서 상기 농산물 살균 처리 플라즈마 시스템을 구성하는 챔버의 컨베이어 벨트에 농산물이 담긴 박스포장 뚜껑이 열린 상태로 탑재하여 챔버 내에서 플라즈마 활성종으로 농산물을 살균 처리하는 단계;를 포함하는 농산물 살균 처리 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

799/1059 Row 799: application_number: 1020190135275, combined_string: invention_title: 농산물 생산 유통 관리 서버 및 이를 이용하는 농산물 생산 유통 관제 시스템 abstract: 본 발명의 일 실시예에 따른 농산물 생산 유통 관리 서버는, 재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어부; 재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장부; 저장DB로부터 수신한 재배지에서 재배되는 농산물 정보를 기초로 잔류 농약을 관리하는 잔류 농약 관리부; 및 출하된 농산물의 유통 환경을 관리하는 유통 환경 관리부를 포함하고, 잔류 농약 관리부는, 농약 잔류기준을 제공하는 농약 잔류기준 제공부와, 농약의 살포량을 저장하는 농약 살포량 저장부와, 농약의 잔류량에 따른 안전성을 판단하는 안전 적합도 판단부를 포함한다. claims: 재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어부;재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장부;저장DB로부터 수신한 상기 재배지에서 재배되는 농산물 정보를 기초로 잔류 농약을 관리하는 잔류 농약 관리부; 및출하된 농산물의 유통 환경을 관리하는 유통 환경 관리부를 포함하고,상기 잔류 농약 관리부는, 농약 잔류기준을 제공하는 농약 잔류기준 제공부와, 상기 농약의 살포량을 저장하는 농약 살포량 저장부와, 상기 농약의 잔류량에 따른 안전성을 판단하는 안전 적합도 판단부를 포함하는 농산물 생산 유통 관리 서버.농산물 유통 관리 서버;재배자 단말;구매자 단말; 및유통 차량을 포함하고,상기 농산물 유통 관리 서버는,재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어부;재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장부;저장DB로부터 수신한 상기 재배지에서 재배되는 농산물 정보를 기초로 잔류 농약을 관리하는 잔류 농약 관리부; 및출하된 농산물의 유통 환경을 관리하는 유통 환경 관리부를 포함하고,상기 잔류 농약 관리부는, 농약 잔류기준을 제공하는 농약 잔류기준 제공부와, 상기 농약의 살포량을 저장하는 농약 살포량 저장부와, 상기 농약의 잔류량에 따른 안전성을 판단하는 안전 적합도 판단부를 포함하는 농산물 생산 유통 관제 시스템.재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어 단계;재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장 단계;저장DB로부터 수신한 상기 재배지에서 재배되는 농산물 정보를 기초로 잔류 농약을 관리하는 잔류 농약 관리 단계; 및출하된 농산물의 유통 환경을 관리하는 유통 환경 관리 단계를 포함하고,상기 잔류 농약 관리 단계는, 농약 잔류기준을 제공하는 농약 잔류기준 제공부와, 상기 농약의 살포량을 저장하는 농약 살포량 저장부와, 상기 농약의 잔류량에 따른 안전성을 판단하는 안전 적합도 판단 단계를 포함하는 농산물 생산 유통 관제 방법.농산물 생산 유통 관제 방법을 실행하기 위한 프로그램을 포함하는 컴퓨터 판독가능 기록매체에 있어서,상기 농산물 생산 유통 관제 방법은, 재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어 단계; 재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장 단계; 상기 재배지에서 재배되는 농산물의 잔류 농약을 관리하는 잔류 농약 관리 단계; 및 출하된 상기 농산물의 유통 환경을 관리하는 유통 환경 관리 단계를 포함하는 컴퓨터 판독가능 기록매체., Ltext: 농업, prediction: 농업
800/1059 Row 800: application_number: 1020190127180, combined_string: invention_title: 표고버섯의 비타민 D2 함량 증강 방법 abstract: 본 발명은 표고버섯을 플라즈마로 전처리한 다음, 자외선을 조사함으로써, 표고버섯의 비타민 D2 함량이 현저히 증가된 처리 방법에 관한 것이다. claims: 챔버 내에 표고버섯 자실체를 넣고 플라즈마를 주입하는 플라즈마 전처리 단계와;상기 플라즈마 전처리된 표고버섯 자실체에 자외선을 조사하는 자외선 처리 단계;를 포함하며,상기 챔버 내의 플라즈마 농도는 0.1~1.0mg/L이고, 플라즈마 전처리 시간은 5~7분이며,상기 자외선은 250~320nm의 파장이고, 상기 자외선 처리 시간은 5~10분인 것을 특징으로 하는 표고버섯의 비타민 D2 함량 증강 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

801/1059 Row 801: application_number: 1020190124163, combined_string: invention_title: 농산물 신선도유지장치 abstract: 본 발명은 농산물 저장시설내 설치하여 작동시키면 플라즈마와 OH 라디컬으로 살균효과를 높혀서 대기중에 방출시킴으로 농산물의 노화 및 부패균으로부터 구근류, 과일류 및 엽채류와 같은 농산물을 안전하게 지켜주도록 팬작동, OH 라디컬 발생과 플라즈마발생을 이용한 농산물 신선도유지장치에 관한 것이다. 이를 위한 본 발명은 컨트롤박스(10)에는 AC 220 V 60Hz가 인가되는 전원스위치(70)와, 인터페이스 보드(16)를 통한 AC 팬(20), 플라즈마 발생기(30), OH 라디컬 발생기(40), LED 표시기(50) 및 옵션으로써의 통신포트(60)가 각각 설치되고; 상기 컨트롤박스(10)는 원칩마이컴(12)을 통해 전면디스플레이(14)와 인터페이스 보드(16)가 각기 연결되는 한편, 상기 전면디스플레이(14)에는 12 V 스위칭모드 파워서플라이(18)이 연결되도록 구성되어; 플라즈마의 1 차신선도 유지에 OH 라디컬의 공간 살균으로 상기 AC 팬(20), 플라즈마 발생기(30), OH 라디컬발생기(40)가 동작된 것을 특징으로 한다. claims: 컨트롤박스(10)에는 AC 220 V 60Hz가 인가되는 전원스위치(70)와, 인터페이스 보드(16)를 통한 AC 팬(20), 플라즈마 발생기(30), OH 라디컬발생기(40), LED 표시기(50) 및 별도의 통신포트(60)가 각각 설치되고; 상기 컨트롤박스(10)는 원칩마이컴(12)을 통해 전면디스플레이(14)와 인터페이스 보드(16)가 각기 연결되는 한편, 상기 전면디스플레이(14)에는 12 V 스위칭모드 파워서플라이(18)이 연결되도록 구성되어; 플라즈마의 1 차 신선도 유지에 OH 라디컬의 공간 살균으로 상기 AC 팬(20), 플라즈마 발생기(30), OH 라디컬 발생기(40)가 동작된 것을 특징으로 하는 농산물 신선도유지장치., Ltext: 농업, prediction: 농업
802/1059 Row 802: application_number: 1020190115066, combined_string: invention_title: 종자 자동공급용 수동 파종기 abstract: 본 발명은 종자 자동공급용 수동 파종기에 관한 것으로, 특히, 파이프 형태로 된 지주관의 소정위치에 종자공급장치를 구비함과 동시에 상기 지주관 자체가 종자통으로 사용되게 하고, 한 쌍의 파종호미를 작동시키는 레버 및 작동봉이 상기 종자공급장치를 연동시킬 수 있게 하여 경운된 밭두둑에 파종호미를 찌른 상태에서 손잡이를 잡고 손아귀의 힘으로 레버를 함께 당기면 작동봉 또는 견인철선이 당겨지면서 종자공급장치와 파종호미를 동시에 연동시킴으로서, 지면에 형성된 파종홈 안에 작물의 종자가 자동 투입되게 하며, 더불어 상기 파종호미가 지면에 들어갈 때 스토퍼에 의해 균일한 깊이의 파종홈을 얻을 수 있게 함으로써 수동식 파종기이지만 균일한 깊이의 파종홈 형성과 함께 종자파종도 동시에 이루어지게 하려는데 그 특징이 있다.이와 같은 본 발명은 파종홈의 형성과 동시에 종자투입이 동시에 이루어지게 되는 것이며, 이에 따라 수동식 파종기이지만 종자투입은 자동으로 이루어질 수 있게 되어 파종효율을 극대화시킬 수 있고, 또, 지극히 구성이 간단하여 저렴하게 제조공급할 수 있어 농가의 부담을 경감시켜줄 수 있음은 물론 신속한 파종작업과 더불어 인력을 절감할 수 있는 등의 많은 효과가 따르는 것이다. claims: 상단에 뚜껑(11)과 손잡이(12)가 구비된 파이프 형태로 된 원통형의 종자통(1)과, 상기 종자통(1)의 하부에 장착되며 90° ~ 180° 로 회전하면서 종자통(1) 내부의 종자를 일정량, 또는 소정 개수만 파종호미(3)로 회전 이송시켜 낙하시키는 종자공급장치(2)와, 상기 종자공급장치(2)가 종자를 파종호미(3) 안으로 떨어뜨릴 때 통로로 작용하는 지지관(4)과, 상기 지지관(4)의 하단에 장착되어 일 측 또는 양 측으로 벌릴 수 있게 한 한 쌍의 파종호미(3)와, 상기 지지관(4)에 장착되어 나비볼트(7)로 높이를 조절할 수 있게 함으로써 손쉽게 파종홈의 깊이를 조절할 수 있게 한 스토퍼(6)와, 상기 파종호미(3)를 지면에 박은 상태에서 강제로 벌려 파종홈을 형성하면서 동시에 종자공급장치(2)도 회전시켜 종자를 파종홈에 투입시킬 수 있게 하는 스프링(52)이 장착된 견인부(5) 및 레버(51)로 이루어짐을 특징으로 하는 종자 자동공급용 수동파종기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

803/1059 Row 803: application_number: 1020190113156, combined_string: invention_title: 전자기파를 이용한 건조장치 abstract: 본 발명은 전자기파를 이용한 건조장치에 관한 것으로, 지면에 지지되는 작업대; 상기 작업대의 일측에 형성되며, 건조대상물이 안착되는 트레이와, 상기 트레이를 상승 또는 하강시키는 제1승강부가 형성되며 건조물을 이동시켜 건조부으로 공급하는 인입이송부; 상기 작업대에 형성되며, 상기 인입이송부가 이동하여 안착되며 상기 건조대상물을 전달받는 도킹부와, 도킹부를 상승 또는 하강시키는 제2승강부가 형성되며 상부에 건조로가 구비된 건조부; 상기 작업대의 타측에 형성되며, 상기 건조로에서 건조를 마친 건조물이 인계되어 안착되는 제2트레이와, 상기 제2트레이를 상승 또는 하강시키는 제3승강부가 형성되어 건조물을 배출하는 인출이송부;를 포함하여 구성된다. 이에 따르면, 액체나 수분을 함유하고 있는 각종 물질을 단시간 내에 대량 건조시킬 수 있는 건조로에 건조대상물을 투입하는 투입수단과, 건조를 마친 건조물을 인출하는 인출수단을 각기 구비하고, 각 투입수단과 인출수단은 높이 조절과 수평 이동이 자동으로 이루어질 수 있어 작업 능률이 향상될 수 있는 효과가 있다. claims: 지면에 지지되는 작업대;상기 작업대의 일측에 형성되며, 건조대상물이 안착되는 트레이와, 상기 트레이를 상승 또는 하강시키는 제1승강부가 형성되며 건조물을 이동시켜 건조부으로 공급하는 인입이송부; 상기 작업대에 형성되며, 상기 인입이송부가 이동하여 안착되며 상기 건조대상물을 전달받는 도킹부와, 도킹부를 상승 또는 하강시키는 제2승강부가 형성되며 상부에 건조로가 구비된 건조부;상기 작업대의 타측에 형성되며, 상기 건조로에서 건조를 마친 건조물이 인계되어 안착되는 제2트레이와, 상기 제2트레이를 상승 또는 하강시키는 제3승강부가 형성되어 건조물을 배출하는 인출이송부;를 포함하는 것을 특징으로 하는 전자기파를 이용한 건조장치., Ltext: 농업, prediction: 임업
804/1059 Row 804: application_number: 1020190110919, combined_string: invention_title: 분체 건조 방법 및 분체 건조 설비 abstract: 본 발명은 건조 대상물인 분체를 골고루 균등하게 건조시킬 수 있어 균일한 건조 품질을 제공하면서도 건조량을 증대시킬 수 있고, 건조 대상물이 이송 벨트에 고착될 일이 없어 설비의 유지 관리성을 향상시킬 수 있으며, 나아가 건조되는 분체의 함수율을 용이하게 조정할 수 있는 적용 분야에 맞는 최적의 건조 분체를 제공할 수 있는 분체 건조 방법 및 분체 건조 설비에 관한 것이다. 본 발명에 따르면, 건조 대상물인 분체를 투입하는 건조대상물 투입 단계; 상기 투입되는 건조 대상물을 하기 건조대상물 이송 단계로 공급하는 건조대상물 공급 단계; 상기 건조대상물을 컨베이어 벨트의 상면에서 이송시키는 건조대상물 이송 단계; 상기 컨베이어 벨트 상에서 이송되는 건조대상물을 건조시키는 건조대상물 건조 단계; 및 건조된 건조 분체를 외부로 배출하는 건조물 배출 단계;를 포함하며, 상기 건조대상물 이송 단계는 건조대상물을 컨베이어 벨트에서 이동시키면서 건조대상물이 뒤집어엎어지도록 이루어지는 것을 특징으로 하는 분체 건조 방법 및 분체 건조 설비가 제공된다. claims: 건조 대상물인 분체를 투입하는 건조대상물 투입 단계;상기 투입되는 건조 대상물을 하기 건조대상물 이송 단계로 공급하는 건조대상물 공급 단계;상기 건조대상물을 컨베이어 벨트의 상면에서 이송시키는 건조대상물 이송 단계;상기 컨베이어 벨트 상에서 이송되는 건조대상물을 건조시키는 건조대상물 건조 단계; 및건조된 건조 분체를 외부로 배출하는 건조물 배출 단계;를 포함하며,상기 건조대상물 이송 단계는 건조대상물을 컨베이어 벨트에서 이동시키면서 건조대상물이 뒤집어엎어지도록 이루어지는 것을 특징으로 하는분체 건조 방법.함수(含水) 분체를 포함하는 건조대상물을 건조시키기 위한 설비로서,일측 상부에 투입 호퍼가 구비되고 타측 단부에 배출구가 구비되는 설비 바디부;상기 투입 호퍼에서 투입되는 건조대상물을 타측으로 이송시키도록 구성되는 분체 이송 장치부;상기 분체 이송 장치부에 의해 이송되는 건조대상물을 건조시키도록 구성되는 분체 건조 장치부;상기 분체 이송 장치부에 의해 이송되는 과정에서 건조대상물을 뒤집어엎도록 구성되는 교반 써레 수단; 및상기 분체 이송 장치부와 분체 건조 장치부의 동작을 제어하기 위한 제어반;을 포함하는 것을 특징으로 하는분체 건조 설비., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

805/1059 Row 805: application_number: 1020190110797, combined_string: invention_title: 농산물 가공 유통 시스템 및 방법 abstract: 본 발명은 산지에서 직접 매입한 배추, 시금치, 상추, 감자, 고구마, 양파, 당근, 오이, 단호박, 양상추, 브로콜리 등과 같은 모든 종류의 농산물을 소비자의 주문에 따라 선택하여 슬라이스나 다이스로 잘라서 포장한 후 택배를 통해 소비자에게 배송할 수 있도록 하는 농산물 가공 유통 시스템 및 방법이 개시된다.개시된 농산물 유통 서버는, 하나 이상의 작업장에 각각 배치된 RFID 리더기와, 세척기, 컨베이어, 슬라이서, 포장기, 바코드 리더기 및 스마트폰과 연동하는 통신부; 상기 농산물의 입고 정보와 제품 주문 정보 및 통신 주문 정보를 저장하거나, 상기 농산물의 입고량과 재고량, 분류 데이터, 제품 정보를 저장하며, 상기 농산물의 판매 정보, 고객 정보, 작업자 정보를 저장하고 있는 DB; 및 상기 농산물의 판매 데이터에 근거해 각 제품 별로 원가와 판매가를 이용해 일정 기간의 마진율과 영업이익률을 산출해 제품명에 매칭시키고, 그 기간 중 다른 값들에 비해 일정 이상으로 차이가 나는 기간에 대해 주요 요인을 입력받아 학습하며, 학습된 데이터를 모델링하여 판매 모델을 생성하며, 상기 판매 모델에 새로운 농산물 정보를 입력하여 마진율과 영업이익률을 예측 산출하는, 마이크로 프로세서를 포함한다. claims: 농산물 가공 유통 앱(Application)을 통해 입고 농산물의 정보를 입력받거나 주문된 제품 주문 정보를 입력받는 스마트폰;통신망으로부터 수신된 통신 주문 정보와 상기 제품 주문 정보에 따라 작업 전표를 발행하여 농산물의 가공 및 유통을 제어하는 농산물 유통 서버;상기 작업 전표에 따라 선택 투입된 농산물을 세척하는 세척기;상기 세척된 농산물을 이동시키는 컨베이어;상기 이동된 농산물을 슬라이스 또는 다이스로 자르는 슬라이서;상기 슬라이서에 의해 잘라진 농산물을 박스 또는 포장지로 포장하고, 상기 박스 또는 포장지에 바코드를 부착하는 포장기; 상기 포장된 농산물의 배송 시 상기 바코드를 리딩하는 바코드 리더기;상기 포장된 농산물의 이상 상태를 검사하는 X-ray기; 및상기 포장된 농산물에 금속이 포함되어 있는지 검사하는 금속 검출기;를 포함하고,상기 농산물 유통 서버는 상기 통신 주문 정보 및 상기 제품 주문 정보에 따른 판매 데이터에 근거해 각 제품 별로 원가와 판매가를 이용해 일정 기간 마진율과 영업이익률을 산출해 제품명에 매칭시키고, 그 기간 중 다른 값들에 비해 일정 이상으로 차이가 나는 기간에 대해 주요 요인을 입력받아 학습하며, 학습한 데이터를 모델링하여 판매 모델을 생성하며, 상기 판매 모델에 새로운 농산물 정보를 입력하여 마진율과 영업이익률을 예측 산출하며,상기 농산물 가공 유통 앱을 통해 상기 슬라이스의 크기가 선택되는 경우, 상기 농산물 가공 유통 앱이 상기 슬라이스의 크기에 따라 해당 농산물의 생산량을 예측하여 화면상으로 표시시키고, 상기 작업 전표에 따라 배정된 각 작업자에 대응된 RFID 신호를 송출하는 복수의 RFID 태그(Tag);를 더 포함하고,상기 농산물 유통 서버는 상기 세척기와 상기 컨베이어, 상기 슬라이서, 상기 포장기 및 상기 바코드 리더기와 유선 네트워크 또는 무선 네트워크를 통해 연동하며,상기 세척기는 제1 작업장에 배치되고 상기 제1 작업장에는 상기 세척기에 매칭된 제1 RFID 리더기가 설치되며,상기 컨베이어는 제2 작업장에 배치되고 상기 제2 작업장에는 상기 컨베이어에 매칭된 제2 RFID 리더기가 설치되며,상기 슬라이서는 제3 작업장에 배치되고 상기 제3 작업장에는 상기 슬라이서에 매칭된 제3 RFID 리더기가 설치되며,상기 포장기는 제4 작업장에 배치되고 상기 제4 작업장에는 상기 포장기에 매칭된 제4 RFID 리더기가 설치되며,상기 바코드 리더기는 제5 작업장에 배치되고 상기 제5 작업장에는 상기 바코드 리더기에 매칭된 제5 RFID 리더기가 설치되며,상기 X-ray기 및 상기 금속 검출기는 상기 제4 작업장 또는 상기 제5 작업장에 배치되며, 상기 제1 내지 제5 RFID 리더기는 각 작업장에 위치해 있는 적어도 하나 이상의 RFID 태그로부터 RFID 신호를 수신하면, 자신의 관할 작업장에서 인식된 RFID 및 시간 데이터를 포함하는 작업장 정보를 상기 농산물 유통 서버로 전송하고,상기 농산물 유통 서버는 상기 제1 내지 제5 RFID 리더기로부터 수신된 작업장 정보에 근거해 각 작업장에 위치해 있는 RFID와 시간 데이터를 인식하여 각 작업장 별 작업 현황을 화면 상에 또는 음성으로 출력하며,상기 농산물 유통 서버는,적어도 하나 이상의 작업장에 각각 배치된 적어도 하나 이상의 RFID 리더기와 상기 세척기, 상기 컨베이어, 상기 슬라이서, 상기 포장기, 상기 바코드 리더기 및 상기 스마트폰과 유선 네트워크 또는 무선 네트워크를 통해 연동하는 통신부;상기 스마트폰의 농산물 가공유통 앱(Application)을 통해 입력받은 농산물의 입고 정보와 제품 주문 정보를 저장하거나, 상기 통신부를 통해 외부로부터 수신된 통신 주문 정보를 저장하거나, 상기 농산물의 입고량과 재고량, 분류 데이터, 제품 정보를 저장하거나, 각 작업장에 배치된 하나 이상의 RFID 리더기 정보와 하나 이상의 RFID 태그 정보를 저장하며, 상기 농산물의 메뉴 정보와 판매 정보, 고객 정보, 작업자 정보를 저장하고 있는 데이터베이스; 및상기 통신 주문 정보 및 상기 제품 주문 정보에 따른 판매 데이터에 근거해 각 제품 별로 원가와 판매가를 이용해 일정 기간의 마진율과 영업이익률을 산출해 제품명에 매칭시키고, 그 기간 중 다른 값들에 비해 일정 이상으로 차이가 나는 기간에 대해 주요 요인을 입력받아 학습하며, 학습된 데이터를 모델링하여 판매 모델을 생성하며, 상기 판매 모델에 새로운 농산물 정보를 입력하여 마진율과 영업이익률을 예측 산출하는, 마이크로 프로세서를 포함하고,상기 마이크로 프로세서는, 상기 판매 데이터에 근거해 각 제품 별로 원가와 판매가를 이용해 일정 기간의 마진율과 영업이익률을 산출해 제품명에 매칭시켜 학습 데이터로 상기 데이터 베이스에 저장하고, 상기 학습 데이터에 대해 모델링하여 모델을 생성하기 위한 모델링 데이터군과, 생성한 모델을 검증하기 위한 검증 데이터군으로 분류하며, 상기 모델링 데이터군에 대해 상기 제품명 별로 마진율과 영업이익률을 학습하여 상기 마진율과 상기 영업이익률 간의 관계를 나타내는 추정 함수식(E(x))을 산출하며,상기 제품명 별 각 영업이익률 데이터와 상기 추정 함수식의 그래프에 해당하는 추정 데이터들 간의 거리값들을 각각 산출하여, 산출된 각 거리값들을 모두 합하여 상기 제품명 수에 따른 데이터 개수로 나누어, 산출된 거리값들 중 최소가 되고 상기 추정 함수식의 그래프에 가장 근접하는 마진율과 영업이익률을 가지는 함수식의 기울기(a) 값과 절편(b) 값을 산출하며,산출된 기울기(a) 값과 절편(b) 값을 상기 추정 함수식에 대입해 판매 함수식(y=ax+b)을 결정하여, 마진율에 따른 영업이익률을 산출하기 위한 상기 판매 모델을 생성하며, 상기 제품명 별로 산출한 각 마진율(x)을 상기 판매 모델에 각각 대입하여 상기 제품명 별로 영업이익률(y)을 산출하고, 상기 제품명 별로 영업이익률(y)과 수수료 데이터를 비교하여 내림차순으로 리스팅(listing)하며,상기 마이크로 프로세서는, 상기 검증 데이터군에 대해 상기 제품명 별로 각각의 마진율(x)을 산출하고, 산출된 각 마진율(x)을 상기 판매 모델에 대입해 영업이익률(y)을 각각 산출하며, 상기 제품명 별로 산출된 각각의 마진율(x) 및 영업이익률(y)에 대해 상기 추정 함수식의 그래프와의 거리값들을 산출하며,상기 산출된 거리값들에 대한 거리 평균값을 산출하고, 산출된 거리 평균값을 상기 마진율(x)과 상기 영업이익률(y) 간의 관계에서 최소가 되는 거리값과 비교해, 상기 산출된 거리 평균값과 상기 최소가 되는 거리값의 차이가 오차 범위 이내인가의 여부에 따라 상기 판매 모델을 검증하며,상기 마이크로 프로세서는, 상기 각 제품 별로 원가와 판매가를 이용해 산출한 마진율과 영업이익률을 제품명에 매칭시키고, 매칭된 제품명에 제품 종류와 제품 성격, 시장 규모를 대응시켜 상기 데이터베이스에 저장하며, 상기 제품 성격은 근채류, 과채류, 양채류 및 기타류를 포함하고, 상기 시장 규모는 이용자가 10만명 미만인 소규모 시장과, 이용자가 10만명 이상 100만명 미만인 중규모 시장, 이용자가 100만명 이상인 대규모 시장을 포함하며,상기 마이크로 프로세서는, 상기 모델링 데이터군을 상기 제품성격에 따라 근채류, 과채류, 양채류 및 기타류의 4가지 분야로 재분류하고, 상기 재분류된 각각의 모델링 데이터군에 대해 상기 제품명 별로 마진율(x), 영업이익률(y)을 학습하여, 상기 마진율(x)과 상기 영업이익률(y) 간의 관계를 나타내는 추정 함수식(E(x))을 상기 제품성격의 4가지 분야 별로 각각 산출하고,상기 마이크로프로세서는 상기 제품성격의 4가지 분야 별로 상기 제품명 별 각 영업이익률(y) 데이터와, 상기 추정 함수식(E(x))의 그래프에 해당하는 추정 데이터들 간의 거리값([E(x)-y(x)]2)들을 각각 산출하고, 각각 산출된 거리값들을 모두 합하여 상기 제품명 수에 따른 데이터 개수(m)로 나누어, 상기 산출된 거리값들 중 최소가 되고 상기 추정 함수식의 그래프에 가장 근접하는 마진율(x)과 영업이익률(y)을 가지는 함수식의 기울기(a) 값과 절편(b) 값을 상기 제품성격의 4 가지 분야에 따라 각각 산출하며,상기 마이크로프로세서는 상기 제품성격의 4가지 분야에 따라 산출된 기울기(a) 값과 절편(b) 값을 상기 제품성격의 4가지 분야 별로 상기 추정 함수식에 대입해 판매 함수식(y=ax+b)을 결정하여, 마진율에 따른 영업이익률을 산출하는 판매 모델을 상기 제품성격의 근채류, 과채류, 양채류 및 기타류에 따라 각각 생성하며,상기 마이크로프로세서는 상기 모델링 데이터군을 상기 시장규모에 따라 소규모 시장, 중규모 시장, 대규모 시장의 3 가지 분야로 재분류하고, 상기 재분류된 각각의 모델링 데이터군에 대해, 상기 제품명 별로 마진율(x), 영업이익률(y)을 학습하여, 상기 마진율(x)과 상기 영업이익률(y) 간의 관계를 나타내는 추정 함수식(E(x))을 상기 시장규모의 3가지 분야 별로 각각 산출하고,상기 마이크로프로세서는 상기 시장규모의 3가지 분야 별로 상기 제품명 별 각 영업이익률(y) 데이터와, 상기 추정 함수식(E(x))의 그래프에 해당하는 추정 데이터들 간의 거리값([E(x)-y(x)]2)들을 각각 산출하고, 각각 산출된 거리값들을 모두 합하여 상기 제품명 수에 따른 데이터 개수(m)로 나누어, 상기 산출된 거리값들 중 최소가 되고 상기 추정 함수식의 그래프에 가장 근접하는 마진율(x)과 영업이익률(y)을 가지는 함수식의 기울기(a) 값과 절편(b) 값을 상기 시장규모의 3 가지 분야에 따라 각각 산출하며,상기 마이크로프로세서는 상기 시장규모의 3가지 분야에 따라 산출된 기울기(a) 값과 절편(b) 값을 상기 시장규모의 3가지 분야 별 추정 함수식에 각각 대입해 판매 함수식(y=ax+b)을 각각 결정하여, 마진율에 따른 영업이익률을 산출하는 판매 모델을 상기 시장규모의 소규모 시장, 중규모 시장, 대규모 시장에 따라 3 가지 분야 별로 각각 생성하는농산물 유통 시스템., Ltext: 농업, prediction: 농업
806/1059 Row 806: application_number: 1020190108424, combined_string: invention_title: 종자의 표면 처리 방법 abstract: 본 발명은 종자의 표면 처리 방법에 관한 것이다.구체적으로, 본 발명의 일 구현예에서는, 농산물의 생산성을 높이는 방법 중 하나로, 종자의 표면에 플라즈마를 조사하는 제1 단계; 및 화학적 처리, 건열 처리, 또는 이들을 조합한 처리 방법으로, 상기 제1 단계가 완료된 종자를 처리하는 제2 단계;를 포함하는, 종자의 표면 처리 방법을 제공한다. claims: 종자의 표면에 플라즈마를 조사하는, 플라즈마 처리 단계; 및 상기 플라즈마 처리된 종자의 표면을 살균 소독액으로 처리하는, 화학적 처리 단계;를 포함하는,종자의 표면 처리 방법.종자의 표면에 플라즈마를 조사하는, 플라즈마 처리 단계; 및 상기 플라즈마 처리된 종자의 표면을 건열 처리하는, 건열 처리 단계;를 포함하는,종자의 표면 처리 방법.종자의 표면에 플라즈마를 조사하는, 플라즈마 처리 단계; 상기 플라즈마 처리된 종자의 표면을 살균 소독액으로 처리하는, 화학적 처리 단계; 및 상기 화학적 처리된 종자의 표면을 건열 처리하는, 건열 처리 단계;를 포함하는,종자의 표면 처리 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

807/1059 Row 807: application_number: 1020190106870, combined_string: invention_title: 딥러닝 기반 농산물 물동량 분배 의사결정 지원 시스템 abstract: 본 발명은 각 도매시장에서의 과거의 수요량과 가격 데이터와, 그 때의 농산물의 재고량, 기후 정보, 프로모션 정보 등을 신경망 또는 딥러닝으로 학습하여, 농산물의 수요량 및 가격을 예측하는, 딥러닝 기반 농산물 물동량 분배 의사결정 지원 시스템에 관한 것으로서, 지역에 기초한 농산물 물동량 관련 정보에 대한 기초 데이터 또는 각 도매시장의 물동량 데이터를 수집하는 기초데이터 수집부; 도매시장과 농산물 종류의 조합 별로 신경망 모델(이하 조합별 신경망 모델)을 설정하는 모델 설정부; 행정구역의 지역으로 구분된 지형 지도를 2차원 사각형의 정규 지도로 매핑하여, 행정구역의 지역에 대한 정규 지도의 지도 상의 지역 영역의 매핑 관계를 설정하는 정규매핑 설정부; 지역에 대한 정규 지도의 매핑 관계를 이용하여, 각 기초 데이터로부터 2차원 이미지의 디스크립터를 산출하는 디스크립터 추출부; 과거 날짜의 농산물 종류별 기초 데이터의 디스크립터(이하 농산물 종류별 디스크립터)에, 도매시장별 물동량 데이터를 라벨 값으로 라벨링하여 조합별 학습 데이터를 생성하고, 생성된 조합별 학습 데이터로 조합별 신경망 모델을 학습시키는 모델 학습부; 조합별 신경망 모델을 이용하여 해당 조합의 농산물 종류 및 도매시장에 대한 농산물 물동량을 예측하는 물동량 예측부를 포함하는 구성을 마련한다.상기와 같은 시스템에 의하여, 농산물의 재고량, 기후 정보, 프로모션 정보 등 특성 정보를 함께 딥러닝으로 학습함으로써, 농산물의 수요량 및 가격을 보다 정확한 예측할 수 있다. claims: 딥러닝 기반 농산물 물동량 분배 의사결정 지원 시스템에 있어서,지역에 기초한 농산물 물동량 관련 정보에 대한 기초 데이터 또는 각 도매시장의 물동량 데이터를 수집하는 기초데이터 수집부;도매시장과 농산물 종류의 조합 별로 신경망 모델(이하 조합별 신경망 모델)을 설정하는 모델 설정부;행정구역의 지역으로 구분된 지형 지도를 2차원 사각형의 정규 지도로 매핑하여, 행정구역의 지역에 대한 정규 지도의 지도 상의 지역 영역의 매핑 관계를 설정하는 정규매핑 설정부;지역에 대한 정규 지도의 매핑 관계를 이용하여, 각 기초 데이터로부터 2차원 이미지의 디스크립터를 산출하는 디스크립터 추출부;과거 날짜의 농산물 종류별 기초 데이터의 디스크립터(이하 농산물 종류별 디스크립터)에, 도매시장별 물동량 데이터를 라벨 값으로 라벨링하여 조합별 학습 데이터를 생성하고, 생성된 조합별 학습 데이터로 조합별 신경망 모델을 학습시키는 모델 학습부;조합별 신경망 모델을 이용하여 해당 조합의 농산물 종류 및 도매시장에 대한 농산물 물동량을 예측하는 물동량 예측부를 포함하는 것을 특징으로 하는 딥러닝 기반 농산물 물동량 분배 의사결정 지원 시스템., Ltext: 농업, prediction: 농업
808/1059 Row 808: application_number: 1020190104879, combined_string: invention_title: 농산물의 신선도 유지에 도움을 주는 투명필름 제조방법 abstract: 독거세대가 늘어나는 추세에 따라 농산물의 포장도 소포장화가 주를 이루고 있는데 이와같은 흐름에 발맞춰 소포장된 농산물이 통기성좋은 비닐과 보습효과를 주는 젤패드와 함께 포장되어 유통이 될 경우 똑같이 냉장고에 보관되어도 기존의 방식보다는 최소 두배이상 오래 신선도를 유지할 수 있게 하는 제품이다. claims: 다연장 비닐포장지에 엑시머레이저기계를 이용하여 미세한 구멍을 연속적으로 천공하는 방법;천공한 비닐을 원형으로 감을때 천공구멍이 겹치지 않도록 간격을 조절하는 패턴 디자인, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

809/1059 Row 809: application_number: 1020190104886, combined_string: invention_title: 농산물의 신선도 유지에 도움을 주는 젤리패드의 제조방법 abstract: 흔히 고기류 제품을 구입할때 빠지는 핏물을 흡수할 수 있도록 흡습패드를 포장지 아래에 깔아주는 경우는 많았으나, 농산물의 장기보존을 위해 반대로 습도를 유지시켜주기 위해 아이스팩의 소재인 수분젤리를 이용해서 습포제 안에 넣어 비닐로 소분 포장된 비닐의 내부 습도를 유지시켜 더욱 오랫동안 신선하게 보존하게 할 수 있는 방법이다. claims: 습기를 천천히 누출하는 펠트지에 수분을 머금은 젤리형태의 재료를 담는방법;습포제에 젤리패드를 넣고 투입구 봉합시 일정 간격으로 미세구멍을 뚫어 습도가 잘 유지될 수 있도록 포장하는 방법, Ltext: 농업, prediction: 농업
810/1059 Row 810: application_number: 1020190103090, combined_string: invention_title: 황토를 이용한 건조장 abstract: 본 발명은 건조대상물이 수용된 트레이가 상하로 다단 적층된 제3 유닛이 도어를 통하여 제1 유닛의 내부로 투입되고, 제2 유닛은 제1 유닛의 내부공기를 강제 대류시키면서 건조대상물을 건조시키되, 제1 유닛의 투명 또는 반투명한 지붕을 통하여 자연채광을 유입시키면서 건조대상물을 자연건조도 시킬 수 있도록 한 구조로부터, 수요자의 요구 조건에 맞춰 고추와 같은 농산물들의 건조가 확실하게 이루어질 수 있도록 하는 황토를 이용한 건조장에 관한 것이다. claims: 황토 또는 황토를 함유한 마감재로 내측 벽면과 바닥면을 형성한 건조장 본체와, 상기 건조장 본체의 상면을 덮는 투명 또는 반투명 소재의 지붕과, 상기 건조장 본체의 일측면에 형성되어 출입 가능한 도어를 포함하는 제1 유닛;상기 지붕 아래에 적어도 하나 이상 배치되어 상기 건조장 본체의 내부 공간의 공기(이하 '내부공기')를 강제 대류시키는 순환기와, 상기 내부공기를 흡입하고 가열시켜 건조된 에어를 토출시키는 황토방 건조기를 포함하는 제2 유닛; 및상기 도어를 통하여 출입 가능하며, 복수의 건조대상물을 상하로 이격하여 다단 적층 가능한 트레이가 상하 슬라이딩 적재 가능한 건조 본체와, 상기 건조 본체의 하부측에 이동 가능한 방향성 캐스터를 포함하는 제3 유닛을 포함하며,상기 건조대상물은 상기 지붕을 통하여 조사되는 자연채광을 통하여 건조되는 것을 특징으로 하는 황토를 이용한 건조장., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

811/1059 Row 811: application_number: 1020190103013, combined_string: invention_title: 농산물 수급 예측 서버 및 농산물 수확 최적지 분석 방법 abstract: 실시예에 따른 농산물 수급 예측 서버 및 농산물 수확 최적지 분석 방법은 품종 별 표준지표와 농수산물별 수확 최적지 정보를 누적된 분석정보를 기반으로 업데이트하여 생산자와 도소매 업자에게 정확한 정보를 제공할 수 있다. 또한, 실제 기후데이터와 품종 별 품질 데이터를 반복측정하고 측정 결과를 누적하여 품종 별 표준지표와 최적지 정보를 업데이트 할 수 있고, 실제 기후에 따라 농작물의 수급과 품질, 가격을 예측할 수 있다. 또한, 실시예를 통해 년도, 계절, 분기에 따른 실제 기후에 따라 수확된 농산물 품질을 분석하여 기후와 품질의 상관관계에 대한 분석 데이터를 확보할 수 있고, 품질 예측을 통해 가격 차등을 정확하게 산출하여, 소비자에게 고품질의 농산물을 합리적인 가격으로 제공할 수 있고, 지역별 농수산물의 품질과 수확량에 대한 정확한 수급 예측을 통해 가격을 안정화 시키고 농수산물 수급을 안정적으로 조정할 수 있도록 한다. claims: 농산물 수확 최적지 분석 방법에 있어서,(A)분석서버에서 농산물의 최적 수확환경데이터인 품종 별 표준지표를 설정하는 단계;(B)분석서버에서 지역별 강수량, 일조량, 일교차를 포함하는 환경정보 및 지역별 누적 날씨 데이터를 수집하는 단계;(C)분석서버에서 수집된 날씨 데이터와 지역별 환경정보를 상기 표준지표와 비교하고 상관관계를 분석하는 단계; 및(D)분석서버에서 상관관계가 가장 높은 지역을 최적지로 추출하고, 상기 최적지로 추출된 지역 농산물의 작황, 수확량, 품질을 포함하는 농산물 수확 품질 세부정보를 파악하는 단계; (E) 분석서버에서 상기 추출된 최적지의 환경정보와 표준지표를 비교하는 단계; (F) 분석서버에서 지역별 환경정보와 표준지표를 기간에 따라 비교하고, 지역 별 농산물 품질을 비교하는 단계;및(G) 분석서버에서 비교 결과에 따라 농산물별 최고 품질지역을 선정하는 단계;를 포함하고,상기 (F) 단계; 는지역별 환경정보와 표준지표 비교결과 및 실제 농산물 수확 품질의 데이터를 축적하여, 시계열 분석을 통해 농산물의 수급, 가격을 예측하고, 최적지를 업데이트 하고, 업데이트된 최적지에 따라 농산물 별 표준지표를 업데이트 하고상기 (C) 단계; 는분석서버에서 실제 지역에서 재배된 농산물의 품종 별 품질 정보를 반복 측정하고, 반복 측정된 정보를 누적 저장하여 새로운 표준지표를 생성하는 단계;표준지표와 지역별 환경정보의 상관관계에 따라 지역별 농산물 품종의 품질을 예측하는 단계; 계절변동 및 순환변동으로 인한 실제 지역별 기후데이터와 환경데이터를 누적저장하고 수확량, 품질을 포함하는 농작물 수확정보를 누적하고 환경데이터와 농작물 수확정보에 대한 상관관계를 파악하여 실제 기후데이터가 입력되면 농작물 재배량과 품질을 예측하는 단계; 및농작물 재배량과 품질 예측 결과에 따라 농산물 가격차등 정도를 산출하는 단계;를 포함하고,상기 (D) 단계; 는분석서버에서 최적지로 추출된 지역 농산물의 작황, 수확량, 품질을 포함하는 농산물 수확 품질 세부정보를 파악하고, 농산물 수확 품질 세부정보에 따라 표준지표와 최적지를 업데이트하고, 지역별 농산물 수급 및 가격을 예측하는 단계; 지역별 환경정보와 표준지표 비교결과 및 실제 농산물 수확 품질의 데이터를 축적하여, 시계열 분석 및 회귀분석을 통해 농산물의 수급, 가격을 예측하고, 최적지를 업데이트 하는 단계;시계열 분석 결과를 통해, 실제 날씨에 따른 품종 별 재배량과 품질 및 수요량을 예측하고 예측 결과를 기반으로 그 해 농작물의 지역별 품질 예측과 가격예측을 수행하는 단계;업데이트된 최적지에 따라 농산물 별 표준지표를 업데이트 하고, 표준지표와 지역별 환경정보의 상관관계에 따라 지역별 농산물 품종 품질을 예측하고, 지역별 농산물 품종 품질 예측 결과에 따라 농산물 가격차등 정도를 산출하는 단계; 및 농산물의 크기, 색 선명도, 당도, 무게, 재배량을 포함하는 측정 가능한 농산물의 세부정보를 전달받아, 품종 별 평균크기와 비교하고 품종 별 표준편차를 산출하여 수확된 농산물의 품질을 파악하는 단계;를 포함하고,상기 시계열 분석은 과거의 날씨정보 변화추세나 이에 따른 지역별 농작물의 재배량, 품질 변화 및 농작물 재배량과 품질에 기반한 수요 또는 소비 변화 데이터를 누적저장하고 저장된 데이터를 추적하여 분석하는 것을 특징으로 하는 농산물 수확 최적지 분석 방법.농산물 수급 예측 서버에 있어서,농산물의 최적 수확환경데이터인 품종 별 표준지표를 설정하여 저장하는 데이터베이스;지역별 강수량, 일조량, 일교차를 포함하는 환경정보 및 지역별 누적 날씨 데이터를 수집하는 수집모듈;수집된 날씨 데이터와 지역별 환경정보를 상기 표준지표와 비교하여 상관관계를 분석하고, 상관관계가 가장 높은 지역을 최적지 추출하는 분석모듈; 및상기 최적지로 추출된 지역 농산물의 작황, 수확량, 품질을 포함하는 농산물 수확 품질 세부정보를 파악하고, 상기 농산물 수확 품질 세부정보에 따라 표준지표와 최적지를 업데이트하고, 지역별 농산물 수급 량 및 가격을 예측하는 연산모듈; 을 포함하고상기 분석모듈; 은 지역별 환경정보와 표준지표를 기간에 따라 비교하고, 지역 별 농산물 품질을 비교하고, 비교 결과에 따라 농산물별 최고 품질지역을 선정하고 상기 연산모듈; 은 실제 지역에서 재배된 농산물의 품종 별 품질 정보를 반복 측정하고, 반복 측정된 정보를 누적 저장하여 새로운 표준지표를 생성하고, 지역별 환경정보와 표준지표 비교결과 및 실제 농산물 수확 품질의 데이터를 축적하여, 시계열 분석을 통해 농산물의 수급, 가격을 예측하고, 최적지를 업데이트하고, 업데이트된 최적지에 따라 농산물 별 표준지표를 업데이트 하고, 표준지표와 지역별 환경정보의 상관관계에 따라 지역별 농산물 품종 품질을 예측하고, 계절변동 및 순환변동으로 인한 실제 지역별 기후데이터와 환경데이터를 누적저장하고 수확량, 품질을 포함하는 농작물 수확정보를 누적하고 환경데이터와 농작물 수확정보에 대한 상관관계를 파악하여 실제 기후데이터가 입력되면 농작물 재배량과 품질을 예측하고, 농작물 재배량과 품질 예측 결과에 따라 지역별 농산물의 가격차등 정도를 산출하고상기 연산모듈; 은 지역별 환경정보와 표준지표 비교결과 및 실제 농산물 수확 품질의데이터를 축적하여, 시계열 분석 및 회귀분석을 통해 농산물의 수급, 가격을 예측하고, 최적지를 업데이트 하고, 시계열 분석 결과를 통해, 실제 날씨에 따른 품종 별 재배량과 품질 및 수요량을 예측하고 예측 결과를 기반으로 그 해 농작물의 지역별 품질 예측과 가격예측을 수행하고, 업데이트된 최적지에 따라 농산물 별 표준지표를 업데이트 하고, 표준지표와 지역별 환경정보의 상관관계에 따라 지역별 농산물 품종 품질을 예측하고, 지역별 농산물 품종 품질 예측 결과에 따라 농산물 가격차등 정도를 산출하고, 농산물의 크기, 색 선명도, 당도, 무게, 재배량을 포함하는 측정 가능한 농산물의 세부정보를 전달받아, 품종 별 평균크기와 비교하고 품종 별 표준편차를 산출하여 수확된 농산물의 품질을 파악하고,상기 시계열 분석은 과거의 날씨정보 변화추세나 이에 따른 지역별 농작물의 재배량, 품질 변화 및 농작물 재배량과 품질에 기반한 수요 또는 소비 변화 데이터를 누적저장하고 저장된 데이터를 추적하여 분석하는 것을 특징으로 하는 농산물 수급 예측 서버., Ltext: 농업, prediction: 농업
812/1059 Row 812: application_number: 1020190101430, combined_string: invention_title: 양액을 분무하는 농산물 저장방법 및 그 저장고 abstract: 본 발명은 양액(養液)을 분무하는 농산물 저장방법 및 그 저장고에 관한 것으로 농산물을 저장하는 일정한 공간을 가진 저장고에 공조수단에 의해 신선공기를 공급 순환하게 된 것에 있어서,상기 저장고에 저장된 각종 농산물에 식물이 흡수할 수 있는 가급태(可給態)의 무기질 양분과 미생물의 살균, 또는 활성을 억제하는 효능이 있는 성분이 혼합된 양액을 분무수단에 의해 분무하여 소정의 온도와 습도를 유지하면서 미생물의 활성을 억제하고 식물학적으로 농산물에 영양분이 보충되어 신선도를 유지하면서 장기간 보관이 가능하게 된 것이다. claims: ,저장고에 저장된 농산물을 공조기구에 의해 일정한 온도와 습도로 공조하여 저장하게 된 것에 있어서,저장고에 저장된 농산물의 생체에 황(S), 칼슘(Ca), 일산화질소(NO)의 무기질 이온이 함유된 양액을 분무수단에 의해 분무하여 저장하는 것을 특징으로 하는 양액을 분무하는 농산물 저장방법.저장고의 상부 측에 냉각기구가 구비된 팬코일이 설치되고 저장고의 하부 측에서 상기 팬코일에 이르는 공기의 순환 닥트가 구비되어 공조하게 된 것에 있어서,상기 저장고에 양액이 분무되는 분무수단이 구비된 것을 특징으로 하는 양액을 분무하는 농산물의 저장고, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

813/1059 Row 813: application_number: 1020190101555, combined_string: invention_title: 밀폐형 제습순환타입의 건조 장치 abstract: 실시예는 밀폐형 제습순환타입의 건조 장치에 관한 것이다.구체적으로, 이러한 장치는 여러 대의 건조장치를 운용하는 경우, 각 건조장치의 순환 파이프의 밸브를 순차적으로 개폐하여 한 조의 순환장치와 응축기를 통해 다수의 건조장치의 수분을 제거한다. claims: 건조할 시, 다수의 건조장치를 운용해서 수분을 제거함으로써 건조하는 장치에 있어서,상기 다수의 건조장치를 통해 수분이 제거될 시, 상기 다수의 건조장치에 대해 공용의 단일장치로서 상기 다수의 건조장치의 수분을 각기 개별적으로 통합하여 빨아들이는 순환장치;상기 순환장치에 의해 다수의 건조장치의 수분이 빨아들여질 시, 상기 순환장치와 연동하여 상기 다수의 건조장치에 대해 공용의 단일장치로서 상기 다수의 건조장치의 수분을 각기 개별적으로 통합하여 제습하는 응축기;상기 순환장치와 상기 응축기에 의해 수분이 제거될 시, 상기 다수의 건조장치마다 개별적으로 상기 순환장치와 상기 응축기에 각기 연결 설치하는 다수의 밸브; 및상기 다수의 밸브에 의해 다수의 건조장치마다 개별적으로 상기 순환장치와 상기 응축기에 연결될 시, 상기 다수의 밸브로부터 구동을 미리 설정된 순서에 따라 순차적으로 시킴으로써 다수의 건조장치의 수분을 순차제거하는 제어유닛; 을 포함하고,상기 제어유닛은 시스템적으로 제어를 할 시, 센서류로부터 신호를 입력받아 제어대상으로 상이한 제어신호를 제공함으로써 사용자의 설정에 따라 동작하도록 하는 PLC로 이루어지되,상기 동작이 될 시, 상기 센서류로부터 신호를 입력받아 데이터를 수집하는 입력모듈;상기 입력모듈에 의해 신호가 입력될 시, 미리 설정된 제어 로직에 따라 입력된 신호를 프로세싱하여 상이한 제어신호를 발생함으로써 데이터에 따라 상이하게 제어하는 CPU모듈; 및상기 CPU 모듈에 의해 제어신호가 발생될 시, 제어대상으로 상기 제어신호를 전달함으로써 제공하는 출력모듈; 을 포함하고 있으며,상기 동작이 될 시, 자체 유/무선 통신모듈을 구비하여 외부의 제어대상 및 IOT센서로부터 데이터를 수집해서 외부의 제어대상으로 제어신호를 송출함으로써 인터페이스하는 IOT모듈; 을 포함하고,상기 CPU모듈은 상기 IOT모듈에 의해 데이터가 수집될 시, 미리 설정된 해당되는 제어 로직에 따라 수집된 데이터를 프로세싱하여 상이한 제어신호를 발생함으로써 IOT 데이터에 따라 상이하게 제어하고,상기 제어유닛은, a) 상기 다수의 건조장치의 수분이 순차제거될 시, 해당되는 건조장치의 수분 제거도가 미리 설정된 수분 제거도보다 이상인 경우 정상 처리하고 미만인 경우 건조장치의 건조에 실질적으로 영향을 미치는 이상인자를 검출하며,b) 상기 이상인자는 건조장치, 건조할 대상이며,c) 상기 이상인자는아래의 [식 1]로 건조장치가 이상인자인지의 여부를 추정하여 상기 [식 1]의 추정 값(Xt)이 미리 설정된 값 이상인 경우 건조장치를 이상인자로 판별하며, 미만인 경우 건조할 대상 자체를 이상인자로 순차적으로 판별하고,[식 1]Xt = γ1Xt-1 + γ2Xt-2 + ... + γpXt-p + ζt - δt-1ζt-1 - ... - δqζt-q(여기서, Xt는 현재 건조장치 영향도, Xt-p는 현재 건조장치의 표면 청결도와, 표면 상태를 포함한 건조장치 자체의 부품인자별 건조장치 영향도, γ는 건조장치 자체의 부품인자별 영향도 간 상관도, ζ는 건조장치 자체의 부품인자별 영향도 이동 평균 값과 상기 Xt-p 간 오차, δ는 상기 ζ의 건조장치 영향도)d) 상기 [식 1]의 이동평균 구간은, 사용 중인 건조장치의 현재 마모도가 미리 설정된 값보다 적은 경우 미리 설정된 기준 이동평균 구간 값에서 아래의 [식 2]에 따라 산출한 이동평균 구간 값만큼 차감하여 단축 설정하고, 큰 경우 상기 기준 이동평균 구간 값에서 아래의 [식 2]에 따라 산출한 이동평균 구간 값만큼 가산하여 신장 설정하는 것을 특징으로 하는 밀폐형 제습순환타입의 건조 장치.[식 2]이동평균 구간 = [{(현재 마모도 - 미리 설정된 마모도)/미리 설정된 단위 마모도 차이 값} × 미리 설정된 단위 이동평균 구간], Ltext: 농업, prediction: 임업
814/1059 Row 814: application_number: 1020190100344, combined_string: invention_title: 친환경 농산물 및 그 가공품의 종합관리 시스템 abstract: 본 발명은 실질적으로 생산 단계에서는 확실한 친환경 농산물을 생산할 수 있도록 지도 및 관리하고, 생산된 친환경 농산물을 지리정보부(WebGIS) 등을 포함한 인터넷 전자상거래를 연계하여 친환경 농산물의 생산, 가공, 유통, 마케팅의 주요 과정을 생산자 입장에서는 통제 관리할 수 있으며, 소비자입장에서는 구매 물품의 생산과정, 가공과정, 유통과정 등을 확인 선택할 수 있도록 함으로써 친환경 농산물을 신뢰를 바탕으로 유효 적절히 생산, 유통 및 판매할 수 있도록 한 친환경 농산물 및 그 가공품의 종합관리 시스템에 관한 것이다. 이러한 본 발명은 무선통신망을 포함하는 인터넷망(100)에 연결되어 친환경 농산물의 생산, 가공, 유통, 마케팅의 주요 과정 및 친환경 농산물 및 그 가공품의 품질인증을 생산자의 입장에서 종합적으로 관리하는 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)와; 상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 상기 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)로 즉시출하가능 친환경 농산물, 예정출하가능 친환경 농산물, 경매출하가능 친환경 농산물 및 농산물 가공품의 이력정보(농산물이력번호, 생산지, 판매지, 보관방법, 농약명, 농약사용횟수, 농약사용일자, 농약제조사, 출하시기, 포장단위, 가격, 생산자 신상정보, 당도, 맛, 크기, 무게 등)를 제공하는 생산자단말기(300)와; 상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 생산자로부터 공급받은 친환경 농산물을 웹서버의 홈페이지를 통해 소비자에게 주문받은 친환경 농산물 및 그 가공품을 판매하는 전문쇼핑몰 웹서버(400)와; 상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 상기 전문쇼핑몰 웹서버(400)에서 친환경 농산물 및 그가공품을 검색한 후, 소비자가 원하는 친환경 농산물 또는 그 가공품을 주문(즉시주문, 예정주문 및 공동주문등)하는 소비자단말기(500)를 포함하여 구성된다. claims: 무선통신망을 포함하는 인터넷망(100)에 연결되어 친환경 농산물의 생산, 가공, 유통, 마케팅의 주요 과정, 친환경 농산물 및 그 가공품의 품질인증을 생산자의 입장에서 종합적으로 관리하는 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)와;상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 상기 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)로 즉시출하가능 친환경 농산물, 예정출하가능 친환경 농산물, 경매출하가능 친환경 농산물및 친환경 농산물 가공품의 이력정보(농산물이력번호, 생산지, 판매지, 보관방법, 농약명, 농약사용횟수, 농약사용일자, 농약제조사, 출하시기, 포장단위, 가격, 생산자 신상정보, 당도, 맛, 크기, 무게 등)를 제공하는 생산자단말기(300)와;상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 생산자로부터 공급 받은 친환경 농산물 및 그 가공품을 웹서버의 홈페이지를 통해 소비자에게 주문받은 친환경 농산물 또는 그 가공품을 판매하는 전문쇼핑몰 웹서버(400)와;상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 상기 전문쇼핑몰 웹서버(400)에서 친환경 농산물 및 그 가공품을 검색한 후, 소비자가 원하는 친환경 농산물 또는 그 가공품을 주문(즉시주문, 예정주문 및 공동주문 등)하는 소비자단말기(500)를 포함하여 구성된 것을 특징으로 하는 친환경 농산물의 종합관리 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

815/1059 Row 815: application_number: 1020190100359, combined_string: invention_title: 농산물 품질 인증 서비스 방법 abstract: 농산물 품질 인증 서비스 방법이 개시된다. 본 발명에 따른 농산물 품질 인증 서비스 방법은 (a) 서로 다른 고유의 식별 코드들을 가지는 비메모리 방식의 알에프아이디 태그들과 시리얼 번호를 인쇄하여 형성된 마커부를 포함하는 롤 타입 스티커를 준비하는 단계와; (b) 생산자 컴퓨터에서 품질 등급 데이터, 및 해당 품질 등급 박스의 수량을 나타내는 수량 데이터를 포함하는 농산물 정보 데이터와 함께 생산자 정보와 유효 기간 데이터를 포함하는 기본 정보 데이터를 농산물 품질 인증 서버로 전송하는 단계와; (c) 농산물 품질 인증 서버에서 기본 정보 데이터를 사용하여 미리 등록되어 있는 인증된 생산자인지를 확인하고 농산물 정보 데이터를 기초로 해당 수량의 알에프아이디 식별코드를 접수하여 데이터베이스에 저장하는 단계와; (d) 농산물 품질 인증 서버에서 전송 시점을 기점으로 유효 기간 데이터를 사용하여 유효기간을 카운트하여 유효 기간이 경과한 제품 박스에 해당하는 식별코드를 무효화 시키는 단계와; (e) 농산물 품질 인증 서버에서 사용자로부터 시리얼 번호를 입력받고 입력된 시리얼 번호에 매핑된 알에프아이디 식별코드를 얻고 알에프아이디 식별코드에 해당하는 생산자 정보를 사용하여 친환경 인증 업체 서버에 접속하여 해당 생산자가 생산하는 농산물이 친환경 농산물인지의 여부를 검색하는단계; 및 (f) 농산물 품질 인증 서버에서 농산물의 유효 여부와 함께 검색된 친환경 농산물 품질 인증 결과를 사용자에게 전송하는 단계;를 포함하는 것을 특징으로 한다.본 발명에 따르면 사용자, 즉, 유통점 또는 최종 소비자는 시리얼 번호를 사용하기 때문에 알에프아이디 리더가 없이도 구입한 제품의 인증 여부를 확인할 수 있고, 당해 제품 박스의 제품 유효기간이 경과하면 식별 코드를 무효화시키기 때문에 포장 박스를 재사용하거나 위조하여 유통시키는 것을 방지할 수 있고 친환경 농산물인지를 확인함에 있어 매우 확고한 수단을 제공한다. 또한, 선택적으로, 최종 소비자는 태그의 저면에 인쇄된 비밀 번호를 사용하여 유통점과는 차별화된 검색 권한을 가지고 자신이 구입한 제품에 대해 인증된 생산자가 판매한 것인지 유통점에서 위조한 제품인지를 확인할 수 있다. claims: (a) 서로 다른 고유의 식별 코드들을 가지는 비메모리 방식의 알에프아이디 태그들과 상기 태그의 인접한 위치에 상기 식별 코드에 포함된 시리얼 번호를 인쇄하여 형성된 마커부를 포함하는 롤 타입 스티커를 준비하는 단계;(b) 물품을 포장하는 장소에 구비되고 알에프아이디 리더가 접속되어 있는 생산자 컴퓨터에서 품질 등급 데이터, 및 해당 품질 등급 박스의 수량을 나타내는 수량 데이터를 포함하는 농산물 정보 데이터와 함께 생산자 정보와 유효 기간 데이터를 포함하는 기본 정보 데이터를 농산물 품질 인증 서버로 전송하는 단계;(c) 농산물 품질 인증 서버에서 기본 정보 데이터를 사용하여 미리 등록되어 있는 인증된 생산자인지를 확인하고 농산물 정보 데이터를 기초로 해당 수량의 알에프아이디 식별코드를 접수하여 데이터베이스에 저장하는 단계;(d) 농산물 품질 인증 서버에서 전송 시점을 기점으로 유효 기간 데이터를 사용하여 유효기간을 카운트하여 유효 기간이 경과한 제품 박스에 해당하는 식별코드를 무효화 시키는 단계;(e) 농산물 품질 인증 서버에서 사용자로부터 시리얼 번호를 입력받고 입력된 시리얼 번호에 매핑된 알에프아이디 식별코드를 얻고 알에프아이디 식별코드에 해당하는 생산자 정보를 사용하여 친환경 인증 업체 서버에 접속하여 해당 생산자가 생산하는 농산물이 친환경 농산물인지의 여부를 검색하는 단계; 및 (f) 농산물 품질 인증 서버에서 농산물의 유효 여부와 함께 검색된 친환경 농산물 품질 인증 결과를 사용자에게 전송하는 단계;를 포함하는 것을 특징으로 하는 농산물 품질 인증 서비스 방법., Ltext: 농업, prediction: 농업
816/1059 Row 816: application_number: 1020190100372, combined_string: invention_title: 농산물 및 그 가공식품의 안전성을 보증하는 안전농산물생산관리시스템 및 그 방법 abstract: 본 발명은 농산물 및 그 가공식품의 생산/가공 과정에서 발생하는 모든 정보를 관리하고 생산자, 소비자, 감독자에게 제공하여 안전성을 보증하는 안전농산물 생산관리시스템 및 그 방법에 관한 것이다.본 발명에 따른 안전농산물 생산관리시스템은, 농산물 생산자 및 가공식품 가공자로부터 생산이력정보를 전송받아 안전성 검사결과에 대하여 인증여부를 판단하고, 생산자, 가공자, 연구자/지도자 및 소비자에게 생산관리정보를 제공하는 중앙생산관리서버; 재배현황정보를 전송하는 생산자단말; 가공현황정보를 전송하는 가공자단말; 생산자 및 가공자와 쌍방향 통신을 통하여 원격상담하는 연구자/지도자단말; 및 농산물 및 가공식품의 RFID 번호를 전송하고, 상기 생산관리정보를 제공받아 상품의 안전성 여부를 확인하는 소비자단말을 포함하여 이루어진다.본 발명에 따르면, 생산자는 고품질의 농산품을 생산할 수 있고 소비자는 생산부터 유통의 전과정을 모니터링함으로써 신뢰할 수 있는 상품을 구매할 수 있는 것으로 생산자에게는 고부가가치의 제품을 생산하고 안정적인 매출을 보장해준다. claims: 네트워크를 통하여 안전농산물 및 그 안전가공식품의 생산관리정보를 공유하여 관리하는 시스템에 있어서,농산물 생산자로부터 생산환경정보를 입력받고 작물재배정보를 제공하고, 가공식품 가공자로부터 가공환경정보를 입력받고 가공처리공정정보를 제공하고, 농산물 생산지 및 가공식품 가공지에 설치된 원격화상카메라가 촬영한 정보를 모니터하고, 상기 농산물 및 가공식품에 대한 안전성 검사결과에 대하여 인증여부를 판단하고, 생산자, 가공자, 연구자/지도자 및 소비자에게 생산관리정보를 제공하는 중앙생산관리서버;상기 중앙생산관리서버로 상기 생산환경정보를 전송하고, 전송받은 상기 작물재배정보에 따른 생산과정에서 발생하는 재배현황정보를 전송하는 생산자단말;상기 중앙생산관리서버로 상기 가공환경정보를 전송하고, 전송받은 상기 가공처리공정정보에 따른 가공과정에서 발생하는 가공현황정보를 전송하는 가공자단말;상기 중앙생산관리서버의 중개에 따라, 상기 원격화상카메라의 모니터정보를 수신하고 생산자 및 가공자와 쌍방향 통신을 통하여 원격상담하는 연구자/지도자단말; 및상기 중앙생산관리서버로 상기 농산물 및 가공식품의 RFID 번호를 전송하고, 상기 생산관리정보를 제공받아 상품의 안전성 여부를 확인하는 소비자단말을 포함하여 이루어지는 것을 특징으로 하는 농산물 및 그 가공식품의 안전성을 보증하는 안전농산물 생산관리시스템.네트워크를 통하여 안전농산물 및 그 안전가공식품의 생산관리정보를 공유하여 관리하는 방법에 있어서,(1)중앙생산관리서버가 생산자단말로부터 생산환경정보 및 전체 재배현황정보를 전송받고 각각 농산물생산환경DB 및 재배현황정보DB에 저장하는 단계;(2)상기 중앙생산관리서버가 가공자단말로부터 가공환경정보 및 전체 가공현황정보를 전송받고 각각 가공식품생산환경DB 및 가공현황정보DB에 저장하는 단계;(3)상기 중앙생산관리서버가 생산완료된 상기 농산물 및 가공식품에 대하여 소정의 안전성 기준에 따른 안전검사를 수행하여 RFID의 인증을 발급하는 단계;(4)상기 중앙생산관리서버가 상기 농산물 및 가공식품이 소정의 유통경로 게이트를 통과할 때 RFID 인식장치로부터 위성통신을 통하여 유통위치정보를 수신하여 모니터링하는 단계;(5)상기 중앙생산관리서버가 개인 단말기(PC, 모바일)로부터 상기 농산물 또는 가공식품의 RFID를 전송받고, 상기 생산환경정보, 재배현황정보, 가공환경정보, 가공현황정보, 안전성 검사인증정보 및 유통정보를 포함하는 생산관리정보를 제공하는 단계를 포함하여 이루어지는 것을 특징으로 하는 농산물 및 그 가공식품의 안전성을 보증하는 안전농산물 생산관리방법., Ltext: 농업, prediction: 농업

Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

817/1059 Row 817: application_number: 1020190099963, combined_string: invention_title: 맞춤형 농산물 유통 시스템 abstract: 본 발명의 일 실시 예에 따른 농산물 유통 시스템은, 소비자 정보를 서버로 전송하고, 상기 소비자의 농산물 소 비 정보를 입력 받아 상기 서버로 전송하는 단말, 소비자 정보와 농산물 정보를 데이터베이스에 저장하고, 상기 소비자가 단말에 입력한 소비 정보를 수신하여, 상기 소비자 정보와 상기 소비 정보를 대응시켜 상기 데이터베이스에 저장하고, 상기 소비 정보에 따라 상기 농산물 정보에서 필요한 농산물을 선별하고, 상기 농산물의 포장량 을 결정하고, 상기 소비자 정보, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 농산물 포장장치에 송신하는 서버, 서버로부터 상기 소비자 정보, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 수신하고, 포대에 상기 소비자의 주소, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 인쇄하고, 상기 포대에 상기 농산물을 담는 포장장치 및 상기 포장된 포대를 상기 소비자에게 배달하는 배송망을 포함하는 농산물 유통 시스템일 수 있다.본 발명에 따르면, 소비자와 생산자를 직접 연결함으로써, 유통경로를 단순화하여 농산물의 공급가격을 낮출 수 있고, 소비자에게 농산물의 생산정보를 제공하여, 소비자의 신뢰를 높일 수 있고, 소비자의 소비량과 소비패턴을 고려하여 농산물을 공급함으로써, 소비자가 항상 신선한 농산물을 소비할 수 있도록 한다. claims: 소비자 정보를 서버로 전송하고, 상기 소비자의 농산물 소비 정보를 입력 받아 상기 서버로 전송하는 단말;소비자 정보와 농산물 정보를 데이터베이스에 저장하고, 상기 소비자가 단말에 입력한 소비 정보를 수신하여, 상기 소비자 정보와 상기 소비 정보를 대응시켜 상기 데이터베이스에 저장하고, 상기 소비 정보에 따라 상기 농 산물 정보에서 필요한 농산물을 선별하고, 상기 농산물의 포장량을 결정하고, 상기 소비자 정보, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 농산물 포장장치에 송신하는 서버;서버로부터 상기 소비자 정보, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 수신하고, 포대에 상기 소비 자의 주소, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 인쇄하고, 상기 포대에 상기 농산물을 담는 포장 장치; 및상기 포장된 포대를 상기 소비자에게 배달하는 배송망을 포함하는 농산물 유통 시스템., Ltext: 농업, prediction: 농업
818/1059 Row 818: application_number: 1020210045649, combined_string: invention_title: 음성인식을 이용한 스마트팜의 제어방법 abstract: 본 발명은 음성인식을 이용한 스마트팜의 제어방법에 관한 것으로, 음성인식을 기반으로 명령을 수행 및 인식할 뿐만 아니라, 누적된 제어 데이터 값 및 주변 환경에 대한 조절인자 값을 분석하여 각 상화 및 시기별로 자동제어 될 수 있게 하기 위한 것이다. 본 발명에 따른 음성인식을 이용한 스마트팜의 제어방법은 미리 정해놓은 시간 간격에 따라 제1 농작물 시설하우스 내부 또는 외부에 설치된 대기온도센서, 지온온도센서, 습도센서, 일사량 측정 센서, CO2 센서를 포함하는 환경센서로부터 수집된 환경정보를 제어부로 전달하는 제1 환경정보 센싱단계; 환경조절모듈이 농작물 시설하우스 내 창 개폐수단, 조명조절수단, 난방수단, CO2 공급수단, 광차폐수단, 천연추출물 제공수단 및 습도조절수단을 포함하는 환경조절수단이 동작하였을 때 예상되는 농작물 시설하우스 내 예상환경정보를 예측하는 환경예측단계; 상기 환경예측단계의 예상환경정보를 사용자 단말기로 전송하는 환경정보제공 단계; 사용자 단말기로부터 음성인식 신호를 수신하여 수신된 신호를 제어부에 전달하고, 미리 정해 놓은 시간 내에 사용자 단말기로부터 수신된 제어신호가 없으면, 의사결정모듈이 상기 환경조절모듈로부터 환경정보를 수신하여 생육작물의 이상적인 환경정보와 매칭시킨 뒤 미리 정해놓은 기준에 따라 제어동작에 의사결정을 하는 의사결정단계; 제어부에서 상기 의사결정모듈에서 제어정보를 수신하여 상기 환경조절수단을 제어하는 제어단계; 상기 제어단계 이후에 미리 정해놓은 시간 간격에 따라 상기 환경센서로부터 수집된 환경정보를 제어부로 전달하는 제2 환경정보 센싱단계를 포함하는 것이다. claims: 미리 정해놓은 시간 간격에 따라 제1 농작물 시설하우스 내부 또는 외부에 설치된 대기온도센서, 지온온도센서, 습도센서, 일사량 측정 센서, CO2 센서를 포함하는 환경센서로부터 수집된 환경정보를 제어부로 전달하는 제1 환경정보 센싱단계;환경조절모듈이 농작물 시설하우스 내 창 개폐수단, 조명조절수단, 난방수단, CO2 공급수단, 광차폐수단, 천연추출물 제공수단 및 습도조절수단을 포함하는 환경조절수단이 동작하였을 때 예상되는 농작물 시설하우스 내 예상환경정보를 예측하는 환경예측단계;상기 환경예측단계의 예상환경정보를 사용자 단말기로 전송하는 환경정보 제공단계;사용자 단말기로부터 음성인식 신호를 수신하여 수신된 신호를 제어부에 전달하고, 미리 정해 놓은 시간 내에 사용자 단말기로부터 수신된 제어신호가 없으면, 의사결정모듈이 상기 환경조절모듈로부터 환경정보를 수신하여 생육작물의 이상적인 환경정보와 매칭시킨 뒤 미리 정해놓은 기준에 따라 제어동작에 의사결정을 하는 의사결정단계;제어부에서 상기 의사결정모듈에서 제어정보를 수신하여 상기 환경조절수단을 제어하는 제어단계;상기 제어단계 이후에 미리 정해놓은 시간 간격에 따라 상기 환경센서로부터 수집된 환경정보를 제어부로 전달하는 제2 환경정보 센싱단계를 포함하는음성인식을 이용한 스마트팜의 제어방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

819/1059 Row 819: application_number: 1020210005447, combined_string: invention_title: 영농 시스템 및 농작업기 abstract: 농작 구획마다 실시되는 농작업의 내용을 비용을 포함시켜 기록하고, 실적 베이스에서 다음 농작업 계획을 세울 수 있는 영농 시스템을 제공한다.영농 시스템은, 농작지를 농작 구획마다 관리하는 농작 구획 관리부(41)와, 농작지에 계시적으로 실시되는 농작업을 나타내는 농작업 이벤트를 그 비용과 함께 농작 구획마다 관리하는 농작업 관리부(42)와, 실시된 농작업 이벤트의 내용과 비용을 농작업 실적으로서 기록하는 데이터 기록부(5)와, 농작업 이벤트의 내용과 비용을 포함하는 농작업 이벤트의 이력을 농작업 실적표로서 출력하기 위한 실적 출력 데이터를 생성하는 실적 출력 데이터 생성부(43)와, 농작업 실적에 기초하여, 계시적으로 실시되어야 할 농작업 이벤트를 표시한 농작업 계획서를 출력하기 위한 계획 출력 데이터를 생성하는 계획 출력 데이터 생성부(44)를 구비하고 있다. claims: 복수의 농작 구획으로 구분된 농작지를, 상기 농작 구획마다 관리하는 농작 구획 관리부와,상기 농작 구획별 농작물의 수득량 데이터 및 식미 데이터가 입력되는 데이터 입력부와,상기 데이터 입력부를 통해 취득한 수득량 데이터 및 식미 데이터를 대응하는 농작 구획에 할당하여 데이터 기록부에 기록하는 수확 평가 관리부와,과거의 시비 작업 계획과 상기 수득량 데이터 및 상기 식미 데이터에 기초하여 시비 작업 계획을 출력하는 계획 출력 데이터 생성부를 구비하고,상기 시비 작업 계획을 표시하는 모니터를 구비하고,상기 모니터는 포장별 수득량과 식미를 표시하는 표시 화면을 표시할 수 있으며, 선택된 농작 구획을 나타내는 포장 정보와 상기 선택된 농작 구획에서의 농작물의 수득량 및 식미를 나타내는 그래프가 상기 표시 화면에 각각 표시되는, 영농 시스템., Ltext: 농업, prediction: 농업
820/1059 Row 820: application_number: 1020200126832, combined_string: invention_title: 기상요인을 고려한 북미 지역의 대두 수확량 예측 방법 abstract: 본 발명은 기상 자료 및 위성 자료를 이용하여 대두의 수율을 추정하고, 이를 기반으로 전체 대두의 수확량을 산정하는 기술에 관한 기술로, 기상 환경에 따른 작물의 수확량을 산출할 수 있는 바, 작황에 따른 가격 등락의 분석으로 생산량 변동에 따른 대책을 수립할 수 있는 효과가 있는 기술이다. claims: 추세 산출 모듈이 대두 수율() 및 대두 수율의 추세()를 산출하는 대두 수율의 추세 산정 단계(S1);상기 대두 수율의 추세 산정 단계에서 산출된 대두 수율()에서 농경 기술 발달에 따른 추세주기 성분()를 제거하고, 기상 요인에 따른 불규칙 성분인 변동 성분()을 추세 제거 모듈이 산출하는 대두 수율의 추세 제거 단계(S2); 미국 농무부에서 제공하는 ASD(Agricultural Statistics District) 단위별 CDL(Cropland Layer Data) 자료의 대두 재배 지역()과, 강수량, 최저기온, 일교차를 포함하는 기상 자료 및 위성 자료의 단위 면적당 시공간을 일치화하여, 평균하여 대상 해의 단위 면적당 대두의 수율을() 수율 예측 모듈이 예측하는 대두 수율 예측 단계(S3);상기 대두 수율의 예측 단계(S3)에서 예측된 대상 해의 단위 면적당 대두의 수율()과 대두 재배 지역으로 대두의 수확량을 수확량 추정 모듈이 추정하는 연간 대두 수확량 추정 단계(S4); 및상기 연간 대두 수확량 추정 단계(S4)에서 추정된 대두의 수확량을 미국 농무부에서 제공하는 직전 년도로부터 6년간의 경작 빈도 중, 대두의 경작 횟수가 1회 또는 2회인 지역 전체에서 대두가 경작될 때의 연간 총 수확량()과, 대두의 경작 횟수가 3회 이상 6회 이하인 지역 전체에서 대두가 경작될 때의 연간 총 수확량()의 앙상블 가중 평균하는 다음의 수학식으로 수확량 산출 모듈이 연간 대두의 총 수확량()을 산출하는 연간 대두의 수확량 산출 단계(S5);를 포함하고,상기 연간 대두의 총 수확량()은의 수학식으로 산출되고,여기서, 는 t년도의 대두 총 수확량, 는 대두의 경작 횟수가 1회 또는 2회인 지역 전체에서 대두가 경작될 때의 연간 총 수확량, 는 대두의 경작 횟수가 3회 이상 6회 이하인 지역 전체에서 대두가 경작될 때의 연간 총 수확량, 는 대두의 경작 횟수가 1회 또는 2회인 지역 전체에서 대두가 경작될 때의 대두 파종 면적, 는 대두의 경작 횟수가 3회 이상 6회 이하인 지역 전체에서 대두가 경작될 때의 대두 파종 면적, 은 상기 대두 수율의 추세 산정 단계(S1)의 대두 수율의 추세()에 대한 상관 계수()의 제곱값이 하위 20%인 ASD 개수()의 평균()이며,상기 대두 수율의 추세 산정 단계(S1)에서 추정하는 상기 대두 수율의 추세()는 최근 10년의 통계를 활용하여 추정하고,상기 대두 수율의 추세 제거 단계(S2)의 추세주기 성분()는 0으로 판단하며,상기 대두 수율의 추세 제거 단계(S2)의 상기 불규칙 성분인 변동 성분()은의 수학식으로 산출되고,여기서, 는 파종 이후부터 예측 시점까지의 16일 간격 순번이고, 는 번째 16일간의 일 최고 기온의 평균, 는 번째 16일간의 일 최저 기온의 평균, 는 번째 16일간의 일 누적 강수량의 평균, 는 번째 16일간의 위성관측 NDVI의 관측값, , , , , 는 회귀 계수, 는 잔차(Residual)인 기상요인을 고려한 북미 지역의 대두 수확량 예측 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

821/1059 Row 821: application_number: 1020200119709, combined_string: invention_title: 센서박스 및 제어박스를 다채널로 구성할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 센서박스 및 제어박스를 다채널로 구성할 수 있는 스마트팜 운영 시스템은, 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서 및, 센서 송수신부를 포함하는 복수의 센서박스; 제어정보를 기반으로 상기 시설장비를 작동시키는 제어부 및 제어 송수신부를 포함하는 복수의 제어박스; 센서 송수신부 및 상기 제어 송수신부와 다중통신 방식으로 통신하여 상기 환경정보 및 상기 제어정보를 송수신하되, 상기 복수의 센서박스 및 상기 복수의 제어박스를 각각에 부여된 식별정보로 구분하는 게이트웨이 박스; 및 상기 게이트웨이 박스와 신호 연결되어 상기 환경정보 및 제어정보를 수신하여 저장하는 정보서버;를 포함한다. claims: 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서 및, 센서 송수신부를 포함하는 복수의 센서박스;제어정보를 기반으로 상기 시설장비를 작동시키는 제어부 및 제어 송수신부를 포함하는 복수의 제어박스;센서 송수신부 및 상기 제어 송수신부와 다중통신 방식으로 동시에 통신하여 상기 환경정보 및 상기 제어정보를 송수신하되, 상기 복수의 센서박스 및 상기 복수의 제어박스를 각각에 부여된 식별정보로 구분하는 게이트웨이 박스; 및상기 게이트웨이 박스와 신호 연결되어 상기 환경정보 및 제어정보를 수신하여 저장하는 정보서버;를 포함하는 센서박스 및 제어박스를 다채널로 구성할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: 임업
822/1059 Row 822: application_number: 1020200045662, combined_string: invention_title: 태양광 발전장치의 기초 구조물 abstract: 본 발명은 태양광 발전장치에 관한 것으로, 더욱 상세하게는 벼농사를 짓는 농지에 설치하여 태양광 발전을 할 수 있도록 하는 영농형 태양광 발전장치의 기초 구조물에 관한 것이다.본 발명의 실시예에 따른 영농형 태양광 발전장치의 기초 구조물는 벼농사를 위한 농지에 설치되는 영농형 태양광 발전장치의 기초 구조물에 있어서, 태양광발전패널; 상기 태양광발전패널을 고정하여 장착하기 위한 고정프레임; 상기 고정프레임을 상기 농지에 고정하기 위한 기초볼트유닛; 및 상기 고정프레임과 상기 기초볼트유닛을 연결하기 위한 연결프레임;을 포함하여 구성되고, 상기 태양광발전패널의 전체 면적은 상기 농지의 전체 면적 대비 70% 이하이고, 상기 태양광발전패널이 상기 고정프레임에 설치되는 높이는 상기 농지의 지면으로부터 2미터 이상이며, 상기 기초볼트유닛은 지지부 및 스크류부로 구성되고, 상기 지지부에는 상기 농지에 고여있는 물에 의한 부식을 방지하기 위한 부식방지부를 포함하는 것을 특징으로 한다.본 발명에 따르면, 기초볼트유닛이 농지에 고여있는 물에 의해 부식되지 않기 때문에 기초볼트유닛의 부식에 의해 태양광 발전장치 구조물의 안전에 문제가 발생하는 것을 방지할 수 있다는 있다. claims: 벼농사를 위한 농지에 설치되는 영농형 태양광 발전장치의 기초 구조물에 있어서,태양광발전패널(100);상기 태양광발전패널을 고정하여 장착하기 위한 것으로, 하부에 원통형 케이스 연결체(210)가 설치되고, 원통형 케이스 연결체(210)의 끝단에는 양측이 경사진 결합용 돌기(210a)가 설치되어 이루어지는 고정프레임(200);상기 고정프레임을 상기 농지에 고정하기 위한 기초볼트유닛(400); 및상기 고정프레임과 상기 기초볼트유닛을 연결하기 위한 연결프레임(300);을 포함하여 구성되고,상기 태양광발전패널의 전체 면적은 상기 농지의 전체 면적 대비 70% 이하이고,상기 태양광발전패널이 상기 고정프레임에 설치되는 높이는 상기 농지의 지면으로부터 2미터 이상이며,상기 기초볼트유닛은 지지부 및 스크류부로 구성되고, 상기 지지부에는 상기 농지에 고여있는 물에 의한 부식을 방지하기 위한 부식방지부를 포함하고;상기 연결 프레임(300)은,최외각에 설치되는 제 1 결합용 몸체(310)와;상기 제 1 결합용 몸체와 일정거리 이격되어 설치되어 공간부를 형성하여 공간부로 결합용 돌기가 진입되도록 하고, 일단에 결합용 홈을 형성하여 결합용 돌기가 삽입 고정되도록 하는 제 2 결합용 몸체(320)와;상기 제 1 결합용 몸체와 제 2 결합용 몸체 사이에 설치되는 제 1 스프링(330)과;상기 제 1 스프링 전단에 설치되어 제 1 결합용 몸체의 결합용 돌기가 진입하면 후퇴하여 제 1 스프링을 압박하고 결합용 돌기가 제 2 결합용 몸체의 결합용 홈에 삽입되면 제 1 스프링의 탄발에 의해 전진하여 결합용 돌기 상부에 위치되는 제 1 스프링 유동부(350)와;상기 제 1 스프링 유동부 후단에 설치되며 탄발 기능을 갖는 제 2 스프링(340)과;상기 제 2 스프링의 외측에 설치되어 제 2 스프링을 구동하는 원통형 형상의 구조체로서 뒤로 후퇴하면서 제 2 스프링을 구동하기 위한 제 2 스프링 유동부(360)와;상기 제 2 스프링의 후단에 설치되어 제 2 스프링의 움직임을 지지하기 위한 제 2 스프링 지지부(370)를 포함하여 구성함을 특징으로 하는 태양광 발전장치의 기초 구조물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

823/1059 Row 823: application_number: 1020200042452, combined_string: invention_title: 농업용 집단 드론 제공 시스템 abstract: 본 발명은 단말기가 드론 서비스를 제공받기 위해 접속하도록 하고, 상기 단말기로부터 드론 서비스의 제공을 위해 필요한 정보를 제공받는 서비스제공시스템; 상기 서비스제공시스템으로부터 상기 정보를 제공받고, 상기 정보에 따른 드론제어정보를 제공하며, 여러 지역에 분포하는 다수의 드론스테이션; 및 상기 드론스테이션 각각에 다수로 배치되고, 상기 드론제어정보에 상응하는 동작을 수행하는 드론;을 포함하도록 한 농업용 집단 드론 제공 시스템에 관한 것이다.본 발명에 따르면, 드론의 집단적인 사용을 가능하도록 하여, 드론의 효용성을 높일 수 있고, 넓은 지역에서의 드론을 효율적으로 사용하기 위한 신뢰성 높은 네트워크의 형성을 가능하도록 함으로써 드론 서비스의 질적인 향상을 가져올 수 있으며, 그 중요성이 점차 확대되고 있는 농업분야에 직접 적용됨으로써 활용도를 높일 수 있다. claims: 단말기가 농업에 필요한 드론 서비스를 제공받기 위해 접속하도록 하고, 상기 단말기로부터 드론 서비스의 제공을 위해 필요한 정보를 제공받는 서비스제공시스템;상기 서비스제공시스템으로부터 상기 정보를 제공받고, 상기 정보에 따른 드론제어정보를 제공하며, 여러 지역에 분포하는 다수의 드론스테이션; 및상기 드론스테이션 각각에 다수로 배치되고, 상기 드론제어정보에 상응하는 동작을 수행하는 드론;을 포함하고, 상기 서비스제공시스템은,상기 단말기가 무선통신망을 통해서 접속하기 위한 웹페이지를 제공하고, 상기 웹페이지를 통해서 상기 단말기로부터 드론을 이용한 작업장소 및 작업목적에 대한 정보를 제공받는 웹서버;상기 웹서버로부터 상기 작업장소 및 작업목적을 제공받고, 상기 드론스테이션에 대한 작업장소까지 거리와 드론 가동대수를 고려하여, 상기 작업목적의 수행을 위해 드론스테이션에 대한 드론의 사용대수 및 이동경로를 산출하는 드론산출부;상기 드론산출부에 의해 산출되는 드론의 사용대수를 해당하는 드론스테이션에게 해당 드론 각각의 이동경로와 함께 제공하는 드론할당부; 및 상기 드론산출부에 산출을 위해 필요한 데이터를 제공하도록 저장하는 데이터베이스부;를 포함하고,상기 드론스테이션은,상기 드론할당부로부터 드론의 사용대수를 제공받은 경우, 해당하는 사용대수의 드론 각각이 제공받은 이동경로를 따라 정해진 작업목적을 수행하도록 설정하는, 농업용 집단 드론 제공 시스템., Ltext: 농업, prediction: 농업
824/1059 Row 824: application_number: 1020200030500, combined_string: invention_title: 영농형 스마트 태양광 발전 시스템 abstract: 본 발명은 영농형 스마트 태양광 발전 시스템에 관한 것으로서, 더욱 상세하게는 고정식 구조물에 복수의 회전식 태양광 패널을 설치하되, 링크부를 통해 복수의 태양광 패널이 일률적으로 회전될 수 있도록 설치하고, 고정식 구조물에 작업발판을 설치함으로써, 경작지 공간 효율성을 높여 경작지에 일조량이 충분히 확보될 수 있도록 하고, 태양광 패널 유지 보수 작업에 대한 효율성을 높인 영농형 스마트 태양광 발전 시스템에 관한 것이다.이를 위해, 경작지로부터 상방으로 고정된 지주; 상기 지주의 상단부에 설치된 탑프레임; 상기 탑프레임을 따라 탑프레임에 대하여 수직한 방향으로 설치된 복수의 지지프레임; 상기 각 지지프레임에 등간격으로 복수로 설치되며, 태양광을 따라 회전될 수 있도록 설치된 태양광 패널; 상기 복수의 태양광 패널을 동시에 연동시키는 링크부; 및 상기 링크부를 구동시켜 복수의 태양광 패널이 동시에 일방향으로 움직일 수 있도록 한 구동부:를 포함하며, 상기 링크부는, 상기 탑프레임을 따라 설치되며, 양단부는 상기 지지프레임에 축 결합된 메인축; 상기 지지프레임마다 각 지지프레임에 대응되게 마련된 복수의 연결로드; 상기 메인축과 상기 각각의 연결로드 사이에 설치되며, 상기 메인축의 회전운동을 상기 연결로드의 왕복운동으로 가변시키는 연동브라켓; 상기 연결로드와 상기 태양광 패널 사이에 설치되며, 상기 연결로드의 왕복운동을 태양광 패널의 회전운동으로 가변시키는 가변수단:을 포함하는 영농형 스마트 태양광 발전 시스템을 제공한다. claims: 경작지로부터 상방으로 고정된 지주;상기 지주의 상단부에 설치된 탑프레임;상기 탑프레임을 따라 탑프레임에 대하여 수직한 방향으로 설치된 복수의 지지프레임;상기 각 지지프레임에 등간격으로 복수로 설치되며, 태양광을 따라 회전될 수 있도록 설치된 태양광 패널;상기 복수의 태양광 패널을 동시에 연동시키는 링크부; 및상기 링크부를 구동시켜 복수의 태양광 패널이 동시에 일방향으로 움직일 수 있도록 한 구동부:를 포함하며,상기 링크부는,상기 탑프레임을 따라 설치되며, 양단부는 상기 지지프레임에 축 결합된 메인축;상기 지지프레임마다 각 지지프레임에 대응되게 마련된 복수의 연결로드;상기 메인축과 상기 각각의 연결로드 사이에 설치되며, 상기 메인축의 회전운동을 상기 연결로드의 왕복운동으로 가변시키는 연동브라켓;상기 연결로드와 상기 태양광 패널 사이에 설치되며, 상기 연결로드의 왕복운동을 태양광 패널의 회전운동으로 가변시키는 가변수단:을 포함하는 영농형 스마트 태양광 발전 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

825/1059 Row 825: application_number: 1020200001233, combined_string: invention_title: 영농 시스템 abstract: 과거에 행해진 농작업에 관한 데이터가 없어도, 가능한 한 효과적인 포장 작업 계획을 작성할 수 있는 영농 시스템을 제공하는 것이다. 영농 시스템은, 각 포장의 포장 특성 파일, 포장 작업 이력 파일, 포장 수확 파일을 포함하는 포장 파일을 저장하는 포장 파일 저장부(51)와, 포장 파일을 사용하여 지정 포장의 포장 작업 계획을 작성하는 작업 계획 작성부(52)와, 지정 포장을 위한 포장 파일이 포장 파일 저장부(51)에 저장되어 있지 않은 경우, 지정 포장을 위한 모의 포장 파일을 작성하여 작업 계획 작성부(52)에 부여하는 모의 파일 작성부(53)를 구비한다.또한, 예상 작업 실적과 실제 작업 실적 사이의 상이를 간단하게 평가할 수 있는 영농 시스템을 제공하는 것이다. 영농 시스템은, 구획별 포장 작업의 계획을 나타내는 작업 계획 맵을 작성하는 작업 계획 맵 작성부(1052)와, 작업 계획 맵에 기초하여 포장 작업의 시뮬레이션을 행하여 당해 시뮬레이션의 결과로서의 작업 예측 맵을 작성하는 작업 예측 맵 작성부(1053)와, 포장 작업을 실시한 포장 작업기에 의해 생성된 작업 데이터에 기초하여 작업 실적 맵을 작성하는 작업 실적 맵 작성부(1054)와, 작업 계획 맵, 작업 예측 맵, 작업 실적 맵 중 어느 것, 또는 전부를 상호 비교 가능하게 디스플레이(1058)에 표시하는 표시 제어부(1055)를 구비한다. claims: 포장 작업기에 의한 포장 작업을 관리하는 영농 시스템이며,각 포장의 포장 특성 파일, 포장 작업 이력 파일, 포장 수확 파일을 포함하는 포장 파일을 저장하는 포장 파일 저장부와,상기 포장 파일을 사용하여 지정 포장의 포장 작업 계획을 작성하는 작업 계획 작성부와, 상기 지정 포장을 위한 상기 포장 파일이 상기 포장 파일 저장부에 저장되어 있지 않은 경우, 상기 지정 포장을 위한 모의 포장 파일을 작성하여 상기 작업 계획 작성부에 부여하는 모의 파일 작성부를 구비한, 영농 시스템.포장 작업기를 사용하여 복수의 구획으로 구분된 포장을 관리하는 영농 시스템이며,상기 구획별로 포장 작업의 계획을 나타내는 작업 계획 맵을 작성하는 작업 계획 맵 작성부와,상기 작업 계획 맵에 기초하여 상기 포장 작업의 시뮬레이션을 행하여 당해 시뮬레이션의 결과로서의 작업 예측 맵을 작성하는 작업 예측 맵 작성부와,상기 포장 작업을 실시한 포장 작업기에 의해 생성된 작업 데이터에 기초하여 작업 실적 맵을 작성하는 작업 실적 맵 작성부와,상기 작업 계획 맵, 상기 작업 예측 맵, 상기 작업 실적 맵 중 어느 것, 또는 전부를 상호 비교 가능하게 디스플레이에 표시하는 표시 제어부를 구비한, 영농 시스템., Ltext: 농업, prediction: 농업
826/1059 Row 826: application_number: 1020190176274, combined_string: invention_title: 기상정보를 이용한 토양수분 예측 시스템 abstract: 본 명세서는 토양수분 예측 시스템을 개시한다. 본 발명의 일 실시예에 따르면, 토양수분 예측 시스템은 농지에 설치되어 토양수분 데이터를 수집하는 토양수분 감지센서(110); 상기 농지에 설치되어 기상정보 데이터를 수집하며, 상기 토양수분 감지센서(110)로부터 상기 토양수분 데이터를 수신하는 기상관측장비(120); 상기 기상관측장비(120)로부터 상기 토양수분 데이터 및 상기 토양수분 데이터를 수신하고 이를 분석하여 토양수분 예측 모델을 도출하며, 기상청 서버(200)로부터 동네 예보 정보를 수신하고 상기 예측 모델을 적용하여 상기 동네 여보 정보에 상응하는 토양수분 예측값을 산출하는 시스템 서버(130); 및 상기 시스템 서버(130)로부터 상기 토양수분 예측값을 전송받는 사용자 단말기(140);를 포함한다. claims: 농지에 설치되어 토양수분 데이터를 수집하는 토양수분 감지센서(110);상기 농지에 설치되어 기상정보 데이터를 수집하며, 상기 토양수분 감지센서(110)로부터 상기 토양수분 데이터를 수신하는 기상관측장비(120);상기 기상관측장비(120)로부터 상기 토양수분 데이터 및 상기 토양수분 데이터를 수신하고 이를 분석하여 토양수분 예측 모델을 도출하며, 기상청 서버(200)로부터 동네 예보 정보를 수신하고 상기 예측 모델을 적용하여 상기 동네 여보 정보에 상응하는 토양수분 예측값을 산출하는 시스템 서버(130); 및상기 시스템 서버(130)로부터 상기 토양수분 예측값을 전송받는 사용자 단말기(140);를 포함하는,토양수분 예측 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

827/1059 Row 827: application_number: 1020190170467, combined_string: invention_title: 영농형 태양광 발전장치 abstract: 본 발명은 영농형 태양광 발전장치에 관한 것이다. 이는, 지지력을 제공하는 지지구조체와; 상기 지지구조체에 위치조절 가능하게 설치되며, 태양광을 받아 전력을 생산하는 다수의 불투명태양광패널 및 투명태양광패널을 포함하는 전력생산부와; 상기 불투명태양광패널의 위치를 조절하는 제1패널위치조절부와; 상기 투명태양광패널의 위치를 조절하는 제2패널위치조절부와; 상기 제1,2패널위치조절부를 제어하는 컨트롤러와; 외부의 기상데이터서버로부터 기상상황을 전달받고, 전달받은 기상 상황에 대응하는 제어신호를 컨트롤러로 전송하는 관리자서버를 구비한다.상기와 같이 이루어지는 본 발명의 영농형 태양광 발전장치는, 투명패널과 불투명패널의 이중 구조를 가져, 기상 상황에 따라 투명패널과 불투명패널을 선택적으로 사용할 수 있어 전기에너지의 생산 효율이 양호하고 전력을 생산하면서도 차광을 방지할 수 있다. 또한, 재배작물에 필요한 최적 차광률을 데이터베이스화 하여 작물에 따라 발전시간을 조절할 수 있다. 아울러, 사용자가 외부의 기상데이터서버와 접속하여, 기상정보에 기초한 패널 각도를 조절을 통해, 작물의 성장에 필요한 최적 일사량을 제공할 수 있다. claims: 지지력을 제공하는 지지구조체와;상기 지지구조체에 위치조절 가능하게 설치되며, 태양광을 받아 전력을 생산하는 다수의 불투명태양광패널 및 투명태양광패널을 포함하는 전력생산부와;상기 불투명태양광패널의 위치를 조절하는 제1패널위치조절부와;상기 투명태양광패널의 위치를 조절하는 제2패널위치조절부와;상기 제1,2패널위치조절부를 제어하는 컨트롤러와;외부의 기상데이터서버로부터 기상상황을 전달받고, 전달받은 기상 상황에 대응하는 제어신호를 컨트롤러로 전송하는 관리자서버를 구비하는 영농형 태양광 발전장치., Ltext: 농업, prediction: 임업
828/1059 Row 828: application_number: 1020190168707, combined_string: invention_title: 농작물의 소득 예측시스템 및 그의 예측방법 abstract: 본 발명은 농작물을 생산하기 전에 통계 데이터들 및 투입된 인프라 등의 정보를 입력받아 생산량을 예측하고, 이를 수치로 환산하여 생산자나 기관이 얻게 될 예상 수익 등의 경작 계획을 컨설팅 가능하게 하는 농작물의 소득 예측시스템 및 이러한 예측 시스템을 이용한 소득 예측방법에 관한 것이다. 본 발명은 기후정보 및 농작물 생산량을 입력받고 농작물 생산량의 예측정보를 산출하는 제1 예측부와, 재배 비용 정보와 농작물 가격정보를 입력받고 농작물 가격 예측정보를 산출하는 제2 예측부, 재배 비용 정보와 소비자 물가 지수(Consumer Price Index)를 입력받고 재배비용정보를 산출하는 제3 예측부, 상기 농작물 생산량 예측정보와 농작물 가격 예측정보를 이용하여 판매정보를 연산하는 제1 연산부, 및 상기 판매정보와 재배 비용정보를 이용하여 단위면적당 농작물의 순이익 정보를 연산하는 제2 연산부를 포함하며, 예측과정은 기계학습을 통해 반복학습하게 된다. claims: 기후정보 및 농작물 생산량을 입력받고 농작물 생산량의 예측정보를 산출하는 제1 예측부; 재배비용 정보와 농작물 가격정보를 입력받고 농작물 가격 예측정보를 산출하는 제2 예측부; 재배 비용 정보와 소비자 물가 지수(Consumer Price Index)를 입력받고 재배비용정보를 산출하는 제3 예측부; 상기 농작물 생산량 예측정보와 농작물 가격 예측정보를 이용하여 판매정보를 연산하는 제1 연산부; 및 상기 판매정보와 재배 비용정보를 이용하여 단위면적당 농작물의 순이익 정보를 연산하는 제2 연산부를 포함하는 것을 특징으로 하는 농작물의 소득 예측시스템.지역별 강수량 및 온도 정보, 그리고 농작물 생산정보를 이용한 농작물 생산량, 농작물의 재배 비용 정보와 농작물 가격정보를 이용한 농작물 가격, 재배 비용 정보와 소비자 물가 지수(Consumer Price Index)를 이용한 재배 비용정보를 각각 예측하는 예측단계; 상기 예측된 농작물의 생산량정보와 농작물 가격정보를 이용하여 농산물의 판매정보를 연산하는 제1 연산단계; 및 상기 농산물의 판매정보와 재배 비용 정보를 이용하여 단위면적당 농작물의 순이익 정보를 연산하는 제2 연산단계를 포함하는 것을 특징으로 하는 농작물의 소득 예측방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

829/1059 Row 829: application_number: 1020190165210, combined_string: invention_title: 클라우드 기반 주간 온실 환경 의사결정지원 서버 및 이를 이용한 주간 온실 환경 의사결정지원 시스템 abstract: 본 발명의 일 실시예에 따른 주간 온실 환경 의사결정지원 서버는 작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단부; 작물 생육상을 기반으로 온실 환경 제어 요소를 결정하는 환경 제어 요소 결정부; 데이터 베이스로부터 작물에 대한 선도 농가 월별 데이터를 수신하는 과거 데이터 수신부; 기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신부; 주간 기상 예보 데이터와 선도 농가 월별 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교부; 및 온도 차 및 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정부를 포함한다. claims: 작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단부;상기 작물 생육상을 기반으로 환경 제어 요소를 결정하는 환경 제어 요소 결정부;데이터 베이스로부터 상기 작물에 대한 과거 기상 데이터와, 이에 대응되는 선도 농가의 과거 온실 데이터를 포함하는 과거 데이터를 수신하는 과거 데이터 수신부;기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신부;상기 주간 기상 예보 데이터와 상기 과거 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교부; 및상기 온도 차 및 상기 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정부를 포함하는 주간 온실 환경 의사결정지원 서버.작물 영상을 촬영하는 작물 영상 촬영 장치;과거 기상 데이터와, 이에 대응되는 선도 농가의 과거 온실 데이터를 포함하는 과거 데이터가 작물의 품목별로 저장되는 데이터 베이스;온실에 제공되어, 온실 데이터를 감지하는 온실 센서;상기 작물 영상 촬영 장치, 상기 데이터 베이스, 및 상기 온실 센서와 데이터 송수신을 통해 주간 환경 제어값을 산출하는 주간 온실 환경 의사결정지원 서버; 및상기 주간 온실 환경 의사결정지원 서버로부터 수신되는 상기 주간 환경 제어값을 기초로 온실 환경을 제어하는 온실 제어기를 포함하며,상기 주간 온실 환경 의사결정지원 서버는,작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단부;상기 작물 생육상을 기반으로 환경 제어 요소를 결정하는 환경 제어 요소 결정부;상기 데이터 베이스로부터 상기 작물에 대한 상기 과거 데이터를 수신하는 과거 데이터 수신부;기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신부;상기 주간 기상 예보 데이터와 상기 과거 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교부; 및상기 온도 차 및 상기 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정부를 포함하는 주간 온실 환경 의사결정지원 시스템.작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단 단계;상기 작물 생육상을 기반으로 환경 제어 요소를 결정하는 환경 제어 요소 결정 단계;데이터 베이스로부터 상기 작물에 대한 과거 기상 데이터와, 이에 대응되는 선도 농가의 과거 온실 데이터를 포함하는 과거 데이터를 수신하는 과거 데이터 수신 단계;기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신 단계;상기 주간 기상 예보 데이터와 상기 과거 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교 단계; 및상기 온도 차 및 상기 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정 단계를 포함하는 주간 온실 환경 의사결정지원 방법.주간 온실 환경 의사결정지원 방법을 실행하기 위한 프로그램을 포함하는 컴퓨터 판독가능 기록매체에 있어서,상기 주간 온실 환경 의사결정지원 방법은,작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단 단계;상기 작물 생육상을 기반으로 환경 제어 요소를 결정하는 환경 제어 요소 결정 단계;데이터 베이스로부터 상기 작물에 대한 과거 기상 데이터와, 이에 대응되는 선도 농가의 과거 온실 데이터를 포함하는 과거 데이터를 수신하는 과거 데이터 수신 단계;기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신 단계;상기 주간 기상 예보 데이터와 상기 과거 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교 단계; 및상기 온도 차 및 상기 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정 단계를 포함하는 컴퓨터 판독가능 기록매체., Ltext: 농업, prediction: 임업
830/1059 Row 830: application_number: 1020190153904, combined_string: invention_title: 관리로봇을 이용한 인공지능 기반의 버섯 재배관리 시스템 abstract: 본 발명은 스마트팜 재배기능과 관리로봇의 자율주행 기능을 이용하여 관리 인건비를 줄여 고부가가치의 버섯을 재배하는 발명에 관한 것으로, 자율주행 기능에 의해 관리로봇이 버섯의 생장상태를 주기적으로 촬영하면, 생장환경통합관리부는 머신러닝 기술을 기반으로 촬영된 버섯의 영상정보를 분석하여 버섯의 생장상태를 판단하고 필요한 작업 이벤트 정보를 사용자단말기로 전송하여 사용자에게 전달하도록 하는 발명이다. claims: 관리로봇을 이용한 인공지능 기반의 버섯 재배관리 시스템에 있어서,버섯을 재배하기 위한 실내공간(110)이 형성되고, 상기 실내공간(110)에는 버섯이 재배되는 복수의 재배단(120)들이 배치되고, 상기 실내공간(110)에는 버섯 재배에 필요한 환경을 조성하는 환경조성수단(130)이 배치되는 재배실(100)과;상기 재배실(100)의 실내공간(110)에서 자율주행으로 이동하며, 재배실(100)내의 환경정보를 감지하여 생장환경통합관리부(300)로 전송하고, 복수의 재배단(120)에서 재배되는 버섯들을 촬영한 버섯의 생장상태 영상정보를 생장환경통합관리부(300)로 전송하는 관리로봇(200)과;상기 관리로봇(200)이 전송한 재배실(100)의 환경정보를 이용해 재배실(100)이 버섯 재배에 적정한 환경이 되도록 재배실(100)에 배치된 환경조성수단(130)을 제어하고, 관리로봇(200)이 전송한 버섯의 생장상태 영상정보를 이용해 버섯의 생장상태를 분석 파악하여 재배단별 버섯생장 상태정보와 재배단별 작업 이벤트 정보를 생성하고, 생성된 재배단별 작업 이벤트 정보를 사용자단말기(400)로 전송하는는 생장환경통합관리부(300))와;버섯 수확이나 부패에 관한 작업 이벤트 정보를 사용자에게 출력 표시하는 사용자단말기(400)를 포함하며,상기 관리로봇(200)은 생장환경통합관리부(300)로 환경정보를 전송 시, 해당 재배실(100)의 고유 아이디 정보를 환경정보에 매칭 시켜 전송하고, 버섯의 생장상태 영상정보 전송 시, 해당 재배단(120)의 고유 식별 정보를 버섯의 생장상태 영상정보에 매칭 시켜 전송하는 것을 특징으로 하는 관리로봇을 이용한 인공지능 기반의 버섯 재배관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

831/1059 Row 831: application_number: 1020190151404, combined_string: invention_title: 작물 재배면적 추출방법 및 프로그램 abstract: 본 발명은 작물 재배면적 추출방법 및 프로그램에 관한 것으로, 고정밀 드론 공간정보 기술 활용의 작업 과정 단순화, 단순화된 공정을 통한 단시간내 광범위지역 드론촬영, RGB센서와 다중분광센서를 통한 영상정보 획득, 지구별 영상촬영조사 시작점 및 운항경로 제시, 촬영지구별 정사영상 및 3D맵 제작을 통한 작물재배면적 산정과 지구별 지형분석이 처리되는 A) 드론을 활용한 영농현황조사 처리과정, 촬영지구에 대한 전수조사 결과를 프로그램에서 제공하는 현황도에 입력하여 작물재배 현황지도 작성, 지구별 대표지점을 선정하여 농가와 연계하며 파악된 작물의 수확량과 생육상태에 대한 정보 입력, 작물의 전수조사 리스트로서 두 지역 이상 분포하는 작물의 경우 숫자로 표기, 특정 지역에서만 재배되는 작물의 경우 알파벳으로 표기되도록 처리되는 B) 전수조사 처리과정, 및 RGB센서에서 획득한 영상을 통한 재배면적 산정과 대표지역의 AI를 통한 작물종류 분류, 다중분광센서에서 획득한 분광정보를 통해 NDVI 지수를 통해 작물의 생육정보 도식화, 국내외 연구사례 조사를 통한 작물판독 증진방안 제시, 간척농지 영농현황조사에 적합한 가이드라인을 제시하는 방식으로 처리되는 C) 촬영결과를 통한 작물판독 검토방안 처리과정을 포함하는 작물 재배면적 추출 방법 및 프로그램 제공에 따라, 미래의 작물 농업에 대한 제반적인 개발 방안을 효과적으로 제시할 수 있다. claims: 고정밀 드론 공간정보 기술 활용의 작업 과정 단순화, 단순화된 공정을 통한 단시간내 광범위지역 드론촬영, RGB센서와 다중분광센서를 통한 영상정보 획득, 지구별 영상촬영조사 시작점 및 운항경로 제시, 촬영지구별 정사영상 및 3D맵 제작을 통한 작물재배면적 산정과 지구별 지형분석이 처리되는 A) 드론을 활용한 영농현황조사 처리과정;촬영지구에 대한 전수조사 결과를 프로그램에서 제공하는 현황도에 입력하여 작물재배 현황지도 작성, 지구별 대표지점을 선정하여 농가와 연계하며 파악된 작물의 수확량과 생육상태에 대한 정보 입력, 작물의 전수조사 리스트로서 두 지역 이상 분포하는 작물의 경우 숫자로 표기, 특정 지역에서만 재배되는 작물의 경우 알파벳으로 표기되도록 처리되는 B) 전수조사 처리과정; 및RGB센서에서 획득한 영상을 통한 재배면적 산정과 대표지역의 AI를 통한 작물종류 분류, 다중분광센서에서 획득한 분광정보를 통해 NDVI 지수를 통해 작물의 생육정보 도식화, 국내외 연구사례 조사를 통한 작물판독 증진방안 제시, 간척농지 영농현황조사에 적합한 가이드라인을 제시하는 방식으로 처리되는 C) 촬영결과를 통한 작물판독 검토방안 처리과정;을 포함하는 것을 특징으로 하는 작물 재배면적 추출 방법.상기 무인기로부터 촬영된 작물 대상지의 영상 정보를 활용하여 작물 종류를 판독하고 상기 영상의 이미지를 편집 수정하여 소정의 표준 데이터로 서버에 저장하는 인공지능 프로그램인 것을 특징으로 하는 작물 재배면적 추출 프로그램., Ltext: 농업, prediction: 농업
832/1059 Row 832: application_number: 1020190151040, combined_string: invention_title: 시설 운영 이력을 저장할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 스마트팜 운영 시스템은, 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서를 포함하고 상기 환경정보를 포함하는 경작지정보를 생성하는 센서박스; 경작자가 상기 경작지정보를 기반으로 상기 재배환경을 조절하기위해 상기 시설장비를 작동시키는 제어정보를 포함하는 경작정보를 입력하는 경작자 단말기; 상기 제어정보를 기반으로 상기 시설장비를 작동시키는 제어박스; 및, 상기 경작지정보 및 상기 경작정보를 상기 작물의 생육단계에 매칭하여 저장하는 저장부를 가지는 정보서버;를 포함한다. claims: 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서를 포함하고 상기 환경정보를 포함하는 경작지정보를 생성하는 센서박스;경작자가 상기 경작지정보를 기반으로 상기 재배환경을 조절하기위해 상기 시설장비를 작동시키는 제어정보를 포함하는 경작정보를 입력하는 경작자 단말기;상기 제어정보를 기반으로 상기 시설장비를 작동시키는 제어박스; 및,상기 경작지정보 및 상기 경작정보를 상기 작물의 생육단계에 매칭하여 저장하는 저장부를 가지는 정보서버;를 포함하고, 상기 경작지정보는, 상기 작물의 이미지를 포함하는 작물정보를 더 포함하고, 상기 경작정보는, 상기 경작자가 상기 작물정보를 기반으로 상기 작물의 생육상태를 규정하는 생육정보를 더 포함하고상기 정보서버는, 상기 경작지정보 및 상기 경작정보를 빅데이터 분석방법으로 분석하여 상기 작물의 최적 생육조건을 위한 상기 시설장비를 작동시키는 최적 제어정보를 예측하여 생성하는 예측하는 예측부;를 더 포함하여,상기 작물을 재배하는 상기 경작자의 경험 및 상기 생육 상태에 따른 상기 최적 제어정보를 디지털 정보로 생성할 수 있고,상기 경작지는, 외부와 격리되어 상기 작물이 재배되는 내부를 가지며,상기 센서박스는,상기 경작지의 외부와 내부 각각의 재배정보를 감지하는 내외부 환경감지유닛 및 상기 경작지 내부의 지중 전기전도도와 산도(Ph)와 함수율 및 온도를 포함하는 내부지중 환경감지유닛을 포함하고, 상기 정보서버는, 상기 저장부에 저장된 상기 경작지정보 및 상기 경작정보를 웹(web)형식의 표시정보로 변환하는 변환부를 포함하고,상기 경작자 단말기는,상기 표시정보를 디스플레이하는 디스플레이부를 포함하고, 상기 경작자 단말기는, 스마트폰, 패드 및 탭을 포함하는 개인용 모바일기기 또는 개인용 컴퓨터(PC) 및 노트북을 포함하는 컴퓨터를 포함하고, 상기 표시정보는,반응형 웹(web)형식의 표시 정보이고,상기 경작지정보 및 상기 제어정보는 정형 데이터(structured data)이고, 상기 생육정보는,비정형 데이터(unstructured data)이며,상기 예측부는,상기 생육정보를 비정형 데이터 마이닝 방법으로 분석하고, 상기 경작지정보 및 상기 제어정보를 정형 데이터 마이닝 방법으로 분석하고, 상기 예측부는, 상기 생육정보를 텍스트 마이닝 기법 및 오피니언 마이닝 기법을 복합적으로 사용하여 분석하여, 상기 작물정보와 상기 작물정보를 기반으로 상기 경작자가 판단한 상기 작물의 생육상태 상호간의 연관성을 도출함으로써, 상기 최적 제어정보에 의한 상기 최적 생육조건의 신뢰성을 더욱 향상시킬 수 있는 시설 운영 이력을 저장할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

833/1059 Row 833: application_number: 1020190151135, combined_string: invention_title: 재배 이력을 추적할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 재배 이력을 추적할 수 있는 스마트팜 운영 시스템은, 작목이 재배되고 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 감지하여 환경정보를 생성하는 환경센서를 포함하는 센서부; 상기 환경정보를 기반으로 상기 시설장비를 작동시키는 제어정보와 상기 작목의 재배정보 및 상기 경작자의 이력정보를 포함하는 경작자정보를 상기 경작자가 입력하는 경작자 단말기; 상기 환경정보와 상기 제어정보와 상기 재배정보 및 상기 경작자정보를 수신하여 생산이력정보로 저장하는 저장부를 가지고 클라우드(cloud) 컴퓨팅을 기반으로 운영되는 정보서버; 상기 작목에서 재배된 농산품을 판매하는 판매처; 및 상기 농산품의 생산이력정보를 상기 정보서버로부터 수신하여 구매자에게 표시하는 구매자 단말기;를 포함한다. claims: 작목이 재배되고 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 감지하여 환경정보를 생성하는 환경센서를 포함하는 센서부;상기 환경정보를 기반으로 상기 시설장비를 작동시키는 제어정보와 상기 작목의 재배정보 및 경작자의 이력정보를 포함하는 경작자정보를 상기 경작자가 입력하는 경작자 단말기;상기 환경정보와 상기 제어정보와 상기 재배정보 및 상기 경작자정보를 수신하여 생산이력정보로 저장하는 저장부를 가지고 클라우드(cloud) 컴퓨팅을 기반으로 운영되는 정보서버;상기 작목에서 재배되어 판매처에서 판매되는 농산품의 생산이력정보를 상기 정보서버로부터 수신하여 구매자에게 표시하는 구매자 단말기;를 포함하고,상기 정보서버는, 상기 농산품이 출하될 때 출하시점과 포장용량과 상기 생산이력정보를 인터넷상에서 검색할 수 있는 좌표정보를 포함하는 고유코드를 생성하여 상기 농산품에 부착하는 재배 이력을 추적할 수 있고,상기 판매처는 상기 농산품이 판매될 때 상기 고유코드가 스캔되면, 상기 농산품의 판매정보를 생성하고,상기 정보서버는 상기 판매정보를 기반으로 하여 상기 농산품의 상기 생산이력정보에 따른 판매량을 포함하는 매출정보를 생성하고,상기 경작자 단말기는 상기 매출정보를 수신하여 상기 경작자에게 표시하고, 상기 구매자 단말기는,상기 구매자가 구매하고자 하는 상기 농산품의 상기 고유코드를 스캔하면 코드 스캔정보를 생성하고, 상기 정보서버에서 상기 코드 스캔정보에 매칭하는 상기 농산품의 상기 생산이력정보를 수신하여 표시하고, 상기 정보서버는,상기 구매자 단말기로부터 상기 농산품의 상기 코드 스캔정보를 수신하면, 상기 농산품에 대한 검색회수를 포함하는 검색정보를 생성하여 상기 농산품에 매칭하여 저장하고,상기 경작자 단말기는, 상기 검색정보를 수신하여 상기 경작자에게 표시하고, 상기 정보서버는,상기 생산이력정보와 상기 매출정보 및 상기 검색정보를 데이터 마이닝 기법으로 분석하여, 상기 농산품의 상기 생산이력정보에 따른 판매량을 포함하는 매출정보 및 상기 검색회수 대비 판매량의 비율인 판매성공률 정보를 생성하는 분석부를 더 포함하고,상기 경작자 단말기는, 상기 매출정보 및 상기 판매성공률 정보를 수신하여 상기 경작자에게 표시하고, 상기 고유코드는 상기 판매처의 위치 및 매장 크기를 포함하는 판매처정보를 포함함으로써, 상기 경작자가 상기 농산품의 상기 매출정보를 상기 판매처별로 관리할 수 있고, 상기 정보서버는,상기 구매자가 관심있는 구매요소를 확인할 수 있도록, 상기 구매자의 상기 구매자 단말기를 이용하여 상기 생산이력정보를 확인할 때, 최종적으로 확인한 생산이력정보의 세부정보를 상기 검색정보에 포함시켜 저장하고,상기 생산이력정보의 세부정보는, 상기 환경정보, 상기 제어정보, 상기 경작자정보 및 상기 재배정보를 포함하는 것을 특징으로 하는, 재배 이력을 추적할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: 임업
834/1059 Row 834: application_number: 1020190150427, combined_string: invention_title: 경작지 관리 시스템 abstract: 본 발명은 경작지의 농업용수에 대한 전반적인 관리를 통해 경작물의 안정성과 고품질 및 고수확성을 확보할 수 있어 물을 이용하여 경작물을 재배하는 논, 수경재배 업종에 적용할 수 있는 경작지 관리 시스템에 관한 것으로, 더욱 상세하게는 작동에 대한 제어와 농업용수에 대한 각종 정보, 농업용수의 정보를 토대로 재배 환경을 개선하는 관리제어부, 상기 관리제어부의 관리를 통해 경작지의 농업용수의 양을 조절하는 용수량조절부로 구성하여; 무선통신을 이용하여 자동화방식으로 전원 및 작동을 제어할 수 있어 관리가 편리한 효과가 있다. claims: 벼를 경작하는 경작지의 농업용수의 양을 조절하기 위한 시스템에 있어서,경작지(1)의 일측에 설치되며 전원공급과 작동을 제어하는 컨트롤부(10);상기 컨트롤부(10)의 하부에는 경작지(1)의 농업용수의 수위, 수소이온농도 및 비료성분을 검출하는 검출부(20);상기 컨트롤부(10)의 하부에는 경작지(1)의 담겨진 농업용수에 산성중화제 및 액상비료를 공급하는 약액부(30)로 이루어지는 관리제어부(40); 및상기 경작지(1)의 타측에는 농업용수 담수양을 조절하도록 상기 관리제어부(40)의 신호를 전달받아 작동하는 용수량조절부(50); 를 형성하여,상기 관리제어부(40) 및 용수량조절부(50)를 개인통신기기(60)를 이용하여 작동 및 제어할 수 있도록 구성하며,상기 약액부(30)는 농업용수가 산성도가 증가할 때 산성도를 낮추기 위한 알카리성약액을 저장하는 약액통(31)에 연결되어 경작지(1)에 약액을 배출하도록 경작지(1)의 바닥에 설치하는 약액호스(32); 및농업용수에 영양분을 공급하기 위한 액상비료를 저장하는 비료통(33)에 연결되어 경작지(1)에 액상비료를 배출하도록 경작지(1)의 바닥에 설치하는 비료호스(34); 를 구성하되, 약액호스(32)와 비료호스(34)를 직교 배치로 설치하여 약액과 비료가 동일 지점에서 배출되는 것이 방지되며,상기 용수량조절부(50)는 농업용수가 흘러갈 수 있는 통로(51)가 중앙에 형성되도록 한 쌍의 측판(52)이 바닥판(57)에 연결된 디귿자 형태이며, 상기 측판(52)의 외측으로 경작지(1)에 매립되는 매립단(53)을 각각 형성하는 배수몸체(54);상기 배수몸체(54)의 통로(51)에는 회전방식으로 농업용수를 차단 및 배수하되, 경작지(1)에 담수된 농업용수의 중량에 의해 개폐시 응력이 집중되지 않도록 단면이 휘어진 사각판 형태의 배수조절판(55); 을 형성하고,상기 배수조절판(55)을 작동시키기 위하여 하나의 측판(52) 외측에 설치하는 모터(56)와 체인(58)으로 연결 형성하며,상기 모터(56) 구동을 위하여 자체적으로 전원을 생산 공급하는 태양광셀(SC); 을 구성하는 것을 특징으로 하는 경작지 관리 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

835/1059 Row 835: application_number: 1020190149900, combined_string: invention_title: 기상요인을 고려한 대두 수확량 예측 방법 abstract: 본 발명은 기상정보를 이용하여 작황 환경을 고려한 수확량을 산출하는 기상요인을 고려한 대두 수확량 예측 방법에 관한 기술로, 기상정보 및 수율 예측정보를 산출하기 위해, 최근 10년간의 통계를 활용한 단순 선형 회귀 방법으로 추세제거 수율을 산출하는 추세제거 수율 산출 단계, 수집된 기상 자료를 기반으로, 가공된 기상자료를 생산하는 기상자료 생산 단계, 기간별 다중선형회귀모형을 도출하는 다중선형회귀모형 도출 단계, 회귀모형을 도출하는 회귀모형 도출 단계를 포함하여, 국제 농산물 가격과 곡물에 대한 현황 파악을 통해, 곡물의 생산량 변동에 따른 대책을 수립할 수 있는 효과가 있다. claims: 최근 10년간의 통계를 활용한 단순 선형 회귀 방법으로 추세제거 수율을 산출하는 추세제거 수율 산출 단계;수집된 기상 자료를 기반으로, 가공된 기상자료를 생산하는 기상자료 생산 단계;기간별 다중선형회귀모형을 도출하는 다중선형회귀모형 도출 단계;회귀모형을 도출하는 회귀모형 도출 단계;를 포함하는 기상요인을 고려한 대두 수확량 예측 방법., Ltext: 농업, prediction: 농업
836/1059 Row 836: application_number: 1020190148514, combined_string: invention_title: 군집비행 드론 플랫폼을 이용한 재배현황 및 식생지수 분석 시스템 abstract: 본 발명은 군집비행 드론 플랫폼을 이용한 재배현황 및 식생지수 분석 시스템에 관한 것이다.보다 구체적으로, 관리대상영역에 대한 전체영상을 생성하여 실제면적을 산출하고, 산출된 실제면적을 기준으로 각 슬레이브 드론에서 촬영할 분할영역 및 초기위치를 설정하는 마스터 드론, 상기 마스터 드론으로부터 해당 촬영영역 및 초기위치를 수신하면, 해당 초기위치로 이동하여 기설정된 경로에 따라 군집비행하며 촬영한 분할영상을 생성하는 복수의 슬레이브 드론 및 상기 마스터 드론 및 복수의 슬레이브 드론으로부터 촬영된 영상을 수집하여 상기 관리대상영역의 재배현황 및 식생지수를 파악하는 관리서버를 포함하는 것을 특징으로 하는 군집비행 드론 플랫폼을 이용한 재배현황 및 식생지수 분석 시스템에 관한 것이다. claims: 관리대상영역에 대한 전체영상을 생성하여 실제면적을 산출하고, 산출된 실제면적을 기준으로 각 슬레이브 드론에서 촬영할 분할영역 및 초기위치를 설정하는 마스터 드론;상기 마스터 드론으로부터 해당 촬영영역 및 초기위치를 수신하면, 해당 초기위치로 이동하여 기설정된 경로에 따라 군집비행하며 해당 분할영역을 촬영한 분할영상을 생성하는 복수의 슬레이브 드론; 및상기 마스터 드론 및 복수의 슬레이브 드론으로부터 촬영된 영상을 수집하여 상기 관리대상영역의 재배현황 및 식생지수를 파악하는 관리서버를 포함하는 것을 특징으로 하는 군집비행 드론 플랫폼을 이용한 재배현황 및 식생지수 분석 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

837/1059 Row 837: application_number: 1020190147584, combined_string: invention_title: 스마트 팜 통합관리 플랫폼 시스템 및 이의 운영방법 abstract: 본 발명은 농작물을 재배하고자 하는 생산자에게 해당 농작물의 재배에 필요한 자원을 제공함과 동시에 생산자로부터 획득한 농작물이 소비자에게 원활하게 공급될 수 있도록 하는 스마트 팜 통합관리 플랫폼 시스템 및 이의 운영방법에 관한 것으로, 더욱 상세하게는 소비자에게 공급하기 위한 농작물이 생산자에 의해 재배하는 제어수단와, 적어도 하나 이상의 상기 제어수단에 농작물 재배에 필요한 정보는 물론, 해당 농작물을 재배시에 필요한 인력이나 장치를 제공하며, 통신망을 통해 소비자와 생산자 간에 농작물의 매매가 이루어질 수 있도록 중개하는 통합관리부 및 농작물이 재배되는 상기 제어수단를 운영하는 생산자는 물론, 예비 생산자에게 필요한 농작물 재배에 관한 재배정보를 제공하는 시스템운영부를 포함하되, 상기 시스템운영부는 상기 제어수단이 위치한 지역의 기상변화정보와 병충해정보로 이루어진 재배정보를 실시간으로 제공하는 것을 특징으로 한다. claims: 소비자에게 공급하기 위한 농작물이 생산자에 의해 재배되는 온실운영부(100);네트워크 통신망을 통하여 적어도 하나 이상의 상기 온실운영부(100)에 농작물 재배에 필요한 기술정보, 인력정보 및 장치정보를 제공하는 통합관리부(200); 및 상기 생산자와 소비자 사이에 재배농산물의 판매와 구매에 관한 정보를 제공하는 시스템운영부(300);를 포함하는 스마트 팜 통합관리 플랫폼 시스템에 있어서, 상기 온실운영부(100)는 외기의 영향이 없이 내부에 구비된 토양에서 농작물이 재배될 수 있는 공간을 제공하는 하우스본체(110); 제어수단(170)의 제어를 통해 상기 하우스본체(110)의 실내공기를 외부로 배출하는 유동팬(120); 상기 하우스본체(110)의 내부 온도가 적정온도로 유지할 수 있도록 상기 하우스본체(110)의 실내온도를 유지하기 위한 온도조절부재(130); 상기 제어수단(170)에 의해 제어되되 해당 토양의 영양분을 분석하는 토양정보센서(140); 상기 제어수단(170)의 제어에 의해 농작물 재배에 필요한 물을 해당 토양에 제공하는 관수제공부재(150); 및 상기 하우스본체(110) 내부나 외부에 설치되는 영상제공부재(160);를 포함하되, 상기 토양정보센서에 의해서 분석된 토양의 영양성분에 따라서 필요한 영양성분을 토양에 공급하는 양액기(113)를 더 구비하고,상기 통합관리부(200)는 생산자 및 소비자를 개별적으로 관리할 수 있는 적어도 하나 이상의 관리매장(210);실시간으로 상기 온실운영부(100)의 제어수단(170)로부터 전송된 실시간 생육정보와 시스템 환경으로부터 전송된 운영정보를 수신하여 온실조건DB(270)와 비교하는 생육환경 모니터링모듈(221);농작물을 재배하는데 필요한 영농자원을 예약하고, 비번인 영농자원을 대여하여 필요한 생산자에게 매칭시키고 영농자원DB(230)에 저장하는 모듈(222);기술지원 단말기(310)로부터 등록된 영농자원DB(230)에 대한 리소스 어카운트 정보를 수신하여 저장하고, 영농자원 사용시에 소요되는 비용을 리소스 어카운트 정보를 통해서 처리하는 모듈(223);소정의 시간에 생육환경 모니터링DB(250)로부터 동일 품종별로 축적된 생육정보 및 스마트팜 운영정보를 추출하여 빅데이터 분석 및 데이터마이닝을 통해서 예측정보 및 분석정보를 생성하여 분석DB(260)에 저장하는 데이터 분석모듈(224); 상기 소비자와 생산자 사이에 거래가 발생하면 해당 농산물에 대한 최초 재배부터 수확까지 농산물의 생산이력정보를 생산이력DB(280)로부터 수신받아 소비자 단말기(320)에 송신하고, 소비자 단말기(320)로부터 고객정보를 수신하여 주문정보를 생성하여 판매DB(240)에 저장하고, 생산자 단말기(330) 및 미리 연계된 배송업체에 주문정보를 송신하는 모듈(225); 을 포함하되, 상기 리소스 어카운트는 영농자원DB(230)로부터 수신된 영농자원정보를 기초로 하여 리소스 어카운트 알고리즘에 의해서 산출되며, 개별 생산자마다 보유한 토탈 리소스 어카운트 정보에 누적되어, 영농자원을 사용하면 상기 영농자원에 설정된 리소스 어카운트 만큼 차감되고, 영농자원을 대여해주면 상기 영농자원에 설정된 리소스 어카운트 만큼 증가되는 것이며, 상기 시스템운영부(300)는, 생산자 단말기(330)와; 소비자 단말기(320);을 포함하되, 상기 생산자 단말기(330)는, 온실조건DB(270)에 저장된 생육정보를 조회하거나 직접 입력받아 제어수단(170)을 통해 온실운영부(100)에 있는 센서를 제어할 수 있는 생육조건 입력/조회모듈(331); 생육환경 모니터링DB(270)에 있는 생육정보와 운영정보를 실시간으로 모니터링 할 수 있는 실시간 생장환경 모니터링 모듈(332); 분석DB(260)에서 추출한 예측 및 분석 정보, 즉 동일 품종별로 축적된 생육정보 및 운영정보를 빅데이터 분석 및 데이터마이닝을 통해서 생성된 예측정보 및 분석정보를 제공하는 모듈(333); 농작물을 재배하는데 필요한 영농자원을 조회하고 관리하는 모듈(334); 온실을 영역ID에 따라 분할하고 판매하는 모듈(335); 생산자가 생산한 농산물의 생산이력을 관리하는 모듈(336); 판매할 농산물을 선택하게 하고 주문정보를 생성하여 소비자 단말기에 전송하는 농산물 판매모듈(337); 생산자별로 보유하고 있는 리소스 어카운트 정보를 조회하는 모듈(338);을 포함하고,상기 소비자 단말기(320)는,상기 구매한 영역ID에 따른 온실조건DB(270)에 저장된 생육조건데이터를 조회하거나 직접 입력하여 제어수단(170)을 통해 온실운영부(100)에 있는 센서를 제어할 수 있는 영역 생육조건 입력/조회모듈(321); 영역ID에 따라 분할된 온실을 구매하고 수확량에 따른 목표를 설정하는 모듈(322); 영역ID의 생육환경 모니터링DB(270)에 저장되어 있는 생육정보 및 운영정보를 실시간으로 모니터링 할 수 있는 영역 실시간 생장환경 모니터링 모듈(323); 영역ID의 농작물을 재배하는데 필요한 영농자원을 관리하고 제어하는 모듈(324); 소비자가 선택한 농산물에 대한 생산이력을 조회하는 모듈(325); 생산된 농산물 또는 특정영역의 농산물을 선택하고 구매하고 주문정보를 생산자 단말기로 전송하는 농산물 구매 모듈(326); 예비농민 또는 소비자에게 분석DB(260)에서 추출한 동일 품종별로 축적된 생육정보 및 운영정보를 빅데이터 분석 및 데이터마이닝을 통해서 생성된 예측정보 및 분석정보를 제공하는 모듈(327); 생산 전에 설정된 수확목표량과 현재 수확량을 비교하여 초과되면 초과실적을 기준으로 리소스 어카운트 알고리즘에 따라 리소스 어카운트가 설정되고 정산되는 모듈(328);을 더 포함하는 것을 특징으로 하는 스마트 팜 통합관리 플랫폼 시스템.제1항의 스마트 팜 통합관리플랫폼 시스템의 운영방법에 있어서, 상기 기술지원 단말기(310)를 통해서 영농자원정보를 입력받고 리소스 어카운트 생성모듈(222)에 의해서 영농자원별 리소스 어카운트가 생성되고 설정되는 단계(W1);상기 생산자 단말기(330)를 통해서 온실조건정보를 입력받아 온실조건DB(270)에 저장하고, 온실운영부의 제어수단(170)으로 전송하여 온실의 센서들을 제어하도록 하는 단계(W2);상기 생산자 단말기(330)를 통해서 생육환경을 모니터링하고 이상 데이터 플래그를 체크하고, 이상이 있는 경우 필요한 조치를 취하는 단계(W3);상기 생산자 단말기(330)를 통해서 필요한 영농자원이 선택되고, 영농자원 매칭모듈(223)로 영농자원정보가 전송되어 자원의 사용이 발생되며, 보유한 토탈 리소스 어카운트에 의해서 비용이 정산되는 단계(W4);매월 마다 데이터 분석모듈(224)에 의해 동일한 품종별로 축적된 생육정보 및 스마트팜 운영정보를 추출하여 빅데이터 분석 및 데이터마이닝을 통해서 예측정보 및 분석정보를 생성하여 분석DB(260)에 저장되는 단계(W5);상기 생산자 단말기(330)를 통해서 예측 및 분석정보를 조회하여 최적의 생육정보를 수신받고, 신규 온실조건정보를 제어수단(170)으로 전송하여 온실의 센서들을 제어하도록 하는 단계(W6);상기 생산자 단말기(330)를 통해서 생산한 농산물 생육정보와 농산물 이력정보를 수신받고, 소비자에 의해서 구매가 결정되면 해당 주문정보가 주문정보생성모듈(225)로 전송되는 단계(W7);상기 주문정보생성모듈(225)은 주문정보를 소비자와 배송업체에 전송하여 유통이 시작되도록 알리는 단계(W8);를 포함하는 것을 특징으로 하는 스마트 팜 통합관리 플랫폼시스템의 운영방법.제1항의 스마트 팜 통합관리플랫폼 시스템의 운영방법에 있어서, 상기 소비자 단말기(320)를 통해서 온실하우스의 구획화된 온실영역을 구매하여 영역구매자로 구분되고, 목표수확량을 설정하고, 정해진 토탈 리소스 어카운트를 지급받는 단계(C1);상기 소비자 단말기(320)를 통해서 예측 및 분석정보를 조회하여 최적의 생육정보를 수신받고, 신규 온실조건정보를 제어수단(170)으로 전송하여 온실의 센서들을 제어하도록 하는 단계(C2);상기 소비자 단말기(320)를 통해서 생육환경을 모니터링하고 이상 데이터 플래그를 체크하고, 이상이 있는 경우 필요한 조치를 취하는 단계(C3);상기 소비자 단말기(320)를 통해서 필요한 영농자원이 선택되고, 영농자원 매칭모듈(223)로 영농자원정보가 전송되어 구매된 영역의 온실에서 자원의 사용이 발생되며, 보유한 토탈 리소스 어카운트에 의해서 비용이 정산되는 단계(C4);상기 소비자 단말기(320)를 통해서 영역 구매자가 생산 전에 설정한 수확목표량와 현재 수확량을 비교하여 초과되면 리소스 어카운트 알고리즘에 따라 리소스 어카운트가 설정되고, 토탈 리소스 어카운트에 누적되는 단계(C5);상기 소비자 단말기(320)를 통해서 농산물 구매시, 보유한 토탈 리스소 어카운트를 통해서 결제가 가능하며, 해당 주문정보가 주문정보생성모듈(225)로 전송되는 단계(C6);상기 주문정보생성모듈(225)은 주문정보를 생산자와 배송업체에 전송하여 유통이 시작되도록 알리는 단계(C7);을 포함하는 것을 특징으로 하는 스마트 팜 통합관리 운영방법., Ltext: 농업, prediction: 임업
838/1059 Row 838: application_number: 1020190147163, combined_string: invention_title: 상생형 병해충 관리 시스템 및 그 방법 abstract: 상생형 병해충 관리 시스템 및 그 방법에 관한 것으로, 상생형 병해충 관리시스템은 사용자 농장의 토양 상태, 병해충 발생 정보, 작물의 특징 정보, 그리고 기상 정보 중에서 하나 이상의 데이터를 수집하고, 인근 농장의 작물 정보, 인근 농장의 병해충 정보를 수집하는 수집부, 데이터를 미리 학습된 머신러닝 알고리즘에 적용하여 사용자 농장에서 발생가능성이 임계치 이상인 병해충을 예측하는 예측부, 그리고 예측된 병해충에 대응하는 방제 방법 중에서 인근 농장에서의 위험 요소를 최소화한 방제 방법을 선별하여 상생형 방제 방법을 추천하는 제어부를 포함한다. claims: 사용자 농장의 토양 상태, 병해충 발생 정보, 작물의 특징 정보, 그리고 기상 정보 중에서 하나 이상의 데이터를 수집하고, 인근 농장의 작물 정보, 상기 인근 농장의 병해충 정보를 수집하는 수집부, 상기 데이터를 미리 학습된 머신러닝 알고리즘에 적용하여 상기 사용자 농장에서 발생가능성이 임계치 이상인 병해충을 예측하는 예측부, 그리고 예측된 상기 병해충에 대응하는 방제 방법 중에서 상기 인근 농장에서의 위험 요소를 최소화한 방제 방법을 선별하여 상생형 방제 방법을 추천하는 제어부를 포함하는 상생형 병해충 관리 시스템.사용자 농장의 토양 상태, 병해충 발생 정보, 작물의 특징 정보, 그리고 기상 정보 중에서 하나 이상의 데이터를 수집하는 단계, 수집한 상기 데이터를 미리 학습된 머신러닝 알고리즘에 적용하여 상기 사용자 농장에서 발생가능성이 임계치 이상인 병해충을 예측하는 단계, 인근 농장의 작물 정보, 상기 인근 농장의 병해충 정보를 수집하는 단계, 그리고 예측된 상기 병해충에 대응하는 방제 방법 중에서 상기 인근 농장에서의 위험 요소를 최소화한 방제 방법을 선별하여 상생형 방제 방법을 추천하는 단계, 를 포함하는 상생형 병해충 관리 시스템의 관리 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

839/1059 Row 839: application_number: 1020190145048, combined_string: invention_title: 농작물 재배 모니터링 시스템 및 이를 이용한 농작물 재배 모니터링 방법 abstract: 본 발명은 농작물을 재배하는 정보의 메타데이터를 통해 자동으로 분류하여 데이터베이스를 구축하고 사용자가 원하는 조건에 따라 농작물재배정보를 추출하여 시각화함으로 인해 사용자가 농작물의 재배과정을 용이하게 분석할 수 있어 농작물의 생산성을 향상시킬 수 있는 농작물 재배 모니터링 시스템 및 이를 이용한 농작물 재배 모니터링 방법에 관한 것이다.본 발명은 농작물이 재배되는 환경을 측정한 환경데이터와, 상기 농작물로 공급되는 양액을 측정한 양액데이터와, 상기 농작물의 성장을 측정한 생육데이터와, 상기 농작물의 수확량을 입력한 생산량데이터와, 상기 농작물의 재배에 소요된 소요비용을 입력한 비용데이터를 메타데이터처리하여 농작물재배정보를 생성하기 위한 다수의 스마트팜(100)과, 상기 다수의 스마트팜(100)으로부터 수신받은 농작물재배정보의 메타데이터를 자동으로 추출하여 미리 설정된 키워드별로 분류하여 데이터베이스로 구축한 후 상기 데이터베이스 중에 사용자가 설정한 조건정보에 따라 데이터를 자동으로 추출하고 그룹화하여 도표화한 재배분석정보를 생성하기 위한 관제서버(200)와, 상기 관제서버(200)로부터 재배분석정보를 수신받아 디스플레이하기 위해 농작물의 재배기간 단위를 포함한 조건을 설정하여 상기 조건정보를 생성하기 위한 사용자단말기(300)를 포함한다. claims: 농작물이 재배되는 환경을 측정한 환경데이터와, 상기 농작물로 공급되는 양액을 측정한 양액데이터와, 상기 농작물의 성장을 측정한 생육데이터와, 상기 농작물의 수확량을 입력한 생산량데이터와, 상기 농작물의 재배에 소요된 소요비용을 입력한 비용데이터를 메타데이터처리하여 농작물재배정보를 생성하기 위한 다수의 스마트팜(100)과, 상기 다수의 스마트팜(100)으로부터 수신받은 농작물재배정보의 메타데이터를 자동으로 추출하여 미리 설정된 키워드별로 분류하여 데이터베이스로 구축한 후 상기 데이터베이스 중에 사용자가 설정한 조건정보에 따라 데이터를 자동으로 추출하고 그룹화하여 도표화한 재배분석정보를 생성하기 위한 관제서버(200)와, 상기 관제서버(200)로부터 재배분석정보를 수신받아 디스플레이하기 위해 농작물의 재배기간 단위를 포함한 조건을 설정하여 상기 조건정보를 생성하기 위한 사용자단말기(300)를 포함하는 농작물 재배 모니터링 시스템.농작물을 원격으로 관리하기 위한 스마트팜(100)에서 농작물이 재배되는 환경을 측정한 환경데이터와, 상기 농작물로 공급되는 양액을 측정한 양액데이터와, 상기 농작물의 성장을 측정한 생육데이터와, 상기 농작물의 수확량을 입력한 생산량데이터와, 상기 농작물의 재배에 소요된 소요비용을 입력한 비용데이터를 생성하는 데이터생성단계와,상기 스마트팜(100)에서 상기 환경데이터와 양액데이터와 생육데이터와 생산량데이터와 비용데이터를 메타데이터처리하여 농작물재배정보를 생성하고 관제서버(200)로 전송하는 메타데이터처리단계와,상기 관제서버(200)에서 수신받은 농작물재배정보의 메타데이터를 추출하는 상기 메타데이터추출단계와,상기 관제서버(200)에서 상기 추출된 메타데이터를 이용하여 미리 설정된 키워드별로 상기 농작물재배정보를 분류하여 데이터베이스로 구축하는 데이터베이스구축단계와,상기 관제서버(200)에서 농작물의 재배를 분석하기 위한 조건을 설정하는 사용자단말기(300)로부터 생성된 조건정보를 수신받는 조건정보수신단계와,상기 관제서버(200)에서 상기 데이터베이스의 메타데이터를 이용하여 상기 데이터베이스 중 조건정보에 대응되는 조건데이터를 추출하는 조건데이터추출단계와,상기 관제서버(200)에서 상기 조건데이터를 그룹핑하고 도표화하여 농작물분석정보를 생성하는 데이터가공단계와,상기 관제서버(200)로부터 생성된 농작물분석정보를 상기 사용자단말기(300)로 출력하는 출력단계를 포함하는 농작물 재배 모니터링 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

840/1059 Row 840: application_number: 1020190144305, combined_string: invention_title: 드론을 이용한 농약방제 시스템 및 그 방법 abstract: 본 발명은 드론을 이용한 농약방제시스템 및 그 방법에 관한 것으로, 더욱 상세하게는 경작자가 농약방제가 필요한 농경지 및 농약 정보와 방제 요청기일 등을 스마트폰을 통해 농약방제 수탁사의 관리서버로 신청할 수 있도록 구성되어 경작자의 스마트폰에 설치되는 농약방제 예약앱(120); 다수의 경작자들로부터 농약방제 예약 및 신청을 받고 관리하기 위한 방제예약 관리부(210)와, 회원으로 등록된 방제사업자들이 소유하고 있는 방제드론을 관리하기 위한 방제드론 관리부(220)와, 경작자의 방제 요청시 지번확인 또는 방제사업자에게 방역용역을 위임할 때 방제사업자가 예약된 농경지를 확인할 수 있도록 경작지 정보등을 제공하기 위한 토지(지리)정보 관리부(230)와, 경작자 또는 방제사업자의 비용입출금 등을 관리하기 위한 비용관리부(240)와, 시기별, 계절별 또는 작물별 발병될 수 있는 병충해정보와 농약정보를 경작자 또는 방제사업자에게 제공할 수 있도록 하는 병충해정보 제공부(250)를 농약방제 수탁사의 관리서버(200); 상기 관리서버에 방제드론의 등록 및 관리서버로부터 농약방제 업무의 송수신과 방제 후 방제내용을 전송하고, 방제 내용에 따라 방제비용을 청구할 수 있도록 구성되어 방제사업자의 스마트폰에 설치되는 농약방제 관리앱(320);을 포함하는 구성으로 이루어진다. claims: 경작자가 농약방제가 필요한 농경지 및 농약 정보와 방제 요청기일 등을 스마트폰을 통해 농약방제 수탁사의 관리서버로 신청할 수 있도록 구성되어 경작자의 스마트폰에 설치되는 농약방제 예약앱(120);다수의 경작자들로부터 농약방제 예약 및 신청을 받고 관리하기 위한 방제예약 관리부(210)와, 회원으로 등록된 방제사업자들이 소유하고 있는 방제드론을 관리하기 위한 방제드론 관리부(220)와, 경작자의 방제 요청시 지번확인 또는 방제사업자에게 방역용역을 위임할 때 방제사업자가 예약된 농경지를 확인할 수 있도록 경작지 정보등을 제공하기 위한 토지(지리)정보 관리부(230)와, 경작자 또는 방제사업자의 비용입출금 등을 관리하기 위한 비용관리부(240)와, 시기별, 계절별 또는 작물별 발병될 수 있는 병충해정보와 농약정보를 경작자 또는 방제사업자에게 제공할 수 있도록 하는 병충해정보 제공부(250)를 포함하는 농약방제 수탁사의 관리서버(200);상기 관리서버에 방제드론의 등록 및 관리서버로부터 농약방제 업무의 송수신과 방제 후 방제내용을 전송하고, 방제 내용에 따라 방제비용을 청구할 수 있도록 구성되어 방제사업자의 스마트폰에 설치되는 농약방제 관리앱(320);을 포함하여 이루어지는 것을 특징으로 하는 드론을 이용한 농약방제 시스템.경작자가 농약방제 수탁업무를 수행하는 농약방제 수탁사의 회원으로 등록하면서 자신이 경작하고 있는 농경지 정보를 입력하고, 농약방제 수탁사가 제공하는 농약방제 예약앱을 자신의 스마트폰에 설치하는 농약방제 예약앱 설치단계(S10);방제드론을 소유한 방제사업자가 농약방제 수탁사의 회원으로 가입하면서 자신이 소유한 방제용드론 정보를 등록하고, 농약방제 수탁사가 제공하는 농약살포 관리앱을 자신의 스마트폰에 설치하는 농약방제 관리앱 설치단계(S20);경작자가 농약방제 예약앱을 통해 농약방제 수탁사의 관리서버에 접속하여 농약방제에 필요한 경작지와 농약정보 및 방제요청 기일을 입력하여 농약방제를 예약하는 단계(S30);농약방제 예약이 접수된 관리서버에서 등록된 방제사업자의 방제드론 중 요청된 예약기일에 농약방제가 가능한 복수의 방제드론을 선별하여 선정하는 방제드론 선별/선정단계(S40);농약방제 수탁사의 관리서버에서 선별된 방제드론을 소유한 방제사업자에게 농약방제를 신청한 예약자의 정보를 전송하여 요청된 방제기일에 농약방제가 가능한지 여부를 확인하기 위한 방제 예약정보 전송단계(S50);방제 예약정보를 수신한 방제사업자가 요청기일에 농약방제가 가능한지 여부를 농약살포 관리앱을 이용하여 농약방제 수탁사에게 통지하는 농약방제 가능여부 통지단계(S60);방제사업자로부터 수신된 방제 가능여부 정보를 토대로 농약방제 수탁사의 관리서버에서 최종 농약방제가 가능한 방제용 드론을 확정, 확정된 방제드론 정보를 경작자 및 해당 방제사업자에게 전송하는 방제드론 확정 통지단계(S70);방제드론 확정정보를 수신한 방제사업자가 해당 기일에 예약자의 농경지에 농약을 방제한 후 농약방제 수탁사의 관리서버로 방제완료 내용 통보 및 방제 비용을 청구하는 방제비용 청구단계(S80);방제사업자로부터 방제완료보고 및 방제비용 청구가 이루어진 경우 농약방제 수탁사의 관리서버에서는 방제내용을 확인하고, 확인된 방제내용을 경작자에게 통지하면서 방제비용에 대해 입금을 요청하는 방제완료 통보 및 방제비용 입금 요청단계(S90);경작자로부터 비용입금이 확인된 관리서버에서 방제사업자에게 방제비용을 지불하는 방제비용 정산단계(S100);로 이루어지는 것을 특징으로 하는 드론을 이용한 농약 방제방법., Ltext: 농업, prediction: 농업
841/1059 Row 841: application_number: 1020190144501, combined_string: invention_title: 모듈형 식물 재배 시스템 abstract: 인체에 필요한 미네랄을 엽채류에서 용이하게 섭취할 수 있도록 각각의 모듈에서 재배되는 엽채류에 게르마늄, 칼슘 또는 마그네슘의 함유량을 증대시키는 모듈형 식물 재배 시스템에 관한 것으로, 각각 엽채류 식물의 재배 기능을 구비한 다수의 재배 모듈, 상기 재배 모듈의 상태를 관리하는 관리자 단말기, 네트워크를 통해 상기 관리자 단말기로부터 전송된 재배 모듈에 관한 정보를 실시간으로 관리하는 관리 서버를 포함하고, 각각의 재배 모듈은 상기 재배 모듈에서 재배될 엽채류에 양액을 공급하는 양액 조성 조절기, 상기 재배 모듈의 양액조 내에 공급된 양액의 농도를 환산하는 농도 환산부, 상기 재배 모듈에서 재배되는 엽채류의 상태를 감지하는 상태 감지부를 포함하는 구성을 마련하여, 소비자가 인체에 필요한 게르마늄, 칼슘 또는 마그네슘 등의 미네랄이 함유된 엽채류를 용이하게 섭취하게 할 수 있다. claims: 각각 엽채류 식물의 재배 기능을 구비한 다수의 재배 모듈,상기 재배 모듈의 상태를 관리하는 관리자 단말기,네트워크를 통해 상기 관리자 단말기로부터 전송된 재배 모듈에 관한 정보를 실시간으로 관리하는 관리 서버를 포함하고,각각의 재배 모듈은상기 재배 모듈에서 재배될 엽채류에 양액을 공급하는 양액 조성 조절기,상기 재배 모듈의 양액조 내에 공급된 양액의 농도를 환산하는 농도 환산부,상기 재배 모듈에서 재배되는 엽채류의 상태를 감지하는 상태 감지부를 포함하는 것을 특징으로 하는 모듈형 식물 재배 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

842/1059 Row 842: application_number: 1020190141711, combined_string: invention_title: 바지선을 활용한 도서(島嶼)지역용 경작용수 공급시스템 abstract: 본 발명은 바지선을 활용한 도서(島嶼)지역용 경작용수 공급시스템에 관한 것으로, 보다 상세하게는 크고 작은 섬에서 작물을 경작하는데 사용하는 경작용수로 바지선에 저장한 우수(雨水)를 활용하여 부족한 지하수 자원을 보충할 수 있고, 도서(島嶼) 지역의 경작용수 부족에 따른 문제점을 해결할 수 있는 바지선을 활용한 도서(島嶼)지역용 경작용수 공급시스템에 관한 것으로,이를 위해 본 발명은, 우수 및 지하수가 저장된 저류지; 우수를 저장하는 저장공간이 구비된 바지선; 상기 바지선에 저장된 물을 전달 받아 저장하는 물탱크; 상기 저류지 또는 상기 물탱크 또는 상기 바지선에 저장된 물을 사용처로 전달하기 위한 관로; 상기 바지선에 저장된 우수를 상기 관로로 전달하기 위하여 상기 바지선을 상기 관로에 분리 가능하게 결합하는 결합모듈;을 포함한다. claims: 우수 및 지하수가 저장된 저류지(10);우수를 저장하는 저장공간이 구비된 바지선(20);상기 바지선(20)에 저장된 물을 전달 받아 저장하는 물탱크(30);상기 저류지(10) 또는 상기 물탱크(30) 또는 상기 바지선(20)에 저장된 물을 사용처로 전달하기 위한 관로(40);상기 바지선(20)에 저장된 우수를 상기 관로(40)로 전달하기 위하여 상기 바지선(20)을 상기 관로(40)에 분리 가능하게 결합하는 결합모듈(50);을 포함하되,상기 결합모듈(50)은,상기 바지선(20)에 구비된 배출관(51)과,상기 관로(40)에 구비되어 상기 배출관(51)의 단부가 결합하여 상호 연통되는 유입관(52)과,길이 방향으로 연장 형성되어 일단은 상기 배출관(51)측에 배치되고 타단은 상기 유입관(52)측에 배치되어 상기 배출관(51)과 상기 유입관(52)의 결합 부위를 감싸도록 배치되는 커플러(53) 및상기 커플러(53)의 내측에 배치되어 상기 배출관(51)측에서 전달된 이동력을 상쇄하는 레벨유지수단(54)을 포함하고,상기 레벨유지수단(54)은,상기 배출관(51)의 외주면과 상기 커플러(53)의 내주면을 따라 배치되되 상기 배출관(51)의 외주면과 상기 커플러(53)의 내주면에 교호(交互)로 맞닿도록 배치되는 지지부(541)와,한 쌍이 상호 이격된 위치에 배치되며 각각의 일단이 상기 지지부(541)에 결합되며 상호간의 간격을 조절함에 따라 상기 지지부(541)의 곡률을 변화시켜 지지부의 탄성력을 조절하는 탄성조절편(542)과,상기 한 쌍의 탄성조절편(542) 간격을 조절하기 위한 것으로, 상기 한 쌍의 탄성조절편(542)에 각각 형성된 결합공(543)과,상기 결합공(543)에 맞물리게 결합되어 회전 방향에 따라 한 쌍의 탄성조절편(542)의 간격을 조절하는 간격조절볼트(544)와,상기 한 쌍의 결합공(543) 중 어느 하나에 배치되어 상기 간격조절볼트(544)가 맞물리는 고정너트(545)를 포함하고,상기 지지부(541)는,일부가 개구된 C 형태로 이루어지고 연속적인 웨이브 형태로 이루어지는 것을 특징으로 하는 바지선을 활용한 도서(島嶼)지역용 경작용수 공급시스템., Ltext: 농업, prediction: 임업
843/1059 Row 843: application_number: 1020190140830, combined_string: invention_title: 온실 작물 최적생육시스템 abstract: 본 발명은 온실 작물 최적생육시스템에 관한 것으로, 더욱 상세하게는 온실 내외부의 환경정보, 온실의 환경을 조절하는 온실환경조절장치의 작동정보와 이에 따른 생육결과를 이용하여 머신러닝 방식에 의해 최적의 생육조건을 도출하고, 이에 따른 온실환경조절장치의 작동이 이루어지도록 함으로써, 온실 작물의 생산효율을 극대화할 수 있도록 하는 온실 작물 최적생육시스템에 관한 것이다. claims: 작물이 재배되는 온실 내의 환경정보를 측정하는 온실환경측정장치와, 온실 내의 환경을 인위적으로 조절하는 온실환경조절장치와, 온실 내 작물의 생육조건에 맞도록 온실환경조절장치의 작동을 조절하는 관리서버를 포함하고, 상기 관리서버는, 일정 기간 동안 상기 온실환경측정장치로부터 측정되는 온실 내 환경정보, 온실 외부의 환경정보 및 온실환경조절장치의 작동정보를 수집하여 작물의 생육결과와의 상관관계를 분석하고 분석된 상관관계에 따라 생육조건을 설정하여 온실환경조절장치의 작동을 조절하도록 하는 것을 특징으로 하는 온실 작물 최적생육시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

844/1059 Row 844: application_number: 1020210040230, combined_string: invention_title: 폴더블 펫 드라이어 abstract: 본 발명은 폴더블 펫 드라이룸에 관한 것으로, 보다 상세하게는 펼침 상태에서 애완동물의 드라이를 위한 공간을 형성하고, 접힘 가능한 폴더블 구조를 제공함으로써, 공간효율 및 휴대성 등이 증대된 폴더블 펫 드라이어에 관한 것이다.이러한 본 발명은, 건조 공간을 구비하고, 상기 건조 공간의 일 측에 구비된 내기 유입부 및 상기 건조 공간의 또 다른 일 측에 구비된 내기 공급부를 포함하는 하우징, 상기 하우징에 결합되어 상기 건조 공간을 형성하는 도어 및 상기 하우징에 구비되고, 상기 하우징의 접힘 및 펼침 동작을 제공하는 힌지결합수단을 포함한다. claims: 건조 공간을 구비하고, 상기 건조 공간의 일 측에 구비된 내기 유입부 및 상기 건조 공간의 또 다른 일 측에 구비된 내기 공급부를 포함하는 하우징; 및상기 하우징에 구비되고, 상기 하우징의 접힘 및 펼침 동작을 제공하는 힌지결합수단;을 포함하는 폴더블 펫 드라이어., Ltext: 농업, prediction: 임업
845/1059 Row 845: application_number: 1020200148884, combined_string: invention_title: 곤충사육사용 조명 abstract: 본 발명은 곤충사육사용 조명에 관한 것으로, 곤충사육사(10)에 설치되며 자연광의 빛을 구현하는 자연광 조명부(110)와 상기 자연광 조명부(110)가 자연광의 빛을 구현하도록, 계절 및 시간대별 태양광 데이터를 기초로 상기 자연광 조명부(110)의 색온도와 점등 및 소등을 제어하는 제어기(120)를 포함한다. 본 발명은 태양의 고도에 따라 일출에서 일몰까지 변화하는 색온도를 실내에서 구현하여 동애등에를 사육하는 곤충사육사의 조명 환경을 개선하여 동애등에의 생산성을 증가시킬 수 있는 이점이 있다. claims: 곤충사육사에 설치되며 자연광의 빛을 구현하는 자연광 조명부; 및상기 자연광 조명부가 자연광의 빛을 구현하도록, 계절 및 시간대별 태양광 데이터를 기초로 상기 자연광 조명부의 색온도와 점등 및 소등을 제어하는 제어기;를 포함하며, 상기 자연광 조명부는 기판에 복수 개의 엘이디가 배열 설치되어 형성되며, 상기 복수 개의 엘이디는 색온도 2800~3000K 대역을 가지는 제1 엘이디; 및색온도 8000K~10000K을 가지는 제2 엘이디;를 포함하고, 상기 제어기는 AC 전원을 DC 전원으로 변환하는 컨버터; 계절 및 시간대별 태양광 고도 및 색온도 데이터가 저장된 저장부;DC 전원을 공급받아 구동하고, 상기 저장부에 저장된 계절 및 시간대별 태양광 고도 및 색온도 데이터에서 현재 날짜와 시간에 대응되는 색온도를 판단하여 구동 제어신호를 전송하는 제어부; 및상기 제어부의 구동 제어신호를 입력받아 상기 엘이디의 온 오프 및 상기 엘이디의 조도를 제어하는 정전류 회로;를 포함하고, 상기 정전류 회로는상기 제1 엘이디와 상기 제2 엘이디를 각각 제어하기 위한 정전류 회로1과 정전류 회로2를 포함하고, 상기 정전류 회로1은 상기 제1 엘이디에 공급되는 전류 출력량을 제어하여 상기 제1 엘이디의 색온도를 제어하고, 상기 정전류 회로2는 상기 제2 엘이디에 공급되는 전류 출력량을 제어하여 상기 제2 엘이디의 조도를 제어하며,상기 제1 엘이디 및 상기 제2 엘이디는 복수 개이고, 상기 제어부는 상기 제1 엘이디와 상기 제2 엘이디를 선택적으로 온 오프시키고, 색온도 및 조도를 제어하여,색온도를 2800K~10000K 범위에서 순차적으로 높이고 낮추고, 상기 제1 엘이디와 상기 제2 엘이디를 점등 및 소등시키며,상기 제어부는 스마트폰 앱과 연결되어 작업자가 수동 조절 또는 자동으로 조절 가능하며, 상기 제어부가 상기 제1 엘이디 및 상기 제2 엘이디를 온 오프시킨 정보 데이터는 상기 스마트폰 앱에 저장되며, 상기 제어부는상기 제1 엘이디 및 상기 제2 엘이디의 점등 및 소등이 춘분 계절의 실외 환경에 대응되도록 06시에 점등하고 19시에 소등하며, 상기 06시에는 상기 제1 엘이디만 점등하고 상기 제2 엘이디는 소등하며,12시에서 13에는 상기 제1 엘이디는 소등하고 상기 제2 엘이디만 점등하며, 18시에는 상기 제1 엘이디는 점등하고 상기 제2 엘이디는 소등하도록 상기 정전류 회로1과 상기 정전류 회로2에 구동 제어신호를 출력하는,곤충사육사용 조명., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

846/1059 Row 846: application_number: 1020200147508, combined_string: invention_title: 수경재배를 이용한 곤충 사육시스템 abstract: 본 발명의 일 실시예에 따른 수경재배를 이용한 곤충 사육시스템은 수경재배용 식물과 사육 대상인 곤충이 서식할 수 있는 서식공간이 구비되는 본체부; 상기 본체부의 하단부에 배치되고, 내부에 상기 수경재배용 식물의 배양을 위한 배양액이 저장되는 재배부; 상기 본체부의 측단부에 배치되고, 서식공간의 온도 및 습도를 감지하여 공조 신호를 출력하는 적어도 하나의 공조센서부; 상기 재배부에 배치되고, 상기 재배부에 저장된 배양액의 수위를 감지하여 수위 신호를 출력하는 수위 조절센서부; 및 상기 본체부 외측에 설치되되, 출력된 공조 신호와 수위 신호를 기반으로 서식공간의 환경을 제어하는 환경 관리부를 포함한다. claims: 수경재배용 식물과 사육 대상인 곤충이 서식할 수 있는 서식공간이 구비되는 본체부;상기 본체부의 하단부에 배치되고, 내부에 상기 수경재배용 식물의 배양을 위한 배양액이 저장되는 재배부;상기 본체부의 측단부에 배치되고, 서식공간의 온도 및 습도를 감지하여 공조 신호를 출력하는 복수 개의 공조센서부;상기 재배부에 배치되고, 상기 재배부에 저장된 배양액의 수위를 감지하여 수위 신호를 출력하는 수위 조절센서부; 및상기 본체부 외측에 설치되되, 출력된 공조 신호와 수위 신호를 기반으로 서식공간의 환경을 제어하는 환경 관리부를 포함하되,상기 환경 관리부는, 상기 배양액을 기 저장하는 배양액 저장부, 상기 서식공간으로 기 설정된 온도 및 기 설정된 습도로 조성된 공기를 공급하거나 상기 재배부로 배양액을 공급하는 유체 펌프부, 및 상기 공조센서부 및 상기 수위 조절센서부와 무선 통신을 통하여 연결되고, 출력된 공조 신호와 수위 신호에 따라 상기 유체 펌프부로 제어 신호를 인가하는 제어부를 포함하고,상기 수위 조절센서부는 저장된 배양액에 침지되고 암모니아, 아질산 및 질산를 포함하는 수질 정보를 감지하여 수질 신호를 출력하고,상기 제어부는 상기 수위 조절센서부로부터 출력된 수질 신호를 기반으로 오염도 수치값을 생성하고, 생성된 오염도 수치값을 기 설정된 오염도 임계수치값과 비교하여 배양액의 오염 상태를 판단하는 수경재배를 이용한 곤충 사육시스템., Ltext: 농업, prediction: 임업
847/1059 Row 847: application_number: 1020200144079, combined_string: invention_title: 애완동물용 배변 처리 가방 abstract: 애완동물의 배변 처리용 물품을 용이하고 효과적으로 수납하며 휴대와 사용이 간편하도록, 양 측단이 접합되어 내부에 수용 공간을 형성하는 전면판과 후면판을 포함하는 본체, 상기 본체에 설치된 고리에 착탈가능하게 결합되는 스트랩을 포함하고, 상기 본체의 상단은 개방되어 입구를 형성하며, 하단은 개방되어 출구를 형성하고, 상기 본체 하단에는 출구를 선택적으로 개폐하는 개폐부가 마련되어, 상기 본체의 입구를 통해 내부에 수용된 물품을 하단의 출구를 통해 배출하는 구조의 애완동물용 배변 처리 가방을 제공한다. claims: 양 측단이 접합되어 내부에 수용 공간을 형성하는 전면판과 후면판을 포함하는 본체, 상기 본체에 설치된 고리에 착탈가능하게 결합되는 스트랩을 포함하고,상기 본체의 상단은 개방되어 입구를 형성하며, 하단은 개방되어 출구를 형성하고, 상기 본체 하단에는 출구를 선택적으로 개폐하는 개폐부가 마련되어, 상기 본체의 입구를 통해 내부에 수용된 물품을 하단의 출구를 통해 배출하는 구조이고,상기 본체는 상단에 설치되어 상기 본체의 상하방향 길이를 선택적으로 확장하는 연장부를 더 포함하고,상기 연장부는 측단이 접합되고 양 선단은 개방되며 상하방향으로 연장된 길이를 갖는 확장포를 포함하고,상기 확장포는 상기 본체의 내면 크기에 대응되는 크기로 형성되고, 일측 선단은 상기 본체 상단의 내측 둘레를 따라 접합되어 고정되고 타측 선단은 자유단을 이루어 필요시 상기 본체 내부로 삽입되거나 외측으로 인출되고, 자유단인 타측 선단에는 조임끈이 설치되어 선단을 선택적으로 조여주는 구조의 애완동물용 배변 처리 가방., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

848/1059 Row 848: application_number: 1020200122940, combined_string: invention_title: 곤충 사육 및 식물 재배를 위한 디바이스 abstract: 본 발명은 곤충 사육 및 식물 재배를 위한 디바이스에 관한 것이다.본 발명은 이를 위해 곤충 사육 및 식물 재배를 위한 디바이스(100)에, 복수개의 공급개별함(141)을 수용하는 공급전체함(140)과, 각 공급개별함(141)을 통해 배출되는 물이나 먹이를 곤충이나 식물이 내장된 상자(101) 내부에 자동으로 정량 공급하여 곤충이나 식물이 자라는 최적의 환경을 제공할 수 있도록 한 정량공급장치(110); 상기 정량공급장치(110)의 일측에 구비되며, 중앙의 사육 및 재배장치 구동부(160)를 중심으로 각각 승하강 작동되도록 좌우측에 각각 하강이송장치(180)와 승강이송장치(170)가 구비된 사육 및 재배장치(150); 및 상기 승강이송장치(170)는 정량공급장치(110)의 일측에 구비되며, 정량공급장치(110)를 통해 공급된 상자(101)를 상부로 순차적으로 이송시킴과 아울러 최상단으로 올라간 상자(101)를 타측 하강이송장치(180)로 이송시키고, 상기 하강이송장치(180)는 이송된 상자(101)를 하부로 순차적으로 이송시킴과 아울러 하강된 상자(101)를 다시 일측 승강이송장치(170)로 이송시킴을 특징으로 하는 곤충 사육 및 식물 재배를 위한 디바이스를 제공한다.상기와 같이 구성된 본 발명은 각종 곤충(예: 동애등애, 거저리, 귀뚜라미, 굼벵이 등)이나 각종 식물(예: 버섯 등)의 사육 및 재배기간 동안 곤충 및 식물이 하나의 디바이스를 통해 효율적으로 사육 및 재배될 수 있도록 한 것이다. claims: 곤충이나 식물의 사육 및 재배기간 동안 곤충 및 식물이 하나의 디바이스를 통해 효율적으로 사육 및 재배될 수 있도록 한 곤충 사육 및 식물 재배를 위한 디바이스(100)를 제공하는 것으로, 상기 곤충 사육 및 식물 재배를 위한 디바이스(100)는, 복수개의 공급개별함(141)을 수용하는 공급전체함(140)과, 각 공급개별함(141)을 통해 배출되는 물이나 먹이를 곤충이나 식물이 내장된 상자(101) 내부에 자동으로 정량 공급하여 곤충이나 식물이 자라는 최적의 환경을 제공할 수 있도록 한 정량공급장치(110); 상기 정량공급장치(110)의 일측에 구비되며, 중앙의 사육 및 재배장치 구동부(160)를 중심으로 각각 승하강 작동되도록 좌우측에 각각 하강이송장치(180)와 승강이송장치(170)가 구비된 사육 및 재배장치(150); 및 상기 승강이송장치(170)는 정량공급장치(110)의 일측에 구비되며, 정량공급장치(110)를 통해 공급된 상자(101)를 상부로 순차적으로 이송시킴과 아울러 최상단으로 올라간 상자(101)를 타측 하강이송장치(180)로 이송시키고, 상기 하강이송장치(180)는 이송된 상자(101)를 하부로 순차적으로 이송시킴과 아울러 하강된 상자(101)를 다시 일측 승강이송장치(170)로 이송시키도록 구성되고,상기 정량공급장치(110)는, 정량공급장치몸체(111); 정량공급장치몸체(111)의 일측에 구비되며, 제1구동모터(121)의 구동에 의해 구동축(122)과 체인풀리(123)를 구동하고, 제2구동모터(125)의 구동에 의해 회동축(126)을 구동하는 정량공급장치구동부(120); 및 정량공급장치몸체(111)의 상단에 일정 간격으로 복수개가 구비되며, 상자(101)를 이송을 돕고, 회전시 상자의 이탈을 방지하는 상자지지브라켓트(130);가 포함됨을 특징으로 하는 곤충 사육 및 식물 재배를 위한 디바이스., Ltext: 농업, prediction: 임업
849/1059 Row 849: application_number: 1020200120573, combined_string: invention_title: 곤충 분변을 활용하여 식물을 재배하기 위한 식용곤충 사육장치 및 그 방법 abstract: 본 발명은 곤충 분변을 활용하여 식물을 재배하기 위한 식용곤충 사육장치 및 그 방법에 관한 것이다. 상기 장치는, 높이를 갖고 연장되는 프레임; 식물을 재배하기 위한 양액이 저장되는 양액보관탱크; 양액을 생성하여 상기 양액보관탱크에 제공하는 양액생성기; 상기 프레임에 의해 복수의 높이에서 지지되며, 바닥면과 측면들로 둘러싸인 내부 공간이 형성된 복수의 곤충사육트레이; 상기 프레임에 의해 복수의 높이에서 지지되며, 상기 곤충사육트레이와 서로 다른 높이에 배치되는 복수의 식물재배트레이; 상기 양액보관탱크와 상기 각각의 식물재배트레이를 연결하는 제1 파이프; 및 상기 각각의 곤충사육트레이와 상기 양액생성기를 연결하는 제2 파이프를 포함할 수 있다. claims: 높이를 갖고 연장되는 프레임;식물을 재배하기 위한 양액이 저장되는 양액보관탱크;양액을 생성하여 상기 양액보관탱크에 제공하는 양액생성기;상기 프레임에 의해 복수의 높이에서 지지되며, 바닥면과 측면들로 둘러싸인 내부 공간이 형성된 복수의 곤충사육트레이;상기 프레임에 의해 복수의 높이에서 지지되며, 상기 곤충사육트레이와 서로 다른 높이에 배치되는 복수의 식물재배트레이;상기 양액보관탱크와 상기 각각의 식물재배트레이를 연결하는 제1 파이프;상기 양액생성기의 상측으로 연장되어 상기 각각의 곤충사육트레이와 상기 양액생성기를 연결하는 제2 파이프; 및상기 양액생성기의 하측으로 연장되어 상기 양액생성기와 상기 양액보관탱크를 연결하는 제3 파이프를 포함하되,상기 곤충사육트레이의 바닥면은 상기 제2 파이프가 연결되는 측을 향하여 하측으로 경사지게 형성되며,상기 양액생성기의 내부 공간은 상기 제3 파이프에 연결되는 부분이 상기 제3 파이프 측으로 직경이 점차 작아지도록 테이퍼지게 형성되어, 상기 곤충사육트레이로부터 상기 제2 파이프를 통해 배출되는 곤충 분변은 병목 현상에 의해 일부가 상기 양액생성기에 보관되며,상기 양액생성기는 물관을 통해 물탱크에 연결되고, 상기 물탱크로부터 곤충 분변을 용액화하여 양액을 생성하기 위한 물을 제공받으며, 상기 물관에는 상기 양액생성기로 전달되는 물의 양을 조절 가능한 밸브가 구비되어, 상기 양액생성기로 제공되는 물은 상기 양액생성기 내부에서 상기 곤충 분변과 혼합되어 양액을 생성하고, 생성된 양액이 상기 제3 파이프를 통해 상기 양액보관탱크에 전달되는 것을 특징으로 하는, 곤충 분변을 활용하여 식물을 재배하기 위한 식용곤충 사육장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

850/1059 Row 850: application_number: 1020200098305, combined_string: invention_title: 탈출방지부재를 갖춘 곤충 사육상자 abstract: 본 발명은 탈출방지부재를 갖춘 곤충 사육상자에 관한 것으로; 이의 목적은 다단으로 적재할 수 있는 사육상자의 내부 벽면 구조를 개선하여 사육 곤충이 벽면을 타고 올라가 환기홀(또는 손잡이 홀)을 통해 탈출하는 것을 방지할 수 있도록 하는 것이다.이를 위해 본 발명에 따른 『탈출방지부재를 갖춘 곤충 사육상자』에 의하면; 바닥면(310)과 벽면(320)을 구비하여 내부에 사육곤충과 먹이를 수용할 수 있도록 서식공간이 마련되며 상부가 개방된 사육상자 본체(300)와; 상기 사육상자 본체(300)의 벽면(320) 상부에 가로방향으로 연장된 복수개의 환기홀(400)과; 상기 사육상자 본체(300)의 벽면(320) 중앙부위 내측을 따라 부착되는 띠 형태의 부착부(510)와, 상기 부착부(510)에서 상기 사육상자 본체(300)의 내부 서식공간을 향해 수평방향으로 연장되어 사육곤충이 상기 사육상자 본체(300)의 벽면(320)을 타고 상측으로 올라가는 것을 방지하기 위한 띠 형태의 탈출방지부(520)로 이루어진 탈출방지부재(500)를; 포함하는 것을 특징으로 한다. claims: 바닥면(310)과 벽면(320)을 구비하여 내부에 사육곤충과 먹이를 수용할 수 있도록 서식공간이 마련되며 상부가 개방된 사육상자 본체(300)와;상기 사육상자 본체(300)의 벽면(320) 상부에 가로방향으로 연장된 복수개의 환기홀(400)과;상기 사육상자 본체(300)의 벽면(320) 중앙부위 내측을 따라 부착되는 띠 형태의 부착부(510)와, 상기 부착부(510)에서 상기 사육상자 본체(300)의 내부 서식공간을 향해 수평방향으로 연장되어 사육곤충이 상기 사육상자 본체(300)의 벽면(320)을 타고 상측으로 올라가는 것을 방지하기 위한 띠 형태의 탈출방지부(520)로 이루어진 탈출방지부재(500)를; 포함하는 것을 특징으로 하는 탈출방지부재를 갖춘 곤충 사육상자., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

851/1059 Row 851: application_number: 1020200091162, combined_string: invention_title: 애완동물 배변 자동 처리 장치 abstract: 본 발명은 간단한 구조로 배변을 처리한 배변 패드가 밀폐되도록 하여 악취 및 위생문제가 적절히 해소되도록 하고 대변과 소변을 구분하여 감지함으로써 배변 패드의 불필요한 낭비가 방지되도록 하는 애완동물 배변 자동 처리 장치에 관한 것으로, 본 배변 자동 처리 장치는 제1 본체(10)와, 상기 제1 본체(10)의 일측에 이격되게 구비되는 제2 본체(20)와, 상기 제1 본체(10)의 내부에 설치되는 처리구동부(30)와, 상기 제2 본체(20)의 내측에 구비되는 권취롤(40)과, 상기 권취롤(40)에 감기어 구비되는 배변 패드(50)와, 상기 제1 본체(10)와 제2 본체(20)의 사이에 한 쌍으로 구비되는 가이드판(60)과, 상기 제1 본체(10)의 외면에 설치되는 카메라(70)와, 상기 제1 본체(10)와 제2 본체(20)의 사이에 장착되는 하부지지판(80)과, 상기 제1 본체(10)에 설치되고 상기 배변 패드(50)의 상면을 지지하는 패드지지부(90)와, 상기 제1 본체(10)의 외면에 설치되는 엘이디(100)와, 상기 하나의 가이드판(60)의 상면에 수직으로 장착되는 격벽(110)을 포함한다. claims: 직사각판으로 구비되는 제1 베이스(11)와, 상기 베이스의 상면 둘레에 장착되는 둘레판(12)과, 상기 둘레판(12)의 상단에 개폐 가능하게 힌지 결합되는 제1 커버(13)와, 상기 둘레판(12)과 제1 커버(13)의 일측에 관통되게 형성되는 유입구(14)를 포함하는 제1 본체(10)와;상기 제1 베이스(11)의 일측으로 이격되게 구비되고 직사각판으로 형성되는 제2 베이스(21)와, 상기 제2 베이스(21)의 상면을 커버하도록 하부가 개방된 중공 입방체 형태로 구비되고 상기 제2 베이스(21)의 상면에 분해 가능하게 끼워지는 제2 커버(22)와, 상기 제2 커버(22)의 타측 하부에 관통되게 형성되는 배출구(23)를 포함하는 제2 본체(20)와;상기 제1 커버(13)의 내측으로 상기 제1 베이스(11)의 상면에 설치되고, 상기 유입구(14)를 통해 유입되는 배변 패드(50)를 감아서 처리하는 처리구동부(30)와;상기 제2 커버(22)의 내측으로 상기 제2 베이스(21)의 상면에 회전 가능하게 설치되는 권취롤(40)과;상기 권취롤(40)에 권취되고, 일단이 상기 처리구동부(30)와 연결되는 배변 패드(50)와;상기 제1 베이스(11)와 제2 베이스(21)의 내측 사이에 상호 이격되게 구비되고, 상기 처리구동부(30)와 권취롤(40)의 사이에 구비되는 상기 배변 패드(50)의 이동을 가이드하는 한 쌍의 가이드판(60)과;상기 제1 커버(13)의 외면에 설치되고, 상기 가이드판(60) 사이에 배치되는 상기 배변 패드(50)의 상면을 촬영하여 대변과 소변을 구별하는 카메라(70)와;상기 제1 베이스(11)와 제2 베이스(21)의 사이에 조립되어 연결되고, 상기 가이드판(60)의 하부로 상기 배변 패드(50)의 하면을 지지하는 하부지지판(80)을; 포함하고,상기 처리구동부(30)는,상기 배변 패드(50)의 양단에 대응하여 상기 제1 커버(13)의 내측으로 상기 제1 베이스(11)의 상면에 상호 이격되게 장착되고 하부측이 개구된 원호형으로 형성되는 한 쌍의 호형가이드(31)와,상기 호형가이드(31)의 외측으로 상기 제1 베이스(11)의 상면에 각각 장착되고 내부에 다수개의 기어가 연결되는 한 쌍의 기어박스(32)와,각각의 상기 기어박스(32)와 연결되어 회전되는 한 쌍의 회전축(33)과,상기 호형가이드(31)의 내측에 구비되고 각각의 상기 회전축(33)에 연결되는 한 쌍의 처리롤러(34)와,상기 처리롤러(34)의 외주면에 다수개가 방사상으로 돌출되게 장착되고 고무 재질로 형성되는 고무블레이드(34a)와,하나의 상기 기어박스(32)에 장착되고 상기 기어박스(32)에 연결되어 상기 처리롤러(34)를 시계방향으로 회전시키는 모터(35)와,상기 제1 베이스(11)의 상면에서 하부로 함몰된 상태로 상단이 노출되면서 회전 가능하게 구비되고 상기 기어박스(32)에 각각 연결되어 상기 모터(35)의 구동과 함께 반시계방향으로 회전되면서 상기 배변 패드(50)를 상기 제1 본체(10)의 내측으로 밀어 넣는 한 쌍의 하부롤러(36)를, 포함하고,상기 처리롤러(34)는,상기 회전축(33)에 분리되어 상기 회전축(33)을 따라 수평으로 이동 가능하게 구비되고,상기 처리구동부(30)는,상기 호형가이드(31)의 사이로 상기 제1 베이스(11)의 상면 중앙에 장착되고 호형으로 형성되며 상기 배변 패드(50)의 권취를 지지하는 호형지지부재(37)와,상기 처리롤러(34)의 내측면에 각각 부착되고 상기 고무블레이드(34a)보다 상대적으로 작은 직경을 가지며 상기 배변 패드(50)의 권취를 지지하는 한 쌍의 지지원판(38)과,상기 처리롤러(34)에 설치되고 상기 처리롤러(34)를 상기 회전축(33)을 따라 외측으로 탄성복원 가능하게 이동시킬 수 있는 탄성이동부(39)를, 더 포함하고,상기 탄성이동부(39)는,상기 기어박스(32)의 내측면과 상기 처리롤러(34)의 외측면 사이로 상기 회전축(33)에 끼워져 상기 처리롤러(34)를 탄성적으로 지지하는 스프링(391)과,상기 처리롤러(34)의 외측면에 다각형으로 형성되는 다각형홈(392)과,상기 지지원판(38)의 중앙부위에서 외측으로 돌출되게 형성되고 상기 다각형홈(392)에 분리 가능하게 끼워지는 다각형턱(393)과,상기 다각형턱(393)의 내측면에 구비되고 상기 다각형턱(393)을 관통하는 상기 회전축(33)의 단부에 부착되는 고정캡(394)을, 포함하는 것을 특징으로 하는 애완동물 배변 자동 처리 장치., Ltext: 농업, prediction: 임업
852/1059 Row 852: application_number: 1020200070150, combined_string: invention_title: 애꽃노린재류 무식물 증식 시스템 abstract: 본 발명은 애꽃노린재류 무식물(plant-less) 증식 시스템 및 애꽃노린재류 무식물(plant-less) 증식 방법에 관한 것으로서, 보다 상세하게는 식물 대체 채란용 물체, 대체먹이 및 사육 환경 최적화를 갖춘 애꽃노린재류 대량 증식 시스템 및 상기 시스템을 이용한 애꽃노린재류 대량 증식 방법에 관한 것이다. 본 발명에 따른 애꽃노린재류 무식물(plant-less) 증식 시스템은 국내 토착 천적인 참멋애꽃노린재(Orius minutus)의 적합한 환경요인 확인, 식물을 대체할 수 있는 채란용 물체 선발 및 경제적인 대체먹이 선발을 통해 기존 사육 시스템 대비 생산 공정 간소화 및 경제적인 생산 시스템 구축이 가능하다. claims: 환기구가 있는 사육 용기; 및상기 사육 용기 내부에,물 및 꿀물을 포함하는 수분 공급부;두께 3 ~ 5 mm이고 거친 면(rough side)을 갖는 코르크를 포함하는 채란부; 및명나방알과 철분이 코팅된 브라인쉬림프(Iron-coated brine shrimp)를 포함하는 먹이 공급부;를 포함하고,상기 사육 용기 외부에,온도, 상대습도 및 광주기를 조절하는 조절부를 포함하는 것을 특징으로 하는,애꽃노린재류 무식물(plant-less) 증식 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

853/1059 Row 853: application_number: 1020200068825, combined_string: invention_title: 산란장 abstract: 본 발명은 산란장 관리를 위해 내부로 들어가지 않아도 외부에서 관리할 수 있도록 함으로써, 산란장의 운영 관리가 수월하고 산란유도배지의 효과를 높일 수 있는 산란장을 제공하기 위한 것으로서, 성충들이 탈출하지 못하도록 제한된 공간을 만드는 망부재(100)와, 터널식(서랍식) 틀을 구비하고, 상기 터널식(서랍식) 틀을 통해 슬라이딩되어 상기 공간의 외부에서 수납되는 적어도 하나 이상의 리빙박스(400) 및 산란목 박스(300)를 보관하는 제1, 2 보관부(120)(130)와, 상기 망부재(100) 내부 공간 바닥면에 일측으로 일정한 경사각을 가지도록 구비되어, 산란장 내부에 쌓이는 성충사체들이 일측으로 이동되도록 유도하는 슬라이딩 유도부(140)와, 상기 일측에 구비되어, 상기 슬라이딩 유도부(140)에서 일측으로 이동되는 성충사체들을 포집하는 사체 포집부(150)를 포함할 수 있다. claims: 성충들이 탈출하지 못하도록 제한된 공간을 만드는 망부재(100)와, 터널식(서랍식) 틀을 구비하고, 상기 터널식(서랍식) 틀을 통해 슬라이딩되어 상기 공간의 외부에서 수납되는 적어도 하나 이상의 리빙박스(400) 및 산란목 박스(300)를 보관하는 제1, 2 보관부(120)(130)와, 상기 망부재(100) 내부 공간 바닥면에 일측으로 일정한 경사각을 가지도록 구비되어, 산란장 내부에 쌓이는 성충사체들이 일측으로 이동되도록 유도하는 슬라이딩 유도부(140)와,상기 일측에 구비되어, 상기 슬라이딩 유도부(140)에서 일측으로 이동되는 성충사체들을 포집하는 사체 포집부(150)를 포함하고,상기 슬라이딩 유도부(140)는 망부재(100)의 뒷면 벽과 상기 망부재(100)의 앞면에 위치하는 사체 포집부(150)와 일정한 경사각으로 구비되며, 상기 망부재(100)의 뒷면 벽과 연결되는 끝단부에 모터의 회전을 통해 진동을 발생시켜, 상기 발생되는 진동을 상기 슬라이딩 유도부(140)로 전달하여 상하 및 좌우방향으로 털어내는 효과를 제공하여 상기 슬라이딩 유도부(140)의 상부에 위치하는 성충사체를 하부의 사체 포집부(150)로 이동시키는 진동부(141)를 더 포함하며,상기 리빙박스(400) 및 산란목 박스(300)는 전면부를 오픈된 상부부터 중심부까지 일정한 기울기를 갖는 사선 형태로 구성하여 전면부의 일부가 오픈되는 산란장., Ltext: 농업, prediction: 임업
854/1059 Row 854: application_number: 1020200064707, combined_string: invention_title: 유충 사육 장치 및 방법 abstract: 본 발명은 유충 사육 방법에 관한 것으로, 사육 공간에 유충과 기본 먹이가 투입된 트레이를 반입하는 과정; 상기 유충을 사육하는 과정; 상기 사육 공간에서 외부로 상기 트레이를 반출하는 과정; 반출된 트레이에 보충 먹이를 투입하는 과정; 및 보충 먹이가 투입된 트레이를 상기 사육 공간에 재반입하는 과정;을 포함하여, 사육 공간의 유지 관리를 용이하게 하여 작업자의 업무 부담을 경감시킬 수 있고, 유지 관리 비용을 절감할 수 있다. claims: 유충을 사육할 수 있는 공간을 제공하는 사육부; 유충이 수용되는 트레이에 보충 먹이를 투입할 수 있도록, 상기 사육부의 외부에 설치되는 보충부;상기 사육부의 외부에 설치되고, 상기 사육부에 반입 및 반출시키기 위해 상기 트레이를 이송시킬 수 있는 이송부; 상기 사육부의 외부에 설치되고, 트레이에 유충과, 상기 유충이 먹을 기본 먹이를 투입하기 위한 트레이 셋팅부; 및상기 보충부와 상기 이송부의 동작을 제어하기 위한 제어부;를 포함하고, 상기 트레이 셋팅부는,상기 트레이에 유충을 투입하기 위한 유충 공급기; 및 상기 트레이에 상기 유충이 먹을 기본 먹이를 상기 트레이에 투입하기 위한 기본 먹이 공급기;를 포함하며,상기 유충 공급기는,유충을 저장할 수 있는 공간을 형성하는 유충 저장기;유충의 배출량을 조절하기 위해 상기 유충 저장기에 형성되는 배출기;상부가 개방되고, 상기 유충 저장기의 하부에 설치되는 용기; 및상기 용기를 회전시킬 수 있도록 지지하는 지지대;를 포함하는 유충 사육 장치.유충을 사육하는 방법으로서, 트레이에 기본 먹이를 투입하는 과정;기본 먹이가 투입된 트레이에 유충을 투입하는 과정;사육 공간에 유충과 기본 먹이가 투입된 트레이를 반입하는 과정;상기 유충을 사육하는 과정;상기 사육 공간에서 외부로 상기 트레이를 반출하는 과정; 반출된 트레이에 보충 먹이를 투입하는 과정; 및보충 먹이가 투입된 트레이를 상기 사육 공간에 재반입하는 과정;을 포함하고, 상기 기본 먹이를 투입하는 과정은, 상기 트레이에 미리 설정된 무게의 기본 먹이를 투입하는 과정을 포함하고, 상기 유충을 투입하는 과정은, 상기 유충의 무게를 측정하는 과정 및 상기 트레이에 투입된 기본 먹이의 무게에 따라 정해지는 무게의 유충을 트레이에 투입하는 과정을 포함하는 유충 사육 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

855/1059 Row 855: application_number: 1020200055015, combined_string: invention_title: 식용곤충용 사육 장치 abstract: 식용곤충용 사육 장치가 개시된다. 본 발명의 일 측면에 따르면, 연속하여 배치되는 복수의 단위 프레임을 포함하며 식용곤충 사육이 가능한 사육 공간을 형성하는 본체, 식용곤충이 이동 가능한 면을 형성하기 위해 복수의 단위 프레임에 설치되는 사육망, 및 본체에 설치되어 사육 공간의 부피를 조절하기 위해 본체의 길이를 조절하는 길이 조절 유닛을 포함하는 식용곤충용 사육 장치가 제공된다. claims: 연속하여 배치되는 복수의 단위 프레임을 포함하며 식용곤충 사육이 가능한 사육 공간을 형성하는 본체;상기 식용곤충이 이동 가능한 면을 형성하기 위해 상기 복수의 단위 프레임에 설치되는 사육망; 및상기 본체에 설치되어 상기 사육 공간의 부피를 조절하기 위해 상기 본체의 길이를 조절하는 길이 조절 유닛을 포함하는 식용곤충용 사육 장치., Ltext: 농업, prediction: 임업
856/1059 Row 856: application_number: 1020200055016, combined_string: invention_title: 식용곤충용 액체사료 공급 장치 abstract: 식용곤충용 액체사료 공급 장치가 개시된다. 본 발명의 일 측면에 따르면, 내부에 식용곤충용 액체사료를 저장하는 사료 저장부, 및 식용곤충용 액체사료를 흡수 가능한 재질로 이루어지며, 일측이 사료 저장부 내부에 설치되어 식용곤충용 액체사료를 흡수하는 사료 공급부를 포함하고, 사료 공급부는 사료 저장부 외부로 연장되어 식용곤충에게 액체사료를 공급하는 식용곤충용 액체사료 공급 장치가 제공된다. claims: 내부에 식용곤충용 액체사료를 저장하는 사료 저장부; 및상기 식용곤충용 액체사료를 흡수 가능한 재질로 이루어지며, 일측이 상기 사료 저장부 내부에 설치되어 상기 식용곤충용 액체사료를 흡수하는 사료 공급부를 포함하고,상기 사료 공급부는 상기 사료 저장부 외부로 연장되어 식용곤충에게 액체사료를 공급하는, 식용곤충용 액체사료 공급 장치.제1에 있어서,상기 사료 저장부에 저장된 상기 식용곤충용 액체사료의 양을 감지하는 사료 감지 센서를 더 포함하는 식용곤충용 액체사료 공급 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

857/1059 Row 857: application_number: 1020200054204, combined_string: invention_title: 친환경 유기성 폐기물 처리용 동물 사육 시스템 abstract: 본 발명은 친환경 유기성 폐기물 처리용 동물 사육 시스템에 있어서, 특히 동애등에 사육용 파레트의 하부에 발열수단을 더 장착하여 음식물 쓰레기를 데워서 공급함으로서 동애등에의 빠른 성장을 유도하여 대량 사육이 가능토록 구성하고, 기둥 조립체를 다단으로 구성하여 조립성이 뛰어난 구조체를 제공한 것을 특징으로하는 친환경 유기성 폐기물 처리용 동물 사육 시스템에 관한 것으로,동애등에를 수납하는 동애등에 사육상자와; 상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과; 상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와; 상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하여 이루어지고; 상기 기둥 조립체는, 하부에 원통형 연결체(210)가 설치되고, 원통형 연결체(210)의 끝단에는 양측이 경사진 합체용 돌기(210a)가 설치되어 이루어지는 제 1 프레임(200)과; 상기 제 2 프레임의 하부에 위치되며 제 1 프레임과 원터치로 합체되는 제 2 프레임(300)으로 이루어지는 것이 특징이다. claims: 동애등에를 수납하는 동애등에 사육상자와;상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과;상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와;상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하여 이루어지고;상기 기둥 조립체는,하부에 원통형 연결체(210)가 설치되고, 원통형 연결체(210)의 끝단에는 양측이 경사진 합체용 돌기(210a)가 설치되어 이루어지는 제 1 프레임(200)과;상기 제 1 프레임의 하부에 위치되며 제 1 프레임과 원터치로 합체되는 제 2 프레임(300)으로 이루어지며;상기 제 2 프레임(300)은,최외각에 설치되는 제 1 합체용 몸체(310)와;상기 제 1 합체용 몸체와 일정거리 이격되어 설치되어 공간부를 형성하여 공간부로 합체용 돌기가 진입되도록 하고, 일단에 합체용 홈을 형성하여 합체용 돌기가 삽입 고정되도록 하는 제 2 합체용 몸체(320)와;상기 제 1 합체용 몸체와 제 2 합체용 몸체 사이에 설치되는 제 1 탄발수단(330)과;상기 제 1 탄발수단 전단에 설치되어 제 1 합체용 몸체의 합체용 돌기가 진입하면 후퇴하여 제 1 탄발수단을 압박하고 합체용 돌기가 제 2 합체용 몸체의 합체용 홈에 삽입되면 제 1 탄발수단의 탄발에 의해 전진하여 합체용 돌기 상부에 위치되는 제 1 탄발수단 유동부(350)와;상기 제 1 탄발수단 유동부 후단에 설치되며 탄발 기능을 갖는 제 2 탄발수단(340)과;상기 제 2 탄발수단의 외측에 설치되어 제 2 탄발수단을 구동하는 원통형 형상의 구조체로서 뒤로 후퇴하면서 제 2 탄발수단을 구동하기 위한 제 2 탄발수단 유동부(360)와;상기 제 2 탄발수단의 후단에 설치되어 제 2 탄발수단의 움직임을 지지하기 위한 제 2 탄발수단 지지부(370)를 포함하여 구성하고;상기 제 2 탄발수단 유동부는,손으로 파지를 용이하게 하기 위해 테두리면에 다수개의 요철을 형성하며;상기 제 1 프레임의 합체용 돌기와 제 2 프레임의 합체용 홈은 양측면에 경사면을 형성하여 이루어진 것을 특징으로 하는 친환경 유기성 폐기물 처리용 동물 사육 시스템., Ltext: 농업, prediction: 임업
858/1059 Row 858: application_number: 1020200054209, combined_string: invention_title: 유기성 폐기물 먹이를 이용한 파리 에벌레 사육 장치 abstract: 본 발명은 유기성 폐기물 먹이를 이용한 파리 에벌레 사육 장치에 있어서, 특히 동애등에 사육용 파레트의 하부에 발열수단을 더 장착하여 음식물 쓰레기를 데워서 공급함으로서 동애등에의 빠른 성장을 유도하여 대량 사육이 가능토록 구성하고, 아울러 고른 열전달을 통해서 동애등에의 고른 사육이 가능토록 구성한 것을 특징으로하는 유기성 폐기물 먹이를 이용한 파리 에벌레 사육 장치에 관한 것으로,동애등에를 수납하는 동애등에 사육상자와; 상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과; 상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와; 상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단과; 상기 발열수단의 상부에 위치되며 순환액을 순환시키되 발열수단에서 발생한 열을 흡수하여 순환액이 가열되도록한후 고르게 사육상자에 순환액이 접촉되도록하는 순환액 수조를 포함하여 더 구성함이 특징이다. claims: 동애등에를 수납하는 동애등에 사육상자와;상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과;상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와;상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단과;상기 발열수단의 상부에 위치되며 순환액을 순환시키되 발열수단에서 발생한 열을 흡수하여 순환액이 가열되도록한후 고르게 사육상자에 순환액이 접촉되도록하는 순환액 수조를 포함하여 구성하고;상기 순환액 수조는,상기 순환액 수조 몸체의 하부 일측을 통해 설치되며 외부에서 공급되는 순환액을 순환액 수조 내부로 공급하는 순환액 입력배관(42)과;상기 순환액 수조 몸체의 상부 타측을 통해 설치되며 순환액 수조 내부를 순환한 순환액을 외부로 출력시키는 순환액 출력배관(43)과;상기 순환액 입력배관을 통해 입력되는 순환액을 임시저장하는 순환액 입력부(44)와;상기 순환액 출력배관을 통해 순환액을 출력하기 전에 임시저장하는 순환액 출력부(45)와;상기 순환액 수조 몸체의 내부에 설치되는 칸막이 형태로서 순환액 입력부와 중앙 공간부 사이에 설치되며 다수개의 입력홀을 형성하여 상기 입력홀을 통해 순환액이 입력되어 중앙 공간부쪽으로 이동하여 순환액이 뎁혀지면서 출력되도록 구성하는 순환액 입력용 패널(46)과;상기 순환액 수조 몸체의 내부에 설치되는 칸막이 형태로서 순환액 출력부와 중앙 공간부 사이에 설치되며 다수개의 출력홀을 형성하여 상기 중앙 공간부에 존재하는 순환액이 순환액 출력부쪽으로 이송되도록 구성하는 순환액 출력용 패널(47)을 포함하여 구성함을 특징으로 하는 유기성 폐기물 먹이를 이용한 파리 에벌레 사육 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

859/1059 Row 859: application_number: 1020200054214, combined_string: invention_title: 유기성 폐기물 처리를 위한 동애등에 사육장치 abstract: 본 발명은 친환경 유기성 폐기물 처리용 동물 사육 시스템에 있어서, 특히 동애등에 사육용 파레트의 하부에 발열수단을 더 장착하여 음식물 쓰레기를 데워서 공급함으로서 동애등에의 빠른 성장을 유도하여 대량 사육이 가능토록 구성하고, 기둥 조립체를 다단으로 구성하여 조립성이 뛰어난 구조체를 제공한 것을 특징으로하는 친환경 유기성 폐기물 처리용 동물 사육 시스템에 관한 것으로,동애등에를 수납하는 동애등에 사육상자와; 상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과; 상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와; 상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하여 이루어지고; 상기 기둥 조립체는, 하부에 원통형 연결체(210)가 설치되고, 원통형 연결체(210)의 끝단에는 양측이 경사진 합체용 돌기(210a)가 설치되어 이루어지는 제 1 프레임(200)과; 상기 제 2 프레임의 하부에 위치되며 제 1 프레임과 원터치로 합체되는 제 2 프레임(300)으로 이루어지는 것이 특징이다. claims: 내부에 동애등에 사육을 위한 공간부를 갖는 동애등에 사육용 하우징과;상기 동애등에 사육용 하우징 내부에 설치되며, 동애등에를 수납하는 동애등에 사육상자와;상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과;상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와;상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단과;상기 사육용 하우징의 내부 일단에 설치되며, 사육상자에 난방을 제공하는 난방장치를 포함하여 이루어지고;상기 난방장치(1100)는,난방장치 본체(1110)와;난방장치 본체(1110)의 점화부(1120)에서 점화되어 발생되는 열기를 출력하는 점화부 출력배관(1130)과;상기 점화부 출력배관에 연결되어 점화부로부터 제공되는 열기를 외부로 방사시키는 지그재그 형태의 방열턱트(1140)와;상기 방열덕트 주변에 설치되어 점화부에서 점화되는 열기를 임시저장하는 열 저장수단(1150)과;상기 방열덕트의 출력단에 연결하되 점화부 출력배관에 연결하여 방열덕트로 재회전시킴으로서 폐열을 회수시키는 열 회수용 배관(1160)과;상기 열 회수용 배관에 열기 토출용 공간부를 두고 일정거리 이격되어 설치하되, 점화부 출력배관에 고정설치되어 열 회수용 배관을 통해 제공되는 폐열을 방열덕트로 재회전시키도록 유도하는 폐열 회수용 중계관(1170)과;본체의 일단에 설치하되 점화부 출력배관에 위치되어 점화부 출력배관을 통해 배출되는 과열기를 외부로 출력시키는 열기 배출수단(1180)으로 이루어지며;상기 폐열 회수용 중계관(1170)은,열기가 재인입시에 점화부(1120)로 열기의 방향이 향하지 못하도록, 상기 점화부 출력배관(1130)과 경사지게 결합하여 구성하고;상기 방열덕트(1140)는,난방장치 본체의 하부에 배치되는 하부덕트(1141)과, 상기 하부덕트에 일체로 연결하되 난방장치 본체의 상부에 배치되는 상부덕트(1142)와, 상기 상부덕트와 하부덕트를 연결하는 수직덕트(1143)로 이루어지고, 상부덕트 또는 하부덕트에 공기 통과용 홀(1190)을 더 형성하여 이루어지며;상기 방열덕트(1140)는,상기 상부덕트 또는 하부덕트 표면 일단에 설치되는 공기 개폐 조절용 모터(1191)와, 상기 공기 개폐 조절용 모터의 축에 연장설치되며 모터의 회전에 상응하여 움직이면서 공기 통과용 홀에 접면되어 공기 통과용 홀의 개방정도를 결정하는 공기 조절용 패널(1192)을 더 설치하여 이루어짐을 특징으로 하는 유기성 폐기물 처리를 위한 동애등에 사육장치., Ltext: 농업, prediction: 임업
860/1059 Row 860: application_number: 1020200054218, combined_string: invention_title: 친환경 에너지팜 시스템 abstract: 본 발명은 친환경 에너지팜 시스템에 있어서, 특히 태양광을 활용하여 에너지를 생산하고 여기서 생성된 에너지를 이용하여 제한된 공간을 최대한 활용하면서도, 노동력이 절감되고 생산 수율이 높은 곤충 유충의 사육 시스템을 제공하는 것을 특징으로 하는 친환경 에너지팜 시스템에 관한 것으로,온도 및 습도조절부, 수분공급부를 구비하고, 센서를 구비하여 온도, 습도 및 수분공급을 제어하는 제어 장치를 포함하는 유충 사육용 하우징과; 태양광선을 전기에너지로 변환하여 전력을 생산 및 저장하면서 배터리와 인버터를 통해 제어장치 및 유충 사육용 하우징의 각 부하로 직류 또는 교류의 동작 전원을 공급하기 위한 태양광 발전부와; 상기 하우징 내부에 설치되며 유충을 사육하기 위한 유충 사육용 상자와; 상기 유충 사육용 상자의 바닥면에 설치되며 유충 사육용 상자에 열을 제공하기 위한 방열수단과; 상기 유충 사육용 상자를 지지하기 위한 철골 구조물을 포함하여 구성함이 특징이다. claims: 온도 및 습도조절부, 수분공급부를 구비하고, 센서를 구비하여 온도, 습도 및 수분공급을 제어하는 제어 장치를 포함하는 유충 사육용 하우징과;태양광선을 전기에너지로 변환하여 전력을 생산 및 저장하면서 배터리와 인버터를 통해 제어장치 및 유충 사육용 하우징의 각 부하로 직류 또는 교류의 동작 전원을 공급하기 위한 태양광 발전부와;상기 하우징 내부에 설치되며 유충을 사육하기 위한 유충 사육용 상자와;상기 유충 사육용 상자의 바닥면에 설치되며 유충 사육용 상자에 열을 제공하기 위한 방열수단과;상기 유충 사육용 상자를 지지하기 위한 철골 구조물을 포함하고;상기 제어장치는,상기 하우징 내에 설치되며, 외부의 원격 제어기 또는 통신 가능하게 결합된 통신기기를 통해 입력되는 사용자설정신호를 무선 수신하여 주제어부로 전달하는 원격 수신부와;상기 하우징의 내부 및 그의 주변영상 촬영이 가능한 위치에 설치되어 하우징의 내부 및 그 주변영상을 실시간 촬영하여 기록하고 주제어부로 전달하는 영상 촬영 및 기록부와;상기 원격 수신부를 통해 수신되는 사용자 설정신호에 따라 온도 및 습도조절부, 수분공급부의 동작을 선택 제어하기 위한 구동신호를 생성하여 상기 온도 및 습도 조절부 및 수분 조절부로 전달하고, 그에 따른 각 조절부의 상태 정보와 영상신호의 무선 전송을 제어하는 주제어부와;상기 주제어부에 전기적으로 접속되어 정보를 출력하는 온도 및 습도 센서 및 수분함량측정 센서와;사용자 설정신호에 따라 상기 주제어부에서 전달되는 작동 신호에 의해 작동되는 온도 및 습도 조절부 및 수분공급부를 포함하여 구성되고;상기 방열수단의 하부에는 순환액을 순환시키되 가열수단에서 발생한 열을 흡수하여 순환액이 가열되도록한후 고르게 사육상자에 순환액이 접촉되도록하는 순환액 수조와;상기 순환액 수조의 하단에 설치되어 순환액 수조에 히팅열을 제공하는 가열수단을 더 포함하여 구성하며;상기 순환액 수조는,상기 순환액 수조 몸체의 하부 일측을 통해 설치되며 외부에서 공급되는 순환액을 순환액 수조 내부로 공급하는 순환액 입력배관(42)과;상기 순환액 수조 몸체의 상부 타측을 통해 설치되며 순환액 수조 내부를 순환한 순환액을 외부로 출력시키는 순환액 출력배관(43)과;상기 순환액 입력배관을 통해 입력되는 순환액을 임시저장하는 순환액 입력부(44)와;상기 순환액 출력배관을 통해 순환액을 출력하기 전에 임시저장하는 순환액 출력부(45)와;상기 순환액 수조 몸체의 내부에 설치되는 칸막이 형태로서 순환액 입력부와 중앙 공간부 사이에 설치되며 다수개의 입력홀을 형성하여 상기 입력홀을 통해 순환액이 입력되어 중앙 공간부쪽으로 이동하여 순환액이 뎁혀지면서 출력되도록 구성하는 순환액 입력용 패널(46)과;상기 순환액 수조 몸체의 내부에 설치되는 칸막이 형태로서 순환액 출력부와 중앙 공간부 사이에 설치되며 다수개의 출력홀을 형성하여 상기 중앙 공간부에 존재하는 순환액이 순환액 출력부쪽으로 이송되도록 구성하는 순환액 출력용 패널(47)을 포함하여 구성함을 특징으로 하는 친환경 에너지팜 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

861/1059 Row 861: application_number: 1020200051882, combined_string: invention_title: 발열수단을 갖는 동애등에 대량 사육 시스템 abstract: 본 발명은 발열수단을 갖는 동애등에 대량 사육 시스템에 있어서, 특히 동애등에 사육용 파레트의 하부에 발열수단을 더 장착하여 음식물 쓰레기를 데워서 공급함으로서 동애등에의 빠른 성장을 유도하여 대량 사육이 가능토록 구성한 것을 특징으로하는 발열수단을 갖는 동애등에 대량 사육 시스템에 관한 것으로,동애등에를 수납하는 동애등에 사육상자와; 상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과; 상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하되, 상기 발열수단은, 지그재그로 배열되어 전기에너지를 열에너지로 변환시키기 위한 열선; 및 상기 열선이 방수 및 절연이 되도록 열선을 사이에 두고 서로 압착되어 결합되는 상판 및 하판으로 이루어지고; 상기 동애등에 사육상자의 일측에 위치하며 유해공기를 태우기 위한 유해공기 버너부를 포함하여 구성함이 특징이다. claims: 동애등에를 수납하는 동애등에 사육상자와;상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과;상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하되, 상기 발열수단은, 지그재그로 배열되어 전기에너지를 열에너지로 변환시키기 위한 열선 및, 상기 열선이 방수 및 절연이 되도록 열선을 사이에 두고 서로 압착되어 결합되는 상판 및 하판으로 이루어지고;상기 동애등에 사육상자의 일측에 위치하며 유해공기를 태우기 위한 유해공기 버너부를 포함하여 구성하고;상기 유해공기 버너부는,불꽃방전 전기 공급용 스위칭 수단(2221)과; 불꽃방전 전기 공급용 스위칭 수단(2221)에 장착되어 불꽃방전을 자동으로 재점화 시키기 위한 불꽃방전 재점화 스위칭 수단(2222)과; 상기 불꽃방전 재점화 스위칭 수단(2222)에 연결되어 불꽃방전 재점화를 위한 신호를 출력하는 불꽃방전 재점화 회로부(2223)가 설치되어 이루어지며;상기 불꽃방전 재점화 스위칭 수단(2222)은,상기 불꽃방전 전기 공급용 스위칭 수단(2221)의 테두리면에 설치되어 불꽃방전 전기 공급용 스위칭 수단(2221)이 회전하면 동시에 회전하는 피니언 기어(2222a)와;상기 피니언 기어(2222a)의 회전에 의해서 수평으로 슬라이딩 이동하도록 원기둥 또는 사각기둥 형상이며 피니언 기어(2222a)와 접촉면에 랙기어(2222e)가 형성되어 이루어지는 제 1 슬라이딩 이송부재(2222b)와;상기 제 1 슬라이딩 이송부재(2222b)의 내측에 결합되며 제 1 슬라이딩 이송부재(2222b)가 움직이면 이에 연동하여 움직이면서 불꽃방전 재점화 회로부(2223)를 스위칭 시키는 제 2 슬라이딩 이송부재(2222c)와;상기 제 1 슬라이딩 이송부재(2222b)의 끝단과 제 2 슬라이딩 이송부재(2222b)의 시작단에 각각 접속되며 불꽃방전 재점화 회로부(2223)의 스위칭 상태를 유지시키는 역할을 하는 인장 스프링(2222d)을 포함하여 이루어지고;상기 불꽃방전 재점화 회로부(2223)는,12볼트 리듐전지, 차량용 축전지 또는 일반용 전지를 다수개 직렬 연결하여 필요한 전압을 공급하기 위해 설치되는 직류 전원부(2101)와;상기 직류 전원부에 일단이 연결되고, 불꽃방전 전기 공급용 스위칭 수단이 회전될때 스위칭되어 온이 되는 불꽃방전 재점화 스위치(2102)와;상기 불꽃방전 재점화 스위치가 온 되면 전기가 공급되어 승압된 교류 전류를 출력하는 발진 승압 회로부(2103)와;상기 발진 승압 회로부의 출력단에 연결되어 전기적 공급에 의해서 온 되는 방전 전극 전기 공급용 스위칭부(2108)와;상기 방전 전극 전기 공급용 스위칭부의 출력단에 설치되며 고압을 발생시키는 고압 승압 회로부(2107)와;상기 고압 승압 회로부에 의해서 공급되는 고압의 전원이 연결되어 이루어지는 고압 방전 간격제(2113a, 2113b)와;상기 고압 방전 간격제에 의해서 제공된 전원을 이용하여 방전이 이루어지면서 점화시켜 불꽃이 타오르도록 유도하는 방전 전극(2114)과;상기 방전 전극과 베이스단이 연결되고 에미터단 및 콜렉터단이 고압 승압 회로부 및 방전 전극 전기 공급용 스위칭부에 연결되며, 공간부에 불꽃이 발생되면 열전자에 의해서 폐회로를 형성하면서 스위칭되어 방전 전극 전기 공급용 스위칭부로 향하는 전원을 차단시켜 방전 전극이 점화되는 것을 차단하고, 외부 바람이나 습기에 의해서 불꽃방전 불꽃이 꺼지면 열전자의 소멸로 인하여 폐회로가 깨지면서 스위칭이 오프되고 이에 따라 방전 전극 전기 공급용 스위칭부로 향하는 전원을 온 시켜 방전 전극이 점화되도록 유도하는 기능을 하는 방전 전극 차단용 스위칭부(2118)를 포함하여 구성함을 특징으로 하는 발열수단을 갖는 동애등에 대량 사육 시스템., Ltext: 농업, prediction: 임업
862/1059 Row 862: application_number: 1020200050468, combined_string: invention_title: 숯을 이용한 벌통 관리구 abstract: 본 발명은 숯을 이용한 벌통 관리구에 관한 것으로서, 숯을 이용하여 벌통 내부의 공기정화 및 습도조절 작용이 지속적으로 이루어질 수 있게 되어 벌통의 관리 효율을 향상시키는 효과를 나타내기 위한 것이다.이를 실현하기 위한 본 발명은, 벌통의 내부에 구비하여 습도를 조절하는 벌통 관리구로서, 습기의 내부 유입 차단을 위한 방수커버(10)와; 상기 방수커버(10)의 내부에 삽입 구성되되, 내부에는 다수의 숯(21)이 보관되는 숯포(20);를 포함하는 구성을 이루는 것을 특징으로 한다. claims: 벌통의 내부에 구비하여 습도를 조절하는 벌통 관리구로서,습기의 내부 유입 차단을 위한 방수커버(10)와;상기 방수커버(10)의 내부에 삽입 구성되되, 내부에는 다수의 숯(21)이 보관되는 통기성 숯포(20);를 포함하되,상기 방수커버(10)는 통기성을 위한 부직포 재질의 내피층(10a)과, 습기 차단을 위한 세라믹 성분이 박막으로 코팅 형성된 외피층(10b)으로 이루어지며,상기 방수커버(10)의 일측은 숯포(20)의 교체가 가능하도록 개방된 구조를 이루며, 상기 개방 부위에는 개폐를 위한 지퍼부(11)가 구비되고,상기 방수커버(10) 일측에는 소금의 보관이 이루어지는 소금 보관팩(12)이 구비된 것을 특징으로 하는 숯을 이용한 벌통 관리구., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

863/1059 Row 863: application_number: 1020200047602, combined_string: invention_title: 양봉통 내부 검사 장치 abstract: 본 발명은 적층된 양봉통을 쉽고 간편하게 개방하여 양봉통의 내부 검사가 용이하게 이루어지도록 하는 양봉통 내부 검사 장치에 관한 것이다.본 발명의 양봉통 내부 검사 장치는 상하로 적층된 양봉통 중 상단에 위치한 양봉통(10)을 후방으로 젖혀서 거치시키는 거치대(100)와, 상기 거치대에 고정된 연결부재(20)와, 상단에 위치한 양봉통이 후방으로 젖혀질 때 하부에 위치한 양봉통(20)이 유동되지 않도록 상기 연결부재에 매달린 상태로 거치되는 중앙부(301)와 하부에 위치한 양봉통을 감싼 상태로 결속되는 양단부(302)를 구비한 탄성재질의 결속로프(300)를 포함한다. claims: 상하로 적층된 양봉통 중, 상단에 위치한 양봉통을 후방으로 젖혀서 거치시키는 거치대;상기 거치대에 고정된 연결부재; 및상단에 위치한 양봉통이 후방으로 젖혀질 때 하부에 위치한 양봉통이 유동되지 않도록, 상기 연결부재에 매달린 상태로 거치되는 탄성재질의 결속로프;를 포함하고,상기 결속로프는 상기 연결부재에 매달린 상태로 거치되는 중앙부와, 하부에 위치한 양봉통을 감싼 상태로 결속되는 양단부를 포함하며,상기 결속로프의 양단부 중 일측단부에는 후크가 결합되고 타측단부에는 상기 후크에 대응되는 적어도 하나 이상의 고리가 결합되고,상기 고리는 결속로프의 타측단부에 결합되는 본체와, 상기 본체의 단부로부터 연장형성된 고리편으로 구성된 양봉통 내부 검사 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

864/1059 Row 864: application_number: 1020200042237, combined_string: invention_title: 벌통 abstract: 본 발명은 다수의 관통공(201), (202)이 형성된 본체(200) 내부 바닥 전, 후방에 배출구(203), (203')를 형성하여 이물질 제거시 개방과 폐쇄를 동시에 병행하도록 형성하고, 이물질 제거시에나, 그늘의 공기를 유입하기 위해 개방하도록 슬라이드 홈(216a)에 환기망(216b)이 형성된 개폐판(216)을 삽입장착하여 본체(200) 내부의 불필요한 이물질을 제거할 때 개방되게 함과 아울러 배출구(203), (203')로 이물질을 제거하거나 폐쇄할 수 있도록 본체(200) 바닥에 제거기(211)를 장착하고, 상기 본체(200)에 형성된 돌출구(204)의 숫체결부(260)를 계상통(230)의 암체결부(270)에 결합함에 따라 계상통(230)을 연장 고정하여 뚜껑(100)을 덮어 고정할 수 있을 뿐만 아니라, 본체(200) 양 중앙 하측의 고리(224')로 인해 본 발명의 벌통(1)을 지면판(400)에 고정할 수 있음은 물론, 뚜껑(100) 내부에 여왕벌을 감금할 수 있는 분봉망(101)을 망고정구(101')로 고정하도록 형성하여 분봉으로 인한 벌들의 외부탈출을 막을 수 있도록 형성하고, 지면에 말뚝(221)을 꽂아 고정된 지면판(400)에 고리(224')로 고정된 벌통(1)이 강풍에 위치이동 되지 않도록 하는 것은 물론, 상기 본체(200)와 계상통(230)을 덮는 뚜껑(100)의 통풍구(110)에 통기구(114)를 장착하여 벌통(1)의 본체(200) 및 계상통(230) 내부의 온도, 습도를 온습도기(150)를 통해 확인 한 다음, 본체(200) 및 계상통(230) 내부의 환기를 환기망(216b)과 통기구(114)의 조절구(116)로 조절할 수 있도록 형성하고, 상기 본체(200)의 전면에 장착되는 전면수단(300)에는 이착륙판(306)에 형성된 관통공(302a)의 턱(306') 상단부에 선택패널(312)이 장착된 벌출입부(310)를 나사(50) 결합하여 선택패널(312)을 구성하는 조절판(312b)의 일측 상하에 U자형출입구(312a)와 O자형출입구(312a')를 형성하여 벌들의 출입을 임의로 통제 및 조절할 수 있도록 형성하고, 상기 이착륙판(306) 하측에는 좌, 우 양측에 각각 전, 후선택공(319), (319')을 형성하여 전면수단(300)을 형성하는 관통공(303), (303')에 화분함(320)과 벌사양부(350)를 슬라이드 삽입장착하고, 상기 벌사양부(350)에는 물과 사양액이 공급되는 물공급관(355), 액공급관(356)에 연질막(358a')이 형성된 부력(358을 장착한 물통(353), 액통(354)을 형성하여 물통로(355a'), 액통로(356a')를 통해 젖어들도록 물심지(355a), 액심지(356a)가 삽입된 물유입통(353'), 액유입통(354')을 형성하여 벌들이 소비하는 물과 사양액의 소비량에 따라 일정량이 공급되도록 형성하고, 상기 본 발명의 벌통(1)을 장, 단거리의 이동시 선택패널(312)의 조절판(312b)으로 벌출입부(310)의 관통공(301)을 봉쇄하거나, 출입구인 관통공(301)을 일정 길이 제한할 수 있는 것을 포함하여 구성된 것을 특징으로 한다. claims: 돌출구(204)의 양 중앙에 숫체결부(260)를 형성한 본체(200)의 하측 중앙부에 판결합부(280)를 장착하여 다수의 통공(60)을 통해 지면에 다수의 말뚝(221)으로 고정된 지면판(400)에 고리(224')가 고정되도록 형성하고,상기 본체(200)의 전방에는 관통공(201), (202)을 형성하고,상기 본체(200)의 상부에 안착하는 계상통(230)의 상, 하돌출턱(231), (231')에는 체결수단(250)을 형성하는 숫체결부(260)와 암체결부(270)를 장착하고,상기 본체(200)의 돌출구(204)에 숫체결부(260)를 장착하여 뚜껑(100)에 형성된 암결합부(270)에 고정할 수 있도록 형성하고,상기 본체(200) 좌우의 락(224a')에는 판결합부(280)를 형성하는 고리(224')의 돌기(224a)를 삽입하도록 형성하고,상기 본체(200)에 형성된 배출구(203), (203') 전후방에는 개폐판(216)이 슬라이드 장착되는 홈(216a')을 형성하고,상기 본체(200)의 홈(216a')에는 일측 단부의 손잡이(216a')와, 타측 단부에 환기망(216b)이 형성된 개폐판(216)이 슬라이드 삽입되도록 형성하고,상기 본체(200) 내부의 좌우 슬라이드장홈(200')에는 막음판(213')과 커트기(214)가 형성된 제거기(211)를 장착하여 전, 후방으로 슬라이드 함과 동시에 배출구(203), (203')를 개폐하도록 형성하고,상기 본체(200)의 지지대(200a) 저면에는 말뚝(221)의 헤드(221')가 삽입되도록 고정홈(206a)을 형성한 고정구(206)에 잠금부(330)의 잠금봉(332')이 삽입되는 연장고정홈(206a')을 형성하여 장착하고,상기 본체(200)의 중앙 저면에는 뚜껑(100)의 장부맞춤돌기(108)와 결합하도록 장부맞춤홈(208)을 형성하고,상기 본체(200)의 지지대(200a) 저면에 장착된 고정구(206)의 연장고정홈(206a')에는 뚜껑(100) 전후방에 장착된 잠금부(330)의 잠금봉(332')이 삽입되도록 구성한 것을 특징으로 하는 벌통., Ltext: 농업, prediction: 임업
865/1059 Row 865: application_number: 1020200030289, combined_string: invention_title: 동애등에 사육시설물 abstract: 본 발명은 동애등에 사육시설물에 관한 것으로서 더욱 상세하게는 사육상자가 각 층별로 순환가능하도록 하는 레일로 및 지지프레임부를 통해 동애등에 유충이 대량으로 수용가능하도록 하며 레일로 일측에 승하강가능하도록 설치되는 승하강작업대를 통해 먹이 공급 및 유충 수거가 신속하고 용이하게 이루어지도록 함에 따라 유충 사육의 대량화는 물론 작업의 용이성을 동시에 충족할 수 있는 동애등에 사육시설물에 관한 것이다. 이를 위해 본 발명은 동애등에 유충이 수용되어 사육되도록 일정 수용공간이 형성되는 복수개의 사육상자와; 상기 복수개의 사육상자가 수평면 상에 레일로를 따라 이동가능하도록 지지되되 상기 레일로가 다단층으로 위치되어 지지되도록 하는 지지프레임부와; 상기 다단층으로 이루어지는 지지프레임부의 레일로 일측 단부에 선택적으로 위치되는 승하강작업대; 및 상기 승하강작업대가 위치되는 레일로의 타측 단부측에 위치되며 다단층의 레일로 각각에 고정설치되는 고정작업대;를 포함하되, 상기 레일로는 제1방향으로 이송하는 제1이송레일로와, 상기 제1이송레일로 일측에 평행하게 설치되며 제2방향으로 이송하는 제2이송레일로를 포함한다. claims: 동애등에 유충이 수용되어 사육되도록 일정 수용공간이 형성되는 복수개의 사육상자와; 상기 복수개의 사육상자가 수평면 상에 레일로를 따라 이동가능하도록 지지되되 상기 레일로가 다단층으로 위치되어 지지되도록 하는 지지프레임부와; 상기 다단층으로 이루어지는 지지프레임부의 레일로 일측 단부에 선택적으로 위치되는 승하강작업대; 및상기 승하강작업대가 위치되는 레일로의 타측 단부측에 위치되며 다단층의 레일로 각각에 고정설치되는 고정작업대;를 포함하되,상기 레일로는 제1방향으로 이송하는 제1이송레일로와, 상기 제1이송레일로 일측에 평행하게 설치되며 제2방향으로 이송하는 제2이송레일로를 포함하고,상기 고정작업대는 다단층으로 이루어지는 레일로의 각 단부측에 위치되어 사육상자가 안착되며 상부측으로 복수개의 볼롤러가 돌출되어 설치되는 고정작업판과, 상기 고정작업판의 하부측에서 지지하는 고정작업대프레임과, 상기 고정작업대프레임을 외측에서 고정지지되도록 하는 고정작업대하우징을 포함하는 것을 특징으로 하는 동애등에 사육시설물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

866/1059 Row 866: application_number: 1020200009563, combined_string: invention_title: 꿀벌 생육환경 제공장치 abstract: 본 발명은 꿀벌의 생육환경을 제공하기 위한 장치에 관한 것이다.본 발명에 따른 꿀벌의 생육환경 제공장치는 벌통(BH)과, 벌통에 설치되고 꿀벌의 먹이를 제공하는 먹이 제공부(10)와, 벌통에 설치되고 꿀벌의 식수를 제공하는 식수 제공부(20)와, 벌통 내부의 온도를 조절하는 온도 조절부(30)와, 상기 먹이 공급부, 식수 제공부, 온도 조절부를 제어하는 컨트롤러(50)와, 상기 컨트롤러와 통신 연결되는 관리자 단말기(70)를 포함하고, 상기 먹이 제공부(10)는 먹이 보관부(12)와, 제1 밸브(14)가 구비되는 제1 배관(13)과, 먹이 노즐로 이루어지고, 상기 식수 제공부(20)는 식수 보관부(22)와, 제2 밸브(24)가 구비되는 제2 배관(23)과, 식수 노즐로 이루어지고, 상기 온도 조절부(30)는 발열체(HTR)와 쿨링팬(CFN)로 이루어지며, 상기 단말기(70)는 컨트롤러(50)을 통해 먹이 제공부, 식수 제공부, 및 온도 조절부를 제어하도록 구성된다.또한, 컨트롤러(50)는 먹이 제공모듈(51), 식수 제공모듈(52), 온도 조절모듈(53), 통신모듈(55)로 이루어지고, 상기 먹이 제공모듈(51) 및 식수 제공모듈(52)은 단말기로부터 전송되는 소정의 주기 시간을 입력받고 먹이 제공부의 제1 밸브와 식수 제공부의 제2 밸브를 개폐하고, 상기 온도 조절모듈(53)은 온도벌통 내부로부터 검출된 온도에 기초하여 발열체를 구동하되, 검출된 온도가 미리 설정된 제1 기준온도 보다 낮을 경우, 발열체로 구동신호를 출력한다. claims: 벌통(BH)과, 상기 벌통에 설치되고 꿀벌의 먹이를 제공하는 먹이 제공부(10)와, 상기 벌통에 설치되고 꿀벌의 식수를 제공하는 식수 제공부(20)와, 벌통 내부의 온도를 조절하는 온도 조절부(30)와, 상기 먹이 공급부, 식수 제공부, 온도 조절부를 제어하는 컨트롤러(50)와, 상기 컨트롤러와 통신 연결되는 관리자 단말기(70)를 포함하고,상기 벌통은 소정의 사각 공간부를 갖는 본체와, 상기 본체의 내부에 구비되는 한 쌍의 걸림부재와, 상기 걸림부재에 안착되는 하나 이상의 소초광과, 상기 걸림부재에 안착되고, 소초광과 동일한 형상을 갖는 환경 제공부와, 상기 본체의 상부에 결합되고 관통홀을 구비하는 커버를 포함하고, 상기 본체에는 벌통 내부의 공기를 배출시키거나 외부의 공기를 벌통 내부로 유입시키는 쿨링팬과, 식수배관, 먹이배관, 센서라인, 및 전원라인이 연결되는 접속패널이 설치되고, 상기 환경제공부는 사각 형상의 바디와, 바디의 상측 양단에 돌출되는 돌출부와, 상기 바디의 하부를 밀폐하는 막음판을 포함하고, 상기 돌출부는 본체 내부에 구비되는 걸림부재에 안착되고, 상기 바디는 일측 상부에 구비되는 식수홈과, 타측 상부에 구비되는 먹이홈과, 바디의 하부에 구비되고 발열체가 삽입되는 발열홈과, 식수배관, 먹이배관, 센서라인, 전원라인을 접속패널과 연결하는 연결패널을 포함하여 이루어지고, 상기 먹이홈에는 먹이를 토출하기 위한 노즐과 먹이의 수위를 검출하는 센서가 설치되며, 상기 식수홈에는 식수를 토출하기 위한 노즐과 식수의 수위를 검출하는 센서가 설치되고,상기 먹이 제공부(10)는 먹이 보관부(12)와, 제1 밸브(14)가 구비되는 제1 배관(13)과, 먹이 노즐로 이루어지고,상기 식수 제공부(20)는 식수 보관부(22)와, 제2 밸브(24)가 구비되는 제2 배관(23)과, 식수 노즐로 이루어지고,상기 온도 조절부(30)는 발열체(HTR)와 쿨링팬(CFN)로 이루어지며,상기 단말기(70)는 컨트롤러(50)을 통해 먹이 제공부, 식수 제공부, 및 온도 조절부를 제어하고,상기 컨트롤러(50)는 먹이 제공모듈(51), 식수 제공모듈(52), 온도 조절모듈(53), 통신모듈(55)로 이루어지고,상기 먹이 제공모듈(51) 및 식수 제공모듈(52)은 단말기로부터 전송되는 소정의 주기 시간을 입력받고 먹이 제공부의 제1 밸브와 식수 제공부의 제2 밸브를 개폐하고,상기 온도 조절모듈(53)은 온도벌통 내부로부터 검출된 온도에 기초하여 발열체를 구동하되, 검출된 온도가 미리 설정된 제1 기준온도 보다 낮을 경우, 발열체로 구동신호를 출력하는 것을 특징으로 하는 꿀벌 생육환경 제공장치.벌통(BH)과, 벌통에 설치되고 꿀벌의 먹이를 제공하는 먹이 제공부(100)와, 벌통 내부의 온도를 조절하는 온도 조절부(200)와, 벌통 내부의 습도를 조절하는 습도 조절부(400)와, 상기 먹이 공급부, 온도 조절부, 습도 조절부를 제어하는 컨트롤러(500)와, 상기 컨트롤러와 통신 연결되는 관리자 단말기(700)를 포함하고,상기 벌통은 소정의 사각 공간부를 갖는 본체와, 상기 본체의 내부에 구비되는 한 쌍의 걸림부재와, 상기 걸림부재에 안착되는 하나 이상의 소초광과, 상기 걸림부재에 안착되고, 소초광과 동일한 형상을 갖는 환경 제공부와, 상기 본체의 상부에 결합되고 관통홀을 구비하는 커버를 포함하고,상기 본체에는 벌통 내부의 공기를 배출시키거나 외부의 공기를 벌통 내부로 유입시키는 쿨링팬과, 식수배관, 먹이배관, 센서라인, 및 전원라인이 연결되는 접속패널이 설치되고,상기 환경제공부는 사각 형상의 바디와, 바디의 상측 양단에 돌출되는 돌출부와, 상기 바디의 하부를 밀폐하는 막음판을 포함하고, 상기 돌출부는 본체 내부에 구비되는 걸림부재에 안착되고, 상기 바디는 일측 상부에 구비되는 식수홈과, 타측 상부에 구비되는 먹이홈과, 바디의 하부에 구비되고 발열체가 삽입되는 발열홈과, 식수배관, 먹이배관, 센서라인, 전원라인을 접속패널과 연결하는 연결패널을 포함하여 이루어지고, 상기 먹이홈에는 먹이를 토출하기 위한 노즐과 먹이의 수위를 검출하는 센서가 설치되며, 상기 식수홈에는 식수를 토출하기 위한 노즐과 식수의 수위를 검출하는 센서가 설치되고,상기 먹이 제공부(100)는 먹이 보관부(120)와, 제1 밸브(140)가 구비되는 제1 배관(130)과, 먹이 노즐로 이루어지고,상기 온도 조절부(200)는 온도 센서(TSR)와, 발열체(HTR)와, 쿨링팬(CFN)으로 이루어지며,상기 습도 조절부(400)는 생수 보관부(420)와, 제4 밸브(440)가 구비되는 제4 배관(430)과, 스프레이로 이루어지고,상기 단말기(700)는 컨트롤러(500)을 통해 먹이 제공부, 온도 조절부, 및 습도 조절부를 제어하는 것을 특징으로 하는 꿀벌 생육환경 제공장치., Ltext: 농업, prediction: 임업
867/1059 Row 867: application_number: 1020200005572, combined_string: invention_title: 다단 유충사육용기 및 이를 포함하는 유충사육시스템 abstract: 본원 발명은 등애사육용기(300) 및 이를 포함하는 등애사육시스템에 관한 것으로서, 다량의 등애애벌레를 용이하게 사육하고 수확할 수 있도록 구성된 것이다. 특히, 사각형상의 바닥부, 상기 바닥부의 각 변에 연장되어 상방향으로 경사지게 구비되는 측변부로 이루어지는 등애사육단위용기(300)에 있어서, 상기 단위 사육용기(300)는 상기 인접한 측변부 사이에 연결기둥(320)을 구비하고, 상기 연결기둥(320)에 의해서 상하로 적층되는 인접한 단위 사육용기(300)와 결합되되, 상기 바닥부는 개폐수단(340)에 의해서 개폐동작이 이루어져 사육이 끝난 등애를 배출하는 것을 특징으로 하는 등애사육용기(300)이다. claims: 사각형상의 바닥부, 상기 바닥부의 각 변에 연장되어 상방향으로 경사지게 구비되는 측변부로 이루어지는 유충사육용기(300); 상기 유충사육용기(300)는 각 모서리에 연결기둥(320)을 구비하여, 상기 연결기둥(320)에 의해서 복수개의 유충사육용기(300)가 상하 인접하여 결합되고, 최하단에 설치되는 이송대차(200)의 각 모서리에 결합된 연결기둥(220) 하단부에는 바퀴(210)가 더 구비되며, 상기 바닥부는 개폐수단(340)에 의해서 개폐되는 복수개의 분할판(330)으로 이루어지되,상기 개폐수단(340)은,상기 분할판(330)의 중심부를 관통하도록 구비된 회전축(341);상단이 상기 회전축(341)에 일체로 결합되는 연결레버(342);상기 연결레버(342)의 하단에 연결되는 작동바(343);다단의 유충사육용기(300)에 각각 구비된 작동바(343)의 단부와 힌지결합되는 연결링크(346);를 구비하되, 적어도 하나의 상기 작동바(343)의 소정위치에 힌지결합되는 작동레버(344);와상기 작동레버(344)의 타단에 결합되어 작동레버(344)를 회전구동하는 구동모터(345);를 포함하는 것을 특징으로 하는 다단유충사육용기. 제3항의 다단유충사육용기; 및 상기 다단유충사육용기를 수용할 수 있는 사육챔버(100)를 포함하는 유충사육시스템에 있어서, 상기 사육챔버(100)의 내부에는 하부 중앙을 가로질러 설치되는 컨베이어;상기 컨베이어의 상부 양측으로 상기 이송대차(200)의 바퀴(210)가 이동될 수 있도록 길이방향을 따라서 구비된 이송레일(150);을 포함하되, 상기 챔버의 일단에는 송풍장치가 구비되고, 상측에는 배기장치가 구비되며 타측에는 상기 유충사육용기(300)에서 배출되어 컨베이어 상면에 떨어진 유충을 이동시켜 배출하는 배출구(160)를 더 구비하고, 상기 이송레일(150)은 상단면이 △산모양으로 돌출되되, 이에 안착되는 이송대차(200)의 바퀴(210)는 외주면이 상기 이송레일(150)의 상단면에 대응되는 형상을 가져서 상기 이송레일(150)로부터 이탈되는 것을 방지한 것을 특징으로 하는 유충사육시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

868/1059 Row 868: application_number: 1020200005036, combined_string: invention_title: 중력 작용으로 사료를 배출하는 동물 사육 로봇 abstract: 본 발명은 동물이 로봇에 가하는 물리적인 외력이나 중력의 작용에 의해서 먹이를 외부로 배출하는 동물 사육용 로봇에 관한 것이다. 모바일 디바이스나 컴퓨터에 설치된 로봇 제어용 컴퓨터 프로그램을 통하여 무선 인터넷으로 구동이 제어되는 동물용 로봇으로서, 특히 먹이 배출부가, 먹이 배출을 통제하는 전자적 또는 기계적 제어장치를 전혀 포함하지 아니하고, 오로지 동물이 가하는 물리적 힘이나 중력의 작용에 의한 먹이 배출만 허용하는 것임을 특징으로 함으로써, 전자적 기계적 통제 수단의 가동으로 인한 전원 소모 가능성을 원천적으로 제거하여, 사육자 부재기간 동안 원격 조종 도중에 전원이 소모되더라도, 동물이 로봇에 가하는 물리적 외력이나 중력의 작용에 먹이가 배출되도록 함으로써, 전원 소모 시에도 먹이주기가 중단되는 위험을 최소화할 수 있는, 동물 사육용 로봇에 대한 것이다. claims: 컴퓨터 또는 모바일 디바이스에 설치되는 로봇 원격 조종 프로그램으로 무선 인터넷을 통하여 조종되거나 또는 로봇에 내장된 제어부에 입력된 자율 작동 프로그램에 따라 작동하는 동물 사육 로봇으로서, 상기 조종 프로그램으로 부터의 제어 신호를 받아들이는 신호송수신부; 로봇 몸체의 양 측면에 돌출된 회전축에 장착된 바퀴; 상기 바퀴에 회전축을 회전력을 전달하는 모터; 상기 모터와 제어부와 신호수신부에 전력을 제공하는 전원과 전원 스위치; 상기 조종 프로그램으로 부터 무선 인터넷을 통해 받은 제어 신호에 따라 로봇의 전진, 후진, 회전의 방향과 속도를 제어하거나 또는 제어부에 입력된 자율 작동 모드 프로그램에 따라 감지 센서의 접촉 감지에 반응하여 몸체를 회전시켜는 제어부; 동물의 먹이를 보관하고 배출하는 먹이 배출부 그리고 상기 모터, 전원, 전원 스위치, 신호송수진부, 제어부, 회전축, 먹이 배출부를 둘러싸는 몸체 하우징, 몸체 하우징과 회전축 사이에 배치되는 베어링을 포함하면서, 먹이 배출만을 위한 별도의 전자적 또는 기계적 작동 장치가 없이 동물이 로봇에 가하는 외력이나 중력의 작용에 의하여 먹이를 외부로 배출하는, 동물 사육 로봇., Ltext: 농업, prediction: 임업
869/1059 Row 869: application_number: 1020200000517, combined_string: invention_title: 착탈식 왕롱을 갖춘 소초광 abstract: 본 발명은 여왕벌을 수용하는 왕롱을 갖춘 소초광에 있어서: 수평외틀(21)과 수직외틀(22)로 형성되는 영역에 소초(10)와 공간부를 구비하는 소광틀(20); 및 상기 소광틀(20)의 공간부에 착탈 가능한 구조로 형성되고, 지지틀(31)의 내측으로 다수의 환봉재(32)에 의한 수용공간을 구비하는 왕롱재(30);를 구비하는 것을 특징으로 한다.이에 따라, 벌통안의 벌들이 많아 증소 과정에서 사용되는 소초광에 있어서 여왕벌을 위한 충분한 공간을 확보하는 동시에 고정과 해체가 용이하여 생산성 향상과 경쟁력 제고를 도모하는 효과가 있다. claims: 여왕벌을 수용하는 왕롱을 갖춘 소초광에 있어서:수평외틀(21)과 수직외틀(22)로 형성되는 영역에 소초(10)와 공간부를 구비하는 소광틀(20); 및상기 소광틀(20)의 공간부에 착탈 가능한 구조로 형성되고, 지지틀(31)의 내측으로 다수의 환봉재(32)에 의한 수용공간을 구비하는 왕롱재(30);를 구비하는 것을 특징으로 하는 착탈식 왕롱을 갖춘 소초광., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

870/1059 Row 870: application_number: 1020190177352, combined_string: invention_title: 인공광을 이용한 아메리카동애등에 성충의 연중 실내 교미 산란방법 abstract: 아메리카동애등에의 가장 안정적인 산란 광 조건을 탐색하였으며 LED광워 조건하에서 빛 파장 범위가 640-680nm의 구간에서 Relative photosynthetic efficiency의 값이 높을 수록 아메리카동애등에의 산란된 난괴수 값이 높게 나타났다. claims: 실내조건에서 인공광으로 교미와 산란을 유발시키는 인공광 wavelength의 범위가 640~680nm에서 Relative photosynthetic efficiency의 값이 0.7-1을 갖는 led lamp로 사육하는 방법, Ltext: 농업, prediction: 임업
871/1059 Row 871: application_number: 1020190176615, combined_string: invention_title: 도봉방지장치 abstract: 본 발명은 토종벌통에 구비된 토종꿀벌의 출입구에 설치되는 도봉방지장치에 있어서, 직육면체 형상을 가지며, 제1측면이 개방 형성되고, 제2측면이 출입구에 밀착 설치되되 출입구에 밀착되는 영역이 관통 형성된 케이스 및 제1측면의 개방된 영역에 망 형상으로 개폐 가능하게 설치되어, 토종꿀벌 중 외역벌 및 내역벌의 출입이 가능하고, 토종꿀벌 중 여왕벌과 수벌, 그리고 서양벌의 출입을 차단하는 차단망을 포함하는 것을 특징으로 한다. claims: 토종벌통에 구비된 토종꿀벌의 출입구에 설치되는 도봉방지장치에 있어서,직육면체 형상을 가지며, 제1측면이 개방 형성되고, 제2측면이 상기 출입구에 밀착 설치되되 상기 출입구에 밀착되는 영역이 관통 형성된 케이스; 상기 제1측면의 개방된 영역에 망 형상으로 개폐 가능하게 설치되어, 상기 토종꿀벌 중 외역벌의 출입이 가능하고, 상기 토종꿀벌 중 여왕벌과 수벌, 그리고 서양벌의 출입을 차단하는 차단망;을 포함하는 것을 특징으로 하는 도봉방지장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

872/1059 Row 872: application_number: 1020190171947, combined_string: invention_title: 여왕벌의 발현음을 이용한 여왕벌 탐지 방법 및 시스템 abstract: 여왕벌의 발현음을 이용한 여왕벌 탐지 방법 및 시스템이 개시된다. 일 실시예에 따른 여왕벌 탐지 방법은, 양봉통에 설치된 복수의 마이크들로부터 수집된 복수의 소리들을 수신하는 단계와, 상기 복수의 소리들에 기초하여 임계치를 초과하는 신호의 여부에 따라 상기 양봉통에 여왕벌이 존재하는지 여부를 판단하는 단계와, 상기 판단 결과에 따라 탐지 데이터를 생성하는 단계를 포함한다. claims: 양봉통에 설치된 복수의 마이크들로부터 수집된 복수의 소리들을 수신하는 단계;상기 복수의 소리들에 기초하여 임계치를 초과하는 신호의 여부에 따라 상기 양봉통에 여왕벌이 존재하는지 여부를 판단하는 단계; 및상기 판단 결과에 따라 탐지 데이터를 생성하는 단계를 포함하는 여왕벌 탐지 방법.여왕벌 탐지를 위한 인스트럭션들을 저장하는 메모리; 및상기 인스트럭션들을 실행하기 위한 프로세서를 포함하고,상기 인스트럭션들이 상기 프로세서에 의해 실행될 때, 상기 프로세서는,양봉통에 설치된 복수의 마이크들로부터 수집된 복수의 소리들을 수신하고,상기 복수의 소리들에 기초하여 임계치를 초과하는 신호의 여부에 따라 상기 양봉통에 여왕벌이 존재하는지 여부를 판단하고,상기 판단 결과에 따라 탐지 데이터를 생성하는여왕벌 탐지 장치., Ltext: 농업, prediction: 임업
873/1059 Row 873: application_number: 1020190170638, combined_string: invention_title: 컨테이너를 이용한 식용곤충 양식 시설물 abstract: 본 발명은 식용곤충 양식을 위한 시설물에 관한 것으로, 좀 더 상세하게는 컨테이너에 유충과 성충 등을 분류해 담는 사육함을 적층해서 공간 활용율을 높이고 사육 인력과 활동범위를 최소화해서 양식 효율성을 높이는 컨테이너를 이용한 식용곤충 양식 시설물에 관한 것으로, 실내외 출입용 도어가 구성된 사육함 보관 기능의 컨테이너; 상기 컨테이너의 실내 공기 상태를 센싱해서 감지신호를 발신하는 실내환경 감지센서; 상기 컨테이너의 실내 공기를 조화하는 공조기; 상기 컨테이너 내에 급배수를 처리하며 급배수량을 체크하는 급배수기; 상기 감지신호에 따른 공기정보를 생성해서 공조기를 동작시키고, 상기 급배수량에 따른 급배수정보를 생성하며, 상기 공기정보와 급배수정보를 관리서버에 전송해서 온라인으로 공유시키는 터미널 서버;를 포함하는 것이다. claims: 실내외 출입용 도어가 구성된 사육함 보관 기능의 컨테이너;상기 컨테이너의 실내 공기 상태를 센싱해서 감지신호를 발신하는 실내환경 감지센서;상기 컨테이너의 실내 공기를 조화하는 공조기;상기 컨테이너 내에 급배수를 처리하며 급배수량을 체크하는 급배수기; 및상기 감지신호에 따른 공기정보를 생성해서 공조기를 동작시키고, 상기 급배수량에 따른 급배수정보를 생성하며, 상기 공기정보와 급배수정보를 관리서버에 전송해서 온라인으로 공유시키는 터미널 서버;를 포함하는 것을 특징으로 하는 컨테이너를 이용한 식용곤충 양식 시설물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

874/1059 Row 874: application_number: 1020190169425, combined_string: invention_title: 사마귀 사육장치 abstract: 본 발명은 사마귀과 곤충의 사육장치에 관한 것으로, 더욱 상세하게는 갈색거저리유충(밀웜) 및 초파리의 특성을 활용한 먹이곤충을 별도로 사육하지 않으면서 사마귀과 곤충의 유충단계부터 성충단계까지 자동으로 먹이급여가 되는 사육장치에 관한 것이다. claims: 사마귀과 곤충을 사육할 수 있는 사육상자(10);사육상자(10) 안 하단부에 위치하는 갈색거저리유충(밀웜)의 급수층(20) 및 먹이층(30);사육상자(10) 안 급수층(20) 위에 위치하는 인큐베이터(40); 를 포함함을 특징으로 하는 사마귀과 곤충의 사육장치(100)본 발명에 따른 사마귀과 곤충의 사육장치(100)를 활용하여, 갈색거저리유충(밀웜) 및 초파리의 특성을 이용한 먹이곤충을 별도로 사육하지 않으면서 사마귀과 곤충의 유충단계부터 성충단계까지 물 분무방식으로 자동으로 먹이급여가 되는 사마귀과 곤충의 사육방법, Ltext: 농업, prediction: 임업
875/1059 Row 875: application_number: 1020190167287, combined_string: invention_title: IoT기반 곤충사육 시스템 abstract: 본 발명은 IoT기반 곤충사육 시스템에 관한 것이다. 본 발명의 하나의 실시예에 따라, 이동설치가 가능하되, 유충사육실과 산란작업실을 구비한 컨테이너유닛; 컨테이너유닛의 중앙통로에 구비된 가이드유닛; 유충사육실과 산란작업실의 사이드 측에 설치된 적층 프레임유닛; 적층 프레임유닛에 다층으로 적층되되 유충 및 성충 각각의 사육공간이 되는 다수의 사육박스유닛; 가이드유닛을 따라 이동하며 사육박스유닛을 이송하는 대차유닛; 컨테이너 내부의 온도 및 습도를 감지하는 센서유닛; 및 센서유닛으로부터 획득된 데이터를 수신하고 유충 및 성충의 사육상태를 관리하는 관리시스템유닛을 포함하고, 대차유닛은 상하로 리프팅되며 적재된 사육박스유닛의 높이를 승강시키고, 적층 프레임유닛은 사육박스유닛을 지지하며 사육박스유닛의 적층 프레임유닛으로의 적층 및 적층 프레임유닛으로부터의 탈거가 가능하도록 슬라이딩하는 다수의 슬라이더를 포함하는 것을 특징으로 하는 IoT기반 곤충사육 시스템이 제안된다. claims: 이동설치가 가능하되, 유충사육실과 산란작업실을 구비한 컨테이너유닛;상기 컨테이너유닛의 중앙통로에 구비된 가이드유닛;상기 유충사육실과 산란작업실의 사이드 측에 설치된 적층 프레임유닛;상기 적층 프레임유닛에 다층으로 적층되되 유충 및 성충 각각의 사육공간이 되는 다수의 사육박스유닛;상기 가이드유닛을 따라 이동하며 상기 사육박스유닛을 이송하는 대차유닛;상기 컨테이너 내부의 온도 및 습도를 감지하는 센서유닛; 및상기 센서유닛으로부터 획득된 데이터를 수신하고 상기 유충 및 성충의 사육상태를 관리하는 관리시스템유닛을 포함하고,상기 대차유닛은 상하로 리프팅되며 적재된 상기 사육박스유닛의 높이를 승강시키고,상기 적층 프레임유닛은 상기 사육박스유닛을 지지하며 상기 사육박스유닛의 상기 적층 프레임유닛으로의 적층 및 상기 적층 프레임유닛으로부터의 탈거가 가능하도록 슬라이딩하는 다수의 슬라이더를 포함하는 것을 특징으로 하는 IoT기반 곤충사육 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

876/1059 Row 876: application_number: 1020190165620, combined_string: invention_title: 센서감지를 통해 작동하는 공기청정기 및 집진기가 구비된 반려동물용 배변케이지 abstract: 개시된 내용은, 내부에 모래가 수납되는 수납공간이 형성되는 하부하우징과 일측에는 반려동물이 출입하는 출입구를 포함하며 상기 하부하우징의 상부에 탈착 가능하게 결합 되고, 상부면에는 개구되어 형성되는 본체결합부가 형성되는 상부하우징과 상기 하부하우징 또는 상기 상부하우징의 일측에 형성되는 센서부와 상기 하부하우징 또는 상기 상부하우징의 일측에 형성되고, 상기 센서부와 전기적으로 결합 되는 전원부와 상기 본체결합부에 탈착 가능하게 결합 되며 내부에 필터부재가 구비되는 공기청정기와 상기 전원부와 전기적으로 연결되는 모터부와 상기 모터부의 회전축에 결합되어 회전하는 팬부로 구성되어, 상기 공기청정기의 상부에 탈착 가능하게 결합되는 구동부와 상기 센서부, 상기 전원부 및 상기 구동부와 전기적으로 연결되고, 상기 공기청정기의 일측에 형성되고, 상기 센서부를 통해 센싱된 신호를 기초로 상기 구동부의 구동을 제어하는 제어부를 포함하는 것을 특징으로 하는 센서감지를 통해 작동하는 공기청정기 및 집진기가 구비된 반려동물용 배변케이지에 관한 것이다. claims: 내부에 모래가 수납되는 수납공간이 형성되는 하부하우징;일측에는 반려동물이 출입하는 출입구를 포함하며 상기 하부하우징의 상부에 탈착 가능하게 결합 되고, 상부면에는 개구되어 형성되는 본체결합부가 형성되는 상부하우징;상기 하부하우징 또는 상기 상부하우징의 일측에 형성되는 센서부; 상기 하부하우징 또는 상기 상부하우징의 일측에 형성되고, 상기 센서부와 전기적으로 결합 되는 전원부; 상기 본체결합부에 탈착 가능하게 결합 되며 내부에 필터부재가 구비되는 하우징조립체;상기 전원부와 전기적으로 연결되는 모터부와 상기 모터부의 회전축에 결합되어 회전하는 팬부로 구성되어, 상기 하우징조립체의 상부에 탈착 가능하게 결합되는 구동부; 및 상기 센서부, 상기 전원부 및 상기 구동부와 전기적으로 연결되고, 상기 하우징조립체의 일측에 형성되고, 상기 센서부를 통해 센싱된 신호를 기초로 상기 구동부의 구동을 제어하는 제어부를 포함하는 것을 특징으로 하는 센서감지를 통해 작동하는 공기청정기 및 집진기가 구비된 반려동물용 배변케이지., Ltext: 농업, prediction: 임업
877/1059 Row 877: application_number: 2020190005021, combined_string: invention_title: 곤충 사육 장치 abstract: 본 고안은 도미노 게임 완구에 관한 것으로, 보다 상세하게는 별도의 선반 등의 구조물 없이 2단 이상으로 안정적인 적층이 가능하여 소정의 면적 내에서 곤충 사육 공간의 용적률을 높여 곤충의 대량 사육 시 효율성을 높일 수 있으며, 내부 바닥면이 중앙부분을 향해 경사지게 형성됨으로써 적층한 상태에서도 세척이 가능한 것을 특징으로 하는 곤충 사육 장치에 관한 것이다. claims: 내부에 유충의 사육 가능한 사육 공간이 마련되며 상부가 개방되는 사각 함체 형상의 곤충 사육 박스;를 포함하며,상기 곤충 사육 박스는내부 바닥면은 중앙을 향해 하향 경사지게 이루어지고, 가로측벽과 세로측벽의 외측면과 내측면이 전체적으로 하부의 너비가 상부의 너비보다 크도록 상협하광의 형태로 이루어지되,상기 가로측벽에는 상단에서 하부로 일정간격 이격된 지점까지 개방되도록 형성되는 공기순환부;상기 곤충 사육 박스의 가로측벽과 세로측벽이 인접한 상단 모서리 부분에 상측방향으로 연장 형성된 적층돌출부; 및 상기 곤충 사육 박스의 외부 바닥면에는 상기 적층돌출부와 대응되는 형상의 적층홈;을 포함하며,상기 적층돌출부를 상기 적층홈에 끼워 다단으로 적층되어 별도의 선반구조물 없이 보관되고,상기 적층된 다수의 곤충 사육 박스를 결합할 수 있는 결합수단이 마련되되,상기 결합수단은상기 적층돌출부에는 수직방향으로 관통 형성되는 제1끼움홈;상기 적층홈에서 상기 측벽의 외측면까지 상기 제1끼움홈에 대응되는 위치에 형성되는 제2끼움홈; 및 상기 제1끼움홈 및 제2끼움홈을 관통하여 끼워지는 끼움봉;이 형성되어,적층된 상기 곤충 사육 박스의 분리 및 쓰러짐을 방지하는 것을 특징으로 하는 곤충 사육 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

878/1059 Row 878: application_number: 1020190160841, combined_string: invention_title: 월동용 말벌 케이지 abstract: 본 발명은 월동용 말벌 케이지로서, 상기 케이지의 길이 방향을 따라 길게 형성되고, 말벌 교미 여왕벌이 개별로 투입되는 수용홀; 및 상기 수용홀의 개방된 양단에 구비되어 상기 수용홀에 투입된 말벌 교미 여왕벌의 출입을 차단하는 차단부를 포함하는 것을 특징으로 한다.이러한 월동용 말벌 케이지는 말벌 교미 여왕벌이 수용홀의 내부에 개별로 투입된 후, 차단부에 의해 수용홀의 개방된 양단이 폐쇄될 수 있으므로, 외부의 빛이 수용홀의 내부 공간에 들어오는 것을 차단하여 여왕벌이 월동에 들어가기가 용이하며, 외부의 자연환경 변화에 따른 영향을 최소화할 수 있기 때문에 여왕벌의 생존율을 높일 수 있다. claims: 월동용 말벌 케이지로서,상기 케이지의 길이 방향을 따라 길게 형성되고, 말벌 교미 여왕벌이 개별로 투입되는 수용홀; 및상기 수용홀의 개방된 양단에 구비되어 상기 수용홀에 투입된 말벌 교미 여왕벌의 출입을 차단하는 차단부를 포함하는 것을 특징으로 하는 월동용 말벌 케이지., Ltext: 농업, prediction: 임업
879/1059 Row 879: application_number: 1020190159735, combined_string: invention_title: 반려동물용 곤충 배출 장치 abstract: 곤충 배출 장치가 개시된다. 본 발명의 일 측면에 따르면, 곤충을 수용 가능한 내부 공간이 형성되며, 내부 공간에 수용된 곤충을 외부로 배출 가능한 개구부가 마련되는 케이스, 내부 공간에 수용된 곤충의 이탈을 방지하도록 개구부를 커버하며, 내측면이 외부를 향하도록 개구부에 회전 가능하게 설치되어, 내측면에 붙어 있는 곤충을 외부로 노출시키는 회전 부재, 케이스에 회전 부재 측으로 이동 가능하게 설치되어, 회전 부재의 회전에 따라 외부로 노출된 곤충이 회전 부재로부터 이탈되도록 유도하는 이탈 유도 부재, 및 회전 부재의 회전 및 이탈 유도 부재의 이동을 위한 구동력을 제공하는 구동 유닛을 포함하는 곤충 배출 장치가 제공된다. claims: 곤충을 수용 가능한 내부 공간이 형성되며, 상기 내부 공간에 수용된 곤충을 외부로 배출 가능한 개구부가 마련되는 케이스;상기 내부 공간에 수용된 곤충의 이탈을 방지하도록 상기 개구부를 커버하며, 내측면이 외부를 향하도록 상기 개구부에 회전 가능하게 설치되어, 내측면에 붙어 있는 곤충을 외부로 노출시키는 회전 부재;상기 케이스에 상기 회전 부재 측으로 이동 가능하게 설치되어, 상기 회전 부재의 회전에 따라 외부로 노출된 곤충이 상기 회전 부재로부터 이탈되도록 유도하는 이탈 유도 부재; 및상기 회전 부재의 회전 및 상기 이탈 유도 부재의 이동을 위한 구동력을 제공하는 구동 유닛을 포함하는 곤충 배출 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

880/1059 Row 880: application_number: 1020190159814, combined_string: invention_title: 생태순환적인 왕지네의 사육시스템 및 그러한 사육시스템의 구축방법 abstract: 본 발명은 내부로 바람이 통하고 비를 맞을 수 있도록 형성된 상부를 가지며, 바닥면의 일부 또는 전부는 토지로 이루어지고, 상기 내부로 햇볕을 받을 수 있는 하우스(H)와; 상기 하우스의 내부에 풀어지는 복수개의 왕지네(100)들과; 상기 하우스의 내부에 풀어지는 상기 왕지네의 먹이가 되는 먹이곤충(200)들과; 상기 하우스의 내부의 바닥면의 토지에서 자라는 것으로서, 상기 먹이곤충들이 먹이가 되는 식물(300)들과; 상기 하우스의 내부에 풀어지는 상기 먹이곤충의 사체를 분해하는 분해곤충(400)들과; 상기 하우스의 내부에 배치되는 상기 왕지네들이 기거하는 왕지네기거수단(110)(120)을 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템(1000)을 제공한다. claims: (a) 내부로 바람이 통하고 비를 맞을 수 있으며, 바닥면의 일부 또는 전부는 토지로 이루어지고, 상기 내부로 햇볕을 받을 수 있는 하우스와;(b) 상기 하우스의 내부에 풀어지는 복수개의 왕지네들과;(c) 상기 하우스의 내부에 풀어지는 상기 왕지네의 먹이가 되는 먹이곤충들과;(d) 상기 하우스의 내부의 바닥면의 토지에서 자라는 것으로서, 상기 먹이곤충들이 먹이가 되는 식물들과;(e) 상기 하우스의 내부에 풀어지는 상기 먹이곤충의 사체를 분해하는 분해곤충들과;(f) 상기 하우스의 내부에 배치되는 상기 왕지네들이 기거하는 왕지네기거수단을 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템.(a) 내부로 바람이 통하고 비를 맞을 수 있으며, 바닥면의 일부 또는 전부는 토지로 이루어지고, 상기 내부로 햇볕을 받을 수 있는 하우스를 제공하는 하우스 제공단계와;(b) 상기 하우스의 토지에 식물들이 살아나가도록 하는 식물생육단계와;(c) 상기 하우스의 내부에 왕지네들이 기거하는 왕지네 기거수단을 배치하는 왕지네기거수단배치단계와; (d) 상기 하우스의 내부에 복수개의 왕지네들과, 상기 왕지네의 먹이가 되는 것으로서 상기 식물들을 먹고사는 복수개의 먹이곤충들과, 상기 먹이곤충의 사체를 분해하는 복수개의 분해곤충들을 풀어 놓는 왕지네와 먹이곤충및 분해곤충의 풀어줌 단계를 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템의 구축방법., Ltext: 농업, prediction: 임업
881/1059 Row 881: application_number: 1020190159817, combined_string: invention_title: 생태순환적인 왕지네의 사육시스템 abstract: 본 발명은 내부로 바람이 통하고 비를 맞을 수 있도록 형성된 상부를 가지며, 바닥면의 일부 또는 전부는 토지로 이루어지고, 상기 내부로 햇볕을 받을 수 있는 하우스(H)와; 상기 하우스의 내부에 풀어지는 복수개의 왕지네(100)들과; 상기 하우스의 내부에 풀어지는 상기 왕지네의 먹이가 되는 먹이곤충(200)들과; 상기 하우스의 내부의 바닥면의 토지에서 자라는 것으로서, 상기 먹이곤충들이 먹이가 되는 식물(300)들과; 상기 하우스의 내부에 풀어지는 상기 먹이곤충의 사체를 분해하는 분해곤충(400)들과; 상기 하우스의 내부에 배치되는 상기 왕지네들이 기거하는 왕지네기거수단(110)(120)을 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템(1000)을 제공한다. claims: (a) 내부에서 왕지네가 사육되는 것으로서 바닥면의 전부 또는 일부가 토지로 이루어진 하우스와;(b) 상기 하우스의 내부에 풀어지는 복수개의 왕지네들과;(c) 상기 하우스의 내부에 풀어지는 상기 왕지네의 먹이가 되는 먹이곤충들과;(d) 상기 하우스의 내부의 바닥면의 토지에서 자라는 것으로서, 상기 먹이곤충들이 먹이가 되는 식물들과;(e) 상기 하우스의 내부에 풀어지는 상기 먹이곤충의 사체를 분해하는 분해곤충들과;(f) 상기 하우스의 내부에 배치되는 상기 왕지네들이 기거하는 왕지네기거수단을 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

882/1059 Row 882: application_number: 1020190158706, combined_string: invention_title: 폐버섯배지를 이용한 자연방사형 곤충사육방법 abstract: 폐버섯배지를 이용한 곤충 사육방법을 개시한다. 본 발명의 곤충 사육방법은 원통형이나 사각기둥형의 폐버섯배지를 수거하여 겉비닐을 제거한 폐버섯배지를 적재한 다음, 6월~9월 첫재 주까지만 운용하는 운용하는 차광시설을 배치하고, 5월~8월 31까지 관수하고, 6~8월에는 폐과일을 공급하여 서리가 내리기 전이나 3~4월에 수확한다. claims: 원통형이나 사각기둥형의 폐버섯배지를 수거하여 겉비닐을 제거한 폐버섯배지를 적재한 다음, 6월~9월 초까지만 운용하는 운용하는 차광시설을 배치하고, 5월~8월 말까지 관수하고, 6~8월에는 폐과일을 공급하여 서리가 내리기 전이나 3~4월에 수확함을 특징으로 하는, 폐버섯배지를 이용한 자연방사형 곤충 사육방법., Ltext: 농업, prediction: 임업
883/1059 Row 883: application_number: 1020190158927, combined_string: invention_title: 먹이보상이 가능한 반려동물용 운동장치 abstract: 내측에 반려동물이 운동할 수 있는 공간인 운동공간부가 형성되고, 내주면에 구비되며 반려동물이 운동공간부 내에서 지속적으로 움직이며 운동할 수 있는 회전모듈; 상기 회전모듈에 반려동물이 움직임에 따라 회전모듈이 회전 가능하도록 지지하는 지지모듈; 상기 회전모듈 내측면에는 회전모듈의 회전수에 따라 간식이 공급되는 먹이공급부가 형성되며; 상기 먹이공급부의 작동 제어 및 회전모듈의 회전수에 따른 간식량을 설정하는 제어모듈; 및 제어모듈로 전송되는 먹이공급부의 동작제어신호를 송신하는 통신부를 포함하는 단말기로 이루어진 먹이보상이 가능한 반려동물용 운동장치를 제공함으로써, 반려동물이 목표와 동기를 가지고 운동을 보다 능동적으로 실시할 수 있도록 함과 더불어 장기적인 운동이 가능하여 실내에서만 활동하는 반려동물의 건강을 증진시킬 수 있는 효과가 있다. claims: 내측에 반려동물이 운동할 수 있는 공간인 운동공간부가 형성되고, 내주면에 구비되며 반려동물이 운동공간부 내에서 지속적으로 움직이며 운동할 수 있는 회전모듈; 상기 회전모듈에 반려동물이 움직임에 따라 회전모듈이 회전 가능하도록 지지하는 지지모듈; 상기 회전모듈 내측면에는 회전모듈의 회전수에 따라 간식이 공급되는 먹이공급부가 형성되며; 상기 먹이공급부의 작동 제어 및 회전모듈의 회전수에 따른 간식량을 설정하는 제어모듈; 및 제어모듈로 전송되는 먹이공급부의 동작제어신호를 송신하는 통신부를 포함하는 단말기로 이루어진 것인 먹이보상이 가능한 반려동물용 운동장치, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

884/1059 Row 884: application_number: 1020200124764, combined_string: invention_title: 열화상 카메라를 이용한 젖소 질병관리 시스템 abstract: 본 발명의 일 실시예에 따른 젖소의 질병관리 시스템은 젖소의 이동통로에 위치하여 젖소에 장착된 생체측정장치로부터 생체정보를 수신하는 젖소 식별장치, 상기 이동통로에 위치하는 복수의 열화상 카메라, 젖소의 질병 및 건강 상태에 따라 젖소를 착유소 또는 질병치료소 중 하나로 가이드하는 게이트를 개폐하는 가이드 장치, 및 상기 젖소 식별장치로부터 젖소의 생체정보 및 상기 복수의 열화상 카메라로부터 촬영된 열화상을 수신하여, 해당 젖소의 유방염 및 발목병 발생여부를 판단하고, 유방염 및 발목병 발생여부에 따라 상기 가이드 장치를 제어하는 제어신호를 송신하는 제어부를 포함한다. claims: 젖소의 귀에 장착되어 체온을 포함하는 생체정보 및 움직임정보를 측정하는 생체측정장치;젖소의 이동통로에 위치하여 상기 생체측정장치로부터 생체정보를 수신하는 젖소 식별장치;상기 이동통로에 위치하는 복수의 열화상 카메라;젖소의 질병 및 건강 상태에 따라 젖소를 착유소 또는 질병치료소 중 하나로 가이드하는 게이트를 개폐하는 가이드 장치; 및상기 젖소 식별장치로부터 생체정보 및 상기 복수의 열화상 카메라로부터 촬영된 열화상을 수신하고, 상기 생체정보에 포함된 제1 체온 및 상기 열화상으로부터 도출되는 제2 체온을 이용하여 해당 젖소의 유방염 및 발목병 발생여부를 판단하고, 유방염 및 발목병 발생여부에 따라 상기 가이드 장치를 제어하는 제어신호를 송신하는 제어부를 포함하고,상기 복수의 열화상 카메라는,상기 이동통로 양측면에 위치하여 유방 및 발목을 촬영하는 제1 및 제2 열화상 카메라; 및상기 이동통로의 바닥면에 위치하여 유선 및 유두를 촬영하는 제3 열화상 카메라를 포함하는 젖소의 질병관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

885/1059 Row 885: application_number: 1020200081093, combined_string: invention_title: 축사 습도 연동형 기능성 냉풍기 abstract: 본 발명은 축사 습도 연동형 기능성 냉풍기에 관한 것으로서, 육면체 박스 형태를 가지는 것으로 개구된 4 개의 제1,2,3,4측면개구부(11)(12)(13)(14), 상기 제1,2,3,4측면개구부(11)(12)(13)(14)의 하부측에 형성된 저수조(15) 및 저수조(15)의 상부측으로 돌출된 테이블(16)을 가지는 냉풍기몸체(10)와; 냉풍기몸체(10)의 상부측에 설치되어 축사(C)와 연결되는 배기덕트(20)와; 냉풍기몸체(10)에 내부에서 제1,2,3,4측면개구부(11)(12)(13)(14)를 막도록 설치되는 것으로서, 종이 재질로 되고 다수의 통풍구멍이 형성된 제1,2,3,4쿨링패드(31)(32)(33)(34)와; 저수조(15)로 물을 공급하는 물공급부(50)와; 저수조(15)에 수용된 물을 제1,2,3,4쿨링패드(31)(32)(33)(34)의 상부측으로 공급하는 순환공급부(60)와; 배기덕트(20) 하부측에 설치된 것으로서, 제1,2,3,4에어필터부(41)(42)(43)(44) 및 제1,2,3,4쿨링패드(31)(32)(33)(34)를 통하여 유입된 공기를 상기 배기덕트(20)로 송풍시키는 송풍팬(70)과; 축사(C) 내부의 습도를 측정하여 대응되는 습도신호(H)를 발생하는 습도측정부(80)와; 테이블(16)에 설치되어 상기 습도신호(H)에 연동되어 상기 순환공급부(60) 및 송풍팬(70)의 동작을 제어하는 제어부(100);를 포함하는 것을 특징으로 한다. claims: 육면체 박스 형태를 가지는 것으로 개구된 4 개의 제1,2,3,4측면개구부(11)(12)(13)(14), 상기 제1,2,3,4측면개구부(11)(12)(13)(14)의 하부측에 형성된 저수조(15) 및 저수조(15)의 상부측으로 돌출된 테이블(16)을 가지는 냉풍기몸체(10);상기 냉풍기몸체(10)의 상부측에 설치되어 축사(C)와 연결되는 배기덕트(20);상기 냉풍기몸체(10)에 내부에서 상기 제1,2,3,4측면개구부(11)(12)(13)(14)를 막도록 설치되는 것으로서, 종이 재질로 되고 다수의 통풍구멍이 형성된 제1,2,3,4쿨링패드(31)(32)(33)(34);상기 저수조(15)로 물을 공급하는 물공급부(50);상기 저수조(15)에 수용된 물을 상기 제1,2,3,4쿨링패드(31)(32)(33)(34)의 상부측으로 공급하는 순환공급부(60);상기 배기덕트(20) 하부측에 설치된 것으로서, 상기 제1,2,3,4쿨링패드(31)(32)(33)(34)를 통하여 유입된 공기를 상기 배기덕트(20)로 송풍시키는 송풍팬(70); 축사(C) 내부의 습도를 측정하여 대응되는 습도신호(H)를 발생하는 습도측정부(80); 상기 테이블(16)에 설치되어 상기 습도신호(H)에 연동되어 상기 순환공급부(60) 및 송풍팬(70)의 동작을 제어하는 제어부(100);상기 저수조(15)의 물에 포함된 이물질 입자에 의한 탁도가 설정탁도(D) 이상이 될 때 세척경고신호(S)를 발생하는 탁도감지부(110); 상기 물공급부(50)와 독립된 구성으로서 상기 세척경고신호(S)에 연동되어 상기 저수조(15) 바닥으로 세척수를 분사하는 세척수노즐(120); 및상기 저수조(15) 바닥과 연결되는 것으로서 상기 저수조(15) 바닥을 세척한 세척수를 드레인하기 위한 드레인관(131)을 선택적으로 개폐하는 드레인밸브(130)를 포함하고;상기 저수조(15)는, 전체적으로 도넛 형태를 이루고, 일측이 높은 상부단(15a)과 타측이 낮은 하부단(15b)으로 구성되고, 상부단(15a)과 하부단(15b) 사이는 비스듬한 경사면(15c)이 형성된 구조를 가지고;상기 세척수노즐(120)은, 상기 저수조(15) 내측의 상부단(15a)에 설치되고;상기 드레인밸브(130)의 드레인관(131)은 상기 저수조(15) 내측의 하부단(15b)에 연결된 것;을 특징으로 하는 축사 습도 연동형 기능성 냉풍기., Ltext: 농업, prediction: 임업
886/1059 Row 886: application_number: 1020200076368, combined_string: invention_title: 자연 환기형 축사 abstract: 본 발명은 자연 환기형 축사에 관한 것으로, 자연 공기 순환방식으로 환기가 이루어져 종래 환풍팬을 구비하는 축사에 비해 관리비용을 절감할 수 있으며, 가축들에게 쾌적한 환경을 제공 함을 목적으로 한다.본 발명에 따른 자연 환기형 축사는, 축사본체, 상기 축사본체의 상부에 배치되는 상부 지붕, 상기 상부 지붕의 일측과 타측 하부에 각각 소정간격 이격되도록 배치되어 공기통로를 형성하는 하부 지붕을 포함한다. claims: 축사본체,상기 축사본체의 상부에 배치되는 상부 지붕,상기 상부 지붕의 일측과 타측 하부에 각각 소정간격 이격되도록 배치되어 공기통로를 형성하는 하부 지붕을 포함하고,상기 축사본체는,상기 하부 지붕의 가장자리를 일정 간격으로 지지하며, 그 내측에 축사공간을 형성시키는 제1 서포트,상기 제1 서포트의 사이 공간을 폐쇄하는 벽체부,상기 축사공간에서 상기 상부 지붕을 일정간격으로 지지하는 제2 서포트를 포함하며,상기 제1 서포트와 하부 지붕을 결합시키는 결합부를 포함하고,상기 결합부는 상기 제1 서포트의 상측에 형성되고 상기 하부 지붕의 저면에 접촉되는 플랜지, 상기 플랜지의 체결홀과 상기 하부 지붕의 체결홀에 공동으로 체결되는 탄성후크유닛을 포함하고,상기 탄성후크유닛은 탄성안내바, 상기 탄성안내바의 끝단 외측으로 돌출되게 형성되어 상기 하부지붕에 걸리는 걸림돌부를 포함하며,상기 탄성안내바에는 서로 일정간격 이격되는 완충슬릿홀이 형성되고,상기 탄성안내바의 전면부에는 플랜지의 체결홀과 하부 지붕의 체결홀의 내측면을 가압하는 탄성지지바가 더 부착되며,상기 탄성안내바의 전면에는 플랜지의 체결홀과 하부 지붕의 체결홀의 내측면과 마찰됨과 아울러 걸림되도록 요철돌부들이 더 형성되고,상기 탄성안내바의 배면부에는 길이방향을 따라 지지림부들이 더 형성되는 자연 환기형 축사., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

887/1059 Row 887: application_number: 1020200064329, combined_string: invention_title: 우사용 위생 급수조 abstract: 본 발명은 우사에서 사용되는 급수조에 관한 것으로서, 보다 상세하게 설명하면, 축사에 사용되는 종래의 급수장치 중 우사에서 사용되는 급수조에 소가 혀를 이용하여 물을 튀기는 장난을 하거나 물을 걷어내는 음용습관에 의해 급수조의 외측으로 물이 비산되는 것을 차단부를 설치하여 방지함으로써, 음용수의 소실, 우사의 바닥오염을 최소화할 수 있고, 이에 따라 급수조의 위생 및 관리의 용이성을 향상시킬 수 있는 우사용 위생 급수조에 관한 기술분야가 개시된다. claims: 상부면에 물이 담기는 적어도 하나의 음용홈(110)이 형성된 베이스몸체(100);와음용방향을 제외한 상기 베이스몸체(100)의 상부면에 하부가 결합되되, 상기 음용홈(110)의 둘레에 위치되도록 결합되는 차단부(200);를 포함하여 구성되고,상기 차단부(200)는상부로 갈수록 상기 베이스몸체(100)의 외측방향으로 기울어져 형성되며,상기 차단부(200)는상기 베이스몸체(100)의 상부면 전방에 하부가 힌지 결합되어 상기 베이스몸체(100)의 외측방향으로 접철되는 전방차단프레임(210);과상기 베이스몸체(100)의 상부면 양측에 각각 하부가 힌지 결합되어 상기 베이스몸체(100)의 외측방향으로 접철되는 측면차단프레임(220);을 포함하여 구성되고,상기 전방차단프레임(210)과 측면차단프레임(220)은상기 베이스몸체(100)의 상부방향으로 펼쳤을 때, 상기 전방차단프레임(210)의 일측 또는 타측에 상기 측면차단프레임(220)의 전방이 결합되어 차단부(200)를 형성하는 것을 특징으로 하며,상기 전방차단프레임(210)은일측과 타측 내부에 내입되어 설치되는 적어도 하나의 제1자석(212);을 포함하여 구성되고,상기 측면차단프레임(220)은전방 내부에 내입되어 설치되어 상기 제1자석(212)과 대응되는 제2자석(222);을 포함하여 구성되는 한편,상기 전방차단프레임(210)과 측면차단프레임(220)은상측 내부에 내입되어 설치되는 적어도 하나의 제3자석(216)(226);을 포함하여 구성되고,상기 차단부(200)는상부에 결합되어 상부를 폐쇄하는 상부차단프레임(230); 또는 상부에 결합되는 메쉬망(240);을 포함하여 구성되며,상기 상부차단프레임(230)과 메쉬망(240)은상기 전방차단프레임(210)과 측면차단프레임(220)의 제3자석(216)(226)과 대응되는 복수 개의 제4자석(232)(242);를 포함하여 구성되고,상기 베이스몸체(100)는상부면에 하부가 결합되고, 상기 음용방향으로 말단이 구부러지며, 상기 말단에 염부재(122)가 구비되는 염분섭취부(120);를 포함하여 구성되는 것을 특징으로 하는 우사용 위생 급수조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

888/1059 Row 888: application_number: 1020200024020, combined_string: invention_title: 가축 농가의 축사 관리 시스템 및 축사 관리 방법 abstract: 본 발명은 딥러닝 방식으로 축사 상태 및 가축의 건강 상태를 모니터링 하는 가축 농가의 축사 관리 시스템 및 축사 관리 방법에 관한 것으로, 축사에 설치되는 적어도 하나 이상의 CCTV 카메라로부터 축사 촬영 데이터를 획득하는 데이터 획득부, 상기 데이터 획득부로부터 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관 상태를 생성하는 가축 이미지 분석부 및 상기 가축 이미지 분석부에서 생성된 가축의 외관상태에 기반하여 딥러닝 기술에 기초하여 가축의 건강상태를 파악하는 건강상태 파악부를 포함하는 것을 특징으로 하는 가축 농가의 축사 관리 시스템에 의해 돼지를 비롯하여 가축의 성장 단계별 적정 체온을 유지하기 위해 축사의 온/습도 파악 및 조절을 용이하게 할 수 있도록 하여 가축의 성장 단계별 맞춤 환경의 제공 및 관리가 가능한 가축 농가의 축사 관리 시스템 및 축사 관리 방법을 제공할 수 있다는 효과가 도출된다. claims: 축사에 설치되는 적어도 하나 이상의 CCTV 카메라로부터 축사 촬영 데이터를 획득하는 데이터 획득부;상기 데이터 획득부로부터 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관 상태를 생성하는 가축 이미지 분석부; 및상기 가축 이미지 분석부에서 생성된 가축의 외관상태에 기반하여 딥러닝 기술에 기초하여 가축의 건강상태를 파악하는 건강상태 파악부;를 포함하고, 상기 축사 내의 가축에 부착된 비콘 모듈로부터 비콘 신호를 수신하여 가축의 실시간 움직임 데이터를 확보하는 움직임 파악부;를 더 포함하며,상기 가축 이미지 분석부는 상기 데이터 획득부로부터 관리자에 의해 설정된 주기마다 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관상태를 생성하되, 시간의 흐름에 따라 동일한 부위의 비교가 가능하도록 방향, 위치가 동일하게 3D모델 형태로 전용뷰어를 통해 제공하고, 가축 몸체에서 외상 변화 부위가 감지되는 경우에 변화되는 부위를 추출하여 표시해주는 것을 특징으로 하며, 축사의 온도, 습도 상태를 파악하고, 기상청의 API를 연동하여 날씨 데이터를 분석하여 분석된 날씨 데이터에 기반하여 축사의 온도, 습도 상태를 제어하는 축사 상태 관리부;를 더 포함하고,상기 가축 이미지 분석부는상기 데이터 획득부로부터 관리자에 의해 설정된 주기마다 시간대별 여러 방향에서 찍은 축사 촬영 데이터를 전달받아 획득한 축사 촬영 데이터를 연결해서 시간대별로 하나의 텍스쳐를 생성하고, Mesh 합성 과정을 거쳐 시간대별로 생성된 하나의 텍스쳐를 축사 내 가축의 3D Model에 입혀 축사 내 가축의 3D 모델을 객체 형식으로(OBJ format) 생성하며, 3D모델 형태로 전용뷰어를 통해 객체 형식으로(OBJ format) 생성된 축사 내 가축의 3D모델의 회전 및 특정 부위 확대에 대한 조작을 수행할 수 있는 사용자 인터페이스를 제공하고, 상기 축사 상태 관리부는 축사 내에서 사육되는 가축의 성장 단계별로 체온 조절을 해줄 수 있도록 축사 내부의 온도 관리를 성장 단계별로 다르게 세팅 가능한 것임을 특징으로 하는, 가축 농가의 축사 관리 시스템.제 1 항 또는 제 2 항에 기재된 가축 농가의 축사 관리 시스템에서 수행되는 가축 농가의 축사 관리 방법에 있어서, 데이터 획득부가 축사에 설치되는 적어도 하나 이상의 CCTV 카메라로부터 축사 촬영 데이터를 획득하는 단계;가축 이미지 분석부가 상기 데이터 획득부로부터 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관 상태를 생성하는 단계; 및가축 건강 상태 파악부가 상기 생성된 가축의 외관상태에 기반하여 딥러닝 기술에 기초하여 가축의 건강상태를 파악하는 단계;를 포함하고, 움직임 파악부가 상기 축사 내의 가축에 부착된 비콘 모듈로부터 비콘 신호를 수신하여 가축의 실시간 움직임 데이터를 확보하는 단계;를 더 포함하며, 상기 가축의 외관 상태를 생성하는 단계는, 상기 가축 이미지 분석부가 상기 데이터 획득부로부터 관리자에 의해 설정된 주기마다 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관상태를 생성하되, 시간의 흐름에 따라 동일한 부위의 비교가 가능하도록 방향, 위치가 동일하게 3D모델 형태로 전용뷰어를 통해 제공하고, 가축 몸체에서 외상 변화 부위가 감지되는 경우에 변화되는 부위를 추출하여 표시해주는 것을 특징으로 하고,축사 상태 관리부가 축사의 온도, 습도 상태를 파악하고, 기상청의 API를 연동하여 날씨 데이터를 분석하여 분석된 날씨 데이터에 기반하여 축사의 온도, 습도 상태를 제어하는 단계;를 더 포함하며, 상기 가축의 외관 상태를 생성하는 단계는,상기 데이터 획득부로부터 관리자에 의해 설정된 주기마다 시간대별 여러 방향에서 찍은 축사 촬영 데이터를 전달받아 획득한 축사 촬영 데이터를 연결해서 시간대별로 하나의 텍스쳐를 생성하고, Mesh 합성 과정을 거쳐 시간대별로 생성된 하나의 텍스쳐를 축사 내 가축의 3D Model에 입혀 축사 내 가축의 3D 모델을 객체 형식으로(OBJ format) 생성하며, 3D모델 형태로 전용뷰어를 통해 객체 형식으로(OBJ format) 생성된 축사 내 가축의 3D모델의 회전 및 특정 부위 확대에 대한 조작을 수행할 수 있는 사용자 인터페이스를 제공하고, 상기 축사 상태 관리부는 축사 내에서 사육되는 가축의 성장 단계별로 체온 조절을 해줄 수 있도록 축사 내부의 온도 관리를 성장 단계별로 다르게 세팅 가능한 것임을 특징으로 하는, 가축 농가의 축사 관리 방법., Ltext: 농업, prediction: 임업
889/1059 Row 889: application_number: 1020190166083, combined_string: invention_title: 가축용 냉온 음수 공급장치 abstract: 개시된 기술은 가축용 냉온 음수 공급장치에 관한 것으로, 축사 내부에 배치되어 일정 주기마다 상기 축사 내부의 온도 및 습도에 대한 환경정보를 감지하는 제 1 센서그룹; 상기 축사에 구비된 수조에 배치되어 상기 수조 내 음수(Drinking Water)의 온도를 감지하는 제 2 센서그룹; 상기 축사에 배치된 가축에 대한 생육정보를 입력받는 입력장치; 상기 환경정보 및 상기 생육정보를 수신하여 상기 가축에 대한 THI(Temperature Humidity Index) 지수를 산출하고, 상기 THI 지수에 따라 상기 음수의 온도를 조절하기 위한 제어신호를 생성하는 제어장치; 및 상기 제어신호를 수신하여 상기 수조 내 음수의 온도를 조절하는 온도조절장치;를 포함한다. 따라서 가축의 열 스트레스를 저감하고 정확한 온도의 냉온 음수를 공급하는 효과가 있다. claims: 축사 내부에 배치되어 일정 주기마다 상기 축사 내부의 온도 및 습도에 대한 환경정보를 감지하는 제 1 센서그룹;상기 축사에 구비된 수조에 배치되어 상기 수조 내 음수(Drinking Water)의 온도를 감지하는 제 2 센서그룹;상기 축사에 배치된 가축에 대한 생육정보를 입력받는 입력장치;상기 환경정보 및 상기 생육정보를 수신하여 상기 가축에 대한 THI(Temperature Humidity Index) 지수를 산출하고, 상기 THI 지수에 따라 상기 음수의 온도를 조절하기 위한 제어신호를 생성하는 제어장치; 및상기 제어신호를 수신하여 상기 수조 내 음수의 온도를 조절하는 온도조절장치;를 포함하는 가축용 냉온 음수 공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

890/1059 Row 890: application_number: 1020190153980, combined_string: invention_title: Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법 abstract: 본 발명은 젖소, 육우, 한우에게서 기능성 성분인 Omega-3가 풍부하게 포함된 우유와 쇠고기를 수득하기 위한 기능성 생초먹이 제조방법에 관한 것이다. 본 발명은 기능성 성분인 Omega-3가 풍부하게 포함된 우유와 쇠고기를 수득하기 위한 기능성 유기농 생초와, 해당 기능성 유기농 생초를 재배하기 위한 기능성 관주양액과, 해당 기능성 관주양액을 제조하기 위한 재료인 항산화 및 영양기능성 운모규암 다공성 이온화 미네랄 수용액을 만들어내는 것에 관한 것이다. 본 발명의 일 실시예에 따른 기능성 생초먹이 제조방법은 기능성 관주양액의 주 재료가 되는 운모규암을 소성하여 그 입자가 다공성 형질을 가지도록 가공하는 운모규암 다공화 소성단계; 및 다공화된 입자를 가진 소성 운모규암이 이온화 되도록 가공하는 다공성 운모규암 이온화단계; 및 상기의 다공성 이온화 운모규암을 물에 녹도록 가공하는 다공성 이온화 운모규암 수용화단계; 및 상기의 다공성 이온화 운모규암 수용액을 활용하여 기능성 관주양액을 제조하는 기능성 관주양액 제조단계; 및 상기의 기능성 관주양액을 활용하여 젖소, 육우, 한우의 조사료가 되는 기능성 밀싹을 재배하는 기능성 밀싹 재배단계;를 상기의 기능성 밀싹을 각각 젖소, 육우, 한우에게 조사료로 급이하는 기능성 조사료 급이단계;를 포함한다. 여기서, 상기 다공성 이온화 운모규암 수용액을 제조하기 위한 재료인 운모규암은 사암(규암)에서 운모의 비율이 25~35% 이상인 것을 말한다. 이와같은 운모규암 조성물은 상기의 제조단계에 의하여 기능성 관주양액으로 제조되어 기능성 밀싹을 재배할 시 밀싹의 세포 내에 풍부한 영양물질을 포함하게 되며, 병해없는 식물의 재배가 가능하다. 또한 본 기능성 밀싹 재배단계에 의하여 Omega-3 성분이 높게 나타난 밀싹은, 젖소의 젖, 육우와 한우의 쇠고기 성분을 좋게 하여 기능성 축산물(우육, 우유)의 수득을 도울 뿐만 아니라, 건강하고 병해없는 축산 사육 전반에 활용될 수 있다는 효용이 있다. claims: 본 발명은 Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법으로써,본 발명의 일 실시예에 따른 기능성 생초먹이 제조방법은,기능성 관주양액의 주 재료가 되는 운모규암을 소성하여 그 입자가 다공성 형질을 가지도록 가공하는 운모규암 다공화 소성단계; 및 다공화된 입자를 가진 소성 운모규암이 이온화 되도록 가공하는 다공성 운모규암 이온화단계; 및 상기의 다공성 이온화 운모규암을 물에 녹도록 가공하는 다공성 이온화 운모규암 수용화단계; 및 상기의 다공성 이온화 운모규암 수용액을 활용하여 기능성 관주양액을 제조하는 기능성 관주양액 제조단계; 및 상기의 기능성 관주양액을 활용하여 젖소, 육우 한우의 조사료가 되는 기능성 밀싹을 재배하는 기능성 밀싹 재배단계;를 상기의 기능성 밀싹을 각각 젖소, 육우, 한우에게 조사료로 급이하는 기능성 조사료 급이단계;를 포함하는 Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법.상기 다공성 운모규암 이온화단계는,3단계의 다공화 소성을 거친 클링커를 나노 분말로 분쇄한 후, 함유된 철석과 자철석을 걸러내기 위하여서 Electronic controller가 포함된 전류자기자석을 활용하고, 건식교반 균질기를 이용하여 혼합분말을 교반함으로써 혼합분말에 정전기를 발생시키는 이온화공정을 수행할 수 있는 Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법.기능성 밀싹 재배단계는,밀싹 씨앗을 침정한 다음 깨끗한 물로 세척하여 넓은 판에 담아 광합성을 야기하는 빛이 들지 않도록 검은 천으로 덮은 다음, 24~28 ℃를 유지하는 발아방에서 24시간동안 싹을 틔운 후, 묘판상에 파종하고, 각각의 묘판을 겹겹이 쌓아 단위 면적당 생산량을 최대화 하며, 24~28 ℃를 유지하는 재배시설에서 싹이 15cm 이상의 길이로 자랄때까지 성장을 시킨 후, White LED 광원을 고루 조사하여 광합성을 촉진시켜 푸른 색의 밀싹으로 재배할 수 있는 Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법., Ltext: 농업, prediction: 임업
891/1059 Row 891: application_number: 1020190136816, combined_string: invention_title: 축사용 정밀제어 방수방진 환풍기 abstract: 본 발명은 축사용 정밀제어 방수방진 환풍기에 관한 것으로, 축사용 환풍기에 오일실과 오링 및 패킹링을 구성함으로써, 방수방진 효과를 부여하고, 홀센서와 제어부 및 알림수단를 구성함으로써, 환풍기의 정밀제어 및 고장알림을 하여, 축사에서 사용되는 환풍기의 고장 및 성능저하를 방지하며, 고장 시, 신속한 교체 및 수리를 할 수 있어, 환풍기 고장 방치로 인한 축사 내 가축의 생육저하 및 질병확산을 방지하는 축사용 정밀제어 방수방진 환풍기에 관한 것이다. claims: 개구된 펜프레임 중심에 연결대을 통해 모터부가 고정되는 환풍기에 있어서,모터부의 모터하우징은 모터하우징의 정면을 관통하여 선두측이 돌출되는 회전자의 둘레를 따라 일정간격을 두고 축보호대가 돌출되고, 돌출된 회전자 선두측과 축보호대 사이에 오일실이 구성되며,모터부의 모터커버는 후방으로 개방된 모터하우징의 내경에 대응되는 끼움턱이 돌출되고, 끼움턱과 모터하우징 사이에 오링이 구성되며,모터부는 전방으로 개방된 콘덴서커버와 모터커버 배면이 결합하되, 콘덴서커버 정면 테두리에 대응되는 패킹링이 모터커버와 콘덴서커버 사이에 구성됨으로써, 모터부는 방수방진되며,모터부는 홀센서를 포함하고, 환풍기는 제어부를 포함하여, 홀센서에서 측정된 모터부의 회전속도와 제어부에서 설정된 회전속도의 차이를 파악하여, 모터부의 회전속도가 설정속도에 근접하도록 제어속도를 수정함으로써, 모터부를 정밀제어하는 축사용 정밀제어 방수방진 환풍기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

892/1059 Row 892: application_number: 1020190136829, combined_string: invention_title: 송아지용 축사 abstract: 본 발명은 송아지용 축사에 관한 것으로, 더욱 상세하게는 어미소 축사의 외측에 배치되는 휀스를 포함하고 어미소와 공유하는 사료통 또는 물통(W)에 인접 설치된 게이트(100)의 통로 면적이 다단계로 조절 가능하며 게이트(100)가 개폐상태를 안정적으로 고정 가능하여 송아지의 안전사고를 예방할 수 있는 송아지용 축사에 관한 것이다.이러한 본 발명은, 어미소 축사의 외측에 배치되어 어미소 축사의 휀스와 어미소 축사의 사료통 또는 물통(W)을 공유하는 송아지용 축사에 있어서, 상기 휀스(F)는, 상기 사료통 또는 물통(W)에 인접배치되어 송아지의 머리가 사료통 또는 물통(W) 측으로 통과할 수 있는 폭과 높이로 이루어지되, 송아지의 생육 과정에 따라 변하는 송아지의 머리 크기에 맞게 다단계의 통로면적을 구비하는 게이트(100)를 포함하여 구성된다. claims: 어미소 축사(400)의 외측에 배치되어 어미소 축사의 휀스와 어미소 축사의 사료통 또는 물통(W)을 공유하는 송아지용 축사에 있어서,상기 휀스(F)는,상기 사료통 또는 물통(W)에 인접배치되어 송아지의 머리가 사료통 또는 물통(W) 측으로 통과할 수 있는 폭과 높이로 이루어지되, 송아지의 생육 과정에 따라 변하는 송아지의 머리 크기에 맞게 다단계의 통로면적을 구비하는 게이트(100)를 포함하는 것을 특징으로 하는 송아지용 축사., Ltext: 농업, prediction: 임업
893/1059 Row 893: application_number: 1020190134173, combined_string: invention_title: 실내 정화용 태양광가열장치가 구비된 축사용 시설물 abstract: 본 발명은 실내 정화용 태양광가열장치가 구비된 축사용 시설물에 관한 발명으로서, 상세하게는 축사와 같은 가축이나 원예작물 기르는 시설물에 맞추어서 태양광 발전판을 설치하여 주되, 비치는 태양광으로 발전되는 전력으로 가동되는 펌프에 의한 가압공기를 급속한 서냉으로 형성되는 냉각공기를 축사의 실내공간에 분출로서 실내정화를 제공하는 발명이다.일반적으로 축사용 하우스와 같은 축사단지는 대부분 도시의 가장자리에서 기술의 발전에 따라 점점 대단위로 설치함으로서, 이의 면적에서 기후 변화로 형성되는 폭염이나 혹서기에 발생하는 피해에 대한 대비가 필요하는 것이다.이는 하우스를 서로 연속적으로 설치로서 원예단지나 하우스로 제공되는 실내공간은 넓은 면적을 형성함으로서, 상기 비닐하우스 단지의 면적에 비치는 태양광의 량으로 발전하는 발전량은 많다고 할 것입니다.따라서 본 발명을 상세히 설명하면, 축산단지(43)에서 골조(11)의 외측으로 감싸주는 비닐(21)로 조립으로 실내공간(28)이 형성되는 하우스(20)와, 상기 하우스(20)용 갓길(14)에서 연속 반복적으로 길이방향에 따라 돌출되는 기둥(15)과, 상기 돌출되는 기둥(15) 사이를 일체로 연결되는 프레임(29)과, 상기 기둥(15)와 프레임(29)에 결합되도록 유입관(65)에 연결된 가압탱크(68)와, 프레임(29)에 결합된 제어장치의 구동으로 회전되는 회전형 도어(27)로, 기둥(15) 사이에 설치된 차양막(30)의 구동으로 조절되는 공기통로(41)와, 상기 기둥(15)을 연결되는 빔(17)으로 조립구간(18)이 구축된 하우스(20)에서 양측으로 경사지는 돌출부(38)를 형성하는 경사프레임(23)과, 상기 경사프레임(23)에 힌지(36)로 결합되는 태양광가열판(40)과, 상기 태양광가열판(40)에 발전소자(16)가 구비된 태양광발전판(25)으로 제공시켜 주는 축산단지에 있어서, 상기 태양광발전판(25)의 배면에다 양측에 입출구(44)가 구비된 가열통로(45)로 결합된 가열판형 탱크(33)와, 상기 가열판형 탱크(33)에서 연결된 입출구(44)에 연결된 공급관(51)에 관통되는 분사구(59)로 냉각된 공기를 분사시켜 주도록 제공되는 발명이다. claims: 축산단지(43)에서 골조(11)의 외측으로 감싸주는 비닐(21)로 조립으로 실내공간(28)이 형성되는 하우스(20)와, 상기 하우스(20)용 갓길(14)에서 연속 반복적으로 길이방향에 따라 돌출되는 기둥(15)과, 상기 돌출되는 기둥(15) 사이를 일체로 연결되는 프레임(29)과, 상기 기둥(15)와 프레임(29)에 결합되도록 유입관(65)에 연결된 가압탱크(68)와, 프레임(29)에 결합된 제어장치의 구동으로 회전되는 회전형 도어(27)로, 기둥(15) 사이에 설치된 차양막(30)의 구동으로 조절되는 공기통로(41)와, 상기 기둥(15)을 연결되는 빔(17)으로 조립구간(18)이 구축된 하우스(20)에서 양측으로 경사지는 돌출부(38)를 형성하는 경사프레임(23)과, 상기 경사프레임(23)에 힌지(36)로 결합되는 태양광가열판(40)과, 상기 태양광가열판(40)에 발전소자(16)가 구비된 태양광발전판(25)으로 제공시켜 주는 축산단지에 있어서, 상기 태양광발전판(25)의 배면에다 양측에 입출구(44)가 구비된 가열통로(45)로 결합된 가열판형 탱크(33)와, 상기 가열판형 탱크(33)에서 연결된 입출구(44)에 연결된 공급관(51)에 관통되는 분사구(59)로 냉각된 공기를 분사시켜 주도록 제공되는 실내 정화용 태양광가열장치가 구비된 축사용 시설물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

894/1059 Row 894: application_number: 1020190127195, combined_string: invention_title: 축사환경 측정장치 abstract: 본 발명은 무선통신으로써 로라(RORA)와 블루투스(BLUETOOTH) 기반을 이용한 스마트팜의 축사환경 측정장치에 관한 것이다. 이를 위한 본 발명은, 각 축사(10A - 10F)마다 전송거리의 비콤모듈(20)이 각기 설치되어 있으며, 해당 축사위치 정보를 접근하는 작업자 송신기(30)로 전송하고, 상기 작업자 송신기(30)와 함께 로라기반의 표준통신 수신기(40)가 별도로 설치되어 네트워킹되도록 구성하며; 상기 작업자 송신기(30)에는 온습도센서와 가스센서, 리튬이온 배터리가 각기 설치되고, 또 작업자 송신기(30)는 설치된 해당 비콘모듈(20)에서 축사위치 정보를 수신하고 자체에 부착된 가스센서(50)를 이용한 오염도를 확인하며 또는 온습도센서(60)로 각 축사내의 온습도를 확인한 것을 그 특징으로 한다. claims: 각 축사(10A - 10F)마다 전송거리의 비콘모듈(20)을 각기 설치하며, 해당 축사위치 정보를 접근하는 작업자 송신기(30)로 전송하고, 상기 작업자 송신기(30)와 함께 로라기반의 표준통신 수신기(40)가 별도로 설치되어 네트워킹되도록 구성하며; 상기 작업자 송신기(30)에는 온습도센서와 가스센서, 리튬이온 배터리가 각기 설치되고, 또 작업자 송신기(30)는 설치된 해당 비콘모듈(20)에서 축사위치 정보를 수신하고 자체에 부착된 가스센서(50)를 이용한 오염도를 확인하며 또는 온습도센서(60)로 각 축사내의 온습도를 확인함을 포함하되; 상기 작업자 송신기(30)는 원칩마이컴(35)에 와이파이 및 블루투스 안테나(31), 부져(34), 로라안테나(32)를 통한 로라모듈(33)이 각각 연결되는 한편, 리튬이온 배터리(37)를 통한 배터리팩 매니져(36)와, 가스센서(50)가 OP앰프(38)를 통한 증폭회로(39)가 각기 연결되고; 상기 표준통신 수신기(40)는 로라안테나(42)를 통한 로라모듈(44)이 원칩마이컴(46)과 연결되도록 구성되고, 수신정보는 작업시간, 작업위치, 현장온도와 현장습도, 현장 오염도이고, 송신정보로는 알람신호인 것을 특징으로 하는 축사환경 측정장치.작업복에 간편히 착용하는 작업자 송신기(30)에는 온습도센서(60)와 가스센서(50), 리튬이온 배터리가 각기 설치되고; 원칩마이컴(35)에 와이파이 및 블루투스 안테나(31), 부져(34), 로라안테나(32)를 통한 로라모듈(33)이 각각 연결되는 한편, 리튬이온 배터리(37)를 통한 배터리팩 매니져(36)와, 가스센서(50)가 OP앰프(38)를 통한 증폭회로(39)가 각기 연결되도록 구성된 작업자 송신기(30)는 설치된 해당 비콘모듈(20)에서 축사위치 정보를 수신하고 자체에 부착된 가스센서(50)를 이용한 현장 오염도를 확인하며 온습도센서(60)로 각 축사내 온습도의 확인함을 포함하되; 상기 가스센서(50)에 연결된 저항(R26)에 1 PPM 당 40 ~ 200 nA 정도의 전류가 발생하고, 상기 가스센서(50)가 동작을 정지할 경우에 전계효과 트랜지스터 (Q2)에 역전압이 흐르면서 화학식 반응을 정지시키고; 상기 가스센서(50)에서는 발생된 전압이 너무 미세하여 미세전압을 증폭하는 OP 앰프(U3A)로 1 차 증폭을 하고, 대기 온도에 적절하게 증폭도를 변화하기 위해 서미스터(RTH1)를 부착하여 온도에 따른 정밀도를 보완하며, 센서 마다 전류값이 많이 차이가 나서 ADC 측정이 힘들므로 이를 보완하기 위하여 추가 OP 앰프(U4A)를 두어 2 차 증폭을 한 것을 특징으로 하는 축사환경 측정장치., Ltext: 농업, prediction: 임업
895/1059 Row 895: application_number: 1020190112674, combined_string: invention_title: 착유기 abstract: 본 발명은 플랜지판을 가압통의 하부에 일체로 형성시켜 곡물의 착유과정에서 작업효율을 향상시킬 수 있으며, 깻묵의 제거 공정이 간편하게 반자동으로 이루어지도록 그 구조가 개선된 착유기에 관한 것으로, 상판 및 하판과; 중판과; 착유통과; 착유하우징과; 가압통; 및 스톱퍼수단;을 포함하되, 상기 스톱퍼수단은 상기 중판의 좌,우측 상부에 고정되고 서로 대칭되게 마련되는 스톱퍼 몸체와, 상기 스톱퍼 몸체의 상측에 좌,우측으로 이동되며 하부가 상기 스톱퍼 몸체의 내부로 진입되고 일단부에 베어링롤러가 마련된 스톱퍼바와, 상기 스톱퍼 몸체의 내부에 마련되고 상기 스톱퍼바측에 일방향 탄성력을 제공하는 스프링부재, 및 일단부가 상기 스톱퍼 몸체의 내부에 수용되고 타단부가 상기 스톱퍼 몸체의 외측으로 출몰동작되며 상기 스프링부재를 지지하는 복수의 지지핀을 포함하여 이루어진다. claims: 복수의 기둥(50)이 관통되도록 결합되는 상판(10) 및 하판(20)과;상기 기둥(50)에 관통되도록 결합되며 승강수단에 의해 상,하 승강동작되는 중판(200)과;상기 중판(200)의 상,하 동작시 연동되고 하부 이동실린더(700)과 착유하우징(350)을 매개로 전진 동작 및 복귀동작되며, 내부에 착유용 곡물이 수납되는 공간이 마련되고, 승강실린더(500)에 의해 승강동작되는 착유판(320)을 갖는 착유통(300)과;상기 중판(200)에 상단부 테두리가 지지되고, 내부에 착유통(300)이 수용되며 상기 하부 이동실린더(700)에 의해 전진 및 복귀동작되는 착유하우징(350)과;상기 상판(10)의 하측에 배치되고 상부 이동실린더(150)에 의해 후진동작 및 복귀동작되며 하부에 플랜지판(110)이 일체로 형성된 가압통(100)과;상기 중판(200)의 좌,우 양측에 마련되고, 상기 가압통(100)의 후진동작시 서로 간의 간격이 좁아지며 상기 가압통(100)의 복귀동작시 서로 간의 간격이 멀어지는 스톱퍼바(410)를 구비하며, 상기 스톱퍼바(410)의 단부가 상기 착유통(300)의 상승을 방지하는 스톱퍼수단(400);을 포함하되,상기 스톱퍼수단(400)은 상기 중판(200)의 좌,우측 상부에 고정되고 서로 대칭되게 마련되는 스톱퍼 몸체(405)와,상기 스톱퍼 몸체(405)의 상측에 좌,우측으로 이동되며 하부가 상기 스톱퍼 몸체(405)의 내부로 진입되고 일단부에 베어링롤러(420)가 마련된 스톱퍼바(410)와,상기 스톱퍼 몸체(405)의 내부에 마련되고 상기 스톱퍼바(410)측에 일방향 탄성력을 제공하는 스프링부재(450)와,일단부가 상기 스톱퍼 몸체(405)의 내부에 수용되고 타단부가 상기 스톱퍼 몸체(405)의 외측으로 출몰동작되며 상기 스프링부재(450)를 지지하는 복수의 지지핀(455)을 구비한 것을 특징으로 하는 착유기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

896/1059 Row 896: application_number: 1020190100145, combined_string: invention_title: 우사용 목걸이틀 abstract: 본 발명의 일 실시예에 따른 우사용 목걸이틀은, 하부가로대; 상기 하부가로대의 상부에 수평으로 평행하게 배치되며, 주걸쇄가 형성되는 상부가로대; 상기 상부가로대 및 상기 하부가로대 사이에 일정각도로 절곡되어 기울어지게 설된 회동지지대; 및 상기 회동지지대에 시소 방식으로 회동가능하게 고정되며, 상단에는 복수의 체결홈이 형성되어 상기 주 걸쇄에 다단으로 체결되는 주 체결핀이 설치된 회동봉;을 포함할 수 있다. claims: 우사용 목걸이틀에 있어서, 하부가로대; 상기 하부가로대의 상부에 수평으로 평행하게 배치되며, 주걸쇄가 형성되는 상부가로대; 상기 상부가로대 및 상기 하부가로대 사이에 일정각도로 절곡되어 기울어지게 설치된 회동지지대; 및 상기 회동지지대에 시소 방식으로 회동가능하게 고정되며, 상단에는 복수의 체결홈이 형성되어 상기 주 걸쇄에 다단으로 체결되는 주 체결핀이 설치된 회동봉;을 포함하고,상기 우사용 목걸이틀은, 상기 주 걸쇄를 관통하여 회동되는 가로유동축에 형성되되, 상기 주 걸쇄로부터 소정 간격 이격된 위치에 형성된 보조 걸쇄; 및 상기 주 걸쇄의 상부에 힌지 결합되며, 체결홈이 형성되어 상기 보조 걸쇄에 체결됨으로써 상기 주 체결핀이 분리됨을 방지하는 보조 체결핀을 더 포함하고,상기 가로유동축의 단부에는 ㄴ자 형상의 걸림손잡이부가 설치되고, 상기 걸림손잡이부의 상측에는 실린더하우징과 단부에 걸림후크가 형성된 피스톤로드로 이루어지는 공압실린더가 설치되되, 상기 실린더하우징은 일단이 상기 회동봉과 마주보는 세로지지대에 회동가능하게 설치되고, 상기 피스톤로드의 걸림후크에는 상기 걸림손잡이부가 상방향으로 회동되어 걸림되거나, 공압에 의해 피스톤로드가 신장되면서 상기 걸림손잡이부를 하방향으로 밀어 걸림후크에서 상기 걸림손잡이부의 걸림이 해제되도록 구성되며,상기 우사용 목걸이틀은, 상기 회동봉 및 상기 세로지지대의 길이 방향을 따라 소정 간격마다 설치되는 감지 센서; 및 상기 회동봉에 설치된 상기 주 체결핀의 회동과, 상기 공압 실린더를 전자적으로 제어하며, 상기 감지 센서로부터 수신되는 센싱 정보에 기초하여 상기 회동봉 및 상기 세로지지대 사이에 소가 위치하는 것으로 확인되면 감지된 위치에 대응되는 주 체결핀만을 독립적으로 구동하는 제어부를 더 포함하되,상기 제어부는, 소정 기간 동안 상기 감지 센서로부터 수신되는 복수의 센싱값에 기초하여 상기 우사용 목걸이틀을 출입하는 소의 평균 목둘레 길이를 추정하고, 추정된 평균 목둘레 길이에 기초하여 상기 회동봉 및 상기 세로지지대 사이로 소가 진입하는 것으로 확인되면 주 체결핀에 형성된 복수의 체결홈 마다 설치된 조명 장치 중 어느 하나의 조명 장치가 작동되도록 제어하며,상기 우사용 목걸이틀은, 상기 회동 지지대의 하단에 설치되어 상기 회동봉의 회동 각도를 미세 조절할 수 있도록 상하 방향의 길이가 다단으로 조절되는 높이 조절부 및 상기 회동지지대의 길이 방향을 따라 설치되는 적어도 하나의 파손방지부를 더 포함하고,상기 높이 조절부는, 원기둥 형태로 형성되어 상기 회동 지지대의 하측을 지지하는 상부 프레임; 및 상부에 상기 상부 프레임이 삽입될 수 있도록 상기 상부 프레임의 하부의 형태에 대응하는 형상의 안착홈이 상부에 형성하며, 상기 상부 프레임의 지지 높이를 조절할 수 있도록 상기 안착홈에 삽입되는 상기 상부 프레임의 삽입 깊이가 다단으로 조절되는 하부 프레임;을 포함하며,상기 상부 프레임은, 원기둥 형태로 형성되어 상기 안착홈에 삽입되는 상부 본체; 상기 상부 본체의 하부 외주면을 따라 다수 개가 설치되며, 상기 안착홈의 벽면을 따라 이동된 후 상기 상부 본체가 더 이상 하강되지 않도록 체결되는 체결 돌기; 및 상기 상부 본체가 상기 안착홈을 따라 하강하다 더 이상 하강하지 못하도록 상기 상부 본체의 상부 외주면을 일주하고 연장 설치되는 걸림턱;을 포함하며,상기 하부 프레임은, 상기 체결 돌기가 상하 수직 방향으로 이동하기 위한 공간을 형성할 수 있도록 상기 안착홈의 벽면의 상측으로부터 하측 수직 방향으로 연장 형성되는 수직 통로; 상기 체결 돌기가 수평 방향으로 이동할 수 있도록 상기 수직 통로의 중간 부분으로부터 일측 수평 방향으로 연장 형성되는 제1 수평 통로; 상기 체결 돌기가 안착될 수 있도록 상기 제1 수평 통로의 말단에서 하측 수직 방향으로 연장 형성되는 제1 체결 통로; 상기 체결 돌기가 수평 방향으로 이동할 수 있도록 상기 수직 통로의 하측으로부터 일측 수평 방향으로 연장 형성되는 제2 수평 통로; 및 상기 체결 돌기가 안착될 수 있도록 상기 제2 수평 통로의 말단에서 하측 수직 방향으로 연장 형성되는 제2 체결 통로;를 포함하며,상기 제1 체결 통로는, 상기 제1 수평 통로를 따라 수평 방향으로 이동하던 상기 체결 돌기가 하강된 후 안착될 수 있도록 제1 수평 통로의 말단에서 하측 방향으로 연장 형성되는 하강 통로; 상기 하강 통로의 상부 일측 또는 양측 벽면에 함몰 형성되는 설치홈에 설치되며, 상기 하강 통로로 노출된 전면이 하측으로 갈수록 상기 설치홈으로부터 멀어지는 방향으로 경사진 경사면을 형성하며, 상기 설치홈에 삽입된 후단이 탄성체에 의해 지지되어 상기 체결 돌기가 상기 경사면을 따라 하강하면 상기 탄성체 방향으로 이동된 후 상기 체결 돌기가 상기 경사면을 통과하여 상기 하강 통로의 하측 공간에 안착되면 상기 탄성체의 탄성력에 의해 상기 경사면이 상기 설치홈으로부터 다시 노출되어 전단 하측면으로 상기 체결 돌기의 상측을 체결하는 체결구; 및 상기 하강 통로의 하부 공간에 설치되며, 상기 하강 통로의 하측 바닥면에 설치되는 탄성체에 의하여 지지되어 상측에 안착되는 상기 체결 돌기를 탄성력을 이용하여 지지하는 탄성 지지판;을 포함하며,상기 파손 방지부는, 상기 회동지지대에 설치되는 하부캡; 상기 하부캡의 상측에 이격되어 설치되어 회동봉을 지지하는 상부캡; 및 상기 하부캡과 상기 상부캡의 사이에 설치되어 상기 상부캡을 지지하는 지지기둥;을 포함하며,상기 하부캡은, 원기둥 형태로 형성되는 캡 본체, 및 상기 지지기둥의 하부가 삽입될 수 있도록 상기 캡 본체의 상부면으로부터 하측 방향으로 상기 지지기둥의 하부 형태에 대응하는 형상으로 함몰 형성되는 하부 안착홈을 포함하며,상기 상부캡은, 상기 지지기둥의 상부가 삽입될 수 있도록 하부면으로부터 상측 방향으로 상기 지지기둥의 상부 형태에 대응하는 형상으로 함몰 형성되는 상부 안착홈이 형성되며,상기 지지기둥은, 중심각이 직각인 원호 형상의 기둥 형태로 형성되는 4 개의 기둥모듈이 서로 연결 설치되어 원기둥 형태를 형성하며, 하부가 상기 하부 안착홈에 삽입되고, 상부가 상기 상부 안착홈에 삽입되며,상기 기둥모듈은, 중심각이 직각인 원호 형상의 기둥 형태로 형성되는 모듈 본체; 상기 모듈 본체의 일측 평면에 상하 길이 방향으로 연장 형성되며, 다른 모듈 본체의 다른 일측 평면에 형성된 슬라이딩 홈의 상측으로부터 삽입 체결되는 슬라이딩 돌기; 상기 모듈 본체의 다른 일측 평면에 상기 슬라이딩 돌기의 형태에 대응하는 형상으로 상하 길이 방향으로 함몰 형성되며, 다른 모듈 본체의 슬라이딩 돌기가 삽입 체결되어 상하 방향으로 슬라이딩 이동하는 슬라이딩 홈; 상기 모듈 본체의 상부에 돌출 형성되어 상기 상부 안착홈의 상측면을 지지하는 지지 돌기; 및 상기 모듈 본체의 상측에 안착된 상기 상부캡이 회전할 수 있도록 상기 지지 돌기의 상부에 설치되는 바퀴;를 포함하며,상기 하부캡은, 상기 하부 안착홈에 대응하는 형상의 원판 형태로 형성되며, 탄성력을 이용하여 지지하기 위한 다수 개의 탄성체가 하측면에 설치되는 지지 원판; 및 상기 하부 안착홈에 대응하는 형상의 원판 형태로 형성되어 상기 지지 원판의 상측에 안착되며, 상측에 안착된 상기 기둥모듈을 상기 하부 안착홈에서 회전시킬 수 있도록 하측면의 각 사방에 바퀴가 설치되는 회전 원판;을 더 포함하는, 우사용 목걸이틀., Ltext: 농업, prediction: 임업
897/1059 Row 897: application_number: 1020190099745, combined_string: invention_title: 가축용 사료 이송 및 공급장치 abstract: 본 발명은 가축용 사료 이송 및 공급장치에 관한 것으로, 사료를 이송하는 이송 컨베이어; 상기 이송 컨베이어의 일측부에 구성되며, 이송되는 사료를 공급하여 일정기간 저장 및 배출될 수 있도록 되도록 하고, 저장된 사료의 배출이 이루어지도록 운송하는 사료 운송수단; 일측부에 상기 사료 운송수단의 승강 작동을 지지하도록 구성되고, 타측 상단부로 저장된 상기 사료의 배출이 이루어지도록 구성된 지지 프레임과, 상기 지지 프레임의 내부에 다수개로 구성되며, 상기 사료 운송수단으로부터 사료를 공급받아 적재 및 저장하는 적재 컨베이어와, 상기 적재 컨베이어의 회전 작동을 지지하며, 적재된 사료의 배출이 이루어지도록 하는 구동부재를 포함하는 프레임부; 상기 프레임부 및 사료 운송수단의 작동에 의해 저장된 상기 사료가 투입되며, 투입된 사료를 일정 크기로 분쇄하여 배출하는 사료 분쇄기; 및 상기 사료 분쇄기의 일측부에 구성되고, 축사의 전방부에 구성되어 배출되는 절단된 사료를 각 축사 마다 공급하는 공급 컨베이어;를 포함하는 것을 특징으로 한다. claims: 사료를 이송하는 이송 컨베이어; 상기 이송 컨베이어의 일측부에 구성되며, 이송되는 사료를 공급하여 일정기간 저장 및 배출될 수 있도록 되도록 하고, 저장된 사료의 배출이 이루어지도록 운송하는 사료 운송수단; 일측부에 상기 사료 운송수단의 승강 작동을 지지하도록 구성되고, 타측 상단부로 저장된 상기 사료의 배출이 이루어지도록 구성된 지지 프레임과, 상기 지지 프레임의 내부에 다수개로 구성되며, 상기 사료 운송수단으로부터 사료를 공급받아 적재 및 저장하는 적재 컨베이어와, 상기 적재 컨베이어의 회전 작동을 지지하며, 적재된 사료의 배출이 이루어지도록 하는 구동부재를 포함하는 프레임부; 상기 프레임부 및 사료 운송수단의 작동에 의해 저장된 상기 사료가 투입되며, 투입된 사료를 일정 크기로 분쇄하여 배출하는 사료 분쇄기; 및 상기 사료 분쇄기의 일측부에 구성되고, 축사의 전방부에 구성되어 배출되는 절단된 사료를 각 축사 마다 공급하는 공급 컨베이어;를 포함하는 것을 특징으로 하는 가축용 사료 이송 및 공급장치.사료를 이송하는 이송 컨베이어; 상기 이송 컨베이어의 일측부에 구성되며, 이송되는 사료가 안착되고 안착된 사료를 상부로 운송하는 사료 운송수단; 상기 사료 운송수단이 결합되며, 상기 사료 운송수단의 운송 작동이 이루어지도록 지지 프레임과, 상기 사료 운송수단이 결합되는 이송 프레임과, 상기 지지 프레임의 외면와 상기 이송 프레임의 내면 사이에 구성되며, 상기 이송 프레임의 위치 이동이 이루어지도록 구성되는 구동부재로 구성되는 프레임부; 상기 사료 운송수단의 하향 이동을 안내하며, 투입된 사료의 분쇄가 이루어지도록 분할된 공간을 형성하는 분쇄본체와, 상기 분쇄본체의 상부에 구성되며, 낙하하는 사료가 투입되는 분쇄호퍼와, 상기 분쇄호퍼로부터 공급되는 사료를 분쇄하는 분쇄장치 및 분쇄된 사료를 공급 컨베이어로 배출하는 공급장치를 포함하는 사료 분쇄기; 및 상기 사료 분쇄기의 일측부에 구성되고, 축사의 전방부에 구성되어 배출되는 사료를 각 축사 마다 공급하는 공급 컨베이어;를 포함하는 것을 특징으로 하는 가축용 사료 이송 및 공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

898/1059 Row 898: application_number: 1020190097866, combined_string: invention_title: 되새김 활동 측정을 이용한 소의 건강 관리 시스템 abstract: 본 발명은 소의 건강 관리 시스템에 관한 것으로서, 보다 구체적으로는 되새김 활동 측정을 이용한 소의 건강 관리 시스템으로서, 소에 부착되어 소의 움직임 및 행동을 감지하는 행동탐지 센서; 상기 행동탐지 센서에서 감지된 데이터를 수신받아 저장하고, 기저장된 축우 관련 사육정보와 함께 데이터베이스를 구축하는 DB 서버; 및 상기 DB 서버에 저장된 데이터를 분석하여, 소의 행동 패턴을 인식하고 건강을 관리하는 분석 서버를 포함하며, 상기 분석 서버는, 상기 DB 서버에 저장된 움직임 데이터를 기초로 분석하여, 소의 먹이 활동상태, 및 되새김 활동상태를 포함하는 행동 유형의 특징적 패턴을 찾아내고, 소의 행동 유형을 판단하는 행동 분석 모듈; 및 상기 행동 분석 모듈에서 판단된 상기 소의 행동 유형 정보를 통해 행동별 활동량을 분석하여, 소의 질병을 탐지하고 건강을 관리하는 질병 탐지 모듈을 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 되새김 활동 측정을 이용한 소의 건강 관리 시스템에 따르면, 행동탐지 센서에서 감지한 소의 먹이 활동상태, 및 되새김 활동상태의 행동 정보를 토대로, 소의 질병을 탐지하고 건강을 관리하는 질병 탐지 모듈을 포함함으로써, 소의 질병 감염 여부를 보다 정확하고 용이하게 판단할 수 있어, 소의 건강상태를 향상시키고 질병 미감지로 인한 피해를 줄여, 한우 농가의 생산성 및 수익성에 이바지할 수 있으며, 개별 가축에 대한 건강 정보를 지속해서 자동으로 제공함에 따라, 질병을 미리 예방하고 질병의 확산을 방지할 수 있다.또한, 본 발명에서 제안하고 있는 되새김 활동 측정을 이용한 소의 건강 관리 시스템에 따르면, 가속도 센서에서 감지된 3축 가속도 신호의 drift 발생으로 인해 생길 수 있는 오차를 보정 및 전처리하고, 감지된 3축 가속도 신호를 통계적, 수학적 방법으로 분석함으로써, 소의 행동 유형 패턴을 보다 정교하게 판단할 수 있으며, 특히, 인공지능 기술 중 딥러닝 알고리즘을 이용하여 소의 행동 유형을 판단함으로써, 같은 유형의 행동이 개체에 따라 다양한 신호 패턴을 보여 그 신호의 편차가 크더라도 오류를 줄일 수 있고, 개체별로 상이한 행동 양식, 성격, 생활 습성, 우방에서의 서열 등을 고려한 판단이 가능하여, 소의 질병 탐지적중률을 제고시킬 수 있다.뿐만 아니라, 본 발명에서 제안하고 있는 되새김 활동 측정을 이용한 소의 건강 관리 시스템에 따르면, 분석 서버에서 분석한 소의 행동 유형 정보 및 질병 탐지 정보와 관찰카메라부에서 촬영한 영상을 기초로, 소의 생애 주기에 따른 건강상태 추적 및 축사 모니터링이 가능한 스마트기기의 애플리케이션을 구축함으로써, 사용자에게 축사의 개체별 종합적인 건강 관리 솔루션을 제공하고, 궁극적으로는 축사 전반적으로 통합적인 관리서비스를 제공하여 축산업의 경쟁력을 상승시킬 수 있다. claims: 소의 건강 관리 시스템(10)으로서,소에 부착되어 소의 움직임 및 행동을 감지하는 행동탐지 센서(100);상기 행동탐지 센서(100)에서 감지된 데이터를 수신받아 저장하고, 기저장된 축우 관련 사육정보와 함께 데이터베이스를 구축하는 DB 서버(200);상기 DB 서버(200)에 저장된 데이터를 분석하여, 소의 행동 패턴을 인식하고 건강을 관리하는 분석 서버(300);축사를 24시간 촬영하고 촬영된 영상을 상기 DB 서버(200)로 송신하는 관찰카메라부(400); 및상기 분석 서버(300)에서 분석한 행동 유형 정보 및 건강 관리 정보와 상기 관찰카메라부(400)에서 촬영된 영상을 시각화시켜 보여주는 스마트기기(500)를 포함하며,상기 분석 서버(300)는,상기 DB 서버(200)에 저장된 움직임 데이터를 기초로 분석하여, 소의 먹이 활동상태, 및 되새김 활동상태를 포함하는 행동 유형의 특징적 패턴을 찾아내고, 소의 행동 유형을 판단하는 행동 분석 모듈(310); 및상기 행동 분석 모듈(310)에서 판단된 상기 소의 행동 유형 정보를 통해 행동별 활동량을 분석하여, 소의 질병을 탐지하고 건강을 관리하는 질병 탐지 모듈(320)을 포함하고,상기 질병 탐지 모듈(320)은,기설정된 일정 시간 단위로 행동 유형별 시간 점유율 및 분포를 계산하여 소의 질병 여부를 탐지하고 건강을 관리하며, 상기 DB 서버(200)에 저장된 움직임 데이터로부터 개체별 습성 및 상태 정보를 취득하여, 소의 질병 여부 판단을 보완하는 것을 특징으로 하는, 되새김 활동 측정을 이용한 소의 건강 관리 시스템(10)., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

899/1059 Row 899: application_number: 1020190090293, combined_string: invention_title: 젖소 유두 보호제 및 그 제조방법 abstract: 본 발명은 젖소 유두 보호제 및 그 제조방법에 관한 것이다.본 발명에 따른 젖소 유두 보호제는 미네랄 오일, 호호바씨 오일, 라놀린 오일, 토코페릴아세테이트, 소르비탄세스퀴올리에이트, 카프릴릭/카프릭트리글리세라이드, 이소프로필팔미테이트, 이소프로필메칠페놀(o-사이멘-5-올(o-Cymen-5-ol)) 및 부틸파라벤으로 이루어진 조성물을 포함한다.상기한 구성에 의해 본 발명은 보습력을 향상시켜 젖소의 유두를 항상 부드럽게 유지하고 겨울철 영하의 날씨에도 유두 및 유두 주변의 살이 트거나 갈라지는 것을 방지함으로써, 착유시 젖소의 스트레스를 줄일 수 있고 젖소 유두 주변에 오물이 쉽게 부착되는 것을 방지할 수 있다. claims: 미네랄 오일, 호호바씨 오일, 라놀린 오일, 토코페릴아세테이트, 소르비탄세스퀴올리에이트, 카프릴릭/카프릭트리글리세라이드, 이소프로필팔미테이트, 이소프로필메칠페놀(o-사이멘-5-올(o-Cymen-5-ol)) 및 부틸파라벤으로 이루어진 조성물을 포함하되,상기 조성물은 미네랄 오일 97 내지 99 중량부, 호호바씨 오일 0.2 내지 0.4 중량부, 라놀린 오일 0.15 내지 0.35 중량부, 토코페릴아세테이트 0.05 내지 0.25 중량부, 소르비탄세스퀴올리에이트 0.05 내지 0.15 중량부, 카프릴릭/카프릭트리글리세라이드 0.05 내지 0.15 중량부, 이소프로필팔미테이트 0.05 내지 0.15 중량부, 이소프로필메칠페놀(o-사이멘-5-올(o-Cymen-5-ol)) 0.005 내지 0.015 중량부 및 부틸파라벤 0.03 내지 0.07 중량부가 포함되고,상기 조성물 이외에, 보이차 추출액 1 내지 3 중량부, 어성초 추출액 2 내지 4 중량부, 오레가노 오일 3 내지 7 중량부 및 브링그라즈 오일 1 내지 3 중량부가 더 포함되되,상기 보이차 추출액은,보이차 생잎을 준비한 후 세척하여 상기 보이차 생잎에 부착되어 있는 이물질을 제거한 후, 상기 세척된 보이차 생잎을 25 내지 30℃ 온도에서 5 내지 10시간 동안 건조하고, 상기 건조된 보이차 생잎을 가열 용기에 투입한 후 90 내지 100℃의 온도에서 3 내지 5분 동안 1차 덖음하고, 상기 1차 덖음된 보이차 생잎을 130 내지 140℃의 온도에서 30 내지 60초 동안 2차 덖음하며, 상기 2차 덖음된 보이차 생잎에 용매를 혼합하고 초음파를 가함으로써 보이차 혼합액을 제조하되, 상기 용매는 상기 2차 덖음된 보이차 생잎 100 중량부에 대해 300 내지 600 중량부의 중량 비율로 혼합되고, 상기 용매로는 물이 사용되며, 상기 2차 덖음된 보이차 생잎 및 용매로 이루어진 혼합물에 가해지는 초음파는 60 내지 80KHz의 진동주파수에서 30 내지 60분 동안 300 내지 400와트(watt)의 출력을 이용하며, 상기 보이차 혼합액에서 고형분을 분리하여 제거한 후 10 내지 15℃의 온도에서 3 내지 7시간 동안 보관하여 숙성하는 과정을 거쳐 제조되고,상기 어성초 추출액은,어성초를 준비한 후 세척하고, 상기 세척된 어성초를 입경이 500 내지 2500㎛의 범위가 되도록 분쇄하며, 상기 분쇄된 어성초를 용매와 혼합하여 혼합액을 제조한 후, 초음파 추출기에 투입하여 20 내지 25℃의 온도 및 0.1 내지 0.5kgf/cm2의 압력하에서 상기 혼합액에 초음파를 가함으로써 어성초 추출 혼합액을 제조하되, 상기 용매는 상기 분쇄된 어성초 100 중량부에 대해 1000 내지 2000 중량부의 중량비율로 혼합되고, 상기 용매로는 물 또는 탄소수 1 내지 4(C1 내지 C4)의 알코올 중에서 선택된 어느 하나 이상의 용매가 사용되며, 상기 혼합액에 가해지는 초음파는 30 내지 50KHz의 진동주파수에서 30 내지 60분 동안 100 내지 200와트(watt)의 출력을 이용하고, 상기 어성초 추출 혼합액에서 고형물을 제거한 후 10 내지 20℃의 온도에서 1 내지 3시간 동안 숙성하는 과정을 거쳐 제조된 것을 특징으로 하는 젖소 유두 보호제., Ltext: 농업, prediction: 임업
900/1059 Row 900: application_number: 2020190002748, combined_string: invention_title: 축사용 문틀 잠금장치 abstract: 본 고안은 가축용 문틀 잠금장치에 관한 것으로, 걸림쇠가 형성되고 양방향으로 개폐되는 축사문의 개폐를 단속하도록 문틀에 설치된 축사용 문틀 잠금장치에 있어서, 상기 문틀에 설치된 몸체; 상기 몸체의 양측에 각각 기 설정된 각도 및 서로 마주보는 방향으로 회동 가능하게 결합된 단속판; 및 상기 단속판 사이에 서로가 연결되도록 결합된 탄성체;를 포함하고, 상기 축사문 폐쇄 시 상기 걸림쇠의 삽입에 의해 상기 걸림쇠와 인접하는 단속판이 밀려 회동되면서 개방되고 상기 걸림쇠 삽입 후 다시 탄성 및 무게 중심에 의해 회동되며 폐쇄되어 상기 축사문을 단속시키며, 상기 단속판은 개방되도록 회동 시, 상기 몸체의 양측에 각각 형성된 스토퍼에 의해 상기 걸림쇠의 직경과 동일한 높이까지만 개방되도록 회동되는 것을 특징으로 한다. 이러한 구성으로, 걸림쇠가 삽입될 때 단속판이 서로 마주하는 방향으로만 회동되도록 형성함으로써, 축사문이 회동됨에 따라 걸림쇠가 자연스레 단속판을 밀치며 삽입 고정되어 폐쇄되거나, 일방향의 단속판을 상방으로 회동시킨 상태에서 걸림쇠를 일방향으로 당김에 따라 축사문의 단속 해제에 의해 개방되도록 하여, 가축에 의해 임의적으로 축사문이 개방되는 것을 방지할 수 있는 효과를 얻을 수 있다. claims: 걸림쇠가 형성되고 양방향으로 개폐되는 축사문의 개폐를 단속하도록 문틀에 설치된 축사용 문틀 잠금장치에 있어서,상기 문틀에 설치된 몸체;상기 몸체의 양측에 각각 기 설정된 각도 및 서로 마주보는 방향으로 회동 가능하게 결합된 단속판; 및상기 단속판 사이에 서로가 연결되도록 결합된 탄성체;를 포함하고,상기 축사문 폐쇄 시 상기 걸림쇠의 삽입에 의해 상기 걸림쇠와 인접하는 단속판이 밀려 회동되면서 개방되고 상기 걸림쇠 삽입 후 다시 탄성 및 무게 중심에 의해 회동되며 폐쇄되어 상기 축사문을 단속시키며,상기 단속판은 개방되도록 회동 시, 상기 몸체의 양측에 각각 형성된 스토퍼에 의해 상기 걸림쇠의 직경과 동일한 높이까지만 개방되도록 회동되고,상기 몸체의 하방에는 상기 단속판이 폐쇄되도록 회동 시 밀착되는 하부 프레임이 형성되고,상기 하부 프레임의 상면에는 상기 단속판이 밀착된 상태에서 각 외측면과 밀착되는 끼임방지턱이 형성되며,상기 하부 프레임은,상면으로부터 상기 단속판의 밀착여부 또는 상기 걸림쇠의 접촉여부를 감지하는 근접센서가 구비되고,상기 근접센서로부터 전달받은 감지값에 따라 단속 여부를 알리는 알림장치가 구비되며,상기 하부 프레임의 일측면에 제1 홀이 형성되고, 상면에는 상기 제1 홀과 직교되도록 연통되는 제2 홀이 형성되며, 상기 제1 홀에는 고정핀이 결합되고 상기 고정핀의 일단에는 상기 제2 홀과 연통되는 부분에 제1 베벨기어가 형성되며 타단이 외부로 돌출되고, 상기 제2 홀에는 고정부재가 결합되며 상기 고정부재의 일단에는 상기 제1 베벨기어와 맞물리는 제2 베벨기어가 형성되고 타단이 외부로 돌출되고 외부로 돌출된 부분에 수나사산이 형성되며,상기 단속판의 하단에는 상기 제2 홀과 마주보는 위치에 이동홈이 형성되고, 상기 이동홈에는 이동부재가 이동 가능하게 결합되며, 상기 이동홈의 내측에는 상기 이동부재와 연결된 스프링이 구비되고, 상기 이동부재의 단부에는 상기 수나사산과 나사 결합되는 암나사산이 형성된 것을 특징으로 하는 축사용 문틀 잠금장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

901/1059 Row 901: application_number: 1020190076982, combined_string: invention_title: 가축의 사양관리 시스템 abstract: 가축의 사양관리 시스템은 가축의 귀에 부착되며, 가축의 활동 및 신체 정보를 센싱하고, 가축의 사양 정보를 표시하는 태그부, 상기 태그부에서 센싱한 데이터를 이용하여 가축의 사양 정보를 분석하는 축사 서버, 상기 태그부와 상기 축사 서버 간의 네트워크 연결을 중계하는 통신 중계부, 상기 축사 서버를 제어하고, 상기 축사 서버에서 분석한 가축의 사양 정보를 표시하는 사용자 단말기 및 상기 축사 서버에서 분석한 데이터를 저장하고 빅데이터화하여 가축의 사양 정보를 분석하는 메인 서버를 포함한다. claims: 가축의 귀에 부착되며, 가축의 활동 및 신체 정보를 센싱하고, 가축의 사양 정보를 표시하는 태그부;상기 태그부에서 센싱한 데이터를 이용하여 가축의 사양 정보를 분석하는 축사 서버;상기 태그부와 상기 축사 서버 간의 네트워크 연결을 중계하는 통신 중계부; 상기 축사 서버를 제어하고, 상기 축사 서버에서 분석한 가축의 사양 정보를 표시하는 사용자 단말기; 및상기 축사 서버에서 분석한 데이터를 저장하고 빅데이터화하여 가축의 사양 정보를 분석하는 메인 서버를 포함하는 가축의 사양관리 시스템., Ltext: 농업, prediction: 임업
902/1059 Row 902: application_number: 1020190075107, combined_string: invention_title: 부식케이스 교체 용이한 축사용 부식방지 공기 조화장치 abstract: 본 발명은 부식케이스 교체 용이한 축사용 부식방지 공기 조화장치에 관한 것으로서, 보다 상세하게는 축사 내부 또는 외부에 설치되어, 축사 내부로 온풍 또는 냉풍을 제공할 수 있도록 하는 공기 조화장치에 관한 것이되, 이러한 공기 조화장치는 전체가 다수개의 케이스가 상호간 적층되며 조립 및 분해가 가능한 구조를 가지도로 함으로써, 부식방지 및 부식이 발생되는 케이스나 구성품만을 교체수리할 수 있어, 부식이 전이되는 것을 방지하여 유지보수가 용이토록 하며, 설치시에도 분리운반 후, 해당 설치공간에서 조립하여 설치할 수 있어, 설치시공조립도 용이한 구조를 가지는 부식케이스 교체 용이한 축사용 부식방지 공기 조화장치에 관한 것이다. claims: 축사 내부 또는 외부에 설치되어, 축사 내부로 냉/온풍을 제공하기 위한 공기 조화장치로써, 외기를 가열 또는 냉각시키는 열교환부(30)와, 외기의 습도를 사전설정습도로 유지시키는 가습부(40)가 설치되어, 외기를 상부로 이동시키는 외기 처리부(10);상기 외기 처리부(10)의 공기를 필터링하여 축사 내부에 제공하기 위해, 이송팬(60) 및 필터부재(70)가 설치되는 공급부(20);로 이루어지되,상기 외기 처리부(10)와 공급부(20) 각각은내부의 공간을 상, 하측으로 구획할 수 있도록, 상/하로 개별분리가 가능한 제 1, 2케이스(11, 12) 및 제 3, 4케이스(21, 22)로 각각 이루어지도록 하여, 공기 조화장치(100)를 축사에 설치시, 케이스 다수를 개별분리하여 운반 후, 축사에서 설치될 수 있도록 함으로써, 설치시공이 용이토록 하고,축사에서 발생되는 유해가스에 의해 내부 구성품 또는 케이스가 부식되는 경우, 해당 구성품 또는 제 1, 2케이스(11, 12) 중 부식되는 케이스만을 개별분리교체하여, 연결된 다른 케이스와 구성품에 부식이 전이되지 않도록 설치되며,상기 제 1, 2, 3, 4케이스(11, 12, 21, 22)는 상호간 접촉부분에 부식방지부재(80)가 설치되어, 상호간 부식이 전이되지 않도록 하고,상기 제 1, 2, 3, 4케이스(11, 12, 21, 22)가 적층되어 구성되는 공기 조화장치(100)는, 외주면 모서리 부분에 적층길이방향을 향해 모서리를 감싸면서, 제 1, 2, 3, 4케이스(11, 12, 21, 22) 상호간이, 동일수직선상에 위치되며 부동될 수 있도록 하는 다수의 지지 고정체(90); 를 더 구비하며,상기 다수의 지지 고정체(90)는상기 공기 조화장치(100)와 접촉되는 내측면에 부식방지부재(80)가 설치되어, 공기 조화장치(100)와 지지 고정체(90) 상호간의 부식 전이를 방지하고, 다수의 지지 고정체(90)를 통해 제 1, 2, 3, 4케이스(11, 12, 21, 22) 상호간의 부식 전이가 방지되도록 하고,상기 지지 고정체(90)는 제 3케이스(21)의 상단모서리, 제 2케이스(12)의 하단모서리, 제 3, 4케이스(21, 22)의 접촉부분 모서리, 제 4, 1케이스(22, 11)의 접촉부분 모서리, 제 1, 2케이스(11, 12)의 접촉부분 모서리마다 연장되는 연장편(91)을 형성하여, 이러한 연장편(91)에 고정부재(B)를 통해 제 1, 2, 3, 4케이스(11, 12, 21, 22)에 지지 고정체(90)가 일체로 고정 및 각각의 케이스마다 개별분리가 가능한 구조를 가지도록 하며,상기 외기 처리부(10)는 외기가 유입되는 공기 유입구(13)에 열교환부(30) 부식 방지를 위한, 유해가스 제거용 활성탄 재질의 가스필터(50)가 설치되는 것을 특징으로 하는 부식케이스 교체 용이한 축사용 부식방지 공기 조화장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

903/1059 Row 903: application_number: 1020190075108, combined_string: invention_title: 부식케이스 교체가 용이하며 희생양극을 이용한 축사용 부식방지 공기 조화장치 abstract: 본 발명은 부식케이스 교체가 용이하며 희생양극을 이용한 축사용 부식방지 공기 조화장치에 관한 것으로서, 보다 상세하게는 축사 내부 또는 외부에 설치되어, 축사 내부로 온풍 또는 냉풍을 제공할 수 있도록 하는 공기 조화장치에 관한 것이되, 희생양극부를 내부의 구성부품 및 케이스에 연결시켜 부식이 발생되지 않도록 함과 동시에, 이러한 공기 조화장치는 전체가 다수개의 케이스가 상호간 적층되며 조립 및 분해가 가능한 구조를 가지도로 함으로써, 부식방지 및 부식이 발생되는 케이스나 구성품만을 교체수리할 수 있어, 부식이 전이되는 것을 방지하여 유지보수가 용이토록 하며, 설치시에도 분리운반 후, 해당 설치공간에서 조립하여 설치할 수 있어, 설치시공조립도 용이한 구조를 가지는 부식케이스 교체가 용이하며 희생양극을 이용한 축사용 부식방지 공기 조화장치에 관한 것이다. claims: 축사 내부 또는 외부에 설치되어, 축사 내부로 냉/온풍을 제공하기 위한 공기 조화장치로써, 외기를 가열 또는 냉각시키는 열교환부(30)와, 외기의 습도를 사전설정습도로 유지시키는 가습부(40)가 설치되어, 외기를 상부로 이동시키는 외기 처리부(10);상기 외기 처리부(10)의 공기를 필터링하여 축사 내부에 제공하기 위해, 이송팬(60) 및 필터부재(70)가 설치되는 공급부(20);로 이루어지되,상기 외기 처리부(10)와 공급부(20) 각각은내부의 공간을 상, 하측으로 구획할 수 있도록, 상/하로 개별분리가 가능한 제 1, 2케이스(11, 12) 및 제 3, 4케이스(21, 22)로 각각 이루어지도록 하여, 공기 조화장치(100)를 축사에 설치시, 케이스 다수를 개별분리하여 운반 후, 축사에서 설치될 수 있도록 함으로써, 설치시공이 용이토록 하고,축사에서 발생되는 유해가스에 의해 내부 구성품 또는 케이스가 부식되는 경우, 해당 구성품 또는 제 1, 2케이스(11, 12) 중 부식되는 케이스만을 개별분리교체하여, 연결된 다른 케이스와 구성품에 부식이 전이되지 않도록 하며,상기 외기 처리부(10), 공급부(20), 제 1, 2, 3, 4케이스(11, 12, 21, 22)에 각각 설치되어 부식을 방지하면서, 인접한 구성부품 또는 케이스에 부식이 전이되지 않도록 설치되는 희생양극부(110); 가 설치되며,상기 제 1, 2, 3, 4케이스(11, 12, 21, 22)는상호간 접촉부분에 부식방지부재(80)가 설치되어, 상호간 부식이 전이되지 않도록 하고,상기 제 1, 2, 3, 4케이스(11, 12, 21, 22)가 적층되어 구성되는 공기 조화장치(100)는, 외주면 모서리 부분에 적층길이방향을 향해 모서리를 감싸면서, 제 1, 2, 3, 4케이스(11, 12, 21, 22) 상호간이, 동일수직선상에 위치되며 부동될 수 있도록 하는 다수의 지지 고정체(90); 를 더 구비하며,상기 다수의 지지 고정체(90)는상기 공기 조화장치(100)와 접촉되는 내측면에 부식방지부재(80)가 설치되어, 공기 조화장치(100)와 지지 고정체(90) 상호간의 부식 전이를 방지하고, 다수의 지지 고정체(90)를 통해 제 1, 2, 3, 4케이스(11, 12, 21, 22) 상호간의 부식 전이가 방지되도록 하며,상기 지지 고정체(90)는 3케이스(21)의 상단모서리, 최하단인 제 2케이스(12)의 하단모서리, 제 3, 4케이스(21, 22)의 접촉부분 모서리, 제 4, 1케이스(22, 11)의 접촉부분 모서리, 제 1, 2케이스(11, 12)의 접촉부분 모서리마다 연장되는 연장편(91)을 형성하여, 연장편(91)에 고정부재(B)를 통해 제 1, 2, 3, 4케이스(11, 12, 21, 22)에 지지 고정체(90)가 일체로 고정 및 각각의 케이스마다 개별분리가 가능한 구조를 가지도록 하며,상기 외기 처리부(10)는외기가 유입되는 공기 유입구(13)에 열교환부(30) 부식 방지를 위한, 유해가스 제거용 활성탄 재질의 가스필터(50)가 설치되며,상기 희생양극부(110)는상기 외기 처리부(10), 공급부(20), 제 1, 2, 3, 4케이스(11, 12, 21, 22) 각각에 직접연결되거나, 또는 전선을 이용하여 연결됨으로써, 각각에 발생되는 부식전류를 희생양극부(110)로 전달하여 부식이 희생양극부(110)에서 발생되도록 하는 것을 특징으로 하는 부식케이스 교체가 용이하며 희생양극을 이용한 축사용 부식방지 공기 조화장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

904/1059 Row 904: application_number: 1020190069196, combined_string: invention_title: ICT 융복합 스마트 축사관리 제어방법 abstract: 외부로부터 공급되는 물을 이용하여 투약펌프로부터 공급되는 약물을 희석하는 희석부를 포함하여 희석된 약물을 공급하는 자동투약장치와, 외부로부터 공급되는 물이 저장되는 물탱크와, 상기 물탱크에 저장된 물에 압력을 가하여 공급하는 가압펌프와, 상기 가압펌프로부터 공급되는 물이 통과하면서 여과되는 여과장치와, 상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부와, 상기 혼압부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프와, 상기 물탱크로부터 공급되는 제1 물의 양을 측정하는 유량계와, 상기 축사 내 및 상기 축사 외의 습도 및 온도와 상기 축사 내의 공기의 질을 측정하는 센싱부와, 상기 축사 내의 온도, 습도 및 환기를 제어하는 축사환경 조절부와, 상기 자동투약장치의 희석 농도를 제어하는 제어부를 포함하는 안개분무 시스템을 제어하는 방법으로서,본 발명에 따른 ICT 융복합 스마트 축사관리 시스템의 제어방법은 상기 센싱부로부터 축사 내외의 온도 및 습도와 상기 축사 내의 공기의 질 데이터를 전달받는 데이터 수집 단계; 상기 전달된 데이터로부터 목표 습도에 부합하는 상기 혼압액의 농도를 산출하는 농도 산출 단계; 상기 산출된 혼압액의 농도에 따라 상기 유량계로부터 공급되는 물의 양을 전달받아 상기 희석부에서의 희석액 농도를 산출하는 희석액 농도 산출단계; 및 상기 산출된 희석액 농도 산출단계에 따라 희석부가 희석하는 제1 희석액 제조단계;를 포함한다. claims: 외부로부터 공급되는 물을 이용하여 투약펌프로부터 공급되는 약물을 희석하는 희석부를 포함하여 희석된 약물을 공급하는 자동투약장치와, 외부로부터 공급되는 물이 저장되는 물탱크와, 상기 물탱크에 저장된 물에 압력을 가하여 공급하는 가압펌프와, 상기 가압펌프로부터 공급되는 물이 통과하면서 여과되는 여과장치와, 상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 복수의 희석부와, 상기 희석부로부터 배출되는 상기 물과 상기 약물의 혼합액에 상기 여과장치로부터 공급되는 제1물을 혼합하는 혼합부와, 상기 혼합부에의하여 혼합된 약물을 일정한 압력을 가하여 축사 내로 공급하는 고압펌프와, 상기 물탱크로부터 공급되는 제1 물의 양을 측정하는 유량계와, 상기 축사 내 및 상기 축사 외의 습도 및 온도와 상기 축사 내의 공기의 질을 측정하는 센싱부와, 상기 축사 내의 온도, 습도 및 환기를 제어하는 축사환경 조절부와, 상기 자동투약장치의 희석 농도를 제어하는 제어부를 포함하는 ICT 융복합 스마트 축사관리 제어방법으로서,상기 센싱부로부터 축사 내외의 온도 및 습도와 상기 축사 내의 공기의 질 데이터를 전달받는 데이터 수집 단계;상기 전달된 데이터로부터 목표 습도에 부합하는 상기 혼합액의 농도를 산출하는 농도 산출 단계;상기 산출된 혼합액의 농도에 따라 상기 유량계로부터 공급되는 물의 양을 전달받아 상기 복수의 희석부 중 어느 한 희석부에서의 제조할 희석액 농도를 산출하는 희석액 농도 산출단계; 및상기 산출된 희석액 농도 산출단계에 따라 상기 어느 한 희석부가 희석하는 제1 희석액 제조단계;를 포함하고,상기 제1 희석액을 물과 혼합하여 상기 축사 내로 공급하는 혼합 및 공급단계;를 더 포함하며,상기 혼합 및 공급단계를 통하여 제1 희석액을 소진하면서 혼합액을 공급하는 과정에서 상기 산출된 혼합액의 농도에 따라 상기 복수의 희석부 중 타 희석부가 별도의 희석액을 제조하는 제2 희석액 제조단계;를 더 포함하고,상기 혼합 및 공급단계에서는 제1 희석액의 소진 후 상기 제2 희석액을 공급하여 혼합액을 형성하며,상기 혼합 및 공급단계 이전에 상기 축사환경 조절부가 온도, 습도 및 공기의 질에 대한 목표 축사 환경지수와 상기 고압펌프로부터 공급되는 혼합액에 의한 축사 환경 변동지수를 고려하여 축사 내의 온도 제어, 습도 제어 및 환기 제어를 수행하는 사전 환경조정 단계;를 더 포함하는 ICT 융복합 스마트 축사관리 제어방법., Ltext: 농업, prediction: 임업
905/1059 Row 905: application_number: 1020190069197, combined_string: invention_title: 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템 abstract: 복수의 분무노즐을 이용하여 물과 약품이 혼합된 혼합액을 축사내로 분무하는 안개분무 시스템으로서, 본 발명에 따른 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템은 희석된 약물을 공급하는 자동투약장치; 외부로부터 공급되는 제1 물이 저장되는 물탱크; 상기 물탱크에 저장된 제1 물에 압력을 가하여 공급하는 가압펌프; 상기 가압펌프로부터 공급되는 제1 물이 통과하면서 여과되는 여과장치; 상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부; 상기 혼압부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프; 상기 고압펌프로부터 공급되는 혼압액을 상기 축사 내의 공간으로 이송하는 혼압액 이송배관; 상기 혼압액 이송배관에 구비되어 상기 혼압액을 분무하는 분무 노즐; 및 상기 축사 내에 수직방향으로 중공의 기둥 형상으로 형성되고, 하부에 제1 환기구가 형성되고, 상부에 제2 환기구가 형성되며, 상기 제1 환기구 및 상기 제2 환기구 사이의 공간부에는 팬부가 구비되는 에어순환기둥을 포함한다. claims: 복수의 분무노즐을 이용하여 물과 약품이 혼합된 혼합액을 축사내로 분무하는 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템으로서,희석된 약물을 공급하는 자동투약장치;외부로부터 공급되는 제1 물이 저장되는 물탱크;상기 물탱크에 저장된 제1 물에 압력을 가하여 공급하는 가압펌프;상기 가압펌프로부터 공급되는 제1 물이 통과하면서 여과되는 여과장치;상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부;상기 혼합부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프;상기 고압펌프로부터 공급되는 혼합액을 상기 축사 내의 공간으로 이송하는 혼합액 이송배관;상기 혼합액 이송배관에 구비되어 상기 혼합액을 분무하는 분무 노즐; 및상기 축사 내에 수직방향으로 중공의 기둥 형상으로 형성되고, 하부에 제1 환기구가 형성되고, 상부에 제2 환기구가 형성되며, 상기 제1 환기구 및 상기 제2 환기구 사이의 공간부에는 팬부가 구비되는 에어순환기둥을 포함하는 안개분무 시스템을 구비하고,상기 분무 노즐 중 상기 축사의 외벽 측에 구비되는 분무 노즐은 타 분무 노즐에 비하여 고압으로 혼합액을 분사하는 안개분무 시스템을 구비하며,상기 제2 환기구는 상기 축사의 벽체 상부에 구비되는 환기창의 높이에 비하여 같거나 높게 형성되는 안개분무 시스템을 구비하고,상기 축사의 지면 아래에는 외부 공기가 주입되는 에어공급관이 구비되고, 상기 에어공급관에는 복수의 에어 배출구가 형성되며,상기 에어 배출구는 상기 에어공급관의 저면에 형성되어 상기 축사 지면의 에어레이션을 수행하고,상기 환기창에는 환풍기가 구비되며,상기 자동투약장치는,약물이 저장되는 약물 탱크;상기 약물 탱크에 저장된 약물을 일정한 압력으로 공급하는 투약펌프; 및외부로부터 공급되는 제2 물을 이용하여 상기 투약펌프로부터 공급되는 약물을 희석하는 희석부;를 포함하고,상기 희석부는 적어도 둘 이상 구비되고, 상기 희석부 중 어느 한 희석부에 의하여 혼합부에 상기 물과 상기 약물의 희석액이 공급되는 경우 타 희석부에는 상기 제2 물을 이용하여 상기 약물의 희석 작업을 수행하는 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

906/1059 Row 906: application_number: 1020190069198, combined_string: invention_title: 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템 및 제어방법 abstract: 복수의 분무노즐을 이용하여 물과 약품이 혼합된 혼합액을 축사내로 분무하는 안개분무 시스템으로서, 본 발명에 따른 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템은 희석된 약물을 공급하는 자동투약장치; 외부로부터 공급되는 제1 물이 저장되는 물탱크; 상기 물탱크에 저장된 제1 물에 압력을 가하여 공급하는 가압펌프; 상기 가압펌프로부터 공급되는 제1 물이 통과하면서 여과되는 여과장치; 상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부; 상기 혼압부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프; 상기 고압펌프로부터 공급되는 혼압액을 상기 축사 내의 공간으로 이송하는 혼압액 이송배관; 상기 혼압액 이송배관에 구비되어 상기 혼압액을 분무하는 분무 노즐; 상기 축사 내 및 상기 축사 외의 습도 및 온도와 상기 축사 내의 공기의 질을 측정하는 센싱부; 상기 축사 내의 온도, 습도 및 환기를 제어하는 축사환경 조절부; 및 상기 센싱부로부터 데이터를 전달받아 상기 축사환경 조절부를 제어하여 축사환경을 개선하고 상기 자동투약장치의 희석 농도를 제어하여 혼합액을 공급제어하는 제어부를 포함한다. claims: 복수의 분무노즐을 이용하여 물과 약품이 혼합된 혼합액을 축사내로 분무하는 안개분무 시스템으로서,희석된 약물을 공급하는 자동투약장치;외부로부터 공급되는 제1 물이 저장되는 물탱크;상기 물탱크에 저장된 제1 물에 압력을 가하여 공급하는 가압펌프;상기 가압펌프로부터 공급되는 제1 물이 통과하면서 여과되는 여과장치;상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부;상기 혼합부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프;상기 고압펌프로부터 공급되는 혼합액을 상기 축사 내의 공간으로 이송하는 혼합액 이송배관;상기 혼합액 이송배관에 구비되어 상기 혼합액을 분무하는 분무 노즐;상기 축사 내 및 상기 축사 외의 습도 및 온도와 상기 축사 내의 공기의 질을 측정하는 센싱부;상기 축사 내의 온도, 습도 및 환기를 제어하는 축사환경 조절부; 및상기 센싱부로부터 데이터를 전달받아 상기 축사환경 조절부를 제어하여 축사환경을 개선하고 상기 자동투약장치의 희석 농도를 제어하여 혼합액을 공급제어하는 제어부를 포함하는 안개분무 시스템을 구비하고,상기 자동투약장치는,약물이 저장되는 약물 탱크;상기 약물 탱크에 저장된 약물을 일정한 압력으로 공급하는 투약펌프; 및외부로부터 공급되는 제2 물을 이용하여 상기 투약펌프로부터 공급되는 약물을 희석하는 희석부;를 포함하며,상기 희석부는 적어도 둘 이상 구비되고, 상기 희석부 중 어느 한 희석부에 의하여 혼합부에 상기 물과 상기 약물의 희석액이 공급되는 경우 타 희석부에는 상기 제2 물을 이용하여 상기 약물의 희석 작업을 수행하고,상기 축사환경 조절부는,상기 축사 내에 수직방향으로 중공의 기둥 형상으로 형성되고, 하부에 제1 환기구가 형성되고, 상부에 제2 환기구가 형성되며, 상기 제1 환기구 및 상기 제2 환기구 사이의 공간부에는 팬부가 구비되는 에어순환기둥; 및상기 축사의 바닥 상에 또는 상기 축사의 지면 아래에는 외부 공기가 주입되고, 저면에 상기 외부 공기를 배출하는 에어 배출구가 형성되는 에어공급관;을 포함하는 안개분무 시스템을 구비하며,상기 제어부는 상기 혼합액의 상기 축사 내 공급 이전에 온도, 습도 및 공기의 질에 대한 목표 축사 환경지수와 상기혼합액의 공급에 따른 축사 환경 변동지수를 고려하여 축사 내의 온도 제어, 습도 제어 및 환기 제어를 미리 수행하는 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

907/1059 Row 907: application_number: 1020190068640, combined_string: invention_title: 가축 사육용 축사 abstract: 본 발명은 축사 내부의 공간을 구획하여 돼지 등의 가축의 사육을 효율적으로 할 수 있도록 구현한 가축 사육용 축사에 관한 것으로, 바닥, 벽체 및 지붕으로 형성되는 축사; 상기 축사 내부의 공기를 환기시킬 수 있도록 상기 벽체를 따라 설치되는 환기 장치; 및 상기 축사의 외측에 설치되어 가축에게 공급할 사료를 저장해 두는 사료 저장 탱크를 포함한다. claims: 바닥, 벽체 및 지붕으로 형성되는 축사;상기 축사 내부의 공기를 환기시킬 수 있도록 상기 벽체를 따라 설치되는 환기 장치; 및상기 축사의 외측에 설치되어 가축에게 공급할 사료를 저장해 두는 사료 저장 탱크를 포함하고,상기 축사는, 가축들이 생활하기 위한 공간을 다수 개의 공간으로 구획시킬 수 있도록 내부 바닥을 따라 설치되는 펜스; 및 상기 펜스에 의해 형성된 일 공간으로부터 다른 공간으로 가축이 이동할 수 있도록 상기 펜스와 다른 펜스 사이의 공간에 개폐 가능하도록 설치되는 도어를 포함하며, 상기 도어는, 상기 펜스와 다른 펜스에 각각 상하 길이 방향으로 연장 설치되며, ㄷ형태로 형성되는 슬라이딩 홈을 형성하는 슬라이딩 레일; 및 일측 및 다른 일측이 상기 슬라이딩 홈에 삽입되며, 상기 슬라이딩 홈을 따라 상하 방향으로 승강 또는 하강하면서 상기 펜스와 다른 펜스 사이의 공간을 개폐시키는 슬라이딩 패널을 포함하며,상기 슬라이딩 패널은, 승강된 후 하강되지 아니하도록 상기 슬라이딩 레일의 상부를 체결하기 위한 패널 체결부가 전면 또는 후면의 하부 양측에 구비되며,상기 패널 체결부는, 상기 슬라이딩 패널의 전면 또는 후면의 하부 일측 또는 다른 일측에 형성되는 수용홈; 및 사각 기둥 형태로 형성되며, 하부가 상기 수용홈의 하부에 회동 가능하도록 연결 설치되는 체결 바아를 포함하며,상기 수용홈은, 하측면이 전단으로 갈수록 하측 방향으로 경사지도록 경사면을 형성하며,상기 경사면 및 상기 경사면과 대향하는 상기 체결 바아의 전면 하부에는, 서로 반대 극성을 가지는 자석이 각각 설치되며,상기 체결 바아는, 회동된 후 상기 슬라이딩 레일의 상부가 삽입될 수 있도록 후단으로 갈수록 하측 방향으로 형성되는 체결홈이 전면에 형성되며, 상기 도어는, 상기 슬라이딩 홈의 하측에 설치되며, 상기 슬라이딩 홈을 따라 하강하는 상기 슬라이딩 패널의 일측 또는 다른 일측을 탄성력을 이용하여 지지하는 탄성 지지대를 더 포함하며, 상기 탄성 지지대는, 평판 형태로 형성되어 상기 슬라이딩 패널의 일측 또는 다른 일측을 지지하는 상판; 상기 상판의 하측에 이격되어 설치되며, 내부 공간을 형성하는 케이스; 및 상기 케이스의 내부 공간에 설치되며, 상부가 상기 케이스의 상측으로 노출되어 탄성력을 이용하여 상기 상판을 지지하는 상판 지지부를 포함하며,상기 상판 지지부는, 상기 상판의 중심을 지지하며, 상기 상판이 하강함에 따라 내부 공간에 담긴 충전액을 공급하는 제1 지지부; 및 상기 상판의 각 모서리의 하측에 각각 설치되며, 상하 방향으로 이동되면서 상기 상판의 모서리를 탄성력을 이용하여 지지하며, 상기 상판이 하강함에 따라 상기 제1 지지부로부터 공급되는 충전액에 의해 상하 방향의 이동이 제동되는 제2 지지부; 상기 제1 지지부는, 상기 상판의 하측면의 중심에 설치되며, 구형의 내부 공간을 형성하는 제1 회동 체결부; 상기 제1 회동 체결부의 내부 공간의 형태에 대응하는 구형으로 형성되며, 상기 제1 회동 체결부의 내부 공간에 회전 가능하도록 설치되는 제1 연결 볼; 상기 제1 연결 볼의 하부로부터 하측 방향으로 연장 형성되어 상기 제1 연결 볼을 지지하는 제1 지지 바아; 원기둥 형태로 형성되어 상기 케이스의 내부 공간에 설치되며, 밀폐된 내부 공간에 충전액이 수용되며, 상기 제1 지지 바아의 하부가 내부 공간으로 삽입되며, 상기 상판이 하강할 경우 상기 제1 지지 바아의 하부가 내부 공간의 상측으로부터 하강함에 따라 충전액이 압착되어 상기 제2 지지부로 공급되는 충전액 탱크; 및 상기 충전액 탱크의 하부로부터 상기 제2 지지부까지 연장 형성되어 충전액이 흐르는 통로를 형성하는 연결관을 포함하며, 상기 제2 지지부는, 상기 상판의 하측면의 모서리에 설치되며, 구형의 내부 공간을 형성하는 제2 회동 체결부; 상기 제2 회동 체결부의 내부 공간의 형태에 대응하는 구형으로 형성되며, 상기 제2 회동 체결부의 내부 공간에 회전 가능하도록 설치되는 제2 연결 볼; 상기 제2 연결 볼의 하부로부터 하측 방향으로 연장 형성되어 상기 제2 연결 볼을 지지하는 제2 지지 바아; 상기 제2 지지 바아의 하측에 설치되어 탄성력을 이용하여 상기 제2 지지 바아를 지지하는 탄성 지지부; 및 상하 방향으로 관통홀을 형성하는 원형의 튜브 형태로 형성되어 상기 관통홀에 상기 제2 지지 바아가 삽입되며, 상기 상판이 하강할 경우 상기 연결관을 통해 충전액이 내부 공간으로 공급되어 팽창함에 따라 상기 관통홀의 크기가 줄어들어 상기 제2 지지 바아가 움직이지 못하도록 체결하는 승하강 조절부를 포함하며,상기 승하강 조절부는, 충전액이 내부 공간으로 공급됨에 따라 상기 관통홀이 위치하는 내측 방향으로 팽창될 수 있도록 외측벽이 경질의 재질로 형성되고, 상기 제2 지지 바아와 대향하는 내측이 팽창 또는 수축이 가능한 재질로 형성되는, 가축 사육용 축사., Ltext: 농업, prediction: 임업
908/1059 Row 908: application_number: 2020190001912, combined_string: invention_title: 축사에서 이용하는 가축 결박장치 abstract: 본 고안은 축사에서 이용하는 가축 결박장치에 관한 것으로서, 상세하게는 축사내의 벽과 축사의 출입문에 해당하는 여닫이문 사이에 가축을 이동시킨 다음 권취기를 이용하여 여닫이문을 축사내의 벽으로 이동시켜 가축을 압박하듯이 결박하는 기술에 관한 것이다.구성은 다음과 같다.축사의 출입문에 해당하는 여닫이문(100)을 걸 수 있는 여닫이문고리(10)와;상기 여닫이문고리(10)의 일측에 로프(11) 일측이 연결되고 로프(11) 타측은 권취기(20)와 연결되며, 상기 권취기(20)의 감속모터(21)에 권취된 와이어(30)와, 상기 와이어(30) 끝단에 연결되어 축사의 벽에 걸 수 있는 벽면고리(40)와, 상기 와이어(30)에 가축이 상기 와이어(30)로부터 간섭을 받지 않도록 상기 와이어에 끼워진 긴 배관(50)과, 감속모터(21)에 전력을 출력하는 전선이 권선기(60)에 포함한 구성이다. claims: 축사의 출입문에 해당하는 여닫이문(100)을 걸 수 있는 여닫이문고리(10)와;상기 여닫이문고리(10)의 일측에 로프(11) 일측이 연결되고 로프(11) 타측은 권취기(20)와 연결되며, 상기 권취기(20)의 감속모터(21)에 권취된 와이어(30)와, 상기 와이어(30)에 끝단에 연결되어 축사의 벽에 걸 수 있는 벽면고리(40)와, 상기 와이어(30)에 가축이 상기 와이어(30)로부터 간섭을 받지 않도록 상기 와이어에 끼워진 긴 배관(50)과, 감속모터(21)에 전력을 출력하는 전선이 권선기(60)를 포함한 구성에 있어서,상기 긴 배관(50)은 복수로 분할(52) 하여 가축의 크기에 따라 수량을 조절하도록 구성하고,상기 로프(11)는 탄성부재(12)를 갖도록 하여 가축이 여닫이문(100)과 축사내의 벽면(200) 사이에서 압박을 받더라도 상기 탄성력(12)이 있어 움직일 수 있도록 구성하는 것을 특징으로 하는 축사에서 이용하는 가축 결박장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

909/1059 Row 909: application_number: 2020190001887, combined_string: invention_title: 축사의 국소적 부압수단에 의한 환기 시스템 abstract: 본 고안은 축사(畜舍)의 국소(局所)적 부압(負壓)수단에 의한 환기시스템에 관한 것으로 대형의 급기팬과 배기팬이 좌우 양측에 마주보게 설치되어 환기하게 된 축사에 있어서,측사에 국소적으로 흡기(吸氣)에 의해 부압이 조성되게 하는 흡기관과; 상기 흡기관의 유입구에 접속되어 상기 흡기관을 통하여 흡입되는 공기와 이물질을 분리하는 사이크론(Cycrone)과; 상기 사이크론의 유출구에 접속되어 상기 흡기관 주위에 형성되는 부압을 유지하여 신선한 공기영역이 부압 측으로 확장되게 하는 에어펌프의; 결합으로 구성된 것이다.본 발명에 의하면, 여러 개의 좁은 칸막이로 된 돼지우리, 또는 병아리나 닭이 사육되는 축사의 바닥면, 즉, 악취공기를 제거할 장소에 상기 흡기관을 배치하고 에어펌프를 가동하면 흡기관의 흡기공으로 흡입된 이물질과 악취공기는 사이크론에 의해 분리되어 공기는 외부로 배출되고 상기 흡기관의 주위에는 부압(reducing pressure)이 형성되면서 대형 급기팬에 의해 축사내부에 형성되는 신선한 공기영역이 부압 측으로 확장되어 신선한 공기영역에서 가축들이 건강하게 사육될 수 있다. claims: 측사에 국소적으로 흡기(吸氣)에 의해 부압이 조성되게 하는 여러 개의 흡기공이 천공된 흡기관과; 상기 흡기관이 유입구에 접속되어 상기 흡기관을 통하여 흡입되는 공기와 이물질을 분리하는 사이크론(Cycrone)과; 상기 사이크론의 유출구에 접속되어 상기 흡기관 주위에 형성되는 부압을 유지하여 신선한 공기영역이 부압 측으로 확장되게 하는 모터로 구동되는 에어펌프를; 포함하여 구성된 것을 특징으로 하는 축사의 국소적 부압수단에 의한 환기시스템., Ltext: 농업, prediction: 임업
910/1059 Row 910: application_number: 1020190050687, combined_string: invention_title: 가축의 반추위를 모니터링하는 장치 및 방법 abstract: 가축의 반추위에 삽입된 센서 장치로부터 움직임 데이터를 수집하여 가축의 활동을 분석하고, 활동 정보를 이용하여 가축의 건강 및 질병 관리 정보를 모니터링하는 장치 및 방법에 관한 것이다. 본 발명에 따라 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 장치는, 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하는 데이터 센싱부; 수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 활동 분석부; 및 분석된 활동 정보를 저장하고, 활동 정보가 분석되지 않는 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 모니터링부를 포함한다. claims: 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 장치에 있어서,상기 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하는 데이터 센싱부;수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 활동 분석부; 및분석된 활동 정보를 저장하고, 상기 활동 정보의 분석에 따른 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 모니터링부를 포함하는 것을 특징으로 하는 장치.장치가 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 방법에 있어서,상기 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하여 센싱하는 단계;수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 단계; 및분석된 활동 정보를 저장하고, 상기 활동 정보의 분석에 따른 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 단계를 포함하는 것을 특징으로 하는 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

911/1059 Row 911: application_number: 1020190043757, combined_string: invention_title: 축사의 배출가스를 이용한 스마트팜 연동형 축산폐수 처리 시스템 abstract: 본 발명은 축사(10)와 스마트팜(20)을 포함하는 스마트팜 연동형 축산폐수 처리 시스템에 있어서, 상기 축사(10)에서 배출되는 배출가스가 포집되어 질소와 탄소를 포함하는 처리가스로 처리되는 배출가스 처리부(30); 상기 처리가스를 공급받는 스마트팜(20); 및 상기 배출가스 처리부(30)와 상기 스마트팜(20)의 연결라인에서 분기된 이송라인에 의해 처리가스를 각각 공급받으며, 상기 축사(10)의 축산폐수를 처리하는 액비 처리부(300) 및 퇴비 처리부(400)를 포함하는, 스마트팜 연동형 축산폐수 처리 시스템을 제공한다. claims: 축사(10)와 스마트팜(20)을 포함하는 스마트팜 연동형 축산폐수 처리 시스템에 있어서,상기 축사(10)에서 배출되는 배출가스가 포집되어 질소와 탄소를 포함하는 처리가스로 처리되는 배출가스 처리부(30);상기 처리가스를 공급받는 스마트팜(20); 및 상기 배출가스 처리부(30)와 상기 스마트팜(20)의 연결라인에서 분기된 이송라인에 의해 처리가스를 각각 공급받으며, 상기 축사(10)의 축산폐수를 처리하는 액비 처리부(300) 및 퇴비 처리부(400)를 포함하고,상기 배출가스 처리부(30)와 상기 스마트팜(20)의 연결라인의 분기부에 위치하는 밸브를 더 포함하고,야간 시, 상기 밸브를 제어하여 상기 스마트팜(20)으로의 이송라인을 차단한 채, 상기 배출가스 처리부(30)의 처리가스를 상기 액비 처리부(300) 및 상기 퇴비 처리부(400) 중 어느 하나 이상에 제공하도록 제어하는, 스마트팜 연동형 축산폐수 처리 시스템., Ltext: 농업, prediction: 임업
912/1059 Row 912: application_number: 1020190039165, combined_string: invention_title: 소 관리시스템 및 관리방법 abstract: 본 발명은 소 관리시스템 및 관리방법에 관한 것으로, 더욱 구체적으로 설명하면, 한우, 육우, 젖소와 같은 소(이하 '소'라 칭함)의 체온과 맥박을 실시간으로 모니터링하여 측정된 수치를 무선전송하고 무선전송된 수치가 관리 서버에 수신 및 저장되고 수신된 정보가 분석되고 분석된 데이터가 사용자의 휴대용 단말기에 전송되어 사용자가 소의 현재의 질병, 임신, 배고픔, 갈증과 같은 소의 현재상태를 실시간으로 알 수 있게 되어 구제역과 같은 긴급한 질병이나 임신상황과 같은 소의 상황을 실시간으로 파악하여 필요한 조치를 취할 수가 있게 되어 소들을 보다 질병이나 배고픔과 같은 욕구를 해결하여 육질이나 우유의 질을 개선하는 것이 가능하게 되는 소 관리시스템 및 관리방법에 관한 것이다. claims: 소 관리시스템(A)에 있어서,상기 소 관리시스템(A)은, 축사(1)내에서 다수가 사육되고 있는 각각의 소(11)의 목에 걸려있는 배터리, 온도센서, 맥박센서, 무선송신부, 제어칩을 포함하는 측정단말기(12)와; 상기 측정단말기(12)에 의하여 송신된 데이터를 포집하는 무선 모뎀 라우터(2)와; 상기 축사(1)에서 이격된 위치의 사무실(3)에 설치되며 상기 무선 모뎀 라우터(2)와 랜으로 연결되어 상기 무선 모뎀 라우터에 의하여 송신된 데이터를 수신하고 수신된 데이터를 분석 및 가공하는 관리서버(31)와; 상기 관리서버(31)에서 송신된 분석 및 가공된 데이터를 수신하는 사용자의 휴대폰, 노트북 또는 PDA의 이동형 단말기(4);를 포함하는 것을 특징으로 하는 소 관리시스템소 관리방법에 있어서,상기 소 관리방법은, 축사내의 각각의 소의 목에 걸려 있는 측정단말기에 의하여 소의 온도와 맥박에 대한 정보를 실시간으로 감지하고 무선 모뎀 라우터로 송신시키는 단계와, 상기 무선 모뎀 라우터로 수신된 정보를 관리서버로 송신시키는 단계와, 송신된 정보를 관리서버에서 수신하고 수신된 각각의 소의 온도와 맥박에 대한 정보를 실시간으로 분석 및 가공하고 가공된 정보를 관리서버의 통신부를 통하여 사용자의 휴대 단말기, 노트북 또는 PDA송신하는 단계와, 상기 관리서버로부터 송신된 데이터를 수신하여 이상 상황의 이벤트가 발생되면 실시간으로 조치를 취하는 단계를 포함하는 것을 특징으로 하는 소 관리방법, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

913/1059 Row 913: application_number: 2020190001365, combined_string: invention_title: 축사용 급수장치 abstract: 축사용 급수장치를 개시한다.이러한 축사용 급수장치는, 급수를 위한 물이 담겨지는 급수탱크를 구비한 급수탱크부와, 상기 급수탱크부 측으로부터 물을 공급받을 수 있는 상태로 축사에 이격 배치되는 복수 개의 급수대들을 구비한 급수부와, 상기 급수부의 급수대들 측과 각각 대응하도록 배치되어 이 급수대들의 수위에 따라 물 공급이 가능하게 개폐 동작되도록 설치되는 플로트 밸브들을 구비한 개폐부와, 상기 급수탱크부 측에 담겨진 물이 자연 낙하에 의한 흐름으로 상기 급수부의 급수대들 측을 순차적으로 경유하는 상태로 상기 개폐부 측을 통해 공급될 수 있도록 배관되는 급수관을 구비한 관로부 및 상기 관로부를 따라 상기 급수부의 급수대들 측을 순차적으로 경유하는 상태로 흐르는 물이 담겨질 수 있는 저장탱크를 구비한 저장탱크부를 포함한다. claims: 급수를 위한 물이 담겨지는 급수탱크를 구비한 급수탱크부;상기 급수탱크부 측으로부터 물을 공급받을 수 있는 상태로 축사에 이격 배치되는 복수 개의 급수대들을 구비한 급수부;상기 급수부의 급수대들 측과 각각 대응하도록 배치되어 이 급수대들의 수위에 따라 물 공급이 가능하게 개폐 동작되도록 설치되는 플로트 밸브들을 구비한 개폐부;상기 급수탱크부 측에 담겨진 물이 자연 낙하에 의한 흐름으로 상기 급수부의 급수대들 측을 순차적으로 경유하는 상태로 상기 개폐부 측을 통해 공급될 수 있도록 배관되는 급수관을 구비한 관로부;상기 관로부를 따라 상기 급수부의 급수대들 측을 순차적으로 경유하는 상태로 흐르는 물이 담겨질 수 있는 저장탱크를 구비한 저장탱크부; 및상기 관로부 내의 물 흐름 방향 전환을 위하여 상기 저장탱크부의 저장탱크 측을 높낮이 조절이 가능하게 받쳐줄 수 있도록 형성되는 전환지지대를 구비한 급수전환부;를 포함하는 축사용 급수장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

914/1059 Row 914: application_number: 1020190035415, combined_string: invention_title: 실내 정화용 태양광가열장치가 구비된 축사용 시설물 abstract: 본 발명은 실내 정화용 태양광가열장치가 구비된 축사용 시설물에 관한 발명으로서, 상세하게는 축사와 같은 가축이나 원예작물 기르는 시설물에 맞추어서 태양광 발전판을 설치하여 주되, 비치는 태양광으로 발전되는 전력으로 가동되는 펌프에 의한 가압공기를 급속한 서냉으로 형성되는 냉각공기를 축사의 실내공간에 분출로서 실내정화를 제공하는 발명이다.일반적으로 축사용 하우스와 같은 축사단지는 대부분 도시의 가장자리에서 기술의 발전에 따라 점점 대단위로 설치함으로서, 이의 면적에서 기후 변화로 형성되는 폭염이나 혹서기에 발생하는 피해에 대한 대비가 필요하는 것이다.이는 하우스를 서로 연속적으로 설치로서 원예단지나 하우스로 제공되는 실내공간은 넓은 면적을 형성함으로서, 상기 비닐하우스 단지의 면적에 비치는 태양광의 량으로 발전하는 발전량은 많다고 할 것입니다.따라서 본 발명을 상세히 설명하면, 축산단지(43)의 실내공간(28)이 구비되도록, 골조(11)의 외측으로 감싸주는 비닐(21)로 조립으로 형성되는 하우스(20)와, 상기 하우스(20)용 갓길(14)에서 연속 반복적으로 길이방향에 따라 돌출되는 기둥(15)과, 상기 돌출되는 기둥(15) 사이를 일체로 연결되는 프레임(29), 상기 프레임(29)에 결합된 미도시된 제어장치의 구동으로 회전되는 회전형 도어(27)로, 기둥(15) 사이에 설치된 차양막(30)의 구동으로 조절되는 공기통로(41)와, 상기 기둥(15)을 연결되는 빔(17)으로 구축된 하우스(20)에서 양측으로 경사지는 경사프레임(23)과 돌출부(38)의 구비로 조립구간(18)을 형성시켜 주는 축산단지에 있어서, 상기 경사프레임(23)에 힌지(36)로 결합되는 태양광가열판(40)과, 상기 태양광가열판(40)의 모서리에 연결되는 로푸(39)의 구비로 태양광의 비치는 방향에 따라 힌지(36)을 중심으로 일측의 태양광가열판(40)이 회전으로 열려지는 경사프레임(23)과, 상기 태양광가열판(40)의 하측으로 고정로드(24)에 조립되는 흰색의 열반사대(35)의 구비로 축산단지(43)의 실내에 서냉이나 보온되도록 제공되는 발명이다.또한 상기 태양광가열판(40)을 소정의 이격된 간격으로 발전소자(16)을 구비된 태양광발전판(25)으로 형성시켜 주되, 상기 빔(17)의 중앙부에서 태양광발전판(25)의 중심부를 고정하도록 연결되는 회전축(37)과, 상기 회전축(37)이 교차하도록 고정봉(22)에 구비된 베벨기어(26)와, 상기 베벨기어(26)의 회전구동으로, 태양광발전판(25)이 태양광 비치는 량을 차단 구동함으로서, 햇볕 유입 및 배출구간(a)(b)을 형성하는 수평구간(c)으로 회전시켜 주고, 상기 실내공간(28)의 상측구간(d)에 구비된 지지로드(46)에 공기 이동구간을 형성하는 안내벽(42)으로, 혹한기에 냉해 방지나, 태풍에 의한 피해를 방지되도록 제공되는 발명이다. claims: 축산단지(43)의 실내공간(28)이 구비되도록, 골조(11)의 외측으로 감싸주는 비닐(21)로 조립으로 형성되는 하우스(20)와, 상기 하우스(20)용 갓길(14)에서 연속 반복적으로 길이방향에 따라 돌출되는 기둥(15)과, 상기 돌출되는 기둥(15) 사이를 일체로 연결되는 프레임(29), 상기 프레임(29)에 결합된 미도시된 제어장치의 구동으로 회전되는 회전형 도어(27)로, 기둥(15) 사이에 설치된 차양막(30)의 구동으로 조절되는 공기통로(41)와, 상기 기둥(15)을 연결되는 빔(17)으로 구축된 하우스(20)에서 양측으로 경사지는 경사프레임(23)과 돌출부(38)의 구비로 조립구간(18)을 형성시켜 주는 축산단지에 있어서, 상기 경사프레임(23)에 힌지(36)로 결합되는 태양광가열판(40)과, 상기 태양광가열판(40)의 모서리에 연결되는 로푸(39)의 구비로 태양광의 비치는 방향에 따라 힌지(36)을 중심으로 일측의 태양광가열판(40)이 회전으로 열려지는 경사프레임(23)과, 상기 태양광가열판(40)의 하측으로 고정로드(24)에 조립되는 흰색의 열반사대(35) 구비로 축산단지(43) 실내에 서냉이나 보온되도록 제공되는 실내 정화용 태양광가열장치가 구비된 축사용 시설물., Ltext: 농업, prediction: 임업
915/1059 Row 915: application_number: 1020190033245, combined_string: invention_title: 가축첨가사료제조법 abstract: 본 발명은 해조류와 파인애플을 주재로 하고, 고온 유산균발효 함이 특징인 가축먹이 첨가사료 및 그 제조방법을 제공하는 것으로서, 소, 닭, 돼지를 포함하는 가축 특히 젖소의 번식기능을 강화하고, 건강지수(mun)를 개선하고, 산유량을 증가하고, 젖에 포함되는 체세포수를 감소시키고, 수태율을 증진시키고, 공태기간을 감소시킴은 물론, 수산업반전에 기여하고, 환경오염을 방지하는 등의 효과를 수반하는 것이다. claims: 가축먹이 첨가사료에 있어서,파쇄 미역, 다시마, 김, 파래 중에서 선택한 해조류 40~90중량부(건조상태);잘게 절단한 파인애플 10~60중량부;의 혼합물을 유산 발효하고,가축먹이에 혼합하여 급이하는 가축 먹이 첨가사료.파쇄 미역, 다시마, 김, 파래 중에서 선택한 해조류 40~90중량부(건조상태),잘게 절단한 파인애플 10~60중량부 및 효소생균제로서 유산균제재 03~07중량부를 혼합하는 단계와;상기 혼합재료를 차광비닐백에 기밀포장하는단계와;상기 기밀포장된 재료를 방치하여 고온 유산 발효를 유도하는 단계;로 구성함이 특징인 가축먹이 첨가사료 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

916/1059 Row 916: application_number: 1020190030352, combined_string: invention_title: 축사용 냉온 환풍기 abstract: 본 발명은 공장이나 돈사 또는 계사 등의 실내 온도를 적정 온도로 유지하는 한편 실내 공기를 환기시키는 냉온 환풍기에 관한 기술로서, 실내 공기에 포함된 미세먼지나 가스 등을 여과 및 정화한 다음, 대기중으로 배출함에 따라 친환경적으로 사용이 가능할 뿐만 아니라 쾌적한 실내환경을 조성하므로, 작업 환경이 개선되는 한편 가축의 성장을 촉진하며, 조립 및 작업성이 우수한 축사용 냉온 환풍기에 관한 기술이다.이러한 본 발명의 주요 구성은, 이동이 용이하게 다수개의 캐스터가 설치된 프레임; 상기 프레임의 상부 한쪽에 설치되고, 내부에 압축기와 팽창밸브가 설치된 컨트롤박스; 상기 컨트롤박스의 상부에 설치되는 응축기; 상기 프레임의 상부 한쪽에 배치되는 증발기; 상기 증발기의 한쪽에 부착 설치되며, 실내로 외부공기를 송풍하는 환풍기; 상기 프레임의 상부 한쪽에 배치되고, 오염된 실내 공기를 흡입해 여과 및 정화하여 대기중으로 배출하는 정화챔버; 및 상기 환풍기에서 실내로 송풍되는 외부공기를 가열하는 가열챔버;를 포함하여 구현된다. claims: 이동이 용이하게 다수개의 캐스터(11)가 설치된 프레임(10); 상기 프레임(10)의 상부 한쪽에 설치되고, 내부에 압축기와 팽창밸브가 설치된 컨트롤박스(20); 상기 컨트롤박스(20)의 상부에 설치되는 응축기(30); 상기 프레임(10)의 상부 한쪽에 배치되는 증발기(40); 상기 증발기(40)의 한쪽에 부착 설치되며, 실내로 외부공기를 송풍하는 환풍기(50); 상기 프레임(10)의 상부 한쪽에 배치되고, 오염된 실내 공기를 흡입해 여과 및 정화하여 대기중으로 배출하는 정화챔버(60); 및 상기 환풍기(50)에서 실내로 송풍되는 외부공기를 가열하는 가열챔버(70);를 포함하고,상기 프레임(10)은 사각틀의 형태로 짜여져 구성되며, 하부에 일정한 간격으로 다수개의 캐스터(11)가 부착 설치되고,상기 컨트롤박스(20)는 철판을 절곡하여 사각 형태로 구성되며, 내부 공간에 압축기ㆍ팽창밸브ㆍ냉매탱크 및 각종 제어기가 설치되고, 프레임(10)의 상부 한쪽에 놓여 조립 설치되며,상기 환풍기(50)는 나팔관 형태로 한쪽은 넓고, 이와 반대쪽은 좁게 형성된 가이드밴(53)이 증발기(40)의 한쪽 면에 부착 설치되며, 상기 가이드밴(53)에서 좁게 형성된 방향의 플렌지에 본체(51)가 체결나사로 부착 설치되고, 상기 본체(51)의 내부에 팬이 배치되는 한편 외부에 모터(52)가 설치되며, 상기 본체(51)의 상부에 외부 공기를 실내로 송풍하는 송풍덕트(54)가 연결 설치되고,상기 정화챔버(60)는 직사각 형상의 박스형태로 구성되며, 외부 한쪽 면에 실내에서 오염된 공기를 흡입하는 배기덕트(61)가 연결 설치되는 한편 내측면에 다수개의 노즐(66)이 장착된 분사관(65)이 설치되고, 길이 방향의 한쪽 면에 배기실(62)이 관통하여 구성되며, 상기 배기실(62)의 상부에 배기팬(63)이 설치되는 한편 배기팬(63)의 상부에 여과 및 정화된 실내 공기를 대기중으로 배출하는 배기관(64)이 연결 설치되고,상기 분사관(65)이 배기덕트(61)와 동일 선상에 위치하며, 상기 배기덕트(61)를 통해 흡입되는 오염된 실내 공기에 노즐(66)이 여과수를 미립자로 분사하고,상기 정화챔버(60)는 배기실(62) 사이에 여과필터(67)가 가로막혀 설치되며, 상기 여과필터(67)의 전방에 다수개의 노즐(66)이 장착된 분사관(65)이 부착 설치되고,상기 가열챔버(70)는 증발기(40)의 상부에 놓여 배치되며, 전면부와 후면부에 송풍덕트(54)가 연결 설치되고, 내부 공간에 복수개로 전기 히터(71)가 설치되며, 상기 히터(71)는 지그재그 형상으로 구성되는 한편 일정한 간격으로 다수개의 방열판(72)이 부착 설치된 것을 특징으로 하는 축사용 냉온 환풍기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

917/1059 Row 917: application_number: 1020190027910, combined_string: invention_title: 가축 질병 예측 시스템 abstract: 본 발명의 일 실시예에 따른 가축 질병 예측 시스템은 가축에 부착되며 가축의 생체정보를 감지하고, 가축의 식별정보가 등록된 무선태그; 축사 내의 피더 및 물탱크 주변에 설치되며, 상기 무선태그가 피더 및 물탱크와 일정거리 이내에 있는 경우 사료 및 물을 섭취하는 것으로 인식하고, 사료 및 물섭취 정보와 생체정보를 전송하는 인식장치; 상기 인식장치로부터 가축의 생체정보와 사료섭취 및 물섭취에 대한 정보를 수신하여 가축의 사료섭취 및 물섭취에 대한 행동정보를 판단하며, 데이터베이스에 저장된 데이터와 비교하여 가축의 이상 여부를 머신러닝 기반으로 분석하여 가축의 질병을 예측하는 분석부; 및 상기 분석결과를 통계화하고, 기 등록된 관리자에게 분석결과를 전송하는 모니터링부를 포함한다. claims: 가축에 부착되며 가축의 생체정보를 감지하고, 가축의 식별정보가 등록된 무선태그;축사 내의 피더 및 물탱크 주변에 설치되며, 상기 무선태그가 피더 및 물탱크와 일정거리 이내에 있는 경우 사료 및 물을 섭취하는 것으로 인식하고, 사료 및 물섭취 정보와 생체정보를 전송하는 인식장치;상기 인식장치로부터 가축의 생체정보와 사료섭취 및 물섭취에 대한 정보를 수신하여 가축의 사료섭취 및 물섭취에 대한 행동정보를 판단하며, 데이터베이스에 저장된 데이터와 비교하여 가축의 이상 여부를 머신러닝 기반으로 분석하여 가축의 질병을 예측하는 분석부; 및상기 분석결과를 통계화하고, 기 등록된 관리자에게 분석결과를 전송하는 모니터링부를 포함하며, 상기 분석부는, 상기 인식장치로부터 센서 데이터 및 인터넷을 통하여 가축관련 클라우드 정보를 수집하되, 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 및 축사 베이스 데이터를 포함하는 정보를 수집하는 데이터 수집부;상기 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 축사 베이스 데이터를 가공하여 통계 분석용 데이터 마트를 생성하는 데이터 가공부;상기 데이터 수집부에서 수집된 데이터 및 데이터 가공부에서 생성된 데이터를 빅데이터 플랫폼으로 저장하는 데이터베이스;상기 사료섭취 및 물섭취에 대한 행동정보를 Random Forest 알고리즘을 기반으로 분석하여 상기 가축의 질병을 예측하는 예측부; 및 상기 예측부에서 예측된 결과와 실제결과값에 대한 재학습을 수행하여 오차율을 최소화하되, 리샘플링 방법에 의해 오차율을 1차적으로 줄이고, 모델 결합법을 이용하여 오차율을 2차적으로 줄여 오차율을 최소화하는 오차율 최소화부;를 포함하고, 상기 모니터링부는, 가축의 일일평균 사료 섭취량, 물섭취량, 및 질병예측 결과를 통계적으로 디스플레이하고, 상기 질병예측 결과에 따른 대응 및 질병 발명 유무에 대한 통계를 디스플레이하고, 상기 가축은 고유번호가 부여된 축사에서 관리되고, 단위 축사에 펜번호가 부여되고, 다수의 펜번호가 그룹핑되어 롯번호가 부여되고, 다수의 롯번호가 그룹핑되어 야드번호가 부여되고, 상기 가축 베이스 데이터는 해당 날짜, 가축의 입출고 날짜, 가축의 출생일, 가축의 고유번호, 가축에게 부착된 태그의 고유번호, 해당 날짜 기준 가축의 무게, 입고일 기준 가축의 무게, 출고일 기준 가축의 무게, 가축의 성별, 해당 날짜에 가축이 속한 축사 번호, 가축의 출신 롯번호 및 가축의 상태에 대한 정보를 포함하고, 상기 사료 베이스 데이터는 해당 날짜, 가축의 고유 번호, 가축에게 부착된 태그의 고유번호, 해당 날짜에 가축이 사료를 먹은 횟수, 해당 날짜에 가축이 사료 섭취를 시작한 시간, 가축이 사료 섭취를 끝낸 시간, 및 가축의 사료 섭취 기간(duration)에 대한 정보를 포함하고, 상기 물 베이스 데이터는 해당 날짜, 가축의 고유번호, 가축에게 부착된 태그의 고유번호, 해당 날짜에 가축이 물을 섭취한 횟수, 해당 날짜에 가축이 물 섭취를 시작한 시간, 해당 날짜에 가축이 물 섭취를 끝낸 시간, 및 가축의 물 섭취 기간(duration)에 대한 정보를 포함하고, 상기 축사 베이스 데이터는 해당 날짜, 가축의 고유번호, 가축에게 부착된 태그의 고유번호, 가축의 속한 펜의 온도, 가축이 속한 펜의 습도, 가축이 해당 날짜에 소속된 펜의 번호, 가축의 상태에 대한 정보를 포함하고, 상기 데이터 가공부는 상기 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 및 축사 베이스 데이터를 가공하여 제1 내지 제9 데이터 마트를 생성하고, 상기 제1 데이터 마트는 가축 식별번호, 펜번호, 날짜, 위험소의 비율 데이터를 포함하고, 상기 제2 데이터 마트는 가축 식별번호, 펜번호, 활동적인 가축의 수, 위험 가축의 수, 위험 가축의 비율 데이터를 포함하고, 상기 제3 데이터 마트는 가축 식별번호, 롯번호, 가축 상태, 사료섭취 횟수, 물섭취 횟수 데이터를 포함하고, 상기 제4 데이터 마트는 가축 식별번호, 펜번호, 가축 상태, 사료섭취 횟수, 물섭취 횟수 데이터를 포함하고, 상기 제5 데이터 마트는 가축 식별번호, 날짜, 사료섭취 횟수, 물섭취 횟수 데이터를 포함하고, 상기 제6 데이터 마트는 가축 식별번호, 야드번호, 가축상태, 사료섭취 횟수, 물섭취 횟수 데이터를 포함하고, 상기 제7 데이터 마트는 가축 식별번호, 건강상태 하위 10%·노멀상태·상위 10% 가축에 대한 데이터를 포함하고, 상기 제8 데이터 마트는 가축 식별번호, 롯번호, 펜번호, 날짜, 사육일수, 가축의 무게, 가축상태에 대한 정보를 포함하고, 상기 제9 데이터 마트는 가축 식별번호, 입고일, 날짜, 사육일수, 가축상태 사료섭취량 합계, 물섭취량 합계, 펜의 평균 사료섭취량, 야드의 평균 사료섭취량, 롯의 평균 사료섭취량, 롯의 평균 물섭취량 데이터를 포함하고, 상기 모니터링부는 상기 제1 데이터 마트 내지 제9 데이터 마트를 이용하여, 각각의 펜, 롯, 야드에 분포되어 있는 가축의 분포를 디스플레이하고, 이상징후 또는 질병 징후가 있는 객체를 선택하여 펜, 롯, 야드의 평균과 비교하여 표시하고, 과거 이력 데이터를 추적하여 이상 가축의 행동 패턴을 추출하고, 사육일수에 마리당 평균 비용을 곱한 값에서 개별 가축의 무게와 단위 무게당 평균 이익을 곱한 값을 차감하여 최적 사육일수를 계산하여 표시하는 것을 특징으로 하는 가축 질병 예측 시스템. 가축에 부착되며 가축의 생체정보를 감지하고, 가축의 식별정보가 등록된 무선태그;축사 내의 피더 및 물탱크 주변에 설치되며, 상기 무선태그가 피더 및 물탱크와 일정거리 이내에 있는 경우 사료 및 물을 섭취하는 것으로 인식하고, 사료 및 물섭취 정보와 생체정보를 전송하는 인식장치;상기 인식장치로부터 가축 식별정보 및 인식장치 식별정보를 수신하고, 상기 인식장치 식별정보를 근거로 가축의 사료섭취 및 물섭취에 대한 행동정보를 판단하며, 전송하는 중계장치; 상기 중계장치로부터 가축의 생체정보와 사료섭취 및 물섭취에 대한 정보를 수신하여 가축의 사료섭취 및 물섭취에 대한 행동정보를 판단하며, 데이터베이스에 저장된 데이터와 비교하여 가축의 이상 여부를 머신러닝 기반으로 분석하여 가축의 질병을 예측하는 분석부; 및상기 분석결과를 통계화하고, 기 등록된 관리자에게 분석결과를 전송하는 모니터링부를 포함하며, 상기 분석부는, 상기 인식장치로부터 센서 데이터 및 인터넷을 통하여 가축관련 클라우드 정보를 수집하되, 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 및 축사 베이스 데이터를 포함하는 정보를 수집하는 데이터 수집부;상기 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 및 축사 베이스 데이터를 가공하여 통계 분석용 데이터 마트를 생성하는 데이터 가공부;상기 데이터 수집부에서 수집된 데이터 및 데이터 가공부에서 생성된 데이터를 빅데이터 플랫폼으로 저장하는 데이터베이스;상기 사료섭취 및 물섭취에 대한 행동정보를 Random Forest 알고리즘을 기반으로 분석하여 상기 가축의 질병을 예측하는 예측부; 및 상기 예측부에서 예측된 결과와 실제결과값에 대한 재학습을 수행하여 오차율을 최소화하되, 리샘플링 방법에 의해 오차율을 1차적으로 줄이고, 모델 결합법을 이용하여 오차율을 2차적으로 줄여 오차율을 최소화하는 오차율 최소화부;를 포함하고, 상기 중계장치는, 상기 축사에 위치하는 가축의 식별정보, 평균 사료 섭취량, 부모 이력, 백신 접종 정보, 출생지 및 도축지에 관한 이력 정보 및 가축의 행동정보를 판단할 수 있는 애플리케이션이 저장되는 저장부;상기 인식장치로부터 가축 식별정보 및 인식장치 식별정보가 수신된 경우, 상기 인식장치 식별정보를 근거로 상기 가축 식별정보에 대응하는 가축의 사료 섭취 및 물 섭취에 대한 행동정보를 판단하는 판단부; 상기 애플리케이션을 구동시켜 상기 판단부가 행동정보를 판단하도록 제어하는 제어부; 및상기 가축 식별정보, 축사 식별정보 및 사료섭취 및 물섭취에 대한 행동정보를 포함하는 센싱정보를 디지털 신호로 변환하여 상기 분석부로 전송하는 무선 통신부;를 포함하고, 상기 가축은 고유번호가 부여된 축사에서 관리되고, 단위 축사에 펜번호가 부여되고, 다수의 펜번호가 그룹핑되어 롯번호가 부여되고, 다수의 롯번호가 그룹핑되어 야드번호가 부여되고, 상기 가축 베이스 데이터는 해당 날짜, 가축의 입출고 날짜, 가축의 출생일, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

918/1059 Row 918: application_number: 1020190024584, combined_string: invention_title: 축사용 악취 및 분진 제거시스템 abstract: 본 발명은 축사용 악취 및 분진 제거시스템에 관한 것이다.더욱 상세하게는, 프레임부; 상기 프레임부의 상부 일 측면에 형성되어 축사 내에서 배출되는 악취 및 분진이 유입되는 유입구; 상기 프레임부의 내부에 구비되며 하나 또는 복수의 분사노즐을 통해 미생물 배양액 및 물 중 어느 하나 또는 복수를 포함하는 액체를 분사하도록 구성되는 하나 또는 복수의 세정부; 상기 프레임부의 내부에 구비되는 하나 또는 복수의 필터부; 및 상기 프레임부의 하부 타 측면에 형성되어 상기 세정부 및 필터부를 통해 이동된 악취 및 분진이 배출되는 배출구를 포함하는 것을 특징으로 한다. 본 발명에 의하면, 축사에서 발생되는 악취 및 분진이 세정부와 필터부를 거쳐서 배출되도록 구성됨으로써, 축사에서 발생되는 악취 및 분진을 처리하기 위한 비용 및 노동력을 절감할 수 있도록 하는 효과가 있다. claims: 상부 일 측면에 형성되어 축사(800) 내에서 배출되는 악취 및 분진이 유입되는 유입구(200) 및 하부 타 측면에 형성되는 배출구(500)를 포함하는 프레임부(100);상기 프레임부(100)의 내부에 구비되며 하나 또는 복수의 분사노즐(310)을 통해 미생물 배양액 및 물 중 어느 하나 또는 복수를 포함하는 액체를 분사하도록 구성되는 하나 또는 복수의 세정부(300); 및상기 프레임부(100)의 내부에 구비되는 하나 또는 복수의 필터부(400);가 포함되고,상기 분사노즐(310)을 통해 분사되는 미생물 배양액은,바실러스(Bacilus)균 배양액, 락토바실러스(Lactobacillus)균 배양액, 엔테로코커스 훼시움(Enterococcus faecium)균 배양액, 스트렙토코커스(Streptococcus)균 배양액, 효모(Saccharomyces)균 배양액 및 하이포마이크로비윰 다니트리피칸스(Hyphomicrobium denitrificans)균 배양액 중 어느 하나 또는 복수가 포함되며,상기 필터부(400)에는,일 측 방향으로 연장 형성되며 나란히 배열되는 복수의 제1상부연장대(411), 상기 제1상부연장대(411)와 대응되는 형상으로 형성되어 상기 제1상부연장대(411)의 사이에 배치되되 하부 방향으로 이격된 위치에 배치되는 복수의 제1하부연장대(412), 상기 복수의 제1상부연장대(411)와 제1하부연장대(412)를 연결하는 복수의 제1연결대(413)를 포함하는 제1필터구조체(410); 및일 측 방향으로 연장 형성되며 나란히 배열되는 복수의 제2상부연장대(421), 상기 제2상부연장대(421)와 대응되는 형상으로 형성되어 상기 제2상부연장대(421)의 사이에 배치되되 하부 방향으로 이격된 위치에 배치되는 복수의 제2하부연장대(422), 상기 복수의 제2상부연장대(421)와 제2하부연장대(422)를 연결하는 복수의 제2연결대(423)를 포함하는 제2필터구조체(420);가 포함되고,상기 제1필터구조체(410) 및 제2필터구조체(420)는 상하 방향으로 적층되어 연결되도록 구성되며,상기 필터부(400)는,상기 제1필터구조체(410) 및 제2필터구조체(420)가 적층되어 연결되는 경우, 상기 제1필터구조체(410)의 복수의 제1하부연장대(412)와 상기 제2필터구조체(420)의 복수의 제2상부연장대(421)가 인접한 위치에서 마주하고 상기 복수의 제1하부연장대(412)의 사이에 위치되는 제1상부연장대(411)와 상기 복수의 제2상부연장대(421)의 사이에 위치되는 제2하부연장대(422)가 이격된 위치에서 마주하면서 상기 제1필터구조체(410) 및 제2필터구조체(420)의 사이에 생장공간(430)이 형성되고,상기 제1상부연장대(411)에 대응되는 방향으로 형성되어 상기 필터부(400)의 일 측 및 타 측에 각각 배치되는 이송수단(610), 상기 이송수단(610)에 연결되어 상기 이송수단(610)을 구동하는 구동모터(620) 및 상기 이송수단(610)에 연결되어 상기 구동모터(620)의 동작에 따라 이동되면서 상기 필터부(400)를 세척하는 브러쉬(630)가 포함되는 세척부(600)가 더 포함되며,상기 프레임부(100)의 하부에는 상기 세정부(300)의 분사노즐에서 분사된 액체 및 상기 액체에 의해 세정된 분진 등의 이물질이 배출되도록 하는 처리조(110)가 구비되고,상기 처리조(110)는 하부가 경사진 형태로 형성되어 외부로의 배출이 용이하도록 구성되는 것을 특징으로 하는 축사용 악취 및 분진 제거시스템.축사(800)의 상부 측면을 통해 배출되는 악취 및 분진이 유입되는 유입구(200), 상기 유입구(200)를 통해 유입된 악취 및 분진을 하부로 이동시키는 유입팬(210), 상기 유입팬(210)을 통해 이동되는 악취 및 분진을 하부로 가이드하는 격판(130) 및 상기 격판(130)을 중심으로 상기 유입구(200)와 대칭되는 위치에 구비되는 배출구(500)를 포함하여 U자 형상의 유로를 형성하는 프레임부(100);상기 프레임부(100)의 내부에 구비되며 하나 또는 복수의 분사노즐(310)을 포함하여, 상부로 이동되는 악취 및 분진에 미생물 배양액 및 물 중 어느 하나 또는 복수를 포함하는 액체를 분사하도록 구성되는 하나 또는 복수의 세정부(300); 및상기 프레임부(100)의 내부에 구비되며 상부로 이동되는 악취 및 분진이 필터링되도록 하는 하나 또는 복수의 필터부(400);가 포함되고,상기 분사노즐(310)을 통해 분사되는 미생물 배양액은,바실러스(Bacilus)균 배양액, 락토바실러스(Lactobacillus)균 배양액, 엔테로코커스 훼시움(Enterococcus faecium)균 배양액, 스트렙토코커스(Streptococcus)균 배양액, 효모(Saccharomyces)균 배양액 및 하이포마이크로비윰 다니트리피칸스(Hyphomicrobium denitrificans)균 배양액 중 어느 하나 또는 복수가 포함되며,상기 필터부(400)에는,일 측 방향으로 연장 형성되며 나란히 배열되는 복수의 제1상부연장대(411), 상기 제1상부연장대(411)와 대응되는 형상으로 형성되어 상기 제1상부연장대(411)의 사이에 배치되되 하부 방향으로 이격된 위치에 배치되는 복수의 제1하부연장대(412), 상기 복수의 제1상부연장대(411)와 제1하부연장대(412)를 연결하는 복수의 제1연결대(413)를 포함하는 제1필터구조체(410); 및일 측 방향으로 연장 형성되며 나란히 배열되는 복수의 제2상부연장대(421), 상기 제2상부연장대(421)와 대응되는 형상으로 형성되어 상기 제2상부연장대(421)의 사이에 배치되되 하부 방향으로 이격된 위치에 배치되는 복수의 제2하부연장대(422), 상기 복수의 제2상부연장대(421)와 제2하부연장대(422)를 연결하는 복수의 제2연결대(423)를 포함하는 제2필터구조체(420);가 포함되고,상기 제1필터구조체(410) 및 제2필터구조체(420)는 상하 방향으로 적층되어 연결되도록 구성되며,상기 필터부(400)는,상기 제1필터구조체(410) 및 제2필터구조체(420)가 적층되어 연결되는 경우, 상기 제1필터구조체(410)의 복수의 제1하부연장대(412)와 상기 제2필터구조체(420)의 복수의 제2상부연장대(421)가 인접한 위치에서 마주하고 상기 복수의 제1하부연장대(412)의 사이에 위치되는 제1상부연장대(411)와 상기 복수의 제2상부연장대(421)의 사이에 위치되는 제2하부연장대(422)가 이격된 위치에서 마주하면서 상기 제1필터구조체(410) 및 제2필터구조체(420)의 사이에 생장공간(430)이 형성되고,상기 제1상부연장대(411)에 대응되는 방향으로 형성되어 상기 필터부(400)의 일 측 및 타 측에 각각 배치되는 이송수단(610), 상기 이송수단(610)에 연결되어 상기 이송수단(610)을 구동하는 구동모터(620) 및 상기 이송수단(610)에 연결되어 상기 구동모터(620)의 동작에 따라 이동되면서 상기 필터부(400)를 세척하는 브러쉬(630)가 포함되는 세척부(600)가 더 포함되며,상기 프레임부(100)의 하부에는 상기 세정부(300)의 분사노즐에서 분사된 액체 및 상기 액체에 의해 세정된 분진 등의 이물질이 배출되도록 하는 처리조(110)가 구비되고,상기 처리조(110)는 하부가 경사진 형태로 형성되어 외부로의 배출이 용이하도록 구성되는 것을 특징으로 하는 축사용 악취 및 분진 제거시스템., Ltext: 농업, prediction: 임업
919/1059 Row 919: application_number: 1020190017161, combined_string: invention_title: 살균 및 항온 겸용 축사용 공기 공급시스템 abstract: 본 발명은 지열과 200nm~280nm 파장을 가지는 UV-C LED를 이용한 살균 및 항온 겸용 축사용 공기 공급시스템에 관한 것으로서, 더욱 상세하게는 지중의 온도인 지열을 이용하여 축사로 공급되는 온도를 유지하고, 또, UV-C 자외선을 이용하여 유입되는 공기중의 병원균, 곰팡이 등을 살균하여 청정한 공기를 공급하는 살균 및 항온 겸용 축사용 공기 공급시스템에 관한 것이다.이러한 기술적 과제를 달성하기 위한 본 발명은, UV LED 자외선 및 지열을 이용하는 살균 및 항온 겸용 축사용 공기 공급시스템에 있어서, 축사 외부의 공기를 축사 내부로 유입시키기 위한 공기유입부(100); 축사 내부로 살균 및 항온이 유지된 공기를 축사 내부로 공급하는 공기유출부(200); 상기 공기유입(100)부로부터 유입된 공기의 온도를 지열을 이용하여 조절하는 열교환부(300); 상기 공기유입부(100)로부터 유입된 공기를 200nm~280nm 파장을 가지는 UV-C LED를 통해 살균 하는 살균부(400); 상기 200nm~280nm 파장을 가지는 UV-C LED의 전원을 제어하는 제어부(500); 를 포함하는 것을 특징으로 한다.또한 바람직하게, 상기 공기유출부(200)는 유출공기의 양을 조절하기 위하여 배기용 팬 장치를 더 포함하는 것을 특징으로 한다.또한 바람직하게, 상기 제어부(500)은, 축사 내부로 유출공기의 온도를 적정하게 유지하기 위하여 축사 내부 공기를 상기 공기유입부(100)로 보내는 재순환하는 재순환부(600)를 더 포함하는 것을 특징으로 한다.` claims: UV LED 자외선 및 지열을 이용하는 살균 및 항온 겸용 축사용 공기 공급시스템에 있어서,축사 외부의 공기를 축사 내부로 유입시키기 위한 공기유입부(100);축사 내부로 살균 및 항온이 유지된 공기를 축사 내부로 공급하는 공기유출부(200);상기 공기유입(100)부로부터 유입된 공기의 온도를 지열을 이용하여 조절하는 열교환부(300);상기 공기유입부(100)로부터 유입된 공기를 200nm~280nm 파장을 가지는 UV-C LED를 통해 살균 하는 살균부(400);상기 200nm~280nm 파장을 가지는 UV-C LED의 전원을 제어하는 제어부(500); 를 포함하는 것을 특징으로 하는 살균 및 항온 겸용 축사용 공기 공급시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

920/1059 Row 920: application_number: 2020190000610, combined_string: invention_title: 축사용 도어 잠금장치 abstract: 축사용 도어 잠금장치에 관한 것으로, 걸림부재의 록킹 및 이탈이 가능하도록 상면이 개방되게 형성되며, 축사의 기둥에 설치되는 고정부재; 축사의 도어프레임에 설치되도록 형성되는 제1 고정플레이트와, 상기 제1 고정플레이트로부터 소정의 간격으로 이격되게 형성되는 제2 고정플레이트와, 상기 제2 고정플레이트로부터 소정의 간격으로 이격되는 제3 고정플레이트가 일체로 형성된 장착부재; 상기 고정부재에 끼워져 록킹되도록 상기 장착부재에 회전 가능하게 설치되는 걸림부재; 상기 걸림부재가 상기 고정부재에 록킹된 상태를 안정적으로 유지시키도록 상기 장착부재에 회전 가능하게 설치되는 록킹부재;를 마련하여 도어프레임에 장착부재를 끼워 간편하게 설치할 수 있고, 걸림부재를 록킹부재로 고정시킴에 따라 2중 잠금 상태로 록킹시킬 수 있으며, 도어프레임의 내측 및 외측에서 자유로이 개폐시킬 수 있고, 소 등의 가축이 도어프레임에 접촉하더라도 록킹 상태를 안정적으로 유지할 수 있다는 효과가 얻어진다. claims: 걸림부재(40)의 록킹 및 이탈이 가능하도록 상면이 개방되게 형성되며, 축사의 기둥에 설치되는 고정부재(10);축사의 도어프레임(1)에 설치되도록 형성되는 제1 고정플레이트(21)와, 상기 제1 고정플레이트(21)로부터 소정의 간격으로 이격되게 형성되는 제2 고정플레이트(22)와, 상기 제2 고정플레이트(22)로부터 소정의 간격으로 이격되는 제3 고정플레이트(23)가 일체로 형성된 장착부재(20);상기 고정부재(10)에 끼워져 록킹되도록 상기 장착부재(20)에 회전 가능하게 설치되는 걸림부재(40); 및상기 걸림부재(40)가 상기 고정부재(10)에 록킹된 상태를 안정적으로 유지시키도록 상기 장착부재(20)에 회전 가능하게 설치되는 록킹부재(50);를 포함하되,상기 장착부재(20)는 상기 도어프레임(1)에 일정 높이 간격으로 고정된 제1 프레임(2)과 제2 프레임(3)의 일측 외면에 밀착되도록 소정 높이로 형성되는 제1 고정플레이트(11);상기 제1 고정플레이트(11)로부터 연장 형성되는 제1 연장부(22a)와, 상기 제1 연장부(22a)로부터 상기 제1 프레임(2)의 타측 외면에 밀착되도록 소정 높이로 형성되는 제2 고정플레이트(22);상기 제2 고정플레이트(22)로부터 연장 형성되는 제2 연장부(23a)와, 상기 제2 연장부(23a)의 선단에서 소정 높이로 형성되는 제3 고정플레이트(23);를 포함하며,상기 제1 고정플레이트(21), 상기 제2 고정플레이트(22) 및 상기 제3 고정플레이트(23)가 일체로 형성되고,상기 장착부재(20)가 상기 제2 프레임(3)에 안정되게 고정되도록 소정의 길이로 형성되는 수평플레이트(32)와, 상기 수평플레이트(32)의 선단에서 소정의 높이로 형성되는 수직플레이트(33)가 일체로 형성된 하부고정플레이트(31);를 포함하는 것을 특징으로 하는 축사용 도어 잠금장치., Ltext: 농업, prediction: 임업
921/1059 Row 921: application_number: 1020190015335, combined_string: invention_title: 살균 및 방충 기능이 구비된 축사용 에어커튼 abstract: 본 발명은 축사용 에어커튼에 관한 것으로, 보다 상세하게는, 축사의 개방된 부위에 설치되어 축사 내부와 외부 사이에 에어 커튼을 형성함에 있어서, 살균 성분이 함유된 운무를 분사하면서 에어 커튼을 형성하여, 축사 외부로부터 해충이나 유해한 세균이 축사 내부로 침투하는 것을 방지하고, 축사 내부의 공기를 정화시켜 악취를 감소시킬 수 있으며, 축사 내부의 공기를 순환시켜 냉방이나 난방 시 전체적으로 적정한 온도로 유지할 수 있는 살균 및 방충 기능이 구비된 축사용 에어커튼에 관한 것이다.이를 위해 본 발명의 일실시예에 따른 살균 및 방충 기능이 구비된 축사용 에어커튼은, 하부에 송풍구가 구비되고 축사의 출입구 상부에 설치되어 출입구 측으로 에어를 분사함에 따라 에어커튼을 형성하는 에어커튼 본체, 상기 에어커튼 본체 내부에 설치되어 풍력을 발생시킴에 따라 출입구 측으로 에어를 분사하는 풍력 발생부, 상기 에어커튼 본체에 축사 내측 방향으로 구비되어, 축사 내부의 공기가 상기 풍력 발생부에 의해 흡입될 때 축사 내부의 악취를 정화시켜주는 에어 필터 및 상기 에어커튼 본체의 상부에 구비되어, 상기 풍력 발생부에서 발생된 바람에 운무가 혼입되어 송풍되도록 운무를 발생시키는 운무 분사부를 포함한다. claims: 하부에 송풍구(110)가 구비되고 축사(10)의 출입구(11) 상부에 설치되어 출입구(11) 측으로 에어를 분사함에 따라 에어커튼을 형성하는 에어커튼 본체(100);상기 에어커튼 본체(100) 내부에 설치되어 풍력을 발생시킴에 따라 출입구(11) 측으로 에어를 분사하는 풍력 발생부(200);상기 에어커튼 본체(100)에 축사(10) 내측 방향으로 구비되어, 축사(10) 내부의 공기가 상기 풍력 발생부(200)에 의해 흡입될 때 축사(10) 내부의 악취를 정화시켜주는 에어 필터(300); 및 상기 에어커튼 본체(100)의 내부에 구비되어, 상기 풍력 발생부(200)에서 발생된 바람에 운무가 혼입되어 송풍되도록 운무를 발생시키는 운무 분사부(400)를 포함함에 있어서,상기 에어커튼 본체(100)는 에어커튼 본체(100)의 하부에 출입구(11)를 향하도록 구비되어 출입구(11) 측으로 에어를 분사하는 송풍구(110)와, 상기 송풍구(110)에 설치되어 송풍 방향을 조절할 수 있는 송풍방향 조절부재(120)와, 별도의 압력탱크(140)에 연결되어, 축사(10) 내부를 향해 고압의 에어를 송풍하는 고압 송풍부(130) 및 상기 운무 분사부(400)에서 발생된 운무를 송풍구(110) 측이나 고압 송풍부(130) 측으로 선택적으로 유도하는 운무 유도편(150)을 포함하고, 상기 운무 분사부(400)는 에어커튼 본체(100)의 상부에 구비되어 다량의 물이 저장되는 물 저장탱크(410)와, 상기 물 저장탱크(410)의 하부 일측에 구비되어, 물 저장탱크(410)로부터 소량의 물이 공급되면 초음파에 의해 운무를 발생시키는 초음파 진동부(420) 및 상기 초음파 진동부(420)의 일측에 연결되어, 초음파 진동부(420)에 의해 발생된 운무를 송풍구 측으로 분사하는 운무 분사 노즐(430)을 포함하되,상기 물 저장탱크(410)는 물 저장탱크(410)에 수용되었던 물이 초음파 진동부(420) 측으로 수압에 의해 일정량씩만 이송되도록 유지하며 물을 이송시키는 물 이송 노즐(411)이 더 구비되며, 상기 물 이송 노즐(411)에는 물 저장탱크(410)에 수용된 물이 이송될 때 소량씩 이송되면서, 물에 함유된 이물질을 걸러주는 다공성 세라믹 볼(412)이 더 구비되는 것을 특징으로 하는 살균 및 방충 기능이 구비된 축사용 에어커튼., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

922/1059 Row 922: application_number: 1020210109391, combined_string: invention_title: 가축분뇨 발효촉진 분말살포제 제조방법 abstract: 본 발명의 '가축분뇨 발효촉진 분말살포제 제조방법'은 축산분뇨에서 분뇨냄새를 소멸시키는 방법은 발효뿐이므로 사육장 바닥에 널려져 있는 가축분뇨를 수거하여 발효시키는 방법이 아니라 아예 사육장 바닥에서 가축이 밟으며 스스로 발효시켜 수거하기만 하면 그대로 발효퇴비로 사용할 수 있게 하는 발효촉진 분말살포제로 제조하는 제조방법에 관한 축산분야의 발명에 속한다,일반적으로 축산분뇨라 하면 냄새, 즉 악취로 취급하는데 축산분뇨는 천연비료로 자연농법에 속하는 퇴비로 이용되므로 버리는 것이 아니라 유용하게 사용되는 것인데 축산농가 주변 주민들에 의해 쫓겨날 처지이기에 이를 대비하여 축산분뇨를 퇴비비료로 만들 발효촉진용 분말살포제로 위기를 벗어나게 하려는 발명이다,본 발명에서 재활용 축산분뇨비료로 제공되므로 인하여 축산농가가 안심하게 사육할 수 있도록 하므로 자연농법용 축산분뇨 퇴비로 재활용비료 제조와 축산농가의 고민을 해결하면서 유기질비료도 얻게 되어 축산농민은 물론 일반경종 영농농민들과 주변 주민들에게도 희소식이 되는 효과가 기대된다,[색인어]북산분뇨, 분말살포제, 유산미량광물, 죽순추출용액,해조추출용액, 패분(貝粉), 입자크기(mesh), claims: 제올라이트(10)와 미량광물질(20)과 죽순(30)과 해조류(40)와 패분(50)을 재료수집(제1단계)하여 재료가공(제2단계)에서 상기 제올라이트는 열 건조시켜 제올라이트분말로 분쇄하고, 상기 패분도 패분분말로 분쇄하고, 상기 미량광물질은 모두 용해시켜 수차례 여과 후 숙성미량광물질용액으로 숙성시키고, 상기 죽순과 상기 해조류는 각각 죽순추출용액과 해조추출용액으로 가공하고,상기 제올라이트분말과 상기 숙성미량광물질용액과 상기 죽순추출용액과 상기 해조추출용액과 상기 패분분말을 지정배합비로 재료칭량(제3단계)하고, 상기 재로칭량 후 혼합할 때 상기 제올라이트분말과 상기 패분분말에 상기 용액들이 골고루 흡수되도록 재료배합(제4단계)하고, 상기 재료배합이 종료되면 지정된 용량으로 재료포장(제5단계)하여 분말살포제(60)로 제작하는 것이 특징인 가축분뇨 발효촉진 분말살포제 제조방법,, Ltext: 농업, prediction: 임업
923/1059 Row 923: application_number: 1020210051014, combined_string: invention_title: 볏짚엔실리지와 이의 제조방법 abstract: 본 발명의 '볏짚엔실리지 제조방법'은 그동안 한우를 키우는 농가에서 집 근처에 볏짚을 쌓고 비닐로 덮고 질소가스를 주입한 후 자체발열로 발효되면서 질소 성분이 볏짚에 스며들도록 한 것과 최근의 곤포볏짚은 단순히 곰팡이를 억제시키는 것인데 내면에 공간이 형성된 볏짚과 보릿짚과 밀짚 등은 옥수수겉대와 달리 속이 비어 있기 때문에 발효할 때 호기성발효로 살이 썩는 것처럼 고약한 냄새로 인해 주민이 사는 동네에서는 도저히 발효시킬 수 없는 발효조사료 재료들을 속이 꽉 찬 옥수수겉대처럼 발효시키려는 엔실리지 제조공법에 속하는 발명이다,이미 곤포포장을 발효시키는 방법은 널리 알여져 있으나 속이 빈 볏짚을 옥수수겉대처럼 발효시키려면 속을 으깨도 보릿짚보다는 발효시킬 때 냄새는 덜 나지만 역시 발효시킨 엔실리지로는 적절하지 못하기 때문에 보조 재료를 첨가하여 악취 없는 옥수수겉대와 같은 발효엔실리지로 제조하는 발효공법에 관한 것이다, 이와 같이 볏짚엔실리지로 제조할 수 있다면 그동안 일반농가에서 기피하는 옥수수재배 대신에 논에서 곤포 등으로 깔 짚으로 전용하던 볏짚을 고품질의 볏짚 엔실리지로 가공할 수 있게 되어 젖소 및 비육우사육농가의 사료 확보에 어려움을 덜 수 있게 하면서 농가수익도 높이는 효과가 기대되는 발명이다,[색인어]볏짚엔실리지, 보릿짚엔실리지, 옥수수겉대엔실리지, 유산용액(乳酸溶液), 탈지미강(脫脂米糠), 강피류(糠皮類), 반추가축(反芻家畜), 곤포(梱包), 톤포(),헤이레이지(haylage), claims: 벼를 수확한 일반볏짚(60) 또는 보리를 수확한 보릿짚을 볏짚수거차(14)로 수거하여 볏짚절단기(12)로 세절시킨 절단볏짚(50) 또는 절단보릿짚(52)을 지정비율로 혼합 또는 단독으로 배합장치(40)에 담아 일정량의 밀기울(30), 또는 보릿겨(32), 또는 탈지미강(34)을 혼합 또는 단독으로 첨가하고 수분함량에 따라 유산용액(20)을 추가 첨가하여 상기 배합장치로 일정시간 배합하는 도중 잠시 정지하여 일정량의 제올라이트(24)와 요소사료(22)를 추가하고 배합이 종료되면 1톤 용적량의 톤포(10)에 담아 톤포볏짚(70)으로 소분하고 발효장소에 상기 톤포볏짚을 다수개로 적재한 후 일정기간 발효시켜 발효볏짚(62)으로 제조되는 것이 특징인 볏짚엔실리지 제조방법, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

924/1059 Row 924: application_number: 1020210044596, combined_string: invention_title: 한우 경매가 예측 서버, 및 이를 이용한 한우 경매가 예측 방법 abstract: 본 발명은 한우 경매가 예측 서버, 및 이를 이용한 한우 경매가 예측 방법에 관한 것으로, 특히 사용자 단말로부터 기준 마커가 부착된 한우 개체 이미지를 수신하여 기준 마커를 인식하고 기준 마커 내의 4개 영역의 색상을 추출하여 원본 마커의 색상과 비교하여 색상 값 오차를 획득하고, 이 색상 값 오차를 이용하여 한우 개체 이미지의 색상을 변환하고, 색상 변환된 한우 개체 이미지로부터 한우 인식 이미지를 생성한 후 한우 선형 심사기준에 의거하여 선형 심사점수를 계산하고, 선형 심사점수 계산시 사용한 변수인 체고 및 체장을 기초로 체중을 계산하며, 이 선형 심사점수 및 체중과 과거 한우 경매가 판정 정보간 유사도를 계산하여 한우 경매가를 산출한 후 사용자 단말에 제공해주는 한우 경매가 예측 서버, 및 이를 이용한 한우 경매가 예측 방법에 관한 것이다. claims: 크기 및 색상 정보가 공개되어 있고 내부에 서로 다른 색상을 갖는 4개의 사각형 영역이 배치되어있는 사각형의 기준 마커를 측면에 부착한 한우 개체를 촬영하여 얻어진 한우 개체 이미지를 사용자 단말로부터 수신하도록 구성된 한우 개체 이미지 수신부;상기 기준 마커를 인식하여 상기 기준 마커 내의 4개의 사각형 영역의 색상을 추출하여서 저장하도록 구성된 기준 마커 인식부;추출된 상기 4개의 사각형 영역의 색상과 원본 마커의 색상을 비교하여 색상 값 오차를 획득하고, 이 색상 값 오차를 이용하여 상기 한우 개체 이미지의 색상을 변환하도록 구성된 이미지 색상 변환부;색상 변환된 상기 한우 개체 이미지로부터 한우 인식 이미지를 생성하도록 구성된 한우 개체 인식부;한우 선형 심사기준을 기초로 상기 한우 인식 이미지에 대한 선형 심사점수를 계산하고, 상기 선형 심사점수 계산시 사용한 변수인 체고 및 체장을 기초로 체중을 계산하며, 상기 사용자 단말의 선형 심사점수 및 체중 계산 결과 확인 후 저장하도록 구성된 한우 외모 정보 인식부; 및상기 선형 심사점수 및 체중과 과거 한우 경매가 판정 정보 간 유사도를 계산하여 한우 경매가를 산출한 후 상기 사용자 단말에 상기 한우 경매가 및 체중 정보를 제공하도록 구성된 경매가 산출부;를 포함하고,상기 한우 개체 인식부는표준 한우 피모색 범위의 RGB 값을 로딩하여 설정 개수로 구분하고;상기 이미지 색상 변환부에 의해 변환된 한우 개체 이미지에서 표준 한우 피모색 범위의 RGB 값에 속하는 RGB 값을 상기 설정 개수만큼 검출하며;검출된 상기 설정 개수의 RGB 값을 갖는 색상을 각각 상기 변환된 한우 개체 이미지에 오버레이(overlay)하여 상기 설정 개수의 한우 개체 이미지를 생성하며;생성된 상기 설정 개수의 한우 개체 이미지를 부위별로 분할하여 부위별로 상기 설정 개수의 이미지를 생성하고 상기 사용자 단말에 제공하며;상기 사용자 단말이 생성된 상기 부위별 설정 개수의 이미지 중에서 부위별로 하나의 이미지를 선택하면, 선택된 상기 부위별 이미지를 통합하여 A타입의 한우 인식 이미지를 생성하고 상기 사용자 단말에 제공하며; 상기 사용자 단말에 의해 상기 A타입 한우 인식 이미지가 확인되면, 상기 A타입 한우 인식 이미지를 저장하고;상기 사용자 단말에 의해 상기 A타입 한우 인식 이미지가 확인되지 않으면, 한우 모양의 한우 가이드 라인 이미지를 로딩하고, 상기 한우 가이드 라인 이미지를 상기 변환된 한우 개체 이미지의 크기에 맞추어 크기 조절 및 매핑하여 B타입의 한우 인식 이미지를 생성하고 저장하는 한우 경매가 예측 서버.한우 경매가 예측 서버를 이용한 한우 경매가 예측 방법으로서,상기 한우 경매가 예측 서버가, 크기 및 색상 정보가 공개되어 있고 내부에 서로 다른 색상을 갖는 4개의 사각형 영역이 배치되어있는 사각형의 기준 마커를 측면에 부착한 한우 개체를 촬영하여 얻어진 한우 개체 이미지를 사용자 단말로부터 수신하는 한우 개체 이미지 수신 단계;상기 한우 경매가 예측 서버가 상기 기준 마커를 인식하여 상기 기준 마커 내의 4개의 사각형 영역의 색상을 추출하여서 저장하는 기준 마커 인식 단계;상기 한우 경매가 예측 서버가 추출된 상기 4개의 사각형 영역의 색상과 원본 마커의 색상을 비교하여 색상 값 오차를 획득하고, 이 색상 값 오차를 이용하여 상기 한우 개체 이미지의 색상을 변환하는 이미지 색상 변환 단계;상기 한우 경매가 예측 서버가 색상 변환된 상기 한우 개체 이미지로부터 한우 인식 이미지를 생성하는 한우 개체 인식 단계;상기 한우 경매가 예측 서버가 한우 선형 심사기준을 기초로 상기 한우 인식 이미지에 대한 선형 심사점수를 계산하고, 상기 선형 심사점수 계산시 사용한 변수인 체고 및 체장을 기초로 체중을 계산하며, 상기 사용자 단말의 선형 심사점수 및 체중 계산 결과 확인 후 저장하는 한우 외모 정보 인식 단계; 및상기 한우 경매가 예측 서버가 상기 선형 심사점수 및 체중과 과거 한우 경매가 판정 정보 간 유사도를 계산하여 한우 경매가를 산출한 후 상기 사용자 단말에 상기 한우 경매가 및 체중 정보를 제공하는 경매가 산출 단계;를 포함하고, 상기 한우 개체 인식 단계는상기 한우 경매가 예측 서버가 표준 한우 피모색 범위의 RGB 값을 로딩하여 설정 개수로 구분하는 단계;상기 한우 경매가 예측 서버가 상기 이미지 색상 변환 단계에서 변환된 한우 개체 이미지에서 표준 한우 피모색 범위의 RGB 값에 속하는 RGB 값을 상기 설정 개수만큼 검출하는 단계;상기 한우 경매가 예측 서버가 검출된 상기 설정 개수의 RGB 값을 갖는 색상을 각각 상기 변환된 한우 개체 이미지에 오버레이(overlay)하여 상기 설정 개수의 한우 개체 이미지를 생성하는 단계;상기 한우 경매가 예측 서버가 생성된 상기 설정 개수의 한우 개체 이미지를 부위별로 분할하여 부위별로 상기 설정 개수의 이미지를 생성하고 상기 사용자 단말에 제공하는 단계;상기 사용자 단말이 생성된 상기 부위별 설정 개수의 이미지 중에서 부위별로 하나의 이미지를 선택하면, 상기 한우 경매가 예측 서버가 선택된 상기 부위별 이미지를 통합하여 A타입의 한우 인식 이미지를 생성하고 상기 사용자 단말에 제공하는 단계; 및상기 사용자 단말에 의해 상기 A타입 한우 인식 이미지가 확인되면, 상기 한우 경매가 예측 서버가 상기 A타입 한우 인식 이미지를 저장하는 단계;를 포함하며,상기 사용자 단말에 의해 상기 A타입 한우 인식 이미지가 확인되지 않으면,상기 한우 경매가 예측 서버가 한우 모양의 한우 가이드 라인 이미지를 로딩하는 단계; 및상기 한우 경매가 예측 서버가 상기 한우 가이드 라인 이미지를 상기 변환된 한우 개체 이미지의 크기에 맞추어 크기 조절 및 매핑하여 B타입의 한우 인식 이미지를 생성하고 저장하는 단계;를 포함하는 한우 경매가 예측 방법., Ltext: 농업, prediction: 임업
925/1059 Row 925: application_number: 1020210043301, combined_string: invention_title: 오미자 줄기의 추출물을 유효성분으로 하는, 육질 개선을 위한 가축 급이용 조성물 및 그 제조방법 abstract: 본 발명은 오미자 부산물의 추출물을 유효성분으로 하는, 육질개선을 위한 가축 급이용 조성물 및 그 제조방법에 관한 것이다. 본 발명의 가축 급이용 조성물은, 줄기를 포함하는 오미자 부산물의 추출물을 유효성분으로 하며, 가축 사료나 음수에 첨가하거나 따로 급이함으로써 육질 내 단백질, 아미노산 및 불포화 지방산 함량을 높일 수 있다. claims: 오미자 줄기의 추출물을 유효성분으로 하며, 육질 내 불포화 지방산 함량은 높이고 포화지방산 함량은 낮추되, 상기 불포화 지방산은 올레산(Oleic acid)을 포함하는 것을 특징으로 하는, 육질 내 단백질 및 불포화 지방산 함량을 높이기 위한 가축 급이용 조성물. 제1항 내지 제3항 중 어느 한 항의 가축 급이용 조성물을 소에게 1개월 이상 급이하는 것을 포함하는, 육질 내 단백질 및 불포화 지방산 함량을 높이기 위한 소 사육방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

926/1059 Row 926: application_number: 1020210042403, combined_string: invention_title: 자외선살균램프를 이용한 친환경 축사 청소 및 소독 살균 자동화 시스템과 그 방법 abstract: [기술분야/해결과제]본 발명은 친환경 축사 청소 및 소독 살균 자동화 시스템과 그 방법에 관한 것으로, 돈방(20) 사이에 설치된 돈방 칸막이(102)를 상승하여 개방시킨 후 한쪽 돈방(20)으로 돼지를 이동시킨 다음 상기 돈방 칸막이(102)를 하강하여 격리시킨 후, 돼지가 비어있는 돈방(20)의 바닥에 소독살균제를 분사하여 소독한 후 고압수로 세척하고 UV-C 자외선으로 소독 살균함으로써, 병균과 해충이 없고 악취가 없는 위생적 사육관리로 돼지의 생산성을 높이고 작업능률을 높일 수 있으며 쾌적한 사육환경을 조성할 수 있다.[해결수단]본 발명에 의한 친환경 축사 청소 및 소독 살균 자동화 방법은, (a) 돈방(20) 사이의 돈방 칸막이(102)를 상승시키되 상기 돈방 칸막이(102)에 연결된 와이어줄을 리프터장치(160)로 감아서 상기 돈방 칸막이(102)를 상승시켜 돈방(20)을 개방하는 단계; (b) 상기 개방한 돈방(20)의 어느 한쪽으로 돼지가 이동된 후, 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시켜 돼지를 한쪽의 돈방(20)에 격리시키는 단계; (c) 상기 돈방(20)의 상부에서 소독살균 리프터장치(180)가 하강한 후 상기 소독살균 리프터장치(180)의 하단에 설치된 소독살균제 분사기(190)에서 소독살균제가 상기 돼지가 비어있는 돈방(20)에 분사되어 소독하는 단계; (d) 상기 돼지가 비어있는 돈방(20)의 벽면에 설치된 고압수 분사기(170)에서 고압수가 분사되어 바닥을 세척하는 단계; (e) 상기 소독살균 리프터장치(180)의 하단에 설치된 자외선 살균램프(200)에서 상기 돼지가 비어있는 돈방(20)에 UV-C 자외선이 소정시간 조사되어 살균하는 단계; (f) 상기 소독살균 리프터장치(180)가 원위치로 상승한 후 상기 돼지가 비어있는 돈방(20)을 자연 건조하거나 송풍기로 건조하는 단계; 및 (g) 상기 살균 및 건조된 돈방(20)과 상기 돼지가 있는 돈방(20) 사이의 돈방 칸막이(102)를 상기 리프터장치(160)로 상승하여 개방한 후 상기 살균 및 건조된 돈방(20)으로 돼지가 이동된 다음 상기 돈방 칸막이(102)를 하강하여 상기 돈방(20)을 분리시키고, 상기 (c) 내지 (f) 단계를 진행하여 상기 돈방(20)을 청소와 소독 및 살균 건조하는 단계;를 포함한다.[기대효과]본 발명에 따르면, 병균과 해충이 없고 악취가 없는 위생적 사육관리로 돼지의 생산성을 높이고 작업능률을 높일 수 있으며 쾌적한 사육환경을 조성할 수 있다. claims: 친환경 축사 청소 및 소독 살균 자동화 방법에 있어서,(a) 돈방(20) 사이의 돈방 칸막이(102)를 상승시키되 상기 돈방 칸막이(102)에 연결된 와이어줄을 리프터장치(160)로 감아서 상기 돈방 칸막이(102)를 상승시켜 돈방(20)을 개방하는 단계;(b) 상기 개방한 돈방(20)의 어느 한쪽으로 돼지가 이동된 후, 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시켜 돼지를 한쪽의 돈방(20)에 격리시키는 단계;(c) 상기 돈방(20)의 상부에서 소독살균 리프터장치(180)가 하강한 후 상기 소독살균 리프터장치(180)의 하단에 설치된 소독살균제 분사기(190)에서 소독살균제가 상기 돼지가 비어있는 돈방(20)에 분사되어 소독하는 단계;(d) 상기 돼지가 비어있는 돈방(20)의 벽면에 설치된 고압수 분사기(170)에서 고압수가 분사되어 바닥을 세척하는 단계;(e) 상기 소독살균 리프터장치(180)의 하단에 설치된 자외선 살균램프(200)에서 상기 돼지가 비어있는 돈방(20)에 UV-C 자외선이 소정시간 조사되어 살균하는 단계;(f) 상기 소독살균 리프터장치(180)가 원위치로 상승한 후 상기 돼지가 비어있는 돈방(20)을 자연 건조하거나 송풍기로 건조하는 단계; 및(g) 상기 살균 및 건조된 돈방(20)과 상기 돼지가 있는 돈방(20) 사이의 돈방 칸막이(102)를 상기 리프터장치(160)로 상승하여 개방한 후 상기 살균 및 건조된 돈방(20)으로 돼지가 이동된 다음 상기 돈방 칸막이(102)를 하강하여 상기 돈방(20)을 분리시키고, 상기 (c) 내지 (f) 단계를 진행하여 상기 돈방(20)을 청소와 소독 및 살균 건조하는 단계;를 포함하며,상기 소독살균제는, 액상소석회를 사용하며,상기 액상소석회는물(H2O)과 생석회(CaO)가 70∼80중량% : 20∼30중량%의 비율로 혼합된 액상소석회(Ca(OH)2)에 이온화 미네랄 입자 3∼5중량%, 시안산나트륨(NaOCN) 0.5∼1.0중량%, 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 및 입도 100∼200메쉬의 숯 분말 5∼10중량%가 혼합된,친환경 축사 청소 및 소독 살균 자동화 방법.친환경 축사 청소 및 소독 살균 자동화 시스템에 있어서,돈방(20) 사이에 설치된 돈방 칸막이(102)를 상승하여 개방시키고, 상기 돈방 칸막이(102)를 하강하여 상기 돈방(20)을 분리시키는 리프터장치(160);상기 돈방(20)의 벽면에 설치되며, 돼지가 비어있는 돈방(20)에 고압수를 분사하여 바닥을 세척하는 고압수 분사기(170);상기 돈방(20)의 상부에 승하강하도록 설치되며, 상기 돈방(20)의 소정 높이까지 하강하여 소독 및 살균하고 상승하는 소독살균 리프터장치(180);상기 소독살균 리프터장치(180)의 하단 양쪽에 설치되며, 돼지가 비어있는 돈방(20)에 소독살균제를 분사하는 소독살균제 분사기(190);상기 소독살균 리프터장치(180)의 하단에 설치되며, 돼지가 비어있는 돈방(20)에 UV-C 자외선을 소정시간 조사하여 살균하는 자외선 살균램프(200); 및상기 리프터장치(160)를 작동하여 상기 돈방 칸막이(102)를 상승시키고 한쪽 돈방(20)으로 돼지가 이동된 후 상기 돈방 칸막이(102)를 하강하여 상기 돈방(20)을 분리시키고, 상기 소독살균 리프터장치(180)를 작동하여 상기 돈방(20)의 소정 높이까지 하강시키고 상기 소독살균제 분사기(190)를 작동하여 소독살균제를 분사하고, 상기 돼지가 비어있는 돈방(20)에 설치된 고압수 분사기(170)를 작동하여 고압수로 세척하고, 상기 자외선 살균램프(200)를 작동하여 UV-C 자외선으로 소독 살균하는 시스템의 동작을 제어하는 제어부(110);를 포함하는 친환경 축사 청소 및 소독 살균 자동화 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

927/1059 Row 927: application_number: 1020210042406, combined_string: invention_title: 축사 소독용  UV-LED 소독 살균 장치와 그 방법 abstract: [기술분야/해결과제]본 발명은 축사 소독용 UV-LED 소독 살균 장치와 그 방법에 관한 것으로, 돈방 사이의 돈방 칸막이를 상승하여 한쪽 돈방으로 돼지를 이동시킨 후 돈방 칸막이를 하강하여 돼지를 격리시킨 다음, 돼지가 비어있는 돈방의 바닥면에는 소독살균제를 분사하여 소독하고 고압수로 세척한 다음 UV-C 자외선으로 소독 살균하고, 돼지가 있는 돈방에는 가시광선 또는 UV-A 자외선을 조사하여 돼지를 소독 살균하는 축사 소독용 UV-LED 소독 살균 장치와 그 방법에 관한 것이다.[해결수단]본 발명에 의한 축사 소독용 UV-LED 소독 살균 방법은, (a) 돈방 사이의 돈방 칸막이(102)에 와이어줄을 연결하여 리프터장치(160)로 감아서 상기 돈방 칸막이(102)를 상승시켜 돈방을 개방하는 단계; (b) 상기 개방한 돈방의 어느 한쪽으로 돼지가 이동된 후, 상기 돼지를 한쪽의 돈방에 격리시키기 위해 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시키는 단계; (c) 상기 돈방의 상부에서 소독살균 리프터장치(180)가 하강하고, 상기 소독살균 리프터장치(180)의 하단에 설치된 소독살균제 분사기(190)에서 상기 돼지가 비어있는 돈방의 바닥면으로 소독살균제를 분사시켜 소독하는 단계; (d) 상기 돈방의 벽면에 설치된 고압수 분사기(170)에서 상기 돼지가 비어있는 돈방의 바닥면으로 고압수를 분사시켜 바닥면을 세척하는 단계; (e) 상기 소독살균 리프터장치(180)의 하단에 설치된 UV-C 발광소자(200)에서 상기 돼지가 비어있는 돈방의 바닥면에 UV-C 자외선을 조사하여 살균하고, 상기 소독살균 리프터장치(180)의 하단에 설치된 가시광선 발광소자(201)에서 상기 돼지가 있는 돈방에 가시광선을 조사하여 돼지를 살균하는 단계; (f) 상기 소독살균 리프터장치(180)가 원위치로 상승한 후 상기 돼지가 비어있는 돈방을 자연 건조하거나 송풍기로 건조하는 단계; 및 (g) 상기 돈방 사이의 돈방 칸막이(102)를 상기 리프터장치(160)로 상승하여 개방한 후 살균 및 건조된 돈방으로 돼지가 이동된 다음, 상기 돼지를 한쪽의 돈방에 격리시키기 위해 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시키고, 상기 (c) 내지 (f) 단계를 진행하여 돈방을 소독 및 살균하는 단계;를 포함한다.[기대효과]본 발명에 따르면, 병균과 해충이 없고 악취가 없는 위생적 사육관리로 돼지의 생산성을 높이고 작업능률을 높일 수 있으며 쾌적한 사육환경을 조성할 수 있다. claims: 축사 소독용 UV-LED 소독 살균 방법에 있어서,(a) 돈방 사이의 돈방 칸막이(102)에 와이어줄을 연결하여 리프터장치(160)로 감아서 상기 돈방 칸막이(102)를 상승시켜 돈방을 개방하는 단계;(b) 상기 개방한 돈방의 어느 한쪽으로 돼지가 이동된 후, 상기 돼지를 한쪽의 돈방에 격리시키기 위해 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시키는 단계;(c) 상기 돈방의 상부에서 소독살균 리프터장치(180)가 하강하고, 상기 소독살균 리프터장치(180)의 하단에 설치된 소독살균제 분사기(190)에서 상기 돼지가 비어있는 돈방의 바닥면으로 소독살균제를 분사시켜 소독하는 단계;(d) 상기 돈방의 벽면에 설치된 고압수 분사기(170)에서 상기 돼지가 비어있는 돈방의 바닥면으로 고압수를 분사시켜 바닥면을 세척하는 단계;(e) 상기 소독살균 리프터장치(180)의 하단에 설치된 UV-C 발광소자(200)에서 상기 돼지가 비어있는 돈방의 바닥면에 UV-C 자외선을 조사하여 살균하고, 상기 소독살균 리프터장치(180)의 하단에 설치된 가시광선 발광소자(201)에서 상기 돼지가 있는 돈방에 가시광선을 조사하여 돼지를 살균하는 단계; (f) 상기 소독살균 리프터장치(180)가 원위치로 상승한 후 상기 돼지가 비어있는 돈방을 자연 건조하거나 송풍기로 건조하는 단계; 및(g) 상기 돈방 사이의 돈방 칸막이(102)를 상기 리프터장치(160)로 상승하여 개방한 후 살균 및 건조된 돈방으로 돼지가 이동된 다음, 상기 돼지를 한쪽의 돈방에 격리시키기 위해 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시키고, 상기 (c) 내지 (f) 단계를 진행하여 돈방을 소독 및 살균하는 단계; 를 포함하는 축사 소독용 UV-LED 소독 살균 방법.축사 소독용 UV-LED 소독 살균 장치에 있어서,돈방 사이에 설치된 돈방 칸막이(102)를 상승하여 개방시키고, 상기 돈방 칸막이(102)를 하강하여 상기 돈방을 분리시키는 리프터장치(160);상기 돈방의 벽면에 설치되며, 돼지가 비어있는 돈방에 고압수를 분사하여 바닥을 세척하는 고압수 분사기(170);상기 돈방의 상부에 승하강하도록 설치되며, 상기 돈방의 소정 높이까지 하강하여 소독 및 살균하고 상승하는 소독살균 리프터장치(180);상기 소독살균 리프터장치(180)의 하단 양쪽에 설치되며, 상기 돼지가 비어있는 돈방에 소독살균제를 분사하는 소독살균제 분사기(190);상기 소독살균 리프터장치(180)의 하단에 설치되며, 상기 돼지가 비어있는 돈방에 UV-C 자외선을 소정시간 조사하여 살균하는 UV-C 발광소자(200);상기 소독살균 리프터장치(180)의 하단에 설치되며, 상기 돼지가 있는 돈방에 가시광선을 소정시간 조사하여 돼지를 살균하는 가시광선 발광소자(201); 및상기 리프터장치(160)를 작동하여 상기 돈방 칸막이(102)를 상승시켜 상기 돈방을 개방시키고, 한쪽 돈방으로 돼지가 이동된 후 상기 돈방 칸막이(102)를 하강하여 상기 돈방을 분리시키고, 상기 소독살균 리프터장치(180)를 작동하여 상기 돈방의 소정 높이까지 하강시키고 상기 소독살균제 분사기(190)를 작동하여 소독살균제를 분사하고, 상기 돼지가 비어있는 돈방에 설치된 고압수 분사기(170)를 작동하여 바닥면을 고압수로 세척하고, 상기 UV-C 발광소자(200)를 작동하여 UV-C 자외선으로 상기 돼지가 비어있는 돈방의 바닥면을 살균하고, 상기 가시광선 발광소자(201)를 작동하여 가시광선으로 돼지를 살균하는 동작을 제어하는 제어부(110);를 포함하는 축사 소독용 UV-LED 소독 살균 장치., Ltext: 농업, prediction: 임업
928/1059 Row 928: application_number: 1020210033404, combined_string: invention_title: 질산염 제거 시스템 및 이에 포함되는 탈질 여과조 abstract: 본 명세서에 개시된 내용은 박테리아에 먹이를 공급하여 질산염을 지속적으로 제거하는 질산염 제거 시스템 및 이에 포함되는 탈질 여과조의 제공에 관한 것이다.본 명세서에 개시된 내용의 일 실시예에 따르면, 질산염 제거 시스템은 수조의 사육수가 유입되는 제1 공간을 구획하는 제1 격벽을 포함하는 유입부, 상기 제1 격벽의 타측에 형성되는 제1 여과부 및 상기 제1 여과부의 타측에 형성되어 상기 수조로 상기 사육수를 배출하는 배출부를 포함하는 탈질 여과조 및 상기 제1 여과부에 박테리아 먹이를 피딩하도록 형성된 피딩부를 포함하고, 상기 피딩부는 상기 제1 격벽의 타측 일부공간을 둘러싸고 통로가 형성되는 구획판에 의해 구비된 먹이투입공간으로 상기 먹이를 투입한다. claims: 용기 형태의 본체, 상기 본체의 일측 내부에서 수조의 사육수가 유입되는 제1 공간을 구획하는 제1 격벽을 포함하는 유입부, 상기 제1 격벽의 타측에 형성되는 제1 여과부 및 상기 제1 여과부의 타측에 형성되어 상기 수조로 상기 사육수를 배출하는 배출부를 포함하는 탈질 여과조; 및상기 제1 여과부에 박테리아 먹이를 피딩하도록 형성된 피딩부;를 포함하고,상기 피딩부는 상기 제1 격벽의 타측 일부공간을 둘러싸고 통로가 형성되는 구획판에 의해 구비된 먹이투입공간으로 상기 먹이를 투입하며,상기 유입부는 상기 제1 격벽보다 높게 연장된 사각판 형태로 형성되어 상기 제1 격벽의 전방에 배치되고, 상기 제1 공간 및 타측에 형성된 제2 공간을 서로 분리시키는 제2 격벽을 더 포함하며,상기 제1 여과부는, 상기 제2 격벽과 동일한 형태로 형성되고 상기 제2 격벽의 타측에 연결되는 제1 구획판, 상기 제1 구획판에 연결되고 전방으로 연장되어상기 제2 공간의 내부에서 상기 먹이투입공간인 제3 공간을 구획하는 제2 구획판 및 상기 제1 격벽보다 높이가 낮고 상기 제2 구획판의 타측에 이격 배치되는 제3 격벽을 포함하며,상기 제1 구획판에는, 상기 제1 구획판의 상부 일부분이 상기 본체의 바닥과 이격된 위치까지 하부로 소정의 거리만큼 함몰되어 상기 제2 및 제3 공간을 연결하는 제1 통로가 형성되는 것을 특징으로 하는 질산염 제거 시스템.용기 형태의 본체;상기 본체의 일측 내부에서 수조의 사육수가 유입되는 제1 공간을 구획하는 제1 격벽 및 펌프가 형성되는 유입부;상기 제1 격벽의 타측에 형성되고 박테리아가 서식되는 제1 여과부;상기 제1 여과부의 타측에 형성되고 박테리아가 서식되는 제2 여과부;상기 제1 및 제2 여과부에 배치되는 여과재; 및상기 제2 여과부의 타측에 배치되고 상기 본체에 형성된 배출구를 통해 외부와 연결되는 배출부;를 포함하며,상기 유입부는 상기 제1 격벽보다 높게 연장된 사각판 형태로 형성되어 상기 제1 격벽의 전방에 배치되고, 상기 제1 공간 및 타측에 형성된 제2 공간을 서로 분리시키는 제2 격벽을 더 포함하며,상기 제1 여과부는, 상기 제2 격벽과 동일한 형태로 형성되고 상기 제2 격벽의 타측에 연결되는 제1 구획판, 상기 제1 구획판에 연결되고 전방으로 연장되어상기 제2 공간의 내부에서 먹이투입공간인 제3 공간을 구획하는 제2 구획판 및 상기 제1 격벽보다 높이가 낮고 상기 제2 구획판의 타측에 이격 배치되는 제3 격벽을 포함하며,상기 제1 구획판에는, 상기 제1 구획판의 상부 일부분이 상기 본체의 바닥과 이격된 위치까지 하부로 소정의 거리만큼 함몰되어 상기 제2 및 제3 공간을 연결하는 제1 통로가 형성되는 것을 특징으로 하는 탈질 여과조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

929/1059 Row 929: application_number: 1020210019185, combined_string: invention_title: 질소가스와 유산 용액을 주입하여 제조되는 곤포발효볏짚 abstract: 본 발명의 '질소가스와 유산 용액을 주입하여 제조되는 곤포발효볏짚'은 그동안 한우를 키우는 농가에서 집 근처에 볏짚을 쌓고 비닐로 덮고 질소가스를 주입한 후 자체발열로 발효되면서 질소성분이 볏짚에 스며들도록 한 방법으로 이용해 왔는데 이러한 방법은 자신의 키우는 소 이외에 이웃농가에 줄 수는 있으나 장거리 이송은 불가능하여 이동이 어려운 발효볏짚을 장거리까지 공급할 수 있도록 곤포로 포장시키고 포장된 곤포볏짚에 질소가스와 미량광물수용액으로 조성되는 유산 용액을 주입하여 곤포발효볏짚으로 제조하므로 밀폐된 체 장거리이송도 가능하게 하는 사료분야의 가공기술에 속한다,곤포로 포장을 하면 접착성을 갖는 비닐 랩으로 4 내지 6겹을 둘러 곤포를 형성시키므로 포장된 곤포에 질소가스와 유산 용액을 주입할 수 없기 때문에 곤포로 제조한 다음에 둥근면의 정 가운데에 작은 주입 공을 만들고 주입기를 삽입하여 일정량의 질소가스와 유산 용액을 주입한 후 접착테이프로 주입 공을 막고 뒤집어 밑면으로 위치시켜 적재 해 놓으면 일정기간 질소 흡수와 유산균 발효가 진행되고 일단 진행된 후는 스스로 발효를 유지하므로 장기보관이 가능하게 하는 방법이다,곤포볏짚은 볏짚이 속이 비어 있어서 질소가스 주입이 가능하고 이에 따라 유산균을 주입하지 아니해도 유산 용액에 의해 유산균이 증식하므로 질소성분으로 우수한 비단백태질소사료로 제조되면 반추동물에게는 비싼 단백질사료를 급여하지 아니해도 충분한 단백질사료로 대체할 수 있게 되어 사육농가의 사료비를 줄이면서 사육농가의 수익을 높이는 효과가 기대되는 발명이다, [색인어]곤포(梱包), 질소가스, 유산 용액, 볏짚사료, 단백질사료,반추동물, 곤포발효볏짚, 비단백태질소사료(非蛋白態窒素詞科), claims: 벼를 수확한 남은 볏짚(50)을 결속시켜 볏짚 롤(60)로 엮고, 곤포포장장치로 상기 볏짚 롤을 곤포용 비닐로 여러 겹을 감아 제조된 곤포(10)를, 상기 곤포의 윗면 또는 아랫면 정중앙에 곤포주입 공(12)을 만들고, 상기 곤포주입 공에 주입기(30)를 삽입하여 일정량의 질소가스(22) 또는 사료용 요소(24)와 유산 용액(20)을 주입하고, 상기 주입기 삽입으로 형성된 상기 곤포주입 공을 대형테이프(40)로 막은 상기 곤포들을 노지 일 측에 모아 보온덮개(70)로 덮고 일정기간 발효시켜 제조되는 것이 특징인 질소가스와 유산 용액을 주입하여 제조되는 곤포발효볏집, Ltext: 농업, prediction: 임업
930/1059 Row 930: application_number: 1020210011745, combined_string: invention_title: 유해물질 유입 차단이 가능한 작업등용 전구 소켓 구조 abstract: 본 발명은 각종 산업현장이나, 가축을 사육하는 축사등에서 사용하는 작업등용 전구 소켓에 관한 것이다.본 발명은 전구가 장착되어지는 전구 소켓 내부로로 유해물질인 분진이나 가축의 배설물로 인해 발생하는 메탄가스 등이 유입되어 발생하는 누전에 의한 감전 사고는 물론, 전구 소켓을 구성하는 전도체의 부식이 가속화되어 사용수명이 현저하게 줄어드는 폐단을 해결할 수 할 수 있도록 한 관한 것이다. claims: 백열전구형 전구(1)의 나사전극(2)이 나사식 결합되어 전기적으로 도통하는 소켓나사전극관(10)이 내측으로 위치하고, 상기 백열전구형 전구(1)의 전구중심전극(3)이 전기적으로 도통하도록 접촉되어지는 소켓중심전극편(21)이 장착되어지는 소켓중심전극장착부재(20)가 상부로 위치하여 있는 소켓나사전극관장착부재(30)의 내구성보강환테(31)에 유해물질차단러버(100)가 장착 구성되어 지되, 상기 유해물질차단러버(100)는 상하로 도통되어 속이빈 형태로 측단면의 둘레벽(140) 형상이 반구형으로 하부 말단에는 소켓나사전극관장착부재(30)의 내측으로 위치한 소켓나사전극관(10)에 전구(1)의 나사전극(2)이 나사결합되어질때 전구(1)의 숄더(4)에 압박됨과 동시에 내측으로 말려 오므려지는 탄성변형이 일어나면서 상기 전구(1)와 소켓(1000) 사이에 공극이 없이 기밀되어질 수 있도록 하는 탄성변형부(110)가 형성되어 있고, 상부의 고정부(120) 내측면에는 소켓나사전극관장착부재(30)의 내구성보강환테(31)에 장착되어지는 장착환홈(130)이 형성되어 있는 것을 특징으로 하는 유해물질 유입 차단이 가능한 작업등용 전구 소켓 구조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

931/1059 Row 931: application_number: 1020200181641, combined_string: invention_title: 혈통정보 및 유전정보 육종가를 이용한 한우 암소의 활용 유형 결정 시스템 abstract: 본원은 한우 암소의 혈통정보 및 유전정보 육종가를 사용하여 암소를 육질형 송아지 생산 용도, 육량형 송아지 생산 용도, 및 비육출하 또는 수정란 대리모 용도로 조기에 판정하는 시스템을 개시한다. 본원은 혈통+유전 통합 정보를 활용하여 단독 정보 활용보다 수익성을 높였다. 본원에 따른 시스템을 이용하면 태어나는 송아지의 사양 방법을 임신시기에 결정하여 맞춤형 정밀사양을 적용할 수 있고, 암소의 활용도를 높이고, 개정된 쇠고기 등급제에 활용하게 되어 한우 산업의 효율 증진을 도모할 수 있다. claims: 한우 암소 표준집단의 근내지방도 및 도체중을 포함하는 혈통 정보 육종가를 구축 및 관리하는 표준집단의 혈통 정보기반 육종가 관리부; 한우 암소 표준집단의 근내지방도 및 도체중을 포함하는 유전 정보 육종가를 구축 및 관리하는 표준집단의 유전 정보기반 육종가 관리부;대상 한우 암소의 근내지방도 및 도체중에 대한 혈통 정보 육종가를 분석하는, 대상 한우 암소의 혈통 정보기반 육종가 분석부; 대상 한우 암소의 근내지방도 및 도체중에 대한 유전 정보 육종가를 분석하는, 대상 한우 암소의 유전 정보기반 육종가 분석부; 상기 대상 한우 암소의 상기 혈통 정보기반 육종가 분석부의 상기 근내지방도 및 도체중의 혈통 정보 육종가를 상기 표준집단의 상응하는 혈통 정보기반 육종가 관리부의 육종가와 비교하여, 상기 대상 한우 암소의 상기 근내지방도 및 도체중의 혈통 정보 기반 육종가의 누적 백분위를 산출하는, 대상 한우 암소의 혈통 정보기반 육종가 누적 백분위 산출부; 상기 대상 한우 암소의 상기 유전 정보기반 육종가 분석부의 상기 근내지방도 또는 도체중의 유전 정보 육종가를 상기 표준집단의 상응하는 유전 정보기반 육종가 관리부의 육종가와 비교하여, 상기 대상 한우 암소의 상기 근내지방도 및 도체중의 유전 정보 기반 육종가의 누적 백분위를 산출하는, 대상 한우 암소의 유전 정보기반 육종가 누적 백분위 산출부; 및상기 혈통 정보기반 육종가 누적 백분위 산출부 및 상기 유전 정보기반 육종가 누적 백분위 산출부에 의해 산출된 상기 대상 한우 암소의 근내지방도 및 도체중의 누적 백분위 정보를 이용하여 상기 대상 한우 암소의 활용 유형을 분류하는 활용 유형 적용부를 포함하며, 상기 활용 유형 적용부에서는 상기 혈통 정보기반 근내지방도 육종가, 혈통 정보기반 도체중 육종가, 유전 정보기반 근내지방도 육종가 및 유전 정보기반 도체중 육종가의 누적 백분위가 미리 정한 기준으로 순차적으로 적용되어 상기 대상 한우 암소는 (i) 육질형 송아지 생산 암소; (ii) 육량형 송아지 생산 암소; 또는 (iii) 암소비육 또는 수정란 대리모로 분류되며, 상기 미리 정한 기준은 (a) 대상 한우의 상기 혈통 정보기반 근내지방도 육종가의 누적 백분위가 상위 70%에 해당; 상기 혈통 정보기반 근내지방도 육종가의 누적 백분위가 상위 70%에 해당되지 않는 경우, 상기 혈통 정보기반 도체중 육종가의 누적 백분위가 상위 30%에 해당되지 않음; 또는 상기 혈통 정보기반 도체중 육종가의 누적 백분위가 상위 30%에 해당되는 경우, 상기 유전 정보기반 근내지방도 육종가가 상위 70%에 해당될 때 상기 (i) 육질형 송아지 생산 암소로 분류되고, (b) 상기 (a)에서 상기 유전 정보기반 근내지방도 육종가가 상위 70%에 해당하지 않는 경우, 상기 유전 정보기반 도체중 육종가가 상위 30%에 해당될 때 상기 (ii) 육량형 송아지 생산 암소로 분류되고, (c) 상기 (b)에서 상기 유전 정보기반 도체중 육종가가 상위 30%에 해당되지 않을 때 (iii) 암소비육 및 수정란 대리모 암소로 분류되는, 한우 암소 활용 유형 분류 시스템., Ltext: 농업, prediction: 임업
932/1059 Row 932: application_number: 1020200163602, combined_string: invention_title: 깊이 영상카메라 및 소리 센서를 활용한 모돈의 발정기 및 수정적기 판단 시스템 abstract: 본 발명은 모돈의 수정 적기를 판단하기 위해 깊이 영상카메라 및 소리 센서로 모돈의 발정기를 탐지하고 수정적기를 판단하는 시스템으로서, 복수의 모돈의 발정 여부를 관찰하기 위해 돈사 내에 모돈을 사육하는 스톨의 천장에 설치되어 상기 모돈의 움직임을 촬영 및 저장하는 깊이 영상카메라; 상기 깊이 영상카메라에서 촬영된 영상을 분석하는 영상분석기를 포함하며, 상기 영상분석기에는 상기 모돈의 수정적기를 판단하기 위한 딥러닝 기반의 수정적기 판단 소프트웨어가 포함되어 있는 것을 특징으로 한다. 본 발명에 따라 모돈의 발정기를 탐지하고 수정 적기를 판단함으로써, 발정 미감지에 따른 피해를 최소화 하여 돈사의 생산성을 극대화 할 수 있으며, 실시간으로 발정기를 자동 탐지함으로써 투입되는 노동력을 절감할 수 있다. claims: 모돈의 수정 적기를 판단하기 위해 깊이 영상카메라 및 소리 센서로 모돈의 발정기를 탐지하고 수정적기를 판단하는 시스템에 있어서,복수의 모돈의 발정 여부를 관찰하기 위해 돈사 내에 모돈을 사육하는 스톨의 천장에 설치되어 상기 모돈의 움직임을 촬영 및 저장하는 깊이 영상카메라; 상기 깊이 영상카메라에서 촬영된 영상을 분석하는 영상분석기를 포함하며,상기 영상분석기에는 상기 모돈의 수정적기를 판단하기 위한 딥러닝 기반의 수정적기 판단 소프트웨어가 포함되고,상기 딥러닝 기반의 수정적기 판단 소프트웨어는, 딥러닝 학습을 통해 학습데이터에서 설정된 기준에서 일정 범위를 벗어나는 분석값을 나타낼 때 이상상황으로 탐지하고 상기 모돈의 수정적기 판단에 활용하는 이상상황 탐지 모듈를 더 포함하며, 상기 이상상황 탐지 모듈은 인공지능 신경망 모델을 사용하되, 신경망 학습에 있어서 부족한 데이터를 사전 제작된 페이크 영상데이터 및 페이크 소리데이터로 대체하고, 비지도 학습 신경망 모델의 GAN(Generative Adversarial Nets)을 학습에 적용하여 상기 딥러닝 학습데이터 기준에서 소정의 수치 범위를 벗어나는 것으로 판단될 때, 상기 모돈이 발정시기인 것으로 판단하는 것을 특징으로 하는 깊이 영상카메라 및 소리 센서를 활용한 모돈의 발정기 및 수정적기 판단 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

933/1059 Row 933: application_number: 1020200148936, combined_string: invention_title: 비타민 A의 급여에 의한 한우 육량 및 육질의 개선 방법 abstract: 본 발명은 비타민 A의 급여에 의한 한우 육량 및 육질의 개선 방법에 관한 것으로, 더욱 상세하게는 어린 송아지 시기에 비타민 A를 경구로 추가 급여함으로써 한우 육량 및 육질을 개선하는 방법에 관한 것이다. claims: 비타민 A을 2개월 경까지 송아지에 급여하는 단계;를 포함하는, 한우 육량 및 육질의 개선 방법., Ltext: 농업, prediction: 임업
934/1059 Row 934: application_number: 1020200089286, combined_string: invention_title: 플라스틱(아크릴)을 성형하여 만든 외장재 및 온실의 제작법 abstract: 본 발명에 의한 플라스틱을 둥근접시모양으로 성형하여 결합한 외부 마감재는 외부에서 오는 열을 넓게 흡수하여 내부에서도 넓게 분배하며 공기층을 가지고 있어, 온도의 보존율이 좋다. 또한 간단한 시공법 및 지속적인 소모품 및 유지에 필요한 전기가 필요없기 때문에 효율성이 좋아지며 식물을 식재하는 농장에서는 사육환경이 개선되며 원가절감을 얻을 수 있는 효과가 있다. claims: 플라스틱(아크릴)을 둥근 접시모양으로 성형하고, 이를 결합하여 건축물의 외부마감재로 사용하는 방식, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

935/1059 Row 935: application_number: 1020200081094, combined_string: invention_title: 동물용 연속주사기 보조장치 abstract: 본 발명은 소 등의 가축이나 사육되는 동물에게 예방 또는 치료용 주사약물를 투약할 때, 원거리에서 다수의 동물들에게 안전하고 신속하게 주사약물을 투약할 수 있도록, 상용의 연속주사기를 장착하여 사용할 수 있도록 구성된 동물용 연속주사기 보조장치에 관한 것으로, 익스텐션 튜브(100); 헤드 어댑터(200); 전방 연장관(500, 500´); 및 주사기 장착관(600, 600´);을 포함하는 연속주사기 연장모듈(2, 2´)로 이루어져 있다. 또한, 본 발명의 보조장치는 상기 연속주사기 연장모듈(2, 2´)이 장착되는 연장모듈 장착관(700, 700´) 및 가압부(800, 800´)를 포함하는 연속주사기 가압모듈(3, 3´)이 추가로 구비하고, 동물들과 다양한 거리에서 안전하고 신속한 주사를 투약할 수 있도록 구성되어 있다. claims: 연속주사기(10)를 장착하여 원거리에서 동물에게 주사약물을 투약할 수 있도록 상기 연속주사기(10)의 전방에 장착되는 연속주사기 연장모듈(2, 2')과 연속주사기 가압모듈(3, 3´)을 포함하는 동물용 연속주사기 보조장치에 있어서, 상기 연속주사기 연장모듈(2, 2´)은 익스텐션 튜브(100); 헤드 어댑터(200); 전방 연장관(500, 500´); 주사기 장착관(600, 600´); 및 제1 고정부재(650,650´)를 포함하고, 상기 익스텐션 튜브(100)는 상기 전방 연장관(500, 500´)에 삽입되어 있고, 상기 익스텐션 튜브(100)의 전방 결합단(110)은 상기 헤드 어댑터(200)를 매개로 상기 전방 연장관(500, 500´)의 전방 단부에 결합되며, 상기 전방 연장관(500, 500´)은 상기 주사기 장착관(600, 600´)에 삽입되어 결합되고, 제1 고정부재(650, 650´)는 전방 연장관(500, 500´)과 상기 주사기 장착관(600, 600´)을 서로 고정시킬 수 있도록 구성되어 있으며, 상기 주사기 장착관(600, 600´)은 연속주사기(10)의 주사기 손잡이(13)는 후방에 노출된 상태에서 상기 연속주사기(10)의 주사기 몸체(12)를 지지하도록 구성되어 있으며, 상기 연속주사기 가압모듈(3, 3´)은 연장모듈 장착관(700, 700´)과 가압부(800, 800´)를 포함하고, 상기 연장모듈 장착관(700, 700´)은 상기 연속주사기 연장모듈(2, 2´)이 장착되는 연장모듈 거치부(710, 710´); 상기 연장모듈 거치부(710, 710´)의 상부에 형성된 연장모듈 삽입공(720, 720´); 및 상기 연장모듈 거치부(710. 710´)의 하부에 형성된 연속주사기 손잡이 삽입공(740, 740´)을 포함하고 있고, 상기 연장모듈 장착관(700, 700´)의 전방은 상기 주사기 장착관(600, 600´)과 결합되며,상기 가압부(800, 800´)는 상기 연장모듈 장착관(700, 700´)의 후방에 결합되어 있는 것을 특징으로 하는 동물용 연속주사기 보조장치., Ltext: 농업, prediction: 임업
936/1059 Row 936: application_number: 1020200076121, combined_string: invention_title: 가축사용 벌레 퇴치 LED살균 조명등 abstract: 본 발명은 가축사용 벌레퇴치 LED살균 조명등에 관한 것으로서, 가축사의 공기를 LED살균하며 벌레를 퇴치시켜 가축사육 환경이 쾌적하게 유지되도록 함을 목적으로 한 것이다.즉, 본 발명은 가축사의 천장에 매달아 가축사의 공기와 가축을 살균하며 벌레를 퇴치하는 가축사용 벌레퇴치 LED살균 조명등을 구비한 것을 특징으로 하는 것이다.따라서, 본 발명은 UVLED를 통하여 가축사의 공기를 LED살균하며 음파발생전원부에 발생되는 벌레퇴치 음파신호를 통하여 벌레를 퇴치시켜 가축사육 환경이 쾌적하게 유지되는 효과를 갖는 것이다. claims: 가축사의 천장에 매달아 가축사의 공기와 가축을 살균하며 벌레를 퇴치하는 가축사용 벌레퇴치 LED살균 조명등을 구비하되,상기 벌레퇴치 LED살균 조명등은 판상으로 형성되는 등몸체와 상기 등몸체의 하부에 UV를 조사하여 공기와 가축을 살균할 수 있게 UVLED소자가 실장된 UVLED등부, 상기 등몸체의 상부에 UVLED소자에서 발열된 열을 공기 중으로 방출시킬 수 있게 구비한 방열부, 상기 방열부의 상부에 스위칭소자에 의하여 전압을 조절 출력하고 벌레퇴치를 위한 음파신호를 출력할 수 있게 구비한 음파발생전원부, 상기 방열부에 음파발생전원부에서 출력되는 음파신호에 따라 공기 중을 벌레퇴치소리를 발산시킬 수 있게 구비한 음파출력부 및 상기 등몸체의 하부에 UVLED등부에서 발산되는 빛이 하부로 집중 조사되게 하고 음파출력부에 의하여 방열부으로 전달된 벌레퇴치음을 하부로 확산 발산시킬 수 있게 구비한 음파방사갓으로 구성하며;상기 UVLED등부는 원형 판상의 LED보드와 상기 LED보드에 실장되는 UVLED소자로 이루어진 2 개 UVLED부로 구성되고;상기 UVLED부는 49개의 UVLED소자가 직렬배선되게 실장되어 형성되며;상기 UVLED소자에는 조사되는 UV가 가축사 중앙부에 공기에 집중 작용되게 조사점을 조절하는 중앙조사렌즈부를 구비하며;상기 방열부는 등몸체에 결합되는 방열몸체와 상기 방열몸체에서 핀형으로 돌출되어 열을 노치 방열하는 방열부으로 구성되며, 방열부과 방열부 사이에 형성되는 방열공 사이의 방열몸체 상단은 누적된 먼지가 음파출력부의 진동에 의하여 흘러 배출되게 중앙에서 외측으로 경사지게 형성하고;상기 음파발생전원부는 외부의 전원이 입력되는 전원입력부와 상기 전원입력부에서 입력된 전원을 스위칭 전압조절을 위하여 20~50Khz 전압조절발진부, 상기 전압조절발진부에서 발진된 20~50Khz 발진 주파수에 의하여 벌레퇴치를 위한 퇴치음 동작신호를 출력할 수 있게 구비한 벌레퇴치음파출력부, 상기 전압조절발진부에서 발진된 발진 주파수에 따라 스위칭 동작하여 입력된 전원을 단속하여 출력할 수 있게 구비한 전압조절스위칭부, 상기 전압조절스위칭부에 의하여 구형파로 출력되는 전원을 평활하여 설정된 전압으로 조절할 수 있게 구비한 전압평활부, 상기 전압평활부에서 평활화된 전원을 출력할 수 있게 구비한 전원출력부 및 상기 각 구성의 동작을 제어하여 전압이 조절되어 출력할 수 있게 구비하며;방열부의 상부 측에는 UVLED등에 의하여 살균된 가축사 중앙부의 공기가 가축사의 가축에게 작용될 수 있게 송풍장치를 구비한 전원제어부로 구성한 것을 특징으로 하는 가축사용 벌레퇴치 LED살균 조명등., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

937/1059 Row 937: application_number: 1020200056193, combined_string: invention_title: 가변형 가축 사육시설 abstract: 본 발명은 가축의 사육 공간이 변형 가능한 가축용 스톨에 관한 것이다. 본 발명에 따른 가축용 스톨은, 가축을 수용하기 위해 소정 방향으로 오픈된 수용 공간을 갖도록 제공된 고정틀; 상기 고정틀의 일측에 배치되며 상기 고정틀의 상기 소정 방향으로 이동 가능한 유동성 틀; 및 상기 유동성 틀의 일측에 제공되며 상기 오픈된 수용 공간을 개폐하는 후면 차단기를 포함하고, 상기 유동성 틀의 상기 소정 방향 이동에 따라 상기 수용 공간의 크기가 변형된다. 이에 따라, 가축의 자유로운 움직임을 조절하여 효율적인 가축 사육이 가능하다. claims: 가축을 수용하기 위해 소정 방향으로 오픈된 수용 공간을 갖도록 제공된 고정틀;상기 고정틀의 일측에 배치되며 상기 고정틀의 상기 소정 방향으로 이동 가능한 유동성 틀; 및상기 유동성 틀의 일측에 제공되며 상기 오픈된 수용 공간을 개폐하는 후면 차단기를 포함하고,상기 유동성 틀의 상기 소정 방향 이동에 따라 상기 수용 공간의 크기가 변형되는 가축용 스톨., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

938/1059 Row 938: application_number: 1020200050682, combined_string: invention_title: 건축물 에너지 절약 시스템, 그리고 이를 위한 건축물 에너지 관리 서버 abstract: 본 발명은 건축물 에너지 절약 시스템에 관한 것이다. 본 발명은, 복수의 스마트 디바이스(100)로 이루어진 스마트 디바이스 그룹(100g), 네트워크(200), 건축물 에너지 관리 서버(300), 복수의 스마트 제어 유닛(400)으로 이루어진 스마트 제어 유닛 그룹(400g)을 포함하는 건축물 에너지 절약 시스템(1)에 있어서, 스마트 제어 유닛(400)은, 지중에 매립된 복수 개의 파이프로 구성될 수 있으며, 파이프로부터 연장된 지열관을 따라 냉각 또는 가열을 수행하며, 냉각 작동시 냉각형 열교환을 위한 보조 열교환 단위 유닛으로부터 보조적으로 냉각 작용을 제공받으며, 가열 작동시 가열형 열교환을 위한 보조 열교환 단위 유닛으로부터 보조적으로 가열 작용을 제공받으며, 냉각 작동과 가열 작동에 따라 구분된 영역을 활용하여 각기 다른 냉각 펌프(410a) 및 히트 펌프(410b)에 의해 축냉 탱크(440) 및 축열 탱크(450)에 냉기 및 열기를 제공하는 지중열교환기(410); 냉난방 운전이 가능한 공조기로 냉방운전을 수행하기 위해 공기와 냉매간에 열교환을 수행하여 축열된 냉매의 열에너지를 응축기와 연결된 축냉 탱크(400)로 냉각 펌프(420a)를 활용해 제공하며, 난방운전을 수행하기 위해 공기와 냉매간의 열교환을 수행하여 축열된 냉매의 열에너지를 기화기와 연결된 축열 탱크(500)로 히트 펌프(420b)를 활용해 제공하는 공기열교환기(420); 외부의 액체 파이프로부터 제공된 냉기를 냉각 히트 펌프를 통해 축냉 탱크(440)로 제공하며, 외부의 액체 파이프로부터 제공된 온기를 온열 히트 펌프를 축열 탱크(450)로 제공할 수 있으며, 냉각 작동과 가열 작동에 따라 구분된 영역을 활용하여 각기 다른 냉각 펌프(430a) 및 히트 펌프(430b)에 의해 축냉 탱크(440) 및 축열 탱크(450)에 냉기 및 열기를 제공하는 수열교환기(430); 냉각 회전 튜브(440a)와 사이에 형성된 냉각 히트 펌프를 통해 건축물의 미리 설정된 구역으로 냉기를 제공함으로써, 미리 설정된 구역에 대한 온도 상승을 억제하도록 하는 냉각 기능을 제공하는 축냉 탱크(440); 온열 회전 튜브(450a)와 사이에 형성된 온열 히트 펌프를 통해 건축물의 미리 설정된 구역으로 온기를 제공함으로써, 미리 설정된 구역에 대한 온도 하락을 억제하도록 하는 온열 기능을 제공하는 축열 탱크(450); 및 제 1 온도센싱단(491a), 제 2 온도센싱단(492a), 냄새 센싱단(493a) 및 온습도센싱단(494a)을 포함하며, 제 1 온도센싱단(491a)은 축냉 탱크(440) 내부에 열매와 맞닿아 형성되며, 제 2 온도센싱단(492a)은 축열 탱크(450) 내부에 냉매에 맞닿아 형성되며, 온습도센싱단(494a)은 건축물의 미리 설정된 구역의 지정된 위치에 형성되는 센싱부(490a); 를 포함하며, 각 스마트 디바이스(100)에 의해 하나 이상의 스마트 제어 유닛(400)에 대한 건축물 에너지 관리 서버(300)로의 등록 이후에 각 스마트 제어 유닛(400)에 대한센싱부(490a)를 통해 센싱된 제 1 온도센싱단(491a)에 의해 측정된 제 1 온도센싱정보, 제 2 온도센싱단(492a)에 의해 측정된 제 2 온도센싱정보에 따라 축냉 탱크(440) 및 축열 탱크(450)에 의한 열교환에 의해 온도를 유지할 뿐만 아니라, 축냉 탱크(440) 및 축열 탱크(450)를 열-전기에너지 변환 단위 유닛(400u)으로 구성함으로써, 변환된 전기 에너지로 스마트 제어 유닛(400)의 구성요소에 대한 전력을 공급하는 것을 특징으로 할 수 있다.이에 의해, 건축물 용도별 에너지 사용량을 시간에 따라 분리하여 냉방, 난방, 급탕 등의 운전을 선택함으로써, 에너지를 절약하도록 할 뿐만 아니라, 건축물이 축사 및 돈사 등인 경우, 축사 및 돈사 등의 냄새 및 일정 온도 유지하도록 하는 효과를 제공할 뿐만 아니라, 축냉 탱크 및 축열 탱크를 열-전기에너지 변환 단위 유닛으로 구성함으로써, 에너지 효율을 높일 뿐만 아니라, 축냉 탱크와 축열 탱크의 온도를 미리 설정된 온도 범위로 자동으로 제어되면서도 에너지 효율을 향상시킬 수 있는 효과를 제공할 수 있다. claims: 복수의 스마트 디바이스(100)로 이루어진 스마트 디바이스 그룹(100g), 네트워크(200), 건축물 에너지 관리 서버(300), 복수의 스마트 제어 유닛(400)으로 이루어진 스마트 제어 유닛 그룹(400g), 그리고 빅데이터 서버(500)를 포함하는 건축물 에너지 절약 시스템(1)에 있어서, 스마트 제어 유닛(400)은, 지중열교환기(410), 공기열교환기(420), 수열교환기(430), 축냉 탱크(440), 냉각 회전 튜브(440a), 축열 탱크(450), 온열 회전 튜브(450a), 급기팬(460), 펠티어소자(470), 약품분사기(480), 센싱부(490a), 컨트롤러(490b), 송수신 안테나(490c)를 포함하며, 지중열교환기(410)는,지중에 매립된 복수 개의 파이프로 구성될 수 있으며, 파이프로부터 연장된 지열관을 따라 냉각 또는 가열을 수행하며, 냉각 작동시 냉각형 열교환을 위한 보조 열교환 단위 유닛으로부터 보조적으로 냉각 작용을 제공받을 수 있으며, 가열 작동시 가열형 열교환을 위한 보조 열교환 단위 유닛으로부터 보조적으로 가열 작용을 제공받으며, 냉각 작동과 가열 작동에 따라 구분된 영역을 활용하여 각기 다른 냉각 펌프(410a) 및 히트 펌프(410b)에 의해 축냉 탱크(440) 및 축열 탱크(450)에 냉기 및 열기를 제공하며,공기열교환기(420)는,냉난방 운전이 가능한 공조기로 냉방운전을 수행하기 위해 공기와 냉매간에 열교환을 수행하여 축열된 냉매의 열에너지를 응축기와 연결된 축냉 탱크(400)로 냉각 펌프(420a)를 활용해 제공하며, 난방운전을 수행하기 위해 공기와 냉매간의 열교환을 수행하여 축열된 냉매의 열에너지를 기화기와 연결된 축열 탱크(500)로 히트 펌프(420b)를 활용해 제공하며,수열교환기(430)는,외부의 액체 파이프로부터 제공된 냉기를 냉각 히트 펌프를 통해 축냉 탱크(440)로 제공하며, 외부의 액체 파이프로부터 제공된 온기를 온열 히트 펌프를 축열 탱크(450)로 제공할 수 있으며, 냉각 작동과 가열 작동에 따라 구분된 영역을 활용하여 각기 다른 냉각 펌프(430a) 및 히트 펌프(430b)에 의해 축냉 탱크(440) 및 축열 탱크(450)에 냉기 및 열기를 제공하며,축냉 탱크(440)는,냉각 회전 튜브(440a)와 사이에 형성된 냉각 히트 펌프를 통해 건축물의 미리 설정된 구역으로 냉기를 제공함으로써, 미리 설정된 구역에 대한 온도 상승을 억제하도록 하는 냉각 기능을 제공하며,축열 탱크(450)는,온열 회전 튜브(450a)와 사이에 형성된 온열 히트 펌프를 통해 건축물의 미리 설정된 구역으로 온기를 제공함으로써, 미리 설정된 구역에 대한 온도 하락을 억제하도록 하는 온열 기능을 제공하며,급기팬(460)은,건축물의 미리 설정된 구역에 대한 외부와의 공기 교환을 위한 팬에 해당하며,펠티어소자(470)는,미리 설정된 구역에서 특수한 목적을 위해 세부 온도 조절이 필요한 설정 영역에 대한 냉온 온도 조절, 급냉 온도 설정을 위해 사용되기 위해 형성되며, 설정 영역에 대한 외부 전력을 이용해 컨트롤러(490b)의 제어에 따라 온도 조절을 수행하며, 온열 회전 튜브(450a)가 형성된 건축물 상에서 온수를 공급하는 급수탱크의 벽면에 형성되며, 모듈 형태로 펠티어 소자와 급수탱크 표면의 온도센서, 아두이노 기판을 활용하여 미리 설정된 온도 범위로 급수탱크에 대한 온도를 제어하며, 약품분사기(480)는,컨트롤러(490b)에 의해 미리 설정된 구역에 대한 냄새가 난다고 센싱부(490a)에 의해 센싱된 경우 천연 방향제를 분사하기 위해 형성되며,센싱부(490a)는,제 1 온도센싱단(491a), 제 2 온도센싱단(492a), 냄새 센싱단(493a) 및 온습도센싱단(494a)을 포함하며, 제 1 온도센싱단(491a)은 축냉 탱크(440) 내부에 열매와 맞닿아 형성되며, 제 2 온도센싱단(492a)은 축열 탱크(450) 내부에 냉매에 맞닿아 형성되며, 냄새 센싱단(493a) 및 온습도센싱단(494a)은 건축물의 미리 설정된 구역의 지정된 위치에 형성되며, 컨트롤러(490b)는, 스마트 제어 유닛(400)을 구성하는 각 구성요소에 대한 제어를 수행할 뿐만 아니라, 송수신 안테나(490c)를 통해 네트워크(200)와 연결된 건축물 에너지 관리 서버(300), 각 스마트 디바이스(100), 빅데이터 서버(500)와 신호 및 데이터 송수신을 수행하며, 건축물 에너지 관리 서버(300)는, 송수신부(310), 제어부(320) 및 데이터베이스(330)를 포함하며, 제어부(320)는 센싱 모듈(321), 에너지 순환 모듈(322), 온도 컨트롤 모듈(323), 공기 컨트롤 모듈(324) 및 피드백 컨트롤 모듈(325)을 포함하며, 센싱 모듈(321)은,각 스마트 제어 유닛(400)의 센싱부(490a) 중 축냉 탱크(440)에 형성된 제 1 온도센싱단(491a)와 축열 탱크(450)에 형성된 제 2 온도센싱단(492a)으로부터 각각 제 1 온도센싱정보 및 제 2 온도센싱정보를 수신하도록 송수신부(310)를 제어한 뒤, 실시간 시간 정보와 제 1 및 제 2 온도센싱정보를 데이터베이스(330)에 각 스마트 제어 유닛(400)의 식별번호를 메타데이터로 저장하며, 각 스마트 제어 유닛(400)의 센싱부(490a) 중 미리 설정된 구역에 형성된 온습도센싱단(494a)으로부터 미리 설정된 구역의 제 3 온도센싱정보 외에 습도 정보를 네트워크(200)를 통해 수신하도록 송수신부(310)를 제어한 뒤, 제 3 온도센싱정보 외에 습도 정보를 제 1 및 제 2 온도센싱정보와 함께 각 스마트 제어 유닛(400)의 식별번호를 메타데이터로 저장하며,센싱부(490a) 중 건축물의 미리 설정된 구역에 형성된 배출되는 가스를 제공받아서 가스의 화학성분을 센싱(sensing)하는 냄새 센싱단(493a)로부터 수신된 정보를 이용하여 냄새 발생여부를 분석한 뒤, 냄새 발생여부 정보를 제 1 및 제 2 온도센싱정보, 제 3 온도센싱정보 및 습도 정보와 함께 각 스마트 제어 유닛(400)의 식별번호를 메타데이터로 함께 모니터링 정보 단위로 저장하며,에너지 순환 모듈(322)은,각 스마트 제어 유닛(400)의 식별번호와 매칭되어 저장된 스마트 디바이스(100)의 단말식별번호(IMEI)를 추출한 뒤, 단말식별번호에 해당하는 스마트 디바이스(100)로 모니터링 정보 단위를 네트워크(200)를 통해 전송하도록 송수신부(310)를 제어하며, 스마트 디바이스(100)로부터 미리 설정된 구역에 대한 제 1 내지 제 3 온도센싱정보에 따른 시간대별 온도구축 정보를 네트워크(200)를 통해 수신하도록 송수신부(310)를 제어한 뒤, 스마트 디바이스(100)의 단말식별번호를 메타데이터로 함께 데이터베이스(330)에 저장하며,온도 컨트롤 모듈(323)은, 제 1 온도센싱정보가 미리 설정된 축냉 탱크 온도 범위 미만인 경우, 축냉 탱크 온도 범위로부터 미리 설정된 온도를 초과하는 냉매(冷媒)를 축냉 탱크(440)로 공급함과 동시에 축냉 탱크(440)와 연결된 배출 밸브에 대한 제어를 통해 냉매(冷媒)에 대한 외부로의 배출이 수행되도록 함으로써, 제 1 온도센싱정보가 축냉 탱크 온도 범위에 속하도록 제어하며, 제 1 온도센싱정보가 미리 설정된 축냉 탱크 온도 범위 미만이고, 제 2 온도센싱정보가 미리 설정된 축열 탱크 온도 범위를 초과하는 경우, 축냉 탱크(440)에서 축열 탱크(450)로의 냉매(冷媒) 제공과 함께 축냉 탱크 온도 범위로부터 미리 설정된 온도를 초과하는 새로운 냉매(冷媒)를 축냉 탱크(440)로 공급을 통해 제 1 온도센싱정보가 축냉 탱크 온도 범위에 속하도록 제어하며, 온도 컨트롤 모듈(323)은,제 1 온도센싱정보가 미리 설정된 축냉 탱크 온도 범위를 초과하는 경우, 지중열교환기(410), 공기열교환기(420) 및 수열교환기(430) 중 현재 냉각 펌프(410a, 420a, 430a)와 히트 펌프(410b, 420b, 430b) 중 히트 펌프(410b, 420b, 430b)가 동작하는 것이 있는 경우 히트 펌프(410b, 420b, 430b)에 대해서 중단시키고, 히트 펌프(410b, 420b, 430b)가 중단된 열교환기(410, 420, 430)와 연결된 냉각 펌프(410a, 420a, 430a)가 동작하도록 제어함으로써, 축냉 탱크 온도 범위 내로 속할 때까지 온도 제어를 수행함으로써, 축, Ltext: 농업, prediction: 임업
939/1059 Row 939: application_number: 1020200047011, combined_string: invention_title: 한우 암소의 반추위 내 체온 변화를 이용한 임신 판정방법 abstract: 본 발명은 한우 암소의 반추위 내 체온 변화를 이용한 임신 판정방법에 관한 것으로, 보다 상세하게는, 본 발명은 ICT 기술을 활용하여 인공수정된 한우 암소의 임신기간 중 반추위 내 체온 변화를 분석함으로써 임신가능성 또는 임신유지 여부를 판정할 수 있을 뿐만 아니라 반추위 내 체온 변화로부터 분만을 예측할 수 있다. claims: 한우 암소의 반추위에 삽입된 온도 센서 장치를 이용하여 인공수정된 암소의 반추위 내 체온 변화를 측정하여 암소의 임신가능성 또는 임신유지 여부를 판정하는 단계를 포함하고,상기 임신가능성 또는 임신유지 여부를 판정하는 단계는 한우 암소의 반추위 내 온도가 38.665 내지 38.679℃인 경우 인공수정일로부터 임신 80 내지 100일령, 38.775 내지 38.795℃인 경우 임신 145 내지 165일령, 38.996 내지 39.016℃인 경우 임신 200 내지 220일령 및 39.136 내지 39.116℃인 경우 임신 250 내지 270일령으로 결정하는 것인, 한우 암소의 임신가능성 또는 임신유지 여부의 판정방법.한우 암소의 반추위에 삽입된 온도 센서 장치를 이용하여 임신한 한우 암소의 반추위 내 체온 변화를 측정하고, 인공수정일로부터 임신 200 내지 220일령 또는 임신 250 내지 270일령의 한우 암소의 반추위 내 온도가 각각 38.996 내지 39.016℃ 또는 39.136 내지 39.116℃의 범위 이하로 떨어져 1일 이상 유지하는 경우 분만 가능성이 있는 것으로 예측하는 단계를 포함하는, 한우 암소의 분만 예측방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

940/1059 Row 940: application_number: 1020200042087, combined_string: invention_title: 볏짚 공급기 abstract: 본 발명은 축산농가의 소 사육에 필요한 원형 볏짚(곤포 사일리지)을 자동으로 공급하는 볏짚 공급기에 관한 것으로, 보다 상세하게는 축사팬스 전방에 설치되어 원형 볏짚을 지지하되, 원형 볏짚의 압축 상태가 불규칙함에도 불구하고 자연스럽게 미끄러지며 소가 볏짚을 원활하게 취식할 수 있도록 공급하고, 개폐장치에 개폐시간을 입력하면 자동으로 볏짚 제공 시간을 조절하여 볏짚이 과잉으로 공급되어 발생할 수 있는 손실을 막을 수 있으며, 볏짚이 소진될때까지 노동력을 최소한으로 줄일 수 있는 볏짚 공급기에 관한 것이다. claims: 축사팬스(1) 전방에 고정설치되고, 소머리가 유입되는 개방부(110)와, 상기 개방부(110) 상부에 폐쇄부(120)를 형성하는 전면프레임(100)과;상기 전면프레임(100)의 개방부(110) 하부에서 후방으로 돌출되는 내부면(210)과, 상기 내부면(210)에서 상향경사지는 경사면(220)과, 상기 경사면(220)을 지면으로부터 지지하는 받침부(230)로 이루어져 상기 경사면(220)에서 원형 볏짚(10)의 일측면과 맞닿아 원형 볏짚(10)을 지지하는 바닥프레임(200)과;상기 전면프레임(100)의 폐쇄부(120)와 상기 바닥프레임(200)의 경사면(220)에 결합되고 세로방향으로 연장설치되되 하나 이상의 절곡부(330)를 형성하는 다수개의 창살이 이격형성되어 창살사이로 원형 볏짚(10)이 공급되는 공급프레임(300);을 포함하되;상기 전면프레임(100)의 폐쇄부(120)에는 원형 볏짚(10)의 일측면이 일정각도를 유지하면서 접촉되도록 상부로 갈수록 폭이 넓어지는 접촉부(130)이 돌출형성되는 볏짚 공급기., Ltext: 농업, prediction: 임업
941/1059 Row 941: application_number: 1020200021373, combined_string: invention_title: IoT제어 및 AC-LED 디밍시스템을 구비한 에너지절감형 스마트 축산사료재배공장 abstract: 본 발명에서는 겨울철 소등 가축들을 위한 목초를 대신할 신선 조사료를 제공하는 조사료 스마트팜 장치를 제공하고자 한다. 이를 위하여, 도어를 구비한 컨테이너; 및 상기 컨테이너 내부 좌우로 배치된 다단재배베드; 및 상기 다단재배베드 중앙에 구비된 통로; 및 상기 다단재배베드의 칸칸이 구비된 관수노즐 및 LED 조명부; 및 상기 다단재배베드에 구비된 재배트레이; 및 상기 컨테이너에 구비된 2개 이상의 온습도 센서; 및 상기 관수노즐과 연결되고, 상기 컨테이너 외부에 구비된 수조; 및 상기 수조를 냉각시키기 위한 냉각기; 및 상기 수조에서 나온 물의 온도를 높이기 위한 가열부; 및 상기 LED 조명부의 광량을 조절하기위한 광제어부를 구비한 것을 특징으로 하는 IoT제어 및 AC-LED 디밍시스템을 구비한 에너지절감형 스마트 축산사료재배공장을 제공한다.상기와 같은 구성에 의하여, 20피트 컨테이너의 경우 매일 500Kg씩 새싹보리를 수확할 수 있고, 40피트 컨테이너의 경우 매일 1000Kg씩 새싹보리를 수확할 수 있는 IoT제어 및 AC-LED 디밍시스템을 구비한 에너지절감형 스마트 축산사료재배공장을 개발하였다. 상기와 같은 장치에 의하여 연 중 매일 500~1000Kg의 신선 조사료를 생산할 수 있는 수단을 제공함으로써, 목초 조차 재배할 수 없는 환경에서 소 등의 가축을 사육할 수 있는 수단을 제공하는 효과가 있다. claims: 도어를 구비한 컨테이너; 및상기 컨테이너 내부 좌우로 배치된 다단재배베드; 및상기 다단재배베드 중앙에 구비된 통로; 및상기 다단재배베드의 칸칸이 구비된 관수노즐 및 LED 조명부; 및상기 다단재배베드에 구비된 재배트레이; 및상기 컨테이너에 구비된 2개 이상의 온습도 센서; 및상기 관수노즐과 연결되고, 상기 컨테이너 외부에 구비된 수조; 및상기 수조를 냉각시키기 위한 냉각기; 및상기 수조에서 나온 물의 온도를 높이기 위한 가열부; 및상기 LED 조명부의 광량을 조절하기위한 광제어부를 구비한 것을 특징으로 하는 IoT제어 및 AC-LED 디밍시스템을 구비한 에너지절감형 스마트 축산사료재배공장., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

942/1059 Row 942: application_number: 2020200000513, combined_string: invention_title: 카프스트롱 - 음수용 abstract: 본 고안은 송아지를 사육하는 농가에 설치하여 송아지에게 우유, 물 등을원활하게 공급하는데에 목적이 있다.또한, 수시로 젖꼭지를 소독하기 위해 젖꼭지 부분의 분리를쉽게 할 수 있도록 설계 하였다.파이프에 고정하여 사용하는 파이프걸이(1),단단히 고정할 수 있는 장착끈구멍(2,3),바닥에 두었을 때 수평이 유지될 수 있는 하부지지대(5),편리하게 들어 이동이 용이한 손잡이(6),D형볼트(7), O형너트(8), 젖꼭지(9)와 와셔를 결합하여 사용하는 것을 포함하여서 제작된 것이다. claims: 카프스트롱 - 음수용 {CALF STRONG} 은 파이프에 고정하여 사용하는 파이프걸이(1), 단단히 고정할 수 있는 장착끈구멍(2,3),바닥에 두었을 때 고정할수 있는 하부지지대(5),편리하게 들어 이동이 용이한 손잡이(6),D형볼트(7), O형너트(8), 젖꼭지(9)와 와셔를 결합하여 사용하는 것을 특징으로하는 카프스트롱 - 음수용 {CALF STRONG} 이다., Ltext: 농업, prediction: 임업
943/1059 Row 943: application_number: 1020200017628, combined_string: invention_title: 육질 개선 및 단기비육용 사료, 및 이를 이용한 한우의 비육방법 abstract: 본 발명은 육질 개선 및 단기비육용 사료, 및 이를 이용한 한우의 비육방법에 관한 것이다. 보다 상세하게는 본 발명은 한우의 사양 단계별로 최적의 사료를 개발하고, 이를 한우에 급여함으로써 한우의 육질 개선 및 비육기간을 단축시키고, 사료비용을 절감할 수 있는, 육질 개선 및 단기비육용 사료, 및 이를 이용한 한우의 비육방법에 관한 것이다. claims: 한우 거세우의 사양 단계를 6 ~ 13 개월령, 14 ~ 22 개월령 및 23 ~ 28 개월령으로 나누어 급여하는 사료로서, 상기 6 ~ 13 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 3 ~ 5 : 7 ~ 5의 중량% 비율로 포함되고, 상기 14 ~ 22 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 1 ~ 3 : 9 ~ 7의 중량% 비율로 포함되며, 상기 23 ~ 28 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 0.5 ~ 1.5 : 9.5 ~ 8.5의 중량% 비율로 포함되는, 한우 거세우의 육질 개선 및 단기비육용 사료.한우 거세우의 사양 단계를 6 ~ 13 개월령, 14 ~ 22 개월령 및 23 ~ 28 개월령으로 나누어 단계별로 영양성분이 상이한 사료를 한우 거세우에게 급여하는 한우거세우의 비육방법으로서,상기 6 ~ 13 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 3 ~ 5 : 7 ~ 5의 중량% 비율로 포함되고, 상기 14 ~ 22 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 1 ~ 3 : 9 ~ 7의 중량% 비율로 포함되며, 상기 23 ~ 28 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 0.5 ~ 1.5 : 9.5 ~ 8.5의 중량% 비율로 포함되는, 한우 거세우의 비육방법.한우 거세우의 사양 단계를 6 ~ 13 개월령, 14 ~ 22 개월령 및 23 ~ 28 개월령으로 나누어 단계별로 영양성분이 상이한 사료를 한우 거세우에게 급여하는 한우 거세우의 비육기간 단축방법으로서,상기 6 ~ 13 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 3 ~ 5 : 7 ~ 5의 중량% 비율로 포함되고, 상기 14 ~ 22 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 1 ~ 3 : 9 ~ 7의 중량% 비율로 포함되며, 상기 23 ~ 28 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 0.5 ~ 1.5 : 9.5 ~ 8.5의 중량% 비율로 포함되는, 한우 거세우의 비육기간 단축 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

944/1059 Row 944: application_number: 1020200015048, combined_string: invention_title: 발전소 감시 시스템 및 방법 abstract: 실시예에 따르면, 발전소내에 설치된 촬영 장치로부터 영상 데이터를 수집하는 통신부; 발전소 내부를 촬영한 영상 데이터를 입력층으로 하여, 사육장 내부 영상과 객체간의 상관관계를 학습하고, 객체를 검출한 영상 데이터가 출력층이 되도록 학습된 제1뉴럴 네트워크를 포함하는 제1처리부; 및 상기 객체를 검출한 영상 데이터를 입력층으로 하여, 상기 객체와 객체의 위험 상태간의 상관관계를 학습하고, 위험 상태 판단 결과가 출력층이 되도록 학습된 제2뉴럴 네트워크를 포함하는 제2처리부를 포함하는 발전소 감시 장치를 제공한다. claims: 발전소내에 설치된 촬영 장치로부터 영상 데이터를 수집하는 통신부;발전소 내부를 촬영한 영상 데이터를 입력층으로 하여, 사육장 내부 영상과 객체간의 상관관계를 학습하고, 객체를 검출한 영상 데이터가 출력층이 되도록 학습된 제1뉴럴 네트워크를 포함하는 제1처리부; 및상기 객체를 검출한 영상 데이터를 입력층으로 하여, 상기 객체와 객체의 위험 상태간의 상관관계를 학습하고, 위험 상태 판단 결과가 출력층이 되도록 학습된 제2뉴럴 네트워크를 포함하는 제2처리부를 포함하는 발전소 감시 장치.발전소 내부에 배치되어 발전소 내부 영상을 촬영하는 촬영 장치;상기 촬영 장치로부터 영상 데이터를 수집하는 통신부;발전소 내부를 촬영한 영상 데이터를 입력층으로 하여, 사육장 내부 영상과 객체간의 상관관계를 학습하고, 객체를 검출한 영상 데이터가 출력층이 되도록 학습된 제1뉴럴 네트워크를 포함하는 제1처리부; 및상기 객체를 검출한 영상 데이터를 입력층으로 하여, 상기 객체와 객체의 위험 상태간의 상관관계를 학습하고, 위험 상태 판단 결과가 출력층이 되도록 학습된 제2뉴럴 네트워크를 포함하는 제2처리부를 포함하는 발전소 감시 시스템.통신부가 발전소내에 설치된 촬영 장치로부터 영상 데이터를 수집하는 단계;제1처리부가 제1뉴럴 네트워크를 이용하여 발전소 내부를 촬영한 영상 데이터를 입력층으로 하여, 사육장 내부 영상과 객체간의 상관관계를 학습하고, 객체를 검출한 영상 데이터가 출력층이 되도록 학습하는 단계; 및제2처리부가 제2뉴럴 네트워크를 이용하여 상기 객체를 검출한 영상 데이터를 입력층으로 하여, 상기 객체와 객체의 위험 상태간의 상관관계를 학습하고, 위험 상태 판단 결과가 출력층이 되도록 학습하는 단계를 포함하는 발전소 감시 방법.제17항에 따른 발전소 감시 방법을 컴퓨터에 실행시키기 위한 프로그램이 기록되어 있는 컴퓨터에서 판독 가능한　기록매체., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

945/1059 Row 945: application_number: 1020200009924, combined_string: invention_title: 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템 abstract: 본 발명은 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템에 관한 것으로, 복수 개의 비대칭 스테레오 카메라가 장착된 모바일 기기로 스테레오 영상을 촬영하여 가축의 무게를 측정하기 위한 것이다.이를 위하여 본 발명은, 피측정 가축의 2D 스테레오 영상을 촬영하는 스테레오 영상 촬영부, 2D 스테레오 영상에 심층학습 인공지능기법을 적용하여 3D 점운 정보를 획득하는 3D 점운 생성부, 3D 점운 처리를 통해 피측정 가축의 유효 데이터를 추출하고 흉위 및 유효 체장을 예측하여 체중을 산출하는 체중 산출부, 산출된 체중정보를 최대수익일 예측모델에 적용하여 해당 가축의 최대 수익일을 예측하는 최대수익일 예측부, 산출된 가축의 체중정보를 각 개체별 아이디와 일자별로 구분하여 저장하는 가축 DB, 및 산출된 각 가축의 개체별 체중정보 및 최대수익일 예측정보가 포함된 그래픽 기반의 인터페이스를 출력하는 디스플레이부를 포함하여, 3D 영상 촬영장비가 구비되어 있지 않은 모바일 기기에서도 비접촉 방식으로 가축의 체중을 간단하게 측정하고 개체별 체중 정보와 최대 수익일 예측정보 등을 확인하여 축산 농가의 시간적, 인력적 및 비용적인 문제를 해결할 수 있게 한다. claims: 피측정 가축의 2차원(2D) 스테레오 영상을 촬영하여 3D 점운 생성부(120)에 전달하는 스테레오 영상 촬영부(110);상기 스테레오 영상 촬영부(110)에서 전달되는 피측정 가축의 2D 스테레오 영상에 심층학습 인공지능기법을 적용하여 3차원(3D) 점운(Point Cloud) 정보를 획득하여 체중 산출부로 전달하는 3D 점운 생성부(120);상기 3D 점운 생성부(120)에서 전달되는 데이터들의 3D 점운 처리를 통해 피측정 가축의 유효 데이터를 추출하고 흉위 및 유효 체장을 예측하여 체중을 산출하며 산출된 체중 정보를 최대 수익일 예측부(140)와 가축 DB(150) 및 디스플레이부(160)로 전달하는 체중 산출부(130);상기 체중 산출부(130)에서 산출된 체중정보를 기설정된 최대수익일 예측모델에 적용하여 해당 가축의 체중이 최대등급에 도달하는 시기, 실질수익이 발생되는 시기를 포함하는 가축별 최대 수익일 예측정보를 산출하는 최대수익일 예측부(140);상기 체중 산출부(130)에서 산출된 가축의 체중정보를 각 개체별 아이디와 일자별로 구분하여 저장하는 가축 DB(150); 및상기 체중 산출부(130) 또는 최대수익일 예측부(140)에서 산출된 각 가축의 개체별 체중정보 또는 최대수익일 예측정보가 포함된 그래픽 기반의 인터페이스를 출력하는 디스플레이부(160);를 포함하여 구성되고,상기 스테레오 영상 촬영부(110)는,상이한 광학변수를 갖는 복수 개의 비대칭 스테레오 카메라로서 근접 객체를 촬영할 때와 원거리 객체를 촬영할 때에 최적의 효과를 낼 수 있도록 초점거리와 조리개의 성능이 비대칭적으로 다르게 설치되는 쌍안 카메라 또는 3중 카메라 중의 어느 하나로 이루어지고, 쌍안 카메라 또는 3중 카메라는 광학축과 이미징 평면이 각각 평행상태를 유지하고 이미징 평면은 동일 평면상에서 구성되며,상기 3D 점운 생성부(120)는,인코더 네트워크; 컴퓨터 비젼 처리에서 필요한 포즈의 추정, 객체 영역화 및 돌출점(salience) 탐지와 같은 다중스케일 표현기능을 수행하는 Res2Net 블록; 및 디코더 네트워크;로 구성되는 딥러닝 네트워크 모델을 통해 시차맵을 예측하고, 예측된 시차맵과 비대칭 스테레오 카메라의 고유 파라미터를 사용하여 깊이정보(Z)를 계산하여 객체의 공간좌표 P(X,Y,Z)를 구하되, 좌측과 우측에 두 대의 비대칭 스테레오 카메라가 설치되어 있고, 좌측 카메라의 광학축 C1과 우측 카메라의 광학축 C2, 두 카메라의 이격 거리는 B, 좌측 카메라의 초점 거리 f1과 좌측 카메라의 초점거리 f2(여기서 f1 = k×f2 관계 유지), 객체 상의 공통점으로서 좌측 카메라에 나타나는 이미지상의 점 P1(x1,y1)과 우측 카메라에 나타나는 이미지 상의 점 P2(x2,y2), 및 좌측 카메라의 좌표계의 원점을 공간 좌표계의 원점으로 가정한 경우,삼각법에 의하여 두 카메라에 나타나는 이미지상의 점 P1(x1,y1)과 점 P2(x2,y2)은,에 의해 정의되며. 두 카메라의 이미지가 정확하게 정합된 경우, P1과 P2 사이의 시차(disparity) d는,에 의해 정의되고,따라서 깊이정보 Z는, 에 의해 정의되며, 최종적으로 스테레오 영상의 각 화소점P1(x1,y1),P2(x2,y2)으로부터 공간좌표계의 점운 P(X,Y,Z)는, 또는에 의해 정의되는 것을 특징으로 하는 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템.제1항에 있어서, 상기 체중 산출부(130)는,상기 3D 점운 생성부(120)로부터 전달되는 데이터들의 점운(point cloud) 처리를 통해 평면적 특성을 나타내는 점운들을 제거하여 피측정 가축의 표면 점운들을 추출하는 3D 점운 처리부(131);상기 3D 점운 처리부(131)에서 추출된 피측정 가축의 표면 점운들로부터 피측정 가축 이외의 점운들을 제거하여 피측정 가축의 순수 표면 점운들만을 추출하는 3D 가축 영역 추출부(132);상기 3D 가축 영역 추출부(132)에서 추출된 피측정 가축의 순수 표면 점운들로부터 앞다리의 뒷쪽 위에 있는 몸통의 둘레 길이로 정의하여 피측정 가축의 흉위 G를 측정하는 흉위 측정부(133);상기 흉위를 측정한 부분의 맨 위 상단에 분포하는 점 A와 꼬리부분의 맨위 상단에 분포하는 점 C 사이의 절대 거리를 산출하여 피측정 가축의 척추부의 유효체장 를 측정하는 유효체장 측정부(134); 및상기 흉위 측정부(133)와 유효체장 측정부(134)에서 각각 측정된 피측정 가축의 흉위 G와 유효체장 를 반영하여 주어진 G 와 에 따른 해당 피측정 가축의 실체중을 계산하고 상기 계산된 피측정 가축의 실체중정보를 최대 수익일 예측부(140)와 가축 DB(150) 및 디스플레이부(160)에 전달하는 회귀 분석부(135);를 포함하여 구성되는 것을 특징으로 하는 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템.제1항에 있어서, 상기 최대수익일 예측부(140)는,현재 체중에 따른 가격(Co), 최적 등급(tp)에 도달하는 시기까지 요구되는 표준 사료 소모량의 가격(fe), 최적 등급에 도달하는 시기까지 요구되는 평균 시설유지비와 평균 인건비의 합(m, 여기서 평균 시설유지비는 총 시설유지비를 가축의 평균사육두수로 나눈 금액이며, 평균 인건비는 총 인건비를 가축의 평균사육두수로 나눈 금액임)을 이용하여 최대 수익일을 예측할 수 있는 최대 수익일 예측 모델을 정립하며,상기 최대 수익일 예측 모델 상의 생산성 곡선(pf)은,으로 산출되는 것을 특징으로 하는 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템.제1항에 있어서, 상기 디스플레이부(160)는,가축의 표준 사료 소모량과 성장량의 관계를 이용하여 최대 수익일을 예측할 수 있는 최대 수익일 예측 모델을 통해 체중 측정이 이루어진 가축이 최대 등급에 해당되는 적정체중에 도달하는 시기(최대수익 도달시기), 및 실질적인 수익이 발생되는 시기를 예측하여 창출 가능한 이익을 정량적으로 가시화하여 제시하는 인터페이스를 제공하는 것을 특징으로 하는 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템., Ltext: 농업, prediction: 임업
946/1059 Row 946: application_number: 1020200005041, combined_string: invention_title: 동물 후각을 자극하는 동물 사육 로봇 abstract: 본 발명은 동물 후각을 자극하는 먹이 냄새를 배출하는 먹이 냄새 배출구가 형성된 먹이 배출부를 장착하여 동물의 예민한 후각을 자극하여, 로봇의 작동이 중단되는 기간에도 동물의 후각을 자극하여 동물의 관심을 유도하고 로봇을 접촉하는 행동을 유발하여 접촉에 대한 성과 보상으로서 먹이를 배출하는 동물 사육 로봇을 제공한다. 본 발명은 전원 소모가 많은 각종 감지 센서나 음향 발생 장치의 사용을 배제하여 전원 소모를 최소화하여 로봇의 원격 관리 가동 가능 시간을 최대화하면서 먹이 냄새 배출을 위한 수단을 갖추어 동물의 자발적 접근과 접촉을 촉진할 수있는 동물 사육 로봇을 제공한다. claims: 외부의 원격 조종 프로그램에 의하여 인터넷을 통하여 조종되거나 또는 로봇에 입력된 내장 프로그램에 의해서 작동하며 동물 먹이 보관함이나 먹이 배출부가 장착된 동물 사육 로봇에 있어서, 상기 먹이 보관함이나 먹이 배출부에 하나 이상의 먹이 냄새 배출구가 형성되어 있는 것을 특징으로 하는, 동물 사육 로봇., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

947/1059 Row 947: application_number: 1020190172717, combined_string: invention_title: 반추동물용 해바라기 조사료, 이의 제조방법 및 해바라기 조사료를 이용한 반추동물 사육방법 abstract: 과제: 해바라기 특유의 냄새를 제어하고 반추동물이 섭취하기 좋으며 영양이 풍부한 해바라기 조사료 및 이를 제조하는 방법을 제공하는 것.과제해결방법: 해바라기의 곤포 사일리지 조제처리시 발효 균주, 좀 더 구체적으로는 락토바실러스속 미생물 및 피디오코커스속 미생물 중 하나 이상을 가하여 해바라기를 발효, 숙성함으로써 다른 재료를 가하지 않고도 단백질, 지방, 회분 등 영양성분이 풍부한 고품질의 조사료를 조제하였으며, 이 조사료를 급여하는 경우 한우가 거부감 없이 잘 섭취하였고, 한우 우육의 올레산 함량이 현저히 증가하였으며, 체중 증가도 현저하였다. claims: 만개 후 10일 내에 수확한, 건조중량 100g 당 조단백질이 10g 이상이고 조섬유가 25g 이상인 절단한 해바라기 잎과 줄기와 꽃에 발효 균주를 가하여 곤포 사일리지에서 발효, 숙성한 반추동물용 해바라기 조사료.1) 건조중량 100g 당 조단백질이 10g 이상이고 조섬유가 25g 이상인 해바라기 잎과 줄기와 꽃을 만개 후 10일 내에 수확하여 적정 크기로 절단하는 단계;2) 절단한 해바라기 잎과 줄기와 꽃에 락토바실러스속 발효 균주 및 피디오코커스속 발효 균주 중 하나 이상을 가하는 단계;3) 상기 발효 균주를 가한 해바라기 잎과 줄기와 꽃을 곤포 사일리지로 조제하고 발효하는 단계; 및4) 상기 발효된 해바라기 곤포 사일리지를 숙성하는 단계;를 포함하는 반추동물용 해바라기 조사료 제조방법.청구항 1 내지 청구항 6 중 어느 하나의 반추동물용 해바라기 조사료를 급여하는 해바라기 조사료를 이용한 반추동물 사육방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

948/1059 Row 948: application_number: 1020190167338, combined_string: invention_title: 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법 abstract: 본 발명은 마우스와 같은 실험 동물 배양을 위한 사육 케이지 내부로의 흡기 또는 외부로의 배기시 흡기관 및 배기관의 크기를 반영하고 블로어의 회전수를 조절 가능하여 최적의 사육 환경을 조성하고, 사육케이지 내부의 공기 정보에 맞추어 사육케이지 내부로 유입되거나 배기되는 공기의 양을 최적 상태로 조절하기 위한 블로어 최적 제어를 가능하게 하는 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법에 관한 것이다.본 발명의 실시예인 외부 공기가 급기되는 흡기관과 내부 공기가 배기되는 배기관과, 상기 흡기관과 연결되는 흡기부(제 1 모터와 제 1 블로어 구비)와, 상기 배기관과 연결되는 배기부(제 2모터와 제 2블로어 구비)와, 상기 흡기관 내부에 설치된 유속 센서와, 상기 배기관 내부에 설치되어 배기되는 공기의 정보를 측정하는 공기 정보 측정용 센서와, 상기 제 1 및 제 2 모터의 듀티비를 제어하는 제어부를 구비하는 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법은,(a) 설정하고자 하는 설정 ACH를 제어부로 전송하는 단계;(b) 상기 설정 ACH에 대응하여, 상기 흡기관으로 급기되는 공기 유량을 상기 제어부에서 계산하는 단계;(c) 상기 공기 유량에 대응하는 제 1 공기 유속을 상기 제어부에서 계산하는 단계;(d) 상기 제어부에서 상기 제 1 공기 유속에 대응하는 상기 제 1 블로어의 RPM을 계산하는 단계;(e) 상기 제어부가 상기 제 1 블로어의 상기 RPM 유지를 위하여 상기 제 1 블로어를 제어하는 상기 제 1 모터의 듀티비를 계산하는 단계;(f) 상기 제 1 모터를 작동시키는 단계;(g) 상기 제 1 모터와 10% 차이가 나는 듀티비를 갖도록 상기 제 2 모터를 작동시키는 단계; (h) 상기 흡기관 내부에 설치된 유속 센서를 통하여 상기 흡기관으로 급기되는 제 2 공기 유속이 측정되어 상기 제어부로 전송되는 단계; (i) 상기 제어부에서 상기 제 2 공기 유속에 대응하는 제 2 공기 유량을 계산하는 단계;(j) 상기 제어부에서 상기 제 2 공기 유량에 따라 계산되는 측정치인 측정 ACH를 도출하고 상기 설정 ACH와의 차이를 비교하는 단계;(k) 상기 설정 ACH와 상기 측정 ACH의 차이가 제로로 수렴할 때까지 상기 단계 (f) ~ 단계 (j)를 반복 실시하되, 상기 단계 (f)의 상기 제 1 모터 작동을 위한 듀티비를 소정 수치 증가 또는 감소시킨 후 반복 실시하는 단계;로 이루어지는 것을 특징으로 한다.본 발명의 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법을 실시하는 경우, 흡기관 배기관의 크기 및 사육 케이지 내부 공기 정보에 따라 사육 케이지 내부의 공기 환경을 최적으로 유지시킬 수 있다는 이점이 있다. claims: 외부 공기가 급기되는 흡기관과 내부 공기가 배기되는 배기관과, 상기 흡기관과 연결되는 흡기부(제 1 모터와 제 1 블로어 구비)와, 상기 배기관과 연결되는 배기부(제 2모터와 제 2블로어 구비)와, 상기 흡기관 내부에 설치된 유속 센서와, 상기 배기관 내부에 설치되어 배기되는 공기의 정보를 측정하는 공기 정보 측정용 센서와, 상기 제 1 및 제 2 모터의 듀티비를 제어하는 제어부를 구비하는 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법으로서,(a) 설정하고자 하는 설정 ACH를 제어부로 전송하는 단계;(b) 상기 설정 ACH에 대응하여, 상기 흡기관으로 급기되는 공기 유량을 상기 제어부에서 계산하는 단계;(c) 상기 공기 유량에 대응하는 제 1 공기 유속을 상기 제어부에서 계산하는 단계;(d) 상기 제어부에서 상기 제 1 공기 유속에 대응하는 상기 제 1 블로어의 RPM을 계산하는 단계;(e) 상기 제어부가 상기 제 1 블로어의 상기 RPM 유지를 위하여 상기 제 1 블로어를 제어하는 상기 제 1 모터의 듀티비를 계산하는 단계;(f) 상기 제 1 모터를 작동시키는 단계;(g) 상기 제 1 모터와 10% 차이가 나는 듀티비를 갖도록 상기 제 2 모터를 작동시키는 단계; (h) 상기 흡기관 내부에 설치된 유속 센서를 통하여 상기 흡기관으로 급기되는 제 2 공기 유속이 측정되어 상기 제어부로 전송되는 단계; (i) 상기 제어부에서 상기 제 2 공기 유속에 대응하는 제 2 공기 유량을 계산하는 단계;(j) 상기 제어부에서 상기 제 2 공기 유량에 따라 계산되는 측정치인 측정 ACH를 도출하고 상기 설정 ACH와의 차이를 비교하는 단계;(k) 상기 설정 ACH와 상기 측정 ACH의 차이가 제로로 수렴할 때까지 상기 단계 (f) ~ 단계 (j)를 반복 실시하되, 상기 단계 (f)의 상기 제 1 모터 작동을 위한 듀티비를 소정 수치 증가 또는 감소시킨 후 반복 실시하는 단계;로 이루어지는 것을 특징으로 하는 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법., Ltext: 농업, prediction: 임업
949/1059 Row 949: application_number: 1020190166844, combined_string: invention_title: 축사용 스탄존 및 그 설치방법 abstract: 본 발명은 소 사육농가에서 예방접종 및 검사시 쉽게 보정하여 소 개체관리를 하거나, 사료 급여시에 활동 반경을 제한하도록 하는 스탄존의 사용수명을 크게 연장하고 증설을 용이하게 할 수 있는 축사용 스탄존 및 그 설치방법에 관한 것이다.즉, 본 발명은 상,하부가로대 사이에 수직으로 설치되는 다수의 지지대, 상기 각 지지대와 지지대의 사이에 결합되고 일정각도로 절곡하여 기울어진 고정대, 상기 고정대에 힌지 결합되고 힌지축을 중심으로 수직 또는 기울어지게 회동되는 회동봉, 상기 상부가로대의 상측에 설치되어 회동봉이 수직으로 세워졌을 때 이를 규제하는 잠금수단이 구비되어 있는 제어봉으로 구비되는 것을 포함하며, 상기 상,하부가로대와 지지대의 연결부분은 양측으로 분할된 T형 클립부재에 의해 결합되고, 상기 각 지지대와 지지대의 사이에 결합되고 일정각도로 절곡하여 기울어진 고정대와 지지대가 맞닿는 부분은 양측으로 분할된 T형 더블클립부재에 의해 결합되는 구성으로 조립이 이루어지는 축사용 스탄존 및 그 설치방법을 특징으로 한다. claims: 상,하부가로대(10)(20) 사이에 수직으로 설치되는 다수의 지지대(30), 상기 각 지지대(30)와 지지대(30)의 사이에 결합되고 일정각도로 절곡하여 기울어진 고정대(40), 상기 고정대(40)에 힌지(42) 결합되고 힌지축을 중심으로 수직 또는 기울어지게 회동되는 회동봉(50), 상기 상부가로대(10)의 상측에 설치되어 회동봉(50)을 규제하는 잠금수단(62)이 구비되어 있는 제어봉(60)으로 구비되는 것을 포함하며,상기 상,하부가로대(10)(20)와 지지대(30)의 연결부분은 양측으로 분할된 T형 클립부재(100)에 의해 결합되되 상기 T형 클립부재(100)는 수평결합부(110)와 수직결합부(120)가 구비되어 상기 수평결합부(110)는 상부가로대(10) 또는 하부가로대(20)에 감싸듯이 결합되고, 상기 수직결합부(120)는 지지대(30)와 감싸듯이 결합되는 구성과,상기 각 지지대(30)와 지지대(30)의 사이에 결합되고 일정각도로 절곡하여 기울어진 고정대(40)와 지지대(30)가 맞닿는 부분은 양측으로 분할된 T형 더블클립부재(100a)에 의해 결합되되 상기 T형 더블클립부재(100a)는 수평결합부(110)와 수직결합부(120)가 구비되어 상기 수평결합부(110)는 상부가로대(10)에 감싸듯이 결합되고, 상기 수직결합부(120)는 측부 연장단면(124)에 의해 병렬 연결되어 구비되는 한 쌍의 수직결합부(120)에 지지대(30) 및 고정대(40)를 각각 감싸듯이 결합되는 구성으로 조립이 이루어지도록 한 것을 특징으로 하는 축사용 스탄존.수평결합부(110)와 수직결합부(120)가 구비된 T형 클립부재(100)와, 수평결합부(110)와 수직결합부(120)는 측부 연장단면(124)에 의해 병렬 연결되어 있는 한 쌍의 수직결합부(120)를 가진 T형 더블클립부재(100a)를 각각 구비한 다음 상,하부가로대(10)(20)가 평행으로 서로 대향되게 배치하는 단계; 상기 하부가로대(20)에 양측으로 T형 클립부재(100)의 수평결합부(110)를 결합하고, T형 클립부재(100)의 수직결합부(120)에 지지대(30) 및 고정대(40)의 하단부를 각각 결합하는 단계; 상기 T형 클립부재(100)의 결합구멍(130)에 체결구(140)를 끼워 체결하는 단계: 상기 상부가로대(10)에 또 다른 T형 클립부재(100) 및 T형 더블클립부재(100a)의 수평결합부(110)를 결합하고, T형 더블클립부재(100a)에 구비된 한 쌍의 수직결합부(120)에 지지대(30) 및 고정대(40)의 상단부를 각각 결합하는 단계; 상기 T형 클립부재(100) 및 T형 더블클립부재(100a)의 결합구멍(130)에 체결구(140)를 끼워 체결하는 단계;를 포함하여서 됨을 특징으로 하는 축사용 스탄존의 설치방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

950/1059 Row 950: application_number: 1020190158098, combined_string: invention_title: 공주알밤한우 건강육 abstract: 본 발명은 공주알밤한우 건강육에 관한 것으로, 더욱 상세하게는 공주에서 생산된 밤에서 분리된 율피를 이용한 육질개선용 소 사료 조성물, 이를 급여하는 소 사육방법 및 이를 급여한 소로부터 생산되는 우육에 관한 것이다.이에 따라 가공되는 밤 함량의 약 25%를 차지하는 율피를 버리지 않고 재활용할 수 있어 자원의 낭비를 막을 수 있으며, 경제적인 가치가 매우 높다. 또한, 화학합성사료가 아닌 자연에서 분리되는 율피를 이용하여 친환경적으로 소의 사육 환경을 개선할 수 있다. 본 발명은 소의 육질을 개선할 수 있고, 구체적으로 아미노산과 불포화지방산의 함량을 증진시키며, 고기의 맛 역시 개선시킬 수 있다. claims: 율피를 포함하는 것을 특징으로 하는 육질개선용 소 사료 조성물.청구항 1 내지 3 중 어느 한 항에 따른 소 사료 조성물을 급여하는 단계를 포함하는 것을 특징으로 하는 소 사육방법.청구항 1 내지 3 중 어느 한 항에 따른 육질개선용 소 사료 조성물을 급여한 소로부터 생산되는 것을 특징으로 하는 우육., Ltext: 농업, prediction: 임업
951/1059 Row 951: application_number: 1020190156532, combined_string: invention_title: 한우 대사물질 판별용 조성물 및 이를 이용한 한우 교배 효율 판별 방법 abstract: 본 발명은 한우 대사물질 판별용 조성물 및 이를 이용한 한우 교배 효율 판별 방법에 관한 것으로, 암소의 혈중에 존재하는 대사물질 중, 번식효율과 관련된 혈중 요소 질소(blood urea nitrogen, BUN) 또는 혈중 에너지 인자를 검출에 효과적이다. 이에, 한유 교배 효율을 판별할 수 있고, 임신우 또는 비임신우의 급여 조절, 수정란의 채란, 인공 수정 및 수태율을 위한 식이 조절을 판별할 수 있는 바, 목축 및 육우 산업 전반에 활용이 가능하다. claims: 한우의 혈중 요소 질소(blood urea nitrogen, BUN) 또는 혈중 에너지 인자를 검출하는 시약을 포함하는, 한우 대사물질 판별용 조성물.제 1항의 조성물을 포함하는 한우 대사물질 판별용 키트.(1) 대상 한우의 시료를 수득하는 단계;(2) 상기 (1)의 시료에 제8항의 키트를 이용하여 혈중 대사물질의 농도를 판별하는 단계; 및(3) 상기 한우의 혈중 대사 물질을 대조 한우와 비교하는 단계;를 포함하는, 한우 교배 효율 판별 방법.(1) 대상 한우의 시료를 수득하는 단계;(2) 상기 (1)의 시료에 제8항의 키트를 이용하여 혈중 대사물질의 농도를 판별하는 단계; 및(3) 상기 한우의 혈중 대사 물질을 대조 한우와 비교하는 단계; 를 포함하는, 한우의 식이 조절을 위한 판별 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

952/1059 Row 952: application_number: 1020190152331, combined_string: invention_title: 축산폐수 처리장치 abstract: 본 발명은 축산폐수 처리장치에 관한 것으로, 축산폐수를 공급받아 침전물을 분리하는 침전조(100); 상기 침전조(100) 내에서 침전물과 분리된 상층수를 공급받아 1차 여과하도록 패각소성체를 포함하는 패각필터가 내장된 제1여과기(200); 및 상기 제1여과기(200)를 통하여 1차 여과된 폐수를 공급받아 2차 여과하도록 목재 톱밥을 포함하는 목재필터가 내장된 제2여과기(300);를 포함하여 소, 돼지, 닭 등의 축산용 가축 사육시 발생하는 축산폐수를 매우 신속하고 효율적으로 정화시킬 수 있는 축산폐수 처리장치에 관한 것이다. claims: 축산폐수를 공급받아 침전물을 분리하는 침전조(100);상기 침전조(100) 내에서 침전물과 분리된 상층수를 공급받아 1차 여과하도록 패각소성체를 포함하는 패각필터가 내장된 제1여과기(200);상기 제1여과기(200)를 통하여 1차 여과된 폐수를 공급받아 2차 여과하도록 목재 톱밥을 포함하는 목재필터가 내장된 제2여과기(300);상기 침전조(100)에 연결되어 침전조(100) 하부에 침전된 침전물을 수거하는 침전물 수거부(400); 및상기 제2여과기(300)를 통하여 2차 여과된 폐수를 공급받아 가열하는 가열장치(500);를 포함하며,상기 패각소성체는 굴패각을 800 내지 1,000℃의 온도로 소성한 것이며,상기 목재 톱밥은 소나무 톱밥과 참나무 톱밥을 소나무 톱밥 100중량부당 참나무 톱밥 300 내지 400중량부의 비율로 혼합한 것이며,상기 침전물 수거부(400)는침전물과 상층수간의 경계를 차단하여 이들을 공간적으로 폐쇄하여 분리하는 층분리기(410); 상기 층분리기(410)가 침전물과 상층수간의 경계를 차단하면 회전작동하여 침전물을 원심력에 의하여 배출공(420)으로 배출시키는 회전체(430); 상기 배출공(420)으로 배출된 침전물을 수거하여 건조하는 건조기(440); 및 상기 건조기에서 건조된 침전물을 분쇄하는 분쇄기(441);를 포함하고,상기 가열장치(500)는상기 제2여과기(300)를 통하여 2차 여과된 폐수를 공급받아 악취를 제거하기 위하여 표면에 송진 피막이 형성된 볏짚 분쇄물을 투입하여 혼합하고 60 내지 70℃로 가열하는 제1가열기(510); 상기 제1가열기(510)에서 가열된 폐수를 공급받아 잔류 악취를 추가로 제거하기 위하여 흑운모 분말을 투입하여 혼합하고 80 내지 90℃로 가열하는 제2가열기(520); 다수의 구리(Cu)판(531)이 내부에 설치되며 상기 제2가열기(520)에서 가열된 폐수를 공급받아 상기 구리판(531)을 가열함으로써 폐수를 60 내지 70℃로 가열하는 제3가열기(530);를 포함하며,상기 침전조(100) 내에는 초음파진동발생기(110)가 구비되며, 상기 초음파진동발생기(110)는 200 내지 300㎑의 주파수를 갖는 초음파를 1초 단위로 주파수를 2㎑씩 연속적으로 변경하면서 폐수의 상층수에 인가하는 것을 특징으로 하는 축산폐수 처리장치., Ltext: 농업, prediction: 임업
953/1059 Row 953: application_number: 1020190145471, combined_string: invention_title: 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템 abstract: 본 발명은 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템으로서 중앙의 서버를 통제하는 관리자가 원격지에 다수 분포되어 있는 농장의 축사에 각각 수용되어 있는 개체별 소 또는 돼지 등 가축의 발육상태 등을 실시간 제공받으며 직접 확인하여, 양방향 송수신되어 제공되는 개체별 정보에 따라 사료의 종류와 분량 및 수분의 제공 등을 원격 제어하며 사육하기 위한 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템에 관한 것으로, 인터넷과 연결되는 컴퓨터를 이용하여 원거리에 있는 농장의 소를 사육하기 위한 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템에 있어서, 각 클라이언트 소유임을 인증할 수 있는 개체식별기가 부착된 개체가 사료급여통으로 진입하여 개체정보를 판독 하고, 클라이언트 소유의 개체인지 여부를 확인하는 개체판단단계, 해당 개체의 사전정보가 중앙서버의 개체별DB에 존재하는지 여부를 확인하여 개체사전정보를 저장하고 해당 개체의 사전정보를 상기 중앙서버를 제어하는 중앙PC 단말기로 디스플레이하여 개체정보를 확인하는 개체정보확인단계, 상기 중앙서버에 저장되는 표준사육정보DB와 개체별DB의 해당 개체 사전정보간을 비교분석하여 해당 개체의 현발육상태의 우성 및 열성 여부를 판단하는 개체우열판단단계, 상기 개체우열판단단계에 의해 우성 및 열성으로 판단된 개체에 적합한 사료의 양 및 종류를 상기 표준사육정보 DB로부터 추출하여 사료를 공급하는 개체별 사료 공급단계로 구성되는 특징으로 하는 인터넷을 이용한 원거리 가축 사육 시스템 처리 방법을 특징으로 한 것으로서, 전국에 분포되며 산재되어 있는 각 가축 농장의 개체에 따른 사료의 양 및 종류 등을 해당 개체의 발육상황에 따라 원거리에서도 일방향 또는 양방향 동시에 일률적 제어가 가능하도록 하여 우량의 육질을 갖는 개체로 사육시킬 수 있는 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템에 관한 것이다. claims: 인터넷과 연결되는 컴퓨터를 이용하여 원거리에 있는 농장의 소를 사육하기 위한 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템에 있어서, 각 클라이언트 소유임을 인증할 수 있는 개체식별기가 부착된 개체가 사료급여통으로 진입하여 개체정보를 판독 하고, 클라이언트 소유의 개체인지 여부를 확인하는 개체판단단계, 해당 개체의 사전정보가 중앙서버의 개체별DB에 존재하는지 여부를 확인하여 개체사전정보를 저장하고 해당 개체의 사전정보를 상기 중앙서버를 제어하는 중앙PC 단말기로 디스플레이하여 개체정보를 확인하는 개체정보확인 단계, 상기 중앙서버에 저장되는 표준사육정보DB와 개체별DB의 해당 개체 사전정보간을 비교분석하여 해당 개체의 현발육상태의 우성 및 열성 여부를 판단하는 개체우열판단단계, 상기 개체우열판단단계에 의해 우성 및 열성으로 판단된 개체에 적합한 사료의 양 및 종류를 상기 표준사육정보 DB로부터 추출하여 사료를 공급하는 개체별 사료 공급단계로 구성되는 특징으로 하는 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

954/1059 Row 954: application_number: 1020190137275, combined_string: invention_title: 실험동물 사육실 살균소독 시스템 abstract: 본 발명은 자율적인 소독액의 분무가 가능하여 상주하지 않고도 외부에서 소독관리를 수행할 수 있음은 물론 여러군데 위치한 사육실을 통합관리할 수 있으며, 실시간 모니터링이 가능한 실험동물 사육실 살균소독 시스템에 관한 것이다.본 발명의 실험동물 사육실 살균소독 시스템은, 실험동물 사육실 내부 일측에 설치되고, 제어부(200)의 제어신호에 의해 작동되면서 소독액통(150)에 저장된 소독액을 노즐(141)을 통해 분무하는 소독기(100); 상기 소독기(100)에 설치되어 관리서버(300)의 제어명령에 따라 제어신호를 생성하여 소독액을 분무하도록 소독기(100)를 제어하는 제어부(200); 상기 제어부(200)와 무선통신망으로 연결되어 원격제어하며, 제어부(200)로부터 소독정보를 전달받아 저장하는 관리서버(300); 상기 제어부(200) 또는 관리서버(300)와 무선통신망으로 연결되어 소독정보를 수신받는 휴대단말기(400);로 이루어진다. claims: 실험동물 사육실 내부 일측에 설치되고, 제어부(200)의 제어신호에 의해 작동되면서 소독액통(150)에 저장된 소독액을 노즐(141)을 통해 분무하는 소독기(100);상기 소독기(100)에 설치되어 관리서버(300)의 제어명령에 따라 제어신호를 생성하여 소독액을 분무하도록 소독기(100)를 제어하는 제어부(200);상기 제어부(200)와 무선통신망으로 연결되어 원격제어하며, 제어부(200)로부터 소독정보를 전달받아 저장하는 관리서버(300);상기 제어부(200) 또는 관리서버(300)와 무선통신망으로 연결되어 소독정보를 수신받는 휴대단말기(400);로 이루어진 것을 특징으로 하는 실험동물 사육실 살균소독 시스템., Ltext: 농업, prediction: 임업
955/1059 Row 955: application_number: 1020190134165, combined_string: invention_title: 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템 abstract: 본 발명은 한우 번식관리 시스템에 관한 것으로서, 보다 구체적으로는 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템으로서, 번식우 개체별 번식주기 내 예정된 번식상태 정보, 예정된 번식상태까지 남은 일수 정보, 및 번식우에 부착된 센서로부터 수집된 활동상태 정보를 개체별 비교하여 제공하는 번식우 관리 모듈; 날짜별 번식상태 정보 및 개체 현황 정보를 저장하고 제공하는 번식예정일 관리 모듈; 축사에서 보유하는 정액과 수정란의 유전정보 및 물류 정보를 저장하고 제공하는 정액/수정란 관리 모듈; 및 축사의 관리자 정보 및 실시간 동영상을 포함하는 축사 현황 정보를 저장하고 제공하는 축사 관리 모듈을 포함하는 것을 그 구성상의 특징으로 하며, 상기 번식우 관리 모듈에서 제공하는 활동상태는, 시간에 따른 개체의 활동을 활동 그래프의 형식으로 함께 제공하는 것을 특징으로 한다.본 발명에서 제안하고 있는 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템에 따르면, 번식우 개체별 번식주기 내 예정된 번식상태 정보, 예정된 번식상태까지 남은 일수 정보, 및 번식우에 부착된 센서로부터 수집된 활동상태 정보를 개체별 비교하여 제공하는 번식우 관리 모듈을 포함함으로써, 개체별 활동 및 번식상태를, 예정된 정보와 실시간으로 확인된 정보로서 상호 비교할 수 있도록 제공하기 때문에, 더욱 정확하고 용이하게 번식우의 번식상태를 판단할 수 있으며, 각각의 번식상태마다 확인해야 할 사항을 제공함으로써, 한우 번식우 관리자에게 해야 할 일을 빠짐없이 안내할 수 있어 번식우 개체별 지속적이고 효과적인 관리가 가능하고, 궁극적으로는 한우 축가의 생산성 및 수익성에 이바지하고 소득 증대를 도모할 수 있다.또한, 본 발명에서 제안하고 있는 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템에 따르면, 각 한우 개체의 활동 그래프뿐만 아니라 다른 한우 개체들의 활동 그래프를 함께 보여주고, 시간에 따른 활동상태를 녹화된 활동 동영상과 함께 제공함으로써, 관리자가 각 개체의 활동상태를 다른 개체들과 한눈에 비교 분석할 수 있으며, 이에 따라 한우 번식우마다 개별적인 건강상태에 적합하도록 번식관리를 할 수 있어, 체계적인 관리를 통해 번식 효율을 높일 수 있다.뿐만 아니라, 본 발명에서 제안하고 있는 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템에 따르면, 캘린더 형식으로 날짜에 따른 번식상태 정보 및 개체 현황정보를 제공하는 번식예정일 관리 모듈을 포함함으로써, 각 일자에 해당하는 일정 정보를 갖는 개체정보를 해당 일정별로 추출하여 오늘의 일정 보기를 제공하고, 관리자로 하여금 매일의 해야 할 일을 꾸준히 안내할 수 있어 한우 번식우 개체별 지속적이고 효과적인 관리가 가능하다. claims: 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템(10)으로서,번식우 개체별 번식주기 내 예정된 번식상태 정보, 예정된 번식상태까지 남은 일수 정보, 및 번식우에 부착된 센서로부터 수집된 활동상태 정보를 개체별 비교하여 제공하는 번식우 관리 모듈(100);날짜별 예정 번식상태 정보 및 개체 현황 정보를 저장하고 제공하는 번식예정일 관리 모듈(200);축사에서 보유하는 정액과 수정란의 유전정보 및 물류 정보를 저장하고 제공하는 정액/수정란 관리 모듈(300); 및축사의 관리자 정보 및 실시간 동영상을 포함하는 축사 현황 정보를 저장하고 제공하는 축사 관리 모듈(400)을 포함하고,상기 번식우 관리 모듈(100)에서 제공하는 활동상태 정보는, 시간에 따른 개체의 활동을 활동 그래프의 형식으로 함께 제공하는 것을 특징으로 하는, 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템(10)., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

956/1059 Row 956: application_number: 1020190134164, combined_string: invention_title: 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템 abstract: 본 발명은 한우 번식주기 관리 시스템에 관한 것으로서, 보다 구체적으로는 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템으로서, 한우 개체의 발정 여부를 탐지하는 발정탐지부; 상기 발정탐지부로부터 발정 정보를 수신하여 개체별 번식주기 및 번식상태에 대한 정보를 관리하고 저장하는 서버; 및 상기 발정탐지부 및 상기 서버로부터 개체별 번식에 대한 정보를 수신받거나, 개체별 번식에 대한 정보를 상기 서버로 송신하는 사육자 단말기를 포함하며, 상기 서버는, 상기 발정탐지부에서 개체의 발정탐지 시, 발정 정보를 수신하여 번식주기를 연산하는 일정연산부; 상기 사육자 단말기로부터 실제 확인된 번식상태를 수신받아 등록하는 등록부; 및 상기 일정연산부에서 연산된 번식주기에 따른 예상 번식상태와 상기 등록부에서 등록된 실제 번식상태 차이를 개체별 비교하는 비교부를 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템에 따르면, 한우 개체마다 부착된 센서에서 감지된 소의 움직임 및 행동 정보를 토대로, 소의 행동 유형 패턴을 판단하고 소의 발정 여부를 탐지하는 발정탐지부를 포함함으로써, 소의 발정기를 보다 정확하고 용이하게 판단할 수 있으며, 공태기간 및 번식장애(저수태, 미약발정, 무발정, 조기배사멸) 발생을 예방할 수 있어, 소의 번식 효율을 증가시키고 발정 미감지로 인한 피해를 줄이며, 궁극적으로는 한우 농가의 생산성 및 수익성에 이바지하고 농가의 소득 증대에 이바지할 수 있다.또한, 본 발명에서 제안하고 있는 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템에 따르면, 한우 개체의 발정탐지 후, 번식주기 내 번식상태 일정 정보를 연산하여 제공하고, 번식상태마다 확인해야 할 사항을 제공함으로써, 한우 번식우 사육자에게 해야 할 일을 빠짐없이 번식상태별로 안내할 수 있어 번식우 개체별 지속적이고 효과적인 관리가 가능하며, 한우 번식우마다 개별적인 건강상태에 적합하도록 번식관리를 할 수 있어, 더욱 체계적인 번식관리를 통해 번식 효율을 증가시킬 수 있다.뿐만 아니라, 발명에서 제안하고 있는 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템에 따르면, 번식주기 내 자동으로 판단된 개체의 번식상태와 사육자로부터 확인된 실제 번식상태의 차이를 비교하여 축사주 내지 사육자에게 등록요청 푸시알람 내지 등록지연 알람을 보냄으로써, 축사주 내지 사육자가 빠뜨림 없이 번식관리를 할 수 있도록 유도하고, 관리를 강제할 수 있으며, 사육자가 업무를 소홀히 하지 않도록 축사주가 고용된 사육자를 관리하는 데 도움을 줄 수 있다. claims: 한우 번식주기 관리 시스템(10)으로서,한우 개체의 발정 여부를 탐지하는 발정탐지부(100);상기 발정탐지부(100)로부터 발정 정보를 수신하여 개체별 번식주기 및 번식상태에 대한 정보를 관리하고 저장하는 서버(200); 및상기 발정탐지부(100) 및 상기 서버(200)로부터 개체별 번식에 대한 정보를 수신받거나, 개체별 번식에 대한 정보를 상기 서버(200)로 송신하는 사육자 단말기(300)를 포함하며,상기 서버(200)는,상기 발정탐지부(100)에서 개체의 발정탐지 시, 발정 정보를 수신하여 번식주기를 연산하는 일정연산부(210);상기 사육자 단말기(300)로부터 실제 확인된 번식상태를 수신받아 등록하는 등록부(220); 및상기 일정연산부(210)에서 연산된 번식주기에 따른 예상 번식상태와 상기 등록부(220)에서 등록된 실제 번식상태 차이를 개체별 비교하는 비교부(230)를 포함하며,상기 사육자 단말기(300)는,한우 개체의 확인된 실제 번식상태를 입력하는 입력부(310);상기 입력부(310)에서 입력된 실제 번식상태, 및 상기 일정연산부(210)에서 연산된 번식주기에 따른 예상 번식상태와 각각의 번식상태에 따라 사육자가 해야할 사항을 제공하는 출력부(320); 및상기 비교부(230)에서 비교된 번식상태의 차이가 기설정된 값보다 초과한 경우, 축사주 내지 사육자에게 등록요청 푸시알람 또는 등록지연 알람을 보내는 알람부(330)를 더 포함하며,상기 사육자 단말기(300)를 통해, 사육자는 어린소 상태의 개체, 수정이 실패한 개체, 임신이 실패한 개체, 또는 분만후 상태의 개체에서 발정 징후가 보이면 실제로 발정 상태인지 확인을 하여 발정인 경우 발정등록, 인공수정이 완료한 개체의 경우 수정등록, 2회 발정주기가 지난 후 자동으로 임신대기 상태가 되고 임신 성공이 확인되면 임신감정등록, 분만이 완료되면 분만등록, 분만 후 개체가 더이상 송아지 생산에 가치가 없다고 판단되면 비육 등록이 이루어지되,확인된 실제 번식상태로서 발정등록, 수정등록, 임신감정등록, 분만등록, 비육등록 중 하나의 등록이 상기 사육자 단말기(300)를 통해 이루어지며, 상기 사육자 단말기(300)를 통한 등록 절차를 거쳐야 상기 일정연산부(210)에서 다음 번식주기가 연산 되도록 함으로써, 사육자의 등록을 강제하는 것을 특징으로 하는, 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템(10)., Ltext: 농업, prediction: 임업
957/1059 Row 957: application_number: 1020190133038, combined_string: invention_title: 가축분뇨를 이용한 완효성 퇴비의 제조방법 및 이에 의해 제조되는 완효성 퇴비 abstract: 본 발명은 우사에서 수거된 우분과 계분을 혼합하여 발효시간을 단축하고 분뇨에 포함된 유효성분을 완효화하는 퇴비 제조방법에 관한 것으로서, 우사 바닥에 마그네시아와 철염을 살포하고 그 위에 톱밥 깔짚을 덮어 바닥층을 형성하는 단계와, 상기 바닥층이 형성된 우사에 소를 사육하며 상기 우사에 설치된 건조 팬을 통하여 우사 내부를 통기시켜 우분을 1차 발효하는 단계 및, 1차 발효된 상기 우분에 계분과 석회고토의 혼합물을 혼합하여 2차 발효하는 단계를 포함한다.본 발명에 따르면 우사 바닥에서부터 분뇨의 배설과 동시에 발효를 촉진함으로써 발효기간을 단축하여 악취 발생을 저감시킬 수 있으며, 가축의 축분에 포함된 유효성분을 난용화ㆍ완효화하여 고품질의 친환경 퇴비를 제공할 수 있다. claims: 우사 바닥에 마그네시아와 황토분말이 코팅된 황산제일철(FeSO4)을 살포하고 그 위에 톱밥 깔짚을 덮어 바닥층을 형성하는 단계;상기 바닥층이 형성된 우사에 소를 사육하며, 상기 우사에 설치된 건조 팬을 통하여 우사 내부를 통기시켜 우분의 함수율이 80% 미만이 되도록 통기시켜 1차발효하는 단계; 및,1차 발효된 상기 우분을 우사에서 수거하여 추가 발효한 후, 계분과 석회고토의 혼합물을 혼합하여 1~3개월 동안 2차 발효하는 단계;를 포함하는 것을 특징으로 하는 가축분뇨를 이용한 완효성 퇴비의 제조방법.제1항, 제2항 및 제6항 내지 제12항 중 어느 한 항에 의하여 제조되는 완효성 퇴비., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

958/1059 Row 958: application_number: 1020190130417, combined_string: invention_title: 동물용 주사기 보조장치 abstract: 본 발명은 소 등의 가축이나 사육되는 동물에게 예방 또는 치료용 주사액를 투약할 때, 원거리에서 안전하고 신속하게 투약할 수 있고, 1회용 주사기를 사용하여 위생적으로 투약할 수 있도록 구성된 동물용 주사기 보조장치에 관한 것으로, 가압부 안내부(120)와 주사기 거치부(110)를 포함하는 본체(100);와, 상기 가압부 안내부(120)에 삽입되어 이동가능하게 결합되는 가압부(220)와 손잡이(260)를 포함하는 피스톤 가압모듈(200);과, 상기 주사기 거치부(110)에 설치되며 상기 주사기(400)의 실린더(410)가 삽입되는 실린더 안착부(310)를 포함하는 주사바늘 보호체(300);를 포함하고 있으며, 상기 주사기 거치부(110)에는 설치되는 주사기(400)의 실린더(410)를 고정 결합할 수 있는 실린더 플랜지 결합홈(140)이 형성되어 있고, 상기 주사바늘 보호체(300)는 상기 주사기 거치부(110)의 내부에서 상기 주사기의 실린더(410) 및 상기 본체(100)와 상대이동 가능하게 설치되어, 상기 주사기 거치부(110)에 설치된 주사기(400)의 주사바늘(430)이 외부로 노출되지 않은 상태에서 동물에게 주사액(a)을 투약할 수 있도록 구성되어 있다. claims: 실린더(410)와 피스톤(240) 및 주사바늘(430)을 포함하는 주사기(400)를 설치하여 원거리에서 동물에게 주사액(a)을 투약하기 위한 동물용 주사기 보조장치로써, 가압부 안내부(120)와 주사기 거치부(110)를 포함하는 본체(100);상기 가압부 안내부(120)에 삽입되어 이동가능하게 결합되는 가압부(220)와 손잡이(260)를 포함하는 피스톤 가압모듈(200); 상기 주사기 거치부(110)에 설치되며 상기 주사기(400)의 실린더(410)가 삽입되는 실린더 안착부(310)를 포함하는 주사바늘 보호체(300);를 포함하되, 상기 주사기 거치부(110)에는 설치되는 주사기(400)의 실린더(410)를 고정 결합할 수 있는 실린더 플랜지 결합홈(140)이 형성되어 있고, 상기 주사바늘 보호체(300)는 상기 주사기 거치부(110)의 내부에서 상기 주사기의 실린더(410) 및 상기 본체(100)와 상대이동 가능하게 설치되어, 상기 주사기 거치부(110)에 설치된 주사기(400)의 주사바늘(430)이 외부로 노출되지 않은 상태에서 동물에게 주사액(a)을 투약할 수 있도록 구성되어 있는 것을 특징으로 하는 동물용 주사기 보조장치., Ltext: 농업, prediction: 임업
959/1059 Row 959: application_number: 1020190124820, combined_string: invention_title: IoT 센서를 활용한 농업 및 목축용 실시간 모니터링 시스템 및 방법 abstract: 본 발명은 농업 및 목축에 있어서, IoT 센서를 활용하여 이동 개체에 부착된 태그(Tag) 및 WiFi 시그널을 감지하고 LMS(Livestock Monitoring System)를 활용하여 이동 개체의 가상 펜스(Virtual Fence) 접근 및 이상 행동을 모니터링할 수 있도록 구현한 IoT 센서를 활용한 농업 및 목축용 실시간 모니터링 시스템 및 방법에 관한 것으로, 태그/WiFi 시그널 발생기가 이동 개체에 설치되어 태그/WiFi 시그널을 발생시켜 주며; IoT 센서가 태그/WiFi 시그널 발생기에서 발생시킨 태그/WiFi 시그널을 감지하며; LMS부가 IoT 센서에서 감지한 태그/WiFi 시그널을 수신받아, 이동 개체의 가상 펜스 접근 및 이상 행동을 모니터링한다. claims: 이동 개체에 설치되어 태그/WiFi 시그널을 발생시켜 주기 위한 태그/WiFi 시그널 발생기;상기 태그/WiFi 시그널 발생기에서 발생시킨 태그/WiFi 시그널을 감지하기 위한 IoT 센서; 및상기 IoT 센서에서 감지한 태그/WiFi 시그널을 수신받아, 이동 개체의 가상 펜스 접근 및 이상 행동을 모니터링하기 위한 LMS부를 포함하는 IoT 센서를 활용한 농업 및 목축용 실시간 모니터링 시스템.이동 개체에 설치되어 있는 태그/WiFi 시그널 발생기가 태그/WiFi 시그널을 발생시켜 주는 단계;IoT 센서가 상기 태그/WiFi 시그널 발생기에서 발생시킨 태그/WiFi 시그널을 감지하는 단계; 및LMS부가 상기 IoT 센서에서 감지한 태그/WiFi 시그널을 수신받아, 이동 개체의 가상 펜스 접근 및 이상 행동을 모니터링하는 단계를 포함하는 IoT 센서를 활용한 농업 및 목축용 실시간 모니터링 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

960/1059 Row 960: application_number: 1020217012096, combined_string: invention_title: 대기 메탄 및 아산화질소 배출을 줄이기 위한 조성물 및 방법 abstract: 본 발명은 가축 사료 첨가제 및/또는 보충제를 사용하여 대기 메탄 및/또는 아산화질소 배출을 감소시키는 조성물 및 방법을 제공한다. 바람직한 실시예에서, 동물이 사료 및/또는 음용수를 삼키기 전에, 유익한 미생물 및/또는 이들의 성장 부산물을 포함하는 조성물을 이들과 접촉시킨다. 상기 조성물은, 예를 들어 상기 동물의 소화계 내 메탄생성 미생물을 제어할 수 있으므로, 동물 및 동물의 폐기물로부터 생산된 장 메탄 배출의 함량을 감소시킨다. claims: 대기 메탄 배출 감소를 위한 방법으로서, 유익한 미생물 및/또는 미생물 성장 부산물을 포함하는 조성물을 동물이 사료 및/또는 음용수를 삼키기 전에 동물 사료 및/또는 음용수와 접촉시키고, 상기 미생물은 Wickerhamomyces anomalus, Bacillus licheniformis, Bacillus amyloliquefaciens, Bacillus subtilis, Starmerella bombicola, Pichia occidentalis, Pleurotus ostreatus, Lentinula edodes, Monascus purpureus, Trichoderma harzianum, Trichoderma viride, Acremonium chrysogenum, Saccharomyces cerevisiae, 및/또는 Saccharomyces boulardii이고,상기 가축에게 사료 및/또는 음용수를 제공하고 상기 가축이 상기 사료 및/또는 물을 삼키고, 및상기 조성물의 가축 섭취로 상기 조성물이 가축의 소화계 내 존재하는 메탄생성 미생물과 접촉할 수 있고 상기 메탄 생성 미생물을 제어할 수 있게 하는, 방법.제18항에 있어서, 상기 평가된 현지 조건은 다음 중 하나 이상을 포함하는 방법: 동물의 연령, 건강, 크기 및/또는 종; 동물 생산을 위한 목적; 동물 장 내 미생물의 종; 설미에서 온실 가스 배출의 타입; 현재 기후; 년중 현재 현재 계절 및 시간; 및 조성물 사용의 모드 및/또는 사용 속도.길들여진 동물을 사육하기 위한 조성물로서, 상기 조성물은 미생물 및/또는 미생물 성장 부산물을 포함하고, 여기서 상기 미생물은 Wickerhamomyces anomalus, Bacillus licheniformis, Bacillus amyloliquefaciens, Bacillus subtilis, Starmerella bombicola, Pichia occidentalis, Pleurotus ostreatus, Lentinula edodes, Monascus purpureus, Trichoderma harzianum, Trichoderma viride, Acremonium chrysogenum, Saccharomyces cerevisiae, 및/또는 Saccharomyces boulardii인, 조성물., Ltext: 농업, prediction: 임업
961/1059 Row 961: application_number: 1020190118533, combined_string: invention_title: 친환경 가축가금 사육 방법 abstract: 본 발명은 친환경 가축가금 사육 방법에 관한 것으로, 보다 상세하게는 제올라이트, 운모, 고령토와 같은 광물질이 첨가된 물을 가축가금에 음용수로 공급하는 제1사육방법과; 칼슘, 비타민D, 젖산과 같은 영양성분을 사료 또는 음용수에 첨가하여 가축가금에 급여하는 제2사육방법을; 병행함으로써 가축가금의 면역력 강화하고, 가축가금의 소화를 돕는 것 뿐만 아니라 영양요소를 충족시키며, 나아가 운모가 첨가된 발효어분과 같은 사료보조성분을 사료에 혼합하여 가축가금에 급여하는 제3사육방법을; 병행함으로써 가축가금을 단시간에 증체시킬 수 있을 뿐만 아니라 사료의 효율을 증가시켜 사료비를 절감시킬 수 있고, 또한 유기물, 무기물, 톱밥이 혼합된 깔개를 사육장 바닥에 깔아 가축가금을 사육하는 제4사육방법을; 일체로 병행함으로써 사육장 환경을 개선시킴은 물론, 사용 후 깔개를 친환경 토양개량제 또는 퇴비로 재활용할 수 있는 친환경 가축가금 사육 방법에 관한 것이다. claims: 제올라이트, 운모, 고령토를 포함하는 제1성분이 첨가된 수소이온농도 pH 6 ~ 8인 물을 가축가금에 음용수로 공급하는 제1사육방법과; 칼슘, 비타민D, 젖산을 포함하는 제2성분을 사료 또는 음용수에 첨가하여 가축가금에 급여하는 제2사육방법을; 포함하는 것을 특징으로 하는 친환경 가축가금 사육 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

962/1059 Row 962: application_number: 1020190110341, combined_string: invention_title: 변이된 COMT 유전자를 포함하는 사료용 작물 및 이의 용도 abstract: 본 발명은 변이된 COMT를 코딩하는 폴리뉴클레오티드, 상기 폴리뉴클레오티드로부터 발현되는 변이된 COMT 단백질, 상기 폴리뉴클레오티드를 포함하는 형질전환 벡터, 상기 형질전환 벡터가 도입되어 형질전환된 사료용 작물, 상기 형질전환된 사료용 작물을 포함하는 사료용 조성물, 상기 사료용 조성물을 포함하는 사료, 상기 사료를 이용한 가축의 사육방법 및 상기 형질전환된 사료용 작물의 생산방법에 관한 것이다. 본 발명에서 제공하는 형질전환된 사료용 작물은 일반적인 사료용 작물에 비하여 총 리그닌 함량이 감소되어 이로부터 얻어진 바이오매스의 소화율이 증가될 뿐만 아니라, 헤미셀룰로오스의 일종인 자일로스의 함량이 증가되는 특징을 나타내므로, 상기 형질전환된 사료용 작물은 다양한 가축 비육용 사료의 유효성분으로서 활용될 수 있을 것이다. claims: 사료용 작물에 도입되어, 리그닌의 합성을 억제하고, 헤미셀룰로오스의 합성을 촉진할 수 있는, 변이된 COMT(caffeic acid O-methyltransferase)를 코딩하는 폴리뉴클레오티드로, 상기 폴리뉴클레오티드는 서열번호 3의 염기서열을 갖는 COMT 유전자의 334번 염기가 결실되거나 또는 상기 334번 위치에 A 또는 T가 삽입된 것인, 폴리뉴클레오티드.제1항 내지 제3항 중 어느 한 항의 폴리뉴클레오티드로부터 발현되는, 변이된 COMT(caffeic acid O-methyltransferase) 단백질.제1항 내지 제3항 중 어느 한 항의 폴리뉴클레오티드를 포함하고, 사료용 작물에서 상기 폴리뉴클레오티드를 도입하여 발현시킬 수 있는 형질전환 벡터. 제7항의 형질전환 벡터가 도입되어, 소화율이 향상되도록 형질전환된, 사료용 작물.제9항의 사료용 조성물을 포함하는 사료.제10항의 사료를 가축에게 급이하는 단계를 포함하는, 가축의 사육방법.제8항의 사료용 작물의 종자를 파종, 재배 및 수확하는 단계를 포함하는, 사료용 작물의 생산방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

963/1059 Row 963: application_number: 1020210142802, combined_string: invention_title: 스마트팜 양돈 시스템 및 방법 abstract: 스마트팜 양돈 시스템 및 방법이 개시된다. 스마트팜 양돈 시스템은 유저 단말로부터 사용자 조작에 따른 돼지의 축사 변동 사항을 제공받는 유저 대응부; 및 상기 축사 변동 사항에 관한 정보가 상응하는 돼지의 사육 데이터에 추가되도록 상기 사육 데이터를 갱신하는 데이터 갱신부를 포함한다. claims: 미리 지정된 GUI(Graphical User Interface) 환경의 관리 화면을 이용하여, 실제 양돈 현장에서의 축사 이동 대상인 대상 돼지에 상응하는 개체 이미지를 가상의 제1 구획 영역에서 가상의 제2 구획 영역으로 드래그 앤 드롭(Drag and Drop) 방식으로 이동시키는 사용자 조작에 따른 상기 대상 돼지의 축사 변동 사항을 유저 단말로부터 제공받는 유저 대응부; 및드래그 앤 드롭 방식으로 이동된 개체 이미지에 상응하는 상기 대상 돼지의 사육 데이터에 상기 축사 변동 사항에 관한 정보가 추가되도록 상기 사육 데이터를 갱신하는 데이터 갱신부를 포함하되,상기 관리 화면은 돼지가 사육되는 실제 양돈 현장에 구비된 실제의 구획 영역들에 일대일 대응되는 가상의 구획 영역들과, 실제의 구획 영역들 각각에서 사육되는 돼지에 대응되도록 상응하는 가상의 구획 영역에 상응하는 돼지의 개체 이미지가 표시되도록 구현되고,가상의 구획 영역에 표시되는 개체 이미지는 가상의 구획 영역에 대응되는 실제의 구획 영역에서 사육되는 돼지의 식별정보에 대응되도록 관리되며,상기 대상 돼지에 상응하는 개체 이미지가 이동되는 상기 가상의 제2 구획 영역은 상기 가상의 제1 구획 영역에 대응되는 실제의 제1 구획 영역에서 사육되는 상기 대상 돼지의 생육 주기에 부합하는 돼지들을 모아 사육하기 위해 미리 설정된 실제의 제2 구획 영역에 대응되는 가상의 구획 영역이며, 출생으로 사육이 개시되어 출하 또는 도축으로 인해 사육이 종료되는 전체 생육 기간 동안에 반복되는 상기 대상 돼지의 실제 양돈 현장에서의 생육 주기별 축사 이동에 대응되도록 상기 대상 돼지에 상응하는 개체 이미지를 드래그 앤 드롭 방식으로 상응하는 가상의 구획 영역으로 이동시키는 사용자 조작에 따른 축사 변동 사항이 순차적으로 제공되는 것만으로, 각각의 시점에서 가상의 구획 영역에 대응되도록 상기 대상 돼지가 사육되는 실제 양돈 현장에서의 축사가 인식되어, 상기 대상 돼지가 전체 생육 기간 동안 실제 양돈 현장에서 이동되며 사육된 각각의 축사와 상기 대상 돼지를 대상으로 하여 수집된 사육 데이터가 상기 대상 돼지의 전체 생육 기간 동안 연속되도록 관리되는 것을 특징으로 하는 스마트팜 양돈 시스템.스마트팜 양돈 방법을 수행하도록 하는 컴퓨터-판독 가능 매체에 저장된 컴퓨터 프로그램으로서, 상기 컴퓨터 프로그램은 컴퓨터로 하여금 이하의 단계들을 수행하도록 하며, 상기 단계들은,돼지의 사육을 위한 실제 양돈 현장의 실제의 구획 영역들에 일대일 대응되는 가상의 구획 영역들과, 실제의 구획 영역들 각각에서 사육되는 돼지에 대응되는 개체 이미지가 각 가상의 구획 영역에 표시된 GUI(Graphical User Interface) 환경의 관리 화면을 이용하여, 실제 양돈 현장에서의 축사 이동 대상인 대상 돼지에 상응하는 개체 이미지를 가상의 제1 구획 영역에서 가상의 제2 구획 영역으로 드래그 앤 드롭(Drag and Drop) 방식으로 이동시키는 사용자 조작에 따른 상기 대상 돼지의 축사 변동 사항을 유저 단말로부터 제공받는 단계; 드래그앤 드롭 방식으로 이동된 개체 이미지에 상응하는 상기 대상 돼지의 사육 데이터에 상기 축사 변동 사항에 관한 정보가 추가되도록 상기 사육 데이터를 갱신하는 단계; 및상기 대상 돼지에 상응하는 개체 이미지가 상기 가상의 제2 구획 영역으로 이동되어 위치하는 동안, 상기 가상의 제2 구획 영역에 대응되는 실제의 제2 구획 영역에 대해 수집된 부가 정보가 상기 사육 데이터에 포함되도록 상기 사육 데이터를 갱신하는 단계를 포함하되,가상의 구획 영역에 표시되는 개체 이미지는 가상의 구획 영역에 대응되는 실제의 구획 영역에서 사육되는 돼지의 식별정보에 대응되도록 관리되며,상기 대상 돼지에 상응하는 개체 이미지가 이동되는 상기 가상의 제2 구획 영역은 상기 가상의 제1 구획 영역에 대응되는 실제의 제1 구획 영역에서 사육되는 상기 대상 돼지의 생육 주기에 상응하는 돼지들을 모아 사육하기 위해 미리 설정된 실제의 제2 구획 영역에 대응되는 가상의 구획 영역이며, 출생으로 사육이 개시되어 출하 또는 도축으로 인해 사육이 종료되는 전체 생육 기간 동안에 반복되는 상기 대상 돼지의 실제 양돈 현장에서의 생육 주기별 축사 이동에 대응되도록 상기 대상 돼지에 상응하는 개체 이미지를 드래그 앤 드롭 방식으로 상응하는 가상의 구획 영역으로 이동시키는 사용자 조작에 따른 축사 변동 사항이 순차적으로 제공되는 것만으로, 각각의 시점에서 가상의 구획 영역에 대응되도록 상기 대상 돼지가 사육되는 실제 양돈 현장에서의 축사가 인식되어, 상기 대상 돼지가 전체 생육 기간 동안 실제 양돈 현장에서 이동되며 사육된 각각의 축사와 상기 대상 돼지를 대상으로 하여 수집된 사육 데이터가 상기 대상 돼지의 전체 생육 기간 동안 연속되도록 관리되되,실제 양돈 현장에서 사육되는 상기 대상 돼지에 대해 전체 생육 기간 동안 생성되는 사육 데이터의 정보 연속성이 유지되도록 하기 위해, 상기 사육 데이터에는 상기 대상 돼지에 상응하는 개체 이미지가 상기 가상의 제1 구획 영역에 위치하는 동안에, 상기 가상의 제1 구획 영역에 대응되는 실제의 제1 구획 영역에 대해 이미 수집되어 포함된 부가 정보가 유지되고,상기 부가 정보는 실제의 구획 영역에 대해 수집된 온도, 습도 및 가스 농도인 요소 항목들을 포함하는 상기 대상 돼지의 사육 환경에 관한 정보를 포함하는 것을 특징으로 하는 컴퓨터-판독 가능 매체에 저장된 컴퓨터 프로그램., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

964/1059 Row 964: application_number: 1020210002483, combined_string: invention_title: IoT 스마트 기술을 이용한 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템 abstract: 본 발명은 IoT 스마트 기술을 이용한 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템에 관한 것으로, IoT 스마트 기술을 이용하여 조류독감(AI)과 구제역(FMD) 및 아프리카돼지열병(ASF) 바이러스를 실시간으로 감시하여 그 결과값을 DB에 저장하고, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 모니터에 실시간으로 표시하여 모니터링하고, 바이러스에 필요한 방역 및 소독제 정보를 인터넷망을 통해 제공함으로써, 효과적으로 바이러스를 살균 및 소독할 수 있고 바이러스 발생 지역을 체계적으로 방역 및 관리할 수 있다.본 발명에 의한 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템은, 바이러스가 발생하기 쉬운 장소에 설치되며, 강수, 호수, 하수, 토양, 공기 중에 포함된 바이러스를 센서로 주기적으로 감지하여 조류독감(AI), 구제역(FMD), 아프리카돼지열병(ASF) 바이러스를 판별하고 그 결과값을 저장하고 통신망을 통해 전송하는 복수의 바이러스 감지 장치(110)와, 상기 통신망을 통해 상기 복수의 바이러스 감지 장치(110)로부터 수신된 결과값을 DB(210)에 저장하고, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 모니터에 실시간으로 표시하여 모니터링하고, 바이러스에 필요한 방역 및 소독제 정보를 제공하는 모니터링 관제 서버(200)와, 상기 모니터링 관제 서버(200)에 인터넷망을 통해 접속하여, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 확인하고, 바이러스에 필요한 방역 및 소독제 정보를 제공받으며, 방역 정보를 입력하여 등록하는 스마트폰(300)의 바이러스 앱(310)을 포함하는 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템에 있어서, 상기 바이러스의 소독제는, 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 후 10∼30분 동안 원심분리기에서 2000RPM 이상의 고속교반으로 수화 및 분쇄를 함께 진행하여 입도 1000메쉬 이상의 액상화를 갖는 액상소석회(Ca(OH)2)로 구성되며, 상기 생석회(CaO)는 석회석(CaCO3)을 1,000∼1,200℃에서 연소시켜 제조한 산화칼슘이고, 상기 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 액상소석회(Ca(OH)2) 85∼92중량%에 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 입도 100∼200메쉬의 숯 분말 5∼10중량%를 혼합하여 구성된다.본 발명에 따르면, 환경오염을 발생하지 않고 조류독감(AI)과 구제역(FMD) 및 아프리카돼지열병(ASF) 바이러스를 효과적으로 소독할 수 있는 효과가 있다. claims: 바이러스가 발생하기 쉬운 장소에 설치되며, 강수, 호수, 하수, 토양, 공기 중에 포함된 바이러스를 센서로 주기적으로 감지하여 조류독감(AI), 구제역(FMD), 아프리카돼지열병(ASF) 바이러스를 판별하고 그 결과값을 저장하고 통신망을 통해 전송하는 복수의 바이러스 감지 장치(110)와, 상기 통신망을 통해 상기 복수의 바이러스 감지 장치(110)로부터 수신된 결과값을 DB(210)에 저장하고, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 모니터에 실시간으로 표시하여 모니터링하고, 바이러스에 필요한 방역 및 소독제 정보를 제공하는 모니터링 관제 서버(200)와, 상기 모니터링 관제 서버(200)에 인터넷망을 통해 접속하여, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 확인하고, 바이러스에 필요한 방역 및 소독제 정보를 제공받으며, 방역 정보를 입력하여 등록하는 스마트폰(300)의 바이러스 앱(310)을 포함하는 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템에 있어서,상기 바이러스의 소독제는,물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 후 10∼30분 동안 원심분리기에서 2000RPM 이상의 고속교반으로 수화 및 분쇄를 함께 진행하여 입도 1000메쉬 이상의 액상화를 갖는 액상소석회(Ca(OH)2)로 구성되며,상기 생석회(CaO)는 석회석(CaCO3)을 1,000∼1,200℃에서 연소시켜 제조한 산화칼슘이고,상기 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 액상소석회(Ca(OH)2) 85∼92중량%에 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 입도 100∼200메쉬의 숯 분말 5∼10중량%를 혼합한,조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템., Ltext: 농업, prediction: 임업
965/1059 Row 965: application_number: 1020200164328, combined_string: invention_title: 포토니아 듀얼 기기 abstract: 포토니아 듀얼 기기가 개시된다. 본 발명은, 가시광선대역의 광을 변조하여 극미약광과 백색광의 형태로 생명체에 전달하는 포토니아 듀얼 기기를 제공한다. 본 발명에 따르면, 생명체, 예컨대 돼지의 생체 에너지를 향상시킴으로서 면역, 번식, 대사 효율에 기여할 수 있다. claims: 중앙으로 극미약광 방사 영역; 및상기 극미약광 방사 영역의 둘레로 배치된 백색광 방사 영역;이 포함되는 것을 특징으로 하는 포토니아 듀얼 기기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

966/1059 Row 966: application_number: 1020200157144, combined_string: invention_title: 협잡물 처리장치 abstract: 본 발명은 하수처리시설, 돈사, 우사 등으로부터 배출되는 각종 협잡물이 유입되어 1차적으로 여과수를 배출하는 호퍼와, 상기 호퍼에 의하여 1차적으로 여과수가 배출된 협잡물을 탈수시켜 탈수된 협잡물을 외부로 배출시키는 스크류 프레스부를 구비하는 협잡물 처리장치에 관한 것으로, 구체적인 특징은 상기 스크류 프레스부는 모터에 의하여 회전되는 축; 상기 축의 외주면에 설치되어 상기 축의 일단부로부터 타단부쪽으로 상기 호퍼로부터 유입되는 협잡물을 이동시키는 스크류; 중심에 상기 축이 통과되도록 원통형상으로 이루어지며, 상기 호퍼로부터의 협잡물이 유입되는 유입구와 탈수된 협잡물을 외부로 배출시키는 배출부가 형성된 하우징; 상기 축과 평행하도록 하우징의 내부에 설치되고 상기 스크류의 외경보다 큰 내경을 갖으며, 상기 스크류에 의하여 이송되는 협잡물을 탈수시키는 바 케이지; 상기 바 케이지의 타단부에 설치되어 상기 스크류에 의하여 이송되는 탈수 협잡물에 의하여 가압되고, 기설정된 압력 이상의 압력이 가압될 때 개방되어 탈수 협잡물을 상기 하우징의 배출부를 통하여 외부로 배출시키는 탈수 협착물 배출밸브를 포함하는 것이다. claims: 수분을 함유하는 협잡물이 유입되어 1차적으로 여과수를 배출하는 호퍼와, 상기 호퍼에 의하여 1차적으로 여과수가 배출된 협잡물을 탈수시켜 탈수된 협잡물을 외부로 배출시키는 스크류 프레스부를 구비하는 협잡물 처리장치에 있어서: 상기 스크류 프레스부는 모터에 의하여 회전되는 축; 상기 축의 외주면에 설치되어 상기 축의 일단부로부터 타단부쪽으로 상기 호퍼로부터 유입되는 협잡물을 이동시키는 스크류; 중심에 상기 축이 통과되도록 원통형상으로 이루어지며, 상기 호퍼로부터의 협잡물이 유입되는 유입구와 탈수된 협잡물을 외부로 배출시키는 배출부가 형성된 하우징;상기 축과 평행하도록 하우징의 내부에 설치되고 상기 스크류의 외경보다 큰 내경을 갖으며, 상기 스크류에 의하여 이송되는 협잡물을 탈수시키는 바 케이지;상기 바 케이지의 타단부에 설치되어 상기 스크류에 의하여 이송되는 탈수 협잡물에 의하여 가압되고, 기설정된 압력 이상의 압력이 가압될 때 개방되어 탈수 협잡물을 상기 하우징의 배출부를 통하여 외부로 배출시키는 탈수 협잡물 배출밸브를 포함하며,상기 바 케이지는 원형상으로 형성되는 양쪽 측단부에 설치되는 측단 테두리들과, 양단부가 상기 측단 테두리들 각각에 결합되어 상기 축과 평행하게 설치되며 상기 측단 테두리를 따라서 균일한 간격으로 설치되되 단면이 원형으로 이루어지는 바들로 이루어지는 것을 특징으로 하는 협잡물 처리장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

967/1059 Row 967: application_number: 1020200149101, combined_string: invention_title: 돈사 구조 abstract: 본 발명은 돈사의 냉난방 비용을 절감할 수 있도록 된 새로운 돈사 구조에 관한 것이다.본 발명에 따른 돈사 구조는, 상기 바닥판(20)이, 상기 저장부(10)의 내부에 상호 연결되도록 배치되어 상기 저장부(10) 내부의 공간을 분뇨가 저장되는 슬러리 피트(13)와 공기가 통과하는 공기통로(12)로 구획하는 제1 및 제2 급기관(22,23)과, 둘레면이 상기 제1 급기관(22) 또는 제2 급기관(23)에 올려지도록 배치되어 상기 슬러리 피트(13)의 상부를 덮는 바닥패널(24)로 구성되어, 외부의 공기가 제1 및 제2 급기관(22,23)을 통과하면서 온도조절된 후 돈사의 내부로 공급됨으로, 여름철이나 겨울철에 돈사 내부의 온도를 적절하게 유지하기 위하여 공기를 가열 또는 냉각시키는데 소요되는 비용을 절감할 수 있는 장점이 있다. claims: 지면을 굴착하여 구덩이를 형성하고 구덩이의 내측면에 시멘트를 도포하여 구성된 저장부(10)와, 상기 저장부(10)의 상면을 막도록 설치된 바닥판(20)과, 상기 바닥판(20)의 상부를 덮도록 시공된 돈사본체(30)와, 상기 바닥판(20)의 상면에 구비되어 바닥판(20) 상부의 공간을 작업자가 통과하는 통로(41)와 돼지가 사육되는 돈방(42)으로 구획하는 격판(40)을 포함하며, 상기 돈사본체(30)의 일측에는 배기팬(35)이 구비된 배기구(34)가 형성된 돈사에 있어서, 상기 바닥판(20)은 상기 저장부(10)의 내부에 상호 연결되도록 배치되어 상기 저장부(10) 내부의 공간을 분뇨가 저장되는 슬러리 피트(13)와 공기가 통과하는 공기통로(12)로 구획하는 제1 및 제2 급기관(22,23)과, 둘레면이 상기 제1 급기관(22) 또는 제2 급기관(23)에 올려지도록 배치되어 상기 슬러리 피트(13)의 상부를 덮는 바닥패널(24)을 포함하며, 상기 제1 급기관(22)은 일단은 상기 돈사본체(30)의 외측으로 연장되고, 상기 제2 급기관(23)의 상면에는 급기공(23c)이 형성되어, 외부의 공기가 상기 제1 급기관(22)의 내부로 유입되어 제2 급기관(23)으로 공급된 후, 상기 급기공(23c)을 통해 돈사본체(30)의 내부로 공급되며, 상기 제1 급기관(22)은 하단이 저장부(10)의 내부 바닥면에 수밀하게 결합되는 한 쌍의 측판(22a)과 상기 측판(22a)의 상단에 수밀하게 결합된 상판(22b)을 갖도록 구성되어 상기 돈방(42)의 하측에 위치되고, 상기 제2 급기관(23)은 하단이 상기 저장부(10)의 내부 바닥면에 수밀하게 결합되는 한 쌍의 측판(23a)과 상기 측판(23a)의 상단에 탈착가능하게 결합되는 상판(23b)을 갖도록 구성되어 상기 통로(41)의 하측에 위치되며, 상기 바닥패널(24)에는 배출공(24a)이 상하면을 관통하도록 형성되어, 돈방(42)에서 사육되는 돼지가 배출하는 분뇨가 배출공(24a)을 통해 하측의 슬러리 피트(13)로 배출되어 저장되도록 구성되고, 상기 격판(40)은 상기 제2 급기관(23)의 측판(23a)의 상단에 구비되고,상하방향으로 연장되며 상단이 개방된 관체형상으로 구성되어 상기 돈사본체(30)의 외측에 구비되며 상기 제1 급기관(22)이 연결되는 외부급기관(25)과, 상기 외부급기관(25)의 상측에 구비되며 승강구동수단(52)에 의해 승강되어 상기 외부급기관(25)의 개폐정도를 조절하는 개폐덮개(51)와, 상기 제1 급기관(22)의 중간부에 구비되어 제1 급기관(22)을 제1 및 제2 급기부(22d,22e)로 구획하는 제1 댐퍼(53)와, 열전도율이 높은 금속재로 구성되며 양단이 상기 제1 및 제2 급기부(22d,22e)에 연결되고 중간부는 상기 슬러리 피트(13)를 통과하도록 배치된 통기관(54)과, 상기 통기관(54)의 중간부에 구비되어 통기관(54)을 통과하는 공기의 흐름을 제어하는 제2 댐퍼(55)와, 상기 제2 급기관(23)의 내부에 구비되어 제2 급기관(23)을 통과하는 공기의 속도를 측정하는 풍속센서(56)와, 상기 제2 급기관(23)에 구비되어 제2 급기관(23)을 통과하는 공기의 온도를 측정하는 제1 온도센서(57)와, 상기 슬러리 피트(13)의 내부에 구비되어 슬러리 피트(13)에 저장된 분뇨의 온도를 측정하는 제2 온도센서(58)와, 상기 풍속센서(56)와 제1 및 제2 온도센서(57,58)의 신호를 수신하며 상기 승강구동수단(52)과 제1 및 제2 댐퍼(53,55)의 작동을 제어하는 제어수단(59)을 더 포함하며, 상기 제어수단(59)은 상기 풍속센서(56)의 신호를 수신하여 제2 급기관(23)을 통과하는 공기의 속도를 수신하고 상기 승강구동수단(52)을 제어하여 상기 개폐덮개(51)를 승강시킴으로써, 상기 제2 급기관(23)을 통과하는 공기의 속도가 미리 입력된 속도를 유지하도록 조절하고, 상기 제1 온도센서(57)의 신호를 수신하여 상기 제2 급기관(23)을 통과하는 공기의 온도가 미리 설정된 기준온도에 비해 낮을 경우, 제2 온도센서(58)의 신호를 수신하여 상기 슬러리 피트(13)에 저장된 분뇨의 온도를 측정하고, 제2 온도센서(58)에 측정된 분뇨의 온도가 상기 제1 온도센서(57)에 의해 측정된 공기의 온도에 비해 높을 경우, 상기 제1 댐퍼(53)를 작동시켜 제2 급기관(23)의 중간부를 밀폐하고 제2 댐퍼(55)를 개방하여, 제2 급기관(23)을 통과하는 공기가 상기 통기관(54)을 통과하도록 함으로써, 공기가 상기 슬러리 피트(13)에 저장된 분뇨에 의해 가열되도록 하는 것을 특징으로 하는 돈사 구조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

968/1059 Row 968: application_number: 1020200138074, combined_string: invention_title: 딥러닝 기반 객체 추적 및 행동 분석을 이용한 스마트 축산관리시스템 및 방법 abstract: 본 발명의 다른 일 실시예에 따른 딥러닝 기반 객체 추적 및 행동 분석을 이용한 스마트 축산관리시스템은 돈사 내의 돼지 객체의 머리에 부착되어, 상기 돼지 객체의 뇌파신호를 측정하여 전송하는 뇌파탐지모듈; 돈사 내의 돼지 객체의 모션 이미지를 촬영하는 제1 촬상장치; 상기 돼지 객체의 열화상 이미지를 생성하는 제2 촬상장치; 상기 돼지 객체의 호흡 및 기침소리를 포함하는 음향정보를 수집하는 음향수집장치; 상기 뇌파신호, 모션 이미지, 상기 열화상 이미지 및 상기 음향정보를 기초로 해당 돼지 객체의 질병발생유무 및 질병의 종류를 예측판단하는 모니터링 서버; 및 상기 모니터링 서버로부터 돼지 객체의 질병발생 알림메시지를 제공받는 관리자 단말을 포함하고, 상기 모니터링 서버는 상기 돼지 객체에서 감지된 뇌파신호의 뇌파변이도를 통해 돼지 객체의 수면상태, 이상발작 상태, 우울감과 관련된 뇌파(electroencephalographic, EEG)를 분류한 후, 레퍼런스와 비교하여 뇌파 변이도의 패턴을 분석하는 뇌파분석부; 상기 관리자 단말로부터 타겟 객체(돼지)가 입력되면, 타겟 객체(돼지)에 위치한 뇌파탐지모듈의 위치신호를 기초로 타겟 객체의 이동경로를 역순으로 트랙킹하는 경로 추적부; 타겟팅된 돼지객체의 이동경로 중 움직임 변화에 대한 모션 이미지를 기초로 상기 돼지 객체의 행동패턴 및 자세를 분석하는 행동패턴 및 자세 분석부; 상기 열화상 이미지를 기초로 상기 돼지 객체의 체온을 분석하는 체온 분석부; 상기 음향정보를 기초로 상기 돼지 객체의 호흡주기, 기침소리의 크기 및 발생주기, 울음소리 중 적어도 하나 이상을 분석하는 음향 분석부; 및 돼지 객체의 뇌파변이도 패턴, 행동패턴의 불규칙한 자세변화, 호흡주기, 기침소리를 기초로 질병 유무를 1차 판단하고, 1차 선별된 돼지객체의 부위별 체온 및 체온변화를 기초로 질병발생유무를 2차 판단하는 질병발생 판단부를 포함하고, 상기 행동자세 및 패턴 분석부는 상기 모션 이미지를 기초로 상기 돈사 내의 돼지의 포즈패턴변화를 Standing, Lying, Sitting 중 어느 하나로 분류하고, 상기 돼지가 이동 시에, 포즈패턴변화를 거리 대비 시간으로 분석하고, 상기 체온 분석부는 상기 포즈패턴변화에 따라 발열되는 돼지들의 부위 별 체온변화를 분석하고, 상기 질병발생 판단부는 딥러닝 학습 알고리즘을 학습한 질병이 발생된 돼지들의 시계열적 포즈패턴변화, 호흡주기, 기침소리의 변화를 기초로 상기 돼지 객체를 1차 선별하는 것을 특징으로 한다. claims: 돈사 내의 돼지 객체의 머리에 부착되어, 상기 돼지 객체의 뇌파신호를 측정하여 전송하는 뇌파탐지모듈;돈사 내의 돼지 객체의 모션 이미지를 촬영하는 제1 촬상장치;상기 돼지 객체의 열화상 이미지를 생성하는 제2 촬상장치;상기 돼지 객체의 호흡 및 기침소리를 포함하는 음향정보를 수집하는 음향수집장치;상기 뇌파신호, 모션 이미지, 상기 열화상 이미지 및 상기 음향정보를 기초로 해당 돼지 객체의 질병발생유무 및 질병의 종류를 예측판단하는 모니터링 서버; 및상기 모니터링 서버로부터 돼지 객체의 질병발생 알림메시지를 제공받는 관리자 단말을 포함하고,상기 모니터링 서버는상기 돼지 객체에서 감지된 뇌파신호의 뇌파변이도를 통해 돼지 객체의 수면상태, 이상발작 상태, 우울감과 관련된 뇌파(electroencephalographic, EEG)를 분류한 후, 레퍼런스와 비교하여 뇌파 변이도의 패턴을 분석하는 뇌파분석부;상기 관리자 단말로부터 타겟 객체(돼지)가 입력되면, 타겟 객체(돼지)에 위치한 뇌파탐지모듈의 위치신호를 기초로 타겟 객체의 이동경로를 역순으로 트랙킹하는 경로 추적부;타겟팅된 돼지객체의 이동경로 중 움직임 변화에 대한 모션 이미지를 기초로 상기 돼지 객체의 행동패턴 및 자세를 분석하는 행동패턴 및 자세 분석부;상기 열화상 이미지를 기초로 상기 돼지 객체의 체온을 분석하는 체온 분석부;상기 음향정보를 기초로 상기 돼지 객체의 호흡주기, 기침소리의 크기 및 발생주기, 울음소리 중 적어도 하나 이상을 분석하는 음향 분석부; 및돼지 객체의 뇌파변이도 패턴, 행동패턴의 불규칙한 자세변화, 호흡주기, 기침소리를 기초로 질병 유무를 1차 판단하고, 1차 선별된 돼지객체의 부위별 체온 및 체온변화를 기초로 질병발생유무를 2차 판단하는 질병발생 판단부를 포함하고,상기 행동자세 및 패턴 분석부는상기 모션 이미지를 기초로 상기 돈사 내의 돼지의 포즈패턴변화를 Standing, Lying, Sitting 중 어느 하나로 분류하고, 상기 돼지가 이동 시에, 포즈패턴변화를 거리 대비 시간으로 분석하고,상기 체온 분석부는 상기 포즈패턴변화에 따라 발열되는 돼지들의 부위 별 체온변화를 분석하고,상기 질병발생 판단부는딥러닝 학습 알고리즘을 학습한 질병이 발생된 돼지들의 시계열적 포즈패턴변화, 호흡주기, 기침소리의 변화를 기초로 상기 돼지 객체를 1차 선별하는 것을 특징으로 하는 딥러닝 기반 객체 추적 및 행동 분석을 이용한 스마트 축산관리시스템.뇌파탐지모듈을 이용하여 돈사 내의 돼지 객체의 뇌파신호를 측정하는 단계;경로 추적부에서 관리자 단말로부터 타겟 객체(돼지)가 입력받으면, 타겟 객체(돼지)에 위치한 뇌파탐지모듈의 위치신호를 기초로 타겟 객체의 이동경로를 역순으로 트랙킹하는 단계;뇌파분석부에서 돼지 객체에서 감지된 뇌파신호의 뇌파변이도를 통해 돼지들의 수면상태, 이상발작 상태, 우울감과 관련된 뇌파(electroencephalographic, EEG)를 분류한 후, 레퍼런스와 비교하여 뇌파 변이도의 패턴을 분석하는 단계;행동패턴 및 자세 분석부에서 타겟팅된 돼지객체의 이동경로 중 움직임 변화에 대한 모션 이미지를 기초로 상기 돼지 객체가 이동 시에, 포즈패턴변화를 거리 대비 시간으로 분석한 후, 질병걸린 돼지들의 표본 데이터와 비교를 통해 행동이상 여부를 판단하는 단계;해당 돼지 객체가 행동이상으로 판단되면, 음향정보수집부에서 돼지 객체의 호흡 및 기침소리를 포함하는 음향정보를 수집하는 단계;질별발생 판단부에서 상기 타겟 객체(돼지)의 뇌파변이도 패턴, 행동패턴의 불규칙한 자세변화, 호흡주기, 기침소리를 기초로 질병 유무를 1차 판단하는 단계;상기 타겟 객체(돼지)가 질병발생으로 판단되면, 제2 촬상장치에서 해당 돼지 객체의 신체 부위별 열화상 이미지를 수집하는 단계질병발생 판단부에서 상기 열화상 이미지를 기초로 해당 돼지 객체의 질병발생유무 및 질병의 종류를 예측하는 단계; 및해당 돼지 객체가 질병에 걸린 것으로 예측되면, 알림부에서 질병발생 알림메시지를 생성하여 관리자 단말로 발송하는 단계를 포함하는 딥러닝 기반 객체 추적 및 행동 분석을 이용한 스마트 축산관리방법., Ltext: 농업, prediction: 임업
969/1059 Row 969: application_number: 1020200099576, combined_string: invention_title: 사육 단계별 양돈 사료 급여 방법 abstract: 사육 단계별 양돈 사료 급여 방법에 관한 것으로, 보다 상세하게는 균일하고 안전한 돼지를 사육 및 공급할 수 있는 사육 단계별 양돈 사료 급여 방법에 관한 것이다. claims: 돼지의 분만일로부터 34일까지의 분만사 단계에서는 돼지 한마리당 분만사 단계의 누적 사료량이 1.5 내지 3kg 이고, 35일부터 62일까지의 이유자돈사 단계에서는 돼지 한마리당 이유자돈사 단계의 누적 사료량이 10 내지 15kg이고, 63일부터 76일까지의 자돈사 단계에서는 돼지 한마리당 자돈사 단계의 누적 사료량이 25 내지 35kg 이고,, 77일부터 111일까지의 육성돈 단계에서는 돼지 한마리당 육성돈 단계의 누적 사료량이 60 내지 80kg 이고,112일부터 출하까지의 비육돈 단계에서는 돼지 한마리당 비육돈 단계의 누적 사료량이 170 내지 180kg 이고, 상기 비육돈 단계의 사료는 녹차, 홍삼박, 대두박, 옥수수, 소맥피 및 당밀을 포함하는 배지에 고초균 (Bacillus subtilis), 황국균(Aspergillus oryzae), 락토바실러스 아시도필루스(Lactobacillus acidophilus), 스트렙토코커스 서머필러스(Streptococcus thermophilus) 및 효모균(Saccharomyces cerevisiae)을 접종하여 발효시킨 기능성 발효녹차 복합생균제를 포함하고, 상기 배지 100 중량%에 대하여, 녹차는 10 내지 30 중량%이고, 홍삼박은 5 내지 30 중량%이고, 대두박은 30 내지 50 중량%이고, 옥수수는 10 내지 30 중량%이고, 소맥피는 10 내지 30중량%이고, 당밀은 1 내지 10 중량%인 것인 사육 단계별 양돈 사료 급여 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

970/1059 Row 970: application_number: 1020200088208, combined_string: invention_title: 악취저감장치 abstract: 악취저감장치 함체에 설치된 흡기구를 통해 양돈축산시설 내부의 악취가 섞인 공기를 빨아들이고 EM균이 포함된 액체를 분사한 1개 내지 4개의 여과필터부를 통과하게 함으로써 공기중의 악취를 제거하고, 악취성분이 제거된 공기를 배기구를 통해 밖으로 배출시키며 다수의 여과필터에 의해 축산시설 내부에서 유입되는 가축털, 먼지 등을 막아 가축털, 먼지 등에 의해 발생하는 기계장치의 고장의 발생가능성을 낮추고 점검용 도어를 제공하여 사용자가 보다 용이하게 장치를 점검할 수 있게 하며, 여과필터를 프레임으로부터 고정걸쇠를 사용하여 쉽게 분리 가능하게 하여 여과필터의 교체를 사용자가 쉽게 할 수 있는 악취저감장치에 관한 것이다. claims: 악취저감장치에 있어서,악취저감장치(100)는 금속재질로 구성되어 밀폐되는 사각함체(10);악취를 함유한 공기를 상기 사각함체(10) 내부로 흡입하는 흡기구(20);상기 흡기구(20)를 통해 흡입된 악취를 함유한 공기를 여과하는 여과필터부(40);상기 여과필터부(40)를 결합하여 탈부착가능하게 하는 고정걸쇠(44);상기 여과필터부(40)는 먼지, 가축 털을 포함한 큰 입자를 걸러내는 1차여과필터(40a);상기 1차여과필터(40a)를 거치고 난 후 상기 1차여과필터(40a)보다 작은 타공으로 구성되어 유해물질을 걸러내는 2차여과필터(40b);상기 2차여과필터(40b)를 통해 여과된 공기를 상기 2차여과필터(40b)보다 세밀한 타공으로 구성되어 악취를 90% 내지 98% 제거하는 3차여과필터(40c);상기 여과필터부(40)를 지나 여과된 공기를 함체 외부로 배출하는 배기구(50);상기 배기구(50)에 설치되어 배기를 돕는 송풍기(51);상기 사각함체(10) 내부 하부에 위치되는 수조부(61);상기 수조부(61)에 저장된 액체를 외부로 배출할 수 있게 하는 밸브가 달린 토출구(85);상기 수조부(61)에 저장된 액체를 함체 내부에서 순환시키거나 배출하는 기능을 가진 수중모터펌프(60);상기 수조부(61)에 저장된 액체에 악취성분을 분해시키는 광합성균 및 고초균으로 구성된 EM균(62);상기 수중모터펌프(60)로부터 상기 수조부(61)에 저장된 액체를 전달받아 공급된 액체를 상기 여과필터부(40)에 분사하는 분사노즐(30);상기 사각함체(10)에 설치되어 사람이 드나들며 점검을 가능하게 하는 점검도어(55); 및상기 사각함체(10)에 설치되어 상기 수중모터펌프(60), 상기 송풍기(51) 및 상기 흡기구(20)의 동작을 외부에서 제어할 수 있는 컨트롤박스(70);를 포함하는 것을 특징으로 하는 악취저감장치., Ltext: 농업, prediction: 임업
971/1059 Row 971: application_number: 1020200085354, combined_string: invention_title: 비육돈 후기 기간의 양돈 사양기법(飼養技法) 및 사료 abstract: 본 발명은 양돈 사양기법(飼養技法) 및 저농도 페닐알라닌 사료에 관한 것이다.본 발명에 따른 양돈 사양기법은 비육돈후기 기간(18-19주. 85±3kg ~ 24-25주. 120±3kg) 동안 법제유황을 자화수에 두당 1일 음수량을 기준으로 2~3g 첨가 용융시켜 급수하여 음용시킴으로서, 돈육의 육질을 극대화시키고, 또 출하 전 3~7일 동안 페닐알라닌 저감사료로 급이 한 후 출하함으로서 PHIP의 발생을 억제시킴을 특징으로 한다.이와 같은 본 발명은 법제유황(두당 : 2~3g)을 자화수에 첨가 용융시켜 돼지가 음용하게 함으로서 법제유황의 체내 흡수율을 극대화시키고, 이에 따라 돈육의 냄새, 육색, 다즙성, 연도 육미 등 육질 개선 및 사육현장의 악취 유발 가스의 감소 효과를 얻을 수 있다.또한 출하 전 최대 7일, 최소3일 동안 페닐알라닌 저감 사료를 급이 함으로서 PhIP의 발생을 억제할 수 있는 유리 페닐알라닌 농도가 저감된 돼지고기를 생산함으로서, 가열 조리에 의해 돼지고기 중에 발생하는 PhIP량을 저감할 수 있고, 이에 따라 PhIP가 하나의 요인이 되는 암의 발생을 억제할 수 있는 효과도 있다. claims: 비육돈후기에 해당하는 체중 85kg±3kg이 되는 생후 18-19주부터 체중 120kg±3kg이 되는 생후 24-25주 동안, 음용수로 사용되는 자화수에 용융시킨 법제유황을 두당 1일 2~3g 음용시키는 단계와, 출하 전 3~7일 동안 페닐알라닌이 첨가되지 않은 비육돈후기사료 또는 비육돈후기사료 1Kg 당 페닐알라닌이 3g이하로 첨가 혼합된 페닐알라닌 저감사료를 급이하는 단계를 포함하는, 돈육의 육질을 극대화시킴과 동시에 페닐이미다졸피리딘(PHIP)의 발생을 억제하기 위한 비육돈후기 기간의 양돈 사양기법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

972/1059 Row 972: application_number: 1020200066441, combined_string: invention_title: 냉방배관을 이용한 냉방시스템이 형성된 돈사 abstract: 본 발명은 냉방배관을 이용한 냉방시스템이 형성된 돈사에 관한 것으로서, 보다 상세하게는 돈사의 돈방에서 분뇨가 저장되는 공간 사이에 돼지들이 휴식을 취할 수 있는 휴식공간의 바닥면에서 콘크리트층 상부에 단열재를 배치하고, 단열재 상부에 고정용 와이어메쉬를 배치하며, 상기 와이어메쉬 상부에 냉방배관을 지그재그로 배치하고, 상기 냉방배관 상부에 두번째 와이어메쉬를 배치하고, 보호용 모르타르를 타설하여 냉방층을 형성하며, 관정에서 지열을 이용해 냉각된 물을 상기 냉방배관으로 공급하고 회수하며 휴식공간의 바닥면을 설정온도로 유지하여 냉방하는 냉방배관을 이용한 냉방시스템이 형성된 돈사에 관한 것이다. claims: 관정에서 유입된 차가운 물과 열교환하며 탱크(130)에서 유입되는 물을 냉각하는 냉각기(110)와; 상기 냉각기(110)와 탱크(130) 사이에서 물을 순환시키는 순환펌프(120)와; 돈방(10)에서 환수되는 물을 상기 냉각기(110)로 보내고, 상기 냉각기(110)의 차가운 냉수를 공급받는 탱크(130)와;상기 탱크(130)에서 배출되는 냉수의 통로가 되고 다수의 돈방(10)으로 냉수를 공급하는 공급배관(140)과;상기 돈방(10)에서 순환된 물을 환수하여 상기 탱크(130)로 이송하는 환수배관(150);을 포함하는 냉방시스템(100)이 형성되되;상기 돈방(10)의 분뇨처리부(11) 사이에 구비되는 휴식공간부(12)는 콘크리트층(210) 상부에 배치되는 단열재(220)와, 상기 단열재(220) 상부에 배치되는 와이어메쉬로 이루어지는 제1열전도판(230)과, 상기 공급배관(140) 및 환수배관(150)과 연결되고 상기 제1열전도판(230) 상부에서 지그재그 형태로 이격되어 배치되는 냉방배관(240)과, 상기 냉방배관(240) 상부에서 접촉되게 배치되는 와이어메쉬로 이루어지는 제2열전도판(250)과, 상기 제2열전도판(250) 상부에서 타설하는 보호용 모르타르(260)의 결합으로 이루어지는 냉방층(200)이 형성되되;상기 단열재(220) 상부에는 스페이서(270)가 서로 이격되어 배치되고, 상기 스페이서(270) 상부에는 제1열전도판(230)이 배치되며, 상기 제1열전도판(230) 상부 상기 스페이서(270)의 내측 안착면(271)에는 냉방배관(240)이 안착되고, 상기 냉방배관(240) 상부에 제2열전도판(250)이 접촉되게 배치되며,상기 제2열전도판(250)의 상부에는 서로 이격되어 다수개로 존재하고, 상기 제2열전도판(250) 하부에 위치하는 상기 냉방배관(240)의 상부에서 대응하게 마련되어 제2열전도판(250)와 접촉되어 냉기를 전도받으며, 상기 냉방배관(240) 및 제2열전도판(250)에서 방출하는 냉기를 보관하는 냉주머니(281)가 내부에 형성된 축열판(280)을 포함하는 냉방배관을 이용한 냉방시스템이 형성된 돈사., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

973/1059 Row 973: application_number: 1020200044957, combined_string: invention_title: 솔잎추출물을 함유하는 돼지사료 제조방법 abstract: 본 발명은 솔잎추출물을 함유하는 돼지사료 제조방법에 관한 것으로서, (A) 솔잎을 세척한 후, 열풍건조기 측 60~80℃에서 2~3시간 동안 건조 처리하거나 또는 드라이오븐 측 70~80℃에서 1~2시간 동안 건조 처리하는 단계; (B) 상기 건조된 솔잎을 분쇄기로 마쇄 처리함으로써 솔잎분말로 만드는 단계; (C) 해조류를 세척 탈염한 후, 열풍건조기 측 60~70℃에서 1~2시간 동안 건조 처리하거나 또는 드라이오븐 측 60~65℃에서 30~60분 동안 건조 처리하는 단계; (D) 상기 건조된 해조류를 분쇄기로 마쇄 처리함으로써 해조류분말로 만드는 단계; (E) 상기 솔잎분말과 물을 열수추출기에 투입한 상태에 110~130℃에서 30~40분 동안 열수추출한 후, 이를 감압여과장치를 통해 감압 여과함으로써 제1솔잎추출물을 얻어내는 단계; (F) 상기 솔잎분말을 아임계 추출장치 측 추출용기 내에 투입하여 아임계 추출방식으로 제2솔잎추출물을 얻어내되, 상기 아임계 추출장치는 이산화탄소유체를 60~80kgf/cm3의 압력으로 공급하는 유체공급부가 상기 추출용기의 일측에 연결되고 타측에는 제1회수기가 연결되며, 상기 제1회수기에 일측이 연결되고 타측이 순환라인에 연결되는 제2회수기를 갖는 상태에서 제1회수기 측 70~80℃ 온도와 제2회수기 측 110~120℃ 온도로 3~4시간 동안 추출한 후, 이를 감압여과장치를 통해 감압 여과함으로써 제2솔잎추출물을 얻어내는 단계; (G) 상기 해조류분말과 물을 열수추출기에 투입한 상태에 100~110℃에서 2~3시간 동안 열수추출한 후, 주정 침지방식과 한외여과방식을 연속 실시하는 정제과정을 거쳐 해조류추출물을 얻어내는 단계; (H) 상기 제1솔잎추출물과 제2솔잎추출물 및 해조류추출물을 돼지사료의 베이스원료에 혼합하는 단계; (I) 상기 혼합재료를 펠릿으로 성형하는 단계; (J) 상기 성형 펠릿을 동결 건조시키는 단계;를 포함하는 것을 특징으로 한다.본 발명에 따르면, 항균과 항바이러스 및 항산화 특성을 갖는 솔잎추출물을 함유하는 돼지사료를 제조할 수 있으며, 기존에 비해 항생제 등을 사용하지 않아 사료에 대한 안전성을 확보할 수 있으면서 친환경 재료를 사용하는 방식에 의한 친환경 돼지사료를 제조할 수 있다. claims: (A) 솔잎을 세척한 후, 열풍건조기 측 60~80℃에서 2~3시간 동안 건조 처리하거나 또는 드라이오븐 측 70~80℃에서 1~2시간 동안 건조 처리하는 단계;(B) 상기 건조된 솔잎을 분쇄기로 마쇄 처리함으로써 솔잎분말로 만드는 단계;(C) 해조류를 세척 탈염한 후, 열풍건조기 측 60~70℃에서 1~2시간 동안 건조 처리하거나 또는 드라이오븐 측 60~65℃에서 30~60분 동안 건조 처리하는 단계;(D) 상기 건조된 해조류를 분쇄기로 마쇄 처리함으로써 해조류분말로 만드는 단계;(E) 상기 솔잎분말과 물을 열수추출기에 투입한 상태에 110~130℃에서 30~40분 동안 열수추출한 후, 이를 감압여과장치를 통해 감압 여과함으로써 제1솔잎추출물을 얻어내는 단계;(F) 상기 솔잎분말을 아임계 추출장치 측 추출용기 내에 투입하여 아임계 추출방식으로 제2솔잎추출물을 얻어내되, 상기 아임계 추출장치는 이산화탄소유체를 60~80kgf/cm3의 압력으로 공급하는 유체공급부가 상기 추출용기의 일측에 연결되고 타측에는 제1회수기가 연결되며, 상기 제1회수기에 일측이 연결되고 타측이 순환라인에 연결되는 제2회수기를 갖는 상태에서 제1회수기 측 70~80℃ 온도와 제2회수기 측 110~120℃ 온도로 3~4시간 동안 추출한 후, 이를 감압여과장치를 통해 감압 여과함으로써 제2솔잎추출물을 얻어내는 단계;(G) 상기 해조류분말과 물을 열수추출기에 투입한 상태에 100~110℃에서 2~3시간 동안 열수추출한 후, 주정 침지방식과 한외여과방식을 연속 실시하는 정제과정을 거쳐 해조류추출물을 얻어내는 단계;(H) 상기 제1솔잎추출물과 제2솔잎추출물 및 해조류추출물을 돼지사료의 베이스원료에 혼합하는 단계;(I) 상기 (H) 단계의 혼합재료를 펠릿으로 성형하는 단계;(J) 상기 성형 펠릿을 동결 건조시키는 단계; 를 포함하며,상기 (G)단계에서는,열수추출한 해조류추출물에 대해 진공 농축기로 보내 600~650mmHg 및 50~60℃ 조건에서 감압 농축한 후, 70~80%의 농도 및 3~5℃의 온도를 갖는 알콜에 침지시켜 12~15시간 동안 주정 침지하는 단계;주정 침지를 마친 해조류추출물을 원심분리하되, 침전물을 증류수에 녹인 후 투석(dialysis) 처리하는 단계;원심분리 후 투석 처리를 마친 해조류추출물을 한외여과장치로 보내 일정 이상의 분자량을 갖는 고분자물질로 분리 정제함으로써 면역활성물질의 활성을 증대시킨 해조류추출물을 얻어내는 단계; 를 포함하는 것을 특징으로 하는 솔잎추출물을 함유하는 돼지사료 제조방법., Ltext: 농업, prediction: 임업
974/1059 Row 974: application_number: 1020200029823, combined_string: invention_title: 스마트팜 양돈 시스템 및 방법 abstract: 스마트팜 양돈 시스템 및 방법이 개시된다. 스마트팜 양돈 시스템은 유저 단말로부터 사용자 조작에 따른 돼지의 축사 변동 사항을 제공받는 유저 대응부; 및 상기 축사 변동 사항에 관한 정보가 상응하는 돼지의 사육 데이터에 추가되도록 상기 사육 데이터를 갱신하는 데이터 갱신부를 포함한다. claims: 유저 단말로부터 사용자 조작에 따른 돼지의 축사 변동 사항을 제공받는 유저 대응부; 및상기 축사 변동 사항에 관한 정보가 상응하는 돼지의 사육 데이터에 추가되도록 상기 사육 데이터를 갱신하는 데이터 갱신부를 포함하되,상기 유저 단말에는 실제 양돈 현장의 실제 구획 영역인 돈사와 돈방에 대응되는 가상의 구획 영역과, 실제 양돈 현장의 돼지 배치 상황에 대응되도록 각 가상의 구획 영역에 개체 이미지가 표시된 GUI(Graphical User Interface) 환경의 관리 화면이 표시되고,가상의 구획 영역에 표시되는 개체 이미지는 상응하는 돼지의 식별정보에 대응되도록 관리되며, 실제 양돈 현장에서의 축사 이동 대상인 돼지에 상응하는 개체 이미지를 어느 하나의 가상의 구획 영역에서 다른 가상의 구획 영역으로 드래그 앤 드롭(Drag and Drop) 방식으로 이동시키는 것에 의해 상기 축사 변동 사항이 입력되고,상기 데이터 갱신부는 상기 사육 데이터가 돼지의 전체 생육 기간 동안의 정보 연속성이 유지되도록 하기 위해, 상기 축사 변동 사항에 상응하도록 이동된 실제 구획 영역에 대응되도록 수집된 부가 정보가 상기 사육 데이터에 더 추가되도록 상기 사육 데이터를 갱신하는 것을 특징으로 하는 스마트팜 양돈 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

975/1059 Row 975: application_number: 1020200028703, combined_string: invention_title: 우수가림막과 다층구조의 태양광 엘이디조명등이 구비된 끈끈이 해충 포획 및 야생동물 퇴치 트랩 abstract: 본 발명은 파리, 모기, 나방 등과 같은 각종 해충포획과 까치, 참새, 까마귀, 찌르레기 등의 위해조류와 고라니, 멧돼지, 너구리, 노루 등의 야생동물을 퇴치하는 용도로 사용하는 우수가림막과 다층구조의 태양광 led조명등이 구비된 끈끈이 해충 포획 및 야생동물 퇴치 트랩에 관한 것으로서, 태양광이 투영되고 해충이 유입될 수 있는 복수의 유입구가 형성되는 통 형상의 망과 상기 망의 외부이며 상부에 형성되는 하부의 일정부분이 개방된 고리에 요입되어 형성되는 태양광이 투영되고 우수를 차단할수 있는 원형판 형상의 우수가림막과 상기 망의 내부에 형성되는 통 형상의 투명한 용기와 상기 용기의 내부에 구비된 태양광에너지를 이용한 led백색광과 led자외선(UVA)광이 수직과 수평으로 조합된 다층구조의 태양광 led조명등과, 상부조명등의 하단이며 중간조명등의 상부 사이에 조명을 투과 또는 차단할 수 있는 탈부착식 불투명 원형판 형상의 조명차단판과, 투명한 용기의 외부에 일정 간격 이격되어 덮어씌워진 태양광이 투과될 수 있는 투명 또는 반투명과 해충이 선호하는 색상이 반복적으로 채색된 줄무늬 형상의 끈끈이 해충유인 솔라백시트의 수직측면의 중앙부를 관통하여 구비된 복수의 페르몬향 또는 야생동물 기피제조성물향 분출구에서 발산되는 페르몬 및 led 백색광과 자외선(UVA)광에 의한 광선 파장으로 포충 점착액이 도포된 솔라백 시트로 해충유인 포획하거나, led 백색광과 자외선(UVA)광에 의한 광선파장과 트랩의 내부에 구비하는 야생동물 기피제 조성물향을 복수의 분출구에서 주변으로 확산하여 야생동물을 퇴치하는 것으로서, 태양광에너지를 활용하여 해충을 유인하는 친환경적이며, 수직 공간활용을 위한 수직형태의 통형상의 끈끈이 해충유인 솔라백시트가 받침대 상부에 형성되어 공간활용을 극대화하고, 우수를 차단할수 있는 원형판 형상의 우수가림막 으로 인한 상기 끈끈이 해충유인 솔라백시트의 점착성능의 감소를 방지하고, 태양광이 투과되는 투명한 용기와 끈끈이 해충유인 솔라백시트 전체의 외부표면으로 조명을 확대하고, 해충 방제 효과 향상을 위한 파장이 다른 led 백색광과 자외선(UVA)광 led램프의 조명으로 해충을 유인할 수 있는 다층구조의 조명등 구조이며, 투명한 용기와 근끈이 시트의 수직측면 중앙부를 관통하여 구비된 복수의 페르몬향 또는 야생동물 기피제조성물향 분출구 주변인 끈끈이 시트 중앙부 인근으로 농작물 재배시에는 태양광 led 조명등인 led 백색광과 자외선(UVA)광과 투명 또는 반투명과 해충이 선호하는 색상이 반복적으로 채색된 줄무늬 형상의 점착포충물질이 도포된 끈끈이 해충유인 솔라백시트 및 페르몬향에 의해 해충을 빠르게 유인하여 해충을 포획하고, 상기 끈끈이 해충유인 솔라백시트점에 의한 지속적인 해충의 포획으로 led 백색광과 자외선(UVA)광 및 페르몬에 의하여 유인된 해충이 포획트랩 주변을 배회하지 않도록 하며, 농작물 수확시기에는 태양광 led 조명등인 led백색광과 led자외선(UVA)광이 수직과 수평으로 조합된 다층구조의 태양광 led조명등과, 투명 또는 반투명과 해충이 선호하는 색상이 반복적으로 채색된 줄무늬 형상의 점착포충물질이 도포된 끈끈이 해충유인 솔라백시트의 간헐적으로 접촉했던 조류 등의 야생동물이 기피하게 되는 학습효과와 상기 솔라백시트를 투과하는 led백색광과 led자외선(UVA)광과 야생동물 기피제 조성물향에 의해 효율적으로 야생동물을 퇴치하는 트랩이며, 조명등이 투명한 끈끈이 시트 내부에 있으므로 작은 해충이나 곤충이 조명등에 들러 붙지 않으며, 끈끈이 시트의 해충포집으로 인한 태양광 투과량이 적더라도 조명등이 소등되어 조명시간이 줄어들지 않도록 다층구조의 조명으로 충분한 조명시간을 확보하며, 태양광에너지를 이용한 led램프의 조명으로 전력소비가 적으며 전기 공급이 원활하지 않은 산악 지역 등에서도 그 활용도가 향상되며, 사멸된 해충포집으로 끈끈이 시트의 투명도가 저하되거나, 시간이 경과되어 점착액이 경화되어 소모된 끈끈이 시트만 편리하게 교체하여 장기간 사용할 수 있으며, 받침대에 의한 축사나 농경지의 바닥에 설치하거나, 고리에 의한 비닐하우스의 천정 또는 수목의 상부에 매달거나, 하부의 지지대 결합부에 의한 농작물 직상부에 설치할 수 있는 구조로서 농경지나 축사 뿐 만아니라주택의 보안등과 해충포집을 겸용으로 사용할 수도 있으므로 사용장소와 용도에 따라 다양하게 사용될 수 있는 다용도를 가지는 해충포획 및 야생동물 퇴치트랩에 관한 것이다. claims: 태양광이 투영되고 해충이 유입될 수 있는 복수의 유입구가 형성되는 망 형태로서 통 형상의 제1케이싱과; 상부에 내부와 연통되는 개구부가 형성되며, 마개에 의하여 개폐되는 통 형상의 투명한 제2케이싱과; 상기 제2케이싱의 내부에 수용되며 하부에 내부와 연통되는 개구부가 형성되며, 마개에 의하여 개폐되는 통을 뒤집어 놓은 형상의 투명한 제3케이싱과; 상기 제2케이싱을 감싸며 외면에는 점착액이 도포된 투명 또는 반투명과 해충이 선호하는 색상이 반복적으로 채색된 줄무늬 형상의 끈끈이 해충유인 솔라백시트와; 상기 끈끈이 해충유인 솔라백 시트의 좌측과 우측 상부의 처짐을 방지하기 위하여 상기 제2케이싱의 개구부의 나사부에 요입되어 하단면에 설치되어 마개로 고정되는 원형판 형상으로 원형 링형태의 솔라백 시트 지지대와; 상기 제2케이싱의 하단 내측면 상부에 설치되는 페르몬 또는 기피제조성물 약제통과; 상기 제2케이싱과 끈끈이 해충유인 솔라백 시트의 수직측면의 중앙부위를 관통하여 제2케이싱 내부 기류가 끈끈이 시트의 중앙부위에서 외부로 분출될 수 있는 복수의 페르몬향 또는 야생동물 기피제조성물향 분출구와; 상기 제1케이싱을 고정하고 지지하며, 상기 제1케이싱을 고정하고 지지하는 제1받침대와; 상기 제1받침대 내부에 고정되어 수용되며, 상기제2케이싱과 제3케이싱을 고정하고 지지하는 제2받침대와; 상기 제2케이싱의 마개에 관통홀을 형성하여 설치되는 제1조명기기와; 상기 제1조명기기의 하부에 일정간격 이격되어 상기 제2케이싱의 내부이며, 상기 제3케이싱의 외부인 상단에 결합되는 제2조명기기와; 상기 제2조명기기와 상호 대향되도록 태양광을 등지고, 상기 제3케이싱의 내부에 설치되는 제3조명기기와; 상기 제2케이싱의 내부이고, 상기 제2조명기기 하부이며, 제3케이싱의 외부상단 좌측에 수평으로 설치되는 제4조명기기와; 상기 제4조명기기와 대향되게 수평으로 우측에 설치되는 제5조명기기와; 상기 제3조명기기의 하부에 일정간격 이격되어 제3케이싱의 마개 내부 면에 설치되는 태양광 반사경과; 상기 제1케이싱을 지면위의 고정물체에 메달 수 있도록 하부의 일정부분이 개방되어 고정설치되는 환봉형상의 고리 체결부와; 상기 고리 체결부의 하부에 개방된 환봉형상의 고리를 관통하여 요입되어 상기 제1케이싱의 외부이며 상부에 설치되는 설치되는 태양광이 투영되고 우수를 차단할수 있는 원형판 형상의 우수가림막과; 상기 제1케이싱과 제2케이싱과 제3케이싱을 상기 받침대에 결합부재로 고정하기 위한 결합부;를 포함하며,상기 제1조명기기와 제2조명기기 및 제3조명기기는 독립형 태양광 전지모듈 기판 및 램프를 통형상의 투명한 용기의 내부에 수직형태이고, 상기 제4조명기기와 제5조명기기는 수평형태인 다층구조로 형성하여 조명을 투명한 용기 전체의 외부표면으로 발산하는 구조이며, 상기 제1조명기기와 제2조명기기 와 제3조명기기 및 제4조명기기와 제5조명기기는 태양광을 집적하여 전력을 생산하는 태양광 전지모듈 기판과 상기 태양광 전지모듈 기판을 견고하게 고정할 수 있는 태양광 전지모듈 지지판과 상기 태양광 전지모듈 기판에서 생산된 전력을 충전할 수 있는 커페시터와, 상기 커페시터로부터 전력을 공급받아 빛을 조사하는 led램프와, 상기 태양광 전지모듈 기판의 수광면에 구비되어 주간에는 생산된 전력을 상기 커페시터에 충전하고 일몰 후에는 상기 led램프의 점등토록 하는 조도센서와, 상기 커페시터의 충전 및 led램프 점등을 제어하는 제어부와, 상기 커페시터, led램프, 제어부를 고정하여 상기 태양광 전지모듈 지지판에 결합부재로 체결되는 조명기판으로 구성되고, 상기 제1조명기기와 제2조명기기 와 제3조명기기에는 투과되는 빛을 굴절시켜 확산시킬 수 있는 빛이 투과되는 재질로서 상기 led램프를 보호하는 조명커버가 구성되며, 상기 제1조명기기의 상기 조명커버 외부의 하단에는 불투명 재질의 원형판 형상의 탈부착식이 가능한 구조의 조명차단판이 밀착고정되어 구성되고, 상기 페르몬향 또는 기피제조성물향 분출구는 중심부에 관통홀이 형성되어 통형상의 투명한 용기와 끈끈이 해충유인 솔라백 시트의 수직측면의 중앙을 관통하여 설치되고, 상기 제2케이싱내의 하부에 형성된 관통홀에 외경보다 적은 구멍이 형성된 수축성 고무부싱 또는 실리콘 부싱 등을 설치하여 부싱내의 구멍에 삽입하여 설치되는 페르몬향 또는 야생동물 기피제조성물향이 내부에 요입되어 설치될 수 있는 약제통이 구성되는 것을 특징으로 하는 우수가림막과 태양광led조명등이 구비되는 끈끈이 해충포획트랩.제1항에 있어서. 상기 제1조명기기의 led램프와 제2조명기기의 led램프와 제3조명기기의 led램프 및 제4조명기기의 led램프와 제5조명기기의 led램프는 해충별 유인효과 향상을 위하여 백색광을 포함하는 1개 이상의 색상별 led 소자 또는 RGB 3원색 led 소자 또는 자외선(UVA)led소자로 구성되는 것을 특징으로 하는 우수가림막과 다층구조의 태양광 led조명등이 구비된 끈끈이 해충 포획 및 야생동물 퇴치 트랩. 제2항에 있어서. 상기 우수가림판은 투명하고 유연성이 있는 재질로서, 태양광 투과가 용이하고, 태양광의 자외선에 의한 변색이 되지 않으며, 전단강도가 우수하며, 우수에 의한 먼지 등의 부착착이 최소화 될 수 있는 제전비닐(ESD) 등의 합성수지계열이 바람직하나, 반드시 그러한 것은 아니며, 상기 체결링을 체결하기 위하여 상기 우수가림판의 원주의 외축 끝단으로부터 체결링의 내경만큼 이격되어 외측 관통홀을 일정한 간격의 방사상으로 4개소이상 형성하며, 중심부에는 상기 중앙지지대가 삽입되어 설치될 수 있도록 중심 관통홀가 형성되며,상기 외측 관통홀은 바람 등의 외력에 의한 반복적인 변형과 원상회복에도 상기 우수가림판의 관통홀이 전단력에 의하여 파손되지 않도록 상기 관통홀의 직경은 2~5mm이며,상기 중앙지지대는 상부의 뚜껑과 하부의 몸체로 형성되는 상하 분리형태로서 상부 뚜껑의 외측돌기와 하부 몸체의 내측돌기를 이용한 압입 고정방식이므로 상기 중앙지지대의 외경보다 적고, 내경보다는 크게 형성되어 상기 우수가림판의 일정부분이 상기 중앙지지대의 상부 뚜껑과 하부 몸체 사이에 겹쳐서 고정되기 위한 것으로서, 상기 중앙지지대는 고리체결부의 지지대의 상부면에 지지되어 상기 우수 가림막의 중심을 유지하고 지지하며 바람 등의 외력에 의한 변형을 최소화 하기 위하여 회전이 가능한 형태로서, 중심부에 관통홀)이 형성되어 상기 고리체결부의 하부 개방공간을 이용하여 고리에 요입 설치되며, 상부의 뚜껑과 하부의 몸체로 형성되는 상하 분리형태로서 상부 뚜껑의 상기 관통홀 주변의 돌출부에 형성된 외측돌기와 하부 몸체의 관통홀 주변의 돌출부에 형성되는 내측돌기를 이용한 압입 고정방식이며, 상부 뚜껑과 하부 몸체의 돌출부의 외경은 상기 중앙지지대의 상부 뚜껑과 하부 몸체의 외경보다 10~20mm 적게 형성되는 것이며, 상기 중앙지지대(105b)의 재질은 부식이 되지 않으며, 성형가공이 가능한 재질로서 폴리에틸렌, 폴리카보네이트 등의 합성수지, 황동, 청동 등의 비철합금이 바람직하며,상기 탄성링은 상기 우수가림판이 바람 등의 외력에 의한 변형후에도 원형상태를 유지하기 위하여 상기 우수가림판의 원주 외측에 후술되는 체결링으로 연결하는 것으로서, 반복적인 변형에도 원형상태를 유지하기 위하여 탄성이 있으며, 습기에 노출되어도 부식이 되지 않으며, 햇빛에 경화되지 않는 재질인 스테인레스 선재, 아연도금 탄소강 선재를 단면이 환봉형태 또는 직사각형태로 제작하여 원형 형상이 유지될 수 있도록 압착클립을 이용하여 연결하는 것이 바람직하나, 단면이 직사각형태가 반복적인 탄성복원력측면에서는 원형단면보다는 유리하다 할 것이다. 전기 압접 방식 등의 용접방식을 활용할 수도 있으나, 용접부위의 경화로 인한 탄성력 저하로 반복적인 변형으로 인한 파손을 방지할 수 있는 열처리를 하는 것도 바람직하며. 상기 체결링은 상기 우수가림판에 외측에 방사상으로 형성된 관통홀을 관통하여 상기 탄성링을 상기 체결링 내측에 인입하여 연결하기 위한 것으로 개폐가 가능하여야 하며, 비틀림 외력에 의한 개폐가 가능하되, 바람등의 외력에 의한 탄성링의 측면외력에는 개방이 되지 않독 개폐부에 돌출부가 형성되고 습기에 부식이 되지 않는 재질로서 아연도금이나 스테인레스 재질의 시중 판매제품인 카드링 등이 바람직한 것을 특징으로 하는 우수가림막과 태양광led조명등이 구비된 해충포획 및 야생동물퇴치 트랩. 제1항에 있어서상기 조명커버의 하부 중앙에는 관통홀이 형성되며, 상기 관통홀의 하부에 설치되는 조명차단판은 설치와 분리가 용이한 탈착식의 조명반사부결합부재의 볼트부를 상기 관통홀를 관통하여 너트 등으로 밀착되도록 고정설치하여 상기 제1조명기기의 조명을 차단하여 상기 제2조명기기의 상기 태양광전지모듈 기판에 내장되어 있는 조도센서가 점등(방전)동작할 수 있도록 하는 것이며, 상기 조명차단판을 분리하여 제거하였을 경우에는 상기 제1조명기기의 led램프 빛이 관통되어 상기 태양광전지모듈 기판에 내장되어 있는 조도센서가 소등(충전)동작할 수 있도록 관통공이 형성되는 것이며, 상기 조명커버는 상기 led램프를 보호하는 역할을 하는 것으로 배광이 확산될 수 있도록 성형가공이 가능한 투명한 유리, 아크릴, 합성수지 등의 재질이 바람직하며. 상기 조명차단판은 탈부착이 용이하고, 상기 제2케이싱의 개구부보다 적으며 상기 태양광전지판넬 지지판(162)보다는 크게 형성된 원판형 구조로서, 재질은 불투명한 폴리카보네이트(pc), 패트(PET), 등의 합성수지 계열이 바람직하며, 다층구조의 태양광 led 조명등의 백색광과 자외선광(UVA)의 효율적인 조합을 위하여 상기 제1조명기기의 조명커버(167)하단에 설치하여 상기 제2조명기기의 점등과 소등을 자유롭게 선택할 수 있으므로 태양광 조도가 낮은 시설하우스나 비닐하우스내의 예비전력사용과 노지의 경작지에서의 상시전력으로 선택적으로 활용함으로서 해충포획효율을 향상시킬 수 있는 것을 특징으로 하는 우수가림막과 태양광led조명등이 구비된 해충포획 및 야생동물퇴치 트랩., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

976/1059 Row 976: application_number: 1020200022813, combined_string: invention_title: 전염병으로 인해 살처분되어 매몰된 동물사체의 매몰지 소멸화 고속처리공정 abstract: 본 발명은 전염병으로 인해 살처분되어 매몰된 동물사체의 매몰지 소멸화 고속처리공정에 관한 것으로, 그 구성은 전염병으로 인해서 살처분된 동물사체를 파쇄하는 파쇄단계와, 상기 파쇄단계를 거친 동물사체를 습식으로 열처리하여 멸균시키는 습식열처리멸균단계와, 상기 습식열처리멸균단계를 거친 동물사체를 고속 발효탱크에서 발효시키는 고속발효단계와, 상기 고속발효단계를 거친 동물사체와 부속물을 포장하여 퇴비로 이송시키는 퇴비이송단계를 포함하되, 상기 고속 발효탱크는, 상면이 개방되며, 하단은 지표면과 접촉되며, 지표면에 대해서 수직방향으로 세워지는 측벽하우징과, 상기 측벽하우징의 하단에 형성되며, 왕겨가 도포된 왕겨층과, 상기 왕겨층의 상단에 마련되며, 폭기펌프에 의해 제공되는 공기가 상방을 향해서 분사되는 폭기조와, 상기 왕겨층의 상단에 마련되며, 동물사체를 분해시키는 미생물과 수피를 포함하는 미생물수피층과, 상기 미생물수피층의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제1동물사체층과, 상기 제1동물사체층의 상단에 마련되며, 수피와 왕겨와 미생물이 혼합되어 위치되는 제1혼합층과, 상기 제1혼합층의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제2동물사체층과, 상기 제2동물사체층의 상단에 마련되며, 수피와 왕겨와 미생물이 혼합되어 위치되는 제2혼합층과, 상기 제2혼합층의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제3동물사체층과, 상기 제3동물사체층의 상단에 마련되며, 수피로 이루어지는 상단수피층과, 상기 측벽하우징의 중심부에 위치되며, 상기 측벽하우징의 상하방향으로 놓여지며, 내부에 공간을 가지는 파이프 형상의 본체파이프와, 상기 본체파이프와 연통되며, 상기 측벽하우징에 대해서 가로방향으로 놓여지며, 상기 상단수피층과 제3동물사체층 사이에 위치되며, 상기 제3동물사체층이 위치된 방향으로 유체통과공이 형성된 분기파이프와, 상기 측벽하우징의 중앙 밑면에 위치되며, 상기 분기파이프와 연결되어 상기 분기파이프로 유체를 이송시키는 이송펌프와, 상기 측벽하우징의 내벽과 지표면의 상면에 위치되며, 유체를 외부로 통과시키지 않는 방수포를 포함하는 것을 특징으로 하는 것으로서, 조류독감(Ai)이나 구제역이나 아프리카 돼지열병 등의 전염병으로 살처분되어 매몰된 동물사체의 매몰지를 빠른 시간 내에 소멸화시킬 수 있으며, 매몰지를 소멸화함으로써 토지의 활용도를 높이고 혐오시설을 제거할 수 있으며, 주위의 환경을 해치지 않으면서 매몰지를 빠른 시간 내에 소멸시킬 수 있으며, 미생물의 활동이 활발하게 될 수 있도록 수분을 계속해서 공급함으로써 미생물에 의한 발효를 더욱 촉진시킬 수 있으며, 침출수 등이 발생하지 않으므로 토양오염 등의 주위 환경을 해치지 않아서 친환경적이며, 발효 후에는 퇴비나 소각을 할 수 있어 전염병으로 인한 동물사체의 매몰지를 빠르게 소멸처리할 수 있는 효과가 있다. claims: 전염병으로 인해서 살처분된 동물사체를 파쇄하는 파쇄단계;상기 파쇄단계를 거친 동물사체를 습식으로 열처리하여 멸균시키는 습식열처리멸균단계;상기 습식열처리멸균단계를 거친 동물사체를 고속 발효탱크에서 발효시키는 고속발효단계;상기 고속발효단계를 거친 동물사체와 부속물을 포장하여 퇴비로 이송시키는 퇴비이송단계를 포함하되, 상기 고속 발효탱크는, 상면이 개방되며, 하단은 지표면과 접촉되며, 지표면에 대해서 수직방향으로 세워지는 측벽하우징(10); 상기 측벽하우징(10)의 하단에 형성되며, 왕겨가 도포된 왕겨층(20);상기 왕겨층(20)의 상단에 마련되며, 폭기펌프(35)에 의해 제공되는 공기가 상방을 향해서 분사되는 폭기조(30);상기 왕겨층(20)의 상단에 마련되며, 동물사체를 분해시키는 미생물과 수피를 포함하는 미생물수피층(40);상기 미생물수피층(40)의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제1동물사체층(50);상기 제1동물사체층(50)의 상단에 마련되며, 수피와 왕겨와 미생물이 혼합되어 위치되는 제1혼합층(60);상기 제1혼합층(60)의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제2동물사체층(70);상기 제2동물사체층(70)의 상단에 마련되며, 수피와 왕겨와 미생물이 혼합되어 위치되는 제2혼합층(80);상기 제2혼합층(80)의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제3동물사체층(90);상기 제3동물사체층(90)의 상단에 마련되며, 수피로 이루어지는 상단수피층(100);상기 측벽하우징(10)의 중심부에 위치되며, 상기 측벽하우징(10)의 상하방향으로 놓여지며, 내부에 공간을 가지는 파이프 형상의 본체파이프(110);상기 본체파이프(110)와 연통되며, 상기 측벽하우징(10)에 대해서 가로방향으로 놓여지며, 상기 상단수피층(100)과 제3동물사체층(90) 사이에 위치되며, 상기 제3동물사체층(90)이 위치된 방향으로 유체통과공(125)이 형성된 분기파이프(120);상기 측벽하우징(10)의 중앙 밑면(160)에 위치되며, 상기 분기파이프(120)와 연결되어 상기 분기파이프(120)로 유체를 이송시키는 이송펌프(130);상기 측벽하우징(10)의 내벽과 지표면의 상면에 위치되며, 유체를 외부로 통과시키지 않는 방수포(150);를 포함하는 것을 특징으로 하는 전염병으로 인해 살처분되어 매몰된 동물사체의 매몰지 소멸화 고속처리공정., Ltext: 농업, prediction: 임업
977/1059 Row 977: application_number: 1020200003608, combined_string: invention_title: 돈사 내 온도 및 습도 센싱정보를 활용한 돼지 성장예측 시스템 abstract: 돈사 내 온도 및 습도 센싱정보를 활용한 돼지 성장예측 시스템이 개시된다. 본 발명의 돈사 내 온도 및 습도 센싱정보를 활용한 돼지 성장예측 시스템은, 돈사 내 온도 정보를 측정하는 온도 측정부; 돈사 내 습도 정보를 측정하는 습도 측정부; 상기 온도 측정부 및 습도 측정부의 측정값을 기반으로 돼지의 성장단계별 일당 증체량을 산출하는 일당 증체량 산출부; 상기 일당 증체량 산출부의 산출값과 돼지의 성장단계별 설정 체중을 기반으로 사육시기별 사육 예상일수를 산출하는 사육 예상일수 산출부; 및 상기 사육일수 산출부의 산출값과 기설정된 돼지의 포유기간을 기반으로 목표 출하일을 산출하는 출하일 예측부를 포함하는 것을 특징으로 한다. 본 발명에 의하면, ICT정보(돈사 내 온도와 습도 센싱정보)를 활용하여 돼지의 성장 능력을 예측함으로써 목표 출하예정일, 목표 출하예정일까지의 총 사료섭취 예상량, 평균 사료요구율 등을 예측할 수 있고, 양돈 농가에서는 정밀한 사양관리로 효율적이고 경제적으로 돼지를 관리할 수 있다. claims: 돈사 내 온도 정보를 측정하는 온도 측정부(100);돈사 내 습도 정보를 측정하는 습도 측정부(200);상기 온도 측정부(100) 및 습도 측정부(200)의 측정값을 기반으로 돼지의 성장단계별 일당 증체량을 산출하는 일당 증체량 산출부(300);상기 일당 증체량 산출부(300)의 산출값과 돼지의 성장단계별 설정 체중을 기반으로 사육시기별 사육 예상일수를 산출하는 사육 예상일수 산출부(400); 및상기 사육 예상일수 산출부(400)의 산출값과 기설정된 돼지의 포유기간을 기반으로 목표 출하일을 산출하는 출하일 예측부(500)를 포함하는 돈사 내 온도 및 습도 센싱정보를 활용한 돼지 성장예측 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

978/1059 Row 978: application_number: 1020200002952, combined_string: invention_title: 동물용 약물 주입 장치와 이를 이용한 약물 주입 시스템, 방법 및 이를 수행하기 위한 컴퓨팅 장치 abstract: 동물용 약물 주입 장치와 이를 이용한 약물 주입 시스템, 방법 및 이를 수행하기 위한 컴퓨팅 장치가 개시된다. 본 발명의 일 실시예에 따른 동물용 약물 주입 장치와 이를 이용한 약물 주입 시스템, 방법 및 이를 수행하기 위한 컴퓨팅 장치는 동물에 부착되어 약물을 주입하는 약물 주입부, 및 상기 동물의 정보를 측정하는 센서부를 포함하는 약물 주입 장치; 및 상기 약물 주입 장치로부터 상기 동물 센싱 정보를 수신하고, 상기 동물 센싱 정보를 바탕으로 약물 주입을 제어하는 약물 주입 신호를 생성하여 상기 약물 주입 장치로 상기 약물 주입 신호를 전송하는 관리 서버를 포함한다. 본 발명의 실시예들에 따르면, 소나 돼지 등의 동물에 약물 주입 장치를 부착하여 원격으로 약물 투입을 제어함으로써, 다수의 가축에게 일괄적으로 약물을 투여할 수 있다. 또한, 본 발명의 실시예들은 원격으로 약물 투입을 제어함으로써, 근접주사에 따른 작업자의 안전사고를 미연에 방지하며, 정확하고 신속하게 주사할 수 있다. 또한, 본 발명의 실시예들은 동물의 상태에 따라 약물을 투여함으로써, 전염병 확산을 방지할 수 있다. claims: 동물에 부착되어 약물을 주입하는 약물 주입부, 및 상기 동물의 정보를 측정하는 센서부를 포함하는 약물 주입 장치; 및상기 약물 주입 장치로부터 상기 동물 센싱 정보를 수신하고, 상기 동물 센싱 정보를 바탕으로 약물 주입을 제어하는 약물 주입 신호를 생성하여 상기 약물 주입 장치로 상기 약물 주입 신호를 전송하는 관리 서버를 포함하는, 약물 주입 시스템.하나 이상의 프로세서들, 및 상기 하나 이상의 프로세서들에 의해 실행되는 하나 이상의 프로그램들을 저장하는 메모리를 구비한 컴퓨팅 장치에서 수행되는 방법으로서,동물에 부착된 약물 주입 장치로부터 동물 센싱 정보를 수신하는 단계; 상기 동물 센싱 정보를 바탕으로 동물에 약물을 주입하도록 상기 약물 주입 장치를 제어하는 약물 주입 신호를 생성하는 단계; 및상기 약물 주입 신호를 상기 약물 주입 장치로 전송하는 단계를 포함하는, 약물 주입 방법.하나 이상의 프로세서들, 및상기 하나 이상의 프로세서들에 의해 실행되는 하나 이상의 프로그램들을 저장하는 메모리를 구비한 컴퓨팅 장치로서,동물에 부착된 약물 주입 장치로부터 동물 센싱 정보를 수신하는 통신 모듈; 및상기 동물 센싱 정보를 바탕으로 상기 동물에 약물을 주입하도록 상기 약물 주입 장치를 제어하는 약물 주입 신호를 생성하는 약물 주입 제어 모듈을 포함하는, 컴퓨팅 장치.동물에 부착되어 약물을 주입하는 약물 주입부;상기 동물의 정보를 측정하는 센서부; 및상기 측정된 동물 센싱 정보를 외부 서버로 전송하는 통신부를 포함하는, 약물 주입 장치., Ltext: 농업, prediction: 임업
979/1059 Row 979: application_number: 1020190160850, combined_string: invention_title: 돈사 소독 및 살균을 위한 ICT LED 살균 및 질병 관리시스템 abstract: 본 발명은 사육공간의 소독 및 살균을 위한 ICT LED 살균 및 질병 관리시스템에 관한 것으로, 더욱 상세하게는, 정보통신기술(Infromation Communication Technology)을 이용하여 사육 공간에 대한 소독(disinfection)과 살균(sterilization)을 실시하여 축사를 살균하고, 자돈의 위치 정보와 LED 동작 정보를 바탕으로 핸드폰과 컴퓨터를 활용하여 LED살균등으로 소독을 실시하고, 관리할 수 있는 사육공간의 소독 및 살균을 위한 ICT LED 살균 및 질병 관리시스템에 관한 것이다. ICT LED 살균 및 질병 관리시스템은 사육공간 내부를 센싱하여 상기 사육공간 내부에 가축이 존재하는지 여부를 지시하는 검출신호를 생성하는 센서, 제1대역의 전자기파를 방출하는 제1LED모듈, 제2대역의 전자기파를 방출하는 제2LED모듈 및 상기 센서로부터 상기 검출신호를 획득하고, 상기 검출신호에 기반하여 상기 사육공간 내부에 가축이 존재하는지 여부를 판정하며, 상기 사육공간 내부에 가축이 존재하는지 여부에 따라 상기 제1LED모듈 및 상기 제2LED모듈의 on/off 제어를 수행하는 제어부를 포함한다. claims: ICT LED 살균 및 질병 관리시스템에 있어서,사육공간 내부를 센싱하여 상기 사육공간 내부에 가축이 존재하는지 여부를 지시하는 검출신호를 생성하는 센서;제1대역의 전자기파를 방출하는 제1LED모듈;제2대역의 전자기파를 방출하는 제2LED모듈; 및상기 센서로부터 상기 검출신호를 획득하고, 상기 검출신호에 기반하여 상기 사육공간 내부에 가축이 존재하는지 여부를 판정하며, 상기 사육공간 내부에 가축이 존재하는지 여부에 따라 상기 제1LED모듈 및 상기 제2LED모듈의 on/off 제어를 수행하는 제어부;를 포함하는 것을 특징으로 하는돈사 소독 및 살균을 위한 ICT LED 살균 및 질병 관리시스템.컴퓨팅 디바이스에 의해 수행되는 사육공간의 소독 및 살균을 위한 ICT LED 살균 및 질병 관리방법에 있어서,(a) 상기 사육공간 내부에 가축이 존재하는지 여부를 지시하는 검출신호를 센서로부터 획득하는 검출신호 획득단계(s10);(b) 상기 검출신호를 기반으로 상기 사육공간 내부에 가축이 존재하는지 여부를 판정하는 판정단계(s20); 및(c) 상기 판정단계에서의 상기 사육공간 내부에 가축이 존재하지 여부에 대한 판정결과에 따라 상기 사육공간에 설치된 서로 다른 대역의 전자기파를 방출하는 제1LED모듈 또는 제2LED모듈에 대한 on/off 제어를 수행하는 on/off 제어 수행단계(s40);를 포함하는돈사 소독 및 살균을 위한 ICT LED 살균 및 질병 관리방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

980/1059 Row 980: application_number: 1020190152017, combined_string: invention_title: 돈사용 난방장치 abstract: 개시되는 돈사용 난방장치는, 금속 보호관과, 금속 보호관의 내부 중심을 따라 배치되는 전열선을 가지는, 전기에너지를 열에너지로 변환시키는 전열부; 알루미늄 강판을 절곡시켜 형성되되, 전열부에서 발생한 열을 돼지가 사육되는 공간으로 반사하는 열 반사판; 및 금속 보호관을 파지하는 행거브라켓과, 행거브라켓을 열 반사판에 고정시키는 고정볼트를 가지는 클램프;를 포함한다. claims: 금속 보호관과, 상기 금속 보호관의 내부 중심을 따라 배치되는 전열선을 가지는, 전기에너지를 열에너지로 변환시키는 전열부;알루미늄 강판을 절곡시켜 형성되되, 상기 전열부에서 발생한 열을 돼지가 사육되는 공간으로 반사하는 열 반사판; 및상기 금속 보호관을 파지하는 행거브라켓과, 상기 행거브라켓을 상기 열 반사판에 고정시키는 고정볼트를 가지는 클램프;를 포함하는 돈사용 난방장치.청구항 1에 있어서,상기 돈사용 난방장치,상기 전열부에서 발생하는 난방열을 이용해 해충 살충제를 증발시키고 증발 시 발생하는 증기를 이용해 해충을 퇴치하는 해충 방제부;를 더 포함하며,상기 해충 방제부는,하부가 상기 열 반사판의 제 1 반사부재의 외측면에 고정되는, 수평한 링 형상의 홀더;내부에 액상의 해충 살충제를 담을 수 있는 용기 형상으로 제공되며, 상기 홀더의 내부로 수용되어 지지되되 하부는 상기 제 1 반사부재의 외측면에 접촉되는 훈증용기; 및상기 훈증용기의 상부를 덮는 오목한 단면을 가지는 트레이를 가지되, 상기 트레이의 내부로는 해충을 유인할 수 있는 미끼가 담겨지고, 상기 훈증용기에 담겨진 상기 해충 살충제의 증기가 배출되는 다수의 증기 배출공이 형성되는 유인트랩;을 포함하는 돈사용 난방장치,, Ltext: 농업, prediction: 임업
981/1059 Row 981: application_number: 1020190141535, combined_string: invention_title: 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법 abstract: 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법이 제시된다. 일 실시예에 따른 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법은, 돈사 내 설치된 카메라를 통해 돈방 내 돼지 영상을 획득하는 단계; 상기 돼지 영상에서 돈방의 바닥과 돼지를 분리하기 위해 전배경 분리 작업을 수행하여 Gray 값이 살아있는 배경과 분리된 돼지 이미지 획득하는 단계; 상기 돼지 이미지에서 연결 요소 레이블링(Connected Component Labeling) 기법을 사용하여 돼지의 중심점과 차지하는 면적을 획득하는 단계; OpenCV를 사용하여 획득한 상기 중심점으로부터 돼지의 외곽선을 잇는 선분을 연결하는 단계; 및 연결된 상기 선분의 길이를 비교하여 그 길이의 차를 각각 구해, 상기 선분 간의 길이 차이가 일정 수준 이상일 경우, 돼지의 자세가 바르지 못하다고 판단하는 단계를 포함하여 이루어질 수 있다. claims: 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법에 있어서, 돈사 내 설치된 카메라를 통해 돈방 내 돼지 영상을 획득하는 단계; 상기 돼지 영상에서 돈방의 바닥과 돼지를 분리하기 위해 전배경 분리 작업을 수행하여 Gray 값이 살아있는 배경과 분리된 돼지 이미지 획득하는 단계; 상기 돼지 이미지에서 연결 요소 레이블링(Connected Component Labeling) 기법을 사용하여 돼지의 중심점과 차지하는 면적을 획득하는 단계; OpenCV를 사용하여 획득한 상기 중심점으로부터 돼지의 외곽선을 잇는 선분을 연결하는 단계; 및 연결된 상기 선분의 길이를 비교하여 그 길이의 차를 각각 구해, 상기 선분 간의 길이 차이가 일정 수준 이상일 경우, 돼지의 자세가 바르지 못하다고 판단하는 단계를 포함하는, 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

982/1059 Row 982: application_number: 1020190142107, combined_string: invention_title: 개량된 냉온풍 겸용 악취 제거장치 abstract: 본 발명은 악취 발생시설 내부에 설치되어 악취 발생시설의 악취를 제거하기 위한 악취 제거장치에 있어서, 악취가 발생하는 악취 발생시설 실내의 공기를 포집하여 1차로 먼지 및 오염물질을 흡착제거하는 1차오염제거필터; 상기 1차오염제거필터를 통해 먼지 및 오염물질이 제거된 공기에 물받이통과 연결되어 일정압력으로 노즐을 통해 물안개를 분사하여 공기중에서 물에 용해되는 암모니아를 포함하는 오염물질을 분리하는 2차물안개분사실; 상기 2차물안개분사실을 통과한 공기가 통과되어 미 제거된 오염물질을 제거하는 호기성 미생물인 효모 종균 또는 바실러스 종균 중 하나이상이 우드칩에 분사된 3차우드칩실; 상기 3차우드칩실을 통과한 공기에서 미 제거된 오염물질을 폴링(pall ring)으로 흡수 분리하는 4차폴링실; 상기 4차폴링실을 통과한 공기에서 미 제거된 오염물질을 제거하는 부직포를 포함하는 5차미세먼지필터; 상기 5차미세먼지필터를 통과한 공기에 이산화수소, 탄산수소나트륨, 에탄올, 시클로덱스트린을 포함하는 약재가 투입된 약품통과 연결되어 약품펌프에 의해 약재액을 분사하여 미 제거된 오염물질을 제거하는 6차약품분사실; 상기 6차약품분사실을 통과한 공기를 통과시켜 물 입자를 제거하는 부식포를 포함하는 7차습기제거필터; 상기 7차습기제거필터를 통과한 공기에서 미 제거된 오염물질을 다시 제거하는 부직포를 포함하는 8차미세먼지필터; 및 상기 8차미세먼지필터를 통과한 정제된 공기를 악취 발생시설 내부로 다시 순환 배출시키는 음압 흡입팬을 구비하는 개량된 냉온풍 겸용 악취 제거장치에 관한 것이다.이러한 본 발명은 우사, 돈사, 계사 및 분뇨 처리장과 도금시설, 나염시설 등 악취 발생시설에서 발생하는 악취를 효율적으로 제거할 수 있고, 동시에 외부의 공기 유입없이 악취 발생시설 내부의 온도를 적절한 온도로 유지할 수 있으며, 특히 악취 발생시설 외부에서 구제역, 조류인플루엔자(AI), 아프리카돼지열병(ASF; African swine fever) 등의 가축전염병 발생시 외부의 질병세균의 실내유입을 근본적으로 차단하여 악취 발생시설 내부의 세균감염을 차단시킬 수 있어 가축의 질병감염 및 질병사를 근본적으로 차단할 수 있는 효과가 있다. claims: 악취 발생시설(40) 내부에 설치되어 악취 발생시설의 악취를 제거하기 위한 악취 제거장치에 있어서,악취가 발생하는 악취 발생시설(40) 실내의 공기를 포집하여 1차로 먼지 및 오염물질을 흡착제거하는 1차오염제거필터(11);상기 1차오염제거필터(11)를 통해 먼지 및 오염물질이 제거된 공기에 물받이통(12a)과 연결되어 일정압력으로 노즐(12b)을 통해 물안개를 분사하여 공기중에서 물에 용해되는 암모니아를 포함하는 오염물질을 분리하는 2차물안개분사실(12);상기 2차물안개분사실(12)을 통과한 공기가 통과되어 미 제거된 오염물질을 제거하는 호기성 미생물인 효모 종균 또는 바실러스 종균 중 하나이상이 우드칩(13a)에 분사된 3차우드칩실(13);상기 3차우드칩실(13)을 통과한 공기에서 미 제거된 오염물질을 폴링(pall ring)(14a)으로 흡수 분리하는 4차폴링실(14);상기 4차폴링실(14)을 통과한 공기에서 미 제거된 오염물질을 제거하는 부직포를 포함하는 5차미세먼지필터(15);상기 5차미세먼지필터(15)를 통과한 공기에 이산화수소, 탄산수소나트륨, 에탄올, 시클로덱스트린을 포함하는 약재가 투입된 약품통(16a)과 연결되어 약품펌프(16b)에 의해 약재액을 분사하여 미 제거된 오염물질을 제거하는 6차약품분사실(16);상기 6차약품분사실(16)을 통과한 공기를 통과시켜 물 입자를 제거하는 부식포를 포함하는 7차습기제거필터(17);상기 7차습기제거필터(17)를 통과한 공기에서 미 제거된 오염물질을 다시 제거하는 부직포를 포함하는 8차미세먼지필터(18); 및상기 8차미세먼지필터(18)를 통과한 정제된 공기를 악취 발생시설(40) 내부로 다시 순환 배출시키는 음압 흡입팬(19)을 구비함을 특징으로 하는 개량된 냉온풍 겸용 악취 제거장치., Ltext: 농업, prediction: 임업
983/1059 Row 983: application_number: 1020190137589, combined_string: invention_title: 돈사의 슬랏받침바연결구 abstract: 본 발명의 효과는돈사 내 돈방 바닥을 형성하는 다공형 슬랏(110)이 얹혀지는 중공체 슬랏바(Slat bar 또는 파이프)(100)를 길이로 연결시켜 자유로운 길이의 슬랏바(100)를 구성함과 함께, 슬랏바(100) 끝단 구멍(11)을 밀폐시켜 오염원 유입으로 발생되는 오염, 부폐 등으로 인한 유해균의 서식을 방지하고, 미려성을 충족하도록 단부가 형성되는 밀폐캡(10-1)을 겸할 수 있도록 구성된 돈사의 바닥재 슬랏받침바 연결구(10)를 제공하므로써 안정된 슬랏의 구성과 견고성 및 오염 병균의 서식을 방지할 수 있는 효과를 발휘할 수 있도록 하는 것이다. claims: 돼지를 사육하는 돈사의 돈방에 돼지가 기거하고 배출하는 돈분을 돈분집류실(200)로 낙하시키는 슬랏(110)을 돈분집류실(200)이 형성된 슬랏바받침(120)에 얻쳐지는 슬랏바(100)를 길이로 연결하는 슬랏받침바연결구(10)를 구성하되,중공부를 형성하는 관체로 구성된 슬랏바(100) 단부 구멍(11)에 삽입되게 중앙으로부터 점차적으로 좁아지는 형태로 전후 또는 좌우로 분할 구성된 상하면 또는 좌우측면에 미끄럼면(15)을 형성한 복수의 압인돌기(13)가 구성되는 좌우삽입관(12),상기 좌우삽입관(12)은 중심부에 연결되는 슬랏바(100)의 단면과 밀착되는 밀폐돌기(14)가 구성되어 연결되는 슬랏바(100)의 단면을 밀폐할 수 있도록 구성함을 특징으로 하는 돈사의 슬랏받침바연결구., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

984/1059 Row 984: application_number: 1020190134740, combined_string: invention_title: 종돈 조기 선발을 위한 SNP chip 데이터 생성 및 분석 기술 abstract: 본 발명은 자동화 장비를 이용하여 종돈의 샘플에서 DNA를 추출하고 유전체 정보를 확인, 분석 후 데이터베이스를 저장하는 일련의 종돈 조기 선발을 위한 SNP chip 데이터 생성 및 분석 기술에 관한 것이다.본 발명의 종돈 조기 선발을 위한 SNP chip 데이터 생성 및 분석 기술은, 자동화 시스템을 갖춘 DNA 추출 기기와; 추출된 DNA의 유전체적 특징을 확인하기 위한 60,000개의 단일염기서열(SNP) 검사 기기와; 이를 분석하기 위한 소프트웨어와 분석된 자료를 저장할 수 있는 서버로 구성된다.본 발명은 종래의 유전체 분석에 널리 사용되고 있는 분석법의 장점을 그대로 살림과 동시에 DNA추출 및 분석과 저장의 일련의 과정을 체계화 함으로써, 결과의 신뢰성을 높이고 분석 시간을 단축 하는 효과가 있다. claims: 종돈의 샘플 채취를 시작으로 자동화 장비를 이용한 DNA 추출 및 추출된 DNA의 정도 관리와 illumina infinium porcine 60K chip을 이용한 유전체 확인 및 genome studio를 이용한 분석과 서버 저장의 일련의 과정을 특징으로 하는 종돈 조기 선발을 위한 SNP chip 데이터 생성 및 분석 기술., Ltext: 농업, prediction: 임업
985/1059 Row 985: application_number: 1020190134575, combined_string: invention_title: 매몰저장탱크를 통한 폐사가축의 발효, 탈취 및 살바이러스 차단 방법 abstract: 본 발명은 폐사가축의 발효, 탈취 및 살바이러스 차단 방법에 관한 것으로, 보다 상세하게는 폐사된 가축, 구제역, 신종플루 및 아프리카 돼지열병 등에 감염된 가축과 같은 오염된 사체를 특정 용기 속에 장입한 채로 매몰처리하되 악취 발생 자체를 차단하여 병원균이 대기를 통해 전파되는 것을 막고, 민원이 생기지 않도록 하면서 침출수 문제도 자연스럽게 해결하여 토양오염이나 2차 환경오염도 일으키지 않은 채 안전하게 처리할 수 있도록 개선된 폐사가축의 발효, 탈취 및 살바이러스 차단 방법에 관한 것이다. claims: 가축 사체가 장입되는 투입구(110)를 구비하고 지중에 매립설치되는 밀폐형 매몰저장탱크(100), 상기 투입구(110)를 밀폐하는 커버(120), 상기 커버(120)의 상면에 설치되고 살바이러스제가 일정수위로 채워진 살바이러스탈취조(130), 상기 살바이러스탈취조(130)의 내부 천정면에 설치된 UV살균탈취기(140), 상기 살바이러스탈취조(130)의 일측 상면에 배관된 배기관(150), 상기 살바이러스탈취조(130)의 일측에 상기 살바이러스제의 수위보다 높은 위치에서 밀폐형 매몰저장탱크(100) 내부와 연통되도록 배관된 바이패스관(160), 일단은 상기 살바이러스제에 침지되고 타단은 상기 밀폐형 매몰저장탱크(100) 내부에 노출되게 배관된 발생가스배출관(170)을 이용하여 매몰저장탱크를 통한 폐사된 가축의 발효, 탈취 및 살바이러스 차단 방법에 있어서;상기 방법을 이용하여 폐사된 가축 사체를 밀폐형 매몰저장탱크(100)의 바닥면에 한 층씩 쌓는 가축 사체 장입단계; 장입된 한 층의 가축 사체에 미생물 발효탈취제(B)를 살포하는 단계; 가축 사체 장입단계와 미생물 발효탈취제 살포단계를 교차로 다수회 반복하여 사체 장입이 완료되면 커버(120)로 밀폐하는 단계; 커버(120) 밀폐 후 부패 및 사체 분해가 진행되면서 발생된 가스를 살바이러스제에 노출시켜 1차로 살균 탈취하는 단계; 1차 살균 탈취와 함께 살바이러스제의 수면 상부로 상승한 기체를 UV살균탈취기(140)로 살균선을 조사하여 2차로 살균 탈취하는 단계; 및, 2차 살균 탈취까지 완료되면 대기중으로 배기하는 배기단계;를 포함하되,상기 미생물 발효탈취제(B)는 당밀액 1ℓ를 기준으로 벤토나이트 분말 250g, 망간아세테이트 150g, 아미노산 150g, 사탕수수 정제당 500g, EM(Effective Micro-organism)원액 50g을 혼합한 후 액체 배지에서 각각 배양된 유산균ㆍ효모균ㆍ바실러스균ㆍ그램 양성 방선균을 첨가한 다음 35℃에서 5일 동안 증식시킨 것을 사용하고;상기 미생물 발효탈취제(B)에는 버섯추출물 200g, 티오바실리스페로옥시단스 50g, 질산망간 10g, NTA(Nitrilotriacetic acid) 50g, 수가용성 철염 10g, 주석산 5g, FeSO4.7H2O 수용액 10㎖을 더 첨가된 것을 특징으로 하는 매몰저장탱크를 통한폐사가축의 발효, 탈취 및 살바이러스 차단 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

986/1059 Row 986: application_number: 1020217013735, combined_string: invention_title: 이종이식 생성물 및 방법 abstract: 인간으로의 임상 이종이식을 위한 생물학적 생성물 및 돼지가 하나 이상의 세포외 표면 글리칸 에피토프를 발현하지 않도록 생물학적으로 조작된 게놈을 갖는 비야생형의 생물학적으로 조작된 돼지를 생산하는 것을 포함하는 인간으로의 임상 이종이식을 위한 생물학적 생성물을 제조하는 방법은 폐쇄된 지정된 병원체가 없는 무리에서 바이오버든-감소 절차에 따라 사육되고, 여기서, 상기 생물학적 생성물은 돼지가 안락사된 후 수확되고 상기 생성물은 돼지로부터 무균적으로 제거되고, 상기 생물학적 생성물은 멸균을 포함하여 처리되고, 상기 생성물을 멸균 용기에 저장하고, 상기 생성물은 하나 이상의 세포외 표면 글리칸을 포함하지 않고, 특정 지정된 병원체가 없고, 생물학적으로 활성이고, 이종이식 후 혈관화할 수 있는 살아있는 세포 및 조직을 포함한다. claims: 인간 수혜자로의 이종이식에 적합한 생물학적 생성물을 생성하는 방법으로서,비야생형의 생물학적으로 조작된 돼지를 생산하는 단계로서, 상기 돼지는 자연 육종 및 자연 출산을 통해 생산되고, 상기 돼지는 하나 이상의 세포외 표면 글리칸 에피토프를 발현하지 않도록 생물학적으로 조작된 게놈을 갖고, 여기서, 상기 돼지는 적어도 다음 병원체: 아스카리스 종 (Ascaris species), 크립토스포리듐 종 (cryptosporidium species), 에키노코쿠스 (Echinococcus), 스트롱길로이드스 스테로콜리스 (Strongyloids sterocolis), 톡소플라스마 곤디 (Toxoplasma gondii), 브루셀라 수이스 (Brucella suis), 렙토스피라 종 (Leptospira species), 미코플라스마 하이오뉴모니애 (mycoplasma hyopneumoniae), 슈도라비스 (pseudorabies), 톡소플라스마 곤디 (Toxoplasma Gondii), 스타필로코쿠스 종 (staphylococcus species), 마이크로피톤 종 (Microphyton species), 및　트리코피톤 종 (Trichophyton　species), 돼지 인플루엔자 (porcine influenza), 거대세포 바이러스 (cytomegalovirus), 아르테리바이러스 (arterivirus), 및 코로나바이러스 (coronavirus)가 없는, 단계, 바이오버든-감소 절차 (bioburden-reducing procedure)에 따라 상기 돼지를 사육하고 상기 돼지를 유지하는 단계로서, 상기 절차는 폐쇄된 무리에서 돼지를 유지함을 포함하며, 상기 폐쇄된 무리에서 다른 모든 동물은 적어도 다음 병원체: 아스카리스 종, 크립토스포리듐 종, 에키노코쿠스, 스트롱길로이드스 스테로콜리스, 톡소플라스마 곤디, 브루셀라 수이스, 렙토스피라 종, 미코플라스마 하이오뉴모니애, 슈도라비스, 톡소플라스마 곤디, 스타필로코쿠스 종, 마이크로피톤 종,　및 트리코피톤 종, 돼지 인플루엔자, 거대세포 바이러스, 아르테리바이러스, 및 코로나바이러스가 없는 것으로 확인되고, 상기 돼지는 상기 폐쇄된 무리 외부에 있는 임의의 비인간 동물 및 동물 사육 시설과의 접촉으로부터 격리시키는, 단계, 상기 돼지로부터 생물학적 생성물을 수확하는 단계로서, 상기 수확 단계는 상기 돼지를 안락사시키고 상기 돼지로부터 생물학적 생성물을 무균적으로 제거함을 포함하는, 단계,수확 15시간 이내에 멸균을 포함하여 상기 생물학적 생성물을 처리하고 상기 생물학적 생성물을 멸균 용기에 저장하는 단계를 포함하되, 상기 생물학적 생성물은 하나 이상의 세포외 표면 글리칸을 함유하지 않고, 여기서, 상기 생성물은 아스카리스 종, 크립토스포리듐 종, 에키노코쿠스, 스트롱길로이드스 스테로콜리스, 톡소플라스마 곤디, 브루셀라 수이스, 렙토스피라 종, 미코플라스마 하이오뉴모니애, 슈도라비스, 톡소플라스마 곤디,스타필로코쿠스 종, 마이크로피톤 종,　및 트리코피톤 종, 돼지 인플루엔자, 거대세포 바이러스, 아르테리바이러스, 및 코로나바이러스가 없고, 여기서, 상기 생성물은 생물학적으로 활성이고 이종이식 후 혈관화할 수 있는 살아있는 세포 및 조직을 포함하고,상기 생성물의 세포 미토콘드리아 활성은 MTT 검정에 의해 측정시 50% 초과이고;상기 생성물은 전형적인 Gal-T 녹아웃 돼지, 전형적인 트리플 녹아웃 돼지, 형질전환 돼지, 야생형 동물, 및/또는 동종이식편으로부터 제조된 이종이식 생성물로부터 얻어진 생물학적 생성물과 비교하여 인간 이종이식 수혜자에게 이식될 때 덜 면역원성이고,상기 생성물은 전형적인 Gal-T 녹아웃 돼지, 전형적인 트리플 녹아웃 돼지, 형질전환 돼지, 야생형 동물, 및/또는 동종이식편으로부터 제조된 이종이식 생성물로부터 얻어진 생물학적 생성물과 비교하여 인간 이종이식 수혜자에게 이식될 때 덜 항원성이고,상기 생성물은 상기 인간 이종이식 수혜자에게 면역억제 약물의 투여 또는 다른 면역억제 요법의 부재 하에 상기 인간 이종이식 수혜자에 의한 거부에 내성이 있는, 방법.제 20 항에 있어서, 부검시 상기 유기체로부터의 비장, 간, 골수, 중추 신경계 및 폐 중 적어도 하나로부터 조직 샘플을 수집하고 동결보존하는 단계를 추가로 포함하는, 방법.제 24 항에 있어서, 상기 생성물을 스캐폴드 상에 상기 생성물과 적어도 동일한 크기로 적용하는 단계, 상기 생성물 및 상기 스캐폴드를 롤링하는 단계, 상기 롤링된 생성물 및 스캐폴드를 멸균 용기에 넣고, 상기 용기를 약 10℃와 약 -80℃ 사이의 온도에서 저장하는 단계를 추가로 포함하는, 방법.제 26 항에 있어서, 상기 게놈은 파괴된 시티딘 모노포스페이트-N-아세틸뉴라민산 하이드록실라제 (CMAH) 유전자를 추가로 포함하는, 생물학적 생성물.인간으로의 임상 이종이식을 위한 생물학적 생성물을 제조하는 방법으로서, 알려진 인간 주요 조직적합성 복합체 유전자 서열을 선택하거나 인간 수혜자의 주요 조직적합성 복합체 유전자를 서열분석하는 단계, 상기 돼지의 세포가 상기 알려진 인간 주요 조직적합성 복합체 유전자 서열의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자 서열의 상응하는 부분을 발현하도록, 상기 돼지의 주요 조직적합성 복합체 유전자 서열의 일부를 상기 알려진 인간 주요 조직적합성 복합체 유전자 서열의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자 서열의 상응하는 부분으로 대체하기 위해 돼지의 세포를 유전적으로 변형하는 단계; 상기 알려진 인간 주요 조직적합성 복합체 유전자 서열의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자 서열의 상응하는 부분을 발현하는 상기 돼지로부터 하나 이상의 세포, 조직, 및/또는 장기를 단리하는 단계로서, 여기서, 상기 단리된 세포, 조직, 및/또는 장기는 생물학적 생성물인, 단계를 포함하는, 방법. 제 37 항 에 있어서, 상기 유전적으로 변형하는 단계는 주형 주요 조직적합성 복합체 서열을 제조하는 단계, CRISPR-Cas9 플라스미드를 제조하는 단계, 주형 주요 조직적합성 복합체 서열을 상기 플라스미드에 클로닝하는 단계, 상기 돼지 세포의 주요 조직적합성 복합체 유전자좌에서 CRISPR 분할 부위를 결정하는 단계, gRNA 서열을 하나 이상의 CRISPR-Cas9 플라스미드에 클로닝하는 단계, CRISPR-Cas9 플라스미드를 돼지 세포에 투여하는 단계, 상기 돼지 세포의 상기 주요 조직적합성 복합체 유전자좌에서 CRIPSR/Cas9 분할을 수행하는 단계, 상기 돼지 세포의 상기 주요 조직적합성 복합체 유전자좌를 상기 알려진 인간 주요 조직적합성 복합체 유전자 서열의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자 서열의 상응하는 부분과 일치하는 하나 이상의 주형 주요 조직적합성 복합체 서열로 대체하는 단계를 포함하는, 방법.파괴된 알파-1,3 갈락토실트랜스퍼라제 유전자를 갖고, 알려진 인간 서열 또는 상기 유전적으로 재프로그래밍된 돼지로부터 단리된 세포, 조직, 및/또는 장기의 인간 수혜자의 주요 조직적합성 복합체의 일부를 발현하도록 유전적으로 변형된 헥 게놈을 포함하는 유전적으로 재프로그래밍된 돼지.제 51 항에 있어서, 상기 유전적으로 재프로그래밍된 돼지의 게놈은 파괴된 시티딘 모노포스페이트-N-아세틸뉴라민산 하이드록실라제 (CMAH) 유전자를 추가로 포함하는, 유전적으로 재프로그래밍된 돼지.파괴된 알파-1,3 갈락토실트랜스퍼라제 유전자를 갖고, 알려진 인간 서열의 주요 조직적합성 복합체 또는 상기 유전적으로 재프로그래밍된 돼지로부터 단리된 세포, 조직, 및/또는 장기의 인간 수혜자를 발현하도록 유전적으로 변형된 헥 게놈을 포함하는 유전적으로 재프로그래밍된 돼지를 제조하는 방법으로서, 상기 방법은 알려진 인간 주요 조직적합성 복합체 서열을 선택하거나 인간 수혜자의 주요 조직적합성 복합체 유전자를 서열분석하는 단계, 적어도 하나의 파괴된 돼지 표면 글리칸 유전자를 갖는 핵 게놈을 포함하는 돼지를 수득하는 단계, 상기 돼지의 세포가 상기 인간 수혜자의 주요 조직적합성 복합체의 일부를 발현하도록, 상기 돼지의 주요 조직적합성 복합 유전자의 일부를 상기 알려진 인간 주요 조직적합성 복합체 유전자의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자의 상응하, Ltext: 농업, prediction: 임업
987/1059 Row 987: application_number: 1020190118818, combined_string: invention_title: 코드를 이용한 스마트 팜 가축 관리 시스템 및 관리 방법 abstract: 개체 정보 인식코드로서 QR 코드 또는 바코드 등을 이용하여 소 또는 돼지 개체를 정확하게 인식하고, 개체 군별 발육 상태를 관리함으로써 최적의 생육환경을 조성할 수 있는 코드를 이용한 스마트 팜 가축 관리 시스템 및 관리 방법에 관한 것으로, 가축에 개체 정보 인식코드를 인가하는 코드 인가 수단, 상기 개체 정보 인식코드를 촬영하는 촬영 수단, 상기 촬영 수단에 의해 촬영된 개체 정보 인식코드를 분석하는 분석 수단, 상기 분석 수단에 의해 분석된 개체 정보 인식코드에 따라 상기 가축을 관리하는 관리 수단을 포함하고, 상기 코드 인가 수단은 자돈이 태어나서 최초 예방 접종시 QR 코드 또는 바코드를 자돈의 등, 옆구리 등에 복수 개 이식하고, 상기 촬영 수단은 상기 개체 정보 인식코드인 QR 코드 또는 바코드를 촬영하기 위해 돈방의 천장에 설치된 카메라인 구성을 마련하여, 가축에 대해 최적의 생육환경을 조성할 수 있다. claims: 가축에 개체 정보 인식코드를 인가하는 코드 인가 수단,상기 개체 정보 인식코드를 촬영하는 촬영 수단,상기 촬영 수단에 의해 촬영된 개체 정보 인식코드를 분석하는 분석 수단,상기 분석 수단에 의해 분석된 개체 정보 인식코드에 따라 상기 가축을 관리하는 관리 수단을 포함하고,상기 코드 인가 수단은 자돈이 태어나서 최초 예방 접종시 QR 코드 또는 바코드를 자돈의 등, 옆구리 등에 복수 개 이식하고,상기 촬영 수단은 상기 개체 정보 인식코드인 QR 코드 또는 바코드를 촬영하기 위해 돈방의 천장에 설치된 카메라인 것을 특징으로 하는 코드를 이용한 스마트 팜 가축 관리 시스템.(a) 가축에 개체 정보 인식코드로서 QR 코드 또는 바코드를 인가하는 단계,(b) 상기 단계 (a)에서 인가된 가축의 QR 코드 또는 바코드를 촬영하는 단계,(c) 상기 단계 (b)에서 촬영된 QR 코드 또는 바코드를 분석하는 단계,(d) 상기 단계 (c)에 의해 분석된 QR 코드 또는 바코드에 따라 상기 가축의 이력 정보를 관리하는 단계를 포함하고,가축의 성장에 따라 QR 코드 또는 바코드의 면적이 넓어지므로, 상기 단계 (c)에서는 면적 정보를 무게 정보로 정확하게 환산하기 위한 기준 데이터가 설정된 것을 특징으로 하는 코드를 이용한 스마트 팜 가축 관리 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

988/1059 Row 988: application_number: 1020190117940, combined_string: invention_title: 홍 단심 흑돼지 사육방법 abstract: 본 발명은 산죽(Sasa borealis; 淡竹葉)과 법제 유황을 이용한 조성물을 살균 소독에 적용하고, 산죽의 탄화물을 사료에 배합하여 친환경적으로 돼지를 사육하는 방법에 대한 것으로, 본 발명의 실시예에 따르면, 돼지의 사육에 필요한 생육환경을 조성함에 있어, 산죽과 법제유황을 포함하는 물질을 이용한 소독과 음용 사료를 제조하여 공급할 수 있도록 해, 친환경적인 사육환경을 조성하고 선홍색 빛깔의 육질을 가지는 돼지를 사육할 수 있다. claims: 원재료인 산죽(Sasa borealis)을 열분해하여, 산죽 수액과 탄화물로 분리하는 1단계;상기 1단계에서 추출된 상기 산죽 수액과 법제된 유황 및 가성소다, 소금, 해록석을 혼합하여, 산죽 금단 살균조성물을 형성하는 2단계;상기 산죽 금단 살균조성물을 물과 혼합하여 축사에 분사하여 소독하는 3단계;를 포함하는, 홍 단심 흑돼지 사육 방법., Ltext: 농업, prediction: 임업
989/1059 Row 989: application_number: 1020190114623, combined_string: invention_title: 승가 검사기를 구비한 돼지 사육장치 abstract: 기존의 돼지 발정 측정은 별도의 장치를 돼지에 결합하거나, 카메라 장치 등으로 돼지의 행동변화를 관찰하는 것으로만 측정 가능하였기 때문에 부정확하고 돼지가 불편해했다. 본 발명은 상기와 같은 문제를 해결하기 위하여, 입구도어, 체중 측정부, 급이부 및 출구 도어 부를 구비한 자동 사육 장치의 상기 체중 측정부는 직사각형의 상판프레임과 상판철망으로 구성된 상판과 상기 상판의 하부에서 상기 상판의 네모서리와 상기 상판의 장변의 중간에 6개의 로드셀이 구비되고, 돼지가 상기 자동 사육 장치에 들어올 때 발생하는 상기 6개의 로드셀에서 측정되는 돼지 걸음걸이에 따른 체중의 변화 패턴으로부터 돼지의 발정 여부를 판단하며, 상기 돼지의 발정 여부 판단에서 돼지의 발정으로 판단되는 경우, 상기 돼지의 발정을 정확히 검사하기 위하여 상기 돼지 체중 측정부 상부에 구비된 승가검사기의 상하이동부를 하강하여 상기 돼지의 등 부위를 눌러 돼지가 승가를 여락하는지 검사하는 승가검사기를 구비하는 것을 특징으로 하는 승가 검사기를 구비한 돼지 사육 장치를 제공한다. 이러한 구성에 의하여 암퇘지의 발정 여부를 정확히 확인할 수 있는 효과가 있다. claims: 입구도어, 체중 측정부, 급이부 및 출구 도어 부를 구비한 자동 사육 장치의 상기 체중 측정부는 직사각형의 상판프레임과 상판철망으로 구성된 상판과 상기 상판의 하부에서 상기 상판의 네모서리와 상기 상판의 장변의 중간에 6개의 로드셀이 구비되고, 또한, 상기 6개의 로드셀 중 출구 도어부 쪽에 설치된 로드셀에 무게가 많이 실리면 돼지가 체중 측정부에 완전히 들어온 것으로 인식하여, 상기 사육장치의 입구를 닫아 다른 돼지의 진입을 막으며, 돼지가 상기 자동 사육 장치에 들어올 때 발생하는 상기 6개의 로드셀에서 측정되는 돼지 걸음걸이에 따른 체중의 변화 패턴으로부터 돼지의 발정 여부를 판단하고, 상기 돼지의 발정 여부 판단에서 돼지의 발정으로 판단되는 경우, 상기 돼지의 발정을 정확히 검사하기 위하여 상기 돼지 체중 측정부 상부에 구비된 승가검사기의 상하이동부를 하강하여 상기 돼지의 등 부위를 눌러 돼지가 승가를 여락하는지 검사하는 승가검사기를 구비하는 것을 특징으로 하는 승가 검사기를 구비한 돼지 사육 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

990/1059 Row 990: application_number: 1020190114624, combined_string: invention_title: 승가 검사기를 구비한 돼지 사육장치 abstract: 기존의 돼지 발정 측정은 별도의 장치를 돼지에 결합하거나, 카메라 장치 등으로 돼지의 행동변화를 관찰하는 것으로만 측정 가능하였기 때문에 부정확하고 돼지가 불편해했다. 본 발명은 상기와 같은 문제를 해결하기 위하여, 입구도어, 체중 측정부, 급이부 및 출구 도어 부를 구비한 자동 사육 장치의 상기 체중 측정부는 직사각형의 상판프레임과 상판철망으로 구성된 상판과 상기 상판의 하부에서 상기 상판의 네모서리와 상기 상판의 장변의 중간에 6개의 로드셀이 구비되고, 돼지가 상기 자동 사육 장치에 들어올 때 발생하는 상기 6개의 로드셀에서 측정되는 돼지 걸음걸이에 따른 체중의 변화 패턴으로부터 돼지의 발정 여부를 판단하며, 상기 돼지의 발정 여부 판단에서 돼지의 발정으로 판단되는 경우, 상기 돼지의 발정을 정확히 검사하기 위하여 상기 돼지 체중 측정부 상부에 구비된 승가검사기의 상하이동부를 하강하여 상기 돼지의 등 부위를 눌러 돼지가 승가를 여락하는지 검사하는 승가검사기를 구비하는 것을 특징으로 하는 승가 검사기를 구비한 돼지 사육 장치를 제공한다. 이러한 구성에 의하여 암퇘지의 발정 여부를 정확히 확인할 수 있는 효과가 있다. claims: 입구도어, 체중 측정부, 급이부 및 출구 도어 부를 구비한 자동 사육 장치의상기 체중 측정부는 직사각형의 상판프레임과 상판철망으로 구성된 상판과 상기 상판의 하부에서 상기 상판의 네모서리와 상기 상판의 장변의 중간에 6개의 로드셀이 구비되고, 돼지가 상기 체중 측정부상기 체중 측정부는 과정에서 상기 6개의 로드셀에 측정되는 좌우 로드셀의 무게 값과 정지 돼지의 무게를 측정하고 이를 비교함으로써 돼지가 서있거나, 걷는 중에 좌우에 동일한 무게가 실리는지를 판단할 수 있고, 이를 이용하여 돼지의 걸음걸이 이상여부를 판단할 수 있으며, 돼지가 상기 자동 사육 장치에 들어올 때 발생하는 상기 6개의 로드셀에서 측정되는 돼지 걸음걸이에 따른 체중의 변화 패턴으로부터 돼지의 발정 여부를 판단하며, 상기 돼지의 발정 여부 판단에서 돼지의 발정으로 판단되는 경우, 상기 돼지의 발정을 정확히 검사하기 위하여 상기 돼지 체중 측정부 상부에 구비된 승가검사기의 상하이동부를 하강하여 상기 돼지의 등 부위를 눌러 돼지가 승가를 여락하는지 검사하는 승가검사기를 구비하는 것을 특징으로 하는 승가 검사기를 구비한 돼지 사육 장치., Ltext: 농업, prediction: 농업
991/1059 Row 991: application_number: 1020190111392, combined_string: invention_title: 동물복지형 모돈사 abstract: 본 발명은 새끼돼지를 분만한 갓난 젖먹이새끼를 키우는 모돈(sow)이 젖먹이 기간동안 일정한 활동을 할 수 있는 공간을 형성시켜 동물보호법 규정에서의 불편함과 고통 및 정상적인 행동을 표현할 수 있도록 함으로써 스트레스로부터의 자유와 법 제3조(동물보호의 기본원칙)에 충족하도록 함과,어미로부터 젓을 먹는 갓난 새끼가 모돈(sow)으로부터의 압사를 방지할 수 있도록 피난공간을 구성하는 모돈사(Farrowing Pen 또는 Farrowing crate)를 제공하는 동물복지형 모돈사로 모돈과 새끼 돼지가 더욱 행복하고 편안함을 보여주는 가장 중요한 혁신 중 하나로 간주되는 돼지 성능을 향상시키고 복지에 대한 우수한 표준을 도출하는 효과를 발휘하는 것이다. claims: 모돈사(100)를 지지하는 H빔(110)에 돼지가 기거하고 분뇨를 배출하는 슬랏(120)에 개폐수단(150)으로 개폐되는 개폐문(151)을 형성한 전후외벽(130)과, 좌우외벽(140,140-1) 및 사료통(152)과 물통(154)을 구성하는 모돈사에 있어서,상기 모돈사(100)에 제 1스톨수단(A)과, 제 2스톨수단(B)를 구성하되,개폐문(151)을 중심으로 구성된 제 1전후외벽(130-1)의 외벽기둥(131)에 힌지된 연동판(21)에 고정되고 복수의 스톨봉(22)을 구성한 스톨제어판(20)과, 스톨제어판(20)에서 돌출된 가이드봉(23)에 끼워지는 안내장공(24)과 손잡이(25)를 구성한 제어판(26),스톨제어판(20)에 힌지되고 제어판(26)으로 연동되는 개폐판(27)에 돌출된 개폐핀(28)을 구성하고, 상기 개폐핀(28)이 제어되는 체결홈(11)과 안착홈(12)을 구성한 가이드판(10)에 스톱봉(13)을 구성시켜 스톨제어판(20)을 내외로 이동과 제어할 수 있도록 구성되는 제 1스톨수단(A),제 2전후외벽(130-2)의 외벽기둥(131-1)에 이송롤(41)이 이동하는 레일(32)과 복수의 정지홈(33)을 구성한 제 1정지판(30)과 제 2정지판(31),복수의 스톨봉(22)을 구성하고 돌출부를 형성한 연동판(40) 상부측 외향 돌출부에 한쌍의 이송롤(41)을 힌지시켜 레일(32)에서 이동되게 구성함과, 연동판(40)의 내향 돌출부에 &amp;quot;&gt;&amp;quot;형상의 키제어판(42)을 힌지하고 키제어판(42)의 상부 단부에 이동조작봉(43)을 구성하고 하부끝단에 상기 제 1정지판(30)과 제 2정지판(31)에 구성된 정지홈(33)에서 출입되는 키봉(44)을 구성한 승하강키판(45)을 힌지시켜 이동조작봉(43)으로 승하강키판(45)을 조작하여 승하강되는 키봉(44)이 제 1정지판(30)과 제 2정지판(31)의 정지홈(33)에서 이탈과 삽입으로 제어하는 제 2스톨수단(B)으로 구성함을 특징으로 하는 동물복지형 모돈사., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

992/1059 Row 992: application_number: 1020190104895, combined_string: invention_title: 도축 폐기물을 함유하는 곤충 사료용 조성물, 이를 이용하여 사육한 곤충을 포함하는 가축, 어패류 또는 반려동물 사료용 조성물 abstract: 본 발명은 오리, 돼지 또는 소 등의 가축 도축 폐기물을 함유하는 곤충 사료용 조성물, 또는 상기 곤충 사료용 조성물로 사육된 동애등에와 이의 분변토를 함유하는 가축, 어패류 또는 반려동물 사료용 조성물에 관한 것으로서, 상기 곤충 사료용 조성물, 가축/어패류/반려동물 사료용 조성물은 복잡한 사료 제조 공정을 필요로 하지 않아 매우 경제적이며, 환경오염의 요인으로 대두되고 있고, 그 처리에 대량의 비용이 소요되는 도축 폐기물을 효과적으로 재활용할 수 있어 친환경적이라는 이점이 존재한다. 덧붙여, 상기 곤충 사료용 조성물을 이용하여 곤충을 사육하는 경우, 영양적으로 매우 뛰어난 품질을 가지는 곤충을 얻을 수 있어, 이러한 곤충을 포함하는 가축, 어패류 또는 반려동물 사료용 조성물의 품질 또한 우수해질 수 있는 이점이 있다. 이 외에도, 상기 가축, 어패류 또는 반려동물 사료용 조성물은 동애등에와 이의 분변토가 함유되기 때문에, 일반곡류만을 사용하던 기존 가축사료와 달리 동물성 고급 단백질을 함유할 수 있고, 가축의 건강유지에 도움이 될 수 있다. claims: 도축 폐혈, 도축 폐모, 음식물, 미강, 갈대, 옥수수대, 왕겨 및 깻묵을 포함하는 것을 특징으로 하는 곤충 사료용 조성물., Ltext: 농업, prediction: 임업
993/1059 Row 993: application_number: 1020200144876, combined_string: invention_title: 죽염 소금이 포함된 친환경 메추리 사료 조성물 제조 방법 abstract: 본 발명은 죽염 소금이 포함된 친환경 메추리 사료 조성물 및 이를 이용한 메추리알 생산 방법에 관한 것으로, 본 발명에 따른 죽염 등을 포함하는 메추리 사료 조성물 및 이를 이용한 메추리 알의 생산 방법을 통해, 사료를 섭취하는 메추리의 면역력을 높이는 동시에 산란되어 얻어지는 메추리알의 영양학적 가치를 높일 수 있고, 소비자들에게 건강하고 안전한 메추리알을 제공할 수 있다. claims: 죽염, 울금 및 스테비아를 3~5분간 75~85 ℃에서 가열 및 건조하는 단계;건조된 죽염, 울금 및 스테비아를 0.1mm 이하의 입자가 되도록 분쇄하여 분말화하는 단계; 및상기 분말화된 죽염, 울금 및 스테비아를 가금류 기초 사료에 혼합하는 단계를 포함하는,메추리용 사료 조성물의 제조방법으로서,상기 혼합 단계 이후 85~95℃의 편백수 및 편백 오일이 포함된 수증기를 분사하여 가열하는 단계를 추가로 포함하는, 메추리용 사료 조성물의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

994/1059 Row 994: application_number: 1020200139670, combined_string: invention_title: 부숙유기질비료의 살균, 탈취 및 부숙 촉진을 위한 사료 첨가제 및 이의 제조방법 abstract: 본 발명은 수용성 황 분말, 광물성 물질 및 비타민제를 포함하는 사료 첨가제로서, 상기 사료 첨가제를 포함하는 배합사료를 부숙유기질비료에 첨가하는 경우 살균, 탈취 및 부숙 촉진 효과를 제공한다. claims: 사료 원료 및 기능성 사료 첨가제;를 포함하는 배합사료이며,상기 기능성 사료 첨가제는 수용성 황 분말 10 내지 20 중량%, 광물성 물질 60 내지 80 중량% 및 비타민제 10 내지 20 중량%를 포함하고,상기 수용성 황 분말은 자연계 또는 화학정제 과정에서 채집이나 부산물로 만들어진 광물성 유황을 정제 및 건조한 후 10℃ 이하에서 저온 파쇄하여 얻어진 분말이고,상기 광물성 물질은 염류를 포함하는 제1 광물성 물질을 0.05~0.1 중량부; 제일인산칼륨, 제이인산칼륨 및 제삼인산칼륨으로 구성되는 군에서 선택되는 1종 이상을 포함하는 제2 광물성 물질을 1~2 중량부; 아미노산킬레이트, 황산나트륨 및 황산수소나트륨으로 구성되는 군에서 선택되는 1종 이상을 포함하는 제3 광물성 물질을 50~60 중량부; 및 탄산아연, 황산구리(황산동) 및 황산아연으로 구성되는 군에서 선택되는 1종 이상을 포함하는 제4 광물성 물질을 10~20 중량부;를 포함하는 혼합 광물성 물질이며,상기 비타민제는 메나디온(menadion), 메나디온 아황산나트륨염 및 메나디온 아황산 니코틴아마이드로 구성되는 군에서 선택되는 1종 이상을 포함하고,상기 배합사료를 부숙유기질비료에 첨가하는 경우 탈취 효과를 갖는 기능성 배합사료., Ltext: 농업, prediction: 농업
995/1059 Row 995: application_number: 1020200131909, combined_string: invention_title: 배기 장치 포깅 시스템 abstract: 본 발명은 배기 장치 포깅 시스템에 관한 것으로, 포깅 시스템에 의해 먼지 또는 악취를 포함하는 입자를 효율적으로 제거할 수 있는 장점이 있다. claims: 내측에 가축을 기를 수 있도록 형성된 공간을 포함하는 축사(100);축사(100) 내부로부터 형성되는 먼지 또는 악취가스를 포함하는 미세입자(600)를 외부로 배출시키기 위해 외부와 연동 형성된 제1배기구(400);제1배기구(400) 내측에 미세입자(600)가 용이하게 포집되어 이동될 수 있도록 하나 이상 형성된 제1배기팬(300); 및제1배기구(400)를 관통하며, 유체(561)가 제1배기구(400) 내측 방향으로 분사될 수 있도록 형성된 제1연결관(500);을 포함하고,유체(561)가 제1배기구(400) 내측 방향으로 고르게 분사될 수 있도록 제1배기팬(300)과 이격 형성된 피팅(550)을 포함하며,유체(561)는 물, 오일, 약제, 세척제 또는 미생물 분해제 중 선택되는 어느 하나를 포함하고,피팅(550) 일측에 유체(561)가 제1배기구(400) 내부 또는 외부 중 선택되는 어느 하나 이상으로 분사될 수 있도록 형성된 제1분무노즐(560)을 포함하며,제1연결관(500) 또는 피팅(550) 중 선택되는 어느 하나 이상의 외측에 연동 형성된 제1온수관(700)을 포함하고,제1연결관(500) 일측 또는 타측 중 선택되는 어느 하나 이상에 유체(561)가 고르게 분사될 수 있도록 관통 형성되며, 제1배기구(400) 내측에 배치되고, 제1배기팬(300)과 마주보는 방향으로 형성된 분사홈을 포함하며,피팅(550)의 양 단부 및 제1연결관(500)을 압력장치에 의해 내경의 변형이 수행되도록 가압하여 형성된 연결통로부(580)를 포함하고,제1온수관(700) 내측에 60~90℃의 항온수가 흐르는 것을 특징으로 하는 배기 장치 포깅 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

996/1059 Row 996: application_number: 1020200124639, combined_string: invention_title: 유해물질 및 해충과 스트레스 해소를 위한 동물전용 브러시 및 그 제조방법 abstract: 본 발명은 축사의 펜스나 벽면의 일측에 장착되어 소나 말 등의 가축의 몸을 비벼서 오염된 변 등의 유해물질 및 진드기 등의 해충을 긁어내거나 가려움 등의 스트레스를 해소할 수 있도록 한 동물전용 브러시 및 그 제조방법에 관한 것이다.즉, 본 발명은 축사에 설치되어 가축의 몸을 비벼댈 수 있는 브러시부를 구비한 브러시 몸체로 이루어지되 상기 브러시 몸체는; 반원형상으로 볼록하게 형성된 상,하부 지지판, 상기 상,하부 지지판의 양측에 각각 연결되고 일정 간격으로 상,하부 지지판이 서로 대응된 위치에 설치되도록 하는 수직 지지대, 상기 상,하부 지지판 및 양측 수직 지지대에 브러시부의 끝단부가 일체로 연결되되 전측에 금속망체로 구비되고 반원형상으로 볼록하게 형성된 브러시부, 상기 상,하부 지지판에 전측이 고정설치되고 후측은 축사의 펜스나 벽면에 장착시키는 장착대를 포함하는 유해물질 및 해충과 스트레스 해소를 위한 동물전용 브러시 및 그 제조방법을 특징으로 한다. claims: 축사에 설치되어 가축의 몸을 비벼댈 수 있는 브러시부(140)를 구비한 브러시 몸체(100)로 이루어지되 상기 브러시 몸체(100)는; 반원형상으로 볼록하게 형성된 상,하부 지지판(110)(120), 상기 상,하부 지지판(110)(120)의 양측에 각각 연결되고 일정 간격으로 상,하부 지지판(110)(120)이 서로 대응된 위치에 설치되도록 하는 수직 지지대(130), 상기 하부 지지판(120)은 수평면을 이루는 내측에 통공부(122)를 형성시켜 브러시부(140)에 의해 가축의 몸에서 탈락되는 각종 이물질이 브러시부(140) 및 하부 지지판(120)에 머무르지 않고 축사 바닥으로 떨어지도록 한 것을 포함하고,상기 상,하부 지지판(110)(120) 및 양측 수직 지지대(130)에 브러시부(140)의 끝단부가 일체로 연결되되 전측에 금속망체로 구비되고 반원형상으로 볼록하게 형성된 브러시부(140)로 이루어지되 상기 금속망체는 파형의 사각철선(142)을 다단으로 횡설하여 마름모 모형(144)으로 된 망사형으로 이루어지고, 상기 마름모 모형(144)은 사각철선(142)의 파형 상단(142a) 전측으로 또 다른 사각철선(142)의 파형 하단(142b)이 중첩되어 전측으로 돌출단부(146)가 형성되며,상기 상,하부 지지판(110)(120)에 전측이 고정설치되고 후측은 축사의 펜스나 벽면에 장착시키는 장착대(150)로 이루어진 것을 특징으로 하는 유해물질 및 해충과 스트레스 해소를 위한 동물전용 브러시.금속제로 된 동물 브러시를 제조하는 것에 있어서,금속판재를 프레스 가공하여서 된 상,하부 지지판(110)(120), 일정 길이의 봉체를 절단 가공하여서 된 수직 지지대(130). 사각철선을 레이저 가공, 용접 및 반원형상으로 만곡지게 절곡하여서 된 브러시부(140)는 전측에 금속망체로 구비되되 금속망체는 파형의 사각철선(142)을 다단으로 횡설하여 마름모 모형(144)으로 된 망사형으로 이루어지고, 상기 마름모 모형(144)은 사각철선(142)의 파형 상단(142a) 전측으로 또 다른 사각철선(142)의 파형 하단(142b)이 중첩되어 전측으로 돌출단부(146)가 형성된 브러시부(140)를 포함하며, 상기 구성요소들의 상,하부 지지판(110)(120) 및 양측 수직 지지대(130)에 브러시부(140)의 끝단부를 일체로 용접하여 전측에 금속망체로 구비되고 반원형상으로 볼록하게 형성된 브러시부를 갖도록 하는 제1구성부재를 구비하는 단계(S1); 금속판재를 프레스 가공 및 절곡하여서 된 장착대(150)로 이루어진 제2구성부재를 구비하는 단계(S2);상기 제1구성부재 및 제2구성부재를 각각 융용아연도금 처리하여 보호피막을 형성하는 단계(S3);상기 제1구성부재의 상,하부 지지판(110)(120)에 전측이 고정설치되고 제2구성부재의 장착대(150) 후측은 축사의 펜스나 벽면에 체결부재(160)로 장착시키는 조립 설치단계(S4);로 이루어진 것을 특징으로 하는 유해물질 및 해충과 스트레스 해소를 위한 동물전용 브러시의 제조방법., Ltext: 농업, prediction: 임업
997/1059 Row 997: application_number: 1020200111424, combined_string: invention_title: 천연광물 미네랄 이온 교환을 통한 성분 강화로 장내 유용미생물을 활성화하는 가축 음용수 제조방법 abstract: 이 발명은 물에 침출되어 있는 토르말린, 일라이트의 천연광물 미네랄 이온 간 교환을 하면서 법제유황과 옻, 그리고 목별자의 유익한 성분을 좀 더 쉽게 가축의 체내에 흡수되도록 강화시켜 가축의 장내 유용미생물이 자극되면서 활성화하는 환경을 조성하고 이를 지속적으로 유지하여 소화력과 면역력을 높이게, 물 90~95WT%에, 2~3㎛의 분말 형태인 천연 광물질들로서, 토르말린 2.5~5.0WT%와, 일라이트 2.5~5.0WT%를 혼합하여 상온에서 5~7시간 경과시킨 후 상기 토르말린과 일라이트 분말을 제거하여 침출액을 만드는 과정과 (S101); 상기 과정(S101)에서 만들어진 침출액 25~65WT%에, 2~3㎛의 분말 형태인 법제유황 15~25WT%와, 옻 추출액 10~25WT%, 그리고 목별자 원액 10~25WT%를 혼합하여 12시간 경과시킨 후 혼합액을 만드는 과정(S102); 및, 상기 과정(S102)에서 만들어진 혼합액 150~250㎖를, 물 20L에 혼합하여 6~7시간 증폭하는 과정(S103);으로 이루어진 것을 특징으로 하는 천연광물 미네랄 이온 교환을 통한 성분 강화로 장내 유용미생물을 활성화하는 가축 음용수 제조방법을 제공한다. claims: 물 90~95WT%에, 2~3㎛의 분말 형태인 천연 광물질들로서, 토르말린 2.5~5.0WT%와, 일라이트 2.5~5.0WT%를 혼합하여 상온에서 5~7시간 경과시킨 후 상기 토르말린과 일라이트 분말을 제거하여 침출액을 만드는 과정과 (S101);상기 과정(S101)에서 만들어진 침출액 25~65WT%에, 2~3㎛의 분말 형태인 법제유황 15~25WT%와, 옻 추출액 10~25WT%, 그리고 목별자 원액 10~25WT%를 혼합하여 12시간 경과 시킨 후 혼합액을 만드는 과정(S102); 및,상기 과정(S102)에서 만들어진 혼합액 150~250㎖를, 물 20L에 혼합하여 6~7시간 증폭하는 과정(S103);으로 이루어진 것을 특징으로 하는 천연광물 미네랄 이온 교환을 통한 성분 강화로 장내 유용미생물을 활성화하는 가축 음용수 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

998/1059 Row 998: application_number: 1020200070891, combined_string: invention_title: 양파 부산물을 유효성분으로 함유하는 산란계 사료 첨가제 및 이의 용도 abstract: 본 발명은 양파 부산물 추출물을 유효성분으로 함유하는 산란율 증가용 산란계 사료첨가제 및 사료 조성물에 관한 것으로, 본 발명의 사료첨가제를 산란계에 급여할 경우 산란율을 증가시켜 양계 농가 소득 증진에 기여할 수 있다. claims: 수정을 투입하여 예열한 건조기에 양파껍질, 양파뿌리 및 사차인치를 투입하여 건조한 양파 혼합 부산물에 물 및 층층나무 수액을 첨가하여 추출한 후 여과하고 감압 농축하여 제조된 양파 부산물 추출물을 유효성분으로 함유하는 산란율 증가용 산란계 사료첨가제.제1항 또는 제2항의 산란계 사료첨가제를 포함하는 산란율 증가용 산란계 사료 조성물.제3항의 산란율 증가용 산란계 사료 조성물을 산란계에 급여하여 산란계의 산란율을 증가시키는 방법.(단계 1) 수정 0.8~1.2 kg을 투입하여 예열한 건조기에 양파껍질 650~750 g, 양파뿌리 120~180 g 및 사차인치 120~180 g을 투입하여 45~55℃에서 1~3시간 동안 건조한 양파 혼합 부산물에 물 2.7~3.3 L 및 층층나무 수액 0.8~1.2 L를 첨가하여 45~55℃에서 4~6시간 동안 추출한 후 여과하고 감압 농축하여 산란계 사료첨가제를 제조하는 단계; 및(단계 2) 상기 (1)단계의 제조한 산란계 사료첨가제와 일반사료 4~6:94~96 중량비율로 혼합하여 산란계에 급여하는 단계를 포함하는 산란계 사육방법., Ltext: 농업, prediction: 임업
999/1059 Row 999: application_number: 1020200014107, combined_string: invention_title: 미생물을 이용한 축사 소독방법 abstract: 본 발명은 미생물을 이용한 축사 소독방법에 관한 것이다.본 발명에 따르면 미생물보관탱크 내부에 보관되는 EM 미생물과 음용수저장탱크의 음용수를 혼합액포집탱크 내부로 설정된 비율로 공급 혼합하고, 동절기에는 혼합액 온도(35℃)를 유지시키며, 미생물과 음용수의 혼합액을 혼합액펌핑수단으로서 펌핑하여 축사 내부로 설정된 시간동안 분사하여 냄새 및 분진 등을 제거한 다음, 음용수저장탱크 내부의 음용수를 음용수펌핑수단으로서 설정된 시간동안 펌핑하여 배출파이프, 공급라인 및 분사수단 내부에 잔류해 적정 온도에 의해 증식되어 배출파이프, 공급라인 및 분사수단을 막고 있는 EM 미생물을 세척 제거한 후, 에어발생기에서 발생되는 고압의 에어를 배출파이프, 공급라인 및 분사수단으로 공급하여, 상기 음용수청소공정 후 배출파이프, 공급라인 및 분사수단 내부에 남아 있는 수분과 미생물을 완전히 제거함으로서, 혼합액 분사작업을 지속적으로 진행할 수 있어 분사작업이 우수하고, 동절기에는 동파를 방지하는 효과가 제공된다. claims: 미생물보관탱크 내부에 보관되는 EM 미생물과 음용수저장탱크의 음용수를 미생물공급수단 및 음용수공급수단에 의해 설정된 비율을 유지하여 혼합액포집탱크 내부로 공급 혼합하기 위한 미생물과 음용수 혼합공정과; 상기 혼합액포집탱크의 미생물과 음용수의 혼합액을 혼합액펌핑수단으로서 펌핑하여 배출파이프, 공급라인 및 분사수단을 통해 축사 내부로 설정된 시간동안 분사하여 축사를 소독하기 위한 혼합액분사공정과; 상기 음용수저장탱크 내부의 음용수를 음용수펌핑수단으로서 펌핑하여 공급라인과 분사수단 내부에 잔류하여 온도에서 증식하는 EM 미생물의 특성으로 공급라인과 분사수단이 막히는 것을 차단하기 위한 음용수청소공정과; 에어발생기에서 발생되는 고압의 에어를 배출파이프, 공급라인 및 분사수단으로 공급하여 상기 음용수청소공정 후 배출파이프, 공급라인 및 분사수단에 남아 있는 미생물 및 수분을 완전히 제거하기 위한 에어청소공정으로 구성되는 미생물을 이용한 축사 소독방법에 있어서,상기 혼합액분사공정의 분사수단(80)은 상기 혼합액펌핑수단(70)의 공급라인(78)에 연통되게 형성되는 다수의 연결구(81)와; 상기 연결구(81)에 분리 가능하게 결합되고, 하부에 연통되게 돌출부(82)가 형성되며, 배출공(83a)이 관통 형성된 상부하우징(83)과, 상부하우징(83)의 일측에서 하방으로 연장되게 연결되는 굴곡연장편(84)과, 굴곡연장편(84) 하부에 상부하우징(83)의 돌출부(82) 하단과 일치되게 형성된 결합공(85a)을 갖는 하부받침대(85)로 이루어진 고정체(86)와;상기 하부받침대(85)의 결합공(85a)에 회전 가능하게 결합되는 회전핀(87)과, 회전핀(87)이 하단에 일체로 형성되고, 상부하우징(83)의 돌출부(82)에 회전 가능하게 결합되는 상부요홈(88a)에 형성되며, 상부요홈(88a)과 연통되게 혼합액이 축사(1)로 분사되는 경사비산공(88b)이 형성되는 경사몸체(88)로 이루어진 회전체(89)로 구성된 것을 특징으로 하는 미생물을 이용한 축사 소독방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1000/1059 Row 1000: application_number: 1020200000371, combined_string: invention_title: 유황오리 사육용 천연식물유황사료 제조방법 abstract: 본발명은 MSM(메틸설포닐메탄) 0.1 ~ 0.5wt%, 바실러스 서브틸러스 1.0 ~ 5.0wt%, 모나콜린-케이가 0.1wt% 이상이 함유되어 있는 홍국균 배양물 0.5 ~ 5.0wt% 및, 부형제인 효모 89.5 ~ 98.4wt% 을 함유하는 제1사료를 28~30℃ 회전조에서 20~30분 혼합하는 제 1사료 혼합공정;혼합된 제 1사료와 오리 일반사료를 1:9 비율로 30 ~ 40℃ 회전조에서 20~30분 뒤집으면서 혼합하며 혼합된 사료가 평균 29 ~ 30℃에 이르도록 하는 제 2사료 혼합공정; 및혼합된 제 2사료를 29 ~ 30℃ 항온조에서 5~6시간 숙성하는 숙성공정;을 수행하는 유황오리 사육용 천연식물유황사료 제조방법에 관한 것으로,본 발명에 따른 사료를 섭취한 오리는 일반사료를 섭취한 통상의 오리에 비해 근육내 황함유화합물의 함량이 증가되고, 콜레스테롤 합성 저해물질인 모나콜린-케이가 급이됨으로써 오리육에 콜레스테롤의 함량이 감소되며, 오리를 사육하는 동안 감염될 수 있는 바이러스에 저항력이 생겨 질병에 강해지므로 별도의 화학성분의 항생제를 투여할 필요가 없게 되고, 오리의 육질개선, 품질향상, 성장속도의 단축, 사료효율의 개선을 제공함으로써 경쟁력 있는 고급 오리제품을 생산하여 농어촌 소득은 물론 국민 보건 향상에 기여할 수 있다. claims: MSM(메틸설포닐메탄) 0.1 ~ 0.5wt%, 바실러스 서브틸러스 1.0 ~ 5.0wt%, 모나콜린-케이가 0.1wt% 이상이 함유되어 있는 홍국균 배양물 0.5 ~ 5.0wt% 및, 부형제인 효모 89.5 ~ 98.4wt% 을 함유하는 제1사료를 28~30℃ 회전조에서 20~30분 혼합하는 제 1사료 혼합공정;혼합된 제 1사료와 오리 일반사료를 1:9 비율로 30 ~ 40℃ 회전조에서 20~30분 뒤집으면서 혼합하며 혼합된 사료가 평균 29 ~ 30℃에 이르도록 하는 제 2사료 혼합공정; 및혼합된 제 2사료를 29 ~ 30℃ 항온조에서 5~6시간 숙성하는 숙성공정;을 수행하는 유황오리 사육용 천연식물유황사료 제조방법., Ltext: 농업, prediction: 임업
1001/1059 Row 1001: application_number: 1020190177320, combined_string: invention_title: 오골계 유래 탈미네랄화된 골분을 이용한 골이식재 및 이의 제조방법 abstract: 본 발명은 오골계 유래 탈미네랄화된 골분(demineralized bone particles ; DBP)을 이용한 골이식재 및 이의 제조방법에 관한 것으로서, 더욱 상세하게는 오골계 유래의 DBP와 골유도물질을 함침시켜 제작한 골 재생에 매우 효과적인 골대체재용 지지체 조성물과 이를 이용하여 제작된 골이식재에 관한 것이다. 이러한 본 발명에 따른 골이식재는 다른 가금류인 닭, 오리 유래의 DBP를 이용하여 제작한 골이식재와 비교하여 골 재생 효과가 월등하게 우수하다. claims: 오골계 유래 탈미네랄화된 골분(demineralized bone particles ; DBP)을 함유하는 골대체재용 지지체 조성물.오골계 유래 탈미네랄화된 골분(demineralized bone particles ; DBP)을 함유하는 골대체재용 지지체 조성물로 이루어지되 청구항 2 내지 청구항 4 중에서 어느 하나의 항에 따른 골대체재용 지지체 조성물로 이루어진 골이식재.(a) 오골계 유래 탈미네랄화된 골분(DBP)을 제조하는 단계; (b) 탈미네랄화된 골분을 이용하여 다공성 성형체로 지지체를 제조하는 단계; 및(c) 상기 지지체에 골유도물질로서 생리활성물질, 골형성 단백질, 세라믹성분 중에 하나이상의 골유도물질을 적용하는 단계 를 포함하는 골이식재의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1002/1059 Row 1002: application_number: 1020190165612, combined_string: invention_title: 들깨 부산물을 포함하는 오메가 3 지방산 함유 육계육용 사료첨가제 조성물 abstract: 본 발명은 육계육용 사료첨가제 조성물, 더욱 상세하게는 들깨 부산물을 포함하는 오메가 3 지방산 함유 육계육용 사료첨가제 조성물에 관한 것이다. 본 발명에 따른 들깨 부산물을 포함하는 육계육용 사료첨가제 조성물은 육계의 생산성 뿐만 아니라 육계육 내 오메가 3 지방산의 함량을 유의적으로 증가시킬 수 있다. claims: 들깨 부산물을 포함하는 오메가 3 지방산 함유 육계육용 사료첨가제 조성물., Ltext: 농업, prediction: 농업
1003/1059 Row 1003: application_number: 1020190158124, combined_string: invention_title: 닭사료 조성물 abstract: 본 발명은 면역성을 높일 수 있는 닭사료 조성물에 관한 것으로서, 분말화된 한약재박, 커피찌꺼기, 과일껍질, 버섯부산물, 목초액, 미강, 굴 껍질 및 혈분으로 이루어지는 베이스 분말과, 황칠나무잎 복합체 발효분말과 매실 분말을 포함한다. 이러한 닭사료 조성물에 따르면, 항생제를 사용하지 않고서도 질병에 대한 면역성을 높여 닭의 건강을 증진시킬 수 있고, 장기 보관을 가능하게 함과 동시에 보관 부피를 줄일 수 있다. claims: 분말화된 한약재박, 커피찌꺼기, 과일껍질, 버섯부산물, 목초액, 미강, 굴 껍질 및 혈분으로 이루어지는 베이스 분말과, 황칠나무잎 복합체 발효분말과 매실 분말을 포함하고;상기 베이스 분말은, 상기 한약재박 100 중량부를 기준으로 하여, 상기 커피찌꺼기 10 내지 20 중량부, 과일껍질 12 내지 17 중량부, 버섯부산물 6 내지 10 중량부, 목초액 0.1 내지 0.5 중량부, 미강 70 내지 120 중량부, 굴 껍질 10 내지 20 중량부, 혈분 3 내지 8 중량부를 포함하고;상기 황칠나무잎 복합체 발효분말은, 연잎 및 황칠나무잎을 1 : 2 중량비로 준비하고 물을 이용하여 깨끗하게 세척한 후 이물질을 제거하고, 이를 70℃에서 3시간 동안 건조한 다음 스팀기에 75℃에서 40분간 투입하여 스팀 히팅을 행하는 단계와; 상기 결과물을 25℃로 냉각시킨 다음, 235℃에서 15분 동안 열풍건조하고 나서 90℃에서 1시간 동안 제1열처리를 실시하는 단계와; 상기 제1열처리된 결과물을 120℃에서 45분 동안 제2열처리를 실시하는 단계와; 상기 제2열처리된 생성물 100 중량부에 설탕 3 중량부, 물 50 중량부를 차례로 부가하고 이를 6일 동안 발효 숙성하거나, 상기 제2열처리된 생성물 100 중량부에 설탕 3 중량부를 부가한 다음, 물 50 중량부 및 설탕 3 중량부를 추가로 부가하며 유산균을 접종하고 이를 온도 35℃, 상대습도 83% 의 조건에서 6일 동안 발효 숙성하는 단계;로 얻어진 것을 특징으로 하는 닭사료 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1004/1059 Row 1004: application_number: 1020190156257, combined_string: invention_title: 반려동물 사료공급장치 및 이를 이용한 반려동물 사료공급방법 abstract: 본 발명은 반려동물 사료공급장치 및 이를 이용한 사료공급방법에 관한 것이다.본 발명의 실시예에 따르면, 반려동물 사료공급장치에 있어서, 외형을 형성하는 하우징부; 상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및 상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함한다. claims: 반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하고,상기 사료공급 어셈블리는,상기 사료공급 어셈블리 몸체부의 하방에 배치되고, 상기 사료보관공간과 연통되며, 상기 정량공급모듈이 배치되는 정량공급모듈 수용부와,상기 정량공급모듈 수용부의 하측에 배치되며, 하방을 향하여 개구되는 상기 사료 공급홀이 형성되는 사료공급 어셈블리 커버브래킷을 더 포함하고,상기 커버브래킷은 상기 정량공급모듈 수용부에 대응되는 원형 플레이트로 형성되는 커버브래킷 몸체를 포함하며,상기 정량공급모듈 수용부의 내부에 배치되는 상기 정량공급모듈은, 상기 정량공급모듈 수용부의 중심축을 중심으로 회전되며, 상기 중심축을 따라서 형성되는 회전 샤프트부와, 상기 회전 샤프트부를 기준으로 방사형으로 배치되는 복수의 회전날개부를 포함하는 회전공급유닛을 포함하고,상기 사료 공급홀은 상기 중심축을 중심으로 하는 부채꼴 형상으로 형성되며,상기 정량공급모듈의 상기 회전공급유닛의 하면은 상기 커버브래킷 몸체의 상면과 마주보고,상기 정량공급모듈은, 상기 회전 샤프트부의 타측에 고정되는 보조날개부들을 포함하고 상기 회전공급유닛과 동시에 회전되는 사료혼합유닛과, 상기 회전공급유닛 및 상기 사료혼합유닛 사이에 배치되며 상기 정량공급모듈 수용부의 내부에 고정되고 상기 정량공급모듈 수용부의 상기 중심축에 대하여 직교하는 방향으로 길게 연장 형성되는 브러시 유닛을 더 포함하고,상기 브러시 유닛은 상기 정량공급모듈 수용부의 상기 중심축과 나란한 방향으로 형성되는 복수의 브래킷들을 포함하는 반려동물 사료공급장치.반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하고,상기 트레이유닛에 선택적으로 물을 공급하기 위한 물공급 어셈블리;를 더 포함하고,상기 물공급 어셈블리는 물 공급과 상기 사료공급 어셈블리의 사료 공급은 상호 간에 독립적으로 이루어지며,상기 물공급 어셈블리는,내부에 물이 수용되는 물수용 공간이 형성되는 물공급 어셈블리 본체와,상기 물공급 어셈블리의 하측에 배치되며 물을 상기 물수용 공간의 외부로부터 배출하기 위한 유로를 제공하는 파이프 유닛과,상기 파이프 유닛의 단부에 형성되며, 물이 상기 트레이 어셈블리 측으로 배출되는 배출유닛을 포함하며,상기 배출유닛은, 상기 파이프 유닛과 연통되며 하방을 향하여 개구되는 배출홀이 형성되는 배출유닛 몸체와, 상기 배출유닛 몸체의 하측에 상기 배출유닛 몸체에 대하여 회전 가능하게 설치되는 스프링클러 플레이트를 포함하고,상기 배출유닛 몸체의 상기 배출홀에서 배출되는 물은 상기 스프링클러 플레이트와 접촉된 다음 상기 트레이 어셈블리 측으로 공급되는 것을 특징으로 하는 반려동물 사료공급장치.반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하고,상기 트레이유닛에 선택적으로 물을 공급하기 위한 물공급 어셈블리;를 더 포함하고,상기 물공급 어셈블리는 물 공급과 상기 사료공급 어셈블리의 사료 공급은 상호 간에 독립적으로 이루어지며,상기 물공급 어셈블리는,내부에 물이 수용되는 물수용 공간이 형성되는 물공급 어셈블리 본체와,상기 물공급 어셈블리의 하측에 배치되며 물을 상기 물수용 공간의 외부로부터 배출하기 위한 유로를 제공하는 파이프 유닛과,상기 파이프 유닛의 단부에 형성되며, 물이 상기 트레이 어셈블리 측으로 배출되는 배출유닛을 포함하며,상기 배출유닛은, 상기 파이프 유닛에 대하여 회전 가능하게 연결되며 하방을 향하여 개구되는 복수의 배출홀이 형성되는 배출유닛 몸체와, 상기 배출유닛 몸체를 수직축을 중심으로 기설정된 각도만큼 왕복 회전시키는 회전구동부를 포함하는 것을 특징으로 하는 반려동물 사료공급장치.반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하고,상기 트레이 어셈블리의 상기 트레이유닛은 복수개로 형성되며, 상기 트레이유닛 중 어느 하나의 트레이 유닛이 상기 하우징부에 형성되는 배식홀을 통하여 상기 하우징부의 외부로 노출된 경우, 적어도 하나의 다른 트레이유닛은 상기 하우징부의 외부로 노출되지 않고,상기 트레이 어셈블리는,상기 복수의 트레이유닛들이 분리 가능하게 결합되며, 중앙에 트레이 어셈블리 회전축이 형성되는 원형의 트레이 어셈블리 몸체를 더 포함하고,상기 트레이 어셈블리는 상기 하우징부에 대하여 분리 가능하게 결합되며,상기 트레이 어셈블리 몸체의 트레이 어셈블리 회전축에 선택적으로 접속 가능한 트레이 어셈블리 구동부;를 더 포함하고,상기 트레이 어셈블리 구동부는, 상하 방향으로 이동 가능하며 상기 트레이 어셈블리 회전축과 선택적으로 결합되어 상기 트레이 어셈블리 몸체를 일방향 또는 타방향으로 회전시키는 구동유닛과, 일측이 상기 구동유닛과 연결되어 상기 구동유닛을 상하 방향으로 이동시키며 상기 하우징부의 외부로 노출된 핸들유닛을 포함하는 반려동물 사료공급장치.외형을 형성하는 하우징부; 상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되고, 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료가 상기 사료보관공간으로부터 배출되며, 상기 사료를 기설정된 양만큼 상기 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및 상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리를 포함하고, 상기 트레이유닛에 선택적으로 물을 공급하기 위한 물공급 어셈블리;를 더 포함하고, 상기 물공급 어셈블리는 물 공급과 상기 사료공급 어셈블리의 사료 공급은 상호 간에 독립적으로 이루어지며, 상기 트레이 어셈블리는 상하 방향으로 형성되는 트레이 어셈블리 회전축을 중심으로 회전되는 복수의 상기 트레이 유닛들을 포함하고, 배식홀을 통하여 하나의 상기 트레이 유닛이 하우징부의 외부로 노출되는 반려동물 사료공급장치를 이용한 반려동물 사료공급방법에 있어서,복수의 트레이유닛 어느 하나의 트레이유닛이 상기 사료공급 어셈블리의 하방에 배치되도록 상기 트레이 어셈블리를 회전시키는 제1 트레이 회전 단계;상기 사료공급 어셈블리의 하방에 배치되는 상기 트레이유닛에 기설정된 양의 사료를 공급하는 사료 분배 단계; 및상기 사료 공급이 완료된 상기 트레이유닛이 상기 하우징부에 형성된 배식홀을 통하여 외부로 노출되도록 상기 트레이 어셈블리를 회전시키는 제2 트레이 회전 단계;를 포함하고,상기 트레이 유닛에 기설정된 양의 물을 공급하는 물공급 단계; 및상기 트레이 유닛과 상기 사료와 상기 물이 공급된 상태에서, 기설정된 시간동안 상기 사료를 재수화(Rehydration) 시키는 사료 수화 단계;를 더 포함하고,상기 사료 분배 단계에서,상기 사료가 공급되는 상기 트레이 유닛(배식 트레이 유닛)은, 상기 배식홀을 통하여 상기 하우징부의 외부로 노출되는 다른 트레이 유닛(노출 트레이 유닛)과 상기 트레이 어셈블리 회전축을 기준으로 상기 다른 트레이 유닛(노출 트레이 유닛)과 대칭되는 또 다른 트레이 유닛(대칭 트레이 유닛) 사이에 배치되며,상기 제1 트레이 이동 단계에서,상기 트레이 유닛들은, 제1 회전 각도만큼 일 방향으로 회전되며,상기 제2 트레이 이동 단계에서,상기 트레이 유닛들은, 제2 회전 각도만큼 상기 일 방향과 반대되는 타 방향으로 회전되거나, 제3 회전 각도만큼 상기 일 방향으로 회전되며,상기 제2 회전 각도는 상기 제1 회전 각도보다 크고,상기 제1 회전 각도와 상기 제3 회전 각도의 합은 360도 보다 작은 것을 특징으로 하는 반려동물 사료공급방법., Ltext: 농업, prediction: 임업
1005/1059 Row 1005: application_number: 1020190155585, combined_string: invention_title: 락토케피아노파시엔스 케피아노파시엔스 DN1 균주를 포함하는 사료 첨가제 조성물 abstract: 본 발명은 락토바실러스 케피아노파시엔스(Lactobacillus kefiranofacience) DN1 (KCCM11869P) 또는 이의 배양액을 포함하는 사료 첨가제 조성물에 대한 것으로, 구체적으로 가금류 살모넬라 감염을 예방하고 감소시켜 사료 조성물로 이용할 수 있다. claims: 락토바실러스 케피아노파시엔스(Lactobacillus kefiranofacience) DN1 (KCCM11869P) 균주 또는 이의 배양액을 포함하는 사료 첨가제 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1006/1059 Row 1006: application_number: 1020190155573, combined_string: invention_title: 농장에 설치되는 AI 바이러스 살균 시스템 abstract: 본 발명은 농장에 설치되는 AI 바이러스 살균 시스템에 대한 것이다. 본 발명에 따른 농장에 설치되는 AI 바이러스 살균 시스템은 외부로부터 공기를 흡입하고, 흡입된 공기를 살균하여 농장 내부에 제공하는 제1 살균장치, 외부로부터 공기를 흡입하고, 흡입된 공기를 살균하여 농장 일측에 위치한 출입부스에 제공하는 제2 살균장치, 그리고 상기 제1 살균장치 및 제2 살균장치의 현재 공기흐름량 및 살균조사량을 산출하고, 산출된 현재 공기흐름량 및 현재 살균조사량과 필요 공기흐름량 및 필요 살균조사량을 비교하여 상기 제1 살균장치와 제2 살균장치에 설치된 팬의 속도 및 UV 조사량을 조절하는 제어장치를 포함한다. 이와 같이 본 발명에 따른 AI 바이러스 살균 시스템은 농장 내부와 출입부스를 분리하여 각각 살균된 공기를 제공하고, 농장내의 사육 환경에 따라 공기 흐름량 및 UV 조사량을 조절하여 항시 멸균된 상태를 유지할 수 있도록 함으로써, 사육되는 조류가 조류 독감 바이러스에 감염되는 것을 근본적으로 방지할 수 있다. claims: 농장에 설치되는 AI 바이러스 살균 시스템에 있어서, 외부로부터 공기를 흡입하고, 흡입된 공기를 살균하여 농장 내부에 제공하는 제1 살균장치, 외부로부터 공기를 흡입하고, 흡입된 공기를 살균하여 농장 일측에 위치한 출입부스에 제공하는 제2 살균장치, 그리고상기 제1 살균장치 및 제2 살균장치의 현재 공기흐름량 및 살균조사량을 산출하고, 산출된 현재 공기흐름량 및 현재 살균조사량과 필요 공기흐름량 및 필요 살균조사량을 비교하여 상기 제1 살균장치와 제2 살균장치에 설치된 팬의 속도 및 UV 조사량을 조절하는 제어장치를 포함하는 AI 바이러스 살균 시스템.제5항에 있어서, 상기 적정 공기 흐름량(γ _ Suitable)은,상기 농장 내부 또는 출입부스 내에 필요한 공기흐름량을 나타내며, 하기의 수학식을 통해 연산되는 AI 바이러스 살균 시스템;여기서, α는 살균 비례상수이고, X는 농장내부 또는 출입부스에서 측정된 상대습도이고, β는 상대습도에 대한 고정상수이고, 는 농장내부 또는 출입부스에서 필요로 하는 살균 조사량을 나타내며, V는 UV 살균 가능 체적을 나타낸다. 제6항에 있어서, 상기 제어부는, 상기 농장 내에서 산출된 적정 공기흐름량(γ _ Suitable)이 현재 공기흐름량(γ _ Current )보다 적으면 상기 제1 흡입부에 설치된 흡입팬의 속도를 감소시키고,상기 출입부스 내에서 산출된 적정 공기흐름량(γ _ Suitable)이 현재 공기흐름량(γ _ Current )보다 적으면 상기 제2 흡입부에 설치된 흡입팬의 속도를 감소시키는 AI 바이러스 살균 시스템.제5항에 있어서, 상기 필요 UV 조사량(Dose_Need)은, 상기 농장 내부에 필요한 UV 조사량을 나타내며, 하기의 수학식을 통해 연산되는 AI 바이러스 살균 시스템;여기서, α는 살균 비례상수이고, X는 농장내부에서 측정된 상대습도이고, β는 상대습도에 대한 고정상수이고, γ는 농장 내부의 공기 흐름량을 나타내며, V는 UV살균 가능 체적을 나타낸다. 제8항에 있어서, 상기 제어부는, 상기 산출된 필요 UV 조사량(Dose_Need)이 현재 UV 조사량(Dose_Current)보다 크면 UV 조사량을 증가시키되, 점등되는 UV LED의 수량의 개수를 증가시키거나 높은 전압을 출력하도록 제어하여 상기 UV 조사량을 증가시키는 AI 바이러스 살균 시스템., Ltext: 농업, prediction: 농업
1007/1059 Row 1007: application_number: 1020190153462, combined_string: invention_title: 진공식 사료 자동 공급장치 abstract: 본 발명은 진공식 사료 자동 공급장치에 관한 발명으로, 내부에 공간 부가 형성되며, 전면에 사료 공급 홀이 형성되며, 상부에 덮개가 개폐 가능하게 설치되는 사료 자동 공급장치 본체; 상기 공간 부 안에 설치되며, 내부에 사료를 저장하는 사료 저장 호퍼; 상기 사료 공급 홀을 선택적으로 개방시켜서 상기 사료 저장 호퍼의 사료를 애견에게 공급하는 사료 공급 유닛; 상기 공간 부 및 상기 사료 저장 호퍼의 내부공간을 진공상태로 유지하기 위한 하나 이상의 진공펌프; 상기 사료 저장 호퍼 내부에 배치되어, 상기 사료 저장 호퍼 내부 공간의 습도를 조절하는 습도조절부; 및 상기 진공펌프 및 상기 습도조절부를 제어하는 제어부를 포함할 수 있다. claims: 내부에 공간 부(11)가 형성되며, 전면에 사료 공급 홀(12)이 형성되며, 상부에 덮개(13)가 개폐 가능하게 설치되는 사료 자동 공급장치 본체(10);상기 공간 부(11) 안에 설치되며, 내부에 사료를 저장하는 사료 저장 호퍼(20); 상기 사료 공급 홀(12)을 선택적으로 개방시켜서 상기 사료 저장 호퍼(20)의 사료를 애견에게 공급하는 사료 공급 유닛(70);상기 공간 부(11) 및 상기 사료 저장 호퍼(20)의 내부공간을 진공상태로 유지하기 위한 하나 이상의 진공펌프(P1, P2); 상기 사료 저장 호퍼(20) 내부에 배치되어, 상기 사료 저장 호퍼(20) 내부 공간의 습도를 조절하는 습도조절부(28); 및상기 진공펌프 및 상기 습도조절부를 제어하는 제어부(C); 를 포함하는 진공식 사료 자동 공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1008/1059 Row 1008: application_number: 1020190151309, combined_string: invention_title: 흰점박이꽃무지 사육용 인공사료 조성물 abstract: 본 발명은 흰점박이꽃무지 사육용 인공사료 조성물에 관한 것으로서, 더욱 상세하게는 흰점박이꽃무지의 산란수, 산란기간 및 생존기간을 현저히 증가시킬 수 있는 인공사료 조성물에 관한 것이다. 본 발명에 따른 흰점박이꽃무지 사육을 위한 인공사료 조성물은 흰점박이꽃무지의 산란수, 산란기간 및 생존기간을 현저히 증가시키는 것을 확인하였다. 이는 본 발명에 따른 인공사료 조성물은 흰점박이꽃무지를 연중 대량 사육할 수 있음을 의미하는 바, 곤충 사육 분야, 나아가 제약 및 식품 분야에서 다양하게 활용될 수 있다. claims: 조성물 100중량부에 대하여,카세인 3 내지 15중량부를 포함하는, 흰점박이꽃무지 사육용 인공사료 조성물.혼합물 100중량부에 대해 아가 0.5 내지 3중량부 및 카세인 3 내지 15중량부를 첨가하여 혼합물을 제조하는 단계;를 포함하는, 흰점박이꽃무지 사육용 인공사료 제조방법.제1항 내지 제4항 중 어느 한 항에 따른 흰점박이꽃무지 사육용 인공사료 조성물을 흰점박이꽃무지에 급여하는 단계;를 포함하는 흰점박이꽃무지의 인공사육방법., Ltext: 농업, prediction: 임업
1009/1059 Row 1009: application_number: 1020190137777, combined_string: invention_title: 축산 악취 저감용 분말제 및 액상제 통합 분사장치 abstract: 본 발명의 축산 악취 저감용 분말제 및 액상제 통합 분사장치는, 축산 악취 저감용 분말제를 저장하기 위한 분말제 탱크; 상기 분말제 탱크에서 분말제가 출력되는 양을 조절하는 분말제 밸브; 축산 악취 저감용 액상제를 저장하기 위한 액상제 탱크; 상기 액상제 탱크에서 액상제가 출력되는 양을 조절하는 액상제 밸브; 사용자의 선택을 입력받는 설정부; 상기 설정부의 설정에 따라 상기 액상제 밸브 및 상기 분말제 밸브를 조절하여 상기 액상제 또는 분말제의 출력량을 조절하는 제어부를 포함한다. 본 발명에서는 중앙의 구멍 이외에 3단계의 반경으로 구분되며 반경의 크기와 구멍의 모양 및 요철형태가 변형 조절되는 테두리 구멍이 있어서 물 또는 액상제나 분말제의 독립적인 분사기능 이외에 분사각도 및 분사거리의 조절과 습윤도 조절이 가능하다. claims: 축산 악취 저감용 분말제를 저장하기 위한 분말제 탱크;상기 분말제 탱크에서 분말제가 출력되는 양을 조절하는 분말제 밸브;축산 악취 저감용 액상제를 저장하기 위한 액상제 탱크;상기 액상제 탱크에서 액상제가 출력되는 양을 조절하는 액상제 밸브;사용자의 선택을 입력받는 설정부;상기 설정부의 설정에 따라 상기 액상제 밸브 및 상기 분말제 밸브를 조절하여 상기 액상제 또는 분말제의 출력량을 조절하는 제어부를 포함하는 축산 악취 저감용 분말제 및 액상제 통합 분사장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1010/1059 Row 1010: application_number: 1020190135846, combined_string: invention_title: 미생물 기반의 사료용 생균제 abstract: 본 발명은 미생물 기반의 사료용 생균제에 관한 것으로, 유익한 미생물들을 함유하여, 가축 및 어류의 증체율 및 면역력을 향상시켜, 사료 효율을 높일 수 있으며, 가축 및 어류의 생산성과 육질의 개선 효과를 나타낼 수 있는 미생물 기반의 사료용 생균제를 제공할 수 있다. claims: 홍국균(Monascus purpureus) 분말을 포함하고; 상기 홍국균 분말 100 중량부에 대하여 광합성 세균 분말 30 내지 50 중량부; 황국균 분말 30 내지 50 중량부 및 효모 분말 30 내지 50 중량부를 포함하는 혼합 미생물,상기 혼합미생물 100 중량부에 대하여, 왕겨 10 내지 20 중량부; 쌀겨 10 내지 20 중량부; 귤착즙 10 내지 20 중량부; 귤박 10 내지 20 중량부; 돌가사리 분말 5 내지 10 중량부 및 흑돌잎 분말 5 내지 10 중량부를 포함하는 미생물 기반의 사료용 생균제. 제 1항에 따른 미생물 기반의 사료용 생균제를 포함하는사료 조성물., Ltext: 농업, prediction: 임업
1011/1059 Row 1011: application_number: 1020190131290, combined_string: invention_title: 오존 및 OH 라디칼을 이용한 축사용 공기정화 시스템 abstract: 본 발명은 오존 및 OH 라디칼(하이드록시 라디칼)을 이용해 축사와 같은 악취 발생원으로부터 배출되는 공기의 탈취 및 살균을 실시할 수 있는 오존 및 OH 라디칼을 이용한 축사용 공기정화 시스템에 관한 것이다. 본 발명에 따른 오존 및 OH 라디칼을 이용한 축사용 공기정화 시스템은 오염원의 실내 공기를 실외로 배출시키는 배기부와, 상기 배기부를 통해 배출되는 공기가 정화되는 처리공간을 제공하도록 상기 오염원의 외측에 형성되는 공기처리부와, 상기 공기처리부 내에 설치되며, 상기 공기처리부 내의 공간을 상기 배기부의 배출구가 위치하는 제1 처리공간과, 상기 공기처리부의 내주면에 접하는 제2 처리공간으로 구획하며, 상기 제1 처리공간으로부터 제2 처리공간으로 공기가 이동할 수 있는 소정 직경의 통과홀들이 형성된 구획부와, 상기 제2 처리공간으로부터 공기를 상기 공기처리부의 외부로 토출시키도록 형성되는 공기토출부와, 상기 공기처리부 내에 설치되며 오존을 발생시키는 제1 오존발생유닛과, 상기 공기토출부와 연결되도록 상기 공기처리부의 외부에 설치되며, 상기 공기토출부를 통해 토출되는 공기가 통과할 수 있는 토출통로를 구비하고 상기 토출통로 내에 오존을 발생시킬 수 있도록 된 제2 오존발생유닛을 포함한다. claims: 오염원의 실내 공기를 실외로 배출시키는 배기부와;상기 배기부를 통해 배출되는 공기가 정화되는 처리공간을 제공하도록 상기 오염원의 외측에 형성되는 공기처리부와;상기 공기처리부 내에 설치되며, 상기 공기처리부 내의 공간을 상기 배기부의 배출구가 위치하는 제1 처리공간과, 상기 공기처리부의 내주면에 접하는 제2 처리공간으로 구획하며, 상기 제1 처리공간으로부터 제2 처리공간으로 공기가 이동할 수 있는 소정 직경의 통과홀들이 형성된 구획부와;상기 제2 처리공간으로부터 공기를 상기 공기처리부의 외부로 토출시키도록 형성되는 공기토출부와;상기 공기처리부 내에 설치되며 오존을 발생시키는 제1 오존발생유닛과;상기 공기토출부와 연결되도록 상기 공기처리부의 외부에 설치되며, 상기 공기토출부를 통해 토출되는 공기가 통과할 수 있는 토출통로를 구비하고 상기 토출통로 내에 오존을 발생시킬 수 있도록 된 제2 오존발생유닛을 포함하는오존 및 OH 라디칼을 이용한 축사용 공기정화 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1012/1059 Row 1012: application_number: 1020190127960, combined_string: invention_title: 냄새 제거 및 신선도 유지 플라즈마 장치 abstract: 본 발명은 상압 플라즈마를 발생시켜 축사의 악취를 제거하고 살균하여 식품의 신선도를 유지하는 냄새 제거 및 신선도 유지 플라즈마 장치에 관한 것으로서, 본 발명에 따른 냄새 제거 및 신선도 유지 플라즈마 장치는, 골격을 형성하는 프레임; 상기 프레임의 내부 전단에 설치되며, 상기 프레임 내부로 외부 공기를 유입시키는 송풍팬; 상기 프레임의 내부 후단에 설치되며, 상기 송풍팬에 의하여 이동하는 공기에 플라즈마 처리를 수행하는 플라즈마 처리부; 상기 프레임의 외면에 부착되어 설치되며, 상기 송풍팬의 유입구 및 상기 플라즈마 처리부의 유출구를 제외한 영역을 외부와 차단하는 차단판;을 포함한다. claims: 골격을 형성하는 프레임;상기 프레임의 내부 전단에 설치되며, 상기 프레임 내부로 외부 공기를 유입시키는 송풍팬;상기 프레임의 내부 후단에 설치되며, 상기 송풍팬에 의하여 이동하는 공기에 플라즈마 처리를 수행하는 플라즈마 처리부;상기 프레임의 외면에 부착되어 설치되며, 상기 송풍팬의 유입구 및 상기 플라즈마 처리부의 유출구를 제외한 영역을 외부와 차단하는 차단판;을 포함하는 냄새 제거 및 신선도 유지 플라즈마 처리장치. 제1항 내지 제8항 중 어느 한 항에 기재된 냄새 제거 및 신선도 유지 플라즈마 처리장치를 콘테이너에 설치하여 이루어지는 신선도 유지 콘테이너., Ltext: 농업, prediction: 임업
1013/1059 Row 1013: application_number: 1020190118366, combined_string: invention_title: 구기자를 이용한 고품질 가금류의 사육방법 abstract: 본 발명은 구기자를 이용한 고품질 가금류의 사육방법에 관한것으로, (a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 일반 가금류 급여용 사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 0.5kg~10kg을 혼합하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가금류 출하전 30일~90일간 급여하여 사육하는 단계; (j) 상기(i)단계의 사육과정을 통하여 사육된 가금류를 출하하여 제품화하는 단계를 포함하여 이루어진다. claims: (a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 일반 가금류 급여용 사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 0.5kg~10kg을 혼합하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가금류 출하전 30일~90일간 급여하여 사육하는 단계; (j) 상기(i)단계의 사육과정을 통하여 사육된 가금류를 출하하여 제품화하는 단계를 포함하는 것을 특징으로 하는 구기자를 이용한 고품질 가금류의 사육방법.제1항의 사육방법에 의하여 생산된 가금육., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1014/1059 Row 1014: application_number: 1020217008926, combined_string: invention_title: 사료 첨가제 abstract: 본 발명은 감초 추출물을 포함하는, 과잉 배란 처리 후에 얻어진 배의 품질을 개선하기 위한 포유 동물의 사료 첨가제, 및 과잉 배란 처리된 포유 동물을, 감초 추출물을 첨가한 사료를 사용해서 사육하는 것을 포함하는, 과잉 배란 처리 후에 얻어진 배의 품질을 개선하기 위한 방법에 관한 것이다. claims: 감초 추출물을 포함하는, 과잉 배란 처리 후에 얻어진 배의 품질을 개선하기 위한, 포유 동물의 사료 첨가제.과잉 배란 처리된 포유 동물을, 감초 추출물을 첨가한 사료를 사용해서 사육하는 것을 포함하는, 과잉 배란 처리 후에 얻어진 배의 품질을 개선하기 위한 방법., Ltext: 농업, prediction: 임업
1015/1059 Row 1015: application_number: 1020190108319, combined_string: invention_title: 폐각 및 질석을 이용한 악취제거용 액상사료첨가제 및 그 제조방법 abstract: 본 발명은 폐각 및 질석을 이용한 악취제거용 액상사료첨가제의 제조방법에 관한 것으로, 상기 악취제거용 액상 사료 첨가제는 분뇨질소 함량이 80% 정도 저감되어, 가축의 분뇨 및 분변의 악취제거를 위한 소, 돼지, 닭 등의 가축 사료 첨가제로서 유용하게 사용될 수 있다. claims: 폐각을 소성하는 소성단계;상기 소성된 폐각을 분쇄하는 분쇄단계;상기 폐각 분쇄물에 물을 첨가하고 교반하는 제1교반단계;상기 제1교반된 혼합물을 상온으로 냉각시키는 냉각단계;상기 냉각된 혼합물에 질석, 힐라이트, 생광석 및 황산을 첨가하고 교반하는 제2교반단계;상기 제2교반된 혼합물을 상온으로 유지하면서 휠타프레스를 이용하여 액상과 슬러지를 분리하는 분리단계; 및상기 액상을 숙성 및 안정시키는 숙성단계를 포함하여 이루어지는 것을 특징으로 하는 폐각 및 질석을 이용한 악취제거용 액상사료첨가제의 제조방법.청구항 1 내지 청구항 4 중에서 어느 하나의 항의 제조방법에 따라 제조된 폐각 및 질석을 이용한 악취제거용 액상사료첨가제., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1016/1059 Row 1016: application_number: 1020190103134, combined_string: invention_title: 유해공기 살균 및 탈취장치 abstract: 본 발명은 공기 중에 존재하는 각종 유해가스 제거 및 탈취가 효율적으로 이루어져 대기환경을 쾌적하게 조성함은 물론, 가축이 생활하는 각종 축사의 공기 중에 존재하는 유해가스 제거 및 탈취로 인하여 가축의 생활환경을 쾌적하게 조성할 수 있도록 한 유해공기 살균 및 탈취장치에 관한 것으로, 그 구성은, 내부가 중공인 본체; 상기 박스의 내측 배출구의 전방에 설치된 유해공기흡입수단; 상기 필터의 후방과 상기 유해공기흡입수단의 전방 사이에 설치되는 유해공기정화수단; 상기 복수의 공기유도편 전방과 후방을 고정 설치되는 유도 편 고정수단; 상기 각 공기유도로에 설치되는 살균램프; 로 이루어진다. claims: 내부가 중공인 박스(110)의 일 측벽(140)에 유해공기를 흡입하는 흡입구(120)가 형성되고, 그 흡입구에는 필터(130)가 설치되며, 상기 흡입구의 상호 마주보는 상기 박스의 타 측벽(150)에는 정화된 공기를 배출하는 배기구(160)를 형성시켜 된 본체(100);상기 박스의 내측 배기구의 전방에 설치되어 상기 흡입구로 유해공기가 흡입돼 들어오도록 흡입력을 발생시키는 유해공기흡입수단(200);상기 필터의 후방과 상기 유해공기흡입수단의 전방 사이에 설치되어 필터를 통과한 유해공기가 복수의 영역으로 분할 진행하며 살균 및 탈취가 이루어지도록 광촉매재인 이산화티타늄(TiO2)이 코팅된  형상을 갖는 복수 개의 공기유도편(310)을 일정간격으로 설치하여 복수의 공기유도로(320)를 형성시키되, 그 각 공기유도로(320)는, 상기  형상을 갖는 복수 개의 공기유도편으로 인해 흡입구 쪽의 폭이 배기구 쪽의 폭보다 넓고, 상기 각 공기유도로의 중앙부는, 흡입구 쪽의 폭보다는 좁고, 배기구 쪽의 폭보다는 넓게 형성시켜 된 유해공기정화수단(300);상기 복수의 공기유도편 전방과 후방을 고정 설치하도록 박스의 내측 전방과 후방에 각각의 전방고정수단(410)과 후방고정수단(420)을 설치하되,상기 전방고정수단(410)은, 중앙에 유해공기의 진행을 차단하는 전방공기차단블록(411)이 상기 박스의 높이와 준하는 높이로 설치되고, 상기 전방공기차단블록의 양측으로는 전방유해공기유입로(412)가 각각 형성되며, 그 전방유해공기유입로에는 공기유도편의 위치이동 및 유동을 방지하는 전방고정바(413)가 설치되고,상기 후방고정수단(420)은, 좌우 양측에 유해공기의 진행을 차단하는 후방공기차단블록(421)이 상기 박스의 높이와 준하는 높이로 설치되고, 상기 후방공기차단블록의 사이에는 후방유해공기유입로(422)가 각각 형성되며, 그 후방유해공기유입로에는 공기유도편의 위치이동 및 유동을 방지하는 후방고정바(423)를 설치하여 된 유도 편 고정수단(400);상기 각 공기유도로의 최전방과 최후방에는 365 나노메타 이상의 빛 파장을 갖는 LED 살균램프가 설치되고, 중앙부에는 275 나노메타 이상의 빛 파장을 갖는 LED 살균램프를 설치하여 된 살균램프(500); 로 구성된 것을 특징으로 하는 유해공기 살균 및 탈취장치., Ltext: 농업, prediction: 임업
1017/1059 Row 1017: application_number: 1020190101599, combined_string: invention_title: 아마씨와 락토바실러스 플란타럼 LP 유산균 생균제를 함유하는 산란계용 사료 첨가제 및 그 제조방법 abstract: 본 발명은 아마씨와 부형제 탄산칼슘으로 구성된 아마씨와 다가불포화지방산을 유산균 내 CLA 합성 관련 효소 유전자를 발현하는 Lactobacillus plantarum(LP WT177(KCTC18774P) 균주가 포함된 산란계용 사료첨가제를 개시하고 상기 사료첨가제를 산란계에 급여하여 계란 내 오메가-6/오메가-3의 함유 비율개선, CLA 함유량 증진 및 산란계의 염증 및 스트레스를 개선시키는 뛰어난 효과가 있으므로 건강 기능성 계란 및 밀식 사육하는 산란계 환경 개선에 매우 유용한 발명이다. claims: 염기서열목록 1로 표시되는 CLA 합성효소 생산용 유산균주 LP WT177(KCTC18774P) 제 1항의 유산균주 Lactobacillus plantarum LP 177, 아마씨 및 탄산칼슘으로 이루어진 산란계용 사료 첨가제제2항에 있어서, 산란계용 사료 첨가제는 전체 중량에 대하여 아마씨 1.8중량%, 유산균 생균제 1.0중량%로 이루어진 산란계용 사료 조성물제3항의 사료를 산란계에 120g/1두씩 급여하여 염증과 스트레스 관련 지표를 감소시키고 산란 성적은 증대시키는 특징인 밀식 사육 산란계의 사육방법제4항의 방법으로 사육되어 계란내 오메가-6/오메가3 함유비율이 균형있게 개선된 것이 특징인 계란, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1018/1059 Row 1018: application_number: 1020190100340, combined_string: invention_title: 가금류 사육장에서의 진드기류 퇴치제 및 이를 이용한 퇴치방법 abstract: 본 발명은 소금을 유효성분으로 함유하는 진드기류 퇴치용 조성물로써, 신속하면서도 높은 효율로 간단하게 가금류의 양식장의 사육과정에서 문제가 되는 진드기류를 퇴치할 수 있어 살충제 성분이 함유되지 않는 친환경 알을 생산할 수 있도록 해주는 진드기류 퇴치제 및 이를 이용한 퇴치방법을 제공한다. claims: 소금을 유효성분으로 함유하는 액상의 가금류 사육장용 와구모 퇴치제.제 1항의 와구모 퇴치제를 가금류에 분사하여 기생하는 와구모를 퇴치하는 것을 특징으로 하는 가금류의 와구모 퇴치방법., Ltext: 농업, prediction: 임업
1019/1059 Row 1019: application_number: 1020190099652, combined_string: invention_title: 공기중의 악취탈취 시스템 abstract: 본 발명은 공기중의 악취탈취 시스템에 관한 것으로서, 악취성분 함유 공기가 유입되는 유입구(11a)가 형성된 하우징(11), 하우징(11) 내측으로 물을 분무하는 분무노즐(12), 분무되는 물에 의하여 악취성분이 제거된 공기를 외기로 배기하는 배기관(13) 및 악취성분이 흡착된 분무된 물이 집수되는 호퍼(14)를 가지는 탈취배기탱크(10)와; 호퍼(14)와 연결된 관로를 통하여 배출되는 악취성분 함유 물을 집수하여 저장하기 위한 것으로서, 외부 환경 변화에도 온도 변화를 최소화할 수 있도록 지중(G)에 매설되는 집수탱크(20)와; 집수탱크(20)에 저장된 물에 함유된 악취성분을 제거하여 정화수로 정화시키기 위한 산기장치(30)와; 집수탱크(20)와 분무노즐(12)을 연결하는 정화수공급라인(40)에 설치되어 집수탱크(20)에 저장된 정화수를 분무노즐(12)로 압송하는 압송펌프(50)와; 압송펌프(50)와 탈취배기탱크(10) 사이의 정화수공급라인(40)과 상기 산기장치(30)와 연결되는 것으로서, 압송펌프(50)에 의하여 압송되는 정화수 일부를 상기 산기장치(30)로 공급하는 선회라인(60);을 포함하는 것을 특징으로 한다. claims: 악취성분 함유 공기가 유입되는 유입구(11a)가 형성된 하우징(11)과, 상기 하우징(11) 내측으로 물을 분무하는 분무노즐(12)과, 분무되는 물에 의하여 악취성분이 제거된 공기를 외기로 배기하는 배기관(13)과, 상기 악취성분이 흡착된 분무된 물이 집수되는 호퍼(14)를 가지는 탈취배기탱크(10);상기 호퍼(14)와 연결된 관로를 통하여 배출되는 악취성분 함유 물을 집수하여 저장하기 위한 것으로서, 외부 환경 변화에도 온도 변화를 최소화할 수 있도록 지중(G)에 매설되는 집수탱크(20);상기 집수탱크(20)에 저장된 물에 함유된 악취성분을 제거하여 정화수로 정화시키기 위한 산기장치(30);상기 집수탱크(20)와 분무노즐(12)을 연결하는 정화수공급라인(40)에 설치되어 상기 집수탱크(20)에 저장된 정화수를 상기 분무노즐(12)로 압송하는 압송펌프(50); 및상기 압송펌프(50)와 탈취배기탱크(10) 사이의 상기 정화수공급라인(40)과 상기 산기장치(30)와 연결되는 것으로서, 상기 압송펌프(50)에 의하여 압송되는 정화수 일부를 상기 산기장치(30)로 공급하는 선회라인(60);을 포함하는 것을 특징으로 하는 공기중의 악취탈취 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1020/1059 Row 1020: application_number: 1020190096544, combined_string: invention_title: 동물용 사료 조성물 abstract: 본 발명은, 물 150g에 대하여 백렴 8g, 고백반 0.6g, 백지 8g, 붕사 1g, 백선피 9g, 용뇌 0.7g, 율초 15g, 편백나무 6g, 케나프 20g 비율로 투입하여 5시간 내지 7시간 110℃에서 끓인 후 약 35~45℃에서 7~8시간 숙성시킨 후 냉각하여 제조되는 제1 첨가물을 포함하는 것을 특징으로 한다.이에, 친환경적이고 천연 재료를 사용하여 동물의 사료를 제조하며 발병율 및 동물분의 냄새를 감소시킬 수 있고, 사료 섭취량을 증대시킬 수 있고, 털이 빠지지 않는 동물용 사료 조성물을 제공할 수 있다. claims: 동물용 사료 조성물에 있어서,물 150g에 대하여 백렴 8g, 고백반 0.6g, 백지 8g, 붕사 1g, 백선피 9g, 용뇌 0.7g, 율초 15g, 편백나무 6g, 케나프 20g 비율로 투입하여 5시간 내지 7시간 110℃에서 끓인 후 약 35~45℃에서 7~8시간 숙성시킨 후 냉각하여 제조되는 제1 첨가물을 포함하는 것을 특징으로 하는 동물용 사료 조성물.동물용 사료 조성물에 있어서,물 100g에 대하여 어성초 15g, 꾸지뽕 5g, 비파엽 9g, 땅콩새싹 12g 비율로 투입하여 5시간 내지 7시간 110℃에서 끓인 후 약 35~45℃에서 7~8시간 숙성시킨 후 냉각하여 제조되는 제2 첨가물을 포함하는 것을 특징으로 하는 동물용 사료 조성물., Ltext: 농업, prediction: 임업
1021/1059 Row 1021: application_number: 1020190088944, combined_string: invention_title: 악취제거제 제조 방법 abstract: 본 발명은 악취제거제를 제조하는 방법에 관한 것으로, 보다 상사하게는 악취의 원인 물질을 근본적으로 분해하여 강력한 탈취 기능을 제공하고, 사용이 간단하며, 적은 사용량에서도 탈취 효율이 높은 악취제거제 제조 방법에 관한 것이다.이러한 본 발명은, 물을 90℃ 이상의 온도로 소정 시간 동안 가열하는 살균 단계, 그리고 광합성균 배양액과, 맥주효모, 옥수수전분, 포도당 및 유황을 포함하는 배양 첨가제를 살균된 물에 혼합하여 제1시간 동안 배양하는 광합성균 배양 단계, 그리고 고초균 배양액과, 상기 배양 첨가제를 살균된 물에 혼합하여 제2시간 동안 배양하는 고초균 배양 단계, 그리고 효모균 배양액과, 상기 배양 첨가제를 살균된 물에 혼합하여 제3시간 동안 배양하는 효모균 배양 단계, 그리고 살균된 물에 배양이 완료된 광합성균 배양액, 고초균 배양액, 효모균 배양액 및 혼합 첨가제를 혼합하여 제4시간동안 배양하는 혼합 배양 단계를 포함한다. claims: 물을 90℃ 이상의 온도로 소정 시간 동안 가열하는 살균 단계; 광합성균 배양액과, 맥주효모, 옥수수전분, 포도당 및 유황을 포함하는 배양 첨가제를 살균된 물에 혼합하여 제1시간 동안 배양하는 광합성균 배양 단계; 고초균 배양액과, 상기 배양 첨가제를 살균된 물에 혼합하여 제2시간 동안 배양하는 고초균 배양 단계; 효모균 배양액과, 상기 배양 첨가제를 살균된 물에 혼합하여 제3시간 동안 배양하는 효모균 배양 단계; 및 살균된 물에 배양이 완료된 광합성균 배양액, 고초균 배양액, 효모균 배양액 및 혼합 첨가제를 혼합하여 제4시간동안 배양하는 혼합 배양 단계;를 포함하고, 상기 혼합 배양 단계는 내부에 수용공간을 구비한 교반조 및 상기 교반조의 상부에 구비되고 상기 수용공간 측으로 돌출 구비되며 회전하는 혼합봉을 구비한 믹서를 포함하는 교반기를 통해 수행되고, 상기 교반조는 외면에 구비되는 보호막을 포함하되, 상기 보호막은 상기 교반조의 외면에 접하는 침투층, 상기 침투층의 상부에 구비된 발열층 및 상기 발열층의 상부에 구비된 보호층을 포함하고, 상기 침투층은 폴리에틸렌 100 중량부 대비, 폴리비닐 아세테이트계 저수축제 20 중량부 및 수소첨가 로젠이스테르 수지와 폴리브텐을 포함하는 점착제 50 중량부를 포함하고, 상기 발열층은 이산화루테늄 100 중량부 대비, 은 200 중량부 및 이산화티타늄과 이규화몰리브덴을 포함하는 기능성 결착제 200 중량부를 포함하고, 상기 보호층은 부틸 합성고무 100 중량부 대비, 탄산칼슘과 벤토나이트를 포함하는 충진제 300 중량부, 나프텐 오일 100중량부 및 바륨알루미네이트와 지르코니아를 포함하는 내열제 50 중량부를 포함하는 것을 특징으로 하는 악취제거제 제조 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1022/1059 Row 1022: application_number: 1020190082745, combined_string: invention_title: 가금류 사육장에서의 진드기류 퇴치제 및 이를 이용한 퇴치방법 abstract: 본 발명은 소금 및 식초를 유효성분으로 함유하는 진드기류 퇴치용 조성물로써, 신속하면서도 높은 효율로 간단하게 가금류의 양식장의 사육과정에서 문제가 되는 진드기류를 퇴치할 수 있어 살충제 성분이 함유되지 않는 친환경 알을 생산할 수 있도록 해주는 진드기류 퇴치제 및 이를 이용한 퇴치방법을 제공한다. claims: 소금 및 식초를 유효성분으로 함유하되, 스프레이 제형으로소금의 농도는 1~50 %(w/w)이고, 식초는 총산도 1~10%인 현미식초로 1~50 %(w/w) 첨가된 것을 특징으로 하는 액상의 가금류 사육장용 진드기류 살충제.제 1항의 진드기류 살충제를 가금류에 분사하여 기생하는 진드기류를 살충하는 것을 특징으로 하는 가금류의 진드기류 살충방법.제 4항의 방법에 의해 생산된 것을 특징으로 하는 가금류의 알., Ltext: 농업, prediction: 임업
1023/1059 Row 1023: application_number: 1020190072885, combined_string: invention_title: 가금류의 생산성 개선을 위한 사료 조성물 abstract: 본 발명은, 가금류 생산성 향상을 위한 동물사료에 관한 것이다. claims: 쑥 추출물을 여과 농축하는 공정을 포함하여 얻은 연조엑스, 그리고 소맥말분 및 탄산칼슘을 혼합한 쑥추출물 혼합물과 동물사료를 혼합하여 제조하는 것으로서,상기 쑥 추출물은 1-프로판올 또는 2-프로판올을 쑥 중량 대비 10배 이상 첨가하여 추출 후, 잔류물에 추가로 1-프로판올 또는 2-프로판올을 가하여 재추출하는 단계; 및상기 재추출하여 얻어진 추출액을 여과하여 감압농축하여 연조엑스 형태의 쑥 추출물을 제조하는 단계에 의해 제조된 것이고,상기 제조된 쑥 추출물에는 유파틸린 0.8~2.4 중량% 및 자세오시딘 0.25~0.75 중량%를 포함하는 것이며,상기 동물사료는 옥수수 (Yellow corn), 소맥(Wheat), 대두박 (Soybean meal), 옥수수글루텐박 (Corn gluten meal), 우지 (Tallow), 리신염산염(LysineHCl), 제2인산칼슘 (Dicalcium phosphate), DL-메티오닌 (DL-methionine), 석회석 (Limestone), 염화콜린 (Choline chloride), 소금 (Salt), 비타민 혼합물 (Vit. mixture) 및 미네랄 혼합물 (Min. mixture)를 포함하는 것을 특징으로 하는 사료조성물의 제조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1024/1059 Row 1024: application_number: 1020190069531, combined_string: invention_title: 반려동물의 습식사료 조성물의 습식사료 제조 장치 및 방법 abstract: 반려동물의 습식사료 조성물, 습식사료 제조 장치 및 방법은 반려동물의 관절 질환, 피부 질환, 장 질환에 따라 질환별로 정해진 원료를 서로 다른 배합 비율로 배합하여 반려동물에 최적화된 맞춤형 습식사료를 제조할 수 있다.본 발명은 반려동물의 관절 질환, 피부 질환, 장 질환별로 맞춤형 사료를 제조하여 반려동물의 섭취가 용이하고, 이에 따라 반려동물의 소화 흡수율과 면역력 증진, 관절 건강, 피부 건강 관리를 동물 유기를 사전에 예방할 수 있는 효과가 있다. claims: 반려동물의 관절 질환, 피부 질환, 장 질환에 따라 질환별로 곡물, 육고기, 어류, 가시오가피, 홍삼, 채소, 고구마, 호박, 양배추 중 하나 이상의 정해진 원료를 서로 다른 배합 비율로 배합하는 단계;상기 교반된 재료를 170 내지 190℃의 온도에서 35 내지 5 ㎏/㎠ 의 스팀 압력하에 30 내지 50분 동안 스팀 가열하는 단계;상기 가열된 재료들을 스팀으로 익힌 후, 스팀 가열에 의해 점성이 있는 상태로 뭉쳐진 재료를 원형바의 형상으로 길게 뽑아내는 형상을 성형하는 단계; 및상기 원형바 형상으로 성형된 재료를 건조기에 삽입하여 수분 함량이 10% 이하가 되도록 저온 건조하거나 동결 건조하는 단계를 포함하는 것을 특징으로 하는 반려동물의 습식사료 제조 방법.반려동물의 관절 질환, 피부 질환, 장 질환에 따라 질환별로 곡물, 육고기, 어류, 가시오가피, 홍삼, 채소, 고구마, 호박, 양배추 중 하나 이상의 정해진 원료를 서로 다른 배합 비율로 배합하는 재료 배합부;상기 재료 배합부에서 교반된 재료를 170 내지 190℃의 온도에서 35 내지 5 ㎏/㎠ 의 스팀 압력하에 30 내지 50분 동안 스팀 가열하는 가열부;상기 가열부에서 가열된 재료들을 스팀으로 익힌 후, 스팀 가열에 의해 점성이 있는 상태로 뭉쳐진 재료를 원형바의 형상으로 길게 뽑아내는 형상 성형부; 및상기 원형바 형상으로 성형된 재료를 건조기에 삽입하여 수분 함량이 10% 이하가 되도록 저온 건조하거나 동결 건조하는 건조부를 포함하는 것을 특징으로 하는 반려동물의 습식사료 제조 장치.곡물 50 내지 65 중량%, 분쇄된 육고기 8 내지 12 중량%, 분쇄된 어류 15 내지 25 중량%, 미네랄믹스 1 내지 3중량%, 가시오가피 분말 3 내지 7 중량%, 홍삼분말 5 내지 10 중량%을 혼합하여 반려동물의 관절 질환을 위한 사료로 제조되는 것을 특징으로 하는 반려동물의 습식사료 조성물.곡물 50 내지 65 중량%, 분쇄된 육고기 8 내지 12 중량%, 분쇄된 연어 8 내지 12 중량%, 미네랄믹스 1 내지 5 중량%, 채소 8 내지 12 중량%와 딸기 5 내지 10 중량%를 혼합하여 반려동물의 피부 질환을 위한 사료로 제조되는 것을 특징으로 하는 반려동물의 습식사료 조성물.곡물 50 내지 65 중량%, 분쇄된 채소 8 내지 12 중량%, 분쇄된 고구마 8 내지 12 중량%, 호박 3 내지 7중량%, 양배추 10 내지 20 중량%를 혼합하여 반려동물의 장 질환을 위한 사료로 제조되는 것을 특징으로 하는 반려동물의 습식사료 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1025/1059 Row 1025: application_number: 1020200171689, combined_string: invention_title: 병아리 사육장의 환기장치 abstract: 본 발명은 부화한 병아리를 사육하는 병아리 사육장의 환기장치에 관한 것으로 보다 구체적인 것은, 병아리 사육장의 일측벽에 배기창을 내어 내부의 공기를 외부로 강제 배출시키는 배기부를 형성하고, 배기창이 형성된 벽체 양측에 위치하는 양측벽에는 외부의 공기를 내부로 흡인하는 흡기부를 형성하여 배기부와 흡기부를 이용하여 사육장 내부의 공기를 환기하고, 환기시 온습도를 조정할 수 있게 한 것인데, 배기부의 배기창에는 전동기로 작동하는 전동배출팬을 장치하여 전동배출팬이 회전하면 배기창 출구에 장치된 셔터가 열리고, 전동배출팬이 정지하면 셔터가 닫히는 개폐장치를 구비하고, 배기창 외측에 배기실을 만들어 배기실 천정에 지하수를 분사하는 분사노즐을 장치하여 배기창으로 배출되는 분진과 오염물을 배기실 실부에서 분사되는 물에 포집시켜 배기실 바닥으로 낙하시켜 바닥에 배치한 배수홈을 통해 집수정화조로 들어가게 함으로써, 배출되는 오염물과 분진이 배기실외부로 나가 공중에 비산되는 것을 예방하고, 흡기부에는 일정간격으로 흡기창을 형성하여 각 흡기창 내면에는 견인끈으로 개폐되는 개폐판을 설치하여 개폐판을 일거에 개폐하도록 하되, 흡기창 외측에 흡기실을 형성하여 흡기실 천정에 지하수를 분사하는 분사노즐을 장치하여 외부 공기와 같이 습기를 공급할 수 있게 하고, 흡기실 외벽에 흡기부를 형성하여 흡기부 크기를 조정할 수 있게 상하로 이동하는 가림판을 설치하여 흡기구의 크기를 조정할 수 있게 함으로써, 흡기량의 조정이 용이하며, 바닥에는 배수홈을 형성하여 분사노즐에서 분사된 물이 바닥에 떨어지면 배수홈을 따라 집수정화조로 들어가게 하여 배수관리가 위생적으로 이루어지게 한 병아리 사육장의 환기장치이다. claims: 병아리 사육장(1)의 길이방향 일측 외벽(1a)에 배기창(2)을 형성하여 배기창에는 입구(2a)측에 전동장치(3)에 의하여 회전하며, 내부의 공기를 외부로 강제 배출시키는 전동배출팬(4)을 장치하고, 배기창 출구측에는 전동배출팬이 회전하면 열리고, 전동배출팬이 정지하면 닫히는 셔터(5)를 장치하며, 셔터(5) 외측에 보온덮개(6)를 장치하여 개폐할 수 있게 하고, 배기창 외측으로 일정간격을 두고, 배기실(7a)을 형성하여 배기실 상단에 지붕(7b)을 형성하고, 외벽(7c)에 배출구(7d)를 형성하며, 바닥에 배수홈(6e)을 만들어 집수정화조와 연결시키고, 배기실 천정에 지하수를 공급하는 관로(7e)를 설치하여 일정간격에 지하수분사노즐(7f)을 장치한 배기부(7)를 형성하여 배기창을 통해 배출되는 분진과 오염물을 분사노즐에서 분사되는 물에 포집시켜 배기실 바닥으로 낙하시키고, 배수홈을 따라 집수정화부로 이송되게 함으로써, 배기창으로 배출되는 분진이 배기실 외부로 나가 공중에 비산되지 않게 구성하고, 병아리 사육장의 양측벽에는 일정간격으로 흡기창(8)을 설치하여 흡기창 내면에 개폐판(8a)을 설치하여 개폐판에 견인끈(8c)을 연결하여 정역회전전동기(8g)를 통해 일거에 개폐되게 하며, 흡기창 외측에 흡기실(9a)을 형성하여 흡기실 상부에 지붕(9b)을 설치하고, 외벽에 흡기구(9c)를 형성하고, 흡기실 천정에 지하수공급관(9d)을 배치하여 지하수분사노즐(9e)을 장치하고, 흡기실 바닥에 배수홈(9f)을 형성하여 집수정화조와 연통시키고, 흡기실 외벽에 가림판(9g)을 설치하여 가림판의 일단에 말대(9h)를 부착하여 가림판을 감거나 푸는 방법으로 흡기실의 크기를 조정하는 흡기부(9)를 형성하여서 되는 병아리 사육장의 환기장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1026/1059 Row 1026: application_number: 1020200108021, combined_string: invention_title: 파각란 검출장치 abstract: 본 발명은 타격대가 계란을 타격한 다음에 감지되는 반발력을 이용하여 균열의 발생 여부를 판단하므로 정확하고 신속하게 균열의 감지가 가능하며 하나의 계란에 한번씩의 타격만이 행해져 계란의 파손이 방지되고 구조가 단순하게 이루어지는 파각란 검출장치를 제공한다.본 발명의 파각란 검출장치는 이송컨베이어의 위쪽에 설치되는 프레임과, 프레임에 폭방향으로 가로질러 설치되는 복수의 타격지지축과, 타격지지축에 설치되고 반발감지센서가 설치되는 복수의 타격대와, 타격대를 타격지지축에 고정하고 한쪽에 타격안내돌기가 형성되는 타격조립부재와, 타격대의 끝단부가 이송컨베이어쪽으로 가까워지도록 힘을 가하는 탄성부재와, 프레임에 설치되는 복수의 회전지지축과, 타격안내돌기와 접하여 타격대가 회전하는 것을 제한하는 타격안내부재와, 구동모터와, 동력전달장치와, 감지된 반발력을 비교하여 균열의 발생여부를 판단하는 중앙처리장치와, 균열 발생 계란의 위치를 표시하는 표시장치를 포함하고, 홀수행에 위치하는 타격지지축에는 계란의 중앙쪽을 타격하도록 하나의 타격대를 설치하고, 짝수행에 위치하는 타격지지축에는 계란의 양쪽 끝부분쪽을 타격하도록 한쌍의 타격대를 서로 다른 위상을 갖게 배치하여 설치한다. claims: 다수의 계란을 일정한 간격으로 복수의 열로 배열된 상태로 이송하는 이송컨베이어의 위쪽에 배치되어 설치되는 프레임과, 상기 프레임에 상기 이송컨베이어에 적재되어 이송되는 계란의 이송방향 전후 간격에 대응되는 간격을 두고 배치되어 이송컨베이의 폭방향으로 가로질러 설치되는 복수의 타격지지축과, 상기 이송컨베이어에 적재되어 이송되는 계란의 좌우 간격에 대응되는 간격을 두고 상기 타격지지축에 배치되어 회전가능하게 설치되고 끝단부에는 계란과 충돌후의 반발력을 감지하는 반발감지센서가 설치되는 복수의 타격대와, 상기 타격대를 각각 상기 타격지지축에 회전가능하게 고정하고 한쪽에 타격안내돌기가 돌출 형성되는 타격조립부재와, 상기 타격대의 끝단부가 상기 이송컨베이어쪽으로 가까워지도록 각각 힘을 가하는 복수의 탄성부재와, 상기 타격지지축과 간격을 두고 평행하게 상기 프레임에 설치되는 복수의 회전지지축과, 상기 타격지지축에 설치되는 타격대에 각각 대응하도록 상기 회전지지축에 설치되고 상기 타격조립부재의 타격안내돌기와 접하여 상기 타격대의 끝단부가 이송컨베이어쪽으로 가까워지도록 회전하는 것을 일정 각도 범위에서 제한하는 복수의 타격안내부재와, 상기 프레임에 설치되는 구동모터와, 상기 구동모터의 회전력을 전달하여 상기 회전지지축을 회전시키는 동력전달장치와, 상기 반발감지센서에서 감지된 반발력을 설정된 반발력과 비교하여 균열의 발생여부를 판단하여 출력하는 중앙처리장치와, 상기 중앙처리장치로부터 출력되는 균열 발생 계란의 위치를 표시하는 표시장치를 포함하고,상기 복수의 타격지지축 중에서 홀수번째 행(홀수행)에 위치하는 타격지지축에는 계란의 중앙쪽을 타격하도록 타격대를 설치하고, 짝수번째 행(짝수행)에 위치하는 타격지지축에는 계란의 양쪽 끝부분쪽을 타격하도록 타격대를 설치하고,상기 짝수번째 행(짝수행)에 위치하는 타격지지축에 계란의 양쪽 끝부분쪽을 타격하도록 설치되는 타격대는 서로 위상차를 갖게 배치하여 설치하고,상기 타격안내부재에는 둘레의 일부를 절개하여 상기 타격조립부재의 타격안내돌기가 삽입되는 돌기삽입홈을 형성하고,상기 타격지지축은 계란이 회전하면서 이송될 때에 하나의 계란에 대하여 서로 다른 복수의 지점을 타격하도록 복수개의 행을 하나의 세트로 구성하여 설치하고,상기 프레임에는 상기 타격지지축과 간격을 두고 평행하게 상기 탄성부재의 끝단부가 고정되는 탄성고정대를 더 설치하는 파각란 검출장치., Ltext: 농업, prediction: 임업
1027/1059 Row 1027: application_number: 1020200064199, combined_string: invention_title: 파각란 검출장치 abstract: 본 발명은 타격대가 계란을 타격한 다음에 감지되는 반발력을 이용하여 균열의 발생 여부를 판단하므로 정확하고 신속하게 균열의 감지가 가능하고 구조가 단순하게 이루어지는 파각란 검출장치를 제공한다.본 발명의 파각란 검출장치는 계란을 이송하는 이송컨베이어의 위쪽에 배치되어 설치되는 프레임과, 프레임에 간격을 두고 폭방향으로 가로질러 설치되는 복수의 타격지지축과, 간격을 두고 타격지지축에 회전가능하게 설치되고 반발감지센서가 설치되는 복수의 타격대와, 타격대를 타격지지축에 회전가능하게 고정하고 한쪽에 타격안내돌기가 형성되는 타격조립부재와, 타격대의 끝단부가 이송컨베이어쪽으로 가까워지도록 힘을 가하는 복수의 탄성부재와, 타격지지축과 간격을 두고 프레임에 설치되는 복수의 회전지지축과, 회전지지축에 설치되고 타격안내돌기와 접하여 타격대가 회전하는 것을 일정 각도 범위에서 제한하는 복수의 타격안내부재와, 프레임에 설치되는 구동모터와, 구동모터의 회전력을 전달하여 회전지지축을 회전시키는 동력전달장치와, 반발감지센서에서 감지된 반발력을 설정된 반발력과 비교하여 균열의 발생여부를 판단하여 출력하는 중앙처리장치와, 중앙처리장치로부터 출력되는 균열 발생 계란의 위치를 표시하는 표시장치를 포함한다. claims: 다수의 계란을 일정한 간격으로 복수의 열로 배열된 상태로 이송하는 이송컨베이어의 위쪽에 배치되어 설치되는 프레임과, 상기 프레임에 상기 이송컨베이어에 적재되어 이송되는 계란의 이송방향 전후 간격에 대응되는 간격을 두고 배치되어 이송컨베이의 폭방향으로 가로질러 설치되는 복수의 타격지지축과, 상기 이송컨베이어에 적재되어 이송되는 계란의 좌우 간격에 대응되는 간격을 두고 상기 타격지지축에 배치되어 회전가능하게 설치되고 끝단부에는 계란과 충돌후의 반발력을 감지하는 반발감지센서가 설치되는 복수의 타격대와, 상기 타격대를 각각 상기 타격지지축에 회전가능하게 고정하고 한쪽에 타격안내돌기가 돌출 형성되는 타격조립부재와, 상기 타격대의 끝단부가 상기 이송컨베이어쪽으로 가까워지도록 각각 힘을 가하는 복수의 탄성부재와, 상기 타격지지축과 간격을 두고 평행하게 상기 프레임에 설치되는 복수의 회전지지축과, 상기 타격지지축에 설치되는 타격대에 각각 대응하도록 상기 회전지지축에 설치되고 상기 타격조립부재의 타격안내돌기와 접하여 상기 타격대의 끝단부가 이송컨베이어쪽으로 가까워지도록 회전하는 것을 일정 각도 범위에서 제한하는 복수의 타격안내부재와, 상기 프레임에 설치되는 구동모터와, 상기 구동모터의 회전력을 전달하여 상기 회전지지축을 회전시키는 동력전달장치와, 상기 반발감지센서에서 감지된 반발력을 설정된 반발력과 비교하여 균열의 발생여부를 판단하여 출력하는 중앙처리장치와, 상기 중앙처리장치로부터 출력되는 균열 발생 계란의 위치를 표시하는 표시장치를 포함하고,상기 프레임에는 상기 타격지지축과 간격을 두고 평행하게 상기 탄성부재의 끝단부가 고정되는 탄성고정대를 더 설치하고,상기 복수의 타격지지축 중에서 홀수번째 행(홀수행)에 위치하는 타격지지축에는 계란의 중앙부 양쪽을 타격하도록 타격대를 설치하고, 짝수번째 행(짝수행)에 위치하는 타격지지축에는 계란의 양쪽 끝부분쪽을 타격하도록 타격대를 설치하고,상기 타격지지축은 계란이 회전하면서 이송될 때에 하나의 계란에 대하여 서로 다른 복수의 지점을 타격하도록 복수개의 행을 하나의 세트로 구성하여 설치하고,상기 타격안내부재에는 둘레의 일부를 절개하여 상기 타격조립부재의 타격안내돌기가 삽입되는 돌기삽입홈을 형성하는 파각란 검출장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1028/1059 Row 1028: application_number: 1020200056773, combined_string: invention_title: 육계 출하관리를 위한 성장 모니터링 장치 abstract: 본 발명의 일 실시예에 따르면, 디스플레이 스크린; 및 상기 디스플레이 스크린을 통하여 개체의 목표 무게를 입력받는 제1입력 박스를 표시하고, 개체의 일령별 평균 무게를 제1그래프상에 표시하고, 개체의 일령별 평균 무게 및 상기 개체의 일령별 평균 무게가 목표 무게에 이를 것으로 예측되는 출하 예상 일자를 표시하도록 설정된 프로세서를 포함하고, 상기 프로세서는 상기 제1그래프의 제1축은 날짜를 표시하고, 제2축은 평균 무게를 표시하도록 제어하고, 상기 프로세서는 상기 제1그래프상에 적어도 하나의 상기 개체의 일령별 평균 무게를 선택 가능한 마크로 표시하며, 상기 마크가 선택되는 경우 선택된 일령별 평균 무게에 대한 분포 데이터를 제2그래프로 표시하도록 제어하는 사육 환경 모니터링 장치를 제공한다. claims: 디스플레이 스크린; 및적어도 두개 이상의 개체의 일령별 평균 무게를 나타내는 제1그래프를 상기 디스플레이 스크린에 표시하는 프로세서를 포함하고, 상기 프로세서는 개체의 현재 평균 무게 및 개체의 평균 무게가 목표 무게에 이를 것으로 예측되는 출하 예상 일자를 표시하도록 설정되고,적어도 두 개 이상의 개체의 일령별 평균 무게는 사용자 입력에 의해 선택 가능하고, 상기 프로세서는 상기 사용자 입력에 대한 응답으로, 선택된 개체의 일령별 평균 무게에 대한 분포 데이터를 나타내는 제2그래프를 표시하도록 제어하는 사육 환경 모니터링 장치., Ltext: 농업, prediction: 임업
1029/1059 Row 1029: application_number: 1020200055466, combined_string: invention_title: 먹이공급용 진동 피더 abstract: 본 발명은 먹이공급용 진동 피더에 관한 것으로, 보다 상세하게는 수족관의 어항(수조), 양어장, 축사 등에 설치하여 물고기나 닭 등에게 일정시간마다 적정량의 먹이(모이)를 공급할 수 있도록 한 것이다.또한, 본 발명은 복잡한 구조나 장치 들을 배제하고, 간단한 구조와 더불어 진동자의 부정형 진동만을 이용하여, 저장된 먹이(모이)를 일정시간마다 적정량을 안정적으로 공급할 수 있다.특히, 본 발명은 별도의 복잡한 구성이나 장치를 이용하지 않고, 스프링 등의 탄성력을 이용하여, 먹이를 배출하는 공급량조절판이 부정형으로 움직이도록 함으로써, 습기에 의해 저장된 먹이가 뭉쳐지더라도 지속적인 먹이공급이 이루어질 수 있다.따라서, 먹이공급장치 분야, 특히 자동 먹이공급장치 분야와 더불어, 가축 사육 분야, 어류양식 분야, 축사/양어장/수족관 관리분야 등은 물론, 이와 유사 내지 연관된 분야에서 신뢰성 및 경쟁력을 향상시킬 수 있다. claims: 하부에 배출홀이 형성된 호퍼;상기 배출홀로부터 일정거리 이격되도록 구성된 베이스;상기 베이스의 상부에 부정형운동이 가능하도록 구성되어 상기 배출홀의 하부에 밀착되는 공급량조절판; 및상기 공급량조절판을 부정형으로 진동시키는 진동자;를 포함하는 먹이공급용 진동 피더., Ltext: 농업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1030/1059 Row 1030: application_number: 2020200001425, combined_string: invention_title: 닭 사료를 자동으로 벨트 콘베어 식으로 주기 abstract: 본 고안은 닭에 사료를 자동으로 주게 한 고안인데, 본 설비를 설치하면 주인 한 사람이 수많은 닭을 관리할 수 있고, 인건비 절감의 효과도 보는 고안이다.[기술분야]본 기술은 닭에 사료를 자동으로 주게 한 기술인데, 본 설비를 설치하면 주인 한 사람이 수많은 닭을 관리할 수 있고, 인건비 절감의 효과도 보는 기술이다.[해결하려는 과제]닭사료는 사람이 일일이 칸칸이 다니며 부어준다. 이것이 해결 하려는 과제이다.[과제의 해결 수단]본 고안은 사료통에 닭사료를 부어 놓으면 모터로 아래로 조금씩 흘러내리면 아래 설치된 특히 좁은 벨트 콘베어가 돌아가며 사료를 운반하여 준다이로서 과제의 해결 수단이 된다 claims: 도면 1의 그림에서닭 ①에 사료를 사료통 ③에 부어 놓으면 전원 스위치 ②를 사료가 하부로 내려와 소형 벨트 콘베어 ④에 실려 닭 ①으로 가서 먹이를 먹게 한 고안이다., Ltext: 농업, prediction: 임업
1031/1059 Row 1031: application_number: 1020200045748, combined_string: invention_title: 자주식 계사청소기 abstract: 본 발명은 자주식 계사청소기에 관한 것으로, 더욱 상세하게는 닭을 사육하는 계사(鷄舍)의 바닥에 쌓인 왕겨와 계분을 파쇄한 후 불필요한 계분만을 적재함에 수거한 후 배출하도록 한 것으로, 왕겨의 재사용 효율을 높여 유지 비용을 낮출 수 있고, 분리 수거된 계분은 거름으로 활용함으로써 농가의 수익을 높일 수 있고, 작업자가 직접 탑승하여 계사를 이동하면서 작업할 수 있어 대형계사는 물론 소형계사에서도 사용이 가능하고, 계사의 바닥을 파쇄하는 작업 공정에서는 파쇄부가 바닥에 맞닿도록 하강하고 이동 과정에서는 파쇄부를 바닥에 맞닿지 않도록 상승시키고 이때 작업자가 탑승한 좌석이 구비된 컨트롤러부의 수평도를 일정하게 유지함으로써 작업자의 피로도를 낮출 수 있고 사고를 예방할 수 있는 자주식 계사청소기에 관한 것으로, 이를 위해 본 발명은 계분 및 왕겨를 저장하는 저장공간이 형성된 적재함을 포함한 적재부; 상기 적재함의 일측에 배치되어 계사의 바닥으로부터 계분과 왕겨를 파쇄하고, 바닥에서 분리된 계분과 왕겨를 일방향으로 공급하는 파쇄부; 상기 파쇄부와 상기 적재함 사이에 배치되며 상기 파쇄부로부터 공급받은 계분과 왕겨를 상기 적재함으로 전달하는 이송부; 상기 적재함의 상단 개구부에 배치되어 상기 이송부로부터 전달된 계분을 분쇄함과 동시에 상기 저장공간에 저장되는 계분의 위치 및 높이를 정렬하는 레벨유지부; 상기 적재함의 내부 바닥면에 배치되어 상기 저장공간에 저장된 계분을 적재함의 외부로 배출하는 배출부; 상기 적재함의 하방에 배치되며 메인엔진 및 조향장치를 통해 제어되는 무빙부; 상기 이송부와 적재부 사이에 배치되어 상기 이송부를 승강시키는 승강부; 및 작업자가 탑승하는 좌석과 상기 무빙부의 동작을 제어하는 조향장치를 포함한 컨트롤부를 포함한다. claims: 계분 및 왕겨를 저장하는 저장공간(111)이 형성된 적재함(11)을 포함한 적재부(10);상기 적재함(11)의 일측에 배치되어 계사의 바닥으로부터 계분과 왕겨를 파쇄하고, 바닥에서 분리된 계분과 왕겨를 일방향으로 공급하는 파쇄부(20);상기 파쇄부(20)와 상기 적재함(11) 사이에 배치되며 상기 파쇄부(20)로부터 공급받은 계분과 왕겨를 상기 적재함(11)으로 전달하는 이송부(30);상기 적재함(11)의 상단 개구부에 배치되어 상기 이송부(30)로부터 전달된 계분을 분쇄함과 동시에 상기 저장공간(111)에 저장되는 계분의 위치 및 높이를 정렬하는 레벨유지부(40);상기 적재함(11)의 내부 바닥면에 배치되어 상기 저장공간(111)에 저장된 계분을 상기 적재함(11)의 외부로 배출하는 배출부(50);상기 적재함(11)의 하방에 배치되며 메인엔진 및 조향장치를 통해 제어되는 무빙부(60);상기 이송부(30)와 적재부(10) 사이에 배치되어 상기 이송부(30)를 승강시키는 승강부(70); 및작업자가 탑승하는 좌석(81)과 상기 무빙부(60)의 동작을 제어하는 조향장치(82)를 포함한 컨트롤부(80)를 포함한 것을 특징으로 하는 자주식 계사청소기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

1032/1059 Row 1032: application_number: 1020200045461, combined_string: invention_title: 수직방향 또는 수평방향으로 전환하여 조명하는 양계장 LED조명장치 abstract: 본 발명은 수직방향 또는 수평방향으로 전환하여 조명하는 양계장 LED조명장치에 관한 것이다. 더욱 상세하게는 다층구조의 사육케이지를 가지는 양계장 내부를 조명하기 위한 조명장치로서, 저층에 위치하는 케이지나 고층에 위치하는 케이지에 대하여 균일한 조도의 조명이 이루어 질 수 있도록 하기 위한 조명장치이다. 종래에는 천장에 수평방향으로 설치된 조명장치를 이용하여, 위에서 아래쪽을 향하여 빛을 비추는 방식으로 조명하다 보니, 고층에 위치하는 케이지는 너무 밝고, 저층에 위치하는 케이지에는 너무 어둡게 되므로, 케이지의 위치에 따라 닭들의 산란율이나 성장률 등이 달라지는 문제점이 있었다. 그러나 본 발명에 의하면 조명장치를 수직방향으로 위치하게 하여 저층이나 고층에 모두 균일한 조명을 제공할 수 있게 되고, 이에 따라 양계장 내 모든 닭들을 균일하게 성장시키고 산란율이 동일하게 할 수 있으면서도 청소, 계란수거 등 작업 시에는 작업공간을 충분히 형성할 수 있도록, 조명장치를 수평방향으로 전환하여 양계장 내부를 조명할 수 있게 된다. claims: 양계장의 내부를 조명하는 LED조명장치에 있어서,일정길이를 가지는 투명튜브, 상기 투명튜브의 내부를 따라 띠 형태로 삽입되는 LED기판 및 상기 LED기판의 양면에 부착되는 복수의 LED소자로 각각 이루어지는 LED조명튜브; 사육케이지 사이의 복도를 따라 천장에 일정간격으로 고정되는 고정 고리; 상기 복도를 따라 상기 고정 고리 각각을 통과하도록 설치되며, 일 단부는 상기 양계장의 일 측면에서 작업자가 조작 가능한 높이까지 내려지는 연동로프; 상기 LED조명튜브가 수직으로 세워진 상태에서, 상기 LED조명튜브의 상단부가 상기 천장에 고정되도록 하되, 상기 LED조명튜브의 상단부를 중심축으로 하여 회전할 수 있게 고정시키는 것이 가능한 천장고정수단; 및일단이 상기 LED조명튜브의 하단부에 고정되고, 타단은 상기 연동로프에 연결되는 당김로프; 를 포함하되, 상기 LED조명튜브는, 상기 복도를 따라 상기 천장에 일정간격으로 고정되는 것을 특징으로 하는, 수직방향 또는 수평방향으로 전환하여 조명하는 양계장 LED조명장치. 양계장의 내부를 조명하는 LED조명장치에 있어서, 일정길이를 가지는 투명튜브, 상기 투명튜브의 내부를 따라 띠 형태로 삽입되는 LED기판 및 상기 LED기판의 양면에 부착되는 복수의 LED소자로 이루어지는 LED조명튜브; 사육케이지 사이의 복도를 따라 천장에 부착되는 가이드 레일; 상기 가이드 레일을 따라 이동 가능하도록, 상기 가이드 레일에 결합되는 복수개의 캐리어; 상기 복도를 따라 상기 복수개의 캐리어 각각에 연결되도록 설치되며, 일 단부는 상기 양계장의 일 측면에서 작업자가 조작 가능한 높이까지 내려지는 연동로프; 상기 LED조명튜브가 수직으로 세워진 상태에서, 상기 LED조명튜브의 상단부가 상기 천장에 고정되도록 하되, 상기 LED조명튜브의 상단부를 중심축으로 하여 회전할 수 있게 고정시키는 것이 가능한 천장고정수단; 및일단이 상기 LED조명튜브의 하단부에 고정되고, 타단은 상기 연동로프에 연결되는 당김로프; 를 포함하되, 상기 LED조명튜브는, 상기 복도를 따라 상기 천장에 일정 간격으로 고정되는 것을 특징으로 하는, 수직방향 또는 수평방향으로 전환하여 조명하는 양계장 LED조명장치., Ltext: 농업, prediction: 임업
1033/1059 Row 1033: application_number: 1020200042561, combined_string: invention_title: 자동 닭사육장 abstract: 내부에 일정한 공간을 형성한 축사(10)와; 상기 축사(10)의 외면에 또는 상기 축사(10)의 외부에 설치되고, 태양광 발전이 가능한 태양광모듈(20)로서, 상기 태양광모듈(20)에 전기적으로 연결되어 제어명령을 송신할 수 있는 제어부(60)와; 상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 벨 소리를 자동으로 낼 수 있는 자동경보부와; 상기 제어부(60) 및 상기 자동경보부에 연결되어 상기 벨 소리에 연동하여 상기 축사(10)의 전면에 설치된 출입용 도어(70)를 자동으로 개폐할 수 있는 자동개폐부; 및 상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 자동으로 모이 및 물을 공급할 수 있는 자동급이부를 포함하는 것을 특징으로 하는 자동 닭사육장에 관한 것이다. claims: 내부에 일정한 공간을 형성한 축사(10);상기 축사(10)의 외면에 또는 상기 축사(10)의 외부에 설치되고, 태양광 발전이 가능한 태양광모듈(20);상기 태양광모듈(20)에 전기적으로 연결되어 제어명령을 송신할 수 있는 제어부(60);상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 벨 소리를 자동으로 낼 수 있는 자동경보부;상기 제어부(60) 및 상기 자동경보부에 연결되어 상기 벨 소리에 연동하여 상기 축사(10)의 전면에 설치된 출입용 도어(70)를 자동으로 개폐할 수 있는 자동개폐부; 및상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 자동으로 모이 및 물을 공급할 수 있는 자동급이부를 포함하고,상기 자동개폐부는,상기 축사(10)의 전면(11) 중 출입구의 상측에 설치되고 회전축을 가지는 모터(41);상기 모터(41)의 회전축에 연결된 제1 스크류(42);상기 제1 스크류(42)에 나합하고 있는 제2 스크류(43);상기 제2 스크류(43)에 'ㅁ'자형 연결부(44)를 통해 연결된 이동부(40); 및상기 이동부(40)의 상하 이동을 안내하는 안내관(45)을 포함하고,상기 출입용 도어(70)가 삽입관(70h)를 상측 내부에 형성하고, 상기 삽입관(70h)을 통해 상기 'ㅁ'자형 연결부(44)의 하측에 결합되어 상기 이동부(40)의 상하 이동에 따라 상하로 이동할 수 있는 것을 특징으로 하는 자동 닭사육장.내부에 일정한 공간을 형성한 축사(10);상기 축사(10)의 외면에 또는 상기 축사(10)의 외부에 설치되고, 태양광 발전이 가능한 태양광모듈(20);상기 태양광모듈(20)에 전기적으로 연결되어 제어명령을 송신할 수 있는 제어부(60);상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 벨 소리를 자동으로 낼 수 있는 자동경보부;상기 제어부(60) 및 상기 자동경보부에 연결되어 상기 벨 소리에 연동하여 상기 축사(10)의 전면에 설치된 출입용 도어(70)를 자동으로 개폐할 수 있는 자동개폐부; 및상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 자동으로 모이 및 물을 공급할 수 있는 자동급이부를 포함하고,상기 자동개폐부는,상기 축사(10)의 전면(11) 중 출입구의 상측에 설치되고 회전축을 가지는 모터(41');상기 모터(41')의 회전축에 연결된 회전봉(81);상기 회전봉(81)에 연결된 도르래(80); 및상기 도르래(80)에 와인딩 및 언와인딩될 수 있고, 출입용 도어(70')의 상단부에 인접한 부분에 연결된 로프(82)를 포함하고,상기 출입용 도어(70')가 상기 로프(82)의 와인딩 및 언와인딩에 따라 출입구에 인접하는 축사의 부분 중 좌측 및 우측 부분의 하측에 연결된 힌지(85)를 중심으로 여닫이식으로 회전하여 상기 축사(10)의 출입구를 개폐할 수 있는 것을 특징으로 하는 자동 닭사육장., Ltext: 농업, prediction: 임업

Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1034/1059 Row 1034: application_number: 1020200040822, combined_string: invention_title: 친환경 방목닭 잡초제거 농법 및 그 잡초제거 농법을 이용한 친환경 방목닭 사육방법 abstract: 본 발명은 친환경 방목닭 잡초제거 농법 및 그 잡초제거 농법을 이용한 친환경 방목닭 사육방법에 관한 것으로 과수의 성장에 해를 끼치지 않을 범위 내의 규격으로 방목케이지를 형성하여 닭의 잡초제거 작업영역을 지정하고, 그 작업영역 내의 잡초만을 제거하면서 방목되도록 하며, 그 작업영역의 작업이 완료되면 다음 작업영역으로 이동하여 방목 및 잡초제거가 효율적이면서 지속적으로 진행될 수 있도록 함과 아울러, 닭이 낯에는 방목케이지에서 잡초와 벌레 등을 먹고, 아침 및 저녁에는 닭사육장에서 사료와 동종수액(음용수)을 취하며 휴식토록 함으로써 품질이 우수한 친환경 방목닭을 사육할 수 있도록 하기 위하여, 과수원 내 과수 사이에 성장한 잡초(9)를 제거하기 위해 일정범위 내의 규격으로 이동형 방목케이지(A)를 마련하되, 상기 방목케이지(A)는 높이를 갖는 측방 폐쇄 형태로 하부틀프레임(10)을 형성하고, 상기 하부틀프레임(10)의 상부측으로 다수의 지지파이프(20)를 고정 연결하고 난 다음, 상기 다수 지지파이프(20)의 외면을 보호망체(25)로 씌워 상기 보호망체(25)의 내측으로 닭(8)이 수용되는 방목공간부(92)를 형성하며, 상기 보호망체(25) 상에 작업자가 출입하도록 출입문(40)을 형성하여 이루어지게 하고, 상기 하부틀프레임(10)을 지면(2)에서 함몰 형성된 설치홈(3) 내에 삽입안착되도록 하여 하부틀프레임(10)의 하부측을 통해 방목공간부(92)로 유해동물의 침입을 방지하도록 하며, 상기 방목공간부(92) 내에 닭(8)을 방목하여 방목케이지(A) 내의 잡초(9)를 일정 시간동안 제거토록 한 다음 방목케이지(A)를 주변 다른구역으로 이동시켜 가며 과수원 내의 잡초(9)를 제거하도록 함을 포함하여 이루어지는 것을 특징으로 한다. claims: 과수원 내 과수 사이에 성장한 잡초(9)를 제거하기 위해 일정범위 내의 규격으로 이동형 방목케이지(A)를 마련하되,상기 방목케이지(A)는 높이를 갖는 측방 폐쇄 형태로 하부틀프레임(10)을 형성하고, 상기 하부틀프레임(10)의 상부측으로 다수의 지지파이프(20)를 고정 연결하고 난 다음, 상기 다수 지지파이프(20)의 외면을 보호망체(25)로 씌워 상기 보호망체(25)의 내측으로 닭(8)이 수용되는 방목공간부(92)를 형성하며, 상기 보호망체(25) 상에 작업자가 출입하도록 출입문(40)을 형성하여 이루어지게 하고,상기 하부틀프레임(10)을 지면(2)에서 함몰 형성된 설치홈(3) 내에 삽입안착되도록 하여 하부틀프레임(10)의 하부측을 통해 방목공간부(92)로 유해동물의 침입을 방지하도록 하며,상기 방목공간부(92) 내에 닭(8)을 방목하여 방목케이지(A) 내의 잡초(9)를 일정 시간동안 제거토록 한 다음 방목케이지(A)를 주변 다른구역으로 이동시켜 가며 과수원 내의 잡초(9)를 제거하도록 함을 포함하여 이루어지는 것을 특징으로 하는 친환경 방목닭 잡초제거 농법.과수원 내 과수 사이에 성장한 잡초(9)를 제거하기 위해 일정범위 내의 규격으로 이동형 방목케이지(A)를 마련하며, 상기 방목케이지(A)는 높이를 갖는 측방 폐쇄 형태로 하부틀프레임(10)을 형성하되 상기 하부틀프레임(10)은 직선바 형태의 전방하부틀(11), 후방하부틀(12) 및 양측방하부틀(13,14)로 구비되어 직사각 형태로 형성되게 하며, 상기 하부틀프레임(10)의 상부측으로 다수의 지지파이프(20)를 고정 연결하되 상기 지지파이프(20)를 “∩”형태로 형성하고, 전방하부틀(11)과 후방하부틀(12) 사이에 다수의 지지파이프(20)를 일정간격 설치하여 방목케이지(A)가 터널형으로 형성한 다음, 상기 다수 지지파이프(20)의 외면을 보호망체(25)로 씌워 상기 보호망체(25)의 내측으로 닭(8)이 수용되는 방목공간부(92)를 형성하며, 상기 보호망체(25) 상에 작업자가 출입하도록 출입문(40)을 형성하여 이루어지게 하고, 상기 하부틀프레임(10)을 지면(2)에서 함몰 형성된 설치홈(3) 내에 삽입안착되도록 하여 하부틀프레임(10)의 하부측을 통해 방목공간부(92)로 유해동물의 침입을 방지하도록 하며,상기 방목케이지(A)의 일측편에 작업자의 출입문(40)을 형성하며, 상기 방목케이지(A)의 타측편에 닭(8)의 출입을 위한 제1출입문(94)을 형성하고, 방목케이지(A)의 인근에 마련된 닭사육장(60)의 측벽(62)에 제2출입문(65)을 형성하며, 상기 제1출입문(94)과 제2출입문(65) 사이에 통로망(70)을 연결 설치하여, 아침 및 저녁에는 닭(8)이 닭사육장(60) 내에 머무르게 하고, 낯에는 상기 통로망(70)을 통해 닭사육장(60)에서 방목케이지(A)로 이동하여 잡초(9)를 제거토록 하되,상기 닭사육장(60) 내에 사료가 수직 충진되는 충진파이프(112)와, 상기 충진파이프(12)에 직교 연장되어 단부에 사료가 노출되는 공급파이프(114)로 된 사료자동급여기(110)를 마련하고,상기 닭사육장(60) 및 방목케이지(A) 내에 동종수액을 생성하는 동종수액추출기(132)와, 상기 동종수액추출기(132)로부터 동종수액을 공급받아 닭사육장(60) 내로 이동시키는 이동관(134)과, 상기 이동관(134) 상에 다수 연결되어 닭(8)에게 동종수액을 공급하는 노즐(136)로 된 동종수액자동급여기(130)를 마련하여,상기 닭(8)이 낮에는 방목케이지(A) 내에서 잡초(9)와 벌레를 먹으면서 사육되고, 아침 및 저녁에는 닭사육장(60) 내에서 사료자동급여기(110) 및 동종수액자동급여기(130)를 통해 사료와 동종수액을 취하며 휴식토록 함으로써 품질이 우수한 친환경 방목닭을 사육할 수 있도록 함을 특징으로 하는 친환경 방목닭 잡초제거 농법을 이용한 친환경 방목닭 사육방법., Ltext: 농업, prediction: 임업
1035/1059 Row 1035: application_number: 1020200038172, combined_string: invention_title: 양계장의 양계활동공간영역의 공기정화장치 abstract: 본 발명은 양계장의 양계활동공간영역의 공기장화장치에 관한 것으로 양계장의 바닥양계에 있어서, 양계활동공간영역 (바닥에서 대략 큰 닭의 키에 상응한 높이의 공간)을 청정공간으로 유지하기 위하여, 양계장의 공기를 정화하는 공기정화부(air purity portion)와; 공기정화장치의 유로(流路)에 공기의 유동성을 부여하는 공기 액추에이트부(air actuate portion)와; 정화된 공기를 양계장 바닥의 평면상에 균일한 분포로 양계의 호흡에 유효한 공간으로 분사하는 공기공급부(air supply portion)를; 포함하여 구성된 것이다.본 발명에 의하면, 양계장 바닥에 설치된 상기 공기정화장치의 공기 액추에이트부의 가동에 따라 상기 공기정화부가 부압으로 되면서 주위의 공기가 흡입되어 세균이 포함된 먼지 등이 제거되고 정화된 공기는 상기 공기공급부에 의해 양계장 바닥의 평면상에 균일한 분포로 분사된다. 따라서 양계활동공간영역이 청정하게 유지되어 병아리의 폐사율이 저감되고 양계가 보다 위생적인 환경에서 건강하고 빠르게 성장할 수 있으며, 공조시설비의 절감 및 양계수익을 보다 높일 수 있다. claims: 양계장의 바닥양계에 있어서, 양계활동공간영역을 청정하기 위하여, 공기의 정화기능을 가진 공기정화부와, 공기정화장치의 유로(流路)에 공기의 유동성을 부여하는 공기 액추에이트부와, 정화된 공기를 평면의 균일한 분포로 분사기능을 가진 공기공급부를 포함하여 구성된 것을 특징으로 하는 양계장의 양계활동공간영역의 공기장화장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1036/1059 Row 1036: application_number: 1020200021123, combined_string: invention_title: ICT 융복합 축산환경 관제시스템 abstract: 개시되는 ICT 융복합 축산환경 관제시스템은, 복수의 축산농가에 각각 설치되는 도징 시스템;으로서, 외부로부터 가축에게 물을 공급하는 펌프;와, 상기 펌프에 의해 공급되는 물의 유량을 감지하는 유량센서;와, 상기 유량센서에 의해 감지된 유량정보에 따라 설정된 비율로 액상 사료첨가제를 공급하는 도징유닛;을 포함하는 도징 시스템; 상기 가축이 배출하는 분뇨 또는 가스로부터 악취를 측정하여 상기 악취정보를 생성하는 악취 측정부; 상기 도징유닛 및 상기 악취 측정부와 통신 가능하게 구비되며, 상기 축산농가 식별정보, 상기 설정된 비율, 누적음수량(L), 순시음 수량(L/hr), 누적 액상 사료첨가제 급이량(L), 도징유닛의 상태(RUN, STOP, ALARM)에 관한 정보를 포함하는 도징 시스템 정보 및 상기 악취정보를 포함하는 악취 측정부 정보를 수집하는 감시정보 수집부; 인터넷에 연결되어 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 송신하는 통신부; 상기 통신부로부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전달받아 저장하는 클라우드 서버; 및 상기 축산농가의 관리자가 인터넷을 통해 상기 클라우드 서버에 접근 가능하게 구비되는 관리자단말;을 포함한다. claims: 복수의 축산농가에 각각 설치되는 도징 시스템;으로서, 외부로부터 가축에게 물을 공급하는 펌프;와, 상기 펌프에 의해 공급되는 물의 유량을 감지하는 유량센서;와, 상기 유량센서에 의해 감지된 유량정보에 따라 설정된 비율로 액상 사료첨가제를 공급하는 도징유닛;을 포함하는 도징 시스템;상기 가축이 배출하는 분뇨 또는 가스로부터 악취를 측정하여 악취정보를 생성하는 악취 측정부;상기 도징유닛 및 상기 악취 측정부와 통신 가능하게 구비되며, 축산농가 식별정보, 상기 설정된 비율, 누적음수량(L), 순시음 수량(L/hr), 누적 액상 사료첨가제 급이량(L), 도징유닛의 상태(RUN, STOP, ALARM)에 관한 정보를 포함하는 도징 시스템 정보 및 상기 악취정보를 포함하는 악취 측정부 정보를 수집하는 감시정보 수집부;인터넷에 연결되고, 상기 감시정보 수집부와 통신가능하도록 연결되어 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 송신하는 통신부;인터넷을 통하여 상기 통신부로부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전달받아 저장하는 클라우드 서버;상기 축산농가의 관리자가 인터넷을 통해 상기 클라우드 서버에 접근 가능하게 구비되는 관리자단말;상기 클라우드 서버로 부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전송받고, 상기 악취정보를 포함하는 사육정보에 따라 상기 설정된 비율을 설정, 변경 또는 갱신하는 관제부;상기 액상 사료첨가제가 수용되고 상기 도징유닛을 통하여 상기 펌프와 배관 연결되며, 상기 액상 사료첨가제의 잔량 정보를 측정하는 수위 감지센서를 구비한 첨가제 수용용기; 및상기 펌프의 온도를 감지하는 온도센서를 포함하고, 상기 관리자가, 상기 관리자단말을 이용하여 상기 가축이 배설하는 분뇨를 수거하는 분뇨수거 주기 및 악취제거제 사용 여부를 포함하는 축사관리정보;와 상기 가축의 축종과 사육두수 및 상기 가축의 사양단계를 포함하는 가축정보; 및 상기 가축에 급이되는 사료의 종류 및 급이량을 포함하는 급이정보를 상기 클라우드 서버에 입력하고,상기 사육정보는 상기 축사관리정보와, 상기 가축정보 및 상기 급이정보를 더 포함하고 상기 관제부는, 상기 악취정보와, 상기 축사관리정보와, 상기 급이정보, 및 상기 가축정보를 기반으로하여, 상기 악취정보와 상기 액상 사료첨가제의 공급량 사이의 상관관계를 도출하고, 도출된 상기 상관관계에 따라 상기 설정된 비율을 설정하거나, 변경 또는 개정하고, 상기 가축이 배출하는 분뇨에서 배출되는 악취의 정도를 분석하고, 비정형 데이터 및 정형 데이터를 모두 포함하는 상기 사육정보를 데이터 마이닝 기법을 이용한 빅데이터 분석하여 상기 상관관계를 도출하고,상기 감시정보 수집부는,상기 액상 사료첨가제의 잔량 정보 및 상기 도징유닛의 온도 정보를 더 포함하는 상기 도징 시스템 정보를 생성하고,상기 도징유닛은,설정된 비율 정보를 입력받아 상기 펌프의 동작을 제어하는 제어부를 더 포함하는 ICT 융복합 축산환경 관제시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1037/1059 Row 1037: application_number: 1020200017179, combined_string: invention_title: 배출모듈이 구비된 자주식 계사청소기 abstract: 본 발명은 배출모듈이 구비된 자주식 계사청소기에 관한 것으로, 보다 상세하게는 닭을 사육하는 계사(鷄舍)의 바닥에 쌓인 왕겨와 계분을 파쇄한 후 계분만을 분리하여 적재함에 수거 후 배출함으로써, 왕겨의 재사용을 통해 유지비용을 절감할 수 있고, 분리 수거된 계분은 거름으로 재활용할 수 있고, 자주식(自走式)으로 구성되어 대형계사는 물론 소형계사에서도 사용이 가능하며, 수거된 계분을 별도의 수거용 장비로 공급하기 위하여 적재함의 높이 및 각도를 조절하는 배출모듈이 구비되어 배출의 용이성을 향상시킨 배출모듈이 구비된 자주식 계사청소기에 관한 것으로, 본 발명은, 몸체프레임; 상기 몸체프레임의 일측에 승강 가능하게 배치되어 계사의 바닥에 쌓인 왕겨와 계분을 파쇄하고, 파쇄된 왕겨와 계분을 일방향으로 공급하는 수거부; 상기 수거부로부터 공급된 왕겨와 계분을 상방으로 이송하되, 이송 중 상대적으로 크기가 작은 왕겨는 하방으로 낙하하도록 다공성으로 이루어진 이송블레이드가 구비된 승강부; 상기 몸체프레임에 결합되고, 상기 승강부로부터 이송된 계분이 투입되도록 상부가 개구되어 형성된 적재함과, 상기 적재함의 개구된 상단에 배치되어 투입되는 계분의 위치 및 높이를 정렬하는 레벨유지수단을 포함한 적재부; 상기 적재함의 바닥에 배치되어 계분을 상기 적재함의 일측단에 형성된 배출공을 통해 배출하도록 이송하는 배출블레이드를 포함한 배출부; 상기 몸체프레임의 하방에 배치되어 메인엔진 및 조향장치를 통해 구동되는 트랙부; 상기 수거부의 각도를 조절하는 각도조절부; 및 상기 트랙부와 상기 적재부 사이에 배치되어 상기 적재함의 높이 및 경사 각도를 조절하는 배출모듈;을 포함하되, 상기 배출모듈은, 상기 적재함이 안치되는 안치프레임과, 상기 안치프레임을 수평방향으로 이동시키는 수평리프트과, 상기 안치프레임을 승강시키기 위한 승강리프트를 포함한다. claims: 몸체프레임(10);상기 몸체프레임(10)의 일측에 승강 가능하게 배치되어 계사의 바닥에 쌓인 왕겨와 계분을 파쇄하고, 파쇄된 왕겨와 계분을 일방향으로 공급하는 수거부(20);상기 수거부(20)로부터 공급된 왕겨와 계분을 상방으로 이송하되, 이송 중 상대적으로 크기가 작은 왕겨는 하방으로 낙하하도록 다공성으로 이루어진 이송블레이드(22)가 구비된 승강부(30);상기 몸체프레임(10)에 결합되고, 상기 승강부(30)로부터 이송된 계분이 투입되도록 상부가 개구되어 형성된 적재함(41)과, 상기 적재함(41)의 개구된 상단에 배치되어 투입되는 계분의 위치 및 높이를 정렬하는 레벨유지수단(42)을 포함한 적재부(40);상기 적재함(41)의 바닥에 배치되어 계분을 상기 적재함(41)의 일측단에 형성된 배출공(412)을 통해 배출하도록 이송하는 배출블레이드(52)를 포함한 배출부(50);상기 몸체프레임(10)의 하방에 배치되어 메인엔진 및 조향장치(WL)를 통해 구동되는 트랙부(60);상기 수거부(20)의 각도를 조절하는 각도조절부(70); 및상기 트랙부(60)와 상기 적재부(40) 사이에 배치되어 상기 적재함(41)의 위치 및 높이를 조절하는 배출모듈(80);을 포함하되,상기 배출모듈(80)은,상기 적재함(41)이 안치되는 안치프레임(81)과,상기 안치프레임(81)을 수평방향으로 이동시키는 수평리프트(82)와,상기 안치프레임(81)을 승강시키기 위한 승강리프트(83)를 포함한 것을 특징으로 하는 배출모듈이 구비된 자주식 계사청소기.몸체프레임(10);상기 몸체프레임(10)의 일측에 승강 가능하게 배치되어 계사의 바닥에 쌓인 왕겨와 계분을 파쇄하고, 파쇄된 왕겨와 계분을 일방향으로 공급하는 수거부(20);상기 수거부(20)로부터 공급된 왕겨와 계분을 상방으로 이송하되, 이송 중 상대적으로 크기가 작은 왕겨는 하방으로 낙하하도록 다공성으로 이루어진 이송블레이드(22)가 구비된 승강부(30);상기 몸체프레임(10)에 결합되고, 상기 승강부(30)로부터 이송된 계분이 투입되도록 상부가 개구되어 형성된 적재함(41)과, 상기 적재함(41)의 개구된 상단에 배치되어 투입되는 계분의 위치 및 높이를 정렬하는 레벨유지수단(42)을 포함한 적재부(40);상기 몸체프레임(10)의 하방에 배치되어 메인엔진 및 조향장치(WL)를 통해 구동되는 트랙부(60);상기 수거부(20)의 각도를 조절하는 각도조절부(70); 및상기 트랙부(60)와 상기 적재부(40) 사이에 배치되어 상기 적재함(41)의 위치 및 경사 각도를 조절하는 배출모듈(80);을 포함하되,상기 배출모듈(80)은,상기 적재함(41)이 안치되는 안치프레임(81)과,상기 적재함(41)의 배출각도를 조절하기 위한 배출각도 조절수단(84)을 포함한 것을 특징으로 하는 배출모듈이 구비된 자주식 계사청소기., Ltext: 농업, prediction: 임업
1038/1059 Row 1038: application_number: 1020200015153, combined_string: invention_title: 스마트 닭 모이통 abstract: 본 발명은 스마트 닭모이통에 관한 것으로서, 대용량 닭 사료가 충진되는 사료 공급통; 사료 공급통의 출구를 조도센서 신호에 따라 자동 개폐하는 자동개폐장치; 상기 사료 공급통의 하부에 이격 설치되어 적정량의 사료가 채워지도록 된 급이통; 상기 급이통의 내부에 설치되어 사료의 유무를 센싱하는 사료감지부; 상기 사료감지부의 신호를 받아 자동개폐장치를 작동하는 제어모듈; 상기 제어모듈 및 자동개폐장치에 전원을 공급하는 전원공급부; 및 상기 급이통과 사료 공급통 사이를 이격시켜 고정하는 거치대;를 포함하는 것을 특징으로 한다. claims: 대용량 닭 사료가 충진되는 사료 공급통(110);사료 공급통(110)의 출구를 조도센서(143) 신호에 따라 자동 개폐하는 자동개폐장치(120);상기 사료 공급통(110)의 하부에 이격 설치되어 적정량의 사료가 채워지도록 된 급이통(130);상기 급이통(130)의 내부에 설치되어 사료의 유무를 센싱하는 사료감지부(140);상기 사료감지부(140)의 신호를 받아 자동개폐장치(120)를 작동하는 제어모듈(150);상기 제어모듈(150) 및 자동개폐장치(120)에 전원을 공급하는 전원공급부(160); 및상기 급이통(130)과 사료 공급통(110) 사이를 이격시켜 고정하는 거치대(170);를 포함하는 것을 특징으로 하는 스마트 닭모이통., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1039/1059 Row 1039: application_number: 1020200014544, combined_string: invention_title: 계사 내 진드기 포획장치 저전력 제어시스템 abstract: 본 발명은 계사 내 진드기 포획장치 저전력 제어시스템에 관한 것이다. 이는, 진드기를 잡아 포획하는 포획층을 구비하고 계사에 배치되는 포획시트, 포획시트의 무게 및 온도변화를 감지하는 센서부, 센서부가 감지한 정보를 외부로 전송하는 RF모듈을 갖는 진드기포획장치를 제어하는 것으로서, 전력공급부에 접속되는 저전력모듈과; 저전력모듈을 통해 전력을 상시 전달받으며 설정시간마다 신호를 출력하는 신호출력부와; 전력공급부로부터 전달받은 전력을 상기 진드기포획장치로 공급하는 주전력모듈과; 신호출력부가 신호를 출력하는 동안에만 주전력모듈로 전력이 공급되게 하는 스위치를 구비한다.상기와 같이 이루어지는 본 발명의 계사 내 진드기 포획장치 저전력 제어시스템은, 진드기포획장치에 설치되어 있는 센서부와 RF모듈을 이용해 포획된 진드기의 개체수를 파악하되, 관리자에 의해 설정된 시간 간격으로 파악할 수 있어, 필요 없는 전력의 낭비를 유발하지 않아 경제적 부담 없이 운용이 가능하다. claims: 다공성 구조를 가지며 내부로 파고 들어온 진드기를 잡아 포획하는 포획층을 구비하고 계사에 배치되는 다수의 포획시트, 시간경과에 따른 포획시트의 무게 및 온도변화를 감지하는 센서부, 상기 센서부가 감지한 정보를 외부로 전송하는 RF모듈을 갖는 진드기포획장치를 제어하는 것으로서, 전력공급부와;상기 전력공급부에 접속되는 저전력모듈과;상기 저전력모듈을 통해 전력을 상시 전달받으며 설정시간마다 신호를 출력하는 신호출력부와;상기 전력공급부에 접속되고 전력공급부로부터 전달받은 전력을 상기 진드기포획장치로 공급하여 센서부와 RF모듈이 동작하게 하는 주전력모듈과;상기 전력공급부와 주전력모듈의 사이에 설치되며, 상기 신호출력부가 신호를 출력하는 동안에만 주전력모듈로 전력이 공급되게 하는 스위치와;상기 RF모듈을 통해 전달받은 진드기포획장치의 온도 및 무게변화 데이터를 관리자에게 전송하는 서버모듈을 구비하는 계사 내 진드기 포획장치 저전력 제어시스템., Ltext: 농업, prediction: 임업
1040/1059 Row 1040: application_number: 1020200011144, combined_string: invention_title: 벼신품종 슈퍼자미를 포함한 육계사료용 첨가제 및 이를 이용하여 생산한 육계 abstract: 본 발명은 슈퍼자미를 육계용 사료에 첨가한 육계용 사료를 개시하고 본 발명에 슈퍼자미를 기본사료에 10%이상을 첨가하여 사양하는 경우 무항생제 처방사육이 가능하고 조지방 함량이 낮고 조단백 함량이 높은 육계를 생산할 수 있는 뛰어난 효과가 있다. claims: 벼 신품종 슈퍼자미(Oryza sativa L. var. super C3GHi)가 포함된 육계사료용 첨가제.제1항의 벼 신품종 슈퍼자미(Oryza sativa L. var. super C3GHi)가 포함된 육계사료용 첨가제로 사육되어 조지방과 콜레스테롤 함량이 동시에 감소된 것이 특징인 육계., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1041/1059 Row 1041: application_number: 1020200006680, combined_string: invention_title: 양계용 음용수 공급장치 abstract: 본 발명은 양계용 음용수 공급장치에 관한 것으로, 닭의 음용수가 공급되는 음용수 공급관; 음용수 공급관에 구비되어 공급되는 음용수를 열교환에 의해 냉수 또는 온수화하는 열교환모듈;을 포함하되, 열교환모듈은 음용수 공급관을 감싸 구비되는 열교환챔버; 열교환챔버에 연결되어 그 내부를 순환하는 냉매로서 음용수 공급관을 냉각 또는 가열하는 냉매순환관; 냉매순환관에 연결되어 냉매를 열교환시켜 냉매순환관으로 공급하는 열교환기; 열교환기에 구비되어 열교환기를 냉각 또는 가열시키는 열전소자; 냉매순환관에 구비되어 냉매를 순환 공급시키는 순환펌프;를 포함하는 음용수 공급장치를 제공한다. claims: 닭의 음용수가 공급되는 음용수 공급관; 음용수 공급관에 구비되어 공급되는 음용수를 열교환에 의해 냉수 또는 온수화하는 열교환모듈;을 포함하는 음용수 공급장치., Ltext: 농업, prediction: 임업
1042/1059 Row 1042: application_number: 1020200002069, combined_string: invention_title: 에너지 공유를 통한 효율적 건조 시스템 및 공정 abstract: 본 발명은 에너지 공유를 통한 효율적 건조 시스템 및 고정에 관한 것으로써, 보다 상세하게는, 바이오매스를 연소시킬 때 발생하는 폐열 및 양계장에서의 닭의 체온을 이용하여 유기성 폐기물이 포함된 전구체를 건조시켜 이중으로 함수율을 감소시키고, 추가적인 에너지가 필요하지 않아 에너지를 절약할 수 있는 에너지 공유를 통한 효율적 건조 시스템 및 공정에 관한 것이다. claims: 유기성 폐기물을 이용하여 전기, 폐열 및 슬러리를 생산하는 혐기성 처리수단; 닭이 사육되는 하우스에서 발생되는 상기 닭의 체열을 방출하는 체열 공급부; 및 상기 혐기성 처리수단에서 생상되는 폐열과 상기 체열 공급부에서 방출되는 상기 닭의 체열을 이용하여 상기 슬러리가 포함된 전구체를 건조하고, 펠렛 비료를 생산하는 다단계 건조기;를 포함하는, 에너지 공유를 통한 효율적 건조 시스템. 유기성 폐기물을 가온시켜 바이오매스를 생산하는 단계; 상기 바이오매스를 생산하고 남은 상기 유기성 폐기물을 폐수 및 슬러리로 고액분리하는 단계; 열병합발전기에 상기 바이오매스를 투입한 후 연소하여 전기 및 폐열을 생산하는 단계; 상기 열병합발전기에서 생산된 폐열과 양계장 내부 닭의 체열을 다단계 건조기로 배출하는 단계; 및 상기 다단계 건조기에 상기 슬러리가 포함된 전구체를 공급하고, 상기 폐열 및 상기 체열로 상기 전구체를 건조시키는 단계;를 포함하는, 에너지 공유를 통한 효율적 건조 공정., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1043/1059 Row 1043: application_number: 1020200000831, combined_string: invention_title: 백색 LED를 이용하여 육계의 생산성 및 면역력을 증가시키는 방법 abstract: 본 발명은 백색 LED를 이용하여 육계의 생산성 및 면역력을 증가시키는 방법에 관한 것으로, 기존의 형광등 또는 다른 파장대의 LED를 사용한 육계의 사육 방법에 비해 육계의 생산성 및 면역력 증진 효과가 우수하므로 육계를 포함한 가금류의 사육 효율을 높일 수 있다. claims: 육계의 사육시기에 따라 조도가 다른 백색 LED 광원을 조사하면서 육계를 사육하는 단계를 포함하는 것을 특징으로 하는 육계의 생산성 및 면역력을 증가시키는 방법.육계의 사육시기에 따라 조도가 다른 백색 LED 광원을 조사하면서 육계를 사육하는 단계를 포함하는 것을 특징으로 하는 생산성 및 면역력이 증가된 육계의 생산 방법.제5항의 방법에 의해 생산된 생산성 및 면역력이 증가된 육계., Ltext: 농업, prediction: 임업
1044/1059 Row 1044: application_number: 1020190173894, combined_string: invention_title: 산란계 온습도지수 알림 시스템 abstract: 본 발명은 산란계 온습도지수(Temperature Humidity Index, THI) 알림 시스템에 관한 것으로, 본 발명에 따른 산란계 온습도지수 알림 시스템은, 오픈 API 방식의 기상 정보를 제공하는 기상 서버; 오픈 API 방식의 맵 데이터 정보를 제공하는 맵 서버; 및 기상 서버 및 맵 서버로부터 기상 정보 및 맵 데이터 정보를 수신하고 수신된 정보를 이용하여 사용자의 어플리케이션을 통해 온습도지수 정보를 제공하는 앱서버로 구성되고, 앱서버는기상 서버로부터 API를 통해 기상정보를 수신하는 기상정보 수신부; 맵서버로부터 API를 통해 맵정보 데이터를 수신하는 맵데이터 정보 수신부;기상정보 수신부로부터 수신된 기상정보를 어플리케이션에서 이용되는 형식으로 변환하고 분류하는 기상정보 분류부; 기상정보 분류부에서 분류된 기상자료에 기반하여 THI를 산출하기 위한 THI 산출부; 맵데이터 정보 수신부로부터 수신된 맵 데이터에 THI 산출부에서 계산된 THI 정보를 매칭시킨 THI 맵을 생성하기 위한 THI 맵 생성부; 및 THI 맵 생성부에서 생성된 THI 맵을 어플리케이션에서 요구되는 형식을 가진 송출용 THI 데이터로 변환하여 생성하는 송출용 THI 데이터 생성부를 포함하고,상기 THI 산출부는, 기상정보 분류부에서 분류된 기상자료에 기반하여 지역별 THI를 계산하는 지역기반 THI 산출부; 기상정보 분류부에서 분류된 기상자료에 기반하여 시간대별 THI를 계산하는 시간기반 THI 계산부; 및 외기온도에 따른 THI를 계산하는 외기온도기반 THI 산출부를 포함하고,상기 THI 산출부는 기상정보 분류부에서 분류된 기상자료에 기반하여 계사의 환기 형태에 따른 THI 값을 계산하도록 구성되고,THI 맵 생성부는 맵 데이터의 지역별 THI 맵과 함께, 계사의 형태에 따른 THI 값에 기반한 컬러 속성을 갖는 THI 맵을 생성하도록 구성된다. claims: 오픈 API 방식의 기상 정보를 제공하는 기상 서버; 오픈 API 방식의 맵 데이터 정보를 제공하는 맵 서버; 및 기상 서버 및 맵 서버로부터 기상 정보 및 맵 데이터 정보를 수신하고 수신된 정보를 이용하여 사용자의 어플리케이션을 통해 온습도지수 정보를 제공하는 앱서버를 포함하는 산란계 온습도지수 알림 시스템에 있어서,상기 앱서버는기상 서버로부터 API를 통해 기상정보를 수신하는 기상정보 수신부; 맵서버로부터 API를 통해 맵정보 데이터를 수신하는 맵데이터 정보 수신부;기상정보 수신부로부터 수신된 기상정보를 어플리케이션에서 이용되는 형식으로 변환하고 분류하는 기상정보 분류부; 기상정보 분류부에서 분류된 기상자료에 기반하여 THI를 산출하기 위한 THI 산출부; 맵데이터 정보 수신부로부터 수신된 맵 데이터에 THI 산출부에서 계산된 THI 정보를 매칭시킨 THI 맵을 생성하기 위한 THI 맵 생성부; 및 THI 맵 생성부에서 생성된 THI 맵을 어플리케이션에서 요구되는 형식을 가진 송출용 THI 데이터로 변환하여 생성하는 송출용 THI 데이터 생성부를 포함하고,상기 THI 산출부는, 기상정보 분류부에서 분류된 기상자료에 기반하여 지역별 THI를 계산하는 지역기반 THI 산출부; 기상정보 분류부에서 분류된 기상자료에 기반하여 시간대별 THI를 계산하는 시간기반 THI 계산부; 및 외기온도에 따른 THI를 계산하는 외기온도기반 THI 산출부를 포함하고,상기 THI 산출부는 기상정보 분류부에서 분류된 기상자료에 기반하여 계사의 환기 형태에 따른 THI 값을 계산하도록 구성되고,THI 맵 생성부는 맵 데이터의 지역별 THI 맵과 함께, 계사의 형태에 따른 THI 값에 기반한 컬러 속성을 갖는 THI 맵을 생성하도록 구성된 것을 특징으로 하는,산란계 온습도지수 알림 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1045/1059 Row 1045: application_number: 1020190170644, combined_string: invention_title: 닭진드기 방제를 위한 계사 내 이동식 자외선 조사장치 abstract: 본 발명은 닭진드기 방제를 위한 계사 내 이동식 자외선 조사장치를 개시한다. 본 발명은 바퀴를 구비하여 케이지 모듈의 좌우 방향으로 왕복 이동하는 이동대차; 상기 이동대차에 장착되고, UVC가 케이지 모듈의 각 층에 구비된 복수의 급이통 상측 및 계분 컨베이어 하측으로 확산되는 것을 차폐하는 확산차폐수단을 구비하여 UVC를 각 층의 급이통에서 계분 컨베이어에 이르는 부위에 조사하는 자외선 조사유닛; 상기 이동대차에 장착되고, 배터리 및 배터리에 의해 구동되는 모터를 구비하여 그 이동대차를 주행시키는 주행수단; 케이지 모듈의 적어도 한쪽 끝에 배치되고, 외부로부터 전원이 공급되어서 이동대차가 도킹함에 따라 배터리를 충전시키는 충전도크; 및 위 구성요소들의 작동을 제어하기 위한 콘트롤러;를 포함한다. 바람직하기로 이동대차가 케이지 모듈과 일정간격을 유지한 채 나란하게 주행할 수 있도록 이동대차를 유도하는 대차 가이드를 더 포함할 수 있다.본 발명은 자외선이 닭에 직접 조사되는 것을 최대한 억제하여 자외선 조사로 인해 유발되는 닭의 스트레스 등 여러 부작용을 최소화하면서 케이지에 기생하는 각종 세균과 기생충 특히 닭진드기를 효과적으로 박멸시킬 수 있다. claims: 각기 닭을 수용하는 다수의 케이지가 수평 및 수직으로 배열된 케이지 모듈을 포함하고, 상기 케이지 모듈의 각 층에 위치하는 다수의 케이지가 각각 공유하도록 복수의 급이통과 달걀받이를 수평으로 길게 가지며, 각 층의 케이지 하부에 계분 컨베이어를 갖는 양계장에 있어서,바퀴를 구비하여 상기 케이지 모듈의 좌우 방향으로 왕복 이동하는 이동대차;상기 이동대차에 장착되고, UVC가 상기 케이지 모듈의 각 층에 구비된 복수의 급이통 상측과 계분 컨베이어 하측으로 확산되는 것을 차폐하는 확산차폐수단을 구비하여 UVC를 각 층의 급이통에서 계분 컨베이어에 이르는 부위에 조사하는 자외선 조사유닛;상기 이동대차에 장착되고, 배터리 및 상기 배터리에 의해 구동되는 모터를 구비하여 그 이동대차를 주행시키는 주행수단;상기 케이지 모듈의 적어도 한쪽 끝에 배치되고, 외부로부터 전원이 공급되어서 상기 이동대차가 도킹함에 따라 상기 배터리를 충전시키는 충전도크; 및상기 구성요소들의 작동을 제어하기 위한 콘트롤러;를 포함하는 것을 특징으로 하는 닭진드기 방제를 위한 계사 내 이동식 자외선 조사장치., Ltext: 농업, prediction: 임업
1046/1059 Row 1046: application_number: 1020190161700, combined_string: invention_title: 미세조절이 가능한 체인식 모이공급장치 abstract: 본 발명은 닭을 사육하는 케이지의 모이공급시스템에 설치되어 닭들에게 모이를 공급할 때 모이의 양을 미세하게 조절할 수 있고 정확한 양을 공급할 수 있도록 개선된 미세조정이 가능한 체인식 모이공급장치를 개시한다. claims: 여러 개가 연속되게 설치되고 닭들이 사육되는 케이지와, 양측과 바닥면이 막혀 있고 상면이 개구된 덕트 형상으로 형성되어 내부에 모이통로가 형성되고 케이지를 따라 순환 형태로 설치되어 각 케이지에 모이를 공급할 수 있게 설치된 모이통과, 모이통의 일부분이 내부를 관통하게 설치되어 공급되는 모이를 모이통의 상면 일부분으로 안내하는 호퍼와, 모이통의 내부를 따라 순환 이송되게 설치된 모이이송체인과, 모이이송체인을 순환 이송시키는 체인작동수단으로 이루어져, 호퍼로 모이를 공급하면 호퍼를 관통하는 모이통의 일부분으로 모이가 안내되고 모이이송체인이 순환 이송되면서 모이를 끌고가 모이통을 따라 전체적으로 모이를 공급하게 구성된 케이지의 모이공급시스템에 설치되는 것으로,상기 호퍼의 정면에서 모이통보다 상부에 고정되게 설치되고, 상단에는 정면 방향으로 고정절곡편이 절곡 형성되며, 고정절곡편의 중간에는 볼트관통공이 관통 형성된 고정판과,상기 고정판의 정면 좌측에 고정되게 설치되고, 우측 단부에는 정면으로 절곡되는 좌측가이드편이 형성되어 고정판과 좌측가이드편의 사이에 좌측가이드홈이 형성된 구조를 갖는 좌측브라켓과,상기 고정판의 정면 우측에서 고정되게 설치되고, 좌측 단부에는 정면으로 절곡되는 우측가이드편이 형성되어 고정판과 우측가이드편의 사이에 우측가이드홈이 형성된 구조를 갖는 우측브라켓과,상기 고정판의 정면에 밀착되게 설치되고, 양단이 좌측가이드홈과 우측가이드홈을 따라 삽입되어 상하로 위치조절할 수 있게 설치되며, 하강했을 때 모이통의 모이통로 내부로 삽입되어 모이통로를 차단하게 설치되고, 상단에는 정면 방향으로 조절절곡편이 절곡 형성되며, 조절절곡편의 중간에는 볼트관통공과 대응되는 볼트조립공이 관통 형성된 조절판과,상기 조절절곡편의 볼트조립공과 고정절곡편의 볼트관통공을 관통하도록 조립되고, 볼트머리가 조절절곡편의 하면에 밀착되어 조절판을 받쳐 지지하도록 설치된 고정볼트와,상기 고정볼트의 볼트머리와 근접하게 체결되고, 조절절곡편의 상면에 밀착되게 고정됨으로 볼트머리와의 협동에 의해 고정볼트를 조절절곡편에 고정시키는 볼트고정너트와,상기 고정볼트의 단부에 체결되어 고정절곡편의 상면에 밀착되게 설치되며, 회전 방향에 따라 고정볼트를 승하강시키면서 조절판을 함께 승하강시키는 조절판조절너트와,상기 고정절곡편과 조절절곡편의 사이에서 고정볼트에 체결되는 스프링조절너트와,상기 고정절곡편과 스프링조절너트의 사이에서 고정볼트에 삽입되게 조립되어 고정절곡편을 탄성 가압하게 설치된 공극조절스프링으로 구성되어,상기 조절판조절너트를 조이고 풀면 고정볼트가 상승 또는 하강하면서 조절판의 위치가 조절되어 조절판과 모이이송체인 사이의 공극이 조절되어 공급되는 모이의 양을 조절하게 되고, 좌측브라켓과 우측브라켓을 통해 조절판이 좌우로 흔들리지 않도록 하며, 스프링조절너트를 조이고 풀면서 공극조절스프링의 압축력을 조절하여 조절판이 상하로 움직일 때 그 압력을 조절할 수 있게 구성되며,상기 조절판과 대응되는 모이통의 모이통로 바닥면에는 체인하강방지판이 추가로 고정되게 설치되어 모이이송체인이 조절판과 대응되는 부분을 통과할 때 체인하강방지판에 올려져 하부로 움직이는 것을 방지함으로 모이이송체인이 흔들리지 않고 체인하강방지판을 따라 평행하게 이동할 수 있게 구성함으로,상기 모이이송체인이 조절판의 하부를 통과할 때 조절판과 모이이송체인 사이의 공극이 일정하게 유지되도록 구성된 것을 특징으로 하는 미세조절이 가능한 체인식 모이공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1047/1059 Row 1047: application_number: 1020190161483, combined_string: invention_title: 닭의 대흉근으로부터 확립된 근아섬유세포주 및 이를 이용한 생리활성물질 스크리닝 방법 abstract: 본 발명은 닭의 대흉근으로부터 확립된 근아섬유세포주를 이용하여 생리활성을 나타내는 물질을 스크리닝하는 방법에 관한 것으로, 상기 닭의 대흉근으로부터 확립된 근아섬유세포주에 생리활성 후보물질로서 당귀 및 당귀 부산물 추출물을 처리한 후 비처리 대조군 근아섬유세포주와 유전자 발현 수준을 비교한 결과, 당귀 및 당귀 부산물 추출물은 세포증식, 근육분화 (myogenesis), 지방생성 (adipogenesis) 또는 당대사 (glycometabolism)를 조절하는 유전자의 발현 수준을 증가 또는 감소시키는 생리활성이 확인됨에 따라, 상기 닭의 대흉근으로부터 확립된 근아섬유세포주를 이용한 스크리닝 방법은 가축 사료첨가제 또는 생리활성물질 선별을 위한 시험관내 (in vitro) 스크리닝 방법으로 제공될 수 있다. claims: 닭의 대흉근으로부터 확립된 근아섬유세포주 (KCLRF-BP-00410).청구항 1에 있어서, 상기 닭의 대흉근으로부터 확립된 근아섬유세포주는 10일령 수컷 병아리 배아의 대흉근으로부터 분리 및 배양된 것을 특징으로 하는 근아섬유세포주.닭의 대흉근으로부터 확립된 근아섬유세포주 (KCLRF-BP-00410)에 생리활성 조절용 후보물질을 처리하는 단계; 상기 후보물질이 처리된 근아섬유세포주의 유전자 발현 수준을 확인하는 단계; 및상기 확인된 유전자 발현 수준을 비처리 대조군과 비교하는 단계를 포함하는 생리활성물질 스크리닝 방법.닭의 대흉근으로부터 확립된 근아섬유세포주 (KCLRF-BP-00410)에 근육분화용 후보물질을 처리하는 단계; 상기 후보물질이 처리된 근아섬유세포주의 유전자 발현 수준을 확인하는 단계; 및상기 확인된 유전자 발현 수준을 비처리 대조군과 비교하는 단계를 포함하는 근육분화 조절제 스크리닝 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1048/1059 Row 1048: application_number: 1020190159831, combined_string: invention_title: 행동패턴 이상 징후 판별 시스템 및 이의 제공방법 abstract: 본 발명의 실시예에 따른 행동패턴 이상 징후 판별 시스템은, 영상센서를 통해 실시간으로 수집되는 영상데이터를 입력 받는 영상수집부; 상기 영상데이터로부터 관심 객체를 검출하기 위하여 영상처리하는 영상처리부; 상기 영상처리된 영상데이터로부터 상기 관심 객체의 행동패턴 특징을 추출하는 행동패턴 추출부; 상기 추출된 행동패턴 특징을 이용하여 상기 관심 객체의 행동패턴을 학습하여 모델링하는 행동패턴 모델링부 및 상기 모델링된 행동패턴을 분석하여 상기 관심 객체의 행동이상 발생 여부를 판단하는 행동이상 판별부를 포함하고, 상기 행동이상 모델링부는 텐서플로우로 학습하여 모델링되고, 상기 행동이상 판별부는, 상기 행동패턴 추출부로부터 행동패턴 특징을 전달받아 관심 객체의 위상과 크기에 대한 정보를 변환하여 주파수의 그래프를 영상정보화한 패턴을 확보하는 FFT변환부; 상기 주파수의 그래프를 영상정보화한 패턴에 대해 실시간으로 딥마인드 판별을 하는 딥마인드판별부를 포함하는 행동패턴 이상 징후 판별 시스템을 제공할 수 있다. claims: 행동패턴 이상 징후 판별 시스템에 있어서,영상센서를 통해 실시간으로 수집되는 영상데이터를 입력 받는 영상수집부;상기 영상데이터로부터 관심 객체를 검출하기 위하여 영상처리하는 영상처리부;상기 영상처리된 영상데이터로부터 상기 관심 객체의 행동패턴 특징을 추출하는 행동패턴 추출부;상기 추출된 행동패턴 특징을 이용하여 상기 관심 객체의 행동패턴을 학습하여 모델링하는 행동패턴 모델링부 및상기 모델링된 행동패턴을 분석하여 상기 관심 객체의 행동이상 발생 여부를 판단하는 행동이상 판별부를 포함하고,상기 행동패턴 모델링부는 텐서플로우로 학습하여 모델링되고,상기 행동이상 판별부는, 상기 행동패턴 추출부로부터 행동패턴 특징을 전달받아 관심 객체의 위상과 크기에 대한 정보를 변환하여 주파수의 그래프를 영상정보화한 패턴을 확보하는 FFT변환부;상기 주파수의 그래프를 영상정보화한 패턴에 대해 실시간으로 딥마인드 판별을 하는 딥마인드판별부를 포함하고,상기 행동패턴 이상 징후 판별 시스템은,상기 행동이상 판별부의 판단에 따라 행동이상의 발생 감지시 정밀검사 의뢰를 요청하는 정밀검사요청부 및관리자 단말로 관심 객체의 행동이상 발생 여부에 관한 정보를 전송하는 알림부를 더 포함하며,상기 영상처리부는,일정 단위 시간 동안 입력된 영상데이터를 이용하여 고정된 화각과 위치를 유지한 영상수집부를 이용해 획득된 영상데이터의 프레임간의 수학적 연산에 의한 정적 화상 정보와 동적 화상 정보를 분리하는 방식을 통해 구분된 영상정보로부터 주위 모델링을 수행하고, 상기 주위 모델링을 통해 학습된 주위 모델을 이용하여 관심 객체를 검출하는 방식으로 영상처리를 진행하고,상기 행동패턴 추출부는,상기 영상데이터를 좌표가 설정된 셀(Cell)단위의 그리드 영역으로 분할하여 구분하고, 분할한 각 영역에서 관심 객체들의 행동패턴 정보를 추출하고, 초당 프레임을 기준으로 움직임 속도와 거리를 산정하며,상기 관심 객체는 닭인 것을 특징으로 하는 행동패턴 이상 징후 판별 시스템.행동패턴 이상 징후 판별 시스템 제공방법에 있어서,(a) 영상센서를 통해 실시간으로 촬영하여 영상데이터를 수집하는 단계;(b) 수집된 영상데이터를 영상처리 하여 관심 객체를 검출하는 단계;(c) 상기 검출된 관심 객체의 행동패턴 특징을 검출하는 단계;(d) 상기 검출된 행동패턴 특징을 이용하여 관심 객체의 행동패턴을 모델링하는 단계 및(e) 상기 모델링된 행동패턴을 분석하여 행동이상 발생 여부를 판단하는 단계를 포함하고,상기 (d)단계는,텐서플로우로 학습하여 모델링되고,상기 (e)단계는,상기 행동패턴 특징으로부터 관심 객체의 위상과 크기에 대한 정보를 변환하여 주파수의 그래프를 영상정보화한 패턴을 확보하기 위해 FFT변환을 진행하는 단계;상기 주파수의 그래프를 영상정보화한 패턴에 대해 실시간으로 딥마인드 판별을 진행하는 단계;상기 딥마인드 판별을 통해 행동이상 발생 여부에 관한 판별결과를 검출하는 단계를 포함하고,상기 (e)단계 이후에,행동이상의 발생 감지시 정밀검사 의뢰를 요청하는 단계를 더 포함하고,상기 행동패턴 이상 징후 판별 시스템 제공방법은,관리자 단말로 관심 객체의 행동이상 발생 여부에 관한 정보를 전송하는 단계를 더 포함하며,상기 (b) 단계는,영상처리부가 일정 단위 시간 동안 입력된 영상데이터를 이용하여 고정된 화각과 위치를 유지한 영상수집부를 이용해 획득된 영상데이터의 프레임간의 수학적 연산에 의한 정적 화상 정보와 동적 화상 정보를 분리하는 방식을 통해 구분된 영상정보로부터 주위 모델링을 수행하고, 상기 주위 모델링을 통해 학습된 주위 모델을 이용하여 관심 객체를 검출하는 방식으로 영상처리를 진행하고,상기 (c)단계는,상기 영상데이터를 좌표가 설정된 셀(Cell)단위의 그리드 영역으로 분할하여 구분하고, 분할한 각 영역에서 관심 객체들의 행동패턴 정보를 추출하고, 초당 프레임을 기준으로 움직임 속도와 거리를 산정하며,상기 관심 객체는 닭인 것을 특징으로 하는 행동패턴 이상 징후 판별 시스템 제공방법., Ltext: 농업, prediction: 임업
1049/1059 Row 1049: application_number: 1020190159395, combined_string: invention_title: 케이지식 계사에서 닭진드기 유인물질을 활용한 닭진드기 모니터링용 유인트랩 및 이를 이용한 닭진드기 감염 여부를 확인하는 방법 abstract: 본 발명은 케이지식 계사에서 닭진드기 유인물질을 활용한 닭진드기 모니터링용 유인트랩에 관한 것으로, 본 발명의 계사에 떨어진 닭 깃털을 유인물질로 활용한 닭진드기 모니터링용 유인트랩은 농가에서 쉽게 활용할 수 있는 소재를 이용하여 제작할 수 있고, 18시간 이상 유인트랩 설치 시 신속하고 유의미하게 계사 내에서 닭진드기 감염여부를 판단할 수 있어 농가에서 감염 초기의 닭진드기 방제 시기를 놓칠 위험을 줄임으로써 산란계 농가의 닭진드기 방제 전략을 구상하는데 활용할 수 있다. claims: 1) 닭진드기 모니터링용 유인트랩을 모니터링 대상 계사에 설치하여 기설정된 시간 동안 닭진드기를 포획하는 설치 및 포획 단계;2) 상기 기설정된 시간 경과 후에 상기 닭진드기 모니터링용 유인트랩을 수거하여 포획된 닭진드기를 확인하는 수거 및 확인 단계; 및3) 상기 모니터링 대상 계사의 감염 여부를 판단하는 판단 단계를 포함하는 것을 특징으로 하는 케이지식 계사에서의 닭진드기 감염 여부를 확인하는 방법.닭진드기 유인용 물질을 포함하는 닭진드기 모니터링용 유인트랩., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1050/1059 Row 1050: application_number: 1020190154078, combined_string: invention_title: 가압방식 파각란 판별장치 abstract: 본 발명은 가압방식 파각란 판별장치에 관한 것으로, 계란판(T)이 안치되는 하부 베이스(10)와; 상기 하부 베이스(10)의 상부에서 승강되며 계란판(T)에 안치된 복수의 계란(E) 상부를 각각 누르되 각각 압축코일스프링(22)의 탄성으로 지지되어 파각란(E1)의 경우에는 압축코일스프링(22)의 압축력보다 약한 힘에 의해 눌려 파손되고, 정상란(E2)의 경우에는 압축코일스프링(22)이 압축되면서 상방으로 밀려 정상란(E2)이 파손되지 않도록 된 가압구(20)가 종횡으로 배치된 상부 가압판(30)과; 상기 상부 가압판(30)을 승강시키는 유압실린더(40)와; 상기 유압실린더(40)를 승강 조작하기 위한 조작스위치(50);를 포함하여 이루어져 있다. claims: 계란판(T)이 안치되는 하부 베이스(10)와;상기 하부 베이스(10)의 상부에서 승강되며 계란판(T)에 안치된 복수의 계란(E) 상부를 각각 누르되 각각 압축코일스프링(22)의 탄성으로 지지되어 파각란(E1)의 경우에는 압축코일스프링(22)의 압축력보다 약한 힘에 의해 눌려 파손되고, 정상란(E2)의 경우에는 압축코일스프링(22)이 압축되면서 상방으로 밀려 정상란(E2)이 파손되지 않도록 된 가압구(20)가 종횡으로 배치된 상부 가압판(30)과;상기 상부 가압판(30)을 승강시키는 유압실린더(40)와;상기 유압실린더(40)를 승강 조작하기 위한 조작스위치(50);를 포함하여 이루어지는 것을 특징으로 하는 가압방식 파각란 판별장치.청구항 1에 있어서.상기 상부 가압판(30)의 전방에는 작업자의 손이나 기타 장애물이 판별장치 내부에 있을 때 조작스위치(50)를 밟더라도 하강이 이루어지지 않도록 하기 위한 안전 센서(70)가 더 구비된 것을 특징으로 하는 가압방식 파각란 판별장치., Ltext: 농업, prediction: 임업
1051/1059 Row 1051: application_number: 1020190148983, combined_string: invention_title: 소리가 발생하는 가축용 음수 공급장치 abstract: 본 발명은 소리가 발생하는 가축용 음수 공급장치에 있어서, 급수공급라인에 분기 형성되는 적어도 하나 이상의 분기관, 상기 분기관에 연결되는 분기관 연결구를 가지며 내부에는 상기 분기관을 통해 공급된 음수가 저장되는 챔버가 마련된 밸브본체, 상기 밸브본체의 하단에 연결되며 상기 챔버로 공급된 음수를 워터컵으로 배출하는 배출관, 상기 밸브본체의 상단에 연결 설치되는 결합관, 상기 결합관의 선단에 삽입되며 중앙으로는 공기를 통과시키는 공기구멍이 형성되어, 상기 챔버에 저장된 음수가 배출되는 과정에서 발생한 기압 차이에 의해 상기 공기구멍을 통해 공기가 상기 챔버로 흡입 또는 배출되는 과정에서 특정음의 소리를 발생시키는 소리발생관을 포함하여 구성함을 특징으로 하는 소리가 발생하는 가축용 음수 공급장치를 제공한다. claims: 소리가 발생하는 가축용 음수 공급장치에 있어서,급수공급라인(10)에 분기 형성되는 적어도 하나 이상의 분기관(20);상기 분기관(20)에 연결되는 분기관 연결구(34)를 가지며 내부에는 상기 분기관(20)을 통해 공급된 음수가 저장되는 챔버(33)가 마련된 밸브본체(32);상기 밸브본체(32)의 하단에 연결되며 상기 챔버(33)로 공급된 음수를 워터컵(16)으로 배출하는 배출관(14);상기 밸브본체(32)의 상단에 연결 설치되는 결합관(50);상기 결합관(50)의 선단에 삽입되며 중앙으로는 공기를 통과시키는 공기구멍(62)이 형성되어, 상기 챔버(33)에 저장된 음수가 배출되는 과정에서 발생한 기압 차이에 의해 상기 공기구멍(62)을 통해 공기가 상기 챔버(33)로 흡입 또는 배출되는 과정에서 특정음의 소리를 발생시키는 소리발생관(60)을 포함하여 구성함을 특징으로 하는 소리가 발생하는 가축용 음수 공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1052/1059 Row 1052: application_number: 1020190118397, combined_string: invention_title: 구기자를 이용한 고품질 가축류의 사육방법 abstract: 본 발명은 구기자를 이용한 고품질 가축류의 사육방법으로(a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 일반 가축류 급여용 사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 1kg~10kg을 혼합하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가축류 출하전 60일~180일간 급여하여 사육하는 단계; (j) 상기(i)단계의 사육과정을 통하여 사육된 가축류를 출하하여 제품화하는 단계를 포함하여 이루어진다. claims: (a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 일반 가축류 급여용 사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 1kg~10kg을 혼합하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가축류 출하전 60일~180일간 급여하여 사육하는 단계; (j) 상기(i)단계의 사육과정을 통하여 사육된 가축류를 출하하여 제품화하는 단계를 포함하는 것을 특징으로 하는 구기자를 이용한 고품질 가축류의 사육방법.제1항의 사육방법에 의하여 생산된 가축의 육류., Ltext: 농업, prediction: 임업
1053/1059 Row 1053: application_number: 1020190115919, combined_string: invention_title: 계사 내 진드기 포획장치 및 포획장치 관리시스템 abstract: 본 발명은 계사 내 진드기 포획장치 및 포획장치 관리시스템에 관한 것이다. 이는, 일정두께의 시트 형태를 취하는 가요성 베이스층, 상기 베이스층에 적층되며 내부로 파고 들어온 진드기를 잡아 포획하는 다공성 포획층을 구비하고, 계사에 설치된 상태로 주변 진드기를 유도 포획하는 포획시트와; 상기 포획시트와 함께 사용하는 것으로서, 상기 포획시트의 무게 변화를 감지하고 감지 내용을 외부로 전달하는 검출수단을 포함한다.상기와 같이 이루어지는 본 발명의 계사 내 진드기 포획장치는, 닭에 기생하는 진드기를 효과적으로 유인 및 포획할 수 있으며, 진드기의 호흡에 의한 온도변화나 무게변화를 감지하여 외부로 전송하므로 원격 제어를 가능하게 한다. 또한, 본 발명의 포획장치 관리시스템은, 다수의 포획장치와 무선 연결되며 포획장치에서 감지된 진드기의 개체수 정보를 기초로 포획장치의 교체 여부를 판단할 수 있으므로 전체적인 관리가 용이하다. claims: 일정두께의 시트 형태를 취하는 가요성 베이스층, 상기 베이스층에 적층되며 내부로 파고 들어온 진드기를 잡아 포획하는 다공성 포획층을 구비하고, 계사에 설치된 상태로 주변 진드기를 유도 포획하는 포획시트와;상기 포획시트와 함께 사용하는 것으로서, 상기 포획시트의 무게 변화를 감지하고 감지 내용을 외부로 전달하는 검출수단을 포함하는 계사 내 진드기 포획장치.일정두께의 시트 형태를 취하는 가요성 베이스층, 상기 베이스층에 적층되며 내부로 파고 들어온 진드기를 잡아 포획하는 다공성 포획층을 구비하고, 계사에 설치된 상태로 주변 진드기를 유도 포획하는 다수의 포획시트와;상기 포획시트와 함께 사용하는 것으로서, 각 포획시트의 무게 변화를 감지하고 감지 내용을 외부로 전달하는 검출수단과; 상기 검출수단을 통해 개별 포획시트의 무게 데이터를 전달받으며, 설정된 무게 기준에 기초하여, 교체할 포획시트를 찾아내는 제어부를 구비하는 포획장치 관리시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1054/1059 Row 1054: application_number: 1020190115691, combined_string: invention_title: 그룹별 축산물 생애 정보 제공 시스템 abstract: 본 발명은 그룹별 축산물 생애 정보 제공 시스템에 관한 것으로서, 보다 구체적으로는 정보 제공 시스템으로서, 정보 제공 시스템으로서, 가축 및 가금을 포함하는 축산물에 대한 정보를 제공하되, 서로 관계있는 복수의 축산물을 그룹화하여 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 관리 및 제공하는 정보 제공 서버; 및 상기 축산물의 식별정보를 인식하고, 인식한 식별정보를 상기 정보 제공 서버에 전송하여 상기 축산물에 대한 데이터 제공 요청을 하는 소비자 디바이스를 포함하며, 상기 소비자 디바이스는, 상기 축산물의 식별정보를 인식하는 인식 모듈; 상기 정보 제공 서버에 상기 식별정보를 전달하고, 상기 식별정보에 대응되는 축산물의 데이터 제공 요청을 하는 정보 요청 모듈; 및 상기 정보 제공 서버로부터 수신한 축산물 생애 정보를 출력하는 출력 모듈을 포함하는 것을 그 구성상의 특징으로 한다.가축 및 가금을 포함하는 축산물에 대한 정보를 제공하는 정보 제공 서버; 및 상기 축산물의 식별정보를 인식하고, 인식한 식별정보를 상기 정보 제공 서버에 전송하여 상기 축산물에 대한 데이터 제공 요청을 하는 소비자 디바이스를 포함하며, 상기 정보 제공 서버는, 서로 관계있는 복수의 축산물을 그룹화하고, 그룹화 한 그룹별로 식별정보를 할당하는 그룹화 모듈; 상기 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 저장하는 데이터베이스 모듈; 상기 그룹별로 축산물이 사육되는 농가의 축사 관리 기록, 축산물의 진료 또는 치료 정보, 및 측정 정보를 포함하는 건강관리 정보를 수집하는 제1 정보 수집 모듈; 상기 그룹별로 축산물이 사육되는 농가 또는 축사의 주변 환경 정보를 포함하는 사육 환경 정보를 수집하는 제2 정보 수집 모듈; 및 상기 소비자 디바이스의 데이터 제공 요청에 대응하여, 상기 소비자 디바이스로부터 수신한 식별정보에 대응하는 그룹의 축산물 생애 정보를 상기 데이터베이스 모듈에서 검색하며, 상기 검색된 그룹의 축산물 생애 정보를 제공하는 데이터 제공 모듈을 포함하며, 상기 소비자 디바이스는, 축산물의 패키지로부터 식별정보를 인식하여 상기 데이터 제공 요청을 하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 그룹별 축산물 생애 정보 제공 시스템에 따르면, 축산물을 그룹화하고 그룹별로 축산물 생애 정보를 제공함으로써, 도축 후의 정보인 이력제 정보와는 상이한, 축산물의 생애와 관련된 다양한 정보를 효율적으로 소비자에게 제공할 수 있고, 동일한 날 하나의 모체에서 생산된 복수의 자체, 또는 하나의 그룹으로 관리되는 복수의 모체에서 생산된 출생일이 유사한 복수의 자체를 그룹화 함으로써, 농가에서 그룹별로 효율적인 축산물 관리를 하면서도, 정확도가 높은 축산물 생애 정보를 소비자에게 제공할 수 있다.또한, 본 발명에 따르면, 축산물 이력제와 연동하여, 소비자 디바이스에서 인식한 식별정보가 축산물 이력제에 따른 이력번호이면, 정보 제공 서버에서 제공하는 축산물 생애 정보와 함께, 도축 후부터 포장, 유통 단계와 관련된 축산물 이력제에 따른 이력 정보를 소비자 디바이스로 출력함으로써, 한 번의 식별정보 인식을 통해 축산물의 출생, 모체 정보, 건강, 사육 환경, 도축, 포장, 및 유통까지 전 과정에 대한 다양한 정보를 쉽게 확인할 수 있다.뿐만 아니라, 본 발명에 따르면, 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 저장하고, 소비자 디바이스의 데이터 제공 요청에 대응하여 그룹의 축산물 생애 정보를 시각화하여 제공함으로써, 축산물 생애와 관련된 다양한 정보를 이해하기 쉽게 소비자에게 제공할 수 있고, 통신망 및 소비자 디바이스를 이용해 정보의 양에 대한 제한 없이 건강한 먹거리와 직결되는 실질적이고 다양한 정보를 쉽게 제공하며, 소비자들이 안심하고 축산물을 선택할 수 있도록 하여 축산물에 대한 소비자 신뢰도를 향상시킬 수 있다. claims: 정보 제공 시스템으로서,가축 및 가금을 포함하는 축산물에 대한 정보를 제공하되, 서로 관계있는 복수의 축산물을 그룹화하여 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 관리하고, 상기 축산물 생애 정보를 소비자에게 제공하는 정보 제공 서버(100); 및상기 축산물의 식별정보를 인식하고, 인식한 식별정보를 상기 정보 제공 서버(100)에 전송하여 상기 축산물에 대한 데이터 제공 요청을 하되, 소비자용 애플리케이션(201)이 설치 및 구동되고, 상기 소비자용 애플리케이션(201)을 이용해 축산물의 패키지나 리포트에 포함된 식별번호를 인식해 상기 정보 제공 서버(100)에 데이터 제공 요청을 하는 소비자 디바이스(200)를 포함하며,상기 소비자 디바이스(200)는,상기 축산물의 식별정보를 인식하는 인식 모듈(210);상기 정보 제공 서버(100)에 상기 식별정보를 전달하고, 상기 식별정보에 대응되는 축산물의 데이터 제공 요청을 하는 정보 요청 모듈(220);상기 인식 모듈(210)에서 인식된 식별정보를 조회하는 번호 조회 모듈(230);상기 번호 조회 모듈(230)의 조회 결과, 상기 식별정보가 축산물 이력제에 따른 이력번호이면, 상기 이력번호를 이용해 해당 축산물의 축산물 이력제에 따른 이력 정보를 검색하는 이력제 검색 모듈(240); 및상기 정보 제공 서버(100)로부터 수신한 축산물 생애 정보를 출력하며, 상기 이력제 검색 모듈(240)의 검색에 따른 이력 정보를 더 출력하는 출력 모듈(250)을 포함하고,상기 정보 제공 서버(100)는,축산물 이력제 시스템과 연동하여, 상기 이력번호와 그룹별 식별정보를 연동하여 관리하되, 상기 이력번호와 그룹별 식별번호를 매칭 테이블로 관리하여, 상기 소비자 디바이스(200)에서 인식된 식별정보가 이력번호인지 그룹별 식별정보인지에 관계없이 축산물 생애 정보를 검색하여 제공할 수 있으며,상기 정보 제공 서버(100)는,서로 관계있는 복수의 축산물을 그룹화하되, 동일한 날 하나의 모체에서 생산된 복수의 자체, 또는 하나의 그룹으로 관리되는 복수의 모체에서 미리 정해진 기간 내에 출생한 복수의 자체를 그룹화하고, 그룹화 한 그룹별로 식별정보를 할당하는 그룹화 모듈(110);상기 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 저장하는 데이터베이스 모듈(120);상기 그룹별로 축산물이 사육되는 농가의 축사 관리 기록, 축산물의 진료 또는 치료 정보, 및 측정 정보를 포함하는 건강관리 정보를 수집하는 제1 정보 수집 모듈(130);상기 그룹별로 축산물이 사육되는 농가 또는 축사의 주변 환경 정보를 포함하는 사육 환경 정보를 수집하는 제2 정보 수집 모듈(140);상기 데이터베이스 모듈(120)에 저장된 축산물 생애 정보를 데이터 마이닝하여 축산물 생애 정보에 포함되는 정보 사이의 상관관계를 분석하며, 데이터 마이닝 기술을 통해 미리 정해진 개수의 등급으로 분류하여 각 분야별 축산물의 등급을 산정하는 데이터 분석 모듈(160); 및상기 소비자 디바이스(200)의 데이터 제공 요청에 대응하여, 상기 소비자 디바이스(200)로부터 수신한 식별정보에 대응하는 그룹의 축산물 생애 정보를 상기 데이터베이스 모듈(120)에서 검색하며, 상기 검색된 그룹의 축산물 생애 정보를 제공하는 데이터 제공 모듈(170)을 포함하며,상기 데이터 제공 모듈(170)은,상기 수신한 식별정보에 대응하는 그룹의 축산물을 생산한 모체 또는 분만일이 미리 정해진 기간 내인 모체 그룹을 매칭하여, 매칭된 모체 또는 모체 그룹의 축산물 생애 정보 및 상기 검색된 그룹의 축산물 생애 정보를 제공하는 것을 특징으로 하는, 그룹별 축산물 생애 정보 제공 시스템., Ltext: 농업, prediction: 임업
1055/1059 Row 1055: application_number: 1020190104646, combined_string: invention_title: 이동식 자연채광 스마트 계사 (소규모사육) abstract: 1. 소규모 사육(100수단위)에 대한 최적화 환경 제공.2. 컨테이너 프레임으로 제작되어 이동이 가능함.3. IoT 구축으로 양계종사자들에게 편의성 제공.4. 맹지 등의 오지(전기,수도,지하수불가지역)에서도 육계, 산란계 사육가능(태양열 집전판 설치)5. 울타리 설치시 계사와 연동으로 방사환경 조성. claims: 자연채광을 제공하는 *PC 지붕층 컨테이너 프레임의 이동식 형태. 계사 자체 소모전력을 자가공급하는 방식의 제작형태에 대한 유사제작방지* PC : 폴리카보네이트, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1056/1059 Row 1056: application_number: 1020190101443, combined_string: invention_title: 자동산란장치 abstract: 본 발명은 닭의 산란 환경을 조성하고 달걀 수거를 자동으로 진행할 수 있는 자동산란장치에 대한 것이며, 구체적으로 닭이 진입하여 산란하는 산란부와 산란부에 진입한 닭의 산란 환경을 조성하기 위한 산란유도부와 산란부의 하단에 형성되며, 바닥재를 수거하여 재생하는 바닥재수거부와 닭이 산란한 달걀을 수거하는 달걀수거부를 구비한다. claims: 닭이 진입하여 산란하는 산란부(100);,상기 산란부(100)에 진입한 닭의 산란 환경을 조성하기 위한 산란유도부(200);,상기 산란부(100)의 하단에 형성되며, 바닥재(20)를 수거하여 재생하는 바닥재수거부(300);닭이 산란한 달걀(10)을 수거하는 달걀수거부(400);를 포함하는 자동산란장치., Ltext: 농업, prediction: 임업
1057/1059 Row 1057: application_number: 1020190101249, combined_string: invention_title: 스마트 달걀 트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 장치 및 방법 abstract: 본 발명의 일 실시예에 따라, 서버에 의해 수행되는, 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법에 있어서, (a) 달걀 트레이로부터 부족한 달걀의 개수를 수신하는 단계; (b) 달걀의 판매가 가능한 양계장 리스트를 사용자 단말로 제공하는 단계; (c) 사용자 단말이 선택한 양계장에 대응하는 양계장의 공급자 단말로 부족한 달걀의 개수만큼 주문요청을 전송하고, 공급자 단말로부터 사용자에게 배송될 달걀 이미지를 수신하는 단계; 및 (d) 달걀 이미지를 사용자 단말로 제공하고, 공급자 단말 또는 사용자 단말을 통해 수집한 유통기한 관련정보를 참고하여, 사용자 단말로 달걀이 주문된 이후, 기 설정된 시간 경과 시 달걀 트레이 내의 달걀에 대한 유통기한 알람메시지를 제공하는 단계를 포함된다. claims: 서버에 의해 수행되는, 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법에 있어서,(a) 달걀 트레이로부터 부족한 달걀의 개수를 수신하는 단계;(b) 달걀의 판매가 가능한 양계장 리스트를 사용자 단말로 제공하는 단계; (c) 상기 사용자 단말이 선택한 양계장에 대응하는 양계장의 공급자 단말로 상기 부족한 달걀의 개수만큼 주문요청을 전송하고, 상기 공급자 단말로부터 사용자에게 배송될 달걀 이미지를 수신하는 단계; 및(d) 상기 달걀 이미지를 사용자 단말로 제공하고, 상기 공급자 단말 또는 상기 사용자 단말을 통해 수집한 유통기한 관련정보를 참고하여, 상기 사용자 단말로 달걀이 주문된 이후, 기 설정된 시간 경과 시 달걀 트레이 내의 달걀에 대한 유통기한 알람메시지를 제공하는 단계를 포함하는 것인, 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법.스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 장치에 있어서,스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법을 제공하는 프로그램이 저장된 메모리 및상기 메모리에 저장된 프로그램을 실행하여 상기 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법을 제공하는 프로세서를 포함하되,상기 프로세서는 달걀 트레이로부터 부족한 달걀의 개수를 수신하고, 달걀의 판매가 가능한 양계장 리스트를 사용자 단말로 제공하고, 상기 사용자 단말이 선택한 양계장에 대응하는 양계장의 공급자 단말로 상기 부족한 달걀의 개수만큼 주문요청을 전송하고, 상기 공급자 단말로부터 사용자에게 배송될 달걀 이미지를 수신하고, 상기 달걀 이미지를 사용자 단말로 제공하고, 상기 공급자 단말 또는 상기 사용자 단말을 통해 수집한 유통기한 관련정보를 참고하여, 상기 사용자 단말로 달걀이 주문된 이후, 기 설정된 시간 경과 시 달걀 트레이 내의 달걀에 대한 유통기한 알람메시지를 제공하는, 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 장치.제 1 항에 의한 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법을 수행하기 위한 프로그램이 기록된 컴퓨터 판독가능 저장매체., Ltext: 농업, prediction: 임업
1058/1059 Row 1058: application_number: 1020190093961, combined_string: invention_title: 종계 음수 첨가용 티백조성물의 제조방법 abstract: 본 발명은 종계 음수 첨가용 티백조성물의 제조방법에 관한 것으로, 동애등에 유충에게 사료를 급여하는 단계(단계 1); 동애등에 성충에게 미생물수를 급여하는 단계(단계 2); 상기 사료를 먹고 사육된 동애등에 번데기 및 상기 미생물수를 먹고 사육된 동애등에 성충을 혼합하여 제1 혼합물을 만든 후 분말화하는 단계(단계 3); 상기 사료를 먹고 사육된 동애등에 번데기 및 미강을 혼합하여 제2 혼합물을 만든 후 건조하는 단계(단계 4); 상기 건조된 제2 혼합물 및 상기 분말화한 제1 혼합물을 혼합하여 제3 혼합물을 만든 후 발효시키는 단계(단계 5); 상기 발효물을 건조하는 단계(단계 6); 및 상기 건조된 발효물을 티백포장하는 단계(단계 7); 를 포함하는 것을 기술적 특징으로 하며, 동애등에를 이용한 종계 음수 첨가용 티백조성물을 음수에 투입하고 종계에 급여함으로써 양계장에서 사육되는 종계의 체중을 표준매뉴얼의 체중에 부합하도록 조절할 수 있는 장점이 있다. claims: 동애등에 유충에게 사료를 급여하는 단계(단계 1);동애등에 성충에게 미생물수를 급여하는 단계(단계 2);상기 사료를 먹고 사육된 동애등에 번데기 및 상기 미생물수를 먹고 사육된 동애등에 성충을 혼합하여 제1 혼합물을 만든 후 분말화하는 단계(단계 3);상기 사료를 먹고 사육된 동애등에 번데기 및 미강을 혼합하여 제2 혼합물을 만든 후 건조하는 단계(단계 4);상기 건조된 제2 혼합물 및 상기 분말화한 제1 혼합물을 혼합하여 제3 혼합물을 만든 후 발효시키는 단계(단계 5);상기 발효물을 건조하는 단계(단계 6); 및상기 건조된 발효물을 티백포장하는 단계(단계 7);를 포함하는, 종계 음수 첨가용 티백조성물의 제조방법., Ltext: 농업, prediction: 임업

In [ ]:
from google.colab import files

# 파일 다운로드
files.download('test_output.csv')

In [ ]:
# CSV 파일 읽기
df = pd.read_csv('test_output.csv', header=None)

# 값이 동일한지 확인
equal_count = (df.iloc[:, 3] == df.iloc[:, 4]).sum()

# 전체 데이터에서 동일한 값이 차지하는 비율 계산
total_rows = len(df)
equal_percentage = (equal_count / total_rows) * 100

# 결과 출력
print(f"Meta-Llama-3.1-8B-Instruct 모델 예측 결과 정확도 계산('농업','임업', '어업') (Base 버전): {equal_percentage:.2f}%")
# Meta-Llama-3.1-8B-Instruct 모델 예측 결과 정확도 계산('농업','임업', '어업') (Base 버전): 42.68%

Meta-Llama-3.1-8B-Instruct 모델 예측 결과 정확도 계산('농업','임업', '어업') (Base 버전): 43.81%

# Part 2 : 프롬프트 튜닝으로 Llama 3.1 성능 개선하기

In [60]:
# 정답이 '임업'일 때
correct_label = '임업'

# 정답이 '임업'일 때 '임업'으로 예측한 비율
correct_forest_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '임업'일 때 '농업'으로 예측한 비율
correct_forest_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '임업'일 때 '어업'으로 예측한 비율
correct_forest_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '농업'일 때
correct_label = '농업'

# 정답이 '농업'일 때 '농업'으로 예측한 비율
correct_agriculture_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '농업'일 때 '임업'으로 예측한 비율
correct_agriculture_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '농업'일 때 '어업'으로 예측한 비율
correct_agriculture_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '어업'일 때
correct_label = '어업'

# 정답이 '어업'일 때 '어업'으로 예측한 비율
correct_fishery_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '어업'일 때 '임업'으로 예측한 비율
correct_fishery_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '어업'일 때 '농업'으로 예측한 비율
correct_fishery_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 결과 출력
print(f"정답이 '임업'일 때 '임업'으로 예측한 비율: {correct_forest_pred_forest:.2f}%")
print(f"정답이 '임업'일 때 '농업'으로 예측한 비율: {correct_forest_pred_agriculture:.2f}%")
print(f"정답이 '임업'일 때 '어업'으로 예측한 비율: {correct_forest_pred_fishery:.2f}%")

print(f"정답이 '농업'일 때 '농업'으로 예측한 비율: {correct_agriculture_pred_agriculture:.2f}%")
print(f"정답이 '농업'일 때 '임업'으로 예측한 비율: {correct_agriculture_pred_forest:.2f}%")
print(f"정답이 '농업'일 때 '어업'으로 예측한 비율: {correct_agriculture_pred_fishery:.2f}%")

print(f"정답이 '어업'일 때 '어업'으로 예측한 비율: {correct_fishery_pred_fishery:.2f}%")
print(f"정답이 '어업'일 때 '임업'으로 예측한 비율: {correct_fishery_pred_forest:.2f}%")
print(f"정답이 '어업'일 때 '농업'으로 예측한 비율: {correct_fishery_pred_agriculture:.2f}%")

정답이 '임업'일 때 '임업'으로 예측한 비율: nan%
정답이 '임업'일 때 '농업'으로 예측한 비율: nan%
정답이 '임업'일 때 '어업'으로 예측한 비율: nan%
정답이 '농업'일 때 '농업'으로 예측한 비율: nan%
정답이 '농업'일 때 '임업'으로 예측한 비율: nan%
정답이 '농업'일 때 '어업'으로 예측한 비율: nan%
정답이 '어업'일 때 '어업'으로 예측한 비율: nan%
정답이 '어업'일 때 '임업'으로 예측한 비율: nan%
정답이 '어업'일 때 '농업'으로 예측한 비율: nan%

/tmp/ipython-input-2357183879.py:5: RuntimeWarning: invalid value encountered in scalar divide
  correct_forest_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100
/tmp/ipython-input-2357183879.py:8: RuntimeWarning: invalid value encountered in scalar divide
  correct_forest_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100
/tmp/ipython-input-2357183879.py:11: RuntimeWarning: invalid value encountered in scalar divide
  correct_forest_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100
/tmp/ipython-input-2357183879.py:17: RuntimeWarning: invalid value encountered in scalar divide
  correct_agriculture_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100
/tmp/ipython-input-2357183879.py:20: RuntimeWarning: invalid value encountered in scalar divide
  correct_agriculture_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100
/tmp/ipython-input-2357183879.py:23: RuntimeWarning: invalid value encountered in scalar divide
  correct_agriculture_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100
/tmp/ipython-input-2357183879.py:29: RuntimeWarning: invalid value encountered in scalar divide
  correct_fishery_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100
/tmp/ipython-input-2357183879.py:32: RuntimeWarning: invalid value encountered in scalar divide
  correct_fishery_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100
/tmp/ipython-input-2357183879.py:35: RuntimeWarning: invalid value encountered in scalar divide
  correct_fishery_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

In [61]:
특허_카테고리_list = ['임업',
 '어업',
 '농업']

In [62]:
특허_카테고리_list

['임업', '어업', '농업']

In [ ]:
#기존 Prompt-Tuning전 프롬프트
system_prompt = f"너는 특허 카테고리를 분류하는 전문가야. \
아래 내용을 다음 특허 카테고리 중 하나로 분류해줘. 가능한 특허 카테고리 : {특허_카테고리_list}. \
최종 출력 결과는 다른말은 하지말고 분류한 카테고리만 출력해줘."
system_prompt

"너는 특허 카테고리를 분류하는 전문가야. 아래 내용을 다음 특허 카테고리 중 하나로 분류해줘. 가능한 특허 카테고리 : ['임업', '어업', '농업']. 최종 출력 결과는 다른말은 하지말고 분류한 카테고리만 출력해줘."

In [63]:
#기존 프롬프트에서 Prompt-Tuning을 한 ㅍ롬프트
system_prompt_ver2 = f"너는 특허 카테고리를 분류하는 전문가야. \
아래 내용을 다음 특허 카테고리 중 하나로 분류해줘. 가능한 특허 카테고리 : {특허_카테고리_list}. \
'농업' 카테고리를 '임업' 카테고리를 분류하지 않도록 주의해. '임업'은 '삼림에서 주로 나무를 벌채하고 목재를 생산하는 산업'을 의미해. \
최종 출력 결과는 다른말은 하지말고 분류한 카테고리만 출력해줘."
system_prompt_ver2

"너는 특허 카테고리를 분류하는 전문가야. 아래 내용을 다음 특허 카테고리 중 하나로 분류해줘. 가능한 특허 카테고리 : ['임업', '어업', '농업']. '농업' 카테고리를 '임업' 카테고리를 분류하지 않도록 주의해. '임업'은 '삼림에서 주로 나무를 벌채하고 목재를 생산하는 산업'을 의미해. 최종 출력 결과는 다른말은 하지말고 분류한 카테고리만 출력해줘."

In [64]:
def generate_response(system_message, user_message, tokenizer, model, max_new_token):
    messages = [
        {"role": "system", "content": system_message},
        {"role": "user", "content": user_message},
    ]

    input_ids = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to(model.device)

    terminators = [
        tokenizer.eos_token_id,
        tokenizer.convert_tokens_to_ids("<|eot_id|>")
    ]

    outputs = model.generate(
        input_ids,
        max_new_tokens=max_new_token,
        eos_token_id=terminators,
        do_sample=False,   # 항상 가장 확률이 높은 값으로 예측
        temperature=0.6,
        top_p=0.9
    )
    response = outputs[0][input_ids.shape[-1]:]

    return tokenizer.decode(response, skip_special_tokens=True)

In [65]:
import csv

# 1. 기존 CSV 파일을 읽어서 application_number 목록을 추출
try:
    existing_df = pd.read_csv('test_output_ver2.csv', encoding='utf-8')
    existing_app_numbers = set(existing_df['application_number'].astype(str))
except FileNotFoundError:
    # 파일이 없을 경우 빈 set으로 초기화
    existing_app_numbers = set()

In [67]:
total_num = len(filtered_df)

# 2. 새 데이터를 추가할 CSV 파일을 연다
with open('test_output_ver2.csv', mode='a', newline='', encoding='utf-8') as file:
    writer = csv.writer(file, quoting=csv.QUOTE_MINIMAL)

    # 3. 데이터프레임 순회하면서 application_number가 중복되지 않으면 추가
    for i, (index, row) in enumerate(filtered_df.iterrows()):
        app_number = str(row['application_number'])  # 문자열로 변환하여 비교
        if app_number not in existing_app_numbers:
            llama3_1_inference_result = generate_response(system_message=system_prompt_ver2,
                                          user_message=row['combined_string'],
                                          tokenizer=tokenizer,
                                          model=model,
                                          max_new_token=512)

            writer.writerow([i, row['application_number'], row['combined_string'], row['Ltext'], llama3_1_inference_result])
            print(f"{i}/{total_num} Row {i}: application_number: {row['application_number']}, combined_string: {row['combined_string']}, Ltext: {row['Ltext']}, prediction: {llama3_1_inference_result}")
            existing_app_numbers.add(app_number)  # 새로 추가된 번호는 추적
        else:
            print(f"Skipping Row {i}: application_number {row['application_number']} already exists.")

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

0/1150 Row 0: application_number: 1020210033985, combined_string: invention_title: 수목 보호 지지대 abstract: 본 발명은 수목 보호 지지대에 관한 것으로, 지면에 하단이 고정되는 다수의 버팀부재의 상단을 용이하게 고정시키는 본체 및 수목의 둘레 면에 접하여 지지하는 다수의 밀착부재 그리고 상기 버팀부재 및 밀착부재를 안정적으로 본체에 장착될 수 있도록 개량한 구조가 간결하게 이루어짐으로써 생산성 향상과 간편하게 설치할 수 있는 작업의 효율성을 높일 수 있고, 안정적으로 수목이 성장되도록 지지함은 물론 수목의 성장에 따른 굵기(체적)의 변화에 따른 밀착부재의 고정위치를 용이하게 조정할 수 있도록 이루어지는 수목 보호 지지대에 관한 것이다. claims: 수목(100)의 둘레 면에 접촉되는 다수의 밀착부재(2)와, 상기 밀착부재(2)를 안착시키면서 수목(100)을 중앙에 위치시키도록 일측이 개방된 중공부(11)를 갖는 본체(1)와, 상기 본체(1)의 개방부분을 폐쇄하는 고정편(3) 및 상기 본체(1)에 상단이 고정되고 하단이 지면에 고정되는 다수의 버팀부재(4)로 이루어진 수목 보호 지지대에 있어서,상기 본체(1)는 수목(100)이 위치하는 중공부(11)를 기준으로 3~4개소에 상기 버팀부재(4)의 상단이 돌출되면서 끼워지도록 천공된 다수의 끼움구멍(12)과, 이 끼움구멍(12)과 끼움구멍(12) 사이에 형성되어 상기 밀착부재(2)를 고정하는 고정볼트가 체결되는 나사공(13) 및 이탈을 방지하면서 수목(100)의 중심으로 직선 이동할 수 있도록 밀착부재(2)를 안내하는 가이드편(14)이 돌출 형성되어 이루어지고;상기 고정편(3)은 고정볼트에 의해 장착되어 본체(1)의 개방부분을 폐쇄하면서 내구성을 증대시키고 상기 밀착부재(2)를 고정하는 고정볼트가 체결되는 나사공(31) 및 이탈을 방지하면서 수목(100)의 중심으로 직선 이동할 수 있도록 밀착부재(2)를 안내하는 가이드편(32)이 돌출 형성되어 이루어지며;상기 밀착부재(2)는 수목(100)의 둘레 면에 접하여 지지하는 수직부(21)와, 상기 본체(1)의 나사공(13) 및 가이드편(14) 그리고 상기 고정편(3)의 나사공(31) 및 가이드편(32) 위치에 안착되면서 고정볼트에 의해 본체(1) 상부면에 고정되도록 장공(23)이 천공된 수평부(22)로 이루어지고;상기 본체(1)에 형성된 다수의 끼움구멍(12) 하측으로 지지편(15)이 하향 돌출 형성되고, 이 지지편(15)에 상기 다수의 버팀부재(4)의 상단이 접촉된 상태로 고정되도록 이루어진 것을 특징으로 하는 수목 보호 지지대., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1/1150 Row 1: application_number: 2020210000760, combined_string: invention_title: 나무보호장치 abstract: 강풍에 나무들이나 전봇대들이 뽑히거나 부러지고 넘어져서 피해를 입는 사고가 많다. 이러한 문제들을 예방하고자 보호 장치를 땅속과 나무에 설치하여 피해를 입는 사고를 예방하고 미관상 문제도 해결하고자 한다. claims: '기초보호대' 와 '땅속지지대' 를 땅속에 설치하여 강풍에 나무가 옆으로 기울거나 뿌리가 뽑혀서 넘어지는 것의 위험으로부터 보호하는 장치.'추가보호대' 를 '기초보호대' 위에 연결 설치하여 나무 꼭대기까지 부러지지 않게 보호하는 장치.'뚜껑겸연결핀' 을 이용하여 '기초보호대' 와 '추가보호대' 를 연결하면 성장에 방해가 되지 않으면서 나무 전체가 보호되는 장치.'15도연결대' 를 옆으로 구부러졌거나 휘어진 나무에 설치하여 부러지는 것의 위험으로부터 보호하는 장치.청구항 1에 있어서, '기초보호대' 의 구조는 둥근 파이프 구조로 되어 있으며, 상단부는 3개, 혹은 4개의 통로가 중간부까지 관통할 수 있게 뚫려 있는데, 이 3개, 혹은 4개의 통로 역할로 인하여 '땅속지지대' 가 3각형, 혹은 4각형의 각도와 간격을 정확하게 잡혀서 땅속에 비스듬하게 사선으로 설치되므로 강풍이 어느 방향으로 불어오더라도 견딜 수 있게 된다.청구항 1에 있어서, '기초보호대' 하단부 끝부위는 땅속에 잘 들어갈 수 있게 뾰족하게 되어 있어서 이미 기존에 심어진 나무에는 땅을 파지 않고 말뚝처럼 박아서 설치할 수 있다.청구항 1과 청구항 2에 있어서, '기초보호대' 와 '땅속지지대' 의 길이와 넓이 사이즈는 '나무보호장치용도' 와 '전봇대보호장치' 두 종류가 있는데, 길이와 굵기만 다를 뿐 구조와 모양은 동일하다.청구항 3에 있어서, 뚜껑겸연결핀' 은 상단부는 봉해져 있어서 빗물 유입도 막아주면서 연결도 가능한 구조이고, 상단부의 면에는 식재할 때 나무의 이름과 연월일을 기록할 수도 있으며, 중간부는 '벨트' 혹은 '반도' 등으로 조여서 고정시킬 때 밑으로 처지지 않는 구조이고, 하단부는 파이프처럼 끼울 수 있는 구조이다.청구항 5에 있어서, '추가보호대' 는 스테인리스강, 강철 등과 같은 금속 종류의 재질도 되고, 또 가볍지만 부러지지 않는 PVC, 플라스틱과 같은 재질도 된다., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

2/1150 Row 2: application_number: 1020210006694, combined_string: invention_title: 수목 관리 장치 및 시스템 abstract: 본 발명은 수목 관리 장치 및 시스템에 관한 것으로, 더욱 상세하게는 수목을 안정적으로 지지하고, 유수를 수목에 공급하여 수목을 효율적으로 관리할 수 있는 수목 관리 장치 및 시스템에 관한 것이다. claims: 수목(1)을 감싸도록 주변에 설치되어 수목(1)을 지지하고, 유수를 집수하여 수목(1)에 수분을 공급하며, 수목(1)의 토양수분을 측정하는 수목 관리 장치(100)에 있어서,상기 수목 관리 장치(100)는,서로 마주보게 설치될 경우 `ㅁ` 형상을 갖는 제1금형(110) 및 제2금형(120);을 포함하되,상기 제1금형(110) 및 제2금형(120)은,`ㄷ` 형상을 갖는 몸체부(111, 121);상기 몸체부(111, 121)의 수목(1) 측에 `ㄷ` 형상으로 형성되어 유수를 유입시키는 입수부(112, 122);상기 입수부(112, 122)를 통해 유입되는 유수를 저장하는 저수부(113, 123);상기 입수부(112, 122)에 적어도 하나 이상 형성되어 상기 저수부(113, 123)에 저장된 유수를 펌프모터(M)를 통해 수목으로 분사해주는 물분사부(114, 124);상기 몸체부(111, 121)의 상단 외주면에 형성되는 조명부(115, 125);상기 조명부(115, 125)의 측면에 형성되어 전력을 생산하는 쏠라셀모듈(116, 126);상기 쏠라셀모듈(116, 126)로부터 생성된 전기가 저장되는 배터리부(117, 127);상기 몸체부(111, 121)의 상단에 버튼형태로 설치되는 긴급구조부(B); 상기 몸체부(111, 121)의 모서리 일측에 버튼형태로 설치되어 장치를 ON/OFF 할 수 있는 전원부(119, 129);상기 몸체부(111, 121)의 모서리 타측에 형성되어 경고음을 발생시키는 알람부(A); 및상기 물분사부(114, 124), 조명부(115, 125) 및 알람부(A)를 제어하는 제어부(118, 128);를 포함하는 것을 특징으로 하는 수목 관리 장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

3/1150 Row 3: application_number: 1020210001336, combined_string: invention_title: 휴대용 나무 안정지지대 abstract: 본 발명은 휴대용 나무 안정지지대에 관한 것으로서, 회동축(A)을 중심으로 크로스 결합된 것으로서, 땅(E)에 지지되어 이식 대기중인 나무기둥(W)을 비스듬하게 지지하는 제1지지바아(10) 및 제2지지바아(20)와; 제2지지바아(20)의 후방측에 설치되어 제1,2지지바아(10)(20)와 삼각형을 이루며 땅(E)에 지지되는 제3지지바아(30)와; 제1지지바아(10)와 제2지지바아(20) 사이에 설치되어 제1,2지지바아(10)(20) 사이의 벌어지는 각도를 구속하기 위한 각도구속부(40)와; 회동축(A) 상부측의 제1,2지지바아(10)(20)에 결합된 것으로서 나무기둥(W)의 하부면을 지지하는 기둥지지부(50);를 포함하는 것을 특징으로 한다. claims: 회동축(A)을 중심으로 크로스 결합된 것으로서, 땅(E)에 지지되어 이식 대기중인 나무기둥(W)을 비스듬하게 지지하는 제1지지바아(10) 및 제2지지바아(20);상기 제2지지바아(20)의 후방측에 설치되어 상기 제1,2지지바아(10)(20)와 삼각형을 이루며 땅(E)에 지지되는 제3지지바아(30);상기 제1지지바아(10)와 제2지지바아(20) 사이에 설치되어 상기 제1,2지지바아(10)(20) 사이의 벌어지는 각도를 구속하기 위한 각도구속부(40); 및상기 회동축(A) 상부측의 제1,2지지바아(10)(20)에 결합된 것으로서 나무기둥(W)의 하부면을 지지하는 기둥지지부(50);를 포함하는 것을 특징으로 하는, 휴대용 나무 안정지지대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

4/1150 Row 4: application_number: 1020200152106, combined_string: invention_title: 수목보호용 블록 abstract: 본 발명은 블록의 조립에 의해 이루어진 식재 공간 내부에 식재되는 수목의 위치에 맞추어 식재공간을 변형할 수 있을 뿐만 아니라 투수성이 우수하여 물이 고이는 것을 방지할 수 있고, 조립성이 우수하여 시공을 용이하게 할 수 있을 뿐만 아니라 천연 골재로 제작됨에 따라 다양한 색상과 변색을 방지하여 보다 미려한 수목보호용 블록에 관한 것이다. claims: 수목의 주위에 설치되어 수목이 설치된 지반의 흙이 외부로 흩어지는 것을 방지하는 수목보호용 블록(10)으로, 직육면체 형상을 이루되, 일측단부에는 단부 결합홈(10g) 또는 단부 결합돌기(10d)가 형성되고, 일측단부의 측벽에는 상기 단부 결합홈 또는 단부 결합돌기와 결합되는 측벽 결합돌기 또는 측벽 결합홈이 형성되어 네 개의 블록의 서로 다른 결합돌기와 결합홈이 서로 결합됨에 의해 사각 틀을 이루고,설치되었을 때 수목이 식재된 식재공간을 향한 부분의 상면에 커팅홈(10c)이 종횡으로 형성되어, 커팅홈이 미관을 미려하게 할 수 있을 뿐만 아니라, 고인 물을 일측으로 배출시킬 수 있고, 필요에 따라 커팅홈을 따라 일부를 뜯어내어 사용할 수 있게 한 수목보호용 블록에 있어서,상기 커팅홈(10c)이 서로 만나는 부분에는 블록을 상하로 관통하도록 관통홀(10h)이 형성되고,상기 블록의 일측에는 지지목이 끼워져 고정되는 지지목고정홈(10s)이 더 형성되고, 상기 지지목고정홈이 형성된 부분의 하부 양측에는 지지목을 관통한 고정핀이 끼워져 고정되는 핀고정홈(10p)이 형성된 것을 특징으로 하는 수목보호용 블록., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

5/1150 Row 5: application_number: 1020200097407, combined_string: invention_title: 수목 보호용 밴드 abstract: 본 발명은 수목의 외주면에 설치되어 수목을 보호하기 위한 밴드로서, 보다 상세하게는 수피에 밴드를 고정하고 밴드의 외측면에 해충 기피물질이 코팅되어 해충의 접근을 막고, 밴드의 내측면에 수목에 필요한 영양성분, 살균성분, 살충성분 등의 약물이 저장되어, 상기 약물을 지속적으로 수피내로 방출함으로써 수목의 성장을 도우며 기생 및 잠복하는 해충을 퇴치하고, 약물이 수목의 형성층에 효과적으로 도달하도록 니들을 이용해 수피내로 공급하며, 지지목에 의한 수피를 보호할 수 있는 효과가 있다. claims: 수피에 부착되는 수목 보호용 밴드에 있어서,수피를 감싸도록 판형으로 형성되며 길이 방향으로 신축성을 갖는 밴드바디와,상기 밴드바디의 수목과 접하는 내측면인 제1 면에 형성되어 수피에 약물을 공급하는 약물공급부와, 상기 밴드바디의 외측면인 제2 면에 형성되며 방충 물질이 함유된 미세캡슐을 포함하는 해충기피부와,상기 밴드바디의 양끝단에 구비되어 상기 밴드바디가 수목의 외주면에 고정되도록 하는 체결부를 포함하며,상기 약물공급부는, 상기 제1 면에 적층되는 방수통기성시트와, 상기 방수통기성시트 상에 적층되고 흡수성 패드로 형성되며 적어도 하나의 약물이 수용되는 약물수용부와, 상기 제2 면으로부터 상기 밴드바디와 상기 방수통기성시트와 상기 약물수용부를 관통하고 상기 제2 면에 부착되는 지지체 상에 일정 간격으로 배열되고 상기 지지체로부터 수직으로 돌출되게 형성되어 첨단이 상기 약물수용부의 표면으로 돌출되는 적어도 하나의 니들을 구비하는 니들부를 포함하고,상기 약물은, 수목에 영양을 공급하기 위한 제1 약물, 수목에 해가 되는 균이나 바이러스를 퇴치하기 위한 제2 약물 또는 수목에 해가 되는 해충을 퇴치하기 위한 제3 약물을 포함하여 수목에 니들을 이용해 약물을 전달하는 수목 보호용 밴드., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

6/1150 Row 6: application_number: 1020200088844, combined_string: invention_title: 수목보호 매트 어셈블리 abstract: 본 발명은 수목의 하부와 상기 수목이 식재된 지면을 덮는 것으로, 천연섬유 소재로 이루어져 복수의 경사(經絲)와 복수의 위사(緯絲)로 직조하여 일정 면적과 일정 형상을 가지도록 형성됨과 동시에, 상기 복수의 경사 또는 상기 복수의 위사 각각의 사이에 일정 간격의 삽입 공극을 형성하는 보호 매트; 및 복수의 상기 삽입 공극에 결합되어 상기 지면과 상기 보호 매트 사이에 배치되는 것으로, 보행자의 답압(踏壓)에 상기 보호 매트의 압착을 방지하며 통기와 통수를 유지시키는 브라켓을 포함하는 것을 특징으로 하여, 보행자의 답력에도 압착되고 경화되어 통기 및 통수가 이루어지지 못하는 것을 미연에 방지할 수 있도록 하며 수목의 하부 및 뿌리 노출 부분을 확실하게 보호할 수 있도록 하는 수목보호 매트 어셈블리에 관한 것이다. claims: 수목의 하부와 상기 수목이 식재된 지면을 덮는 것으로, 천연섬유 소재로 이루어져 복수의 경사(經絲)와 복수의 위사(緯絲)로 직조하여 일정 면적과 일정 형상을 가지도록 형성됨과 동시에, 상기 복수의 경사 또는 상기 복수의 위사 각각의 사이에 일정 간격의 삽입 공극을 형성하는 보호 매트; 및복수의 상기 삽입 공극에 결합되어 상기 지면과 상기 보호 매트 사이에 배치되는 것으로, 보행자의 답압(踏壓)에 상기 보호 매트의 압착을 방지하며 통기와 통수를 유지시키는 브라켓을 포함하며,상기 브라켓은, 상기 보호 매트의 사면과 상기 지면 사이에 배치되는 몸체와, 상기 몸체의 상면으로부터 돌출되어 복수로 이격하여 배치되고, 상기 삽입 공극에 끼움 결합되는 연통 리브와, 상기 몸체의 상면으로부터 하면까지 관통되어 통기와 통수를 허용하는 복수의 연통공과, 상기 연통 리브로부터 상기 몸체의 하면까지 관통 형성되어 통기와 통수를 허용하는 복수의 연통슬롯을 포함하는 것을 특징으로 하는 수목보호 매트 어셈블리., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

7/1150 Row 7: application_number: 1020200069704, combined_string: invention_title: 빗물활용 일체형 수목생장 및 보호시스템 abstract: 본 발명은 중앙에 수목이 놓이는 중공부가 형성된 빗물활용 일체형 수목생장 및 보호시스템에 있어서, 빗물이 투입되는 홈이 형성된 상판부; 상기 상판부의 하부에 부착되며, 투입된 빗물을 여과하여 여과수를 수목에 공급하기 위한 빗물여과용 여재 및 상기 여재를 수용하는 수용부를 포함하는 빗물여과모듈; 상기 빗물여과모듈의 하부에 결합되며, 여과수를 저장하는 빗물저장조, 상기 저장조의 일측에 장착되어 상기 여과수를 수목의 뿌리에 공급하기 위한 관수펌프 및 빗물공급관을 포함하는 빗물저장모듈; 및 대기정보를 획득하기 위한 대기센서부 및 토양정보를 획득하기 위한 토양센서부로 이루어진 센서부;를 포함하는 것을 특징으로 하는 빗물활용 일체형 수목생장 및 보호시스템을 제공한다. claims: 중앙에 수목이 놓이는 중공부가 형성된 빗물활용 일체형 수목생장 및 보호시스템에 있어서,빗물이 투입되는 홈이 형성된 상판부;상기 상판부의 하부에 부착되며, 투입된 빗물을 여과하여 여과수를 수목에 공급하기 위한 빗물여과용 여재 및 상기 여재를 수용하는 수용부를 포함하는 빗물여과모듈;상기 빗물여과모듈의 하부에 결합되며, 여과수를 저장하는 빗물저장조, 상기 저장조의 일측에 장착되어 상기 여과수를 수목의 뿌리에 공급하기 위한 관수펌프 및 빗물공급관을 포함하는 빗물저장모듈; 및대기정보를 획득하기 위한 대기센서부 및 토양정보를 획득하기 위한 토양센서부로 이루어진 센서부;를 포함하되,상기 빗물여과모듈의 일측에 양액공급홀이 형성되고,상기 빗물저장모듈에 상기 양액공급홀을 통해 공급되는 양액을 저장하는 양액저장조가 포함되며,상기 대기센서부 및 토양센서부는 빗물저장모듈에 형성되고,상기 빗물저장모듈은 중앙이 빈 사각형상의 이중벽으로 이루어지되, 빗물저장조, 양액저장조 및 IoT제어부로 구획되고, 상기 구획은 내벽과 외벽 및 격벽에 의해 이루어지고, 상기 대기센서부 및 토양센서부는 내벽의 일측에 부착되어지며,상기 빗물저장모듈은 빗물저장조의 내측면에 압력센서가 설치되고, 바닥면에는 발열선이 설치되어, 상기 압력센서가 빗물저장조에 저장된 여과수가 겨울철에 얼어 팽창시, 팽창과정에서 발생하는 압력을 감지하고 IoT 제어부로 신호를 전송하도록 하고, IoT 제어부는 여과수가 얼은 것으로 판단하여, 상기 빗물저장조 바닥면에 설치된 발열선을 발열시켜 얼음을 녹이고, 얼음이 녹아 감소된 압력센서로부터의 신호를 전송받아 즉시 혹은 일정시간 경과 후 관수펌프를 가동시키는 것을 특징으로 하는 빗물활용 일체형 수목생장 및 보호시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

8/1150 Row 8: application_number: 1020200066770, combined_string: invention_title: 수목 지지대 abstract: 본 발명은 수목 지지대에 관한 것으로서, 수목이 식수 후 뿌리를 토착할 때까지 수목이 쓰러지지 않게 안정적으로 지지할 수 있도록 함을 목적으로 한 것이다.즉, 본 발명은 수목 지지대에 있어서, 수목의 지지를 위하여 클램핑 구속할 수 있게 구비되는 수목클램프와 상기 수목클램프의 상단과 하단에 나무의 외면과 탄성 접촉되어 수목의 클램핑절단홈이 방지되게 구비되는 클램핑완충밴드, 수목의 크기에 따라 수목클램프를 조여주는 클램핑조임부 및 상기 수목클램프의 외측에 등 간격으로 3 개 내지 4 개로 결속되어 수목을 지지하는 수목지지발로 구성한 것을 특징으로 하는 것이다.따라서, 본 발명은 수목클램프에 의하여 수목지지대의 설치가 신속하게 이루어지고 작업자의 숙련도에 영향을 받지 않고 견고하게 설치되어 수목이 뿌리를 토착할 때까지 수목을 안정적으로 지지하는 효과를 갖는 것이다. claims: 수목 지지대에 있어서;수목의 지지를 위하여 클램핑 구속할 수 있게 구비되는 수목클램프와 상기 수목클램프의 상단과 하단에 나무의 외면과 탄성 접촉되어 수목의 클램핑절단홈이 방지되게 구비되는 클램핑완충밴드, 수목의 크기에 따라 수목클램프를 조여주는 클램핑조임부 및 상기 수목클램프의 외측에 등 간격으로 3 개 내지 4 개로 결속되어 수목을 지지하는 수목지지발로 구성하고;수목클램프가 수목의 성장에 따라 자동으로 벌어지게 상기 수목클램프는 수목지지발에 대응하여 3 개 내지 4 개의 판으로 분할된 분할클램프판으로 구성하고, 상기 분할클램프판은 외면에 일단으로 지지발힌지부가 결합되는 힌지결합부로 구성하고, 상기 힌지결합부의 반대 측에는 연장 형성되어 다른 분할클램프판의 힌지결합부 내면으로 끼워 결합되어 수목의 신축을 흡수할 수 있게 한 신축가동판을 형성하며, 상기 신축가동판에는 다른 분할클램프판과의 결속을 위한 신축결속핀을 형성하고, 상기 힌지결합부에는 다른 분할클램프판의 신축결속핀을 구속하고 신축가동을 가이드하는 신축가이드공을 형성하며, 상기 신축가동판의 외면과 힌지결합부의 내면에는 팽창제한마찰접속부를 형성하고;바람에 의하여 수목의 한 방향으로 작용되는 힘에 의하여 수목클램프가 신축팽창되지 않게 수목클램프의 상단과 하단에 신축제한공을 등 간격으로 형성하고, 수목지지발의 힌지부 측 상단과 하단에 수목지지발의 지지발힌지부를 지점으로한 회전에 대하여 신축제한공에 키 결합되는 신축제한키돌기를 형성한 것을 특징으로 하는 한 것을 특징으로 하는 수목 지지대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

9/1150 Row 9: application_number: 1020200059563, combined_string: invention_title: 수목용 보호덮개 조립체 abstract: 본 발명은 수목용 보호덮개 조립체에 관한 것으로서, 특히 가로수 등의 수목의 하부를 덮어 보호하는 수목용 보호덮개 조립체에 관한 것이다.본 발명의 수목용 보호덮개 조립체는, 중공 사각형상의 프레임부재와; 상기 프레임부재의 안쪽에 장착되고, 안쪽에 반원형상의 장착공이 각각 형성된 한 쌍의 외측커버와; 원호형상으로 이루어져 상기 장착공에 결합되고, 안쪽에 수목이 관통하는 반원형상의 관통공이 형성된 한 쌍의 내측커버;를 포함하여 이루어지되, 상기 외측커버의 내주부의 하부에는 제1받침돌기가 돌출 형성되어 상기 장착공이 장착되는 상기 내측커버의 하부를 지지하고, 상기 내측커버의 외주부의 상부에는 제2받침돌기가 돌출 형성되고 상기 제2받침돌기는 상기 외측커버의 상면에 걸려 상기 내측커버의 하방향 이동을 저지시키며, 상기 내측커버의 외주부의 하부에는 제3받침돌기가 돌출 형성되고 상기 제3받침돌기는 상기 외측커버의 하면에 걸려 상기 내측커버의 상방향 이동을 저지시키는 것을 특징으로 한다. claims: 중공 사각형상의 프레임부재와;상기 프레임부재의 안쪽에 장착되고, 안쪽에 반원형상의 장착공이 각각 형성된 한 쌍의 외측커버와;원호형상으로 이루어져 상기 장착공에 결합되고, 안쪽에 수목이 관통하는 반원형상의 관통공이 형성된 한 쌍의 내측커버;를 포함하여 이루어지되,상기 외측커버의 내주부의 하부에는 제1받침돌기가 돌출 형성되어 상기 장착공이 장착되는 상기 내측커버의 하부를 지지하고,상기 내측커버의 외주부의 상부에는 제2받침돌기가 돌출 형성되고 상기 제2받침돌기는 상기 외측커버의 상면에 걸려 상기 내측커버의 하방향 이동을 저지시키며,상기 내측커버의 외주부의 하부에는 제3받침돌기가 돌출 형성되고 상기 제3받침돌기는 상기 외측커버의 하면에 걸려 상기 내측커버의 상방향 이동을 저지시키고,상기 장착공의 양끝단에는 외측방향으로 걸림홈이 하방향으로 오목하게 형성되고, 상기 걸림홈은 상기 장착공의 내측방향과 이와 직교되는 수평방향 및 상방향으로 개방 형성되며,상기 내측커버의 양끝단에는 상기 걸림홈에 삽입되는 걸림돌기가 외측방향으로 돌출 형성되어,상기 걸림홈에 삽입된 걸림돌기에 의해 상기 외측커버에 대한 상기 내측커버의 수평방향 회전이 저지되며,상기 제3받침돌기는,상기 내측커버의 양끝단의 하부에서 외측방향으로 돌출 형성된 한 쌍의 제3-1받침돌기와;한 쌍의 상기 제3-1받침돌기 사이에 배치되고, 상기 내측커버의 외주부의 하부에서 외측방향으로 돌출 형성된 제3-2받침돌기;로 이루어지되,상기 제3-1받침돌기는 상기 내측커버의 양끝단 하부에 장착되면서 측면에 수평방향으로 지지면을 형성하고,한 쌍의 상기 내측커버는 상기 장착공에 장착된 상태에서 상기 제3-1받침돌기의 지지면이 서로 인접하게 대면하여 한 쌍의 상기 내측커버가 수평방향으로 서로 지지되면서 회전되거나 흔들리는 것을 방지하며,상기 외측커버는 안쪽에 반원형상의 상기 장착공이 형성되면서 수평방향으로 배치되어 상호 결합되는 제1외측커버와 제2외측커버로 이루어지며,상기 제1외측커버에는 상기 제2외측커버 방향으로 결합돌기가 돌출 형성되고,상기 제2외측커버의 상면에는 상기 결합돌기가 안착되는 결합홈이 형성되며,상기 결합돌기에는 상하방향으로 제1관통공이 형성되고, 상기 결합홈에는 상하방향으로 제2관통공이 형성되며,상기 제1관통공은 상기 제2관통공보다 큰 직경을 갖고,상기 결합돌기의 상면에는 끼움부재가 배치되고, 상기 끼움부재에는 상기 제1관통공에 안착되는 끼움돌기부가 하방향으로 돌출 형성되며,상기 끼움돌기부에는 상기 제1관통공 및 제2관통공과 연통되는 장공형상의 제3관통공이 형성되고,머리부가 상기 끼움돌기부의 안쪽에 안착되면서 끝단이 상기 제3관통공, 제1관통공 및 제2관통공을 관통하는 볼트에 의해 상기 제1외측커버와 제2외측커버는 상호 결합되는 것을 특징으로 하는 수목용 보호덮개 조립체., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

10/1150 Row 10: application_number: 1020200056830, combined_string: invention_title: 충격 보호 기능이 구비된 수목 보호대 abstract: 본 발명은 충격 보호 기능이 구비된 수목 보호대에 관한 것으로서, 보행자 또는 자전거 등의 이동수단의 충돌로 인한 충격으로 부터 수목을 보호함과 함께 보행자, 자전거 이용자의 부상 발생을 방지하기 위한 것이다.이를 실현하기 위한 본 발명은, 판형태를 이루어 수목 주변으로 지면에 설치가 이루어지는 수목 보호판(10)과; 상기 수목 보호판(10)의 상부에 수직으로 일정 높이를 이루어 세워지도록 연결 구성되는 지주(20)와; 상기 지주(20) 상단부에 연결 구성되어 수목 주변을 감싸는 형태로 구비되되, 복수개가 쌍을 이루어 상호 간격의 가변이 가능하도록 탄성 지지가 이루어지는 완충대(30)와; 상기 지주(20)와 완충대의 연결부위에 구성되는 제1힌지핀(21)과; 상기 지주(20)와 수목 보호판 연결부위에 구성되는 제2힌지핀(22);을 포함하는 구성을 이루는 것을 특징으로 한다. claims: 판형태를 이루어 수목 주변으로 지면에 설치가 이루어지는 수목 보호판(10)과;상기 수목 보호판(10)의 상부에 수직으로 일정 높이를 이루어 세워지도록 연결 구성되는 지주(20)와;상기 지주(20) 상단부에 연결 구성되어 수목 주변을 감싸는 형태로 구비되되, 복수개가 쌍을 이루어 상호 간격의 가변이 가능하도록 탄성 지지가 이루어지는 완충대(30)와;상기 지주(20)와 완충대(30)의 연결부위에 구성되는 제1힌지핀(21)과;상기 지주(20)와 수목 보호판(10) 연결부위에 구성되는 제2힌지핀(22);을 포함하되,상기 완충대(30)는 제1완충대(31)와 제2완충대(32)가 상호 쌍을 이루는 대칭형 구조를 이루되, 상기 제1완충대(31)에는 제2완충대(32)의 일단부가 삽입되는 삽입홈(31a)이 형성되고, 내부에는 제2완충대(32)를 탄성 지지하는 탄성스프링(31b)이 구성됨과 함께 탄성스프링(31b)을 지지하기 위한 지지격벽(31c)이 일체로 구성되며,상기 제2완충대(32)에는 삽입홈(31a)으로의 삽입 길이를 제한하기 위한 걸림턱(32a)이 돌출 구성되고, 단부에는 삽입홈(31a)의 내벽면과 마찰력 증대를 위한 마찰브러시(32b)가 구성된 것을 특징으로 하는 충격 보호 기능이 구비된 수목 보호대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

11/1150 Row 11: application_number: 1020200049726, combined_string: invention_title: 다목적 미세먼지 방재숲 조성 방법 abstract: 본 발명은 미세먼지 방재숲 조성 방법에 있어서, 도심지역, 대기 오염 발생원이 설치된 오염원지역, 해안지역에 미세먼지를 저감시킬 수 있는 방재숲을 조성하되, 상기 방재숲은 각 지역별로 수목을 일정패턴으로 식재하고, 상기 방재숲에 다목적 방재 및 생육조절 장치를 일정높이로 설치하여 식재된 수목의 방재와 생육을 조절하고, 상기 방재숲에 토양 정화설비를 설치하여 방재숲의 토양에 오염수를 정화한 정화수를 공급하도록 조성하는 다목적 미세먼지 방재숲 조성 방법에 관한 발명이다. claims: 도심지역, 대기 오염 발생원이 설치된 오염원지역, 해안지역에 미세먼지를 저감시킬 수 있는 방재숲을 조성하되,상기 방재숲(100)은 각 지역별로 수목을 일정패턴으로 식재하고,상기 방재숲에 방재 및 생육조절 장치(101)를 일정높이로 설치하여 식재된 수목의 다목적 방재와 생육을 조절하고,상기 방재숲에 토양 정화설비(102)를 설치하여 방재숲의 토양에 오염수를 정화한 정화수를 수목에 공급하도록 조성하는 미세먼지 방재숲 조성 방법에 있어서,상기 방재숲의 수목 식재패턴은 바람길을 고려한 유입존(103), 미세먼지 저감을 위한 저감존(104), 미세먼지 차단을 위한 차단존(105)으로 구분하여 조성하되,유입존은 3~5m, 저감존은 8~10m, 차단존은 12~15m의 폭으로 조성하여 미세먼지 영역의 전체 폭이 최소 23m에서 최대 30m가 되도록 조성하고,상기 유입존과 저감존 및 차단존 각각에 식재하는 수목은 3열로 식재하되,1열은 상록수, 낙엽수, 상록수 순서로 대교목을 식재하여 상층림을 조성하고,2열은 낙엽수, 상록수, 낙엽수 순서로 소교목을 식재하여 중층림을 조성하며,3열은 상록수, 낙엽수, 상록수 순서로 관목을 식재하여 하층림을 조성하며,상기 방재 및 생육조절장치(101)와 토양 정화설비(102)는 미세먼지 전체영역 최대 폭 30m, 길이 30m의 900m2의 면적을 기준으로 상기 방재 및 생육조절 장치(101) 4개를 상기 기준의 가로와 세로 단부로부터 각각 10m 간격으로 이격시켜 설치하고, 상기 방재 및 생육조절 장치(101)는 상단부에 고압살수용 스프링클러(101a)를 형성하고, 그 하부에 미스트를 분무하는 다수개의 분무노즐(101b)을 형성하며, 상기 분무노즐 형성부위에 LED등 또는 레이저빔 장치로 이루어지는 조명장치(101c)를 설치하고,상기 토양 정화설비(102)는 오염된 물을 정화하는 여과장치가 설치된 집수정화조(102a)와 정수조(102b)를 연결하고 정수조에 다수개의 코어로프를 결합하여 일정길이로 형성되는 워터서코어로프(102c)를 연결하여 토양에 일정깊이로 매설하며, 워터서코어로프를 통해 정수조에 저장되는 물이 토양에 공급되도록 하는 것을 특징으로 하는 다목적 미세먼지 방재숲 조성 방법., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

12/1150 Row 12: application_number: 1020200048811, combined_string: invention_title: 복합로프 및 상기 복합로프와 비철금속으로 제조된 수목 보호용 밴드 abstract: 본 발명은 복합로프 및 상기 복합로프와 비철금속으로 제조된 수목 보호용 밴드에 관한 것이다.구체적으로는, 나일론 재질의 피복 내부에 나일론과 아라미드 재질의 속심으로 이루어진 복합로프와, 이러한 복합로프를 밴드로 구성하여 내부에 요철(凹凸)의 구성을 가지는 요철구성을 포함하는, 수목 보호용 밴드에 관한 것이다. claims: 복합로프(1)를 이용하여 만들어진 밴드구성(10)과, 상기 밴드구성(10)과 보호 대상인 나무 사이에 위치되는 요철구성(20)을 포함하여 구성된 수목 보호용 밴드(2)에 있어서,상기 복합로프(1)는,나일론 재질의 피복과, 상기 피복 내부에 구비된 속심을 포함하되,상기 속심은 나일론 재질로 꼰 나일론 속심과, 아라미드 재질의 아라미드 속심을 포함하고,상기 요철구성(20)은,상호 이격된 위치를 가지는 2개의 직선판(21)과, 2개의 직선판(21)의 인접한 각 단부에 결합된 'ㄷ'자 형상의 ㄷ자판(22)을 포함하는 구조가 복수 개 배열되되,인접한 2개의 요철구성(20)의 각 직선판(21)이 보호 대상인 나무의 표면에 맞닿도록 위치되고, 요철구성(20)의 ㄷ자판(22) 양측의 2개 이상 구비된 직선판(21) 중 어느 하나에는 소정의 길이를 가지며 직선판(21)의 폭방향으로 관통된 홀이 형성되며, 다른 하나에는 'U'자 형상으로 만곡되도록 구성된 결합부가 형성되고,상기 결합부의 단부에는 상기 홀의 길이방향과 동일하거나 작게 구성되며 홀의 길이방향에 수직된 가로방향은 홀보다 크게 형성된 날개가 구성됨으로써,상기 결합부의 단부를 다른 인접한 요철구성의 직선판의 홀에 결합시키되, 상기 결합부의 굴곡진 방향은 ㄷ자판(22)의 돌출방향과 동일한 방향을 가지도록 하여, 결합부가 나무 표피를 파손하는 것을 방지하고,상기 결합부의 만곡으로 인해, 홀에 삽입된 후, 2개의 요철구성(20)이 인접한 각각의 직선판(21)을 통해 소정의 각도만큼 회동될 때, 결합부의 만곡각도를 따라 회동할 수 있도록 하는 것을 특징으로 하는, 수목 보호용 밴드., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

13/1150 Row 13: application_number: 1020200047680, combined_string: invention_title: 조경 자생환경 시스템 abstract: 본 발명은 조경 자생환경 시스템에 관한 것으로서, 보다 상세하게는 지중에 매립되어 조경수의 뿌리의 하부에 위치하는 열발생모듈과 열발생모듈을 둘러싸되 소정의 경사를 이루는 측벽으로 형성된 단열반사막과 조경수의 하부에 설치되어 열발생모듈의 열을 지중으로 반사시키는 보온커버부 및 지중의 온도를 감지하여 열발생모듈의 작동을 제어하는 토양온도센서가 구비된 제어부를 포함하는 조경 자생환경 시스템에 관한 것이다. claims: 내부에 전열선이 매립되는 판으로 형성되고 상기 판을 둘러싸는 고정틀이 형성되어 지중에 매립되며, 조경수의 뿌리의 하부에 위치하는 열발생장치와 상기 열발생장치의 하부에 단열재를 구비한 보온층과 상기 열발생장치의 상부와 상기 보온층의 하부에 각 위치하는 금속보호판 및 상기 지중으로 유입되는 수분을 상기 열발생장치의 하부로 배수시키는 배수부를 포함하여 형성된 열발생모듈;상기 열발생모듈을 둘러싸되 소정의 경사를 이루는 측벽으로 형성되어 상기 조경수의 뿌리의 크기에 대응하여 상기 측벽의 경사를 조절하는 단열반사막;상기 조경수의 하부에 설치되어 상기 열발생모듈의 열을 지중으로 반사시키는 보온커버부; 및지중의 온도를 감지하여 상기 열발생모듈의 작동을 제어하는 토양온도센서가 구비된 제어부를 포함하고,상기 배수부는상기 열발생장치와 상기 보온층과 상기 금속보호판의 일면을 관통하여 서로 연통하는 홀을 복수개로 형성한 배수홀;상기 배수홀에 삽입되는 관으로 형성되어 상기 열발생장치의 상부에 위치한 상기 금속보호판의 일면으로 유입된 수분을 하부로 이동시키고, 상기 관의 상부에 플랜지가 형성된 배수관; 및상기 배수관의 하부에 나선 결합되어 상기 배수관이 상기 열발생장치에 견고하게 위치시키는 볼트를 포함하는 것을 특징으로 하는조경 자생환경 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

14/1150 Row 14: application_number: 1020200041251, combined_string: invention_title: 수목 보호 구조물 abstract: 본 발명은 특히 수목 주변 토양의 급격한 온도 변화를 완화하고 토양 내 보습력을 향상시킬 수 있는 수목 보호 구조물에 관한 것으로, 복수의 지지대; 및 상기 복수의 지지대에 의해 지지되어 상기 복수의 지지대를 둘러싸는 차광망을 포함한다. claims: 복수의 지지대; 및상기 복수의 지지대에 의해 지지되어 상기 복수의 지지대를 둘러싸는 차광망을 포함하는 수목 보호 구조물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

15/1150 Row 15: application_number: 1020200036891, combined_string: invention_title: 재활용 대형 플라스틱 통을 이용한 나무 식재형 대형 화분 abstract: 본 발명은 재활용 대형 플라스틱 통을 이용한 나무 식재형 대형 화분에 관한 것으로서, 토양이 수용되며 나무의 식재가 가능도록 상부가 절개되어 형성되는 대형 플라스틱 수용용기; 플라스틱 수용용기의 바닥면에 배치되며, 식재된 나무에 물을 공급하는 수분 공급부; 수분 공급부의 상면에 배치되어 수분 공급부에 수용된 물을 삼투압에 의해서 토양에 전달시키는 수분전달부; 및 관 형상으로 형성되어 일단이 수분 공급부에 배치되고, 타단이 토양의 상단으로 돌출되며, 관의 내부에 수위를 확인할 수 있는 부표가 구비되는 수위 확인부;를 포함한다.본 발명에 의하면, 플라스틱 용기의 내부로 공기가 고르게 순환되도록 함으로써 토양에 식재되어 있는 뿌리에 적절한 산소를 공급함으로써 나무의 뿌리가 괴사되는 것을 방지할 수 있다. 또한, 물의 수위를 적절하게 파악할 수 있어 물이 필요할 때에 사용자가 물을 공급할 수 있게 된다. 뿐만 아니라, 화학약품을 수용하는 대형플라스틱 용기를 재활용함으로써 별도의 큰 용기를 제작할 필요가 없기 때문에 자원 재활용하여 환경친화적인 특성이 있다. claims: 재활용 대형 플라스틱 통을 이용한 나무 식재형 대형 화분에 있어서,토양이 수용되며 나무의 식재가 가능도록 상부가 절개되어 형성되는 대형 플라스틱 수용용기;상기 플라스틱 수용용기의 바닥면의 일측면의 소정 영역이 노출되도록 배치되며, 식재된 나무에 물을 공급하는 수분 공급부;상기 수분 공급부의 상면에 배치되어 상기 수분 공급부에 수용된 물을 삼투압에 의해서 토양에 전달시키는 수분전달부; 및관 형상으로 형성되어 일단이 상기 수분 공급부에 배치되고, 타단이 상기 토양의 상단으로 돌출되며, 상기 관의 내부에 수위를 확인할 수 있는 수위 확인부;를 포함하며,상기 플라스틱 수용용기는,재활용 화학약품 대형용기이며, 상기 플라스틱 수용용기의 내부로 공기가 유입되도록 토양이 수용되어 있는 측면에 적어도 하나 이상의 공기 유입홀이 형성되며, 상기 공기 유입홀은 상기 플라스틱 수용용기 내부의 토양이 상기 플라스틱 수용용기의 측면으로 유출되지 않도록 와이어 메쉬가 배치되고, 상기 플라스틱 수용용기를 감싸서 보호하는 보호구를 구비하며,상기 수분전달부는,부직포로 형성되며, 상기 수분 공급부의 상측면을 감싸면서, 상기 플라스틱 수용용기의 바닥면의 노출되는 영역으로 하방향으로 꺾여져 연장되고, 다시 상기 플라스틱 수용용기의 측면을 따라 상측으로 연장되어, 그 사이에 형성된 공간에 토양이 채워지도록 유도하며,상기 수분 공급부는,판상으로 형성되어 상기 부직포를 지지하는 지지판;상기 지지판에서 매트릭스 형상으로 배열되어 하방향으로 물을 수용할 수 있는 복수의 물수용구; 및상기 지지판에 형성되어 매트릭스 형상으로 배열된 상기 복수의 물수용구에 물이 전달되도록 상기 물수용구의 상단을 연결시키는 격자형 유로;를 포함하며,상기 보호구는,하면에는 지게차의 포크가 삽입될 수 있도록 포크 안착홀이 형성되는 것을 특징으로 하는 재활용 대형 플라스틱 통을 이용한 나무 식재형 대형 화분., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

16/1150 Row 16: application_number: 2020200001006, combined_string: invention_title: 수목의 지주목 abstract: 개시된 본 고안에 따른 수목의 지주목은, 수목의 둘레를 따라 받칠 수 있게 방사상으로 배치되며, 상단에 적어도 하나의 지주 구멍이 형성되고, 땅속에 묻히는 지주 받침이 하단에 구비되는 지주부; 및 상기 지주 구멍에 삽입되어 상기 지주부의 상단을 연결하는 연결부;를 포함한다. 본 고안에 따른 수목의 지주목은, 지주부의 상단 및 중간 부분마다 지주 구멍이 형성되어 대향 배치된 지주부를 연결부를 통해 견고하게 연결 가능하고, 하단에 땅속에 묻히는 지주 받침이 지주부와 교차 구비되어 바람이 강하게 불면서 지주목이 지면에서 솟아오르거나 이탈됨을 방지 가능하고, 수피에 햇빛이 잘 들고 물관의 흐름을 좋게 하고, 뿌리 쪽으로 오는 빗물의 도달을 도우며, 시공이 간편하고 경제적인 효과가 있다. claims: 수목(10)의 둘레를 따라 받칠 수 있게 방사상으로 배치되며, 상단에 적어도 하나의 지주 구멍이 형성되고, 땅속에 묻히는 지주 받침(116)이 하단에 구비된 지주부(110); 및상기 지주 구멍에 삽입되어 상기 지주부(110)의 상단을 연결하는 연결부(120);를 포함하며,상기 지주 받침(116)의 중앙에는 상부에 반원홈(1162)이 형성된 몸체(1160)가 삽입결합되고,상기 몸체(1160)의 반원홈(1162) 내주면에는 다수의 반구홈(1164)이 일정 간격으로 이격되어 형성되며,상기 지주부(110)의 하단 단면은 상기 지주부(110)의 하단에 구비된 힌지(H)를 중심으로 상기 반원홈(1162) 내부에서 회동 가능하도록 상기 반원홈(1162)과 대응되는 반원형으로 형성되고,상기 지주부(110) 하단에는 홈부(G)가 형성되며,상기 홈부에는 탄성부재(118b)가 삽입 구비되고, 상기 탄성부재(118b)는 끝단에 구비된 구부재(118a)를 가압하여 상기 반구홈(1164) 내부로 삽입되도록 하며,상기 구부재(118a)는 각도가 변경되도록 상기 힌지(H)를 중심으로 상기 지주부(110)를 회동작동시 상기 반구홈(1164) 중 하나의 반구홈(1164)로부터 상기 탄성부재(118b)에 의하여 가압되는 상태로 이탈되어 이동한 후 상기 탄성부재(118b)의 가압에 의하여 이웃하는 반구홈(1164)에 삽입되는 것을 특징으로 하는 수목의 지주목., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

17/1150 Row 17: application_number: 1020200010979, combined_string: invention_title: 산림용 묘목 보호 시트 abstract: 본 발명은 산림용 묘목 보호 시트에 관한 것으로서, 더욱 상세하게는, 산에 식재된 어린 묘목의 위치표시 및 보호를 위해 설치하여 외부의 피해를 방지하고 묘목의 생장을 방해하는 잡초의 생장을 방지하는 산림용 묘목 보호 시트에 관한 것이다. claims: 조림목이 내부에 수용되며, 지면에 설치되는 산림용 묘목 보호 시트에 있어서,상기 조림목(100)의 하단부분을 수용하도록 설치된 본체(10);상기 본체(10)의 양측단으로 연장되며, 절곡선(BL)을 기준으로 절곡되어 지면을 지지하는 절곡부(20)로 이루어지되,상기 본체(10)는,중앙에 상기 조림목(100)을 수용하는 수용홈(11)과, 상기 수용홈(11)에서 전면을 향해 형성되어 상기 조림목(100)이 유입되는 절개홈(12)의 형상을 따라 절취선(PL)이 형성되어 절취되는 절취부(14)가 포함되되,상기 절취부(14)는,상기 수용홈(11)의 형상을 따라 절취되어 중앙부분에는 상기 조림목(100)의 상단에 고정되는 걸이홈(15a)이 형성된 걸이부(15)와,상기 절개홈(12)의 형상의 따라 절취되며, 길이방향을 따라 중앙이 절취되어 외부로 노출된 인식부(16)로 이루어지는 것을 특징으로 하는 산림용 묘목 보호 시트., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

18/1150 Row 18: application_number: 1020190177295, combined_string: invention_title: 수목 생물적 방제를 위한 다목적 천적 방사기 abstract: 본 발명은 용기 본체의 전면부에 제1 천적의 알을 산란할 수 있는 천적유지식물을 배치하여 제1 천적이 지속적으로 산란함으로서 당해 수목으로 지속적으로 천적이 유입될 수 있도록 하며, 이와 더불어 하단부에 개폐가 용이한 비가림 구조의 제2 천적인 포식성 응애류 천적을 수납할 수 있는 공간을 구성하여 다양한 해충발생시 선택적으로 천적을 운영할 수 있도록 하며, 방사된 천적이 안정적으로 생존하고 수목으로 이동할 수 있도록 하는 물리적 특성을 가진 수목 부착형 다목적 천적방사기에 관한 것이다. claims: 천적유지식물를 포함한 수목에 부착 가능한 용기 본체;상기 용기 본체의 전면부에 배치되고, 제1 천적의 알을 산란할 수 있는 천적유지식물이 함께 제공되며 천적유지 식물의 상단부와 연결된 제1 천적을 수납할 수 있는 비가림 구조의 방사장치 및,상기 용기 본체의 하부측에 배치되어 비가림 기능이 있고 손쉽게 개폐가 가능한 제2 천적의 수납공간으로 여러 가지 해충 방제에 효과가 있는 포식성 응애류 천적과 그 먹이곤충을 수시로 공급할 수 있는 방사장치. 상기 용기 본체의 제1 천적과 제2 천적을 안정적으로 수납할 수 있는 수목 부착형 방사장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

19/1150 Row 19: application_number: 1020190177700, combined_string: invention_title: 수목생육관리장치 및 이를 포함하는 생태 모니터링 시스템 abstract: 본 발명의 수목생육관리장치는, 내부에 공간부가 형성되어 수분을 저장하며, 상기 토양에 수분을 제공하는 집수블록과, 상기 수목의 뿌리와 인접한 토양의 상태를 측정하는 센서부와, 상기 센서부에 의해 생성된 측정 정보와 상기 수목에 할당된 식별번호를 포함하는 생태 정보를 생성하는 제어부와, 외부와 통신을 수행하는 통신부을 포함한다. claims: 내부에 공간부가 형성되어 수분을 저장하며, 상기 토양에 수분을 제공하는 집수블록;상기 수목의 뿌리와 인접한 토양의 상태를 측정하는 센서부;상기 센서부에 의해 생성된 측정 정보와 상기 수목에 할당된 식별번호를 포함하는 생태 정보를 생성하는 제어부; 및외부와 통신을 수행하는 통신부을 포함하는 수목생육관리장치.지표면의 하부에 매립되어 내부에 형성된 공간부에 수분을 저장하고 상기 수분을 인접한 수목의 뿌리를 둘러싼 토양에 제공하는 집수블록과, 상기 토양의 상태를 측정하는 센서부와, 상기 센서부에 의해 측정된 센싱 결과와 상기 수목에 할당된 식별번호를 포함하는 토양 정보를 생성하는 제어부와, 외부와 통신을 수행하는 통신부를 포함하는 수목생육관리장치; 및상기 통신부로부터 제공된 상기 식별번호에 대응하는 지도상 위치에 상기 센싱 결과에 대응하는 단계별 색상, 수치, 및 기호 중 적어도 하나를 표기하여 토양생태지도를 생성하는 생태 관리 서버를 포함하는 생태 모니터링 시스템., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

20/1150 Row 20: application_number: 1020190171077, combined_string: invention_title: 접합식물체 생산방법 및 이에 의해 생산된 접합식물체 abstract: 본 발명은 최소한 하나의 나무 개체가 다른 하나의 나무 개체 줄기를 관통한 관계인 접합식물체의 생산방법 및 이에 의해 생산된 접합식물체에 관한 것으로서, 보다 상세하게는 제1나무 개체의 줄기 또는 가지에 관통공을 형성하는 관통공형성단계; 및 제2나무 개체의 줄기 또는 가지를 제1나무 개체의 관통공으로 통과시키는 관통배치단계;를 포함하는 접합식물체 생산방법 및 이에 의해 생산된 접합식물체에 관한 것이다. claims: 제1나무 개체의 줄기 또는 가지에 관통공을 형성하는 관통공형성단계;제2나무 개체의 줄기 또는 가지를 제1나무 개체의 관통공으로 통과시키는 관통배치단계;를 포함하는 것을 특징으로 하는 접합식물체 생산방법.청구항 1 내지 3 중 어느 한 항에 의한 생산방법에 의해 생산된 접합식물체., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

21/1150 Row 21: application_number: 1020190166460, combined_string: invention_title: 산림빅데이터 플랫폼에 기반하여 데이터 상품을 제공하는 장치 및 방법 abstract: 본 발명은 산림빅데이터 플랫폼을 구축하고, 산림빅데이터 플랫폼에 기반하여 다양한 데이터 상품을 제공하는 기술적 사상에 관한 것으로서, 보다 상세하게는 산림빅데이터 플롯폼에 기반하여 산림자원관리 서비스, 산림휴양 복지 서비스, 산림재해안전 서비스를 도출하고, 도출된 서비스와 관련된 데이터 상품을 소비자들에게 제공하는 기술에 관한 것이다. claims: 산림 자원과 관련된 정보 데이터를 수집하고, 상기 수집된 정보 데이터와 관련된 수집 데이터 DB(database)를 구축하는 데이터 수집부;상기 구축된 수집 데이터 DB(database)를 통해 상기 수집된 정보 데이터를 분석, 가공 및 매쉬업(mash-up)하여 산림 휴양 및 복지 서비스, 산림자원관리 서비스 및 산림 재해안전 서비스와 관련된 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하는 데이터 상품 결정부; 및상기 구축된 빅데이터 DB(database)에 기반하여 상기 결정된 적어도 하나 이상의 데이터 상품을 제공하기 위한 오픈 마켓 플레이스를 생성하고, 상기 생성된 오픈 마켓 플레이스를 통해 소비자에게 상기 결정된 적어도 하나 이상의 데이터 상품을 제공하는 데이터 상품 제공부를 포함하고,상기 데이터 상품 결정부는 상기 산림 자원과 관련된 정보 데이터를 가공하여 상기 산림자원관리 서비스와 관련된 활용 자원 데이터를 결정하고, 상기 결정된 활용 자원 데이터를 이용하여 산지관리법에 기반하여 필지의 경사를 레벨 별로 구분하여 표시된 맵 데이터를 생성하고, 상기 생성된 맵 데이터에 기반하여 상기 레벨과 관련된 상기 필지 별 개발 용이성에 따라 상기 필지 내에서 개발 가능한 영역을 안내하는 데이터 상품을 결정하며, 상기 산림 재해안전 서비스와 관련된 상기 결정된 재해 대응 데이터 또는 산림 재해 데이터를 이용하여 도시 숲 대비 기온 분석이 표시된 그래프 데이터를 생성하고, 상기 생성된 그래프 데이터에 기반하여 도시의 분할 구역의 면적과 1인당 도시 숲의 면적 그리고 상기 도시의 분할 구역의 면적과 1인당 도시 숲의 면적에 따른 낮 온도, 저녁 온도 및 온도 변화를 표시함에 따라 도시 숲 조성 지역 선정을 보조하는 데이터 상품을 결정하며, 상기 산림자원관리 서비스와 관련된 상기 결정된 임산물 생산 유통 데이터를 이용하여 임산물 가격 예측 데이터, 월별 도매시장 별 임산물 거래 현황 데이터, 월별도매시장 임산물 시장 점유율 데이터 및 월별 임산물 거래량 증감현황 데이터를 생성하고, 상기 생성된 임산물 가격 예측 데이터, 월별 도매시장 별 임산물 거래 현황 데이터, 월별도매시장 임산물 시장 점유율 데이터 및 월별 임산물 거래량 증감현황 데이터에 기반하여 월별 거래단량과 전체 거래단량에 따른 임산물 거래 현황 정보, 전국도매시장 일별 정산 경락 가격과 수출입정보의 적용에 따라 구현된 가격 예측 알고리즘 및 최근 5년간 추세분석에 기반한 거래량의 변화와 관련된 임산물 거래량 증강 정보를 제공하는 데이터 상품을 결정하고,상기 데이터 상품 결정부는, 상기 산림 자원과 관련된 정보 데이터를 가공하여, 상기 결정된 적어도 하나 이상의 데이터 상품과 관련된 트랙킹 활용증대 데이터, 휴양 자원 데이터 또는 산림 소비자 요건 데이터를 결정하여 상기 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하고, 상기 산림 휴양 및 복지 서비스와 관련된 상기 결정된 휴양 자원 데이터를 이용하여 피톤치드 예측발생량이 표시된 맵 데이터를 생성하고, 상기 생성된 맵 데이터에 기반하여 피톤치드에 특화된 관광코스를 제공하는 데이터 상품을 결정하며, 상기 산림 휴양 및 복지 서비스와 관련된 상기 결정된 트랙킹 활용증대 데이터 또는 휴양 자원 데이터를 이용하여 휴양지 관련 대중교통 접근성 평가 데이터를 생성하고, 상기 생성된 대중교통 접근성 평가 데이터에 기반하여 대중교통의 타입, 개수 또는 빈도 중 적어도 하나를 결정 또는 변경하도록 지원하는 데이터 상품을 결정하는산림빅데이터 플랫폼에 기반하여 데이터 상품을 제공하는 장치.데이터 수집부에서, 산림 자원과 관련된 정보 데이터를 수집하고, 상기 수집된 정보 데이터와 관련된 수집 데이터 DB(database)를 구축하는 단계;데이터 상품 결정부에서, 상기 구축된 수집 데이터 DB(database)를 통해 상기 수집된 정보 데이터를 분석, 가공 및 매쉬업(mash-up)하여 산림 휴양 및 복지 서비스, 산림자원관리 서비스 및 산림 재해안전 서비스와 관련된 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하는 단계; 및데이터 상품 제공부에서, 상기 구축된 빅데이터 DB(database)에 기반하여 상기 결정된 적어도 하나 이상의 데이터 상품을 제공하기 위한 오픈 마켓 플레이스를 생성하고, 상기 생성된 오픈 마켓 플레이스를 통해 소비자에게 상기 결정된 적어도 하나 이상의 데이터 상품을 제공하는 단계를 포함하고,상기 적어도 하나 이상의 데이터 상품을 결정하는 단계는,상기 산림 자원과 관련된 정보 데이터를 가공하여 상기 산림자원관리 서비스와 관련된 활용 자원 데이터를 결정하고, 상기 결정된 활용 자원 데이터를 이용하여 산지관리법에 기반하여 필지의 경사를 레벨 별로 구분하여 표시된 맵 데이터를 생성하고, 상기 생성된 맵 데이터에 기반하여 상기 레벨과 관련된 상기 필지 별 개발 용이성에 따라 상기 필지 내에서 개발 가능한 영역을 안내하는 데이터 상품을 결정하는 단계;상기 산림 재해안전 서비스와 관련된 상기 결정된 재해 대응 데이터 또는 산림 재해 데이터를 이용하여 도시 숲 대비 기온 분석이 표시된 그래프 데이터를 생성하고, 상기 생성된 그래프 데이터에 기반하여 도시의 분할 구역의 면적과 1인당 도시 숲의 면적 그리고 상기 도시의 분할 구역의 면적과 1인당 도시 숲의 면적에 따른 낮 온도, 저녁 온도 및 온도 변화를 표시함에 따라 도시 숲 조성 지역 선정을 보조하는 데이터 상품을 결정하는 단계; 및상기 산림자원관리 서비스와 관련된 상기 결정된 임산물 생산 유통 데이터를 이용하여 임산물 가격 예측 데이터, 월별 도매시장 별 임산물 거래 현황 데이터, 월별도매시장 임산물 시장 점유율 데이터 및 월별 임산물 거래량 증감현황 데이터를 생성하고, 상기 생성된 임산물 가격 예측 데이터, 월별 도매시장 별 임산물 거래 현황 데이터, 월별도매시장 임산물 시장 점유율 데이터 및 월별 임산물 거래량 증감현황 데이터에 기반하여 월별 거래단량과 전체 거래단량에 따른 임산물 거래 현황 정보, 전국도매시장 일별 정산 경락 가격과 수출입정보의 적용에 따라 구현된 가격 예측 알고리즘 및 최근 5년간 추세분석에 기반한 거래량의 변화와 관련된 임산물 거래량 증강 정보를 제공하는 데이터 상품을 결정하는 단계를 포함하고,상기 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하는 단계는 상기 산림 자원과 관련된 정보 데이터를 가공하여, 상기 결정된 적어도 하나 이상의 데이터 상품과 관련된 트랙킹 활용증대 데이터, 휴양 자원 데이터 또는 산림 소비자 요건 데이터를 결정하여 상기 적어도 하나 이상의 데이터 상품을 결정하고, 상기 결정된 데이터 상품과 관련된 빅데이터 DB(database)를 구축하는 단계를 포함하고,상기 적어도 하나 이상의 데이터 상품을 결정하는 단계는 상기 산림 휴양 및 복지 서비스와 관련된 상기 결정된 휴양 자원 데이터를 이용하여 피톤치드 예측발생량이 표시된 맵 데이터를 생성하고, 상기 생성된 맵 데이터에 기반하여 피톤치드에 특화된 관광코스를 제공하는 데이터 상품을 결정하는 단계 및 상기 산림 휴양 및 복지 서비스와 관련된 상기 결정된 트랙킹 활용증대 데이터 또는 휴양 자원 데이터를 이용하여 휴양지 관련 대중교통 접근성 평가 데이터를 생성하고, 상기 생성된 대중교통 접근성 평가 데이터에 기반하여 대중교통의 타입, 개수 또는 빈도 중 적어도 하나를 결정 또는 변경하도록 지원하는 데이터 상품을 결정하는 단계를 포함하는산림빅데이터 플랫폼에 기반하여 데이터 상품을 제공하는 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

22/1150 Row 22: application_number: 1020190162420, combined_string: invention_title: 수목용 지지구 abstract: 본 발명은 수목의 하부에서 수목을 지지하는 지지구의 길이를 용이하게 조절할 수 있도록 하는 구조물에 대한 것으로, 지지부재를 형성하는 제 2 지지관에, 제 1 지지관의 진퇴작용을 물리적으로 구속하는 스토핑 구조를 형성하되, 제1지지관을 구속하는 고정요소를 해제하기 위한 과도한 힘을 가하지 않고, 회전동작에 의해 고정요소를 해제할 수 있도록 하여, 사용의 편의성을 극대화할 수 있다. claims: 안착부재의 하부에 지지부재가 설치된 형태로 구성되고, 상기 지지부재는, 제 1 지지관(10)이 제 2 지지관(20)의 중공부에 삽입된 형태로 이루어져 제 1 지지관의 진퇴거리에 따라 총 길이가 변경하여 설정되도록 구성되고, 제 2 지지관(20)에는 제 1 지지관(10)의 진퇴작용을 구속하는 스토핑 구조물(S)이 형성된 수목용 지지구에 있어서,상기 스토핑 구조물(S)은,제1지지관(10)이 관통하는 중공부를 구비하는 제1브라켓몸체(100);상기 제1브라켓몸체(100)와 끼움결합 형식으로 결합되며, 제2지지관(20)의 중공부와 연통하는 중공부를 가지는 관상의 제2브라켓몸체(210);상기 제1브라켓몸체(100) 내에 안착되며, 상기 제1지지관(10)이 관통하는 중공이 형성되며, 상기 제1브라켓몸체(100)의 내벽에 형성되는 가이드홈(G1, G2)에 테두리부가 밀착하는 고정부재(120); 를 포함하며,상기 제2브라켓몸체(210)의 상부는 경사구조의 받침구조물(230)이 구현되며, 상기 제2브라켓몸체(210)의 회전동작에 따라 상기 받침구조물(230)이 상기 고정부재(120)의 일측을 상승 또는 하강하게 하여, 상기 제1지지관의 구속 및 해제 동작을 구현하는,수목용 지지구조물.안착부재의 하부에 지지부재가 설치된 형태로 구성되고, 상기 지지부재는, 제 1 지지관(10)이 제 2 지지관(20)의 중공부에 삽입된 형태로 이루어져 제 1 지지관의 진퇴거리에 따라 총 길이가 변경하여 설정되도록 구성되고, 제 2 지지관(20)에는 제 1 지지관(10)의 진퇴작용을 구속하는 스토핑 구조물(S)이 형성된 수목용 지지구에 있어서,상기 스토핑 구조물(S)은,제1지지관(10)이 관통하는 중공부를 구비하는 제1브라켓몸체(100);상기 제1브라켓몸체(100)의 전면부 하단에 하측은 개구되며, 상측으로 요입된 형상으로 구현되는 가이드홈(110B);상기 제1브라켓몸체(100)와 끼움결합 형식으로 결합되며, 제2지지관(20)의 중공부와 연통하는 중공부를 가지는 관상의 제2브라켓몸체(210);상기 브라켓몸체(210)의 상에 안착되며, 좌우 회전동작이 가능하도록 상기 브라켓몸체(210) 상에 결합되는 회전몸체(240);상기 제1브라켓몸체(100) 내에 안착되며, 상기 제1지지관(10)이 관통하는 중공이 형성되며, 상기 제1브라켓몸체(100)의 내벽에 상기 고정부재(120)의 테두리부가 밀착하며, 상기 고정부재의 테두리부의 일단에 돌출구조로 형성되는 제2각도조절편(126)이 형성되는 고정부재(120);를 포함하며,상기 회전몸체(240)의 상부 테두리부 상에 돌출구조 받침구조물(250)이 구현되며, 상기 돌출구조 받침구조물(250)은 상기 가이드홈(110B)의 좌우폭에 대응되도록 이동하며,상기 회전몸체(240)0)의 회전동작에 따라 상기 돌출구조 받침구조물(250)이 상기 고정부재(120)의 일측을 상승 또는 하강하게 하여, 상기 제1지지관의 구속 및 해제 동작을 구현하는,수목용 지지구조물., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

23/1150 Row 23: application_number: 1020190161324, combined_string: invention_title: 수목 지지대 abstract: 본 발명에 따른 수목을 지지하는 수목 지지대는, 일단이 지면에 삽입 고정되고, 상기 수목을 중심으로 복수개로 배치되는 지지프레임과, 상기 지지프레임의 일측에 구비되며, 전면에는 함몰부가 형성되는 한편, 후면에는 'T'자형으로 형성되는 결합부가 마련되되, 상기 결합부의 측면에는 체결볼트가 관통되는 관통공이 형성되고, 상기 결합부의 측부에는 로프를 고정하는 고정홈이 형성되는 리브와, 상기 관통공에 볼트 결합되어 회동 가능하게 설치되고, 단부에는 삽입공이 형성되어 상기 지지프레임의 타단이 삽입고정되는 브라켓 및 상기 리브의 함몰부에 결합되고, 상기 수목의 외주면에 탄력적으로 밀착되는 완충부재를 포함하는 것을 특징으로 한다. claims: 수목을 지지하는 수목 지지대에 있어서,일단이 지면에 삽입 고정되고, 상기 수목을 중심으로 복수개로 배치되는 지지프레임; 상기 지지프레임의 일측에 구비되며, 전면에는 함몰부가 형성되는 한편, 후면에는 'T'자형으로 형성되는 결합부가 마련되되, 상기 결합부의 측면에는 체결볼트가 관통되는 관통공이 형성되고, 상기 결합부의 측부에는 로프를 고정하는 고정홈이 형성되는 리브;상기 관통공에 볼트 결합되어 회동 가능하게 설치되고, 단부에는 삽입공이 형성되어 상기 지지프레임의 타단이 삽입고정되는 브라켓; 및상기 리브의 함몰부에 결합되고, 상기 수목의 외주면에 탄력적으로 밀착되는 완충부재;를 포함하는 것을 특징으로 하는 수목 지지대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

24/1150 Row 24: application_number: 1020190144596, combined_string: invention_title: 건조한 지역에서 친환경적인 급수를 위한 조림장치 abstract: 본 발명은 건조한 지역에서 친환경적인 급수를 위한 조림장치에 관한 것으로서, 더 상세하게는 가뭄이 계속되거나 사막과 같은 건조지역의 들판과 연계된 경사지 등에서 초목 등의 조림을 위한 작업에서 초목에서 비산되는 수분을 친환경적으로 토지로 유도시켜 주도록 구상되는 급수장치에 관한 것이다. 일반적으로 사막화가 진행되는 지역이나, 초지 또는 준 사막화 진행되는 들판에서 극심한 가뭄이 진행되는 지역에서는 강우량의 부족으로 초목이 말라죽는 현상이 일어나고 있는 것이다. 고로 본 발명은 건조한 지역에서 친환경적인 조림을 위한 급수장치에 관한 것으로서, 건조지역이나 미세먼지가 발생되는 사막지역의 토양(65)에 매설되면서 소정의 유휴공간(다)으로 이격된 기둥(91)으로 심어진 나무(85)로 조성된 조림수(90)와, 상기 토양에 고착된 뿌리(94)에서 돌출되는 기둥(91)과, 기둥에서 성장되는 가지(97)가 다수개의 가지(97)(97a)(97b)의 잔가지(97')에서 돋아나는 잎사귀(92)와, 상기 뿌리(94)가 매설로 구비되는 조림지역에 있어서, 상기 다수개의 가지(97)(97a)(97b) 중에서 일측의 가지(97a)에 돋아나는 잎사귀뭉치(92)의 외측을 감싸주도록 내측공간(가)을 형성되는 포집포대(95)의 하측으로 돌출되는 유입부에 가지(97a)를 감싸주는 결속밴드(88)와, 상기 포집포대(95)와 결속밴드(88)의 결속하는 유입부에 결합된 지퍼(89)와, 상기 포집포대(95)의 하측으로 연결된 수분공급관(86)을, 뿌리(94)가 착토된 토양(65)에 매설되는 부숙대(80)으로 공급되도록 제공되는 발명이다.또한 상기 응축수응축관(86)에 구비되는 차단밸브(82)와,상기 토양(65)이 경사지는 구간으로 형성된 조림지역(98)에 연속 반복적으로 지지기둥(53)과 태양광발전판(50)으로 구축된 태양광발전장치(60)과, 상기 태양광발전판(50)의 하측단에 결합되도록 조립대(72)로 구비된 빗물받이(79)으로 부숙대(80)가 매설된 토양에 용수를 공급시켜 주도록 제공되는 발명이다. claims: 건조지역이나 미세먼지가 발생되는 사막지역의 토양(65)에 매설되면서 소정의 유휴공간(다)으로 이격된 기둥(91)으로 심어진 나무(85)로 조성된 조림수(90)과, 상기 조림수(90)에서 돌출되는 기둥(91)과, 기둥(91)에 분기로 성장하는 가지(97)가 다수개의 가지(97)(97a)(97b)의 잔가지(97')에서 돋아나는 잎사귀(92)가 구비됨으로서 조성된 조림지역(98)과, 상기 조림지역(98)에 형성된 유휴공간(다)의 토양(65)에는 키가 작은 관목(77)이 성장되도록 심어진 조림지역에 있어서, 상기 다수개의 가지(97)(97a)(97b) 중에서 일측의 가지(97a)에 돋아나는 잎사귀(92)의 외측을 감싸주도록 내측공간(가)을 형성되는 포집포대(95)의 하측으로 돌출되는 유입부에 가지(97a)를 감싸서 결속되는 결속밴드(88)와, 상기 포집포대(95)와 결속밴드(88)의 결속하는 유입부에 결합된 지퍼(89)와,상기 뿌리(94)가 착토된 토양(65)에 매설되는 부숙대(80)와, 상기 포집포대(95)의 하측으로 연결된 수분공급관(86)과, 상기 수분공급관(86)이 토양(65)애 매설된 구간에 급수구(89)가 천공된 용수공급관(96)으로 부숙대(80)에 용수를 공급시켜 주고, 상기 관목(77)의 잎사귀 뭉치(92)의 높이(h)에서 고정되도록 받침빔(72)으로 고정된 공기흡입관(81')을 흡입펌프(75)의 흡입력으로 토양(65)에 심어진 조림수(90)와 관목(77)의 뿌리(94)가 매설된 토양(65)에 수분공급관(96)으로 연결시켜 주도록 제공되는 건조한 지역에서 친환경적인 급수를 위한 조림장치., Ltext: 임업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

25/1150 Row 25: application_number: 1020190143087, combined_string: invention_title: 건조지역에서 친환경적인 조림을 위한 급수장치 abstract: 본 발명은 건조한 지역에서 친환경적인 조림을 위한 급수장치에 관한 것으로서, 더 상세하게는 가뭄이 계속되는 건조지역의 토양에서 식생되는 과수 또는 초목 등에서 비산되는 수분을 친환경적으로 포집과 아울러 급수를 위한 포집장치에 관한 발명으로서, 토양(65)에서 돌출된 지지기둥으로 조립되는 태양광발전판(50)과, 토양에 고착된 뿌리(94)에서 돌출되는 기둥(91)과, 기둥에서 성장되는 가지(97)가 다수개의 가지(97)(97a)(97b)의 잔가지(97')에서 돋아나는 잎사귀(92)와, 상기 뿌리(94)가 매설로 구비되는 초목(조림목)(85)에 있어서, 상기 다수개의 가지(97)(97a)(97b) 중에서 일측의 가지(97a)에 돋아나는 잎사귀(92)의 외측을 감싸주도록 내측공간(가)을 형성되는 포집포대(95)의 하측으로 돌출되는 유입부에 가지(97a)를 감싸시켜 주는 결속밴드(88)와, 상기 포집포대(95)와 결속밴드(88)의 결속하는 유입부에 결합된 지퍼(89)와, 상기 포집포대(95)의 하측으로 연결된 응축수응축관(86)을 부숙대(80)으로 공급되도록 제공되는 발명이다.또한 상기 큰조림수(190)의 기둥(191)에서 뻗어나는 장뿌리(194)에서 흡입된 깊숙한 토지(165)에 흐르는 지하수를, 기둥(191)에 삽입되는 흡입관(146)으로 이동시켜 주는 암거배수관(78)과, 상기 응축수응축관(86)에 구비되는 차단밸브(82)와,상기 조림수(90)용 뿌리(94)가 뻗어있는 토사에는 부숙대(80)을 암거배수관(78)으로 연결로 매설된 별도의 부숙대(80')와, 상기 부숙대(80')에 연결된 암거배수관(78)에 공급시켜 주도록, 태양광발전판(50)의 배면에다 교호상의 응축관(75')으로 구성된 응축수응축대(75)에 연결관(64)으로 연결된 암거배수관(78)으로 응축수를 공급시켜 주도록 제공되는 발명이다. claims: 배수관(76)이 매설된 토양(65)에서 돌출된 지지기둥으로 조립되는 태양광발전판(50)과, 토양에 고착되면서 기둥에 분기로 성장하는 조림수(90)의 뿌리(94)에서 돌출되는 기둥(91)에서, 가지(97)가 다수개의 가지(97)(97a)(97b)의 잔가지(97')에서 돋아나는 잎사귀(92)와, 큰조림수(90)의 기둥(191)에서 깊숙한 토지(165)에 뻗어준 장뿌리(194)와, 상기 뿌리(94)가 매설된 토사에 부숙대(80)의 매설로 구비되는 조림지역에 있어서,상기 다수개의 가지(97)(97a)(97b) 중에서 일측의 가지(97a)에 돋아나는 잎사귀(92)의 외측을 감싸주도록 내측공간(가)을 형성되는 포집포대(95)의 하측으로 돌출되는 유입부에 가지(97a)를 감싸서 결속시켜 주는 결속밴드(88)와, 상기 포집포대(95)와 결속밴드(88)의 결속하는 유입부에 결합된 지퍼(89)와, 상기 포집포대(95)의 하측으로 연결된 응축수응축관(86)을 부숙대(80)으로 공급되도록 제공되는 건조지역에서 조림을 위한 친환경적인 급수장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

26/1150 Row 26: application_number: 1020190142717, combined_string: invention_title: 수목 보호판 abstract: 본 발명에 따른 수목 보호판은, 수목을 둘러싸도록 배치되고 물과 양분은 수목 뿌리로 통과시키고 태양광은 차단할 수 있도록 천연 소재를 엮어서 제작되는 제1 천연소재 보호대, 상기 제1 천연소재 보호대의 상부에 놓이고 상기 제1 천연소재 보호대와 동일한 소재로 제작되며, 상기 제1 천연소재 보호대와 상하 방향으로 일부 중첩되도록 배치되는 제2 천연소재 보호대, 및 상기 제1 천연소재 보호대의 하부에 설치되어 양분은 수목 뿌리로 통과시키고 태양광은 차단하는 천연 부직포를 포함하는 것을 특징으로 한다. claims: 수목을 둘러싸도록 배치되고 물과 양분은 수목 뿌리로 통과시키고 태양광은 차단할 수 있도록 천연 소재를 엮어서 제작되는 제1 천연소재 보호대;상기 제1 천연소재 보호대의 상부에 놓이고 상기 제1 천연소재 보호대와 동일한 소재로 제작되며, 상기 제1 천연소재 보호대와 상하 방향으로 일부 중첩되도록 배치되는 제2 천연소재 보호대; 및상기 제1 천연소재 보호대의 하부에 설치되어 양분은 수목 뿌리로 통과시키고 태양광은 차단하는 천연 부직포를 포함하는 것을 특징으로 하는 수목 보호판., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

27/1150 Row 27: application_number: 1020190137139, combined_string: invention_title: 수목지지구조와 그 방법 abstract: 본 발명은 수목지지구조와 그 방법에 관한 것으로, 수목의 뿌리분을 감싸는 그물망과, 상기 뿌리분이 안착되는 평판 형태의 지지판 및 상기 지지판과 상기 그물망을 연결, 고정하는 로프를 포함하여 수목지지수단이 지중에 매설됨으로써 수목 주위의 경관을 향상시키고 보행자의 통행이 용이할 뿐 아니라 수목지지수단의 철거 작업이 불필요하여 인력과 비용을 절감할 수 있는 수목지지구조와 그 방법을 제공한다. claims: 수목의 뿌리분을 감싸는 그물망과;상기 뿌리분이 안착되는 평판 형태의 지지판; 및상기 지지판과 상기 그물망을 연결, 고정하는 로프;를 포함함으로써 상기 지지판이 상기 뿌리분과 함께 지중에 매립되어 상기 수목을 지지하도록 한 것을 특징으로 하는 수목지지구조.(a) 수목의 뿌리분을 그물망으로 감싸는 단계와;(b) 그물망으로 감싼 뿌리분을 평판 형태의 지지판에 안착시키는 단계와;(c) 상기 지지판과 상기 그물망을 로프로 연결, 고정하는 단계; 및(d) 상기 지지판을 상기 뿌리분과 함께 지중에 매립하는 단계;를 포함하는 수목지지방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

28/1150 Row 28: application_number: 1020190129091, combined_string: invention_title: 친환경적인 조림장치 abstract: 본 발명은 친환경적인 조림장치에 관한 것으로서, 더 상세하게는 가뭄이 계속되거나 겨울철이나 혹한지역에서 조림을 위한 동파반지 또는 사막과 같은 건조지역 등에서 비산되는 수분을 친환경적으로 산림에 대한 성장을 보강시켜 주는 조림장치에 관한 것이다. 일반적으로 사막화와 같은 건조지역에서도 새벽녘에는 이슬과 같은 응축수가 형성되는 것이다. 이는 사막화가 진행되는 지역이나, 혹한지에서 초지 또는 야산과 같은 들판에서 극심한 추위가 진행되는 지역에서는, 식생하는 초목(나무)의 냉해로 많은 손실이 발생하는 것이다. 고로 지중의 토양(70)에 깊숙이 뿌리(83)로 고정하면서 지상으로 성장되는 나무용 기둥(81)과, 상기 기둥(81)의 일측으로 구비된 태양광발전판(42)과, 상기 토양(70)에 깊숙이 뿌리(83)로 고정하면서 지상으로 성장되는 나무용 기둥(81)의 가지에 돋아나는 잎사귀(87)와, 상기 잎사귀(87)을 둘러싸여서 내측공간(55)이 형성되도록 다수개의 원주형 고정링(66)과, 상기 원주형 고정링(66)을 지지되는 지지대(68)으로 구비되는 원통형의 포집포대(60)과, 상기 포집블럭(40)의 외측면을 감싸주는 포집블럭(40)으로 형성되는 내측공간(55)에 있어서, 상기 토양(70)에 고정되는 뿌리(83) 부근에 매설되는 부숙재(49)와, 상기 뿌리(83)와 부숙재(49)를 감싸주는 보온망태(74)와,상기 태양광발전판(42)의 배면에 일체되는 응축수 포집판(51)과, 상기 응축수 포집판(51)에서 파이프(46)로 연결되는 부숙탱크(78)과, 상기 부숙탱크(78)에서 공급되는 가열공기를 토양(70)으로 감싸주는 보온망태(74)로 공급시켜 주도록 이송관(48)이 제공되는 발명이다. claims: 지중의 토양(70)에 깊숙이 뿌리(83)로 고정하면서 지상으로 성장되는 나무용 기둥(81)과, 상기 기둥(81)의 일측으로 구비된 태양광발전판(42)과, 상기 나무용 기둥(81)에서 자라나는 가지에서 돋아나는 잎사귀(87)와, 상기 잎사귀(87)을 둘러싸여 주는 포집포대(60)의 내측공간(55)이 형성되도록 다수개의 원주형 고정링(66)과, 상기 원주형 고정링(66)을 지지되는 지지대(68)으로 구비되는 원통형의 포집포대(60)과, 상기 포집포대(60)의 외측면을 감싸주는 포집블럭(40)으로 형성되는 친환경적인 조림장치에 있어서, 상기 토양(70)에 고정되는 뿌리(83) 부근에 매설되는 부숙재(49)와, 상기 뿌리(83)와 부숙재(49)를 감싸주는 보온망태(74)와,상기 태양광발전판(42)의 배면에 이동간격(47)이 구비되도록 응축수 포집판(51)으로 일체된 태양광발전장치(53)와, 상기 응축수 포집판(51)에서 파이프(46)로 연결되는 부숙탱크(78)과, 상기 부숙탱크(78)에서 공급되는 가열공기를 토양(70)으로 감싸주는 보온망태(74)로 공급시켜 주도록 이송관(48)이 제공되는 친환경적인 조림장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

29/1150 Row 29: application_number: 1020190129296, combined_string: invention_title: 친환경재를 이용한 수목용 다기능 생육매트 및 그 제조방법 abstract: 본 발명은 친환경재를 이용한 수목용 다기능 생육매트 및 그 제조방법에 관한 것으로, 더욱 상세하게는 매트 본체(100);와 상기 매트 본체(100)의 중앙에 형성되어 수목이 위치되는 개구부(200);를 포함하되, 상기 매트 본체(100)는, 버개스, 코코칩 및 코코섬유를 포함하는 것을 특징으로 한다. 본 발명의 친환경재를 이용한 수목용 다기능 생육매트 및 그 제조방법에 의하면, 내구연한의 경과시 자연 부식되어 환경피해가 전혀 없으며, 친환경 유기질 비료로 작용할 수 있고, 우수한 보수력으로 인해 수목 생장기에 가뭄 피해를 예방할 수 있으며, 동절기 동해방지의 효과가 있어 수목의 고사율을 낮출 수 있다는 장점이 있다. 아울러, 잡초억제 효과, 발근촉진 효과는 물론, 미관적 향상 효과가 있으며, 제조비용이 낮아 상용화가 가능하다는 장점이 있다. claims: 버개스, 코코칩 및 코코섬유를 혼합하는 단계와,상기 혼합된 혼합물을 압축 및 니들펀칭하여 매트로 성형하는 단계와,상기 성형된 매트의 상부 및 하부에 수용성 수지 접착제를 살포하는 단계와,상기 수용성 수지 접착제가 살포된 매트를 건조하는 단계와,상기 건조된 매트를 재단하여 매트 본체(100)를 제조하고, 상기 매트 본체(100)의 중앙에 개구부(200)를 형성하는 단계를 포함하며,상기 수용성 수지 접착제를 살포하는 단계 시,상기 수용성 수지 접착제에 발근촉진제 및 친환경 살균살충제를 혼합하여 살포하며,상기 수용성 수지 접착제는 폴리비닐알코올(PVA)이고,상기 코코섬유, 버개스 및 코코칩의 사용량은, 상기 코코섬유 60~80중량%, 상기 버개스 10~20중량% 및 상기 코코칩 10~20중량%인 것을 특징으로 하는 친환경재를 이용한 수목용 다기능 생육매트의 제조방법.버개스를 포설하여 버개스층(110)을 형성하는 단계와,상기 버개스층(110)의 상부에 코코칩을 포설하여 코코칩층(120)을 형성하는 단계와,상기 코코칩층(120)의 상부에 코코섬유를 포설하여 코코섬유층(130)을 형성하는 단계와,상기 버개스층(110)의 하부 및 코코섬유층(130)의 상부에 수용성 수지 접착제를 살포하여 상기 버개스층(110), 상기 코코칩층(120) 및 상기 코코섬유층(130)이 상호 접착되도록 하는 단계와, 상기 수용성 수지 접착제가 살포된 매트를 건조 및 압축하는 단계와,상기 건조된 매트를 재단하여 매트 본체(100)를 제조하고, 상기 매트 본체(100)의 중앙에 개구부(200)를 형성하는 단계를 포함하며,상기 수용성 수지 접착제를 살포하는 단계 시,상기 수용성 수지 접착제에 발근촉진제 및 친환경 살균살충제를 혼합하여 살포하며,상기 수용성 수지 접착제는 폴리비닐알코올(PVA)이고, 상기 코코섬유, 버개스 및 코코칩의 사용량은, 상기 코코섬유 60~80중량%, 상기 버개스 10~20중량% 및 상기 코코칩 10~20중량%인 것을 특징으로 하는 친환경재를 이용한 수목용 다기능 생육매트의 제조방법.제6항 또는 제7항의 제조방법으로 제조되는 것을 특징으로 하는 수목용 다기능 생육매트., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

30/1150 Row 30: application_number: 1020190127989, combined_string: invention_title: 고정밀 측량 기법을 활용하는 산림 조사 방법 및 장치 abstract: 산림 조사를 위한 작업 타입을 설정하고, 산림 조사에 있어서 요구되는 측량의 정밀도를 일반/정밀 측량 방식 중 어느 하나로 설정하고, 산림 내의 조사지에서, 설정된 정밀도에 기반하여 조사지의 위치 정보를 획득하고, 해당 조사지와 관련하여 사용자로부터 입력된 정보를 획득하여 조사지에 대한 산림 조사 데이터를 생성하는, 측량 기법을 활용하고 모바일 단말을 이용하여 산림을 조사하는 산림 조사 방법이 제공된다. claims: 측량 기법을 활용하고 모바일 단말을 이용하여 산림을 조사하는 산림 조사 방법에 있어서, 상기 산림 조사 방법은 상기 모바일 단말에 의해 수행되고,상기 모바일 단말에 의해, 상기 산림을 조사하는 산림 조사를 위한 작업 타입을 설정하는 단계; 상기 모바일 단말에 의해, 상기 산림 조사에 있어서 요구되는 측량의 정밀도를 설정하는 단계;상기 모바일 단말에 의해, 상기 산림 내의 조사지에서, 상기 설정된 정밀도에 기반하여 상기 조사지의 위치 정보를 획득하는 단계;상기 모바일 단말에 의해, 상기 조사지와 관련하여 사용자로부터 입력된 정보를 획득하는 단계; 및상기 모바일 단말에 의해, 상기 획득된 위치 정보 및 상기 입력된 정보에 기반하여 상기 조사지에 대한 산림 조사 데이터를 생성하는 단계를 포함하고,상기 측량의 정밀도를 설정하는 단계는, 상기 측량의 정밀도를 설정하기 위한 복수의 옵션들을 제공하는 단계 - 상기 복수의 옵션들은 일반 측량 방식을 설정하기 위한 제1 옵션, 정밀 측량 방식을 설정하기 위한 제2 옵션 및 고정밀 측량 방식을 설정하기 위한 제3 옵션을 포함함 -; 및 상기 제1 옵션 내지 상기 제3 옵션 중 어느 하나로 상기 측량의 정밀도를 설정하는 단계를 포함하고, 상기 위치 정보를 획득하는 단계는, 상기 측량의 정밀도가 상기 제1 옵션으로 설정되면, 상기 모바일 단말의 GPS 장치를 사용하여 상기 위치 정보를 획득하고, 상기 측량의 정밀도가 상기 제2 옵션으로 설정되면, 상기 모바일 단말의 GPS 장치를 사용하여 획득된 상기 조사지에 대한 복수의 위치 값들 중 평균 값 또는 상기 복수의 위치 값들에 기반한 보간법에 따라 획득된 위치 값을 상기 위치 정보로서 획득하고, 상기 측량의 정밀도가 상기 제3 옵션으로 설정되면, 상기 모바일 단말과 통신하는 DGPS 장치로부터 획득된 위치 값을 상기 위치 정보로서 획득하고,상기 산림 조사 방법은,상기 모바일 단말에 의해, 상기 설정된 작업 타입 별로, 상기 사용자가 상이한 정보를 입력 가능하도록 하는 입력 항목을 포함하는 사용자 인터페이스를 제공하는 단계를 더 포함하고,상기 산림 조사는, 상기 산림을 복수의 표준지들로 분할하여 각각의 표준지를 조사하는 표준지 조사이고, 상기 표준지들의 각각은 형태 및 면적이 미리 설정되어 있고, 상기 사용자 인터페이스를 제공하는 단계는, 상기 표준지들 중 조사의 대상이 되는 표준지에 포함된 나무들의 각 나무의 상태를 입력 가능하도록 하는 상기 각 나무에 대응하는 입력 항목을 포함하는 사용자 인터페이스를 제공하고,상기 각 나무에 대응하는 입력 항목은 상기 표준지에 대한 조사점에 대응하고,상기 각 나무에 대해 입력된 상기 각 나무의 상태에 따라 상기 각 나무에 대응하는 입력 항목은 상이하게 표시되는, 산림 조사 방법.제1항 내지 제7항 및 제10항 중 어느 한 항의 방법을 수행하는 컴퓨터 판독 가능 기록매체에 저장된 컴퓨터 프로그램., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

31/1150 Row 31: application_number: 1020190125967, combined_string: invention_title: 연결관이 구비되는 유공관 abstract: 본 발명은 연결관이 구비되는 유공관에 관한 것으로, 일반적인 토양이나, 배수가 불량한 혐기성 토양에 설치되어 수목 뿌리의 호흡작용을 돕고, 호기성 토양으로의 변환을 도와 수목에게 유리한 미생물들의 생육 환경을 조성하여 수목의 발육을 촉진하도록 수목의 주변 토양 내에 수직방향으로 설치되는 유공관의 외주연에 다수개의 결합편을 하나의 군 단위로 돌출형성하고, 하나의 군 단위로 돌출형성된 결합편에 연결관의 결합홈이 탈착가능하게 결합됨으로써 유공관에 설치된 연결관의 위치 변경이 자유로울 뿐만 아니라, 별도의 이음관이 요구됨이 없이 유공관에 다수개의 연결관의 연결설치가 가능하며, 하나의 군 단위로 돌출형성되는 결합편들의 중심부에 동심원 상으로 투수공이 형성되어 유공관에 연결관의 연결 시 동심원 상으로 관통형성되는 투수공을 통해 유공관의 물 및 공기가 연결관으로 유입 및 순환되도록 하는 연결관이 구비되는 유공관을 제공하기 위한 것이다. claims: 식재된 수목 주변의 토양 내에 수직방향으로 적어도 하나 이상으로 설치되되, 내부에 중공을 갖는 관 형상체로서, 외주연에 돌출형성되는 적어도 하나 이상의 결합부, 및 외주연에 관통형성되는 적어도 하나 이상의 투수공을 포함하는 유공관; 및상기 각 유공관 사이에 배치되되, 그 일측 및 타측이 각 유공관에 결합되어 각 유공관을 상호 연결하며, 외주연에 적어도 하나 이상의 투수공이 관통형성되고, 내부에 중공을 갖는 관 형상체로서, 중심부에 일정 길이를 갖되, 원통형상으로 형성되는 본체와, 상기 본체의 양 단부에 구비되되, 자바라 형태의 주름진 관으로 형성되는 신축관, 및 상기 신축관의 각 단부에 플랜지 형태로 형성되되, 일측면 단부에 상기 유공관의 결합부가 삽입결합되도록 적어도 하나 이상의 결합홈을 갖는 결합관을 포함하는 연결관;을 포함하여 구성되고,상기 결합부는 핀 형태로 형성되되, 상기 유공관의 외주연에 형성되는 연결편, 및 상기 연결편의 단부에 형성되되, 연결편의 직경보다 큰 직경을 갖는 결합편을 포함하고, 상기 결합홈은 ㅓ자 형태로 형성되되, 입구측 직경이 상기 결합부의 연결편 직경과 동일 또는 약간 크게 형성되고, 상기 결합홈의 내부측 직경이 상기 결합부의 결합편 직경에 대응되게 형성되며,상기 결합편은 그 길이방향 양 단부 가장자리가 라운드 형태로 형성되고, 상기 결합홈 내의 입구측에서 내측을 향하여 직경의 크기가 달라지도록 라운드 형태로 형성되며, 상기 결합편을 결합홈에 인입 또는 인출 시 라운드 형태로 형성되는 결합편의 양 단부가 결합홈의 입구측에 맞닿아 슬라이딩하면서 변형되어 결합홈의 입구측을 통과하도록 이루어지며,상기 유공관의 외주연에 돌출형성되는 결합부는 마름모꼴 형태를 이루는 상, 하, 좌, 우 4개를 하나의 군으로 형성하고, 상기 하나의 군으로 형성되는 4개의 결합부 중심부에 원호를 그리면서 동심원 형태로 다수개의 투수공이 배치되며, 상기 결합홈은 연결관의 결합관 단부 상, 하, 좌, 우에 각각 형성되며,상기 연결관의 결합관 단부에 형성되는 각 결합홈 사이에는 1/4 원호 형태의 밀폐홈이 각각 형성되고, 상기 각 밀폐홈에는 밀폐부재가 삽입설치되되, 상기 밀폐부재는 합성수지재질로 이루어지되, 단면이 H자 형상으로 형성되고, 상기 밀폐홈은 상기 밀폐부재의 형상에 대응되도록 형성되되, 입구의 크기가 그 내부의 크기보다 작게 형성되며,상기 밀폐부재의 일측 단부는 밀폐홈의 입구 및 내부에 결합되고, 그 타측 단부는 밀폐홈의 외부로 노출 및 돌출되게 결합되되, 유공관의 외주연에 맞닿게 설치되는 것을 특징으로 하는 연결관이 구비되는 유공관., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

32/1150 Row 32: application_number: 1020190123699, combined_string: invention_title: 왜성 체리나무 재배방법 abstract: 본 발명은 재배 관리 및 과실 수확이 용이한 왜성 체리나무 재배방법에 관한 것으로, 흙 10~30 중량부와, 마사토 20~40중량부와, 소나무톱밥 35~55중량부와, 미강 40~60중량부를 혼합한 배양토를 상향 개방의 부직포 화분(2)에 채운 다음 대목에 접목된 체리나무(3)를 심어 관수 재배 및 전지함으로써 1.6~2.2m 수고(樹高)의 왜성 체리나무(3)로 재배되어 사다리나 받침대 없이도 재배 관리가 쉬울 뿐 아니라 과실(39)을 쉽게 수확할 수 있으며, 관상수로 키울 수도 있다.상기 전지는, a) 식재 후 10월~11월 무렵 접목 부위에서 20~40㎝ 올라간 접수 부분을 전지하고, b) 식재 1년 후 5~8개의 원 가지를 받아 기른 다음 가을이나 이듬해 봄에 20~40㎝ 남기고 전지하고, c) 식재 후 2년차에 원 가지에서 새로 나온 가지 20~40㎝ 위를 전지하고 곁가지 나온 것을 정리하고, d) 원 가지에서 새로 나온 가지의 20~40㎝ 위를 전지하고 곁가지도 전지하여 최종 수고가 1.6~2.2m가 되는 와인잔 형상의 체리나무(3)를 재배할 수 있다. 본 발명은 노지 또는 시설재배지에 대목에 접목된 체리나무(3)를 심어 관수 재배 및 전지함으로써 1.6~2.2m 수고(樹高)의 왜성 체리나무(3)로 재배할 수도 있다. claims: 부직포 화분에 배양토를 채워 넣고 대목에 접목된 체리나무를 식재하여 전지 재배하되, 상기 배양토는, 흙 10~30 중량부와 마사토 20~40중량부와 톱밥 35~55중량부와 미강 40~60중량부를 혼합한 것이고, 상기 전지는, a) 식재 후 10월~11월에 접목 부위에서 20~40㎝ 올라간 접수 부분을 전지하고, b) 식재 1년 후 5~8개의 원 가지를 기른 다음 가을이나 이듬해 봄에 20~40㎝ 남기고 전지하고, c) 식재 후 2년차에 원 가지에서 새로 나온 가지 20~40㎝ 위를 전지하고 곁가지 나온 것을 정리하고,d) 원 가지에서 새로 나온 가지의 20~40㎝ 위를 전지하고 곁가지도 전지하여 최종 수고가 1.6~2.2m인 왜성 체리나무 재배방법.노지 또는 시설재배지에 대목에 접목된 체리나무를 식재하여 전지 재배하되, 상기 노지 또는 시설재배지에 구덩이를 판 다음 구덩이에 부직포 화분을 투입한 다음 흙 10~30중량부와 마사토 20~40중량부와 톱밥 35~55중량부와 미강 40~60중량부를 혼합한 배양토를 넣으면서 대목이 접목된 체리나무를 식재하여 재배하고,상기 전지는,a) 식재 후 10월~11월에 접목 부위에서 20~40㎝ 올라간 접수 부분을 전지하고, b) 식재 1년 후 5~8개의 원 가지를 기른 다음 가을이나 이듬해 봄에 20~40㎝ 남기고 전지하고, c) 식재 후 2년차에 원 가지에서 새로 나온 가지 20~40㎝ 위를 전지하고 곁가지 나온 것을 정리하고,d) 원 가지에서 새로 나온 가지의 20~40㎝ 위를 전지하고 곁가지도 전지하여 최종 수고가 1.6~2.2m인 왜성 체리나무 재배방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

33/1150 Row 33: application_number: 1020190122985, combined_string: invention_title: 토양미생물 발효수를 이용한 금화규 재배방법 abstract: 본 발명은 토양미생물 발효수를 이용한 금화규 재배방법에 관한 것으로, (a) 금화규의 노지 이식후부터 개화 5일전까지 3일 간격으로 토양미생물 발효수를 하루 한 번씩 금화규 줄기에 분무하는 단계와; (b) 금화규의 꽃잎 채취 다음날부터 20일간 3일 간격으로 하루 복수 회 금화규 씨방에 토양미생물 발효수를 분무하는 단계와; (c) 씨방 채취 10일후부터 토양미생물 발효수를 5일 간격으로 하루 한 번씩 금화규 줄기에 분무하는 단계로 구성됨으로써, 토양미생물인 바실러스 베레젠시스를 이용하여 유기물을 발효한 천연 액비를 활용하여 인체에 무해한 친환경 농법으로 금화규를 대량 생산할 수 있는 효과가 있다. claims: 금화규의 줄기에 토양미생물 발효수를 분무하여 금화규를 재배하되,상기 토양미생물 발효수는,(A) 천연 유기물 100 중량부에 대하여, 정제수 100 ~ 500 중량부, 토양미생물 0.01 ~ 15 중량부를 밀폐용기에 충전 혼합한 후 30 ~ 42℃에서 2 ~ 6개월 발효한 다음 여과하여 1차 발효물을 제조하는 단계와;(B) 상기 1차 발효물 100 중량부에 대하여, 정제수 50 ~ 30,000 중량부를 첨가한 후 45 ~ 55℃에서 5 ~ 8시간 가열하여 2차 발효물을 제조하는 단계로 제조되고,상기 천연 유기물은 풀, 나무잎, 볏짚, 과일, 채소 및 음식 찌꺼기 중 어느 하나 이상이고,상기 토양미생물은 바실러스 서브틸리스 아종 서브틸리스, 바실러스 벨레젠시스, 바실러스 베레젠시스 중 어느 하나인 것을 특징으로 하는 토양미생물 발효수를 이용한 금화규 재배방법.(a) 금화규의 노지 이식후부터 개화 5일전까지 3일 간격으로 토양미생물 발효수를 하루 한 번씩 금화규 줄기에 분무하는 단계와;(b) 금화규의 꽃잎 채취 다음날부터 20일간 3일 간격으로 하루 복수 회 금화규 씨방에 토양미생물 발효수를 분무하는 단계와;(c) 씨방 채취 10일후부터 토양미생물 발효수를 5일 간격으로 하루 한 번씩 금화규 줄기에 분무하는 단계로 이루어진 토양미생물 발효수를 이용한 금화규 재배방법., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

34/1150 Row 34: application_number: 1020190122229, combined_string: invention_title: 튜브형 수목 물주머니 abstract: 본 발명은 튜브형 수목 물주머니에 관한 것으로, 내부에 물을 채우기 위한 공간이 형성되고, 내부에 물이 채워지는 경우 수목을 감싸도록 튜브 형상을 갖도록 마련되되, 일부가 끊어진 반 튜브 형상을 갖도록 마련된 반 튜브 팩과; 상기 반 튜브 팩의 끊어진 양측 가장자리를 연결하며, 상기 반 튜브 팩이 수목에 감길 때 수목의 두께에 따라 길이를 조절하기 위한 길이 조절 유닛과; 상기 반 튜브 팩으로부터 연장되어 수목에 물을 공급하기 위한 물 공급 튜브를 포함하는 것을 특징으로 한다. 이에 따라, 튜브 형상의 반 튜브 팩에 물이 채워진 상태에서 수목의 둘레를 감싸듯이 반 튜브 팩이 수목에 설치되어, 무게 중심의 분산으로 인해 수목의 생장에 끼치는 영향을 최소화할 수 있게 된다. 또한, 수목을 감싸는 형태로 수목에 설치되어 단순히 거치하거나 일측에 묶어놓은 형태의 종래의 물주머니와 대비할 때 미관이 끼치는 영향을 최소화할 수 있게 된다. claims: 튜브형 수목 물주머니에 있어서,내부에 물을 채우기 위한 공간이 형성되고, 내부에 물이 채워지는 경우 수목을 감싸도록 튜브 형상을 갖도록 마련되되, 일부가 끊어진 반 튜브 형상을 갖도록 마련된 반 튜브 팩과;상기 반 튜브 팩의 끊어진 양측 가장자리를 연결하며, 상기 반 튜브 팩이 수목에 감길 때 수목의 두께에 따라 길이를 조절하기 위한 길이 조절 유닛과;상기 반 튜브 팩으로부터 연장되어 수목에 물을 공급하기 위한 물 공급 튜브를 포함하는 것을 특징으로 하는 튜브형 수목 물주머니., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

35/1150 Row 35: application_number: 1020190116673, combined_string: invention_title: 친환경적인 식물 세척, 식물 영양 공급 및 토양 오염물질 제거용 영양 크리너 조성물 및 이의 제조방법 abstract: 본 발명의 일 예에 따른 영양 크리너 조성물은 락토바실러스 플란타럼(Lactobacillus plantarum) 배양액, 질소 함유 물질, 칼륨 함유 물질, 닥나무 잿물, 식물의 생장에 필요한 미량 원소 함유 물질, 닥나무 농축액, 식물 생장 조절제, 양이온계 중화제 및 음이온계 중화제를 포함한다. 본 발명의 일 예에 따른 영양 크리너 조성물은 구성성분으로 통상적으로 사용되는 계면활성제나 인산 등과 같은 산도 조절제 대신 한지의 제조 공정 중에 버려지는 부산물의 가공에 의해 수득한 닥나무 잿물 및 닥나무 농축액을 포함하기 때문에 경제성과 환경성을 동시에 충족시킬 수 있다. 또한, 본 발명의 일 예에 따른 영양 크리너 조성물은 공해에 오염된 식물체의 세척, 식물에 필요한 영양분의 공급, 토양 내에 과다 축적된 염분, 제설제 등과 같은 토양 오염 원인 물질의 제거, 산도 교정 효과가 우수할 뿐만 아니라 토양의 물리화학적 성질을 변경하여 식물의 생장에 유리하도록 토양을 개량할 수 있는 효과 또한 뛰어나다. claims: 전체 중량을 기준으로 락토바실러스 플란타럼(Lactobacillus plantarum) 배양액 35~55 중량%, 질소 함유 물질 15~35 중량%, 칼륨 함유 물질 6~20 중량%, 닥나무 잿물 0.5~6 중량%, 식물의 생장에 필요한 미량 원소 함유 물질 1~6 중량%, 닥나무 농축액 3~16 중량%, 식물 생장 조절제 0.2~3 중량%, 양이온계 중화제 0.1~2 중량% 및 음이온계 중화제 0.1~2 중량%를 포함하는 조성물로서,상기 닥나무 잿물은 수피(樹皮)가 제거된 닥나무 줄기를 건조시키고 900~1300℃의 가열로에서 연소시켜 재(ash) 형태의 연소물을 수득하고, 상기 연소물을 물(water) 1L를 기준으로 0.05~0.2L의 양으로 첨가하고 물(water)의 온도를 50~80℃로 유지하면서 2~10 hr 동안 교반한 후 여과하여 잔사를 제거한 것이고,상기 닥나무 농축액은 닥나무 1L를 기준으로 물(water) 1.2~2.5L와 함께 밀폐된 상태에서 400~700℃의 온도를 유지하며 12~24 hr 동안 삶은 후 닥나무를 건져서 분리하고 삶은 물을 12~24 hr동안 가열하여 물을 증발시키고 최초 물(water) 부피의 1/10 내지 1/2 수준으로 농축시킨 것이며,상기 조성물은 살아있는 식물체의 표면에 존재하는 오염물질의 세척, 식물의 생장에 필요한 영양분의 공급, 토양 내에 과다 축적된 제설제의 중화 및 토양의 산도 조정을 통해 토양을 개량하고 식물의 생장을 향상시키는 것을 특징으로 하는, 영양 크리너 조성물.(a) 락토바실러스 플란타럼(Lactobacillus plantarum) 배양액을 1차 기초물질로 하여, 여기에 질소 함유 물질, 칼륨 함유 물질 및 닥나무 잿물을 첨가하고 혼합하여 2차 기초물질을 제조하는 단계;(b) 상기 2차 기초물질에 식물의 생장에 필요한 미량 원소 함유 물질을 첨가하고 혼합하여 3차 기초물질을 제조하는 단계; 및(c) 상기 3차 기초물질에 닥나무 농축액, 식물 생장 조절제, 양이온계 중화제 및 음이온계 중화제를 첨가하고 혼합하여 최종 조성물을 제조하는 단계를 포함하는 방법으로서,상기 닥나무 잿물은 수피(樹皮)가 제거된 닥나무 줄기를 건조시키고 900~1300℃의 가열로에서 연소시켜 재(ash) 형태의 연소물을 수득하고, 상기 연소물을 물(water) 1L를 기준으로 0.05~0.2L의 양으로 첨가하고 물(water)의 온도를 50~80℃로 유지하면서 2~10 hr 동안 교반한 후 여과하여 잔사를 제거한 것이고,상기 닥나무 농축액은 닥나무 1L를 기준으로 물(water) 1.2~2.5L와 함께 밀폐된 상태에서 400~700℃의 온도를 유지하며 12~24 hr 동안 삶은 후 닥나무를 건져서 분리하고 삶은 물을 12~24 hr동안 가열하여 물을 증발시키고 최초 물(water) 부피의 1/10 내지 1/2 수준으로 농축시킨 것이며,상기 최종 조성물은 전체 중량을 기준으로 락토바실러스 플란타럼(Lactobacillus plantarum) 배양액 35~55 중량%, 질소 함유 물질 15~35 중량%, 칼륨 함유 물질 6~20 중량%, 닥나무 잿물 0.5~6 중량%, 식물의 생장에 필요한 미량 원소 함유 물질 1~6 중량%, 닥나무 농축액 3~16 중량%, 식물 생장 조절제 0.2~3 중량%, 양이온계 중화제 0.1~2 중량% 및 음이온계 중화제 0.1~2 중량%를 포함하고 살아있는 식물체의 표면에 존재하는 오염물질의 세척, 식물의 생장에 필요한 영양분의 공급, 토양 내에 과다 축적된 제설제의 중화 및 토양의 산도 조정을 통해 토양을 개량하고 식물의 생장을 향상시키는 것을 특징으로 하는, 영양 크리너 조성물의 제조방법., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

36/1150 Row 36: application_number: 1020190115945, combined_string: invention_title: 수목 보호대 abstract: 본 발명은 수목 보호대에 관한 것으로, 수목의 기설정된 높이의 바깥 둘레를 감싸고 있으며, 한쪽 면으로 중첩되어 결착 고정되는 보호몸체; 및 상기 보호몸체의 중첩된 한쪽면에 배치되어 있으며, 상기 보호몸체의 중첩된 위치에 복수 위치로 관통 삽입된 상태에서 열변형에 의해 단면적이 확대되면서 상기 보호몸체의 바깥 면에 융착되는 삽입결착부;를 포함한다. claims: 수목의 기설정된 높이의 바깥 둘레를 감싸고 있으며, 한쪽 면으로 중첩되어 결착 고정되는 보호몸체; 및상기 보호몸체의 중첩된 한쪽면에 배치되어 있으며, 상기 보호몸체의 중첩된 위치에 복수 위치로 관통 삽입된 상태에서 열변형에 의해 단면적이 확대되면서 상기 보호몸체의 바깥 면에 융착되는 삽입결착부;및상기 보호몸체에 설치된 상기 삽입결착부가 삽입 결착된 상태에서 상기 삽입결착부의 상기 보호몸체의 중첩된 부분에서 관통 돌출된 부분을 가열하여 열변형하는 가열변형부;를 포함하되,상기 가열변형부는,상기 보호몸체의 중첩부분에 배치되어 있으며, 상기 삽입결착부의 상기 보호몸체에 삽입 관통한 후에 상부에서 하부로 돌출된 복수 위치로 각각 접촉되는 홈 형태의 변형홈을 가지면서 가열한 상태로 압력을 가하여 열변형 시키는 가열변형몸체; 및상기 가열변형몸체에 일측에 배치되어 있으며, 상기 삽입결착부를 열변형하는 상기 변형홈으로 열기를 발산하도록 상기 가열변형몸체를 가열하는 가열체;를 포함하며,상기 가열체는 상기 가열변형몸체의 내부에 배치되어 있으며, 전력의 공급으로 상기 변형홈 위치에서 가열되는 열선 형태인 가열열선;으로 구비된수목 보호대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

37/1150 Row 37: application_number: 1020190104203, combined_string: invention_title: 식물 생육 관리장치 abstract: 본 발명은 화분에 식립되어 화분에 담긴 흙의 습도, 주변 조도 등을 측정하여 표시하고 화분에 식재된 식물이 실제 자연환경과 유사한 환경에서 생육될 수 있도록 식물에 바람을 제공하여 식물이 생육되는 최적의 환경을 조성하는데 기여하는 식물 생육 관리장치에 관한 것이다. claims: 내부에 흙이 담기고 식물이 심어지는 화분의 흙으로 일부 삽입된 상태에서 화분의 상단 외주 둘레에 거치되는 식물 생육 관리장치에 있어서,식물을 향해 바람을 제공하도록 내부에 송풍팬이 내장되며 송풍팬에 의해 흡입되는 공기가 통과되는 유입부와 흡입된 공기가 바람으로서 배출되는 배출구가 형성되는 토출하우징;상기 토출하우징의 배면에 회동 가능하게 마련되는 클립;상기 클립에 슬라이딩 가능하게 결합되며 흙으로 삽입되어 흙의 습도를 측정하는 습도측정센서; 및상기 토출하우징에 내장되며 식물 주변의 조도를 측정하는 조도측정센서;를 포함하며,상기 토출하우징에는 상기 습도측정센서와 조도측정센서에서 측정한 습도와 조도가 도시되는 디스플레이창이 마련되는 것을 특징으로 하는 식물 생육 관리장치., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

38/1150 Row 38: application_number: 1020190098620, combined_string: invention_title: 내절단성이 강화된 섬유사를 이용하는 망 구조의 해충 방제용 수목 보호대 abstract: 본 발명은 내절단성이 강화된 섬유사를 이용하는 망 구조의 해충 방제용 수목 보호대에 관한 것으로, 상세하게는 HPPE 또는 UHMWPE 섬유사 단독으로 제조된 망, HPPE와 UHMWPE 섬유사에 합성수지 사를 복합하여 제조한 망, 상기 망에 타포린으로 코팅한 망을 평직 또는 라셀형으로 제조한 것이다. 본 발명에 따른 해충 방제용 수목 보호대는 하늘소류의 절단이 불가능하여 탈출을 저지시킴으로써, 소나무재선충병의 방제효과가 우수하다는 것을 확인하였다. claims: HPPE(high-pressure polyethylene) 또는 UHMWPE(Ultra High Molecular Weight Polyethylene) 섬유사를 이용하여 제조된 망 구조의 해충 방제용 수목 보호대., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

39/1150 Row 39: application_number: 2020190003133, combined_string: invention_title: 수목점적관수장치 abstract: 본 고안은 수목점적관수장치에 관한 것으로 보다 상세하게는 수목에 개별적으로 설치하여 생육에 필요한 물 또는 영양제 등을 공급하기 위한 수목점적관수장치는 물을 담수할 수 있도록 내부에 공간부가 형성되고 상부에는 수목에 걸 수 있는 걸이연결구멍이 형성되며, 상측 양측단에는 공간부로 물을 공급할 수 있는 유입공이 형성되고, 상기 공간부 하단면부에는 관통공이 중심부에 형성된 강화패드가 융착되고 상기 강화패드의 관통공과 대응되는 외주면부에는 주입표시부가 형성된 물주머니와 상기 물주머니의 주입표시부를 관통하여 강화패드의 관통공으로 삽입되어 상기 물주머니에 담수된 물을 수목에 공급하도록 하는 주사부를 포함하여 이루어진 구조이다. claims: 물을 담수할 수 있도록 내부에 공간부가 형성되고 상부에는 수목에 걸 수 있는 걸이연결구멍이 형성되며, 상측 양측단에는 공간부로 물을 공급할 수 있는 유입공이 형성되고, 상기 공간부 하단면부에는 관통공이 중심부에 형성된 강화패드가 융착되고 상기 강화패드의 관통공과 대응되는 외주면부에는 주입표시부가 형성된 물주머니와;상기 물주머니의 주입표시부를 관통하여 강화패드의 관통공으로 삽입되어 상기 물주머니에 담수된 물을 수목에 공급하도록 하는 주사부를 포함하여 이루어진 것이며,상기 주사부는; 상기 물주머니의 공간부에 담수된 물이 유입될 수 있도록 일측단에 유입공이 형성되고 중심부에는 유입공과 연통된 통공이 형성된 바늘부와; 상기 바늘부의 하단에는 상기 바늘부의 통공와 연통된 통공이 중심부에 형성되며 상부에는 물주머니의 외주면을 지지하는 날개편이 형성된 몸체부와; 상기 몸체부의 하부결착되어 상기 몸체부의 통공으로 부터 유입되는 물을 담수하는 담수공간부가 형성되고 상기 담수공간부의 하단에는 담수공간부의 물을 수목에 공급하도록 소정의 길이로 형성된 공급호스가 구비된 공급부를 포함하여 이루어진 것을 특징으로 하는 수목점적관수장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

40/1150 Row 40: application_number: 1020190085071, combined_string: invention_title: 잡초 생장 억제 구조물 abstract: 본 발명은 잡초생성억제, 재배지 보온 및 습도 유지 구조물에 관한 것으로서, 보다 상세하게는 합성 수지 또는 플렉서블한 재질로 만들어져 설치 및 철거작업이 용이하고, 요철 결합으로 철거 후 재사용이 가능한 잡초생성억제, 재배지 보온 및 습도 유지 구조물에 관한 것이다. claims: 재배식물의 크기에 따라 크기가 정해지는 관통 홀(12-1)을 포함하는 생장보호판(12); 및상기 한쌍의 생장보호판(12) 사이에 결합되며, 핀홀(11-1)을 포함하는 사이드고정판(11);를 포함하는 잡초생성억제, 재배지 보온 및 습도 유지 구조물.폴리에틸렌 필름로 이루어지고, 복수개가 열융착 결합 가능하며, 재배식물의 크기에 따라 크기가 정해지는 관통 홀을 포함하는 조립식 생장 억제 시트(12);상기 생장 억제 시트에, 물이 재배식물에 공급되도록 형성되는 수로(12-2);상기 수로(12-2)와 호스(22)로 연결되어 물을 공급하는 물저장부(21);를 포함하는 잡초생성억제, 재배지 보온 및 습도 유지 구조물.일정 재질로 이루어지고, 복수개가 분리 결합 가능하며, 재배식물의 크기에 따라 크기가 정해지는 관통 홀 또는 고정 핀홀이 형성된 멀칭패널;상기 멀칭패널의 관통 홀과 일정 간격 이격되어 형성되고 상기 관통 홀에 연장된 연장호스에 외부의 물을 공급하는 수로(12-2);를 포함하는 잡초생성억제, 재배지 보온 및 습도 유지 구조물.플렉서블한 일정 재질로 이루어지고, 복수개가 열융착으로 결합 가능하며, 재배식물의 크기에 따라 크기가 정해지는 관통 홀 또는 고정 핀홀이 형성된 멀칭패널;상기 멀칭패널의 관통 홀과 일정 간격 이격되어 형성되고 상기 관통 홀에 연장된 연장호스에 외부의 물을 공급하는 수로(12-2);를 포함하는 잡초생성억제, 재배지 보온 및 습도 유지 구조물., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

41/1150 Row 41: application_number: 1020190084597, combined_string: invention_title: 과실나무의 생장 촉진을 위한 토양조성방법 abstract: 본 발명은 과실나무의 생장 촉진을 위한 토양조성방법에 관한 것으로서, 보다 상세하게는 과실나무가 심겨진 밭에 과실나무를 둘러싸고 부직포층과 자갈층을 형성시켜 잡초성장을 억제함과 동시에, 자갈층에 반사되는 햇빛이 과실나무에 효과적으로 도달되게 함으로써 과실나무의 생장을 촉진시키는 토양조성방법에 관한 것이다.본 발명에 따르면, 과실나무 주위에 있는 잡초의 생장이 억제될 뿐만 아니라, 자갈층에 반사된 햇빛이 과실나무에 전달됨으로써, 과실나무의 생장이 촉진되는 효과가 있다. claims: 과실나무(1)를 둘러싸는 지면(F) 아래 소정영역의 토양(G)을 파내어 과실나무(1)의 기둥을 지나는 직선 위에 위치한 구의 중심(M1)으로부터 소정 반경(r1)을 가진 구면 형상으로 반사곡면(R)을 형성시키는 단계(S110);과실나무(1)를 둘러싸고 원통형의 자갈차단틀(10)을 형성시키는 단계(S120);반사곡면(R)에 자갈차단틀(10)을 소정 깊이(d1) 삽입하여 반사곡면(R)으로부터 소정 높이(d2) 돌출형성시키는 단계(S130);상기 자갈차단틀(10)의 바깥쪽에 위치한 반사곡면(R)에 부직포를 펼쳐 깔고 고정수단(t)을 이용하여 반사곡면(R)에 고정하여 부직포층(20)을 형성시키는 단계(S140);상기 부직포층(20)의 상부면에 자갈을 깔고 골라서 반사곡면(R)으로부터 동일한 높이(h1)를 가지는 자갈층(30)을 형성시키되, 상기 자갈층(30)의 높이(h1)는 반사곡면(R)으로부터 돌출형성된 자갈차단틀(10)의 높이(d2)보다 작게 되도록 고르는 단계(S150);를 포함하되,상기 S120 단계에서는,원통으로 상호 결합되는 한 쌍의 제1,2반원통부재(11,12)를 준비하는 단계(S121)와,과실나무(1)를 둘러싸고 상기 제1,2반원통부재(11,12)를 서로 마주보게 결합하여 원통형의 자갈차단틀(10)을 형성시키는 단계(S122)를 포함하는 것을 특징으로 하는 과실나무의 생장 촉진을 위한 토양조성방법., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

42/1150 Row 42: application_number: 1020190083524, combined_string: invention_title: 수목과 식물 보호 및 잡초 생장 제한장치 abstract: 본 발명은 수목과 식물들을 보호하는 동시에 수목과 식물들의 밑동 주위에 서 잡초들이 생장하는 것을 제한할 수 있는 장치에 관한 것으로 특히, 물을 모아 뿌리 방향의 지층으로 공급하는 상광하협 형상의 집수판을 구비하여 우천시나 급수시 공급되는 물이 수목이나 식물의 뿌리에 집중 공급될 수 있도록 하고 집수판의 상측부에 내측절곡홈으로 연결되는 안내플랜지를 구비하여 집수판 중앙으로 물이 모일 수 있도록 안내하도록 하며 집수판의 하측부에 외측절곡홈으로 연결되어 지층으로 박혀 지지되는 지지판에 의해 집수판을 안정된 상태로 지지시킨 다음 집수판의 중앙부에 삽입공을 형성하여 지지판이 수목이나 식물의 외곽부를 감싸면서 설치될 수 있도록 하고 조립수단에 의해 집수판을 평면상의 필름 재질로 프레싱하여 형상을 제작한 다음 집수판을 입체적으로 조립할 수 있도록 된 수목과 식물 보호 및 잡초 생장 제한장치를 제공한다. claims: 우천시나 급수시 공급되는 물이 수목이나 식물(142)의 뿌리에 집중 공급될 수 있도록 물을 모아 뿌리 방향의 지층으로 공급하는 상광하협 형상의 집수판(101)과,상기 집수판(101) 중앙으로 물이 모일 수 있도록 안내하기 위해 집수판(101)의 상측부에 내측절곡홈(104)으로 연결되는 안내플랜지(105)와,상기 집수판(101)을 안정된 상태로 지지시키기 위해 집수판(101)의 하측부에 외측절곡홈(102)으로 연결되어 지층으로 박혀 지지되는 지지판(103)과,상기 지지판(103)이 수목이나 식물(142)의 외곽부를 감싸면서 설치될 수 있도록 집수판(101)의 중앙부에 형성되는 삽입공(106)과,상기 집수판(101)을 평면상의 필름 재질로 프레싱하여 형상을 제작한 다음 집수판(101)을 입체적으로 조립하기 위한 조립수단을 구비한 것을 특징으로 하는 수목과 식물 보호 및 잡초 생장 제한장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

43/1150 Row 43: application_number: 1020190080692, combined_string: invention_title: 전자 지도상의 위치 정보를 이용하여 수목을 관리하는 시스템 및 그 방법 abstract: 본 발명은 전자 지도상의 위치 정보를 이용하여 수목을 관리하는 시스템 및 그 방법에 관한 것으로서, 산림조사지역내의 개별목의 정보를 입력하여 서버로 업로딩하는 적어도 하나의 단말기; 및 상기 적어도 하나의 단말기로부터 입력되는 상기 개별목의 정보를 수신하여 다른 단말기로 전송하는 서버; 를 포함한다.또한, 본 발명은 2018년 7월 4일 특허출원한 &amp;quot;전자 지도상의 위치 정보를 이용하여 나무의 병충해를 조사하고 방제하는 시스템 및 그 방법&amp;quot;(한국특허 출원번호 10-2018-0077616호)을 기본으로 하여 국내우선권 주장으로 특허출원한다. 본 발명은 인용된 특허출원 10-2018-0077616호에 비하여 전자 지도상의 위치 정보를 이용하여 수목을 관리하고 산림생장량, 산림자원량, 탄소배출권 중 적어도 하나를 산출할 수 있는 장점을 제공한다. claims: 산림조사지역내의 개별목의 정보를 입력하여 서버로 업로딩하는 적어도 하나의 단말기; 및상기 적어도 하나의 단말기로부터 입력되는 상기 개별목의 정보를 수신하여 다른 단말기로 전송하는 서버; 를 포함하는 전자 지도상의 위치 정보를 이용하여 수목을 관리하는 시스템.제1 또는 제2 사용자 인터페이스에 표시되는 전자 지도상에서 산림조사지역을 선정하는 제1 단계;제1 사용자 인터페이스에서 상기 제1 단계에서 선정된 상기 산림조사지역내의 개별목의 정보를 입력하는 제2 단계; 상기 제2 단계에서 입력된 상기 산림조사지역내의 개별목의 정보를 서버로 업로딩하는 제3 단계; 및 상기 서버는 적어도 하나의 사용자 단말기로부터 상기 업로딩된 상기 개별목의 정보를 다른 사용자 단말기에 전송하는 제4 단계; 를 포함하는 전자 지도상의 위치 정보를 이용하여 수목을 관리하는 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

44/1150 Row 44: application_number: 1020190080343, combined_string: invention_title: 수목 보호용 방초 매트 abstract: 본 발명은 수목 보호용 방초 매트에 관한 것으로, 보다 상세하게는 끝단 둘레가 사선방향으로 절곡된 제1절곡부와, 상기 제1절곡부와 연장되어 측면으로 연장된 제2절곡부가 형성된 방초 매트;와, 상기 방초 매트 중앙에 원형의 제1절취부가 형성되고, 상기 제1절취부를 절취하여 형성된 개구부;와, 상기 개구부 일측 끝단에서 방초 매트 끝단까지 연장된 제2절취부가 형성되고, 상기 제2절취부를 절취하여 형성된 절개부;를 포함하되, 상기 방초 매트 상부면에는 수목 이력사항이 기재된 수목안내부가 더 설치되고, 상기 절개부 양측에 벨크로를 설치하여 상호 고정시켜 수목 밑둥을 감싸 고정시키고, 상기 개구부 끝단 둘레에 제1삽입홈이 형성되고, 상기 제1삽입홈에 와이어가 삽설되어 상기 와이어가 수목 밑둥 둘레를 감싸고 조인 후 고정하여 방초 매트가 미끄러지는 것을 방지하는 것을 특징으로 한다. claims: 끝단 둘레가 사선방향으로 절곡된 제1절곡부(101)와, 상기 제1절곡부(101)와 연장되어 측면으로 연장된 제2절곡부(102)가 형성된 방초 매트(100)와, 상기 방초 매트(100) 중앙에 원형의 제1절취부(11)가 형성되고, 상기 제1절취부(11)를 절취하여 형성된 개구부(10)와, 상기 개구부(10) 일측 끝단에서 방초 매트(100) 끝단까지 연장된 제2절취부(21)가 형성되고, 상기 제2절취부(21)를 절취하여 형성된 절개부(20);를 포함하는 수목용 방초 매트에 있어서,상기 방초 매트(100) 상부면에는 수목 이력사항이 기재된 수목안내부(30)가 더 설치되고, 상기 절개부(20) 양측에 벨크로(40)를 설치하여 수목 밑둥을 감싸서 상호 고정되고, 상기 개구부(10) 끝단 둘레에 제1삽입홈(51)이 형성되며 상기 제1삽입홈(51)에 와이어(50)가 삽설되어 상기 와이어(50)가 수목 밑둥 둘레를 감싸고 조임으로서 방초 매트(100)가 미끄러지는 것을 방지하고, 상기 제1절취부(11)는 방초 매트(100) 중앙 둘레에 크기별로 다수개 설치되어 수목 밑둥의 크기에 맞도록 선택적으로 절취하도록 이루어지며, 상기 제2절곡부(102) 하부면에 미끄럼 방지 패드(12)를 설치하여 방초 매트(100)의 유동을 방지하도록 이루어지되,상기 제1삽입홈(51)에는 제1고정삽입부(53)가 삽설되되, 상기 제1고정삽입부(53) 양측에 하방으로 절곡되고 끝단에 돌기(55)가 형성되어 상기 돌기(55)가 지면에 삽입되어 방초 매트(100)를 고정하는 제3절곡부(103)와;상기 방초 매트(100) 끝단 둘레에는 제2삽입홈(52)이 형성되고,상기 제2삽입홈(52)에는 제2고정삽입부(54)가 삽설되되, 상기 제2고정삽입부(54) 양측에 하방으로 절곡된 제4절곡부(104)가 형성되며, 상기 제4절곡부(104) 끝단에 돌기(55)가 형성되어 상기 돌기(55)가 지면에 삽입되어 방초 매트(100)를 견고히 고정하는 것을 특징으로 하는 수목 보호용 방초 매트., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

45/1150 Row 45: application_number: 1020190075485, combined_string: invention_title: 평형함수율을 이용한 산림연료습도의 추정방법 및 시스템 abstract: 본 발명은 산악기상관측망 기상자료를 이용하여 평형함수율을 산출하는 단계; 평형함수율을 이용하여 10시간 사연료습도와의 선형회귀식을 얻는 단계; 상기 선형회귀식을 이용하여 10시간 사연료습도를 산출하는 단계; 및 상기 10시간 사연료습도를 이용하여 산림연료습도를 추정하는 단계를 포함하는 평형함수율을 이용한 산림연료습도의 추정방법 및 시스템을 제공한다. claims: 산악기상관측망 기상자료를 이용하여 평형함수율을 산출하는 단계;평형함수율을 이용하여 10시간 사연료습도와의 선형회귀식을 얻는 단계;상기 선형회귀식을 이용하여 10시간 사연료습도를 산출하는 단계; 및상기 10시간 사연료습도를 이용하여 산림연료습도를 추정하는 단계를 포함하는 평형함수율을 이용한 산림연료습도의 추정방법. 산악기상관측망(AMOS) 기상자료를 제공하는 기상자료제공수단; 산악기상관측망 기상자료를 이용하여 평형함수율을 산출하는 평형함수율산출수단; 평형함수율을 이용하여 10시간 사연료습도와의 선형회귀식을 얻는 선형회귀식도출수단; 상기 선형회귀식을 이용하여 10시간 사연료습도를 산출하는 사연료습도산출수단; 및 상기 10시간 사연료습도를 이용하여 산림연료습도를 추정하는 산림연료습도추정수단;을 포함하는 평형함수율을 이용한 산림연료습도의 추정시스템., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

46/1150 Row 46: application_number: 1020190074709, combined_string: invention_title: 보행자 안전과 지중 시설물 보호를 위한 수목뿌리 보호 생장 유도 장치 abstract: 본 발명은 수목 뿌리 생장방향을 유도하는 장치에 관한 것으로 더욱 상세하게는 하부 내주면 지름이 상부 내주면 지름보다 소폭 큰 형상을 이루고, 수평수공 및 수직수공이 형성되는 식재측벽체와 자갈채움층이 형성되도록 식재측벽체 외방으로 형성되는 지반측벽체 등으로 인위적 조성 및 물리적으로 수목 뿌리 생장방향을 이루어 수분 및 산소 공급등의 생장환경을 최적화시키는 것이며, 그에 따라서 수목의 생장을 돕고, 수목 식재 후 수목 뿌리가 지면 상부 또는 도로 하부나 시설물 하부로 자라는 것을 방지하여 수목의 고사를 억제하는 보행자 안전과 지중 시설물 보호를 위한 수목뿌리 보호 생장 유도 장치에 관한 것이다.이상에서 설명한 바와 같이 본 발명에 의한 보행자 안전과 지중 시설물 보호를 위한 수목뿌리 보호 생장 유도 장치는 단지, 도로 및 공원등에 식재되는 수목 뿌리의 생장방향을 하방으로 하여 뿌리가 지면 상방으로 노출되거나 지중 시설물로 생장되는 것을 방지하여 차량 및 보행자의 통행 방해를 방지하고, 뿌리로 인한 시설물 파손을 방지하며, 자갈채움층을 형성하고, 복수개의 수평수공과 수직수공을 구성하여 뿌리로 수분 및 산소공급과 뿌리에서 발생되는 이산화탄소 배출을 원활히 하여 수목 생장을 원활히 실시하며, 자갈채움층을 형성하고, 공극을 가지는 현무암 재질의 잔자갈을 충진하며, 공극사이로 유용미생물을 주입하여 수목 생장에 도움을 준다. claims: 수목 뿌리의 생장방향을 유도하는 장치에 있어서,상기 장치는 평면상 원형 또는 다각형으로 중앙이 개방되어 식재공간을 가지고, 하부 내주면 지름이 상부 내주면 지름보다 소폭 큰 형상을 이루며, 수목 뿌리에 수분과 산소를 공급하고, 수목 뿌리로부터 발생되는 이산화탄소의 배출를 위해 측면에 복수개의 수평수공이 형성된 식재측벽체; 및상기 식재측벽체와 동일한 형상으로 식재측벽체의 하단이 하단돌출부로 연결되고, 식재측벽체의 외방을 감싸되 식재측벽체와 소정거리 떨어져 자갈을 채울수 있는 공간인 자갈채움층이 형성되며, 상기 자갈은 현무암으로 잔자갈로 이루어 충진되는 지반측벽체;를 포함하여 이루어지고,상기 하단돌출부는 자갈채움층이 형성된 하부면에 사용자에 의하여 공급되는 수분 또는 우수등이 원지반으로 침투시키기 위해 복수개의 수직수공을 형성하고, 상기 지반측벽체는 상부 끝단에 외방으로 돌출된 상단돌출부가 지면상방으로 형성되어 지면에 설치되되 표층블럭의 상방에 위치시켜 보행자 및 차량으로부터 수목을 보호하며,상기 상단돌출부와 지반측벽체 외방으로 돌출된 하단돌출부는 각각 복수개의 상단천공과 하단천공이 구비되고, 상기 상단천공 통해 수목의 줄기 또는 가지를 고정 및 지지하는 케이블이 통과되고 하단천공을 통해 지중에 고정설치되는 지중스크류의 상부에 상기 케이블이 고정되고,상기 자갈은 현무암 재질로 외면에 복수개의 공극을 가지고, 공극사이에 유용미생물(EM, Effective Microorgani는)이 주입되는 보행자 안전과 지중 시설물 보호를 위한 수목뿌리 보호 생장 유도 장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

47/1150 Row 47: application_number: 1020190070705, combined_string: invention_title: 수목 식재용 대나무 유공관과 이를 이용한 수목의 식재방법 abstract: 본 발명은 수목 식재용 대나무 유공관과 이를 이용한 수목의 식재방법에 관한 것으로서, 더욱 상세하게는 수목의 식재시 뿌리 주위에 설치되는 플라스틱 유공관을 천연 소재인 대나무로 대체함으로써 환경보호와 함께 통기성 및 배수성을 향상시킬 수 있는 수목 식재용 대나무 유공관과 이를 이용한 수목의 식재방법에 관한 것이다. 본 발명의 수목 식재용 대나무 유공관은 마디들에 의해 내부가 다수의 공간으로 구획된 대나무를 일정 길이로 자른 후 상기 마디들 전부 또는 일부를 제거하여 형성한 대통과, 대통의 측면을 관통하여 형성시킨 다수의 타공홀들을 구비한다. claims: 마디들에 의해 내부가 다수의 공간으로 구획된 대나무를 일정 길이로 자른 후 상기 마디들 일부를 제거하여 적어도 2개의 마디가 남아있고, 수목의 뿌리방향을 향하도록 하부를 비스듬하게 절단하여 하부가 뾰족한 대통과;상기 대통의 측면을 관통하여 형성시킨 다수의 타공홀들;을 구비하고,상기 대통의 뾰족한 하부에는 상기 타공홀이 미형성되며, 상기 대통에 남아있는 마디들 사이에 양분이 저장된 양분실이 형성되고, 상기 대통에 남아있는 마디들에는 상하로 관통된 연통홀이 형성되며,상기 양분실로 양분을 주입할 수 있도록 상기 대통의 측면에는 주입구가 형성되고, 상기 주입구는 천연수지 또는 황토로 밀폐되고,길이가 서로 다른 대롱들을 상기 대통의 내부에 삽입하여 유체가 통과하는 다수의 유로를 상기 대통의 내부에 상하로 길게 형성하며 상기 대롱들의 하단 위치는 상하방향으로 서로 엇갈리게 형성된 것을 특징으로 하는 수목 식재용 대나무 유공관. 수목을 식재하고자 하는 위치에 일정한 깊이로 구덩이를 파는 굴토단계와;상기 구덩이에 수목의 뿌리분을 안착시키는 뿌리안착단계와;상기 구덩이의 바닥에 대나무 유공관을 박아서 고정시키는 유공관고정단계와;상기 구덩이에 흙을 채워 상기 뿌리분을 매립하되 상기 대나무 유공관의 상부는 지상으로 노출되도록 매립하는 매립단계;를 포함하고,상기 대나무 유공관은 마디들에 의해 내부가 다수의 공간으로 구획된 대나무를 일정 길이로 자른 후 상기 마디들 일부를 제거하여 적어도 2개의 마디가 남아있고 상기 뿌리분을 향하도록 하부를 비스듬하게 절단하여 하부가 뾰족한 대통과, 상기 대통의 측면을 관통하여 형성시킨 다수의 타공홀들을 구비하고,상기 대통의 뾰족한 하부에는 상기 타공홀이 미형성되며, 상기 대통에 남아있는 마디들 사이에 양분이 저장된 양분실이 형성되고, 상기 대통에 남아있는 마디들에는 상하로 관통된 연통홀이 형성되며,상기 양분실로 양분을 주입할 수 있도록 상기 대통의 측면에는 주입구가 형성되고, 상기 주입구는 천연수지 또는 황토로 밀폐되고, 상기 유공관고정단계는 상기 대나무 유공관이 상기 뿌리분을 비스듬하게 관통하도록 고정시켜 상기 대나무 유공관에 의해 상기 뿌리분이 지지되는 것을 특징으로 하는 대나무 유공관을 이용한 수목의 식재방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

48/1150 Row 48: application_number: 1020190062936, combined_string: invention_title: 자립식 수목관수용 물통 abstract: 본 발명은 자립식 수목 관수용 물통에 관한 것으로, 상세하게는, 자립식으로 수목이 지면과 교차하는 수간부에 그 수간을 에워싸도록 수목에 고정 설치되고, 관수량을 조절하는 밸브를 일체형으로 구비하여 상기 밸브를 매개로 내부에 채워져 있는 물을 점적관수 방식으로 수목으로 공급하는 자립식 수목관수용 물통에 관한 것이다. claims: 각각 물이 저장되는 물 저장공간이 마련되어 있고, 일단부가 서로 접철 가능하게 결합되어 수목(1)의 수간을 에워싼 상태로 결속부(15)에 의해 결속되는 제1 및 제2 물탱크(11, 12);상기 제1 및 제2 물탱크(11, 12)를 상호 연결하여 상기 제1 물탱크(11)에 마개(16)에 의해 밀폐되도록 형성된 주입구(11a)를 통해 주입되어 상기 제1 물탱크(11)에 저장된 물을 상기 제2 물탱크(12)로 공급하는 연결관(13);상기 제1 물탱크(11)의 하부에 형성된 배수구(11c)에 설치되고, 상기 제1 물탱크(11)의 배수구(11c)를 통해 배출되는 물을 수목으로 급수하는 급수밸브(14);상기 제1 및 제2 물탱크(11, 12)의 상단 내측에는 상기 수목(1)의 수간부에 묶음끈을 이용하여 안정적으로 고정하기 위해 일정 간격으로 설치된 복수 개의 고리(18);를 포함하며,상기 제1 및 제2 물탱크(11, 12)의 내측 하부에는 상기 제1 및 제2 물탱크(11, 12)를 상호 결속할 때 상기 연결관(13)이 간섭되지 않도록 상기 연결관(13)이 내부로 매입되는 매입홈(11b, 12a)이 형성되어 있고, 상기 제1 및 제2 물탱크(11, 12)의 타측부 하단에는 상기 급수밸브(14)를 외부에서 조작할 수 있도록 상기 제1 및 제2 물탱크(11, 12)가 상호 결합된 상태에서 상기 급수밸브(14)가 외부로 노출되도록 급수밸브 조작용 홈(10a)이 형성되어 있으며,상기 제1 및 제2 물탱크(11, 12)는 상기 결속부(15)에 의해 상기 수목(1)의 수간을 에워싸도록 상호 결속된 상태에서 상단부에서 하단부로 갈수록 균일하게 지름이 증가하는 원추형 구조로 이루어지고, 각각의 내측면에는 상기 수목(1)의 수간부 외주면에 대응하여 오목한 반호 형상을 갖도록 형성되고,상기 연결관(13)은 상기 제1 및 제2 물탱크(11, 12)의 전개시 당겨지는 힘에 의해 길이가 늘어나고, 결속시에는 원상태로 복귀하여 상기 제1 및 제2 물탱크(11, 12)의 전개 및 결속시 방해가 되지 않도록 길이가 가변되는 주름관으로 이루어지는 것을 특징으로 하는 자립식 수목관수용 물통., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

49/1150 Row 49: application_number: 1020190058973, combined_string: invention_title: 캄포 나무의 수액 추출 방법 abstract: 본 발명은 캄포 나무 수액 추출 방법을 개시한다. 이러한 본 발명은 벌목된 캄포 나무를 가공한 것을 가열하여 수액 증류수를 추출하는 것이고, 이를 통해 생육 상태의 나무로부터 수액 추출시 초래되는 종래의 각종 문제점을 개선하고, 추출된 수액 증류수를 미용 제품에 도포 또는 함유시키면서 화학 원료 사용없이 안전한 친환경적인 미용 제품을 제공하는 것이다. claims: (a) 벌목된 캄포 나무 원목을 일정크기로 제재기로 가공하는 공정;(b) 상기 (a)공정으로부터 가공되는 일정크기의 캄포 나무 원목을 가열하여 수액 증류수를 추출하는 공정; 및,(c) 상기 (b)공정으로부터 추출되는 수액 증류수를 필터를 이용하여 불순물을 제거하는 공정; 을 포함하는 것을 특징으로 하는 캄포 나무의 수액 추출 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

50/1150 Row 50: application_number: 1020210077868, combined_string: invention_title: 천연물 복합 추출물을 함유하는 모발 건강 개선용 식품 또는 화장료 조성물 abstract: 본 발명은 건조 조성물 중량 기준으로 구절초 추출물 5~25%, 페퍼민트 추출물 65~85% 및 감초 추출물 5~15%를 포함하는 복합 생약 추출물을 유효성분으로 함유하는 모발 건강 개선용 조성물에 관한 것이다. claims: 구절초 추출물 5~25 중량%, 페퍼민트 추출물 65~85 중량% 및 감초 추출물 5~15 중량%를 포함하는 복합 생약 추출물을 유효성분으로 함유하고,여기서, 상기 생약 추출물은 물, C1~C4의 저급알코올 또는 이들의 혼합물로 40 내지 100℃의 온도에서 1시간 이상 추출되고,당귀 추출물, 은행잎 추출물 및 병풀잎 추출물 중 하나 이상을 함유하지 않는 것인, 탈모 방지 또는 발모 개선용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

51/1150 Row 51: application_number: 1020210059871, combined_string: invention_title: 천연물질의 선택적 추출 방법 abstract: 비극성 천연물질의 추출 방법이 개시된다. 본 발명의 일 실시예에 따른 비극성 천연물질의 추출 방법은, 중대가리풀(Centipeda minima), 삼푸트리(Litsea glutinous), Arnica 속 식물 및 Helenium 속 식물로 이루어진 그룹에서 선택된 어느 하나 이상을 포함하는 천연물 원료를 추출하여 1차 추출액을 제조하는 단계, 1차 추출액에 친유성 가용화제를 포함하는 상분리 조성물을 혼합하여 상기 1차 추출액 내 Brevilin A 또는 이의 유도체들을 용해 및 가용화시켜 고농축된 상분리 2차 추출액을 제조하는 단계 및 상분리된 용액의 상층을 분리하여 Brevilin A 또는 이의 유도체들을 수득하는 단계를 포함한다. 따라서, 비극성 천연물질을 용해-유화 추출법(Dissolution-Emulsion Extract, DEE)을 이용하여 고효율로 비교적 용이하게 추출할 수 있다. claims: 중대가리풀(Centipeda minima), 삼푸트리(Litsea glutinous), Arnica 속 식물 및 Helenium 속 식물로 이루어진 그룹에서 선택된 어느 하나 이상을 포함하는 천연물 원료를 추출하여 1차 추출액을 제조하는 단계; 1차 추출액에 친유성 가용화제를 포함하는 상분리 조성물을 혼합하여 상기 1차 추출액 내 Brevilin A 또는 이의 유도체들을 용해 및 가용화시켜 고농축된 상분리 2차 추출액을 제조하는 단계; 및 상분리된 용액의 상층을 분리하여 Brevilin A 또는 이의 유도체들을 수득하는 단계를 포함하는 비극성 천연물질의 추출 방법.친유성 가용화제를 포함하는 상분리 조성물을 이용하여 중대가리풀(Centipeda minima), 삼푸트리(Litsea glutinous), Arnica 속 식물 및 Helenium 속 식물로 이루어진 그룹에서 선택된 어느 하나 이상을 포함하는 천연물 원료로부터 Brevilin A 또는 이의 유도체들을 용해 및 가용화시켜 고농축된 상분리된 추출액을 제조하는 단계; 및 상분리된 용액의 상층을 분리하여 Brevilin A 또는 이의 유도체들을 수득하는 단계를 포함하는 비극성 천연물질의 추출 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

52/1150 Row 52: application_number: 1020210054372, combined_string: invention_title: 천연 추출물을 포함하는 패드용 화장료 조성물 abstract: 본 발명은 어성초 잎 추출물, 실크 피브로인, 상백피 추출물, 및 당근 추출물을 유효성분으로 포함하는 패드용 화장료 조성물 및 상기 화장료 조성물이 함침된 화장용 패드에 관한 것이다.본 발명의 어성초 잎 추출물, 실크 피브로인, 상백피 추출물, 및 당근 추출물을 포함하는 조성물은 여드름균에 대한 항균 활성 및 피부 미백 활성이 우수할 뿐만 아니라, 이를 화장 패드에 적용함으로써 사용 편의성을 높이고, 각질 제거 등의 피부 개선 효과를 가짐을 확인하였다. claims: 어성초 잎 추출물 4 내지 7 중량부, 실크 피브로인 10 중량부, 상백피 추출물 0.1 내지 3 중량부, 당근 추출물 0.1 내지 3 중량부, 익모초 추출물 1 중량부, 및 창이자 추출물 1 중량부를 포함하는 패드용 화장료 조성물로서,상기 패드용 화장료 조성물은 화장용 패드에 함침시켜 사용되는 것이며,상기 조성물은 프로피오니박테리움 아크네스(Propionibacterium acnes) 균주 및 스태필로코커스 에피더미스(Staphylococcus epidermidis) 균주에 대한 항균 활성, 미백 활성 및 각질 제거 효과를 나타내는 것을 특징으로 하는, 패드용 화장료 조성물.제1항의 화장료 조성물이 함침된 화장용 패드., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

53/1150 Row 53: application_number: 1020210048957, combined_string: invention_title: 복합 세라마이드 및 천연 추출물을 포함하는 피부개선용 화장료 조성물 abstract: 본 발명은 5종의 복합 세라마이드 및 천연 추출물을 포함하는 피부 개선용 화장료 조성물에 관한 것으로, 구체적으로 5종의 복합 세라마이드 및 서양민들레잎 추출물이 피부 내 마이크로바이옴 균형 유지 및 피부장벽강화 효능을 가지는 피부 개선용 화장료 조성물 및 이의 제조방법에 관한 것이다. claims: 세라마이드이오피(EOP), 세라마이드엔에스(NS), 세라마이드엔피(NP), 세라마이드에이에스(AS) 및 세라마이드에이피(AP)가 1~1.5 : 1~1.5 : 1~3 : 1~1.5 : 1~1.5의 비율로 이루어진 세라마이드; 서양민들레잎 추출물; 및락토바실러스 발효용해물;을 포함하는 피부 내 마이크로바이옴 균형 유지용 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

54/1150 Row 54: application_number: 1020210047621, combined_string: invention_title: 천연 추출물을 포함하는 살균소독용 조성물 abstract: 본 발명은 염화알킬벤질디메틸암모늄; 알킬디메틸에틸벤질암모늄클로라이드; 및 잔대, 하고초, 골풀, 모시풀 및 길경의 혼합 추출물;을 포함하는 살균 또는 소독용 조성물, 상기 조성물의 제조 방법, 상기 조성물을 이용한 소독 방법, 상기 조성물을 포함하는 액상형 소독제, 화장실 청소용 소독제 및 의약외품 조성물에 관한 것이다.본 발명은 잔대, 하고초, 골풀, 모시풀 및 길경의 혼합 추출물을 염화알킬벤질디메틸암모늄 및 알킬디메틸에틸벤질암모늄클로라이드와 함께 포함하는 조성물이 불쾌한 향을 유발하지 않으면서도 뛰어난 항균, 항바이러스 활성을 나타냄을 확인한 바, 독성을 유발할 수 있는 화합물의 함량은 감소시켜 안전하면서도 친환경적인 살균소독제로 유용하게 활용될 수 있다. claims: 염화알킬벤질디메틸암모늄 1 내지 3 중량부; 알킬디메틸에틸벤질암모늄클로라이드(alkyldimethyl(ethylbenzyl)amonium chloride) 1 내지 3 중량부; 및 잔대(Adenophora triphylla), 하고초(Prunella vulgaris), 골풀(Juncus effusus), 모시풀(Boehmeria nivea) 및 길경(Platycodon grandiflorum)을 각각 3:3:3:1:1의 중량비로 혼합하여 추출한 혼합 추출물 10 내지 20 중량부;를 포함하는, 소독용 조성물로서,상기 혼합 추출물은 50%(v/v) 에탄올로 추출된 것인, 소독용 조성물.염화알킬벤질디메틸암모늄 1 내지 3 중량부; 알킬디메틸에틸벤질암모늄클로라이드(alkyldimethyl(ethylbenzyl)amonium chloride) 1 내지 3 중량부; 및잔대(Adenophora triphylla), 하고초(Prunella vulgaris), 골풀(Juncus effusus), 모시풀(Boehmeria nivea) 및 길경(Platycodon grandiflorum)을 각각 3:3:3:1:1의 중량비로 혼합하여 추출한 혼합 추출물 10 내지 20 중량부;를 혼합하는 단계를 포함하는, 소독용 조성물의 제조 방법으로서,상기 혼합 추출물은 50%(v/v) 에탄올로 추출된 것인, 소독용 조성물의 제조 방법.제1항의 소독용 조성물을 이용한 인체를 제외한 물체의 소독 방법.제1항의 소독용 조성물을 포함하는 액상형 소독제.제1항의 소독용 조성물을 포함하는 화장실 청소용 소독제.염화알킬벤질디메틸암모늄 1 내지 3 중량부; 알킬디메틸에틸벤질암모늄클로라이드(alkyldimethyl(ethylbenzyl)amonium chloride) 1 내지 3 중량부; 및 잔대(Adenophora triphylla), 하고초(Prunella vulgaris), 골풀(Juncus effusus), 모시풀(Boehmeria nivea) 및 길경(Platycodon grandiflorum)을 각각 3:3:3:1:1의 중량비로 혼합하여 추출한 혼합 추출물 10 내지 20 중량부;를 포함하는, 살균용 조성물로서,상기 혼합 추출물은 50%(v/v) 에탄올로 추출된 것인, 살균용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

55/1150 Row 55: application_number: 1020210046402, combined_string: invention_title: 천연 공융용매로 추출한 쓴풀, 서양고추나물 및 하늘타리 혼합추출물을 함유하는 피부 미백용 화장료 조성물 abstract: 본 발명은 천연 공융용매로 추출한 쓴풀, 서양고추나물 및 하늘타리 혼합추출물을 함유하는 피부 미백용 화장료 조성물에 관한 것으로, 구체적으로는 쓴풀, 서양고추나물 및 하늘타리를 천연 공융용매를 이용하여 추출하고, 이를 다시 아임계 추출하여 제조되는 쓴풀, 서양고추나물 및 하늘타리 혼합추출물을 함유하여 우수한 피부 미백 효능을 나타내는 화장료 조성물에 관한 것이다. claims: 쓴풀, 서양고추나물 및 하늘타리가 각각 1 : 3 : 2의 중량비로 혼합되어 이루어지는 쓴풀, 서양고추나물 및 하늘타리 혼합물을 비테인(Betaine)과 사카로즈(Saccharose)로 이루어지는 천연 공융용매와 물을 용매로 하여 추출하고, 다시 추출용매를 가하여 아임계 조건인 120~200℃, 압력 0.1~15MPa에서 10~30분간 아임계 추출하여 제조되는 쓴풀, 서양고추나물 및 하늘타리 혼합추출물을 유효성분으로서 조성물 전체 중량에 대하여 0.1~10 중량% 함유하는 피부 미백용 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

56/1150 Row 56: application_number: 1020210043862, combined_string: invention_title: 천연 오일 및 천연 추출물을 포함하는 화장료 조성물 abstract: 본 발명은 식물 오일 및 천연 추출물을 함유하는 피부 외용제에 관한 것으로, 구체적으로 파인 오일을 아미노 알코올과 효소 반응을 통해 세라마이드와 유사한 피부 보습 및 피부장벽 강화 효과를 가지면서 유화 안정제로 작용할 수 있는 피부 외용제에 관한 것이다. 나아가, 할미꽃 식물세포 또는 부정근 배양 추출물 및 후박나무껍질 추출물과 혼합하여 항균 및 항염 용도로 활용할 수 있다. 나아가, 본 발명의 피부 외용제는 복수의 유효성분을 포함함으로써, 피부 열감 개선 및 쿨링 효과를 나타냄과 동시에 체내 독소 배출 효과를 기대할 수 있다. claims: a) 파인(Pinus sylvestris) 잎 및 가지에서 각각 추출한 오일을 1 : 1의 중량비로 혼합한 오일 및 3-아미노부탄-1,2-디올(3-aminobutane-1,2-diol)을 혼합하고 리파아제인 리포자임 TL IM(Lipozyme TL IM)를 반응시켜 파인발효 오일을 제조하는 단계; b) 할미꽃 식물세포 또는 부정근 배양 추출물 및 후박나무껍질 추출물을 포함하는 식물 복합 추출물을 제조하는 단계; 및c) 상기 a) 단계의 파인발효 오일 및 b) 단계의 식물 복합 추출물을 혼합하는 단계;를 포함하는, 항균 및 항염용 피부 외용제 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

57/1150 Row 57: application_number: 1020210042561, combined_string: invention_title: 매스틱 및 천연물 유래 추출물을 포함하는 헬리코박터균 억제용 제품 abstract: 본 발명은 매스틱 및 천연물 유래의 추출물을 포함하여 제조된 식품 및 구강 케어 제품에 관한 것으로서, 헬리코박터 파일로리(Helicobacter pylori)균의 억제 효과를 갖는 것을 특징으로 한다. claims: 매스틱(Mastic, Pistacia lentiscus LINNE) 에센셜 오일 1 내지 10 중량부;금은화(Lonicera japonica) 10 내지 15 중량부, 감초(Glycyrrhiza uralensis) 10 내지 15 중량부, 인삼(Panax ginseng) 3 내지 9 중량부, 계피(Cinnamomum japonicum SIEB.) 3 내지 7 중량부, 차조기(Perilla frutescens) 2 내지 5 중량부 및 유카(Yucca gloriosa) 1 내지 5 중량부로 이루어진 군에서 하나 이상 선택된 천연물의 혼합 추출물을 포함하는 수상;을 혼합 후 고압 유화장치(microfluidizer)로 분산시켜 고압 분산 에멀젼화 하여 제조한 중심물질; 및상기 중심물질을, 오일상으로서 MCT:매스틱 오일:올리브 오일: 솔잣나무 잎 오일을 47:22:4:8의 중량비로 혼합한 피복물질;로 피복하여 제조한 미세캡슐을 포함하고,소세지, 육류, 빵, 초콜릿류, 스넥류, 캔디류, 과자류, 라면, 피자, 면류, 껌류, 아이스크림류를 포함한 낙농제품, 스프, 음료수, 차, 드링크제, 알코올 음료 및 비타민 복합제로 구성된 군에서 하나 이상 선택된 제형을 가진, 헬리코박터 파일로리균(Helicobacter pyroli) 억제용 식품 조성물.매스틱(Mastic, Pistacia lentiscus LINNE) 에센셜 오일 1 내지 10 중량부;금은화(Lonicera japonica) 10 내지 15 중량부, 감초(Glycyrrhiza uralensis) 10 내지 15 중량부, 인삼(Panax ginseng) 3 내지 9 중량부, 계피(Cinnamomum japonicum SIEB.) 3 내지 7 중량부, 차조기(Perilla frutescens) 2 내지 5 중량부 및 유카(Yucca gloriosa) 1 내지 5 중량부로 이루어진 군에서 하나 이상 선택된 천연물의 혼합 추출물을 포함하는 수상;을 혼합 후 고압 유화장치(microfluidizer)로 분산시켜 고압 분산 에멀젼화 하여 제조한 중심물질; 및상기 중심물질을, 오일상으로서 MCT:매스틱 오일:올리브 오일: 솔잣나무 잎 오일을 47:22:4:8의 중량비로 혼합한 피복물질;로 피복하여 제조한 미세캡슐을 포함하고,구강 세척제 및 치과용 세척제, 치약, 가글 용액, 패취 및 스프레이로 구성된 군으로부터 하나 이상 선택된 제형을 가진, 헬리코박터 파일로리균(Helicobacter pyroli) 억제용 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

58/1150 Row 58: application_number: 1020210040231, combined_string: invention_title: 천연물 추출장치 abstract: 본 발명은 천연물 추출장치에 관한 것으로, 본 발명의 실시예에 의하면, 추출부를 진동 및 타격하고 추출액을 적하시키며 반복 추출하여 천연물의 유효성분 추출 효율을 향상시키는 효과가 있다. claims: 내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및상기 추출부의 상측에 연결되고, 상기 용매가 투입되며, 상기 원물에 상기 용매를 분사하는 용매분사부;를 포함하고,상기 용매분사부의 하측에 연결되고, 상기 용매분사부에 의해 분사된 상기 용매를 더 확산시키기 위한 회전판; 및상기 회전판을 회전시키는 회전모듈;을 더 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및상기 추출부에 연결되고, 상기 용매와 상기 원물이 잘 섞이도록 상기 추출부에 진동을 가함으로써 추출 효율을 향상시키는 진동부;를 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및일측이 상기 저장부에 연결되고, 타측이 상기 추출부에 연결되며, 상기 유효성분의 추출 효율을 높이도록 상기 추출액을 상기 추출부로 재공급하는 순환부;를 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부; 및상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부;를 포함하고,상기 추출부는,상부가 개구되고, 하부가 메쉬로 형성되며, 내측에 상기 원물을 수용하는 원물트레이; 및상부가 개구되어 상기 용매가 투입되고, 내측에 상기 원물트레이를 수용할 수 있는 공간이 형성되며, 상기 원물로부터 상기 유효성분을 추출하여 상기 추출액을 생성하고, 상기 추출액이 통과할 수 있도록 하부에 홀이 형성된 추출하우징;을 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부; 및상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부;를 포함하고,상기 저장부는,상기 추출부의 하측에 연결되고, 상기 추출부에서 추출된 상기 추출액을 저장하는 저장탱크;상기 저장탱크에 연결되어 저장된 상기 추출액을 배출하는 배출파이프; 및상기 배출파이프에 구비되어 상기 배출파이프를 선택적으로 개방 또는 폐쇄하는 배출밸브;를 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및상기 추출부의 상측에 연결되고, 상기 용매가 투입되며, 상기 원물에 상기 용매를 분사하는 용매분사부;를 포함하고,상기 용매분사부는,상기 추출부의 상측에 연결되고, 용매투입구가 형성되어 용매가 투입되는 용매탱크; 및상기 용매탱크 하부에 구비되어 상기 원물에 상기 용매를 분사하는 용매분사체;를 포함하는 것을 특징으로 하는 천연물 추출장치.내부에 원물을 수용하고, 용매가 투입되며, 상기 원물로부터 유효성분을 추출하여 추출액을 생성하는 추출부;상기 추출부의 하측에 연결되고, 상기 추출부에서 생성된 상기 추출액을 저장하며, 저장된 상기 추출액을 배출하는 저장부; 및상기 추출부와 상기 저장부 사이에 구비되고, 상기 추출부에서 추출된 상기 추출액을 저장하며, 상기 저장부로 낙하하는 상기 추출액의 유량을 제어하는 적하부;를 포함하고상기 적하부는,상측이 상기 추출부의 하측에 연결되고, 하측이 상기 저장부와 적하파이프로 연결되며, 상기 추출부에서 추출된 상기 추출액을 저장하는 이너탱크;상기 이너탱크 내부에 구비되고, 상기 이너탱크 내부에 저장되는 상기 추출액의 수위를 측정하는 수위센서;상기 적하파이프에 구비되고, 상기 저장부로 낙하하는 상기 추출액의 유량을 조절하는 유량조절밸브; 및상기 수위센서로부터 수위값을 전송받아 상기 추출액이 기설정된 수위에 도달하면 상기 유량조절밸브를 개방하도록 제어하는 수위제어부;를 포함하는 것을 특징으로 하는 천연물 추출장치., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

59/1150 Row 59: application_number: 1020210034971, combined_string: invention_title: 이온화 미네랄과 감잎 추출물 등 천연물로 조성된 천연 항균 탈취제 조성물 abstract: 본 발명은 항균 및 탈취 기능을 가진 조성물에 관한 것으로, 보다 상세하게는 인체에 무해하면서도 우수한 항균, 탈취 효과를 가지는 조성물에 관한 것이다. 즉 본 발명은 일라이트, 뮤스코바이트, 클로라이트의 점토 혼합광물에서 추출한 이온화 미네랄과 감잎 추출물, 소나무잎 추출물, 편백잎 추출물, 목련잎 추출물을 이용한 항균 및 탈취제 조성물로 이루어져 있으며, 상기 항균 탈취제는 일라이트, 뮤스코바이트, 클로라이트의 점토 혼합광물에서 추출한 이온화 미네랄 91 내지 97 중량부와 감잎 추출물 0.1 내지 5 중량부, 소나무잎 추출물 0.1 내지 5 중량부, 편백잎 추출물 0.1 내지 5 중량부, 목련잎 추출물 0.1 내지 5 중량부의 비율로 혼합되는 것을 특징으로 한다. claims: 일라이트, 뮤스코바이트, 클로라이트의 점토 혼합광물에서 추출한 이온화 미네랄, 구체적으로는 칼슘 이온 100-200mg/l, 칼륨이온 500-600mg/l, 구리이온 40-50mg/l, 은이온 1-3mg/l을 함유하는 이온화 미네랄 91 내지 97 중량부와 감잎 추출물 0.1 내지 5 중량부, 소나무잎 추출물 0.1 내지 5 중량부, 편백잎 추출물 0.1 내지 5 중량부, 목련잎 추출물 0.1 내지 5 중량부의 비율로 혼합되는 것을 특징으로 하는 항균 탈취제 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

60/1150 Row 60: application_number: 1020210010474, combined_string: invention_title: 천연소재 추출물 함유 약학적 조성물 및 그의 제조 방법 abstract: 본 발명은 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물을 포함하는 약학적 조성물 및 그의 제조 방법에 관한 것이다. claims: 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물로 이루어진 군에서 선택되는 적어도 하나의 추출물을 포함하는 피부 관련 질환의 예방 또는 치료용 약학적 조성물.청구항 1의 약학적 조성물을 이를 필요로 하는 개체에 투여하는 단계를 포함하는 피부 관련 질환의 예방 또는 치료 방법.황금, 맥문동, 고삼, 백선피 및 황백으로 이루어진 군에서 선택되는 적어도 하나의 천연소재를 추출하는 단계를 포함하는 피부 관련 질환의 예방 또는 치료용 약학적 조성물의 제조 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

61/1150 Row 61: application_number: 1020210010478, combined_string: invention_title: 천연소재 추출물 함유 동물용 약학적 조성물 및 그의 제조 방법 abstract: 본 발명은 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물을 포함하는 동물용 약학적 조성물 및 그의 제조 방법에 관한 것이다. claims: 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물로 이루어진 군에서 선택되는 적어도 하나의 추출물을 포함하는 동물의 피부 관련 질환의 예방 또는 치료용 약학적 조성물.청구항 1의 약학적 조성물을 이를 필요로 하는 개체에 투여하는 단계를 포함하는 동물의 피부 관련 질환의 예방 또는 치료 방법.황금, 맥문동, 고삼, 백선피 및 황백으로 이루어진 군에서 선택되는 적어도 하나의 천연소재를 추출하는 단계를 포함하는 동물의 피부 관련 질환의 예방 또는 치료용 약학적 조성물의 제조 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

62/1150 Row 62: application_number: 1020210010482, combined_string: invention_title: 천연소재 추출물 함유 식품 조성물 및 그의 제조 방법 abstract: 본 발명은 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물을 포함하는 식품 조성물 및 그의 제조 방법에 관한 것이다. claims: 황금 추출물, 맥문동 추출물, 고삼 추출물, 백선피 추출물 및 황백 추출물로 이루어진 군에서 선택되는 적어도 하나의 추출물을 포함하는 피부 관련 질환의 예방 또는 개선용 식품 조성물.청구항 1의 식품 조성물을 이를 필요로 하는 개체에게 섭취시키는 단계를 포함하는 피부 관련 질환의 예방 또는 개선 방법.황금, 맥문동, 고삼, 백선피 및 황백으로 이루어진 군에서 선택되는 적어도 하나의 천연소재를 추출하는 단계를 포함하는 피부 관련 질환의 예방 또는 개선용 식품 조성물의 제조 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

63/1150 Row 63: application_number: 1020210007582, combined_string: invention_title: 천연 추출물을 포함하는 두피 개선용 조성물 abstract: 본 발명은 당귀 추출물, 고삼 추출물, 감초 추출물, 하수오 추출물 및 인삼 추출물을 포함하는 두피 개선용 조성물에 관한 것으로, 상기 한방 약재 추출물에 때죽나무 잎 추출물 및 고로쇠나무 발효 수액을 포함하여 비듬 감소 및 두피 가려움증의 효능을 향상시키고, 나아가 우수한 탈모 방지 효능을 가지는 것을 특징으로 하는 조성물에 관한 것이다. claims: 전체 조성물의 중량을 기준으로, 당귀 추출물 3 중량부, 고삼 추출물 3 중량부, 감초 추출물 3 중량부, 하수오 추출물 3 중량부 및 인삼 추출물 3 중량부를 포함하는 한방 약재 추출물; 때죽나무 잎 발효 추출물 7 중량부; 고로쇠나무 발효 수액 6 중량부; 로즈마리오일 1.5 중량부; 및 멘톨 0.5 중량부를 포함하는 두피 개선용 조성물로서,상기 한방 약재 추출물은 당귀, 고삼, 감초, 하수오 및 인삼의 건조 분쇄물을 50% 에탄올을 용매로 하여 50℃에서 12시간 동안 침적 추출하고, 여과 후 30℃에서 감압 농축하고 동결 건조하여 수득한 것이며,상기 때죽나무 잎 발효 추출물은 때죽나무 잎을 70% 에탄올을 용매로 하여 상온에서 7일 동안 침적 추출하고, 여과 후 40℃에서 감압 농축하고 동결 건조하여 수득한 때죽나무 잎 추출물에 락토바실러스(lactobacillus) 속 균주를 접종하여 발효시킨 추출물이고,상기 고로쇠나무 발효 수액은 효모(Saccharomyces cerevisiae)균을 고로쇠나무 수액 100 중량부에 대해 2 내지 5 중량부가 되도록 넣어 40℃에서 48시간 발효하고, 발효된 원료에 30% 함량의 부틸렌글리콜을 넣고 상온에서 7일 추출한 다음 여과하여 수득한 것이며,상기 조성물은 비듬 생성 억제, 두피 가려움증 완화 및 탈모 방지 효과를 갖는 것을 특징으로 하는, 두피 개선용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

64/1150 Row 64: application_number: 1020210007583, combined_string: invention_title: 천연 추출물을 포함하는 모발 개선용 조성물 abstract: 본 발명은 당귀, 고삼, 감초, 하수오 및 인삼 추출물 등의 한방 약재 추출물을 포함하는 모발용 화장료 조성물에 관한 것으로, 상기 한방 약재 추출물에 싸리 발효 추출물을 첨가하여 모발 윤기 및 부드러움을 향상시키고, 나아가 고로쇠나무 발효 수액, 올리브 오일 및 로즈마리 오일을 첨가하여 두피 보호 효과를 가지는 것을 특징으로 하는 조성물에 관한 것이다. claims: 전체 조성물의 중량을 기준으로, 당귀 추출물 3 중량부, 고삼 추출물 3 중량부, 감초 추출물 3 중량부, 하수오 추출물 3 중량부 및 인삼 추출물 3 중량부를 포함하는 한방 약재 추출물; 싸리 발효 추출물 7 중량부; 고로쇠나무 발효 수액 5 중량부; 로즈마리오일 1 중량부; 및 올리브오일 1 중량부;를 포함하는 모발용 화장료 조성물로서,상기 한방 약재 추출물은 당귀, 고삼, 감초, 하수오 및 인삼의 건조 분쇄물을 50%(w/v) 에탄올을 용매로 하여 50℃에서 12시간 동안 침적 추출하고, 여과 후 30℃에서 감압 농축하고 동결 건조하여 수득한 것이며,상기 싸리 발효 추출물은, 분쇄된 싸리나무 잎을 110℃의 해양심층수 및 증류수 혼합 용매에서 8시간 동안 추출하여 수득한 싸리 추출물을 맥주 효모,　아위버섯 균주 및 락토바실러스(Lactobacillus) 속 균주로 이루어진 군에서 선택된 어느 하나의 균주로 발효시킨 것이고,상기 조성물은 모발 컨디셔닝, 모발 윤기 개선 및 두피 가려움증 개선 효과를 갖는 것을 특징으로 하는, 모발용 화장료 조성물., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

65/1150 Row 65: application_number: 1020210007584, combined_string: invention_title: 천연물 유래 추출물을 포함하는 피부 개선용 화장료 조성물 및 이의 제조방법 abstract: 본 발명은 천연물 유래 추출물 및 허브 파우더를 함유하는 화장료 조성물에 관한 것으로서, 구체적으로는 로즈마리, 라벤더, 페퍼민트 추출물 및 이들의 허브 파우더를 함유함으로써 피부 노폐물 제거, 피부장벽 개선, 피부 탄력 부여, 피부 보습, 각질제거 및 영양공급 효과를 갖는 것을 특징으로 한다. claims: 페퍼민트(Mentha piperita) 잎 추출물 100 중량부 대비, 로즈마리(Salvia rosmarinus) 잎 추출물 100 중량부, 라벤더(Lavandula) 꽃 추출물 100 중량부, 마조람(Origanum majorana) 잎 추출물 40 중량부, 모란(Paeonia suffruticosa) 뿌리 추출물 35 중량부, 들깨(Perilla frutescens) 잎 추출물 27 중량부, 연꽃(Nelumbo nucifera) 추출물 22 중량부, 목련나무(Magnolia) 껍질 추출물 15 중량부 및 목화(Gossypium indicum) 씨 추출물 8 중량부; 및 페퍼민트 파우더 30 중량부, 로즈마리 파우더 25 중량부, 라벤더 파우더 25 중량부 및 살구씨 파우더 35 중량부를 포함하여 제조된 화장료 조성물로서,상기 추출물은 페퍼민트 잎, 로즈마리 잎, 라벤더 꽃, 마조람, 모란 뿌리, 들깨 잎, 연꽃, 목련나무 껍질 및 목화 씨를 -60℃ 내지 -80℃ 조건에서 동결 건조하고, 각 재료의 2배 중량의 정제수를 혼합하여 수분을 흡수시키고, 70%(v/v) 에탄올을 용매로 하여 2시간 동안 환류 추출한 후, 250 메쉬 및 0.5μm 필터로 여과하고 40℃에서 감압 농축하여 수득한 것이며,상기 화장료 조성물은 피부 노폐물 제거, 피부장벽 개선, 피부 탄력 부여, 피부 보습, 각질제거 및 영양공급 효과를 갖는 것인, 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

66/1150 Row 66: application_number: 1020210005266, combined_string: invention_title: 천연 쌀눈 추출물을 포함하는 칠곡 삼계죽의 제조방법 abstract: 본 발명은 천연 쌀눈 추출물을 포함하는 칠곡 삼계죽의 제조방법에 관한 것으로, 본 발명에 따른 천연 쌀눈 추출물을 포함하는 칠곡 삼계죽의 경우, 쌀눈을 원물 그대로 첨가한 것이 아닌 증류수만을 이용한 천연 추출방법으로 추출하여 쌀눈에 첨가된 GABA 함량과 쌀눈의 향을 증가시킬 수 있으며, 삼계죽에 멥쌀, 찹쌀, 현미, 귀리, 기장 및 보리를 포함하는 곡물과 채소를 첨가하여 영양적 가치가 높은 삼계죽을 제조할 수 있는 장점이 있다. claims: 쌀눈 추출물, 기장, 멥쌀, 찹쌀, 귀리, 녹두, 현미, 닭가슴살, 양파, 당근, 마늘, 인삼, 천일염, 대파, 치킨스톡, 찹쌀가루 및 감자전분을 포함하는 칠곡 삼계죽 재료를 준비하는 단계;정제수에 쌀눈추출물, 기장, 멥쌀, 찹쌀, 귀리, 녹두, 현미, 닭가슴살, 양파, 당근, 마늘, 인삼 및 천일염을 첨가하여 5 내지 15분간 가열하여 1차 육수를 제조하는 단계;상기 1차 육수에 대파 및 치킨스톡을 넣고 3 내지 7분간 가열하여 2차 육수를 제조하는 단계; 및상기 2차 육수에 상기 찹쌀가루 및 감자전분을 넣고 1 내지 3분간 가열하여 칠곡 삼계죽을 제조하는 단계;를 포함하는 칠곡 삼계죽 제조 방법.제1항 내지 제6항의 방법으로 제조된 칠곡 삼계죽., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

67/1150 Row 67: application_number: 1020210004132, combined_string: invention_title: 천연 식물 추출물을 포함하는 화장품용 PLGA 나노입자 및 이의 제조방법 abstract: 본 발명은 PLGA 입자 내에 마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 유효 성분을 포함하는 화장품용 PLGA 나노입자 및 이의 제조방법에 관한 것으로, 유효 성분을 단계적이고 집약적으로 피부로 흡수시켜 흡수율과 지속력을 높일 수 있는 효과를 제공한다. claims: PLGA(poly(lactic-co-glycolic acid)) 고분자가 유기 용매에 용해된 유기용액과 포스파티딜콜린(phosphatidyl choline)을 혼합한 용액을 클로로포름(chloroform)으로 용해시키고, 여기에 안정화제를 혼합하여 1차 혼합물을 제조하는 제1 단계;상기 1차 혼합물에 마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 천연 식물 추출물을 포함하는 수용액을 첨가한 후 1℃ 내지 5℃에서 초음파 처리 및 교반하여 2차 혼합물을 제조하는 제2 단계;상기 2차 혼합물에 키토산(chitosan)을 혼합 및 교반하여 키토산 코팅된 1차 입자를 제조하는 제3 단계;마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 천연 식물 추출물과 상기 1차 입자를 포함하는 수용액에 PLGA(poly(lactic-co-glycolic acid)) 고분자가 유기 용매에 용해된 유기용액을 혼합하여 3차 혼합물을 제조하는 제4 단계;상기 3차 혼합물에 계면활성제를 첨가한 후 10℃ 이하에서 초음파 처리 및 교반하여 4차 혼합물을 제조하는 제5 단계; 및상기 4차 혼합물에 알긴산 나트륨(sodium alginate)을 혼합 및 교반하여 알긴산 코팅된 2차 입자를 제조하는 제6 단계;를 포함하고,상기 1차 혼합물에 포함되는 PLGA(poly(lactic-co-glycolic acid)) 고분자는 PLA(poly(lactic acid)):PGA(poly(glycolic acid)) 의 몰비가 3:2 내지 4:1 이고,상기 3차 혼합물에 포함되는 PLGA(poly(lactic-co-glycolic acid)) 고분자는 PLA(poly(lactic acid)):PGA(poly(glycolic acid)) 의 몰비가 1:4 내지 2:3 인 것을 특징으로 하는 화장품용 PLGA 나노입자 제조방법. 마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 유효 성분을 포함하고, PLA(poly(lactic acid)):PGA(poly(glycolic acid)) 의 몰비가 3:2 내지 4:1인 PLGA(poly(lactic-co-glycolic acid)) 고분자로 형성되는 PLGA 코어; 및상기 PLGA 코어 표면에 형성되는 키토산 코팅;상기 키토산 코팅 표면에 마트린(matrine), 님오일(neem oil), 타임 오일(Thyme oil) 및 제라니올 오일(geraniol oil)로 구성되는 군에서 선택되는 적어도 1종의 유효 성분을 포함하고, PLA(poly(lactic acid)):PGA(poly(glycolic acid)) 의 몰비가 1:4 내지 2:3 인 PLGA(poly(lactic-co-glycolic acid)) 고분자로 형성되는 PLGA 쉘; 및상기 PLGA 쉘 표면에 형성되는 알긴산 코팅;을 포함하는 화장품용 PLGA 나노입자., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

68/1150 Row 68: application_number: 1020210001307, combined_string: invention_title: 천연 추출물 및 천연 가루를 포함하는 화장료 조성물 abstract: 본 발명은 천연 추출물 및 천연 가루를 포함하는 화장료 조성물에 관한 것으로, 구체적으로 접시꽃 뿌리 추출물, 인삼 추출물, 라벤더꽃 가루 및 페퍼민트잎 가루를 포함하는 피부 내 유익균 증진, 붓기 완화 등의 피부 개선용 조성물에 관한 것이다. claims: 접시꽃 뿌리 추출물, 인삼 추출물, 로즈마리잎 가루, 라벤더꽃 가루 및 페퍼민트잎 가루를 포함하는,피부 유익균인 류코노스톡 메센테로이데스(Leuconostoc mesenteorides)의 증진 또는 붓기 완화용 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

69/1150 Row 69: application_number: 1020200179652, combined_string: invention_title: 천연 복합 추출물을 함유하는 치주질환 개선용 구강 조성물 abstract: 본 발명은 치은염 또는 치주염 개선용 구강 조성물에 관한 것으로, 황련 추출물 및 고삼 추출물을 유효성분으로 포함하는 구강 조성물을 제공한다. claims: 황련 추출물, 감초 추출물, 녹차 추출물 및 고삼 추출물을 3:3:2:2의 중량비로 포함하고, 진지발리스균(P. Gingivitis)에 대한 항균 용도를 포함하고, 항염증, 치석 방지 및 구취 억제 용도를 포함하고,상기 추출물은 60 내지 80%(v/v) 농도의 에탄올 추출물인, 치주질환 개선용 구강 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

70/1150 Row 70: application_number: 1020200178119, combined_string: invention_title: 위 건강 개선 및 헬리코박터균 억제를 위한 매스틱 및 천연물 유래 추출물을 포함하는 조성물 및 그 용도 abstract: 본 발명은 헬리코박터 파일로리(Helicobacter pyroli)균의 억제 효과를 갖는 매스틱 및 천연물 유래의 추출물을 포함하여 제조된 헬리코박터 파일로리 억제용 조성물과 상기 조성물의 용도 및 그 제조 방법에 관한 것이다. claims: 매스틱(Mastic, Pistacia lentiscus LINNE) 에센셜 오일 1 내지 10 중량부;금은화(Lonicera japonica) 10 내지 15 중량부, 감초(Glycyrrhiza uralensis) 10 내지 15 중량부, 인삼(Panax ginseng) 3 내지 9 중량부, 계피(Cinnamomum japonicum SIEB.) 3 내지 7 중량부, 차조기(Perilla frutescens) 2 내지 5 중량부 및 유카(Yucca gloriosa) 1 내지 5 중량부로 이루어진 군에서 하나 이상 선택된 천연물의 혼합 추출물을 포함하는 수상;을 혼합 후 고압 유화장치(microfluidizer)로 분산시켜 고압 분산 에멀젼화 하여 제조한 중심물질; 및상기 중심물질을, 오일상으로서 MCT:매스틱 오일:올리브 오일: 솔잣나무 잎 오일을 47:22:4:8의 중량비로 혼합한 피복물질;로 피복하여 제조한 미세캡슐을 포함하는, 헬리코박터 파일로리균(Helicobacter pyroli) 억제용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

71/1150 Row 71: application_number: 1020200170347, combined_string: invention_title: 천연 추출물 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 조성물 abstract: 본 발명은 천연물 기반인 녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 화장료 조성물에 관한 것이다. 본 발명의 조성물은 다양한 원인에 기한 피부의 비정상적 상태(아토피, 염증, 홍반, 산화, 피부 내 세포 독성물질, 수분의 소실, 기미, 가려움, 거칠어짐, 주름 등)를 효과적으로 진정시킬 수 있다. claims: 녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 화장료 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 염증 및 주름 개선인 것을 특징으로 하는 피부 진정용 화장료 조성물.제 1 항의 화장료 조성물을 포함하는 마스크팩.녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 식품 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 염증 및 주름 개선인 것을 특징으로 하는 피부 진정용 식품 조성물.녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 약제학적 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 염증 및 주름 개선인 것을 특징으로 하는 피부 진정용 약제학적 조성물., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

72/1150 Row 72: application_number: 1020200166551, combined_string: invention_title: 천연 식물 혼합발효추출물을 유효성분으로 함유하는 피부 개선용 화장료 조성물 abstract: 본 발명은 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물을 함유하는 화장료 조성물에 관한 것으로, 본 발명에 따르면 유산균으로 발효된 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물을 유효성분으로 함유하는 화장료 조성물이 제공된다. 상기 유산균으로 발효된 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물을 유효성분으로 함유하는 화장료 조성물은 우수한 항산화, 피부주름 개선, 피부 탄력 개선, 피부보습 개선, 염증 완화 효과를 나타낸다. claims: 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물을 유효성분으로 조성물 전체 중량에 대하여 0.01~90 중량% 함유하는 화장료 조성물.(A) 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화를 각각 1~2: 1~2: 1~2: 1~2: 1~2: 1~2의 중량비로 혼합하여 혼합물을 제조하는 단계; (B) 상기 혼합물에 물, 에탄올, 메탄올, 부탄올, 프로판올, 부틸렌글리콜, 글리세린, 클로로포름, 에틸아세테이트, 디클로로메탄, 헥산, 아세톤, 아세토나이트릴, 페트로레움에테르 및 디에틸에테르로 이루어진 군으로부터 선택되는 적어도 하나의 용매를 가하고 추출하여 혼합추출물을 제조하는 단계; (C) 제조된 상기 혼합추출물에 바실루스 서브틸리스, 락토바실루스 브레비스, 페디오코커스 매시디락티스, 류코노스톡 메센테로이데스, 스트렙토코커스 써모필러스, 락토바실러스 카제이, 락토코코스 락티스, 락토바실러스 델부르키 및 엔테로코쿠스 페슘으로 이루어지는 군으로부터 선택되는 적어도 하나의 유산균을 접종하여 발효시키는 단계; 및 (D) 멸균 후 여과하는 단계를 포함하는 하고초, 고삼, 가자, 칠채국, 할미꽃 및 금은화 혼합발효추출물의 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

73/1150 Row 73: application_number: 1020200163928, combined_string: invention_title: 비타민나무 추출물의 비타민 안정성 증진을 위한 천연 소재 및 이의 제조 방법 abstract: 본 발명은 비타민 C와 복합체를 이룰 수 있는 펩티드에 관한 것으로서, 비타민 C가 외부의 산화 환경에 노출되는 것을 차단하여 비타민 C의 안정성을 증가시킬 수 있다. claims: 하기의 일반식 1의 아미노산 서열을 포함하는 펩티드:[일반식 1]X1-A-A-X2-X3상기 식에서 X1, X2, 및 X3는 각각 독립적으로 세린(Serine; S), 트레오닌(Threonine; T), 아스파라긴(Asparagine; N), 및 글루타민(Glutamine; Q)으로 이루어진 군으로부터 선택되는 어느 하나인 아미노산이고,상기 펩티드는 서열번호 1, 서열번호 2, 서열번호 3, 서열번호 4, 및 서열번호 5로 이루어진 군으로부터 선택된 아미노산 서열로 구성되는 것인 펩티드.제1항의 펩티드 및 비타민 C를 포함하는 복합체.제6항의 복합체를 포함하는 건강기능식품.제6항의 복합체를 포함하는 식품 첨가제.제6항의 복합체를 포함하는 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

74/1150 Row 74: application_number: 1020200161492, combined_string: invention_title: 천연 추출물을 유효성분으로 하는 화장료 조성물 abstract: 본 발명은 천연 추출물을 유효성분으로 하는 화장료 조성물에 관한 것으로, 본 발명에 따른 화장료 조성물은 인체에 대한 부작용이 적을 뿐만 아니라 우수한 항노화 및 미백 효과를 가져 화장품, 피부 의약품 등에 유용하게 사용될 수 있다. claims: 천연 추출물을 유효성분으로 함유하는 화장료 조성물에 있어서,상기 천연 추출물은 꽃송이버섯 10~20 중량%, 함초 5~15 중량%, 알로에 5~15 중량%, 버드나무껍질 5~15 중량%, 노근 5~15 중량%, 콩뿌리 5~15 중량%, 무궁화잎 5~15 중량%, 매화 1~10 중량%, 수선화 1~10 중량%, 허브 1~10 중량%, 황칠나무잎 1~10 중량% 및 사과나무잎 1~10 중량% 비율의 혼합물을, 이산화탄소 분위기, 300 기압 및 60℃ 온도에서 초임계 추출하여 얻어진 복합 추출물이고,상기 화장료 조성물은 용액, 현탁액, 유탁액, 페이스트, 겔, 크림, 로션, 파우더, 비누, 클렌징, 오일, 분말파운데이션, 유탁액 파운데이션, 왁스 파운데이션, 팩, 마사지크림, 스프레이 및 미용팩으로 구성된 군으로부터 선택되는 제형이며,상기 크림은 초임계 추출물 0.1 내지 30중량%, 마유 1~5 중량%, 동백 오일 1~5 중량%, 코코넛 오일 1~5 중량%, 알라토닌 1~5 중량%, 스쿠알렌 1~5 중량%, 세라마이드 1~5 중량%, 히알루론산 1~10 중량%, 전분 1~10 중량%, 트라칸트 1~10 중량%, 실리콘 1~10 중량%, 벤토나이트 1~10 중량%, 폴리솔베이트 1~10 중량%, 폴리에틸렌글라이콜 스테아레이트 1~10 중량%, 글리세릴 스테아레이트 1~10 중량%, 폴리프로필렌글라이콜 1~10 중량%, 탈크 1~5 중량%, 산화아연 1~5 중량%, 글리세롤 1~5 중량% 및 정제수 0.5~3 중량%를 포함하는 것을 특징으로 하는 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

75/1150 Row 75: application_number: 1020200159853, combined_string: invention_title: 친환경적 천연가죽 가공방법 및 이를 이용한 천연가죽 abstract: 이 발명은 탄닝 전처리 공정에 죽초액을 사용함으로써 단백질 분해를 유도하여 유연성을 부여하고 소취효과를 나타내어 천연가죽 특유의 냄새를 제거할 수 있으며, 천연가죽의 품질을 저하시키는 균을 사멸시켜 항균 효과를 나타낼 수 있을 뿐만 아니라 폐수처리시 환경 오염 위험성을 감소시킬 수 있는, 친환경적 천연가죽 가공방법 및 이를 이용한 천연가죽에 관한 것이다.. claims: 천연가죽을 질량농도가 3~5%인 수산화칼슘 수용액에 함침하여 탈모하는 탈모단계; 상기 탈모단계를 거쳐 탈모된 천연가죽을 밴드나이프를 이용하여 지방을 제거하는 지방제거단계; 상기 지방제거단계를 거친 천연가죽을 전처리 용액에 함침하는 탄닝전처리단계; 상기 탄닝전처리단계를 거친 천연가죽에 탄닝제를 혼합하여 탄닝하는 탄닝단계; 상기 탄닝단계를 거친 천연가죽을 쉐이빙 장치를 이용하여 두께를 조정하는 쉐이빙단계;를 포함하며,상기 탄닝전처리단계는, 전처리 용액을 제조하는 단계; 천연가죽 100 중량부에 대하여, 전처리 용액 200~250 중량부를 투입하여 함침하는 단계;를 포함하며,상기 전처리 용액을 제조하는 단계는, 숙성 죽초액을 제조하는 단계; 상기 숙성 죽초액을 15~20 중량% 및 정제수 80~95 중량%를 혼합하는 단계;를 포함하여 제조하는 것을 특징으로 하는 친환경적 천연가죽 가공방법.제 3항 내지 제 6항 중 어느 한 항의 방법으로 제조되는 것을 특징으로 하는 천연가죽., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

76/1150 Row 76: application_number: 1020200159140, combined_string: invention_title: 천연소재추출물을 포함하는 피부 개선용 식품 조성물 abstract: 본 발명은 천연소재추출물을 포함하는 피부 개선용 식품 조성물에 관한 것으로, 기존의 피부 외용제가 가지는 한계를 극복하고, 경구 섭취에 따라 표피층 전체와 진피층의 피부 조직에 피부 개선 효과가 전달되는 먹는 화장품을 제공한다. claims: 도라지추출물, 배추출물, 석류추출물 및 자소엽추출물을 모두 포함하며,상기 도라지추출물은 51~55 ℃에서 25~29 시간 추출한 것이고,상기 배추출물은 94~98 ℃에서 18~22 시간 추출한 것이고,상기 석류추출물은 94~98 ℃에서 12~16 시간 추출한 것이고,상기 자소엽추출물은 51~55 ℃에서 25~29 시간 추출한 것이며,도라지추출물, 배추출물, 석류추출물 및 자소엽추출물은 1:1:1:1의 중량비, 1:2:1:1의 중량비 또는 1:2:1:2의 중량비로 혼합되는 것을 특징으로 하는 폴리페놀이 강화된 피부 주름 개선용 식품 조성물.도라지추출물, 배추출물, 석류추출물 및 자소엽추출물을 모두 포함하며,상기 도라지추출물은 51~55 ℃에서 25~29 시간 추출한 것이고,상기 배추출물은 94~98 ℃에서 18~22 시간 추출한 것이고,상기 석류추출물은 94~98 ℃에서 12~16 시간 추출한 것이고,상기 자소엽추출물은 51~55 ℃에서 25~29 시간 추출한 것이며,도라지추출물, 배추출물, 석류추출물 및 자소엽추출물은 1:1:1:1의 중량비, 2:1:1:2의 중량비 또는 1:1:2:2의 중량비로 혼합되는 것을 특징으로 하는 폴리페놀이 강화된 피부 미백용 식품 조성물.도라지추출물, 배추출물, 석류추출물 및 자소엽추출물을 모두 포함하며,상기 도라지추출물은 51~55 ℃에서 25~29 시간 추출한 것이고,상기 배추출물은 94~98 ℃에서 18~22 시간 추출한 것이고,상기 석류추출물은 94~98 ℃에서 12~16 시간 추출한 것이고,상기 자소엽추출물은 51~55 ℃에서 25~29 시간 추출한 것이며,도라지추출물, 배추출물, 석류추출물 및 자소엽추출물은 1:1:1:1의 중량비, 1:1:2:1의 중량비, 2:2:1:1의 중량비 또는 1:2:2:1의 중량비로 혼합되는 것을 특징으로 하는 폴리페놀이 강화된 피부 보습용 식품 조성물., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

77/1150 Row 77: application_number: 1020200154338, combined_string: invention_title: 혈액순환 개선 및 면역력 증진 효능을 가지는 천연 추출물을 포함하는 식품 조성물 abstract: 본 발명은 혈액순환 개선 및 면역력 증진 효능을 가지는 천연 추출물을 함유하는 조성물에 관한 것으로, 본 발명의 해조칼슘, 갈랑갈 추출분말, 홍삼 농축분말, 황기 추출분말, 백출 추출분말, 삼채 추출분말, 유산균 및 모링가 추출분말을 유효성분으로 포함하는 조성물은 혈소판 응집을 억제하여 혈전생성을 저해하는 효능이 있으며, 혈관의 수축을 억제하여 혈관 이완을 유도하는 효능이 있다. 또한, 콜레스테롤의 증가를 억제하여 혈액과 간의 지질을 감소시키는 효능이 인정된다. 따라서, 이러한 효능을 통해, 혈액 순환 개선에 효과적이며, 혈관 건강을 증진시킬 뿐만 아니라, 비만, 당뇨 및 고지혈증 등의 치료 또는 예방에 효과적으로 사용될 수 있다. 또한, 본 발명의 조성물은 면역력 증진에 매우 효과적이며, 피로회복, 소화기능 개선효과가 있을 뿐만 아니라, 항비만 및 항염증 효능을 가진다. claims: 해조칼슘 100 중량부에 대하여 갈랑갈 추출분말 12 내지 18 중량부, 홍삼 농축분말 20 내지 25 중량부, 황기 추출분말 12 내지 18 중량부, 백출 추출분말 5 내지 8 중량부, 삼채 추출분말 2 내지 3 중량부, 유산균 2 내지 3 중량부 및 모링가 추출분말 2 내지 3 중량부의 양으로 혼합되는 것을 특징으로 하는 식품 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

78/1150 Row 78: application_number: 1020200119183, combined_string: invention_title: 천연소재 추출물을 포함하는 피부 개선용 조성물 abstract: 본 발명은 몰식자, 소목, 대황, 오수유, 오필초, 향춘자 또는 가와 추출물을 유효성분으로 포함하는 화장료 조성물, 식품 조성물 또는 의약외품 조성물에 관한 것이다. 구체적으로, 상기 추출물을 유효성분으로 포함하는 항산화용; 피부 보습용; 피부 미백용; 피부 트러블 개선용; 주름 개선용; 피부 탄력 증진용; 또는 피부 재생용 조성물에 관한 것이다. 본 발명의 조성물은 항당화, 멜라닌 감소, 항염증, 콜라겐 합성 촉진, 엘라스타제 활성 저해, 세포 증식 효과가 우수하여, 항산화, 피부 보습, 피부 미백, 피부 트러블 개선, 주름 개선, 피부 탄력 증진, 피부 재생 용도로 유용하게 사용될 수 있다. 따라서, 본 발명의 조성물은 피부에 안전하면서도 피부 상태 개선 효과가 우수한 화장료 조성물, 식품 조성물, 의약외품 조성물로 이용될 수 있다. claims: 몰식자, 소목, 대황, 오수유, 오필초, 향춘자 또는 가와 추출물을 유효성분으로 포함하는 항당화용 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

79/1150 Row 79: application_number: 1020200118754, combined_string: invention_title: 견운모 추출물의 제조 방법, 상기 방법에 의해 제조되는 견운모 용매 추출물 및 상기 견운모 용매 추출물을 이용한 천연 미네랄 이온수의 제조 방법 abstract: 본 발명은 견운모 추출물의 제조 방법, 상기 방법에 의해 제조되는 견운모 용매 추출물 및 상기 견운모 용매 추출물을 이용한 천연 미네랄 이온수의 제조 방법에 관한 것으로서, 더욱 상세하게는 국내에서 다량 생산되는 고급 견운모로부터 유효성분을 추출하여 이를 이용해 탈취제, 항균제 또는 화장품 원료 등으로 사용하는 기술을 제공한다. 본 발명에 따르면, 견운모를 활용하여 천연 미네랄 이온수를 제조함에 있어서, 견운모 표면에 존재하는 이물질을 완전 제거하고, 용매 추출을 이용해 고순도의 천연 미네랄 이온수를 제조함으로써 식품첨가물 뿐만 아니라, 탈취제, 항균제, 화장품 원료 등의 다양한 용도로 활용할 수 있는 기술을 제공할 수 있다. 따라서 자연 상태로 존재하는 많은 견운모를 단지 분말화하여 타 성분의 보조성분으로만 활용하는 것이 아니라 식품첨가물, 탈취제, 항균제, 화장물 원료 등의 주성분으로 재활용함으로써 부가가치 높은 제품을 제조할 수 있는 방안이 될 수 있다. claims: (1) 견운모를 산성 용액에 침지하여 교반한 후 세척하는 제1단계;(2) 상기 제1단계에서 얻어진 견운모를 전기로에 투입하여 800~1200℃의 온도로 12 내지 36 시간 동안 직접 소성하고 냉각시키는 제2단계;(3) 상기 제2단계에서 얻어진 다공질화된 견운모를 100~300 메쉬 크기로 분말화하는 제3단계;(4) 상기 제3단계에서 얻어진 견운모 분말을 내열성 용기에 넣은 후 밀봉하고, 이를 다시 350~ 500 kHz의 고주파로에 넣어 1400~1800℃의 온도로 0.5~2 시간 동안 간접 소성하고 냉각시키는 제4단계;(5) 상기 제4단계에서 얻어진 분말을 400~700 메쉬 크기로 분말화하는 제5단계;(6) 상기 제5단계에서 얻어진 분말을 용매 처리하여 추출물을 얻고 석출물을 여과시킨 후 액상 성분만을 분리하는 제6단계; 및(7) 상기 제6단계에서 얻어진 액상 성분을 농축기에 넣고 농축하는 제7단계;를 포함하여 구성되는 것을 특징으로 하며, 상기 제6단계에서 상기 용매 처리하여 추출물을 얻는 것은 상기 제5단계에서 얻어진 견운모 분말 중량의 10 내지 20배에 해당하는 부피의 에탄올에 24 시간 동안 가압 침지하여 이온 상태의 미네랄 성분을 추출하고 이온화되지 않은 금속 물질 부유물을 여과포를 이용하여 여과시켜 액상 성분만을 분리하는 것을 특징으로 하며, 상기 제7단계에서 액상 성분을 농축기에 넣고 농축함으로써 이온수의 순도가 97~99.9 중량%에 해당하는 이온수를 얻는 것을 특징으로 하는 견운모 추출물의 제조 방법.청구항 6에 따른 방법으로 제조되며, 탈취제 또는 화장품 원료로 이용되는 것을 특징으로 하는 견운모 추출물을 이용한 천연 미네랄 이온수., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

80/1150 Row 80: application_number: 1020200116667, combined_string: invention_title: 유산균주, 유산균 발효물 및 천연 추출물을 함유하는 항노화 화장료 조성물 및 그 제조방법 abstract: 본 발명은 유산균주, 유산균 발효물 및 천연 추출물을 함유하여 피부 광택이 뛰어난 피부 항노화 화장료 조성물을 제공한다. 항노화 화장료 조성물은 락토바실러스 카제이(Lactobacillus casei, 기탁번호:KCTC3110)와 락토바실러스 람노서스(Lactobacillus rhamnosers, 기탁번호:KCTC3237)를 사용하는 유산균주, 락토바실러스 발효물(Lactobacillus sakei subsp. Sakei), 비피다발효여과물(Bifidobacterium bifidum) 및 락토코쿠스 발효물(Lactococcus lactis subsp. lactis)을 사용하는 유산균 발효물 및 천연추출물을 유효성분으로 함유하여 피부 광택 기능을 부여한다. claims: 락토바실러스 카제이(Lactobacillus casei, 기탁번호:KCTC3110)와 락토바실러스 람노서스(Lactobacillus rhamnosers, 기탁번호:KCTC3237)를 사용하는 유산균주, 락토바실러스 발효물(Lactobacillus sakei subsp. Sakei), 비피다발효여과물(Bifidobacterium bifidum) 및 락토코쿠스 발효물(Lactococcus lactis subsp. lactis)을 사용하는 유산균 발효물 및 천연추출물을 유효성분으로 함유하여 피부 광택 기능을 부여하는 항노화 화장료 조성물.락토바실러스 카제이(Lactobacillus casei, 기탁번호:KCTC3110) 균주와 락토바실러스 람노서스(Lactobacillus rhamnosers, 기탁번호:KCTC3237) 균주를 배양한 배양액을 가열 멸균 처리하여 유산균주 사균체액을 제조하는 제1 단계;상기 유산균주 사균체액과 유산균 발효물을 1:3의 배합비로 혼합하여 혼합액을 제조하는 제2 단계; 및상기 혼합액에 흰목이버섯에서 추출한 베타-글루칸, 사케에서 추출하여 동결건조시킨 쌀발효여과물 및 요엽후박나무껍질추출물을 포함하는 천연 추출물을 2:1의 배합비로 혼합하는 제3 단계를 포함하는 유산균주, 유산균 발효물 및 천연 추출물을 함유하는 항노화 화장료 조성물 제조 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

81/1150 Row 81: application_number: 1020200114285, combined_string: invention_title: 돌콩 추출물을 포함하는 천연 화장료 조성물 abstract: 본 발명은 돌콩 추출물을 포함하는 천연 화장료 조성물로 특히, 돌콩 추출물을 포함하여, 피부 흡수율 및 제형 안정성이 우수한 천연 화장료 조성물에 관한 것이다.구체적으로, 본 발명은 디우탄검을 포함하는 천연 점증제; 탄소수 5 내지 6의 탄소사슬을 포함하는 폴리올; 및 돌콩 추출물;을 포함하는 천연 화장료 조성물로서, 천연 유래 성분들로 구성되어 피부에 저자극이면서도 피부 흡수율 및 제형 안정성이 우수할 수 있다. claims: 디우탄검을 포함하는 천연 점증제;탄소수 5 내지 6의 탄소사슬을 포함하는 폴리올; 및돌콩 추출물;을 포함하되,조성물 총 중량 기준으로 상기 천연 점증제 0.01 ~ 5 중량%, 상기 폴리올 2 ~ 10 중량%, 상기 돌콩 추출물 0.001 ~ 10 중량% 및 잔량의 물을 포함하는 것을 특징으로 하는, 돌콩 추출물을 포함하는 천연 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

82/1150 Row 82: application_number: 1020200114757, combined_string: invention_title: 천연물 유래 추출물을 포함하는 탈모 방지용 외용제 조성물 및 그 제조방법 abstract: 본 발명은 천연물 유래 추출물을 포함하는 탈모방지용 외용제 조성물과 이의 제조방법에 관한 것이다.구체적으로, 본 발명의 조성물은 또한, 본 발명은 천연물 유래 추출물을 포함함으로써, 피부에 적용시 우수한 보습효과를 보여 두피 생장을 촉진하기 위한 최적의 환경을 조성할 수 있으며, 두피의 열을 내리고, 모유두세포의 분화를 촉진하며, 모발의 굵기가 굵어지는 복합적인 효과를 동시에 나타내는 것을 특징으로 한다. claims: 발효 균주를 접종하여 발효한 천연물 유래 혼합 추출물을 포함하는 탈모 방지 및 육모 촉진용 조성물에 있어서,상기 천연물 유래 혼합 추출물은 도둑놈의지팡이 뿌리 추출물 28 중량부, 고추 열매 추출물 17 중량부, 구기자 추출물 19 중량부, 녹차 추출물 15 중량부, 참당귀 뿌리 추출물 20 중량부, 구릿대 뿌리 추출물 25 중량부, 뽕나무 열매 추출물 22 중량부, 뽕나무 뿌리 추출물 10 중량부, 대왕송잎 추출물 15 중량부, 지치 뿌리 추출물 12 중량부, 하수오 뿌리 추출물 10 중량부, 라벤더 추출물 5 중량부, 베르가못 잎 추출물 5 중량부, 페퍼민트 잎 추출물 7 중량부, 프리지아 추출물 3 중량부, 마트리카리아 꽃 추출물 3 중량부 및 로즈마리 잎 추출물 3 중량부를 포함하고,상기 발효는 발효 균주로서 락토바실러스 애시도필러스(Lactobacillus acidophilus), 락토바실러스 헬베티커스(Lactobacillus helveticus), 락토바실러스 람노서스(Lactobacillus rhamnosus), 비피도박테리움 롱검(Bifidobacterium longum), 비피도박테리움 락티스(Bifidobacterium lactis), 비피도박테리움 애니말리스(Bifidobacterium animalis), 비피도박테리움 비피덤(Bifidobacterium bifidum), 락토바실러스 카제이(Lactobacillus casei) 및 엔테로코커스 패시움(Enterococcus faecium)을 이용한 것인, 탈모 방지 및 육모 촉진용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

83/1150 Row 83: application_number: 1020200112986, combined_string: invention_title: 천연물 유래 추출물을 포함하는 혈당 강하용 조성물 abstract: 본 발명은 황기, 도라지, 칡, 진피, 구기자, 둥굴레, 맥문동 및 마를 포함하는 혈당 강하용 조성물과 이를 포함하는 기능성 식품 조성물에 관한 것이다.인체에 무해한 천연 원료만을 포함하여 제조되는 것으로서, 혈당 상승과 관련이 있는 α-아밀라아제(α-amylase) 및 α-글루코시다아제(α-glucosidase)의 저해활성을 가지고, 꾸준히 복용하는 경우 식후 혈당 상승을 억제하는 효과가 있음을 확인하였다. claims: 황기 50 중량부, 도라지 50 중량부, 칡 50 중량부, 진피 50 중량부, 구기자 100 중량부, 둥굴레 50 중량부, 맥문동 50 중량부 및 마 100 중량부의 추출물을 포함하고,상기 황기 및 도라지는 각 50 중량부에 정제수 50 중량부씩 첨가한 후 100℃에서 6시간동안 열수 추출하였고, 상기 칡 및 진피는 각 50 중량부에 정제수 50 중량부를 첨가한 후 98℃에서 4시간동안 열수 추출하였으며, 상기 구기자 100 중량부 및 50 중량부에 같은 중량부의 정제수를 첨가한 후 95℃에서 6시간동안 열수 추출하였고, 상기 맥문동 50 중량부 및 마 100 중량부에 같은 중량부의 정제수를 첨가한 후 92℃에서 6시간동안 추출하여 제조한 것인, 혈당 강하용 조성물.황기 및 도라지 각 50 중량부에 정제수 50 중량부씩 첨가한 후 100℃에서 6시간동안 열수 추출하는 단계;칡 및 진피 각 50 중량부에 정제수 50 중량부를 첨가한 후 98℃에서 4시간동안 열수 추출하는 단계;구기자 100 중량부 및 50 중량부에 같은 중량부의 정제수를 첨가한 후 95℃에서 6시간동안 열수 추출하는 단계; 및맥문동 50 중량부 및 마 100 중량부에 같은 중량부의 정제수를 첨가한 후 92℃에서 6시간동안 추출하는 단계;를 포함하는, 혈당 강하용 조성물의 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

84/1150 Row 84: application_number: 1020200110928, combined_string: invention_title: 아임계 천연추출물을 함유하는 세정제 조성물 abstract: 본 발명은 세정을 목적으로 하는 생활용품의 주성분으로 사용되어 수질오염의 원인이 되는 계면활성제의 사용량을 줄이면서도 그와 동일한 세정력을 나타내도록 개발된 세정제 조성물에 관한 것으로, 상세하게는 그 효능을 높이고 적은 에너지로 단시간에 높은 수율로 추출하여 친환경적인 생산이 가능한 아임계추출법을 적용한 것을 특징으로 한다.또한 상기와 같은 본 발명의 아임계추출법으로 추출한 무환자, 비누풀, 도라지, 도토리, 쇠뜨기 추출물을 포함하며 기포력을 높이기 위해 다당류 중 어느 하나를 포함하는 것을 특징으로 한다. claims: 무환자, 비누풀 그리고 도라지의 아임계 추출물 및,도토리와 쇠뜨기의 아임계 추출물을 포함하는 세정제 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

85/1150 Row 85: application_number: 1020200106207, combined_string: invention_title: 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법 및 이를 함유하는 화장료 조성물 abstract: 본 발명은 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법 및 이를 함유하는 화장료 조성물에 관한 것으로서, 더욱 상세하게는 각종 생약 추출물을 가온 마이크로버블 추출 방법을 활용하여 추출 효율을 극대화시킬 수 있는 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법 및 이를 함유하는 화장료 조성물에 관한 것이다. claims: 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법에 있어서,가온마이크로버블시스템(1000)의 천연추출물공급자켓(100)의 내부 공간에 천연 화장품 원료를 투입하기 위한 천연화장품원료투입단계(S100);와가온마이크로버블시스템(1000)의 용매공급용펌프(200)를 동작시켜 용매탱크(300)에 저장된 용매를 천연추출물공급자켓(100)으로 공급하기 위한 용매투입단계(S200);와가온마이크로버블시스템(1000)에서 용매투입선감지센서(950)로부터 제공된 이벤트 신호를 획득할 경우에 용매공급용펌프(200)로 동작 정지 신호를 제공하여 용매 공급을 차단하기 위한 용매공급차단단계(S300);와가온마이크로버블시스템(1000)의 마이크로버블발생기(600)를 동작시키고, 일정 시간 경과 후, 마이크로버블공급용펌프(500)를 동작시켜 마이크로버블발생기(600)에 의해 발생된 마이크로 버블을 천연추출물공급자켓(100)으로 공급하여 마이크로 버블에 의해 천연 화장품 원료와 용매가 지속적으로 접촉하고, 용존 산소 및 OH 라디칼의 증가를 통해 유용 성분의 추출을 수행하기 위한 마이크로버블공급단계(S400);와가온마이크로버블시스템(1000)의 가온수단(800)을 동작시켜 천연추출물공급자켓(100) 내부의 온도를 높이고, 이를 통해 공급된 용매를 가열시켜 천연 화장품 원료의 유용 성분의 추출을 극대화시키기 위한 가온단계(S500);와가온마이크로버블시스템(1000)에서 용매수위상한선감지센서(970)로부터 제공된 이벤트 신호를 획득할 경우에 마이크로버블공급용펌프(500)의 토출량을 줄여주기 위하여 마이크로버블공급용펌프(500)로 토출량 감소 신호를 제공하여 추출 진행에 따른 거품 발생을 축소시키기 위한 거품발생축소단계(S510);와가온마이크로버블시스템(1000)이 설정된 시간 경과 후, 마이크로버블공급용펌프(500) 및 마이크로버블발생기(600)로 동작 정지 신호를 제공하여 동작을 종료시키며, 일정 시간 경과 후, 가온수단(800)에 동작 정지 신호를 제공하여 천연 화장품 원료의 추출 공정을 마무리하기 위한 가온마이크로버블공정마무리단계(S600);와가온마이크로버블시스템(1000)에서 용매배출구(905)에 형성된 용매배출밸브(915)에 개방 신호를 송출하여 용매배출구(905)를 개방시켜 천연추출물공급자켓(100)의 내부 공간에 추출 후 존재하는 용매를 외부로 배출하는 용매배출단계(S700);를 포함하여 구성되되,상기 단계를 수행하기 위하여, 가온마이크로버블시스템(1000)은,내부에 일정한 체적 공간을 가지고 있으며, 상측에 화장료 조성물로 이용되는 천연 화장품 원료를 투입하기 위한 천연재료투입구(110)가 형성되어 있는 천연추출물공급자켓(100);과상기 천연추출물공급자켓(100)의 어느 일측에 형성시켜 천연추출물공급자켓(100)으로 용매탱크에 보관된 용매를 공급하게 되는 용매공급용펌프(200);와상기 용매공급용펌프(200)에 연결되어 용매공급용펌프(200)가 동작할 경우에 저장된 용매를 천연추출물공급자켓(100)으로 공급하게 되는 용매탱크(300);와상기 천연추출물공급자켓(100)에 일측이 설치 구성하여 용매공급용펌프(200)로부터 공급받은 용매를 공급하기 위한 용매공급수단(400);과상기 천연추출물공급자켓(100)의 하측에 구성하여 천연추출물공급자켓(100)에 마이크로버블발생기로부터 발생된 마이크로 버블을 공급하게 되는 마이크로버블공급용펌프(500);와상기 마이크로버블공급용펌프(500)에 연결하여 마이크로버블공급용펌프(500)가 동작할 경우에 발생된 마이크로 버블을 천연추출물공급자켓(100)으로 공급하게 되는 마이크로버블발생기(600);와상기 천연추출물공급자켓(100)의 일측에 설치 구성하여 마이크로버블공급용펌프(500)로부터 공급받은 마이크로 버블을 공급하기 위한 마이크로버블공급수단(700);과천연추출물공급자켓(100)의 외면을 따라 설치 구성하여 전원이 공급될 경우에 가온되어 상기 천연추출물공급자켓(100) 내부의 온도를 높이고, 이를 통해 공급된 용매를 가열시켜 천연 화장품 원료의 유용 성분의 추출을 더욱 극대화시키게 되는 가온수단(800);을 특징으로 하며,상기 가온수단(800)은,상기 천연추출물공급자켓(100)의 중심축을 기준으로 원통 모양으로 권취되어 나선형을 형성하는 열에너지생성코일부(810);상기 열에너지생성코일부(810)로 주파수를 발진하는 주파수발진부(820);를 포함하여 구성하는 것을 특징으로 하며,상기 천연추출물공급자켓(100)에는 용매투입선감지센서(950)보다 높은 위치에 용매수위상한선감지센서(970)를 설치 구성하는 것을 특징으로 하며,상기 가온마이크로버블시스템(1000)에는컨트롤러(900);가 형성되게 되는데,상기 컨트롤러(900)는,용매공급수단(400)에 형성된 용매공급밸브(925)에 개방 신호를 제공하고, 개방될 경우에 용매공급용펌프(200)에 동작 신호를 제공하여 동작시켜 용매탱크(300)에 저장된 용매를 천연추출물공급자켓(100)으로 공급하기 위한 용매공급처리부(910);와용매투입선감지센서(950)에서 용매를 감지하게 되면 임계치에 도달함을 알리기 위한 이벤트 신호를 생성하여 용매공급용펌프(200)로 동작 정지 신호를 제공하기 위한 용매공급용펌프동작정지처리부(920);와마이크로버블발생기(600)를 동작시키기 위한 동작 신호를 제공하고, 설정된 시간만큼 경과 후, 마이크로버블공급용펌프(500)를 동작시키기 위한 동작 신호를 제공하고, 마이크로버블발생기(600)에 의해 발생된 마이크로 버블을 천연추출물공급자켓(100)으로 공급하기 위하여 마이크로버블공급밸브(935)로 동작 신호를 제공하기 위한 마이크로버블공급처리부(930);와가온수단(800)을 동작시키기 위하여 가온수단으로 동작 신호를 제공하기 위한 가온수단동작처리부(940);와설정된 시간 경과 후, 마이크로버블공급용펌프(500) 및 마이크로버블발생기(600)로 동작 정지 신호를 제공하여 동작을 종료시키며, 일정 시간 경과 후, 가온수단(800)에 동작 정지 신호를 제공하여 천연 화장품 원료의 추출 공정을 마무리하기 위한 추출공정마무리처리부(950);와용매수위상한선감지센서(970)로부터 제공된 이벤트 신호, 즉, 수위 감지 신호를 획득할 경우에 마이크로버블공급용펌프(500)의 토출량을 줄여주기 위하여 마이크로버블공급용펌프(500)로 토출량 감소 신호를 제공하여 추출 진행에 따른 거품 발생을 축소시키기 위한 거품발생축소처리부(960);와용매배출밸브(915)에 개방 신호를 송출하여 용매배출구(905)를 개방시켜 천연추출물공급자켓(100)의 내부 공간에 추출 후 존재하는 용매를 외부로 배출하기 위한 용매배출처리부(970);를 특징으로 하며,상기 마이크로버블발생기(600)는 5 ~ 50um 의 포어사이즈, 1.0 ~ 1.2 Ton / hr 의 토출량을 가진 것을 특징으로 하는 가온 마이크로버블을 이용한 천연 화장품 원료의 추출물 제조 방법.제 1항의 제조방법으로 제조된 천연 추출물을 유효성분으로 함유하는 화장료 조성물., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

86/1150 Row 86: application_number: 1020200103058, combined_string: invention_title: 천연 추출물을 이용한 기능성 마스크 제조공법 및 이의 제조공법으로 제조된 마스크 abstract: 본 발명은 천연 추출물을 이용한 기능성 마스크 제조공법 및 이의 제조공법으로 제조된 마스크에 관련되며, 이는 마스크원단 생지에 녹차 추출물, 편백 추출물, 치자 추출물, 청미래덩굴 추출물을 포함하는 천연염료를 염색처리하여 마스크원단 생지 고유의 이취를 제거함과 더불어 살균작용으로 마스크 착용자 입냄새 구취 제거 및 비말로 인한 세균번식을 차단하여 장시간 쾌적한 착용감을 제공할 수 있도록 천연염색단계(S10), 가재단단계(S20), 천연분말 합성공정(S30), 정재단단계(S40), 성형공정(S50), 접합공정(S60)을 포함하여 주요구성으로 한다. claims: 마스크원단 생지(10)를 평탄화처리 후, 녹차 추출물, 편백 추출물, 치자 추출물, 청미래덩굴 추출물 중 어느 1종 이상의 추출물을 포함하는 천연염료를 이용하여 염색하는 천연염색단계(S10);상기 천연염색단계(S10)를 거친 염색원단(20)을 평탄화처리 후, 소정의 사이즈로 가재단하는 가재단단계(S20);상기 가재단단계(S20)를 거친 가재단원단(30)을 평탄화처리 후, 녹차, 편백, 쑥, 생강, 솔잎 중 어느 1종 이상의 천연분말을 첨가하는 천연분말 합성공정(S30);상기 천연분말이 첨가된 가재단원단(30)을 마스크모양으로 정재단하는 정재단단계(S40);정재단원단(40)을 마스크 모양으로 봉제 및 프레스 가공하는 성형공정(S50); 및상기 성형공정(S50)을 거친 마스크본체(50) 양측에 끈(52)을 부착하는 접합공정(S60);을 포합하고,상기 천연염색단계(S10)에서 천연염료는 물 100% 중량부 기준 녹차, 편백, 치자, 청미래덩굴 중 어느 1종 이상의 천연분말을 5~10 중량부를 혼합한 후, 5~15℃ 온도에서 1~3일 동안 우려내는 방식으로 추출한 후, 여과처리하여 준비되며,상기 천연염료는 염색조(100)에 저장되고, 상기 마스크원단 생지(10)는 복수의 상, 하부 피딩롤러(120)(140)를 경유하여 지그재그방향으로 횡형 이동되며, 상기 하부 피딩롤러(140)는 염색조(100)에 저장된 천연염료에 잠기도록 배치되고, 상기 마스크원단 생지(10)가 상, 하부 피딩롤러(120)(140)를 타고 피딩되는 중에 하부 피딩롤러(140)와 대응하는 위치에서 천연염료에 일시적으로 잠기면서 염색이 이루어지며, 상부 피딩롤러(120) 내부에 내부히터(122)가 설치되거나 상부 피딩롤러(120)와 대응하는 외측에 외부히터(124)가 설치되어 염색처리된 마스크원단 생지(10)를 건조하도록 구비되며, 상기 하부 피딩롤러(140)를 경유하는 중에 수행되는 염색과정과 상부 피딩롤러(120)를 경유하는 중에 수행되는 건조과정을 수회 반복하여 천연염료에 의핸 염색농도가 조절되도록 구비되는 것을 특징으로 하는 천연 추출물을 이용한 기능성 마스크 제조공법.상기 제 1항, 제 2항, 제 5항 내지 제 12항 중 어느 한 항의 천연 추출물을 이용한 기능성 마스크 제조공법을 이용하여,녹차 추출물, 편백 추출물, 치자 추출물, 청미래덩굴 추출물 중 어느 1종 이상의 추출물을 포함하는 천연염료에 염색하여 형성되는 마스크본체(50) 양측에 끈(52)을 부착하여 형성되는 것을 특징으로 하는 천연 추출물을 이용한 기능성 마스크 제조공법으로 제조된 마스크., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

87/1150 Row 87: application_number: 1020200096555, combined_string: invention_title: 천연 추출물을 함유하는 면역력 증강용 조성물 abstract: 본 발명은 천연 추출물을 유효성분으로 포함하는 혈액순환 개선 및 면역력 증진 효능을 가지는 조성물에 관한 것으로, 노니, 사과, 양파, 가지, 대두, 생강 및 카카오 추출물을 유효성분으로 포함하는 본 발명의 조성물은 혈액순환을 개선하고 면역기능을 강화한다. 또한 본 발명의 천연 추출물은 세포 독성이 없어 약학적 및 식품 조성물에 안전하게 사용할 수 있다. claims: 노니, 사과, 양파, 가지, 대두, 생강 및 카카오 추출물을 유효성분으로 포함하는 천연 추출물을 함유하는 면역력 증강용 조성물.제 1 항 내지 제 3 항 중 어느 한 항에 있어서.상기 조성물이 약학적 조성물인 것을 특징으로 천연 추출물을 함유하는 면역력 증강용 조성물.제 1 항 내지 제 3 항 중 어느 한 항에 있어서.상기 조성물이 식품 조성물인 것을 특징으로 천연 추출물을 함유하는 면역력 증강용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

88/1150 Row 88: application_number: 1020200095495, combined_string: invention_title: 천연발효 추출물 혼합 조성물 abstract: 본 발명은 한국에서 자생하는 천연식물들을 열수추출한 열수 추출물을 농축과 증류수를 일정비율로 혼합한 혼합물을 다단 발효시킨 복합발효물을 숙성시킨 숙성물을 농축시켜 제조한 천연 발효 추출물 혼합 조성물 및 이를 화장품 원료, 건강기능식품 원료, 바이오 천연 약물 원료 등으로 적용할 수 있는 발명에 관한 것이다. claims: 천연식물 복합 열수 추출물을 다단 발효시킨 발효물의 숙성물을 농축시킨 농축물을 포함하며,상기 천연식물 복합 열수 추출물은 천연식물 혼합 건조물을 열수 추출시켜서 수득한 열수 추출물이고,상기 천연식물 혼합 건조물은 쇠뜨기 100 중량부에 대하여, 어성초 1 ~ 5 중량부, 쇠비름 5 ~ 10 중량부, 붉나무 1 ~ 10 중량부, 비누나무 1 ~ 5 중량부, 함초 5 ~ 10 중량부, 백작약 1 ~ 5 중량부, 숙지황 20 ~ 30 중량부, 목단피 20 ~ 30 중량부, 백부근 30 ~ 50 중량부, 섬가시오가피 20 ~ 40 중량부, 황칠 1 ~ 10 중량부, 사상자 1 ~ 10 중량부, 형개 1 ~ 10 중량부, 지부자 10 ~ 20 중량부, 백두옹 0.5 ~ 5 중량부, 금화규 1 ~ 5 중량부, 당귀 5 ~ 20 중량부 및 꾸지뽕의 잎과 줄기 20 ~ 30 중량부를 포함하며,상기 발효물은 혐기성균을 이용한 1차 발효, 호기성균을 이용한 2차 발효 및 토양 미생물을 이용한 3차 발효를 포함하는 다단 발효 공정을 수행한 발효물을 포함하고,상기 혐기성균은 바실러스 속균 및 누룩균을 1 : 0.1 ~ 0.2 비율(CFU 비율)로 혼합한 혐기성 혼합 균주를 포함하며,상기 호기성균은 마리노박터균과 효모균을 1 : 1 ~ 2 비율(CFU 비율)로 혼합한 호기성 혼합 균주를 포함하고,상기 토양 미생물은 버섯균 및 유산균 중에서 선택된 1종 또는 2종을 포함하는 것을 특징으로 하는 천연발효 추출물 혼합 조성물.제3항의 천연발효 추출물 혼합 조성물을 포함하는 화장료.제3항의 천연발효 추출물 혼합 조성물을 포함하는 건강기능식품.천연식물 혼합 건조물을 열수 추출하여 열수 추출물을 제조하는 1단계;상기 천연식물 복합 열수 추출물 및 증류수를 혼합한 혼합액을 다단 발효를 수행하여 발효물을 수득하는 2단계;상기 발효물을 3 ~ 10℃ 하에서 24 ~ 48 시간 동안 숙성시켜서 숙성물을 수득하는 3단계; 및상기 숙성물을 농축시켜서 농축액을 제조하는 4단계;를 포함하는 공정을 수행하며,상기 다단 발효는 1단계에서 제조한 상기 천연식물 복합 열수 추출물 및 증류수를 1 : 1 ~ 3 부피비로 혼합한 혼합액에 혐기성균을 접종한 후, 40 ~ 50℃에서 15~20일간 1차 발효를 수행하여 1차 발효액을 수득하는 2-1 단계;1차 발효액을 필터링한 후, 필터링된 1차 발효액에 호기성균을 접종한 후, pH 5.5 ~ 6.5 및 15~40℃에서 3~5일간 2차 발효를 수행하여 2차 발효액을 수득하는 2-2단계; 및2차 발효액을 필터링한 후, 필터링된 2차 발효액에 광합성 미생물과 토양미생물을 접종한 후, 3차 발효를 수행하여 3차 발효액을 수득한 후, 필터링하여 다단 발효공정을 수행한 발효물을 제조하는 2-3단계;를 포함하는 공정을 수행하고,상기 천연식물 혼합 건조물은 쇠뜨기 100 중량부에 대하여, 어성초 1 ~ 5 중량부, 쇠비름 5 ~ 10 중량부, 붉나무 1 ~ 10 중량부, 비누나무 1 ~ 5 중량부, 함초 5 ~ 10 중량부, 백작약 1 ~ 5 중량부, 숙지황 20 ~ 30 중량부, 목단피 20 ~ 30 중량부, 백부근 30 ~ 50 중량부, 섬가시오가피 20 ~ 40 중량부, 황칠 1 ~ 10 중량부, 사상자 1 ~ 10 중량부, 형개 1 ~ 10 중량부, 지부자 10 ~ 20 중량부, 백두옹 0.5 ~ 5 중량부, 금화규 1 ~ 5 중량부, 당귀 5 ~ 20 중량부 및 꾸지뽕의 잎과 줄기 20 ~ 30 중량부를 포함하며,상기 발효물은 혐기성균을 이용한 1차 발효, 호기성균을 이용한 2차 발효 및 토양 미생물을 이용한 3차 발효를 포함하는 다단 발효 공정을 수행한 발효물을 포함하고,상기 혐기성균은 바실러스 속균 및 누룩균을 1 : 0.1 ~ 0.2 비율(CFU 비율)로 혼합한 혐기성 혼합 균주를 포함하며,상기 호기성균은 마리노박터균과 효모균을 1 : 1 ~ 2 비율(CFU 비율)로 혼합한 호기성 혼합 균주를 포함하고,상기 토양 미생물은 버섯균 및 유산균 중에서 선택된 1종 또는 2종을 포함하는 것을 특징으로 하는 천연발효 추출물 혼합 조성물의 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

89/1150 Row 89: application_number: 1020200081542, combined_string: invention_title: 천연 식물추출물을 함유하는 탈취제 조성물 abstract: 본 발명은 천연 식물추출물을 함유하는 탈취제 조성물에 관한 것으로, 보다 구체적으로는 밤부사 불가리스잎/줄기 추출물, 삼나무잎 추출물, 편백잎 추출물, 나한백가지 추출물 및 분비나무 오일로 이루어진 혼합물을 함유하는 탈취제 조성물에 관한 것이다. 본 발명에 따른 탈취제 조성물은 악취를 유발하는 주요성분인 암모니아, 초산, 포름알데히드, 황화수소, 트리메틸아민에 대한 소취효과가 우수하므로 탈취제로 유용하게 사용될 수 있다. claims: 밤부사 불가리스잎/줄기 추출물, 삼나무잎 추출물, 편백잎 추출물, 나한백가지 추출물 및 분비나무 오일이 동일한 중량비로 혼합되어 이루어지는 혼합물을 탈취제 조성물 전체 중량에 대하여 2.0~5.0중량% 함유하여 암모니아, 초산, 포름알데히드, 황화수소 및 트리메틸아민에 대한 소취효과를 나타내는 탈취제 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

90/1150 Row 90: application_number: 1020200074790, combined_string: invention_title: 천연물 유래 추출물 및 이를 포함하는 화장료 조성물 및 이의 제조방법 abstract: 본 발명은 천연물 유래 추출물 및 에센셜 오일을 함유하는 화장료 조성물에 관한 것으로서, 상기 화장료 조성물은 피부장벽 개선, 피부 보습, 피부 진정, 각질제거, 블랙헤드 케어, 피부결 정돈, 광채감 부여 및 영양공급 효과를 갖는 것을 특징으로 한다. claims: 육두구(Nutmeg) 20 내지 50 중량부, 하늘타리(Chinese cucumber) 뿌리 20 내지 50 중량부, 흰무늬엉겅퀴(Silybum marianum) 씨 10 내지 40 중량부, 엘더플라워(Elder flower) 10 내지 40 중량부, 다마스크장미(Rosa Damascena) 꽃 10 내지 30 중량부, 라벤더꽃 10 내지 30 중량부, 클레리(Salvia Sclarea) 10 내지 30 중량부, 히아신스(Hyacinthus) 전초 1 내지 30 중량부, 마트리카리아(Matricaria chamomilla) 꽃 1 내지 30 중량부, 보리지(Borago officinalis) 1 내지 30 중량부 및 수레국화(Centaurea cyanus) 꽃 1 내지 30 중량부로부터 수득한 추출물; 및 베르가못(citrus aurantium bergamia, bergamot) 오일 1 내지 5 중량부, 티트리(Melaleuca alternifolia) 오일 1 내지 5 중량부, 오렌지(Citrus Aurantium Dulcis) 오일 1 내지 5 중량부 및 해바라기씨 오일 1 내지 30 중량부를 포함하여 제조된 것인, 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

91/1150 Row 91: application_number: 1020200064776, combined_string: invention_title: 오미자, 백리향 및 꽃향유의 추출 혼합물을 유효성분으로 함유하는 천연 방부대체제 및 이의 용도 abstract: 본 발명은 오미자, 백리향 및 꽃향유의 추출 혼합물을 유효성분으로 함유하는 천연 방부대체제 및 이의 용도에 관한 것으로, 본 발명의 오미자, 백리향 및 꽃향유의 추출 혼합물은 스타필로코커스 아우레우스(Staphlyococcus aureus), 슈도모나스 에루지노사(Pseudomonas aeruginosa), 대장균(Escherichia coli), 칸디다 알비칸스(Candida albicans) 및 아스퍼질러스 브라실리엔시스(Aspergillus brasiliensis)에 대해 우수한 항균 효과를 나타내며, 이를 함유한 화장료 조성물은 항균력, 방부력 및 보존력이 우수하므로, 합성 방부제를 대체할 수 있는 천연 방부제로서 화장료 조성물 제조에 매우 유용하게 이용될 수 있다. claims: 칸디다 알비칸스(Candida albicans) 및 아스퍼질러스 브라실리엔시스(Aspergillus brasiliensis)에 대한 항균 활성을 가지는, 4:1:1의 중량비로 혼합한 오미자, 백리향 및 꽃향유 에탄올 추출물의 혼합물을 유효성분으로 포함하는 방부제 조성물., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

92/1150 Row 92: application_number: 1020200060133, combined_string: invention_title: 액화 천연 가스(LNG)로부터 천연 가스액(NGL)을 추출하는 추출 시스템 abstract: 소비지에 가깝기 때문에 상정되는 LNG 새틀라이트 기지로부터 아임계 압력으로 공급되는 액화 천연 가스를 사용하여 천연 가스액을 추출하는 시스템을 제공하는 것이다.천연 가스액 추출 시스템은, 소정 압력의 액화 천연 가스가 원료로서 공급되는 제1 탑정부(11)와, 제1 증류부(12)와, 제1 리보일러(131)를 구비하는 제1 탑저부(13)를 갖는 제1 탑(1)과, 제1 콘덴서(211)를 구비하는 제2 탑정부(21)와, 제1 탑저부(13)로부터 도출되는 제1 증류 유체가 그 중간단에 공급되는 제2 증류부(22)와, 제2 리보일러(231)를 구비하는 제2 탑저부(23)를 갖는 제2 탑(2)을 구비한다. claims: 소정 압력의 액화 천연 가스가 원료로서 공급되는 제1 탑정부(11)와, 제1 증류부(12)와, 제1 리보일러(131)를 구비하는 제1 탑저부(13)를 갖는 제1 탑(1)과,제1 콘덴서(211)를 구비하는 제2 탑정부(21)와, 상기 제1 탑저부(13)로부터 도출되는 제1 증류 유체가 그 중간단에 공급되는 제2 증류부(22)와, 제2 리보일러(231)를 구비하는 제2 탑저부(23)를 갖는 제2 탑(2)을 구비하는 천연 가스액 추출 시스템.내부 펌프(502)를 구비하는 LNG 탱크(501)와,상기 LNG 탱크(501)로부터 도출되는 소정 압력의 액화 천연 가스가 원료로서 공급되는 제1 탑정부(11)와, 제1 증류부(12)와, 제1 리보일러(131)를 구비하는 제1 탑저부(13)를 갖는 제1 탑(1)과,제1 콘덴서(211)를 구비하는 제2 탑정부(21)와, 상기 제1 탑저부(13)로부터 도출되는 제1 증류 유체가 그 중간단에 공급되는 제2 증류부(22)와, 제2 리보일러(231)를 구비하는 제2 탑저부(23)를 갖는 제2 탑(2)과,상기 메탄 부화 가스와 상기 에탄 부화 가스를 포함하는 연료 가스와, LNG 탱크(501)로부터 취출된 BOG의 혼합 가스를 승압시키는 컴프레서(503)와,상기 내부 펌프(502)에 의해 보내진 LNG의 전부 또는 그 일부를 승압시키는 승압 장치(505)와,상기 승압 장치(505)에서 승압된 승압 LNG의 일부를 증발시켜 천연 가스로 하는 증발기(506)와,상기 승압 장치(505)에서 승압된 승압 LNG의 일부를 냉열원으로 하여, 랭킨 사이클(60)의 작동 유체를 액화시키는 작동 유체 열교환기(61)와,상기 작동 유체 열교환기(61)에서 액화된 작동 유체를 승압시키는 작동 유체 승압 장치(62)와,작동 유체 승압 장치(62)에서 승압된 작동 유체를 증발시키는 작동 유체 증발기(63)와,상기 작동 유체 증발기(63)에서 증발된 작동 유체를 팽창시시키는 팽창 터빈(64)과,상기 제2 탑저부(23)로부터 회수된 프로판 부화 유체가 도입되는, 상기 작동 유체의 랭킨 사이클(60)의 작동 유체 라인(L60)을 구비하는, 랭킨 사이클을 구비하는 천연 가스액 추출 시스템.내부 펌프(502)를 구비하는 LNG 탱크(501)와,상기 LNG 탱크(501)로부터 도출되는 소정 압력의 액화 천연 가스가 원료로서 공급되는 제1 탑정부(11)와, 제1 증류부(12)와, 제1 리보일러(131)를 구비하는 제1 탑저부(13)를 갖는 제1 탑(1)과,제1 콘덴서(211)를 구비하는 제2 탑정부(21)와, 상기 제1 탑저부(13)로부터 도출되는 제1 증류 유체가 그 중간단에 공급되는 제2 증류(칼럼)부(22)와, 제2 리보일러(231)를 구비하는 제2 탑저부(23)를 갖는 제2 탑(탈에탄탑)(2)과,제2 콘덴서(312)를 구비하는 제3 탑정부(31)와, 상기 제2 탑저부(23)로부터 도출되는 제2 증류 유체가 그 중간단에 공급되는 제3 증류(칼럼)부(32)와, 제3 리보일러(331)를 구비하는 제3 탑저부(33)를 갖는 제3 탑(3)과,상기 메탄 부화 가스와 상기 에탄 부화 가스를 포함하는 연료 가스와, LNG 탱크(501)로부터 취출된 BOG의 혼합 가스를 승압시키는 컴프레서(503)와,상기 LNG 탱크(501)로부터 도출되는 LNG의 전부 또는 그 일부를 승압시키는 승압 장치(505)와,상기 승압 장치(505)에서 승압된 승압 LNG의 일부를 증발시켜 천연 가스로 하는 증발기(506)와,상기 승압 장치(505)에서 승압된 승압 LNG의 일부를 냉열원으로 하여, 랭킨 사이클(60)의 작동 유체를 액화시키는 작동 유체 열교환기(61)와,상기 작동 유체 열교환기(61)에서 액화된 작동 유체를 승압시키는 작동 유체 승압 장치(62)와,작동 유체 승압 장치(62)에서 승압된 작동 유체를 증발시키는 작동 유체 증발기(63)와,상기 작동 유체 증발기(63)에서 증발된 작동 유체를 팽창시시키는 팽창 터빈(64)과,상기 제1 탑정부(11)로부터 회수되는 메탄 부화 가스의 일부, 상기 제2 탑정부(21)로부터 회수되는 에탄 부화 가스의 일부, 상기 제3 탑정부(31)로부터 회수되는 프로판 부화 유체의 일부, 상기 제3 탑저부(33)로부터 회수되는 부탄 부화 유체의 일부 중, 1종 또는 1종 이상의 혼합 유체가 도입되는, 상기 작동 유체의 랭킨 사이클(60)의 작동 유체 라인(L60)을 구비하는 랭킨 사이클을 구비하는 천연 가스액 추출 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

93/1150 Row 93: application_number: 1020200055124, combined_string: invention_title: 드라이아이스를 이용한 천연물의 추출방법 및 이에 따라 수득된 추출물을 함유하는 조성물 abstract: 본 발명은 드라이아이스를 이용한 천연물의 추출방법 및 이에 따라 수득된 추출물을 함유하는 조성물에 관한 것이다. 본 발명에 따른 추출방법은 천연물로부터 추출되는 활성성분의 양을 현저하게 증가시켜줄 수 있다. 특히, 본 발명에 따른 추출방법이 적용될 수 있는 천연물에는 제한이 없으며, 활성성분 또는 추출물이 나타내는 효과에 따라 화장품, 식품, 의약외품, 의약품 등 다양한 분야에서 활용이 가능하다. claims: 식물, 과일, 광물, 동물, 및 이로부터 생성되는 분비물 및 대사산물 중에서 선택되는 하나 이상인 천연물의 추출방법으로서, 하기 단계를 포함하는 추출방법:a) 천연물에 용매 물을 첨가하는 단계;b) 상기 a) 단계의 생성물에 드라이아이스를 첨가하여 추출하는 단계; 및c) 상기 b) 단계에서 수득된 추출물을 분리하여 여과하는 단계.제1항에 있어서,상기 b) 단계에서 수득된 추출물 또는 상기 c) 단계에서 수득된 여과물을 농축하는 d) 단계를 더 포함하는 것을 특징으로 하는 추출방법.제1항에 따라 수득된 추출물을 포함하는 화장품 조성물.제1항에 따라 수득된 추출물을 포함하는 식품 조성물.제1항에 따라 수득된 추출물을 포함하는 의약외품 조성물.제1항에 따라 수득된 추출물을 포함하는 의약품 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

94/1150 Row 94: application_number: 1020200052371, combined_string: invention_title: 천연 추출물 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 조성물 abstract: 본 발명은 천연물 기반인 녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 화장료 조성물에 관한 것이다. 본 발명의 조성물은 다양한 원인에 기한 피부의 비정상적 상태(아토피, 염증, 홍반, 산화, 피부 내 세포 독성물질, 수분의 소실, 기미, 가려움, 거칠어짐, 주름 등)를 효과적으로 진정시킬 수 있다. claims: 녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 화장료 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 항염증 또는 아토피 피부염의 개선인 것을 특징으로 하는 피부 진정용 화장료 조성물.제 1 항의 화장료 조성물을 포함하는 마스크팩.녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 식품 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 항염증 또는 아토피 피부염의 개선인 것을 특징으로 하는 피부 진정용 식품 조성물.녹용 유래 엑소좀을 유효성분으로 포함하는 피부 진정용 약제학적 조성물로서, 상기 엑소좀의 직경은 120 내지 600 ㎚이며, 상기 피부 진정은 항염증 또는 아토피 피부염의 개선인 것을 특징으로 하는 피부 진정용 약제학적 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

95/1150 Row 95: application_number: 1020200050675, combined_string: invention_title: 백합조개의 패각분말과 천연추출물이 함유된 치약조성물 abstract: 본 발명은 백합조개의 패각분말 1~3 중량%, 쓴쑥 추출물 0.2 중량%, 두송열매 추출물 0.2 중량%, 페퍼민트잎 추출물 0.2 중량%, 참당귀 추출물 0.2 중량%, 어성초 추출물 0.2 중량%, 고본 추출물 0.2 중량%, 인삼 추출물 0.5 중량%, 목향 추출물 0.3 중량%, 황금 추출물 0.2 중량%, 오미자 추출물 0.3 중량%, 캐모마일 추출물 0.5 중량%, 라타니아 추출물 0.7 중량%, 염장된 올리브열매 추출물 0.6 중량%가 함유된 것임을 특징으로 하는 치약조성물을 제공함으로써, 구강 내 탁월한 항균작용에 의해 각종 치과 질환 치료에 우수한 효과를 발휘할 수 있고, 치아 연마세정작용도 동시에 병행하게 하는 효과가 있다. claims: 백합조개의 패각분말 1~3 중량%, 쓴쑥 추출물 0.2 중량%, 두송열매 추출물 0.2 중량%, 페퍼민트잎 추출물 0.2 중량%, 참당귀 추출물 0.2 중량%, 어성초 추출물 0.2 중량%, 고본 추출물 0.2 중량%, 인삼 추출물 0.5 중량%, 목향 추출물 0.3 중량%, 황금 추출물 0.2 중량%, 오미자 추출물 0.3 중량%, 캐모마일 추출물 0.5 중량%, 라타니아 추출물 0.7 중량%, 염장된 올리브열매 추출물 0.6 중량%가 함유된 것임을 특징으로 하는 치약조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

96/1150 Row 96: application_number: 1020200049051, combined_string: invention_title: 피부노화방지 및 피부주름개선용 천연추출물을 함유한 화장품 및 이의 제조방법 abstract: 본 발명은 일정기간 식물성추출물을 발효 피부주름개선 비타민이 풍부한 균주를 원료로 하여 피부 노화방지 및피부 주름 개선용 천연추출물 숙성 발효 조성물 및 이를 이용한 화장품에 관한 것으로서, 좀 더 구체적으로 설명하면, 인공향료, 인공색소, 메틸 파라벤 등의 인공적인 합성 또는 화학성분을 주성분으로 사용하지 않으면서, 부작용을 일으키지 않고 장기간 동안 사용 가능 하면서도, 피부 흡수력이 우수하여 피부 주름개선 및 피부 노화방지력이 우수한 천연 영양성분의 화장료 조성물, 이를 포함하는 화장품에 관한 것이다. claims: 54 ~ 56Hz 클러스터의 전해환원수;잣나무잎 액상 발효 추출물, 편백잎 액상 발효 추출물, 녹차잎 액상 발효 추출물 및 병풀 액상 발효 추출물을포함하는 숙성 발효 추출물; 및감식초 및 벌꿀을 포함하는 보존제;를 포함하는 것을 특징으로 하는 피부노화방지 및 피부주름개선용 천연추출, Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

97/1150 Row 97: application_number: 1020200047157, combined_string: invention_title: 천연추출물을 포함하는 피부 미백 및 보습용 화장료 조성물 abstract: 본 발명은 천연추출물을 포함하는 피부 미백 및 보습용 화장료 조성물에 관한 것이다.본 발명에 따른 천연추출물을 포함하는 피부 미백 및 보습용 화장료 조성물은 병풀 추출물, 매생이 추출물, 오레가노 오일, 브링그라즈 오일, 호호바씨 오일, 누에 숙성분말 가공유, 셀레늄 및 옥파우더를 포함한다.상기한 구성에 의해 본 발명에 따른 화장료 조성물은 천연추출물을 유효성분으로 포함함으로써, 피부 미백 및 보습 효과가 있고 피부의 건강을 향상시킬 수 있다. claims: 병풀 추출물, 매생이 추출물, 오레가노 오일, 브링그라즈 오일, 호호바씨 오일, 누에 숙성분말 가공유, 셀레늄 및 옥파우더를 포함하되,상기 병풀 추출물 1 내지 3 중량부, 매생이 추출물 0.1 내지 1.5 중량부, 오레가노 오일 0.1 내지 0.5 중량부, 브링그라즈 오일 0.05 내지 0.15 중량부, 호호바씨 오일 0.05 내지 0.15 중량부, 누에 숙성분말 가공유 0.1 내지 0.5 중량부, 셀레늄 0.01 내지 0.1 중량부 및 옥파우더 0.005 내지 0.015 중량부의 중량 비율로 포함되고,상기 매생이 추출물은, 매생이를 준비한 후 상기 매생이를 15 내지 25℃ 온도의 정제수로 제1 세척하고, 상기 제1 세척된 매생이를 숙성액에 침지시켜 제2 세척하되, 상기 제2 세척은 녹차 잎, 월계수 잎 및 정제수를 0.5:1.5:8의 중량 비율로 혼합하고, 상기 녹차 잎 및 월계수 잎이 혼합된 정제수를 70 내지 75℃의 온도에서 20 내지 60분 동안 가열한 후 녹차 잎 및 월계수 잎을 제거하고 여과하여 여과액을 제조하며, 상기 여과액에 오징어 먹물을 9.5:0.5의 중량비로 혼합하고 10 내지 15℃의 온도에서 3 내지 6시간 동안 숙성시켜 숙성액을 제조하며, 상기 정제수로 세척된 매생이를 상기 숙성액에 침지시킨 후 5 내지 7℃의 온도에서 10 내지 20분 동안 보관하고, 상기 숙성액에 침지된 매생이를 분리한 후 15 내지 20℃ 온도의 정제수로 세척하는 과정으로 진행되며, 상기 제2 세척된 매생이를 45 내지 50℃의 온도에서 20 내지 40시간 동안 보관하여 건조시키고, 상기 건조된 매생이 100 중량부에 대해 진피 발효액 1 내지 5 중량부의 중량 비율로 혼합한 후 8 내지 12℃의 온도에서 20 내지 40시간 동안 보관함으로써 상기 매생이를 숙성 발효시키며, 상기 숙성 발효된 매생이를 -20 내지 -30℃의 온도에서 동결 건조하고, 상기 동결 건조된 매생이를 분쇄하여 매생이 분말을 제조한 후, 상기 매생이 분말 100 중량부에 대해 정제수 2,000 내지 2,500 중량부의 중량 비율로 혼합하고, 90 내지 95℃의 온도에서 5 내지 10시간 동안 열수 추출하여 매생이 열수 추출물을 제조하며, 상기 매생이 열수 추출물을 -40 내지 -50℃의 온도에서 동결 건조하여 동결 건조된 매생이 열수 추출물을 제조하고, 상기 동결 건조된 매생이 열수 추출물을 환류 추출하는 과정을 거쳐 제조된 것을 특징으로 하는 천연추출물을 포함하는 피부 미백 및 보습용 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

98/1150 Row 98: application_number: 1020200044781, combined_string: invention_title: 천연물 추출수를 포함한 세탁 세제, 섬유 유연제, 주방 세제, 샴푸, 바디 클렌져 등 세정용 조성물 및 그 제조 방법 abstract: 천연물 추출수를 포함한 세정용 조성물 및 그 제조 방법이 제공된다. claims: 천연물 추출수를 포함한 세정용 조성물의 제조 방법으로서,붉나무, 오배자, 무환자 및 노니 중에서 선택된 1종 이상의 천연물을 열수 추출하여 천연물 추출수를 제조하는 단계를 포함한, 세정용 조성물의 제조 방법.천연물 추출수를 포함하고,상기 천연물 추출수는 붉나무, 오배자, 무환자 및 노니 중에서 선택된 1종 이상의 천연물로부터 유래된, 세정용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

99/1150 Row 99: application_number: 1020200044123, combined_string: invention_title: 천연추출물을 유효성분으로 하는 여드름 증상의 예방, 완화 또는 치료용 조성물 abstract: 본 발명은 유효성분으로서 참깨(Sesamum Indicum (Sesame) Seed) 추출물, 로버참나무껍질(Quercus Robur Bark Extract) 추출물 및 어성초(Houttuynia Cordata) 추출물을 포함하며, 이에 추가 유효성분으로서 엉겅퀴(Cirsium Japonicum) 추출물 및 측백나무(Thuja orientalis) 중 적어도 하나 이상의 천연물질을 포함하는 여드름 증상의 예방, 완화 또는 치료용 조성물에 관한 것으로, 여드름 발생 원인 균주인 C.acnes에 대한 높은 항균활성능을 가짐으로써, 여드름의 예방, 개선 또는 치료 효과를 가지는 천연추출물을 유효성분으로 하는 여드름 증상의 예방, 완화 또는 치료용 조성물에 관한 것이다. claims: 유효성분으로 참깨 추출물, 로버참나무껍질 추출물 및 어성초 추출물을 포함하며, 이에 추가 유효성분으로서 엉겅퀴 추출물 또는 측백나무 추출물을 포함하는 것을 특징으로 하는 여드름 증상의 예방, 완화 또는 치료용 조성물.유효성분으로 참깨 추출물, 로버참나무껍질 추출물 및 어성초 추출물을 포함하며, 이에 추가 유효성분으로서 엉겅퀴 추출물 또는 측백나무 추출물을 포함하는 것을 특징으로 하는 여드름 증상의 예방 또는 완화를 위한 화장료 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

100/1150 Row 100: application_number: 1020210012264, combined_string: invention_title: 스마트 캠핑장 관리 시스템 abstract: 본 발명은 스마트 캠핑장 관리 시스템에 관한 것으로, 보다 상세하게는 캠핑장마다 무선인터넷 환경을 구축하여 캠핑장마다 고유의 컨텐츠를 제공하며, 캠핑장의 방역과 안전을 위해 비대면 출입통제 및 동선관리가 가능한 스마트 캠핑장 관리 시스템을 제공하는 것이다. claims: 원격지에 설치된 복수의 스마트 캠핑장을 관리하는 시스템으로,복수의 스마트 캠핑장 식별정보와 각 스마트 캠핑장 내부에 서로 이격되게 설치되는 복수의 액세스 포인트(AP) 식별정보를 저장하며, 사용자통신단말에서 와이파이 접속 앱(APP)을 실행하여 생성한 일회용 패스워드 정보를 캠핑장 PC로부터 수신하면 상기 일회용 패스워드 정보의 유효성을 인증하고 인증 결과를 캠핑장 PC로 전송하는 인증서버; 관리자의 조작에 따라 복수의 스마트 캠핑장 내부에 설치된 복수의 액세스 포인트(AP) 식별정보를 입력받아 저장하며 이를 상기 인증서버로 전송하고, 캠핑장 PC로부터 스마트 캠핑장 식별정보와 액세스 포인트(AP) 식별정보와 접속된 사용자정보와 시간정보를 입력받아 저장하며, 상기 스마트 캠핑장 식별정보와 액세스 포인트(AP) 식별정보와 사용자정보 및 시간정보를 수집 및 분석하여 각 스마트 캠핑장의 사용빈도에 관한 통계정보를 생성하여 저장하는 관리서버;스마트 캠핑장 식별정보를 포함하는 복수의 스마트 캠핑장 정보와 각 스마트 캠핑장별 컨텐츠정보를 생성, 저장 또는 편집하고, 상기 생성, 저장 또는 편집된 복수의 스마트 캠핑장 정보와 스마트 캠핑장별 컨텐츠정보를 해당 캠핑장 PC로 전송하는 컨텐츠 제공서버;스마트 캠핑장 식별정보를 포함하는 복수의 스마트 캠핑장 정보와 광고 정보를 저장하고, 상기 관리서버에 저장된 각 스마트 캠핑장의 사용빈도에 관한 통계정보를 이용하여 광고 송출 기준을 만족하는 스마트 캠핑장이 있는지를 판단하고, 판단결과 긍정인 해당 캠핑장 PC로 광고 정보를 전송하는 광고서버; 및복수의 스마트 캠핑장 식별정보와 예약 정보를 저장하고, 사용자통신단말로 예약안내정보를 전송하고 사용자가 선택한 스마트 캠핑장정보와 예약날짜와 전체 이용자정보가 입력되면 이를 저장하고, 사용자가 선택한 스마트 캠핑장에 대응하는 와이파이 접속 앱(APP)을 다운받도록 안내하는 연결정보를 사용자통신단말로 전송하는 예약서버를 포함하며,상기 컨텐츠정보는, 각 스마트 캠핑장의 일교차, 지리적 정보, 유해 동물 및 유해 곤충이 출몰하는 위험지역에 대한 정보 및 캠핑장 시설에 대한 정보를 포함하는 캠핑장 정보와, 캠핑 장비들의 설치 방법과 사용 방법을 포함하는 캠핑 장비 이용 정보와, 캠핑장에서 먹을 수 있는 요리의 정보를 포함하는 캠핑 조리 정보 및 스마트 캠핑장에서 제작한 게임정보를 포함하는 것을 특징으로 하는,스마트 캠핑장 관리시스템., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

101/1150 Row 101: application_number: 1020210012672, combined_string: invention_title: 컨테이너 조경수 생산 및 유통 관리를 위한 ERP 시스템과 그 방법 abstract: 본 발명은 컨테이너 조경수 생산 및 유통 관리를 위한 ERP 시스템과 그 방법을 개시한다. 즉, 본 발명은 컨테이너에서 재배되는 수목인 컨테이너 조경수의 생육 데이터, 환경 데이터 등을 근거로 딥러닝 또는 기계 학습을 통해 생육 데이터를 예측하고, 생산성 환경을 분석하여, 최적의 조경수 생산을 위한 생산성 환경을 추천함으로써, 데이터 기반의 표준화된 조경수 데이터베이스를 구축하고, 조경수 생산을 위한 스마트 재배 시스템의 전체 운영 효율을 향상시킬 수 있다. claims: 앱 실행 결과 화면 중에서 미리 설정된 생육 예측 데이터 메뉴가 선택될 때, 조경수에 대한 생육과 관련한 예측 데이터를 확인하기 위한 생육 예측 데이터 화면을 표시하고, 썸네일 형태로 표시되는 복수의 조경수 중에서 어느 하나의 특정 조경수가 선택될 때, 상기 선택된 특정 조경수에 대응하는 생육 예측 데이터를 표시하는 단말;상기 단말의 요청에 따라 복수의 조경수의 고유 식별 정보별 생육 예측 데이터 중에서 상기 조경수의 고유 식별 정보에 대응하는 생육 예측 데이터를 확인하고, 상기 확인된 상기 조경수의 고유 식별 정보에 대응하는 생육 예측 데이터를 상기 단말에 제공하는 ERP 서버; 특정 조경수와 관련한 영상 정보, 생육 데이터 및 환경 데이터를 수집하는 데이터 수집부; 및복수의 조경수로 구성된 농장의 환경을 제어하는 스마트 재배 시스템을 포함하며,상기 ERP 서버는,상기 데이터 수집부로부터 전송되는 특정 조경수와 관련한 영상 정보, 생육 데이터 및 환경 데이터를 수신하고, 상기 영상 정보에 포함된 특정 조경수를 미리 설정된 수형 이미지 분류 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 영상 정보에 포함된 특정 조경수의 수형, 높이, 너비 및 생태학적 분류와 이용상의 분류와 생육 환경에 따른 분류를 포함하는 상기 특정 조경수의 분류를 확인하고, 상기 스마트 재배 시스템과 연동하여 상기 특정 조경수와 관련한 고유 식별 정보 및 조경수 관리 데이터를 수집하고, 상기 영상 정보, 생육 데이터 및 환경 데이터를 표준화하고, 표준화된 규격의 조경수 데이터베이스를 구축하고, 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생육 데이터 예측 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생육과 관련한 생육 예측 데이터를 생성하고, 상기 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생산성 환경 분석 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생산 환경과 관련한 분석 결과를 생성하고, 상기 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생산성 환경 추천 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생산 환경과 관련한 추천 결과를 생성하며,상기 단말은,상기 표시되는 앱 실행 결과 화면 중에서 미리 설정된 스마트 재배 제어 메뉴가 선택될 때, 특정 조경수에 대한 생장에 필요한 단계별 작업 관리를 위한 스마트 재배 제어 화면을 표시하고, 상기 ERP 서버 및 상기 스마트 재배 시스템과 연동하여, 상기 단말에 표시되는 스마트 재배 제어 화면에서 관리자 입력에 따라 상기 농장에 구성된 하나 이상의 관리 장치의 작동을 제어하며,상기 표준화된 규격은,생태학적 분류, 이용상의 분류 및 생육 환경에 따른 분류를 포함하는 조경수의 분류와, 조경수목 사진과, 높이와, 너비를 포함하며,상기 농장에 구성된 하나 이상의 관리 장치는,온도 관리 장치, 수분 관리 장치, 차광 관리 장치, 관수 관리 장치, 시비 관리 장치, 제초 관리 장치, 병충해 관리 장치, 수형 관리 장치, 풍해 관리 장치 및 월동 관리 장치를 포함하는 것을 특징으로 하는 컨테이너 조경수 생산 및 유통 관리를 위한 ERP 시스템.단말에 의해, 앱 실행 결과 화면에서 미리 설정된 영상 확인 메뉴가 선택될 때, 농장에 설치된 복수의 카메라를 통해 실시간으로 조경수의 상태를 확인하기 위한 영상 확인 화면을 표시하는 단계;상기 단말의 영상 확인 화면 내의 농장의 지도상에 표시되는 복수의 카메라 중에서 어느 하나의 카메라가 선택될 때, 상기 단말에 의해, 상기 선택된 카메라로부터 획득되는 실시간 영상 정보를 표시하는 단계;상기 앱 실행 결과 화면 중에서 미리 설정된 생육 예측 데이터 메뉴가 선택될 때, 상기 단말에 의해, 조경수에 대한 생육과 관련한 예측 데이터를 확인하기 위한 생육 예측 데이터 화면을 표시하는 단계;상기 단말의 생육 예측 데이터 화면 내의 농장의 지도상에 표시되는 복수의 조경수 중에서 어느 하나의 특정 조경수가 선택될 때, 상기 단말에 의해, ERP 서버와 연동하여, 상기 선택된 특정 조경수에 대응하는 생육 예측 데이터를 표시하는 단계; 데이터 수집부에 의해, 특정 조경수와 관련한 영상 정보, 생육 데이터 및 환경 데이터를 수집하는 단계;상기 ERP 서버에 의해, 상기 데이터 수집부로부터 전송되는 특정 조경수와 관련한 영상 정보, 생육 데이터 및 환경 데이터를 수신하는 단계;상기 ERP 서버에 의해, 상기 영상 정보에 포함된 특정 조경수를 미리 설정된 수형 이미지 분류 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 영상 정보에 포함된 특정 조경수의 수형, 높이, 너비 및 분류를 확인하는 단계;상기 ERP 서버에 의해, 복수의 조경수로 구성된 농장의 환경을 제어하는 스마트 재배 시스템과 연동하여, 상기 특정 조경수와 관련한 고유 식별 정보 및 조경수 관리 데이터를 수집하는 단계;상기 ERP 서버에 의해, 상기 영상 정보, 생육 데이터 및 환경 데이터를 표준화하고, 표준화된 규격의 조경수 데이터베이스를 구축하는 단계;상기 ERP 서버에 의해, 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생육 데이터 예측 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생육과 관련한 생육 예측 데이터를 생성하는 단계;상기 ERP 서버에 의해, 상기 특정 조경수와 관련한 고유 식별 정보와 상기 생성된 생육 예측 데이터를 매핑하여 저장하는 단계;상기 ERP 서버에 의해, 상기 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생산성 환경 분석 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생산 환경과 관련한 분석 결과를 생성하는 단계;상기 ERP 서버에 의해, 상기 미리 설정된 조경수와 관련한 기본 데이터, 상기 수신된 특정 조경수와 관련한 생육 데이터 및 환경 데이터를 미리 설정된 생산성 환경 추천 모델의 입력값으로 하여 기계 학습을 수행하고, 기계 학습 결과를 근거로 상기 특정 조경수의 생산 환경과 관련한 추천 결과를 생성하는 단계;상기 ERP 서버에 의해, 상기 특정 조경수와 관련한 고유 식별 정보와 상기 생성된 분석 결과와 상기 생성된 추천 결과를 매핑하여 저장하는 단계;상기 표시되는 앱 실행 결과 화면 중에서 미리 설정된 스마트 재배 제어 메뉴가 선택될 때, 상기 단말에 의해, 특정 조경수에 대한 생장에 필요한 단계별 작업 관리를 위한 스마트 재배 제어 화면을 표시하는 단계; 및상기 단말에 의해, 상기 ERP 서버 및 상기 스마트 재배 시스템과 연동하여, 상기 단말에 표시되는 스마트 재배 제어 화면에서 관리자 입력에 따라 상기 농장에 구성된 하나 이상의 관리 장치의 작동을 제어하는 단계를 포함하며,상기 영상 정보에 포함된 특정 조경수의 수형, 높이, 너비 및 분류를 확인하는 단계는,상기 기계 학습 수행에 따라 생태학적 분류, 이용상의 분류 및 생육 환경에 따른 분류를 포함하는 상기 특정 조경수의 분류를 확인하며,상기 표준화된 규격은,생태학적 분류, 이용상의 분류 및 생육 환경에 따른 분류를 포함하는 조경수의 분류와, 조경수목 사진과, 높이와, 너비를 포함하며,상기 농장에 구성된 하나 이상의 관리 장치는,온도 관리 장치, 수분 관리 장치, 차광 관리 장치, 관수 관리 장치, 시비 관리 장치, 제초 관리 장치, 병충해 관리 장치, 수형 관리 장치, 풍해 관리 장치 및 월동 관리 장치를 포함하는 것을 특징으로 하는 컨테이너 조경수 생산 및 유통 관리를 위한 ERP 방법., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

102/1150 Row 102: application_number: 1020200178788, combined_string: invention_title: 음파 및 IoT 기반의 농작물 생장 제어 및 병해충 방제 시스템 abstract: 본 발명은 시설재배지의 농작물의 생장 환경 정보를 생성하는 온습도센서, 조도 센서, 진동 센서, 적외선 센서, 초음파 센서 및 이산화탄소(CO2) 측정센서 및 재배농작물의 영상을 촬영하여 촬영영상을 생성하는 영상 센서를 포함하는 멀티 센서 모듈(10); 상기 멀티 센서 모듈로부터 생성된 농작물의 생장 환경 정보 및 촬영 영상에 기초하여 판단된 상기 농작물의 생장 단계 또는 병해충의 종류에 따라 상이한 주파수를 갖는 음파를 방사시키는 음파 방사 모듈(20); 상기 생장 환경 정보를 선택적으로 수신하고 상기 영상센서의 촬영 영상으로부터 영상데이터를 생성하는 주제어모듈(30); 및 상기 생장 환경 정보 또는 상기 영상 데이터를 상기 주 제어모듈(30)로부터 관리 서버(50)에 유선 또는 무선으로 전송하는 통신 모듈(40)을 포함할 수 있다. claims: 시설재배지의 농작물의 생장 환경 정보를 생성하는 온습도센서, 조도 센서, 진동 센서, 적외선 센서, 초음파 센서 및 이산화탄소(CO2) 측정센서 및 재배농작물의 영상을 촬영하여 촬영영상을 생성하는 영상 센서를 포함하는 멀티 센서 모듈(10); 멀티 센서 모듈로부터 생성된 농작물의 생장 환경 정보 및 촬영 영상에 기초하여 판단된 농작물의 생장 단계 및 농장물의 생육 단계에 따라 주파수 및 음압에 대한 데이터와 병해충의 종류에 따른 방제 특성을 가진 음파에 대한 데이터가 저장된 방사 음파 데이터베이스에 기초하여 병해충의 종류에 따라 상이한 주파수를 갖는 음파를 방사시키는 음파 방사 모듈(20);생장 환경 정보를 선택적으로 수신하고 영상센서의 촬영 영상으로부터 영상데이터를 생성하는 주제어모듈(30); 및 생장 환경 정보 또는 영상 데이터를 상기 주 제어모듈(30)로부터 관리 서버(50)에 유선 또는 무선으로 전송하는 통신 모듈(40)을 포함하고, 음파는 주파수 범위가 20Hz 내지 40kHz이고 음압은 1m 이내에서 80 내지 90dB이며, 영상데이터의 특징 벡터를 추출하여 미리 저장된 병해충 데이터 베이스를 탐색하여 특정 병해충 이미지 데이터의 존재를 확인하여 후보 병해충 이미지 데이터로부터 농작물의 병해충의 발생 여부 또는 발생된 병해충의 종류를 판단하고,멀티 센서 모듈(10)에 의해 생성된 농작물의 생장 환경 정보는 멀티 센서 모듈(10)에 포함된 초음파 센서에서 발사된 초음파 펄스가 농작물의 잎이나 줄기의 표면에서 반사되어 초음파 센서로 되돌아올 때까지의 시간을 측정하여 획득한 농작물의 크기 및 도달 거리에 관한 정보를 포함하는 것을 특징으로 하는 음파 및 IoT기반의 농작물 생장 제어 및 병해충 방제 시스템., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

103/1150 Row 103: application_number: 1020200135202, combined_string: invention_title: 공간정보를 이용한 확률지도와 정사영상의 이미지 학습을 연계한 고사목 및 병해충 모니터링 시스템 abstract: 본 발명은 공간정보를 이용한 확률지도와 정사영상의 이미지 학습을 연계한 고사목 및 병해충 모니터링 시스템에 관한 것으로서, 본 발명은 병해충 피해목을 모니터링하기 위한 모니터링부; 및 상기 고사목 및 병해충 모니터링부로부터 제공되는 데이터를 저장하거나, 상기 고사목 및 병해충 모니터링부에 데이터를 제공하는 공간 DBMS를 포함하고, 상기 고사목 및 병해충 모니터링부는, 정사이미지와 제1 위치정보를 갖는 고사목 및 병해충 분포도를 기반으로 고사목 및 병해충 발생확률을 나타내는 제1 확률지도를 생성하는 제1 모니터링부; 및 공간 DBMS의 공간정보 및 상기 제1 위치정보를 갖는 고사목 및 병해충 분포도를 기반으로 고사목 및 병해충 발생확률을 나타내는 제2 확률지도를 생성하는 제2 모니터링부를 포함한다. claims: 고사목 및 병해충을 모니터링하기 위한 모니터링부; 및 상기 모니터링부로부터 제공되는 데이터를 저장하거나, 상기 모니터링부에 데이터를 제공하는 공간 DBMS; 및확률지도 조합부를 포함하여 구성되고, 상기 모니터링부는, 정사이미지와 제1 위치정보를 갖는 고사목 및 병해충 분포도를 기반으로 인공지능 학습방법을 이용하여 고사목 및 병해충 발생확률을 나타내는 제1 확률지도를 생성하는 제1 모니터링부; 및공간 DBMS의 공간정보 및 상기 제1 위치정보를 갖는 고사목 및 병해충 분포도를 기반으로 고사목 및 병해충 발생확률을 나타내는 제2 확률지도를 생성하는 제2 모니터링부를 포함하며,상기 확률지도 조합부는 상기 제1 확률지도 및 상기 제2 확률지도에서 동일지점의 병해충 발생확률을 미리 설정된 가중치로 연산하여 제3 확률지도를 생성하고,상기 제1모니터링부는 상기 공간DBMS에 저장된 정사이미지를 복수의 타일링 이미지로 분할하고, 분할된 타일링 이미지 각각에 대한 속성정보를 공간DBMS에 저장하며, 상기 속성정보는 병해충 발생확률 정보 및 병해충 발생영역 여부에 대한 샘플링 정보를 포함하고, 상기 샘플링 정보는 제1 위치정보에 대응하며 검출모델을 생성하는데 사용되는 제1-1 타일링 이미지, 제1 위치정보에 대응하며 검출모델을 검증하는데 사용되는 제1-2 타일링 이미지 및 제1 위치정보에 대응하지 않는 제2 타일링 이미지로 분류되고,상기 제1모니터링부의 검출모델 생성부는,제1-2 타일링 이미지에 대해 검출모델을 적용하여 병해충 발생확률을 계산하고, 병해충 발생확률이 설정값 이상일때 병해충 피해목이 위치하는 것으로 판단하며, 상기 설정값 이상의 발생확률을 갖는 제1-2 타일링 이미지의 개수 대비 제1-2 타일링 이미지의 전체 개수를 비율로 계산하고, 상기 비율이 설정값을 넘는지 비교하여 검출모델의 적합성을 판단하는 공간정보를 이용한 확률지도와 정사영상의 이미지 학습을 연계한 고사목 및 병해충 모니터링 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

104/1150 Row 104: application_number: 1020200127585, combined_string: invention_title: 패턴을 갖는 조류 충돌방지용 필름 제조방법 abstract: 본 발명은 조류 충돌방지용 필름 제조방법에 관한 것으로, 더욱 상세하게는 베이스층을 형성하는 베이스층형성단계, 상기 베이스층의 일측면에 일정 간격으로 패턴을 형성하는 패턴형성단계, 상기 패턴이 형성된 베이스층의 일측면에 접착제를 도포하는 접착제도포단계, 상기 접착제가 도포된 베이스층의 일측으로 보호층을 형성하는 보호층형성단계, 상기 베이스층의 타측면에 스크래치방지층을 형성하는 스크래치방지층형성단계, 상기 보호층의 일측면에 점착제를 도포하여 점착층을 형성하는 점착층형성단계, 및 상기 점착층이 형성된 보호층의 일측면에 커버층을 형성하는 커버층형성단계,를 포함한다.상기한 바와 같이, 조류의 시야에 장애물이 확인되어 충돌을 방지할 수 있어 안전사고를 방지함은 물론, 설치하고자 하는 면에 쉽게 부착시킬 수 있어 작업효율을 향상시킬 수 있을 뿐만 아니라 여러 자연 환경에도 변형이 거의 없어 유지 보수가 용이한 매우 유용하고 효과적인 발명이다. claims: 베이스층을 형성하는 베이스층형성단계;상기 베이스층의 일측면에 일정 간격으로 패턴을 형성하는 패턴형성단계;상기 패턴이 형성된 베이스층의 일측면에 접착제를 형성하는 접착제형성단계;상기 접착제가 형성된 베이스층의 일측으로 보호층을 형성하는 보호층형성단계;상기 베이스층의 타측면에 스크래치방지층을 형성하는 스크래치방지층형성단계;상기 보호층의 일측면에 점착제를 형성하여 점착층을 형성하는 점착층형성단계; 및상기 점착층이 형성된 보호층의 일측면에 커버층을 형성하는 커버층형성단계;를 포함하고,상기 베이스층형성단계의 베이스층은 투명한 수지재로 형성되며,상기 패턴형성단계의 패턴은 알루미늄, 은, 세라믹, 진주펄 중 어느 하나 이상이고,상기 각 패턴의 간격은 세로 5cm 및 가로 5cm로 형성되는 것을 특징으로 하는 패턴을 갖는 조류 충돌방지용 필름 제조방법.제1항 내지 제2항 중 어느 한 항의 조류 충돌방지용 필름 제조방법에 의해 제조되는 조류 충돌방지용 필름., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

105/1150 Row 105: application_number: 1020200104661, combined_string: invention_title: 동작 및 온도 감지 기반의 해충 퇴치용 LED 조명장치 abstract: 본 발명에 따른 동작 및 온도 감지 기반의 해충 퇴치용 LED 조명장치는 550 내지 700nm의 광파장을 발광하는 복수의 LED가 행렬 구조로 배치된 기판; 상기 기판에 설치된 것으로, 해충의 움직임을 감지하는 동작감지센서; 상기 기판에 설치된 것으로, 15 내지 25kHz 대역의 음파를 발생하는 음파 발생기; 상기 기판을 감싸는 하우징; 상기 하우징에서 상기 LED의 대향 측에 설치된 방열판; 상기 LED와 방열판에서 이격된 상기 하우징의 일 측에 형성된 것으로서, 외부 온도를 측정하는 온도감지센서; 상기 기판에 장착된 것으로서, 상기 동작감지센서의 동작 감지 및 상기 온도감지센서의 온도 감지로 상기 LED 및 음파 발생기를 구동하는 컨트롤러;를 포함하는 것을 특징으로 한다. claims: 동작 및 온도 감지 기반의 해충 퇴치용 LED 조명장치로서,550 내지 700nm의 광파장을 발광하는 복수의 LED가 행렬 구조로 배치된 기판;상기 기판에 설치된 것으로, 해충의 움직임을 감지하는 동작감지센서; 상기 기판에 설치된 것으로, 15 내지 25kHz 대역의 음파를 발생하는 음파 발생기;상기 기판을 감싸는 하우징;상기 하우징에서 상기 LED의 대향 측에 설치된 방열판;상기 LED와 방열판에서 이격된 상기 하우징의 일 측에 형성된 것으로서, 외부 온도를 측정하는 온도감지센서;상기 기판에 장착된 것으로서, 상기 동작감지센서의 동작 감지 및 상기 온도감지센서의 온도 감지로 상기 LED 및 음파 발생기를 구동하는 컨트롤러;를 포함하되,상기 컨트롤러는,상기 동작감지센서 및 상기 온도감지센서를 통해 해충 개체수의 고저를 파악하는 개체수 파악모듈과, 상기 해충 개체수의 고저에 따라 상기 LED의 광파장과 상기 음파 발생기의 주파수 대역 및 작동 시간을 차등 조절하는 차등 제어모듈을 포함하고,상기 차등 제어모듈은,다음의 수학식 1을 통해 상기 주파수 대역을 차등 조절하는 것을 특징으로 하는, LED 조명장치.수학식 1.(여기서, 은 기준 주파수(23 내지 25 kHz), 는 상기 음파 발생기의 주파수(kHz), T는 상기 온도감지센서에서 측정한 온도(℃), L은 상기 해충 개체수의 고저에 따른 레벨()로서, 개체수가 많을수록 증가), Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

106/1150 Row 106: application_number: 1020200085955, combined_string: invention_title: 솔수염하늘소 방제용 조성물 및 이를 이용한 솔수염하늘소의 방제 방법 abstract: 본 발명은 보베리아 바시아나 ERL836 균주 (KCCM11506P) 또는 이의 포자를 유효성분으로 포함하는 솔수염하늘소 방제용 조성물 및 이를 이용한 솔수염하늘소의 방제 방법에 관한 것으로, 상기 솔수염하늘소 방제용 조성물은 보베리아 바시아나 ERL836 균주 (KCCM11506P) 또는 이의 포자를 유효성분으로 포함함으로써 소나무재선충병을 매개하는 솔수염하늘소에 대해 우수한 살충효과를 나타낼 수 있으며, 인체나 다른 생물에 피해를 주지 않고 친환경적으로 소나무재선충의 피해를 줄일 수 있다. claims: 보베리아 바시아나 ERL836 균주 (KCCM11506P) 또는 이의 포자를 유효성분으로 포함하는 솔수염하늘소 방제용 조성물.솔수염하늘소 알 또는 유충의 감염이 의심되는 나무에 청구항 1의 솔수염하늘소 방제용 조성물을 살포하는 단계를 포함하는 솔수염하늘소의 방제 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

107/1150 Row 107: application_number: 1020200016831, combined_string: invention_title: 식물성 유지가 포함된 친환경 방제소재를 이용한 플로팅 방제장치 abstract: 본 발명은 식물성 유지기반 플로팅 방제장치에 관한 것으로서, 농작물의 오염과 환경교란 등 경제적, 사회적 문제로 심각하게 대두되는 농약을 사용을 저감할 수 있고, 온실의 내부로 휘산되는 식물성 유지를 이용하여 병해충을 높은 효율로 제충할 수 있는 식물성 유지기반 플로팅 방제장치에 관한 것이다. claims: 상부가 개방된 수용홈이 형성된 휘산용기와;식물성유지가 포함된 친환경 병충해 방제소재가 수용되는 수용용기와;상기 수용용기에 수용된 식물성유지가 포함된 친환경 병충해 방제소재를 일정량 상기 휘산용기의 수용홈으로 공급하는 식물성유지 공급부와;상기 식물성유지공급부에 의해 상기 휘산용기의 수용홈에 공급된 친환경 병충해 방제소재를 식물성유지의 휘산온도로 가열시키는 히터부와;상기 휘산용기 및 히터부가 내부에 수용되는 수용몸체와;상기 수용몸체와 연통된 상태로 상기 수용몸체의 상부에 상하각도조절가능하도록 하부가 축결합되고, 내부로 유입된 상기 히터부에 의해 휘산된 식물성 유지를 외부로 안내하는 가이드몸체와;상기 가이드몸체의 일측에 구비되어 상기 가이드몸체의 내부로 유입된 상기 히터부에 의해 휘산된 식물성 유지를 상기 가이드몸체의 타측 외부방향으로 배기시키는 팬부재;를 포함하고,상기 수용몸체의 하부 측면에 상기 수용몸체 주변의 외부공기를 상기 수용몸체의 내부로 안내하는 가이드슬릿이 형성되며,상기 수용몸체의 상부와 상기 팬부재 사이의 상기 가이드몸체의 내부 하측에 상기 가이드몸체의 하부 타측방향으로 볼록한 호형상으로 구비되어 상기 팬부재에 의해 상기 가이드몸체의 외부로 유입된 외부공기를 상기 수용몸체의 상부방향의 상기 가이드몸체의 내부 상측으로 안내하는 가이드판;이 구비되는 것을 특징으로 하는 식물성 유지가 포함된 친환경 방제소재를 이용한 플로팅 방제장치.식물성유지가 포함된 친환경 병충해 방제소재를 휘산온도로 가열하여 외부로 휘산시키는 히터부와;상기 히터부가 내부에 수용되는 수용몸체와;상기 수용몸체와 연통된 상태로 상기 수용몸체의 상부에 상하각도조절가능하도록 하부가 축결합되고, 내부로 유입된 상기 히터부에 의해 휘산된 식물성 유지를 외부로 안내하는 가이드몸체와;상기 가이드몸체의 일측에 구비되어 상기 가이드몸체의 내부로 유입된 상기 히터부에 의해 휘산된 식물성 유지를 상기 가이드몸체의 타측 외부방향으로 배기시키는 팬부재;가 구비되고,상기 수용몸체의 하부 측면에 상기 수용몸체 주변의 외부공기를 상기 수용몸체의 내부로 안내하는 가이드슬릿이 형성되며,상기 수용몸체의 상부와 상기 팬부재 사이의 상기 가이드몸체의 내부 하측에 상기 가이드몸체의 하부 타측방향으로 볼록한 호형상으로 구비되어 상기 팬부재에 의해 상기 가이드몸체의 외부로 유입된 외부공기를 상기 수용몸체의 상부방향의 상기 가이드몸체의 내부 상측으로 안내하는 가이드판;이 구비되는 것을 특징으로 하는 식물성 유지가 포함된 친환경 방제소재를 이용한 플로팅 방제장치., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

108/1150 Row 108: application_number: 1020200014121, combined_string: invention_title: 딸기 흰가루병 방제 약제 및 이의 제조방법과 용도 abstract: 본 발명은 살균제와 신고지막 500배액 내지 800배액을 복합함으로써 살균제의 약 효과를 향상하고 농약의 사용 횟수를 줄여 약물 사용 안전성을 향상하는 딸기 흰가루병 방제 약제를 제공한다. 상기 방제 약제를 딸기에 응용함으로써 딸기 과일 또는 딸기 식물체 표면에 한 층의 고분자 막을 형성할 수 있어 식물의 수분 흡수, 통기성 및 광 투과 품질을 최적화하며, 병충 포식 신호를 차단하고 전파 매체를 약화시킬 수 있어 딸기 흰가루병에 대하여 보다 양호한 방제 효과을 구비하여 딸기의 안전생산에 기술보장을 제공함으로써 높은 실제의 응용가치를 구비한다. claims: 신고지막과 살균제를 포함하며 여기서, 신고지막은 신고지막 500배액 내지 800배액인 것을 특징으로 하는 딸기 흰가루병 방제 약제.제 1 항 내지 제 4 항 중 임의의 한 항에 따른 딸기 흰가루병 방제 약제의 제조방법에 있어서,단계 (1) 500배 내지 800배의 사용량으로 희석된 신고지막을 일부분 물에 용해하여 용액 A를 얻으며;단계 (2) 살균제를 다른 일부분 물에 용해하여 용액 B를 얻으며;단계 (3) 상기 용액 A와 상기 용액 B를 혼합하고 나머지 물을 첨가한 후 균일하게 혼합하여 신고지막의 500배 내지 800배 희석액과 살균제 희석액을 얻음으로써 딸기 흰가루병 방제 약제를 조제하는 단계를 포함하는 것을 특징으로 하는 딸기 흰가루병 방제 약제의 제조방법.제 1 항 내지 제 4 항 중 임의의 한 항에 따른 딸기 흰가루병 방제 약제를 포함하는 것을 특징으로 하는 분무액.제 1 항 내지 제 4 항 중 임의의 한 항에 따른 방제 약제가 딸기 과일 및/또는 딸기 식물체에 적용되는 방법.제 1 항 내지 제 4 항 중 임의의 한 항에 따른 방제 약제가 딸기 흰가루병 방제에 적용되는 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

109/1150 Row 109: application_number: 1020200009227, combined_string: invention_title: 나무심기 입지 분석 장치 및 방법 abstract: 본 발명은 나무심기 입지 분석 장치 및 방법에 관한 것으로, 상기 장치는 특정 지역에 관한 연속지적도를 기준으로 이용현황, 도시계획 및 특정지목과 연관된 식재 불가 지역을 순차적으로 반영하여 식재 가능 지역을 결정하는 식재 가능 지역 결정부, 상기 식재 가능 지역에 대해 물리적 또는 비물리적 요인으로 분류되는 토지 특성 요인들에 따라 토지 특성을 도출하는 토지 특성 도출부 및 상기 토지 특성을 고려하여 상기 식재 가능 지역에 관한 적합 수종을 결정하는 적합 수종 결정부를 포함한다. claims: 특정 지역에 관한 연속지적도를 기준으로 이용현황, 도시계획 및 특정지목과 연관된 식재 불가 지역을 순차적으로 반영하여 식재 가능 지역을 결정하는 식재 가능 지역 결정부;상기 식재 가능 지역에 대해 물리적 또는 비물리적 요인으로 분류되는 토지 특성 요인들에 따라 토지 특성을 도출하는 토지 특성 도출부; 및상기 토지 특성을 고려하여 상기 식재 가능 지역에 관한 적합 수종을 결정하는 적합 수종 결정부를 포함하는 나무심기 입지 분석 장치.나무심기 입지 분석 장치에서 수행되는 방법에 있어서,특정 지역에 관한 연속지적도를 기준으로 이용현황, 도시계획 및 특정지목과 연관된 식재 불가 지역을 순차적으로 반영하여 식재 가능 지역을 결정하는 단계;상기 식재 가능 지역에 대해 물리적 또는 비물리적 요인으로 분류되는 토지 특성 요인들에 따라 토지 특성을 도출하는 단계;상기 토지 특성을 고려하여 상기 식재 가능 지역에 관한 적합 수종을 결정하는 단계; 및상기 식재 가능 지역의 식재가능 면적을 고려하여 상기 적합 수종의 식재 효과를 산출하는 단계를 포함하는 나무심기 입지 분석 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

110/1150 Row 110: application_number: 1020200004448, combined_string: invention_title: 수목 정보 제공 시스템 abstract: 본 발명은 수목 정보 제공 시스템에 관한 것으로, 해결하고자 하는 기술적 과제는 온라인 상에서 위치에 제약 없이 사용자가 필요할 때 특정 지역이나 위치에 식재된 수목에 대한 병충해 등의 상태나 이를 위한 관리 또는 진료 정보를 열람할 수 있도록 하는데 있다.일례로, 사용자 통신단말에 설치되고, 지도 서비스를 기반으로 사용자로부터 식재된 수목의 상태정보를 입력 받아 서버에 등록하고, 사용자의 열람요청에 따른 수목 별 상태정보를 지도 상에 표시하여 제공하는 수목 정보 어플리케이션; 및 상기 수목 정보 어플리케이션을 통해 수신되는 수목의 위치정보 및 상태정보를 저장하고, 상기 열람요청에 따른 위치정보를 기반으로 수목 상태정보를 상기 수목 정보 어플리케이션으로 제공하는 수목 정보 서버를 포함하는 수목 정보 제공 시스템을 개시한다. claims: 사용자 통신단말에 설치되고, 지도 서비스를 기반으로 사용자로부터 식재된 수목의 상태정보를 입력 받아 서버에 등록하고, 사용자의 열람요청에 따른 수목 별 상태정보를 지도 상에 표시하여 제공하는 수목 정보 어플리케이션; 및 상기 수목 정보 어플리케이션을 통해 수신되는 수목의 위치정보 및 상태정보를 저장하고, 상기 열람요청에 따른 위치정보를 기반으로 수목 상태정보를 상기 수목 정보 어플리케이션으로 제공하는 수목 정보 서버; 및수목 식별정보에 각각 대응되는 마커를 포함하고, 수목 별로 부착 또는 설치된 수목 마커정보 표시부를 포함하고,상기 수목 정보 어플리케이션은, 상기 수목 식별정보에 대하여 수목 진료기록정보를 입력 받고, 입력된 상기 수목 진료기록정보를 상기 수목 정보 서버에 등록 요청하는 수목 진료기록정보 등록 요청부;사용자 통신단말의 위치정보 또는 사용자에 의해 지정된 위치정보에 따른 상기 열람요청을 상기 수목 정보 서버에 전달하고, 사용자 통신단말의 위치정보 또는 사용자에 의해 지정된 위치정보를 기반으로 지도 상에 표시되는 아이콘 별로 상기 수목 진료기록정보를 각각 제공하는 수목 진료기록정보 검색 제공부;사용자 통신단말의 위치정보를 기반으로 상기 수목 식별정보를 입력하고, 입력된 수목 식별정보와 사용자 통신단말의 위치정보를 매칭하고, 위치정보가 매칭된 수목 식별정보를 상기 수목 정보 서버에 등록 요청하는 수목 식별정보 등록 요청부;상기 수목 식별정보에 대하여 다수의 수목 상태정보 중 적어도 하나를 선택 또는 입력 받고, 입력된 상기 수목 상태정보에 따라 미리 설정된 아이콘을 생성하여 상기 수목 식별정보에 대한 상기 수목 상태정보를 상기 수목 정보 서버에 등록 요청하는 수목 상태정보 등록 요청부;사용자 통신단말의 위치정보 또는 사용자에 의해 지정된 위치정보에 따른 상기 열람요청을 상기 수목 정보 서버에 전달하고, 사용자 통신단말의 위치정보 또는 사용자에 의해 지정된 위치정보를 기반으로 지도 상에 상기 아이콘을 표시하여 상기 수목 상태정보를 각각 제공하는 수목 상태정보 검색 제공부;사용자 통신단말의 카메라와 연동하여 현장에 식재된 상기 마커를 인식하고, 인식된 마커 정보를 상기 수목 정보 서버에 전송하며, 상기 수목 정보 서버로부터 상기 마커 정보에 따른 상기 수목 상태정보와 상기 수목 진료기록정보를 수신하여 사용자 통신단말의 카메라를 통한 촬영 영상 내 해당 수목 상에 오버랩 된 증강현실 그래픽으로 표시하되, 수목의 건강 상태에 따라 상이한 색상의 가상 이미지로 이루어진 증강현실 그래픽을 촬영 영상 내 해당 수목 상에 오버랩 하여 표시하는 증강현실 실행부; 및 상기 수목 상태정보와 상기 수목 진료기록정보에 따라 수목병이 발생된 경우 수목병 발생 경로 및 원인정보를 상기 수목 정보 서버에 요청하고, 요청에 대한 응답을 수신하여 상기 아이콘을 통해 표시하는 수목병 정보 요청 표시부를 포함하는 것을 특징으로 하는 수목 정보 제공 시스템., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

111/1150 Row 111: application_number: 1020190177214, combined_string: invention_title: GIS를 이용한 수목 관리 시스템 abstract: 본 발명은 수목 관리 시스템에 관한 것으로, 보다 상세하게는 GIS(Geographic Information System)을 이용하여 실시간으로 수목을 관리할 수 있는 시스템에 관한 것이다. claims: GIS로부터 다수의 환경 인자를 포함하는 지리 정보 데이터를 추출하는 데이터 추출부;광을 조사한 후 수목으로부터 반사되는 광을 취득하여 상기 수목의 3차원 정보를 획득하기 위한 광조사부;수목의 분광 정보를 수집하여 수목의 분광 특성을 측정하기 위한 분광 영상 처리부; 및상기 추출부, 상기 광조사부, 상기 분광 영상 처리부로부터 획득된 데이터를 처리하는 데이터 처리부;를 포함하는, GIS를 이용한 수목 관리 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

112/1150 Row 112: application_number: 1020190176224, combined_string: invention_title: 야생동물 및 유해조류 퇴치기 abstract: 본 발명은 야생동물 및 유해조류 퇴치기에 관한 것으로, 지면에 고정하는 지주부; 상기 지주부 상단에 결합되며, 내부에 레이저모듈부를 구비하는 본체부: 상기 지주부 일측에 결합 고정되는 제어부; 및 상기 본체부 상단부에 결합하여 유입되는 이물질을 차단하는 보호부;를 포함하되, 상기 레이저모듈부는 녹색 또는 적색 레이저 광을 발사하는 제1 및 제2 레이저발생부와, 상기 제1 및 제2 레이저모듈 각각을 상하로 슬라이드 시키는 필렛부, 및 상기 필렛부를 상하로 롤링 및 수평으로 회전시키는 제1 및 제2 모터를 포함하는 것을 특징으로 한다. claims: 지면에 고정하는 지주부;상기 지주부 상단에 결합되며, 내부에 레이저모듈부를 구비하는 본체부:상기 지주부 일측에 결합 고정되는 제어부; 및상기 본체부 상단부에 결합하여 유입되는 이물질을 차단하는 보호부;를 포함하되, 상기 레이저모듈부는,녹색 또는 적색 레이저 광을 발사하는 제1 및 제2 레이저발생부와,상기 제1 및 제2 레이저발생부 각각을 상하로 슬라이드 시키는 필렛부, 및상기 필렛부를 상하로 롤링 및 수평으로 회전시키는 제1 및 제2 모터를 포함하며,상기 필렛부는 중앙에 구동축이 결합되고, 상기 구동축을 중심으로 소정 길이로 획정된 제1 및 제2 홈이 형성되며, 상기 제1 및 제2 홈에 제1 및 2 레이저발생부의 일측이 제1 및 제2 핀으로 각각 결합되며,상기 제1 모터로 밸트를 통해 구동축을 회전시키면서 제2 모터로 롤링캠을 통해 구동축을 상하로 동작시키면, 상기 구동축 중앙에 결합된 필렛부의 제1 및 제2 홈을 따라 제1 및 제2 핀과 결합된 제1 및 2 레이저발생부가 회전하면서 상하로 로링하여 레이저 광이 360도 회전하면서 상하로 방출되는 것을 특징으로 하는 야생동물 및 유해조류 퇴치기., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

113/1150 Row 113: application_number: 1020190173691, combined_string: invention_title: 투-웨이 유인기작 유인등 트랩 abstract: 본 발명은 노린재류의 효과적인 유인 과 포획이 가능하도록 시각 및 후각적인 유인기작을 동시에 사용한 투-웨이 유인기작 유인등 트랩에 관한 것으로, 상단에 행거 고리(110)가 구비된 몸체(100)와; 상기 몸체(100)의 하단부에 설치되고, 하단에 포획통(210)이 분리가능하게 결합되며 내측에 유인제인 집합페로몬이 설치된 깔때기 형태의 유인부(200)와; 상기 유인부(200)의 상측에 설치되는 유인등(300)과; 상기 유인등(300)의 외곽에 설치되는 전기충격부(400)와; 상기 몸체(100)에 설치되어 상기 유인등(300)과 전기충격부(400)의 동작을 제어하는 제어부(500);를 포함하여 이루어져 있다. claims: 상단에 행거 고리(110)가 구비된 몸체(100)와;상기 몸체(100)의 하단부에 설치되고, 하단에 포획통(210)이 분리가능하게 결합되며 내측에 유인제인 집합페로몬이 설치된 깔때기 형태의 유인부(200)와;상기 유인부(200)의 상측에 설치되는 유인등(300)과;상기 유인등(300)의 외곽에 설치되는 전기충격부(400)와;상기 몸체(100)에 설치되어 상기 유인등(300)과 전기충격부(400)의 동작을 제어하는 제어부(500);를 포함하여 이루어진 것을 특징으로 하는 투-웨이 유인기작 유인등 트랩., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

114/1150 Row 114: application_number: 1020190170987, combined_string: invention_title: 재선충 감지와 제거를 위한 스마트 방제 시스템 abstract: 재선충 감지와 제거를 위한 스마트 방제 시스템는 소나무에 존재하는 재선충을 감지하고, 재선충의 매개충인 솔수염 하늘소와 북방수염하늘소를 유인성 조성물에 의해 유인하여 포획한다.본 발명은 재선충의 매개충인 솔수염 하늘소와 북방수염하늘소의 유충 및 성충의 소리 신호를 수집하여 유충과 성충을 유인하기 적합한 유인성 조성물을 발산하여 솔수염 하늘소와 북방수염하늘소를 빠르게 제거할 수 있어 재선충병의 확산을 미연히 예방할 수 있으며, 각 세부 구역의 재선충 탐지와 솔수염 하늘소와 북방수염하늘소의 유충 및 성충의 개체수를 파악하여 조기에 빠른 대처와 확산 방지 및 신속한 방제 업무가 가능한 효과가 있다. claims: 관리하고자 하는 영역에 존재하는 대표 지표 소나무에 부착하여 재선충에 따른 소나무의 고유 진동을 통해 소나무 내부의 수분 및 양분 이동 통로에 대한 밀도 변화를 측정하여 재선충을 감지하는 각 세부 구역에 설치된 하나 이상의 재선충 감시 장치;상기 재선충 감시 장치로부터 재선충 감지 신호를 수신하고, 상기 수신한 재선충 감지 신호를 외부로 전송하는 하나 이상의 센서 통신 중계기; 및상기 각각의 센서 통신 중계기로부터 수신한 재선충 감지 신호에서 식별자를 분석하여 상기 재선충 감시 장치의 위치와, 재선충병이 발생한 것으로 예측되는 세부 구역을 판단하는 데이터 분석 서버를 포함하는 것을 특징으로 하는 스마트 방제 시스템.관리하고자 하는 영역에 존재하는 대표 지표 소나무에 부착되고, 상부가 개방되어 솔수염하늘소나 북방수염하늘소의 성충이나 유충이 유입되는 개방구를 형성한 하우징과 상기 하우징의 하단에 결합되어 상기 성충이나 유충이 상기 하우징을 거쳐 하강하여 포획되는 재선충 수집부를 구비하고, 각 세부 구역에 설치된 하나 이상의 재선충 제거 장치;상기 재선충 제거 장치로부터 포획된 유충 개수와 성충 개수를 포함한 재선충 정보를 수신하고, 상기 수신한 재선충 정보를 외부로 전송하는 하나 이상의 센서 통신 중계기; 및상기 각각의 센서 통신 중계기로부터 수신한 재선충 정보에서 식별자를 분석하여 상기 재선충 제거 장치의 위치를 판단하는 데이터 분석 서버를 포함하는 것을 특징으로 하는 스마트 방제 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

115/1150 Row 115: application_number: 1020190169582, combined_string: invention_title: 온열 가압에 의한 하수관로 내의 모기 방제 시스템 abstract: 본 발명은 온열 가압에 의한 하수관로 내의 모기 방제 시스템에 관한 것으로서, 뜨거운 공기를 일정한 압력으로 공급하는 콤프레서; 상기 콤프레서와 연결되되 약제를 포함하는 약제 탱크; 상기 약제 탱크와 연결되되 실질적으로 하수관로 내에 배치되어 상기 하수관로 내부를 향해 초미세 상태의 약제를 분사하는 약제 분사장치; 및 운전 시 상기 콤프레서에서 발생하는 고온 공기가 상기 약제 탱크로 공급되어 상기 약제 탱크 내의 약제가 가열되게 한 후, 상기 약제 분사장치를 통해 상기 하수관로 내부를 향해 분사되게 하되 분사되는 약제가 소정의 압력에 의하여 초미세 입자의 스팀 스모그(steam smoke) 상태로 분사될 수 있도록 상기 콤프레서, 상기 약제 탱크 및 상기 약제 분사장치의 동작을 컨트롤하는 컨트롤러를 포함한다. claims: 뜨거운 공기를 일정한 압력으로 공급하는 콤프레서;상기 콤프레서와 연결되되 약제를 포함하는 약제 탱크;상기 약제 탱크와 연결되되 실질적으로 하수관로 내에 배치되어 상기 하수관로 내부를 향해 초미세 상태의 약제를 분사하는 약제 분사장치; 및운전 시 상기 콤프레서에서 발생하는 고온 공기가 상기 약제 탱크로 공급되어 상기 약제 탱크 내의 약제가 가열되게 한 후, 상기 약제 분사장치를 통해 상기 하수관로 내부를 향해 분사되게 하되 분사되는 약제가 소정의 압력에 의하여 초미세 입자의 스팀 스모그(steam smoke) 상태로 분사될 수 있도록 상기 콤프레서, 상기 약제 탱크 및 상기 약제 분사장치의 동작을 컨트롤하는 컨트롤러를 포함하고,상기 약제 탱크는,탱크 본체;상기 탱크 본체에 결합하는 가압 파이프;상기 가압 파이프와는 별개로 마련되는 열기 공급 파이프;상기 탱크 본체 내에 배치되되 상기 열기 공급 파이프를 둘러싸게 배치되는 보일러 코일;상기 탱크 본체의 일측에 마련되며, 상기 탱크 본체 내로 약제를 투입하는 약제 투입부;상기 탱크 본체의 상부 일측에 마련되는 안전밸브;상기 탱크 본체의 하부 일측에 마련되며, 상기 탱크 본체 내의 잔류 약제를 배출하는 잔류량 배출밸브;상기 탱크 본체의 일측에 결합하는 컨트롤 박스; 및일단부가 상기 컨트롤 박스에 결합하고 타단부는 상기 약제 분사장치와 연결되며, 상기 약제 탱크 측의 약제 및 공기를 공급하는 약제 및 공기 공급호스를 포함하며,상기 콤프레서에서 상기 약제 탱크로 공기를 전달하되 상기 약제 탱크에 압력을 가하는 제1 공기 전달호스; 및상기 제1 공기 전달호스와는 다른 경로를 통해 상기 콤프레서에서 상기 약제 탱크로 공기를 전달하되 상기 약제 분사장치에 풍량을 제공하는 제2 공기 전달호스를 더 포함하며,상기 제1 공기 전달호스는 상기 약제 탱크의 가압 파이프에 연결되고, 상기 제2 공기 전달호스는 상기 약제 탱크의 열기 공급 파이프에 연결되는 것을 특징으로 하는 온열 가압에 의한 하수관로 내의 모기 방제 시스템.뜨거운 공기를 일정한 압력으로 공급하는 콤프레서;상기 콤프레서와 연결되되 약제를 포함하는 약제 탱크;상기 약제 탱크와 연결되되 실질적으로 하수관로 내에 배치되어 상기 하수관로 내부를 향해 초미세 상태의 약제를 분사하는 약제 분사장치; 및운전 시 상기 콤프레서에서 발생하는 고온 공기가 상기 약제 탱크로 공급되어 상기 약제 탱크 내의 약제가 가열되게 한 후, 상기 약제 분사장치를 통해 상기 하수관로 내부를 향해 분사되게 하되 분사되는 약제가 소정의 압력에 의하여 초미세 입자의 스팀 스모그(steam smoke) 상태로 분사될 수 있도록 상기 콤프레서, 상기 약제 탱크 및 상기 약제 분사장치의 동작을 컨트롤하는 컨트롤러를 포함하고,,상기 약제 분사장치는,내부에 약제와 공기가 공급되는 공간이 형성되는 분사장치 본체;상기 분사장치 본체 내외에 연결되며, 상기 약제 탱크 측에서 공급되는 약제와 공기가 공급되는 약제 및 공기 공급관;상기 분사장치 본체 내에 마련되며, 상기 약제 및 공기 공급관에서 공급되는 공기를 필터링하는 필터;상기 분사장치 본체 내에 마련되며, 상기 약제 및 공기 공급관에서 공급되는 약제와 공기 중 액체 상태와 기체 상태를 분리하는 분리막;상기 분사장치 본체의 하단부에 결합하며, 상기 분사장치 본체 내의 하부 영역으로 모이는 액체 상태의 약제가 모이는 액상 약제 저장부;상기 분사장치 본체의 측벽에 결합하는 복수의 플랜지;상기 플랜지에 결합하며, 약제를 분사하는 분사노즐;양단부가 상기 분사장치 본체 내의 상부 영역에 마련되는 에어 니플과 상기 분사노즐에 연결되며, 상기 분사장치 본체 내의 공기를 상기 분사노즐로 공급하는 공기 공급라인; 및양단부가 상기 액상 약제 저장부과 상기 분사노즐에 연결되며, 상기 액상 약제 저장부 내의 액상 약제를 상기 분사노즐로 공급하는 약재 공급라인을 포함하고,상기 약제 분사장치는,상기 분사장치 본체의 하부에 연결되며, 상기 분사장치 본체를 지지하는 복수의 장치 지지대;상기 분사장치 본체의 상부에 결합하는 고리;상기 고리에 결합하는 현수 와이어; 및상기 분사장치 본체에 결합하며, 상기 분사장치 본체 내의 압력을 감지하는 압력계를 더 포함하는 것을 특징으로 하는 온열 가압에 의한 하수관로 내의 모기 방제 시스템., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

116/1150 Row 116: application_number: 1020190164761, combined_string: invention_title: 갈색날개매미충 포획용 트랩 abstract: 본 발명은 갈색날개매미충과 같은 외래 해층을 효과적으로 포획할 수 있도록 한 포획용 트랩으로, 대체로 원통형으로 이루어지며, 내부에 유인제가 설치되고, 측면과 하면에 외광내협의 형태로 이루어진 복수의 해충 유입구(110)가 형성된 포획통(100)과; 상기 포획통(100) 상부 내측에 분리가능하게 안치되며, 상부에서 유입된 해충을 포획통(100)으로 빠지도록 하고 외부에서 유입된 바람에 회전기류를 일으켜 포획통(100) 내의 유인제가 상기 모든 복수의 해충 유입구(110)를 통해 외부로 배출되도록 하기 위한 깔대기 형태로 이루어진 분리체(200)와; 상기 포획통(100)의 상부에 분리가능하게 결합되며, 외부로부터 바람이 유입되도록 하기 위한 바람유입구(310)가 외곽에 형성된 뚜껑(300);을 포함하여 이루어진다. claims: 내부에 유인제가 설치되고, 측면과 하면에 복수의 해충 유입구(110)가 형성된 포획통(100)과;상기 포획통(100) 상부 내측에 분리가능하게 안치되며, 상부에서 유입된 해충을 포획통(100)으로 빠지도록 하고 외부에서 유입된 바람에 회전기류를 일으켜 포획통(100) 내의 유인제가 상기 모든 복수의 해충 유입구(110)를 통해 외부로 배출되도록 하기 위한 깔대기 형태로 이루어진 분리체(200)와;상기 포획통(100)의 상부에 분리가능하게 결합되며, 외부로부터 바람이 유입되도록 하기 위한 바람유입구(310)가 외곽에 형성된 뚜껑(300);을 포함하여 이루어진 것을 특징으로 하는 갈색날개매미충 포획용 트랩.청구항 5에 있어서.상기 철(凸)형 유입구(110b)에는 유인 길(120)에서 연장되어 45° 각도로 오름길(130)이 만들어진 것을 특징으로 하는 갈색날개매미충 포획용 트랩., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

117/1150 Row 117: application_number: 1020190162669, combined_string: invention_title: 해충 포획장치 abstract: 해충 포획장치를 제공한다. 본 발명은, 유인제가 용해된 일정량의 유인액이 저장된 내부박스를 교체가능하도록 내부수용하는 외부박스 ; 전원인가시 회전구동되는 회전날개를 갖추어 상기 외부박스의 상부면에 관통형성된 배출구를 통하여 상기 유인제를 상향 배출유도시키는 송풍팬 ; 상기 외부박스의 상부면에 올려지는 지지체를 매개로 상기 외부박스와 결합되고, 상기 배출구를 통해 상향 배출되는 유인제를 측방향으로 확산시키는 확산구를 관통형성하는 외부면에 상기 유인제에 의해서 유인되는 곤충을 내부로 진입유도시키는 진입유도로를 구비하는 유도체 ; 상기 진입유도로를 통하여 상기 유도체의 내부공간으로 진입된 곤충이 탈출하는 탈출공을 관통형성하여 상기 유도체의 개방된 상부를 덮도록 결합되는 덮개체 ; 상기 탈출공에 일단이 연통연결되는 연결관체의 타단과 연통연결되어 상기 연결관체를 따라 유도되는 곤충을 포획하여 수거하는 포집체;를 포함한다. claims: 유인제가 용해된 일정량의 유인액이 저장된 내부박스를 교체가능하도록 내부수용하는 외부박스 ;전원인가시 회전구동되는 회전날개를 갖추어 상기 외부박스의 상부면에 관통형성된 배출구를 통하여 상기 유인제를 상향 배출유도시키는 송풍팬 ;상기 외부박스의 상부면에 올려지는 지지체를 매개로 상기 외부박스와 결합되고, 상기 배출구를 통해 상향 배출되는 유인제를 측방향으로 확산시키는 확산구를 관통형성하는 외부면에 상기 유인제에 의해서 유인되는 곤충을 내부로 진입유도시키는 진입유도로를 구비하는 유도체 ;상기 진입유도로를 통하여 상기 유도체의 내부공간으로 진입된 곤충이 탈출하는 탈출공을 관통형성하여 상기 유도체의 개방된 상부를 덮도록 결합되는 덮개체 ;상기 탈출공에 일단이 연통연결되는 연결관체의 타단과 연통연결되어 상기 연결관체를 따라 유도되는 곤충을 포획하여 수거하는 포집체;를 포함하는, 해충 포획장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

118/1150 Row 118: application_number: 1020190156768, combined_string: invention_title: 벤질옥시알코올계 화합물을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충을 방제하는 방법 abstract: 본 발명은 벤질옥시알코올계 화합물을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충을 방제하는 방법에 관한 것이다. claims: 벤질옥시알코올계 화합물을 포함하는 소나무재선충 방제용 조성물.제 1항 내지 제 5항 중 어느 하나의 조성물을 식물 또는 토양에 처리하여 소나무재선충을 방제하는 방법., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

119/1150 Row 119: application_number: 1020190156769, combined_string: invention_title: 나프토퀴논계 화합물을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나 무재선충을 방제하는 방법 abstract: 본 발명은 나프토퀴논을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충을 방제하는 방법에 관한 것이다. claims: 나프토퀴논계 화합물을 포함하는 소나무재선충 방제용 조성물.제 1항 내지 제 5항 중 어느 하나의 조성물을 식물 또는 토양에 처리하여 소나무재선충을 방제하는 방법., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

120/1150 Row 120: application_number: 2020190004549, combined_string: invention_title: 멧돼지 퇴치 장치 abstract: 본 고안은 멧돼지 퇴치 장치에 관한 것으로 일단이 지면에 삽입되는 지지부, 일단이 상기 본체의 타단에서 상측으로 연장되어 형성되는 일직선형의 본체, 상기 본체의 타단에 끼움 결합되며, 내측면에 건전지가 설치된 상단 캡, 일단이 상기 상단 캡에 수직하게 결합되며, 타단이 하측으로 절곡되는 한 쌍의 스프링, 상기 스프링의 타단에 부착되는 눈 형상의 야광패치, 상기 야광패치의 후측에 설치되는 발광수단 및 상기 건전지와 상기 발광수단을 전기적으로 연결하는 전선을 포함한다. claims: 일단이 지면에 삽입되는 지지부;일단이 상기 본체의 타단에서 상측으로 연장되어 형성되는 일직선형의 본체;상기 본체의 타단에 끼움 결합되며, 내측면에 건전지가 설치된 상단 캡;일단이 상기 상단 캡에 수직하게 결합되며, 타단이 하측으로 절곡되는 한 쌍의 스프링; 상기 스프링의 타단에 부착되는 눈 형상의 야광패치;상기 야광패치의 후측에 설치되는 발광수단; 및 상기 건전지와 상기 발광수단을 전기적으로 연결하는 전선;을 포함하는 것을 특징으로 하는 멧돼지 퇴치 장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

121/1150 Row 121: application_number: 1020190141698, combined_string: invention_title: 드론용 연무연막 방제장치 abstract: 본 발명에 따른 드론용 연무연막 방제장치는: 드론의 무게 중심 하부에 착탈 가능하게 결합 되는 본체 프레임; 상기 본체 프레임의 중심부에 착탈 가능하게 결합 되는 본체 케이싱; 상기 본체 케이싱의 내부에 구비되고, 내부에는 물, 방제 약제, 바이오 디젤유가 혼합된 혼합물이 내부에 수용되는 약제 탱크; 상기 본체 케이싱의 내부에서 외부로 노출되게 구비되고, 상기 약제 탱크에 연결되어 상기 약제 탱크의 내부에 수용된 혼합물이 외부로 분사되도록 하는 기화 유닛; 및, 상기 약제 탱크와 상기 기화 유닛의 사이에 구비되어 상기 약제 탱크의 내부에 수용된 혼합물이 상기 기화 유닛으로 이동되어 분사되도록 하는 분사 펌프;를 포함하는 것을 특징으로 한다. 이에 의하여, 드론에 연무연막 방제장치를 간편하게 탈부착하여 손쉽게 적용할 수 있고, 무선 조종을 통해 공중을 비행하는 드론에서 방제 약제를 가열하여 연막 또는 연무 상태로 산림과 해안가 등지에서 농작물이나 나무 등에 방제 약제를 살포하여 방제하도록 함으로써, 연막의 넓은 확산력과 연무에 의해 방제 약제의 침투력을 높이고 광범위한 지역을 손쉽고 용이하게 방제하도록 할 수 있는 드론용 연무연막 방제장치를 제공할 수 있다. claims: 드론의 무게 중심 하부에 착탈 가능하게 결합 되는 본체 프레임;상기 본체 프레임의 중심부에 착탈 가능하게 결합 되는 본체 케이싱;상기 본체 케이싱의 내부에 구비되고, 내부에는 물, 방제 약제, 바이오 디젤유가 혼합된 혼합물이 내부에 수용되는 약제 탱크;상기 본체 케이싱의 내부에서 외부로 노출되게 구비되고, 상기 약제 탱크에 연결되어 상기 약제 탱크의 내부에 수용된 혼합물이 외부로 분사되도록 하는 기화 유닛; 및상기 약제 탱크와 상기 기화 유닛의 사이에 구비되어 상기 약제 탱크의 내부에 수용된 혼합물이 상기 기화 유닛으로 이동되어 분사되도록 하는 분사 펌프;를 포함하는 것을 특징으로 하는 드론용 연무연막 방제장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

122/1150 Row 122: application_number: 1020190140576, combined_string: invention_title: 수목관리용 IoT 밴드 및 이를 이용한 수목관리 시스템 abstract: 본 발명은 수목관리용 IoT 밴드 및 이를 이용한 수목관리 시스템에 관한 것이다. 좀 더 상세하게로는 산림관리 등을 목적으로 수목의 생장상황을 측정 및 관찰하기 위해, 수목의 상태를 식별하여 정보를 취득하거나, 수목병해충에 감염된 것으로 의심되는 수목 등에 대한 식별, 시료채취 등을 함에 있어 스마트폰 등 스마트기기를 이용하여 관리대상 수목에 대한 정보를 자동으로 식별하여 수집할 수 있도록 하는, 수목관리용 IoT 밴드와 이를 이용한 수목관리시스템에 관한 것이다. 이를 위하여 본 발명은, 관리대상 수목의 나무줄기를 두를 수 있고, 스마트기기에 의하여 상기 관리대상 수목에 대한 정보가 인식될 수 있는 띠 모양의 밴드로서, 고유코드와 관리정보를 디지털형식으로 포함하고 있는 제1식별수단, 상기 띠의 길이방향을 따라 일련의 숫자가 연속적으로 표시되는 제1표시수단 및 상기 제1표시수단과 평행하게 일련의 숫자가 연속적으로 표시되는 제2표시수단을 상기 띠 모양의 전면에 포함하는 것을 특징으로 하는 것이 바람직하다. claims: 정보시스템을 이용하여 관리대상 수목에 대한 정보를 관리하는 수목관리 시스템으로서,수목관리용 IoT 밴드;상기 수목관리용 IoT 밴드를 인식할 수 있는 스마트기기;통신망을 통하여 상기 스마트기기와 정보를 주고받는 수목관리 서버; 및 상기 관리대상 수목에 대한 정보를 저장하는 수목정보DB; 를 포함하며,상기 수목관리용 IoT 밴드는, 상기 관리대상 수목의 나무줄기를 두를 수 있고, 상기 스마트기기에 의하여 상기 관리대상 수목에 대한 정보가 인식될 수 있는 띠 모양의 밴드로서,- 고유코드와 관리정보를 디지털형식으로 포함하고 있으며, 큐알코드로 이루어진 제1식별수단,- 상기 띠의 길이방향을 따라 일련의 숫자가 연속적으로 표시되는 제1표시수단 및 - 상기 제1표시수단과 평행하게 일련의 숫자가 연속적으로 표시되는 제2표시수단을 상기 띠 모양의 전면에 포함하고,- 상기 띠를 상기 나무줄기에 둘러싸서 고정시킬 수 있는 고정수단을 상기 띠 모양의 후면에 포함하며,- 상기 제1식별수단은 상기 띠의 시작부분에 위치하며,- 상기 고정수단을 이용하여 상기 띠를 상기 나무줄기에 둘러싸서 고정시켰을 때, 상기 제1식별수단 옆에 상기 나무줄기의 지름 및 둘레가 표시되되, 상기 제1식별수단에 가장 근접하게 위치하는 숫자 중, 상기 제1표시수단의 숫자는 상기 나무줄기의 지름이고, 상기 제2표시수단의 숫자는 상기 나무줄기의 둘레이며,상기 스마트기기는, 상기 관리대상 수목을 둘러싸며 고정되어 있는 상기 수목관리용 IoT 밴드 중 상기 제1식별수단이 포함된 특정부분이 촬영되면, 상기 관리대상 수목 대한 고유코드, 관리정보 및 크기를 한꺼번에 식별하되,- 상기 제1식별수단으로부터 상기 고유코드 및 상기 관리정보를 식별해내고,- 상기 특정부분 중에서 상기 제1식별수단에 가장 근접하게 위치한 숫자를 OCR기능을 통하여 읽어 들인 후, 읽어 들인 숫자 중 상기 제1표시수단의 숫자를 상기 관리대상 수목의 지름으로 인식하고, 상기 제2표시수단의 숫자를 상기 관리대상 수목의 둘레로 인식하며,- 상기 지름 또는 상기 둘레를 포함하는 상기 관리대상 수목의 크기정보를 생성한 후, 상기 고유코드, 상기 관리정보, 상기 크기정보, 상기 수목관리용 IoT 밴드가 촬영된 장소에 대한 GPS좌표, 촬영일시 및 담당자정보를 포함하는 관리대상 수목정보를 생성하여 상기 수목관리 서버에 전송하며,상기 수목관리 서버는,- 상기 관리대상 수목정보를 수신하는 경우, 상기 수목정보DB에 저장하고- 상기 스마트기기 또는 단말기로부터 정보제공 요청 시 상기 수목정보DB에 저장된 정보를 제공하는; 것을 특징으로 하는, 수목관리용 IoT 밴드를 이용한 수목관리 시스템, Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

123/1150 Row 123: application_number: 1020190138634, combined_string: invention_title: 분광라이브러리와 무인기의 다중분광영상을 이용한 산불 피해 등급 분석 장치 및 방법 abstract: 본 발명의 실시예에 따른 산불 피해 등급 분석 장치는, 산불 피해 지역을 촬영한 적어도 하나의 다중분광영상을 입력받는 입력부, 상기 적어도 하나의 다중분광영상을 전처리하는 전처리부, 상기 전처리된 적어도 하나의 다중분광영상을 하나의 영상으로 집성하여 모자이크(Mosaic) 반사율 영상으로 변환하는 모자이크 반사율 영상 생성부 및 상기 모자이크 반사율 영상을 기반으로 산불 피해 등급별 분광반사율과 상기 모자이크 반사율 영상 화소 각각에 대한 분광반사율의 유사도를 산출하여 산불 피해 등급을 검출하는 산불 피해 등급 검출부를 포함할 수 있다. claims: 산불 피해 등급 분석 장치에 있어서,산불 피해 지역을 촬영한 적어도 하나의 다중분광영상을 입력받는 입력부;상기 적어도 하나의 다중분광영상을 전처리하는 전처리부;상기 전처리된 적어도 하나의 다중분광영상을 하나의 영상으로 집성하여 모자이크(Mosaic) 반사율 영상으로 변환하는 모자이크 반사율 영상 생성부; 및상기 모자이크 반사율 영상을 기반으로 산불 피해 등급별 분광반사율과 상기 모자이크 반사율 영상의 화소 각각에 대한 분광반사율의 유사도를 산출하여 산불 피해 등급을 검출하는 산불 피해 등급 검출부를 포함하는 것을 특징으로 하는 산불 피해 등급 분석 장치.산불 피해 등급 분석 방법에 있어서,산불 피해 지역을 촬영한 적어도 하나의 다중분광영상을 입력받는 단계;상기 적어도 하나의 다중분광영상을 기하 보정과 복사 보정을 수행하는 전처리 단계;상기 전처리된 적어도 하나의 다중분광영상을 하나의 영상으로 집성하여 모자이크(Mosaic) 반사율 영상으로 변환하는 단계; 및상기 모자이크 반사율 영상을 기반으로 산불 피해 등급별 분광반사율과 상기 모자이크 반사율 영상의 화소 각각에 대한 분광반사율의 유사도를 산출하여 산불 피해 등급을 검출하는 단계를 포함하는 것을 특징으로 하는 산불 피해 등급 분석 방법.제12항에 있어서,상기 분광반사율 유사도 산출 단계는,n차원(상기 n은 1보다 큰 자연수)에서 상기 선택된 분광반사율 데이터와 상기 모자이크 반사율 영상의 화소 각각에 대한 분광반사율 데이터 사이의 각도인 분광각을 구하고, 상기 분광각을 기반으로 분광반사율 유사도를 산출하는 것을 특징으로 하는 산불 피해 등급 분석 장치.제13항에 있어서,상기 산불 피해 등급 부여 단계는,상기 분광각 중 최소값에 대응되는 산불 피해 등급 분광반사율 데이터를 상기 모자이크 반사율 영상에 부여하는 것을 특징으로 하는 산불 피해 등급 분석 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

124/1150 Row 124: application_number: 1020190136254, combined_string: invention_title: 소나무재선충병 매개하늘소용 유인제와 살충제의 혼합 사용을 통한 소나무재선충병의 방제방법 abstract: 본 발명은 소나무재선충병 매개하늘소용 유인제와 소나무재선충병 매개하늘소용 살충제를 함께 살포하는 것을 특징으로 하는 소나무재선충병의 방제방법에 관한 것이다.본 발명의 방법은 소나무재선충병 매개하늘소를 유인하는 유인제를 소나무 재선충 매개하늘소를 살충하는 살충제와 함께 살포함으로써 소나무재선충병 매개하늘소 유인트랩의 장점인 우수한 유인력에 의해 유인된 매개하늘소를 살충제로 살충함으로써 살충제의 살충효율을 높여 소나무재선충병을 효과적으로 방제할 수 있다. claims: 소나무재선충병 매개하늘소용 유인제와 소나무재선충병 매개하늘소용 살충제를 함께 살포하는 것을 특징으로 하는 소나무재선충병의 방제방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

125/1150 Row 125: application_number: 1020190126958, combined_string: invention_title: 표고버섯균사체를 포함하는 탄저병 방제용 조성물 및 이를 이용하여 탄저병을 방제하는 방법 abstract: 본 발명은 표고버섯균사체를 유효성분으로 포함하는 바이러스병 및 탄저병 방제용 조성물 및 이를 이용하여 원예식물의 바이러스병 및 탄저병을 방제하는 방법에 관한 것으로, 본 발명에 따른 표고버섯 균사체를 포함하는 조성물은 탄저병 및 바이러스병으로 인해 발생되는 농작물의 포자점질물 및 진물 형성을 완전하고 빠르게 억제하고 병의 치료 속도가 월등하게 증진되는 장점이 있다. 또한, 상기 조성물은 실내 및 실외 농작물 모두 효과가 탁월하며, 1회 살포만으로도 충분한 방제 효과를 나타내어 경제적인 장점이 있다. 더욱이, 본 발명의 조성물은 중금속을 함유하지 아니한 의약품으로 조성되므로 농약공해를 피할 수 있으며 효과가 탁월하여 농사의 병충해를 획기적으로 구제할 수 있게 될 것이다. claims: 원예작물의 탄저병 방제용 조성물로서,표고버섯 균사체를 유효성분으로 포함하고,표고버섯 균사체를 10 내지 50 중량% 포함하며,상기 원예작물은 고추, 피망, 사과, 감, 참외, 토마토, 방울토마토, 참깨 및 들깨로 이루어진 군에서 선택된 것임을 특징으로 하는 원예작물의 탄저병 방제용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

126/1150 Row 126: application_number: 1020190124490, combined_string: invention_title: 해충 제거 장치 abstract: 본 발명은 교대로 배치되며 상호 이격된 제1와이어와 제2와이어를 포함하는 포집부; 상기 제1와이어 및 상기 제2와이어 각각에 고전압의 교류전류를 인가하는 고전압 공급부; 및 상기 포집부에 일단이 연결되며 길이 조절이 가능한 손잡이부; 를 포함하고, 상기 고전압 공급부에서 상기 제1와이어 및 제2와이어에 고전압을 인가 시, 상기 제1와이어와 제2와이어 사이에서 아크 방전이 발생하는 해충 제거 장치를 개시한다. claims: 절연성의 플레이트, 상기 플레이트 상부에 이격되어 배치된 절연성의 링부재, 상기 플레이트와 상기 링부재를 연결하며, 교대로 배치되며 상호 이격된 제1와이어 및 제2와이어를 포함하고, 상기 플레이트, 링부재, 제1와이어 및 제2와이어로 형성된 포집 공간을 갖는 포집부;상기 제1와이어 및 상기 제2와이어 각각에 고전압의 교류전류를 인가하는 고전압 공급부;상기 포집부에 일단이 연결되며 길이 조절이 가능한 손잡이부; 및상기 손잡이부의 타단 영역에 배치되며, 상기 고전압 공급부의 동작을 제어하는 제어부; 를 포함하고,상기 고전압 공급부에서 상기 제1와이어 및 제2와이어에 고전압을 인가 시, 상기 제1와이어와 제2와이어 사이에서 아크 방전이 발생하고,상기 제어부는,상기 고전압 공급부의 온/오프를 제어하는 온/오프 스위치 및 상기 제1와이어 및 상기 제2와이어 각각에 인가되는 고전압의 세기를 조절하는 전압 세기 조절 스위치를 포함하고,고전압의 세기를 조절함으로써, 해충 또는 야생동물에 가해지는 충격 정도를 조절하는 것이 가능하고,상기 제1와이어와 제2와이어 사이에 해충이나 말벌집과 같은 도체가 배치되는 경우 도체를 통해 고온의 전기 스파크가 흘러, 상기 포집 공간에 위치하여 고온의 전기 스파크가 흐른 해충이나 말벌집은 전소시키는 해충 제거 장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

127/1150 Row 127: application_number: 1020190124863, combined_string: invention_title: 기온완화를 위한 기온저감활동의 효과분석 시스템 abstract: 본 발명은 기온 상승 현상에 대한 기온완화 대응책으로 실시되는 기온저감활동의 효과를 분석하는 기온저감활동 효과분석 시스템으로서, 복사에너지 정보를 포함하는 조사대상 지역의 위성영상을 획득하는 위성영상 획득부; 상기 복사에너지 정보와 절대온도의 관계를 통해 밝기온도를 산출하고, 상기 밝기온도와 지표피복에 따른 방출률의 관계를 통해 지표면 온도를 산출하는 지표면 온도 산출부; 상기 조사대상 지역의 지형 및 지물적 특징을 반영하고, 상기 조사대상 지역에서 상기 기온저감활동의 시뮬레이션을 위한 모델을 산출하는 기온저감활동 모델링부; 상기 모델에 상기 기온저감활동을 적용하며, 상기 기온저감활동의 성능 실험을 위한 조건을 설정하고 적용되는 프로그램을 설계하는 프로그래밍부; 및 상기 프로그램을 통해 상기 조사대상 지역에서의 상기 기온저감활동의 성능을 분석하는 분석부를 포함하고, 상기 기온저감활동 모델링부는, 종관기상관측시스템(ASOS) 및 자동기상관측시스템(AWS)에서 측정된 기상정보를 획득하고, 상기 지표면 온도와 상기 기상정보를 이용하여 기상자료를 생성하는 기상자료 구축부; 상기 기상자료에 따른 기상 현상에서 발생하는 유체 또는 난류의 흐름을 방정식을 이용하여 분석 및 반영하는 정보처리부; 상기 지표면 온도 및 상기 기상자료를 반영하고, 상기 조사대상 지역의 복수의 구조물을 포함하는 지형지물의 특징을 반영함으로써 실제 환경과 유사한 환경을 구현하는 변환 알고리즘을 수행하는 지형지물 설계부; 상기 조사대상 지역의 수평 및 연직 에너지 평형을 분석하고, 상기 지형지물 및 상기 구조물의 열플럭스, 현열플럭스의 난류플럭스의 특성을 반영하여 상기 조사대상 지역의 표면온도를 산출하는 표면온도 산출부; 및 상기 기상자료 구축부, 상기 정보처리부, 상기 지형지물 설계부 및 상기 표면온도 산출부를 통해 상기 조사대상 지역의 특성이 반영된 모델을 산출하는 결과산출부를 포함하여, 조사대상 지역에서의 기온저감활동의 효과 및 활용성을 판단할 수 있고, 폭염관련 대응정책과 연계하여 효과적인 관리방향을 제시할 수 있는 것을 특징으로 한다. claims: 기온 상승 현상에 대한 기온완화 대응책으로 실시되는 기온저감활동의 효과를 분석하는 기온저감활동 효과분석 시스템으로서,복사에너지 정보를 포함하는 조사대상 지역의 위성영상을 획득하는 위성영상 획득부;상기 복사에너지 정보와 절대온도의 관계를 통해 밝기온도를 산출하고, 상기 밝기온도와 지표피복에 따른 방출률의 관계를 통해 지표면 온도를 산출하는 지표면 온도 산출부; 상기 조사대상 지역의 지형 및 지물적 특징을 반영하고, 상기 조사대상 지역에서 상기 기온저감활동의 시뮬레이션을 위한 모델을 산출하는 기온저감활동 모델링부;상기 모델에 상기 기온저감활동을 적용하며, 상기 기온저감활동의 성능 실험을 위한 조건을 설정하고 적용되는 프로그램을 설계하는 프로그래밍부; 및상기 프로그램을 통해 상기 조사대상 지역에서의 상기 기온저감활동의 성능을 분석하는 분석부를 포함하고,상기 기온저감활동 모델링부는,종관기상관측시스템(ASOS) 및 자동기상관측시스템(AWS)에서 측정된 기상정보를 획득하고, 상기 지표면 온도와 상기 기상정보를 이용하여 기상자료를 생성하는 기상자료 구축부;상기 기상자료에 따른 기상 현상에서 발생하는 유체 또는 난류의 흐름을 방정식을 이용하여 분석 및 반영하는 정보처리부; 상기 지표면 온도 및 상기 기상자료를 반영하고, 상기 조사대상 지역의 복수의 구조물을 포함하는 지형지물의 특징을 반영함으로써 실제 환경과 유사한 환경을 구현하는 변환 알고리즘을 수행하는 지형지물 설계부;상기 조사대상 지역의 수평 및 연직 에너지 평형을 분석하고, 상기 지형지물 및 상기 구조물의 열플럭스, 현열플럭스의 난류플럭스의 특성을 반영하여 상기 조사대상 지역의 표면온도를 산출하는 표면온도 산출부; 및상기 기상자료 구축부, 상기 정보처리부, 상기 지형지물 설계부 및 상기 표면온도 산출부를 통해 상기 조사대상 지역의 특성이 반영된 모델을 산출하는 결과산출부를 포함하는 기온저감활동 효과분석 시스템., Ltext: 임업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

128/1150 Row 128: application_number: 1020190117677, combined_string: invention_title: 말레이즈 트랩, 비행간섭 트랩 및 피트폴 트랩기능을 갖는 곤충류 복합 포충장치 abstract: 본 발명은, 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ; 상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및 상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함한다. claims: 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 중앙연결부는 상기 중앙바, 전,후방 수직바 및 제1,2,3 및 4수평바에 접해지는 한쌍의 상부연결판과, 상기 제1,2,3 및 4수평바에 접해지는 하부연결판을 포함하고, 상기 한쌍의 상부연결판은 상기 중앙바의 외면에 접하도록 연장되는 고정편과, 상기 전,후방 수직바의 외면에 접하도록 연장되는 수직편 및 상기 제1,2,3 및 4수평바의 외면에 접하도록 연장되는 수평편을 포함하는 것을 특징으로 하는 곤충류 복합 포충장치. 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 프레임부는 상기 전,후방 수직바의 수직상태를 유지하는 제1바홀더를 포함하고, 상기 제1바홀더는 상기 전,후방 수직바의 각 하단이 회동가능하게 조립되는 한쌍의 상부연결판의 수직편을 덮도록 상기 전,후방 수직바에 힌지핀을 매개로 일단이 회동가능하게 조립되는 ㄷ단면상의 덮개판을 포함하는 것을 특징으로 하는 곤충류 복합 포충장치. 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 프레임부는 상기 제1,2,3 및 4수평바의 수평상태를 유지하는 제2바홀더를 포함하고 상기 제2바홀더는 상기 제1,2,3 및 4수평바의 각 일단이 회동가능하게 조립되는 한쌍의 상부연결판의 수평편과 하부연결판의 단부를 덮도록 상기 제1,2,3 및 4수평바에 힌지핀을 매개로 일단이 회동가능하게 조립되는 ㄷ단면상의 덮개판을 포함하는 것을 특징으로 하는 곤충류 복합 포충장치. 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 전방 수직바는 상기 포집부가 상단에 고정설치되는 상부수직바와, 상기 중앙연결부와 하단이 연결되는 하부수직바와, 상기 상부수직바의 하단에 구비되는 상부경첩과 회동가능하게 조립되는 하부경첩을 상기 하부수직바의 상단에 구비하는 경첩부 및 상기 하부수직바의 상단을 덮도록 상부수직바의 하단에 힌지핀을 매개로 일단이 회동가능하게 조립되는 ㄷ단면상의 덮개판으로 이루어지는 제4바홀더를 포함하여, 상기 후방 수직바보다 상대적으로 높은 높이를 갖도록 상대적으로 길게 구비되는 것을 특징으로 하는 곤충류 복합 포충장치. 중앙바의 일단과 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제1,2수평바를 구비하고, 상기 중앙바의 타단과 다른 중앙연결부를 매개로 회동가능하게 조립되는 좌우한쌍의 제3,4수평바를 구비하며, 상기 중앙연결부와 하단이 회동가능하게 조립되는 전방 수직바와 나란하도록 상기 제1,2수평바의 각 일단과 측방연결부를 매개로 회동가능하게 조립되는 제1,2수직바를 구비하며, 상기 다른 중앙연결부와 하단이 회동가능하게 조립되는 후방 수직바와 나란하도록 상기 제3,4수평바의 각 일단과 다른 측방연결부를 매개로 회동가능하게 조립되는 제3,4수직바를 구비하는 프레임부 ;상기 전방 수직바 및 제1,2수직바의 각 상단과 상기 후방 수직바 및 제3,4수직바의 각 상단에 연결되어 천정을 형성하는 천정망체를 구비하고, 상기 전방 수직바 및 제1,2수직바로 이루어지는 전방프레임을 덮는 전방망체를 구비하고, 상기 후방 수직바 및 제3,4수직바로 이루어지는 후방프레임을 덮는 후방망체를 구비하며, 상기 전방 수직바와 후방 수직바와의 사이에 구비되는 수직망체를 구비하는 텐트부 ; 및상기 수직망체를 타고 기어오르는 곤충이 진입되는 입구를 갖추어 상기 전방 수직바의 상단에 고정설치되는 포집박스를 구비하고, 상기 포집박스의 내부와 연통연결되는 포집용기를 구비하여 상기 포집박스의 내부로 진입되는 곤충을 상기 포집용기에 낙하시켜 포획하는 포집부 ; 를 포함하고, 상기 중앙바는 상기 전방 수직바와 중앙연결부를 매개로 일단이 조립되는 제1중앙바와, 상기 후방 수직바와 다른 중앙연결부를 매개로 일단이 조립되는 제2중앙바와, 상기 제1,2중앙바와 양단이 힌지핀을 매개로 하여 회동가능하게 조립되는 한쌍의 중앙연결판 및 상기 제1중앙바의 타단을 덮도록 제2중앙바의 타단에 힌지핀을 매개로 회동가능하게 조립되는 ㄷ단면상의 덮개판으로 이루어지는 제5바홀더를 포함하는 것을 특징으로 하는 곤충류 복합 포충장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

129/1150 Row 129: application_number: 1020190111217, combined_string: invention_title: 산불 재해 감시 서버 abstract: 본 발명은 산불 재해 감시 서버에 관한 것이다. 본 발명은, 송수신부(410), 제어부(420) 및 데이터베이스(430)를 포함하며, 제어부(420)는, LoRa 화재 센서 장치 그룹(100g)을 구성하는 각 LoRa 화재 센서 장치(100)의 연기량 정보, 온도 정보, 열온도 정보 중 적어도 하나 이상을 LoRa 수신장치(200)를 통해 IoT 네트워크(300)를 통해 수신하도록 송수신부(410)를 제어하며, 수신시 LoRa 수신장치(200)로부터 각 LoRa 화재 센서 장치(100)의 식별번호도 함께 수신하도록 송수신부(410)를 제어하는 것을 특징으로 하는 정보 수집 모듈(421); 을 포함하는 것을 특징으로 한다.이에 의해, 화재 원점의 위치, 화재의 강도, 화재의 방향 정보를 포함하는 화재 정보를 화재 구호 요원은 모니터링된 화면으로 제공받음으로써, 화재로부터 산림 자원을 보다 효율적으로 보호하도록 하는 효과를 제공한다. claims: 송수신부(410), 제어부(420) 및 데이터베이스(430)를 포함하며, 제어부(420)는, LoRa 화재 센서 장치 그룹(100g)을 구성하는 각 LoRa 화재 센서 장치(100)의 연기량 정보, 온도 정보, 열온도 정보 중 적어도 하나 이상을 LoRa 수신장치(200)를 통해 IoT 네트워크(300)를 통해 수신하도록 송수신부(410)를 제어하며, 수신시 LoRa 수신장치(200)로부터 각 LoRa 화재 센서 장치(100)의 식별번호도 함께 수신하도록 송수신부(410)를 제어하며, 각 LoRa 화재 센서 장치(100)의 식별번호를 메타데이터로 연기량 정보, 온도 정보, 열온도 정보 중 수신된 정보를 데이터베이스(430)에 저장하는 정보 수집 모듈(421);적어도 하나 이상의 LoRa 화재 센서 장치(100)에서 연기량 정보가 수신되는 경우, 연기량 정보가 수신된 LoRa 화재 센서 장치(100)의 식별번호와 매칭되는 위치정보를 데이터베이스(430)에서 추출한 뒤, 추출된 위치정보가 이웃하는지 여부를 분석하고, 이웃하는 LoRa 화재 센서 장치(100)를 추출한 뒤, 이웃하는 적어도 2개 이상의 LoRa 화재 센서 장치(100)의 연기량 정보가 미리 설정된 연기량 오차 범위 이내이고, 이웃하는 2개의 LoRa 화재 센서 장치(100)의 각 연기량 정보가 수신된 시간 정보가 이웃하는 2개의 LoRa 화재 센서 장치(100)의 거리에 비례하는 미리 설정된 시간 오차 범위 이내인 경우 이웃하는 LoRa 화재 센서 장치(100)가 설치된 커버리지 전체를 1차의 화재 확산 지점으로 분석하여 데이터베이스(430)에 저장하고, 이웃하는 LoRa 화재 센서 장치(100) 중 가장 연기량 정보의 정량적 수치가 큰 LoRa 화재 센서 장치(100)가 설치된 커버리지를 화재 원점으로 분석하여 LoRa 화재 센서 장치(100)의 위치정보와 커버리지 정보를 데이터베이스(430)에 LoRa 화재 센서 장치(100)의 식별번호를 메타데이터로 저장하며,다른 LoRa 화재 센서 장치(100)에 의해 연기량 정보가 수신됨이 없는 하나의 LoRa 화재 센서 장치(100)에 의해 연기량 정보가 수신되는 경우 LoRa 화재 센서 장치(100)의 위치정보와 커버리지 정보를 데이터베이스(430)에 화재 원점 주의 대상으로 데이터베이스(430)에 저장하고, 하나의 LoRa 화재 센서 장치(100)를 중심으로 이웃하는 다른 적어도 하나 이상의 LoRa 화재 센서 장치(100)에 의해 연기량 정보가 수신되는지 여부를 모니터링하도록 하기 위해 이웃하는 다른 적어도 하나 이상의 LoRa 화재 센서 장치(100)의 위치 정보와 커버리지 정보를 데이터베이스(430)에서 추출한 뒤, 화재 원점 주의 대상인 LoRa 화재 센서 장치(100)의 위치정보와 커버리지 정보와 함께, 화재 원점 주의 대상인 LoRa 화재 센서 장치(100)의 식별번호를 메타데이터로 데이터베이스(430)에 저장할 뿐만 아니라, IoT 네트워크(300)를 통해 화재 구호 요원 단말(600)로 제공하는 화재 원점 분석 모듈(422);화재 원점 분석 모듈(422)에 의해 화재 원점으로 분석된 LoRa 화재 센서 장치(100)의 식별번호를 메타데이터로 데이터베이스(430)에 저장된 온도 정보, 열온도 정보를 제 1 화재 강도 예비 정보로 추출하고, 화재 원점 분석 모듈(422)에 의해 1차로 분석된 화재 지점으로 분석된 화재 원점으로 분석된 LoRa 화재 센서 장치(100)를 포함하되 화재 원점으로 분석된 LoRa 화재 센서 장치(100)와 이웃하여 임계 범위 내로 연기량이 발생된 것으로 분석된 모든 LoRa 화재 센서 장치(100)가 설치된 커버리지 전체 정보를 제 2 화재 강도 예비 정보로 추출하고, 그리고 각 LoRa 화재 센서 장치(100)에 의해 제공된 온도 정보, 열온도 정보를 데이터베이스(430)에서 제 3 화재 강도 예비 정보로 추출하고, 제 1 화재 강도 예비 정보, 제 2 화재 강도 예비 정보, 제 3 화재 강도 예비 정보를 분석하여 화재 강도를 생성하며, 제 2 화재 강도 예비 정보에 해당하는 커버리지가 미리 설정된 제 1 면적 미만의 산림 면적을 파괴하는 경우 경미한 산불, 미리 설정된 제 1 면적 이상에서 미리 설정된 제 2 면적 미만인 경우보통 산불, 미리 설정된 제 2 면적 이상에서 미리 설정된 제 3 면적 미만인 경우 무서운 산불, 미리 설정된 제 3 면적 이상인 경우 극한의 산불로 분석하여 화상 데이터로 생성하고, 4 단계의 화재 강도인 경미한 산불, 보통 산불, 무서운 산불, 극한의 산불에 대해서 각 커버리지의 변동에 따라 화재 강도를 재설정하며, 4 단계의 화재 강도를 위한 제 2 화재 강도 예비 정보의 단계별 정량적 수치에 제 1 화재 강도 예비 정보의 온도 정보에 대한 제 1 가중치에 따른 정량적 수치와 제 1 화재 강도 예비 정보의 열온도 정보에 대한 제 2 가중치에 따른 정량적 수치, 그리고 제 3 화재 강도 예비 정보를 구성하는 복수의 LoRa 화재 센서 장치(100)에 대한 온도 정보에 대한 화재 원점으로부터의 거리에 비례하는 제 3 가중치에 따른 정량적 수치와 열온도 정보에 대한 화재 원점으로부터의 거리에 비례하는 제 4 가중치에 따른 정량적 수치를 모두 합산한 전체의 정량적 수치를 통해 향후 화재가 현재의 4 단계의 화재 강도에서 얼마나 퍼질 것이라는 화재 예측 정보를 생성하여, 생성된 화재 예측 정보는 데이터베이스(430)에 저장하며, 제 1 내지 제 4 가중치에 대해서는 제 1 가중치에서 제 4 가중치로 갈수록 낮아지도록 설정한 값을 활용하는 화재 강도 분석 모듈(423); 을 포함하는 것을 특징으로 하는 산불 재해 감시 서버., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

130/1150 Row 130: application_number: 1020190110085, combined_string: invention_title: 천적류의 지속 방사형 구조체 abstract: 천적류의 지속 방사형 구조체로서, 내부에 하측으로 개방된 공간부가 형성되며 천적류 방사를 위하여 형성되는 하나 이상의 방사구를 포함하는 용기부; 및 상기 용기부의 하단부에 분리 가능하게 결합되는 뚜껑부;를 포함하며, 상기 공간부에는 먹이 응애가 포함된 배지와 상기 천적류가 수용되는 구성을 마련함으로써, 농업 토양 해충의 천적류를 토양에 장기간 지속 방사시켜 천적류의 작물 정착도를 향상시키고 해충 방제 효율을 향상시키며 천적 활용 비용 및 노동력을 절감할 수 있게 된다. claims: 내부에 하측으로 개방된 공간부가 형성되며 천적류 방사를 위하여 형성되는 하나 이상의 방사구를 포함하는 용기부;상기 용기부의 하단부에 분리 가능하게 결합되는 뚜껑부;상기 공간부의 하측에 수용되는 수분 처리된 왕겨배지;상기 공간부 내에서 상기 왕겨배지 위에 배치되는 왕겨, 먹이 응애 및 상기 천적류의 혼합물; 및상기 공간부 내에서 상기 혼합물 위에 배치되는 상기 먹이 응애의 먹이원;을 포함하는 것을 특징으로 하는, 천적류의 지속 방사형 구조체., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

131/1150 Row 131: application_number: 1020190110176, combined_string: invention_title: 작물 이미지의 병해충 검출 방법 및 장치 abstract: 본 발명은 작물 이미지의 병해충 검출 방법 및 장치에 관한 것으로서, 본 발명의 일 실시 예에 따른 병해충 검출 방법은, 이미지 처리부가 작물 이미지를 수퍼픽셀(superpixel) 단위로 분할하는 단계, 이미지 처리부가 수퍼픽셀의 윤곽(outline)에 외접하는 경계박스를 생성하는 단계, 필터링부가 경계박스에 포함된 수퍼픽셀 이외의 배경영역을 제거하는 단계, 데이터 분석부가 합성곱신경망(Convolutional Neural Network, CNN)을 이용하여 특정 작물의 병해충 종류를 기준으로 배경영역이 제거된 경계박스를 분류하는 단계 및 병해충 진단부가 분류된 경계박스 별로 병해충을 검출하는 단계를 포함할 수 있다. claims: 작물 이미지의 병해충 검출 방법에 있어서,이미지 처리부가 작물 이미지를 수퍼픽셀(superpixel) 단위로 분할하는 단계;상기 이미지 처리부가 상기 수퍼픽셀의 윤곽(outline)에 외접하는 경계박스를 생성하는 단계;필터링부가 상기 경계박스에 포함된 수퍼픽셀 이외의 배경영역을 제거하는 단계;데이터 분석부가 합성곱신경망(Convolutional Neural Network, CNN)을 이용하여 특정 작물의 병해충 종류를 기준으로 상기 배경영역이 제거된 경계박스를 분류하는 단계; 및병해충 진단부가 상기 분류된 경계박스 별로 병해충을 검출하는 단계를 포함하는 것을 특징으로 하는 병해충 검출 방법.작물 이미지의 병해충 검출 장치에 있어서,작물 이미지를 수퍼픽셀(superpixel) 단위로 분할하고, 상기 수퍼픽셀의 윤곽(outline)에 외접하는 경계박스를 생성하는 이미지 처리부;상기 경계박스에 포함된 수퍼픽셀 이외의 배경영역을 제거하는 필터링부;합성곱신경망(Convolutional Neural Network, CNN)을 이용하여 특정 작물의 병해충 종류를 기준으로 상기 배경영역이 제거된 경계박스를 분류하는 데이터 분석부; 및상기 분류된 경계박스 별로 병해충을 검출하는 병해충 진단부를 포함하는 것을 특징으로 하는 병해충 검출 장치.제 1 항 내지 제 4 항 중 어느 한 항의 방법을 구현하기 위한 프로그램이 기록된 컴퓨터로 판독 가능한 기록 매체., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

132/1150 Row 132: application_number: 1020190109783, combined_string: invention_title: 자가 충전식 모기 기피 장치 abstract: 본 발명은 자가 충전식 모기 기피 장치에 관한 것으로, 사용자가 장치를 흔들면 내부 충전부에 의해 베터리가 충전되어 외부 전력의 공급없이 모기 기피 장치의 사용이 가능하다. 또한, 모기와 같은 해충이 싫어하는 고주파를 발생하여, 인체에 무해하면서도 해충 퇴치 효과가 우수하다. claims: 본체;상기 본체부의 일면에 구성된 해충 퇴치를 위한 고주파 발생 스피커; 상기 본체부의 내부에 구성된 베터리; 및상기 본체 내부에 구성된 충전부를 포함하며, 상기 베터리는 본체 내부의 충전부와 전기적으로 연결되며,사용자가 본체를 흔들게 되면, 충전부에 의해 발생된 전압이 유도되어 베터리를 충전할 수 있는자가 충전식 모기 기피 장치.해충 퇴치를 위한 고주파 발생부; 베터리부; 및충전부를 포함하며, 상기 베터리부는 충전부와 전기적으로 연결되며,사용자가 본체부를 흔들게 되면, 충전부에 의해 발생된 전압이 유도되어 베터리부를 충전하여 외부 전력 공급 없이 사용이 가능하고,상기 고주파 발생부에서 발생된 15 내지 25kHz의 소음에 의해 암컷 모기의 접근을 방지할 수 있는자가 충전식 모기 기피 시스템., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

133/1150 Row 133: application_number: 1020190105359, combined_string: invention_title: 드론을 이용한 수목소독 시스템 abstract: 본 발명의 드론을 이용한 수목소독 시스템은 드론에 설치된 방제호스를 지면에 대하여 길이 및 각도를 병행 조절할 수 있어 다양한 지형의 수목지역에 대하여 근접 살포 및 광역 살포가 상황별로 적합하게 적용될 수 있도록 하는데 목적이 있다. 이에 따라, 본 발명의 실시예에 따른 드론을 이용한 수목소독 시스템은, 드론, 드론의 하부에 위치하며 약제통이 구비되고 선단에 노즐이 구비된 복수의 방제호스를 포함하는 방제부, 및 방제부의 하부에 위치하며 방제호스와 결합되어 방제호스의 분사각도를 조절하는 각도조절부를 포함하여 구성되며, 드론은 본체와 복수의 드론암과 복수의 프로펠러 및 드론레그;를 포함하여 구성되고, 방제부는, 본체의 하부에 위치하며 내부에 약제통을 수용하는 회전실린더; 및 상부로는 본체와 결합하고 하부로는 회전실린더와 결합하여 고정시키되 회전축을 포함하여 구성되는 프레임;을 더 포함하되, 방제호스는 약제통에 연결되고 회전실린더의 외측면에 권취된 후 복수의 드론암에 각각 분기되어 연결되어 노즐을 통해 소독약을 분사하는 것을 포함하여 구성되고, 각도조절부는, 프레임에 연결되어 방제부의 하부에 위치하는 것을 포함하고, 헬륨과 같은 공기보다 가벼운 가스를 보관하는 가스탱크; 가스탱크와 연결되어 가스를 압축하며 공급하고 흡입하는 압축기; 압축기와 임의의 방제호스를 연결하며 압축기에 의해 가스가 공급되고 흡입되는 통로를 형성하는 가스공급관; 측면에 인접한 방제호스 간을 연결하며 복수의 방제호스에 모두 연결되고 확장과 수축이 가능한 주름관; 및 방제호스를 압축기 및 주름관과 결합시키는 주름관고정유닛;을 포함하여 구성되는 것을 특징으로 한다. claims: 드론;드론의 하부에 위치하며, 약제통이 구비되고, 선단에 노즐이 구비된 복수의 방제호스를 포함하는 방제부; 및방제부의 하부에 위치하며, 방제호스와 결합되어 방제호스의 분사각도를 조절하는 각도조절부;를 포함하고,드론은, 중앙에 위치하며 회전모터와 분사모터와 제어유닛을 포함하여 구성되는 본체;본체를 중심으로 방사형으로 연결된 복수의 드론암;드론암의 선단에 각각 구비되는 복수의 프로펠러; 및본체의 하단에 지면 착지를 위해 구비되는 드론레그;를 포함하여 구성되고, 방제부는, 본체의 하부에 위치하며 내부에 약제통을 수용하는 회전실린더; 및상부로는 본체와 결합하고 하부로는 회전실린더와 결합하여 고정시키되 회전축을 포함하여 구성되는 프레임;을 더 포함하되, 방제호스는 약제통에 연결되고 회전실린더의 외측면에 권취된 후 복수의 드론암에 각각 분기되어 연결되어 노즐을 통해 소독약을 분사하는 것을 포함하여 구성되고,각도조절부는, 프레임에 연결되어 방제부의 하부에 위치하는 것을 포함하고, 헬륨과 같은 공기보다 가벼운 가스를 보관하는 가스탱크;가스탱크와 연결되어 가스를 압축하며 공급하고 흡입하는 압축기;압축기와 임의의 방제호스를 연결하며 압축기에 의해 가스가 공급되고 흡입되는 통로를 형성하는 가스공급관;측면에 인접한 방제호스 간을 연결하며 복수의 방제호스에 모두 연결되고 확장과 수축이 가능한 주름관; 및방제호스를 압축기 및 주름관과 결합시키는 주름관고정유닛;을 포함하여 구성되되,드론의 본체는, 제어유닛과 분사모터와 회전모터를 포함하며, 제어유닛은 회전모터 및 분사모터의 구동과 프로펠러를 회전시키며 비행 조종을 하는 제어모듈, 통신기능을 구비하며 조종명령을 수신하여 제어부에 연계하는 통신모듈, 동력원을 제공하고 동력 정보를 표시하는 동력모듈,을 포함하여 구성되고, 분사모터는 약제통의 소독약을 방제호스와 노즐을 통해 분사시키며, 회전모터는 회전실린더를 회전시키는 것을 더 포함하며, 방제부는, 노즐이 소정의 무게를 갖도록 구비되어 드론암의 선단으로부터 하부 수직방향으로 향하도록 구성되며, 회전실린더가 프레임에 연결된 채 회전함에 따라 방제호스의 감김과 풀림이 이루어져, 회전실린더를 일방향으로 회전시키면 방제호스가 풀어지면 노즐의 무게로 인해 하부로 길게 늘어뜨려지고, 회전실린더를 타방향으로 회전시키면 방제호스가 감겨지면서 상부로 상승하게 되어 드론암의 외측으로 이격되는 방제호스의 길이를 조절할 수 있는 것을 더 포함하는 것을 특징으로 하는 드론을 이용한 수목소독 시스템., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

134/1150 Row 134: application_number: 1020190100760, combined_string: invention_title: 해충 포획용 유아등 abstract: 본 발명은 본체(100), 램프부(200), 포집부(300) 및 전원부(400)를 포함하여 이루어지되, 상기 본체(100)는 전원부(400)가 설치된 상부체(120)와 포집부(300)가 설치된 하부체(130)로 구성되고, 상기 상,하부체(120,130) 사이에는 320~430nm 파장의 자외선을 방출하는 자외선 램프(210)로 구성된 램프부(200)가 설치되되 초기 점등시 등대효과를 갖도록 깜빡이면서 점차 밝아져 점등되도록 하고, 상기 본체(100)의 외측에는 자외선 램프(210)의 빛이 어느 방향으로도 가려지지 않도록 투명 커버(140)가 씌워지고, 상기 투명 커버(140)의 내측에는 본체(100)의 상,하부체(120,130)를 연결하는 지지기둥(150)이 연결되며, 상기 투명 커버(140)의 사방으로는 자외선 램프(210)로 유인된 해충이 본체(100) 내측으로 진입하도록 개구(142)가 형성되어 사각지대 없이 해충의 유인이 가능하고, 포집부(300)의 흡입팬(340)은 난기류가 발생하지 않도록 수직통로(320)내에 설치되어 해충이 포집망으로 딸려들러가도록 되어 있다. claims: 복수의 지지다리(110)를 갖는 본체(100)와, 상기 본체(100)에 구비되어 해충을 유인하도록 자외선을 방출하는 램프부(200)와, 상기 본체(10)의 하부측에 구비되고 상기 램프부(200)에 의해 유인된 해충을 포집하는 포집부(300)와, 상기 램프부(200)와 포집부(300)에 전원을 공급하는 전원부(400)를 포함하여 이루어지는 해충 포획용 유아등으로; 상기 본체(100)는 전원부(400)가 설치된 상부체(120)와 포집부(300)가 설치된 하부체(130)로 이루어지고, 상기 상,하부체(120,130) 사이에는 램프부(200)가 설치되되 상기 램프부(200)는 320~430nm 파장의 자외선을 방출하는 자외선 램프(210)를 사용하고, 상기 자외선 램프(210)가 설치된 본체(100)의 외측에는 자외선 램프(210)의 빛이 어느 방향으로도 가려지지 않도록 투명 커버(140)가 씌워지고, 상기 투명 커버(140)의 내측에는 본체(100)의 상,하부체(120,130)를 연결하는 지지기둥(150)이 연결되며, 상기 투명 커버(140)의 사방으로는 자외선 램프(210)로 유인된 해충이 본체(100) 내측으로 진입하도록 개구(142)가 형성된 것을 특징으로 하는 해충 포획용 유아등., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

135/1150 Row 135: application_number: 1020190098679, combined_string: invention_title: 측백나무 추출물 또는 이의 분획물을 유효성분으로 함유하는 식물병 방제용 조성물 및 상기 조성물을 사용한 식물병 방제 방법 abstract: 본 발명은 측백나무(Platycladusorientalis) 추출물 또는 이의 분획물을 유효성분으로 함유하는 식물병 방제용 조성물 및 상기 조성물을 사용한 식물병 방제 방법에 관한 것으로, 상기 측백나무 추출물 또는 이의 분획물은 천연물로서 인체에 무해하고, 자연계에서 생분해되어 환경오염을 유발하지 않으면서, 식물병을 방제하는 효과가 있어 식물병 방제용 조성물로 유용하게 사용될 수 있다. claims: 측백나무(Platycladusorientalis) 추출물 및 이의 분획물로 이루어진 군으로부터 선택되는 하나 이상을 유효성분으로 함유하는 식물병 방제용 조성물.제1항의 측백나무(Platycladusorientalis) 추출물 및 이의 분획물로 이루어진 군으로부터 선택되는 하나 이상을 유효성분으로 함유하는 식물병 방제용 조성물을 식물, 이의 종자 또는 이의 서식지에 처리하는 단계를 포함하는 식물병 방제 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

136/1150 Row 136: application_number: 1020190098688, combined_string: invention_title: 측백나무 추출물에서 유래한 다이터페노이드 화합물을 유효성분으로 함유하는 식물병 방제용 조성물 및 상기 조성물을 사용한 식물병 방제 방법 abstract: 본 발명은 측백나무 추출물에서 유래한 다이터페노이드 화합물을 유효성분으로 함유하는 식물병 방제용 조성물 및 상기 조성물을 사용한 식물병 방제 방법에 관한 것으로, 상기 화합물은 천연물로서 인체에 무해하고, 자연계에서 생분해되어 환경오염을 유발하지 않으면서, 식물병을 방제하는 효과가 있어 식물병 방제용 조성물로 유용하게 사용될 수 있다. claims: 하기 화학식 A 및 화학식 B로 표시되는 화합물로 이루어진 군으로부터 선택되는 하나 이상의 화합물, 이의 입체 이성질체 또는 이의 농약학적으로 허용가능한 염을 유효성분으로 함유하는 식물병 방제용 조성물:[화학식 A](상기 화학식 A에서,R1은 CH3 또는 H이고, 및R2는 ,,또는이다); 및[화학식 B](상기 화학식 B에서,은 단일결합 또는 이중결합이고,R1은 OH 또는 H이고,R2는 CH3 또는 CH3OH이고, 및R3는 부재 또는 OH이다).제1항에 있어서,상기 화합물은 측백나무(Platycladusorientalis) 추출물로부터 유래하는 것을 특징으로 하는 식물병 방제용 조성물.제1항에 있어서,상기 식물병은 벼 도열병, 감자 역병, 토마토 역병, 밀 붉은녹병, 호접란 세균성갈색점무늬병, 작물 무름병 및 키위 궤양병으로 구성된 군으로부터 선택되는 하나 이상의 식물병인 것을 특징으로 하는 식물병 방제용 조성물.제1항에 있어서,상기 식물병 방제용 조성물은 마그나포르테 오라이제(Magnaportheoryzae), 파이토프토라 인페스탄스(Phytophthora infestans) 및 푸시니아 트리티시나(Pucciniatriticina)로 구성된 군으로부터 선택되는 하나 이상의 식물병원성 곰팡이의 생장을 억제하는 것을 특징으로 하는 식물병 방제용 조성물.제1항에 있어서,상기 식물병 방제용 조성물은 엑시도보락스 아베네 subsp. 캇트레이에(Acidovorax avenae subsp. cattleyae), 딕케야 크리산테마이(Dickeya chrysanthemi), 펙토박테리움 카로토보룸 subsp. 카로토보룸(Pectobacteriumcarotovorum subsp. carotovorum) 및 슈도모나스 시린게 pv. 액티니디에(Pseudomonassyringae pv. actinidiae)로 구성된 군으로부터 선택되는 하나 이상의 식물병원성 세균의 생장을 억제하는 것을 특징으로 하는 식물병 방제용 조성물.제1항에 있어서,상기 유효성분은 식물병 방제용 조성물에 100 내지 2000 μg/ml 농도로 포함되는 것을 특징으로 하는 식물병 방제용 조성물.제1항의 식물병 방제용 조성물을 식물, 이의 종자 또는 이의 서식지에 처리하는 단계를 포함하는 식물병 방제방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

137/1150 Row 137: application_number: 1020190088935, combined_string: invention_title: 공간빅데이터를 활용한 LULUCF 분야 토지이용변화 매트릭스 처리 장치 및 방법 abstract: 공간빅데이터를 활용한 LULUCF 분야 토지이용변화 매트릭스 처리 장치 및 방법이 제공된다. DB는 지표면 상태를 자연생태적 기준으로 분류한 토지피복지도, 산림 여부를 보여주는 임상도 및 농경지 정보를 보여주는 농경지 전자지도를 저장하고, 메모리는 토지피복지도, 임상도 및 농경지 전자지도를 분석하여 LULUCF 분야에 대한 토지 매트릭스를 구축하는 토지 매트릭스 구축 프로그램을 저장하고, 프로세서는 메모리에 저장된 토지 매트릭스 구축 프로그램을 실행하여 DB에 저장된 토지피복지도, 임상도 및 농경지 전자지도를 중첩하여 GIS 레이어를 생성하고, GIS 레이어를 6개의 토지이용범주 별로 분류한 후, 분류된 6개의 토지이용범주와 사전에 분류된 6개의 토지이용범주를 비교하여 유지된 토지 및 전용된 토지를 추출하고, 추출된 유지된 토지 및 전용된 토지의 면적을 이용하여 토지 매트릭스를 구축할 수 있다. claims: 지표면 상태를 자연생태적 기준으로 분류한 토지피복지도, 산림 여부를 보여주는 임상도 및 농경지 정보를 보여주는 농경지 전자지도를 저장하는 DB;상기 토지피복지도, 임상도 및 농경지 전자지도를 분석하여 토지 이용, 토지이용변화 및 임업(LULUCF: LAND USE, LAND USE CHANGE AND FOREST) 분야에 대한 토지 매트릭스를 구축하는 토지 매트릭스 구축 프로그램을 저장하는 메모리; 및상기 메모리에 저장된 토지 매트릭스 구축 프로그램을 실행하여 상기 DB에 저장된 토지피복지도, 임상도 및 농경지 전자지도를 중첩하여 GIS 레이어를 생성하고, GIS 레이어를 6개의 토지이용범주 별로 분류한 후, 분류된 6개의 토지이용범주와 사전에 분류된 6개의 토지이용범주를 비교하여 유지된 토지 및 전용된 토지를 추출하고, 상기 추출된 유지된 토지 및 전용된 토지의 면적을 이용하여 토지 매트릭스를 구축하는 프로세서;를 포함하고,상기 프로세서는,상기 토지피복지도, 임상도 및 농경지 전자지도를 중첩하여 임시 GIS 레이어를 생성하고, 상기 임시 GIS 레이어에서 토지피복지도, 임상도 및 농경지 전자지도 간의 이격이 발생하는 경우, 경계 조정 작업을 수행하여 이격을 보정하여 상기 GIS 레이어를 생성하는 레이어 생성부;를 포함하며,상기 레이어 생성부는 상기 생성된 임시 GIS 레이어에서 이격이 발생한 지역을 판단하고, 상기 이격이 발생한 지역에 해당하는 지역의 속성을 상기 토지피복지도로부터 추출하여 상기 이격이 발생한 지역의 속성으로 설정하는 경계 조정 작업을 수행하여 이격을 보정하며,상기 6개의 토지이용범주는 산림지, 농경지, 초지, 습지, 정주지 및 기타토지를 포함하는 것을 특징으로 하는 공간빅데이터를 활용한 LULUCF 분야 토지이용변화 매트릭스 처리 장치.(A) 전자장치가, 지표면 상태를 자연생태적 기준으로 분류한 토지피복지도, 산림 여부를 보여주는 임상도 및 농경지 정보를 보여주는 농경지 전자지도를 중첩하여 GIS 레이어를 생성하는 단계;(B) 상기 전자장치가, 상기 GIS 레이어를 6개의 토지이용범주 별로 분류하는 단계;(C) 상기 전자장치가, 상기 (B) 단계에서 분류된 6개의 토지이용범주와 사전에 분류된 6개의 토지이용범주를 비교하여 유지된 토지 및 전용된 토지를 추출하는 단계; 및(D) 상기 (C) 단계에서 추출된 유지된 토지 및 전용된 토지의 면적을 이용하여 토지 매트릭스를 구축하는 단계;를 포함하고,상기 (A) 단계는,(A1) 상기 전자장치가, 토지피복지도, 임상도 및 농경지 전자지도를 중첩하여 임시 GIS 레이어를 생성하는 단계; 및(A2) 상기 전자장치가, 상기 임시 GIS 레이어에서 토지피복지도, 임상도 및 농경지 전자지도 간의 이격이 발생하는 경우, 경계 조정 작업을 수행하여 이격을 보정하여 상기 GIS 레이어를 생성하는 단계;를 포함하고,상기 (A2) 단계는,상기 생성된 임시 GIS 레이어에서 이격이 발생한 지역을 판단하고, 상기 이격이 발생한 지역에 해당하는 지역의 속성을 상기 토지피복지도로부터 추출하여 상기 이격이 발생한 지역의 속성으로 설정하는 경계 조정 작업을 수행하여 이격을 보정하며,상기 6개의 토지이용범주는 산림지, 농경지, 초지, 습지, 정주지 및 기타토지를 포함하는 것을 특징으로 하는 공간빅데이터를 활용한 LULUCF 분야 토지이용변화 매트릭스 처리 방법., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

138/1150 Row 138: application_number: 1020190083977, combined_string: invention_title: 수목장용 식별장치와 이를 이용한 수목장 관리 시스템 abstract: 본 발명은 수목장의 특정 지면 하부로 삽입되어 영역을 인식시키는 식별장치로서, 상기 특정 지면의 식별정보를 저장하고 있는 식별 칩과, 내부에 상기 식별 칩을 수용할 수 있는 공간이 형성된 식별 칩 수용부와, 상기 식별 칩 수용부의 하부에 연결되고, 소정의 길이를 가지고 지면에 삽입될 수 있는 지면 삽입부를 포함한다. claims: 수목장의 특정 지면 하부로 삽입되어 영역을 인식시키는 식별장치에 있어서,상기 특정 지면의 식별정보를 저장하고 있는 식별 칩;내부에 상기 식별 칩을 수용할 수 있는 공간이 형성된 식별 칩 수용부; 및상기 식별 칩 수용부의 하부에 연결되고, 소정의 길이를 가지고 지면에 삽입될 수 있는 지면 삽입부;를 포함하며,상기 식별 칩 수용부에는 흡수성 고분자가 물을 흡수한 상태로 충진되어 열기로부터 식별칩을 보호하는 수목장용 식별장치.수목장에 매장된 고인들을 구분할 수 있도록 분획된 수목장의 특정 지점에 매립되고, 상기 특정 지점에 매장된 고인을 식별할 수 있는 정보가 저장되며, 근거리 무선통신 수단이 구비되어 상기 매장된 고인을 식별할 수 있는 정보를 전송할 수 있는 식별 칩;상기 식별 칩에서 전송된 고인의 식별 정보를 수신하기 위한 근거리 무선통신 수단을 구비하고, 수목장 관리 서버 및 이벤트 컨텐츠 서버와 통신이 가능하며, 상기 수목장 관리 서버 및 이벤트 컨텐츠 서버에서 전송받은 정보를 표시하는 어플리케이션이 설치된 모바일 단말기;수목장 내 추모목의 위치, 상기 추모목에 매칭된 고인의 성명, 가족관계, 매장일시 또는 유족의 방문기록이 저장되고, 상기 모바일 단말기의 요청에 의하여 상기 추모목에 매칭된 고인의 성명, 가족관계, 매장일시 또는 유족의 방문기록에 관한 정보를 모바일 단말기로 전송하는 수목장 관리서버; 및고인의 생전 모습 사진 또는 동영상이 저장되고, 모바일 단말기의 요청에 의하여 상기 고인의 생전 모습 사진 또는 동영상에 관한 정보를 모바일 단말기로 제공하는 이벤트 컨텐츠 서버;를 포함하고,특정 고인의 식별 칩에 매칭되어 할당된 로그인 정보로 상기 모바일 단말기의 어플리케이션에 로그인하고, 근거리 무선통신에 의하여 감지된 상기 특정 고인의 식별 칩과 로그인 정보가 매칭되는 것으로 판단되면, 상기 어플리케이션이 수목장 관리 서버에 저장된 특정 고인의 성명, 가족관계, 매장일시 또는 유족의 방문기록에 관한 정보를 모바일 단말기에 전송할 것을 요청하고, 수목장 관리 서버는 모바일 단말기로 수목장 관리 서버에 저장된 특정 고인의 성명, 가족관계, 매장일시 또는 유족의 방문기록에 관한 정보를 전송하고, 근거리 무선통신에 의하여 감지된 상기 특정 고인의 식별 칩과 로그인 정보가 매칭되는 것으로 판단되면, 상기 어플리케이션에 이벤트 컨텐츠 서버에 저장된 고인의 생전 모습 사진 또는 동영상에 관한 정보를 모바일 단말기에 전송할 것을 요청할 수 있는 요청 버튼이 활성화되고, 상기 활성화된 요청 버튼이 실행되면 이벤트 컨텐츠 서버에 저장된 고인의 생전 모습 사진이 모바일 단말기에 표시되거나 동영상이 재생되며, 상기 수목장 관리 서버 및 이벤트 컨텐츠 서버는 모바일 단말기로 정보를 전송한 기록을 저장하며, 상기 식별 칩의 수용부에는 흡수성 고분자가 물을 흡수한 상태로 충진되어 열기로부터 식별칩을 보호하는 것을 특징으로 하는 수목장 관리 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

139/1150 Row 139: application_number: 1020210053129, combined_string: invention_title: 편백향 확산 기능을 강화한 편백재의 제조방법 abstract: 본 발명에 따른 편백향 확산 기능을 강화한 편백재의 제조방법은,건조 처리된 편백나무를 절단하여 편백 목재를 수득하는, 절단 단계; 상기 편백 목재를 재단하고 세공하여 편백재를 제작하는, 편백재 제작 단계; 제작된 상기 편백재의 표면을 가공 처리하여 거칠기를 부여하는, 표면 가공 처리 단계; 가공 처리된 상기 편백재의 표면을 아크릴계 수지를 포함하는 기능성 코팅제로 코팅 처리하는, 코팅 단계;를 포함하는 것을 특징으로 한다. claims: 편백향 확산 기능을 강화한 편백재의 제조방법으로서,건조 처리된 편백나무를 절단하여 편백 목재를 수득하는, 절단 단계;상기 편백 목재를 재단하고 세공하여 편백재를 제작하는, 편백재 제작 단계;제작된 상기 편백재의 표면을 가공 처리하여 거칠기를 부여하는, 표면 가공 처리 단계;가공 처리된 상기 편백재의 표면에 아크릴계 수지를 포함하는 기능성 코팅제를 분사하는, 코팅 단계;를 포함하되,상기 기능성 코팅제는,우레탄 아크릴레이트 20 내지 50 중량부, 폴리옥시에틸렌 솔비탄 지방산 에스테르(polyoxyethylene sorbitan fatty acid ester) 10 내지 30 중량부, 메틸에틸케톤 20 내지 40 중량부, 폴리에틸렌글라이콜(Polyethylene glycol) 및 2-하이드록시-2-메틸프로피오페논(2-Hydroxy-2-methylpropiophenone)을 포함하는 표면 개질제 1 내지 10 중량부를 포함하고,상기 표면 개질제는,알파-피넨(α-pinene) 30 내지 50 중량부, 세스퀴테르펜 10 내지 30 중량부, 에탄올 20 내지 40 중량부를 혼합하여 제 1 혼합액을 제조하는 단계;상기 제 1 혼합액 60 내지 90 중량부와, 실리카 파우더 15 내지 30 중량부, n-부틸아크릴레이트(n-butyl acrylate) 5 내지 10 중량부를 혼합하여 제 2 혼합액을 제조하는 단계;상기 제 2 혼합액 70 내지 85 중량부와, 폴리에틸렌글라이콜(Polyethylene glycol) 10 내지 25 중량부 및, 1-도데카놀 5 내지 10 중량부를 혼합하여 제 3 혼합액을 제조하는 단계;상기 제 3 혼합액 90 내지 95 중량부와, 2-하이드록시-2-메틸프로피오페논(2-Hydroxy-2-methylpropiophenone) 1 내지 10 중량부 및, 테트라에틸암모늄 하이드록사이드(tetraethylammonium hydroxide) 1 내지 3 중량부를 혼합하여 표면 개질제를 완성하는 단계;를 통해 제조되는 것을 특징으로 하는, 편백재의 제조방법., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

140/1150 Row 140: application_number: 1020210047469, combined_string: invention_title: 동충하초의 대량 증식 종균 획득 방법과 이를 이용한 대량 배양방법 abstract: 동충하초의 대량 증식 종균 획득 방법과 이를 이용한 대량 배양방법이 개시된다. 동충하초의 대량 증식 종균 획득 방법은 a) 다양한 기주로부터 동충하초 종균을 자연 채취하여 소독하고 포자분리 검색단계; b) 검색된 종균을 포자분리를 위한 아가(Aga) 사면 배지에 배양하는 단계; c) 포자 증식을 하기 위한 고체배지, 액상 영양원 제조 단계; d) 용기에 선발 영양원을 충진한 후 고압멸균하고, 멸균 제조된 용기 안의 영양원에 액상 균사를 증식하는 단계; e) 액상 영양원 용기에서 균사를 대량 증식하는 단계; 및 f) 균사 대량 증식 영양원 용기를 멸균한 후 하온시키는 단계로 구성됨을 특징으로 한다.상기와 같이 구성되는 본 발명의 동충하초의 대량 증식 종균 획득 방법과 이를 이용한 대량 배양방법은 야생 동충하초 채취에서부터 얻어진 포자분리 대량 증식 종균 획득 방법과, 이를 이용하여 특정한 방법에 의해 동충하초의 대량 재배 생산, 생산된 동충하초의 가공 및 가공된 동충하초 완성제품을 획득하는 방법을 제공하여, 동충하초를 배양하여 생육재배 수확하는 기간 동안 멸균된 상태로 유지 수확하여 인체에 해로운 오염원을 막을 수 있으며, 인위적인 수분 공급 과정을 생략함으로써 노동력 절감과 청결한 순수 동충하초 상품을 대량으로 수확할 수 있게 하여 종래의 문제점을 해결하면서 인류의 건강에 이바지할 수 있는 발명을 제공한다. claims: a) 소독한 다양한 기주로부터 동충하초 종균을 채취하여 포자를 분리하기 위한 종균을 검색하는 단계; b) 검색된 종균을 포자분리를 위한 아가(Aga) 사면 배지에 배양하는 단계; c) 포자 증식을 하기 위한 고체배지, 액상 영양원 제조 단계; d) 용기에 선발 영양원을 충진한 후 고압멸균하고, 멸균 제조된 용기 안의 영양원에 액상 균사를 증식하는 단계로, 본 단계는 액상 균사를 121℃, 1.5기압에서 20분간 처리하고 25℃로 냉각한 뒤에 여기에 동충하초의 원균을 접종하여 25℃ 배양실에서 7일간 배양하고, 그 다음 여기에 액상 종균을 15 내지 30ml를 접종하여, 25±1℃의 온도로 유지된 배양실에서 7일간 균사 배양하는 단계; e) 상기 단계에 의해 종균 접종 후 균사 배양된 동충하초 배지를 실내온도 17℃ 내지 24℃±1℃의 균상 발아실로 옮겨 45일간 용기 속의 자실체 생육 (수확)시까지 습도조절을 위해 물을 주지 않고 온도와 빛의 조절만으로 생육 용기 내에서 온도 충격에 인하여 결로 수 (水)가 발생하여 자실체 생육에 영양과 수분이 원활하게 공급하여 수확시까지 뚜껑을 열지 않고 증식하는 단계에 의해 동충하초의 대량 증식 종균을 획득한 후, 추가로; f) 균사 대량 증식 영양원용 용기를 멸균한 후 하온시키는 단계;g) 상기 멸균된 용기 안의 영양원에, 잘 소독된 멸균 크린벤치 내에서 우량 포자를 대량 증식한 종균을 접종하는 단계; h) 생육 배지 용기 안에 영양원을 충진하고 고압멸균 후 하온시키는 단계;i) 상기 멸균 하온된 용기 안의 영양 배지에, 잘 소독된 크린벤치 내에서 상기 g) 단계의 우량 대량 증식 종균을 접종한 후에, 동충하초의 대량배양을 위한 배지를 조제하기 위한 단계로서 곡물인 현미, 율무쌀, 보리, 수수, 찹쌀, 백미, 밀, 조 중에서 택일한 1종 이상의 곡물을 발아시키고 임의로 기주 곤충의 4령 유충에서 종영 유충을 깨끗하게 세척 후 채반에 건져 수분을 제거하고 솥에 넣고 100℃에 쪄서 수증기를 날려 버리고 건조기에 넣어 완전히 건조하여 자연에서의 기주곤충 동충하초의 성분을 그대로 유지되게 한 다음, 상기 곡물 20~50g: 상기 기주곤충 분말 5~10g; 게르마늄과 셀레늄 각 0.2g 비율로 혼합한 혼합물을 용기 안에 넣고, 상기 용기에 물 60ml 내지 70ml에 펩타이드를 물 중량 대비 10 내지 50 중량%로 혼합한 혼합물을 생육 병 용기에 충진하는 단계;j) 상기 우량 종균 접종 영양 배지를 22 내지 24℃의 항온실에 옮겨서 45일간 빛과, 온도 관리로 생육하는 단계; 및k) 상기 단계에서 재배된 동충하초를 무균실에서 자실체와 배지를 분리 균일하게 수확하는 단계를 포함함을 특징으로 하는 동충하초의 대량 증식 종균 획득 방법을 이용한 대량 배양방법. 청구항 1 및 2 중 어느 한 항에 따라 제조된 동충하초를 포함하는 것을 특징으로 하는 식품., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

141/1150 Row 141: application_number: 1020200182976, combined_string: invention_title: 비팽창부재가 결합된 편백나무 가습부재가 포함된 천연 가습기 abstract: 본 발명은 목재의 자연증발 원리를 이용하여 주변으로 습기를 공급하고, 목재의 흡습 팽창과 수축에 따른 물투입부의 높이가 변하여 표시부재의 노출 상태를 통해 사용자가 실내의 건조 여부를 알 수 있는 목재가 포함된 천연 가습기에 관한 것이다.또, 본 발명은 별도의 외부 전력을 사용하지 않는 친환경적이며, 세척이 가능하여 위생적으로 사용할 수 있는 이점이 있다. claims: 가습부재(10)가 끼워지고 유입된 물이 수납되는 물받이 베이스(110)와, 물받이 베이스(110) 내부에 상측 방향으로 돌출 형성되어 물투입부(200)를 지지하는 지지부(120)가 포함되는 물받이부(100); 및가습부재(10) 상측에 걸쳐지고, 지지부(120)에 끼움 결합되되, 헤드 베이스(210) 및 조절부재(220)가 포함되어 가습부재(10)로 물을 흘려보내는 물투입부(200);가 포함되고,가습부재(10)는 단면이 다각 형상으로 형성된 목재 일측면에 유입된 물이 흐르기 위해 물가이드홈(11)이 형성되고, 목재 타측면에 접착제(12)를 이용하여 비팽창부재(13)가 부착되어 흡습 또는 증발에 따라 가습부재(10)가 휘는 정도를 일정하게 유지하여 평준화되며,목재는 가습부재(10)가 물받이부(100)와 물투입부(200) 사이에 세워 배치되어 습기나 수분 흡수 시에 팽창하여 휘기 위해 목재의 결이 수평 방향으로 형성된 편백나무가 사용되고,비팽창부재(13)는 금속, 플라스틱 또는 탄소섬유 강화 플라스틱(CFRP) 중 어느 하나가 사용되며,헤드 베이스(210)는 원기둥 또는 원뿔대로 형성되되, 공간부(212)와 제2가이드부(214) 사이에 형성되는 평탄부(211); 헤드 베이스(210) 상부 단면이 사각형상으로 개방 형성되어 물이 수납되는 공간부(212); 평탄부(211) 가장자리에 하부방향으로 관통 형성되어 물이 하부방향으로 배출되기 위한 물통로부(213); 헤드 베이스(210) 하부 단면이 반원형상으로 개방 형성되어 가습부재(10)의 팽창 또는 수축에 따라 물투입부(200)의 높이 변화 시에 가습부재(10)가 이탈되는 것을 방지하는 제2가이드부(214);가 포함되고,조절부재(220)는 내부에서 지지부(120)가 상부 또는 하부 방향으로 움직이기 위해 원형 또는 다각형 관이 헤드 베이스(210) 내측에 관통 형성되며,가습부재(10)가 팽창되면 제2가이드부(214)를 따라 내측 방향으로 휘게 되어 물투입부(200)가 아래 방향으로 내려가게 되면서, 표시부재(20)가 외부로 노출되어 실내에 습기를 공급하고 있음을 표시하고,가습부재(10)가 수축되면 제2가이드부(214)를 따라 외측 방향으로 펴지게 되어 물투입부(200)가 위 방향으로 올라가게 되면서, 표시부재(20)가 물투입부(200) 내부로 배치되어 외부에 노출되지 않음에 따라 실내에 습기가 공급되지 않음을 표시하는 것을 특징으로 하는, 비팽창부재가 결합된 편백나무 가습부재가 포함된 천연 가습기., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

142/1150 Row 142: application_number: 1020200156857, combined_string: invention_title: 수정조성물을 이용한 체리 꽃 수정 방법 및 그와 같이 수정된 체리 열매 abstract: 본 발명은 현저하게 낮은 국내 체리 결실률을 탁월하게 증진시키고, 체리의 품질을 향상시키며, 계획적으로 생산량을 조절할 수 있는 수정조성물을 이용한 체리 꽃 수정 방법에 관한 것으로, 더욱 상세하게는 3 내지 5년생 이상 묘목의 체리 꽃이 50 내지 100% 개화한 시기에 수정조성물을 2 내지 3일 간격으로 1 내지 3회 분무살포하는 방법으로 체리를 수정한다. 상기 수정 조성물은 질소화합물 7 내지 8 중량부, 수용성인산 2 내지 3 중량부, 수용성칼륨 4 내지 5 중량부, 수용성붕소 0.05 내지 0.2 중량부, 식용알콜 10 내지 15 중량부, 물 100 중량부 및 정제화분은 0.5 내지 1.5 중량부를 혼합하여 제조한다. claims: 수정조성물을 이용한 체리 꽃 수정 방법에 있어서, 상기 수정조성물을 이용한 체리 꽃 수정 방법은 3 내지 5년생 묘목의 꽃이 50 내지 100% 개화한 시기에 수정조성물을 2 내지 3일 간격으로 1 내지 3회 분무살포하며, 상기 수정조성물을 개화한 체리나무의 꽃에 분무살포할 때 수정조성물은 470 내지 520배의 물에 희석하여 분무살포하되,상기 수정조성물은 물 100중량부에 질소화합물 7 내지 8 중량부, 수용성인산 2 내지 3 중량부, 수용성칼륨 4 내지 5 중량부, 수용성붕소 0.05 내지 0.2 중량부, 식용알콜 10 내지 15 중량부를 혼합하여 조성물용액을 제조하고, 상기 조성물용액에 정제화분은 0.5 내지 1.5 중량부를 혼합하여 제조하며, 체리 결실율을 향상시키기 위하여 상기 정제화분을 혼합하는 단계에서 정제화분이 조성물용액에 충분히 희석될 수 있도록 20 내지 30분 동안 저속으로 교반시켜 수정조성물을 제조하며,체리 꽃 수정을 촉진하기 위하여 상기 수정조성물의 조성물용액에 미량원소로 수용성 아연(Zn), 수용성 구리(Cu), 수용성 망간(Mn), 수용성 몰리브덴(Mo) 또는 수용성 철(Fe) 성분을 각각 또는 하나 이상의 성분을 0.05 ~1.5중량부 더 혼합하는 것을 특징으로 하는 수정조성물을 이용한 체리 꽃 수정 방법., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

143/1150 Row 143: application_number: 1020200135185, combined_string: invention_title: 조형목을 단기간 내에 대량 제조하는 방법 abstract: 본 발명은 조형목을 단기간 내에 대량 제조하는 방법에 관한 것으로, (S1) 묘목 단계의 수목을 철사를 이용하여 기본 수형을 잡는 단계; (S2) 수목의 한 가지에서 희생지를 선택하고 희생지 외에 나머지 가지들은 전지시키는 단계; (S3) 수목의 성장을 유지시키면서 상기 단계 (S2)에서와 동일하게 수목의 나머지 가지들에서 희생지를 선택하고 희생지 외에 나머지 가지들은 전지시키는 단계; (S4) 수목의 성장을 유지시키면서 수형을 만들어 가면서 원하는 수고까지 생장시키는 단계; (S5) 수목 가지의 서열을 정하여 원하는 굴곡으로 유도하는 단계; 및 (S6) 수목 가지를 원하는 생장으로 높인 후 수목 출하 직전에 희생지를 절지하는 단계를 포함하는 본 발명에 따른 조형목의 제조방법은 조형목을 기본 재목을 가지고 출하하던 기존 방식과 달리 묘목부터 시작하기 때문에 기본 재목 수급이 용이하고 낮은 단가의 묘목으로도 충분히 고품질의 조형목 및 가로수를 공급할 수 있어 많은 시간과 인건비를 절감할 수 있을 뿐만 아니라 대량 생산이 가능하다. 또한, 기존의 고가의 조형목을 가로수로 사용하기에 부적절하였던 점을 보완하여 보다 외관이 화려한 조형목을 낮은 단가로 가로수에 사용할 수 있게 되는 장점을 가진다. 따라서, 현재 수목의 가치를 높게 평가하고 관심이 높아지고 있는 시점에서 시간의 단축과 비용절감으로 인해 대량 생산을 가능하게 하고 고품질의 수목을 상대적으로 낮은 단가에 많이 식재할 수 있다. claims: (S1) 묘목 단계의 수목을 철사를 이용하여 기본 수형을 잡는 단계;(S2) 수목의 한 가지에서 희생지를 선택하고 희생지 외에 나머지 가지들은 전지시키는 단계;(S3) 수목의 성장을 유지시키면서 상기 단계 (S2)에서와 동일하게 수목의 나머지 가지들에서 희생지를 선택하고 희생지 외에 나머지 가지들은 전지시키는 단계;(S4) 수목의 성장을 유지시키면서 수형을 만들어 가면서 원하는 수고까지 생장시키는 단계;(S5) 상술한 단계에서 전지나 절지되지 않고 남아 있는 수목 가지의 서열을 정하여 원하는 굴곡으로 유도하는 단계; 및(S6) 원하는 형태를 갖는 수목 가지를 원하는 만큼 생장시킨 후 수목 출하 직전에 희생지를 절지하는 단계를 포함하여 조형목을 생산하되,상기 조형목은 가로수이며,상기 단계 (S5) 이후 2m 이내의 가지는 절지하여 지하고를 높이는 단계를 추가로 포함하는 것을 특징으로 하는 조형목의 대량 생산방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

144/1150 Row 144: application_number: 1020200128536, combined_string: invention_title: 수목전지 드론 abstract: 본 발명은 수목전지 드론에 관한 것으로서, 수목의 전지작업을 위해 수목 측 원하는 위치 및 높이로 비행하기 위한 드론; 상기 드론에 장착되고, 엔진 구동을 통해 수목의 나뭇가지를 컷팅하기 위한 전지톱;을 포함하며, 상기 드론과 전지톱은 상호간에 연결 조립 또는 분리 가능하도록 구성하고, 전지톱에 대해 드론 착지시 수평 배치 상태를 유지하도록 하고 드론의 상승 비행시 수평 배치 상태에서 수직 배치 상태로 자세 변환함에 의해 수목 전지작업을 위한 컷팅 자세를 유지하도록 구성하는 것을 특징으로 한다.본 발명에 따르면, 비행(飛行) 운전이 가능한 드론에 엔진 구동을 갖는 전지톱을 장착하는 구성을 통해 드론 조정으로 수목 측 원하는 위치 및 높이로 근접시켜 비행 운전함과 더불어 전지톱 측 원형톱날을 회전시킴으로써 수목 측 나뭇가지를 치는 전지작업을 용이하면서도 편리하게 수행할 수 있으며, 그 외 컷팅(Cutting) 작업 등을 수행하는 데에도 유용하게 사용할 수 있는 수목전지 드론을 제공할 수 있다. claims: 수목의 전지작업을 위해 수목 측 원하는 위치 및 높이로 비행하기 위한 드론; 및 상기 드론에 장착되고, 엔진 구동을 통해 수목의 나뭇가지를 컷팅하기 위한 전지톱; 을 포함하는 수목전지 드론으로서, 상기 드론과 전지톱은, 브라켓을 이용하여 상호간에 연결 조립 또는 분리 가능하도록 구성되되, 상기 드론의 하측단면에 고정 결합되는 수평판 구조체의 제1브래킷;상기 제1브래킷의 하면에 고정 결합되는 디귿자형 구조체의 제2브래킷;상기 제2브래킷에 지지 결합되어 수직 배치되는 파이프형 구조체로서, 하단부 일측에서 연장 돌출되고 제1잠금고정공이 형성된 제1잠금고정부를 갖는 드론연결프레임;상기 전지톱의 상단부 일측에 위치하여 고정 결합 및 수평 배치되고, 상면에서 상측방향으로 연장 돌출되어 간격 배치 및 제2잠금고정공이 형성된 한쌍의 제2잠금고정부를 갖는 받침부재;상기 받침부재의 상면에 고정 결합되어 수직 배치되는 전지톱연결프레임;상기 받침부재의 상면에 고정 배치되고, 정역회전에 따라 전후진하는 잠금샤프트를 갖는 스텝모터; 를 포함하며,상기 드론연결프레임을 전지톱연결프레임에 삽입 배치하되, 제1잠금고정부를 한쌍의 제2잠금고정부의 사이에 삽입 끼움한 상태에서 스텝모터를 정회전 구동하여 잠금샤프트를 전진시킴에 의해 제1잠금고정공과 제2잠금고정공을 관통시키면 잠금되어 드론과 전지톱이 연결 조립되고, 상기 스텝모터를 역회전 구동하여 잠금샤프트를 후진시키면 드론과 전지톱이 분리되는 것을 특징으로 하는 수목전지 드론., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

145/1150 Row 145: application_number: 1020200125759, combined_string: invention_title: 컨테이너를 이용한 조경수 생산방법 abstract: 본 발명은 컨테이너를 이용한 조경수 생산방법에 관한 것으로서, 더욱 상세하게는 수목의 강한 뿌리시스템을 창출하는 특수 컨테이너를 모든 단계에서 사용함으로써, 보다 뿌리 발달이 향상되어 현장의 토양에 잘 적응하기 때문에 활착률과 생장률이 향상되고, 생산방법에 적용된 컨테이너는 수목의 이식 성공률을 높이기 위하여 단순한 용기가 아닌 세근발달을 촉진시키는 특수 컨테이너이고, 각각의 단계는 종전의 세근발달을 기반으로 다음 단계를 준비하며, 세근발달은 보다 큰 용적의 컨테이너에서 확장되어 수분ㆍ양분의 흡수, 생장률, 생존률 등의 효율성을 증대시키는 특징이 있다. claims: 조경수를 생산하는 방법에 있어서,(1) 묘목을 4L 용적용 제 1 컨테이너에 이식하여 생장시키는 단계;(2) 상기 (1) 단계에서 생장시킨 수목을 12L 용적용 제 2 컨테이너에 이식하여 중간 수목으로 생장시키는 단계;(3) 상기 (2) 단계에서 생장시킨 중간 수목을 50L 용적용 제 3 컨테이너에 이식하여 소형 수목을 생산하는 단계;를 포함하고,상기 4L 용적용 제 1 컨테이너와 12L 용적용 제 2 컨테이너는 지상재배 방식으로써 컨테이너와 컨테이너의 간격을 두지 않는 조밀배치방법과 수목의 수관을 고려하여 소정 간격을 이격하여 배치하는 이격배치방법을 사용하는데, 상기 조밀배치방법 또는 이격배치방법에 의해 배치된 다수개의 컨테이너를 전도방지용 연결 고정구를 통해 고정하고,상기 전도방지용 연결 고정구는 하측에 컨테이너와 컨테이너 또는 컨테이너와 와이어를 상호 연결시켜 고정시키는 2개의 고정홈이 형성되고, 상측에는 수평으로 파이프가 결합되도록 결합홈이 형성되고,상기 2개의 고정홈 사이에는 컨테이너 또는 와이어가 고정홈에서 이탈되지 않도록 압착돌기가 고정홈 내측으로 돌출 형성되고, 상기 압착돌기는 끝단부가 상측으로 라운드지게 형성되어 컨테이너 또는 와이어가 고정홈에 용이하게 삽입시키는 동시에 삽입 후에는 쉽게 이탈되지 않는 것을 특징으로 하는 컨테이너를 이용한 조경수 생산방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

146/1150 Row 146: application_number: 1020200117100, combined_string: invention_title: 산삼배양근의 제조방법 abstract: 본 발명은 본 발명은 산삼배양근의 제조방법에 관한 것이며, 천연 산삼을 절단하여 천연산삼 조각을 준비하는 단계(S100); 상기 천연산삼 조각을 산삼배양용 배지에 접종하고 1차 배양하여 산삼 세포괴로 성장시키는 단계(S200); 상기 산삼 세포괴를 더욱 성장시켜 부정근을 유도하는 단계(S300); 상기 부정근 중에서 형질이 우수한 뿌리를 선별하고 이를 2차 배양하여 산삼세근을 얻는 단계(S400); 상기 산삼세근을 생물반응기에 넣고 3차 배양시키는 단계(S500); 및 생물반응기에서 자란 산삼세근을 대형 배양탱크에 넣고 4차 배양하는 단계(S600);를 포함하며, 이는 제조되는 산삼배양근에 함유되는 아연 (Zn), 칼슘 (Ca) 및 황(S)의 비율을 효과적으로 향상시킬 수 있음과 동시에 높은 수율로 천연산삼과 성분이 동일한 배양산삼을 수득할 수 있는 장점을 갖는다. claims: 천연 산삼을 절단하여 천연산삼 조각을 준비하는 단계(S100);상기 천연산삼 조각을 산삼배양용 배지에 접종하고 1차 배양하여 산삼 세포괴로 성장시키는 단계(S200);상기 산삼 세포괴를 더욱 성장시켜 부정근을 유도하는 단계(S300);상기 부정근 중에서 형질이 우수한 뿌리를 선별하고 이를 2차 배양하여 산삼세근을 얻는 단계(S400);상기 산삼세근을 생물반응기에 넣고 3차 배양시키는 단계(S500); 및생물반응기에서 자란 산삼세근을 대형 배양탱크에 넣고 4차 배양하는 단계(S600);를 포함하며,상기 1차 배양 내지 4차 배양은 각각질산암모늄 (NH4NO3, ammonium nitrate), 질산칼슘사수화물 ([CaNO3]2·4H20, calcium nitrate tetrahydrate), 제1인산칼륨 (KH2PO4, potassium phosphate monobasic), 황산칼륨 (K2SO4, potassium sulfate), 황산마그네슘7수화물 (MgSO4·7H2O, magnesium sulfate heptahydrate), 무수염화칼슘 (CaCl2, calcium chloride anhydrous), 붕산 (H3BO3, boric acid), 황산아연7수화물 (ZnSO4·7H2O, zinc sulfate heptahydrate), 몰리브덴산나트륨2수화물 (Na2Mo04·2H20, sodium molybdate dihydrate), 황산구리오수염 (CuS04·5H2O, copper(I) sulfate pentahydrate), 나트륨에데트산제2철 (EDTA ferric sodium salt trihydrate), 3-인돌부틸산 (IBA(C12H13NO2), 3-indolebutyric acid), 수산화칼륨 (KOH), 이노시톨 (inositol), 피리독신염산염 (C8H11NO3HCl, pyridoxine hydrochloride), 티아민염산염 (thiamine hydrochloride), 아연(Zn) 및 칼슘(Ca)을 포함하는 산삼배양용 액상 배지를 이용하여 수행되는 것을 특징으로 하는 산삼배양근 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

147/1150 Row 147: application_number: 1020200115667, combined_string: invention_title: 편백 오일의 제조방법 및 이를 함유하는 항균 조성물 abstract: 본 발명은 편백 오일의 제조방법, 이를 함유하는 항균 조성물, 화장료 조성물 및 의약외품 조성물에 관한 것으로, 상세하게는 편백나무 심재를 원료로 하며 분쇄 단계; 전처리 단계; 추출 단계; 수증기 배출 단계; 냉각 단계; 분리 단계; 및 숙성단계를 포함하여 수행됨으로써 항균 효과가 우수한 고품질의 편백나무 오일을 높은 생산성으로 생산할 수 있는, 편백 오일의 제조방법 및 그를 이용하여 제조되는 항균 조성물, 화장료 조성물 및 의약외품 조성물에 관한 것이다. claims: 벌목후 24시간이 지나지 않은 수령 30년 이상 편백나무 유래 심재를 분쇄하여 분쇄물을 얻는 단계;상기 분쇄물을 용기에 투입하는 단계;상기 용기에 100 내지 200℃ 온도의 건증기를 10 내지 30분 공급하는 전처리 단계;상기 용기에 150 내지 230℃ 온도의 증기를 1 내지 2kgf/cm2의 압력조건으로 1 내지 3시간 동안 공급하는 추출 단계;상기 용기 내부온도가 100 내지 120℃이고 내부압력이 1 내지 1.5kgf/cm2이 되면 수증기를 배출시키는 수증기 배출 단계;상기 용기에서 배출되는 수증기를 2차에 걸쳐 냉각하여 응축시키는 냉각 단계;상기 냉각 단계에서 얻어지는 응축수에서 편백수 및 편백오일을 분리하는 분리 단계; 및분리된 편백오일을 10 내지 15 ℃ 온도에서 7 내지 90일간 숙성시키는 숙성 단계;를 포함하되,상기 분리 단계는 편백수와 편백오일의 경계면에서 먼 하층의 편백수 및 상층의 편백오일을 먼저 분리하는 제 1단계; 상기 경계면 부근의 편백수 및 편백오일을 탈크에 흘려보내 오일 성분을 탈크에 고정시키는 제 2단계; 상기 탈크에 에테르를 처리하여 오일 성분을 용해시키는 제 3단계; 및 상기 에테르를 증발시켜 오일 성분만을 남기는 제 4단계를 포함하고,상기 숙성 단계에서 숙성된 편백오일은 숙성된 편백오일 총 100중량%에 대하여 알파피넨(α-pinene) 10 내지 15중량% 및 보닐아세테이트(bornyl acetate) 5 내지 15중량%으로 함유하는, 편백오일 제조방법.청구항 1 또는 4의 제조방법으로 제조되는 편백오일을 유효성분으로 함유하는, 항균용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

148/1150 Row 148: application_number: 1020200097400, combined_string: invention_title: 생태복원용 식생매트 및 이를 이용한 시공방법 abstract: 본 발명은 본 발명은 하천 및 산림의 훼손지의 식생기반을 형성하기 위한 식생매트에 관한 것으로, 복원 대상지별 특성에 따라 식생매트의 구조 및 식생배합을 구분하여 적용할 수 있도록 해, 다양한 식물을 사용하여 복원사업의 용도 및 목표에 따라 조기피복 및 장기적인 용도의 생태복원을 구현할 수 있도록 한다. claims: 복원사업의 대상이 되는 적용대상지를 하천형(ERS), 도로형(ERR), 산지형(ERF) 중 어느 하나로 구분하여, 복원목표와 식생완성 목표시기 및 식생배합비율을 결정하는 1단계; 상기 1단계 이후, 상기 적용대상지의 현장여건을 고려하여, 식생매트의 설계 구성을 종자부착형 또는 완성형 중 어느 하나로 결정하는 2단계; 상기 1단계 및 2단계에 따른 결정조건에 부합하는 식생매트를 다층구조로 적층하여 제작하는 3단계; 상기 적용대상지의 하부에 유기물재료로 형성되는 근계 유도형 식생블럭을 매립하고, 상기 식생블럭을 매립한 대상지의 상부 토양표면에 식생매트를 배치하는 4단계;를 포함하며,상기 1단계는, 상기 하천형(ERS)은 복원목표를 조기녹화로 하고, 식생배합 비율은 초본 : 관목 : 교목 = 100 : 0 : 0으로 배합하고, 상기 도로형(ERR)은 복원목표를 중기녹화로 하고, 초본 : 관목 : 교목 = 50~70 : 30~50 : 0으로 배합하며,상기 산지형(ERF)은 복원목표를 장기녹화로 하고, 초본 : 관목 : 교목 = 10~30 : 40~60 : 20~40으로 배합하는 단계인, 생태복원용 식생매트를 이용한 시공방법.청구항 1의 시공방법에 적용되는, 생태복원용 식생매트., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

149/1150 Row 149: application_number: 1020200093409, combined_string: invention_title: 인삼밭 차양막 지주용 목재 제조방법, 이 제조방법에 의해 제조된 지주용 목재 및, 이 지주용 목재를 이용한 인삼밭 차양막 지주 abstract: 인삼밭 차양막 지주용 목재 제조방법, 이 제조방법에 의해 제조된 지주용 목재 및, 이 지주용 목재를 이용한 인삼밭 차양막 지주가 개시된다. 개시된 인삼밭 차양막 지주용 목재 제조방법은, a) 국내산 낙엽송으로 이루어진 각목을 준비하는 단계; b) 상기 각목의 표면에 수성 열경화접착제를 도포하는 단계; c) 상기 각목의 표면에 도포된 상기 수성 열경화접착제를 15℃~25℃의 상온에서 소정시간동안 건조시켜 상기 각목 표면에 접착제코팅층이 형성되도록 하는 단계; d) 상기 접착제코팅층이 형성된 각목의 표면에 열수축 필름을 감싸 랩핑하는 단계; e) 상기 열수축필름이 랩핑된 각목을 가열하여 상기 열수축필름이 수축되면서 상기 접착제코팅층에 밀착고정되는 단계;를 포함하는 것을 특징으로 한다. claims: a) 국내산 낙엽송으로 이루어진 각목을 준비하는 단계;b) 상기 각목의 표면에 수성 열경화접착제를 도포하는 단계;c) 상기 각목의 표면에 도포된 상기 수성 열경화접착제를 15℃~25℃의 상온에서 소정시간동안 건조시켜 상기 각목 표면에 접착제코팅층이 형성되도록 하는 단계;d) 상기 접착제코팅층이 형성된 각목의 표면에 열수축 필름을 감싸 랩핑하는 단계;e) 상기 열수축필름이 랩핑된 각목을 가열하여 상기 열수축필름이 수축되면서 상기 접착제코팅층에 밀착고정되는 단계;를 포함하며, 상기 e) 단계에서, 상기 열수축필름이 랩핑된 각목을 100℃ 이상의 스팀으로 가열하여 상기 열수축필름이 수축되도록 구성되는 것을 특징으로 하는 인삼밭 차양막 지주용 목재 제조방법. 제 1 항 또는 제 2 항에 기재된 인삼밭 차양막 지주용 목재 제조방법에 의해 제조된 인삼밭 차양막 지주용 목재로서, 국내산 낙엽송으로 이루어진 각목;상기 각목의 표면에 수성 열경화 접착제가 도포된 후 건조되어 형성된 상기 접착제코팅층;상기 접착제코팅층의 외면에 랩핑된 후 가열에 의해 수축된 열수축필름;을 포함하는 것을 특징으로 하는 인삼밭 차양막 지주용 목재.인삼밭 지면에 전후 좌우 방향을 따라 소정간격으로 수직하게 설치되는 지주대;전후로 이웃하는 두 지주대의 상단부를 경사진 형태로 연결하는 경사가로대;좌우 이웃하는 두 지주대를 서로 수평되게 연결하여 상기 좌우 이웃하는 지주대들이 쓰러지지 않고 안정적으로 세워진 상태를 유지하게 하는 수평연결지지대를 포함하며, 상기 지주대, 상기 경사가로대, 상기 수평연결지지대 모두는, a) 국내산 낙엽송으로 이루어진 각목을 준비하는 단계;b) 상기 각목의 표면에 수성 열경화접착제를 도포하는 단계;c) 상기 각목의 표면에 도포된 상기 수성 열경화접착제를 15℃~25℃의 상온에서 소정시간동안 건조시켜 상기 각목 표면에 접착제코팅층이 형성되도록 하는 단계;d) 상기 접착제코팅층이 형성된 각목의 표면에 열수축 필름을 감싸 랩핑하는 단계;e) 상기 열수축필름이 랩핑된 각목을 가열하여 상기 열수축필름이 수축되면서 상기 접착제코팅층에 밀착고정되는 단계;를 포함하는 인삼밭 차양막 지주용 목재 제조방법에 의해 제조된 인삼밭 차양막 지주용 목재로 이루어지는 것이며, 상기 e) 단계에서, 상기 열수축필름이 랩핑된 각목을 100℃ 이상의 스팀으로 가열하여 상기 열수축필름이 수축되도록 구성되는 것을 특징으로 하는 인삼밭 차양막 지주., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

150/1150 Row 150: application_number: 1020200089274, combined_string: invention_title: 대나무를 이용한 임산물 및 수목 생장촉진 구조를 갖는 유공관, 이의 제조 방법 및 이의 시공 방법 abstract: 본 발명은 임산물 및 수목 식재시 뿌리 주위를 따라 설치되어 물과 영양분을 공급함으로써 환경보호와 함께 통기성 및 관수성을 향상시킬 수 있도록 구현한 대나무를 이용한 임산물 및 수목 생장촉진 구조를 갖는 유공관, 이의 제조 방법 및 이의 시공 방법에 관한 것으로, 대나무를 원형 파이프 형태로 가공하여 제작되며, 둘레를 따라 다수 개의 관통홀이 일정한 간격으로 열을 지어 타공 형성되며, 식재된 임산물 및 수목의 생장촉진을 위해 토양에 삽입된 뒤 내부 공간으로 공급되는 물을 상기 관통홀을 통해 토양으로 배출하는 기둥부; 상기 기둥부의 외주면을 덮는 커버부; 및 식재된 임산물 및 수목의 생장촉진을 위한 영양제 성분이 내측에 수용되며, 상기 커버부의 외측에 설치되는 영양 공급부;을 포함한다. claims: 대나무를 원형 파이프 형태로 가공하여 제작되며, 물이 토양으로 배출되게 상기 대나무의 둘레를 따라 다수 개의 관통홀이 일정한 간격으로 열을 지어 타공 형성되고, 상부는 지상방향으로 일정 높이로 돌출되게 형성하며 하부는 경사면으로 절개된 기둥부;상기 기둥부는 외측 표면을 강화시키고 내구성을 향상시킬 수 있도록 150℃ 내지 200℃의 온도로 1차 열처리된 후, 표면강화를 위한 광택작업이 70℃ 내지 90℃로 2차로 이루어지며 천연 방부, 방청 및 방수 기능이 있는 도료를 이용하여 3차 작업이 이루어지고,상기 기둥부의 상부 입구를 덮는 덮개부;상기 덮개부는 덮개 본체를 개폐하는 대나무 또는 목재재질로 된 보강판, 상기 보강판에 형성된 다수 개의 배출홀, 상기 덮개 본체와 상기 보강판을 체결하는 체결수단을 포함하며, 상기 기둥부의 외주면을 하부 방향으로 덮는 생분해성 부직포인 PLA(Poly Lactic Acid), 코코넛 섬유, 화장지, 마 또는 광목 무명천 중 어느 하나의 재질로 이루어진 커버부;식재된 임산물 및 수목의 생장촉진을 위한 영양제 성분이 내측에 수용되며 상기 커버부의 외측에 설치하고, 영양제 성분이 분리되어 수용되기 위한 독립된 공간을 열을 지어 구비하는 줄(wire) 형태로 형성된 영양 공급부; 및 상기 기둥부 내부에 전등을 더 포함하는, 대나무를 이용한 임산물 및 수목 생장촉진 구조를 갖는 유공관., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

151/1150 Row 151: application_number: 1020200083993, combined_string: invention_title: 스마트 산림재해대응 상황관제차량 abstract: 본 발명은 스마트 산림재해대응 상황관제차량에 관한 것으로, 드론을 현장까지 운반하면서 충전을 할 수도 있고, 산불, 산사대, 산림병해충 등을 비롯한 산림의 각종 재해상황을 모니터링할 수 있는 스마트 산림재해대응 상황관제차량에 관한 것으로, 더욱 상세히는 드론과 연계한 산불지휘차량을 현장에서 운용하고, 드론으로 촬영된 산불진화영상 등을 실시간으로 확인하면서 소화작전이나 언론 브리핑 등을 실시할 수 있도록 한 것인바, 상부에 드론이 적재되고 레일을 따라 차량의 후방도어 외측으로 슬라이드방식으로 인출가능하게 설치되는 드론 적재대(100)와; 상기 적재대 하부의 하부 수납공간(200)과; 상기 적재대 좌측 또는 우측 공간에 형성되는 모니터 수납공간(300)과; 상기 모니터 수납공간에 수납되며 레일을 따라 모니터 수납공간의 외부로 인출되는 모니터(400)와; 차량의 2열 위치에 설치되는 PC용 데스크(500)와; 상기 PC용 데스크에 설치되는 워크스테이션(600)과; 상기 모니터(400)와 워크스테이션(600)의 구동 및 드론의 충전을 위한 전원부(700);를 포함하여 이루어진다. claims: 상부에 드론이 적재되고 레일을 따라 차량의 후방도어 외측으로 슬라이드방식으로 인출가능하게 설치되는 드론 적재대(100)와; 상기 적재대 하부의 하부 수납공간(200)과; 상기 드론 적재대 좌측 또는 우측 공간에 형성되는 모니터 수납공간(300)과; 상기 모니터 수납공간에 수납되며 레일을 따라 모니터 수납공간의 외부로 인출되는 모니터(400)와; 차량의 2열 위치에 설치되는 PC용 데스크(500)와; 상기 PC용 데스크에 설치되는 워크스테이션(600)과; 상기 모니터(400)와 워크스테이션(600)의 구동 및 드론의 충전을 위한 전원부(700);를 포함하여 이루어지며,상기 모니터 수납공간(300)에는 내부에 대형 모니터400)가 수납되고 외부로 인출하여 현장에서 상황브리핑이나 교육에 사용되며, 상기 모니터 수납공간(300)은 차량의 내부공간 일측에 형성되고, 측벽에 부착된 2중 레일(R)에 의해 중량이 무거운 모니터(400)를 안정적으로 지지하면서도 외부로 인출이 가능하고, 상기 모니터(400)는 외부로 인출된 상태에서 후방의 힌지(H)에 의해 수평회동되어 차량의 후방을 향하는 것을 특징으로 하는 스마트 산림재해대응 상황관제차량., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

152/1150 Row 152: application_number: 1020200074403, combined_string: invention_title: 광질 조절에 의한 뿌리 생육이 증진된 차나무 기내배양묘의 배양방법 abstract: 본 발명은 광질 조절에 의한 뿌리 생육이 증진된 차나무 기내배양묘의 배양방법에 관한 것으로, 기내(in vitro)에서, 차나무 유묘에 적색광, 청색광 및 백색광이 혼합된 LED(Light-emitting diode) 인공광원을 조사(irradiation)하며 배양하는 단계를 포함하는, 뿌리 생육이 증진된 차나무(Camellia sinensis L.) 기내배양묘의 재배방법에 관한 것이다. claims: (a) 종피를 제거한 차나무(Camellia sinensis L.) 종자를 멸균하는 단계;(b) 상기 (a) 단계에서 멸균한 차나무 종자로부터 유근을 적출하는 단계;(c) 상기 (b) 단계에서 적출한 유근을 기내(in vitro)에서 배지에 치상하여 신초를 유도하고 1.5~2.5주간 배양하여 차나무 유묘를 생장시키는 단계; 및(d) 상기 (c) 단계의 차나무 유묘에 적색광, 청색광 및 백색광이 동일한 광량비율로 혼합되어 이루어진 LED 인공광원을 조사하며 40~50일 동안 재배하는 단계;를 포함하는 것인, 뿌리 수 및 뿌리 길이가 증진된 차나무 기내배양묘의 재배방법.제1항의 방법에 의해 재배된, 뿌리 수 및 뿌리 길이가 증진된 차나무(Camellia sinensis L.) 기내배양묘., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

153/1150 Row 153: application_number: 1020200066300, combined_string: invention_title: 인삼재배용 보온덮개 겸용 차광막 및 그 제조방법 abstract: 본 발명은 인삼재배용 보온덮개 겸용 차광막 및 그 제조방법에 관한 것으로, 알루미늄 호일층(10)과; 상기 알루미늄 호일층(10)의 상하 양면에 도포되는 접착제층(20, 70)과; 상기 접착제층(20) 상에 접착되는 폴리에스터 필름층(30)과; 상기 폴리에스터 필름층(30) 상에 도포되는 접착제층(40)과; 상기 접착제층(40) 상에 T다이 압출작업으로 샌드위치 방식으로 접착되는 폴리에틸렌 압출코팅층(50) 및 자외선(UV) 차단 폴리에틸렌 필름층(60) 및; 상기 접착제층(70) 상에 T다이 압출작업으로 샌드위치 방식으로 접착되는 폴리에틸렌 압출코팅층(80) 및 폴리에틸렌 마대지층(90)으로 구성되어 야간의 보온덮개 효율 및 주간의 차광 효율을 동시에 탁월하게 증진시켜 인삼식물의 성장에 적합한 재배 환경을 최적화할 수 있고, 접합면이 쉽게 벗겨지지 않아 알루미늄 포일의 물리적으로 나 빗물이나 겨울철 눈이 내릴 경우 강수에 의해 산화 부식이 용이하지 않으므로 장기간 안정되게 사용할 수 있는 수명이 종래 2 내지 3년에서 3년 이상 5년 이내 사용이 가능할 뿐만 아니라 구조가 단순하여 간단한 제조방법으로 제조할 수 있어 제품의 가격 저렴화로 경제성이 탁월한 각별한 장점이 있는 유용한 발명이다. claims: 6㎛ ∼ 7㎛ 두께의 알루미늄 호일층(10)을 프레스롤을 통해 접착제에 통과시켜 알루미늄 호일층(10)에 접착제층(20)을 도포하여 형성하는 제 1 접착제 도포공정(S1공정)과; 상기 접착제층(20)과 11㎛ ∼ 13㎛의 폴리에스터 필름층(30)을 프레스롤을 통과시켜 접착한 후 안내롤을 거쳐 덕터를 통과시켜 90℃ ∼ 110℃에서 경화시키는 폴리에스터 필름층 형성공정(S2공정)과; 상기 폴리에스터 필름층(30)이 형성된 알루미늄 호일층(10)을 1급지로 공급하고 접착제와 용제가 혼합된 용액을 도포한 후 건조 챔버에서 40 ∼ 80℃로 용제를 건조시켜 접착제층(40)을 형성하는 제 2 접착제 도포공정(S3공정)과; 상기 접착제층(40)이 형성된 폴리에스터 필름층(30)에 T다이를 통해 폴리에틸렌 압출코팅층(50)을 압출 코팅하여 형성하면서 2급지에 자외선(UV) 차단 폴리에틸렌 필름층(60)을 공급하여 샌드위치 방식으로 18㎛ ∼ 22㎛ 두께의 폴리에틸렌 압출코팅층(50)과 28㎛ ∼ 38㎛ 두께의 자외선(UV) 차단 폴리에틸렌 필름층(60)을 적층시킨 후 숙성실에서 48시간 동안 보관하여 접착제층(40)을 경화시키는 폴리에틸렌 압출코팅층 및 자외선(UV) 차단 폴리에틸렌 필름층 형성공정(S4공정)과; 상기 자외선(UV) 차단 폴리에틸렌 필름층(60)이 형성된 알루미늄 호일층(10)을 1급지로 공급하고 접착제와 용제가 혼합된 용액을 도포한 후 건조 챔버에서 40 ∼ 80℃로 용제를 건조시켜 접착제층(70)을 형성하는 제 3 접착제 도포공정(S5공정) 및; 상기 접착제층(70)이 형성된 상기 알루미늄 호일층(10)에 T다이를 통해 폴리에틸렌 압출코팅층(80)을 압출 코팅하여 형성하면서 2급지에 폴리에틸렌 마대지를 공급하여 샌드위치 방식으로 15㎛ ∼ 20㎛ 두께의 폴리에틸렌 압출코팅층(80)과 20㎛ ∼ 25㎛ 두께의 폴리에틸렌 마대지층(90)을 적층시킨 후 숙성실에서 48시간 동안 보관하여 접착제층(70)을 경화시키는 폴리에틸렌 압출코팅층 및 폴리에틸렌 마대지층 형성공정(S6공정)으로 이루어지는 인삼재배용 보온덮개 겸용 차광막의 제조방법.제 1항의 방법으로 제조된 인삼재배용 보온덮개 겸용 차광막., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

154/1150 Row 154: application_number: 1020200065170, combined_string: invention_title: 탄화 코르크를 이용한 인삼 재배장치 abstract: 본 발명은 인삼 재배장치에 관한 것으로서 특히 탄화코르크를 소재로 재배장치를 성형함으로써, 여러 세균의 감염으로부터 인삼을 보호하고, 적정한 습도를 유지하면서 인삼을 대량으로 건강하고 빠르게 수경 재배할 수 있는 인삼 재배 장치에 관한 것이다. claims: 일면에 개방된 측방향으로 인삼종묘가 삽입되어 인삼종묘 전체가 수납되도록 상부와 측부가 개방된 수직의 재배홈(102)이 소정 간격마다 연속 형성된 코르크 소재로 성형된 몸체(101); 상기 재배홈(102)의 하부 위치에서 각 재배홈(102) 하부와 연통되도록 형성된 수평의 연장홈(103);상기 몸체(101)의 측면에 체결되어 인삼종묘의 뿌리가 덮이도록 재배홈(102)의 개방된 측부를 밀폐함으로써, 인삼종묘가 재배홈(102)에 수납된 상태에서 상부만 개방되고 나머지는 밀폐되도록 하는 코르크를 소재로 하여 판 형태로 성형된 덮개(104); 및상기 덮개(104)를 몸체(101)에 체결하는 체결수단;으로 구성된 것을 특징으로 하는 탄화 코르크를 이용한 인삼 재배장치., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

155/1150 Row 155: application_number: 1020200050666, combined_string: invention_title: 편백큐브의 제조공정시스템 abstract: 본 발명에 따른 편백큐브의 제조공정시스템은: 편백나무 판재에 절개 홈이 길이방향으로 나란히 여러 개 형성되도록 유입되는 편백나무를 종 방향으로 가공하는 절개 홈 커팅장치; 상기 절개 홈 커팅장치를 거치면서 여러 개의 절개 홈이 형성된 편백나무 판재를 횡 방향으로 절단하여 절개 홈들이 형성된 편백나무 판재가 다수의 편백 마디 블록들이 되도록 가공하는 마디 커팅장치; 및, 상기 마디 커팅장치를 거치면서 가공된 다수의 편백 마디 블록들이 상부로 유입되면 이들을 한꺼번에 회전시키며 연마되도록 하여 다수의 편백큐브들로 가공되도록 하는 편백큐브 가공장치;를 포함하는 것을 특징으로 한다. 이에 의하여, 베개 등의 충전재로 사용되는 큐브 형태의 편백나무 칩을 제조하기 위하여 편백나무 판재를 절단, 연마, 모서리 가공 등의 일련의 연속 공정으로 편리하게 가공하고 가공 공정 중에 편백나무 가루가 칩에 달라붙는 것도 효과적으로 방지하여 작업성과 상품성이 향상되도록 할 수 있으며, 특히 모서리 부분이 둥글게 형성되도록 할 수 있는 편백큐브의 제조공정시스템을 제공할 수 있다. claims: 편백나무 판재에 절개 홈이 길이방향으로 나란히 여러 개 형성되도록 유입되는 편백나무를 종 방향으로 가공하는 절개 홈 커팅장치;상기 절개 홈 커팅장치를 거치면서 여러 개의 절개 홈이 형성된 편백나무 판재를 횡 방향으로 절단하여 절개 홈들이 형성된 편백나무 판재가 다수의 편백 마디 블록들이 되도록 가공하는 마디 커팅장치; 및상기 마디 커팅장치를 거치면서 가공된 다수의 편백 마디 블록들이 상부로 유입되면 이들을 한꺼번에 회전시키며 연마되도록 하여 다수의 편백큐브들로 가공되도록 하는 편백큐브 가공장치;를 포함하고,상기 편백큐브 가공장치는, 하부에 구비된 지지 프레임과, 상기 지지 프레임의 상부에 구비되며 상부가 개방 또는 개폐 가능하게 구비된 원통 형상으로 마련되어 다수의 편백 마디 블록들이 내부로 유입되고 내부에는 유입되는 다수의 편백 마디 블록들이 한꺼번에 회전되며 연마되어 다수의 편백큐브들로 가공되도록 하부에 회전 연마 트레이가 구비된 큐브 가공 드럼과, 상기 회전 연마 트레이에 연결되어 상기 회전 연마 트레이가 회전되도록 구동력을 제공하는 회전 구동부를 포함하며,상기 편백큐브 가공장치는 상기 큐브 가공 드럼 내부에서 다수의 편백 마디 블록들이 편백큐브들로 가공될 때에 발생되는 칩 분진이 제거되도록 일측은 상기 큐브 가공 드럼에 연결되고 타측은 집진기에 연결되어 상기 큐브 가공 드럼 내부의 공기가 흡입되도록 하는 분진 흡입부를 더 포함하고,상기 큐브 가공 드럼의 상부에는 개폐 커버가 구비되어 개폐 커버의 개폐 동작에 의해 개방 또는 폐쇄가 선택적으로 이뤄지며, 상기 개폐 커버의 하부에는 개폐 커버로부터 이격 되게 가압 커버가 구비되고, 상기 개폐 커버와 상기 가압 커버의 사이에는 가압 스프링이 구비되며,상기 편백큐브 가공장치를 거치며 가공된 편백큐브들이 떨림 진동에 의해 일정한 크기별로 선별 분류되도록 하는 큐브 선별장치를 더 포함하고,상기 큐브 선별장치는, 상기 편백큐브 가공장치의 일측에서 하부에 원통 형상으로 마련되어 고정 설치된 고정부와, 상기 고정부의 상부에 상기 고정부의 외경보다 큰 외경을 갖도록 마련되며 상기 고정부와 분리되게 구비되어 후술할 선별 진동자에 의해 상기 고정부에 대해 떨림 진동되고 판면에 다수의 선별 공들이 천공 형성된 선별 채가 구비된 가동 틀과, 상기 고정부 및 상기 가동 틀의 중심부 사이에 구비되어 상기 가동 틀이 상기 고정부에 대해 떨림 진동되도록 하는 선별 진동자와, 상기 고정부의 상부에서 둘레를 따라 상기 가동 틀과의 사이에 일정 간격마다 구비되어 상기 가동 틀의 진동시 상기 가동 틀이 상기 고정부에서 이탈 변위 되는 것을 잡아주는 진동 완충 스프링과, 상기 진동 완충 스프링의 상부 및 하부에서 삽입 연장되게 상기 고정부의 상부 및 상기 가동 틀의 하부에서 각각 연장되며 상호 대칭되게 구비된 고무 재질의 댐퍼를 포함하는 것을 특징으로 하는 편백큐브의 제조공정시스템., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

156/1150 Row 156: application_number: 1020200044560, combined_string: invention_title: 사카린을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충 방제 방법 abstract: 본 발명은 사카린을 포함하는 소나무재선충 방제용 조성물 및 이를 이용한 소나무재선충을 방제하는 방법에 관한 것이다. claims: 사카린을 포함하는 소나무재선충 방제용 조성물.제 1항 내지 제 4항 중 어느 하나의 조성물을 식물 또는 토양에 처리하여 소나무재선충을 방제하는 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

157/1150 Row 157: application_number: 1020200043339, combined_string: invention_title: 토마토 혼성체 HN5003 및 부모 계통 SENG9234 abstract: 본 발명은 신규한 토마토 혼성체 HN5003 또는 계통 SENG9234 및 이로부터 유래하는 식물 부분, 종자 및 조직 배양을 제공한다. 또한, 본 발명은 본 발명의 토마토 식물을 그 자신 또는 다른 토마토 식물과 교배함으로써 토마토 식물을 생산하는 방법을 제공한다. 또한, 본 발명은 이 같은 교배로부터 생산되는 토마토 식물뿐만 아니라 이로부터 유래하는 식물 부분, 종자 및 조직 배양을 제공한다. claims: 각각 NCIMB 기탁 번호 제43380호 및 NCIMB 기탁 번호 제43381호로 기탁되어 있는 대표적인 종자 시료인 토마토 혼성체 HN5003 또는 계통 SENG9234를 생산하는 종자.제8항의 상기 조직 배양으로부터 재생되는 토마토 식물 또는 이의 자가 수분된 자손으로서,상기 토마토 식물은 토마토 혼성체 HN5003 또는 계통 SENG9234의 생리학적 및 형태학적 특징을 모두 포함하는 것인 토마토 식물 또는 이의 자가 수분된 자손.토마토 종자를 생산하는 방법으로서,제2항의 상기 식물을 그 자신 또는 제2 토마토 식물과 교배하는 단계; 및얻어진 종자를 수확하는 단계를 포함하는 것인 토마토 종자를 생산하는 방법.접목된 토마토 식물을 생산하는 방법으로서,(a) 제2항의 상기 식물로부터 어린 가지를 제공하는 단계; 및(b) 상이한 토마토 식물에서 유래하는 근경에 상기 어린 가지를 접목하는 단계를 포함하는 것인 접목된 토마토 식물을 생산하는 방법.토마토 혼성체 HN5003 또는 계통 SENG9234에서 유래하는 토마토 식물의 종자를 생산하는 방법으로서,(a) 제2항의 상기 식물을 상이한 토마토 식물과 교배하는 단계;(b) 종자를 형성하도록 하는 단계;(c) 단계 (b)의 상기 종자로부터 식물을 재배하여 토마토 혼성체 HN5003 또는 계통 SENG9234에서 유래하는 식물을 생산하는 단계;(d) 단계 (c)의 상기 식물을 자가 수분시키거나 이를 제2 토마토 식물과 교배하여 토마토 혼성체 HN5003 또는 계통 SENG9234에서 유래하는 부가적인 토마토 종자를 형성하는 단계; 및(e) 선택적으로는 단계 (c) 및 단계 (d)를 1회 이상 반복하여 토마토 혼성체 HN5003 또는 계통 SENG9234로부터 유래하는 추가의 토마토 종자를 생성하는 단계를 포함하며,이때, 단계 (c)에서는 단계 (b)의 상기 종자로부터 식물을 재배하는 대신에 단계 (d)의 상기 부가적인 토마토 종자로부터 식물을 재배하는 것인 토마토 식물의 종자를 생산하는 방법.토마토 혼성체 HN5003 또는 계통 SENG9234를 영양 번식하는 방법으로서,(a) 제2항의 상기 식물로부터 번식될 수 있는 조직을 수집하는 단계;(b) 상기 조직을 배양하여 증식된 새싹을 수득하는 단계;(c) 증식된 새싹을 발근(rooting)시켜 발근된 묘목(plantlet)을 수득하는 단계; 및(d) 선택적으로는 상기 발근된 묘목으로부터 식물을 재배하는 단계를 포함하는 것인 토마토 혼성체 HN5003 또는 계통 SENG9234를 영양 번식하는 방법.제17항의 상기 방법에 의해 수득되는 토마토 묘목 또는 식물로서,상기 토마토 묘목 또는 식물은 토마토 혼성체 HN5003 또는 계통 SENG9234의 생리학적 및 형태학적 특징을 모두 포함하는 것인 토마토 묘목 또는 식물.토마토 혼성체 HN5003 또는 계통 SENG9234에 목적하는 부가 형질을 도입하는 방법으로서,(a) 반복친(recurrent parent)으로서의 제2항의 상기 식물을 목적하는 부가 형질을 포함하는 상이한 토마토 식물과 교배하여 F1 자손을 생산하는 단계;(b) 상기 목적하는 부가 형질을 포함하는 F1 자손을 선별하는 단계;(c) 상기 선별된 F1 자손을 단계 (a)에서와 동일한 반복친과 교배하여 역교배 자손을 생산하는 단계;(d) 상기 목적하는 부가 형질을 포함하는 역교배 자손을 선별하는 단계; 및(e) 선택적으로는 단계 (c) 및 단계 (d)를 1회 이상 반복하여, 상기 목적하는 부가 형질을 포함하고, 그렇지 않는 경우 토마토 혼성체 HN5003 또는 계통 SENG9234의 생리학적 및 형태학적 특징을 모두 포함하는 토마토 혼성체 HN5003 또는 계통 SENG9234에서 유래한 식물을 생산하는 단계를 포함하며,이때, 단계 (c)에서는 단계 (d)에서 생산된 상기 선별된 역교배 자손을 단계 (b)의 상기 선별된 F1 자손 대신에 사용하는 것인 토마토 혼성체 HN5003 또는 계통 SENG9234에 목적하는 부가 형질을 도입하는 방법.제22항의 상기 방법에 의해 생산되는 토마토 식물 또는 이의 자가 수분된 자손으로서,상기 토마토 식물은 상기 목적하는 부가 형질을 갖는 것인 토마토 식물 또는 이의 자가 수분된 자손.목적하는 부가 형질을 포함하는 토마토 혼성체 HN5003 또는 계통 SENG9234의 식물을 생산하는 방법으로서,제2항의 상기 식물에 상기 목적하는 형질을 부여하는 이식 유전자를 도입하는 단계를 포함하는 것인 토마토 혼성체 HN5003 또는 계통 SENG9234의 식물을 생산하는 방법.제26항의 상기 방법에 의해 생산되는 토마토 식물 또는 이의 자가 수분된 자손으로서,상기 토마토 식물은 상기 이식 유전자를 포함하고 상기 목적하는 부가 형질을 갖는 것인 토마토 식물 또는 이의 자가 수분된 자손.토마토 열매를 생산하는 방법으로서,(a) 제2항에 따른 상기 토마토 식물을 재배하여 토마토 열매를 생산하는 단계; 및(b) 상기 토마토 열매를 수확하는 단계를 포함하는 것인 토마토 열매를 생산하는 방법.토마토 가공 산물을 생산하는 방법으로서,(a) 제2항의 상기 식물의 열매를 수득하는 단계; 및(b) 상기 열매를 가공하여 가공 산물을 생산하는 단계를 포함하는 것인 토마토 가공 산물을 생산하는 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

158/1150 Row 158: application_number: 1020200037928, combined_string: invention_title: 탄소복합소재 적재함을 가진 다목적 드론 abstract: 본 발명은 탄소복합소재 적재함을 가진 다목적 드론에 관한 것이다. 본 발명에 의한 탄소복합소재 적재함을 가진 다목적 드론은, 복수의 프로펠러들이 회전 가능하게 설치되고, 드론 구동을 위한 회로기판 및 전자부품들이 수용되는 캐노피; 드론 랜딩시 랜딩면에 접촉되는 한 쌍의 랜딩부들과, 각각 일측은 상기 각 랜딩부에 연결되고 타측은 상기 상기 캐노피에 연결되는 연결프레임부들을 구비하는 스키드; 및 비료와 같은 농업에 사용되는 재료 또는 묘목과 같은 임업 수확물 수용을 위한 것으로, 탄소복합소재를 포함한 재질로 이루어지고, 상기 연결프레임부의 일측과 타측 사이의 부분에 지지가능하게 설치되는 적재함;을 포함하여 이루어지는 것을 특징으로 한다. claims: 복수의 프로펠러들이 회전 가능하게 설치되고, 드론 구동을 위한 회로기판 및 전자부품들이 수용되는 캐노피;드론 랜딩시 랜딩면에 접촉되는 한 쌍의 랜딩부들과, 각각 일측은 상기 각 랜딩부에 연결되고 타측은 상기 상기 캐노피에 연결되는 연결프레임부들을 구비하는 스키드; 및비료와 같은 농업에 사용되는 재료 또는 묘목과 같은 임업 수확물 수용을 위한 것으로, 탄소복합소재를 포함한 재질로 이루어지고, 상기 연결프레임부의 일측과 타측 사이의 부분에 지지가능하게 설치되는 적재함;을 포함하여 이루어지는 것을 특징으로 하는 탄소복합소재 적재함을 가진 다목적 드론., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

159/1150 Row 159: application_number: 1020200037943, combined_string: invention_title: 규조토, 일라이트를 함유하고 편백추출액으로 코팅된 건축용 마감재 abstract: 본 발명은 규조토, 일라이트를 함유하고 편백추출액으로 코팅된 건축용 마감재에 관한 것으로서, 그 구성은 살균하여 분쇄 및 압착된 알갱이 형태의 왕겨, 황토분말, 규조토 분말, 숯 분말 및 게르마늄 분말이 혼합된 제 1 혼합물과 일라이트, 맥반석, 흑운모 및 연옥을 분쇄하여 각각 5mm 내지 20mm 크기의 석재가 혼합된 제 2 혼합물을 교반기 통해 혼합하고, 미강, 찹쌀 및 물을 혼합하여 95℃로 일정시간 가열하여 냉각시켜 준비된 천연 접착제를 제 1 혼합물과 제 2 혼합물과 혼합하여 고형화를 위해 건축용 마감재의 비중에 맞춰 압축 로울러로 압착하여 성형하고, 성형된 마감재 표면을 편백추출액으로 코팅한 후 120℃ ∼ 140℃의 온도로 가열하여 성형된 건축용 마감재의 접착성분에 의해 압축상태를 유지하기 위해 가열하여 바닥, 벽, 천정, 실외 벽재를 위한 건축용 마감재의 형태를 구성되는 것을 특징으로 한다. 이에 의해, 왕겨, 황토, 규조토, 숯의 성분을 통해 자연습도조절은 물론 총휘발성 유기화합물, 포름알데히드 등 유해요소의 제거, 탈취기능 및 항균기능 등을 함께 가지는 것은 물론 일라이트, 흑운모, 연옥를 통해 도막의 변색이나 변형이 거의 없어 건축 마감재뿐만 아니라, 내 외장용 마감재로도 사용할 수 있는 쾌적하면서도 친환경적인 건축마감재를 제공한다. claims: 살균하여 분쇄 및 압착된 알갱이 형태의 왕겨, 황토분말, 규조토 분말, 숯 분말 및 게르마늄 분말이 혼합된 제 1 혼합물과 일라이트, 맥반석, 흑운모 및 연옥을 분쇄하여 각각 5mm 내지 20mm 크기의 석재가 혼합된 제 2 혼합물을 교반기 통해 혼합하고, 미강, 찹쌀 및 물을 혼합하여 95℃로 일정시간 가열하여 냉각시켜 준비된 천연 접착제를 제 1 혼합물과 제 2 혼합물과 혼합하여 고형화를 위해 건축용 마감재의 비중에 맞춰 압축 로울러로 압착하여 성형하고, 성형된 마감재 표면을 편백추출액으로 코팅한 후 120℃ ∼ 140℃의 온도로 가열하여 성형된 건축용 마감재의 접착성분에 의해 압축상태를 유지하기 위해 가열하여 바닥, 벽, 천정, 실외 벽재를 위한 건축용 마감재의 형태를 이루어지는 것을 특징으로 하는 규조토, 일라이트를 함유하고 편백추출액으로 코팅된 건축용 마감재., Ltext: 임업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

160/1150 Row 160: application_number: 1020200033916, combined_string: invention_title: 소나무재선충 신속 검출용 재조합효소-중합효소 증폭 프라이머 프로브 세트 abstract: 본 발명은 소나무재선충(Bursaphelenchus xylophilus) 신속 검출용 재조합효소-중합효소 증폭 프라이머 프로브 세트에 관한 것이다. 본 발명의 소나무재선충 검출용 RPA 프라이머 프로브 세트는 어리소나무재선충(B. mucronatus)을 포함한 근연관계의 부식성 선충류(B. doui, B. thailandae, B. hylobianum)로부터 소나무재선충(B. xylophilus)을 특이적으로 구별할 수 있기 때문에 소나무재선충병 감염이 의심되는 목편 시료에서 신속하고 정확하게 소나무재선충병 감염 여부를 진단할 수 있으므로, 소나무재선충 검출 및 소나무재선충병 진단 방법에 효과적이다. claims: 서열번호 1의 염기서열로 이루어진 정방향 프라이머 및 서열번호 2의 염기서열로 이루어진 역방향 프라이머로 이루어진 프라이머 세트; 및 서열번호 3의 염기서열로 이루어진 증폭산물을 확인하는 프로브를 포함하는, 소나무재선충(Bursaphelenchus xylophilus) 신속 검출용 재조합효소-중합효소 반응 (Recombinase Polymerase Amplification; RPA) 프라이머 프로브 세트.(a) 소나무 시료로부터 DNA를 분리하는 단계;(b) 상기 (a) 단계에서 분리한 DNA를 주형으로 하고 제 1항의 프라이머 세트를 이용하여 재조합효소-중합효소 반응(RPA)을 수행하는 단계; 및(c) 상기 (b) 단계의 반응 산물을 분석하는 단계를 포함하는 소나무재선충병 진단 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

161/1150 Row 161: application_number: 1020200024958, combined_string: invention_title: 농업 및 임업용 드론 abstract: 본 발명은 농업 및 임업용 드론에 관한 것으로, 예컨대 농업용에 사용되는 비료들 중 입상 비료와 액상 비료의 체적이 달라 케이스의 규격이 다른 경우 그 케이스가 탑재되는 스키드의 규격이 달라 교체가 요구되는 경우에, 드론 구동을 위한 전자부품과 프로펠라가 설치된 캐노피는 그대로 두고 스키드를 캐노피에 결합시키되, 결합 유닛의 레일부와 레일홈부 간의 슬라이딩 동작에 의한 결합 및 분리가 가능하여 교체 작업의 편리성을 향상시킬 수 있게 하는 효과와, 나사나 볼트에 의한 반복적인 드릴링 과정이 요구되지 않게 됨으로써 제품의 내구성을 높일 수 있게 하는 효과를 기대할 수 있게 한다. claims: 복수의 프로펠러들이 회전 가능하게 설치되고, 드론 구동을 위한 회로기판 및 전자부품들이 수용되는 캐노피; 비료와 같은 농업에 사용되는 재료 또는 묘목과 같은 임업 수확물 수용을 위한 케이스를 상기 캐노피에 지지시켜 주기 위한 것으로, 랜딩시 랜딩면에 접촉되는 한 쌍의 랜딩부들과, 일측은 상기 각 랜딩부에 연결되고 타측은 상기 상기 캐노피에 연결되며, 상기 일측과 타측 사이의 부분에 상기 케이스가 지지가능하게 설치되며, 상기 랜딩부의 길이방향을 따라 간격을 두고 배치되는 한 쌍의 연결프레임부들을 구비하는 스키드; 및 상기 캐노피와 스키드가 서로 상대이동 과정에서 끼움결합될 수 있도록, 상기 캐노피와 스키드 중 어느 하나에 일방향 축선을 따라 길게 형성된 레일부와 다른 하나에 마련되고 상기 레일부가 끼워지는 레일홈부와 상기 캐노피와 스키드의 끼움 결합이 완료된 상태에서 임의 분리를 방지하기 위한 록킹부를 포함하는 결합 유닛;을 포함하여 이루어지고,상기 케이스는, 상기 각 연결프레임부에 고정되는 고정케이스; 및 상기 고정케이스에 상대이동 가능하게 설치되고, 상기 묘목과 같은 임업 수확물이 수용되는 공간을 가지며, 묘목이 놓이는 바닥면의 중심부에 형성되는 것으로 흙과 같은 이물질이 상기 고정케이스 측으로 배출될 수 있게 하는 이물질 배출부와, 상기 바닥면의 중심부를 사이에 두고 반대측에 형성되는 것으로 상기 중심부측으로 갈수록 높이가 낮게 형성되는 한 쌍의 경사부들을 구비하는 인출케이스;를 포함하여 이루어지는 것을 특징으로 하는 농업 및 임업용 드론., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

162/1150 Row 162: application_number: 1020200016784, combined_string: invention_title: 신규 스트렙토마이세스 속 균주 또는 이로부터 분리된 화합물을 함유하는 소나무재선충병 방제용 조성물 abstract: 본 발명은 신규한 스트렙토마이세스 속(Streptomyces sp.) 균주 및 상기 균주 또는 상기 균주로부터 분리된 화합물을 유효성분으로 함유하는 소나무재선충병 방제용 조성물에 관한 것으로, 본 발명의 스트렙토마이세스 속 균주 및 이로부터 분리한 화합물은 소나무재선충병 방제에 효과적인 환경친화형 생물농약을 제공할 수 있어 관련 산업에 매우 유용할 것으로 기대된다. claims: 기탁번호가 KCTC13792BP인 스트렙토마이세스 속(Streptomyces sp.) AE170020 균주.하기 화학식 1로 표시되는 화합물, 이의 입체이성질체 또는 이의 농약학적으로 허용가능한 염을 유효성분으로 함유하는 소나무재선충병 방제용 조성물.[화학식 1]상기 화학식 1에서,R1 및 R2는 각각 독립적으로 수소, C1~4 알킬 또는 C1~4 알콕시이고;R3은 C1~4 알킬이고;R4 및 R5는 각각 독립적으로 수소, C1~4 알킬, C1~4 알콕시, 히드록시 또는 할로이고;R6 내지 R8은 각각 독립적으로 수소, 또는 C1~4 알킬이고;n은 1, 2 또는 3의 정수이다.기탁번호가 KCTC13792BP인 스트렙토마이세스 속(Streptomyces sp.) AE170020 균주 배양액을 유효성분으로 함유하는 소나무재선충병 방제용 조성물., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

163/1150 Row 163: application_number: 1020200017233, combined_string: invention_title: 다양한 소나무에 저항성을 유도하는 바실러스 서린지엔시스 JCK-1233 균주 및 이를 이용한 소나무재선충병 방제용 조성물 abstract: 본 발명은 다양한 소나무에 저항성을 유도하는 바실러스 서린지엔시스(Bacillus thuringiensis) JCK-1233 균주(수탁번호 KCTC 14085BP) 및 이로부터 분리된 다이케토피페라진(Diketopiperazine) 화합물, 및 이를 유효성분으로 포함하는 살선충제 조성물 및 식물병 방제용 조성물에 관한 것으로, 본 발명의 바실러스 서린지엔시스(Bacillus thuringiensis) JCK-1233 균주 및 이로부터 분리된 다이케토피페라진(Diketopiperazine) 화합물은 소나무에 저항성을 유도함으로써 식물병 원인 선충에 대한 방제 활성을 가지는 것을 실험적으로 확인하였다. 따라서, 본 발명의 바실러스 서브틸리스 JCK-1233 균주는 관련 식물병 방제 용도로 유용하게 사용될 수 있으며, 엽면살포를 통한 광범위 지역 살포가 가능하므로, 낮은 비용으로 소나무재선충병의 확산을 방지할 수 있을 것으로 기대된다. claims: 병해충에 대한 식물의 유도저항성 (induced resistance)을 활성화하는 수탁번호 KCTC 14085BP의 바실러스 서린지엔시스 (Bacillus thuringiensis) JCK-1233 균주.제1항 내지 제3항 중 어느 한 항의 균주, 상기 균주의 배양물, 상기 배양물의 농축물, 상기 배양물의 건조물 및 상기 균주의 배양 상등액으로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물.하기 화학식 1 내지 화학식 6으로 표시되는 화합물 및 이의 유도체(derivative)로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물:[화학식 1][화학식 2][화학식 3][화학식 4][화학식 5][화학식 6].제6항에 있어서, 상기 화학식 1 내지 화학식 6으로 표시되는 화합물은 수탁번호 KCTC 14085BP의 바실러스 서린지엔시스 (Bacillus thuringiensis) JCK-1233 균주로부터 분리된 것인, 조성물.제6항에 있어서, 상기 식물병은 소나무재선충병인, 조성물., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

164/1150 Row 164: application_number: 1020200017234, combined_string: invention_title: 다양한 식물에 저항성을 유도하는 바실러스 메가테리움 JCK-758-1 균주, 이를 이용한 소나무재선충병 방제용 조성물 및 방제방법 abstract: 본 발명은 소나무 및 다양한 식물에 유도저항성 활성을 갖는 바실러스 메가테리움 (Bacillus megaterium) JCK-758-1 균주 (수탁번호 KCTC 14083BP) 및 이로부터 분리된 화합물, 및 이를 유효성분으로 포함하는 살선충제 또는 항균제 조성물, 식물병 방제용 조성물 및 이를 이용한 방제방법에 관한 것으로, 본 발명의 바실러스 메가테리움 JCK-758-1 균주 및 이로부터 분리된 화합물은 기주에 저항성을 유도함으로써 식물병 원인 선충 및 균에 대한 방제 활성을 가지는 것을 실험적으로 확인하였다. 따라서, 본 발명의 바실러스 메가테리움 JCK-758-1 균주는 관련 식물병 방제 용도로 유용하게 사용될 수 있으며, 엽면살포를 통한 광범위 지역 살포가 가능하므로, 낮은 비용으로 소나무재선충병의 확산을 방지할 수 있을 것으로 기대된다. claims: 병해충에 대한 식물의 유도저항성 (induced resistance)을 활성화하는 수탁번호 KCTC 14083BP의 바실러스 메가테리움 (Bacillus megaterium) JCK-758-1 균주.제1항 내지 제3항 중 어느 한 항의 균주, 상기 균주의 배양물, 상기 배양물의 농축물, 상기 배양물의 건조물 및 상기 균주의 배양 상등액으로 이루어진 군으로부터 선택된 1종 이상을 포함하는 살선충제 또는 항균제 조성물.제1항 내지 제3항 중 어느 한 항의 균주, 상기 균주의 배양물, 상기 배양물의 농축물, 상기 배양물의 건조물 및 상기 균주의 배양 상등액으로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물.하기 화학식 1 내지 화학식 5로 표시되는 화합물 및 이의 유도체로 이루어진 군으로부터 선택된 1종 이상을 포함하는 살선충제 또는 항균제 조성물:[화학식 1][화학식 2][화학식 3][화학식 4][화학식 5].제9항에 있어서, 상기 화학식 1 내지 화학식 5로 표시되는 화합물은 수탁번호 KCTC 14083BP의 바실러스 메가테리움 (Bacillus megaterium) JCK-758-1 균주로부터 분리된 것인, 조성물.제9항에 있어서, 상기 선충은 소나무재선충 (Bursaphelenchus xylophilus)인 것인, 조성물.제9항에 있어서, 상기 균은 크산토모나스 유베시카토리아 (Xanthomonas euvesicatoria)인 것인, 조성물.하기 화학식 1 내지 화학식 5로 표시되는 화합물 및 이의 유도체로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물:[화학식 1][화학식 2][화학식 3][화학식 4][화학식 5].제13항에 있어서, 상기 화학식 1 내지 화학식 5로 표시되는 화합물은 수탁번호 KCTC 14083BP의 바실러스 메가테리움 (Bacillus megaterium) JCK-758-1 균주로부터 분리된 것인, 조성물.제13항에 있어서, 상기 식물병은 소나무재선충병 및 고추세균성점무늬병으로 이루어진 군으로부터 선택된 것인, 조성물., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

165/1150 Row 165: application_number: 1020200017232, combined_string: invention_title: 다양한 식물에 저항성을 유도하는 바실러스 서브틸리스 JCK-1398 균주, 이를 이용한 소나무재선충병 방제용 조성물 및 방제방법 abstract: 본 발명은 소나무 및 다양한 식물에 유도저항성 활성을 갖는 바실러스 서브틸리스 (Bacillus subtilis) JCK-1398 균주 (수탁번호 KCTC 14084BP) 및 이를 유효성분으로 포함하는 살충제 또는 항균제 조성물, 식물병 또는 해충 방제용 조성물 및 이를 이용한 방제방법에 관한 것으로, 본 발명의 바실러스 서브틸리스 (Bacillus subtilis) JCK-1398 균주는 기주에 저항성을 유도함으로써 다양한 식물병 원인 해충, 선충 및 균에 대한 방제 활성을 가지는 것을 실험적으로 확인하였다. 따라서, 본 발명의 바실러스 서브틸리스 JCK-1398 균주는 관련 식물병 방제 용도로 유용하게 사용될 수 있으며, 엽면살포를 통한 광범위 지역 살포가 가능하므로, 낮은 비용으로 소나무재선충병의 확산을 방지할 수 있을 것으로 기대된다. claims: 식물병에 대한 소나무, 고추, 잔디 및 토마토로 이루어진 군으로부터 선택되는 1종 이상의 유도저항성 (induced resistance)을 활성화하는 수탁번호 KCTC 14084BP의 바실러스 서브틸리스 (Bacillus subtilis) JCK-1398 균주.수탁번호 KCTC 14084BP의 바실러스 서브틸리스 (Bacillus subtilis) JCK-1398 균주, 상기 균주의 배양물, 상기 배양물의 농축물, 상기 배양물의 건조물 및 상기 균주의 배양 상등액으로 이루어진 군으로부터 선택된 1종 이상을 포함하는 식물병 방제용 조성물에 관한 것으로서,상기 식물병은 소나무재선충병, 고추세균성점무늬병 및 잔디동전마름병으로 이루어진 군으로부터 선택된 것인, 조성물., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

166/1150 Row 166: application_number: 1020200015543, combined_string: invention_title: 국내산 낙엽송과 잣나무 탄화건조 가로등 지주목 abstract: 본 발명은 국내산 낙엽송과 잣나무 탄화건조 가로등 지주목에 관한 것으로서, 더욱 상세하게는 국내산 낙엽송, 잣나무 등과 같은 원목을 가로등 지주에 사용 가능하도록 탄화건조방식으로 처리하여, 내구성뿐만 아니라 친환경적이면서 친자연적인 아름다움을 극대화함에 따라 도시화된 거리에 자연적인 이미지를 부각시켜줌에 따라 불특정 다수인들에게 편안하고 안락한 친밀감을 제공하는 가로등 지주의 제품경쟁력을 강화하는 국내산 낙엽송과 잣나무 탄화건조 가로등지주목에 관한 것이다.이를 위해 본 발명의 가로등지주목(1)는 길이방향으로 관통하는 중심홀(2)이 형성되고; 상기 중심홀(2)이 형성된 가로등지주목(1)를 150 ~ 350(℃)의 온도에서 2 내지 7(일) 동안 간접 가열로 숙성 건조하는 탄화건조법으로 상기 가로등지주목(1)를 방부처리하며; 상기 탄화건조법으로 방부처리된 가로등지주목(1)의 중심홀(2)에는 금속재이면서 일정두께를 가지는 파이프(10)를 억지 끼움으로 삽입하여;된 것을 특징으로 하는 한다. claims: 가로등과 같이 일정높이 세워지는 지주로 사용 가능한 가로등지주목에 있어서, 상기 가로등지주목(1)은길이방향으로 관통하는 중심홀(2)이 형성되고;상기 중심홀(2)이 형성된 가로등지주목(1)을 150 ~ 350(℃)의 온도에서 1 내지 7(일) 동안 간접 가열로 숙성 건조하는 탄화건조법으로 상기 가로등지주목(1)의 내구성 및 방부기능을 가지도록 하는 것을 특징으로 하는 국내산 낙엽송과 잣나무 탄화건조 가로등 지주목.가로등과 같이 일정높이 세워지는 지주로 사용 가능한 가로등지주목에 있어서, 상기 가로등지주목(1)은길이방향으로 관통하는 중심홀(2)이 형성되고;상기 중심홀(2)에는 일정두께를 가지는 파이프(10)를 삽입하며;상기 파이프(10)가 삽입된 가로등지주목(1)을 150 ~ 350(℃)의 온도에서 1 내지 7(일) 동안 간접 가열로 숙성 건조하는 탄화건조법으로 상기 가로등지주목(1)의 내구성 및 방부기능을 가지도록 하며;상기 탄화건조법에 의해 수축되는 가로등지주목(1)에 의해 상기 중심홀(2)에 삽입된 파이프(10)가 수축력에 의한 압박으로 상기 중심홀(2)에 고정되도록;하는 것을 특징으로 하는 국내산 낙엽송과 잣나무 탄화건조 가로등 지주목., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

167/1150 Row 167: application_number: 1020200015705, combined_string: invention_title: 시맨틱 분할을 이용한 소나무 재선충 확산 방지 시스템 및 방법 abstract: 본 발명의 일 실시예에 따른 시맨틱 분할을 이용한 소나무 재선충 확산 방지 시스템은 소나무가 분포한 지역에 관한 촬영 이미지를 데이터 세트로서 수집하고, 상기 수집된 데이터 세트에 대하여 픽셀 단위로 레이블을 지정하여 훈련 세트를 생성하는 전처리부; 및 상기 데이터 세트 및 상기 훈련 세트를 바탕으로 시맨틱 분할 딥러닝을 수행하여 객체를 분류하고, 상기 객체의 분류 결과에 기초하여 소나무 재선충병 관련 정보를 제공하는 학습부를 포함한다. claims: 소나무가 분포한 지역에 관한 촬영 이미지를 데이터 세트로서 수집하고, 상기 수집된 데이터 세트에 대하여 픽셀 단위로 레이블을 지정하여 훈련 세트를 생성하는 전처리부; 및상기 데이터 세트 및 상기 훈련 세트를 바탕으로 시맨틱 분할 딥러닝을 수행하여 객체를 분류하고, 상기 객체의 분류 결과에 기초하여 소나무 재선충병 관련 정보를 제공하는 학습부를 포함하는 것을 특징으로 하는 시맨틱 분할을 이용한 소나무 재선충 확산 방지 시스템.시맨틱 분할을 이용한 소나무 재선충 확산 방지 시스템을 이용한 소나무 재선충 확산 방지 방법에 있어서,상기 소나무 재선충 확산 방지 시스템의 전처리부가 소나무 분포 지역에 관한 촬영 이미지를 데이터 세트로서 수집하는 단계;상기 전처리부가 상기 수집된 데이터 세트에 대하여 픽셀 단위로 레이블을 지정하여 훈련 세트를 생성하는 단계;상기 소나무 재선충 확산 방지 시스템의 학습부가 상기 데이터 세트 및 상기 훈련 세트를 바탕으로 시맨틱 분할 딥러닝을 수행하여 객체를 분류하는 단계; 및상기 학습부가 상기 객체의 분류 결과에 기초하여 소나무 재선충병 관련 정보를 제공하는 단계를 포함하는 것을 특징으로 하는 시맨틱 분할을 이용한 소나무 재선충 확산 방지 방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

168/1150 Row 168: application_number: 1020200003149, combined_string: invention_title: 고로쇠 수액 출수량 예측 시스템 abstract: 개시된 본 발명에 따른 고로쇠 수액 출수량 예측 시스템은, 복수의 센서가 설치되어 복수의 환경정보를 얻으며 고로쇠 수액이 저장되는 스마트 집수조(100)와, 스마트 집수조에서 보내온 복수의 환경정보와 고로쇠 수액 출수량 정보및 기상청의 기상환경 정보가 입력되는 데이터 입력부(200)와, 데이터 입력부에 입력된 정보들을 머신러닝 알고리즘의 학습 데이터로 활용하기 위해 전처리를 수행하는 데이터 전처리부(300)와, 고로쇠 수액 출수량을 예측하기 위해 복수의 인공신경망 트리 모델을 구성하며, 구축된 복수의 인공신경망 트리 모델은 상기 데이터 전처리부의 데이터를 입력값으로 하여 상기 환경정보와 고로쇠 수액 출수량의 상관관계를 분석하여 각각의 예측을 진행하고, 예측 수액 출수량을 출력값으로 하여 예측 결과를 도출하는 수액 출수량 예측모델 생성부(400), 및 수액 출수량 예측모델 생성부의 복수의 예측 결과를 다수결의 원칙으로 처리하여 최종 고로쇠 수액의 예측 출수량을 산출하는 수액 출수량 산출부를 포함한다. 본 발명에 의하면 머신러닝에 기반하여 학습 시간, 예측 시간, 정확도를 기준으로 가장 정확하고 효율적인 고로쇠나무 수액 출수량을 예측할 수 있고, 이러한 고로쇠나무 수액의 생산량 예측으로 산간 농가들의 효율적인 노동력 활용과 고로쇠 수액의 품질관리를 개선할 수 있는 효과가 있다. claims: 복수의 센서가 설치되어 복수의 환경정보를 얻으며 고로쇠 수액이 저장되는 스마트 집수조;상기 스마트 집수조에서 보내온 복수의 환경정보와 고로쇠 수액 출수량 정보및 기상청의 기상환경 정보가 입력되는 데이터 입력부;상기 데이터 입력부에 입력된 정보들을 머신러닝 알고리즘의 학습 데이터로 활용하기 위해 전처리를 수행하는 데이터 전처리부;고로쇠 수액 출수량을 예측하기 위해 복수의 인공신경망 트리 모델을 구성하며, 구축된 복수의 인공신경망 트리 모델은 상기 데이터 전처리부의 데이터를 입력값으로 하여 상기 환경정보와 고로쇠 수액 출수량의 상관관계를 분석하여 각각의 예측을 진행하고, 예측 수액 출수량을 출력값으로 하여 예측 결과를 도출하는 수액 출수량 예측모델 생성부; 및,상기 수액 출수량 예측모델 생성부의 복수의 예측 결과를 다수결의 원칙으로 처리하여 최종 고로쇠 수액의 예측 출수량을 산출하는 수액 출수량 산출부;를 포함하는 것을 특징으로 하는 고로쇠 수액 출수량 예측 시스템., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

169/1150 Row 169: application_number: 1020200000111, combined_string: invention_title: 생산성이 현저히 증진된 일본잎갈나무 조직배양 묘목의 생산방법 abstract: 본 발명에서는 체세포배의 발아 및 재분화 촉진 공정 및 순화묘 생장 촉진 공정을 통하여 생산성이 현저히 증진된 일본잎갈나무 조직배양 묘목의 생산방법이 개시된다. 본 발명에 따른 일본잎갈나무 조직배양 묘목의 생산방법은 산림조림용 일본잎갈나무 조직배양묘 대량생산 시스템으로 효율적인 적용이 가능하다. 또한 본 발명에 따른 일본잎갈나무 묘목은 생장이 양호한 건전 순화묘이어서 대량 산지조림용에 활용성이 높다. claims: i) 일본잎갈나무 체세포배를 준비하는 단계; ii) 발아배지 상에 필터페이퍼를 올려놓은 후 일본잎갈나무 체세포배를 치상하여 배양하여 발아시키는 단계; iii) 발아체를 필터페이퍼가 없는 발아배지 상에 옮겨서 배양하여 재분화하여 유식물체를 얻는 단계; 및 iv) 유식물체를 80~90%의 습도가 유지되는 순화용기 내 인공토양에 이식하여 하이포넥스를 처리하여 배양하여 순화묘를 얻는 단계;를 포함하는 일본잎갈나무 조직배양 묘목의 생산방법.제 1항 내지 제 11항 중 어느 한 항에 따른 방법에 의해 생산된 일본잎갈나무 묘목., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

170/1150 Row 170: application_number: 1020190166857, combined_string: invention_title: 배 대목의 증식을 위한 조직배양 배지 조성물 및 이의 이용 abstract: 본 발명은 배 대목, 구체적으로 배 왜화성 대목의 증식을 위한 조직배양 배지 조성물 및 이의 이용에 관한 것이다. 본 발명에 따른 조직배양 배지 조성물은 배의 왜화성 대목 계통에서 92%의 뿌리 형성을 나타낼 뿐만 아니라, 배양묘의 순화 과정에서 식물체의 높이 및 크기가 50% 이상 향상되는 등 전반적인 식물체 활력을 개선하고 우량 개체의 비율이 높아지는 효과가 있다. 이에, 본 발명은 묘목의 대량증식 및 순화에 적용시 경제적으로 유리하며, 뿌리가 발생하지 않아 어려움을 겪었던 유전자원의 증식 및 보존에 적용할 수 있다. claims: 배 왜화성 대목의 조직배양 배지 조성물로서,상기 배지 조성물은 배지 조성물 1리터당 MS(Murashige and Skoog) 배지 또는 LS(Linsmaier and Skoog) 배지 중 어느 하나인 배지 0.9 내지 1.3g, IBA(Indole-3-butyric acid) 0.4 내지 0.6ml, NAA(Naphthalene acetic acid) 0.4 내지 0.6ml, 수크로스(sucrose) 10 내지 20g 및 아가(agar) 7 내지 11g을 포함하는, 배지 조성물.제1항 내지 제5항 중 어느 한 항의 배지 조성물에서 배 왜화성 대목을 배양하는 단계를 포함하는, 조직배양 방법., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

171/1150 Row 171: application_number: 1020190162916, combined_string: invention_title: 편백나무 내장판넬을 구비한 수면캡슐장치 abstract: 편백나무 내장판넬을 구비한 수면캡슐장치가 개시된다. 개시된 편백나무 내장판넬을 구비한 수면캡슐장치는, 사용자의 신장 길이보다 수평방향으로 긴 사각박스형태로 이루어지며 일측면에 개방부를 구비한 캡슐본체와, 상기 캡슐본체와 힌지에 의해 연결되어 상방 회동동작 또는 하방회동동작에 의해 상기 개방부를 개폐하는 플랩도어로 구성된 수면캡슐; 상기 수면캡슐의 내부로 냉풍을 공급하는 냉풍기; 상기 수면캡슐의 내부로 온풍을 공급하는 온풍기;를 포함하며, 상기 냉풍기와 상기 온풍기의 구동에 따라, 상기 수면캡슐 내부의 온도가 일정하게 유지되도록 구성되며, 상기 캡슐본체는, 외관을 형성하는 금속판넬로 이루어진 골격프레임; 상기 골격프레임의 내측에 설치되어 단열이 이루어지도록 단열재; 상기 단열재의 내측에 설치되어 상기 수면캡슐의 내장재로서 기능하며, 피톤치드가 다량 함유된 편백나무 내장판넬;을 포함하는 것을 특징으로 한다. claims: 사용자의 신장 길이보다 수평방향으로 긴 사각박스형태로 이루어지며, 4개의 측면 중 사용자의 신장보다 길도록 구성된 일측면에 개방부를 구비한 캡슐본체와, 상기 캡슐본체와 힌지에 의해 연결되어 상방 회동동작 또는 하방회동동작에 의해 상기 개방부를 개폐하는 플랩도어로 구성되어 적층가능하도록 구성된 수면캡슐;상기 수면캡슐의 내부로 냉풍을 공급하는 냉풍기;상기 수면캡슐의 내부로 온풍을 공급하는 온풍기;를 포함하며, 상기 냉풍기와 상기 온풍기의 구동에 따라, 상기 수면캡슐 내부의 온도가 일정하게 유지되도록 구성되며, 상기 캡슐본체는, 외관을 형성하는 금속판넬로 이루어진 골격프레임;상기 골격프레임의 내측에 설치되어 단열이 이루어지도록 단열재;상기 단열재의 내측에 설치되어 상기 수면캡슐의 내장재로서 기능하며, 피톤치드가 다량 함유된 편백나무 내장판넬;을 포함하며, 상기 캡슐본체에는 외부공기와 내부공기가 교환되어 상기 캡슐본체 내부의 환기가 이루어지도록 하는 환풍구가 구비되며, 상기 환풍구는 상기 골격프레임과 상기 단열재에 형성된 통기공이 구성되고, 상기 캡슐본체의 외면에는 통기그릴이 설치되며, 상기 편백나무 내장판넬에는 전체영역에 다수의 환기공이 형성되도록 구성되며, 상기 편백나무 내장판넬과 상기 단열재는 서로 이격되게 설치되되, 상기 편백나무 내장판넬과 상기 단열재의 이격공간에는 상기 통기공과 상기 다수의 환기공을 연결하는 덕트부재가 설치되도록 구성되며, 상기 덕트부재는 일면에 상기 통기공과 일치하는 제1통공이 구비되고, 타면에는 상기 편백나무 내장판넬에 형성된 상기 다수의 환기공을 모두 커버하는 제2통공을 포함하도록 구성되어, 상기 통기공을 통해 상기 제1통공으로 유입된 공기가 상기 제2통공을 통해 퍼져 상기 다수의 환기공으로 전달되도록 구성되며, 상기 플랩도어의 외면에는 사용자가 파지하여 상기 플랩도어를 회동시키기 위한 손잡이부가 설치되도록 구성되며, 상기 손잡이부는 상기 플랩도어의 외면에 고정설치되는 회전지지부와, 상기 회전지지부에 대해 힌지핀에 의해 힌지가능하게 설치되며 사용자가 파지하도록 구성된 손잡이부재를 포함하도록 구성되며, 상기 손잡이부는 상기 수면캡슐을 복수개 상하로 적층하여 복수층으로 구성하는 경우, 사용자가 하층의 수면캡슐의 플랩도어에 설치된 손잡이부를 딛고 상층의 수면캡슐로 올라 입실할 수 있도록 상기 손잡이부재가 상기 플랩도어에 대해 직각되게 90도 펼쳐진 다음 더 이상 회동되지 않게 상기 손잡이부재를 지지하는 회전규제부를 더 포함하도록 구성되는 것을 특징으로 하는 수면캡슐장치., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

172/1150 Row 172: application_number: 1020190160618, combined_string: invention_title: 비부착성 패류의 고밀도 인공종묘 생산용 채묘수조 abstract: 본 발명에 따른 하단부가 교체 가능한 채묘수조는 비부착성 패류의 인공종묘 생산을 위한 채묘수조에 있어서, 상기 채묘수조의 상단부가 하단부 보다 넓게 형성되고, 상기 채묘수조의 외주면은 지지대에 대응되게 형성되고, 상기 하단부에 메쉬가 위치하는 복수의 프레임이 구비될 수 있다. claims: 비부착성 패류의 인공종묘 생산을 위한 채묘수조에 있어서,상기 채묘수조의 상단부가 하단부 보다 넓게 형성되고,상기 채묘수조의 외주면은 지지대에 대응되게 형성되고,상기 하단부에 메쉬가 위치하는 복수의 프레임이 구비된, 하단부가 교체 가능한 채묘수조., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

173/1150 Row 173: application_number: 1020190160940, combined_string: invention_title: 비부착성 패류의 고밀도 인공종묘 생산용 채묘수조 abstract: 본 발명에 따른 하단부가 교체 가능한 채묘수조는 비부착성 패류의 인공종묘 생산을 위한 채묘수조에 있어서, 상기 채묘수조의 상단부가 하단부 보다 넓게 형성되고, 상기 채묘수조의 외주면은 지지대에 대응되게 형성되고, 상기 하단부에 메쉬가 위치하는 복수의 프레임이 구비될 수 있다. claims: 비부착성 패류의 인공종묘 생산을 위한 채묘수조에 있어서,상기 채묘수조의 상단부가 하단부 보다 넓게 형성되고,상기 채묘수조의 외주면은 지지대에 대응되게 형성되고,상기 하단부에 메쉬가 위치하는 복수의 프레임이 구비된, 하단부가 교체 가능한 채묘수조., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

174/1150 Row 174: application_number: 1020190160436, combined_string: invention_title: 고로쇠수액 염수 제조방법 abstract: 본 발명은 고로쇠수액의 제조방법에 관한 것으로, (a) 고로쇠수액을 저장조에 충전한 후 1 ~ 10일간 정치하는 단계와; (b) 상기 정치된 고로쇠수액을 자외선 살균 및 필터링하는 단계와; (c) 상기 필터링된 고로쇠수액에 천일염 첨가하여 숙성하는 단계로 구성됨으로써, 고로쇠수액 염수를 활용하여 일반 된장, 간장에 부족한 칼슘, 칼륨, 마그네슘, 나트륨 등 각종 영양소와 미네랄을 보충하고 풍미가 개선된 고로쇠 된장, 고로쇠 간장을 대량 생산할 수 있는 효과가 있다. claims: (a) 고로쇠수액을 저장조에 충전한 후 1 ~ 10일간 정치하는 단계와;(b) 상기 정치된 고로쇠수액을 자외선 살균 및 필터링하는 단계와;(c) 상기 필터링된 고로쇠수액에 천일염 첨가하여 숙성하는 단계로 이루어지되,상기 (a)단계는 직경 10 ~ 50㎜의 세라믹 볼과 직경 3 ~ 5㎜의 마그네슘 볼을 고로쇠수액이 충전된 저장조에 충전하는 (a)-1 단계를 더 포함하되,상기 세라믹 볼은 고로쇠수액 1㎥에 대하여 세라믹 볼 50 ~ 75개를 충전하고, 마그네슘 볼은 고로쇠수액 1㎥에 대하여 1 ~ 10개를 충전하고,상기 세라믹 볼은 항균 세라믹 볼 100 중량부에 대하여, 맥반석 세라믹 볼 30 ~ 45 중량부 및 화산석 세라믹 볼 10 ~ 20 중량부로 구성되고,상기 (c)단계는,(c)-1 필터링된 고로쇠수액에 염도 21.5 ~ 23.5 보메가 되도록 천일염을 첨가한 후 교반한 다음 12 ~ 18일간 0 ~ 15℃에서 정치하여 1차 고로쇠수액 염수를 제조하는 단계와;(c)-2 상기 1차 고로쇠수액 염수의 상등액을 염도 19.5 ~ 20.8 보메가 되도록 필터링한 후 12 ~ 18일간 0 ~ 15℃에서 정치하여 2차 고로쇠수액 염수를 제조하는 단계와;(c)-3 상기 2차 고로쇠수액 염수의 상등액을 염도 17.5 ~ 18.5 보메가 되도록 필터링하여 최종 고로쇠수액 염수를 제조하는 단계로 이루어지는 것을 특징으로 하는 고로쇠수액 염수 제조방법., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

175/1150 Row 175: application_number: 1020190151636, combined_string: invention_title: 커피 추출물 및 부산물에 기반한 생분해성 육묘 포트 제작 방법 및 이에 의해 제작된 생분해성 육묘 포트 abstract: 본 발명은 커피 부산물과 커피 추출물의 원료를 활용하여 육묘 포트를 형성함과 아울러 육묘 식물의 영양 성분으로 제공할 수 있어 친환경성과 경제성을 확보할 수 있고, 별도의 상토 사용 없이도 파종과 발아가 가능하며, 식재 후 생분해되어 토양에 영양분으로서 기능할 수 있는, 커피 추출물 및 부산물에 기반한 생분해성 육묘 포트 제작 방법 및 이에 의해 제작된 생분해성 육묘 포트에 관한 것이다. 본 발명에 따르면, 제1 원료로서 커피부산물 및 코코피트 중 적어도 하나, 및 제2 원료로서 펄프를 마련하는 육묘포트 원료 마련 단계; 상기 제1 및 제2 원료를 물에 투입하여 교반하고 유동화(liquefaction)하여 유동성 재료로 제조하는 유동화 단계; 상기 유동화 된 유동성 재료를 육묘 포트 형상으로 성형하기 위한 성형 단계; 및 커피 부산물로부터 추출한 상토대체물을 물과 혼합하여 상기 성형 단계에서 성형된 육묘 포트에 충전하는 상토대체물 충전 단계;를 포함하는 것을 특징으로 하는 생분해성 육묘 포트 제작 방법이 제공된다. claims: 생분해가 가능한 육모 포트(pot) 제작 방법으로서,제1 원료로서 커피부산물 및 코코피트 중 적어도 하나, 및 제2 원료로서 펄프를 마련하는 육묘포트 원료 마련 단계;상기 제1 및 제2 원료를 물에 투입하여 교반하고 유동화(liquefaction)하여 유동성 재료로 제조하는 유동화 단계;상기 유동화 된 유동성 재료를 육묘 포트 형상으로 성형하기 위한 성형 단계; 및커피 부산물로부터 추출한 상토대체물을 물과 혼합하여 상기 성형 단계에서 성형된 육묘 포트에 충전하는 상토대체물 충전 단계;를 포함하는 것을 특징으로 하는생분해성 육묘 포트 제작 방법.청구항 1 내지 청구항 5중 어느 한 항에 따른 생분해성 육묘 포트 제작 방법에 의해 제작된 생분해성 육묘 포트.커피부산물과 코코피트 중 적어도 하나 및 펄프로 이루어지는 단일 또는 트레이형의 육묘 포트 본체; 및커피부산물에서 추출한 섬유질을 포함하여 상기 육묘 포트 본체에 충전되는 상토대체물;을 포함하는 것을 특징으로 하는생분해성 육묘 포트., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

176/1150 Row 176: application_number: 1020190147330, combined_string: invention_title: 목재 침대 프레임 abstract: 본 발명은 목재 침대 프레임에 관한 것으로서, 편백나무 등과 같은 목재 재질로 제작됨으로써 친환경적인 생산이 이루어질 수 있으며, 통풍성 향상에 따른 매트리스 유지관리 용이 및 숙면을 취할 수 있도록 하기 위한 것이다.이를 실현하기 위한 본 발명은, 사각형상으로 제작되는 목재 재질의 프레임 본체(10) 상부에는 다수의 수평판재(20)가 상호 일정 이격간격(d)을 이루어 안착 구성되며; 상기 프레임 본체(10)의 일측에는 침대 머리판을 이루는 다수의 수직판재(30)가 상호 일정 이격간격을 이루어 구성되고; 상기 수직판재(30)의 지지를 위해 배면에는 머리판 지지목(40)이 수평방향으로 결합 구성되며; 상기 프레임 본체(10)를 일정 높이로 지지하기 위해 하부 모서리 부위에는 지지다리(11)가 구성된 것을 특징으로 한다. claims: 사각형상으로 제작되는 목재 재질의 프레임 본체(10) 상부에는 다수의 수평판재(20)가 상호 일정 이격간격(d)을 이루어 안착 구성되며;상기 프레임 본체(10)의 일측에는 침대 머리판을 이루는 다수의 수직판재(30)가 상호 일정 이격간격을 이루어 구성되고,상기 수직판재(30)의 지지를 위해 배면에는 머리판 지지목(40)이 수평방향으로 결합 구성되며,상기 프레임 본체(10)를 일정 높이로 지지하기 위해 하부 모서리 부위에는 지지다리(11)가 구성되며,상기 프레임 본체(10), 수평판재(20) 및 수직판재(30)는 편백나무 재질로 이루어지고,상기 머리판 지지목(40)에는 인체에 유익한 기능성 향기를 발산하는 향발산 쫄대(50)의 삽입이 가능하도록 삽입공(41)이 형성되며, 상기 머리판 지지목(40)에는 향발산 효율 향상을 위한 다수의 향발산공(42)이 형성되며,상기 향발산 쫄대(50)는 우레탄 수지, 나노은, 계피나무 껍질 추출액, 황화알릴, 아로마 오일, 회향유, 프로필렌글리콜, 코발트 파우더의 혼합 조성을 이루는 것을 특징으로 하는 목재 침대 프레임., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

177/1150 Row 177: application_number: 1020190141644, combined_string: invention_title: ＩＣＴ 및 ＩｏＴ를 이용한 스마트 양묘 시스템, 그리고 이를 위한 하이브리드 양묘장 abstract: 본 발명은 ICT 및 IoT를 이용한 스마트 양묘 시스템, 그리고 이를 위한 하이브리드 양묘장에 관한 것이다. 본 발명은, 양묘장(10) 상단에 형성됨으로써 양묘장(10) 내부의 트레이(200)에 파종된 식물에 대해서 1년 이후 훈련장으로 옮기지 않고 위치 변동 없이 온실에 해당하는 양묘장(10)을 외부 환경으로 변경시켜 훈련시킬 수 있도록 양묘장(10)의 천장을 개방하도록 하기 위해 차양 비닐막(110)과 포켓부(120)로 구성되는 롤러장치(100); 및 포켓부(120) 내부의 권치 장치에 대한 제어를 통해 포켓부(120) 내부로 차양 비닐막(110)이 롤업 되거나 포켓부(120) 외부로 차양 비닐막(110)이 롤다운 하도록 제어하되, 양묘장(10)의 천장 개폐 구간을 비닐을 권치 장치를 이용하여 감아올린 후 양묘장(10) 탑부의 포켓부(120)로 삽입된 천장을 오픈시킴으로써, 야외 조건처럼 조성할 수 있어서 파종된 식물을 옮겨심지 않아도 노지 적응훈련시키는 것이 가능하도록 하는 제어부(460); 를 포함하는 것을 특징으로 한다.본 발명의 실시예에 따른 ICT 및 IoT를 이용한 스마트 양묘 시스템, 그리고 이를 위한 양묘장은, 천창개폐구간을 비닐을 롤업 및 롤다운을 수행하는 권취장치를 이용하여 감아올린 후 탑부의 홈부에 삽입하여 끼움으로써 완전 오픈시킴으로써, 야외 조건처럼 조성할 수 있어 파종된 식물을 옮겨심지 않아도 노지 적응훈련시키는 것이 가능하도록 하는 효과가 있고, 100% 완전 오픈 상태에서도 ICT 관리를 통해 생존율을 더 높일 수 있을 뿐만 아니라, 혹서, 동파 등의 비상 상황이 발생하는 경우 야외 노지 조건을 완화시켜 생존율을 높일 수 있도록 하며, 양묘장 내부에 파종을 위한 트레이에 RF 태그를 통해 각 트레이별 관리가 가능하고, 개개 묘목이 아니라 트레이 단위로 관리를 수행할 수 있는 효과가 있다. claims: 양묘장(10) 상단에 형성됨으로써 양묘장(10) 내부의 트레이(200)에 파종된 식물에 대해서 1년 이후 훈련장으로 옮기지 않고 위치 변동 없이 온실에 해당하는 양묘장(10)을 외부 환경으로 변경시켜 훈련시킬 수 있도록 양묘장(10)의 천장을 개방하도록 하기 위해 차양 비닐막(110)과 포켓부(120)로 구성되는 롤러장치(100); 및포켓부(120) 내부의 권치 장치에 대한 제어를 통해 포켓부(120) 내부로 차양 비닐막(110)이 롤업 되거나 포켓부(120) 외부로 차양 비닐막(110)이 롤다운 하도록 제어하되, 양묘장(10)의 천장 개폐 구간을 비닐을 권치 장치를 이용하여 감아올린 후 양묘장(10) 탑부의 포켓부(120)로 삽입된 천장을 오픈시킴으로써, 야외 조건처럼 조성할 수 있어서 파종된 식물을 옮겨심지 않아도 노지 적응훈련시키는 것이 가능하도록 하는 제어부(460); 를 포함하는 것을 특징으로 하며, 제어부(460)는, 상하로 구분된 수평/수직 유동팬(420)의 상부 수평/수직 유동팬(420-1) 및 하부 수평/수직 유동팬(420-2)에 대해서 작동 온(On) 명령을 제공함으로써 풍향이 방향이 반대 방향으로 형성된 상부 수평/수직 유동팬(420-1) 및 하부 수평/수직 유동팬(420-2)이 상부 수직 격벽 장치(420a) 및 하부 수직 격벽 장치(430b)에 의해 하나의 미리 설정된 구역에 대해서만 수평 및 수직 방향의 바람을 형성할 수 있도록 제어하고, 이후, 피드백 정보로 제 2 습도 센서(483)에 의해 측정된 습도 센싱정보가 미리 설정된 습도 미만이거나 제 2 온도 센서(484)에 의해 측정된 온도 센싱정보가 미리 설정된 온도 미만에 해당하는 경우 상부 수평/수직 유동팬(420-1) 및 하부 수평/수직 유동팬(420-2)에 대한 동작 오프(OFF)를 제어하도록 구성되는 것을 특징으로 하는 ICT를 이용한 스마트 양묘 시스템., Ltext: 임업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

178/1150 Row 178: application_number: 1020190140209, combined_string: invention_title: 새싹삼 판매 전용 쇼케이스 와 유통 시스템 abstract: 본 발명은 가전형 다기능 새싹삼 재배기를 일반 가정집이나 국내는 물론 해외의 영업 매장에 설치하고 현재 유통 되고 있는 1~2년생 새싹삼은 물론이고 깊은 산속에서나 볼 수있는 5년근 10년근 등 고가의 다년근 새싹 산양삼을 추가하여 줄기와 뿌리가 활기차게 살아 있는 새싹 산양삼을 계절에 관계없이 소비자에게 제공하는 새로운 새싹 산양삼 유통 시스템애 관한 것이다. claims: 가전형 새싹산삼 다기능 재배기와 새싹삼 유통 시스템으로서, 다기능 재배기는 재배실과 보관실을 온도 차이로 나누어 각 사용하는 기능도 있고 재배실 온도(25℃)와 보관실 온도(12℃)조절만으로 재배나 보관의 한가지 기능으로 재배실 전체를 사용할 수도 있는 복합 다기능 재배기로 일반 가정이나 국내, 해외 영업장 매장에 설치하는 단계:새싹삼을 재배하는 농장(100)에서 재배한 새싹삼이 심어진 재배틀 박스와 씨눈이 싹튼 산양삼 종묘를 식재한 재배틀 박스를 유통 업자에게 납품(200)하는 단계:유통업자는 냉장장치 자동차에 12℃ 전후의 안전한 온도로 이동하여 다기능 재배기가 설치된 가정집이나 국내 영업장, 수출업체에 납품하는 단계로 이루어지는 가전형 새싹산삼 다기능 재배기와 새싹삼 유통 시스템., Ltext: 임업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

179/1150 Row 179: application_number: 1020190139435, combined_string: invention_title: 편백오일 추출장치 및 추출방법 abstract: 본 발명은 편백오일 추출장치 및 이를 이용한 편백오일 추출방법에 관한 것으로, 그 구성은, 파쇄한 편백나무 원목을 적재할 공간이 마련되는 원료통; 상기 원료통의 상단에 구비되어 원료통 내부의 온도를 감지하는 온도계; 상기 원료통 하방으로 스팀을 공급하는 스팀발생기; 상기 원료통에서 생성된 수증기를 응축시킬 다수개의 제 1 수증기관과, 제 1 수증기관 주변에 마련되는 제 1 냉각부로 구성되는 제 1 냉각기; 상기 제 1 냉각기에 의해 생성된 제 1 응축수를 한번 더 응축시킬 나선형의 제 2 수증기관과, 제 2 수증기관 주변에 마련되는 제 2 냉각부와, 일측 하단에 냉각부를 채울 액체 또는 기체를 공급하는 공급부로 구성되는 제 2 냉각기; 상기 제 2 냉각기에서 생성된 제 2 응축수를 물과 오일로 분리시키는 오일분리기; 상기 원료통과 상기 스팀발생기를 연결하며, 일측에 제 1 밸브가 마련되는 제 1 유로; 상기 원료통과 상기 제 1수증기관을 연결하며, 일측에 제 2 밸브가 마련되는 제 2유로; 상기 제 1 수증기관과 상기 제 2 수증기관을 내부로 연결하고 상기 제 1 냉각부와 상기 제 2 냉각부를 외부로 연결하는 제 3 유로; 상기 제 2 냉각기와 상기 오일분리기를 연결하는 제 4 유로;를 포함하여 구성되는 것을 특징으로 하며, 상기 제 2 밸브는 원료통의 온도가 110 내지 115℃에 도달하면 개방하는 것을 특징으로 한다. claims: 파쇄한 편백나무 원목을 적재할 공간이 마련되는 원료통;상기 원료통의 상단에 구비되어 원료통 내부의 온도를 감지하는 온도계;상기 원료통 하방으로 스팀을 공급하는 스팀발생기;상기 원료통에서 생성된 수증기를 응축시킬 다수개의 제 1 수증기관과, 제 1 수증기관 주변에 마련되는 제 1 냉각부로 구성되는 제 1 냉각기;상기 제 1 냉각기에 의해 생성된 제 1 응축수를 한번 더 응축시킬 나선형의 제 2 수증기관과, 제 2 수증기관 주변에 마련되는 제 2 냉각부와, 일측 하단에 냉각부를 채울 액체 또는 기체를 공급하는 공급부로 구성되는 제 2 냉각기;상기 제 2 냉각기에서 생성된 제 2 응축수를 물과 오일로 분리시키는 오일분리기;상기 원료통과 상기 스팀발생기를 연결하며, 일측에 제 1 밸브가 마련되는 제 1 유로;상기 원료통과 상기 제 1수증기관을 연결하며, 일측에 제 2 밸브가 마련되는 제 2 유로;상기 제 1 수증기관과 상기 제 2 수증기관을 내부로 연결하고 상기 제 1 냉각부와 상기 제 2 냉각부를 외부로 연결하는 제 3 유로;상기 제 2 냉각기와 상기 오일분리기를 연결하는 제 4 유로;를 포함하여 구성되며,상기 제 2 냉각부가 8℃일 때, 상기 제 1 응축수를 상기 제 2 수증기관으로 이송하고,상기 제 2 밸브는 원료통의 온도가 110 내지 115℃에 도달하면 개방하는 것을 특징으로 하는 편백오일 추출장치를 이용하는 방법에 있어서,당일 벌목한 편백나무 원목을 밀봉하여 이동시키는 제 1단계;상기 밀봉하여 이동시킨 편백나무 원목을 일정한 크기로 파쇄한 뒤, 밀봉하여 이동시키는 제 2단계;상기 밀봉하여 이동시킨 파쇄된 편백나무 원목을 원료통에 적재하는 제 3단계;상기 원료통에 스팀을 공급하는 제 4단계;공급부에 냉각부를 채울 액체 또는 기체를 공급하는 제 5 단계;상기 원료통이 일정 온도에 도달하면, 원료통에서 생성된 수증기를 제 1 수증기관으로 이송하여 제 1 응축수를 제조하는 제 6 단계;상기 제 1 응축수를 제 2 수증기관으로 이송하여 제 2 응축수를 제조하는 제 7단계;상기 제 2 응축수를 오일분리기로 이송하여 물과 오일로 분리하는 제 8단계;상기 분리된 오일을 곧바로 밀봉하는 제 9단계를 포함하여 구성되며,상기 제 2단계에서, 상기 편백나무 원목은 1cm 크기로 파쇄하고,상기 제 3단계에서, 상기 원료통에 넣는 편백나무 원목은 200 내지 300Kg 를 적재하고,상기 제 4단계에서, 상기 스팀은 편백나무 원목 1중량부에 대하여 0.4 내지 0.6중량부를 공급하는 것을 특징으로 하는 편백오일 추출방법., Ltext: 임업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

180/1150 Row 180: application_number: 1020210067226, combined_string: invention_title: 어류의 질병여부를 판단하고 포획할 수 있는 어류질병 감지장치 abstract: 어류질병 감지장치 및 그 감지방법이 개시된다. 본 발명에 따른 어류질병 감지장치는, 어류에 대한 질병의 종류와 각각의 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 움직임패턴 저장부; 가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 영상신호 수신부; 영상신호 수신부에 의해 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 움직임패턴 분석부; 움직임 분석부에 의해 분석되는 각각의 어류의 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 어류 추출부; 어류 추출부에 의해 추출된 어류에 대응하는 움직임패턴을 움직임패턴 저장부에 저장된 움직임패턴과 비교하는 움직임패턴 비교부; 및 움직임패턴 비교부에 의해 비교되는 결과에 따라 어류 추출부에 의해 추출된 어류에 대한 질병 여부를 판단하는 어류질병 판단부;를 포함하는 것을 특징으로 한다. claims: 어류에 대한 질병의 종류와 각각의 상기 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 움직임패턴 저장부;가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 영상신호 수신부; 상기 영상신호 수신부에 의해 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 움직임패턴 분석부;상기 움직임 분석부에 의해 분석되는 각각의 어류의 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 어류 추출부;상기 어류 추출부에 의해 추출된 어류에 대응하는 움직임패턴을 상기 움직임패턴 저장부에 저장된 움직임패턴과 비교하는 움직임패턴 비교부;상기 움직임패턴 비교부에 의해 비교되는 결과에 따라 상기 어류 추출부에 의해 추출된 어류에 대한 질병 여부를 판단하는 어류질병 판단부;상기 어류 추출부에 의해 추출된 어류의 위치를 확인하는 어류위치 확인부; 및상기 어류위치 확인부에 의해 확인되는 위치에 대응하여 어류를 포획하는 어류 포획부;를 포함하는 것을 특징으로 하는, 어류의 질병여부를 판단하고 포획할 수 있는, 어류질병 감지장치., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

181/1150 Row 181: application_number: 1020200109970, combined_string: invention_title: 이동바늘을 갖는 인조 미끼 abstract: 본 발명은 수중에서 주꾸미 또는 갑오징어 등의 두족류를 용이하게 잡을 수 있도록 하는 이동바늘을 갖는 인조 미끼에 관한 것으로, 챔질을 하는 과정에서 본체의 일단부에 위치되어 있던 이동바늘이 가이드홀을 따라 본체의 타단부 방향으로 이동되도록 구성되므로, 본체 주변의 두족류는 갑자기 튀어나온 이동바늘에 용이하게 포획되는 효과가 있다. claims: 본체;상기 본체의 내부에 위치되는 탄성부; 및상기 탄성부에 연결된 상태로 상기 본체의 내부에 위치되는 바늘부재를 포함하고,상기 바늘부재는:상기 본체의 내부 길이방향을 따라 이동 가능하도록 위치되는 와이어;상기 본체의 일단부를 향하도록 위치되는 상기 와이어의 일측에 상기 본체의 측부 방향으로 돌출 형성되는 이동바늘; 및상기 본체의 타단부를 향하도록 위치되는 상기 와이어의 타측에 상기 본체의 타단부를 관통하도록 돌출되어 낚싯줄에 연결되는 연결부를 포함하고,상기 탄성부는 상기 본체 내부의 일단부 또는 타단부에 위치되되 상기 와이어와 연결된 상태로 상기 이동바늘이 상기 본체의 일단부와 가까워지는 방향으로 탄성 압력을 가하도록 구성되고,상기 탄성부의 탄성 압력이 상기 와이어로 전달되어, 상기 이동바늘이 상기 본체의 일단부 방향으로 이동되면, 상기 이동바늘은 상기 본체의 내부에 위치되고,상기 탄성 압력보다 강한 외부 압력이 상기 연결부에 가해져서, 상기 이동바늘이 상기 본체의 타단부 방향으로 이동되면, 상기 이동바늘은 상기 본체의 측부를 관통하여 외부로 돌출되는 것을 특징으로 하는 이동바늘을 갖는 인조 미끼.본체;상기 본체의 내부에 위치되는 탄성부; 및상기 탄성부에 연결된 상태로 상기 본체의 내부에 위치되는 바늘부재를 포함하고,상기 바늘부재는:상기 본체의 내부 길이방향을 따라 이동 가능하도록 위치되는 와이어;상기 본체의 일단부를 향하도록 위치되는 상기 와이어의 일측에 상기 본체의 외부로 돌출 형성되는 이동바늘; 및상기 본체의 타단부를 향하도록 위치되는 상기 와이어의 타측에 상기 본체의 타단부를 관통하도록 돌출되어 낚싯줄에 연결되는 연결부를 포함하고,상기 탄성부는 상기 본체 내부의 일단부 또는 타단부에 위치되되 상기 와이어와 연결된 상태로 상기 이동바늘이 상기 본체의 일단부와 가까워지는 방향으로 탄성 압력을 가하도록 구성되고,상기 탄성부의 탄성 압력이 상기 와이어로 전달되면, 상기 본체의 외부로 돌출된 상기 이동바늘이 상기 본체의 일단부 방향으로 이동되고,상기 탄성 압력보다 강한 외부 압력이 상기 연결부에 가해지면, 상기 본체의 외부로 돌출된 상기 이동바늘이 상기 본체의 타단부 방향으로 이동되는 것을 특징으로 하는 이동바늘을 갖는 인조 미끼., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

182/1150 Row 182: application_number: 1020200106869, combined_string: invention_title: 지중작물 수확 및 비닐수거 겸용장치 abstract: 본 발명은 트랙터 등 견인수단에 견인되어 지중작물을 수확할 수 있으며, 이에 더하여 밭두둑에 덮어 놓은 비닐을 수거하도록 구성되는 지중작물 수확 및 비닐수거 겸용장치에 관한 것으로, 견인수단에 연결되는 연결부, 하부에 수확공간이 형성되도록 상호 이격되는 한 쌍의 측판 및 상기 측판과 직교하는 방향으로 상기 한 쌍의 측판 간을 연결하는 하나 이상의 지지대를 포함하는 본체; 상기 수확공간에 구성되어 땅속 작물을 수확하도록 구성되는 수확부; 및 상기 본체의 후단부에 배치되는 것으로, 상기 측판 또는 지지대 중 하나 이상에 결합되며 지중에 고정된 비닐을 수거하도록 구성되는 비닐수거부;를 포함하여 트랙터 등 견인수단에 견인되어 지중작물을 수확하는 과정에서 지중작물로부터 이물질이 자동으로 분리되도록 구성되고, 이에 더하여 밭두둑에 덮여 고정된 비닐을 순차적으로 굴착하면서 동시에 권취되도록 하는 수거방식이 적용되어 비닐 수거에 대한 노동력이 절감되고 생산성이 향상되며 또한, 수거된 비닐을 자동으로 지면에 투척하도록 구성하여 별도의 인력소보가 배제될 수 있으며 작업의 연속성이 확보되어 작업효율이 크게 향상되는 효과가 있는 지중작물 수확 및 비닐수거 겸용장치에 관한 것이다. claims: 견인수단에 연결되는 연결부, 하부에 수확공간이 형성되도록 상호 이격되는 한 쌍의 측판 및 상기 측판과 직교하는 방향으로 상기 한 쌍의 측판 간을 연결하는 하나 이상의 지지대를 포함하는 본체;상기 수확공간에 구성되어 땅속 작물을 수확하도록 구성되는 수확부; 및상기 본체의 후단부에 배치되는 것으로, 상기 측판 또는 지지대 중 하나 이상에 결합되며 지중에 고정된 비닐을 수거하도록 구성되는 비닐수거부;를 포함하고,상기 수확부는상기 수확공간의 전방 하부에서 선단측으로 갈수록 하향되는 경사구조로 구성되며 상기 본체가 전방으로 이동함에 따라 지중작물을 채굴하도록 구성되는 채굴판; 및상기 채굴판의 후단과 연계되도록 구성되어 상기 채굴판에 의해 채굴된 지중작물을 후방으로 배출시키되, 지중작물로부터 이물을 분리시키는 배출부재;를 포함하며,상기 비닐수거부는상기 지지대로부터 후방을 향해 회전 가능한 구조로 연장되며 후단에는 한 쌍이 상호 나란하게 이격되는 제 1샤프트;한 쌍의 상기 제 1샤프트의 후단에 각각 고정되되, 상기 제 1샤프트와는 수직 구조로 배치되는 한 쌍의 제 2샤프트;한 쌍의 상기 제 2샤프트의 사이에 배치되며, 일단 보다 타단의 직경이 큰 콘 형태로 마련되고, 각 타단부가 상기 제 2샤프트에 각각 회전가능하게 결합되며 비닐이 권취되는 한 쌍의 수거부재;한 쌍의 상기 수거부재 중 하나 이상에 회전력을 제공하는 동력수단; 및한 쌍의 상기 제 1샤프트를 서로 반대되는 방향으로 회전제어하는 회전제어부;를 포함하여 구성되는 것을 특징으로 하는 지중작물 수확 및 비닐수거 겸용장치., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

183/1150 Row 183: application_number: 1020200104288, combined_string: invention_title: 어업용 로프 abstract: 본 발명은 외부에 결합된 무게추 없이 물속으로 가라앉을 수 있도록 된 새로운 구조의 어업용 로프에 관한 것이다.본 발명에 따른 어업용 로프는 합성수지재질로 구성된 복수개의 와이어(1)를 꼬아서 제작된 로프의 내부에 무게추(2)가 구비되며, 특히, 상기 무게추(2)는 길이가 긴 바형상으로 구성되고, 상기 와이어(1)는 상기 무게추(2)의 둘레부를 감싸도록 무게추(2)의 둘레부에 나선형으로 배치됨으로, 어업용 로프의 비중이 바닷물의 비중에 비해 높아져, 바닷속으로 가라앉게 된다.따라서, 로프의 둘레면에 외부에 별도로 무게추(2)를 결합할 필요가 없어서, 사용이 더욱 편리할 뿐 아니라, 둘레부에 외측으로 돌출되는 부분이 없어서, 기계를 이용하여 어업용 로프를 감아올릴 때, 로프가 기계에 걸리게 되는 것을 방지할 수 있는 장점이 있다. claims: 합성수지재질로 구성된 복수개의 와이어(1)를 꼬아서 제작된 어업용 로프에 있어서, 상기 로프의 내부에는 납재질로 구성된 무게추(2)가 구비되고,상기 무게추(2)는 길이가 긴 바형상으로 구성되고, 상기 와이어(1)는 상기 무게추(2)의 둘레부를 감싸도록 무게추(2)의 둘레부에 나선형으로 배치되고, 상기 무게추(2)의 중간부에는 무게추(2)를 관통하며 양단이 상기 와이어(1)의 외측으로 연장된 복수개의 고정철사(3)가 무게추(2)의 길이방향으로 상호 이격되도록 구비되며, 상기 고정철사(3)의 외측단은 어업용 로프의 원주방향으로 벤딩되어 상기 와이어(1)가 무게추(2)의 둘레면에 밀착되도록 가압고정하도록 하는 것을 특징으로 하는 어업용 로프., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

184/1150 Row 184: application_number: 1020200104290, combined_string: invention_title: 어업용 로프 abstract: 본 발명은 손쉽게 통발이나 주낙의 목줄을 일정한 간격으로 연결할 수 있도록 된 새로운 구조의 어업용 로프에 관한 것이다.본 발명에 따른 어업용 로프는 일정 거리마다 눈금(2)이 표시됨으로, 작업자가 로프(1)에 목줄을 연결할 때, 정확한 간격으로 목줄을 연결할 수 있는 장점이 있다.특히, 상기 눈금(2)은 표시장치(10)를 이용하여 자동으로 일정간격으로 로프(1)에 표시됨으로, 로프(1)에 눈금(2)을 표시하는 작업이 매우 용이한 장점이 있다. claims: 합성수지재질로 구성된 복수개의 로프(1)를 꼬아서 제작된 어업용 로프에 있어서, 상기 로프(1)의 중간부에는 일정한 간격으로 눈금(2)이 표시되고,상기 눈금(2)은 표시장치(20)를 이용하여 상기 로프(1)의 둘레면에 합성수지를 사출하여 형성되며, 상기 표시장치(20)는 지지대(21)와, 상기 지지대(21)에 구비되며 구동모터에 의해 구동되어 상기 로프(1)를 전방에서 후방으로 이송하는 이송로울러(22)와, 상기 지지대(21)에 구비되며 상기 로프(1)의 중간부 외주면에 합성수지를 사출하여 눈금(2)을 형성하는 사출장치(23)와, 상기 사출장치(23)의 후방에 위치되도록 상기 지지대(21)에 전후방향으로 위치조절가능하게 구비되어 상기 로프(1)의 외주면에 사출된 합성수지를 감지하는 감지센서(24)와, 상기 감지센서(24)의 신호를 수신하며 상기 이송로울러(22)와 사출장치(23)의 작동을 제어하는 제어수단(25)을 포함하며, 상기 제어수단(25)은 상기 사출장치(23)를 이용하여 로프(1)의 중간부에 합성수지가 사출되어 눈금(2)이 표시되도록 한 후, 상기 구동모터를 구동시켜 이송로울러(22)에 의해 로프(1)가 후방으로 이송되도록 하면서 상기 감지센서(24)의 신호를 감시하여, 상기 감지센서(24)에 이송로울러(22)의 외주면에 사출된 합성수지가 감지되면 상기 이송로울러(22)를 정지시키고 상기 사출장치(23)를 이용하여 로프(1)의 중간부에 합성수지를 사출하는 작업을 반복하도록 된 것을 특징으로 하는 어업용 로프., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

185/1150 Row 185: application_number: 1020200062751, combined_string: invention_title: 드론을 이용한 고기잡이장치 abstract: 본 발명은 드론을 이용한 고기잡이장치에 관한 것으로, 호수, 강 또는 바다의 수면에 부유하면서 어군 탐지, 집어, 최적의 어군 밀집 지점에 그물망 투하 및 인양, 위치이동, 수면에서의 드론 이/착륙이 가능하게 하기 위한 것이다.이를 위하여 본 발명은 그물망에 연결된 인양줄을 감거나 풀 수 있는 권취기가 설치되고 원격 제어신호 또는 미리 설정된 제어신호에 따라 권취기의 동작을 제어하는 제어부를 구비하여 원격 제어신호 또는 미리 설정된 제어신호에 의해 상기 권취기를 제어하는 드론부, 부력에 의해 호수, 강 또는 바다의 수면에 부유하여 그물망의 부표 및 수상에서의 드론 이/착륙을 위한 도킹 플랫폼을 제공하고 드론부의 권취기에서 풀리거나 감기는 인양줄의 승강 동작을 안내하는 수상 랜딩부, 및 접거나 펼침 가능한 다수 개의 탄성바와 각 탄성바 사이의 봉돌이 중심부에서부터 방사상으로 균등하게 이격되어 분산 배치되는 그물망 몸체로서 인양줄에 의해 드론부에 매달리는 형태로 승강 가능하게 설치되어 수상 랜딩부의 하부에서 수중으로 투하 또는 견인되는 절첩식 그물부를 포함하여, 현장에 직접 배를 출항시키지 않고도 최적의 어군 밀집 지점에서 효율적인 고기잡이가 가능하게 하여 배의 출항에 따른 유류비와 인건비를 획기적으로 줄일 수 있게 한다. claims: 드론몸체(11)를 바닥면에서 상부로 일정 높이 이격시켜 지지하기 위한 다수 개의 다리(12)가 구비되고, 그물망에 연결된 인양줄(13)을 감거나 풀어줄 수 있는 권취기(14)가 드론몸체(11)의 하부 중심부에 설치되고 외부에서 무선 수신되는 원격 제어신호 또는 미리 설정된 제어신호에 따라 상기 권취기(14)의 동작을 제어하는 제어부(15)를 구비하여 원격 제어신호 또는 미리 설정된 제어신호에 의해 상기 권취기(14)를 제어하는 드론부(10);공기를 주입 또는 배출하여 부피가 팽창 또는 축소되는 튜브형 몸체(21)로서 부력에 의해 호수, 강 또는 바다의 수면에 부유하여 그물망의 부표 및 수상에서의 드론 이/착륙을 위한 도킹 플랫폼을 제공하고, 수밀 구조의 전원공급장치(22)와 무선 송수신부(23)를 구비하여 상기 드론부(10)와의 무선 통신으로 데이터를 송수신하며 상기 튜브형 몸체(21)의 중앙부 빈 공간(21a)으로 상기 드론부(10)의 권취기(14)에서 풀리거나 감기는 다수 개의 인양줄(13)을 통과시켜 상기 인양줄(13)의 종단부에 연결되는 절첩식 그물부(30) 또는 어군 탐지기(41) 또는 집어등(42) 또는 영상 표출부(43)의 승강 동작을 안내하는 수상 랜딩부(20); 및 접거나 펼침 가능한 다수 개의 탄성바(31)와 각 탄성바 사이의 봉돌(32)이 중심부에서부터 방사상으로 균등하게 이격되어 분산 배치되는 그물망 몸체로서, 상기 드론부(10)에 연결된 다수 개의 인양줄(13)이 상기 수상 랜딩부(20)의 튜브형 몸체(21)의 중앙부 빈 공간(21a)을 통과하여 그물망 몸체의 둘레에 일정 간격마다 이격되게 연결되되 상기 다수 개의 인양줄(13)에 의해 상기 드론부(10)에 매달리는 형태로 승강 가능하게 설치되어 상기 드론부(10)의 비행 동작에 따라 상기 인양줄(13)을 상부로 당기거나 놓는 동작에 의해 그물망 몸체의 탄성바(31)가 접히거나 펼쳐져 상기 수상 랜딩부(20)의 하부에서 수중으로 투하 또는 견인되는 절첩식 그물부(30);를 포함하여 구성되는 것을 특징으로 하는 드론을 이용한 고기잡이장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

186/1150 Row 186: application_number: 1020200063253, combined_string: invention_title: 기포발생기 일체형 집어등 abstract: 기포발생기 일체형 집어등이 개시된다. 본 발명의 실시예에 따른 기포발생기 일체형 집어등은, 빛을 발생하여 수면 상에 조사함으로써 빛으로 물고기를 집어함과 동시에 수중에 기포를 발생시킬 수 있는 기포발생기 일체형 집어등에 관한 것으로서, 내부에 제어부 및 에어펌프를 탑재할 수 있는 수용공간이 마련되고, 분해조립이 가능한 박스형 구조의 하우징; 상기 하우징의 상부 일측에 힌지 구조에 의해 장착되는 조명제공부; 상기 하우징의 내부에 탑재되는 에어펌프, 에어펌프로부터 제공되는 압축공기를 외부로 제공하기위해 하우징의 일측면으로부터 외부로 노출되도록 장착되는 에어공급 노즐을 포함하는 기포제공부; 및 상기 하우징 내부에 장착되고, 조명제공부 및 기포제공부를 제어하는 제어부;를 포함하는 것을 을 구성의 요지로 한다.본 발명에 따르면, 빛을 발생하여 수면 상에 조사하여 빛으로 물고기를 집어함과 동시에 수중에 기포를 발생시켜 집어 효과를 극대화시킬 수 있는 기포발생기 일체형 집어등을 제공할 수 있다. claims: 빛을 발생하여 수면 상에 조사함으로써 빛으로 물고기를 집어함과 동시에 수중에 기포를 발생시킬 수 있는 기포발생기 일체형 집어등에 관한 것으로서,내부에 제어부(140) 및 에어펌프(150)를 탑재할 수 있는 수용공간이 마련되고, 분해조립이 가능한 박스형 구조의 하우징(110);상기 하우징(110)의 상부 일측에 힌지 구조(121)에 의해 장착되는 조명제공부(120);상기 하우징(110)의 내부에 탑재되는 에어펌프(150), 에어펌프(150)로부터 제공되는 압축공기를 외부로 제공하기 위해 하우징(110)의 일측면으로부터 외부로 노출되도록 장착되는 에어공급 노즐(131)을 포함하는 기포제공부(130); 및상기 하우징(110) 내부에 장착되고, 조명제공부(120) 및 기포제공부(130)를 제어하는 제어부(140);를 포함하고,상기 제어부(140)는,상기 하우징(110)의 일측면에 장착되어, 조명제공부(120) 및 기포제공부(130)에 전원을 인가하거나 차단하는 전원스위치(141);상기 하우징(110)의 일측면에 장착되어, 조명제공부(120)를 통해 발생되는 조명의 밝기를 제어하는 조명제어스위치(142);상기 하우징(110)의 일측면에 장착되어, 에어펌프(150)의 작동 및 발생되는 기포량을 제어하는 기포제어스위치(143); 및상기 하우징(110)의 일측면에 장착되고, 조명제공부(120)로부터 발생되는 빛의 색상을 변경하는 조명색상 변경스위치(144);를 포함하고,상기 조명제어스위치(142)는, 기설정된 어종에 따른 광 조사 패턴 및 광 조사 유지시간에 따라 조명제공부(120)를 제어하고,상기 기포제어스위치(143)는, 기설정된 어종에 따른 기포 발생 유량, 기포 분사 속도, 기포 크기, 기포 발생 패턴, 기포 발생 유지시간에 따라 기포제공부(130)를 제어하는 것을 특징으로 하는 기포발생기 일체형 집어등., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

187/1150 Row 187: application_number: 1020200053555, combined_string: invention_title: 낚시바늘줄 엉킴을 방지하는 낚시채비 abstract: 본발명은 낚시바늘줄 엉킴을 방지하는 낚시채비에 관한 것으로, 상부 낚시줄(10)에 메달린 합성수지 재질의 물고기 모양 인조미끼(100)의 몸체(110)를 관통하여 끼워지는 상부 낚시바늘(20)과, 상기 인조미끼(100)를 관통한 상부 낚시바늘(20)의 하부에 결합되는 하부 낚시바늘줄(30)의 끝단에 연결부재(200)에 의해 연결되는 하부 낚시바늘(50)로 이루어지는 것으로,본발명은 합성수지 재질의 인조미끼를 관통하여 끼워지는 상부 낚시바늘(20)하부에 연결부재에 의해 하부 낚시바늘을 연결하여 낚시바늘줄 엉킴을 방지하는 현저한 효과가 있다. claims: 상부 낚시줄(10)에 메달린 합성수지 재질의 물고기 모양 인조미끼(100)의 몸체(110)를 관통하여 끼워지는 상부 낚시바늘(20)과, 상기 인조미끼(100)를 관통한 상부 낚시바늘(20)의 하부에 결합되는 하부 낚시바늘줄(30)의 끝단에 연결부재(200)에 의해 연결되는 하부 낚시바늘(50)로 이루어지는 낚시바늘줄 엉킴을 방지하는 낚시채비에 있어서,상기 연결부재(200)는 연질의 상부부재(210)와 하부부재(220)로 이루어지되, 상기 상부부재(210)는 세로방향이 길고 가로방향이 짧은 단면이 타원형상이며 중심부의 세로방향으로 낚시바늘줄이 통과되는 구멍이 형성되고, 하부부재(220)는 단면이 원형형상이며 중심부의 세로방향으로 낚시바늘줄이 통과되는 구멍이 형성되며,상기 하부 낚시바늘줄(30)은 상기 상부 낚시바늘(20)에 감겨진 중앙 부위는 고리를 형성하여, 하부 낚시바늘줄(30)이 고리의 하부방향으로 두가닥이 되며, 상기 하부 낚시바늘줄(30)은 흔들려서 엉키지 않게 철선을 사용하며,상기 연결부재(200)의 상부부재(210)는 상부로 밀착시켜 연질재질인 실리콘이나 고무재질로 인해 상기 하부 낚시바늘줄(30)의 고리를 상부로 밀착시켜 흔들리지 않게 하여 하부 낚시바늘줄(30)이 상부 낚시바늘(20)이나 상부 낚시줄(10)과 엉키지 않게 하며,하부부재(220)는 상부부재(210)가 상부로 밀착될때 탄성복원력에 의해 다시 원위치되지 않게 연질재질인 실리콘이나 고무재질로 제작되어, 상부부재(210)의 하부에서 고정되고 하부부재(220)는 상부부재(210)보다 탄성력이 작아서 더 딱딱한 것을 특징으로 하는 낚시바늘줄 엉킴을 방지하는 낚시채비, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

188/1150 Row 188: application_number: 1020200041426, combined_string: invention_title: 초고속 갈치낚시 방법 abstract: 본 발명은 초고속 갈치낚시 방법에 관한 것으로, 더욱 상세히는 낚시바늘을 미끼에 연결시 낚시줄이 연결되는 낚시바늘의 고리부분부터 미끼에 삽입시키는 방식으로 낚시바늘을 미끼에 연결하여 갈치의 입걸림을 빠르게 할 수 있는 초고속 갈치낚시 방법에 관한 것이다.본 발명의 초고속 갈치낚시 방법은 후크형 낚시바늘(10)의 상단에 낚시줄(20)을 연결할 수 있는 고리(11)가 형성되고 타단에 바늘코(12)가 형성된 갈치낚시용 낚시바늘을 이용한 갈치낚시 방법에 있어서,일정크기로 잘라 미끼(30)를 준비하는 단계;상기 낚시바늘(10)의 고리(11)부터 상기 미끼(30)에 삽입시켜 고리(11)는 미끼(30)를 관통하여 외부로 노출되고 낚시바늘(10)은 미끼(30)에 삽입된 상태가 되게 미끼(30)에 낚시바늘(10)을 연결하는 단계;상기 고리(11)에 낚시줄(20)을 연결하는 단계로 이루어지는 것을 특징으로 한다. claims: 후크형 낚시바늘(10)의 상단에 낚시줄(20)을 연결할 수 있는 고리(11)가 형성되고 타단에 바늘코(12)가 형성된 갈치낚시용 낚시바늘을 이용한 갈치낚시 방법에 있어서,일정크기로 잘라 미끼(30)를 준비하는 단계;상기 낚시바늘(10)의 고리(11)부터 상기 미끼(30)에 삽입시켜 고리(11)는 미끼(30)를 관통하여 외부로 노출되고 낚시바늘(10)은 미끼(30)에 삽입된 상태가 되게 미끼(30)에 낚시바늘(10)을 연결하는 단계;상기 고리(11)에 낚시줄(20)을 연결하는 단계로 이루어지는 것을 특징으로 하는 초고속 갈치낚시 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

189/1150 Row 189: application_number: 1020190168833, combined_string: invention_title: 오징어낚시용 축광루어 abstract: 본 발명은 오징어낚시용 루어에 관한 것으로서, 구체적으로 축광기능이 구비한 루어를 형성함에 있어서 오징어가 느끼는 이물감을 제거하여 효율적인 오징어낚시를 가능하게 하는 오징어낚시용 축광루어에 관한 것이다.본 발명은 물고기 또는 새우형상을 가지는 루어몸체(100); 상기 루어몸체(100)의 외면을 감싸는 메시상의 섬유재(110); 상기 루어몸체(100)의 후부에 구비되어 오징어가 낚이도록 하는 후크(300)부:를 포함하는 오징어낚시용 루어에 있어서, 상기 루어몸체(100)의 외면과 상기 섬유재(110) 사이에는 몸체(100)의 길이방향으로 축광필름(130)이 적어도 하나이상 부착되되 상기 루어몸체(100)의 길이방향을 따라 형성된 그루브(120)에 부착되도록 하며, 특히 축광필름(130)과 루어몸체(100) 경계에 단차가 없어서 매끄럽게 형성된 것을 특징으로 하는 오징어낚시용 루어이다. claims: 물고기 또는 새우형상을 가지는 루어몸체(100);상기 루어몸체(100)의 외면을 감싸는 메시상의 섬유재(110);상기 루어몸체(100)의 후부에 구비되어 오징어가 낚이도록 하는 후크(300)부:를 포함하는 오징어낚시용 루어에 있어서, 상기 루어몸체(100)의 외면과 상기 섬유재(110) 사이에 축광필름(130)이 구비되되, 상기 축광필름(130)은 상기 루어몸체(100)의 표면에 적어도 하나 이상 부착된 것을 특징으로 하는 오징어낚시용 축광루어., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

190/1150 Row 190: application_number: 1020190143633, combined_string: invention_title: 음향 센서를 이용한 3차원 어구 위치 추적 시스템 및 방법 abstract: 본 발명은 음향 센서를 이용한 3차원 어구 위치 추적 시스템 및 방법에 관한 것으로, 물고기 등의 대상물을 포획하기 위해 해상 또는 해저에 위치하는 자망이나 통발과 같은 어구에서 송출되는 음향신호를 3척의 선박에서 수신하여 개별 선박으로 부터 어구에 설치된 수중 음향센서와의 거리를 산출하고 위경도 좌표값을 이용해 어구의 위치를 3차원적으로 해석 및 추출하여 어구의 위치를 확인하고 신속하고 쉽게 추적 회수가 가능하도록 하는 3차원 어구 위치 추적 시스템 및 방법을 제공한다. claims: 해상 또는 해저에 위치하는 어구(1)에 설치되어 음향신호를 송출하는 수중 음향센서(100)와, 제1 내지 제3 선박(2a,2b,2c)에 구비되어 상기 수중 음향센서(100)로부터 음향신호가 수신되면 거리값을 추출하고 위도 및 경도값을 수집하고 상기 거리값과 위도 및 경도값을 포함하는 선박수집정보를 생성하는 제1 내지 제3 선박용 추적장치(200a,200b,200c)와, 상기 제1 내지 제3 선박용 추적장치(200a,200b,200c)로부터 선박수집정보가 수신되면 3차원 좌표변환을 통해 어구(1)에 설치된 수중 음향센서(100)의 위치를 포함하는 추적정보를 도출하는 관제센터(3)의 추적서버(300)를 포함하는 것을 특징으로 하는 음향 센서를 이용한 3차원 어구 위치 추적 시스템.제1 내지 제3 선박(2a,2b,2c)에 구비되는 제1 내지 제3 선박용 추적장치(200a,200b,200c)로부터 어구(1)에 설치된 음향수신기(210)의 음향신호로부터 산출된 수중 음향센서(100)의 거리값과 GPS수신기(220)에서 수신되는 GPS정보에서 추출된 위도 및 경도값을 을 포함하는 선박수집정보를 수신하여 3차원 좌표계로 변환하는 제1단계; 및 상기 3차원 좌표계로 변환한 선박수집정보를 이용해 상기 수중 음향센서(100)의 위치에 관한 3차원 좌표값(위도, 경도, 수심) 형태의 추적정보를 도출하는 제2단계;를 포함하는 것을 특징으로 하는 음향 센서를 이용한 3차원 어구 위치 추적 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

191/1150 Row 191: application_number: 2020190004280, combined_string: invention_title: 낚시바늘 교정기 abstract: 본 고안은 주로 오징어 낚시 등에 사용되는 두족류 낚시바늘 등을 매우 간편히 교정할 수 있도록 한 낚시바늘 교정기에 관한 것이다.본 고안은 두족류 낚시바늘의 바늘(10)을 바르게 펴서 교정하는 바늘 교정기(1)를 구성함에 있어서, 휘어진 바늘을 바르게 펼 수 있는 교정부(2)와, 상기 교정부(2)를 사용하기위해 교정기(1)를 파지할 수 있도록 하는 파지부(3)로 이루어지며, 상기 교정부(2)는 바깥로 벌어진 바늘(10)을 문질러 마찰시키면서 이와 동시에 안쪽으로 강제로 밀어서 바깥으로 휘어진 바늘(10)이 안쪽으로 다시 휘어지면서 교정될 수 있도록 수정벽(4)으로 형성하고, 상기 수정벽(4)에는 바늘(10)이 제 위치에서 고정되어 이동되도록 요철(41)을 형성하여 낚시바늘 교정기를 구성한 것에 요지가 있다. claims: 두족류 낚시바늘의 바늘(10)을 바르게 펴서 교정하는 바늘 교정기(1)를 구성함에 있어서,휘어진 바늘을 바르게 펼 수 있는 교정부(2)와, 상기 교정부(2)를 사용하기위해 교정기(1)를 파지할 수 있도록 하는 파지부(3)로 이루어진 것을 특징으로 하는 낚시바늘 교정기., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

192/1150 Row 192: application_number: 1020190131568, combined_string: invention_title: 낚시 abstract: 본 발명은 오징어가 프리미끼(60)를 먹잇감으로 인식하여 덥석 물면서 요동치거나 어선의 롤링이 발생될 경우, 오징어는 바늘(62)에 더욱 깊게 낚이면서 저항 및 반항하게 되는데, 이 과정에서 어퍼고정판(41)으로부터 프리미끼(60)가 센터스프링(63)의 탄성에 의해 순간적으로 이격 및 복원되면서 위성수직홀(61b)들 속에 채워진 공기들이 순식간에 수중으로 퍼지면서 공기방울에 의한 주변 오징어의 유인을 극대화시킬 수 있도록 하고, 구체적으로 오징어가 바늘(62)에 낚이면서 빠져나오려고 요동치는 순간 바늘(62)과 함께 움직이는 프리승강봉(61)이 낚싯줄(10)을 타고 센터스프링(63)의 탄성과 더불어 하강 후 복원하면서, 즉 어퍼고정판(41)으로부터 이격 후 다시 맞닿는 과정에서 위성수직홀(61b)들 속에 채워진 공기가 수중으로 퍼져[무수히 많은 공기방울로 퍼져] 주변 오징어의 유인을 극대화시킬 수 있도록 하는 낚시에 관한 발명이다. claims: 낚싯줄(10)에 서로 이격 고정된 어퍼스토퍼(40) 및 언더스토퍼(50)와, 바늘(62)을 지니며 상기 어퍼스토퍼(40) 및 언더스토퍼(50) 사이에서 상기 낚싯줄(10)을 통과시키는 센터수직홀(61a)을 가진 프리미끼(60)를 포함하는 낚시에 있어서,상기 어퍼스토퍼(40)에 마련된 어퍼고정판(41)을 구비하고,상기 프리미끼(60)는 상기 바늘(62)을 지니면서 상기 센터수직홀(61a)로부터 방사상으로 이격 뚫려져 공기가 채워지는 위성수직홀(61b)들을 구비한 프리승강봉(61)과, 상기 어퍼고정판(41) 및 프리승강봉(61)에 상하 고정되면서 상기 낚싯줄(10)을 중심에 두고 상기 센터수직홀(61a) 속으로 끼워져 상기 프리승강봉(61)을 탄성적으로 승강시키되 상기 프리승강봉(61)의 탄성적 상승시 상기 어퍼고정판(41)으로 하여금 상기 위성수직홀(61b)들의 상단을 실링시키도록 하는 반면 상기 프리승강봉(61)의 탄성적 하강시 상기 위성수직홀(61b)들 속의 공기를 수중으로 순식간에 퍼뜨리도록 하는 센터스프링(63)을 포함하는 것을 특징으로 하는 낚시., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

193/1150 Row 193: application_number: 1020190129747, combined_string: invention_title: 낚시바늘 복원장치 abstract: 본 발명은, 사용되어 훼손된 낚시바늘을 원상태로 복원하여 재사용할 수 있도록;낚시몸체와, 상기 낚시몸체에 평면상 중앙을 중심으로 원주방향으로 둘러서 방사상방향으로 고정되는 다수의 갈고리 형상의 낚시바늘들을 가지는 낚시바늘조립체에서, 외측으로 벌어진 상기 낚시바늘을 오므리어 원상태로 복원하도록 된 낚시바늘 복원장치에 있어서; 길이를 가지며 내측에 상기 낚시바늘들이 수용되면서 길이방향으로 이동운동하도록 된 복원공간을 가지는 복원본체;를 포함하여 이루어지되; 상기 복원공간은, 중앙를 중심으로 복원하고자 하는 상기 낚시바늘들의 외측단부들을 각각 연결하는 '원(圓;circle)' 형상의 내벽을 가지는 낚시바늘 복원장치를 제공한다. claims: 낚시몸체와, 상기 낚시몸체에 평면상 중앙을 중심으로 원주방향으로 둘러서 방사상방향으로 고정되는 다수의 갈고리 형상의 낚시바늘들을 가지는 낚시바늘조립체에서, 외측으로 벌어진 상기 낚시바늘을 오므리어 원상태로 복원하도록 된 낚시바늘 복원장치에 있어서;길이를 가지며 내측에 상기 낚시바늘들이 수용되면서 길이방향으로 이동운동하도록 된 복원공간을 가지는 복원본체;를 포함하여 이루어지되;상기 복원공간은,중앙를 중심으로 복원하고자 하는 상기 낚시바늘들의 외측단부들을 각각 연결하는 '원(圓;circle)' 형상의 내벽을 가지는 것을 특징으로 하는 낚시바늘 복원장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

194/1150 Row 194: application_number: 1020190123586, combined_string: invention_title: 어류질병 감지장치 및 그 감지방법 abstract: 어류질병 감지장치 및 그 감지방법이 개시된다. 본 발명에 따른 어류질병 감지장치는, 어류에 대한 질병의 종류와 각각의 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 움직임패턴 저장부; 가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 영상신호 수신부; 영상신호 수신부에 의해 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 움직임패턴 분석부; 움직임 분석부에 의해 분석되는 각각의 어류의 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 어류 추출부; 어류 추출부에 의해 추출된 어류에 대응하는 움직임패턴을 움직임패턴 저장부에 저장된 움직임패턴과 비교하는 움직임패턴 비교부; 및 움직임패턴 비교부에 의해 비교되는 결과에 따라 어류 추출부에 의해 추출된 어류에 대한 질병 여부를 판단하는 어류질병 판단부;를 포함하는 것을 특징으로 한다. claims: 어류에 대한 질병의 종류와 각각의 상기 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 움직임패턴 저장부;가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 영상신호 수신부; 상기 영상신호 수신부에 의해 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 움직임패턴 분석부;상기 움직임 분석부에 의해 분석되는 각각의 어류의 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 어류 추출부;상기 어류 추출부에 의해 추출된 어류에 대응하는 움직임패턴을 상기 움직임패턴 저장부에 저장된 움직임패턴과 비교하는 움직임패턴 비교부; 및상기 움직임패턴 비교부에 의해 비교되는 결과에 따라 상기 어류 추출부에 의해 추출된 어류에 대한 질병 여부를 판단하는 어류질병 판단부;를 포함하는 것을 특징으로 하는 어류질병 감지장치.어류질병 감지장치에 의해 수행되는 어류질병 감지방법에 있어서,어류에 대한 질병의 종류와 각각의 상기 질병에 대응하는 어류의 움직임패턴을 데이터베이스화하여 저장하는 단계;가두리 양식장의 해수면 및 수중의 적어도 하나를 촬영하는 카메라로부터 영상신호를 수신하는 단계; 상기 카메라로부터 수신되는 영상신호에 대하여 설정된 시간간격 동안의 각각의 어류의 움직임패턴을 분석하는 단계;분석되는 상기 움직임패턴에 기초하여 움직임의 범위가 설정된 값 이하인 어류를 추출하는 단계;추출된 상기 어류에 대응하는 움직임패턴을 저장된 상기 움직임패턴과 비교하는 단계; 및비교되는 결과에 따라 추출된 상기 어류에 대한 질병 여부를 판단하는 단계;를 포함하는 것을 특징으로 하는 어류질병 감지방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

195/1150 Row 195: application_number: 1020190122208, combined_string: invention_title: 무게조절이 가능한 통발 abstract: 본 발명의 일 실시예에 따른 무게조절이 가능한 통발은, 어류를 포획하는 무게조절이 가능한 통발에 있어서, 아릿줄과 체결되는 체결부, 상기 체결부와 연결되며, 내부에 포획공간이 형성되는 원통형 통발부, 상기 통발부의 하부측에 착탈 가능하도록 연결되며, 상기 어류의 상기 포획공간으로의 통로를 제공하는 어류통로부를 포함하며, 상기 통발부는, 외주면을 따라 함입되어 형성된 채, 자연석 또는 인공석이 삽입되는 함입부를 구비하며, 상기 함입부에 삽입된 상기 자연석 또는 인공석에 의해 수중에서의 침강이 용이하게 할 수 있다. claims: 어류를 포획하는 무게조절이 가능한 통발에 있어서,아릿줄과 체결되는 체결부;상기 체결부와 연결되며, 내부에 포획공간이 형성되는 원통형 통발부;상기 통발부의 하부측에 착탈 가능하도록 연결되며, 상기 어류의 상기 포획공간으로의 통로를 제공하는 어류통로부;를 포함하며,상기 통발부는,외주면을 따라 함입되어 형성된 채, 자연석 또는 인공석이 삽입되는 함입부를 구비하며, 상기 함입부에 삽입된 상기 자연석 또는 인공석에 의해 수중에서의 침강이 용이하게 하고, 상기 통발부는,내부에 포획공간이 형성되는 원통형 통발내피부 및 상기 통발내피부의 외측면을 커버하고, 상기 통발내피부의 외측면과 접촉되는 내측면이 형성되는 원통형 통발외피부를 구비하고,상기 함입부는,상기 통발외피부의 외주면으로부터 함입되어 형성되며, 탄성 재질로 형성되어, 상기 자연석 또는 인공석이 삽입되는 경우, 팽창 탄성 변형되고, 상기 자연석 또는 인공석이 삽입 완료되면, 복원력에 의해 상기 자연석 또는 인공석을 압착하여 이탈을 방지하는 것을 특징으로 하는 무게조절이 가능한 통발., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

196/1150 Row 196: application_number: 1020190120702, combined_string: invention_title: 탐지 영역 스캔 장치 abstract: 탐지 영역 스캔 장치 및 방법이 개시된다. 본 발명은 현재 레이더의 위치 정보와 표적 정보를 포함하는 신호를 수신 받아 탐지 영역 및 스캔 설정 정보에 대한 데이터를 획득하는 데이터 획득부, 스캔 설정 정보를 이용하여 기계적 빔을 조향하는 서보 제어 신호를 생성하는 서보 제어부 및 스캔 설정 정보를 이용하여 전자적 빔을 조향하는 위상 변환 제어 신호를 생성하는 위상 변위기 제어부를 포함함으로써, 좁은 빔폭으로 탐지 영역을 빠르게 스캔할 수 있다. claims: 탐지 영역 스캔 장치에 있어서,현재 레이더의 위치 정보와 표적 정보를 포함하는 신호를 수신 받아 탐지 영역 및 스캔 설정 정보에 대한 데이터를 획득하는 데이터 획득부;상기 스캔 설정 정보를 이용하여 기계적 빔을 조향하는 서보 제어 신호를 생성하는 서보 제어부; 및상기 스캔 설정 정보를 이용하여 전자적 빔을 조향하는 위상 변환 제어 신호를 생성하는 위상 변위기 제어부를 포함하며,상기 스캔 설정 정보는, 표적 탐지를 위한 최소 조사 시간(Dwell Time), 방위각 방향 풋프린트(Foot-print) 값, 고각 방향 풋프린트 값, 김발 조향각 및 김발 스캔 속도를 포함하는 것을 특징으로 하는 탐지 영역 스캔 장치.전자기파를 송수신하는 안테나;상기 안테나에 연결되며 현재 레이더의 위치 정보와 표적 정보를 포함하는 신호를 수신 받아 탐지 영역 및 스캔 설정 정보에 대한 데이터를 획득하는 데이터 획득부;상기 스캔 설정 정보를 이용하여 기계적 빔을 조향하는 서보 제어 신호를 생성하는 서보 제어부; 및상기 스캔 설정 정보를 이용하여 전자적 빔을 조향하는 위상 변환 제어 신호를 생성하는 위상 변위기 제어부를 포함하며,상기 안테나는, 상기 탐지 영역을 스캔하도록 방위각 방향 및 고각 방향 회전 동작하는 김발을 더 포함하며,상기 김발은 서보 제어 신호에 의해 제어되는 것을 특징으로 하는 레이더 시스템., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

197/1150 Row 197: application_number: 1020190116681, combined_string: invention_title: 비접촉식 어류 계수 장치 및 계수 방법 abstract: 본 발명은 비접촉식 어류 계수 장치에 관한 것으로, 보다 상세하게는 어류가 유입될 수 있도록 일측면은 입구가 구비되고 상기 입구와 마주 보는 타측면에는 출구가 형성된 내부가 비어 있는 몸체부; 및 상기 몸체부를 통과하는 어류의 크기 및/또는 개체수를 측정하기 위한 측정수단이 상기 몸체부 소정 영역에 구비된 것을 특징으로 하는 비접촉식 어류 계수 장치에 관한 것이다. claims: 어류가 유입될 수 있도록 일측면은 입구(111)가 구비되고 상기 입구(111)와 마주 보는 타측면에는 출구(112)가 형성된 내부가 비어 있는 몸체부(100); 및상기 몸체부(100)를 통과하는 어류의 크기 및/또는 개체수를 측정하기 위한 측정수단이 상기 몸체부(100) 소정 영역에 구비되되,상기 몸체부(100)는 입구(111) 및 상기 입구(111)와 마주 보는 타측면에 출구(112)가 구비되고, 천정면과 바닥면의 소정 영역이 개구되어 있으며, 높이 조절이 가능하도록 측면이 주름진 형상인 통로 본체부(110); 상기 통로 본체부(110)의 상면에 위치하는 상판부(120); 및 하면 외부에 위치하는 하판부(130)를 포함하되, 상기 상판부(120)에는 천정면 개구부와 대응되는 상판 개구부(121), 상기 하판부(130)에는 바닥면 개구부와 대응되는 하판 개구부(131)가 형성되고,상기 상판 개구부(121)와 하판 개구부(131)에 각각 안착되는 1개 이상의 센싱부(200)를 포함하는 것을 특징으로 하는 비접촉식 어류 계수 장치.청구항 제1항에 기재된 비접촉식 어류 계수 장치를 이용한 어류 계수 방법에 있어서,어류의 종류와 크기를 고려하여 어류 계수 장치의 통로 본체부(110) 높이를 조절하는 단계;통로 본체부(110) 상부와 하부에 센싱부(200)를 고정한 후, 케이지(C)에 어류 계수 장치를 설치하는 단계; 및센싱부(200)에 전원을 공급하여 통로 본체부(110)를 이동하는 어류를 계수하는 단계를 포함하는 것을 특징으로 하는 비접촉식 어류 계수 장치를 이용한 어류 계수 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

198/1150 Row 198: application_number: 1020190110239, combined_string: invention_title: 휴대용 수중 집어등 abstract: 본 발명은 수중에서 양의 주광성을 갖는 어종을 효과적으로 유인할 수 있도록 구성된 휴대용 수중 집어등에 관한 것으로, 상세하게는 평판 형상을 갖는 둘 이상의 단위 발광면이 상호 연결된 본체; 상기 단위 발광면에 장착되어 빛을 조사하는 광원부재; 및 상기 본체의 상단에 결합되는 부력구;를 포함하는 것이 특징이다. claims: 평판 형상을 갖는 둘 이상의 단위 발광면이 상호 연결된 본체;상기 단위 발광면에 장착되어 빛을 조사하는 광원부재; 및상기 본체의 상단에 결합되는 부력구;를 포함하는 것을 특징으로 하는 휴대용 수중 집어등., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

199/1150 Row 199: application_number: 1020190104059, combined_string: invention_title: 문어 낚시용 어구 abstract: 본 발명은 각 바늘의 각각의 연결고리가 봉돌의 후면으로 동시에 같이 돌출되어 각 바늘의 유동성을 방지하면서 봉돌에 크랙(crack)이 발생하지 않도록 봉돌에 매설되는 중앙 바늘, 측면 바늘 및 상부 바늘의 각 연결고리는 봉돌의 후면으로 각각 돌출되게 형성되되, 상기 각 연결고리는 하부에 상부 바늘의 연결고리가, 상기 상부 바늘의 연결고리 상부에 측면 바늘의 연결고리가, 상기 측면 바늘의 연결고리 상부에 중앙 바늘의 연결고리가 순차적으로 배치되도록 형성되는 문어 낚시용 어구를 제공한다. 그에 따라 낚싯줄 또는 맨도래와 연결되는 각 연결고리의 높은 강성으로 인해 분실을 최소화함은 물론 오랜 사용기간을 확보할 수 있는 효과와 함께 어구에 대한 높은 신뢰성을 확보할 수 있는 효과 또한 가진다. claims: 각 선단이 후크 형태로 절곡 형성되며, 각 중앙을 절곡하여 각각의 연결고리가 형성되는 중앙 바늘과, 측면 바늘 및 상부 바늘의 일부가 중량체인 봉돌에 매설되어 형성되는 문어 낚시용 어구로서, 상기 중앙 바늘, 측면 바늘 및 상부 바늘의 각 연결고리는 봉돌의 후면으로 각각 돌출되게 형성되되, 상기 각 연결고리는 하부에 상부 바늘의 연결고리가, 상기 상부 바늘의 연결고리 상부에 측면 바늘의 연결고리가, 상기 측면 바늘의 연결고리 상부에 중앙 바늘의 연결고리가 순차적으로 배치되도록 형성되는 문어 낚시용 어구., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

200/1150 Row 200: application_number: 1020190097614, combined_string: invention_title: 낚시대 바늘 고정판 abstract: 나의 발명은 낚시대에 달려 있는 알루미늄으로 만들어진 제품이고 그곳에 구멍이 뚫려 있다. 그곳에 바늘을 꼽아 바람에 날리지 않게 한다. claims: 알루미늄 판이 구부러져 있고 알루미늄 판에 구멍이 5매가 뚫려 있다. 또 구멍이 휘어져 있어 구멍에 일치한다. 이 알루미늄 판은 바늘이 바람에 날리지 않도록 방지하고 바늘이 사람에게 꼽히지 않는 것을 도와준다., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

201/1150 Row 201: application_number: 1020190092782, combined_string: invention_title: 낚시바늘 미늘추가장치 abstract: 기존 낚시바늘의 미늘(20)에 미끼를 고정할수 있는 미늘장치(50)을 설치하여 바다낚시, 민물낚시, 루어낚시등 다양하게 이용중인 낚시의 바늘에 미끼를 더욱 더 견고하게 고정하고 어류의 입질을 더 강력하게 유도하기 위한 장치 claims: 기존 낚시바늘의 구성에서 바다낚시, 민물낚시, 루어낚시등 모든 낚시에서 미늘이 사용중인 각각의 바늘(감성돔용, 벵에돔용, 참돔용, 부시리용, 농어용, 방어용, 우럭용, 볼락용, 학꽁치용, 메가리,전갱이용, 전어용,고등어용 카드채비, 가물치용, 붕어용, 잉어용, 향어용, 루어낚시용 싱글훅, 더블훅, 트레블훅등)에 추가된 미끼고정용 낚시바늘 미늘장치(50)청구항 2청구항 1에 있어서 때에 따라 여러개의 미늘(50)장치를 낚시바늘의 안쪽으로 추가하는 장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

202/1150 Row 202: application_number: 1020190084217, combined_string: invention_title: 집어등 abstract: 본 발명은 집어등에 관한 것으로, 상부플레이트, 하부플레이트, 조명유닛, 상부 고정유닛을 포함하되 하부 고정유닛을 더 포함함으로써 하부 고정유닛을 통하여 선박의 흔들림에도 상단과 함께 하단부분이 안정적으로 고정될 수 있도록 하여 집어등의 상단은 물론 하단부분의 유동 발생을 방지할 수 있도록 하는 한편, 상단과 함께 하단부분의 유동 발생을 방지함으로써 집어를 위한 조명이 해수면 측으로 안정적으로 비추어지도록 함과 동시에 이웃하는 집어등과의 충돌 및 충돌로 인한 파손을 방지할 수 있도록 하는 한편, 조명유닛 자체 및 조명유닛의 점등상태를 제어하는 컨트롤패널에 대한 방수기능을 한층 강화시킬 수 있도록 하며, 조명빛에 유인되어 날아든 불나방 등의 곤충의 사체가 아랫쪽으로 손쉽게 배출될 수 있도록 하고, 각각의 조명유닛으로부터 발생되는 열이 보다 신속하게 강제 배출되도록 하여 단위 시간당 열방출효율을 극대화시킬 수 있도록 하는 것이다. claims: 어업용 선박의 둘레부분 상, 하부에 상하방향으로 일정간격을 가지고 상호 평행이 되도록 설치된 상, 하부 장착 와이어(10, 20)에 대하여 상부 장착 와이어(10)에 상단이 고정설치되며 하부 장착 와이어(20)에 하단이 고정설치되는 집어등(100)에 있어서, 원판 상으로 제공되며, 중앙부분에 양측으로 일정간격을 가지고 설치공(113)이 관통형성되는 상부플레이트(110)와; 상기 상부플레이트(110)의 하부에 일정거리 떨어져 배치되되 상기 상부플레이트(110)와 대응되는 원판 상으로 제공되며, 중앙부분에 일정지름을 가지고 상기 상부플레이트(110)와의 사이 공간내로 외부의 찬 공기가 유입될 수 있도록 하는 흡기공(121)이 관통형성되고, 상기 흡기공(121)의 양측에 설치공(123)이 관통형성되는 하부플레이트(120)와; 조명을 비추기 위한 일면이 호형으로 돌출형성되는 바 타입으로 제공되며, 상기 상부플레이트(110)와 하부플레이트(120) 사이의 둘레방향을 따라 다수 개로 연이어 배치되어 상단이 상기 상부플레이트(110)의 하면에 고정설치되고 하단이 상기 하부플레이트(120)의 상면에 고정설치되는 조명유닛(130)과; 상기 하부플레이트(120)상의 흡기공(121) 상부에 배치되어 둘레부분이 상기 흡기공(121) 상면 둘레부분에 고정설치되는 모터팬(140); 하단의 절곡된 단부가 상기 상부플레이트(110)의 설치공(113)을 관통하여 상기 상부플레이트(110) 하면에 밀착된 상태로 연결부재를 통해 연결고정되고, 상부에 상기 상부 장착 와이어(10)의 단면 1/2과 대응되게 상부 설치홈(153)이 절곡형성되는 상부 고정편(151)이 한 쌍으로 대향되어 밀착된 후 결합부재를 통해 밀착설치되는 상부 고정유닛(150); 및 상단이 상기 하부플레이트(120) 하측으로부터 상향 관통하여 연결부재를 통해 연결고정되며, 하부에 상기 하부 장착 와이어(20)가 삽입고정되도록 하는 하부 고정유닛(160)을 포함하여 이루어진 집어등., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

203/1150 Row 203: application_number: 1020190082851, combined_string: invention_title: 물김처리장치 abstract: 본 발명은 물김처리장치이다. 양식장의 김발에서 채취된 물김을 다수개의 물김포대(30)에 직접 낙하되어 모아지도록 한다. 상기 물김포대(30)는 물김채취선(10)의 갑판에 설치된 프레임(20)의 포대공간(207)에 안착된다. 물김이 채워진 물김포대(30)를 크레인(40)이 인양하는데, 크레인(40)의 인양라인(41)에 설치된 로드셀(43)은 물김의 무게를 측정하여 외부의 단말기(49,50,51)들로 전송한다. 상기 포대공간(207)은 입출구(208)쪽의 횡단면적이 상대적으로 넓고 바닥쪽이 상대적으로 좁게 되어 크레인(40)으로 물김포대(40)를 쉽게 들어올 릴 수 있다. claims: 물김채취선 상에 설치되고 포대공간이 다수개의 행과 열을 가지도록 배치되는 프레임과,상기 포대공간에 위치되고 내부에 물김이 채워지는 물김포대와,상기 프레임에 설치된 레일을 따라 이동하면서 상기 각각의 포대공간의 행의 위치에서 물김을 채취하여 포대공간에 설치된 물김포대에 낙하시키는 채취이동유닛을 포함하는 물김처리장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

204/1150 Row 204: application_number: 1020190080012, combined_string: invention_title: 부표 abstract: 본 발명은 이너수평층간뭉치(100) 및 아우터수직층간뭉치(200)에 의한 쿠션력의 극대화는 물론이거니와 수평방향 및 수직방향으로의 견고함을 동시에 보장하여 로프로 묶을 때 특히 수평방향으로의 찌그러짐[쉽게 찌그러질 경우 최외곽표면융착층(200a)의 파손으로 바닷물이 침투되어 수명이 단축됨]을 방지토록 함으로써 해양시설물과의 설치시 더욱 강도 높은 결합을 가능케 한 부표에 관한 발명이다. claims: 1차 발포된 합성수지발포원판(111)들을 수평층간갭(111d)이 형성되도록 적층시킨 원판뭉치(110)를 제1히팅금형 속에 넣어 2차 발포시키면서 외곽표면융착층(100a)을 지니도록 한 이너수평층간뭉치(100)와,상기 이너수평층간뭉치(100)의 외연을 따라 1차 발포된 합성수지발포시트(211)를 와인딩시켜 상기 수평층간갭(111d)과 직교되는 수직층간갭(211d)이 형성되도록 와인딩시킨 와인딩뭉치를 제2히팅금형 속에 넣어 3차 발포시키면서 최외곽표면융착층(200a)을 지니도록 한 아우터수직층간뭉치(200)를 포함하는 것을 특징으로 하는 부표., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

205/1150 Row 205: application_number: 1020190079468, combined_string: invention_title: 해류에 능동적 대응하는 수중 집어등 abstract: 본 발명은 용기 형태의 프레임 표면에 LED를 부착하여 수중에서 광선의 조사범위를 넓히고, 안정적으로 해류의 흐름에 대응할 수 있도록 평판을 수직으로 설치해 물의 저항을 최소화하여 어종을 보다 효과적으로 유인할 수 있도록 한 수중 집어등에 관한 것으로, 수중에 조명을 투광하여 어류를 조획하기 위한 집어등에 있어서, 속이 빈 용기 형상으로 개구면이 구비된 프레임부; 상기 프레임부의 중심에 위치하는 무게추부; 및 상기 프레임부의 외면에 장착되어 광을 조사하는 조명부;를 포함하는 것이 특징이다. claims: 수중에 조명을 투광하여 어류를 조획하기 위한 집어등에 있어서,속이 빈 용기 형상으로 개구면이 구비된 프레임부;상기 프레임부의 중심에 위치하는 무게추부; 및상기 프레임부의 외면에 장착되어 광을 조사하는 조명부;를 포함하는 것을 특징으로 하는 해류에 능동적 대응하는 수중 집어등., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

206/1150 Row 206: application_number: 1020190077433, combined_string: invention_title: 수압으로 램프를 작동시키는 집어등 abstract: 본 발명은 심해용 집어등에 관한 것으로, 더욱 상세하게는 공기가 들어 있는 폐쇄 용기를 물속에 넣으면 수압을 받아 부피가 줄어들면서 압착되는 힘을 이용하여 전원스위치를 ON 시켜서 램프를 점등하고, 물 밖으로 나오면 수압이 0으로 낮아지면서 수축되었던 폐쇄 용기가 원래 형상으로 복원되는 힘으로 전원스위치를 OFF 시켜서 램프를 소등하는 수압으로 램프를 작동하는 집어등에 관한 것이다 본 고안에 의한 수압으로 램프를 작동하는 집어등은, 램프와 스위치 등 내부회로와 건전지로 구성된 모듈에서 램프의 - 단자와 건전지의 - 단자를 직결하고, 램프의 + 단자와 건전지의 + 단자는 수평으로 배치하여 상기 단자 중에서 어느 하나가 수압을 받아 상대 단자가 있는 방향으로 힘을 받으면 접속되는 스위치, 상기 스위치가 포함된 모듈을 연질의 통형상 케이스에 넣고 수밀되게 밀봉하되, 스위치가 있는 부분은 공기방이 형성된 케이스로 구성되는 특징이 있다. 이와 같은 본 고안에 의하면, 램프를 작동하기 위한 별도의 조작이 필요 없고, 자동으로 물속에서 점등시키고 물 밖에서는 소등시킬 수 있으므로 전원을 효율적으로 사용할 수 있을 뿐만 아니라, 구조를 간단하게 변형하여 수동으로 작동 가능하게 할 수 있고, 소형으로 제작 가능하므로 바늘에 근접 사용이 가능하며, 원과 같은 인조미끼에 삽입하여 집어 기능을 극대화할 수 있는 기능을 제공할 수 있는 특징을 가진 수압에 의해 램프를 작동하는 집어등이다. claims: 램프와 건전지와 스위치 등으로 구성된 모듈과 상기 모듈을 수압으로부터 보호하기 위한 케이스로 구성된 집어등에 관한 것으로, 램프와 건전지의 +, - 전원단자 중에서 어느 하나 이상이 상대 전원단자 방향으로 힘을 받아 움직이면 접속되는 스위치로 구성된 모듈과; 상기 모듈이 삽입되는 투명한 연질의 재료를 사용한 통형상 케이스와; 상기 연질의 통형상 케이스에 있어서 램프와 건전지의 전원단자가 스위치로 기능하는 부분에 공기방(13)을 형성한 것을 특징으로 하는 수압으로 램프를 작동시키는 집어등, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

207/1150 Row 207: application_number: 1020190072936, combined_string: invention_title: 미케니컬 조인트방식으로 제조된 어업용 부표 abstract: 본 발명은 어업용 부표에 관한 것으로, 구체적으로는 몸체를 좌, 우로 별도 형성시키어 각각의 끝단을 미케니컬 조인트방식으로 접합시킨 구조의 어업용 부표에 관한 것이다.본 발명은 두 개의 몸체를 조인트접합방식을 통해 결합시킴으로써 내부가 중공상태인 부표를 제공함으로써 기밀을 유지하고 좌우 고리형상으로 밀폐되어 접합된 부분이 분리되지 않는 형상의 부표를 제공함으로써 불량률이 개선되는 효과가 있다. 또한 본 발명의 부표를 알루미늄으로 제조함으로써 내구성 강화 및 경량강화가 가능한 효과가 있다. claims: 일측이 개방된 형태로 내부공간이 형성되는 제1몸체부(110)와,상기 제1몸체부(110)와 접합되도록 제1몸체부(110)와 대응된 형태로 형성되되, 일측이 개방된 형태로 내부공간을 포함하여 형성되는 제2몸체부(120)와,제1몸체부(110)의 제1접합부(111)와 제2몸체부(120)의 제2접합부(121) 사이에 위치하는 실링부(130)와,상기 제1몸체부(110)의 일측에 형성되는 공기주입부(140)를 포함하되,상기 제1몸체부(110)는제1몸체부(110)의 끝단을 둘러싸되 바깥방향으로 돌출되어 형성되는 제1접합부(111)를 포함하고,상기 제2몸체부(120)는제2몸체부(120)의 끝단을 둘러싸되 바깥방향으로 돌출되어 형성되며, 상기 제1접합부(111)와 실링부(130)가 삽입되도록 제2몸체부(120)의 내부 방향으로 ‘ㄷ’자 형태로 구부러져서 형성되는 제2접합부(121)를 포함하는 것을 특징으로 하는 어업용 부표.일측이 개방된 형태로 내부공간이 형성되되, 몸체가 원통으로 이루어지고 끝단이 반구형태로 형성되는 제1몸체부(110)와, 일측이 개방된 형태로 내부공간이 형성되되, 몸체가 원통으로 이루어지고 끝단이 반구형태로 형성되되 제2몸체부(120)와,제1몸체부(110)의 제1접합부(111)와 제2몸체부(120)의 제2접합부(121) 사이에 위치하는 실링부(130)와,상기 제2몸체부(120)의 공기주입부보호홈(123)에 위치하되 공기가 주입되도록 형성되는 공기주입부(140)를 포함하되,상기 제1몸체부(110)는상기 제1몸체부(110)의 끝단에 바깥방향으로 돌출되어 형성되는 제1접합부(111)와, 제1몸체부(110)의 일측에 형성되되, 양식로프체결줄이 형성되기 위한 제1홈(112)을 포함하고,상기 제2몸체부(120)는상기 제1접합부(111)가 삽입되도록 제2몸체부(120)의 내부 방향으로 ‘ㄷ’자로 구부러진 형태로 형성되는 제2접합부(121)와,제2몸체부(120)의 일측에 형성되되, 양식로프체결줄이 형성되기 위한 제2홈(122)와,공기주입부(140)가 위치하기 위해 제2몸체부(120)의 일측에 함몰되어 형성되는 공기주입부보호홈(123)를 포함하되,상기 제1몸체부(110)의 제1접합부(111)와 제2몸체부(120)의 제2접합부(121)는 미케니컬 조인트 방식으로 접합되는 것을 특징으로 하는 어업용 부표., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

208/1150 Row 208: application_number: 1020190056960, combined_string: invention_title: 탈착식 미노우 에깅 훅 abstract: 본 발명은 육식어종(농어,우럭,광어)낚시에 사용되는 루어(lure=모형 물고기),혹은 미노우에 오징어 낚시등에 주로 사용되는 두족류 낚시바늘을 간편하게 연결하여,한가지 루어로 육식어종과 오징어 낚시를 동시에 즐길수 있게 하기 위한 탈부착식 두족류 낚시바늘에 관한 것이다. claims: 끝부분에 축광 에폭시(06)를 삽입하여 완성하는 두족류 전용바늘(01)과 이를 다른 두족류 전용바늘(02)에 연결 고정시키는 유리섬유(03)와;상기 두족류 전용바늘(02)과 결합하여 스냅(05)과 연결 시켜주는 롤링스위벨(04) 로 구성되는 탈착식 자유형 미노우 에깅훅(100)에 있어서;상기 두족류 전용바늘(02) 내부에 공간을 확보하여 롤링스위벨(04)을 삽입.고정하고;스냅(05)은 분해한여 롤링스위벨(04)과 연결한 후 다시 체결하여;루어의 뒤쪽 바늘을 제거한 상태의 루어(10)에 손쉽게 탈착과 부착이 가능하도록 구성하여 물속에서 자유롭게 움직일수 있도록 하는 특징의 탈착식 자유형 미노우 에깅훅(100).끝부분에 축광 에폭시(06)를 삽입하여 완성하는 바깥쪽 두족류 전용바늘(01)과 이를 다른 안쪽 두족류 전용바늘(02)에 연결 고정시키는 유리섬유(03)로 구성되는 두족류 전용 바늘묶음(07)과;상기 두족류 전용 바늘묶음(07)을 루어의 뒤쪽 바늘을 제거한 상태의 루어(10)에 움직이지 않도록 고정시켜 연결하기 위하여 발명된 축광 플라스틱(08)과 고정핀(09)으로 구성되는 탈착식 고정형 미노우 에깅훅(101)에 있어서;상기 축광 플라스틱(06)은 상기 두족류 전용 바늘묶음(07)의 유리섬유가 삽입될수 있는 구멍을 내어 삽입하고 에폭시로 고정하며; 상기 축광 플라스틱(08)은 루어의 뒤쪽 바늘을 제거한 상태의 루어(10)의 쇠고리 부분이 삽입되어 고정될수 있도록 홈을 내고 고정핀(09)이 들어갈 구멍을 내어 결속할수 있도록 하여; 루어의 뒤쪽 바늘을 제거한 상태의 루어(10)에 손쉽게 탈착과 부착이 가능하도록 구성하고 루어에 단단하게 고정되어 움직일수 있도록 하는 특징의 탈착식 고정형 미노우 에깅훅(101)., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

209/1150 Row 209: application_number: 1020190030417, combined_string: invention_title: 집어등 빛 그림자 조절장치 abstract: 본 발명은 집어등(L)이 장착된 파이프(80)를 어선(S)의 현(H)방향으로 근접시켜 현(H)에 의한 바다 속 그림자 영역을 작게 형성함과 더불어 집어등(L)의 빛 영역을 더 근접하게 형성시킬 수 있도록 하는 반면 집어등(L)이 장착된 파이프(80)를 갑판(G)의 중심방향으로 근접시켜 현(H)에 의한 바다 속 그림자 영역을 크게 형성함과 더불어 집어등(L)의 빛 영역을 더 멀리 형성시킬 수 있도록 하여, 즉 집어등(L)의 명암의 영역을 현(H)을 기점으로 한 횡바(70)들을 따라 파이프(80)의 신속 간단한 이동으로 일거에 조절 가능하게 하여, 야간 달빛의 영향이나 배의 크기 및 높이 또는 어류의 각 특성에 맞는 조업활동을 보다 적극적으로 대응케 하여 어획량을 극대화시킬 수 있도록 한 집어등 빛 그림자 조절장치에 관한 발명이다. claims: 어선(S)의 현(H)으로부터 평행하게 이격되는 갑판(G) 위에 수직으로 병렬 세워진 제1열서포터(41) 및 제2열서포터(42)와,상기 제1열서포터(41) 및 제2열서포터(42)의 상부를 가로질러 고정된 횡바(70)들과,집어등(L)을 등간격으로 장착하여 상기 횡바(70)들을 따라 상기 어선(S)의 현(H)방향으로 또는 상기 갑판(G)의 중심방향으로 이동하면서 상기 현(H)을 기점으로 바다를 향한 상기 집어등(L)의 빛과 그림자를 조절하는 파이프(80)와,상기 파이프(80)를 상기 횡바(70)들에 착탈 가능하게 고정시키는 착탈수단(90)을 포함하는 것을 특징으로 하는 집어등 빛 그림자 조절장치., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

210/1150 Row 210: application_number: 1020190028232, combined_string: invention_title: 사각통그물망을 구비한 정치어망 abstract: 정치어망용 사각통그물망에 관한 것으로, 회유성 어류가 통그물로 유인되도록 육지에서 바다를 향해 일직선상으로 설치되는 유도망; 상기 유도망과 함께 회유성 어류가 유인되도록 상기 유도망의 좌우 양측에 소정의 각도로 경사지게 설치되는 보조유도망; 상기 유도망과 상기 보조유도망으로 유인된 회유성 어류가 머물 수 있도록 상기 유도망 및 상기 보조유도망으로부터 소정의 거리만큼 이격되어 설치되는 통그물; 회유성 어류가 사각통그물망으로 이동되도록 상기 통그물의 일측에 설치되는 노부리; 상기 사각통그물망으로 이동된 어류가 상기 통그물로의 이동을 제한하도록 상기 노부리의 일측에 설치되는 조구; 회유성 어류를 포획하도록 상기 조구의 일측에 설치되는 사각통그물망;을 마련하여 사각통그물망의 길이를 선박의 길이보다 길게 설치할 수 있고, 길이가 길게 설치된 사각통그물망에 대량의 어류를 수용할 수 있으며, 사각통그물망의 상면그물망에 의해 수면을 따라 이동하는 회유성 어류를 포획할 수 있다는 효과가 얻어진다. claims: 회유성 어류가 통그물로 유인되도록 육지에서 바다를 향해 일직선상으로 설치되는 유도망;상기 유도망과 함께 회유성 어류가 유인되도록 상기 유도망의 좌우 양측에 소정의 각도로 경사지게 설치되는 보조유도망;상기 유도망과 상기 보조유도망으로 유인된 회유성 어류가 머물 수 있도록 상기 유도망 및 상기 보조유도망으로부터 소정의 거리만큼 이격되어 설치되는 통그물;회유성 어류가 사각통그물망으로 이동되도록 상기 통그물의 일측에 설치되는 노부리;상기 사각통그물망으로 이동된 어류가 상기 통그물로의 이동을 제한하도록 상기 노부리의 일측에 설치되는 조구;회유성 어류를 포획하도록 상기 조구의 일측에 설치되는 사각통그물망;을 포함하며,상기 사각통그물망은 수면에 접하는 상면그물망이 일체로 이루어지는 것을 특징으로 하는 정치어망용 사각통그물망., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

211/1150 Row 211: application_number: 1020190028222, combined_string: invention_title: 보조유도망이 구비된 정치어망 abstract: 보조유도망이 구비된 정치어망에 관한 것으로, 어류의 유입을 안내하도록 일직선상으로 설치되는 유도망; 상기 유도망의 선단에 유입된 어류가 자유로이 움직일 수 있게 공간을 제공하도록 상기 유도망의 선단에 설치되는 통그물; 상기 통그물의 어류가 원통으로 이동하도록 상기 통그물의 일측에 설치되는 노부리; 상기 노부리를 통과한 어류가 상기 통그물로 이탈되지 않도록 상기 노부리의 일측에 설치되는 조구; 상기 조구를 통과한 어류가 포획되도록 상기 조구의 일측에 설치되는 원통;을 포함하며, 회유성 어류가 상기 유도망을 거쳐 상기 통그물 내부로의 이동을 안내하도록 상기 통그물의 양측에 각각 소정 거리만큼 이격되게 설치되는 보조유도망;을 마련하여 유도망의 좌우 양측에 보조유도망을 설치하여 선회하는 어류의 이동을 통그물로 유도하게 되고, 유도망과 보조유도망을 고정로프로 안정적으로 고정시켜 둠으로써 어류의 이동 경로를 확보할 수 있으며, 보조유도망이 유도망의 선단으로부터 보다 길게 연장 형성되어 어류의 유인을 확보할 수 있다는 효과가 얻어진다. claims: 어류의 유입을 안내하도록 일직선상으로 설치되는 유도망;상기 유도망의 선단에 유입된 어류가 자유로이 움직일 수 있게 공간을 제공하도록 상기 유도망의 선단에 설치되는 통그물;상기 통그물의 어류가 원통으로 이동하도록 상기 통그물의 일측에 설치되는 노부리;상기 노부리를 통과한 어류가 상기 통그물로 이탈되지 않도록 상기 노부리의 일측에 설치되는 조구;상기 조구를 통과한 어류가 포획되도록 상기 조구의 일측에 설치되는 원통;회유성 어류가 상기 유도망을 거쳐 상기 통그물 내부로의 이동을 안내하도록 상기 유도망의 양측에 각각 소정 거리만큼 이격되게 설치되는 보조유도망;을 포함하며,상기 보조유도망은 상기 유도망의 일측에 설치되는 제1 보조유도망과 상기 유도망의 타측에 설치되는 제2 보조유도망으로 이루어지고,상기 제1 보조유도망 및 상기 제2 보조유도망 각각의 일단은 상기 유도망의 선단으로부터 육지 방향으로 보다 돌출되게 설치되고,상기 제1 보조유도망 및 상기 제2 보조유도망 각각의 타단은 상기 통그물의 입구로부터 소정의 거리만큼 이격되게 설치되어 회유성 어류가 상기 유도망 및 상기 보조유도망 사이를 통해 회유되면서 상기 통그물의 내측으로 이동되게 설치되는 것을 특징으로 하는 보조유도망이 구비된 정치어망., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

212/1150 Row 212: application_number: 1020190021312, combined_string: invention_title: 어업용 부구 abstract: 본 발명은, 내부에 빈공간을 가지도록 일측이 개방되며, 내주면에는 개방 단부의 모서리 방향과 직각 방향으로 복수개의 보강 리브가 상호 소정 간격 이격된 채로 돌출 형성되며, 상기 개방 단부가 맞닿아 상호 접합되도록 구성된 제1 및 제2 반구형 몸체; 및 상기 제1 및 제2 반구형 몸체의 개방 단부의 내주면과 접촉하여 이를 보강 지지하는 보강 프레임을 포함하는 어업용 부구를 개시한다. claims: 내부에 빈공간을 가지도록 일측이 개방되며, 내주면에는 개방 단부의 모서리 방향과 직각 방향으로 복수개의 보강 리브가 상호 소정 간격 이격된 채로 돌출 형성되며, 상기 개방 단부가 맞닿아 상호 접합되도록 구성된 제1 및 제2 반구형 몸체; 및상기 제1 및 제2 반구형 몸체의 개방 단부의 내주면과 접촉하여 이를 보강 지지하는 보강 프레임을 포함하는 것을 특징으로 하는 어업용 부구., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

213/1150 Row 213: application_number: 1020190021335, combined_string: invention_title: 김 채취기용 분배장치 abstract: 본 발명은 중간부는 높고 양쪽으로 갈 수록 경사가 낮아지는 경사판과, 상기 경사판의 양쪽에 절곡되어 김의 이탈을 방지하기 위한 차단판과, 경사판의 일측에는 선박의 갑판 중간부에 배치되는 저장통의 입구와 일치하도록 통공이 통공되고, 상기 통공의 양측에 형성된 슬라이드부를 따라 이동가능하면서 통공을 막기위한 슬라이드판으로 구성되는 김 채취기용 분배장치를 제공하기 위한 것으로, 본 발명의 효과로는 본 발명의 효과로는 김 채취기용 분배장치는, 중간부는 높고 양쪽으로 갈 수록 경사가 낮아지는 경사판이 김채취기 하부에 부착되므로 상기 김채취기에 의해 절단된 김이 아래로 쏟아질 때 경사판을 타고 흐르게 되는데, 이때 슬라이드판에 의해 통공의 넓이가 조절가능하게 되어 작업자가 중앙에 배치된 저장통에 적당한 양의 김이 쏟아지도록 하고, 또 통공을 지나친 김들은 경사판의 양쪽으로 배출되어 가장자리 저장통에 저장되도록 함으로써 모든 저장통에 균일한 양의 김을 채울 수 있어 김 수확량을 늘일 수 있는 매우 유용한 발명인 것이다. claims: 중간부는 높고 양쪽으로 갈 수록 경사가 낮아지는 경사판과, 상기 경사판의 양쪽에 절곡되어 김의 이탈을 방지하기 위한 차단판과, 경사판의 일측에는 선박의 갑판 중간부에 배치되는 저장통의 입구와 일치하도록 통공이 통공되고, 상기 통공의 양측에 형성된 슬라이드부를 따라 이동가능하면서 통공을 막기위한 슬라이드판으로 구성됨을 특징으로 하는 김 채취기용 분배장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

214/1150 Row 214: application_number: 2020190000251, combined_string: invention_title: 수중 집어등을 수용하는 낚시추 조립체 abstract: 본 고안은 낚시추 조립체에 관한 것으로서, 보다 구체적으로는 수중 집어등을 수용하는 낚시추 조립체에 관한 것이다. 본 고안의 일 실시예에 따르면, 복수의 리브(22) 및 복수의 리브(22) 각 사이에 형성되는 윈도우(32)를 포함하는 상부 하우징(2); 및 상부 하우징(2)과 분리 가능하게 결합되고 내부에 공간(14)을 포함하며 기 설정된 무게로 구성되는 하부 하우징(4);을 포함하는 낚시추 조립체가 제공된다. claims: 복수의 리브 및 상기 복수의 리브 각 사이에 형성되는 윈도우를 포함하고, 상기 복수의 리브 중 각 리브의 일 측을 일체로 결합하는 접합부 및 상기 복수의 리브 중 각 리브의 타 측을 결합하는 결합부를 포함하는 상부 하우징; 상기 상부 하우징과 상기 결합부에 의해 분리 가능하게 결합되고 내부에 공간을 포함하며 기 설정된 무게로 구성되는 하부 하우징;상기 상부 하우징 및 하부 하우징 내부에 수용되고, 내측에 램프가 장착되고 빛이 투과하도록 형성되며 상기 상부 하우징 내에 배치되는 상부 구조체 및 상기 상부 구조체와 수밀하게 결합하고 램프에 전원을 공급하는 전원공급부가 배치되는 하부 구조체를 포함하는 집어등 구조체; 상기 하부 하우징의 내측에 고정 형성되고 상기 하부 구조체를 고정하는 인서트; 및상기 접합부, 상부 구조체 및 하부 구조체를 관통하는 로드;를 포함하고, 상기 로드의 일 측에는 수평방향으로 관통 형성되는 홀이 형성되고, 상기 로드의 타 측에는 상기 인서트와 분리가능하게 결합하는 고정부가 형성되는 것인 수중 집어등을 수용하는 낚시추 조립체., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

215/1150 Row 215: application_number: 1020190002961, combined_string: invention_title: 낚시바늘 결합구 제작방법 abstract: 본발명은 낚시바늘 결합구 제작방법에 관한 것으로, 다수개의 낚시바늘에 인조미끼를 꿰어서 낚시를 하기 위하여, 다수개의 낚시바늘이 하부에 각각 연결되는 다수개의 걸이부(100)와, 상기 다수개의 걸이부(100)가 같이 결합되는 몸체부(200)로 이루어지는 것으로,본발명은 다수개의 낚시바늘에 인조미끼를 꿰어서 낚시를 하기 위하여 상기 낚시바늘이 하부에 연결되는 걸이부들이 몸체부에 결합되되 몸체부가 다수의 몸체로 철선에 의해 연결되어 있어서, 미끼를 메단 걸이부들이 회전되더라도 서로 엉키지 않는 등 사용이 편리하며 제작이 간단한 현저한 효과가 있다. claims: 다수개의 낚시바늘에 인조미끼를 꿰어서 낚시를 하기 위하여, 다수개의 낚시바늘이 하부에 각각 연결되는 다수개의 걸이부(100)와, 상기 다수개의 걸이부(100)가 같이 결합되는 몸체부(200)로 이루어지는 낚시바늘 결합구 제작방법에 있어서,상기 몸체부(200)는 다수 개의 몸체(210)로 이루어지는 것으로 상기 몸체(210)은 원통형의 양단에 경사부가 형성되어 지름이 축소된 것이며,상기 몸체부(200)와 걸이부(100)는 직각을 이루는 것으로, 몸체부에 대하여 걸이부가 회전되더라도 엉키지 않게 되며, 상기 몸체부(200)와 걸이부(100)는 녹이 쓸지 않는 금속을 사용하여 제작하는 것이며,상기 걸이부(100)는 원통형의 양단에 경사부가 형성되어 지름이 축소된 것으로, 파이프를 일정길이로 절단한 후 내부에 양 끝단에 멈춤부가 형성되는 상하부 고리를 제작한 후, 상하부 멈춤부를 파이프 내부에 삽입한 후, 디스크 형상의 롤러로 파이프 양단을 롤포밍하여 멈춤부가 파이프 내부에서 밖으로 이탈되지 않게 하되, 회전 롤러로 파이프 양단을 눌러서 압착할시 파이프 내부에 철선 멈춤부가 삽입된 상태에서 가공하는 것이며,상기 걸이부(100)의 상부고리(101)를 몸체부(200)에 결합하는 것으로, 상기 몸체부(200)는 원통형의 양단에 경사부가 형성되어 지름이 축소된 다수 개의 파이프가 각각의 몸체(210)가 되어 일직선으로 결합되고, 중간의 몸체들 간의 결합은 철선(1)을 파이프 내부에 넣고 롤러로 양단을 압입하여 상기 철선 양단이 파이프 밖으로 나오지 못하게 한 것이며, 양단에 위치하는 몸체는 철선 양 끝단에 형성된 반원형의 멈춤부를 파이프 내부에 삽입한 후 롤러로 파이프 양단을 압입하여 지름을 작게 하여 멈춤부가 파이프 내부에서 밖으로 이탈되지 않게 하는 것이되, 회전 롤러로 파이프 양단을 눌러서 압착할시 파이프 내부에 철선이 삽입된 상태에서 가공하는 것이며, 판재 모양의 금속재질의 금형을 사용하는 것으로, 상기 금형 표면에는 몸체 모양의 홈이 다수개가 간격을 두고 형성되어 있고 몸체홈 사이에는 철선에 해당되는 홈이 형성되어 있어서, 상기 파이프와 철선을 해당 홈에 넣고 롤러로 파이프 양단을 압입하고, 몸체부 양 끝단의 몸체의 좌우측으로서, 몸체부의 좌우양끝단에는 좌측고리부와 우측고리부가 형성되는 것이며,상기 걸이부(100)의 하부고리(102)와 인조미끼는 철선을 둥글게 말아서 둥근 양단을 철선 중앙부에 걸치게 한 체결고리(300)에 의해 착탈되는 것이며, 양단부분을 눌러서 철선 중앙부에서 착탈할 수 있는 것이며,상기 걸이부(100)와 몸체(210)는 동일형상으로 제작가능한 것을 특징으로 하는 낚시바늘 결합구 제작방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

216/1150 Row 216: application_number: 1020190002000, combined_string: invention_title: 오징어낚시용 조립체 abstract: 오징어낚시용 조립체에 있어서, 경심에 묶이는 유인구고리(11)의 하단에 순차적으로 오징어를 유인하는 유인구(12), 상기 유인구(12)와 낚싯바늘(14) 사이의 간격을 유지하는 간격유지구(13), 오징어가 걸리는 상기 낚싯바늘(14), 상기 낚싯바늘(14)의 지름보다 큰 안내구(15), 경심에 묶이는 안내구고리(16)가 구성되는 것을 특징으로 한다.또한 경심에 묶이는 유인구고리(11)의 하단에 순차적으로 오징어를 유인하는 유인구(12), 상기 유인구(12)와 낚싯바늘(14) 사이의 간격을 유지하는 간격유지구(13), 오징어가 걸리는 상기 낚싯바늘(14), 중간고리(18)와 결합하는 낚시고리(17), 상기 낚시고리(17)와 결합하는 중간고리(18), 상기 낚싯바늘(14)의 지름보다 큰 안내구(15), 경심에 묶이는 안내구고리(16)가 구성되는 것을 특징으로 한다.본 발명에 따른 오징어낚시용 조립체에 의하면, 경심이 낚싯바늘에 걸리지 않으므로 낚싯바늘을 풀지 않을 뿐만 아니라 여러 대의 물레를 관리하므로 어획량을 증가시키는 이점이 있다. claims: 오징어낚시용 조립체에서, 경심(20)에 묶이는 유인구고리(11)의 하단에 순차적으로 오징어를 유인하는 유인구(12), 상기 유인구(12)와 낚싯바늘(14) 사이의 간격을 유지하는 간격유지구(13), 오징어가 걸리는 상기 낚싯바늘(14), 상기 낚싯바늘(14)의 지름보다 큰 안내구(15), 경심(20에 묶이는 안내구고리(16)가 구성되는 것을 특징으로 하는 오징어낚시용 조립체.오징어낚시용 조립체에서, 경심(20)에 묶이는 유인구고리(11)의 하단에 순차적으로 오징어를 유인하는 유인구(12), 상기 유인구(12)와 낚싯바늘(14) 사이의 간격을 유지하는 간격유지구(13), 오징어가 걸리는 상기 낚싯바늘(14), 중간고리(18)와 결합하는 낚시고리(17), 상기 낚시고리(17)와 결합하는 상기 중간고리(18), 상기 낚싯바늘(14)의 지름보다 큰 안내구(15), 경심(20)에 묶이는 안내구고리(16)가 구성되는 것을 특징으로 하는 오징어낚시용 조립체., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

217/1150 Row 217: application_number: 1020180140208, combined_string: invention_title: 원격제어가 가능한 집어등을 부착한 어업용 스마트 부표 abstract: 본 발명을 어업에서 사용하는 부표에 관한 것으로 주로 원양 어업에서 트랜스듀서가 탑재되어 어군 탐지가 가능한 부표에 집어등 기능을 부착한 것이다. 또한 집어등의 켜짐과 꺼짐을 위성 통신을 통해 원격으로 확인하고 제어하도록 하여 집어 기능에 대한 관리를 수월하게 하도록 제공하는 것이다. claims: 원격으로 집어등의 켜짐과 꺼짐의 상태확인이 가능하고 켜짐과 꺼짐의 제어가 가능한 집어등을 부착한 어군 탐지가 가능한 어업용 부표원격지에서 부표에 부착된 집어등의 켜짐과 꺼짐에 대한 시간 설정이 가능하도록 한다. 집어등이 켜지고 어군형성이 되어 있는지 어탐을 통해 확인이 가능하므로 특정 시간 동안 어군이 형성 되지 않을 경우 배터리 소모를 줄이기 위해 집어등이 자동으로 꺼지도록 설정이 가능한 어업용 부표, Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

218/1150 Row 218: application_number: 1020180137855, combined_string: invention_title: 편리한 낚시 abstract: 본 발명의 편한낚시는 낚시하는 낚시 바늘에 높낮이를 간단하게 조정할 수 있어 낚시인이 어떠한 환경에 있더라도 여려가지 낚시기법을 쉽게 조정하여 낚시를 할 수 있다 낚시인이 낚시기법을 바꾼다면 채비교한에 번거로움이 생긴다 이것을 해소 하는데 중점을 두였다 claims: 원줄(1)을 원통(4-1 4-2)를 통콰 한후 철심(4-1 4-2)를 이용하는방법목줄(7)을 돌출부(5-2)에 고정한후 돌출부(5-1)로 사용하는방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

219/1150 Row 219: application_number: 1020180131838, combined_string: invention_title: 어류 선별기 abstract: 본 발명은 어류 선별기에 관한 것으로서, 물과 함께 투입된 어류를 크기별로 간편하게 선별할 수 있을 뿐만 아니라 어류의 이동 및 어류와 함께 투입된 물의 흐름이 원활해질 수 있음은 물론 선별된 어류가 이탈되는 것을 방지할 수 있고, 나아가, 어류의 정밀한 선별을 위해 어류의 이동을 일시적으로 차단할 수 있는 효과가 있다. claims: 선별된 어류가 배출되는 배출공이 형성되고 상부가 개방형성된 상태로 연속적으로 배치되는 복수의 배출조와;복수의 상기 배출조의 상부에 각각 배치되어 상측으로 투입된 어류 중 일정한 크기의 어류에 한해 복수의 상기 배출조 내부로 각각 낙하시키는 복수의 선별망과;복수의 상기 배출조의 양측벽에 상측으로 연장되는 일측 연장판 및 타측 연장판으로 구성되어, 복수의 상기 선별망상으로 공급되는 어류의 이동을 안내하는 어류이동안내부와;복수의 상기 배출조 중 인접한 배출조 사이에 배치되는 격벽과, 상기 격벽을 상승시켜 상기 어류이동안내부의 이동공간을 폐쇄시키는 승강부재로 구성되는 어류이동차단부와;상기 어류이동안내부의 일측 연장판의 내면 및 타측 연장판의 내면에 형성되어 상기 격벽의 상하이동을 안내하는 가이드홈내에 구비되고, 상기 격벽의 일측과 타측에 밀착된 상태로 상기 격벽의 일측과 타측을 탄성지지하여 상기 격벽이 상승된 상태로 위치고정될 수 있도록 하는 탄성판;을 포함하여 이루어지는 것을 특징으로 하는 어류 선별기.선별된 어류가 배출되는 배출공이 형성되고 상부가 개방형성된 상태로 연속적으로 배치되는 복수의 배출조와;복수의 상기 배출조의 상부에 각각 배치되어 상측으로 투입된 어류 중 일정한 크기의 어류에 한해 복수의 상기 배출조 내부로 각각 낙하시키는 복수의 선별망과;복수의 상기 배출조의 양측벽에 상측으로 연장되는 일측 연장판 및 타측 연장판으로 구성되어, 복수의 상기 선별망상으로 공급되는 어류의 이동을 안내하는 어류이동안내부와;복수의 상기 배출조 중 인접한 배출조 사이에 배치되는 격벽과, 상기 격벽을 상승시켜 상기 어류이동안내부의 이동공간을 폐쇄시키는 승강부재로 구성되는 어류이동차단부와;복수의 상기 배출조를 일정높이로 지지하는 지지프레임과;상기 지지프레임의 전측과 후측에 각각 수직구비되는 수직가이드관과, 상기 수직가이드관의 내부에 상하이동가능하게 구비되는 상하이동관과, 상기 상하이동관을 상하이동시키는 상하이동부재와, 복수의 상기 선별망의 상부로 공급된 물이 복수의 상기 배출조의 전측에서 후측방향으로 원활히 흐를 수 있도록 상기 지지프레임의 전측 높낮이와 후측 높낮이가 서로 상이하게 조절되어 복수의 상기 배출조와 함께 상기 지지프레임이 하향경사질 경우 지면과 안정적으로 면접촉된 상태를 유지하여 복수의 상기 배출조가 안정적으로 하향경사진 상태를 유지할 수 있도록 상기 상하이동관의 하부에 상하각도조절가능하게 결합되는 바닥판부재로 구성되어 상기 지지프레임의 일측 높낮이와 타측 높낮이를 각각 조절하는 높낮이 조절부;를 포함하여 이루어지는 것을 특징으로 하는 어류 선별기., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

220/1150 Row 220: application_number: 2020180004832, combined_string: invention_title: 두족류 낚시도구 abstract: 미끼형상을 가지는 낚시도구 본체와, 낚시도구 본체의 후단에 설치되며 복수의 바늘을 포함하는 바늘군 및 바늘군의 후단으로 돌출되어 연장되도록 설치되는 지지대를 포함하는 것을 특징으로 하는 두족류 낚시도구가 개시된다. claims: 미끼형상을 가지는 낚시도구 본체;상기 낚시도구 본체의 후단에 설치되며, 복수의 바늘을 포함하는 바늘군; 및상기 바늘군의 후단으로 돌출되어 연장되도록 설치되는 지지대;를 포함하는 것을 특징으로 하는 두족류 낚시도구., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

221/1150 Row 221: application_number: 1020180119834, combined_string: invention_title: 매생이 채취장치 abstract: 본 발명은 매생이에 물을 공급하여 건조된 매생이를 축축하게 적시기 위한 물공급수단과, 상기 물에 적셔진 매생이발을 견인하기 위해 프레임의 일측에 형성되는 견인수단과, 상기 견인된 매생이발을 지지하기 위해 프레임의 상부에 형성되는 매생이발 지지수단과, 상기 견인수단의 뒤쪽에 형성되고 매생이발 지지수단에 의해 지지된 매생이발의 상하에 회전타격을 가해 매생이를 떼어내기 위한 회전타격수단으로 구성되는 매생이 채취장치를 제공하기 위한 것으로, 본 발명의 효과로는 바다에서 매생이 발을 수거하고 운반하는 과정 중에 일부는 말라붙어 덩어리지고, 가닥이 매우 가늘고 연해서 서로 잘 들러붙고 잘 엉키는 매생이를 수작업이 아닌 기계에 의해 매생이발로 부터 매생이만을 손쉽고 빠르게 분리시켜 채취할 수 있는 매우 유용한 발명인 것이다. claims: 매생이에 물을 공급하여 건조된 매생이를 축축하게 적시기 위한 물공급수단과, 상기 물에 적셔진 매생이발을 견인하기 위해 프레임의 일측에 형성되는 견인수단과, 상기 견인된 매생이발을 지지하기 위해 프레임의 상부에 형성되는 매생이발 지지수단과, 상기 견인수단의 뒤쪽에 형성되고 매생이발 지지수단에 의해 지지된 매생이발의 상하에 회전타격을 가해 매생이를 떼어내기 위한 회전타격수단으로 구성됨을 특징으로 하는 매생이 채취장치., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

222/1150 Row 222: application_number: 1020180105073, combined_string: invention_title: 집어등 기능을 가지는 두족류 낚시용 인조 미끼 abstract: 본 발명은 해저를 유영하는 오징어 또는 주꾸미 등의 두족류 어종 가까이 빛을 제공할 수 있게 함으로써, 두족류 어종을 효과적으로 유인할 수 있게 하여 어획량을 늘릴 수 있게 하는 집어등 기능을 가지는 두족류 낚시용 인조 미끼에 관한 것으로, 본 발명은 몸통부와, 몸통부의 상단 측에 하단 측에 결합되는 커버부를 가지되, 몸통부 및 커버부는 빛이 투과되는 몸체; 및 상호 결합된 몸통부와 커버부의 내부에 수용되어 빛을 발광시키는 집어수단;을 포함한다. claims: 몸통부와, 상기 몸통부의 상단 측에 하단 측에 결합되는 커버부를 가지되, 상기 몸통부 및 상기 커버부는 빛이 투과되는 몸체; 및상호 결합된 상기 몸통부와 상기 커버부의 내부에 수용되어 빛을 발광시키는 집어수단;을 포함하되,상기 몸통부의 하단에는 하나 이상의 낚싯바늘이 장착되며, 상기 커버부의 상단에는 낚싯줄이 결속되는 고리가 형성되고,상기 집어수단은 인쇄회로기판, 상기 인쇄회로기판에 실장되는 다수의 발광다이오드, 및 배터리가 끼워지는 배터리 연결단자를 포함하되, 상기 배터리 연결단자에 상기 배터리가 연결되면 상기 발광다이오드가 발광하여 빛을 외부로 발산시키는 집어등 기능을 가지는 두족류 낚시용 인조 미끼., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

223/1150 Row 223: application_number: 1020180097412, combined_string: invention_title: 어류 포획 시스템 abstract: 본 발명은 어류 포획 시스템에 관한 것으로서, 더욱 상세하게는해상에서 어군(魚群)을 탐지하고, 탐지된 어군에 대해 다방면에서 광(光)을 조사함과 동시에 음향(音響)을 방사하여 특정 영역 또는 포획장치로 몰아서 한 번에 손쉽게 어군을 이루는 어류들을 대량 포획할 수 있도록 하는 어류 포획 시스템에 관한 것이다. claims: 어군의 위치와 양 및 종류를 포함한 어군정보를 음파 또는 시각정보로 수집하여 사전에 프로그램화된 알고리즘에 따라 분석하고, 분석된 데이터에 따라 생성된 운항신호를 토대로 어군 위치로 이동하여, 해당 어군에 대한 기피신호를 출력하면서 어군을 포획장치 방향으로 몰아가는 주어군유도장치 및 상기 주어군유도장치에서 송출되는 운항신호 및 기피신호에 따라 주어군유도장치의 양 측면 방향에서 간격을 유지하면서 어군을 상기 포획장치 방향으로 몰아가는 복수의 보조어군유도장치를 포함하는 어군유도장치; 상기 어군유도장치와 통신 연결된 상태로, 특정 영역에 유입구를 갖는 어망형태로 마련되어, 송신되는 제어신호하에 유도되는 타깃 어군을 수용하여 포획하는 포획장치; 상기 어군유도장치 및 포획장치와 통신 연결된 상태로 상기 포획장치의 어군이 유입되는 개방부 측에 마련되어, 포획된 어군이 기설정된 포획량에 도달하면, 자체 제어 알고리즘 또는 어군유도장치에서 송신되는 제어신호에 따라, 상기 포획장치로 동작신호를 전송하여 포획장치의 개방부를 차단하는 차단장치;를 포함하는 것을 특징으로 하는 어류 포획 시스템., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

224/1150 Row 224: application_number: 2020180003789, combined_string: invention_title: 다운샷 및 외줄낚시 채비용 낚시 바늘 abstract: 본 고안은 주로 바닥에서 서식하는 광어와 같은 어종을 낚시 할때 사용하는 다운샷 및 외줄낚시 채비용 낚시 바늘에 관한 것으로서 보다 상세하게는,낚시대에 연결되어 있는 원줄의 일측 끝단부에 체결되는 것으로, 원줄 끝단부에 연결되는 목줄(100)과 상기 목줄(100) 일단부에 체결되는 바늘부(200)와 상기 목줄(100)의 타측 끝단부에 연결되는 봉돌(300)을 포함하고,상기 바늘부(200)는 목줄(100) 일단부에 연결되는 수직연결부(211)와 상기 수직연결부(211) 하측에서 절곡 연장되는 절곡부(212)와 상기 절곡부(212) 하측으로 절곡 연장되는 바늘(213)로 형성된 와이드훅바늘(210)과, 상기 와이드훅바늘(210)의 절곡부(212)에 삽입 연결되기 위한 고리(223)가 슬리브(222)의 결속에 의해 보조목줄(221)의 상단에 형성되어 있고 상기 보조목줄(221) 하측으로는 3개의 바늘로 이루어진 훅킹바늘(224)이 슬리브(222)에 의해 연결되어 있는 훅킹부재(220)로 포함되며,상기 와이드훅바늘(210)의 절곡부(212)는 경사진 형태로 이루어져 있으며 일측에 걸림턱(214)을 구비하여 상기 훅킹부재(220)의 고리(223)가 절곡부(212)에 삽입된 후 제차 이탈하는 것을 방지할 수 있도록 한 것을 특징으로 하여,본 고안은 통으로 된 미끼의 측면만 먹고 낚시 바늘은 물지 않아 발생하는 훅킹의 어려움을 해결하기 위해 별도의 훅킹부재를 구비하여 물고기가 통으로 된 미끼의 측면부터 먹더라도 훅킹이 용이해 우수한 조과를 기대할 수 있는 다운샷 및 외줄낚시 채비용 낚시 바늘에 관한 것이다. claims: 낚시대에 연결되어 있는 원줄의 일측 끝단부에 체결되는 것으로, 원줄 끝단부에 연결되는 목줄(100)과 상기 목줄(100) 일단부에 체결되는 바늘부(200)와 상기 목줄(100)의 타측 끝단부에 연결되는 봉돌(300)을 포함하고,상기 바늘부(200)는 목줄(100) 일단부에 연결되는 수직연결부(211)와 상기 수직연결부(211) 하측에서 절곡 연장되는 절곡부(212)와 상기 절곡부(212) 하측으로 절곡 연장되는 바늘(213)로 형성된 와이드훅바늘(210)과, 상기 와이드훅바늘(210)의 절곡부(212)에 삽입 연결되기 위한 고리(223)가 슬리브(222)의 결속에 의해 보조목줄(221)의 상단에 형성되어 있고 상기 보조목줄(221) 하측으로는 3개의 바늘로 이루어진 훅킹바늘(224)이 슬리브(222)에 의해 연결되어 있는 훅킹부재(220)로 포함되며,상기 와이드훅바늘(210)의 절곡부(212)는 경사진 형태로 이루어져 있으며 일측에 걸림턱(214)을 구비하여 상기 훅킹부재(220)의 고리(223)가 절곡부(212)에 삽입된 후 제차 이탈하는 것을 방지할 수 있도록 한 것을 특징으로 하는 다운샷 및 외줄낚시 채비용 낚시 바늘., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

225/1150 Row 225: application_number: 2020180003729, combined_string: invention_title: 원활한 김발 이송을 위한 물공급 수단을 갖는 물김 자동 채취장치 abstract: 본 고안은 원활한 김발 이송을 위한 물공급 수단을 갖는 물김 자동 채취장치에 있어서, 특히 동력장치를 이용하여 물김을 채취하되 물김을 절단칼날로 인입하는 과정에서 보다 용이하게 인입되면서 자연스럽게 절단작업이 이루어지도록하고, 더불어 이송되는 김발에 물을 공급하여 김발이 뻑뻑하지 않고 원활하게 이송되도록함으로서 생산효율을 극대화시키도록 구성한 것을 특징으로 하는 물김 자동 채취장치에 관한 것으로,김발(B)에 매달려있는 물김(A)을 절단하여 하부로 배출하기 위한 절단유닛(110)과; 상기 절단유닛(110)의 전후 각도를 조절할 수 있도록 형성하는 조절유닛(120)과; 상기 절단유닛(110)을 회전시키기 위한 구동유닛(130)을 포함하고; 상기 절단유닛(110)은 회전축(111)과; 상기 회전축(111)의 양측에 형성하는 한 쌍의 지지부(112)와; 상기 지지부(112)의 사이를 연결하되 하부에 길이방향을 따라서 절단된 물김(C)을 배출하기 위한 배출공간(10)을 형성하는 배출부(113)와; 상기 회전축(111)의 외측에 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 보강부(114)와; 다수개의 상기 보강부(114)를 연결하여 물김을 절단하기 위한 다수개의 절단날(115)과; 다수개의 상기 절단날(115)의 외측에 빙둘러 형성하여 상기 배출부(113)와 연결하되 상기 절단날(115)의 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 유도부(116)와; 상기 배출부(113)의 후방에서 전방으로 빙둘러 마련하여 김발이 통과하면서 상기 절단날(115)이 물김을 절단할 수 있도록 절단공간(20)을 형성하는 마감부(117)로 구성하는 것이 특징이다. claims: 김발을 통해 이동되는 물김을 절단하기 위한 절단수단(100)과; 상기 절단수단(100)의 전면에 위치하여 김발이 절단수단(100)으로 인입하는 과정에서 회전하면서 가이드하여 김발이 원활하게 절단수단(100)으로 인입되도록 유도하는 회전용 롤러수단(200)을 포함하고;상기 절단수단(100)은,김발(B)에 매달려있는 물김(A)을 절단하여 하부로 배출하기 위한 절단유닛(110)과; 상기 절단유닛(110)의 전후 각도를 조절할 수 있도록 형성하는 조절유닛(120)과; 상기 절단유닛(110)을 회전시키기 위한 구동유닛(130)을 포함하며;상기 절단유닛(110)은,회전축(111)과; 상기 회전축(111)의 양측에 형성하는 한 쌍의 지지부(112)와; 상기 지지부(112)의 사이를 연결하되 하부에 길이방향을 따라서 절단된 물김(C)을 배출하기 위한 배출공간(10)을 형성하는 배출부(113)와; 상기 회전축(111)의 외측에 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 보강부(114)와; 다수개의 상기 보강부(114)를 연결하여 물김을 절단하기 위한 다수개의 절단날(115)과; 다수개의 상기 절단날(115)의 외측에 빙둘러 형성하여 상기 배출부(113)와 연결하되 상기 절단날(115)의 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 유도부(116)와; 상기 배출부(113)의 후방에서 전방으로 빙둘러 마련하여 김발이 통과하면서 상기 절단날(115)이 물김을 절단할 수 있도록 절단공간(20)을 형성하는 마감부(117)로 구성하고;상기 조절유닛(120)은,상기 절단유닛(110)의 지지부(112)를 감싸도록 형성하는 고정부(121)와; 상기 고정부(121)의 일측을 절단하고 그 사이에 개방공간(122a)을 형성하는 개방부(122)와; 상기 개방부(122)를 내측 또는 외측으로 이동시켜 상기 고정부(121)가 지지부(112)를 밀착시켜 고정하기 위한 고정부재(123)와; 상기 개방부(122)의 내측에 형성하여 상기 지지부(112)의 외측에 밀착하는 밀착부(124)와; 상기 고정부(121)의 하부에 형성하여 선박에 고정하는 고정몸체(125)로 구성하고;상기 회전용 롤러수단(200)은,상기 고정몸체에 일단이 결합되며 내측에 공간부를 형성한 원통형 파이프 형태로 이루어지되, 파지하기에 용이한 형태로 이루어지는 지지몸체(210)와;상기 지지몸체에 일정간격을 두고 형성되며, 회전용 롤러수단의 결합위치를 자유롭게 선택할 수 있도록 유도하는 결합홀(211)과;상기 지지몸체에 일체형으로 연결하되 기억자 형태로 이루어지고, 내측에 공간부를 형성하며, 수직방향으로 위치되는 지지몸체와 수평방향으로 위치되는 회전봉을 상호 연결하는 연결몸체(220)와;상기 연결몸체의 상부 끝단 내부에 위치하며 다수개의 구형태로 이루어져 자유회전이 가능하도록하여 회전봉이 자체 회전이 이루어지도록 유도하는 베어링(221)과;상기 연결몸체의 양측에 결합하되 자유회전이 가능하여 김발을 이송시에 회전봉의 자유회전에 따라서 슬라이딩 이동이 가능하게 하는 회전봉(230)과; 상기 회전봉으로부터 일정길이 돌출 성형되며, 베어링과 외주연이 맞물려서 상기 베어링과 섭동되면서 회전봉의 회전을 유도하는 결합축(231)과;상기 고정몸체에 일측이 고정되며, 원통형 파이프 형상의 가이드봉을 구비하고, 상기 가이드봉에 지지몸체를 수납하여 체결시키는 체결수단(250)과;상기 체결수단을 통해 지지몸체를 고정시키되 지지몸체의 결합홀을 통과하면서 고정시키는 체결볼트(251)와;상기 회전봉의 몸체에 다수개 형성되어 김발에 물을 공급하여 자연스러운 김발의 이동을 유도하는 물배출용 홀(240)을 포함하여 구성함을 특징으로 하는 원활한 김발 이송을 위한 물공급 수단을 갖는 물김 자동 채취장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

226/1150 Row 226: application_number: 1020180094071, combined_string: invention_title: 물김 자동 채취장치 abstract: 본 발명은 물김 자동 채취장치에 있어서, 특히 동력장치를 이용하여 물김을 채취하되 물김을 절단칼날로 인입하는 과정에서 보다 용이하게 인입되면서 자연스럽게 절단작업이 이루어지도록하고, 더불어 이송되는 김발에 물을 공급하여 김발이 뻑뻑하지 않고 원활하게 이송되도록함으로서 생산효율을 극대화시키도록 구성한 것을 특징으로 하는 물김 자동 채취장치에 관한 것으로,김발(B)에 매달려있는 물김(A)을 절단하여 하부로 배출하기 위한 절단유닛(110)과; 상기 절단유닛(110)의 전후 각도를 조절할 수 있도록 형성하는 조절유닛(120)과; 상기 절단유닛(110)을 회전시키기 위한 구동유닛(130)을 포함하고; 상기 절단유닛(110)은 회전축(111)과; 상기 회전축(111)의 양측에 형성하는 한 쌍의 지지부(112)와; 상기 지지부(112)의 사이를 연결하되 하부에 길이방향을 따라서 절단된 물김(C)을 배출하기 위한 배출공간(10)을 형성하는 배출부(113)와; 상기 회전축(111)의 외측에 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 보강부(114)와; 다수개의 상기 보강부(114)를 연결하여 물김을 절단하기 위한 다수개의 절단날(115)과; 다수개의 상기 절단날(115)의 외측에 빙둘러 형성하여 상기 배출부(113)와 연결하되 상기 절단날(115)의 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 유도부(116)와; 상기 배출부(113)의 후방에서 전방으로 빙둘러 마련하여 김발이 통과하면서 상기 절단날(115)이 물김을 절단할 수 있도록 절단공간(20)을 형성하는 마감부(117)로 구성하는 것이 특징이다. claims: 김발을 통해 이동되는 물김을 절단하기 위한 절단수단(100)과; 상기 절단수단(100)의 전면에 위치하여 김발이 절단수단(100)으로 인입하는 과정에서 회전하면서 가이드하여 김발이 원활하게 절단수단(100)으로 인입되도록 유도하는 회전용 롤러수단(200)을 포함하고;상기 절단수단(100)은,김발(B)에 매달려있는 물김(A)을 절단하여 하부로 배출하기 위한 절단유닛(110)과; 상기 절단유닛(110)의 전후 각도를 조절할 수 있도록 형성하는 조절유닛(120)과; 상기 절단유닛(110)을 회전시키기 위한 구동유닛(130)을 포함하며;상기 절단유닛(110)은,회전축(111)과; 상기 회전축(111)의 양측에 형성하는 한 쌍의 지지부(112)와; 상기 지지부(112)의 사이를 연결하되 하부에 길이방향을 따라서 절단된 물김(C)을 배출하기 위한 배출공간(10)을 형성하는 배출부(113)와; 상기 회전축(111)의 외측에 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 보강부(114)와; 다수개의 상기 보강부(114)를 연결하여 물김을 절단하기 위한 다수개의 절단날(115)과; 다수개의 상기 절단날(115)의 외측에 빙둘러 형성하여 상기 배출부(113)와 연결하되 상기 절단날(115)의 길이방향을 따라서 일정간격 떨어지도록 형성하는 다수개의 유도부(116)와; 상기 배출부(113)의 후방에서 전방으로 빙둘러 마련하여 김발이 통과하면서 상기 절단날(115)이 물김을 절단할 수 있도록 절단공간(20)을 형성하는 마감부(117)로 구성하고;상기 조절유닛(120)은,상기 절단유닛(110)의 지지부(112)를 감싸도록 형성하는 고정부(121)와; 상기 고정부(121)의 일측을 절단하고 그 사이에 개방공간(122a)을 형성하는 개방부(122)와; 상기 개방부(122)를 내측 또는 외측으로 이동시켜 상기 고정부(121)가 지지부(112)를 밀착시켜 고정하기 위한 고정부재(123)와; 상기 개방부(122)의 내측에 형성하여 상기 지지부(112)의 외측에 밀착하는 밀착부(124)와; 상기 고정부(121)의 하부에 형성하여 선박에 고정하는 고정몸체(125)로 구성하고;상기 회전용 롤러수단(200)은,상기 고정몸체에 일단이 결합되며 내측에 공간부를 형성한 원통형 파이프 형태로 이루어지되, 파지하기에 용이한 형태로 이루어지는 지지몸체(210)와;상기 지지몸체에 일정간격을 두고 형성되며, 회전용 롤러수단의 결합위치를 자유롭게 선택할 수 있도록 유도하는 결합홀(211)과;상기 지지몸체에 일체형으로 연결하되 기억자 형태로 이루어지고, 내측에 공간부를 형성하며, 수직방향으로 위치되는 지지몸체와 수평방향으로 위치되는 회전봉을 상호 연결하는 연결몸체(220)와;상기 연결몸체의 상부 끝단 내부에 위치하며 다수개의 구형태로 이루어져 자유회전이 가능하도록하여 회전봉이 자체 회전이 이루어지도록 유도하는 베어링(221)과;상기 연결몸체의 양측에 결합하되 자유회전이 가능하여 김발을 이송시에 회전봉의 자유회전에 따라서 슬라이딩 이동이 가능하게 하는 회전봉(230)과; 상기 회전봉으로부터 일정길이 돌출 성형되며, 베어링과 외주연이 맞물려서 상기 베어링과 섭동되면서 회전봉의 회전을 유도하는 결합축(231)과;상기 고정몸체에 일측이 고정되며, 원통형 파이프 형상의 가이드봉을 구비하고, 상기 가이드봉에 지지몸체를 수납하여 체결시키는 체결수단(250)과;상기 체결수단을 통해 지지몸체를 고정시키되 지지몸체의 결합홀을 통과하면서 고정시키는 체결볼트(251)와;상기 회전봉의 몸체에 다수개 형성되어 김발에 물을 공급하여 자연스러운 김발의 이동을 유도하는 물배출용 홀(240)을 포함하여 구성하며;상기 회전봉에 외주연에 설치되어 김발에 의해서 가해지는 압력값을 채크하는 압력센싱수단(400)과;상기 압력센싱수단(400)에 의해서 채크된 압력값에 의해서 외부 물공급수단의 물공급량을 조절하는 제어부(500)와;상기 제어부의 제어에 의해서 외부 물공급수단(300)의 물을 회전봉으로 펌핑하여 물배출용 홀을 통해 물을 출력시키는 펌프(310)를 포함하여 구성함을 특징으로 하는 물김 자동 채취장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

227/1150 Row 227: application_number: 1020180091406, combined_string: invention_title: 부류식 물김 자동 채취장치 abstract: 본 개시는 부류식 김양식에서 장치를 이용해 자동으로 김발을 뒤집거나 또는 채취를 위해 어선으로 건져 올릴 수 있고, 노출과 침수를 번갈아가며 김발을 효율적으로 뒤집을 수 있어 우수한 품질의 김 생산이 가능하고, 이로 인한 사업 증대가 도모되며, 파고, 풍량, 바람, 해수 등의 기상적인 요인 및 어선내 바닥의 미끄러움, 각종 장비와 구조상의 요인 등에 따른 문제점으로 인한 작업의 어려움없이 안전하게 김발로부터 김을 채취할 수 있고, 비교적 간단한 구성을 가져 제작 및 설치가 용이하고, 이를 통해 김양식 어선에 접목이 쉬워 보급 활성화가 도모되며, 사용성과 경제성이 우수한 장점을 갖는 부류식 물김 자동 채취장치에 관한 것이다.본 개시의 실시예에 따른 부류식 물김 자동 채취장치는, 부류식 김 양식을 위해 사용되는 선박의 측면 일측에 결합되는 어선결합몸체부와, 상기 어선결합몸체부에 회전 가능하게 결합되어 상기 선박의 내측 상부면과 외측 하부면의 사이에서 상하로 회동되는 회동암부 및 상기 회동암부에 설치되어 상기 회동암부의 회전에 의해 상하로 회동되며, 상기 어선의 외측 하부면에 위치되면 김 양식을 위한 김발을 걸어 상기 회동암부의 회동으로 상기 어선의 내측 상부면으로 상기 김발을 건져 올리는 걸이부를 포함하여 이루어지는 것을 특징으로 한다. claims: 부류식 김 양식을 위해 사용되는 선박의 측면 일측에 결합되는 어선결합몸체부;상기 어선결합몸체부에 회전 가능하게 결합되어 상기 선박의 내측 상부면과 외측 하부면의 사이에서 상하로 회동되는 회동암부; 및상기 회동암부에 설치되어 상기 회동암부의 회전에 의해 상하로 회동되며, 상기 어선의 외측 하부면에 위치되면 김 양식을 위한 김발을 걸어 상기 회동암부의 회동으로 상기 어선의 내측 상부면으로 상기 김발을 건져 올리는 걸이부;를 포함하여 이루어지는 것을 특징으로 하는 부류식 물김 자동 채취장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

228/1150 Row 228: application_number: 1020180087454, combined_string: invention_title: 가압부상방식을 이용한 미세조류 수확장치 abstract: 본 발명은 가압부상방식을 이용한 미세조류 수확장치에 관한 것으로서, 본 발명에 따른 가압부상방식을 이용한 미세조류 수확장치는, 상측이 개방되고 평면이 장방형으로 형성되는 박스형상의 부상조 하우징(100); 상기 부상조 하우징의 일측 전단면을 관통하게 설치되어 배양이 완료된 스피루리나 미세조류와 부상용수를 상기 부상조 하우징의 내부로 공급하는 미세조류 공급부(200)와; 상기 미세조류 공급부(200)와 인접하게 설치되어 미세기포를 발생시키고 상기 부상조 하우징의 내부로 공급되는 스피루리나 미세조류에 미세기포를 함침시키는 미세기포 발생부(300)와; 상기 부상조 하우징(100)의 수면위로 부상하는 부상용수의 흐름에 변화를 주기 위하여 상기 부상용수의 흐름방향을 제어하는 플레이트 패널을 상기 부상조 하우징의 횡방향 수직으로 설치하여 구비하며 상기 플레이트 패널의 각도 조절이 가능한 배플 플레이트부(400)와; 상기 배플 플레이트부(400)를 통과하여 부상하는 스피루리나 미세조류를 상기 부상조 하우징(100)의 수면위에서 채집하기 위하여 상기 부상조 하우징(100)의 내측에서 높낮이 조절이 가능한 격벽으로 설치되는 부상조 웨어 패널부(500)와; 상기 부상조 웨어 패널부(500)에 의해 채집되는 스피루리나 미세조류를 상기 부상조 하우징(100)의 수면위에서 걷어내기 위한 스키머 장치(600); 및 상기 부상조 하우징(100)의 타측 후단면을 관통하게 설치되며 스피루리나 미세조류를 채집하고 남은 부상용수를 배출하기 위한 배출구(700);를 포함할 수 있다.따라서, 본 발명은, 부상용수의 속도 및 방향을 조절할 수 있는 수류가변형 배플 플레이트부와 수면위로 부상되는 스피루리나를 효율적으로 채집할 수 있도록 높이조절이 가능한 부상조웨어를 구비하여 스피루리나 미세조류의 수확효율을 높일 수 있는 가압부상방식을 이용한 미세조류 수확장치를 제공하는 효과가 있다. claims: 상측이 개방되고 평면이 장방형으로 형성되는 박스형상의 부상조 하우징(100);상기 부상조 하우징의 일측 전단면을 관통하게 설치되어 배양이 완료된 스피루리나 미세조류와 부상용수를 상기 부상조 하우징의 내부로 공급하는 미세조류 공급부(200)와;상기 미세조류 공급부(200)와 인접하게 설치되어 미세기포를 발생시키고 상기 부상조 하우징의 내부로 공급되는 스피루리나 미세조류에 미세기포를 함침시키는 미세기포 발생부(300)와;상기 부상조 하우징(100)의 수면위로 부상하는 부상용수의 흐름에 변화를 주기 위하여 상기 부상용수의 흐름방향을 제어하는 플레이트 패널을 상기 부상조 하우징의 횡방향 수직으로 설치하여 구비하며 상기 플레이트 패널의 각도 조절이 가능한 배플 플레이트부(400)와;상기 배플 플레이트부(400)를 통과하여 부상하는 스피루리나 미세조류를 상기 부상조 하우징(100)의 수면위에서 채집하기 위하여 상기 부상조 하우징(100)의 내측에서 높낮이 조절이 가능한 격벽으로 설치되는 부상조 웨어 패널부(500)와;상기 부상조 웨어 패널부(500)에 의해 채집되는 스피루리나 미세조류를 상기 부상조 하우징(100)의 수면위에서 걷어내기 위한 스키머 장치(600); 및상기 부상조 하우징(100)의 타측 후단면을 관통하게 설치되며 스피루리나 미세조류를 채집하고 남은 부상용수를 배출하기 위한 배출구(700);를 포함하는 것을 특징으로 하는 가압부상방식을 이용한 미세조류 수확장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

229/1150 Row 229: application_number: 1020180077554, combined_string: invention_title: 낚시용 미끼 보조장치 abstract: 본 발명은 낚시 미끼와 함께 발광하거나 움직이는 미끼 보조장치에 관한 것이다. 보다 상세하게는 낚시 바늘에 끼워지는 미끼부와 제어부가 분리되어 미끼가 끼워진 상태에서 낚시 바늘과 미끼가 발광하여 움직여서 물고기를 잘 유인할 수 있도록 하는 미끼 보조장치에 관한 것이다. claims: 전원, 회로부, 및 스위치를 구비한 제어전원부;발광체와 모터 중 어느 하나 또는 둘을 구비한 미끼부; 및상기 제어전원부와 상기 미끼부를 연결하는 전선;을 포함하며상기 제어전원부, 미끼부, 및 전선은 모두 방수처리되며, 그리고상기 제어전원부에 의해서 상기 발광체와 모터이 작동되는 것,을 특징으로 하는 미끼 보조장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

230/1150 Row 230: application_number: 1020210071286, combined_string: invention_title: 그물 구조물 abstract: 그물 구조물을 제공한다. 그물 구조물은 이웃하는 곶들 사이의 만 지형에 그 하단부가 고정되도록 설치된 그물 및 상기 그물 상단부와 결합되어 상기 그물을 상하부로 이동시키는 이동 유닛을 포함한다. 상기 이동 유닛은 상기 그물의 상단부에 연결되는 도르래, 상기 도르래에 연결되는 윈치, 및 상기 그물의 상단부, 상기 도르래, 및 상기 윈치를 연결하는 와이어를 포함하고, 상기 만으로 바닷물이 유입될 때 상기 그물의 하단부는 고정되되 상기 그물의 상단부를 상기 이동 유닛을 이용하여 상부로 끌어 올려 상기 그물을 커튼 형식으로 펼쳐 상기 만의 일 측을 덮는다. claims: 이웃하는 곶들 사이의 너비와 만의 바닥에 곶의 상부까지의 거리에 따라 크기가 결정되는 그물;상기 그물의 상단에 설치되고, 상기 이웃하는 곶들 사이의 너비에 따라 크기가 결정되는 그물 상단부;상기 그물의 하단에 설치되고, 상기 만의 바닥에 고정되도록 설치되는 그물 하단부;상기 이웃하는 곶들 사이의 만 지형에 상기 그물 하단부가 고정되도록 설치되는 고정 유닛; 및상기 그물 상단부와 결합되어 상기 그물을 상하부로 이동시키는 이동 유닛을 포함하되,상기 이동 유닛은 상기 그물 상단부의 양단에 각각 연결되어 상기 이웃하는 곶들에 두 개가 각각 설치되는 그물 구조물., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

231/1150 Row 231: application_number: 1020210030572, combined_string: invention_title: 부상이동식 친환경 인공어초 abstract: 본 발명은 부상이동식 친환경 인공어초에 관한 것으로, 보다 상세하게는 하나의 콘크리트 블록 일체로 이루어지며, 단독으로도 인공어초(100)로 사용 가능하고 복수의 인공어초(100)를 상하로 적층하여서도 사용 가능한 인공어초(100)로서, 상기 인공어초(100)는, 내부에 어류 또는 패류를 보호하기 위한 보호공간이 형성되고, 직육면체 형상으로 형성된 본체부(110); 상기 본체부(110)의 4면에 각각 돌출 형성되어 적층시 다른 인공어초(100)와의 공간을 확보하기 위한 날개부(120)를 포함한다. 본 발명의 실시예에서는, 제작비용이 저렴하고, 운반비용이 감소하고, 상하차 비용이 생략되고, 바지선 크레인이 불필요하다. claims: 하나의 콘크리트 블록 일체로 이루어지며, 단독으로도 인공어초(100)로 사용 가능하고 복수의 인공어초(100)를 상하로 적층하여서도 사용 가능한 인공어초(100)로서,상기 인공어초(100)는,내부에 어류 또는 패류를 보호하기 위한 보호공간이 형성되고, 직육면체 형상으로 형성된 본체부(110);상기 본체부(110)의 4면에 각각 돌출 형성되어 적층시 다른 인공어초(100)와의 공간을 확보하기 위한 날개부(120)를 포함하고,상기 본체부(110)는 직육면체이고,상기 본체부(110)의 6면에는 각각 어류 또는 패류의 출입이 가능하도록 입구(111)가 형성되며,상기 본체부(110)의 입구(111)에는 뚜껑(130)이 밀봉되어 장착되는 것을 특징으로 하고,상기 뚜껑(130)은 수밀성 재질로서 FRP 원형 뚜껑(130)이고,상기 뚜껑(130)은,인장 케이블(142)이 고정장치(131)에 인장되어 있고, 고정장치(131)의 고정핀이 풀리면, 뚜껑(130)이 오픈되는 구조이고,상기 뚜껑(130)의 밀봉에 의하여 인공어초(100)는 수중에서 부상이동이 가능하며,회수 케이블(152)을 이용하여 상기 복수개의 뚜껑(130)을 한번에 회수하는 것을 특징으로 하고,상기 뚜껑(130)은 케이블(172)에 고정되고, 케이블이 당겨지면 상기 뚜껑(130)이 제거되는 것을 특징으로 하는 부상이동식 친환경 인공어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

232/1150 Row 232: application_number: 1020210015930, combined_string: invention_title: 부유성 산란어류의 산란장 조성시스템 abstract: 본 발명은 부유성 산란어류의 산란장 조성시스템에 관한 것으로서, 보다 상세하게는 해저면에 구비되는 복수의 제1수중와이어와, 이 제1수중와이어의 어느 한 지점을 서로 연결하는 제2수중와이어를 통하여 중층에서 산란하는 어류나 어패류의 산란장을 조성하고, 상기 제1수중와이어 및 제2수중와이어를 연결유닛을 통해 고정함에 따라 수중 작업을 보다 손쉽게 하며, 해수면에 위치하는 제1부구와 수중에 위치하는 제2부구를 통하여 조류 등에 의한 해수면의 높이 변화가 있더라도 제1수중와이어의 텐션을 유지할 수 있도록 고안된 부유성 산란어류의 산란장 조성시스템에 관한 것이다. claims: 해저면에 서로 이격되어 구비되는 복수의 제1수중와이어;상기 각각의 제1수중와이어의 어느 한 지점을 서로 연결하도록 구비되는 제2수중와이어;상기 제1수중와이어에 구비되어, 상기 제1수중와이어에 연결되는 제2수중와이어를 부상시키는 부구;상기 제1수중와이어의 특정 위치에 고정되어, 상기 제2수중와이어를 결합하는 연결유닛;을 포함하여 이루어지되,상기 연결유닛은제2수중와이어가 체결되는 체결부와, 상기 체결부로부터 절곡형성되어, 상기 제1수중와이어가 안착되는 와이어결합부 및 상기 제1수중와이어를 일방향에서 끼워 상기 와이어결합부에 안착시키도록 상기 와이어결합부에 형성되는 끼움공을 포함하여 이루어지는 것을 특징으로 하고,상기 끼움공은상기 와이어결합부에 둘 이상으로 일단이 개방된 개방부를 갖도록 구비되어, 상기 와이어를 개방부를 통해 끼움결합시키되, 상기 와이어가 지그재그형상으로 결합되도록 이루어지는 것을 특징으로 하는 부유성 산란어류의 산란장 조성시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

233/1150 Row 233: application_number: 1020200181923, combined_string: invention_title: 인공 수초형 어류산란장 조성용 구조물 abstract: 본 발명은 저수지, 강, 댐 등에 별도의 프레임을 구성하지 않고 어류가 산란 및 서식할 수 있는 공간을 간편하고 신속하게 설치 및 철거할 수 있고 구조가 간단한 인공 수초형 어류산란장 조성용 구조물에 관한 것이다.즉, 본 발명은 일정 길이의 지지로프와, 상기 지지로프에 매달림 형태로 등간격 구비되어 있는 다수의 인공수초와, 상기 인공수초가 설치된 범위내의 지지로프에 일정 간격으로 무게추 및 제2부구가 각각 연결되어 지지로프가 수중 부유할 수 있도록 한 것을 포함하며, 상기 인공수초가 설치된 범위의 외측에 위치한 지지로프에 연결되는 제1부구와, 상기 제1부구와 연결된 지지로프의 양끝단에 설치되어 수중 바닥면에 고정되는 앵커부재로 이루어진 것인공 수초형 어류산란장 조성용 구조물을 특징으로 한다. claims: 일정 길이의 지지로프(10)와, 상기 지지로프(10)에 매달림 형태로 등간격 구비되어 있는 다수의 인공수초(20)와, 상기 인공수초(20)가 설치된 범위내의 지지로프(10)가 일정한 잠수깊이로 수중 부유할 수 있도록 한 수중유도부재(30)와, 상기 인공수초(20)가 설치된 범위의 외측에 위치한 지지로프(10)에 연결되는 제1부구(40)와, 상기 제1부구(40)와 연결된 지지로프(10)의 양끝단에 설치되어 수중 바닥면에 고정되는 앵커부재(50)를 길이가 조절되는 가변형 지지로프(10a)로 연결하되 제1부구(40)에 가이드로울(60)을 구비하여 가변형 지지로프(10a)를 슬라이딩 안내되게 연결한 다음 가변형 지지로프(10a)의 상부 끝단은 장력유지용 무게추(70)가 연결된 구성으로 이루어지며,상기 수중유도부재(30)는 인공수초(20)가 설치된 범위내의 지지로프(10)에 일정 간격으로 무게추(36) 및 제2부구(32)가 각각 연결되고, 상기 제2부구(32)의 하부에 수직으로 일정 길이의 지지대(38) 상단이 연결되고, 지지대(38) 하단은 지지로프(10)와 연결되어 지지로프(10)가 수중 부유할 수 있도록 한 것을 특징으로 하는 인공 수초형 어류산란장 조성용 구조물., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

234/1150 Row 234: application_number: 1020200127923, combined_string: invention_title: 수산 질병 관리 시스템, 방법 및 프로그램 abstract: 본 발명의 일 실시예에 따른 수산 질병 관리 시스템은 주기적인 모니터링이 필요한 양식장을 포함한 수산질병 관리 장소에 설치된 카메라 및 센서로부터 각각 영상 데이터, 센싱 데이터를 수집하고, 통신망과 연결되어 관리서버로 데이터를 전송하는 데이터수집장치; 및 상기 데이터수집장치로부터 수집된 데이터를 기반으로 어류의 질병 원인을 분석 및 질병 진단을 하고, 진단 결과에 따라 처방을 생성하고, 관리단말기로 분석 데이터, 진단 결과 및 처방을 전송하는 상기 관리서버를 포함한다. claims: 주기적인 모니터링이 필요한 양식장을 포함한 수산질병 관리 장소에 설치된 카메라 및 센서로부터 각각 영상 데이터, 센싱 데이터를 수집하고, 통신망과 연결되어 관리서버로 데이터를 전송하는 데이터수집장치;상기 데이터수집장치로부터 수집된 데이터를 기반으로 어류의 질병 원인을 분석 및 질병 진단을 하고, 진단 결과에 따라 처방을 생성하고, 관리단말기로 분석 데이터, 진단 결과 및 처방을 전송하는 상기 관리서버를 포함하는 수산 질병 관리 시스템.데이터수집장치는 수산질병 관리 장소에 설치된 카메라의 영상 데이터 또는 센서의 센싱 데이터를 수집하고, 관리서버로 수집된 데이터를 전송하는 단계;상기 관리서버는 수집된 데이터 기반으로 질병원인을 통하여 질병 분석 및 예측을 수행하는 단계;상기 관리서버는 분석 및 진단 결과를 보고서 또는 통계 자료 형태로 생성하고, 분석 및 진단 결과에 따라 미리 설정된 처방을 생성하는 단계;상기 관리서버는 진단 결과 및 처방을, 연동되는 관리 프로그램을 통하여 관리자가 소지한 관리단말기로 전송하는 단계를 포함하는 수산 질병 관리 방법.제6항 내지 제9항 중 어느 한 항의 수산 질병 관리 방법을 수행하는 컴퓨터로 읽을 수 있는 저장매체에 저장된 컴퓨터 프로그램., Ltext: 어업, prediction: '어업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

235/1150 Row 235: application_number: 1020200116246, combined_string: invention_title: 갑오징어 수정란 부착용 인공조초 abstract: 본 발명의 해저면 상에 고정 설치되는 산란초 고정부; 상기 산란초 고정부에는 산란초의 하부 말단부가 일정간격으로 하나 이상 연결 고정되어 이루어지는 갑오징어 산란장치를 제공함으로써, 서식과 산란 장소를 동시에 제공하는 한편, 자연상태의 갑오징어 개체수를 증가시킬 수 있는 효과가 있다. claims: 일정 길이와 너비를 가지는 가로 및 세로부재 말단이 연결되어 상부틀을 형성하고, 상기 상부틀 내측에는 가로 또는 세로 부재가 하나 이상 이격되어 설치되는 고정부재부와 상부틀 하부에는 상부틀이 해저면과 일정 높이로 이격 설치될 수 있도록 지지부가 형성되어 이루어지는 산란초 고정부가 해저면 상에 고정되고;일정 길이를 갖는 직경 5-10mm의 폴리에틸렌 재질의 로프 복수개를 반으로 접어 접힌 하단부를 고정하여 묶음형태를 이루는 부착부와 상기 부착부 상단부에는 로프를 매개로 일단에 부자가 연결된 부력부를 형성한 산란초가 상기 상부틀과 고정부재부 상면에 일정간격으로 이격되어 복수개 설치되며; 상기 산란초가 설치된 상부틀과 고정부재부 상면의 이격공간에는 일정길이를 갖는 직경 2-3mm의 로프가 무작위 다발형상으로 얽혀지도록 이루어진 부착기질부가 형성되는 것을 특징으로 하는 갑오징어 수정란 부착용 인공조초, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

236/1150 Row 236: application_number: 1020200110703, combined_string: invention_title: 뻘 바닥 또는 모래 바닥에 묻혀 움직이지 않도록 하는 패각용 주꾸미 포획어구 abstract: 본 발명은 뻘 바닥 또는 모래 바닥에 위치하는 상부몸체 또는 하부몸체가 바닷물의 흐름(조류)이 심할 경우에 패각용 주꾸미 포획어구의 상부몸체와 하부몸체의 외측면에 형성된 다수개의 돌출부 사이로 뻘 또는 모래가 침투하여 하부몸체의 일부가 뻘 바닥 또는 모래 바닥에 묻히어 패각용 주꾸미 포획어구가 조류에 유동하지 않고 고정되어 있게 하므로써 주꾸미가 자신의 몸을 완전히 은폐시켜 은신을 위한 안전한 서식처 또는 산란처로 인식하여 패각용 주꾸미 포획어구에 숨어 있는 상태에서 포획어구를 끌어 올려 어획량을 증대시키며, 끌어 올려진 상, 하부몸체의 표면에 형성되어 있는 미끄럼이 없는 돌기부를 손바닥으로 눌러 비틀어서 주꾸미를 용이하게 꺼낼수 있도록 하는 패각용 주꾸미 포획어구에 관한 것이다.본 발명은 조개껍질형상으로 형성된 상부몸체(2)와, 상부몸체(2)와 상하대칭을 이루는 조개껍질형상으로 형성되는 하부몸체(3)로 이루어지고, 상기 상부몸체(2)와 하부몸체(3)의 후단부에는 끈삽입공(4a)(4b)이 각각 관통 형성되거나 결속용 고리부(5a)(5b)가 각각 돌출 형성되며, 상기 상부몸체(2)와 하부몸체(3)는 후단부에 형성된 끈삽입공(4a)(4b) 또는 결속용 고리부(5a)(5b)에 삽입되는 결속용 끈(6)에 의하여 결합되는 주꾸미 포획용 어구에 있어서, 상기 상부몸체(2)와 하부몸체(3)의 외측 표면에는 5 ~ 10mm의 높이로 소뿔 형태의 타원형으로 형성된 다수개의 돌출부(7)가 일정한 간격을 두고 분포 형성되며, 상기 다수개의 돌출부(7)는, 상부몸체(2)와 하부몸체(3)의 외측 표면에 일정 간격을 두고 30개 내지 50개가 골고루 분포 형성되고, 상기 상,하부몸체(2)(3)와, 결속용 고리부(5a)(5b)와, 다수개의 돌출부(7)는, 25 ~ 35중량%의 ABS수지 또는 HIPS수지와 65 ~ 75중량%의 칼페트가 혼합되는 물보다 비중이 큰 합성수지재질로 이루어져 뻘 바닥 또는 모래 바닥에 묻혀 움직이지 않도록 하는 것을 특징으로 한다. claims: 조개껍질형상으로 형성된 상부몸체(2)와, 상부몸체(2)와 상하대칭을 이루는 조개껍질형상으로 형성되는 하부몸체(3)로 이루어지고,상기 상부몸체(2)와 하부몸체(3)의 후단부에는 끈삽입공(4a)(4b)이 각각 관통 형성되거나 결속용 고리부(5a)(5b)가 각각 돌출 형성되며,상기 상부몸체(2)와 하부몸체(3)는 후단부에 형성된 끈삽입공(4a)(4b) 또는 결속용 고리부(5a)(5b)에 삽입되는 결속용 끈(6)에 의하여 결합되는 주꾸미 포획용 어구에 있어서,상기 상부몸체(2)와 하부몸체(3)의 외측 표면에는 5 ~ 10mm의 높이로 소뿔 형태의 타원형으로 형성된 돌출부(7)가 일정한 간격을 두고 30개 내지 50개가 골고루 분포 형성되고,상기 상,하부몸체(2)(3)와, 결속용 고리부(5a)(5b)와, 다수개의 돌출부(7)는, 25 ~ 35중량%의 ABS수지 또는 HIPS수지와 65 ~ 75중량%의 칼페트가 혼합되는 물보다 비중이 큰 합성수지재질로 이루어진 것을 특징으로 하는 뻘 바닥 또는 모래 바닥에 묻혀 움직이지 않도록 하는 패각용 주꾸미 포획어구., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

237/1150 Row 237: application_number: 1020200109318, combined_string: invention_title: 어선용 그물 자동정리장치 및 이를 포함하는 그물 자동정리시스템 abstract: 본 발명은 어선용 그물 자동정리장치 및 이를 포함하는 그물 자동정리시스템에 관한 것으로서, 보다 상세하게는 어선용 그물 자동정리장치를 통해 어선에서 사용된 그물을 사용이 가능한 상태로 정리하기 위한 것이다.또한, 본 발명은 그물이 안내되는 안내활의 중앙부에 취합통과부를 형성하여 그물의 그물망이 해당 취합통과부로 취합되도록 구성함으로써, 안내활로 안내되는 그물이 한 쪽으로 쏠리지 않고, 중앙부로 뭉쳐 지나가게 할 수 있는 어선용 그물 자동정리장치 및 이를 포함하는 그물 자동정리시스템을 제공하는데 목적이 있다.특히, 본 발명은 그물 정리 작업 중 그물이 한 쪽으로 쏠려 발생하는 부하를 감지하여 측정값에 따라 그물을 끌어당기는 롤러의 동작을 제어함으로써, 그물의 정리 작업 중 발생하는 부하를 방지할 수 있는 장점이 있다. claims: 유입된 그물을 펼쳐서 배출하는 어선용 그물 자동정리장치에 있어서,좌우측에 마련되는 양측프레임;상기 그물과 상기 그물의 양측 가장자리에 구성된 그물와이어의 유입을 가이드하며 상기 그물와이어 사이의 그물망을 펼치는 안내활;상기 안내활로 유입된 그물을 회전력에 의하여 끌어당기는 롤러;상기 롤러에 유입된 그물을 상기 롤러 방향으로 압박하는 압박휠; 및상기 그물와이어가 상기 양측프레임측으로 이동하는 것을 제한하는 그물이탈방지구;를 포함하고,상기 안내활은,상기 양측프레임에 설치되는 고정바; 및상기 고정바의 일측 및 타측에 각각 이격되어 한 쌍으로 구성되는 가이드구;및상기 한 쌍으로 구성된 가이드구의 사이에 형성되는 취합통과부;를 포함하고,상기 각각의 가이드구는,상기 고정바에서 상부방향으로 경사지게 구성되고, 하부보다 상부가 넓게 형성되며,상기 가이드구의 하부에는,상기 그물와이어가 통과되는 로프통과부;가 형성된 것을 특징으로 하는 어선용 그물 자동정리장치.제 1항에 따른 어선용 그물 자동정리장치를 포함하는 어선용 그물정리시스템에 있어서,어선에 고정 설치되는 거치장치;를 포함하며,상기 어선용 그물 자동정리장치는 상기 거치장치에서 평면상 이동 및 회동 중 적어도 하나의 동작이 가능하도록 구성되는 것을 특징으로 하는 그물 자동정리시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

238/1150 Row 238: application_number: 1020200080289, combined_string: invention_title: 수산자원 생산성 향상을 위한 인공어초 및 그의 제조방법 abstract: 본 발명은 인공어초 및 그의 제조방법에 관한 것으로 세굴에 의한 매몰 및 침하 문제 발생을 최소화하여 초기 설치 및 유지관리가 용이하고, 해조류의 초기 정착이 용이하며, 해수와 다양한 어류가 자유롭게 출입할 수 있는 서식공간을 풍부하게 제공할 수 있도록 한 것이다.이러한 본 발명은 인공어초의 경우 상부에서 하부로 갈수록 점진적으로 외경이 증가하는 원뿔대 형상으로 이루어지되 내부공간을 갖고 하면이 개구된 중공의 원뿔대 형상으로 이루어지며, 외주면 다수의 지점과 상면 중앙에는 해수와 어류가 내부공간으로 출입할 수 있도록 측면 출입공과 상면 출입공이 형성되며, 외주면에는 둘레방향을 따라 해조류의 활착을 유도하는 제1해조류 활착유도홈이 오목한 라인 형태로 복수 형성된 어초 본체; 및 상기 어초 본체의 하측에 설치되어 상기 어초 본체가 설치되는 인근 해저면을 덮으면서 해수의 흐름으로 인한 세굴을 방지해주는 세굴방지 매트;를 포함하는 것을 특징으로 한다. claims: 상부에서 하부로 갈수록 점진적으로 외경이 증가하는 원뿔대 형상으로 이루어지되 내부공간을 갖고 하면이 개구된 중공의 원뿔대 형상으로 이루어지며, 외주면 다수의 지점과 상면 중앙에는 해수와 어류가 내부공간으로 출입할 수 있도록 측면 출입공과 상면 출입공이 형성되며, 외주면에는 둘레방향을 따라 해조류의 활착을 유도하는 제1해조류 활착유도홈이 오목한 라인 형태로 복수 형성된 어초 본체; 및 상기 어초 본체의 하측에 설치되어 상기 어초 본체가 설치되는 인근 해저면을 덮으면서 해수의 흐름으로 인한 세굴을 방지해주는 세굴방지 매트;를 포함하며, 상기 어초 본체의 하단에는 상기 측면 출입공에 비해 넓은 수평 폭을 갖는 하단 출입구가 형성되어 어류와 함께 해저면을 기어다니는 저서성 패류까지 내부공간으로 동시에 출입 가능하도록 하며, 상기 제1해조류 활착유도홈의 내부에는 해조류의 영양성분이 되는 하이드로 아파타이트가 내장된 다공성 콘크리트가 형성되며, 상기 어초 본체는 상기 하단 출입구를 구비한 하부 본체에 대하여 상기 측면 출입공을 구비한 중간 본체와, 상기 상면 출입공을 구비한 상부 본체가 순차적으로 적층된 형태로 이루어지며, 상기 하부 본체와 중간 본체 사이와, 상기 중간 본체와 상부 본체의 사이에 하이드로 아파타이트를 내장한 다공성 콘크리트가 일정 두께를 갖고 개재되고, 그 외측으로 상기 제1해조류 활착유도홈이 형성된 것을 특징으로 하는 인공어초.인공어초의 제조방법으로서, 상기 인공어초는, 상부에서 하부로 갈수록 점진적으로 외경이 증가하는 원뿔대 형상으로 이루어지되 내부공간을 갖고 하면이 개구된 중공의 원뿔대 형상으로 이루어지며, 외주면 다수의 지점과 상면 중앙에는 해수와 어류가 내부공간으로 출입할 수 있도록 측면 출입공과 상면 출입공이 형성되며, 외주면에는 둘레방향을 따라 해조류의 활착을 유도하는 제1해조류 활착유도홈이 오목한 라인 형태로 복수 형성된 어초 본체; 및 상기 어초 본체의 하측에 설치되어 상기 어초 본체가 설치되는 인근 해저면을 덮으면서 해수의 흐름으로 인한 세굴을 방지할 수 있도록 격자구조를 갖는 지오그리드 보강재와, 상기 지오그리드 보강재의 상면에 접합된 콘크리트 보강재로 이루어진 세굴방지 매트;를 포함하며, 상기 세굴방지 매트의 콘크리트 보강재는, 모르타르를 제조하여 교반하는 단계; 상기 모르타르를 성형기에 투입하여 다수의 안착홀이 형성된 평판 형상의 콘크리트 보강재를 성형하는 단계; 상기 성형기에서 성형된 콘크리트 보강재를 성형기에서 탈형하는 단계; 상기 성형기에서 탈형된 콘크리트 보강재를 양생하는 단계; 및 양생된 콘크리트 보강재에 광촉매를 도포하는 단계;에 의해 제조하며, 상기 콘크리트 보강재의 강도보강을 위하여 3 내지 6cm의 길이를 갖고 양단부가 고리 형태로 구부러진 단섬유 PE 합사를 모르타르에 균일하게 분산된 형태로 첨가하는 것을 특징으로 하는 인공어초 제조방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

239/1150 Row 239: application_number: 1020200079342, combined_string: invention_title: 낙지의 탈출을 방지하는 통발용 진입구 및 그것이 적용된 통발 abstract: 본 발명은 낙지의 탈출을 방지하는 통발용 진입구 및 그것이 적용된 통발에 관한 것으로, 특히 통발의 내부로 포획된 낙지의 외부 탈출을 방지하고, 낙지의 진입을 원활하게 하여 포획량을 향상함은 물론 어업인의 소득을 대폭 증대하는 신개념의 기술에 관한 것이다.종래에 개시된 통발용 진입구는 망체를 구성하는 망살의 단면이 사각형으로 이루어짐으로써 입구에서 출구 쪽으로 유속이 작용할 때 저항을 많이 받으면서 출구가 벌어져 통발의 내부로 포획된 낙지가 외부로 탈출하여 포획량이 줄어드는 문제점이 야기된다.본 발명은 이러한 문제점을 일소하기 위한 방안으로 반분할 된 한 쌍의 상부 진입구 및 하부 진입구의 조립구성으로 이루어진 통발용 진입구의 망체를 구성하는 망살을 원형 단면으로 형성하여 유속에 따른 저항을 줄여 출구의 벌어짐을 방지할 수 있도록 하는 기술을 강구함을 특징으로 한다. claims: 하부가 개방된 망체(11)로 형성되고, 입구(13)에서 출구(14) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(12)가 형성되며, 상기 입구(13)의 양단에 지지살 파지부(15)가 형성됨과 아울러 상단에 링 밀착부(16)가 형성된 상부 진입구(10)와;상기 상부 진입구(10)과 일체로 맞대어 결합되되, 상부가 개방된 망체(21)로 형성되고, 입구(23)에서 출구(24) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(22)가 형성되며, 상기 입구(23)의 양단에 지지살 파지부(25)가 형성됨과 아울러 하단에 링 밀착부(26)가 형성된 하부 진입구(20)로 이루어지는 한편;상기 하부 진입구(20)의 양측 상단에 형성된 맞댐부(28)에 간격을 두고 다수의 결합돌기(28a)가 돌출 형성되고, 상기 상부 진입구(10)의 양측 하단에 형성된 맞댐부(18)에는 상기 결합돌기(28a)가 끼움 결합되는 다수의 결합홀(18a)이 형성된 것을 특징으로 하는 낙지의 탈출을 방지하는 통발용 진입구.하부가 개방된 망체(11)로 형성되고, 입구(13)에서 출구(14) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(12)가 형성되며, 상기 입구(13)의 양단에 지지살 파지부(15)가 형성됨과 아울러 상단에 링 밀착부(16)가 형성된 상부 진입구(10)와;상기 상부 진입구(10)과 일체로 맞대어 결합되되, 상부가 개방된 망체(21)로 형성되고, 입구(23)에서 출구(24) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(22)가 형성되며, 상기 입구(23)의 양단에 지지살 파지부(25)가 형성됨과 아울러 하단에 링 밀착부(26)가 형성된 하부 진입구(20)로 이루어지는 한편;상기 하부 진입구(20)의 양측 상단에 형성된 맞댐부(28)에 한 쌍의 결합돌기(28a)가 돌출 형성되고, 상기 상부 진입구(10)의 양측 하단에 형성된 맞댐부(18)에는 상기 결합돌기(28a)가 끼움 결합되는 다수의 결합홀(18a)이 형성되며, 상기 결합돌기(28a)의 사이 맞댐부(18)(28)는 상호 미싱으로 박음질 결합되는 것을 특징으로 하는 낙지의 탈출을 방지하는 통발용 진입구.하부가 개방된 망체(11)로 형성되고, 입구(13)에서 출구(14) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(12)가 형성되며, 상기 입구(13)의 양단에 지지살 파지부(15)가 형성됨과 아울러 상단에 링 밀착부(16)가 형성된 상부 진입구(10)와;상기 상부 진입구(10)과 일체로 맞대어 결합되되, 상부가 개방된 망체(21)로 형성되고, 입구(23)에서 출구(24) 쪽으로 진행할수록 점진적으로 면적이 좁아지도록 유인통로(22)가 형성되며, 상기 입구(23)의 양단에 지지살 파지부(25)가 형성됨과 아울러 하단에 링 밀착부(26)가 형성된 하부 진입구(20)의 조립구성으로 이루어진 통발용 진입구(E)를 구비하는 한편;상기 하부 진입구(20)의 양측 상단에 형성된 맞댐부(28)에 간격을 두고 다수의 결합돌기(28a)가 돌출 형성되고, 상기 상부 진입구(10)의 양측 하단에 형성된 맞댐부(18)에는 상기 결합돌기(28a)가 끼움 결합되는 다수의 결합홀(18a)이 형성되며;상부링(1) 및 하부링(2)의 사이에 다수의 지지살(3)이 연결되어 형성된 원통형 지지골조(4)의 외측면에 상기 통발용 진입구(E)가 설치되는 부위를 제외한 전체 부위를 그물망(5)이 둘러싸고;상기 통발용 진입구(E)는 지지살 파지부(15)(25)가 한 쌍의 지지살(3)을 파지함과 아울러 링 밀착부(16)(26)가 상, 하부링(1)(2)에 각각 밀착된 상태에서 그물망 보호구(30)를 이용하여 상기 링 밀착부(16)(26) 및 상, 하부링(1)(2)을 함께 감싸는 원터치 조작으로 상기 통발용 진입구(E)를 편리하게 설치하는 것을 특징으로 하는 낙지의 탈출을 방지하는 통발용 진입구가 적용된 통발., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

240/1150 Row 240: application_number: 1020200074042, combined_string: invention_title: 모터 내입형 다기능 양망기. abstract: 본 발명은 원통형의 모터 하우징에 모터가 장착되고, 외경에 회동드럼이 형성되어 있어 설치시 공간적인 제약이 거의 없으며, 취부용 브라켓을 이용하여 선체에 고정할 수 있음에 따라 선체에 별도로 조립공(고정홀)을 별도로 형성하지 않아도 됨에 따라 선박의 내구성 저하를 최소화할 수 있으며, 양망기에 함께 그물 가이드가 구비되어 별도로 안내 가이드를 구매할 필요가 없으며, 양망기 컨트롤 박스를 선내 또는 유선 리코컨으로 조작이 가능함에 따라 최소 인원으로 양승작업을 할 수 있으며, 양망기인 경우 일반적으로 사용되는 차량용 배터리를 사용함에 따라 충전 및 방전이 효율적이고 굳이 선박의 엔진을 가동할 필요가 없어 연료비를 절감할 수 있으며, 그물을 수리시에 기존은 인력을 이용하여 외부에 펼친후 수리하였으나, 양망기를 이용하여 손쉽게 외부에서 그물수리 작업을 할 수 있어 과도한 인력낭비를 최소화하여 경제적으로 사용할 수 있다. claims: 선박 내측에 고정할 수 있도록 사각형상의 취부용 브라켓이 형성되고, 취부용 브라켓 중앙에는 원통형의 모터 하우징이 구비되며, 모터 하우징 내경에는 다수개의 모터 고정 지지대가 형성되며, 모터를 작동할 수 있도록 선박 내부에 컨트롤 박스가 형성되며, 상기 모터 고정 지지대에는 모터가 구비되며, 모터의 샤프트에는 내입홈부가 형성되며, 샤프트가 관통될 수 있도록 중앙에 제 1 관통공이 형성된 샤프트 고정 하우징이 구비되며, 상기 샤프트는 회동드럼을 관통한 후 전면 브라켓의 중앙에 형성된 브라켓 통공에 거치된 후 브라켓 통공 상부에 형성된 걸림부에 샤프트의 내입홈부가 거치되는 모터 내입형 다기능 양망기에 있어서, 상기 회동드럼은 중앙에 제 2 관통공이 형성된 배면 브라켓이 형성되며, 배면 브라켓 전면에는 중앙에 제 3 관통공이 구비된 제 1 타원부가 구비 되며, 제 1 타원부의 전면에는 중앙에 제 4 관통공이 형성된 원통형의 연결 부재가 형성되며, 상기 연결부재의 외경에는 등 간격으로 다수개의 완충부재가 구비되며, 내경에는 다수개의 베어링 부재가 형성되며, 베어링 부재는 베어링 지지대 전면과 배면에 각각 제 1 돌출부와 제 2 돌출부가 구비되며, 상기 제 1 돌출부에는 제 1 와셔와 롤러 및 제 2 와셔가 순차적으로 결합되며, 제 2 돌출부는 제 2 타원부의 조립공에 결합되며, 제 2 타원부는 연결 부재의 전면에 용접결합되며, 제 2 타원부의 중앙에는 타원부 통공이 형성되며, 타원부 통공에 면접될 수 있도록 중앙에 브라켓 통공이 구비된 전면 브라켓이 형성되며, 상기 브라켓 통공 상부는 걸림부가 구비되며, 상기 전면 브라켓 전면에는 전면 커버가 형성됨을 특징으로 하는 모터 내입형 다기능 양망기., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

241/1150 Row 241: application_number: 1020200066766, combined_string: invention_title: 수중지반 신속자중매립용 팽이형 콘크리트 파일블럭 일체형 인공어초 및 그 시공방법 abstract: 본 발명은, 수중지반 신속자중매립용 팽이형 콘크리트 파일블럭 일체형 인공어초 및 그 시공방법에 관한 것으로, 원형평면 형상으로 일정 두께를 가지는 상면부와, 상기 상면부 하부로 일체로 형성되는 상광하협 원뿔형상의 몸체부와, 상기 몸체부 하부로 일체로 형성되는 상광하협의 기둥형상의 파일부와, 상기 상면부, 몸체부 및 파일부 내부 중앙에는 일정 구경을 가지고 수직관통되어 외부로 개구되는 통수공과, 상기 상면부의 외주부에는 상면부 두께를 상하로 관통하여 형성되고 볼트가 관통되는 복수개의 볼트체결공과, 상기 상면부의 외주부 상면에 수평 크레인 이송 및 안착을 위하여 복수개 형성되는 파일블럭 크레인걸이부를 포함하여 구성되는 팽이형 콘크리트 파일블럭과; 일정 두께를 가지는 상부원형벽 및 상기 상부원형벽에 연결되는 측부수직벽으로 이루어지며, 내부 중공부가 형성되고 하부가 개구된 상협하광 형상의 전도된 원통용기모양을 가지되, 상기 측부수직벽 둘레의 외경은 상기 팽이형 콘크리트 파일블럭의 상면부 외경과 일치되도록 형성되는 인공어초 하우징과, 상기 하우징 측부수직벽 둘레를 따라 상기 측부수직벽을 관통하여 복수개로 형성되는 원형 또는 사각형상의 어군출입구와, 상기 측부수직벽 하부면에는 상기 상면부의 하부로부터 상기 볼트체결공을 관통한 볼트가 삽입 너트체결되어 상기 팽이형 콘크리트 파일블럭과 상기 인공어초 하우징이 일체로 결합되도록 상기 복수개의 볼트체결공에 대응되는 위치에 형성되는 복수개의 너트매립체결공과, 상기 상부원형벽 중앙에는 일정 구경을 가지고 수직관통되어 상기 통수공에 결합되는 통수파이프가 삽입관통되도록 형성되는 통수파이프 관통공과, 상기 상부원형벽 외주부 상면에 수평 크레인 이송 및 안착을 위하여 복수개 형성되는 인공어초크레인걸이부를 포함하여 구성되는 인공어초블럭;이 일체로 결합되어 상기 통수파이프 및 통수공을 통해 고압수를 공급하여 상기 파일부 하부의 수중 연약지반의 토사를 토출하여 상기 팽이형 콘크리트 파일블럭이 수중지반에 신속히 자중에 의하여 견고히 매립고정될 수 있는 수중지반 신속자중매립용 팽이형 콘크리트 파일블럭 일체형 인공어초 및 그 시공방법에 관한 것이다. claims: 원형평면 형상으로 일정 두께를 가지는 상면부와, 상기 상면부 하부로 일체로 형성되는 상광하협 원뿔형상의 몸체부와, 상기 몸체부 하부로 일체로 형성되는 상광하협의 기둥형상의 파일부와, 상기 상면부, 몸체부 및 파일부 내부 중앙에는 일정 구경을 가지고 수직관통되어 외부로 개구되는 통수공과, 상기 상면부의 외주부에는 상면부 두께를 상하로 관통하여 형성되고 볼트가 관통되는 복수개의 볼트체결공과, 상기 상면부의 외주부 상면에 수평 크레인 이송 및 안착을 위하여 복수개 형성되는 파일블럭 크레인걸이부를 포함하여 구성되는 팽이형 콘크리트 파일블럭과; 일정 두께를 가지는 상부원형벽 및 상기 상부원형벽에 연결되는 측부수직벽으로 이루어지며, 내부 중공부가 형성되고 하부가 개구된 상협하광 형상의 전도된 원통용기모양을 가지되, 상기 측부수직벽 둘레의 외경은 상기 팽이형 콘크리트 파일블럭의 상면부 외경과 일치되도록 형성되는 인공어초 하우징과, 상기 하우징 측부수직벽 둘레를 따라 상기 측부수직벽을 관통하여 복수개로 형성되는 원형 또는 사각형상의 어군출입구와, 상기 측부수직벽 하부면에는 상기 상면부의 하부로부터 상기 볼트체결공을 관통한 볼트가 삽입 너트체결되어 상기 팽이형 콘크리트 파일블럭과 상기 인공어초 하우징이 일체로 결합되도록 상기 복수개의 볼트체결공에 대응되는 위치에 형성되는 복수개의 너트매립체결공과, 상기 상부원형벽 중앙에는 일정 구경을 가지고 수직관통되어 상기 통수공에 결합되는 통수파이프가 삽입관통되도록 형성되는 통수파이프 관통공과, 상기 상부원형벽 외주부 상면에 수평 크레인 이송 및 안착을 위하여 복수개 형성되는 인공어초크레인걸이부를 포함하여 구성되는 인공어초블럭;이 일체로 결합되어 상기 통수파이프 및 통수공을 통해 고압수를 공급하여 상기 파일부 하부의 수중 연약지반의 토사를 토출하여 상기 팽이형 콘크리트 파일블럭이 수중지반에 신속히 자중에 의하여 견고히 매립고정될 수 있는 것을 특징으로 하는 수중지반 신속자중매립용 팽이형 콘크리트 파일블럭 일체형 인공어초원형평면 형상으로 일정 두께를 가지는 상면부와, 상기 상면부 하부로 일체로 형성되는 상광하협 원뿔형상의 몸체부와, 상기 몸체부 하부로 일체로 형성되는 상광하협의 기둥형상의 파일부와, 상기 상면부, 몸체부 및 파일부 내부 중앙에는 일정 구경을 가지고 수직관통되어 외부로 개구되는 통수공과, 상기 상면부의 외주부에는 상면부 두께를 상하로 관통하여 형성되고 볼트가 관통되는 복수개의 볼트체결공과, 상기 상면부의 외주부 상면에 수평 크레인 이송 및 안착을 위하여 복수개 형성되는 파일블럭 크레인걸이부를 포함하여 구성되는 팽이형 콘크리트 파일블럭을 준비하는 단계와; 일정 두께를 가지는 상부원형벽 및 상기 상부원형벽에 연결되는 측부수직벽으로 이루어지며, 내부 중공부가 형성되고 하부가 개구된 상협하광 형상의 전도된 원통용기모양을 가지되, 상기 측부수직벽 둘레의 외경은 상기 팽이형 콘크리트 파일블럭의 상면부 외경과 일치되도록 형성되는 인공어초 하우징과, 상기 하우징 측부수직벽 둘레를 따라 상기 측부수직벽을 관통하여 복수개로 형성되는 원형 또는 사각형상의 어군출입구와, 상기 측부수직벽 하부면에는 상기 상면부의 하부로부터 상기 볼트체결공을 관통한 볼트가 삽입 너트체결되어 상기 팽이형 콘크리트 파일블럭과 상기 인공어초 하우징이 일체로 결합되도록 상기 복수개의 볼트체결공에 대응되는 위치에 형성되는 복수개의 너트매립체결공과, 상기 상부원형벽 중앙에는 일정 구경을 가지고 수직관통되어 상기 통수공에 결합되는 통수파이프가 삽입관통되도록 형성되는 통수파이프 관통공과, 상기 상부원형벽 외주부 상면에 수평 크레인 이송 및 안착을 위하여 복수개 형성되는 인공어초크레인걸이부를 포함하여 구성되는 인공어초블럭을 준비하는 단계와; 상기 팽이형 콘크리트 파일블럭의 상면부의 하부로부터 상기 볼트체결공을 관통한 볼트가 상기 인공어초 하우징의 너트매립체결공에 삽입 너트체결되어 상기 팽이형 콘크리트 파일블럭과 상기 인공어초 하우징을 일체화 결합시키는 단계와; 상기 인공어초 하우징의 통수파이프 관통공을 통하여 통수파이프를 삽입 관통하고 상기 통수파이프를 상기 팽이형 콘크리트 파일블럭 통수공에 결합시키는 단계와; 상기 인공어초 하우징의 인공어초크레인걸이부 및 크레인에 의하여 수평 크레인 이송 후, 매립될 수중지반에 안착시키고, 상기 통수파이프 및 통수공을 통해 고압수를 공급하여 상기 파일부 하부의 수중 연약지반의 토사를 토출하여 상기 팽이형 콘크리트 파일블럭이 수중지반에 신속히 자중에 의하여 견고히 매립 고정되도록 하는 단계와; 상기 매립 고정된 상기 인공어초 하우징 내부의 상기 통수파이프를 수중작업에 의하여 상기 통수공으로부터 결합 해제하고 상기 통수파이프 관통공을 통하여 제거하는 단계;를 포함하는 것을 특징으로 하는 수중지반 신속자중매립용 팽이형 콘크리트 파일블럭 일체형 인공어초의 시공방법, Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

242/1150 Row 242: application_number: 1020200036288, combined_string: invention_title: 암반해역 수산자원 포획용 저층트롤어구 abstract: 해양에서 이동하고 사이드 또는 선미에서 그물의 수거가 가능한 선체; 상기 선체와 연결되는 하나 이상의 끌줄; 상기 끌줄과 연결되는 전개판과; 상기 전개판과 앞 끝에 연결한 후 타 끝에는 자루형상의 그물 좌우 앞 끝에 연결되는 후릿줄과; 상기 후릿줄과 연결되어 해저의 골재를 채취되며 몸통그물과 끝자루를 포함하는 그물감으로 이루어지는 암반용 저층트롤어구를 제공함으로써, 골재채취해역의 급격한 암반지형에 타이어부가 바퀴처럼 굴러서 지나가게 트롤어구가 예인됨으로 트롤어구의 손상을 최소화할 수 있으므로 기존의 다양한 암반지형에서 발생하는 어구가 파손되는 것을 줄일 수 있다. claims: 해양에서 추진력으로 이동되며 사이드 또는 선미에서 양망 가능한 선체 및 선체와 한 쌍의 전개판을 연결하는 끌줄 및 한 쌍의 전개판과 자루형상의 그물을 연결하는 후릿줄 및 상기 후릿줄과 연결되어 몸통그물과 끝자루를 포함하는 그물 어구로 이루어지는 저층트롤 어구에 있어서, 상기 그물어구는 날개그물과 몸통그물 끝자루로 구분되고, 날개그물은 밑날개와 윗날개로 구분되어 결합되며, 상기 몸통그물은 날개 삼각망, 자루 삼각망, 천정망, 자루등판, 자루옆판, 자루밑판, 밑판 삼각망으로 이루어지고,상기 날개그물의 밑날개와 몸통그물의 자루밑판과 밑판 삼각망은 PEUC 네트(Polyethylene Ultra Cross Netting)로 이루어지며,상기 밑날개와 자루밑판에는 발줄이 연결되고 발줄에는 복수개의 타이어 결합으로 이루어지는 타이어부가 연결되어 급격한 암반지형에서 타이어부가 바퀴처럼 굴러서 지나가도록 그물어구가 예인됨으로 암반해역에서 그물어구의 손상을 방지할 수 있도록 한 것을 특징으로 하는 암반해역 수산자원 포획용 저층트롤 어구, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

243/1150 Row 243: application_number: 1020200027689, combined_string: invention_title: 동·식물 인공어초 abstract: 동·식물 인공어초가 개시된다. 상기 동·식물 인공어초는 다각형 블록 형태의 동식물 인공어초로서, 다각형 블록의 중심부에 형성되는 제1 해양동물서식공간; 상기 제1 해양동물서식공간의 둘레 주변에 고리형상으로 형성되고, 다각형 블록의 상면으로부터 소정 깊이를 갖도록 형성되는 제2 해양동물서식공간; 다각형 블록의 서로 이웃하는 측면을 사선으로 관통하여 형성되는 복수의 제3 해양동물서식공간; 및 상기 제1 해양동물서식공간의 둘레에 배치되도록 다각형 블록의 내부에 구비되고, 다각형 블록의 측면 및 상기 제1 해양동물서식공간의 내면에 소통되고, 다각형 블록의 측면에 소통하는 방향이 입출구를 형성하며, 단지 형상을 갖는 복수의 제4 해양동물서식공간을 포함하고, 상기 제1 해양동물서식공간 에는 사석이 채워지며, 상기 제1 내지 제4 해양동물서식공간(110, 120, 130, 140)을 통해 다양한 어종, 문어류, 해조류, 해삼, 전복 및 갑각류의 서식이 가능하다. claims: 다각형 블록 형태의 동·식물 인공어초로서,다각형 블록의 중심부에 형성되는 제1 해양동물서식공간(110);상기 제1 해양동물서식공간(110)의 둘레 주변에 고리형상으로 형성되고, 다각형 블록의 상면으로부터 소정 깊이를 갖도록 형성되는 제2 해양동물서식공간(120);다각형 블록의 서로 이웃하는 측면을 사선으로 관통하여 형성되는 복수의 제3 해양동물서식공간(130); 및상기 제1 해양동물서식공간(110)의 둘레에 배치되도록 다각형 블록의 내부에 구비되고, 다각형 블록의 측면 및 상기 제1 해양동물서식공간(110)의 내면에 소통되고, 다각형 블록의 측면에 소통하는 방향이 입출구를 형성하며, 단지 형상을 갖는 복수의 제4 해양동물서식공간(140)을 포함하고,상기 제1 해양동물서식공간(110) 에는 사석(150)이 채워지며,상기 제1 내지 제4 해양동물서식공간(110, 120, 130, 140)을 통해 다양한 어종, 문어류, 해조류, 해삼, 전복 및 갑각류의 서식이 가능하도록 구비되고;상기 제1 해양동물서식공간(110)의 내면에 밀착할 수 있는 고리 형상을 가지며, 상기 제1 해양동물서식공간(110)의 높이에 대응하는 높이를 갖고, 내면에 상기 고리 형상을 따라 형성되고 상기 고리 형상의 높이 방향으로 다수 배열되며 상기 고리 형상의 내측 방향으로 소정 형상으로 돌출되는 복수의 볼륨부(211)를 포함하는, 제1 사석구속부재(210);상기 각각의 볼륨부(211) 내에 채워져서 상기 각각의 볼륨부(211)의 볼륨을 유지시키는 볼륨유지탄성부재(220); 및상기 제1 해양동물서식공간(110)의 바닥면으로부터 수직하게 세워지는 지주부(231) 및 상기 지주부(231)의 전체 길이를 덮는 실리콘 재질의 지주커버부(232)를 포함하고, 상기 제1 해양동물서식공간(110) 내에 랜덤하게 배치되는 복수의 제2 사석구속부재(230)를 더 포함하며,상기 제1 내지 제4 해양동물서식공간(110, 120, 130, 140)을 통해 다양한 어종, 문어류, 해조류, 해삼, 전복 및 갑각류의 서식이 가능하도록 구비된 것을 특징으로 하는 동·식물 인공어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

244/1150 Row 244: application_number: 1020200007239, combined_string: invention_title: 선망 어업에 사용되는 그물 조립체 abstract: 이 발명은 선박에 의해 견인되어 어류를 포위하여 앙망함으로써 어류를 포획하는 선망 어업에서 사용하는 그물 조립체에 관한 것으로서, 해수면에 부유하여 그물 조립체에 부력을 제공하고, 복수 개가 그물 조립체의 길이 방향으로 서로 인접하게 배치되는 복수 개의 부력체; 해수면으로부터 침강하여 전개되어 어류를 포위 및 포획하는 그물; 그물 조립체의 길이 방향으로 연장되며, 그물 조립체를 견인하는 견인력을 받는 메인 로프; 부력체를 관통하여 연장되고 메인 로프에 결합되어 부력체를 메인 로프에 지지하여 주는 부력체 결합용 로프; 및 메인 로프를 따라 연장되고 그물이 결합되어 그물을 메인 로프에 지지하여 주는 그물 결합용 로프를 포함하고, 부력체 결합용 로프는 부력체를 관통하여 부력체와 결합되되, 하나의 부력체를 관통한 위치로부터 메인 로프를 관통하여 다시 인접한 부력체의 위치로 복귀함으로써 메인 로프에 대하여 부력체의 반대 위치에 고리를 형성하고, 그물 결합용 로프는 부력체 결합용 로프가 이루는 고리들을 관통하여 연장되는 것이다. claims: 선박에 의해 견인되어 어류를 포위하여 앙망함으로써 어류를 포획하는 선망 어업에서 사용하는 그물 조립체로서, 해수면에 부유하여 그물 조립체에 부력을 제공하고, 복수 개가 그물 조립체의 길이 방향으로 서로 인접하게 배치되는 복수 개의 부력체; 해수면으로부터 침강하여 전개되어 어류를 포위 및 포획하는 그물; 그물 조립체의 길이 방향으로 연장되며, 그물 조립체를 견인하는 견인력을 받는 메인 로프; 부력체를 관통하여 연장되고 메인 로프에 결합되어 부력체를 메인 로프에 지지하여 주는 부력체 결합용 로프; 및 메인 로프를 따라 연장되고 그물이 결합되어 그물을 메인 로프에 지지하여 주는 그물 결합용 로프를 포함하고,부력체 결합용 로프는 부력체를 관통하여 부력체와 결합되되, 하나의 부력체를 관통한 위치로부터 메인 로프를 관통하여 다시 인접한 부력체의 위치로 복귀함으로써 메인 로프에 대하여 부력체의 반대 위치에 고리를 형성하고, 그물 결합용 로프는 부력체 결합용 로프가 이루는 고리들을 관통하여 연장되며, 2개 이상의 부력체 결합용 로프가 마련되어 서로 평행하게 부력체를 관통하도록 배치되고, 메인 로프의 서로 다른 위치를 관통하여 상기 고리를 형성하고, 그물 결합용 로프는 부력체 결합용 로프가 형성하는 고리들을 함께 관통하는 것인, 그물 조립체., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

245/1150 Row 245: application_number: 1020200006666, combined_string: invention_title: 다단층 재순환여과 빌딩양식 시스템 abstract: 본 발명은 물의 수조내 순환방식을 적용하여 해수 환수비율을 줄이면서 활어의 생육에 유리한 환경을 조성함과 동시에 전체 에너지를 저감하고 활어 양식을 통합적으로 관리할 수 있도록 구성된 다단층 재순환여과 빌딩양식 시스템을 제공함을 제공하고자 한 것이다.이를 위해, 본 발명은 다층으로 이루어지되 각층마다 각각 물과 활어가 수용되는 복수 개의 수조모듈이 설치되며, 상기 수조모듈 각각에 물을 공급하는 물공급모듈과 상기 각 수조모듈로부터 배출되는 물을 공급받아 상기 물공급모듈로 재공급하는 수처리모듈을 포함하는 다단층 재순환여과 빌딩양식 시스템을 제공한다. claims: 다층으로 이루어지되 각층마다 각각 물과 활어가 수용되는 복수 개의 수조모듈이 설치되며,상기 수조모듈 각각에 물을 공급하는 물공급모듈과 상기 각 수조모듈로부터 배출되는 물을 공급받아 상기 물공급모듈로 재공급하는 수처리모듈을 포함하며,상기 수조모듈은 전체적으로 폐루프 형태로 이루어져 물이 순환하도록 구성되는 수조부와, 상기 수조부 내측에 설치되어 상기 수조부를 따라 유동하는 물의 유속을 조절하는 유속조절모듈을 포함하며,상기 유속조절모듈은 상기 수조부의 바닥부에 선택된 위치로 적용되는 배출홀과, 상기 배출홀을 통하여 배출되는 물이 유동하는 배출유동관과, 상기 배출유동관에 수직 상향으로 연결되며 상부가 개구된 수직관과, 상기 수직관의 상측에 연결되며 상기 수조부로 물을 재배출하는 절곡관과, 상기 수직관의 하측에 연결되어 외부로부터 공기를 공급받아 상기 배출유동관으로 배출된 물을 공기압을 이용하여 상기 수직관으로 공기와 함께 이동시키는 에어공급관과, 상기 수직관의 상부에 상기 수직관 외부를 둘러 감싸는 형태로 설치되는 버켓부를 포함하며,상기 배출홀 주변으로 상기 수조부 바닥부에는 상기 배출홀로부터 멀어지는 측으로 경사진 형태로 플렉시블한 재질로 이루어진 돌출리브부가 상기 배출홀 주변 둘레를 따라서 소정 이격된 간격마다 구비되는, 다단층 재순환여과 빌딩양식 시스템., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

246/1150 Row 246: application_number: 1020200000662, combined_string: invention_title: 어망의 독살 abstract: 조수가 심한 일정한 장소에 기둥관의 어망을 조수를 이용, 자동으로 어망을 상승 하강하여 고기를 잡고 해수욕장 등은 보호구역 내에 독해파리등의 침투를 방지하고 어촌의 바다에 떠다니는 오물, 쓰레기, 장마철의 해파리 떼를 수거 또는 제거하는 것이다. 타 어업에는 전혀 지장이 없는 것이다. claims: 본 발명은 조수차이가 심한 곳의 일정한 장소에 태풍에도 견딜 수 있게 도3과 같이 구성한 기둥관(1) 밖으로 링(8)에 어망줄(29),(31)을 결합, 지렛대(5) 하단의 어망줄구(21)에 결합하고 기둥관(1) 내부에는 부력공(2) 하단에 부력공줄(9)을 하단도르레(6)를 통과, 기둥관(1) 외부 상단도르레(7)를 통과하여 지렛대(5)의 중간 부력줄구(20)를 결합하면 지렛대(5)는 부력공줄구(9)의 당기는 힘으로 지탱이 되어 어망(8)은 해수면(25) 보다 높이 올라 나르는 고기 탈출을 방지하는 것이다. 이리하여 어망줄(31) 중간요소에 어망추(24)를 장착한 하중과 링(4)의 하중으로 퇴수구밸브(13)를 열면 배수와 동시에 어망(8)과 부력공(2)은 하강, 지면에 안착한다. 이리하여 반복으로 어망(8)은 상승, 하강하고 있는 것이다.해수욕장 같은 장소에서는 퇴수구(13)를 열어 놓으면 어망(8)은 물속에서 항상 펴져있는 어망의 독살1항에 있어서 어망(8) 상단에 지렛대(5)를 구성하여 나르는 고기의 탈출을 방지하는 어망의 독살, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

247/1150 Row 247: application_number: 1020190175271, combined_string: invention_title: 무척추동물 유생 사육장치 abstract: 본 발명은 유생 사육장치(1)에 관한 것이다. 그러한 유생 사육장치(1)는, 사육수가 저장되어 무척추 생물을 사육하는 사육조(3)와; 사육조(3)의 내부에 배치되어 무척추 생물의 성장에 맞추어 가변적으로 회전함으로써 사육하는 회전부(5)와; 회전부(5)를 구동시키는 구동부(7)와; 무척추 생물을 외측으로 분산시키는 과밀 방지틀(25)과; 사육조(3)의 물을 외부로 배출하는 배수관(27)과; 그리고 배수관(27)의 상측에 장착되어 배출되는 유수에 함유된 이물질을 제거하는 스크린(9)을 포함한다. claims: 사육수가 저장되어 무척추 생물을 사육하는 사육조(3)와;사육조(3)의 내부에 배치되어 무척추 생물의 성장에 맞추어 가변적으로 회전함으로써 사육하는 회전부(5)와; 회전부(5)를 구동시키는 구동부(7)와; 무척추 생물을 외측으로 분산시키는 과밀 방지틀(25)과; 사육조(3)의 물을 외부로 배출하는 배수관(27)과; 그리고배수관(27)의 상측에 장착되어 배출되는 유수에 함유된 이물질을 제거하는 스크린(9)을 포함하는 유생 사육장치(1)., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

248/1150 Row 248: application_number: 1020190170807, combined_string: invention_title: 적조 및 해양환경 오염방지를 위한 양식장 abstract: 본 발명은 적조 및 해양환경오염방지 양식장의 구조에 관한 것으로서, 더욱 상세하게는 적조 발생시 적조 미생물이 양식장 내부로 침입하는 것을 차단하여 어패류의 폐사를 막고, 해상 양식시 파생되는 사료찌꺼기와 배설물, 폐어구 등이 해저에 바로 침적되지 않고 본 발명의 수족관구조물의 수족관부 내부 바닥에 침적되게 하여 해양환경오염 및 생태계 파괴로 이어지지 않도록 예방하며, 해상원유사고 발생시 유발되는 어패류의 폐사를 막을 수 있도록 양식장구조물, 그물구조물, 수족관구조물이 유기적으로 결합 구성되며, 그물구조물과 수족관구조물이 상하작동이 가능하도록 구성된 적조 및 해양환경 오염방지 양식장 구조물에 관한 것이다. claims: 해상에서 양식작업이 가능하도록 일정한 통로의 형태로 형성된 작업로와 상기 작업로의 상부에 다수개의 수평프레임 및 수직프레임을 포함한 다수의 프레임의 결합으로 이루어지는 프레임구조물로 구성되는 양식장구조물; 어류를 수용할 수 있는 그물망과 상기 그물망의 상부에는 둘레를 따라 그물망을 지탱하도록 상부테두리가 형성되는 그물구조물; 다수개의 수평프레임 및 수직프레임을 포함하여 구성된 상부프레임과, 상기 상부프레임의 하부에 외부 해수의 출입을 차단하는 통형태의 수족관부로 이루어진 수족관구조물; 상기 수족관구조물을 들어 올릴 수 있도록 상기 프레임구조물의 일정위치에 설치된 제1승강수단; 및 상기 그물구조물을 들어 올릴수 있도록 상기 프레임구조물의 일정위치에 설치된 제2승강수단을 포함하여 구성되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장에서, 상기 그물구조물의 상부테두리에는 상기 제2승강수단과 결합하는 결합부가 형성되고, 상기 양식장구조물의 상단에 결합되어 아랫방향으로 형성된 가이드프레임이 관통할 수 있도록 가이드프레임 결합구멍이 형성되며, 상기 가이드프레임결합구멍에는 상기 가이드프레임이 원활하게 움직일수 있도록 지지롤러가 형성되고, 상기 그물구조물의 하단에는 상기 그물망을 개방할수 있는 개방수단이 구비되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장.해상에서 양식작업이 가능하도록 일정한 통로의 형태로 형성된 작업로와 상기 작업로의 상부에 다수개의 수평프레임 및 수직프레임을 포함한 다수의 프레임의 결합으로 이루어지는 프레임구조물로 구성되는 양식장구조물; 어류를 수용할 수 있는 그물망과 상기 그물망의 상부에는 둘레를 따라 그물망을 지탱하도록 상부테두리가 형성되는 그물구조물; 다수개의 수평프레임 및 수직프레임을 포함하여 구성된 상부프레임과, 상기 상부프레임의 하부에 외부 해수의 출입을 차단하는 통형태의 수족관부로 이루어진 수족관구조물; 상기 수족관구조물을 들어 올릴수 있도록 상기 프레임구조물의 일정위치에 설치된 제1승강수단; 및 상기 그물구조물을 들어 올릴수 있도록 상기 프레임구조물의 일정위치에 설치된 제2승강수단을 포함하여 구성되는 것을 특징으로 하는 적조 및 해양환경오염방지를 위한 양식장에서, 상기 수족관구조물은 상기 수족관부의 하부에 형성되어 내부가 빈 상태로 밀폐된 부기통부와, 상기 상부프레임의 상부에 형성되어 제1승강수단과 결합하는 상부고리를 더 포함하여 형성되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장.해상에서 양식작업이 가능하도록 일정한 통로의 형태로 형성된 작업로와 상기 작업로의 상부에 다수개의 수평프레임 및 수직프레임을 포함한 다수의 프레임의 결합으로 이루어지는 프레임구조물로 구성되는 양식장구조물; 어류를 수용할 수 있는 그물망과 상기 그물망의 상부에는 둘레를 따라 그물망을 지탱하도록 상부테두리가 형성되는 그물구조물; 다수개의 수평프레임 및 수직프레임을 포함하여 구성된 상부프레임과, 상기 상부프레임의 하부에 외부 해수의 출입을 차단하는 통형태의 수족관부로 이루어진 수족관구조물; 상기 수족관구조물을 들어 올릴 수 있도록 상기 프레임구조물의 일정위치에 설치된 제1승강수단; 및 상기 그물구조물을 들어 올릴수 있도록 상기 프레임구조물의 일정위치에 설치된 제2승강수단을 포함하여 구성되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장에서, 제1승강수단과 제2승강수단은 각각 도르래와 와이어를 포함하여 구성하되, 상기와이어의 일단에는 갈고리가 결합되어 각각 상기 수족관구조물과 그물구조물에 결합 및 해지될 수 있으며, 나머지 일단에는 하나 이상의 결합링이 결합되어 상기 프레임구조물의 일정위치에 형성된 고정수단에 걸어, 상기 수족관구조물과 상기 그물구조물을 일정위치에 고정할 수 있도록 구성되는 것을 특징으로 하는 적조 및 해양환경 오염방지를 위한 양식장., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

249/1150 Row 249: application_number: 1020190170131, combined_string: invention_title: 홈이 없는 방오어망 및 그 제조방법 abstract: 본 발명은 어망 소재 섬유의 내열성 여부와 관계없이 2종의 방오물질이 첨가된 열가소성수지를 용융 침적 후 냉각 또는 열경화성수지를 상온에서 침적 후, 열 경화하여 어망에 피복하되, 어망용 섬유의 열 손상 방지를 위해, 섬유의 물성 변화 온도 이하, 합성수지의 용융 또는 경화온도 범위에서 최단 시간 피복을 위해서, 연속적인 제망공정을 분리하여, 1차로, 스트랜드를 피복한 후, 2차로, 제망한 어망을 재피복해서 어망 로프의 홈을 메워 표면을 매끄럽게 하고, 윤활성, 항균성, 전기전도성을 가지며, 슈퍼 섬유에 피복하여 굵기가 가는 어망 및 동합금어망 보다 저중량, 저가로 제조하며, 피복된 합성수지는 상온건조형 방오도료 보다 내구성이 우수한 친환경 방오어망이 특징이다. claims: 홈이 없는 전기전도성 방오어망에 있어서,전기전도성이 있는 자기윤활성물질과 무기항균제가 첨가된 합성수지로 어망을 피복하되,상기 합성수지는 어망용 소재 섬유와 같이 유연성이 있는 합성수지로써 열가소성이면 용융상태의 수지에 침적하여 일체형 성형을 위해서 탈포, 급냉하여 피복하고, 열경화성이면 상온에서 액상 수지에 침적, 탈포, 가열 경화하여 피복하며, 열가소성수지의 용융열 또는 열경화성수지의 경화열에 의해 어망용 소재 섬유의 물성이 변화하는 온도 이하 및 열가소성수지의 용융온도 또는 열경화성수지의 경화온도 이상으로써 피복이 가능한 온도 범위, 즉 온도차(△t)에서 피복함으로써 어망용 소재 섬유에 대한 열 손상 없이 피복이 가능하고,상기 어망의 로프 외주면에 피복된 합성수지(360)가 로프에 형성된 섬유 올의 미세 홈(130)과 나선형 홈(330)을 메우고, 위사와 경사 로프(310, 320)의 교차부위에 형성된 홈(340)은 교차부위에 형성된 합성수지(350)가 메워 로프(100)의 전체 표면을 매끄럽게 하여 해양생물이 착상하는 홈을 제거하고, 자기윤활성물질에 의해 로프 표면을 미끄럽게 하는 물리적 방오 기능, 무기항균제에 의한 항균기능과 전기전도성을 가지는 것을 특징으로 하는 홈이 없는 전기전도성 방오어망., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

250/1150 Row 250: application_number: 1020190168559, combined_string: invention_title: 어류양식장의 순환여과를 위한 차세대 스마트 여과시스템 abstract: 본 발명에 따른 어류양식장의 순환여과용 차세대 스마트 여과시스템은 시스템 내부에 기능성 여과 챔버를 구비하여 오염원별로 이를 여과할 수 있도록 함으로서 여과 효율을 증대시키고 또한 설비의 유지보수 비용을 대폭 절감하기 위해 각 여과챔버의 운정 상황을 감시하고 제어하는 기능을 전자동으로 가능하게하며, 이를 인터넷 등 통신망과 연결하여 컴퓨터나 모바일 기기등을 활용하여 원격으로 감시 및 제어할 수 있도록 설게된 차세대 맞춤형 스마트 여과장치이다.일반적인 여과장치는 단순히 유량의 흐름만을 감시하며 이를 통해 설비유지 및 보수의 필요성을 작업자가 판단하도록 하여 불편함이 있었으나 이를 자동화하고 자동 전송시킴으로서 운영의 편리성을 증대시켜 원가절감을 극대화 할 수 있다.또한 이를통해 미세 오염물, 항생물질 등의 문제적 오염물질 등을 여과함으로서 어류양식장의 배출수에 의한 오염을 줄이고, 물의 재사용율을 높임으로서 첨단 순환여과 방식의 확산에 기여하여 환경적 측면과 양식어가의 수익성 증대 등 양측면에 기여할 수 있는 장점이 있다. claims: 오염물질을 선택적으로 여과해주는 필터 카트리지의 제조 및 조립방법과 필터 카트리지 내부의 필터간 빈 공간에 활성탄 비드를 채운 필터카트리지필터 카트리지가 내부에 카트리지 두께만큼의 간격으로 5개 ~20개 이내로 장착되어 오염수의 흐름을 원활하게 유지하며 여과 챔버의 처리량을 증대시킨 여과 챔버여과챔버의 양측면 상단과 하단에 입수부에 한개의 입수구가 장치되고, 배수부에 상,하로 두개의 배수구가 장치되고 이를 제어형밸브로 선택적으로 배수 경로를 결정할 수 있도록 설계 및 조립된 여과 챔버 각 여과 챔버별로 각각의 여과 기능을 달리하여 선택적으로 오염물질을 여과함으로서 필터카트리지의 교체 및 교환과 설비유지보수의 편리성을 증대시킴.정상운전시 배수부의 상단에 위치한 배수구를 통하여 배수되도록 설계되어 최소 7분 이상의 접촉 및 반응 시간동안 정체 시켜 여과 효율을 증대시킨 여과챔버금속프로파일 구조물에 여과챔버를 장치시킴에 있어서 입수부의 위치를 수평에서 각도로 1~3도 정도 높게 위치하여 여과 챔버내에 잔류 오염수가 남지 않도록 하는 점여과 시스템의 자동과 수동 조작을 위한 운전조작반에 있어서 통신기법을 이용한 원격감시제어 기능을 구비하여 인터넷 또는 모바일기기 등으로 감시 및 제어가 가능한 기능의 부가, Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

251/1150 Row 251: application_number: 1020190162682, combined_string: invention_title: 조립식 인공 어초 및 이의 시공 방법 abstract: 본 개시는, 수직방향으로 길이연장되고 방사상 외측으로 돌출된 3개 이상의 돌출부로 이루어진 코어부와, 상기 돌출부의 끝단에 배치된 결합 돌기를 구비하는 커넥터와; 서로 인접배치된 일 커넥터의 돌출부와 타 커넥터의 돌출부 사이에 개재될 수 있게 상기 결합 돌기가 삽입결합되는 결합홈을 양 단부에 구비하는 패널을 포함하고, 여기서, 상기 다수의 커넥터와 다수의 패널은, 해저 지형에 대응되게 같거나 다른 높낮이로 사방으로 확장되도록 조립연결될 수 있어 어류 서식처로 사용될 다수의 내부 공간을 형성하는 조립식 인공 어초에 관한 것이다. 또한, 본 개시는 조립식 인공 어초의 시공 방법에 관한 것이다. claims: 수직방향으로 길이연장되고 방사상 외측으로 돌출된 3개 이상의 돌출부(111)로 이루어진 코어부(110)와, 상기 돌출부(111)의 끝단에 배치되고 길이방향을 따라 내부에 제2 중공부(121)를 형성한 결합 돌기(120)를 구비하는 커넥터(100)와;서로 인접배치된 일 커넥터(100)의 돌출부(111)와 타 커넥터(100)의 돌출부(111) 사이에 개재될 수 있게 상기 결합 돌기(120)가 삽입결합되는 결합홈(220)을 양 단부에 구비하되,상기 결합 돌기(120)와 대면하는 상기 결합홈(220)의 내부면 둘레를 따라 상기 결합 돌기의 삽입방향으로 수직 배열된 다수의 볼록부(222)를 갖춘 패널(200);을 포함하고, 여기서, 상기 다수의 커넥터(100)와 다수의 패널(200)은, 해저 지형에 대응되게 같거나 다른 높낮이로 사방으로 확장되도록 조립연결될 수 있어 어류 서식처로 사용될 다수의 내부 공간(S)을 형성하는 조립식 인공 어초. 인공 어초를 설치할 해저 지형을 탐지하는 단계(S100);수직방향으로 길이연장되고 방사상 외측으로 돌출된 3개 이상의 돌출부(111)로 이루어진 코어부(110)와, 상기 돌출부(111)의 끝단에 배치되고 길이방향을 따라 내부에 제2 중공부(121)를 형성한 결합 돌기(120)를 구비하는 커넥터(100)를 탐지된 지형을 고려하여 준비하는 단계(S200); 서로 인접배치된 일 커넥터(100)의 돌출부(111)와 타 커넥터(100)의 돌출부(111) 사이에 개재될 수 있게 상기 결합 돌기(120)가 삽입결합되는 결합홈(220)을 양 단부에 구비하되, 상기 결합 돌기(120)와 대면하는 상기 결합홈(220)의 내부면 둘레를 따라 상기 결합 돌기의 삽입방향으로 수직 배열된 다수의 볼록부(222)를 갖춘 패널(200)을 탐지된 지형을 고려하여 준비하는 단계(S300); 상기 커넥터(100)와 상기 패널(200)을 탐지된 지형에 일치하도록 같거나 다르게 높낮이를 조절하면서 사방으로 확장되는 조립연결을 통해 다수의 내부 공간(S)을 제공하는 인공 어초(1)를 형성하는 단계(S400); 및 상기 인공 어초(1)를 미리 설정된 해저에 침설(沈設)하는 단계(S500);를 포함하는 조립식 인공 어초의 시공방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

252/1150 Row 252: application_number: 1020190156831, combined_string: invention_title: 다단형 경량화 구조를 갖는 고순환 여과방식 이미패류 관리시스템 abstract: 본 발명은 사육 수조의 수위를 극도로 낮추어 패류가 공기 중에 노출되지 않는 범위에서 수심을 결정할 수 있고, 기존 순환여과 시스템의 사육 수조보다 수량이 극도로 작기 때문에 동일동력에서 환수율을 증가시킬 수 있으며, 순환율을 높여 먹이생물 유실을 최소화시킬 수 있도록 한 다단형 경량화 구조를 갖는 고순환 여과방식 이미패류 관리시스템에 관한 것이다. claims: 사육수조, 물리여과조, 생물학적 여과조, 디지털순환펌프(사육수의 온도조절 및 해수공급 기능), 히트펌프(펌프와 연동해서 작동), 컨트롤 판넬을 포함하는 다단형 경량화 구조를 갖는 고순환 여과방식 이미패류 관리시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

253/1150 Row 253: application_number: 1020190151885, combined_string: invention_title: 유해 외래어종 산란장 abstract: 본 발명은 유해 외래어종 산란장에 관한 것으로 본 발명의 일면에 따른 유해 외래어종 산란장은 수중 바닥에 안착되는 산란틀, 산란틀의 상부에 탈착가능하게 설치되고 산란틀의 상부에 입구와 출구를 마련하는 가림막, 산란틀의 일측에 연결된 상태에서 하단이 수중 바닥에 고정되고 상단이 수면위로 노출되는 지지대, 지지대의 상단에 설치되는 태양전지, 지지대에 설치되고, 태양전지로부터 전원을 공급받아, 입구와 출구를 촬영하는 카메라를 포함한다. claims: 수중 바닥에 안착되는 산란틀;상기 산란틀의 상부에 탈착가능하게 설치되고 상기 산란틀의 상부에 입구와 출구를 마련하는 가림막;상기 산란틀의 일측에 연결된 상태에서 하단이 수중 바닥에 고정되고 상단이 수면위로 노출되는 지지대;상기 지지대의 상단에 설치되는 태양전지; 및상기 지지대에 설치되고, 상기 태양전지로부터 전원을 공급받아, 상기 입구와 출구를 촬영하는 카메라;를 포함하는 유해 외래어종 산란장., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

254/1150 Row 254: application_number: 1020190147376, combined_string: invention_title: 폭기설비를 활용한 사육조 유속 조절장치 abstract: 순환형 수산양식장의 순환시스템에서 순환되는 사육수의 운동성 및 목적 용존산소 용해도까지 올리고 효율성을 높이기 위해 발명하는 시스템으로서 폭기설비와 순환수 통합하는 장치와 이의 분사노즐의 위치와 각도 등을 조절하여 사육수의 운동성 및 용해도를 높이는 방식으로 발명의 목적을 구현한다. claims: 순환형 수산양식장의 순환시스템에서 순환되는 사육수의 운동성 및 목적 용존산소 용해도까지 올리고 효율성을 높이기 위해 발명하는 시스템으로서 폭기설비와 순환수 통합하는 장치와 이의 분사노즐의 위치와 각도 등을 조절하여 사육수의 운동성 및 용해도를 높이는 방식의 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

255/1150 Row 255: application_number: 1020190142790, combined_string: invention_title: 스마트 양식 수조용 히트펌프 시스템 abstract: 본 발명은, 양식을 위한 양식장 수조; 해수를 공급받아 상기 양식장 수조에 사용하는 해수를 공급하는 해수조; 상기 양식장 수조에서 사용한 오폐수가 배출되는 배수라인에 설치된 오폐수 열교환부; 상기 오폐수를 순환시키는 순환부; 상기 해수조로부터 해수를 공급받아 상기 오폐수 열교환부에 거쳐서 상기 해수보다 승온된 해수를 상기 양식장 수조로 공급하는 제 1 공급라인; 상기 해수조로부터 해수를 공급받아 상기 오폐수 열교환부에 거쳐서 상기 해수보다 승온된 해수를 저장하고, 보일러를 통해서 추가로 승온하는 것이 가능한 온수조; 상기 온수조로부터 해수를 공급받아 상기 양식장 수조로 공급하는 제 2 공급라인; 상기 해수조로부터 해수를 공급받아 상기 해수를 상기 양식장 수조로 공급하는 제 3 공급라인; 및 상기 온수부 앞의 위치에서 제 1 공급라인에서 상기 해수조로 해수를 회수시키는 회수부;를 포함하고, 상기 양식장 수조 및 상기 해수조의 온도 및 저수량를 각각 검출하는 제 1 센서부 및 제 2 센서부, 그리고 제 1 공급라인, 제 2 공급라인, 및 제 3 공급라인의 해수 온도를 검출하는 제 3 센서부, 제 4 센서부, 및 제 5 센서부; 및 상기 양식장 수조에서 필요로 하는 온도의 해수량을 최저의 에너지 소비로 공급하기 위하여 계산하는 제어부;를 더 구비하고, 상기 제어부의 제어에 따라서, 제 1 공급라인, 제 2 공급라인, 및 제 3 공급라인을 통한 해수의 공급량이 조절되는 것을 특징으로 하는, 양식 수조용 히트펌프 시스템을 개시한다. claims: 양식을 위한 양식장 수조; 해수를 공급받아 상기 양식장 수조에 사용하는 해수를 공급하는 해수조; 상기 양식장 수조에서 사용한 오폐수가 배출되는 배수라인에 설치된 오폐수 열교환부; 상기 오폐수를 순환시키는 순환부; 상기 해수조로부터 해수를 공급받아 상기 오폐수 열교환부에 거쳐서 상기 해수보다 승온된 해수를 상기 양식장 수조로 공급하는 제 1 공급라인; 상기 해수조로부터 해수를 공급받아 상기 오폐수 열교환부에 거쳐서 상기 해수보다 승온된 해수를 저장하고, 보일러를 통해서 추가로 승온하는 것이 가능한 온수조; 상기 온수조로부터 해수를 공급받아 상기 양식장 수조로 공급하는 제 2 공급라인; 상기 해수조로부터 해수를 공급받아 상기 해수를 상기 양식장 수조로 공급하는 제 3 공급라인; 및상기 온수부 앞의 위치에서 제 1 공급라인에서 상기 해수조로 해수를 회수시키는 회수부;를 포함하고, 상기 오폐수 열교환부는, 쉘과 상기 쉘 내에 위치한 다수의 튜브로 이루어진 히트 펌프를 포함하며, 상기 다수의 튜브를 일일이 한 개씩 청소하지 않고 복수 개의 노즐을 회전시키면서 세척하는 것이 가능하도록 랙앤 피니언 기어를 이용한 기구에 부착될 수 있는 구조를 채택한 것을 특징으로 하는, 양식 수조용 히트펌프 시스템., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

256/1150 Row 256: application_number: 1020190142292, combined_string: invention_title: 선박용 그물 로프 양망장치 abstract: 본 발명은 선박용 그물 로프 양망장치에 관한 것으로, 상부 로터 하우징과 하부 로터 하우징으로 구성되는 로터 하우징; 상기 상부 로터 하우징에 결합되는 감속기와, 상기 감속기의 하부에 결합되는 모터와, 상기 하부 로터 하우징에 내장되며, 상기 모터의 구동 및 속도 제어를 위한 유압을 공급하는 유압 공급부로 구성되며, 상기 상부 로터 하우징을 회전시키는 회전수단; 상기 상부 로터 하우징에 결합되며, 상기 상부 로터 하우징으로부터 소정의 회전력을 전달받는 회전축; 상기 회전축과 결합되고, 상기 회전력을 전달받아 회전 작동하면서 그물 로프의 권취가 이루어지는 권취롤러; 및 상기 회전수단의 회전 여부 및 회전 속도를 제어하는 제어장치;를 포함하는 것을 특징으로 한다. claims: 상부 로터 하우징과 하부 로터 하우징으로 구성되는 로터 하우징; 상기 상부 로터 하우징에 결합되는 감속기와, 상기 감속기의 하부에 결합되는 모터와, 상기 하부 로터 하우징에 내장되며, 상기 모터의 구동 및 속도 제어를 위한 유압을 공급하는 유압 공급부로 구성되며, 상기 상부 로터 하우징을 회전시키는 회전수단; 상기 상부 로터 하우징에 결합되며, 상기 상부 로터 하우징으로부터 소정의 회전력을 전달받는 회전축; 상기 회전축과 결합되고, 상기 회전력을 전달받아 회전 작동하면서 그물 로프의 권취가 이루어지는 권취롤러; 및 상기 회전수단의 회전 여부 및 회전 속도를 제어하는 제어장치;를 포함하고, 상기 상부 로터 하우징은, 상기 감속기가 결합되는 상부 연결 플랜지와, 상부 중앙에 돌출되게 형성되며, 상기 회전축의 하단부가 결합되는 체결홈과, 상기 회전축의 회전 작동을 지지하도록 베어링이 안착되는 안착홈으로 구성되는 축 결합부와, 상기 축 결합부의 외주면을 따라 소정 간격 이격되게 다수개의 지지리브로 구성되는 것을 특징으로 하는 선박용 그물 로프 양망장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

257/1150 Row 257: application_number: 1020190141700, combined_string: invention_title: 폐기물을 이용한 친환경 인공어초와, 이의 제조방법 abstract: 본 발명은 폐기물을 이용하면서도 수중 생태계를 오염시키지 않는 친환경 인공어초와, 이의 제조방법에 관한 것이다.본 발명에 따른 친환경 인공어초는, 바닥 구조물(100)의 테두리관(110)과, 기둥관(200) 및, 연결 보강관(300)이 내부에 충진되는 시멘트 혼합물을 매개로 상호 견고하게 일체화된 구조를 이루고, 이들 테두리관(110)과 기둥관(200) 및 연결 보강관(300)이 PE 재질이므로, 친환경 재질의 PE관 인공어초가 별도의 고정수단 없이도 자중에 의해 해저에 안전하게 고정되는 효과가 있다. 또한, 기둥관(200)의 상부와 하부가 시멘트 혼합물(A)을 매개로 견고하게 밀폐된 상태에서, 폐기물(B)을 기둥관(200)의 내부에 안전하게 보관 처리할 수 있게 되어, 폐기물 처리 문제가 해소되는 효과가 있다.또한, 본 발명의 제작방법에 따르면, PE관을 상호 연결하고, 시멘트 혼합재를 충진하고, 폐기물을 채워넣고 밀봉하며, 각 구성요소들을 상호 결합하는 일체의 제작 작업이 효율적이면서도 신뢰할 수 있게 이루어지는 효과가 있다. claims: 적어도 3개 이상의 제1삽입구가 형성되고, 이들 제1삽입구 사이에 적어도 1개 이상의 제2삽입구가 형성되어진 테두리관과, 테두리관의 내측에 설치되는 받침용 보강재로 이루어진 바닥 구조물과 ; 제1연통구가 형성된 하부는 테두리관의 제1삽입구에 삽입 고정되고, 상부는 바닥 구조물의 중심 상부에 위치되도록 기울어지게 설치되는 기둥관 ; 제3삽입구가 형성되고, 양쪽 선단이 인접한 기둥관에 각각 고정되는 가로관과, 상하부에 각각 제2연통구가 형성되되, 하부는 테두리관의 제2삽입구에 삽입 고정되고, 상부는 가로관의 제3삽입구에 삽입 고정되는 세로관으로 이루어진 연결 보강관 및; 바닥 구조물의 중심 상부로 모아진 기둥관들의 상부를 결속하는 제1고정재로 구성되되,상기 테두리관과 기둥관 및 연결 보강관은 PE관이고, 테두리관과 연결 보강관의 내부는 시멘트 혼합물로 충전되며, 기둥관의 상부와 하부가 시멘트 혼합물을 매개로 견고하게 밀폐된 상태에서, 기둥관의 내부에 폐기물이 채워진 것을 특징으로 하는 폐기물을 이용한 친환경 인공어초.테두리관과 받침용 보강재로 이루어진 바닥 구조물에 기둥관과 연결 보강관을 설치하는 제1공정 ;테두리관에 시멘트 혼합물을 타설, 양생해서, 테두리관의 내부가 시멘트 혼합물로 충전되고, 테두리관에 삽입되어 연통된 기둥관의 하부가 시멘트 혼합물로 밀폐되며, 연결 보강관을 구성하는 세로관의 하부가 시멘트 혼합물로 충전되어, 테두리관과 기둥관 및 세로관이 상호 견고하게 결합되도록 하는 제2공정 ;연결 보강관을 구성하는 가로관에 시멘트 혼합물을 타설, 양생해서, 가로관과 세로관의 내부가 시멘트 혼합물로 충전되어, 가로관과 세로관이 상호 견고하게 결합되도록 하는 제3공정 ;기둥관의 상부 개구면을 통해서 기둥관의 내부에 폐기물을 채워넣는 제4공정 ;기둥관의 상부 개구면을 통해서 기둥관의 내부에 밀봉재를 설치하여, 기둥관에 채워진 폐기물을 임시로 밀봉하는 제5공정 및;기둥관의 상부 개구면으로 시멘트 혼합물을 타설, 양생해서, 기둥관의 상부가 시멘트 혼합물로 밀폐되도록 하고, 바닥 구조물의 중심 상부로 모아진 기둥관들의 상부를 제1고정재를 매개로 결속하는 제6공정으로 이루어진 것을 특징으로 하는 폐기물을 이용한 친환경 인공어초 제조방법., Ltext: 어업, prediction: '어업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

258/1150 Row 258: application_number: 1020190136560, combined_string: invention_title: 바지락 유생 및 치패 중간육성장치 abstract: 본 발명은 바지락 유생 및 치패의 중간육성장치에 관한 것으로 가상식 구조물 구조로 일정 직경의 파이프가 파이프 클램프를 매개로 하나 이상 이격고정되고, 상기 마주하는 파이프는 코팅 와이어로 연결되며, 코팅 와이어 상부에는 안전망이 수평으로 설치되는 와류시설과, 상기 와류 시설에는 복수개의 채묘기가 설치되어 와류시설 내 와류를 일으켜 바지락 유생 및 치패를 채묘기내로 유도가 가능하고 바지락 채묘기를 신속하게 중간 육성장으로 이동 및 양성하기 용이한 잠입성 패류의 종묘육성장치 및 이를 이용한 채묘방법을 제공함으로써, 불안정한 국내 바지락 바지락 종패 수급문제 해결을 기대해 볼 수 있고, 자연채묘 된 바지락 유생 및 치패를 신속하게 중간육성장으로 이동 및 양성이 가능하도록 하여 생존율을 극대화 할 수 있을 뿐만 아니라 잠입성 패류의 자연채묘가능성 확보로 바지락이외의 다른 잠입성 패류에도 적용할 수 있는 효과가 있다. claims: 가상식 구조물 형태로 일정 직경의 파이프가 파이프 클램프를 매개로 바닥과 수직으로 하나 이상 이격 고정되어 평단면상 직사각형 구조를 이루고, 평행하는 파이프는 코팅와이어로 연결되며, 상기 코팅와이어 상부에는 안전망이 수평으로 설치되는 와류시설;상기 와류시설 안전망 상부 또는 하부의 갯벌에는 일정 크기의 다각형 구조로 형성되는 패류 채묘기가 설치되며,상기 패류 채묘기는 일정한 다각형의 외측을 구성하는 외측틀과 상기 외측틀의 내측에는 무결절 망지로 이루어진 그물망으로 이루어진 침착판과, 상기 그물망의 망사가 십자로 교차하는 부분에 일정한 인공잔디가 일정 간격으로 결합되며, 상기 침착판 하부에는 바닥판이 착탈 가능하도록 부착되며, 상기 인공잔디가 만드는 잔디와 잔디 사이의 공극에 잠입성 패류 유생이 착저될 수 있도록 한 것을 특징으로 하는 바지락 유생 및 치패의 중간육성장치가상식 구조물 형태로 일정 직경의 파이프가 파이프 클램프를 매개로 바닥과 수직으로 하나 이상 이격 고정되고 이격된 파이프 내측 양단을 연승줄이 연결되며, 연승줄에는 일정 크기의 다각형 구조로 형성되는 패류 채묘기가 설치되며,상기 패류 채묘기는 일정한 다각형의 외측을 구성하는 외측틀과 상기 외측틀의 내측에는 무결절 망지로 이루어진 그물망으로 이루어진 침착판과, 상기 그물망의 망사가 십자로 교차하는 부분에 일정한 인공잔디가 일정 간격으로 결합되며, 상기 침착판 하부에는 바닥판이 착탈 가능하도록 부착되며, 상기 인공잔디가 만드는 잔디와 잔디 사이의 공극에 잠입성 패류 유생이 착저될 수 있도록 한 것을 특징으로 하는 바지락 유생 및 치패의 중간육성장치일정한 다각형의 외측을 구성하는 외측틀과 상기 외측틀의 내측에는 무결절 망지로 이루어진 그물망으로 이루어진 침착판과, 상기 그물망의 망사가 십자로 교차하는 부분에 일정한 인공잔디가 일정 간격으로 결합되며, 상기 침착판 하부에는 바닥판이 착탈 가능하도록 부착되며, 상기 인공잔디가 만드는 잔디와 잔디 사이의 공극에 잠입성 패류 유생이 착저될 수 있도록 한 것을 특징으로 하는 바지락 유생 및 치패의 중간육성장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

259/1150 Row 259: application_number: 1020190135812, combined_string: invention_title: 꼬막 종패 분리 및 세척 장치 abstract: 본 발명은 꼬막 종패 분리 및 세척 장치에 관한 것으로서, 더욱 상세하게는 그물망 이동방향에 반대방향으로 회전되는 브러쉬 롤러로 물을 분사하여 부착된 꼬막 종패를 분리시키는 꼬막 종패 분리 및 세척 장치에 관한 것이다.본 발명의 꼬막 종패 분리 및 세척장치는 그물망 이송방향에 반대방향으로 회전되는 제1브러쉬 롤러에 의해 그물망에 부착된 꼬막종패를 분리시키면서, 제1브러쉬 롤러의 상방에 위치에서 물을 분사하는 물 분사관을 통해 동시에 그물망을 세척할 수 있어 작업 효율이 향상될 수 있는 이점이 있다. claims: 선박의 갑판 상에 설치되며 상방으로 꼬막 종패가 부착된 그물망이 이동되는 제1프레임과,상기 제1프레임 상에 상기 그물망의 이동방향에 반대방향으로 회전가능하게 설치되어 상기 그물망에 부착된 꼬막 종패를 분리시키는 제1브러쉬롤러와,상기 제1브러쉬 롤러의 상방에 위치되게 상기 제1프레임의 상단에 설치되고 상기 제1브러쉬 롤러의 길이방향에 나란하게 연장되어 상기 제1브러쉬 롤러 방향으로 상기 그물망 세척 및 꼬막 종패 분리를 위한 물을 분사하는 물 분사관과,상기 제1브러쉬 롤러를 회전시키는 위한 구동부와,상기 물분사관에 물 공급을 위한 제1물 공급펌프를 구비하는 것을 특징으로 하는 꼬막 종패 분리 및 세척장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

260/1150 Row 260: application_number: 1020190135967, combined_string: invention_title: 소형어선용그물망인출장 abstract: 본 고안의 소형 어선용 그물 인출장치는, 어선 본체의 상판 일측에 고정 설치된그물 인출장치를 전개하고자 하는 방향 또는 인양하고자 하는 방향으로 회전시켜 어선 본체의 외부로 돌출시킬 수 있기 때문에 그물의 전개 및 인양 작업이 용이함에 따라 작업 능률을 향상시킴과 아울러 인양시 그물에 일정 이상의 부하가 발생될 때 유압 모우터에 공급되는 오일을 제어하는 릴리이프 밸브가 마련되어 있기 때문에 장비의 고정 발생 및 그물이 찢어지는 현상을 방지할 수 있는 이점이 있다. claims: 어선 본체(1)의 상판(3)에 고정 설치된 하부 지지대(7)와; 상기한 하부 지지대(7)에 회전 가능하게 설치된 상부 지지대(9)와; 상기한 상부 지지대(9)에 고정 설치됨과 아울러 유압의 공급 방향에 따라 정, 역회전 가능한 유압 모우터(23)와; 상기한 유압 모우터(23)의 축상에 제공된 드럼(27)과; 상기한 유압 모우터(23)에 오일을 공급하도록 어선의 기관 작동에 연동하여 저장탱크(39)에 저장된 오일을 펌핑하는 오일펌프(41)와 연통설치되어 유로를 선택적으로 절환시키는 방향 전환 밸브(37)를 포함하여 이루어진 소형 어선용 그물 인출장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

261/1150 Row 261: application_number: 1020190129184, combined_string: invention_title: 개량형 사각어초 abstract: 본 발명은 개량형 사각어초에 관한 것으로서, 더욱 상세하게는 종래의 사각어초 구조를 개량하여 연약지반에서 침하를 방지함과 동시에 어패류가 서식할 수 있는 공간을 제공하고 해중림을 조성함으로써 수산자원을 보호하고 육성할 수 있는 사각어초에 관한 것이다. 본 발명의 개량형 사각어초는 어패류의 서식 및 해중림 조성을 위한 사각어초에 있어서, 내부가 비어있는 육면체 형태의 본체와, 본체를 전후 방향 및 좌우 방향, 상하 방향으로 관통할 수 있도록 본체의 각 면마다 형성된 개구부와, 본체의 전후면을 제외한 사면에 일정 간격으로 돌출되어 형성된 돌출부를 구비한다. claims: 어패류의 서식 및 해중림 조성을 위한 사각어초에 있어서, 내부가 비어있는 육면체 형태의 본체와;상기 본체를 전후 방향 및 좌우 방향, 상하 방향으로 관통할 수 있도록 상기 본체의 각 면마다 형성된 개구부와;상기 본체의 전후면을 제외한 사면에 일정 간격으로 돌출되어 형성된 돌출부;를 구비하는 것을 특징으로 하는 개량형 사각어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

262/1150 Row 262: application_number: 1020190129185, combined_string: invention_title: 침선 어초 abstract: 본 발명은 폐선박을 해저에 가라앉혀 설치하는 침선 어초에 관한 것으로서, 어패류가 서식하거나 은신할 수 있는 공간을 제공하여 바다 환경을 개선시킴과 동시에 강한 해류에도 전도되지 않고 불법어업을 방지할 수 있는 기능성이 부가된 침선 어초에 관한 것이다. 본 발명의 침선 어초는 상부구조물과 갑판 및 하부선체를 포함하는 폐선박을 개조하여 형성시킨 본체부와, 본체부의 내부로 해수가 유통될 수 있도록 하부선체의 측면에 일정 간격으로 형성된 출입구들과, 본체부의 내부에 설치되어 어패류의 서식공간 및 은신공간을 제공하는 단위어초들과, 본체부가 해저면에 안착된 경우 본체부의 전도를 방지하기 위해 본체부에 설치되는 전도방지수단을 구비한다. claims: 상부구조물과 갑판 및 하부선체를 포함하는 폐선박을 개조하여 형성시킨 본체부와; 상기 본체부의 내부로 해수가 유통될 수 있도록 상기 하부선체의 측면에 일정 간격으로 형성된 출입구들과; 상기 본체부의 내부에 설치되어 어패류의 서식공간 및 은신공간을 제공하는 단위어초들과;상기 본체부가 해저면에 안착된 경우 상기 본체부의 전도를 방지하기 위해 상기 본체부에 설치되는 전도방지수단;을 구비하는 것을 특징으로 하는 침선 어초., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

263/1150 Row 263: application_number: 1020190127066, combined_string: invention_title: 연체동물용 인공어초 abstract: 본 발명은, 연체동물용 인공어초로서, 사다리꼴 형태를 가지며, 전면과 후면에 연체동물이 유입될 수 있는 서식홈이 마련된 제1블록체; 및 상기 제1블록체의 면적보다 작은 면적을 가지는 사다리꼴 형태를 가지며, 상기 제1블록체의 측면과 결합되는 제2블록체;를 포함하며, 상기 제1블록체와 상기 제2블록체는 다수개로 마련된채 서로 교대로 결합되어 수평방향으로 연장된 방벽의 구조체를 형성하는 것을 특징으로 한다. claims: 연체동물용 인공어초로서,사다리꼴 형태를 가지며, 전면과 후면에 연체동물이 유입될 수 있는 서식홈이 마련된 제1블록체; 및상기 제1블록체의 면적보다 작은 면적을 가지는 사다리꼴 형태를 가지며, 상기 제1블록체의 측면과 결합되는 제2블록체;를 포함하며,상기 제1블록체와 상기 제2블록체는 다수개로 마련된채 서로 교대로 결합되어 수평방향으로 연장된 방벽의 구조체를 형성하는 연체동물용 인공어초에 있어서,상기 제2블록체는 상기 제1블록체의 측면에서 상기 서식홈의 개방된 측부를 차단하는 것을 특징으로 하는 연체동물용 인공어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

264/1150 Row 264: application_number: 1020190112375, combined_string: invention_title: 문어 산란용 어초 abstract: 본 발명은 문어 산란용 어초에 관련되며, 이때 문어 산란용 어초는 일체형 콘크리트 성형물로 형성되어 제작이 간편하면서 시공성이 우수하고, 출입구와 연통되는 산란공간부 상부영역이 가림블록에 의해 비노출되도록 차폐되어 문어 산란에 최적화된 서식환경을 조성함과 더불어 경사바닥면 및 퇴적물배출구에 의해 산란공간부로 유입되는 모래를 포함하는 이물질이 신속하게 배출처리되므로 산란공간부 내의 서식환경이 장기적으로 쾌적하게 유지되도록 하기 위해 본체블록(10), 산란공간부(20), 가림블록(30), 해수홀(40)을 포함하여 주요구성으로 이루어진다. claims: 제강슬래그골재 50~60 중량부, 전기로산화슬래그 20~30 중량부, 모래 10~20 중량부, 슬래그시멘트 10~15 중량부를 포함하는 혼합물로 형성되고, 받침다리(12)에 의해 저면이 해저바닥과 이격되어 하부해수통로(14)가 형성되도록 설치되는 본체블록(10);상기 본체블록(10) 일측으로 개방되는 출입구(22)와 연결되고, 천장에 평탄면(24)이 형성되는 산란공간부(20);상기 출입구(22) 상부에서 하향 돌출되어, 출입구(22)를 통하여 산란공간부(20) 상부영역이 비노출되도록 차폐하는 가림블록(30); 및상기 본체블록(10) 측면 및 상면에서 산란공간부(20) 내부로 관통되어 해수를 순환하도록 구비되는 해수홀(40);을 포함하여 이루어지고,상기 출입구(22)는 산란공간부(20) 대비 축소된 사이즈로 형성되어, 출입구(22) 바닥면이 산란공간부(20) 바닥면 연장선상에 일치되도록 편심 위치에 구비되며,상기 산란공간부(20) 바닥면과 출입구(22) 바닥면은 본체블록(10) 외부로 갈수록 하향 경사각을 이루는 경사바닥면(50)으로 형성되어, 산란공간부(20) 내부로 유입되는 모래를 포함하는 이물질이 경사바닥면(50)을 타고 본체블록(10) 외부로 배출되도록 구비되는 것을 특징으로 하는 문어 산란용 어초., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

265/1150 Row 265: application_number: 1020190104996, combined_string: invention_title: 인공어초 abstract: 본 발명은 콘크리트 재질의 박스형상의 프레임으로 각면에 유로가 형성된 유닛의 조립에 의해 형성되는 인공어초에 관한 것이다. claims: 콘크리트 재질의 박스형상의 프레임으로 각면에 유로가 형성된 유닛의 조립에 의해 형성되고,상기 유닛은 백태방지층이 외연에 도포되고,상기 백태방지층은, 수지 100중량부에 대해 다공성세라믹볼 20 내지 80중량부, 실리카퓸 20 내지 40중량부, 이산화티탄 10 내지 30중량부, 부틸카비톨 5 내지 10중량부, 부틸셀로솔브 5 내지 10중량부, 수용성증점제 1 내지 3중량부, 탄산수소칼륨 0.1 내지 2중량부를 포함하는 것을 특징으로 하는 인공어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

266/1150 Row 266: application_number: 1020190104200, combined_string: invention_title: 바이오플락 발효조와 아쿠아포닉스를 이용한 순환여과식 양식시스템 abstract: 물의 효과적인 순환을 가능하게 하는 생물사육수조; 유기물을 배출하지 않고 이를 다시 이용하여 바이오플락의 영양분을 이용하는 발효조; 또한 잔여 유기고형물을 자동으로 수세 및 역세를 통해 순환여과조 및 발효조로 이동이 가능한 유기고형물 제거 장치; 식물재배수조로 구성된 순환여과식 양식시스템(Recirculating aquaculture system; RAS)에서 발생한 유기물을 바이오플락(Biofloc Technology; BFT)으로 재활용하는 아쿠아포닉스 시스템을 제공함으로서, 양식생물과 재배식물의 생산성 증대로 이루어지며 또한 잔여 유기물의 세척을 통해 더욱 효과적인 수질관리를 통해 완전한 물 순환으로 매우 친환경적이며, 경비를 절감할 수 있는 시스템으로 친환경 양식 산업화에 기여한다. claims: 양식어종을 사육하는 순환여과식 양식시스템; 순환여과식 양식시스템에서 배수된 사육수를 필터링하는 드럼필터;상기 드럼필터의 필터링된 사육수가 이동되어 정화되는 순환여과시스템;상기 드럼필터의 역세수가 이동되어 정화되는 자동여과시스템; 상기 자동여과시스템의 역세수에 산소를 공급 및 혼합하는 바이오플락 발효시스템; 상기 바이오플락 발효시스템에서 이동된 고농도 산소가 혼합된 사육수로 식물 재배가 가능한 식물재배시스템;을 포함하여 이루어지는 것을 특징으로 하는 바이오플락 발효조와 아쿠아포닉스를 이용한 순환여과식 양식시스템양식어종을 사육하는 순환여과식 양식시스템; 순환여과식 양식시스템에서 배수된 사육수를 바이오플락 발효시스템에서 식물재배용 사육수로 정화하여 식물재배시스템으로 공급하여 사용한 후, 순환여과식 양식시스템으로 공급하는 순환구조를 갖는 포함하여 이루어지는 것을 특징으로 하는 바이오플락 발효조와 아쿠아포닉스를 이용한 순환여과식 양식시스템, Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

267/1150 Row 267: application_number: 1020190104030, combined_string: invention_title: 안전한 서식환경이 구비된 어류 서식처 및 시공방법 abstract: 본 발명은 안전한 서식환경이 구비된 어류 서식처 및 시공방법에 관한 것으로서, 강이나 바다에서 물고기 등과 같은 어류의 안전한 서식환경 및 산란처를 제공함으로써 수상 생태계 복원에 효과를 나타내기 위한 것이다.이를 실현하기 위한 본 발명의 어류 서식처는, 어류의 출입이 가능하도록 일측에 출입공간(11)이 형성된 육면체 형상의 철망 하우징(10)과; 상기 철망 하우징(10) 상부에 안착 되는 다수의 조경석(20)과; 상기 철망 하우징(10)과 조경석(20) 사이에 배치되어 식물의 성장이 이루어지는 식생매트(30);를 포함하는 구성을 이루는 것을 특징으로 한다. claims: 어류의 출입이 가능하도록 일측에 출입공간(11)이 형성된 육면체 형상의 철망 하우징(10)과;상기 철망 하우징(10) 상부에 안착 되는 다수의 조경석(20)과;상기 철망 하우징(10)과 조경석(20) 사이에 배치되어 식물의 성장이 이루어지는 식생매트(30);를 포함하되,상기 철망 하우징(10)은 내부에 자갈이 채워진 상태에서 개별 제작된 다수개가 중앙에 출입공간(11)을 형성하도록 연결 조립된 구조를 이루되, 상호간의 대응 부위에는 볼트 체결을 위한 연결플레이트(10a)가 구성되며, 철망 하우징(10)에는 내부의 수류 유동을 제한하기 위하여 측벽 둘레를 따라 일정 높이로 방수시트(12)가 구성됨과 함께 측압을 지지하기 위한 지지핀(13)이 구성되고, 상부에 형성된 출입공간(11)에는 조경석(20)의 중량을 지지하기 위한 강봉(14)이 격자 형태로 구비된 것을 특징으로 하는 안전한 서식 환경이 구비된 어류 서식처.어류의 출입이 가능하도록 일측에 출입공간(11)이 형성된 육면체 형상의 철망 하우징(10)과;상기 철망 하우징(10) 상부에 안착 되는 다수의 조경석(20)과;상기 철망 하우징(10)과 조경석(20) 사이에 배치되어 식물의 성장이 이루어지는 식생매트(30);를 포함하되,상기 철망 하우징(10)의 내부 바닥면 일측에는 산란환경 조성을 위한 맥반석(15)을 구성하되, 상기 맥반석(15)의 유동을 방지하기 위한 유동방지벽(16)이 일측에 구비되고, 상기 맥반석(15)에는 일정 점성을 유지하는 코팅층(15a)이 형성되며, 상기 코팅층(15a)은 코코넛 활성탄, 굴패각 분말, 실리콘, 폴리글리콜, 이산화티탄, 클로브 오일, 벤토나이트 분말, 나노은의 혼합 조성을 이루는 것을 특징으로 하는 어류 서식처.어류의 출입이 가능하도록 일측에 출입공간(11)이 형성된 육면체 형상의 철망 하우징(10)과;상기 철망 하우징(10) 상부에 안착 되는 다수의 조경석(20)과;상기 철망 하우징(10)과 조경석(20) 사이에 배치되어 식물의 성장이 이루어지는 식생매트(30);를 포함하되,상기 철망 하우징(10) 내부에는 조경석(20)의 하중을 탄성 지지하기 위한 탄성스프링(17)이 구성되고, 상기 탄성스프링(17)의 상부와 하부에는 각각 안정적인 지지력 유지를 위한 지지플레이트(18)가 연결 구성된 것을 특징으로 하는 어류 서식처.청구항1 또는 청구항3 또는 청구항4 또는 청구항5의 어류 서식처를 설치함에 있어서,조립형 구조를 이루는 철망 하우징(10)의 상부에 식생매트(30)와 조경석(20)을 순차적으로 안착시킨 후, 식생매트(30)에 식물을 식재하여 시공이 이루어짐을 특징으로 하는 어류 서식처 시공방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

268/1150 Row 268: application_number: 1020190100847, combined_string: invention_title: 어업도구 상태정보 제공 시스템 및 그 제어방법. abstract: 본 발명은 원격 어구 모니터링 시스템에 관한 것이며, 구체적으로 개별 어구의 위치 및 상태정보를 모니터링할 수 있는 원격 어구 모니터링 시스템에 관한 것이다. 특히 수중에 설치된 어구의 상태정보까지 감시하는 기술을 제공한다.구성은 다음과 같다.수면아래에 설치되는 어구(40)의 길이방향 상하단에 서로 일정간격 이격시켜 설치한 복수의 기울기센서(50)와,상기 복수의 기울기센서(50)와 유선으로 통신되도록 연결하여 수면에 떠 있는 부표(51)에 설치하는 무선통신부(52)를 포함한 상태에서, 바다에 어구(40) 투척으로 수면아래로 안착된 어구의 기울기가 기 설정된 기울기 범위에 있는 경우 어구(40)에 어류가 유입(포획)될 수 있는 상태에 있는 것으로 판단하고 무선통신부(52)를 통해 관리자측에 어구상태를 송신하고,수중에 설치한 어구(40)의 기울기가 기 설정된 기울기 범위를 벗어나는 경우 어구(40)가 뒤죽박죽되어 어류를 포획할 수 없는 것으로 판단하고 무선통신부(52)를 통해 관리자측에 어구상태를 송신하는 구성이다. claims: 수면아래에 설치되는 어구(40)의 길이방향 상하단에 서로 일정간격 이격시켜 설치한 복수의 기울기센서(50)와,상기 복수의 기울기센서(50)와 유선으로 통신되도록 연결하여 수면에 떠 있는 부표(51)에 설치하는 무선통신부(52)를 포함한 상태에서, 바다에 어구(40) 투척으로 수면아래로 안착된 어구의 기울기가 기 설정된 기울기 범위에 있는 경우 어구(40)에 어류가 유입(포획)될 수 있는 상태에 있는 것으로 판단하고 무선통신부(52)를 통해 관리자측에 어구상태를 송신하고,수중에 설치한 어구(40)의 기울기가 기 설정된 기울기 범위를 벗어나는 경우 어구(40)가 뒤죽박죽되어 어류를 포획할 수 없는 것으로 판단하고 무선통신부(52)를 통해 관리자측에 어구상태를 송신하는 구성을 특징으로 하는 어업도구 상태정보 제공 시스템 및 그 제어방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

269/1150 Row 269: application_number: 1020190099346, combined_string: invention_title: 어로용 통발 abstract: 본 발명은 어로용 통발에 관한 것으로서, 그 목적은 유인구의 출구 또는 포획구의 포획부가 탄성력이 아닌 어류의 추진력에 의해 개방되고, 자중에 의해 닫혀지도록 함으로서, 출구 또는 포획부를 헐거워짐이 전혀 발생됨이 개폐될 수 있도록 할 수 었어 반영구적으로 통발의 유효수명을 연장될 수 있어 어로단가를 현저히 낮출 수 있을 뿐만 아니라 어획량도 크게 증대시킬 수 있도록 하는 것이며, 그 구성은 상, 하부링의 사이에 등간격으로 다수의 지지바가 연결된 통발 몸체와, 상기 통발 몸체의 외부를 그물망이 감사게 설치되되, 상기 그물망의 상부에 개폐가능한 배출구가 형성되고, 입구가 넓고 출구가 좁게 형성된 사각깔대기 형상의 망체로서 상기 그물망의 측면에 형성된 개방부에 결합 설치된 유인구로 구성된 어로용 통발에 있어서, 상기 유인구는 출구의 상단부 및 하단부에 각각 회동가능하게 힌지결합되고, 출구를 개폐하는 2개의 차단부재를 구비한 것을 특징으로 한다. claims: 상, 하부링의 사이에 등간격으로 다수의 지지바가 연결된 통발 몸체와, 상기 통발 몸체의 외부를 그물망이 감사게 설치되되, 상기 그물망의 상부에 개폐가능한 배출구가 형성되고, 입구가 넓고 출구가 좁게 형성된 사각깔대기 형상의 망체로서 상기 그물망의 측면에 형성된 개방부에 결합 설치된 유인구로 구성된 어로용 통발에 있어서,상기 유인구(10)는,출구(10a)의 상단부 및 하단부에 각각 회동가능하게 힌지결합되고, 출구(10b)를 개폐하는 2개의 탈출방지 차단부재(20)를 구비한 것을 특징으로 하는 어로용 통발., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

270/1150 Row 270: application_number: 1020190099382, combined_string: invention_title: 어로용 통발의 제조방법 abstract: 본 발명은 어로용 통발의 제조방법에 관한 것으로서, 그 목적은 액상 코팅재과 코팅틀을 사용하여 그물망을 통발본체상에 견고하게 장착시키는 동시에 그물망을 확실하게 보호할 수 있으면서도 작업생산성을 현저히 향상시킬 수 있도록 하는 것이며, 그 구성은 상부링 및 하부링를 각각 가로지르도록 상부링 및 하부링의 내측에 가로대를 설치하고, 가로대가 설치된 상부링 및 하부링 사이에 다수개의 지지바를 설치하여 통발 프레임인 통발본체를 제작하는 통발본체 제작단계와; 상기 통발본체 제작단계를 통해 완성된 통발본체의 외측에 그물망을 덮어 감싼 미완성 통발을 제작하는 그물망 설치단계와; 코팅액이 채워진 코팅틀 내에 상기 그물망 설치단계를 통해 제작된 미완성 통발의 하부링 및 하부링과 접하고 있는 그물망 부분까지 함께 완전히 잠기도록 미완성 통발을 코팅틀 상에 배치시키고, 코팅액이 완전히 경화되어 코팅체가 하부링의 외측을 따라 형성되도록 하는 하부 코팅체 형성단계와; 상기 하부코팅체 형성단계가 완료되면, 코팅액이 채워진 코팅틀 내에 상기 그물망 설치단계를 통해 제작된 미완성 통발의 상부링 및 상부링과 접하고 있는 그물망 부분까지 함께 완전히 잠기도록 미완성 통발을 코팅틀 상에 배치시키고, 코팅액이 완전히 경화되어 코팅체가 상부링의 외측을 따라 형성되도록 하는 상부 코팅체 형성단계를 포함하는 것을 특징으로 한다. claims: 상, 하부링의 사이에 등간격으로 다수의 지지바가 설치된 통발 몸체와, 상기 통발 몸체의 외부를 그물망이 감싸게 설치되되, 상기 그물망의 상부에 개폐가능한 배출구가 형성되고, 입구가 넓고 출구가 좁게 형성된 사각깔대기 형상의 망체로서 상기 그물망의 측면에 형성된 개방부에 결합 설치된 유인구로 구성되고, 내측에 미끼를 놓은 상태로 물속에 배치하여 미끼에 의해 유인된 어류를 포획하는 어로용 통발을 제조하기 위한 어로용 통발의 제조방법에 있어서,상기 제조방법은,상부링(21) 및 하부링(22)를 각각 가로지르도록 상부링(21) 및 하부링(22)의 내측에 가로대(21a)(22a)를 설치하고, 가로대(21a)(22a)가 설치된 상부링(21) 및 하부링(22) 사이에 다수개의 지지바(23)를 설치하여 통발 프레임인 통발본체(20)를 제작하는 통발본체 제작단계(S100)와;상기 통발본체 제작단계(S100)를 통해 완성된 통발본체(20)의 외측에 그물망(30)을 덮어 감싼 미완성 통발(10a)을 제작하는 그물망 설치단계(S200)와;코팅액이 채워진 코팅틀 내에 상기 그물망 설치단계(S200)를 통해 제작된 미완성 통발(10a)의 하부링(22) 및 하부링(22)과 접하고 있는 그물망 부분까지 함께 완전히 잠기도록 미완성 통발(10)을 코팅틀 상에 배치시키고, 코팅액이 완전히 경화되어 코팅체(40)가 하부링(22)의 외측을 따라 형성되도록 하는 하부 코팅체 형성단계(S300)와;상기 하부코팅체 형성단계(S300)가 완료되면, 코팅액이 채워진 코팅틀 내에 상기 그물망 설치단계(S100)를 통해 제작된 미완성 통발(10a)의 상부링(21) 및 상부링(21)과 접하고 있는 그물망 부분까지 함께 완전히 잠기도록 미완성 통발(10)을 코팅틀 상에 배치시키고, 코팅액이 완전히 경화되어 코팅체(41)가 상부링(21)의 외측을 따라 형성되도록 하는 상부 코팅체 형성단계(S400)를 포함하는 것을 특징으로 하는 어로용 통발의 제조방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

271/1150 Row 271: application_number: 1020190095341, combined_string: invention_title: 외해 수중 가두리 장치 abstract: 본 발명과 관련된 외해 수중 가두리 장치는, 수중에 설치되는 그물의 상부 테두리를 형성하며, 부력을 가질 수 있게 형성된, 상부림; 상기 그물의 하부 테두리를 형성하는 하부림; 및 상기 하부림에 연결되는 복수의 무게추를 포함하고, 상기 상부림은, 고정된 부력을 제공할 수 있도록 공기가 채워져 밀봉된 제1림; 상기 제1림과 동심 형태로 배치되며, 가변 부력을 제공하는, 제2림; 상기 제2림의 일측에 설치되며, 공기가 상기 제2림의 내부로 유출입될 수 있게 설치되는 공기 연결부; 및 상기 제2림의 다른 일측에 설치되며, 상기 공기 연결부를 통하여 공기가 상기 제2림으로 유입될 때 내부의 해수가 유출되도록 하고, 상기 공기 연결부를 통하여 공기가 상기 제2림으로부터 유출될 때 해수가 유입되도록 하는, 해수 연결부를 포함하고, 상기 해수 연결부는 상기 제2림으로부터 상기 하부림으로 연장된 형태로 형성될 수 있다. claims: 수중에 설치되는 그물의 상부 테두리를 형성하며, 부력을 가질 수 있게 형성된, 상부림;상기 그물의 하부 테두리를 형성하는 하부림; 및상기 하부림에 연결되는 복수의 무게추를 포함하고,상기 상부림은,고정된 부력을 제공할 수 있도록 공기가 채워져 밀봉된 제1림;상기 제1림과 동심 형태로 배치되며, 가변 부력을 제공하는, 제2림;상기 제2림의 일측에 설치되며, 공기가 상기 제2림의 내부로 유출입될 수 있게 설치되는 공기 연결부; 및상기 제2림의 다른 일측에 설치되며, 상기 공기 연결부를 통하여 공기가 상기 제2림으로 유입될 때 내부의 해수가 유출되도록 하고, 상기 공기 연결부를 통하여 공기가 상기 제2림으로부터 유출될 때 해수가 유입되도록 하는, 해수 연결부를 포함하고,상기 해수 연결부는 상기 제2림으로부터 상기 하부림으로 연장된 형태로 형성되며,상기 해수 연결부의 단부는 상기 하부림으로 연장되어 상기 하부림에 고정부재에 의하여 고정된 형태로 설치되고,상기 상부림의 상기 해수 연결부가 위치된 쪽에 보조 무게추가 설치되며,상기 상부림의 상기 공기 연결부가 위치된 쪽에 보조 부력체가 설치된, 외해 수중 가두리 장치., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

272/1150 Row 272: application_number: 1020190080025, combined_string: invention_title: 꽁치 부산물을 이용한 갈치 낚시용 인공미끼 및 이의 제조방법 abstract: 본 발명은 꽁치 부산물을 이용한 갈치 낚시용 인공미끼 및 이의 제조방법에 관한 것으로, 본 발명의 갈치 낚시용 인공미끼는 꽁치를 처리하는 과정에서 발생되는 부산물을 활용하여 인공미끼를 제조함으로써 꽁치 특유의 향과 집어제 및 형광색소로 인해 갈치를 시각적 및 후각적으로 유인하여 갈치 집어능력을 향상시키는 효과가 있다. claims: 꽁치 부산물 100 중량부;젤라틴 60 내지 70중량부;집어제 1.5 내지 2.5 중량부; 및비타민 B2 5 내지 15 중량부;를 포함하며,15,000 내지 30,000 gf의 경도를 갖는, 갈치 낚시용 인공미끼.꽁치 부산물을 분쇄하고, 물과 혼합하여 가열 후 꽁치 부산물 건더기와 꽁치 부산물 추출액을 분리하는 단계(단계 1);상기 단계 1의 꽁치 부산물 추출액에 젤라틴을 혼합하고 젤라틴을 녹이는 단계(단계 2); 및상기 단계 2의 혼합액에 상기 단계 1의 꽁치 건더기, 집어제 및 비타민 B2를 첨가하고 틀에 넣어 굳히는 단계(단계 3);를 포함하며,상기 꽁치 부산물 100 중량부 기준 젤라틴은 60 내지 70중량부, 집어제는 1.5 내지 2.5 중량부, 비타민 B2를 5 내지 15 중량부를 사용하고, 15,000 내지 30,000 gf의 경도를 갖도록 하는 것인, 갈치 낚시용 인공미끼의 제조방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

273/1150 Row 273: application_number: 1020210014213, combined_string: invention_title: 어류 양식장용 사료공급시스템 및 이를 이용한 사료공급방법 abstract: 본 발명은 어류 양식장용 사료공급시스템 및 이를 이용한 사료공급방법에 관한 것으로, 보다 상세하게는 요구하는 분사방향으로 사료분사수단이 회전될 수 있을 뿐만 아니라, 사료의 분사량이 자동으로 조절될 수 있는 어류 양식장용 사료공급시스템 및 이를 이용한 사료공급방법에 관한 것이다. 본 발명은 다음과 같은 효과를 발휘한다.즉, 본 발명에 따르면, 육상의 양식장이나 해상의 가두리 양식장과 같이 제한된 공간에서도 그 설치 및 운용이 편리하도록 소형으로 제작이 가능하고, 하나의 사료공급장치로 여러 개의 양식수조나 가두리그물에 대한 선택적 자동급이가 가능하며, 필요시 여러 대의 사료공급장치를 서로 연결하여 일괄 제어토록 할 수도 있는 등, 양식장의 정량토출식 급이관리와 현장제어 및 원격제어에 의한 급이작업의 자동화 측면에 최적화된 시스템을 제공하는 효과가 있으며, 보다 더 나아가서는 사료공급량의 정확한 측정과 체계적인 데이터 관리 및 이를 기초로 한 피드백 제어를 통하여 급이작업의 편의성과 능률성을 극대화시킴으로서, 양식업자들의 수익 향상과 양식산업의 대외경쟁력 확보 측면에도 크게 이바지할 수 있는 등의 매우 유용한 효과가 있다. claims: 수조(10)에 사료를 공급하는 사료공급부재(100);상기 사료공급부재(100)에 의해 수조(10)에 사료가 공급될 때 물고기가 사료를 섭취하는 과정에서 발생되는 수면의 출렁거림을 촬영하는 영상촬영수단(200);상기 영상촬영수단(200)에서 촬영된 영상에서 수면의 출렁거림의 정도를 분석하여, 사료공급부재(100)에서 공급될 사료의 목표량을 수치화하는 연산부(300);상기 연산부(300)에서 수치화된 목표량에 부합되도록 사료공급부재(100)를 제어하여 사료의 공급량을 조절하는 제어부(400);를 포함하고,상기 사료공급부재(100)는사료가 저장되는 사료저장통(110)과,상기 사료저장통(110)의 하부에 형성되되, 배출제어부(410)에 의해 제어되어 사료저장통(110)에서 배출되는 사료의 양이 조절되는 배출조절수단(120)과,상기 배출조절수단(120)의 하부에 형성되어, 배출조절수단(120)에서 이동된 사료를 수조(10)에 분사하는 사료분사수단(130)과,상기 사료분사수단(130)의 하부에 형성되어, 사료분사수단(130)을 회전시키되, 회전제어부(420)에 의해 회전속도 및 회전방향이 제어되는 회전수단(140)을 포함하고,상기 영상촬영수단(200)은배출조절수단(120)의 일측에 형성되되, 사료분사수단(130)의 출구를 향하여 형성되는 것을 특징으로 하고,상기 제어부(400)는연산부(300)에서 수치화된 목표량을 기준으로 배출조절수단(120)의 사료 배출량을 제어하는 배출제어부(410)와,연산부(300)에서 수치화된 목표량을 기준으로 회전수단(140)의 회전속도 및 회전방향을 제어하는 회전제어부(420)를 포함하는 것을 특징으로 하는어류 양식장용 사료공급시스템.제1항 내지 제3항 중 어느 한 항의 어류 양식장용 사료공급시스템을 이용하여 사료를 공급하는 방법에 있어서,수조(10)에 소정량의 사료를 공급하는 단계(S100);상기 공급된 사료를 물고기가 섭취하는 과정에서 발생되는 수면의 출렁거림을 촬영하는 단계(S200);상기 촬영된 영상에서 수면의 출렁거림의 정도를 분석하여, 사료공급부재(100)에서 공급될 사료의 목표량을 수치화하는 단계(S300);상기 수치화된 목표량에 부합되도록 사료공급부재(100)를 제어하여, 사료의 공급량을 조절하면서 수조(10)에 사료를 공급하는 단계(S400);를 포함하는 것을 특징으로 하는어류 양식장용 사료공급시스템을 이용한 사료공급방법., Ltext: 어업, prediction: '어업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

274/1150 Row 274: application_number: 1020200128506, combined_string: invention_title: 양식장용 산소 용해 장치 abstract: 본 발명은 양식장에 공급되는 해수에 산소를 투입하여 용존산소율을 향상하기 위해 양식장에 공급되는 해수가 유입되는 유입파이프(100)와, 상기 유입파이프로 유입되는 해수에 기화된 산소를 공급하는 산소공급구(200)와, 상기 유입파이프에 연결되어 산소와 해수가 혼합되어 공급되는 혼합공급구(300)를 구한 양식장용 산소용해장치에 있어서,상기 혼합공급구(300)가 상부에 설치되고, 혼합공급구(300)를 통해 유입된 해수에 혼합 유입된 기체산소가 용해되는 산소용해통체(400)와, 상기 산소용해통체(400) 내부에 설치되어 공급되는 산소의 압력에 따라 수위가 조절될 수 있도록 해수 유출면적이 조절되는 산소용해파이프(500)를 구비하며, 상기 산소용해파이프(500)의 단부에 연결되어 산소용해통체(400)의 외부로 해수가 배출되는 배출구(600)를 구비하여 형성된 것을 특징으로 하는 양식장용 산소용해장치를 제공한다. claims: 양식장에 공급되는 해수에 산소를 투입하여 용존산소율을 향상하기 위해 양식장에 공급되는 해수가 유입되는 유입파이프(100)와, 기화된 산소를 공급하는 산소공급구(200)와, 상기 유입된 산소와 해수가 혼합되면서 공급된 산소가 해수에 용해되는 양식장용 산소용해장치에 있어서,상기 양식장용 산소용해장치는 상부에는 공급된 기체 산소와 해수가 혼합되는 혼합공간부(A)와 상기 혼합공간부(A) 하부에는 해수가 일정한 해수 수위(410)를 가지는 해수공간부(B)와, 상기 해수공간부(B) 하부에 배출구(600)를 구비한 산소용해통체(400)로 이루어지며,또한, 상기 산소용해통체(400) 내부에서 배출구(600)와 연결되는 산소용해파이프(500)를 더 구비하며,상기 산소용해파이프(500)는 상기 배출구(600)와 수평방향으로 연결되는 수평파이프(510)와,상기 수평파이프(510)와 수직 방향으로 연결되는 수직파이프(520)로 이루어지며,상기 산소용해파이프(500)에는 일정한 간격으로 통공되어 형성된 해수 유출홀(530)이 구비되고,상기 해수공간부(B)의 해수가 해수 유출홀(530)을 통하여 산소용해파이프(500)에 연결된 상기 배출구(600)로 배출되되,상기 혼합공간부(A) 내의 압력을 일정하게 유지될 수 있도록 상기 혼합공간부(A) 압력에 따라 해수가 산소용해파이프(500)로 배출되는 해수유출 면적(M3)이 변경되며,상기 해수유출 면적(M3)의 변경은 혼합공간부(A)의 압력에 의하여 해수공간부(B)의 해수 수위(410)가 변화되고, 상기 해수 수위(410)의 변화에 의하여 해수공간부(B)에서 수직파이프(520)에 형성된 해수가 유입되는 해수 유출홀(530)의 개수가 변경됨에 따라 해수가 유출되는 면적이 변경되는 것을 특징으로 하는 양식장용 산소용해장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

275/1150 Row 275: application_number: 1020200100615, combined_string: invention_title: 돌망태를 이용한 해삼 양식장 및 그 시공방법 abstract: 본 발명은 돌망태를 이용한 해삼 양식장 및 그 시공방법에 관한 것으로서, 파도의 영향으로 인한 해삼의 유실을 방지하는 가운데 친환경 돌망태를 이용하여 해삼의 생장에 필요한 다양한 요소를 구비한 생태환경을 제공하기 위한 것이다.이를 실현하기 위한 본 발명은, 그물망(11)의 내부에 다수의 골재(20)가 채워져 구성되는 돌망태(10)를 이용하여 해삼 양식장을 조성함에 있어서, 해삼의 양식이 이루어지는 양식공간(A)을 일정 면적으로 형성시키기 위해 다수의 돌망태를 선형으로 배치하는 양식공간 형성구간(100)과; 상기 양식공간 형성구간(100) 주변을 둘러싸는 형태로 다수의 돌망태(10)를 다층의 선형으로 배치하여 파도의 영향을 차단하는 쇄파 상쇄구간(200, 300, 400);을 포함하는 구성을 이루는 것을 특징으로 한다. claims: 그물망(11)의 내부에 다수의 골재(20)가 채워져 구성되는 돌망태(10)를 이용하여 해삼 양식장을 조성함에 있어서,해삼의 양식이 이루어지는 양식공간(A)을 일정 면적으로 형성시키기 위해 다수의 돌망태를 선형으로 배치하는 양식공간 형성구간(100)과;상기 양식공간 형성구간(100) 주변을 둘러싸는 형태로 다수의 돌망태(10)를 다층의 선형으로 배치하여 파도의 영향을 차단하는 쇄파 상쇄구간(200, 300, 400);을 포함하고,상기 쇄파 상쇄구간(200, 300, 400)은 최 외곽에 형성되는 1차 쇄파 상쇄라인(400)과, 그 내측에 일정 간격을 이루어 순차적으로 형성되는 2차 쇄파 상쇄라인(300) 및 3차 쇄파 상쇄라인(200)으로 이루어지며, 그중 1차 쇄파 상쇄라인(400)은 돌망태(10)를 2단~4단으로 쌓아서 일정 높이로 적층 시키고, 상기 각각의 쇄파 상쇄구간(200, 300, 400) 사이에는 멸치, 다시마, 미역을 갯벌, 흙과 섞어서 열을 가하지 아니하고 압축한 형상으로 제작한 시비재(30)가 구비됨을 특징으로 하는 돌망태를 이용한 해삼 양식장.그물망(11)의 내부에 다수의 골재(20)가 채워져 구성되는 돌망태(10)를 이용하여 해삼 양식장을 조성함에 있어서,해삼의 양식이 이루어지는 양식공간(A)을 일정 면적으로 형성시키기 위해 다수의 돌망태를 선형으로 배치하는 양식공간 형성구간(100)과;상기 양식공간 형성구간(100) 주변을 둘러싸는 형태로 다수의 돌망태(10)를 다층의 선형으로 배치하여 파도의 영향을 차단하는 쇄파 상쇄구간(200, 300, 400);을 포함하고,상기 양식공간(A)에는 멸치, 다시마, 미역을 갯벌, 흙과 섞어서 육면체 형상으로 제작한 시비재(30) 및 어린 치삼의 생장공간(41)이 반원의 동굴 형태로 형성된 해삼전용 어초(40)가 구비됨을 특징으로 하는 돌망태를 이용한 해삼 양식장.청구항 1 또는 청구항 3의 해삼 양식장을 시공함에 있어서,수중에 돌망태를 배치하여 해삼의 양식이 이루어지는 양식공간을 일정 면적으로 형성시키기 위해 다수의 돌망태를 선형으로 배치하여 양식공간 형성구간을 시공한 후, 상기 양식공간 형성구간 주변을 둘러싸는 형태로 다수의 돌망태를 선형으로 배치하여 파도의 영향을 차단하는 쇄파 상쇄구간을 시공하는 것을 특징으로 하는 돌망태를 이용한 해삼 양식장 시공방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

276/1150 Row 276: application_number: 1020200071698, combined_string: invention_title: 양식수조내 어류의 먹이활동성 측정 장치 및 이를 이용한 먹이 공급 방법 abstract: 본 발명과 관련된 양식수조내 어류의 먹이활동성 측정 장치는, 수면 상에서 부유하며 파동에 따라 흔들릴 수 있게 형성된 함체; 상기 함체 내에 설치되는 센서모듈; 상기 함체를 양식수조 상에 지지시키는 지지부; 상기 센서모듈에 의해 감지된 신호를 전송할 수 있게 형성된 통신모듈; 및 상기 통신모듈을 통하여 수신된 감지신호를 통하여 양식수조 내 어류의 먹이활동 및 양식수조의 상태를 모니터링할 수 있게 형성된 제어부를 포함할 수 있다. claims: 수면 상에 부유하는 함체 내에 지지되는 가속도센서에 의하여 파동을 측정하는 단계;측정된 상기 가속도센서의 신호를 통신모듈에 의하여 제어부에 전송하는 단계;상기 가속도센서의 신호를 기초로 양식수조 내의 어류의 먹이활동의 강도를 산정하는 단계; 및상기 어류의 먹이활동의 강도에 따라 급이장치를 통해 공급되는 먹이를 조절하는 단계를 포함하고,상기 가속도센서의 신호를 기초로 양식수조 내의 어류의 먹이활동의 강도를 산정하는 단계는,재귀필터를 활용하여 데이터 잡음을 제거하는 과정을 포함하며,상기 가속도센서의 신호를 기초로 양식수조 내의 어류의 먹이활동의 강도를 산정하는 단계는,일정 시간간격으로 측정된 3축 방향의 가속도벡터값들을 수신하는 단계;상기 3축 방향의 가속도벡터의 합을 n개(n은 2이상의 자연수)의 참조갯수만큼 취하여 평균을 구하는 단계; 및특정 구간에서 먹이활동 측정 이벤트가 발행하였을 때 상기 특정 구간 이전의 값을 기준값으로 하여 상기 기준값과 실시간 측정되는 이동평균값 사이의 상대오차값을 비율로 환산하여 먹이활동성을 추정하는 단계를 포함하는, 양식수조내 어류의 먹이활동성 측정 장치를 이용한 먹이 공급방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

277/1150 Row 277: application_number: 1020200065835, combined_string: invention_title: 에너지 저감 수로 유수식 친환경 축제식 양식장 abstract: 본 발명은 육상의 축제식 양식장을 제공하면서 해안가의 산비탈면 또는 육지의 산이나 폐광산의 경사면 암반을 굴착하여 양식장을 제공함으로써 에너지 사용을 줄일 수 있는 친환경적인 축제식 양식장에 관한 발명이다.본 발명은 산의 경사면에 수조를 계단식으로 다단으로 형성하고, 상기 수조의 바닥에는 소정의 두께로 모래가 구비되며, 상기 수조의 내부에는 모래를 일측으로 이동시키기 위한 모래이동부가 더 구비되며, 상기 수조의 일측에는 수조의 모래를 배출시켜 이동시키기 위한 모래배출관이 연결되며, 상기 모래배출관의 끝단에는 배출되는 모래에 부착된 이물질을 세척하기 위한 모래세척부가 결합되고, 상기 모래세척부에서 세척된 모래가 수조로 공급되도록 하는 것을 특징으로 한다.본 발명은 산의 경사면에 다단으로 수조를 형성하여 육상 양식장을 제공함으로써, 어류의 양식 생산성을 높이고 어업인의 소득을 증대시킬 수 있는 효과가 있다. claims: 산의 경사면에 수조를 계단식으로 다단으로 형성하고,상기 수조의 바닥에는 소정의 두께로 모래가 구비되며,상기 수조의 내부에는 모래를 일측으로 이동시키기 위한 모래이동부가 더 구비되며, 상기 모래이동부는 상기 수조의 내부를 횡방향을 가로지르며 회전하는 회전축과, 상기 회전축에 설치되어 수조의 바닥에 깔린 모래를 모래배출관 측으로 이동시키기 위한 밀대를 포함하며,상기 수조의 외측에는 상기 모래이동부를 회전시키기 위한 구동부가 더 구비되며, 상기 구동부는 구동모터와 구동축 및, 상기 모래이동부의 회전축과 치합되어 구동축의 회전력을 회전축에 전달하는 베벨기어를 포함하며,상기 수조의 일측에는 수조의 모래를 배출시켜 이동시키기 위한 모래배출관이 연결되고, 상기 모래배출관의 끝단에는 배출되는 모래에 부착된 이물질을 세척하기 위한 모래세척부가 결합되고,상기 모래세척부의 타측에서 수조의 타측 사이에는 모래공급관이 연결되어, 상기 모래세척부에서 세척된 모래가 수조로 재 공급되도록 하며,상기 수조는 모래의 이동이 용이하도록 모래공급관 측 바닥면이 모래배출관 측 바닥면 보다 더 높도록 경사지게 형성되고, 모래이동부도 모래공급관 측에서 모래배출관 측으로 갈수록 점차 위치가 낮게 위치하도록 형성되며,상기 수조의 일측면에는 양식수유입관이 구비되고, 고압의 펌프에 의해 공급되는 양식수가 상기 양식수유입관을 통해 최상단의 수조 일측으로 공급되며,상기 최상단 수조부터 최하단 수조 사이를 연통배수로가 일측 또는 타측 끝단에 지그재그 형태로 연통되도록 형성되어, 상기 최상단 수조로 공급된 양식수가 최하단의 수조로 유입되는 것을 특징으로 하는 축제식 양식장., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

278/1150 Row 278: application_number: 1020200052002, combined_string: invention_title: 양식장 슬러지 배출장치 abstract: 본 발명은 양식장 슬러지 배출장치에 관한 것으로, 더욱 상세하게는 배출관 내에 공기의 주입 조절이 가능한 에어백을 삽입하여 배출관에 형성된 배출공을 통한 슬러지 및 양식수의 배출을 조절하도록 함으로써, 양식장 내 슬러지와 배수관 내 슬러지의 배출이 효과적으로 이루어지도록 하고, 배출에 대한 제어가 용이하게 이루어질 수 있도록 하는 양식장 슬러지 배출장치에 관한 것이다. claims: 양식장 바닥에 매입되어 외부로 양식수를 배출하는 배수관과; 양식장 내에 삽입되어 배수관과 연결되며, 배출공이 관통되어 양식장 내의 슬러지를 배수관으로 배출하는 배출관과; 상기 배수관 및 배출관을 연결하는 배수연결부와; 상기 배출관을 통한 슬러지의 배출을 조절하는 배출조절부와; 상기 배출조절부의 작동을 조절하는 제어부;를 포함하고, 상기 배출조절부는 상기 배출관 내에 삽입되어 공기의 주입에 따라 배출공을 개폐하는 에어백과, 상기 배출관 내에 형성되어 에어백을 지지하는 받침지지대와, 상기 에어백에 대한 공기의 주입을 조절하는 공기주입수단을 포함하며, 상기 공기주입수단은 상기 배출관 상단으로 인입되어 에어백에 공기를 주입하는 주입관과, 상기 주입관에 대한 공기의 주입 및 배출을 조절하는 주입조절밸브와, 양식장 내에 연결되어 주입관으로 주입되는 공기를 순환시키는 공기순환관을 포함하고, 상기 배수연결부는, 상기 배출관의 둘레를 따라 끼워지며, 양식장 바닥에 포설되는 차수시트와 동일한 소재로 형성되어 차수시트와 부착되는 부착어댑터와; 상기 부착어댑터의 내측 둘레를 따라 접착되며, 상기 배출관과 동일한 소재로 형성되어 배출관에 부착되는 연결소켓과; 상기 부착어댑터에 차수시트를 고정시키는 시트고정수단;을 포함하고, 상기 시트고정수단은 상기 부착어댑터에 부착되어  형상으로 형성되는 지지프레임과, 상기 지지프레임에 삽입되어 탄성에 의해 차수시트를 관통·고정시키는 탄성고정체를 포함하며, 상기 탄성고정체는 상기 지지프레임 및 차수시트를 관통하는 관통부재와, 상기 관통부재의 상단에 형성되어 지지프레임 상부에 걸리는 걸림단과, 상기 관통부재의 둘레를 따라 돌출되어 차수시트를 누르는 누름단과, 상기 지지프레임 및 누름단 사이에 삽입되어 누름단을 하측으로 누르는 누름탄성부재를 포함하고, 상기 제어부는 상기 에어백에 대한 압력을 조절하는 압력조절부와, 상기 배수관 바닥에 쌓이는 슬러지의 양에 따라 자동으로 배출조절부를 작동시키는 배출작동부와, 슬러지의 처리 정도에 따라 배출조절부의 작동 상태를 진단하는 처리진단부를 포함하고, 상기 압력조절부는 상기 배출조절부의 작동개시정보를 수신하는 작동정보수신모듈과, 상기 주입조절밸브를 조작하여 에어백에 설정된 양의 공기를 주입하는 밸브조절모듈과, 상기 배출관의 배출공 주위에 형성되는 압력측정센서로부터 에어백의 접촉에 의한 압력정보를 수신하는 압력정보수신모듈과, 수신된 압력정보에 따라 주입조절밸브를 미세조절하는 미세조절모듈과, 상기 압력측정센서에 의해 측정된 압력과 초기 설정된 압력의 차를 산출하는 압력차산출모듈과, 산출된 압력차를 설정된 경계값과 비교하는 경계값비교모듈과, 압력차가 경계값을 초과하는 경우 에어백의 교체 필요를 알리는 교체알림모듈을 포함하며, 상기 배출작동부는 상기 배수관 내에 형성되어 배수관에 쌓이는 슬러지를 감지하는 슬러지센싱모듈과, 상기 슬러지센싱모듈에 의한 감지정보에 따라 슬러지의 양을 산출하는 슬러지양산출모듈과, 산출된 슬러지양을 복수의 구간으로 설정된 값과 비교하는 설정값비교모듈과, 슬러지양에 따른 구간에 따라 배출조절부의 작동시간을 설정하는 작동시간설정모듈과, 상기 배출조절부의 작동을 개시하는 작동개시모듈과, 상기 배출조절부의 작동개시 후 상기 슬러지센싱모듈에 의해 슬러지의 양을 감시하는 슬러지감시모듈과, 슬러지의 양이 일정값 이하로 줄어드는 경우 배출조절부의 작동을 중단하는 자동중단모듈과, 작업시간의 종료에도 슬러지의 양이 일정값 이하로 줄지 않는 경우 일정값이 될 때까지 배출조절부를 추가 작동시키는 추가작동모듈을 포함하고, 상기 처리진단부는 상기 슬러지센싱모듈에 의해 감지되는 초기 슬러지 양과 작동시간의 종료후 감지되는 슬러지의 양을 비교하여 처리율이 기준값 이하인 경우 배출조절부의 결함으로 판단하는 결함확정부와, 슬러지의 처리율이 결함으로 확정되는 기준값을 초과하는 근접범위에서 연속되는 경우 처리율의 저하정도와 연속정도에 따라 결함이 발생되는 시기를 예측하는 결함예측부와, 결함으로 확정되거나 결함시기가 예측되지 않더라도 슬러지의 처리율이 급격하게 떨어지는 경우 배출조절부에 대한 점검을 요청하는 점검요청부를 포함하며, 상기 결함확정부는 상기 작동시간설정모듈에 의해 설정된 작동시간의 종료정보를 수신하는 시간만료정보수신모듈과, 종료시점에 상기 슬러지센싱모듈에 의해 측정되는 슬러지의 양을 산출하는 잔여량산출모듈과, 초기 슬러지 양 및 잔여 슬러지양의 비율에 따라 처리율을 산정하는 처리율산정모듈과, 산정된 처리율을 기준값과 비교하는 기준값비교모듈과, 처리율이 기준값 이하인 경우 배출조절부의 결함으로 판정하여 이를 알리는 결함판정모듈을 포함하고, 상기 결함예측부는 슬러지의 처리율이 설정된 근접범위에 도달하는 것을 감지하는 근접범위감지모듈과, 근접범위에서 연속되는 경우 그 횟수를 산정하는 연속횟수산정모듈과, 처리율이 설정된 정상값에서 벗어나는 정도를 합산하여 결함지수를 산출하는 결함지수산출모듈과, 결함지수에 따라 결함으로 확정되는 시기를 예측하는 결함시기예상모듈을 포함하며, 상기 점검요청부는 슬러지 처리율이 저하 정도를 산정하는 저하율산정모듈과, 산정된 저하율을 임계값과 비교하는 임계값비교모듈과, 저하율이 임계값을 초과하는 경우 그 연속횟수를 산출하는 지속횟수산출모듈과, 연속횟수가 설정된 횟수를 초과하는 경우 점검을 지시하는 점검지시모듈을 포함하는 것을 특징으로 하는 양식장 슬러지 배출장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

279/1150 Row 279: application_number: 1020200046565, combined_string: invention_title: 스마트양식장 사료공급장치 및 이의 제어 방법 abstract: 스마트양식장 사료공급장치 및 이의 제어 방법이 개시된다. 이에 의하면, 양식 수조의 수면 영상과 내부환경정보 및 상기 양식 수조내의 서식 어류의 정보를 수신하는 입력부; 와, 어종별 사료섭취패턴 및 소화 기능을 학습하여 어종별 사료공급모델을 생성하는 학습부; 와, 상기 수면 영상을 분석하여 서식 어류가 사료 공급 개시 후 양식 수조에 최초로 투입되는 초기사료공급량을 소비하는 먹이행동패턴을 분석하는 분석부; 와, 양식 수조내에 소정량의 사료를 공급할 수 있도록, 사료 저장고에 밸브 개방 신호를 전송하는 사료 공급부; 및 어종별 사료공급모델 중에서 서식 어류에 대응하는 소정 사료공급모델을 선택하고, 소정 사료공급모델을 참조하여 초기사료공급량을 설정한 후, 사료 공급이 개시되면 초기사료공급량을 양식 수조내에 투입하도록 사료 공급부를 제어하고, 소정 사료공급모델 및 먹이행동패턴을 참조하여 서식 어류에의 단계별 공급 사료량을 결정한 후, 단계별 공급 사료량을 순차적으로 상기 양식 수조내에 투입하도록 사료 공급부를 제어하는 제어부를 포함한다. claims: 스마트양식장 사료공급장치에 있어서,양식 수조의 수면 영상과 내부환경정보 및 상기 양식 수조내의 서식 어류의 정보를 수신하는 입력부;어종별 사료섭취패턴 및 소화 기능을 학습하여 어종별 사료공급모델을 생성하는 학습부;상기 수면 영상을 분석하여, 상기 서식 어류가 사료 공급 개시 후 상기 양식 수조에 최초로 투입되는 초기사료공급량을 소비하는 먹이행동패턴을 분석하는 분석부;상기 양식 수조내에 소정량의 사료를 공급할 수 있도록, 사료 저장고에 밸브 개방 신호를 전송하는 사료 공급부; 및 상기 어종별 사료공급모델 중에서 상기 서식 어류에 대응하는 소정 사료공급모델을 선택하고, 상기 소정 사료공급모델을 참조하여 상기 초기사료공급량을 설정한 후, 사료 공급이 개시되면 상기 초기사료공급량을 상기 양식 수조내에 투입하도록 상기 사료 공급부를 제어하고, 상기 소정 사료공급모델 및 상기 먹이행동패턴을 참조하여 상기 서식 어류에의 단계별 공급 사료량을 결정한 후, 상기 단계별 공급 사료량을 순차적으로 상기 양식 수조내에 투입하도록 상기 사료 공급부를 제어하는 제어부를 포함하고,상기 학습부는,어류의 소화기관의 외부형태 및 조직학성 특성 중 적어도 하나에 기초하여 상기 어종별 사료섭취패턴 및 상기 소화 기능을 학습하는, 스마트양식장 사료공급장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

280/1150 Row 280: application_number: 1020200036815, combined_string: invention_title: 버블을 이용한 양식장의 적조방제 및 고수온 억제 장치 abstract: 본 발명은 버블을 이용한 양식장의 적조방제 및 고수온 억제 장치에 관한 것으로, 보다 상세하게는 양식장의 외측에 설치된 버블 생성부를 통해 버블막을 형성하여 양식장 내로 적조가 유입되는 현상을 방지할 수 있으면서 양식장의 하측에 설치된 버블 생성부에서 배출된 버블을 이용하여 수면에 비해 상대적으로 저온인 바닷물을 수면으로 상승시켜 양식장의 수온 상승을 억제할 수 있는 양식장의 적조방제 및 고수온 억제장치에 관한 것이다.이러한 본 발명은, 공기를 압축하는 압축공기 생성부(10); 양식장의 외측을 둘러싸는 형태로 수중에 설치되고, 상기 압축공기 생성부(10)에서 생성된 압축공기를 수중으로 배출하며 수면을 향해 부상하는 버블을 양식장(60) 외측을 둘러 생성하여 양식장(60) 내로 적조의 유입을 방지하는 제1버블 생성부(20a); 상기 양식장(60) 하측으로 수면보다 수온이 3℃ 이하 낮은 수심상에 배치되고, 상기 압축공기 생성부(10)에서 생성된 압축공기를 배출하여 양식장(60)을 향해 부상하는 버블을 생성하고 수면보다 상대적으로 낮은 온도의 바닷물을 수면으로 상승시켜 수면의 온도를 낮추는 제2버블 생성부(20b);를 포함하여 이루어진다. claims: 복수의 부표(61)와, 상기 부표(61)를 연결하며 결합되는 파이프(62)와, 수중에 설치되는 그물(64)을 포함하여 이루어지는 양식장(60)에 설치되는 적조방제 및 고수온 억제 장치에 있어서,공기를 압축하는 압축공기 생성부(10);상기 양식장(60)의 외측을 둘러싸는 형태로 수중에 설치되고, 상기 압축공기 생성부(10)에서 생성된 압축공기를 수중으로 배출하며 수면을 향해 부상하는 버블을 양식장(60) 외측을 둘러 생성하여 양식장(60) 내로 적조의 유입을 방지하는 제1버블 생성부(20a);상기 양식장(60) 하측으로 수면보다 수온이 3℃ 이하 낮은 수심상에 배치되고, 상기 압축공기 생성부(10)에서 생성된 압축공기를 배출하여 양식장(60)을 향해 부상하는 버블을 생성하고 수면보다 상대적으로 낮은 온도의 바닷물을 수면으로 상승시켜 수면의 온도를 낮추는 제2버블 생성부(20b);를 포함하고,상기 압축공기 생성부(10)에서 상기 제1버블 생성부(20a)와 제2버블 생성부(20b) 중 하나 이상으로 압축공기의 공급은 각각의 경로를 선택적으로 개폐함에 의해 제어되는 것을 특징으로 하는 버블을 이용한 양식장의 적조방제 및 고수온 억제 장치., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

281/1150 Row 281: application_number: 1020200024101, combined_string: invention_title: 철갑상어의 육질을 향상시키는 방법 abstract: 본 발명이 제공하는 어육의 품질을 향상시키는 방법은 저온, 청정 및 부영양화 특성을 갖춘 심층 해수를 이용해 담수로 염도를 10-20ppt까지 조정하고, 수온을 20℃ 미만으로 낮추어 철갑상어를 적어도 2주 동안 양식 처리하면, 그 맛과 풍미를 분명하게 향상시킬 수 있고, 제품의 가치를 높일 수 있다. claims: 철갑상어를 담수 환경에서 적어도 1kg 무게의 성년 철갑상어까지 양식하며,염도 10ppt~20ppt의 범위, 수온이 20℃ 미만으로 유지되는 혼합 염수 중에서, 상기 성년 철갑상어를 적어도 2주간 귀화시키며,상기 혼합 염수는 심층 해수와 담수를 혼합해서 만들며,상기 단계를 포함하는 것을 특징으로 하는 철갑상어 육질을 향상시키는 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

282/1150 Row 282: application_number: 1020200022623, combined_string: invention_title: 어미 해삼 육상관리를 통한 해삼 인공종묘의 조기생산방법 abstract: 본 발명은 모삼의 사육수온을 12주간 8℃ 까지 낮추었다가 14주간 18℃ 까지 올려 관리하는 단계(가), (가)단계의 모삼을 수온자극, 표면자극, 건조자극을 통해산란자극으로 산란과 방정시키는 단계(나), (나)단계에서 얻은 수정란을 수조에서 발생시키는 단계(다), (다)단계에서 발생된 치삼이 0.5 g으로 성장할 때까지 파판에서 사육하는 단계(라), 및 (라)단계에서 치삼이 0.5 g으로 성장하면 치삼을 특수망지에서 사육하는 단계(마)로 이루어진 어미 해삼 육상관리를 통한 조기생산 및 생산시기 조절방법을 제공함으로써, 우량의 해삼종묘를 안정적으로 확보하고, 해삼 종묘생산이 가능한 기간을 확대할 뿐만 아니라, 해삼의 양식기간을 단축시킬 수 있어 해삼양식 어가의 소득증대에 기여할 수 있다. claims: (가) 육상수조에서 사료를 공급하면서 다년간 관리되는 모삼을 이용한 인공종묘생산은 저온 관리 기간의 사육수온을 자연수온에서 12주간 8℃ 까지 낮추는 단계로 관리하고, (나) 산란유발 전까지 사육수온을 8℃에서 11 내지 12주간 사육수온 17.5℃ 내지 18℃로 단계별로 승온하여 산란유도까지 18℃로 유지하는 단계로 관리하며, (다) 상기 (나)단계의 관리되는 모삼을 산란자극으로 산란과 방정시켜 얻은 수정란을 사육수조에서 발생시키며, (라) 상기 (다)단계에서 발생된 치삼이 0.5g으로 성장할 때까지는 육상수조의 해삼 양식장치에서 사육시키고, 치삼이 0.5g으로 성장하면 망사를 여러겹 묶어서 형성한 특수망지로 옮겨서 사육하는 단계로 이루어지며, 상기 해삼 양식장치는 해삼이 부착하여 성장하는 복수개의 파판이 바닥면과 수직하게 형성될 수 있도록 하는 상부 파판 홀더부의 하부에 양식장 바닥면과 수평하게 하나 이상의 파판이 수납될 수 있도록 한 수용부를 갖는 하부 파판 홀더부가 상기 상부 파판홀더부와 일체로 결합되어 이루어지며; 상기 상부 파판 홀더부는 가로 및 세로 부재가 연결되어 상부가 개구된 사각틀 형상의 상부면과 상부면을 이루는 가로 및 세로 부재와 연결되는 일정 길이의 수직부재가 하부 파판 홀더부와 일체로 결합되어 상광하협의 내부 공간부를 갖는 구조를 이루며, 상기 상부 파판 홀더부의 좌측 및 우측면의 수직부재는 서로 마주하는 방향을 향해 65 내지 75도 사이각으로 경사를 이루며 상광하협의 하향 수렴 구조를 갖고 하부 파판 홀더부의 상부 내측면에 일체로 결합되며 상기 하부 파판 홀더부는 수직부재와 수평부재의 결합으로 직육면체 형상을 이루고, 전면 또는 후면에는 하부 파판이 바닥면과 수평으로 수납될 수 있도록 파판 수용부가 형성되며, 상기 하부 파판 홀더부 하부 모서리에는 받침대가 형성되어 이루어지는 것을 특징으로 하는 어미 해삼 육상관리를 통한 해삼 인공종묘 조기생산방법, Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

283/1150 Row 283: application_number: 1020190172658, combined_string: invention_title: 가두리양식장용 적조차단장치 abstract: 본 발명은 가두리양식장용 적조차단장치에 관한 것으로서, 바닷물에서 번식하는 미생물의 영향으로 생기는 적조현상을 차단할 수 있도록 한 것이다. 본원 발명은 구체적으로 해양에 발생하는 적조 현상으로 인한 가두리양식장의 피해를 없애기 위한 것으로서, 특히 가두리양식장의 테두리를 따라서 해저에 목기장치를 설치함으로써 조류를 따라서 흘러들어오는 적조의 유입을 사전에 차단하며, 더불어 양식장의 해저의 낮은 수온을 표층으로 순환시킴으로써 여름철 고온수로 인한 양식장의 피해를 줄이는 것을 특징으로 하는 가두리양식장용 적조차단장치에 관한 것이다. claims: 격자형의 형상을 가지도록 수면위에 떠 있는 부유수단(100); 상기 부유수단(100)의 상면에 배치된 격자형의 작업통로(200);상기 작업통로(200)를 따라서 수중으로 배치되어 어류의 양식공간을 형성하는 그물망(300)을 구비하는 가두리양식장에 있어서, 압축공기를 제공하는 공기압축기(500):상기 부유수단(100) 하부의 수중에 배치되되 상기 부유수단(100)의 가장자리를 따라서 장방형으로 결합되고 로프에 의해서 수직하방향으로 달아내려져서 적조의 외부유입을 차단하는 공기방울 보호벽을 형성하도록 수중에 배치되는 제1폭기파이프(400);장방형의 상기 제1폭기파이프(400)들의 내부에 배치되는 제2폭기파이프(800);상기 공기압축기(500)와 상기 제1폭기파이프(400) 및 제2폭기파이프(800)를 연결하는 압축공기공급관(510); 및 상기 제1폭기파이프(400)와 상기 제2폭기파이프(800)는 상기 압축공기공급관(510)으로부터 공급되는 압축공기를 수중에서 분사할 수 있도록 길이방향으로 다수의 노즐(410)이 구비되는 것을 특징으로 하는 가두리양식장용 적조차단장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

284/1150 Row 284: application_number: 1020190172105, combined_string: invention_title: 수소 생산 및 양식장 수온 관리 통합 시스템 및 그 운용 방법 abstract: 본 발명은 해수를 전기분해하여 수소 및 차아염소산 나트륨을 생산하고, 생산된 수소의 일부를 수소연료전지로 공급하여 전기를 생산하며, 생산된 수소의 나머지 일부를 양식장으로 공급하여 물을 냉각시켜 수온을 일정한 온도로 관리할 수 있는 수소 생산 및 양식장 수온 관리 통합 시스템 및 방법에 관한 것으로, 본 발명에 따른 수소 생산 및 양식장 수온 관리 통합 시스템은 해수를 전기분해하여 수소 기체와 차아염소산 나트륨(NaOCl)을 생산하는 해수전기분해부; 상기 해수전기분해부에서 생산된 수소 기체의 일부와, 상기 해수전기분해부에서 생성된 산소 기체 또는 외부에서 공급되는 산소 기체를 공급받아 전기에너지를 생산하는 수소 연료전지; 상기 수소 연료전지에서 생산된 전기에너지를 저장하는 축전지; 상기 해수전기분해부에서 생산된 수소 기체의 나머지 일부와, 외부의 액화질소공급원에서 공급되는 액화질소의 열교환을 통해 수소를 액화시켜 액화수소를 생성하는 수소액화부; 상기 수소액화부에서 생성된 액화수소를 공급받아, 상기 액화수소와 양식장의 수온을 조절하기 위한 냉각수와의 열교환을 통해 냉각수를 냉각시키는 양식장수온관리부; 상기 양식장수온관리부를 통과하여 이송된 수소 기체를 흡수하여 저장하는 수소저장합금을 포함하는 수소저장부;를 포함한다. claims: 해수를 전기분해하여 수소 기체와 차아염소산 나트륨(NaOCl)을 생산하는 해수전기분해부;상기 해수전기분해부에서 생산된 수소 기체의 일부와, 상기 해수전기분해부에서 생성된 산소 기체 또는 외부에서 공급되는 산소 기체를 공급받아 전기에너지를 생산하는 수소 연료전지;상기 수소 연료전지에서 생산된 전기에너지를 저장하는 축전지;상기 해수전기분해부에서 생산된 수소 기체의 나머지 일부와, 외부의 액화질소공급원에서 공급되는 액화질소의 열교환을 통해 수소를 액화시켜 액화수소를 생성하는 수소액화부;상기 수소액화부에서 생성된 액화수소를 공급받아, 상기 액화수소와 양식장의 수온을 조절하기 위한 냉각수와의 열교환을 통해 냉각수를 냉각시키는 양식장수온관리부;상기 양식장수온관리부를 통과하여 이송된 수소 기체를 흡수하여 저장하는 수소저장합금을 포함하는 수소저장부;를 포함하는 수소 생산 및 양식장 수온 관리 통합 시스템.제1항 내지 제5항 중 어느 한 항에 따른 수소 생산 및 양식장 수온 관리 통합 시스템의 운용 방법으로서, (S1) 해수전기분해부에서 해수를 전기분해하여 수소 기체와 차아염소산 나트륨(NaOCl)을 생산하는 단계;(S2) 상기 해수전기분해부에서 생산된 수소 기체의 일부를 수소 연료전지로 공급하여 전기에너지를 생산하고, 생산된 전기에너지를 축전지에 저장하는 단계;(S3) 상기 해수전기분해부에서 생산된 수소 기체의 나머지 일부를 수소액화부로 공급하고, 상기 수소액화부에 액화질소공급원에서 공급되는 액화질소를 공급하여 상기 수소기체와 액화질소 간의 열교환을 통해 수소를 액화시켜 액화수소를 생성하는 단계;(S4) 상기 수소액화부에서 생성된 액화수소를 양식장수온관리부로 공급하여 양식장의 수온을 조절하기 위한 냉각수를 냉각시키는 단계; 및,(S5) 상기 양식장수온관리부를 통과하여 이송된 수소 기체를 수소저장부에 저장하는 단계;를 포함하는 수소 생산 및 양식장 수온 관리 통합 시스템의 운용 방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

285/1150 Row 285: application_number: 1020190170378, combined_string: invention_title: 공압을 이용한 양식 자동화 장치 abstract: 다각형의 수조바닥을 일정높이의 수조외벽이 둘러싸며 내부 사육공간과 상부 개구부가 형성되는 양식수조; 상기 수조바닥에는 사육수 및 양식 슬러지가 배수될 수 있는 배수장치가 설치되며; 상기 배수장치와 연결되는 배수관을 매개로 배수된 사육수 및 양식 슬러지가 상기 양식수조의 어느 한 모서리부에 설치되는 수집부로 이동하며; 상기 양식수조에는 자동적으로 먹이공급과 사육수의 pH를 조절할 수 있는 공압식 자동사료 공급장치 및 공압식 자동 pH조절장치, 바이오플락 수질 조절에 필요한 미생물, 배양액, 수질조절제 자동공급장치, 자동환수장치중에서 선택되는 하나 이상의 장치가 설치되며; 상기 수집부에 저장된 바이오플락 사육수 및 양식 슬러지는 수처리시스템 이동관을 통해 수처리시스템으로 이동하여 정화 및 슬러지가 제거되며; 상기 수처리시스템에는 인라인 UV살균시스템이 장착된 재공급관이 설치되어 미생물 밀도가 조절된 사육수가 상기 양식수조로 재공급되도록 이루어진 공압식 자동화 양식장을 제공함으로써, 양식장 운영비용을 줄일 수 있으면서 동시에 자동적으로 양식장 관리를 할 수 있는 효과가 있다. claims: 다각형의 수조바닥을 일정높이의 수조외벽이 둘러싸며 내부 사육공간과 상부 개구부가 형성되는 양식수조; 상기 수조바닥에는 사육수 및 양식 슬러지가 배수될 수 있는 배수장치가 설치되며; 상기 배수장치와 연결되는 배수관을 매개로 배수된 사육수 및 양식 슬러지가 상기 양식수조에 설치된 수집부로 이동하며; 상기 양식수조에는 하나의 공압 라인에서 분지된 하나 이상의 공압 자동제어장치가 설치되며;상기 수집부에 저장된 바이오플락 사육수 및 양식 슬러지는 수처리시스템 이동관을 통해 수처리시스템으로 이동하여 정화 및 슬러지가 제거되며; 상기 수처리시스템에는 인라인 UV살균시스템이 장착된 재공급관이 설치되어 미생물 밀도가 조절된 사육수가 상기 양식수조로 재공급되도록 이루어진 것을 특징으로 하는 공압을 이용한 양식 자동화 장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

286/1150 Row 286: application_number: 2020190005015, combined_string: invention_title: 양어장용 수차 abstract: 본 발명에 따른 양어장용 수차는, 수면에 떠 있도록 부력을 제공하는 좌,우측 부구; 상기 좌,우측 부구위에 서로 마주보는 2개의 측변이 결합수단에 의해 고정 설치되는 사각프레임; 상기 사각프레임상에 설치되어 모터를 지지하는 수직프레임; 동력을 제공하는 모터; 상기 모터의 회전축에 설치된 웜; 상기 웜으로부터 치합 연결되어 동력을 전달받는 웜기어; 상기 웜기어의 중심을 관통하여 회전가능하도록 상기 사각프레임상에 구비되는 &amp;quot;U&amp;quot;자 형태를 갖는 두 개 이상의 합성수지재 지지부에 의해 지지되는 종동축; 및 상기 사각프레임 및 수직프레임을 포함하고, 상기 종동축의 양측에 구비되는 좌,우측 프로펠러가 수면 위에 있도록 지지하는 지지 프레임을 포함한다. claims: 수면에 떠 있도록 부력을 제공하는 좌,우측 부구(10,11);상기 좌,우측 부구(10,11) 위에 서로 마주보는 2개의 측변이 결합수단에 의해 고정 설치되는 사각프레임(21);상기 사각프레임(21)상에 설치되어 모터(30)를 지지하는 수직프레임(22);동력을 제공하는 모터(30);상기 모터의 회전축에 설치된 웜(40);상기 웜(40)으로부터 치합 연결되어 동력을 전달받는 웜기어(50);상기 웜기어(50)의 중심을 관통하여 회전가능하도록 상기 사각프레임(21)상에 구비되는 &amp;quot;U&amp;quot;자 형태를 갖는 두 개 이상의 합성수지재 지지부(70)에 의해 지지되는 종동축(60); 및상기 사각프레임(21) 및 수직프레임(22)을 포함하고, 상기 종동축(60)의 양측에 구비되는 좌,우측 프로펠러(80)가 수면 위에 있도록 지지하는 지지 프레임(20)을포함하는 양어장용 수차., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

287/1150 Row 287: application_number: 1020190164247, combined_string: invention_title: 해삼 또는 전복 양식용 패널 및 이의 시공 방법 abstract: 본 발명은 해삼 또는 전복 양식용 패널 및 이의 시공 방법에 관한 것으로, 외주면에 다공질 홀(10a)이 다수 형성되어 있는 다공성 콘크리트 재질로 이루어져 있으며, 직선으로 이루어진 일측변부(11)와, 상기 일측변부(11)로부터 일정 거리 이격되어 일측변부(11)와 평행을 이루는 타측변부(12)와, 일측변부(11)와 타측변부(12)의 양측 끝단으로부터 각각 타측변부(12)와 일측변부(11)를 향해 직선으로 형성되어 있는 연결변부(13)와, 양측 연결변부(13)의 끝단으로부터 중앙을 향해 경사지게 형성되어 있는 경사변부(14)와, 양측의 경사변부(14)를 서로 연결하는 직선형의 경사연결변부(15)로 이루어진 평면 형상을 취하고, 일측변부(11)와 타측변부(12)의 양측 끝단에 형성된 두 연결변부(13)를 연결하는 가상의 선과 경사변부(14) 및 경사연결변부(15)에 의해 둘러쌓인 공간인 연결홈부(16)가 형성되어 있고, 경사연결변부(15)를 연장한 가상의 선, 경사변부(14), 일측변부(11) 타측변부(12)에 의해 둘러쌓인 공간인 돌출부(17)가 형성되어 있으며, 인접한 본체(10)들의 일측변부(11) 측 돌출부(17) 및 타측변부(12) 측 돌출부(17)가 상기 연결홈부(16)에 끼워져 서로 연결 조립되고, 상면 중앙에는 저면까지 관통된 용기삽입홀(18)이 형성되어 있으며, 상기 용기삽입홀(18)의 주변에는 벽면에 다수의 걸림홈(19a)이 형성된 다수 개의 핀삽입홈(19)이 형성되어 있고, 일측변부(11)와 타측변부(12)의 저부 모서리에는 길이방향을 따라 각각 &amp;quot;ㄴ&amp;quot;자 단면 형상의 외곽홈(20)이 형성되어 있으며, 양측의 외곽홈(20)과 이격되어 저부 중앙에는 상기 용기삽입홀(18)과 연통되며, 외곽홈(20)과 평행한 방향으로 &amp;quot;∪&amp;quot;자 단면 형상의 중앙홈(21)이 형성되어 있고, 일측 끝단이 외곽홈(20)과 연통되어 있으며, 타측 끝단은 중앙홈(21)과 연통되어 있고, &amp;quot;∪&amp;quot;자 단면 형상의 교차홈(22)이 다수 형성되어 있으며, 상기 외곽홈(20), 중앙홈(21), 교차홈(22)에 의해 둘러쌓이며 저부로 돌출된 다수 개의 저부돌출부(23)가 형성되어 있는 본체(10)와 하부 둘레에 측면개구부(31)가 형성되어 있으며, 내부에 양식용 해삼 또는 전복 종묘가 저장되는 저장공간(32)이 형성되어 있고, 상기 용기삽입홀(18)에 삽입되되, 측면개구부(31)가 위치한 하부가 본체(10) 저부의 중앙홈(21)으로 돌출되어 저장공간(32)이 중앙홈(21)과 연통되도록 이루어져 있으며, 상부에는 덮개(33)가 설치되어 저장공간(32)을 개폐시키도록 이루어져 있으며, 토기 재질로 이루어진 저장용기(30)를 포함하여 구성되며, 전후로 인접한 본체(10)의 일측변부(11)와 타측변부(12)가 서로 맞닿아 각각 저부에 형성되어 있는 외곽홈(20)이 접하여 &amp;quot;∪&amp;quot;자형 단면의 통로를 이루면서 좌우로 인접한 본체(10)의 중앙홈(21)이 상기 통로와 연통되도록 이루어져 있는 것을 특징으로 하며, 상면에는 핀삽입홈이 형성되어 있어 해중림을 조성할 수 있도록 하며, 본체의 저부에는 해삼 및 전복 종묘가 인접한 본체의 저부 사이로 이동 가능하도록 통로를 형성하는 한편, 본체 중앙에는 해삼 또는 전복 종묘가 저장되는 저장공간이 구비된 저장용기가 삽입되되, 저장용기의 내부가 본체 저부의 통로와 연통되도록 함으로써 본체의 저부에 외부와 최대한 격리된 성장 공간을 제공할 수 있게 된다. claims: 청구항 1은 본 발명의 해삼 또는 전복 양식용 패널의 상측 부분을 나타낸 분해 사시도.청구항 2는 본 발명의 해삼 또는 전복 양식용 패널의 저부측을 나타낸 분해 사시도.청구항 3은 본 발명의 해삼 또는 전복 양식용 패널이 다수 연결된 상태를 저부측에서 나타낸 사시도.청구항 4는 본 발명에서 상측에 로프삽입홈이 형성된 예를 나타낸 분해 사시도., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

288/1150 Row 288: application_number: 1020190157770, combined_string: invention_title: 수하식 양식 구조물 abstract: 본 발명은 수하식으로 양식이 가능한 구조물에 관한 것으로서, 본 발명의 일 실시예에 따르면, 다수 개의 부력체; 다수 개의 부력체 간을 연결하는 제1연결라인; 제1연결라인으로부터 하방으로 연장된 다수개의 제2연결라인; 및 다수 개의 제2연결라인과 연결되고, 양식물이 성장되는 하나 이상의 수하라인이 하방으로 배치되도록 하는 제3연결라인;을 포함하고, 양식물의 자중은 제3연결라인, 제2연결라인, 제1연결라인 및 다수 개의 부력체로 순차적으로 전달되는, 수하식 양식 구조물이 제공된다. claims: 다수 개의 부력체;상기 다수 개의 부력체 간을 연결하는 제1연결라인;상기 제1연결라인으로부터 하방으로 연장된 다수개의 제2연결라인; 및상기 다수 개의 제2연결라인과 연결되고, 양식물이 성장되는 하나 이상의 수하라인이 하방으로 배치되도록 하는 제3연결라인;을 포함하고,상기 양식물의 자중은 상기 제3연결라인, 상기 제2연결라인, 상기 제1연결라인 및 상기 다수 개의 부력체로 순차적으로 전달되는, 수하식 양식 구조물., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

289/1150 Row 289: application_number: 1020190154068, combined_string: invention_title: 해상풍력을 이용한 굴 양식 장치 abstract: 본 발명은 굴 양식 장치에 관한 것으로서, 더욱 상세하게는 해수면에서 풍력을 이용하여 별도의 전기 에너지 없이 굴 양식 케이지를 수면위와 수면아래로 순환시키는 굴 양식 장치에 관한 것이다.본 발명은 해상풍력을 이용한 굴 양식 장치에 있어서, 부력을 가져 해수면에 부유하는 부력체; 상기 부력체의 일측에 형성되어, 해상풍력을 이용하여 동력이 발생하는 동력발생부; 상기 동력발생부 하부에 설치되어, 상기 동력발생부에서 발생한 동력을 웜과 웜기어에 의해 수직방향으로 동력전달부에 전달하는 기어부; 상기 기어부를 감싸면서 상기 기어부를 외부요인으로부터 보호하는 기어박스; 상기 기어박스 일측 또는 양측에 설치되며, 상기 윔기어의 회전축 끝단에 설치된 구동 풀리(Pulley)와 굴 양식부에 연결된 종동 풀리가 타이밍 벨트(Timing belt)에 의해 연결되어, 상기 기어부에서 전달된 동력을 굴 양식부로 전달하는 동력전달부; 상기 동력전달부로부터 전달되는 동력에 의해 굴이 수납되는 굴 양식 케이지를 수면위와 수면아래로 순환시키는 굴 양식부;를 포함하는 해상풍력을 위한 굴 양식 장치를 제공할 수 있다. claims: 해상풍력을 이용한 굴 양식 장치에 있어서, 부력을 가져 해수면에 부유하는 부력체;상기 부력체의 일측에 형성되어, 해상풍력을 이용하여 동력이 발생하는 동력발생부;상기 동력발생부 하부에 설치되어, 상기 동력발생부에서 발생한 동력을 웜과 웜기어에 의해 수직방향으로 동력전달부에 전달하는 기어부;상기 기어부를 감싸면서 상기 기어부를 외부요인으로부터 보호하는 기어박스;상기 기어박스 일측 또는 양측에 설치되며, 상기 윔기어의 회전축 끝단에 설치된 구동 풀리(Pulley)와 굴 양식부에 연결된 종동 풀리가 타이밍 벨트(Timing belt)에 의해 연결되어, 상기 기어부에서 전달된 동력을 굴 양식부로 전달하는 동력전달부;상기 동력전달부로부터 전달되는 동력에 의해 굴이 수납되는 굴 양식 케이지를 수면위와 수면아래로 순환시키는 굴 양식부;를 포함하는 굴 양식 장치., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

290/1150 Row 290: application_number: 1020190152982, combined_string: invention_title: 굴 양식 장치 abstract: 본 발명은 해상에서 수산양식 동물, 특히 조개, 더 구체적으로는 굴을 양육하기 위한 굴 양식 장치에 관한 것으로, 해상의 바닥면에 일정 간격으로 이격되어 복수 개로 배치되는 고정부와, 복수 개의 상기 고정부에 연결되되, 단부에는 부표가 결합되는 연결부와, 상기 연결부에 연결되는 양육망과, 상기 양육망의 하단에 결합되며, 상기 양육망과 상기 연결부가 연결되는 각도를 변경시키는 터빈부 및 상기 양육망과 터빈부 사이에 결합되며, 상기 터빈부와 양육망을 체결시키는 체결부를 포함하는 것을 특징으로 한다. claims: 해상의 바닥면에 일정 간격으로 이격되어 복수 개로 배치되는 고정부;복수 개의 상기 고정부에 연결되되, 단부에는 부표가 결합되는 연결부;상기 연결부에 연결되는 양육망;상기 양육망의 하단에 결합되며, 상기 양육망과 상기 연결부가 연결되는 각도를 변경시키는 터빈부; 및상기 양육망과 터빈부 사이에 결합되며, 상기 터빈부와 양육망을 체결시키는 체결부;를 포함하는 것을 특징으로 하는 굴 양식 장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

291/1150 Row 291: application_number: 1020190153062, combined_string: invention_title: 회전 부력체를 이용한 가두리 양식장 abstract: 회전 부력체를 이용한 가두리 양식장이 개시된다. 개시되는 일 실시예에 따른 가두리 양식장은, 내부에 길이 방향으로 관통부가 마련되는 복수 개의 부력체, 복수 개의 부력체의 상단에 마련되는 고정바, 고정바와 연결되고, 고정바 상에 마련되는 이동 통로, 관통부를 통해 복수 개의 부력체를 연결하는 제1 로프, 및 일단이 제1 로프에 연결되고, 타단이 고정바에 연결되는 제2 로프를 포함한다. claims: 내부에 길이 방향으로 관통부가 마련되는 복수 개의 부력체;상기 복수 개의 부력체의 상단에 마련되는 고정바;상기 고정바와 연결되고, 상기 고정바 상에 마련되는 이동 통로;상기 관통부를 통해 상기 복수 개의 부력체를 연결하는 제1 로프; 및일단이 상기 제1 로프에 연결되고, 타단이 상기 고정바에 연결되는 제2 로프를 포함하고, 상기 부력체는, 내부에 상기 관통부가 길이 방향으로 마련되는 바디; 상기 바디의 외주면에 마련되고 유체의 흐름에 의해 상기 바디가 회전하도록 하는 회전 유도부; 및상기 바디의 내부에서 상기 관통부와 상기 바디를 연결하며 마련되는 복수 개의 지지 리브를 포함하는, 가두리 양식장., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

292/1150 Row 292: application_number: 1020190145410, combined_string: invention_title: 해상풍력발전기를 이용한 가두리 양식장 abstract: 해상풍력발전기를 이용한 가두리 양식장이 제시된다. 본 발명의 실시예에 따른 해상풍력발전기를 이용한 가두리 양식장은, 해상에 수직으로 세워져 하부는 해저면에 고정되고, 상부는 해수면 위로 노출되는 해상기초시설물; 상기 해상기초시설물의 외면에 설치되는 가두리 양식장; 상기 해상기초시설물의 내부에 설치되어 가두리 양식장에 공급될 사료를 저장하는 저장탱크; 상기 저장탱크의 출구로 배출되는 사료를 이송하는 사료 이송장치; 상기 사료 이송장치에 의해 이송된 사료를 해수와 혼합하여 가두리 양식장에 공급하는 사료 공급장치; 상기 해상기초시설물 내부에 설치되어 상기 사료 이송장치와 사료 공급장치의 동작을 제어하는 컨트롤러; 및 상기 가두리 양식장에 설치되어 가두리 양식장 내부를 비추어줌으로써 양식어류가 어망에 충돌하여 폐사되는 것을 방지하는 조명장치;를 포함하는 것을 구성의 요지로 한다.본 발명에 따르면, 기상조건에 관계없이 수중에 위치하는 가두리 양식장에 자동으로 먹이를 공급할 수 있는 구성을 포함하는 해상풍력발전기를 이용한 가두리 양식장을 제공할 수 있다. claims: 해상에 수직으로 세워져 하부는 해저면에 고정되고, 상부는 해수면 위로 노출되는 해상기초시설물;상기 해상기초시설물의 외면에 설치되는 가두리 양식장;상기 해상기초시설물의 내부에 설치되어 가두리 양식장에 공급될 사료를 저장하는 저장탱크;상기 저장탱크의 출구로 배출되는 사료를 이송하는 사료 이송장치;상기 사료 이송장치에 의해 이송된 사료를 해수와 혼합하여 가두리 양식장에 공급하는 사료 공급장치;상기 해상기초시설물 내부에 설치되어 상기 사료 이송장치와 사료 공급장치의 동작을 제어하는 컨트롤러; 및상기 가두리 양식장에 설치되어 가두리 양식장 내부를 비추어줌으로써 양식어류가 어망에 충돌하여 폐사되는 것을 방지하는 조명장치;를 포함하는 것을 특징으로 하는 해상풍력발전기를 이용한 가두리 양식장.해상에 수직으로 세워져 하부는 해저면에 고정되고, 상부는 해수면 위로 노출되는 해상기초시설물;상기 해상기초시설물에서 수십에서 수천미터 떨어진 수중에 설치되는 가두리 양식장;상기 해상기초시설물의 내부에 설치되어 가두리 양식장에 공급될 사료를 저장하는 저장탱크;상기 저장탱크의 출구로 배출되는 사료를 이송하는 사료 이송장치;상기 사료 이송장치에 의해 이송된 사료를 해수와 혼합하여 가두리 양식장에 공급하는 사료 공급장치;상기 해상기초시설물 내부에 설치되어 상기 사료 이송장치와 사료 공급장치의 동작을 제어하는 컨트롤러; 및상기 가두리 양식장에 설치되어 가두리 양식장 내부를 비추어줌으로써 양식어류가 어망에 충돌하여 폐사되는 것을 방지하는 조명장치;를 포함하는 것을 특징으로 하는 해상풍력발전기를 이용한 가두리 양식장., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

293/1150 Row 293: application_number: 1020190143552, combined_string: invention_title: 양식장 순환수 처리장치 abstract: 양식장 순환수 처리장치가 개시된다. 개시되는 양식장 순환수 처리장치는, 양식장에서 배출되는 양식장 배출수를 유입시켜 상기 양식장 배출수 내에 존재하는 인 및 질소를 스트루바이트(struvite) 결정화시켜 배출하고, 스트루바이트 결정화 이후의 처리수를 배출하는, 스트루바이트 결정화부(110), 상기 스트루바이트 결정화부에서 배출되는 상기 스트루바이트 결정화 이후의 처리수를 유입시켜 상기 스트루바이트 결정화 이후의 처리수 내에 포함된 부유물질을 기포를 이용하여 부상 분리시켜 제거하고, 부유물질 제거 이후의 처리수를 배출하는, 부유물질 제거부(120), 및 상기 부유물질 제거부에서 배출되는 상기 부유물질 제거 이후의 처리수를 유입시켜 상기 부유물질 제거 이후의 처리수 내에 포함된 유기물을 제거하고, 유기물 제거 이후의 최종 처리수를 양식장으로 다시 공급하여 순환시키는 생물막 반응부(130)를 포함하여, 영양염류(N, P), 부유물질 및 유기물들을 효율적으로 처리할 수 있다. claims: 양식장 순환수 처리장치로서,양식장에서 배출되는 양식장 배출수를 유입시켜 상기 양식장 배출수 내에 존재하는 인 및 질소를 스트루바이트(struvite) 결정화시켜 배출하고, 스트루바이트 결정화 이후의 처리수를 배출하는, 스트루바이트 결정화부(110);상기 스트루바이트 결정화부에서 배출되는 상기 스트루바이트 결정화 이후의 처리수를 유입시켜 상기 스트루바이트 결정화 이후의 처리수 내에 포함된 부유물질을 기포를 이용하여 부상 분리시켜 제거하고, 부유물질 제거 이후의 처리수를 배출하는, 부유물질 제거부(120); 및상기 부유물질 제거부에서 배출되는 상기 부유물질 제거 이후의 처리수를 유입시켜 상기 부유물질 제거 이후의 처리수 내에 포함된 유기물을 제거하고, 유기물 제거 이후의 최종 처리수를 양식장으로 다시 공급하여 순환시키는 생물막 반응부(130);를 포함하는 것을 특징으로 하는 양식장 순환수 처리장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

294/1150 Row 294: application_number: 1020190143553, combined_string: invention_title: 양식장 순환수의 분산형 처리장치 abstract: 양식장 순환수의 분산형 처리장치가 개시된다. 개시되는 양식장 순환수의 분산형 처리장치는, 양식장 수조(1); 및 상기 양식장 수조에 대응되게 배치되며, 상기 양식장 수조로부터 물을 유입시켜 상기 양식장 수조로부터의 물에 포함된 부유물질을 기포를 이용하여 부상 분리시켜 제거하고, 부유물질 제거 이후의 처리수를 상기 양식장 수조 내로 배출하는, 부유물질 제거부(110)를 포함하여, 각 양식장 수조 내에서 수질을 안정적으로 유지하면서도 바이러스 등으로 인한 질병의 발생시 양식장 수조 전체에 피해를 줄이고, 고농도의 산소를 용해하여 유기물질을 효과적으로 제거할 뿐만 아니라, 처리장 면적이 줄어 공사비용도 줄고 공간활용도를 높일 수 있다. claims: 양식장 순환수의 분산형 처리장치로서,양식장 수조(1); 및상기 양식장 수조에 대응되게 배치되며, 상기 양식장 수조로부터 물을 유입시켜 상기 양식장 수조로부터의 물에 포함된 부유물질을 기포를 이용하여 부상 분리시켜 제거하고, 부유물질 제거 이후의 처리수를 상기 양식장 수조 내로 배출하는, 부유물질 제거부(110)를 포함하는 것을 특징으로 하는, 양식장 순환수의 분산형 처리장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

295/1150 Row 295: application_number: 1020190140933, combined_string: invention_title: 해상지주를 활용한 4차산업혁명 해상주거관광생태통합 사물인터넷, 무인 로봇 양식장 abstract: 일 실시예에 따른 사물인터넷 기반의 무인 로봇 양식장 시스템은, 수면 상에 부유하도록 부력을 가지며, 해수의 유출입으로 부력을 조절하는 사물인터넷 기반의 부유식 구조물을 구성하는 부유 조정식 구조체; 상기 부유 조정식 구조체의 상부에 로봇 작업대가 설치되고, 상기 설치된 로봇 작업대를 이용하여 로봇의 작업이 가능한 이동식 로봇 운행 레일; 및 상기 부유 조정식 구조체의 하부에 설치되며, 상기 부유 조정식 구조물에 구성된 부유식 구조물의 제어를 통하여 해수의 유출입이 조절됨에 따라 승하강되는 양식장을 포함하고, 상기 양식장 시스템은, 통신 칩이 장착됨에 따라 구성된 통신 환경을 통하여 상기 양식장의 생태 환경을 자동으로 계측하고, 상기 양식장 시스템에 구성된 각각의 구성 요소와 데이터를 송수신하며, 상기 송수신된 데이터를 원격의 서버와 통신할 수 있다. claims: 사물인터넷 기반의 무인 로봇 양식장 시스템에 있어서, 수면 상에 부유하도록 부력을 가지며, 해수의 유출입으로 부력을 조절하는 사물인터넷 기반의 부유식 구조물을 구성하는 부유 조정식 구조체; 상기 부유 조정식 구조체의 상부에 로봇 작업대가 설치되고, 상기 설치된 로봇 작업대를 이용하여 로봇의 작업이 가능한 이동식 로봇 운행 레일; 및상기 부유 조정식 구조체의 하부에 설치되며, 상기 부유 조정식 구조체에 구성된 부유식 구조물의 제어를 통하여 해수의 유출입이 조절됨에 따라 승강되는 양식장 을 포함하고, 상기 양식장 시스템은, 통신 칩이 장착됨에 따라 구성된 통신 환경을 통하여 상기 양식장의 생태 환경을 자동으로 계측하고, 상기 양식장 시스템에 구성된 각각의 구성 요소와 데이터를 송수신하며, 상기 송수신된 데이터를 원격의 서버와 통신하는 사물인터넷 기반의 무인 로봇 양식장 시스템., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

296/1150 Row 296: application_number: 1020190134984, combined_string: invention_title: 양식장 고수온 및 적조 방재 시스템 abstract: 본 발명은 수조로 전달되는 물의 온도와 수질을 조절하여 외부 수질 변화에 능동적으로 대처하여 어류를 양식할 수 있는 최적의 조건을 제공할 수 있는 양식장 고수온 및 적조 방재 시스템을 제공하는데 그 목적이 있다.상기한 목적을 이루기 위해 본 발명의 양식장 고수온 및 적조 방재 시스템은 양식장의 물을 관리하는 시스템에 있어서, 어류 및 물이 수용되는 수조, 외부의 물을 전달받아, 상기 수조에 물을 공급하고, 기포를 발생시키는 탱크 기포발생장치가 형성된 물 공급부, 상기 물 공급부의 물을 상기 수조로 전달하는 물 공급관에 형성되어, 상기 물 공급관의 물을 냉각시키는 냉각부, 냉각된 공기를 생성하고, 상기 물 공급부와 연결된 공기 공급관을 통해, 상기 탱크 기포발생장치에 냉각된 공기를 공급하는 공기 공급부 및 상기 수조, 상기 탱크 기포발생장치, 상기 물 공급부, 상기 물 공급관, 상기 냉각부, 상기 공기 공급관 및 상기 공기 공급부의 작동을 제어하고, 외부와 통신이 가능한 제어부를 포함하여 이루어지는 것을 특징으로 한다. claims: 양식장의 물을 관리하는 시스템에 있어서,어류 및 물이 수용되는 수조;외부의 물을 전달받아, 상기 수조에 물을 공급하고, 기포를 발생시키는 탱크 기포발생장치가 형성된 물 공급부;상기 물 공급부의 물을 상기 수조로 전달하는 물 공급관에 형성되어, 상기 물 공급관의 물을 냉각시키는 냉각부;냉각된 공기를 생성하고, 상기 물 공급부와 연결된 공기 공급관을 통해, 상기 탱크 기포발생장치에 냉각된 공기를 공급하는 공기 공급부; 및상기 수조, 상기 탱크 기포발생장치, 상기 물 공급부, 상기 물 공급관, 상기 냉각부, 상기 공기 공급관 및 상기 공기 공급부의 작동을 제어하고, 외부와 통신이 가능한 제어부;를 포함하여 이루어지는 것을 특징으로 하는 양식장 고수온 및 적조 방재 시스템., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

297/1150 Row 297: application_number: 1020190134489, combined_string: invention_title: 양식장용 스크류식 사료공급유닛 abstract: 본 발명은 사료저장통으로부터 투입호퍼를 거쳐 스크류피더의 내부로 투입된 사료를 스크류피더의 이송스크류를 이용하여 스크류케이싱을 따라 양식수조로 공급시키도록 한 양식장용 스크류식 사료공급유닛에 관한 것으로서, 더욱 상세하게는 투입호퍼의 직전방에 해당하는 스크류케이싱의 내주면 상측부에 소정의 길이만큼 하방으로 돌출되는 차단판을 설치하거나, 투입호퍼의 전방측에서 스크류케이싱을 따라 위치하는 전방측 이송스크류의 스크류 피치를 투입호퍼의 하부측에 위치하는 후방측 이송스크류의 스크류 피치보다 크게 되도록 하거나, 상기 전방측 이송스크류의 피치가 스크류케이싱의 길이 방향을 따라 점차 증대되도록 하거나, 투입호퍼의 직전방에 해당하는 부분을 제외한 나머지 스크류케이싱 부분의 내경이 이송스크류의 스크류날개 직경보다 크게 되도록 함으로서, 이송스크류의 축회전에 의하여 사료저장통의 투입호퍼로부터 스크류케이싱을 거쳐 공급되는 사료가 이송스크류와 스크류케이싱의 사이에서 과도하게 압착되지 않고 이송스크류에 의하여 부드럽게 밀려 나갈 수 있도록 하며, 이를 통하여 이송스크류의 과도한 압착력으로 사료의 입자가 뭉개짐에 따라 사료의 기능을 제대로 수행하지 못하는 현상과, 사료의 압착에 따른 스크류모터의 과부하 및 스크류피더의 고장이나 오작동을 미연에 방지할 수 있도록 한 양식장용 스크류식 사료공급유닛에 관한 것이다. claims: 하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(3)를 포함하여서 이루어지며, 상기 스크류피더(3)는 선단부가 개구된 원통 파이프 형상의 스크류케이싱(4)과, 상기 스크류케이싱(4)의 내부에 삽입 설치되어 스크류모터(7)의 동력으로 축회전하는 이송스크류(5)를 포함하여서 이루어지는 양식장용 스크류식 사료공급유닛(10)에 있어서,상기 투입호퍼(2)의 직전방에 해당하는 스크류케이싱(4)의 내주면 상측부에는 사료(8)의 이송량을 제한하는 차단판(9)이 하측 방향으로 돌출 형성되고, 상기 차단판(9)은 스크류케이싱(4) 직경의 1/15 내지 2/5에 해당하는 길이로 돌출 형성되며,상기 이송스크류(5)의 축회전시 차단판(9)이 걸리게 되는 스크류 부분은 일정 피치 만큼이 잘려 나간 형태를 이루거나, 해당 스크류 부분에 차단판(9)의 통과홈이 절개 형성되는 것을 특징으로 하는 양식장용 스크류식 사료공급유닛.하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(3)를 포함하여서 이루어지며, 상기 스크류피더(3)는 선단부가 개구된 원통 파이프 형상의 스크류케이싱(4)과, 상기 스크류케이싱(4)의 내부에 삽입 설치되어 스크류모터(7)의 동력으로 축회전하는 이송스크류(5)를 포함하여서 이루어지는 양식장용 스크류식 사료공급유닛(10)에 있어서,상기 이송스크류(5)는 투입호퍼(2)의 출구 하측에 위치하는 스크류의 피치를 기준으로 하여 투입호퍼(2)의 전방측에 위치하는 나머지 스크류의 피치가 10~50%의 비율로 크게 형성된 것임을 특징으로 하는 양식장용 스크류식 사료공급유닛.하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(3)를 포함하여서 이루어지며, 상기 스크류피더(3)는 선단부가 개구된 원통 파이프 형상의 스크류케이싱(4)과, 상기 스크류케이싱(4)의 내부에 삽입 설치되어 스크류모터(7)의 동력으로 축회전하는 이송스크류(5)를 포함하여서 이루어지는 양식장용 스크류식 사료공급유닛(10)에 있어서,상기 이송스크류(5)는 투입호퍼(2)의 출구 하측에 위치하는 스크류의 피치를 기준으로 하여 투입호퍼(2)의 전방측에 위치하는 나머지 스크류의 피치가 스크류케이싱(4)의 길이 방향을 따라가면서 5~20%의 비율로 점차 크게 형성된 것임을 특징으로 하는 양식장용 스크류식 사료공급유닛.하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(3)를 포함하여서 이루어지며, 상기 스크류피더(3)는 선단부가 개구된 파이프 형상의 스크류케이싱(4)과, 상기 스크류케이싱(4)의 내부에 삽입 설치되어 스크류모터(7)의 동력으로 축회전하는 이송스크류(5)를 포함하여서 이루어지는 양식장용 스크류식 사료공급유닛(10)에 있어서,상기 투입호퍼(2)의 직전방에 해당하는 스크류케이싱(4) 부분은 이송스크류(5)의 스크류날개 가장자리와 밀착되는 압출케이싱(4a)이 되고, 상기 압출케이싱(4a) 부분을 제외한 나머지 스크류케이싱(4) 부분은 이송스크류(5)의 스크류날개 직경보다 소정의 길이(d)만큼 큰 내경을 가지는 확장케이싱(4b)으로 형성되는 것을 특징으로 하는 양식장용 스크류식 사료공급유닛., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

298/1150 Row 298: application_number: 1020190134492, combined_string: invention_title: 양식장용 스크류식 사료공급장치 abstract: 본 발명은 사료저장통으로부터 그 하단측의 투입호퍼를 거쳐 스크류피더의 내부로 투입된 사료를 스크류모터의 동력으로 축회전하는 스크류피더의 이송스크류를 이용하여 스크류케이싱을 따라 양식수조로 공급시키도록 하되, 상기 사료저장통의 하부에는 사료저장통을 지지하는 받침통이 설치되고, 상기 스크류케이싱은 받침통의 벽체를 관통하여 소정의 길이만큼 전방측으로 연장 형성된 양식장용 스크류식 사료공급장치에 관한 것으로서, 더욱 상세하게는 상기 스크류케이싱을 받침통의 내부에 배치되는 후방케이싱과 받침통의 전방면에 착탈 가능하게 조립 설치되는 전방케이싱으로 분할 형성시키고, 상기 이송스크류의 스크류축은 스크류모터의 구동축과 나사체결식으로 착탈 가능하게 조립 설치함으로서, 스크류피더의 청소나 수리 및 유지보수 작업을 매우 손쉽고 간단하게 수행할 수 있도록 하며, 상기 투입호퍼의 직전방에 해당하는 스크류케이싱의 내주면 상측부에 사료의 이송량을 제한하는 차단판을 돌출 형성시킴으로서, 스크류케이싱을 거쳐 공급되는 사료가 이송스크류와 스크류케이싱의 사이에서 과도하게 압착되지 않고 이송스크류에 의하여 부드럽게 밀려 나갈 수 있도록 하며, 스크류케이싱의 선단 배출구에 설치되는 사료살포기의 비산플랩을  ） 형태의 곡면판으로 하여 사료의 확산범위를 보다 더 폭넓게 확보할 수 있도록 한 양식장용 스크류식 사료공급장치에 관한 것이다. claims: 하측부에 깔때기형 투입호퍼(2)가 제공된 사료저장통(1)과, 상기 투입호퍼(2)와 연결 설치되어 사료저장통(1)을 하부에서 지지하는 받침통(6)과, 상기 투입호퍼(2)의 하단 출구측에 연결 설치된 상태로 받침통(6)의 벽체 부분을 관통하여 소정의 길이만큼 전방측으로 연장 형성되는 스크류피더(7)를 포함하여서 이루어지며, 상기 스크류피더(7)는 투입호퍼(2)의 하단 출구측으로부터 받침통(6)의 벽체 부분을 관통하여 연장되는 원통 파이프 형상의 스크류케이싱(11)과, 상기 스크류케이싱(11)의 내부에 삽입 설치되어 스크류모터(30)의 동력으로 축회전하는 이송스크류(12)를 포함하여서 이루어지고, 상기 스크류케이싱(11)의 선단측에는 사료의 배출구(11a)가 제공된 양식장용 스크류식 사료공급장치(10)에 있어서,상기 스크류케이싱(11)은 투입호퍼(2)의 하단 출구로부터 받침통(6)의 벽체측에 이르기까지의 길이를 가지는 후방케이싱(22)과, 상기 후방케이싱(22)의 선단측으로부터 받침통(6)의 외부로 연장되는 전방케이싱(21)으로 분할 형성되고, 상기 전방케이싱(21)은 케이싱조립부(17)를 개재시킨 상태로 받침통(6)과 탈,부착 가능하게 연결 설치되며,상기 케이싱조립부(17)는 전방케이싱(21)의 후단부측 외주면상에서 전방케이싱(21)과 일체로 연결 설치되는 장착플랜지(24)와, 상기 받침통(6)의 외측면상에 조립 설치된 상태로 전방케이싱(21)의 장착플랜지(24)와 맞대어지는 받침플랜지(25)와, 상기 장착플랜지(24)와 받침플랜지(25)의 외주면을 따라 회전 가능하게 설치되는 원통형 결착노브(7a)를 포함하여서 이루어지고,상기 장착플랜지(24)의 후단부측 외주면에는 일정한 각도범위를 두고 쐐기프레임(24a)이 돌출 형성되며, 상기 받침플랜지(25)의 선단부측 외주면에는 일정한 각도범위를 두고 결착노브(7a)용 가이드프레임(25a)이 돌출 형성되고, 상기 결착노브(7a)의 선단부측 내주면에는 장착플랜지(24)의 쐐기프레임(24a)이 제공하는 쐐기홈(24b)을 따라 돌려 끼워지는 결착프레임(7b)이 돌출 형성되며,상기 이송스크류(12)의 스크류축(13) 후단부는 스크류모터(30)의 동력으로 축회전하는 구동축(28)과 나사체결식으로 조립 설치되고, 상기 이송스크류(12)의 조립 방향은 구동축(28)의 회전이 정 방향과 반대 방향이 되는 것을 특징으로 하는 양식장용 스크류식 사료공급장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

299/1150 Row 299: application_number: 1020190131088, combined_string: invention_title: 육상 양식장용 청소장치 abstract: 본 발명은 육상 양식장용 청소장치를 제공한다. 이와 같은 본 발명에 따른 육상 양식장용 청소장치는 육상 양식장의 수조 내 어패류와 물을 이동시키거나 드레인(drain)하지 않고 그대로 둔 상태에서 수조의 바닥이나 측벽에 위치한 이물질/오물질의 제거와 오수(汚水)의 배출이 진행될 수 있는 장치구성을 제공함으로써 육상 양식장의 운용 효율 증대와 수조 청소작업의 편의성과 능률 증대가 도모될 수 있고, 작업자가 간편하게 수동 조작하면서 이동시킬 수 있는 단순화되고 컴팩트화된 구성을 제공함으로써 수조 청소를 위한 비용이 절감되는 한편 필요에 따라 수시로 수조를 청소할 수 있는 기술적 특징을 갖는다. claims: 전복, 넙치 등을 포함하는 어패류를 기르는 육상 양식장을 구성하는 하나 이상의 수조(2)를 청소하기 위한 육상 양식장용 청소장치에 있어서,상기 수조(2)의 물 내부에 배치되며, 저면이 개방된 캡 형상으로 이루어져 물 유입공간(110)을 형성하게 되고, 경사지게 배치되는 설정길이의 핸들(120)이 상향 돌출되게 형성되는 회전체 케이싱(100);상기 회전체 케이싱(100)의 물 유입공간(110)에 설정패턴으로 배치되어 고정되고, 수조(2)의 바닥면(3)을 따라 이동하면서 상기 바닥면(3)에 부착된 이물질을 제거하게 되는 복수의 회전 스위퍼 유닛(200);상기 회전체 케이싱(100)을 통과하여 상기 회전 스위퍼 유닛(200)과 연결되고, 상기 회전 스위퍼 유닛(200)의 회전을 유도하게 되는 회전 스위퍼용 액추에이터(600);상기 물 유입공간(110)과 연통되게 상기 회전체 케이싱(100)과 연결되는 배출관체(700);상기 수조(2) 외부에 배치되며, 상기 배출관체(700)가 연결되는 진공탱크(800);상기 진공탱크(800)와 연결되고, 진공탱크(800)의 내부공간(810)을 진공압으로 만들어 상기 수조(2)의 물이 상기 회전체 케이싱(100)의 물 유입공간(110)과 배출관체(700)를 거쳐 진공탱크(800)로 유입되도록 하는 진공펌프(900); 및상기 회전 스위퍼용 액추에이터(600)와 진공펌프(900)의 동작을 제어하는 컨트롤러(1300);를 포함하는 구성으로 이루어져,상기 진공펌프(900)의 구동에 따라 상기 회전체 케이싱(100)의 물 유입공간(110), 배출관체(700), 진공탱크(800), 진공펌프(900)를 상기 수조(2)의 물이 통과하여 외부로 배출되는 한편, 상기 회전 스위퍼용 액추에이터(600)에 의해 상기 회전 스위퍼 유닛(200)의 회전이 유도되는 과정에서 상기 수조(2)의 청소가 수행되도록 하는 것을 특징으로 하는 육상 양식장용 청소장치.전복, 넙치 등을 포함하는 어패류를 기르는 육상 양식장을 구성하는 하나 이상의 수조(2)를 청소하기 위한 육상 양식장용 청소장치에 있어서,회전가능하게 수평 배치되는 판체 형상으로 이루어지고, 수조(2)의 바닥면(3)을 따라 이동하면서 상기 바닥면(3)에 부착된 이물질을 제거하게 되는 회전 스위퍼(300);상기 회전 스위퍼(300)의 상부면 중앙에 연결되어 상향 연장 형성되는 회전축(400);상기 회전축(400)과 일체로 결합되고, 상기 회전축(400)과 동일한 축선을 가지면서 상기 회전축(400)의 반경방향으로 돌출형성되며, 상기 수조(2)의 물이 통과하면서 회전하게 되는 수차용 임펠러(1100);저면이 개방된 캡 형상으로 이루어져 물 유입공간(110)을 형성하게 되며, 상기 물 유입공간(110) 내에 배치되는 상기 회전 스위퍼(300)의 측방 부위와 상단 부위를 감싸게 되는 회전스위퍼 커버(100');상기 회전스위퍼 커버(100')의 상부면 중앙으로부터 상향 연장 형성되고, 상기 물 유입공간(110)과 연통되는 이동채널(1210)이 상하 관통형성되며, 상기 이동채널(1210)에 상기 회전축(400)과 수차용 임펠러(1100)가 배치되되, 상기 회전축(400)을 베어링(410)을 매개로 고정시키게 되는 핸들 겸용 연결대(1200);상기 핸들 겸용 연결대(1200)의 이동채널(1210) 상단과 연통되고, 상기 이동채널(1210)에 진공압을 부여하게 되는 진공펌프(900); 및상기 진공펌프(900)의 동작을 제어하는 컨트롤러(1300);를 포함하는 구성으로 이루어져,상기 진공펌프(900)의 구동에 따라, 상기 회전스위퍼 커버(100')의 물 유입공간(110), 핸들 겸용 연결대(1200)의 이동채널(1210), 진공펌프(900)를 상기 수조(2)의 물이 통과하여 외부로 배출되는 한편, 상기 핸들 겸용 연결대(1200)의 이동채널(1210)을 통과하는 물에 의해 상기 수차용 임펠러(1100)가 회전하여 상기 회전 스위퍼(300)의 회전이 유도되는 과정에서 상기 수조(2)의 청소가 수행되도록 하는 것을 특징으로 하는 육상 양식장용 청소장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

300/1150 Row 300: application_number: 1020190117264, combined_string: invention_title: 가리비 양식 방법 abstract: 본 발명은 가리비 양식 방법에 관한 것으로서, 고무판이 다수 개 구비된 채롱에 가리비 치패를 상기 고무판에 부착시켜 해수에서 수하식으로 소정 기간 양식할 때에, 상기 고무판은 구멍이 형성되어 있고, 에틸렌 아크릴 고무, 게르마늄 및 아민계 가류제를 포함한 고무 조성물로 이루어진 것을 특징으로 한다. 본 발명에 따르면, 채롱의 고무판에서 게르마늄이 높은 함량으로 존재하므로 가리비가 안칙된 고무판에서 게르마늄에 의해 산소의 발생량이 증가하므로 치패가 산소의 결핍에 의해 폐사하는 비율이 저감된다. 또한, 고무판이 향상된 내염수성과 내수성을 가지므로 다년간 채롱을 해수에서 사용하더라도 세척할 때에 변형과 깨짐이 발생하지 않아 채롱의 내구성이 향상된다. claims: 고무판이 다수 개 구비된 채롱에 가리비 치패를 상기 고무판에 부착시켜 해수에서 수하식으로 소정 기간 양식하는 가리비 양식방법에 있어, 상기 고무판은 구멍이 형성되어 있고, 에틸렌 아크릴 고무 100 중량부 대비 10 ~ 500 ㎛의 분말의 게르마늄 30 ~ 100 중량부, 아민계 가류제 및 이소티오시아네이트류를 포함하고, 상기 아민계 가류제는 헥사메틸렌디아민카바메이트 또는 N, N´-디신나밀리덴-1,6-헥산 디아민이고, 상기 이소티오시아네이트류는 2,4-디클로로페닐이소티오시아네이트 또는 3,4-디클로로페닐이소티오시아네이트인, 고무 조성물로 제조된 것을 특징으로 하는 가리비 양식 방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

301/1150 Row 301: application_number: 1020190115420, combined_string: invention_title: 해삼 양식장치 abstract: 양식장에 설치되어 해삼이 표면에 부착하여 생육할 수 있는 파판이 바닥과 수직하게 설치될 수 있도록 고정하는 상부 파판 홀더부; 상기 상부 파판 홀더부 하부에는 바닥과 수평하게 하나 이상의 파판이 수납될 수 있는 수용부가 마련되는 하부 파판 홀더부가 형성되며; 상기 하부 파판 홀더부 하부 모서리에는 받침대가 설치되는 해삼 양식장치를 제공함으로써 수직 설치된 파판에 부착된 양식 해삼은 중력의 영향으로 일정한 부착력을 유지하지 않아도 되고, 부착력이 약해지면 탈락하여 양식 해삼이 하부 파판에 다수가 서식하게 됨으로 성장 불균형을 방지할 수 있을 뿐만 아니라 상부 파판의 먹이 안착률이 우수하여 해삼 성장량 증가 및 먹이효율을 증가시킬 수 있는 효과가 있다. claims: 해삼이 부착하여 성장하는 복수개의 파판이 바닥면과 수직하게 형성될 수 있도록 하는 상부 파판 홀더부의 하부에 양식장 바닥면과 수평하게 하나 이상의 파판이 수납될 수 있도록 한 수용부를 갖는 하부 파판 홀더부가 상기 상부 파판홀더부와 일체로 결합되어 이루어지며;상기 상부 파판 홀더부는 가로 및 세로 부재가 연결되어 상부가 개구된 사각틀 형상의 상부면과 상부면을 이루는 가로 및 세로 부재와 연결되는 일정 길이의 수직부재가 하부 파판 홀더부와 일체로 결합되어 상광 하협의 내부 공간부를 갖는 구조를 이루며,상기 상부 파판 홀더부의 좌측 및 우측면의 수직부재는 서로 마주하는 방향을 향해 65 내지 75도 사이각으로 경사를 이루며 상광하협의 하향 수렴 구조를 갖고 하부 파판 홀더부의 상부 내측면에 일체로 결합되며, 상기 하부 파판 홀더부는 수직부재와 수평부재의 결합으로 직육면체 형상을 이루고, 전면 또는 후면에는 파판이 바닥면과 수평으로 수납될 수 있도록 파판 수용부가 형성되며, 상기 하부 파판 홀더부 하부 모서리에는 받침대가 형성되어 이루어지는 것을 특징으로 하는 해삼 양식장치, Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

302/1150 Row 302: application_number: 1020190115427, combined_string: invention_title: 효율적인 공간 활용을 위한 양식장용 다층 수조 시스템 abstract: 본 발명은 양식장용 다층 수조 시스템에 관한 것으로, 넙치, 가자미 등의 편평어를 양식하는 양식장에서 공간을 효율적으로 활용하면서 물고기의 관리와 반입 및 반출이 편리하도록 한 것이다. 이러한 본 발명은, 상하로 이격을 두고 다층 설치된 다수의 베이스 패널을 구비한 본체 프레임; 각 층에 위치한 베이스 패널의 상측에서 전후방향으로 슬라이딩 가능하도록 설치되며 상면이 개방된 사각의 용기 형태로 형성되어 해수를 담을 수 있도록 한 다수의 서랍형 수조; 및 상기 본체 프레임에 설치되어 각 층에 위치한 상기 수조에 해수를 공급할 수 있도록 한 다수의 공급관;을 포함하는 것을 특징으로 한다. claims: 상하로 이격을 두고 다층 설치된 다수의 베이스 패널을 구비한 본체 프레임; 각 층에 위치한 베이스 패널의 상측에서 전후방향으로 슬라이딩 가능하도록 설치되며 상면이 개방된 사각의 용기 형태로 형성되어 해수를 담을 수 있도록 한 다수의 서랍형 수조; 및 상기 본체 프레임에 설치되어 각 층에 위치한 상기 수조에 해수를 공급할 수 있도록 한 다수의 공급관;을 포함하며, 상기 수조의 전면 벽에는 물고기의 반출을 위한 개구부가 형성되고, 상기 개구부를 개폐 가능한 차단판이 더 설치되며, 상기 차단판은 상기 본체 프레임의 탑 플레이트에 설치된 제1전동윈치에 제1와이어로 연결되어 상기 제1전동윈치가 제1와이어를 감아주면 상기 차단판이 상승하면서 상기 수조의 개구부를 개방하고 상기 제1전동윈치가 제1와이어를 풀어주면 상기 차단판이 하강하면서 상기 수조의 개구부를 폐쇄하도록 한 것을 특징으로 하는 양식장용 다층 수조 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

303/1150 Row 303: application_number: 1020190112359, combined_string: invention_title: 수산물 양식 및 태양광 발전 복합단지 abstract: 본 발명은 수산물 양식 및 태양광 발전 복합단지에 관한 것으로서, 수산물 양식을 위한 해수가 수용된 양식장(10)(10')(10)과; 양식장(10)(10')(10)의 전후방에서 작업자가 양식중인 수산물을 수확하기 위한 작업공간을 제공하는 작업존(20)(20')(20)과; 양식장(10)(10')(10)의 상부측을 덮도록 설치되는 것으로서 태양광을 통하여 상기 양식장(10)(10')(10)을 운영하기 위한 전력을 생산하는 복수의 태양광어레이(30)(30')(30);를 포함한다. claims: 수산물 양식을 위한 해수가 수용된 양식장(10)(10')(10);상기 양식장(10)(10')(10)의 전후방에서 작업자가 양식중인 수산물을 수확하기 위한 작업공간을 제공하는 작업존(20)(20')(20); 상기 양식장(10)(10')(10)의 상부측을 덮도록 설치되는 것으로서 태양광을 통하여 상기 양식장(10)(10')(10)을 운영하기 위한 전력을 생산하는 복수의 태양광어레이(30)(30')(30);상기 태양광어레이(30)(30')(30)를 구성하는 태양광모듈에서 출력되는 직류전력을 병합하여 출력하는 다수의 단위접속반(70)(70')(70);상기 단위접속반(70)(70')(70)에서 출력되는 직류전력을 교류전력으로 변환하는 다수의 단위인버터(80)(80')(80); 및 상기 다수의 단위인버터(80)(80')(80)에서 출력되는 전력중, 상기 양식장(10)(10')(10)을 운영하는 과정에서 남은 잉여전력을 한전과 연계된 계통으로 공급하는 계통제어반(90);을 포함하고;상기 계통제어반(90)은, 전방측에 점검을 위한 도어(91a) 및 전장품(P)을 지지하는 다수의 선반(91b)을 가지는 함체(91)와; 상기 함체(91)의 마주보는 4 개의 모서리측에 설치되어 그 함체(91)를 수직 방향으로 지지하는 것으로서, 각각의 내부에 유로(92a)가 형성되고, 마주보는 면에 그 유로(92a)와 연통되는 다수의 통기구멍(92b)이 형성된 프로파일(92)과; 상기 함체(91)의 내부 상부측에 4 개의 프로파일(92)에 지지되는 것으로서 상기 유로(92a)와 연통되게 설치되는 흡배기공간(98)과; 상기 함체(91) 외부에 설치되어 상기 흡배기공간(98)을 흡입압을 형성하는 흡배기팬(99)과; 상기 단위접속반(70)(70')(70)에서 비정상적인 상황이 발생할 때 접속반이상신호(S1)를 발생하는 접속반이상신호발생부(93)와; 상기 단위인버터(80)(80')(80)에서 비정상적인 상황이 발생할 때 인버터이상신호(S2)를 발생하는 인버터이상신호발생부(94)와; 상기 프로파일(92)에 설치되는 것으로서, 상기 전장품(P), 접속반이상신호발생부(93), 인버터이상신호발생부(94)에서 발생되는 아크를 감지하여 아크경고신호(AS)를 발생하는 아크감지부(96);을 포함하고; 상기 프로파일(92)은, 단면이 직각 삼각형을 이루는 것으로서 내부에 상기 유로(92a) 및 상기 통기구멍(92b)이 형성되는 경사면을 가지는 프로파일몸체(92c)와; 상기 경사면에 형성되는 것으로서 상기 아크감지부(96)가 끼어지는 끼움슬릿(92d)과; 상기 경사면의 배면에 형성된 것으로서 끼움슬릿(92d)을 상기 유로(92a) 및 통기공(92b)과 차단하는 슬릿배면(92e)을 포함하고;상기 아크감지부(96)는, 상기 끼움슬릿(92d) 및 슬릿배면(92e) 사이에 끼어지는 기판(96a)과, 상기 기판(96a)에 설치되는 자외선센서(96b)와, 아크발생시 발생되는 특정 자외선 파장 영역을 상기 자외선센서(96b)로 투과시키는 투과필터(96c)와, 상기 자외선센서(96b)에서 감지된 자외선 광량이 설정된 광량값 이상이 될 때 아크경고신호(AS)를 발생하는 아크경고신호발생부(96d)를 포함하는 것을 특징으로 하는 수산물 양식 및 태양광 발전 복합단지., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

304/1150 Row 304: application_number: 1020190111376, combined_string: invention_title: 전복양식장치 abstract: 본 발명은 전복양육장치에 관한 것으로, 부구(11)들에 의해 해상에 떠 있는 작업대(1), 상기 작업대(1)의 저면측에 거치되어 수중에 잠겨 유지되는 전복 쉘터(2), 상기 쉘터(2)로 유입된 뻘이 해수 흐름에 의해 제거되도록 작업대(1)의 양측에서 각각 해저에 고정된 닻(31)에 연결된 로프(32)들을 선택적으로 견인하고 풀어주어 작업대의 좌우측을 쉘터(2)들과 함께 상하좌우로 요동치게 하는 요동장치를 포함하여 구성됨으로써, 작업대를 요동장치에 의해 상하좌우로 요동시킴으로써 그 하측에 설치되어 요동되는 쉘터들에서 종패와 전복 먹이에 유입된 뻘과 슬러리를 제거하고 새로운 해수가 유입되므로, 전복이 폐사되지 않고 건강하게 양식할 수 있게 되어 생산성이 증대되는 효과가 있으며, 상기 요동장치는 기존의 양식장치에도 간편하게 설치할 수 있으며, 단순화된 구조로 설치비용을 절감할 수 있는 효과가 있다 claims: 부구(11)들에 의해 해상에 떠 있는 작업대(1), 상기 작업대(1)의 저면측에 거치되어 수중에 잠겨 유지되는 전복 쉘터(2),상기 쉘터(2)로 유입된 뻘이 해수 흐름에 의해 제거되도록 작업대(1)의 양측에서 각각 해저에 고정된 닻(31)에 연결된 로프(32)들을 선택적으로 견인하고 풀어주어 작업대의 좌우측을 쉘터(2)들과 함께 상하좌우로 요동치게 하는 요동장치를 포함하는 전복양육장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

305/1150 Row 305: application_number: 1020190106424, combined_string: invention_title: 양식장용 산소공급장치 abstract: 본 발명에 의하면, 양식장의 수면에 부력을 이용하여 부상하는 부력부; 부력부의 양측부에 회전 가능하게 구성되어 부력부가 양식장을 이동하도록 하고 양식장 상층 수위의 물을 퍼올려 물이 포말로 부서진 후 낙하되도록 하여 상층 수위에 산소가 공급되도록 하는 제1산소공급부; 및 부력부의 하측에 벤츄리 구조를 제공하고 양식장의 물이 양식장 하층 수위에 펌핑시 대기 중의 공기가 분사되도록 하여 하층 수위에 산소가 공급되도록 하는 제2산소공급부를 포함하는 양식장용 산소공급장치가 제공된다. claims: 양식장의 수면에 부력을 이용하여 부상하는 부력부(110);부력부(110)의 양측부에 회전 가능하게 구성되어 부력부(110)가 양식장을 이동하도록 하고 양식장 상층 수위의 물을 퍼올려 물이 포말로 부서진 후 낙하되도록 하여 상층 수위에 산소가 공급되도록 하는 제1산소공급부(120); 및부력부(110)의 하측에 벤츄리 구조를 제공하고 양식장의 물이 양식장 하층 수위에 펌핑시 대기 중의 공기가 분사되도록 하여 하층 수위에 산소가 공급되도록 하는 제2산소공급부(130)를 포함하는 것을 특징으로 하는 양식장용 산소공급장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

306/1150 Row 306: application_number: 1020190106425, combined_string: invention_title: 공기가열부를 가지는 양식장용 산소공급장치 abstract: 본 발명에 의하면, 양식장의 수면에 부력을 이용하여 부상하는 부력부; 부력부의 양측부에 회전 가능하게 구성되어 부력부가 양식장을 이동하도록 하고 양식장 상층 수위의 물을 퍼올려 물이 포말로 부서진 후 낙하되도록 하여 상층 수위에 산소가 공급되도록 하는 제1산소공급부; 부력부의 하측에 벤츄리 구조를 제공하고 양식장의 물이 양식장 하층 수위에 펌핑시 대기 중의 공기가 분사되도록 하여 하층 수위에 산소가 공급되도록 하는 제2산소공급부; 및 부력부에 소정의 공간을 제공하고 상기 공간의 공기가 가열되도록 한 후 제2산소공급부를 통해 양식장 하층 수위에 가열 공가기 공급되도록 하여 대류를 통한 수온 상승을 가능하게 하는 공기가열부를 포함하는 양식장용 산소공급장치가 제공된다. claims: 양식장의 수면에 부력을 이용하여 부상하는 부력부(110);부력부(110)의 양측부에 회전 가능하게 구성되어 부력부(110)가 양식장을 이동하도록 하고 양식장 상층 수위의 물을 퍼올려 물이 포말로 부서진 후 낙하되도록 하여 상층 수위에 산소가 공급되도록 하는 제1산소공급부(120);부력부(110)의 하측에 벤츄리 구조를 제공하고 양식장의 물이 양식장 하층 수위에 펌핑시 대기 중의 공기가 분사되도록 하여 하층 수위에 산소가 공급되도록 하는 제2산소공급부(130); 및 부력부(110)에 소정의 공간을 제공하고 상기 공간의 공기가 가열되도록 한 후 제2산소공급부(130)를 통해 양식장 하층 수위에 가열 공가기 공급되도록 하여 대류를 통한 수온 상승을 가능하게 하는 공기가열부(140)를 포함하는 것을 특징으로 하는 양식장용 산소공급장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

307/1150 Row 307: application_number: 1020190104343, combined_string: invention_title: 양식장용 부구 abstract: 본 발명은 양식장용 부구에 관한 것으로서, 더욱 상세하게는 굴이나 따개비 등의 해양생물이 부구 표면에 부착되는 것을 방지함으로써 해양생물에 의해 부구가 손상되거나 양식망이 손상되는 것을 예방할 수 있는 양식장용 부구에 관한 것이다.본 발명에 따른 양식장용 부구는 파도나 해류에 의해 양식장용 부구가 자동으로 회전되므로 수중에 일정 시간 침지되어 있던 부구의 표면을 공기중 및 태양광에 노출시킬 수 있어 부구 표면에 녹조류 및 해조류, 굴이나 따개비 등과 같은 해양 부착생물이 부착 및 서식하는 것을 사전에 예방 및 차단할 수 있고, 해양 부착 생물이 부착될 시 이를 쉽게 제거할 수 있는 장점이 있다.또한, 본 발명에 따른 양식장용 부구는 그 표면에 굴이나 따개비가 부착되는 것을 미연에 차단함으로써 부구의 내구성을 높여 사용 기간을 늘리고, 양식망이 손상되는 것을 예방할 수 있는 장점이 있다. claims: 부력을 갖고, 원통형으로 형성되며, 부구 고정용 브라켓에 길이방향 양측이 회전 가능하게 설치되는 부구본체와;상기 부구본체의 길이방향 양측에 구비되고, 파도에 의해 상기 부구본체에 돌림힘을 발생시키는 회전유도부;를 구비하고,상기 회전유도부는 상기 부구본체의 길이방향 양측 전면 및 후면으로부터 각각 돌출되고, 상기 부구본체의 전면 및 후면 중심 측에서 상기 부구본체의 전면 및 후면 가장자리 측으로 각각 연장되며, 상기 부구본체의 원주방향을 따라 일정 간격 이격되게 배치되는 복수의 간섭날개를 포함하는 것을 특징으로 하는 양식장용 부구.상판을 설치할 수 있도록 형성된 상판부와, 상기 상판부의 길이방향 양측 단부로부터 하방으로 각각 연장되고 내부에는 수평방향으로 중공부가 형성된 회전지지부를 포함하는 부구 고정용 브라켓과;부력을 갖고 원통형으로 형성되며 길이방향 양측 단부가 각각 상기 회전지지부의 중공부에 삽입된 상태로 상기 회전지지부에 회전 가능하게 설치되는 부구본체와, 상기 부구본체의 길이방향 양측에 구비되고 파도에 의해 상기 부구본체에 돌림힘을 발생시키는 회전유도부를 포함하는 양식장용 부구;를 구비하고,상기 회전유도부는 상기 부구본체의 길이방향 양측 전면 및 후면으로부터 각각 돌출되고, 상기 부구본체의 전면 및 후면 중심 측에서 상기 부구본체의 전면 및 후면 가장자리 측으로 각각 연장되며, 상기 부구본체의 원주방향을 따라 일정 간격 이격되게 배치되는 복수의 간섭날개를 포함하고,상기 부구 고정용 브라켓은 상기 부구본체가 회전될 때, 상기 부구본체의 외주면에 마찰되면서 상기 부구본체의 외주면에 부착된 이물질을 제거하기 위한 이물질 제거부를 더 구비하며,상기 이물질 제거부는 일 측의 상기 회전지지부로부터 타 측의 상기 회전지지부로 연장되고, 상기 부구본체의 외주면에 접하도록 설치되는 스크래퍼를 포함하는 것을 특징으로 하는 양식장용 부유체., Ltext: 어업, prediction: '어업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

308/1150 Row 308: application_number: 1020190101539, combined_string: invention_title: 양식장 용수의 살균장치 abstract: 본 발명은 양식장 용수의 살균장치에 관한 것으로서, 더욱 상세하게는 해양생물, 담수생물 등의 양식장 용수의 살균성분 농도를 필요한 농도로 정확하게 맞출 수 있는 양식장 용수의 살균장치에 관한 것이다. 본 발명에 따른 양식장 용수의 살균장치는 원수 공급 라인을 통해 공급되는 원수가 저장되고 염소농도가 조정되는 조정조; 상기 조정조에서 배출되는 양식장 용수를 전기분해를 통해 살균성분을 생성시키는 차아염소산 생성장치; 상기 조정조에서 배출되는 양식장 용수의 잔류 염소를 제거하는 잔류염소 처리장치; 상기 잔류염소 처리장치에서 배출되는 양식장 용수가 공급되는 양식 수조; 및 장치내에 설치된 각종 밸브, 상기 차아염소산 생성장치를 온오프시키는 콘트롤패널을 포함하되, 상기 조정조의 원수를 상기 차아염소산 생성장치로 용수 공급라인을 통해 유입시킨 후, 상기 차아염소산 생성장치에서 생성된 살균성분을 함유하는 전해수를 차아염소산 공급라인을 통해 상기 조정조로 다시 유입시킨다. claims: 원수 공급 라인을 통해 공급되는 원수가 저장되고 염소농도가 조정되는 조정조;상기 조정조에서 배출되는 양식장 용수를 전기분해를 통해 살균성분을 생성시키는 차아염소산 생성장치;상기 조정조에서 배출되는 양식장 용수의 잔류 염소를 제거하는 잔류염소 처리장치; 상기 잔류염소 처리장치에서 배출되는 양식장 용수가 공급되는 양식 수조; 및 장치내에 설치된 각종 밸브, 상기 차아염소산 생성장치를 온오프시키는 콘트롤패널을 포함하되, 상기 조정조의 원수를 상기 차아염소산 생성장치로 용수 공급라인을 통해 유입시킨 후, 상기 차아염소산 생성장치에서 생성된 살균성분을 함유하는 전해수를 차아염소산 공급라인을 통해 상기 조정조로 다시 유입시키는 것을 특징으로 하는 양식장 용수의 살균장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

309/1150 Row 309: application_number: 1020190099689, combined_string: invention_title: 양식장용 부유 구조물 abstract: 해수면에 부유할 수 있는 부력을 포함하는 부체가 일정 간격으로 복수개 배치되고; 상기 부체의 상부에 설치되어 작업자가 가두리 양식장에서 작업하는 공간을 제공하는 발판부로 이루어지는 양식장용 부유 구조물을 제공함으로써 상기 부체는 성형제작이 용이하여 제작에 소요되는 시간과 수고 및 비용을 감소시킴은 물론 부력은 감소되지 않으면서 내구력은 향상되어 발판부의 하중이 증가해도 부체구조의 변형이 거의 없어 장치 교환에 소비되는 비용을 줄일 수 있다. claims: 해수면에 부유할 수 있도록 부력을 갖는 양식장용 부유구조물에 있어서, 부유구조물의 내부는 빈공간을 갖고, 외측면 하부는 반원형상으로 이루어지며, 외측면 상부는 작업 공간을 제공하는 발판부를 형성하도록 평평한 형상으로 이루어지고, 상기 부유구조물의 내부 중심부 상, 하면에는 지지프레임의 상단 및 하단이 삽입 고정되도록 끼움부가 형성되어, 지지프레임이 수직방향으로 삽입 고정되며,내부 중심부에 고정되는 지지프레임은 직사면체의 판 형상으로 내부가 빈 공간을 이루고 좌, 우면을 관통하는 하나 이상의 통공이 형성되어 수직으로 구분된 좌우 공간의 압력평형을 이루도록하며, 전, 후면은 개구 또는 폐쇄되어 이루어지는 것을 특징으로 하는 양식장용 부유 구조물, Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

310/1150 Row 310: application_number: 1020190098983, combined_string: invention_title: 개체굴 양식장치 abstract: 본 발명은 굴 치패가 부착되어 생육하는 채묘부재를 포함하는 개체굴 양식장치로서, 상기 채묘부재는 바닷물 속에서 소정 시간이 경과 하면 녹는 플라스틱 재질로 이루어지는 것을 특징으로 하는 개체굴 양식장치를 제공한다. 본 발명은 상기 구성에 의해서, 개체굴이 부착되는 채묘부재의 표면을 물에 녹는 소재로 함으로써 일정 시간이 지난 후 굴 치패가 자동으로 양식장 바닥으로 떨어지고, 바닥으로 떨어진 굴은 특성상 다시는 어떤 곳에도 부착하지 않게 되어 개체굴로 성장하게 된다. claims: 굴 치패가 부착되어 생육하는 채묘부재를 포함하는 개체굴 양식장치로서,상기 채묘부재는 물 속에서 소정 시간이 경과 하면 녹는 소재로 이루어지는 것을 특징으로 하는 개체굴 양식장치.굴 치패가 부착하여 생육하는 채묘부재를 포함하는 개체굴 양식장치로서,상기 채묘부재는,플레이트 형상의 제1부재; 및상기 제1부재의 일측면 또는 양측면에 구비되고 굴 치패가 부착하여 먹이활동을 하는 제2부재;로 이루어지고,상기 제2부재는 물 속에서 소정 시간이 경과 하면 녹는 소재인 것을 특징으로 하는 개체굴 양식장치., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

311/1150 Row 311: application_number: 1020190095324, combined_string: invention_title: 해삼 전복전용 참나무 어초 abstract: 본 발명은 해삼 전복전용 참나무 어초에 관한 것이다. 본 발명은 중량물인 무게중심구조물 상에 다수의 참나무가 배열된 참나무유닛을 다층으로 마련함과 동시에 최상단의 참나무유닛에서 그 하부의 참나무유닛으로 갈수록 넓어지는 피라미드형상으로 마련함으로써 참나무유닛에 전복의 주된 먹이인 미역 등과 같은 해조류와 규조류의 부착, 발생 및 생장이 지속적으로 이루어지고 다층의 참나무유닛 전체에 걸쳐 골고루 서식되며, 특히 음지와 양지를 주야로 이동하는 전복 및 해삼의 생태특성을 고려하여 참나무유닛의 참나무들 사이에 트랙형상의 홈과 통로를 통해 전복 및 해삼의 은신처 내지 대피통로를 확보하고자 하는 어초분야에 유용하게 이용할 수 있다. claims: 중량물로 이루어진 무게중심구조물; 이 무게중심구조물 위에 복수의 층을 이루도록 서로 이격되어 수평으로 설치되는 다층프레임; 이 다층프레임의 각 층마다 소정간격으로 다수의 참나무가 배열 설치되는 다층참나무유닛; 을 포함하여 구성되는 것을 특징으로 하는 해삼 전복전용 참나무 어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

312/1150 Row 312: application_number: 1020190095403, combined_string: invention_title: 복합배치 펌프 기반 육상양식장 해수공급시스템 abstract: 본 발명은 복합배치 펌프 기반 육상양식장 해수공급시스템을 제공한다. 이와 같은 본 발명에 따른 복합배치 펌프 기반 육상양식장 해수공급시스템은 육상 양식장의 규모 확장에 따라 요구되는 공급해수 유량의 확대가 육상 양식장으로 해수를 공급하는 해수공급배관의 해수면 아래 부위에 수중 보조펌프를 추가적으로 설치하는 것으로 가능해지도록 함으로써 육상 양식장과 해수공급배관 등의 현재 시설을 그대로 유지한 상태에서 보조펌프의 단순 설치를 통해서 공급해수의 유량 확대가 안정되고 원활하게 수행될 수 있게 되고, 수중 보조펌프의 추가 배치에 따른 공급해수의 유속증대와 유량확대를 통해 육상 양식장으로의 해수공급 안정성이 증대될 수 있으며, 특히 수중 보조펌프가 육상 양식장으로 해수를 공급하는 수역의 조수간만에 따른 최소 해수위 아래의 수심 위치에 설치되도록 함으로써 수중 보조펌프가 상시적으로 해수면 아래 잠긴 상태를 유지하면서 원활한 해수 강제 압송구동을 수행하게 되어 해수공급을 위한 시스템의 운용 안정성이 극대화될 수 있는 기술적 특징을 갖는다. claims: 육상 양식장(2)의 기계실(4)에 배치되는 메인 펌프(100);상기 메인 펌프(100)에 연결되어 해수면 아래로 연장형성되고, 설정된 해수유입 수심(H) 위치에 유입구(210)가 배치되는 해수공급배관(200);해수면 아래 잠긴 상태로 배치되고, 설정된 펌프설치 수심(h) 위치의 해수공급배관(200)에 설치되는 수중 보조펌프(300);육상 양식장(2)의 수조(3)와 연결되어 상기 수조(3)로 해수를 공급하는 양식장 연결배관(400);상기 해수공급배관(200)이 배치되는 수역(5)의 조수간만 정보에 맞추어 상기 메인 펌프(100)와 수중 보조펌프(300)의 동작을 제어하는 컨트롤러(500);를 포함하는 구성으로 이루어지는 것을 특징으로 하는 복합배치 펌프 기반 육상양식장 해수공급시스템., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

313/1150 Row 313: application_number: 1020190095045, combined_string: invention_title: 해삼용 쉘터 abstract: 본 발명은 해삼용 쉘터에 관한 것으로, 더욱 상세하게는 유속에 의해 쉘터가 이동되는 것을 방지하여 해삼의 서식환경이 균일하게 유지될 수 있는 해삼용 쉘터에 관한 것이다.본 발명의 해삼용 쉘터는 해수가 유입 및 배출됨에 따라 길이방향으로 해수가 흐르는 해수조부 내에 상하방향으로 일정한 폭을 형성하며, 해수의 흐름 방향으로 연장되어 양측면에 해삼이 부착되는 생장공간을 형성하는 해삼생장부와; 상기 해삼생장부가 펼쳐진 상태를 유지하고, 유속에 의해 움직이는 것을 방지하도록, 상기 해삼생장부의 하부에 상기 해삼생장부의 길이방향을 따라 다수개가 상호 이격되게 설치되며, 상기 해삼생장부의 길이방향으로 양단부가 개방된 내부수용공간을 형성하여 내부에 해수가 흐름에 따라 상기 해삼생장부에 장력을 제공하고, 개방된 양단부를 통해 상기 내부수용공간에 해삼이 유입되어 해삼이 하면 또는 동면을 하거나 생장할 수 있는 해삼휴면유닛;을 구비한다. claims: 해수가 유입 및 배출됨에 따라 길이방향으로 해수가 흐르는 해수조부 내에 상하방향으로 일정한 폭을 형성하며, 해수의 흐름 방향으로 연장되어 양측면에 해삼이 부착되는 생장공간을 형성하는 해삼생장부와;상기 해삼생장부가 펼쳐진 상태를 유지하고, 유속에 의해 움직이는 것을 방지하도록, 상기 해삼생장부의 하부에 상기 해삼생장부의 길이방향을 따라 다수개가 상호 이격되게 설치되며, 상기 해삼생장부의 길이방향으로 양단부가 개방된 내부수용공간을 형성하여 내부에 해수가 흐름에 따라 상기 해삼생장부에 장력을 제공하고, 개방된 양단부를 통해 상기 내부수용공간에 해삼이 유입되어 해삼이 하면 또는 동면을 하거나 생장할 수 있는 해삼휴면유닛;을 구비하는 것을 특징으로 하는 해삼용 쉘터., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

314/1150 Row 314: application_number: 1020190095046, combined_string: invention_title: 육상용 해삼 양식장 abstract: 본 발명은 육상용 해삼 양식장에 관한 것으로서, 더욱 상세하게는 육상에 해수가 흐르는 방향으로 해삼이 부착되어 생장하는 쉘터가 연장되게 설치될 수 있는 양식공간을 갖는 육상용 해삼 양식장에 관한 것이다.본 발명의 육상용 해삼 양식장은 다수의 쉘터가 수조부의 길이방향으로 각각 나란하게 연장되어 있어 수조부 공간대비 해삼이 부착되어 생장되는 다수의 부착공간이 확보되므로 해삼의 생산량을 증대시킬 수 있는 이점이 있다.그리고, 본 발명의 육상용 해삼 양식장은 쉘터의 하부에 형성된 다수의 해삼채집부에 의해 쉘터가 해수의 유속에 의해 움직이는 것이 방지되므로 쉘터 간 균일한 서식환경을 지속적으로 제공하여 다수의 해삼의 생장이 균일하게 이루어질 수 있는 이점이 있다. claims: 육상에 상방으로 개방되며 일정한 폭으로 제1방향으로 길게 연장된 양식공간이 형성되게 설치되며 해수가 유입되어 배출되는 수조부와;상기 수조부의 상부에 상기 수조부의 길이방향에 교차하는 방향으로 각각 연장되며 상기 수조부의 길이방향으로 상호 이격되게 배치되는 복수의 쉘터거치바를 포함하는 쉘터거치유닛과;상기 수조부 내에 양측면에 해삼이 부착되어 생장될 수 있는 부착공간을 제공할 수 있도록 상하방향으로 연장되고, 상기 제1방향으로 각각 길이 연장되며 상기 양식공간의 폭 방향으로 일정간격 이격되어 상호 나란하도록 상단에 상기 쉘터거치바에 거치되는 다수의 쉘터;를 구비하고,상기 쉘터는 상기 수조부의 하부에 양측이 상기 제1방향으로 개방되어, 상기 수조부 내에 흐르는 해수의 온도 상승 또는 하강에 따라 해삼이 상부에서 내려와 하면 또는 동면을 하거나 생장할 수 있는 유입공간을 각각 형성하여 해삼이 모일 수 있도록 유도하며, 해삼이 개방된 양측으로 유입되게 상기 제1방향으로 상호 이격되는 다수의 해삼채집부를 구비하는 것을 특징으로 하는 육상용 해삼 양식장., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

315/1150 Row 315: application_number: 1020190095047, combined_string: invention_title: 가두리 해삼 양식장치와 이를 이용한 가두리 양식장 abstract: 본 발명은 가두리 해삼 양식장치와 이를 이용한 가두리 양식장에 관한 것으로서, 더욱 상세하게는 가두리망 내에 수용되어 해삼이 생장할 수 있는 공간을 형성하는 가두리 양식장용 해삼 양식장치와 이를 이용한 가두리 양식장에 관한 것이다.본 발명의 가두리 해삼 양식장치와 이를 이용한 가두리 양식장은 격자형태로 배열된 다수 생육공간 중 일부를 해삼양식에 적용할 수 있어 이종의 해양생물의 양식이 가능하므로 양식공간 형성을 위한 별도의 설치비용을 절감할 수 있으며 공간활용을 효율을 높일 수 있어 경제적인 이점이 있다. 또한, 본 발명의 가두리 해삼 양식장치는 중심측에서 방사방향으로 다수의 쉘터부가 설치되어 구획된 다수의 해삼생장공간이 확보되므로 해삼의 생산량을 증대시킬 수 있는 이점이 있다. claims: 수상에 부유하는 가두리 양식장의 가두리망 내에 수용 가능하게 형성되며 각 면이 개방된 내부공간을 갖는 프레임과;상방으로 개방된 내부공간이 각각 형성되되 폭과 높이가 다른 다수의 쉘터부가 방사상 및 상하방향으로 상호 이격되게 중첩되어 상기 제1프레임의 중심측에서 외측 방향으로 구획된 다수의 해삼생장공간을 형성하는 쉘터유닛과;다수의 상기 쉘터부가 상기 프레임 내에서 상호 방사 방향 및 상하방향으로 이격되게 다수의 상기 쉘터부를 위치되게 고정하는 선형부재;를 구비하는 것을 특징으로 하는 가두리 해삼 양식장치.격자형태로 배열되어 다수의 생육공간을 형성하며 부력을 제공하는 다수의 부구와;상기 부구를 연결하는 파이프와; 상기 부구의 배열된 방향으로 연장되며 상기 부구에 설치되는 발판과;상기 파이프 또는 상기 발판에 설치되어 상기 생육공간에 수면 아래로 펼쳐저 해양생물을 가두는 다수의 가두리망과;상기 가두리 망내에 수용되며, 수상에 부유하는 가두리 양식장의 가두리망 내에 수용 가능하게 형성되며 각 면이 개방된 내부공간을 갖는 프레임과, 상방으로 개방된 내부공간이 각각 형성되되 폭과 높이가 다른 다수의 쉘터부가 방사상 및 상하방향으로 상호 이격되게 중첩되어 상기 프레임의 중심측에서 외측 방향으로 구획된 다수의 해삼생장공간을 형성하는 쉘터유닛과, 다수의 상기 쉘터부가 상기 프레임 내에서 상호 방사 방향 및 상하방향으로 이격되게 다수의 상기 쉘터부를 위치되게 고정하는 선형부재;를 구비하는 가두리 해삼 양식장치;를 구비하고,상기 가두리 해삼 양식장치는수온이 기준 온도보다 높게 상승되면 수저면에 인접하게 위치되게 설치되며 수온이 기준온도보다 낮은 경우에는 수상에 인접하게 위치되게 상기 가두리망 내에 설치되며, 상기 가두리망은 수온 상승 시 상기 가두리양식장용 다수의 상기 쉘터부가 수저면에 인접하게 설치될 수 있도록 다수의 상기 쉘터부의 높이보다 길고 하부가 수저면에 인접하게 상하방향으로 길이 연장형성되는 것을 특징으로 하는 가두리양식장., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

316/1150 Row 316: application_number: 1020190090707, combined_string: invention_title: 부력변동형 가두리 양식장치 abstract: 본 발명은 부력변동형 가두리 양식장치에 관한 것으로서, 수중에 구비되는 가두리 구조체와, 수면에 부상하여 상기 가두리 구조체와 연결되는 고정부표와, 상기 가두리 구조체의 상측 중앙에 설치되고 외부에서 에어를 공급받아 부력을 발생시킴으로써 상기 가두리 구조체를 부상시키거나 에어를 배기하여 물을 흡입함으로써 상기 가두리 구조체를 침강시키는 메인부력체와, 상기 가두리 구조체의 바닥 중심에 고정되어 상기 가두리 구조체의 무게중심을 잡아주는 센터링고정추와, 상기 메인부력체와 센터링고정추를 연결하는 연결수단을 포함하여 이루어지는 부력변동형 가두리 양식장치에 있어서, 상기 가두리 구조체의 상단 가장자리에는 상기 메인부력체의 요동을 최소화하기 위하여 상기 메인부력체를 향하면서 상기 메인부력체에 근접하도록 설치되는 수평밸런싱수단이 구비되어, 상기 가두리 구조체가 침하 또는 부상시 일측으로 기울어지지 않고 수평 밸런스를 유지하게 하는 것을 특징으로 한다. claims: 수중에 구비되는 가두리 구조체와, 수면에 부상하여 상기 가두리 구조체와 연결되는 고정부표와, 상기 가두리 구조체의 상측 중앙에 설치되고 외부에서 에어를 공급받아 부력을 발생시킴으로써 상기 가두리 구조체를 부상시키거나 에어를 배기하여 물을 흡입함으로써 상기 가두리 구조체를 침강시키는 메인부력체와, 상기 가두리 구조체의 바닥 중심에 고정되어 상기 가두리 구조체의 무게중심을 잡아주는 센터링고정추와, 상기 메인부력체와 센터링고정추를 연결하는 연결수단을 포함하여 이루어지는 부력변동형 가두리 양식장치에 있어서,상기 가두리 구조체의 상단 가장자리에는 상기 메인부력체의 기울어짐을 최소화하기 위하여 상기 메인부력체를 향하면서 상기 메인부력체에 근접하도록 설치되는 수평밸런싱수단이 구비되어,상기 가두리 구조체가 침하 또는 부상시 일측으로 기울어지지 않고 수평 밸런스를 유지하게 하는 것을 특징으로 하는 부력변동형 가두리 양식장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

317/1150 Row 317: application_number: 1020190090838, combined_string: invention_title: 에너지절감을 위한 저전력 고효율의 양식장 abstract: 양식장이 개시된다. 양식장은 내부에 온수 또는 냉수를 저장하도록 구성되는 물저장부; 내부에 물을 저장하도록 구성되며, 또한 물 속에서 살수 있는 생물체를 수용하도록 구성되는 수조부; 물이 순환하기 위한 코일이 마련되며, 상기 물저장부와 배관으로 연결되어 상기 물저장부로부터 공급된 물이 상기 양식장 내부를 순환되도록 구성되는 물순환부; 상기 양식장에서 배출되는 배기의 공기열을 회수하여 상기 물저장부에 저장된 물의 온도를 상승시키도록 구성되는 공기열회수부; 상기 물저장부에 저장된 물이 상기 물순환부 또는 상기 수조부로 전달되도록 구성되는 펌프부; 및 상기 물 저장부에서 물이 상기 물순환부로 또는 상기 수조부로 전달되도록 상기 펌프부의 동작을 제어하도록 구성되는 제어부를 포함한다. 본 발명에 따르면 전력을 사용하여 물의 온도를 높이이거나 낮추는 보일러와 칠러가 사용되지 않거나 사융개수가 줄어듬으로써 오랜 기간 양식장을 가동하더라도 소모비용의 부담이 덜어진다. claims: 양식장에 있어서,내부에 온수 또는 냉수를 저장하도록 구성되는 물저장부;내부에 물을 저장하도록 구성되며, 또한 물 속에서 살수 있는 생물체를 수용하도록 구성되는 수조부;물이 순환하기 위한 코일이 마련되며, 상기 물저장부와 배관으로 연결되어 상기 물저장부로부터 공급된 물이 상기 양식장 내부를 순환되도록 구성되는 물순환부;상기 양식장에서 배출되는 배기의 공기열을 회수하여 상기 물저장부에 저장된 물의 온도를 상승시키도록 구성되는 공기열회수부;상기 물저장부에 저장된 물이 상기 물순환부 또는 상기 수조부로 전달되도록 구성되는 펌프부; 및상기 물저장부에서 물이 상기 물순환부로 또는 상기 수조부로 전달되도록 상기 펌프부의 동작을 제어하도록 구성되는 제어부를 포함하는 양식장., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

318/1150 Row 318: application_number: 1020210131235, combined_string: invention_title: 큰징거미새우의 다칸 다단 양식 장치 abstract: 본 발명은 상방으로 개방되고, 저수를 위한 수조; 상기 수조의 내측에서 링형태의 경로를 따라 순환 이동하도록 다수로 배치되고, 상기 수조의 내측에서 큰징거미새우의 양식을 위한 공간을 분할 형성하도록 하는 분리칸; 및 상기 분리칸 각각이 상기 경로를 따라 이동하도록 하는 칸이송부;를 포함하도록 한 큰징거미새우의 다칸 다단 양식 장치에 관한 것이다.본 발명에 따르면, 큰징거미새우가 서로 잡아먹는 특성을 고려하여, 개별 양식을 강화시킬 수 있고, 개별 양식에도 불구하고 사육 밀도를 높임으로써 대량 양식을 도모할 수 있으며, 칸별 이송 뿐만 아니라 단별 이송을 가능하도록 함으로써, 큰징거미새우의 양식에 필요한 작업을 정해진 장소에서 편리하게 수행하도록 할 수 있고, 이로 인해 양식에 소요되는 노력과 인원을 최소화하도록 하는 효과를 가진다. claims: 상방으로 개방되고, 저수를 위한 수조;상기 수조의 내측에서 링형태의 경로를 따라 순환 이동하도록 다수로 배치되고, 상기 수조의 내측에서 물에 잠기어 큰징거미새우의 양식을 위한 공간을 분할 형성하도록 하는 분리칸; 및상기 분리칸 각각이 상기 경로를 따라 이동하도록 하는 칸이송부;를 포함하는, 큰징거미새우의 다칸 다단 양식 장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

319/1150 Row 319: application_number: 1020210101310, combined_string: invention_title: 어군용 재활용 냉동습식사료 가공방법 abstract: 본 발명은 최근에 식생활이 상향되어 먹는 부위보다 버리는 부위가 많아져 이로 인한 음식찌꺼기가 폐기물로 버려지는데 외식업조합의 노력으로 수거는 되지만 재활용도 어렵고 폐기장소도 막혀가며 더구나 비료로 활용하고자 하나 염도도 높아 사용하기 어렵고 처리하기도 어려운 상황인데 대량으로 발생되는 수산물가공공장에서 발생하는 폐기수산물까지 발생하지만 이는 가두리양식장이나 축양어장에서 활용할 수 있는 수준이므로 어군용 습식사료로 재활용하고자 개발한 어류사료에 속하는 재활용사업 가공분야에 관한 사료분야의 연구개발 사업이다,예전에는 양식어장에서 신선한 활어를 사료용으로 사용하였으나 어족자원보호와 연근해 어획통제로 활어를 구하기 어려워 이제는 사료가공 산업에도 다양한 품목과 기술이 향상되어 웬만한 신선도만 유지할 수 있게 가공한다면 폐기물에서도 재활용을 위한 선별과 가공이 가능하여 이를 새로운 재활용사업으로 이끌려는 연구가 개시되므로 재활용분야에서 새로운 과제로 전개되어 뜨는 기술개발분야이다,비록 폐기수산물만이라 하지만 모두 재활용이 가능하며 본 발명에서 어군용 재활용 냉동습식사료로 가공하여 어류습식사료로 제공되므로 인해 늘어만 가던 수산업계에 분리수거 가공으로 폐기물처리의 발생량을 저감 할 수 있고 사료사업에서도 저가의 재활용사료로 인해 사육원가도 줄일 수 있는 양대 효과는 물론 어류사료 부족문제까지 해결되는 효과가 기대된다,[색인어]폐기수산물, 분리어유, 냉동습식사료, 파쇄어죽,재활용사료, 생어사료, 가두리양식, 축양어장, claims: 가두리 또는 축양양식장양식어군에 수산물가공부산물사료로 제공되는 재활용 어군용 냉동습식사료의 가공방법에 있어서,참치수산물가공공장에서 폐기되는 참치가공부산물을 원료수집(제1공정)하여 파쇄어죽(제2공정)으로 가공하여 용기에 담고, 상기 파쇄어죽과 상기 파쇄어죽의 동량의 물로 가수교반(제3공정)한 후 가온분리(제4공정)로 상기 파쇄어죽에서 어유가 물에 용해되면 드럼여과(제5공정)로 여과어육(제6-1공정)만 수거하여 수지용기에 담아 컨베이어벨트에 올려 자외선조사(제8공정)를 하여 냉동어육(제9-1공정)으로 가공되는 것이 특징인 재활용 어군용 냉동습식사료의 가공방법, Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

320/1150 Row 320: application_number: 1020210062227, combined_string: invention_title: 동애등에 공급을 통한 넙치 양식방법 및 사료조성물 abstract: 본 발명은 넙치 유수식 양식방법에 관한 것으로, 유수식 양식에서 사용되는 넙치 사료를 어분을 대신하여 동애등에로 이루어진 곤충분이 포함하거나, 어유의 일부를 대신하여 동애등에로부터 얻어진 곤충유를 포함하여 공급함으로서 유수식 수산 양식 시스템에서 양식 넙치의 성장 및 장내 소화 활성을 증가시킬 수 있도록한 넙치 유수식 양식방법를 제공함으로써, 낮은 원료 가격과 안정된 생산량으로 사료를 제조할 수 있는 효과를 얻을 수 있다. claims: 넙치 양식방법에 있어서 넙치 양식용 사료에 포함된 성분중 동물성 단백질의 일부를 곤충으로 대체하여 급이하며,상기 넙치 양식용 사료 조성물은 탈피대두박 2중량%, 밀가루 10중량%, 비타민C 와 E 각각 0.5중량%, 비타민프리믹스와 미네랄프리믹스 각각 1중량%, 인산칼슘, 염화콜린 및 타우린이 각각 0.5중량%, 어유 3중량%로 고정되며, 동물성 단백질원인 어분이 56 내지 63중량%로 포함될 때, 동애등에로 이루어진 곤충분말은 7 내지 14중량%의 범위값으로 포함하고, 소맥글루텐 6.2~8.1중량%, 전분 2.02~4.17중량% 및 셀룰로오스 0.13~0.38중량%의 범위 값으로 포함하여 이루어지며;상기 사료조성물 100중량부에 대하여 물 30~40중량부를 더 첨가하여 펠렛 제조기로 사료를 성형하되 , 익스트루더의 스크류 속도를 885 rpm/min로 조절하여 사료 입도를 181um이하 크기로 제조한 사료를 급이하는 것을 특징으로 하는 넙치 양식방법탈피대두박 2중량%, 밀가루 10중량%, 비타민C 와 E 각각 0.5중량%, 비타민프리믹스와 미네랄프리믹스 각각 1중량%, 인산칼슘, 염화콜린 및 타우린이 각각 0.5중량%, 어유 3중량%로 고정되며, 동물성 단백질원인 어분이 56 내지 63중량%로 포함될 때, 동애등에로 이루어진 곤충분말은 7 내지 14중량%의 범위값으로 포함하고, 소맥글루텐 6.2~8.1중량%, 전분 2.02~4.17중량% 및 셀룰로오스 0.13~0.38중량%의 범위값으로 포함하여 이루어지는 것을 특징으로 하는 넙치 양식용 사료, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

321/1150 Row 321: application_number: 1020210062239, combined_string: invention_title: 동애등에 공급을 통한 무지개송어 양식방법 및 사료조성물 abstract: 본 발명은 무지개송어 순환여과식 양식방법에 관한 것으로, 순환여과식 양식에서 사용되는 무지개송어 사료의 어분을 대신하여 동애등에로 이루어진 곤충분이 포함하거나, 어유의 일부를 대신하여 동애등에로 이루어진 곤충유를 포함하여 급이함으로서 순환여과식 양식 시스템에서 양식 무지개 송어의 성장 및 장내 미생물 활성을 증가시킬수 있도록한 무지개송어 순환여과식 양식방법를 제공함으로써, 낮은 원료 가격과 안정된 생산량으로 사료를 제조할 수 있는 효과를 얻을 수 있고, 어분 및 곤충분에 의한 충실한 동물성 단백질 공급이 가능하여, 무지개송어의 성장, 비만도 저하, 생존율 및 장내 미생물 다양성 확보로 인한 항병력이 증가될 수 있는 효과가 있다. claims: 무지개송어 양식방법에 있어서 무지개송어 양식용 사료에 포함된 성분중 동물성 단백질의 일부를 곤충으로 대체하여 급이하며, 상기 무지개송어 양식용 사료는 동물성 단백질원인 어분 16중량%, 동애등에 분말 4중량%, 탈피대두박 19중량%, 소맥글루텐 10중량%, 전분 5중량%, 밀가루 14.03중량%, 비타민믹스, 미네랄믹스 각각 1중량%, 비타민 C 0.2중량%, 비타민 E 0.1중량%, 인산칼슘 0.5중량%, 염화콜린 2.5중량%, 라이신 0.07중량%, 메치오닌, 트레오닌 각각 0.04중량%, 타우린 0.52중량%, 어유11중량%를 포함하여 이루어지는 사료 조성물을 혼합하여,상기 혼합물 100중량부에 대하여 물 30~40중량부를 더 첨가하여 익스트루더로 사료를 성형하며, 상기 사료의 성형은 압출성형기의 압력조건을 619.5~708 rpm/min의 범위에서 실시하며, 사료원료의 입자도는 사료원료의 입자도는 평균 직경 180μm의 소립자로 성형한 사료를 급이하는 것을 특징으로 하는 무지개송어 양식방법동물성 단백질원인 어분 16중량%, 동애등에 분말 4중량%, 탈피대두박 19중량%, 소맥글루텐 10중량%, 전분 5중량%, 밀가루 14.03중량%, 비타민믹스, 미네랄믹스 각각 1중량%, 비타민 C 0.2중량%, 비타민 E 0.1중량%, 인산칼슘 0.5중량%, 염화콜린 2.5중량%, 라이신 0.07중량%, 메치오닌, 트레오닌 각각 0.04중량%, 타우린 0.52중량%, 어유 11중량%를 포함하여 이루어지는 것을 특징으로 하는 무지개송어 양식용 사료, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

322/1150 Row 322: application_number: 1020210044001, combined_string: invention_title: 유용미생물을 포함하는 사료 첨가제 조성물 및 이의 제조방법 abstract: 본 발명은 EM(Effective microorganisms) 발효액 및 천일염을 포함하는 장어용 사료 첨가제 조성물 및 상기 장어용 사료 첨가제의 제조방법에 관한 것이다.본 발명의 장어용 사료 첨가제 조성물은 EM 발효액 및 천일염 등의 천연 성분을 포함함으로써 우수한 항균 및 항산화 활성을 나타내어 합성 항생제의 사용을 대체할 수 있으며, 상기 사료 첨가제를 급여하여 양식된 장어는 뛰어난 맛과 향을 가지는 것을 확인하였다. claims: EM(Effective microorganisms) 발효액, 천일염, 톳 분말, 비타민 C 및 비타민 E를 포함하는 장어용 사료 첨가제 조성물로서,상기 조성물은 EM 발효액 100 중량부를 기준으로, 천일염 5 중량부, 톳 분말 10 중량부, 비타민 C 1 중량부, 및 비타민 E 1 중량부를 포함하는 것이며,상기 EM 발효액은 EM 원액, 매실 열수 추출물, 및 설탕을 1:7:2의 중량비로 혼합하여 10 내지 15일 간 발효하여 제조된 것인, 장어용 사료 첨가제 조성물.제1항의 EM(Effective microorganisms) 발효액, 천일염, 톳 분말, 비타민 C 및 비타민 E를 혼합하는 단계;를 포함하는, 제1항 장어용 사료 첨가제의 제조방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

323/1150 Row 323: application_number: 1020210033912, combined_string: invention_title: 자율주행 기반의 양식장 관리 로봇 및 그 운영 시스템 abstract: 본 명세서는 스마트 양식장을 위한 양식장 관리 로봇의 메인 컨트롤러에 의한 먹이충전 방법에 있어서, 탐지된 먹이 공급 이벤트에 근거하여 : 1) 먹이 공급이 요구되는 수조의 식별자, 먹이 종류 및 먹이 공급량 정보를 판단하고, 2) 사료 공급장치의 호퍼에 포함된 잔여 사용량을 판단하는 단계; 상기 잔여 사료량이 상기 먹이 공급량보다 적을 경우, 자율주행 구동부를 통해, 먹이 충전을 위한 충전장치로 상기 양식장 관리 로봇을 이동시키는 단계; 및 상기 충전장치로 이동이 완료된 경우, 상기 충전장치로 먹이 충전을 요청하는 충전 요청 메시지를 전송하는 단계;를 포함할 수 있다. claims: 스마트 양식장을 위한 양식장 관리 로봇의 메인 컨트롤러에 의한 먹이 공급 방법에 있어서,탐지된 먹이 공급 이벤트에 근거하여 :1) 먹이 공급이 요구되는 수조의 식별자, 먹이 종류 및 먹이 공급량 정보를 판단하고, 2) 사료 공급장치의 호퍼에 포함된 잔여 사료량을 판단하는 단계;상기 잔여 사료량이 상기 먹이 공급량보다 많거나 같은 경우 :상기 수조의 식별자 및 기설정된 순서 리스트에 근거하여, 자율주행 구동부를 통해, 상기 수조의 식별자와 대응되는 제1 수조로 상기 양식장 관리 로봇을 이동시키는 단계;상기 먹이 종류 및 상기 먹이 공급량 정보에 근거하여, 토출구를 확장시켜, 상기 제1 수조에 급이하는 단계로서, 상기 토출구는 텔레스코픽(Telescopic) 구조를 갖음; 및상기 수조의 식별자 및 기설정된 순서 리스트에 근거하여, 상기 자율주행 구동부를 통해, 제2 수조로 상기 양식장 관리 로봇을 이동시키는 단계;를 포함하는, 먹이 공급 방법.스마트 양식장을 위한 먹이를 공급하는 양식장 관리 로봇에 있어서,전기 신호를 송수신하기 위한 송수신부;디스플레이부;자율주행 구동부;수조에 먹이를 공급하고, 충전장치로부터 먹이를 충전받기 위한 사료 공급 장치; 및상기 디스플레이부; 상기 송수신부, 상기 자율주행 구동부 및 상기 사료 공급장치를 제어하는 메인 컨트롤러;를 포함하며,상기 메인 컨트롤러는탐지된 먹이 공급 이벤트에 근거하여 :1) 먹이 공급이 요구되는 수조의 식별자, 먹이 종류 및 먹이 공급량 정보를 판단하고, 2) 상기 사료 공급장치의 호퍼에 포함된 잔여 사료량을 판단하며,상기 잔여 사료량이 상기 먹이 공급량보다 많거나 같은 경우 :상기 수조의 식별자 및 기설정된 순서 리스트에 근거하여, 상기 자율주행 구동부를 통해, 상기 수조의 식별자와 대응되는 제1 수조로 상기 양식장 관리 로봇을 이동시키고,상기 먹이 종류 및 상기 먹이 공급량 정보에 근거하여, 토출구를 확장시켜, 상기 제1 수조에 급이하며, 상기 토출구는 텔레스코픽(Telescopic) 구조를 갖고,상기 수조의 식별자 및 기설정된 순서 리스트에 근거하여, 상기 자율주행 구동부를 통해, 제2 수조로 상기 양식장 관리 로봇을 이동시키는, 로봇., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

324/1150 Row 324: application_number: 1020210013676, combined_string: invention_title: 관상어 양식 시스템 abstract: 물을 지속적으로 순환시키면서 불순물의 여과 및 정제를 수행하며, 용존산소량을 대폭 상승시켜 주는 것과 더불어 수위를 일정하게 유지하는 것으로 관상어를 안정적으로 양식할 수 있는 관상어 양식 시스템을 개시한다.본 발명의 목적은 어항의 물을 지속적으로 순환시키면서 불순물의 여과 및 정제를 수행할 수 있으며, 용존산소량을 늘릴 수 있는 관상어 양식 시스템을 제공하는 것이다. claims: 4면과 바닥면으로 구성되는 관상어 양식조;상기 양식조에 물을 공급하는 물 공급수단; 및상기 물 공급수단의 말단에 연결되어 상기 양식조의 수위를 일정하게 유지하는 수위조절수단;을 포함하는 관상어 양식 시스템에 있어서,상기 양식조는,상기 양식조의 4면과 바닥면으로 형성되며, 내부에 상단의 높이는 상기 양식조의 4면보다 낮고 전, 후단은 양식조의 전, 후면에, 하단은 바닥면에 각각 고정되어 상기 양식조의 일측에 양식실을 형성하며 타측에 격실을 형성하는 제1격벽;상단의 높이는 상기 양식조의 상단에 근접하고 상기 양식조의 좌면과 제1격벽의 사이에 위치하여 상기 격실을 제1 격실과 제2격실로 분할하는 제2격벽;상기 제2격벽의 하단과 바닥면의 사이에 형성되는 유통로;작은 구멍이 무수하게 천공된 다공성으로 제작되며 상기 유통로에 대응하는 높이로 상기 제1격실 및 제2격실의 바닥에 설치되는 유통판;상기 제1격실의 유통판 상부에 적층되는 밀도가 높은 스펀지;상기 제2격실의 유통판 상부에 적층하는 밀도가 낮은 스펀지; 및상기 양식실의 바닥과 상기 스펀지의 상부에 설치되는 광물질을 구비하며;상기 물 공급수단은,외부에서 공급되는 물을 일정기간 동안 저장하는 저장조;상기 저장조에서 공급되는 물에 미네랄, 영양성분 및 관상어용 약제를 자동으로 투입하는 약품 투입수단;상기 약품투입수단을 거쳐 공급되는 물을 상기 양식조로 운송하는 파이프; 및상기 저장조의 물을 상기 양식조로 공급하기 위하여 가압하는 물공급 펌프;를 포함하며,상기 수위조절수단은,상기 파이프의 말단에 연결되는 연결부;상기 연결부에서 공급되는 물을 개폐하는 벨브; 및상기 벨브에 연결되며, 수위를 감지하여 상기 벨브의 개폐를 제어하는 수위감지수단;을 포함하며,상기 수위감지수단은,상기 벨브에 일측이 연결되며, 타측이 부력볼과 연결되어 상기 부력볼이 상승할 때 상기 벨브를 폐쇠하는 작동암; 및상기 작동암의 타측에 연결되어 일정한 부력을 가지고 있어 수위의 상승에 따라 상승하는 부력볼;을 포함하며,상기 양식 시스템은 여과조 및 광생물 반응기를 추가로 포함하며;상기 여과조는 호기조 및 혐기조를 포함하며;상기 호기조는,4면벽과 바닥으로 형성되는 내부에 상단이 상기 4면벽의 상단과 동일한 높이로 되며 전단이 4면벽 중 전면벽의 내면 중간에 고정되는 전측부와 전측부의 후단에서 좌측으로 직각연장되며 4면벽 중 후면벽의 내면과 격리되게 좌단이 4면벽 중 좌면벽의 내면 후측에 고정되는 후측부와 후측부의 하단에 천공되는 유통구를 구비하는 제1격판에 의해 구획형성되는 침전실과, 상단의 높이가 상기 제1격판보다 낮으며 좌단은 전측부의 우면 후단에 고정하고 우단은 4면벽 중 우면벽의 후측에 밀착고정하는 제2격판에 의해 침전실의 후방에 위치하게 구획형성되는 제1여과실과, 상단의 높이가 상기 제1격판보다는 낮고 제2격판보다는 높으며 제2격판과 4면벽 중 전면벽의 우측부 사이에서 좌단은 제1격판의 전측부 우면에 밀착고정하고 우단은 4면벽중 우면벽에 고정하며 하단부는 바닥과 격리되게 설치되어 하단부와 바닥 사이에 유통부가 형성되게 하는 제3격판에 의해 제1여과실 우측부 전방에 구획형성되는 제2여과실과, 상기 제3격판에 의해 제2여과실의 전방에 구획형성되는 제3여과실과, 상단이 상기 4면벽 중 전면벽의 우측부 상측에 천공되는 구멍에 결합고정되어 제3여과실의 물을 혐기조로 공급하는 공급관과, 상기 침전실에 하부로부터 차례로 적층되는 광물질과 스펀지필터 및 부직포필터와, 상기 제1~3여과실의 바닥에 깔아주는 광물질을 구비하여 구성되며;상기 혐기조는,4면벽, 상부 및 바닥으로 형성되는 혐기조 본체;상기 본체의 상부에 결합되어 상기 본체 내부의 임펠러를 일정 속도로 회전시키는 회전축;상기 회전축의 일단에 연결되어 상기 본체 내부의 물을 혼합하는 임펠러;상기 회전축의 타단에 연결되어 상기 회전축을 회전시키는 모터;상기 혐기조 4면벽 중 좌측면 벽 하단에 연결되어 상기 제3여과실에서 공급되는 물을 상기 혐기조 내부로 주입하는 공급부;상기 혐기조 4면벽중 우측벽 상단이 연결되어 혐기반응이 완료된 물을 배출하여 광생물 반응기로 공급하는 배출부; 및상기 혐기조에 유기성분을 공급하는 유기성분 공급부;를 포함하며,상기 광생물 반응기는,상기 혐기조에서 공급되는 물을 각 광생물반응기 본체로 공급하는 분배관;내부에 미세조류 및 물을 포함하며, 상기 분배관에서 공급되는 물을 이용하여 광생물반응을 수행하는 1~30개의 광생물반응기 본체; 및상기 광생물반응기 본체에서 배출되는 물을 상기 양식조로 공급하는 물 공급부;를 포함하며,상기 광생물 반응기 본체는,고분자 필름으로 제조되어 내부에 반응공간을 형성하는 필름형 본체;상기 반응공간에 위치하며, 광생물반응을 수행하는 미세조류;상기 필름형 본체를 프레임에 고정시키는 고정수단;상기 필름형 본체의 하부에 연결되어 상기 반응공간의 내부로 상기 분배관에서 공급되는 물을 주입할 수 있는 주입부; 및상기 필름형 본체의 상부에 연결되며, 상기 반응공간 내부의 물을 상기 물공급부로 공급하는 배출부;를 포함하는 것을 특징으로 하는 관상어 양식 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

325/1150 Row 325: application_number: 1020200168018, combined_string: invention_title: 육상수조식 양식장 육성기 넙치용 배합사료의 물성조절 제조방법 abstract: 본 발명은 사료원료의 입자도 조절, 압출펠렛(Extruded pellet; EP) 제조기의 압력 조절 및 알파전분에 의해 제조된 EP사료가 양식 넙치의 성장, 사료효율 및 성장인자 호르몬이 증가될 수 있도록 하는 넙치용 고품질 배합사료 제조방법에 관한 것으로, 품질 개선된 사료는 넙치의 성장 및 비만도가 증가될 수 있는 효과 및 본 발명의 기술을 적용하기 위해서 추가적인 설비 없이 양어사료회사의 기존 분쇄기, 익스트루더를 이용하여 적용 가능하여, 비용 상승 없이 품질 개선된 넙치용 배합사료 생산이 가능하다. claims: 사료원료는 어분 69중량%, 보조 단백질원으로 소맥글루텐 1.5중량%, 지질원으로 어유 3.0중량% 및 전분을 8중량%로 포함하며, 사료원료의 입자도는 평균 직경은 180μm의 소입자로 분쇄하며, 익스트루전 가공 압력은 1062~1079rpm/min의 고압력 가공조건으로 설정하여 제조된 배합사료를 1일 2회 8주간 공급하여 사육하는 것을 특징으로 하는 육상수조식 양식장의 육성기 넙치 양식방법, Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

326/1150 Row 326: application_number: 1020200162515, combined_string: invention_title: 흰다리 새우 양식용 사료 및 이를 이용한 흰다리 새우 양식 시스템 abstract: 본 발명은 녹차, 녹차, 유청, 채종박, 채종유, 어유, 스테비아, 스피룰리나, 타우린, 모자반, 호밀 및 녹말을 포함하여 제조된 흰다리 새우 양식용 사료를 이용한 흰다리 새우 양식 시스템에 관련된 것으로서, 흰다리 새우 치어가 배양되는 치어 배양 수조; 바이오플락 양식을 위해 미생물을 증식시킨 사육수가 저장되고, 치어 배양부에서 배양된 흰다리 새우 치어를 입식시켜 기 설정된 주기마다 흰다리 새우 양식용 사료를 급여함으로써 흰다리 새우 치어를 성체로 양식하는 양식 수조; 양식 수조에서 수질 샘플을 채취하여, 채취된 수질 샘플에서 검출된 수질 정보를 수집하는 센서부; 및 센서부에서 수집되는 수질 정보를 이용하여 양식 수조의 양식 환경을 제어하는 양식 환경 제어부;를 포함하는 것을 특징으로 한다. claims: 녹차, 유청, 채종박, 채종유, 어유, 스테비아, 스피룰리나, 타우린, 모자반, 호밀 및 녹말을 포함하여 제조된 흰다리 새우 양식용 사료를 이용한 흰다리 새우 양식 시스템에 있어서,흰다리 새우 치어가 배양되는 치어 배양 수조;바이오플락 양식을 위해 미생물을 증식시킨 사육수가 저장되고, 상기 치어 배양 수조에서 배양된 흰다리 새우 치어를 입식시켜 기 설정된 주기마다 상기 흰다리 새우 양식용 사료를 급여함으로써 상기 흰다리 새우 치어를 성체로 양식하는 양식 수조; 상기 양식 수조에서 수질 샘플을 채취하여, 채취된 상기 수질 샘플에서 검출되는 수질 정보를 수집하는 센서부; 및상기 센서부에서 수집된 수질 정보를 이용하여 상기 양식 수조의 양식 환경을 제어하는 양식 환경 제어부;를 포함하되,상기 흰다리 새우 양식용 사료는,전체 흰다리 새우 양식용 사료 100중량%에 대하여, 상기 녹차 4.3 내지 5.8중량%, 상기 유청 17 내지 23중량%, 상기 채종박 10.2 내지 13.8중량%, 상기 채종유 6 내지 8.1중량%, 상기 어유 11.9 내지 16.1중량%, 상기 스테비아 8.5 내지 11.5중량%, 상기 스피룰리나 2.6 내지 3.5중량%, 상기 타우린 4.3 내지 5.8중량%, 상기 모자반 4.3 내지 5.8중량%, 상기 호밀 6 내지 8.1중량% 및 상기 녹말 10.2 내지 13.8중량%를 포함하고,상기 흰다리 새우 양식 시스템은,상기 양식 수조의 내부를 촬영하는 제1 카메라 모듈이 구비되어, 상기 제1 카메라 모듈을 통해 수집되는 제1 영상 데이터와 데이터베이스에 기 저장된 흰다리 새우의 기준 영상 데이터를 비교하여, 상기 양식 수조에서 양식되는 상기 흰다리 새우 치어의 활동성을 이동 속도, 이동 범위 및, 먹이 반응성 중 적어도 어느 하나를 포함하는 행동 패턴으로 분석함으로써 모니터링하는 제1 모니터링부; 및,상기 양식 수조에 저장된 사육수 표면을 촬영하는 제2 카메라 모듈이 구비되어, 상기 제2 카메라 모듈을 통해 수집되는 제2 영상 데이터에서, 기 학습된 부유물에 대응되는 색상이 검출될 시, 사육수 면적에서 부유물에 대응되는 색상이 검출된 면적을 연산하여 상기 사육수에 현탁하여 있는 고형 부유물의 발생량을 추정하는 제2 모니터링부;를 더 포함하는 것을 특징으로 하는 흰다리 새우 양식 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

327/1150 Row 327: application_number: 1020200159150, combined_string: invention_title: 사료 급이 장치 abstract: 사료 급이 장치가 제공된다. 상기 사료 급이 장치는 사료가 저장된 저장부; 상기 저장부에 저장된 사료를 자동 배출하는 급이부;를 포함할 수 있다. claims: 양식장에 적용되는 사료 급이 장치에 있어서,사료가 저장된 저장부;상기 저장부에 저장된 사료를 자동 배출하는 급이부;를 포함하고,단말기와 통신하는 통신부가 마련되고,상기 급이부는 상기 통신부를 통해 제어 신호가 입수되면, 상기 사료를 배출하며,용존 산소량을 측정하는 측정부, 상기 급이부를 제어하는 조절부가 마련되고,상기 조절부는 상기 측정부에서 측정된 용존 산소량이 설정값을 만족하면, 상기 통신부를 통해 상기 제어 신호가 입수되더라도 상기 사료를 배출하지 못하도록 상기 급이부를 제어하는 사료 급이 장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

328/1150 Row 328: application_number: 1020200137539, combined_string: invention_title: 전복용 치패 양식판의 조립장치 abstract: 본 발명은 전복용 치패 양식판의 조립장치에 관한 것으로, 보다 상세하게는 다수 개의 양식판과 이격링을 삽입하고 조립봉으로 체결, 조립되도록 형성함으로써, 일정 간격으로 삽입, 정렬되어 고정된 상태의 다수 개의 양식판을 조립봉으로 용이하게 체결, 조립하기 때문에, 양식판의 조립 체결작업이 신속하고 간편할 수 있을 뿐만 아니라, 다수 개의 양식판이 일정 간격으로 정렬된 상태에서 조립봉을 이용하여 삽입, 고정되도록 함으로써, 양식판의 조립 및 결합 오차가 낮고 그 조립과정에서의 파손 및 손상을 미연에 방지할 수 있기 때문에, 불량률이 낮은 양식판 조립체에서 전복 치패의 안정적인 서식 및 양식 효율을 향상시킬 수 있도록 한 것이다. claims: 다수 개의 양식판을 연결, 조립하도록 하는 본체(10)와;다수 개의 양식판을 일정 간격으로 삽입, 지지하도록 상부 지지부와 하부 지지부로 구비된 조립부재(20)와;조립부재(20)의 상부 지지부(21)를 회동시키도록 하는 회동부재(30);로 형성하도록 구성되되,상기 조립부재(20)는 양식판이 일정 간격으로 삽입, 정렬되도록 형성하되, 양식판의 상부를 삽입하여 지지되도록 하는 상부 지지부(21)와, 양식판의 하부를 삽입하여 지지되도록 하는 하부 지지부(22)를 형성하도록 구성되고,상기 상부 지지부(21)와 하부 지지부(22)는,다수 개의 이격판(23)을 일정 간격으로 연결, 결합되도록 구비하여, 각 이격판 사이의 간격으로 양식판이 삽입되도록 형성하여 구성되며,상기 이격판(23)은 각 양식판의 간격을 유지하도록 하는 이격링이 요입되는 요입홈(23a)을 형성하되,양식판의 크기에 따라 조립할 수 있도록 다 수개의 요입홈(23a)을 구비하도록 형성하여 구성되는 것을 특징으로 하는 전복용 치패 양식판의 조립장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

329/1150 Row 329: application_number: 1020200089283, combined_string: invention_title: 분리가 가능한 일체형 관상어부화기 및 치어수조 abstract: 본 발명에 의한 수조의 상부에 부착하여 기포를 이용해 스폰지를 통과하여 부유물을 여과한 물이 부화기로 유입되고 조절밸브로 유입된 물을 조절해 안전하게 알을 부화시키고 부화한 치어는 자연스럽게 치어수조로 이동하며 이동한 치어수조에 바닥의 스펀지를 통해 출수되는 물에 의한 데미지를 없애고 여과기와 부화기, 치어수조를 상황에 맞게 자석을 이용해서 탈착 및 부착 할 수 있게끔 제작하여 알과 치어사육에 있어서 건강함을 유지시킬수 있으며 그동안 수조안에서 사용하던 부화기의 불편함과 위험성을 줄임으로써 사육환경의 개선과 원가절감 및 사육의 편리성등을 얻을수 있는 효과가 있다. claims: 수조의 상부에서 사용하는 분리가 가능한 일체형 부화기 및 치어사육수조청구항1에 있어서 자석을 이용해서 여과기와 부화기를 붙이는 방식 및 제작법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

330/1150 Row 330: application_number: 1020200083233, combined_string: invention_title: 항공 수송용 활어 컨테이너 abstract: 항공기 내부 공간에 적재될 수 있는 규격의 다각형상의 바닥부를 일정 높이의 외벽이 둘러싸며 내부에는 사육수와 활어가 입식되는 내부 공간이 형성되는 수조본체; 상기 수조본체 어느 한 측면부에는 수조본체 환경을 조절하는 구동장치부가 설치되는 항공 수송용 활어 컨테이너를 제공함으로써, 환경에 민감한 살아있는 활어를 항공기로 수송이 가능하여 장거리의 지역에서도 높은 신선도의 수산 식품을 제공할 수 있을 뿐만 아니라 국내 수산물의 수출량을 증가시킬 수 있고, 항공수송시 피칭이 크고 빈도수가 많아 수조본체 내부에 저장된 사육수가 이동관을 따라 지그재그 형상으로 따라 흐르면서 피칭으로 생성된 사육수압이 이동하는 힘으로 전환됨에 따라 수압이 소산되어 수조본체 외부로 누수되는 것을 방지할 수 있는 효과가 있다. claims: 항공기 내부 공간에 적재될 수 있는 규격의 다각형상의 바닥부를 일정 높이의 외벽이 둘러싸며 내부에는 사육수와 활어가 입식되는 내부 공간이 형성되는 수조본체; 상기 수조본체 어느 한 측면부에는 수조본체 환경을 조절하는 구동장치부가 설치되어 이루어지는 것인 항공 수송용 활어 컨테이너, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

331/1150 Row 331: application_number: 1020200046137, combined_string: invention_title: 황금색 체색 발현율을 향상시키기 위한 양식 황금넙치의 육종방법 abstract: 본 발명은 황금 넙치 선별을 위해 표본 넙치를 영상 촬영장치를 이용하여 촬영하는 넙치 촬영단계(가); 상기 (가) 단계로 촬영된 표본 넙치 이미지를 소프트웨어 상에서 배경보정 및 어체 이미지의 RGB값과 CMYK값을 분석하는 단계를 포함하는 이미지 보정 및 분석단계(나); 상기 (나)단계로 분석된 CMKY값 중 Y값의 비율이 45.00 이상인 것을 선별하는 넙치 선별 단계(다); 상기 (다)단계로 선별된 넙치 암,수를 교배하는 교배단계(라)로 이루어진 황금넙치 육종방법을 제공함으로써, 세대를 거듭할수록 발현시점이 빨라지고, 발현크기는 작아지며, 최종 발현율은 높아질 뿐만 아니라 상품성이 높은 개체가 늘어나는 육종 황금넙치 개발이 가능하다. claims: 황금색을 갖는 넙치를 수집하여 선별된 GF0세대의 암, 수 황금넙치를 교배하여 발생한 GF1세대 넙치자손 교배단계(A);상기 (A)단계의 GF1세대 넙치자손을 다시 선별하여 교배하는 GF2세대 넙치자손 교배단계(B);상기 (B)단계의 GF2세대 넙치자손을 다시 선별하여 교배하는 GF3세대 넙치자손을 교배단계(C)를 포함하며,상기 어느 하나의 교배단계에서 넙치의 선별은 이미지 촬영장치를 이용하여 넙치의 체표면을 촬영하고, 상기 촬영된 넙치 이미지를 소프트웨어 상에서 보정하여 넙치 이미지의 색채값을 RGB값과 CMYK값으로 분석하고, 분석된 CMKY값 중 Y값의 비율이 43% 이상인 넙치를 선별하는 것을 특징으로 하는 황금넙치 육종방법넙치의 체표면을 이미지 촬영장치로 촬영하고, 상기 촬영된 넙치 이미지를 소프트웨어 상에서 보정하여 넙치 이미지의 색채값을 RGB값과 CMYK값으로 분석하고, 상기 분석된 CMKY값 중, Y값의 비율이 43% 이상인 넙치를 선별하여 상기 선별된 넙치 암, 수를 교배하는 것을 특징으로 하는 황금넙치 육종방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

332/1150 Row 332: application_number: 1020200040248, combined_string: invention_title: 자동 생먹이 공급기 abstract: 본 발명은 일정한 내부공간을 구비하여 상기 내부공간에 생물 먹이가 수용되도록 하는 몸통부와; 상기 생물 먹이의 공급량을 일정하게 조절하여 지속적으로 공급할 수 있도록 적정량의 물을 상기 몸통부의 상기 내부공간으로 공급하는 물 주입부와; 상기 몸통부의 상기 내부공간에 냉동 혹은 살아있는 생물 먹이를 균일한 밀도로 용해 혹은 각반시킬 수 있도록 하는 에어공급부와; 용해 또는 각반된 상기 생물 먹이를 사육조로 내보내는 먹이 배출구를; 포함하여 구성됨으로써, 대규모의 수중동물의 양식 산업시설에서 초기 부화 자어에서 상품이 성어가 되기 전까지의 양식 과정에서 생물 먹이(냉동생물 먹이 포함)를 안전하게 적정량으로 지속 공급하기 위한 장치를 개발하여 먹이의 절감과 노동력이 부족한 양식 현장의 생력화를 기하며 수질환경을 안정시켜 사육어를 건강하게 사육시켜 생존율을 높임으로서 경제적 양식을 실현할 수 있는 효과가 있다. claims: 일정한 내부공간(110)을 구비하여 상기 내부공간에 생물 먹이(1)이 수용되도록 하는 몸통부(100)와; 상기 생물 먹이(1)의 공급량을 일정하게 조절하여 지속적으로 공급할 수 있도록 적정량의 물을 상기 몸통부(100)의 상기 내부공간(110)으로 공급하는 물 주입부(200)와;상기 몸통부(100)의 상기 내부공간(110)에 냉동 혹은 살아있는 생물 먹이(1)을 균일한 밀도로 용해 혹은 각반시킬 수 있도록 하는 에어공급부(300)와;용해 또는 각반된 상기 생물 먹이(1)를 사육조로 내보내는 먹이 배출구(400)를; 포함한 것을 특징으로 하는 자동 생먹이 공급기., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

333/1150 Row 333: application_number: 1020200036300, combined_string: invention_title: 픽티바실러스 속 균주 또는 이의 배양액을 유효성분으로 포함하는 적조 방제용 조성물 abstract: 본 발명은 코클로디니움 폴리크리코이데스 (Cochlodinium polykrikoides)를 포함하는 와편모조류에 대해 살조 활성을 가지는 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주, 배양액 또는 이로부터 분리한 화합물 및 이의 용도에 관한 것으로, 보다 상세하게는 본 발명의 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주는 유해 적조생물인 코클로디니움 폴리크리코이데스 (Cochlodinium polykrikoides)를 포함하는 와편모조류에 대해서만 선택적으로 살조 활성을 나타내기 때문에 적조 제어시 수생태계의 교란을 최소화할 수 있으며, 균주를 직접 처리하지 않고 배양액을 처리하더라도 비교적 안정적으로 살조 활성을 유지하므로, 국내 양식장에 큰 피해를 입히는 코클로디니움 폴리크리코이데스 (Cochlodinium polykrikoides)를 포함하는 와편모조류를 살조하는데 더욱 유용하게 사용될 수 있다. claims: 살조 활성을 가지는 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주.제1항 내지 제4항 중 어느 한 항의 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주, 이의 배양액 또는 이의 배양여액을 유효성분으로 포함하는 적조 방제용 조성물픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주로부터 분리한 L-페닐알라닌 또는 안트라닐산을 유효성분으로 포함하는 적조 방제용 조성물제1항 내지 제4항 중 어느 한 항의 픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주, 이의 배양액 또는 이의 배양여액의 유효량을 적조 발생 지역에 처리하는 단계를 포함하는 적조를 방제하는 방법픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주로부터 분리한 L-페닐알라닌 또는 안트라닐산의 유효량을 적조 발생 지역에 처리하는 단계를 포함하는 적조를 방제하는 방법픽티바실러스 속 (Fictibacillus sp.) 5A8M 균주를 배양하는 단계를 포함하는 적조 방제용 조성물의 제조 방법, Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

334/1150 Row 334: application_number: 1020200034466, combined_string: invention_title: 부유형 공기 공급장치 abstract: 호수나 양식장 등의 수중에 공기를 공급하여 수중 생물의 서식환경을 개선시킬 수 있는 부유형 공기 공급장치가 개시된다. 이를 위하여 공기탱크의 기능을 제공하도록 내부에 공기가 수용되는 중공이 구비된 블록형 구조로 형성되고, 내부에 수용된 공기를 외부로 배출하는 연통구가 표면에 형성되며, 수면 위를 부유하는 부유체와, 상기 부유체에 설치되어 공기를 흡입하는 공기펌프, 및 상기 공기펌프에 연결되어 부유체의 내부로 공기를 주입하는 흡기관을 포함하는 공기흡입부와, 상기 부유체의 측면에 설치되어 부유체에 부력을 보조하는 부력체, 및 상기 부유체의 내부와 수중을 연결하여 부유체의 내부에 수용된 공기를 수중으로 배출시키는 공기배출부를 포함하는 부유형 공기 공급장치를 제공한다. 본 발명에 의하면, 산소가 필요한 지점에 바로 설치하여 불필요한 배관을 설치할 필요가 없기 때문에 공기 공급장치의 제작비용을 절감할 수 있으며, 공기의 이동경로를 제공하는 배관의 총 길이가 기존 공기 공급장치보다 짧아지므로 공기의 이동에 따른 마찰손실이 줄어들어 에너지 효율을 극대화시킬 수 있다. claims: 공기탱크의 기능을 제공하도록 내부에 공기가 수용되는 중공이 구비된 블록형 구조로 형성되고, 내부에 수용된 공기를 외부로 배출하는 연통구가 표면에 형성되며, 수면 위를 부유하는 부유체; 상기 부유체에 설치되어 공기를 흡입하는 공기펌프, 및 상기 공기펌프에 연결되어 부유체의 내부로 공기를 주입하는 흡기관을 포함하는 공기흡입부;상기 부유체의 측면에 설치되어 부유체에 부력을 보조하는 부력체; 및상기 부유체의 연통구에 결합되어 부유체의 내부에 수용된 공기를 수중으로 배출시키는 공기배출부를 포함하는 부유형 공기 공급장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

335/1150 Row 335: application_number: 1020200033484, combined_string: invention_title: 미생물을 활용한 양식방법 abstract: 본 발명의 일 실시예에 따른 미생물을 활용한 양식방법은, 양식수조, 상기 양식수조 내에 수용된 사육수를 정화하는 정화장치 및 상기 정화장치에서 정화된 사육수에 공기를 혼합하여 용해하는 용해장치를 포함하는 미생물 양식시스템에 적용된 미생물을 활용한 양식방법에 관한 것이다. claims: 양식수조, 상기 양식수조 내에 수용된 사육수를 정화하는 정화장치 및 상기 정화장치에서 정화된 사육수에 공기를 혼합하여 용해하는 용해장치를 포함하며,상기 양식수조는 상부가 개구되고 바닥과 외벽이 구비된 수용부; 상기 수용부의 중심에 회전 가능하도록 배치되고 내부에 재공급 유로가 형성되는 회전로드; 일측이 상기 회전로드의 외주면과 연통되도록 결합되되, 내부에는 상기 재공급 유로와 연결된 서브유로가 형성되고, 측면에는 복수 개의 공급공이 형성되는 적어도 하나의 정화수 재공급유닛; 상기 수용부의 외벽 내측에 부착된 이물질을 제거하기 위하여 상기 정화수 재공급유닛의 타측에 배치된 브러시유닛;을 포함하며,상기 수용부 측벽에는 투명창부가 구비되되, 상기 투명창부의 수용부 내측으로는 격자망 형태의 메시부가 구비되며,상기 투명창부에 대응되는 위치로 상기 수용부 내부에는 램프부가 구비되며,상기 정화장치는 상기 양식수조에서 배출된 사육수의 고형 이물질을 제거하는 가압부상모듈; 고형 이물질이 제거된 사육수에 포함된 질소성분을 제거하는 탈질모듈; 질소성분이 제거된 사육수를 중공사막필터를 이용하여 정화하는 중공사막모듈; 중공사막모듈을 통과한 사육수를 여과막을 이용하여 여과하는 막정화모듈; 및 상기 탈질모듈의 탈질과정에서 발생된 오염공기를 탈취하는 탈취모듈;을 포함하고,상기 탈취모듈은 내부 중공된 박스 형태의 외부케이스와, 상기 외부케이스의 일측 하부에 상기 탈질모듈과 연결되게 구비되는 연결관과, 상기 외부케이스 타측 상부에 구비되는 공기배출부를 포함하며,상기 외부케이스는 내측에 상하로 다수 개의 격벽부가 구비되되, 상기 격벽부는 각각 일측과 타측이 상기 외부케이스로부터 이격된 상태를 이루어 하부로부터 상측 상기 공기배출부까지 지그재그방식으로 공기가 유동 가능하도록 구성되며,최하단에 구비된 격벽부는 상기 외부케이스와 이격된 부위를 개폐하는 경로차단부가 구비되며, 상기 각 격벽부는 소정 이격된 간격마다 탈취유닛이 설치되는,미생물 양식시스템에 적용된 미생물을 활용한 양식방법에 있어서,상기 양식수조 내에 양식생물, 사료, 미생물 및 사육수를 공급하는 단계;상기 사육수의 오염정도에 기초하여 상기 양식수조 내에 수용된 사육수를 배출하는 단계;상기 정화장치가 상기 양식수조에서 배출된 사육수를 정화하는 단계;상기 용해장치가 상기 정화장치에 의하여 정화된 정화수에 공기를 혼합하여 용해하는 단계; 및상기 공기가 용해된 사육수를 상기 양식수조에 재공급하는 단계;를 포함하는 미생물을 활용한 양식방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

336/1150 Row 336: application_number: 1020200028854, combined_string: invention_title: 프로바이오틱스를 활용한 사료 및 그 제조방법 abstract: 본 발명은 프로바이오틱스를 활용한 동물 사료 및 그 제조방법에 관한 것으로써, 배양단계(S1a), S.C.배양단계(S1b) 및 베이스혼합단계(S1c)와; 혼합단계(S2)와; 생산단계(S3)와; 절단단계(S4)와; 확인단계(St)와; 포장단계(S5)로 구성되어 있어, 사료 제조시 열에 의하여 사멸되는 생균의 개체수를 최소화하여, 동물이 사료를 섭취할 때, 최대한 많은 개체수의 프로바이오틱스가 체내로 유입되어, 증식하면서 장내 환경을 산성으로 만들고, 유해균의 번식을 억제할 수 있어, 장내 환경을 건강하게 유지할 수 있으며, 또한, 면역시스템을 향상시킬 수 있는 프로바이오틱스를 활용한 동물 사료 및 그 제조방법에 관한 것이다. claims: 프로바이오틱스를 활용한 동물 사료 제조방법에 있어서, pH 5.0~7.0 및 30~55℃의 환경에서 포자 형성균을 배양하는 배양단계(S1a)와; 30~55℃의 환경에서 Saccharomyces cerevisiae를 배양하는 S.C.배양단계(S1b)와;전분, 셀룰로오스, 생선살, 동물성원료가수분해물, 보존제, 연어유, 글리세린, 정제 포도당 및 정제수를 혼합하여 베이스혼합물을 제조하는 베이스혼합단계(S1c)와; 베이스혼합단계(S1c)를 통하여 생성된 베이스혼합물에 배양단계(S1a)에서 배양된 포자형성균과 S.C.배양단계(S1b)에서 배양된 Saccharomyces cerevisiae를 혼합하여 최종혼합물을 제조하는 혼합단계(S2)와; 상기 최종혼합물을 섭씨60~130도에서 압출장치를 이용하여 압출혼합물을 생산하는 생산단계(S3)로; 구성되어 있는 것을 특징으로 하는 프로바이오틱스를 활용한 동물 사료 제조방법.제 1항 내지 6항 중 어느 한 항의 방법을 이용하여 제조되는 것을 특징으로 하는 프로바이오틱스를 활용한 동물 사료., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

337/1150 Row 337: application_number: 1020200024803, combined_string: invention_title: 수생물 보호블럭을 이용한 양식장의 모니터링 관리시스템 및 그 방법 abstract: 본 발명은 친환경적인 수생물 보호블럭을 적용하여 수중 식물 및 어류의 서식 활동을 돕고, 각종 센서들이 보호블럭 수생군락에 설치되어 서식 온도, 해류 및 일조량의 조건에 따른 개체수의 증감 변화를 쉽게 파악할 수 있도록 하고, 자가발전을 통해 각종 센서들의 센싱구동이 가능하여 측정 오차를 줄일 수 있고, 수중중계기에 의해 외부에서 안전하게 어류의 생태 환경을 감시 개량해 나갈 수 있도록 한 수생물 보호블럭을 이용한 양식장의 모니터링 관리시스템 및 그 방법을 제공한다. 본 발명의 적절한 실시 형태에 따른 수생물 보호블럭을 이용한 양식장의 모니터링 관리시스템은, 다수의 수생물 보호블럭들이 상호 결합되어져 연결수단을 통해 양식장에 분포 배치된 보호블럭 수생군락과; 해당 보호블럭 수생군락에 각기 배치되어 수온, 해류, 일조량, 어군을 감지하여 해당 감지 신호를 출력하는 서식환경 감지부와; 양식장의 수면에 부상되어 상기 환경감지부로부터 검출된 신호를 수신하고 데이타 처리하여 양식장의 관리자 또는 운영자의 외부 단말기로 송신하는 수중중계기와; 상기 수중중계기에 장착되어 자가 발전으로 수중중계기를 구동시키는 발전유닛;을 포함한 것을 특징으로 한다. claims: 다수의 수생물 보호블럭(20)들이 상호 결합되어져 연결수단(5)을 통해 양식장에 분포 배치된 보호블럭 수생군락(201~207)과;해당 보호블럭 수생군락(201~207)에 각기 배치되어 수온, 해류, 일조량, 어군을 감지하여 해당 감지 신호를 출력하는 서식환경 감지부(300)와;양식장의 수면에 부상되어 상기 환경감지부(300)로부터 검출된 신호를 수신하고 데이타 처리하여 양식장의 관리자 또는 운영자의 외부 단말기(600)로 송신하는 수중중계기(400)와;상기 수중중계기(400)에 장착되어 자가 발전으로 수중중계기(400)를 구동시키는 발전유닛(500);을 포함한 것을 특징으로 하는 수생물 보호블럭을 이용한 양식장의 모니터링 관리시스템.다수의 수생물 보호블럭(20)들이 상호 결합되어져 보호블럭 수생군락(201~207)을 이루도록 한 후, 연결수단(5)을 통해 양식장에 보호블럭 수생군락(201~207)을 분포 배치시키는 단계와;부양체(420), 부양체(420)에 고정되어 있는 수중중계기 함체(410), 수중중계기 함체(410)에 탑재된 측정검출부(430), 측정검출부(430)에서 검출된 데이타를 실시간으로 처리하여 송신모듈(450)로 전송시키기 위한 수중중계기 제어부(440)를 포함한 수중중계기(400)를 수상에 배치시켜 놓는 단계와;상기 보호블럭 수생군락(201~207)에 배치된 온도 감지센서(310), 해류 감지센서(320), 일조량 감지센서(330), 어군 감지센서(340)로부터 해당 감지 신호를 수중중계기(400)의 측정검출부(430)로 송출시키는 단계와;상기 측정검출부(430)에 의해 검출된 온도, 해류, 일조량 및 어군 데이타를 실시간으로 송신모듈(450)을 통해 외부 단말기(600)로 송출시키는 단계;를 포함한 것을 특징으로 하는 수생물 보호블럭을 이용한 양식장의 모니터링 관리 방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

338/1150 Row 338: application_number: 1020200021150, combined_string: invention_title: 상황버섯 추출액을 이용한 장어 사료 제조방법 abstract: 본 발명은 상황버섯 추출액을 이용한 장어 사료 제조방법에 관한 것으로서, 장어의 양식에 있어서 면역력을 증대시켜 항생제를 사용하지 않고 양식할 수 있도록 함을 목적으로 한 것이다.즉, 본 발명은 장어 사료 제조방법에 있어서, 상황버섯을 분쇄가 용이하게 건조하는 상황버섯건조과정과 상기 상황버섯건조과정을 통하여 건조된 상황버섯을 270매쉬 이상의 크기로 상황버섯분말로 분쇄하는 상황버섯분쇄과정, 상황버섯분말을 90℃의 온도로 열처리하는 상황버섯분말열처리과정, 상기 상황버섯분말열처리과정을 통하여 열처리되어 열이 축열된 상황버섯분말을 상온의 온도로 냉각하는 상황버섯분말냉각과정, 상기 상황버섯분말에 90℃의 물과 혼합하여 상황믹싱수를 제조하는 상황버섯온수믹싱과정, 상기 상황믹싱수를 100℃의 온도로 6시간 가열하는 상황믹싱수가열과정, 상기 상황믹싱수를 270매쉬의 여과지를 통과시켜 상황수추출물을 추출하는 상황수추출과정, 상기 상황수추출물을 이용하여 어육과 대맥분말 또는 소맥분말을 믹싱하여 장어사료반죽제조과정, 상기 장어사료장어사료반죽제조과정을 제조된 장어사료반죽을 일정크기로 압출하는 장어사료알갱이제조과정, 상기 장어사료알갱이제조과정을 건조하는 알갱이건조과정을 이루어진 것을 특징으로 하는 것이다.따라서, 본 발명은 장어의 양식에 있어서 장어의 면역력을 증대시켜 항생제를 사용하지 않고 양식할 수 있는 효과를 갖는 것이다. claims: 장어 사료 제조방법에 있어서;상황버섯을 분쇄가 용이하게 건조하는 상황버섯건조과정과 상기 상황버섯건조과정을 통하여 건조된 상황버섯을 270매쉬 이상의 크기로 상황버섯분말로 분쇄하는 상황버섯분쇄과정, 상황버섯분말을 90℃의 온도로 열처리하는 상황버섯분말열처리과정, 상기 상황버섯분말열처리과정을 통하여 열처리되어 열이 축열된 상황버섯분말을 상온의 온도로 냉각하는 상황버섯분말냉각과정, 상기 상황버섯분말에 90℃의 물과 혼합하여 상황믹싱수를 제조하는 상황버섯온수믹싱과정, 상기 상황믹싱수를 100℃의 온도로 6시간 가열하는 상황믹싱수가열과정, 상기 상황믹싱수를 270매쉬의 여과지를 통과시켜 상황수추출물을 추출하는 상황수추출과정, 상기 상황수추출물을 이용하여 어육과 대맥분말 또는 소맥분말을 믹싱하여 장어사료반죽제조과정, 상기 장어사료장어사료반죽제조과정을 제조된 장어사료반죽을 일정크기로 압출하는 장어사료알갱이제조과정, 상기 장어사료알갱이제조과정을 건조하는 알갱이건조과정을 이루어진 것을 특징으로 하는 상황버섯 추출액을 이용한 장어 사료 제조방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

339/1150 Row 339: application_number: 1020200010429, combined_string: invention_title: 관상어 치어의 입식을 위한 수질환경 조성방법 abstract: 본 발명은 비단잉어 및 금붕어 관상어 치어를 양식장에 입식 하기 전처리하여 치어의 안정적인 성장을 위한 양식장 수질환경을 조성하는 방법에 관한 것으로 더욱 상세하게는 치어의 먹이원인 물벼룩을 채집하여 수조에 투입하는 물벼룩 투입단계, 물벼룩을 배양시키기 위해 건조된 배양재료를 수조에 투입하는 준비단계, 상기 준비단계 후 산소용존량과 pH와 수온을 측정하면서 물벼룩을 배양하는 배양단계 및 상기 배양단계를 마친 후 관상어 치어를 입식하는 입식단계로 이루어지는 관상어 치어의 입식을 위한 수질환경 조성방법에 관한 것이다.이상에서 설명한 바와 같이 본 발명에 의한 관상어 치어의 입식을 위한 수질환경 조성방법은 관상어 치어 입식 전 치어의 먹이원인 물벼룩을 배양시켜 안정적으로 물벼룩을 제공함으로써 치어의 생장을 돕고, 수질 측정과 물벼룩 배양시 사용되는 배양재료에 따라 관상어 치어의 입식시기를 결정하여 관상어 치어의 성장률을 높이며, 해외에 의존하고 있는 사료를 사용하지 않아 치어 생장에 드는 비용을 절감시키고, 그 과정도 단순화하여 치어 생육이 간단히 이루어질 수 있다. claims: 관상어 치어를 입식하기 전 수질환경 조성방법에 있어서,상기 수질환경 조성방법은 a) 치어의 먹이원인 물벼룩을 채집하여 수조에 투입하는 물벼룩 투입단계;b) 물벼룩을 배양시키기 위해 건조된 배양재료를 수조에 투입하는 준비단계;c) 상기 준비단계 후 산소용존량과 pH와 수온을 측정하면서 물벼룩을 배양하는 배양단계; 및d) 상기 배양단계를 마친 후 관상어 치어를 입식하는 입식단계;로 이루어지는 것을 특징으로 하는 관상어 치어의 입식을 위한 수질환경 조성방법., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

340/1150 Row 340: application_number: 1020217023207, combined_string: invention_title: 수산양식용 프로바이오틱 먹이 abstract: 본 발명은 양식된 수생 동물에게 먹이원으로서 비브리오 미대 SY9를 공급하는 단계를 포함하는 수산양식 방법을 제공한다. 또한 비브리오 미대 SY9를 포함하는 먹이 조성물이 제공된다. 상기 수생 동물은 전형적으로 조류를 먹는 해양 동물이다. 이들은 전복 및 극피동물, 예컨대 성게, 해삼, 불가사리, 거미 불가사리, 연잎 성게류 및 바다나리류를 포함한다. 상기 비브리오 미대 SY9는 지지체 상에 형성된 알긴산염 막 상에 또는 내에 제공될 수 있다. claims: 수생 동물의 수산양식 방법으로서, 수생 동물에게 먹이원으로서 적어도 비브리오 미대 SY9를 공급하는 단계를 포함하는 방법.수생 동물의 사료용으로 제제화된 먹이 조성물로서, 주요 먹이원으로서 비브리오 미대 SY9를 포함하는 먹이 조성물., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

341/1150 Row 341: application_number: 1020190168422, combined_string: invention_title: 디지털 트윈 스마트 어항 플랫폼 서비스 기술 abstract: 본 발명은 디지털트윈 기술(현실세계 제품의 형상, 기능, 운전조건(센서와 연계) 등을 실제와 완전히 동일한 디지털(사이버) 모델로 구현하고 지능형 통합시뮬레이션(Intelligent Multi-Physics Simulation)을 통해 제품 거동, 결함, 수명 등의 복잡한 미래 특성을 정밀 예측·분석하기 위한 차세대 제품개발 기술 및 확장 기술)을 이용하여 고가의 열대어 양식 사업자 또는 집에서 열대어를 키우는 사용자들이 이용 가능한 스마트 어항에 대한 플랫폼 서비스를 제공하는 것을 특징으로 한다. claims: 열대어를 키우는 어항에 여과기, 조명, 히터, 온도측정기, 조명, 카메라 및 센서가 연결되어 조건이 변화됨에 따른 변화를 인지하고 디지털 트윈으로 정보를 전달하는 것을 특징으로 한다., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

342/1150 Row 342: application_number: 1020190164300, combined_string: invention_title: 다영양 입체양식을 이용한 해조류와 우렁쉥이의 복합양식방법 abstract: 우렁쉥이와 해조류를 복합적으로 양성하는 생태통합양식장치를 이용한 복합양식방법을 제공함으로써 동물과 식물양식의 수질개선 기반의 복합양식으로 상부의 해조류양식을 통해 수질개선과 해조류생산을 유도하고, 하부의 우렁쉥이 양식은 개선된 수질양식의 효과를 통해 동물양식에서 발생하기 쉬운 질병발생 및 오염과부하를 감소시킬 수 있어 친환경적인 양식이 가능함으로 양식어장의 오염저감, 안전, 안심 수산물의 안정적 생산 공급과 양식수산물의 부가가치 극대화 및 수산업의 미래 산업화를 통한 신성장 동력을 창출할 수 있는 효과가 있다. claims: 설정된 해역 해저면에 고정 설치되는 다수개의 계류장치; 상기 계류장치 일단과 연결 설치되고 타단은 우렁쉥이 양성로프와 연결되는 계류로프; 상기 계류로프 일단과 양단이 연결되어 해중에 수평하게 설치되는 우렁쉥이 양성로프; 상기 우렁쉥이 양성로프에는 수하식으로 하나 이상의 우렁쉥이 채묘장치가 일정 간격 이격되어 설치되며; 상기 우렁쉥이 양성로프 및 계류로프와 연결되는 해조류 고정로프; 상기 해조류 고정로프와 수평으로 연결되는 해조류 양성장치; 상기 해조류 고정로프에는 복수개의 부력장치가 코너플래이트를 매개로 연결되어 이루어지는 것인 생태통합양식장치생태통합양식을 실시할 해역을 정하고 생태통합양식장치 설치를 준비하는 단계(가); 부화한 우렁쉥이 유생이 입식된 채묘 수조에 유생을 우렁쉥이 채묘장치에 부착시킨 후, 상기 (가)단계의 생태통합양식장치의 우렁쉥이 양성로프에 4월 내지 6월까지 연결 설치하는 우렁쉥이 채묘장치 설치단계(나);상기 (나)단계를 거친 후, 수온이 22℃ 이하로 하강하는 시기에 해조류 양성로프 설치를 시작하여 이듬해 2월까지 로프 설치를 실시하는 해조류 양성로프 설치단계(다);상기 (다)단계를 거친 후 상기 (나)단계를 기준으로 3년차까지 우렁쉥이와 해조류를 복합적으로 양성하는 복합양성단계(라)로 이루어진 것인 생태통합양식장치를 이용한 복합양식방법, Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

343/1150 Row 343: application_number: 1020190149264, combined_string: invention_title: 통합 컨트롤 및 실시간 모니터링이 가능한 비바리움 유리 사육장 abstract: 본 발명은 파충류나 양서류를 사육하는 사육장에 있어서, 애완동물이 사육하지 좋은 환경을 제공하는 것을 목적으로 하는 것으로서 즉, 사육공간을 갖는 몸체케이스, 외부 일측에 부착되어 몸체케이스 내부로 물을 순환공급하는 순환물공급장치, 상부덮개부로 구성하고, 상기 상부덮개부 하단에 UV램프부, 순환물공급장치의 물을 사육공간으로 안개로 분사하는 안개분사부, 쿨링팬부 및 사육공간을 측정하는 환경감지센서부와 상기 몸체케이스 내부 사육환경을 조절하는 제어장치부, 상기 제어장치부를 조작하는 모니터링조작장치부로 구비하고, 상기 순환물공급장치는 조절된 온도의 물을 공급하는 수중펌프부와 일측에 물을 정화하는 물정화장치부를 구비하며, 상기 복수의 사육장을 원격으로 관리하는 사육장원격조작시스템을 구비하여, UV램프부, 쿨링팬부 및 안개분사구로 인하여 사육장내부에 온도, 공기, 습도를 조절하며, 특히 상기 안개분사구의 경우 상기 순환물공급장치로 인하여 여과된 물을 분사하여 가습시 오염을 방지하며, 상기 순환물공급장치와 물정화장치부로 인하여 물을 여과하며 순환시키며, 적정한 온도의 물을 공급하여 사육장내부에 물의 관리에 편리성이 증대되며, 복수의 사육장을 사육장원격조작시스템으로 원격으로 관리하여 사육환경의 관리를 손쉽게 하는 효과를 갖는 통합 컨트롤 및 실시간 모니터링이 가능한 비바리움 유리사육장에 관한 것이다. claims: 파충류 및 양서류를 사육하는 유리사육장에 있어서,내부에 사육공간을 갖는 몸체케이스(1), 상기 몸체케이스(1) 외부 일측에 부착되어 몸체케이스(1) 내부로 물을 순환공급하는 순환물공급장치(100), 상기 몸체케이스(1) 상단에 몸체케이스(1)를 덮는 상부덮개부(300), 상기 상부덮개부(300) 하단에 발광하여 열을 공급하는 UV램프부(310), 습도를 조절하는 습기를 공급하는 안개분사부(320), 환기 및 쿨링하는 쿨링팬부(330), 사육공간의 온습도를 측정하는 환경감지센서부(340), 상기 몸체케이스(1) 내부 사육환경을 조절하는 제어장치부(400), 상기 제어장치부(400)를 조작하는 모니터링조작장치부(500)로 구비하고,상기 순환물공급장치(100)는 몸체케이스(1) 하부내부와 공급통로(251)로 연결되어 공급되는 물을 저장하는 보관수조구(110), 상기 보관수조구(110) 내부에 수온을 조절하는 수중히터구(120) 및 수온을 측정하는 수온측정구(130)를 구비하고,상기 안개분사부(320)는 상기 보관수조구(110)의 물을 끌어 분사하도록 일단이 보관수조구(110)에 연결된 관형으로 구비하고, 상부덮개부(300)측에 안개가 분사되는 분사노즐(321)을 구비하고,상기 제어장치부(400)는 무선으로 정보를 송수신하는 외부통신구(410)를 구비하고,PC 또는 스마트 기기에 상기 외부통신구(410)의 신호를 통신장치로 송수신하여 사육환경을 모니터링하며, 제어장치부(400)를 원격으로 조작하는 사육장원격조작시스템(600)을 구비하고,상기 사육장원격조작시스템(600)은 복수의 유리사육장을 통합하여 연결관리하는 멀티통합관리시스템을 구비하는 통합 컨트롤 및 실시간 모니터링이 가능한 비바리움 유리사육장., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

344/1150 Row 344: application_number: 1020190149510, combined_string: invention_title: 경사배양대를 이용한 민물김의 양식 방법 abstract: 본 발명은 민물김을 성숙시켜 포자를 얻고 상기 포자를 생장시켜 민물김을 얻을 수 있는 민물김의 양식 방법에 대한 것으로, 더욱 상세하게는 포자생장시 특정 단계에서 유속의 부여시 경사배양대를 이용하여 용이하게 대량으로 민물김을 얻을 수 있는 민물김의 양식 방법에 대한 것이다. claims: 민물김을 성숙시켜 포자 방출을 유도하여 포자를 얻는 포자수득단계와, 상기 포자수득단계에서 얻은 포자를 생장시켜 민물김을 얻는 포자생장단계를 포함하며,상기 포자생장단계에서는 특정 시기에 유속을 부여하여야 포자를 생장시켜 민물김을 얻을 수 있으며, 상기 포자생장단계에서 유속의 부여시 경사배양대를 이용하는 것을 특징으로 하는 민물김의 양식 방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

345/1150 Row 345: application_number: 1020217012550, combined_string: invention_title: 활어 선별 장치 (SORTING DEVICE FOR LIVE FISH) abstract: 알려진 선별 장치(sorting device)는 복수의 슬릿 구멍(slit opening)들을 포함하는 수직의 그리드 유닛(grid unit)으로 구성되고, 그 크기는 어류에 적합하고 그리고 어류가 자발적으로 헤엄칠 수 있다. 가능한 적은 스트레스를 유발하는 슬릿 구멍들(07)의 크기 조정을 위해, 본 발명에 따른 선별 장치(01)는 슬릿 구멍들(07)의 배열 및 크기를 동일하게 가지는 최소의 캐리어 플레이트(carrier plate)(15) 및 조정 플레이트(adjustment plate)(16)을 가진다. 조정 플레이트(16)는 조정 플레이트(16) 상의 수평 또는 수직의 웹들(08, 09)이 덮이거나 또는 드러나도록, 유효 슬릿 구멍(effective slit opening)들(07e)이 형성되는 캐리어 플레이트(15) 상의 슬릿 구멍들(07)이 그들의 위치 상에 있도록 하기 위해 캐리어 플레이트(15)상에 이동 가능한 방식으로 배열된다. 측면 이동성이 있는 경우, 유효 슬릿 구멍들(07e)의 폭만 조정되고, 그리고 높이는 변함없이 유지된다. 청구된 선별 장치(01)는 고정된 그리드 유닛(03)에서의 스트레스 없는 자발적인 자체 선별, 또는 양식의 넙치류 생선의 물 탱크(02)에서 움직이는 그리드 유닛(03)에서의 낮은 스트레스의 능동적인 선별에 특히 적합하다. claims: 활어(live fish)의 선별 장치(sorting device)(01)에 있어서, 상기 선별 장치는,위쪽을 향해 열리는 물 탱크(02); 및주변의(circumferential) 밀봉 엘리먼트(sealing element)(06)를 통해 상기 물 탱크(02)의 내부에 연결되고, 상기 물 탱크(02)를 2개의 분리된 영역들(04,05)로 나누고, 복수의 슬릿 구멍(slit opening)들(07)을 가지는 수직의 그리드(grid) 유닛(03) -상기 복수의 슬릿 구멍들은 수평 및 수직의 웹(web)들(08, 09)로 범위가 정해지고, 선별되는 상기 활어의 모양 및 사이즈로 조절되고, 이들에 대해 폐쇄됨-; 을 포함하고,상기 그리드 유닛(03)은 적어도 하나의 캐리어 플레이트(carrier plate)(15) 및 적어도 하나의 조정 플레이트(adjustment plate)(16)로 구성되고 -상기 적어도 하나의 캐리어 플레이트(15) 및 상기 적어도 하나의 조정 플레이트(16)는 동일한 디자인과 배열의 상기 슬릿 구멍들(07) 및 상기 수평 및 수직의 웹들(08,09)을 가짐-,상기 캐리어 플레이트(15)는 상기 물 탱크(02)를 상기 2개의 영역들(04, 05)로 나누고,상기 조정 플레이트(16)는 상기 캐리어 플레이트(15) 상에서 옮길 수 있게(displaceably) 배열되고, 그리고상기 조정 플레이트(16)의 위치에 따라, 상기 캐리어 플레이트(15)의 상기 슬릿 구멍들(07)은 상기 조정 플레이트(16)의 상기 수평 및 수직의 웹들(08, 09)로 커버되고(covered), 최대값(MAX)과 최소값(MIN) 사이의 유효(effective) 슬릿 구멍들(07e)이 형성되고,상기 캐리어 플레이트(15) 상의 상기 유효 슬릿 구멍들(07e)은 상기 최대값에서 완전히 열리고, 선별되는 상기 활어가 사이로 헤엄치지는 것을 방지하는 정도까지 상기 최소값으로 닫히는,선별 장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

346/1150 Row 346: application_number: 1020217016436, combined_string: invention_title: 동물 세포 증식 촉진제, 동물 세포 배양용 배지 및 동물 세포 배양 장치 abstract: 본 발명은, 신규한 동물 세포 증식 촉진제를 제공하는 것을 목적으로 한다. 구체적으로는, 조류 또는 파충류 알의 배아막의 배양 상등액을 동물 세포 증식 촉진제로 사용한다. 예를 들어, 동물 세포 배양용 배지에 조류 또는 파충류 알의 배아막의 배양 상등액을 유효성분으로 함유하는 세포 증식제를 첨가함으로써. 동물 세포의 증식을 촉진할 수 있다. claims: 새 또는 파충류의 유정란 유래 배아막의 배양 상등액을 유효성분으로 함유하는 동물 세포 배양 증식 촉진제.제1항 내지 제5항 중 어느 한 항에 기재된 세포 증식 촉진제를 함유하는 세포 배양용 배지.조류 또는 파충류 알의 배아막 유래의 세포를 배양하는 제 1 배양조와,증식을 목적으로 하는 동물 세포를 배양하는 제 2 배양조와,제 1 배양조에서 제 2 배양조로 배지를 흐르게 하는 제 1 유로와, 제 2 배양조에서 제 1 배양조로 배지를 흐르게 하는 제 2 유로와,제 1 배양조, 제 1 유로, 제 2 배양조, 제 2 유로의 순서로 세포 배양용 배지를 환류시키고, 상기 동물 세포 및/또는 상기 세포 배양용 배지의 상태에 따라, 제 1 유로 및 제 2 유로에 있어서의 상기 세포 배양용 배지의 흐름을 제어하는 배지 유량 제어부를 구비하는 동물 세포 배양 장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

347/1150 Row 347: application_number: 1020190137573, combined_string: invention_title: 수산 양식장 IOT 관리 시스템 abstract: 본 발명은 양식장에 설치된 설비의 작동정보와 센서들에서 측정된 센싱정보를 제공받아 관리하면서 센싱정보에 따라 예약된 설비의 작동을 작동시키며 센싱정보가 기준 범위를 벗어나면 양식업체에게 알려주고, 양식업체가 설비의 작동을 변경시킬 수 있도록 하는 수산 양식장 IOT 관리 시스템에 관한 것이다.본 발명에 따른 수산 양식장 IOT 관리 시스템은 단일보드 컴퓨터(200)에서 양식장에 설치된 센서들에서 측정된 센싱정보와 양식장에 설치된 설비의 작동시키는 설비 제어장치(100)와 통신하면서 설비의 작동정보를 제공받아 관리센터(300)로 제공하고, 관리센터(300)는 양식업체가 확인할 수 있도록 설비작동정보와 센싱정보를 인터넷 또는 양식업체 단말기(400)로 제공하고, 센싱정보가 등록된 설비작동기준을 확인하여 변경되는 설비의 작동변경정보를 단일보드 컴퓨터(200)로 제공하게 된다. claims: 양식장에 설치된 설비를 작동시키는 설비 제어장치(100), 양식장에 설치된 센서들에서 측정된 센싱정보와 설비 제어장치(100)로부터 설비의 작동상태를 제공받으며 유동아이피를 사용하는 단일보드 컴퓨터(200), 관리센터(300), 양식업체 단말기(400)를 포함하되, 단일보드 컴퓨터(200)는 관리센터(300)에 각종 정보를 제공하고 수신받을 수 있도록 인증키, 고유식별코드를 제공하고 인증받아 유동아이피를 사용하는 단일보드 컴퓨터(200)를 관리센터(300)에 정기적 또는 비정기적으로 접속하는 관리센터 호출부(202)와; 양식장에 설치된 설비의 작동을 제어하는 설비 제어장치(100)로부터 설비의 작동상태를 제공받는 실시간 설비작동상태 확인부(204)와; 양식장에 설치된 센서로부터 실시간으로 측정된 센싱정보를 제공받는 실시간 센싱정보 확인부(206)와; 실시간 설비작동상태 확인부(204)에서 수신된 양식장 설비의 작동정보와 실시간 센싱정보 확인부(206)에서 수신된 양식장 센서의 센싱정보를 관리센터(300)로 제공하는 양식장정보 제공부(208)와; 관리센터(300)로부터 양식장 설비의 작동을 변경하는 변경정보를 수신받는 설비작동변경 수신부(210)와; 설비작동변경 수신부(210)로 수신된 설비의 변경정보를 양식장의 설비에 매칭된 설비 제어장치(100)로 제공하는 설비작동변경 요청부(212);를 포함하고, 관리센터(300)는 양식장에 대한 정보를 단말기로 제공받아 관리하는 양식업체에 대한 정보를 등록받아 관리하는 양식업체 등록부(302)와; 등록된 단일보드 컴퓨터(200)의 접속을 확인하는 단일보드 컴퓨터 접속확인부(304)와; 접속된 단일보드 컴퓨터(200)로부터 실시간으로 제공되는 센싱정보를 제공받아 저장하면서 업데이트하는 센싱정보 관리부(306)와; 접속된 단일보드 컴퓨터(200)로부터 실시간으로 양식장의 설비 작동상태를 제공받아 저장하면서 업데이트하는 설비상태 관리부(308)와; 양식장의 센싱정보에 따라 대응되는 설비작동기준을 등록받아 관리하는 양식장 설비작동기준 등록부(310)와; 단일보드 컴퓨터(200)로부터 제공받은 양식장의 센싱정보와 양식장의 설비상태를 등록된 설비작동기준과 비교하여 센싱정보에 따라 설정된 설비작동기준을 확인하는 양식장 센싱정보 비교부(312)와; 양식장 센싱정보 비교부(312)에서 확인된 센싱정보에 대응되는 설비작동기준을 접속된 단일보드 컴퓨터(200)로 제공하는 양식장 설비작동 조작부(314)와; 실시간 설비작동상태 확인부(204)에서 수신된 양식장의 실시간 설비의 작동상태를 등록된 양식업체가 확인할 수 있도록 제공하는 양식장 설비상태 전송부(316)와; 실시간 센싱정보 확인부(206)에서 수신된 양식장의 센싱정보를 등록된 양식업체가 확인할 수 있도록 제공하는 실시간 양식장 센싱정보 전송부(318)와; 실시간 센싱정보 확인부(206)에서 수신된 양식장 주변정보와 수질정보에 대한 센싱정보가 등록된 기준 정상범위를 벗어나면 등록된 양식업체에게 긴급알림정보로 제공하는 설비 이상작동 경고부(320)와; 등록된 양식업체로부터 설비의 작동을 변경하기 위한 설비작동 변경정보를 제공받으면 접속된 단일보드 컴퓨터(200)로 제공하는 양식업체 설비작동 전송부(322)와; 등록된 양식업체로부터 다른 양식업체에 대한 고유식별정보를 등록받고, 다른 양식업체로부터 등록승인을 받으면 제휴 양식장으로 등록하여 관리하는 제휴 양식장 등록부(324)와; 제휴 양식장에 대한 실시간 센싱정보를 제휴 양식장으로 등록한 양식업체에게 제공하는 제휴 양식장 센싱정보 확인부(326)와; 등록된 양식장의 센싱정보를 제공받아 활용하는 기관을 등록받고, 센싱정보를 제공하는 양식업체로부터 등록승인을 받으면 제휴된 타기관으로 관리하는 타기관 등록부(328)와; 등록된 타기관에게 단일보드 컴퓨터(200)로부터 제공받은 센싱정보를 제공하는 타기관 센싱정보 제공부(330);를 포함하고, 양식업체 단말기(400)는 관리센터(300)로부터 제공받은 양식장의 실시간 설비의 작동상태를 화면에 표시하는 실시간 양식장 설비상태 표시부(402)와; 관리센터(300)로부터 제공받은 양식장의 실시간 주변정보 및 양식장 수질정보를 화면에 표시하는 실시간 양식장 센싱정보 표시부(404)와; 관리센터(300)의 양식장 설비작동기준 등록부(310)에 등록되는 설비의 예약기준을 변경하는 설비작동 예약 변경부(406)와; 관리센터(300)로부터 긴급알림정보가 수신되면 해당 센싱정보를 화면에 표시하는 긴급 알림표시부(408)와; 양식장에 설치된 설비의 작동이 변경되도록 조작하여 관리센터(300)로 제공하는 설비 조작부(410)와; 양식장의 센싱정보를 제공받는 다른 양식장에 정보를 관리센터(300)로 제공하는 이웃 양식장 등록부(412)와; 관리센터(300)로부터 제공받은 등록된 다른 양식장의 실시간 센싱정보를 표시하는 이웃 양식장 센싱정보 표시부(414);를 포함하며, 센싱정보는 온도, 습도, 조도를 포함하는 양식장의 주변정보와, 물의 온도, 염도, DO, pH, 적조, 녹조 수치를 포함하는 양식장의 수질정보로 이루어지고, 타기관은 관공소, 연구기관, 양식장 설비 수리업체 중의 어느 하나인 것을 특징으로 하는 수산 양식장 IOT 관리 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

348/1150 Row 348: application_number: 1020190109828, combined_string: invention_title: 게 껍질 함유 사료를 이용한 뱀장어 치어의 양성방법 abstract: 본 발명은 미성어(未成魚) 단계의 새끼장어(치어, 稚魚)와 성어(成魚) 단계의 식용장어에 게 껍질 분말이 함유된 사료를 급여하여 성장률과 생존율을 향상시킬 수 있는 어류, 특히 뱀장어의 양성방법에 관한 것이다.본 발명의 게 껍질 함유 사료를 급여하는 뱀장어 치어의 양성방법은 일반 분말사료를 급여하는 양식방법에 비하여 뱀장어의 체장과 체중의 성장률이 증가하고 어체의 비필수 아미노산 함량이 증가하며, 면역력이 강화되어 별도의 항생제를 사용하지 않아도 생존율이 높고 사료효율이 우수하며 폐기처분되는 게 껍질 수산부산물을 단순 분쇄하여 재활용하므로 뱀장어 양식의 경제성을 높일 수 있으며, 또한 게 껍질에 함유된 키틴, 키토산뿐만 아니라 각종 유기물과 미네랄 성분들이 분말사료에 더하여지므로 영양과 미네랄이 조합된 고효율의 사료를 저비용으로 뱀장어에 공급할 수 있다. claims: 체중 4~7 g의 새끼장어를 수온 25~32 ℃의 순환여과식 시스템에 입식하는 단계;상기 입식된 새끼장어에 분말사료를 2~4일간 급여하는 단계; 및상기 분말사료 급여 후 게 껍질 분말이 5~12 중량% 함유된 분말사료를 어체 총중량의 2~5 중량%/일의 양으로 급여하는 단계;를 포함하는, 게 껍질 함유 사료를 이용한 뱀장어 치어의 양성방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

349/1150 Row 349: application_number: 1020190097865, combined_string: invention_title: 행동 패턴 인식을 이용한 소의 발정 탐지 시스템 abstract: 본 발명은 소의 발정 탐지 시스템에 관한 것으로서, 보다 구체적으로는 행동 패턴 인식을 이용한 소의 발정 탐지 시스템으로서, 소에 부착되어 소의 움직임 및 행동을 감지하는 행동탐지 센서; 상기 행동탐지 센서에서 감지된 데이터를 수신받아 저장하고, 기저장된 축우 관련 사육정보와 함께 데이터베이스를 구축하는 DB 서버; 및 상기 DB 서버에 저장된 데이터를 분석하여 소의 행동 패턴을 인식하고 발정을 탐지하는 분석 서버를 포함하여 구성되며, 상기 분석 서버는, 상기 DB 서버에 저장된 움직임 데이터를 기초로 분석하여, 소의 휴식상태, 활동상태, 및 고활동상태를 포함하는 행동 유형의 특징적 패턴을 찾아내고, 소의 행동 유형을 판단하는 행동분석 모듈; 및 상기 행동분석 모듈에서 판단된 상기 소의 행동 유형 정보를 통해 승가 정보를 분석하고 소의 발정 여부를 탐지하는 발정탐지 모듈을 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 행동 패턴 인식을 이용한 소의 발정 탐지 시스템에 따르면, 부착된 행동탐지 센서에서 감지한 소의 움직임 및 행동 정보를 토대로, 소의 행동 유형 패턴을 판단하고 소의 발정 여부를 탐지하는 분석 서버 및 발정탐지 모듈을 포함함으로써, 소의 발정기를 보다 정확하고 용이하게 판단할 수 있어, 소의 번식 효율을 증가시키고 발정 미감지로 인한 피해를 줄여, 궁극적으로는 한우 농가의 생산성 및 수익성에 이바지하고 농가의 소득 증대에 이바지할 수 있다.또한, 본 발명에서 제안하고 있는 행동 패턴 인식을 이용한 소의 발정 탐지 시스템에 따르면, 가속도 센서에서 감지된 3축 가속도 신호의 drift 발생으로 인해 생길 수 있는 오차를 보정 및 전처리하고, 감지된 3축 가속도 신호를 통계적, 수학적 방법으로 분석함으로써, 소의 행동 유형 패턴을 보다 정교하게 판단할 수 있으며, 특히, 인공지능 기술 중 딥러닝 알고리즘을 이용하여 소의 행동 유형을 판단함으로써, 같은 유형의 행동이 개체에 따라 다양한 신호 패턴을 보여 그 신호의 편차가 크더라도 오류를 줄일 수 있고, 한우 개체별로 상이한 행동 양식, 성격, 생활 습성, 건강상태, 우방에서의 서열 등을 고려한 판단이 가능하여, 소의 발정기 탐지적중률을 제고시킬 수 있다.뿐만 아니라, 본 발명에서 제안하고 있는 행동 패턴 인식을 이용한 소의 발정 탐지 시스템에 따르면, 분석 서버에서 분석한 소의 행동 유형 정보 및 발정 탐지 정보와 관찰카메라부에서 촬영한 영상을 기초로, 소의 생애 주기에 따른 생체정보 제공 및 축사 모니터링이 가능한 스마트기기의 애플리케이션을 구축함으로써, 궁극적으로는 종합적인 축사 사육현황 및 번식관리 솔루션을 제공하고, ICT 융복합 관련 핵심기술인 무선통신기술, 통합제어기술, 센싱기술, 알고리즘 기술을 활용하여, 우리나라 축산에 대한 소비자의 인식전환을 유도하고 축산업 경쟁력을 상승시킬 수 있다. claims: 소의 발정 탐지 시스템(10)으로서,소에 부착되어 소의 움직임 및 행동을 감지하는 행동탐지 센서(100);상기 행동탐지 센서(100)에서 감지된 데이터를 수신받아 저장하고, 기저장된 축우 관련 사육정보와 함께 데이터베이스를 구축하는 DB 서버(200);상기 DB 서버(200)에 저장된 데이터를 분석하여 소의 행동 패턴을 인식하고 발정을 탐지하는 분석 서버(300);축사를 24시간 촬영하고 촬영된 영상을 상기 DB 서버(200)로 송신하는 관찰카메라부(400); 및상기 분석 서버(300)에서 분석한 행동 유형 정보 및 발정 탐지 정보와 상기 관찰카메라부(400)에서 촬영된 영상을 시각화시켜 보여주는 스마트기기(500)를 포함하며,상기 행동탐지 센서(100)는,소의 귀에 부착되는 것을 특징으로 하며,개체의 머리, 귀, 입놀림 및 몸 전체의 움직임에 의한 귀의 떨림을 이용하여, 기울기 값을 측정하는 3축 가속도 센서(110);개체의 머리, 귀, 입놀림 및 몸 전체의 움직임에 의한 귀의 떨림을 이용하여, 방향값을 측정하는 자력계(120); 및상기 3축 가속도 센서(110) 및 상기 자력계(120)에서 측정된 소의 움직임 및 행동 데이터를 상기 DB 서버(200)로 송신하는 송신부(130)를 포함하여 구성되고,상기 3축 가속도 센서(110)는,감지된 3축 가속도 신호의 drift 발생으로 인한 오차를 보정 및 전처리하되, state-space 기반의 방식으로 sensor fusion 혹은 state-space model을 사용함으로써 drift 누적으로 인한 오차 및 발생하는 에러를 보상하며,상기 행동탐지 센서(100)에서 사용되는 통신은, 동적으로 무선 자원을 할당하여 배터리 소모를 줄이는 알고리즘을 이용하되, 데이터양과 변화율을 측정하여 Beacon Interval을 조절해 채널 경쟁을 하는 노드 수를 줄이고 데이터 전달 지연시간을 최소화하며, 보장 전송 구간 할당 요청으로 가중치를 계산하여 우선도에 따라 보장 전송 구간을 할당하거나 공정한 분배를 통해 보장 전송 구간 요청 처리율을 높이고 지연시간을 감소시키며,상기 분석 서버(300)는,상기 DB 서버(200)에 저장된 움직임 데이터를 기초로 분석하여, 소의 휴식상태, 활동상태, 및 고활동상태를 포함하는 행동 유형의 특징적 패턴을 찾아내고, 소의 행동 유형을 판단하는 행동분석 모듈(310); 및상기 행동분석 모듈(310)에서 판단된 상기 소의 행동 유형 정보를 통해 승가 정보를 분석하고 소의 발정 여부를 탐지하는 발정탐지 모듈(320)을 포함하며,상기 행동분석 모듈(310)은,통계적 분석 방법으로서, 단위 시간 동안의 평균/분산/표준편차(RMS), 평균 편차 비교 분석법, 기울기 변화량 적분법, 변량 도수 분포 분석법, 및 퓨리에 주파수 변환(FFT) 분석법 중 적어도 하나 이상을 이용하며, 딥러닝 기술을 기반으로 상기 DB 서버(200)에 저장된 움직임 데이터로부터 행동 유형을 분석하여, 같은 행동의 패턴이더라도 개체에 따라서 3축 가속도 센서의 신호 패턴의 편차가 크게 나오는 경우를 보완하며,상기 발정탐지 모듈(320)은,기설정된 일정 시간 단위로 행동 유형별 시간 점유율 및 분포를 계산하여 승가 정보를 분석하고 소의 발정 여부를 탐지하며, 상기 DB 서버(200)에 저장된 움직임 데이터로부터 개체별 습성 및 상태 정보를 취득하여, 소의 발정 여부 판단을 보완하며,소의 엉덩이에 부착되어, 접점검출 방식으로 승가 허용 여부를 감지하고, 감지된 승가 허용 정보를 상기 DB 서버(200)로 송신하는 승가 허용 탐지 센서(600)를 더 포함하여, 상기 승가 허용 탐지 센서(600)에서 감지된 소의 승가 허용 정보를 함께 이용하여 소의 발정 여부를 탐지하는 것을 특징으로 하는, 행동 패턴 인식을 이용한 소의 발정 탐지 시스템(10)., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

350/1150 Row 350: application_number: 1020217023134, combined_string: invention_title: 여과기 부착 수조 셋트 abstract: 수조 본체(1) 내에 여과기(F)를 구비한 여과기 부착 수조 셋트에 있어서, 수조 본체(1)는, 저류수가 저류되고 상면이 개방된 그릇형으로 형성되고, 그 내부에 여과기(F)가 설치되고, 수조 본체(1)와 여과기(F)의 여과 케이스(10)가, 모두 동색으로 불투명하게 형성된다. 이것에 의해, 관상어를 관상하는 관상자에게 있어서, 수조 내에 설치되는 여과기가, 수조의 밖에서 잘 보이지 않도록 하여 관상어의 관상 효과를 높이도록 했다. claims: 수조 본체(1) 내에, 상기 수조 본체(1) 내의 저류수를 순환 여과하는 여과기(F)를 구비한 여과기 부착 수조 셋트로서, 상기 수조 본체(1)는, 관상어를 사육하기 위해 저류수가 저류되고 상면이 개방된 그릇형으로 형성되고, 그 내부에 상기 여과기(F)가 설치되고, 상기 수조 본체(1)와 상기 여과기(F)의 여과 케이스(10)는 모두 동색(同色)으로 불투명하게 형성되는 것을 특징으로 하는 여과기 부착 수조 셋트., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

351/1150 Row 351: application_number: 1020210136681, combined_string: invention_title: 빅데이터를 이용한 인공지능 기술 기반 이상징후 표적 감지 방법 및 그 시스템 abstract: 본 개시(disclosure)의 다양한 실시 예들에 따르면, 바다를 항해하는 표적의 이상징후를 감지하기 위한 이상징후표적 감지 시스템은, 항해 표적을 탐지하여 항해 표적 정보를 출력하는 레이더, 서버로부터 미리 등록된 표적들에 대한 저장 표적 정보를 선박식별장치에게 전달하는 서버, 상기 항해 표적 정보와 상기 저장 표적 정보를 융합하여 상기 항해 표적의 이상징후 여부를 결정하고, 상기 이상징후 여부를 표시하는 선박식별장치를 포함할 수 있다. claims: 바다를 항해하는 표적의 이상징후를 감지하기 위한 이상징후표적 감지 시스템에 있어서,항해표적을 탐지하여 항해표적 정보를 출력하는 레이더;기등록된 복수의 항해표적 각각에 대하여, 복수의 시각 각각에 대응하는 표적크기 정보, 표적위치 정보, 계획된 이동경로 정보 및 이동속도 정보를 포함하는 저장표적 정보를 선박식별장치에게 전달하는 서버; 및상기 레이더로부터 탐지된 항해표적에 대한 항해표적 정보를 수신하고, 상기 탐지된 항해표적이 상기 저장표적 정보에 기등록된 복수의 표적에 포함되어 있지 않은 표적인 경우 상기 항해표적을 제1 이상징후 표적으로 결정하고, 상기 탐지된 항해표적이 상기 저장표적 정보에 기등록된 복수의 표적에 포함된 표적인 경우 상기 항해표적 정보를 상기 저장표적 정보와 융합하여 표적크기 정보, 표적위치 정보, 이동경로 정보 및 이동속도 정보를 포함하는 빅데이터 분석정보를 생성하고, 상기 생성된 빅데이터 분석정보를 상기 서버로 전송하는 선박식별장치; 를 포함하고,상기 서버는, 상기 선박식별장치로부터 수신된 빅데이터 분석정보를, 제1 가중치가 부여된 표적크기 정보, 제2 가중치를 부여된 표적위치 정보, 제3 가중치가 부여된 이동경로 정보 및 제4 가중치가 부여된 이동속도 정보를 포함하는 분석정보를 학습 정보로 하여 이동 경로를 출력하도록 학습된 인공지능 모델에 입력하고, 상기 인공지능 모델을 통해 출력된 출력 정보를 기초로 상기 항해표적의 과거 이동경로 및 상기 항해표적의 미래 예측경로를 획득하고, 상기 항해표적의 과거 이동경로 및 상기 항해표적의 미래 예측경로를 상기 선박식별장치로 전송하고, 상기 선박식별장치는, 상기 서버로부터 수신한 과거 이동경로와 상기 저장표적 정보에 포함된 계획된 이동경로 정보 간의 오차에 대응하는 제1 오차 값 및 상기 서버로부터 수신한 미래 예측경로와 상기 저장표적 정보에 포함된 계획된 이동경로 정보 간의 오차에 제5 가중치가 부여된 제2 오차값을 획득하고, 상기 제1 오차값 및 상기 제2 오차값 중 적어도 하나가 기설정된 임계 값 이상인 것으로 판단되면, 상기 항해표적을 제2 이상징후 표적으로 결정하는 것을 특징으로 하는, 이상징후표적 감지 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

352/1150 Row 352: application_number: 1020210058941, combined_string: invention_title: 슬러지 고착방지기구를 구비한 양식장용 산소용해장치 abstract: 본 발명은 양식장에 공급되는 해수에 산소를 투입하여 용존산소율을 향상하기 위해 양식장에 공급되는 해수가 유입되는 유입파이프(100)와, 상기 유입파이프로 유입되는 해수에 기화된 산소를 공급하는 산소공급구(200)와, 상기 유입파이프에 연결되어 산소와 해수가 혼합되어 공급되는 혼합공급구(300)를 구비하고, 상기 양식장용 산소용해장치는 상부에는 공급된 기체 산소와 해수가 혼합되는 혼합공간부(A)와 상기 혼합공간부(A)에서 혼합된 해수를 배출하는 해수배출구(600)가 부착된 산소용해통체(400)를 구비한 양식장용 산소용해장치에 있어서,상기 해수배출구(600) 와 산소용해통체(400)의 바닥면(410) 사이에 상기 바닥면에 모여지는 슬러지의 고착되는 것을 방지하고, 고착된 슬러지를 바닥면(410)에서 분리할 수 있는 슬러지 고착방지구(700)를 구비하며, 상기 슬러지 고착방지구(700)는 고압공기구(800)에서 공급되는 고압공기를 바닥면을 향하여 분사하는 다수개의 분사구(710)를 구비하는 것을 특징으로 하는 슬러지 고착방지기구를 구비한 양식장용 산소용해장치를 제공한다. claims: 양식장에 공급되는 해수에 산소를 투입하여 용존산소율을 향상하기 위해 양식장에 공급되는 해수가 유입되는 유입파이프(100)와, 상기 유입파이프로 유입되는 해수에 기화된 산소를 공급하는 산소공급구(200)와, 상기 유입파이프에 연결되어 산소와 해수가 혼합되어 공급되는 혼합공급구(300)를 구비하고,상부에는 공급된 기체 산소와 해수가 혼합되는 혼합공간부(A)와 혼합공간부(A)에서 산소가 혼합되어 산소가 용해된 해수로 이루어진 해수공간(B)로 이루어지고, 산소가 용해된 해수를 배출하는 해수배출구(600)가 부착된 산소용해통체(400)를 구비한 양식장용 산소용해장치에 있어서,상기 해수배출구(600)와 산소용해통체(400)의 바닥면(410) 사이에 상기 바닥면에 모여지는 슬러지의 고착되는 것을 방지하고, 고착된 슬러지를 바닥면(410)에서 분리할 수 있는 슬러지 고착방지구(700)를 구비하며,상기 슬러지 고착방지구(700)는 고압공기구(800)에서 공급되는 고압공기를 바닥면을 향하여 분사하는 다수개의 분사구(710)를 구비하며, 또한, 상기 슬러지 고착방지구(700)는 원통 형상의 산소용해통체(400) 내부에 내부공간을 가진 파이프로 원형 링 형상으로 형성된 고착방지구 몸체(720)와,상기 고착방지구 몸체(720)에 일정한 간격으로 분사구(710)가 구비되되,상기 분사구(710)의 분사 방향은 바닥면으로 향하되, 고착방지구 몸체(720)의 중심원주와 수직보다 작은 각도(α1〈 90)로 형성되어 고착방지구 몸체(720)의 내경쪽으로 향하는 동시에 원주방향으로 일정한 각도(α2)로 기우려져, 상기 분사구(710)에서 분사된 압축공기에 의하여 바닥면의 해수가 회전할 수 있도록 이루어진 것을 특징으로 하는 슬러지 고착방지기구를 구비한 양식장용 산소용해장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

353/1150 Row 353: application_number: 1020210053987, combined_string: invention_title: 오픈형 난로겸 온수공급 시스템 abstract: 본 발명은 본 발명은 오픈형 난방장치겸 온수공급 시스템에 관한 것으로, 가스버너에 의해 발생되는 불꽃에 의해 열전도율이 우수한 동파이프가열관을 통과하면서 가열하고 내부에 설치된 순환되어 보일러나 난방 파이프 역할을 수행하는 나선형 온수동관을 시속하게 뎁히는 것을 특징으로하는 다용도 고열효율 오픈형 난방장치겸 온수공급 시스템을 제공한다.이에 의해, 본 발명은 높은 열전도율을 보이는 동파이프를 이용하여 실내공기를 빠른 속도로 상승시킬 뿐만아니라, 완전연소로 클린 실내 환경이 가능토록하고 온수 또한 급속하게 가열하여 공급함으로써 열감절감 및 에너지 효율을 극대화할 수 있는 효과가 있다. 따라서 식물원, 온실, 가축사육장, 어류양식장에 사용할 수 있고, 또한 온수탱크를 설치하면 식당, 휴게소, 아파트 연립주택 실내 난로 겸 온수공급시스템으로 광범위한 용도로 편리하게 사용할 수 있다. claims: 동선으로 된 나선형 형상의 온수관으로 하부의 버너(130)에 대한 제어장치부(200)에 대한 제어에 따라 내부 온수 가열시, 순환되어 보일러나 난방 파이프 역할을 수행하는 나선형 온수동관(110); 및나선형 온수동관(110)의 상부에 동으로 된 파이프형가열관이 나선형을 따라 N개(N은 2 이상의 자연수)가 설치됨으로써, 나선형 온수관(110)에서 전달된 열원을 상부로 제공하는 역할을 수행할 뿐만 아니라, LNG 또는 LPG 가스를 이용해 버너(130)를 가열을 하면 동심원 형태의 나선형 온수관(110) 사이 공간인 관 공간부(110a)로 불꽃이 올라오면 불꽃에 의해 가열되어서 달궈져서 열 저장 공간으로 작용할 뿐만 아니라, 버너(130)에서 발생된 가스의 불완전 연소를 완전 연소로 바꿔주는 역할을 수행하는 동파이프가열관(120); 을 포함하는 것을 특징으로 하는 실내공기를 뎁히는 난로 겸 온수 공급 방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

354/1150 Row 354: application_number: 1020210053579, combined_string: invention_title: 침몰방지 시스템 abstract: 본 발명은 침몰방지 시스템으로서, 레이저 절단기, 플라즈마 절단기, 드릴링 머신 및 탭핑 머신을 이용하여 최적화된 선박 구조물을 제조한다. claims: 레이저 절단기, 플라즈마 절단기, 드릴링 머신 및 탭핑 머신을 이용하여 최적화된 선박 구조물을 제조하는, 침몰방지 시스에 있어서.상기 선박 구조물은,상기 선박의 격벽에 일정한 간격으로 다수 개 구비되어 상기 선박을 용이하게 인양하는 격벽고리;를 포함하고,상기 격벽고리는,가로 방향으로 위치하는 인양가이드;상기 인양가이드의 상단에 일정한 거리를 가지며 직각으로 위치하고, 상단이 상기 선박의 격벽에 고정 연결되어 있는 상단고정부;상기 상단고정부의 하단에 고정 연결되어 있으며, '∩'와 같은 형상으로 형성되되 서로 마주보는 상단의 간격이 하단의 간격보다 넓은 너비를 갖는 형상으로 형성되고, 양단 중앙에는 상기 인양가이드가 관통 가능한 크기를 가지며 상기 인양가이드의 형상에 맞추어 형성된 관통홈이 형성되어 있으며, 양하단에는 원형의 체결홈이 형성되어 있는 고정고리부;원기둥의 형상으로 형성되며 외측면은 나선형의 홈이 형성되어 있고, 상기 고정고리부의 양하단에 형성된 상기 체결홈으로 삽입하여 위치하는 하단고정부; 및외측면은 상기 고정고리부의 상기 체결홈보다 넓은 너비로 형성되되 각진 형상으로 형성되고, 비어 있는 내측면은 상기 하단고정부가 삽입 가능한 너비와 형상으로 형성되되, 상기 하단고정부의 외측면과 대응되도록 나선형의 돌기가 형성되어 있고, 상기 하단고정부의 외측면에 형성된 나선형의 홈을 따라 맞닿아 회전하는 회전고정부;를 포함하되,,상기 선박 구조물은,상기 선박의 양측 및 후방에 일정한 간격으로 다수 개 마련되며, 부력을 발생시키고, 상기 선박의 기울기에 따라 부력을 다르게 발생시키는 에어백;을 더 포함하고,상기 선박 구조물은,내부가 비어 있는 직육면체의 형상으로 형성되며, 일단면이 개폐 가능하도록 구성되어 에어백 또는 히팅부를 비어 있는 내부에 내장하여 보관하고, 상기 선박의 내측면 또는 외측면에 고정 가능한 후면으로 형성되는 케이스부;를 포함하고,상기 케이스부는,하나의 일측면이 제거된 육면체의 형상으로 형성되며 내부가 비어 있도록 형성된 내장보관부; 및일단이 상기 내장보관부의 일측면이 제거된 하단에 회전 가능하도록 연결 고정되어 있으며, 상하로 회전 구동하여 상기 내장보관부의 일측면을 개폐하는 회전개폐부;를 포함하고,상기 내장보관부는,내측면 일단에 적어도 하나 마련되어 있으며, 상기 에어백 또는 상기 히팅부를 고정시키는 내측고정부;내측면 양단에 마련되어 있으며, 상하로 회전 구동하는 상기 회전개폐부를 지지하도록 수축 및 이완 구동하고, 상기 회전개폐부가 상단 방향으로 구동하여 닫히는 경우 수축하고, 상기 회전개폐부가 하단 방향으로 구동하여 열리는 경우 이완하는 개폐지지부;하나의 일측면이 제거된 입구의 외곽 부분으로 돌출되어 형성되고, 외측면 상단 중앙으로부터 내측면 상단 중앙으로 관통한 채 위치하는 상단잠금부가 구비된 외곽돌출부; 및상기 외곽돌출부의 일측면 하단에 마련되어 있으며, 상기 회전개폐부와 고정 연결되고 상기 회전개폐부의 회전 구동을 가능하게 하는 회전연결부;를 포함하고,상기 회전개폐부는,상기 내장보관부 측을 향하는 타단면에 잠금모듈이 마련되어 있고,상기 잠금모듈은,내부가 비어 있는 'П'와 같은 형상으로 형성되며, 양하단은 상기 회전개폐부의 타단면과 맞닿을 수 있도록 직각으로 굽어지게 형성되고, 직각으로 형성된 양하단에 일정한 간격으로 원형의 고정홈이 형성되어 있으며 상기 고정홈으로 너트가 삽입하여 타단면에 고정 연결되는 잠금보호부; 및상기 잠금보호부의 내측에 위치하며, 상기 외곽돌출부에 구비된 상단잠금부와 맞닿아 고정되도록 형성되고, 상기 상단잠금부가 외측면으로부터 내측면 방향으로 외부의 압력에 의하여 이동하는 경우, 하단으로 이동하여 잠금을 해제하는 하단잠금부;를 포함하고,상기 케이스부는,외측면에 마련되어 있는 탄성모듈을 포함하고,상기 탄성모듈은,상기 케이스부의 모서리에 체결되는 중앙프레임;상기 선박에 충격을 주는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 상기 케이스부의 진행 방향에 대응하여 회동 가능한 다수의 합성수지재로 형성되고, 상기 중앙프레임의 전면에 결속되는 회전롤러;상기 각 회전롤러의 중앙에 길이 방향으로 관통 삽입하여 고정되고, 상기 회전롤러를 지지하며 상기 회전롤러의 원활한 회동을 도모하는 롤러지지부;상기 중앙프레임의 상, 하부 내측에 삽입되며, 상기 케이스부의 충돌 시 상기 회전롤러에 가해진 압력에 따라 수축 또는 팽창하여 상기 회전롤러의 수평 위치를 조절하는 탄성부;상기 중앙프레임의 상면 일측에 체결되며, 물체의 접근 여부를 감지하여 경고음을 발생하는 감지센서부; 및다수의 상기 중앙프레임을 관통하여 결속되는 고정스트랩;을 포함하고,상기 중앙프레임은,직각으로 형성되어 있는 벽이나 기둥의 구조물의 모서리 형상에 대응하여 안정적인 체결이 가능하도록 단면이 ㄴ자 형상으로 절곡되어 있는 제1 프레임;전면에 상기 회전롤러가 삽입되어 고정된 상기 롤러지지부가 결속됨과 동시에 상기 케이스부가 바다에 존재하여 상기 선박에 충격을 가하는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 상기 케이스부에 가해지는 충격을 완화하는 완충 공간을 형성하도록 상기 제1 프레임의 전면 상, 하단에 각각 외향 돌출 성형되어 있는 W 형상의 제2 프레임; 및 전면에 상기 회전롤러가 삽입되어 고정된 상기 롤러지지부가 결속됨과 동시에 상기 케이스부가 바다에 존재하여 상기 선박에 충격을 가하는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 상기 케이스부에 가해지는 충격을 완화하는 완충 공간을 형성하도록 상기 제1 프레임의 전면 상, 하단에 각각 외향 돌출 성형되어 있는 W 형상의 제3 프레임;을 포함하고,상기 제1 프레임은,상기 중앙프레임 간의 결속력을 향상시키는 상기 고정스트랩이 관통하도록 전면 상, 하부에 장공형의 스트랩고정홈이 천공되어 있고,상기 제1 프레임은,상기 스트랩고정홈과 나사의 결속에 의해 단일의 상기 중앙 프레임이 상기 케이스부의 모서리에 체결되도록 상기 스트랩고정홈 사이에 천공홈이 각각 천공되어 있고,상기 제2 프레임은,상면 일측에 상향 돌출 성형되어 있으며, 물체의 접근 여부를 감지하여 경고음을 발생하는 상기 감지센서부가 상기 중앙프레임의 상부에 체결되도록 체결홈이 형성되어 있고,상기 나사는,나사삽입홈에 삽결되어 상기 탄성모듈이 상기 케이스부의 외측면에 안정적으로 체결되고,상기 제2 프레임은,저면에 장방형의 제2 프레임 고정부와 하단고정부가 각각 함몰 성형되어 있어 상기 롤러지지부의 상, 하단부가 삽입하여 고정되고, 삽결된 상기 롤러지지부의 원활한 수평 이동을 도모하고,상기 제3 프레임은,상면에 장방형의 제2 프레임 고정부와 하단고정부가 각각 함몰 성형되어 있어 상기 롤러지지부의 상, 하단부가 삽입하여 고정되고, 삽결된 상기 롤러지지부의 원활한 수평 이동을 도모하고,상기 제2 프레임 고정부는,일측에 상기 케이스부가 바다에 존재하여 상기 선박에 충격을 가하는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 수축 또는 팽창하는 상기 탄성부가 상기 중앙프레임의 내측에 삽입 고정되는 탄성체가 함몰 성형되어 있고,상기 프레임 고정부는,타측에 상기 하단고정부와 상이하게 상기 제2 프레임의 전면으로부터 중심축의 상단이 삽입 고정 가능하도록 개방되어 있고,상기 제2 프레임 고정부는,개방되어 있는 개방면의 내측에 프레임보호부가 내향 돌출 성형되어 있어 삽결된 상기 중심축의 상단이 이탈하는 것을 방지하고,상기 회전롤러는,상기 케이스부가 바다에 존재하여 상기 선박에 충격을 줄 수 있는 일정 무게 및 일정 부피 이상을 갖는 이물질과의 충돌 시 상기 케이스부의 진행 방향에 대응하여 회동함으로써 상기 케이스부와의 접촉 면적을 최소화하여 상기 케이스부에 가해지는 충격을 완화할 수 있도록 원통형으로 성형되어 있고,상기 회전롤러는,상기 롤러지지부가 삽입 고정되도록 상면 중앙에 길이 방향으로 관통홈이 천공되어 있고,상기 감지센서부는,물체의 접근 여부를 감지할 수 있는 감지센서를 포함하고,상기 감지센서부는,일측에 작동 유무를 제어하는 것이 가능한 스위치가 형성되어 있고,상기 고정스트랩은,상기 중앙프레임의 상기 제1 프레임에 천공되어 있는 상기 스트랩고정홈에 삽입 고정되어 다수의 상기 중앙프레임을 결속하고,상기 고정스트랩은,일체화된 다수의 상기 중앙프레임을 상기 케이스부의 외측면에 안정적으로 고정 가능하도록 양측 단부의 전, 후면에 상호 부착 가능한 고정부착부가 각각 구비되어 있고,상기 케이스부의 모서기에 단일의 상기 중앙프레임이 체결되는 경우,상기 제1 프레임의 전면에 천공되어 있는 상기 천공홈에 상기 나사가 삽입 고정되어 상기 케이스부의 외측면에 결속되고,상기 롤러지지부는,상기 케이스부의 외측면에 체결된 상기 중앙프레임의 상기 제2 프레임 및 상기 제3 프레임의 사이에 상, 하단부가 삽입 고정되어 상기 중앙프레임의 전면에 결속되고,상기 롤러지지부는,하단부가 상기 제3 프레임의 상면에 함몰 성형되어 있는 상기 하단고정부에 먼저 삽입 고정된 후, 상단부가 상기 제2 프레임의 저면에 함몰 성형되어 있는 상기 제2 프레임 고정부의 개방된 일측면으로 삽입 고정되어 상기 중앙프레임의 전면에 결속되는, 침몰방지 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

355/1150 Row 355: application_number: 1020210046922, combined_string: invention_title: 어군 생태계의 이상 여부를 감지하기 위한 어군 생태계 모니터링 시스템 장치 및 그 동작 방법 abstract: 어군 생태계의 이상 여부를 감지하기 위한 어군 생태계 모니터링 시스템 장치 및 그 동작 방법이 개시된다. 본 발명은 SONAR(SOund Navigation And Ranging) 모듈이 탑재되어 있는 부이(buoy) 장치로부터, SONAR 모듈에 의해 촬영된 SONAR 이미지를 사전 설정된 획득 시간 간격으로 수신하고, SONAR 이미지들 각각을 어군 객체 식별 모델에 입력으로 인가하여, SONAR 이미지들 각각에서 어군 객체를 식별한 후, SONAR 이미지들 각각에서 식별된 어군 객체의 수를 기초로, 어군 생태계의 이상 여부를 판단하여, 어군 생태계의 이상이 있는 것으로 판단되면, 경고 메시지를 생성하여 관리자의 단말로 전송하는 어군 생태계 모니터링 시스템 장치 및 그 동작 방법에 대한 것이다. claims: 어군 생태계의 이상 여부를 감지하기 위한 어군 생태계 모니터링 시스템 장치에 있어서,수중에서 SONAR(SOund Navigation And Ranging) 이미지를 획득하기 위한 SONAR 모듈이 탑재되어 있는 부이(buoy) 장치로부터, 상기 SONAR 모듈에 의해 촬영된 SONAR 이미지를 매일 k(k는 2이상의 자연수임)개의 사전 설정된 획득 시간마다 수신함으로써, 매일 k개의 SONAR 이미지들을 획득하는 이미지 획득부;매일 k개의 SONAR 이미지들이 획득 완료될 때마다, k개의 SONAR 이미지들 각각을, 이미지에서 어군 객체를 식별하기 위한 사전 학습 완료된 어군 객체 식별 모델에 입력으로 인가하여, k개 SONAR 이미지들 각각에서 어군 객체를 식별하고, k개의 SONAR 이미지들 각각에서 식별된 어군 객체의 수를 성분으로 갖는 k차원의 객체 벡터를 생성한 후, k차원의 객체 벡터와 k차원의 객체 벡터가 생성된 날짜에 대한 정보를 서로 대응시켜 벡터 데이터베이스에 저장하는 벡터 생성부;상기 벡터 데이터베이스에 저장되어 있는 객체 벡터의 수를 확인하여 상기 벡터 데이터베이스에 저장되어 있는 객체 벡터의 수가 사전 설정된 기준 개수인 n(n은 3이상의 자연수임)개가 되면, 어군 생태계의 이상 여부를 판단하기 위한 판단 이벤트를 발생시키는 이벤트 발생부; 상기 판단 이벤트가 발생되면, 상기 벡터 데이터베이스에 저장되어 있는 n개의 객체 벡터들을 기초로, 어군 객체의 수가 감소 추세인지 여부를 판단하는 판단부;상기 n개의 객체 벡터들을 기초로, 어군 객체의 수에 대한 일별 변화 정도를 표상하는 변화 수치를 연산한 후, 상기 변화 수치를 사전 설정된 기준치와 비교하여 상기 변화 수치가 상기 기준치를 초과하는지 여부를 확인하는 수치 확인부; 및어군 객체의 수가 감소 추세인 것으로 판단되고, 상기 변화 수치가 사전 설정된 기준치를 초과하는 것으로 확인되는 경우, 어군 생태계에 이상이 있는 것으로 판단한 후, 어군 생태계에 이상이 있음을 지시하는 경고 메시지를 생성하여 관리자의 단말로 전송하는 메시지 전송부를 포함하는 어군 생태계 모니터링 시스템 장치.어군 생태계의 이상 여부를 감지하기 위한 어군 생태계 모니터링 시스템 장치의 동작 방법에 있어서,수중에서 SONAR(SOund Navigation And Ranging) 이미지를 획득하기 위한 SONAR 모듈이 탑재되어 있는 부이(buoy) 장치로부터, 상기 SONAR 모듈에 의해 촬영된 SONAR 이미지를 매일 k(k는 2이상의 자연수임)개의 사전 설정된 획득 시간마다 수신함으로써, 매일 k개의 SONAR 이미지들을 획득하는 단계;매일 k개의 SONAR 이미지들이 획득 완료될 때마다, k개의 SONAR 이미지들 각각을, 이미지에서 어군 객체를 식별하기 위한 사전 학습 완료된 어군 객체 식별 모델에 입력으로 인가하여, k개 SONAR 이미지들 각각에서 어군 객체를 식별하고, k개의 SONAR 이미지들 각각에서 식별된 어군 객체의 수를 성분으로 갖는 k차원의 객체 벡터를 생성한 후, k차원의 객체 벡터와 k차원의 객체 벡터가 생성된 날짜에 대한 정보를 서로 대응시켜 벡터 데이터베이스에 저장하는 단계;상기 벡터 데이터베이스에 저장되어 있는 객체 벡터의 수를 확인하여 상기 벡터 데이터베이스에 저장되어 있는 객체 벡터의 수가 사전 설정된 기준 개수인 n(n은 3이상의 자연수임)개가 되면, 어군 생태계의 이상 여부를 판단하기 위한 판단 이벤트를 발생시키는 단계; 상기 판단 이벤트가 발생되면, 상기 벡터 데이터베이스에 저장되어 있는 n개의 객체 벡터들을 기초로, 어군 객체의 수가 감소 추세인지 여부를 판단하는 단계;상기 n개의 객체 벡터들을 기초로, 어군 객체의 수에 대한 일별 변화 정도를 표상하는 변화 수치를 연산한 후, 상기 변화 수치를 사전 설정된 기준치와 비교하여 상기 변화 수치가 상기 기준치를 초과하는지 여부를 확인하는 단계; 및어군 객체의 수가 감소 추세인 것으로 판단되고, 상기 변화 수치가 사전 설정된 기준치를 초과하는 것으로 확인되는 경우, 어군 생태계에 이상이 있는 것으로 판단한 후, 어군 생태계에 이상이 있음을 지시하는 경고 메시지를 생성하여 관리자의 단말로 전송하는 단계를 포함하는 어군 생태계 모니터링 시스템 장치의 동작 방법.제6항 내지 제10항 중 어느 한 항의 방법을 컴퓨터와의 결합을 통해 실행시키기 위한 컴퓨터 프로그램을 기록한 컴퓨터 판독 가능 기록 매체.제6항 내지 제10항 중 어느 한 항의 방법을 컴퓨터와의 결합을 통해 실행시키기 위한 저장매체에 저장된 컴퓨터 프로그램., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

356/1150 Row 356: application_number: 1020200160427, combined_string: invention_title: 해상 무선 통신 시스템 및 그 방법 abstract: 본 발명은 해상 무선 통신 시스템 및 그 방법에 관한 것으로서, 부이, 어선용 단말 장치, 관리선박용 단말 장치 또는 육상 관제 센터 간에 무선 통신을 수행하는 해상 무선 통신 시스템에 있어서, 상기 부이에 설치되어 적어도 하나 이상의 센서를 이용한 센싱 정보, 자신의 식별 정보와 위치 정보를 제공하고, 어구 유실을 포함한 이벤트 상황 발생시 통신 연결성을 보장하는 통신옵션을 변경하는 통신 모듈; 및 상기 어선용 단말 장치와 관리 선박용 단말 장치에 각각 설치되고, 적어도 하나 이상의 부이 및 육상 관제 센터와 LoRa(Long Range Low Power) 기반의 통신망을 통해 통신을 수행하여 어선 및 어구의 위치와 상황, 유실 어구의 위치를 포함한 각종 어업 정보를 제공하며, 정상 상황에서의 통신 옵션과 이벤트 상황에서의 통신 옵션을 다르게 설정하여 통신 연결 기능을 수행하는 게이트웨이 장치를 포함하되, 상기 부이의 통신 모듈, 어선 및 관리 선박에 설치된 게이트웨이 장치는 저전력 장거리 통신을 위해 상용(Public) 로라망을 통해 메인 통신 채널을 형성하고, 전파 음영 지역에서 상기 상용 로라망과의 메인 통신 연결을 해제한 후 사설 로라망(Private LoRa)을 통해 서브 통신 채널을 형성하는 것이다. claims: 부이, 어선용 단말 장치, 관리선박용 단말 장치 또는 육상 관제 센터 간에 무선 통신을 수행하는 해상 무선 통신 시스템에 있어서,상기 부이에 설치되어 적어도 하나 이상의 센서를 이용한 센싱 정보, 자신의 식별 정보와 위치 정보를 제공하고, 어구 유실을 포함한 이벤트 상황 발생시 통신 연결성을 보장하는 통신옵션을 변경하는 통신 모듈; 및상기 어선용 단말 장치와 관리 선박용 단말 장치에 각각 설치되고, 적어도 하나 이상의 부이 및 육상 관제 센터와 LoRa(Long Range Low Power) 기반의 통신망을 통해 통신을 수행하여 어선 및 어구의 위치와 상황, 유실 어구의 위치를 포함한 각종 어업 정보를 제공하며, 정상 상황에서의 통신 옵션과 이벤트 상황에서의 통신 옵션을 다르게 설정하여 통신 연결 기능을 수행하는 게이트웨이 장치를 포함하되,상기 부이의 통신 모듈, 어선 및 관리 선박에 설치된 게이트웨이 장치는 저전력 장거리 통신을 위해 상용(Public) 로라망을 통해 메인 통신 채널을 형성하고, 전파 음영 지역에서 상기 상용 로라망과의 메인 통신 연결을 해제한 후 사설 로라망(Private LoRa)을 통해 서브 통신 채널을 형성하고,상기 게이트웨이 장치는, 상기 부이의 통신 품질에 기반하여 부이별 적용되는 기준 확산계수를 설정하고, 상기 이벤트 상황 발생시 상기 기준 확산 계수보다 높은 확산계수로 변경하여 상기 부이와 통신을 수행하도록 통신 옵션을 변경하는 것인, 해상 무선 통신 시스템.부이, 어선용 단말 장치, 관리 선박용 단말 장치 또는 육상 관제 센터 간에 무선 통신을 수행하는 해상 무선 통신 방법에 있어서,a) 상기 어선용 단말 장치 또는 관리 선박용 단말 장치에 설치된 게이트웨이 장치는 상기 부이의 통신 품질에 기반하여 부이별 적용되는 기준 확산계수를 설정하는 단계;b) 상기 설정된 기준 확산계수를 이용하여 상기 부이와 통신을 수행하여, 상기 부이로부터 적어도 하나 이상의 센서를 이용한 센싱 정보, 자신의 식별 정보와 위치 정보를 수신하는 단계; 및 c) 상기 부이로부터 수신한 정보를 분석하여 상기 부이의 도난 또는 유실을 포함한 이벤트 상황이 감지되면, 상기 기준 확산 계수보다 높은 확산계수로 변경하여 상기 부이와 통신을 수행하는 단계를 포함하는 것인, 해상 무선 통신 방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

357/1150 Row 357: application_number: 1020200160489, combined_string: invention_title: 어업 도구의 유실 모니터링 시스템 및 그 방법 abstract: 본 발명은 어업 도구의 유실 모니터링 시스템 및 그 방법에 관한 것으로서, 수중에 설치되는 어구에 탈착 가능하게 설치되고, 적어도 하나 이상의 센서를 이용하여 센싱 정보를 제공하며, 자신의 식별 정보와 위치 정보를 제공하는 부이(Buoy); 적어도 하나 이상의 부이에 자신의 어구 식별 정보를 등록하고, 상기 부이와 통신하여 자신의 부이 위치 정보를 확인하며, 자신의 어선 식별 정보, 자기 어선 위치 정보, 자기 어구 식별 정보 및 자기 부이 위치 정보를 포함한 어선 정보를 제공하는 어선용 단말장치; 및 기 설정된 관할 지역 내 어구 또는 어선에 대한 관리 기능을 수행하고, 상기 어선용 단말장치 또는 부이와 통신망을 통해 정보를 송수신하여, 상기 부이 위치 정보를 이용하여 부이 속도를 측정하고, 측정된 부이 속도가 기 설정된 기준 속도 범위를 벗어나면 예비 부이 유실 정보를 발생하고, 상기 예비 부이 유실 정보의 발생에 따라 상기 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경을 벗어난 경우에 최종 부이 유실 정보를 제공하는 육상 관제 센터를 포함하는 시스템일 수 있다. claims: 수중에 설치되는 어구에 탈착 가능하게 설치되고, 적어도 하나 이상의 센서를 이용하여 센싱 정보를 제공하며, 자신의 식별 정보와 위치 정보를 제공하는 부이(Buoy);적어도 하나 이상의 부이에 자신의 어구 식별 정보를 등록하고, 상기 부이와 통신하여 자신의 부이 위치 정보를 확인하며, 자신의 어선 식별 정보, 자기 어선 위치 정보, 자기 어구 식별 정보 및 자기 부이 위치 정보를 포함한 어선 정보를 제공하는 어선용 단말장치; 및기 설정된 관할 지역 내 어구 또는 어선에 대한 관리 기능을 수행하고, 상기 어선용 단말장치 또는 부이와 통신망을 통해 정보를 송수신하여, 상기 부이로부터 기설정시간 동안 수중 온도 정보와 수상 온도 정보를 포함한 센싱 정보를 수집하고, 상기 수중 온도 정보와 수상 온도 정보의 각 평균값의 차이가 기설정된 오차범위를 벗어나는 경우에 상기 부이 위치 정보를 이용하여 부이 속도를 측정하고, 측정된 부이 속도가 기 설정된 기준 속도 범위를 벗어나면 예비 부이 유실 정보를 발생하고, 상기 예비 부이 유실 정보의 발생에 따라 상기 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경을 벗어난 경우에 부이 또는 어구의 유실 정보를 제공하는 육상 관제 센터를 포함하되,상기 육상 관제 센터는, 상기 예비 부이 유실 정보가 발생된 이후에, 상기 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경 이내인 경우에 상기 예비 부이 유실 정보의 발생을 해제하고, 조류에 따른 부이 위치 변화 정보를 제공하는 것인, 어업 도구의 유실 모니터링 시스템. 부이를 이용하여 부이 또는 어구의 유실을 모니터링하기 위한 어업 도구의 유실 모니터링 방법에 있어서, a) 기 설정된 관할 지역 내 부이 위치 정보와 어선 정보를 주기적으로 획득하여 육상에서 부이 또는 어구의 유실 여부를 감지하여 알려주는 육상 관제 센터는 적어도 하나 이상의 부이에 자신의 어구 식별 정보를 등록 및 관리하는 어선용 단말 장치, 관할 지역 내 어업 지도 또는 어업 단속을 포함한 어업 관리 기능을 수행하면서 부이 또는 어구의 유실 정보에 따라 어구 스캐닝을 통해 유실된 어구를 회수하는 동작을 수행하기 위해 관리 선박에 설치된 관리 선박용 단말 장치, 및 어구에 설치되어 적어도 하나 이상의 센서를 이용한 센싱 정보를 제공하는 부이와 LoRa 기반의 통신 채널을 형성하는 단계; b) 상기 육상 관제 센터는 상기 통신 채널을 통해 부이 위치 정보 또는 센싱 정보를 주기적으로 획득하고, 기 설정된 시간 동안에 상기 부이로부터 수중 온도 정보와 수상 온도 정보를 포함한 센싱 정보를 수집하여, 상기 수중 온도 정보와 수상 온도 정보의 각 평균값의 차이가 기설정된 오차범위를 벗어나는 경우에, 상기 부이 위치 정보를 이용하여 부이 속도를 측정하여, 상기 측정된 부이 속도가 기 설정된 기준 속도 범위를 벗어나면 예비 부이 유실 정보를 발생하는 단계; 및 c) 상기 육상 관제 센터는 상기 예비 부이 유실 정보의 발생에 따라 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경을 벗어난 경우에 부이 또는 어구의 유실 정보를 생성하여 상기 어선용 단말 장치 또는 상기 관리 선박용 단말 장치로 전송하는 단계를 포함하되,상기 c) 단계는, 상기 예비 부이 유실 정보가 발생된 이후에, 상기 어선 위치 정보와 부이 위치 정보를 이용하여 어선과 부이간의 거리가 기 설정된 어구 작업 반경 이내인 경우에 상기 예비 부이 유실 정보의 발생을 해제하고, 조류에 따른 부이 위치 변화 정보를 제공하는 것인, 어업 도구의 유실 모니터링 방법., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

358/1150 Row 358: application_number: 1020200158475, combined_string: invention_title: 어선용 웨어러블 선원 안전관리 시스템 abstract: 본 발명은 어선의 운항시나 조업시 발생할 수 있는 선원들의 안전사고를 예방하기 위한 안전관리 시스템에 관한 것으로서, 더욱 상세하게는 어선의 운항으로부터 조업작업에 이르기까지의 전과정에 걸쳐 사고의 위험에 처한 선원 당사자 또는 이를 발견한 다른 선원이 자신의 신체에 착용한 웨어러블 송수신기의 신호버튼을 이용하여 어선의 중앙통제장치로 사고위험신호를 즉시 전송시킬 수 있도록 하고, 상기 중앙통제장치에서는 선원들이 바다에 빠지는 안전사고가 주로 발생하는 운항모드와 선원들이 조업기계에 의하여 부상을 당하는 안전사고가 주로 발생하는 조업모드에 맞추어, 운항모드시에는 어선의 운항속도를 감속시키거나 어선의 운항을 일시 정지시키는 한편, 조업모드시에는 특정 조업기계 또는 갑판상에 설치된 모든 조업기계의 작동을 일시 중지시킨 다음, 나머지 선원들에게 사고위험의 발생상황을 일괄적으로 신속히 전달시키는 관리조치를 수행함에 따라, 안전사고에 의한 인명피해가 발생하기 이전에 해당 피해를 유발시키는 가장 큰 위험요소를 어선 내부에서 선원들과 중앙통제장치간의 직접적이며 빠른 정보교환을 거쳐 신속하고 안전하게 무마시킬 수 있는 동시에, 사고위험신호를 전송한 선원 이외의 다른 모든 선원들이 즉시 집결하여 현장수습과 후속처리에 협력함으로서 정상작업으로의 조기복귀가 가능토록 한 어선용 웨어러블 선원 안전관리 시스템에 관한 것이다. claims: 어선(10)의 운항으로부터 조업작업을 수행하는 과정에 이르기까지 어선(10)에 승선한 선원의 안전사고를 예방하는 어선용 안전관리 시스템에 있어서,사고의 위험에 처한 선원 당사자 또는 상기 선원을 발견한 다른 선원이 자신의 신체에 착용한 웨어러블(Wearable) 송수신기(11)의 신호버튼(15)을 이용하여 사고위험신호를 어선(10)의 중앙통제장치(20)로 전송시키는 신호전송단계와, 어선(10)의 중앙통제장치(20)로 수신된 사고위험신호를 선원별로 부여된 송수신기(11)의 고유번호에 맞추어 구분하는 신호판단단계와, 어선(10)의 운항모드시에는 중앙통제장치(20)에서 어선(10)의 운항속도를 감속시키거나 어선(10)의 운항을 정지시키고, 어선(10)의 조업모드시에는 중앙통제장치(20)에서 갑판(2)상에 설치된 조업기계의 작동을 중지시키는 관리조치단계를 포함하여서 이루어지며,상기 운항모드시의 관리조치단계에서는 중앙통제장치(20)에서 어선(10)의 운항속도를 감속시키거나 어선(10)의 운항을 정지시키는 단계를 거친 직후, 상기 신호판단단계에서 사고위험신호가 발신된 것으로 판단된 선원의 송수신기(11)를 제외한 나머지 선원의 송수신기(11)로 알람신호를 송출하는 단계와, 알람신호를 수신받은 선원들에 의한 후속처리 이후의 시스템 리셋 단계가 추가로 수행되는 것을 특징으로 하는 어선용 웨어러블 선원 안전관리 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

359/1150 Row 359: application_number: 1020200125213, combined_string: invention_title: 생태교란 어종의 생태 조사 및 포획시스템 abstract: 본 발명은 댐이나 저수지 등 생태교란 어종의 서식이 예상되는 구역에 배치되어, 상기 구역에 수중을 원격으로 탐사하여 생태 교란 어종의 생태 여부와 생태 현황의 실시간 분석을 도모하여, 효율성 높은 생태교란 어종의 퇴치가 가능하도록 하는 생태교란 어종의 생태 조사 및 포획시스템에 관한 것으로,본 발명에서는 수면에 부양된 탐색정에 탑재되어, 탐색지역의 수중에 초음파를 조사하여 수중지형과 수중에 생태하는 어군들이 표식된 초음파 탐색지역 영상을 수득하는 초음파 어군 탐지부와; 상기 초음파 어군 탐색부를 통해 탐색되는 초음파 영상을 분석하여 어군 패턴을 추출하고 상기 추출된 어군 패턴들을 분석하여서, 생태교란 어종의 군집구역을 판독하는 생태교란 어종 군집구역 판독부와; 상기 생태교란 어종 군집구역 판독부에 의해 판독된 생태교란 어종 군집구역에 입수하여 탑재된 카메라 모듈을 통해 해당 군집구역의 지형과 생태교란 어종을 촬영하여서, 생태교란 어종 군집구역의 생태 영상을 수득하는 입수형 군집 영상 수득부를 포함하여 구성된 것을 특징으로 한다. claims: 수면에 부양된 탐색정에 탑재되어, 탐색지역의 수중에 초음파를 조사하여 수중지형과 수중에 생태하는 어군들이 표식된 초음파 탐색지역 영상을 수득하는 초음파 어군 탐지부와; 상기 초음파 어군 탐색부를 통해 탐색되는 초음파 영상을 분석하여 어군 패턴을 추출하고 상기 추출된 어군 패턴들을 분석하여서, 생태교란 어종의 군집구역을 판독하는 생태교란 어종 군집구역 판독부와; 상기 생태교란 어종 군집구역 판독부에 의해 판독된 생태교란 어종 군집구역에 입수하여 탑재된 카메라 모듈을 통해 해당 군집구역의 지형과 생태교란 어종을 촬영하여서, 생태교란 어종 군집구역의 생태 영상을 수득하는 입수형 군집 영상 수득부를 포함하고,상기 입수형 군집 영상 수득부는 수밀형 함체와; 상기 수밀형 함체에 수밀구조로 배치되어 수중 영상을 수득하는 카메라 모듈과; 상기 수밀형 함체에 탑재되어 수밀형 함체의 유형에 따른 추력을 생성하는 추력모듈과; 상기 수밀형 함체에 탑재되어, 초음파 어군 탐지부를 통해 조사되는 초음파에 의해 수중에서의 위치가 식별되도록 하는 초음파 식별모듈을 포함하되,상기 초음파 식별모듈은, 수밀형 함체의 외부에 노출되는 팽창튜브와; 상기 팽창튜브를 탄지하여 팽창되도록 하는 탄지 스프링과; 상기 탄지 스프링과 결속된 와이어를 와인딩, 또는 언와인딩하여 탄지 스프링의 수축상태를 조절하여 팽창튜브의 부피를 조절하는 권취부재를 포함하여 구성된 부피 증감형인 것을 특징으로 하는 생태교란 어종의 생태 조사 및 포획시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

360/1150 Row 360: application_number: 1020200108976, combined_string: invention_title: 수상드론을 이용한 양식장 감시 방법 abstract: 본 발명에 따른 수상드론을 이용한 양식장 감시 방법은, 양식장 주위를 운항하며 영상을 획득하는 제1단계와, 획득한 영상 데이터를 임시 저장하는 제2단계와, 기준 이미지와 현재 프레임 이미지를 비교하여 그 변화량을 산출하는 제3단계와, 상기 변화량이 임계값보다 큰 경우 이상 상태로 판단하여 단말에 알람을 송출하는 제4단계와, 이상이 감지된 프레임의 일정 프레임 이전부터 영상 데이터를 영구 저장하는 제5단계를 포함하여 구성된다. claims: 수상드론을 이용한 양식장 감시 방법으로서,양식장 주위를 운항하며 영상을 획득하는 단계와,획득한 영상 데이터를 임시 저장하는 단계와,기준 이미지와 현재 프레임 이미지를 비교하여 그 변화량을 산출하는 단계와,상기 변화량이 임계값보다 큰 경우 이상 상태로 판단하여 단말에 알람을 송출하는 단계와,이상이 감지된 프레임의 일정 프레임 이전부터 영상 데이터를 영구 저장하는 단계와,상기 수상드론의 제1센서부가 측정한 수온 및 제2센서부가 측정한 대기 환경 데이터를 입력받아 목표 수심의 수온을 추정하는 단계를 포함하며,상기 제1센서부는 상기 수상드론의 선저부에 위치하며, 상기 제2센서부는 해수면 위로 노출되도록 상기 수상드론의 선체부에 설치되며,상기 목표 수심 수온 추정 단계는, 상기 제1센서부에 의해 측정된 센서 위치 수심의 수온과 상기 제2센서부에 의해 측정된 대기 온도, 조도, 습도, 풍량 및 각 목표 수심의 수온과 측정 시각을 가지고 학습된 인공지능 신경망을 이용하는 것인수상드론을 이용한 양식장 감시 방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

361/1150 Row 361: application_number: 1020200108148, combined_string: invention_title: 플랑크톤 채집장치 abstract: 본 발명은 플랑크톤 채취장치에 관한 것으로, 유체가 통과되도록 유로가 상하로 관통되는 본체와, 상기 유로의 내부에 상하로 길이를 갖도록 설치되는 지지대 및, 하부의 체결관이 상기 지지대의 측면을 감싸는 상태로 결합되고, 다수의 메쉬홀이 형성된 상부의 메쉬망이 상기 지지대의 측면을 감싸는 채집부를 포함하며, 상기 메쉬망은 상기 본체가 수중으로 하강시 수압에 의해 상단이 상기 지지대의 측면 방향으로 축소되고, 상기 본체가 수중에서 상승시 수압에 의해 상단이 상기 지지대의 측면과 이격되는 방향으로 확장되는 것을 특징으로 한다. claims: 유체가 통과되도록 유로가 상하로 관통되는 본체;상기 유로의 내부에 상하로 길이를 갖도록 설치되는 지지대; 및하부의 체결관이 상기 지지대의 측면을 감싸는 상태로 결합되고, 다수의 메쉬홀이 형성된 상부의 메쉬망이 상기 지지대의 측면을 감싸는 채집부;를 포함하며,상기 메쉬망은 상기 본체가 수중으로 하강시 수압에 의해 상단이 상기 지지대의 측면 방향으로 축소되고, 상기 본체가 수중에서 상승시 수압에 의해 상단이 상기 지지대의 측면과 이격되는 방향으로 확장되는 것을 특징으로 하는 플랑크톤 채집장치., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

362/1150 Row 362: application_number: 1020200100373, combined_string: invention_title: 스마트양식장을 위한 방법 및 장치 abstract: 본 명세서는 스마트양식을 위한 제어장치의 스마트양식 시스템을 제어하는 제어방법에 있어서, 사용자로부터 수신받은 입력값을 통해, 수조에 대응하는 ID(identification) 별로 사육정보를 등록하는 단계; 상기 등록된 ID와 대응되는 수조로부터, 상기 수조에 포함된 센서를 통해 생성되는 제1 센싱데이터를 수신하는 단계; 상기 제1 센싱데이터를 이용하여, 상기 수조의 상태를 모니터링하는 단계; 상기 모니터링의 결과값을 디스플레이부에 디스플레이하는 단계; 상기 모니터링을 통해, 제어 이벤트를 감지하는 단계; 및 상기 제어 이벤트에 근거하여, 상기 수조로, 상기 수조의 동작모듈을 제어하기 위한 제1 제어메시지를 전송하는 단계; 를 포함하며, 상기 센서는 수온 센서, 용존산소 센서, ph 센서, 수위 센서 및 먹이활동성 센서를 포함할 수 있다. claims: 제어장치가 스마트 양식장을 제어하는 제어방법에 있어서,사용자로부터 수신받은 입력값을 통해, 수조에 대응하는 ID(identification) 별로 사육정보를 등록하는 단계;상기 등록된 ID와 대응되는 수조로부터, 상기 수조에 포함된 센서를 통해 생성되는 제1 센싱데이터를 수신하는 단계;상기 제1 센싱데이터를 이용하여, 상기 수조의 상태를 모니터링하는 단계;상기 모니터링의 결과값을 디스플레이부에 디스플레이하는 단계;상기 모니터링을 통해, 제어 이벤트를 감지하는 단계;상기 제어 이벤트에 근거하여, 상기 수조로, 상기 수조의 동작모듈을 제어하기 위한 제1 제어메시지를 전송하는 단계;상기 제어 이벤트가 먹이 공급을 지시하는 이벤트인 경우, 먹이 공급부 및 상기 수조로 상기 먹이 공급을 지시하는 이벤트와 관련된 수조에 먹이를 공급하기 위한 제2 제어메시지를 전송하는 단계;상기 수조로부터, 먹이활동성 센서로부터 생성된 센싱데이터가 포함된 제2 센싱데이터를 수신하는 단계;상기 제2 센싱데이터를 이용하여, 상기 수조의 먹이활동성을 측정하는 단계; 및상기 측정된 먹이활동성에 근거하여, 상기 수조로 제3 제어메시지를 전송하는 단계;를 포함하며,상기 센서는 수온 센서, 용존산소 센서, ph 센서, 수위 센서 및 상기 먹이활동성 센서를 포함하고,상기 먹이활동성 센서는 상기 수조의 수면 상에 부유하여, 상기 수면의 움직임을 측정하며,상기 제2 센싱데이터는 상기 먹이활동성 센서를 통해, 생성되는 3축 가속도의 벡터값을 포함하고,상기 수조의 먹이활동성을 측정하는 단계는기설정된 1) 상기 센싱데이터의 센싱주기, 및 2) 상기 센싱데이터의 참조갯수에 근거하여:상기 먹이가 공급되기 전에, 센싱된 상기 3축 가속도의 벡터값에 근거하여, 재귀적으로 이동평균의 기준값을 계산하는 단계;상기 먹이가 공급된 이후에, 센싱된 상기 3축 가속도의 벡터값에 근거하여, 재귀적으로 이동평균의 현재값을 계산하는 단계; 및상기 이동평균의 기준값 및 상기 이동평균의 현재값에 근거하여, 상기 먹이활동성을 측정하는 단계;를 포함하는, 제어방법.스마트 양식장을 제어하는 제어장치에 있어서,메모리;송수신부;디스플레이부; 및상기 메모리, 상기 송수신부 및 상기 디스플레이부를 기능적으로 제어하는 프로세서;를 포함하고,상기 프로세서는사용자로부터 수신받은 입력값을 통해, 수조에 대응하는 ID(identification) 별로 사육정보를 상기 메모리에 등록하고,상기 송수신부를 통해, 상기 등록된 ID와 대응되는 수조로부터, 상기 수조에 포함된 센서를 통해 생성되는 제1 센싱데이터를 수신하며,상기 제1 센싱데이터를 이용하여, 상기 수조의 상태를 모니터링하고,상기 모니터링의 결과값을 상기 디스플레이부에 디스플레이하고,상기 모니터링을 통해, 제어 이벤트를 감지하며,상기 송수신부를 통해, 상기 제어 이벤트에 근거하여, 상기 수조로, 상기 수조의 동작모듈을 제어하기 위한 제1 제어메시지를 전송하며,상기 제어 이벤트가 먹이 공급을 지시하는 이벤트인 경우, 먹이 공급부 및 상기 수조로 상기 먹이 공급을 지시하는 이벤트와 관련된 수조에 먹이를 공급하기 위한 제2 제어메시지를 전송하고,상기 수조로부터, 먹이활동성 센서로부터 생성된 센싱데이터가 포함된 제2 센싱데이터를 수신하며,상기 제2 센싱데이터를 이용하여, 상기 수조의 먹이활동성을 측정하고,상기 측정된 먹이활동성에 근거하여, 상기 수조로 제3 제어메시지를 전송하며,상기 센서는 수온 센서, 용존산소 센서, ph 센서, 수위 센서 및 상기 먹이활동성 센서를 포함하고,상기 먹이활동성 센서는 상기 수조의 수면 상에 부유하여, 상기 수면의 움직임을 측정하며,상기 제2 센싱데이터는 상기 먹이활동성 센서를 통해, 생성되는 3축 가속도의 벡터값을 포함하고,상기 프로세서는상기 먹이활동성을 측정하기 위해,기설정된 1) 상기 센싱데이터의 센싱주기, 및 2) 상기 센싱데이터의 참조갯수에 근거하여:상기 먹이가 공급되기 전에, 센싱된 상기 3축 가속도의 벡터값에 근거하여, 재귀적으로 이동평균의 기준값을 계산하고,상기 먹이가 공급된 이후에, 센싱된 상기 3축 가속도의 벡터값에 근거하여, 재귀적으로 이동평균의 현재값을 계산하며,상기 이동평균의 기준값 및 상기 이동평균의 현재값에 근거하여, 상기 먹이활동성을 측정하는, 제어장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

363/1150 Row 363: application_number: 1020200077973, combined_string: invention_title: 빅데이터를 이용한 인공지능 기술 기반 이상징후 표적 감지 방법 및 그 시스템 abstract: 본 개시(disclosure)의 다양한 실시 예들에 따르면, 바다를 항해하는 표적의 이상징후를 감지하기 위한 이상징후표적 감지 시스템은, 항해 표적을 탐지하여 항해 표적 정보를 출력하는 레이더, 서버로부터 미리 등록된 표적들에 대한 저장 표적 정보를 선박식별장치에게 전달하는 서버, 상기 항해 표적 정보와 상기 저장 표적 정보를 융합하여 상기 항해 표적의 이상징후 여부를 결정하고, 상기 이상징후 여부를 표시하는 선박식별장치를 포함할 수 있다. claims: 바다를 항해하는 표적의 이상징후를 감지하기 위한 이상징후표적 감지 시스템에 있어서,항해 표적을 탐지하여 항해 표적 정보를 출력하는 레이더;미리 등록된 표적들에 대한 저장 표적 정보를 선박식별장치에게 전달하는 서버; 및상기 레이더로부터 상기 항해 표적 정보가 수신될 때마다 상기 항해 표적 정보의 수신 시간 및 상기 표적의 표적 위치 정보를 획득하고, 상기 표적 위치 정보를 상기 수신 시간에 동기화시켜 상기 표적의 예측 위치 정보를 획득하고, 상기 예측 위치 정보와 상기 저장 표적 정보를 융합하여 선박의 위치 정보, 크기 정보, 이동 경로 정보, 예측 경로 정보 중 적어도 하나 이상을 포함하는 빅데이터 분석 정보를 생성하고, 상기 빅데이터 분석 정보와 상기 항해 표적 정보를 비교하고, 상기 비교에 기반하여 상기 항해 표적의 이상징후 여부를 결정하고, 상기 이상징후 여부를 표시하는 선박식별장치;를 포함하고,상기 선박식별장치는, 상기 항해 표적이 상기 저장 표적 정보가 포함하는 기등록된 표적들에 포함되어 있는지 여부를 결정하고, 포함되어 있으면, 상기 항해 표적 정보를 상기 저장 표적 정보와 융합하고, 포함되어 있지 않으면, 상기 항해 표적을 제1 이상징후 표적으로 결정하고, 상기 제1 이상징후 표적을 표시하고, 상기 제1 이상징후 표적의 항해 표적 정보와 상기 저장 표적 정보를 융합하여 상기 제1 이상징후 표적의 과거 이동 경로를 나타내는 이동 경로 정보를 생성하고, 상기 생성된 과거 이동 경로와 상기 제1 이상징후 표적의 실제 경로를 비교하고, 상기 제1 이상징후 표적의 과거 이동 경로와 상기 제1 이상징후 표적의 실제 경로가 일치하지 않으면 상기 제1 이상징후 표적을 제2 이상징후 표적으로 결정하고, 상기 제2 이상징후 표적을 표시하는 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

364/1150 Row 364: application_number: 1020200072507, combined_string: invention_title: 어구를 식별하는 스마트부이 abstract: 본 발명은 어구를 식별하는 스마트부이에 관한 것으로서, 더욱 상세하게는 스마트부이를 소형화 하여 스마트부이의 파손을 방지하고, 외부전원 없이도 스마트부이의 충전이 용이한 어구를 식별하는 스마트부이에 관한 것이다. claims: 스마트부이로서,투명재질의 상부케이스;안테나기판 및 상기 안테나기판 상에 형성되어 있는 안테나패턴을 포함하는 안테나모듈;제1PCB기판, 상기 제1PCB기판 상에 배치되는 MCU, 상기 안테나패턴을 통하여 통신을 수행하는 통신모듈, GNSS안테나, 및 GNSS모듈을 포함하는 제1PCB부;상기 안테나모듈의 위치를 고정시키고, 상기 제1PCB부를 내부에서 보호하는 보호케이스;전력관리를 수행하는 제2PCB부;배터리모듈;상기 배터리를 충전하는 충전모듈; 및하부케이스를 포함하고,상기 상부케이스와 상기 하부케이스에 의하여 형성되는 공간에 상기 안테나모듈, 제1PCB부, 보호케이스, 제2PCB부, 배터리모듈, 및 충전모듈이 배치되고,상기 보호케이스의 상면에는 안테나모듈고정슬롯이 형성되어 있고,상기 안테나모듈고정슬롯은 상기 안테나기판의 일부를 지지하고,상기 안테나기판과 상기 제1PCB기판은 서로 수직하는 형태로 접합되어 있는,스마트부이., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

365/1150 Row 365: application_number: 1020200066527, combined_string: invention_title: 유해 조류 퇴치 시스템 abstract: 본 발명은 유해 조류 퇴치 시스템을 개시한다. 이러한 본 발명은 감시영역내에서 레이저 광원을 조사하는 위치 고정형의 메인 조류 퇴치기, 그리고 상기 메인 조류 퇴치기와 연동되는 위치 이동형의 타겟 조류 퇴치기를 구성한 것이고, 이에따라 음영지역없이 감시영역 전체에 대한 조류 퇴치의 효율성을 높이면서, 공항이나 공군 비행장에서 비행기의 이착륙시 충돌로 인한 인적, 경제적 피해, 과수원이나 양식장 등에서의 농작물이나 양식 어류 피해, 그리고 축산, 양계, 가금 농가에 조류 인플루엔자(Al) 바이러스 전파 피해와 대형 공장이나 물류 창고 건물의 조류 배설물 피해 등을 방지하는 것이다. claims: 케이블을 통해 공급되는 전원을 분배하는 전원 분배부와, 상기 전원분배부와 전기적으로 연결되는 하나 또는 복수의 격납부를 가지는 고정대; 상기 고정대의 상단에 설치되어 상기 전원분배부로부터 구동전원을 공급받으며 제 1 팬틸트 구동부에 의해 회전되는 것으로 설정된 감시영역내에서 조류 출몰 여부를 감지한 후 그 감지신호와 방위각을 전송하는 조류 감지기; 상기 고정대의 상단에 고정 설치되어 상기 전원분배부로부터 구동전원을 공급받는 것으로 상기 조류 감지기에 의해 감지된 조류 감지 정보와 방위각 정보가 입력시 조류 감지 위치로 레이저 광원을 자동 조사하는 위치 고정형의 메인 조류 퇴치기; 및, 상기 고정대의 상기 격납부에 분리 가능하게 장착되면서 상기 메인 조류 퇴치기와 통신 연결되어 조류 감지 정보와 방위각 정보를 공유받으며 상기 격납부로부터 분리된 후 조류 감지 위치로 이동시 상기 메인 조류 퇴치기에서 레이저 광원이 조사되지 못하는 음영지역에 수동 또는 자동으로 레이저 광원을 타겟 조사하는 위치 이동형의 타겟 조류 퇴치기; 를 포함하고,상기 조류감지기는 조류 감지정보와 방위각 정보를 전송하기 위한 제 1 통신부와 감시 제어부 및, 상기 감시 제어부의 제어에 따라 상기 제 1 팬틸트 구동부가 팬틸트 구동시 그 팬틸트 구동에 따른 회전량으로 방위각을 산출한 후 이를 상기 제 1 통신부를 통해 상기 메인 조류 퇴치기로 전송하는 방위각 산출부를 포함하는 레이더 감지기인 것을 특징으로 하는 유해 조류 퇴치 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

366/1150 Row 366: application_number: 1020200060255, combined_string: invention_title: 양식장용 파이프 및 그 제조방법 abstract: 본 발명은 사용수명, 강도, 복원력 등이 우수하며, 해양 유래 부착 생물에 대해 방오 효과를 발휘하도록 한 양식장용 파이프 및 그 제조방법에 관한 것으로, 그 구성은 a) 폴리카보네이트 수지(polycarbonate resin) 60 - 80중량%와, 유리섬유(glass fiber) 20 - 40중량%를 혼합하여 수지 조성물을 수득하는 단계; b) 상기 a)단계의 수지 조성물을 인발가공 또는 압출가공 중에서 선택된 어느 하나의 가공방법을 통해 내경이 원형 또는 육각형상을 이루는 원형파이프 또는 육각파이프의 형태로서, 내부에 일정간격마다 구획 벽이 형성되게 성형하여 성형물을 형성하는 단계; c) 천연무기도료 80 - 90중량%와, 해중 생물이 달라붙는 것을 방지하기 위한 해중생물기피 조성물 10 - 20중량%를 혼합하여 혼합 도료를 수득하는 단계; d) 상기 c)단계의 혼합 도료를 상기 b)단계의 성형물에 도포하는 단계; 및 e) 상기 d)단계를 거친 성형물을 건조시킨 후, 원하는 길이로 절단하는 단계;를 포함하여 구성된다. claims: a) 폴리카보네이트 수지(polycarbonate resin) 60 - 80중량%와, 유리섬유(glass fiber) 20 - 40중량%를 혼합하여 수지 조성물을 수득하는 단계;b) 상기 a)단계의 수지 조성물을 인발가공 또는 압출가공 중에서 선택된 어느 하나의 가공방법을 통해 내경이 원형 또는 육각형상을 이루는 원형파이프 또는 육각파이프의 형태로서, 내부에 일정간격마다 구획 벽이 형성되게 성형하여 성형물을 형성하는 단계;c) 천연무기도료 80 - 90중량%와, 해중 생물이 달라붙는 것을 방지하기 위한 해중생물기피 조성물 10 - 20중량%를 혼합하여 혼합 도료를 수득하는 단계;d) 상기 c)단계의 혼합 도료를 상기 b)단계의 성형물에 도포하는 단계; 및e) 상기 d)단계를 거친 성형물을 건조시킨 후, 원하는 길이로 절단하는 단계;를 포함하여 구성되고,상기 c)단계의 천연무기도료는 제올라이트 분말, 순지트 분말, 토르말린 분말, 운모 분말, 맥반석 분말, 황토 분말, 현무암 분말, 화산송이 분말 중에서 선택된 어느 하나의 분말 또는 둘 이상의 분말을 배합하여 광물분말을 형성한 후, 그 광물분말을 800 - 900℃ 온도에서 소성한 다음 무기질 바인더 100중량부에 대하여 소성된 상기 광물분말 10 - 40중량부 및 물 20 - 80중량부를 혼합하여 제조된 것이며,상기 c)단계의 해중생물기피 조성물은 천연유황분말 40 - 60중량%, 고추분말 5 - 15중량% 및 잉글리쉬 아이비 잎, 투구꽃 뿌리, 피마자 씨앗, 묵주완두 씨, 협죽도 잎, 디펜바키아 잎, 포인세티아 잎, 크로톤 뿌리, 란타나 잎, 두루미천남성 줄기, 독미나리 뿌리, 미치광이풀 뿌리, 디기탈리스 잎, 사람주나무 뿌리 중에서 선택된 어느 하나 이상의 독성식물 추출물 35 - 45중량%를 포함하는 것을 특징으로 하는 양식장용 파이프 제조방법.양식장용 파이프에 있어서,내경이 원형 또는 육각형상을 이루는 원형파이프 또는 육각파이프의 형태로서, 내부에 일정한 간격으로 구획 벽이 형성된 성형물과;상기 성형물에 도포되는 혼합 도료;로 구성되고,상기 성형물은 폴리카보네이트 수지(polycarbonate resin) 60 - 80중량%와, 유리섬유(glass fiber) 20 - 40중량%를 혼합하여 된 수지 조성물을 인발가공 또는 압출가공 중에서 선택된 어느 하나의 가공방법을 통해 형성된 것이고,상기 혼합 도료는 제올라이트 분말, 순지트 분말, 토르말린 분말, 운모 분말, 맥반석 분말, 황토 분말, 현무암 분말, 화산송이 분말 중에서 선택된 어느 하나의 분말 또는 둘 이상의 분말을 배합하여 광물분말을 형성한 후, 그 광물분말을 800 - 900℃ 온도에서 소성한 다음 무기질 바인더 100중량부에 대하여 소성된 상기 광물분말 10 - 40중량부 및 물 20 - 80중량부를 혼합하여 제조된 천연무기도료 80 - 90중량%와, 천연유황분말 40 - 60중량%, 고추분말 5 - 15중량% 및 잉글리쉬 아이비 잎, 투구꽃 뿌리, 피마자 씨앗, 묵주완두 씨, 협죽도 잎, 디펜바키아 잎, 포인세티아 잎, 크로톤 뿌리, 란타나 잎, 두루미천남성 줄기, 독미나리 뿌리, 미치광이풀 뿌리, 디기탈리스 잎, 사람주나무 뿌리 중에서 선택된 어느 하나 이상의 독성식물 추출물 35 - 45중량%를 포함하는 해중생물기피 조성물 10 - 20중량%가 혼합된 것임을 특징으로 하는 양식장용 파이프., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

367/1150 Row 367: application_number: 1020200053175, combined_string: invention_title: 유입과 배출 방출수의 효율적 활용이 가능한 양식장용 소수력 발전장치 abstract: 본 발명은 양식장의 방출수를 통해 발현되는 수력에너지를 통해 전기에너지로 얻기 위한 양식장용 소수력 발전장치를 구성함에 있어서: 양식장의 방출수를 수용하면서 배출이 가능하게끔 방출파이프와 배출파이프가 상호 연결되는 수용부; 수용부의 일 측편에 연통되어 발전파이프로 배출되는 방출수를 통해 발전기로부터 발전이 가능하도록 구현하는 발전부; 수용부의 배출파이프에 근접 형성되어 방출수의 외부 방출 및 차단을 위해 개폐가 가능하면서도 방출수의 역류 방지를 상시적으로 조절이 가능하게끔 차단판을 구비하는 조절수단; 및 발전파이프에 근접 형성되어 방출수의 발전을 위한 방출과 차단을 조절하는 개방판을 구비하고, 방출 시에 발생되는 강한 수압으로부터 개방판의 개방이 용이하도록 구성하는 개방수단을 포함함을 특징으로 한다.이러한 본 발명에 따르면, 양식장으로 24시간 내내 유입 · 방출되는 바닷물 등을 이용안 소수력 발전이 가능토록 하면서도, 기존에 설치된 양식장의 방출수 설비를 대폭 교체하지 않고도 설치가 가능하게끔 하며, 방출수의 배출을 통해 발전을 도모할 시 방출수를 차단하고 있던 개방판에 강한 수압이 발생할 경우 쉽게 개방되도록 하면서도 양식장으로 유입되는 방출수의 양과 배출되는 방출수의 양이 다를 경우에 발생되는 역류도 효율적으로 방지할 수 있도록 하는 효과를 제공한다. claims: 양식장에서 외부로 방출되는 방출수(1)를 통해 발현된 수력에너지를 전기에너지로 얻기 위한 양식장용 소수력 발전장치를 구성함에 있어서:상기 양식장으로부터 방출수(1)를 수용하면서 배출이 가능하게끔 방출파이프(11)와 배출파이프(12)가 상호 연결되는 수용부(10); 상기 수용부(10)의 일측에 연통되어 발전파이프(21)로 방출되는 방출수(1)를 통하여 발전기(22)로부터 발전이 가능하도록 구현하고, 수용부(10)로부터 유입되는 방출수(1)에 포함되어 있는 이물질을 제거하도록 메쉬망(23)을 구비하는 발전부(20);상기 수용부(10)의 배출파이프(12) 상에 근접 형성되어 방출수(1)의 외부 방출과 차단하도록 개폐가 가능하면서도 방출수(1)의 역류 방지를 상시적으로 조절이 가능하도록 차단판(31)을 구비하는 조절수단(30); 및상기 발전부(20)의 발전파이프(21)에 근접 형성되어 방출수(1)의 발전을 위한 방출과 차단을 조절하는 개방판(41)을 구비하고, 방출 시에 발생되는 수압으로부터 개방판(41)의 개방이 용이하도록 구성하는 개방수단(40);을 포함하여 이루어지되,상기 조절수단(30)의 차단판(31)은 방출수(1)의 외부 방출을 차단하면서도 개폐가 가능하도록 제1가이드(32)의 제1수직홈(33)에 삽설되어 개폐되도록 하고, 발전파이프(21)로 방출수(1)를 방출할 경우에는 방출수(1)의 역류방지 조절이 가능하도록 하기 위해 배출파이프(12)의 전체를 막지 않도록 구성하고,상기 개방수단(40)은 힌지(45)에 의해 개방판(41)의 회전이 가능하도록 형성되는 회전대(46)와, 회전대(46)의 일 측편에 좌우로의 회전에 의해 가이드홈(47)을 가압하여 개방판(41)이 기울어지도록 함으로써 작은 틈(C)이 발생되도록 하는 가압부(48)와, 타 측편에 연결되어 있는 회전대(46)에 회전조절용 핸들(49)을 구비한 뒤 작업자가 파지한 상태에서 방출수(1)의 배출 시에 발생되는 강한 수압으로부터 개방판(41)의 개방이 용이하도록 구성함을 특징으로 하는 유입과 배출 방출수의 효율적 활용이 가능한 양식장용 소수력 발전장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

368/1150 Row 368: application_number: 1020200030101, combined_string: invention_title: 인공지능을 활용하여 생육 환경 복사가 가능한 바이오 플락 양식 시스템 abstract: 본 발명은 스마트 양식장 관리 시스템에 관한 것으로서, 대상 어류의 생육 데이터에 기반하여 하나 이상의 배양조와, 각 배양조에 설치되어 사육 환경과 어류 상태를 감지하여 센서 데이터를 제공하는 하나 이상의 센서를 포함하는 마스터 양식장에 대한 사육환경 데이터를 제공하고, 상기 센서로부터 전송되는 센서 데이터를 이용하는 인공 지능 기반의 양식 모델을 통해 각 배양조에 적용하기 위한 사료, 산소, 온도, 염분을 포함한 사육환경 변수를 조절하는 환경 제어 데이터를 제공하는 마스터 장치; 및 상기 마스터 장치와 통신망을 통해 연결되어 상기 마스터 장치의 사육환경 데이터를 이용하여 슬레이브 양식장에 적합한 사육환경 복제 데이터를 제공하고, 상기 사육환경 복제 데이터에 따른 상기 슬레이브 양식장이 완료됨을 알리는 양식장 완료 데이터가 수신되면 상기 환경 제어 데이터에 기반하여 상기 슬레이브 양식장에 적용하기 위한 환경 제어 복제 데이터를 제공하는 하나 이상의 슬레이브 장치를 포함할 수 있다. claims: 양식조에 설치된 복수의 센서를 통해 양식장을 관리하는 스마트 양식장 관리 시스템에 있어서, 대상 어류의 생육 데이터에 기반하여 하나 이상의 배양조와, 각 배양조에 설치되어 사육 환경과 어류 상태를 감지하여 센서 데이터를 제공하는 하나 이상의 센서를 포함하는 마스터 양식장에 대한 사육환경 데이터를 제공하고, 상기 센서로부터 전송되는 센서 데이터를 이용하는 인공 지능 기반의 양식 모델을 통해 각 배양조에 적용하기 위한 사료, 산소, 온도, 염분을 포함한 사육환경 변수를 조절하는 환경 제어 데이터를 제공하는 마스터 장치; 및상기 마스터 장치와 통신망을 통해 연결되어 상기 마스터 장치의 사육환경 데이터를 이용하여 슬레이브 양식장에 적합한 사육환경 복제 데이터를 제공하고, 상기 사육환경 복제 데이터에 따른 상기 슬레이브 양식장이 완료됨을 알리는 양식장 완료 데이터가 수신되면 상기 환경 제어 데이터에 기반하여 상기 슬레이브 양식장에 적용하기 위한 환경 제어 복제 데이터를 제공하는 하나 이상의 슬레이브 장치를 포함하되,상기 마스터 장치는 네트워크를 통해 상기 대상 어류에 관련된 먹이 및 행동 데이터들을 수집하여 빅데이터 분석을 통해 생육 데이터를 제공하고, 상기 인공 지능 기반의 양식 모델을 통해 상기 생육 데이터와 상기 센서데이터에 기반한 사육환경의 변수에 따라 사료 공급, 상기 대상 어류의 크기와 무게의 추정, 수온 및 용존 산소의 공급 조절을 포함한 환경 제어 데이터를 지속적으로 업그레이드하는 것인, 스마트 양식장 관리 시스템., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

369/1150 Row 369: application_number: 1020200025366, combined_string: invention_title: 생명 보호 장치 시스템 abstract: 본 발명은 생명 보호 장치 시스템에 관한 것으로서, 보다 구체적으로는 생명 보호 장치 시스템으로서, 이동체의 추락이나 충돌 시에 탑승자의 생명을 보호할 수 있도록 충격을 완화시킬 수 있도록 이동체에 장착되는 충격완화부와 쇼크업 쇼바 및 에어백을 구비하는 충격완화 장치; 상기 이동체에 가해지는 충격을 감지하기 위한 측정기; 상기 측정기의 감지되는 충격에 따라 미리 설정된 구동제어 신호를 발생시키는 제어기; 및 상기 제어기의 구동제어 신호에 대응하여 미리 설정된 재난센터로 재난발생을 알리고 도움을 요청하기 위한 인공지능부를 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 생명 보호 장치 시스템에 따르면, 이동체의 추락이나 충돌 시에 탑승자의 생명을 보호할 수 있도록 충격을 완화시킬 수 있도록 이동체에 장착되는 충격완화부와 쇼크업 쇼바 및 에어백을 구비하는 충격완화 장치와, 이동체에 가해지는 충격을 감지하기 위한 측정기와, 측정기의 감지되는 충격에 따라 미리 설정된 구동제어 신호를 발생시키는 제어기와, 제어기의 구동제어 신호에 대응하여 미리 설정된 재난센터로 재난발생을 알리고 도움을 요청하기 위한 인공지능부를 포함하여 구성함으로써, 드론이나 자율비행체 및 자율주행 자동차를 포함하는 이동체가 추락이나 충돌 시 또는 강이나 바다에 빠질 때에도 이동체의 탑승자에 가해지는 충격을 최소화하고, 그에 따른 긴급한 상황에서의 생명을 보호할 수 있도록 할 수 있다.또한, 본 발명의 생명 보호 장치 시스템에 따르면, 자율주행을 위한 이동체에 충격완화 장치의 충격완화부와 쇼크업 쇼바와 에어백 등을 장착함으로써, 이동체의 추락이나 충돌 시, 또는 강이나 바다에 빠질 때에도 체계적이고 종합적인 단계별 충격완화를 통해 탑승자의 부상을 최소화함과 동시에 위급한 상황에서 재난센터에 알려 도움을 요청하고, 그에 따른 긴급 구호가 가능하도록 할 수 있다. claims: 생명 보호 장치 시스템(10)으로서,이동체의 추락이나 충돌 시에 탑승자의 생명을 보호할 수 있도록 충격을 완화시킬 수 있도록 이동체에 장착되는 충격완화부(110)와 쇼크업 쇼바(120) 및 에어백(130)을 구비하는 충격완화 장치(100);상기 이동체에 가해지는 충격을 감지하기 위한 측정기(200);상기 측정기(200)의 감지되는 충격에 따라 미리 설정된 구동제어 신호를 발생시키는 제어기(300); 및상기 제어기(300)의 구동제어 신호에 대응하여 미리 설정된 재난센터로 재난발생을 알리고 도움을 요청하기 위한 인공지능부(400)를 포함하는 것을 특징으로 하는, 생명 보호 장치 시스템., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

370/1150 Row 370: application_number: 1020200024918, combined_string: invention_title: 다종의 해양표층요소 획득을 위한 관측시스템 abstract: 본 발명은 조위를 따라 부침하며 해저 고정식 해양 관측소에서 해양표층관측을 위한 관측 시스템으로서, 해양관측을 위해 관측장비를 탑재하여 해상에서 부유하는 부유력을 제공하는 부이 본체; 상기 부이 본체의 외부를 이루면서 뼈대를 형성하고 중심부를 통해서 와이어로프가 관통하는 통로를 제공하는 가이드 유닛; 상기 가이드 유닛의 상부에 연결되면서 상기 부이 본체의 상부를 형성하여 상기 가이드 유닛을 해상에서 부유하는 부력을 제공하는 부력유닛; 상기 가이드 유닛 내측의 일부분에 설치되어 해양을 관측하는 상기 관측장비가 수용되는 공간을 제공하는 관측유닛; 및 상기 가이드 유닛의 양단에 각각 설치되어 상기 가이드 유닛을 관통하는 상기 와이어로프를 감싸면서 상기 와이어로프를 보호하는 보호유닛;을 포함하는 것을 특징으로 한다. claims: 조위를 따라 부침하며 해저 고정식 해양 관측소에서 해양표층관측을 위한 관측 시스템으로서,해양관측을 위해 관측장비를 탑재하여 해상에서 부유하는 부유력을 제공하는 부이 본체;상기 부이 본체의 외부를 이루면서 뼈대를 형성하고 중심부를 통해서 와이어로프가 관통하는 통로를 제공하는 가이드 유닛;상기 가이드 유닛의 상부에 연결되면서 상기 부이 본체의 상부를 형성하여 상기 가이드 유닛을 해상에서 부유하는 부력을 제공하는 부력유닛;상기 가이드 유닛 내측의 일부분에 설치되어 해양을 관측하는 상기 관측장비가 수용되는 공간을 제공하는 관측유닛; 및상기 가이드 유닛의 양단에 각각 설치되어 상기 가이드 유닛을 관통하는 상기 와이어로프를 감싸면서 상기 와이어로프를 보호하는 보호유닛;을 포함하되,상기 관측유닛은,상기 가이드 유닛의 내부에 설치되어 상기 관측장비가 수용되는 공간을 제공하는 보조 프레임;상기 보조 프레임 측면의 일부분에 설치되며 상기 관측장비가 수용되는 수용홀이 마련된 수용홀더; 및상기 보조 프레임의 내부에 설치되어 상기 가이드 유닛에 연결되며, 상기 보조 프레임을 상기 가이드 유닛에 고정시키면서 지지하는 보조 프레임 지지대;를 포함하는 것을 특징으로 하는 다종의 해양표층요소 획득을 위한 관측시스템., Ltext: 어업, prediction: '해양' 카테고리가 포함된 특허 카테고리 중 하나인 '어업' 카테고리로 분류할 수 있습니다.

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

371/1150 Row 371: application_number: 1020200023942, combined_string: invention_title: 양식장용 수차 발전장치 abstract: 본 발명은 양식장용 수차 발전장치에 관한 것으로, 그 구성은 양식장에서 회수되는 물을 공급받아 하방으로 자유 낙하시키는 수직 안내관;과, 상기 수직 안내관의 내부 하부에 형성되어 상기 수직 안내관을 통해 자유 낙하하는 물과 접촉되면서 수압에 의해 회전되는 것으로, 상기 수직 안내관에 대하여 상대회동 가능하게 형성되는 회전 팬;과, 일단은 상기 회전 팬과 연결되어 상기 회전 팬과 함께 회전되되, 타단은 제1발전기와 연결되어 상기 제1발전기로 회전력을 공급하는 제1공급축;과, 상기 제1공급축과 연결되어 상기 제1공급축으로부터 공급되는 회전력을 기반으로 발전하는 제1발전기;와, 상기 수직 안내관과 제1발전기를 지지 고정하는 지지대;로 구성된 것을 특징으로 하는 것으로서, 양식장에서 회수되는 물을 수직 안내관을 통해 하방으로 자유 낙하시켜 수직 안내관 하부에 위치되는 회전 팬이 물과 접촉 마찰되면서 회전되게 유도하고, 그 회전되는 회전 팬과 연결되는 제1공급축이 회전되면서 제1발전기로 회전력이 공급되어 전기가 1차적으로 발전되게 하며 동시에, 수직 안내관을 통과한 물은 수평 안내관으로 유입 유통되면서 발전수단을 통해 2차적으로 전기의 발전이 유도되는 방식으로 매우 효율적인 전기의 발전을 유도할 뿐만 아니라, 그 발전된 전기를 양식장에서 전기 사용처(각종 장비 및 장치)로 공급 사용함으로 양식장 운영에 전기 사용으로 인해 소요되는 금전적인 부담을 대폭 절감하여 양식장의 경제적인 운영을 유도할 수 있는 효과가 있다.또한, 발전수단의 수평 안내관을 통해 유통되는 물은 정제수단을 통해 정화된 상태로 배출되므로 양식장에 매우 깨끗한 물이 공급될 수 있어 양식장 어류의 용이한 양식을 유도할 수 있을 뿐만 아니라, 정제수단은 반 영구적인 사용이 유도되어 장치의 편리한 사용 운영이 유도될 수 있는 효과가 있다. claims: 양식장에서 회수되는 물을 공급받아 하방으로 자유 낙하시키는 수직 안내관(10);상기 수직 안내관(10)의 내부 하부에 형성되어 상기 수직 안내관(10)을 통해 자유 낙하하는 물과 접촉되면서 수압에 의해 회전되는 것으로, 상기 수직 안내관(10)에 대하여 상대회동 가능하게 형성되는 회전 팬(20);일단은 상기 회전 팬(20)과 연결되어 상기 회전 팬(20)과 함께 회전되되, 타단은 제1발전기(40)와 연결되어 상기 제1발전기(40)로 회전력을 공급하는 제1공급축(30);상기 제1공급축(30)과 연결되어 상기 제1공급축(30)으로부터 공급되는 회전력을 기반으로 발전하는 제1발전기(40); 및상기 수직 안내관(10)과 제1발전기(40)를 지지 고정하는 지지대(50);를 포함하여 구성되며,상기 수직 안내관(10)에 설치된 상기 회전 팬(20)을 통과한 물을 이용하여 발전하는 발전수단(60);을 더 포함하여 구성되되,상기 발전수단(60)은 상기 수직 안내관(10)과 연결되어 상기 수직 안내관(10)을 통해 배출되는 물을 회전판(62)으로 안내하는 수평 안내관(61)과, 상기 수평 안내관(61)의 내부에 경사(θ2)지게 형성되는 것으로, 전면 가장자리 부분에 등각 간격으로 형성되어 상기 수평 안내관(61)으로 흐르는 물과 접촉 마찰되는 다수의 회전날개(62a)가 형성되어 상기 수평 안내관(61)에 대하여 상대회동 되는 회전판(62)과, 일단은 상기 회전판(62)과 연결되어 상기 회전판(62)과 함께 회전되되, 타단은 제2발전기(64)와 연결되어 상기 제2발전기(64)로 회전력을 공급하는 제2공급축(63)과, 상기 제2공급축(63)과 연결되어 상기 제2공급축(63)으로부터 공급되는 회전력을 기반으로 발전하는 제2발전기(64)를 포함하여 구성되는 것을 특징으로 하는 양식장용 수차 발전장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

372/1150 Row 372: application_number: 1020200020631, combined_string: invention_title: 양식어류의 질병 감시를 위한 스마트 지원시스템 abstract: 본 발명은 양식어류의 질병 감시를 위한 스마트 지원시스템에 대한 것으로, 더욱 상세하게는 양식어류 질병 진단 및 확산 방지 활동에 대한 양어관련자의 행위를 기설정된 기준에 따라 차등 분류하여 이에 따라 양어업에서만 사용할 수 있는 가상화폐인 양어코인을 지급함으로써, 시스템 및 양어산업 활성화를 동시에 도모할 수 있는 양식어류의 질병 감시를 위한 스마트 지원시스템에 대한 것이다. claims: 양식어류에 관한 정보를 센싱하여 관리서버에 전송하는 센서부와; 상기 센서부에서 출력된 정보를 분석하여 양식어류 질병 진단 및 확산 방지 활동에 대한 양어관련자의 참여 정보를 파악하여 상기 양어관련자에게 지급하여야 할 보상을 산정하는 보상산정부를 가지는 관리서버;를 포함하는 것을 특징으로 하는 양식어류의 질병 감시를 위한 스마트 지원시스템., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

373/1150 Row 373: application_number: 1020200017241, combined_string: invention_title: 드론을 이용한 양식장 관리 시스템 및 관리 방법 abstract: 본 발명은 드론을 이용한 양식장 관리 시스템 및 관리 방법에 관한 것이다. 본 발명은, 양식장 관리서버(400)가 드론(300)과 신호 및 데이터 송수신을 통해 자율비행 기반으로 이동 경로 정보에 맞는 비행이 이루어지는지를 실시간으로 드론(300)의 GPS 위치 정보를 수신하여 확인함으로써, 드론(300)에 대해서 오차 범위 내에서 이동 경로 정보에 맞는 드론 영상 정보가 획득되도록 제어하는 제 1 단계; 및 양식장 관리서버(400)가 드론 영상 정보에 대한 영상 분석을 통해 해조류/패류 양식장의 수면에 떠 있는 부이의 상태, 부이를 연결하는 라인의 간격 등의 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 부이의 가라앉은 정보와 가라 앉은 위치 정보가 포함된 제 1 이벤트 정보를 생성하며, 드론 영상 정보에 대한 영상 분석을 통해 라인의 엉킴, 라인 주위의 다른 객체의 발견 등과 같은 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 라인 엉킴 및 다른 객체가 발견된 장소에 대한 엉킨 정보와 다른 객체의 크기 정보, 그 밖의 각 위치 정보를 포함하는 제 2 이벤트 정보를 생성하는 제 2 단계; 를 포함할 수 있다.이에 의해, 해양 상의 양식장을 드론에 의해 촬영한 영상 정보를 무선통신에 의해 수집한 뒤, 영상 정보에서 수면에 떠 있는 부이의 상태, 라인의 간격 등의 설정 기준을 벗어나서 양식장의 부이가 가라앉은 정도 또는 줄 엉킴 등 이상이 발생한 장소 및 현장 상황을 관리자에게 실시간 또는 주기적으로 통지할 수 있는 효과를 제공할 수 있다. claims: 양식장 관리서버(400)가 드론(300)과 신호 및 데이터 송수신을 통해 자율비행 기반으로 이동 경로 정보에 맞는 비행이 이루어지는지를 실시간으로 드론(300)의 GPS 위치 정보를 수신하여 확인함으로써, 드론(300)에 대해서 오차 범위 내에서 이동 경로 정보에 맞는 드론 영상 정보가 획득되도록 제어하는 제 1 단계; 및 양식장 관리서버(400)가 드론 영상 정보에 대한 영상 분석을 통해 해조류/패류 양식장의 수면에 떠 있는 부이의 상태, 부이를 연결하는 라인의 간격 등의 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 부이의 가라앉은 정보와 가라 앉은 위치 정보가 포함된 제 1 이벤트 정보를 생성하며, 드론 영상 정보에 대한 영상 분석을 통해 라인의 엉킴, 라인 주위의 다른 객체의 발견 등과 같은 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 라인 엉킴 및 다른 객체가 발견된 장소에 대한 엉킨 정보와 다른 객체의 크기 정보, 그 밖의 각 위치 정보를 포함하는 제 2 이벤트 정보를 생성하는 제 2 단계; 를 포함하는 것을 특징으로 하는 드론을 이용한 양식장 관리 방법.모바일 단말(100), 네트워크(200), 드론(300), 양식장 관리서버(400)를 포함하는 드론을 이용한 양식장 관리 시스템(1)에 있어서, 양식장 관리서버(400)는,드론(300)과 신호 및 데이터 송수신을 통해 자율비행 기반으로 이동 경로 정보에 맞는 비행이 이루어지는지를 실시간으로 드론(300)의 GPS 위치 정보를 수신하여 확인함으로써, 드론(300)에 대해서 오차 범위 내에서 이동 경로 정보에 맞는 드론 영상 정보가 획득되도록 제어하는 드론 관리/제어모듈(423); 및 드론 영상 정보에 대한 영상 분석을 통해 해조류/패류 양식장의 수면에 떠 있는 부이의 상태, 부이를 연결하는 라인의 간격 등의 설정 기준을 벗어나는 경우 해조류/패류 양식장에 대한 부이의 가라앉은 정보와 가라 앉은 위치 정보가 포함된 제 1 이벤트 정보를 생성하는 영상정보 분석모듈(424); 을 포함하는 것을 특징으로 하는 드론을 이용한 양식장 관리 시스템., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

374/1150 Row 374: application_number: 1020200016470, combined_string: invention_title: 스마트 팜과, 그 관리 방법 및 장치 abstract: 스마트 팜과, 그 관리 방법 및 시스템이 개시된다. 본 개시의 일 실시 예에 따른 스마트 팜 관리 방법은, 미생물에 의해 분해된 어류로부터의 배설물이나 수조 잔존물을 포함한 수조의 물을 식물 재배부에 공급하는 어류 양식부의 수조 환경을 감지하는 단계와, 어류 양식부의 상단 측에 구비되어 어류 양식부로부터 공급 받은 물이 식물들에 의해 정화된 물을 어류 양식부에 공급하는 식물 재배부의 식물 재배 환경을 감지하는 단계와, 식물 재배부에 광원을 제공하는 조명부의 조명 정보를 감지하는 단계와, 수조 환경, 식물 재배 환경 및 조명 정보 중 적어도 하나 이상에 기초하여, 어류 양식부 및 식물 재배부의 환경이 설정 조건으로 유지되도록 제어하는 단계를 포함할 수 있다. claims: 내부에 어류가 서식할 수 있는 수조를 포함하여, 미생물에 의해 분해된 어류로부터의 배설물이나 수조 잔존물을 포함한 상기 수조의 물을 식물 재배부에 공급하는 어류 양식부;식물들 각각이 지지되도록 형성된 지지대를 포함하여 식물 재배가 가능하도록 설치되고, 상기 어류 양식부의 상단 측에 구비되어 상기 어류 양식부로부터 공급 받은 물이 상기 식물들에 의해 정화된 물을 상기 어류 양식부에 공급하는 식물 재배부; 및상기 식물 재배부의 상단 측에 상하 이동 가능하도록 구비되어 상기 식물 재배부에 광원을 제공하고, 조명 각도, 높낮이, 밝기 및 색상이 조절되는 조명부를 포함하고,상기 어류 양식부의 물을 상기 식물 재배부에 이송하기 위한 펌프를 구비한 제 1 순환라인 및 상기 식물 재배부에서 상기 어류 양식부로의 물 공급을 조절하기 위한 개폐 밸브를 구비한 제 2 순환라인을 통해 물이 순환되도록 하는,스마트 팜.스마트 팜을 관리하는 방법으로서,내부에 어류가 서식할 수 있는 수조를 포함하여, 미생물에 의해 분해된 어류로부터의 배설물이나 수조 잔존물을 포함한 상기 수조의 물을 식물 재배부에 공급하는 어류 양식부의 수조 환경을 감지하는 단계; 식물들 각각이 지지되도록 형성된 지지대를 포함하여 식물 재배가 가능하도록 설치되고, 상기 어류 양식부의 상단 측에 구비되어 상기 어류 양식부로부터 공급 받은 물이 상기 식물들에 의해 정화된 물을 상기 어류 양식부에 공급하는 식물 재배부의 식물 재배 환경을 감지하는 단계;상기 식물 재배부의 상단 측에 상하 이동 가능하도록 구비되어 상기 식물 재배부에 광원을 제공하는 조명부의 조명 정보를 감지하는 단계; 및상기 어류 양식부의 수조 환경, 상기 식물 재배부의 식물 재배 환경 및 상기 조명부의 조명 정보 중 적어도 하나 이상에 기초하여, 상기 어류 양식부 및 상기 식물 재배부의 환경이 설정 조건으로 유지되도록 제어하는 단계를 포함하고,상기 제어하는 단계는, 상기 어류 양식부의 물을 상기 식물 재배부에 이송하기 위한 펌프를 구비한 제 1 순환라인 및 상기 식물 재배부에서 상기 어류 양식부로의 물 공급을 조절하기 위한 개폐 밸브를 구비한 제 2 순환라인을 통해 물이 순환되도록 하는 물 순환부의 펌프 구동 및 개폐 밸브 제어를 수행하거나 상기 조명부의 조명 각도, 높낮이, 밝기 및 색상 중 적어도 하나 이상을 조절하는 단계를 포함하는,스마트 팜 관리 방법.스마트 팜을 관리하는 장치로서,스마트 팜과 통신하는 통신 인터페이스;하나 이상의 프로세서; 및상기 하나 이상의 프로세서와 연결되는 메모리를 포함하고,상기 메모리는, 상기 프로세서에 의해 실행될 때, 상기 프로세서로 하여금,내부에 어류가 서식할 수 있는 수조를 포함하여, 미생물에 의해 분해된 어류로부터의 배설물이나 수조 잔존물을 포함한 상기 수조의 물을 식물 재배부에 공급하는 어류 양식부의 수조 환경을 감지하고,식물들 각각이 지지되도록 형성된 지지대를 포함하여 식물 재배가 가능하도록 설치되고, 상기 어류 양식부의 상단 측에 구비되어 상기 어류 양식부에 정화된 물을 공급하는 식물 재배부의 식물 재배 환경을 감지하며,상기 식물 재배부의 상단 측에 상하 이동 가능하도록 구비되어 상기 식물 재배부에 광원을 제공하는 조명부의 조명 정보를 감지하고,상기 어류 양식부의 수조 환경, 상기 식물 재배부의 식물 재배 환경 및 상기 조명부의 조명 정보 중 적어도 하나 이상에 기초하여, 상기 어류 양식부 및 상기 식물 재배부의 환경이 설정 조건으로 유지되도록 제어하며, 상기 어류 양식부의 물을 상기 식물 재배부에 이송하기 위한 펌프를 구비한 제 1 순환라인 및 상기 식물 재배부에서 상기 어류 양식부로의 물 공급을 조절하기 위한 개폐 밸브를 구비한 제 2 순환라인을 통해 물이 순환되도록 하는 물 순환부의 펌프 구동 및 개폐 밸브 제어를 수행하거나 상기 조명부의 조명 각도, 높낮이, 밝기 및 색상 중 적어도 하나 이상을 조절하도록 야기하는(cause) 코드들을 저장하는,스마트 팜 관리 장치., Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

375/1150 Row 375: application_number: 1020200013755, combined_string: invention_title: 양식장용 슬러지 제거장치 abstract: 본 발명은 양식장용 슬러지 제거장치에 관한 것으로서, 보다 상세하게는 선회류에 따라 침전성 슬러지가 발생하는 수조본체와, 이 수조본체 저면에 구비되어 선회류에 의해 침전되는 슬러지를 수거하는 수집홈 및 수집된 슬러지를 배출하는 배출수단을 포함하되, 상기 수집홈을 유체가 흐르는 방향과 교차되는 방향으로 형성된 장홈으로 구성하여 보다 빠르고 효과적으로 슬러지를 수거할 수 있도록 고안된 양식장용 슬러지 제거장치에 관한 것이다. claims: 선회류가 형성시켜 유체가 일방향으로 회전하도록 이루어지는 수조 본체;상기 본체 저면에 구비되어 침전되는 슬러지가 유입되는 수집홈;상기 수집홈에 구비되어 수집홈으로 유입된 슬러지를 배출시키는 배출수단;을 포함하여 이루어지되,상기 수집홈은 상기 본체 내에서 유체가 흐르는 방향과 교차되는 방향으로 형성된 장홈인 것을 특징으로 하는 양식장용 슬러지 제거장치., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

376/1150 Row 376: application_number: 1020217025673, combined_string: invention_title: 근해 자유 부유식 거대 조류 양식을 위한 장치 및 방법 abstract: 본 발명은 수역, 더 구체적으로 바다/근해에서 거대 조류를 양식하기 위한 신규한 장치, 시스템 및 방법을 제공한다. claims: 수역(body-of-water), 바람직하게 바다/근해에서 거대 조류를 성장/양식시키기 위한 장치로서,(a) 수역으로부터 성장 케이지로 그리고 그 반대로 물, 가스 및 영양소의 자유로운 흐름을 가능하게 하는 투과성 벽 및 바닥을 갖는, 수역에 위치시키기 위한 성장/양식 케이지/반응기; 및(b) 가스 흐름 출구(gas flow outlet)를 통해 케이지 바닥으로부터 가스를 스트리밍(streaming)함으로써, 케이지 내의 물 및 결과적으로 그 내부에서 성장하는 거대 조류을 바닥으로부터 상부로 혼합/텀블링/현탁하도록 설계된 거대 조류 현탁 및 혼합 시스템을 포함하며;상기 장치는 상기 거대 조류의 자유 부유식 성장을 위해 설계되는,수역, 바람직하게 바다/근해에서 거대 조류를 성장/양식시키기 위한 장치.수역, 바람직하게 바다/근해에서 거대 조류를 성장시키기 위한 장치로서,a) 수역에 위치시키고, 수역으로부터 성장 케이지로 그리고 그 반대로 물, 가스 및 영양소의 자유로운 흐름을 가능하게 하는 투과성 벽과 바닥을 가지는 성장/양식 케이지/반응기;b) 가스 흐름 출구를 통해 케이지의 바닥으로부터 가스를 스트리밍함으로써, 바닥으로부터 상부로 케이지 내의 물 및 결과적으로 그 내부에서 성장한 거대 조류를 혼합/텀블링/현탁하도록 설계된 거대 조류 현탁 및 혼합 시스템;c) 수면에 또는 케이지 내의 물의 상부 표면이 여전히 햇빛에 노출되는 원하는 깊이에 상기 케이지를 부유 상태로 유지하기 위한 부유 장치/메커니즘;d) 성장 케이지에서 물 교환 및 선택적으로 난류 향상을 위한 적어도 하나의 외부 에어리프트; 및e) 성장 케이지에서 물 교환을 위한 워터-펌프를 포함하며;상기 장치는 상기 거대 조류의 자유로운 부유식 성장을 위해 설계되는,수역, 바람직하게 바다/근해에서 거대 조류를 성장시키기 위한 장치.수역, 바람직하게 바다/근해에서 거대 조류를 성장/양식시키는 방법으로서,(i) 제 1 항 내지 제 16 항 중 어느 한 항에 따른 장치를 수역에 위치시키는 단계;(ii) 성장/양식 케이지/저수조 케이지에 거대 조류 접종물을 배치하는 단계; 및(iii) 케이지 내의 물의 상이한 부분 및 결과적으로 그 내부에서 성장한 거대 조류를 주기적 방식으로 햇빛에 노출시킴으로써 바닥으로부터 상부로 양식 케이지 내의 물을 텀블링/현탁시키기 위한 거대 조류 현탁 및 혼합 시스템을 활성화하는 단계를 포함하며;(1) 상기 현탁 및 혼합 시스템에 의해 양식 케이지 내로 스트리밍된 가스의 양, 세기 및 속도는 상기 거대 조류의 유형, 밀도 및 성장 단계에 따라 결정되며; (2) 상기 텀블링은 양식 케이지 내의 거대 조류의 원하는 밀도/양이 달성될 때까지 연속적으로 수행되는,수역, 바람직하게 바다/근해에서 거대 조류를 성장/양식시키는 방법., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

377/1150 Row 377: application_number: 1020200008035, combined_string: invention_title: 해양 쓰레기 수거 및 재생 처리용 다기능 선박 abstract: 본 발명에 따른 해양 쓰레기 수거 및 재생 처리용 다기능 선박은, 해상에 부유하거나 해저에 침적된 해양 쓰레기를 탐지하여 선체로 수거하는 부유물수거선박, 부유물수거선박에서 수거되어 수분이 제거된 해양 쓰레기를 넘겨받아 성상별로 선별하고 재활용 가능하게 가공 및 처리하는 가공및재활용선박 및 해양 쓰레기의 가공 및 처리 작업에 필요한 작업자들이 거주하는 작업자거주선박 을 포함하며, 부유물수거선박과 가공및재활용선박 및 작업자거주선박은, 해양 쓰레기가 있는 해수면 상의 위치까지 이동하는 동안에는 결합하여 이동하고, 해양 쓰레기가 있는 해수면 상의 위치에 이르러 해양 쓰레기 수거 및 재생 처리 작업을 개시할 때 분리되어 해양 쓰레기가 중심이 되는 삼각형으로 둘러싸며, 중심 방향으로 정상파 파동의 파도를 발생시켜 해양 쓰레기가 중심으로 모이도록 한 후, 부유물수거선박이 중심 근방에 모인 해양 쓰레기를 수거하는 것을 특징으로 한다. 이와 같은 구성을 가지는 본 발명에 의하면, 해상에 부유하는 오염물과 쓰레기를 모아서 수거 및 처리하여 재생유를 생산하거나 재활용 처리할 수 있는 해양 쓰레기 수거 및 재생 처리용 다기능 선박을 제공하는 것과 같은 이점이 있다. claims: 해상에 부유하거나 해저에 침적된 해양 쓰레기를 탐지하여 선체로 수거하는 부유물수거선박; 상기 부유물수거선박에서 수거되어 수분이 제거된 해양 쓰레기를 넘겨받아 성상별로 선별하고 재활용 가능하게 가공 및 처리하는 가공및재활용선박; 및 해양 쓰레기의 가공 및 처리 작업에 필요한 작업자들이 거주하는 작업자거주선박; 을 포함하며, 상기 부유물수거선박과 상기 가공및재활용선박 및 상기 작업자거주선박은, 해양 쓰레기가 있는 해수면 상의 위치까지 이동하는 동안에는 결합하여 이동하고, 해양 쓰레기가 있는 해수면 상의 위치에 이르러 상기 해양 쓰레기 수거 및 재생 처리 작업을 개시할 때 분리되어 상기 해양 쓰레기가 중심이 되는 삼각형으로 둘러싸며, 상기 중심 방향으로 정상파 파동의 파도를 발생시켜 해양 쓰레기가 상기 중심으로 모이도록 한 후, 상기 부유물수거선박이 상기 중심 근방에 모인 해양 쓰레기를 수거하고, 상기 부유물수거선박에서 해양 쓰레기를 수거하는 동안, 상기 가공및재활용선박 및 상기 작업자거주선박이 각각 다시 상기 부유물수거선박과 결합하며, 상기 작업자거주선박의 작업자들이 상기 가공및재활용선박으로 이동하고, 상기 부유물수거선박에서 수거된 해양 쓰레기는 상기 가공및재활용선박으로 이송되며, 상기 부유물수거선박은, 해상에 부유하거나 해저에 침적된 해양 쓰레기를 탐지하도록 선체 또는 상부데크에 구비되는 탐지장치; 및 상기 탐지장치에 의해 탐지된 해양 쓰레기를 선체로 수거하도록 선체 또는 상부데크에 설치되는 수거장치; 를 포함하며, 해양 쓰레기를 수거하여 상기 가공및재활용선박으로 이송하는 것을 특징으로 하는 해양 쓰레기 수거 및 재생 처리용 다기능 선박., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

378/1150 Row 378: application_number: 1020200005260, combined_string: invention_title: 에너지제로 생태순환형 농수축산 통합생산시스템 abstract: 양식어류 및 바이오플락 사육수가 저장되는 공간이 마련된 양식수조를 갖는 바이오플락 양식시스템; 일정 면적의 철망바닥부가 지면에 설치되고, 철망 바닥부 가장자리를 둘러싸며 일정 높이의 축사외벽이 형성되며, 축사외벽 상부에는 지붕이 설치되어 내부에 가축 사육공간이 형성되는 축사; 재배식물이 안착된 재배분 및 재배수를 저장할 수 있는 프레임구조의 재배조가 복층 또는 다층구조로 설치되는 식물재배시스템; 상기 바이오플락사육수 공급라인을 매개로 상기 축사 및 식물재배시스템과 연결되어 배수된 바이오플락 사육수가 공급되고, 상기 축사와 식물 재배시스템은 축사분뇨 공급라인으로 연결되며, 상기 식물재배시스템은 바이오플락 양식시스템과 식물재배수 공급라인으로 연결되어 생태순환시스템을 형성하며; 상기 시스템의 가동은 신재생에너지 발전에서 신재생에너지를 에너지 공급원으로 하여 전기에너지를 생산하여 공급되는 것인 에너지제로 생태순환형 농수축산 통합생산시스템을 제공한다. claims: 양식어류 및 바이오플락 사육수가 저장되는 공간이 마련된 양식수조와 상기 양식수조 내부에는 바이오플락 사육수에 공기 공급 및 수류를 형성하는 벤추리장치가 설치되는 바이오플락 양식시스템;일정 면적의 철망바닥부가 지면에 설치되고, 상기 철망 바닥부 가장자리를 둘러싸며 일정 높이의 축사외벽이 형성되며, 상기 축사외벽 상부에는 지붕이 설치되어 내부에 가축 사육공간이 형성되는 축사;재배식물이 안착된 재배분 및 재배수를 저장할 수 있는 프레임구조의 재배조가 복층 또는 다층구조로 설치되는 식물재배시스템;상기 바이오플락 양식시스템은 바이오플락사육수 공급라인을 매개로 상기 축사 및 식물재배시스템과 연결되어 배수된 바이오플락 사육수가 공급되고, 상기 축사와 식물 재배시스템은 축사분뇨 공급라인으로 연결되며, 상기 식물재배시스템은 바이오플락 양식시스템과 식물재배수 공급라인으로 연결되어 생태순환시스템을 형성하며;상기 시스템의 가동은 신재생에너지 발전에서 신재생에너지를 에너지 공급원으로 하여 전기에너지를 생산하여 공급되는 것인 에너지제로 생태순환형 농수축산 통합생산시스템, Ltext: 어업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

379/1150 Row 379: application_number: 1020200005269, combined_string: invention_title: 양식장 사육수 산소공급을 위한 산소용해장치 abstract: 일정길이의 산소용해 파이프라인이 나선형구조를 이루며 케이싱내부에 설치되고; 상기 산소용해 파이프라인 일측 말단은 산소공급장치와 연결되고, 타측 말단은 사육수 살균장치와 연결되어 이루어지는 고효율 산소용해장치 및 살균장치를 제공함으로써, 기존의 산소용해장치와 동일한 수압을 제공하는 것으로 미세버블을 제조가 가능할 뿐만 아니라 용존산소량의 증가 및 지속이 가능하여 대용량의 산소용해수의 제조가 가능할 뿐만 아니라 설치비용 및 가동부담을 줄일 수 있는 효과가 있다. claims: 일정길이의 산소용해 파이프라인이 나선형구조를 이루며 케이싱내부에 설치되고; 상기 산소용해 파이프라인 일측 말단은 산소공급장치와 연결되고, 타측 말단은 사육수 살균장치와 연결되어 이루어지는 것인 고효율 산소용해장치 및 살균장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

380/1150 Row 380: application_number: 1020200002003, combined_string: invention_title: 어군 탐지 시스템 및 어군 탐지 방법 abstract: 본 발명은 어군 탐지 시스템 및 어군 탐지 방법에 관한 것으로, 본 발명의 일 실시예에 따른 어군 탐지 방법은, 수중에 음파를 송출하고, 송출된 음파를 수신하는 어군 탐지기 및 상기 어군 탐지기를 설정하고 제어하는 관리 단말기를 이용하여 어군을 탐지하기 위해, 상기 어군 탐지기의 통신을 개방하는 단계; 상기 관리 단말기에서 통신 속도 및 수중 음속을 이용하여 BIN 개수 당 거리를 계산하는 단계; 상기 어군 탐지기에서 수중에 대한 수심을 탐지하는 단계; 탐지된 상기 수심을 이용하여 수심에 따른 상기 BIN 개수를 산정하는 단계; 산정된 상기 BIN 개수에 따라 상기 어군 탐지기 및 관리 단말기 중 하나 이상의 화면에 출력하기 위해 상기 BIN 개수에 대한 화면표시 비율을 산정하는 단계; 및 상기 화면표시 비율에 따라 수중의 어군을 상기 어군 탐지기 및 관리 단말기 중 하나 이상의 화면에 표시하는 단계를 포함하고, 상기 수중에 대한 수심을 탐지하는 단계는, 수중에 어군이 있는 경우, 어군까지의 수심을 탐지할 수 있다. 본 발명에 의하면, 어군 탐지기와의 통신을 위한 프로그램에 대한 설계를 변경하고, 탐지된 어군을 화면에 표시하기 위한 방식을 BIN 개수를 이용함으로써, 어군의 위치를 보다 정확하고 명확하게 실시간으로 확인할 수 있는 효과가 있다. claims: 수중에 음파를 송출하고, 송출된 음파를 수신하는 어군 탐지기; 및상기 어군 탐지기를 설정하고 제어하는 관리 단말기를 포함하며,상기 관리 단말기는, 통신 속도 및 수중 음속을 이용하여 BIN 개수 당 거리를 계산하고, 상기 어군 탐지기에서 탐지된 수심에 따른 BIN 개수를 산정하며, 산정된 BIN 개수에 따라 화면에 출력하기 위해 BIN 개수에 대한 화면표시 비율을 산정하여 산정된 화면표시 비율에 따라 수중의 어군을 표시하고,상기 화면은 상기 어군 탐지기 및 관리 단말기 중 하나 이상에 포함된 디스플레이 장치를 통해 표시되는 화면인 어군 탐지 시스템이고,상기 어군 탐지시스템은 수중에 음파를 송출하고, 송출된 음파를 수신하는 어군 탐지기 및 상기 어군 탐지기를 설정하고 제어하는 관리 단말기를 이용하여 어군을 탐지하기 위해, 상기 어군 탐지기의 통신을 개방하는 단계; 상기 관리 단말기에서 통신 속도 및 수중 음속을 이용하여 BIN 개수 당 거리를 계산하는 단계; 상기 어군 탐지기에서 수중에 대한 수심을 탐지(수중에 어군이 있는 경우, 어군까지의 수심을 탐지)하는 단계; 탐지된 상기 수심을 이용하여 수심에 따른 상기 BIN 개수를 산정하는 단계; 산정된 상기 BIN 개수에 따라 상기 어군 탐지기 및 관리 단말기 중 하나 이상의 화면에 출력하기 위해 상기 BIN 개수에 대한 화면표시 비율을 산정하는 단계; 및 상기 화면표시 비율에 따라 수중의 어군을 상기 어군 탐지기 및 관리 단말기 중 하나 이상의 화면에 표시하는 단계를 포함하고, 상기 통신을 개방하는 단계 이전에, 상기 어군 탐지기와 통신하기 위한 상기 관리 단말기에 포함된 통신 포트를 통해 설정하는 단계를 더 포함하고, 상기 화면표시 비율의 산정이 이루어지면, 픽셀의 중복 출력 회수를 산정하는 단계를 더 포함하고, 상기 수중의 어군을 상기 어군 탐지기의 화면에 표시하는 단계는, 상기 픽셀의 중복 출력 회수에 따라 화면에 표시하며, 상기 통신을 개방하는 단계 이전에, 상기 어군 탐지기에 대한 암호를 해제하는 단계를 더 포함하는 방식으로 어군을 탐지하며,상기 어군 탐지기의 외부면에는 오염 방지도포용 조성물로 이루어진 오염방지도포층이 도포되되, 상기 오염 방지 도포용 조성물은 메르캅토벤조씨아졸 및 아미도알킬 베타인이 1:0.01 ~ 1:2 몰비로 포함되어 있고, 메르캅토벤조씨아졸과 아미도알킬 베타인의 총함량은 전체 수용액에 대해 1 ~10 중량%이고,상기 관리 단말기가 금속재인 경우에 표면 상에 부식 방지 도포층을 도포하고, 상기 부식 방지 도포층에 포함된 표면 도포 재료는 벤즈트리아졸 15중량%, 에틸렌 글리콜 부틸 에테르 25중량%, 하프늄 20중량%, 유화몰리브덴(MoS2) 10중량%, 산화티타늄(TiO2) 15중량%, 페놀 노블락형 글리시딜에테르 15중량%로 구성되며, 코팅두께는 8㎛로 형성되며,상기 관리 단말기의 하단에는 고무재의 진동흡수방지부가 더 설치되되, 상기 진동흡수방지부의 원료 함량비는 고무 58 중량%, 카아본블랙 32중량%, 산화방지재 5 중량%, 촉진재인 유황 3중량%, 레소르시놀 수지 2 중량%를 혼합하는, 어군 탐지 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

381/1150 Row 381: application_number: 1020190171379, combined_string: invention_title: 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표 및 이를 이용한 센싱 시스템 abstract: 본 발명의 일 실시예는 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표 및 이를 이용한 센싱 시스템에 관한 것으로, 해결하고자 하는 기술적 과제는 환경보호와 저전력 시스템, 청정 에너지 사용이 가능하게 하는데 있다.이를 위해 본 발명의 일 실시예는 어구 또는 어망에 장착되는 LoRaWAN 통신 기반 IoT 부표고, 몸체부; 상기 몸체부에 구비되고, GPS 신호를 수신하는 GPS 모듈; 상기 몸체부에 구비되고, 상기 몸체부 주변의 해수 온도 및 파도 정보를 감지하는 센서부; 및 상기 몸체부에 구비되고, 상기 GPS 모듈 및 센서부에 의하여 감지되는 위치정보, 해수 온도 및 파도 정보를 LoRaWAN 통신 망을 통하여 외부로 전송하는 통신부를 포함하는 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표를 개시한다. claims: 어구 또는 어망에 장착되는 LoRaWAN 통신 기반 IoT 부표이고,몸체부;상기 몸체부에 구비되고, GPS 신호를 수신하는 GPS 모듈;상기 몸체부에 구비되고, 상기 몸체부 주변의 해수 온도 및 파도 정보를 감지하는 센서부; 및상기 몸체부에 구비되고, 상기 GPS 모듈 및 센서부에 의하여 감지되는 위치정보, 해수 온도 및 파도 정보를 LoRaWAN 통신 망을 통하여 외부로 전송하는 통신부를 포함하고,상기 몸체부는 IP7 이상의 방수기능을 가지고,상기 몸체부의 상면과 내부 하부 영역에는 상기 몸체부의 내부에 구비되는 배터리에 전원을 공급하는 태양광 충전부와 충전포트가 구비되며,상기 통신부는 일대 다자간 통신프로토콜을 위하여 IoT 부표의 식별정보 및 위치정보와, 해수 온도 및 파도 정보와, 배터리의 전원량 정보 및 전원 공급 정보를 LoRaWAN 방식으로 주기적으로 송신하고,상기 IoT부표의 내외부면에는 오염 방지 도포용 조성물로 이루어진 오염방지도포층이 도포되되, 상기 오염 방지 도포용 조성물은 코카미도프로필베타인 및 암포 글리시네이트가 1:0.01 ~ 1:2 몰비로 포함되어 있고, 코카미도프로필베타인과 암포 글리시네이트의 총함량은 전체 수용액에 대해 1 ~10 중량%이며,상기 센서부 표면에는 부식방지도포층이 도포되되, 상기 부식방지도포층의 도포 재료는 벤즈이미다졸 20중량%, 프로필렌 글리콜 메틸 에테르 30중량%, 하프늄 15중량%, 유화몰리브덴(MoS2) 10중량%, 산화알루미늄 15중량%, 비스페놀 F형 디글리시딜에테르 10중량%로 구성되며, 코팅두께는 8㎛로 형성되고,상기 태양광충전부를 몸체부에 장착할 때 태양광충전부와 몸체부간의 접착력을 높이기 위해 접착 향상재를 통하여 접착시키되, 상기 접착 향상재는 물 50중량부와, 에틸 아크릴레이트 25중량부와, 스티렌 10중량부와, 메타 아크릴산 5중량부와, 계면활성제 5중량부와, 첨가제 2중량부와, 과황산암모늄 2중량부와, 완충제 1중량부를 포함하여 이루어진 것을 특징으로 하는 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표.제1항에 기재된 적어도 하나의 LoRaWAN 통신 기반 IoT 부표;상기 IoT 부표로부터 수신한 상기 IoT 부표의 식별정보 및 위치정보와, 해수 온도 및 파도 정보와, 배터리의 전원량 정보 및 전원 공급 정보를 LoRaWAN 통신 망을 통하여 선박 또는 육상에 구비된 중앙관제서버로 송신하는 게이트웨이부; 및상기 IoT 부표의 식별정보 및 위치정보를 수신하여, 미리 설치된 위치 표시 프로그램을 이용하여 미리 설정된 연동 형식이나 AIS 표준 신호로 변환후 IoT 부표의 식별정보 및 위치정보를 표시하고, 상기 해수 온도 및 파도 정보와, 배터리의 전원량 정보 및 전원 공급 정보를 수신하여 상기 IoT 부표의 동작 상태를 모니터링하고, 이상 발생시 외부로 알림 신호를 출력하는 중앙관제서버를 포함하고,상기 IoT 부표가 상기 게이트웨이부에게 업링크(Up-Link) 전송을 수행한 이후 두번의 다운링크(Down-Link) 수신이 가능하며, 상기 IoT 부표는 Tx를 하기 전에 Tx와 Rx를 모두 꺼두었다가 Tx이후 미리 설정된 시간에 Rx신호를 감지하여 저전력 LoRaWAN 통신을 수행하며,상기 중앙관제서버는 서버 내부의 오작동으로 인한 화재 분석이 가능한 에너지 저장 시스템을 더 구비하되, 상기 에너지 저장 시스템은 배터리; 상기 배터리의 충방전 상태를 감시하는 배터리 모니터링 시스템(BMS), 배터리의 충방전 상태를 제어하는 파워 컨디셔닝 시스템(PCS), BMS로부터 배터리 모니터링 데이터를 감시하고 PCS를 제어하는 에너지 모니터링 시스템(EMS), 및 BMS로부터 배터리의 전압, 전류, 온도의 데이터와 외부 통신 데이터를 수신하고, PCS로부터 전압, 전류의 데이터를 수신하며, EMS로부터 감시 및 제어 데이터를 수신하여 저장하는 블랙박스를 포함하고, 또한, 상기 에너지 저장 시스템은 내부를 촬영하는 카메라, 에너지 저장 시스템의 온도를 센싱하는 온도 센서, 에너지 저장 시스템의 습도를 센싱하는 습도 센서, 및 에너지 저장 시스템의 오프 가스를 센싱하는 오프 가스 센서를 포함하는 것을 특징으로 하는 원거리 해양환경 모니터링을 위한 LoRaWAN 통신 기반 IoT 부표를 이용한 센싱 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

382/1150 Row 382: application_number: 1020190170368, combined_string: invention_title: 바이오플락 양식 사육수를 이용한 군체 형성 미세조류 및 동물 플랑크톤 자동 생산 및 회수장치 abstract: 다각형의 수조바닥을 일정높이의 수조외벽이 둘러싸며 상부가 개구되고 내부공간이 형성되는 회수 수조; 상기 회수 수조의 수조외벽 어느 한 측면에는 바이오플락 사육수조와 연결되어 배수된 바이오플락 사육수가 이동하는 바이오플락 사육수 공급관; 상기 사육수조 중심부에는 회전장치가 수조바닥과 수직하게 설치되며; 상기 회전장치의 최상단에 설치되어, 회전장치의 설치방향을 중심축으로 회전하는 수집장치; 상기 회수 수조 내부에 설치되어 저장된 바이오플락 사육수의 수류를 형성하는 수류형성장치로 이루어진 바이오플락 양식 사육수를 이용한 군체형성 미세조류 및 동물 플랑크톤 자동 생산 및 회수장치를 제공함으로써, 고부가 가치를 지니는 바이오플락 사육수를 미세조류와 동물 플랑크톤의 배양수로 공급하여 배양 시에 무기염류 및 영양성분을 별도로 공급할 필요가 없고, 배양수로 이용된 바이오플락 사육수에 포함되어 있는 질소 및 무기염류 성분이 제거되어 사육 수조로 재공급이 가능함으로 친환경적일 뿐만 아니라 경제적인 효과가 있다. claims: 다각형의 수조바닥을 일정높이의 수조외벽이 둘러싸며 상부가 개구되고 내부공간이 형성되는 회수 수조; 상기 회수 수조의 수조외벽 어느 한 측면에는 바이오플락 사육수조와 연결되어 배수된 바이오플락 사육수가 이동하는 바이오플락 사육수 공급관; 상기 회수수조 중심부에는 회전장치가 수조바닥과 수직하게 설치되며; 상기 회전장치의 최상단에 설치되어, 회전장치의 설치방향을 중심축으로 회전하는 수집장치; 상기 회수 수조 내부에 설치되어 저장된 바이오플락 사육수의 수류를 형성하는 수류형성장치로 이루어진 것을 특징으로 하는 바이오플락 양식 사육수를 이용한 군체형성 생물 자동 생산 회수장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

383/1150 Row 383: application_number: 1020190170477, combined_string: invention_title: 자동 어류 계수 시스템 abstract: 본 발명은 자동 어류 계수 시스템에 관한 것이다. 본 발명은, CMOS 카메라(110) 및 적외선 카메라(120)로 이루어진 카메라 모듈(100), 적어도 하나 이상의 카메라 모듈(100)과 유/무선 통신 라인으로 신호 및 데이터 송수신을 수행하는 SBC(Single Board Computer)(200), 네크워크(300), 자동 계수 서버(400)를 포함하는 자동 어류 계수 시스템(1)에 있어서, 카메라 모듈(100)은, CMOS 카메라(110)를 통해 어도의 미리 설정된 낮 시간동안의 영상 정보를 획득하고 적외선 카메라(120)를 통해 어도의 미리 설정된 저녁시간동안의 영상 정보를 획득하여 네트워크(200)를 통해 SBC(200)로 제공하며, SBC(200)는, 미리 설정된 어도에 설치되어 설치된 어도를 지나가는 물체에 대해서 적어도 하나 이상의 카메라 모듈(100)을 통해 촬영되는 영상 정보에서 인식을 수행하고, 물체가 인식된 영상 정보를 네트워크(300)를 통해 자동 계수 서버(400)로 전송하여 저장하도록 할 뿐만 아니라, 영상 정보에서 감시하는 대상 어종 정보에 해당하는 인식을 수행하고, 인식된 대상 어종에 대한 마킹을 설정하고, 설정된 마킹 ID를 저장부(240) 상에 저장하고 개체수에 대한 추적을 수행하는 것을 특징으로 할 수 있다. 이에 의해, 인공지능 학습과 분류를 통해 필요한 자료를 수집하고 분류하여 수집한 데이터를 통해 어떤 결과를 얻을 것인지를 예측할 수 있으므로, 영상 정보의 수집을 통해 충분한 양의 데이터를 확보하고, 수집한 데이터에서 관심 있는 영역을 자동 마킹을 통해 얻고자하는 어종의 갯수를 포함하는 계수 결과를 정확하게 도출가능한 효과를 제공할 수 있다. claims: CMOS 카메라(110) 및 적외선 카메라(120)로 이루어진 카메라 모듈(100); 적어도 하나 이상의 카메라 모듈(100)과 유선 및 무선 통신 라인으로 신호 및 데이터 송수신을 수행하는 SBC(Single Board Computer)(200); 네크워크(300); 복수의 관리자 단말(500); 그리고 SBC(200)를 통해 수집된 영상 정보를 빅데이터 기반으로 저장할 뿐만 아니라 네트워크(300)를 통해 액세스하는 관리자 단말(500)에 대한 인증 과정을 통해 관리자 단말(500)에게 제공하는 자동 계수 서버(400); 를 포함하는 자동 어류 계수 시스템(1)에 있어서, 카메라 모듈(100)은, CMOS 카메라(110)를 통해 어도의 미리 설정된 낮 시간동안의 영상 정보를 획득하고 적외선 카메라(120)를 통해 어도의 미리 설정된 저녁시간동안의 영상 정보를 획득하여 네트워크(200)를 통해 SBC(200)로 제공하며, SBC(200)는,I/O 인터페이스(210); 송수신부(230); 저장부(240); 경고 출력부(250); 외에, 미리 설정된 어도에 설치되어 설치된 어도를 지나가는 물체에 대해서 적어도 하나 이상의 카메라 모듈(100)을 통해 촬영되는 영상 정보에서 인식을 수행하고, 물체가 인식된 영상 정보를 네트워크(300)를 통해 자동 계수 서버(400)로 전송하여 저장하도록 할 뿐만 아니라, 영상 정보에서 감시하는 대상 어종 정보에 해당하는 인식을 수행하고, 인식된 대상 어종에 대한 마킹을 설정하고, 설정된 마킹 ID를 저장부(240) 상에 저장하고 개체수에 대한 추적을 수행하는 제어부(220); 를 포함하며, 제어부(220)는,SBC(220)가 관리하는 어도에 설치된 적어도 하나 이상의 카메라모듈(100)의 카메라 식별 ID, 그리고 어도 영역 정보, 감시하는 대상 어종 정보를 포함하는 카메라 수집 단위 정보에 대해서 네트워크(300)를 통해 자동 계수 서버(400) 또는 관리자 단말(500)로부터 수신하도록 송수신부(210)를 제어한 뒤, 저장부(240) 상에 카메라 수집 단위 정보를 저장하고, 카메라 모듈(100)이 설치된 영역에는 조도 센서(100a)가 구비되는 경우 카메라 수집 단위 정보에 실시간으로 카메라모듈(100)로부터 I/O 인터페이스(210)를 통해 수신되는 영상 정보를 미리 설정된 조도 이상의 낮 시간 동안과 미리 설정된 조도 미만의 저녁 시간 동안으로 분류하여 저장부(240) 상에 함께 저장하는 정보수집 모듈(221);영상 정보에서 감시하는 대상 어종 정보에 해당하는 인식을 수행하고, 인식된 대상 어종에 대한 마킹을 설정하고, 설정된 마킹 ID를 저장부(240) 상에 저장하기 위해, 영상 정보에서 대상 어종 정보에 대한 인식시 네트워크(300)를 통해 자동 계수 서버(400)에 대한 요청을 통해 복수의 대상 어종 정보에 대한 치어와 성어에 대해 구분된 낮 시간대 및 밤 시간대의 형상 패턴, 그리고 각 형상 패턴에 대해서 미리 설정된 각도 범위로 기울어진 것, 각 형상 패턴에 대해서 축소 또는 확대된 것, 각 형상 패턴에 대해서 역으로 된 것, 일부 가려진 패턴을 포함하는 형상 패턴과 영상 정보를 비교하여 영상 정보 속의 대상 어종 정보에 대한 판별을 수행하며, 판별된 대상 어종에 대해서 대상 어종 정보, 치어/성어 정보를 포함하는 마킹 ID를 설정한 뒤, 마킹 ID를 메타데이터로 대상 어종 정보 및 치어/성어 정보를 마킹 단위 정보로 저장부(240)에 저장하며, 대상 어종에 대한 패턴 인식시 인공지능 기반의 학습을 통해 정보를 처리하기 위해, 네트워크(300)를 통해 자동 계수 서버(400)로 액세스하여 빅데이터 기반의 학습 정보를 활용하여 대상 어종과 치어 및 성어에 대한 인식을 수행하는 전처리 모듈(222);네트워크(300)를 통해 카메라 수집 단위 정보 및 마킹 단위 정보를 실시간으로 자동 계수 서버(400)로 전송하도록 송수신부(210)를 제어함으로써, 자동 계수 서버(400)에 의해 어도의 연속성에 따른 대상 어종의 증감이 예측될 수 있도록 하되, 자동 계수 서버(400)에 의해 어도의 연속성에 따른 대상 어종의 증감이 예측시 자동 계수 서버(400)가 카메라 수집 단위 정보와 마킹 단위 정보를 각 SBC(200)의 SBC 식별 ID 별로 데이터베이스 상에 저장하고 SBC 식별 ID 간에 미리 설정된 거리 내에 물의 흐름 방향에서 전방 또는 후방에 해당하는 위치 정보를 데이터베이스에서 추출한 뒤, SBC 식별 ID 별로 저장된 마킹 단위 정보에서 대상 어류 별로 수를 계측하고, 계측된 대상 어류에 대해서 전방으로 진입하는 대상 어류의 증감을 다시 계측함으로써, 각 SBC 식별 ID를 중심으로 모든 대상 어류의 증감 정보를 생성하고, 대상 어류의 증감 정보를 기초로 미리 설정된 임계치 이상의 감소 정보가 발생하는 두 개의 SBC(200)의 식별 ID를 추출하고, 추출된 SBC(200)의 식별 ID 중 물의 흐름 방향에서 후순위에 해당하는 SBC(200)의 식별 ID를 추출하도록 하는 인공지능 기반 분류 모듈(223);자동 계수 서버(400)로부터 추출된 두 개의 SBC(200)의 식별 ID에 해당하는 경우 제 1 경고 출력 명령을 수신하고, 후순위에 해당하는 SBC(200)의 식별 ID에 해당하는 경우 제 2 경고 출력 명령을 네트워크(300)를 통해 수신하도록 송수신부(310)를 제어하고, 제 1 경고 출력 명령을 수신함에 따라 경고 출력부(250)를 통해 제 1 경고 신호를 출력하고, 제 2 경고 출력 명령을 수신함에 따라 경고출력부(250)를 통해 제 2 경고 신호를 출력하고, 제 1 경고 신호와 제 2 경고 신호로 서로 구분되는 음향 또는 영상 신호로 출력하며, 경고 신호에 따라 복수로 구비되는 관리자 단말(500) 중 카메라 모듈(100)이 설치된 어구에 대해 근접시 대상 어류에 대한 문제(보에 의해 이동 제한 포함)가 발생함을 인식할 수 있도록 하며, 제 2 경고 신호를 출력하기 전에 SBC(200)가 어도 출구부에 형성된 것인 경우 닫힌 하구로 분석하고, 미리 설정된 임계치 이상의 감소치를 보인 어류 정보에 대한 치어 또는 성어 여부, 그리고 영상 인식된 각 개체의 평균 면적 정보를 생성한 뒤, 네트워크(300)를 통해 위치 기반의 관리자 단말(500)로 전송하는 서비스 제공 모듈(224); 및 네트워크(300)를 통한 관리자 단말(500)에 의한 VR 콘텐츠를 제공 요청에 따라 2차원 영상에 해당하는 영상 정보에 대해서 VR 영상 정보를 생성하고, 생성된 VR 영상 정보를 네트워크(300)를 통해 관리자 단말(500)로 전송함으로써, 관리자 단말(500)와 근거리 무선통신 방식으로 신호 및 데이터 송수신을 수행하는 HMD에 형성된 자이로 센서에 의해 인식된 각 우 시차각 및 좌 시차각에 다른 VR 영상 정보가 출력되도록 하는 VR 영상 제공 모듈(225); 을 포함하며, 관리자 단말(500)은, VR 영상 정보에 포함된 각 마킹 ID, 그리고 카메라 식별 ID를 네트워크(300)를 통해 서비스 제공 모듈(224)에 대한 요청을 통해 수신한 뒤 근거리 무선통신 방식으로 VR 영상 정보와 함께 HMD 상으로 출력하도록 하며, 각 마킹 ID에 해당하는 대상 어류에 대해서 VR 영상 정보 상의 영시차로 미리 설정된 시간 이상 응시가 되는 것으로 HMD로부터 신호를 수신하는 경우, 마킹 ID를 네트워크(300)를 통해 정보수집 모듈(221)로 제공함으로써, 정보수집 모듈(221)에 의해 마킹 ID와 매칭되는 마킹 단위 정보가 추출되어 네트워크(300)를 통해 마킹 단위 정보를 수신하는 경우 마킹 단위 정보에서 대상 어종 정보 및 치어/성어 정보를 추출하여 마킹 ID에 해당하는 인식된 대상 어류의 좌표 정보에 매칭하여 출력하도록 제어하며, 마킹 ID에 해당하는 영상 정보를 제공한 카메라 식별 ID를 네트워크(300)를 통해 정보수집 모듈(221)로 제공함으로써, 정보수집 모듈(221)에 의해 카메라 식별 ID에 해당하는 카메라모듈(100)에 의해 의해 수집된 카메라 수집 단위 정보가 추출되는 경우, 정보수집 모듈(221)로부터 카메라 수집 단위 정보를 네트워크(300)를 통해 수신한 뒤, 카메라 수집 단위 정보에 포함된 카메라 식별 ID, 뿐만 아니라, 어도 영역 정보, 감시하는 대상 어종 정보를 HMD로 출력하도록 제어하며, 관리, Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

384/1150 Row 384: application_number: 1020190169285, combined_string: invention_title: 블럭형 자가발전 어구 표시 부이 abstract: 본 발명에 의한 블럭형 자가발전 어구 표시 부이는, 무선통신이 가능한 본체부, 상기 본체부 하측에 구비되며, 상기 본체부가 구동되도록 전기 에너지를 생산하고, 공급하는 자가 발전부를 포함하며, 상기 자가 발전부는, 외부로부터 충격력을 인가받았을 때 전기 에너지를 생산하는 자가 전력 나노발전기와, 파도에 의해 움직여 상기 자가 전력 나노발전기에 충격력을 인가하는 기계적 운동 에너지 장치와, 상기 자가 전력 나노발전기에서 생산된 전기 에너지를 저장하고 상기 저장된 전기 에너지를 상기 본체부에 공급하는 충전용 배터리가 순차적으로 적층된 것을 특징으로 한다. claims: 자가발전부와 전기적으로 연결되어 해중 어구의 위치를 표시하는 부이에 있어서,무선통신이 가능한 본체부 및상기 본체부 하측에 구비되며, 상기 본체부가 구동되도록 전기 에너지를 생산하고, 공급하는 자가 발전부를 포함하며,상기 자가 발전부는, 외부로부터 충격력을 인가받았을 때 전기 에너지를 생산하는 자가 전력 나노발전기와, 파도에 의해 움직여 상기 자가 전력 나노발전기에 충격력을 인가하는 기계적 운동 에너지 장치와, 상기 자가 전력 나노발전기에서 생산된 전기 에너지를 저장하고 상기 저장된 전기 에너지를 상기 본체부에 공급하는 충전용 배터리가 순차적으로 적층된 것이고,상기 기계적 운동에너지 장치는,상기 자가 전력 나노발전기의 상면을 덮도록 결합되고, 내부에 공간이 구비된 하우징, 상기 하우징 내부에 배치되어 상기 자가 전력 나노발전기의 상면에 충격력을 가하는 가압부를 포함하며,상기 가압부는,상기 하우징의 내부공간 천장에 고정되는 고정바,중단이 상기 고정바에 힌지결합되어 길이방향 양측이 상기 자가 전력 나노발전기의 상면에 충격력을 가하는 누름바를 포함하는 것을 특징으로 하는 블럭형 자가발전 어구 표시 부이.제1항 내지 제3항, 제7항 및 제8항 중 어느 한 항의 블럭형 자가발전 어구 표시 부이를 포함하는 어구 표시 부이 모니터링 시스템., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

385/1150 Row 385: application_number: 1020210016858, combined_string: invention_title: 인공어초단지 및 해조 바다목장 모니터링 방법 및 장치 abstract: 해저의 촬영 영역을 촬영하는 카메라; 상기 카메라 하부에 설치되어 360도방향으로 설정 시간에 따라 일정 각도로 회전 하는 타임랩스 회전부; 상기 회전부의 하부에는 카메라와 타임랩스 회전부를 지지하는 베이스부가 설치되며; 상기 카메라, 타임랩스 회전부, 베이스부는 방수케이스 내부에 내장되며; 상기 방수케이스 내부에는 카메라의 촬영과 타임랩스 회전부의 구동을 설정 및 제어하는 제어부가 설치되며;상기 방수케이스 외측 하부면에는 고정장치 체결부가 형성되어 고정장치를 매개로 설치하고자 하는 해저 지역에 고정되어 이루어지는 인공어초단지 및 해조장 모니터링장치를 제공함으로써, 시간에 따라 360도 평면상을 포함하는 영상촬영이 가능하여 조식동물(성게류, 고둥류)구제와 같은 조성지 환경개선과 인공어초단지나 해중림 조성지의 조성 후 사후 모니터링이 가능하여 보다 효율적인 관리가 가능한 효과가 있고 해저에 설치되는 파이프라인, 해저 배수관, 돌핀 구조물등의 해저구조물의 모니터링까지 가능한 효과가 있다. claims: 수중 영역을 촬영하는 카메라; 상기 카메라 하부에 설치되어 360도방향으로 설정 시간에 따라 일정 각도 만큼 회전하는 타임랩스 회전부; 상기 회전부의 하부에는 카메라와 타임랩스 회전부를 지지하는 베이스부가 설치되며; 상기 타임랩스 회전부의 상부에는 카메라를 고정하는 고정홀더가 형성되고, 카메라의 촬영과 타임랩스 회전부의 구동을 설정, 제어하는 제어부로 이루어지고,상기 카메라와 타임랩스 회전부 및 베이스부를 내장하여 둘러싸는 방수케이스로 이루어지며, 상기 방수케이스의 내측 투명부에는 카메라의 초점고정 및 거리측정용 초점판(450) 격자가 인쇄되어 이루어지며, 방수케이스 외측 하부면에는 고정장치 체결부가 형성되어 수중의 일정 면에 고정되어 이루어지는 것을 특징으로 하는 인공어초단지 및 해조 바다목장 모니터링 장치청구항 1의 인공어초단지 및 해조 바다목장 모니터링 장치를 설정된 수역에 고정장치를 이용하여 고정 및 설치하고, 일정기간 모니터링한 후, 방수케이스와 고정장치를 분리하여 회수하고 수집된 데이터 영상을 분석하는 단계로 이루어진 것을 특징으로 하는 인공어초단지 및 해조 바다목장 모니터링 방법, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

386/1150 Row 386: application_number: 1020200106674, combined_string: invention_title: 순환 여과식 새우양식장 abstract: 본 발명은 양식생물이 입식되어 사육되는 양식수조가 하나 이상 설치되고; 상기 양식수조의 사육수가 배수되어 저장되는 집수조; 상기 집수조에 저장된 사육수가 이동되어 정화되는 정화수조;로 이루어지는 순환 여과식 새우 양식장을 제공함으로써, 정화수조 전단에 설치되는 제1분리부에서 고정상여재부를 매개로 하는 여과 효과가 발휘되고, 후단의 제2분리부에는 전단의 제1분리부에서 탈리된 슬러지 및 미처리된 물질들을 제거하는 효과가 발휘됨으로써 전체적으로 안정적인 정화효과를 확보할 수 있어 양식수조에서 사육수의 즉각적인 배수에도 정화효율이 떨어지지 않고, 기존의 새우 양식장과 같이 사육수 분사장치마다 모터 및 산소공급장치를 여러개 설치하지 않고도 이동라인에 모터부 및 산소공급장치를 설치하여 정화가 완료된 사육수에 산소를 용해시킴과 동시에 수압을 공급할 수 있어 양식장 설치비용을 절감할 수 있는 효과가 있다. claims: 양식생물이 입식되어 사육되는 양식수조가 하나 이상 설치되고; 상기 양식수조의 사육수가 배수되어 저장되는 집수조; 상기 집수조에 저장된 사육수가 이동되어 정화되는 정화수조로 이루어지는 순환 여과식 양식장에 있어서;상기 정화수조는 다각형의 수조바닥을 수조외벽이 둘러싸고 상부는 개구되어 내부에는 저장공간이 형성되며, 상기 저장공간에는 전, 후 방향으로 하나 이상의 격벽으로 분리되어, 정화수조 내부가 하나 이상의 사육수 저장공간으로 형성되고;상기 정화수조 전, 후단 어느 한 측면에는 집수조에 저장된 사육수를 공급하는 배수라인이 설치되고, 상기 배수라인과 최단 거리에 형성되는 저장공간의 순서로 고정상 여과재로 이루어진 제1분리부, 유동상 여과재로 이루어진 제2분리부, 필터판으로 이루어진 제3분리부 및 수집부의 순서로 정화수조가 형성되며; 상기 제1분리부의 상부 개구부에는 전, 후 방향으로 고정로프가 좌, 우방향으로 이격되어 복수개 설치되고, 상기 고정로프에는 하나 이상의 고정상 여재부가 일정간격 이격되어 수직으로 고정되며, 상기 제2분리부에는 망사주머니에 유동상 여과재가 충전되고, 제3분리부에는 필터판이 설치되어 이루어지는 것을 특징으로 하는 순환 여과식 양식장, Ltext: 어업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

387/1150 Row 387: application_number: 1020200079209, combined_string: invention_title: LED 유도 통발 abstract: 본 발명은 LED 유도 통발에 관한 것으로, 양측으로 링부재가 이격배치된 본체; 상기 본체를 감싸도록 형성되고, 양측에 내측으로 갈수록 좁아지는 유도공이 형성된 메쉬망; 및 상기 본체의 테두리를 따라 상기 메쉬망을 고정시키도록 결합된 발광로프;를 포함한다. 이러한 구성으로, 본체에 발광로프를 결합함으로써, 발광을 통해 어류를 유인하는 것은 물론, 어류를 유인함에 따라 어획량을 증대시킬 수 있는 효과를 얻을 수 있다. claims: 양측으로 링부재가 이격배치된 본체;상기 본체를 감싸도록 형성되고, 양측에 내측으로 갈수록 좁아지는 유도공이 형성된 메쉬망; 및상기 본체의 테두리를 따라 상기 메쉬망을 고정시키도록 결합된 발광로프;를 포함하고,상기 발광로프의 내부에는 길이 방향으로 일측에 구비된 전원부로부터 전원이 공급되는 전원선이 매립되고, 상기 전원선에 일정간격으로 연결된 LED램프가 구비되며,상기 발광로프의 내부에는 상기 LED램프가 유동 가능하도록 유동홈이 형성되어, 외부 충격 시 상기 LED램프가 유동되고,상기 LED램프의 하단에는 상기 LED램프가 양측으로 유동 가능하도록 볼록하게 형성된 볼록편이 형성된 것을 특징으로 하는 LED 유도 통발., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

388/1150 Row 388: application_number: 1020200072721, combined_string: invention_title: 상시 개구부를 갖는 개체굴 양성장치 abstract: 일정크기의 격자망을 갖는 판프레임이 수평으로 상, 하 일정거리 이격되어 설치되고, 수직방향으로 판프레임이 하나 이상 상기 상, 하 판프레임의 가장자리를 둘러싸며 이루어지는 케이스부와; 상기 수직방향으로 설치된 판프레임 어느 한 측면에는 케이스부 내부로 개체굴의 저장과 방출이 가능한 개체굴 상시 개구부가 형성되며; 상기 케이스부는 고정장치를 매개로 상, 하로 하나 이상 적층 결합되어 이루어지는 개체굴 양성장치를 제공함으로써 상시 개구부를 통해 사용자가 보다 개체굴의 출입을 용이하게 하여 선별 및 분리작업 또는 수확 시에 작업시간이 감소될 수 있으며 다단으로 설치된 단일의 양성장치를 분리하지 않고 결합된 상태에서도 개체굴의 저장 및 방출이 가능하여 사용자가 수중에서 작업이 가능한 효과가 있다. claims: 일정크기의 격자망을 갖는 다각형 판프레임이 수평으로 상, 하 일정거리 이격되어 천정면과 바닥면을 형성하고, 상기 천정면과 바닥면의 가장자리를 판프레임이 둘러싸며 연결되어 일정 체적을 갖는 내부 수용공간을 이루는 케이스부; 상기 케이스부를 이루는 판프레임 어느 한 측면에는 개체굴의 투입과 방출이 가능한 개체굴 상시 개구부가 형성되고;상기 개체굴 상시 개구부는 개체굴이 안착되는 바닥면으로부터 일정 길이로 이격된 케이스부 일 측면에 상시 개방된 형태로 이루어지는 것을 특징으로 하는 상시 개구부를 갖는 개체굴 양성장치, Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

389/1150 Row 389: application_number: 1020200064056, combined_string: invention_title: 큰징거미새우의 종묘 생육 장치 abstract: 큰징거미새우의 종묘 생육 장치가 소개된다.이를 위해 본 발명은 복수개로 일렬로 배치되고 외부에서 공급되는 해수와 담수가 혼합되는 수조하우징(100); 유생이 입식되고 유생의 먹이생물이 포함되도록 상기 복수개의 수조하우징(100) 내부에 각각 위치하고 그 상방이 개방되며 둘레를 따라 상기 유생과 상기 먹이생물의 크기보다 작은 다수개의 메쉬로 이루어진 케이지(200); 상기 복수개의 수조하우징(100) 내부로 해수공급관(310)과 담수공급관(410)을 통해 각각 해수와 담수와 공급될 수 있도록 상기 복수개의 수조하우징(100)의 일측에 마련된 해수탱크(300)와 담수탱크(400); 상기 복수개의 수조하우징(100) 내부에 설치되어 수조 내의 수질 환경을 센싱하는 센서부; 및 상기 센서부에 의해 센싱된 수조 내의 수질 환경 정보를 입력받아 상기 수조 하우징 내의 물의 온도와 염분을 설정된 온도와 염분으로 유지할 수 있도록 상기 수조 하우징 내부에 위치한 히터와 상기 해수공급관(310)과 상기 담수공급관(410)의 개폐를 제어하는 제어부(600)를 포함한다. claims: 복수개로 일렬로 배치되고 외부에서 공급되는 해수와 담수가 혼합되는 수조하우징;유생이 입식되고 유생의 먹이생물이 포함되도록 상기 복수개의 수조하우징 내부에 각각 위치하고 그 상방이 개방되며 둘레를 따라 상기 유생과 상기 먹이생물의 크기보다 작은 다수개의 메쉬로 이루어진 케이지;상기 복수개의 수조하우징 내부로 해수공급관과 담수공급관을 통해 각각 해수와 담수와 공급될 수 있도록 상기 복수개의 수조하우징의 일측에 마련된 해수탱크와 담수탱크;상기 복수개의 수조하우징 내부에 설치되어 수조 내의 수질 환경을 센싱하는 센서부; 및상기 센서부에 의해 센싱된 수조 내의 수질 환경 정보를 입력받아 상기 수조 하우징 내의 물의 온도와 염분을 설정된 온도와 염분으로 유지할 수 있도록 상기 수조 하우징 내부에 위치한 히터와 상기 해수공급관과 상기 담수공급관의 개폐를 제어하는 제어부를 포함하는, 큰징거미새우의 종묘 생육 장치., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

390/1150 Row 390: application_number: 1020190172634, combined_string: invention_title: 어로용 통발의 미끼통 abstract: 본 발명은 어로용 통발의 미끼통에 관한 것으로서, 그 목적은 별도의 고정로프를 사용하지 않고 미끼통을 통발의 내측 중앙에 통발의 배치상태와 상관 없이 유동 없이 확실하게 위치되도록 간편하게 착탈가능하게 고정설치할 수 있으면서도, 각종 어류 유입기능을 구비하여 충분한 시간(어류를 포획하기 위해 통발을 바닷물에 투척한 후 투척된 통발 내에 어획물을 획득하기 위해 통발을 수거하는 시간 동안) 어류유인효과가 지속적으로 유인되도록 하여 어획량 증대에 기여할 수 있도록 하는 것이며, 그 구성은 내부에 미끼가 채워진 상태로 어로용 통발의 내측에 설치되어 어류를 통발 내로 유인하기 위한 어로용 통발의 미끼통으로서, 상기 미끼통은 내부중공에 미끼가 충전되고, 충전된 미끼를 서서히 외부로 배출시켜 어류를 유지하는 미끼통 본체와; 일정 높이를 갖는 지지봉으로서, 하단부는 하단부에 통발의 하부 프레임 중 하면을 중심을 가로지르는 종대와 착탈가능하게 체결되고, 상단부에 상기 미끼통 본체가 착탈가능하게 체결되고, 상기 미끼통 본체를 통발의 내측 중앙위치에 고정지지하는 미끼통 본체 지지대로 구성되는 것을 특징으로 한다. claims: 내부에 미끼가 채워진 상태로 어로용 통발의 내측에 설치되어 어류를 통발 내로 유인하기 위한 어로용 통발의 미끼통으로서,상기 미끼통(10)은,내부중공에 미끼(100)가 충전되고, 충전된 미끼를 서서히 외부로 배출시켜 어류를 유인하는 미끼통 본체(20)와;일정 높이를 갖는 지지봉으로서, 하단부는 하단부에 통발(200)의 하부 프레임 중 하면을 중심을 가로지르는 종대(211)와 착탈가능하게 체결되고, 상단부에 상기 미끼통 본체(20)가 착탈가능하게 체결되고, 상기 미끼통 본체(20)를 통발(200)의 내측 중앙위치에 고정지지하는 미끼통 본체 지지대(30)로 구성되는 것을 특징으로 하는 어로용 통발의 미끼통., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

391/1150 Row 391: application_number: 2020190004777, combined_string: invention_title: 가자미목 어류용 개체 식별표 abstract: 가자미목 어류용 개체 식별표로서, 개체 식별번호가 부여되어 있고 무선 인식이 가능한 전자칩이 내장된 태그; 및 일측은 아가미에 형성된 관통공을 관통하고 타측은 상기 태그에 형성된 관통공을 관통하도록 설치되는 링 타입의 연결부재;를 포함하는 구성을 마련함으로써, 가자미목 어류의 경골조직인 아가미에 천공한 후 부착할 수 있어 횟감으로 사용되는 근육 부분에 전혀 손상을 주지 않고 2차 감염 등의 위험 없이 어류 개체의 이력을 추적할 수 있게 된다. claims: 개체 식별번호가 부여되어 있고 무선 인식이 가능한 전자칩이 내장된 태그; 및일측은 아가미 뚜껑에 형성된 관통공을 관통하고 타측은 상기 태그에 형성된 관통공을 관통하도록 설치되는 링 타입의 연결부재;를 포함하는 것을 특징으로 하는, 가자미목 어류용 개체 식별표., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

392/1150 Row 392: application_number: 1020190150523, combined_string: invention_title: 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초 abstract: 본 발명은 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초에 관한 것이다.더욱 구체적으로는, 어류의 생활환경을 조성해주는 인공어초에 있어서 사각형의 형태를 이루되 내부에 여덟 개의 날개판이 소정의 형상을 가지도록 구성됨으로써, 해양 저면에 안착된 인공어초가 침하되는 것을 방지하고, 조류의 흐름을 결정해서 먹이 활동에 의한 어류의 유집 효과를 가지며, 유체 흐름(오름흐름) 방향과 속도에 변화를 주는 구조를 가짐으로써 어류의 먹이활동의 장을 제공할 수 있도록 구성된것과 내부공간이 연결되어 어류의 이동이 자유롭도록, 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초에 관한 것이다. claims: 사각바 형상을 가지는 프레임(10)이 결합되어 사각형을 이뤄 내부공간(20)이 형성되고, 상기 사각형이 6개의 면을 이뤄 육면체형의 형상을 이뤄, 사각 인공어초를 형성하되,각 면을 이루는 프레임(10)의 일측에서부터는 인공어초의 내부 방향으로 소정의 경사각을 가지면서 연장된 날개판(30)이 총 8개 형성되는, 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초에 있어서,상기 날개판(30)은 인접한 것들 간에 일측이 연결된 구조를 가지되,제1 날개판①의 하방의 프레임 중 일측에서 연장되고, 제2 날개판②은 상기 제1 날개판①에 대하여 개구부가 수직된 방향으로 제1 날개판①에 연결되며,제3 날개판③은 상기 제2 날개판②에 대하여 개구부가 수직된 방향으로 제2 날개판②에 연결됨으로써, 상방의 프레임 중 일측에서 연장되고,제4 날개판④ 역시 제3 날개판③에 대하여 개구부가 수직된 방향으로 연결되며, 제5 날개판⑤은 제4 날개판④에 대하여 개구부가 수직된 방향으로 연결됨에 따라 하방의 프레임 중 일측에서 연장되고,제6 날개판⑥은 제5 날개판⑤에 대하여 개구부가 수직된 방향으로, 제7 날개판⑦은 제6 날개판⑥에 대하여 개구부가 수직된 방향으로 연결되되, 상방의 프레임 중 일측에서 연장되고, 제8 날개판⑧은 상기 제7 날개판⑦에 대하여 개구부가 수직된 방향으로 연결되고, 다른 방향이 상기 제1 날개판①에 대하여 개구부가 수직된 방향으로 연결되는 것을 특징으로 하는, 내부에 여덟 개의 날개판을 가지는 다기능 사각 인공어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

393/1150 Row 393: application_number: 1020190137804, combined_string: invention_title: 붉바리 등 어류 치어 선별작업장치 abstract: 본 발명은 붉바리 등 어류 치어 선별작업 장치에 대하여 개시한다. 본 발명의 붉바리 등 어류 치어 선별작업장치는 치어 선별분리작업을 이루는 작업대가 바닥에서 소정의 높이로 형성되고 치어선별을 위한 일정크기의 수조가 구비되는 작업부재와, 상기 작업부재의 수조 상단에 설치되어 선별을 위한 치어가 공급되는 분리하는 선별부재와, 상기 선별부재 상부에 크기별로 분리된 치어와 용수가 공급되는 유도홀이 구비된 가이드대가 설치되며 상기 가이드대의 출구에는 크기별로 분리 선별된 치어가 각각 수집되는 집어함이 구비된 분리부재를 포함하여 이루어져 있어 작업자의 이동이 없고 치어의 크기 선별작업 시 작업자의 자세 또한 허리를 편안한 자세로 하게 되므로 육체적 고통이 없으며, 선별된 치어는 크기별로 자동으로 수집되어 작업인력과 소요 경비가 절감되 이점이 있는 것이다. claims: 치어 선별분리작업을 이루는 작업대가 바닥에서 소정의 높이로 형성되고 치어선별을 위한 일정크기의 수조가 구비되는 작업부재;상기 작업부재의 수조 상단에 설치되어 선별을 위한 치어가 공급되는 분리하는 선별부재;상기 선별부재 상부에 크기별로 분리된 치어와 용수가 공급되는 유도홀이 구비된 가이드대가 설치되며 상기 가이드대의 출구에는 크기별로 분리 선별된 치어가 각각 수집되는 집어함이 구비된 분리부재;를 포함하여 이루어진 붉바리 등 어류 치어 선별작업장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

394/1150 Row 394: application_number: 1020190121866, combined_string: invention_title: 어류에 대한 바이러스성 출혈성 패혈증 예방 방법 및 바이러스성 출혈성 패혈증 바이러스에 대한 감염 내성을 갖는 어류의 생산 방법 abstract: 본 발명의 바이러스성 출혈성 패혈증 예방 방법은 넙치에서 발생하는 바이러스성 출혈성 패혈증을 효과적으로 예방할 수 있으므로, 넙치의 양식 산업 등에 유용하게 사용될 수 있다. 또한, 침지를 통해 주사 기반 백신과 유사하게 바이러스성 출혈성 패혈증에 대한 방어 효과를 나타내기 때문에 성어 뿐 아니라 치어에서도 간편하게 바이러스성 출혈성 패혈증을 예방할 수 있고, 이를 통해 바이러스성 출혈성 패혈증 바이러스에 대하여 내병성을 가진 넙치를 생산할 수 있다. claims: 바이러스성 출혈성 패혈증 바이러스(Viral hemorrhagic septicemia virus, VHSV)를 포함하는 17 내지 23℃의 수온의 수조에 어류를 침지하는 단계를 포함하는 어류에 대한 바이러스성 출혈성 패혈증 예방 방법. 다음 단계를 포함하는 바이러스성 출혈성 패혈증 바이러스에 대한 감염 내성을 갖는 어류의 생산 방법:바이러스성 출혈성 패혈증 바이러스(Viral hemorrhagic septicemia virus, VHSV)를 포함하는 17 내지 23℃의 수온의 수조에 어류를 침지하는 단계; 5 내지 25℃의 수온의 수조에서 3주 내지 5주 동안 상기 어류를 사육하여 바이러스성 출혈성 패혈증 바이러스에 대한 면역반응을 유도하는 단계; 및바이러스성 출혈성 패혈증 바이러스 감염 내성을 갖는 어류를 수득하는 단계., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

395/1150 Row 395: application_number: 2020190003614, combined_string: invention_title: 산호 양식용 지지대 및 이를 포함하는 산호 양식용 수조 abstract: 본 고안은 산호 양식용 수조 및 산호 양식용 지지대를 제공한다. 본 고안은 상부가 개방된 수조와, 상기 수조의 상부에 설치되는 조명과, 상기 수조의 내부공간에 배치되고, 복수개의 플레이트가 각각 서로 다른 높이의 계단식으로 배치되는 산호 지지대, 및 상기 산호 지지대에 설치되는 복수개의 양식용 지그;를 포함하고, 상기 플레이트는 상기 양식용 지그가 삽입되며 복수개로 구비되는 삽입홀, 및 상기 플레이트의 가장자리를 따라 배치되는 돌출벽을 구비한다. claims: 상부가 개방된 수조;상기 수조의 상부에 설치되는 조명;상기 수조의 내부공간에 배치되고, 복수개의 플레이트가 각각 서로 다른 높이의 계단식으로 배치되는 산호 지지대; 및상기 산호 지지대에 설치되는 복수개의 양식용 지그;를 포함하고,상기 플레이트는상기 양식용 지그가 삽입되며 복수개로 구비되는 삽입홀; 및상기 플레이트의 가장자리를 따라 배치되는 돌출벽;을 구비하는, 산호 양식용 수조.제1 지지판;상기 제1 지지판의 후방에 배치되고, 상기 제1 지지판 보다 높게 배치된 제2 지지판;상기 제2 지지판의 후방에 배치되고, 상기 제2 지지판 보다 높게 배치된 제3 지지판;상기 제1 지지판, 상기 제2 지지판 및 상기 제3 지지판에 각각 배치되고, 양식용 지그가 삽입되는 복수개의 삽입홀; 및상기 제1 지지판, 상기 제2 지지판 및 상기 제3 지지판의 가장자리를 따라 기 설정된 높이로 돌출된 돌출벽;을 포함하는, 산호 양식용 지지대., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

396/1150 Row 396: application_number: 1020217007179, combined_string: invention_title: 불임 및 단성 자손을 생성하는 방법 abstract: 본 개시는 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 방법을 제공한다. 상기 방법은 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위해 (i) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물과 (ii) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계를 포함하고, 상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키고, 상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키며, 상기 가임 동형접합인 암컷 어류, 갑각류, 또는 연체동물 및 가임 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물의 가임성은 회복됐다. 또한 본 개시는 친어 그 자체뿐만 아니라, 불임 및 성 결정된 담수 및 해수 생명체를 생성하는 데 사용하기 위한 담수 및 해수 생명체로 친어를 생성하는 방법을 제공한다. claims: 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, 상기 방법은: (i) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 반접합(hemizygous) 돌연변이된 암컷 어류, 갑각류, 또는 연체동물과 (ii) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계; 및유전자형 선발을 통해, 불임 및 성 결정된 어류, 갑각류, 또는 연체동물인 동형접합인 전구체를 선발하는 단계;를 포함하고,상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키며,상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키는 것인, 방법.불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, 상기 방법은: 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위해 (i) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 동형접합(homozygous) 돌연변이된 암컷 어류, 갑각류, 또는 연체동물과 (ii) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계를 포함하고,상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키고,상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키며,상기 가임 동형접합인 암컷 어류, 갑각류, 또는 연체동물 및 가임 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물의 가임성은 회복된 것인, 방법. 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, 상기 방법은: 불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위해 (i) 동형접합 돌연변이를 가지고 있는 가임 암컷 어류, 갑각류, 또는 연체동물과 (ii) 동형접합 돌연변이를 가지고 있는 가임 수컷 어류, 갑각류, 또는 연체동믈을 교배시키는 단계를 포함하고,상기 돌연변이는 직접 또는 간접적으로 정자형성을 결손시키거나, 및/또는 직접 난황형성을 결손시키며,상기 가임 암컷 어류, 갑각류, 또는 연체동물 및 가임 수컷 어류, 갑각류, 또는 연체동물의 가임성은 회복된 것인, 방법.불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위한 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물로서, 상기 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물은 적어도 첫 번째 및 두 번째 돌연변이를 가지고, 상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키고, 상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키며, 상기 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물의 가임성은 회복된 것인, 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물.불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하기 위한 동형접합 돌연변이를 가지고 있는 가임 어류, 갑각류, 또는 연체동물로서, 상기 돌연변이는 직접 또는 간접적으로 정자형성을 결손시키거나, 및/또는 직접 난황형성을 결손시키고, 상기 가임 어류, 갑각류, 또는 연체동물의 가임성은 회복된 것인, 가임 어류, 갑각류, 또는 연체동물.불임 및 성 결정된 어류, 갑각류, 또는 연체동물을 생성하는 가임 동형접합 돌연변이된 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, 상기 방법은: (i) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 반접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물과 (ii) 적어도 첫 번째 및 두 번째 돌연변이를 가지는 가임 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계; 유전자형 선발을 통해, 동형접합인 전구체를 선발하는 단계; 및상기 동형접합인 전구체의 가임성을 회복시키는 단계;를 포함하고,상기 첫 번째 돌연변이는 성적 분화를 지정하는 하나 이상의 유전자들을 결손시키며,상기 두 번째 돌연변이는 생식세포 기능을 지정하는 하나 이상의 유전자들을 결손시키는 것인, 방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

397/1150 Row 397: application_number: 1020190095119, combined_string: invention_title: 풀무치의 인공 부화방법 abstract: 본 발명은 풀무치의 인공 부화방법에 관한 것이다. 본 발명에 따른 풀무치의 인공 부화방법은 풀무치 알을 최적 온도, 광주기, 조도 조건에서 부화시킴에 따라 상기 풀무치 알의 부화율을 현저히 증가시킬 수 있어, 계획적으로 풀무치를 대량 생산 및 출하할 수 있다. claims: (a) 부화온도 30 내지 38℃;(b) 습도 55 내지 80%;(c) 광주기 9L/15D 내지 12L/12D;(d) 조도 3,000 내지 6,000Lux의 조건 하에서 풀무치의 알을 부화시키는 단계; 를 포함하는, 풀무치의 인공 부화방법., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

398/1150 Row 398: application_number: 1020190089348, combined_string: invention_title: 어류털이장치 abstract: 어류털이장치가 개시된다. 어류털이장치는 그물에 걸린 어류를 터는 어류털이장치에 있어서, 하측이 좌측 회전체의 돌기에 고정되어, 좌측 회전체의 회전에 따라 움직이는 좌측 하부축, 하측이 우측 회전체의 돌기에 고정되어, 우측 회전체의 회전에 따라 움직이는 우측 하부축, 하측이 좌측 하부축의 상측과 힌지결합되고, 좌측 하부축의 움직임에 따라 상하부로 움직이는 좌측 상부축, 하측이 우측 하부축의 상측와 힌지결합되고, 우측 하부축의 움직임에 따라 상하부로 움직이는 우측 상부축, 일측이 좌측 상부축 상부에 고정되고, 타측이 우측 상부축 상부에 고정되며, 그물을 하부에서 받히고, 좌측 상부축 및 우측 상부축의 움직임에 따라 상부로 이동하여 그물을 아래에서 위로 치는 받침 털이대, 메인 프레임부에 고정되어 받침 털이대 및 좌측 하부축 사이에 위치하며, 좌측 상부축이 상하부로 직선 운동하게 가이드 하는 좌측 가이드부, 및 메인 프레임부에 고정되어 받침 털이대 및 우측 하부축 사이에 위치하며, 우측 상부축이 상하부로 직선 운동하게 가이드 하는 우측 가이드부를 포함할 수 있다. claims: 그물에 걸린 어류를 터는 어류털이장치에 있어서,회전력을 제공하는 모터;판형으로 형성된 몸체 및 상기 몸체 일면에서 돌출되어 형성된 돌기를 포함하는 좌측 회전체;판형으로 형성된 몸체 및 상기 몸체 일면에서 돌출되어 형성된 돌기를 포함하는 우측 회전체;상기 모터의 회전력을 전달받아 상기 좌측 회전체 및 상기 우측 회전체를 회전시키는 동력전달부;상기 동력전달부를 지지하는 메인 프레임부;하측이 상기 좌측 회전체의 돌기에 고정되어, 상기 좌측 회전체의 회전에 따라 움직이는 좌측 하부축;하측이 상기 우측 회전체의 돌기에 고정되어, 상기 우측 회전체의 회전에 따라 움직이는 우측 하부축;하측이 상기 좌측 하부축의 상측과 힌지결합되고, 상기 좌측 하부축의 움직임에 따라 상하부로 수직하게 움직이는 좌측 상부축;하측이 상기 우측 하부축의 상측와 힌지결합되고, 상기 우측 하부축의 움직임에 따라 상하부로 수직하게 움직이는 우측 상부축;일측이 상기 좌측 상부축 상부에 고정되고, 타측이 상기 우측 상부축 상부에 고정되며, 상기 그물을 하부에서 받히고, 상기 좌측 상부축 및 상기 우측 상부축의 움직임에 따라 상부로 이동하여 상기 그물을 아래에서 위로 치는 받침 털이대;상기 메인 프레임부에 고정되어 상기 받침 털이대 및 상기 좌측 하부축 사이에 위치하며, 상기 좌측 상부축이 상하부로 직선 운동하게 가이드 하는 좌측 가이드부; 및상기 메인 프레임부에 고정되어 상기 받침 털이대 및 상기 우측 하부축 사이에 위치하며, 상기 우측 상부축이 상하부로 직선 운동하게 가이드 하는 우측 가이드부를 포함하는 것을 특징으로 하는 어류털이장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

399/1150 Row 399: application_number: 1020217005050, combined_string: invention_title: 불임 자손을 생성하는 방법 abstract: 본 개시는 불임 어류,　갑각류,　또는 연체동물을 생성하는 방법을 제공한다.　상기 방법은　(i)　가임 반접합 돌연변이된(fertile hemizygous mutated)　암컷 어류,　갑각류,　또는 연체동물과　(ii)　가임 반접합 돌연변이된 수컷 어류,　갑각류,　또는 연체동물을 교배시키는 단계,　유전자형 선발(genotypic selection)을 통해 동형접합인(homozygous)　암컷 전구체(progenitor)를 선발하는 단계,　불임 어류,　갑각류,　또는 연체동물을 생성하기 위해 상기 동형접합인 암컷 전구체를 교배시키는 단계를 포함한다.　상기 돌연변이는 원시생식세포(PGC)　발달 유전자의 모계영향을 결손시키고,　동형접합인 전구체의 생존율,　성 결정,　가임성,　또는 이들의 조합을 손상하지 않는다.　또한 본 개시는 불임화된 담수 및 해양 생명체들을 생성하는데 사용하기 위한 담수 및 해양 생명체로 친어(broodstock)를 생성하는 방법, 및 상기 친어를 제공한다. claims: 불임 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, (i) 가임 반접합 돌연변이된(fertile hemizygous mutated) 암컷 어류, 갑각류, 또는 연체동물과 (ii) 가임 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배(breeding)시키는 단계; 유전자형 선발(genotypic selection)을 통해 동형접합인(homozygous) 암컷 전구체(progenitor)를 선발하는 단계; 및불임 어류, 갑각류, 또는 연체동물을 생성하기 위해 상기 동형접합인 암컷 전구체를 교배시키는 단계를 포함하고,상기 돌연변이는 원시생식세포(primordial germ cell, PGC) 발달 유전자(development gene)의 모계영향(maternal-effect)을 결손시키며(disrupt), PGC 발달 유전자의 모계영향을 결손시키는 상기 돌연변이는 동형접합인 전구체의 생존율(viability), 성 결정(sex determination), 가임성(fertility), 또는 이들의 조합에 손상을 주지 않는 것인, 방법.불임 어류, 갑각류, 또는 연체동물을 생성하기 위한 가임 동형접합 돌연변이된(fertile homozygous mutated) 암컷 어류, 갑각류, 또는 연체동물로서, 상기 돌연변이는 원시생식세포 발달 유전자의 모계영향을 줄이기 위해 원시생식세포 발달 유전자의 전사 후 조절을 결손시키고,상기 원시생식세포 발달 유전자의 전사 후 조절을 결손시키는 돌연변이는 상기 유전자의 체세포 기능(somatic function)을 손상하지 않는 것인, 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물.불임 어류, 갑각류, 또는 연체동물을 생성하기 위해, 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물을 교배시키는 방법으로서, 상기 방법은 불임 어류, 갑각류, 또는 연체동물을 생성하기 위해, 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물을, 야생형의 수컷 어류, 갑각류, 또는 연체동물, 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물, 또는 동형접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물과 교배시키는 단계를 포함하고,상기 돌연변이는 원시생식세포 발달 유전자의 모계영향을 결손시키며, PGC 발달 유전자의 모계영향을 결손시키는 상기 돌연변이는 동형접합인 전구체의 생존율, 성 결정, 가임성, 또는 이들의 조합에 손상을 주지 않는 것인, 방법.불임 어류, 갑각류, 또는 연체동물을 생성하는 가임 동형접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물을 생성하는 방법으로서, (i) 가임 반접합 돌연변이된 암컷 어류, 갑각류, 또는 연체동물 암컷과 (ii) 가임 반접합 돌연변이된 수컷 어류, 갑각류, 또는 연체동물을 교배시키는 단계; 및유전자형 선발을 통해 동형접합인 암컷 전구체를 선발하는 단계를 포함하고,상기 돌연변이는 원시생식세포 발달 유전자의 모계영향을 결손시키며, PGC 발달 유전자의 모계영향을 결손시키는 상기 돌연변이는 동형접합인 전구체의 생존율, 성 결정, 가임성, 또는 이들의 조합에 손상을 주지 않는 것인, 방법., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

400/1150 Row 400: application_number: 1020190076063, combined_string: invention_title: 큰징거미새우 전용 부화 수조 abstract: 큰징거미새우에게 스트레스를 주지 않고 모패와 치패를 분리할 수 있는 큰징거미새우 전용 부화 수조가 개시된다. 본 발명은 상면이 개방되고, 모패부 및 치패부를 포함하는 본체; 상기 본체의 내측 양측면 중앙부에 설치되고, 상기 모패부 및 상기 치패부를 구획하는 제1칸막이; 상기 치패부의 상면 모서리에 횡방향으로 설치된 집어등; 및 상기 본체의 전단벽에 형성된 모임조;를 포함하는 큰징거미새우 전용 부화 수조를 제공한다. claims: 상면이 개방되고, 모패부 및 치패부를 포함하는 본체;상기 본체의 내측 양측면 중앙부에 설치되고, 상기 모패부 및 상기 치패부를 구획하는 제1칸막이;상기 치패부의 상면 모서리에 횡방향으로 설치된 집어등; 및상기 본체의 전단벽에 형성된 모임조;를 포함하는 큰징거미새우 전용 부화 수조로서,상기 치패부는 하면에 제1배수구가 형성되고, 상기 제1배수구 상면에 차단망이 설치되고,상기 모임조는 상면이 개방되고, 상기 모임조는 하면에 제2배수구, 순환여과구 및 수위조절구가 형성되고, 상기 수위조절구 상면은 수위조절 파이프와 연결되고, 상기 수위조절구 하면은 상기 제1배수구의 하면과 파이프를 통해 연결된 것을 특징으로 하는 큰징거미새우 전용 부화 수조., Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

401/1150 Row 401: application_number: 1020190073873, combined_string: invention_title: 부유식 해상구조물을 활용한 어류 양식 설비 abstract: 본 발명은 부유식 선박, 바지선, 해양철구조물과 같이 해상에서 이동이 가능한 해상구조물의 내부에 사료, 해수 및 산소를 공급하며, 배설물, 사료찌꺼기 등과 같은 폐기물을 외부로 배출시킴으로써 항시 청결한 양식 환경이 유지되도록 하고, 특히 양식조에 공급되는 해수의 흡입관의 심도를 조절하여 어류의 양식에 필요한 적절한 양식수의 온도 조정이 가능하며, 해상구조물의 평형수 조절을 통해 양식조 내의 수위 조절이 가능하도록 하는 부유식 해상구조물을 활용한 어류 양식 설비에 관한 것이다. claims: 해상구조물의 내부에 마련되며, 내측으로 치어를 공급하기 위한 치어 공급 파이프를 포함하는 양식조; 및상기 해상구조물의 외측에서 외부의 물을 흡입하여 상기 양식조 내로 물을 공급하며, 상기 해상구조물의 외측면에 마련되는 흡입 펌프, 상기 흡입 펌프와 연결되며 하측 방향으로 연장됨에 따라 상기 해상구조물 외부의 물을 흡입하는 흡입관, 상기 흡입관과 흡입펌프가 연결되며 상기 양식조 내로 물을 배출하는 배출관 및 상기 흡입 펌프를 감싸며 상기 해상구조물 외측의 물이 상기 흡입 펌프에 유입되는 것을 방지하는 밀폐 박스를 포함하는 물 공급부;를 포함하며,상기 양식조의 하측에는 다수의 물 배출용 관통홀이 형성됨에 따라, 상기 해상구조물의 평형수 변화에 의해 상기 양식조 내의 수위가 조절되고,상기 흡입관의 하측 말단부에는 물 흡입구가 위치하며, 상기 흡입관 중간에 물을 흡입하여 양식조에 공급되는 수온을 조절하는 개폐형 흡입개구부가 형성되는 것을 특징으로 하는, 부유식 해상구조물을 활용한 어류 양식 설비., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

402/1150 Row 402: application_number: 1020190068918, combined_string: invention_title: 수조순환장치 abstract: 본 발명은 수조 내부의 수조수를 순환시켜 어류생식조건을 형성하며, 수조수 오염 방지를 목적으로 한다. 구체적으로 상부가 개방되며, 수조수를 수용하는 수조와 상기 수조 내부에 위치하며, 수조수를 순환시키는 추진장치와 수조 내부에 위치하며, 수조수 를 흡입하는 흡입장치와 추진장치 및 흡입장치 사이에 위치하여 수조수를 유동하는 순환장치를 구비한다. claims: 상부가 개방되며, 수조수(20)를 수용하는 수조(10);상기 수조(10) 내부에 위치하며, 수조수(20)를 순환시키는 추진장치(100);상기 수조(10) 내부에 위치하며, 수조수(20)를 흡입하는 흡입장치(200);상기 추진장치(100) 및 흡입장치(200) 사이에 위치하여 수조수(20)를 유동하는 순환장치(300);를 포함하고,상기 추진장치(100)는 복수로 형성되며, 수조(10) 내부에 수용되며, 수조수(20)를 분사시키는 추진부(120);상기 순환장치(300) 및 상기 복수의 추진부(120) 사이를 연통하는 분배부(130);상기 복수의 추진부(120)를 상기 수조(10)에 일체로 고정하는 고정부(160);를 포함하고,상기 추진부(120)는 내부에 고압의 수조수(20)가 채워지며, 일면에 내부배출개구가 형성되며, 나선형으로 형성된 케이스(121);상기 케이스(121)와 이격 설치되고, 상기 내부배출개구 위치에 중첩된 판재로 형성되며, 상단에서 하단으로 향할수록 상기 케이스(121)와 이격 간격이 상이 하게 형성된 추진판(122);상기 추진판(122) 단부 및 상기 케이스(121)에 결합되며, 상기 추진판(122)을 회동시키는 회전축(140);상기 회전축(140) 및 추진판(122)을 회동시키는 엑츄에이터;상기 케이스(121) 내부에 형성되며, 수조수(20)의 방출 방향을 조절하는 복수의 조절판(150);을 포함하는 수조순환장치., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

403/1150 Row 403: application_number: 1020190068027, combined_string: invention_title: 홍해삼 수정란 생산방법 abstract: 홍해삼 어미관리의 체계화를 통해 종묘생산자가 원하는 시기에 양질의 수정란을 계획생산이 가능하여 양식산업 및 종묘산업화로서 견인 가능하다. 또한 조기 수정란 생산을 통하여 당해 연도에 필요한 방류 및 중간육성용 대형종묘를 생산함으로서 방류효과를 증대시키고, 마을어장 자원조성량 증대를 통해 가공산업, 수출, 관광, 미용 및 건강식품 등의 관련산업 유발효과를 통해 시너지 효과를 기대할 수 있다. claims: 수조에서 사육수를 뺀 후, 해삼이 공기중에 노출된 채로 1시간 방치하는 간출자극을 진행한 후, 모삼이 수용된 수조에 해수를 가득 채운 후 배합사료의 농도를 100-150ppm으로 조절한 사료현탁액을 공급하는 사료현탁액 자극의 순서로 이루어지는 것을 특징으로 하는 홍해삼 수정란 생산방법수조에서 사육수를 뺀 후, 해삼이 공기중에 노출된 채로 1시간 방치하는 간출자극을 진행한 후, 모삼이 수용된 수조에 해수를 가득 채운 후, 배합사료의 농도를 100-150ppm으로 조절한 사료 현탁액을 공급하는 사료현탁액 자극 후, 모삼이 수용된 수조내에 공기주입과 해수주입을 중단하고 3 - 5시간 동안 방치하는 무에어, 무환수자극의 순서로 이루어지는 것을 특징으로 하는 홍해삼 수정란 생산방법, Ltext: 어업, prediction: '어업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

404/1150 Row 404: application_number: 1020190068095, combined_string: invention_title: 바이오플락을 이용한 새우 양식장 abstract: 본 발명은 바이오플락을 이용한 새우 양식장에 관한 것으로, 본 발명이 해결하고자 하는 과제는 수조에 새우와 함께 양식되는 미생물이 뭉쳐서 가라앉지 않게 컨트롤 할 수 있으며, 양식장의 확장 없이 새우의 탈피할 수 있는 공간과 탈피 후 쉴 수 있는 공간을 마련하는데 있다.일례로, 바이오플락 양식을 위한 미생물 및 양식수를 수용하고, 면적이 서로 다르며 서로 분리된 다수의 양식수조; 및 상기 양식수조 사이에 형성되고, 상기 양식수조와의 격벽 일부가 개방되어 연결되고, 상기 양식수조보다 깊게 형성되며, 잉여 양식수를 상기 양식수조로 공급하기 위한 다수의 침전조를 포함하는 바이오플락을 이용한 새우 양식장을 개시한다. claims: 바이오플락 양식을 위한 미생물 및 양식수를 수용하고, 면적이 서로 다르며 서로 분리된 다수의 양식수조; 및상기 양식수조 사이에 형성되고, 상기 양식수조와의 격벽 일부가 개방되어 연결되고, 상기 양식수조보다 깊게 형성되며, 잉여 양식수를 상기 양식수조로 공급하기 위한 다수의 침전조를 포함하고,상기 양식수조와 상기 침전조 간의 격벽 상단이 개방되어 상기 격벽 상단에 단차부가 형성되고, 상기 단차부를 통해 상기 침전조가 상기 양식수조와 연결되고,상기 양식수조의 내측벽은 상기 양식수조의 바닥면을 향해 45° 내지 75°의 경사각으로 기울어진 경사면을 갖도록 형성된 것을 특징으로 하는 바이오플락을 이용한 새우 양식장., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

405/1150 Row 405: application_number: 1020217000447, combined_string: invention_title: 동일한 경쇄 I을 갖는 다양한 항체를 생산하기 위한 트랜스제닉 동물 abstract: 본원은 무엇보다도 항체 다양화를 위해 유전자 전환을 사용하는 트랜스제닉 동물에서 항체 다양화를 최소화하기위한 전략을 제공한다. 일부 실시양태에서, 상기 동물은 내인성 면역 글로불린 경쇄 유전자 좌위(endogenous immunoglobulin light chain locus)를 포함하는 게놈(genome)을 포함한다: (a) 경쇄 가변 영역을 인코딩하는 핵산을 포함하는 기능성 면역글로블린 경쇄 유전자; 및 (b) 상기 기능성 면역글로불린 경쇄 유전자에 작동가능하게 연결되고, 유전자 전환에 의해, 경쇄 가변 영역을 인코딩하는 상기 핵산에 뉴클레오티드 서열을 기증하는 다수의 유사 유전자(pseudogenes)를 포함하며, 상기 유사 유전자가 상기 기능성 면역글로불린 경쇄 유전자의 상류(upstream) 또는 하류(downstream)에 있으며, 각각의 상기 유사 유전자는 (a)의 기능성 면역글로불린 경쇄 유전자의 경쇄 가변 영역과 동일한 아미노산을 인코딩한다. 다른 실시양태에서, 상기 유전자좌는 상기 경쇄에 대한 코딩 서열이 직렬 어레이를 가질 수 있다. claims: 내인성 면역 글로불린 경쇄 유전자 좌위(endogenous immunoglobulin light chain locus)를 포함하는 게놈(genome)을 포함하는 항체 다양화를 위해 유전자 변환을 사용하는 트랜스제닉 동물로서, (a) 경쇄 가변 영역을 인코딩하는 핵산을 포함하는 기능성 면역글로블린 경쇄 유전자; 및(b) 상기 기능성 면역글로불린 경쇄 유전자에 작동가능하게 연결되고, 유전자 전환에 의해, 경쇄 가변 영역을 인코딩하는 상기 핵산에 뉴클레오티드 서열을 기증하는 다수의 유사 유전자(pseudogenes)를 포함하며, 상기 유사 유전자가 상기 기능성 면역글로불린 경쇄 유전자의 상류(upstream) 또는 하류(downstream)에 있으며, 각각의 상기 유사 유전자는 (a)의 기능성 면역글로불린 경쇄 유전자의 경쇄 가변 영역과 동일한 아미노산을 인코딩하는, 트랜스제닉 동물.(a) 제1항 내지 제15항 중 어느 한 항의 트랜스제닉 동물을 항원으로 면역화하는 단계;(b) 상기 항원에 특이적으로 결합하는 항체를 상기 동물로부터 수득하는 단계를 포함하는 방법.제1항 내지 제15항 중 어느 한 항의 트랜스제닉 동물에 의해 생성된 폴리클로날 항체로서, 상기 항혈청(antiserum) 내 항체의 적어도 50% 이상이 실질적으로 동일한 경쇄 서열을 갖는 폴리클로날 항체.제1항 내지 제15항 중 어느 한 항의 트랜스제닉 동물에 의해 생성된 적어도 1000개 이상의 B 세포 집단으로서, 상기 B 세포의 적어도 50% 이상이 실질적으로 동일한 경쇄 서열을 갖는 항체를 생성하는 집단.제1항 내지 제15항 중 어느 한 항의 동물로부터 분리된 B 세포.제1항 내지 제15항 어느 한 항의 동물로 생성된 모노클로날 항체., Ltext: 어업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

406/1150 Row 406: application_number: 1020217001018, combined_string: invention_title: 유전자 변환에 의한 자율 중쇄 가변 도메인의 수정에 의한 항체 생산 abstract: 본원은 무엇보다도 B 세포(B cell)를 포함하는, 항체 다양화를 위해 유전자 변환을 사용하는 트랜스제닉 동물을 제공하며, 내인성 면역 글로불린 중쇄 유전자 좌위는 다음을 포함한다: (a) 자율 중쇄(autonomous heavy chain, AHC) 가변 도메인을 인코딩하는 핵산을 포함하는 기능성 면역 글로불린 중쇄 유전자; 및 (b)　상기 기능성 면역글로불린 중쇄 유전자에 작동가능하게 연결되고, 유전자 전환에 의해 (a)의 AHC 가변 도메인을 인코딩하는 핵산에 뉴클레오티드 서열을 제공하는 복수의 유사 유전자(pseudogenes)로서, 상기 유사 유전자는 상기 기능성 면역글로불린 중쇄 유전자의 상류(upstream) 또는 하류(downstream)에 존재한다. claims: B 세포(B cell)를 포함하는 항체 다양화를 위해 유전자 변환을 사용하는 트랜스제닉 동물로서, 내인성 면역 글로불린 중쇄 유전자 좌위(endogenous immunoglobulin heavy chain locus)는:(a) 자율 중쇄(autonomous heavy chain, AHC) 가변 도메인을 인코딩하는 핵산을 포함하는 기능성 면역 글로불린 중쇄 유전자; 및(b)　상기 기능성 면역글로불린 중쇄 유전자에 작동가능하게 연결되고, 유전자 전환에 의해 (a)의 AHC 가변 도메인을 인코딩하는 핵산에 뉴클레오티드 서열을 제공하는 복수의 유사 유전자(pseudogenes)를 포함하며, 상기 유사 유전자는 상기 기능성 면역글로불린 중쇄 유전자의 상류(upstream) 또는 하류(downstream)에 존재하는 것인, 트랜스제닉 동물.(a) 제1항 내지 제23항 중 어느 한 항의 트랜스제닉 동물을 항원으로 면역화하는 단계;(b) 상기 항원에 특이적으로 결합하는 항체를 상기 동물로부터 수득하는 단계를 포함하는 방법.제1항 내지 제23항 중 어느 한 항의 트랜스제닉 동물에 의해 생산된 모노클로날 또는 폴리클로날 항체로서, 상기 항체가 자율 중쇄 (autonomous heavy chain, AHC) 가변 도메인 항체인 모노클로날 또는 폴리클로날 항체.제1항 내지 제23항 중 어느 한 항의 동물로부터 분리된 B 세포., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

407/1150 Row 407: application_number: 1020190062035, combined_string: invention_title: 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초 제조방법 및 그 세라믹 인공어초 abstract: 본 발명은 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초 제조방법 및 그 세라믹 인공어초에 관한 것으로 인공어초의 표면에 해조류 등의 활착성이 우수하면서도 성장성을 도모하며, 어류 등의 산란장 및 휴식장을 마련하도록 하며, 인공어초의 적층 및 연결이 용이한 구조를 갖도록 하기 위하여, 세라믹파우더 100중량부를 기준으로 칼슘, 인, 칼륨, 나트륨, 염소, 마그네슘, 철, 아이오딘, 구리, 아연, 코발트, 망간 중 어느 하나 또는 어느 하나 이상의 미네랄파우더를 5∼8중량부 첨가하여 혼합파우더를 제조 하는 단계(S1); 상기 혼합파우더를 배합기에 투입하고 가수하여 함수율 19∼20％의 상태로 배합하는 단계(S2); 상기 배합된 혼합파우더를 진공토련기에 투입하여 공기를 뽑아내고, 상기 진공토련기의 압출구 전단에 설치된 어초형상의 사출금형을 통하여 인공어초 반제품을 사출성형하는 1차성형단계(S3); 절단기를 이용하여 상기 1차성형된 인공어초 반제품을 요구되는 길이로 절단하는 2차성형단계(S4); 직립기를 이용하여 상기 2차성형된 인공어초 반제품을 건조판의 상부로 일으켜 세워 직립시킨 다음, 상기 인공어초 반제품을 건조대차에 적재하는 단계(S5); 상기 인공어초 반제품이 적재된 건조대차를 건조실로 이송하여 건조하는 단계(S6); 상기 건조된 인공어초 반제품을 소성컨테이너에 적재한 후, 상기 적재된 소성컨테이너를 가마에 이송하고 이를 950∼1030℃ 사이에서 산화소성하여 인공어초를 완성하는 단계(S7);를 포함하여 이루어짐을 특징으로 한다. claims: 세라믹 파우더를 포함한 혼합파우더를 제조하는 단계(S1); 상기 혼합파우더를 배합기에 투입하고 가수하여 함수율 19∼20％의 상태로 배합하는 단계(S2); 상기 배합된 혼합파우더를 진공토련기에 투입하여 공기를 뽑아내고, 상기 진공토련기의 압출구 전단에 설치된 어초형상의 사출금형을 통하여 인공어초 반제품을 사출성형하는 1차성형단계(S3); 절단기를 이용하여 상기 1차성형된 인공어초 반제품을 400~600mm의 길이로 절단하는 2차성형단계(S4); 상기 2차성형된 인공어초 반제품을 적재하는 단계(S5); 상기 인공어초 반제품이 적재된 건조대차를 건조실로 이송하여 건조하는 단계(S6); 상기 건조된 인공어초 반제품을 소성컨테이너에 적재한 후, 상기 적재된 소성컨테이너를 가마에 이송하고 이를 산화소성하여 인공어초를 완성하는 단계(S7);를 포함하여 이루어지는 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초 제조방법에 있어서,상기 혼합파우더를 제조 하는 단계(S1)는 세라믹파우더 100중량부를 기준으로 인, 나트륨, 염소, 아이오딘, 구리, 아연, 코발트, 망간 중 어느 하나 또는 어느 하나 이상의 미네랄파우더를 5∼8중량부 첨가하여 혼합파우더를 제조한 후, 상기 혼합파우더 100중량부를 기준으로 바인더를 9~12중량부 혼합하되, 상기 바인더는 점토와 산청토를 혼합하고,상기 적재하는 단계(S5)는, 상기 2차성형된 인공어초 반제품을 건조판의 상부로 일으켜 세워 직립시킨 다음, 상기 인공어초 반제품을 건조대차에 적재하며,상기 건조하는 단계(S6)는 상기 인공어초 반제품이 적재된 건조대차를 1차건조실에서 6일간 숙성한 다음 건조하고, 2차건조실에서 6일간 온도 70℃, 습도 15%에서 건조하고,상기 완성하는 단계(S7)는 950∼1030℃ 사이에서 25시간 산화소성한 후, 상온까지 냉각하여 요출하며,상기 인공어초는 단면이 6각관 형태로 형성되며, 상기 6각관 형태로 형성된 인공어초의 적층 시 상호간에 돌부(17) 및 홈부(19) 결합구조로 결합되도록 구성되고,상기 인공어초의 내외측 표면에 다수의 정형 또는 비정형의 홈형태로 된 스크래치홈부(92)를 형성하여, 상기 스크래치홈부(92) 내에서 해조류가 활착되도록 구성하는 것을 특징으로 하는 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초 제조방법.세라믹파우더 100중량부를 기준으로 칼슘, 인, 나트륨, 염소, 아이오딘, 구리, 아연, 코발트, 망간 중 어느 하나 또는 어느 하나 이상의 미네랄파우더를 5∼8중량부 첨가하여 혼합파우더를 제조 하고, 상기 혼합파우더를 배합기에 투입하고 가수하여 함수율 19∼20％의 상태로 배합하며, 상기 배합된 혼합파우더를 진공토련기에 투입하여 공기를 뽑아내고, 상기 진공토련기의 압출구 전단에 설치된 어초형상의 사출금형을 통하여 인공어초 반제품을 사출성형하여 1차성형하고, 절단기를 이용하여 상기 1차성형된 인공어초 반제품을 요구되는 길이로 절단하는 2차성형하며, 직립기를 이용하여 상기 2차성형된 인공어초 반제품을 건조판의 상부로 일으켜 세워 직립시킨 다음, 상기 인공어초 반제품을 건조대차에 적재하고, 상기 인공어초 반제품이 적재된 건조대차를 건조실로 이송하되, 1차건조실에서 6일간 숙성한 다음 건조하고, 2차건조실에서 6일간 온도 70℃, 습도 15%에서 건조하며, 상기 건조된 인공어초 반제품을 소성컨테이너에 적재한 후, 상기 적재된 소성컨테이너를 가마에 이송하고 이를 950∼1030℃ 사이에서 25시간 산화소성한 다음 상온까지 냉각하여 요출하여 구성되고,상기 혼합파우더 100중량부를 기준으로 바인더를 9~12중량부 혼합하되, 상기 바인더는 점토와 산청토를 혼합하여 구성되며,상기 인공어초는 단면이 6각관 형태로 형성되며, 상기 6각관 형태로 형성된 인공어초의 적층 시 상호간에 돌부(17) 및 홈부(19) 결합구조로 결합되도록 구성되고,상기 인공어초의 내외측 표면에 다수의 정형 또는 비정형의 홈형태로 된 스크래치홈부(92)를 형성하여, 상기 스크래치홈부(92) 내에서 해조류가 활착되도록 구성하는 것을 특징으로 하는 해조류의 활착성과 성장성이 우수한 적층 가능한 구조의 세라믹 인공어초., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

408/1150 Row 408: application_number: 1020190053290, combined_string: invention_title: 패류 부유기 인공종묘 양식설비 abstract: 본 발명은 바다와 인접한 육상의 실내 공간에 설치되는 것으로, 바다로부터 해수를 공급받아 패류의 부유기(400㎛ 이하의 길이) 유생을 양성하는 인공종묘 양식설비에 있어서, 해수를 수용하기 위한 공간부를 갖는 통형상으로 이루어지며, 상기 공간부 외벽의 일측에 관통형성된 배수관을 갖는 수조부; 상기 수조부의 상부에 길이방향을 따라 복수열로 설치되어 바다로부터 공급된 해수를 상기 수조부에 공급하되, 저면에는 길이방향을 따라 일정 간격으로 복수개의 배수공이 관통형성되어 하방으로 상기 해수가 배수되도록 하는 해수공급부; 및 상기 해수공급부의 배수공과 대응하는 위치에 배치되도록 상기 수조부의 내부에 수용되되, 저면에는 상기 유생보다 작은 면적의 구멍을 갖는 그물망이 형성되어 일정 개체수의 유생을 수용하는 유생수용유닛;을 포함하는 것을 기술적 요지로 한다. claims: 바다와 인접한 육상의 실내 공간에 설치되는 것으로, 바다로부터 해수를 공급받아 패류의 부유기(400㎛ 이하의 길이) 유생을 양성하는 인공종묘 양식설비에 있어서,해수를 수용하기 위한 공간부를 갖는 통형상으로 이루어지며, 상기 공간부 외벽의 일측에 관통형성된 배수관을 갖는 수조부;상기 수조부의 상부에 길이방향을 따라 복수열로 설치되어 바다로부터 공급된 해수를 상기 수조부에 공급하되, 저면에는 길이방향을 따라 일정 간격으로 복수개의 배수공이 관통형성되어 하방으로 상기 해수가 배수되도록 하는 해수공급부; 및상기 해수공급부의 배수공과 대응하는 위치에 배치되도록 상기 수조부의 내부에 수용되되, 저면에는 상기 유생보다 작은 면적의 구멍을 갖는 그물망이 형성되어 일정 개체수의 유생을 수용하는 유생수용유닛;을 포함하는 것을 특징으로 하는 패류 부유기 인공종묘 양식설비., Ltext: 어업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

409/1150 Row 409: application_number: 1020190053060, combined_string: invention_title: 3D 프린터에 의해 제조되는 인공어초 abstract: 본 발명은 3D 프린터에 의해 제조되는 인공어초에 관한 것으로, 3D 프린터에 의해 제조되며, 하부로 갈수록 면적이 증가하는 하광상협의 기둥형태를 갖는 몸체와, 상기 몸체의 내부에 형성되는 중공부와, 상기 중공부와 몸체의 외부를 연통시키는 상기 몸체의 측면에 형성된 다수의 관통 홀 및 상기 중공부에 형성되고 상기 몸체의 내측면을 지지하는 보강 지지체를 포함하는 것을 특징으로 하는 3D 프린터에 의해 제조되는 인공어초가 개시된다. claims: 3D 프린터에 의해 제조되며,하부로 갈수록 면적이 증가하는 하광상협의 기둥형태를 갖는 몸체;상기 몸체의 내부에 형성되는 중공부;상기 중공부와 몸체의 외부를 연통시키는 상기 몸체의 측면에 형성된 다수의 관통 홀; 및상기 중공부에 형성되고 상기 몸체의 내측면을 지지하는 보강 지지체;를 포함하며,상기 몸체는 표면에 다수의 요철부가 형성되고,상기 몸체는 다각 기둥형태를 갖되, 상기 보강 지지체는 몸체의 면과 면이 만나는 경계로부터 몸체의 하부를 향해 형성되며,상기 보강 지지체는 상기 몸체의 무게중심이 몸체의 하부에 위치하도록 형성되고,상기 몸체는해저면에 안치되는 평판형의 바닥부;상기 바닥부의 가장자리 둘레에 일정 간격을 두고 상부로 연장되는 메인 지지체; 및상기 메인 지지체의 양측면에 형성되어 상기 메인 지지체의 상단을 이웃한 메인 지지체의 상단 및 상기 바닥부와 일체로 연결하는 측면 지지체;를 포함하며,상기 측면 지지체는수산생물 및 해류가 출입하며 상기 측면 지지체의 상하방향에 걸쳐 형성되는 제1관통 홀; 및상기 제1관통 홀의 주변에 형성되며 상기 제1관통 홀에 비해 작은 개구 면적을 형성하는 제2관통 홀;을 포함하고,상기 제2관통 홀은 타원형, 원형, 삼각형 중 적어도 어느 하나로 형성되며,상기 바닥부는 해저면과 상기 중공부를 연통시키는 제3관통 홀이 형성되고,상기 몸체와 보강 지지체는 혼합물 전체 부피의 2.8 ~ 4.9%의 결합재와, 혼합물 전체 부피의 70.0 ~ 78.5%의 산업부산물과, 혼합물 전체 부피의 0.28 ~ 0.49 %의 콘크리트용 섬유와, 혼합물 전체 부피의 0.02 ~ 0.05 %의 혼화제와, 혼합물 전체 부피의 15.7 ~ 21.0%의 물과 잔량으로서 공기를 포함하여 구성되고,상기 혼화제는 조강제, 수축저감제, 고유동화제가 1 : 1 : 1의 중량비로 혼합된 것을 특징으로 하는 3D 프린터에 의해 제조되는 인공어초., Ltext: 어업, prediction: 어업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

410/1150 Row 410: application_number: 1020210002476, combined_string: invention_title: 액상소석회를 이용한 조류독감 및 구제역 바이러스 소독제 및 그의 제조 방법 abstract: [기술분야/해결과제]본 발명은 액상소석회를 이용한 조류독감 및 구제역 바이러스 소독제 및 그의 제조 방법에 관한 것으로, 액상소석회(Ca(OH)2)에 이온화 미네랄 입자와 시안산나트륨(NaOCN)를 혼합하여 환경오염을 발생시키지 않고 조류독감(AI)과 구제역(FMD) 및 아프리카돼지열병(ASF) 바이러스를 살균 및 소독할 수 있다.[해결수단]본 발명에 의한 조류독감 및 구제역 바이러스 소독제의 제조 방법은, 액상소석회를 이용한 조류독감 및 구제역 바이러스 소독제의 제조 방법에 있어서, (a) 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 후 10∼30분 동안 원심분리기에서 2000RPM 이상의 고속교반으로 수화 및 분쇄를 함께 진행하여 입도 1000메쉬 이상의 액상화를 갖는 소독을 위한 액상소석회(Ca(OH)2)를 얻는 단계; (b) 조개류 껍질을 1,000℃∼1,300℃에서 2시간 동안 소성하고 분쇄기로 분쇄하여 입도 100∼200메쉬의 분말을 만든 후 초음파 분쇄하여 나노화한 다음 전기분해하여 미네랄 입자를 이온화하고, 상기 액상소석회(Ca(OH)2)에 상기 이온화한 미네랄 입자 3∼5중량%를 혼합하는 단계; (c) 상기 (b)단계의 혼합물에 시안산나트륨(NaOCN) 0.5∼1.0중량%를 혼합하는 단계; 및 (d) 상기 (c)의 혼합물에 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 입도 100∼200메쉬의 숯 분말 5∼10중량%를 혼합하는 단계;를 포함한다.[기대효과]본 발명에 따르면, 환경오염을 발생하지 않고 조류독감(AI)과 구제역(FMD) 및 아프리카돼지열병(ASF) 바이러스를 효과적으로 소독할 수 있는 효과가 있다. claims: 액상소석회를 이용한 조류독감 및 구제역 바이러스 소독제의 제조 방법에 있어서,(a) 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 후 10∼30분 동안 원심분리기에서 2000RPM 이상의 고속교반으로 수화 및 분쇄를 함께 진행하여 입도 1000메쉬 이상의 액상화를 갖는 소독을 위한 액상소석회(Ca(OH)2)를 얻는 단계;(b) 조개류 껍질을 1,000℃∼1,300℃에서 2시간 동안 소성하고 분쇄기로 분쇄하여 입도 100∼200메쉬의 분말을 만든 후 초음파 분쇄하여 나노화한 다음 전기분해하여 미네랄 입자를 이온화하고, 상기 액상소석회(Ca(OH)2)에 상기 이온화한 미네랄 입자 3∼5중량%를 혼합하는 단계;(c) 상기 (b)단계의 혼합물에 시안산나트륨(NaOCN) 0.5∼1.0중량%를 혼합하는 단계; 및(d) 상기 (c)의 혼합물에 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 입도 100∼200메쉬의 숯 분말 5∼10중량%를 혼합하는 단계;를 포함하는 조류독감 및 구제역 바이러스 소독제의 제조 방법.액상소석회를 이용한 조류독감 및 구제역 바이러스 소독제에 있어서,물(H2O)과 생석회(CaO)가 70∼80중량% : 20∼30중량%의 비율로 혼합된 액상소석회(Ca(OH)2)에 이온화 미네랄 입자 3∼5중량%, 시안산나트륨(NaOCN) 0.5∼1.0중량%, 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 입도 100∼200메쉬의 숯 분말 5∼10중량%이 혼합된,조류독감 및 구제역 바이러스 소독제., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

411/1150 Row 411: application_number: 1020200144876, combined_string: invention_title: 죽염 소금이 포함된 친환경 메추리 사료 조성물 제조 방법 abstract: 본 발명은 죽염 소금이 포함된 친환경 메추리 사료 조성물 및 이를 이용한 메추리알 생산 방법에 관한 것으로, 본 발명에 따른 죽염 등을 포함하는 메추리 사료 조성물 및 이를 이용한 메추리 알의 생산 방법을 통해, 사료를 섭취하는 메추리의 면역력을 높이는 동시에 산란되어 얻어지는 메추리알의 영양학적 가치를 높일 수 있고, 소비자들에게 건강하고 안전한 메추리알을 제공할 수 있다. claims: 죽염, 울금 및 스테비아를 3~5분간 75~85 ℃에서 가열 및 건조하는 단계;건조된 죽염, 울금 및 스테비아를 0.1mm 이하의 입자가 되도록 분쇄하여 분말화하는 단계; 및상기 분말화된 죽염, 울금 및 스테비아를 가금류 기초 사료에 혼합하는 단계를 포함하는,메추리용 사료 조성물의 제조방법으로서,상기 혼합 단계 이후 85~95℃의 편백수 및 편백 오일이 포함된 수증기를 분사하여 가열하는 단계를 추가로 포함하는, 메추리용 사료 조성물의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

412/1150 Row 412: application_number: 1020200139670, combined_string: invention_title: 부숙유기질비료의 살균, 탈취 및 부숙 촉진을 위한 사료 첨가제 및 이의 제조방법 abstract: 본 발명은 수용성 황 분말, 광물성 물질 및 비타민제를 포함하는 사료 첨가제로서, 상기 사료 첨가제를 포함하는 배합사료를 부숙유기질비료에 첨가하는 경우 살균, 탈취 및 부숙 촉진 효과를 제공한다. claims: 사료 원료 및 기능성 사료 첨가제;를 포함하는 배합사료이며,상기 기능성 사료 첨가제는 수용성 황 분말 10 내지 20 중량%, 광물성 물질 60 내지 80 중량% 및 비타민제 10 내지 20 중량%를 포함하고,상기 수용성 황 분말은 자연계 또는 화학정제 과정에서 채집이나 부산물로 만들어진 광물성 유황을 정제 및 건조한 후 10℃ 이하에서 저온 파쇄하여 얻어진 분말이고,상기 광물성 물질은 염류를 포함하는 제1 광물성 물질을 0.05~0.1 중량부; 제일인산칼륨, 제이인산칼륨 및 제삼인산칼륨으로 구성되는 군에서 선택되는 1종 이상을 포함하는 제2 광물성 물질을 1~2 중량부; 아미노산킬레이트, 황산나트륨 및 황산수소나트륨으로 구성되는 군에서 선택되는 1종 이상을 포함하는 제3 광물성 물질을 50~60 중량부; 및 탄산아연, 황산구리(황산동) 및 황산아연으로 구성되는 군에서 선택되는 1종 이상을 포함하는 제4 광물성 물질을 10~20 중량부;를 포함하는 혼합 광물성 물질이며,상기 비타민제는 메나디온(menadion), 메나디온 아황산나트륨염 및 메나디온 아황산 니코틴아마이드로 구성되는 군에서 선택되는 1종 이상을 포함하고,상기 배합사료를 부숙유기질비료에 첨가하는 경우 탈취 효과를 갖는 기능성 배합사료., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

413/1150 Row 413: application_number: 1020200131909, combined_string: invention_title: 배기 장치 포깅 시스템 abstract: 본 발명은 배기 장치 포깅 시스템에 관한 것으로, 포깅 시스템에 의해 먼지 또는 악취를 포함하는 입자를 효율적으로 제거할 수 있는 장점이 있다. claims: 내측에 가축을 기를 수 있도록 형성된 공간을 포함하는 축사(100);축사(100) 내부로부터 형성되는 먼지 또는 악취가스를 포함하는 미세입자(600)를 외부로 배출시키기 위해 외부와 연동 형성된 제1배기구(400);제1배기구(400) 내측에 미세입자(600)가 용이하게 포집되어 이동될 수 있도록 하나 이상 형성된 제1배기팬(300); 및제1배기구(400)를 관통하며, 유체(561)가 제1배기구(400) 내측 방향으로 분사될 수 있도록 형성된 제1연결관(500);을 포함하고,유체(561)가 제1배기구(400) 내측 방향으로 고르게 분사될 수 있도록 제1배기팬(300)과 이격 형성된 피팅(550)을 포함하며,유체(561)는 물, 오일, 약제, 세척제 또는 미생물 분해제 중 선택되는 어느 하나를 포함하고,피팅(550) 일측에 유체(561)가 제1배기구(400) 내부 또는 외부 중 선택되는 어느 하나 이상으로 분사될 수 있도록 형성된 제1분무노즐(560)을 포함하며,제1연결관(500) 또는 피팅(550) 중 선택되는 어느 하나 이상의 외측에 연동 형성된 제1온수관(700)을 포함하고,제1연결관(500) 일측 또는 타측 중 선택되는 어느 하나 이상에 유체(561)가 고르게 분사될 수 있도록 관통 형성되며, 제1배기구(400) 내측에 배치되고, 제1배기팬(300)과 마주보는 방향으로 형성된 분사홈을 포함하며,피팅(550)의 양 단부 및 제1연결관(500)을 압력장치에 의해 내경의 변형이 수행되도록 가압하여 형성된 연결통로부(580)를 포함하고,제1온수관(700) 내측에 60~90℃의 항온수가 흐르는 것을 특징으로 하는 배기 장치 포깅 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

414/1150 Row 414: application_number: 1020200130913, combined_string: invention_title: 반려동물 사료공급장치 및 이를 이용한 반려동물 사료공급방법 abstract: 본 발명은 반려동물 사료공급장치 및 이를 이용한 사료공급방법에 관한 것이다.본 발명의 실시예에 따르면, 반려동물 사료공급장치에 있어서, 외형을 형성하는 하우징부; 상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및 상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함한다. claims: 반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하는 반려동물 사료공급장치.외형을 형성하는 하우징부; 상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되고, 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료가 상기 사료보관공간으로부터 배출되며, 상기 사료를 기설정된 양만큼 상기 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및 상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리를 포함하는 반려동물 사료공급장치를 이용한 반려동물 사료공급방법에 있어서,복수의 트레이유닛 어느 하나의 트레이유닛이 상기 사료공급 어셈블리의 하방에 배치되도록 상기 트레이 어셈블리를 회전시키는 제1 트레이 회전 단계;상기 사료공급 어셈블리의 하방에 배치되는 상기 트레이유닛에 기설정된 양의 사료를 공급하는 사료 분배 단계; 및상기 사료 공급이 완료된 상기 트레이유닛이 상기 하우징부에 형성된 배식홀을 통하여 외부로 노출되도록 상기 트레이 어셈블리를 회전시키는 제2 트레이 회전 단계;를 포함하는 반려동물 사료공급방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

415/1150 Row 415: application_number: 1020200124639, combined_string: invention_title: 유해물질 및 해충과 스트레스 해소를 위한 동물전용 브러시 및 그 제조방법 abstract: 본 발명은 축사의 펜스나 벽면의 일측에 장착되어 소나 말 등의 가축의 몸을 비벼서 오염된 변 등의 유해물질 및 진드기 등의 해충을 긁어내거나 가려움 등의 스트레스를 해소할 수 있도록 한 동물전용 브러시 및 그 제조방법에 관한 것이다.즉, 본 발명은 축사에 설치되어 가축의 몸을 비벼댈 수 있는 브러시부를 구비한 브러시 몸체로 이루어지되 상기 브러시 몸체는; 반원형상으로 볼록하게 형성된 상,하부 지지판, 상기 상,하부 지지판의 양측에 각각 연결되고 일정 간격으로 상,하부 지지판이 서로 대응된 위치에 설치되도록 하는 수직 지지대, 상기 상,하부 지지판 및 양측 수직 지지대에 브러시부의 끝단부가 일체로 연결되되 전측에 금속망체로 구비되고 반원형상으로 볼록하게 형성된 브러시부, 상기 상,하부 지지판에 전측이 고정설치되고 후측은 축사의 펜스나 벽면에 장착시키는 장착대를 포함하는 유해물질 및 해충과 스트레스 해소를 위한 동물전용 브러시 및 그 제조방법을 특징으로 한다. claims: 축사에 설치되어 가축의 몸을 비벼댈 수 있는 브러시부(140)를 구비한 브러시 몸체(100)로 이루어지되 상기 브러시 몸체(100)는; 반원형상으로 볼록하게 형성된 상,하부 지지판(110)(120), 상기 상,하부 지지판(110)(120)의 양측에 각각 연결되고 일정 간격으로 상,하부 지지판(110)(120)이 서로 대응된 위치에 설치되도록 하는 수직 지지대(130), 상기 하부 지지판(120)은 수평면을 이루는 내측에 통공부(122)를 형성시켜 브러시부(140)에 의해 가축의 몸에서 탈락되는 각종 이물질이 브러시부(140) 및 하부 지지판(120)에 머무르지 않고 축사 바닥으로 떨어지도록 한 것을 포함하고,상기 상,하부 지지판(110)(120) 및 양측 수직 지지대(130)에 브러시부(140)의 끝단부가 일체로 연결되되 전측에 금속망체로 구비되고 반원형상으로 볼록하게 형성된 브러시부(140)로 이루어지되 상기 금속망체는 파형의 사각철선(142)을 다단으로 횡설하여 마름모 모형(144)으로 된 망사형으로 이루어지고, 상기 마름모 모형(144)은 사각철선(142)의 파형 상단(142a) 전측으로 또 다른 사각철선(142)의 파형 하단(142b)이 중첩되어 전측으로 돌출단부(146)가 형성되며,상기 상,하부 지지판(110)(120)에 전측이 고정설치되고 후측은 축사의 펜스나 벽면에 장착시키는 장착대(150)로 이루어진 것을 특징으로 하는 유해물질 및 해충과 스트레스 해소를 위한 동물전용 브러시.금속제로 된 동물 브러시를 제조하는 것에 있어서,금속판재를 프레스 가공하여서 된 상,하부 지지판(110)(120), 일정 길이의 봉체를 절단 가공하여서 된 수직 지지대(130). 사각철선을 레이저 가공, 용접 및 반원형상으로 만곡지게 절곡하여서 된 브러시부(140)는 전측에 금속망체로 구비되되 금속망체는 파형의 사각철선(142)을 다단으로 횡설하여 마름모 모형(144)으로 된 망사형으로 이루어지고, 상기 마름모 모형(144)은 사각철선(142)의 파형 상단(142a) 전측으로 또 다른 사각철선(142)의 파형 하단(142b)이 중첩되어 전측으로 돌출단부(146)가 형성된 브러시부(140)를 포함하며, 상기 구성요소들의 상,하부 지지판(110)(120) 및 양측 수직 지지대(130)에 브러시부(140)의 끝단부를 일체로 용접하여 전측에 금속망체로 구비되고 반원형상으로 볼록하게 형성된 브러시부를 갖도록 하는 제1구성부재를 구비하는 단계(S1); 금속판재를 프레스 가공 및 절곡하여서 된 장착대(150)로 이루어진 제2구성부재를 구비하는 단계(S2);상기 제1구성부재 및 제2구성부재를 각각 융용아연도금 처리하여 보호피막을 형성하는 단계(S3);상기 제1구성부재의 상,하부 지지판(110)(120)에 전측이 고정설치되고 제2구성부재의 장착대(150) 후측은 축사의 펜스나 벽면에 체결부재(160)로 장착시키는 조립 설치단계(S4);로 이루어진 것을 특징으로 하는 유해물질 및 해충과 스트레스 해소를 위한 동물전용 브러시의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

416/1150 Row 416: application_number: 1020200111424, combined_string: invention_title: 천연광물 미네랄 이온 교환을 통한 성분 강화로 장내 유용미생물을 활성화하는 가축 음용수 제조방법 abstract: 이 발명은 물에 침출되어 있는 토르말린, 일라이트의 천연광물 미네랄 이온 간 교환을 하면서 법제유황과 옻, 그리고 목별자의 유익한 성분을 좀 더 쉽게 가축의 체내에 흡수되도록 강화시켜 가축의 장내 유용미생물이 자극되면서 활성화하는 환경을 조성하고 이를 지속적으로 유지하여 소화력과 면역력을 높이게, 물 90~95WT%에, 2~3㎛의 분말 형태인 천연 광물질들로서, 토르말린 2.5~5.0WT%와, 일라이트 2.5~5.0WT%를 혼합하여 상온에서 5~7시간 경과시킨 후 상기 토르말린과 일라이트 분말을 제거하여 침출액을 만드는 과정과 (S101); 상기 과정(S101)에서 만들어진 침출액 25~65WT%에, 2~3㎛의 분말 형태인 법제유황 15~25WT%와, 옻 추출액 10~25WT%, 그리고 목별자 원액 10~25WT%를 혼합하여 12시간 경과시킨 후 혼합액을 만드는 과정(S102); 및, 상기 과정(S102)에서 만들어진 혼합액 150~250㎖를, 물 20L에 혼합하여 6~7시간 증폭하는 과정(S103);으로 이루어진 것을 특징으로 하는 천연광물 미네랄 이온 교환을 통한 성분 강화로 장내 유용미생물을 활성화하는 가축 음용수 제조방법을 제공한다. claims: 물 90~95WT%에, 2~3㎛의 분말 형태인 천연 광물질들로서, 토르말린 2.5~5.0WT%와, 일라이트 2.5~5.0WT%를 혼합하여 상온에서 5~7시간 경과시킨 후 상기 토르말린과 일라이트 분말을 제거하여 침출액을 만드는 과정과 (S101);상기 과정(S101)에서 만들어진 침출액 25~65WT%에, 2~3㎛의 분말 형태인 법제유황 15~25WT%와, 옻 추출액 10~25WT%, 그리고 목별자 원액 10~25WT%를 혼합하여 12시간 경과 시킨 후 혼합액을 만드는 과정(S102); 및,상기 과정(S102)에서 만들어진 혼합액 150~250㎖를, 물 20L에 혼합하여 6~7시간 증폭하는 과정(S103);으로 이루어진 것을 특징으로 하는 천연광물 미네랄 이온 교환을 통한 성분 강화로 장내 유용미생물을 활성화하는 가축 음용수 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

417/1150 Row 417: application_number: 1020200103333, combined_string: invention_title: 기호도와 보존성이 우수한 원물사료 조성물 abstract: 본 발명은 기호도와 보존성이 우수한 원물사료 조성물에 관한 것으로, 더욱 상세하게는 사료원물 및 상기 사료원물의 표면에 형성되며, 연어가 함유된 코팅혼합물로 이루어진 코팅층으로 이루어진다.상기의 원물사료 조성물은 애완동물의 기호도가 우수할 뿐만 아니라, 보존성이 우수하며 단백질이나 오메가-3와 같은 영양성분이 풍부하게 함유되어 있다. claims: 사료원물; 및상기 사료원물의 표면에 형성되며, 연어가 함유된 코팅혼합물로 이루어진 코팅층;으로 이루어지며,상기 코팅혼합물은 연어 100 중량부, 바인더 5 내지 7 중량부, 가수분해닭간 5 내지 7 중량부, 효모 3 내지 5 중량부, 토코페롤 2 내지 3 중량부 및 감미료 5 내지 7 중량부로 이루어지고,상기 바인더는 쌀전분, 보리전분, 밀전분, 감자전분 및 옥수수전분으로 이루어진 그룹에서 선택된 하나 이상으로 이루어지는 것을 특징으로 하는 기호도와 보존성이 우수한 원물사료 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

418/1150 Row 418: application_number: 1020200102926, combined_string: invention_title: 차아염소산나트륨과 글루콘산나트륨이 함유된 축사소독용 액상소석회 및 그의 제조 방법 abstract: [기술분야/해결과제]본 발명은 차아염소산나트륨과 글루콘산나트륨이 함유된 축사소독용 액상소석회 및 그의 제조 방법에 관한 것으로, 기존의 분말로 된 생석회의 살포 시 가루가 날리고, 균일한 도포의 어려움이 있고, 다량의 도포량이 필요하고, 취급 시 화상의 위험이 있으며, 폭발 위험성이 있어 보관이 까다롭고 어려운 문제점을 해결하기 위한 것이다.[해결수단]본 발명의 축사소독용 액상소석회의 제조 방법은, (a) 물(H2O)과 생석회(CaO)를 혼합하여 액상으로 된 액상소석회(Ca(OH)2)를 제조하는 단계와, (b) 상기 액상소석회(Ca(OH)2)에 차아염소산나트륨(NaOCl)을 혼합하는 단계와, (c) 상기 (b)단계의 혼합물에 글루콘산나트륨(NaC6H11O7)을 혼합하는 단계와, (d) 상기 (c)단계의 혼합물에 글루타르알데히드(C5H8O2)를 혼합하는 단계로 이루어진 축사소독용 액상소석회(Ca(OH)2)의 제조 방법에 있어서, 상기 액상소석회(Ca(OH)2)는, 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 후 10∼30분 동안 원심분리기에서 2000RPM 이상의 고속교반으로 수화 및 분쇄를 함께 진행하여 산화칼슘(CaO) 분말이 80중량% 이상, 수산화칼슘(Ca(OH)2)의 함량이 20±1 내지 30±1 중량%, pH12 내지 13, 비중이 1.08±0.5 내지 1.10±0.5, 불순물이 0.3중량% 이하, 입도가 1000메시(mesh)에 95% 이상 통과하고 수화 및 포졸란 반응을 통해 C-S-H를 형성하고, 상기 차아염소산나트륨(NaOCl)은 상기 액상소석회(Ca(OH)2) 10ℓ를 기준으로 500ｇ 중량을 혼합하고, 상기 글루콘산나트륨(NaC6H11O7)은 상기 액상소석회(Ca(OH)2)와 상기 차아염소산나트륨(NaOCl)의 혼합물에 50ｇ 중량을 혼합하며, 상기 글루타르알데히드(C5H8O2)는 상기 액상소석회(Ca(OH)2), 상기 차아염소산나트륨(NaOCl), 글루콘산나트륨(NaC6H11O7)의 혼합물의 100% 중량에 대해 2∼3% 중량을 혼합하는 것을 특징으로 한다.[기대효과]본 발명에 따르면, 축사내에서 서식하는 유기병원체 및 유해균들을 소독하여 각종 계절성 전염병을 사전에 예방하고 가축들의 면역력을 향상시켜 축산농가의 축산 환경을 개선할 수 있는 효과가 있다. claims: (a) 물(H2O)과 생석회(CaO)를 혼합하여 액상으로 된 액상소석회(Ca(OH)2)를 제조하는 단계와, (b) 상기 액상소석회(Ca(OH)2)에 차아염소산나트륨(NaOCl)을 혼합하는 단계와, (c) 상기 (b)단계의 혼합물에 글루콘산나트륨(NaC6H11O7)을 혼합하는 단계와, (d) 상기 (c)단계의 혼합물에 글루타르알데히드(C5H8O2)를 혼합하는 단계로 이루어진 축사소독용 액상소석회(Ca(OH)2)의 제조 방법에 있어서,상기 액상소석회(Ca(OH)2)는, 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 후 10∼30분 동안 원심분리기에서 2000RPM 이상의 고속교반으로 수화 및 분쇄를 함께 진행하여 산화칼슘(CaO) 분말이 80중량% 이상, 수산화칼슘(Ca(OH)2)의 함량이 20±1 내지 30±1 중량%, pH12 내지 13, 비중이 1.08±0.5 내지 1.10±0.5, 불순물이 0.3중량% 이하, 입도가 1000메시(mesh)에 95% 이상 통과하고 수화 및 포졸란 반응을 통해 C-S-H를 형성하고,상기 차아염소산나트륨(NaOCl)은 상기 액상소석회(Ca(OH)2) 10ℓ를 기준으로 500ｇ 중량을 혼합하고,상기 글루콘산나트륨(NaC6H11O7)은 상기 액상소석회(Ca(OH)2)와 상기 차아염소산나트륨(NaOCl)의 혼합물에 50ｇ 중량을 혼합하며,상기 글루타르알데히드(C5H8O2)는 상기 액상소석회(Ca(OH)2), 상기 차아염소산나트륨(NaOCl), 글루콘산나트륨(NaC6H11O7)의 혼합물의 100% 중량에 대해 2∼3% 중량을 혼합하는,축사소독용 액상소석회의 제조 방법.청구항 1 또는 청구항 4에 기재된 축사소독용 액상소석회의 제조 방법에 의해 제조된 축사소독용 액상소석회., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

419/1150 Row 419: application_number: 1020200087761, combined_string: invention_title: 분쇄 마늘을 이용한 사료첨가제 제조방법 abstract: 본 발명은 분쇄 마늘을 이용한 사료첨가제 제조방법에 관한 것으로, 보다 상세하게는 간편하게 한두 숟가락 떠 넣어서 사용할 수 있으면서 상온에서 보관이 가능하고 오래두어도 쉽게 변질되지 않고, 접근성은 물론 사용상 편리성, 보관의 용이성이 좋고 특히, 자극 및 동물에 무해하면서 가축 질병예방에 기여할 수 있도록 개선된 분쇄 마늘을 이용한 사료첨가제 제조방법에 관한 것이다. claims: 김치로부터 유산균을 추출하는 제1단계; 추출된 유산균을 고구마를 이용하여 대량으로 증식 배양하는 제2단계; 천일염을 녹인 물에 배양한 유산균을 첨가하여 1차 숙성시키는 제3단계; 숙성된 유산균액에 분쇄한 마늘을 첨가하고 간장을 부어 염도를 조절하는 제4단계; 염도가 조절된 유산균액을 2차 발효 숙성시키는 제5단계; 숙성된 유산균액에서 투명간장을 제거하고 마늘 고형물을 분리하는 제6단계;를 포함하는 분쇄 마늘을 이용한 사료첨가제 제조방법에 있어서;상기 제6단계 후 발효통에 소금 100~500g, 물엿 100~2,500g, 정제수 500~2,500g, 레몬그라스 15g 및 소성산호분말 5g을 넣고, 상기 제6단계에서 투명간장의 발효 부산물로 건져낸 마늘 고형물을 건조시켜 만든 마늘 건물 100g을 투여한 후에 6개월 동안 25℃ 이내에서 발효 증식하여 50mg당 유산균의 수가 1조 마리 이상되도록 하여 사료첨가제로 만드는 제7단계;를 더 포함하는 분쇄 마늘을 이용한 사료첨가제 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

420/1150 Row 420: application_number: 1020200070891, combined_string: invention_title: 양파 부산물을 유효성분으로 함유하는 산란계 사료 첨가제 및 이의 용도 abstract: 본 발명은 양파 부산물 추출물을 유효성분으로 함유하는 산란율 증가용 산란계 사료첨가제 및 사료 조성물에 관한 것으로, 본 발명의 사료첨가제를 산란계에 급여할 경우 산란율을 증가시켜 양계 농가 소득 증진에 기여할 수 있다. claims: 수정을 투입하여 예열한 건조기에 양파껍질, 양파뿌리 및 사차인치를 투입하여 건조한 양파 혼합 부산물에 물 및 층층나무 수액을 첨가하여 추출한 후 여과하고 감압 농축하여 제조된 양파 부산물 추출물을 유효성분으로 함유하는 산란율 증가용 산란계 사료첨가제.제1항 또는 제2항의 산란계 사료첨가제를 포함하는 산란율 증가용 산란계 사료 조성물.제3항의 산란율 증가용 산란계 사료 조성물을 산란계에 급여하여 산란계의 산란율을 증가시키는 방법.(단계 1) 수정 0.8~1.2 kg을 투입하여 예열한 건조기에 양파껍질 650~750 g, 양파뿌리 120~180 g 및 사차인치 120~180 g을 투입하여 45~55℃에서 1~3시간 동안 건조한 양파 혼합 부산물에 물 2.7~3.3 L 및 층층나무 수액 0.8~1.2 L를 첨가하여 45~55℃에서 4~6시간 동안 추출한 후 여과하고 감압 농축하여 산란계 사료첨가제를 제조하는 단계; 및(단계 2) 상기 (1)단계의 제조한 산란계 사료첨가제와 일반사료 4~6:94~96 중량비율로 혼합하여 산란계에 급여하는 단계를 포함하는 산란계 사육방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

421/1150 Row 421: application_number: 1020200014107, combined_string: invention_title: 미생물을 이용한 축사 소독방법 abstract: 본 발명은 미생물을 이용한 축사 소독방법에 관한 것이다.본 발명에 따르면 미생물보관탱크 내부에 보관되는 EM 미생물과 음용수저장탱크의 음용수를 혼합액포집탱크 내부로 설정된 비율로 공급 혼합하고, 동절기에는 혼합액 온도(35℃)를 유지시키며, 미생물과 음용수의 혼합액을 혼합액펌핑수단으로서 펌핑하여 축사 내부로 설정된 시간동안 분사하여 냄새 및 분진 등을 제거한 다음, 음용수저장탱크 내부의 음용수를 음용수펌핑수단으로서 설정된 시간동안 펌핑하여 배출파이프, 공급라인 및 분사수단 내부에 잔류해 적정 온도에 의해 증식되어 배출파이프, 공급라인 및 분사수단을 막고 있는 EM 미생물을 세척 제거한 후, 에어발생기에서 발생되는 고압의 에어를 배출파이프, 공급라인 및 분사수단으로 공급하여, 상기 음용수청소공정 후 배출파이프, 공급라인 및 분사수단 내부에 남아 있는 수분과 미생물을 완전히 제거함으로서, 혼합액 분사작업을 지속적으로 진행할 수 있어 분사작업이 우수하고, 동절기에는 동파를 방지하는 효과가 제공된다. claims: 미생물보관탱크 내부에 보관되는 EM 미생물과 음용수저장탱크의 음용수를 미생물공급수단 및 음용수공급수단에 의해 설정된 비율을 유지하여 혼합액포집탱크 내부로 공급 혼합하기 위한 미생물과 음용수 혼합공정과; 상기 혼합액포집탱크의 미생물과 음용수의 혼합액을 혼합액펌핑수단으로서 펌핑하여 배출파이프, 공급라인 및 분사수단을 통해 축사 내부로 설정된 시간동안 분사하여 축사를 소독하기 위한 혼합액분사공정과; 상기 음용수저장탱크 내부의 음용수를 음용수펌핑수단으로서 펌핑하여 공급라인과 분사수단 내부에 잔류하여 온도에서 증식하는 EM 미생물의 특성으로 공급라인과 분사수단이 막히는 것을 차단하기 위한 음용수청소공정과; 에어발생기에서 발생되는 고압의 에어를 배출파이프, 공급라인 및 분사수단으로 공급하여 상기 음용수청소공정 후 배출파이프, 공급라인 및 분사수단에 남아 있는 미생물 및 수분을 완전히 제거하기 위한 에어청소공정으로 구성되는 미생물을 이용한 축사 소독방법에 있어서,상기 혼합액분사공정의 분사수단(80)은 상기 혼합액펌핑수단(70)의 공급라인(78)에 연통되게 형성되는 다수의 연결구(81)와; 상기 연결구(81)에 분리 가능하게 결합되고, 하부에 연통되게 돌출부(82)가 형성되며, 배출공(83a)이 관통 형성된 상부하우징(83)과, 상부하우징(83)의 일측에서 하방으로 연장되게 연결되는 굴곡연장편(84)과, 굴곡연장편(84) 하부에 상부하우징(83)의 돌출부(82) 하단과 일치되게 형성된 결합공(85a)을 갖는 하부받침대(85)로 이루어진 고정체(86)와;상기 하부받침대(85)의 결합공(85a)에 회전 가능하게 결합되는 회전핀(87)과, 회전핀(87)이 하단에 일체로 형성되고, 상부하우징(83)의 돌출부(82)에 회전 가능하게 결합되는 상부요홈(88a)에 형성되며, 상부요홈(88a)과 연통되게 혼합액이 축사(1)로 분사되는 경사비산공(88b)이 형성되는 경사몸체(88)로 이루어진 회전체(89)로 구성된 것을 특징으로 하는 미생물을 이용한 축사 소독방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

422/1150 Row 422: application_number: 1020200000371, combined_string: invention_title: 유황오리 사육용 천연식물유황사료 제조방법 abstract: 본발명은 MSM(메틸설포닐메탄) 0.1 ~ 0.5wt%, 바실러스 서브틸러스 1.0 ~ 5.0wt%, 모나콜린-케이가 0.1wt% 이상이 함유되어 있는 홍국균 배양물 0.5 ~ 5.0wt% 및, 부형제인 효모 89.5 ~ 98.4wt% 을 함유하는 제1사료를 28~30℃ 회전조에서 20~30분 혼합하는 제 1사료 혼합공정;혼합된 제 1사료와 오리 일반사료를 1:9 비율로 30 ~ 40℃ 회전조에서 20~30분 뒤집으면서 혼합하며 혼합된 사료가 평균 29 ~ 30℃에 이르도록 하는 제 2사료 혼합공정; 및혼합된 제 2사료를 29 ~ 30℃ 항온조에서 5~6시간 숙성하는 숙성공정;을 수행하는 유황오리 사육용 천연식물유황사료 제조방법에 관한 것으로,본 발명에 따른 사료를 섭취한 오리는 일반사료를 섭취한 통상의 오리에 비해 근육내 황함유화합물의 함량이 증가되고, 콜레스테롤 합성 저해물질인 모나콜린-케이가 급이됨으로써 오리육에 콜레스테롤의 함량이 감소되며, 오리를 사육하는 동안 감염될 수 있는 바이러스에 저항력이 생겨 질병에 강해지므로 별도의 화학성분의 항생제를 투여할 필요가 없게 되고, 오리의 육질개선, 품질향상, 성장속도의 단축, 사료효율의 개선을 제공함으로써 경쟁력 있는 고급 오리제품을 생산하여 농어촌 소득은 물론 국민 보건 향상에 기여할 수 있다. claims: MSM(메틸설포닐메탄) 0.1 ~ 0.5wt%, 바실러스 서브틸러스 1.0 ~ 5.0wt%, 모나콜린-케이가 0.1wt% 이상이 함유되어 있는 홍국균 배양물 0.5 ~ 5.0wt% 및, 부형제인 효모 89.5 ~ 98.4wt% 을 함유하는 제1사료를 28~30℃ 회전조에서 20~30분 혼합하는 제 1사료 혼합공정;혼합된 제 1사료와 오리 일반사료를 1:9 비율로 30 ~ 40℃ 회전조에서 20~30분 뒤집으면서 혼합하며 혼합된 사료가 평균 29 ~ 30℃에 이르도록 하는 제 2사료 혼합공정; 및혼합된 제 2사료를 29 ~ 30℃ 항온조에서 5~6시간 숙성하는 숙성공정;을 수행하는 유황오리 사육용 천연식물유황사료 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

423/1150 Row 423: application_number: 1020190177320, combined_string: invention_title: 오골계 유래 탈미네랄화된 골분을 이용한 골이식재 및 이의 제조방법 abstract: 본 발명은 오골계 유래 탈미네랄화된 골분(demineralized bone particles ; DBP)을 이용한 골이식재 및 이의 제조방법에 관한 것으로서, 더욱 상세하게는 오골계 유래의 DBP와 골유도물질을 함침시켜 제작한 골 재생에 매우 효과적인 골대체재용 지지체 조성물과 이를 이용하여 제작된 골이식재에 관한 것이다. 이러한 본 발명에 따른 골이식재는 다른 가금류인 닭, 오리 유래의 DBP를 이용하여 제작한 골이식재와 비교하여 골 재생 효과가 월등하게 우수하다. claims: 오골계 유래 탈미네랄화된 골분(demineralized bone particles ; DBP)을 함유하는 골대체재용 지지체 조성물.오골계 유래 탈미네랄화된 골분(demineralized bone particles ; DBP)을 함유하는 골대체재용 지지체 조성물로 이루어지되 청구항 2 내지 청구항 4 중에서 어느 하나의 항에 따른 골대체재용 지지체 조성물로 이루어진 골이식재.(a) 오골계 유래 탈미네랄화된 골분(DBP)을 제조하는 단계; (b) 탈미네랄화된 골분을 이용하여 다공성 성형체로 지지체를 제조하는 단계; 및(c) 상기 지지체에 골유도물질로서 생리활성물질, 골형성 단백질, 세라믹성분 중에 하나이상의 골유도물질을 적용하는 단계 를 포함하는 골이식재의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

424/1150 Row 424: application_number: 1020190169490, combined_string: invention_title: 사료용 첨가제 조성물 abstract: 본 발명에 따른 사료용 첨가제 조성물은 고추(Capsicum annuum) 분말을 포함하는 것일 수 있다.본 발명에 따른 사료용 첨가제 조성물은 식물성 소재를 활용하여 가축 내 축적되는 항생제 및 향균제의 분해를 촉진하고 축전된 중금속을 배출하거나 감소시킨다.또한 본 발명에 따른 사료용 첨가제 조성물은 가축의 면역성이 증진될 수 있도록 하여 항생제 등의 사용을 줄이고 축산물 생산을 높일 수 있도록 하면서 궁극적으로 축산물의 품질이 향상되게 한다. claims: 고추(Capsicum annuum) 분말을 포함하는 것인사료용 첨가제 조성물.제 1항 내지 제6항 중 어느 한 항에 따른 사료 첨가제용 조성물을 포함하는 사료., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

425/1150 Row 425: application_number: 1020190165565, combined_string: invention_title: 수용성 규산염을 포함하는 동물 사료 첨가제 abstract: 본 발명은 수용성 규산염을 포함하는 동물 사료 첨가제를 제공한다. 본 발명에서는 동물 사료 첨가제에 포함되는 수용성 규산염을 규산광물과 탄산나트륨을 전기로에서 1,800℃ 이상의 고온으로 용융시켜 제조함으로써, 고순도의 수용성 규산염을 제조할 뿐만 아니라 제조공정과 시간이 단축되고, 농작물이나 또는 원예작물 등의 비료로 사용하여 병충해를 예방하는 한편, 제조된 수용성 규산염이 축산 동물의 성장을 촉진하고, 육질 등급 향상의 효과를 나타내어 동물 사료 첨가제로 사용될 수 있으므로, 축산 동물 산업 및 사료 첨가제 분야에서 성장 촉진과 육질 등급 향상 효과를 나타내는 동물 사료 첨가제로서 유용하게 사용될 수 있다. claims: 수용성 규산염을 포함하는 동물 사료 첨가제., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

426/1150 Row 426: application_number: 1020190165612, combined_string: invention_title: 들깨 부산물을 포함하는 오메가 3 지방산 함유 육계육용 사료첨가제 조성물 abstract: 본 발명은 육계육용 사료첨가제 조성물, 더욱 상세하게는 들깨 부산물을 포함하는 오메가 3 지방산 함유 육계육용 사료첨가제 조성물에 관한 것이다. 본 발명에 따른 들깨 부산물을 포함하는 육계육용 사료첨가제 조성물은 육계의 생산성 뿐만 아니라 육계육 내 오메가 3 지방산의 함량을 유의적으로 증가시킬 수 있다. claims: 들깨 부산물을 포함하는 오메가 3 지방산 함유 육계육용 사료첨가제 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

427/1150 Row 427: application_number: 1020190160850, combined_string: invention_title: 돈사 소독 및 살균을 위한 ICT LED 살균 및 질병 관리시스템 abstract: 본 발명은 사육공간의 소독 및 살균을 위한 ICT LED 살균 및 질병 관리시스템에 관한 것으로, 더욱 상세하게는, 정보통신기술(Infromation Communication Technology)을 이용하여 사육 공간에 대한 소독(disinfection)과 살균(sterilization)을 실시하여 축사를 살균하고, 자돈의 위치 정보와 LED 동작 정보를 바탕으로 핸드폰과 컴퓨터를 활용하여 LED살균등으로 소독을 실시하고, 관리할 수 있는 사육공간의 소독 및 살균을 위한 ICT LED 살균 및 질병 관리시스템에 관한 것이다. ICT LED 살균 및 질병 관리시스템은 사육공간 내부를 센싱하여 상기 사육공간 내부에 가축이 존재하는지 여부를 지시하는 검출신호를 생성하는 센서, 제1대역의 전자기파를 방출하는 제1LED모듈, 제2대역의 전자기파를 방출하는 제2LED모듈 및 상기 센서로부터 상기 검출신호를 획득하고, 상기 검출신호에 기반하여 상기 사육공간 내부에 가축이 존재하는지 여부를 판정하며, 상기 사육공간 내부에 가축이 존재하는지 여부에 따라 상기 제1LED모듈 및 상기 제2LED모듈의 on/off 제어를 수행하는 제어부를 포함한다. claims: ICT LED 살균 및 질병 관리시스템에 있어서,사육공간 내부를 센싱하여 상기 사육공간 내부에 가축이 존재하는지 여부를 지시하는 검출신호를 생성하는 센서;제1대역의 전자기파를 방출하는 제1LED모듈;제2대역의 전자기파를 방출하는 제2LED모듈; 및상기 센서로부터 상기 검출신호를 획득하고, 상기 검출신호에 기반하여 상기 사육공간 내부에 가축이 존재하는지 여부를 판정하며, 상기 사육공간 내부에 가축이 존재하는지 여부에 따라 상기 제1LED모듈 및 상기 제2LED모듈의 on/off 제어를 수행하는 제어부;를 포함하는 것을 특징으로 하는돈사 소독 및 살균을 위한 ICT LED 살균 및 질병 관리시스템.컴퓨팅 디바이스에 의해 수행되는 사육공간의 소독 및 살균을 위한 ICT LED 살균 및 질병 관리방법에 있어서,(a) 상기 사육공간 내부에 가축이 존재하는지 여부를 지시하는 검출신호를 센서로부터 획득하는 검출신호 획득단계(s10);(b) 상기 검출신호를 기반으로 상기 사육공간 내부에 가축이 존재하는지 여부를 판정하는 판정단계(s20); 및(c) 상기 판정단계에서의 상기 사육공간 내부에 가축이 존재하지 여부에 대한 판정결과에 따라 상기 사육공간에 설치된 서로 다른 대역의 전자기파를 방출하는 제1LED모듈 또는 제2LED모듈에 대한 on/off 제어를 수행하는 on/off 제어 수행단계(s40);를 포함하는돈사 소독 및 살균을 위한 ICT LED 살균 및 질병 관리방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

428/1150 Row 428: application_number: 1020190158267, combined_string: invention_title: 과일 및 야채 부산물을 유효성분으로 포함하는 반추 동물용 사료 첨가제 조성물 abstract: 본 발명은 과일 및 야채 부산물을 포함하는 반추동물용 사료 첨가제 조성물 및 이의 제조방법에 관한 것이다. 본 발명은 우수한 영양학적 특성을 가져 한우(Bos taurus coreanae)를 비롯한 반추동물의 생산성을 현저히 향상시키면서도 폐기되는 과일 및 야채 부산물을 활용함으로써 친환경적일 뿐 아니라 비용 측면에서 효율적인 사료 조성물로 유용하게 이용될 수 있다. claims: 15 - 25 w/w%의 과일 및 야채 부산물을 유효성분으로 포함하는 반추동물용 사료 조성물.25 - 35 w/w%의 양배추 및 배추 부산물을 유효성분으로 포함하는 반추동물용 사료 조성물.다음의 단계를 포함하는 반추동물용 사료 조성물의 제조 방법:(a) 수집된 과일 및 야채 부산물을 25 - 45 mm 절편으로 분쇄하는 단계; (b) 상기 분쇄된 과일 및 야채 부산물 절편에 산화 방지제를 첨가하는 단계; 및(c) 전체 조성물 내에 과일 및 야채 부산물 함량과 수분 함량이 각각 15 - 25 w/w% 및 7- 13 w/w%로 포함되도록 배합하는 단계.제 14 항에 있어서, 상기 산화 방지제는 메타중아황산나트륨(Sodium Metabisulfite)인 것을 특징으로 하는 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

429/1150 Row 429: application_number: 1020190158124, combined_string: invention_title: 닭사료 조성물 abstract: 본 발명은 면역성을 높일 수 있는 닭사료 조성물에 관한 것으로서, 분말화된 한약재박, 커피찌꺼기, 과일껍질, 버섯부산물, 목초액, 미강, 굴 껍질 및 혈분으로 이루어지는 베이스 분말과, 황칠나무잎 복합체 발효분말과 매실 분말을 포함한다. 이러한 닭사료 조성물에 따르면, 항생제를 사용하지 않고서도 질병에 대한 면역성을 높여 닭의 건강을 증진시킬 수 있고, 장기 보관을 가능하게 함과 동시에 보관 부피를 줄일 수 있다. claims: 분말화된 한약재박, 커피찌꺼기, 과일껍질, 버섯부산물, 목초액, 미강, 굴 껍질 및 혈분으로 이루어지는 베이스 분말과, 황칠나무잎 복합체 발효분말과 매실 분말을 포함하고;상기 베이스 분말은, 상기 한약재박 100 중량부를 기준으로 하여, 상기 커피찌꺼기 10 내지 20 중량부, 과일껍질 12 내지 17 중량부, 버섯부산물 6 내지 10 중량부, 목초액 0.1 내지 0.5 중량부, 미강 70 내지 120 중량부, 굴 껍질 10 내지 20 중량부, 혈분 3 내지 8 중량부를 포함하고;상기 황칠나무잎 복합체 발효분말은, 연잎 및 황칠나무잎을 1 : 2 중량비로 준비하고 물을 이용하여 깨끗하게 세척한 후 이물질을 제거하고, 이를 70℃에서 3시간 동안 건조한 다음 스팀기에 75℃에서 40분간 투입하여 스팀 히팅을 행하는 단계와; 상기 결과물을 25℃로 냉각시킨 다음, 235℃에서 15분 동안 열풍건조하고 나서 90℃에서 1시간 동안 제1열처리를 실시하는 단계와; 상기 제1열처리된 결과물을 120℃에서 45분 동안 제2열처리를 실시하는 단계와; 상기 제2열처리된 생성물 100 중량부에 설탕 3 중량부, 물 50 중량부를 차례로 부가하고 이를 6일 동안 발효 숙성하거나, 상기 제2열처리된 생성물 100 중량부에 설탕 3 중량부를 부가한 다음, 물 50 중량부 및 설탕 3 중량부를 추가로 부가하며 유산균을 접종하고 이를 온도 35℃, 상대습도 83% 의 조건에서 6일 동안 발효 숙성하는 단계;로 얻어진 것을 특징으로 하는 닭사료 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

430/1150 Row 430: application_number: 1020190156257, combined_string: invention_title: 반려동물 사료공급장치 및 이를 이용한 반려동물 사료공급방법 abstract: 본 발명은 반려동물 사료공급장치 및 이를 이용한 사료공급방법에 관한 것이다.본 발명의 실시예에 따르면, 반려동물 사료공급장치에 있어서, 외형을 형성하는 하우징부; 상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및 상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함한다. claims: 반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하고,상기 사료공급 어셈블리는,상기 사료공급 어셈블리 몸체부의 하방에 배치되고, 상기 사료보관공간과 연통되며, 상기 정량공급모듈이 배치되는 정량공급모듈 수용부와,상기 정량공급모듈 수용부의 하측에 배치되며, 하방을 향하여 개구되는 상기 사료 공급홀이 형성되는 사료공급 어셈블리 커버브래킷을 더 포함하고,상기 커버브래킷은 상기 정량공급모듈 수용부에 대응되는 원형 플레이트로 형성되는 커버브래킷 몸체를 포함하며,상기 정량공급모듈 수용부의 내부에 배치되는 상기 정량공급모듈은, 상기 정량공급모듈 수용부의 중심축을 중심으로 회전되며, 상기 중심축을 따라서 형성되는 회전 샤프트부와, 상기 회전 샤프트부를 기준으로 방사형으로 배치되는 복수의 회전날개부를 포함하는 회전공급유닛을 포함하고,상기 사료 공급홀은 상기 중심축을 중심으로 하는 부채꼴 형상으로 형성되며,상기 정량공급모듈의 상기 회전공급유닛의 하면은 상기 커버브래킷 몸체의 상면과 마주보고,상기 정량공급모듈은, 상기 회전 샤프트부의 타측에 고정되는 보조날개부들을 포함하고 상기 회전공급유닛과 동시에 회전되는 사료혼합유닛과, 상기 회전공급유닛 및 상기 사료혼합유닛 사이에 배치되며 상기 정량공급모듈 수용부의 내부에 고정되고 상기 정량공급모듈 수용부의 상기 중심축에 대하여 직교하는 방향으로 길게 연장 형성되는 브러시 유닛을 더 포함하고,상기 브러시 유닛은 상기 정량공급모듈 수용부의 상기 중심축과 나란한 방향으로 형성되는 복수의 브래킷들을 포함하는 반려동물 사료공급장치.반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하고,상기 트레이유닛에 선택적으로 물을 공급하기 위한 물공급 어셈블리;를 더 포함하고,상기 물공급 어셈블리는 물 공급과 상기 사료공급 어셈블리의 사료 공급은 상호 간에 독립적으로 이루어지며,상기 물공급 어셈블리는,내부에 물이 수용되는 물수용 공간이 형성되는 물공급 어셈블리 본체와,상기 물공급 어셈블리의 하측에 배치되며 물을 상기 물수용 공간의 외부로부터 배출하기 위한 유로를 제공하는 파이프 유닛과,상기 파이프 유닛의 단부에 형성되며, 물이 상기 트레이 어셈블리 측으로 배출되는 배출유닛을 포함하며,상기 배출유닛은, 상기 파이프 유닛과 연통되며 하방을 향하여 개구되는 배출홀이 형성되는 배출유닛 몸체와, 상기 배출유닛 몸체의 하측에 상기 배출유닛 몸체에 대하여 회전 가능하게 설치되는 스프링클러 플레이트를 포함하고,상기 배출유닛 몸체의 상기 배출홀에서 배출되는 물은 상기 스프링클러 플레이트와 접촉된 다음 상기 트레이 어셈블리 측으로 공급되는 것을 특징으로 하는 반려동물 사료공급장치.반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하고,상기 트레이유닛에 선택적으로 물을 공급하기 위한 물공급 어셈블리;를 더 포함하고,상기 물공급 어셈블리는 물 공급과 상기 사료공급 어셈블리의 사료 공급은 상호 간에 독립적으로 이루어지며,상기 물공급 어셈블리는,내부에 물이 수용되는 물수용 공간이 형성되는 물공급 어셈블리 본체와,상기 물공급 어셈블리의 하측에 배치되며 물을 상기 물수용 공간의 외부로부터 배출하기 위한 유로를 제공하는 파이프 유닛과,상기 파이프 유닛의 단부에 형성되며, 물이 상기 트레이 어셈블리 측으로 배출되는 배출유닛을 포함하며,상기 배출유닛은, 상기 파이프 유닛에 대하여 회전 가능하게 연결되며 하방을 향하여 개구되는 복수의 배출홀이 형성되는 배출유닛 몸체와, 상기 배출유닛 몸체를 수직축을 중심으로 기설정된 각도만큼 왕복 회전시키는 회전구동부를 포함하는 것을 특징으로 하는 반려동물 사료공급장치.반려동물 사료공급장치에 있어서,외형을 형성하는 하우징부;상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되는 사료공급 어셈블리 몸체부와, 상기 사료를 기설정된 양만큼 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리;를 포함하고,상기 트레이 어셈블리의 상기 트레이유닛은 복수개로 형성되며, 상기 트레이유닛 중 어느 하나의 트레이 유닛이 상기 하우징부에 형성되는 배식홀을 통하여 상기 하우징부의 외부로 노출된 경우, 적어도 하나의 다른 트레이유닛은 상기 하우징부의 외부로 노출되지 않고,상기 트레이 어셈블리는,상기 복수의 트레이유닛들이 분리 가능하게 결합되며, 중앙에 트레이 어셈블리 회전축이 형성되는 원형의 트레이 어셈블리 몸체를 더 포함하고,상기 트레이 어셈블리는 상기 하우징부에 대하여 분리 가능하게 결합되며,상기 트레이 어셈블리 몸체의 트레이 어셈블리 회전축에 선택적으로 접속 가능한 트레이 어셈블리 구동부;를 더 포함하고,상기 트레이 어셈블리 구동부는, 상하 방향으로 이동 가능하며 상기 트레이 어셈블리 회전축과 선택적으로 결합되어 상기 트레이 어셈블리 몸체를 일방향 또는 타방향으로 회전시키는 구동유닛과, 일측이 상기 구동유닛과 연결되어 상기 구동유닛을 상하 방향으로 이동시키며 상기 하우징부의 외부로 노출된 핸들유닛을 포함하는 반려동물 사료공급장치.외형을 형성하는 하우징부; 상기 하우징부의 내부에 배치되며, 사료가 수용되는 사료보관공간이 형성되고, 상기 사료보관공간 하부에 배치되는 사료 공급홀을 통하여 상기 사료가 상기 사료보관공간으로부터 배출되며, 상기 사료를 기설정된 양만큼 상기 사료 공급홀을 통하여 상기 사료보관공간의 외부로 배출시키는 정량공급모듈을 포함하는 사료공급 어셈블리; 및 상기 사료공급 어셈블리의 하방에 배치되며, 상기 사료 공급홀을 통하여 상기 사료보관공간으로부터 배출된 상기 사료가 수용되는 트레이유닛을 포함하는 트레이 어셈블리를 포함하고, 상기 트레이유닛에 선택적으로 물을 공급하기 위한 물공급 어셈블리;를 더 포함하고, 상기 물공급 어셈블리는 물 공급과 상기 사료공급 어셈블리의 사료 공급은 상호 간에 독립적으로 이루어지며, 상기 트레이 어셈블리는 상하 방향으로 형성되는 트레이 어셈블리 회전축을 중심으로 회전되는 복수의 상기 트레이 유닛들을 포함하고, 배식홀을 통하여 하나의 상기 트레이 유닛이 하우징부의 외부로 노출되는 반려동물 사료공급장치를 이용한 반려동물 사료공급방법에 있어서,복수의 트레이유닛 어느 하나의 트레이유닛이 상기 사료공급 어셈블리의 하방에 배치되도록 상기 트레이 어셈블리를 회전시키는 제1 트레이 회전 단계;상기 사료공급 어셈블리의 하방에 배치되는 상기 트레이유닛에 기설정된 양의 사료를 공급하는 사료 분배 단계; 및상기 사료 공급이 완료된 상기 트레이유닛이 상기 하우징부에 형성된 배식홀을 통하여 외부로 노출되도록 상기 트레이 어셈블리를 회전시키는 제2 트레이 회전 단계;를 포함하고,상기 트레이 유닛에 기설정된 양의 물을 공급하는 물공급 단계; 및상기 트레이 유닛과 상기 사료와 상기 물이 공급된 상태에서, 기설정된 시간동안 상기 사료를 재수화(Rehydration) 시키는 사료 수화 단계;를 더 포함하고,상기 사료 분배 단계에서,상기 사료가 공급되는 상기 트레이 유닛(배식 트레이 유닛)은, 상기 배식홀을 통하여 상기 하우징부의 외부로 노출되는 다른 트레이 유닛(노출 트레이 유닛)과 상기 트레이 어셈블리 회전축을 기준으로 상기 다른 트레이 유닛(노출 트레이 유닛)과 대칭되는 또 다른 트레이 유닛(대칭 트레이 유닛) 사이에 배치되며,상기 제1 트레이 이동 단계에서,상기 트레이 유닛들은, 제1 회전 각도만큼 일 방향으로 회전되며,상기 제2 트레이 이동 단계에서,상기 트레이 유닛들은, 제2 회전 각도만큼 상기 일 방향과 반대되는 타 방향으로 회전되거나, 제3 회전 각도만큼 상기 일 방향으로 회전되며,상기 제2 회전 각도는 상기 제1 회전 각도보다 크고,상기 제1 회전 각도와 상기 제3 회전 각도의 합은 360도 보다 작은 것을 특징으로 하는 반려동물 사료공급방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

431/1150 Row 431: application_number: 1020190155585, combined_string: invention_title: 락토케피아노파시엔스 케피아노파시엔스 DN1 균주를 포함하는 사료 첨가제 조성물 abstract: 본 발명은 락토바실러스 케피아노파시엔스(Lactobacillus kefiranofacience) DN1 (KCCM11869P) 또는 이의 배양액을 포함하는 사료 첨가제 조성물에 대한 것으로, 구체적으로 가금류 살모넬라 감염을 예방하고 감소시켜 사료 조성물로 이용할 수 있다. claims: 락토바실러스 케피아노파시엔스(Lactobacillus kefiranofacience) DN1 (KCCM11869P) 균주 또는 이의 배양액을 포함하는 사료 첨가제 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

432/1150 Row 432: application_number: 1020190155573, combined_string: invention_title: 농장에 설치되는 AI 바이러스 살균 시스템 abstract: 본 발명은 농장에 설치되는 AI 바이러스 살균 시스템에 대한 것이다. 본 발명에 따른 농장에 설치되는 AI 바이러스 살균 시스템은 외부로부터 공기를 흡입하고, 흡입된 공기를 살균하여 농장 내부에 제공하는 제1 살균장치, 외부로부터 공기를 흡입하고, 흡입된 공기를 살균하여 농장 일측에 위치한 출입부스에 제공하는 제2 살균장치, 그리고 상기 제1 살균장치 및 제2 살균장치의 현재 공기흐름량 및 살균조사량을 산출하고, 산출된 현재 공기흐름량 및 현재 살균조사량과 필요 공기흐름량 및 필요 살균조사량을 비교하여 상기 제1 살균장치와 제2 살균장치에 설치된 팬의 속도 및 UV 조사량을 조절하는 제어장치를 포함한다. 이와 같이 본 발명에 따른 AI 바이러스 살균 시스템은 농장 내부와 출입부스를 분리하여 각각 살균된 공기를 제공하고, 농장내의 사육 환경에 따라 공기 흐름량 및 UV 조사량을 조절하여 항시 멸균된 상태를 유지할 수 있도록 함으로써, 사육되는 조류가 조류 독감 바이러스에 감염되는 것을 근본적으로 방지할 수 있다. claims: 농장에 설치되는 AI 바이러스 살균 시스템에 있어서, 외부로부터 공기를 흡입하고, 흡입된 공기를 살균하여 농장 내부에 제공하는 제1 살균장치, 외부로부터 공기를 흡입하고, 흡입된 공기를 살균하여 농장 일측에 위치한 출입부스에 제공하는 제2 살균장치, 그리고상기 제1 살균장치 및 제2 살균장치의 현재 공기흐름량 및 살균조사량을 산출하고, 산출된 현재 공기흐름량 및 현재 살균조사량과 필요 공기흐름량 및 필요 살균조사량을 비교하여 상기 제1 살균장치와 제2 살균장치에 설치된 팬의 속도 및 UV 조사량을 조절하는 제어장치를 포함하는 AI 바이러스 살균 시스템.제5항에 있어서, 상기 적정 공기 흐름량(γ _ Suitable)은,상기 농장 내부 또는 출입부스 내에 필요한 공기흐름량을 나타내며, 하기의 수학식을 통해 연산되는 AI 바이러스 살균 시스템;여기서, α는 살균 비례상수이고, X는 농장내부 또는 출입부스에서 측정된 상대습도이고, β는 상대습도에 대한 고정상수이고, 는 농장내부 또는 출입부스에서 필요로 하는 살균 조사량을 나타내며, V는 UV 살균 가능 체적을 나타낸다. 제6항에 있어서, 상기 제어부는, 상기 농장 내에서 산출된 적정 공기흐름량(γ _ Suitable)이 현재 공기흐름량(γ _ Current )보다 적으면 상기 제1 흡입부에 설치된 흡입팬의 속도를 감소시키고,상기 출입부스 내에서 산출된 적정 공기흐름량(γ _ Suitable)이 현재 공기흐름량(γ _ Current )보다 적으면 상기 제2 흡입부에 설치된 흡입팬의 속도를 감소시키는 AI 바이러스 살균 시스템.제5항에 있어서, 상기 필요 UV 조사량(Dose_Need)은, 상기 농장 내부에 필요한 UV 조사량을 나타내며, 하기의 수학식을 통해 연산되는 AI 바이러스 살균 시스템;여기서, α는 살균 비례상수이고, X는 농장내부에서 측정된 상대습도이고, β는 상대습도에 대한 고정상수이고, γ는 농장 내부의 공기 흐름량을 나타내며, V는 UV살균 가능 체적을 나타낸다. 제8항에 있어서, 상기 제어부는, 상기 산출된 필요 UV 조사량(Dose_Need)이 현재 UV 조사량(Dose_Current)보다 크면 UV 조사량을 증가시키되, 점등되는 UV LED의 수량의 개수를 증가시키거나 높은 전압을 출력하도록 제어하여 상기 UV 조사량을 증가시키는 AI 바이러스 살균 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

433/1150 Row 433: application_number: 1020190153462, combined_string: invention_title: 진공식 사료 자동 공급장치 abstract: 본 발명은 진공식 사료 자동 공급장치에 관한 발명으로, 내부에 공간 부가 형성되며, 전면에 사료 공급 홀이 형성되며, 상부에 덮개가 개폐 가능하게 설치되는 사료 자동 공급장치 본체; 상기 공간 부 안에 설치되며, 내부에 사료를 저장하는 사료 저장 호퍼; 상기 사료 공급 홀을 선택적으로 개방시켜서 상기 사료 저장 호퍼의 사료를 애견에게 공급하는 사료 공급 유닛; 상기 공간 부 및 상기 사료 저장 호퍼의 내부공간을 진공상태로 유지하기 위한 하나 이상의 진공펌프; 상기 사료 저장 호퍼 내부에 배치되어, 상기 사료 저장 호퍼 내부 공간의 습도를 조절하는 습도조절부; 및 상기 진공펌프 및 상기 습도조절부를 제어하는 제어부를 포함할 수 있다. claims: 내부에 공간 부(11)가 형성되며, 전면에 사료 공급 홀(12)이 형성되며, 상부에 덮개(13)가 개폐 가능하게 설치되는 사료 자동 공급장치 본체(10);상기 공간 부(11) 안에 설치되며, 내부에 사료를 저장하는 사료 저장 호퍼(20); 상기 사료 공급 홀(12)을 선택적으로 개방시켜서 상기 사료 저장 호퍼(20)의 사료를 애견에게 공급하는 사료 공급 유닛(70);상기 공간 부(11) 및 상기 사료 저장 호퍼(20)의 내부공간을 진공상태로 유지하기 위한 하나 이상의 진공펌프(P1, P2); 상기 사료 저장 호퍼(20) 내부에 배치되어, 상기 사료 저장 호퍼(20) 내부 공간의 습도를 조절하는 습도조절부(28); 및상기 진공펌프 및 상기 습도조절부를 제어하는 제어부(C); 를 포함하는 진공식 사료 자동 공급장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

434/1150 Row 434: application_number: 1020190151309, combined_string: invention_title: 흰점박이꽃무지 사육용 인공사료 조성물 abstract: 본 발명은 흰점박이꽃무지 사육용 인공사료 조성물에 관한 것으로서, 더욱 상세하게는 흰점박이꽃무지의 산란수, 산란기간 및 생존기간을 현저히 증가시킬 수 있는 인공사료 조성물에 관한 것이다. 본 발명에 따른 흰점박이꽃무지 사육을 위한 인공사료 조성물은 흰점박이꽃무지의 산란수, 산란기간 및 생존기간을 현저히 증가시키는 것을 확인하였다. 이는 본 발명에 따른 인공사료 조성물은 흰점박이꽃무지를 연중 대량 사육할 수 있음을 의미하는 바, 곤충 사육 분야, 나아가 제약 및 식품 분야에서 다양하게 활용될 수 있다. claims: 조성물 100중량부에 대하여,카세인 3 내지 15중량부를 포함하는, 흰점박이꽃무지 사육용 인공사료 조성물.혼합물 100중량부에 대해 아가 0.5 내지 3중량부 및 카세인 3 내지 15중량부를 첨가하여 혼합물을 제조하는 단계;를 포함하는, 흰점박이꽃무지 사육용 인공사료 제조방법.제1항 내지 제4항 중 어느 한 항에 따른 흰점박이꽃무지 사육용 인공사료 조성물을 흰점박이꽃무지에 급여하는 단계;를 포함하는 흰점박이꽃무지의 인공사육방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

435/1150 Row 435: application_number: 1020190145489, combined_string: invention_title: 상심자 추출물이 코팅된 면역증강용 사료첨가제 abstract: 본 발명은 면역증강용 사료첨가제에 관한 것으로, 보다 상세하게는 상심자 추출물이 코팅된 면역증강용 사료첨가제에 관한 것이다.본 발명에 따르면, 상심자 추출물을 사료첨가제에 코팅하여 동물 면역증강 효과 또한 기존 시판중인 동물용 일반의약품과 동등한 수준을 나타내는 면역증강용 사료첨가제를 제공할 수 있다. claims: 상심자 추출물이 코팅된 면역증강용 사료첨가제로서,상기 상심자 추출물은 정제수를 이용하여 상심자를 80~90℃에서 5~6시간 추출되고, 상기 상심자 추출물은 상기 사료첨가제를 포함하여 제조되는 사료 중 5~10중량% 함량으로 코팅되고,상기 상심자 추출물 1g당 0.5~1.5mg의 클로로게닉산(chlorogenic acid)이 포함되고,상기 면역증강은 살모넬라균 감염에 대한 방어면역증강인 것을 특징으로 하는 면역증강용 사료첨가제., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

436/1150 Row 436: application_number: 1020190137275, combined_string: invention_title: 실험동물 사육실 살균소독 시스템 abstract: 본 발명은 자율적인 소독액의 분무가 가능하여 상주하지 않고도 외부에서 소독관리를 수행할 수 있음은 물론 여러군데 위치한 사육실을 통합관리할 수 있으며, 실시간 모니터링이 가능한 실험동물 사육실 살균소독 시스템에 관한 것이다.본 발명의 실험동물 사육실 살균소독 시스템은, 실험동물 사육실 내부 일측에 설치되고, 제어부(200)의 제어신호에 의해 작동되면서 소독액통(150)에 저장된 소독액을 노즐(141)을 통해 분무하는 소독기(100); 상기 소독기(100)에 설치되어 관리서버(300)의 제어명령에 따라 제어신호를 생성하여 소독액을 분무하도록 소독기(100)를 제어하는 제어부(200); 상기 제어부(200)와 무선통신망으로 연결되어 원격제어하며, 제어부(200)로부터 소독정보를 전달받아 저장하는 관리서버(300); 상기 제어부(200) 또는 관리서버(300)와 무선통신망으로 연결되어 소독정보를 수신받는 휴대단말기(400);로 이루어진다. claims: 실험동물 사육실 내부 일측에 설치되고, 제어부(200)의 제어신호에 의해 작동되면서 소독액통(150)에 저장된 소독액을 노즐(141)을 통해 분무하는 소독기(100);상기 소독기(100)에 설치되어 관리서버(300)의 제어명령에 따라 제어신호를 생성하여 소독액을 분무하도록 소독기(100)를 제어하는 제어부(200);상기 제어부(200)와 무선통신망으로 연결되어 원격제어하며, 제어부(200)로부터 소독정보를 전달받아 저장하는 관리서버(300);상기 제어부(200) 또는 관리서버(300)와 무선통신망으로 연결되어 소독정보를 수신받는 휴대단말기(400);로 이루어진 것을 특징으로 하는 실험동물 사육실 살균소독 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

437/1150 Row 437: application_number: 1020190137777, combined_string: invention_title: 축산 악취 저감용 분말제 및 액상제 통합 분사장치 abstract: 본 발명의 축산 악취 저감용 분말제 및 액상제 통합 분사장치는, 축산 악취 저감용 분말제를 저장하기 위한 분말제 탱크; 상기 분말제 탱크에서 분말제가 출력되는 양을 조절하는 분말제 밸브; 축산 악취 저감용 액상제를 저장하기 위한 액상제 탱크; 상기 액상제 탱크에서 액상제가 출력되는 양을 조절하는 액상제 밸브; 사용자의 선택을 입력받는 설정부; 상기 설정부의 설정에 따라 상기 액상제 밸브 및 상기 분말제 밸브를 조절하여 상기 액상제 또는 분말제의 출력량을 조절하는 제어부를 포함한다. 본 발명에서는 중앙의 구멍 이외에 3단계의 반경으로 구분되며 반경의 크기와 구멍의 모양 및 요철형태가 변형 조절되는 테두리 구멍이 있어서 물 또는 액상제나 분말제의 독립적인 분사기능 이외에 분사각도 및 분사거리의 조절과 습윤도 조절이 가능하다. claims: 축산 악취 저감용 분말제를 저장하기 위한 분말제 탱크;상기 분말제 탱크에서 분말제가 출력되는 양을 조절하는 분말제 밸브;축산 악취 저감용 액상제를 저장하기 위한 액상제 탱크;상기 액상제 탱크에서 액상제가 출력되는 양을 조절하는 액상제 밸브;사용자의 선택을 입력받는 설정부;상기 설정부의 설정에 따라 상기 액상제 밸브 및 상기 분말제 밸브를 조절하여 상기 액상제 또는 분말제의 출력량을 조절하는 제어부를 포함하는 축산 악취 저감용 분말제 및 액상제 통합 분사장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

438/1150 Row 438: application_number: 1020190135846, combined_string: invention_title: 미생물 기반의 사료용 생균제 abstract: 본 발명은 미생물 기반의 사료용 생균제에 관한 것으로, 유익한 미생물들을 함유하여, 가축 및 어류의 증체율 및 면역력을 향상시켜, 사료 효율을 높일 수 있으며, 가축 및 어류의 생산성과 육질의 개선 효과를 나타낼 수 있는 미생물 기반의 사료용 생균제를 제공할 수 있다. claims: 홍국균(Monascus purpureus) 분말을 포함하고; 상기 홍국균 분말 100 중량부에 대하여 광합성 세균 분말 30 내지 50 중량부; 황국균 분말 30 내지 50 중량부 및 효모 분말 30 내지 50 중량부를 포함하는 혼합 미생물,상기 혼합미생물 100 중량부에 대하여, 왕겨 10 내지 20 중량부; 쌀겨 10 내지 20 중량부; 귤착즙 10 내지 20 중량부; 귤박 10 내지 20 중량부; 돌가사리 분말 5 내지 10 중량부 및 흑돌잎 분말 5 내지 10 중량부를 포함하는 미생물 기반의 사료용 생균제. 제 1항에 따른 미생물 기반의 사료용 생균제를 포함하는사료 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

439/1150 Row 439: application_number: 1020190131290, combined_string: invention_title: 오존 및 OH 라디칼을 이용한 축사용 공기정화 시스템 abstract: 본 발명은 오존 및 OH 라디칼(하이드록시 라디칼)을 이용해 축사와 같은 악취 발생원으로부터 배출되는 공기의 탈취 및 살균을 실시할 수 있는 오존 및 OH 라디칼을 이용한 축사용 공기정화 시스템에 관한 것이다. 본 발명에 따른 오존 및 OH 라디칼을 이용한 축사용 공기정화 시스템은 오염원의 실내 공기를 실외로 배출시키는 배기부와, 상기 배기부를 통해 배출되는 공기가 정화되는 처리공간을 제공하도록 상기 오염원의 외측에 형성되는 공기처리부와, 상기 공기처리부 내에 설치되며, 상기 공기처리부 내의 공간을 상기 배기부의 배출구가 위치하는 제1 처리공간과, 상기 공기처리부의 내주면에 접하는 제2 처리공간으로 구획하며, 상기 제1 처리공간으로부터 제2 처리공간으로 공기가 이동할 수 있는 소정 직경의 통과홀들이 형성된 구획부와, 상기 제2 처리공간으로부터 공기를 상기 공기처리부의 외부로 토출시키도록 형성되는 공기토출부와, 상기 공기처리부 내에 설치되며 오존을 발생시키는 제1 오존발생유닛과, 상기 공기토출부와 연결되도록 상기 공기처리부의 외부에 설치되며, 상기 공기토출부를 통해 토출되는 공기가 통과할 수 있는 토출통로를 구비하고 상기 토출통로 내에 오존을 발생시킬 수 있도록 된 제2 오존발생유닛을 포함한다. claims: 오염원의 실내 공기를 실외로 배출시키는 배기부와;상기 배기부를 통해 배출되는 공기가 정화되는 처리공간을 제공하도록 상기 오염원의 외측에 형성되는 공기처리부와;상기 공기처리부 내에 설치되며, 상기 공기처리부 내의 공간을 상기 배기부의 배출구가 위치하는 제1 처리공간과, 상기 공기처리부의 내주면에 접하는 제2 처리공간으로 구획하며, 상기 제1 처리공간으로부터 제2 처리공간으로 공기가 이동할 수 있는 소정 직경의 통과홀들이 형성된 구획부와;상기 제2 처리공간으로부터 공기를 상기 공기처리부의 외부로 토출시키도록 형성되는 공기토출부와;상기 공기처리부 내에 설치되며 오존을 발생시키는 제1 오존발생유닛과;상기 공기토출부와 연결되도록 상기 공기처리부의 외부에 설치되며, 상기 공기토출부를 통해 토출되는 공기가 통과할 수 있는 토출통로를 구비하고 상기 토출통로 내에 오존을 발생시킬 수 있도록 된 제2 오존발생유닛을 포함하는오존 및 OH 라디칼을 이용한 축사용 공기정화 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

440/1150 Row 440: application_number: 1020190127960, combined_string: invention_title: 냄새 제거 및 신선도 유지 플라즈마 장치 abstract: 본 발명은 상압 플라즈마를 발생시켜 축사의 악취를 제거하고 살균하여 식품의 신선도를 유지하는 냄새 제거 및 신선도 유지 플라즈마 장치에 관한 것으로서, 본 발명에 따른 냄새 제거 및 신선도 유지 플라즈마 장치는, 골격을 형성하는 프레임; 상기 프레임의 내부 전단에 설치되며, 상기 프레임 내부로 외부 공기를 유입시키는 송풍팬; 상기 프레임의 내부 후단에 설치되며, 상기 송풍팬에 의하여 이동하는 공기에 플라즈마 처리를 수행하는 플라즈마 처리부; 상기 프레임의 외면에 부착되어 설치되며, 상기 송풍팬의 유입구 및 상기 플라즈마 처리부의 유출구를 제외한 영역을 외부와 차단하는 차단판;을 포함한다. claims: 골격을 형성하는 프레임;상기 프레임의 내부 전단에 설치되며, 상기 프레임 내부로 외부 공기를 유입시키는 송풍팬;상기 프레임의 내부 후단에 설치되며, 상기 송풍팬에 의하여 이동하는 공기에 플라즈마 처리를 수행하는 플라즈마 처리부;상기 프레임의 외면에 부착되어 설치되며, 상기 송풍팬의 유입구 및 상기 플라즈마 처리부의 유출구를 제외한 영역을 외부와 차단하는 차단판;을 포함하는 냄새 제거 및 신선도 유지 플라즈마 처리장치. 제1항 내지 제8항 중 어느 한 항에 기재된 냄새 제거 및 신선도 유지 플라즈마 처리장치를 콘테이너에 설치하여 이루어지는 신선도 유지 콘테이너., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

441/1150 Row 441: application_number: 1020190118533, combined_string: invention_title: 친환경 가축가금 사육 방법 abstract: 본 발명은 친환경 가축가금 사육 방법에 관한 것으로, 보다 상세하게는 제올라이트, 운모, 고령토와 같은 광물질이 첨가된 물을 가축가금에 음용수로 공급하는 제1사육방법과; 칼슘, 비타민D, 젖산과 같은 영양성분을 사료 또는 음용수에 첨가하여 가축가금에 급여하는 제2사육방법을; 병행함으로써 가축가금의 면역력 강화하고, 가축가금의 소화를 돕는 것 뿐만 아니라 영양요소를 충족시키며, 나아가 운모가 첨가된 발효어분과 같은 사료보조성분을 사료에 혼합하여 가축가금에 급여하는 제3사육방법을; 병행함으로써 가축가금을 단시간에 증체시킬 수 있을 뿐만 아니라 사료의 효율을 증가시켜 사료비를 절감시킬 수 있고, 또한 유기물, 무기물, 톱밥이 혼합된 깔개를 사육장 바닥에 깔아 가축가금을 사육하는 제4사육방법을; 일체로 병행함으로써 사육장 환경을 개선시킴은 물론, 사용 후 깔개를 친환경 토양개량제 또는 퇴비로 재활용할 수 있는 친환경 가축가금 사육 방법에 관한 것이다. claims: 제올라이트, 운모, 고령토를 포함하는 제1성분이 첨가된 수소이온농도 pH 6 ~ 8인 물을 가축가금에 음용수로 공급하는 제1사육방법과; 칼슘, 비타민D, 젖산을 포함하는 제2성분을 사료 또는 음용수에 첨가하여 가축가금에 급여하는 제2사육방법을; 포함하는 것을 특징으로 하는 친환경 가축가금 사육 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

442/1150 Row 442: application_number: 1020190118366, combined_string: invention_title: 구기자를 이용한 고품질 가금류의 사육방법 abstract: 본 발명은 구기자를 이용한 고품질 가금류의 사육방법에 관한것으로, (a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 일반 가금류 급여용 사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 0.5kg~10kg을 혼합하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가금류 출하전 30일~90일간 급여하여 사육하는 단계; (j) 상기(i)단계의 사육과정을 통하여 사육된 가금류를 출하하여 제품화하는 단계를 포함하여 이루어진다. claims: (a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 일반 가금류 급여용 사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 0.5kg~10kg을 혼합하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가금류 출하전 30일~90일간 급여하여 사육하는 단계; (j) 상기(i)단계의 사육과정을 통하여 사육된 가금류를 출하하여 제품화하는 단계를 포함하는 것을 특징으로 하는 구기자를 이용한 고품질 가금류의 사육방법.제1항의 사육방법에 의하여 생산된 가금육., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

443/1150 Row 443: application_number: 1020217008926, combined_string: invention_title: 사료 첨가제 abstract: 본 발명은 감초 추출물을 포함하는, 과잉 배란 처리 후에 얻어진 배의 품질을 개선하기 위한 포유 동물의 사료 첨가제, 및 과잉 배란 처리된 포유 동물을, 감초 추출물을 첨가한 사료를 사용해서 사육하는 것을 포함하는, 과잉 배란 처리 후에 얻어진 배의 품질을 개선하기 위한 방법에 관한 것이다. claims: 감초 추출물을 포함하는, 과잉 배란 처리 후에 얻어진 배의 품질을 개선하기 위한, 포유 동물의 사료 첨가제.과잉 배란 처리된 포유 동물을, 감초 추출물을 첨가한 사료를 사용해서 사육하는 것을 포함하는, 과잉 배란 처리 후에 얻어진 배의 품질을 개선하기 위한 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

444/1150 Row 444: application_number: 1020190117940, combined_string: invention_title: 홍 단심 흑돼지 사육방법 abstract: 본 발명은 산죽(Sasa borealis; 淡竹葉)과 법제 유황을 이용한 조성물을 살균 소독에 적용하고, 산죽의 탄화물을 사료에 배합하여 친환경적으로 돼지를 사육하는 방법에 대한 것으로, 본 발명의 실시예에 따르면, 돼지의 사육에 필요한 생육환경을 조성함에 있어, 산죽과 법제유황을 포함하는 물질을 이용한 소독과 음용 사료를 제조하여 공급할 수 있도록 해, 친환경적인 사육환경을 조성하고 선홍색 빛깔의 육질을 가지는 돼지를 사육할 수 있다. claims: 원재료인 산죽(Sasa borealis)을 열분해하여, 산죽 수액과 탄화물로 분리하는 1단계;상기 1단계에서 추출된 상기 산죽 수액과 법제된 유황 및 가성소다, 소금, 해록석을 혼합하여, 산죽 금단 살균조성물을 형성하는 2단계;상기 산죽 금단 살균조성물을 물과 혼합하여 축사에 분사하여 소독하는 3단계;를 포함하고,상기 2단계는,2-1) 가열부와 교반부를 포함하는 액비제조장치에 가성소다 투입하고 교반 및 가열하여 상기 가성소다를 75~85℃로 구현하는 단계;2-2) 소금과 해록석(glauconite) 및 지장수를 상기 가성소다와 혼합하며 교반하는 단계;2-3) 법제유황을 투입하고, 상기 액비제조기의 온도를 100℃로 유지하며 교반하는 단계;2-4) 상기 1단계의 산죽 수액 100L를 투입하여 5시간 교반하는 단계;를 포함하는, 홍 단심 흑돼지 사육 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

445/1150 Row 445: application_number: 1020190108319, combined_string: invention_title: 폐각 및 질석을 이용한 악취제거용 액상사료첨가제 및 그 제조방법 abstract: 본 발명은 폐각 및 질석을 이용한 악취제거용 액상사료첨가제의 제조방법에 관한 것으로, 상기 악취제거용 액상 사료 첨가제는 분뇨질소 함량이 80% 정도 저감되어, 가축의 분뇨 및 분변의 악취제거를 위한 소, 돼지, 닭 등의 가축 사료 첨가제로서 유용하게 사용될 수 있다. claims: 폐각을 소성하는 소성단계;상기 소성된 폐각을 분쇄하는 분쇄단계;상기 폐각 분쇄물에 물을 첨가하고 교반하는 제1교반단계;상기 제1교반된 혼합물을 상온으로 냉각시키는 냉각단계;상기 냉각된 혼합물에 질석, 힐라이트, 생광석 및 황산을 첨가하고 교반하는 제2교반단계;상기 제2교반된 혼합물을 상온으로 유지하면서 휠타프레스를 이용하여 액상과 슬러지를 분리하는 분리단계; 및상기 액상을 숙성 및 안정시키는 숙성단계를 포함하여 이루어지는 것을 특징으로 하는 폐각 및 질석을 이용한 악취제거용 액상사료첨가제의 제조방법.청구항 1 내지 청구항 4 중에서 어느 하나의 항의 제조방법에 따라 제조된 폐각 및 질석을 이용한 악취제거용 액상사료첨가제., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

446/1150 Row 446: application_number: 1020190104895, combined_string: invention_title: 도축 폐기물을 함유하는 곤충 사료용 조성물, 이를 이용하여 사육한 곤충을 포함하는 가축, 어패류 또는 반려동물 사료용 조성물 abstract: 본 발명은 오리, 돼지 또는 소 등의 가축 도축 폐기물을 함유하는 곤충 사료용 조성물, 또는 상기 곤충 사료용 조성물로 사육된 동애등에와 이의 분변토를 함유하는 가축, 어패류 또는 반려동물 사료용 조성물에 관한 것으로서, 상기 곤충 사료용 조성물, 가축/어패류/반려동물 사료용 조성물은 복잡한 사료 제조 공정을 필요로 하지 않아 매우 경제적이며, 환경오염의 요인으로 대두되고 있고, 그 처리에 대량의 비용이 소요되는 도축 폐기물을 효과적으로 재활용할 수 있어 친환경적이라는 이점이 존재한다. 덧붙여, 상기 곤충 사료용 조성물을 이용하여 곤충을 사육하는 경우, 영양적으로 매우 뛰어난 품질을 가지는 곤충을 얻을 수 있어, 이러한 곤충을 포함하는 가축, 어패류 또는 반려동물 사료용 조성물의 품질 또한 우수해질 수 있는 이점이 있다. 이 외에도, 상기 가축, 어패류 또는 반려동물 사료용 조성물은 동애등에와 이의 분변토가 함유되기 때문에, 일반곡류만을 사용하던 기존 가축사료와 달리 동물성 고급 단백질을 함유할 수 있고, 가축의 건강유지에 도움이 될 수 있다. claims: 도축 폐혈, 도축 폐모, 음식물, 미강, 갈대, 옥수수대, 왕겨 및 깻묵을 포함하는 것을 특징으로 하는 곤충 사료용 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

447/1150 Row 447: application_number: 1020217008632, combined_string: invention_title: 동물에서의 모노글리세라이드의 사용 abstract: 다양한 실시 형태는 이유후(post-weaning) 돼지와 같은 동물에서의 모노글리세라이드의 사용에 관한 것이다. 동물에게 사료급여하는 방법은 하나 이상의 모노글리세라이드를 포함하는 식이를 상기 동물에게 사료급여하는 단계를 포함한다. 다양한 실시 형태는 상기 방법을 수행하기 위한 농축물, 프리믹스(premix), 톱 드레스(top dress), 또는 완전 사료, 및 이들의 제조 방법을 제공한다. claims: 동물에게 사료급여(feeding)하는 방법으로서,하나 이상의 모노글리세라이드를 포함하는 식이를 상기 동물에게 사료급여하는 단계를 포함하는, 방법.동물용 농축물, 프리믹스, 또는 톱 드레스로서,올레에이트(C18:1)를 포함하는 하나 이상의 모노글리세라이드를 포함하며, C18:1 모노글리세라이드 대 C18:0 및 C16:0 모노글리세라이드의 중량비가 적어도 약 0.01인, 동물용 농축물, 프리믹스, 또는 톱 드레스.동물용 완전 사료로서,올레에이트(C18:1)를 포함하는 하나 이상의 모노글리세라이드를 포함하며, 상기 올레에이트(C18:1)를 포함하는 하나 이상의 모노글리세라이드는 상기 완전 사료의 약 0.01 중량% 내지 약 5 중량%인, 동물용 완전 사료.제19항의 완전 사료의 제조 방법으로서,상기 프리믹스, 농축물, 또는 톱 드레스를 상기 기본 동물 사료와 배합하여 상기 완전 사료를 형성하는 단계를 포함하는, 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

448/1150 Row 448: application_number: 1020190103134, combined_string: invention_title: 유해공기 살균 및 탈취장치 abstract: 본 발명은 공기 중에 존재하는 각종 유해가스 제거 및 탈취가 효율적으로 이루어져 대기환경을 쾌적하게 조성함은 물론, 가축이 생활하는 각종 축사의 공기 중에 존재하는 유해가스 제거 및 탈취로 인하여 가축의 생활환경을 쾌적하게 조성할 수 있도록 한 유해공기 살균 및 탈취장치에 관한 것으로, 그 구성은, 내부가 중공인 본체; 상기 박스의 내측 배출구의 전방에 설치된 유해공기흡입수단; 상기 필터의 후방과 상기 유해공기흡입수단의 전방 사이에 설치되는 유해공기정화수단; 상기 복수의 공기유도편 전방과 후방을 고정 설치되는 유도 편 고정수단; 상기 각 공기유도로에 설치되는 살균램프; 로 이루어진다. claims: 내부가 중공인 박스(110)의 일 측벽(140)에 유해공기를 흡입하는 흡입구(120)가 형성되고, 그 흡입구에는 필터(130)가 설치되며, 상기 흡입구의 상호 마주보는 상기 박스의 타 측벽(150)에는 정화된 공기를 배출하는 배기구(160)를 형성시켜 된 본체(100);상기 박스의 내측 배기구의 전방에 설치되어 상기 흡입구로 유해공기가 흡입돼 들어오도록 흡입력을 발생시키는 유해공기흡입수단(200);상기 필터의 후방과 상기 유해공기흡입수단의 전방 사이에 설치되어 필터를 통과한 유해공기가 복수의 영역으로 분할 진행하며 살균 및 탈취가 이루어지도록 광촉매재인 이산화티타늄(TiO2)이 코팅된  형상을 갖는 복수 개의 공기유도편(310)을 일정간격으로 설치하여 복수의 공기유도로(320)를 형성시키되, 그 각 공기유도로(320)는, 상기  형상을 갖는 복수 개의 공기유도편으로 인해 흡입구 쪽의 폭이 배기구 쪽의 폭보다 넓고, 상기 각 공기유도로의 중앙부는, 흡입구 쪽의 폭보다는 좁고, 배기구 쪽의 폭보다는 넓게 형성시켜 된 유해공기정화수단(300);상기 복수의 공기유도편 전방과 후방을 고정 설치하도록 박스의 내측 전방과 후방에 각각의 전방고정수단(410)과 후방고정수단(420)을 설치하되,상기 전방고정수단(410)은, 중앙에 유해공기의 진행을 차단하는 전방공기차단블록(411)이 상기 박스의 높이와 준하는 높이로 설치되고, 상기 전방공기차단블록의 양측으로는 전방유해공기유입로(412)가 각각 형성되며, 그 전방유해공기유입로에는 공기유도편의 위치이동 및 유동을 방지하는 전방고정바(413)가 설치되고,상기 후방고정수단(420)은, 좌우 양측에 유해공기의 진행을 차단하는 후방공기차단블록(421)이 상기 박스의 높이와 준하는 높이로 설치되고, 상기 후방공기차단블록의 사이에는 후방유해공기유입로(422)가 각각 형성되며, 그 후방유해공기유입로에는 공기유도편의 위치이동 및 유동을 방지하는 후방고정바(423)를 설치하여 된 유도 편 고정수단(400);상기 각 공기유도로의 최전방과 최후방에는 365 나노메타 이상의 빛 파장을 갖는 LED 살균램프가 설치되고, 중앙부에는 275 나노메타 이상의 빛 파장을 갖는 LED 살균램프를 설치하여 된 살균램프(500); 로 구성된 것을 특징으로 하는 유해공기 살균 및 탈취장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

449/1150 Row 449: application_number: 1020190101599, combined_string: invention_title: 아마씨와 락토바실러스 플란타럼 LP 유산균 생균제를 함유하는 산란계용 사료 첨가제 및 그 제조방법 abstract: 본 발명은 아마씨와 부형제 탄산칼슘으로 구성된 아마씨와 다가불포화지방산을 유산균 내 CLA 합성 관련 효소 유전자를 발현하는 Lactobacillus plantarum(LP WT177(KCTC18774P) 균주가 포함된 산란계용 사료첨가제를 개시하고 상기 사료첨가제를 산란계에 급여하여 계란 내 오메가-6/오메가-3의 함유 비율개선, CLA 함유량 증진 및 산란계의 염증 및 스트레스를 개선시키는 뛰어난 효과가 있으므로 건강 기능성 계란 및 밀식 사육하는 산란계 환경 개선에 매우 유용한 발명이다. claims: 염기서열목록 1로 표시되는 CLA 합성효소 생산용 유산균주 LP WT177(KCTC18774P) 제 1항의 유산균주 Lactobacillus plantarum LP 177, 아마씨 및 탄산칼슘으로 이루어진 산란계용 사료 첨가제제2항에 있어서, 산란계용 사료 첨가제는 전체 중량에 대하여 아마씨 1.8중량%, 유산균 생균제 1.0중량%로 이루어진 산란계용 사료 조성물제3항의 사료를 산란계에 120g/1두씩 급여하여 염증과 스트레스 관련 지표를 감소시키고 산란 성적은 증대시키는 특징인 밀식 사육 산란계의 사육방법제4항의 방법으로 사육되어 계란내 오메가-6/오메가3 함유비율이 균형있게 개선된 것이 특징인 계란, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

450/1150 Row 450: application_number: 1020190100340, combined_string: invention_title: 가금류 사육장에서의 진드기류 퇴치제 및 이를 이용한 퇴치방법 abstract: 본 발명은 소금을 유효성분으로 함유하는 진드기류 퇴치용 조성물로써, 신속하면서도 높은 효율로 간단하게 가금류의 양식장의 사육과정에서 문제가 되는 진드기류를 퇴치할 수 있어 살충제 성분이 함유되지 않는 친환경 알을 생산할 수 있도록 해주는 진드기류 퇴치제 및 이를 이용한 퇴치방법을 제공한다. claims: 소금을 유효성분으로 함유하는 액상의 가금류 사육장용 와구모 퇴치제.제 1항의 와구모 퇴치제를 가금류에 분사하여 기생하는 와구모를 퇴치하는 것을 특징으로 하는 가금류의 와구모 퇴치방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

451/1150 Row 451: application_number: 1020190099745, combined_string: invention_title: 가축용 사료 이송 및 공급장치 abstract: 본 발명은 가축용 사료 이송 및 공급장치에 관한 것으로, 사료를 이송하는 이송 컨베이어; 상기 이송 컨베이어의 일측부에 구성되며, 이송되는 사료를 공급하여 일정기간 저장 및 배출될 수 있도록 되도록 하고, 저장된 사료의 배출이 이루어지도록 운송하는 사료 운송수단; 일측부에 상기 사료 운송수단의 승강 작동을 지지하도록 구성되고, 타측 상단부로 저장된 상기 사료의 배출이 이루어지도록 구성된 지지 프레임과, 상기 지지 프레임의 내부에 다수개로 구성되며, 상기 사료 운송수단으로부터 사료를 공급받아 적재 및 저장하는 적재 컨베이어와, 상기 적재 컨베이어의 회전 작동을 지지하며, 적재된 사료의 배출이 이루어지도록 하는 구동부재를 포함하는 프레임부; 상기 프레임부 및 사료 운송수단의 작동에 의해 저장된 상기 사료가 투입되며, 투입된 사료를 일정 크기로 분쇄하여 배출하는 사료 분쇄기; 및 상기 사료 분쇄기의 일측부에 구성되고, 축사의 전방부에 구성되어 배출되는 절단된 사료를 각 축사 마다 공급하는 공급 컨베이어;를 포함하는 것을 특징으로 한다. claims: 사료를 이송하는 이송 컨베이어; 상기 이송 컨베이어의 일측부에 구성되며, 이송되는 사료를 공급하여 일정기간 저장 및 배출될 수 있도록 되도록 하고, 저장된 사료의 배출이 이루어지도록 운송하는 사료 운송수단; 일측부에 상기 사료 운송수단의 승강 작동을 지지하도록 구성되고, 타측 상단부로 저장된 상기 사료의 배출이 이루어지도록 구성된 지지 프레임과, 상기 지지 프레임의 내부에 다수개로 구성되며, 상기 사료 운송수단으로부터 사료를 공급받아 적재 및 저장하는 적재 컨베이어와, 상기 적재 컨베이어의 회전 작동을 지지하며, 적재된 사료의 배출이 이루어지도록 하는 구동부재를 포함하는 프레임부; 상기 프레임부 및 사료 운송수단의 작동에 의해 저장된 상기 사료가 투입되며, 투입된 사료를 일정 크기로 분쇄하여 배출하는 사료 분쇄기; 및 상기 사료 분쇄기의 일측부에 구성되고, 축사의 전방부에 구성되어 배출되는 절단된 사료를 각 축사 마다 공급하는 공급 컨베이어;를 포함하는 것을 특징으로 하는 가축용 사료 이송 및 공급장치.사료를 이송하는 이송 컨베이어; 상기 이송 컨베이어의 일측부에 구성되며, 이송되는 사료가 안착되고 안착된 사료를 상부로 운송하는 사료 운송수단; 상기 사료 운송수단이 결합되며, 상기 사료 운송수단의 운송 작동이 이루어지도록 지지 프레임과, 상기 사료 운송수단이 결합되는 이송 프레임과, 상기 지지 프레임의 외면와 상기 이송 프레임의 내면 사이에 구성되며, 상기 이송 프레임의 위치 이동이 이루어지도록 구성되는 구동부재로 구성되는 프레임부; 상기 사료 운송수단의 하향 이동을 안내하며, 투입된 사료의 분쇄가 이루어지도록 분할된 공간을 형성하는 분쇄본체와, 상기 분쇄본체의 상부에 구성되며, 낙하하는 사료가 투입되는 분쇄호퍼와, 상기 분쇄호퍼로부터 공급되는 사료를 분쇄하는 분쇄장치 및 분쇄된 사료를 공급 컨베이어로 배출하는 공급장치를 포함하는 사료 분쇄기; 및 상기 사료 분쇄기의 일측부에 구성되고, 축사의 전방부에 구성되어 배출되는 사료를 각 축사 마다 공급하는 공급 컨베이어;를 포함하는 것을 특징으로 하는 가축용 사료 이송 및 공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

452/1150 Row 452: application_number: 1020190099652, combined_string: invention_title: 공기중의 악취탈취 시스템 abstract: 본 발명은 공기중의 악취탈취 시스템에 관한 것으로서, 악취성분 함유 공기가 유입되는 유입구(11a)가 형성된 하우징(11), 하우징(11) 내측으로 물을 분무하는 분무노즐(12), 분무되는 물에 의하여 악취성분이 제거된 공기를 외기로 배기하는 배기관(13) 및 악취성분이 흡착된 분무된 물이 집수되는 호퍼(14)를 가지는 탈취배기탱크(10)와; 호퍼(14)와 연결된 관로를 통하여 배출되는 악취성분 함유 물을 집수하여 저장하기 위한 것으로서, 외부 환경 변화에도 온도 변화를 최소화할 수 있도록 지중(G)에 매설되는 집수탱크(20)와; 집수탱크(20)에 저장된 물에 함유된 악취성분을 제거하여 정화수로 정화시키기 위한 산기장치(30)와; 집수탱크(20)와 분무노즐(12)을 연결하는 정화수공급라인(40)에 설치되어 집수탱크(20)에 저장된 정화수를 분무노즐(12)로 압송하는 압송펌프(50)와; 압송펌프(50)와 탈취배기탱크(10) 사이의 정화수공급라인(40)과 상기 산기장치(30)와 연결되는 것으로서, 압송펌프(50)에 의하여 압송되는 정화수 일부를 상기 산기장치(30)로 공급하는 선회라인(60);을 포함하는 것을 특징으로 한다. claims: 악취성분 함유 공기가 유입되는 유입구(11a)가 형성된 하우징(11)과, 상기 하우징(11) 내측으로 물을 분무하는 분무노즐(12)과, 분무되는 물에 의하여 악취성분이 제거된 공기를 외기로 배기하는 배기관(13)과, 상기 악취성분이 흡착된 분무된 물이 집수되는 호퍼(14)를 가지는 탈취배기탱크(10);상기 호퍼(14)와 연결된 관로를 통하여 배출되는 악취성분 함유 물을 집수하여 저장하기 위한 것으로서, 외부 환경 변화에도 온도 변화를 최소화할 수 있도록 지중(G)에 매설되는 집수탱크(20);상기 집수탱크(20)에 저장된 물에 함유된 악취성분을 제거하여 정화수로 정화시키기 위한 산기장치(30);상기 집수탱크(20)와 분무노즐(12)을 연결하는 정화수공급라인(40)에 설치되어 상기 집수탱크(20)에 저장된 정화수를 상기 분무노즐(12)로 압송하는 압송펌프(50); 및상기 압송펌프(50)와 탈취배기탱크(10) 사이의 상기 정화수공급라인(40)과 상기 산기장치(30)와 연결되는 것으로서, 상기 압송펌프(50)에 의하여 압송되는 정화수 일부를 상기 산기장치(30)로 공급하는 선회라인(60);을 포함하는 것을 특징으로 하는 공기중의 악취탈취 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

453/1150 Row 453: application_number: 1020190096544, combined_string: invention_title: 동물용 사료 조성물 abstract: 본 발명은, 물 150g에 대하여 백렴 8g, 고백반 0.6g, 백지 8g, 붕사 1g, 백선피 9g, 용뇌 0.7g, 율초 15g, 편백나무 6g, 케나프 20g 비율로 투입하여 5시간 내지 7시간 110℃에서 끓인 후 약 35~45℃에서 7~8시간 숙성시킨 후 냉각하여 제조되는 제1 첨가물을 포함하는 것을 특징으로 한다.이에, 친환경적이고 천연 재료를 사용하여 동물의 사료를 제조하며 발병율 및 동물분의 냄새를 감소시킬 수 있고, 사료 섭취량을 증대시킬 수 있고, 털이 빠지지 않는 동물용 사료 조성물을 제공할 수 있다. claims: 동물용 사료 조성물에 있어서,물 150g에 대하여 백렴 8g, 고백반 0.6g, 백지 8g, 붕사 1g, 백선피 9g, 용뇌 0.7g, 율초 15g, 편백나무 6g, 케나프 20g 비율로 투입하여 5시간 내지 7시간 110℃에서 끓인 후 약 35~45℃에서 7~8시간 숙성시킨 후 냉각하여 제조되는 제1 첨가물을 포함하는 것을 특징으로 하는 동물용 사료 조성물.동물용 사료 조성물에 있어서,물 100g에 대하여 어성초 15g, 꾸지뽕 5g, 비파엽 9g, 땅콩새싹 12g 비율로 투입하여 5시간 내지 7시간 110℃에서 끓인 후 약 35~45℃에서 7~8시간 숙성시킨 후 냉각하여 제조되는 제2 첨가물을 포함하는 것을 특징으로 하는 동물용 사료 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

454/1150 Row 454: application_number: 1020190088944, combined_string: invention_title: 악취제거제 제조 방법 abstract: 본 발명은 악취제거제를 제조하는 방법에 관한 것으로, 보다 상사하게는 악취의 원인 물질을 근본적으로 분해하여 강력한 탈취 기능을 제공하고, 사용이 간단하며, 적은 사용량에서도 탈취 효율이 높은 악취제거제 제조 방법에 관한 것이다.이러한 본 발명은, 물을 90℃ 이상의 온도로 소정 시간 동안 가열하는 살균 단계, 그리고 광합성균 배양액과, 맥주효모, 옥수수전분, 포도당 및 유황을 포함하는 배양 첨가제를 살균된 물에 혼합하여 제1시간 동안 배양하는 광합성균 배양 단계, 그리고 고초균 배양액과, 상기 배양 첨가제를 살균된 물에 혼합하여 제2시간 동안 배양하는 고초균 배양 단계, 그리고 효모균 배양액과, 상기 배양 첨가제를 살균된 물에 혼합하여 제3시간 동안 배양하는 효모균 배양 단계, 그리고 살균된 물에 배양이 완료된 광합성균 배양액, 고초균 배양액, 효모균 배양액 및 혼합 첨가제를 혼합하여 제4시간동안 배양하는 혼합 배양 단계를 포함한다. claims: 물을 90℃ 이상의 온도로 소정 시간 동안 가열하는 살균 단계; 광합성균 배양액과, 맥주효모, 옥수수전분, 포도당 및 유황을 포함하는 배양 첨가제를 살균된 물에 혼합하여 제1시간 동안 배양하는 광합성균 배양 단계; 고초균 배양액과, 상기 배양 첨가제를 살균된 물에 혼합하여 제2시간 동안 배양하는 고초균 배양 단계; 효모균 배양액과, 상기 배양 첨가제를 살균된 물에 혼합하여 제3시간 동안 배양하는 효모균 배양 단계; 및 살균된 물에 배양이 완료된 광합성균 배양액, 고초균 배양액, 효모균 배양액 및 혼합 첨가제를 혼합하여 제4시간동안 배양하는 혼합 배양 단계;를 포함하고, 상기 혼합 배양 단계는 내부에 수용공간을 구비한 교반조 및 상기 교반조의 상부에 구비되고 상기 수용공간 측으로 돌출 구비되며 회전하는 혼합봉을 구비한 믹서를 포함하는 교반기를 통해 수행되고, 상기 교반조는 외면에 구비되는 보호막을 포함하되, 상기 보호막은 상기 교반조의 외면에 접하는 침투층, 상기 침투층의 상부에 구비된 발열층 및 상기 발열층의 상부에 구비된 보호층을 포함하고, 상기 침투층은 폴리에틸렌 100 중량부 대비, 폴리비닐 아세테이트계 저수축제 20 중량부 및 수소첨가 로젠이스테르 수지와 폴리브텐을 포함하는 점착제 50 중량부를 포함하고, 상기 발열층은 이산화루테늄 100 중량부 대비, 은 200 중량부 및 이산화티타늄과 이규화몰리브덴을 포함하는 기능성 결착제 200 중량부를 포함하고, 상기 보호층은 부틸 합성고무 100 중량부 대비, 탄산칼슘과 벤토나이트를 포함하는 충진제 300 중량부, 나프텐 오일 100중량부 및 바륨알루미네이트와 지르코니아를 포함하는 내열제 50 중량부를 포함하는 것을 특징으로 하는 악취제거제 제조 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

455/1150 Row 455: application_number: 1020190082745, combined_string: invention_title: 가금류 사육장에서의 진드기류 퇴치제 및 이를 이용한 퇴치방법 abstract: 본 발명은 소금 및 식초를 유효성분으로 함유하는 진드기류 퇴치용 조성물로써, 신속하면서도 높은 효율로 간단하게 가금류의 양식장의 사육과정에서 문제가 되는 진드기류를 퇴치할 수 있어 살충제 성분이 함유되지 않는 친환경 알을 생산할 수 있도록 해주는 진드기류 퇴치제 및 이를 이용한 퇴치방법을 제공한다. claims: 소금 및 식초를 유효성분으로 함유하되, 스프레이 제형으로소금의 농도는 1~50 %(w/w)이고, 식초는 총산도 1~10%인 현미식초로 1~50 %(w/w) 첨가된 것을 특징으로 하는 액상의 가금류 사육장용 진드기류 살충제.제 1항의 진드기류 살충제를 가금류에 분사하여 기생하는 진드기류를 살충하는 것을 특징으로 하는 가금류의 진드기류 살충방법.제 4항의 방법에 의해 생산된 것을 특징으로 하는 가금류의 알., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

456/1150 Row 456: application_number: 1020190072885, combined_string: invention_title: 가금류의 생산성 개선을 위한 사료 조성물 abstract: 본 발명은, 가금류 생산성 향상을 위한 동물사료에 관한 것이다. claims: 쑥 추출물을 여과 농축하는 공정을 포함하여 얻은 연조엑스, 그리고 소맥말분 및 탄산칼슘을 혼합한 쑥추출물 혼합물과 동물사료를 혼합하여 제조하는 것으로서,상기 쑥 추출물은 1-프로판올 또는 2-프로판올을 쑥 중량 대비 10배 이상 첨가하여 추출 후, 잔류물에 추가로 1-프로판올 또는 2-프로판올을 가하여 재추출하는 단계; 및상기 재추출하여 얻어진 추출액을 여과하여 감압농축하여 연조엑스 형태의 쑥 추출물을 제조하는 단계에 의해 제조된 것이고,상기 제조된 쑥 추출물에는 유파틸린 0.8~2.4 중량% 및 자세오시딘 0.25~0.75 중량%를 포함하는 것이며,상기 동물사료는 옥수수 (Yellow corn), 소맥(Wheat), 대두박 (Soybean meal), 옥수수글루텐박 (Corn gluten meal), 우지 (Tallow), 리신염산염(LysineHCl), 제2인산칼슘 (Dicalcium phosphate), DL-메티오닌 (DL-methionine), 석회석 (Limestone), 염화콜린 (Choline chloride), 소금 (Salt), 비타민 혼합물 (Vit. mixture) 및 미네랄 혼합물 (Min. mixture)를 포함하는 것을 특징으로 하는 사료조성물의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

457/1150 Row 457: application_number: 1020190069531, combined_string: invention_title: 반려동물의 습식사료 조성물의 습식사료 제조 장치 및 방법 abstract: 반려동물의 습식사료 조성물, 습식사료 제조 장치 및 방법은 반려동물의 관절 질환, 피부 질환, 장 질환에 따라 질환별로 정해진 원료를 서로 다른 배합 비율로 배합하여 반려동물에 최적화된 맞춤형 습식사료를 제조할 수 있다.본 발명은 반려동물의 관절 질환, 피부 질환, 장 질환별로 맞춤형 사료를 제조하여 반려동물의 섭취가 용이하고, 이에 따라 반려동물의 소화 흡수율과 면역력 증진, 관절 건강, 피부 건강 관리를 동물 유기를 사전에 예방할 수 있는 효과가 있다. claims: 반려동물의 관절 질환, 피부 질환, 장 질환에 따라 질환별로 곡물, 육고기, 어류, 가시오가피, 홍삼, 채소, 고구마, 호박, 양배추 중 하나 이상의 정해진 원료를 서로 다른 배합 비율로 배합하는 단계;상기 교반된 재료를 170 내지 190℃의 온도에서 35 내지 5 ㎏/㎠ 의 스팀 압력하에 30 내지 50분 동안 스팀 가열하는 단계;상기 가열된 재료들을 스팀으로 익힌 후, 스팀 가열에 의해 점성이 있는 상태로 뭉쳐진 재료를 원형바의 형상으로 길게 뽑아내는 형상을 성형하는 단계; 및상기 원형바 형상으로 성형된 재료를 건조기에 삽입하여 수분 함량이 10% 이하가 되도록 저온 건조하거나 동결 건조하는 단계를 포함하는 것을 특징으로 하는 반려동물의 습식사료 제조 방법.반려동물의 관절 질환, 피부 질환, 장 질환에 따라 질환별로 곡물, 육고기, 어류, 가시오가피, 홍삼, 채소, 고구마, 호박, 양배추 중 하나 이상의 정해진 원료를 서로 다른 배합 비율로 배합하는 재료 배합부;상기 재료 배합부에서 교반된 재료를 170 내지 190℃의 온도에서 35 내지 5 ㎏/㎠ 의 스팀 압력하에 30 내지 50분 동안 스팀 가열하는 가열부;상기 가열부에서 가열된 재료들을 스팀으로 익힌 후, 스팀 가열에 의해 점성이 있는 상태로 뭉쳐진 재료를 원형바의 형상으로 길게 뽑아내는 형상 성형부; 및상기 원형바 형상으로 성형된 재료를 건조기에 삽입하여 수분 함량이 10% 이하가 되도록 저온 건조하거나 동결 건조하는 건조부를 포함하는 것을 특징으로 하는 반려동물의 습식사료 제조 장치.곡물 50 내지 65 중량%, 분쇄된 육고기 8 내지 12 중량%, 분쇄된 어류 15 내지 25 중량%, 미네랄믹스 1 내지 3중량%, 가시오가피 분말 3 내지 7 중량%, 홍삼분말 5 내지 10 중량%을 혼합하여 반려동물의 관절 질환을 위한 사료로 제조되는 것을 특징으로 하는 반려동물의 습식사료 조성물.곡물 50 내지 65 중량%, 분쇄된 육고기 8 내지 12 중량%, 분쇄된 연어 8 내지 12 중량%, 미네랄믹스 1 내지 5 중량%, 채소 8 내지 12 중량%와 딸기 5 내지 10 중량%를 혼합하여 반려동물의 피부 질환을 위한 사료로 제조되는 것을 특징으로 하는 반려동물의 습식사료 조성물.곡물 50 내지 65 중량%, 분쇄된 채소 8 내지 12 중량%, 분쇄된 고구마 8 내지 12 중량%, 호박 3 내지 7중량%, 양배추 10 내지 20 중량%를 혼합하여 반려동물의 장 질환을 위한 사료로 제조되는 것을 특징으로 하는 반려동물의 습식사료 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

458/1150 Row 458: application_number: 1020190068640, combined_string: invention_title: 가축 사육용 축사 abstract: 본 발명은 축사 내부의 공간을 구획하여 돼지 등의 가축의 사육을 효율적으로 할 수 있도록 구현한 가축 사육용 축사에 관한 것으로, 바닥, 벽체 및 지붕으로 형성되는 축사; 상기 축사 내부의 공기를 환기시킬 수 있도록 상기 벽체를 따라 설치되는 환기 장치; 및 상기 축사의 외측에 설치되어 가축에게 공급할 사료를 저장해 두는 사료 저장 탱크를 포함한다. claims: 바닥, 벽체 및 지붕으로 형성되는 축사;상기 축사 내부의 공기를 환기시킬 수 있도록 상기 벽체를 따라 설치되는 환기 장치; 및상기 축사의 외측에 설치되어 가축에게 공급할 사료를 저장해 두는 사료 저장 탱크를 포함하고,상기 축사는, 가축들이 생활하기 위한 공간을 다수 개의 공간으로 구획시킬 수 있도록 내부 바닥을 따라 설치되는 펜스; 및 상기 펜스에 의해 형성된 일 공간으로부터 다른 공간으로 가축이 이동할 수 있도록 상기 펜스와 다른 펜스 사이의 공간에 개폐 가능하도록 설치되는 도어를 포함하며, 상기 도어는, 상기 펜스와 다른 펜스에 각각 상하 길이 방향으로 연장 설치되며, ㄷ형태로 형성되는 슬라이딩 홈을 형성하는 슬라이딩 레일; 및 일측 및 다른 일측이 상기 슬라이딩 홈에 삽입되며, 상기 슬라이딩 홈을 따라 상하 방향으로 승강 또는 하강하면서 상기 펜스와 다른 펜스 사이의 공간을 개폐시키는 슬라이딩 패널을 포함하며,상기 슬라이딩 패널은, 승강된 후 하강되지 아니하도록 상기 슬라이딩 레일의 상부를 체결하기 위한 패널 체결부가 전면 또는 후면의 하부 양측에 구비되며,상기 패널 체결부는, 상기 슬라이딩 패널의 전면 또는 후면의 하부 일측 또는 다른 일측에 형성되는 수용홈; 및 사각 기둥 형태로 형성되며, 하부가 상기 수용홈의 하부에 회동 가능하도록 연결 설치되는 체결 바아를 포함하며,상기 수용홈은, 하측면이 전단으로 갈수록 하측 방향으로 경사지도록 경사면을 형성하며,상기 경사면 및 상기 경사면과 대향하는 상기 체결 바아의 전면 하부에는, 서로 반대 극성을 가지는 자석이 각각 설치되며,상기 체결 바아는, 회동된 후 상기 슬라이딩 레일의 상부가 삽입될 수 있도록 후단으로 갈수록 하측 방향으로 형성되는 체결홈이 전면에 형성되며, 상기 도어는, 상기 슬라이딩 홈의 하측에 설치되며, 상기 슬라이딩 홈을 따라 하강하는 상기 슬라이딩 패널의 일측 또는 다른 일측을 탄성력을 이용하여 지지하는 탄성 지지대를 더 포함하며, 상기 탄성 지지대는, 평판 형태로 형성되어 상기 슬라이딩 패널의 일측 또는 다른 일측을 지지하는 상판; 상기 상판의 하측에 이격되어 설치되며, 내부 공간을 형성하는 케이스; 및 상기 케이스의 내부 공간에 설치되며, 상부가 상기 케이스의 상측으로 노출되어 탄성력을 이용하여 상기 상판을 지지하는 상판 지지부를 포함하며,상기 상판 지지부는, 상기 상판의 중심을 지지하며, 상기 상판이 하강함에 따라 내부 공간에 담긴 충전액을 공급하는 제1 지지부; 및 상기 상판의 각 모서리의 하측에 각각 설치되며, 상하 방향으로 이동되면서 상기 상판의 모서리를 탄성력을 이용하여 지지하며, 상기 상판이 하강함에 따라 상기 제1 지지부로부터 공급되는 충전액에 의해 상하 방향의 이동이 제동되는 제2 지지부; 상기 제1 지지부는, 상기 상판의 하측면의 중심에 설치되며, 구형의 내부 공간을 형성하는 제1 회동 체결부; 상기 제1 회동 체결부의 내부 공간의 형태에 대응하는 구형으로 형성되며, 상기 제1 회동 체결부의 내부 공간에 회전 가능하도록 설치되는 제1 연결 볼; 상기 제1 연결 볼의 하부로부터 하측 방향으로 연장 형성되어 상기 제1 연결 볼을 지지하는 제1 지지 바아; 원기둥 형태로 형성되어 상기 케이스의 내부 공간에 설치되며, 밀폐된 내부 공간에 충전액이 수용되며, 상기 제1 지지 바아의 하부가 내부 공간으로 삽입되며, 상기 상판이 하강할 경우 상기 제1 지지 바아의 하부가 내부 공간의 상측으로부터 하강함에 따라 충전액이 압착되어 상기 제2 지지부로 공급되는 충전액 탱크; 및 상기 충전액 탱크의 하부로부터 상기 제2 지지부까지 연장 형성되어 충전액이 흐르는 통로를 형성하는 연결관을 포함하며, 상기 제2 지지부는, 상기 상판의 하측면의 모서리에 설치되며, 구형의 내부 공간을 형성하는 제2 회동 체결부; 상기 제2 회동 체결부의 내부 공간의 형태에 대응하는 구형으로 형성되며, 상기 제2 회동 체결부의 내부 공간에 회전 가능하도록 설치되는 제2 연결 볼; 상기 제2 연결 볼의 하부로부터 하측 방향으로 연장 형성되어 상기 제2 연결 볼을 지지하는 제2 지지 바아; 상기 제2 지지 바아의 하측에 설치되어 탄성력을 이용하여 상기 제2 지지 바아를 지지하는 탄성 지지부; 및 상하 방향으로 관통홀을 형성하는 원형의 튜브 형태로 형성되어 상기 관통홀에 상기 제2 지지 바아가 삽입되며, 상기 상판이 하강할 경우 상기 연결관을 통해 충전액이 내부 공간으로 공급되어 팽창함에 따라 상기 관통홀의 크기가 줄어들어 상기 제2 지지 바아가 움직이지 못하도록 체결하는 승하강 조절부를 포함하며,상기 승하강 조절부는, 충전액이 내부 공간으로 공급됨에 따라 상기 관통홀이 위치하는 내측 방향으로 팽창될 수 있도록 외측벽이 경질의 재질로 형성되고, 상기 제2 지지 바아와 대향하는 내측이 팽창 또는 수축이 가능한 재질로 형성되는, 가축 사육용 축사., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

459/1150 Row 459: application_number: 1020210005753, combined_string: invention_title: 계란 품질 자동검사 시스템 abstract: 본 발명은 이송 과정에서 암실을 통과하는 계란의 이미지를 촬영하고, 촬영된 다수의 계란 이미지를 인공지능을 통해 분석하여 상품으로서 불량한 상태인 계란을 선별함에 있어 높은 신뢰도를 확보할 수 있도록 구성되는 검사 시스템에 관한 것이다.본 발명에 의한 계란 품질 자동검사 시스템은 컨베이어를 포함하는 이송 라인에 설치되어 암실을 형성하고, 컨베이어의 상단에 안착된 상태로 회전되며 이송되는 계란을 암실에서 촬영하여 계란 이미지를 생성하며, 생성된 계란 이미지를 선별부로 전송하는 촬영부, 촬영부의 하방에 설치된 상태로 촬영을 위해 조명하는 조명부 및, 촬영부로부터 전송되는 계란 이미지를 인공지능으로 분석하여 선별하고, 불량으로 선별된 계란의 위치 정보를 생성하는 선별부를 포함하여 구성되는 것을 특징으로 한다. claims: 컨베이어를 포함하는 이송 라인에 설치되어 암실을 형성하고, 상기 컨베이어의 상단에 안착된 상태로 회전되며 이송되는 계란을 상기 암실에서 촬영하여 계란 이미지를 생성하며, 생성된 계란 이미지를 선별부로 전송하는 촬영부(100);상기 촬영부(100)의 하방에 설치된 상태로 촬영을 위해 조명하는 조명부(200); 및,상기 촬영부(100)로부터 전송되는 계란 이미지를 인공지능으로 분석하여 선별하고, 불량으로 선별된 계란의 위치 정보를 생성하는 선별부(300); 를 포함하고,상기 촬영부(100)는,내부에 공간이 형성된 상태로 일측에 유입구(111)가 형성되고, 타측에 배출구(112)가 형성되는 본체부(110);상기 본체부(110)의 유입구(111)측에 설치되어 내부의 공간으로 진입하는 계란을 감지하는 센서부(120);상기 본체부(110)의 내부에 설치되어 그 내부를 통과하는 계란을 촬영하며 다수의 계란 이미지를 생성하는 다수의 머신비전 카메라(130); 및,생성된 다수의 계란 이미지를 상기 선별부(300)로 전송하는 통신부(140); 를 포함하고,상기 본체부(110)는 상단과 하단이 모두 개방되는 하부체(113)와, 상단에 일자형의 관통홀(114)이 형성된 상태로 상기 하부체(113)의 상단측 모서리에 힌지 결합되는 덮개 형태의 중부체(115), 그리고 상기 중부체(115)의 상단측 모서리에 힌지 결합되는 덮개 형태의 상부체(116)로 형성되고,상기 본체부(110)는 상기 중부체(115)와 상기 상부체(116)가 함께 축회전하여 상기 하부체(113)의 내부를 개방할 수 있도록 구성되고, 상기 상부체(116)가 단독으로 축회전하여 상기 중부체(115)의 상단을 개방할 수 있는 2중의 개방 구조로 구성되는 것을 특징으로 하는 계란 품질 자동검사 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

460/1150 Row 460: application_number: 1020200171689, combined_string: invention_title: 병아리 사육장의 환기장치 abstract: 본 발명은 부화한 병아리를 사육하는 병아리 사육장의 환기장치에 관한 것으로 보다 구체적인 것은, 병아리 사육장의 일측벽에 배기창을 내어 내부의 공기를 외부로 강제 배출시키는 배기부를 형성하고, 배기창이 형성된 벽체 양측에 위치하는 양측벽에는 외부의 공기를 내부로 흡인하는 흡기부를 형성하여 배기부와 흡기부를 이용하여 사육장 내부의 공기를 환기하고, 환기시 온습도를 조정할 수 있게 한 것인데, 배기부의 배기창에는 전동기로 작동하는 전동배출팬을 장치하여 전동배출팬이 회전하면 배기창 출구에 장치된 셔터가 열리고, 전동배출팬이 정지하면 셔터가 닫히는 개폐장치를 구비하고, 배기창 외측에 배기실을 만들어 배기실 천정에 지하수를 분사하는 분사노즐을 장치하여 배기창으로 배출되는 분진과 오염물을 배기실 실부에서 분사되는 물에 포집시켜 배기실 바닥으로 낙하시켜 바닥에 배치한 배수홈을 통해 집수정화조로 들어가게 함으로써, 배출되는 오염물과 분진이 배기실외부로 나가 공중에 비산되는 것을 예방하고, 흡기부에는 일정간격으로 흡기창을 형성하여 각 흡기창 내면에는 견인끈으로 개폐되는 개폐판을 설치하여 개폐판을 일거에 개폐하도록 하되, 흡기창 외측에 흡기실을 형성하여 흡기실 천정에 지하수를 분사하는 분사노즐을 장치하여 외부 공기와 같이 습기를 공급할 수 있게 하고, 흡기실 외벽에 흡기부를 형성하여 흡기부 크기를 조정할 수 있게 상하로 이동하는 가림판을 설치하여 흡기구의 크기를 조정할 수 있게 함으로써, 흡기량의 조정이 용이하며, 바닥에는 배수홈을 형성하여 분사노즐에서 분사된 물이 바닥에 떨어지면 배수홈을 따라 집수정화조로 들어가게 하여 배수관리가 위생적으로 이루어지게 한 병아리 사육장의 환기장치이다. claims: 병아리 사육장(1)의 길이방향 일측 외벽(1a)에 배기창(2)을 형성하여 배기창에는 입구(2a)측에 전동장치(3)에 의하여 회전하며, 내부의 공기를 외부로 강제 배출시키는 전동배출팬(4)을 장치하고, 배기창 출구측에는 전동배출팬이 회전하면 열리고, 전동배출팬이 정지하면 닫히는 셔터(5)를 장치하며, 셔터(5) 외측에 보온덮개(6)를 장치하여 개폐할 수 있게 하고, 배기창 외측으로 일정간격을 두고, 배기실(7a)을 형성하여 배기실 상단에 지붕(7b)을 형성하고, 외벽(7c)에 배출구(7d)를 형성하며, 바닥에 배수홈(6e)을 만들어 집수정화조와 연결시키고, 배기실 천정에 지하수를 공급하는 관로(7e)를 설치하여 일정간격에 지하수분사노즐(7f)을 장치한 배기부(7)를 형성하여 배기창을 통해 배출되는 분진과 오염물을 분사노즐에서 분사되는 물에 포집시켜 배기실 바닥으로 낙하시키고, 배수홈을 따라 집수정화부로 이송되게 함으로써, 배기창으로 배출되는 분진이 배기실 외부로 나가 공중에 비산되지 않게 구성하고, 병아리 사육장의 양측벽에는 일정간격으로 흡기창(8)을 설치하여 흡기창 내면에 개폐판(8a)을 설치하여 개폐판에 견인끈(8c)을 연결하여 정역회전전동기(8g)를 통해 일거에 개폐되게 하며, 흡기창 외측에 흡기실(9a)을 형성하여 흡기실 상부에 지붕(9b)을 설치하고, 외벽에 흡기구(9c)를 형성하고, 흡기실 천정에 지하수공급관(9d)을 배치하여 지하수분사노즐(9e)을 장치하고, 흡기실 바닥에 배수홈(9f)을 형성하여 집수정화조와 연통시키고, 흡기실 외벽에 가림판(9g)을 설치하여 가림판의 일단에 말대(9h)를 부착하여 가림판을 감거나 푸는 방법으로 흡기실의 크기를 조정하는 흡기부(9)를 형성하여서 되는 병아리 사육장의 환기장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

461/1150 Row 461: application_number: 1020200108021, combined_string: invention_title: 파각란 검출장치 abstract: 본 발명은 타격대가 계란을 타격한 다음에 감지되는 반발력을 이용하여 균열의 발생 여부를 판단하므로 정확하고 신속하게 균열의 감지가 가능하며 하나의 계란에 한번씩의 타격만이 행해져 계란의 파손이 방지되고 구조가 단순하게 이루어지는 파각란 검출장치를 제공한다.본 발명의 파각란 검출장치는 이송컨베이어의 위쪽에 설치되는 프레임과, 프레임에 폭방향으로 가로질러 설치되는 복수의 타격지지축과, 타격지지축에 설치되고 반발감지센서가 설치되는 복수의 타격대와, 타격대를 타격지지축에 고정하고 한쪽에 타격안내돌기가 형성되는 타격조립부재와, 타격대의 끝단부가 이송컨베이어쪽으로 가까워지도록 힘을 가하는 탄성부재와, 프레임에 설치되는 복수의 회전지지축과, 타격안내돌기와 접하여 타격대가 회전하는 것을 제한하는 타격안내부재와, 구동모터와, 동력전달장치와, 감지된 반발력을 비교하여 균열의 발생여부를 판단하는 중앙처리장치와, 균열 발생 계란의 위치를 표시하는 표시장치를 포함하고, 홀수행에 위치하는 타격지지축에는 계란의 중앙쪽을 타격하도록 하나의 타격대를 설치하고, 짝수행에 위치하는 타격지지축에는 계란의 양쪽 끝부분쪽을 타격하도록 한쌍의 타격대를 서로 다른 위상을 갖게 배치하여 설치한다. claims: 다수의 계란을 일정한 간격으로 복수의 열로 배열된 상태로 이송하는 이송컨베이어의 위쪽에 배치되어 설치되는 프레임과, 상기 프레임에 상기 이송컨베이어에 적재되어 이송되는 계란의 이송방향 전후 간격에 대응되는 간격을 두고 배치되어 이송컨베이의 폭방향으로 가로질러 설치되는 복수의 타격지지축과, 상기 이송컨베이어에 적재되어 이송되는 계란의 좌우 간격에 대응되는 간격을 두고 상기 타격지지축에 배치되어 회전가능하게 설치되고 끝단부에는 계란과 충돌후의 반발력을 감지하는 반발감지센서가 설치되는 복수의 타격대와, 상기 타격대를 각각 상기 타격지지축에 회전가능하게 고정하고 한쪽에 타격안내돌기가 돌출 형성되는 타격조립부재와, 상기 타격대의 끝단부가 상기 이송컨베이어쪽으로 가까워지도록 각각 힘을 가하는 복수의 탄성부재와, 상기 타격지지축과 간격을 두고 평행하게 상기 프레임에 설치되는 복수의 회전지지축과, 상기 타격지지축에 설치되는 타격대에 각각 대응하도록 상기 회전지지축에 설치되고 상기 타격조립부재의 타격안내돌기와 접하여 상기 타격대의 끝단부가 이송컨베이어쪽으로 가까워지도록 회전하는 것을 일정 각도 범위에서 제한하는 복수의 타격안내부재와, 상기 프레임에 설치되는 구동모터와, 상기 구동모터의 회전력을 전달하여 상기 회전지지축을 회전시키는 동력전달장치와, 상기 반발감지센서에서 감지된 반발력을 설정된 반발력과 비교하여 균열의 발생여부를 판단하여 출력하는 중앙처리장치와, 상기 중앙처리장치로부터 출력되는 균열 발생 계란의 위치를 표시하는 표시장치를 포함하고,상기 복수의 타격지지축 중에서 홀수번째 행(홀수행)에 위치하는 타격지지축에는 계란의 중앙쪽을 타격하도록 타격대를 설치하고, 짝수번째 행(짝수행)에 위치하는 타격지지축에는 계란의 양쪽 끝부분쪽을 타격하도록 타격대를 설치하고,상기 짝수번째 행(짝수행)에 위치하는 타격지지축에 계란의 양쪽 끝부분쪽을 타격하도록 설치되는 타격대는 서로 위상차를 갖게 배치하여 설치하고,상기 타격안내부재에는 둘레의 일부를 절개하여 상기 타격조립부재의 타격안내돌기가 삽입되는 돌기삽입홈을 형성하고,상기 타격지지축은 계란이 회전하면서 이송될 때에 하나의 계란에 대하여 서로 다른 복수의 지점을 타격하도록 복수개의 행을 하나의 세트로 구성하여 설치하고,상기 프레임에는 상기 타격지지축과 간격을 두고 평행하게 상기 탄성부재의 끝단부가 고정되는 탄성고정대를 더 설치하는 파각란 검출장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

462/1150 Row 462: application_number: 1020200064199, combined_string: invention_title: 파각란 검출장치 abstract: 본 발명은 타격대가 계란을 타격한 다음에 감지되는 반발력을 이용하여 균열의 발생 여부를 판단하므로 정확하고 신속하게 균열의 감지가 가능하고 구조가 단순하게 이루어지는 파각란 검출장치를 제공한다.본 발명의 파각란 검출장치는 계란을 이송하는 이송컨베이어의 위쪽에 배치되어 설치되는 프레임과, 프레임에 간격을 두고 폭방향으로 가로질러 설치되는 복수의 타격지지축과, 간격을 두고 타격지지축에 회전가능하게 설치되고 반발감지센서가 설치되는 복수의 타격대와, 타격대를 타격지지축에 회전가능하게 고정하고 한쪽에 타격안내돌기가 형성되는 타격조립부재와, 타격대의 끝단부가 이송컨베이어쪽으로 가까워지도록 힘을 가하는 복수의 탄성부재와, 타격지지축과 간격을 두고 프레임에 설치되는 복수의 회전지지축과, 회전지지축에 설치되고 타격안내돌기와 접하여 타격대가 회전하는 것을 일정 각도 범위에서 제한하는 복수의 타격안내부재와, 프레임에 설치되는 구동모터와, 구동모터의 회전력을 전달하여 회전지지축을 회전시키는 동력전달장치와, 반발감지센서에서 감지된 반발력을 설정된 반발력과 비교하여 균열의 발생여부를 판단하여 출력하는 중앙처리장치와, 중앙처리장치로부터 출력되는 균열 발생 계란의 위치를 표시하는 표시장치를 포함한다. claims: 다수의 계란을 일정한 간격으로 복수의 열로 배열된 상태로 이송하는 이송컨베이어의 위쪽에 배치되어 설치되는 프레임과, 상기 프레임에 상기 이송컨베이어에 적재되어 이송되는 계란의 이송방향 전후 간격에 대응되는 간격을 두고 배치되어 이송컨베이의 폭방향으로 가로질러 설치되는 복수의 타격지지축과, 상기 이송컨베이어에 적재되어 이송되는 계란의 좌우 간격에 대응되는 간격을 두고 상기 타격지지축에 배치되어 회전가능하게 설치되고 끝단부에는 계란과 충돌후의 반발력을 감지하는 반발감지센서가 설치되는 복수의 타격대와, 상기 타격대를 각각 상기 타격지지축에 회전가능하게 고정하고 한쪽에 타격안내돌기가 돌출 형성되는 타격조립부재와, 상기 타격대의 끝단부가 상기 이송컨베이어쪽으로 가까워지도록 각각 힘을 가하는 복수의 탄성부재와, 상기 타격지지축과 간격을 두고 평행하게 상기 프레임에 설치되는 복수의 회전지지축과, 상기 타격지지축에 설치되는 타격대에 각각 대응하도록 상기 회전지지축에 설치되고 상기 타격조립부재의 타격안내돌기와 접하여 상기 타격대의 끝단부가 이송컨베이어쪽으로 가까워지도록 회전하는 것을 일정 각도 범위에서 제한하는 복수의 타격안내부재와, 상기 프레임에 설치되는 구동모터와, 상기 구동모터의 회전력을 전달하여 상기 회전지지축을 회전시키는 동력전달장치와, 상기 반발감지센서에서 감지된 반발력을 설정된 반발력과 비교하여 균열의 발생여부를 판단하여 출력하는 중앙처리장치와, 상기 중앙처리장치로부터 출력되는 균열 발생 계란의 위치를 표시하는 표시장치를 포함하고,상기 프레임에는 상기 타격지지축과 간격을 두고 평행하게 상기 탄성부재의 끝단부가 고정되는 탄성고정대를 더 설치하고,상기 복수의 타격지지축 중에서 홀수번째 행(홀수행)에 위치하는 타격지지축에는 계란의 중앙부 양쪽을 타격하도록 타격대를 설치하고, 짝수번째 행(짝수행)에 위치하는 타격지지축에는 계란의 양쪽 끝부분쪽을 타격하도록 타격대를 설치하고,상기 타격지지축은 계란이 회전하면서 이송될 때에 하나의 계란에 대하여 서로 다른 복수의 지점을 타격하도록 복수개의 행을 하나의 세트로 구성하여 설치하고,상기 타격안내부재에는 둘레의 일부를 절개하여 상기 타격조립부재의 타격안내돌기가 삽입되는 돌기삽입홈을 형성하는 파각란 검출장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

463/1150 Row 463: application_number: 1020200062268, combined_string: invention_title: 불량 계란 색출 및 계란 분류를 위한 계란 선별 장치 abstract: 본 발명의 실시 예에 따른 불량 계란 색출 및 계란 분류를 위한 계란 선별 장치는, 계란이 안착되도록 구비되는 계란 홀더; 상기 계란 홀더를 이송시키는 이송부; 상기 계란 홀더에 안착되어 이송된 계란을 세척하는 세척부; 세척부를 통과한 계란을 건조하는 건조부; 불량 계란을 감지하고 색출하는 불량 선별부; 계란의 중량을 감지하여 중량별로 계란을 분류하는 중량 선별부 및 선별된 계란을 포장하는 포장부를 포함하는 것을 특징으로 한다.본 발명의 실시 예에 따른 불량 계란 색출 및 계란 분류를 위한 방법은, 계란을 계란 홀더에 안착시키는 안착 단계; 계란을 세척하는 세척 단계; 세척된 계란을 건조하는 건조 단계; 건조된 계란의 불량 여부를 감지하고, 불량 계란을 색출하는 불량 계란 선별 단계; 계란을 중량별로 분류하는 중량 분류 단계 및 중량별로 분류된 계란을 포장하는 포장 단계를 포함할 수 있다. claims: 계란이 안착되도록 구비되는 계란 홀더;상기 계란 홀더를 이송시키는 이송부;상기 계란 홀더에 안착되어 이송된 계란을 세척하는 세척부;세척부를 통과한 계란을 건조하는 건조부;불량 계란을 감지하고 색출하는 불량 선별부;계란의 중량을 감지하여 중량별로 계란을 분류하는 중량 선별부 및 선별된 계란을 포장하는 포장부를 포함하고,상기 계란 홀더는,타원형의 계란이 안착될 수 있는 타원형으로 함몰된 안착부가 형성되고,상기 안착부에는,안착부에 안착된 계란이 미끄러짐에 따라 이탈하는 것을 방지하는 미끄럼 방지부재 및 안착부에 안착된 계란이 안착부의 내벽과 맞닿아 깨지는 것을 방지하는 완충 부재가 구비되고,상기 안착부의 하부에는,안착부에 안착된 계란을 흡입하여 고정시키는 흡입 고정부가 형성되고,상기 불량 선별부는,계란을 타격하는 타격 수단 및상기 타격 수단에 의해 타격된 계란의 소리를 감지하여, 계란의 불량 여부를 감지하는 불량 감지 수단을 포함하고,상기 불량 감지 수단에 의해 계란이 불량임을 감지할 경우,불량 계란이 안착되어있던 계란 홀더를 불량 계란 이송 라인으로 운송하고,불량 계란 이송 라인의 종단에는,불량 계란의 껍질과 내용물을 분리하는 불량 계란 처리 수단이 구비되는 것을 특징으로 하는 불량 계란 색출 및 계란 분류를 위한 계란 선별 장치, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

464/1150 Row 464: application_number: 1020200056773, combined_string: invention_title: 육계 출하관리를 위한 성장 모니터링 장치 abstract: 본 발명의 일 실시예에 따르면, 디스플레이 스크린; 및 상기 디스플레이 스크린을 통하여 개체의 목표 무게를 입력받는 제1입력 박스를 표시하고, 개체의 일령별 평균 무게를 제1그래프상에 표시하고, 개체의 일령별 평균 무게 및 상기 개체의 일령별 평균 무게가 목표 무게에 이를 것으로 예측되는 출하 예상 일자를 표시하도록 설정된 프로세서를 포함하고, 상기 프로세서는 상기 제1그래프의 제1축은 날짜를 표시하고, 제2축은 평균 무게를 표시하도록 제어하고, 상기 프로세서는 상기 제1그래프상에 적어도 하나의 상기 개체의 일령별 평균 무게를 선택 가능한 마크로 표시하며, 상기 마크가 선택되는 경우 선택된 일령별 평균 무게에 대한 분포 데이터를 제2그래프로 표시하도록 제어하는 사육 환경 모니터링 장치를 제공한다. claims: 디스플레이 스크린; 및적어도 두개 이상의 개체의 일령별 평균 무게를 나타내는 제1그래프를 상기 디스플레이 스크린에 표시하는 프로세서를 포함하고, 상기 프로세서는 개체의 현재 평균 무게 및 개체의 평균 무게가 목표 무게에 이를 것으로 예측되는 출하 예상 일자를 표시하도록 설정되고,적어도 두 개 이상의 개체의 일령별 평균 무게는 사용자 입력에 의해 선택 가능하고, 상기 프로세서는 상기 사용자 입력에 대한 응답으로, 선택된 개체의 일령별 평균 무게에 대한 분포 데이터를 나타내는 제2그래프를 표시하도록 제어하는 사육 환경 모니터링 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

465/1150 Row 465: application_number: 1020200055466, combined_string: invention_title: 먹이공급용 진동 피더 abstract: 본 발명은 먹이공급용 진동 피더에 관한 것으로, 보다 상세하게는 수족관의 어항(수조), 양어장, 축사 등에 설치하여 물고기나 닭 등에게 일정시간마다 적정량의 먹이(모이)를 공급할 수 있도록 한 것이다.또한, 본 발명은 복잡한 구조나 장치 들을 배제하고, 간단한 구조와 더불어 진동자의 부정형 진동만을 이용하여, 저장된 먹이(모이)를 일정시간마다 적정량을 안정적으로 공급할 수 있다.특히, 본 발명은 별도의 복잡한 구성이나 장치를 이용하지 않고, 스프링 등의 탄성력을 이용하여, 먹이를 배출하는 공급량조절판이 부정형으로 움직이도록 함으로써, 습기에 의해 저장된 먹이가 뭉쳐지더라도 지속적인 먹이공급이 이루어질 수 있다.따라서, 먹이공급장치 분야, 특히 자동 먹이공급장치 분야와 더불어, 가축 사육 분야, 어류양식 분야, 축사/양어장/수족관 관리분야 등은 물론, 이와 유사 내지 연관된 분야에서 신뢰성 및 경쟁력을 향상시킬 수 있다. claims: 하부에 배출홀이 형성된 호퍼;상기 배출홀로부터 일정거리 이격되도록 구성된 베이스;상기 베이스의 상부에 부정형운동이 가능하도록 구성되어 상기 배출홀의 하부에 밀착되는 공급량조절판; 및상기 공급량조절판을 부정형으로 진동시키는 진동자;를 포함하는 먹이공급용 진동 피더., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

466/1150 Row 466: application_number: 2020200001425, combined_string: invention_title: 닭 사료를 자동으로 벨트 콘베어 식으로 주기 abstract: 본 고안은 닭에 사료를 자동으로 주게 한 고안인데, 본 설비를 설치하면 주인 한 사람이 수많은 닭을 관리할 수 있고, 인건비 절감의 효과도 보는 고안이다.[기술분야]본 기술은 닭에 사료를 자동으로 주게 한 기술인데, 본 설비를 설치하면 주인 한 사람이 수많은 닭을 관리할 수 있고, 인건비 절감의 효과도 보는 기술이다.[해결하려는 과제]닭사료는 사람이 일일이 칸칸이 다니며 부어준다. 이것이 해결 하려는 과제이다.[과제의 해결 수단]본 고안은 사료통에 닭사료를 부어 놓으면 모터로 아래로 조금씩 흘러내리면 아래 설치된 특히 좁은 벨트 콘베어가 돌아가며 사료를 운반하여 준다이로서 과제의 해결 수단이 된다 claims: 도면 1의 그림에서닭 ①에 사료를 사료통 ③에 부어 놓으면 전원 스위치 ②를 사료가 하부로 내려와 소형 벨트 콘베어 ④에 실려 닭 ①으로 가서 먹이를 먹게 한 고안이다., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

467/1150 Row 467: application_number: 1020200051068, combined_string: invention_title: 스마트 가축 관리 시스템 및 그 방법 abstract: 스마트 가축 관리 시스템 및 그 방법이 제공된다. 상기 방법은 가축관리서버가 축사에 위치하는 가축들을 촬영한 가축영상데이터를 획득하는 단계; 상기 가축관리서버가 상기 가축영상데이터에 포함된 상기 가축들을 개별 객체로 각각 분리하는 단계; 상기 가축관리서버가 상기 가축영상데이터으로부터 상기 개별 객체의 객체체온정보 및 객체행동정보가 포함된 객체정보를 추출하는 단계; 상기 가축관리서버가 표준축사관리데이터를 기초로하여 상기 객체정보를 분석하여 상기 가축의 이상징후여부를 판단한 판단결과데이터를 생성하는 단계; 및 상기 가축관리서버가 상기 판단결과데이터를 관리자 단말기로 전송하는 단계;를 포함하되, 상기 가축관리서버는 상기 표준축사관리데이터를 기초로하여 딥러닝 기법을 이용하여 상기 가축의 이상징후여부 판단하고, 상기 이상징후여부를 질병증상, 분만증상 및 승가증상으로 구분할 수 있다. claims: 가축관리서버가 축사에 위치하는 가축들을 촬영한 가축영상데이터를 획득하는 단계;상기 가축관리서버가 상기 가축영상데이터에 포함된 상기 가축들을 개별 객체로 각각 분리하는 단계;상기 가축관리서버가 상기 가축영상데이터로부터 상기 개별 객체의 객체체온정보 및 객체행동정보가 포함된 객체정보를 추출하는 단계;상기 가축관리서버가 표준축사관리데이터를 기초로하여 상기 객체정보를 분석하여 상기 가축의 이상징후여부를 판단한 판단결과데이터를 생성하는 단계; 및상기 가축관리서버가 상기 판단결과데이터를 관리자 단말기로 전송하는 단계;를 포함하고,상기 표준축사관리데이터는, 상기 가축영상데이터로부터 이상징후여부가 발생되지 않은 정상객체 및 상기 정상객체의 주변객체의 최고체온정보 및 최저체온정보를 반복 학습하여 생성된 객체기본온도정보와, 정상축사 및 상기 정상축사의 주변축사의 최고온도정보 및 최저온도정보를 반복 학습하여 생성된 축사기본온도정보, 및 상기 정상객체의 정상행동을 분석하여 생성된 객체기본행동정보를 포함하고,상기 가축관리서버는, 상기 표준축사관리데이터를 기초로 하여 딥러닝 기법을 이용하여 상기 가축의 이상징후여부 판단하고, 상기 이상징후여부를 질병증상, 분만증상 및 승가증상으로 각각 구분하고,상기 판단결과데이터를 생성하는 단계는, 상기 가축관리서버가 상기 객체체온정보와 상기 표준축사관리데이터에 포함된 상기 객체기본온도정보 및 상기 객체행동정보와 상기 표준축사관리데이터에 포함된 상기 객체기본행동정보를 비교 분석하는 단계;상기 비교 분석한 결과로 상기 이상징후여부가 상기 질병증상으로 판단된 경우, 상기 가축관리서버가 질병객체에 대한 상기 객체체온정보를 모니터링하여 질병확산경로를 예측하는 단계;상기 비교 분석한 결과로 상기 이상징후여부가 상기 분만증상으로 판단된 경우, 상기 가축관리서버가 분만객체에 대한 상기 객체행동정보를 모니터링하여 분만상황정보를 예측하는 단계; 및상기 비교 분석한 결과로 상기 이상징후여부가 상기 승가증상으로 판단된 경우, 상기 가축관리서버가 승가객체에 대한 상기 객체행동정보를 모니터링하여 승가상황정보를 예측하는 단계;를 포함하고, 상기 질병확산경로를 예측하는 단계는,상기 가축관리서버가 상기 질병객체의 체온을 측정하여 제1 객체온도정보를 획득하고, 상기 질병객체의 주변객체의 체온을 측정하여 제2 객체온도정보를 획득하는 단계; 및상기 가축관리서버가 상기 표준축사관리데이터에 포함된 상기 객체기본온도정보를 기초로 하여 상기 제1 객체온도정보 및 제2 객체온도정보 간의 제1 온도차이를 산출하여 질병확산경로를 예측하는 단계;를 포함하고,상기 분만상황정보를 예측하는 단계는,상기 가축관리서버가 상기 분만객체의 분만 후에 환경정보를 고려하여 신규객체에 대한 객체체온정보 및 객체행동정보를 모니터링하여 이상징후가 발생한 경우, 상기 관리자 단말기로 알림메시지를 전송하는 단계-상기 환경정보는, 상기 분만객체 및 상기 축사 주변의 날씨정보, 계절정보 및 시간정보를 포함함-;상기 가축관리서버가 상기 환경정보를 기반으로, 상기 분만객체가 기 설정된 계절에 기 설정된 날씨 및 기 설정된 시간대에 상기 신규객체를 분만한 경우, 상기 신규객체의 체온을 지속적으로 모니터링하는 단계;상기 가축관리서버가 상기 모니터링의 결과 상기 신규객체의 체온이 기 설정된 온도 이하인 저체온일 경우에, 상기 신규객체가 저체온임을 알리는 알림 메시지를 상기 관리자 단말기로 전송하는 단계; 및상기 가축관리서버가 상기 모니터링의 결과 상기 신규객체의 체온이 상기 저체온일 경우에, 상기 축사의 내부 기온을 기 설정된 온도로 상승시키며 상기 축사의 조명을 기 설정된 밝기로 밝게 하도록 하는 신호를 생성하여 축사 제어 장치로 전송하는 단계;를 포함하고,상기 승가상황정보를 예측하는 단계는,상기 가축관리서버가 상기 승가상황정보를 실시간으로 업데이트하여 상기 관리자 단말기에게 실시간으로 전송하는 단계-상기 승가상황정보는 발정 전의 객체 수, 발정 예상 시간, 발정 예상 객체 수 및 공태 예상 기간을 포함함-; 및상기 가축관리서버가 상기 승가증상으로 판단된 경우, 상기 승가상황정보를 이용하여 승가 객체와 승가가 예상되는 객체가 합방되도록 하는 신호를 생성하여 상기 축사 제어 장치로 전송하는 단계;를 포함하는, 스마트 가축 관리 방법.축사의 상황을 제어하고, 상기 축사에 위치하는 가축들을 촬영한 가축영상데이터를 실시간으로 획득하는 축사제어장치; 및상기 가축영상데이터에 포함된 상기 가축들을 개별 객체로 각각 분리하고, 상기 가축영상데이터로부터 상기 개별 객체의 객체체온정보 및 객체행동정보가 포함된 객체정보를 추출하고, 표준축사관리데이터를 기초로 상기 추출된 객체정보를 분석하여 상기 가축의 이상징후여부를 판단한 판단결과데이터를 생성하고, 상기 생성된 판단결과데이터를 관리자 단말기로 전송하는 가축관리서버;를 포함하고,상기 표준축사관리데이터는, 상기 가축영상데이터로부터 이상징후여부가 발생되지 않은 정상객체 및 상기 정상객체의 주변객체의 최고체온정보 및 최저체온정보를 반복 학습하여 생성된 객체기본온도정보와, 정상축사 및 상기 정상축사의 주변축사의 최고온도정보 및 최저온도정보를 반복 학습하여 생성된 축사기본온도정보, 및 상기 정상객체의 정상행동을 분석하여 생성된 객체기본행동정보를 포함하고,상기 가축관리서버는, 상기 표준축사관리데이터를 기초로 하여 딥러닝 기법을 이용하여 상기 가축의 이상징후여부 판단하고, 상기 이상징후여부를 질병증상, 분만증상 및 승가증상으로 각각 구분하고,상기 객체체온정보와 상기 표준축사관리데이터에 포함된 상기 객체기본온도정보 및 상기 객체행동정보와 상기 표준축사관리데이터에 포함된 상기 객체기본행동정보를 비교 분석하고,상기 비교 분석한 결과로 상기 이상징후여부가 상기 질병증상으로 판단된 경우 질병객체에 대한 상기 객체체온정보를 모니터링하여 질병확산경로를 예측하고, 상기 비교 분석한 결과로 상기 이상징후여부가 상기 분만증상으로 판단된 경우 분만객체에 대한 상기 객체행동정보를 모니터링하여 분만상황정보를 예측하며, 상기 비교 분석한 결과로 상기 이상징후여부가 상기 승가증상으로 판단된 경우 승가객체에 대한 상기 객체행동정보를 모니터링하여 승가상황정보를 예측하고,상기 질병확산경로를 예측 시에, 상기 질병객체의 체온을 측정하여 제1 객체온도정보를 획득하고 상기 질병객체의 주변객체의 체온을 측정하여 제2 객체온도정보를 획득하고, 상기 표준축사관리데이터에 포함된 상기 객체기본온도정보를 기초로하여 상기 제1 객체온도정보 및 제2 객체온도정보 간의 제1 온도차이를 산출하고,상기 분만상황정보를 예측 시에, 상기 분만객체의 분만 후에 환경정보를 고려하여 신규객체에 대한 객체체온정보 및 객체행동정보를 모니터링하여 이상징후가 발생한 경우 상기 관리자 단말기로 알림메시지를 전송하고-상기 환경정보는, 상기 분만객체 및 상기 축사 주변의 날씨정보, 계절정보 및 시간정보를 포함함-, 상기 환경정보를 기반으로 상기 분만객체가 기 설정된 계절에 기 설정된 날씨 및 기 설정된 시간대에 상기 신규객체를 분만한 경우 상기 신규객체의 체온을 지속적으로 모니터링하고, 상기 모니터링의 결과 상기 신규객체의 체온이 기 설정된 온도 이하인 저체온일 경우에 상기 신규객체가 저체온임을 알리는 알림 메시지를 상기 관리자 단말기로 전송하고, 상기 모니터링의 결과 상기 신규객체의 체온이 기 설정된 온도 이하인 저체온일 경우에 상기 축사의 내부 기온을 기 설정된 온도로 상승시키며 상기 축사의 조명을 기 설정된 밝기로 밝게 하도록 하는 신호를 생성하여 상기 축사 제어 장치로 전송하고,상기 승가상황정보를 예측 시에, 상기 승가상황정보를 실시간으로 업데이트하여 상기 관리자 단말기에게 실시간으로 전송하고-상기 승가상황정보는 발정 전의 객체 수, 발정 예상 시간, 발정 예상 객체 수 및 공태 예상 기간을 포함함-, 상기 승가증상으로 판단된 경우 상기 승가상황정보를 이용하여 승가 객체와 승가가 예상되는 객체가 합방되도록 하는 신호를 생성하여 상기 축사 제어 장치로 전송하는, 스마트 가축 관리 시스템., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

468/1150 Row 468: application_number: 1020200046714, combined_string: invention_title: 보리 새싹 급여를 통한 기능성 계란 생산 방법 및 상기 방법에 의하여 생산된 기능성 계란 abstract: 본 발명은 계란으로 이행성이 향상되도록 처리된 보리 새싹을 산란계에 급여하여 보리 새싹의 활성 성분이 증강된 기능성 계란, 구체적으로 면역력 증강 효과, 항염증 효과, 알코올성 지방간 예방 및 개선 효과에 우수한 사포나린(saponarin) 함량이 증대된 기능성 계란을 생산하는 방법 및 이와 같은 방법에 의해 생산된 계란에 관한 것으로서, 본 발명은 칡즙을 혼합한 후에 알파-아밀라제(α-amylase) 및 셀룰라제(cellulase)로 효소 처리한 후 사카로마이세스 크레비시아에(Saccharomyces cerevisiae)로 발효한 보리 새싹 분말을 포함하는 사료를 산란계에 섭취시키는 것을 특징으로 하는 보리 새싹 급여를 통한 기능성 계란 생산 방법을 제공한다. claims: 보리 새싹 분말과 칡즙을 혼합한 혼합물에 알파-아밀라제(α-amylase) 및 셀룰라제(cellulase)로 25 내지 65℃에서 2 내지 7시간 동안 효소 처리한 후 상기 효소 처리물을 사카로마이세스 크레비시아에(Saccharomyces cerevisiae)로 20 내지 40℃에서 10 내지 48시간 동안 발효한 보리 새싹 분말 사료를 산란계에 섭취시키는 것을 특징으로 하는 보리 새싹 분말 사료를 통한 사포나린 함량이 증대된 기능성 계란 생산 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

469/1150 Row 469: application_number: 1020200045748, combined_string: invention_title: 자주식 계사청소기 abstract: 본 발명은 자주식 계사청소기에 관한 것으로, 더욱 상세하게는 닭을 사육하는 계사(鷄舍)의 바닥에 쌓인 왕겨와 계분을 파쇄한 후 불필요한 계분만을 적재함에 수거한 후 배출하도록 한 것으로, 왕겨의 재사용 효율을 높여 유지 비용을 낮출 수 있고, 분리 수거된 계분은 거름으로 활용함으로써 농가의 수익을 높일 수 있고, 작업자가 직접 탑승하여 계사를 이동하면서 작업할 수 있어 대형계사는 물론 소형계사에서도 사용이 가능하고, 계사의 바닥을 파쇄하는 작업 공정에서는 파쇄부가 바닥에 맞닿도록 하강하고 이동 과정에서는 파쇄부를 바닥에 맞닿지 않도록 상승시키고 이때 작업자가 탑승한 좌석이 구비된 컨트롤러부의 수평도를 일정하게 유지함으로써 작업자의 피로도를 낮출 수 있고 사고를 예방할 수 있는 자주식 계사청소기에 관한 것으로, 이를 위해 본 발명은 계분 및 왕겨를 저장하는 저장공간이 형성된 적재함을 포함한 적재부; 상기 적재함의 일측에 배치되어 계사의 바닥으로부터 계분과 왕겨를 파쇄하고, 바닥에서 분리된 계분과 왕겨를 일방향으로 공급하는 파쇄부; 상기 파쇄부와 상기 적재함 사이에 배치되며 상기 파쇄부로부터 공급받은 계분과 왕겨를 상기 적재함으로 전달하는 이송부; 상기 적재함의 상단 개구부에 배치되어 상기 이송부로부터 전달된 계분을 분쇄함과 동시에 상기 저장공간에 저장되는 계분의 위치 및 높이를 정렬하는 레벨유지부; 상기 적재함의 내부 바닥면에 배치되어 상기 저장공간에 저장된 계분을 적재함의 외부로 배출하는 배출부; 상기 적재함의 하방에 배치되며 메인엔진 및 조향장치를 통해 제어되는 무빙부; 상기 이송부와 적재부 사이에 배치되어 상기 이송부를 승강시키는 승강부; 및 작업자가 탑승하는 좌석과 상기 무빙부의 동작을 제어하는 조향장치를 포함한 컨트롤부를 포함한다. claims: 계분 및 왕겨를 저장하는 저장공간(111)이 형성된 적재함(11)을 포함한 적재부(10);상기 적재함(11)의 일측에 배치되어 계사의 바닥으로부터 계분과 왕겨를 파쇄하고, 바닥에서 분리된 계분과 왕겨를 일방향으로 공급하는 파쇄부(20);상기 파쇄부(20)와 상기 적재함(11) 사이에 배치되며 상기 파쇄부(20)로부터 공급받은 계분과 왕겨를 상기 적재함(11)으로 전달하는 이송부(30);상기 적재함(11)의 상단 개구부에 배치되어 상기 이송부(30)로부터 전달된 계분을 분쇄함과 동시에 상기 저장공간(111)에 저장되는 계분의 위치 및 높이를 정렬하는 레벨유지부(40);상기 적재함(11)의 내부 바닥면에 배치되어 상기 저장공간(111)에 저장된 계분을 상기 적재함(11)의 외부로 배출하는 배출부(50);상기 적재함(11)의 하방에 배치되며 메인엔진 및 조향장치를 통해 제어되는 무빙부(60);상기 이송부(30)와 적재부(10) 사이에 배치되어 상기 이송부(30)를 승강시키는 승강부(70); 및작업자가 탑승하는 좌석(81)과 상기 무빙부(60)의 동작을 제어하는 조향장치(82)를 포함한 컨트롤부(80)를 포함한 것을 특징으로 하는 자주식 계사청소기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

470/1150 Row 470: application_number: 1020200045461, combined_string: invention_title: 수직방향 또는 수평방향으로 전환하여 조명하는 양계장 LED조명장치 abstract: 본 발명은 수직방향 또는 수평방향으로 전환하여 조명하는 양계장 LED조명장치에 관한 것이다. 더욱 상세하게는 다층구조의 사육케이지를 가지는 양계장 내부를 조명하기 위한 조명장치로서, 저층에 위치하는 케이지나 고층에 위치하는 케이지에 대하여 균일한 조도의 조명이 이루어 질 수 있도록 하기 위한 조명장치이다. 종래에는 천장에 수평방향으로 설치된 조명장치를 이용하여, 위에서 아래쪽을 향하여 빛을 비추는 방식으로 조명하다 보니, 고층에 위치하는 케이지는 너무 밝고, 저층에 위치하는 케이지에는 너무 어둡게 되므로, 케이지의 위치에 따라 닭들의 산란율이나 성장률 등이 달라지는 문제점이 있었다. 그러나 본 발명에 의하면 조명장치를 수직방향으로 위치하게 하여 저층이나 고층에 모두 균일한 조명을 제공할 수 있게 되고, 이에 따라 양계장 내 모든 닭들을 균일하게 성장시키고 산란율이 동일하게 할 수 있으면서도 청소, 계란수거 등 작업 시에는 작업공간을 충분히 형성할 수 있도록, 조명장치를 수평방향으로 전환하여 양계장 내부를 조명할 수 있게 된다. claims: 양계장의 내부를 조명하는 LED조명장치에 있어서,일정길이를 가지는 투명튜브, 상기 투명튜브의 내부를 따라 띠 형태로 삽입되는 LED기판 및 상기 LED기판의 양면에 부착되는 복수의 LED소자로 각각 이루어지는 LED조명튜브; 사육케이지 사이의 복도를 따라 천장에 일정간격으로 고정되는 고정 고리; 상기 복도를 따라 상기 고정 고리 각각을 통과하도록 설치되며, 일 단부는 상기 양계장의 일 측면에서 작업자가 조작 가능한 높이까지 내려지는 연동로프; 상기 LED조명튜브가 수직으로 세워진 상태에서, 상기 LED조명튜브의 상단부가 상기 천장에 고정되도록 하되, 상기 LED조명튜브의 상단부를 중심축으로 하여 회전할 수 있게 고정시키는 것이 가능한 천장고정수단; 및일단이 상기 LED조명튜브의 하단부에 고정되고, 타단은 상기 연동로프에 연결되는 당김로프; 를 포함하되, 상기 LED조명튜브는, 상기 복도를 따라 상기 천장에 일정간격으로 고정되는 것을 특징으로 하는, 수직방향 또는 수평방향으로 전환하여 조명하는 양계장 LED조명장치. 양계장의 내부를 조명하는 LED조명장치에 있어서, 일정길이를 가지는 투명튜브, 상기 투명튜브의 내부를 따라 띠 형태로 삽입되는 LED기판 및 상기 LED기판의 양면에 부착되는 복수의 LED소자로 이루어지는 LED조명튜브; 사육케이지 사이의 복도를 따라 천장에 부착되는 가이드 레일; 상기 가이드 레일을 따라 이동 가능하도록, 상기 가이드 레일에 결합되는 복수개의 캐리어; 상기 복도를 따라 상기 복수개의 캐리어 각각에 연결되도록 설치되며, 일 단부는 상기 양계장의 일 측면에서 작업자가 조작 가능한 높이까지 내려지는 연동로프; 상기 LED조명튜브가 수직으로 세워진 상태에서, 상기 LED조명튜브의 상단부가 상기 천장에 고정되도록 하되, 상기 LED조명튜브의 상단부를 중심축으로 하여 회전할 수 있게 고정시키는 것이 가능한 천장고정수단; 및일단이 상기 LED조명튜브의 하단부에 고정되고, 타단은 상기 연동로프에 연결되는 당김로프; 를 포함하되, 상기 LED조명튜브는, 상기 복도를 따라 상기 천장에 일정 간격으로 고정되는 것을 특징으로 하는, 수직방향 또는 수평방향으로 전환하여 조명하는 양계장 LED조명장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

471/1150 Row 471: application_number: 1020200042561, combined_string: invention_title: 자동 닭사육장 abstract: 내부에 일정한 공간을 형성한 축사(10)와; 상기 축사(10)의 외면에 또는 상기 축사(10)의 외부에 설치되고, 태양광 발전이 가능한 태양광모듈(20)로서, 상기 태양광모듈(20)에 전기적으로 연결되어 제어명령을 송신할 수 있는 제어부(60)와; 상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 벨 소리를 자동으로 낼 수 있는 자동경보부와; 상기 제어부(60) 및 상기 자동경보부에 연결되어 상기 벨 소리에 연동하여 상기 축사(10)의 전면에 설치된 출입용 도어(70)를 자동으로 개폐할 수 있는 자동개폐부; 및 상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 자동으로 모이 및 물을 공급할 수 있는 자동급이부를 포함하는 것을 특징으로 하는 자동 닭사육장에 관한 것이다. claims: 내부에 일정한 공간을 형성한 축사(10);상기 축사(10)의 외면에 또는 상기 축사(10)의 외부에 설치되고, 태양광 발전이 가능한 태양광모듈(20);상기 태양광모듈(20)에 전기적으로 연결되어 제어명령을 송신할 수 있는 제어부(60);상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 벨 소리를 자동으로 낼 수 있는 자동경보부;상기 제어부(60) 및 상기 자동경보부에 연결되어 상기 벨 소리에 연동하여 상기 축사(10)의 전면에 설치된 출입용 도어(70)를 자동으로 개폐할 수 있는 자동개폐부; 및상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 자동으로 모이 및 물을 공급할 수 있는 자동급이부를 포함하고,상기 자동개폐부는,상기 축사(10)의 전면(11) 중 출입구의 상측에 설치되고 회전축을 가지는 모터(41);상기 모터(41)의 회전축에 연결된 제1 스크류(42);상기 제1 스크류(42)에 나합하고 있는 제2 스크류(43);상기 제2 스크류(43)에 'ㅁ'자형 연결부(44)를 통해 연결된 이동부(40); 및상기 이동부(40)의 상하 이동을 안내하는 안내관(45)을 포함하고,상기 출입용 도어(70)가 삽입관(70h)를 상측 내부에 형성하고, 상기 삽입관(70h)을 통해 상기 'ㅁ'자형 연결부(44)의 하측에 결합되어 상기 이동부(40)의 상하 이동에 따라 상하로 이동할 수 있는 것을 특징으로 하는 자동 닭사육장.내부에 일정한 공간을 형성한 축사(10);상기 축사(10)의 외면에 또는 상기 축사(10)의 외부에 설치되고, 태양광 발전이 가능한 태양광모듈(20);상기 태양광모듈(20)에 전기적으로 연결되어 제어명령을 송신할 수 있는 제어부(60);상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 벨 소리를 자동으로 낼 수 있는 자동경보부;상기 제어부(60) 및 상기 자동경보부에 연결되어 상기 벨 소리에 연동하여 상기 축사(10)의 전면에 설치된 출입용 도어(70)를 자동으로 개폐할 수 있는 자동개폐부; 및상기 제어부(60)에 연결된 제1 타이머에 의해 미리 설정된 시간에 자동으로 모이 및 물을 공급할 수 있는 자동급이부를 포함하고,상기 자동개폐부는,상기 축사(10)의 전면(11) 중 출입구의 상측에 설치되고 회전축을 가지는 모터(41');상기 모터(41')의 회전축에 연결된 회전봉(81);상기 회전봉(81)에 연결된 도르래(80); 및상기 도르래(80)에 와인딩 및 언와인딩될 수 있고, 출입용 도어(70')의 상단부에 인접한 부분에 연결된 로프(82)를 포함하고,상기 출입용 도어(70')가 상기 로프(82)의 와인딩 및 언와인딩에 따라 출입구에 인접하는 축사의 부분 중 좌측 및 우측 부분의 하측에 연결된 힌지(85)를 중심으로 여닫이식으로 회전하여 상기 축사(10)의 출입구를 개폐할 수 있는 것을 특징으로 하는 자동 닭사육장., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

472/1150 Row 472: application_number: 1020200040822, combined_string: invention_title: 친환경 방목닭 잡초제거 농법 및 그 잡초제거 농법을 이용한 친환경 방목닭 사육방법 abstract: 본 발명은 친환경 방목닭 잡초제거 농법 및 그 잡초제거 농법을 이용한 친환경 방목닭 사육방법에 관한 것으로 과수의 성장에 해를 끼치지 않을 범위 내의 규격으로 방목케이지를 형성하여 닭의 잡초제거 작업영역을 지정하고, 그 작업영역 내의 잡초만을 제거하면서 방목되도록 하며, 그 작업영역의 작업이 완료되면 다음 작업영역으로 이동하여 방목 및 잡초제거가 효율적이면서 지속적으로 진행될 수 있도록 함과 아울러, 닭이 낯에는 방목케이지에서 잡초와 벌레 등을 먹고, 아침 및 저녁에는 닭사육장에서 사료와 동종수액(음용수)을 취하며 휴식토록 함으로써 품질이 우수한 친환경 방목닭을 사육할 수 있도록 하기 위하여, 과수원 내 과수 사이에 성장한 잡초(9)를 제거하기 위해 일정범위 내의 규격으로 이동형 방목케이지(A)를 마련하되, 상기 방목케이지(A)는 높이를 갖는 측방 폐쇄 형태로 하부틀프레임(10)을 형성하고, 상기 하부틀프레임(10)의 상부측으로 다수의 지지파이프(20)를 고정 연결하고 난 다음, 상기 다수 지지파이프(20)의 외면을 보호망체(25)로 씌워 상기 보호망체(25)의 내측으로 닭(8)이 수용되는 방목공간부(92)를 형성하며, 상기 보호망체(25) 상에 작업자가 출입하도록 출입문(40)을 형성하여 이루어지게 하고, 상기 하부틀프레임(10)을 지면(2)에서 함몰 형성된 설치홈(3) 내에 삽입안착되도록 하여 하부틀프레임(10)의 하부측을 통해 방목공간부(92)로 유해동물의 침입을 방지하도록 하며, 상기 방목공간부(92) 내에 닭(8)을 방목하여 방목케이지(A) 내의 잡초(9)를 일정 시간동안 제거토록 한 다음 방목케이지(A)를 주변 다른구역으로 이동시켜 가며 과수원 내의 잡초(9)를 제거하도록 함을 포함하여 이루어지는 것을 특징으로 한다. claims: 과수원 내 과수 사이에 성장한 잡초(9)를 제거하기 위해 일정범위 내의 규격으로 이동형 방목케이지(A)를 마련하되,상기 방목케이지(A)는 높이를 갖는 측방 폐쇄 형태로 하부틀프레임(10)을 형성하고, 상기 하부틀프레임(10)의 상부측으로 다수의 지지파이프(20)를 고정 연결하고 난 다음, 상기 다수 지지파이프(20)의 외면을 보호망체(25)로 씌워 상기 보호망체(25)의 내측으로 닭(8)이 수용되는 방목공간부(92)를 형성하며, 상기 보호망체(25) 상에 작업자가 출입하도록 출입문(40)을 형성하여 이루어지게 하고,상기 하부틀프레임(10)을 지면(2)에서 함몰 형성된 설치홈(3) 내에 삽입안착되도록 하여 하부틀프레임(10)의 하부측을 통해 방목공간부(92)로 유해동물의 침입을 방지하도록 하며,상기 방목공간부(92) 내에 닭(8)을 방목하여 방목케이지(A) 내의 잡초(9)를 일정 시간동안 제거토록 한 다음 방목케이지(A)를 주변 다른구역으로 이동시켜 가며 과수원 내의 잡초(9)를 제거하도록 함을 포함하여 이루어지는 것을 특징으로 하는 친환경 방목닭 잡초제거 농법.과수원 내 과수 사이에 성장한 잡초(9)를 제거하기 위해 일정범위 내의 규격으로 이동형 방목케이지(A)를 마련하며, 상기 방목케이지(A)는 높이를 갖는 측방 폐쇄 형태로 하부틀프레임(10)을 형성하되 상기 하부틀프레임(10)은 직선바 형태의 전방하부틀(11), 후방하부틀(12) 및 양측방하부틀(13,14)로 구비되어 직사각 형태로 형성되게 하며, 상기 하부틀프레임(10)의 상부측으로 다수의 지지파이프(20)를 고정 연결하되 상기 지지파이프(20)를 “∩”형태로 형성하고, 전방하부틀(11)과 후방하부틀(12) 사이에 다수의 지지파이프(20)를 일정간격 설치하여 방목케이지(A)가 터널형으로 형성한 다음, 상기 다수 지지파이프(20)의 외면을 보호망체(25)로 씌워 상기 보호망체(25)의 내측으로 닭(8)이 수용되는 방목공간부(92)를 형성하며, 상기 보호망체(25) 상에 작업자가 출입하도록 출입문(40)을 형성하여 이루어지게 하고, 상기 하부틀프레임(10)을 지면(2)에서 함몰 형성된 설치홈(3) 내에 삽입안착되도록 하여 하부틀프레임(10)의 하부측을 통해 방목공간부(92)로 유해동물의 침입을 방지하도록 하며,상기 방목케이지(A)의 일측편에 작업자의 출입문(40)을 형성하며, 상기 방목케이지(A)의 타측편에 닭(8)의 출입을 위한 제1출입문(94)을 형성하고, 방목케이지(A)의 인근에 마련된 닭사육장(60)의 측벽(62)에 제2출입문(65)을 형성하며, 상기 제1출입문(94)과 제2출입문(65) 사이에 통로망(70)을 연결 설치하여, 아침 및 저녁에는 닭(8)이 닭사육장(60) 내에 머무르게 하고, 낯에는 상기 통로망(70)을 통해 닭사육장(60)에서 방목케이지(A)로 이동하여 잡초(9)를 제거토록 하되,상기 닭사육장(60) 내에 사료가 수직 충진되는 충진파이프(112)와, 상기 충진파이프(12)에 직교 연장되어 단부에 사료가 노출되는 공급파이프(114)로 된 사료자동급여기(110)를 마련하고,상기 닭사육장(60) 및 방목케이지(A) 내에 동종수액을 생성하는 동종수액추출기(132)와, 상기 동종수액추출기(132)로부터 동종수액을 공급받아 닭사육장(60) 내로 이동시키는 이동관(134)과, 상기 이동관(134) 상에 다수 연결되어 닭(8)에게 동종수액을 공급하는 노즐(136)로 된 동종수액자동급여기(130)를 마련하여,상기 닭(8)이 낮에는 방목케이지(A) 내에서 잡초(9)와 벌레를 먹으면서 사육되고, 아침 및 저녁에는 닭사육장(60) 내에서 사료자동급여기(110) 및 동종수액자동급여기(130)를 통해 사료와 동종수액을 취하며 휴식토록 함으로써 품질이 우수한 친환경 방목닭을 사육할 수 있도록 함을 특징으로 하는 친환경 방목닭 잡초제거 농법을 이용한 친환경 방목닭 사육방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

473/1150 Row 473: application_number: 1020200038172, combined_string: invention_title: 양계장의 양계활동공간영역의 공기정화장치 abstract: 본 발명은 양계장의 양계활동공간영역의 공기장화장치에 관한 것으로 양계장의 바닥양계에 있어서, 양계활동공간영역 (바닥에서 대략 큰 닭의 키에 상응한 높이의 공간)을 청정공간으로 유지하기 위하여, 양계장의 공기를 정화하는 공기정화부(air purity portion)와; 공기정화장치의 유로(流路)에 공기의 유동성을 부여하는 공기 액추에이트부(air actuate portion)와; 정화된 공기를 양계장 바닥의 평면상에 균일한 분포로 양계의 호흡에 유효한 공간으로 분사하는 공기공급부(air supply portion)를; 포함하여 구성된 것이다.본 발명에 의하면, 양계장 바닥에 설치된 상기 공기정화장치의 공기 액추에이트부의 가동에 따라 상기 공기정화부가 부압으로 되면서 주위의 공기가 흡입되어 세균이 포함된 먼지 등이 제거되고 정화된 공기는 상기 공기공급부에 의해 양계장 바닥의 평면상에 균일한 분포로 분사된다. 따라서 양계활동공간영역이 청정하게 유지되어 병아리의 폐사율이 저감되고 양계가 보다 위생적인 환경에서 건강하고 빠르게 성장할 수 있으며, 공조시설비의 절감 및 양계수익을 보다 높일 수 있다. claims: 양계장의 바닥양계에 있어서, 양계활동공간영역을 청정하기 위하여, 공기의 정화기능을 가진 공기정화부와, 공기정화장치의 유로(流路)에 공기의 유동성을 부여하는 공기 액추에이트부와, 정화된 공기를 평면의 균일한 분포로 분사기능을 가진 공기공급부를 포함하여 구성된 것을 특징으로 하는 양계장의 양계활동공간영역의 공기장화장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

474/1150 Row 474: application_number: 1020200035451, combined_string: invention_title: 루테인 및 제아잔틴의 함량이 증대된 계란 생산방법, 이로부터 생산된 계란, 및 상기 계란으로부터 난황유 또는 난황 분말을 제조하는 방법 abstract: 본 발명은 루테인 및 제아잔틴의 함량이 증대된 계란 생산방법, 이로부터 생산된 계란, 상기 계란으로부터 난황유 또는 난황 분말을 얻는 방법에 관한 것으로서, 본 발명에 따른 루테인 및 제아잔틴의 함량이 증대된 계란의 생산방법은 일반적인 계란보다 루테인 및 제아잔틴의 함유량이 2.5 내지 4배 가량 높은 계란을 생산할 수 있으며, 제조된 계란의 색과 맛이 우수하여 소비자의 기호도가 높으면서도 건강에 이로운 건강 기능식품을 제공할 수 있다. 또한, 본 발명에 따르면 상기 계란으로부터 루테인 및 제아잔틴의 함량이 높은 난황유 및 난황 분말을 제조함으로써 눈 건강에 유익한, 특히 황반변성을 개선할 수 있는 다양한 기능성 식품에 적용될 수 있을 뿐만 아니라, 저장안정성과 맛이 우수한 식품을 제공할 수 있다. claims: 루테인 및 제아잔틴을 함유하는 미세조류를 1.5 내지 5중량% 포함하는 사료 또는 사료 첨가제를 산란계에 급여하여 계란을 수득하는 단계를 포함하는, 루테인 및 제아잔틴의 함량이 증대된 계란의 생산방법.제 1 항 내지 제 4 항 중 어느 한 항의 방법으로 생산된, 루테인 및 제아잔틴의 함량이 증대된 계란.다음의 단계를 포함하는, 루테인 및 제아잔틴의 함량이 증대된 난황유의 제조방법:(a) 제 5 항에 따른 계란으로부터 난황을 분리하는 단계; (b) 상기 난황에 유기 용매를 첨가하고 교반하는 단계; (c) 상기 혼합물을 원심분리하여 상층액을 분리하는 단계; 및 (d) 상기 상층액으로부터 용매를 증발시켜 난황유를 얻는 단계.제 6 항에 있어서,상기 유기 용매가 에탄올인 것을 특징으로 하는, 루테인 및 제아잔틴의 함량이 증대된 난황유의 제조방법.제 6 항에 있어서,상기 (c) 단계 이후에,침전물의 색이 무색이 될 때까지 상기 (b) 단계 및 (c) 단계를 반복하는 것을 특징으로 하는, 루테인 및 제아잔틴의 함량이 증대된 난황유의 제조방법.제 6 항에 따른 방법으로 제조된, 루테인 및 제아잔틴의 함량이 증대된 난황유.다음의 단계를 포함하는 루테인 및 제아잔틴의 함량이 증대된 난황 분말의 제조방법: (a) 제 5 항에 따른 계란으로부터 난황을 분리하는 단계; (b) 난황을 균질화하는 단계; 및 (c) 난황을 젤라틴, 젖당, 포도당, 전분, 변성전분, 전분 분해물, 아라비아 검, 트라간트 고무, 덱스트린, 말토덱스트린, 콜라겐, 카세인, 난백 알부민, 알긴산나트륨, 탈지분유, 전유, 대두 단백질, 두유, 카카오 유지, 코코넛 유지, 동물유, 식물추출 엑기스, 메틸셀룰로오스 및 카르복시메틸셀룰로오스로 구성된 군에서 선택된 1종 이상의 부형제와 혼합한 후, 품온을 35 내지 45℃로 유지하면서 분무 건조하는 단계.제 10 항에 있어서,상기 부형제가 젤라틴, 젖당, 인산이전분, 아라비아 검 및 말토덱스트린의 혼합물인 것을 특징으로 하는, 루테인 및 제아잔틴의 함량이 증대된 난황 분말의 제조방법.제 10 항에 따른 방법으로 제조된, 루테인 및 제아잔틴의 함량이 증대된 난황 분말.제 13 항에 따른 난황 분말을 포함하는, 식품 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

475/1150 Row 475: application_number: 1020200028806, combined_string: invention_title: 도라지 박을 이용한 카로티노이드 및 비타민 B군 함량이 높은 기능성 계란 생산 방법 abstract: 본 발명은 착즙하고 남은 도라지 박 건조 분말을 포함하는 사료를 산란계에 섭취시켜 카로티노이드 및 비타민 B군 함량이 높은 기능성 계란 생산 방법 및 이에 의해 생산된 계란에 관한 것으로서, 본 발명에 의해 생산된 계란을 섭취하게 되면, 항산화 효과 및 항암 효과가 보고되고 있고, 피부암을 감소시키거나 폐암의 위험도를 줄이는 작용을 보일 수 있으며, 혈중 HDL 콜레스테롤 수치를 높게 만들어 혈중 지방 성분을 몸 밖으로 배출시키고 혈관을 깨끗하게 만드는 것은 물론, 동맥경화를 일으키는 물질을 간으로 이동시켜 혈관과 심장을 보호하는 역할을 한다. claims: 착즙하고 남은 도라지 박 건조 분말을 포함하는 사료를 산란계에 섭취시켜 카로티노이드 및 비타민 B군 함량이 향상된 기능성 계란 생산 방법.전술한 제 1항의 방법에 의하여 생산된 것을 특징으로 하는 카로티노이드 및 비타민 B군 함량이 향상된 기능성 계란., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

476/1150 Row 476: application_number: 1020200021123, combined_string: invention_title: ICT 융복합 축산환경 관제시스템 abstract: 개시되는 ICT 융복합 축산환경 관제시스템은, 복수의 축산농가에 각각 설치되는 도징 시스템;으로서, 외부로부터 가축에게 물을 공급하는 펌프;와, 상기 펌프에 의해 공급되는 물의 유량을 감지하는 유량센서;와, 상기 유량센서에 의해 감지된 유량정보에 따라 설정된 비율로 액상 사료첨가제를 공급하는 도징유닛;을 포함하는 도징 시스템; 상기 가축이 배출하는 분뇨 또는 가스로부터 악취를 측정하여 상기 악취정보를 생성하는 악취 측정부; 상기 도징유닛 및 상기 악취 측정부와 통신 가능하게 구비되며, 상기 축산농가 식별정보, 상기 설정된 비율, 누적음수량(L), 순시음 수량(L/hr), 누적 액상 사료첨가제 급이량(L), 도징유닛의 상태(RUN, STOP, ALARM)에 관한 정보를 포함하는 도징 시스템 정보 및 상기 악취정보를 포함하는 악취 측정부 정보를 수집하는 감시정보 수집부; 인터넷에 연결되어 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 송신하는 통신부; 상기 통신부로부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전달받아 저장하는 클라우드 서버; 및 상기 축산농가의 관리자가 인터넷을 통해 상기 클라우드 서버에 접근 가능하게 구비되는 관리자단말;을 포함한다. claims: 복수의 축산농가에 각각 설치되는 도징 시스템;으로서, 외부로부터 가축에게 물을 공급하는 펌프;와, 상기 펌프에 의해 공급되는 물의 유량을 감지하는 유량센서;와, 상기 유량센서에 의해 감지된 유량정보에 따라 설정된 비율로 액상 사료첨가제를 공급하는 도징유닛;을 포함하는 도징 시스템;상기 가축이 배출하는 분뇨 또는 가스로부터 악취를 측정하여 악취정보를 생성하는 악취 측정부;상기 도징유닛 및 상기 악취 측정부와 통신 가능하게 구비되며, 축산농가 식별정보, 상기 설정된 비율, 누적음수량(L), 순시음 수량(L/hr), 누적 액상 사료첨가제 급이량(L), 도징유닛의 상태(RUN, STOP, ALARM)에 관한 정보를 포함하는 도징 시스템 정보 및 상기 악취정보를 포함하는 악취 측정부 정보를 수집하는 감시정보 수집부;인터넷에 연결되고, 상기 감시정보 수집부와 통신가능하도록 연결되어 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 송신하는 통신부;인터넷을 통하여 상기 통신부로부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전달받아 저장하는 클라우드 서버;상기 축산농가의 관리자가 인터넷을 통해 상기 클라우드 서버에 접근 가능하게 구비되는 관리자단말;상기 클라우드 서버로 부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전송받고, 상기 악취정보를 포함하는 사육정보에 따라 상기 설정된 비율을 설정, 변경 또는 갱신하는 관제부;상기 액상 사료첨가제가 수용되고 상기 도징유닛을 통하여 상기 펌프와 배관 연결되며, 상기 액상 사료첨가제의 잔량 정보를 측정하는 수위 감지센서를 구비한 첨가제 수용용기; 및상기 펌프의 온도를 감지하는 온도센서를 포함하고, 상기 관리자가, 상기 관리자단말을 이용하여 상기 가축이 배설하는 분뇨를 수거하는 분뇨수거 주기 및 악취제거제 사용 여부를 포함하는 축사관리정보;와 상기 가축의 축종과 사육두수 및 상기 가축의 사양단계를 포함하는 가축정보; 및 상기 가축에 급이되는 사료의 종류 및 급이량을 포함하는 급이정보를 상기 클라우드 서버에 입력하고,상기 사육정보는 상기 축사관리정보와, 상기 가축정보 및 상기 급이정보를 더 포함하고 상기 관제부는, 상기 악취정보와, 상기 축사관리정보와, 상기 급이정보, 및 상기 가축정보를 기반으로하여, 상기 악취정보와 상기 액상 사료첨가제의 공급량 사이의 상관관계를 도출하고, 도출된 상기 상관관계에 따라 상기 설정된 비율을 설정하거나, 변경 또는 개정하고, 상기 가축이 배출하는 분뇨에서 배출되는 악취의 정도를 분석하고, 비정형 데이터 및 정형 데이터를 모두 포함하는 상기 사육정보를 데이터 마이닝 기법을 이용한 빅데이터 분석하여 상기 상관관계를 도출하고,상기 감시정보 수집부는,상기 액상 사료첨가제의 잔량 정보 및 상기 도징유닛의 온도 정보를 더 포함하는 상기 도징 시스템 정보를 생성하고,상기 도징유닛은,설정된 비율 정보를 입력받아 상기 펌프의 동작을 제어하는 제어부를 더 포함하는 ICT 융복합 축산환경 관제시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

477/1150 Row 477: application_number: 1020200017179, combined_string: invention_title: 배출모듈이 구비된 자주식 계사청소기 abstract: 본 발명은 배출모듈이 구비된 자주식 계사청소기에 관한 것으로, 보다 상세하게는 닭을 사육하는 계사(鷄舍)의 바닥에 쌓인 왕겨와 계분을 파쇄한 후 계분만을 분리하여 적재함에 수거 후 배출함으로써, 왕겨의 재사용을 통해 유지비용을 절감할 수 있고, 분리 수거된 계분은 거름으로 재활용할 수 있고, 자주식(自走式)으로 구성되어 대형계사는 물론 소형계사에서도 사용이 가능하며, 수거된 계분을 별도의 수거용 장비로 공급하기 위하여 적재함의 높이 및 각도를 조절하는 배출모듈이 구비되어 배출의 용이성을 향상시킨 배출모듈이 구비된 자주식 계사청소기에 관한 것으로, 본 발명은, 몸체프레임; 상기 몸체프레임의 일측에 승강 가능하게 배치되어 계사의 바닥에 쌓인 왕겨와 계분을 파쇄하고, 파쇄된 왕겨와 계분을 일방향으로 공급하는 수거부; 상기 수거부로부터 공급된 왕겨와 계분을 상방으로 이송하되, 이송 중 상대적으로 크기가 작은 왕겨는 하방으로 낙하하도록 다공성으로 이루어진 이송블레이드가 구비된 승강부; 상기 몸체프레임에 결합되고, 상기 승강부로부터 이송된 계분이 투입되도록 상부가 개구되어 형성된 적재함과, 상기 적재함의 개구된 상단에 배치되어 투입되는 계분의 위치 및 높이를 정렬하는 레벨유지수단을 포함한 적재부; 상기 적재함의 바닥에 배치되어 계분을 상기 적재함의 일측단에 형성된 배출공을 통해 배출하도록 이송하는 배출블레이드를 포함한 배출부; 상기 몸체프레임의 하방에 배치되어 메인엔진 및 조향장치를 통해 구동되는 트랙부; 상기 수거부의 각도를 조절하는 각도조절부; 및 상기 트랙부와 상기 적재부 사이에 배치되어 상기 적재함의 높이 및 경사 각도를 조절하는 배출모듈;을 포함하되, 상기 배출모듈은, 상기 적재함이 안치되는 안치프레임과, 상기 안치프레임을 수평방향으로 이동시키는 수평리프트과, 상기 안치프레임을 승강시키기 위한 승강리프트를 포함한다. claims: 몸체프레임(10);상기 몸체프레임(10)의 일측에 승강 가능하게 배치되어 계사의 바닥에 쌓인 왕겨와 계분을 파쇄하고, 파쇄된 왕겨와 계분을 일방향으로 공급하는 수거부(20);상기 수거부(20)로부터 공급된 왕겨와 계분을 상방으로 이송하되, 이송 중 상대적으로 크기가 작은 왕겨는 하방으로 낙하하도록 다공성으로 이루어진 이송블레이드(22)가 구비된 승강부(30);상기 몸체프레임(10)에 결합되고, 상기 승강부(30)로부터 이송된 계분이 투입되도록 상부가 개구되어 형성된 적재함(41)과, 상기 적재함(41)의 개구된 상단에 배치되어 투입되는 계분의 위치 및 높이를 정렬하는 레벨유지수단(42)을 포함한 적재부(40);상기 적재함(41)의 바닥에 배치되어 계분을 상기 적재함(41)의 일측단에 형성된 배출공(412)을 통해 배출하도록 이송하는 배출블레이드(52)를 포함한 배출부(50);상기 몸체프레임(10)의 하방에 배치되어 메인엔진 및 조향장치(WL)를 통해 구동되는 트랙부(60);상기 수거부(20)의 각도를 조절하는 각도조절부(70); 및상기 트랙부(60)와 상기 적재부(40) 사이에 배치되어 상기 적재함(41)의 위치 및 높이를 조절하는 배출모듈(80);을 포함하되,상기 배출모듈(80)은,상기 적재함(41)이 안치되는 안치프레임(81)과,상기 안치프레임(81)을 수평방향으로 이동시키는 수평리프트(82)와,상기 안치프레임(81)을 승강시키기 위한 승강리프트(83)를 포함한 것을 특징으로 하는 배출모듈이 구비된 자주식 계사청소기.몸체프레임(10);상기 몸체프레임(10)의 일측에 승강 가능하게 배치되어 계사의 바닥에 쌓인 왕겨와 계분을 파쇄하고, 파쇄된 왕겨와 계분을 일방향으로 공급하는 수거부(20);상기 수거부(20)로부터 공급된 왕겨와 계분을 상방으로 이송하되, 이송 중 상대적으로 크기가 작은 왕겨는 하방으로 낙하하도록 다공성으로 이루어진 이송블레이드(22)가 구비된 승강부(30);상기 몸체프레임(10)에 결합되고, 상기 승강부(30)로부터 이송된 계분이 투입되도록 상부가 개구되어 형성된 적재함(41)과, 상기 적재함(41)의 개구된 상단에 배치되어 투입되는 계분의 위치 및 높이를 정렬하는 레벨유지수단(42)을 포함한 적재부(40);상기 몸체프레임(10)의 하방에 배치되어 메인엔진 및 조향장치(WL)를 통해 구동되는 트랙부(60);상기 수거부(20)의 각도를 조절하는 각도조절부(70); 및상기 트랙부(60)와 상기 적재부(40) 사이에 배치되어 상기 적재함(41)의 위치 및 경사 각도를 조절하는 배출모듈(80);을 포함하되,상기 배출모듈(80)은,상기 적재함(41)이 안치되는 안치프레임(81)과,상기 적재함(41)의 배출각도를 조절하기 위한 배출각도 조절수단(84)을 포함한 것을 특징으로 하는 배출모듈이 구비된 자주식 계사청소기., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

478/1150 Row 478: application_number: 1020200015153, combined_string: invention_title: 스마트 닭 모이통 abstract: 본 발명은 스마트 닭모이통에 관한 것으로서, 대용량 닭 사료가 충진되는 사료 공급통; 사료 공급통의 출구를 조도센서 신호에 따라 자동 개폐하는 자동개폐장치; 상기 사료 공급통의 하부에 이격 설치되어 적정량의 사료가 채워지도록 된 급이통; 상기 급이통의 내부에 설치되어 사료의 유무를 센싱하는 사료감지부; 상기 사료감지부의 신호를 받아 자동개폐장치를 작동하는 제어모듈; 상기 제어모듈 및 자동개폐장치에 전원을 공급하는 전원공급부; 및 상기 급이통과 사료 공급통 사이를 이격시켜 고정하는 거치대;를 포함하는 것을 특징으로 한다. claims: 대용량 닭 사료가 충진되는 사료 공급통(110);사료 공급통(110)의 출구를 조도센서(143) 신호에 따라 자동 개폐하는 자동개폐장치(120);상기 사료 공급통(110)의 하부에 이격 설치되어 적정량의 사료가 채워지도록 된 급이통(130);상기 급이통(130)의 내부에 설치되어 사료의 유무를 센싱하는 사료감지부(140);상기 사료감지부(140)의 신호를 받아 자동개폐장치(120)를 작동하는 제어모듈(150);상기 제어모듈(150) 및 자동개폐장치(120)에 전원을 공급하는 전원공급부(160); 및상기 급이통(130)과 사료 공급통(110) 사이를 이격시켜 고정하는 거치대(170);를 포함하는 것을 특징으로 하는 스마트 닭모이통., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

479/1150 Row 479: application_number: 1020200014544, combined_string: invention_title: 계사 내 진드기 포획장치 저전력 제어시스템 abstract: 본 발명은 계사 내 진드기 포획장치 저전력 제어시스템에 관한 것이다. 이는, 진드기를 잡아 포획하는 포획층을 구비하고 계사에 배치되는 포획시트, 포획시트의 무게 및 온도변화를 감지하는 센서부, 센서부가 감지한 정보를 외부로 전송하는 RF모듈을 갖는 진드기포획장치를 제어하는 것으로서, 전력공급부에 접속되는 저전력모듈과; 저전력모듈을 통해 전력을 상시 전달받으며 설정시간마다 신호를 출력하는 신호출력부와; 전력공급부로부터 전달받은 전력을 상기 진드기포획장치로 공급하는 주전력모듈과; 신호출력부가 신호를 출력하는 동안에만 주전력모듈로 전력이 공급되게 하는 스위치를 구비한다.상기와 같이 이루어지는 본 발명의 계사 내 진드기 포획장치 저전력 제어시스템은, 진드기포획장치에 설치되어 있는 센서부와 RF모듈을 이용해 포획된 진드기의 개체수를 파악하되, 관리자에 의해 설정된 시간 간격으로 파악할 수 있어, 필요 없는 전력의 낭비를 유발하지 않아 경제적 부담 없이 운용이 가능하다. claims: 다공성 구조를 가지며 내부로 파고 들어온 진드기를 잡아 포획하는 포획층을 구비하고 계사에 배치되는 다수의 포획시트, 시간경과에 따른 포획시트의 무게 및 온도변화를 감지하는 센서부, 상기 센서부가 감지한 정보를 외부로 전송하는 RF모듈을 갖는 진드기포획장치를 제어하는 것으로서, 전력공급부와;상기 전력공급부에 접속되는 저전력모듈과;상기 저전력모듈을 통해 전력을 상시 전달받으며 설정시간마다 신호를 출력하는 신호출력부와;상기 전력공급부에 접속되고 전력공급부로부터 전달받은 전력을 상기 진드기포획장치로 공급하여 센서부와 RF모듈이 동작하게 하는 주전력모듈과;상기 전력공급부와 주전력모듈의 사이에 설치되며, 상기 신호출력부가 신호를 출력하는 동안에만 주전력모듈로 전력이 공급되게 하는 스위치와;상기 RF모듈을 통해 전달받은 진드기포획장치의 온도 및 무게변화 데이터를 관리자에게 전송하는 서버모듈을 구비하는 계사 내 진드기 포획장치 저전력 제어시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

480/1150 Row 480: application_number: 1020200011144, combined_string: invention_title: 벼신품종 슈퍼자미를 포함한 육계사료용 첨가제 및 이를 이용하여 생산한 육계 abstract: 본 발명은 슈퍼자미를 육계용 사료에 첨가한 육계용 사료를 개시하고 본 발명에 슈퍼자미를 기본사료에 10%이상을 첨가하여 사양하는 경우 무항생제 처방사육이 가능하고 조지방 함량이 낮고 조단백 함량이 높은 육계를 생산할 수 있는 뛰어난 효과가 있다. claims: 벼 신품종 슈퍼자미(Oryza sativa L. var. super C3GHi)가 포함된 육계사료용 첨가제.제1항의 벼 신품종 슈퍼자미(Oryza sativa L. var. super C3GHi)가 포함된 육계사료용 첨가제로 사육되어 조지방과 콜레스테롤 함량이 동시에 감소된 것이 특징인 육계., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

481/1150 Row 481: application_number: 1020200006680, combined_string: invention_title: 양계용 음용수 공급장치 abstract: 본 발명은 양계용 음용수 공급장치에 관한 것으로, 닭의 음용수가 공급되는 음용수 공급관; 음용수 공급관에 구비되어 공급되는 음용수를 열교환에 의해 냉수 또는 온수화하는 열교환모듈;을 포함하되, 열교환모듈은 음용수 공급관을 감싸 구비되는 열교환챔버; 열교환챔버에 연결되어 그 내부를 순환하는 냉매로서 음용수 공급관을 냉각 또는 가열하는 냉매순환관; 냉매순환관에 연결되어 냉매를 열교환시켜 냉매순환관으로 공급하는 열교환기; 열교환기에 구비되어 열교환기를 냉각 또는 가열시키는 열전소자; 냉매순환관에 구비되어 냉매를 순환 공급시키는 순환펌프;를 포함하는 음용수 공급장치를 제공한다. claims: 닭의 음용수가 공급되는 음용수 공급관; 음용수 공급관에 구비되어 공급되는 음용수를 열교환에 의해 냉수 또는 온수화하는 열교환모듈;을 포함하는 음용수 공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

482/1150 Row 482: application_number: 1020200002069, combined_string: invention_title: 에너지 공유를 통한 효율적 건조 시스템 및 공정 abstract: 본 발명은 에너지 공유를 통한 효율적 건조 시스템 및 고정에 관한 것으로써, 보다 상세하게는, 바이오매스를 연소시킬 때 발생하는 폐열 및 양계장에서의 닭의 체온을 이용하여 유기성 폐기물이 포함된 전구체를 건조시켜 이중으로 함수율을 감소시키고, 추가적인 에너지가 필요하지 않아 에너지를 절약할 수 있는 에너지 공유를 통한 효율적 건조 시스템 및 공정에 관한 것이다. claims: 유기성 폐기물을 이용하여 전기, 폐열 및 슬러리를 생산하는 혐기성 처리수단; 닭이 사육되는 하우스에서 발생되는 상기 닭의 체열을 방출하는 체열 공급부; 및 상기 혐기성 처리수단에서 생상되는 폐열과 상기 체열 공급부에서 방출되는 상기 닭의 체열을 이용하여 상기 슬러리가 포함된 전구체를 건조하고, 펠렛 비료를 생산하는 다단계 건조기;를 포함하는, 에너지 공유를 통한 효율적 건조 시스템. 유기성 폐기물을 가온시켜 바이오매스를 생산하는 단계; 상기 바이오매스를 생산하고 남은 상기 유기성 폐기물을 폐수 및 슬러리로 고액분리하는 단계; 열병합발전기에 상기 바이오매스를 투입한 후 연소하여 전기 및 폐열을 생산하는 단계; 상기 열병합발전기에서 생산된 폐열과 양계장 내부 닭의 체열을 다단계 건조기로 배출하는 단계; 및 상기 다단계 건조기에 상기 슬러리가 포함된 전구체를 공급하고, 상기 폐열 및 상기 체열로 상기 전구체를 건조시키는 단계;를 포함하는, 에너지 공유를 통한 효율적 건조 공정., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

483/1150 Row 483: application_number: 1020200000831, combined_string: invention_title: 백색 LED를 이용하여 육계의 생산성 및 면역력을 증가시키는 방법 abstract: 본 발명은 백색 LED를 이용하여 육계의 생산성 및 면역력을 증가시키는 방법에 관한 것으로, 기존의 형광등 또는 다른 파장대의 LED를 사용한 육계의 사육 방법에 비해 육계의 생산성 및 면역력 증진 효과가 우수하므로 육계를 포함한 가금류의 사육 효율을 높일 수 있다. claims: 육계의 사육시기에 따라 조도가 다른 백색 LED 광원을 조사하면서 육계를 사육하는 단계를 포함하는 것을 특징으로 하는 육계의 생산성 및 면역력을 증가시키는 방법.육계의 사육시기에 따라 조도가 다른 백색 LED 광원을 조사하면서 육계를 사육하는 단계를 포함하는 것을 특징으로 하는 생산성 및 면역력이 증가된 육계의 생산 방법.제5항의 방법에 의해 생산된 생산성 및 면역력이 증가된 육계., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

484/1150 Row 484: application_number: 1020190173894, combined_string: invention_title: 산란계 온습도지수 알림 시스템 abstract: 본 발명은 산란계 온습도지수(Temperature Humidity Index, THI) 알림 시스템에 관한 것으로, 본 발명에 따른 산란계 온습도지수 알림 시스템은, 오픈 API 방식의 기상 정보를 제공하는 기상 서버; 오픈 API 방식의 맵 데이터 정보를 제공하는 맵 서버; 및 기상 서버 및 맵 서버로부터 기상 정보 및 맵 데이터 정보를 수신하고 수신된 정보를 이용하여 사용자의 어플리케이션을 통해 온습도지수 정보를 제공하는 앱서버로 구성되고, 앱서버는기상 서버로부터 API를 통해 기상정보를 수신하는 기상정보 수신부; 맵서버로부터 API를 통해 맵정보 데이터를 수신하는 맵데이터 정보 수신부;기상정보 수신부로부터 수신된 기상정보를 어플리케이션에서 이용되는 형식으로 변환하고 분류하는 기상정보 분류부; 기상정보 분류부에서 분류된 기상자료에 기반하여 THI를 산출하기 위한 THI 산출부; 맵데이터 정보 수신부로부터 수신된 맵 데이터에 THI 산출부에서 계산된 THI 정보를 매칭시킨 THI 맵을 생성하기 위한 THI 맵 생성부; 및 THI 맵 생성부에서 생성된 THI 맵을 어플리케이션에서 요구되는 형식을 가진 송출용 THI 데이터로 변환하여 생성하는 송출용 THI 데이터 생성부를 포함하고,상기 THI 산출부는, 기상정보 분류부에서 분류된 기상자료에 기반하여 지역별 THI를 계산하는 지역기반 THI 산출부; 기상정보 분류부에서 분류된 기상자료에 기반하여 시간대별 THI를 계산하는 시간기반 THI 계산부; 및 외기온도에 따른 THI를 계산하는 외기온도기반 THI 산출부를 포함하고,상기 THI 산출부는 기상정보 분류부에서 분류된 기상자료에 기반하여 계사의 환기 형태에 따른 THI 값을 계산하도록 구성되고,THI 맵 생성부는 맵 데이터의 지역별 THI 맵과 함께, 계사의 형태에 따른 THI 값에 기반한 컬러 속성을 갖는 THI 맵을 생성하도록 구성된다. claims: 오픈 API 방식의 기상 정보를 제공하는 기상 서버; 오픈 API 방식의 맵 데이터 정보를 제공하는 맵 서버; 및 기상 서버 및 맵 서버로부터 기상 정보 및 맵 데이터 정보를 수신하고 수신된 정보를 이용하여 사용자의 어플리케이션을 통해 온습도지수 정보를 제공하는 앱서버를 포함하는 산란계 온습도지수 알림 시스템에 있어서,상기 앱서버는기상 서버로부터 API를 통해 기상정보를 수신하는 기상정보 수신부; 맵서버로부터 API를 통해 맵정보 데이터를 수신하는 맵데이터 정보 수신부;기상정보 수신부로부터 수신된 기상정보를 어플리케이션에서 이용되는 형식으로 변환하고 분류하는 기상정보 분류부; 기상정보 분류부에서 분류된 기상자료에 기반하여 THI를 산출하기 위한 THI 산출부; 맵데이터 정보 수신부로부터 수신된 맵 데이터에 THI 산출부에서 계산된 THI 정보를 매칭시킨 THI 맵을 생성하기 위한 THI 맵 생성부; 및 THI 맵 생성부에서 생성된 THI 맵을 어플리케이션에서 요구되는 형식을 가진 송출용 THI 데이터로 변환하여 생성하는 송출용 THI 데이터 생성부를 포함하고,상기 THI 산출부는, 기상정보 분류부에서 분류된 기상자료에 기반하여 지역별 THI를 계산하는 지역기반 THI 산출부; 기상정보 분류부에서 분류된 기상자료에 기반하여 시간대별 THI를 계산하는 시간기반 THI 계산부; 및 외기온도에 따른 THI를 계산하는 외기온도기반 THI 산출부를 포함하고,상기 THI 산출부는 기상정보 분류부에서 분류된 기상자료에 기반하여 계사의 환기 형태에 따른 THI 값을 계산하도록 구성되고,THI 맵 생성부는 맵 데이터의 지역별 THI 맵과 함께, 계사의 형태에 따른 THI 값에 기반한 컬러 속성을 갖는 THI 맵을 생성하도록 구성된 것을 특징으로 하는,산란계 온습도지수 알림 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

485/1150 Row 485: application_number: 1020190170644, combined_string: invention_title: 닭진드기 방제를 위한 계사 내 이동식 자외선 조사장치 abstract: 본 발명은 닭진드기 방제를 위한 계사 내 이동식 자외선 조사장치를 개시한다. 본 발명은 바퀴를 구비하여 케이지 모듈의 좌우 방향으로 왕복 이동하는 이동대차; 상기 이동대차에 장착되고, UVC가 케이지 모듈의 각 층에 구비된 복수의 급이통 상측 및 계분 컨베이어 하측으로 확산되는 것을 차폐하는 확산차폐수단을 구비하여 UVC를 각 층의 급이통에서 계분 컨베이어에 이르는 부위에 조사하는 자외선 조사유닛; 상기 이동대차에 장착되고, 배터리 및 배터리에 의해 구동되는 모터를 구비하여 그 이동대차를 주행시키는 주행수단; 케이지 모듈의 적어도 한쪽 끝에 배치되고, 외부로부터 전원이 공급되어서 이동대차가 도킹함에 따라 배터리를 충전시키는 충전도크; 및 위 구성요소들의 작동을 제어하기 위한 콘트롤러;를 포함한다. 바람직하기로 이동대차가 케이지 모듈과 일정간격을 유지한 채 나란하게 주행할 수 있도록 이동대차를 유도하는 대차 가이드를 더 포함할 수 있다.본 발명은 자외선이 닭에 직접 조사되는 것을 최대한 억제하여 자외선 조사로 인해 유발되는 닭의 스트레스 등 여러 부작용을 최소화하면서 케이지에 기생하는 각종 세균과 기생충 특히 닭진드기를 효과적으로 박멸시킬 수 있다. claims: 각기 닭을 수용하는 다수의 케이지가 수평 및 수직으로 배열된 케이지 모듈을 포함하고, 상기 케이지 모듈의 각 층에 위치하는 다수의 케이지가 각각 공유하도록 복수의 급이통과 달걀받이를 수평으로 길게 가지며, 각 층의 케이지 하부에 계분 컨베이어를 갖는 양계장에 있어서,바퀴를 구비하여 상기 케이지 모듈의 좌우 방향으로 왕복 이동하는 이동대차;상기 이동대차에 장착되고, UVC가 상기 케이지 모듈의 각 층에 구비된 복수의 급이통 상측과 계분 컨베이어 하측으로 확산되는 것을 차폐하는 확산차폐수단을 구비하여 UVC를 각 층의 급이통에서 계분 컨베이어에 이르는 부위에 조사하는 자외선 조사유닛;상기 이동대차에 장착되고, 배터리 및 상기 배터리에 의해 구동되는 모터를 구비하여 그 이동대차를 주행시키는 주행수단;상기 케이지 모듈의 적어도 한쪽 끝에 배치되고, 외부로부터 전원이 공급되어서 상기 이동대차가 도킹함에 따라 상기 배터리를 충전시키는 충전도크; 및상기 구성요소들의 작동을 제어하기 위한 콘트롤러;를 포함하는 것을 특징으로 하는 닭진드기 방제를 위한 계사 내 이동식 자외선 조사장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

486/1150 Row 486: application_number: 1020190165097, combined_string: invention_title: 항산화제가 강화된 기능성 계란의 생산방법 abstract: 본 발명은 항산화제가 강화된 기능성 계란의 생산방법에 관한 것으로, 더욱 상세하게는 해저 퇴적층으로 지각변동에 의해 지상에 융기된 부식토를 준비하는 단계; 상기 부식토를 주류 양조 추출법, 주수 추출법, 자연 저온 추출법 중 어느 하나의 방법을 이용하고, 4~14μm 파장 에너지를 자연수에 투입하여 영양수를 제조하는 단계; 및 상기 영양수의 pH를 조절하는 단계를 포함하여 구성되는 산란계 급여용 조성물을 산란계에 급여하는 것을 기술적 특징으로 한다.이에 따라, 비린내가 없으며, 전란 kg당 유황 1931.11mg 비타민C 8.78mg 비타민D3 9295.35IU이상, 비타민E 1.70mg, 셀레늄 0.61mg 이상, 100g당 탄닌 6.22mg, 오메가7 3.34g 이상 함유하여 유황 비타민 아미노산 셀레늄, 오메가7 다양한 영양소 계란 요리의 섭취만으로도 비타민C, E, D3, 탄닌, 셀레늄, 등의 항산화물질 흡수 효과를 얻어 비타민C, E, D3, 탄닌, 셀레늄의 항산화 물질이 갖는 효과를 발현시킬 수 있고, 난황을 착색시킴으로써 착색된 색상을 요하는 요리에 사용될 수 있을 뿐만 아니라 아토피 피부질환 어린이들에게 부작용이 없는 계란의 섭취를 용이하게 할 수 있는 효과가 있다. claims: 해저 퇴적층으로 지각변동에 의해 지상에 융기된 부식토를 준비하는 단계;상기 부식토를 주류 양조 추출법, 주수 추출법, 자연 저온 추출법 중 어느 하나의 방법을 이용하고, 4~14μm 파장 에너지를 자연수에 투입하여 영양수를 제조하는 단계; 및상기 영양수의 pH를 조절하는 단계를 포함하여 구성되는 것을 특징으로 하는 산란계 급여용 조성물의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

487/1150 Row 487: application_number: 1020190161700, combined_string: invention_title: 미세조절이 가능한 체인식 모이공급장치 abstract: 본 발명은 닭을 사육하는 케이지의 모이공급시스템에 설치되어 닭들에게 모이를 공급할 때 모이의 양을 미세하게 조절할 수 있고 정확한 양을 공급할 수 있도록 개선된 미세조정이 가능한 체인식 모이공급장치를 개시한다. claims: 여러 개가 연속되게 설치되고 닭들이 사육되는 케이지와, 양측과 바닥면이 막혀 있고 상면이 개구된 덕트 형상으로 형성되어 내부에 모이통로가 형성되고 케이지를 따라 순환 형태로 설치되어 각 케이지에 모이를 공급할 수 있게 설치된 모이통과, 모이통의 일부분이 내부를 관통하게 설치되어 공급되는 모이를 모이통의 상면 일부분으로 안내하는 호퍼와, 모이통의 내부를 따라 순환 이송되게 설치된 모이이송체인과, 모이이송체인을 순환 이송시키는 체인작동수단으로 이루어져, 호퍼로 모이를 공급하면 호퍼를 관통하는 모이통의 일부분으로 모이가 안내되고 모이이송체인이 순환 이송되면서 모이를 끌고가 모이통을 따라 전체적으로 모이를 공급하게 구성된 케이지의 모이공급시스템에 설치되는 것으로,상기 호퍼의 정면에서 모이통보다 상부에 고정되게 설치되고, 상단에는 정면 방향으로 고정절곡편이 절곡 형성되며, 고정절곡편의 중간에는 볼트관통공이 관통 형성된 고정판과,상기 고정판의 정면 좌측에 고정되게 설치되고, 우측 단부에는 정면으로 절곡되는 좌측가이드편이 형성되어 고정판과 좌측가이드편의 사이에 좌측가이드홈이 형성된 구조를 갖는 좌측브라켓과,상기 고정판의 정면 우측에서 고정되게 설치되고, 좌측 단부에는 정면으로 절곡되는 우측가이드편이 형성되어 고정판과 우측가이드편의 사이에 우측가이드홈이 형성된 구조를 갖는 우측브라켓과,상기 고정판의 정면에 밀착되게 설치되고, 양단이 좌측가이드홈과 우측가이드홈을 따라 삽입되어 상하로 위치조절할 수 있게 설치되며, 하강했을 때 모이통의 모이통로 내부로 삽입되어 모이통로를 차단하게 설치되고, 상단에는 정면 방향으로 조절절곡편이 절곡 형성되며, 조절절곡편의 중간에는 볼트관통공과 대응되는 볼트조립공이 관통 형성된 조절판과,상기 조절절곡편의 볼트조립공과 고정절곡편의 볼트관통공을 관통하도록 조립되고, 볼트머리가 조절절곡편의 하면에 밀착되어 조절판을 받쳐 지지하도록 설치된 고정볼트와,상기 고정볼트의 볼트머리와 근접하게 체결되고, 조절절곡편의 상면에 밀착되게 고정됨으로 볼트머리와의 협동에 의해 고정볼트를 조절절곡편에 고정시키는 볼트고정너트와,상기 고정볼트의 단부에 체결되어 고정절곡편의 상면에 밀착되게 설치되며, 회전 방향에 따라 고정볼트를 승하강시키면서 조절판을 함께 승하강시키는 조절판조절너트와,상기 고정절곡편과 조절절곡편의 사이에서 고정볼트에 체결되는 스프링조절너트와,상기 고정절곡편과 스프링조절너트의 사이에서 고정볼트에 삽입되게 조립되어 고정절곡편을 탄성 가압하게 설치된 공극조절스프링으로 구성되어,상기 조절판조절너트를 조이고 풀면 고정볼트가 상승 또는 하강하면서 조절판의 위치가 조절되어 조절판과 모이이송체인 사이의 공극이 조절되어 공급되는 모이의 양을 조절하게 되고, 좌측브라켓과 우측브라켓을 통해 조절판이 좌우로 흔들리지 않도록 하며, 스프링조절너트를 조이고 풀면서 공극조절스프링의 압축력을 조절하여 조절판이 상하로 움직일 때 그 압력을 조절할 수 있게 구성되며,상기 조절판과 대응되는 모이통의 모이통로 바닥면에는 체인하강방지판이 추가로 고정되게 설치되어 모이이송체인이 조절판과 대응되는 부분을 통과할 때 체인하강방지판에 올려져 하부로 움직이는 것을 방지함으로 모이이송체인이 흔들리지 않고 체인하강방지판을 따라 평행하게 이동할 수 있게 구성함으로,상기 모이이송체인이 조절판의 하부를 통과할 때 조절판과 모이이송체인 사이의 공극이 일정하게 유지되도록 구성된 것을 특징으로 하는 미세조절이 가능한 체인식 모이공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

488/1150 Row 488: application_number: 1020190161483, combined_string: invention_title: 닭의 대흉근으로부터 확립된 근아섬유세포주 및 이를 이용한 생리활성물질 스크리닝 방법 abstract: 본 발명은 닭의 대흉근으로부터 확립된 근아섬유세포주를 이용하여 생리활성을 나타내는 물질을 스크리닝하는 방법에 관한 것으로, 상기 닭의 대흉근으로부터 확립된 근아섬유세포주에 생리활성 후보물질로서 당귀 및 당귀 부산물 추출물을 처리한 후 비처리 대조군 근아섬유세포주와 유전자 발현 수준을 비교한 결과, 당귀 및 당귀 부산물 추출물은 세포증식, 근육분화 (myogenesis), 지방생성 (adipogenesis) 또는 당대사 (glycometabolism)를 조절하는 유전자의 발현 수준을 증가 또는 감소시키는 생리활성이 확인됨에 따라, 상기 닭의 대흉근으로부터 확립된 근아섬유세포주를 이용한 스크리닝 방법은 가축 사료첨가제 또는 생리활성물질 선별을 위한 시험관내 (in vitro) 스크리닝 방법으로 제공될 수 있다. claims: 닭의 대흉근으로부터 확립된 근아섬유세포주 (KCLRF-BP-00410).청구항 1에 있어서, 상기 닭의 대흉근으로부터 확립된 근아섬유세포주는 10일령 수컷 병아리 배아의 대흉근으로부터 분리 및 배양된 것을 특징으로 하는 근아섬유세포주.닭의 대흉근으로부터 확립된 근아섬유세포주 (KCLRF-BP-00410)에 생리활성 조절용 후보물질을 처리하는 단계; 상기 후보물질이 처리된 근아섬유세포주의 유전자 발현 수준을 확인하는 단계; 및상기 확인된 유전자 발현 수준을 비처리 대조군과 비교하는 단계를 포함하는 생리활성물질 스크리닝 방법.닭의 대흉근으로부터 확립된 근아섬유세포주 (KCLRF-BP-00410)에 근육분화용 후보물질을 처리하는 단계; 상기 후보물질이 처리된 근아섬유세포주의 유전자 발현 수준을 확인하는 단계; 및상기 확인된 유전자 발현 수준을 비처리 대조군과 비교하는 단계를 포함하는 근육분화 조절제 스크리닝 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

489/1150 Row 489: application_number: 1020190159831, combined_string: invention_title: 행동패턴 이상 징후 판별 시스템 및 이의 제공방법 abstract: 본 발명의 실시예에 따른 행동패턴 이상 징후 판별 시스템은, 영상센서를 통해 실시간으로 수집되는 영상데이터를 입력 받는 영상수집부; 상기 영상데이터로부터 관심 객체를 검출하기 위하여 영상처리하는 영상처리부; 상기 영상처리된 영상데이터로부터 상기 관심 객체의 행동패턴 특징을 추출하는 행동패턴 추출부; 상기 추출된 행동패턴 특징을 이용하여 상기 관심 객체의 행동패턴을 학습하여 모델링하는 행동패턴 모델링부 및 상기 모델링된 행동패턴을 분석하여 상기 관심 객체의 행동이상 발생 여부를 판단하는 행동이상 판별부를 포함하고, 상기 행동이상 모델링부는 텐서플로우로 학습하여 모델링되고, 상기 행동이상 판별부는, 상기 행동패턴 추출부로부터 행동패턴 특징을 전달받아 관심 객체의 위상과 크기에 대한 정보를 변환하여 주파수의 그래프를 영상정보화한 패턴을 확보하는 FFT변환부; 상기 주파수의 그래프를 영상정보화한 패턴에 대해 실시간으로 딥마인드 판별을 하는 딥마인드판별부를 포함하는 행동패턴 이상 징후 판별 시스템을 제공할 수 있다. claims: 행동패턴 이상 징후 판별 시스템에 있어서,영상센서를 통해 실시간으로 수집되는 영상데이터를 입력 받는 영상수집부;상기 영상데이터로부터 관심 객체를 검출하기 위하여 영상처리하는 영상처리부;상기 영상처리된 영상데이터로부터 상기 관심 객체의 행동패턴 특징을 추출하는 행동패턴 추출부;상기 추출된 행동패턴 특징을 이용하여 상기 관심 객체의 행동패턴을 학습하여 모델링하는 행동패턴 모델링부 및상기 모델링된 행동패턴을 분석하여 상기 관심 객체의 행동이상 발생 여부를 판단하는 행동이상 판별부를 포함하고,상기 행동패턴 모델링부는 텐서플로우로 학습하여 모델링되고,상기 행동이상 판별부는, 상기 행동패턴 추출부로부터 행동패턴 특징을 전달받아 관심 객체의 위상과 크기에 대한 정보를 변환하여 주파수의 그래프를 영상정보화한 패턴을 확보하는 FFT변환부;상기 주파수의 그래프를 영상정보화한 패턴에 대해 실시간으로 딥마인드 판별을 하는 딥마인드판별부를 포함하고,상기 행동패턴 이상 징후 판별 시스템은,상기 행동이상 판별부의 판단에 따라 행동이상의 발생 감지시 정밀검사 의뢰를 요청하는 정밀검사요청부 및관리자 단말로 관심 객체의 행동이상 발생 여부에 관한 정보를 전송하는 알림부를 더 포함하며,상기 영상처리부는,일정 단위 시간 동안 입력된 영상데이터를 이용하여 고정된 화각과 위치를 유지한 영상수집부를 이용해 획득된 영상데이터의 프레임간의 수학적 연산에 의한 정적 화상 정보와 동적 화상 정보를 분리하는 방식을 통해 구분된 영상정보로부터 주위 모델링을 수행하고, 상기 주위 모델링을 통해 학습된 주위 모델을 이용하여 관심 객체를 검출하는 방식으로 영상처리를 진행하고,상기 행동패턴 추출부는,상기 영상데이터를 좌표가 설정된 셀(Cell)단위의 그리드 영역으로 분할하여 구분하고, 분할한 각 영역에서 관심 객체들의 행동패턴 정보를 추출하고, 초당 프레임을 기준으로 움직임 속도와 거리를 산정하며,상기 관심 객체는 닭인 것을 특징으로 하는 행동패턴 이상 징후 판별 시스템.행동패턴 이상 징후 판별 시스템 제공방법에 있어서,(a) 영상센서를 통해 실시간으로 촬영하여 영상데이터를 수집하는 단계;(b) 수집된 영상데이터를 영상처리 하여 관심 객체를 검출하는 단계;(c) 상기 검출된 관심 객체의 행동패턴 특징을 검출하는 단계;(d) 상기 검출된 행동패턴 특징을 이용하여 관심 객체의 행동패턴을 모델링하는 단계 및(e) 상기 모델링된 행동패턴을 분석하여 행동이상 발생 여부를 판단하는 단계를 포함하고,상기 (d)단계는,텐서플로우로 학습하여 모델링되고,상기 (e)단계는,상기 행동패턴 특징으로부터 관심 객체의 위상과 크기에 대한 정보를 변환하여 주파수의 그래프를 영상정보화한 패턴을 확보하기 위해 FFT변환을 진행하는 단계;상기 주파수의 그래프를 영상정보화한 패턴에 대해 실시간으로 딥마인드 판별을 진행하는 단계;상기 딥마인드 판별을 통해 행동이상 발생 여부에 관한 판별결과를 검출하는 단계를 포함하고,상기 (e)단계 이후에,행동이상의 발생 감지시 정밀검사 의뢰를 요청하는 단계를 더 포함하고,상기 행동패턴 이상 징후 판별 시스템 제공방법은,관리자 단말로 관심 객체의 행동이상 발생 여부에 관한 정보를 전송하는 단계를 더 포함하며,상기 (b) 단계는,영상처리부가 일정 단위 시간 동안 입력된 영상데이터를 이용하여 고정된 화각과 위치를 유지한 영상수집부를 이용해 획득된 영상데이터의 프레임간의 수학적 연산에 의한 정적 화상 정보와 동적 화상 정보를 분리하는 방식을 통해 구분된 영상정보로부터 주위 모델링을 수행하고, 상기 주위 모델링을 통해 학습된 주위 모델을 이용하여 관심 객체를 검출하는 방식으로 영상처리를 진행하고,상기 (c)단계는,상기 영상데이터를 좌표가 설정된 셀(Cell)단위의 그리드 영역으로 분할하여 구분하고, 분할한 각 영역에서 관심 객체들의 행동패턴 정보를 추출하고, 초당 프레임을 기준으로 움직임 속도와 거리를 산정하며,상기 관심 객체는 닭인 것을 특징으로 하는 행동패턴 이상 징후 판별 시스템 제공방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

490/1150 Row 490: application_number: 1020190159395, combined_string: invention_title: 케이지식 계사에서 닭진드기 유인물질을 활용한 닭진드기 모니터링용 유인트랩 및 이를 이용한 닭진드기 감염 여부를 확인하는 방법 abstract: 본 발명은 케이지식 계사에서 닭진드기 유인물질을 활용한 닭진드기 모니터링용 유인트랩에 관한 것으로, 본 발명의 계사에 떨어진 닭 깃털을 유인물질로 활용한 닭진드기 모니터링용 유인트랩은 농가에서 쉽게 활용할 수 있는 소재를 이용하여 제작할 수 있고, 18시간 이상 유인트랩 설치 시 신속하고 유의미하게 계사 내에서 닭진드기 감염여부를 판단할 수 있어 농가에서 감염 초기의 닭진드기 방제 시기를 놓칠 위험을 줄임으로써 산란계 농가의 닭진드기 방제 전략을 구상하는데 활용할 수 있다. claims: 1) 닭진드기 모니터링용 유인트랩을 모니터링 대상 계사에 설치하여 기설정된 시간 동안 닭진드기를 포획하는 설치 및 포획 단계;2) 상기 기설정된 시간 경과 후에 상기 닭진드기 모니터링용 유인트랩을 수거하여 포획된 닭진드기를 확인하는 수거 및 확인 단계; 및3) 상기 모니터링 대상 계사의 감염 여부를 판단하는 판단 단계를 포함하는 것을 특징으로 하는 케이지식 계사에서의 닭진드기 감염 여부를 확인하는 방법.닭진드기 유인용 물질을 포함하는 닭진드기 모니터링용 유인트랩., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

491/1150 Row 491: application_number: 1020190155663, combined_string: invention_title: 생리활성물질이 함유된 계란 생산용 가축 사료첨가제 조성물 및 이의 제조방법 abstract: 본 발명은 당귀 부산물을 유효성분으로 함유하는 생리활성물질이 함유된 계란 생산용 가축 사료첨가제 및 이의 제조방법에 관한 것으로, 상기 당귀 부산물인 줄기 및 잎 건조 분쇄물이 첨가된 사료를 급여시킨 산란용 닭은 대조군 및 당귀 뿌리 분말이 포함된 식이를 섭취시킨 닭과 유사한 수준의 계란 생산률을 나타내었으며, 건조된 당귀 줄기 및 잎 분쇄물이 첨가된 사료를 급여시킨 산란용 닭에서 생산된 계란의 난백 및 난황에서 데커신 및 데쿠르시놀 유사체 생리활성 성분이 검출됨에 따라, 상기 당귀 부산물을 유효성분으로 함유하는 조성물은 생리활성물질이 함유된 계란을 생산하는 가축 사료첨가제로 제공될 수 있으며, 고품질의 고부가가치 가축 생산품을 생산할 수 있다. claims: 당귀 부산물을 유효성분으로 함유하며, 생리활성물질이 함유된 계란 생산용 가축 사료첨가제 조성물.당귀 부산물을 60 내지 70℃에서 40 내지 50시간 동안 건조시키는 단계; 상기 건조된 당귀 부산물을 분쇄하는 단계; 및상기 분쇄된 당귀 부산물을 평균직경 1 내지 2 mm 입자 크기로 체질하는 단계를 포함하는 것을 특징으로 하는 생리활성물질이 함유된 계란 생산용 가축 사료첨가제 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

492/1150 Row 492: application_number: 1020190154078, combined_string: invention_title: 가압방식 파각란 판별장치 abstract: 본 발명은 가압방식 파각란 판별장치에 관한 것으로, 계란판(T)이 안치되는 하부 베이스(10)와; 상기 하부 베이스(10)의 상부에서 승강되며 계란판(T)에 안치된 복수의 계란(E) 상부를 각각 누르되 각각 압축코일스프링(22)의 탄성으로 지지되어 파각란(E1)의 경우에는 압축코일스프링(22)의 압축력보다 약한 힘에 의해 눌려 파손되고, 정상란(E2)의 경우에는 압축코일스프링(22)이 압축되면서 상방으로 밀려 정상란(E2)이 파손되지 않도록 된 가압구(20)가 종횡으로 배치된 상부 가압판(30)과; 상기 상부 가압판(30)을 승강시키는 유압실린더(40)와; 상기 유압실린더(40)를 승강 조작하기 위한 조작스위치(50);를 포함하여 이루어져 있다. claims: 계란판(T)이 안치되는 하부 베이스(10)와;상기 하부 베이스(10)의 상부에서 승강되며 계란판(T)에 안치된 복수의 계란(E) 상부를 각각 누르되 각각 압축코일스프링(22)의 탄성으로 지지되어 파각란(E1)의 경우에는 압축코일스프링(22)의 압축력보다 약한 힘에 의해 눌려 파손되고, 정상란(E2)의 경우에는 압축코일스프링(22)이 압축되면서 상방으로 밀려 정상란(E2)이 파손되지 않도록 된 가압구(20)가 종횡으로 배치된 상부 가압판(30)과;상기 상부 가압판(30)을 승강시키는 유압실린더(40)와;상기 유압실린더(40)를 승강 조작하기 위한 조작스위치(50);를 포함하여 이루어지는 것을 특징으로 하는 가압방식 파각란 판별장치.청구항 1에 있어서.상기 상부 가압판(30)의 전방에는 작업자의 손이나 기타 장애물이 판별장치 내부에 있을 때 조작스위치(50)를 밟더라도 하강이 이루어지지 않도록 하기 위한 안전 센서(70)가 더 구비된 것을 특징으로 하는 가압방식 파각란 판별장치., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

493/1150 Row 493: application_number: 1020190148983, combined_string: invention_title: 소리가 발생하는 가축용 음수 공급장치 abstract: 본 발명은 소리가 발생하는 가축용 음수 공급장치에 있어서, 급수공급라인에 분기 형성되는 적어도 하나 이상의 분기관, 상기 분기관에 연결되는 분기관 연결구를 가지며 내부에는 상기 분기관을 통해 공급된 음수가 저장되는 챔버가 마련된 밸브본체, 상기 밸브본체의 하단에 연결되며 상기 챔버로 공급된 음수를 워터컵으로 배출하는 배출관, 상기 밸브본체의 상단에 연결 설치되는 결합관, 상기 결합관의 선단에 삽입되며 중앙으로는 공기를 통과시키는 공기구멍이 형성되어, 상기 챔버에 저장된 음수가 배출되는 과정에서 발생한 기압 차이에 의해 상기 공기구멍을 통해 공기가 상기 챔버로 흡입 또는 배출되는 과정에서 특정음의 소리를 발생시키는 소리발생관을 포함하여 구성함을 특징으로 하는 소리가 발생하는 가축용 음수 공급장치를 제공한다. claims: 소리가 발생하는 가축용 음수 공급장치에 있어서,급수공급라인(10)에 분기 형성되는 적어도 하나 이상의 분기관(20);상기 분기관(20)에 연결되는 분기관 연결구(34)를 가지며 내부에는 상기 분기관(20)을 통해 공급된 음수가 저장되는 챔버(33)가 마련된 밸브본체(32);상기 밸브본체(32)의 하단에 연결되며 상기 챔버(33)로 공급된 음수를 워터컵(16)으로 배출하는 배출관(14);상기 밸브본체(32)의 상단에 연결 설치되는 결합관(50);상기 결합관(50)의 선단에 삽입되며 중앙으로는 공기를 통과시키는 공기구멍(62)이 형성되어, 상기 챔버(33)에 저장된 음수가 배출되는 과정에서 발생한 기압 차이에 의해 상기 공기구멍(62)을 통해 공기가 상기 챔버(33)로 흡입 또는 배출되는 과정에서 특정음의 소리를 발생시키는 소리발생관(60)을 포함하여 구성함을 특징으로 하는 소리가 발생하는 가축용 음수 공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

494/1150 Row 494: application_number: 1020190148122, combined_string: invention_title: 복분자 계란의 생산 방법 및 상기 방법으로 생산된 복분자 계란 abstract: 본 발명은 복분자 계란의 생산 방법 및 상기 방법으로 생산된 복분자 계란에 관한 것이다.구체적으로는, 복분자의 유효성분이 함유된 사료를 섭취한 닭으로부터 계란을 생산하여, 복분자의 유효성분이 함유된 계란을 섭취할 수 있도록 하는, 복분자 계란의 생산 방법에 관한 것이다. claims: 복분자 분말을 획득하는 단계;사료를 준비하는 단계;상기 복분자 분말을 획득하는 단계에서 획득된 복분자 분말과, 사료를 준비하는 단계에서 혼합되어 준비된 사료를 혼합하는 복분자 분말 및 사료를 혼합하는 단계;상기 복분자 분말 및 사료를 혼합하는 단계에서 획득된 복분자 사료를 산란계에게 섭취시키는 사료를 섭취시키는 단계; 및상기 사료를 섭취하는 단계를 통해 산란계가 복분자 사료 섭취 후 10일 이후에 낳은 복분자 계란을 수집하는 단계;를 포함하여 이루어지는 것을 특징으로 하는, 복분자 계란의 생산 방법.청구항 1 내지 8 중 선택된 어느 한 항에 기재된 생산 방법으로 생산된 복분자 계란., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

495/1150 Row 495: application_number: 1020190118397, combined_string: invention_title: 구기자를 이용한 고품질 가축류의 사육방법 abstract: 본 발명은 구기자를 이용한 고품질 가축류의 사육방법으로(a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 일반 가축류 급여용 사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 1kg~10kg을 혼합하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가축류 출하전 60일~180일간 급여하여 사육하는 단계; (j) 상기(i)단계의 사육과정을 통하여 사육된 가축류를 출하하여 제품화하는 단계를 포함하여 이루어진다. claims: (a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 일반 가축류 급여용 사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 1kg~10kg을 혼합하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가축류 출하전 60일~180일간 급여하여 사육하는 단계; (j) 상기(i)단계의 사육과정을 통하여 사육된 가축류를 출하하여 제품화하는 단계를 포함하는 것을 특징으로 하는 구기자를 이용한 고품질 가축류의 사육방법.제1항의 사육방법에 의하여 생산된 가축의 육류., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

496/1150 Row 496: application_number: 1020190118410, combined_string: invention_title: 구기자를 이용한 고품질계란의 생산방법 abstract: 본 발명은 구기자를 이용한 고품질계란의 생산방법에 관한 것으로,(a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 가금류용 일반사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 0.5kg~10kg의 중량비로 첨가하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가금류에 산란전 20~30일부터 급여하여 사육하는 단계; (j) 상기를 (i)단계의 사육과정을 통하여 생산되는 계란을 제품화하는 단계로 이루어진다. claims: (a) 구기자 : 구기자잎을 10~40 : 60~90의 중량비로 혼합하는 단계; (b) 상기(a)의 구기자혼합물을 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자혼합물 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 상기(f)단계의 발효가 완료된 구기자혼합물을 건조하는 단계; (h) 가금류용 일반사료 1000kg당 상기(g)단계의 건조된 구기자혼합물을 0.5kg~10kg의 중량비로 첨가하여 교반하는 단계; (i) 상기(h)단계의 혼합사료를 가금류에 산란전 20~30일부터 급여하여 사육하는 단계; (j) 상기를 (i)단계의 사육과정을 통하여 생산되는 계란을 제품화하는 단계를 포함하는 것을 특징으로 하는 구기자를 이용한 고품질계란의 생산방법. 제1항의 사육방법에 의하여 생산된 계란., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

497/1150 Row 497: application_number: 1020190115919, combined_string: invention_title: 계사 내 진드기 포획장치 및 포획장치 관리시스템 abstract: 본 발명은 계사 내 진드기 포획장치 및 포획장치 관리시스템에 관한 것이다. 이는, 일정두께의 시트 형태를 취하는 가요성 베이스층, 상기 베이스층에 적층되며 내부로 파고 들어온 진드기를 잡아 포획하는 다공성 포획층을 구비하고, 계사에 설치된 상태로 주변 진드기를 유도 포획하는 포획시트와; 상기 포획시트와 함께 사용하는 것으로서, 상기 포획시트의 무게 변화를 감지하고 감지 내용을 외부로 전달하는 검출수단을 포함한다.상기와 같이 이루어지는 본 발명의 계사 내 진드기 포획장치는, 닭에 기생하는 진드기를 효과적으로 유인 및 포획할 수 있으며, 진드기의 호흡에 의한 온도변화나 무게변화를 감지하여 외부로 전송하므로 원격 제어를 가능하게 한다. 또한, 본 발명의 포획장치 관리시스템은, 다수의 포획장치와 무선 연결되며 포획장치에서 감지된 진드기의 개체수 정보를 기초로 포획장치의 교체 여부를 판단할 수 있으므로 전체적인 관리가 용이하다. claims: 일정두께의 시트 형태를 취하는 가요성 베이스층, 상기 베이스층에 적층되며 내부로 파고 들어온 진드기를 잡아 포획하는 다공성 포획층을 구비하고, 계사에 설치된 상태로 주변 진드기를 유도 포획하는 포획시트와;상기 포획시트와 함께 사용하는 것으로서, 상기 포획시트의 무게 변화를 감지하고 감지 내용을 외부로 전달하는 검출수단을 포함하는 계사 내 진드기 포획장치.일정두께의 시트 형태를 취하는 가요성 베이스층, 상기 베이스층에 적층되며 내부로 파고 들어온 진드기를 잡아 포획하는 다공성 포획층을 구비하고, 계사에 설치된 상태로 주변 진드기를 유도 포획하는 다수의 포획시트와;상기 포획시트와 함께 사용하는 것으로서, 각 포획시트의 무게 변화를 감지하고 감지 내용을 외부로 전달하는 검출수단과; 상기 검출수단을 통해 개별 포획시트의 무게 데이터를 전달받으며, 설정된 무게 기준에 기초하여, 교체할 포획시트를 찾아내는 제어부를 구비하는 포획장치 관리시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

498/1150 Row 498: application_number: 1020190115691, combined_string: invention_title: 그룹별 축산물 생애 정보 제공 시스템 abstract: 본 발명은 그룹별 축산물 생애 정보 제공 시스템에 관한 것으로서, 보다 구체적으로는 정보 제공 시스템으로서, 정보 제공 시스템으로서, 가축 및 가금을 포함하는 축산물에 대한 정보를 제공하되, 서로 관계있는 복수의 축산물을 그룹화하여 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 관리 및 제공하는 정보 제공 서버; 및 상기 축산물의 식별정보를 인식하고, 인식한 식별정보를 상기 정보 제공 서버에 전송하여 상기 축산물에 대한 데이터 제공 요청을 하는 소비자 디바이스를 포함하며, 상기 소비자 디바이스는, 상기 축산물의 식별정보를 인식하는 인식 모듈; 상기 정보 제공 서버에 상기 식별정보를 전달하고, 상기 식별정보에 대응되는 축산물의 데이터 제공 요청을 하는 정보 요청 모듈; 및 상기 정보 제공 서버로부터 수신한 축산물 생애 정보를 출력하는 출력 모듈을 포함하는 것을 그 구성상의 특징으로 한다.가축 및 가금을 포함하는 축산물에 대한 정보를 제공하는 정보 제공 서버; 및 상기 축산물의 식별정보를 인식하고, 인식한 식별정보를 상기 정보 제공 서버에 전송하여 상기 축산물에 대한 데이터 제공 요청을 하는 소비자 디바이스를 포함하며, 상기 정보 제공 서버는, 서로 관계있는 복수의 축산물을 그룹화하고, 그룹화 한 그룹별로 식별정보를 할당하는 그룹화 모듈; 상기 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 저장하는 데이터베이스 모듈; 상기 그룹별로 축산물이 사육되는 농가의 축사 관리 기록, 축산물의 진료 또는 치료 정보, 및 측정 정보를 포함하는 건강관리 정보를 수집하는 제1 정보 수집 모듈; 상기 그룹별로 축산물이 사육되는 농가 또는 축사의 주변 환경 정보를 포함하는 사육 환경 정보를 수집하는 제2 정보 수집 모듈; 및 상기 소비자 디바이스의 데이터 제공 요청에 대응하여, 상기 소비자 디바이스로부터 수신한 식별정보에 대응하는 그룹의 축산물 생애 정보를 상기 데이터베이스 모듈에서 검색하며, 상기 검색된 그룹의 축산물 생애 정보를 제공하는 데이터 제공 모듈을 포함하며, 상기 소비자 디바이스는, 축산물의 패키지로부터 식별정보를 인식하여 상기 데이터 제공 요청을 하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 그룹별 축산물 생애 정보 제공 시스템에 따르면, 축산물을 그룹화하고 그룹별로 축산물 생애 정보를 제공함으로써, 도축 후의 정보인 이력제 정보와는 상이한, 축산물의 생애와 관련된 다양한 정보를 효율적으로 소비자에게 제공할 수 있고, 동일한 날 하나의 모체에서 생산된 복수의 자체, 또는 하나의 그룹으로 관리되는 복수의 모체에서 생산된 출생일이 유사한 복수의 자체를 그룹화 함으로써, 농가에서 그룹별로 효율적인 축산물 관리를 하면서도, 정확도가 높은 축산물 생애 정보를 소비자에게 제공할 수 있다.또한, 본 발명에 따르면, 축산물 이력제와 연동하여, 소비자 디바이스에서 인식한 식별정보가 축산물 이력제에 따른 이력번호이면, 정보 제공 서버에서 제공하는 축산물 생애 정보와 함께, 도축 후부터 포장, 유통 단계와 관련된 축산물 이력제에 따른 이력 정보를 소비자 디바이스로 출력함으로써, 한 번의 식별정보 인식을 통해 축산물의 출생, 모체 정보, 건강, 사육 환경, 도축, 포장, 및 유통까지 전 과정에 대한 다양한 정보를 쉽게 확인할 수 있다.뿐만 아니라, 본 발명에 따르면, 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 저장하고, 소비자 디바이스의 데이터 제공 요청에 대응하여 그룹의 축산물 생애 정보를 시각화하여 제공함으로써, 축산물 생애와 관련된 다양한 정보를 이해하기 쉽게 소비자에게 제공할 수 있고, 통신망 및 소비자 디바이스를 이용해 정보의 양에 대한 제한 없이 건강한 먹거리와 직결되는 실질적이고 다양한 정보를 쉽게 제공하며, 소비자들이 안심하고 축산물을 선택할 수 있도록 하여 축산물에 대한 소비자 신뢰도를 향상시킬 수 있다. claims: 정보 제공 시스템으로서,가축 및 가금을 포함하는 축산물에 대한 정보를 제공하되, 서로 관계있는 복수의 축산물을 그룹화하여 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 관리하고, 상기 축산물 생애 정보를 소비자에게 제공하는 정보 제공 서버(100); 및상기 축산물의 식별정보를 인식하고, 인식한 식별정보를 상기 정보 제공 서버(100)에 전송하여 상기 축산물에 대한 데이터 제공 요청을 하되, 소비자용 애플리케이션(201)이 설치 및 구동되고, 상기 소비자용 애플리케이션(201)을 이용해 축산물의 패키지나 리포트에 포함된 식별번호를 인식해 상기 정보 제공 서버(100)에 데이터 제공 요청을 하는 소비자 디바이스(200)를 포함하며,상기 소비자 디바이스(200)는,상기 축산물의 식별정보를 인식하는 인식 모듈(210);상기 정보 제공 서버(100)에 상기 식별정보를 전달하고, 상기 식별정보에 대응되는 축산물의 데이터 제공 요청을 하는 정보 요청 모듈(220);상기 인식 모듈(210)에서 인식된 식별정보를 조회하는 번호 조회 모듈(230);상기 번호 조회 모듈(230)의 조회 결과, 상기 식별정보가 축산물 이력제에 따른 이력번호이면, 상기 이력번호를 이용해 해당 축산물의 축산물 이력제에 따른 이력 정보를 검색하는 이력제 검색 모듈(240); 및상기 정보 제공 서버(100)로부터 수신한 축산물 생애 정보를 출력하며, 상기 이력제 검색 모듈(240)의 검색에 따른 이력 정보를 더 출력하는 출력 모듈(250)을 포함하고,상기 정보 제공 서버(100)는,축산물 이력제 시스템과 연동하여, 상기 이력번호와 그룹별 식별정보를 연동하여 관리하되, 상기 이력번호와 그룹별 식별번호를 매칭 테이블로 관리하여, 상기 소비자 디바이스(200)에서 인식된 식별정보가 이력번호인지 그룹별 식별정보인지에 관계없이 축산물 생애 정보를 검색하여 제공할 수 있으며,상기 정보 제공 서버(100)는,서로 관계있는 복수의 축산물을 그룹화하되, 동일한 날 하나의 모체에서 생산된 복수의 자체, 또는 하나의 그룹으로 관리되는 복수의 모체에서 미리 정해진 기간 내에 출생한 복수의 자체를 그룹화하고, 그룹화 한 그룹별로 식별정보를 할당하는 그룹화 모듈(110);상기 그룹별로 축산물의 건강관리 정보, 사육 환경 정보 및 농장 정보를 포함하는 축산물 생애 정보를 저장하는 데이터베이스 모듈(120);상기 그룹별로 축산물이 사육되는 농가의 축사 관리 기록, 축산물의 진료 또는 치료 정보, 및 측정 정보를 포함하는 건강관리 정보를 수집하는 제1 정보 수집 모듈(130);상기 그룹별로 축산물이 사육되는 농가 또는 축사의 주변 환경 정보를 포함하는 사육 환경 정보를 수집하는 제2 정보 수집 모듈(140);상기 데이터베이스 모듈(120)에 저장된 축산물 생애 정보를 데이터 마이닝하여 축산물 생애 정보에 포함되는 정보 사이의 상관관계를 분석하며, 데이터 마이닝 기술을 통해 미리 정해진 개수의 등급으로 분류하여 각 분야별 축산물의 등급을 산정하는 데이터 분석 모듈(160); 및상기 소비자 디바이스(200)의 데이터 제공 요청에 대응하여, 상기 소비자 디바이스(200)로부터 수신한 식별정보에 대응하는 그룹의 축산물 생애 정보를 상기 데이터베이스 모듈(120)에서 검색하며, 상기 검색된 그룹의 축산물 생애 정보를 제공하는 데이터 제공 모듈(170)을 포함하며,상기 데이터 제공 모듈(170)은,상기 수신한 식별정보에 대응하는 그룹의 축산물을 생산한 모체 또는 분만일이 미리 정해진 기간 내인 모체 그룹을 매칭하여, 매칭된 모체 또는 모체 그룹의 축산물 생애 정보 및 상기 검색된 그룹의 축산물 생애 정보를 제공하는 것을 특징으로 하는, 그룹별 축산물 생애 정보 제공 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

499/1150 Row 499: application_number: 1020190104646, combined_string: invention_title: 이동식 자연채광 스마트 계사 (소규모사육) abstract: 1. 소규모 사육(100수단위)에 대한 최적화 환경 제공.2. 컨테이너 프레임으로 제작되어 이동이 가능함.3. IoT 구축으로 양계종사자들에게 편의성 제공.4. 맹지 등의 오지(전기,수도,지하수불가지역)에서도 육계, 산란계 사육가능(태양열 집전판 설치)5. 울타리 설치시 계사와 연동으로 방사환경 조성. claims: 자연채광을 제공하는 *PC 지붕층 컨테이너 프레임의 이동식 형태. 계사 자체 소모전력을 자가공급하는 방식의 제작형태에 대한 유사제작방지* PC : 폴리카보네이트, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

500/1150 Row 500: application_number: 1020190101443, combined_string: invention_title: 자동산란장치 abstract: 본 발명은 닭의 산란 환경을 조성하고 달걀 수거를 자동으로 진행할 수 있는 자동산란장치에 대한 것이며, 구체적으로 닭이 진입하여 산란하는 산란부와 산란부에 진입한 닭의 산란 환경을 조성하기 위한 산란유도부와 산란부의 하단에 형성되며, 바닥재를 수거하여 재생하는 바닥재수거부와 닭이 산란한 달걀을 수거하는 달걀수거부를 구비한다. claims: 닭이 진입하여 산란하는 산란부(100);,상기 산란부(100)에 진입한 닭의 산란 환경을 조성하기 위한 산란유도부(200);,상기 산란부(100)의 하단에 형성되며, 바닥재(20)를 수거하여 재생하는 바닥재수거부(300);닭이 산란한 달걀(10)을 수거하는 달걀수거부(400);를 포함하는 자동산란장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

501/1150 Row 501: application_number: 1020190101249, combined_string: invention_title: 스마트 달걀 트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 장치 및 방법 abstract: 본 발명의 일 실시예에 따라, 서버에 의해 수행되는, 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법에 있어서, (a) 달걀 트레이로부터 부족한 달걀의 개수를 수신하는 단계; (b) 달걀의 판매가 가능한 양계장 리스트를 사용자 단말로 제공하는 단계; (c) 사용자 단말이 선택한 양계장에 대응하는 양계장의 공급자 단말로 부족한 달걀의 개수만큼 주문요청을 전송하고, 공급자 단말로부터 사용자에게 배송될 달걀 이미지를 수신하는 단계; 및 (d) 달걀 이미지를 사용자 단말로 제공하고, 공급자 단말 또는 사용자 단말을 통해 수집한 유통기한 관련정보를 참고하여, 사용자 단말로 달걀이 주문된 이후, 기 설정된 시간 경과 시 달걀 트레이 내의 달걀에 대한 유통기한 알람메시지를 제공하는 단계를 포함된다. claims: 서버에 의해 수행되는, 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법에 있어서,(a) 달걀 트레이로부터 부족한 달걀의 개수를 수신하는 단계;(b) 달걀의 판매가 가능한 양계장 리스트를 사용자 단말로 제공하는 단계; (c) 상기 사용자 단말이 선택한 양계장에 대응하는 양계장의 공급자 단말로 상기 부족한 달걀의 개수만큼 주문요청을 전송하고, 상기 공급자 단말로부터 사용자에게 배송될 달걀 이미지를 수신하는 단계; 및(d) 상기 달걀 이미지를 사용자 단말로 제공하고, 상기 공급자 단말 또는 상기 사용자 단말을 통해 수집한 유통기한 관련정보를 참고하여, 상기 사용자 단말로 달걀이 주문된 이후, 기 설정된 시간 경과 시 달걀 트레이 내의 달걀에 대한 유통기한 알람메시지를 제공하는 단계를 포함하는 것인, 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법.스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 장치에 있어서,스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법을 제공하는 프로그램이 저장된 메모리 및상기 메모리에 저장된 프로그램을 실행하여 상기 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법을 제공하는 프로세서를 포함하되,상기 프로세서는 달걀 트레이로부터 부족한 달걀의 개수를 수신하고, 달걀의 판매가 가능한 양계장 리스트를 사용자 단말로 제공하고, 상기 사용자 단말이 선택한 양계장에 대응하는 양계장의 공급자 단말로 상기 부족한 달걀의 개수만큼 주문요청을 전송하고, 상기 공급자 단말로부터 사용자에게 배송될 달걀 이미지를 수신하고, 상기 달걀 이미지를 사용자 단말로 제공하고, 상기 공급자 단말 또는 상기 사용자 단말을 통해 수집한 유통기한 관련정보를 참고하여, 상기 사용자 단말로 달걀이 주문된 이후, 기 설정된 시간 경과 시 달걀 트레이 내의 달걀에 대한 유통기한 알람메시지를 제공하는, 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 장치.제 1 항에 의한 스마트 달걀트레이 기반 달걀 자동주문 및 관리를 수행하기 위한 방법을 수행하기 위한 프로그램이 기록된 컴퓨터 판독가능 저장매체., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

502/1150 Row 502: application_number: 1020190093961, combined_string: invention_title: 종계 음수 첨가용 티백조성물의 제조방법 abstract: 본 발명은 종계 음수 첨가용 티백조성물의 제조방법에 관한 것으로, 동애등에 유충에게 사료를 급여하는 단계(단계 1); 동애등에 성충에게 미생물수를 급여하는 단계(단계 2); 상기 사료를 먹고 사육된 동애등에 번데기 및 상기 미생물수를 먹고 사육된 동애등에 성충을 혼합하여 제1 혼합물을 만든 후 분말화하는 단계(단계 3); 상기 사료를 먹고 사육된 동애등에 번데기 및 미강을 혼합하여 제2 혼합물을 만든 후 건조하는 단계(단계 4); 상기 건조된 제2 혼합물 및 상기 분말화한 제1 혼합물을 혼합하여 제3 혼합물을 만든 후 발효시키는 단계(단계 5); 상기 발효물을 건조하는 단계(단계 6); 및 상기 건조된 발효물을 티백포장하는 단계(단계 7); 를 포함하는 것을 기술적 특징으로 하며, 동애등에를 이용한 종계 음수 첨가용 티백조성물을 음수에 투입하고 종계에 급여함으로써 양계장에서 사육되는 종계의 체중을 표준매뉴얼의 체중에 부합하도록 조절할 수 있는 장점이 있다. claims: 동애등에 유충에게 사료를 급여하는 단계(단계 1);동애등에 성충에게 미생물수를 급여하는 단계(단계 2);상기 사료를 먹고 사육된 동애등에 번데기 및 상기 미생물수를 먹고 사육된 동애등에 성충을 혼합하여 제1 혼합물을 만든 후 분말화하는 단계(단계 3);상기 사료를 먹고 사육된 동애등에 번데기 및 미강을 혼합하여 제2 혼합물을 만든 후 건조하는 단계(단계 4);상기 건조된 제2 혼합물 및 상기 분말화한 제1 혼합물을 혼합하여 제3 혼합물을 만든 후 발효시키는 단계(단계 5);상기 발효물을 건조하는 단계(단계 6); 및상기 건조된 발효물을 티백포장하는 단계(단계 7);를 포함하는, 종계 음수 첨가용 티백조성물의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

503/1150 Row 503: application_number: 1020210040230, combined_string: invention_title: 폴더블 펫 드라이어 abstract: 본 발명은 폴더블 펫 드라이룸에 관한 것으로, 보다 상세하게는 펼침 상태에서 애완동물의 드라이를 위한 공간을 형성하고, 접힘 가능한 폴더블 구조를 제공함으로써, 공간효율 및 휴대성 등이 증대된 폴더블 펫 드라이어에 관한 것이다.이러한 본 발명은, 건조 공간을 구비하고, 상기 건조 공간의 일 측에 구비된 내기 유입부 및 상기 건조 공간의 또 다른 일 측에 구비된 내기 공급부를 포함하는 하우징, 상기 하우징에 결합되어 상기 건조 공간을 형성하는 도어 및 상기 하우징에 구비되고, 상기 하우징의 접힘 및 펼침 동작을 제공하는 힌지결합수단을 포함한다. claims: 건조 공간을 구비하고, 상기 건조 공간의 일 측에 구비된 내기 유입부 및 상기 건조 공간의 또 다른 일 측에 구비된 내기 공급부를 포함하는 하우징; 및상기 하우징에 구비되고, 상기 하우징의 접힘 및 펼침 동작을 제공하는 힌지결합수단;을 포함하는 폴더블 펫 드라이어., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

504/1150 Row 504: application_number: 1020210000977, combined_string: invention_title: 바닥공간 활용도가 향상된 수직적층형 벌통 abstract: 본 발명에 따른 바닥공간 활용도가 향상된 수직적층형 벌통은: 상부가 개방된 오면체 형상의 외관을 갖도록 마련되며, 내부 바닥에 형성된 둘 이상의 장착 슬롯들 중 적어도 하나에 사양기가 착탈 가능하게 장착되고, 운반 또는 보관시 하부에 배치되며, 설치시 상부에 배치되는 몸체 어셈블리; 운반 또는 보관시 상기 몸체 어셈블리의 개방된 상부가 밀폐되게 상기 몸체 어셈블리의 상부에 구비되며, 설치시 상기 몸체 어셈블리의 하부에 배치될 때에 상기 사양기가 하부로 관통 돌출되는 사양기 관통공이 방사상 천공 형성된 상부커버를 갖는 커버 어셈블리; 상부와 하부가 개방된 사면체 형상의 외관을 갖도록 마련되며, 운반 또는 보관시 상기 몸체 어셈블리와 상기 커버 어셈블리의 사이에 개재되도록 하부가 상기 몸체 어셈블리의 상부에 맞물림 결합되고 상부가 상기 커버 어셈블리의 하부에 맞물림 결합되도록 구비되는 계상 어셈블리; 및, 상기 몸체 어셈블리의 장착 슬롯에 상기 사양기를 대신하여 착탈 가능하게 구비되며, 외부에서의 회전 조작에 의해 상기 몸체 어셈블리의 내부가 환기되도록 하는 바닥슬롯 환기유닛;을 포함하는 것을 특징으로 한다. 이에 의하여, 벌통의 몸체 내부의 바닥공간이 충분히 확보되도록 하여 벌통의 몸체 내부의 소비를 줄이거나 벌통의 몸체를 수평방향으로 불필요하게 확장할 필요없이 몸체의 내부에 하나 이상의 사양기가 간편하게 장착되도록 할 수 있고, 설치시 벌통의 몸체 내부에 장착된 사양기가 지면으로부터 충분한 이격을 갖도록 하여 부력체를 갖는 사양기의 부력체가 제대로 작동되도록 할 수 있으며, 벌통 몸체 내부의 바닥공간에서 소문이 형성된 전방에 인접한 부분과 후방 측에 간편하게 조작되는 환기 수단을 두어 단열 보강과 함께 입체적인 환기를 통한 꿀벌의 생육과 벌꿀의 생산이 증대되도록 할 수 있고, 벌통의 제작이 보다 저렴한 비용으로 간편하게 이뤄지며 변형 또한 최소화 되도록 내구성이 향상되도록 할 수 있으며, 운반과 설치도 용이 해지도록 할 수 있는 바닥공간 활용도가 향상된 수직적층형 벌통을 제공할 수 있다. claims: 상부가 개방된 오면체 형상의 외관을 갖도록 마련되며, 내부 바닥에 형성된 둘 이상의 장착 슬롯(111)들 중 적어도 하나에 사양기(10)가 착탈 가능하게 장착되고, 운반 또는 보관시 하부에 배치되며, 설치시 상부에 배치되는 몸체 어셈블리(100);운반 또는 보관시 상기 몸체 어셈블리(100)의 개방된 상부가 밀폐되게 상기 몸체 어셈블리(100)의 상부에 구비되며, 설치시 상기 몸체 어셈블리(100)의 하부에 배치될 때에 상기 사양기(10)가 하부로 관통 돌출되는 사양기 관통공(211)이 방사상 천공 형성된 상부커버(210)를 갖는 커버 어셈블리(200);상부와 하부가 개방된 사면체 형상의 외관을 갖도록 마련되며, 운반 또는 보관시 상기 몸체 어셈블리(100)와 상기 커버 어셈블리(200)의 사이에 개재되도록 하부가 상기 몸체 어셈블리(100)의 상부에 맞물림 결합되고 상부가 상기 커버 어셈블리(200)의 하부에 맞물림 결합되도록 구비되는 계상 어셈블리(300); 및상기 몸체 어셈블리(100)의 장착 슬롯(111)에 상기 사양기(10)를 대신하여 착탈 가능하게 구비되며, 외부에서의 회전 조작에 의해 상기 몸체 어셈블리(100)의 내부가 환기되도록 하는 바닥슬롯 환기유닛(500);을 포함하고,상기 바닥슬롯 환기유닛(500)은, 상기 장착 슬롯(111)의 길이방향을 따라 긴 통 형상의 외관을 이루며 표면에는 다수의 통공들이 천공 형성된 슬롯환기 케이싱(510)과, 상기 슬롯환기 케이싱(510)의 내부에서 회전가능하게 구비되어 회전 정도에 따라 상기 장착 슬롯(111)이 개폐되도록 하며 통풍 양도 조절되도록 상기 슬롯환기 케이싱(510)의 평면 형상에 대응되게 판체 형상으로 마련된 회전판(520)과, 상기 회전판(520)의 일측에 일측이 조립되고 타측이 상기 슬롯환기 케이싱(510)의 외부로 돌출 연장되게 구비되어 상기 회전판(520)의 회전이 조작되도록 하는 회전조작 로드(530)를 포함하며,상기 몸체 어셈블리(100)의 내부 바닥 중 후방에는 바닥 환기창(113)이 천공 형성되고, 상기 바닥 환기창(113)은 슬라이딩 이동가능한 구조로 상기 몸체 어셈블리(100)에 구비된 바닥 환기 어셈블리(600)에 의해 개폐되며,상기 몸체 어셈블리(100)의 상부와 상기 계상 어셈블리(300)의 하부의 사이, 그리고 상기 커버 어셈블리(200)의 하부와 상기 계상 어셈블리(300)의 상부의 사이에 각각 구비되어 운반 또는 보관시 이중 잠금 조작에 의해 상기 몸체 어셈블리(100), 커버 어셈블리(200), 계상 어셈블리(300)가 서로 수직으로 맞물려 결합된 상태가 고정되도록 하는 이중잠금장치(400)를 더 포함하고, 상기 이중잠금장치(400)는, 상기 커버 어셈블리(200)의 하부와 상기 계상 어셈블리(300)의 하부에 각각 구비되며 전방으로 제1 후크(411)가 돌출 연장된 경첩 물림부(410)와, 상기 계상 어셈블리(300)의 상부와 상기 몸체 어셈블리(100)의 상부에서 상기 경첩 물림부(410)의 하부에 대응되는 위치에 각각 구비되며 하부에는 전방으로 제2 후크(422)가 돌출 형성된 레버 홀더(421)와 레버 홀더(421)의 상부에 회동가능하게 구비되는 잠금 레버(425)와 잠금 레버(425)에 회동가능하게 구비되어 회동 동작에 의해 상기 경첩 물림부(410)의 제1 후크(411)에 걸려 고정되는 걸림 고리(427)로 이뤄진 경첩부(420)와, 상기 잠금 레버(425)의 전방에서 잠금 레버(425)의 회동방향에 가로방향으로 회동가능하게 구비되어 상기 제1 후크(411)에 상기 걸림 고리(427)의 걸림이 완료되고 난 후 회동 동작에 의해 상기 제2 후크(422)를 가로막는 방향으로 걸려 고정되는 빗장부(430)를 포함하며, 상기 잠금 레버(425)의 하부에는 상기 제2 후크(422)가 전방으로 관통되어 노출되도록 관통공(426)이 천공 형성되고, 상기 레버 홀더(421)의 하부에서 상기 제2 후크(422)의 좌우 양측 중 적어도 하나에는 상기 빗장부(430)에 의한 제2 후크(422)의 걸림 시 상기 잠금 레버(425)의 하부를 밀어주는 스프링 부재(423)가 구비된 것을 특징으로 하는 바닥공간 활용도가 향상된 수직적층형 벌통., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

505/1150 Row 505: application_number: 1020200148884, combined_string: invention_title: 곤충사육사용 조명 abstract: 본 발명은 곤충사육사용 조명에 관한 것으로, 곤충사육사(10)에 설치되며 자연광의 빛을 구현하는 자연광 조명부(110)와 상기 자연광 조명부(110)가 자연광의 빛을 구현하도록, 계절 및 시간대별 태양광 데이터를 기초로 상기 자연광 조명부(110)의 색온도와 점등 및 소등을 제어하는 제어기(120)를 포함한다. 본 발명은 태양의 고도에 따라 일출에서 일몰까지 변화하는 색온도를 실내에서 구현하여 동애등에를 사육하는 곤충사육사의 조명 환경을 개선하여 동애등에의 생산성을 증가시킬 수 있는 이점이 있다. claims: 곤충사육사에 설치되며 자연광의 빛을 구현하는 자연광 조명부; 및상기 자연광 조명부가 자연광의 빛을 구현하도록, 계절 및 시간대별 태양광 데이터를 기초로 상기 자연광 조명부의 색온도와 점등 및 소등을 제어하는 제어기;를 포함하며, 상기 자연광 조명부는 기판에 복수 개의 엘이디가 배열 설치되어 형성되며, 상기 복수 개의 엘이디는 색온도 2800~3000K 대역을 가지는 제1 엘이디; 및색온도 8000K~10000K을 가지는 제2 엘이디;를 포함하고, 상기 제어기는 AC 전원을 DC 전원으로 변환하는 컨버터; 계절 및 시간대별 태양광 고도 및 색온도 데이터가 저장된 저장부;DC 전원을 공급받아 구동하고, 상기 저장부에 저장된 계절 및 시간대별 태양광 고도 및 색온도 데이터에서 현재 날짜와 시간에 대응되는 색온도를 판단하여 구동 제어신호를 전송하는 제어부; 및상기 제어부의 구동 제어신호를 입력받아 상기 엘이디의 온 오프 및 상기 엘이디의 조도를 제어하는 정전류 회로;를 포함하고, 상기 정전류 회로는상기 제1 엘이디와 상기 제2 엘이디를 각각 제어하기 위한 정전류 회로1과 정전류 회로2를 포함하고, 상기 정전류 회로1은 상기 제1 엘이디에 공급되는 전류 출력량을 제어하여 상기 제1 엘이디의 색온도를 제어하고, 상기 정전류 회로2는 상기 제2 엘이디에 공급되는 전류 출력량을 제어하여 상기 제2 엘이디의 조도를 제어하며,상기 제1 엘이디 및 상기 제2 엘이디는 복수 개이고, 상기 제어부는 상기 제1 엘이디와 상기 제2 엘이디를 선택적으로 온 오프시키고, 색온도 및 조도를 제어하여,색온도를 2800K~10000K 범위에서 순차적으로 높이고 낮추고, 상기 제1 엘이디와 상기 제2 엘이디를 점등 및 소등시키며,상기 제어부는 스마트폰 앱과 연결되어 작업자가 수동 조절 또는 자동으로 조절 가능하며, 상기 제어부가 상기 제1 엘이디 및 상기 제2 엘이디를 온 오프시킨 정보 데이터는 상기 스마트폰 앱에 저장되며, 상기 제어부는상기 제1 엘이디 및 상기 제2 엘이디의 점등 및 소등이 춘분 계절의 실외 환경에 대응되도록 06시에 점등하고 19시에 소등하며, 상기 06시에는 상기 제1 엘이디만 점등하고 상기 제2 엘이디는 소등하며,12시에서 13에는 상기 제1 엘이디는 소등하고 상기 제2 엘이디만 점등하며, 18시에는 상기 제1 엘이디는 점등하고 상기 제2 엘이디는 소등하도록 상기 정전류 회로1과 상기 정전류 회로2에 구동 제어신호를 출력하는,곤충사육사용 조명., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

506/1150 Row 506: application_number: 1020200147508, combined_string: invention_title: 수경재배를 이용한 곤충 사육시스템 abstract: 본 발명의 일 실시예에 따른 수경재배를 이용한 곤충 사육시스템은 수경재배용 식물과 사육 대상인 곤충이 서식할 수 있는 서식공간이 구비되는 본체부; 상기 본체부의 하단부에 배치되고, 내부에 상기 수경재배용 식물의 배양을 위한 배양액이 저장되는 재배부; 상기 본체부의 측단부에 배치되고, 서식공간의 온도 및 습도를 감지하여 공조 신호를 출력하는 적어도 하나의 공조센서부; 상기 재배부에 배치되고, 상기 재배부에 저장된 배양액의 수위를 감지하여 수위 신호를 출력하는 수위 조절센서부; 및 상기 본체부 외측에 설치되되, 출력된 공조 신호와 수위 신호를 기반으로 서식공간의 환경을 제어하는 환경 관리부를 포함한다. claims: 수경재배용 식물과 사육 대상인 곤충이 서식할 수 있는 서식공간이 구비되는 본체부;상기 본체부의 하단부에 배치되고, 내부에 상기 수경재배용 식물의 배양을 위한 배양액이 저장되는 재배부;상기 본체부의 측단부에 배치되고, 서식공간의 온도 및 습도를 감지하여 공조 신호를 출력하는 복수 개의 공조센서부;상기 재배부에 배치되고, 상기 재배부에 저장된 배양액의 수위를 감지하여 수위 신호를 출력하는 수위 조절센서부; 및상기 본체부 외측에 설치되되, 출력된 공조 신호와 수위 신호를 기반으로 서식공간의 환경을 제어하는 환경 관리부를 포함하되,상기 환경 관리부는, 상기 배양액을 기 저장하는 배양액 저장부, 상기 서식공간으로 기 설정된 온도 및 기 설정된 습도로 조성된 공기를 공급하거나 상기 재배부로 배양액을 공급하는 유체 펌프부, 및 상기 공조센서부 및 상기 수위 조절센서부와 무선 통신을 통하여 연결되고, 출력된 공조 신호와 수위 신호에 따라 상기 유체 펌프부로 제어 신호를 인가하는 제어부를 포함하고,상기 수위 조절센서부는 저장된 배양액에 침지되고 암모니아, 아질산 및 질산를 포함하는 수질 정보를 감지하여 수질 신호를 출력하고,상기 제어부는 상기 수위 조절센서부로부터 출력된 수질 신호를 기반으로 오염도 수치값을 생성하고, 생성된 오염도 수치값을 기 설정된 오염도 임계수치값과 비교하여 배양액의 오염 상태를 판단하는 수경재배를 이용한 곤충 사육시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

507/1150 Row 507: application_number: 1020200144079, combined_string: invention_title: 애완동물용 배변 처리 가방 abstract: 애완동물의 배변 처리용 물품을 용이하고 효과적으로 수납하며 휴대와 사용이 간편하도록, 양 측단이 접합되어 내부에 수용 공간을 형성하는 전면판과 후면판을 포함하는 본체, 상기 본체에 설치된 고리에 착탈가능하게 결합되는 스트랩을 포함하고, 상기 본체의 상단은 개방되어 입구를 형성하며, 하단은 개방되어 출구를 형성하고, 상기 본체 하단에는 출구를 선택적으로 개폐하는 개폐부가 마련되어, 상기 본체의 입구를 통해 내부에 수용된 물품을 하단의 출구를 통해 배출하는 구조의 애완동물용 배변 처리 가방을 제공한다. claims: 양 측단이 접합되어 내부에 수용 공간을 형성하는 전면판과 후면판을 포함하는 본체, 상기 본체에 설치된 고리에 착탈가능하게 결합되는 스트랩을 포함하고,상기 본체의 상단은 개방되어 입구를 형성하며, 하단은 개방되어 출구를 형성하고, 상기 본체 하단에는 출구를 선택적으로 개폐하는 개폐부가 마련되어, 상기 본체의 입구를 통해 내부에 수용된 물품을 하단의 출구를 통해 배출하는 구조이고,상기 본체는 상단에 설치되어 상기 본체의 상하방향 길이를 선택적으로 확장하는 연장부를 더 포함하고,상기 연장부는 측단이 접합되고 양 선단은 개방되며 상하방향으로 연장된 길이를 갖는 확장포를 포함하고,상기 확장포는 상기 본체의 내면 크기에 대응되는 크기로 형성되고, 일측 선단은 상기 본체 상단의 내측 둘레를 따라 접합되어 고정되고 타측 선단은 자유단을 이루어 필요시 상기 본체 내부로 삽입되거나 외측으로 인출되고, 자유단인 타측 선단에는 조임끈이 설치되어 선단을 선택적으로 조여주는 구조의 애완동물용 배변 처리 가방., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

508/1150 Row 508: application_number: 1020200138452, combined_string: invention_title: 양봉 벌통에 토봉 사용을 위한 겸용판 abstract: 개시된 본 발명에 따른 양봉 벌통에 토봉 사용을 위한 겸용판은, 벌통의 일측 대향면에 각각 대칭 결합되는 겸용판으로서, 상기 벌통의 타측 대향면의 거리와 대응되는 길이로 형성되며, 전면 상부에 소비의 단부가 안착되도록 안착돌기가 형성된 몸체부; 및 상기 몸체의 하부에 결합되어 상기 일측 대향면과의 틈을 없애는 틈상쇄부;를 포함한다.본 발명에 의하면, 양봉 벌통의 일측 대향면에 각각 몸체부가 결합되어 전면 상부에 형성된 안착돌기에 토봉시 사용되는 소비의 양단이 걸리게 하고, 양봉시 사용되는 소비는 겸용판을 양벌 벌통에서 분리한 상태로 양봉 벌통의 일측 대향면에 형성된 안착돌기부에 양단이 걸리게 하여 겸용판의 설치 여부에 따라 양봉 벌통을 토봉에 겸용으로 사용 가능한 효과가 있다. claims: 벌통의 일측 대향면에 각각 대칭 결합되는 겸용판으로서,상기 벌통의 타측 대향면의 거리와 대응되는 길이로 형성되며, 전면 상부에 소비의 단부가 안착되도록 안착돌기가 형성된 몸체부; 및상기 몸체의 하부에 결합되어 상기 일측 대향면과의 틈을 없애는 틈상쇄부;를 포함하는 것을 특징으로 하는 양봉 벌통에 토봉 사용을 위한 겸용판., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

509/1150 Row 509: application_number: 1020200122940, combined_string: invention_title: 곤충 사육 및 식물 재배를 위한 디바이스 abstract: 본 발명은 곤충 사육 및 식물 재배를 위한 디바이스에 관한 것이다.본 발명은 이를 위해 곤충 사육 및 식물 재배를 위한 디바이스(100)에, 복수개의 공급개별함(141)을 수용하는 공급전체함(140)과, 각 공급개별함(141)을 통해 배출되는 물이나 먹이를 곤충이나 식물이 내장된 상자(101) 내부에 자동으로 정량 공급하여 곤충이나 식물이 자라는 최적의 환경을 제공할 수 있도록 한 정량공급장치(110); 상기 정량공급장치(110)의 일측에 구비되며, 중앙의 사육 및 재배장치 구동부(160)를 중심으로 각각 승하강 작동되도록 좌우측에 각각 하강이송장치(180)와 승강이송장치(170)가 구비된 사육 및 재배장치(150); 및 상기 승강이송장치(170)는 정량공급장치(110)의 일측에 구비되며, 정량공급장치(110)를 통해 공급된 상자(101)를 상부로 순차적으로 이송시킴과 아울러 최상단으로 올라간 상자(101)를 타측 하강이송장치(180)로 이송시키고, 상기 하강이송장치(180)는 이송된 상자(101)를 하부로 순차적으로 이송시킴과 아울러 하강된 상자(101)를 다시 일측 승강이송장치(170)로 이송시킴을 특징으로 하는 곤충 사육 및 식물 재배를 위한 디바이스를 제공한다.상기와 같이 구성된 본 발명은 각종 곤충(예: 동애등애, 거저리, 귀뚜라미, 굼벵이 등)이나 각종 식물(예: 버섯 등)의 사육 및 재배기간 동안 곤충 및 식물이 하나의 디바이스를 통해 효율적으로 사육 및 재배될 수 있도록 한 것이다. claims: 곤충이나 식물의 사육 및 재배기간 동안 곤충 및 식물이 하나의 디바이스를 통해 효율적으로 사육 및 재배될 수 있도록 한 곤충 사육 및 식물 재배를 위한 디바이스(100)를 제공하는 것으로, 상기 곤충 사육 및 식물 재배를 위한 디바이스(100)는, 복수개의 공급개별함(141)을 수용하는 공급전체함(140)과, 각 공급개별함(141)을 통해 배출되는 물이나 먹이를 곤충이나 식물이 내장된 상자(101) 내부에 자동으로 정량 공급하여 곤충이나 식물이 자라는 최적의 환경을 제공할 수 있도록 한 정량공급장치(110); 상기 정량공급장치(110)의 일측에 구비되며, 중앙의 사육 및 재배장치 구동부(160)를 중심으로 각각 승하강 작동되도록 좌우측에 각각 하강이송장치(180)와 승강이송장치(170)가 구비된 사육 및 재배장치(150); 및 상기 승강이송장치(170)는 정량공급장치(110)의 일측에 구비되며, 정량공급장치(110)를 통해 공급된 상자(101)를 상부로 순차적으로 이송시킴과 아울러 최상단으로 올라간 상자(101)를 타측 하강이송장치(180)로 이송시키고, 상기 하강이송장치(180)는 이송된 상자(101)를 하부로 순차적으로 이송시킴과 아울러 하강된 상자(101)를 다시 일측 승강이송장치(170)로 이송시키도록 구성되고,상기 정량공급장치(110)는, 정량공급장치몸체(111); 정량공급장치몸체(111)의 일측에 구비되며, 제1구동모터(121)의 구동에 의해 구동축(122)과 체인풀리(123)를 구동하고, 제2구동모터(125)의 구동에 의해 회동축(126)을 구동하는 정량공급장치구동부(120); 및 정량공급장치몸체(111)의 상단에 일정 간격으로 복수개가 구비되며, 상자(101)를 이송을 돕고, 회전시 상자의 이탈을 방지하는 상자지지브라켓트(130);가 포함됨을 특징으로 하는 곤충 사육 및 식물 재배를 위한 디바이스., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

510/1150 Row 510: application_number: 1020200120573, combined_string: invention_title: 곤충 분변을 활용하여 식물을 재배하기 위한 식용곤충 사육장치 및 그 방법 abstract: 본 발명은 곤충 분변을 활용하여 식물을 재배하기 위한 식용곤충 사육장치 및 그 방법에 관한 것이다. 상기 장치는, 높이를 갖고 연장되는 프레임; 식물을 재배하기 위한 양액이 저장되는 양액보관탱크; 양액을 생성하여 상기 양액보관탱크에 제공하는 양액생성기; 상기 프레임에 의해 복수의 높이에서 지지되며, 바닥면과 측면들로 둘러싸인 내부 공간이 형성된 복수의 곤충사육트레이; 상기 프레임에 의해 복수의 높이에서 지지되며, 상기 곤충사육트레이와 서로 다른 높이에 배치되는 복수의 식물재배트레이; 상기 양액보관탱크와 상기 각각의 식물재배트레이를 연결하는 제1 파이프; 및 상기 각각의 곤충사육트레이와 상기 양액생성기를 연결하는 제2 파이프를 포함할 수 있다. claims: 높이를 갖고 연장되는 프레임;식물을 재배하기 위한 양액이 저장되는 양액보관탱크;양액을 생성하여 상기 양액보관탱크에 제공하는 양액생성기;상기 프레임에 의해 복수의 높이에서 지지되며, 바닥면과 측면들로 둘러싸인 내부 공간이 형성된 복수의 곤충사육트레이;상기 프레임에 의해 복수의 높이에서 지지되며, 상기 곤충사육트레이와 서로 다른 높이에 배치되는 복수의 식물재배트레이;상기 양액보관탱크와 상기 각각의 식물재배트레이를 연결하는 제1 파이프;상기 양액생성기의 상측으로 연장되어 상기 각각의 곤충사육트레이와 상기 양액생성기를 연결하는 제2 파이프; 및상기 양액생성기의 하측으로 연장되어 상기 양액생성기와 상기 양액보관탱크를 연결하는 제3 파이프를 포함하되,상기 곤충사육트레이의 바닥면은 상기 제2 파이프가 연결되는 측을 향하여 하측으로 경사지게 형성되며,상기 양액생성기의 내부 공간은 상기 제3 파이프에 연결되는 부분이 상기 제3 파이프 측으로 직경이 점차 작아지도록 테이퍼지게 형성되어, 상기 곤충사육트레이로부터 상기 제2 파이프를 통해 배출되는 곤충 분변은 병목 현상에 의해 일부가 상기 양액생성기에 보관되며,상기 양액생성기는 물관을 통해 물탱크에 연결되고, 상기 물탱크로부터 곤충 분변을 용액화하여 양액을 생성하기 위한 물을 제공받으며, 상기 물관에는 상기 양액생성기로 전달되는 물의 양을 조절 가능한 밸브가 구비되어, 상기 양액생성기로 제공되는 물은 상기 양액생성기 내부에서 상기 곤충 분변과 혼합되어 양액을 생성하고, 생성된 양액이 상기 제3 파이프를 통해 상기 양액보관탱크에 전달되는 것을 특징으로 하는, 곤충 분변을 활용하여 식물을 재배하기 위한 식용곤충 사육장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

511/1150 Row 511: application_number: 2020200003045, combined_string: invention_title: 다기능 벌통 내검보조기 abstract: 본 발명의 일 실시예에 따른 다기능 벌통 내검보조기는 내부에 복 수의 벌집틀이 일렬로 적층되는 벌통본체와, 상기 벌통본체의 상부를 덮어 내부를 밀폐시키는 벌통뚜껑을 포함하고, 상기 벌통본체와 벌통뚜껑 사이에 안내공간이 형성된 복 수개의 벌통이 수직으로 적층되는 벌통부를 내검하는 벌통 내검보조기에 있어서, 지면에 놓여지는 받침대와, 상기 받침대의 중앙에 배치되며 수직으로 세워지는 수직대가 구비되는 수직지지부; 상기 수직지지부의 수직대 외측면에 삽입되며, 상기 수직대의 길이방향으로 상하 이동되고, 회전고정구의 회전에 의해 설정높이에 고정되는 수직이동부; 일단이 상기 수직이동부의 후면에 연결되며, 상기 수직지지부의 받침대와 평행하게 배치되는 고정대와, 상기 고정대의 양단에 직각을 이루도록 수평되게 결합되는 한 쌍의 안착대가 구비되는 수평지지부; 및 상기 한 쌍의 안착대 사이에 연결되며, 하부 일측과 타측에 설정간격으로 이격되어 고정되는 보조거치부;를 포함하며, 상기 수직이동부의 후면과 수평지지부의 하부 일단이 회전식브라켓으로 결합되어 상기 수직이동부와 수평지지부가 접철되거나 직각으로 펼쳐지고, 상기 수평지지부의 안착대가 상기 벌통부 중에서 선택되는 어느 하나의 상기 안내공간에 삽입된 상태에서 상기 벌집틀이 상기 보조거치부에 걸쳐지거나, 상기 안착대의 상부에 배치된 상기 벌통부가 상기 수평지지부로 수평 이동된다. claims: 내부에 복 수의 벌집틀이 일렬로 적층되는 벌통본체와, 상기 벌통본체의 상부를 덮어 내부를 밀폐시키는 벌통뚜껑을 포함하고, 상기 벌통본체와 벌통뚜껑 사이에 안내공간이 형성된 복 수개의 벌통이 수직으로 적층되는 벌통부를 내검하는 벌통 내검보조기에 있어서, 지면에 놓여지는 받침대와, 상기 받침대의 중앙에 배치되며 수직으로 세워지는 수직대가 구비되는 수직지지부;상기 수직지지부의 수직대 외측면에 삽입되며, 상기 수직대의 길이방향으로 상하 이동되고, 회전고정구의 회전에 의해 설정높이에 고정되는 수직이동부;일단이 상기 수직이동부의 후면에 연결되며, 상기 수직지지부의 받침대와 평행하게 배치되는 고정대와, 상기 고정대의 양단에 직각을 이루도록 수평되게 결합되는 한 쌍의 안착대가 구비되는 수평지지부; 및상기 한 쌍의 안착대 사이에 연결되며, 하부 일측과 타측에 설정간격으로 이격되어 고정되는 보조거치부;를 포함하며,상기 수직이동부의 후면과 수평지지부의 하부 일단이 회전식브라켓으로 결합되어 상기 수직이동부와 수평지지부가 접철되거나 직각으로 펼쳐지고, 상기 수평지지부의 안착대가 상기 벌통부 중에서 선택되는 어느 하나의 상기 안내공간에 삽입된 상태에서 상기 벌집틀이 상기 보조거치부에 걸쳐지거나, 상기 안착대의 상부에 배치된 상기 벌통부가 상기 수평지지부로 수평 이동되는 것을 특징으로 하는 다기능 벌통 내검보조기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

512/1150 Row 512: application_number: 1020200098305, combined_string: invention_title: 탈출방지부재를 갖춘 곤충 사육상자 abstract: 본 발명은 탈출방지부재를 갖춘 곤충 사육상자에 관한 것으로; 이의 목적은 다단으로 적재할 수 있는 사육상자의 내부 벽면 구조를 개선하여 사육 곤충이 벽면을 타고 올라가 환기홀(또는 손잡이 홀)을 통해 탈출하는 것을 방지할 수 있도록 하는 것이다.이를 위해 본 발명에 따른 『탈출방지부재를 갖춘 곤충 사육상자』에 의하면; 바닥면(310)과 벽면(320)을 구비하여 내부에 사육곤충과 먹이를 수용할 수 있도록 서식공간이 마련되며 상부가 개방된 사육상자 본체(300)와; 상기 사육상자 본체(300)의 벽면(320) 상부에 가로방향으로 연장된 복수개의 환기홀(400)과; 상기 사육상자 본체(300)의 벽면(320) 중앙부위 내측을 따라 부착되는 띠 형태의 부착부(510)와, 상기 부착부(510)에서 상기 사육상자 본체(300)의 내부 서식공간을 향해 수평방향으로 연장되어 사육곤충이 상기 사육상자 본체(300)의 벽면(320)을 타고 상측으로 올라가는 것을 방지하기 위한 띠 형태의 탈출방지부(520)로 이루어진 탈출방지부재(500)를; 포함하는 것을 특징으로 한다. claims: 바닥면(310)과 벽면(320)을 구비하여 내부에 사육곤충과 먹이를 수용할 수 있도록 서식공간이 마련되며 상부가 개방된 사육상자 본체(300)와;상기 사육상자 본체(300)의 벽면(320) 상부에 가로방향으로 연장된 복수개의 환기홀(400)과;상기 사육상자 본체(300)의 벽면(320) 중앙부위 내측을 따라 부착되는 띠 형태의 부착부(510)와, 상기 부착부(510)에서 상기 사육상자 본체(300)의 내부 서식공간을 향해 수평방향으로 연장되어 사육곤충이 상기 사육상자 본체(300)의 벽면(320)을 타고 상측으로 올라가는 것을 방지하기 위한 띠 형태의 탈출방지부(520)로 이루어진 탈출방지부재(500)를; 포함하는 것을 특징으로 하는 탈출방지부재를 갖춘 곤충 사육상자., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

513/1150 Row 513: application_number: 1020200091162, combined_string: invention_title: 애완동물 배변 자동 처리 장치 abstract: 본 발명은 간단한 구조로 배변을 처리한 배변 패드가 밀폐되도록 하여 악취 및 위생문제가 적절히 해소되도록 하고 대변과 소변을 구분하여 감지함으로써 배변 패드의 불필요한 낭비가 방지되도록 하는 애완동물 배변 자동 처리 장치에 관한 것으로, 본 배변 자동 처리 장치는 제1 본체(10)와, 상기 제1 본체(10)의 일측에 이격되게 구비되는 제2 본체(20)와, 상기 제1 본체(10)의 내부에 설치되는 처리구동부(30)와, 상기 제2 본체(20)의 내측에 구비되는 권취롤(40)과, 상기 권취롤(40)에 감기어 구비되는 배변 패드(50)와, 상기 제1 본체(10)와 제2 본체(20)의 사이에 한 쌍으로 구비되는 가이드판(60)과, 상기 제1 본체(10)의 외면에 설치되는 카메라(70)와, 상기 제1 본체(10)와 제2 본체(20)의 사이에 장착되는 하부지지판(80)과, 상기 제1 본체(10)에 설치되고 상기 배변 패드(50)의 상면을 지지하는 패드지지부(90)와, 상기 제1 본체(10)의 외면에 설치되는 엘이디(100)와, 상기 하나의 가이드판(60)의 상면에 수직으로 장착되는 격벽(110)을 포함한다. claims: 직사각판으로 구비되는 제1 베이스(11)와, 상기 베이스의 상면 둘레에 장착되는 둘레판(12)과, 상기 둘레판(12)의 상단에 개폐 가능하게 힌지 결합되는 제1 커버(13)와, 상기 둘레판(12)과 제1 커버(13)의 일측에 관통되게 형성되는 유입구(14)를 포함하는 제1 본체(10)와;상기 제1 베이스(11)의 일측으로 이격되게 구비되고 직사각판으로 형성되는 제2 베이스(21)와, 상기 제2 베이스(21)의 상면을 커버하도록 하부가 개방된 중공 입방체 형태로 구비되고 상기 제2 베이스(21)의 상면에 분해 가능하게 끼워지는 제2 커버(22)와, 상기 제2 커버(22)의 타측 하부에 관통되게 형성되는 배출구(23)를 포함하는 제2 본체(20)와;상기 제1 커버(13)의 내측으로 상기 제1 베이스(11)의 상면에 설치되고, 상기 유입구(14)를 통해 유입되는 배변 패드(50)를 감아서 처리하는 처리구동부(30)와;상기 제2 커버(22)의 내측으로 상기 제2 베이스(21)의 상면에 회전 가능하게 설치되는 권취롤(40)과;상기 권취롤(40)에 권취되고, 일단이 상기 처리구동부(30)와 연결되는 배변 패드(50)와;상기 제1 베이스(11)와 제2 베이스(21)의 내측 사이에 상호 이격되게 구비되고, 상기 처리구동부(30)와 권취롤(40)의 사이에 구비되는 상기 배변 패드(50)의 이동을 가이드하는 한 쌍의 가이드판(60)과;상기 제1 커버(13)의 외면에 설치되고, 상기 가이드판(60) 사이에 배치되는 상기 배변 패드(50)의 상면을 촬영하여 대변과 소변을 구별하는 카메라(70)와;상기 제1 베이스(11)와 제2 베이스(21)의 사이에 조립되어 연결되고, 상기 가이드판(60)의 하부로 상기 배변 패드(50)의 하면을 지지하는 하부지지판(80)을; 포함하고,상기 처리구동부(30)는,상기 배변 패드(50)의 양단에 대응하여 상기 제1 커버(13)의 내측으로 상기 제1 베이스(11)의 상면에 상호 이격되게 장착되고 하부측이 개구된 원호형으로 형성되는 한 쌍의 호형가이드(31)와,상기 호형가이드(31)의 외측으로 상기 제1 베이스(11)의 상면에 각각 장착되고 내부에 다수개의 기어가 연결되는 한 쌍의 기어박스(32)와,각각의 상기 기어박스(32)와 연결되어 회전되는 한 쌍의 회전축(33)과,상기 호형가이드(31)의 내측에 구비되고 각각의 상기 회전축(33)에 연결되는 한 쌍의 처리롤러(34)와,상기 처리롤러(34)의 외주면에 다수개가 방사상으로 돌출되게 장착되고 고무 재질로 형성되는 고무블레이드(34a)와,하나의 상기 기어박스(32)에 장착되고 상기 기어박스(32)에 연결되어 상기 처리롤러(34)를 시계방향으로 회전시키는 모터(35)와,상기 제1 베이스(11)의 상면에서 하부로 함몰된 상태로 상단이 노출되면서 회전 가능하게 구비되고 상기 기어박스(32)에 각각 연결되어 상기 모터(35)의 구동과 함께 반시계방향으로 회전되면서 상기 배변 패드(50)를 상기 제1 본체(10)의 내측으로 밀어 넣는 한 쌍의 하부롤러(36)를, 포함하고,상기 처리롤러(34)는,상기 회전축(33)에 분리되어 상기 회전축(33)을 따라 수평으로 이동 가능하게 구비되고,상기 처리구동부(30)는,상기 호형가이드(31)의 사이로 상기 제1 베이스(11)의 상면 중앙에 장착되고 호형으로 형성되며 상기 배변 패드(50)의 권취를 지지하는 호형지지부재(37)와,상기 처리롤러(34)의 내측면에 각각 부착되고 상기 고무블레이드(34a)보다 상대적으로 작은 직경을 가지며 상기 배변 패드(50)의 권취를 지지하는 한 쌍의 지지원판(38)과,상기 처리롤러(34)에 설치되고 상기 처리롤러(34)를 상기 회전축(33)을 따라 외측으로 탄성복원 가능하게 이동시킬 수 있는 탄성이동부(39)를, 더 포함하고,상기 탄성이동부(39)는,상기 기어박스(32)의 내측면과 상기 처리롤러(34)의 외측면 사이로 상기 회전축(33)에 끼워져 상기 처리롤러(34)를 탄성적으로 지지하는 스프링(391)과,상기 처리롤러(34)의 외측면에 다각형으로 형성되는 다각형홈(392)과,상기 지지원판(38)의 중앙부위에서 외측으로 돌출되게 형성되고 상기 다각형홈(392)에 분리 가능하게 끼워지는 다각형턱(393)과,상기 다각형턱(393)의 내측면에 구비되고 상기 다각형턱(393)을 관통하는 상기 회전축(33)의 단부에 부착되는 고정캡(394)을, 포함하는 것을 특징으로 하는 애완동물 배변 자동 처리 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

514/1150 Row 514: application_number: 1020200089702, combined_string: invention_title: 스마트 목줄을 이용한 애완동물 관리 시스템 abstract: 본 발명의 실시 예에 따른 스마트 목줄을 이용한 애완동물 관리 시스템은, 애완동물의 신체 움직임과 신체 정보를 측정하여 운동감지신호 및 생체 신호를 생성하고, 생성된 운동감지신호와 생체신호를 분석하여 상기 애완동물의 건강 상태를 판단하는 스마트 목줄과, 애완동물 관리 어플리케이션이 실행되며, 상기 스마트 목줄과의 무선통신을 통해 애완동물 정보를 수신하여 화면상에 표시하는 사용자 단말을 포함한다. claims: 애완동물의 신체 움직임과 신체 정보를 측정하여 운동감지신호 및 생체 신호를 생성하고, 생성된 운동감지신호와 생체신호를 분석하여 상기 애완동물의 건강 상태를 판단하는 스마트 목줄; 및애완동물 관리 어플리케이션이 실행되며, 상기 스마트 목줄과의 무선통신을 통해 애완동물 정보를 수신하여 화면상에 표시하는 사용자 단말을 포함하고,상기 스마트 목줄은,상기 애완동물의 신체의 일부를 감싸도록 착용되는 몸체부;상기 몸체부의 일면에 부착되어 상기 몸체부가 수축 및 팽창되는 정도를 감지하여 상기 운동감지신호를 생성하고, 상기 애완동물의 심박수, 체온, 혈압, 및 심호흡 상태 중 적어도 하나를 측정하여 상기 생체신호를 생성하는 센서부; 상기 운동감지신호를 기초로 상기 몸체부가 수축 및 팽창을 반복하는 경우 상기 애완동물이 운동 상태에 있는 것으로 판단하여 상기 애완동물의 운동량을 판단하고, 상기 생체신호를 분석하여 상기 애완동물의 건강 상태를 판단하는 제어부; 및상기 사용자 단말과 무선통신을 수행하는 통신부를 포함하며, 상기 제어부는 상기 몸체부가 기준 크기 미만의 상태로 기설정된 시간을 유지하는 동안에 상기 애완동물의 심박수, 체온, 혈압, 및 심호흡 상태 중 적어도 하나가 정상 상태를 벗어난 경우 상기 애완동물의 건강상태를 상태이상으로 판단하고, 상기 몸체부가 기준 크기 이상의 상태에서 상기 애완동물의 심박수, 체온, 혈압, 및 심호흡 상태 중 어느 하나가 정상 상태를 벗어난 경우 상기 애완동물의 건강상태를 정상상태로 판단하고,상기 사용자 단말은,상기 애완동물이 운동상태에 있는 경우, 상기 애완동물 정보에 포함된 GPS 정보를 기초로 상기 애완동물이 이동한 산책거리를 계산하고, 기저장된 지도에 상기 애완동물의 이동경로를 표시하는 애완동물 관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

515/1150 Row 515: application_number: 1020200088920, combined_string: invention_title: 실험용 동물 케이지 abstract: 본 발명은 실험용 동물 케이지에 관한 것으로, 폴리카보네이트(Polycarbonate) 재질로 형성되고, 상단이 개방된 내부공간을 가지며, 상단 테두리에 일정 간격으로 결합돌기가 형성된 본체; 상기 본체와 동일한 재질로 형성되고, 상기 본체의 상단에 지지되며, 테두리에 상기 결합돌기가 삽입되도록 삽입공이 형성되고, 상단에 손잡이가 형성된 상판; 및 상기 본체에 결합된 상판을 고정시키기 위해 상기 결합돌기와 체결되는 고정부재;를 포함한다. 이러한 구성으로, 본체 및 상판이 폴리카보네이트(Polycarbonate) 재질로 형성됨으로써, 세척 후 멸균이 가능하여 위색정이며, 견고한 케이지를 제공할 수 있는 효과를 얻을 수 있다. claims: 폴리카보네이트(Polycarbonate) 재질로 형성되고, 상단이 개방된 내부공간을 가지며, 상단 테두리에 일정 간격으로 결합돌기가 형성된 본체;상기 본체와 동일한 재질로 형성되고, 상기 본체의 상단에 지지되며, 테두리에 상기 결합돌기가 삽입되도록 삽입공이 형성되고, 상단에 손잡이가 형성된 상판; 및상기 본체에 결합된 상판을 고정시키기 위해 상기 결합돌기와 체결되는 고정부재;를 포함하고,상기 본체의 상단 각 꼭지점에는 상기 상판의 하단 꼭지점이 지지되고, 상기 상판 둘레의 각 꼭지점에 형성된 걸림홈이 결합되는 걸림턱이 형성되며,상기 본체는 외측벽이 상방으로 갈수록 벌어지는 형상으로 형성되고,상기 본체의 외측면 상면에 상기 상판이 지지되며,상기 본체의 내측 하면에는 먹이통 또는 급수통이 거치 가능하도록 고정포트가 형성되고,상기 고정포트의 일측은 단차가 형성되도록 일부 개방되며,상기 고정포트는 상기 본체의 내측 하면에 탈착 가능하게 구비되고,상기 본체의 내측 하면에는 상기 고정포트가 하방으로부터 삽입 가능하도록 고정홀이 형성되며,상기 본체의 하면 중 상기 고정홀과 인접한 위치에 이동홈이 형성되고, 상기 이동홈에는 이동부재가 이동 가능하게 결합되며, 상기 이동부재에는 암나사산이 형성되고, 상기 이동홈의 내측에는 상기 이동부재와 연결된 스프링이 결합되며,상기 고정포트의 하단에는 상기 고정홀의 직경보다 크게 형성된 고정판이 형성되고, 상기 고정판 상단 중 상기 이동홈과 마주보는 위치에는 제1 홀이 형성되고, 상기 고정판의 일측면에는 상기 제1 홀과 직교되도록 제2 홀이 형성되며,상기 제1 홀에는 제1 핀이 결합되고, 상기 제2 홀에는 제2 핀이 결합되며,상기 제1 핀은 일측이 외부로 돌출되고 돌출된 부분에는 상기 암나사산과 나사 결합되는 수나사산이 형성되며 타측이 상기 제2 홀과 직교되는 부분에 제1 베벨기어가 형성되고,상기 제2 핀은 일측이 외부로 돌출되고 타측이 상기 제1 베벨기어와 맞물리도록 제2 베벨기어가 형성되어,상기 고정포트가 상기 본체에 나사 결합되고,상기 본체의 측벽은 상방으로 갈수록 두꺼워지는 형상을 가지며,상기 본체의 측벽 일측에는 제1 통기공이 형성되고,상기 상판의 상면 양측에는 제2 통기공이 형성되는 것을 특징으로 하는 실험용 동물 케이지., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

516/1150 Row 516: application_number: 1020200070150, combined_string: invention_title: 애꽃노린재류 무식물 증식 시스템 abstract: 본 발명은 애꽃노린재류 무식물(plant-less) 증식 시스템 및 애꽃노린재류 무식물(plant-less) 증식 방법에 관한 것으로서, 보다 상세하게는 식물 대체 채란용 물체, 대체먹이 및 사육 환경 최적화를 갖춘 애꽃노린재류 대량 증식 시스템 및 상기 시스템을 이용한 애꽃노린재류 대량 증식 방법에 관한 것이다. 본 발명에 따른 애꽃노린재류 무식물(plant-less) 증식 시스템은 국내 토착 천적인 참멋애꽃노린재(Orius minutus)의 적합한 환경요인 확인, 식물을 대체할 수 있는 채란용 물체 선발 및 경제적인 대체먹이 선발을 통해 기존 사육 시스템 대비 생산 공정 간소화 및 경제적인 생산 시스템 구축이 가능하다. claims: 환기구가 있는 사육 용기; 및상기 사육 용기 내부에,물 및 꿀물을 포함하는 수분 공급부;두께 3 ~ 5 mm이고 거친 면(rough side)을 갖는 코르크를 포함하는 채란부; 및명나방알과 철분이 코팅된 브라인쉬림프(Iron-coated brine shrimp)를 포함하는 먹이 공급부;를 포함하고,상기 사육 용기 외부에,온도, 상대습도 및 광주기를 조절하는 조절부를 포함하는 것을 특징으로 하는,애꽃노린재류 무식물(plant-less) 증식 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

517/1150 Row 517: application_number: 1020200068825, combined_string: invention_title: 산란장 abstract: 본 발명은 산란장 관리를 위해 내부로 들어가지 않아도 외부에서 관리할 수 있도록 함으로써, 산란장의 운영 관리가 수월하고 산란유도배지의 효과를 높일 수 있는 산란장을 제공하기 위한 것으로서, 성충들이 탈출하지 못하도록 제한된 공간을 만드는 망부재(100)와, 터널식(서랍식) 틀을 구비하고, 상기 터널식(서랍식) 틀을 통해 슬라이딩되어 상기 공간의 외부에서 수납되는 적어도 하나 이상의 리빙박스(400) 및 산란목 박스(300)를 보관하는 제1, 2 보관부(120)(130)와, 상기 망부재(100) 내부 공간 바닥면에 일측으로 일정한 경사각을 가지도록 구비되어, 산란장 내부에 쌓이는 성충사체들이 일측으로 이동되도록 유도하는 슬라이딩 유도부(140)와, 상기 일측에 구비되어, 상기 슬라이딩 유도부(140)에서 일측으로 이동되는 성충사체들을 포집하는 사체 포집부(150)를 포함할 수 있다. claims: 성충들이 탈출하지 못하도록 제한된 공간을 만드는 망부재(100)와, 터널식(서랍식) 틀을 구비하고, 상기 터널식(서랍식) 틀을 통해 슬라이딩되어 상기 공간의 외부에서 수납되는 적어도 하나 이상의 리빙박스(400) 및 산란목 박스(300)를 보관하는 제1, 2 보관부(120)(130)와, 상기 망부재(100) 내부 공간 바닥면에 일측으로 일정한 경사각을 가지도록 구비되어, 산란장 내부에 쌓이는 성충사체들이 일측으로 이동되도록 유도하는 슬라이딩 유도부(140)와,상기 일측에 구비되어, 상기 슬라이딩 유도부(140)에서 일측으로 이동되는 성충사체들을 포집하는 사체 포집부(150)를 포함하고,상기 슬라이딩 유도부(140)는 망부재(100)의 뒷면 벽과 상기 망부재(100)의 앞면에 위치하는 사체 포집부(150)와 일정한 경사각으로 구비되며, 상기 망부재(100)의 뒷면 벽과 연결되는 끝단부에 모터의 회전을 통해 진동을 발생시켜, 상기 발생되는 진동을 상기 슬라이딩 유도부(140)로 전달하여 상하 및 좌우방향으로 털어내는 효과를 제공하여 상기 슬라이딩 유도부(140)의 상부에 위치하는 성충사체를 하부의 사체 포집부(150)로 이동시키는 진동부(141)를 더 포함하며,상기 리빙박스(400) 및 산란목 박스(300)는 전면부를 오픈된 상부부터 중심부까지 일정한 기울기를 갖는 사선 형태로 구성하여 전면부의 일부가 오픈되는 산란장., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

518/1150 Row 518: application_number: 1020200064707, combined_string: invention_title: 유충 사육 장치 및 방법 abstract: 본 발명은 유충 사육 방법에 관한 것으로, 사육 공간에 유충과 기본 먹이가 투입된 트레이를 반입하는 과정; 상기 유충을 사육하는 과정; 상기 사육 공간에서 외부로 상기 트레이를 반출하는 과정; 반출된 트레이에 보충 먹이를 투입하는 과정; 및 보충 먹이가 투입된 트레이를 상기 사육 공간에 재반입하는 과정;을 포함하여, 사육 공간의 유지 관리를 용이하게 하여 작업자의 업무 부담을 경감시킬 수 있고, 유지 관리 비용을 절감할 수 있다. claims: 유충을 사육할 수 있는 공간을 제공하는 사육부; 유충이 수용되는 트레이에 보충 먹이를 투입할 수 있도록, 상기 사육부의 외부에 설치되는 보충부;상기 사육부의 외부에 설치되고, 상기 사육부에 반입 및 반출시키기 위해 상기 트레이를 이송시킬 수 있는 이송부; 상기 사육부의 외부에 설치되고, 트레이에 유충과, 상기 유충이 먹을 기본 먹이를 투입하기 위한 트레이 셋팅부; 및상기 보충부와 상기 이송부의 동작을 제어하기 위한 제어부;를 포함하고, 상기 트레이 셋팅부는,상기 트레이에 유충을 투입하기 위한 유충 공급기; 및 상기 트레이에 상기 유충이 먹을 기본 먹이를 상기 트레이에 투입하기 위한 기본 먹이 공급기;를 포함하며,상기 유충 공급기는,유충을 저장할 수 있는 공간을 형성하는 유충 저장기;유충의 배출량을 조절하기 위해 상기 유충 저장기에 형성되는 배출기;상부가 개방되고, 상기 유충 저장기의 하부에 설치되는 용기; 및상기 용기를 회전시킬 수 있도록 지지하는 지지대;를 포함하는 유충 사육 장치.유충을 사육하는 방법으로서, 트레이에 기본 먹이를 투입하는 과정;기본 먹이가 투입된 트레이에 유충을 투입하는 과정;사육 공간에 유충과 기본 먹이가 투입된 트레이를 반입하는 과정;상기 유충을 사육하는 과정;상기 사육 공간에서 외부로 상기 트레이를 반출하는 과정; 반출된 트레이에 보충 먹이를 투입하는 과정; 및보충 먹이가 투입된 트레이를 상기 사육 공간에 재반입하는 과정;을 포함하고, 상기 기본 먹이를 투입하는 과정은, 상기 트레이에 미리 설정된 무게의 기본 먹이를 투입하는 과정을 포함하고, 상기 유충을 투입하는 과정은, 상기 유충의 무게를 측정하는 과정 및 상기 트레이에 투입된 기본 먹이의 무게에 따라 정해지는 무게의 유충을 트레이에 투입하는 과정을 포함하는 유충 사육 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

519/1150 Row 519: application_number: 1020200055015, combined_string: invention_title: 식용곤충용 사육 장치 abstract: 식용곤충용 사육 장치가 개시된다. 본 발명의 일 측면에 따르면, 연속하여 배치되는 복수의 단위 프레임을 포함하며 식용곤충 사육이 가능한 사육 공간을 형성하는 본체, 식용곤충이 이동 가능한 면을 형성하기 위해 복수의 단위 프레임에 설치되는 사육망, 및 본체에 설치되어 사육 공간의 부피를 조절하기 위해 본체의 길이를 조절하는 길이 조절 유닛을 포함하는 식용곤충용 사육 장치가 제공된다. claims: 연속하여 배치되는 복수의 단위 프레임을 포함하며 식용곤충 사육이 가능한 사육 공간을 형성하는 본체;상기 식용곤충이 이동 가능한 면을 형성하기 위해 상기 복수의 단위 프레임에 설치되는 사육망; 및상기 본체에 설치되어 상기 사육 공간의 부피를 조절하기 위해 상기 본체의 길이를 조절하는 길이 조절 유닛을 포함하는 식용곤충용 사육 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

520/1150 Row 520: application_number: 1020200055016, combined_string: invention_title: 식용곤충용 액체사료 공급 장치 abstract: 식용곤충용 액체사료 공급 장치가 개시된다. 본 발명의 일 측면에 따르면, 내부에 식용곤충용 액체사료를 저장하는 사료 저장부, 및 식용곤충용 액체사료를 흡수 가능한 재질로 이루어지며, 일측이 사료 저장부 내부에 설치되어 식용곤충용 액체사료를 흡수하는 사료 공급부를 포함하고, 사료 공급부는 사료 저장부 외부로 연장되어 식용곤충에게 액체사료를 공급하는 식용곤충용 액체사료 공급 장치가 제공된다. claims: 내부에 식용곤충용 액체사료를 저장하는 사료 저장부; 및상기 식용곤충용 액체사료를 흡수 가능한 재질로 이루어지며, 일측이 상기 사료 저장부 내부에 설치되어 상기 식용곤충용 액체사료를 흡수하는 사료 공급부를 포함하고,상기 사료 공급부는 상기 사료 저장부 외부로 연장되어 식용곤충에게 액체사료를 공급하는, 식용곤충용 액체사료 공급 장치.제1에 있어서,상기 사료 저장부에 저장된 상기 식용곤충용 액체사료의 양을 감지하는 사료 감지 센서를 더 포함하는 식용곤충용 액체사료 공급 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

521/1150 Row 521: application_number: 1020200054204, combined_string: invention_title: 친환경 유기성 폐기물 처리용 동물 사육 시스템 abstract: 본 발명은 친환경 유기성 폐기물 처리용 동물 사육 시스템에 있어서, 특히 동애등에 사육용 파레트의 하부에 발열수단을 더 장착하여 음식물 쓰레기를 데워서 공급함으로서 동애등에의 빠른 성장을 유도하여 대량 사육이 가능토록 구성하고, 기둥 조립체를 다단으로 구성하여 조립성이 뛰어난 구조체를 제공한 것을 특징으로하는 친환경 유기성 폐기물 처리용 동물 사육 시스템에 관한 것으로,동애등에를 수납하는 동애등에 사육상자와; 상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과; 상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와; 상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하여 이루어지고; 상기 기둥 조립체는, 하부에 원통형 연결체(210)가 설치되고, 원통형 연결체(210)의 끝단에는 양측이 경사진 합체용 돌기(210a)가 설치되어 이루어지는 제 1 프레임(200)과; 상기 제 2 프레임의 하부에 위치되며 제 1 프레임과 원터치로 합체되는 제 2 프레임(300)으로 이루어지는 것이 특징이다. claims: 동애등에를 수납하는 동애등에 사육상자와;상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과;상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와;상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하여 이루어지고;상기 기둥 조립체는,하부에 원통형 연결체(210)가 설치되고, 원통형 연결체(210)의 끝단에는 양측이 경사진 합체용 돌기(210a)가 설치되어 이루어지는 제 1 프레임(200)과;상기 제 1 프레임의 하부에 위치되며 제 1 프레임과 원터치로 합체되는 제 2 프레임(300)으로 이루어지며;상기 제 2 프레임(300)은,최외각에 설치되는 제 1 합체용 몸체(310)와;상기 제 1 합체용 몸체와 일정거리 이격되어 설치되어 공간부를 형성하여 공간부로 합체용 돌기가 진입되도록 하고, 일단에 합체용 홈을 형성하여 합체용 돌기가 삽입 고정되도록 하는 제 2 합체용 몸체(320)와;상기 제 1 합체용 몸체와 제 2 합체용 몸체 사이에 설치되는 제 1 탄발수단(330)과;상기 제 1 탄발수단 전단에 설치되어 제 1 합체용 몸체의 합체용 돌기가 진입하면 후퇴하여 제 1 탄발수단을 압박하고 합체용 돌기가 제 2 합체용 몸체의 합체용 홈에 삽입되면 제 1 탄발수단의 탄발에 의해 전진하여 합체용 돌기 상부에 위치되는 제 1 탄발수단 유동부(350)와;상기 제 1 탄발수단 유동부 후단에 설치되며 탄발 기능을 갖는 제 2 탄발수단(340)과;상기 제 2 탄발수단의 외측에 설치되어 제 2 탄발수단을 구동하는 원통형 형상의 구조체로서 뒤로 후퇴하면서 제 2 탄발수단을 구동하기 위한 제 2 탄발수단 유동부(360)와;상기 제 2 탄발수단의 후단에 설치되어 제 2 탄발수단의 움직임을 지지하기 위한 제 2 탄발수단 지지부(370)를 포함하여 구성하고;상기 제 2 탄발수단 유동부는,손으로 파지를 용이하게 하기 위해 테두리면에 다수개의 요철을 형성하며;상기 제 1 프레임의 합체용 돌기와 제 2 프레임의 합체용 홈은 양측면에 경사면을 형성하여 이루어진 것을 특징으로 하는 친환경 유기성 폐기물 처리용 동물 사육 시스템., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

522/1150 Row 522: application_number: 1020200054209, combined_string: invention_title: 유기성 폐기물 먹이를 이용한 파리 에벌레 사육 장치 abstract: 본 발명은 유기성 폐기물 먹이를 이용한 파리 에벌레 사육 장치에 있어서, 특히 동애등에 사육용 파레트의 하부에 발열수단을 더 장착하여 음식물 쓰레기를 데워서 공급함으로서 동애등에의 빠른 성장을 유도하여 대량 사육이 가능토록 구성하고, 아울러 고른 열전달을 통해서 동애등에의 고른 사육이 가능토록 구성한 것을 특징으로하는 유기성 폐기물 먹이를 이용한 파리 에벌레 사육 장치에 관한 것으로,동애등에를 수납하는 동애등에 사육상자와; 상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과; 상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와; 상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단과; 상기 발열수단의 상부에 위치되며 순환액을 순환시키되 발열수단에서 발생한 열을 흡수하여 순환액이 가열되도록한후 고르게 사육상자에 순환액이 접촉되도록하는 순환액 수조를 포함하여 더 구성함이 특징이다. claims: 동애등에를 수납하는 동애등에 사육상자와;상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과;상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와;상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단과;상기 발열수단의 상부에 위치되며 순환액을 순환시키되 발열수단에서 발생한 열을 흡수하여 순환액이 가열되도록한후 고르게 사육상자에 순환액이 접촉되도록하는 순환액 수조를 포함하여 구성하고;상기 순환액 수조는,상기 순환액 수조 몸체의 하부 일측을 통해 설치되며 외부에서 공급되는 순환액을 순환액 수조 내부로 공급하는 순환액 입력배관(42)과;상기 순환액 수조 몸체의 상부 타측을 통해 설치되며 순환액 수조 내부를 순환한 순환액을 외부로 출력시키는 순환액 출력배관(43)과;상기 순환액 입력배관을 통해 입력되는 순환액을 임시저장하는 순환액 입력부(44)와;상기 순환액 출력배관을 통해 순환액을 출력하기 전에 임시저장하는 순환액 출력부(45)와;상기 순환액 수조 몸체의 내부에 설치되는 칸막이 형태로서 순환액 입력부와 중앙 공간부 사이에 설치되며 다수개의 입력홀을 형성하여 상기 입력홀을 통해 순환액이 입력되어 중앙 공간부쪽으로 이동하여 순환액이 뎁혀지면서 출력되도록 구성하는 순환액 입력용 패널(46)과;상기 순환액 수조 몸체의 내부에 설치되는 칸막이 형태로서 순환액 출력부와 중앙 공간부 사이에 설치되며 다수개의 출력홀을 형성하여 상기 중앙 공간부에 존재하는 순환액이 순환액 출력부쪽으로 이송되도록 구성하는 순환액 출력용 패널(47)을 포함하여 구성함을 특징으로 하는 유기성 폐기물 먹이를 이용한 파리 에벌레 사육 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

523/1150 Row 523: application_number: 1020200054214, combined_string: invention_title: 유기성 폐기물 처리를 위한 동애등에 사육장치 abstract: 본 발명은 친환경 유기성 폐기물 처리용 동물 사육 시스템에 있어서, 특히 동애등에 사육용 파레트의 하부에 발열수단을 더 장착하여 음식물 쓰레기를 데워서 공급함으로서 동애등에의 빠른 성장을 유도하여 대량 사육이 가능토록 구성하고, 기둥 조립체를 다단으로 구성하여 조립성이 뛰어난 구조체를 제공한 것을 특징으로하는 친환경 유기성 폐기물 처리용 동물 사육 시스템에 관한 것으로,동애등에를 수납하는 동애등에 사육상자와; 상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과; 상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와; 상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하여 이루어지고; 상기 기둥 조립체는, 하부에 원통형 연결체(210)가 설치되고, 원통형 연결체(210)의 끝단에는 양측이 경사진 합체용 돌기(210a)가 설치되어 이루어지는 제 1 프레임(200)과; 상기 제 2 프레임의 하부에 위치되며 제 1 프레임과 원터치로 합체되는 제 2 프레임(300)으로 이루어지는 것이 특징이다. claims: 내부에 동애등에 사육을 위한 공간부를 갖는 동애등에 사육용 하우징과;상기 동애등에 사육용 하우징 내부에 설치되며, 동애등에를 수납하는 동애등에 사육상자와;상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과;상기 받침 앵글을 결합하는 것으로, 크고 작은 관들 및 나사들의 집합체로 이루어지는 기둥 조립체와;상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단과;상기 사육용 하우징의 내부 일단에 설치되며, 사육상자에 난방을 제공하는 난방장치를 포함하여 이루어지고;상기 난방장치(1100)는,난방장치 본체(1110)와;난방장치 본체(1110)의 점화부(1120)에서 점화되어 발생되는 열기를 출력하는 점화부 출력배관(1130)과;상기 점화부 출력배관에 연결되어 점화부로부터 제공되는 열기를 외부로 방사시키는 지그재그 형태의 방열턱트(1140)와;상기 방열덕트 주변에 설치되어 점화부에서 점화되는 열기를 임시저장하는 열 저장수단(1150)과;상기 방열덕트의 출력단에 연결하되 점화부 출력배관에 연결하여 방열덕트로 재회전시킴으로서 폐열을 회수시키는 열 회수용 배관(1160)과;상기 열 회수용 배관에 열기 토출용 공간부를 두고 일정거리 이격되어 설치하되, 점화부 출력배관에 고정설치되어 열 회수용 배관을 통해 제공되는 폐열을 방열덕트로 재회전시키도록 유도하는 폐열 회수용 중계관(1170)과;본체의 일단에 설치하되 점화부 출력배관에 위치되어 점화부 출력배관을 통해 배출되는 과열기를 외부로 출력시키는 열기 배출수단(1180)으로 이루어지며;상기 폐열 회수용 중계관(1170)은,열기가 재인입시에 점화부(1120)로 열기의 방향이 향하지 못하도록, 상기 점화부 출력배관(1130)과 경사지게 결합하여 구성하고;상기 방열덕트(1140)는,난방장치 본체의 하부에 배치되는 하부덕트(1141)과, 상기 하부덕트에 일체로 연결하되 난방장치 본체의 상부에 배치되는 상부덕트(1142)와, 상기 상부덕트와 하부덕트를 연결하는 수직덕트(1143)로 이루어지고, 상부덕트 또는 하부덕트에 공기 통과용 홀(1190)을 더 형성하여 이루어지며;상기 방열덕트(1140)는,상기 상부덕트 또는 하부덕트 표면 일단에 설치되는 공기 개폐 조절용 모터(1191)와, 상기 공기 개폐 조절용 모터의 축에 연장설치되며 모터의 회전에 상응하여 움직이면서 공기 통과용 홀에 접면되어 공기 통과용 홀의 개방정도를 결정하는 공기 조절용 패널(1192)을 더 설치하여 이루어짐을 특징으로 하는 유기성 폐기물 처리를 위한 동애등에 사육장치., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

524/1150 Row 524: application_number: 1020200054218, combined_string: invention_title: 친환경 에너지팜 시스템 abstract: 본 발명은 친환경 에너지팜 시스템에 있어서, 특히 태양광을 활용하여 에너지를 생산하고 여기서 생성된 에너지를 이용하여 제한된 공간을 최대한 활용하면서도, 노동력이 절감되고 생산 수율이 높은 곤충 유충의 사육 시스템을 제공하는 것을 특징으로 하는 친환경 에너지팜 시스템에 관한 것으로,온도 및 습도조절부, 수분공급부를 구비하고, 센서를 구비하여 온도, 습도 및 수분공급을 제어하는 제어 장치를 포함하는 유충 사육용 하우징과; 태양광선을 전기에너지로 변환하여 전력을 생산 및 저장하면서 배터리와 인버터를 통해 제어장치 및 유충 사육용 하우징의 각 부하로 직류 또는 교류의 동작 전원을 공급하기 위한 태양광 발전부와; 상기 하우징 내부에 설치되며 유충을 사육하기 위한 유충 사육용 상자와; 상기 유충 사육용 상자의 바닥면에 설치되며 유충 사육용 상자에 열을 제공하기 위한 방열수단과; 상기 유충 사육용 상자를 지지하기 위한 철골 구조물을 포함하여 구성함이 특징이다. claims: 온도 및 습도조절부, 수분공급부를 구비하고, 센서를 구비하여 온도, 습도 및 수분공급을 제어하는 제어 장치를 포함하는 유충 사육용 하우징과;태양광선을 전기에너지로 변환하여 전력을 생산 및 저장하면서 배터리와 인버터를 통해 제어장치 및 유충 사육용 하우징의 각 부하로 직류 또는 교류의 동작 전원을 공급하기 위한 태양광 발전부와;상기 하우징 내부에 설치되며 유충을 사육하기 위한 유충 사육용 상자와;상기 유충 사육용 상자의 바닥면에 설치되며 유충 사육용 상자에 열을 제공하기 위한 방열수단과;상기 유충 사육용 상자를 지지하기 위한 철골 구조물을 포함하고;상기 제어장치는,상기 하우징 내에 설치되며, 외부의 원격 제어기 또는 통신 가능하게 결합된 통신기기를 통해 입력되는 사용자설정신호를 무선 수신하여 주제어부로 전달하는 원격 수신부와;상기 하우징의 내부 및 그의 주변영상 촬영이 가능한 위치에 설치되어 하우징의 내부 및 그 주변영상을 실시간 촬영하여 기록하고 주제어부로 전달하는 영상 촬영 및 기록부와;상기 원격 수신부를 통해 수신되는 사용자 설정신호에 따라 온도 및 습도조절부, 수분공급부의 동작을 선택 제어하기 위한 구동신호를 생성하여 상기 온도 및 습도 조절부 및 수분 조절부로 전달하고, 그에 따른 각 조절부의 상태 정보와 영상신호의 무선 전송을 제어하는 주제어부와;상기 주제어부에 전기적으로 접속되어 정보를 출력하는 온도 및 습도 센서 및 수분함량측정 센서와;사용자 설정신호에 따라 상기 주제어부에서 전달되는 작동 신호에 의해 작동되는 온도 및 습도 조절부 및 수분공급부를 포함하여 구성되고;상기 방열수단의 하부에는 순환액을 순환시키되 가열수단에서 발생한 열을 흡수하여 순환액이 가열되도록한후 고르게 사육상자에 순환액이 접촉되도록하는 순환액 수조와;상기 순환액 수조의 하단에 설치되어 순환액 수조에 히팅열을 제공하는 가열수단을 더 포함하여 구성하며;상기 순환액 수조는,상기 순환액 수조 몸체의 하부 일측을 통해 설치되며 외부에서 공급되는 순환액을 순환액 수조 내부로 공급하는 순환액 입력배관(42)과;상기 순환액 수조 몸체의 상부 타측을 통해 설치되며 순환액 수조 내부를 순환한 순환액을 외부로 출력시키는 순환액 출력배관(43)과;상기 순환액 입력배관을 통해 입력되는 순환액을 임시저장하는 순환액 입력부(44)와;상기 순환액 출력배관을 통해 순환액을 출력하기 전에 임시저장하는 순환액 출력부(45)와;상기 순환액 수조 몸체의 내부에 설치되는 칸막이 형태로서 순환액 입력부와 중앙 공간부 사이에 설치되며 다수개의 입력홀을 형성하여 상기 입력홀을 통해 순환액이 입력되어 중앙 공간부쪽으로 이동하여 순환액이 뎁혀지면서 출력되도록 구성하는 순환액 입력용 패널(46)과;상기 순환액 수조 몸체의 내부에 설치되는 칸막이 형태로서 순환액 출력부와 중앙 공간부 사이에 설치되며 다수개의 출력홀을 형성하여 상기 중앙 공간부에 존재하는 순환액이 순환액 출력부쪽으로 이송되도록 구성하는 순환액 출력용 패널(47)을 포함하여 구성함을 특징으로 하는 친환경 에너지팜 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

525/1150 Row 525: application_number: 1020200051882, combined_string: invention_title: 발열수단을 갖는 동애등에 대량 사육 시스템 abstract: 본 발명은 발열수단을 갖는 동애등에 대량 사육 시스템에 있어서, 특히 동애등에 사육용 파레트의 하부에 발열수단을 더 장착하여 음식물 쓰레기를 데워서 공급함으로서 동애등에의 빠른 성장을 유도하여 대량 사육이 가능토록 구성한 것을 특징으로하는 발열수단을 갖는 동애등에 대량 사육 시스템에 관한 것으로,동애등에를 수납하는 동애등에 사육상자와; 상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과; 상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하되, 상기 발열수단은, 지그재그로 배열되어 전기에너지를 열에너지로 변환시키기 위한 열선; 및 상기 열선이 방수 및 절연이 되도록 열선을 사이에 두고 서로 압착되어 결합되는 상판 및 하판으로 이루어지고; 상기 동애등에 사육상자의 일측에 위치하며 유해공기를 태우기 위한 유해공기 버너부를 포함하여 구성함이 특징이다. claims: 동애등에를 수납하는 동애등에 사육상자와;상기 동애등에 사육상자를 수용하는 수용부를 구비하며, 수직방향으로 일정간격을 유지하여 설치되는 다수개의 받침앵글과;상기 동애등에 사육상자와 받침앵글 사이에 설치되어 공급되는 전원에 의해 동애등에 사육상자 내부에 존재하는 동애등에의 발아와 생육에 필요한 온도를 발생시키는 발열수단을 포함하되, 상기 발열수단은, 지그재그로 배열되어 전기에너지를 열에너지로 변환시키기 위한 열선 및, 상기 열선이 방수 및 절연이 되도록 열선을 사이에 두고 서로 압착되어 결합되는 상판 및 하판으로 이루어지고;상기 동애등에 사육상자의 일측에 위치하며 유해공기를 태우기 위한 유해공기 버너부를 포함하여 구성하고;상기 유해공기 버너부는,불꽃방전 전기 공급용 스위칭 수단(2221)과; 불꽃방전 전기 공급용 스위칭 수단(2221)에 장착되어 불꽃방전을 자동으로 재점화 시키기 위한 불꽃방전 재점화 스위칭 수단(2222)과; 상기 불꽃방전 재점화 스위칭 수단(2222)에 연결되어 불꽃방전 재점화를 위한 신호를 출력하는 불꽃방전 재점화 회로부(2223)가 설치되어 이루어지며;상기 불꽃방전 재점화 스위칭 수단(2222)은,상기 불꽃방전 전기 공급용 스위칭 수단(2221)의 테두리면에 설치되어 불꽃방전 전기 공급용 스위칭 수단(2221)이 회전하면 동시에 회전하는 피니언 기어(2222a)와;상기 피니언 기어(2222a)의 회전에 의해서 수평으로 슬라이딩 이동하도록 원기둥 또는 사각기둥 형상이며 피니언 기어(2222a)와 접촉면에 랙기어(2222e)가 형성되어 이루어지는 제 1 슬라이딩 이송부재(2222b)와;상기 제 1 슬라이딩 이송부재(2222b)의 내측에 결합되며 제 1 슬라이딩 이송부재(2222b)가 움직이면 이에 연동하여 움직이면서 불꽃방전 재점화 회로부(2223)를 스위칭 시키는 제 2 슬라이딩 이송부재(2222c)와;상기 제 1 슬라이딩 이송부재(2222b)의 끝단과 제 2 슬라이딩 이송부재(2222b)의 시작단에 각각 접속되며 불꽃방전 재점화 회로부(2223)의 스위칭 상태를 유지시키는 역할을 하는 인장 스프링(2222d)을 포함하여 이루어지고;상기 불꽃방전 재점화 회로부(2223)는,12볼트 리듐전지, 차량용 축전지 또는 일반용 전지를 다수개 직렬 연결하여 필요한 전압을 공급하기 위해 설치되는 직류 전원부(2101)와;상기 직류 전원부에 일단이 연결되고, 불꽃방전 전기 공급용 스위칭 수단이 회전될때 스위칭되어 온이 되는 불꽃방전 재점화 스위치(2102)와;상기 불꽃방전 재점화 스위치가 온 되면 전기가 공급되어 승압된 교류 전류를 출력하는 발진 승압 회로부(2103)와;상기 발진 승압 회로부의 출력단에 연결되어 전기적 공급에 의해서 온 되는 방전 전극 전기 공급용 스위칭부(2108)와;상기 방전 전극 전기 공급용 스위칭부의 출력단에 설치되며 고압을 발생시키는 고압 승압 회로부(2107)와;상기 고압 승압 회로부에 의해서 공급되는 고압의 전원이 연결되어 이루어지는 고압 방전 간격제(2113a, 2113b)와;상기 고압 방전 간격제에 의해서 제공된 전원을 이용하여 방전이 이루어지면서 점화시켜 불꽃이 타오르도록 유도하는 방전 전극(2114)과;상기 방전 전극과 베이스단이 연결되고 에미터단 및 콜렉터단이 고압 승압 회로부 및 방전 전극 전기 공급용 스위칭부에 연결되며, 공간부에 불꽃이 발생되면 열전자에 의해서 폐회로를 형성하면서 스위칭되어 방전 전극 전기 공급용 스위칭부로 향하는 전원을 차단시켜 방전 전극이 점화되는 것을 차단하고, 외부 바람이나 습기에 의해서 불꽃방전 불꽃이 꺼지면 열전자의 소멸로 인하여 폐회로가 깨지면서 스위칭이 오프되고 이에 따라 방전 전극 전기 공급용 스위칭부로 향하는 전원을 온 시켜 방전 전극이 점화되도록 유도하는 기능을 하는 방전 전극 차단용 스위칭부(2118)를 포함하여 구성함을 특징으로 하는 발열수단을 갖는 동애등에 대량 사육 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

526/1150 Row 526: application_number: 1020200050468, combined_string: invention_title: 숯을 이용한 벌통 관리구 abstract: 본 발명은 숯을 이용한 벌통 관리구에 관한 것으로서, 숯을 이용하여 벌통 내부의 공기정화 및 습도조절 작용이 지속적으로 이루어질 수 있게 되어 벌통의 관리 효율을 향상시키는 효과를 나타내기 위한 것이다.이를 실현하기 위한 본 발명은, 벌통의 내부에 구비하여 습도를 조절하는 벌통 관리구로서, 습기의 내부 유입 차단을 위한 방수커버(10)와; 상기 방수커버(10)의 내부에 삽입 구성되되, 내부에는 다수의 숯(21)이 보관되는 숯포(20);를 포함하는 구성을 이루는 것을 특징으로 한다. claims: 벌통의 내부에 구비하여 습도를 조절하는 벌통 관리구로서,습기의 내부 유입 차단을 위한 방수커버(10)와;상기 방수커버(10)의 내부에 삽입 구성되되, 내부에는 다수의 숯(21)이 보관되는 통기성 숯포(20);를 포함하되,상기 방수커버(10)는 통기성을 위한 부직포 재질의 내피층(10a)과, 습기 차단을 위한 세라믹 성분이 박막으로 코팅 형성된 외피층(10b)으로 이루어지며,상기 방수커버(10)의 일측은 숯포(20)의 교체가 가능하도록 개방된 구조를 이루며, 상기 개방 부위에는 개폐를 위한 지퍼부(11)가 구비되고,상기 방수커버(10) 일측에는 소금의 보관이 이루어지는 소금 보관팩(12)이 구비된 것을 특징으로 하는 숯을 이용한 벌통 관리구., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

527/1150 Row 527: application_number: 1020200047602, combined_string: invention_title: 양봉통 내부 검사 장치 abstract: 본 발명은 적층된 양봉통을 쉽고 간편하게 개방하여 양봉통의 내부 검사가 용이하게 이루어지도록 하는 양봉통 내부 검사 장치에 관한 것이다.본 발명의 양봉통 내부 검사 장치는 상하로 적층된 양봉통 중 상단에 위치한 양봉통(10)을 후방으로 젖혀서 거치시키는 거치대(100)와, 상기 거치대에 고정된 연결부재(20)와, 상단에 위치한 양봉통이 후방으로 젖혀질 때 하부에 위치한 양봉통(20)이 유동되지 않도록 상기 연결부재에 매달린 상태로 거치되는 중앙부(301)와 하부에 위치한 양봉통을 감싼 상태로 결속되는 양단부(302)를 구비한 탄성재질의 결속로프(300)를 포함한다. claims: 상하로 적층된 양봉통 중, 상단에 위치한 양봉통을 후방으로 젖혀서 거치시키는 거치대;상기 거치대에 고정된 연결부재; 및상단에 위치한 양봉통이 후방으로 젖혀질 때 하부에 위치한 양봉통이 유동되지 않도록, 상기 연결부재에 매달린 상태로 거치되는 탄성재질의 결속로프;를 포함하고,상기 결속로프는 상기 연결부재에 매달린 상태로 거치되는 중앙부와, 하부에 위치한 양봉통을 감싼 상태로 결속되는 양단부를 포함하며,상기 결속로프의 양단부 중 일측단부에는 후크가 결합되고 타측단부에는 상기 후크에 대응되는 적어도 하나 이상의 고리가 결합되고,상기 고리는 결속로프의 타측단부에 결합되는 본체와, 상기 본체의 단부로부터 연장형성된 고리편으로 구성된 양봉통 내부 검사 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

528/1150 Row 528: application_number: 1020200042237, combined_string: invention_title: 벌통 abstract: 본 발명은 다수의 관통공(201), (202)이 형성된 본체(200) 내부 바닥 전, 후방에 배출구(203), (203')를 형성하여 이물질 제거시 개방과 폐쇄를 동시에 병행하도록 형성하고, 이물질 제거시에나, 그늘의 공기를 유입하기 위해 개방하도록 슬라이드 홈(216a)에 환기망(216b)이 형성된 개폐판(216)을 삽입장착하여 본체(200) 내부의 불필요한 이물질을 제거할 때 개방되게 함과 아울러 배출구(203), (203')로 이물질을 제거하거나 폐쇄할 수 있도록 본체(200) 바닥에 제거기(211)를 장착하고, 상기 본체(200)에 형성된 돌출구(204)의 숫체결부(260)를 계상통(230)의 암체결부(270)에 결합함에 따라 계상통(230)을 연장 고정하여 뚜껑(100)을 덮어 고정할 수 있을 뿐만 아니라, 본체(200) 양 중앙 하측의 고리(224')로 인해 본 발명의 벌통(1)을 지면판(400)에 고정할 수 있음은 물론, 뚜껑(100) 내부에 여왕벌을 감금할 수 있는 분봉망(101)을 망고정구(101')로 고정하도록 형성하여 분봉으로 인한 벌들의 외부탈출을 막을 수 있도록 형성하고, 지면에 말뚝(221)을 꽂아 고정된 지면판(400)에 고리(224')로 고정된 벌통(1)이 강풍에 위치이동 되지 않도록 하는 것은 물론, 상기 본체(200)와 계상통(230)을 덮는 뚜껑(100)의 통풍구(110)에 통기구(114)를 장착하여 벌통(1)의 본체(200) 및 계상통(230) 내부의 온도, 습도를 온습도기(150)를 통해 확인 한 다음, 본체(200) 및 계상통(230) 내부의 환기를 환기망(216b)과 통기구(114)의 조절구(116)로 조절할 수 있도록 형성하고, 상기 본체(200)의 전면에 장착되는 전면수단(300)에는 이착륙판(306)에 형성된 관통공(302a)의 턱(306') 상단부에 선택패널(312)이 장착된 벌출입부(310)를 나사(50) 결합하여 선택패널(312)을 구성하는 조절판(312b)의 일측 상하에 U자형출입구(312a)와 O자형출입구(312a')를 형성하여 벌들의 출입을 임의로 통제 및 조절할 수 있도록 형성하고, 상기 이착륙판(306) 하측에는 좌, 우 양측에 각각 전, 후선택공(319), (319')을 형성하여 전면수단(300)을 형성하는 관통공(303), (303')에 화분함(320)과 벌사양부(350)를 슬라이드 삽입장착하고, 상기 벌사양부(350)에는 물과 사양액이 공급되는 물공급관(355), 액공급관(356)에 연질막(358a')이 형성된 부력(358을 장착한 물통(353), 액통(354)을 형성하여 물통로(355a'), 액통로(356a')를 통해 젖어들도록 물심지(355a), 액심지(356a)가 삽입된 물유입통(353'), 액유입통(354')을 형성하여 벌들이 소비하는 물과 사양액의 소비량에 따라 일정량이 공급되도록 형성하고, 상기 본 발명의 벌통(1)을 장, 단거리의 이동시 선택패널(312)의 조절판(312b)으로 벌출입부(310)의 관통공(301)을 봉쇄하거나, 출입구인 관통공(301)을 일정 길이 제한할 수 있는 것을 포함하여 구성된 것을 특징으로 한다. claims: 돌출구(204)의 양 중앙에 숫체결부(260)를 형성한 본체(200)의 하측 중앙부에 판결합부(280)를 장착하여 다수의 통공(60)을 통해 지면에 다수의 말뚝(221)으로 고정된 지면판(400)에 고리(224')가 고정되도록 형성하고,상기 본체(200)의 전방에는 관통공(201), (202)을 형성하고,상기 본체(200)의 상부에 안착하는 계상통(230)의 상, 하돌출턱(231), (231')에는 체결수단(250)을 형성하는 숫체결부(260)와 암체결부(270)를 장착하고,상기 본체(200)의 돌출구(204)에 숫체결부(260)를 장착하여 뚜껑(100)에 형성된 암결합부(270)에 고정할 수 있도록 형성하고,상기 본체(200) 좌우의 락(224a')에는 판결합부(280)를 형성하는 고리(224')의 돌기(224a)를 삽입하도록 형성하고,상기 본체(200)에 형성된 배출구(203), (203') 전후방에는 개폐판(216)이 슬라이드 장착되는 홈(216a')을 형성하고,상기 본체(200)의 홈(216a')에는 일측 단부의 손잡이(216a')와, 타측 단부에 환기망(216b)이 형성된 개폐판(216)이 슬라이드 삽입되도록 형성하고,상기 본체(200) 내부의 좌우 슬라이드장홈(200')에는 막음판(213')과 커트기(214)가 형성된 제거기(211)를 장착하여 전, 후방으로 슬라이드 함과 동시에 배출구(203), (203')를 개폐하도록 형성하고,상기 본체(200)의 지지대(200a) 저면에는 말뚝(221)의 헤드(221')가 삽입되도록 고정홈(206a)을 형성한 고정구(206)에 잠금부(330)의 잠금봉(332')이 삽입되는 연장고정홈(206a')을 형성하여 장착하고,상기 본체(200)의 중앙 저면에는 뚜껑(100)의 장부맞춤돌기(108)와 결합하도록 장부맞춤홈(208)을 형성하고,상기 본체(200)의 지지대(200a) 저면에 장착된 고정구(206)의 연장고정홈(206a')에는 뚜껑(100) 전후방에 장착된 잠금부(330)의 잠금봉(332')이 삽입되도록 구성한 것을 특징으로 하는 벌통., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

529/1150 Row 529: application_number: 1020200030289, combined_string: invention_title: 동애등에 사육시설물 abstract: 본 발명은 동애등에 사육시설물에 관한 것으로서 더욱 상세하게는 사육상자가 각 층별로 순환가능하도록 하는 레일로 및 지지프레임부를 통해 동애등에 유충이 대량으로 수용가능하도록 하며 레일로 일측에 승하강가능하도록 설치되는 승하강작업대를 통해 먹이 공급 및 유충 수거가 신속하고 용이하게 이루어지도록 함에 따라 유충 사육의 대량화는 물론 작업의 용이성을 동시에 충족할 수 있는 동애등에 사육시설물에 관한 것이다. 이를 위해 본 발명은 동애등에 유충이 수용되어 사육되도록 일정 수용공간이 형성되는 복수개의 사육상자와; 상기 복수개의 사육상자가 수평면 상에 레일로를 따라 이동가능하도록 지지되되 상기 레일로가 다단층으로 위치되어 지지되도록 하는 지지프레임부와; 상기 다단층으로 이루어지는 지지프레임부의 레일로 일측 단부에 선택적으로 위치되는 승하강작업대; 및 상기 승하강작업대가 위치되는 레일로의 타측 단부측에 위치되며 다단층의 레일로 각각에 고정설치되는 고정작업대;를 포함하되, 상기 레일로는 제1방향으로 이송하는 제1이송레일로와, 상기 제1이송레일로 일측에 평행하게 설치되며 제2방향으로 이송하는 제2이송레일로를 포함한다. claims: 동애등에 유충이 수용되어 사육되도록 일정 수용공간이 형성되는 복수개의 사육상자와; 상기 복수개의 사육상자가 수평면 상에 레일로를 따라 이동가능하도록 지지되되 상기 레일로가 다단층으로 위치되어 지지되도록 하는 지지프레임부와; 상기 다단층으로 이루어지는 지지프레임부의 레일로 일측 단부에 선택적으로 위치되는 승하강작업대; 및상기 승하강작업대가 위치되는 레일로의 타측 단부측에 위치되며 다단층의 레일로 각각에 고정설치되는 고정작업대;를 포함하되,상기 레일로는 제1방향으로 이송하는 제1이송레일로와, 상기 제1이송레일로 일측에 평행하게 설치되며 제2방향으로 이송하는 제2이송레일로를 포함하고,상기 고정작업대는 다단층으로 이루어지는 레일로의 각 단부측에 위치되어 사육상자가 안착되며 상부측으로 복수개의 볼롤러가 돌출되어 설치되는 고정작업판과, 상기 고정작업판의 하부측에서 지지하는 고정작업대프레임과, 상기 고정작업대프레임을 외측에서 고정지지되도록 하는 고정작업대하우징을 포함하는 것을 특징으로 하는 동애등에 사육시설물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

530/1150 Row 530: application_number: 1020200009563, combined_string: invention_title: 꿀벌 생육환경 제공장치 abstract: 본 발명은 꿀벌의 생육환경을 제공하기 위한 장치에 관한 것이다.본 발명에 따른 꿀벌의 생육환경 제공장치는 벌통(BH)과, 벌통에 설치되고 꿀벌의 먹이를 제공하는 먹이 제공부(10)와, 벌통에 설치되고 꿀벌의 식수를 제공하는 식수 제공부(20)와, 벌통 내부의 온도를 조절하는 온도 조절부(30)와, 상기 먹이 공급부, 식수 제공부, 온도 조절부를 제어하는 컨트롤러(50)와, 상기 컨트롤러와 통신 연결되는 관리자 단말기(70)를 포함하고, 상기 먹이 제공부(10)는 먹이 보관부(12)와, 제1 밸브(14)가 구비되는 제1 배관(13)과, 먹이 노즐로 이루어지고, 상기 식수 제공부(20)는 식수 보관부(22)와, 제2 밸브(24)가 구비되는 제2 배관(23)과, 식수 노즐로 이루어지고, 상기 온도 조절부(30)는 발열체(HTR)와 쿨링팬(CFN)로 이루어지며, 상기 단말기(70)는 컨트롤러(50)을 통해 먹이 제공부, 식수 제공부, 및 온도 조절부를 제어하도록 구성된다.또한, 컨트롤러(50)는 먹이 제공모듈(51), 식수 제공모듈(52), 온도 조절모듈(53), 통신모듈(55)로 이루어지고, 상기 먹이 제공모듈(51) 및 식수 제공모듈(52)은 단말기로부터 전송되는 소정의 주기 시간을 입력받고 먹이 제공부의 제1 밸브와 식수 제공부의 제2 밸브를 개폐하고, 상기 온도 조절모듈(53)은 온도벌통 내부로부터 검출된 온도에 기초하여 발열체를 구동하되, 검출된 온도가 미리 설정된 제1 기준온도 보다 낮을 경우, 발열체로 구동신호를 출력한다. claims: 벌통(BH)과, 상기 벌통에 설치되고 꿀벌의 먹이를 제공하는 먹이 제공부(10)와, 상기 벌통에 설치되고 꿀벌의 식수를 제공하는 식수 제공부(20)와, 벌통 내부의 온도를 조절하는 온도 조절부(30)와, 상기 먹이 공급부, 식수 제공부, 온도 조절부를 제어하는 컨트롤러(50)와, 상기 컨트롤러와 통신 연결되는 관리자 단말기(70)를 포함하고,상기 벌통은 소정의 사각 공간부를 갖는 본체와, 상기 본체의 내부에 구비되는 한 쌍의 걸림부재와, 상기 걸림부재에 안착되는 하나 이상의 소초광과, 상기 걸림부재에 안착되고, 소초광과 동일한 형상을 갖는 환경 제공부와, 상기 본체의 상부에 결합되고 관통홀을 구비하는 커버를 포함하고, 상기 본체에는 벌통 내부의 공기를 배출시키거나 외부의 공기를 벌통 내부로 유입시키는 쿨링팬과, 식수배관, 먹이배관, 센서라인, 및 전원라인이 연결되는 접속패널이 설치되고, 상기 환경제공부는 사각 형상의 바디와, 바디의 상측 양단에 돌출되는 돌출부와, 상기 바디의 하부를 밀폐하는 막음판을 포함하고, 상기 돌출부는 본체 내부에 구비되는 걸림부재에 안착되고, 상기 바디는 일측 상부에 구비되는 식수홈과, 타측 상부에 구비되는 먹이홈과, 바디의 하부에 구비되고 발열체가 삽입되는 발열홈과, 식수배관, 먹이배관, 센서라인, 전원라인을 접속패널과 연결하는 연결패널을 포함하여 이루어지고, 상기 먹이홈에는 먹이를 토출하기 위한 노즐과 먹이의 수위를 검출하는 센서가 설치되며, 상기 식수홈에는 식수를 토출하기 위한 노즐과 식수의 수위를 검출하는 센서가 설치되고,상기 먹이 제공부(10)는 먹이 보관부(12)와, 제1 밸브(14)가 구비되는 제1 배관(13)과, 먹이 노즐로 이루어지고,상기 식수 제공부(20)는 식수 보관부(22)와, 제2 밸브(24)가 구비되는 제2 배관(23)과, 식수 노즐로 이루어지고,상기 온도 조절부(30)는 발열체(HTR)와 쿨링팬(CFN)로 이루어지며,상기 단말기(70)는 컨트롤러(50)을 통해 먹이 제공부, 식수 제공부, 및 온도 조절부를 제어하고,상기 컨트롤러(50)는 먹이 제공모듈(51), 식수 제공모듈(52), 온도 조절모듈(53), 통신모듈(55)로 이루어지고,상기 먹이 제공모듈(51) 및 식수 제공모듈(52)은 단말기로부터 전송되는 소정의 주기 시간을 입력받고 먹이 제공부의 제1 밸브와 식수 제공부의 제2 밸브를 개폐하고,상기 온도 조절모듈(53)은 온도벌통 내부로부터 검출된 온도에 기초하여 발열체를 구동하되, 검출된 온도가 미리 설정된 제1 기준온도 보다 낮을 경우, 발열체로 구동신호를 출력하는 것을 특징으로 하는 꿀벌 생육환경 제공장치.벌통(BH)과, 벌통에 설치되고 꿀벌의 먹이를 제공하는 먹이 제공부(100)와, 벌통 내부의 온도를 조절하는 온도 조절부(200)와, 벌통 내부의 습도를 조절하는 습도 조절부(400)와, 상기 먹이 공급부, 온도 조절부, 습도 조절부를 제어하는 컨트롤러(500)와, 상기 컨트롤러와 통신 연결되는 관리자 단말기(700)를 포함하고,상기 벌통은 소정의 사각 공간부를 갖는 본체와, 상기 본체의 내부에 구비되는 한 쌍의 걸림부재와, 상기 걸림부재에 안착되는 하나 이상의 소초광과, 상기 걸림부재에 안착되고, 소초광과 동일한 형상을 갖는 환경 제공부와, 상기 본체의 상부에 결합되고 관통홀을 구비하는 커버를 포함하고,상기 본체에는 벌통 내부의 공기를 배출시키거나 외부의 공기를 벌통 내부로 유입시키는 쿨링팬과, 식수배관, 먹이배관, 센서라인, 및 전원라인이 연결되는 접속패널이 설치되고,상기 환경제공부는 사각 형상의 바디와, 바디의 상측 양단에 돌출되는 돌출부와, 상기 바디의 하부를 밀폐하는 막음판을 포함하고, 상기 돌출부는 본체 내부에 구비되는 걸림부재에 안착되고, 상기 바디는 일측 상부에 구비되는 식수홈과, 타측 상부에 구비되는 먹이홈과, 바디의 하부에 구비되고 발열체가 삽입되는 발열홈과, 식수배관, 먹이배관, 센서라인, 전원라인을 접속패널과 연결하는 연결패널을 포함하여 이루어지고, 상기 먹이홈에는 먹이를 토출하기 위한 노즐과 먹이의 수위를 검출하는 센서가 설치되며, 상기 식수홈에는 식수를 토출하기 위한 노즐과 식수의 수위를 검출하는 센서가 설치되고,상기 먹이 제공부(100)는 먹이 보관부(120)와, 제1 밸브(140)가 구비되는 제1 배관(130)과, 먹이 노즐로 이루어지고,상기 온도 조절부(200)는 온도 센서(TSR)와, 발열체(HTR)와, 쿨링팬(CFN)으로 이루어지며,상기 습도 조절부(400)는 생수 보관부(420)와, 제4 밸브(440)가 구비되는 제4 배관(430)과, 스프레이로 이루어지고,상기 단말기(700)는 컨트롤러(500)을 통해 먹이 제공부, 온도 조절부, 및 습도 조절부를 제어하는 것을 특징으로 하는 꿀벌 생육환경 제공장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

531/1150 Row 531: application_number: 1020200005572, combined_string: invention_title: 다단 유충사육용기 및 이를 포함하는 유충사육시스템 abstract: 본원 발명은 등애사육용기(300) 및 이를 포함하는 등애사육시스템에 관한 것으로서, 다량의 등애애벌레를 용이하게 사육하고 수확할 수 있도록 구성된 것이다. 특히, 사각형상의 바닥부, 상기 바닥부의 각 변에 연장되어 상방향으로 경사지게 구비되는 측변부로 이루어지는 등애사육단위용기(300)에 있어서, 상기 단위 사육용기(300)는 상기 인접한 측변부 사이에 연결기둥(320)을 구비하고, 상기 연결기둥(320)에 의해서 상하로 적층되는 인접한 단위 사육용기(300)와 결합되되, 상기 바닥부는 개폐수단(340)에 의해서 개폐동작이 이루어져 사육이 끝난 등애를 배출하는 것을 특징으로 하는 등애사육용기(300)이다. claims: 사각형상의 바닥부, 상기 바닥부의 각 변에 연장되어 상방향으로 경사지게 구비되는 측변부로 이루어지는 유충사육용기(300); 상기 유충사육용기(300)는 각 모서리에 연결기둥(320)을 구비하여, 상기 연결기둥(320)에 의해서 복수개의 유충사육용기(300)가 상하 인접하여 결합되고, 최하단에 설치되는 이송대차(200)의 각 모서리에 결합된 연결기둥(220) 하단부에는 바퀴(210)가 더 구비되며, 상기 바닥부는 개폐수단(340)에 의해서 개폐되는 복수개의 분할판(330)으로 이루어지되,상기 개폐수단(340)은,상기 분할판(330)의 중심부를 관통하도록 구비된 회전축(341);상단이 상기 회전축(341)에 일체로 결합되는 연결레버(342);상기 연결레버(342)의 하단에 연결되는 작동바(343);다단의 유충사육용기(300)에 각각 구비된 작동바(343)의 단부와 힌지결합되는 연결링크(346);를 구비하되, 적어도 하나의 상기 작동바(343)의 소정위치에 힌지결합되는 작동레버(344);와상기 작동레버(344)의 타단에 결합되어 작동레버(344)를 회전구동하는 구동모터(345);를 포함하는 것을 특징으로 하는 다단유충사육용기. 제3항의 다단유충사육용기; 및 상기 다단유충사육용기를 수용할 수 있는 사육챔버(100)를 포함하는 유충사육시스템에 있어서, 상기 사육챔버(100)의 내부에는 하부 중앙을 가로질러 설치되는 컨베이어;상기 컨베이어의 상부 양측으로 상기 이송대차(200)의 바퀴(210)가 이동될 수 있도록 길이방향을 따라서 구비된 이송레일(150);을 포함하되, 상기 챔버의 일단에는 송풍장치가 구비되고, 상측에는 배기장치가 구비되며 타측에는 상기 유충사육용기(300)에서 배출되어 컨베이어 상면에 떨어진 유충을 이동시켜 배출하는 배출구(160)를 더 구비하고, 상기 이송레일(150)은 상단면이 △산모양으로 돌출되되, 이에 안착되는 이송대차(200)의 바퀴(210)는 외주면이 상기 이송레일(150)의 상단면에 대응되는 형상을 가져서 상기 이송레일(150)로부터 이탈되는 것을 방지한 것을 특징으로 하는 유충사육시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

532/1150 Row 532: application_number: 1020200005036, combined_string: invention_title: 중력 작용으로 사료를 배출하는 동물 사육 로봇 abstract: 본 발명은 동물이 로봇에 가하는 물리적인 외력이나 중력의 작용에 의해서 먹이를 외부로 배출하는 동물 사육용 로봇에 관한 것이다. 모바일 디바이스나 컴퓨터에 설치된 로봇 제어용 컴퓨터 프로그램을 통하여 무선 인터넷으로 구동이 제어되는 동물용 로봇으로서, 특히 먹이 배출부가, 먹이 배출을 통제하는 전자적 또는 기계적 제어장치를 전혀 포함하지 아니하고, 오로지 동물이 가하는 물리적 힘이나 중력의 작용에 의한 먹이 배출만 허용하는 것임을 특징으로 함으로써, 전자적 기계적 통제 수단의 가동으로 인한 전원 소모 가능성을 원천적으로 제거하여, 사육자 부재기간 동안 원격 조종 도중에 전원이 소모되더라도, 동물이 로봇에 가하는 물리적 외력이나 중력의 작용에 먹이가 배출되도록 함으로써, 전원 소모 시에도 먹이주기가 중단되는 위험을 최소화할 수 있는, 동물 사육용 로봇에 대한 것이다. claims: 컴퓨터 또는 모바일 디바이스에 설치되는 로봇 원격 조종 프로그램으로 무선 인터넷을 통하여 조종되거나 또는 로봇에 내장된 제어부에 입력된 자율 작동 프로그램에 따라 작동하는 동물 사육 로봇으로서, 상기 조종 프로그램으로 부터의 제어 신호를 받아들이는 신호송수신부; 로봇 몸체의 양 측면에 돌출된 회전축에 장착된 바퀴; 상기 바퀴에 회전축을 회전력을 전달하는 모터; 상기 모터와 제어부와 신호수신부에 전력을 제공하는 전원과 전원 스위치; 상기 조종 프로그램으로 부터 무선 인터넷을 통해 받은 제어 신호에 따라 로봇의 전진, 후진, 회전의 방향과 속도를 제어하거나 또는 제어부에 입력된 자율 작동 모드 프로그램에 따라 감지 센서의 접촉 감지에 반응하여 몸체를 회전시켜는 제어부; 동물의 먹이를 보관하고 배출하는 먹이 배출부 그리고 상기 모터, 전원, 전원 스위치, 신호송수진부, 제어부, 회전축, 먹이 배출부를 둘러싸는 몸체 하우징, 몸체 하우징과 회전축 사이에 배치되는 베어링을 포함하면서, 먹이 배출만을 위한 별도의 전자적 또는 기계적 작동 장치가 없이 동물이 로봇에 가하는 외력이나 중력의 작용에 의하여 먹이를 외부로 배출하는, 동물 사육 로봇., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

533/1150 Row 533: application_number: 1020200000517, combined_string: invention_title: 착탈식 왕롱을 갖춘 소초광 abstract: 본 발명은 여왕벌을 수용하는 왕롱을 갖춘 소초광에 있어서: 수평외틀(21)과 수직외틀(22)로 형성되는 영역에 소초(10)와 공간부를 구비하는 소광틀(20); 및 상기 소광틀(20)의 공간부에 착탈 가능한 구조로 형성되고, 지지틀(31)의 내측으로 다수의 환봉재(32)에 의한 수용공간을 구비하는 왕롱재(30);를 구비하는 것을 특징으로 한다.이에 따라, 벌통안의 벌들이 많아 증소 과정에서 사용되는 소초광에 있어서 여왕벌을 위한 충분한 공간을 확보하는 동시에 고정과 해체가 용이하여 생산성 향상과 경쟁력 제고를 도모하는 효과가 있다. claims: 여왕벌을 수용하는 왕롱을 갖춘 소초광에 있어서:수평외틀(21)과 수직외틀(22)로 형성되는 영역에 소초(10)와 공간부를 구비하는 소광틀(20); 및상기 소광틀(20)의 공간부에 착탈 가능한 구조로 형성되고, 지지틀(31)의 내측으로 다수의 환봉재(32)에 의한 수용공간을 구비하는 왕롱재(30);를 구비하는 것을 특징으로 하는 착탈식 왕롱을 갖춘 소초광., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

534/1150 Row 534: application_number: 1020190177352, combined_string: invention_title: 인공광을 이용한 아메리카동애등에 성충의 연중 실내 교미 산란방법 abstract: 아메리카동애등에의 가장 안정적인 산란 광 조건을 탐색하였으며 LED광워 조건하에서 빛 파장 범위가 640-680nm의 구간에서 Relative photosynthetic efficiency의 값이 높을 수록 아메리카동애등에의 산란된 난괴수 값이 높게 나타났다. claims: 실내조건에서 인공광으로 교미와 산란을 유발시키는 인공광 wavelength의 범위가 640~680nm에서 Relative photosynthetic efficiency의 값이 0.7-1을 갖는 led lamp로 사육하는 방법, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

535/1150 Row 535: application_number: 1020190176615, combined_string: invention_title: 도봉방지장치 abstract: 본 발명은 토종벌통에 구비된 토종꿀벌의 출입구에 설치되는 도봉방지장치에 있어서, 직육면체 형상을 가지며, 제1측면이 개방 형성되고, 제2측면이 출입구에 밀착 설치되되 출입구에 밀착되는 영역이 관통 형성된 케이스 및 제1측면의 개방된 영역에 망 형상으로 개폐 가능하게 설치되어, 토종꿀벌 중 외역벌 및 내역벌의 출입이 가능하고, 토종꿀벌 중 여왕벌과 수벌, 그리고 서양벌의 출입을 차단하는 차단망을 포함하는 것을 특징으로 한다. claims: 토종벌통에 구비된 토종꿀벌의 출입구에 설치되는 도봉방지장치에 있어서,직육면체 형상을 가지며, 제1측면이 개방 형성되고, 제2측면이 상기 출입구에 밀착 설치되되 상기 출입구에 밀착되는 영역이 관통 형성된 케이스; 상기 제1측면의 개방된 영역에 망 형상으로 개폐 가능하게 설치되어, 상기 토종꿀벌 중 외역벌의 출입이 가능하고, 상기 토종꿀벌 중 여왕벌과 수벌, 그리고 서양벌의 출입을 차단하는 차단망;을 포함하는 것을 특징으로 하는 도봉방지장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

536/1150 Row 536: application_number: 1020190172788, combined_string: invention_title: 회전소문을 갖는 기능성 벌통 abstract: 본 발명은 바닥면 및 벽면을 포함하는 벌통받침, 상기 벌통받침 상에 구비되는 벌통몸체 및 상기 벌통몸체의 상부를 덮는 벌통뚜껑으로 구성되는 벌통으로서, 상기 벌통받침의 벽면의 전부 또는 일부가 개방되어 벽면의 두께에 의해 형성되는 벽공간을 구비하고, 상기 벽공간의 형상에 대응하는 형상의 회전소문을 포함하여 소문의 인입 및 인출이 용이하고 소문의 위치 변경이 용이한 벌통을 제공할 수 있다. claims: 바닥면 및 벽면을 포함하는 벌통받침, 상기 벌통받침 상에 구비되는 벌통몸체 및 상기 벌통몸체의 상부를 덮는 벌통뚜껑으로 구성되는 벌통으로서, 상기 벌통받침의 벽면의 전부 또는 일부가 개방되어 벽면의 두께에 의해 형성되는 벽공간을 구비하고,상기 벽공간의 형상에 대응하는 형상의 회전소문을 더 포함하여,상기 회전소문을 상기 벽공간에 결합하거나 분리가 가능한 것을 특징으로 하는 벌통., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

537/1150 Row 537: application_number: 1020190172797, combined_string: invention_title: 환기 및 사양액 공급이 가능한 바닥판 구조를 갖는 벌통 abstract: 본 발명은 바닥면 및 벽면을 포함하는 벌통받침, 상기 벌통받침 상에 구비되는 벌통몸체 및 상기 벌통몸체의 상부를 덮는 벌통뚜껑으로 구성되는 벌통으로서, 환기를 위하여 벌통받침에 개방된 공간을 구비하고, 이 개방된 공간의 형상에 대응하는 형상의 채움수단을 포함하여 벌통 바닥에 분비물이나 찌꺼기가 쌓이거나, 소충 등이 기생할 수 있는 환경을 차단함으로써 최적의 꿀벌 사양 환경을 제공할 수 있다. claims: 바닥면 및 벽면을 포함하는 벌통받침, 상기 벌통받침 상에 구비되는 벌통몸체 및 상기 벌통몸체의 상부를 덮는 벌통뚜껑으로 구성되는 벌통으로서, 상기 벌통받침의 바닥면의 전부 또는 일부가 개방되어 바닥면의 두께에 의해 형성되는 바닥공간을 구비하고,상기 바닥공간의 형상에 대응하는 형상의 채움수단을 더 포함하여,상기 채움수단을 상기 바닥공간에 결합하거나 분리가 가능한 것을 특징으로 하는 벌통., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

538/1150 Row 538: application_number: 1020190171947, combined_string: invention_title: 여왕벌의 발현음을 이용한 여왕벌 탐지 방법 및 시스템 abstract: 여왕벌의 발현음을 이용한 여왕벌 탐지 방법 및 시스템이 개시된다. 일 실시예에 따른 여왕벌 탐지 방법은, 양봉통에 설치된 복수의 마이크들로부터 수집된 복수의 소리들을 수신하는 단계와, 상기 복수의 소리들에 기초하여 임계치를 초과하는 신호의 여부에 따라 상기 양봉통에 여왕벌이 존재하는지 여부를 판단하는 단계와, 상기 판단 결과에 따라 탐지 데이터를 생성하는 단계를 포함한다. claims: 양봉통에 설치된 복수의 마이크들로부터 수집된 복수의 소리들을 수신하는 단계;상기 복수의 소리들에 기초하여 임계치를 초과하는 신호의 여부에 따라 상기 양봉통에 여왕벌이 존재하는지 여부를 판단하는 단계; 및상기 판단 결과에 따라 탐지 데이터를 생성하는 단계를 포함하는 여왕벌 탐지 방법.여왕벌 탐지를 위한 인스트럭션들을 저장하는 메모리; 및상기 인스트럭션들을 실행하기 위한 프로세서를 포함하고,상기 인스트럭션들이 상기 프로세서에 의해 실행될 때, 상기 프로세서는,양봉통에 설치된 복수의 마이크들로부터 수집된 복수의 소리들을 수신하고,상기 복수의 소리들에 기초하여 임계치를 초과하는 신호의 여부에 따라 상기 양봉통에 여왕벌이 존재하는지 여부를 판단하고,상기 판단 결과에 따라 탐지 데이터를 생성하는여왕벌 탐지 장치., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

539/1150 Row 539: application_number: 1020190170638, combined_string: invention_title: 컨테이너를 이용한 식용곤충 양식 시설물 abstract: 본 발명은 식용곤충 양식을 위한 시설물에 관한 것으로, 좀 더 상세하게는 컨테이너에 유충과 성충 등을 분류해 담는 사육함을 적층해서 공간 활용율을 높이고 사육 인력과 활동범위를 최소화해서 양식 효율성을 높이는 컨테이너를 이용한 식용곤충 양식 시설물에 관한 것으로, 실내외 출입용 도어가 구성된 사육함 보관 기능의 컨테이너; 상기 컨테이너의 실내 공기 상태를 센싱해서 감지신호를 발신하는 실내환경 감지센서; 상기 컨테이너의 실내 공기를 조화하는 공조기; 상기 컨테이너 내에 급배수를 처리하며 급배수량을 체크하는 급배수기; 상기 감지신호에 따른 공기정보를 생성해서 공조기를 동작시키고, 상기 급배수량에 따른 급배수정보를 생성하며, 상기 공기정보와 급배수정보를 관리서버에 전송해서 온라인으로 공유시키는 터미널 서버;를 포함하는 것이다. claims: 실내외 출입용 도어가 구성된 사육함 보관 기능의 컨테이너;상기 컨테이너의 실내 공기 상태를 센싱해서 감지신호를 발신하는 실내환경 감지센서;상기 컨테이너의 실내 공기를 조화하는 공조기;상기 컨테이너 내에 급배수를 처리하며 급배수량을 체크하는 급배수기; 및상기 감지신호에 따른 공기정보를 생성해서 공조기를 동작시키고, 상기 급배수량에 따른 급배수정보를 생성하며, 상기 공기정보와 급배수정보를 관리서버에 전송해서 온라인으로 공유시키는 터미널 서버;를 포함하는 것을 특징으로 하는 컨테이너를 이용한 식용곤충 양식 시설물., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

540/1150 Row 540: application_number: 1020190169425, combined_string: invention_title: 사마귀 사육장치 abstract: 본 발명은 사마귀과 곤충의 사육장치에 관한 것으로, 더욱 상세하게는 갈색거저리유충(밀웜) 및 초파리의 특성을 활용한 먹이곤충을 별도로 사육하지 않으면서 사마귀과 곤충의 유충단계부터 성충단계까지 자동으로 먹이급여가 되는 사육장치에 관한 것이다. claims: 사마귀과 곤충을 사육할 수 있는 사육상자(10);사육상자(10) 안 하단부에 위치하는 갈색거저리유충(밀웜)의 급수층(20) 및 먹이층(30);사육상자(10) 안 급수층(20) 위에 위치하는 인큐베이터(40); 를 포함함을 특징으로 하는 사마귀과 곤충의 사육장치(100)본 발명에 따른 사마귀과 곤충의 사육장치(100)를 활용하여, 갈색거저리유충(밀웜) 및 초파리의 특성을 이용한 먹이곤충을 별도로 사육하지 않으면서 사마귀과 곤충의 유충단계부터 성충단계까지 물 분무방식으로 자동으로 먹이급여가 되는 사마귀과 곤충의 사육방법, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

541/1150 Row 541: application_number: 1020190166558, combined_string: invention_title: 양봉용 자동 사양기 abstract: 꿀벌 생태 환경 센서를 활용하여 양봉 벌통 내외 온도/습도/음향을 포함한 생태 환경 정보 수집하고 사양수 조절 기구에 의해 사양수의 공급 및 차단을 자동으로 조절할 수 있는 양봉용 자동 사양기가 제공된다. 양봉용 자동 사양기는 벌통의 내부에 삽입되어 배치되는 소초광의 크기에 대응되게 마련되며, 벌의 출입이 가능하도록 일측벽에 원호 형상의 출입용 슬릿이 형성되고 측벽에 센서 케이블 입구 홀이 형성되는 본체; 상기 본체의 내부 상단에 설치되어 유입되는 사양수의 공급 및 차단을 자동으로 조절하는 사양수 조절 기구; 상기 본체의 내부에 위치하여 벌통 내외 생태 환경을 감지하여 벌통 내외 생태 환경 정보를 출력하는 센서부; 및 상기 센서부에 전기적으로 연결되어 상기 센서부로부터의 상기 생태 환경 정보를 수집하여 상기 벌통 내의 생태 환경을 제어하고, 시간, 온도, 및 습도 설정치에 의해 상기 사양수 조절 기구로의 사양수 공급 시간대를 24절기 시기와 오전 일출 전과 일몰 후로 제어하고 벌통의 내부 및 외부 습도를 원하는 값으로 제어하는 사양 공급 제어기를 포함한다. claims: 벌통의 내부에 삽입되어 배치되는 소초광의 크기에 대응되게 마련되며, 벌의 출입이 가능하도록 일측벽에 원호 형상의 출입용 슬릿이 형성되고 측벽에 센서 케이블 입구 홀이 형성되는 본체;상기 본체의 내부 상단에 설치되어 유입되는 사양수의 공급 및 차단을 자동으로 조절하는 사양수 조절 기구;상기 본체의 내부에 위치하여 벌통 내외 생태 환경을 감지하여 벌통 내외 생태 환경 정보를 출력하는 센서부; 및상기 센서부에 전기적으로 연결되어 상기 센서부로부터의 상기 생태 환경 정보를 수집하여 상기 벌통 내의 생태 환경을 제어하고, 시간, 온도, 및 습도 설정치에 의해 상기 사양수 조절 기구로의 사양수 공급 시간대를 24절기 시기와 오전 일출 전과 일몰 후로 제어하고 벌통의 내부 및 외부 습도를 원하는 값으로 제어하는 사양 공급 제어기를 포함하는 양봉용 자동 사양기.벌통의 내부에 삽입되어 배치되는 소초광의 크기에 대응되게 마련되며, 벌의 출입이 가능하도록 일측벽에 원호 형상의 출입용 슬릿이 형성되고 측벽에 센서 케이블 입구 홀이 형성되는 본체;상기 본체의 내부 상단에 설치되어 유입되는 사양수의 공급 및 차단을 자동으로 조절하는 사양수 조절 기구;상기 본체의 내부에 위치하여 벌통 내외 생태 환경을 감지하여 벌통 내외 생태 환경 정보를 출력하는 센서부;상기 센서부에 전기적으로 연결되어 상기 센서부로부터의 상기 생태 환경 정보를 수집하여 상기 벌통 내의 생태 환경을 제어하고, 시간, 온도, 및 습도 설정치에 의해 상기 사양수 조절 기구로의 사양수 공급 시간대를 24절기 시기와 오전 일출 전과 일몰 후로 제어하고 벌통의 내부 및 외부 습도를 원하는 값으로 제어하는 사양 공급 제어기;상기 사양수 조절 기구로 공급되는 상기 사양수를 저장하는 사양수 통;일단은 사양수 통에 연결되고 타단은 상기 사양 공급 제어기에 연결되는 제1 사양수 공급 호스;일단이 상기 사양 공급 제어기에 연결되고 타단이 상기 사양수 조절 기구에 연결되는 제2 사양수 공급 호스를 포함하며,상기 사양수 조절 기구는상기 사양수가 유입되는 사양수 유입공이 형성되고 상기 사양수가 담기는 용기;하단이 상기 용기의 바닥에 놓이고 상기 용기에 상기 사양수가 채워지는 경우 부유하는 부유물; 및상기 부유물로부터 일체형으로 연장되어 형성되어 상기 부유물가 부유하는 경우 하강하여 상기 용기의 사양수 유입공을 막아 상기 사양수의 유입을 차단하는 돌출부를 포함하며,상기 용기는 홈이 형성된 수평 바닥면;상기 수평 바닥면으로부터 전방 상향으로 경사져 형성되고 수직으로 상기 사양수 유입공이 형성되어 있는 전방 경사면; 및상기 수평 바닥면으로부터 후방 상향으로 경사져 형성된 후방 경사면을 포함하고,상기 부유물의 하단이 상기 용기의 수평 바닥면의 홈에 삽입되어 상기 용기의 바닥에 놓이고 상기 용기에 상기 사양수가 채워지는 경우 상기 부유물은 부유하는 양봉용 자동 사양기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

542/1150 Row 542: application_number: 1020190167287, combined_string: invention_title: IoT기반 곤충사육 시스템 abstract: 본 발명은 IoT기반 곤충사육 시스템에 관한 것이다. 본 발명의 하나의 실시예에 따라, 이동설치가 가능하되, 유충사육실과 산란작업실을 구비한 컨테이너유닛; 컨테이너유닛의 중앙통로에 구비된 가이드유닛; 유충사육실과 산란작업실의 사이드 측에 설치된 적층 프레임유닛; 적층 프레임유닛에 다층으로 적층되되 유충 및 성충 각각의 사육공간이 되는 다수의 사육박스유닛; 가이드유닛을 따라 이동하며 사육박스유닛을 이송하는 대차유닛; 컨테이너 내부의 온도 및 습도를 감지하는 센서유닛; 및 센서유닛으로부터 획득된 데이터를 수신하고 유충 및 성충의 사육상태를 관리하는 관리시스템유닛을 포함하고, 대차유닛은 상하로 리프팅되며 적재된 사육박스유닛의 높이를 승강시키고, 적층 프레임유닛은 사육박스유닛을 지지하며 사육박스유닛의 적층 프레임유닛으로의 적층 및 적층 프레임유닛으로부터의 탈거가 가능하도록 슬라이딩하는 다수의 슬라이더를 포함하는 것을 특징으로 하는 IoT기반 곤충사육 시스템이 제안된다. claims: 이동설치가 가능하되, 유충사육실과 산란작업실을 구비한 컨테이너유닛;상기 컨테이너유닛의 중앙통로에 구비된 가이드유닛;상기 유충사육실과 산란작업실의 사이드 측에 설치된 적층 프레임유닛;상기 적층 프레임유닛에 다층으로 적층되되 유충 및 성충 각각의 사육공간이 되는 다수의 사육박스유닛;상기 가이드유닛을 따라 이동하며 상기 사육박스유닛을 이송하는 대차유닛;상기 컨테이너 내부의 온도 및 습도를 감지하는 센서유닛; 및상기 센서유닛으로부터 획득된 데이터를 수신하고 상기 유충 및 성충의 사육상태를 관리하는 관리시스템유닛을 포함하고,상기 대차유닛은 상하로 리프팅되며 적재된 상기 사육박스유닛의 높이를 승강시키고,상기 적층 프레임유닛은 상기 사육박스유닛을 지지하며 상기 사육박스유닛의 상기 적층 프레임유닛으로의 적층 및 상기 적층 프레임유닛으로부터의 탈거가 가능하도록 슬라이딩하는 다수의 슬라이더를 포함하는 것을 특징으로 하는 IoT기반 곤충사육 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

543/1150 Row 543: application_number: 2020190005034, combined_string: invention_title: 양봉 및 토봉 겸용 보온성 호환벌통 abstract: 본 고안은 벌통 안에서 생육되고 있는 벌들이 벌통 외부의 기온 및 환경 변화에 노출됨이 없이 보온과 단열을 통해 벌통 내부가 항상 적정 온도로 유지될 수 있도록 하고, 도봉의 피해를 최소화하며, 벌통을 양봉과 토봉으로 구분하여 각각 별도로 제작할 필요없이 하나의 벌통이 양봉 및 토봉의 용도로 함께 호환성을 갖고 사용할 수 있도록 한 양봉 및 토봉 겸용 보온성 호환벌통에 관한 것으로서, 그 구성은 소비통의 정면판 후면 양측, 및 배면판의 전면 양측에 서로 대향되게 형성되는 내향의 수직홈A,B와; 상기 소비통의 길이방향에 대하여 직각을 이루고, 양단부가 상기 수직홈A,B에 각각 수직방향으로 삽입되는 한쌍의 차단판A,B와; 상기 차단판A와 좌측판의 사이, 상기 차단판B와 우측판의 사이에 형성되는 제1,2 보온/단열공간부와; 상기 정.배면판의 내측 상부에 서로 대향되게 형성되는 양봉소비 걸이턱, 및 상기 좌.우측판 내측 상부에 형성되는 토봉소비 걸이턱과; 상기 좌.우측판의 하부 중간에 제1,2 소문이 형성되고, 상기 제1 소문과 대향되는 차단판B의 하부 중간에 제3 소문이 형성된 것이다. claims: 측면과 하부가 정.배면판(11)(12) 및 좌.우측판(13)(14)과 바닥판()에 의해 막히고 상부가 개방된 장방형체의 소비통(1)과, 상기 소비통(1)의 상단부 아래 각 측면을 따라 구비되는 지지대(1a)와, 상기 소비통(1)의 상부측 개방부를 개폐하고 일측면에 환기창(2a)를 갖는 소비통 덮개(2)로 구성됨에 있어서,상기 정면판(11)의 후면 양측, 및 배면판(12)의 전면 양측에 서로 대향되게 형성되는 내향의 수직홈A,B(21)(22)와; 상기 소비통(1)의 길이방향에 대하여 직각을 이루고, 양단부가 상기 수직홈A,B(21)(22)에 각각 수직방향으로 삽입되는 한쌍의 차단판A,B(23)(24)와;상기 차단판A(23)와 좌측판(13)의 사이, 상기 차단판B(24)와 우측판(14)의 사이에 형성되는 제1,2 보온/단열공간부(25)(26)와;상기 좌.우측판(13)(14)의 하부 중간에 형성되는 제1,2 소문(31)(32), 및 상기 제1 소문(31)과 대향되는 차단판B(24)의 하부 중간에 형성되는 제3 소문(33)과;상기 정.배면판(11(12)의 내측 상부에 서로 대향되게 형성되는 양봉소비 걸이턱(41), 및 상기 좌.우측판(13)(14) 내측 상부에 형성되는 토봉소비 걸이턱(42);으로 구성된 것을 특징으로 한 양봉 및 토봉 겸용 보온성 호환벌통., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

544/1150 Row 544: application_number: 1020190165620, combined_string: invention_title: 센서감지를 통해 작동하는 공기청정기 및 집진기가 구비된 반려동물용 배변케이지 abstract: 개시된 내용은, 내부에 모래가 수납되는 수납공간이 형성되는 하부하우징과 일측에는 반려동물이 출입하는 출입구를 포함하며 상기 하부하우징의 상부에 탈착 가능하게 결합 되고, 상부면에는 개구되어 형성되는 본체결합부가 형성되는 상부하우징과 상기 하부하우징 또는 상기 상부하우징의 일측에 형성되는 센서부와 상기 하부하우징 또는 상기 상부하우징의 일측에 형성되고, 상기 센서부와 전기적으로 결합 되는 전원부와 상기 본체결합부에 탈착 가능하게 결합 되며 내부에 필터부재가 구비되는 공기청정기와 상기 전원부와 전기적으로 연결되는 모터부와 상기 모터부의 회전축에 결합되어 회전하는 팬부로 구성되어, 상기 공기청정기의 상부에 탈착 가능하게 결합되는 구동부와 상기 센서부, 상기 전원부 및 상기 구동부와 전기적으로 연결되고, 상기 공기청정기의 일측에 형성되고, 상기 센서부를 통해 센싱된 신호를 기초로 상기 구동부의 구동을 제어하는 제어부를 포함하는 것을 특징으로 하는 센서감지를 통해 작동하는 공기청정기 및 집진기가 구비된 반려동물용 배변케이지에 관한 것이다. claims: 내부에 모래가 수납되는 수납공간이 형성되는 하부하우징;일측에는 반려동물이 출입하는 출입구를 포함하며 상기 하부하우징의 상부에 탈착 가능하게 결합 되고, 상부면에는 개구되어 형성되는 본체결합부가 형성되는 상부하우징;상기 하부하우징 또는 상기 상부하우징의 일측에 형성되는 센서부; 상기 하부하우징 또는 상기 상부하우징의 일측에 형성되고, 상기 센서부와 전기적으로 결합 되는 전원부; 상기 본체결합부에 탈착 가능하게 결합 되며 내부에 필터부재가 구비되는 하우징조립체;상기 전원부와 전기적으로 연결되는 모터부와 상기 모터부의 회전축에 결합되어 회전하는 팬부로 구성되어, 상기 하우징조립체의 상부에 탈착 가능하게 결합되는 구동부; 및 상기 센서부, 상기 전원부 및 상기 구동부와 전기적으로 연결되고, 상기 하우징조립체의 일측에 형성되고, 상기 센서부를 통해 센싱된 신호를 기초로 상기 구동부의 구동을 제어하는 제어부를 포함하는 것을 특징으로 하는 센서감지를 통해 작동하는 공기청정기 및 집진기가 구비된 반려동물용 배변케이지., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

545/1150 Row 545: application_number: 2020190005021, combined_string: invention_title: 곤충 사육 장치 abstract: 본 고안은 도미노 게임 완구에 관한 것으로, 보다 상세하게는 별도의 선반 등의 구조물 없이 2단 이상으로 안정적인 적층이 가능하여 소정의 면적 내에서 곤충 사육 공간의 용적률을 높여 곤충의 대량 사육 시 효율성을 높일 수 있으며, 내부 바닥면이 중앙부분을 향해 경사지게 형성됨으로써 적층한 상태에서도 세척이 가능한 것을 특징으로 하는 곤충 사육 장치에 관한 것이다. claims: 내부에 유충의 사육 가능한 사육 공간이 마련되며 상부가 개방되는 사각 함체 형상의 곤충 사육 박스;를 포함하며,상기 곤충 사육 박스는내부 바닥면은 중앙을 향해 하향 경사지게 이루어지고, 가로측벽과 세로측벽의 외측면과 내측면이 전체적으로 하부의 너비가 상부의 너비보다 크도록 상협하광의 형태로 이루어지되,상기 가로측벽에는 상단에서 하부로 일정간격 이격된 지점까지 개방되도록 형성되는 공기순환부;상기 곤충 사육 박스의 가로측벽과 세로측벽이 인접한 상단 모서리 부분에 상측방향으로 연장 형성된 적층돌출부; 및 상기 곤충 사육 박스의 외부 바닥면에는 상기 적층돌출부와 대응되는 형상의 적층홈;을 포함하며,상기 적층돌출부를 상기 적층홈에 끼워 다단으로 적층되어 별도의 선반구조물 없이 보관되고,상기 적층된 다수의 곤충 사육 박스를 결합할 수 있는 결합수단이 마련되되,상기 결합수단은상기 적층돌출부에는 수직방향으로 관통 형성되는 제1끼움홈;상기 적층홈에서 상기 측벽의 외측면까지 상기 제1끼움홈에 대응되는 위치에 형성되는 제2끼움홈; 및 상기 제1끼움홈 및 제2끼움홈을 관통하여 끼워지는 끼움봉;이 형성되어,적층된 상기 곤충 사육 박스의 분리 및 쓰러짐을 방지하는 것을 특징으로 하는 곤충 사육 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

546/1150 Row 546: application_number: 1020190160841, combined_string: invention_title: 월동용 말벌 케이지 abstract: 본 발명은 월동용 말벌 케이지로서, 상기 케이지의 길이 방향을 따라 길게 형성되고, 말벌 교미 여왕벌이 개별로 투입되는 수용홀; 및 상기 수용홀의 개방된 양단에 구비되어 상기 수용홀에 투입된 말벌 교미 여왕벌의 출입을 차단하는 차단부를 포함하는 것을 특징으로 한다.이러한 월동용 말벌 케이지는 말벌 교미 여왕벌이 수용홀의 내부에 개별로 투입된 후, 차단부에 의해 수용홀의 개방된 양단이 폐쇄될 수 있으므로, 외부의 빛이 수용홀의 내부 공간에 들어오는 것을 차단하여 여왕벌이 월동에 들어가기가 용이하며, 외부의 자연환경 변화에 따른 영향을 최소화할 수 있기 때문에 여왕벌의 생존율을 높일 수 있다. claims: 월동용 말벌 케이지로서,상기 케이지의 길이 방향을 따라 길게 형성되고, 말벌 교미 여왕벌이 개별로 투입되는 수용홀; 및상기 수용홀의 개방된 양단에 구비되어 상기 수용홀에 투입된 말벌 교미 여왕벌의 출입을 차단하는 차단부를 포함하는 것을 특징으로 하는 월동용 말벌 케이지., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

547/1150 Row 547: application_number: 1020190159735, combined_string: invention_title: 반려동물용 곤충 배출 장치 abstract: 곤충 배출 장치가 개시된다. 본 발명의 일 측면에 따르면, 곤충을 수용 가능한 내부 공간이 형성되며, 내부 공간에 수용된 곤충을 외부로 배출 가능한 개구부가 마련되는 케이스, 내부 공간에 수용된 곤충의 이탈을 방지하도록 개구부를 커버하며, 내측면이 외부를 향하도록 개구부에 회전 가능하게 설치되어, 내측면에 붙어 있는 곤충을 외부로 노출시키는 회전 부재, 케이스에 회전 부재 측으로 이동 가능하게 설치되어, 회전 부재의 회전에 따라 외부로 노출된 곤충이 회전 부재로부터 이탈되도록 유도하는 이탈 유도 부재, 및 회전 부재의 회전 및 이탈 유도 부재의 이동을 위한 구동력을 제공하는 구동 유닛을 포함하는 곤충 배출 장치가 제공된다. claims: 곤충을 수용 가능한 내부 공간이 형성되며, 상기 내부 공간에 수용된 곤충을 외부로 배출 가능한 개구부가 마련되는 케이스;상기 내부 공간에 수용된 곤충의 이탈을 방지하도록 상기 개구부를 커버하며, 내측면이 외부를 향하도록 상기 개구부에 회전 가능하게 설치되어, 내측면에 붙어 있는 곤충을 외부로 노출시키는 회전 부재;상기 케이스에 상기 회전 부재 측으로 이동 가능하게 설치되어, 상기 회전 부재의 회전에 따라 외부로 노출된 곤충이 상기 회전 부재로부터 이탈되도록 유도하는 이탈 유도 부재; 및상기 회전 부재의 회전 및 상기 이탈 유도 부재의 이동을 위한 구동력을 제공하는 구동 유닛을 포함하는 곤충 배출 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

548/1150 Row 548: application_number: 1020190159814, combined_string: invention_title: 생태순환적인 왕지네의 사육시스템 및 그러한 사육시스템의 구축방법 abstract: 본 발명은 내부로 바람이 통하고 비를 맞을 수 있도록 형성된 상부를 가지며, 바닥면의 일부 또는 전부는 토지로 이루어지고, 상기 내부로 햇볕을 받을 수 있는 하우스(H)와; 상기 하우스의 내부에 풀어지는 복수개의 왕지네(100)들과; 상기 하우스의 내부에 풀어지는 상기 왕지네의 먹이가 되는 먹이곤충(200)들과; 상기 하우스의 내부의 바닥면의 토지에서 자라는 것으로서, 상기 먹이곤충들이 먹이가 되는 식물(300)들과; 상기 하우스의 내부에 풀어지는 상기 먹이곤충의 사체를 분해하는 분해곤충(400)들과; 상기 하우스의 내부에 배치되는 상기 왕지네들이 기거하는 왕지네기거수단(110)(120)을 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템(1000)을 제공한다. claims: (a) 내부로 바람이 통하고 비를 맞을 수 있으며, 바닥면의 일부 또는 전부는 토지로 이루어지고, 상기 내부로 햇볕을 받을 수 있는 하우스와;(b) 상기 하우스의 내부에 풀어지는 복수개의 왕지네들과;(c) 상기 하우스의 내부에 풀어지는 상기 왕지네의 먹이가 되는 먹이곤충들과;(d) 상기 하우스의 내부의 바닥면의 토지에서 자라는 것으로서, 상기 먹이곤충들이 먹이가 되는 식물들과;(e) 상기 하우스의 내부에 풀어지는 상기 먹이곤충의 사체를 분해하는 분해곤충들과;(f) 상기 하우스의 내부에 배치되는 상기 왕지네들이 기거하는 왕지네기거수단을 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템.(a) 내부로 바람이 통하고 비를 맞을 수 있으며, 바닥면의 일부 또는 전부는 토지로 이루어지고, 상기 내부로 햇볕을 받을 수 있는 하우스를 제공하는 하우스 제공단계와;(b) 상기 하우스의 토지에 식물들이 살아나가도록 하는 식물생육단계와;(c) 상기 하우스의 내부에 왕지네들이 기거하는 왕지네 기거수단을 배치하는 왕지네기거수단배치단계와; (d) 상기 하우스의 내부에 복수개의 왕지네들과, 상기 왕지네의 먹이가 되는 것으로서 상기 식물들을 먹고사는 복수개의 먹이곤충들과, 상기 먹이곤충의 사체를 분해하는 복수개의 분해곤충들을 풀어 놓는 왕지네와 먹이곤충및 분해곤충의 풀어줌 단계를 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템의 구축방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

549/1150 Row 549: application_number: 1020190159817, combined_string: invention_title: 생태순환적인 왕지네의 사육시스템 abstract: 본 발명은 내부로 바람이 통하고 비를 맞을 수 있도록 형성된 상부를 가지며, 바닥면의 일부 또는 전부는 토지로 이루어지고, 상기 내부로 햇볕을 받을 수 있는 하우스(H)와; 상기 하우스의 내부에 풀어지는 복수개의 왕지네(100)들과; 상기 하우스의 내부에 풀어지는 상기 왕지네의 먹이가 되는 먹이곤충(200)들과; 상기 하우스의 내부의 바닥면의 토지에서 자라는 것으로서, 상기 먹이곤충들이 먹이가 되는 식물(300)들과; 상기 하우스의 내부에 풀어지는 상기 먹이곤충의 사체를 분해하는 분해곤충(400)들과; 상기 하우스의 내부에 배치되는 상기 왕지네들이 기거하는 왕지네기거수단(110)(120)을 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템(1000)을 제공한다. claims: (a) 내부에서 왕지네가 사육되는 것으로서 바닥면의 전부 또는 일부가 토지로 이루어진 하우스와;(b) 상기 하우스의 내부에 풀어지는 복수개의 왕지네들과;(c) 상기 하우스의 내부에 풀어지는 상기 왕지네의 먹이가 되는 먹이곤충들과;(d) 상기 하우스의 내부의 바닥면의 토지에서 자라는 것으로서, 상기 먹이곤충들이 먹이가 되는 식물들과;(e) 상기 하우스의 내부에 풀어지는 상기 먹이곤충의 사체를 분해하는 분해곤충들과;(f) 상기 하우스의 내부에 배치되는 상기 왕지네들이 기거하는 왕지네기거수단을 포함하여 이루어지는 것을 특징으로 하는 생태순환적인 왕지네 사육시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

550/1150 Row 550: application_number: 1020190158706, combined_string: invention_title: 폐버섯배지를 이용한 자연방사형 곤충사육방법 abstract: 폐버섯배지를 이용한 곤충 사육방법을 개시한다. 본 발명의 곤충 사육방법은 원통형이나 사각기둥형의 폐버섯배지를 수거하여 겉비닐을 제거한 폐버섯배지를 적재한 다음, 6월~9월 첫재 주까지만 운용하는 운용하는 차광시설을 배치하고, 5월~8월 31까지 관수하고, 6~8월에는 폐과일을 공급하여 서리가 내리기 전이나 3~4월에 수확한다. claims: 원통형이나 사각기둥형의 폐버섯배지를 수거하여 겉비닐을 제거한 폐버섯배지를 적재한 다음, 6월~9월 초까지만 운용하는 운용하는 차광시설을 배치하고, 5월~8월 말까지 관수하고, 6~8월에는 폐과일을 공급하여 서리가 내리기 전이나 3~4월에 수확함을 특징으로 하는, 폐버섯배지를 이용한 자연방사형 곤충 사육방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

551/1150 Row 551: application_number: 1020190158927, combined_string: invention_title: 먹이보상이 가능한 반려동물용 운동장치 abstract: 내측에 반려동물이 운동할 수 있는 공간인 운동공간부가 형성되고, 내주면에 구비되며 반려동물이 운동공간부 내에서 지속적으로 움직이며 운동할 수 있는 회전모듈; 상기 회전모듈에 반려동물이 움직임에 따라 회전모듈이 회전 가능하도록 지지하는 지지모듈; 상기 회전모듈 내측면에는 회전모듈의 회전수에 따라 간식이 공급되는 먹이공급부가 형성되며; 상기 먹이공급부의 작동 제어 및 회전모듈의 회전수에 따른 간식량을 설정하는 제어모듈; 및 제어모듈로 전송되는 먹이공급부의 동작제어신호를 송신하는 통신부를 포함하는 단말기로 이루어진 먹이보상이 가능한 반려동물용 운동장치를 제공함으로써, 반려동물이 목표와 동기를 가지고 운동을 보다 능동적으로 실시할 수 있도록 함과 더불어 장기적인 운동이 가능하여 실내에서만 활동하는 반려동물의 건강을 증진시킬 수 있는 효과가 있다. claims: 내측에 반려동물이 운동할 수 있는 공간인 운동공간부가 형성되고, 내주면에 구비되며 반려동물이 운동공간부 내에서 지속적으로 움직이며 운동할 수 있는 회전모듈; 상기 회전모듈에 반려동물이 움직임에 따라 회전모듈이 회전 가능하도록 지지하는 지지모듈; 상기 회전모듈 내측면에는 회전모듈의 회전수에 따라 간식이 공급되는 먹이공급부가 형성되며; 상기 먹이공급부의 작동 제어 및 회전모듈의 회전수에 따른 간식량을 설정하는 제어모듈; 및 제어모듈로 전송되는 먹이공급부의 동작제어신호를 송신하는 통신부를 포함하는 단말기로 이루어진 것인 먹이보상이 가능한 반려동물용 운동장치, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

552/1150 Row 552: application_number: 1020200124764, combined_string: invention_title: 열화상 카메라를 이용한 젖소 질병관리 시스템 abstract: 본 발명의 일 실시예에 따른 젖소의 질병관리 시스템은 젖소의 이동통로에 위치하여 젖소에 장착된 생체측정장치로부터 생체정보를 수신하는 젖소 식별장치, 상기 이동통로에 위치하는 복수의 열화상 카메라, 젖소의 질병 및 건강 상태에 따라 젖소를 착유소 또는 질병치료소 중 하나로 가이드하는 게이트를 개폐하는 가이드 장치, 및 상기 젖소 식별장치로부터 젖소의 생체정보 및 상기 복수의 열화상 카메라로부터 촬영된 열화상을 수신하여, 해당 젖소의 유방염 및 발목병 발생여부를 판단하고, 유방염 및 발목병 발생여부에 따라 상기 가이드 장치를 제어하는 제어신호를 송신하는 제어부를 포함한다. claims: 젖소의 귀에 장착되어 체온을 포함하는 생체정보 및 움직임정보를 측정하는 생체측정장치;젖소의 이동통로에 위치하여 상기 생체측정장치로부터 생체정보를 수신하는 젖소 식별장치;상기 이동통로에 위치하는 복수의 열화상 카메라;젖소의 질병 및 건강 상태에 따라 젖소를 착유소 또는 질병치료소 중 하나로 가이드하는 게이트를 개폐하는 가이드 장치; 및상기 젖소 식별장치로부터 생체정보 및 상기 복수의 열화상 카메라로부터 촬영된 열화상을 수신하고, 상기 생체정보에 포함된 제1 체온 및 상기 열화상으로부터 도출되는 제2 체온을 이용하여 해당 젖소의 유방염 및 발목병 발생여부를 판단하고, 유방염 및 발목병 발생여부에 따라 상기 가이드 장치를 제어하는 제어신호를 송신하는 제어부를 포함하고,상기 복수의 열화상 카메라는,상기 이동통로 양측면에 위치하여 유방 및 발목을 촬영하는 제1 및 제2 열화상 카메라; 및상기 이동통로의 바닥면에 위치하여 유선 및 유두를 촬영하는 제3 열화상 카메라를 포함하는 젖소의 질병관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

553/1150 Row 553: application_number: 1020200122826, combined_string: invention_title: 축산동물의 유방염 진단방법 및 진단장치 abstract: 본 발명은 본 발명은 우유를 착유할 때 신선한 고품질의 우유인지 유방염에 걸린 젖산우유인지를 즉시 감지하기 위한 축산동물의 유방염 진단방법 및 진단장치에 관한 것으로 특히 RFID센서 및 유방염 착유검취필터를 이용하여 젖소 등의 유방염을 더욱 정밀하고 신속하게 진단하면서 계속적인 모니터링이 가능한 유방염 진단방법 및 진단장치에 관한 것에 관한 것으로, 본 발명의 목적을 실현하기 위한 본 발명의 구성은 축산동물의 착유정보를 관리하기 위해 부착되어 식별 가능한 고유신호를 발생하는 태깅(tagging)된 동물개체로부터 고유신호를 수신하는 사업자의 착유정보판독서버(100)와, 축산동물 착유시 착유기(200)의 착유라인에 탈부착이 가능한 착유검취필터(210)로 상기 착유정보를 추출하는 착유정보검취부(220), 그리고 상기 착유정보를 기 저장하고 있는 착유정보데이터베이스(DB)(120); 와, 상기 착유정보를 기 저장하고 있는 착유정보데이터베이스(DB)와, 상기 착유정보판독서버(100)로부터 수신된 고유신호를 이용하여 상기 착유정보데이터베이스(DB)(120)부터 상기 착유정보검취부(220)로부터 착유검취물의 착유정보를 추출한 착유정보로 상기 착유정보데이터베이스(DB)(120)에 구현되는 유방염진단 프로그램으로 유방염 감염 및 예후를 진단하는 유방염진단부(122) 및 상기 유방염진단부로부터 유방염진단과 관련한 착유정보를 실시간 수신받은 사용자 단말기(300)를 포함하여 구성되는 축산동물의 유방염 진단방법 및 이를 구현하는 장치로 구성되는 것을 특징으로 한다. claims: 축산동물의 착유정보를 관리하기 위해 부착되어 식별 가능한 고유신호를 발생하는 태깅(tagging)된 동물개체로부터 고유신호를 수신하는 사업자의 착유정보판독서버(100); 축산동물 착유시 착유기(200)의 착유라인에 탈부착이 가능한 착유검취필터(210)로 상기 착유정보를 추출하며, 상기 착유검취필터(210)에 검취된 고형물을 촬상하기 위한 촬상모듈(221)와 촬상모듈(221)과 연동되어 음성정보의 저장 및 송수신이 가능한 음성모듈(222)을 포함하여 구성되는 착유정보검취부(220); 상기 착유정보를 기 저장하고 있는 착유정보데이터베이스(DB)(120); 상기 착유정보판독서버(100)로부터 수신된 고유신호를 이용하여 상기 착유정보데이터베이스(DB)(120)부터 상기 착유정보검취부(220)로부터 착유검취물의 착유정보를 추출한 착유정보로 상기 착유정보데이터베이스(DB)(120)에 구현되는 유방염진단 프로그램으로 유방염 감염 및 예후를 진단하는 유방염진단부(122); 및 상기 유방염진단부로부터 유방염진단과 관련한 착유정보를 실시간 수신받은 사용자 단말기(300);를 포함하여 구성되는 축산동물의 유방염 진단장치.축산동물의 착유정보를 관리하기 위해 부착되어 식별 가능한 고유신호를 발생하는 태깅(tagging)된 동물개체로부터 고유신호를 수신하는 사업자의 착유정보판독서버(100)에서 착유정보를 판독하여 축산동물의 유방염 진단방법에 있어서, 상기 사업자의 착유정보판독서버(100)에서 착유정보를 판독하기 위하여 실시간 연동되는 착유정보검취부(220)에 의하여 축산동물 착유시 착유기(200)의 착유라인에 탈부착이 가능한 착유검취필터(210)에서 상기 착유정보를 추출하여 검취하되, 상기 착유정보검취부(220)에서 촬영모듈(221)를 이용하여 착유검취물의 착유정보를 추출하는 착유정보검취단계에서 음성모듈(222)을 더 이용하여 상기 착유정보에 대한 음성정보를 송수신하기 위해 저장되어 상기 착유정보를 더 추출하여 검취하는 착유정보검취단계; 상기 착유정보판독서버(100)에 수신된 고유신호를 이용하여 착유정보데이터베이스(DB)부터 상기 착유정보검취부(220)로부터 착유검취물의 착유정보를 추출하여 유방염 감염 및 예후를 진단하는 유방염 진단단계; 상기 유방염 진단단계에서 추출된 착유정보와 진단정보가 착유정보데이터베이스(DB)(120)에 실시간 수신되어 전자화된 문서정보 또는 이미지의 기록매체를 자동으로 생성 및 저장되는 착유정보 데이터 저장단계; 및상기 착유정보검취부(220)에서 착유검취필터(210)에 걸리는 착유된 검취물의 촬영된 이미지로 연산하는 유방염진단 프로그램을 이용하여 검취된 고형물의 확인된 2차원 면적값의 계산에 의하여 유방염을 진단하는 유방염 감염 및 예후를 진단하는 유방염진단부(122)에서 판단되면 유방염진단 여부를 디스플레이부(110)에 송수신하는 디스플레이 송수신단계;를 더 포함하여 구성되는 것을 특징으로 하는 축산동물의 유방염 진단방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

554/1150 Row 554: application_number: 1020200121813, combined_string: invention_title: 축사정보에 따른 먹이공급 자동화시스템 abstract: 본 발명은 축사에서 길러지는 가축과 관리자의 이동에 방해를 주지 않고, 축사의 먹이통에 먹이를 공급하는 축사정보에 따른 먹이공급 자동화시스템을 제공하는 것을 목적으로 한다. 본 발명은 축사의 먹이통 위에서 먹이를 공급함으로써 축사에서 길러지는 가축과 관리자의 이동에 방해를 주지 않고, 축사에서 길러지는 가축 종류, 가축 생육에 요구되는 먹이 종류에 맞게 축사의 먹이통에 먹이를 공급함으로써 가축의 생육 조건을 만족시킬 수 있고, 축사의 먹이통에 먹이를 공급하는 이동식 먹이통을 다수 개 구성함으로써 먹이 공급을 끊김 없이 원활하게 하고, 가축 생육에 도움을 주는 효과를 가질 수 있다. claims: 축사(70) 위에 설치되는 레일(40);상기 레일(40)을 따라 이동하면서 상기 축사(70)의 먹이통(60)에 먹이를 공급하는 이동식 먹이통(20);상기 이동식 먹이통(20)을 이동시키는 구동부(30); 및상기 이동식 먹이통(20)에 먹이를 공급하는 호퍼(10);를 포함하고,상기 이동식 먹이통(20)은,상기 이동식 먹이통(20)에 공급되는 먹이의 양을 감지하여 기설정된 먹이양을 저장하는 저장센서(22); 및저장된 먹이양 중 상기 축사(70)의 먹이통(60)에 공급될 먹이양을 감지하여 기설정된 먹이양을 분배하는 분배센서(21);를 포함하고,상기 축사(70)의 먹이통(60)과 연결된 기둥에 표시된 식별 정보를 인식하고, 인식된 식별 정보를 참조하여 상기 먹이통(60)에 먹이를 공급하고,손상된 식별 정보를 인식하지 못하는 경우, 기둥(71)에 설치된 디스플레이(52)에 포함된 통신부와 통신해서 상기 축사(70)의 먹이통(60)에 설정된 정보를 수신하고, 수신된 정보에 따라 상기 축사(70)의 먹이통(60)에 먹이를 공급하고, 식별 정보 인식과 디스플레이(52)의 통신부 연결을 통해 정보 송수신을 이중화하여 상기 축사(70)의 먹이통(60)에 불특정 사유로 인한 먹이 공급 중단 없이 항상 먹이를 공급하고,상기 레일(40)의 전원 공급 장치(41)로부터 전원을 공급받아 동작 전원으로 사용하고, 개별 제어 또는 중앙 통제 제어되고,상기 레일(40)의 전원 공급 장치(41)는 무선 전원 공급 장치이고,상기 구동부(30)는,상기 레일(40) 상에 위치하여 상기 이동식 먹이통(20)을 연결하여 이동시키고,상기 호퍼(10)는,대용량의 먹이를 저장하고, 상기 이동식 먹이통(20)이 먹이 공급을 요청하면 상기 이동식 먹이통(20)에 기설정된 먹이양을 공급하고,기설정된 레벨 미만으로 저장된 먹이양이 줄어들면 외부 먹이 공급차(90)에 먹이 공급을 요청하고,상기 먹이 공급차(90)는,먹이 공급 요청에 응답해서 상기 호퍼(10)에 다량의 먹이를 공급하고,상기 축사(70)의 기둥(71)은,상기 축사(70)에서 양육되는 가축의 종류, 가축 마리수, 생육 정도 및 상기 이동식 먹이통(20)의 먹이 공급 회수를 표시하는 디스플레이(52)를 포함하고,상기 이동식 먹이통(20)과 상기 축사(70)의 먹이통(60)은,먹이 관로(80)로 연결되고,레일(40) 위에는 먹이 종류별로 다수의 이동식 먹이통(20)이 위치하고, 이동식 먹이통(20) 내부에 다수의 이동식 먹이통(20)이 구성되며, 이동식 먹이통(20) 내부에 구성된 다수의 이동식 먹이통(20)은 TMR(Total mixed Ration) 사료로 구성된 먹이가 종류별로 구성되는 것을 특징으로 하는, 축사정보에 따른 먹이공급 자동화시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

555/1150 Row 555: application_number: 1020200081093, combined_string: invention_title: 축사 습도 연동형 기능성 냉풍기 abstract: 본 발명은 축사 습도 연동형 기능성 냉풍기에 관한 것으로서, 육면체 박스 형태를 가지는 것으로 개구된 4 개의 제1,2,3,4측면개구부(11)(12)(13)(14), 상기 제1,2,3,4측면개구부(11)(12)(13)(14)의 하부측에 형성된 저수조(15) 및 저수조(15)의 상부측으로 돌출된 테이블(16)을 가지는 냉풍기몸체(10)와; 냉풍기몸체(10)의 상부측에 설치되어 축사(C)와 연결되는 배기덕트(20)와; 냉풍기몸체(10)에 내부에서 제1,2,3,4측면개구부(11)(12)(13)(14)를 막도록 설치되는 것으로서, 종이 재질로 되고 다수의 통풍구멍이 형성된 제1,2,3,4쿨링패드(31)(32)(33)(34)와; 저수조(15)로 물을 공급하는 물공급부(50)와; 저수조(15)에 수용된 물을 제1,2,3,4쿨링패드(31)(32)(33)(34)의 상부측으로 공급하는 순환공급부(60)와; 배기덕트(20) 하부측에 설치된 것으로서, 제1,2,3,4에어필터부(41)(42)(43)(44) 및 제1,2,3,4쿨링패드(31)(32)(33)(34)를 통하여 유입된 공기를 상기 배기덕트(20)로 송풍시키는 송풍팬(70)과; 축사(C) 내부의 습도를 측정하여 대응되는 습도신호(H)를 발생하는 습도측정부(80)와; 테이블(16)에 설치되어 상기 습도신호(H)에 연동되어 상기 순환공급부(60) 및 송풍팬(70)의 동작을 제어하는 제어부(100);를 포함하는 것을 특징으로 한다. claims: 육면체 박스 형태를 가지는 것으로 개구된 4 개의 제1,2,3,4측면개구부(11)(12)(13)(14), 상기 제1,2,3,4측면개구부(11)(12)(13)(14)의 하부측에 형성된 저수조(15) 및 저수조(15)의 상부측으로 돌출된 테이블(16)을 가지는 냉풍기몸체(10);상기 냉풍기몸체(10)의 상부측에 설치되어 축사(C)와 연결되는 배기덕트(20);상기 냉풍기몸체(10)에 내부에서 상기 제1,2,3,4측면개구부(11)(12)(13)(14)를 막도록 설치되는 것으로서, 종이 재질로 되고 다수의 통풍구멍이 형성된 제1,2,3,4쿨링패드(31)(32)(33)(34);상기 저수조(15)로 물을 공급하는 물공급부(50);상기 저수조(15)에 수용된 물을 상기 제1,2,3,4쿨링패드(31)(32)(33)(34)의 상부측으로 공급하는 순환공급부(60);상기 배기덕트(20) 하부측에 설치된 것으로서, 상기 제1,2,3,4쿨링패드(31)(32)(33)(34)를 통하여 유입된 공기를 상기 배기덕트(20)로 송풍시키는 송풍팬(70); 축사(C) 내부의 습도를 측정하여 대응되는 습도신호(H)를 발생하는 습도측정부(80); 상기 테이블(16)에 설치되어 상기 습도신호(H)에 연동되어 상기 순환공급부(60) 및 송풍팬(70)의 동작을 제어하는 제어부(100);상기 저수조(15)의 물에 포함된 이물질 입자에 의한 탁도가 설정탁도(D) 이상이 될 때 세척경고신호(S)를 발생하는 탁도감지부(110); 상기 물공급부(50)와 독립된 구성으로서 상기 세척경고신호(S)에 연동되어 상기 저수조(15) 바닥으로 세척수를 분사하는 세척수노즐(120); 및상기 저수조(15) 바닥과 연결되는 것으로서 상기 저수조(15) 바닥을 세척한 세척수를 드레인하기 위한 드레인관(131)을 선택적으로 개폐하는 드레인밸브(130)를 포함하고;상기 저수조(15)는, 전체적으로 도넛 형태를 이루고, 일측이 높은 상부단(15a)과 타측이 낮은 하부단(15b)으로 구성되고, 상부단(15a)과 하부단(15b) 사이는 비스듬한 경사면(15c)이 형성된 구조를 가지고;상기 세척수노즐(120)은, 상기 저수조(15) 내측의 상부단(15a)에 설치되고;상기 드레인밸브(130)의 드레인관(131)은 상기 저수조(15) 내측의 하부단(15b)에 연결된 것;을 특징으로 하는 축사 습도 연동형 기능성 냉풍기., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

556/1150 Row 556: application_number: 1020200076368, combined_string: invention_title: 자연 환기형 축사 abstract: 본 발명은 자연 환기형 축사에 관한 것으로, 자연 공기 순환방식으로 환기가 이루어져 종래 환풍팬을 구비하는 축사에 비해 관리비용을 절감할 수 있으며, 가축들에게 쾌적한 환경을 제공 함을 목적으로 한다.본 발명에 따른 자연 환기형 축사는, 축사본체, 상기 축사본체의 상부에 배치되는 상부 지붕, 상기 상부 지붕의 일측과 타측 하부에 각각 소정간격 이격되도록 배치되어 공기통로를 형성하는 하부 지붕을 포함한다. claims: 축사본체,상기 축사본체의 상부에 배치되는 상부 지붕,상기 상부 지붕의 일측과 타측 하부에 각각 소정간격 이격되도록 배치되어 공기통로를 형성하는 하부 지붕을 포함하고,상기 축사본체는,상기 하부 지붕의 가장자리를 일정 간격으로 지지하며, 그 내측에 축사공간을 형성시키는 제1 서포트,상기 제1 서포트의 사이 공간을 폐쇄하는 벽체부,상기 축사공간에서 상기 상부 지붕을 일정간격으로 지지하는 제2 서포트를 포함하며,상기 제1 서포트와 하부 지붕을 결합시키는 결합부를 포함하고,상기 결합부는 상기 제1 서포트의 상측에 형성되고 상기 하부 지붕의 저면에 접촉되는 플랜지, 상기 플랜지의 체결홀과 상기 하부 지붕의 체결홀에 공동으로 체결되는 탄성후크유닛을 포함하고,상기 탄성후크유닛은 탄성안내바, 상기 탄성안내바의 끝단 외측으로 돌출되게 형성되어 상기 하부지붕에 걸리는 걸림돌부를 포함하며,상기 탄성안내바에는 서로 일정간격 이격되는 완충슬릿홀이 형성되고,상기 탄성안내바의 전면부에는 플랜지의 체결홀과 하부 지붕의 체결홀의 내측면을 가압하는 탄성지지바가 더 부착되며,상기 탄성안내바의 전면에는 플랜지의 체결홀과 하부 지붕의 체결홀의 내측면과 마찰됨과 아울러 걸림되도록 요철돌부들이 더 형성되고,상기 탄성안내바의 배면부에는 길이방향을 따라 지지림부들이 더 형성되는 자연 환기형 축사., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

557/1150 Row 557: application_number: 1020200074536, combined_string: invention_title: 통합형 착유 장치 abstract: 통합형 착유 장치를 개시한다.본 실시예는 젖소의 우유를 착유하는 공정에서 소요되는 착유시간을 줄이고 빠른 착유시간을 확보하기 위해 세척 공정, 전착유 공정, 착유 공정 및 침지 공정을 하나의 프로세스로 통합하여 착유컵의 부착만으로 착유와 관련된 모든 프로세스가 한 번에 이루어지도록 하여 착유에 소요되는 시간을 단축하는 동시에 착유에 필요한 노동력을 절감시킬 수 있는 통합형 착유 장치를 제공한다. claims: 젖소의 유두를 감싸는 형태로 상기 유두에 직접 체결되어 상기 유두로부터 착유한 우유가 일차적으로 담기도록 하는 착유컵;상기 착유컵의 일측에 세척배관으로 연결되어, 착유 시작전에 고압으로 세척액을 분사하여 상기 착유컵 내에 삽입된 상기 유두를 세척하는 세척액 분사부;상기 착유컵의 타측과 제1 착유배관으로 연결되며, 상기 착유컵으로부터 전착유 공정으로 기 설정된 횟수로 착유된 우유를 상기 제1 착유배관으로 입력받아 보관하는 배수탱크;상기 착유컵의 타측과 상기 제1 착유배관을 분기하여 연결되며, 상기 착유컵으로부터 상기 전착유 공정이 완료된 후 착유된 우유를 상기 제1 착유배관으로 입력받아 보관하는 우유집유 탱크;상기 배수탱크와 상기 우유집유 탱크와 제2 착유배관으로 연결되고, 상기 제2 착유배관으로부터 내부 공기를 빨아들여 외부로 배출하여 상기 착유컵 내에 삽입된 상기 유두로부터 우유를 착유하는 진공펌프;상기 진공펌프를 제어하여 상기 착유컵 내에 삽입된 상기 유두로부터 착유된 우유가 상기 배수탱크 및 상기 우유집유 탱크 중 어느 하나로 입력되도록 제어하는 제어부;상기 착유컵의 일측에 침지배관으로 연결되어, 착유가 완료된 후 침지제를 분사하여 상기 착유컵 내에 삽입된 상기 유두가 침지되도록 하는 침지제 분사부;상기 세척배관과 상기 침지배관은 하나로 통합된 통합배관으로 상기 착유컵의 일측에 연결되고, 상기 통합배관의 일측에 설치되어, 고압으로 에어를 분사하여 상기 세척액 또는 상기 침지제가 상기 착유컵 내에 삽입된 상기 유두로 분사되도록 하는 에어 분사부;을 포함하되,상기 세척액 분사부, 상기 침지제 분사부, 상기 에어 분사부를 연결하는 체결 뭉치 형태의 셀렉터 부재를 배열하는 1단; 상기 세척액 분사부에 포함된 세척액 분사 펌프와 상기 침지제 분사부에 포함된 침지제 분사 펌프를 배열하는 2단; 복수의 배관이 통과하는 배관 통과홀을 포함하는 3단;을 포함하며, 상기 1단, 상기 2단, 상기 3단이 적층 구조를 가지며,상기 셀렉터 부재는, 상기 세척액 분사부와 상기 세척배관으로 연결되는 세척배관 연결부; 상기 침지제 분사부와 상기 침지배관으로 연결되는 침지배관 연결부; 상기 에어 분사부와 직접 연결되는 에어분사 연결부; 상기 착유컵과 상기 통합배관으로 연결되는 통합배관 연결부; 상기 1단의 바닥면에 연결되어 고정되는 본체 하우징;을 포함하며,상기 본체 하우징은 ∧ 형상을 갖는 정면부; 상기 정면부와 이어지는 형태로 돌출되어 기 설정된 기울기를 갖는 돌출부; 상기 돌출부와 이어지는 형태로 평면을 갖는 상면부;를 포함하며,상기 정면부의 ∧ 형상의 각 면에 상기 세척배관 연결부와 상기 침지배관 연결부가 각각 형성되는 Y자 구조를 가지며, 상기 돌출부의 기울기를 갖는 면에 상기 에어분사 연결부가 형성되며, 상기 정면부의 ∧ 형상을 갖는 반대면에 상기 통합배관 연결부가 형성되는 구조를 갖는 것을 특징으로 하는 통합형 착유 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

558/1150 Row 558: application_number: 1020200074537, combined_string: invention_title: 3D 카메라를 이용한 유두 인식 방법 및 장치 abstract: 3D 카메라를 이용한 유두 인식 방법 및 장치를 개시한다.본 실시예는 젖소로부터 우유를 무인 착유하기 위한 로봇 착유기에 이용되는 기술로서 3D 카메라를 이용하여 젖소의 엉덩이, 꼬리 위치, 유방 및 유두를 구분하여 인식하고, 유두의 ��향 및 위치를 판별하여 꼬리 부분에서 유두의 위치가 어느 정도에 포진하고 있는지를 확인한 후 좌표화하여 로봇암(Robot Arm)이나 매니퓰레이터(Manipulator)를 이용하여 착유컵을 유두로 이동 및 착유할 수 있도록 하는 3D 카메라를 이용한 유두 인식 방법 및 장치를 제공한다. claims: 유두 인식 장치가 유두를 인식하는 방법에 있어서,착유실의 케이지(Cage)의 천장에 설치된 꼬리 인식용 카메라를 이용하여 젖소의 꼬리를 포함하는 엉덩이 영역을 촬영한 엉덩이 영역 영상 데이터를 획득하는 과정;상기 엉덩이 영역 영상 데이터를 분석하여 상기 젖소의 꼬리 위치를 결정하는 과정;상기 꼬리 위치를 기반으로 젖소의 유방과 젖꼭지의 예상위치를 산출하는 과정;로봇암을 이용하여 상기 로봇암에 부착된 착유컵 그립퍼의 일측에 부착된 유두 인식용 카메라를 상기 유방과 젖꼭지의 예상위치로 이동시키는 과정;상기 유두 인식용 카메라를 이용하여 유두 영역을 촬영한 유두 영역 영상 데이터를 획득하는 과정;상기 유두 영역 영상 데이터를 분석하여 유두 예상 위치를 산출하는 과정; 및상기 로봇암을 이용하여 상기 유두 예상 위치로 상기 착유컵 그립퍼에 체결된 착유컵을 이동시킨 후 착유를 수행하도록 하는 과정을 포함하되, 상기 꼬리 인식용 카메라는 엉덩이 영역에 대한 3D 데이터와 2D 이미지를 조합한 상기 엉덩이 영역 영상 데이터를 획득하며, 상기 유두 인식용 카메라는 유두 영역에 대한 3D 데이터와 2D 이미지를 조합한 상기 유두 영역 영상 데이터를 획득하며,상기 유두 예상 위치를 산출하는 과정은, 이동하는 상기 로봇암에 부착된 상기 유두 인식용 카메라로부터 획득한 상기 유두 영역의 3D 데이터에서 젖소의 유방 영역 포인트 클라우드를 획득하고, 상기 로봇암이 x,y,z 방향으로 변위하고 회전할 때, 상기 유두 인식용 카메라에 부착된 좌표계를 이용하여 카메라의 위치 및 방향에 따라 측정한 포인트 클라우드 데이터를 로봇 좌표계상의 데이터로 변환하며, 상기 젖소의 꼬리 위치를 결정하는 과정은, 케이지 내부의 로봇 좌표계상의 3차원 공간을 설정하고, 상기 3차원 공간 내에서 상기 꼬리 인식용 카메라의 설치 위치를 설정하고, 상기 꼬리 인식용 카메라로부터 획득한 엉덩이 영역에 대한 3D 데이터 내의 포인트 클라우드에서 케이지 내부의 영역만을 추출하고, 상기 케이지 내부의 영역에서 젖소의 엉덩이 영역만을 추출하고, 상기 젖소의 엉덩이 영역만을 이진화한 영상으로 변환하며,상기 유두 예상 위치를 산출하는 과정은, 상기 유두 인식용 카메라로부터 획득한 유두 영역에 대한 3D 데이터 내의 포인트 클라우드에서 유두의 영역만을 추출하고, 상기 유두 영역만을 이진화한 영상으로 변환한 유두 이진화 영상을 생성하고, 상기 유두 이진화 영상에서 잡음을 제거한 잡음 제거 영상을 생성하고, 상기 잡음 제거 영상에서 유두 외곽선을 추출한 유두 외곽선 영상을 생성하고, 상기 유두 외곽선 영상에 하우스도르프 거리(Hausdorff Distance) 기반으로 유두 외곽선을 단순화한 외곽선 단순화 영상을 생성하고, 상기 외곽선 단순화 영상에서 유두를 인식하는 것을 특징으로 하는 유두 인식 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

559/1150 Row 559: application_number: 1020200064329, combined_string: invention_title: 우사용 위생 급수조 abstract: 본 발명은 우사에서 사용되는 급수조에 관한 것으로서, 보다 상세하게 설명하면, 축사에 사용되는 종래의 급수장치 중 우사에서 사용되는 급수조에 소가 혀를 이용하여 물을 튀기는 장난을 하거나 물을 걷어내는 음용습관에 의해 급수조의 외측으로 물이 비산되는 것을 차단부를 설치하여 방지함으로써, 음용수의 소실, 우사의 바닥오염을 최소화할 수 있고, 이에 따라 급수조의 위생 및 관리의 용이성을 향상시킬 수 있는 우사용 위생 급수조에 관한 기술분야가 개시된다. claims: 상부면에 물이 담기는 적어도 하나의 음용홈(110)이 형성된 베이스몸체(100);와음용방향을 제외한 상기 베이스몸체(100)의 상부면에 하부가 결합되되, 상기 음용홈(110)의 둘레에 위치되도록 결합되는 차단부(200);를 포함하여 구성되고,상기 차단부(200)는상부로 갈수록 상기 베이스몸체(100)의 외측방향으로 기울어져 형성되며,상기 차단부(200)는상기 베이스몸체(100)의 상부면 전방에 하부가 힌지 결합되어 상기 베이스몸체(100)의 외측방향으로 접철되는 전방차단프레임(210);과상기 베이스몸체(100)의 상부면 양측에 각각 하부가 힌지 결합되어 상기 베이스몸체(100)의 외측방향으로 접철되는 측면차단프레임(220);을 포함하여 구성되고,상기 전방차단프레임(210)과 측면차단프레임(220)은상기 베이스몸체(100)의 상부방향으로 펼쳤을 때, 상기 전방차단프레임(210)의 일측 또는 타측에 상기 측면차단프레임(220)의 전방이 결합되어 차단부(200)를 형성하는 것을 특징으로 하며,상기 전방차단프레임(210)은일측과 타측 내부에 내입되어 설치되는 적어도 하나의 제1자석(212);을 포함하여 구성되고,상기 측면차단프레임(220)은전방 내부에 내입되어 설치되어 상기 제1자석(212)과 대응되는 제2자석(222);을 포함하여 구성되는 한편,상기 전방차단프레임(210)과 측면차단프레임(220)은상측 내부에 내입되어 설치되는 적어도 하나의 제3자석(216)(226);을 포함하여 구성되고,상기 차단부(200)는상부에 결합되어 상부를 폐쇄하는 상부차단프레임(230); 또는 상부에 결합되는 메쉬망(240);을 포함하여 구성되며,상기 상부차단프레임(230)과 메쉬망(240)은상기 전방차단프레임(210)과 측면차단프레임(220)의 제3자석(216)(226)과 대응되는 복수 개의 제4자석(232)(242);를 포함하여 구성되고,상기 베이스몸체(100)는상부면에 하부가 결합되고, 상기 음용방향으로 말단이 구부러지며, 상기 말단에 염부재(122)가 구비되는 염분섭취부(120);를 포함하여 구성되는 것을 특징으로 하는 우사용 위생 급수조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

560/1150 Row 560: application_number: 1020200024020, combined_string: invention_title: 가축 농가의 축사 관리 시스템 및 축사 관리 방법 abstract: 본 발명은 딥러닝 방식으로 축사 상태 및 가축의 건강 상태를 모니터링 하는 가축 농가의 축사 관리 시스템 및 축사 관리 방법에 관한 것으로, 축사에 설치되는 적어도 하나 이상의 CCTV 카메라로부터 축사 촬영 데이터를 획득하는 데이터 획득부, 상기 데이터 획득부로부터 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관 상태를 생성하는 가축 이미지 분석부 및 상기 가축 이미지 분석부에서 생성된 가축의 외관상태에 기반하여 딥러닝 기술에 기초하여 가축의 건강상태를 파악하는 건강상태 파악부를 포함하는 것을 특징으로 하는 가축 농가의 축사 관리 시스템에 의해 돼지를 비롯하여 가축의 성장 단계별 적정 체온을 유지하기 위해 축사의 온/습도 파악 및 조절을 용이하게 할 수 있도록 하여 가축의 성장 단계별 맞춤 환경의 제공 및 관리가 가능한 가축 농가의 축사 관리 시스템 및 축사 관리 방법을 제공할 수 있다는 효과가 도출된다. claims: 축사에 설치되는 적어도 하나 이상의 CCTV 카메라로부터 축사 촬영 데이터를 획득하는 데이터 획득부;상기 데이터 획득부로부터 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관 상태를 생성하는 가축 이미지 분석부; 및상기 가축 이미지 분석부에서 생성된 가축의 외관상태에 기반하여 딥러닝 기술에 기초하여 가축의 건강상태를 파악하는 건강상태 파악부;를 포함하고, 상기 축사 내의 가축에 부착된 비콘 모듈로부터 비콘 신호를 수신하여 가축의 실시간 움직임 데이터를 확보하는 움직임 파악부;를 더 포함하며,상기 가축 이미지 분석부는 상기 데이터 획득부로부터 관리자에 의해 설정된 주기마다 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관상태를 생성하되, 시간의 흐름에 따라 동일한 부위의 비교가 가능하도록 방향, 위치가 동일하게 3D모델 형태로 전용뷰어를 통해 제공하고, 가축 몸체에서 외상 변화 부위가 감지되는 경우에 변화되는 부위를 추출하여 표시해주는 것을 특징으로 하며, 축사의 온도, 습도 상태를 파악하고, 기상청의 API를 연동하여 날씨 데이터를 분석하여 분석된 날씨 데이터에 기반하여 축사의 온도, 습도 상태를 제어하는 축사 상태 관리부;를 더 포함하고,상기 가축 이미지 분석부는상기 데이터 획득부로부터 관리자에 의해 설정된 주기마다 시간대별 여러 방향에서 찍은 축사 촬영 데이터를 전달받아 획득한 축사 촬영 데이터를 연결해서 시간대별로 하나의 텍스쳐를 생성하고, Mesh 합성 과정을 거쳐 시간대별로 생성된 하나의 텍스쳐를 축사 내 가축의 3D Model에 입혀 축사 내 가축의 3D 모델을 객체 형식으로(OBJ format) 생성하며, 3D모델 형태로 전용뷰어를 통해 객체 형식으로(OBJ format) 생성된 축사 내 가축의 3D모델의 회전 및 특정 부위 확대에 대한 조작을 수행할 수 있는 사용자 인터페이스를 제공하고, 상기 축사 상태 관리부는 축사 내에서 사육되는 가축의 성장 단계별로 체온 조절을 해줄 수 있도록 축사 내부의 온도 관리를 성장 단계별로 다르게 세팅 가능한 것임을 특징으로 하는, 가축 농가의 축사 관리 시스템.제 1 항 또는 제 2 항에 기재된 가축 농가의 축사 관리 시스템에서 수행되는 가축 농가의 축사 관리 방법에 있어서, 데이터 획득부가 축사에 설치되는 적어도 하나 이상의 CCTV 카메라로부터 축사 촬영 데이터를 획득하는 단계;가축 이미지 분석부가 상기 데이터 획득부로부터 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관 상태를 생성하는 단계; 및가축 건강 상태 파악부가 상기 생성된 가축의 외관상태에 기반하여 딥러닝 기술에 기초하여 가축의 건강상태를 파악하는 단계;를 포함하고, 움직임 파악부가 상기 축사 내의 가축에 부착된 비콘 모듈로부터 비콘 신호를 수신하여 가축의 실시간 움직임 데이터를 확보하는 단계;를 더 포함하며, 상기 가축의 외관 상태를 생성하는 단계는, 상기 가축 이미지 분석부가 상기 데이터 획득부로부터 관리자에 의해 설정된 주기마다 시간대별 축사 촬영 데이터를 전달받아 축사 촬영 데이터에 포함되는 가축의 3D모델로 가축의 외관상태를 생성하되, 시간의 흐름에 따라 동일한 부위의 비교가 가능하도록 방향, 위치가 동일하게 3D모델 형태로 전용뷰어를 통해 제공하고, 가축 몸체에서 외상 변화 부위가 감지되는 경우에 변화되는 부위를 추출하여 표시해주는 것을 특징으로 하고,축사 상태 관리부가 축사의 온도, 습도 상태를 파악하고, 기상청의 API를 연동하여 날씨 데이터를 분석하여 분석된 날씨 데이터에 기반하여 축사의 온도, 습도 상태를 제어하는 단계;를 더 포함하며, 상기 가축의 외관 상태를 생성하는 단계는,상기 데이터 획득부로부터 관리자에 의해 설정된 주기마다 시간대별 여러 방향에서 찍은 축사 촬영 데이터를 전달받아 획득한 축사 촬영 데이터를 연결해서 시간대별로 하나의 텍스쳐를 생성하고, Mesh 합성 과정을 거쳐 시간대별로 생성된 하나의 텍스쳐를 축사 내 가축의 3D Model에 입혀 축사 내 가축의 3D 모델을 객체 형식으로(OBJ format) 생성하며, 3D모델 형태로 전용뷰어를 통해 객체 형식으로(OBJ format) 생성된 축사 내 가축의 3D모델의 회전 및 특정 부위 확대에 대한 조작을 수행할 수 있는 사용자 인터페이스를 제공하고, 상기 축사 상태 관리부는 축사 내에서 사육되는 가축의 성장 단계별로 체온 조절을 해줄 수 있도록 축사 내부의 온도 관리를 성장 단계별로 다르게 세팅 가능한 것임을 특징으로 하는, 가축 농가의 축사 관리 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

561/1150 Row 561: application_number: 1020190169788, combined_string: invention_title: 가축용 유방세척기 abstract: 본 발명은 필름커팅장치에 관한 것으로, 본체 전단에 체결홀을 형성한 체결판을 결합하고, 체결홀 각각에 브러쉬를 형성한 세척부를 회전가능하게 결합하여, 세척부의 기어가 맞물리도록 하며, 본체 내측에 복수의 세척부 중 어느 하나에 연결되는 구동모터를 설치하고, 본체 전단에 상면에 진입홀을 형성하되, 세척부를 커버하는 유방수용하우징을 설치하며, 체결판에 세척수를 분사하는 세척수노즐을 형성하여, 유방수용하우징의 진입홀을 통해 가축의 유방가 유방수용하우징 내로 진입되도록 함으로써, 세척수가 분사됨과 동시에 세척부의 브러쉬가 가축의 유방 외면과 마찰되면서, 먼지, 이물질 또는 세균등이 가축의 유방 외면에서 탈락되도록 하여, 가축의 유방를 청결하게 세척한다.본 발명에 따르면, 세척수를 분사함과 동시에 세척부의 브러쉬가 유방 외면과 마찰되면서 유방에 뭍어있는 먼지, 이물질 및 세균등을 탈락시켜, 유방이 청결하게 세척되고, 세척부의 브러쉬가 회전되면서 유방의 외면을 정해진 압으로 가압하여 유방 내에서 잔여된 우유가 외부로 손쉽게 배출되며, 유방 내에 잔여 우유가 발생되지 않고, 특히, 가축의 유방이 브러쉬에 의해 가압되면서 마사지되어 가축의 유방 건강상태가 유지되며, 또한, 공기노즐에서 분사되는 공기로 가축의 유방에 잔여된 세척수를 제거하여 유방를 청결한 상태로 유지시킬 수 있다. claims: 전, 후가 개방된 중공형상의 본체(100)와;상기 본체(100)의 전단에 체결되고, 전면에 복수개의 체결홀(201)을 형성한 체결판(200);상기 체결홀(201) 각각에 회전가능하게 설치되고, 일단에 서로 맞물림되어 동력을 전달하는 기어(301)를 형성하며, 외면에 브러쉬(302)를 형성한 세척부(300);상기 본체(100) 내측에 고정 설치되고, 복수개의 상기 세척부(300) 중 어느 하나의 상기 세척부(300)의 중심부와 연결되어 상기 세척부(300)를 회전구동시키는 구동모터(400);상기 본체(100)의 전단에서 연장되어 상기 세척부(300)를 커버하고, 상면에 가축의 유방가 진입되도록 허용하는 진입홀(501)을 형성한 유방수용하우징(500);일단이 상기 세척부(300) 방향으로 노출되도록 상기 체결판(200)에 고정되어 상기 세척부(300) 방향으로 세척수를 분사하는 세척수노즐(600);로 구성된 것을 특징으로 하는 가축용 유방세척기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

562/1150 Row 562: application_number: 1020190166948, combined_string: invention_title: 개체별 착유정보 기록 시스템 abstract: 개시된 기술은 개체별 착유정보 기록 시스템에 관한 것으로, 착유시설의 게이트에 설치되고 상기 게이트를 입장하는 복수의 젖소들에 부착된 태그를 식별하여 각 젖소의 ID 및 젖소의 개체수를 확인하는 식별장치; 상기 착유시설 내부에 구비된 복수개의 착유칸마다 설치되어 각각 고유한 식별번호가 부여되고 센서를 이용하여 상기 복수의 젖소가 상기 복수개의 착유칸의 점유상태를 감지하는 복수개의 감지장치; 상기 복수개의 착유칸에 각각 설치되어 착유된 원유의 착유량을 측정하는 복수개의 착유장치; 상기 식별장치에서 수신된 상기 개체수 및 상기 복수개의 감지장치의 개수를 비교하고, 상기 식별장치에서 수신된 젖소의 ID 및 상기 감지장치에서 수신된 상기 점유상태에 따라 상기 복수의 젖소들이 각각 어느 위치의 착유칸에서 착유중인지 판단하고 상기 복수개의 착유장치에서 상기 착유량에 대한 결과값을 수신하여 상기 복수의 젖소들 각각에 대한 착유정보를 생성하는 제어장치; 및 상기 제어장치와 통신하여 상기 착유정보를 수신하는 모니터링 단말기;를 포함한다. 따라서 가축에 대한 착유성적을 분석하고 착유시설을 효율적으로 운영하는 효과가 있다. claims: 착유시설의 게이트에 설치되고 상기 게이트를 입장하는 복수의 젖소들에 부착된 태그를 식별하여 각 젖소의 ID 및 젖소의 개체수를 확인하는 식별장치;상기 착유시설 내부에 구비된 복수개의 착유칸마다 설치되어 각각 고유한 식별번호가 부여되고 센서를 이용하여 상기 복수의 젖소가 상기 복수개의 착유칸의 점유상태를 감지하는 복수개의 감지장치;상기 복수개의 착유칸에 각각 설치되어 착유된 원유의 착유량을 측정하는 복수개의 착유장치;상기 식별장치에서 수신된 상기 개체수 및 상기 복수개의 감지장치의 개수를 비교하고, 상기 식별장치에서 수신된 젖소의 ID 및 상기 감지장치에서 수신된 상기 점유상태에 따라 상기 복수의 젖소들이 각각 어느 위치의 착유칸에서 착유중인지 판단하고 상기 복수개의 착유장치에서 상기 착유량에 대한 결과값을 수신하여 상기 복수의 젖소들 각각에 대한 착유정보를 생성하는 제어장치; 및상기 제어장치와 통신하여 상기 착유정보를 수신하는 모니터링 단말기;를 포함하는 개체별 착유정보 기록 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

563/1150 Row 563: application_number: 1020190167006, combined_string: invention_title: 가축의 젖 생산량 산출시스템 abstract: 본 발명은 경제적이고 간편한 방식을 구현하는 가축의 젖 생산량을 측정하고 산출하는 기술에 대한 것으로, 가축의 착유량의 측정 변수인 유속, 착유하는 가축의 체온, 호르몬분비등의 내외부 환경에 따라 실시간으로 변하는 착유량의 측정을 구현하기 위해, 착유된 젖에 포함되는 공기의 흐름을 상부로 이동시키며, 자연스럽게 곡률을 가지는 가이드몸체를 따라 유도하며, 착유된 젖의 전극접촉면적에 따라 변동하는 전류, 전압값을 산출함과 동시에 온도지수를 반영하여 실시간 착유된 젖의 유속을 산출하여 착유량을 추정할 수 있는 시스템을 제공할 수 있도록 한다. claims: 가축의 젖 생산량 산출시스템에 있어서,가축으로 부타 착유되는 착유기구에 접속하여, 착유량을 산출하는 센싱모듈(200)로 가이드하는 착유 가이드 모듈(100)을 포함하며,상기 착유 가이드 모듈(100)은,착유기구와 결합하여 착유된 젖을 하부로 유도하는 유입관(110);상기 유입관(110)이 결합되는 상부판(A)과, 상기 상부판(A)의 대응되는 방향에 배치되는 하부판(B) 및상기 상부판(A)에 연장되어 하부 방향으로 연장되어 상기 하부판(B)과 연결되는 가이드몸체(130);를 구비하며,상기 가이드몸체(130)는,상기 상부판(A)의 일단(a1)과 상기 하부판(B)의 일단(b1)이 연결되는 제1곡률부(L1)와,상기 상부판(A)의 타단(a2)과 상기 하부판(B)의 타단(b2)이 연결되는 제2곡률부(L2)를 구비하며,상기 착유 가이드 모듈(100)의 상기 유입관(110)과 상기 가이드몸체(130) 및 배출관(120)이 상부에서 하부로 연통하는 구조로 배치되어, 착유된 젖이 우선적으로 상기 제2곡률부(L2)에 접촉하여 이동하도록 구현되며,상기 제1곡률부(L1)에 비해 상기 제2곡률부(L2)가 상대적으로 길게 구현되는 구조의,가축의 젖 생산량 산출시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

564/1150 Row 564: application_number: 1020190167007, combined_string: invention_title: 가축 유두 세척장치 abstract: 본 발명은 가축 유두 세척장치에 관한 것으로, 내부에 유두를 세척하는 세척공간이 형성되어 있고, 상면에는 유두를 상기 세척공간으로 삽입하기 위한 삽입홀이 형성되어 있으며, 하면에는 유두 세척 시 사용한 세척수가 배출되는 배출홀이 형성된 본체부; 상기 세척공간에 회전 가능하게 배치되어 삽입된 유두를 세척하는 복수의 브러시를 포함하는 세척부; 상기 본체부의 하면에 배치되어 가축의 꼬리 털이 상기 배출홀을 통해 상기 세척공간으로 유입되는 것을 차단하며, 상기 세척수가 배출되도록 복수의 배수홀이 형성된 차단판; 상기 본체부에 배치되어 상기 세척공간으로 상기 세척수를 분사하는 공급부; 및 상기 본체부의 상면에 배치되어 있으며 빛을 조사할 수 있는 조명부;를 포함한다.따라서, 본체부의 하면에 형성되어 세척수가 배출되는 배출홀을 차단판이 막고 있으므로 유두 세척 중 젖소의 꼬리 털이 배출홀을 통해 세척공간으로 유입되는 것을 차단한다. 이에 젖소의 꼬리 털이 브러시에 말리지 않으므로 젖소의 유두 세척에 따른 안정성을 확보할 수 있다. claims: 내부에 유두를 세척하는 세척공간이 형성되어 있고, 상면에는 유두를 상기 세척공간으로 삽입하기 위한 삽입홀이 형성되어 있으며, 하면에는 유두 세척 시 사용한 세척수가 배출되는 배출홀이 형성된 본체부;상기 세척공간에 회전 가능하게 배치되어 삽입된 유두를 세척하는 복수의 브러시를 포함하는 세척부;상기 본체부의 하면에 배치되어 가축의 꼬리 털이 상기 배출홀을 통해 상기 세척공간으로 유입되는 것을 차단하며, 상기 세척수가 배출되도록 복수의 배수홀이 형성된 차단판;상기 본체부에 배치되어 상기 세척공간으로 상기 세척수를 분사하는 공급부; 및상기 본체부의 상면에 배치되어 있으며 빛을 조사할 수 있는 조명부;를 포함하는 가축 유두 세척장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

565/1150 Row 565: application_number: 1020190167008, combined_string: invention_title: 착유량 측정장치 abstract: 본 발명은 착유량 측정장치에 관한 것으로, 내부공간이 낙하공이 형성된 구획벽의 배치로 상부공간과 하부공간으로 구획되어 있는 착유통, 상기 착유통에 배치되어 있고 상기 낙하공을 개방 또는 차단하는 개폐부, 상기 개폐부와 연결되어 있고 상기 개폐부에 진공압을 형성하여 상기 개폐부를 작동시키는 개폐밸브, 상기 개폐부와 상기 개폐밸브를 연결하는 진공호스 및 상기 진공호스에 배치되어 있고 상기 진공호스의 내부 진공여부를 감지하여 상기 착유통에서 배출되는 우유량을 산출하는 진공센서를 포함한다.상기 착유통에는 상기 상부공간과 연결된 유입구와 상기 하부공간과 연결된 배출구가 형성되어 있고 상기 우유는 상기 배출구를 통해 배출된다.따라서, 착유통에서 우유 배출 시 진공호스의 진공여부를 측정하여 우유 산출량을 측정하므로 전기적 오작동을 방지할 수 있다. 그리고 착유통에 채워진 우유를 배출하면서 우유량을 산출하므로 착유량을 정확하게 측정할 수 있다. claims: 내부공간이 낙하공이 형성된 구획벽의 배치로 상부공간과 하부공간으로 구획되어 있는 착유통,상기 착유통에 배치되어 있고 상기 낙하공을 개방 또는 차단하는 개폐부,상기 개폐부와 연결되어 있고 상기 개폐부에 진공압을 형성하여 상기 개폐부를 작동시키는 개폐밸브,상기 개폐부와 상기 개폐밸브를 연결하는 진공호스 및상기 진공호스에 배치되어 있고 상기 진공호스의 내부 진공여부를 감지하여 상기 착유통에서 배출되는 우유량을 산출하는 진공센서를 포함하며,상기 착유통에는 상기 상부공간과 연결된 유입구와 상기 하부공간과 연결된 배출구가 형성되어 있고 상기 우유는 상기 배출구를 통해 배출되는착유량 측정장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

566/1150 Row 566: application_number: 1020190166083, combined_string: invention_title: 가축용 냉온 음수 공급장치 abstract: 개시된 기술은 가축용 냉온 음수 공급장치에 관한 것으로, 축사 내부에 배치되어 일정 주기마다 상기 축사 내부의 온도 및 습도에 대한 환경정보를 감지하는 제 1 센서그룹; 상기 축사에 구비된 수조에 배치되어 상기 수조 내 음수(Drinking Water)의 온도를 감지하는 제 2 센서그룹; 상기 축사에 배치된 가축에 대한 생육정보를 입력받는 입력장치; 상기 환경정보 및 상기 생육정보를 수신하여 상기 가축에 대한 THI(Temperature Humidity Index) 지수를 산출하고, 상기 THI 지수에 따라 상기 음수의 온도를 조절하기 위한 제어신호를 생성하는 제어장치; 및 상기 제어신호를 수신하여 상기 수조 내 음수의 온도를 조절하는 온도조절장치;를 포함한다. 따라서 가축의 열 스트레스를 저감하고 정확한 온도의 냉온 음수를 공급하는 효과가 있다. claims: 축사 내부에 배치되어 일정 주기마다 상기 축사 내부의 온도 및 습도에 대한 환경정보를 감지하는 제 1 센서그룹;상기 축사에 구비된 수조에 배치되어 상기 수조 내 음수(Drinking Water)의 온도를 감지하는 제 2 센서그룹;상기 축사에 배치된 가축에 대한 생육정보를 입력받는 입력장치;상기 환경정보 및 상기 생육정보를 수신하여 상기 가축에 대한 THI(Temperature Humidity Index) 지수를 산출하고, 상기 THI 지수에 따라 상기 음수의 온도를 조절하기 위한 제어신호를 생성하는 제어장치; 및상기 제어신호를 수신하여 상기 수조 내 음수의 온도를 조절하는 온도조절장치;를 포함하는 가축용 냉온 음수 공급장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

567/1150 Row 567: application_number: 1020190153980, combined_string: invention_title: Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법 abstract: 본 발명은 젖소, 육우, 한우에게서 기능성 성분인 Omega-3가 풍부하게 포함된 우유와 쇠고기를 수득하기 위한 기능성 생초먹이 제조방법에 관한 것이다. 본 발명은 기능성 성분인 Omega-3가 풍부하게 포함된 우유와 쇠고기를 수득하기 위한 기능성 유기농 생초와, 해당 기능성 유기농 생초를 재배하기 위한 기능성 관주양액과, 해당 기능성 관주양액을 제조하기 위한 재료인 항산화 및 영양기능성 운모규암 다공성 이온화 미네랄 수용액을 만들어내는 것에 관한 것이다. 본 발명의 일 실시예에 따른 기능성 생초먹이 제조방법은 기능성 관주양액의 주 재료가 되는 운모규암을 소성하여 그 입자가 다공성 형질을 가지도록 가공하는 운모규암 다공화 소성단계; 및 다공화된 입자를 가진 소성 운모규암이 이온화 되도록 가공하는 다공성 운모규암 이온화단계; 및 상기의 다공성 이온화 운모규암을 물에 녹도록 가공하는 다공성 이온화 운모규암 수용화단계; 및 상기의 다공성 이온화 운모규암 수용액을 활용하여 기능성 관주양액을 제조하는 기능성 관주양액 제조단계; 및 상기의 기능성 관주양액을 활용하여 젖소, 육우, 한우의 조사료가 되는 기능성 밀싹을 재배하는 기능성 밀싹 재배단계;를 상기의 기능성 밀싹을 각각 젖소, 육우, 한우에게 조사료로 급이하는 기능성 조사료 급이단계;를 포함한다. 여기서, 상기 다공성 이온화 운모규암 수용액을 제조하기 위한 재료인 운모규암은 사암(규암)에서 운모의 비율이 25~35% 이상인 것을 말한다. 이와같은 운모규암 조성물은 상기의 제조단계에 의하여 기능성 관주양액으로 제조되어 기능성 밀싹을 재배할 시 밀싹의 세포 내에 풍부한 영양물질을 포함하게 되며, 병해없는 식물의 재배가 가능하다. 또한 본 기능성 밀싹 재배단계에 의하여 Omega-3 성분이 높게 나타난 밀싹은, 젖소의 젖, 육우와 한우의 쇠고기 성분을 좋게 하여 기능성 축산물(우육, 우유)의 수득을 도울 뿐만 아니라, 건강하고 병해없는 축산 사육 전반에 활용될 수 있다는 효용이 있다. claims: 본 발명은 Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법으로써,본 발명의 일 실시예에 따른 기능성 생초먹이 제조방법은,기능성 관주양액의 주 재료가 되는 운모규암을 소성하여 그 입자가 다공성 형질을 가지도록 가공하는 운모규암 다공화 소성단계; 및 다공화된 입자를 가진 소성 운모규암이 이온화 되도록 가공하는 다공성 운모규암 이온화단계; 및 상기의 다공성 이온화 운모규암을 물에 녹도록 가공하는 다공성 이온화 운모규암 수용화단계; 및 상기의 다공성 이온화 운모규암 수용액을 활용하여 기능성 관주양액을 제조하는 기능성 관주양액 제조단계; 및 상기의 기능성 관주양액을 활용하여 젖소, 육우 한우의 조사료가 되는 기능성 밀싹을 재배하는 기능성 밀싹 재배단계;를 상기의 기능성 밀싹을 각각 젖소, 육우, 한우에게 조사료로 급이하는 기능성 조사료 급이단계;를 포함하는 Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법.상기 다공성 운모규암 이온화단계는,3단계의 다공화 소성을 거친 클링커를 나노 분말로 분쇄한 후, 함유된 철석과 자철석을 걸러내기 위하여서 Electronic controller가 포함된 전류자기자석을 활용하고, 건식교반 균질기를 이용하여 혼합분말을 교반함으로써 혼합분말에 정전기를 발생시키는 이온화공정을 수행할 수 있는 Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법.기능성 밀싹 재배단계는,밀싹 씨앗을 침정한 다음 깨끗한 물로 세척하여 넓은 판에 담아 광합성을 야기하는 빛이 들지 않도록 검은 천으로 덮은 다음, 24~28 ℃를 유지하는 발아방에서 24시간동안 싹을 틔운 후, 묘판상에 파종하고, 각각의 묘판을 겹겹이 쌓아 단위 면적당 생산량을 최대화 하며, 24~28 ℃를 유지하는 재배시설에서 싹이 15cm 이상의 길이로 자랄때까지 성장을 시킨 후, White LED 광원을 고루 조사하여 광합성을 촉진시켜 푸른 색의 밀싹으로 재배할 수 있는 Omega-3 성분이 풍부한 유기농 소고기 및 우유 생산용 기능성 생초먹이 제조방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

568/1150 Row 568: application_number: 1020190146630, combined_string: invention_title: 사료 조성물 abstract: 본 발명의 사료 조성물은 알팔파를 포함하는 조사료, 배합사료 및 첨가제를 포함하는 사료 조성물이고, 상기 알팔파는 상기 사료 조성물 100 중량부 중 30 중량부 내지 50 중량부로 포함되어, 소화가 원활하게 이루어지도록 하여 소의 건강 상태를 개선시킬 뿐만 아니라, 본 발명 사료 조성물을 섭취하는 소가 생산하는 우유는 유지방 함량 및 기능성 지방산 함량이 높고, 오메가-3와 오메가-6의 비율이 개선되며, 체세포수도 낮은 장점이 있다. claims: 알팔파, 클라인그라스 및 연맥을 포함하는 조사료;배합사료; 및아마씨, 생균제, 효모제, 톡신바인더, 간기능강화제, 비타민제 및 칼슘제를 포함하는 첨가제;를 포함하는 사료 조성물이고,상기 사료 조성물 100 중량부 중,상기 알팔파는 33 중량부 내지 42 중량부;상기 클라인그라스는 6 중량부 내지 15 중량부;상기 연맥은 3 중량부 내지 10 중량부;상기 배합사료는 35 중량부 내지 45 중량부;상기 아마씨는 0.1 중량부 내지 0.5 중량부;상기 생균제는 0.1 중량부 내지 0.5 중량부;상기 효모제는 0.1 중량부 내지 0.5 중량부;상기 톡신바인더는 0.05 중량부 내지 0.3 중량부;상기 간기능강화제는 0.01 중량부 내지 0.3 중량부;상기 비타민제는 0.05 중량부 내지 0.3 중량부;상기 칼슘제는 0.1 중량부 내지 0.5 중량부;로 포함되고,상기 사료 조성물은 하기 식 1로 표시되는 조농비가 0.55 내지 0.63이며,상기 사료 조성물은 오메가-3 및 오메가-6가 1:3 내지 1:4의 중량비로 포함되고, 유지방 함량이 3.4 내지 4.2 중량%이고, 상기 유지방 중 EPA가 0.07 내지 0.1 중량%인 우유를 생산하는 것인 사료조성물:[식 1]조농비=(조사료 건물 함량)/(조사료 건물 함량 + 배합사료 건물 함량)., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

569/1150 Row 569: application_number: 1020190136816, combined_string: invention_title: 축사용 정밀제어 방수방진 환풍기 abstract: 본 발명은 축사용 정밀제어 방수방진 환풍기에 관한 것으로, 축사용 환풍기에 오일실과 오링 및 패킹링을 구성함으로써, 방수방진 효과를 부여하고, 홀센서와 제어부 및 알림수단를 구성함으로써, 환풍기의 정밀제어 및 고장알림을 하여, 축사에서 사용되는 환풍기의 고장 및 성능저하를 방지하며, 고장 시, 신속한 교체 및 수리를 할 수 있어, 환풍기 고장 방치로 인한 축사 내 가축의 생육저하 및 질병확산을 방지하는 축사용 정밀제어 방수방진 환풍기에 관한 것이다. claims: 개구된 펜프레임 중심에 연결대을 통해 모터부가 고정되는 환풍기에 있어서,모터부의 모터하우징은 모터하우징의 정면을 관통하여 선두측이 돌출되는 회전자의 둘레를 따라 일정간격을 두고 축보호대가 돌출되고, 돌출된 회전자 선두측과 축보호대 사이에 오일실이 구성되며,모터부의 모터커버는 후방으로 개방된 모터하우징의 내경에 대응되는 끼움턱이 돌출되고, 끼움턱과 모터하우징 사이에 오링이 구성되며,모터부는 전방으로 개방된 콘덴서커버와 모터커버 배면이 결합하되, 콘덴서커버 정면 테두리에 대응되는 패킹링이 모터커버와 콘덴서커버 사이에 구성됨으로써, 모터부는 방수방진되며,모터부는 홀센서를 포함하고, 환풍기는 제어부를 포함하여, 홀센서에서 측정된 모터부의 회전속도와 제어부에서 설정된 회전속도의 차이를 파악하여, 모터부의 회전속도가 설정속도에 근접하도록 제어속도를 수정함으로써, 모터부를 정밀제어하는 축사용 정밀제어 방수방진 환풍기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

570/1150 Row 570: application_number: 1020190136829, combined_string: invention_title: 송아지용 축사 abstract: 본 발명은 송아지용 축사에 관한 것으로, 더욱 상세하게는 어미소 축사의 외측에 배치되는 휀스를 포함하고 어미소와 공유하는 사료통 또는 물통(W)에 인접 설치된 게이트(100)의 통로 면적이 다단계로 조절 가능하며 게이트(100)가 개폐상태를 안정적으로 고정 가능하여 송아지의 안전사고를 예방할 수 있는 송아지용 축사에 관한 것이다.이러한 본 발명은, 어미소 축사의 외측에 배치되어 어미소 축사의 휀스와 어미소 축사의 사료통 또는 물통(W)을 공유하는 송아지용 축사에 있어서, 상기 휀스(F)는, 상기 사료통 또는 물통(W)에 인접배치되어 송아지의 머리가 사료통 또는 물통(W) 측으로 통과할 수 있는 폭과 높이로 이루어지되, 송아지의 생육 과정에 따라 변하는 송아지의 머리 크기에 맞게 다단계의 통로면적을 구비하는 게이트(100)를 포함하여 구성된다. claims: 어미소 축사(400)의 외측에 배치되어 어미소 축사의 휀스와 어미소 축사의 사료통 또는 물통(W)을 공유하는 송아지용 축사에 있어서,상기 휀스(F)는,상기 사료통 또는 물통(W)에 인접배치되어 송아지의 머리가 사료통 또는 물통(W) 측으로 통과할 수 있는 폭과 높이로 이루어지되, 송아지의 생육 과정에 따라 변하는 송아지의 머리 크기에 맞게 다단계의 통로면적을 구비하는 게이트(100)를 포함하는 것을 특징으로 하는 송아지용 축사., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

571/1150 Row 571: application_number: 1020190134173, combined_string: invention_title: 실내 정화용 태양광가열장치가 구비된 축사용 시설물 abstract: 본 발명은 실내 정화용 태양광가열장치가 구비된 축사용 시설물에 관한 발명으로서, 상세하게는 축사와 같은 가축이나 원예작물 기르는 시설물에 맞추어서 태양광 발전판을 설치하여 주되, 비치는 태양광으로 발전되는 전력으로 가동되는 펌프에 의한 가압공기를 급속한 서냉으로 형성되는 냉각공기를 축사의 실내공간에 분출로서 실내정화를 제공하는 발명이다.일반적으로 축사용 하우스와 같은 축사단지는 대부분 도시의 가장자리에서 기술의 발전에 따라 점점 대단위로 설치함으로서, 이의 면적에서 기후 변화로 형성되는 폭염이나 혹서기에 발생하는 피해에 대한 대비가 필요하는 것이다.이는 하우스를 서로 연속적으로 설치로서 원예단지나 하우스로 제공되는 실내공간은 넓은 면적을 형성함으로서, 상기 비닐하우스 단지의 면적에 비치는 태양광의 량으로 발전하는 발전량은 많다고 할 것입니다.따라서 본 발명을 상세히 설명하면, 축산단지(43)에서 골조(11)의 외측으로 감싸주는 비닐(21)로 조립으로 실내공간(28)이 형성되는 하우스(20)와, 상기 하우스(20)용 갓길(14)에서 연속 반복적으로 길이방향에 따라 돌출되는 기둥(15)과, 상기 돌출되는 기둥(15) 사이를 일체로 연결되는 프레임(29)과, 상기 기둥(15)와 프레임(29)에 결합되도록 유입관(65)에 연결된 가압탱크(68)와, 프레임(29)에 결합된 제어장치의 구동으로 회전되는 회전형 도어(27)로, 기둥(15) 사이에 설치된 차양막(30)의 구동으로 조절되는 공기통로(41)와, 상기 기둥(15)을 연결되는 빔(17)으로 조립구간(18)이 구축된 하우스(20)에서 양측으로 경사지는 돌출부(38)를 형성하는 경사프레임(23)과, 상기 경사프레임(23)에 힌지(36)로 결합되는 태양광가열판(40)과, 상기 태양광가열판(40)에 발전소자(16)가 구비된 태양광발전판(25)으로 제공시켜 주는 축산단지에 있어서, 상기 태양광발전판(25)의 배면에다 양측에 입출구(44)가 구비된 가열통로(45)로 결합된 가열판형 탱크(33)와, 상기 가열판형 탱크(33)에서 연결된 입출구(44)에 연결된 공급관(51)에 관통되는 분사구(59)로 냉각된 공기를 분사시켜 주도록 제공되는 발명이다. claims: 축산단지(43)에서 골조(11)의 외측으로 감싸주는 비닐(21)로 조립으로 실내공간(28)이 형성되는 하우스(20)와, 상기 하우스(20)용 갓길(14)에서 연속 반복적으로 길이방향에 따라 돌출되는 기둥(15)과, 상기 돌출되는 기둥(15) 사이를 일체로 연결되는 프레임(29)과, 상기 기둥(15)와 프레임(29)에 결합되도록 유입관(65)에 연결된 가압탱크(68)와, 프레임(29)에 결합된 제어장치의 구동으로 회전되는 회전형 도어(27)로, 기둥(15) 사이에 설치된 차양막(30)의 구동으로 조절되는 공기통로(41)와, 상기 기둥(15)을 연결되는 빔(17)으로 조립구간(18)이 구축된 하우스(20)에서 양측으로 경사지는 돌출부(38)를 형성하는 경사프레임(23)과, 상기 경사프레임(23)에 힌지(36)로 결합되는 태양광가열판(40)과, 상기 태양광가열판(40)에 발전소자(16)가 구비된 태양광발전판(25)으로 제공시켜 주는 축산단지에 있어서, 상기 태양광발전판(25)의 배면에다 양측에 입출구(44)가 구비된 가열통로(45)로 결합된 가열판형 탱크(33)와, 상기 가열판형 탱크(33)에서 연결된 입출구(44)에 연결된 공급관(51)에 관통되는 분사구(59)로 냉각된 공기를 분사시켜 주도록 제공되는 실내 정화용 태양광가열장치가 구비된 축사용 시설물., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

572/1150 Row 572: application_number: 1020190127195, combined_string: invention_title: 축사환경 측정장치 abstract: 본 발명은 무선통신으로써 로라(RORA)와 블루투스(BLUETOOTH) 기반을 이용한 스마트팜의 축사환경 측정장치에 관한 것이다. 이를 위한 본 발명은, 각 축사(10A - 10F)마다 전송거리의 비콤모듈(20)이 각기 설치되어 있으며, 해당 축사위치 정보를 접근하는 작업자 송신기(30)로 전송하고, 상기 작업자 송신기(30)와 함께 로라기반의 표준통신 수신기(40)가 별도로 설치되어 네트워킹되도록 구성하며; 상기 작업자 송신기(30)에는 온습도센서와 가스센서, 리튬이온 배터리가 각기 설치되고, 또 작업자 송신기(30)는 설치된 해당 비콘모듈(20)에서 축사위치 정보를 수신하고 자체에 부착된 가스센서(50)를 이용한 오염도를 확인하며 또는 온습도센서(60)로 각 축사내의 온습도를 확인한 것을 그 특징으로 한다. claims: 각 축사(10A - 10F)마다 전송거리의 비콘모듈(20)을 각기 설치하며, 해당 축사위치 정보를 접근하는 작업자 송신기(30)로 전송하고, 상기 작업자 송신기(30)와 함께 로라기반의 표준통신 수신기(40)가 별도로 설치되어 네트워킹되도록 구성하며; 상기 작업자 송신기(30)에는 온습도센서와 가스센서, 리튬이온 배터리가 각기 설치되고, 또 작업자 송신기(30)는 설치된 해당 비콘모듈(20)에서 축사위치 정보를 수신하고 자체에 부착된 가스센서(50)를 이용한 오염도를 확인하며 또는 온습도센서(60)로 각 축사내의 온습도를 확인함을 포함하되; 상기 작업자 송신기(30)는 원칩마이컴(35)에 와이파이 및 블루투스 안테나(31), 부져(34), 로라안테나(32)를 통한 로라모듈(33)이 각각 연결되는 한편, 리튬이온 배터리(37)를 통한 배터리팩 매니져(36)와, 가스센서(50)가 OP앰프(38)를 통한 증폭회로(39)가 각기 연결되고; 상기 표준통신 수신기(40)는 로라안테나(42)를 통한 로라모듈(44)이 원칩마이컴(46)과 연결되도록 구성되고, 수신정보는 작업시간, 작업위치, 현장온도와 현장습도, 현장 오염도이고, 송신정보로는 알람신호인 것을 특징으로 하는 축사환경 측정장치.작업복에 간편히 착용하는 작업자 송신기(30)에는 온습도센서(60)와 가스센서(50), 리튬이온 배터리가 각기 설치되고; 원칩마이컴(35)에 와이파이 및 블루투스 안테나(31), 부져(34), 로라안테나(32)를 통한 로라모듈(33)이 각각 연결되는 한편, 리튬이온 배터리(37)를 통한 배터리팩 매니져(36)와, 가스센서(50)가 OP앰프(38)를 통한 증폭회로(39)가 각기 연결되도록 구성된 작업자 송신기(30)는 설치된 해당 비콘모듈(20)에서 축사위치 정보를 수신하고 자체에 부착된 가스센서(50)를 이용한 현장 오염도를 확인하며 온습도센서(60)로 각 축사내 온습도의 확인함을 포함하되; 상기 가스센서(50)에 연결된 저항(R26)에 1 PPM 당 40 ~ 200 nA 정도의 전류가 발생하고, 상기 가스센서(50)가 동작을 정지할 경우에 전계효과 트랜지스터 (Q2)에 역전압이 흐르면서 화학식 반응을 정지시키고; 상기 가스센서(50)에서는 발생된 전압이 너무 미세하여 미세전압을 증폭하는 OP 앰프(U3A)로 1 차 증폭을 하고, 대기 온도에 적절하게 증폭도를 변화하기 위해 서미스터(RTH1)를 부착하여 온도에 따른 정밀도를 보완하며, 센서 마다 전류값이 많이 차이가 나서 ADC 측정이 힘들므로 이를 보완하기 위하여 추가 OP 앰프(U4A)를 두어 2 차 증폭을 한 것을 특징으로 하는 축사환경 측정장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

573/1150 Row 573: application_number: 1020190112674, combined_string: invention_title: 착유기 abstract: 본 발명은 플랜지판을 가압통의 하부에 일체로 형성시켜 곡물의 착유과정에서 작업효율을 향상시킬 수 있으며, 깻묵의 제거 공정이 간편하게 반자동으로 이루어지도록 그 구조가 개선된 착유기에 관한 것으로, 상판 및 하판과; 중판과; 착유통과; 착유하우징과; 가압통; 및 스톱퍼수단;을 포함하되, 상기 스톱퍼수단은 상기 중판의 좌,우측 상부에 고정되고 서로 대칭되게 마련되는 스톱퍼 몸체와, 상기 스톱퍼 몸체의 상측에 좌,우측으로 이동되며 하부가 상기 스톱퍼 몸체의 내부로 진입되고 일단부에 베어링롤러가 마련된 스톱퍼바와, 상기 스톱퍼 몸체의 내부에 마련되고 상기 스톱퍼바측에 일방향 탄성력을 제공하는 스프링부재, 및 일단부가 상기 스톱퍼 몸체의 내부에 수용되고 타단부가 상기 스톱퍼 몸체의 외측으로 출몰동작되며 상기 스프링부재를 지지하는 복수의 지지핀을 포함하여 이루어진다. claims: 복수의 기둥(50)이 관통되도록 결합되는 상판(10) 및 하판(20)과;상기 기둥(50)에 관통되도록 결합되며 승강수단에 의해 상,하 승강동작되는 중판(200)과;상기 중판(200)의 상,하 동작시 연동되고 하부 이동실린더(700)과 착유하우징(350)을 매개로 전진 동작 및 복귀동작되며, 내부에 착유용 곡물이 수납되는 공간이 마련되고, 승강실린더(500)에 의해 승강동작되는 착유판(320)을 갖는 착유통(300)과;상기 중판(200)에 상단부 테두리가 지지되고, 내부에 착유통(300)이 수용되며 상기 하부 이동실린더(700)에 의해 전진 및 복귀동작되는 착유하우징(350)과;상기 상판(10)의 하측에 배치되고 상부 이동실린더(150)에 의해 후진동작 및 복귀동작되며 하부에 플랜지판(110)이 일체로 형성된 가압통(100)과;상기 중판(200)의 좌,우 양측에 마련되고, 상기 가압통(100)의 후진동작시 서로 간의 간격이 좁아지며 상기 가압통(100)의 복귀동작시 서로 간의 간격이 멀어지는 스톱퍼바(410)를 구비하며, 상기 스톱퍼바(410)의 단부가 상기 착유통(300)의 상승을 방지하는 스톱퍼수단(400);을 포함하되,상기 스톱퍼수단(400)은 상기 중판(200)의 좌,우측 상부에 고정되고 서로 대칭되게 마련되는 스톱퍼 몸체(405)와,상기 스톱퍼 몸체(405)의 상측에 좌,우측으로 이동되며 하부가 상기 스톱퍼 몸체(405)의 내부로 진입되고 일단부에 베어링롤러(420)가 마련된 스톱퍼바(410)와,상기 스톱퍼 몸체(405)의 내부에 마련되고 상기 스톱퍼바(410)측에 일방향 탄성력을 제공하는 스프링부재(450)와,일단부가 상기 스톱퍼 몸체(405)의 내부에 수용되고 타단부가 상기 스톱퍼 몸체(405)의 외측으로 출몰동작되며 상기 스프링부재(450)를 지지하는 복수의 지지핀(455)을 구비한 것을 특징으로 하는 착유기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

574/1150 Row 574: application_number: 1020190100145, combined_string: invention_title: 우사용 목걸이틀 abstract: 본 발명의 일 실시예에 따른 우사용 목걸이틀은, 하부가로대; 상기 하부가로대의 상부에 수평으로 평행하게 배치되며, 주걸쇄가 형성되는 상부가로대; 상기 상부가로대 및 상기 하부가로대 사이에 일정각도로 절곡되어 기울어지게 설된 회동지지대; 및 상기 회동지지대에 시소 방식으로 회동가능하게 고정되며, 상단에는 복수의 체결홈이 형성되어 상기 주 걸쇄에 다단으로 체결되는 주 체결핀이 설치된 회동봉;을 포함할 수 있다. claims: 우사용 목걸이틀에 있어서, 하부가로대; 상기 하부가로대의 상부에 수평으로 평행하게 배치되며, 주걸쇄가 형성되는 상부가로대; 상기 상부가로대 및 상기 하부가로대 사이에 일정각도로 절곡되어 기울어지게 설치된 회동지지대; 및 상기 회동지지대에 시소 방식으로 회동가능하게 고정되며, 상단에는 복수의 체결홈이 형성되어 상기 주 걸쇄에 다단으로 체결되는 주 체결핀이 설치된 회동봉;을 포함하고,상기 우사용 목걸이틀은, 상기 주 걸쇄를 관통하여 회동되는 가로유동축에 형성되되, 상기 주 걸쇄로부터 소정 간격 이격된 위치에 형성된 보조 걸쇄; 및 상기 주 걸쇄의 상부에 힌지 결합되며, 체결홈이 형성되어 상기 보조 걸쇄에 체결됨으로써 상기 주 체결핀이 분리됨을 방지하는 보조 체결핀을 더 포함하고,상기 가로유동축의 단부에는 ㄴ자 형상의 걸림손잡이부가 설치되고, 상기 걸림손잡이부의 상측에는 실린더하우징과 단부에 걸림후크가 형성된 피스톤로드로 이루어지는 공압실린더가 설치되되, 상기 실린더하우징은 일단이 상기 회동봉과 마주보는 세로지지대에 회동가능하게 설치되고, 상기 피스톤로드의 걸림후크에는 상기 걸림손잡이부가 상방향으로 회동되어 걸림되거나, 공압에 의해 피스톤로드가 신장되면서 상기 걸림손잡이부를 하방향으로 밀어 걸림후크에서 상기 걸림손잡이부의 걸림이 해제되도록 구성되며,상기 우사용 목걸이틀은, 상기 회동봉 및 상기 세로지지대의 길이 방향을 따라 소정 간격마다 설치되는 감지 센서; 및 상기 회동봉에 설치된 상기 주 체결핀의 회동과, 상기 공압 실린더를 전자적으로 제어하며, 상기 감지 센서로부터 수신되는 센싱 정보에 기초하여 상기 회동봉 및 상기 세로지지대 사이에 소가 위치하는 것으로 확인되면 감지된 위치에 대응되는 주 체결핀만을 독립적으로 구동하는 제어부를 더 포함하되,상기 제어부는, 소정 기간 동안 상기 감지 센서로부터 수신되는 복수의 센싱값에 기초하여 상기 우사용 목걸이틀을 출입하는 소의 평균 목둘레 길이를 추정하고, 추정된 평균 목둘레 길이에 기초하여 상기 회동봉 및 상기 세로지지대 사이로 소가 진입하는 것으로 확인되면 주 체결핀에 형성된 복수의 체결홈 마다 설치된 조명 장치 중 어느 하나의 조명 장치가 작동되도록 제어하며,상기 우사용 목걸이틀은, 상기 회동 지지대의 하단에 설치되어 상기 회동봉의 회동 각도를 미세 조절할 수 있도록 상하 방향의 길이가 다단으로 조절되는 높이 조절부 및 상기 회동지지대의 길이 방향을 따라 설치되는 적어도 하나의 파손방지부를 더 포함하고,상기 높이 조절부는, 원기둥 형태로 형성되어 상기 회동 지지대의 하측을 지지하는 상부 프레임; 및 상부에 상기 상부 프레임이 삽입될 수 있도록 상기 상부 프레임의 하부의 형태에 대응하는 형상의 안착홈이 상부에 형성하며, 상기 상부 프레임의 지지 높이를 조절할 수 있도록 상기 안착홈에 삽입되는 상기 상부 프레임의 삽입 깊이가 다단으로 조절되는 하부 프레임;을 포함하며,상기 상부 프레임은, 원기둥 형태로 형성되어 상기 안착홈에 삽입되는 상부 본체; 상기 상부 본체의 하부 외주면을 따라 다수 개가 설치되며, 상기 안착홈의 벽면을 따라 이동된 후 상기 상부 본체가 더 이상 하강되지 않도록 체결되는 체결 돌기; 및 상기 상부 본체가 상기 안착홈을 따라 하강하다 더 이상 하강하지 못하도록 상기 상부 본체의 상부 외주면을 일주하고 연장 설치되는 걸림턱;을 포함하며,상기 하부 프레임은, 상기 체결 돌기가 상하 수직 방향으로 이동하기 위한 공간을 형성할 수 있도록 상기 안착홈의 벽면의 상측으로부터 하측 수직 방향으로 연장 형성되는 수직 통로; 상기 체결 돌기가 수평 방향으로 이동할 수 있도록 상기 수직 통로의 중간 부분으로부터 일측 수평 방향으로 연장 형성되는 제1 수평 통로; 상기 체결 돌기가 안착될 수 있도록 상기 제1 수평 통로의 말단에서 하측 수직 방향으로 연장 형성되는 제1 체결 통로; 상기 체결 돌기가 수평 방향으로 이동할 수 있도록 상기 수직 통로의 하측으로부터 일측 수평 방향으로 연장 형성되는 제2 수평 통로; 및 상기 체결 돌기가 안착될 수 있도록 상기 제2 수평 통로의 말단에서 하측 수직 방향으로 연장 형성되는 제2 체결 통로;를 포함하며,상기 제1 체결 통로는, 상기 제1 수평 통로를 따라 수평 방향으로 이동하던 상기 체결 돌기가 하강된 후 안착될 수 있도록 제1 수평 통로의 말단에서 하측 방향으로 연장 형성되는 하강 통로; 상기 하강 통로의 상부 일측 또는 양측 벽면에 함몰 형성되는 설치홈에 설치되며, 상기 하강 통로로 노출된 전면이 하측으로 갈수록 상기 설치홈으로부터 멀어지는 방향으로 경사진 경사면을 형성하며, 상기 설치홈에 삽입된 후단이 탄성체에 의해 지지되어 상기 체결 돌기가 상기 경사면을 따라 하강하면 상기 탄성체 방향으로 이동된 후 상기 체결 돌기가 상기 경사면을 통과하여 상기 하강 통로의 하측 공간에 안착되면 상기 탄성체의 탄성력에 의해 상기 경사면이 상기 설치홈으로부터 다시 노출되어 전단 하측면으로 상기 체결 돌기의 상측을 체결하는 체결구; 및 상기 하강 통로의 하부 공간에 설치되며, 상기 하강 통로의 하측 바닥면에 설치되는 탄성체에 의하여 지지되어 상측에 안착되는 상기 체결 돌기를 탄성력을 이용하여 지지하는 탄성 지지판;을 포함하며,상기 파손 방지부는, 상기 회동지지대에 설치되는 하부캡; 상기 하부캡의 상측에 이격되어 설치되어 회동봉을 지지하는 상부캡; 및 상기 하부캡과 상기 상부캡의 사이에 설치되어 상기 상부캡을 지지하는 지지기둥;을 포함하며,상기 하부캡은, 원기둥 형태로 형성되는 캡 본체, 및 상기 지지기둥의 하부가 삽입될 수 있도록 상기 캡 본체의 상부면으로부터 하측 방향으로 상기 지지기둥의 하부 형태에 대응하는 형상으로 함몰 형성되는 하부 안착홈을 포함하며,상기 상부캡은, 상기 지지기둥의 상부가 삽입될 수 있도록 하부면으로부터 상측 방향으로 상기 지지기둥의 상부 형태에 대응하는 형상으로 함몰 형성되는 상부 안착홈이 형성되며,상기 지지기둥은, 중심각이 직각인 원호 형상의 기둥 형태로 형성되는 4 개의 기둥모듈이 서로 연결 설치되어 원기둥 형태를 형성하며, 하부가 상기 하부 안착홈에 삽입되고, 상부가 상기 상부 안착홈에 삽입되며,상기 기둥모듈은, 중심각이 직각인 원호 형상의 기둥 형태로 형성되는 모듈 본체; 상기 모듈 본체의 일측 평면에 상하 길이 방향으로 연장 형성되며, 다른 모듈 본체의 다른 일측 평면에 형성된 슬라이딩 홈의 상측으로부터 삽입 체결되는 슬라이딩 돌기; 상기 모듈 본체의 다른 일측 평면에 상기 슬라이딩 돌기의 형태에 대응하는 형상으로 상하 길이 방향으로 함몰 형성되며, 다른 모듈 본체의 슬라이딩 돌기가 삽입 체결되어 상하 방향으로 슬라이딩 이동하는 슬라이딩 홈; 상기 모듈 본체의 상부에 돌출 형성되어 상기 상부 안착홈의 상측면을 지지하는 지지 돌기; 및 상기 모듈 본체의 상측에 안착된 상기 상부캡이 회전할 수 있도록 상기 지지 돌기의 상부에 설치되는 바퀴;를 포함하며,상기 하부캡은, 상기 하부 안착홈에 대응하는 형상의 원판 형태로 형성되며, 탄성력을 이용하여 지지하기 위한 다수 개의 탄성체가 하측면에 설치되는 지지 원판; 및 상기 하부 안착홈에 대응하는 형상의 원판 형태로 형성되어 상기 지지 원판의 상측에 안착되며, 상측에 안착된 상기 기둥모듈을 상기 하부 안착홈에서 회전시킬 수 있도록 하측면의 각 사방에 바퀴가 설치되는 회전 원판;을 더 포함하는, 우사용 목걸이틀., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

575/1150 Row 575: application_number: 1020190097866, combined_string: invention_title: 되새김 활동 측정을 이용한 소의 건강 관리 시스템 abstract: 본 발명은 소의 건강 관리 시스템에 관한 것으로서, 보다 구체적으로는 되새김 활동 측정을 이용한 소의 건강 관리 시스템으로서, 소에 부착되어 소의 움직임 및 행동을 감지하는 행동탐지 센서; 상기 행동탐지 센서에서 감지된 데이터를 수신받아 저장하고, 기저장된 축우 관련 사육정보와 함께 데이터베이스를 구축하는 DB 서버; 및 상기 DB 서버에 저장된 데이터를 분석하여, 소의 행동 패턴을 인식하고 건강을 관리하는 분석 서버를 포함하며, 상기 분석 서버는, 상기 DB 서버에 저장된 움직임 데이터를 기초로 분석하여, 소의 먹이 활동상태, 및 되새김 활동상태를 포함하는 행동 유형의 특징적 패턴을 찾아내고, 소의 행동 유형을 판단하는 행동 분석 모듈; 및 상기 행동 분석 모듈에서 판단된 상기 소의 행동 유형 정보를 통해 행동별 활동량을 분석하여, 소의 질병을 탐지하고 건강을 관리하는 질병 탐지 모듈을 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 되새김 활동 측정을 이용한 소의 건강 관리 시스템에 따르면, 행동탐지 센서에서 감지한 소의 먹이 활동상태, 및 되새김 활동상태의 행동 정보를 토대로, 소의 질병을 탐지하고 건강을 관리하는 질병 탐지 모듈을 포함함으로써, 소의 질병 감염 여부를 보다 정확하고 용이하게 판단할 수 있어, 소의 건강상태를 향상시키고 질병 미감지로 인한 피해를 줄여, 한우 농가의 생산성 및 수익성에 이바지할 수 있으며, 개별 가축에 대한 건강 정보를 지속해서 자동으로 제공함에 따라, 질병을 미리 예방하고 질병의 확산을 방지할 수 있다.또한, 본 발명에서 제안하고 있는 되새김 활동 측정을 이용한 소의 건강 관리 시스템에 따르면, 가속도 센서에서 감지된 3축 가속도 신호의 drift 발생으로 인해 생길 수 있는 오차를 보정 및 전처리하고, 감지된 3축 가속도 신호를 통계적, 수학적 방법으로 분석함으로써, 소의 행동 유형 패턴을 보다 정교하게 판단할 수 있으며, 특히, 인공지능 기술 중 딥러닝 알고리즘을 이용하여 소의 행동 유형을 판단함으로써, 같은 유형의 행동이 개체에 따라 다양한 신호 패턴을 보여 그 신호의 편차가 크더라도 오류를 줄일 수 있고, 개체별로 상이한 행동 양식, 성격, 생활 습성, 우방에서의 서열 등을 고려한 판단이 가능하여, 소의 질병 탐지적중률을 제고시킬 수 있다.뿐만 아니라, 본 발명에서 제안하고 있는 되새김 활동 측정을 이용한 소의 건강 관리 시스템에 따르면, 분석 서버에서 분석한 소의 행동 유형 정보 및 질병 탐지 정보와 관찰카메라부에서 촬영한 영상을 기초로, 소의 생애 주기에 따른 건강상태 추적 및 축사 모니터링이 가능한 스마트기기의 애플리케이션을 구축함으로써, 사용자에게 축사의 개체별 종합적인 건강 관리 솔루션을 제공하고, 궁극적으로는 축사 전반적으로 통합적인 관리서비스를 제공하여 축산업의 경쟁력을 상승시킬 수 있다. claims: 소의 건강 관리 시스템(10)으로서,소에 부착되어 소의 움직임 및 행동을 감지하는 행동탐지 센서(100);상기 행동탐지 센서(100)에서 감지된 데이터를 수신받아 저장하고, 기저장된 축우 관련 사육정보와 함께 데이터베이스를 구축하는 DB 서버(200);상기 DB 서버(200)에 저장된 데이터를 분석하여, 소의 행동 패턴을 인식하고 건강을 관리하는 분석 서버(300);축사를 24시간 촬영하고 촬영된 영상을 상기 DB 서버(200)로 송신하는 관찰카메라부(400); 및상기 분석 서버(300)에서 분석한 행동 유형 정보 및 건강 관리 정보와 상기 관찰카메라부(400)에서 촬영된 영상을 시각화시켜 보여주는 스마트기기(500)를 포함하며,상기 분석 서버(300)는,상기 DB 서버(200)에 저장된 움직임 데이터를 기초로 분석하여, 소의 먹이 활동상태, 및 되새김 활동상태를 포함하는 행동 유형의 특징적 패턴을 찾아내고, 소의 행동 유형을 판단하는 행동 분석 모듈(310); 및상기 행동 분석 모듈(310)에서 판단된 상기 소의 행동 유형 정보를 통해 행동별 활동량을 분석하여, 소의 질병을 탐지하고 건강을 관리하는 질병 탐지 모듈(320)을 포함하고,상기 질병 탐지 모듈(320)은,기설정된 일정 시간 단위로 행동 유형별 시간 점유율 및 분포를 계산하여 소의 질병 여부를 탐지하고 건강을 관리하며, 상기 DB 서버(200)에 저장된 움직임 데이터로부터 개체별 습성 및 상태 정보를 취득하여, 소의 질병 여부 판단을 보완하는 것을 특징으로 하는, 되새김 활동 측정을 이용한 소의 건강 관리 시스템(10)., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

576/1150 Row 576: application_number: 1020190090293, combined_string: invention_title: 젖소 유두 보호제 및 그 제조방법 abstract: 본 발명은 젖소 유두 보호제 및 그 제조방법에 관한 것이다.본 발명에 따른 젖소 유두 보호제는 미네랄 오일, 호호바씨 오일, 라놀린 오일, 토코페릴아세테이트, 소르비탄세스퀴올리에이트, 카프릴릭/카프릭트리글리세라이드, 이소프로필팔미테이트, 이소프로필메칠페놀(o-사이멘-5-올(o-Cymen-5-ol)) 및 부틸파라벤으로 이루어진 조성물을 포함한다.상기한 구성에 의해 본 발명은 보습력을 향상시켜 젖소의 유두를 항상 부드럽게 유지하고 겨울철 영하의 날씨에도 유두 및 유두 주변의 살이 트거나 갈라지는 것을 방지함으로써, 착유시 젖소의 스트레스를 줄일 수 있고 젖소 유두 주변에 오물이 쉽게 부착되는 것을 방지할 수 있다. claims: 미네랄 오일, 호호바씨 오일, 라놀린 오일, 토코페릴아세테이트, 소르비탄세스퀴올리에이트, 카프릴릭/카프릭트리글리세라이드, 이소프로필팔미테이트, 이소프로필메칠페놀(o-사이멘-5-올(o-Cymen-5-ol)) 및 부틸파라벤으로 이루어진 조성물을 포함하되,상기 조성물은 미네랄 오일 97 내지 99 중량부, 호호바씨 오일 0.2 내지 0.4 중량부, 라놀린 오일 0.15 내지 0.35 중량부, 토코페릴아세테이트 0.05 내지 0.25 중량부, 소르비탄세스퀴올리에이트 0.05 내지 0.15 중량부, 카프릴릭/카프릭트리글리세라이드 0.05 내지 0.15 중량부, 이소프로필팔미테이트 0.05 내지 0.15 중량부, 이소프로필메칠페놀(o-사이멘-5-올(o-Cymen-5-ol)) 0.005 내지 0.015 중량부 및 부틸파라벤 0.03 내지 0.07 중량부가 포함되고,상기 조성물 이외에, 보이차 추출액 1 내지 3 중량부, 어성초 추출액 2 내지 4 중량부, 오레가노 오일 3 내지 7 중량부 및 브링그라즈 오일 1 내지 3 중량부가 더 포함되되,상기 보이차 추출액은,보이차 생잎을 준비한 후 세척하여 상기 보이차 생잎에 부착되어 있는 이물질을 제거한 후, 상기 세척된 보이차 생잎을 25 내지 30℃ 온도에서 5 내지 10시간 동안 건조하고, 상기 건조된 보이차 생잎을 가열 용기에 투입한 후 90 내지 100℃의 온도에서 3 내지 5분 동안 1차 덖음하고, 상기 1차 덖음된 보이차 생잎을 130 내지 140℃의 온도에서 30 내지 60초 동안 2차 덖음하며, 상기 2차 덖음된 보이차 생잎에 용매를 혼합하고 초음파를 가함으로써 보이차 혼합액을 제조하되, 상기 용매는 상기 2차 덖음된 보이차 생잎 100 중량부에 대해 300 내지 600 중량부의 중량 비율로 혼합되고, 상기 용매로는 물이 사용되며, 상기 2차 덖음된 보이차 생잎 및 용매로 이루어진 혼합물에 가해지는 초음파는 60 내지 80KHz의 진동주파수에서 30 내지 60분 동안 300 내지 400와트(watt)의 출력을 이용하며, 상기 보이차 혼합액에서 고형분을 분리하여 제거한 후 10 내지 15℃의 온도에서 3 내지 7시간 동안 보관하여 숙성하는 과정을 거쳐 제조되고,상기 어성초 추출액은,어성초를 준비한 후 세척하고, 상기 세척된 어성초를 입경이 500 내지 2500㎛의 범위가 되도록 분쇄하며, 상기 분쇄된 어성초를 용매와 혼합하여 혼합액을 제조한 후, 초음파 추출기에 투입하여 20 내지 25℃의 온도 및 0.1 내지 0.5kgf/cm2의 압력하에서 상기 혼합액에 초음파를 가함으로써 어성초 추출 혼합액을 제조하되, 상기 용매는 상기 분쇄된 어성초 100 중량부에 대해 1000 내지 2000 중량부의 중량비율로 혼합되고, 상기 용매로는 물 또는 탄소수 1 내지 4(C1 내지 C4)의 알코올 중에서 선택된 어느 하나 이상의 용매가 사용되며, 상기 혼합액에 가해지는 초음파는 30 내지 50KHz의 진동주파수에서 30 내지 60분 동안 100 내지 200와트(watt)의 출력을 이용하고, 상기 어성초 추출 혼합액에서 고형물을 제거한 후 10 내지 20℃의 온도에서 1 내지 3시간 동안 숙성하는 과정을 거쳐 제조된 것을 특징으로 하는 젖소 유두 보호제., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

577/1150 Row 577: application_number: 2020190002748, combined_string: invention_title: 축사용 문틀 잠금장치 abstract: 본 고안은 가축용 문틀 잠금장치에 관한 것으로, 걸림쇠가 형성되고 양방향으로 개폐되는 축사문의 개폐를 단속하도록 문틀에 설치된 축사용 문틀 잠금장치에 있어서, 상기 문틀에 설치된 몸체; 상기 몸체의 양측에 각각 기 설정된 각도 및 서로 마주보는 방향으로 회동 가능하게 결합된 단속판; 및 상기 단속판 사이에 서로가 연결되도록 결합된 탄성체;를 포함하고, 상기 축사문 폐쇄 시 상기 걸림쇠의 삽입에 의해 상기 걸림쇠와 인접하는 단속판이 밀려 회동되면서 개방되고 상기 걸림쇠 삽입 후 다시 탄성 및 무게 중심에 의해 회동되며 폐쇄되어 상기 축사문을 단속시키며, 상기 단속판은 개방되도록 회동 시, 상기 몸체의 양측에 각각 형성된 스토퍼에 의해 상기 걸림쇠의 직경과 동일한 높이까지만 개방되도록 회동되는 것을 특징으로 한다. 이러한 구성으로, 걸림쇠가 삽입될 때 단속판이 서로 마주하는 방향으로만 회동되도록 형성함으로써, 축사문이 회동됨에 따라 걸림쇠가 자연스레 단속판을 밀치며 삽입 고정되어 폐쇄되거나, 일방향의 단속판을 상방으로 회동시킨 상태에서 걸림쇠를 일방향으로 당김에 따라 축사문의 단속 해제에 의해 개방되도록 하여, 가축에 의해 임의적으로 축사문이 개방되는 것을 방지할 수 있는 효과를 얻을 수 있다. claims: 걸림쇠가 형성되고 양방향으로 개폐되는 축사문의 개폐를 단속하도록 문틀에 설치된 축사용 문틀 잠금장치에 있어서,상기 문틀에 설치된 몸체;상기 몸체의 양측에 각각 기 설정된 각도 및 서로 마주보는 방향으로 회동 가능하게 결합된 단속판; 및상기 단속판 사이에 서로가 연결되도록 결합된 탄성체;를 포함하고,상기 축사문 폐쇄 시 상기 걸림쇠의 삽입에 의해 상기 걸림쇠와 인접하는 단속판이 밀려 회동되면서 개방되고 상기 걸림쇠 삽입 후 다시 탄성 및 무게 중심에 의해 회동되며 폐쇄되어 상기 축사문을 단속시키며,상기 단속판은 개방되도록 회동 시, 상기 몸체의 양측에 각각 형성된 스토퍼에 의해 상기 걸림쇠의 직경과 동일한 높이까지만 개방되도록 회동되고,상기 몸체의 하방에는 상기 단속판이 폐쇄되도록 회동 시 밀착되는 하부 프레임이 형성되고,상기 하부 프레임의 상면에는 상기 단속판이 밀착된 상태에서 각 외측면과 밀착되는 끼임방지턱이 형성되며,상기 하부 프레임은,상면으로부터 상기 단속판의 밀착여부 또는 상기 걸림쇠의 접촉여부를 감지하는 근접센서가 구비되고,상기 근접센서로부터 전달받은 감지값에 따라 단속 여부를 알리는 알림장치가 구비되며,상기 하부 프레임의 일측면에 제1 홀이 형성되고, 상면에는 상기 제1 홀과 직교되도록 연통되는 제2 홀이 형성되며, 상기 제1 홀에는 고정핀이 결합되고 상기 고정핀의 일단에는 상기 제2 홀과 연통되는 부분에 제1 베벨기어가 형성되며 타단이 외부로 돌출되고, 상기 제2 홀에는 고정부재가 결합되며 상기 고정부재의 일단에는 상기 제1 베벨기어와 맞물리는 제2 베벨기어가 형성되고 타단이 외부로 돌출되고 외부로 돌출된 부분에 수나사산이 형성되며,상기 단속판의 하단에는 상기 제2 홀과 마주보는 위치에 이동홈이 형성되고, 상기 이동홈에는 이동부재가 이동 가능하게 결합되며, 상기 이동홈의 내측에는 상기 이동부재와 연결된 스프링이 구비되고, 상기 이동부재의 단부에는 상기 수나사산과 나사 결합되는 암나사산이 형성된 것을 특징으로 하는 축사용 문틀 잠금장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

578/1150 Row 578: application_number: 1020190076982, combined_string: invention_title: 가축의 사양관리 시스템 abstract: 가축의 사양관리 시스템은 가축의 귀에 부착되며, 가축의 활동 및 신체 정보를 센싱하고, 가축의 사양 정보를 표시하는 태그부, 상기 태그부에서 센싱한 데이터를 이용하여 가축의 사양 정보를 분석하는 축사 서버, 상기 태그부와 상기 축사 서버 간의 네트워크 연결을 중계하는 통신 중계부, 상기 축사 서버를 제어하고, 상기 축사 서버에서 분석한 가축의 사양 정보를 표시하는 사용자 단말기 및 상기 축사 서버에서 분석한 데이터를 저장하고 빅데이터화하여 가축의 사양 정보를 분석하는 메인 서버를 포함한다. claims: 가축의 귀에 부착되며, 가축의 활동 및 신체 정보를 센싱하고, 가축의 사양 정보를 표시하는 태그부;상기 태그부에서 센싱한 데이터를 이용하여 가축의 사양 정보를 분석하는 축사 서버;상기 태그부와 상기 축사 서버 간의 네트워크 연결을 중계하는 통신 중계부; 상기 축사 서버를 제어하고, 상기 축사 서버에서 분석한 가축의 사양 정보를 표시하는 사용자 단말기; 및상기 축사 서버에서 분석한 데이터를 저장하고 빅데이터화하여 가축의 사양 정보를 분석하는 메인 서버를 포함하는 가축의 사양관리 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

579/1150 Row 579: application_number: 1020190075107, combined_string: invention_title: 부식케이스 교체 용이한 축사용 부식방지 공기 조화장치 abstract: 본 발명은 부식케이스 교체 용이한 축사용 부식방지 공기 조화장치에 관한 것으로서, 보다 상세하게는 축사 내부 또는 외부에 설치되어, 축사 내부로 온풍 또는 냉풍을 제공할 수 있도록 하는 공기 조화장치에 관한 것이되, 이러한 공기 조화장치는 전체가 다수개의 케이스가 상호간 적층되며 조립 및 분해가 가능한 구조를 가지도로 함으로써, 부식방지 및 부식이 발생되는 케이스나 구성품만을 교체수리할 수 있어, 부식이 전이되는 것을 방지하여 유지보수가 용이토록 하며, 설치시에도 분리운반 후, 해당 설치공간에서 조립하여 설치할 수 있어, 설치시공조립도 용이한 구조를 가지는 부식케이스 교체 용이한 축사용 부식방지 공기 조화장치에 관한 것이다. claims: 축사 내부 또는 외부에 설치되어, 축사 내부로 냉/온풍을 제공하기 위한 공기 조화장치로써, 외기를 가열 또는 냉각시키는 열교환부(30)와, 외기의 습도를 사전설정습도로 유지시키는 가습부(40)가 설치되어, 외기를 상부로 이동시키는 외기 처리부(10);상기 외기 처리부(10)의 공기를 필터링하여 축사 내부에 제공하기 위해, 이송팬(60) 및 필터부재(70)가 설치되는 공급부(20);로 이루어지되,상기 외기 처리부(10)와 공급부(20) 각각은내부의 공간을 상, 하측으로 구획할 수 있도록, 상/하로 개별분리가 가능한 제 1, 2케이스(11, 12) 및 제 3, 4케이스(21, 22)로 각각 이루어지도록 하여, 공기 조화장치(100)를 축사에 설치시, 케이스 다수를 개별분리하여 운반 후, 축사에서 설치될 수 있도록 함으로써, 설치시공이 용이토록 하고,축사에서 발생되는 유해가스에 의해 내부 구성품 또는 케이스가 부식되는 경우, 해당 구성품 또는 제 1, 2케이스(11, 12) 중 부식되는 케이스만을 개별분리교체하여, 연결된 다른 케이스와 구성품에 부식이 전이되지 않도록 설치되며,상기 제 1, 2, 3, 4케이스(11, 12, 21, 22)는 상호간 접촉부분에 부식방지부재(80)가 설치되어, 상호간 부식이 전이되지 않도록 하고,상기 제 1, 2, 3, 4케이스(11, 12, 21, 22)가 적층되어 구성되는 공기 조화장치(100)는, 외주면 모서리 부분에 적층길이방향을 향해 모서리를 감싸면서, 제 1, 2, 3, 4케이스(11, 12, 21, 22) 상호간이, 동일수직선상에 위치되며 부동될 수 있도록 하는 다수의 지지 고정체(90); 를 더 구비하며,상기 다수의 지지 고정체(90)는상기 공기 조화장치(100)와 접촉되는 내측면에 부식방지부재(80)가 설치되어, 공기 조화장치(100)와 지지 고정체(90) 상호간의 부식 전이를 방지하고, 다수의 지지 고정체(90)를 통해 제 1, 2, 3, 4케이스(11, 12, 21, 22) 상호간의 부식 전이가 방지되도록 하고,상기 지지 고정체(90)는 제 3케이스(21)의 상단모서리, 제 2케이스(12)의 하단모서리, 제 3, 4케이스(21, 22)의 접촉부분 모서리, 제 4, 1케이스(22, 11)의 접촉부분 모서리, 제 1, 2케이스(11, 12)의 접촉부분 모서리마다 연장되는 연장편(91)을 형성하여, 이러한 연장편(91)에 고정부재(B)를 통해 제 1, 2, 3, 4케이스(11, 12, 21, 22)에 지지 고정체(90)가 일체로 고정 및 각각의 케이스마다 개별분리가 가능한 구조를 가지도록 하며,상기 외기 처리부(10)는 외기가 유입되는 공기 유입구(13)에 열교환부(30) 부식 방지를 위한, 유해가스 제거용 활성탄 재질의 가스필터(50)가 설치되는 것을 특징으로 하는 부식케이스 교체 용이한 축사용 부식방지 공기 조화장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

580/1150 Row 580: application_number: 1020190075108, combined_string: invention_title: 부식케이스 교체가 용이하며 희생양극을 이용한 축사용 부식방지 공기 조화장치 abstract: 본 발명은 부식케이스 교체가 용이하며 희생양극을 이용한 축사용 부식방지 공기 조화장치에 관한 것으로서, 보다 상세하게는 축사 내부 또는 외부에 설치되어, 축사 내부로 온풍 또는 냉풍을 제공할 수 있도록 하는 공기 조화장치에 관한 것이되, 희생양극부를 내부의 구성부품 및 케이스에 연결시켜 부식이 발생되지 않도록 함과 동시에, 이러한 공기 조화장치는 전체가 다수개의 케이스가 상호간 적층되며 조립 및 분해가 가능한 구조를 가지도로 함으로써, 부식방지 및 부식이 발생되는 케이스나 구성품만을 교체수리할 수 있어, 부식이 전이되는 것을 방지하여 유지보수가 용이토록 하며, 설치시에도 분리운반 후, 해당 설치공간에서 조립하여 설치할 수 있어, 설치시공조립도 용이한 구조를 가지는 부식케이스 교체가 용이하며 희생양극을 이용한 축사용 부식방지 공기 조화장치에 관한 것이다. claims: 축사 내부 또는 외부에 설치되어, 축사 내부로 냉/온풍을 제공하기 위한 공기 조화장치로써, 외기를 가열 또는 냉각시키는 열교환부(30)와, 외기의 습도를 사전설정습도로 유지시키는 가습부(40)가 설치되어, 외기를 상부로 이동시키는 외기 처리부(10);상기 외기 처리부(10)의 공기를 필터링하여 축사 내부에 제공하기 위해, 이송팬(60) 및 필터부재(70)가 설치되는 공급부(20);로 이루어지되,상기 외기 처리부(10)와 공급부(20) 각각은내부의 공간을 상, 하측으로 구획할 수 있도록, 상/하로 개별분리가 가능한 제 1, 2케이스(11, 12) 및 제 3, 4케이스(21, 22)로 각각 이루어지도록 하여, 공기 조화장치(100)를 축사에 설치시, 케이스 다수를 개별분리하여 운반 후, 축사에서 설치될 수 있도록 함으로써, 설치시공이 용이토록 하고,축사에서 발생되는 유해가스에 의해 내부 구성품 또는 케이스가 부식되는 경우, 해당 구성품 또는 제 1, 2케이스(11, 12) 중 부식되는 케이스만을 개별분리교체하여, 연결된 다른 케이스와 구성품에 부식이 전이되지 않도록 하며,상기 외기 처리부(10), 공급부(20), 제 1, 2, 3, 4케이스(11, 12, 21, 22)에 각각 설치되어 부식을 방지하면서, 인접한 구성부품 또는 케이스에 부식이 전이되지 않도록 설치되는 희생양극부(110); 가 설치되며,상기 제 1, 2, 3, 4케이스(11, 12, 21, 22)는상호간 접촉부분에 부식방지부재(80)가 설치되어, 상호간 부식이 전이되지 않도록 하고,상기 제 1, 2, 3, 4케이스(11, 12, 21, 22)가 적층되어 구성되는 공기 조화장치(100)는, 외주면 모서리 부분에 적층길이방향을 향해 모서리를 감싸면서, 제 1, 2, 3, 4케이스(11, 12, 21, 22) 상호간이, 동일수직선상에 위치되며 부동될 수 있도록 하는 다수의 지지 고정체(90); 를 더 구비하며,상기 다수의 지지 고정체(90)는상기 공기 조화장치(100)와 접촉되는 내측면에 부식방지부재(80)가 설치되어, 공기 조화장치(100)와 지지 고정체(90) 상호간의 부식 전이를 방지하고, 다수의 지지 고정체(90)를 통해 제 1, 2, 3, 4케이스(11, 12, 21, 22) 상호간의 부식 전이가 방지되도록 하며,상기 지지 고정체(90)는 3케이스(21)의 상단모서리, 최하단인 제 2케이스(12)의 하단모서리, 제 3, 4케이스(21, 22)의 접촉부분 모서리, 제 4, 1케이스(22, 11)의 접촉부분 모서리, 제 1, 2케이스(11, 12)의 접촉부분 모서리마다 연장되는 연장편(91)을 형성하여, 연장편(91)에 고정부재(B)를 통해 제 1, 2, 3, 4케이스(11, 12, 21, 22)에 지지 고정체(90)가 일체로 고정 및 각각의 케이스마다 개별분리가 가능한 구조를 가지도록 하며,상기 외기 처리부(10)는외기가 유입되는 공기 유입구(13)에 열교환부(30) 부식 방지를 위한, 유해가스 제거용 활성탄 재질의 가스필터(50)가 설치되며,상기 희생양극부(110)는상기 외기 처리부(10), 공급부(20), 제 1, 2, 3, 4케이스(11, 12, 21, 22) 각각에 직접연결되거나, 또는 전선을 이용하여 연결됨으로써, 각각에 발생되는 부식전류를 희생양극부(110)로 전달하여 부식이 희생양극부(110)에서 발생되도록 하는 것을 특징으로 하는 부식케이스 교체가 용이하며 희생양극을 이용한 축사용 부식방지 공기 조화장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

581/1150 Row 581: application_number: 1020190069196, combined_string: invention_title: ICT 융복합 스마트 축사관리 제어방법 abstract: 외부로부터 공급되는 물을 이용하여 투약펌프로부터 공급되는 약물을 희석하는 희석부를 포함하여 희석된 약물을 공급하는 자동투약장치와, 외부로부터 공급되는 물이 저장되는 물탱크와, 상기 물탱크에 저장된 물에 압력을 가하여 공급하는 가압펌프와, 상기 가압펌프로부터 공급되는 물이 통과하면서 여과되는 여과장치와, 상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부와, 상기 혼압부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프와, 상기 물탱크로부터 공급되는 제1 물의 양을 측정하는 유량계와, 상기 축사 내 및 상기 축사 외의 습도 및 온도와 상기 축사 내의 공기의 질을 측정하는 센싱부와, 상기 축사 내의 온도, 습도 및 환기를 제어하는 축사환경 조절부와, 상기 자동투약장치의 희석 농도를 제어하는 제어부를 포함하는 안개분무 시스템을 제어하는 방법으로서,본 발명에 따른 ICT 융복합 스마트 축사관리 시스템의 제어방법은 상기 센싱부로부터 축사 내외의 온도 및 습도와 상기 축사 내의 공기의 질 데이터를 전달받는 데이터 수집 단계; 상기 전달된 데이터로부터 목표 습도에 부합하는 상기 혼압액의 농도를 산출하는 농도 산출 단계; 상기 산출된 혼압액의 농도에 따라 상기 유량계로부터 공급되는 물의 양을 전달받아 상기 희석부에서의 희석액 농도를 산출하는 희석액 농도 산출단계; 및 상기 산출된 희석액 농도 산출단계에 따라 희석부가 희석하는 제1 희석액 제조단계;를 포함한다. claims: 외부로부터 공급되는 물을 이용하여 투약펌프로부터 공급되는 약물을 희석하는 희석부를 포함하여 희석된 약물을 공급하는 자동투약장치와, 외부로부터 공급되는 물이 저장되는 물탱크와, 상기 물탱크에 저장된 물에 압력을 가하여 공급하는 가압펌프와, 상기 가압펌프로부터 공급되는 물이 통과하면서 여과되는 여과장치와, 상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 복수의 희석부와, 상기 희석부로부터 배출되는 상기 물과 상기 약물의 혼합액에 상기 여과장치로부터 공급되는 제1물을 혼합하는 혼합부와, 상기 혼합부에의하여 혼합된 약물을 일정한 압력을 가하여 축사 내로 공급하는 고압펌프와, 상기 물탱크로부터 공급되는 제1 물의 양을 측정하는 유량계와, 상기 축사 내 및 상기 축사 외의 습도 및 온도와 상기 축사 내의 공기의 질을 측정하는 센싱부와, 상기 축사 내의 온도, 습도 및 환기를 제어하는 축사환경 조절부와, 상기 자동투약장치의 희석 농도를 제어하는 제어부를 포함하는 ICT 융복합 스마트 축사관리 제어방법으로서,상기 센싱부로부터 축사 내외의 온도 및 습도와 상기 축사 내의 공기의 질 데이터를 전달받는 데이터 수집 단계;상기 전달된 데이터로부터 목표 습도에 부합하는 상기 혼합액의 농도를 산출하는 농도 산출 단계;상기 산출된 혼합액의 농도에 따라 상기 유량계로부터 공급되는 물의 양을 전달받아 상기 복수의 희석부 중 어느 한 희석부에서의 제조할 희석액 농도를 산출하는 희석액 농도 산출단계; 및상기 산출된 희석액 농도 산출단계에 따라 상기 어느 한 희석부가 희석하는 제1 희석액 제조단계;를 포함하고,상기 제1 희석액을 물과 혼합하여 상기 축사 내로 공급하는 혼합 및 공급단계;를 더 포함하며,상기 혼합 및 공급단계를 통하여 제1 희석액을 소진하면서 혼합액을 공급하는 과정에서 상기 산출된 혼합액의 농도에 따라 상기 복수의 희석부 중 타 희석부가 별도의 희석액을 제조하는 제2 희석액 제조단계;를 더 포함하고,상기 혼합 및 공급단계에서는 제1 희석액의 소진 후 상기 제2 희석액을 공급하여 혼합액을 형성하며,상기 혼합 및 공급단계 이전에 상기 축사환경 조절부가 온도, 습도 및 공기의 질에 대한 목표 축사 환경지수와 상기 고압펌프로부터 공급되는 혼합액에 의한 축사 환경 변동지수를 고려하여 축사 내의 온도 제어, 습도 제어 및 환기 제어를 수행하는 사전 환경조정 단계;를 더 포함하는 ICT 융복합 스마트 축사관리 제어방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

582/1150 Row 582: application_number: 1020190069197, combined_string: invention_title: 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템 abstract: 복수의 분무노즐을 이용하여 물과 약품이 혼합된 혼합액을 축사내로 분무하는 안개분무 시스템으로서, 본 발명에 따른 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템은 희석된 약물을 공급하는 자동투약장치; 외부로부터 공급되는 제1 물이 저장되는 물탱크; 상기 물탱크에 저장된 제1 물에 압력을 가하여 공급하는 가압펌프; 상기 가압펌프로부터 공급되는 제1 물이 통과하면서 여과되는 여과장치; 상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부; 상기 혼압부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프; 상기 고압펌프로부터 공급되는 혼압액을 상기 축사 내의 공간으로 이송하는 혼압액 이송배관; 상기 혼압액 이송배관에 구비되어 상기 혼압액을 분무하는 분무 노즐; 및 상기 축사 내에 수직방향으로 중공의 기둥 형상으로 형성되고, 하부에 제1 환기구가 형성되고, 상부에 제2 환기구가 형성되며, 상기 제1 환기구 및 상기 제2 환기구 사이의 공간부에는 팬부가 구비되는 에어순환기둥을 포함한다. claims: 복수의 분무노즐을 이용하여 물과 약품이 혼합된 혼합액을 축사내로 분무하는 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템으로서,희석된 약물을 공급하는 자동투약장치;외부로부터 공급되는 제1 물이 저장되는 물탱크;상기 물탱크에 저장된 제1 물에 압력을 가하여 공급하는 가압펌프;상기 가압펌프로부터 공급되는 제1 물이 통과하면서 여과되는 여과장치;상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부;상기 혼합부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프;상기 고압펌프로부터 공급되는 혼합액을 상기 축사 내의 공간으로 이송하는 혼합액 이송배관;상기 혼합액 이송배관에 구비되어 상기 혼합액을 분무하는 분무 노즐; 및상기 축사 내에 수직방향으로 중공의 기둥 형상으로 형성되고, 하부에 제1 환기구가 형성되고, 상부에 제2 환기구가 형성되며, 상기 제1 환기구 및 상기 제2 환기구 사이의 공간부에는 팬부가 구비되는 에어순환기둥을 포함하는 안개분무 시스템을 구비하고,상기 분무 노즐 중 상기 축사의 외벽 측에 구비되는 분무 노즐은 타 분무 노즐에 비하여 고압으로 혼합액을 분사하는 안개분무 시스템을 구비하며,상기 제2 환기구는 상기 축사의 벽체 상부에 구비되는 환기창의 높이에 비하여 같거나 높게 형성되는 안개분무 시스템을 구비하고,상기 축사의 지면 아래에는 외부 공기가 주입되는 에어공급관이 구비되고, 상기 에어공급관에는 복수의 에어 배출구가 형성되며,상기 에어 배출구는 상기 에어공급관의 저면에 형성되어 상기 축사 지면의 에어레이션을 수행하고,상기 환기창에는 환풍기가 구비되며,상기 자동투약장치는,약물이 저장되는 약물 탱크;상기 약물 탱크에 저장된 약물을 일정한 압력으로 공급하는 투약펌프; 및외부로부터 공급되는 제2 물을 이용하여 상기 투약펌프로부터 공급되는 약물을 희석하는 희석부;를 포함하고,상기 희석부는 적어도 둘 이상 구비되고, 상기 희석부 중 어느 한 희석부에 의하여 혼합부에 상기 물과 상기 약물의 희석액이 공급되는 경우 타 희석부에는 상기 제2 물을 이용하여 상기 약물의 희석 작업을 수행하는 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

583/1150 Row 583: application_number: 1020190069198, combined_string: invention_title: 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템 및 제어방법 abstract: 복수의 분무노즐을 이용하여 물과 약품이 혼합된 혼합액을 축사내로 분무하는 안개분무 시스템으로서, 본 발명에 따른 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템은 희석된 약물을 공급하는 자동투약장치; 외부로부터 공급되는 제1 물이 저장되는 물탱크; 상기 물탱크에 저장된 제1 물에 압력을 가하여 공급하는 가압펌프; 상기 가압펌프로부터 공급되는 제1 물이 통과하면서 여과되는 여과장치; 상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부; 상기 혼압부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프; 상기 고압펌프로부터 공급되는 혼압액을 상기 축사 내의 공간으로 이송하는 혼압액 이송배관; 상기 혼압액 이송배관에 구비되어 상기 혼압액을 분무하는 분무 노즐; 상기 축사 내 및 상기 축사 외의 습도 및 온도와 상기 축사 내의 공기의 질을 측정하는 센싱부; 상기 축사 내의 온도, 습도 및 환기를 제어하는 축사환경 조절부; 및 상기 센싱부로부터 데이터를 전달받아 상기 축사환경 조절부를 제어하여 축사환경을 개선하고 상기 자동투약장치의 희석 농도를 제어하여 혼합액을 공급제어하는 제어부를 포함한다. claims: 복수의 분무노즐을 이용하여 물과 약품이 혼합된 혼합액을 축사내로 분무하는 안개분무 시스템으로서,희석된 약물을 공급하는 자동투약장치;외부로부터 공급되는 제1 물이 저장되는 물탱크;상기 물탱크에 저장된 제1 물에 압력을 가하여 공급하는 가압펌프;상기 가압펌프로부터 공급되는 제1 물이 통과하면서 여과되는 여과장치;상기 여과장치로부터 공급되는 제1 물과 상기 자동투약장치로부터 공급되는 약물이 혼합되는 혼합부;상기 혼합부로부터 배출되는 상기 물과 상기 약물의 혼합액에 일정한 압력을 가하여 상기 축사 내로 공급하는 고압펌프;상기 고압펌프로부터 공급되는 혼합액을 상기 축사 내의 공간으로 이송하는 혼합액 이송배관;상기 혼합액 이송배관에 구비되어 상기 혼합액을 분무하는 분무 노즐;상기 축사 내 및 상기 축사 외의 습도 및 온도와 상기 축사 내의 공기의 질을 측정하는 센싱부;상기 축사 내의 온도, 습도 및 환기를 제어하는 축사환경 조절부; 및상기 센싱부로부터 데이터를 전달받아 상기 축사환경 조절부를 제어하여 축사환경을 개선하고 상기 자동투약장치의 희석 농도를 제어하여 혼합액을 공급제어하는 제어부를 포함하는 안개분무 시스템을 구비하고,상기 자동투약장치는,약물이 저장되는 약물 탱크;상기 약물 탱크에 저장된 약물을 일정한 압력으로 공급하는 투약펌프; 및외부로부터 공급되는 제2 물을 이용하여 상기 투약펌프로부터 공급되는 약물을 희석하는 희석부;를 포함하며,상기 희석부는 적어도 둘 이상 구비되고, 상기 희석부 중 어느 한 희석부에 의하여 혼합부에 상기 물과 상기 약물의 희석액이 공급되는 경우 타 희석부에는 상기 제2 물을 이용하여 상기 약물의 희석 작업을 수행하고,상기 축사환경 조절부는,상기 축사 내에 수직방향으로 중공의 기둥 형상으로 형성되고, 하부에 제1 환기구가 형성되고, 상부에 제2 환기구가 형성되며, 상기 제1 환기구 및 상기 제2 환기구 사이의 공간부에는 팬부가 구비되는 에어순환기둥; 및상기 축사의 바닥 상에 또는 상기 축사의 지면 아래에는 외부 공기가 주입되고, 저면에 상기 외부 공기를 배출하는 에어 배출구가 형성되는 에어공급관;을 포함하는 안개분무 시스템을 구비하며,상기 제어부는 상기 혼합액의 상기 축사 내 공급 이전에 온도, 습도 및 공기의 질에 대한 목표 축사 환경지수와 상기혼합액의 공급에 따른 축사 환경 변동지수를 고려하여 축사 내의 온도 제어, 습도 제어 및 환기 제어를 미리 수행하는 안개분무 시스템을 구비하는 ICT 융복합 스마트 축사관리 시스템., Ltext: 농업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

584/1150 Row 584: application_number: 2020190001912, combined_string: invention_title: 축사에서 이용하는 가축 결박장치 abstract: 본 고안은 축사에서 이용하는 가축 결박장치에 관한 것으로서, 상세하게는 축사내의 벽과 축사의 출입문에 해당하는 여닫이문 사이에 가축을 이동시킨 다음 권취기를 이용하여 여닫이문을 축사내의 벽으로 이동시켜 가축을 압박하듯이 결박하는 기술에 관한 것이다.구성은 다음과 같다.축사의 출입문에 해당하는 여닫이문(100)을 걸 수 있는 여닫이문고리(10)와;상기 여닫이문고리(10)의 일측에 로프(11) 일측이 연결되고 로프(11) 타측은 권취기(20)와 연결되며, 상기 권취기(20)의 감속모터(21)에 권취된 와이어(30)와, 상기 와이어(30) 끝단에 연결되어 축사의 벽에 걸 수 있는 벽면고리(40)와, 상기 와이어(30)에 가축이 상기 와이어(30)로부터 간섭을 받지 않도록 상기 와이어에 끼워진 긴 배관(50)과, 감속모터(21)에 전력을 출력하는 전선이 권선기(60)에 포함한 구성이다. claims: 축사의 출입문에 해당하는 여닫이문(100)을 걸 수 있는 여닫이문고리(10)와;상기 여닫이문고리(10)의 일측에 로프(11) 일측이 연결되고 로프(11) 타측은 권취기(20)와 연결되며, 상기 권취기(20)의 감속모터(21)에 권취된 와이어(30)와, 상기 와이어(30)에 끝단에 연결되어 축사의 벽에 걸 수 있는 벽면고리(40)와, 상기 와이어(30)에 가축이 상기 와이어(30)로부터 간섭을 받지 않도록 상기 와이어에 끼워진 긴 배관(50)과, 감속모터(21)에 전력을 출력하는 전선이 권선기(60)를 포함한 구성에 있어서,상기 긴 배관(50)은 복수로 분할(52) 하여 가축의 크기에 따라 수량을 조절하도록 구성하고,상기 로프(11)는 탄성부재(12)를 갖도록 하여 가축이 여닫이문(100)과 축사내의 벽면(200) 사이에서 압박을 받더라도 상기 탄성력(12)이 있어 움직일 수 있도록 구성하는 것을 특징으로 하는 축사에서 이용하는 가축 결박장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

585/1150 Row 585: application_number: 2020190001887, combined_string: invention_title: 축사의 국소적 부압수단에 의한 환기 시스템 abstract: 본 고안은 축사(畜舍)의 국소(局所)적 부압(負壓)수단에 의한 환기시스템에 관한 것으로 대형의 급기팬과 배기팬이 좌우 양측에 마주보게 설치되어 환기하게 된 축사에 있어서,측사에 국소적으로 흡기(吸氣)에 의해 부압이 조성되게 하는 흡기관과; 상기 흡기관의 유입구에 접속되어 상기 흡기관을 통하여 흡입되는 공기와 이물질을 분리하는 사이크론(Cycrone)과; 상기 사이크론의 유출구에 접속되어 상기 흡기관 주위에 형성되는 부압을 유지하여 신선한 공기영역이 부압 측으로 확장되게 하는 에어펌프의; 결합으로 구성된 것이다.본 발명에 의하면, 여러 개의 좁은 칸막이로 된 돼지우리, 또는 병아리나 닭이 사육되는 축사의 바닥면, 즉, 악취공기를 제거할 장소에 상기 흡기관을 배치하고 에어펌프를 가동하면 흡기관의 흡기공으로 흡입된 이물질과 악취공기는 사이크론에 의해 분리되어 공기는 외부로 배출되고 상기 흡기관의 주위에는 부압(reducing pressure)이 형성되면서 대형 급기팬에 의해 축사내부에 형성되는 신선한 공기영역이 부압 측으로 확장되어 신선한 공기영역에서 가축들이 건강하게 사육될 수 있다. claims: 측사에 국소적으로 흡기(吸氣)에 의해 부압이 조성되게 하는 여러 개의 흡기공이 천공된 흡기관과; 상기 흡기관이 유입구에 접속되어 상기 흡기관을 통하여 흡입되는 공기와 이물질을 분리하는 사이크론(Cycrone)과; 상기 사이크론의 유출구에 접속되어 상기 흡기관 주위에 형성되는 부압을 유지하여 신선한 공기영역이 부압 측으로 확장되게 하는 모터로 구동되는 에어펌프를; 포함하여 구성된 것을 특징으로 하는 축사의 국소적 부압수단에 의한 환기시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

586/1150 Row 586: application_number: 1020190050687, combined_string: invention_title: 가축의 반추위를 모니터링하는 장치 및 방법 abstract: 가축의 반추위에 삽입된 센서 장치로부터 움직임 데이터를 수집하여 가축의 활동을 분석하고, 활동 정보를 이용하여 가축의 건강 및 질병 관리 정보를 모니터링하는 장치 및 방법에 관한 것이다. 본 발명에 따라 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 장치는, 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하는 데이터 센싱부; 수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 활동 분석부; 및 분석된 활동 정보를 저장하고, 활동 정보가 분석되지 않는 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 모니터링부를 포함한다. claims: 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 장치에 있어서,상기 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하는 데이터 센싱부;수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 활동 분석부; 및분석된 활동 정보를 저장하고, 상기 활동 정보의 분석에 따른 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 모니터링부를 포함하는 것을 특징으로 하는 장치.장치가 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 방법에 있어서,상기 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하여 센싱하는 단계;수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 단계; 및분석된 활동 정보를 저장하고, 상기 활동 정보의 분석에 따른 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 단계를 포함하는 것을 특징으로 하는 방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

587/1150 Row 587: application_number: 1020190043757, combined_string: invention_title: 축사의 배출가스를 이용한 스마트팜 연동형 축산폐수 처리 시스템 abstract: 본 발명은 축사(10)와 스마트팜(20)을 포함하는 스마트팜 연동형 축산폐수 처리 시스템에 있어서, 상기 축사(10)에서 배출되는 배출가스가 포집되어 질소와 탄소를 포함하는 처리가스로 처리되는 배출가스 처리부(30); 상기 처리가스를 공급받는 스마트팜(20); 및 상기 배출가스 처리부(30)와 상기 스마트팜(20)의 연결라인에서 분기된 이송라인에 의해 처리가스를 각각 공급받으며, 상기 축사(10)의 축산폐수를 처리하는 액비 처리부(300) 및 퇴비 처리부(400)를 포함하는, 스마트팜 연동형 축산폐수 처리 시스템을 제공한다. claims: 축사(10)와 스마트팜(20)을 포함하는 스마트팜 연동형 축산폐수 처리 시스템에 있어서,상기 축사(10)에서 배출되는 배출가스가 포집되어 질소와 탄소를 포함하는 처리가스로 처리되는 배출가스 처리부(30);상기 처리가스를 공급받는 스마트팜(20); 및 상기 배출가스 처리부(30)와 상기 스마트팜(20)의 연결라인에서 분기된 이송라인에 의해 처리가스를 각각 공급받으며, 상기 축사(10)의 축산폐수를 처리하는 액비 처리부(300) 및 퇴비 처리부(400)를 포함하고,상기 배출가스 처리부(30)와 상기 스마트팜(20)의 연결라인의 분기부에 위치하는 밸브를 더 포함하고,야간 시, 상기 밸브를 제어하여 상기 스마트팜(20)으로의 이송라인을 차단한 채, 상기 배출가스 처리부(30)의 처리가스를 상기 액비 처리부(300) 및 상기 퇴비 처리부(400) 중 어느 하나 이상에 제공하도록 제어하는, 스마트팜 연동형 축산폐수 처리 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

588/1150 Row 588: application_number: 1020190039165, combined_string: invention_title: 소 관리시스템 및 관리방법 abstract: 본 발명은 소 관리시스템 및 관리방법에 관한 것으로, 더욱 구체적으로 설명하면, 한우, 육우, 젖소와 같은 소(이하 '소'라 칭함)의 체온과 맥박을 실시간으로 모니터링하여 측정된 수치를 무선전송하고 무선전송된 수치가 관리 서버에 수신 및 저장되고 수신된 정보가 분석되고 분석된 데이터가 사용자의 휴대용 단말기에 전송되어 사용자가 소의 현재의 질병, 임신, 배고픔, 갈증과 같은 소의 현재상태를 실시간으로 알 수 있게 되어 구제역과 같은 긴급한 질병이나 임신상황과 같은 소의 상황을 실시간으로 파악하여 필요한 조치를 취할 수가 있게 되어 소들을 보다 질병이나 배고픔과 같은 욕구를 해결하여 육질이나 우유의 질을 개선하는 것이 가능하게 되는 소 관리시스템 및 관리방법에 관한 것이다. claims: 소 관리시스템(A)에 있어서,상기 소 관리시스템(A)은, 축사(1)내에서 다수가 사육되고 있는 각각의 소(11)의 목에 걸려있는 배터리, 온도센서, 맥박센서, 무선송신부, 제어칩을 포함하는 측정단말기(12)와; 상기 측정단말기(12)에 의하여 송신된 데이터를 포집하는 무선 모뎀 라우터(2)와; 상기 축사(1)에서 이격된 위치의 사무실(3)에 설치되며 상기 무선 모뎀 라우터(2)와 랜으로 연결되어 상기 무선 모뎀 라우터에 의하여 송신된 데이터를 수신하고 수신된 데이터를 분석 및 가공하는 관리서버(31)와; 상기 관리서버(31)에서 송신된 분석 및 가공된 데이터를 수신하는 사용자의 휴대폰, 노트북 또는 PDA의 이동형 단말기(4);를 포함하는 것을 특징으로 하는 소 관리시스템소 관리방법에 있어서,상기 소 관리방법은, 축사내의 각각의 소의 목에 걸려 있는 측정단말기에 의하여 소의 온도와 맥박에 대한 정보를 실시간으로 감지하고 무선 모뎀 라우터로 송신시키는 단계와, 상기 무선 모뎀 라우터로 수신된 정보를 관리서버로 송신시키는 단계와, 송신된 정보를 관리서버에서 수신하고 수신된 각각의 소의 온도와 맥박에 대한 정보를 실시간으로 분석 및 가공하고 가공된 정보를 관리서버의 통신부를 통하여 사용자의 휴대 단말기, 노트북 또는 PDA송신하는 단계와, 상기 관리서버로부터 송신된 데이터를 수신하여 이상 상황의 이벤트가 발생되면 실시간으로 조치를 취하는 단계를 포함하는 것을 특징으로 하는 소 관리방법, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

589/1150 Row 589: application_number: 2020190001365, combined_string: invention_title: 축사용 급수장치 abstract: 축사용 급수장치를 개시한다.이러한 축사용 급수장치는, 급수를 위한 물이 담겨지는 급수탱크를 구비한 급수탱크부와, 상기 급수탱크부 측으로부터 물을 공급받을 수 있는 상태로 축사에 이격 배치되는 복수 개의 급수대들을 구비한 급수부와, 상기 급수부의 급수대들 측과 각각 대응하도록 배치되어 이 급수대들의 수위에 따라 물 공급이 가능하게 개폐 동작되도록 설치되는 플로트 밸브들을 구비한 개폐부와, 상기 급수탱크부 측에 담겨진 물이 자연 낙하에 의한 흐름으로 상기 급수부의 급수대들 측을 순차적으로 경유하는 상태로 상기 개폐부 측을 통해 공급될 수 있도록 배관되는 급수관을 구비한 관로부 및 상기 관로부를 따라 상기 급수부의 급수대들 측을 순차적으로 경유하는 상태로 흐르는 물이 담겨질 수 있는 저장탱크를 구비한 저장탱크부를 포함한다. claims: 급수를 위한 물이 담겨지는 급수탱크를 구비한 급수탱크부;상기 급수탱크부 측으로부터 물을 공급받을 수 있는 상태로 축사에 이격 배치되는 복수 개의 급수대들을 구비한 급수부;상기 급수부의 급수대들 측과 각각 대응하도록 배치되어 이 급수대들의 수위에 따라 물 공급이 가능하게 개폐 동작되도록 설치되는 플로트 밸브들을 구비한 개폐부;상기 급수탱크부 측에 담겨진 물이 자연 낙하에 의한 흐름으로 상기 급수부의 급수대들 측을 순차적으로 경유하는 상태로 상기 개폐부 측을 통해 공급될 수 있도록 배관되는 급수관을 구비한 관로부;상기 관로부를 따라 상기 급수부의 급수대들 측을 순차적으로 경유하는 상태로 흐르는 물이 담겨질 수 있는 저장탱크를 구비한 저장탱크부; 및상기 관로부 내의 물 흐름 방향 전환을 위하여 상기 저장탱크부의 저장탱크 측을 높낮이 조절이 가능하게 받쳐줄 수 있도록 형성되는 전환지지대를 구비한 급수전환부;를 포함하는 축사용 급수장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

590/1150 Row 590: application_number: 1020190035415, combined_string: invention_title: 실내 정화용 태양광가열장치가 구비된 축사용 시설물 abstract: 본 발명은 실내 정화용 태양광가열장치가 구비된 축사용 시설물에 관한 발명으로서, 상세하게는 축사와 같은 가축이나 원예작물 기르는 시설물에 맞추어서 태양광 발전판을 설치하여 주되, 비치는 태양광으로 발전되는 전력으로 가동되는 펌프에 의한 가압공기를 급속한 서냉으로 형성되는 냉각공기를 축사의 실내공간에 분출로서 실내정화를 제공하는 발명이다.일반적으로 축사용 하우스와 같은 축사단지는 대부분 도시의 가장자리에서 기술의 발전에 따라 점점 대단위로 설치함으로서, 이의 면적에서 기후 변화로 형성되는 폭염이나 혹서기에 발생하는 피해에 대한 대비가 필요하는 것이다.이는 하우스를 서로 연속적으로 설치로서 원예단지나 하우스로 제공되는 실내공간은 넓은 면적을 형성함으로서, 상기 비닐하우스 단지의 면적에 비치는 태양광의 량으로 발전하는 발전량은 많다고 할 것입니다.따라서 본 발명을 상세히 설명하면, 축산단지(43)의 실내공간(28)이 구비되도록, 골조(11)의 외측으로 감싸주는 비닐(21)로 조립으로 형성되는 하우스(20)와, 상기 하우스(20)용 갓길(14)에서 연속 반복적으로 길이방향에 따라 돌출되는 기둥(15)과, 상기 돌출되는 기둥(15) 사이를 일체로 연결되는 프레임(29), 상기 프레임(29)에 결합된 미도시된 제어장치의 구동으로 회전되는 회전형 도어(27)로, 기둥(15) 사이에 설치된 차양막(30)의 구동으로 조절되는 공기통로(41)와, 상기 기둥(15)을 연결되는 빔(17)으로 구축된 하우스(20)에서 양측으로 경사지는 경사프레임(23)과 돌출부(38)의 구비로 조립구간(18)을 형성시켜 주는 축산단지에 있어서, 상기 경사프레임(23)에 힌지(36)로 결합되는 태양광가열판(40)과, 상기 태양광가열판(40)의 모서리에 연결되는 로푸(39)의 구비로 태양광의 비치는 방향에 따라 힌지(36)을 중심으로 일측의 태양광가열판(40)이 회전으로 열려지는 경사프레임(23)과, 상기 태양광가열판(40)의 하측으로 고정로드(24)에 조립되는 흰색의 열반사대(35)의 구비로 축산단지(43)의 실내에 서냉이나 보온되도록 제공되는 발명이다.또한 상기 태양광가열판(40)을 소정의 이격된 간격으로 발전소자(16)을 구비된 태양광발전판(25)으로 형성시켜 주되, 상기 빔(17)의 중앙부에서 태양광발전판(25)의 중심부를 고정하도록 연결되는 회전축(37)과, 상기 회전축(37)이 교차하도록 고정봉(22)에 구비된 베벨기어(26)와, 상기 베벨기어(26)의 회전구동으로, 태양광발전판(25)이 태양광 비치는 량을 차단 구동함으로서, 햇볕 유입 및 배출구간(a)(b)을 형성하는 수평구간(c)으로 회전시켜 주고, 상기 실내공간(28)의 상측구간(d)에 구비된 지지로드(46)에 공기 이동구간을 형성하는 안내벽(42)으로, 혹한기에 냉해 방지나, 태풍에 의한 피해를 방지되도록 제공되는 발명이다. claims: 축산단지(43)의 실내공간(28)이 구비되도록, 골조(11)의 외측으로 감싸주는 비닐(21)로 조립으로 형성되는 하우스(20)와, 상기 하우스(20)용 갓길(14)에서 연속 반복적으로 길이방향에 따라 돌출되는 기둥(15)과, 상기 돌출되는 기둥(15) 사이를 일체로 연결되는 프레임(29), 상기 프레임(29)에 결합된 미도시된 제어장치의 구동으로 회전되는 회전형 도어(27)로, 기둥(15) 사이에 설치된 차양막(30)의 구동으로 조절되는 공기통로(41)와, 상기 기둥(15)을 연결되는 빔(17)으로 구축된 하우스(20)에서 양측으로 경사지는 경사프레임(23)과 돌출부(38)의 구비로 조립구간(18)을 형성시켜 주는 축산단지에 있어서, 상기 경사프레임(23)에 힌지(36)로 결합되는 태양광가열판(40)과, 상기 태양광가열판(40)의 모서리에 연결되는 로푸(39)의 구비로 태양광의 비치는 방향에 따라 힌지(36)을 중심으로 일측의 태양광가열판(40)이 회전으로 열려지는 경사프레임(23)과, 상기 태양광가열판(40)의 하측으로 고정로드(24)에 조립되는 흰색의 열반사대(35) 구비로 축산단지(43) 실내에 서냉이나 보온되도록 제공되는 실내 정화용 태양광가열장치가 구비된 축사용 시설물., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

591/1150 Row 591: application_number: 1020190033245, combined_string: invention_title: 가축첨가사료제조법 abstract: 본 발명은 해조류와 파인애플을 주재로 하고, 고온 유산균발효 함이 특징인 가축먹이 첨가사료 및 그 제조방법을 제공하는 것으로서, 소, 닭, 돼지를 포함하는 가축 특히 젖소의 번식기능을 강화하고, 건강지수(mun)를 개선하고, 산유량을 증가하고, 젖에 포함되는 체세포수를 감소시키고, 수태율을 증진시키고, 공태기간을 감소시킴은 물론, 수산업반전에 기여하고, 환경오염을 방지하는 등의 효과를 수반하는 것이다. claims: 가축먹이 첨가사료에 있어서,파쇄 미역, 다시마, 김, 파래 중에서 선택한 해조류 40~90중량부(건조상태);잘게 절단한 파인애플 10~60중량부;의 혼합물을 유산 발효하고,가축먹이에 혼합하여 급이하는 가축 먹이 첨가사료.파쇄 미역, 다시마, 김, 파래 중에서 선택한 해조류 40~90중량부(건조상태),잘게 절단한 파인애플 10~60중량부 및 효소생균제로서 유산균제재 03~07중량부를 혼합하는 단계와;상기 혼합재료를 차광비닐백에 기밀포장하는단계와;상기 기밀포장된 재료를 방치하여 고온 유산 발효를 유도하는 단계;로 구성함이 특징인 가축먹이 첨가사료 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

592/1150 Row 592: application_number: 1020190030352, combined_string: invention_title: 축사용 냉온 환풍기 abstract: 본 발명은 공장이나 돈사 또는 계사 등의 실내 온도를 적정 온도로 유지하는 한편 실내 공기를 환기시키는 냉온 환풍기에 관한 기술로서, 실내 공기에 포함된 미세먼지나 가스 등을 여과 및 정화한 다음, 대기중으로 배출함에 따라 친환경적으로 사용이 가능할 뿐만 아니라 쾌적한 실내환경을 조성하므로, 작업 환경이 개선되는 한편 가축의 성장을 촉진하며, 조립 및 작업성이 우수한 축사용 냉온 환풍기에 관한 기술이다.이러한 본 발명의 주요 구성은, 이동이 용이하게 다수개의 캐스터가 설치된 프레임; 상기 프레임의 상부 한쪽에 설치되고, 내부에 압축기와 팽창밸브가 설치된 컨트롤박스; 상기 컨트롤박스의 상부에 설치되는 응축기; 상기 프레임의 상부 한쪽에 배치되는 증발기; 상기 증발기의 한쪽에 부착 설치되며, 실내로 외부공기를 송풍하는 환풍기; 상기 프레임의 상부 한쪽에 배치되고, 오염된 실내 공기를 흡입해 여과 및 정화하여 대기중으로 배출하는 정화챔버; 및 상기 환풍기에서 실내로 송풍되는 외부공기를 가열하는 가열챔버;를 포함하여 구현된다. claims: 이동이 용이하게 다수개의 캐스터(11)가 설치된 프레임(10); 상기 프레임(10)의 상부 한쪽에 설치되고, 내부에 압축기와 팽창밸브가 설치된 컨트롤박스(20); 상기 컨트롤박스(20)의 상부에 설치되는 응축기(30); 상기 프레임(10)의 상부 한쪽에 배치되는 증발기(40); 상기 증발기(40)의 한쪽에 부착 설치되며, 실내로 외부공기를 송풍하는 환풍기(50); 상기 프레임(10)의 상부 한쪽에 배치되고, 오염된 실내 공기를 흡입해 여과 및 정화하여 대기중으로 배출하는 정화챔버(60); 및 상기 환풍기(50)에서 실내로 송풍되는 외부공기를 가열하는 가열챔버(70);를 포함하고,상기 프레임(10)은 사각틀의 형태로 짜여져 구성되며, 하부에 일정한 간격으로 다수개의 캐스터(11)가 부착 설치되고,상기 컨트롤박스(20)는 철판을 절곡하여 사각 형태로 구성되며, 내부 공간에 압축기ㆍ팽창밸브ㆍ냉매탱크 및 각종 제어기가 설치되고, 프레임(10)의 상부 한쪽에 놓여 조립 설치되며,상기 환풍기(50)는 나팔관 형태로 한쪽은 넓고, 이와 반대쪽은 좁게 형성된 가이드밴(53)이 증발기(40)의 한쪽 면에 부착 설치되며, 상기 가이드밴(53)에서 좁게 형성된 방향의 플렌지에 본체(51)가 체결나사로 부착 설치되고, 상기 본체(51)의 내부에 팬이 배치되는 한편 외부에 모터(52)가 설치되며, 상기 본체(51)의 상부에 외부 공기를 실내로 송풍하는 송풍덕트(54)가 연결 설치되고,상기 정화챔버(60)는 직사각 형상의 박스형태로 구성되며, 외부 한쪽 면에 실내에서 오염된 공기를 흡입하는 배기덕트(61)가 연결 설치되는 한편 내측면에 다수개의 노즐(66)이 장착된 분사관(65)이 설치되고, 길이 방향의 한쪽 면에 배기실(62)이 관통하여 구성되며, 상기 배기실(62)의 상부에 배기팬(63)이 설치되는 한편 배기팬(63)의 상부에 여과 및 정화된 실내 공기를 대기중으로 배출하는 배기관(64)이 연결 설치되고,상기 분사관(65)이 배기덕트(61)와 동일 선상에 위치하며, 상기 배기덕트(61)를 통해 흡입되는 오염된 실내 공기에 노즐(66)이 여과수를 미립자로 분사하고,상기 정화챔버(60)는 배기실(62) 사이에 여과필터(67)가 가로막혀 설치되며, 상기 여과필터(67)의 전방에 다수개의 노즐(66)이 장착된 분사관(65)이 부착 설치되고,상기 가열챔버(70)는 증발기(40)의 상부에 놓여 배치되며, 전면부와 후면부에 송풍덕트(54)가 연결 설치되고, 내부 공간에 복수개로 전기 히터(71)가 설치되며, 상기 히터(71)는 지그재그 형상으로 구성되는 한편 일정한 간격으로 다수개의 방열판(72)이 부착 설치된 것을 특징으로 하는 축사용 냉온 환풍기., Ltext: 농업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

593/1150 Row 593: application_number: 1020190027910, combined_string: invention_title: 가축 질병 예측 시스템 abstract: 본 발명의 일 실시예에 따른 가축 질병 예측 시스템은 가축에 부착되며 가축의 생체정보를 감지하고, 가축의 식별정보가 등록된 무선태그; 축사 내의 피더 및 물탱크 주변에 설치되며, 상기 무선태그가 피더 및 물탱크와 일정거리 이내에 있는 경우 사료 및 물을 섭취하는 것으로 인식하고, 사료 및 물섭취 정보와 생체정보를 전송하는 인식장치; 상기 인식장치로부터 가축의 생체정보와 사료섭취 및 물섭취에 대한 정보를 수신하여 가축의 사료섭취 및 물섭취에 대한 행동정보를 판단하며, 데이터베이스에 저장된 데이터와 비교하여 가축의 이상 여부를 머신러닝 기반으로 분석하여 가축의 질병을 예측하는 분석부; 및 상기 분석결과를 통계화하고, 기 등록된 관리자에게 분석결과를 전송하는 모니터링부를 포함한다. claims: 가축에 부착되며 가축의 생체정보를 감지하고, 가축의 식별정보가 등록된 무선태그;축사 내의 피더 및 물탱크 주변에 설치되며, 상기 무선태그가 피더 및 물탱크와 일정거리 이내에 있는 경우 사료 및 물을 섭취하는 것으로 인식하고, 사료 및 물섭취 정보와 생체정보를 전송하는 인식장치;상기 인식장치로부터 가축의 생체정보와 사료섭취 및 물섭취에 대한 정보를 수신하여 가축의 사료섭취 및 물섭취에 대한 행동정보를 판단하며, 데이터베이스에 저장된 데이터와 비교하여 가축의 이상 여부를 머신러닝 기반으로 분석하여 가축의 질병을 예측하는 분석부; 및상기 분석결과를 통계화하고, 기 등록된 관리자에게 분석결과를 전송하는 모니터링부를 포함하며, 상기 분석부는, 상기 인식장치로부터 센서 데이터 및 인터넷을 통하여 가축관련 클라우드 정보를 수집하되, 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 및 축사 베이스 데이터를 포함하는 정보를 수집하는 데이터 수집부;상기 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 축사 베이스 데이터를 가공하여 통계 분석용 데이터 마트를 생성하는 데이터 가공부;상기 데이터 수집부에서 수집된 데이터 및 데이터 가공부에서 생성된 데이터를 빅데이터 플랫폼으로 저장하는 데이터베이스;상기 사료섭취 및 물섭취에 대한 행동정보를 Random Forest 알고리즘을 기반으로 분석하여 상기 가축의 질병을 예측하는 예측부; 및 상기 예측부에서 예측된 결과와 실제결과값에 대한 재학습을 수행하여 오차율을 최소화하되, 리샘플링 방법에 의해 오차율을 1차적으로 줄이고, 모델 결합법을 이용하여 오차율을 2차적으로 줄여 오차율을 최소화하는 오차율 최소화부;를 포함하고, 상기 모니터링부는, 가축의 일일평균 사료 섭취량, 물섭취량, 및 질병예측 결과를 통계적으로 디스플레이하고, 상기 질병예측 결과에 따른 대응 및 질병 발명 유무에 대한 통계를 디스플레이하고, 상기 가축은 고유번호가 부여된 축사에서 관리되고, 단위 축사에 펜번호가 부여되고, 다수의 펜번호가 그룹핑되어 롯번호가 부여되고, 다수의 롯번호가 그룹핑되어 야드번호가 부여되고, 상기 가축 베이스 데이터는 해당 날짜, 가축의 입출고 날짜, 가축의 출생일, 가축의 고유번호, 가축에게 부착된 태그의 고유번호, 해당 날짜 기준 가축의 무게, 입고일 기준 가축의 무게, 출고일 기준 가축의 무게, 가축의 성별, 해당 날짜에 가축이 속한 축사 번호, 가축의 출신 롯번호 및 가축의 상태에 대한 정보를 포함하고, 상기 사료 베이스 데이터는 해당 날짜, 가축의 고유 번호, 가축에게 부착된 태그의 고유번호, 해당 날짜에 가축이 사료를 먹은 횟수, 해당 날짜에 가축이 사료 섭취를 시작한 시간, 가축이 사료 섭취를 끝낸 시간, 및 가축의 사료 섭취 기간(duration)에 대한 정보를 포함하고, 상기 물 베이스 데이터는 해당 날짜, 가축의 고유번호, 가축에게 부착된 태그의 고유번호, 해당 날짜에 가축이 물을 섭취한 횟수, 해당 날짜에 가축이 물 섭취를 시작한 시간, 해당 날짜에 가축이 물 섭취를 끝낸 시간, 및 가축의 물 섭취 기간(duration)에 대한 정보를 포함하고, 상기 축사 베이스 데이터는 해당 날짜, 가축의 고유번호, 가축에게 부착된 태그의 고유번호, 가축의 속한 펜의 온도, 가축이 속한 펜의 습도, 가축이 해당 날짜에 소속된 펜의 번호, 가축의 상태에 대한 정보를 포함하고, 상기 데이터 가공부는 상기 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 및 축사 베이스 데이터를 가공하여 제1 내지 제9 데이터 마트를 생성하고, 상기 제1 데이터 마트는 가축 식별번호, 펜번호, 날짜, 위험소의 비율 데이터를 포함하고, 상기 제2 데이터 마트는 가축 식별번호, 펜번호, 활동적인 가축의 수, 위험 가축의 수, 위험 가축의 비율 데이터를 포함하고, 상기 제3 데이터 마트는 가축 식별번호, 롯번호, 가축 상태, 사료섭취 횟수, 물섭취 횟수 데이터를 포함하고, 상기 제4 데이터 마트는 가축 식별번호, 펜번호, 가축 상태, 사료섭취 횟수, 물섭취 횟수 데이터를 포함하고, 상기 제5 데이터 마트는 가축 식별번호, 날짜, 사료섭취 횟수, 물섭취 횟수 데이터를 포함하고, 상기 제6 데이터 마트는 가축 식별번호, 야드번호, 가축상태, 사료섭취 횟수, 물섭취 횟수 데이터를 포함하고, 상기 제7 데이터 마트는 가축 식별번호, 건강상태 하위 10%·노멀상태·상위 10% 가축에 대한 데이터를 포함하고, 상기 제8 데이터 마트는 가축 식별번호, 롯번호, 펜번호, 날짜, 사육일수, 가축의 무게, 가축상태에 대한 정보를 포함하고, 상기 제9 데이터 마트는 가축 식별번호, 입고일, 날짜, 사육일수, 가축상태 사료섭취량 합계, 물섭취량 합계, 펜의 평균 사료섭취량, 야드의 평균 사료섭취량, 롯의 평균 사료섭취량, 롯의 평균 물섭취량 데이터를 포함하고, 상기 모니터링부는 상기 제1 데이터 마트 내지 제9 데이터 마트를 이용하여, 각각의 펜, 롯, 야드에 분포되어 있는 가축의 분포를 디스플레이하고, 이상징후 또는 질병 징후가 있는 객체를 선택하여 펜, 롯, 야드의 평균과 비교하여 표시하고, 과거 이력 데이터를 추적하여 이상 가축의 행동 패턴을 추출하고, 사육일수에 마리당 평균 비용을 곱한 값에서 개별 가축의 무게와 단위 무게당 평균 이익을 곱한 값을 차감하여 최적 사육일수를 계산하여 표시하는 것을 특징으로 하는 가축 질병 예측 시스템. 가축에 부착되며 가축의 생체정보를 감지하고, 가축의 식별정보가 등록된 무선태그;축사 내의 피더 및 물탱크 주변에 설치되며, 상기 무선태그가 피더 및 물탱크와 일정거리 이내에 있는 경우 사료 및 물을 섭취하는 것으로 인식하고, 사료 및 물섭취 정보와 생체정보를 전송하는 인식장치;상기 인식장치로부터 가축 식별정보 및 인식장치 식별정보를 수신하고, 상기 인식장치 식별정보를 근거로 가축의 사료섭취 및 물섭취에 대한 행동정보를 판단하며, 전송하는 중계장치; 상기 중계장치로부터 가축의 생체정보와 사료섭취 및 물섭취에 대한 정보를 수신하여 가축의 사료섭취 및 물섭취에 대한 행동정보를 판단하며, 데이터베이스에 저장된 데이터와 비교하여 가축의 이상 여부를 머신러닝 기반으로 분석하여 가축의 질병을 예측하는 분석부; 및상기 분석결과를 통계화하고, 기 등록된 관리자에게 분석결과를 전송하는 모니터링부를 포함하며, 상기 분석부는, 상기 인식장치로부터 센서 데이터 및 인터넷을 통하여 가축관련 클라우드 정보를 수집하되, 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 및 축사 베이스 데이터를 포함하는 정보를 수집하는 데이터 수집부;상기 가축 베이스 데이터, 사료 베이스 데이터, 물 베이스 데이터, 및 축사 베이스 데이터를 가공하여 통계 분석용 데이터 마트를 생성하는 데이터 가공부;상기 데이터 수집부에서 수집된 데이터 및 데이터 가공부에서 생성된 데이터를 빅데이터 플랫폼으로 저장하는 데이터베이스;상기 사료섭취 및 물섭취에 대한 행동정보를 Random Forest 알고리즘을 기반으로 분석하여 상기 가축의 질병을 예측하는 예측부; 및 상기 예측부에서 예측된 결과와 실제결과값에 대한 재학습을 수행하여 오차율을 최소화하되, 리샘플링 방법에 의해 오차율을 1차적으로 줄이고, 모델 결합법을 이용하여 오차율을 2차적으로 줄여 오차율을 최소화하는 오차율 최소화부;를 포함하고, 상기 중계장치는, 상기 축사에 위치하는 가축의 식별정보, 평균 사료 섭취량, 부모 이력, 백신 접종 정보, 출생지 및 도축지에 관한 이력 정보 및 가축의 행동정보를 판단할 수 있는 애플리케이션이 저장되는 저장부;상기 인식장치로부터 가축 식별정보 및 인식장치 식별정보가 수신된 경우, 상기 인식장치 식별정보를 근거로 상기 가축 식별정보에 대응하는 가축의 사료 섭취 및 물 섭취에 대한 행동정보를 판단하는 판단부; 상기 애플리케이션을 구동시켜 상기 판단부가 행동정보를 판단하도록 제어하는 제어부; 및상기 가축 식별정보, 축사 식별정보 및 사료섭취 및 물섭취에 대한 행동정보를 포함하는 센싱정보를 디지털 신호로 변환하여 상기 분석부로 전송하는 무선 통신부;를 포함하고, 상기 가축은 고유번호가 부여된 축사에서 관리되고, 단위 축사에 펜번호가 부여되고, 다수의 펜번호가 그룹핑되어 롯번호가 부여되고, 다수의 롯번호가 그룹핑되어 야드번호가 부여되고, 상기 가축 베이스 데이터는 해당 날짜, 가축의 입출고 날짜, 가축의 출생일, Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

594/1150 Row 594: application_number: 1020190024584, combined_string: invention_title: 축사용 악취 및 분진 제거시스템 abstract: 본 발명은 축사용 악취 및 분진 제거시스템에 관한 것이다.더욱 상세하게는, 프레임부; 상기 프레임부의 상부 일 측면에 형성되어 축사 내에서 배출되는 악취 및 분진이 유입되는 유입구; 상기 프레임부의 내부에 구비되며 하나 또는 복수의 분사노즐을 통해 미생물 배양액 및 물 중 어느 하나 또는 복수를 포함하는 액체를 분사하도록 구성되는 하나 또는 복수의 세정부; 상기 프레임부의 내부에 구비되는 하나 또는 복수의 필터부; 및 상기 프레임부의 하부 타 측면에 형성되어 상기 세정부 및 필터부를 통해 이동된 악취 및 분진이 배출되는 배출구를 포함하는 것을 특징으로 한다. 본 발명에 의하면, 축사에서 발생되는 악취 및 분진이 세정부와 필터부를 거쳐서 배출되도록 구성됨으로써, 축사에서 발생되는 악취 및 분진을 처리하기 위한 비용 및 노동력을 절감할 수 있도록 하는 효과가 있다. claims: 상부 일 측면에 형성되어 축사(800) 내에서 배출되는 악취 및 분진이 유입되는 유입구(200) 및 하부 타 측면에 형성되는 배출구(500)를 포함하는 프레임부(100);상기 프레임부(100)의 내부에 구비되며 하나 또는 복수의 분사노즐(310)을 통해 미생물 배양액 및 물 중 어느 하나 또는 복수를 포함하는 액체를 분사하도록 구성되는 하나 또는 복수의 세정부(300); 및상기 프레임부(100)의 내부에 구비되는 하나 또는 복수의 필터부(400);가 포함되고,상기 분사노즐(310)을 통해 분사되는 미생물 배양액은,바실러스(Bacilus)균 배양액, 락토바실러스(Lactobacillus)균 배양액, 엔테로코커스 훼시움(Enterococcus faecium)균 배양액, 스트렙토코커스(Streptococcus)균 배양액, 효모(Saccharomyces)균 배양액 및 하이포마이크로비윰 다니트리피칸스(Hyphomicrobium denitrificans)균 배양액 중 어느 하나 또는 복수가 포함되며,상기 필터부(400)에는,일 측 방향으로 연장 형성되며 나란히 배열되는 복수의 제1상부연장대(411), 상기 제1상부연장대(411)와 대응되는 형상으로 형성되어 상기 제1상부연장대(411)의 사이에 배치되되 하부 방향으로 이격된 위치에 배치되는 복수의 제1하부연장대(412), 상기 복수의 제1상부연장대(411)와 제1하부연장대(412)를 연결하는 복수의 제1연결대(413)를 포함하는 제1필터구조체(410); 및일 측 방향으로 연장 형성되며 나란히 배열되는 복수의 제2상부연장대(421), 상기 제2상부연장대(421)와 대응되는 형상으로 형성되어 상기 제2상부연장대(421)의 사이에 배치되되 하부 방향으로 이격된 위치에 배치되는 복수의 제2하부연장대(422), 상기 복수의 제2상부연장대(421)와 제2하부연장대(422)를 연결하는 복수의 제2연결대(423)를 포함하는 제2필터구조체(420);가 포함되고,상기 제1필터구조체(410) 및 제2필터구조체(420)는 상하 방향으로 적층되어 연결되도록 구성되며,상기 필터부(400)는,상기 제1필터구조체(410) 및 제2필터구조체(420)가 적층되어 연결되는 경우, 상기 제1필터구조체(410)의 복수의 제1하부연장대(412)와 상기 제2필터구조체(420)의 복수의 제2상부연장대(421)가 인접한 위치에서 마주하고 상기 복수의 제1하부연장대(412)의 사이에 위치되는 제1상부연장대(411)와 상기 복수의 제2상부연장대(421)의 사이에 위치되는 제2하부연장대(422)가 이격된 위치에서 마주하면서 상기 제1필터구조체(410) 및 제2필터구조체(420)의 사이에 생장공간(430)이 형성되고,상기 제1상부연장대(411)에 대응되는 방향으로 형성되어 상기 필터부(400)의 일 측 및 타 측에 각각 배치되는 이송수단(610), 상기 이송수단(610)에 연결되어 상기 이송수단(610)을 구동하는 구동모터(620) 및 상기 이송수단(610)에 연결되어 상기 구동모터(620)의 동작에 따라 이동되면서 상기 필터부(400)를 세척하는 브러쉬(630)가 포함되는 세척부(600)가 더 포함되며,상기 프레임부(100)의 하부에는 상기 세정부(300)의 분사노즐에서 분사된 액체 및 상기 액체에 의해 세정된 분진 등의 이물질이 배출되도록 하는 처리조(110)가 구비되고,상기 처리조(110)는 하부가 경사진 형태로 형성되어 외부로의 배출이 용이하도록 구성되는 것을 특징으로 하는 축사용 악취 및 분진 제거시스템.축사(800)의 상부 측면을 통해 배출되는 악취 및 분진이 유입되는 유입구(200), 상기 유입구(200)를 통해 유입된 악취 및 분진을 하부로 이동시키는 유입팬(210), 상기 유입팬(210)을 통해 이동되는 악취 및 분진을 하부로 가이드하는 격판(130) 및 상기 격판(130)을 중심으로 상기 유입구(200)와 대칭되는 위치에 구비되는 배출구(500)를 포함하여 U자 형상의 유로를 형성하는 프레임부(100);상기 프레임부(100)의 내부에 구비되며 하나 또는 복수의 분사노즐(310)을 포함하여, 상부로 이동되는 악취 및 분진에 미생물 배양액 및 물 중 어느 하나 또는 복수를 포함하는 액체를 분사하도록 구성되는 하나 또는 복수의 세정부(300); 및상기 프레임부(100)의 내부에 구비되며 상부로 이동되는 악취 및 분진이 필터링되도록 하는 하나 또는 복수의 필터부(400);가 포함되고,상기 분사노즐(310)을 통해 분사되는 미생물 배양액은,바실러스(Bacilus)균 배양액, 락토바실러스(Lactobacillus)균 배양액, 엔테로코커스 훼시움(Enterococcus faecium)균 배양액, 스트렙토코커스(Streptococcus)균 배양액, 효모(Saccharomyces)균 배양액 및 하이포마이크로비윰 다니트리피칸스(Hyphomicrobium denitrificans)균 배양액 중 어느 하나 또는 복수가 포함되며,상기 필터부(400)에는,일 측 방향으로 연장 형성되며 나란히 배열되는 복수의 제1상부연장대(411), 상기 제1상부연장대(411)와 대응되는 형상으로 형성되어 상기 제1상부연장대(411)의 사이에 배치되되 하부 방향으로 이격된 위치에 배치되는 복수의 제1하부연장대(412), 상기 복수의 제1상부연장대(411)와 제1하부연장대(412)를 연결하는 복수의 제1연결대(413)를 포함하는 제1필터구조체(410); 및일 측 방향으로 연장 형성되며 나란히 배열되는 복수의 제2상부연장대(421), 상기 제2상부연장대(421)와 대응되는 형상으로 형성되어 상기 제2상부연장대(421)의 사이에 배치되되 하부 방향으로 이격된 위치에 배치되는 복수의 제2하부연장대(422), 상기 복수의 제2상부연장대(421)와 제2하부연장대(422)를 연결하는 복수의 제2연결대(423)를 포함하는 제2필터구조체(420);가 포함되고,상기 제1필터구조체(410) 및 제2필터구조체(420)는 상하 방향으로 적층되어 연결되도록 구성되며,상기 필터부(400)는,상기 제1필터구조체(410) 및 제2필터구조체(420)가 적층되어 연결되는 경우, 상기 제1필터구조체(410)의 복수의 제1하부연장대(412)와 상기 제2필터구조체(420)의 복수의 제2상부연장대(421)가 인접한 위치에서 마주하고 상기 복수의 제1하부연장대(412)의 사이에 위치되는 제1상부연장대(411)와 상기 복수의 제2상부연장대(421)의 사이에 위치되는 제2하부연장대(422)가 이격된 위치에서 마주하면서 상기 제1필터구조체(410) 및 제2필터구조체(420)의 사이에 생장공간(430)이 형성되고,상기 제1상부연장대(411)에 대응되는 방향으로 형성되어 상기 필터부(400)의 일 측 및 타 측에 각각 배치되는 이송수단(610), 상기 이송수단(610)에 연결되어 상기 이송수단(610)을 구동하는 구동모터(620) 및 상기 이송수단(610)에 연결되어 상기 구동모터(620)의 동작에 따라 이동되면서 상기 필터부(400)를 세척하는 브러쉬(630)가 포함되는 세척부(600)가 더 포함되며,상기 프레임부(100)의 하부에는 상기 세정부(300)의 분사노즐에서 분사된 액체 및 상기 액체에 의해 세정된 분진 등의 이물질이 배출되도록 하는 처리조(110)가 구비되고,상기 처리조(110)는 하부가 경사진 형태로 형성되어 외부로의 배출이 용이하도록 구성되는 것을 특징으로 하는 축사용 악취 및 분진 제거시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

595/1150 Row 595: application_number: 1020190017161, combined_string: invention_title: 살균 및 항온 겸용 축사용 공기 공급시스템 abstract: 본 발명은 지열과 200nm~280nm 파장을 가지는 UV-C LED를 이용한 살균 및 항온 겸용 축사용 공기 공급시스템에 관한 것으로서, 더욱 상세하게는 지중의 온도인 지열을 이용하여 축사로 공급되는 온도를 유지하고, 또, UV-C 자외선을 이용하여 유입되는 공기중의 병원균, 곰팡이 등을 살균하여 청정한 공기를 공급하는 살균 및 항온 겸용 축사용 공기 공급시스템에 관한 것이다.이러한 기술적 과제를 달성하기 위한 본 발명은, UV LED 자외선 및 지열을 이용하는 살균 및 항온 겸용 축사용 공기 공급시스템에 있어서, 축사 외부의 공기를 축사 내부로 유입시키기 위한 공기유입부(100); 축사 내부로 살균 및 항온이 유지된 공기를 축사 내부로 공급하는 공기유출부(200); 상기 공기유입(100)부로부터 유입된 공기의 온도를 지열을 이용하여 조절하는 열교환부(300); 상기 공기유입부(100)로부터 유입된 공기를 200nm~280nm 파장을 가지는 UV-C LED를 통해 살균 하는 살균부(400); 상기 200nm~280nm 파장을 가지는 UV-C LED의 전원을 제어하는 제어부(500); 를 포함하는 것을 특징으로 한다.또한 바람직하게, 상기 공기유출부(200)는 유출공기의 양을 조절하기 위하여 배기용 팬 장치를 더 포함하는 것을 특징으로 한다.또한 바람직하게, 상기 제어부(500)은, 축사 내부로 유출공기의 온도를 적정하게 유지하기 위하여 축사 내부 공기를 상기 공기유입부(100)로 보내는 재순환하는 재순환부(600)를 더 포함하는 것을 특징으로 한다.` claims: UV LED 자외선 및 지열을 이용하는 살균 및 항온 겸용 축사용 공기 공급시스템에 있어서,축사 외부의 공기를 축사 내부로 유입시키기 위한 공기유입부(100);축사 내부로 살균 및 항온이 유지된 공기를 축사 내부로 공급하는 공기유출부(200);상기 공기유입(100)부로부터 유입된 공기의 온도를 지열을 이용하여 조절하는 열교환부(300);상기 공기유입부(100)로부터 유입된 공기를 200nm~280nm 파장을 가지는 UV-C LED를 통해 살균 하는 살균부(400);상기 200nm~280nm 파장을 가지는 UV-C LED의 전원을 제어하는 제어부(500); 를 포함하는 것을 특징으로 하는 살균 및 항온 겸용 축사용 공기 공급시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

596/1150 Row 596: application_number: 2020190000610, combined_string: invention_title: 축사용 도어 잠금장치 abstract: 축사용 도어 잠금장치에 관한 것으로, 걸림부재의 록킹 및 이탈이 가능하도록 상면이 개방되게 형성되며, 축사의 기둥에 설치되는 고정부재; 축사의 도어프레임에 설치되도록 형성되는 제1 고정플레이트와, 상기 제1 고정플레이트로부터 소정의 간격으로 이격되게 형성되는 제2 고정플레이트와, 상기 제2 고정플레이트로부터 소정의 간격으로 이격되는 제3 고정플레이트가 일체로 형성된 장착부재; 상기 고정부재에 끼워져 록킹되도록 상기 장착부재에 회전 가능하게 설치되는 걸림부재; 상기 걸림부재가 상기 고정부재에 록킹된 상태를 안정적으로 유지시키도록 상기 장착부재에 회전 가능하게 설치되는 록킹부재;를 마련하여 도어프레임에 장착부재를 끼워 간편하게 설치할 수 있고, 걸림부재를 록킹부재로 고정시킴에 따라 2중 잠금 상태로 록킹시킬 수 있으며, 도어프레임의 내측 및 외측에서 자유로이 개폐시킬 수 있고, 소 등의 가축이 도어프레임에 접촉하더라도 록킹 상태를 안정적으로 유지할 수 있다는 효과가 얻어진다. claims: 걸림부재(40)의 록킹 및 이탈이 가능하도록 상면이 개방되게 형성되며, 축사의 기둥에 설치되는 고정부재(10);축사의 도어프레임(1)에 설치되도록 형성되는 제1 고정플레이트(21)와, 상기 제1 고정플레이트(21)로부터 소정의 간격으로 이격되게 형성되는 제2 고정플레이트(22)와, 상기 제2 고정플레이트(22)로부터 소정의 간격으로 이격되는 제3 고정플레이트(23)가 일체로 형성된 장착부재(20);상기 고정부재(10)에 끼워져 록킹되도록 상기 장착부재(20)에 회전 가능하게 설치되는 걸림부재(40); 및상기 걸림부재(40)가 상기 고정부재(10)에 록킹된 상태를 안정적으로 유지시키도록 상기 장착부재(20)에 회전 가능하게 설치되는 록킹부재(50);를 포함하되,상기 장착부재(20)는 상기 도어프레임(1)에 일정 높이 간격으로 고정된 제1 프레임(2)과 제2 프레임(3)의 일측 외면에 밀착되도록 소정 높이로 형성되는 제1 고정플레이트(11);상기 제1 고정플레이트(11)로부터 연장 형성되는 제1 연장부(22a)와, 상기 제1 연장부(22a)로부터 상기 제1 프레임(2)의 타측 외면에 밀착되도록 소정 높이로 형성되는 제2 고정플레이트(22);상기 제2 고정플레이트(22)로부터 연장 형성되는 제2 연장부(23a)와, 상기 제2 연장부(23a)의 선단에서 소정 높이로 형성되는 제3 고정플레이트(23);를 포함하며,상기 제1 고정플레이트(21), 상기 제2 고정플레이트(22) 및 상기 제3 고정플레이트(23)가 일체로 형성되고,상기 장착부재(20)가 상기 제2 프레임(3)에 안정되게 고정되도록 소정의 길이로 형성되는 수평플레이트(32)와, 상기 수평플레이트(32)의 선단에서 소정의 높이로 형성되는 수직플레이트(33)가 일체로 형성된 하부고정플레이트(31);를 포함하는 것을 특징으로 하는 축사용 도어 잠금장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

597/1150 Row 597: application_number: 1020190015335, combined_string: invention_title: 살균 및 방충 기능이 구비된 축사용 에어커튼 abstract: 본 발명은 축사용 에어커튼에 관한 것으로, 보다 상세하게는, 축사의 개방된 부위에 설치되어 축사 내부와 외부 사이에 에어 커튼을 형성함에 있어서, 살균 성분이 함유된 운무를 분사하면서 에어 커튼을 형성하여, 축사 외부로부터 해충이나 유해한 세균이 축사 내부로 침투하는 것을 방지하고, 축사 내부의 공기를 정화시켜 악취를 감소시킬 수 있으며, 축사 내부의 공기를 순환시켜 냉방이나 난방 시 전체적으로 적정한 온도로 유지할 수 있는 살균 및 방충 기능이 구비된 축사용 에어커튼에 관한 것이다.이를 위해 본 발명의 일실시예에 따른 살균 및 방충 기능이 구비된 축사용 에어커튼은, 하부에 송풍구가 구비되고 축사의 출입구 상부에 설치되어 출입구 측으로 에어를 분사함에 따라 에어커튼을 형성하는 에어커튼 본체, 상기 에어커튼 본체 내부에 설치되어 풍력을 발생시킴에 따라 출입구 측으로 에어를 분사하는 풍력 발생부, 상기 에어커튼 본체에 축사 내측 방향으로 구비되어, 축사 내부의 공기가 상기 풍력 발생부에 의해 흡입될 때 축사 내부의 악취를 정화시켜주는 에어 필터 및 상기 에어커튼 본체의 상부에 구비되어, 상기 풍력 발생부에서 발생된 바람에 운무가 혼입되어 송풍되도록 운무를 발생시키는 운무 분사부를 포함한다. claims: 하부에 송풍구(110)가 구비되고 축사(10)의 출입구(11) 상부에 설치되어 출입구(11) 측으로 에어를 분사함에 따라 에어커튼을 형성하는 에어커튼 본체(100);상기 에어커튼 본체(100) 내부에 설치되어 풍력을 발생시킴에 따라 출입구(11) 측으로 에어를 분사하는 풍력 발생부(200);상기 에어커튼 본체(100)에 축사(10) 내측 방향으로 구비되어, 축사(10) 내부의 공기가 상기 풍력 발생부(200)에 의해 흡입될 때 축사(10) 내부의 악취를 정화시켜주는 에어 필터(300); 및 상기 에어커튼 본체(100)의 내부에 구비되어, 상기 풍력 발생부(200)에서 발생된 바람에 운무가 혼입되어 송풍되도록 운무를 발생시키는 운무 분사부(400)를 포함함에 있어서,상기 에어커튼 본체(100)는 에어커튼 본체(100)의 하부에 출입구(11)를 향하도록 구비되어 출입구(11) 측으로 에어를 분사하는 송풍구(110)와, 상기 송풍구(110)에 설치되어 송풍 방향을 조절할 수 있는 송풍방향 조절부재(120)와, 별도의 압력탱크(140)에 연결되어, 축사(10) 내부를 향해 고압의 에어를 송풍하는 고압 송풍부(130) 및 상기 운무 분사부(400)에서 발생된 운무를 송풍구(110) 측이나 고압 송풍부(130) 측으로 선택적으로 유도하는 운무 유도편(150)을 포함하고, 상기 운무 분사부(400)는 에어커튼 본체(100)의 상부에 구비되어 다량의 물이 저장되는 물 저장탱크(410)와, 상기 물 저장탱크(410)의 하부 일측에 구비되어, 물 저장탱크(410)로부터 소량의 물이 공급되면 초음파에 의해 운무를 발생시키는 초음파 진동부(420) 및 상기 초음파 진동부(420)의 일측에 연결되어, 초음파 진동부(420)에 의해 발생된 운무를 송풍구 측으로 분사하는 운무 분사 노즐(430)을 포함하되,상기 물 저장탱크(410)는 물 저장탱크(410)에 수용되었던 물이 초음파 진동부(420) 측으로 수압에 의해 일정량씩만 이송되도록 유지하며 물을 이송시키는 물 이송 노즐(411)이 더 구비되며, 상기 물 이송 노즐(411)에는 물 저장탱크(410)에 수용된 물이 이송될 때 소량씩 이송되면서, 물에 함유된 이물질을 걸러주는 다공성 세라믹 볼(412)이 더 구비되는 것을 특징으로 하는 살균 및 방충 기능이 구비된 축사용 에어커튼., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

598/1150 Row 598: application_number: 1020210131193, combined_string: invention_title: 초식동물용 보조사료 조성물 abstract: 본 발명은 초식동물용 보조사료 조성물에 관한 것으로, 증삼농축액 분말, 홍삼박, 한약재박, 및 미강을 소정의 함량으로 포함하며, 위 보조사료 조성물을 급여시 사육 동물에서 간 기능 강화 효과, 피로회복 및 항산화 효과, 골격근 손상 방어 효과, 소화 기능 개선 효과가 나타나므로 본 발명의 보조사료 조성물을 동물의 건강 개선용으로 사용할 수 있다. claims: 0.1 내지 3 중량부의 증삼농축액 분말, 55 내지 70 중량부의 홍삼박, 15 내지 25 중량부의 한약재박, 및 9 내지 15 중량부의 미강을 포함하는 경주마용 보조사료 조성물로서, 상기 증삼농축액은 인삼의 증삼시에 생성되는 부산물인 증삼액을 농축 및 건조하여 제조되고, 상기 증삼농축액 분말은 상기 증삼농축액 100 중량부에 말토덱스트린을 10 내지 60 중량부로 포함시켜 분말화한 것이고,상기 한약재박은, 한약재박 100 중량부에 대하여, 1~30 중량부의 백작약, 1~30 중량부의 당귀, 1~30 중량부의 계지, 1~30 중량부의 백출, 1~30 중량부의 백출, 1~30 중량부의 숙지황, 1~30 중량부의 황기, 0.01~10 중량부의 천궁 및 0.01~10 중량부의 진피를 포함하며,상기 조성물은 경주마의 근육 피로회복을 위한 것인, 경주마용 보조사료 조성물.청구항 1의 경주마용 보조사료 조성물을 포함하는,경주마의 근육 피로회복을 위한 경주마용 사료., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

599/1150 Row 599: application_number: 1020210109391, combined_string: invention_title: 가축분뇨 발효촉진 분말살포제 제조방법 abstract: 본 발명의 '가축분뇨 발효촉진 분말살포제 제조방법'은 축산분뇨에서 분뇨냄새를 소멸시키는 방법은 발효뿐이므로 사육장 바닥에 널려져 있는 가축분뇨를 수거하여 발효시키는 방법이 아니라 아예 사육장 바닥에서 가축이 밟으며 스스로 발효시켜 수거하기만 하면 그대로 발효퇴비로 사용할 수 있게 하는 발효촉진 분말살포제로 제조하는 제조방법에 관한 축산분야의 발명에 속한다,일반적으로 축산분뇨라 하면 냄새, 즉 악취로 취급하는데 축산분뇨는 천연비료로 자연농법에 속하는 퇴비로 이용되므로 버리는 것이 아니라 유용하게 사용되는 것인데 축산농가 주변 주민들에 의해 쫓겨날 처지이기에 이를 대비하여 축산분뇨를 퇴비비료로 만들 발효촉진용 분말살포제로 위기를 벗어나게 하려는 발명이다,본 발명에서 재활용 축산분뇨비료로 제공되므로 인하여 축산농가가 안심하게 사육할 수 있도록 하므로 자연농법용 축산분뇨 퇴비로 재활용비료 제조와 축산농가의 고민을 해결하면서 유기질비료도 얻게 되어 축산농민은 물론 일반경종 영농농민들과 주변 주민들에게도 희소식이 되는 효과가 기대된다,[색인어]북산분뇨, 분말살포제, 유산미량광물, 죽순추출용액,해조추출용액, 패분(貝粉), 입자크기(mesh), claims: 제올라이트(10)와 미량광물질(20)과 죽순(30)과 해조류(40)와 패분(50)을 재료수집(제1단계)하여 재료가공(제2단계)에서 상기 제올라이트는 열 건조시켜 제올라이트분말로 분쇄하고, 상기 패분도 패분분말로 분쇄하고, 상기 미량광물질은 모두 용해시켜 수차례 여과 후 숙성미량광물질용액으로 숙성시키고, 상기 죽순과 상기 해조류는 각각 죽순추출용액과 해조추출용액으로 가공하고,상기 제올라이트분말과 상기 숙성미량광물질용액과 상기 죽순추출용액과 상기 해조추출용액과 상기 패분분말을 지정배합비로 재료칭량(제3단계)하고, 상기 재로칭량 후 혼합할 때 상기 제올라이트분말과 상기 패분분말에 상기 용액들이 골고루 흡수되도록 재료배합(제4단계)하고, 상기 재료배합이 종료되면 지정된 용량으로 재료포장(제5단계)하여 분말살포제(60)로 제작하는 것이 특징인 가축분뇨 발효촉진 분말살포제 제조방법,, Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

600/1150 Row 600: application_number: 1020210051014, combined_string: invention_title: 볏짚엔실리지와 이의 제조방법 abstract: 본 발명의 '볏짚엔실리지 제조방법'은 그동안 한우를 키우는 농가에서 집 근처에 볏짚을 쌓고 비닐로 덮고 질소가스를 주입한 후 자체발열로 발효되면서 질소 성분이 볏짚에 스며들도록 한 것과 최근의 곤포볏짚은 단순히 곰팡이를 억제시키는 것인데 내면에 공간이 형성된 볏짚과 보릿짚과 밀짚 등은 옥수수겉대와 달리 속이 비어 있기 때문에 발효할 때 호기성발효로 살이 썩는 것처럼 고약한 냄새로 인해 주민이 사는 동네에서는 도저히 발효시킬 수 없는 발효조사료 재료들을 속이 꽉 찬 옥수수겉대처럼 발효시키려는 엔실리지 제조공법에 속하는 발명이다,이미 곤포포장을 발효시키는 방법은 널리 알여져 있으나 속이 빈 볏짚을 옥수수겉대처럼 발효시키려면 속을 으깨도 보릿짚보다는 발효시킬 때 냄새는 덜 나지만 역시 발효시킨 엔실리지로는 적절하지 못하기 때문에 보조 재료를 첨가하여 악취 없는 옥수수겉대와 같은 발효엔실리지로 제조하는 발효공법에 관한 것이다, 이와 같이 볏짚엔실리지로 제조할 수 있다면 그동안 일반농가에서 기피하는 옥수수재배 대신에 논에서 곤포 등으로 깔 짚으로 전용하던 볏짚을 고품질의 볏짚 엔실리지로 가공할 수 있게 되어 젖소 및 비육우사육농가의 사료 확보에 어려움을 덜 수 있게 하면서 농가수익도 높이는 효과가 기대되는 발명이다,[색인어]볏짚엔실리지, 보릿짚엔실리지, 옥수수겉대엔실리지, 유산용액(乳酸溶液), 탈지미강(脫脂米糠), 강피류(糠皮類), 반추가축(反芻家畜), 곤포(梱包), 톤포(),헤이레이지(haylage), claims: 벼를 수확한 일반볏짚(60) 또는 보리를 수확한 보릿짚을 볏짚수거차(14)로 수거하여 볏짚절단기(12)로 세절시킨 절단볏짚(50) 또는 절단보릿짚(52)을 지정비율로 혼합 또는 단독으로 배합장치(40)에 담아 일정량의 밀기울(30), 또는 보릿겨(32), 또는 탈지미강(34)을 혼합 또는 단독으로 첨가하고 수분함량에 따라 유산용액(20)을 추가 첨가하여 상기 배합장치로 일정시간 배합하는 도중 잠시 정지하여 일정량의 제올라이트(24)와 요소사료(22)를 추가하고 배합이 종료되면 1톤 용적량의 톤포(10)에 담아 톤포볏짚(70)으로 소분하고 발효장소에 상기 톤포볏짚을 다수개로 적재한 후 일정기간 발효시켜 발효볏짚(62)으로 제조되는 것이 특징인 볏짚엔실리지 제조방법, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

601/1150 Row 601: application_number: 1020210044596, combined_string: invention_title: 한우 경매가 예측 서버, 및 이를 이용한 한우 경매가 예측 방법 abstract: 본 발명은 한우 경매가 예측 서버, 및 이를 이용한 한우 경매가 예측 방법에 관한 것으로, 특히 사용자 단말로부터 기준 마커가 부착된 한우 개체 이미지를 수신하여 기준 마커를 인식하고 기준 마커 내의 4개 영역의 색상을 추출하여 원본 마커의 색상과 비교하여 색상 값 오차를 획득하고, 이 색상 값 오차를 이용하여 한우 개체 이미지의 색상을 변환하고, 색상 변환된 한우 개체 이미지로부터 한우 인식 이미지를 생성한 후 한우 선형 심사기준에 의거하여 선형 심사점수를 계산하고, 선형 심사점수 계산시 사용한 변수인 체고 및 체장을 기초로 체중을 계산하며, 이 선형 심사점수 및 체중과 과거 한우 경매가 판정 정보간 유사도를 계산하여 한우 경매가를 산출한 후 사용자 단말에 제공해주는 한우 경매가 예측 서버, 및 이를 이용한 한우 경매가 예측 방법에 관한 것이다. claims: 크기 및 색상 정보가 공개되어 있고 내부에 서로 다른 색상을 갖는 4개의 사각형 영역이 배치되어있는 사각형의 기준 마커를 측면에 부착한 한우 개체를 촬영하여 얻어진 한우 개체 이미지를 사용자 단말로부터 수신하도록 구성된 한우 개체 이미지 수신부;상기 기준 마커를 인식하여 상기 기준 마커 내의 4개의 사각형 영역의 색상을 추출하여서 저장하도록 구성된 기준 마커 인식부;추출된 상기 4개의 사각형 영역의 색상과 원본 마커의 색상을 비교하여 색상 값 오차를 획득하고, 이 색상 값 오차를 이용하여 상기 한우 개체 이미지의 색상을 변환하도록 구성된 이미지 색상 변환부;색상 변환된 상기 한우 개체 이미지로부터 한우 인식 이미지를 생성하도록 구성된 한우 개체 인식부;한우 선형 심사기준을 기초로 상기 한우 인식 이미지에 대한 선형 심사점수를 계산하고, 상기 선형 심사점수 계산시 사용한 변수인 체고 및 체장을 기초로 체중을 계산하며, 상기 사용자 단말의 선형 심사점수 및 체중 계산 결과 확인 후 저장하도록 구성된 한우 외모 정보 인식부; 및상기 선형 심사점수 및 체중과 과거 한우 경매가 판정 정보 간 유사도를 계산하여 한우 경매가를 산출한 후 상기 사용자 단말에 상기 한우 경매가 및 체중 정보를 제공하도록 구성된 경매가 산출부;를 포함하고,상기 한우 개체 인식부는표준 한우 피모색 범위의 RGB 값을 로딩하여 설정 개수로 구분하고;상기 이미지 색상 변환부에 의해 변환된 한우 개체 이미지에서 표준 한우 피모색 범위의 RGB 값에 속하는 RGB 값을 상기 설정 개수만큼 검출하며;검출된 상기 설정 개수의 RGB 값을 갖는 색상을 각각 상기 변환된 한우 개체 이미지에 오버레이(overlay)하여 상기 설정 개수의 한우 개체 이미지를 생성하며;생성된 상기 설정 개수의 한우 개체 이미지를 부위별로 분할하여 부위별로 상기 설정 개수의 이미지를 생성하고 상기 사용자 단말에 제공하며;상기 사용자 단말이 생성된 상기 부위별 설정 개수의 이미지 중에서 부위별로 하나의 이미지를 선택하면, 선택된 상기 부위별 이미지를 통합하여 A타입의 한우 인식 이미지를 생성하고 상기 사용자 단말에 제공하며; 상기 사용자 단말에 의해 상기 A타입 한우 인식 이미지가 확인되면, 상기 A타입 한우 인식 이미지를 저장하고;상기 사용자 단말에 의해 상기 A타입 한우 인식 이미지가 확인되지 않으면, 한우 모양의 한우 가이드 라인 이미지를 로딩하고, 상기 한우 가이드 라인 이미지를 상기 변환된 한우 개체 이미지의 크기에 맞추어 크기 조절 및 매핑하여 B타입의 한우 인식 이미지를 생성하고 저장하는 한우 경매가 예측 서버.한우 경매가 예측 서버를 이용한 한우 경매가 예측 방법으로서,상기 한우 경매가 예측 서버가, 크기 및 색상 정보가 공개되어 있고 내부에 서로 다른 색상을 갖는 4개의 사각형 영역이 배치되어있는 사각형의 기준 마커를 측면에 부착한 한우 개체를 촬영하여 얻어진 한우 개체 이미지를 사용자 단말로부터 수신하는 한우 개체 이미지 수신 단계;상기 한우 경매가 예측 서버가 상기 기준 마커를 인식하여 상기 기준 마커 내의 4개의 사각형 영역의 색상을 추출하여서 저장하는 기준 마커 인식 단계;상기 한우 경매가 예측 서버가 추출된 상기 4개의 사각형 영역의 색상과 원본 마커의 색상을 비교하여 색상 값 오차를 획득하고, 이 색상 값 오차를 이용하여 상기 한우 개체 이미지의 색상을 변환하는 이미지 색상 변환 단계;상기 한우 경매가 예측 서버가 색상 변환된 상기 한우 개체 이미지로부터 한우 인식 이미지를 생성하는 한우 개체 인식 단계;상기 한우 경매가 예측 서버가 한우 선형 심사기준을 기초로 상기 한우 인식 이미지에 대한 선형 심사점수를 계산하고, 상기 선형 심사점수 계산시 사용한 변수인 체고 및 체장을 기초로 체중을 계산하며, 상기 사용자 단말의 선형 심사점수 및 체중 계산 결과 확인 후 저장하는 한우 외모 정보 인식 단계; 및상기 한우 경매가 예측 서버가 상기 선형 심사점수 및 체중과 과거 한우 경매가 판정 정보 간 유사도를 계산하여 한우 경매가를 산출한 후 상기 사용자 단말에 상기 한우 경매가 및 체중 정보를 제공하는 경매가 산출 단계;를 포함하고, 상기 한우 개체 인식 단계는상기 한우 경매가 예측 서버가 표준 한우 피모색 범위의 RGB 값을 로딩하여 설정 개수로 구분하는 단계;상기 한우 경매가 예측 서버가 상기 이미지 색상 변환 단계에서 변환된 한우 개체 이미지에서 표준 한우 피모색 범위의 RGB 값에 속하는 RGB 값을 상기 설정 개수만큼 검출하는 단계;상기 한우 경매가 예측 서버가 검출된 상기 설정 개수의 RGB 값을 갖는 색상을 각각 상기 변환된 한우 개체 이미지에 오버레이(overlay)하여 상기 설정 개수의 한우 개체 이미지를 생성하는 단계;상기 한우 경매가 예측 서버가 생성된 상기 설정 개수의 한우 개체 이미지를 부위별로 분할하여 부위별로 상기 설정 개수의 이미지를 생성하고 상기 사용자 단말에 제공하는 단계;상기 사용자 단말이 생성된 상기 부위별 설정 개수의 이미지 중에서 부위별로 하나의 이미지를 선택하면, 상기 한우 경매가 예측 서버가 선택된 상기 부위별 이미지를 통합하여 A타입의 한우 인식 이미지를 생성하고 상기 사용자 단말에 제공하는 단계; 및상기 사용자 단말에 의해 상기 A타입 한우 인식 이미지가 확인되면, 상기 한우 경매가 예측 서버가 상기 A타입 한우 인식 이미지를 저장하는 단계;를 포함하며,상기 사용자 단말에 의해 상기 A타입 한우 인식 이미지가 확인되지 않으면,상기 한우 경매가 예측 서버가 한우 모양의 한우 가이드 라인 이미지를 로딩하는 단계; 및상기 한우 경매가 예측 서버가 상기 한우 가이드 라인 이미지를 상기 변환된 한우 개체 이미지의 크기에 맞추어 크기 조절 및 매핑하여 B타입의 한우 인식 이미지를 생성하고 저장하는 단계;를 포함하는 한우 경매가 예측 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

602/1150 Row 602: application_number: 1020210043301, combined_string: invention_title: 오미자 줄기의 추출물을 유효성분으로 하는, 육질 개선을 위한 가축 급이용 조성물 및 그 제조방법 abstract: 본 발명은 오미자 부산물의 추출물을 유효성분으로 하는, 육질개선을 위한 가축 급이용 조성물 및 그 제조방법에 관한 것이다. 본 발명의 가축 급이용 조성물은, 줄기를 포함하는 오미자 부산물의 추출물을 유효성분으로 하며, 가축 사료나 음수에 첨가하거나 따로 급이함으로써 육질 내 단백질, 아미노산 및 불포화 지방산 함량을 높일 수 있다. claims: 오미자 줄기의 추출물을 유효성분으로 하며, 육질 내 불포화 지방산 함량은 높이고 포화지방산 함량은 낮추되, 상기 불포화 지방산은 올레산(Oleic acid)을 포함하는 것을 특징으로 하는, 육질 내 단백질 및 불포화 지방산 함량을 높이기 위한 가축 급이용 조성물. 제1항 내지 제3항 중 어느 한 항의 가축 급이용 조성물을 소에게 1개월 이상 급이하는 것을 포함하는, 육질 내 단백질 및 불포화 지방산 함량을 높이기 위한 소 사육방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

603/1150 Row 603: application_number: 1020210042403, combined_string: invention_title: 자외선살균램프를 이용한 친환경 축사 청소 및 소독 살균 자동화 시스템과 그 방법 abstract: [기술분야/해결과제]본 발명은 친환경 축사 청소 및 소독 살균 자동화 시스템과 그 방법에 관한 것으로, 돈방(20) 사이에 설치된 돈방 칸막이(102)를 상승하여 개방시킨 후 한쪽 돈방(20)으로 돼지를 이동시킨 다음 상기 돈방 칸막이(102)를 하강하여 격리시킨 후, 돼지가 비어있는 돈방(20)의 바닥에 소독살균제를 분사하여 소독한 후 고압수로 세척하고 UV-C 자외선으로 소독 살균함으로써, 병균과 해충이 없고 악취가 없는 위생적 사육관리로 돼지의 생산성을 높이고 작업능률을 높일 수 있으며 쾌적한 사육환경을 조성할 수 있다.[해결수단]본 발명에 의한 친환경 축사 청소 및 소독 살균 자동화 방법은, (a) 돈방(20) 사이의 돈방 칸막이(102)를 상승시키되 상기 돈방 칸막이(102)에 연결된 와이어줄을 리프터장치(160)로 감아서 상기 돈방 칸막이(102)를 상승시켜 돈방(20)을 개방하는 단계; (b) 상기 개방한 돈방(20)의 어느 한쪽으로 돼지가 이동된 후, 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시켜 돼지를 한쪽의 돈방(20)에 격리시키는 단계; (c) 상기 돈방(20)의 상부에서 소독살균 리프터장치(180)가 하강한 후 상기 소독살균 리프터장치(180)의 하단에 설치된 소독살균제 분사기(190)에서 소독살균제가 상기 돼지가 비어있는 돈방(20)에 분사되어 소독하는 단계; (d) 상기 돼지가 비어있는 돈방(20)의 벽면에 설치된 고압수 분사기(170)에서 고압수가 분사되어 바닥을 세척하는 단계; (e) 상기 소독살균 리프터장치(180)의 하단에 설치된 자외선 살균램프(200)에서 상기 돼지가 비어있는 돈방(20)에 UV-C 자외선이 소정시간 조사되어 살균하는 단계; (f) 상기 소독살균 리프터장치(180)가 원위치로 상승한 후 상기 돼지가 비어있는 돈방(20)을 자연 건조하거나 송풍기로 건조하는 단계; 및 (g) 상기 살균 및 건조된 돈방(20)과 상기 돼지가 있는 돈방(20) 사이의 돈방 칸막이(102)를 상기 리프터장치(160)로 상승하여 개방한 후 상기 살균 및 건조된 돈방(20)으로 돼지가 이동된 다음 상기 돈방 칸막이(102)를 하강하여 상기 돈방(20)을 분리시키고, 상기 (c) 내지 (f) 단계를 진행하여 상기 돈방(20)을 청소와 소독 및 살균 건조하는 단계;를 포함한다.[기대효과]본 발명에 따르면, 병균과 해충이 없고 악취가 없는 위생적 사육관리로 돼지의 생산성을 높이고 작업능률을 높일 수 있으며 쾌적한 사육환경을 조성할 수 있다. claims: 친환경 축사 청소 및 소독 살균 자동화 방법에 있어서,(a) 돈방(20) 사이의 돈방 칸막이(102)를 상승시키되 상기 돈방 칸막이(102)에 연결된 와이어줄을 리프터장치(160)로 감아서 상기 돈방 칸막이(102)를 상승시켜 돈방(20)을 개방하는 단계;(b) 상기 개방한 돈방(20)의 어느 한쪽으로 돼지가 이동된 후, 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시켜 돼지를 한쪽의 돈방(20)에 격리시키는 단계;(c) 상기 돈방(20)의 상부에서 소독살균 리프터장치(180)가 하강한 후 상기 소독살균 리프터장치(180)의 하단에 설치된 소독살균제 분사기(190)에서 소독살균제가 상기 돼지가 비어있는 돈방(20)에 분사되어 소독하는 단계;(d) 상기 돼지가 비어있는 돈방(20)의 벽면에 설치된 고압수 분사기(170)에서 고압수가 분사되어 바닥을 세척하는 단계;(e) 상기 소독살균 리프터장치(180)의 하단에 설치된 자외선 살균램프(200)에서 상기 돼지가 비어있는 돈방(20)에 UV-C 자외선이 소정시간 조사되어 살균하는 단계;(f) 상기 소독살균 리프터장치(180)가 원위치로 상승한 후 상기 돼지가 비어있는 돈방(20)을 자연 건조하거나 송풍기로 건조하는 단계; 및(g) 상기 살균 및 건조된 돈방(20)과 상기 돼지가 있는 돈방(20) 사이의 돈방 칸막이(102)를 상기 리프터장치(160)로 상승하여 개방한 후 상기 살균 및 건조된 돈방(20)으로 돼지가 이동된 다음 상기 돈방 칸막이(102)를 하강하여 상기 돈방(20)을 분리시키고, 상기 (c) 내지 (f) 단계를 진행하여 상기 돈방(20)을 청소와 소독 및 살균 건조하는 단계;를 포함하며,상기 소독살균제는, 액상소석회를 사용하며,상기 액상소석회는물(H2O)과 생석회(CaO)가 70∼80중량% : 20∼30중량%의 비율로 혼합된 액상소석회(Ca(OH)2)에 이온화 미네랄 입자 3∼5중량%, 시안산나트륨(NaOCN) 0.5∼1.0중량%, 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 및 입도 100∼200메쉬의 숯 분말 5∼10중량%가 혼합된,친환경 축사 청소 및 소독 살균 자동화 방법.친환경 축사 청소 및 소독 살균 자동화 시스템에 있어서,돈방(20) 사이에 설치된 돈방 칸막이(102)를 상승하여 개방시키고, 상기 돈방 칸막이(102)를 하강하여 상기 돈방(20)을 분리시키는 리프터장치(160);상기 돈방(20)의 벽면에 설치되며, 돼지가 비어있는 돈방(20)에 고압수를 분사하여 바닥을 세척하는 고압수 분사기(170);상기 돈방(20)의 상부에 승하강하도록 설치되며, 상기 돈방(20)의 소정 높이까지 하강하여 소독 및 살균하고 상승하는 소독살균 리프터장치(180);상기 소독살균 리프터장치(180)의 하단 양쪽에 설치되며, 돼지가 비어있는 돈방(20)에 소독살균제를 분사하는 소독살균제 분사기(190);상기 소독살균 리프터장치(180)의 하단에 설치되며, 돼지가 비어있는 돈방(20)에 UV-C 자외선을 소정시간 조사하여 살균하는 자외선 살균램프(200); 및상기 리프터장치(160)를 작동하여 상기 돈방 칸막이(102)를 상승시키고 한쪽 돈방(20)으로 돼지가 이동된 후 상기 돈방 칸막이(102)를 하강하여 상기 돈방(20)을 분리시키고, 상기 소독살균 리프터장치(180)를 작동하여 상기 돈방(20)의 소정 높이까지 하강시키고 상기 소독살균제 분사기(190)를 작동하여 소독살균제를 분사하고, 상기 돼지가 비어있는 돈방(20)에 설치된 고압수 분사기(170)를 작동하여 고압수로 세척하고, 상기 자외선 살균램프(200)를 작동하여 UV-C 자외선으로 소독 살균하는 시스템의 동작을 제어하는 제어부(110);를 포함하는 친환경 축사 청소 및 소독 살균 자동화 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

604/1150 Row 604: application_number: 1020210042406, combined_string: invention_title: 축사 소독용  UV-LED 소독 살균 장치와 그 방법 abstract: [기술분야/해결과제]본 발명은 축사 소독용 UV-LED 소독 살균 장치와 그 방법에 관한 것으로, 돈방 사이의 돈방 칸막이를 상승하여 한쪽 돈방으로 돼지를 이동시킨 후 돈방 칸막이를 하강하여 돼지를 격리시킨 다음, 돼지가 비어있는 돈방의 바닥면에는 소독살균제를 분사하여 소독하고 고압수로 세척한 다음 UV-C 자외선으로 소독 살균하고, 돼지가 있는 돈방에는 가시광선 또는 UV-A 자외선을 조사하여 돼지를 소독 살균하는 축사 소독용 UV-LED 소독 살균 장치와 그 방법에 관한 것이다.[해결수단]본 발명에 의한 축사 소독용 UV-LED 소독 살균 방법은, (a) 돈방 사이의 돈방 칸막이(102)에 와이어줄을 연결하여 리프터장치(160)로 감아서 상기 돈방 칸막이(102)를 상승시켜 돈방을 개방하는 단계; (b) 상기 개방한 돈방의 어느 한쪽으로 돼지가 이동된 후, 상기 돼지를 한쪽의 돈방에 격리시키기 위해 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시키는 단계; (c) 상기 돈방의 상부에서 소독살균 리프터장치(180)가 하강하고, 상기 소독살균 리프터장치(180)의 하단에 설치된 소독살균제 분사기(190)에서 상기 돼지가 비어있는 돈방의 바닥면으로 소독살균제를 분사시켜 소독하는 단계; (d) 상기 돈방의 벽면에 설치된 고압수 분사기(170)에서 상기 돼지가 비어있는 돈방의 바닥면으로 고압수를 분사시켜 바닥면을 세척하는 단계; (e) 상기 소독살균 리프터장치(180)의 하단에 설치된 UV-C 발광소자(200)에서 상기 돼지가 비어있는 돈방의 바닥면에 UV-C 자외선을 조사하여 살균하고, 상기 소독살균 리프터장치(180)의 하단에 설치된 가시광선 발광소자(201)에서 상기 돼지가 있는 돈방에 가시광선을 조사하여 돼지를 살균하는 단계; (f) 상기 소독살균 리프터장치(180)가 원위치로 상승한 후 상기 돼지가 비어있는 돈방을 자연 건조하거나 송풍기로 건조하는 단계; 및 (g) 상기 돈방 사이의 돈방 칸막이(102)를 상기 리프터장치(160)로 상승하여 개방한 후 살균 및 건조된 돈방으로 돼지가 이동된 다음, 상기 돼지를 한쪽의 돈방에 격리시키기 위해 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시키고, 상기 (c) 내지 (f) 단계를 진행하여 돈방을 소독 및 살균하는 단계;를 포함한다.[기대효과]본 발명에 따르면, 병균과 해충이 없고 악취가 없는 위생적 사육관리로 돼지의 생산성을 높이고 작업능률을 높일 수 있으며 쾌적한 사육환경을 조성할 수 있다. claims: 축사 소독용 UV-LED 소독 살균 방법에 있어서,(a) 돈방 사이의 돈방 칸막이(102)에 와이어줄을 연결하여 리프터장치(160)로 감아서 상기 돈방 칸막이(102)를 상승시켜 돈방을 개방하는 단계;(b) 상기 개방한 돈방의 어느 한쪽으로 돼지가 이동된 후, 상기 돼지를 한쪽의 돈방에 격리시키기 위해 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시키는 단계;(c) 상기 돈방의 상부에서 소독살균 리프터장치(180)가 하강하고, 상기 소독살균 리프터장치(180)의 하단에 설치된 소독살균제 분사기(190)에서 상기 돼지가 비어있는 돈방의 바닥면으로 소독살균제를 분사시켜 소독하는 단계;(d) 상기 돈방의 벽면에 설치된 고압수 분사기(170)에서 상기 돼지가 비어있는 돈방의 바닥면으로 고압수를 분사시켜 바닥면을 세척하는 단계;(e) 상기 소독살균 리프터장치(180)의 하단에 설치된 UV-C 발광소자(200)에서 상기 돼지가 비어있는 돈방의 바닥면에 UV-C 자외선을 조사하여 살균하고, 상기 소독살균 리프터장치(180)의 하단에 설치된 가시광선 발광소자(201)에서 상기 돼지가 있는 돈방에 가시광선을 조사하여 돼지를 살균하는 단계; (f) 상기 소독살균 리프터장치(180)가 원위치로 상승한 후 상기 돼지가 비어있는 돈방을 자연 건조하거나 송풍기로 건조하는 단계; 및(g) 상기 돈방 사이의 돈방 칸막이(102)를 상기 리프터장치(160)로 상승하여 개방한 후 살균 및 건조된 돈방으로 돼지가 이동된 다음, 상기 돼지를 한쪽의 돈방에 격리시키기 위해 상기 리프터장치(160)로 상기 돈방 칸막이(102)를 하강시키고, 상기 (c) 내지 (f) 단계를 진행하여 돈방을 소독 및 살균하는 단계; 를 포함하는 축사 소독용 UV-LED 소독 살균 방법.축사 소독용 UV-LED 소독 살균 장치에 있어서,돈방 사이에 설치된 돈방 칸막이(102)를 상승하여 개방시키고, 상기 돈방 칸막이(102)를 하강하여 상기 돈방을 분리시키는 리프터장치(160);상기 돈방의 벽면에 설치되며, 돼지가 비어있는 돈방에 고압수를 분사하여 바닥을 세척하는 고압수 분사기(170);상기 돈방의 상부에 승하강하도록 설치되며, 상기 돈방의 소정 높이까지 하강하여 소독 및 살균하고 상승하는 소독살균 리프터장치(180);상기 소독살균 리프터장치(180)의 하단 양쪽에 설치되며, 상기 돼지가 비어있는 돈방에 소독살균제를 분사하는 소독살균제 분사기(190);상기 소독살균 리프터장치(180)의 하단에 설치되며, 상기 돼지가 비어있는 돈방에 UV-C 자외선을 소정시간 조사하여 살균하는 UV-C 발광소자(200);상기 소독살균 리프터장치(180)의 하단에 설치되며, 상기 돼지가 있는 돈방에 가시광선을 소정시간 조사하여 돼지를 살균하는 가시광선 발광소자(201); 및상기 리프터장치(160)를 작동하여 상기 돈방 칸막이(102)를 상승시켜 상기 돈방을 개방시키고, 한쪽 돈방으로 돼지가 이동된 후 상기 돈방 칸막이(102)를 하강하여 상기 돈방을 분리시키고, 상기 소독살균 리프터장치(180)를 작동하여 상기 돈방의 소정 높이까지 하강시키고 상기 소독살균제 분사기(190)를 작동하여 소독살균제를 분사하고, 상기 돼지가 비어있는 돈방에 설치된 고압수 분사기(170)를 작동하여 바닥면을 고압수로 세척하고, 상기 UV-C 발광소자(200)를 작동하여 UV-C 자외선으로 상기 돼지가 비어있는 돈방의 바닥면을 살균하고, 상기 가시광선 발광소자(201)를 작동하여 가시광선으로 돼지를 살균하는 동작을 제어하는 제어부(110);를 포함하는 축사 소독용 UV-LED 소독 살균 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

605/1150 Row 605: application_number: 1020210033404, combined_string: invention_title: 질산염 제거 시스템 및 이에 포함되는 탈질 여과조 abstract: 본 명세서에 개시된 내용은 박테리아에 먹이를 공급하여 질산염을 지속적으로 제거하는 질산염 제거 시스템 및 이에 포함되는 탈질 여과조의 제공에 관한 것이다.본 명세서에 개시된 내용의 일 실시예에 따르면, 질산염 제거 시스템은 수조의 사육수가 유입되는 제1 공간을 구획하는 제1 격벽을 포함하는 유입부, 상기 제1 격벽의 타측에 형성되는 제1 여과부 및 상기 제1 여과부의 타측에 형성되어 상기 수조로 상기 사육수를 배출하는 배출부를 포함하는 탈질 여과조 및 상기 제1 여과부에 박테리아 먹이를 피딩하도록 형성된 피딩부를 포함하고, 상기 피딩부는 상기 제1 격벽의 타측 일부공간을 둘러싸고 통로가 형성되는 구획판에 의해 구비된 먹이투입공간으로 상기 먹이를 투입한다. claims: 용기 형태의 본체, 상기 본체의 일측 내부에서 수조의 사육수가 유입되는 제1 공간을 구획하는 제1 격벽을 포함하는 유입부, 상기 제1 격벽의 타측에 형성되는 제1 여과부 및 상기 제1 여과부의 타측에 형성되어 상기 수조로 상기 사육수를 배출하는 배출부를 포함하는 탈질 여과조; 및상기 제1 여과부에 박테리아 먹이를 피딩하도록 형성된 피딩부;를 포함하고,상기 피딩부는 상기 제1 격벽의 타측 일부공간을 둘러싸고 통로가 형성되는 구획판에 의해 구비된 먹이투입공간으로 상기 먹이를 투입하며,상기 유입부는 상기 제1 격벽보다 높게 연장된 사각판 형태로 형성되어 상기 제1 격벽의 전방에 배치되고, 상기 제1 공간 및 타측에 형성된 제2 공간을 서로 분리시키는 제2 격벽을 더 포함하며,상기 제1 여과부는, 상기 제2 격벽과 동일한 형태로 형성되고 상기 제2 격벽의 타측에 연결되는 제1 구획판, 상기 제1 구획판에 연결되고 전방으로 연장되어상기 제2 공간의 내부에서 상기 먹이투입공간인 제3 공간을 구획하는 제2 구획판 및 상기 제1 격벽보다 높이가 낮고 상기 제2 구획판의 타측에 이격 배치되는 제3 격벽을 포함하며,상기 제1 구획판에는, 상기 제1 구획판의 상부 일부분이 상기 본체의 바닥과 이격된 위치까지 하부로 소정의 거리만큼 함몰되어 상기 제2 및 제3 공간을 연결하는 제1 통로가 형성되는 것을 특징으로 하는 질산염 제거 시스템.용기 형태의 본체;상기 본체의 일측 내부에서 수조의 사육수가 유입되는 제1 공간을 구획하는 제1 격벽 및 펌프가 형성되는 유입부;상기 제1 격벽의 타측에 형성되고 박테리아가 서식되는 제1 여과부;상기 제1 여과부의 타측에 형성되고 박테리아가 서식되는 제2 여과부;상기 제1 및 제2 여과부에 배치되는 여과재; 및상기 제2 여과부의 타측에 배치되고 상기 본체에 형성된 배출구를 통해 외부와 연결되는 배출부;를 포함하며,상기 유입부는 상기 제1 격벽보다 높게 연장된 사각판 형태로 형성되어 상기 제1 격벽의 전방에 배치되고, 상기 제1 공간 및 타측에 형성된 제2 공간을 서로 분리시키는 제2 격벽을 더 포함하며,상기 제1 여과부는, 상기 제2 격벽과 동일한 형태로 형성되고 상기 제2 격벽의 타측에 연결되는 제1 구획판, 상기 제1 구획판에 연결되고 전방으로 연장되어상기 제2 공간의 내부에서 먹이투입공간인 제3 공간을 구획하는 제2 구획판 및 상기 제1 격벽보다 높이가 낮고 상기 제2 구획판의 타측에 이격 배치되는 제3 격벽을 포함하며,상기 제1 구획판에는, 상기 제1 구획판의 상부 일부분이 상기 본체의 바닥과 이격된 위치까지 하부로 소정의 거리만큼 함몰되어 상기 제2 및 제3 공간을 연결하는 제1 통로가 형성되는 것을 특징으로 하는 탈질 여과조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

606/1150 Row 606: application_number: 1020210019185, combined_string: invention_title: 질소가스와 유산 용액을 주입하여 제조되는 곤포발효볏짚 abstract: 본 발명의 '질소가스와 유산 용액을 주입하여 제조되는 곤포발효볏짚'은 그동안 한우를 키우는 농가에서 집 근처에 볏짚을 쌓고 비닐로 덮고 질소가스를 주입한 후 자체발열로 발효되면서 질소성분이 볏짚에 스며들도록 한 방법으로 이용해 왔는데 이러한 방법은 자신의 키우는 소 이외에 이웃농가에 줄 수는 있으나 장거리 이송은 불가능하여 이동이 어려운 발효볏짚을 장거리까지 공급할 수 있도록 곤포로 포장시키고 포장된 곤포볏짚에 질소가스와 미량광물수용액으로 조성되는 유산 용액을 주입하여 곤포발효볏짚으로 제조하므로 밀폐된 체 장거리이송도 가능하게 하는 사료분야의 가공기술에 속한다,곤포로 포장을 하면 접착성을 갖는 비닐 랩으로 4 내지 6겹을 둘러 곤포를 형성시키므로 포장된 곤포에 질소가스와 유산 용액을 주입할 수 없기 때문에 곤포로 제조한 다음에 둥근면의 정 가운데에 작은 주입 공을 만들고 주입기를 삽입하여 일정량의 질소가스와 유산 용액을 주입한 후 접착테이프로 주입 공을 막고 뒤집어 밑면으로 위치시켜 적재 해 놓으면 일정기간 질소 흡수와 유산균 발효가 진행되고 일단 진행된 후는 스스로 발효를 유지하므로 장기보관이 가능하게 하는 방법이다,곤포볏짚은 볏짚이 속이 비어 있어서 질소가스 주입이 가능하고 이에 따라 유산균을 주입하지 아니해도 유산 용액에 의해 유산균이 증식하므로 질소성분으로 우수한 비단백태질소사료로 제조되면 반추동물에게는 비싼 단백질사료를 급여하지 아니해도 충분한 단백질사료로 대체할 수 있게 되어 사육농가의 사료비를 줄이면서 사육농가의 수익을 높이는 효과가 기대되는 발명이다, [색인어]곤포(梱包), 질소가스, 유산 용액, 볏짚사료, 단백질사료,반추동물, 곤포발효볏짚, 비단백태질소사료(非蛋白態窒素詞科), claims: 벼를 수확한 남은 볏짚(50)을 결속시켜 볏짚 롤(60)로 엮고, 곤포포장장치로 상기 볏짚 롤을 곤포용 비닐로 여러 겹을 감아 제조된 곤포(10)를, 상기 곤포의 윗면 또는 아랫면 정중앙에 곤포주입 공(12)을 만들고, 상기 곤포주입 공에 주입기(30)를 삽입하여 일정량의 질소가스(22) 또는 사료용 요소(24)와 유산 용액(20)을 주입하고, 상기 주입기 삽입으로 형성된 상기 곤포주입 공을 대형테이프(40)로 막은 상기 곤포들을 노지 일 측에 모아 보온덮개(70)로 덮고 일정기간 발효시켜 제조되는 것이 특징인 질소가스와 유산 용액을 주입하여 제조되는 곤포발효볏집, Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

607/1150 Row 607: application_number: 1020210011745, combined_string: invention_title: 유해물질 유입 차단이 가능한 작업등용 전구 소켓 구조 abstract: 본 발명은 각종 산업현장이나, 가축을 사육하는 축사등에서 사용하는 작업등용 전구 소켓에 관한 것이다.본 발명은 전구가 장착되어지는 전구 소켓 내부로로 유해물질인 분진이나 가축의 배설물로 인해 발생하는 메탄가스 등이 유입되어 발생하는 누전에 의한 감전 사고는 물론, 전구 소켓을 구성하는 전도체의 부식이 가속화되어 사용수명이 현저하게 줄어드는 폐단을 해결할 수 할 수 있도록 한 관한 것이다. claims: 백열전구형 전구(1)의 나사전극(2)이 나사식 결합되어 전기적으로 도통하는 소켓나사전극관(10)이 내측으로 위치하고, 상기 백열전구형 전구(1)의 전구중심전극(3)이 전기적으로 도통하도록 접촉되어지는 소켓중심전극편(21)이 장착되어지는 소켓중심전극장착부재(20)가 상부로 위치하여 있는 소켓나사전극관장착부재(30)의 내구성보강환테(31)에 유해물질차단러버(100)가 장착 구성되어 지되, 상기 유해물질차단러버(100)는 상하로 도통되어 속이빈 형태로 측단면의 둘레벽(140) 형상이 반구형으로 하부 말단에는 소켓나사전극관장착부재(30)의 내측으로 위치한 소켓나사전극관(10)에 전구(1)의 나사전극(2)이 나사결합되어질때 전구(1)의 숄더(4)에 압박됨과 동시에 내측으로 말려 오므려지는 탄성변형이 일어나면서 상기 전구(1)와 소켓(1000) 사이에 공극이 없이 기밀되어질 수 있도록 하는 탄성변형부(110)가 형성되어 있고, 상부의 고정부(120) 내측면에는 소켓나사전극관장착부재(30)의 내구성보강환테(31)에 장착되어지는 장착환홈(130)이 형성되어 있는 것을 특징으로 하는 유해물질 유입 차단이 가능한 작업등용 전구 소켓 구조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

608/1150 Row 608: application_number: 1020200181641, combined_string: invention_title: 혈통정보 및 유전정보 육종가를 이용한 한우 암소의 활용 유형 결정 시스템 abstract: 본원은 한우 암소의 혈통정보 및 유전정보 육종가를 사용하여 암소를 육질형 송아지 생산 용도, 육량형 송아지 생산 용도, 및 비육출하 또는 수정란 대리모 용도로 조기에 판정하는 시스템을 개시한다. 본원은 혈통+유전 통합 정보를 활용하여 단독 정보 활용보다 수익성을 높였다. 본원에 따른 시스템을 이용하면 태어나는 송아지의 사양 방법을 임신시기에 결정하여 맞춤형 정밀사양을 적용할 수 있고, 암소의 활용도를 높이고, 개정된 쇠고기 등급제에 활용하게 되어 한우 산업의 효율 증진을 도모할 수 있다. claims: 한우 암소 표준집단의 근내지방도 및 도체중을 포함하는 혈통 정보 육종가를 구축 및 관리하는 표준집단의 혈통 정보기반 육종가 관리부; 한우 암소 표준집단의 근내지방도 및 도체중을 포함하는 유전 정보 육종가를 구축 및 관리하는 표준집단의 유전 정보기반 육종가 관리부;대상 한우 암소의 근내지방도 및 도체중에 대한 혈통 정보 육종가를 분석하는, 대상 한우 암소의 혈통 정보기반 육종가 분석부; 대상 한우 암소의 근내지방도 및 도체중에 대한 유전 정보 육종가를 분석하는, 대상 한우 암소의 유전 정보기반 육종가 분석부; 상기 대상 한우 암소의 상기 혈통 정보기반 육종가 분석부의 상기 근내지방도 및 도체중의 혈통 정보 육종가를 상기 표준집단의 상응하는 혈통 정보기반 육종가 관리부의 육종가와 비교하여, 상기 대상 한우 암소의 상기 근내지방도 및 도체중의 혈통 정보 기반 육종가의 누적 백분위를 산출하는, 대상 한우 암소의 혈통 정보기반 육종가 누적 백분위 산출부; 상기 대상 한우 암소의 상기 유전 정보기반 육종가 분석부의 상기 근내지방도 또는 도체중의 유전 정보 육종가를 상기 표준집단의 상응하는 유전 정보기반 육종가 관리부의 육종가와 비교하여, 상기 대상 한우 암소의 상기 근내지방도 및 도체중의 유전 정보 기반 육종가의 누적 백분위를 산출하는, 대상 한우 암소의 유전 정보기반 육종가 누적 백분위 산출부; 및상기 혈통 정보기반 육종가 누적 백분위 산출부 및 상기 유전 정보기반 육종가 누적 백분위 산출부에 의해 산출된 상기 대상 한우 암소의 근내지방도 및 도체중의 누적 백분위 정보를 이용하여 상기 대상 한우 암소의 활용 유형을 분류하는 활용 유형 적용부를 포함하며, 상기 활용 유형 적용부에서는 상기 혈통 정보기반 근내지방도 육종가, 혈통 정보기반 도체중 육종가, 유전 정보기반 근내지방도 육종가 및 유전 정보기반 도체중 육종가의 누적 백분위가 미리 정한 기준으로 순차적으로 적용되어 상기 대상 한우 암소는 (i) 육질형 송아지 생산 암소; (ii) 육량형 송아지 생산 암소; 또는 (iii) 암소비육 또는 수정란 대리모로 분류되며, 상기 미리 정한 기준은 (a) 대상 한우의 상기 혈통 정보기반 근내지방도 육종가의 누적 백분위가 상위 70%에 해당; 상기 혈통 정보기반 근내지방도 육종가의 누적 백분위가 상위 70%에 해당되지 않는 경우, 상기 혈통 정보기반 도체중 육종가의 누적 백분위가 상위 30%에 해당되지 않음; 또는 상기 혈통 정보기반 도체중 육종가의 누적 백분위가 상위 30%에 해당되는 경우, 상기 유전 정보기반 근내지방도 육종가가 상위 70%에 해당될 때 상기 (i) 육질형 송아지 생산 암소로 분류되고, (b) 상기 (a)에서 상기 유전 정보기반 근내지방도 육종가가 상위 70%에 해당하지 않는 경우, 상기 유전 정보기반 도체중 육종가가 상위 30%에 해당될 때 상기 (ii) 육량형 송아지 생산 암소로 분류되고, (c) 상기 (b)에서 상기 유전 정보기반 도체중 육종가가 상위 30%에 해당되지 않을 때 (iii) 암소비육 및 수정란 대리모 암소로 분류되는, 한우 암소 활용 유형 분류 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

609/1150 Row 609: application_number: 1020200163602, combined_string: invention_title: 깊이 영상카메라 및 소리 센서를 활용한 모돈의 발정기 및 수정적기 판단 시스템 abstract: 본 발명은 모돈의 수정 적기를 판단하기 위해 깊이 영상카메라 및 소리 센서로 모돈의 발정기를 탐지하고 수정적기를 판단하는 시스템으로서, 복수의 모돈의 발정 여부를 관찰하기 위해 돈사 내에 모돈을 사육하는 스톨의 천장에 설치되어 상기 모돈의 움직임을 촬영 및 저장하는 깊이 영상카메라; 상기 깊이 영상카메라에서 촬영된 영상을 분석하는 영상분석기를 포함하며, 상기 영상분석기에는 상기 모돈의 수정적기를 판단하기 위한 딥러닝 기반의 수정적기 판단 소프트웨어가 포함되어 있는 것을 특징으로 한다. 본 발명에 따라 모돈의 발정기를 탐지하고 수정 적기를 판단함으로써, 발정 미감지에 따른 피해를 최소화 하여 돈사의 생산성을 극대화 할 수 있으며, 실시간으로 발정기를 자동 탐지함으로써 투입되는 노동력을 절감할 수 있다. claims: 모돈의 수정 적기를 판단하기 위해 깊이 영상카메라 및 소리 센서로 모돈의 발정기를 탐지하고 수정적기를 판단하는 시스템에 있어서,복수의 모돈의 발정 여부를 관찰하기 위해 돈사 내에 모돈을 사육하는 스톨의 천장에 설치되어 상기 모돈의 움직임을 촬영 및 저장하는 깊이 영상카메라; 상기 깊이 영상카메라에서 촬영된 영상을 분석하는 영상분석기를 포함하며,상기 영상분석기에는 상기 모돈의 수정적기를 판단하기 위한 딥러닝 기반의 수정적기 판단 소프트웨어가 포함되고,상기 딥러닝 기반의 수정적기 판단 소프트웨어는, 딥러닝 학습을 통해 학습데이터에서 설정된 기준에서 일정 범위를 벗어나는 분석값을 나타낼 때 이상상황으로 탐지하고 상기 모돈의 수정적기 판단에 활용하는 이상상황 탐지 모듈를 더 포함하며, 상기 이상상황 탐지 모듈은 인공지능 신경망 모델을 사용하되, 신경망 학습에 있어서 부족한 데이터를 사전 제작된 페이크 영상데이터 및 페이크 소리데이터로 대체하고, 비지도 학습 신경망 모델의 GAN(Generative Adversarial Nets)을 학습에 적용하여 상기 딥러닝 학습데이터 기준에서 소정의 수치 범위를 벗어나는 것으로 판단될 때, 상기 모돈이 발정시기인 것으로 판단하는 것을 특징으로 하는 깊이 영상카메라 및 소리 센서를 활용한 모돈의 발정기 및 수정적기 판단 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

610/1150 Row 610: application_number: 1020200148936, combined_string: invention_title: 비타민 A의 급여에 의한 한우 육량 및 육질의 개선 방법 abstract: 본 발명은 비타민 A의 급여에 의한 한우 육량 및 육질의 개선 방법에 관한 것으로, 더욱 상세하게는 어린 송아지 시기에 비타민 A를 경구로 추가 급여함으로써 한우 육량 및 육질을 개선하는 방법에 관한 것이다. claims: 비타민 A을 2개월 경까지 송아지에 급여하는 단계;를 포함하는, 한우 육량 및 육질의 개선 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

611/1150 Row 611: application_number: 1020200089286, combined_string: invention_title: 플라스틱(아크릴)을 성형하여 만든 외장재 및 온실의 제작법 abstract: 본 발명에 의한 플라스틱을 둥근접시모양으로 성형하여 결합한 외부 마감재는 외부에서 오는 열을 넓게 흡수하여 내부에서도 넓게 분배하며 공기층을 가지고 있어, 온도의 보존율이 좋다. 또한 간단한 시공법 및 지속적인 소모품 및 유지에 필요한 전기가 필요없기 때문에 효율성이 좋아지며 식물을 식재하는 농장에서는 사육환경이 개선되며 원가절감을 얻을 수 있는 효과가 있다. claims: 플라스틱(아크릴)을 둥근 접시모양으로 성형하고, 이를 결합하여 건축물의 외부마감재로 사용하는 방식, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

612/1150 Row 612: application_number: 1020200081094, combined_string: invention_title: 동물용 연속주사기 보조장치 abstract: 본 발명은 소 등의 가축이나 사육되는 동물에게 예방 또는 치료용 주사약물를 투약할 때, 원거리에서 다수의 동물들에게 안전하고 신속하게 주사약물을 투약할 수 있도록, 상용의 연속주사기를 장착하여 사용할 수 있도록 구성된 동물용 연속주사기 보조장치에 관한 것으로, 익스텐션 튜브(100); 헤드 어댑터(200); 전방 연장관(500, 500´); 및 주사기 장착관(600, 600´);을 포함하는 연속주사기 연장모듈(2, 2´)로 이루어져 있다. 또한, 본 발명의 보조장치는 상기 연속주사기 연장모듈(2, 2´)이 장착되는 연장모듈 장착관(700, 700´) 및 가압부(800, 800´)를 포함하는 연속주사기 가압모듈(3, 3´)이 추가로 구비하고, 동물들과 다양한 거리에서 안전하고 신속한 주사를 투약할 수 있도록 구성되어 있다. claims: 연속주사기(10)를 장착하여 원거리에서 동물에게 주사약물을 투약할 수 있도록 상기 연속주사기(10)의 전방에 장착되는 연속주사기 연장모듈(2, 2')과 연속주사기 가압모듈(3, 3´)을 포함하는 동물용 연속주사기 보조장치에 있어서, 상기 연속주사기 연장모듈(2, 2´)은 익스텐션 튜브(100); 헤드 어댑터(200); 전방 연장관(500, 500´); 주사기 장착관(600, 600´); 및 제1 고정부재(650,650´)를 포함하고, 상기 익스텐션 튜브(100)는 상기 전방 연장관(500, 500´)에 삽입되어 있고, 상기 익스텐션 튜브(100)의 전방 결합단(110)은 상기 헤드 어댑터(200)를 매개로 상기 전방 연장관(500, 500´)의 전방 단부에 결합되며, 상기 전방 연장관(500, 500´)은 상기 주사기 장착관(600, 600´)에 삽입되어 결합되고, 제1 고정부재(650, 650´)는 전방 연장관(500, 500´)과 상기 주사기 장착관(600, 600´)을 서로 고정시킬 수 있도록 구성되어 있으며, 상기 주사기 장착관(600, 600´)은 연속주사기(10)의 주사기 손잡이(13)는 후방에 노출된 상태에서 상기 연속주사기(10)의 주사기 몸체(12)를 지지하도록 구성되어 있으며, 상기 연속주사기 가압모듈(3, 3´)은 연장모듈 장착관(700, 700´)과 가압부(800, 800´)를 포함하고, 상기 연장모듈 장착관(700, 700´)은 상기 연속주사기 연장모듈(2, 2´)이 장착되는 연장모듈 거치부(710, 710´); 상기 연장모듈 거치부(710, 710´)의 상부에 형성된 연장모듈 삽입공(720, 720´); 및 상기 연장모듈 거치부(710. 710´)의 하부에 형성된 연속주사기 손잡이 삽입공(740, 740´)을 포함하고 있고, 상기 연장모듈 장착관(700, 700´)의 전방은 상기 주사기 장착관(600, 600´)과 결합되며,상기 가압부(800, 800´)는 상기 연장모듈 장착관(700, 700´)의 후방에 결합되어 있는 것을 특징으로 하는 동물용 연속주사기 보조장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

613/1150 Row 613: application_number: 1020200076121, combined_string: invention_title: 가축사용 벌레 퇴치 LED살균 조명등 abstract: 본 발명은 가축사용 벌레퇴치 LED살균 조명등에 관한 것으로서, 가축사의 공기를 LED살균하며 벌레를 퇴치시켜 가축사육 환경이 쾌적하게 유지되도록 함을 목적으로 한 것이다.즉, 본 발명은 가축사의 천장에 매달아 가축사의 공기와 가축을 살균하며 벌레를 퇴치하는 가축사용 벌레퇴치 LED살균 조명등을 구비한 것을 특징으로 하는 것이다.따라서, 본 발명은 UVLED를 통하여 가축사의 공기를 LED살균하며 음파발생전원부에 발생되는 벌레퇴치 음파신호를 통하여 벌레를 퇴치시켜 가축사육 환경이 쾌적하게 유지되는 효과를 갖는 것이다. claims: 가축사의 천장에 매달아 가축사의 공기와 가축을 살균하며 벌레를 퇴치하는 가축사용 벌레퇴치 LED살균 조명등을 구비하되,상기 벌레퇴치 LED살균 조명등은 판상으로 형성되는 등몸체와 상기 등몸체의 하부에 UV를 조사하여 공기와 가축을 살균할 수 있게 UVLED소자가 실장된 UVLED등부, 상기 등몸체의 상부에 UVLED소자에서 발열된 열을 공기 중으로 방출시킬 수 있게 구비한 방열부, 상기 방열부의 상부에 스위칭소자에 의하여 전압을 조절 출력하고 벌레퇴치를 위한 음파신호를 출력할 수 있게 구비한 음파발생전원부, 상기 방열부에 음파발생전원부에서 출력되는 음파신호에 따라 공기 중을 벌레퇴치소리를 발산시킬 수 있게 구비한 음파출력부 및 상기 등몸체의 하부에 UVLED등부에서 발산되는 빛이 하부로 집중 조사되게 하고 음파출력부에 의하여 방열부으로 전달된 벌레퇴치음을 하부로 확산 발산시킬 수 있게 구비한 음파방사갓으로 구성하며;상기 UVLED등부는 원형 판상의 LED보드와 상기 LED보드에 실장되는 UVLED소자로 이루어진 2 개 UVLED부로 구성되고;상기 UVLED부는 49개의 UVLED소자가 직렬배선되게 실장되어 형성되며;상기 UVLED소자에는 조사되는 UV가 가축사 중앙부에 공기에 집중 작용되게 조사점을 조절하는 중앙조사렌즈부를 구비하며;상기 방열부는 등몸체에 결합되는 방열몸체와 상기 방열몸체에서 핀형으로 돌출되어 열을 노치 방열하는 방열부으로 구성되며, 방열부과 방열부 사이에 형성되는 방열공 사이의 방열몸체 상단은 누적된 먼지가 음파출력부의 진동에 의하여 흘러 배출되게 중앙에서 외측으로 경사지게 형성하고;상기 음파발생전원부는 외부의 전원이 입력되는 전원입력부와 상기 전원입력부에서 입력된 전원을 스위칭 전압조절을 위하여 20~50Khz 전압조절발진부, 상기 전압조절발진부에서 발진된 20~50Khz 발진 주파수에 의하여 벌레퇴치를 위한 퇴치음 동작신호를 출력할 수 있게 구비한 벌레퇴치음파출력부, 상기 전압조절발진부에서 발진된 발진 주파수에 따라 스위칭 동작하여 입력된 전원을 단속하여 출력할 수 있게 구비한 전압조절스위칭부, 상기 전압조절스위칭부에 의하여 구형파로 출력되는 전원을 평활하여 설정된 전압으로 조절할 수 있게 구비한 전압평활부, 상기 전압평활부에서 평활화된 전원을 출력할 수 있게 구비한 전원출력부 및 상기 각 구성의 동작을 제어하여 전압이 조절되어 출력할 수 있게 구비하며;방열부의 상부 측에는 UVLED등에 의하여 살균된 가축사 중앙부의 공기가 가축사의 가축에게 작용될 수 있게 송풍장치를 구비한 전원제어부로 구성한 것을 특징으로 하는 가축사용 벌레퇴치 LED살균 조명등., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

614/1150 Row 614: application_number: 1020200056193, combined_string: invention_title: 가변형 가축 사육시설 abstract: 본 발명은 가축의 사육 공간이 변형 가능한 가축용 스톨에 관한 것이다. 본 발명에 따른 가축용 스톨은, 가축을 수용하기 위해 소정 방향으로 오픈된 수용 공간을 갖도록 제공된 고정틀; 상기 고정틀의 일측에 배치되며 상기 고정틀의 상기 소정 방향으로 이동 가능한 유동성 틀; 및 상기 유동성 틀의 일측에 제공되며 상기 오픈된 수용 공간을 개폐하는 후면 차단기를 포함하고, 상기 유동성 틀의 상기 소정 방향 이동에 따라 상기 수용 공간의 크기가 변형된다. 이에 따라, 가축의 자유로운 움직임을 조절하여 효율적인 가축 사육이 가능하다. claims: 가축을 수용하기 위해 소정 방향으로 오픈된 수용 공간을 갖도록 제공된 고정틀;상기 고정틀의 일측에 배치되며 상기 고정틀의 상기 소정 방향으로 이동 가능한 유동성 틀; 및상기 유동성 틀의 일측에 제공되며 상기 오픈된 수용 공간을 개폐하는 후면 차단기를 포함하고,상기 유동성 틀의 상기 소정 방향 이동에 따라 상기 수용 공간의 크기가 변형되는 가축용 스톨., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

615/1150 Row 615: application_number: 1020200050682, combined_string: invention_title: 건축물 에너지 절약 시스템, 그리고 이를 위한 건축물 에너지 관리 서버 abstract: 본 발명은 건축물 에너지 절약 시스템에 관한 것이다. 본 발명은, 복수의 스마트 디바이스(100)로 이루어진 스마트 디바이스 그룹(100g), 네트워크(200), 건축물 에너지 관리 서버(300), 복수의 스마트 제어 유닛(400)으로 이루어진 스마트 제어 유닛 그룹(400g)을 포함하는 건축물 에너지 절약 시스템(1)에 있어서, 스마트 제어 유닛(400)은, 지중에 매립된 복수 개의 파이프로 구성될 수 있으며, 파이프로부터 연장된 지열관을 따라 냉각 또는 가열을 수행하며, 냉각 작동시 냉각형 열교환을 위한 보조 열교환 단위 유닛으로부터 보조적으로 냉각 작용을 제공받으며, 가열 작동시 가열형 열교환을 위한 보조 열교환 단위 유닛으로부터 보조적으로 가열 작용을 제공받으며, 냉각 작동과 가열 작동에 따라 구분된 영역을 활용하여 각기 다른 냉각 펌프(410a) 및 히트 펌프(410b)에 의해 축냉 탱크(440) 및 축열 탱크(450)에 냉기 및 열기를 제공하는 지중열교환기(410); 냉난방 운전이 가능한 공조기로 냉방운전을 수행하기 위해 공기와 냉매간에 열교환을 수행하여 축열된 냉매의 열에너지를 응축기와 연결된 축냉 탱크(400)로 냉각 펌프(420a)를 활용해 제공하며, 난방운전을 수행하기 위해 공기와 냉매간의 열교환을 수행하여 축열된 냉매의 열에너지를 기화기와 연결된 축열 탱크(500)로 히트 펌프(420b)를 활용해 제공하는 공기열교환기(420); 외부의 액체 파이프로부터 제공된 냉기를 냉각 히트 펌프를 통해 축냉 탱크(440)로 제공하며, 외부의 액체 파이프로부터 제공된 온기를 온열 히트 펌프를 축열 탱크(450)로 제공할 수 있으며, 냉각 작동과 가열 작동에 따라 구분된 영역을 활용하여 각기 다른 냉각 펌프(430a) 및 히트 펌프(430b)에 의해 축냉 탱크(440) 및 축열 탱크(450)에 냉기 및 열기를 제공하는 수열교환기(430); 냉각 회전 튜브(440a)와 사이에 형성된 냉각 히트 펌프를 통해 건축물의 미리 설정된 구역으로 냉기를 제공함으로써, 미리 설정된 구역에 대한 온도 상승을 억제하도록 하는 냉각 기능을 제공하는 축냉 탱크(440); 온열 회전 튜브(450a)와 사이에 형성된 온열 히트 펌프를 통해 건축물의 미리 설정된 구역으로 온기를 제공함으로써, 미리 설정된 구역에 대한 온도 하락을 억제하도록 하는 온열 기능을 제공하는 축열 탱크(450); 및 제 1 온도센싱단(491a), 제 2 온도센싱단(492a), 냄새 센싱단(493a) 및 온습도센싱단(494a)을 포함하며, 제 1 온도센싱단(491a)은 축냉 탱크(440) 내부에 열매와 맞닿아 형성되며, 제 2 온도센싱단(492a)은 축열 탱크(450) 내부에 냉매에 맞닿아 형성되며, 온습도센싱단(494a)은 건축물의 미리 설정된 구역의 지정된 위치에 형성되는 센싱부(490a); 를 포함하며, 각 스마트 디바이스(100)에 의해 하나 이상의 스마트 제어 유닛(400)에 대한 건축물 에너지 관리 서버(300)로의 등록 이후에 각 스마트 제어 유닛(400)에 대한센싱부(490a)를 통해 센싱된 제 1 온도센싱단(491a)에 의해 측정된 제 1 온도센싱정보, 제 2 온도센싱단(492a)에 의해 측정된 제 2 온도센싱정보에 따라 축냉 탱크(440) 및 축열 탱크(450)에 의한 열교환에 의해 온도를 유지할 뿐만 아니라, 축냉 탱크(440) 및 축열 탱크(450)를 열-전기에너지 변환 단위 유닛(400u)으로 구성함으로써, 변환된 전기 에너지로 스마트 제어 유닛(400)의 구성요소에 대한 전력을 공급하는 것을 특징으로 할 수 있다.이에 의해, 건축물 용도별 에너지 사용량을 시간에 따라 분리하여 냉방, 난방, 급탕 등의 운전을 선택함으로써, 에너지를 절약하도록 할 뿐만 아니라, 건축물이 축사 및 돈사 등인 경우, 축사 및 돈사 등의 냄새 및 일정 온도 유지하도록 하는 효과를 제공할 뿐만 아니라, 축냉 탱크 및 축열 탱크를 열-전기에너지 변환 단위 유닛으로 구성함으로써, 에너지 효율을 높일 뿐만 아니라, 축냉 탱크와 축열 탱크의 온도를 미리 설정된 온도 범위로 자동으로 제어되면서도 에너지 효율을 향상시킬 수 있는 효과를 제공할 수 있다. claims: 복수의 스마트 디바이스(100)로 이루어진 스마트 디바이스 그룹(100g), 네트워크(200), 건축물 에너지 관리 서버(300), 복수의 스마트 제어 유닛(400)으로 이루어진 스마트 제어 유닛 그룹(400g), 그리고 빅데이터 서버(500)를 포함하는 건축물 에너지 절약 시스템(1)에 있어서, 스마트 제어 유닛(400)은, 지중열교환기(410), 공기열교환기(420), 수열교환기(430), 축냉 탱크(440), 냉각 회전 튜브(440a), 축열 탱크(450), 온열 회전 튜브(450a), 급기팬(460), 펠티어소자(470), 약품분사기(480), 센싱부(490a), 컨트롤러(490b), 송수신 안테나(490c)를 포함하며, 지중열교환기(410)는,지중에 매립된 복수 개의 파이프로 구성될 수 있으며, 파이프로부터 연장된 지열관을 따라 냉각 또는 가열을 수행하며, 냉각 작동시 냉각형 열교환을 위한 보조 열교환 단위 유닛으로부터 보조적으로 냉각 작용을 제공받을 수 있으며, 가열 작동시 가열형 열교환을 위한 보조 열교환 단위 유닛으로부터 보조적으로 가열 작용을 제공받으며, 냉각 작동과 가열 작동에 따라 구분된 영역을 활용하여 각기 다른 냉각 펌프(410a) 및 히트 펌프(410b)에 의해 축냉 탱크(440) 및 축열 탱크(450)에 냉기 및 열기를 제공하며,공기열교환기(420)는,냉난방 운전이 가능한 공조기로 냉방운전을 수행하기 위해 공기와 냉매간에 열교환을 수행하여 축열된 냉매의 열에너지를 응축기와 연결된 축냉 탱크(400)로 냉각 펌프(420a)를 활용해 제공하며, 난방운전을 수행하기 위해 공기와 냉매간의 열교환을 수행하여 축열된 냉매의 열에너지를 기화기와 연결된 축열 탱크(500)로 히트 펌프(420b)를 활용해 제공하며,수열교환기(430)는,외부의 액체 파이프로부터 제공된 냉기를 냉각 히트 펌프를 통해 축냉 탱크(440)로 제공하며, 외부의 액체 파이프로부터 제공된 온기를 온열 히트 펌프를 축열 탱크(450)로 제공할 수 있으며, 냉각 작동과 가열 작동에 따라 구분된 영역을 활용하여 각기 다른 냉각 펌프(430a) 및 히트 펌프(430b)에 의해 축냉 탱크(440) 및 축열 탱크(450)에 냉기 및 열기를 제공하며,축냉 탱크(440)는,냉각 회전 튜브(440a)와 사이에 형성된 냉각 히트 펌프를 통해 건축물의 미리 설정된 구역으로 냉기를 제공함으로써, 미리 설정된 구역에 대한 온도 상승을 억제하도록 하는 냉각 기능을 제공하며,축열 탱크(450)는,온열 회전 튜브(450a)와 사이에 형성된 온열 히트 펌프를 통해 건축물의 미리 설정된 구역으로 온기를 제공함으로써, 미리 설정된 구역에 대한 온도 하락을 억제하도록 하는 온열 기능을 제공하며,급기팬(460)은,건축물의 미리 설정된 구역에 대한 외부와의 공기 교환을 위한 팬에 해당하며,펠티어소자(470)는,미리 설정된 구역에서 특수한 목적을 위해 세부 온도 조절이 필요한 설정 영역에 대한 냉온 온도 조절, 급냉 온도 설정을 위해 사용되기 위해 형성되며, 설정 영역에 대한 외부 전력을 이용해 컨트롤러(490b)의 제어에 따라 온도 조절을 수행하며, 온열 회전 튜브(450a)가 형성된 건축물 상에서 온수를 공급하는 급수탱크의 벽면에 형성되며, 모듈 형태로 펠티어 소자와 급수탱크 표면의 온도센서, 아두이노 기판을 활용하여 미리 설정된 온도 범위로 급수탱크에 대한 온도를 제어하며, 약품분사기(480)는,컨트롤러(490b)에 의해 미리 설정된 구역에 대한 냄새가 난다고 센싱부(490a)에 의해 센싱된 경우 천연 방향제를 분사하기 위해 형성되며,센싱부(490a)는,제 1 온도센싱단(491a), 제 2 온도센싱단(492a), 냄새 센싱단(493a) 및 온습도센싱단(494a)을 포함하며, 제 1 온도센싱단(491a)은 축냉 탱크(440) 내부에 열매와 맞닿아 형성되며, 제 2 온도센싱단(492a)은 축열 탱크(450) 내부에 냉매에 맞닿아 형성되며, 냄새 센싱단(493a) 및 온습도센싱단(494a)은 건축물의 미리 설정된 구역의 지정된 위치에 형성되며, 컨트롤러(490b)는, 스마트 제어 유닛(400)을 구성하는 각 구성요소에 대한 제어를 수행할 뿐만 아니라, 송수신 안테나(490c)를 통해 네트워크(200)와 연결된 건축물 에너지 관리 서버(300), 각 스마트 디바이스(100), 빅데이터 서버(500)와 신호 및 데이터 송수신을 수행하며, 건축물 에너지 관리 서버(300)는, 송수신부(310), 제어부(320) 및 데이터베이스(330)를 포함하며, 제어부(320)는 센싱 모듈(321), 에너지 순환 모듈(322), 온도 컨트롤 모듈(323), 공기 컨트롤 모듈(324) 및 피드백 컨트롤 모듈(325)을 포함하며, 센싱 모듈(321)은,각 스마트 제어 유닛(400)의 센싱부(490a) 중 축냉 탱크(440)에 형성된 제 1 온도센싱단(491a)와 축열 탱크(450)에 형성된 제 2 온도센싱단(492a)으로부터 각각 제 1 온도센싱정보 및 제 2 온도센싱정보를 수신하도록 송수신부(310)를 제어한 뒤, 실시간 시간 정보와 제 1 및 제 2 온도센싱정보를 데이터베이스(330)에 각 스마트 제어 유닛(400)의 식별번호를 메타데이터로 저장하며, 각 스마트 제어 유닛(400)의 센싱부(490a) 중 미리 설정된 구역에 형성된 온습도센싱단(494a)으로부터 미리 설정된 구역의 제 3 온도센싱정보 외에 습도 정보를 네트워크(200)를 통해 수신하도록 송수신부(310)를 제어한 뒤, 제 3 온도센싱정보 외에 습도 정보를 제 1 및 제 2 온도센싱정보와 함께 각 스마트 제어 유닛(400)의 식별번호를 메타데이터로 저장하며,센싱부(490a) 중 건축물의 미리 설정된 구역에 형성된 배출되는 가스를 제공받아서 가스의 화학성분을 센싱(sensing)하는 냄새 센싱단(493a)로부터 수신된 정보를 이용하여 냄새 발생여부를 분석한 뒤, 냄새 발생여부 정보를 제 1 및 제 2 온도센싱정보, 제 3 온도센싱정보 및 습도 정보와 함께 각 스마트 제어 유닛(400)의 식별번호를 메타데이터로 함께 모니터링 정보 단위로 저장하며,에너지 순환 모듈(322)은,각 스마트 제어 유닛(400)의 식별번호와 매칭되어 저장된 스마트 디바이스(100)의 단말식별번호(IMEI)를 추출한 뒤, 단말식별번호에 해당하는 스마트 디바이스(100)로 모니터링 정보 단위를 네트워크(200)를 통해 전송하도록 송수신부(310)를 제어하며, 스마트 디바이스(100)로부터 미리 설정된 구역에 대한 제 1 내지 제 3 온도센싱정보에 따른 시간대별 온도구축 정보를 네트워크(200)를 통해 수신하도록 송수신부(310)를 제어한 뒤, 스마트 디바이스(100)의 단말식별번호를 메타데이터로 함께 데이터베이스(330)에 저장하며,온도 컨트롤 모듈(323)은, 제 1 온도센싱정보가 미리 설정된 축냉 탱크 온도 범위 미만인 경우, 축냉 탱크 온도 범위로부터 미리 설정된 온도를 초과하는 냉매(冷媒)를 축냉 탱크(440)로 공급함과 동시에 축냉 탱크(440)와 연결된 배출 밸브에 대한 제어를 통해 냉매(冷媒)에 대한 외부로의 배출이 수행되도록 함으로써, 제 1 온도센싱정보가 축냉 탱크 온도 범위에 속하도록 제어하며, 제 1 온도센싱정보가 미리 설정된 축냉 탱크 온도 범위 미만이고, 제 2 온도센싱정보가 미리 설정된 축열 탱크 온도 범위를 초과하는 경우, 축냉 탱크(440)에서 축열 탱크(450)로의 냉매(冷媒) 제공과 함께 축냉 탱크 온도 범위로부터 미리 설정된 온도를 초과하는 새로운 냉매(冷媒)를 축냉 탱크(440)로 공급을 통해 제 1 온도센싱정보가 축냉 탱크 온도 범위에 속하도록 제어하며, 온도 컨트롤 모듈(323)은,제 1 온도센싱정보가 미리 설정된 축냉 탱크 온도 범위를 초과하는 경우, 지중열교환기(410), 공기열교환기(420) 및 수열교환기(430) 중 현재 냉각 펌프(410a, 420a, 430a)와 히트 펌프(410b, 420b, 430b) 중 히트 펌프(410b, 420b, 430b)가 동작하는 것이 있는 경우 히트 펌프(410b, 420b, 430b)에 대해서 중단시키고, 히트 펌프(410b, 420b, 430b)가 중단된 열교환기(410, 420, 430)와 연결된 냉각 펌프(410a, 420a, 430a)가 동작하도록 제어함으로써, 축냉 탱크 온도 범위 내로 속할 때까지 온도 제어를 수행함으로써, 축, Ltext: 농업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

616/1150 Row 616: application_number: 1020200047011, combined_string: invention_title: 한우 암소의 반추위 내 체온 변화를 이용한 임신 판정방법 abstract: 본 발명은 한우 암소의 반추위 내 체온 변화를 이용한 임신 판정방법에 관한 것으로, 보다 상세하게는, 본 발명은 ICT 기술을 활용하여 인공수정된 한우 암소의 임신기간 중 반추위 내 체온 변화를 분석함으로써 임신가능성 또는 임신유지 여부를 판정할 수 있을 뿐만 아니라 반추위 내 체온 변화로부터 분만을 예측할 수 있다. claims: 한우 암소의 반추위에 삽입된 온도 센서 장치를 이용하여 인공수정된 암소의 반추위 내 체온 변화를 측정하여 암소의 임신가능성 또는 임신유지 여부를 판정하는 단계를 포함하고,상기 임신가능성 또는 임신유지 여부를 판정하는 단계는 한우 암소의 반추위 내 온도가 38.665 내지 38.679℃인 경우 인공수정일로부터 임신 80 내지 100일령, 38.775 내지 38.795℃인 경우 임신 145 내지 165일령, 38.996 내지 39.016℃인 경우 임신 200 내지 220일령 및 39.136 내지 39.116℃인 경우 임신 250 내지 270일령으로 결정하는 것인, 한우 암소의 임신가능성 또는 임신유지 여부의 판정방법.한우 암소의 반추위에 삽입된 온도 센서 장치를 이용하여 임신한 한우 암소의 반추위 내 체온 변화를 측정하고, 인공수정일로부터 임신 200 내지 220일령 또는 임신 250 내지 270일령의 한우 암소의 반추위 내 온도가 각각 38.996 내지 39.016℃ 또는 39.136 내지 39.116℃의 범위 이하로 떨어져 1일 이상 유지하는 경우 분만 가능성이 있는 것으로 예측하는 단계를 포함하는, 한우 암소의 분만 예측방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

617/1150 Row 617: application_number: 1020200042087, combined_string: invention_title: 볏짚 공급기 abstract: 본 발명은 축산농가의 소 사육에 필요한 원형 볏짚(곤포 사일리지)을 자동으로 공급하는 볏짚 공급기에 관한 것으로, 보다 상세하게는 축사팬스 전방에 설치되어 원형 볏짚을 지지하되, 원형 볏짚의 압축 상태가 불규칙함에도 불구하고 자연스럽게 미끄러지며 소가 볏짚을 원활하게 취식할 수 있도록 공급하고, 개폐장치에 개폐시간을 입력하면 자동으로 볏짚 제공 시간을 조절하여 볏짚이 과잉으로 공급되어 발생할 수 있는 손실을 막을 수 있으며, 볏짚이 소진될때까지 노동력을 최소한으로 줄일 수 있는 볏짚 공급기에 관한 것이다. claims: 축사팬스(1) 전방에 고정설치되고, 소머리가 유입되는 개방부(110)와, 상기 개방부(110) 상부에 폐쇄부(120)를 형성하는 전면프레임(100)과;상기 전면프레임(100)의 개방부(110) 하부에서 후방으로 돌출되는 내부면(210)과, 상기 내부면(210)에서 상향경사지는 경사면(220)과, 상기 경사면(220)을 지면으로부터 지지하는 받침부(230)로 이루어져 상기 경사면(220)에서 원형 볏짚(10)의 일측면과 맞닿아 원형 볏짚(10)을 지지하는 바닥프레임(200)과;상기 전면프레임(100)의 폐쇄부(120)와 상기 바닥프레임(200)의 경사면(220)에 결합되고 세로방향으로 연장설치되되 하나 이상의 절곡부(330)를 형성하는 다수개의 창살이 이격형성되어 창살사이로 원형 볏짚(10)이 공급되는 공급프레임(300);을 포함하되;상기 전면프레임(100)의 폐쇄부(120)에는 원형 볏짚(10)의 일측면이 일정각도를 유지하면서 접촉되도록 상부로 갈수록 폭이 넓어지는 접촉부(130)이 돌출형성되는 볏짚 공급기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

618/1150 Row 618: application_number: 1020200035357, combined_string: invention_title: 한우용 사료 조성물 abstract: 본 발명은 한우용 사료 조성물에 관한 것으로, 더욱 상세하게는 곡물류, 강피류, 박류, 섬유질류, 발효 사료 및 면실을 포함하되, 상기 발효 사료는 귀리, 보리, 맥주박, 버섯배지 및 액상 효모를 혼합하여 발효한 것임을 특징으로 한다. 본 발명의 한우용 사료 조성물에 의하면, 한우의 일당증체량을 증가시키고, 사료요구율을 개선할 수 있으며, 한우육의 콜레스테롤 함량은 낮추면서, 불포화지방산 함량을 높일 수 있다는 장점이 있다. 또한, 한우의 육질을 개선할 수 있다는 장점이 있다. claims: 옥수수 후레이크와 루핀 후레이크를 1:1중량비로 혼합한 곡물류 100중량부, 소맥피 20중량부, 단백피 20중량부, 아몬드박 10중량부, 옥배아박 10중량부, 주정박 10중량부, 캐슈넛박 10중량부, 티모시 20중량부, 알팔파 20중량부, 연맥 20중량부, 톨페스큐 20중량부, 페레니얼 20중량부, 블루그라스 20중량부, 애뉴얼 라이그라스 20중량부, 이탈리안 라이그라스 20중량부, 발효 사료 50중량부, 면실 40중량부, 욱리인 5중량부, 무화과 잎의 발효물 5중량부 및 배초향과 코끼리마늘의 열수추출물 5중량부를 포함하되,상기 발효 사료는 귀리, 보리, 맥주박 및 버섯배지를 1:1:1:1 중량비로 혼합하고, 이에 맥주 액상 효모를 접종하여 발효한 것이며,상기 욱리인은 0.1~1mm의 크기로 분쇄한 것이고,상기 무화과 잎 발효물은 무화과 잎에 락토바실러스 카제이(Lactobacillus Casei)를 접종한 후, 35℃에서 7일간 발효한 것이며,상기 배초향과 코끼리마늘의 열수추출물은 배초향의 잎과 코끼리마늘을 1:1 중량비로 혼합한 후, 이에 10중량배의 물을 가하고, 90℃로 7시간 가열, 냉각, 여과, 감압농축 및 동결건조한 것임을 특징으로 하는 한우용 사료 조성물., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

619/1150 Row 619: application_number: 1020200021373, combined_string: invention_title: IoT제어 및 AC-LED 디밍시스템을 구비한 에너지절감형 스마트 축산사료재배공장 abstract: 본 발명에서는 겨울철 소등 가축들을 위한 목초를 대신할 신선 조사료를 제공하는 조사료 스마트팜 장치를 제공하고자 한다. 이를 위하여, 도어를 구비한 컨테이너; 및 상기 컨테이너 내부 좌우로 배치된 다단재배베드; 및 상기 다단재배베드 중앙에 구비된 통로; 및 상기 다단재배베드의 칸칸이 구비된 관수노즐 및 LED 조명부; 및 상기 다단재배베드에 구비된 재배트레이; 및 상기 컨테이너에 구비된 2개 이상의 온습도 센서; 및 상기 관수노즐과 연결되고, 상기 컨테이너 외부에 구비된 수조; 및 상기 수조를 냉각시키기 위한 냉각기; 및 상기 수조에서 나온 물의 온도를 높이기 위한 가열부; 및 상기 LED 조명부의 광량을 조절하기위한 광제어부를 구비한 것을 특징으로 하는 IoT제어 및 AC-LED 디밍시스템을 구비한 에너지절감형 스마트 축산사료재배공장을 제공한다.상기와 같은 구성에 의하여, 20피트 컨테이너의 경우 매일 500Kg씩 새싹보리를 수확할 수 있고, 40피트 컨테이너의 경우 매일 1000Kg씩 새싹보리를 수확할 수 있는 IoT제어 및 AC-LED 디밍시스템을 구비한 에너지절감형 스마트 축산사료재배공장을 개발하였다. 상기와 같은 장치에 의하여 연 중 매일 500~1000Kg의 신선 조사료를 생산할 수 있는 수단을 제공함으로써, 목초 조차 재배할 수 없는 환경에서 소 등의 가축을 사육할 수 있는 수단을 제공하는 효과가 있다. claims: 도어를 구비한 컨테이너; 및상기 컨테이너 내부 좌우로 배치된 다단재배베드; 및상기 다단재배베드 중앙에 구비된 통로; 및상기 다단재배베드의 칸칸이 구비된 관수노즐 및 LED 조명부; 및상기 다단재배베드에 구비된 재배트레이; 및상기 컨테이너에 구비된 2개 이상의 온습도 센서; 및상기 관수노즐과 연결되고, 상기 컨테이너 외부에 구비된 수조; 및상기 수조를 냉각시키기 위한 냉각기; 및상기 수조에서 나온 물의 온도를 높이기 위한 가열부; 및상기 LED 조명부의 광량을 조절하기위한 광제어부를 구비한 것을 특징으로 하는 IoT제어 및 AC-LED 디밍시스템을 구비한 에너지절감형 스마트 축산사료재배공장., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

620/1150 Row 620: application_number: 2020200000513, combined_string: invention_title: 카프스트롱 - 음수용 abstract: 본 고안은 송아지를 사육하는 농가에 설치하여 송아지에게 우유, 물 등을원활하게 공급하는데에 목적이 있다.또한, 수시로 젖꼭지를 소독하기 위해 젖꼭지 부분의 분리를쉽게 할 수 있도록 설계 하였다.파이프에 고정하여 사용하는 파이프걸이(1),단단히 고정할 수 있는 장착끈구멍(2,3),바닥에 두었을 때 수평이 유지될 수 있는 하부지지대(5),편리하게 들어 이동이 용이한 손잡이(6),D형볼트(7), O형너트(8), 젖꼭지(9)와 와셔를 결합하여 사용하는 것을 포함하여서 제작된 것이다. claims: 카프스트롱 - 음수용 {CALF STRONG} 은 파이프에 고정하여 사용하는 파이프걸이(1), 단단히 고정할 수 있는 장착끈구멍(2,3),바닥에 두었을 때 고정할수 있는 하부지지대(5),편리하게 들어 이동이 용이한 손잡이(6),D형볼트(7), O형너트(8), 젖꼭지(9)와 와셔를 결합하여 사용하는 것을 특징으로하는 카프스트롱 - 음수용 {CALF STRONG} 이다., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

621/1150 Row 621: application_number: 1020200017628, combined_string: invention_title: 육질 개선 및 단기비육용 사료, 및 이를 이용한 한우의 비육방법 abstract: 본 발명은 육질 개선 및 단기비육용 사료, 및 이를 이용한 한우의 비육방법에 관한 것이다. 보다 상세하게는 본 발명은 한우의 사양 단계별로 최적의 사료를 개발하고, 이를 한우에 급여함으로써 한우의 육질 개선 및 비육기간을 단축시키고, 사료비용을 절감할 수 있는, 육질 개선 및 단기비육용 사료, 및 이를 이용한 한우의 비육방법에 관한 것이다. claims: 한우 거세우의 사양 단계를 6 ~ 13 개월령, 14 ~ 22 개월령 및 23 ~ 28 개월령으로 나누어 급여하는 사료로서, 상기 6 ~ 13 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 3 ~ 5 : 7 ~ 5의 중량% 비율로 포함되고, 상기 14 ~ 22 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 1 ~ 3 : 9 ~ 7의 중량% 비율로 포함되며, 상기 23 ~ 28 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 0.5 ~ 1.5 : 9.5 ~ 8.5의 중량% 비율로 포함되는, 한우 거세우의 육질 개선 및 단기비육용 사료.한우 거세우의 사양 단계를 6 ~ 13 개월령, 14 ~ 22 개월령 및 23 ~ 28 개월령으로 나누어 단계별로 영양성분이 상이한 사료를 한우 거세우에게 급여하는 한우거세우의 비육방법으로서,상기 6 ~ 13 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 3 ~ 5 : 7 ~ 5의 중량% 비율로 포함되고, 상기 14 ~ 22 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 1 ~ 3 : 9 ~ 7의 중량% 비율로 포함되며, 상기 23 ~ 28 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 0.5 ~ 1.5 : 9.5 ~ 8.5의 중량% 비율로 포함되는, 한우 거세우의 비육방법.한우 거세우의 사양 단계를 6 ~ 13 개월령, 14 ~ 22 개월령 및 23 ~ 28 개월령으로 나누어 단계별로 영양성분이 상이한 사료를 한우 거세우에게 급여하는 한우 거세우의 비육기간 단축방법으로서,상기 6 ~ 13 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 3 ~ 5 : 7 ~ 5의 중량% 비율로 포함되고, 상기 14 ~ 22 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 1 ~ 3 : 9 ~ 7의 중량% 비율로 포함되며, 상기 23 ~ 28 개월령에서 급여하는 사료는 건물에서의 조사료 및 농후사료가 0.5 ~ 1.5 : 9.5 ~ 8.5의 중량% 비율로 포함되는, 한우 거세우의 비육기간 단축 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

622/1150 Row 622: application_number: 1020200015048, combined_string: invention_title: 발전소 감시 시스템 및 방법 abstract: 실시예에 따르면, 발전소내에 설치된 촬영 장치로부터 영상 데이터를 수집하는 통신부; 발전소 내부를 촬영한 영상 데이터를 입력층으로 하여, 사육장 내부 영상과 객체간의 상관관계를 학습하고, 객체를 검출한 영상 데이터가 출력층이 되도록 학습된 제1뉴럴 네트워크를 포함하는 제1처리부; 및 상기 객체를 검출한 영상 데이터를 입력층으로 하여, 상기 객체와 객체의 위험 상태간의 상관관계를 학습하고, 위험 상태 판단 결과가 출력층이 되도록 학습된 제2뉴럴 네트워크를 포함하는 제2처리부를 포함하는 발전소 감시 장치를 제공한다. claims: 발전소내에 설치된 촬영 장치로부터 영상 데이터를 수집하는 통신부;발전소 내부를 촬영한 영상 데이터를 입력층으로 하여, 사육장 내부 영상과 객체간의 상관관계를 학습하고, 객체를 검출한 영상 데이터가 출력층이 되도록 학습된 제1뉴럴 네트워크를 포함하는 제1처리부; 및상기 객체를 검출한 영상 데이터를 입력층으로 하여, 상기 객체와 객체의 위험 상태간의 상관관계를 학습하고, 위험 상태 판단 결과가 출력층이 되도록 학습된 제2뉴럴 네트워크를 포함하는 제2처리부를 포함하는 발전소 감시 장치.발전소 내부에 배치되어 발전소 내부 영상을 촬영하는 촬영 장치;상기 촬영 장치로부터 영상 데이터를 수집하는 통신부;발전소 내부를 촬영한 영상 데이터를 입력층으로 하여, 사육장 내부 영상과 객체간의 상관관계를 학습하고, 객체를 검출한 영상 데이터가 출력층이 되도록 학습된 제1뉴럴 네트워크를 포함하는 제1처리부; 및상기 객체를 검출한 영상 데이터를 입력층으로 하여, 상기 객체와 객체의 위험 상태간의 상관관계를 학습하고, 위험 상태 판단 결과가 출력층이 되도록 학습된 제2뉴럴 네트워크를 포함하는 제2처리부를 포함하는 발전소 감시 시스템.통신부가 발전소내에 설치된 촬영 장치로부터 영상 데이터를 수집하는 단계;제1처리부가 제1뉴럴 네트워크를 이용하여 발전소 내부를 촬영한 영상 데이터를 입력층으로 하여, 사육장 내부 영상과 객체간의 상관관계를 학습하고, 객체를 검출한 영상 데이터가 출력층이 되도록 학습하는 단계; 및제2처리부가 제2뉴럴 네트워크를 이용하여 상기 객체를 검출한 영상 데이터를 입력층으로 하여, 상기 객체와 객체의 위험 상태간의 상관관계를 학습하고, 위험 상태 판단 결과가 출력층이 되도록 학습하는 단계를 포함하는 발전소 감시 방법.제17항에 따른 발전소 감시 방법을 컴퓨터에 실행시키기 위한 프로그램이 기록되어 있는 컴퓨터에서 판독 가능한　기록매체., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

623/1150 Row 623: application_number: 1020200009924, combined_string: invention_title: 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템 abstract: 본 발명은 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템에 관한 것으로, 복수 개의 비대칭 스테레오 카메라가 장착된 모바일 기기로 스테레오 영상을 촬영하여 가축의 무게를 측정하기 위한 것이다.이를 위하여 본 발명은, 피측정 가축의 2D 스테레오 영상을 촬영하는 스테레오 영상 촬영부, 2D 스테레오 영상에 심층학습 인공지능기법을 적용하여 3D 점운 정보를 획득하는 3D 점운 생성부, 3D 점운 처리를 통해 피측정 가축의 유효 데이터를 추출하고 흉위 및 유효 체장을 예측하여 체중을 산출하는 체중 산출부, 산출된 체중정보를 최대수익일 예측모델에 적용하여 해당 가축의 최대 수익일을 예측하는 최대수익일 예측부, 산출된 가축의 체중정보를 각 개체별 아이디와 일자별로 구분하여 저장하는 가축 DB, 및 산출된 각 가축의 개체별 체중정보 및 최대수익일 예측정보가 포함된 그래픽 기반의 인터페이스를 출력하는 디스플레이부를 포함하여, 3D 영상 촬영장비가 구비되어 있지 않은 모바일 기기에서도 비접촉 방식으로 가축의 체중을 간단하게 측정하고 개체별 체중 정보와 최대 수익일 예측정보 등을 확인하여 축산 농가의 시간적, 인력적 및 비용적인 문제를 해결할 수 있게 한다. claims: 피측정 가축의 2차원(2D) 스테레오 영상을 촬영하여 3D 점운 생성부(120)에 전달하는 스테레오 영상 촬영부(110);상기 스테레오 영상 촬영부(110)에서 전달되는 피측정 가축의 2D 스테레오 영상에 심층학습 인공지능기법을 적용하여 3차원(3D) 점운(Point Cloud) 정보를 획득하여 체중 산출부로 전달하는 3D 점운 생성부(120);상기 3D 점운 생성부(120)에서 전달되는 데이터들의 3D 점운 처리를 통해 피측정 가축의 유효 데이터를 추출하고 흉위 및 유효 체장을 예측하여 체중을 산출하며 산출된 체중 정보를 최대 수익일 예측부(140)와 가축 DB(150) 및 디스플레이부(160)로 전달하는 체중 산출부(130);상기 체중 산출부(130)에서 산출된 체중정보를 기설정된 최대수익일 예측모델에 적용하여 해당 가축의 체중이 최대등급에 도달하는 시기, 실질수익이 발생되는 시기를 포함하는 가축별 최대 수익일 예측정보를 산출하는 최대수익일 예측부(140);상기 체중 산출부(130)에서 산출된 가축의 체중정보를 각 개체별 아이디와 일자별로 구분하여 저장하는 가축 DB(150); 및상기 체중 산출부(130) 또는 최대수익일 예측부(140)에서 산출된 각 가축의 개체별 체중정보 또는 최대수익일 예측정보가 포함된 그래픽 기반의 인터페이스를 출력하는 디스플레이부(160);를 포함하여 구성되고,상기 스테레오 영상 촬영부(110)는,상이한 광학변수를 갖는 복수 개의 비대칭 스테레오 카메라로서 근접 객체를 촬영할 때와 원거리 객체를 촬영할 때에 최적의 효과를 낼 수 있도록 초점거리와 조리개의 성능이 비대칭적으로 다르게 설치되는 쌍안 카메라 또는 3중 카메라 중의 어느 하나로 이루어지고, 쌍안 카메라 또는 3중 카메라는 광학축과 이미징 평면이 각각 평행상태를 유지하고 이미징 평면은 동일 평면상에서 구성되며,상기 3D 점운 생성부(120)는,인코더 네트워크; 컴퓨터 비젼 처리에서 필요한 포즈의 추정, 객체 영역화 및 돌출점(salience) 탐지와 같은 다중스케일 표현기능을 수행하는 Res2Net 블록; 및 디코더 네트워크;로 구성되는 딥러닝 네트워크 모델을 통해 시차맵을 예측하고, 예측된 시차맵과 비대칭 스테레오 카메라의 고유 파라미터를 사용하여 깊이정보(Z)를 계산하여 객체의 공간좌표 P(X,Y,Z)를 구하되, 좌측과 우측에 두 대의 비대칭 스테레오 카메라가 설치되어 있고, 좌측 카메라의 광학축 C1과 우측 카메라의 광학축 C2, 두 카메라의 이격 거리는 B, 좌측 카메라의 초점 거리 f1과 좌측 카메라의 초점거리 f2(여기서 f1 = k×f2 관계 유지), 객체 상의 공통점으로서 좌측 카메라에 나타나는 이미지상의 점 P1(x1,y1)과 우측 카메라에 나타나는 이미지 상의 점 P2(x2,y2), 및 좌측 카메라의 좌표계의 원점을 공간 좌표계의 원점으로 가정한 경우,삼각법에 의하여 두 카메라에 나타나는 이미지상의 점 P1(x1,y1)과 점 P2(x2,y2)은,에 의해 정의되며. 두 카메라의 이미지가 정확하게 정합된 경우, P1과 P2 사이의 시차(disparity) d는,에 의해 정의되고,따라서 깊이정보 Z는, 에 의해 정의되며, 최종적으로 스테레오 영상의 각 화소점P1(x1,y1),P2(x2,y2)으로부터 공간좌표계의 점운 P(X,Y,Z)는, 또는에 의해 정의되는 것을 특징으로 하는 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템.제1항에 있어서, 상기 체중 산출부(130)는,상기 3D 점운 생성부(120)로부터 전달되는 데이터들의 점운(point cloud) 처리를 통해 평면적 특성을 나타내는 점운들을 제거하여 피측정 가축의 표면 점운들을 추출하는 3D 점운 처리부(131);상기 3D 점운 처리부(131)에서 추출된 피측정 가축의 표면 점운들로부터 피측정 가축 이외의 점운들을 제거하여 피측정 가축의 순수 표면 점운들만을 추출하는 3D 가축 영역 추출부(132);상기 3D 가축 영역 추출부(132)에서 추출된 피측정 가축의 순수 표면 점운들로부터 앞다리의 뒷쪽 위에 있는 몸통의 둘레 길이로 정의하여 피측정 가축의 흉위 G를 측정하는 흉위 측정부(133);상기 흉위를 측정한 부분의 맨 위 상단에 분포하는 점 A와 꼬리부분의 맨위 상단에 분포하는 점 C 사이의 절대 거리를 산출하여 피측정 가축의 척추부의 유효체장 를 측정하는 유효체장 측정부(134); 및상기 흉위 측정부(133)와 유효체장 측정부(134)에서 각각 측정된 피측정 가축의 흉위 G와 유효체장 를 반영하여 주어진 G 와 에 따른 해당 피측정 가축의 실체중을 계산하고 상기 계산된 피측정 가축의 실체중정보를 최대 수익일 예측부(140)와 가축 DB(150) 및 디스플레이부(160)에 전달하는 회귀 분석부(135);를 포함하여 구성되는 것을 특징으로 하는 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템.제1항에 있어서, 상기 최대수익일 예측부(140)는,현재 체중에 따른 가격(Co), 최적 등급(tp)에 도달하는 시기까지 요구되는 표준 사료 소모량의 가격(fe), 최적 등급에 도달하는 시기까지 요구되는 평균 시설유지비와 평균 인건비의 합(m, 여기서 평균 시설유지비는 총 시설유지비를 가축의 평균사육두수로 나눈 금액이며, 평균 인건비는 총 인건비를 가축의 평균사육두수로 나눈 금액임)을 이용하여 최대 수익일을 예측할 수 있는 최대 수익일 예측 모델을 정립하며,상기 최대 수익일 예측 모델 상의 생산성 곡선(pf)은,으로 산출되는 것을 특징으로 하는 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템.제1항에 있어서, 상기 디스플레이부(160)는,가축의 표준 사료 소모량과 성장량의 관계를 이용하여 최대 수익일을 예측할 수 있는 최대 수익일 예측 모델을 통해 체중 측정이 이루어진 가축이 최대 등급에 해당되는 적정체중에 도달하는 시기(최대수익 도달시기), 및 실질적인 수익이 발생되는 시기를 예측하여 창출 가능한 이익을 정량적으로 가시화하여 제시하는 인터페이스를 제공하는 것을 특징으로 하는 비대칭 스테레오 카메라를 이용한 비접촉식 모바일 가축 체중 측정시스템., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

624/1150 Row 624: application_number: 1020200005041, combined_string: invention_title: 동물 후각을 자극하는 동물 사육 로봇 abstract: 본 발명은 동물 후각을 자극하는 먹이 냄새를 배출하는 먹이 냄새 배출구가 형성된 먹이 배출부를 장착하여 동물의 예민한 후각을 자극하여, 로봇의 작동이 중단되는 기간에도 동물의 후각을 자극하여 동물의 관심을 유도하고 로봇을 접촉하는 행동을 유발하여 접촉에 대한 성과 보상으로서 먹이를 배출하는 동물 사육 로봇을 제공한다. 본 발명은 전원 소모가 많은 각종 감지 센서나 음향 발생 장치의 사용을 배제하여 전원 소모를 최소화하여 로봇의 원격 관리 가동 가능 시간을 최대화하면서 먹이 냄새 배출을 위한 수단을 갖추어 동물의 자발적 접근과 접촉을 촉진할 수있는 동물 사육 로봇을 제공한다. claims: 외부의 원격 조종 프로그램에 의하여 인터넷을 통하여 조종되거나 또는 로봇에 입력된 내장 프로그램에 의해서 작동하며 동물 먹이 보관함이나 먹이 배출부가 장착된 동물 사육 로봇에 있어서, 상기 먹이 보관함이나 먹이 배출부에 하나 이상의 먹이 냄새 배출구가 형성되어 있는 것을 특징으로 하는, 동물 사육 로봇., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

625/1150 Row 625: application_number: 1020190172717, combined_string: invention_title: 반추동물용 해바라기 조사료, 이의 제조방법 및 해바라기 조사료를 이용한 반추동물 사육방법 abstract: 과제: 해바라기 특유의 냄새를 제어하고 반추동물이 섭취하기 좋으며 영양이 풍부한 해바라기 조사료 및 이를 제조하는 방법을 제공하는 것.과제해결방법: 해바라기의 곤포 사일리지 조제처리시 발효 균주, 좀 더 구체적으로는 락토바실러스속 미생물 및 피디오코커스속 미생물 중 하나 이상을 가하여 해바라기를 발효, 숙성함으로써 다른 재료를 가하지 않고도 단백질, 지방, 회분 등 영양성분이 풍부한 고품질의 조사료를 조제하였으며, 이 조사료를 급여하는 경우 한우가 거부감 없이 잘 섭취하였고, 한우 우육의 올레산 함량이 현저히 증가하였으며, 체중 증가도 현저하였다. claims: 만개 후 10일 내에 수확한, 건조중량 100g 당 조단백질이 10g 이상이고 조섬유가 25g 이상인 절단한 해바라기 잎과 줄기와 꽃에 발효 균주를 가하여 곤포 사일리지에서 발효, 숙성한 반추동물용 해바라기 조사료.1) 건조중량 100g 당 조단백질이 10g 이상이고 조섬유가 25g 이상인 해바라기 잎과 줄기와 꽃을 만개 후 10일 내에 수확하여 적정 크기로 절단하는 단계;2) 절단한 해바라기 잎과 줄기와 꽃에 락토바실러스속 발효 균주 및 피디오코커스속 발효 균주 중 하나 이상을 가하는 단계;3) 상기 발효 균주를 가한 해바라기 잎과 줄기와 꽃을 곤포 사일리지로 조제하고 발효하는 단계; 및4) 상기 발효된 해바라기 곤포 사일리지를 숙성하는 단계;를 포함하는 반추동물용 해바라기 조사료 제조방법.청구항 1 내지 청구항 6 중 어느 하나의 반추동물용 해바라기 조사료를 급여하는 해바라기 조사료를 이용한 반추동물 사육방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

626/1150 Row 626: application_number: 1020190167338, combined_string: invention_title: 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법 abstract: 본 발명은 마우스와 같은 실험 동물 배양을 위한 사육 케이지 내부로의 흡기 또는 외부로의 배기시 흡기관 및 배기관의 크기를 반영하고 블로어의 회전수를 조절 가능하여 최적의 사육 환경을 조성하고, 사육케이지 내부의 공기 정보에 맞추어 사육케이지 내부로 유입되거나 배기되는 공기의 양을 최적 상태로 조절하기 위한 블로어 최적 제어를 가능하게 하는 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법에 관한 것이다.본 발명의 실시예인 외부 공기가 급기되는 흡기관과 내부 공기가 배기되는 배기관과, 상기 흡기관과 연결되는 흡기부(제 1 모터와 제 1 블로어 구비)와, 상기 배기관과 연결되는 배기부(제 2모터와 제 2블로어 구비)와, 상기 흡기관 내부에 설치된 유속 센서와, 상기 배기관 내부에 설치되어 배기되는 공기의 정보를 측정하는 공기 정보 측정용 센서와, 상기 제 1 및 제 2 모터의 듀티비를 제어하는 제어부를 구비하는 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법은,(a) 설정하고자 하는 설정 ACH를 제어부로 전송하는 단계;(b) 상기 설정 ACH에 대응하여, 상기 흡기관으로 급기되는 공기 유량을 상기 제어부에서 계산하는 단계;(c) 상기 공기 유량에 대응하는 제 1 공기 유속을 상기 제어부에서 계산하는 단계;(d) 상기 제어부에서 상기 제 1 공기 유속에 대응하는 상기 제 1 블로어의 RPM을 계산하는 단계;(e) 상기 제어부가 상기 제 1 블로어의 상기 RPM 유지를 위하여 상기 제 1 블로어를 제어하는 상기 제 1 모터의 듀티비를 계산하는 단계;(f) 상기 제 1 모터를 작동시키는 단계;(g) 상기 제 1 모터와 10% 차이가 나는 듀티비를 갖도록 상기 제 2 모터를 작동시키는 단계; (h) 상기 흡기관 내부에 설치된 유속 센서를 통하여 상기 흡기관으로 급기되는 제 2 공기 유속이 측정되어 상기 제어부로 전송되는 단계; (i) 상기 제어부에서 상기 제 2 공기 유속에 대응하는 제 2 공기 유량을 계산하는 단계;(j) 상기 제어부에서 상기 제 2 공기 유량에 따라 계산되는 측정치인 측정 ACH를 도출하고 상기 설정 ACH와의 차이를 비교하는 단계;(k) 상기 설정 ACH와 상기 측정 ACH의 차이가 제로로 수렴할 때까지 상기 단계 (f) ~ 단계 (j)를 반복 실시하되, 상기 단계 (f)의 상기 제 1 모터 작동을 위한 듀티비를 소정 수치 증가 또는 감소시킨 후 반복 실시하는 단계;로 이루어지는 것을 특징으로 한다.본 발명의 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법을 실시하는 경우, 흡기관 배기관의 크기 및 사육 케이지 내부 공기 정보에 따라 사육 케이지 내부의 공기 환경을 최적으로 유지시킬 수 있다는 이점이 있다. claims: 외부 공기가 급기되는 흡기관과 내부 공기가 배기되는 배기관과, 상기 흡기관과 연결되는 흡기부(제 1 모터와 제 1 블로어 구비)와, 상기 배기관과 연결되는 배기부(제 2모터와 제 2블로어 구비)와, 상기 흡기관 내부에 설치된 유속 센서와, 상기 배기관 내부에 설치되어 배기되는 공기의 정보를 측정하는 공기 정보 측정용 센서와, 상기 제 1 및 제 2 모터의 듀티비를 제어하는 제어부를 구비하는 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법으로서,(a) 설정하고자 하는 설정 ACH를 제어부로 전송하는 단계;(b) 상기 설정 ACH에 대응하여, 상기 흡기관으로 급기되는 공기 유량을 상기 제어부에서 계산하는 단계;(c) 상기 공기 유량에 대응하는 제 1 공기 유속을 상기 제어부에서 계산하는 단계;(d) 상기 제어부에서 상기 제 1 공기 유속에 대응하는 상기 제 1 블로어의 RPM을 계산하는 단계;(e) 상기 제어부가 상기 제 1 블로어의 상기 RPM 유지를 위하여 상기 제 1 블로어를 제어하는 상기 제 1 모터의 듀티비를 계산하는 단계;(f) 상기 제 1 모터를 작동시키는 단계;(g) 상기 제 1 모터와 10% 차이가 나는 듀티비를 갖도록 상기 제 2 모터를 작동시키는 단계; (h) 상기 흡기관 내부에 설치된 유속 센서를 통하여 상기 흡기관으로 급기되는 제 2 공기 유속이 측정되어 상기 제어부로 전송되는 단계; (i) 상기 제어부에서 상기 제 2 공기 유속에 대응하는 제 2 공기 유량을 계산하는 단계;(j) 상기 제어부에서 상기 제 2 공기 유량에 따라 계산되는 측정치인 측정 ACH를 도출하고 상기 설정 ACH와의 차이를 비교하는 단계;(k) 상기 설정 ACH와 상기 측정 ACH의 차이가 제로로 수렴할 때까지 상기 단계 (f) ~ 단계 (j)를 반복 실시하되, 상기 단계 (f)의 상기 제 1 모터 작동을 위한 듀티비를 소정 수치 증가 또는 감소시킨 후 반복 실시하는 단계;로 이루어지는 것을 특징으로 하는 사육 케이지 내부의 공기 정보 맞춤형 공조 제어방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

627/1150 Row 627: application_number: 1020190166844, combined_string: invention_title: 축사용 스탄존 및 그 설치방법 abstract: 본 발명은 소 사육농가에서 예방접종 및 검사시 쉽게 보정하여 소 개체관리를 하거나, 사료 급여시에 활동 반경을 제한하도록 하는 스탄존의 사용수명을 크게 연장하고 증설을 용이하게 할 수 있는 축사용 스탄존 및 그 설치방법에 관한 것이다.즉, 본 발명은 상,하부가로대 사이에 수직으로 설치되는 다수의 지지대, 상기 각 지지대와 지지대의 사이에 결합되고 일정각도로 절곡하여 기울어진 고정대, 상기 고정대에 힌지 결합되고 힌지축을 중심으로 수직 또는 기울어지게 회동되는 회동봉, 상기 상부가로대의 상측에 설치되어 회동봉이 수직으로 세워졌을 때 이를 규제하는 잠금수단이 구비되어 있는 제어봉으로 구비되는 것을 포함하며, 상기 상,하부가로대와 지지대의 연결부분은 양측으로 분할된 T형 클립부재에 의해 결합되고, 상기 각 지지대와 지지대의 사이에 결합되고 일정각도로 절곡하여 기울어진 고정대와 지지대가 맞닿는 부분은 양측으로 분할된 T형 더블클립부재에 의해 결합되는 구성으로 조립이 이루어지는 축사용 스탄존 및 그 설치방법을 특징으로 한다. claims: 상,하부가로대(10)(20) 사이에 수직으로 설치되는 다수의 지지대(30), 상기 각 지지대(30)와 지지대(30)의 사이에 결합되고 일정각도로 절곡하여 기울어진 고정대(40), 상기 고정대(40)에 힌지(42) 결합되고 힌지축을 중심으로 수직 또는 기울어지게 회동되는 회동봉(50), 상기 상부가로대(10)의 상측에 설치되어 회동봉(50)을 규제하는 잠금수단(62)이 구비되어 있는 제어봉(60)으로 구비되는 것을 포함하며,상기 상,하부가로대(10)(20)와 지지대(30)의 연결부분은 양측으로 분할된 T형 클립부재(100)에 의해 결합되되 상기 T형 클립부재(100)는 수평결합부(110)와 수직결합부(120)가 구비되어 상기 수평결합부(110)는 상부가로대(10) 또는 하부가로대(20)에 감싸듯이 결합되고, 상기 수직결합부(120)는 지지대(30)와 감싸듯이 결합되는 구성과,상기 각 지지대(30)와 지지대(30)의 사이에 결합되고 일정각도로 절곡하여 기울어진 고정대(40)와 지지대(30)가 맞닿는 부분은 양측으로 분할된 T형 더블클립부재(100a)에 의해 결합되되 상기 T형 더블클립부재(100a)는 수평결합부(110)와 수직결합부(120)가 구비되어 상기 수평결합부(110)는 상부가로대(10)에 감싸듯이 결합되고, 상기 수직결합부(120)는 측부 연장단면(124)에 의해 병렬 연결되어 구비되는 한 쌍의 수직결합부(120)에 지지대(30) 및 고정대(40)를 각각 감싸듯이 결합되는 구성으로 조립이 이루어지도록 한 것을 특징으로 하는 축사용 스탄존.수평결합부(110)와 수직결합부(120)가 구비된 T형 클립부재(100)와, 수평결합부(110)와 수직결합부(120)는 측부 연장단면(124)에 의해 병렬 연결되어 있는 한 쌍의 수직결합부(120)를 가진 T형 더블클립부재(100a)를 각각 구비한 다음 상,하부가로대(10)(20)가 평행으로 서로 대향되게 배치하는 단계; 상기 하부가로대(20)에 양측으로 T형 클립부재(100)의 수평결합부(110)를 결합하고, T형 클립부재(100)의 수직결합부(120)에 지지대(30) 및 고정대(40)의 하단부를 각각 결합하는 단계; 상기 T형 클립부재(100)의 결합구멍(130)에 체결구(140)를 끼워 체결하는 단계: 상기 상부가로대(10)에 또 다른 T형 클립부재(100) 및 T형 더블클립부재(100a)의 수평결합부(110)를 결합하고, T형 더블클립부재(100a)에 구비된 한 쌍의 수직결합부(120)에 지지대(30) 및 고정대(40)의 상단부를 각각 결합하는 단계; 상기 T형 클립부재(100) 및 T형 더블클립부재(100a)의 결합구멍(130)에 체결구(140)를 끼워 체결하는 단계;를 포함하여서 됨을 특징으로 하는 축사용 스탄존의 설치방법., Ltext: 농업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

628/1150 Row 628: application_number: 1020190158098, combined_string: invention_title: 공주알밤한우 건강육 abstract: 본 발명은 공주알밤한우 건강육에 관한 것으로, 더욱 상세하게는 공주에서 생산된 밤에서 분리된 율피를 이용한 육질개선용 소 사료 조성물, 이를 급여하는 소 사육방법 및 이를 급여한 소로부터 생산되는 우육에 관한 것이다.이에 따라 가공되는 밤 함량의 약 25%를 차지하는 율피를 버리지 않고 재활용할 수 있어 자원의 낭비를 막을 수 있으며, 경제적인 가치가 매우 높다. 또한, 화학합성사료가 아닌 자연에서 분리되는 율피를 이용하여 친환경적으로 소의 사육 환경을 개선할 수 있다. 본 발명은 소의 육질을 개선할 수 있고, 구체적으로 아미노산과 불포화지방산의 함량을 증진시키며, 고기의 맛 역시 개선시킬 수 있다. claims: 율피를 포함하는 것을 특징으로 하는 육질개선용 소 사료 조성물.청구항 1 내지 3 중 어느 한 항에 따른 소 사료 조성물을 급여하는 단계를 포함하는 것을 특징으로 하는 소 사육방법.청구항 1 내지 3 중 어느 한 항에 따른 육질개선용 소 사료 조성물을 급여한 소로부터 생산되는 것을 특징으로 하는 우육., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

629/1150 Row 629: application_number: 1020190156532, combined_string: invention_title: 한우 대사물질 판별용 조성물 및 이를 이용한 한우 교배 효율 판별 방법 abstract: 본 발명은 한우 대사물질 판별용 조성물 및 이를 이용한 한우 교배 효율 판별 방법에 관한 것으로, 암소의 혈중에 존재하는 대사물질 중, 번식효율과 관련된 혈중 요소 질소(blood urea nitrogen, BUN) 또는 혈중 에너지 인자를 검출에 효과적이다. 이에, 한유 교배 효율을 판별할 수 있고, 임신우 또는 비임신우의 급여 조절, 수정란의 채란, 인공 수정 및 수태율을 위한 식이 조절을 판별할 수 있는 바, 목축 및 육우 산업 전반에 활용이 가능하다. claims: 한우의 혈중 요소 질소(blood urea nitrogen, BUN) 또는 혈중 에너지 인자를 검출하는 시약을 포함하는, 한우 대사물질 판별용 조성물.제 1항의 조성물을 포함하는 한우 대사물질 판별용 키트.(1) 대상 한우의 시료를 수득하는 단계;(2) 상기 (1)의 시료에 제8항의 키트를 이용하여 혈중 대사물질의 농도를 판별하는 단계; 및(3) 상기 한우의 혈중 대사 물질을 대조 한우와 비교하는 단계;를 포함하는, 한우 교배 효율 판별 방법.(1) 대상 한우의 시료를 수득하는 단계;(2) 상기 (1)의 시료에 제8항의 키트를 이용하여 혈중 대사물질의 농도를 판별하는 단계; 및(3) 상기 한우의 혈중 대사 물질을 대조 한우와 비교하는 단계; 를 포함하는, 한우의 식이 조절을 위한 판별 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

630/1150 Row 630: application_number: 1020190152331, combined_string: invention_title: 축산폐수 처리장치 abstract: 본 발명은 축산폐수 처리장치에 관한 것으로, 축산폐수를 공급받아 침전물을 분리하는 침전조(100); 상기 침전조(100) 내에서 침전물과 분리된 상층수를 공급받아 1차 여과하도록 패각소성체를 포함하는 패각필터가 내장된 제1여과기(200); 및 상기 제1여과기(200)를 통하여 1차 여과된 폐수를 공급받아 2차 여과하도록 목재 톱밥을 포함하는 목재필터가 내장된 제2여과기(300);를 포함하여 소, 돼지, 닭 등의 축산용 가축 사육시 발생하는 축산폐수를 매우 신속하고 효율적으로 정화시킬 수 있는 축산폐수 처리장치에 관한 것이다. claims: 축산폐수를 공급받아 침전물을 분리하는 침전조(100);상기 침전조(100) 내에서 침전물과 분리된 상층수를 공급받아 1차 여과하도록 패각소성체를 포함하는 패각필터가 내장된 제1여과기(200);상기 제1여과기(200)를 통하여 1차 여과된 폐수를 공급받아 2차 여과하도록 목재 톱밥을 포함하는 목재필터가 내장된 제2여과기(300);상기 침전조(100)에 연결되어 침전조(100) 하부에 침전된 침전물을 수거하는 침전물 수거부(400); 및상기 제2여과기(300)를 통하여 2차 여과된 폐수를 공급받아 가열하는 가열장치(500);를 포함하며,상기 패각소성체는 굴패각을 800 내지 1,000℃의 온도로 소성한 것이며,상기 목재 톱밥은 소나무 톱밥과 참나무 톱밥을 소나무 톱밥 100중량부당 참나무 톱밥 300 내지 400중량부의 비율로 혼합한 것이며,상기 침전물 수거부(400)는침전물과 상층수간의 경계를 차단하여 이들을 공간적으로 폐쇄하여 분리하는 층분리기(410); 상기 층분리기(410)가 침전물과 상층수간의 경계를 차단하면 회전작동하여 침전물을 원심력에 의하여 배출공(420)으로 배출시키는 회전체(430); 상기 배출공(420)으로 배출된 침전물을 수거하여 건조하는 건조기(440); 및 상기 건조기에서 건조된 침전물을 분쇄하는 분쇄기(441);를 포함하고,상기 가열장치(500)는상기 제2여과기(300)를 통하여 2차 여과된 폐수를 공급받아 악취를 제거하기 위하여 표면에 송진 피막이 형성된 볏짚 분쇄물을 투입하여 혼합하고 60 내지 70℃로 가열하는 제1가열기(510); 상기 제1가열기(510)에서 가열된 폐수를 공급받아 잔류 악취를 추가로 제거하기 위하여 흑운모 분말을 투입하여 혼합하고 80 내지 90℃로 가열하는 제2가열기(520); 다수의 구리(Cu)판(531)이 내부에 설치되며 상기 제2가열기(520)에서 가열된 폐수를 공급받아 상기 구리판(531)을 가열함으로써 폐수를 60 내지 70℃로 가열하는 제3가열기(530);를 포함하며,상기 침전조(100) 내에는 초음파진동발생기(110)가 구비되며, 상기 초음파진동발생기(110)는 200 내지 300㎑의 주파수를 갖는 초음파를 1초 단위로 주파수를 2㎑씩 연속적으로 변경하면서 폐수의 상층수에 인가하는 것을 특징으로 하는 축산폐수 처리장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

631/1150 Row 631: application_number: 1020190145471, combined_string: invention_title: 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템 abstract: 본 발명은 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템으로서 중앙의 서버를 통제하는 관리자가 원격지에 다수 분포되어 있는 농장의 축사에 각각 수용되어 있는 개체별 소 또는 돼지 등 가축의 발육상태 등을 실시간 제공받으며 직접 확인하여, 양방향 송수신되어 제공되는 개체별 정보에 따라 사료의 종류와 분량 및 수분의 제공 등을 원격 제어하며 사육하기 위한 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템에 관한 것으로, 인터넷과 연결되는 컴퓨터를 이용하여 원거리에 있는 농장의 소를 사육하기 위한 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템에 있어서, 각 클라이언트 소유임을 인증할 수 있는 개체식별기가 부착된 개체가 사료급여통으로 진입하여 개체정보를 판독 하고, 클라이언트 소유의 개체인지 여부를 확인하는 개체판단단계, 해당 개체의 사전정보가 중앙서버의 개체별DB에 존재하는지 여부를 확인하여 개체사전정보를 저장하고 해당 개체의 사전정보를 상기 중앙서버를 제어하는 중앙PC 단말기로 디스플레이하여 개체정보를 확인하는 개체정보확인단계, 상기 중앙서버에 저장되는 표준사육정보DB와 개체별DB의 해당 개체 사전정보간을 비교분석하여 해당 개체의 현발육상태의 우성 및 열성 여부를 판단하는 개체우열판단단계, 상기 개체우열판단단계에 의해 우성 및 열성으로 판단된 개체에 적합한 사료의 양 및 종류를 상기 표준사육정보 DB로부터 추출하여 사료를 공급하는 개체별 사료 공급단계로 구성되는 특징으로 하는 인터넷을 이용한 원거리 가축 사육 시스템 처리 방법을 특징으로 한 것으로서, 전국에 분포되며 산재되어 있는 각 가축 농장의 개체에 따른 사료의 양 및 종류 등을 해당 개체의 발육상황에 따라 원거리에서도 일방향 또는 양방향 동시에 일률적 제어가 가능하도록 하여 우량의 육질을 갖는 개체로 사육시킬 수 있는 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템에 관한 것이다. claims: 인터넷과 연결되는 컴퓨터를 이용하여 원거리에 있는 농장의 소를 사육하기 위한 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템에 있어서, 각 클라이언트 소유임을 인증할 수 있는 개체식별기가 부착된 개체가 사료급여통으로 진입하여 개체정보를 판독 하고, 클라이언트 소유의 개체인지 여부를 확인하는 개체판단단계, 해당 개체의 사전정보가 중앙서버의 개체별DB에 존재하는지 여부를 확인하여 개체사전정보를 저장하고 해당 개체의 사전정보를 상기 중앙서버를 제어하는 중앙PC 단말기로 디스플레이하여 개체정보를 확인하는 개체정보확인 단계, 상기 중앙서버에 저장되는 표준사육정보DB와 개체별DB의 해당 개체 사전정보간을 비교분석하여 해당 개체의 현발육상태의 우성 및 열성 여부를 판단하는 개체우열판단단계, 상기 개체우열판단단계에 의해 우성 및 열성으로 판단된 개체에 적합한 사료의 양 및 종류를 상기 표준사육정보 DB로부터 추출하여 사료를 공급하는 개체별 사료 공급단계로 구성되는 특징으로 하는 인터넷을 활용한 온라인 원거리 가축을 위한 사육시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

632/1150 Row 632: application_number: 1020190137121, combined_string: invention_title: 3차원 영상을 이용한 한우 체중 측정 장치 abstract: 본 발명은 한우에 대한 3차원 영상 획득과 영상처리 기술을 적용하여 한우의 체중을 측정하는 장치에 관한 것이다. 종래의 체중계를 이용한 한우의 체중 측정에 많은 노력이 소요되고, 가축을 고정하지 않을 경우 부상의 위험이 상존하고 있으며, 분뇨가 체중계 위에 남아있을 경우 체중의 정확한 측정이 불가능한 실정이다.본 발명에 따르면 한우의 3차원 영상 획득용 ToF(Time Of Flight) 카메라(A)는 고정용 브라켓(B)에 의해서 확장용 암(C)에 연결된다. 확장용 암(C)은 기본 암(D)에 연결되며, 기본 암(D)의 무게 균형을 위해서 균형추(E)가 사용된다. 기본 암(D)은 삼각대(F)에 의해서 지지된다. ToF 카메라(A)에 의해서 획득된 영상은 컴퓨터(G)에 저장되며, 영상처리 및 체중추정용 알고리즘에 의해서 체중이 결정된다.상기의 구성에 의하여 한우의 체장, 체고, 흉폭, 요각폭 등 체형정보를 결정하고 상기 정보와 함께 측정 한우의 월령을 회귀 식(1)에 대입함으로써 한우의 체중을 측정할 수 있는 수단을 제공하였다. 이러한 구성에 의하여 한우를 거의 전 연령대에 걸쳐 체중을 측정할 수 있는 효과적인 수단을 제공하였다. claims: 3차원 영상 획득과 영상처리가 가능하도록 ToF 카메라(A), 고정용 브라켓(B), 확장용 암(C), 기본 암(D), 균형추(E), 삼각대(F), 컴퓨터(G)를 포함하여 이루어지는 것을 특징으로 하는 한우 체중측정 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

633/1150 Row 633: application_number: 1020190134165, combined_string: invention_title: 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템 abstract: 본 발명은 한우 번식관리 시스템에 관한 것으로서, 보다 구체적으로는 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템으로서, 번식우 개체별 번식주기 내 예정된 번식상태 정보, 예정된 번식상태까지 남은 일수 정보, 및 번식우에 부착된 센서로부터 수집된 활동상태 정보를 개체별 비교하여 제공하는 번식우 관리 모듈; 날짜별 번식상태 정보 및 개체 현황 정보를 저장하고 제공하는 번식예정일 관리 모듈; 축사에서 보유하는 정액과 수정란의 유전정보 및 물류 정보를 저장하고 제공하는 정액/수정란 관리 모듈; 및 축사의 관리자 정보 및 실시간 동영상을 포함하는 축사 현황 정보를 저장하고 제공하는 축사 관리 모듈을 포함하는 것을 그 구성상의 특징으로 하며, 상기 번식우 관리 모듈에서 제공하는 활동상태는, 시간에 따른 개체의 활동을 활동 그래프의 형식으로 함께 제공하는 것을 특징으로 한다.본 발명에서 제안하고 있는 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템에 따르면, 번식우 개체별 번식주기 내 예정된 번식상태 정보, 예정된 번식상태까지 남은 일수 정보, 및 번식우에 부착된 센서로부터 수집된 활동상태 정보를 개체별 비교하여 제공하는 번식우 관리 모듈을 포함함으로써, 개체별 활동 및 번식상태를, 예정된 정보와 실시간으로 확인된 정보로서 상호 비교할 수 있도록 제공하기 때문에, 더욱 정확하고 용이하게 번식우의 번식상태를 판단할 수 있으며, 각각의 번식상태마다 확인해야 할 사항을 제공함으로써, 한우 번식우 관리자에게 해야 할 일을 빠짐없이 안내할 수 있어 번식우 개체별 지속적이고 효과적인 관리가 가능하고, 궁극적으로는 한우 축가의 생산성 및 수익성에 이바지하고 소득 증대를 도모할 수 있다.또한, 본 발명에서 제안하고 있는 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템에 따르면, 각 한우 개체의 활동 그래프뿐만 아니라 다른 한우 개체들의 활동 그래프를 함께 보여주고, 시간에 따른 활동상태를 녹화된 활동 동영상과 함께 제공함으로써, 관리자가 각 개체의 활동상태를 다른 개체들과 한눈에 비교 분석할 수 있으며, 이에 따라 한우 번식우마다 개별적인 건강상태에 적합하도록 번식관리를 할 수 있어, 체계적인 관리를 통해 번식 효율을 높일 수 있다.뿐만 아니라, 본 발명에서 제안하고 있는 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템에 따르면, 캘린더 형식으로 날짜에 따른 번식상태 정보 및 개체 현황정보를 제공하는 번식예정일 관리 모듈을 포함함으로써, 각 일자에 해당하는 일정 정보를 갖는 개체정보를 해당 일정별로 추출하여 오늘의 일정 보기를 제공하고, 관리자로 하여금 매일의 해야 할 일을 꾸준히 안내할 수 있어 한우 번식우 개체별 지속적이고 효과적인 관리가 가능하다. claims: 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템(10)으로서,번식우 개체별 번식주기 내 예정된 번식상태 정보, 예정된 번식상태까지 남은 일수 정보, 및 번식우에 부착된 센서로부터 수집된 활동상태 정보를 개체별 비교하여 제공하는 번식우 관리 모듈(100);날짜별 예정 번식상태 정보 및 개체 현황 정보를 저장하고 제공하는 번식예정일 관리 모듈(200);축사에서 보유하는 정액과 수정란의 유전정보 및 물류 정보를 저장하고 제공하는 정액/수정란 관리 모듈(300); 및축사의 관리자 정보 및 실시간 동영상을 포함하는 축사 현황 정보를 저장하고 제공하는 축사 관리 모듈(400)을 포함하고,상기 번식우 관리 모듈(100)에서 제공하는 활동상태 정보는, 시간에 따른 개체의 활동을 활동 그래프의 형식으로 함께 제공하는 것을 특징으로 하는, 활동 그래프 및 번식상태 정보를 제공하는 한우 번식관리 시스템(10)., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

634/1150 Row 634: application_number: 1020190134164, combined_string: invention_title: 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템 abstract: 본 발명은 한우 번식주기 관리 시스템에 관한 것으로서, 보다 구체적으로는 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템으로서, 한우 개체의 발정 여부를 탐지하는 발정탐지부; 상기 발정탐지부로부터 발정 정보를 수신하여 개체별 번식주기 및 번식상태에 대한 정보를 관리하고 저장하는 서버; 및 상기 발정탐지부 및 상기 서버로부터 개체별 번식에 대한 정보를 수신받거나, 개체별 번식에 대한 정보를 상기 서버로 송신하는 사육자 단말기를 포함하며, 상기 서버는, 상기 발정탐지부에서 개체의 발정탐지 시, 발정 정보를 수신하여 번식주기를 연산하는 일정연산부; 상기 사육자 단말기로부터 실제 확인된 번식상태를 수신받아 등록하는 등록부; 및 상기 일정연산부에서 연산된 번식주기에 따른 예상 번식상태와 상기 등록부에서 등록된 실제 번식상태 차이를 개체별 비교하는 비교부를 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템에 따르면, 한우 개체마다 부착된 센서에서 감지된 소의 움직임 및 행동 정보를 토대로, 소의 행동 유형 패턴을 판단하고 소의 발정 여부를 탐지하는 발정탐지부를 포함함으로써, 소의 발정기를 보다 정확하고 용이하게 판단할 수 있으며, 공태기간 및 번식장애(저수태, 미약발정, 무발정, 조기배사멸) 발생을 예방할 수 있어, 소의 번식 효율을 증가시키고 발정 미감지로 인한 피해를 줄이며, 궁극적으로는 한우 농가의 생산성 및 수익성에 이바지하고 농가의 소득 증대에 이바지할 수 있다.또한, 본 발명에서 제안하고 있는 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템에 따르면, 한우 개체의 발정탐지 후, 번식주기 내 번식상태 일정 정보를 연산하여 제공하고, 번식상태마다 확인해야 할 사항을 제공함으로써, 한우 번식우 사육자에게 해야 할 일을 빠짐없이 번식상태별로 안내할 수 있어 번식우 개체별 지속적이고 효과적인 관리가 가능하며, 한우 번식우마다 개별적인 건강상태에 적합하도록 번식관리를 할 수 있어, 더욱 체계적인 번식관리를 통해 번식 효율을 증가시킬 수 있다.뿐만 아니라, 발명에서 제안하고 있는 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템에 따르면, 번식주기 내 자동으로 판단된 개체의 번식상태와 사육자로부터 확인된 실제 번식상태의 차이를 비교하여 축사주 내지 사육자에게 등록요청 푸시알람 내지 등록지연 알람을 보냄으로써, 축사주 내지 사육자가 빠뜨림 없이 번식관리를 할 수 있도록 유도하고, 관리를 강제할 수 있으며, 사육자가 업무를 소홀히 하지 않도록 축사주가 고용된 사육자를 관리하는 데 도움을 줄 수 있다. claims: 한우 번식주기 관리 시스템(10)으로서,한우 개체의 발정 여부를 탐지하는 발정탐지부(100);상기 발정탐지부(100)로부터 발정 정보를 수신하여 개체별 번식주기 및 번식상태에 대한 정보를 관리하고 저장하는 서버(200); 및상기 발정탐지부(100) 및 상기 서버(200)로부터 개체별 번식에 대한 정보를 수신받거나, 개체별 번식에 대한 정보를 상기 서버(200)로 송신하는 사육자 단말기(300)를 포함하며,상기 서버(200)는,상기 발정탐지부(100)에서 개체의 발정탐지 시, 발정 정보를 수신하여 번식주기를 연산하는 일정연산부(210);상기 사육자 단말기(300)로부터 실제 확인된 번식상태를 수신받아 등록하는 등록부(220); 및상기 일정연산부(210)에서 연산된 번식주기에 따른 예상 번식상태와 상기 등록부(220)에서 등록된 실제 번식상태 차이를 개체별 비교하는 비교부(230)를 포함하며,상기 사육자 단말기(300)는,한우 개체의 확인된 실제 번식상태를 입력하는 입력부(310);상기 입력부(310)에서 입력된 실제 번식상태, 및 상기 일정연산부(210)에서 연산된 번식주기에 따른 예상 번식상태와 각각의 번식상태에 따라 사육자가 해야할 사항을 제공하는 출력부(320); 및상기 비교부(230)에서 비교된 번식상태의 차이가 기설정된 값보다 초과한 경우, 축사주 내지 사육자에게 등록요청 푸시알람 또는 등록지연 알람을 보내는 알람부(330)를 더 포함하며,상기 사육자 단말기(300)를 통해, 사육자는 어린소 상태의 개체, 수정이 실패한 개체, 임신이 실패한 개체, 또는 분만후 상태의 개체에서 발정 징후가 보이면 실제로 발정 상태인지 확인을 하여 발정인 경우 발정등록, 인공수정이 완료한 개체의 경우 수정등록, 2회 발정주기가 지난 후 자동으로 임신대기 상태가 되고 임신 성공이 확인되면 임신감정등록, 분만이 완료되면 분만등록, 분만 후 개체가 더이상 송아지 생산에 가치가 없다고 판단되면 비육 등록이 이루어지되,확인된 실제 번식상태로서 발정등록, 수정등록, 임신감정등록, 분만등록, 비육등록 중 하나의 등록이 상기 사육자 단말기(300)를 통해 이루어지며, 상기 사육자 단말기(300)를 통한 등록 절차를 거쳐야 상기 일정연산부(210)에서 다음 번식주기가 연산 되도록 함으로써, 사육자의 등록을 강제하는 것을 특징으로 하는, 등록 절차를 통해 한우 관리를 강제할 수 있는 한우 번식주기 관리 시스템(10)., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

635/1150 Row 635: application_number: 1020190133038, combined_string: invention_title: 가축분뇨를 이용한 완효성 퇴비의 제조방법 및 이에 의해 제조되는 완효성 퇴비 abstract: 본 발명은 우사에서 수거된 우분과 계분을 혼합하여 발효시간을 단축하고 분뇨에 포함된 유효성분을 완효화하는 퇴비 제조방법에 관한 것으로서, 우사 바닥에 마그네시아와 철염을 살포하고 그 위에 톱밥 깔짚을 덮어 바닥층을 형성하는 단계와, 상기 바닥층이 형성된 우사에 소를 사육하며 상기 우사에 설치된 건조 팬을 통하여 우사 내부를 통기시켜 우분을 1차 발효하는 단계 및, 1차 발효된 상기 우분에 계분과 석회고토의 혼합물을 혼합하여 2차 발효하는 단계를 포함한다.본 발명에 따르면 우사 바닥에서부터 분뇨의 배설과 동시에 발효를 촉진함으로써 발효기간을 단축하여 악취 발생을 저감시킬 수 있으며, 가축의 축분에 포함된 유효성분을 난용화ㆍ완효화하여 고품질의 친환경 퇴비를 제공할 수 있다. claims: 우사 바닥에 마그네시아와 황토분말이 코팅된 황산제일철(FeSO4)을 살포하고 그 위에 톱밥 깔짚을 덮어 바닥층을 형성하는 단계;상기 바닥층이 형성된 우사에 소를 사육하며, 상기 우사에 설치된 건조 팬을 통하여 우사 내부를 통기시켜 우분의 함수율이 80% 미만이 되도록 통기시켜 1차발효하는 단계; 및,1차 발효된 상기 우분을 우사에서 수거하여 추가 발효한 후, 계분과 석회고토의 혼합물을 혼합하여 1~3개월 동안 2차 발효하는 단계;를 포함하는 것을 특징으로 하는 가축분뇨를 이용한 완효성 퇴비의 제조방법.제1항, 제2항 및 제6항 내지 제12항 중 어느 한 항에 의하여 제조되는 완효성 퇴비., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

636/1150 Row 636: application_number: 1020190130417, combined_string: invention_title: 동물용 주사기 보조장치 abstract: 본 발명은 소 등의 가축이나 사육되는 동물에게 예방 또는 치료용 주사액를 투약할 때, 원거리에서 안전하고 신속하게 투약할 수 있고, 1회용 주사기를 사용하여 위생적으로 투약할 수 있도록 구성된 동물용 주사기 보조장치에 관한 것으로, 가압부 안내부(120)와 주사기 거치부(110)를 포함하는 본체(100);와, 상기 가압부 안내부(120)에 삽입되어 이동가능하게 결합되는 가압부(220)와 손잡이(260)를 포함하는 피스톤 가압모듈(200);과, 상기 주사기 거치부(110)에 설치되며 상기 주사기(400)의 실린더(410)가 삽입되는 실린더 안착부(310)를 포함하는 주사바늘 보호체(300);를 포함하고 있으며, 상기 주사기 거치부(110)에는 설치되는 주사기(400)의 실린더(410)를 고정 결합할 수 있는 실린더 플랜지 결합홈(140)이 형성되어 있고, 상기 주사바늘 보호체(300)는 상기 주사기 거치부(110)의 내부에서 상기 주사기의 실린더(410) 및 상기 본체(100)와 상대이동 가능하게 설치되어, 상기 주사기 거치부(110)에 설치된 주사기(400)의 주사바늘(430)이 외부로 노출되지 않은 상태에서 동물에게 주사액(a)을 투약할 수 있도록 구성되어 있다. claims: 실린더(410)와 피스톤(240) 및 주사바늘(430)을 포함하는 주사기(400)를 설치하여 원거리에서 동물에게 주사액(a)을 투약하기 위한 동물용 주사기 보조장치로써, 가압부 안내부(120)와 주사기 거치부(110)를 포함하는 본체(100);상기 가압부 안내부(120)에 삽입되어 이동가능하게 결합되는 가압부(220)와 손잡이(260)를 포함하는 피스톤 가압모듈(200); 상기 주사기 거치부(110)에 설치되며 상기 주사기(400)의 실린더(410)가 삽입되는 실린더 안착부(310)를 포함하는 주사바늘 보호체(300);를 포함하되, 상기 주사기 거치부(110)에는 설치되는 주사기(400)의 실린더(410)를 고정 결합할 수 있는 실린더 플랜지 결합홈(140)이 형성되어 있고, 상기 주사바늘 보호체(300)는 상기 주사기 거치부(110)의 내부에서 상기 주사기의 실린더(410) 및 상기 본체(100)와 상대이동 가능하게 설치되어, 상기 주사기 거치부(110)에 설치된 주사기(400)의 주사바늘(430)이 외부로 노출되지 않은 상태에서 동물에게 주사액(a)을 투약할 수 있도록 구성되어 있는 것을 특징으로 하는 동물용 주사기 보조장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

637/1150 Row 637: application_number: 1020190124820, combined_string: invention_title: IoT 센서를 활용한 농업 및 목축용 실시간 모니터링 시스템 및 방법 abstract: 본 발명은 농업 및 목축에 있어서, IoT 센서를 활용하여 이동 개체에 부착된 태그(Tag) 및 WiFi 시그널을 감지하고 LMS(Livestock Monitoring System)를 활용하여 이동 개체의 가상 펜스(Virtual Fence) 접근 및 이상 행동을 모니터링할 수 있도록 구현한 IoT 센서를 활용한 농업 및 목축용 실시간 모니터링 시스템 및 방법에 관한 것으로, 태그/WiFi 시그널 발생기가 이동 개체에 설치되어 태그/WiFi 시그널을 발생시켜 주며; IoT 센서가 태그/WiFi 시그널 발생기에서 발생시킨 태그/WiFi 시그널을 감지하며; LMS부가 IoT 센서에서 감지한 태그/WiFi 시그널을 수신받아, 이동 개체의 가상 펜스 접근 및 이상 행동을 모니터링한다. claims: 이동 개체에 설치되어 태그/WiFi 시그널을 발생시켜 주기 위한 태그/WiFi 시그널 발생기;상기 태그/WiFi 시그널 발생기에서 발생시킨 태그/WiFi 시그널을 감지하기 위한 IoT 센서; 및상기 IoT 센서에서 감지한 태그/WiFi 시그널을 수신받아, 이동 개체의 가상 펜스 접근 및 이상 행동을 모니터링하기 위한 LMS부를 포함하는 IoT 센서를 활용한 농업 및 목축용 실시간 모니터링 시스템.이동 개체에 설치되어 있는 태그/WiFi 시그널 발생기가 태그/WiFi 시그널을 발생시켜 주는 단계;IoT 센서가 상기 태그/WiFi 시그널 발생기에서 발생시킨 태그/WiFi 시그널을 감지하는 단계; 및LMS부가 상기 IoT 센서에서 감지한 태그/WiFi 시그널을 수신받아, 이동 개체의 가상 펜스 접근 및 이상 행동을 모니터링하는 단계를 포함하는 IoT 센서를 활용한 농업 및 목축용 실시간 모니터링 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

638/1150 Row 638: application_number: 1020217012096, combined_string: invention_title: 대기 메탄 및 아산화질소 배출을 줄이기 위한 조성물 및 방법 abstract: 본 발명은 가축 사료 첨가제 및/또는 보충제를 사용하여 대기 메탄 및/또는 아산화질소 배출을 감소시키는 조성물 및 방법을 제공한다. 바람직한 실시예에서, 동물이 사료 및/또는 음용수를 삼키기 전에, 유익한 미생물 및/또는 이들의 성장 부산물을 포함하는 조성물을 이들과 접촉시킨다. 상기 조성물은, 예를 들어 상기 동물의 소화계 내 메탄생성 미생물을 제어할 수 있으므로, 동물 및 동물의 폐기물로부터 생산된 장 메탄 배출의 함량을 감소시킨다. claims: 대기 메탄 배출 감소를 위한 방법으로서, 유익한 미생물 및/또는 미생물 성장 부산물을 포함하는 조성물을 동물이 사료 및/또는 음용수를 삼키기 전에 동물 사료 및/또는 음용수와 접촉시키고, 상기 미생물은 Wickerhamomyces anomalus, Bacillus licheniformis, Bacillus amyloliquefaciens, Bacillus subtilis, Starmerella bombicola, Pichia occidentalis, Pleurotus ostreatus, Lentinula edodes, Monascus purpureus, Trichoderma harzianum, Trichoderma viride, Acremonium chrysogenum, Saccharomyces cerevisiae, 및/또는 Saccharomyces boulardii이고,상기 가축에게 사료 및/또는 음용수를 제공하고 상기 가축이 상기 사료 및/또는 물을 삼키고, 및상기 조성물의 가축 섭취로 상기 조성물이 가축의 소화계 내 존재하는 메탄생성 미생물과 접촉할 수 있고 상기 메탄 생성 미생물을 제어할 수 있게 하는, 방법.제18항에 있어서, 상기 평가된 현지 조건은 다음 중 하나 이상을 포함하는 방법: 동물의 연령, 건강, 크기 및/또는 종; 동물 생산을 위한 목적; 동물 장 내 미생물의 종; 설미에서 온실 가스 배출의 타입; 현재 기후; 년중 현재 현재 계절 및 시간; 및 조성물 사용의 모드 및/또는 사용 속도.길들여진 동물을 사육하기 위한 조성물로서, 상기 조성물은 미생물 및/또는 미생물 성장 부산물을 포함하고, 여기서 상기 미생물은 Wickerhamomyces anomalus, Bacillus licheniformis, Bacillus amyloliquefaciens, Bacillus subtilis, Starmerella bombicola, Pichia occidentalis, Pleurotus ostreatus, Lentinula edodes, Monascus purpureus, Trichoderma harzianum, Trichoderma viride, Acremonium chrysogenum, Saccharomyces cerevisiae, 및/또는 Saccharomyces boulardii인, 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

639/1150 Row 639: application_number: 1020190110341, combined_string: invention_title: 변이된 COMT 유전자를 포함하는 사료용 작물 및 이의 용도 abstract: 본 발명은 변이된 COMT를 코딩하는 폴리뉴클레오티드, 상기 폴리뉴클레오티드로부터 발현되는 변이된 COMT 단백질, 상기 폴리뉴클레오티드를 포함하는 형질전환 벡터, 상기 형질전환 벡터가 도입되어 형질전환된 사료용 작물, 상기 형질전환된 사료용 작물을 포함하는 사료용 조성물, 상기 사료용 조성물을 포함하는 사료, 상기 사료를 이용한 가축의 사육방법 및 상기 형질전환된 사료용 작물의 생산방법에 관한 것이다. 본 발명에서 제공하는 형질전환된 사료용 작물은 일반적인 사료용 작물에 비하여 총 리그닌 함량이 감소되어 이로부터 얻어진 바이오매스의 소화율이 증가될 뿐만 아니라, 헤미셀룰로오스의 일종인 자일로스의 함량이 증가되는 특징을 나타내므로, 상기 형질전환된 사료용 작물은 다양한 가축 비육용 사료의 유효성분으로서 활용될 수 있을 것이다. claims: 사료용 작물에 도입되어, 리그닌의 합성을 억제하고, 헤미셀룰로오스의 합성을 촉진할 수 있는, 변이된 COMT(caffeic acid O-methyltransferase)를 코딩하는 폴리뉴클레오티드로, 상기 폴리뉴클레오티드는 서열번호 3의 염기서열을 갖는 COMT 유전자의 334번 염기가 결실되거나 또는 상기 334번 위치에 A 또는 T가 삽입된 것인, 폴리뉴클레오티드.제1항 내지 제3항 중 어느 한 항의 폴리뉴클레오티드로부터 발현되는, 변이된 COMT(caffeic acid O-methyltransferase) 단백질.제1항 내지 제3항 중 어느 한 항의 폴리뉴클레오티드를 포함하고, 사료용 작물에서 상기 폴리뉴클레오티드를 도입하여 발현시킬 수 있는 형질전환 벡터. 제7항의 형질전환 벡터가 도입되어, 소화율이 향상되도록 형질전환된, 사료용 작물.제9항의 사료용 조성물을 포함하는 사료.제10항의 사료를 가축에게 급이하는 단계를 포함하는, 가축의 사육방법.제8항의 사료용 작물의 종자를 파종, 재배 및 수확하는 단계를 포함하는, 사료용 작물의 생산방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

640/1150 Row 640: application_number: 1020210142802, combined_string: invention_title: 스마트팜 양돈 시스템 및 방법 abstract: 스마트팜 양돈 시스템 및 방법이 개시된다. 스마트팜 양돈 시스템은 유저 단말로부터 사용자 조작에 따른 돼지의 축사 변동 사항을 제공받는 유저 대응부; 및 상기 축사 변동 사항에 관한 정보가 상응하는 돼지의 사육 데이터에 추가되도록 상기 사육 데이터를 갱신하는 데이터 갱신부를 포함한다. claims: 미리 지정된 GUI(Graphical User Interface) 환경의 관리 화면을 이용하여, 실제 양돈 현장에서의 축사 이동 대상인 대상 돼지에 상응하는 개체 이미지를 가상의 제1 구획 영역에서 가상의 제2 구획 영역으로 드래그 앤 드롭(Drag and Drop) 방식으로 이동시키는 사용자 조작에 따른 상기 대상 돼지의 축사 변동 사항을 유저 단말로부터 제공받는 유저 대응부; 및드래그 앤 드롭 방식으로 이동된 개체 이미지에 상응하는 상기 대상 돼지의 사육 데이터에 상기 축사 변동 사항에 관한 정보가 추가되도록 상기 사육 데이터를 갱신하는 데이터 갱신부를 포함하되,상기 관리 화면은 돼지가 사육되는 실제 양돈 현장에 구비된 실제의 구획 영역들에 일대일 대응되는 가상의 구획 영역들과, 실제의 구획 영역들 각각에서 사육되는 돼지에 대응되도록 상응하는 가상의 구획 영역에 상응하는 돼지의 개체 이미지가 표시되도록 구현되고,가상의 구획 영역에 표시되는 개체 이미지는 가상의 구획 영역에 대응되는 실제의 구획 영역에서 사육되는 돼지의 식별정보에 대응되도록 관리되며,상기 대상 돼지에 상응하는 개체 이미지가 이동되는 상기 가상의 제2 구획 영역은 상기 가상의 제1 구획 영역에 대응되는 실제의 제1 구획 영역에서 사육되는 상기 대상 돼지의 생육 주기에 부합하는 돼지들을 모아 사육하기 위해 미리 설정된 실제의 제2 구획 영역에 대응되는 가상의 구획 영역이며, 출생으로 사육이 개시되어 출하 또는 도축으로 인해 사육이 종료되는 전체 생육 기간 동안에 반복되는 상기 대상 돼지의 실제 양돈 현장에서의 생육 주기별 축사 이동에 대응되도록 상기 대상 돼지에 상응하는 개체 이미지를 드래그 앤 드롭 방식으로 상응하는 가상의 구획 영역으로 이동시키는 사용자 조작에 따른 축사 변동 사항이 순차적으로 제공되는 것만으로, 각각의 시점에서 가상의 구획 영역에 대응되도록 상기 대상 돼지가 사육되는 실제 양돈 현장에서의 축사가 인식되어, 상기 대상 돼지가 전체 생육 기간 동안 실제 양돈 현장에서 이동되며 사육된 각각의 축사와 상기 대상 돼지를 대상으로 하여 수집된 사육 데이터가 상기 대상 돼지의 전체 생육 기간 동안 연속되도록 관리되는 것을 특징으로 하는 스마트팜 양돈 시스템.스마트팜 양돈 방법을 수행하도록 하는 컴퓨터-판독 가능 매체에 저장된 컴퓨터 프로그램으로서, 상기 컴퓨터 프로그램은 컴퓨터로 하여금 이하의 단계들을 수행하도록 하며, 상기 단계들은,돼지의 사육을 위한 실제 양돈 현장의 실제의 구획 영역들에 일대일 대응되는 가상의 구획 영역들과, 실제의 구획 영역들 각각에서 사육되는 돼지에 대응되는 개체 이미지가 각 가상의 구획 영역에 표시된 GUI(Graphical User Interface) 환경의 관리 화면을 이용하여, 실제 양돈 현장에서의 축사 이동 대상인 대상 돼지에 상응하는 개체 이미지를 가상의 제1 구획 영역에서 가상의 제2 구획 영역으로 드래그 앤 드롭(Drag and Drop) 방식으로 이동시키는 사용자 조작에 따른 상기 대상 돼지의 축사 변동 사항을 유저 단말로부터 제공받는 단계; 드래그앤 드롭 방식으로 이동된 개체 이미지에 상응하는 상기 대상 돼지의 사육 데이터에 상기 축사 변동 사항에 관한 정보가 추가되도록 상기 사육 데이터를 갱신하는 단계; 및상기 대상 돼지에 상응하는 개체 이미지가 상기 가상의 제2 구획 영역으로 이동되어 위치하는 동안, 상기 가상의 제2 구획 영역에 대응되는 실제의 제2 구획 영역에 대해 수집된 부가 정보가 상기 사육 데이터에 포함되도록 상기 사육 데이터를 갱신하는 단계를 포함하되,가상의 구획 영역에 표시되는 개체 이미지는 가상의 구획 영역에 대응되는 실제의 구획 영역에서 사육되는 돼지의 식별정보에 대응되도록 관리되며,상기 대상 돼지에 상응하는 개체 이미지가 이동되는 상기 가상의 제2 구획 영역은 상기 가상의 제1 구획 영역에 대응되는 실제의 제1 구획 영역에서 사육되는 상기 대상 돼지의 생육 주기에 상응하는 돼지들을 모아 사육하기 위해 미리 설정된 실제의 제2 구획 영역에 대응되는 가상의 구획 영역이며, 출생으로 사육이 개시되어 출하 또는 도축으로 인해 사육이 종료되는 전체 생육 기간 동안에 반복되는 상기 대상 돼지의 실제 양돈 현장에서의 생육 주기별 축사 이동에 대응되도록 상기 대상 돼지에 상응하는 개체 이미지를 드래그 앤 드롭 방식으로 상응하는 가상의 구획 영역으로 이동시키는 사용자 조작에 따른 축사 변동 사항이 순차적으로 제공되는 것만으로, 각각의 시점에서 가상의 구획 영역에 대응되도록 상기 대상 돼지가 사육되는 실제 양돈 현장에서의 축사가 인식되어, 상기 대상 돼지가 전체 생육 기간 동안 실제 양돈 현장에서 이동되며 사육된 각각의 축사와 상기 대상 돼지를 대상으로 하여 수집된 사육 데이터가 상기 대상 돼지의 전체 생육 기간 동안 연속되도록 관리되되,실제 양돈 현장에서 사육되는 상기 대상 돼지에 대해 전체 생육 기간 동안 생성되는 사육 데이터의 정보 연속성이 유지되도록 하기 위해, 상기 사육 데이터에는 상기 대상 돼지에 상응하는 개체 이미지가 상기 가상의 제1 구획 영역에 위치하는 동안에, 상기 가상의 제1 구획 영역에 대응되는 실제의 제1 구획 영역에 대해 이미 수집되어 포함된 부가 정보가 유지되고,상기 부가 정보는 실제의 구획 영역에 대해 수집된 온도, 습도 및 가스 농도인 요소 항목들을 포함하는 상기 대상 돼지의 사육 환경에 관한 정보를 포함하는 것을 특징으로 하는 컴퓨터-판독 가능 매체에 저장된 컴퓨터 프로그램., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

641/1150 Row 641: application_number: 1020210002483, combined_string: invention_title: IoT 스마트 기술을 이용한 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템 abstract: 본 발명은 IoT 스마트 기술을 이용한 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템에 관한 것으로, IoT 스마트 기술을 이용하여 조류독감(AI)과 구제역(FMD) 및 아프리카돼지열병(ASF) 바이러스를 실시간으로 감시하여 그 결과값을 DB에 저장하고, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 모니터에 실시간으로 표시하여 모니터링하고, 바이러스에 필요한 방역 및 소독제 정보를 인터넷망을 통해 제공함으로써, 효과적으로 바이러스를 살균 및 소독할 수 있고 바이러스 발생 지역을 체계적으로 방역 및 관리할 수 있다.본 발명에 의한 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템은, 바이러스가 발생하기 쉬운 장소에 설치되며, 강수, 호수, 하수, 토양, 공기 중에 포함된 바이러스를 센서로 주기적으로 감지하여 조류독감(AI), 구제역(FMD), 아프리카돼지열병(ASF) 바이러스를 판별하고 그 결과값을 저장하고 통신망을 통해 전송하는 복수의 바이러스 감지 장치(110)와, 상기 통신망을 통해 상기 복수의 바이러스 감지 장치(110)로부터 수신된 결과값을 DB(210)에 저장하고, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 모니터에 실시간으로 표시하여 모니터링하고, 바이러스에 필요한 방역 및 소독제 정보를 제공하는 모니터링 관제 서버(200)와, 상기 모니터링 관제 서버(200)에 인터넷망을 통해 접속하여, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 확인하고, 바이러스에 필요한 방역 및 소독제 정보를 제공받으며, 방역 정보를 입력하여 등록하는 스마트폰(300)의 바이러스 앱(310)을 포함하는 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템에 있어서, 상기 바이러스의 소독제는, 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 후 10∼30분 동안 원심분리기에서 2000RPM 이상의 고속교반으로 수화 및 분쇄를 함께 진행하여 입도 1000메쉬 이상의 액상화를 갖는 액상소석회(Ca(OH)2)로 구성되며, 상기 생석회(CaO)는 석회석(CaCO3)을 1,000∼1,200℃에서 연소시켜 제조한 산화칼슘이고, 상기 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 액상소석회(Ca(OH)2) 85∼92중량%에 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 입도 100∼200메쉬의 숯 분말 5∼10중량%를 혼합하여 구성된다.본 발명에 따르면, 환경오염을 발생하지 않고 조류독감(AI)과 구제역(FMD) 및 아프리카돼지열병(ASF) 바이러스를 효과적으로 소독할 수 있는 효과가 있다. claims: 바이러스가 발생하기 쉬운 장소에 설치되며, 강수, 호수, 하수, 토양, 공기 중에 포함된 바이러스를 센서로 주기적으로 감지하여 조류독감(AI), 구제역(FMD), 아프리카돼지열병(ASF) 바이러스를 판별하고 그 결과값을 저장하고 통신망을 통해 전송하는 복수의 바이러스 감지 장치(110)와, 상기 통신망을 통해 상기 복수의 바이러스 감지 장치(110)로부터 수신된 결과값을 DB(210)에 저장하고, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 모니터에 실시간으로 표시하여 모니터링하고, 바이러스에 필요한 방역 및 소독제 정보를 제공하는 모니터링 관제 서버(200)와, 상기 모니터링 관제 서버(200)에 인터넷망을 통해 접속하여, 각 지역의 바이러스 분포 현황과 바이러스 종류 및 방역 정보를 확인하고, 바이러스에 필요한 방역 및 소독제 정보를 제공받으며, 방역 정보를 입력하여 등록하는 스마트폰(300)의 바이러스 앱(310)을 포함하는 조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템에 있어서,상기 바이러스의 소독제는,물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 후 10∼30분 동안 원심분리기에서 2000RPM 이상의 고속교반으로 수화 및 분쇄를 함께 진행하여 입도 1000메쉬 이상의 액상화를 갖는 액상소석회(Ca(OH)2)로 구성되며,상기 생석회(CaO)는 석회석(CaCO3)을 1,000∼1,200℃에서 연소시켜 제조한 산화칼슘이고,상기 물(H2O)과 생석회(CaO)를 70∼80중량% : 20∼30중량%의 비율로 혼합한 액상소석회(Ca(OH)2) 85∼92중량%에 마그네슘(Mg) 2∼3중량%, 칼슘(Ca) 1∼2중량%, 입도 100∼200메쉬의 숯 분말 5∼10중량%를 혼합한,조류독감 및 구제역 바이러스 실시간 감시 및 관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

642/1150 Row 642: application_number: 1020200164328, combined_string: invention_title: 포토니아 듀얼 기기 abstract: 포토니아 듀얼 기기가 개시된다. 본 발명은, 가시광선대역의 광을 변조하여 극미약광과 백색광의 형태로 생명체에 전달하는 포토니아 듀얼 기기를 제공한다. 본 발명에 따르면, 생명체, 예컨대 돼지의 생체 에너지를 향상시킴으로서 면역, 번식, 대사 효율에 기여할 수 있다. claims: 중앙으로 극미약광 방사 영역; 및상기 극미약광 방사 영역의 둘레로 배치된 백색광 방사 영역;이 포함되는 것을 특징으로 하는 포토니아 듀얼 기기., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

643/1150 Row 643: application_number: 1020200157144, combined_string: invention_title: 협잡물 처리장치 abstract: 본 발명은 하수처리시설, 돈사, 우사 등으로부터 배출되는 각종 협잡물이 유입되어 1차적으로 여과수를 배출하는 호퍼와, 상기 호퍼에 의하여 1차적으로 여과수가 배출된 협잡물을 탈수시켜 탈수된 협잡물을 외부로 배출시키는 스크류 프레스부를 구비하는 협잡물 처리장치에 관한 것으로, 구체적인 특징은 상기 스크류 프레스부는 모터에 의하여 회전되는 축; 상기 축의 외주면에 설치되어 상기 축의 일단부로부터 타단부쪽으로 상기 호퍼로부터 유입되는 협잡물을 이동시키는 스크류; 중심에 상기 축이 통과되도록 원통형상으로 이루어지며, 상기 호퍼로부터의 협잡물이 유입되는 유입구와 탈수된 협잡물을 외부로 배출시키는 배출부가 형성된 하우징; 상기 축과 평행하도록 하우징의 내부에 설치되고 상기 스크류의 외경보다 큰 내경을 갖으며, 상기 스크류에 의하여 이송되는 협잡물을 탈수시키는 바 케이지; 상기 바 케이지의 타단부에 설치되어 상기 스크류에 의하여 이송되는 탈수 협잡물에 의하여 가압되고, 기설정된 압력 이상의 압력이 가압될 때 개방되어 탈수 협잡물을 상기 하우징의 배출부를 통하여 외부로 배출시키는 탈수 협착물 배출밸브를 포함하는 것이다. claims: 수분을 함유하는 협잡물이 유입되어 1차적으로 여과수를 배출하는 호퍼와, 상기 호퍼에 의하여 1차적으로 여과수가 배출된 협잡물을 탈수시켜 탈수된 협잡물을 외부로 배출시키는 스크류 프레스부를 구비하는 협잡물 처리장치에 있어서: 상기 스크류 프레스부는 모터에 의하여 회전되는 축; 상기 축의 외주면에 설치되어 상기 축의 일단부로부터 타단부쪽으로 상기 호퍼로부터 유입되는 협잡물을 이동시키는 스크류; 중심에 상기 축이 통과되도록 원통형상으로 이루어지며, 상기 호퍼로부터의 협잡물이 유입되는 유입구와 탈수된 협잡물을 외부로 배출시키는 배출부가 형성된 하우징;상기 축과 평행하도록 하우징의 내부에 설치되고 상기 스크류의 외경보다 큰 내경을 갖으며, 상기 스크류에 의하여 이송되는 협잡물을 탈수시키는 바 케이지;상기 바 케이지의 타단부에 설치되어 상기 스크류에 의하여 이송되는 탈수 협잡물에 의하여 가압되고, 기설정된 압력 이상의 압력이 가압될 때 개방되어 탈수 협잡물을 상기 하우징의 배출부를 통하여 외부로 배출시키는 탈수 협잡물 배출밸브를 포함하며,상기 바 케이지는 원형상으로 형성되는 양쪽 측단부에 설치되는 측단 테두리들과, 양단부가 상기 측단 테두리들 각각에 결합되어 상기 축과 평행하게 설치되며 상기 측단 테두리를 따라서 균일한 간격으로 설치되되 단면이 원형으로 이루어지는 바들로 이루어지는 것을 특징으로 하는 협잡물 처리장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

644/1150 Row 644: application_number: 1020200149101, combined_string: invention_title: 돈사 구조 abstract: 본 발명은 돈사의 냉난방 비용을 절감할 수 있도록 된 새로운 돈사 구조에 관한 것이다.본 발명에 따른 돈사 구조는, 상기 바닥판(20)이, 상기 저장부(10)의 내부에 상호 연결되도록 배치되어 상기 저장부(10) 내부의 공간을 분뇨가 저장되는 슬러리 피트(13)와 공기가 통과하는 공기통로(12)로 구획하는 제1 및 제2 급기관(22,23)과, 둘레면이 상기 제1 급기관(22) 또는 제2 급기관(23)에 올려지도록 배치되어 상기 슬러리 피트(13)의 상부를 덮는 바닥패널(24)로 구성되어, 외부의 공기가 제1 및 제2 급기관(22,23)을 통과하면서 온도조절된 후 돈사의 내부로 공급됨으로, 여름철이나 겨울철에 돈사 내부의 온도를 적절하게 유지하기 위하여 공기를 가열 또는 냉각시키는데 소요되는 비용을 절감할 수 있는 장점이 있다. claims: 지면을 굴착하여 구덩이를 형성하고 구덩이의 내측면에 시멘트를 도포하여 구성된 저장부(10)와, 상기 저장부(10)의 상면을 막도록 설치된 바닥판(20)과, 상기 바닥판(20)의 상부를 덮도록 시공된 돈사본체(30)와, 상기 바닥판(20)의 상면에 구비되어 바닥판(20) 상부의 공간을 작업자가 통과하는 통로(41)와 돼지가 사육되는 돈방(42)으로 구획하는 격판(40)을 포함하며, 상기 돈사본체(30)의 일측에는 배기팬(35)이 구비된 배기구(34)가 형성된 돈사에 있어서, 상기 바닥판(20)은 상기 저장부(10)의 내부에 상호 연결되도록 배치되어 상기 저장부(10) 내부의 공간을 분뇨가 저장되는 슬러리 피트(13)와 공기가 통과하는 공기통로(12)로 구획하는 제1 및 제2 급기관(22,23)과, 둘레면이 상기 제1 급기관(22) 또는 제2 급기관(23)에 올려지도록 배치되어 상기 슬러리 피트(13)의 상부를 덮는 바닥패널(24)을 포함하며, 상기 제1 급기관(22)은 일단은 상기 돈사본체(30)의 외측으로 연장되고, 상기 제2 급기관(23)의 상면에는 급기공(23c)이 형성되어, 외부의 공기가 상기 제1 급기관(22)의 내부로 유입되어 제2 급기관(23)으로 공급된 후, 상기 급기공(23c)을 통해 돈사본체(30)의 내부로 공급되며, 상기 제1 급기관(22)은 하단이 저장부(10)의 내부 바닥면에 수밀하게 결합되는 한 쌍의 측판(22a)과 상기 측판(22a)의 상단에 수밀하게 결합된 상판(22b)을 갖도록 구성되어 상기 돈방(42)의 하측에 위치되고, 상기 제2 급기관(23)은 하단이 상기 저장부(10)의 내부 바닥면에 수밀하게 결합되는 한 쌍의 측판(23a)과 상기 측판(23a)의 상단에 탈착가능하게 결합되는 상판(23b)을 갖도록 구성되어 상기 통로(41)의 하측에 위치되며, 상기 바닥패널(24)에는 배출공(24a)이 상하면을 관통하도록 형성되어, 돈방(42)에서 사육되는 돼지가 배출하는 분뇨가 배출공(24a)을 통해 하측의 슬러리 피트(13)로 배출되어 저장되도록 구성되고, 상기 격판(40)은 상기 제2 급기관(23)의 측판(23a)의 상단에 구비되고,상하방향으로 연장되며 상단이 개방된 관체형상으로 구성되어 상기 돈사본체(30)의 외측에 구비되며 상기 제1 급기관(22)이 연결되는 외부급기관(25)과, 상기 외부급기관(25)의 상측에 구비되며 승강구동수단(52)에 의해 승강되어 상기 외부급기관(25)의 개폐정도를 조절하는 개폐덮개(51)와, 상기 제1 급기관(22)의 중간부에 구비되어 제1 급기관(22)을 제1 및 제2 급기부(22d,22e)로 구획하는 제1 댐퍼(53)와, 열전도율이 높은 금속재로 구성되며 양단이 상기 제1 및 제2 급기부(22d,22e)에 연결되고 중간부는 상기 슬러리 피트(13)를 통과하도록 배치된 통기관(54)과, 상기 통기관(54)의 중간부에 구비되어 통기관(54)을 통과하는 공기의 흐름을 제어하는 제2 댐퍼(55)와, 상기 제2 급기관(23)의 내부에 구비되어 제2 급기관(23)을 통과하는 공기의 속도를 측정하는 풍속센서(56)와, 상기 제2 급기관(23)에 구비되어 제2 급기관(23)을 통과하는 공기의 온도를 측정하는 제1 온도센서(57)와, 상기 슬러리 피트(13)의 내부에 구비되어 슬러리 피트(13)에 저장된 분뇨의 온도를 측정하는 제2 온도센서(58)와, 상기 풍속센서(56)와 제1 및 제2 온도센서(57,58)의 신호를 수신하며 상기 승강구동수단(52)과 제1 및 제2 댐퍼(53,55)의 작동을 제어하는 제어수단(59)을 더 포함하며, 상기 제어수단(59)은 상기 풍속센서(56)의 신호를 수신하여 제2 급기관(23)을 통과하는 공기의 속도를 수신하고 상기 승강구동수단(52)을 제어하여 상기 개폐덮개(51)를 승강시킴으로써, 상기 제2 급기관(23)을 통과하는 공기의 속도가 미리 입력된 속도를 유지하도록 조절하고, 상기 제1 온도센서(57)의 신호를 수신하여 상기 제2 급기관(23)을 통과하는 공기의 온도가 미리 설정된 기준온도에 비해 낮을 경우, 제2 온도센서(58)의 신호를 수신하여 상기 슬러리 피트(13)에 저장된 분뇨의 온도를 측정하고, 제2 온도센서(58)에 측정된 분뇨의 온도가 상기 제1 온도센서(57)에 의해 측정된 공기의 온도에 비해 높을 경우, 상기 제1 댐퍼(53)를 작동시켜 제2 급기관(23)의 중간부를 밀폐하고 제2 댐퍼(55)를 개방하여, 제2 급기관(23)을 통과하는 공기가 상기 통기관(54)을 통과하도록 함으로써, 공기가 상기 슬러리 피트(13)에 저장된 분뇨에 의해 가열되도록 하는 것을 특징으로 하는 돈사 구조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

645/1150 Row 645: application_number: 1020200138074, combined_string: invention_title: 딥러닝 기반 객체 추적 및 행동 분석을 이용한 스마트 축산관리시스템 및 방법 abstract: 본 발명의 다른 일 실시예에 따른 딥러닝 기반 객체 추적 및 행동 분석을 이용한 스마트 축산관리시스템은 돈사 내의 돼지 객체의 머리에 부착되어, 상기 돼지 객체의 뇌파신호를 측정하여 전송하는 뇌파탐지모듈; 돈사 내의 돼지 객체의 모션 이미지를 촬영하는 제1 촬상장치; 상기 돼지 객체의 열화상 이미지를 생성하는 제2 촬상장치; 상기 돼지 객체의 호흡 및 기침소리를 포함하는 음향정보를 수집하는 음향수집장치; 상기 뇌파신호, 모션 이미지, 상기 열화상 이미지 및 상기 음향정보를 기초로 해당 돼지 객체의 질병발생유무 및 질병의 종류를 예측판단하는 모니터링 서버; 및 상기 모니터링 서버로부터 돼지 객체의 질병발생 알림메시지를 제공받는 관리자 단말을 포함하고, 상기 모니터링 서버는 상기 돼지 객체에서 감지된 뇌파신호의 뇌파변이도를 통해 돼지 객체의 수면상태, 이상발작 상태, 우울감과 관련된 뇌파(electroencephalographic, EEG)를 분류한 후, 레퍼런스와 비교하여 뇌파 변이도의 패턴을 분석하는 뇌파분석부; 상기 관리자 단말로부터 타겟 객체(돼지)가 입력되면, 타겟 객체(돼지)에 위치한 뇌파탐지모듈의 위치신호를 기초로 타겟 객체의 이동경로를 역순으로 트랙킹하는 경로 추적부; 타겟팅된 돼지객체의 이동경로 중 움직임 변화에 대한 모션 이미지를 기초로 상기 돼지 객체의 행동패턴 및 자세를 분석하는 행동패턴 및 자세 분석부; 상기 열화상 이미지를 기초로 상기 돼지 객체의 체온을 분석하는 체온 분석부; 상기 음향정보를 기초로 상기 돼지 객체의 호흡주기, 기침소리의 크기 및 발생주기, 울음소리 중 적어도 하나 이상을 분석하는 음향 분석부; 및 돼지 객체의 뇌파변이도 패턴, 행동패턴의 불규칙한 자세변화, 호흡주기, 기침소리를 기초로 질병 유무를 1차 판단하고, 1차 선별된 돼지객체의 부위별 체온 및 체온변화를 기초로 질병발생유무를 2차 판단하는 질병발생 판단부를 포함하고, 상기 행동자세 및 패턴 분석부는 상기 모션 이미지를 기초로 상기 돈사 내의 돼지의 포즈패턴변화를 Standing, Lying, Sitting 중 어느 하나로 분류하고, 상기 돼지가 이동 시에, 포즈패턴변화를 거리 대비 시간으로 분석하고, 상기 체온 분석부는 상기 포즈패턴변화에 따라 발열되는 돼지들의 부위 별 체온변화를 분석하고, 상기 질병발생 판단부는 딥러닝 학습 알고리즘을 학습한 질병이 발생된 돼지들의 시계열적 포즈패턴변화, 호흡주기, 기침소리의 변화를 기초로 상기 돼지 객체를 1차 선별하는 것을 특징으로 한다. claims: 돈사 내의 돼지 객체의 머리에 부착되어, 상기 돼지 객체의 뇌파신호를 측정하여 전송하는 뇌파탐지모듈;돈사 내의 돼지 객체의 모션 이미지를 촬영하는 제1 촬상장치;상기 돼지 객체의 열화상 이미지를 생성하는 제2 촬상장치;상기 돼지 객체의 호흡 및 기침소리를 포함하는 음향정보를 수집하는 음향수집장치;상기 뇌파신호, 모션 이미지, 상기 열화상 이미지 및 상기 음향정보를 기초로 해당 돼지 객체의 질병발생유무 및 질병의 종류를 예측판단하는 모니터링 서버; 및상기 모니터링 서버로부터 돼지 객체의 질병발생 알림메시지를 제공받는 관리자 단말을 포함하고,상기 모니터링 서버는상기 돼지 객체에서 감지된 뇌파신호의 뇌파변이도를 통해 돼지 객체의 수면상태, 이상발작 상태, 우울감과 관련된 뇌파(electroencephalographic, EEG)를 분류한 후, 레퍼런스와 비교하여 뇌파 변이도의 패턴을 분석하는 뇌파분석부;상기 관리자 단말로부터 타겟 객체(돼지)가 입력되면, 타겟 객체(돼지)에 위치한 뇌파탐지모듈의 위치신호를 기초로 타겟 객체의 이동경로를 역순으로 트랙킹하는 경로 추적부;타겟팅된 돼지객체의 이동경로 중 움직임 변화에 대한 모션 이미지를 기초로 상기 돼지 객체의 행동패턴 및 자세를 분석하는 행동패턴 및 자세 분석부;상기 열화상 이미지를 기초로 상기 돼지 객체의 체온을 분석하는 체온 분석부;상기 음향정보를 기초로 상기 돼지 객체의 호흡주기, 기침소리의 크기 및 발생주기, 울음소리 중 적어도 하나 이상을 분석하는 음향 분석부; 및돼지 객체의 뇌파변이도 패턴, 행동패턴의 불규칙한 자세변화, 호흡주기, 기침소리를 기초로 질병 유무를 1차 판단하고, 1차 선별된 돼지객체의 부위별 체온 및 체온변화를 기초로 질병발생유무를 2차 판단하는 질병발생 판단부를 포함하고,상기 행동자세 및 패턴 분석부는상기 모션 이미지를 기초로 상기 돈사 내의 돼지의 포즈패턴변화를 Standing, Lying, Sitting 중 어느 하나로 분류하고, 상기 돼지가 이동 시에, 포즈패턴변화를 거리 대비 시간으로 분석하고,상기 체온 분석부는 상기 포즈패턴변화에 따라 발열되는 돼지들의 부위 별 체온변화를 분석하고,상기 질병발생 판단부는딥러닝 학습 알고리즘을 학습한 질병이 발생된 돼지들의 시계열적 포즈패턴변화, 호흡주기, 기침소리의 변화를 기초로 상기 돼지 객체를 1차 선별하는 것을 특징으로 하는 딥러닝 기반 객체 추적 및 행동 분석을 이용한 스마트 축산관리시스템.뇌파탐지모듈을 이용하여 돈사 내의 돼지 객체의 뇌파신호를 측정하는 단계;경로 추적부에서 관리자 단말로부터 타겟 객체(돼지)가 입력받으면, 타겟 객체(돼지)에 위치한 뇌파탐지모듈의 위치신호를 기초로 타겟 객체의 이동경로를 역순으로 트랙킹하는 단계;뇌파분석부에서 돼지 객체에서 감지된 뇌파신호의 뇌파변이도를 통해 돼지들의 수면상태, 이상발작 상태, 우울감과 관련된 뇌파(electroencephalographic, EEG)를 분류한 후, 레퍼런스와 비교하여 뇌파 변이도의 패턴을 분석하는 단계;행동패턴 및 자세 분석부에서 타겟팅된 돼지객체의 이동경로 중 움직임 변화에 대한 모션 이미지를 기초로 상기 돼지 객체가 이동 시에, 포즈패턴변화를 거리 대비 시간으로 분석한 후, 질병걸린 돼지들의 표본 데이터와 비교를 통해 행동이상 여부를 판단하는 단계;해당 돼지 객체가 행동이상으로 판단되면, 음향정보수집부에서 돼지 객체의 호흡 및 기침소리를 포함하는 음향정보를 수집하는 단계;질별발생 판단부에서 상기 타겟 객체(돼지)의 뇌파변이도 패턴, 행동패턴의 불규칙한 자세변화, 호흡주기, 기침소리를 기초로 질병 유무를 1차 판단하는 단계;상기 타겟 객체(돼지)가 질병발생으로 판단되면, 제2 촬상장치에서 해당 돼지 객체의 신체 부위별 열화상 이미지를 수집하는 단계질병발생 판단부에서 상기 열화상 이미지를 기초로 해당 돼지 객체의 질병발생유무 및 질병의 종류를 예측하는 단계; 및해당 돼지 객체가 질병에 걸린 것으로 예측되면, 알림부에서 질병발생 알림메시지를 생성하여 관리자 단말로 발송하는 단계를 포함하는 딥러닝 기반 객체 추적 및 행동 분석을 이용한 스마트 축산관리방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

646/1150 Row 646: application_number: 1020200099576, combined_string: invention_title: 사육 단계별 양돈 사료 급여 방법 abstract: 사육 단계별 양돈 사료 급여 방법에 관한 것으로, 보다 상세하게는 균일하고 안전한 돼지를 사육 및 공급할 수 있는 사육 단계별 양돈 사료 급여 방법에 관한 것이다. claims: 돼지의 분만일로부터 34일까지의 분만사 단계에서는 돼지 한마리당 분만사 단계의 누적 사료량이 1.5 내지 3kg 이고, 35일부터 62일까지의 이유자돈사 단계에서는 돼지 한마리당 이유자돈사 단계의 누적 사료량이 10 내지 15kg이고, 63일부터 76일까지의 자돈사 단계에서는 돼지 한마리당 자돈사 단계의 누적 사료량이 25 내지 35kg 이고,, 77일부터 111일까지의 육성돈 단계에서는 돼지 한마리당 육성돈 단계의 누적 사료량이 60 내지 80kg 이고,112일부터 출하까지의 비육돈 단계에서는 돼지 한마리당 비육돈 단계의 누적 사료량이 170 내지 180kg 이고, 상기 비육돈 단계의 사료는 녹차, 홍삼박, 대두박, 옥수수, 소맥피 및 당밀을 포함하는 배지에 고초균 (Bacillus subtilis), 황국균(Aspergillus oryzae), 락토바실러스 아시도필루스(Lactobacillus acidophilus), 스트렙토코커스 서머필러스(Streptococcus thermophilus) 및 효모균(Saccharomyces cerevisiae)을 접종하여 발효시킨 기능성 발효녹차 복합생균제를 포함하고, 상기 배지 100 중량%에 대하여, 녹차는 10 내지 30 중량%이고, 홍삼박은 5 내지 30 중량%이고, 대두박은 30 내지 50 중량%이고, 옥수수는 10 내지 30 중량%이고, 소맥피는 10 내지 30중량%이고, 당밀은 1 내지 10 중량%인 것인 사육 단계별 양돈 사료 급여 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

647/1150 Row 647: application_number: 1020200088675, combined_string: invention_title: 유황 돼지 사료 abstract: 본 발명의 유황 돼지 사료는 옥수수, 탈지대두, 채종박, 주정박, 무화과 가루, 무독성 유황, 오가피, 타우린, 아세로라 및 구충제를 포함하되, 상기 옥수수는 64 내지 66 중량부이며, 상기 탈지대두는 8 내지 10 중량부이며, 상기 채종박은 5 내지 6 중량부이며, 상기 주정박은 18 내지 22 중량부이며, 상기 무화과 가루는 1.9 내지 2.3 중량부이며, 상기 무독성 유황은 2.8 내지 3.2 중량부이며, 상기 오가피는 1.9 내지 2.1 중량부이며, 상기 타우린은 0.7 내지 0.9 중량부이며, 상기 아세로라는 1.1 내지 1.3 중량부이며, 상기 구충제는 0.02 중량부인 것을 특징으로 한다. claims: 옥수수, 탈지대두, 채종박, 주정박, 무화과 가루, 무독성 유황, 오가피, 타우린, 아세로라 및 구충제를 포함하되,상기 옥수수는 64 내지 66 중량부이며, 상기 탈지대두는 8 내지 10 중량부이며, 상기 채종박은 5 내지 6 중량부이며, 상기 주정박은 18 내지 22 중량부이며, 상기 무화과 가루는 1.9 내지 2.3 중량부이며, 상기 무독성 유황은 2.8 내지 3.2 중량부이며, 상기 오가피는 1.9 내지 2.1 중량부이며, 상기 타우린은 0.7 내지 0.9 중량부이며, 상기 아세로라는 1.1 내지 1.3 중량부이며, 상기 구충제는 0.02 중량부인 것을 특징으로 하는 유황 돼지 사료., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

648/1150 Row 648: application_number: 1020200088208, combined_string: invention_title: 악취저감장치 abstract: 악취저감장치 함체에 설치된 흡기구를 통해 양돈축산시설 내부의 악취가 섞인 공기를 빨아들이고 EM균이 포함된 액체를 분사한 1개 내지 4개의 여과필터부를 통과하게 함으로써 공기중의 악취를 제거하고, 악취성분이 제거된 공기를 배기구를 통해 밖으로 배출시키며 다수의 여과필터에 의해 축산시설 내부에서 유입되는 가축털, 먼지 등을 막아 가축털, 먼지 등에 의해 발생하는 기계장치의 고장의 발생가능성을 낮추고 점검용 도어를 제공하여 사용자가 보다 용이하게 장치를 점검할 수 있게 하며, 여과필터를 프레임으로부터 고정걸쇠를 사용하여 쉽게 분리 가능하게 하여 여과필터의 교체를 사용자가 쉽게 할 수 있는 악취저감장치에 관한 것이다. claims: 악취저감장치에 있어서,악취저감장치(100)는 금속재질로 구성되어 밀폐되는 사각함체(10);악취를 함유한 공기를 상기 사각함체(10) 내부로 흡입하는 흡기구(20);상기 흡기구(20)를 통해 흡입된 악취를 함유한 공기를 여과하는 여과필터부(40);상기 여과필터부(40)를 결합하여 탈부착가능하게 하는 고정걸쇠(44);상기 여과필터부(40)는 먼지, 가축 털을 포함한 큰 입자를 걸러내는 1차여과필터(40a);상기 1차여과필터(40a)를 거치고 난 후 상기 1차여과필터(40a)보다 작은 타공으로 구성되어 유해물질을 걸러내는 2차여과필터(40b);상기 2차여과필터(40b)를 통해 여과된 공기를 상기 2차여과필터(40b)보다 세밀한 타공으로 구성되어 악취를 90% 내지 98% 제거하는 3차여과필터(40c);상기 여과필터부(40)를 지나 여과된 공기를 함체 외부로 배출하는 배기구(50);상기 배기구(50)에 설치되어 배기를 돕는 송풍기(51);상기 사각함체(10) 내부 하부에 위치되는 수조부(61);상기 수조부(61)에 저장된 액체를 외부로 배출할 수 있게 하는 밸브가 달린 토출구(85);상기 수조부(61)에 저장된 액체를 함체 내부에서 순환시키거나 배출하는 기능을 가진 수중모터펌프(60);상기 수조부(61)에 저장된 액체에 악취성분을 분해시키는 광합성균 및 고초균으로 구성된 EM균(62);상기 수중모터펌프(60)로부터 상기 수조부(61)에 저장된 액체를 전달받아 공급된 액체를 상기 여과필터부(40)에 분사하는 분사노즐(30);상기 사각함체(10)에 설치되어 사람이 드나들며 점검을 가능하게 하는 점검도어(55); 및상기 사각함체(10)에 설치되어 상기 수중모터펌프(60), 상기 송풍기(51) 및 상기 흡기구(20)의 동작을 외부에서 제어할 수 있는 컨트롤박스(70);를 포함하는 것을 특징으로 하는 악취저감장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

649/1150 Row 649: application_number: 1020200085354, combined_string: invention_title: 비육돈 후기 기간의 양돈 사양기법(飼養技法) 및 사료 abstract: 본 발명은 양돈 사양기법(飼養技法) 및 저농도 페닐알라닌 사료에 관한 것이다.본 발명에 따른 양돈 사양기법은 비육돈후기 기간(18-19주. 85±3kg ~ 24-25주. 120±3kg) 동안 법제유황을 자화수에 두당 1일 음수량을 기준으로 2~3g 첨가 용융시켜 급수하여 음용시킴으로서, 돈육의 육질을 극대화시키고, 또 출하 전 3~7일 동안 페닐알라닌 저감사료로 급이 한 후 출하함으로서 PHIP의 발생을 억제시킴을 특징으로 한다.이와 같은 본 발명은 법제유황(두당 : 2~3g)을 자화수에 첨가 용융시켜 돼지가 음용하게 함으로서 법제유황의 체내 흡수율을 극대화시키고, 이에 따라 돈육의 냄새, 육색, 다즙성, 연도 육미 등 육질 개선 및 사육현장의 악취 유발 가스의 감소 효과를 얻을 수 있다.또한 출하 전 최대 7일, 최소3일 동안 페닐알라닌 저감 사료를 급이 함으로서 PhIP의 발생을 억제할 수 있는 유리 페닐알라닌 농도가 저감된 돼지고기를 생산함으로서, 가열 조리에 의해 돼지고기 중에 발생하는 PhIP량을 저감할 수 있고, 이에 따라 PhIP가 하나의 요인이 되는 암의 발생을 억제할 수 있는 효과도 있다. claims: 비육돈후기에 해당하는 체중 85kg±3kg이 되는 생후 18-19주부터 체중 120kg±3kg이 되는 생후 24-25주 동안, 음용수로 사용되는 자화수에 용융시킨 법제유황을 두당 1일 2~3g 음용시키는 단계와, 출하 전 3~7일 동안 페닐알라닌이 첨가되지 않은 비육돈후기사료 또는 비육돈후기사료 1Kg 당 페닐알라닌이 3g이하로 첨가 혼합된 페닐알라닌 저감사료를 급이하는 단계를 포함하는, 돈육의 육질을 극대화시킴과 동시에 페닐이미다졸피리딘(PHIP)의 발생을 억제하기 위한 비육돈후기 기간의 양돈 사양기법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

650/1150 Row 650: application_number: 1020200066441, combined_string: invention_title: 냉방배관을 이용한 냉방시스템이 형성된 돈사 abstract: 본 발명은 냉방배관을 이용한 냉방시스템이 형성된 돈사에 관한 것으로서, 보다 상세하게는 돈사의 돈방에서 분뇨가 저장되는 공간 사이에 돼지들이 휴식을 취할 수 있는 휴식공간의 바닥면에서 콘크리트층 상부에 단열재를 배치하고, 단열재 상부에 고정용 와이어메쉬를 배치하며, 상기 와이어메쉬 상부에 냉방배관을 지그재그로 배치하고, 상기 냉방배관 상부에 두번째 와이어메쉬를 배치하고, 보호용 모르타르를 타설하여 냉방층을 형성하며, 관정에서 지열을 이용해 냉각된 물을 상기 냉방배관으로 공급하고 회수하며 휴식공간의 바닥면을 설정온도로 유지하여 냉방하는 냉방배관을 이용한 냉방시스템이 형성된 돈사에 관한 것이다. claims: 관정에서 유입된 차가운 물과 열교환하며 탱크(130)에서 유입되는 물을 냉각하는 냉각기(110)와; 상기 냉각기(110)와 탱크(130) 사이에서 물을 순환시키는 순환펌프(120)와; 돈방(10)에서 환수되는 물을 상기 냉각기(110)로 보내고, 상기 냉각기(110)의 차가운 냉수를 공급받는 탱크(130)와;상기 탱크(130)에서 배출되는 냉수의 통로가 되고 다수의 돈방(10)으로 냉수를 공급하는 공급배관(140)과;상기 돈방(10)에서 순환된 물을 환수하여 상기 탱크(130)로 이송하는 환수배관(150);을 포함하는 냉방시스템(100)이 형성되되;상기 돈방(10)의 분뇨처리부(11) 사이에 구비되는 휴식공간부(12)는 콘크리트층(210) 상부에 배치되는 단열재(220)와, 상기 단열재(220) 상부에 배치되는 와이어메쉬로 이루어지는 제1열전도판(230)과, 상기 공급배관(140) 및 환수배관(150)과 연결되고 상기 제1열전도판(230) 상부에서 지그재그 형태로 이격되어 배치되는 냉방배관(240)과, 상기 냉방배관(240) 상부에서 접촉되게 배치되는 와이어메쉬로 이루어지는 제2열전도판(250)과, 상기 제2열전도판(250) 상부에서 타설하는 보호용 모르타르(260)의 결합으로 이루어지는 냉방층(200)이 형성되되;상기 단열재(220) 상부에는 스페이서(270)가 서로 이격되어 배치되고, 상기 스페이서(270) 상부에는 제1열전도판(230)이 배치되며, 상기 제1열전도판(230) 상부 상기 스페이서(270)의 내측 안착면(271)에는 냉방배관(240)이 안착되고, 상기 냉방배관(240) 상부에 제2열전도판(250)이 접촉되게 배치되며,상기 제2열전도판(250)의 상부에는 서로 이격되어 다수개로 존재하고, 상기 제2열전도판(250) 하부에 위치하는 상기 냉방배관(240)의 상부에서 대응하게 마련되어 제2열전도판(250)와 접촉되어 냉기를 전도받으며, 상기 냉방배관(240) 및 제2열전도판(250)에서 방출하는 냉기를 보관하는 냉주머니(281)가 내부에 형성된 축열판(280)을 포함하는 냉방배관을 이용한 냉방시스템이 형성된 돈사., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

651/1150 Row 651: application_number: 1020200064335, combined_string: invention_title: 캡슐형 가축용 첨가제의 제조방법 abstract: 본 발명은 소나 돼지 등의 가축에게 급여하는 사료 첨가제에 관한 기술로서, 비타민, 미네랄 등의 첨가제 원료로 내용물을 조성하고, 그 외부에 사료를 조성하는 옥수수, 대두박, 소맥 등의 일반 원료로 외피를 만들어 캡슐형태로 가축용 첨가제를 구성함으로써, 기호성을 저하시키지 않고 급여시 편리성을 도모하며, 가축의 성장 단계별로 나타날 수 있는 질병 저항력과 면역력을 강화시켜 생산성을 높이는 캡슐형 가축용 첨가제의 제조방법에 관한 기술이다.이러한 본 발명의 제조방법은, 첨가제 원료를 각각 설정된 용량으로 계량하는 단계; 계량된 첨가제 원료를 혼합하는 단계; 사료 원료를 각각 미립자로 분쇄하는 단계; 분쇄된 사료 원료를 각각 설정된 용량으로 계량하는 단계; 계량된 사료 원료를 혼합하고, 이를 반죽하는 단계; 상기에서 혼합된 첨가제 원료로 내부 내용물을 만들고, 그 외부에 혼합 반죽된 사료 원료로 외피를 만들어 캡슐형태로 첨가제를 성형하는 단계; 캡슐형태로 성형된 첨가제를 고르게 익히는 단계; 및 골고루 익은 첨가제를 냉각하고, 살균 및 건조하는 단계;를 포함하여 구현된다. claims: 첨가제 원료를 각각 설정된 용량으로 계량하는 단계(F10); 계량된 첨가제 원료를 혼합하는 단계(F20); 사료 원료를 각각 미립자로 분쇄하는 단계(S10); 분쇄된 사료 원료를 각각 설정된 용량으로 계량하는 단계(S20); 계량된 사료 원료를 혼합하고, 이를 반죽하는 단계(S30); 상기에서 혼합된 첨가제 원료로 내부 내용물(300)을 만들고, 그 외부에 혼합 반죽된 사료 원료로 외피(200)를 만들어 캡슐형태로 첨가제를 성형하는 단계(S40); 캡슐형태로 성형된 첨가제를 고르게 익히는 단계(S50); 및 골고루 익은 첨가제를 냉각하고, 살균 및 건조하는 단계(S60);를 포함하며,상기 첨가제 원료를 계량하는 단계(F10)는, 계근기를 이용하여 비타민 45~50 중량%, 미네랄 40~45 중량%, 광물질 5~15 중량%로 각각 계량한 다음, 계량된 첨가제 원료를 혼합탱크에 모두 투입하고,상기 첨가제 원료를 혼합하는 단계(F20)는, 혼합탱크에 투입된 비타민, 미네랄, 광물질 첨가제 원료를 30분 이상 고르게 뒤섞어 혼합하며,상기 사료 원료를 분쇄하는 단계(S10)는, 입고된 옥수수, 대두박, 소맥 원료를 각각 분쇄기에 넣고, 50 메시~100 메시의 미세입자로 분쇄한 다음, 분쇄된 옥수수, 대두박, 소맥 분말을 각각 밀폐된 저장탱크에 담아 준비하고,상기 사료 원료를 계량하는 단계(S20)는, 저장탱크에 담긴 옥수수, 대두박, 소맥 분말원료를 각각 인출하고, 계근기를 이용하여 옥수수 40~45 중량%, 대두박 35~40 중량%, 소맥 15~25 중량%로 각각 계량한 다음, 계량된 분말원료를 교반탱크에 모두 투입하며,상기 사료 원료를 혼합하고, 반죽하는 단계(S30)는, 교반탱크에 투입된 옥수수, 대두박, 소맥 분말원료를 고르게 뒤섞어 혼합하며, 혼합된 분말원료 대비 규산액 35 중량%를 교반탱크에 넣고, 1시간 이상 교반하여 분말원료를 반죽하며, 상기 규산액은 물 95 중량%에 수용성 규산염 5 중량%가 용해된 알카리성을 사용하고,상기 캡슐형태로 첨가제를 성형하는 단계(S40)는, 혼합 반죽된 사료 원료를 성형기의 호퍼에 담아 준비하고, 혼합된 첨가제 원료를 성형기의 다른 호퍼에 담아 준비한 다음, 성형기를 통해 반죽된 사료 원료를 가래떡 형태로 압출하면서 그 내부에 일정한 간격으로 첨가제 원료를 주입하고, 압출 성형되는 사료 원료를 주입된 첨가제 원료의 사이사이 간격으로 커팅하여 캡슐형태로 첨가제를 성형하며,상기 캡슐형태로 성형된 첨가제를 익히는 단계(S50)는, 상기 성형된 캡슐형 첨가제를 컨베이어로 이송하여 오븐(oven)을 통과시켜 골고루 익히고, 이때 오븐은 170~180℃로 온도를 유지하며,상기 익힌 캡슐형 첨가제를 냉각하고, 상기 살균 및 건조하는 단계(S60)는, 오븐을 통과하여 골고루 익은 캡슐형 첨가제를 컨베이어로 이송하면서 송풍기를 통해 냉각하고, UV 자외선 살균기를 통과시켜 각종 유해성 세균을 살균 처리한 다음, 건조실로 이송해 수분 함량이 3% 이하로 건조하며,상기 건조하여 제조된 캡슐형 첨가제를 탱크에 넣고, 캡슐형 첨가제 대비 5 중량%의 사료 분말원료를 탱크에 넣은 다음, 15분 이상 섞어서 캡슐형 첨가제의 외부 표면에 사료 분말원료를 도포하며,튀김용 탱크에 팜유를 담고, 170℃ 이상으로 팜유를 가열한 다음, 사료 분말원료가 도포된 캡슐형 첨가제를 컨베이어로 이송하여 팜유에 투입하고, 3.5초 이상 튀김 과정을 거친 후, 컨베이어로 이송하면서 송풍기를 통해 냉각하는 것을 특징으로 하는 캡슐형 가축용 첨가제의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

652/1150 Row 652: application_number: 1020200050746, combined_string: invention_title: 악취제거 가축분뇨 발효비료와 이의 가공방법 abstract: 본 발명의 '악취제거 가축분뇨 발효비료'는 강산성수용액으로 악취를 소멸시키고 발효시켜 유기질비료로 재활용되도록 가공하는 발명인데 그동안은 처리하지 않고 쉽게 해양투기를 해 왔으나 국제법상 투기가 금지되어 국내에서 문제가 되고 있고 특히 돼지분뇨는 악취가 심하여 논밭에 살포도 허가를 받는 등 심히 어려운 처지에 놓인 축산분뇨를 유기질비료로 가공하기 위해 발효를 택하여 실시하는 악취제거와 발효로 어려움에 처한 축산분뇨의 처리방법에 관한 발명이다,가장 먼저 처리할 문제는 악취로서 수거할 때 미리 전처리로 강산성수용액을 살포한 후 축산분뇨처리장으로 운반하여 후처리로 강산성수용액을 추가한 후 악취제거를 확실히 하기 위해 7 내지 10일간 자연발효를 시키면 손으로 만져도 냄새가 없어서 분말로 논밭에 살포하거나 시설재배영농에도 사용할 수 있는 유기질비료로 기공하는 축산분뇨 발효유기질비료 가공에 관한 제조기술에 속하는 분야이다,본 발명에서 재활용 축산분뇨비료로 제공하므로 인하여 악취로 인한 폐기물 처리도 어려운 축산분뇨가 비료로 제조됨은 물론 해양투기도 할 필요 없이 재활용 비료로 제조되어 축산농가의 고민도 해결되고 유기질비료도 얻게 되어 축산농민과 유기질비료를 필요로 하는 영농농민들에게 희소식이 되는 효과가 기대된다, [색인어]유수분리, 가축액비(家畜液肥), 유기질비료, 재활용비료,축산분뇨, 가축구비(家畜), 황화철수용액, 부루-민수용액,계분(鷄糞), 우분(牛糞), claims: 계분, 우분 또는 돼지분뇨를 일정량씩 트럭적재함 또는 탱크로리로 이송하기 직전 황화철수용액(10)으로 전처리(제1공정)하며 처리장소로 이송하고, 상기 돼지분뇨는 유수분리(제2공정)시켜 얻은 액비와 구비 중에 상기 액비는 상기 구비와 분리하여 부루-민수용액(20)으로 액비후처리(제4-1공정)한 후 액비숙성(제6-1공정)과 액비포장(제7-1공정)으로 악취 없는 가축액비로 가공하고,상기 계분과 우분은 상기 전처리를 거치면서 상기 유수분리 없이 수거하여 상기 돼지분뇨에서 분리수거 된 상기 돼지구비와 함께 혼합수집(제3공정)에서 혼합하며 상기 부루-민수용액으로 구비후처리(제4-2공정)를 하고 일정기간의 혼합발효(제5공정)와 구비숙성(제6-2공정)으로 가축구비가 제조되고, 제조된 상기 가축구비를 구비포장(제7-1공정)시켜 유기질비료로 재활용되는 것이 특징인 악취제거 가축분뇨 발효비료 가공방법돼지분뇨를 일정량씩 수거용 차량탱크로리에 담고 상기 돼지분뇨에 1 내지 2중량%의 황화철수용액(10)을 첨가하는 전처리(제1공정)로 가공공장에 이송하고, 이송 시마다 상기 돼지분뇨를 유수분리(제2공정)시키고,상기 유수분리로 수거된 액비를 제외한 돼지구비만 별도 수거하고, 상기 전처리로 별도 수거된 우분과 계분의 구비도 혼합수집(제3공정)하고 구비후처리(제4-2공정)에서 부루-민수용액(20) 1중량%를 10배의 물로 희석시켜 살포하여 3일간은 뒤집고 7일간은 공기만 주입하며 혼합발효(제5공정)로 제조된 발효구비를 구비숙성(제6-2공정)으로 완숙시켜 구비포장(제7-2공정)으로 유기질비료로 재활용되는 것이 특징인 악취제거 가축분뇨 발효비료, Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

653/1150 Row 653: application_number: 1020200044957, combined_string: invention_title: 솔잎추출물을 함유하는 돼지사료 제조방법 abstract: 본 발명은 솔잎추출물을 함유하는 돼지사료 제조방법에 관한 것으로서, (A) 솔잎을 세척한 후, 열풍건조기 측 60~80℃에서 2~3시간 동안 건조 처리하거나 또는 드라이오븐 측 70~80℃에서 1~2시간 동안 건조 처리하는 단계; (B) 상기 건조된 솔잎을 분쇄기로 마쇄 처리함으로써 솔잎분말로 만드는 단계; (C) 해조류를 세척 탈염한 후, 열풍건조기 측 60~70℃에서 1~2시간 동안 건조 처리하거나 또는 드라이오븐 측 60~65℃에서 30~60분 동안 건조 처리하는 단계; (D) 상기 건조된 해조류를 분쇄기로 마쇄 처리함으로써 해조류분말로 만드는 단계; (E) 상기 솔잎분말과 물을 열수추출기에 투입한 상태에 110~130℃에서 30~40분 동안 열수추출한 후, 이를 감압여과장치를 통해 감압 여과함으로써 제1솔잎추출물을 얻어내는 단계; (F) 상기 솔잎분말을 아임계 추출장치 측 추출용기 내에 투입하여 아임계 추출방식으로 제2솔잎추출물을 얻어내되, 상기 아임계 추출장치는 이산화탄소유체를 60~80kgf/cm3의 압력으로 공급하는 유체공급부가 상기 추출용기의 일측에 연결되고 타측에는 제1회수기가 연결되며, 상기 제1회수기에 일측이 연결되고 타측이 순환라인에 연결되는 제2회수기를 갖는 상태에서 제1회수기 측 70~80℃ 온도와 제2회수기 측 110~120℃ 온도로 3~4시간 동안 추출한 후, 이를 감압여과장치를 통해 감압 여과함으로써 제2솔잎추출물을 얻어내는 단계; (G) 상기 해조류분말과 물을 열수추출기에 투입한 상태에 100~110℃에서 2~3시간 동안 열수추출한 후, 주정 침지방식과 한외여과방식을 연속 실시하는 정제과정을 거쳐 해조류추출물을 얻어내는 단계; (H) 상기 제1솔잎추출물과 제2솔잎추출물 및 해조류추출물을 돼지사료의 베이스원료에 혼합하는 단계; (I) 상기 혼합재료를 펠릿으로 성형하는 단계; (J) 상기 성형 펠릿을 동결 건조시키는 단계;를 포함하는 것을 특징으로 한다.본 발명에 따르면, 항균과 항바이러스 및 항산화 특성을 갖는 솔잎추출물을 함유하는 돼지사료를 제조할 수 있으며, 기존에 비해 항생제 등을 사용하지 않아 사료에 대한 안전성을 확보할 수 있으면서 친환경 재료를 사용하는 방식에 의한 친환경 돼지사료를 제조할 수 있다. claims: (A) 솔잎을 세척한 후, 열풍건조기 측 60~80℃에서 2~3시간 동안 건조 처리하거나 또는 드라이오븐 측 70~80℃에서 1~2시간 동안 건조 처리하는 단계;(B) 상기 건조된 솔잎을 분쇄기로 마쇄 처리함으로써 솔잎분말로 만드는 단계;(C) 해조류를 세척 탈염한 후, 열풍건조기 측 60~70℃에서 1~2시간 동안 건조 처리하거나 또는 드라이오븐 측 60~65℃에서 30~60분 동안 건조 처리하는 단계;(D) 상기 건조된 해조류를 분쇄기로 마쇄 처리함으로써 해조류분말로 만드는 단계;(E) 상기 솔잎분말과 물을 열수추출기에 투입한 상태에 110~130℃에서 30~40분 동안 열수추출한 후, 이를 감압여과장치를 통해 감압 여과함으로써 제1솔잎추출물을 얻어내는 단계;(F) 상기 솔잎분말을 아임계 추출장치 측 추출용기 내에 투입하여 아임계 추출방식으로 제2솔잎추출물을 얻어내되, 상기 아임계 추출장치는 이산화탄소유체를 60~80kgf/cm3의 압력으로 공급하는 유체공급부가 상기 추출용기의 일측에 연결되고 타측에는 제1회수기가 연결되며, 상기 제1회수기에 일측이 연결되고 타측이 순환라인에 연결되는 제2회수기를 갖는 상태에서 제1회수기 측 70~80℃ 온도와 제2회수기 측 110~120℃ 온도로 3~4시간 동안 추출한 후, 이를 감압여과장치를 통해 감압 여과함으로써 제2솔잎추출물을 얻어내는 단계;(G) 상기 해조류분말과 물을 열수추출기에 투입한 상태에 100~110℃에서 2~3시간 동안 열수추출한 후, 주정 침지방식과 한외여과방식을 연속 실시하는 정제과정을 거쳐 해조류추출물을 얻어내는 단계;(H) 상기 제1솔잎추출물과 제2솔잎추출물 및 해조류추출물을 돼지사료의 베이스원료에 혼합하는 단계;(I) 상기 (H) 단계의 혼합재료를 펠릿으로 성형하는 단계;(J) 상기 성형 펠릿을 동결 건조시키는 단계; 를 포함하며,상기 (G)단계에서는,열수추출한 해조류추출물에 대해 진공 농축기로 보내 600~650mmHg 및 50~60℃ 조건에서 감압 농축한 후, 70~80%의 농도 및 3~5℃의 온도를 갖는 알콜에 침지시켜 12~15시간 동안 주정 침지하는 단계;주정 침지를 마친 해조류추출물을 원심분리하되, 침전물을 증류수에 녹인 후 투석(dialysis) 처리하는 단계;원심분리 후 투석 처리를 마친 해조류추출물을 한외여과장치로 보내 일정 이상의 분자량을 갖는 고분자물질로 분리 정제함으로써 면역활성물질의 활성을 증대시킨 해조류추출물을 얻어내는 단계; 를 포함하는 것을 특징으로 하는 솔잎추출물을 함유하는 돼지사료 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

654/1150 Row 654: application_number: 1020200029823, combined_string: invention_title: 스마트팜 양돈 시스템 및 방법 abstract: 스마트팜 양돈 시스템 및 방법이 개시된다. 스마트팜 양돈 시스템은 유저 단말로부터 사용자 조작에 따른 돼지의 축사 변동 사항을 제공받는 유저 대응부; 및 상기 축사 변동 사항에 관한 정보가 상응하는 돼지의 사육 데이터에 추가되도록 상기 사육 데이터를 갱신하는 데이터 갱신부를 포함한다. claims: 유저 단말로부터 사용자 조작에 따른 돼지의 축사 변동 사항을 제공받는 유저 대응부; 및상기 축사 변동 사항에 관한 정보가 상응하는 돼지의 사육 데이터에 추가되도록 상기 사육 데이터를 갱신하는 데이터 갱신부를 포함하되,상기 유저 단말에는 실제 양돈 현장의 실제 구획 영역인 돈사와 돈방에 대응되는 가상의 구획 영역과, 실제 양돈 현장의 돼지 배치 상황에 대응되도록 각 가상의 구획 영역에 개체 이미지가 표시된 GUI(Graphical User Interface) 환경의 관리 화면이 표시되고,가상의 구획 영역에 표시되는 개체 이미지는 상응하는 돼지의 식별정보에 대응되도록 관리되며, 실제 양돈 현장에서의 축사 이동 대상인 돼지에 상응하는 개체 이미지를 어느 하나의 가상의 구획 영역에서 다른 가상의 구획 영역으로 드래그 앤 드롭(Drag and Drop) 방식으로 이동시키는 것에 의해 상기 축사 변동 사항이 입력되고,상기 데이터 갱신부는 상기 사육 데이터가 돼지의 전체 생육 기간 동안의 정보 연속성이 유지되도록 하기 위해, 상기 축사 변동 사항에 상응하도록 이동된 실제 구획 영역에 대응되도록 수집된 부가 정보가 상기 사육 데이터에 더 추가되도록 상기 사육 데이터를 갱신하는 것을 특징으로 하는 스마트팜 양돈 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

655/1150 Row 655: application_number: 1020200028703, combined_string: invention_title: 우수가림막과 다층구조의 태양광 엘이디조명등이 구비된 끈끈이 해충 포획 및 야생동물 퇴치 트랩 abstract: 본 발명은 파리, 모기, 나방 등과 같은 각종 해충포획과 까치, 참새, 까마귀, 찌르레기 등의 위해조류와 고라니, 멧돼지, 너구리, 노루 등의 야생동물을 퇴치하는 용도로 사용하는 우수가림막과 다층구조의 태양광 led조명등이 구비된 끈끈이 해충 포획 및 야생동물 퇴치 트랩에 관한 것으로서, 태양광이 투영되고 해충이 유입될 수 있는 복수의 유입구가 형성되는 통 형상의 망과 상기 망의 외부이며 상부에 형성되는 하부의 일정부분이 개방된 고리에 요입되어 형성되는 태양광이 투영되고 우수를 차단할수 있는 원형판 형상의 우수가림막과 상기 망의 내부에 형성되는 통 형상의 투명한 용기와 상기 용기의 내부에 구비된 태양광에너지를 이용한 led백색광과 led자외선(UVA)광이 수직과 수평으로 조합된 다층구조의 태양광 led조명등과, 상부조명등의 하단이며 중간조명등의 상부 사이에 조명을 투과 또는 차단할 수 있는 탈부착식 불투명 원형판 형상의 조명차단판과, 투명한 용기의 외부에 일정 간격 이격되어 덮어씌워진 태양광이 투과될 수 있는 투명 또는 반투명과 해충이 선호하는 색상이 반복적으로 채색된 줄무늬 형상의 끈끈이 해충유인 솔라백시트의 수직측면의 중앙부를 관통하여 구비된 복수의 페르몬향 또는 야생동물 기피제조성물향 분출구에서 발산되는 페르몬 및 led 백색광과 자외선(UVA)광에 의한 광선 파장으로 포충 점착액이 도포된 솔라백 시트로 해충유인 포획하거나, led 백색광과 자외선(UVA)광에 의한 광선파장과 트랩의 내부에 구비하는 야생동물 기피제 조성물향을 복수의 분출구에서 주변으로 확산하여 야생동물을 퇴치하는 것으로서, 태양광에너지를 활용하여 해충을 유인하는 친환경적이며, 수직 공간활용을 위한 수직형태의 통형상의 끈끈이 해충유인 솔라백시트가 받침대 상부에 형성되어 공간활용을 극대화하고, 우수를 차단할수 있는 원형판 형상의 우수가림막 으로 인한 상기 끈끈이 해충유인 솔라백시트의 점착성능의 감소를 방지하고, 태양광이 투과되는 투명한 용기와 끈끈이 해충유인 솔라백시트 전체의 외부표면으로 조명을 확대하고, 해충 방제 효과 향상을 위한 파장이 다른 led 백색광과 자외선(UVA)광 led램프의 조명으로 해충을 유인할 수 있는 다층구조의 조명등 구조이며, 투명한 용기와 근끈이 시트의 수직측면 중앙부를 관통하여 구비된 복수의 페르몬향 또는 야생동물 기피제조성물향 분출구 주변인 끈끈이 시트 중앙부 인근으로 농작물 재배시에는 태양광 led 조명등인 led 백색광과 자외선(UVA)광과 투명 또는 반투명과 해충이 선호하는 색상이 반복적으로 채색된 줄무늬 형상의 점착포충물질이 도포된 끈끈이 해충유인 솔라백시트 및 페르몬향에 의해 해충을 빠르게 유인하여 해충을 포획하고, 상기 끈끈이 해충유인 솔라백시트점에 의한 지속적인 해충의 포획으로 led 백색광과 자외선(UVA)광 및 페르몬에 의하여 유인된 해충이 포획트랩 주변을 배회하지 않도록 하며, 농작물 수확시기에는 태양광 led 조명등인 led백색광과 led자외선(UVA)광이 수직과 수평으로 조합된 다층구조의 태양광 led조명등과, 투명 또는 반투명과 해충이 선호하는 색상이 반복적으로 채색된 줄무늬 형상의 점착포충물질이 도포된 끈끈이 해충유인 솔라백시트의 간헐적으로 접촉했던 조류 등의 야생동물이 기피하게 되는 학습효과와 상기 솔라백시트를 투과하는 led백색광과 led자외선(UVA)광과 야생동물 기피제 조성물향에 의해 효율적으로 야생동물을 퇴치하는 트랩이며, 조명등이 투명한 끈끈이 시트 내부에 있으므로 작은 해충이나 곤충이 조명등에 들러 붙지 않으며, 끈끈이 시트의 해충포집으로 인한 태양광 투과량이 적더라도 조명등이 소등되어 조명시간이 줄어들지 않도록 다층구조의 조명으로 충분한 조명시간을 확보하며, 태양광에너지를 이용한 led램프의 조명으로 전력소비가 적으며 전기 공급이 원활하지 않은 산악 지역 등에서도 그 활용도가 향상되며, 사멸된 해충포집으로 끈끈이 시트의 투명도가 저하되거나, 시간이 경과되어 점착액이 경화되어 소모된 끈끈이 시트만 편리하게 교체하여 장기간 사용할 수 있으며, 받침대에 의한 축사나 농경지의 바닥에 설치하거나, 고리에 의한 비닐하우스의 천정 또는 수목의 상부에 매달거나, 하부의 지지대 결합부에 의한 농작물 직상부에 설치할 수 있는 구조로서 농경지나 축사 뿐 만아니라주택의 보안등과 해충포집을 겸용으로 사용할 수도 있으므로 사용장소와 용도에 따라 다양하게 사용될 수 있는 다용도를 가지는 해충포획 및 야생동물 퇴치트랩에 관한 것이다. claims: 태양광이 투영되고 해충이 유입될 수 있는 복수의 유입구가 형성되는 망 형태로서 통 형상의 제1케이싱과; 상부에 내부와 연통되는 개구부가 형성되며, 마개에 의하여 개폐되는 통 형상의 투명한 제2케이싱과; 상기 제2케이싱의 내부에 수용되며 하부에 내부와 연통되는 개구부가 형성되며, 마개에 의하여 개폐되는 통을 뒤집어 놓은 형상의 투명한 제3케이싱과; 상기 제2케이싱을 감싸며 외면에는 점착액이 도포된 투명 또는 반투명과 해충이 선호하는 색상이 반복적으로 채색된 줄무늬 형상의 끈끈이 해충유인 솔라백시트와; 상기 끈끈이 해충유인 솔라백 시트의 좌측과 우측 상부의 처짐을 방지하기 위하여 상기 제2케이싱의 개구부의 나사부에 요입되어 하단면에 설치되어 마개로 고정되는 원형판 형상으로 원형 링형태의 솔라백 시트 지지대와; 상기 제2케이싱의 하단 내측면 상부에 설치되는 페르몬 또는 기피제조성물 약제통과; 상기 제2케이싱과 끈끈이 해충유인 솔라백 시트의 수직측면의 중앙부위를 관통하여 제2케이싱 내부 기류가 끈끈이 시트의 중앙부위에서 외부로 분출될 수 있는 복수의 페르몬향 또는 야생동물 기피제조성물향 분출구와; 상기 제1케이싱을 고정하고 지지하며, 상기 제1케이싱을 고정하고 지지하는 제1받침대와; 상기 제1받침대 내부에 고정되어 수용되며, 상기제2케이싱과 제3케이싱을 고정하고 지지하는 제2받침대와; 상기 제2케이싱의 마개에 관통홀을 형성하여 설치되는 제1조명기기와; 상기 제1조명기기의 하부에 일정간격 이격되어 상기 제2케이싱의 내부이며, 상기 제3케이싱의 외부인 상단에 결합되는 제2조명기기와; 상기 제2조명기기와 상호 대향되도록 태양광을 등지고, 상기 제3케이싱의 내부에 설치되는 제3조명기기와; 상기 제2케이싱의 내부이고, 상기 제2조명기기 하부이며, 제3케이싱의 외부상단 좌측에 수평으로 설치되는 제4조명기기와; 상기 제4조명기기와 대향되게 수평으로 우측에 설치되는 제5조명기기와; 상기 제3조명기기의 하부에 일정간격 이격되어 제3케이싱의 마개 내부 면에 설치되는 태양광 반사경과; 상기 제1케이싱을 지면위의 고정물체에 메달 수 있도록 하부의 일정부분이 개방되어 고정설치되는 환봉형상의 고리 체결부와; 상기 고리 체결부의 하부에 개방된 환봉형상의 고리를 관통하여 요입되어 상기 제1케이싱의 외부이며 상부에 설치되는 설치되는 태양광이 투영되고 우수를 차단할수 있는 원형판 형상의 우수가림막과; 상기 제1케이싱과 제2케이싱과 제3케이싱을 상기 받침대에 결합부재로 고정하기 위한 결합부;를 포함하며,상기 제1조명기기와 제2조명기기 및 제3조명기기는 독립형 태양광 전지모듈 기판 및 램프를 통형상의 투명한 용기의 내부에 수직형태이고, 상기 제4조명기기와 제5조명기기는 수평형태인 다층구조로 형성하여 조명을 투명한 용기 전체의 외부표면으로 발산하는 구조이며, 상기 제1조명기기와 제2조명기기 와 제3조명기기 및 제4조명기기와 제5조명기기는 태양광을 집적하여 전력을 생산하는 태양광 전지모듈 기판과 상기 태양광 전지모듈 기판을 견고하게 고정할 수 있는 태양광 전지모듈 지지판과 상기 태양광 전지모듈 기판에서 생산된 전력을 충전할 수 있는 커페시터와, 상기 커페시터로부터 전력을 공급받아 빛을 조사하는 led램프와, 상기 태양광 전지모듈 기판의 수광면에 구비되어 주간에는 생산된 전력을 상기 커페시터에 충전하고 일몰 후에는 상기 led램프의 점등토록 하는 조도센서와, 상기 커페시터의 충전 및 led램프 점등을 제어하는 제어부와, 상기 커페시터, led램프, 제어부를 고정하여 상기 태양광 전지모듈 지지판에 결합부재로 체결되는 조명기판으로 구성되고, 상기 제1조명기기와 제2조명기기 와 제3조명기기에는 투과되는 빛을 굴절시켜 확산시킬 수 있는 빛이 투과되는 재질로서 상기 led램프를 보호하는 조명커버가 구성되며, 상기 제1조명기기의 상기 조명커버 외부의 하단에는 불투명 재질의 원형판 형상의 탈부착식이 가능한 구조의 조명차단판이 밀착고정되어 구성되고, 상기 페르몬향 또는 기피제조성물향 분출구는 중심부에 관통홀이 형성되어 통형상의 투명한 용기와 끈끈이 해충유인 솔라백 시트의 수직측면의 중앙을 관통하여 설치되고, 상기 제2케이싱내의 하부에 형성된 관통홀에 외경보다 적은 구멍이 형성된 수축성 고무부싱 또는 실리콘 부싱 등을 설치하여 부싱내의 구멍에 삽입하여 설치되는 페르몬향 또는 야생동물 기피제조성물향이 내부에 요입되어 설치될 수 있는 약제통이 구성되는 것을 특징으로 하는 우수가림막과 태양광led조명등이 구비되는 끈끈이 해충포획트랩.제1항에 있어서. 상기 제1조명기기의 led램프와 제2조명기기의 led램프와 제3조명기기의 led램프 및 제4조명기기의 led램프와 제5조명기기의 led램프는 해충별 유인효과 향상을 위하여 백색광을 포함하는 1개 이상의 색상별 led 소자 또는 RGB 3원색 led 소자 또는 자외선(UVA)led소자로 구성되는 것을 특징으로 하는 우수가림막과 다층구조의 태양광 led조명등이 구비된 끈끈이 해충 포획 및 야생동물 퇴치 트랩. 제2항에 있어서. 상기 우수가림판은 투명하고 유연성이 있는 재질로서, 태양광 투과가 용이하고, 태양광의 자외선에 의한 변색이 되지 않으며, 전단강도가 우수하며, 우수에 의한 먼지 등의 부착착이 최소화 될 수 있는 제전비닐(ESD) 등의 합성수지계열이 바람직하나, 반드시 그러한 것은 아니며, 상기 체결링을 체결하기 위하여 상기 우수가림판의 원주의 외축 끝단으로부터 체결링의 내경만큼 이격되어 외측 관통홀을 일정한 간격의 방사상으로 4개소이상 형성하며, 중심부에는 상기 중앙지지대가 삽입되어 설치될 수 있도록 중심 관통홀가 형성되며,상기 외측 관통홀은 바람 등의 외력에 의한 반복적인 변형과 원상회복에도 상기 우수가림판의 관통홀이 전단력에 의하여 파손되지 않도록 상기 관통홀의 직경은 2~5mm이며,상기 중앙지지대는 상부의 뚜껑과 하부의 몸체로 형성되는 상하 분리형태로서 상부 뚜껑의 외측돌기와 하부 몸체의 내측돌기를 이용한 압입 고정방식이므로 상기 중앙지지대의 외경보다 적고, 내경보다는 크게 형성되어 상기 우수가림판의 일정부분이 상기 중앙지지대의 상부 뚜껑과 하부 몸체 사이에 겹쳐서 고정되기 위한 것으로서, 상기 중앙지지대는 고리체결부의 지지대의 상부면에 지지되어 상기 우수 가림막의 중심을 유지하고 지지하며 바람 등의 외력에 의한 변형을 최소화 하기 위하여 회전이 가능한 형태로서, 중심부에 관통홀)이 형성되어 상기 고리체결부의 하부 개방공간을 이용하여 고리에 요입 설치되며, 상부의 뚜껑과 하부의 몸체로 형성되는 상하 분리형태로서 상부 뚜껑의 상기 관통홀 주변의 돌출부에 형성된 외측돌기와 하부 몸체의 관통홀 주변의 돌출부에 형성되는 내측돌기를 이용한 압입 고정방식이며, 상부 뚜껑과 하부 몸체의 돌출부의 외경은 상기 중앙지지대의 상부 뚜껑과 하부 몸체의 외경보다 10~20mm 적게 형성되는 것이며, 상기 중앙지지대(105b)의 재질은 부식이 되지 않으며, 성형가공이 가능한 재질로서 폴리에틸렌, 폴리카보네이트 등의 합성수지, 황동, 청동 등의 비철합금이 바람직하며,상기 탄성링은 상기 우수가림판이 바람 등의 외력에 의한 변형후에도 원형상태를 유지하기 위하여 상기 우수가림판의 원주 외측에 후술되는 체결링으로 연결하는 것으로서, 반복적인 변형에도 원형상태를 유지하기 위하여 탄성이 있으며, 습기에 노출되어도 부식이 되지 않으며, 햇빛에 경화되지 않는 재질인 스테인레스 선재, 아연도금 탄소강 선재를 단면이 환봉형태 또는 직사각형태로 제작하여 원형 형상이 유지될 수 있도록 압착클립을 이용하여 연결하는 것이 바람직하나, 단면이 직사각형태가 반복적인 탄성복원력측면에서는 원형단면보다는 유리하다 할 것이다. 전기 압접 방식 등의 용접방식을 활용할 수도 있으나, 용접부위의 경화로 인한 탄성력 저하로 반복적인 변형으로 인한 파손을 방지할 수 있는 열처리를 하는 것도 바람직하며. 상기 체결링은 상기 우수가림판에 외측에 방사상으로 형성된 관통홀을 관통하여 상기 탄성링을 상기 체결링 내측에 인입하여 연결하기 위한 것으로 개폐가 가능하여야 하며, 비틀림 외력에 의한 개폐가 가능하되, 바람등의 외력에 의한 탄성링의 측면외력에는 개방이 되지 않독 개폐부에 돌출부가 형성되고 습기에 부식이 되지 않는 재질로서 아연도금이나 스테인레스 재질의 시중 판매제품인 카드링 등이 바람직한 것을 특징으로 하는 우수가림막과 태양광led조명등이 구비된 해충포획 및 야생동물퇴치 트랩. 제1항에 있어서상기 조명커버의 하부 중앙에는 관통홀이 형성되며, 상기 관통홀의 하부에 설치되는 조명차단판은 설치와 분리가 용이한 탈착식의 조명반사부결합부재의 볼트부를 상기 관통홀를 관통하여 너트 등으로 밀착되도록 고정설치하여 상기 제1조명기기의 조명을 차단하여 상기 제2조명기기의 상기 태양광전지모듈 기판에 내장되어 있는 조도센서가 점등(방전)동작할 수 있도록 하는 것이며, 상기 조명차단판을 분리하여 제거하였을 경우에는 상기 제1조명기기의 led램프 빛이 관통되어 상기 태양광전지모듈 기판에 내장되어 있는 조도센서가 소등(충전)동작할 수 있도록 관통공이 형성되는 것이며, 상기 조명커버는 상기 led램프를 보호하는 역할을 하는 것으로 배광이 확산될 수 있도록 성형가공이 가능한 투명한 유리, 아크릴, 합성수지 등의 재질이 바람직하며. 상기 조명차단판은 탈부착이 용이하고, 상기 제2케이싱의 개구부보다 적으며 상기 태양광전지판넬 지지판(162)보다는 크게 형성된 원판형 구조로서, 재질은 불투명한 폴리카보네이트(pc), 패트(PET), 등의 합성수지 계열이 바람직하며, 다층구조의 태양광 led 조명등의 백색광과 자외선광(UVA)의 효율적인 조합을 위하여 상기 제1조명기기의 조명커버(167)하단에 설치하여 상기 제2조명기기의 점등과 소등을 자유롭게 선택할 수 있으므로 태양광 조도가 낮은 시설하우스나 비닐하우스내의 예비전력사용과 노지의 경작지에서의 상시전력으로 선택적으로 활용함으로서 해충포획효율을 향상시킬 수 있는 것을 특징으로 하는 우수가림막과 태양광led조명등이 구비된 해충포획 및 야생동물퇴치 트랩., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

656/1150 Row 656: application_number: 1020200023787, combined_string: invention_title: 돈육 떡갈비 및 이의 제조방법 abstract: 본 발명은 황설탕, 백설탕, 간장, 물, 매실청원액, 대파, 사과 및 생강을 190~210 : 130~140 : 280~300 : 160~170 : 45~55 : 45~55 : 23~27 : 23~27의 중량비율로 혼합하여 가열하여 졸여서 1차 양념장을 제조하는 단계; 참기름, 후추, 된장, 간생강, 간마늘, 양파, 대파, 불린 표고버섯, 배 및 상기 1차 양념장을 23~27 : 13~17 : 105~115 : 45~55 : 195~205 : 195~205 : 145~155 : 195~205 : 48~52 : 590~610의 중량비율로 혼합하여 2차 양념장을 제조하는 단계; 돈전지채, 우지방 및 상기 2차 양념장을 3,490~3,510 : 345~355 : 1,615~1,635의 중량비율로 버무려서 치대어 떡갈비 반죽을 제조하는 단계; 및 상기 떡갈비 반죽을 원하는 양으로 떼내어 원하는 형태로 성형하는 단계;를 포함하는 돈육 떡갈비 및 이의 제조방법에 관한 것이다. 본 발명에 의하면, 돈육의 육질을 잘 살림과 아울러, 맛의 조화를 통해서 뛰어난 맛과 식감을 제공할 수 있고, 자극적인 맛을 최소화하면서도 떡갈비의 영양학적인 조화가 이루어지도록 하여 식단의 웰빙화에 기여할 수 있으며, 떡갈비의 외형 유지력이 뛰어나면서도 식욕의 자극을 통한 돈육 떡갈비의 기호도를 향상시킬 수 있다. claims: 황설탕, 백설탕, 간장, 물, 매실청원액, 대파, 사과 및 생강을 190~210 : 130~140 : 280~300 : 160~170 : 45~55 : 45~55 : 23~27 : 23~27의 중량비율로 혼합하고 가열하여 졸인 후 건더기를 제거하고 냉각하여 1차 양념장을 제조하는 단계;참기름, 후추, 된장, 간생강, 간마늘, 양파, 대파, 불린 표고버섯, 배 및 상기 1차 양념장을 23~27 : 13~17 : 105~115 : 45~55 : 195~205 : 195~205 : 145~155 : 195~205 : 48~52 : 590~610의 중량비율로 혼합하여 2차 양념장을 제조하는 단계;돈전지채, 우지방 및 상기 2차 양념장을 3,490~3,510 : 345~355 : 1,615~1,635의 중량비율로 버무려서 치대어 떡갈비 반죽을 제조하는 단계; 상기 떡갈비 반죽을 원하는 양으로 떼내어 원하는 형태로 성형하는 단계;상기 성형을 마친 떡갈비를 -2 ~ -0.5℃의 냉장 보관하는 단계; 및 상기 냉장 보관한 떡갈비를 냉장고로부터 꺼내어 어도리기계의 석쇠에 위치시킨 다음, 석쇠 위의 떡갈비에 떡갈비소스를 펴바른 다음, 어도리기계 내에서 4~6분 동안 1차로 구워내고, 1차로 구워진 떡갈비를 뒤집어서 떡갈비소스를 펴바른 다음, 어도리기계 내에서 4~6분 동안 2차로 구워내고, 어도리기계 내에서 1~2분 동안 구워내는 단계;를 포함하며,상기 2차 양념장을 제조하는 단계는,상기 양파를 껍질 깐 상태로 사용하고, 상기 배를 껍질채 사용하되, 씨를 제거하며, 상기 양파와 상기 배를 칼로 1~3mm 이내의 크기로 다져서 사용하고, 상기 표고버섯을 끓는 물에 불린 후, 식혀서 물기를 짜낸 다음, 절단하여 분쇄하여 사용하며, 상기 대파를 1~3mm 이내의 크기로 다져서 사용하고, 상기 된장으로서 합동된장과 간생강을 핸드믹서로 갈아서 사용하고, 상기 떡갈비 반죽을 제조하는 단계는,돈전지를 냉장시설 내에서 길이 3~5cm 및 두께 1~3mm로 채 썰어 상기 돈전지채로서 사용하고, 상기 돈전지채, 상기 우지방 및 상기 2차 양념장을 버무려서 치대는, 돈육 떡갈비의 제조방법.청구항 1 내지 청구항 3 중 어느 한 항에 기재된 돈육 떡갈비의 제조방법에 의해 제조되는 돈육 떡갈비., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

657/1150 Row 657: application_number: 1020200022813, combined_string: invention_title: 전염병으로 인해 살처분되어 매몰된 동물사체의 매몰지 소멸화 고속처리공정 abstract: 본 발명은 전염병으로 인해 살처분되어 매몰된 동물사체의 매몰지 소멸화 고속처리공정에 관한 것으로, 그 구성은 전염병으로 인해서 살처분된 동물사체를 파쇄하는 파쇄단계와, 상기 파쇄단계를 거친 동물사체를 습식으로 열처리하여 멸균시키는 습식열처리멸균단계와, 상기 습식열처리멸균단계를 거친 동물사체를 고속 발효탱크에서 발효시키는 고속발효단계와, 상기 고속발효단계를 거친 동물사체와 부속물을 포장하여 퇴비로 이송시키는 퇴비이송단계를 포함하되, 상기 고속 발효탱크는, 상면이 개방되며, 하단은 지표면과 접촉되며, 지표면에 대해서 수직방향으로 세워지는 측벽하우징과, 상기 측벽하우징의 하단에 형성되며, 왕겨가 도포된 왕겨층과, 상기 왕겨층의 상단에 마련되며, 폭기펌프에 의해 제공되는 공기가 상방을 향해서 분사되는 폭기조와, 상기 왕겨층의 상단에 마련되며, 동물사체를 분해시키는 미생물과 수피를 포함하는 미생물수피층과, 상기 미생물수피층의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제1동물사체층과, 상기 제1동물사체층의 상단에 마련되며, 수피와 왕겨와 미생물이 혼합되어 위치되는 제1혼합층과, 상기 제1혼합층의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제2동물사체층과, 상기 제2동물사체층의 상단에 마련되며, 수피와 왕겨와 미생물이 혼합되어 위치되는 제2혼합층과, 상기 제2혼합층의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제3동물사체층과, 상기 제3동물사체층의 상단에 마련되며, 수피로 이루어지는 상단수피층과, 상기 측벽하우징의 중심부에 위치되며, 상기 측벽하우징의 상하방향으로 놓여지며, 내부에 공간을 가지는 파이프 형상의 본체파이프와, 상기 본체파이프와 연통되며, 상기 측벽하우징에 대해서 가로방향으로 놓여지며, 상기 상단수피층과 제3동물사체층 사이에 위치되며, 상기 제3동물사체층이 위치된 방향으로 유체통과공이 형성된 분기파이프와, 상기 측벽하우징의 중앙 밑면에 위치되며, 상기 분기파이프와 연결되어 상기 분기파이프로 유체를 이송시키는 이송펌프와, 상기 측벽하우징의 내벽과 지표면의 상면에 위치되며, 유체를 외부로 통과시키지 않는 방수포를 포함하는 것을 특징으로 하는 것으로서, 조류독감(Ai)이나 구제역이나 아프리카 돼지열병 등의 전염병으로 살처분되어 매몰된 동물사체의 매몰지를 빠른 시간 내에 소멸화시킬 수 있으며, 매몰지를 소멸화함으로써 토지의 활용도를 높이고 혐오시설을 제거할 수 있으며, 주위의 환경을 해치지 않으면서 매몰지를 빠른 시간 내에 소멸시킬 수 있으며, 미생물의 활동이 활발하게 될 수 있도록 수분을 계속해서 공급함으로써 미생물에 의한 발효를 더욱 촉진시킬 수 있으며, 침출수 등이 발생하지 않으므로 토양오염 등의 주위 환경을 해치지 않아서 친환경적이며, 발효 후에는 퇴비나 소각을 할 수 있어 전염병으로 인한 동물사체의 매몰지를 빠르게 소멸처리할 수 있는 효과가 있다. claims: 전염병으로 인해서 살처분된 동물사체를 파쇄하는 파쇄단계;상기 파쇄단계를 거친 동물사체를 습식으로 열처리하여 멸균시키는 습식열처리멸균단계;상기 습식열처리멸균단계를 거친 동물사체를 고속 발효탱크에서 발효시키는 고속발효단계;상기 고속발효단계를 거친 동물사체와 부속물을 포장하여 퇴비로 이송시키는 퇴비이송단계를 포함하되, 상기 고속 발효탱크는, 상면이 개방되며, 하단은 지표면과 접촉되며, 지표면에 대해서 수직방향으로 세워지는 측벽하우징(10); 상기 측벽하우징(10)의 하단에 형성되며, 왕겨가 도포된 왕겨층(20);상기 왕겨층(20)의 상단에 마련되며, 폭기펌프(35)에 의해 제공되는 공기가 상방을 향해서 분사되는 폭기조(30);상기 왕겨층(20)의 상단에 마련되며, 동물사체를 분해시키는 미생물과 수피를 포함하는 미생물수피층(40);상기 미생물수피층(40)의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제1동물사체층(50);상기 제1동물사체층(50)의 상단에 마련되며, 수피와 왕겨와 미생물이 혼합되어 위치되는 제1혼합층(60);상기 제1혼합층(60)의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제2동물사체층(70);상기 제2동물사체층(70)의 상단에 마련되며, 수피와 왕겨와 미생물이 혼합되어 위치되는 제2혼합층(80);상기 제2혼합층(80)의 상단에 마련되며, 전염병으로 인해 살처분된 동물사체가 위치되는 제3동물사체층(90);상기 제3동물사체층(90)의 상단에 마련되며, 수피로 이루어지는 상단수피층(100);상기 측벽하우징(10)의 중심부에 위치되며, 상기 측벽하우징(10)의 상하방향으로 놓여지며, 내부에 공간을 가지는 파이프 형상의 본체파이프(110);상기 본체파이프(110)와 연통되며, 상기 측벽하우징(10)에 대해서 가로방향으로 놓여지며, 상기 상단수피층(100)과 제3동물사체층(90) 사이에 위치되며, 상기 제3동물사체층(90)이 위치된 방향으로 유체통과공(125)이 형성된 분기파이프(120);상기 측벽하우징(10)의 중앙 밑면(160)에 위치되며, 상기 분기파이프(120)와 연결되어 상기 분기파이프(120)로 유체를 이송시키는 이송펌프(130);상기 측벽하우징(10)의 내벽과 지표면의 상면에 위치되며, 유체를 외부로 통과시키지 않는 방수포(150);를 포함하는 것을 특징으로 하는 전염병으로 인해 살처분되어 매몰된 동물사체의 매몰지 소멸화 고속처리공정., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

658/1150 Row 658: application_number: 1020200003608, combined_string: invention_title: 돈사 내 온도 및 습도 센싱정보를 활용한 돼지 성장예측 시스템 abstract: 돈사 내 온도 및 습도 센싱정보를 활용한 돼지 성장예측 시스템이 개시된다. 본 발명의 돈사 내 온도 및 습도 센싱정보를 활용한 돼지 성장예측 시스템은, 돈사 내 온도 정보를 측정하는 온도 측정부; 돈사 내 습도 정보를 측정하는 습도 측정부; 상기 온도 측정부 및 습도 측정부의 측정값을 기반으로 돼지의 성장단계별 일당 증체량을 산출하는 일당 증체량 산출부; 상기 일당 증체량 산출부의 산출값과 돼지의 성장단계별 설정 체중을 기반으로 사육시기별 사육 예상일수를 산출하는 사육 예상일수 산출부; 및 상기 사육일수 산출부의 산출값과 기설정된 돼지의 포유기간을 기반으로 목표 출하일을 산출하는 출하일 예측부를 포함하는 것을 특징으로 한다. 본 발명에 의하면, ICT정보(돈사 내 온도와 습도 센싱정보)를 활용하여 돼지의 성장 능력을 예측함으로써 목표 출하예정일, 목표 출하예정일까지의 총 사료섭취 예상량, 평균 사료요구율 등을 예측할 수 있고, 양돈 농가에서는 정밀한 사양관리로 효율적이고 경제적으로 돼지를 관리할 수 있다. claims: 돈사 내 온도 정보를 측정하는 온도 측정부(100);돈사 내 습도 정보를 측정하는 습도 측정부(200);상기 온도 측정부(100) 및 습도 측정부(200)의 측정값을 기반으로 돼지의 성장단계별 일당 증체량을 산출하는 일당 증체량 산출부(300);상기 일당 증체량 산출부(300)의 산출값과 돼지의 성장단계별 설정 체중을 기반으로 사육시기별 사육 예상일수를 산출하는 사육 예상일수 산출부(400); 및상기 사육 예상일수 산출부(400)의 산출값과 기설정된 돼지의 포유기간을 기반으로 목표 출하일을 산출하는 출하일 예측부(500)를 포함하는 돈사 내 온도 및 습도 센싱정보를 활용한 돼지 성장예측 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

659/1150 Row 659: application_number: 1020200002952, combined_string: invention_title: 동물용 약물 주입 장치와 이를 이용한 약물 주입 시스템, 방법 및 이를 수행하기 위한 컴퓨팅 장치 abstract: 동물용 약물 주입 장치와 이를 이용한 약물 주입 시스템, 방법 및 이를 수행하기 위한 컴퓨팅 장치가 개시된다. 본 발명의 일 실시예에 따른 동물용 약물 주입 장치와 이를 이용한 약물 주입 시스템, 방법 및 이를 수행하기 위한 컴퓨팅 장치는 동물에 부착되어 약물을 주입하는 약물 주입부, 및 상기 동물의 정보를 측정하는 센서부를 포함하는 약물 주입 장치; 및 상기 약물 주입 장치로부터 상기 동물 센싱 정보를 수신하고, 상기 동물 센싱 정보를 바탕으로 약물 주입을 제어하는 약물 주입 신호를 생성하여 상기 약물 주입 장치로 상기 약물 주입 신호를 전송하는 관리 서버를 포함한다. 본 발명의 실시예들에 따르면, 소나 돼지 등의 동물에 약물 주입 장치를 부착하여 원격으로 약물 투입을 제어함으로써, 다수의 가축에게 일괄적으로 약물을 투여할 수 있다. 또한, 본 발명의 실시예들은 원격으로 약물 투입을 제어함으로써, 근접주사에 따른 작업자의 안전사고를 미연에 방지하며, 정확하고 신속하게 주사할 수 있다. 또한, 본 발명의 실시예들은 동물의 상태에 따라 약물을 투여함으로써, 전염병 확산을 방지할 수 있다. claims: 동물에 부착되어 약물을 주입하는 약물 주입부, 및 상기 동물의 정보를 측정하는 센서부를 포함하는 약물 주입 장치; 및상기 약물 주입 장치로부터 상기 동물 센싱 정보를 수신하고, 상기 동물 센싱 정보를 바탕으로 약물 주입을 제어하는 약물 주입 신호를 생성하여 상기 약물 주입 장치로 상기 약물 주입 신호를 전송하는 관리 서버를 포함하는, 약물 주입 시스템.하나 이상의 프로세서들, 및 상기 하나 이상의 프로세서들에 의해 실행되는 하나 이상의 프로그램들을 저장하는 메모리를 구비한 컴퓨팅 장치에서 수행되는 방법으로서,동물에 부착된 약물 주입 장치로부터 동물 센싱 정보를 수신하는 단계; 상기 동물 센싱 정보를 바탕으로 동물에 약물을 주입하도록 상기 약물 주입 장치를 제어하는 약물 주입 신호를 생성하는 단계; 및상기 약물 주입 신호를 상기 약물 주입 장치로 전송하는 단계를 포함하는, 약물 주입 방법.하나 이상의 프로세서들, 및상기 하나 이상의 프로세서들에 의해 실행되는 하나 이상의 프로그램들을 저장하는 메모리를 구비한 컴퓨팅 장치로서,동물에 부착된 약물 주입 장치로부터 동물 센싱 정보를 수신하는 통신 모듈; 및상기 동물 센싱 정보를 바탕으로 상기 동물에 약물을 주입하도록 상기 약물 주입 장치를 제어하는 약물 주입 신호를 생성하는 약물 주입 제어 모듈을 포함하는, 컴퓨팅 장치.동물에 부착되어 약물을 주입하는 약물 주입부;상기 동물의 정보를 측정하는 센서부; 및상기 측정된 동물 센싱 정보를 외부 서버로 전송하는 통신부를 포함하는, 약물 주입 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

660/1150 Row 660: application_number: 1020190159858, combined_string: invention_title: 커피박 추출물을 포함하는 가축분뇨의 악취 저감용 조성물 abstract: 본 발명은 커피박 추출물을 포함하는 가축분뇨의 악취 저감용 조성물 및 이의 제조방법에 관한 것으로서, 보다 상세하게는 커피박을 산 처리, 알칼리 처리, 산 및 효소 복합 처리, 및 알칼리 및 효소 복합 처리로 구성된 군으로부터 선택된 어느 하나로 처리하여 추출한 커피박 추출물을 유효성분으로 함유하는 가축분뇨의 악취 저감용 조성물 및 이의 제조방법에 관한 것이다. 본 발명에 따른 커피박 추출물은 올리고당을 다량 포함하여 황화합물 저감 미생물의 에너지원이 되고, 암모니아, 황화수소 및 복합악취를 현저히 저감시킬 수 있으므로, 양돈장을 포함한 축산시설에서 분뇨에서 발생되는 악취를 저감 또는 제거하는데 유용하게 사용될 수 있다. claims: 커피박을 산 처리, 알칼리 처리, 산 및 효소 복합 처리, 및 알칼리 및 효소 복합 처리로 구성된 군으로부터 선택된 어느 하나로 처리하여 추출한 커피박 추출물을 유효성분으로 함유하는 가축분뇨의 악취 저감용 조성물.i) 커피박을 산 처리, 알칼리 처리, 산 및 효소 복합 처리, 및 알칼리 및 효소 복합 처리로 구성된 군으로부터 선택된 어느 하나로 전처리하는 단계;ii) 상기 단계 i)에서 전처리된 커피박을 원심분리하여 상층액 및 잔사를 분리하는 단계; 및iii) 상기 단계 ii)에서 상층액인 커피박 추출 액상물 또는 잔사인 커피박 추출 고형물을 수득하는 단계;를 포함하는, 가축분뇨의 악취 저감용 조성물의 제조 방법.제1항 내지 제6항 중 어느 한 항에 따른 가축분뇨의 악취 저감용 조성물을 가축분뇨에 처리하여 가축분뇨의 악취를 저감하는 방법.커피박을 산 처리, 알칼리 처리, 산 및 효소 복합 처리, 및 알칼리 및 효소 복합 처리로 구성된 군으로부터 선택된 어느 하나로 처리하여 추출한 커피박 추출물을 유효성분으로 함유하는 가축사료용 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

661/1150 Row 661: application_number: 1020190152017, combined_string: invention_title: 돈사용 난방장치 abstract: 개시되는 돈사용 난방장치는, 금속 보호관과, 금속 보호관의 내부 중심을 따라 배치되는 전열선을 가지는, 전기에너지를 열에너지로 변환시키는 전열부; 알루미늄 강판을 절곡시켜 형성되되, 전열부에서 발생한 열을 돼지가 사육되는 공간으로 반사하는 열 반사판; 및 금속 보호관을 파지하는 행거브라켓과, 행거브라켓을 열 반사판에 고정시키는 고정볼트를 가지는 클램프;를 포함한다. claims: 금속 보호관과, 상기 금속 보호관의 내부 중심을 따라 배치되는 전열선을 가지는, 전기에너지를 열에너지로 변환시키는 전열부;알루미늄 강판을 절곡시켜 형성되되, 상기 전열부에서 발생한 열을 돼지가 사육되는 공간으로 반사하는 열 반사판; 및상기 금속 보호관을 파지하는 행거브라켓과, 상기 행거브라켓을 상기 열 반사판에 고정시키는 고정볼트를 가지는 클램프;를 포함하는 돈사용 난방장치.청구항 1에 있어서,상기 돈사용 난방장치,상기 전열부에서 발생하는 난방열을 이용해 해충 살충제를 증발시키고 증발 시 발생하는 증기를 이용해 해충을 퇴치하는 해충 방제부;를 더 포함하며,상기 해충 방제부는,하부가 상기 열 반사판의 제 1 반사부재의 외측면에 고정되는, 수평한 링 형상의 홀더;내부에 액상의 해충 살충제를 담을 수 있는 용기 형상으로 제공되며, 상기 홀더의 내부로 수용되어 지지되되 하부는 상기 제 1 반사부재의 외측면에 접촉되는 훈증용기; 및상기 훈증용기의 상부를 덮는 오목한 단면을 가지는 트레이를 가지되, 상기 트레이의 내부로는 해충을 유인할 수 있는 미끼가 담겨지고, 상기 훈증용기에 담겨진 상기 해충 살충제의 증기가 배출되는 다수의 증기 배출공이 형성되는 유인트랩;을 포함하는 돈사용 난방장치,, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

662/1150 Row 662: application_number: 1020190141535, combined_string: invention_title: 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법 abstract: 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법이 제시된다. 일 실시예에 따른 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법은, 돈사 내 설치된 카메라를 통해 돈방 내 돼지 영상을 획득하는 단계; 상기 돼지 영상에서 돈방의 바닥과 돼지를 분리하기 위해 전배경 분리 작업을 수행하여 Gray 값이 살아있는 배경과 분리된 돼지 이미지 획득하는 단계; 상기 돼지 이미지에서 연결 요소 레이블링(Connected Component Labeling) 기법을 사용하여 돼지의 중심점과 차지하는 면적을 획득하는 단계; OpenCV를 사용하여 획득한 상기 중심점으로부터 돼지의 외곽선을 잇는 선분을 연결하는 단계; 및 연결된 상기 선분의 길이를 비교하여 그 길이의 차를 각각 구해, 상기 선분 간의 길이 차이가 일정 수준 이상일 경우, 돼지의 자세가 바르지 못하다고 판단하는 단계를 포함하여 이루어질 수 있다. claims: 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법에 있어서, 돈사 내 설치된 카메라를 통해 돈방 내 돼지 영상을 획득하는 단계; 상기 돼지 영상에서 돈방의 바닥과 돼지를 분리하기 위해 전배경 분리 작업을 수행하여 Gray 값이 살아있는 배경과 분리된 돼지 이미지 획득하는 단계; 상기 돼지 이미지에서 연결 요소 레이블링(Connected Component Labeling) 기법을 사용하여 돼지의 중심점과 차지하는 면적을 획득하는 단계; OpenCV를 사용하여 획득한 상기 중심점으로부터 돼지의 외곽선을 잇는 선분을 연결하는 단계; 및 연결된 상기 선분의 길이를 비교하여 그 길이의 차를 각각 구해, 상기 선분 간의 길이 차이가 일정 수준 이상일 경우, 돼지의 자세가 바르지 못하다고 판단하는 단계를 포함하는, 돼지의 자세 판정을 위한 빠르고 간단한 길이 비교 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

663/1150 Row 663: application_number: 1020190142107, combined_string: invention_title: 개량된 냉온풍 겸용 악취 제거장치 abstract: 본 발명은 악취 발생시설 내부에 설치되어 악취 발생시설의 악취를 제거하기 위한 악취 제거장치에 있어서, 악취가 발생하는 악취 발생시설 실내의 공기를 포집하여 1차로 먼지 및 오염물질을 흡착제거하는 1차오염제거필터; 상기 1차오염제거필터를 통해 먼지 및 오염물질이 제거된 공기에 물받이통과 연결되어 일정압력으로 노즐을 통해 물안개를 분사하여 공기중에서 물에 용해되는 암모니아를 포함하는 오염물질을 분리하는 2차물안개분사실; 상기 2차물안개분사실을 통과한 공기가 통과되어 미 제거된 오염물질을 제거하는 호기성 미생물인 효모 종균 또는 바실러스 종균 중 하나이상이 우드칩에 분사된 3차우드칩실; 상기 3차우드칩실을 통과한 공기에서 미 제거된 오염물질을 폴링(pall ring)으로 흡수 분리하는 4차폴링실; 상기 4차폴링실을 통과한 공기에서 미 제거된 오염물질을 제거하는 부직포를 포함하는 5차미세먼지필터; 상기 5차미세먼지필터를 통과한 공기에 이산화수소, 탄산수소나트륨, 에탄올, 시클로덱스트린을 포함하는 약재가 투입된 약품통과 연결되어 약품펌프에 의해 약재액을 분사하여 미 제거된 오염물질을 제거하는 6차약품분사실; 상기 6차약품분사실을 통과한 공기를 통과시켜 물 입자를 제거하는 부식포를 포함하는 7차습기제거필터; 상기 7차습기제거필터를 통과한 공기에서 미 제거된 오염물질을 다시 제거하는 부직포를 포함하는 8차미세먼지필터; 및 상기 8차미세먼지필터를 통과한 정제된 공기를 악취 발생시설 내부로 다시 순환 배출시키는 음압 흡입팬을 구비하는 개량된 냉온풍 겸용 악취 제거장치에 관한 것이다.이러한 본 발명은 우사, 돈사, 계사 및 분뇨 처리장과 도금시설, 나염시설 등 악취 발생시설에서 발생하는 악취를 효율적으로 제거할 수 있고, 동시에 외부의 공기 유입없이 악취 발생시설 내부의 온도를 적절한 온도로 유지할 수 있으며, 특히 악취 발생시설 외부에서 구제역, 조류인플루엔자(AI), 아프리카돼지열병(ASF; African swine fever) 등의 가축전염병 발생시 외부의 질병세균의 실내유입을 근본적으로 차단하여 악취 발생시설 내부의 세균감염을 차단시킬 수 있어 가축의 질병감염 및 질병사를 근본적으로 차단할 수 있는 효과가 있다. claims: 악취 발생시설(40) 내부에 설치되어 악취 발생시설의 악취를 제거하기 위한 악취 제거장치에 있어서,악취가 발생하는 악취 발생시설(40) 실내의 공기를 포집하여 1차로 먼지 및 오염물질을 흡착제거하는 1차오염제거필터(11);상기 1차오염제거필터(11)를 통해 먼지 및 오염물질이 제거된 공기에 물받이통(12a)과 연결되어 일정압력으로 노즐(12b)을 통해 물안개를 분사하여 공기중에서 물에 용해되는 암모니아를 포함하는 오염물질을 분리하는 2차물안개분사실(12);상기 2차물안개분사실(12)을 통과한 공기가 통과되어 미 제거된 오염물질을 제거하는 호기성 미생물인 효모 종균 또는 바실러스 종균 중 하나이상이 우드칩(13a)에 분사된 3차우드칩실(13);상기 3차우드칩실(13)을 통과한 공기에서 미 제거된 오염물질을 폴링(pall ring)(14a)으로 흡수 분리하는 4차폴링실(14);상기 4차폴링실(14)을 통과한 공기에서 미 제거된 오염물질을 제거하는 부직포를 포함하는 5차미세먼지필터(15);상기 5차미세먼지필터(15)를 통과한 공기에 이산화수소, 탄산수소나트륨, 에탄올, 시클로덱스트린을 포함하는 약재가 투입된 약품통(16a)과 연결되어 약품펌프(16b)에 의해 약재액을 분사하여 미 제거된 오염물질을 제거하는 6차약품분사실(16);상기 6차약품분사실(16)을 통과한 공기를 통과시켜 물 입자를 제거하는 부식포를 포함하는 7차습기제거필터(17);상기 7차습기제거필터(17)를 통과한 공기에서 미 제거된 오염물질을 다시 제거하는 부직포를 포함하는 8차미세먼지필터(18); 및상기 8차미세먼지필터(18)를 통과한 정제된 공기를 악취 발생시설(40) 내부로 다시 순환 배출시키는 음압 흡입팬(19)을 구비함을 특징으로 하는 개량된 냉온풍 겸용 악취 제거장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

664/1150 Row 664: application_number: 1020190138385, combined_string: invention_title: 돈사관리 제어시스템 abstract: 본 발명은 양돈사, 무창돈사 및 조기이유 자돈사등 돈사내의 유해 가스를 환기시키고, 환기로 인한 입기 공기가 돈사 내에서의 고른 분포와 온도차에 따른 예열 및 냉각으로 사육사 내의 온도차를 줄이고, 돼지 생육에 적정한 온습도제어 및 먹이를 자동으로 공급하여 최적의 생육환경을 제공하는 돈사관리 제어시스템을 제공한다. 본 발명은 실내온도를 감지하는 제1온도센서; 실내습도를 감지하는 습도센서; 실내온도를 감지하는 제2온도센서; 사료량을 감지하는 사료감지센서; 상기 제1온도센서에서 감지된 온도에 따라 환기팬의 작동을 제어하는 환기팬 제어기; 상기 습도센서에서 감지된 습도에 따라 안개분무기의 작동을 제어하는 안개분무 제어기; 상기 제2온도센서에서 감지된 온도에 따라 보온등의 작동을 제어하는 보온등 제어기; 상기사료감지센서에서 감지된 사료량에 따라 사료급이기의 작동을 제어하는 급이 제어기;를 포함하되, 상기 환기팬 제어기, 안개분무 제어기, 보온등 제어기 및 급이 제어기가 하나의 초소형 컴퓨터 탑재 제어기에 일체형으로 구성된다. claims: 실내온도를 감지하는 제1온도센서;실내습도를 감지하는 습도센서;실내온도를 감지하는 제2온도센서;사료량을 감지하는 사료감지센서;상기 제1온도센서에서 감지된 온도에 따라 환기팬의 작동을 제어하는 환기팬 제어기;상기 습도센서에서 감지된 습도에 따라 안개분무기의 작동을 제어하는 안개분무 제어기;상기 제2온도센서에서 감지된 온도에 따라 보온등의 작동을 제어하는 보온등 제어기;상기사료감지센서에서 감지된 사료량에 따라 사료급이기의 작동을 제어하는 급이 제어기;를 포함하되,상기 환기팬 제어기, 안개분무 제어기, 보온등 제어기 및 급이 제어기가 하나의 초소형 컴퓨터 탑재 제어기에 일체형으로 구성는 것을 특징으로 하는 돈사관리 제어시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

665/1150 Row 665: application_number: 1020190137589, combined_string: invention_title: 돈사의 슬랏받침바연결구 abstract: 본 발명의 효과는돈사 내 돈방 바닥을 형성하는 다공형 슬랏(110)이 얹혀지는 중공체 슬랏바(Slat bar 또는 파이프)(100)를 길이로 연결시켜 자유로운 길이의 슬랏바(100)를 구성함과 함께, 슬랏바(100) 끝단 구멍(11)을 밀폐시켜 오염원 유입으로 발생되는 오염, 부폐 등으로 인한 유해균의 서식을 방지하고, 미려성을 충족하도록 단부가 형성되는 밀폐캡(10-1)을 겸할 수 있도록 구성된 돈사의 바닥재 슬랏받침바 연결구(10)를 제공하므로써 안정된 슬랏의 구성과 견고성 및 오염 병균의 서식을 방지할 수 있는 효과를 발휘할 수 있도록 하는 것이다. claims: 돼지를 사육하는 돈사의 돈방에 돼지가 기거하고 배출하는 돈분을 돈분집류실(200)로 낙하시키는 슬랏(110)을 돈분집류실(200)이 형성된 슬랏바받침(120)에 얻쳐지는 슬랏바(100)를 길이로 연결하는 슬랏받침바연결구(10)를 구성하되,중공부를 형성하는 관체로 구성된 슬랏바(100) 단부 구멍(11)에 삽입되게 중앙으로부터 점차적으로 좁아지는 형태로 전후 또는 좌우로 분할 구성된 상하면 또는 좌우측면에 미끄럼면(15)을 형성한 복수의 압인돌기(13)가 구성되는 좌우삽입관(12),상기 좌우삽입관(12)은 중심부에 연결되는 슬랏바(100)의 단면과 밀착되는 밀폐돌기(14)가 구성되어 연결되는 슬랏바(100)의 단면을 밀폐할 수 있도록 구성함을 특징으로 하는 돈사의 슬랏받침바연결구., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

666/1150 Row 666: application_number: 1020190136030, combined_string: invention_title: 삼엽 동물 배합사료의 제조방법 abstract: 본 발명의 일 측면은 인삼잎을 가축의 사료 등에 첨가하여 음용할 수 있게 하거나 사료로 사용할 수 있도록 하는 삼엽 동물 배합사료 제조방법에 관한 것으로, 더욱 상세하게는 소정의 양의 인삼잎을 소정의 온도 및 소정의 시간 동안 건조 분쇄하여 그린파우더를 만든 다음 발효시켜 가축의 면역력을 증대시키는 삼엽 동물 배합사료 제조방법에 관한 것이다.본 발명의 일 실시예에 따르면 폐농산물로 버려지는 인삼잎을 수거하여 이를 가공하여 사료에 첨가하는 단계를 포함하여 돼지 등 가축에 면역력을 강화시키는 삼엽 동물 배합사료의 제조방법을 제공한다. claims: 삼엽을 선별하여 수거하는 수거단계;상기 수거된 삼엽을 수회 세척하고, 상기 수거된 삼엽의 표면에 물기와 이물질 및 협착물을 제거하는 세척단계;상기 삼엽을 정해진 시간 및 정해진 온도로 건조시키는 건조단계;상기 건조된 삼엽을 분말 상태로 만들기 위해 분쇄하는 분쇄단계; 및상기 분쇄된 삼엽 분말을 가축 사료에 혼합하는 혼합단계;를 포함하는 삼엽 동물 배합사료 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

667/1150 Row 667: application_number: 1020190134740, combined_string: invention_title: 종돈 조기 선발을 위한 SNP chip 데이터 생성 및 분석 기술 abstract: 본 발명은 자동화 장비를 이용하여 종돈의 샘플에서 DNA를 추출하고 유전체 정보를 확인, 분석 후 데이터베이스를 저장하는 일련의 종돈 조기 선발을 위한 SNP chip 데이터 생성 및 분석 기술에 관한 것이다.본 발명의 종돈 조기 선발을 위한 SNP chip 데이터 생성 및 분석 기술은, 자동화 시스템을 갖춘 DNA 추출 기기와; 추출된 DNA의 유전체적 특징을 확인하기 위한 60,000개의 단일염기서열(SNP) 검사 기기와; 이를 분석하기 위한 소프트웨어와 분석된 자료를 저장할 수 있는 서버로 구성된다.본 발명은 종래의 유전체 분석에 널리 사용되고 있는 분석법의 장점을 그대로 살림과 동시에 DNA추출 및 분석과 저장의 일련의 과정을 체계화 함으로써, 결과의 신뢰성을 높이고 분석 시간을 단축 하는 효과가 있다. claims: 종돈의 샘플 채취를 시작으로 자동화 장비를 이용한 DNA 추출 및 추출된 DNA의 정도 관리와 illumina infinium porcine 60K chip을 이용한 유전체 확인 및 genome studio를 이용한 분석과 서버 저장의 일련의 과정을 특징으로 하는 종돈 조기 선발을 위한 SNP chip 데이터 생성 및 분석 기술., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

668/1150 Row 668: application_number: 1020190134575, combined_string: invention_title: 매몰저장탱크를 통한 폐사가축의 발효, 탈취 및 살바이러스 차단 방법 abstract: 본 발명은 폐사가축의 발효, 탈취 및 살바이러스 차단 방법에 관한 것으로, 보다 상세하게는 폐사된 가축, 구제역, 신종플루 및 아프리카 돼지열병 등에 감염된 가축과 같은 오염된 사체를 특정 용기 속에 장입한 채로 매몰처리하되 악취 발생 자체를 차단하여 병원균이 대기를 통해 전파되는 것을 막고, 민원이 생기지 않도록 하면서 침출수 문제도 자연스럽게 해결하여 토양오염이나 2차 환경오염도 일으키지 않은 채 안전하게 처리할 수 있도록 개선된 폐사가축의 발효, 탈취 및 살바이러스 차단 방법에 관한 것이다. claims: 가축 사체가 장입되는 투입구(110)를 구비하고 지중에 매립설치되는 밀폐형 매몰저장탱크(100), 상기 투입구(110)를 밀폐하는 커버(120), 상기 커버(120)의 상면에 설치되고 살바이러스제가 일정수위로 채워진 살바이러스탈취조(130), 상기 살바이러스탈취조(130)의 내부 천정면에 설치된 UV살균탈취기(140), 상기 살바이러스탈취조(130)의 일측 상면에 배관된 배기관(150), 상기 살바이러스탈취조(130)의 일측에 상기 살바이러스제의 수위보다 높은 위치에서 밀폐형 매몰저장탱크(100) 내부와 연통되도록 배관된 바이패스관(160), 일단은 상기 살바이러스제에 침지되고 타단은 상기 밀폐형 매몰저장탱크(100) 내부에 노출되게 배관된 발생가스배출관(170)을 이용하여 매몰저장탱크를 통한 폐사된 가축의 발효, 탈취 및 살바이러스 차단 방법에 있어서;상기 방법을 이용하여 폐사된 가축 사체를 밀폐형 매몰저장탱크(100)의 바닥면에 한 층씩 쌓는 가축 사체 장입단계; 장입된 한 층의 가축 사체에 미생물 발효탈취제(B)를 살포하는 단계; 가축 사체 장입단계와 미생물 발효탈취제 살포단계를 교차로 다수회 반복하여 사체 장입이 완료되면 커버(120)로 밀폐하는 단계; 커버(120) 밀폐 후 부패 및 사체 분해가 진행되면서 발생된 가스를 살바이러스제에 노출시켜 1차로 살균 탈취하는 단계; 1차 살균 탈취와 함께 살바이러스제의 수면 상부로 상승한 기체를 UV살균탈취기(140)로 살균선을 조사하여 2차로 살균 탈취하는 단계; 및, 2차 살균 탈취까지 완료되면 대기중으로 배기하는 배기단계;를 포함하되,상기 미생물 발효탈취제(B)는 당밀액 1ℓ를 기준으로 벤토나이트 분말 250g, 망간아세테이트 150g, 아미노산 150g, 사탕수수 정제당 500g, EM(Effective Micro-organism)원액 50g을 혼합한 후 액체 배지에서 각각 배양된 유산균ㆍ효모균ㆍ바실러스균ㆍ그램 양성 방선균을 첨가한 다음 35℃에서 5일 동안 증식시킨 것을 사용하고;상기 미생물 발효탈취제(B)에는 버섯추출물 200g, 티오바실리스페로옥시단스 50g, 질산망간 10g, NTA(Nitrilotriacetic acid) 50g, 수가용성 철염 10g, 주석산 5g, FeSO4.7H2O 수용액 10㎖을 더 첨가된 것을 특징으로 하는 매몰저장탱크를 통한폐사가축의 발효, 탈취 및 살바이러스 차단 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

669/1150 Row 669: application_number: 1020217013735, combined_string: invention_title: 이종이식 생성물 및 방법 abstract: 인간으로의 임상 이종이식을 위한 생물학적 생성물 및 돼지가 하나 이상의 세포외 표면 글리칸 에피토프를 발현하지 않도록 생물학적으로 조작된 게놈을 갖는 비야생형의 생물학적으로 조작된 돼지를 생산하는 것을 포함하는 인간으로의 임상 이종이식을 위한 생물학적 생성물을 제조하는 방법은 폐쇄된 지정된 병원체가 없는 무리에서 바이오버든-감소 절차에 따라 사육되고, 여기서, 상기 생물학적 생성물은 돼지가 안락사된 후 수확되고 상기 생성물은 돼지로부터 무균적으로 제거되고, 상기 생물학적 생성물은 멸균을 포함하여 처리되고, 상기 생성물을 멸균 용기에 저장하고, 상기 생성물은 하나 이상의 세포외 표면 글리칸을 포함하지 않고, 특정 지정된 병원체가 없고, 생물학적으로 활성이고, 이종이식 후 혈관화할 수 있는 살아있는 세포 및 조직을 포함한다. claims: 인간 수혜자로의 이종이식에 적합한 생물학적 생성물을 생성하는 방법으로서,비야생형의 생물학적으로 조작된 돼지를 생산하는 단계로서, 상기 돼지는 자연 육종 및 자연 출산을 통해 생산되고, 상기 돼지는 하나 이상의 세포외 표면 글리칸 에피토프를 발현하지 않도록 생물학적으로 조작된 게놈을 갖고, 여기서, 상기 돼지는 적어도 다음 병원체: 아스카리스 종 (Ascaris species), 크립토스포리듐 종 (cryptosporidium species), 에키노코쿠스 (Echinococcus), 스트롱길로이드스 스테로콜리스 (Strongyloids sterocolis), 톡소플라스마 곤디 (Toxoplasma gondii), 브루셀라 수이스 (Brucella suis), 렙토스피라 종 (Leptospira species), 미코플라스마 하이오뉴모니애 (mycoplasma hyopneumoniae), 슈도라비스 (pseudorabies), 톡소플라스마 곤디 (Toxoplasma Gondii), 스타필로코쿠스 종 (staphylococcus species), 마이크로피톤 종 (Microphyton species), 및　트리코피톤 종 (Trichophyton　species), 돼지 인플루엔자 (porcine influenza), 거대세포 바이러스 (cytomegalovirus), 아르테리바이러스 (arterivirus), 및 코로나바이러스 (coronavirus)가 없는, 단계, 바이오버든-감소 절차 (bioburden-reducing procedure)에 따라 상기 돼지를 사육하고 상기 돼지를 유지하는 단계로서, 상기 절차는 폐쇄된 무리에서 돼지를 유지함을 포함하며, 상기 폐쇄된 무리에서 다른 모든 동물은 적어도 다음 병원체: 아스카리스 종, 크립토스포리듐 종, 에키노코쿠스, 스트롱길로이드스 스테로콜리스, 톡소플라스마 곤디, 브루셀라 수이스, 렙토스피라 종, 미코플라스마 하이오뉴모니애, 슈도라비스, 톡소플라스마 곤디, 스타필로코쿠스 종, 마이크로피톤 종,　및 트리코피톤 종, 돼지 인플루엔자, 거대세포 바이러스, 아르테리바이러스, 및 코로나바이러스가 없는 것으로 확인되고, 상기 돼지는 상기 폐쇄된 무리 외부에 있는 임의의 비인간 동물 및 동물 사육 시설과의 접촉으로부터 격리시키는, 단계, 상기 돼지로부터 생물학적 생성물을 수확하는 단계로서, 상기 수확 단계는 상기 돼지를 안락사시키고 상기 돼지로부터 생물학적 생성물을 무균적으로 제거함을 포함하는, 단계,수확 15시간 이내에 멸균을 포함하여 상기 생물학적 생성물을 처리하고 상기 생물학적 생성물을 멸균 용기에 저장하는 단계를 포함하되, 상기 생물학적 생성물은 하나 이상의 세포외 표면 글리칸을 함유하지 않고, 여기서, 상기 생성물은 아스카리스 종, 크립토스포리듐 종, 에키노코쿠스, 스트롱길로이드스 스테로콜리스, 톡소플라스마 곤디, 브루셀라 수이스, 렙토스피라 종, 미코플라스마 하이오뉴모니애, 슈도라비스, 톡소플라스마 곤디,스타필로코쿠스 종, 마이크로피톤 종,　및 트리코피톤 종, 돼지 인플루엔자, 거대세포 바이러스, 아르테리바이러스, 및 코로나바이러스가 없고, 여기서, 상기 생성물은 생물학적으로 활성이고 이종이식 후 혈관화할 수 있는 살아있는 세포 및 조직을 포함하고,상기 생성물의 세포 미토콘드리아 활성은 MTT 검정에 의해 측정시 50% 초과이고;상기 생성물은 전형적인 Gal-T 녹아웃 돼지, 전형적인 트리플 녹아웃 돼지, 형질전환 돼지, 야생형 동물, 및/또는 동종이식편으로부터 제조된 이종이식 생성물로부터 얻어진 생물학적 생성물과 비교하여 인간 이종이식 수혜자에게 이식될 때 덜 면역원성이고,상기 생성물은 전형적인 Gal-T 녹아웃 돼지, 전형적인 트리플 녹아웃 돼지, 형질전환 돼지, 야생형 동물, 및/또는 동종이식편으로부터 제조된 이종이식 생성물로부터 얻어진 생물학적 생성물과 비교하여 인간 이종이식 수혜자에게 이식될 때 덜 항원성이고,상기 생성물은 상기 인간 이종이식 수혜자에게 면역억제 약물의 투여 또는 다른 면역억제 요법의 부재 하에 상기 인간 이종이식 수혜자에 의한 거부에 내성이 있는, 방법.제 20 항에 있어서, 부검시 상기 유기체로부터의 비장, 간, 골수, 중추 신경계 및 폐 중 적어도 하나로부터 조직 샘플을 수집하고 동결보존하는 단계를 추가로 포함하는, 방법.제 24 항에 있어서, 상기 생성물을 스캐폴드 상에 상기 생성물과 적어도 동일한 크기로 적용하는 단계, 상기 생성물 및 상기 스캐폴드를 롤링하는 단계, 상기 롤링된 생성물 및 스캐폴드를 멸균 용기에 넣고, 상기 용기를 약 10℃와 약 -80℃ 사이의 온도에서 저장하는 단계를 추가로 포함하는, 방법.제 26 항에 있어서, 상기 게놈은 파괴된 시티딘 모노포스페이트-N-아세틸뉴라민산 하이드록실라제 (CMAH) 유전자를 추가로 포함하는, 생물학적 생성물.인간으로의 임상 이종이식을 위한 생물학적 생성물을 제조하는 방법으로서, 알려진 인간 주요 조직적합성 복합체 유전자 서열을 선택하거나 인간 수혜자의 주요 조직적합성 복합체 유전자를 서열분석하는 단계, 상기 돼지의 세포가 상기 알려진 인간 주요 조직적합성 복합체 유전자 서열의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자 서열의 상응하는 부분을 발현하도록, 상기 돼지의 주요 조직적합성 복합체 유전자 서열의 일부를 상기 알려진 인간 주요 조직적합성 복합체 유전자 서열의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자 서열의 상응하는 부분으로 대체하기 위해 돼지의 세포를 유전적으로 변형하는 단계; 상기 알려진 인간 주요 조직적합성 복합체 유전자 서열의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자 서열의 상응하는 부분을 발현하는 상기 돼지로부터 하나 이상의 세포, 조직, 및/또는 장기를 단리하는 단계로서, 여기서, 상기 단리된 세포, 조직, 및/또는 장기는 생물학적 생성물인, 단계를 포함하는, 방법. 제 37 항 에 있어서, 상기 유전적으로 변형하는 단계는 주형 주요 조직적합성 복합체 서열을 제조하는 단계, CRISPR-Cas9 플라스미드를 제조하는 단계, 주형 주요 조직적합성 복합체 서열을 상기 플라스미드에 클로닝하는 단계, 상기 돼지 세포의 주요 조직적합성 복합체 유전자좌에서 CRISPR 분할 부위를 결정하는 단계, gRNA 서열을 하나 이상의 CRISPR-Cas9 플라스미드에 클로닝하는 단계, CRISPR-Cas9 플라스미드를 돼지 세포에 투여하는 단계, 상기 돼지 세포의 상기 주요 조직적합성 복합체 유전자좌에서 CRIPSR/Cas9 분할을 수행하는 단계, 상기 돼지 세포의 상기 주요 조직적합성 복합체 유전자좌를 상기 알려진 인간 주요 조직적합성 복합체 유전자 서열의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자 서열의 상응하는 부분과 일치하는 하나 이상의 주형 주요 조직적합성 복합체 서열로 대체하는 단계를 포함하는, 방법.파괴된 알파-1,3 갈락토실트랜스퍼라제 유전자를 갖고, 알려진 인간 서열 또는 상기 유전적으로 재프로그래밍된 돼지로부터 단리된 세포, 조직, 및/또는 장기의 인간 수혜자의 주요 조직적합성 복합체의 일부를 발현하도록 유전적으로 변형된 헥 게놈을 포함하는 유전적으로 재프로그래밍된 돼지.제 51 항에 있어서, 상기 유전적으로 재프로그래밍된 돼지의 게놈은 파괴된 시티딘 모노포스페이트-N-아세틸뉴라민산 하이드록실라제 (CMAH) 유전자를 추가로 포함하는, 유전적으로 재프로그래밍된 돼지.파괴된 알파-1,3 갈락토실트랜스퍼라제 유전자를 갖고, 알려진 인간 서열의 주요 조직적합성 복합체 또는 상기 유전적으로 재프로그래밍된 돼지로부터 단리된 세포, 조직, 및/또는 장기의 인간 수혜자를 발현하도록 유전적으로 변형된 헥 게놈을 포함하는 유전적으로 재프로그래밍된 돼지를 제조하는 방법으로서, 상기 방법은 알려진 인간 주요 조직적합성 복합체 서열을 선택하거나 인간 수혜자의 주요 조직적합성 복합체 유전자를 서열분석하는 단계, 적어도 하나의 파괴된 돼지 표면 글리칸 유전자를 갖는 핵 게놈을 포함하는 돼지를 수득하는 단계, 상기 돼지의 세포가 상기 인간 수혜자의 주요 조직적합성 복합체의 일부를 발현하도록, 상기 돼지의 주요 조직적합성 복합 유전자의 일부를 상기 알려진 인간 주요 조직적합성 복합체 유전자의 상응하는 부분 또는 상기 인간 수혜자의 주요 조직적합성 복합체 유전자의 상응하, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

670/1150 Row 670: application_number: 1020190118818, combined_string: invention_title: 코드를 이용한 스마트 팜 가축 관리 시스템 및 관리 방법 abstract: 개체 정보 인식코드로서 QR 코드 또는 바코드 등을 이용하여 소 또는 돼지 개체를 정확하게 인식하고, 개체 군별 발육 상태를 관리함으로써 최적의 생육환경을 조성할 수 있는 코드를 이용한 스마트 팜 가축 관리 시스템 및 관리 방법에 관한 것으로, 가축에 개체 정보 인식코드를 인가하는 코드 인가 수단, 상기 개체 정보 인식코드를 촬영하는 촬영 수단, 상기 촬영 수단에 의해 촬영된 개체 정보 인식코드를 분석하는 분석 수단, 상기 분석 수단에 의해 분석된 개체 정보 인식코드에 따라 상기 가축을 관리하는 관리 수단을 포함하고, 상기 코드 인가 수단은 자돈이 태어나서 최초 예방 접종시 QR 코드 또는 바코드를 자돈의 등, 옆구리 등에 복수 개 이식하고, 상기 촬영 수단은 상기 개체 정보 인식코드인 QR 코드 또는 바코드를 촬영하기 위해 돈방의 천장에 설치된 카메라인 구성을 마련하여, 가축에 대해 최적의 생육환경을 조성할 수 있다. claims: 가축에 개체 정보 인식코드를 인가하는 코드 인가 수단,상기 개체 정보 인식코드를 촬영하는 촬영 수단,상기 촬영 수단에 의해 촬영된 개체 정보 인식코드를 분석하는 분석 수단,상기 분석 수단에 의해 분석된 개체 정보 인식코드에 따라 상기 가축을 관리하는 관리 수단을 포함하고,상기 코드 인가 수단은 자돈이 태어나서 최초 예방 접종시 QR 코드 또는 바코드를 자돈의 등, 옆구리 등에 복수 개 이식하고,상기 촬영 수단은 상기 개체 정보 인식코드인 QR 코드 또는 바코드를 촬영하기 위해 돈방의 천장에 설치된 카메라인 것을 특징으로 하는 코드를 이용한 스마트 팜 가축 관리 시스템.(a) 가축에 개체 정보 인식코드로서 QR 코드 또는 바코드를 인가하는 단계,(b) 상기 단계 (a)에서 인가된 가축의 QR 코드 또는 바코드를 촬영하는 단계,(c) 상기 단계 (b)에서 촬영된 QR 코드 또는 바코드를 분석하는 단계,(d) 상기 단계 (c)에 의해 분석된 QR 코드 또는 바코드에 따라 상기 가축의 이력 정보를 관리하는 단계를 포함하고,가축의 성장에 따라 QR 코드 또는 바코드의 면적이 넓어지므로, 상기 단계 (c)에서는 면적 정보를 무게 정보로 정확하게 환산하기 위한 기준 데이터가 설정된 것을 특징으로 하는 코드를 이용한 스마트 팜 가축 관리 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

671/1150 Row 671: application_number: 1020190114623, combined_string: invention_title: 승가 검사기를 구비한 돼지 사육장치 abstract: 기존의 돼지 발정 측정은 별도의 장치를 돼지에 결합하거나, 카메라 장치 등으로 돼지의 행동변화를 관찰하는 것으로만 측정 가능하였기 때문에 부정확하고 돼지가 불편해했다. 본 발명은 상기와 같은 문제를 해결하기 위하여, 입구도어, 체중 측정부, 급이부 및 출구 도어 부를 구비한 자동 사육 장치의 상기 체중 측정부는 직사각형의 상판프레임과 상판철망으로 구성된 상판과 상기 상판의 하부에서 상기 상판의 네모서리와 상기 상판의 장변의 중간에 6개의 로드셀이 구비되고, 돼지가 상기 자동 사육 장치에 들어올 때 발생하는 상기 6개의 로드셀에서 측정되는 돼지 걸음걸이에 따른 체중의 변화 패턴으로부터 돼지의 발정 여부를 판단하며, 상기 돼지의 발정 여부 판단에서 돼지의 발정으로 판단되는 경우, 상기 돼지의 발정을 정확히 검사하기 위하여 상기 돼지 체중 측정부 상부에 구비된 승가검사기의 상하이동부를 하강하여 상기 돼지의 등 부위를 눌러 돼지가 승가를 여락하는지 검사하는 승가검사기를 구비하는 것을 특징으로 하는 승가 검사기를 구비한 돼지 사육 장치를 제공한다. 이러한 구성에 의하여 암퇘지의 발정 여부를 정확히 확인할 수 있는 효과가 있다. claims: 입구도어, 체중 측정부, 급이부 및 출구 도어 부를 구비한 자동 사육 장치의 상기 체중 측정부는 직사각형의 상판프레임과 상판철망으로 구성된 상판과 상기 상판의 하부에서 상기 상판의 네모서리와 상기 상판의 장변의 중간에 6개의 로드셀이 구비되고, 또한, 상기 6개의 로드셀 중 출구 도어부 쪽에 설치된 로드셀에 무게가 많이 실리면 돼지가 체중 측정부에 완전히 들어온 것으로 인식하여, 상기 사육장치의 입구를 닫아 다른 돼지의 진입을 막으며, 돼지가 상기 자동 사육 장치에 들어올 때 발생하는 상기 6개의 로드셀에서 측정되는 돼지 걸음걸이에 따른 체중의 변화 패턴으로부터 돼지의 발정 여부를 판단하고, 상기 돼지의 발정 여부 판단에서 돼지의 발정으로 판단되는 경우, 상기 돼지의 발정을 정확히 검사하기 위하여 상기 돼지 체중 측정부 상부에 구비된 승가검사기의 상하이동부를 하강하여 상기 돼지의 등 부위를 눌러 돼지가 승가를 여락하는지 검사하는 승가검사기를 구비하는 것을 특징으로 하는 승가 검사기를 구비한 돼지 사육 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

672/1150 Row 672: application_number: 1020190114624, combined_string: invention_title: 승가 검사기를 구비한 돼지 사육장치 abstract: 기존의 돼지 발정 측정은 별도의 장치를 돼지에 결합하거나, 카메라 장치 등으로 돼지의 행동변화를 관찰하는 것으로만 측정 가능하였기 때문에 부정확하고 돼지가 불편해했다. 본 발명은 상기와 같은 문제를 해결하기 위하여, 입구도어, 체중 측정부, 급이부 및 출구 도어 부를 구비한 자동 사육 장치의 상기 체중 측정부는 직사각형의 상판프레임과 상판철망으로 구성된 상판과 상기 상판의 하부에서 상기 상판의 네모서리와 상기 상판의 장변의 중간에 6개의 로드셀이 구비되고, 돼지가 상기 자동 사육 장치에 들어올 때 발생하는 상기 6개의 로드셀에서 측정되는 돼지 걸음걸이에 따른 체중의 변화 패턴으로부터 돼지의 발정 여부를 판단하며, 상기 돼지의 발정 여부 판단에서 돼지의 발정으로 판단되는 경우, 상기 돼지의 발정을 정확히 검사하기 위하여 상기 돼지 체중 측정부 상부에 구비된 승가검사기의 상하이동부를 하강하여 상기 돼지의 등 부위를 눌러 돼지가 승가를 여락하는지 검사하는 승가검사기를 구비하는 것을 특징으로 하는 승가 검사기를 구비한 돼지 사육 장치를 제공한다. 이러한 구성에 의하여 암퇘지의 발정 여부를 정확히 확인할 수 있는 효과가 있다. claims: 입구도어, 체중 측정부, 급이부 및 출구 도어 부를 구비한 자동 사육 장치의상기 체중 측정부는 직사각형의 상판프레임과 상판철망으로 구성된 상판과 상기 상판의 하부에서 상기 상판의 네모서리와 상기 상판의 장변의 중간에 6개의 로드셀이 구비되고, 돼지가 상기 체중 측정부상기 체중 측정부는 과정에서 상기 6개의 로드셀에 측정되는 좌우 로드셀의 무게 값과 정지 돼지의 무게를 측정하고 이를 비교함으로써 돼지가 서있거나, 걷는 중에 좌우에 동일한 무게가 실리는지를 판단할 수 있고, 이를 이용하여 돼지의 걸음걸이 이상여부를 판단할 수 있으며, 돼지가 상기 자동 사육 장치에 들어올 때 발생하는 상기 6개의 로드셀에서 측정되는 돼지 걸음걸이에 따른 체중의 변화 패턴으로부터 돼지의 발정 여부를 판단하며, 상기 돼지의 발정 여부 판단에서 돼지의 발정으로 판단되는 경우, 상기 돼지의 발정을 정확히 검사하기 위하여 상기 돼지 체중 측정부 상부에 구비된 승가검사기의 상하이동부를 하강하여 상기 돼지의 등 부위를 눌러 돼지가 승가를 여락하는지 검사하는 승가검사기를 구비하는 것을 특징으로 하는 승가 검사기를 구비한 돼지 사육 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

673/1150 Row 673: application_number: 1020190111392, combined_string: invention_title: 동물복지형 모돈사 abstract: 본 발명은 새끼돼지를 분만한 갓난 젖먹이새끼를 키우는 모돈(sow)이 젖먹이 기간동안 일정한 활동을 할 수 있는 공간을 형성시켜 동물보호법 규정에서의 불편함과 고통 및 정상적인 행동을 표현할 수 있도록 함으로써 스트레스로부터의 자유와 법 제3조(동물보호의 기본원칙)에 충족하도록 함과,어미로부터 젓을 먹는 갓난 새끼가 모돈(sow)으로부터의 압사를 방지할 수 있도록 피난공간을 구성하는 모돈사(Farrowing Pen 또는 Farrowing crate)를 제공하는 동물복지형 모돈사로 모돈과 새끼 돼지가 더욱 행복하고 편안함을 보여주는 가장 중요한 혁신 중 하나로 간주되는 돼지 성능을 향상시키고 복지에 대한 우수한 표준을 도출하는 효과를 발휘하는 것이다. claims: 모돈사(100)를 지지하는 H빔(110)에 돼지가 기거하고 분뇨를 배출하는 슬랏(120)에 개폐수단(150)으로 개폐되는 개폐문(151)을 형성한 전후외벽(130)과, 좌우외벽(140,140-1) 및 사료통(152)과 물통(154)을 구성하는 모돈사에 있어서,상기 모돈사(100)에 제 1스톨수단(A)과, 제 2스톨수단(B)를 구성하되,개폐문(151)을 중심으로 구성된 제 1전후외벽(130-1)의 외벽기둥(131)에 힌지된 연동판(21)에 고정되고 복수의 스톨봉(22)을 구성한 스톨제어판(20)과, 스톨제어판(20)에서 돌출된 가이드봉(23)에 끼워지는 안내장공(24)과 손잡이(25)를 구성한 제어판(26),스톨제어판(20)에 힌지되고 제어판(26)으로 연동되는 개폐판(27)에 돌출된 개폐핀(28)을 구성하고, 상기 개폐핀(28)이 제어되는 체결홈(11)과 안착홈(12)을 구성한 가이드판(10)에 스톱봉(13)을 구성시켜 스톨제어판(20)을 내외로 이동과 제어할 수 있도록 구성되는 제 1스톨수단(A),제 2전후외벽(130-2)의 외벽기둥(131-1)에 이송롤(41)이 이동하는 레일(32)과 복수의 정지홈(33)을 구성한 제 1정지판(30)과 제 2정지판(31),복수의 스톨봉(22)을 구성하고 돌출부를 형성한 연동판(40) 상부측 외향 돌출부에 한쌍의 이송롤(41)을 힌지시켜 레일(32)에서 이동되게 구성함과, 연동판(40)의 내향 돌출부에 &amp;quot;&gt;&amp;quot;형상의 키제어판(42)을 힌지하고 키제어판(42)의 상부 단부에 이동조작봉(43)을 구성하고 하부끝단에 상기 제 1정지판(30)과 제 2정지판(31)에 구성된 정지홈(33)에서 출입되는 키봉(44)을 구성한 승하강키판(45)을 힌지시켜 이동조작봉(43)으로 승하강키판(45)을 조작하여 승하강되는 키봉(44)이 제 1정지판(30)과 제 2정지판(31)의 정지홈(33)에서 이탈과 삽입으로 제어하는 제 2스톨수단(B)으로 구성함을 특징으로 하는 동물복지형 모돈사., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

674/1150 Row 674: application_number: 1020200129601, combined_string: invention_title: 농산물 가공장치 abstract: 농산물 가공장치가 개시된다. 본 발명에 따른 농산물 가공장치는, 일측에 개폐도어가 설치되고, 내부의 바닥면에 한 쌍의 인입레일이 설치되며, 상부에 진공펌프와 가압펌프가 각각 연결되고, 농산물이 내부로 인입된 후, 순서에 따라 상기 진공펌프에 의해 진공 및 해제되고 상기 가압펌프로부터 공급되는 혼합액에 의해 가압 및 해제되도록 마련되는 가공챔버; 상기 농산물을 상기 가공챔버로 운반하도록 형성되고, 상기 인입레일과 대응되는 안내레일이 상부에 설치되도록 마련되는 운반부; 상기 운반부의 상부에 적어도 하나 이상 적재되고, 상기 농산물이 수용되며, 상기 안내레일과 상기 인입레일을 따라 안내되어 상기 가공챔버 내로 인입되도록 마련되는 농산물 수용부; 및 상기 혼합액이 저장되고, 상기 가압펌프와 연결되도록 마련되는 혼합액 저장부;를 포함하는 것을 특징으로 한다. claims: 일측에 개폐도어가 설치되고, 내부의 바닥면에 한 쌍의 인입레일이 설치되며, 상부에 진공펌프와 가압펌프가 각각 연결되고, 농산물이 내부로 인입된 후, 순서에 따라 상기 진공펌프에 의해 진공 및 해제되고 상기 가압펌프로부터 공급되는 혼합액에 의해 가압 및 해제되도록 마련되는 가공챔버;상기 농산물을 상기 가공챔버로 운반하도록 형성되고, 상기 인입레일과 대응되는 안내레일이 상부에 설치되도록 마련되는 운반부;상기 운반부의 상부에 적어도 하나 이상 적재되고, 상기 농산물이 수용되며, 상기 안내레일과 상기 인입레일을 따라 안내되어 상기 가공챔버 내로 인입되도록 마련되는 농산물 수용부; 및상기 혼합액이 저장되고, 상기 가압펌프와 연결되도록 마련되는 혼합액 저장부;를 포함하고상기 운반부는 상기 안내레일의 선단부에 상기 인입레일과 연결되도록 설치되는 이음레일을 더 포함하며, 상기 인입레일은 일측에 고정홈을 갖는 계단형상의 인입레일 연결부가 형성되고, 상기 이음레일은 상기 인입레일과 연결되는 일측에 상기 인입레일 연결부와 대응되도록 고정돌기를 갖는 이음레일 연결부가 형성되며, 상기 운반부는 상기 안내레일과 상기 인입레일을 상기 이음레일로 연결시 상기 이음레일 연결부와 상기 인입레일 연결부 간의 연결구조에 의해 상기 가공챔버에 고정되도록 연결되는 것을 특징으로 하는 농산물 가공장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

675/1150 Row 675: application_number: 1020200129602, combined_string: invention_title: 농산물 가공방법 abstract: 농산물 가공방법이 개시된다. 본 발명에 따른 농산물 가공방법은, 토마토가 수용된 적어도 하나 이상의 농산물 수용부를 운반부에 적재하여 가공챔버의 인입 위치까지 운반하고, 상기 운반부에 설치된 안내레일과 이음레일을 상기 가공챔버의 내부에 형성된 인입레일과 연결하는 단계; 상기 농산물 수용부를 상기 안내레일 및 이음레일을 따라 이동시켜 상기 인입레일에 위치되도록 상기 가공챔버 내로 인입시킨 후, 상기 운반부를 상기 가공챔버와 분리하고, 상기 가공챔버를 밀폐시키는 단계; 상기 가공챔버를 진공펌프에 의해 일정시간 동안 진공상태로 유지시켜 토마토 껍질과 내용물 사이에 침투공간을 형성하는 단계; 상기 토마토 껍질과 내용물 사이에 침투공간의 형성 후, 상기 가공챔버의 진공상태를 해제하고, 상기 토마토가 복원되도록 일정시간 동안 안정화시키는 단계; 상기 토마토의 안정화 후, 가압펌프를 동작시켜 혼합액 저장부에 저장된 혼합액을 상기 가공챔버에 공급하여 채우고 일정시간 동안 가압하는 단계; 상기 가압펌프에 의해 상기 가공챔버의 가압상태를 일정시간 동안 해제하고 다시 일정시간 동안 가압하여 상기 가공챔버의 가압을 유지하는 단계; 및 상기 가공챔버에 채워진 혼합액을 상기 혼합액 저장부로 회수하고, 상기 가공챔버를 개방하여 상기 농산물 수용부를 인출하는 단계;를 포함하는 것을 특징으로 한다. claims: 토마토가 수용된 적어도 하나 이상의 농산물 수용부를 운반부에 적재하여 가공챔버의 인입 위치까지 운반하고, 상기 운반부에 설치된 안내레일과 이음레일을 상기 가공챔버의 내부에 형성된 인입레일과 연결하는 단계;상기 농산물 수용부를 상기 안내레일 및 이음레일을 따라 이동시켜 상기 인입레일에 위치되도록 상기 가공챔버 내로 인입시킨 후, 상기 운반부를 상기 가공챔버와 분리하고, 상기 가공챔버를 밀폐시키는 단계;상기 가공챔버를 진공펌프에 의해 일정시간 동안 진공상태로 유지시켜 토마토 껍질과 내용물 사이에 침투공간을 형성하는 단계;상기 토마토 껍질과 내용물 사이에 침투공간의 형성 후, 상기 가공챔버의 진공상태를 해제하고, 상기 농산물이 복원되도록 일정시간 동안 안정화시키는 단계;상기 농산물의 안정화 후, 가압펌프를 동작시켜 혼합액 저장부에 저장된 혼합액을 상기 가공챔버에 공급하여 채우고 일정시간 동안 가압하는 단계;상기 가압펌프에 의해 상기 가공챔버의 가압상태를 일정시간 동안 해제하고 다시 일정시간 동안 가압하여 상기 가공챔버의 가압을 유지하는 단계; 및상기 가공챔버에 채워진 혼합액을 상기 혼합액 저장부로 회수하고, 상기 가공챔버를 개방하여 상기 농산물 수용부를 인출하는 단계;를 포함하고,상기 인입레일은 일측에 고정홈을 갖는 계단형상의 인입레일 연결부가 형성되고, 상기 이음레일은 상기 인입레일과 연결되는 일측에 상기 인입레일 연결부와 대응되도록 고정돌기를 갖는 이음레일 연결부가 형성되며, 상기 운반부는 상기 안내레일과 상기 인입레일을 상기 이음레일로 연결시 상기 이음레일 연결부와 상기 인입레일 연결부 간의 연결구조에 의해 상기 가공챔버와 고정되도록 연결되는 것을 특징으로 하는 농산물 가공방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

676/1150 Row 676: application_number: 1020200103659, combined_string: invention_title: 건조장치 abstract: 본 발명에 따른 건조장치는, 건조실과 입구 및 출구를 갖는 건조 드럼을 구비하고, 드럼 회전장치로부터 회전력을 제공받아 회전하는 회전 드럼과, 건조실로 원료를 투입하는 원료 투입기와, 건조실의 원료를 파쇄하기 위한 파쇄기와, 탈취로 및 송풍기를 구비하고 열풍을 발생하는 열풍 공급기와, 회전 드럼과 열풍 공급기를 연결하는 열풍 공급덕트와, 출구로부터 배출되는 건조물을 외부로 배출시키기 위한 건조물 배출부를 갖는 건조물 배출덕트와, 건조 드럼을 감싸도록 설치되는 배기덕트와, 회전 드럼에 결합되고 건조물 배출덕트로 유입되는 배기 가스를 배기덕트로 유동시키는 폐열회수관과, 배기덕트의 배기 가스를 원심 분리하여 이물질을 제거하고 이물질이 제거된 배기 가스를 열풍 공급기에 공급하는 열회수용 집진기를 포함한다. claims: 원료를 건조하기 위한 건조실과 상기 건조실과 연결되도록 일단 및 타단에 각각 마련되는 입구와 출구를 갖는 건조 드럼을 구비하고, 드럼 회전장치로부터 회전력을 제공받아 회전하는 회전 드럼;상기 입구를 통해 상기 건조실로 원료를 투입하는 원료 투입기;상기 건조실의 원료를 파쇄하기 위해 상기 건조실에 배치되어 회전하는 복수의 블레이드를 구비하는 파쇄기;내부에 연소실이 마련된 탈취로와, 상기 탈취로로 공기를 송풍하는 송풍기를 구비하고, 상기 건조실에 공급하기 위한 열풍을 발생하는 열풍 공급기;상기 회전 드럼의 일단을 회전 가능하게 지지하고, 상기 열풍 공급기에서 공급되는 열풍을 상기 건조실로 유입시키기 위해 상기 회전 드럼과 상기 열풍 공급기를 연결하는 열풍 공급덕트;상기 회전 드럼의 타단을 회전 가능하게 지지하고, 상기 출구와 연결되며, 상기 출구로부터 배출되는 건조물을 외부로 배출시키기 위한 건조물 배출부를 갖는 건조물 배출덕트;상기 건조 드럼을 감싸도록 설치되는 배기덕트;상기 회전 드럼과 함께 회전할 수 있도록 상기 회전 드럼에 결합되며, 일단에 상기 건조물 배출덕트의 내부와 연결되는 유입구가 구비되고 타단에 상기 배기덕트의 내부와 연결되는 유출구가 마련되어 상기 회전 드럼에서 상기 건조물 배출덕트로 유입되는 배기 가스를 상기 배기덕트로 유동시키는 폐열회수관; 및상기 배기덕트의 배기 가스를 원심 분리하여 이물질을 제거할 수 있도록 상기 배기덕트와 연결되고, 이물질이 제거된 배기 가스를 상기 열풍 공급기에 공급하는 열회수용 집진기;를 포함하고,상기 열풍 공급기는 외기와 상기 열회수용 집진기에서 공급되는 배기 가스를 혼합하여 가열 후 상기 건조실에 공급하는 것을 특징으로 하는 건조장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

677/1150 Row 677: application_number: 1020200090193, combined_string: invention_title: 농산물 매매가격 제시 방법 및 시스템 abstract: 본 개시는 정보 처리 시스템에 의해 수행되는 농산물 매매가격 제시 방법에 관한 것이다. 농산물 매매가격 제시 방법은, 통신부에 의해, 시세 데이터 세트를 수신하는 단계, 프로세서에 의해, 시세 데이터 세트에 주성분 분석(Principal Component Analysis)을 사용하여 시장 수급 상황을 반영한 주성분을 추출하는 단계, 프로세서에 의해, 추출된 주성분에 따라 미리 결정된 생산자 수취 가격의 비율을 적용하여 표준 가격을 산출하는 단계를 포함할 수 있다. claims: 정보 처리 시스템에 의해 수행되는 농산물 매매가격 제시 방법에 있어서,통신부에 의해, 농산물의 출하가, 경매가, 도매가, 소매가 중 적어도 하나를 포함하는 시세 데이터 세트를 수신하는 단계;프로세서에 의해, 상기 시세 데이터 세트에 주성분 분석(Principal Component Analysis)을 사용하여 시장 수급 상황을 반영한 주성분을 추출하는 단계;상기 프로세서에 의해, 상기 추출된 주성분에 미리 결정된 생산자 수취 가격의 비율을 적용하여 표준 가격을 산출하는 단계; 및상기 프로세서에 의해, 상기 산출된 표준 가격에 미리 결정된 스케일링 조정값을 적용하여 제시 가격을 산출하는 단계 - 상기 스케일링 조정값은 상품 대비 파품의 수율의 차이를 반영한 값을 포함하고, 상기 제시 가격은 등급 외 농산물의 제시 가격임 -를 포함하는, 농산물 매매가격 제시 방법.제1항에 따른 정보 처리 시스템에 의해 농산물 매매가격 제시 방법을 컴퓨터에서 실행하기 위한 컴퓨터 프로그램이 기록된, 컴퓨터로 판독 가능한 매체.정보 처리 시스템에 있어서,농산물의 출하가, 경매가, 도매가, 소매가 중 적어도 하나를 포함하는 시세 데이터 세트를 수신하도록 구성된 통신부;상기 시세 데이터 세트 및 하나 이상의 프로그램 명령어를 저장하도록 구성된 저장부; 및상기 저장된 하나 이상의 프로그램 명령어를 실행함으로써, 시세 데이터 세트에 주성분 분석을 사용하여 주성분을 추출하는 주성분 분석부 및 추출된 주성분에 미리 결정된 생산자 수취 가격의 비율을 적용하여 표준 가격을 산출하도록 구성된 가격조정부로 구성된 프로세서를 포함하며,상기 가격조정부는,상기 산출된 표준 가격에 미리 결정된 스케일링 조정값을 적용하여 제시 가격을 산출하도록 더 구성되며, 상기 스케일링 조정값은 상품 대비 파품의 수율의 차이를 반영한 값을 포함하고, 상기 제시 가격은 등급 외 농산물의 제시 가격인,정보 처리 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

678/1150 Row 678: application_number: 1020200083822, combined_string: invention_title: 열풍 건조장치 abstract: 본 발명은 음식물쓰레기 또는 하수 슬러지가 건조되는 과정에서 발생하는 많은 양의 수분을 외부로 빠르게 배출시킬 수 있고, 많은 양의 음식물쓰레기 또는 하수 슬러지를 빠르고 효과적으로 건조시킬 수 있는 열풍 건조장치에 관한 것이다.상기의 과제를 해결하기 위한 본 발명에 따른 열풍 건조장치는, 피건조물이 상부 일측으로 투입된 다음 사행상의 유로를 따라 하부 일측으로 이송되어 배출되는 건조부; 상기 건조부의 내측에 수평으로 길이를 가지도록 설치되면서 피건조물을 이송시키는 복수 개의 이송부; 상기 건조부의 일측에 위치되면서 상기 이송부를 회전 동작시키는 구동부; 상기 건조부의 일측에 위치되면서 소정 온도로 공기를 가열하여 열풍을 생성하는 열풍발생부; 상기 건조부의 일측 내부와 연통되는 복수 개의 배관을 포함하는 열풍공급관; 상기 건조부의 타측 내부와 연통되는 복수 개의 배관을 포함하는 열풍배출관; 상기 열풍공급관에 설치되면서 상기 건조부 내측으로 열풍을 공급하는 공급블로워; 상기 열풍배출관에 설치되면서 상기 건조부 내측의 열풍을 외부로 배출시키는 배출블로워; 및 상기 구동부, 열풍발생부, 공급블로워 및 배출블로워의 동작을 제어하는 제어부를 포함하는 것을 특징으로 한다. claims: 피건조물이 상부 일측으로 투입된 다음 사행상의 유로를 따라 하부 일측으로 이송되어 배출되는 건조부(10);상기 건조부(10)의 내측에 수평으로 길이를 가지도록 설치되면서 피건조물을 이송시키는 복수 개의 이송부(20);상기 건조부(10)의 일측에 위치되면서 상기 이송부(20)를 회전 동작시키는 구동부(30);상기 건조부(10)의 일측에 위치되면서 소정 온도로 공기를 가열하여 열풍을 생성하는 열풍발생부(40);상기 건조부(10)의 일측 내부와 연통되는 복수 개의 배관을 포함하는 열풍공급관(50);상기 건조부(10)의 타측 내부와 연통되는 복수 개의 배관을 포함하는 열풍배출관(60);상기 열풍공급관(50)에 설치되면서 상기 건조부(10) 내측으로 열풍을 공급하는 공급블로워(70);상기 열풍배출관(60)에 설치되면서 상기 건조부(10) 내측의 열풍을 외부로 배출시키는 배출블로워(80); 및상기 구동부(30), 열풍발생부(40), 공급블로워(70) 및 배출블로워(80)의 동작을 제어하는 제어부(90);를 포함하고,상기 건조부(10)는,상하 복수 열로 배치되면서 수평으로 소정 길이를 가지도록 설치되는 복수 개의 메인배관(11); 및상기 메인배관(11)의 양단에 설치되면서 상하로 인접하여 위치되는 상기 메인배관(11)의 유로를 사행상으로 연결하는 복수 개의 3방향 연결배관(12);을 포함하며,상기 메인배관(11)에는,외측면과 소정 간격 이격되어 감싸도록 소정 지름을 가지는 보조배관(11A)이 구비되어 이중배관으로 형성되고,상기 열풍공급관(50)은,상기 메인배관(11)의 일단 내부, 상기 보조배관(11A)의 일단 내부 및 상기 이송부(20)의 일단 내부로 각각 열풍이 공급되도록 배관이 연결되며,상기 열풍배출관(60)은,상기 메인배관(11)의 타단 내부 및 상기 보조배관(11A)의 타단 내부와 연결되어 내부의 열풍이 외부로 배출되도록 배관이 연결되고,상기 이송부(20)는,소정 지름을 가지면서 내부를 따라 소정 지름의 관통공(H)이 형성되는 회전축(21);상기 회전축(21)의 외측면을 따라 나선 모양으로 형성되는 소정 폭의 나선플레이트(22); 및상기 회전축(21)의 양단에 설치되어 열풍을 차단하는 소정 지름의 패킹(23);을 포함하고,상기 회전축(21)에는,상기 관통공(H)의 내측으로 열풍을 공급하는 열풍유입공(21A)이 일단에 형성되고, 상기 나선플레이트(22) 사이로 열풍을 배출시키는 복수 개의 열풍배출공(21B)이 길이를 따라 형성되며,상기 공급블로워(70)의 공기 유입구와 상기 배출블로워(80)의 공기 배출구를 연결하는 유로가 설치되고, 상기 유로상에는 배출되는 공기 중에 포함된 습기가 저장되는 수분저장탱크(100)가 설치되며, 외부로 배출되는 공기 중에 포함된 수분으로 인한 악취가 발생하지 않도록 하고,상기 수분저장탱크(100)를 기준으로 일측 상기 유로상에 제1 에어필터(F1)와 제1 스트레이너(S1)가 설치되고, 타측 상기 유로상에 제2 에어필터(F2)와 제2 스트레이너(S2)가 설치되며, 공기가 유로를 따라 순환되는 동안 공기 중의 이물질이 제거되도록 구성되는 것을 특징으로 하는 열풍 건조장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

679/1150 Row 679: application_number: 1020207031220, combined_string: invention_title: 공기 흡입식 마늘 배향 배종 장치 abstract: 본 발명은 농업 기계 기술 분야에 관한 것으로, 더욱 상세하게는 공기 흡입식 마늘 배향 배종 장치에 관한 것이며, 여기에는 종자실 하우징, 종자 흡입실 하우징, 종자 흡착판, 밀봉 링, 배향 탄성편, 내부 배향 핀, 외부 배향 핀, 이미지 수집기, 회전 배향 장치, 이미지 식별 제어 유닛, 전동축 및 전동 스프로킷이 포함되고, 종자실 하우징은 종자 흡입실 하우징과 고정 연결되고, 종자 흡착판은 종자실 하우징과 종자 흡입실 하우징 사이에 배치되고, 종자 흡착판과 종자 흡입실 하우징 사이에 밀봉 링이 설치되고, 종자 흡입실 하우징 상에는 흡입관이 설치되고, 종자 흡착판은 원주를 따라 균일하게 복수의 종자 흡입 통공이 설치되고, 종자 흡착판의 배향 영역에서 각 종자 흡입 통공 중심원 시계 반대 방향을 따라 순차적으로 배향 탄성편, 내부 배향 핀, 외부 배향 핀, 이미지 수집기 및 회전 배향 장치가 배치되고, 전동축 일단은 종자 흡착판 중심에 고정 연결되고, 타단은 전동 스프로킷에 고정 연결되고, 중간은 베어링을 거쳐 종자 흡입실 하우징 상에서 지탱된다. 본 발명은 마늘 종자의 단립 배향 배종을 구현할 수 있다. claims: 공기 흡입식 마늘 배향 배종 장치에 있어서, 종자실 하우징(1), 종자 흡입실 하우징(2), 종자 흡착판(3), 밀봉 링(4), 배향 탄성편(7), 내부 배향 핀(8), 외부 배향 핀(9), 이미지 수집기(10), 회전 배향 장치, 이미지 식별 제어 유닛, 전동축(5) 및 전동 스프로킷(6)을 포함하고, 종자실 하우징(1)은 종자 흡입실 하우징(2)과 고정 연결되고, 종자 흡착판(3)은 종자실 하우징(1)과 종자 흡입실 하우징(2) 사이에 배치되고, 종자 흡착판(3)과 종자 흡입실 하우징(2) 사이에 밀봉 링(4)이 설치되고, 밀봉 링(4), 종자 흡착판(3), 종자 흡입실 하우징(2)은 종자 흡입실(11)을 둘러싸고, 종자 흡입실 하우징(2) 상에는 흡입관(13)이 설치되고, 흡입관(13)은 종자 흡입실(11)과 연통하고, 종자 흡착판(3)과 종자실 하우징(1)은 종자실(12)을 둘러싸고, 종자실 하우징(1) 상단에 개구가 설치되고, 종자 흡착판(3)은 원주를 따라 균일하게 복수의 원형 통공이 설치되고, 각 원형 통공 내에는 조합 흡입 블록이 설치되고, 조합 흡입 블록은 원형 통공 갭에 매칭되고, 조합 흡입 블록 중심에는 종자 흡입 통공이 설치되고, 대응하는 종자 흡착판(3)의 비스듬한 상방은 각 종자 흡입 통공 중심원을 따라 반시계 방향으로 배향 탄성편(7), 내부 배향 핀(8), 외부 배향 핀(9), 이미지 수집기(10) 및 회전 배향 장치가 순차적으로 배치되고, 배향 탄성편(7), 내부 배향 핀(8), 외부 배향 핀(9), 이미지 수집기(10)가 종자실 하우징(1) 상에 고정되고, 회전 배향 장치는 종자 흡착판(3)의 타측에서 종자 흡입실 하우징(2) 상에 고정되고, 배향 탄성편(7), 이미지 수집기(10) 및 회전 배향 장치의 중심은 종자 흡입 통공 중심원에 대응하고, 내부 배향 핀(8), 외부 배향 핀(9)은 각각 종자 흡입 통공 중심원의 내측과 외측에 위치하고, 전동축(5) 일단은 종자 흡착판(3) 중심에 고정 연결되고, 타단은 전동 스프로킷(6)에 고정 연결되고, 중간은 베어링을 거쳐 종자 흡입실 하우징(2) 상에서 지탱되는 것을 특징으로 하는 공기 흡입식 마늘 배향 배종 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

680/1150 Row 680: application_number: 1020200045251, combined_string: invention_title: 제습 건조기 abstract: 본 발명은 제습 건조기에 관한 것으로서, 농산물 등의 피건조물을 건조시키기 위한 공기에 포함된 수분의 제습효율이 매우 우수함은 물론 여름철 저온건조 및 겨울철 고온건조가 가능하고, 나아가, 피건조물 전체를 균일하게 건조할 수 있어 건조효율이 크게 향상될 수 있으며, 공기의 저항이 줄어들어 공기의 순환흐름이 크게 향상될 수 있는 효과가 있다. claims: 피건조물이 수용되고, 내부 타측에 격벽이 수직형성되며, 상기 격벽과 타측 내면 사이에 피건조물을 건조시키기 위한 공기가 순환이동하는 순환공간이 형성되는 건조실과;상기 건조실의 순환공간에 구비되고, 상기 건조실의 내부 일측에서 상기 순환공간의 하부로 순환이동하는 공기가 통과 및 공기에 포함된 습기를 제거하는 증발기와;상기 증발기의 상부방향에 위치하도록 상기 건조실의 순환공간에 구비되고, 상기 증발기를 통과한 습기가 제거된 공기가 통과 및 공기를 가열하는 응축기와;상기 건조실의 일측에서 타측방향으로 일정길이로 연장되어 상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 상부에 구비되고, 상기 응축기에 의해 가열된 공기를 통해 피건조물을 건조시키기 위해 내부로 유입된 상기 응축기에 의해 가열된 공기를 상기 건조실의 내부 일측으로 배출하는 배출구가 형성되는 상부덕트와;상기 상부덕트의 내부로 상기 증발기에 의해 습기가 제거 및 상기 응축기에 의해 가열된 공기를 안내하는 송풍기와;상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 하부에 구비되고, 상기 상부덕트의 배출구를 통해 상기 건조실의 내부 일측으로 배출되어 피건조물을 건조시키는 공기가 유입되는 유입구가 형성되며, 상기 유입구를 통해 내부로 유입된 공기를 상기 순환공간으로 안내하는 하부덕트와;상기 건조실의 외부에 설치되고, 상기 건조실의 순환공간에 구비된 증발기 및 응축기와 연결되는 압축기 및 응축기가 구비되는 실외기와;상기 건조실의 순환공간에 구비된 증발기와 상기 실외기의 압축기를 연결하는 제 1연결라인과, 상기 실외기의 압축기와 상기 실외기의 응축기를 연결하는 제 2연결라인과, 상기 실외기의 응축기와 상기 건조실의 순환공간에 구비된 증발기를 연결하는 제 3연결라인과, 상기 제 2연결라인으로부터 분기되어 상기 제 2연결라인과 상기 건조실의 순환공간에 구비된 응축기를 연결하는 제 4연결라인과, 상기 제 4연결라인과 일정간격을 유지한 상태로 상기 제 2연결라인으로부터 분기되어 상기 제 2연결라인과 상기 건조실의 순환공간에 구비된 응축기를 연결하는 제 5연결라인으로 구성되는 연결라인과;상기 제 4연결라인에 구비되는 체크밸브와;상기 제 4연결라인이 분기되는 상기 제 2연결라인의 분기지점과 상기 제 5연결라인이 분기되는 제 2연결라인의 분기지점 사이의 상기 제 2연결라인에 구비되어 상기 제 2연결라인을 개폐하는 제 1개폐밸브와, 상기 제 5연결라인에 구비되어 상기 제 5연결라인을 개폐하는 제 2개폐밸브로 구성되는 개폐밸브와;상기 건조실의 내부의 온도를 설정하는 온도설정부와;상기 건조실의 내부의 온도를 감지하는 온도센서와;상기 응축기의 상부방향에 위치하도록 상기 건조실의 순환공간에 구비되는 보조히터와;상기 온도센서의 온도감지값과 상기 온도설정부의 온도설정값을 비교하여 상기 개폐밸브, 상기 건조실의 순환공간의 증발기와 응축기 및 상기 실외기와 상기 보조히터를 제어하는 제어부;를 포함하여 이루어지는 것을 특징으로 하는 제습 건조기.피건조물이 수용되고, 내부 타측에 격벽이 수직형성되며, 상기 격벽과 타측 내면 사이에 피건조물을 건조시키기 위한 공기가 순환이동하는 순환공간이 형성되는 건조실과;상기 건조실의 순환공간에 구비되고, 상기 건조실의 내부 일측에서 상기 순환공간의 하부로 순환이동하는 공기가 통과 및 공기에 포함된 습기를 제거하는 증발기와;상기 증발기의 일측 하부에 구비되고, 상기 증발기에서 발생되어 상기 증발기의 일측 하부방향으로 낙하하는 물이 내부에 수용되는 물받이부와;상기 물받이부의 내면 일측에 상기 물받이부의 일측에서 타측 하부방향으로 하향경사지게 일정높이로 형성되는 일측 경사판과, 상기 물받이부의 내면 타측에 상기 물받이부의 타측에서 일측 하부방향으로 하향경사지게 일정높이로 형성되고 일측이 상기 일측 경사판의 타측 하부 방향에 위치하는 타측 경사판으로 구성되는 경사판부와;상기 증발기의 상부방향에 위치하도록 상기 건조실의 순환공간에 구비되고, 상기 증발기를 통과한 습기가 제거된 공기가 통과 및 공기를 가열하는 응축기와;상기 건조실의 일측에서 타측방향으로 일정길이로 연장되어 상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 상부에 구비되고, 상기 응축기에 의해 가열된 공기를 통해 피건조물을 건조시키기 위해 내부로 유입된 상기 응축기에 의해 가열된 공기를 상기 건조실의 내부 일측으로 배출하는 배출구가 형성되는 상부덕트와;상기 상부덕트의 내부로 상기 증발기에 의해 습기가 제거 및 상기 응축기에 의해 가열된 공기를 안내하는 송풍기와;상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 하부에 구비되고, 상기 상부덕트의 배출구를 통해 상기 건조실의 내부 일측으로 배출되어 피건조물을 건조시키는 공기가 유입되는 유입구가 형성되며, 상기 유입구를 통해 내부로 유입된 공기를 상기 순환공간으로 안내하는 하부덕트;를 포함하여 이루어지는 것을 특징으로 하는 제습 건조기.피건조물이 수용되고, 내부 타측에 격벽이 수직형성되며, 상기 격벽과 타측 내면 사이에 피건조물을 건조시키기 위한 공기가 순환이동하는 순환공간이 형성되는 건조실과;상기 건조실의 순환공간에 구비되고, 상기 건조실의 내부 일측에서 상기 순환공간의 하부로 순환이동하는 공기가 통과 및 공기에 포함된 습기를 제거하는 증발기와;상기 증발기의 상부방향에 위치하도록 상기 건조실의 순환공간에 구비되고, 상기 증발기를 통과한 습기가 제거된 공기가 통과 및 공기를 가열하는 응축기와;상기 건조실의 일측에서 타측방향으로 일정길이로 연장되어 상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 상부에 구비되고, 상기 응축기에 의해 가열된 공기를 통해 피건조물을 건조시키기 위해 내부로 유입된 상기 응축기에 의해 가열된 공기를 상기 건조실의 내부 일측으로 배출하는 배출구가 전측, 후측 및 하부에 각각 형성되며, 상하간격이 타측에서 일측으로 갈수록 점차 작아지는 상부덕트와;상기 상부덕트의 내부로 상기 증발기에 의해 습기가 제거 및 상기 응축기에 의해 가열된 공기를 안내하는 송풍기와;상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 전측 하부에 상기 건조실의 일측에서 타측방향으로 일정길이로 좌우연장되는 전측 하부덕트와, 상기 건조실의 순환공간과 연통되도록 상기 건조실의 내부 후측 하부에 상기 전측 하부덕트를 따라 일정길이로 좌우연장되는 후측 하부덕트와, 상기 전측 하부덕트 및 상기 후측 하부덕트와 연통되도록 상기 건조실의 내부 일측 하부에 상기 건조실의 전측에서 후측방향으로 일정길이로 전후연장되는 일측 하부덕트로 구성되고, 상기 전측 하부덕트, 상기 후측 하부덕트 및 상기 일측 하부덕트에 상기 상부덕트의 배출구를 통해 상기 건조실의 내부 일측으로 배출되어 피건조물을 건조시키는 공기가 유입되는 유입구가 형성되며, 상기 유입구를 통해 내부로 유입된 공기를 상기 순환공간으로 안내하는 하부덕트;를 포함하여 이루어지는 것을 특징으로 하는 제습 건조기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

681/1150 Row 681: application_number: 1020200041883, combined_string: invention_title: 플라즈마를 이용한 종자 처리 장치 abstract: 본 발명에 의하면, 수용 공간인 챔버를 제공하는 챔버 하우징; 상기 챔버에 수용되고 플라즈마 방전을 이용하여 종자를 처리하는 복수개의 종자 처리 모듈들; 및 상기 플라즈마 방전을 위하여 상기 복수개의 종자 처리 모듈들 각각으로 전원을 공급하는 전원 공급부를 포함하며, 상기 종자 살균 모듈들 각각은 상기 챔버에 위치하도록 설치되고 상기 플라즈마 방전이 일어나는 플라즈마 방전 유닛과, 상기 플라즈마 방전 유닛과 분리 가능하게 결합되고 처리 대상 종자들이 담기는 트레이 유닛을 구비하는 플라즈마를 이용한 종자 처리 장치가 제공된다. claims: 수용 공간인 챔버를 제공하는 챔버 하우징;상기 챔버에 수용되고 플라즈마 방전을 이용하여 종자를 처리하는 복수개의 종자 처리 모듈들;상기 챔버의 공기를 외부로 배출하여 상기 챔버를 진공 상태로 형성하는 배기 펌프; 및상기 플라즈마 방전을 위하여 상기 복수개의 종자 처리 모듈들 각각으로 전원을 공급하는 전원 공급부를 포함하며,상기 종자 처리 모듈들 각각은 상기 챔버에 위치하도록 설치되고 상기 플라즈마 방전이 일어나는 플라즈마 방전 유닛과, 상기 플라즈마 방전 유닛과 분리 가능하게 결합되고 처리 대상 종자들이 담기는 트레이 유닛을 구비하며,상기 트레이 유닛에는 상기 트레이 유닛이 상기 플라즈마 방전 유닛에 결합된 상태에서 상기 트레이 유닛의 내부와 외부를 연통시키는 연통 유로가 형성되며,상기 챔버의 공기가 외부로 배출되는 과정에서 상기 트레이 유닛 내의 공기도 상기 연통 유로를 통해 배출되어서, 상기 트레이 유닛의 내부에 플라즈마 방전이 용이한 진공 상태가 형성되는,플라즈마를 이용한 종자 처리 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

682/1150 Row 682: application_number: 1020200020594, combined_string: invention_title: 빅데이터에 기반한 농업 공공 데이터를 수집하는 방법 및 이를 위한 장치 abstract: 본 발명은 농산물 관리 서버가 빅데이터를 기반으로 농산물의 수요를 예측하는 방법을 개시한다. 특히, 상기 방법은 기상 예측 서버로부터 현시점 이후 제 1 기간 동안의 복수의 농업 피해 요소들에 관련된 기상 예측 정보를 수신하고, 현시점부터 제 2 기간 전까지의 상기 농산물의 판매량, 판매 가격 및 상기 복수의 농업 피해 요소들에 대한 정보를 획득하고, 미디어 서버로부터 상기 농산물의 검색량 및 상기 농산물과 관련된 키워드를 획득하여, 상기 농산물의 소비 추이를 분석하고, 상기 기상 예측 정보, 상기 농업 피해 요소들에 대한 정보 및 상기 농산물의 소비 추이를 기반으로, 제 3 기간 이후의 시점에서의 상기 농산물의 가격 및 수요를 예측하는 것을 특징으로 한다. claims: 농산물 관리 서버가 빅데이터를 기반으로 농산물의 수요를 예측하는 방법에 있어서,기상 예측 서버로부터 현시점 이후 제 1 기간 동안의 복수의 농업 피해 요소들에 관련된 기상 예측 정보를 수신하고,현시점부터 제 2 기간 전까지의 상기 농산물의 판매량, 판매 가격 및 상기 복수의 농업 피해 요소들에 대한 정보를 획득하고,미디어 서버로부터 상기 농산물의 검색량 및 상기 농산물과 관련된 키워드를 획득하여, 상기 농산물의 소비 추이를 분석하고,상기 기상 예측 정보, 상기 농업 피해 요소들에 대한 정보 및 상기 농산물의 소비 추이를 기반으로, 제 3 기간 이후의 시점에서의 상기 농산물의 가격 및 수요를 예측하고,상기 농산물의 소비 추이를 분석하는 것은,상기 농산물이 검색되거나 상기 농산물과 관련된 키워드를 획득하는데 기반이 된 미디어 매체들 각각에 대한 서로 다른 가중치를 부여하고,상기 서로 다른 가중치를 기반으로 상기 농산물의 소비 추이를 분석하는 것을 포함하고,상기 농산물과 관련된 병충해 정보를 획득하고,상기 병충해 정보를 기반으로 상기 병충해 정보와 관련된 병충해로 인한 상기 농산물의 피해 규모 및 피해 기간을 추정하고,상기 병충해로 인한 피해 규모 및 피해 기간을 최소화하기 위한 방지책을 결정하는 것을 더 포함하고,상기 병충해 정보는 상기 병충해의 종류, 상기 병충해의 예상 개체 수 및 상기 병충해가 상기 농산물에 입히는 피해 종류를 포함하고,상기 농산물의 가격 및 수요를 기반으로 상기 농산물의 매입 시점 및 상기 농산물의 매도 시점을 결정하고,상기 농산물의 가격 및 수요를 예측하는 것은,상기 농산물이 수입되는 수입량 및 상기 수입되는 농산물의 가격을 더 고려하고,상기 복수의 농업 피해 요소들은 풍수, 침수, 산불, 폭염 및 가뭄에 관련된 피해 요소들 및 야생 동물에 관련된 피해 요소를 포함하고,상기 제 2 기간 전의 상기 복수의 농업 피해 요소들 각각에 의한 농업 피해 규모를 획득하고,상기 농업 피해 규모를 기반으로 상기 복수의 농업 피해 요소들 각각에 서로 다른 가중치를 설정하고,상기 서로 다른 가중치를 기반으로 상기 농산물의 생산량을 예측하는 것을 더 포함하고,상기 농업 피해 규모는 상기 복수의 농업 피해 요소들 각각에 대한 억원 단위의 금액 정보를 포함하고,상기 복수의 농업 피해 요소들 중 상기 농업 피해 규모에 따른 금액 정보 간의 차이가 일정 값 미만인 농업 피해 요소들은 동일한 가중치가 설정되고,동일한 가중치로 설정된 농업 피해 요소들이 3가지 이상이고, 가장 낮은 금액 정보를 가지는 농업 피해 요소 및 가장 높은 금액 정보를 가지는 농업 피해 요소 간의 차이가 상기 일정 값 이상인 경우, 상기 가장 높은 금액 정보를 가지는 농업 피해 요소에 대한 가중치는 상기 동일한 가중치에 1.1배로 설정되고,상기 농산물과 관련된 병충해 정보는,농산물의 특정 부위에 대한 복수 개의 제 1 이미지들을 획득하고,상기 복수 개의 제 1 이미지 들을 기반으로, 상기 농산물이 병충해 피해를 입지 않은 경우의 상기 특정 부위의 제 1 색상 정보를 추출하고, 상기 농산물의 특정 부위가 병충해 피해를 입은 것을 포함하는 복수 개의 제 2 이미지들을 획득하고, 상기 복수 개의 제 2 이미지들에 포함된 상기 특정 부위의 제 2 색상 정보를 추출하고, 상기 제 1 색상 정보 및 상기 제 2 색상 정보를 비교하여, 병충해가 발생한 경우의 이미지 값들을 저장하고, 농장에 설치된 카메라를 통해 수신한 제 3 이미지를 상기 이미지 값과 비교한 것을 기반으로 획득되는,농산물 수요 예측 방법., Ltext: 농업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

683/1150 Row 683: application_number: 1020200020605, combined_string: invention_title: IoT 기술을 이용하여 농산물을 생산하는 방법 및 이를 위한 장치 abstract: 본 발명은 농장 관리 서버가 농산물을 생산하기 위해 IoT (Internet of Things)를 이용한 스마트 농장을 제어하는 방법을 개시한다. 특히, 상기 방법은, 상기 스마트 농장에서 생산하는 농산물에 대한 정보를 추출하고, 상기 스마트 농장에 설치된 온습도 센서를 통해 상기 스마트 농장의 온습도 정보를 획득하고, 상기 농산물에 대한 정보를 기반으로, 상기 스마트 농장의 목표 온습도를 설정하고, 상기 목표 온습도를 기반으로, 상기 스마트 농장의 조명 장치 및 가습 장치를 제어하는 것을 특징으로 한다. claims: 농장 관리 서버가 농산물을 생산하기 위해 IoT (Internet of Things)를 이용한 스마트 농장을 제어하는 방법에 있어서,상기 스마트 농장에서 생산하는 농산물에 대한 정보를 추출하고,상기 스마트 농장에 설치된 온습도 센서를 통해 상기 스마트 농장의 온습도 정보를 획득하고,상기 농산물에 대한 정보를 기반으로, 상기 스마트 농장의 목표 온습도를 설정하고,상기 목표 온습도를 기반으로, 상기 스마트 농장의 조명 장치 및 가습 장치를 제어하고,상기 스마트 농장 내부에 설치된 카메라를 이용하여 상기 농산물의 크기를 측정하고,상기 농산물의 크기를 기반으로, 상기 농산물로 방출되는 조성물의 양 및 상기 조성물의 농도를 결정하고,상기 양 및 농도에 따라 상기 조성물을 방출할 것을 상기 스마트 농장에 명령하고,상기 농산물에 대한 정보를 기반으로, 상기 농산물에 대응하는 시간 별 목표 조도 및 추천 조명 색상을 획득하고,현재 시각, 목표 조도 및 추천 조명 색상을 기반으로, 상기 스마트 농장에 설치된 조명 장치를 제어하고,상기 조명 장치는,조명, 상기 조명의 아래에 설치되어 상기 조명의 명암을 조절하는 개폐 장치 및 상기 조명과 상기 개폐 장치 사이에 설치되어 상기 조명의 색상을 변경하기 위한 광색 조절 장치를 포함하고,상기 조명 장치를 제어하는 것은,현 시간에 대응하는 상기 농산물을 위한 광색에 대한 정보를 RGB 값으로 획득하고,상기 광색 조절 장치에 포함된 복수의 광색판들 중, 상기 RGB 값과 가장 가까운 RGB 값을 가지는 제 1 광색판을 상기 조명의 아래쪽으로 위치시키고, 상기 제 1 광색판을 제외한 나머지 제 2 광색판들은 상기 조명으로부터 일정 거리 이상 떨어져 위치하도록 제어하며,상기 농산물의 크기를 측정하는 것은,상기 카메라가 제 1 시점에서 상기 농산물을 촬영한 제 1 이미지와 상기 카메라가 상기 제 1 시점 이후인 제 2 시점에서 상기 농산물을 촬영한 제 2 이미지를 비교하여, 상기 제 1 이미지에서 상기 농산물이 차지하는 제 1 비율과 상기 제 2 이미지에서 상기 농산물이 차지하는 제 2 비율 간의 차이 값을 계산하고,상기 제 1 이미지에서의 상기 농산물의 제 1 크기를 산출하고,상기 차이 값 및 상기 제 1 크기를 기반으로, 상기 제 2 시점에서의 상기 농산물의 제 2 크기를 결정하는 것을 포함하고,상기 제 1 크기를 산출하는 것은,상기 카메라의 중심선을 기준으로 2개의 측정선들을 생성하고, 상기 2개의 측정선들 각각이 상기 농산물을 만나는 교차점들을 결정하고, 상기 교차점들을 잇는 선과 상기 중심선이 만나는 지점으로부터 카메라까지의 길이를 측정하고, 상기 측정된 카메라까지의 길이와, 상기 중심선과 상기 2개의 측정선 사이의 각도를 이용하여 상기 농산물의 세로 길이를 측정하고, 상기 세로 길이 및 상기 농산물의 가로 방향의 양 끝점을 기반으로 상기 농산물의 제 1 크기를 산출하는 것을 포함하며,상기 농산물은 복수의 재배 영역들에서 재배되고,상기 복수의 재배 영역들은 세로 길이는 동일하되, 가로 길이는 서로 상이하고,상기 복수의 재배 영역들은 각 라인 별로 설치된 가로 이동 레일들 위에 설치되어, 가로 방향으로 이동하며,상기 가로 이동 레일들의 가장 우측 방향으로 이동하여, 세로 이동 레일에 옮겨지면, 상기 세로 이동 레일에 따라 세로 방향으로 이동하는,스마트 농장 제어 방법.농산물을 생산하기 위해 IoT (Internet of Things)를 이용한 스마트 농장을 제어하는 농장 관리 서버에 있어서,스마트 농장과 데이터를 송수신하기 위한 통신 모듈;상기 데이터를 저장하는 저장 모듈; 및상기 통신 모듈 및 상기 저장 모듈과 연동되어, 상기 농장 관리 서버의 동작을 제어하는 제어 모듈;을 포함하고,상기 제어 모듈은,상기 저장 모듈로부터 상기 스마트 농장에서 생산하는 농산물에 대한 정보를 추출하고,상기 통신 모듈을 이용하여 상기 스마트 농장에 설치된 온습도 센서를 통해 상기 스마트 농장의 온습도 정보를 획득하고,상기 농산물에 대한 정보를 기반으로, 상기 스마트 농장의 목표 온습도를 설정하고,상기 통신 모듈을 이용하여 상기 목표 온습도를 기반으로, 상기 스마트 농장의 조명 장치 및 가습 장치를 제어하고,상기 스마트 농장 내부에 설치된 카메라를 이용하여 상기 농산물의 크기를 측정하고,상기 농산물의 크기를 기반으로, 상기 농산물로 방출되는 조성물의 양 및 상기 조성물의 농도를 결정하고,상기 양 및 농도에 따라 상기 조성물을 방출할 것을 상기 스마트 농장에 명령하고,상기 농산물에 대한 정보를 기반으로, 상기 농산물에 대응하는 시간 별 목표 조도 및 추천 조명 색상을 획득하고,현재 시각, 목표 조도 및 추천 조명 색상을 기반으로, 상기 스마트 농장에 설치된 조명 장치를 제어하고,상기 조명 장치는,조명, 상기 조명의 아래에 설치되어 상기 조명의 명암을 조절하는 개폐 장치 및 상기 조명과 상기 개폐 장치 사이에 설치되어 상기 조명의 색상을 변경하기 위한 광색 조절 장치를 포함하고,상기 조명 장치를 제어하는 것은,현 시간에 대응하는 상기 농산물을 위한 광색에 대한 정보를 RGB 값으로 획득하고,상기 광색 조절 장치에 포함된 복수의 광색판들 중, 상기 RGB 값과 가장 가까운 RGB 값을 가지는 제 1 광색판을 상기 조명의 아래쪽으로 위치시키고, 상기 제 1 광색판을 제외한 나머지 제 2 광색판들은 상기 조명으로부터 일정 거리 이상 떨어져 위치하도록 제어하며,상기 농산물의 크기를 측정하는 것은,상기 카메라가 제 1 시점에서 상기 농산물을 촬영한 제 1 이미지와 상기 카메라가 상기 제 1 시점 이후인 제 2 시점에서 상기 농산물을 촬영한 제 2 이미지를 비교하여, 상기 제 1 이미지에서 상기 농산물이 차지하는 제 1 비율과 상기 제 2 이미지에서 상기 농산물이 차지하는 제 2 비율 간의 차이 값을 계산하고,상기 제 1 이미지에서의 상기 농산물의 제 1 크기를 산출하고,상기 차이 값 및 상기 제 1 크기를 기반으로, 상기 제 2 시점에서의 상기 농산물의 제 2 크기를 결정하는 것을 포함하고,상기 제 1 크기를 산출하는 것은,상기 카메라의 중심선을 기준으로 2개의 측정선들을 생성하고, 상기 2개의 측정선들 각각이 상기 농산물을 만나는 교차점들을 결정하고, 상기 교차점들을 잇는 선과 상기 중심선이 만나는 지점으로부터 카메라까지의 길이를 측정하고, 상기 측정된 카메라까지의 길이와, 상기 중심선과 상기 2개의 측정선 사이의 각도를 이용하여 상기 농산물의 세로 길이를 측정하고, 상기 세로 길이 및 상기 농산물의 가로 방향의 양 끝점을 기반으로 상기 농산물의 제 1 크기를 산출하는 것을 포함하며,상기 농산물은 복수의 재배 영역들에서 재배되고,상기 복수의 재배 영역들은 세로 길이는 동일하되, 가로 길이는 서로 상이하고,상기 복수의 재배 영역들은 각 라인 별로 설치된 가로 이동 레일들 위에 설치되어, 가로 방향으로 이동하며,상기 가로 이동 레일들의 가장 우측 방향으로 이동하여, 세로 이동 레일에 옮겨지면, 상기 세로 이동 레일에 따라 세로 방향으로 이동하는,농장 관리 서버., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

684/1150 Row 684: application_number: 1020200020618, combined_string: invention_title: 인공지능 기술을 이용한 농산물의 병충해 발생 정보를 획득하는 방법 및 이를 위한 장치 abstract: 본 발명은 농산물 관리 서버가 병충해 정보를 획득하는 방법을 개시한다. 특히, 상기 방법은 농산물의 특정 부위에 대한 N 개의 제 1 이미지들을 획득하고, 상기 N 개의 제 1 이미지들을 기반으로, 상기 농산물이 병충해 피해를 입지 않은 경우의 상기 특정 부위의 제 1 색상 정보를 추출하고, 상기 농산물의 특정 부위가 병충해 피해를 입은 것을 포함하는 X 개의 제 2 이미지들을 획득하고, 상기 X 개의 제 2 이미지들에 포함된 상기 특정 부위의 제 2 색상 정보를 추출하고, 상기 제 1 색상 정보 및 상기 제 2 색상 정보를 비교하여, 병충해가 발생한 경우의 이미지 값들을 저장하고, 농장의 카메라를 통해 수신한 제 3 이미지를 상기 이미지 값과 비교한 것을 기반으로, 상기 병충해 정보를 획득할 수 있다. claims: 농산물 관리 서버가 병충해 정보를 획득하는 방법에 있어서,농산물의 특정 부위에 대한 N 개의 제 1 이미지들을 획득하고,상기 N 개의 제 1 이미지들을 기반으로, 상기 농산물이 병충해 피해를 입지 않은 경우의 상기 특정 부위의 제 1 색상 정보를 추출하고,상기 농산물의 특정 부위가 병충해 피해를 입은 것을 포함하는 X 개의 제 2 이미지들을 획득하고,상기 X 개의 제 2 이미지들에 포함된 상기 특정 부위의 제 2 색상 정보를 추출하고,상기 제 1 색상 정보 및 상기 제 2 색상 정보를 비교하여, 병충해가 발생한 경우의 이미지 값들을 저장하고,농장에 설치된 카메라를 통해 수신한 제 3 이미지를 상기 이미지 값과 비교한 것을 기반으로, 상기 병충해 정보를 획득하고,상기 병충해 정보를 획득하는 것은,상기 제 3 이미지를 상기 이미지 값과 비교한 것을 기반으로, 복수의 후보 병충해들을 선택하고,상기 제 3 이미지가 촬영된 시간, 상기 농장의 온습도, 상기 농장의 토양 성분을 기반으로, 상기 복수의 후보 병충해들 중, 특정 병충해를 결정하고,상기 농장은 상기 농장에 설치된 온습도 센서를 통해 상기 농장의 온습도 정보를 획득하고,상기 농장은 상기 온습도 정보 및 상기 농산물에 따른 목표 온습도를 기반으로 상기 농장에 설치된 조명 장치 및 가습 장치를 제어하고,상기 조명 장치는 조명, 상기 조명의 아래에 설치되어 상기 조명의 명암을 조절하는 개폐 장치 및 상기 조명과 상기 개폐 장치 사이에 설치되어 상기 조명의 색상을 변경하기 위한 광색 조절 장치를 포함하고,상기 조명 장치는 현 시간에 대응하는 상기 농산물을 위한 광색에 대한 정보를 RGB 값으로 획득하고, 상기 광색 조절 장치에 포함된 복수의 광색판들 중, 상기 RGB 값과 가장 가까운 RGB 값을 가지는 제 1 광색판을 상기 조명의 아래쪽으로 위치시키고, 상기 제 1 광색판을 제외한 나머지 제 2 광색판들은 상기 조명으로부터 일정 거리 이상 떨어져 위치하도록 제어되고,상기 농장은 상기 카메라를 통해 상기 농산물의 크기를 측정하고,상기 농산물의 크기에 대한 측정은 상기 카메라가 제 1 시점에서 상기 농산물을 촬영한 제 4 이미지와 상기 카메라가 상기 제 1 시점 이후인 제 2 시점에서 상기 농산물을 촬영한 제 5 이미지를 비교하여, 상기 제 4 이미지에서 상기 농산물이 차지하는 제 1 비율과 상기 제 5 이미지에서 상기 농산물이 차지하는 제 2 비율 간의 차이 값을 계산하고,상기 제 4 이미지에서의 상기 농산물의 제 1 크기를 산출하고,상기 차이 값 및 상기 제 1 크기를 기반으로, 상기 제 2 시점에서의 상기 농산물의 제 2 크기를 결정하는 것을 포함하고,상기 제 1 크기를 산출하는 것은 상기 카메라의 중심선을 기준으로 2개의 측정선들을 생성하고, 상기 2개의 측정선들 각각이 상기 농산물을 만나는 교차점들을 결정하고, 상기 교차점들을 잇는 선과 상기 중심선이 만나는 지점으로부터 상기 카메라까지의 길이를 측정하고, 상기 측정된 카메라까지의 길이와, 상기 중심선과 상기 2개의 측정선 사이의 각도를 이용하여 상기 농산물의 세로 길이를 측정하고, 상기 세로 길이 및 상기 농산물의 가로 방향의 양 끝점을 기반으로 상기 농산물의 제 1 크기를 산출하는 것을 포함하고,상기 농산물은 복수의 재배 영역들에서 재배되고,상기 복수의 재배 영역들은 세로 길이는 동일하되, 가로 길이는 서로 상이하고,상기 복수의 재배 영역들은 각 라인 별로 설치된 가로 이동 레일들 위에 설치되어, 가로 방향으로 이동하며,상기 가로 이동 레일들의 가장 우측 방향으로 이동하여, 세로 이동 레일에 옮겨지면, 상기 세로 이동 레일에 따라 세로 방향으로 이동하는,병충해 정보 획득 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

685/1150 Row 685: application_number: 1020200002465, combined_string: invention_title: 하이브리드 냉온풍 겸용 건조장치 abstract: 본 발명은 하이브리드 냉온풍 겸용 건조장치에 관한 것으로서, 제습기와, 제습기 후단에 열교환기를 설치하고, 이 열교환기 후단에 스팀온풍기를 설치하며, 스팀온풍기 후단에 냉각쿨러를 설치하고, 냉각쿨러에서 토출되는 공기를 공급받는 건조실를 형성하며, 건조실과 제습기 사이에 제1댐퍼를 형성하고, 건조실과 열교환기 사이에 제2댐퍼를 형성함으로써, 제습기에서 수분이 제거된 공기가 열교환기 및 스팀온풍기, 냉각쿨러로 순차 통과되면서 정해진 온도로 냉각 또는 가열된 후, 건조실 내로 공급되어 농산물을 고온의 열기 또는 냉기로 건조하되, 이 건조실 내의 열기 또는 냉기가 제1댐퍼 또는 제2댐퍼를 통해 열교환기를 가열한 후 배출되도록 하거나 혹은 제습기로 재공급된다.본 발명에 따르면, 열교환기, 스팀온풍기, 냉각쿨러의 작동을 제어하여, 건조실 내로 열풍을 공급하거나 또는 냉풍을 선택 공급할 수 있고, 이 열풍 또는 냉풍의 선택 공급으로 건조실 내에서 다양한 종류의 농산물을 건조할 수 있으며, 특히, 건조실 내에서 배출되는 공기중 일부를 건조실 내로 재 공급하되, 일부 공기는 외부로 배출하면서, 외부 공기를 재 공급받아 건조실 내의 공기 오염농도가 감소되고, 이 공기 오염농도가 감소된 공기를 농산물에 마찰시키면서, 농산물을 건조하여 농산물을 청결한 상태로 유지시킬 수 있다. claims: 공기를 공급받아 이 공기에 포함된 수분을 제거하는 제습기(100)와;상기 제습기(100) 후단에 설치되고, 상기 제습기(100)에서 토출되는 공기를 흡입하여, 이 공기를 가열하거나 또는 통과시키는 열교환기(200);상기 열교환기(200) 후단에 설치되고, 상기 열교환기(200)를 통과한 공기를 공급받아, 열풍건조시 이 공기를 가열하거나 또는 통과시키는 스팀온풍기(300);상기 스팀온풍기(300) 후단에 설치되고, 상기 스팀온풍기(300)에서 토출되는 공기를 공급받아, 냉풍건조시 이 공기를 냉각하거나 또는 통과시키는 냉각쿨러(400);중공형상으로, 상기 냉각쿨러(400)에서 토출되는 공기를 공급받고, 내부공간으로 공기를 순환시켜 내부에 수용된 농산물을 건조하는 건조실(500);상기 건조실(500)과 상기 제습기(100) 사이에 설치되고, 개폐작동되어 상기 건조실(500) 내의 공기가 냉풍건조시에는 상기 제습기(100)로 이동하는 것을 허용하고, 열풍건조시에는 차단하는 제1댐퍼(600);상기 건조실(500)과 상기 열교환기(200) 사이에 설치되고, 개폐작동되어 상기 건조실(500) 내의 공기가 열풍건조시에는 상기 열교환기(200)로 이동하는 것을 허용하고, 냉풍건조시에는 차단하는 제2댐퍼(700);로 구성되고,상기 건조실(500)은 내측 상부에 상기 냉각쿨러(400)에서 토출된 공기를 상기 건조실(500)의 양측방향으로 고르게 분산되도록 유도하는 유도관(504)과, 내측 벽면에 고정 설치되고, 회전작동되어 상기 건조실(500) 내의 공기를 순환시키는 순환팬(505)을 더 형성하며,상기 유도관(504)은 일단에 상기 냉각쿨러(400)의 공기를 공급받는 유입구(504a)와, 상기 유입구(504a)와 반대되는 타단에 양측으로 서로 대향되게 한 쌍으로 형성되어 상기 유입구(504a)를 통해 유입되는 공기를 상기 건조실(500) 내부 공간으로 토출하는 배출구(504b), 상기 배출구(504b) 내측 각각에 설치되고, 회전작동되어 한 쌍의 상기 배출구(504b)를 통해 상기 건조실(500) 내로 공기가 강제 배출되도록 하는 배기팬(504c)으로 구성되되,일단이 상기 배출구(504b)에 연결되고, 타단이 상기 건조실(500) 내부 공간을 향하도록 설치되며, 그 내측에 다단구조로 적층되되, 일단에서 타단으로 갈수록 그 사이의 틈새가 상대적으로 점차 넓어지는 복수개의 격자판(511)을 형성하여, 이 격자판(511) 사이의 틈새를 통해 공기가 건조실(500) 내로 분산 토출되도록 안내하는 풍향격자판(510)을 더 형성한 것을 특징으로 하는 하이브리드 냉온풍 겸용 건조장치., Ltext: 농업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

686/1150 Row 686: application_number: 1020190179260, combined_string: invention_title: 인공지능을 이용한 농산물 분류 장치 abstract: 본 발명은 농산물 분류 장치에 관한 것으로, 더욱 상세하게는 인공지능 기술을 이용하여 농산물의 등급을 자동적으로 판별해줄 수 있도록 하여 농업인들이 농산물을 분류하는 단순 반복노동으로부터 탈피할 수 있도록 해주는 인공지능을 이용한 농산물 분류 장치에 관한 것이다.또한, 본 발명에 따르면, 농산물을 이동시키는 컨베이어 벨트; 컨베이어 벨트 위에 있는 농산물을 촬영해서 촬영된 영상을 인공지능 분류기에 전송하는 카메라; 상기 카메라를 지지하는 지지대; 카메라로부터 전송받은 농산물 이미지를 기존 학습 데이터와 비교하여 등급을 판별하는 인공지능 분류기; 인공지능 분류기가 판별한 등급 정보를 수신하여 모터를 제어하여 농산물을 분류하도록 하는 모터 제어기; 모터제어기에 의해 제어되는 한쌍의 모터; 및 상기 한쌍의 모터의 회전에 따라 각각 회전하는 한쌍의 분류판를 포함하는 인공지능을 이용한 농산물 분류 장치가 제공된다.상기와 같은 본 발명에 따르면, 농업인들이 농산물을 분류하는 단순 반복노동으로부터 탈피할 수 있게 하며, 인건비를 절감할 수 있도록 한다. claims: 농산물을 이동시키는 컨베이어 벨트;컨베이어 벨트 위에 있는 농산물을 촬영해서 촬영된 영상을 인공지능 분류기에 전송하는 카메라; 상기 카메라를 지지하는 지지대; 카메라로부터 전송받은 농산물 이미지를 기존 학습 데이터와 비교하여 등급을 판별하는 인공지능 분류기; 인공지능 분류기가 판별한 등급 정보를 수신하여 모터를 제어하여 농산물을 분류하도록 하는 모터 제어기;모터제어기에 의해 제어되는 한쌍의 모터; 및상기 한쌍의 모터의 회전에 따라 각각 회전하는 한쌍의 분류판를 포함하는 인공지능을 이용한 농산물 분류 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

687/1150 Row 687: application_number: 1020190179880, combined_string: invention_title: 열풍 분배구조 장치 abstract: 우드칩 건조 장치의 열풍 분배구조.에 있어서, 우드칩 건조장치에 있어서, 열교환기에 의해 생성된 열풍이 건조부에 투입되는 열풍 투입구와, 건조부의 밑면에 구성되는 상기 열풍 투입구(13)로부터 투입된 열풍이 분배되도록 구성된 열풍분배 통로와, 열풍분배 통로(10)가 6개로 분할되도록 구성되는 열풍분리판과, 열풍분리판(12)에 1개 이상 구성되는 열풍통로관과, 열풍분배 통로(10)에 채워진 열풍이 건조부로 퍼져나갈 수 있도록 열풍분배통로 상부에 구성되는 루버타공 분리판재로 구성되어, 단순화된 구조로 건조부가 구성되므로 장치의 내구성 및 유지보수에 용이한 효과를 갖는다. claims: 우드칩 건조장치에 있어서, 열교환기에 의해 생성된 열풍이 건조부에 투입되는 열풍 투입구(13);건조부의 밑면에 구성되는 상기 열풍 투입구(13)로부터 투입된 열풍이 분배되도록 구성된 열풍분배 통로(10);상기 열풍분배 통로(10)가 6개로 분할되도록 구성되는 열풍분리판(12);상기 열풍분리판(12)에 1개 이상 구성되는 열풍통로관(12-1);상기 열풍분배 통로(10)에 채워진 열풍이 건조부로 퍼져나갈 수 있도록 열풍분배통로 상부에 구성되는 루버타공 분리판재(21)로 구성되는 것을 특징으로 하는 열풍 분배구조 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

688/1150 Row 688: application_number: 1020190171765, combined_string: invention_title: 스마트 팜 플랫폼 abstract: 상기 또는 다른 목적을 달성하기 위해 본 발명의 일 측면에 따른 스마트 팜 플랫폼은, 식물재배기로부터 수신한 정보 중에서 농산물의 상태 정보 및 상기 식물재배기의 동작 이력 정보에 기초하여 상기 농산물의 추천 판매 가격을 결정하고, 단말기는, 디스플레이에 상기 농산물의 상기 추천 판매 가격을 표시함으로써, 간편하게 농산물의 가격 결정 및 확인이 가능하다. claims: 농산물(agriculturl products)을 생산하는 식물재배기;상기 식물재배기로부터 상기 농산물 및 상기 식물재배기에 대한 정보를 수신하는 비즈니스 플랫폼; 및,상기 비즈니스 플랫폼에 접속하여, 상기 농산물과 관련된 소정 정보를 요청하고, 상기 요청에 대응하여 상기 비즈니스 플랫폼으로부터 수신되는 응답에 기초하는 화면을 디스플레이에 표시하는 단말기;를 포함하고,상기 비즈니스 플랫폼은, 상기 식물재배기로부터 수신한 정보 중에서 상기 농산물의 상태 정보 및 상기 식물재배기의 동작 이력 정보에 기초하여 상기 농산물의 추천 판매 가격을 결정하고,상기 단말기는, 상기 디스플레이에 상기 농산물의 상기 추천 판매 가격을 표시하는 것을 특징으로 하는 스마트 팜 플랫폼., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

689/1150 Row 689: application_number: 1020190168579, combined_string: invention_title: 글로벌 GAP 인증을 위한 농산물 관리 시스템 및 그 관리 방법 abstract: 본 발명은 글로벌 GAP 인증을 위한 농산물 관리 시스템 및 그 관리 방법에 관한 것으로, 글로벌 GAP를 적용한 농산물 관리 서비스를 제공함에 있어서 현장 관리 서버, 품질 관리 서버 및 생장 관리 서버를 구축하고 각 서버를 상호 연계함으로써 효과적이고 지속적인 농산물 품질관리가 가능하고, 또한 스마트 폰, 태블릿 PC와 같은 스마트기기를 사용하여 농산물 재배 현장에서 직접 글로벌 GAP와 관련된 모든 작업내용을 입력 및 관리할 수 있으며, 또한 농가 시설에 센서를 설치하여 USN에 의한 관리가 가능하도록 함으로써, 통제사항에 따른 상황 발생 시 SMS를 통해 관리자에게 통보하거나 혹은 자동으로 상황에 대응 및 조치할 수 있고, 생장 관리 데이터를 자동으로 수집하며 생산성 향상과 에너지 절감 등 농산물 생산 효율을 향상시킬 수 있는 글로벌 GAP 인증을 위한 농산물 관리 시스템 및 그 관리 방법에 관한 것이다. claims: 농가 현장에서 실시간으로 농산물에 대한 기록 정보를 입력받고, 필요한 정보를 확인할 수 있도록 하는 현장 관리 서버;글로벌 GAP에서 요구하는 각종 기록 정보에 대한 관리 및 농가별 정보 서비스를 제공하는 품질 관리 서버; 및USN 데이터 관리 시스템을 통해 농장의 농산물 생산성을 관리하는 생장 관리 서버;를 포함하며, 상기 현장 관리 서버, 품질 관리 서버 및 생장 관리 서버가 서로 인터랙션 하여 글로벌 GAP 인증 규격에 맞는 정보를 기록 및 관리하고 서비스할 수 있는 것을 특징으로 하는 글로벌 GAP 인증을 위한 농산물 관리 시스템.현장 관리 서버 및 생장 관리 서버를 통해 농가 현장 데이터가 입력되는 단계;품질 관리 서버를 통해 상기 입력된 농가 현장 데이터를 저장하고 농가 별로 관리하는 단계;농가 현장 데이터에 대한 글로벌 GAP 관련 분석 데이터를 전송 받아 관리하는 단계; 및 GAP 기준 정보, 농가별 기록 데이터, 분석 데이터, 농가별 통계 정보 또는 이들의 조합 중 적어도 하나 이상을 포함한 정보 서비스를 제공하는 단계;를 포함하며, 상기 현장 관리 서버, 품질 관리 서버 및 생장 관리 서버가 서로 인터랙션 하여 글로벌 GAP 인증 규격에 맞는 정보를 기록 및 관리하고 서비스할 수 있는 것을 특징으로 하는 글로벌 GAP 인증을 위한 농산물 관리 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

690/1150 Row 690: application_number: 2020190005051, combined_string: invention_title: 이산화염소수를 이용한 농,수산물 건조장치 abstract: 본 고안은 농업용 열풍건조기를 이용하여 농산물은 물론 30℃이상 온도가 올라가면 악취가 나면서 부패가 시작되어 농업용 열풍건조기로 건조가 불가능한 수산물을 건조시키는 데 있다. 방법은 기존의 열풍건조기 안에 간단하게 가습기를 부착하고 가습기 용액으로 물 대신에 살균,탈취효과가 뛰어난 식품첨가물로 허용된 30PPM미만의 이산화 염소수(ClO2)를 사용, 이를 분사시켜 쉽게 부패하기 쉬운 수산물을 건조시켜 저장기간을 늘리고 고부가가치화 하는 데 있다. claims: 열풍건조기 안에 가습기를 부착하는 단계. 이는 건조기 안에 할수도 있고 건조기바깥에 설치할 수 있다.제1항의 가습기안에 물 대신 가습기 용액으로 이산화염소수를 사용하는 단계, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

691/1150 Row 691: application_number: 1020190165218, combined_string: invention_title: 농산물 건조장치 및 건조장치에 의해 건조된 농산물 abstract: 본 발명은 수분이 많은 건조대상물을 건조시 상부 및 하부에서도 열풍을 조사하여 건조시간을 단축시킬수 있으며 다양한 형태로 건조가 가능하고 건조바구니를 자동으로 적재 이동할 수 있는 농산물 건조장치 및 건조장치에 의해 건조된 농산물에 관한 것으로, 더욱 더욱 상세하게는 케이스에 열풍홀을 형성하며, 건조대는 건조바구니를 직접 올리는 방식이나 열풍전환부를 설치하는 방식으로 구성하여; 수분이 가장 많이 모여지는 건조대상물의 하부 부분에 열풍을 조사하여 건조시간을 단축하도록 하는 효과가 있다. claims: 농작물, 수산물, 축산물, 의류, 한약재의 건조대상물을 건조하기 위하여, 개폐문(11)에 의해 개폐되는 개방부(12)와 연통되는 건조공간(13)에 다수 열풍으로 건조대(20)를 형성하는 케이스(10), 상기 케이스(10)의 상부에는 열풍을 발산하는 열풍부(30), 상기 케이스(10)의 상부에는 건조공간(13)에 건조시 발생하는 수증기와 냄새를 배기하는 배기구(41) 및 건조시 발생하는 수분을 배출하도록 케이스(10)의 바닥부에 형성하는 배출구(40), 상기 열풍부(30), 배출구(40)를 제어하는 제어부(50)로 이루어지는 건조장치에 있어서,상기 케이스(10)의 양 측벽에는 열풍부(30)의 열풍이 분사되는 열풍홀(14)을 형성하고,상기 건조대(20)에 결합되며 열풍홀(14)을 통해 열풍을 전달받아 열풍을 상부 방향으로 분사하며 건조대상물이 담겨지는 건조바구니(1)가 올려지는 열풍전환부(60)를 형성하여,상기 열풍부(30)의 열풍이 열풍전환부(60)를 통해 건조바구니(1)에 담겨진 건조대상물의 하부쪽으로 분사되어 건조시간을 단축할 수 있도록 구성하는 것을 특징으로 하는 농산물 건조장치.제 1항 내지 제 5항의 농산물 건조장치에 의해 건조된 농산물은 고사리, 고추, 콩, 버섯, 수산물, 약재 중 하나로 구성하는 것을 특징으로 하는 건조된 농산물., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

692/1150 Row 692: application_number: 1020190164445, combined_string: invention_title: 인공지능 농산물생산판매추천 시스템 및 그 방법 abstract: 본 발명은 인공지능 농산물생산판매추천 시스템 및 그 방법에 관한 것이다.사용자가 인공지능이 학습하여 추론한 농산물의 추천 지역과 예상 판매 단가 등을 알려주는 앱 인터페이스부와 인공지능이 학습할 빅데이터를 저장하는 저장부, 저장된 빅데이터를 학습하여 추론하는 인공지능부를 포함하는 인공지능 농산물생산판매추천 시스템이다. claims: 사용자가 인공지능이 학습하여 추론한 농산물의 추천 지역과 예상 판매 단가 등을 알려주는 앱 인터페이스부와 인공지능이 학습할 빅데이터를 저장하는 저장부, 저장된 빅데이터를 학습하여 추론하는 인공지능부를 포함하는 인공지능 농산물생산판매추천 시스템.경매를 위해 반입되는 농산물의 생산 이력 정보 입력수단, 및 상기 농산물의 영상 정보 입력수단을 제공하는 입력 수단 제공부;입력된 상기 농산물의 생산 이력 정보와 영상 정보를 저장하는 농산물 정보 저장부;미리 설정된 경매 시스템으로부터 상기 농산물에 대한 낙찰 정보를 전달받아 저장하는 유통 이력 정보 저장부;상기 농산물을 낙찰받은 1차 판매자의 오프라인점포 판매관리시스템에 상기 낙찰받은 농산물의 낙찰 정보를 전송하는 판매자 판매관리시스템 연동부;상기 1차 판매자의 온라인점포 운영시스템에 상기 1차 판매자의 온라인 점포에 대응하여 상기 낙찰받은 농산물을 등록하는 온라인점포 운영시스템 연동부; 및소비자 단말로부터 상기 1차 판매자의 온라인점포 운영시스템에 등록된 농산물이 선택되는 경우 상기 선택된 농산물의 생산 이력 정보, 영상 정보, 및 낙찰 정보를 제공하는 농산물 정보 제공부를 포함하는 농산물 거래 시스템으로서,상기 판매자 판매관리시스템 연동부는 상기 1차 판매자의 온라인 점포 운영 시스템을 통해 상기 농산물이 판매되는 경우, 상기 1차 판매자의 오프라인점포 판매관리시스템으로 상기 농산물의 판매 정보를 더 전송하고, 상기 온라인점포 운영시스템 연동부는 상기 1차 판매자의 오프라인점포 판매관리시스템에 상기 농산물의 판매정보가 입력되는 경우, 상기 온라인 점포 운영 시스템에 상기 판매 정보를 더 전송하며,상기 농산물의 생산 이력 정보는 상기 농산물상에 부착된 정보 저장 수단에 저장되고 상기 부착된 정보 저장 수단에 대응하는 정보 획득 장치에 의해 입력된 정보이고,상기 농산물의 영상 정보는 육안 식별 가능한 상기 정보 저장 수단의 영상 정보를 더 포함하는 것을 특징으로하는 인공지능 농산물생산판매추천 시스템.농산물 거래 시스템이, 경매를 위해 반입되는 농산물의 생산 이력 정보 입력수단, 및 상기 농산물의 영상 정보 입력수단을 제공하는 단계;입력된 상기 농산물의 생산 이력 정보와 영상 정보를 저장하는 단계;미리 설정된 경매 시스템으로부터 상기 농산물에 대한 낙찰 정보를 전달받아 저장하는 단계;상기 농산물을 낙찰받은 1차 판매자의 오프라인점포 판매관리시스템에 상기 낙찰받은 농산물의 낙찰 정보를 전송하는 단계;상기 1차 판매자의 온라인 점포 운영 시스템에 상기 1차 판매자의 온라인 점포에 대응하여 상기 낙찰받은 농산물을 등록하는 단계; 및소비자 단말로부터 상기 1차 판매자의 온라인 점포 운영 시스템에 등록된 농산물이 선택되는 경우 상기 선택된 농산물의 생산 이력 정보, 영상 정보, 및 낙찰 정보를 제공하는 단계를 포함하는 농산물 거래 방법으로서,상기 1차 판매자의 온라인 점포 운영 시스템을 통해 상기 농산물이 판매되는 경우, 상기 1차 판매자의 오프라인 점포 판매관리시스템으로 상기 농산물의 판매 정보를 전송하는 단계; 및상기 1차 판매자의 오프라인점포 판매관리시스템에 상기 농산물의 판매 정보가 입력되는 경우, 상기 온라인 점포 운영 시스템에 상기 판매 정보를 전송하는 단계를 더 포함하며,상기 농산물의 생산 이력 정보는 상기 농산물상에 부착된 정보 저장 수단에 저장되고 상기 부착된 정보 저장 수단에 대응하는 정보 획득 장치에 의해 입력된 정보이고,상기 농산물의 영상 정보는 육안 식별 가능한 상기 정보 저장 수단의 영상 정보를 더 포함하는 것을 특징으로 하는 인공지능 농산물생산판매추천방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

693/1150 Row 693: application_number: 1020190164192, combined_string: invention_title: 농산물용 신선도 유지 장치 및 농산물 가스 처리 방법 abstract: 본 발명은 농산물용 신선도 유지 장치 및 농산물 가스 처리 방법에 관한 것으로, 구체적으로 농산물의 미생물, 에틸렌 및 이산화탄소의 민감도에 따라 처리되는 가스를 조절하여 신선도를 유지하며, 농산물의 저장기간을 연장하는 농산물용 신선도 유지 장치 및 농산물 가스 처리 방법에 관한 것이다. claims: 농산물을 인입하고 이산화탄소, 이산화염소 및 에틸렌 분해제 중 하나 이상의 가스처리를 위한 농산물용 신선도 유지 장치에 있어서,내부에 농산물을 적재할 수 있는 공간이 형성된 본체부(10);상기 본체부(10)의 내부에 구비되며, 상기 가스 농도를 감지할 수 있는 센서를 구비하는 센싱부(20); 및상기 본체부(10)의 일측에 구비되며, 상기 센싱부(20)에 의해 감지된 상기 가스 농도에 따라 공급되는 가스의 양을 제어하는 컨트롤부(30);와본체부(10)의 일측에 구비되며, 외부에서 공급되는 상기 가스를 상기 본체부의 내부로 공급하기 위한 가스인입부(40)를 포함하는 것을 특징으로 하는 농산물용 신선도 유지 장치.청구항 1 내지 3 중 어느 한 항의 농산물용 신선도 유지 장치의 본체부(10) 내부에 농산물을 구비하는 단계(S10);상기 구비된 농산물의 품목에 따라 사용자가 컨트롤부(30)의 입력모듈에 농산물 품목을 입력하는 단계(S20);상기 정보처리모듈이 상기 입력된 농산물의 품목과 상기 정보저장모듈에 저장된 제1 정보를 비교하여 이산화탄소, 이산화염소, 에틸렌 분해제 및 이들의 조합으로 구성된 군으로부터 선택된 하나의 가스 중 공급될 가스를 결정하는 단계(S30);상기 본체부 내부로 상기 결정된 가스를 공급하는 단계(S40);상기 센싱부(20)에 감지된 농도에 따라 상기 가스공급을 중단하는 단계(S50);를 포함하는농산물 가스 처리 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

694/1150 Row 694: application_number: 1020190161717, combined_string: invention_title: 종자 코팅 조성물, 항공파종용 코팅 종자, 및 코팅 종자를 이용한 항공파종법 abstract: 본 발명의 일 실시에에 따르면, 장축과 단축을 갖는 타원구형의 종자; 상기 종자 상에 제공되는 코팅층을 포함하고, 상기 코팅층은 증량제 및 접착제를 포함하고, 상기 증량제는 탄산칼슘(CaCO3), 제오라이트(Zeolite), 고령토, 석고, 탈크(Talc)로 이루어진 군으로부터 선택되는 적어도 1종 이상의 물질을 포함하고, 상기 종자의 상기 단축 상에서의 상기 코팅층의 두께는 상기 종자의 상기 단축 상에서의 상기 코팅층의 두께보다 큰, 코팅 종자가 제공된다. claims: 장축과 단축을 갖는 타원구형의 종자;상기 종자 상에 제공되는 코팅층을 포함하고,상기 코팅층은 증량제 및 접착제를 포함하고,상기 증량제는 탄산칼슘(CaCO3), 제오라이트(Zeolite), 고령토, 석고, 탈크(Talc)로 이루어진 군으로부터 선택되는 적어도 1종 이상의 물질을 포함하고,상기 종자의 상기 단축 상에서의 상기 코팅층의 두께는 상기 종자의 상기 단축 상에서의 상기 코팅층의 두께보다 큰, 코팅 종자.비행체를 이용하여 경작지로부터 이격된 곳에서 코팅 종자를 살포하는 단계를 포함하고,상기 코팅 종자는 장축과 단축을 갖는 타원구형의 종자;상기 종자 상에 제공되는 코팅층을 포함하고,상기 코팅층은 증량제 및 접착제를 포함하고,상기 증량제는 탄산칼슘(CaCO3), 제오라이트(Zeolite), 고령토, 석고, 탈크(Talc)로 이루어진 군으로부터 선택되는 적어도 1종 이상의 물질을 포함하고,상기 코팅 종자의 무게는 상기 종자의 무게보다 큰, 항공파종 방법.증량제 및 접착제를 포함하고,상기 증량제는 탄산칼슘(CaCO3), 제오라이트(Zeolite), 고령토, 석고, 탈크(Talc)로 이루어진 군으로부터 선택되는 적어도 1종 이상의 물질을 포함하는, 종자 코팅 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

695/1150 Row 695: application_number: 1020190158861, combined_string: invention_title: 총체곡물 복합 처리장치 abstract: 본 발명의 실시 예에 따른 총체곡물 복합 처리장치는, 총체곡물을 예취하는 예취부와; 예취된 상기 총체곡물을 베일(bale)로 형성하는 베일링부와; 상기 베일을 비닐로 포장하는 래핑부와; 상기 예취부에 의해 예취된 총체곡물을 상기 베일링부로 이송하는 이송부와; 상기 예취부, 상기 베일링부, 상기 래핑부 및 상기 이송부를 지지하고, 주행하는 주행부를 포함한다. claims: 총체곡물을 예취하는 예취부;예취된 상기 총체곡물을 베일(bale)로 형성하는 베일링부;상기 베일을 비닐로 포장하는 래핑부; 및상기 예취부에 의해 예취된 총체곡물을 상기 베일링부로 이송하는 이송부를 포함하되,상기 베일링부는 상기 이송부에 의해 이송되는 총체곡물이 내부로 유입되는 유입구를 포함하고, 상기 이송부는 상기 예취부와 연결되는 제 1 이송 유닛과 상기 제 1 이송 유닛 및 상기 유입구에 연결되는 제 2 이송 유닛을 포함하는 총체곡물 복합 처리 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

696/1150 Row 696: application_number: 1020190156233, combined_string: invention_title: 식용곤충 분말, 질소고정세균, 황토 및 전분을 포함하는 종자 코팅제 및 상기 종자 코팅제로 코팅된 종자 abstract: 본 발명은 식용곤충 분말, 질소고정세균, 황토 및 전분을 포함하는 종자 코팅제 및 상기 종자 코팅제로 코팅된 종자에 관한 것으로, 본 발명의 식용곤충, 질소고정세균, 황토 및 전분을 포함하는 종자 코팅제를 이용하게 되면 종자 발아율 및 식물의 초장 길이가 현저하게 증가되고 파종 시 종자의 수분유지 및 유실방지 효과가 있을 뿐만 아니라, 종자 발아부터 유묘기까지 별도로 비료를 공급할 필요가 없으며, 화학 비료를 사용하지 않아 친환경농법으로 매우 유용하게 이용될 수 있다. claims: 식용곤충 분말, 질소고정세균 분말, 황토 및 전분을 포함하는 종자 코팅제. 제1항 내지 제5항 중 어느 한 항의 종자 코팅제로 코팅된 종자., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

697/1150 Row 697: application_number: 1020190154966, combined_string: invention_title: 곡물 건조 장치 및 곡물의 비린취 제거 방법 abstract: 본 발명은 밀폐 구조를 구비하며, 곡물을 수용하는 바디; 상기 바디 내부에 구비되어, 상기 바디 내에 수용된 곡물을 슬라이딩시키는 스크류 블레이드; 상기 바디를 가열하는 가열 수단; 및 상기 바디에 연결되어, 상기 바디 내부에 건열을 주입하는 폭기 수단을 포함하는 곡물 건조 장치, 및 이를 이용한 곡물의 비린취 제거 방법에 관한 것이다. claims: 밀폐 구조를 구비하며, 곡물을 수용하는 바디;상기 바디 내부에 구비되어, 상기 바디 내에 수용된 곡물을 슬라이딩시키는 스크류 블레이드;상기 바디를 가열하는 가열 수단; 및상기 바디에 연결되어, 상기 바디 내부에 건열을 주입하는 폭기 수단을 포함하는 곡물 건조 장치.곡물을 바디에 투입하는 곡물 투입 단계;상기 바디에 투입된 곡물을 스크류 블레이드를 이용하여 슬라이딩하는 슬라이딩 단계;상기 곡물에 광선을 조사하는 광선 조사 단계;상기 바디를 밀폐시켜 상기 바디 내부의 공기가 곡물들의 사이를 순환하도록 하는 열 순환 단계; 및상기 바디 내부에 건열을 주입하는 폭기 단계를 포함하는 곡물의 비린취 제거 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

698/1150 Row 698: application_number: 2020190004804, combined_string: invention_title: 슬라이스 형태로 절단된 농산물의 건조틀 abstract: 본 고안은 슬라이스 형태로 절단된 농산물이 서로 겹치지 않도록 수용하여 건조시키기 위한 슬라이스 형태로 절단된 농산물의 건조틀에 관한 것이다. 본 고안의 실시예에 따른 슬라이스 형태로 절단된 농산물의 건조틀은 내부에 농산물을 수용하는 수용공간이 형성되며 복수 개의 통기공이 관통형성된 외통, 상기 외통의 일부를 절개하여 상기 수용공간으로 농산물을 반입하는 반출입구, 상기 반출입구를 개폐하며 복수 개의 통기공이 관통형성된 개폐커버, 상기 수용공간을 복수 개로 분할하며, 분할된 각 수용공간마다 슬라이스 형태로 절단된 농산물을 세워 삽입하도록 상기 수용공간에 복수 개가 서로 이격되어 설치되는 분할격판, 및 상기 외통을 줄에 걸어 거치하도록 상기 외통에 설치되는 걸고리를 포함한다. 따라서, 건조공간을 최소화하고, 통기성을 확보할 수 있으며, 대량의 농산물을 용이하게 건조시킬 수 있는 이점이 있다. claims: 내부에 농산물을 수용하는 수용공간이 형성되며 복수 개의 통기공이 형성된 외통,상기 외통의 일부를 절개하여 상기 수용공간으로 농산물을 반입하는 반출입구,상기 반출입구를 개폐하며 복수 개의 통기공이 형성된 개폐커버,상기 수용공간을 복수 개로 분할하며, 분할된 각 수용공간마다 슬라이스 형태로 절단된 농산물을 세워 삽입하도록 상기 수용공간에 복수 개가 서로 이격되어 설치되는 분할격판, 및상기 외통을 줄에 걸어 거치하도록 상기 외통에 설치되는 걸고리를 포함하는 것을 슬라이스 형태로 절단된 농산물의 건조틀., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

699/1150 Row 699: application_number: 1020190154775, combined_string: invention_title: 전자기파를 이용한 태양초 고추건조기 abstract: 본 발명은 전자기파를 이용하여 고추의 색상을 보정할 수 있으며, 꼭지를 자동으로 분리시킬 수 있는 전자기파를 이용한 태양초 고추건조기에 관한 것이다. 본 발명의 실시예에 따른 전자기파를 이용한 태양초 고추건조기는 고추가 반입되는 건조실이 형성된 외장케이스, 상기 건조실을 개폐하도록 상기 외장케이스에 설치되는 개폐도어, 상기 개폐도어를 중심으로 상기 외장케이스의 양측면에 각각 설치되어 고추를 건조시키기 위한 전자기파를 상기 건조실의 내부로 방출하는 마그네트론, 상기 외장케이스의 하부에 설치되어 상기 건조실로 공기를 공급하는 송풍기, 상기 외장케이스의 상부에 설치되어 상기 송풍기에 의해 상기 건조실의 내부로 공급된 공기를 외부로 방출하는 배기구, 상기 건조실의 내부로 반입된 고추의 온도를 측정하는 온도측정기, 상기 건조실에 반입된 고추의 무게를 측정하고 상기 고추의 건조된 무게를 측정하는 저울부, 및 상기 온도측정기에서 측정되는 온도와 상기 저울부에서 측정되는 고추의 무게를 기초로 상기 마그네트론과 상기 송풍기를 제어하는 건조제어컨트롤러를 포함하고, 상기 건조제어컨트롤러는 상기 저울부에서 측정되는 고추의 변화된 무게를 기초로 상기 고추의 함수율을 측정하고, 상기 고추의 함수율이 50% 이상 55% 이하의 범위에 속하면, 상기 송풍기의 작동을 멈추고 상기 마그네트론를 작동시켜 상기 고추의 온도를 70℃ 이상 75℃ 이하의 범위에 이르도록 미리 설정된 시간동안 상기 고추를 급속가열하여 상기 고추의 갈변된 색상을 탈색하는 색상보정단계, 및 상기 고추의 함수율이 42% 이상 48% 이하의 범위에 속하면, 상기 송풍기의 작동을 멈추고 상기 마그네트론을 작동시켜 상기 고추의 온도를 75℃ 이상 80℃ 이하의 온도 범위에 이르도록 미리 설정된 시간동안 상기 고추를 급속가열하여 고추 내부의 수분을 급속히 팽창시키는 형태로 팽창력에 의해 상기 고추에서 고추꼭지를 분리하는 꼭지분리단계를 포함한다. 따라서, 마치 태양초와 같은 우수한 색상과 품질의 건 고추를 생산할 수 있다. claims: 고추가 반입되는 건조실이 형성된 외장케이스,상기 건조실을 개폐하도록 상기 외장케이스에 설치되는 개폐도어,상기 개폐도어를 중심으로 상기 외장케이스의 양측면에 각각 설치되어 고추를 건조시키기 위한 전자기파를 상기 건조실의 내부로 방출하는 마그네트론,상기 외장케이스의 하부에 설치되어 상기 건조실로 공기를 공급하는 송풍기,상기 외장케이스의 상부에 설치되어 상기 송풍기에 의해 상기 건조실의 내부로 공급된 공기를 외부로 방출하는 배기구,상기 건조실의 내부로 반입된 고추의 온도를 측정하는 온도측정기,상기 건조실에 반입된 고추의 무게를 측정하고 상기 고추의 건조된 무게를 측정하는 저울부,상기 온도측정기에서 측정되는 온도와 상기 저울부에서 측정되는 고추의 무게를 기초로 상기 마그네트론과 상기 송풍기를 제어하는 건조제어컨트롤러를 포함하고,상기 건조제어컨트롤러는상기 저울부에서 측정되는 고추의 변화된 무게를 기초로 상기 고추의 함수율을 측정하고, 상기 고추의 함수율이 50% 이상 55% 이하의 범위에 속하면, 상기 송풍기의 작동을 멈추고 상기 마그네트론를 작동시켜 상기 고추의 온도를 70℃ 이상 75℃ 이하의 범위에 이르도록 미리 설정된 시간동안 상기 고추를 급속가열하여 상기 고추의 갈변된 색상을 탈색하는 색상보정단계, 및상기 고추의 함수율이 42% 이상 48% 이하의 범위에 속하면, 상기 송풍기의 작동을 멈추고 상기 마그네트론을 작동시켜 상기 고추의 온도를 75℃ 이상 80℃ 이하의 온도 범위에 이르도록 미리 설정된 시간동안 상기 고추를 급속가열하여 고추 내부의 수분을 급속히 팽창시키는 형태로 팽창력에 의해 상기 고추에서 고추꼭지를 분리하는 꼭지분리단계를 포함하는 것을 특징으로 하는 전자기파를 이용한 태양초 고추건조기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

700/1150 Row 700: application_number: 1020190145847, combined_string: invention_title: 식물공장 설립과 농산물 판매를 위한 중개 서비스 장치 및 그 방법 abstract: 본 발명은 식물공장 설립과 농산물 판매를 위한 중개 서비스 장치 및 그 방법이 개시된다. 본 발명의 식물공장 설립과 농산물 판매를 위한 중개 서비스 장치는, 식물공장의 설립에 필요한 부지, 설비, 기자재 및 판매를 위한 농산물 중 적어도 하나를 등록하고, 식물공장의 설립을 위한 부지, 설비, 기자재 및 구매하기 위한 농산물 중 적어도 하나를 검색하여 구매하고 결제하는 사용자 단말기; 식물공장 설립 및 농산물 판매를 위한 정보를 저장하고, 주문정보와 회원정보를 저장하는 서비스 DB; 및 사용자 단말기를 통해 식물공장 설립과 농산물 판매를 위한 정보가 등록되면 서비스 DB에 저장하고, 사용자 단말기로부터 검색요청에 따라 서비스 DB에 저장된 정보를 검색하여 제공하며, 주문 결제가 요청되면 결제서버를 통해 결제를 수행한 후 주문 결제정보를 제공자에게 전달하여 용역 및 재화를 제공할 수 있도록 중개하는 중개서버;를 포함하는 것을 특징으로 한다. claims: 식물공장의 설립에 필요한 부지, 설비, 기자재 및 판매를 위한 농산물 중 적어도 하나를 등록하고, 상기 식물공장의 설립을 위한 부지, 설비, 기자재 및 구매하기 위한 농산물 중 적어도 하나를 검색하여 구매하고 결제하는 사용자 단말기; 상기 식물공장 설립 및 농산물 판매를 위한 정보를 저장하고, 주문정보와 회원정보를 저장하는 서비스 DB; 및 상기 사용자 단말기를 통해 상기 식물공장 설립과 농산물 판매를 위한 정보가 등록되면 상기 서비스 DB에 저장하고, 상기 사용자 단말기로부터 검색요청에 따라 상기 서비스 DB에 저장된 정보를 검색하여 제공하며, 주문 결제가 요청되면 결제서버를 통해 결제를 수행한 후 주문 결제정보를 제공자에게 전달하여 용역 및 재화를 제공할 수 있도록 중개하는 중개서버;를 포함하는 것을 특징으로 하는 식물공장 설립과 농산물 판매를 위한 중개 서비스 장치. 제 1항에 있어서, 상기 중개서버는, 상기 사용자 단말기를 통해 입력되는 상기 식물공장을 설립할 수 있는 부지의 임대 및 매매 정보를 상기 서비스 DB에 등록하고, 상기 사용자 단말기로부터 입력된 부지의 임대 및 매매를 위한 검색조건에 따라 매칭되는 정보를 검색하여 제공하는 부지 중개부; 상기 사용자 단말기를 통해 입력되는 상기 식물공장 설립과 운영을 위한 설비 및 기자재 정보를 상기 서비스 DB에 등록하고, 상기 사용자 단말기로부터 입력된 설비 및 기자재의 구매조건에 따라 매칭되는 정보를 검색하여 제공하는 설비 중개부; 상기 사용자 단말기를 통해 입력되는 상기 식물공장 설립과 운영을 위한 용역 정보를 상기 서비스 DB에 등록하고, 상기 사용자 단말기로부터 입력된 용역조건에 따라 매칭되는 정보를 검색하여 제공하는 용역 중개부; 상기 사용자 단말기를 통해 입력되는 상기 식물공장에서 생산된 농산물의 판매를 위해 상기 서비스 DB에 등록하고, 등록된 농산물을 제공하여 농산물을 구매할 수 있도록 중개하는 판매 중개부; 상기 사용자 단말기로부터 판매와 구매를 위한 주문정보를 입력받아 상기 서비스 DB에 등록하고, 상기 결제서버를 통해 결제를 수행하는 주문 결제부; 및 상기 사용자 단말기로부터 입력된 중개서비스를 이용하고자 하는 회원정보를 상기 서비스 DB에 등록하여 로그인 및 주문 결제를 관리하는 회원 관리부;를 포함하는 것을 특징으로 한다. 중개서버가 사용자 단말기로부터 입력되는 식물공장의 설립에 필요한 부지, 설비, 기자재 및 판매를 위한 농산물 중 적어도 하나를 입력받아 서비스 DB에 등록하는 단계; 상기 중개서버가 상기 사용자 단말기로부터 입력되는 상기 식물공장의 설립을 위한 부지, 설비, 기자재 및 구매하기 위한 농산물 중 적어도 하나를 상기 서비스 DB로부터 검색하여 제공하는 단계; 상기 중개서버가 검색 결과를 기반으로 상기 사용자 단말기로부터 주문정보가 입력되는 경우 상기 서비스 DB에 등록하고 결제서버를 통해 결제를 수행하는 단계; 및 상기 중개서버가 주문정보에 대한 결제를 수행하여 결제가 완료되면 주문 결제정보를 제공자에게 전달하는 단계;를 포함하는 것을 특징으로 하는 식물공장 설립과 농산물 판매를 위한 중개 서비스 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

701/1150 Row 701: application_number: 1020190139975, combined_string: invention_title: 플라즈마 가감압 종자 살균 장치 abstract: 플라즈마 방전을 이용하여 종자를 살균처리 하되 살균이 이루어지는 챔버 내부가 가압과 감압 상태로 제어되며 살균 효과를 극대화할 수 있는 플라즈마 종자 살균 장치가 개시된다. 본 발명에 의한 플라즈마 종자 살균 장치는, 내부에서 플라즈마가 발생되는 플라즈마 챔버; 상기 플라즈마 챔버에 연결되어 플라즈마가 공급되고, 내부에는 종자들이 내장되어 있으며 내부의 기압이 대기압 상태와 저진공 상태를 주기적으로 반복하게 되면서 종자가 살균되는 종자 살균 챔버; 상기 종자 살균 챔버에 연결되어 내부에 진공압을 제공하는 진공 펌프; 상기 플라즈마 챔버와 상기 종자 살균 챔버 사이에 설치되어 상기 종자 살균 챔버로 공급되는 플라즈마의 이동을 제어하는 플라즈마 공급 제어 밸브;를 포함한다. claims: 플라즈마가 발생되는 플라즈마 챔버;상기 플라즈마 챔버에 연결되어 플라즈마가 공급되고, 내부에는 종자들이 내장되어 있으며 내부가 가압 및 감압 상태로 제어되며 종자가 살균되는 종자 살균 챔버;상기 종자 살균 챔버에 연결되어 내부에 진공압을 제공하는 진공 펌프;상기 플라즈마 챔버와 상기 종자 살균 챔버 사이에 설치되어 상기 종자 살균 챔버로 공급되는 플라즈마의 이동을 제어하는 플라즈마 공급 제어 밸브;를 포함하는 플라즈마 종자 살균 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

702/1150 Row 702: application_number: 1020190140179, combined_string: invention_title: 중적외선과 히트펌프를 이용한 농산물 복합 건조장치 abstract: 본 발명에 따른 농산물 복합 건조장치는, 건조실에 배치되어 중적외선을 조사하는 중적외선 조사부, 건조실의 다습한 공기로부터 습기를 제거하여 일정 온도의 건조 공기가 되도록 처리하는 히트펌프부, 건조실의 내부에 배치되는 하나 이상의 덕트, 히트펌프부에서 처리된 일정 온도의 건조 공기를 덕트로 공급하는 하나 이상의 송풍팬, 및 중적외선 조사부와 히트펌프부를 제어하는 제어부를 포함하여 이루어진다. 중적외선과 히트펌프를 복합적으로 이용하여 농산물을 건조함에 따라, 아로니아와 미인고추 등 내외부를 균일하게 건조하기 어려운 농산물을 효율적으로 건조할 수 있다. 자연풍에 가까운 약 35도의 저온에서도 충분히 건조할 수 있어서, 원재료가 지닌 각종 효능이 건조 후에도 지속됨과 아울러 변질 또는 부패가 방지되어 저장성을 향상시킬 수 있다. 또한, 밀폐된 건조실의 내부 공기를 순환시켜 폐열을 재사용함으로써, 건조 효율 및 에너지 효율을 높일 수 있다. claims: 건조실의 농산물을 건조시키는 장치로서,상기 건조실에 배치되어 중적외선을 조사하는 중적외선 조사부;상기 건조실의 다습한 공기로부터 습기를 제거하여 일정 온도의 건조 공기가 되도록 처리하는 히트펌프부;상기 히트펌프부에서 처리된 일정 온도의 건조 공기를 상기 건조실의 내부로 공급하기 위하여, 상기 건조실의 천장 가운데 부분을 따라 서로 나란하게 상기 건조실의 중심 부근까지 연장되고, 상기 건조실의 바닥을 향해 건조 공기를 배출하는 한 쌍의 덕트;상기 건조실의 내부에서 습기를 머금은 다습한 공기를 상기 히트펌프부 측으로 보내기 위하여, 상기 건조실의 천장 양쪽 가장자리를 따라 서로 나란하게 연장되는 한 쌍의 덕트;상기 히트펌프부에서 처리된 일정 온도의 건조 공기가 상기 건조 공기를 배출하는 한 쌍의 덕트를 통해 흐르도록 하는 송풍팬과, 상기 건조실의 내부에서 습기를 머금은 다습한 공기가 상기 서로 나란하게 연장되는 한 쌍의 덕트를 통해 흐르도록 하는 송풍팬을 포함하는 복수의 송풍팬; 및상기 중적외선 조사부와 히트펌프부를 제어하는 제어부를 포함하고,상기 중적외선 조사부는 탄소 필라멘트로 이루어진 복수 개의 카본 램프를 포함하는, 중적외선과 히트펌프를 이용한 농산물 복합 건조장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

703/1150 Row 703: application_number: 1020190138331, combined_string: invention_title: 파종장치 abstract: 본 발명은 파종장치에 관한 것으로서, 베이스프레임 상에 고정 결합되는 호퍼형 몸체의 종자배출부 내에 위치하여 경사지게 안착 배치 및 회전 가능하게 지지 결합되는 종자배출판; 상기 종자배출판에 연결되어 시계방향 또는 반시계방향의 회전력을 제공하기 위한 회전유도수단; 상기 종자배출판의 상측에 위치하여 종자배출판으로 파종용 종자를 공급하여주는 호퍼형 구조의 종자공급통; 상기 종자배출부 내 상부 일측에 고정 결합된 고정브래킷 상에 일단부가 고정된 채로 종자배출판을 향해 볼록형 곡면 구조를 갖는 타단부가 종자배출판 측 어느 한 부분의 종자배출홀 상에 위치하도록 배치되어 종자배출판을 따라 회전 이송되는 종자를 누름 가압함에 의해 종자배출판의 종자배출홀 상에서 종자를 내보내는 역할을 하는 종자누름부재;를 포함하는 것을 특징으로 한다.본 발명에 따르면, 콩이나 팥 또는 서리태 등의 농작물 파종시 사용되는 종자의 크기 및 형상에 따라 종자배출판을 다양한 규격으로 제작하여 사용할 수 있고, 이를 통해 종자공급통으로부터 공급되는 종자에 대해 종자배출판 측 종자배출홀을 쉽게 통과하여 용이하게 파종 처리할 수 있으며 종자배출판에서의 종자 배출을 종래에 비해 보다 원활하게 수행할 수 있어 파종효율을 높일 수 있다. claims: 베이스프레임 상에 고정 결합되는 호퍼형 몸체의 종자배출부 내에 위치하여 경사지게 안착 배치 및 회전 가능하게 지지 결합되는 종자배출판;상기 종자배출판에 연결되어 시계방향 또는 반시계방향의 회전력을 제공하기 위한 회전유도수단;상기 종자배출판의 상측에 위치하여 종자배출판으로 파종용 종자를 공급하여주는 호퍼형 구조의 종자공급통;상기 종자배출부 내 상부 일측에 고정 결합된 고정브래킷 상에 일단부가 고정된 채로 종자배출판을 향해 볼록형 곡면 구조를 갖는 타단부가 종자배출판 측 어느 한 부분의 종자배출홀 상에 위치하도록 배치되어 종자배출판을 따라 회전 이송되는 종자를 누름 가압함에 의해 종자배출판의 종자배출홀 상에서 종자를 내보내는 역할을 하는 종자누름부재; 를 포함하되, 상기 종자누름부재는, 상기 종자배출판 측 종자배출홀에 대해 2열 배치구조로 형성하는 경우, 종자배출부에 고정 결합된 고정브래킷 상에 일단이 고정 결합된 채로 한쌍이 경사지게 분배되는 직선부 및 그 직선부 말단에 형성되어 종자배출홀에 위치하면서 종자를 누름 가압하는 호형부를 포함하는 누름부; 및 직선부가 관통되도록 2개의 간격홀을 갖는 간격유지구;를 포함함으로써, 간격유지구가 직선부 상에서 슬라이딩을 통해 간격이 조절되어 호형부가 종자배출홀 측 2열 배치구조의 간격에 대응하여 종자배출홀 상에 안착됨에 의해 종자가 누름 가압되어 종자배출판을 통과하면서 배출되는 것을 특징으로 하는 파종장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

704/1150 Row 704: application_number: 1020190137886, combined_string: invention_title: 농산물 살균 처리 플라즈마 시스템 및 방법 abstract: 농산물 살균 처리 플라즈마 시스템에 관하여 개시한다. 본 발명은, 농산물이 통과하는 임의의 한정된 공간을 형성하는 챔버; 상기 챔버의 베드를 구성하고 농산물이 챔버 안을 경유하도록 챔버의 내부를 가로지르도록 배치된 메인 컨베이어 벨트; 플라즈마 토치의 노즐 방향이 상기 메인 컨베이어 벨트의 상부에서 위치하면서 대면하는 방향을 향하도록 상기 챔버 내부 적소에 배치되는 플라즈마 발생기; 및 상기 챔버내에 생성되는 기체의 순환을 유도하기 위해 상기 챔버의 주변부에 배치된 배기후드;를 포함하여 구성될 수 있다. claims: 농산물이 통과하는 임의의 한정된 공간을 형성하는 챔버;상기 챔버의 베드를 구성하고 농산물이 챔버 안을 경유하도록 챔버의 내부를 가로지르도록 배치된 메인 컨베이어 벨트;플라즈마 토치의 노즐 방향이 상기 메인 컨베이어 벨트의 상부에서 위치하면서 대면하는 방향을 향하도록 상기 챔버 내부 적소에 배치되는 플라즈마 발생기; 및상기 챔버내에 생성되는 기체의 순환을 유도하기 위해 상기 챔버의 주변부에 배치된 배기후드;를 포함하는 농산물 살균 처리 플라즈마 시스템.농산물 선과장의 선과 라인 말단에 농산물 살균 처리 플라즈마 시스템을 배치하고, 선과된 농산물의 박스포장 뚜껑을 닫기 전 단계에서 상기 농산물 살균 처리 플라즈마 시스템을 구성하는 챔버의 컨베이어 벨트에 농산물이 담긴 박스포장 뚜껑이 열린 상태로 탑재하여 챔버 내에서 플라즈마 활성종으로 농산물을 살균 처리하는 단계;를 포함하는 농산물 살균 처리 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

705/1150 Row 705: application_number: 1020190135275, combined_string: invention_title: 농산물 생산 유통 관리 서버 및 이를 이용하는 농산물 생산 유통 관제 시스템 abstract: 본 발명의 일 실시예에 따른 농산물 생산 유통 관리 서버는, 재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어부; 재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장부; 저장DB로부터 수신한 재배지에서 재배되는 농산물 정보를 기초로 잔류 농약을 관리하는 잔류 농약 관리부; 및 출하된 농산물의 유통 환경을 관리하는 유통 환경 관리부를 포함하고, 잔류 농약 관리부는, 농약 잔류기준을 제공하는 농약 잔류기준 제공부와, 농약의 살포량을 저장하는 농약 살포량 저장부와, 농약의 잔류량에 따른 안전성을 판단하는 안전 적합도 판단부를 포함한다. claims: 재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어부;재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장부;저장DB로부터 수신한 상기 재배지에서 재배되는 농산물 정보를 기초로 잔류 농약을 관리하는 잔류 농약 관리부; 및출하된 농산물의 유통 환경을 관리하는 유통 환경 관리부를 포함하고,상기 잔류 농약 관리부는, 농약 잔류기준을 제공하는 농약 잔류기준 제공부와, 상기 농약의 살포량을 저장하는 농약 살포량 저장부와, 상기 농약의 잔류량에 따른 안전성을 판단하는 안전 적합도 판단부를 포함하는 농산물 생산 유통 관리 서버.농산물 유통 관리 서버;재배자 단말;구매자 단말; 및유통 차량을 포함하고,상기 농산물 유통 관리 서버는,재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어부;재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장부;저장DB로부터 수신한 상기 재배지에서 재배되는 농산물 정보를 기초로 잔류 농약을 관리하는 잔류 농약 관리부; 및출하된 농산물의 유통 환경을 관리하는 유통 환경 관리부를 포함하고,상기 잔류 농약 관리부는, 농약 잔류기준을 제공하는 농약 잔류기준 제공부와, 상기 농약의 살포량을 저장하는 농약 살포량 저장부와, 상기 농약의 잔류량에 따른 안전성을 판단하는 안전 적합도 판단부를 포함하는 농산물 생산 유통 관제 시스템.재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어 단계;재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장 단계;저장DB로부터 수신한 상기 재배지에서 재배되는 농산물 정보를 기초로 잔류 농약을 관리하는 잔류 농약 관리 단계; 및출하된 농산물의 유통 환경을 관리하는 유통 환경 관리 단계를 포함하고,상기 잔류 농약 관리 단계는, 농약 잔류기준을 제공하는 농약 잔류기준 제공부와, 상기 농약의 살포량을 저장하는 농약 살포량 저장부와, 상기 농약의 잔류량에 따른 안전성을 판단하는 안전 적합도 판단 단계를 포함하는 농산물 생산 유통 관제 방법.농산물 생산 유통 관제 방법을 실행하기 위한 프로그램을 포함하는 컴퓨터 판독가능 기록매체에 있어서,상기 농산물 생산 유통 관제 방법은, 재배지에 제공된 재배 환경 센서로부터 재배 환경 정보를 수신하여 재배 환경을 제어하는 재배 환경 제어 단계; 재배자 단말로부터 수신한 작업 일지 정보를 저장하는 작업 일지 저장 단계; 상기 재배지에서 재배되는 농산물의 잔류 농약을 관리하는 잔류 농약 관리 단계; 및 출하된 상기 농산물의 유통 환경을 관리하는 유통 환경 관리 단계를 포함하는 컴퓨터 판독가능 기록매체., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

706/1150 Row 706: application_number: 1020190127180, combined_string: invention_title: 표고버섯의 비타민 D2 함량 증강 방법 abstract: 본 발명은 표고버섯을 플라즈마로 전처리한 다음, 자외선을 조사함으로써, 표고버섯의 비타민 D2 함량이 현저히 증가된 처리 방법에 관한 것이다. claims: 챔버 내에 표고버섯 자실체를 넣고 플라즈마를 주입하는 플라즈마 전처리 단계와;상기 플라즈마 전처리된 표고버섯 자실체에 자외선을 조사하는 자외선 처리 단계;를 포함하며,상기 챔버 내의 플라즈마 농도는 0.1~1.0mg/L이고, 플라즈마 전처리 시간은 5~7분이며,상기 자외선은 250~320nm의 파장이고, 상기 자외선 처리 시간은 5~10분인 것을 특징으로 하는 표고버섯의 비타민 D2 함량 증강 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

707/1150 Row 707: application_number: 1020190124163, combined_string: invention_title: 농산물 신선도유지장치 abstract: 본 발명은 농산물 저장시설내 설치하여 작동시키면 플라즈마와 OH 라디컬으로 살균효과를 높혀서 대기중에 방출시킴으로 농산물의 노화 및 부패균으로부터 구근류, 과일류 및 엽채류와 같은 농산물을 안전하게 지켜주도록 팬작동, OH 라디컬 발생과 플라즈마발생을 이용한 농산물 신선도유지장치에 관한 것이다. 이를 위한 본 발명은 컨트롤박스(10)에는 AC 220 V 60Hz가 인가되는 전원스위치(70)와, 인터페이스 보드(16)를 통한 AC 팬(20), 플라즈마 발생기(30), OH 라디컬 발생기(40), LED 표시기(50) 및 옵션으로써의 통신포트(60)가 각각 설치되고; 상기 컨트롤박스(10)는 원칩마이컴(12)을 통해 전면디스플레이(14)와 인터페이스 보드(16)가 각기 연결되는 한편, 상기 전면디스플레이(14)에는 12 V 스위칭모드 파워서플라이(18)이 연결되도록 구성되어; 플라즈마의 1 차신선도 유지에 OH 라디컬의 공간 살균으로 상기 AC 팬(20), 플라즈마 발생기(30), OH 라디컬발생기(40)가 동작된 것을 특징으로 한다. claims: 컨트롤박스(10)에는 AC 220 V 60Hz가 인가되는 전원스위치(70)와, 인터페이스 보드(16)를 통한 AC 팬(20), 플라즈마 발생기(30), OH 라디컬발생기(40), LED 표시기(50) 및 별도의 통신포트(60)가 각각 설치되고; 상기 컨트롤박스(10)는 원칩마이컴(12)을 통해 전면디스플레이(14)와 인터페이스 보드(16)가 각기 연결되는 한편, 상기 전면디스플레이(14)에는 12 V 스위칭모드 파워서플라이(18)이 연결되도록 구성되어; 플라즈마의 1 차 신선도 유지에 OH 라디컬의 공간 살균으로 상기 AC 팬(20), 플라즈마 발생기(30), OH 라디컬 발생기(40)가 동작된 것을 특징으로 하는 농산물 신선도유지장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

708/1150 Row 708: application_number: 1020190115066, combined_string: invention_title: 종자 자동공급용 수동 파종기 abstract: 본 발명은 종자 자동공급용 수동 파종기에 관한 것으로, 특히, 파이프 형태로 된 지주관의 소정위치에 종자공급장치를 구비함과 동시에 상기 지주관 자체가 종자통으로 사용되게 하고, 한 쌍의 파종호미를 작동시키는 레버 및 작동봉이 상기 종자공급장치를 연동시킬 수 있게 하여 경운된 밭두둑에 파종호미를 찌른 상태에서 손잡이를 잡고 손아귀의 힘으로 레버를 함께 당기면 작동봉 또는 견인철선이 당겨지면서 종자공급장치와 파종호미를 동시에 연동시킴으로서, 지면에 형성된 파종홈 안에 작물의 종자가 자동 투입되게 하며, 더불어 상기 파종호미가 지면에 들어갈 때 스토퍼에 의해 균일한 깊이의 파종홈을 얻을 수 있게 함으로써 수동식 파종기이지만 균일한 깊이의 파종홈 형성과 함께 종자파종도 동시에 이루어지게 하려는데 그 특징이 있다.이와 같은 본 발명은 파종홈의 형성과 동시에 종자투입이 동시에 이루어지게 되는 것이며, 이에 따라 수동식 파종기이지만 종자투입은 자동으로 이루어질 수 있게 되어 파종효율을 극대화시킬 수 있고, 또, 지극히 구성이 간단하여 저렴하게 제조공급할 수 있어 농가의 부담을 경감시켜줄 수 있음은 물론 신속한 파종작업과 더불어 인력을 절감할 수 있는 등의 많은 효과가 따르는 것이다. claims: 상단에 뚜껑(11)과 손잡이(12)가 구비된 파이프 형태로 된 원통형의 종자통(1)과, 상기 종자통(1)의 하부에 장착되며 90° ~ 180° 로 회전하면서 종자통(1) 내부의 종자를 일정량, 또는 소정 개수만 파종호미(3)로 회전 이송시켜 낙하시키는 종자공급장치(2)와, 상기 종자공급장치(2)가 종자를 파종호미(3) 안으로 떨어뜨릴 때 통로로 작용하는 지지관(4)과, 상기 지지관(4)의 하단에 장착되어 일 측 또는 양 측으로 벌릴 수 있게 한 한 쌍의 파종호미(3)와, 상기 지지관(4)에 장착되어 나비볼트(7)로 높이를 조절할 수 있게 함으로써 손쉽게 파종홈의 깊이를 조절할 수 있게 한 스토퍼(6)와, 상기 파종호미(3)를 지면에 박은 상태에서 강제로 벌려 파종홈을 형성하면서 동시에 종자공급장치(2)도 회전시켜 종자를 파종홈에 투입시킬 수 있게 하는 스프링(52)이 장착된 견인부(5) 및 레버(51)로 이루어짐을 특징으로 하는 종자 자동공급용 수동파종기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

709/1150 Row 709: application_number: 1020190113156, combined_string: invention_title: 전자기파를 이용한 건조장치 abstract: 본 발명은 전자기파를 이용한 건조장치에 관한 것으로, 지면에 지지되는 작업대; 상기 작업대의 일측에 형성되며, 건조대상물이 안착되는 트레이와, 상기 트레이를 상승 또는 하강시키는 제1승강부가 형성되며 건조물을 이동시켜 건조부으로 공급하는 인입이송부; 상기 작업대에 형성되며, 상기 인입이송부가 이동하여 안착되며 상기 건조대상물을 전달받는 도킹부와, 도킹부를 상승 또는 하강시키는 제2승강부가 형성되며 상부에 건조로가 구비된 건조부; 상기 작업대의 타측에 형성되며, 상기 건조로에서 건조를 마친 건조물이 인계되어 안착되는 제2트레이와, 상기 제2트레이를 상승 또는 하강시키는 제3승강부가 형성되어 건조물을 배출하는 인출이송부;를 포함하여 구성된다. 이에 따르면, 액체나 수분을 함유하고 있는 각종 물질을 단시간 내에 대량 건조시킬 수 있는 건조로에 건조대상물을 투입하는 투입수단과, 건조를 마친 건조물을 인출하는 인출수단을 각기 구비하고, 각 투입수단과 인출수단은 높이 조절과 수평 이동이 자동으로 이루어질 수 있어 작업 능률이 향상될 수 있는 효과가 있다. claims: 지면에 지지되는 작업대;상기 작업대의 일측에 형성되며, 건조대상물이 안착되는 트레이와, 상기 트레이를 상승 또는 하강시키는 제1승강부가 형성되며 건조물을 이동시켜 건조부으로 공급하는 인입이송부; 상기 작업대에 형성되며, 상기 인입이송부가 이동하여 안착되며 상기 건조대상물을 전달받는 도킹부와, 도킹부를 상승 또는 하강시키는 제2승강부가 형성되며 상부에 건조로가 구비된 건조부;상기 작업대의 타측에 형성되며, 상기 건조로에서 건조를 마친 건조물이 인계되어 안착되는 제2트레이와, 상기 제2트레이를 상승 또는 하강시키는 제3승강부가 형성되어 건조물을 배출하는 인출이송부;를 포함하는 것을 특징으로 하는 전자기파를 이용한 건조장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

710/1150 Row 710: application_number: 1020190110919, combined_string: invention_title: 분체 건조 방법 및 분체 건조 설비 abstract: 본 발명은 건조 대상물인 분체를 골고루 균등하게 건조시킬 수 있어 균일한 건조 품질을 제공하면서도 건조량을 증대시킬 수 있고, 건조 대상물이 이송 벨트에 고착될 일이 없어 설비의 유지 관리성을 향상시킬 수 있으며, 나아가 건조되는 분체의 함수율을 용이하게 조정할 수 있는 적용 분야에 맞는 최적의 건조 분체를 제공할 수 있는 분체 건조 방법 및 분체 건조 설비에 관한 것이다. 본 발명에 따르면, 건조 대상물인 분체를 투입하는 건조대상물 투입 단계; 상기 투입되는 건조 대상물을 하기 건조대상물 이송 단계로 공급하는 건조대상물 공급 단계; 상기 건조대상물을 컨베이어 벨트의 상면에서 이송시키는 건조대상물 이송 단계; 상기 컨베이어 벨트 상에서 이송되는 건조대상물을 건조시키는 건조대상물 건조 단계; 및 건조된 건조 분체를 외부로 배출하는 건조물 배출 단계;를 포함하며, 상기 건조대상물 이송 단계는 건조대상물을 컨베이어 벨트에서 이동시키면서 건조대상물이 뒤집어엎어지도록 이루어지는 것을 특징으로 하는 분체 건조 방법 및 분체 건조 설비가 제공된다. claims: 건조 대상물인 분체를 투입하는 건조대상물 투입 단계;상기 투입되는 건조 대상물을 하기 건조대상물 이송 단계로 공급하는 건조대상물 공급 단계;상기 건조대상물을 컨베이어 벨트의 상면에서 이송시키는 건조대상물 이송 단계;상기 컨베이어 벨트 상에서 이송되는 건조대상물을 건조시키는 건조대상물 건조 단계; 및건조된 건조 분체를 외부로 배출하는 건조물 배출 단계;를 포함하며,상기 건조대상물 이송 단계는 건조대상물을 컨베이어 벨트에서 이동시키면서 건조대상물이 뒤집어엎어지도록 이루어지는 것을 특징으로 하는분체 건조 방법.함수(含水) 분체를 포함하는 건조대상물을 건조시키기 위한 설비로서,일측 상부에 투입 호퍼가 구비되고 타측 단부에 배출구가 구비되는 설비 바디부;상기 투입 호퍼에서 투입되는 건조대상물을 타측으로 이송시키도록 구성되는 분체 이송 장치부;상기 분체 이송 장치부에 의해 이송되는 건조대상물을 건조시키도록 구성되는 분체 건조 장치부;상기 분체 이송 장치부에 의해 이송되는 과정에서 건조대상물을 뒤집어엎도록 구성되는 교반 써레 수단; 및상기 분체 이송 장치부와 분체 건조 장치부의 동작을 제어하기 위한 제어반;을 포함하는 것을 특징으로 하는분체 건조 설비., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

711/1150 Row 711: application_number: 1020190110797, combined_string: invention_title: 농산물 가공 유통 시스템 및 방법 abstract: 본 발명은 산지에서 직접 매입한 배추, 시금치, 상추, 감자, 고구마, 양파, 당근, 오이, 단호박, 양상추, 브로콜리 등과 같은 모든 종류의 농산물을 소비자의 주문에 따라 선택하여 슬라이스나 다이스로 잘라서 포장한 후 택배를 통해 소비자에게 배송할 수 있도록 하는 농산물 가공 유통 시스템 및 방법이 개시된다.개시된 농산물 유통 서버는, 하나 이상의 작업장에 각각 배치된 RFID 리더기와, 세척기, 컨베이어, 슬라이서, 포장기, 바코드 리더기 및 스마트폰과 연동하는 통신부; 상기 농산물의 입고 정보와 제품 주문 정보 및 통신 주문 정보를 저장하거나, 상기 농산물의 입고량과 재고량, 분류 데이터, 제품 정보를 저장하며, 상기 농산물의 판매 정보, 고객 정보, 작업자 정보를 저장하고 있는 DB; 및 상기 농산물의 판매 데이터에 근거해 각 제품 별로 원가와 판매가를 이용해 일정 기간의 마진율과 영업이익률을 산출해 제품명에 매칭시키고, 그 기간 중 다른 값들에 비해 일정 이상으로 차이가 나는 기간에 대해 주요 요인을 입력받아 학습하며, 학습된 데이터를 모델링하여 판매 모델을 생성하며, 상기 판매 모델에 새로운 농산물 정보를 입력하여 마진율과 영업이익률을 예측 산출하는, 마이크로 프로세서를 포함한다. claims: 농산물 가공 유통 앱(Application)을 통해 입고 농산물의 정보를 입력받거나 주문된 제품 주문 정보를 입력받는 스마트폰;통신망으로부터 수신된 통신 주문 정보와 상기 제품 주문 정보에 따라 작업 전표를 발행하여 농산물의 가공 및 유통을 제어하는 농산물 유통 서버;상기 작업 전표에 따라 선택 투입된 농산물을 세척하는 세척기;상기 세척된 농산물을 이동시키는 컨베이어;상기 이동된 농산물을 슬라이스 또는 다이스로 자르는 슬라이서;상기 슬라이서에 의해 잘라진 농산물을 박스 또는 포장지로 포장하고, 상기 박스 또는 포장지에 바코드를 부착하는 포장기; 상기 포장된 농산물의 배송 시 상기 바코드를 리딩하는 바코드 리더기;상기 포장된 농산물의 이상 상태를 검사하는 X-ray기; 및상기 포장된 농산물에 금속이 포함되어 있는지 검사하는 금속 검출기;를 포함하고,상기 농산물 유통 서버는 상기 통신 주문 정보 및 상기 제품 주문 정보에 따른 판매 데이터에 근거해 각 제품 별로 원가와 판매가를 이용해 일정 기간 마진율과 영업이익률을 산출해 제품명에 매칭시키고, 그 기간 중 다른 값들에 비해 일정 이상으로 차이가 나는 기간에 대해 주요 요인을 입력받아 학습하며, 학습한 데이터를 모델링하여 판매 모델을 생성하며, 상기 판매 모델에 새로운 농산물 정보를 입력하여 마진율과 영업이익률을 예측 산출하며,상기 농산물 가공 유통 앱을 통해 상기 슬라이스의 크기가 선택되는 경우, 상기 농산물 가공 유통 앱이 상기 슬라이스의 크기에 따라 해당 농산물의 생산량을 예측하여 화면상으로 표시시키고, 상기 작업 전표에 따라 배정된 각 작업자에 대응된 RFID 신호를 송출하는 복수의 RFID 태그(Tag);를 더 포함하고,상기 농산물 유통 서버는 상기 세척기와 상기 컨베이어, 상기 슬라이서, 상기 포장기 및 상기 바코드 리더기와 유선 네트워크 또는 무선 네트워크를 통해 연동하며,상기 세척기는 제1 작업장에 배치되고 상기 제1 작업장에는 상기 세척기에 매칭된 제1 RFID 리더기가 설치되며,상기 컨베이어는 제2 작업장에 배치되고 상기 제2 작업장에는 상기 컨베이어에 매칭된 제2 RFID 리더기가 설치되며,상기 슬라이서는 제3 작업장에 배치되고 상기 제3 작업장에는 상기 슬라이서에 매칭된 제3 RFID 리더기가 설치되며,상기 포장기는 제4 작업장에 배치되고 상기 제4 작업장에는 상기 포장기에 매칭된 제4 RFID 리더기가 설치되며,상기 바코드 리더기는 제5 작업장에 배치되고 상기 제5 작업장에는 상기 바코드 리더기에 매칭된 제5 RFID 리더기가 설치되며,상기 X-ray기 및 상기 금속 검출기는 상기 제4 작업장 또는 상기 제5 작업장에 배치되며, 상기 제1 내지 제5 RFID 리더기는 각 작업장에 위치해 있는 적어도 하나 이상의 RFID 태그로부터 RFID 신호를 수신하면, 자신의 관할 작업장에서 인식된 RFID 및 시간 데이터를 포함하는 작업장 정보를 상기 농산물 유통 서버로 전송하고,상기 농산물 유통 서버는 상기 제1 내지 제5 RFID 리더기로부터 수신된 작업장 정보에 근거해 각 작업장에 위치해 있는 RFID와 시간 데이터를 인식하여 각 작업장 별 작업 현황을 화면 상에 또는 음성으로 출력하며,상기 농산물 유통 서버는,적어도 하나 이상의 작업장에 각각 배치된 적어도 하나 이상의 RFID 리더기와 상기 세척기, 상기 컨베이어, 상기 슬라이서, 상기 포장기, 상기 바코드 리더기 및 상기 스마트폰과 유선 네트워크 또는 무선 네트워크를 통해 연동하는 통신부;상기 스마트폰의 농산물 가공유통 앱(Application)을 통해 입력받은 농산물의 입고 정보와 제품 주문 정보를 저장하거나, 상기 통신부를 통해 외부로부터 수신된 통신 주문 정보를 저장하거나, 상기 농산물의 입고량과 재고량, 분류 데이터, 제품 정보를 저장하거나, 각 작업장에 배치된 하나 이상의 RFID 리더기 정보와 하나 이상의 RFID 태그 정보를 저장하며, 상기 농산물의 메뉴 정보와 판매 정보, 고객 정보, 작업자 정보를 저장하고 있는 데이터베이스; 및상기 통신 주문 정보 및 상기 제품 주문 정보에 따른 판매 데이터에 근거해 각 제품 별로 원가와 판매가를 이용해 일정 기간의 마진율과 영업이익률을 산출해 제품명에 매칭시키고, 그 기간 중 다른 값들에 비해 일정 이상으로 차이가 나는 기간에 대해 주요 요인을 입력받아 학습하며, 학습된 데이터를 모델링하여 판매 모델을 생성하며, 상기 판매 모델에 새로운 농산물 정보를 입력하여 마진율과 영업이익률을 예측 산출하는, 마이크로 프로세서를 포함하고,상기 마이크로 프로세서는, 상기 판매 데이터에 근거해 각 제품 별로 원가와 판매가를 이용해 일정 기간의 마진율과 영업이익률을 산출해 제품명에 매칭시켜 학습 데이터로 상기 데이터 베이스에 저장하고, 상기 학습 데이터에 대해 모델링하여 모델을 생성하기 위한 모델링 데이터군과, 생성한 모델을 검증하기 위한 검증 데이터군으로 분류하며, 상기 모델링 데이터군에 대해 상기 제품명 별로 마진율과 영업이익률을 학습하여 상기 마진율과 상기 영업이익률 간의 관계를 나타내는 추정 함수식(E(x))을 산출하며,상기 제품명 별 각 영업이익률 데이터와 상기 추정 함수식의 그래프에 해당하는 추정 데이터들 간의 거리값들을 각각 산출하여, 산출된 각 거리값들을 모두 합하여 상기 제품명 수에 따른 데이터 개수로 나누어, 산출된 거리값들 중 최소가 되고 상기 추정 함수식의 그래프에 가장 근접하는 마진율과 영업이익률을 가지는 함수식의 기울기(a) 값과 절편(b) 값을 산출하며,산출된 기울기(a) 값과 절편(b) 값을 상기 추정 함수식에 대입해 판매 함수식(y=ax+b)을 결정하여, 마진율에 따른 영업이익률을 산출하기 위한 상기 판매 모델을 생성하며, 상기 제품명 별로 산출한 각 마진율(x)을 상기 판매 모델에 각각 대입하여 상기 제품명 별로 영업이익률(y)을 산출하고, 상기 제품명 별로 영업이익률(y)과 수수료 데이터를 비교하여 내림차순으로 리스팅(listing)하며,상기 마이크로 프로세서는, 상기 검증 데이터군에 대해 상기 제품명 별로 각각의 마진율(x)을 산출하고, 산출된 각 마진율(x)을 상기 판매 모델에 대입해 영업이익률(y)을 각각 산출하며, 상기 제품명 별로 산출된 각각의 마진율(x) 및 영업이익률(y)에 대해 상기 추정 함수식의 그래프와의 거리값들을 산출하며,상기 산출된 거리값들에 대한 거리 평균값을 산출하고, 산출된 거리 평균값을 상기 마진율(x)과 상기 영업이익률(y) 간의 관계에서 최소가 되는 거리값과 비교해, 상기 산출된 거리 평균값과 상기 최소가 되는 거리값의 차이가 오차 범위 이내인가의 여부에 따라 상기 판매 모델을 검증하며,상기 마이크로 프로세서는, 상기 각 제품 별로 원가와 판매가를 이용해 산출한 마진율과 영업이익률을 제품명에 매칭시키고, 매칭된 제품명에 제품 종류와 제품 성격, 시장 규모를 대응시켜 상기 데이터베이스에 저장하며, 상기 제품 성격은 근채류, 과채류, 양채류 및 기타류를 포함하고, 상기 시장 규모는 이용자가 10만명 미만인 소규모 시장과, 이용자가 10만명 이상 100만명 미만인 중규모 시장, 이용자가 100만명 이상인 대규모 시장을 포함하며,상기 마이크로 프로세서는, 상기 모델링 데이터군을 상기 제품성격에 따라 근채류, 과채류, 양채류 및 기타류의 4가지 분야로 재분류하고, 상기 재분류된 각각의 모델링 데이터군에 대해 상기 제품명 별로 마진율(x), 영업이익률(y)을 학습하여, 상기 마진율(x)과 상기 영업이익률(y) 간의 관계를 나타내는 추정 함수식(E(x))을 상기 제품성격의 4가지 분야 별로 각각 산출하고,상기 마이크로프로세서는 상기 제품성격의 4가지 분야 별로 상기 제품명 별 각 영업이익률(y) 데이터와, 상기 추정 함수식(E(x))의 그래프에 해당하는 추정 데이터들 간의 거리값([E(x)-y(x)]2)들을 각각 산출하고, 각각 산출된 거리값들을 모두 합하여 상기 제품명 수에 따른 데이터 개수(m)로 나누어, 상기 산출된 거리값들 중 최소가 되고 상기 추정 함수식의 그래프에 가장 근접하는 마진율(x)과 영업이익률(y)을 가지는 함수식의 기울기(a) 값과 절편(b) 값을 상기 제품성격의 4 가지 분야에 따라 각각 산출하며,상기 마이크로프로세서는 상기 제품성격의 4가지 분야에 따라 산출된 기울기(a) 값과 절편(b) 값을 상기 제품성격의 4가지 분야 별로 상기 추정 함수식에 대입해 판매 함수식(y=ax+b)을 결정하여, 마진율에 따른 영업이익률을 산출하는 판매 모델을 상기 제품성격의 근채류, 과채류, 양채류 및 기타류에 따라 각각 생성하며,상기 마이크로프로세서는 상기 모델링 데이터군을 상기 시장규모에 따라 소규모 시장, 중규모 시장, 대규모 시장의 3 가지 분야로 재분류하고, 상기 재분류된 각각의 모델링 데이터군에 대해, 상기 제품명 별로 마진율(x), 영업이익률(y)을 학습하여, 상기 마진율(x)과 상기 영업이익률(y) 간의 관계를 나타내는 추정 함수식(E(x))을 상기 시장규모의 3가지 분야 별로 각각 산출하고,상기 마이크로프로세서는 상기 시장규모의 3가지 분야 별로 상기 제품명 별 각 영업이익률(y) 데이터와, 상기 추정 함수식(E(x))의 그래프에 해당하는 추정 데이터들 간의 거리값([E(x)-y(x)]2)들을 각각 산출하고, 각각 산출된 거리값들을 모두 합하여 상기 제품명 수에 따른 데이터 개수(m)로 나누어, 상기 산출된 거리값들 중 최소가 되고 상기 추정 함수식의 그래프에 가장 근접하는 마진율(x)과 영업이익률(y)을 가지는 함수식의 기울기(a) 값과 절편(b) 값을 상기 시장규모의 3 가지 분야에 따라 각각 산출하며,상기 마이크로프로세서는 상기 시장규모의 3가지 분야에 따라 산출된 기울기(a) 값과 절편(b) 값을 상기 시장규모의 3가지 분야 별 추정 함수식에 각각 대입해 판매 함수식(y=ax+b)을 각각 결정하여, 마진율에 따른 영업이익률을 산출하는 판매 모델을 상기 시장규모의 소규모 시장, 중규모 시장, 대규모 시장에 따라 3 가지 분야 별로 각각 생성하는농산물 유통 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

712/1150 Row 712: application_number: 1020190108424, combined_string: invention_title: 종자의 표면 처리 방법 abstract: 본 발명은 종자의 표면 처리 방법에 관한 것이다.구체적으로, 본 발명의 일 구현예에서는, 농산물의 생산성을 높이는 방법 중 하나로, 종자의 표면에 플라즈마를 조사하는 제1 단계; 및 화학적 처리, 건열 처리, 또는 이들을 조합한 처리 방법으로, 상기 제1 단계가 완료된 종자를 처리하는 제2 단계;를 포함하는, 종자의 표면 처리 방법을 제공한다. claims: 종자의 표면에 플라즈마를 조사하는, 플라즈마 처리 단계; 및 상기 플라즈마 처리된 종자의 표면을 살균 소독액으로 처리하는, 화학적 처리 단계;를 포함하는,종자의 표면 처리 방법.종자의 표면에 플라즈마를 조사하는, 플라즈마 처리 단계; 및 상기 플라즈마 처리된 종자의 표면을 건열 처리하는, 건열 처리 단계;를 포함하는,종자의 표면 처리 방법.종자의 표면에 플라즈마를 조사하는, 플라즈마 처리 단계; 상기 플라즈마 처리된 종자의 표면을 살균 소독액으로 처리하는, 화학적 처리 단계; 및 상기 화학적 처리된 종자의 표면을 건열 처리하는, 건열 처리 단계;를 포함하는,종자의 표면 처리 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

713/1150 Row 713: application_number: 1020190106870, combined_string: invention_title: 딥러닝 기반 농산물 물동량 분배 의사결정 지원 시스템 abstract: 본 발명은 각 도매시장에서의 과거의 수요량과 가격 데이터와, 그 때의 농산물의 재고량, 기후 정보, 프로모션 정보 등을 신경망 또는 딥러닝으로 학습하여, 농산물의 수요량 및 가격을 예측하는, 딥러닝 기반 농산물 물동량 분배 의사결정 지원 시스템에 관한 것으로서, 지역에 기초한 농산물 물동량 관련 정보에 대한 기초 데이터 또는 각 도매시장의 물동량 데이터를 수집하는 기초데이터 수집부; 도매시장과 농산물 종류의 조합 별로 신경망 모델(이하 조합별 신경망 모델)을 설정하는 모델 설정부; 행정구역의 지역으로 구분된 지형 지도를 2차원 사각형의 정규 지도로 매핑하여, 행정구역의 지역에 대한 정규 지도의 지도 상의 지역 영역의 매핑 관계를 설정하는 정규매핑 설정부; 지역에 대한 정규 지도의 매핑 관계를 이용하여, 각 기초 데이터로부터 2차원 이미지의 디스크립터를 산출하는 디스크립터 추출부; 과거 날짜의 농산물 종류별 기초 데이터의 디스크립터(이하 농산물 종류별 디스크립터)에, 도매시장별 물동량 데이터를 라벨 값으로 라벨링하여 조합별 학습 데이터를 생성하고, 생성된 조합별 학습 데이터로 조합별 신경망 모델을 학습시키는 모델 학습부; 조합별 신경망 모델을 이용하여 해당 조합의 농산물 종류 및 도매시장에 대한 농산물 물동량을 예측하는 물동량 예측부를 포함하는 구성을 마련한다.상기와 같은 시스템에 의하여, 농산물의 재고량, 기후 정보, 프로모션 정보 등 특성 정보를 함께 딥러닝으로 학습함으로써, 농산물의 수요량 및 가격을 보다 정확한 예측할 수 있다. claims: 딥러닝 기반 농산물 물동량 분배 의사결정 지원 시스템에 있어서,지역에 기초한 농산물 물동량 관련 정보에 대한 기초 데이터 또는 각 도매시장의 물동량 데이터를 수집하는 기초데이터 수집부;도매시장과 농산물 종류의 조합 별로 신경망 모델(이하 조합별 신경망 모델)을 설정하는 모델 설정부;행정구역의 지역으로 구분된 지형 지도를 2차원 사각형의 정규 지도로 매핑하여, 행정구역의 지역에 대한 정규 지도의 지도 상의 지역 영역의 매핑 관계를 설정하는 정규매핑 설정부;지역에 대한 정규 지도의 매핑 관계를 이용하여, 각 기초 데이터로부터 2차원 이미지의 디스크립터를 산출하는 디스크립터 추출부;과거 날짜의 농산물 종류별 기초 데이터의 디스크립터(이하 농산물 종류별 디스크립터)에, 도매시장별 물동량 데이터를 라벨 값으로 라벨링하여 조합별 학습 데이터를 생성하고, 생성된 조합별 학습 데이터로 조합별 신경망 모델을 학습시키는 모델 학습부;조합별 신경망 모델을 이용하여 해당 조합의 농산물 종류 및 도매시장에 대한 농산물 물동량을 예측하는 물동량 예측부를 포함하는 것을 특징으로 하는 딥러닝 기반 농산물 물동량 분배 의사결정 지원 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

714/1150 Row 714: application_number: 1020190104879, combined_string: invention_title: 농산물의 신선도 유지에 도움을 주는 투명필름 제조방법 abstract: 독거세대가 늘어나는 추세에 따라 농산물의 포장도 소포장화가 주를 이루고 있는데 이와같은 흐름에 발맞춰 소포장된 농산물이 통기성좋은 비닐과 보습효과를 주는 젤패드와 함께 포장되어 유통이 될 경우 똑같이 냉장고에 보관되어도 기존의 방식보다는 최소 두배이상 오래 신선도를 유지할 수 있게 하는 제품이다. claims: 다연장 비닐포장지에 엑시머레이저기계를 이용하여 미세한 구멍을 연속적으로 천공하는 방법;천공한 비닐을 원형으로 감을때 천공구멍이 겹치지 않도록 간격을 조절하는 패턴 디자인, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

715/1150 Row 715: application_number: 1020190104886, combined_string: invention_title: 농산물의 신선도 유지에 도움을 주는 젤리패드의 제조방법 abstract: 흔히 고기류 제품을 구입할때 빠지는 핏물을 흡수할 수 있도록 흡습패드를 포장지 아래에 깔아주는 경우는 많았으나, 농산물의 장기보존을 위해 반대로 습도를 유지시켜주기 위해 아이스팩의 소재인 수분젤리를 이용해서 습포제 안에 넣어 비닐로 소분 포장된 비닐의 내부 습도를 유지시켜 더욱 오랫동안 신선하게 보존하게 할 수 있는 방법이다. claims: 습기를 천천히 누출하는 펠트지에 수분을 머금은 젤리형태의 재료를 담는방법;습포제에 젤리패드를 넣고 투입구 봉합시 일정 간격으로 미세구멍을 뚫어 습도가 잘 유지될 수 있도록 포장하는 방법, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

716/1150 Row 716: application_number: 1020190103090, combined_string: invention_title: 황토를 이용한 건조장 abstract: 본 발명은 건조대상물이 수용된 트레이가 상하로 다단 적층된 제3 유닛이 도어를 통하여 제1 유닛의 내부로 투입되고, 제2 유닛은 제1 유닛의 내부공기를 강제 대류시키면서 건조대상물을 건조시키되, 제1 유닛의 투명 또는 반투명한 지붕을 통하여 자연채광을 유입시키면서 건조대상물을 자연건조도 시킬 수 있도록 한 구조로부터, 수요자의 요구 조건에 맞춰 고추와 같은 농산물들의 건조가 확실하게 이루어질 수 있도록 하는 황토를 이용한 건조장에 관한 것이다. claims: 황토 또는 황토를 함유한 마감재로 내측 벽면과 바닥면을 형성한 건조장 본체와, 상기 건조장 본체의 상면을 덮는 투명 또는 반투명 소재의 지붕과, 상기 건조장 본체의 일측면에 형성되어 출입 가능한 도어를 포함하는 제1 유닛;상기 지붕 아래에 적어도 하나 이상 배치되어 상기 건조장 본체의 내부 공간의 공기(이하 '내부공기')를 강제 대류시키는 순환기와, 상기 내부공기를 흡입하고 가열시켜 건조된 에어를 토출시키는 황토방 건조기를 포함하는 제2 유닛; 및상기 도어를 통하여 출입 가능하며, 복수의 건조대상물을 상하로 이격하여 다단 적층 가능한 트레이가 상하 슬라이딩 적재 가능한 건조 본체와, 상기 건조 본체의 하부측에 이동 가능한 방향성 캐스터를 포함하는 제3 유닛을 포함하며,상기 건조대상물은 상기 지붕을 통하여 조사되는 자연채광을 통하여 건조되는 것을 특징으로 하는 황토를 이용한 건조장., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

717/1150 Row 717: application_number: 1020190103013, combined_string: invention_title: 농산물 수급 예측 서버 및 농산물 수확 최적지 분석 방법 abstract: 실시예에 따른 농산물 수급 예측 서버 및 농산물 수확 최적지 분석 방법은 품종 별 표준지표와 농수산물별 수확 최적지 정보를 누적된 분석정보를 기반으로 업데이트하여 생산자와 도소매 업자에게 정확한 정보를 제공할 수 있다. 또한, 실제 기후데이터와 품종 별 품질 데이터를 반복측정하고 측정 결과를 누적하여 품종 별 표준지표와 최적지 정보를 업데이트 할 수 있고, 실제 기후에 따라 농작물의 수급과 품질, 가격을 예측할 수 있다. 또한, 실시예를 통해 년도, 계절, 분기에 따른 실제 기후에 따라 수확된 농산물 품질을 분석하여 기후와 품질의 상관관계에 대한 분석 데이터를 확보할 수 있고, 품질 예측을 통해 가격 차등을 정확하게 산출하여, 소비자에게 고품질의 농산물을 합리적인 가격으로 제공할 수 있고, 지역별 농수산물의 품질과 수확량에 대한 정확한 수급 예측을 통해 가격을 안정화 시키고 농수산물 수급을 안정적으로 조정할 수 있도록 한다. claims: 농산물 수확 최적지 분석 방법에 있어서,(A)분석서버에서 농산물의 최적 수확환경데이터인 품종 별 표준지표를 설정하는 단계;(B)분석서버에서 지역별 강수량, 일조량, 일교차를 포함하는 환경정보 및 지역별 누적 날씨 데이터를 수집하는 단계;(C)분석서버에서 수집된 날씨 데이터와 지역별 환경정보를 상기 표준지표와 비교하고 상관관계를 분석하는 단계; 및(D)분석서버에서 상관관계가 가장 높은 지역을 최적지로 추출하고, 상기 최적지로 추출된 지역 농산물의 작황, 수확량, 품질을 포함하는 농산물 수확 품질 세부정보를 파악하는 단계; (E) 분석서버에서 상기 추출된 최적지의 환경정보와 표준지표를 비교하는 단계; (F) 분석서버에서 지역별 환경정보와 표준지표를 기간에 따라 비교하고, 지역 별 농산물 품질을 비교하는 단계;및(G) 분석서버에서 비교 결과에 따라 농산물별 최고 품질지역을 선정하는 단계;를 포함하고,상기 (F) 단계; 는지역별 환경정보와 표준지표 비교결과 및 실제 농산물 수확 품질의 데이터를 축적하여, 시계열 분석을 통해 농산물의 수급, 가격을 예측하고, 최적지를 업데이트 하고, 업데이트된 최적지에 따라 농산물 별 표준지표를 업데이트 하고상기 (C) 단계; 는분석서버에서 실제 지역에서 재배된 농산물의 품종 별 품질 정보를 반복 측정하고, 반복 측정된 정보를 누적 저장하여 새로운 표준지표를 생성하는 단계;표준지표와 지역별 환경정보의 상관관계에 따라 지역별 농산물 품종의 품질을 예측하는 단계; 계절변동 및 순환변동으로 인한 실제 지역별 기후데이터와 환경데이터를 누적저장하고 수확량, 품질을 포함하는 농작물 수확정보를 누적하고 환경데이터와 농작물 수확정보에 대한 상관관계를 파악하여 실제 기후데이터가 입력되면 농작물 재배량과 품질을 예측하는 단계; 및농작물 재배량과 품질 예측 결과에 따라 농산물 가격차등 정도를 산출하는 단계;를 포함하고,상기 (D) 단계; 는분석서버에서 최적지로 추출된 지역 농산물의 작황, 수확량, 품질을 포함하는 농산물 수확 품질 세부정보를 파악하고, 농산물 수확 품질 세부정보에 따라 표준지표와 최적지를 업데이트하고, 지역별 농산물 수급 및 가격을 예측하는 단계; 지역별 환경정보와 표준지표 비교결과 및 실제 농산물 수확 품질의 데이터를 축적하여, 시계열 분석 및 회귀분석을 통해 농산물의 수급, 가격을 예측하고, 최적지를 업데이트 하는 단계;시계열 분석 결과를 통해, 실제 날씨에 따른 품종 별 재배량과 품질 및 수요량을 예측하고 예측 결과를 기반으로 그 해 농작물의 지역별 품질 예측과 가격예측을 수행하는 단계;업데이트된 최적지에 따라 농산물 별 표준지표를 업데이트 하고, 표준지표와 지역별 환경정보의 상관관계에 따라 지역별 농산물 품종 품질을 예측하고, 지역별 농산물 품종 품질 예측 결과에 따라 농산물 가격차등 정도를 산출하는 단계; 및 농산물의 크기, 색 선명도, 당도, 무게, 재배량을 포함하는 측정 가능한 농산물의 세부정보를 전달받아, 품종 별 평균크기와 비교하고 품종 별 표준편차를 산출하여 수확된 농산물의 품질을 파악하는 단계;를 포함하고,상기 시계열 분석은 과거의 날씨정보 변화추세나 이에 따른 지역별 농작물의 재배량, 품질 변화 및 농작물 재배량과 품질에 기반한 수요 또는 소비 변화 데이터를 누적저장하고 저장된 데이터를 추적하여 분석하는 것을 특징으로 하는 농산물 수확 최적지 분석 방법.농산물 수급 예측 서버에 있어서,농산물의 최적 수확환경데이터인 품종 별 표준지표를 설정하여 저장하는 데이터베이스;지역별 강수량, 일조량, 일교차를 포함하는 환경정보 및 지역별 누적 날씨 데이터를 수집하는 수집모듈;수집된 날씨 데이터와 지역별 환경정보를 상기 표준지표와 비교하여 상관관계를 분석하고, 상관관계가 가장 높은 지역을 최적지 추출하는 분석모듈; 및상기 최적지로 추출된 지역 농산물의 작황, 수확량, 품질을 포함하는 농산물 수확 품질 세부정보를 파악하고, 상기 농산물 수확 품질 세부정보에 따라 표준지표와 최적지를 업데이트하고, 지역별 농산물 수급 량 및 가격을 예측하는 연산모듈; 을 포함하고상기 분석모듈; 은 지역별 환경정보와 표준지표를 기간에 따라 비교하고, 지역 별 농산물 품질을 비교하고, 비교 결과에 따라 농산물별 최고 품질지역을 선정하고 상기 연산모듈; 은 실제 지역에서 재배된 농산물의 품종 별 품질 정보를 반복 측정하고, 반복 측정된 정보를 누적 저장하여 새로운 표준지표를 생성하고, 지역별 환경정보와 표준지표 비교결과 및 실제 농산물 수확 품질의 데이터를 축적하여, 시계열 분석을 통해 농산물의 수급, 가격을 예측하고, 최적지를 업데이트하고, 업데이트된 최적지에 따라 농산물 별 표준지표를 업데이트 하고, 표준지표와 지역별 환경정보의 상관관계에 따라 지역별 농산물 품종 품질을 예측하고, 계절변동 및 순환변동으로 인한 실제 지역별 기후데이터와 환경데이터를 누적저장하고 수확량, 품질을 포함하는 농작물 수확정보를 누적하고 환경데이터와 농작물 수확정보에 대한 상관관계를 파악하여 실제 기후데이터가 입력되면 농작물 재배량과 품질을 예측하고, 농작물 재배량과 품질 예측 결과에 따라 지역별 농산물의 가격차등 정도를 산출하고상기 연산모듈; 은 지역별 환경정보와 표준지표 비교결과 및 실제 농산물 수확 품질의데이터를 축적하여, 시계열 분석 및 회귀분석을 통해 농산물의 수급, 가격을 예측하고, 최적지를 업데이트 하고, 시계열 분석 결과를 통해, 실제 날씨에 따른 품종 별 재배량과 품질 및 수요량을 예측하고 예측 결과를 기반으로 그 해 농작물의 지역별 품질 예측과 가격예측을 수행하고, 업데이트된 최적지에 따라 농산물 별 표준지표를 업데이트 하고, 표준지표와 지역별 환경정보의 상관관계에 따라 지역별 농산물 품종 품질을 예측하고, 지역별 농산물 품종 품질 예측 결과에 따라 농산물 가격차등 정도를 산출하고, 농산물의 크기, 색 선명도, 당도, 무게, 재배량을 포함하는 측정 가능한 농산물의 세부정보를 전달받아, 품종 별 평균크기와 비교하고 품종 별 표준편차를 산출하여 수확된 농산물의 품질을 파악하고,상기 시계열 분석은 과거의 날씨정보 변화추세나 이에 따른 지역별 농작물의 재배량, 품질 변화 및 농작물 재배량과 품질에 기반한 수요 또는 소비 변화 데이터를 누적저장하고 저장된 데이터를 추적하여 분석하는 것을 특징으로 하는 농산물 수급 예측 서버., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

718/1150 Row 718: application_number: 1020190101430, combined_string: invention_title: 양액을 분무하는 농산물 저장방법 및 그 저장고 abstract: 본 발명은 양액(養液)을 분무하는 농산물 저장방법 및 그 저장고에 관한 것으로 농산물을 저장하는 일정한 공간을 가진 저장고에 공조수단에 의해 신선공기를 공급 순환하게 된 것에 있어서,상기 저장고에 저장된 각종 농산물에 식물이 흡수할 수 있는 가급태(可給態)의 무기질 양분과 미생물의 살균, 또는 활성을 억제하는 효능이 있는 성분이 혼합된 양액을 분무수단에 의해 분무하여 소정의 온도와 습도를 유지하면서 미생물의 활성을 억제하고 식물학적으로 농산물에 영양분이 보충되어 신선도를 유지하면서 장기간 보관이 가능하게 된 것이다. claims: ,저장고에 저장된 농산물을 공조기구에 의해 일정한 온도와 습도로 공조하여 저장하게 된 것에 있어서,저장고에 저장된 농산물의 생체에 황(S), 칼슘(Ca), 일산화질소(NO)의 무기질 이온이 함유된 양액을 분무수단에 의해 분무하여 저장하는 것을 특징으로 하는 양액을 분무하는 농산물 저장방법.저장고의 상부 측에 냉각기구가 구비된 팬코일이 설치되고 저장고의 하부 측에서 상기 팬코일에 이르는 공기의 순환 닥트가 구비되어 공조하게 된 것에 있어서,상기 저장고에 양액이 분무되는 분무수단이 구비된 것을 특징으로 하는 양액을 분무하는 농산물의 저장고, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

719/1150 Row 719: application_number: 1020190101555, combined_string: invention_title: 밀폐형 제습순환타입의 건조 장치 abstract: 실시예는 밀폐형 제습순환타입의 건조 장치에 관한 것이다.구체적으로, 이러한 장치는 여러 대의 건조장치를 운용하는 경우, 각 건조장치의 순환 파이프의 밸브를 순차적으로 개폐하여 한 조의 순환장치와 응축기를 통해 다수의 건조장치의 수분을 제거한다. claims: 건조할 시, 다수의 건조장치를 운용해서 수분을 제거함으로써 건조하는 장치에 있어서,상기 다수의 건조장치를 통해 수분이 제거될 시, 상기 다수의 건조장치에 대해 공용의 단일장치로서 상기 다수의 건조장치의 수분을 각기 개별적으로 통합하여 빨아들이는 순환장치;상기 순환장치에 의해 다수의 건조장치의 수분이 빨아들여질 시, 상기 순환장치와 연동하여 상기 다수의 건조장치에 대해 공용의 단일장치로서 상기 다수의 건조장치의 수분을 각기 개별적으로 통합하여 제습하는 응축기;상기 순환장치와 상기 응축기에 의해 수분이 제거될 시, 상기 다수의 건조장치마다 개별적으로 상기 순환장치와 상기 응축기에 각기 연결 설치하는 다수의 밸브; 및상기 다수의 밸브에 의해 다수의 건조장치마다 개별적으로 상기 순환장치와 상기 응축기에 연결될 시, 상기 다수의 밸브로부터 구동을 미리 설정된 순서에 따라 순차적으로 시킴으로써 다수의 건조장치의 수분을 순차제거하는 제어유닛; 을 포함하고,상기 제어유닛은 시스템적으로 제어를 할 시, 센서류로부터 신호를 입력받아 제어대상으로 상이한 제어신호를 제공함으로써 사용자의 설정에 따라 동작하도록 하는 PLC로 이루어지되,상기 동작이 될 시, 상기 센서류로부터 신호를 입력받아 데이터를 수집하는 입력모듈;상기 입력모듈에 의해 신호가 입력될 시, 미리 설정된 제어 로직에 따라 입력된 신호를 프로세싱하여 상이한 제어신호를 발생함으로써 데이터에 따라 상이하게 제어하는 CPU모듈; 및상기 CPU 모듈에 의해 제어신호가 발생될 시, 제어대상으로 상기 제어신호를 전달함으로써 제공하는 출력모듈; 을 포함하고 있으며,상기 동작이 될 시, 자체 유/무선 통신모듈을 구비하여 외부의 제어대상 및 IOT센서로부터 데이터를 수집해서 외부의 제어대상으로 제어신호를 송출함으로써 인터페이스하는 IOT모듈; 을 포함하고,상기 CPU모듈은 상기 IOT모듈에 의해 데이터가 수집될 시, 미리 설정된 해당되는 제어 로직에 따라 수집된 데이터를 프로세싱하여 상이한 제어신호를 발생함으로써 IOT 데이터에 따라 상이하게 제어하고,상기 제어유닛은, a) 상기 다수의 건조장치의 수분이 순차제거될 시, 해당되는 건조장치의 수분 제거도가 미리 설정된 수분 제거도보다 이상인 경우 정상 처리하고 미만인 경우 건조장치의 건조에 실질적으로 영향을 미치는 이상인자를 검출하며,b) 상기 이상인자는 건조장치, 건조할 대상이며,c) 상기 이상인자는아래의 [식 1]로 건조장치가 이상인자인지의 여부를 추정하여 상기 [식 1]의 추정 값(Xt)이 미리 설정된 값 이상인 경우 건조장치를 이상인자로 판별하며, 미만인 경우 건조할 대상 자체를 이상인자로 순차적으로 판별하고,[식 1]Xt = γ1Xt-1 + γ2Xt-2 + ... + γpXt-p + ζt - δt-1ζt-1 - ... - δqζt-q(여기서, Xt는 현재 건조장치 영향도, Xt-p는 현재 건조장치의 표면 청결도와, 표면 상태를 포함한 건조장치 자체의 부품인자별 건조장치 영향도, γ는 건조장치 자체의 부품인자별 영향도 간 상관도, ζ는 건조장치 자체의 부품인자별 영향도 이동 평균 값과 상기 Xt-p 간 오차, δ는 상기 ζ의 건조장치 영향도)d) 상기 [식 1]의 이동평균 구간은, 사용 중인 건조장치의 현재 마모도가 미리 설정된 값보다 적은 경우 미리 설정된 기준 이동평균 구간 값에서 아래의 [식 2]에 따라 산출한 이동평균 구간 값만큼 차감하여 단축 설정하고, 큰 경우 상기 기준 이동평균 구간 값에서 아래의 [식 2]에 따라 산출한 이동평균 구간 값만큼 가산하여 신장 설정하는 것을 특징으로 하는 밀폐형 제습순환타입의 건조 장치.[식 2]이동평균 구간 = [{(현재 마모도 - 미리 설정된 마모도)/미리 설정된 단위 마모도 차이 값} × 미리 설정된 단위 이동평균 구간], Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

720/1150 Row 720: application_number: 1020190100344, combined_string: invention_title: 친환경 농산물 및 그 가공품의 종합관리 시스템 abstract: 본 발명은 실질적으로 생산 단계에서는 확실한 친환경 농산물을 생산할 수 있도록 지도 및 관리하고, 생산된 친환경 농산물을 지리정보부(WebGIS) 등을 포함한 인터넷 전자상거래를 연계하여 친환경 농산물의 생산, 가공, 유통, 마케팅의 주요 과정을 생산자 입장에서는 통제 관리할 수 있으며, 소비자입장에서는 구매 물품의 생산과정, 가공과정, 유통과정 등을 확인 선택할 수 있도록 함으로써 친환경 농산물을 신뢰를 바탕으로 유효 적절히 생산, 유통 및 판매할 수 있도록 한 친환경 농산물 및 그 가공품의 종합관리 시스템에 관한 것이다. 이러한 본 발명은 무선통신망을 포함하는 인터넷망(100)에 연결되어 친환경 농산물의 생산, 가공, 유통, 마케팅의 주요 과정 및 친환경 농산물 및 그 가공품의 품질인증을 생산자의 입장에서 종합적으로 관리하는 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)와; 상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 상기 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)로 즉시출하가능 친환경 농산물, 예정출하가능 친환경 농산물, 경매출하가능 친환경 농산물 및 농산물 가공품의 이력정보(농산물이력번호, 생산지, 판매지, 보관방법, 농약명, 농약사용횟수, 농약사용일자, 농약제조사, 출하시기, 포장단위, 가격, 생산자 신상정보, 당도, 맛, 크기, 무게 등)를 제공하는 생산자단말기(300)와; 상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 생산자로부터 공급받은 친환경 농산물을 웹서버의 홈페이지를 통해 소비자에게 주문받은 친환경 농산물 및 그 가공품을 판매하는 전문쇼핑몰 웹서버(400)와; 상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 상기 전문쇼핑몰 웹서버(400)에서 친환경 농산물 및 그가공품을 검색한 후, 소비자가 원하는 친환경 농산물 또는 그 가공품을 주문(즉시주문, 예정주문 및 공동주문등)하는 소비자단말기(500)를 포함하여 구성된다. claims: 무선통신망을 포함하는 인터넷망(100)에 연결되어 친환경 농산물의 생산, 가공, 유통, 마케팅의 주요 과정, 친환경 농산물 및 그 가공품의 품질인증을 생산자의 입장에서 종합적으로 관리하는 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)와;상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 상기 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)로 즉시출하가능 친환경 농산물, 예정출하가능 친환경 농산물, 경매출하가능 친환경 농산물및 친환경 농산물 가공품의 이력정보(농산물이력번호, 생산지, 판매지, 보관방법, 농약명, 농약사용횟수, 농약사용일자, 농약제조사, 출하시기, 포장단위, 가격, 생산자 신상정보, 당도, 맛, 크기, 무게 등)를 제공하는 생산자단말기(300)와;상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 생산자로부터 공급 받은 친환경 농산물 및 그 가공품을 웹서버의 홈페이지를 통해 소비자에게 주문받은 친환경 농산물 또는 그 가공품을 판매하는 전문쇼핑몰 웹서버(400)와;상기 인터넷망(100)을 통해 친환경 농산물 및 그 가공품의 종합관리 웹서버(200)에 연결되어 상기 전문쇼핑몰 웹서버(400)에서 친환경 농산물 및 그 가공품을 검색한 후, 소비자가 원하는 친환경 농산물 또는 그 가공품을 주문(즉시주문, 예정주문 및 공동주문 등)하는 소비자단말기(500)를 포함하여 구성된 것을 특징으로 하는 친환경 농산물의 종합관리 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

721/1150 Row 721: application_number: 1020190100359, combined_string: invention_title: 농산물 품질 인증 서비스 방법 abstract: 농산물 품질 인증 서비스 방법이 개시된다. 본 발명에 따른 농산물 품질 인증 서비스 방법은 (a) 서로 다른 고유의 식별 코드들을 가지는 비메모리 방식의 알에프아이디 태그들과 시리얼 번호를 인쇄하여 형성된 마커부를 포함하는 롤 타입 스티커를 준비하는 단계와; (b) 생산자 컴퓨터에서 품질 등급 데이터, 및 해당 품질 등급 박스의 수량을 나타내는 수량 데이터를 포함하는 농산물 정보 데이터와 함께 생산자 정보와 유효 기간 데이터를 포함하는 기본 정보 데이터를 농산물 품질 인증 서버로 전송하는 단계와; (c) 농산물 품질 인증 서버에서 기본 정보 데이터를 사용하여 미리 등록되어 있는 인증된 생산자인지를 확인하고 농산물 정보 데이터를 기초로 해당 수량의 알에프아이디 식별코드를 접수하여 데이터베이스에 저장하는 단계와; (d) 농산물 품질 인증 서버에서 전송 시점을 기점으로 유효 기간 데이터를 사용하여 유효기간을 카운트하여 유효 기간이 경과한 제품 박스에 해당하는 식별코드를 무효화 시키는 단계와; (e) 농산물 품질 인증 서버에서 사용자로부터 시리얼 번호를 입력받고 입력된 시리얼 번호에 매핑된 알에프아이디 식별코드를 얻고 알에프아이디 식별코드에 해당하는 생산자 정보를 사용하여 친환경 인증 업체 서버에 접속하여 해당 생산자가 생산하는 농산물이 친환경 농산물인지의 여부를 검색하는단계; 및 (f) 농산물 품질 인증 서버에서 농산물의 유효 여부와 함께 검색된 친환경 농산물 품질 인증 결과를 사용자에게 전송하는 단계;를 포함하는 것을 특징으로 한다.본 발명에 따르면 사용자, 즉, 유통점 또는 최종 소비자는 시리얼 번호를 사용하기 때문에 알에프아이디 리더가 없이도 구입한 제품의 인증 여부를 확인할 수 있고, 당해 제품 박스의 제품 유효기간이 경과하면 식별 코드를 무효화시키기 때문에 포장 박스를 재사용하거나 위조하여 유통시키는 것을 방지할 수 있고 친환경 농산물인지를 확인함에 있어 매우 확고한 수단을 제공한다. 또한, 선택적으로, 최종 소비자는 태그의 저면에 인쇄된 비밀 번호를 사용하여 유통점과는 차별화된 검색 권한을 가지고 자신이 구입한 제품에 대해 인증된 생산자가 판매한 것인지 유통점에서 위조한 제품인지를 확인할 수 있다. claims: (a) 서로 다른 고유의 식별 코드들을 가지는 비메모리 방식의 알에프아이디 태그들과 상기 태그의 인접한 위치에 상기 식별 코드에 포함된 시리얼 번호를 인쇄하여 형성된 마커부를 포함하는 롤 타입 스티커를 준비하는 단계;(b) 물품을 포장하는 장소에 구비되고 알에프아이디 리더가 접속되어 있는 생산자 컴퓨터에서 품질 등급 데이터, 및 해당 품질 등급 박스의 수량을 나타내는 수량 데이터를 포함하는 농산물 정보 데이터와 함께 생산자 정보와 유효 기간 데이터를 포함하는 기본 정보 데이터를 농산물 품질 인증 서버로 전송하는 단계;(c) 농산물 품질 인증 서버에서 기본 정보 데이터를 사용하여 미리 등록되어 있는 인증된 생산자인지를 확인하고 농산물 정보 데이터를 기초로 해당 수량의 알에프아이디 식별코드를 접수하여 데이터베이스에 저장하는 단계;(d) 농산물 품질 인증 서버에서 전송 시점을 기점으로 유효 기간 데이터를 사용하여 유효기간을 카운트하여 유효 기간이 경과한 제품 박스에 해당하는 식별코드를 무효화 시키는 단계;(e) 농산물 품질 인증 서버에서 사용자로부터 시리얼 번호를 입력받고 입력된 시리얼 번호에 매핑된 알에프아이디 식별코드를 얻고 알에프아이디 식별코드에 해당하는 생산자 정보를 사용하여 친환경 인증 업체 서버에 접속하여 해당 생산자가 생산하는 농산물이 친환경 농산물인지의 여부를 검색하는 단계; 및 (f) 농산물 품질 인증 서버에서 농산물의 유효 여부와 함께 검색된 친환경 농산물 품질 인증 결과를 사용자에게 전송하는 단계;를 포함하는 것을 특징으로 하는 농산물 품질 인증 서비스 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

722/1150 Row 722: application_number: 1020190100372, combined_string: invention_title: 농산물 및 그 가공식품의 안전성을 보증하는 안전농산물생산관리시스템 및 그 방법 abstract: 본 발명은 농산물 및 그 가공식품의 생산/가공 과정에서 발생하는 모든 정보를 관리하고 생산자, 소비자, 감독자에게 제공하여 안전성을 보증하는 안전농산물 생산관리시스템 및 그 방법에 관한 것이다.본 발명에 따른 안전농산물 생산관리시스템은, 농산물 생산자 및 가공식품 가공자로부터 생산이력정보를 전송받아 안전성 검사결과에 대하여 인증여부를 판단하고, 생산자, 가공자, 연구자/지도자 및 소비자에게 생산관리정보를 제공하는 중앙생산관리서버; 재배현황정보를 전송하는 생산자단말; 가공현황정보를 전송하는 가공자단말; 생산자 및 가공자와 쌍방향 통신을 통하여 원격상담하는 연구자/지도자단말; 및 농산물 및 가공식품의 RFID 번호를 전송하고, 상기 생산관리정보를 제공받아 상품의 안전성 여부를 확인하는 소비자단말을 포함하여 이루어진다.본 발명에 따르면, 생산자는 고품질의 농산품을 생산할 수 있고 소비자는 생산부터 유통의 전과정을 모니터링함으로써 신뢰할 수 있는 상품을 구매할 수 있는 것으로 생산자에게는 고부가가치의 제품을 생산하고 안정적인 매출을 보장해준다. claims: 네트워크를 통하여 안전농산물 및 그 안전가공식품의 생산관리정보를 공유하여 관리하는 시스템에 있어서,농산물 생산자로부터 생산환경정보를 입력받고 작물재배정보를 제공하고, 가공식품 가공자로부터 가공환경정보를 입력받고 가공처리공정정보를 제공하고, 농산물 생산지 및 가공식품 가공지에 설치된 원격화상카메라가 촬영한 정보를 모니터하고, 상기 농산물 및 가공식품에 대한 안전성 검사결과에 대하여 인증여부를 판단하고, 생산자, 가공자, 연구자/지도자 및 소비자에게 생산관리정보를 제공하는 중앙생산관리서버;상기 중앙생산관리서버로 상기 생산환경정보를 전송하고, 전송받은 상기 작물재배정보에 따른 생산과정에서 발생하는 재배현황정보를 전송하는 생산자단말;상기 중앙생산관리서버로 상기 가공환경정보를 전송하고, 전송받은 상기 가공처리공정정보에 따른 가공과정에서 발생하는 가공현황정보를 전송하는 가공자단말;상기 중앙생산관리서버의 중개에 따라, 상기 원격화상카메라의 모니터정보를 수신하고 생산자 및 가공자와 쌍방향 통신을 통하여 원격상담하는 연구자/지도자단말; 및상기 중앙생산관리서버로 상기 농산물 및 가공식품의 RFID 번호를 전송하고, 상기 생산관리정보를 제공받아 상품의 안전성 여부를 확인하는 소비자단말을 포함하여 이루어지는 것을 특징으로 하는 농산물 및 그 가공식품의 안전성을 보증하는 안전농산물 생산관리시스템.네트워크를 통하여 안전농산물 및 그 안전가공식품의 생산관리정보를 공유하여 관리하는 방법에 있어서,(1)중앙생산관리서버가 생산자단말로부터 생산환경정보 및 전체 재배현황정보를 전송받고 각각 농산물생산환경DB 및 재배현황정보DB에 저장하는 단계;(2)상기 중앙생산관리서버가 가공자단말로부터 가공환경정보 및 전체 가공현황정보를 전송받고 각각 가공식품생산환경DB 및 가공현황정보DB에 저장하는 단계;(3)상기 중앙생산관리서버가 생산완료된 상기 농산물 및 가공식품에 대하여 소정의 안전성 기준에 따른 안전검사를 수행하여 RFID의 인증을 발급하는 단계;(4)상기 중앙생산관리서버가 상기 농산물 및 가공식품이 소정의 유통경로 게이트를 통과할 때 RFID 인식장치로부터 위성통신을 통하여 유통위치정보를 수신하여 모니터링하는 단계;(5)상기 중앙생산관리서버가 개인 단말기(PC, 모바일)로부터 상기 농산물 또는 가공식품의 RFID를 전송받고, 상기 생산환경정보, 재배현황정보, 가공환경정보, 가공현황정보, 안전성 검사인증정보 및 유통정보를 포함하는 생산관리정보를 제공하는 단계를 포함하여 이루어지는 것을 특징으로 하는 농산물 및 그 가공식품의 안전성을 보증하는 안전농산물 생산관리방법., Ltext: 농업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

723/1150 Row 723: application_number: 1020190099963, combined_string: invention_title: 맞춤형 농산물 유통 시스템 abstract: 본 발명의 일 실시 예에 따른 농산물 유통 시스템은, 소비자 정보를 서버로 전송하고, 상기 소비자의 농산물 소 비 정보를 입력 받아 상기 서버로 전송하는 단말, 소비자 정보와 농산물 정보를 데이터베이스에 저장하고, 상기 소비자가 단말에 입력한 소비 정보를 수신하여, 상기 소비자 정보와 상기 소비 정보를 대응시켜 상기 데이터베이스에 저장하고, 상기 소비 정보에 따라 상기 농산물 정보에서 필요한 농산물을 선별하고, 상기 농산물의 포장량 을 결정하고, 상기 소비자 정보, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 농산물 포장장치에 송신하는 서버, 서버로부터 상기 소비자 정보, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 수신하고, 포대에 상기 소비자의 주소, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 인쇄하고, 상기 포대에 상기 농산물을 담는 포장장치 및 상기 포장된 포대를 상기 소비자에게 배달하는 배송망을 포함하는 농산물 유통 시스템일 수 있다.본 발명에 따르면, 소비자와 생산자를 직접 연결함으로써, 유통경로를 단순화하여 농산물의 공급가격을 낮출 수 있고, 소비자에게 농산물의 생산정보를 제공하여, 소비자의 신뢰를 높일 수 있고, 소비자의 소비량과 소비패턴을 고려하여 농산물을 공급함으로써, 소비자가 항상 신선한 농산물을 소비할 수 있도록 한다. claims: 소비자 정보를 서버로 전송하고, 상기 소비자의 농산물 소비 정보를 입력 받아 상기 서버로 전송하는 단말;소비자 정보와 농산물 정보를 데이터베이스에 저장하고, 상기 소비자가 단말에 입력한 소비 정보를 수신하여, 상기 소비자 정보와 상기 소비 정보를 대응시켜 상기 데이터베이스에 저장하고, 상기 소비 정보에 따라 상기 농 산물 정보에서 필요한 농산물을 선별하고, 상기 농산물의 포장량을 결정하고, 상기 소비자 정보, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 농산물 포장장치에 송신하는 서버;서버로부터 상기 소비자 정보, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 수신하고, 포대에 상기 소비 자의 주소, 상기 농산물 정보 및 상기 농산물의 포장량 정보를 인쇄하고, 상기 포대에 상기 농산물을 담는 포장 장치; 및상기 포장된 포대를 상기 소비자에게 배달하는 배송망을 포함하는 농산물 유통 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

724/1150 Row 724: application_number: 1020210140795, combined_string: invention_title: 가축의 반추위를 모니터링하는 장치 및 방법 abstract: 가축의 반추위에 삽입된 센서 장치로부터 움직임 데이터를 수집하여 가축의 활동을 분석하고, 활동 정보를 이용하여 가축의 건강 및 질병 관리 정보를 모니터링하는 장치 및 방법에 관한 것이다. 본 발명에 따라 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 장치는, 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하는 데이터 센싱부; 수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 활동 분석부; 및 분석된 활동 정보를 저장하고, 활동 정보가 분석되지 않는 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 모니터링부를 포함한다. claims: 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 장치에 있어서, 상기 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하는 데이터 센싱부; 수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 활동 분석부; 및 분석된 활동 정보를 저장하고, 상기 활동 정보의 분석에 따른 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 모니터링부를 포함하고, 상기 모니터링부는 상기 활동분석부에서 분석된 섭취 활동, 반추 활동 및 휴식 활동을 기 누적 저장된 개체별 및 품종별 패턴 정보와 비교하여 섭취 활동, 반추 활동 및 휴식 활동의 어느 부분에서 문제가 있는지를 관리자에게 통보할 수 있는 것을 특징으로 하는 장치.장치가 경구 투여로 가축의 반추위에 삽입된 센서 장치를 이용하여 가축의 활동을 모니터링하는 방법에 있어서, 상기 센서 장치로부터 반추위의 움직임 데이터를 포함한 센싱 데이터를 수신하여 센싱하는 단계; 수신된 센싱 데이터를 이용하여 섭취 활동, 반추 활동 및 휴식 활동으로 분석하는 단계; 및 분석된 활동 정보를 저장하고, 상기 활동 정보의 분석에 따른 가축의 건강 및 질병의 정보를 제공하여 모니터링하는 단계를 포함하고, 상기 분석된 섭취 활동, 반추 활동 및 휴식 활동을 기 누적 저장된 개체별 및 품종별 패턴 정보와 비교하여 섭취 활동, 반추 활동 및 휴식 활동의 어느 부분에서 문제가 있는지를 관리자에게 통보할 수 있는 것을 특징으로 하는 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

725/1150 Row 725: application_number: 1020210030455, combined_string: invention_title: 가축 건강상태 면역 지표화 시스템 abstract: 본 발명은 가축 건강상태 면역 지표화 시스템에 관한 것으로서, 보다 구체적으로는 축산농가에서 수집된 데이터를 이용해 가축의 건강상태를 나타내는 면역 관련 지표를 선정하여 가축의 건강상태를 면역 지표화하는, 가축 건강상태 면역 지표화 시스템으로서, 복수의 축산농가에서 수집된 데이터를 저장하는 데이터베이스부; 가축 건강상태와 관련된 변수 중에서 면역학적 건강 정도를 나타내는 후보 지표를 도출하는 후보 도출부; 상기 데이터베이스부에 저장된 검체 정보를 이용해, 상기 후보 지표의 상태 값을 분석하는 데이터 분석부; 상기 후보 지표의 상태 값과 다른 기존 지표 사이의 연관성을 분석하는 연관성 분석부; 상기 연관성 분석 결과 상기 후보 지표를 새로운 지표로 선정할지 결정하는 선정 결정부; 및 상기 선정 결정부에서 선정된 새로운 지표를 평가하되, 가축의 건강상태를 나타내는 정도를 평가하는 지표 평가부; 및 평가 대상 농가에서 수집된 상기 새로운 지표와 관련된 검체 정보를 이용해 상기 평가 대상 농가의 가축의 면역력을 포함하는 건강상태를 추정하는 농가 평가부를 포함하는 것을 그 구성상의 특징으로 한다.본 발명에서 제안하고 있는 가축 건강상태 면역 지표화 시스템에 따르면, 가축 건강상태와 관련된 변수 중에서 면역학적 건강 정도를 나타내는 후보 지표를 도출해, 실제 축산농가에서 수집된 데이터를 이용해 후보 지표의 상태 값을 분석하고, 다른 기존 지표와의 연관성을 분석해 새로운 지표로 선정하고 평가함으로써, 실제 축산농가의 데이터를 이용해 실용성 높은 새로운 지표를 개발 및 확립할 수 있고, 이를 통해 가축의 면역력 정도를 포함하는 건강상태를 쉽고 빠르게 파악하고, 노출 위험성 있는 질병이나 생산성을 예측하여 예방적 수의료 서비스를 위한 가축의 면역력 관리를 할 수 있다. claims: 축산농가에서 수집된 데이터를 이용해 가축의 건강상태를 나타내는 면역 관련 지표를 선정하여 가축의 건강상태를 면역 지표화하는, 가축 건강상태 면역 지표화 시스템(100)으로서,복수의 축산농가에서 수집된 데이터를 저장하는 데이터베이스부(110);가축 건강상태와 관련된 변수 중에서 면역학적 건강 정도를 나타내는 후보 지표를 도출하는 후보 도출부(120);상기 데이터베이스부(110)에 저장된 검체 정보를 이용해, 상기 후보 지표의 상태 값을 분석하는 데이터 분석부(130);상기 후보 지표의 상태 값과 다른 기존 지표 사이의 연관성을 분석하되, 상기 후보 지표의 상태 값과 항체가를 포함하는 기존의 면역지표 및 생리학적 건강 정도를 나타내는 건강 지표와의 연관성을 분석하는 연관성 분석부(140);상기 연관성 분석 결과 상기 후보 지표를 새로운 지표로 선정할지 결정하는 선정 결정부(150); 및상기 선정 결정부(150)에서 선정된 새로운 지표를 평가하되, 가축의 건강상태를 나타내는 정도를 평가하는 지표 평가부(160); 및평가 대상 농가에서 수집된 상기 새로운 지표와 관련된 검체 정보를 이용해 상기 평가 대상 농가의 가축의 면역력을 포함하는 건강상태를 추정하는 농가 평가부(180)를 포함하되,상기 데이터베이스부(110)는, 복수의 축산농가에서 사육하는 가축을 대상으로 수집한 면역 단백질 분석 데이터를 저장하며,상기 후보 지표는, 면역항체 형성력을 나타내는 면역 단백질이며,면역 단백질을 새로운 지표로 선정하여, 예방적 수의료 서비스를 위한 가축의 면역력 관리를 지원하고,상기 연관성 분석부(140)는,면역학적 건강 정도를 나타내는 면역지표인 상기 후보 지표의 상태 값과 생리학적 건강 정도를 나타내는 건강 지표의 상태 값 사이의 연관성을 분석하며,상기 생리학적 건강 정도를 나타내는 건강 지표는,생육 단계별 가축 생체 무게, 폐사율 및 생산성을 포함하는 군에서 선택된 적어도 하나 이상이고,상기 데이터 분석부(130)는, 상기 데이터베이스부(110)에 저장된 상기 후보 지표와 관련된 검체 정보를 이용해 정상범위를 설정하며,상기 연관성 분석부(140)는, 상기 설정한 정상범위를 이용하여, 상기 후보 지표의 상태 값을 미리 정해진 개수의 그룹으로 설정하고, 그룹별로 상태 값과 다른 기존 지표 사이의 연관성을 분석하는 것을 특징으로 하는, 가축 건강상태 면역 지표화 시스템(100)., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

726/1150 Row 726: application_number: 1020210001393, combined_string: invention_title: 정자의 동결보존제 스트레스 저항성 판별용 조성물 abstract: 본 발명은 동결보존제 스트레스 저항성 정자와 민감성 정자간의 NT5C1B, FH, CAPZB, VDAC2, 및 UQCRC1 단백질 발현 수준에 차이가 있음을 확인하여, 상기 단백질을 동결보존제 스트레스 저항성 마커로 제공하고, 상기 마커의 발현을 측정하는 물질을 포함하는 동결보존제 스트레스 저항성 판별용 조성물 등을 제공하는 것으로서, 본 발명의 제공에 의해 가축인공수정시 동결정액의 품질평가에 소요되는 비용 및 시간을 절감할 수 있고, 동결보존제에 의해 운동성, 생존성, 및 수정능획득이 저하되지 않는 고품질의 정자를 선별하여 인공수정의 성공률을 높이고 그 비용을 절감할 수 있을 것으로 기대된다. claims: 동결보존제 스트레스 저항성 마커 FH (Fumarate hydratase), 상기 마커를 코딩하는 유전자, 또는 상기 유전자의 mRNA를 검출하는 물질을 유효성분으로 포함하는 것을 특징으로 하는, 정자의 동결보존제 스트레스 저항성 판별용 조성물.제5항에 있어서,상기 단계 (3)은 동결보존제를 처리한 샘플에서 CAPZB (F-actin-capping protein subunit beta), VDAC2 (Voltage-dependent anion-selective channel protein 2), 및 UQCRC1 (Cytochrome b-c1 complex subunit 1)으로 이루어진 군으로부터 선택되는 하나 이상의 동결보존제 스트레스 저항성 마커, 상기 마커를 코딩하는 유전자, 또는 상기 유전자의 mRNA의 발현 수준을 추가로 측정하는 것을 특징으로 하고,상기 단계 (4)는 상기 샘플에서 측정한 발현 수준과 동결보존제를 처리하지 않은 대조군의 발현 수준을 비교하여 하기의 조건 (a)를 만족하는 경우 샘플의 정자가 동결보존제 스트레스에 저항성이 있는 것으로 추가 판별하는 것을 특징으로 하는, 동결보존제 스트레스 저항성 정자를 판별하기 위한 정보제공방법:(a) UQCRC1, CAPZB, 및 VDAC2로 이루어진 군으로부터 선택되는 하나 이상의 마커, 상기 마커를 코딩하는 유전자, 또는 상기 유전자의 mRNA의 발현 수준이 대조군의 발현 수준보다 낮을 것.제5항에 있어서,상기 동결보존제는 TYB(tris-egg yolk buffer) 및 글리세롤(glycerol); 폼아마이드(fomamide); 프로판디올(propanediol); DMSO(Dimethyl sulfoxide); 및 아도니톨(adonitol)로 이루어지는 군으로부터 선택되는 하나 이상을 포함하는 것을 특징으로 하는, 동결보존제 스트레스 저항성 정자를 판별하기 위한 정보제공방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

727/1150 Row 727: application_number: 1020200185962, combined_string: invention_title: 가축의 인공수정 시스템 abstract: 본 발명은 가축의 정액 또는 수정란을 가축의 생식기 내에 주입하기 위한 가축의 인공 수정 시스템에 있어서, 선단에 대상 가축에 정액 또는 수정란을 주입하기 위한 삽입관(110)을 구하는 인공수정용 주입기(100); 상기 인공수정용 주입기(100)와 길이방향으로 결합되고, 선단에 내시경 카메라(210)가 설치되어 상기 대상 가축의 자궁에 삽입되는 내시경 튜브(200); 상기 인공수정용 주입기(100)와 상기 내시경 튜브(200)가 결합되는 손잡이(300); 상기 대상 가축의 생식기 내 감염이 방지되도록 상기 인공수정용 주입기(100)와 상기 내시경 튜브(200)의 외주면을 감싸는 커버 스트로우(400); 및 상기 커버 스트로우(400)의 단부에 착탈가능하도록 결합되는 토출캡(500)을 포함하고, 상기 토출캡(500)은 상기 인공수정용 주입기(100)가 삽입되도록 일측이 개구되고, 타측이 상기 정액 또는 상기 수정란을 토출할 수 있도록 토출부(511)가 형성된 수용부(510); 상기 내시경 카메라(210)에 대응하여 위치하는 카메라용 렌즈(520); 및 일측에 상기 수용부(510) 및 상기 카메라용 렌즈(520)가 연결되고 타측이 상기 커버 스트로우(400)의 단부에 끼워지는 몸체부(530)를 포함하며, 상기 토출부(511)는 90도 간격으로 배치된 4개의 슬릿으로 형성되며, 상기 슬릿은 상기 토출부(511)의 전방 및 측면을 개구한 형태인 것을 특징으로 한다. claims: 가축의 정액 또는 수정란을 가축의 생식기 내에 주입하기 위한 가축의 인공 수정 시스템에 있어서,선단에 대상 가축에 정액 또는 수정란을 주입하기 위한 삽입관(110)을 구하는 인공수정용 주입기(100);상기 인공수정용 주입기(100)와 길이방향으로 결합되고, 선단에 내시경 카메라(210)가 설치되어 상기 대상 가축의 자궁에 삽입되는 내시경 튜브(200);상기 인공수정용 주입기(100)와 상기 내시경 튜브(200)가 결합되는 손잡이(300);상기 대상 가축의 생식기 내 감염이 방지되도록 상기 인공수정용 주입기(100)와 상기 내시경 튜브(200)의 외주면을 감싸는 커버 스트로우(400); 및상기 커버 스트로우(400)의 단부에 착탈가능하도록 결합되는 토출캡(500)을 포함하고,상기 토출캡(500)은상기 인공수정용 주입기(100)가 삽입되도록 일측이 개구되고, 타측이 상기 정액 또는 상기 수정란을 토출할 수 있도록 토출부(511)가 형성된 수용부(510);상기 내시경 카메라(210)에 대응하여 위치하는 카메라용 렌즈(520); 및일측에 상기 수용부(510) 및 상기 카메라용 렌즈(520)가 연결되고 타측이 상기 커버 스트로우(400)의 단부에 끼워지는 몸체부(530)를 포함하며,상기 토출부(511)는 90도 간격으로 배치된 4개의 슬릿으로 형성되며,상기 슬릿은 상기 토출부(511)의 전방 및 측면을 개구한 형태인 것을 특징으로 하는 가축의 인공수정 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

728/1150 Row 728: application_number: 1020200177413, combined_string: invention_title: 반려동물 보험 서비스 제공 방법 abstract: 반려동물 보험 서비스 제공 방법이 개시된다. 본 발명의 일 측면에 따르면, 동물병원 단말기로부터 반려동물이 보험에 가입되어 있는지 여부에 대한 확인 요청을 수신하는 단계; 반려동물이 보험에 가입되어 있는 것으로 확인되는 경우, 동물병원 단말기에 반려동물에 대한 진료 항목마다 수령 가능한 보험금 정보를 포함하는 보험금 테이블을 제공하는 단계; 동물병원 단말기로부터 반려동물의 진료에 따른 진료비를 입력받고 보험금 테이블 중 반려동물의 진료에 따른 보험금을 선택 입력받는 단계; 고객 단말기에 진료비에서 보험금을 차감한 금액을 최종 결제 금액으로 전송하는 단계; 동물병원 단말기로부터 보험금의 지급을 위한 진료 증빙 자료를 수신하는 단계; 보험금 지급 심사를 위하여 진료 증빙 자료를 보험사 서버에 전송하는 단계; 보험사 서버로부터 보험금 지급 결정에 대한 심사 결과를 수신하는 단계; 동물병원 단말기에 심사 결과를 통보하는 단계; 고객 단말기에 심사 결과를 통보하는 단계; 보험금 지급 내역을 동물병원 단말기에 통보하는 단계; 및 보험금 지급 내역을 고객 단말기에 통보하는 단계를 포함하는 반려동물 보험 서비스 제공 방법이 제공된다. claims: 반려동물 보험 서비스 제공 시스템은 고객이 반려동물의 진료에 보험의 적용을 요청하는 경우, 동물병원 단말기로부터 상기 반려동물이 보험에 가입되어 있는지 여부에 대한 확인 요청을 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 반려동물이 보험에 가입되어 있는 것으로 확인되는 경우, 상기 동물병원 단말기에 상기 반려동물에 대한 진료 항목마다 수령 가능한 보험금 정보를 포함하는 보험금 테이블을 제공하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원 단말기로부터 상기 반려동물의 진료에 따른 진료비를 입력받고 상기 보험금 테이블 중 상기 반려동물의 진료에 따른 보험금을 선택 입력받는 단계;상기 반려동물 보험 서비스 제공 시스템은 고객 단말기에 상기 진료비에서 상기 보험금을 차감한 금액을 최종 결제 금액으로 전송하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원 단말기로부터 상기 보험금의 지급을 위한 진료 증빙 자료를 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험금 지급 심사를 위하여 상기 진료 증빙 자료를 보험사 서버에 전송하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 진료 증빙 자료에 기초한 상기 보험금 지급 심사에 따라 상기 보험금의 지급이 결정되는 경우, 상기 보험사 서버로부터 상기 보험금 지급 결정에 대한 심사 결과를 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원 단말기에 상기 심사 결과를 통보하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기에 상기 심사 결과를 통보하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원에 상기 보험금이 지급되는 경우, 상기 보험금 지급 내역을 상기 동물병원 단말기에 통보하는 단계; 및상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원에 상기 보험금이 지급되는 경우, 상기 보험금 지급 내역을 상기 고객 단말기에 통보하는 단계를 포함하고,상기 반려동물이 보험에 가입되어 있는지 여부에 대한 확인 요청을 수신하는 단계는, 상기 동물병원 단말기로부터 상기 반려동물의 동물등록번호를 입력받는 단계를 포함하고,상기 반려동물의 동물등록번호는,상기 반려동물 보험 서비스 제공 시스템은 동물보호관리시스템 서버로부터 동물등록 대행업체로 인증된 업체 정보를 제공받는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물병원 단말기로부터 상기 동물병원이 상기 동물등록 대행업체로 인증되어 있는지 여부에 대한 확인 요청을 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 인증된 업체 정보에 상기 동물병원이 포함되는 경우, 상기 동물병원이 인증된 상기 동물등록 대행업체임을 확인한 결과를 상기 동물병원 단말기에 통보하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물등록 대행업체로 인증된 상기 동물병원에서 상기 반려동물에 대해 동물등록을 위한 절차가 수행되는 경우, 상기 동물병원 단말기로부터 상기 동물등록을 위한 절차 수행 관련 정보를 입력받는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물보호관리시스템 서버에 상기 동물등록을 위한 절차 수행 관련 정보를 전송하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 동물등록을 위한 절차 수행 관련 정보에 따라 상기 반려동물의 동물등록이 승인되는 경우, 상기 동물보호관리시스템 서버로부터 상기 반려동물의 동물등록 승인 결과를 수신하는 단계; 및상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기에 상기 반려동물의 동물등록 승인 결과를 통보하는 단계를 통해 획득되고,상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로부터 보험 상품 가입 신청을 받아 보험 상품 가입을 진행하고,상기 보험 상품 가입은,상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로부터 상기 보험 상품 가입 신청을 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험사 서버로 상기 보험 상품 가입 신청 정보를 전송하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험사 서버로부터 승인과 함께 보험료 결제 정보를 수신하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로 보험 승인 결정 및 상기 보험료 결제 정보를 전송하는 단계; 및상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로부터 보험료가 지급되는 경우, 상기 보험사 서버로부터 가입 승인 및 약관 정보를 수신받아 상기 고객 단말기로 전송하는 단계를 통해 진행되고,상기 보험 상품 가입 신청은 상기 반려동물에 대한 상세 정보를 포함하고,상기 반려동물에 대한 상세 정보는 상기 반려동물의 동물등록번호를 포함하고,상기 고객 단말기는 고객의 선택에 따라 직접 보험금을 수령 가능하도록 상기 반려동물 보험 서비스 제공 시스템에 보험금 지급을 요청하는 단계를 더 포함하고,상기 보험금 지급 요청 단계는,상기 반려동물 보험 서비스 제공 시스템은 상기 고객 단말기로부터 보험금 지급 요청 및 상기 반려동물의 진료에 대한 진료 증빙 자료를 전송받는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험금 지급 요청 및 상기 반려동물의 진료에 대한 진료 증빙 자료를 상기 보험사 서버에 제공하는 단계;상기 반려동물 보험 서비스 제공 시스템은 상기 보험사 서버로부터 보험금 지급 요청에 대한 심사 결과를 제공받아 상기 고객 단말기에 통보하는 단계; 및상기 보험사 서버는 상기 고객의 계좌로 직접 보험금을 지급하는 단계를 포함하는, 반려동물 보험 서비스 제공 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

729/1150 Row 729: application_number: 1020200166733, combined_string: invention_title: 유전자 정보에 기반한 품종정보 제공 시스템 및 방법 abstract: 본 발명은 애완동물의 혼혈정보를 제공하는 시스템을 개시한다. 상세하게는, 본 발명은 애완동물의 품종 특이적인 유전자 마커를 찾아내어 확정하고, 피검 애완동물의 유전적 품종을 명확하게 판별하는 유전자 정보에 기반한 품종정보 제공 시스템 및 방법에 관한 것이다.본 발명의 실시예에 따르면, 특정 품종의 유전자 정보가 얼마 만큼씩 유사한지를 측정하는 것이 아닌, 해당 품종에만 있는 유전자 마커를 단정적으로 확인하고, 그 품종에 속하는지 아닌지를 명확히 식별함에 따라, 단순 비율을 제공하는 것이 아닌, 실제 각 혼혈동물의 조상중에 어떤 품종들이 있는지를 정확하게 알려주는 효과가 있다. claims: 피검 동물로부터 채취된 시료를 해독하는 게놈 해독장치;상기 게놈 해독장치로부터 시료 해독 결과를 입력받고, 미리 구축된 분자 라이브러리와의 대조를 통해 상기 시료에 대한 유전자 검사를 수행하는 검사 단말기; 및정보통신망을 통해 원격지에 위치한 하나 이상의 검사 단말기와 연결되어 상기 유전자 검사결과를 전송받고, 상기 검사결과로부터 판단된 피검 동물의 품종과 관련된 하나 이상의 유전자 마커 중, 타 품종과의 특이성을 대표하는 비 공통 유전자를 하나 이상 추출하여 어느 품종인지 판단하고, 품종 의뢰에 따른 품종 정보를 제공하는 유전자 센터 서버를 포함하고,상기 유전자 센터 서버는,관리자에 의한 입력 또는 외부 시스템으로부터 전송되는 복수의 동물에 대한 유전자 정보를 수시로 수집하고, 수집된 동물의 유전자 정보의 분석을 수행하는 해독부;품종별 표준게놈지도를 해독, 조립 또는 전장게놈서열을 해독하거나, DNA chip에 기록된 데이터를 로딩하여 상기 유전자 정보에 포함되는 특이적 유전자 마커를 도출하는 특이마커 도출부;도출된 특이적 유전자 마커에 따라, 해당 동물을 품종을 분류하는 개체 분류부;동물 그룹의 특이적인 변이들의 비중복(non-redundant)세트가 정의되며, 해당 세트에 대한 피검 동물의 유전자 정보를 공지의 염기서열 분석 기술인 시퀀싱(sequencing) 및, 개체가 가지는 유전형의 다양성 분석 기술인 제노타이핑(genotyping) 방식으로 생성된 정보가 저장되고, 하나 이상의 동물에 대한 유전자 마커에 따라 분류되는 품종별 유전자 마커를 포함하는 유전자 정보가 저장되는 데이터 베이스;상기 검사 단말기로부터 피검 동물의 시료를 포함하는 유전자 검사결과를 입력받아, 상기 피검 동물의 시료로부터 도출되는 유전자 마커와, 상기 데이터 베이스를 참조하여 저장된 유전자 정보의 유전자 마커를 대조하는 마커 대조부; 및유전자 마커의 대조 결과에 따라, 상기 피검 동물의 유전자 정보에 포함된 하나 이상의 특이적 유전자 마커를 도출하여 상기 피검 동물에 대한 단일품종 또는 혼혈품종 여부를 포함하는 품종정보를 상기 검사 단말기에 회신하되, 상기 피검 동물이 혼혈품종일 경우, 존재하는 모든 특이적 유전자 마커에 해당하는 각 품종을 특정하여 상기 품종정보에 반영하고, 상기 피검 동물이 어느 품종 특이적인 유전자 마커를 보유하고 있는지 확인하여 가장 많은 품종 특이적 유전자 마커를 가진 품종을 상기 피검 동물의 품종으로 1개 이상 지정하고, 상기 피검 동물에 둘 이상의 특이적 유전자 마커의 조합이 존재하되, 상기 데이터 베이스에 존재하지 않는 경우, 상기 피검 동물에 대한 유전자 정보를 상기 데이터 베이스에 반영하는 품종 특정부를 포함하고,상기 품종정보를 판별하는 데 이용되는 유전적 마커는,단일염기 다형성(single nucleotide polymorphism), 삽입-결실(indel), 반복변이(copy number variants) 및 구조변이(structural variant) 중, 적어도 하나 또는 둘 이상을 조합하여 도출한 것인, 유전자 정보에 기반한 품종정보 제공 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

730/1150 Row 730: application_number: 1020200165592, combined_string: invention_title: 반려동물 사체 비대면 처리 통합관리 시스템 및 방법 abstract: 반려동물 사체 비대면 처리 통합관리 시스템 및 방법이 개시된다. 스마트 폰으로부터 동물 사체의 이미지 및 해당 위치 정보를 수신하는 이미지/위치 정보 수신 모듈; 상기 이미지/위치 정보 수신 모듈에서 수신된 이미지 및 위치 정보에 따라 동물 사체 신고를 접수하는 동물 사체 신고 접수 모듈; 동물 사체 수거 업체 단말로 해당 동물 사체에 대한 수거를 요청하는 동물 사체 수거 요청 모듈을 구성한다. 상술한 반려동물 사체 비대면 처리 통합관리 시스템 및 방법에 의하면, 동물 사체의 이미지와 정확한 위치 정보를 스마트 폰으로부터 수신하고, 자동으로 동물 사체 신고를 접수받도록 구성됨으로써, 동물 사체의 처리에 대한 행정적 처리가 명확해지고 체계화되는 효과가 있다. 또한, 이를 동물 수거 업체에 전달하여 즉시 수거하도록 구성됨으로써, 신속한 동물 사체 수거가 가능해지고 2차 사고가 뒤따르는 것을 방지할 수 있는 효과가 있다. claims: 스마트 폰(200)으로부터 동물 사체의 이미지 및 해당 위치 정보를 수신하는 이미지/위치 정보 수신 모듈(101);상기 이미지/위치 정보 수신 모듈(101)에서 수신된 이미지 및 위치 정보에 따라 동물 사체 신고를 접수하는 동물 사체 신고 접수 모듈(103);동물 사체 수거 업체 단말(300)로 해당 동물 사체에 대한 수거를 요청하는 동물 사체 수거 요청 모듈(109)을 포함하고,상기 이미지/위치 정보 수신 모듈(101)에서 수신된 이미지 및 위치 정보가 저장되는 이미지/위치정보 데이터베이스(102)를 더 포함하며,상기 동물 사체 신고 접수 모듈(103)에서 접수된 동물 사체의 이미지로부터 딥러닝을 이용하여 해당 동물을 자동 인식하는 딥러닝 동물 자동 인식 모듈(104),상기 딥러닝 동물 자동 인식 모듈(104)에서 자동 인식된 동물의 동물 사체를 미리 정해진 카테고리에 따라 자동 분류하는 동물 사체 분류 모듈(105)을 더 포함하고,상기 동물 사체 분류 모듈(105)에서 분류된 동물 사체에 대해 상기 카테고리에 따라 동물 사체 처리에 대한 과금을 수행하는 동물 사체 처리 과금 모듈(106),상기 동물 사체 처리 과금 모듈(106)의 과금에 대해 상기 스마트 폰(200)의 결제 처리를 수행하는 과금 결제 모듈(107)을 더 포함하며,상기 과금 결제 모듈(107)에서 결제 처리가 완료된 경우 상기 이미지/위치정보 데이터베이스(102)의 위치 정보를 참조하여 해당 동물 사체를 수거하기 위한 수거 동선을 산출하여 제공하는 동물 사체 수거 동선 산출 모듈(108)을 더 포함하고, 상기 동물 사체 신고 접수 모듈(103)에서 접수된 동물 사체 신고에 따른 동물 사체 처리 결과에 대해 통계 처리를 수행하는 동물 사체 처리 통계 모듈(109),상기 동물 사체 처리 통계 모듈(109)에서 수행된 통계 처리 결과가 저장되는 동물 사체 처리 통계 데이터베이스(111)를 더 포함하며,상기 이미지/위치 정보 수신 모듈(101)은 스마트 폰(200)의 카메라를 이용하여 동물 사체 이미지를 촬영하고,상기 스마트 폰(200)은 동물 사체만 촬영하는 것이 아니라 주변 공간을 포함한 파노라마 촬영을 안내하며,상기 위치 정보는 상기 스마트 폰(200)의 GPS 모듈이나 와이파이 모듈을 통해 자동으로 기록되고,상기 동물 사체 처리 과금 모듈(106)은 상기 동물 사체 분류 모듈(105)에서 분류된 동물 사체에 대한 카테고리에 따른 동물 사체의 평균적인 크기를 참조하여 과금을 수행하며,상기 동물 사체 수거 동선 산출 모듈(108)에 의해 산출된 수거 동선은 미리 알고 있는 동물 사체 수거 업체의 위치로부터 동물 사체까지의 동선이고,상기 동물 사체 처리 통계 모듈(110)의 동물 사체 처리 결과에 대한 통계 처리는 계절, 월, 휴일 여부, 일자, 시간대를 포함하는 시간적 요소를 포함하며,상기 동물 사체 수거 업체 단말(300)은 동물 사체를 수거 완료한 후 동물 장묘 업체 서버(400)에 접속하여 수거 완료된 동물 사체에 대한 장묘를 요청하는 것을 특징으로 하는 반려동물 사체 비대면 처리 통합관리 시스템., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

731/1150 Row 731: application_number: 1020200160404, combined_string: invention_title: ICT 융복합 축산환경 관제시스템 abstract: 개시되는 ICT 융복합 축산환경 관제시스템은, 복수의 축산농가에 각각 설치되는 도징 시스템;으로서, 외부로부터 가축에게 물을 공급하는 펌프;와, 상기 펌프에 의해 공급되는 물의 유량을 감지하는 유량센서;와, 상기 유량센서에 의해 감지된 유량정보에 따라 설정된 비율로 액상 사료첨가제를 공급하는 도징유닛;을 포함하는 도징 시스템; 상기 가축이 배출하는 분뇨 또는 가스로부터 악취를 측정하여 상기 악취정보를 생성하는 악취 측정부; 상기 도징유닛 및 상기 악취 측정부와 통신 가능하게 구비되며, 상기 축산농가 식별정보, 상기 설정된 비율, 누적음수량(L), 순시음 수량(L/hr), 누적 액상 사료첨가제 급이량(L), 도징유닛의 상태(RUN, STOP, ALARM)에 관한 정보를 포함하는 도징 시스템 정보 및 상기 악취정보를 포함하는 악취 측정부 정보를 수집하는 감시정보 수집부; 인터넷에 연결되어 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 송신하는 통신부; 상기 통신부로부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전달받아 저장하는 클라우드 서버; 및 상기 축산농가의 관리자가 인터넷을 통해 상기 클라우드 서버에 접근 가능하게 구비되는 관리자단말;을 포함한다. claims: 복수의 축산농가에 각각 설치되는 도징 시스템;으로서, 외부로부터 가축에게 물을 공급하는 펌프;와, 상기 펌프에 의해 공급되는 물의 유량을 감지하는 유량센서;와, 상기 유량센서에 의해 감지된 유량정보에 따라 설정된 비율로 액상 사료첨가제를 공급하는 도징유닛;을 포함하는 도징 시스템;상기 가축이 배출하는 분뇨 또는 가스로부터 악취를 측정하여 상기 악취정보를 생성하는 악취 측정부;상기 도징유닛 및 상기 악취 측정부와 통신 가능하게 구비되며, 상기 축산농가 식별정보, 상기 설정된 비율, 누적음수량(L), 순시음 수량(L/hr), 누적 액상 사료첨가제 급이량(L), 도징유닛의 상태(RUN, STOP, ALARM)에 관한 정보를 포함하는 도징 시스템 정보 및 상기 악취정보를 포함하는 악취 측정부 정보를 수집하는 감시정보 수집부;인터넷에 연결되고, 상기 감시정보 수집부와 통신가능하도록 연결되어 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 송신하는 통신부;상기 통신부로부터 상기 도징 시스템 정보 및 상기 악취 측정부 정보를 전달받아 저장하는 클라우드 서버; 및상기 축산농가의 관리자가 인터넷을 통해 상기 클라우드 서버에 접근 가능하게 구비되는 관리자단말;을 포함하는 ICT 융복합 축산환경 관제시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

732/1150 Row 732: application_number: 1020200156831, combined_string: invention_title: 반려동물의 훈육을 가이드하는 챗봇 시스템, 방법, 및 컴퓨터 프로그램 abstract: 챗봇 시스템의 반려동물 훈육 가이드 방법이 개시된다. 본 방법은, 반려동물의 훈육에 대한 가이드를 제공하도록 훈련된 복수의 인공지능 모델 중, 사용자 입력에 따라 선택된 반려동물의 행동에 대응되는 인공지능 모델을 식별하는 단계, 식별된 인공지능 모델을 기반으로, 선택된 행동을 수행하는 반려동물의 훈육에 대한 가이드를 제공하는 단계를 포함한다. claims: 챗봇 시스템의 반려동물 훈육 가이드 방법에 있어서,반려동물의 복수의 행동 중 적어도 하나의 행동을 선택하는 사용자 입력을 수신하는 단계;반려동물의 훈육에 대한 가이드를 제공하도록 훈련된 복수의 인공지능 모델 중, 상기 선택된 행동에 대한 훈육 지침을 기반으로 훈련된 인공지능 모델을 식별하는 단계; 및상기 식별된 인공지능 모델을 기반으로, 상기 선택된 행동을 수행하는 반려동물의 훈육에 대한 가이드를 제공하는 단계;를 포함하고,상기 가이드를 제공하는 단계는,상기 식별된 인공지능 모델의 출력을 기반으로 제1 단계의 훈육 가이드를 제공하고,상기 제공된 제1 단계의 훈육 가이드에 대한 사용자의 경과 보고가 수신된 경우, 상기 경과 보고가 입력된 상기 식별된 인공지능 모델의 출력을 기반으로 제2 단계의 훈육 가이드를 제공하고,상기 제공된 제1 단계의 훈육 가이드에 대한 사용자의 질문이 수신된 경우, 상기 질문이 입력된 상기 식별된 인공지능 모델의 출력을 기반으로 상기 질문에 대한 답변을 제공하고,상기 제공된 제1 단계의 훈육 가이드에 대하여 보충 설명을 요청하는 사용자 입력이 수신되면, 상기 제1 단계의 훈육 가이드와 관련된 적어도 하나의 시범 영상을 제공하고,상기 챗봇 시스템의 반려동물 훈육 가이드 방법은,반려동물의 특정한 행동을 교정하기 위한 서로 다른 복수의 훈육 지침 각각을 기반으로, 인공지능 모델들을 각각 독립적으로 훈련시키는 단계; 및상기 인공지능 모델들 각각을 통해 제공된 가이드에 대한 사용자들의 평가에 기초하여, 상기 복수의 훈육 지침 각각에 대한 스코어를 산출하는 단계;를 더 포함하는, 챗봇 시스템의 반려동물 훈육 가이드 방법.하나 이상의 인스트럭션을 저장하는 적어도 하나의 메모리; 및상기 하나 이상의 인스트럭션을 실행함으로써 제1항의 반려동물 훈육 가이드 방법을 수행하는 적어도 하나의 프로세서;를 포함하는, 시스템., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

733/1150 Row 733: application_number: 1020200140462, combined_string: invention_title: 반려동물 사료 및 간식 큐레이션 방법, 장치 및 이를 이용한 시스템 abstract: 본 발명은 본 발명은 반려동물 사료 및 간식 큐레이션 방법, 장치 및 이를 이용한 시스템에 관한 것으로서, SNS(Social Network service)로부터 반려동물이 섭취하는 사료 또는 간식과 관련된 비정형 피드 정보를 마이닝하는 단계, 상기 비정형 피드 정보를 가공하여 상기 비정형 피드 정보를 정형 피드 정보로 전처리하는 단계, 상기 구축된 피드 큐레이션 데이터베이스를 이용하여 상기 반려동물 정보에 따른 반려동물에 대한 피드를 매칭하는 단계를 포함할 수 있다. claims: 컴퓨팅 장치에 의해 수행되는 방법에 있어서,SNS(Social Network service)로부터 반려동물이 섭취하는 사료 또는 간식과 관련된 비정형 피드 정보를 마이닝하는 단계;상기 비정형 피드 정보를 가공하여 상기 비정형 피드 정보를 정형 피드 정보로 전처리하는 단계;상기 정형 피드 정보를 취합하여 피드 큐레이션 데이터베이스를 구축하는 단계;사용자 단말로부터 반려동물 정보를 입력받는 단계;상기 구축된 피드 큐레이션 데이터베이스를 이용하여 상기 반려동물 정보에 따른 반려동물에 대한 피드를 매칭하는 단계; 및상기 매칭된 피드를 상기 반려동물에게 추천하는 피드 큐레이션 정보를 상기 사용자 단말로 전송하는 단계를 포함하고,상기 반려동물이 섭취하는 사료 또는 간식과 관련된 비정형 피드 정보를 마이닝하는 단계는,상기 SNS에 접속하는 단계;상기 SNS의 컨텐츠가 이미지 또는 영상인 경우 상기 컨텐츠에 반려동물이 포함되고 상기 컨텐츠 내에서 상기 반려동물의 입 속 또는 입 주변에 물질이 존재하는 경우 상기 피드가 존재하는 것으로 판단하고, 상기 SNS의 컨텐츠가 텍스트인 경우 상기 컨텐츠에 반려동물에 관한 텍스트가 포함되고 상기 컨텐츠 내에서 상기 반려동물에 관한 텍스트에 미리 설정된 단어 간격 이내에 상기 피드가 존재하는 것으로 판단하는 단계;상기 피드가 존재한다는 판단한 결과에 기초하여 상기 SNS의 컨텐츠를 상기 비정형 피드 정보로 결정하는 단계;및상기 비정형 피드 정보로 결정된 상기 SNS의 컨텐츠를 크롤링하는 단계를 포함하며,상기 매칭된 피드를 상기 반려동물에게 추천하는 피드 큐레이션 정보를 상기 사용자 단말로 전송하는 단계는,상기 피드 큐레이션 정보의 신뢰도를 검증하는 단계를 더 포함하되,상기 피드 큐레이션 정보의 신뢰도를 검증하는 단계는,다른 사용자 단말로부터 상기 피드 큐레이션 정보에 대한 평가 정보를 수집하고, 상기 피드 큐레이션 정보에 대한 평가정보에 따라 상기 피드 큐레이션 정보에 대한 신뢰도를 산정하는 단계;상기 반려동물 정보를 입력한 사용자 단말로부터 입력된 희망 신뢰도 정보와 상기 피드 큐레이션 정보에 대한 신뢰도를 비교하는 단계; 및상기 피드 큐레이션 정보의 신뢰도가 상기 희망 신뢰도에 비해 높은 경우에만 상기 피드 큐레이션 정보를 상기 사용자 단말로 전송하는 단계를 포함하고,상기 비정형 피드 정보를 가공하여 상기 비정형 피드 정보를 정형 피드 정보로 전처리하는 단계는,상기 이미지 또는 영상 컨텐츠 및 텍스트로 이루어진 상기 비정형 피드 정보에 대하여 상기 반려동물의 품종, 생년월일, 성별 및 체중과, 관심 질병 및 관심 기능에 해당되는 특징을 라벨링하는 단계;상기 라벨링된 비정형 피드 정보의 속성을 기초로 클러스터링하여 유사도를 기초로 상기 비정형 피드 정보가 카테고라이징된 정형화 피드 정보를 출력하는 단계를 포함하고,상기 사용자 단말로부터 반려동물 정보를 입력받는 단계는,상기 반려동물의 품종, 생년월일, 성별 및 체중에 대한 필수 정보와 상기 반려동물의 관심 질병 및 관심 기능에 대한 선택 정보를 입력받는 단계를 포함하고,상기 구축된 피드 큐레이션 데이터베이스를 이용하여 상기 반려동물에 대한 피드를 매칭하는 단계는,상기 반려동물 정보를 기초로 품종별 유전질환, 필요 기능, 필요 원료/성분 및 급여량을 결정하는 단계;상기 결정된 품종별 유전질환, 필요 기능, 필요 원료/성분 및 급여량 정보와 상기 피드 큐레이션 데이터베이스에 저장된 피드 리스트를 비교하는 단계; 및상기 비교에 의해 매칭되는 데이터의 크기를 기준으로 상기 피드 리스트를 정렬하는 단계를 포함하고,상기 매칭된 피드를 상기 반려동물에게 추천하는 피드 큐레이션 정보를 상기 사용자 단말로 전송하는 단계는,상기 피드에 적합한 연령 정보, 크기 정보, 복수의 기능 정보와 상기 반려동물 정보가 매칭되는 데이터 크기가 가장 큰 피드에서부터 상기 피드에 적합한 연령 정보, 크기 정보, 복수의 기능 정보와 상기 반려동물 정보가 매칭되는 데이터 크기가 작아지는 순서로 상기 피드를 추천하는 단계를 포함하며,상기 반려동물의 정보와 상기 정형 피드 정보를 취합하여 피드 큐레이션 데이터 베이스를 구축하는 단계는,상기 반려동물의 분류, 연령, 견종크기, 희망 주요기능, 희망 주원료와 상기 피드의 브랜드, 상품명, 용량, 공급가, 온라인 평균 판매가, 소비자가, 정가, 프로모션 현황, 주요기능, 주원료, 함유성분, 제조 특징, 원산지, 전체 원료 구성, 급여량, 낱개 속포장 여부, 유통기한, 유사 검색어, 간략 설명으로 데이터를 분류하여 저장하는 단계;상기 연령을, 1년 미만의 퍼피, 1년 이상 7년 미만의 성견, 7년 이상의 노령견으로 분류하는 단계;상기 견종크기를, 품종에 따른 소형, 중형 및 대형으로 분류하는 단계;상기 주요기능을 면역력 향상, 소화력 증진, 치석 예방/제거, 관절/뼈 강화, 피부(모질) 개선, 다이어트, 눈 건강, 장기능 개선 및 호흡기 건강 개선으로 분류하는 단계; 및상기 피드에 적합한 몸무게 및 급여량을, 생년, 체중대비 급여횟수, 기초대사량, 1일 급여칼로리 및 1일 섭취량으로 분류하는 단계를 포함하는,반려동물 사료 및 간식 큐레이션 방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

734/1150 Row 734: application_number: 1020200140463, combined_string: invention_title: 반려동물 헬스 케어 큐레이션 방법, 장치 및 이를 이용한 시스템 abstract: 본 발명은 본 발명은 반려동물 헬스 케어 큐레이션 방법, 장치 및 이를 이용한 시스템에 관한 것으로서, SNS(Social Network service)로부터 반려동물의 행동 및 증상과 관련된 비정형 건강 정보를 마이닝하는 단계, 상기 비정형 건강 정보를 가공하여 상기 비정형 건강 정보를 정형 건강 정보로 전처리하는 단계, 상기 구축된 통합 건강 데이터베이스를 이용하여 상기 반려동물 정보에 따른 반려동물에 대한 진단 정보를 매칭하는 단계, 상기 반려동물에 대한 진단 정보를 기초로 상기 반려동물의 건강을 케어하는 관리 방안을 결정하는 단계, 및 상기 진단 정보, 상기 관리 방안, 및 상기 SNS로부터 실시간으로 수집된 상기 관리 방안에 따른 비용 정보가 포함된 헬스 케어 정보를 상기 사용자 단말로 전송하는 단계를 포함할 수 있다. claims: 컴퓨팅 장치에 의해 수행되는 방법에 있어서,SNS(Social Network service)로부터 반려동물의 행동 및 증상과 관련된 비정형 건강 정보를 마이닝하는 단계;상기 비정형 건강 정보를 가공하여 상기 비정형 건강 정보를 정형 건강 정보로 전처리하는 단계;상기 정형 건강 정보를 취합하여 통합 건강 데이터베이스를 구축하는 단계;사용자 단말로부터 반려동물 정보를 입력받는 단계;상기 구축된 통합 건강 데이터베이스를 이용하여 상기 반려동물 정보에 따른 반려동물에 대한 진단 정보를 매칭하는 단계;상기 반려동물에 대한 진단 정보를 기초로 상기 반려동물의 건강을 케어하는 관리 방안을 결정하는 단계; 및상기 진단 정보, 상기 관리 방안, 및 상기 SNS로부터 실시간으로 수집된 상기 관리 방안에 따른 비용 정보가 포함된 헬스 케어 정보를 상기 사용자 단말로 전송하는 단계를 포함하며,상기 반려동물의 행동 및 증상과 관련된 비정형 건강 정보를 마이닝하는 단계는,상기 SNS에 접속하는 단계; 및상기 SNS로부터 상기 반려동물과 상기 반려동물의 건강 상태에 대한 정보가 함께 포함된 미디어 컨텐츠 및 텍스트를 크롤링하는 단계를 포함하며,상기 비정형 건강 정보를 가공하여 상기 비정형 건강 정보를 정형 건강 정보로 전처리하는 단계는,상기 미디어 컨텐츠 및 텍스트로 이루어진 상기 비정형 건강 정보에 대하여 상기 반려동물의 부위 별 행동과, 상기 부위에 대한 증상으로 분류하고, 상기 반려동물의 부위 별 행동에 따른 이상 징후와 및 상기 부위에 대한 증상에 따른 이상 징후를 라벨링하는 단계; 및상기 라벨링된 비정형 건강 정보의 속성을 기초로 이상 징후를 클러스터링하여 상기 이상 징후의 유사도를 기초로 상기 비정형 건강 정보가 카테고라이징된 정형화 건강 정보를 출력하는 단계를 포함하고,상기 사용자 단말로부터 반려동물 정보를 입력받는 단계는,상기 반려동물의 부위 별 행동 및 상기 부위에 대한 증상을 입력받는 단계를 포함하고,상기 구축된 통합 건강 데이터베이스를 이용하여 상기 반려동물에 대한 진단 정보를 매칭하는 단계는,상기 반려동물의 부위 별 행동 및 상기 부위에 대한 증상을 상기 통합 건강 데이터베이스에 포함된 이상 징후와 비교하는 단계;상기 반려동물의 부위 별 행동 및 상기 부위에 대한 증상에 매칭되는 이상 징후 중에서 매칭되는 데이터의 크기를 기초로 이상 징후를 결정하는 단계; 및상기 이상 징후를 기초로 상기 반려동물에 적용되는 예상 질병을 결정하는 단계를 포함하고,상기 반려동물에 대한 진단 정보를 기초로 상기 반려동물의 건강을 케어하는 관리 방안을 결정하는 단계는,상기 예상 질병을 치료하는 지역별 예상 진료비를 제공하는 단계;상기 예상 질병이 예방 접종에 의해 치료되는 것으로 판단되는 경우 상기 예방 접종의 종류에 따른 지역별 예상 접종비 정보를 제공하는 단계; 및상기 반려동물의 상기 예상 질병을 치료한 후의 추천 사료를 제공하는 단계를 포함하고,상기 매칭된 진단 정보를 상기 반려동물에게 추천하는 헬스 케어 정보를 상기 사용자 단말로 전송하는 단계는,상기 반려동물의 부위 별 행동 및 상기 부위에 대한 증상에 매칭되는 이상 징후 중에서 매칭되는 데이터의 크기를 기준으로, 매칭되는 데이터 크기가 가장 큰 이상 징후에 해당되는 예상 질병을 가능성이 높은 예상 질병으로 표시하고, 상기 가능성이 높은 예상 질병보다 매칭되는 이상 징후의 데이터 크기가 작은 예상 질병을 가능성이 낮은 예상 질병으로 표시하는 단계를 포함하는,반려동물 헬스 케어 큐레이션 방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

735/1150 Row 735: application_number: 1020200133898, combined_string: invention_title: 가축 유도 시스템 abstract: 본 발명은 가축들을 지정된 장소로 무인으로 유도시켜 줌과 동시에 축사장 바닥을 청소하도록 구현한 가축 유도 시스템에 관한 것으로, 바닥 위에 위치하여 전측으로 이동시 바닥의 이물질을 청소하고, 후측으로 이동시 가축을 지정된 장소로 유도시키는 유도장치; 유도장치 양측에 연결되어 상하방향으로 이동시켜 주는 수직이동장치; 및 수직이동장치 상단에 연결되어 전후방향으로 이동시켜 주는 수평이동장치를 포함한다. claims: 바닥 위에 위치하여 전측으로 이동시 바닥의 이물질을 청소하고, 후측으로 이동시 가축을 지정된 장소로 유도시키는 유도장치;상기 유도장치 양측에 연결되어 상하방향으로 이동시켜 주는 수직이동장치; 및상기 수직이동장치 상단에 연결되어 전후방향으로 이동시켜 주는 수평이동장치를 포함하되,전측에 위치하여 가축이 통로에 들어오기 전 가축의 건강상태를 체크하는 건강체크기;전측 통로 입구에 위치하여 가축을 샤워해주는 샤워기; 및상기 샤워기에서 기 설정된 후측방향에 설치하여 가축을 건조하는 건조기를 포함하는 가축 유도 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

736/1150 Row 736: application_number: 1020200129621, combined_string: invention_title: IOT 반려동물용 스마트 식기 abstract: 본 발명의 일 실시예는 내부공간을 형성하며, 내측으로 함몰되는 제 1 수용부를 포함하는 본체부; 상기 제 1 수용부에 지지되며, 내측으로 함몰되는 제 2 수용부를 포함하는 지지부; 상기 제 2 수용부에 지지되며, 반려동물용 사료 또는 물이 수용되는 제 3 수용부를 포함하는 보울부; 상기 본체부의 내부공간에 마련되어, 상기 지지부, 상기 보울부 및 상기 보울부에 수용되는 반려동물용 사료 또는 물의 무게를 측정하는 무게센서부; 유저 단말; 상기 유저 단말과 통신할 수 있는 통신부; 및 상기 무게센서부에서 측정된 무게 정보로부터 반려동물에게 제공된 반려동물용 사료 또는 물의 양 또는 반려동물이 섭취한 사료 또는 물의 양을 산출하여 상기 유저 단말에 전송하는 제어부; 를 포함하고, 상기 보울부에서 유출된 물이 상기 제 1 수용부 내부에 수용될 수 있도록, 상기 제 2 수용부는 상기 제 1 수용부로부터 소정거리 이격되어 지지되는 것을 특징으로 하는, IOT 반려동물용 스마트 식기를 제공한다. claims: 내부공간을 형성하며, 내측으로 함몰되는 제 1 수용부를 포함하는 본체부;상기 제 1 수용부에 지지되며, 내측으로 함몰되는 제 2 수용부를 포함하는 지지부;상기 제 2 수용부에 지지되며, 반려동물용 사료 또는 물이 수용되는 제 3 수용부를 포함하는 보울부;상기 본체부의 내부공간에 마련되어, 상기 지지부, 상기 보울부 및 상기 보울부에 수용되는 반려동물용 사료 또는 물의 무게를 측정하는 무게센서부; 반려동물용 사료 또는 물을 제공하는 유저의 단말과 통신할 수 있는 통신부; 및상기 무게센서부에서 측정된 무게 정보로부터 반려동물에게 제공된 반려동물용 사료 또는 물의 양 또는 반려동물이 섭취한 사료 또는 물의 양을 산출하여 상기 통신부를 통하여 유저의 단말에 전송하는 제어부; 를 포함하고,상기 보울부에서 유출된 물이 상기 제 1 수용부 내부에 수용될 수 있도록, 상기 제 2 수용부는 상기 제 1 수용부로부터 소정거리 이격되어 지지되고,상기 제 1 수용부의 하단에는 상기 본체부의 내부공간과 연통하는 개구가 형성되고,상기 개구의 둘레를 따라 상측으로 돌출되는 제 1 격벽이 형성되고,상기 제 2 수용부의 하단에는 상기 개구를 관통하여 상기 본체부의 내부공간과 연통하는 돌출홈이 형성되고,상기 무게센서부는 상기 돌출홈과 결합하고,상기 제 1 수용부 내부에 수용된 물이 상기 본체부 외측으로 흐를 수 있도록 상기 제 1 수용부에는 상기 본체부를 관통하는 배수구가 형성되고,상기 제 1 수용부는, 그 상단부 둘레를 따라 상측으로 돌출하는 제 2 격벽을 포함하고,상기 보울부에서 유출된 물이 상기 제 1 수용부 내부로 흐를 수 있도록, 상기 제 2 격벽의 외주면 둘레에는 관통유로가 형성되는 것을 특징으로 하는, IOT 반려동물용 스마트 식기., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

737/1150 Row 737: application_number: 1020200126788, combined_string: invention_title: 정자의 동결보존제 스트레스 저항성 판별용 조성물 abstract: 본 발명은 동결보존제 스트레스 저항성 정자와 민감성 정자간의 NT5C1B, FH, CAPZB, VDAC2, 및 UQCRC1 단백질 발현 수준에 차이가 있음을 확인하여, 상기 단백질을 동결보존제 스트레스 저항성 마커로 제공하고, 상기 마커의 발현을 측정하는 물질을 포함하는 동결보존제 스트레스 저항성 판별용 조성물 등을 제공하는 것으로서, 본 발명의 제공에 의해 가축인공수정시 동결정액의 품질평가에 소요되는 비용 및 시간을 절감할 수 있고, 동결보존제에 의해 운동성, 생존성, 및 수정능획득이 저하되지 않는 고품질의 정자를 선별하여 인공수정의 성공률을 높이고 그 비용을 절감할 수 있을 것으로 기대된다. claims: NT5C1B (Cytosolic 5’-Nucleotidase 1B), CAPZB (F-actin-capping protein subunit beta), VDAC2 (Voltage-dependent anion-selective channel protein 2), UQCRC1 (Cytochrome b-c1 complex subunit 1), 및 FH (Fumarate hydratase)로 이루어진 군으로부터 선택되는 하나 이상의 동결보존제 스트레스 저항성 마커, 상기 마커를 코딩하는 유전자, 또는 상기 유전자의 mRNA를 검출하는 물질을 유효성분으로 포함하는 것을 특징으로 하는, 정자의 동결보존제 스트레스 저항성 판별용 조성물.제4항에 있어서,상기 동결보존제는 TYB(tris-egg yolk buffer) 및 글리세롤(glycerol); 폼아마이드(fomamide); 프로판디올(propanediol); DMSO(Dimethyl sulfoxide); 및 아도니톨(adonitol)로 이루어지는 군으로부터 선택되는 하나 이상을 포함하는 것을 특징으로 하는, 동결보존제 스트레스 저항성 정자를 판별하기 위한 정보제공방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

738/1150 Row 738: application_number: 1020200127111, combined_string: invention_title: 가축의 발정기 정보 획득 시스템 및 방법 abstract: 본 발명은 개체 정보 획득 및 표시 시스템 및 방법에 관한 것으로서, 센서-통신망 구축을 통하여 광활한 초지에서 방목하는 가축으로부터 각각의 개별 생체정보 및 위치정보를 효과적으로 취득하고, 그 정보를 가축에 부착된 표시부에 표시함으로써 가축의 관리에 효과적으로 활용할 수 있는 개체 정보 획득/표시 시스템 및 방법에 관한 것이다. 또한 본 발명은 가축의 발정기, 수정, 분만에 관한 정보를 효과적으로 취득하고 이를 표시부에 표시하여 육안식별 가능한 장치를 제공한다. claims: 둘 이상의 개체로부터 그 생체정보 및 위치정보를 포함하는 개체 정보를 획득하는 시스템에 있어서,각 개체의 질 내와 외부에 걸쳐 장착되어 개체의 생체정보를 획득하는 제1 식별장치;각 개체의 체외에 부착되어 개체의 위치정보를 획득하고, 상기 제1 식별장치가 획득한 생체정보를 수신하여 개체의 생체정보 및 위치정보를 포함하는 개체 정보를 획득하는 제2 식별장치;상기 제2 식별장치들로부터 개체의 생체정보 및 위치정보를 수신하는 중계기 네트워크;를 포함하여 구성되며,상기 제1 식별장치는,개체의 질 내에 삽입 안착되어, 개체의 발정기, 수정, 분만에 관련된 정보를 수집하는 본체부;개체의 체외에 노출되어 상기 본체부로부터 수집된 생체 정보를 이용하여 상기 개체의 발정기, 수정, 분만에 관련된 정보를 표시하는 표시부;상기 본체부와 표시부를 연결하여 본체부로부터 표시부로 데이터와 전력을 송신하는 연결부;를 포함하여 구성되며,상기 표시부와 본체부는 연결부를 통하여 상호 연결된 상태로, 상기 본체부는 개체의 질 내에 삽입/안착되고, 상기 표시부는 체외로 노출되며,상기 제2 식별장치는 다른 개체의 제2 식별장치로부터 상기 다른 개체의 생체정보 및/또는 위치정보를 추가로 수신하는 것을 특징으로 하며, 상기 생체정보는 개체의 발정, 수정, 분만에 관련된 정보인 것을 특징으로 하는 개체 정보 획득 시스템.가축의 발정기, 수정, 분만에 관련된 생체정보를 수집하는 생체정보 수집장치로서, 가축의 질 내에 삽입 안착되어, 가축의 발정기, 수정, 분만에 관련된 생체 정보를 수집하는 본체부;가축의 체외에 노출되어 상기 본체부로부터 수집된 생체 정보를 이용하여 상기 가축의 발정기, 수정, 분만에 관련된 정보를 표시하는 표시부;상기 본체부와 표시부를 연결하여 본체부로부터 표시부로 데이터와 전력을 송신하는 연결부;를 포함하여 구성되며,상기 표시부와 본체부는 연결부를 통하여 상호 연결된 상태로, 상기 본체부는 가축의 질 내에 삽입/안착되고, 상기 표시부는 체외로 노출되는 것을 특징으로 하고,상기 본체부는,가축의 질 내부의 영상/열영상을 취득하는 센서모듈; 및 상기 센서모듈의 외부에 노출되어 상기 질 내의 온도, 분비물의 PH, 전기 전도도, 농도를 측정하는 센서감지부; 를 포함하여 구성되어, 상기 취득한 질 내부의 영상/열영상과 상기 측정된 질 내의 온도, 분비물의 PH, 전기 전도도, 농도를 기반으로 가축의 발정기, 수정, 분만에 관련된 생체정보를 수집하는 것을 특징으로 하는 생체정보 수집 장치.둘 이상의 개체로부터 그 생체정보 및 위치정보를 포함하는 개체 정보를 획득하는 방법에 있어서,개체의 질 내로 제1 식별장치의 본체부를 삽입 안착하고 안착시켜 개체의 발정기, 수정, 분만에 관련된 체내 생체정보를 획득하는 생체정보 획득단계;수집한 생체정보를 근거로 표시 이벤트를 판정하는 이벤트 판정단계;상기 판정된 이벤트 정보를 상기 제1 식별장치의 본체부로부터 연장되어 개체의 체외로 노출된 표시부로 전송하는 이벤트 정보 전송단계;상기 판정된 이벤트 정보를 상기 개체의 질 내에 삽입 안착된 본체부와 연결되어 체외로 노출된 표시부에서 시각적으로 표시하는 생체정보 표시단계;개체의 체외에 부착되는 제2 식별장치가 개체의 위치정보를 획득하고, 상기 제1 식별장치로부터 개체의 생체정보를 수신 받아, 개체의 생체정보 및 위치정보를 포함하는 개체 정보를 생성하는 개체 정보 생성단계;상기 생성한 개체 정보를 중계기 네트워크로 전송하는 개체 정보 전송단계;를 포함하며,상기 개체 정보 전송단계는, 상기 제2 식별장치가 다른 개체의 제2 식별장치로부터 다른 개체의 개체 정보를 수신하여 이를 전송하는 단계를 추가로 포함하며, 상기 제1 식별장치가 획득하는 생체정보는 개체의 발정, 수정, 분만에 관련된 정보인 것을 특징으로 하는 개체 정보 획득 및 표시 방법.가축의 체내에서 생체정보를 수집하고 이를 시각적으로 표시하는 방법으로서, 가축의 질 내로 제1 식별장치를 삽입하고 상기 제1 식별장치를 통해 질 내부의 영상/열영상 및 온도, 분비물의 PH, 전기 전도도, 농도 데이터를 획득하여 이를 바탕으로 체내 생체정보를 수집하는 생체정보 수집단계;수집한 생체정보를 근거로 표시 이벤트를 판정하는 이벤트 판정 단계;상기 판정된 이벤트 정보를 시각적으로 표시하는 시각표시 단계;상기 생체정보 수집단계에서 수집된 생체정보를 가축의 체외에 부착된 제2 식별장치를 통하여 서버로 전송하는 생체정보 전송단계;를 포함하여 이루어지며,상기 이벤트 판정단계는 제2 식별장치에서 진행되며,상기 시각표시 단계는, 상기 제2 식별장치의 표시부에 상기 판정된 이벤트 정보를 시각적으로 표시하는 것; 을 특징으로 하는 생체정보 수집 및 표시 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

739/1150 Row 739: application_number: 2020200003500, combined_string: invention_title: 폭식방지용 반려동물 식기 abstract: 본 고안은 반려동물, 특히 반려견의 성장속도와 적정 식사량에 맞는 사료를 담을 수 있는 여러 용량(예: 대, 중, 소 용량)의 식기를 키트형으로 제공하고, 이들 식기를 측면 배열, 적층 배열, 삽입 배열 하는 등의 방식으로 다양하게 배열하며, 체결수단에 의하여 배열형태를 고정할 수 있어 반려동물의 관심을 높이고 미감도 향상시킬 수 있으며, 무엇보다도 성장속도 및 적정성에 맞는 식사를 제공하여 폭식방지 효과를 얻을 수 있는 반려동물 식기에 관한 것이다.본 고안에 따른 폭식방지용 반려동물 식기는 대용량 제1보울; 및 상기 제1보울의 측면형상에 상응하는 측면형상을 갖거나, 상기 제1보울의 상면 또는 하면 형상에 상응하는 상면 또는 하면 형상을 가져 측면 또는 상하면 접촉 배열되는 소용량 제2보울;을 포함하여 이루어진다. claims: 대용량 제1보울; 및상기 제1보울의 측면형상에 상응하는 측면형상을 갖거나, 상기 제1보울의 상면 또는 하면 형상에 상응하는 상면 또는 하면 형상을 가져 측면 또는 상하면 접촉 배열되는 소용량 제2보울;을 포함하여 이루어지되,제1보울과 제2보울은 상하면 접촉 배열되고,상하면 인접 배열되는 제1 및 제2 보울, 또는 제2보울 및 제2보울은 상호 체결수단을 갖고,상기 체결수단은 상하 배열된 제2 및 제1 보울의 접면에 구비된 체결유닛으로 구성되고, 이 체결유닛은제2보울에 구비되는 제1블록과, 제1보울에 구비되어 상기 제1블록이 인입되는 인입홀이 형성된 제2블록, 상기 제1블록 내에 구비되어 상기 인입홀에 형성된 끼움홈으로 돌출되어 고정되는 한 쌍의 고정팔 및 상기 제1블록 내부에서 승하강하여, 상기 한 쌍의 고정팔 후퇴를 제한하는 승하강봉돌을 포함하여 이루어지고,상기 제1블록이 상기 인입홀에 인입되면, 상기 승하강봉돌이 하강하여 상기 한 쌍의 고정팔을 양측으로 돌출시킴에 따라, 상기 고정팔이 상기 끼움홈에 내삽 되어 제1블록을 제2블록에 고정하고,상기 하강한 승하강봉돌이 상기 한 쌍의 고정팔 사이에 위치하여 상기 고정팔이 후퇴를 제한하여 상기 제1블록과 제2블록의 고정 상태를 유지하고,상기 제1블록 하부에는 상기 승하강봉돌 하면에 밀착되며 복귀스프링을 포함하는 복귀부재가 구비되어,상기 복귀스프링의 탄성력에 의해 상기 복귀부재가 상기 승하강봉돌의 하면을 타격하여 승하강봉을 상승시키면, 상기 고정팔의 후퇴를 허용하여 상기 제1블록을 제2블록으로부터 분리시킬 수 있도록 이루어지는 것을 특징으로 하는 폭식방지용 반려동물 식기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

740/1150 Row 740: application_number: 1020200114349, combined_string: invention_title: 동물약국 중개 시스템 및 서비스 방법 abstract: 본 발명은 동물약국 중개 시스템 및 서비스 방법에 관한 것이다. 개시된 동물약국 중개 시스템 및 서비스 방법에 따르면, 반려동물을 키우는 소비자와 동물약국을 연결하는 동물약국 중개 시스템에 있어서, 반려동물을 키우는 동물약 소비자가 주변 동물약국에 동물약을 주문하기 위한 소비자단말, 반려동물 약을 보유하고 있는 약국에서 보유하고 있는 동물약 정보를 저장하고 있는 약국단말 및 상기 소비자단말의 위치, 구매약정보 및 약국단말를 매칭하여 동물약국 중개 서비스를 제공하는 동물약국 중개서버를 포함하는 것을 특징으로 하는 동물약국 중개 시스템 및 서비스 방법을 제공한다. 본 발명에 의하면, 반려동물 가족과 동물약국을 연결하는 플랫폼으로 동물약 정보를 공유하여, 소비자 측면에서 손쉽게 동물약을 구입해서 간단한 치료 및 예방에는 비용 부담이 없도록 하고, 동물약국 측면에서는 주변 소비자들이 원하는 동물약에 대한 정보를 지속적으로 얻어, 재고 부담없이 약을 적극적으로 판매할 수 있도록 한다는 이점이 있다. claims: 반려동물을 키우는 소비자와 동물약국을 연결하는 동물약국 중개 시스템에 있어서,반려동물을 키우는 동물약 소비자가 주변 동물약국에 동물약을 주문하기 위한 소비자단말;반려동물의 약을 보유하고 있는 약국에서 보유하고 있는 동물약 정보를 저장하고 있는 약국단말; 및 상기 소비자단말의 위치, 구매약정보 및 약국단말을 매칭하여 동물약국 중개 서비스를 제공하는 동물약국 중개서버를 포함하고, 상기 약국단말은, 약국에서 보유하고 있는 약정보를 저장하는 보유 약정보 저장부; 상기 동물약국 중개서버로부터 요청받은 약과 동등한 효과를 가지는 대체약에 대한 정보를 저장하여 보유약의 재고가 없는 경우 이를 대체하여 제공할 수 있도록 하는 대체 약정보 저장부; 상기 보유 약정보 저장부 및 상기 대체 약정보 저장부에 저장되어 있는 약의 보유량 정보를 저장하는 재고관리부; 상기 동물약국 중개서버와 정보를 주고 받기 위한 유무선통신부인 통신부; 및 소비자가 약사로부터 복약지도를 제대로 받을 수 없는 경우를 대비하여, 상기 보유 약정보 저장부 및 상기 대체 약정보 저장부에 저장되어 있는 약에 대한 복약정보를 저장하고 있다가 상기 소비자단말에 제공하는 복약정보 저장부를 포함하고, 상기 재고관리부는, 상기 재고관리부에 상기 동물약국 중개서버로부터 요청된 약에 대한 재고가 없거나, 유행병에 따라 특정약에 대한 추가적인 분량이 요구되는 것으로 예측되는 경우, 제약회사서버에 해당약에 대한 조달요청 정보를 전송하는 것을 특징으로 하는 동물약국 중개 시스템., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

741/1150 Row 741: application_number: 1020200112031, combined_string: invention_title: 반려동물 행동 인식 시스템 및 그 제어방법 abstract: 본 발명은 반려동물 행동 인식 시스템 및 그 제어방법에 관한 것으로서, 반려동물 소유주가 반려동물에 행동에 따라 신속한 대응을 할 수 있도록 함을 목적으로 한 것이다.즉, 본 발명은 반려동물의 행동영상을 통하여 반려동물의 특이행동 이유를 반려동물 소유주에게 알려주는 반려동물 행동 인식 시스템을 구비하되, 상기 반려동물 행동 인식 시스템은 반려동물의 행동분석을 위한 어플이 구비되어 있게 구성한 스마트폰과 상기 스마트폰에 구비되어 소유주의 조작에 따라 반려동물의 행동을 분석할 수 있게 실행되는 반려동물행동분석어플 및 상기 스마트폰에 네트워크를 통하여 전송된 반려동물의 행동정보를 분석하여 분석된 결과를 스마트폰에 구비된 반려동물행동분석어플을 통하여 제공하는 반려동물행동분석서버로 구성한 것을 특징으로 하는 것이다.따라서, 본 발명은 반려동물 소유주가 반려동물에 행동에 따라 신속한 대응을 통하여 반려동물이 올바른 생활습관을 가지게 되는 효과와 반려동물과 소유주가 빠른시간 안정된 가족을 이루게 되는 효과를 갖는 것이다. claims: 반려동물의 행동영상을 통하여 반려동물의 특이행동 이유를 반려동물 소유주에게 알려주는 반려동물 행동 인식 시스템을 구비하되,상기 반려동물 행동 인식 시스템은 반려동물의 행동분석을 위한 어플이 구비되어 있게 구성한 스마트폰과 상기 스마트폰에 구비되어 소유주의 조작에 따라 반려동물의 행동을 분석할 수 있게 실행되는 반려동물행동분석어플 및 상기 스마트폰에 네트워크를 통하여 전송된 반려동물의 행동정보를 분석하여 분석된 결과를 스마트폰에 구비된 반려동물행동분석어플을 통하여 제공하는 반려동물행동분석서버로 구성하고;상기 반려동물행동분석어플은 스마트폰의 바탕화면에 디스플레이되어 소유주 반려동물행동분석어플을 실행할 수 있게 구비한 반려동물행동분석아이콘과 상기 반려동물행동분석아이콘의 터치에 따라 소유주가 반려동물행동분석을 진행할 수 있게 팝업되는 반려동물행동촬영창, 상기 반려동물행동촬영창에 반려동물의 행동을 촬영할 수 있게 구비되는 반려동물행동촬영버튼, 상기 반려동물행동촬영창에 반려동물행동촬영버튼의 조작에 따라 반려동물행동영상이 취득되면 소유주가 반려동물행동분석을 위하여 행동분석을 실행하는 행동분석실행버튼, 상기 행동분석실행버튼에 따라 실행되는 반려동물의 행동분석을 위하여 반려동물환경정보를 입력할 수 있게 팝업되는 반려동물환경정보창부, 상기 반려동물환경정보창부를 통한 반려동물환경정보의 입력완료에 따라 반려동물행동영상 및 반려동물환경정보를 네트워크를 통하여 전송받은 반려동물행동분석서버가 반려동물행동에 따라 분석하여 전송한 정보를 표시할 수 있게 팝업되는 반려동물행동분석창, 상기 반려동물행동분석창을 통하여 제공된 분석정보에 따라 소유주가 반려동물에게 조치할 분석정보의 선택에 따라 조치 영상을 촬영할 수 있게 팝업되는 조치영상촬영창 및 상기 조치영상촬영창을 통하여 촬영 취득된 조치영상을 촬영완료에 따라 반려동물행동분석서버로 전송하는 조치영상전송부로 구성하며;상기 반려동물행동분석서버는 네트워크를 통한 소유주의 접속을 관리할 수 있게 구비한 접속관리부와 행동분석대상 반려동물의 소유주로부터 전달된 반려동물의 행동영상정보와 반려동물의 환경정보를 축적된 행동분석데이터와 비교연산하여 반려동물의 행동에 따른 대응정보를 제공할 수 있게 구비한 반려동물행동분석부, 상기 반려동물행동분석부로부터 제공된 행동분석정보를 소유주에게 전달하는 반려동물행동분석정보제공부, 반려동물행동분석서버로부터 제공된 행동분석정보와 현재 반려동물의 행동상태와 일치 여부를 소유주가 체크한 정보를 분석하여 저장할 수 있게 구비한 반려동물행동피드백분석부 및 반려동물행동별 분석정보가 저장되고 소유주로부터 피드백된 데이터가 저장할 수 있게 구비한 반려동물행동분석데이터부로 구성한 것을 특징으로 하는 반려동물 행동 인식 시스템.반려동물 행동 인식 시스템의 제어방법은 스마트폰에 구비된 반려동물행동분석아이콘의 클릭에 따라 반려동물행동분석을 위한 반려동물행동촬영창이 팝업되는 반려동물행동분석실행과정과 상기 반려동물행동분석실행과정을 통하여 팝업된 반려동물행동촬영창의 반려동물행동촬영버튼의 클릭을 통하여 반려동물의 행동을 촬영하는 반려동물행동촬영과정, 반려동물행동촬영과정을 통하여 촬영된 행동영상을 반려동물행동분석서버로 전송하는 반려동물행동분석의뢰과정, 상기 스마트폰으로부터 전송된 영상을 반려동물행동분석데이터부와 비교연산하여 반려동물의 행동을 분석하는 반려동물행동분석과정, 상기 반려동물행동분석과정을 통하여 분석된 3가지 이상의 분석결과를 의뢰자의 스마트폰으로 전송하는 반려동물행동분석결과제공과정, 상기 반려동물행동분석결과제공과정을 통하여 반려동물행동분석창에 표시된 분석결과에 따라 알맞은 조치사항을 반려동물에게 실행하는 반려동물분석조치실행과정, 상기 반려동물분석조치실행과정을 통하여 반려동물에게 알맞은 조치를 실행하는 과정을 촬영하는 반려동물분석조치실행촬영과정, 상기 반려동물분석조치실행과정을 통하여 반려동물행동에 알맞은 조치의 실행항목을 선택표시하는 반려동물분석일치체크과정, 상기 반려동물분석일치체크과정을 통하여 알맞은 조치에 해당하는 조치영상을 반려동물행동분석서버로 제공하는 반려동물조치영상제공과정 및 상기 스마트폰으로부터 전달된 반려동물 조치결과를 반려동물행동분석데이터부에 저장하여 반려동물행동과 그 조치실행을 학습하는 반려동물행동학습과정으로 이루어지고;상기 반려동물행동분석의뢰과정의 실행과 연동하여 반려동물의 환경정보를 반려동물행동분석서버로 제공할 수 있게 반려동물의 환경정보를 입력하는 반려동물행동정보제공과정으로 이루어지며;상기 반려동물행동정보제공과정은 날씨정보입력창을 통하여 현재의 기상정보와 온도 및 습도의 정보를 입력하는 날씨정보입력단계와 사육정보입력창을 통하여 반려동물의 사용장소와 반려동물의 집 종류를 입력하는 사육정보입력단계, 취식입력창을 통하여 반려동물의 취식하는 사료종류와 취식횟수를 입력하는 취식입력단계, 배변습관입력창을 통하여 반려동물의 배변 횟수와 배변장소 정보를 입력하는 배변습관입력단계로 이루어지는 것을 특징으로 하는 반려동물 행동 인식 시스템의 제어방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

742/1150 Row 742: application_number: 1020200108851, combined_string: invention_title: 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 방법과 그 시스템 abstract: [기술분야/해결과제]본 발명은 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 방법과 그 시스템에 관한 것으로, 반려동물의 홍채 이미지 정보와 반려동물정보(소유주, 연락처, 반려동물의 종류, 이름, 나이, 암수, 특징 등)를 데이터화하여 대용량 서버에 등록 및 공개함으로써, 반려동물의 홍채 인식을 통해 반려동물정보를 실시간으로 추적 및 확인이 가능하고 유기를 방지할 수 있다.[해결수단]본 발명에 의한 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 시스템은, 반려동물의 양쪽 눈과 코 부분을 촬영하여 반려동물관리 앱을 통해 반려동물의 홍채 이미지와, 소유주, 연락처, 반려동물의 종류, 이름, 나이, 암수, 특징을 포함하는 반려동물정보를 중앙관제센터의 서버에 전송하여 등록하고, 상기 반려동물관리 앱의 사용자 인터페이스를 통해, 자신이 등록한 반려동물의 정보를 수정 및 삭제하고, 주변의 동물병원, 애견카페, 동물호텔을 검색하고 반려동물 도우미를 호출하며, 반려동물의 분실 및 유기시 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고 분실 또는 유기된 반려동물을 등록하는 회원가입자의 PC 또는 스마트폰; 상기 반려동물관리 앱을 인터넷 망을 통해 제공하고, 상기 회원가입자의 PC 또는 스마트폰으로부터 수신받은, 상기 반려동물의 홍채 이미지와 반려동물정보를 데이터베이스에 등록하고, 상기 반려동물관리 앱을 통해 반려동물의 검색 요청이 들어오면 수신된 반려동물의 홍채 이미지와 데이터베이스에 등록된 반려동물의 홍채 이미지를 종별로 분류된 패턴 알고리즘 분석을 통해 자동으로 비교 분석하여 홍채가 일치한 반려동물의 반려동물정보를 제공하고, 분실 또는 유기된 반려동물의 이미지나 영상 정보, 반려동물정보를 수신받아 유기동물 리스트에 등록하는 중앙관제센터의 서버; 상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 반려동물을 검색하거나, 또는 상기 중앙관제센터의 서버에 반려동물의 양쪽 눈과 코 부분을 촬영한 반려동물의 홍채 이미지를 전송하여 반려동물의 검색을 요청하여 검색 결과를 확인하고, 검색한 반려동물에 대한 병원치료내역을 포함한 부가정보를 입력하여 등록하며, 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고, 분실 또는 유기된 반려동물을 등록하는 동물병원, 동물보호센터, 애견카페를 포함한 관련업체의 PC 또는 스마트폰; 및 상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고, 분실 또는 유기된 반려동물을 등록하는 비회원의 PC 또는 스마트폰;을 포함한다.[기대효과]본 발명에 따르면, 반려동물의 홍채 이미지를 데이터화하여 대용량 서버에 저장하고 데이터를 분산 처리함으로써, 반려동물의 홍채 인식을 통해 반려동물의 소유주와 연락처를 파악할 수 있고 동물의 유기를 방지할 수 있는 효과가 있다. claims: 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 방법에 있어서,(a) 회원가입자의 PC 또는 스마트폰에서 중앙관제센터의 서버로부터 다운로드 받은 반려동물관리 앱을 통해, 반려동물의 양쪽 눈과 코 부분을 촬영한 반려동물의 홍채 이미지와, 소유주, 연락처, 반려동물의 종류, 이름, 나이, 암수, 특징을 포함하는 반려동물정보를 상기 중앙관제센터의 서버에 전송하여 반려동물을 등록하는 단계;(b) 상기 중앙관제센터의 서버에서 상기 회원가입자의 PC 또는 스마트폰으로부터 수신받은, 상기 반려동물의 홍채 이미지와 반려동물정보를 데이터베이스에 등록하여 인터넷으로 정보를 공유하는 단계;(c) 동물병원, 동물보호센터, 애견카페를 포함한 관련업체의 PC 또는 스마트폰에서 상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 반려동물을 검색하거나, 또는 반려동물의 양쪽 눈과 코 부분을 촬영한 반려동물의 홍채 이미지를 전송하여 상기 중앙관제센터의 서버에 등록된 반려동물의 검색을 요청하는 단계;(d) 상기 중앙관제센터의 서버에서 상기 관련업체의 PC 또는 스마트폰으로부터 수신받은 반려동물의 홍채 이미지와 데이터베이스에 등록된 반려동물의 홍채 이미지를 종별로 분류된 패턴 알고리즘 분석을 통해 자동으로 비교 분석하여 홍채가 일치한 반려동물의 반려동물정보를 검색하여 제공하는 단계; 및(e) 상기 관련업체의 PC 또는 스마트폰에서 상기 중앙관제센터의 서버로부터 제공받은 반려동물정보를 확인하고 병원치료내역을 포함한 부가정보를 입력하여 등록하는 단계;를 포함하는 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 방법.반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 시스템에 있어서,반려동물의 양쪽 눈과 코 부분을 촬영하여 반려동물관리 앱을 통해 반려동물의 홍채 이미지와, 소유주, 연락처, 반려동물의 종류, 이름, 나이, 암수, 특징을 포함하는 반려동물정보를 중앙관제센터의 서버에 전송하여 등록하고, 상기 반려동물관리 앱의 사용자 인터페이스를 통해, 자신이 등록한 반려동물의 정보를 수정 및 삭제하고, 주변의 동물병원, 애견카페, 동물호텔을 검색하고 반려동물 도우미를 호출하며, 반려동물의 분실 및 유기시 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고 분실 또는 유기된 반려동물을 등록하는 회원가입자의 PC 또는 스마트폰;상기 반려동물관리 앱을 인터넷 망을 통해 제공하고, 상기 회원가입자의 PC 또는 스마트폰으로부터 수신받은, 상기 반려동물의 홍채 이미지와 반려동물정보를 데이터베이스에 등록하고, 상기 반려동물관리 앱을 통해 반려동물의 검색 요청이 들어오면 수신된 반려동물의 홍채 이미지와 데이터베이스에 등록된 반려동물의 홍채 이미지를 종별로 분류된 패턴 알고리즘 분석을 통해 자동으로 비교 분석하여 홍채가 일치한 반려동물의 반려동물정보를 제공하고, 분실 또는 유기된 반려동물의 이미지나 영상 정보, 반려동물정보를 수신받아 유기동물 리스트에 등록하는 중앙관제센터의 서버;상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 반려동물을 검색하거나, 또는 상기 중앙관제센터의 서버에 반려동물의 양쪽 눈과 코 부분을 촬영한 반려동물의 홍채 이미지를 전송하여 반려동물의 검색을 요청하여 검색 결과를 확인하고, 검색한 반려동물에 대한 병원치료내역을 포함한 부가정보를 입력하여 등록하며, 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고, 분실 또는 유기된 반려동물을 등록하는 동물병원, 동물보호센터, 애견카페를 포함한 관련업체의 PC 또는 스마트폰; 및상기 중앙관제센터의 서버로부터 다운로드 받은 상기 반려동물관리 앱을 통해, 상기 중앙관제센터의 서버에 등록된 유기동물을 검색 및 조회하고, 분실 또는 유기된 반려동물을 등록하는 비회원의 PC 또는 스마트폰;을 포함하는 반려동물 생체인식을 통한 빅데이터 및 보호 통합 플랫폼 구축 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

743/1150 Row 743: application_number: 1020200105449, combined_string: invention_title: 반려 동물의 정보를 제공하는 방법 및 디바이스 abstract: 반려 동물의 정보를 제공하는 방법에 있어서, 상기 반려 동물의 상태 정보, 특성 정보 및 돌봄 히스토리 정보를 획득하는 단계; 공개 설정에 따라 상기 상태 정보, 상기 특성 정보 및 돌봄 히스토리 정보를 외부 디바이스에 제공하는 단계; 및 상기 상태 정보에 따라 사용자 단말의 위치 정보를 상기 반려 동물의 위치 정보로 상기 외부 디바이스에 제공하는 단계;를 포함하는 방법이 개시된다. claims: 반려 동물의 정보를 제공하는 방법에 있어서,상기 반려 동물의 상태 정보, 특성 정보 및 돌봄 히스토리 정보를 획득하는 단계;공개 설정에 따라 상기 상태 정보, 상기 특성 정보 및 돌봄 히스토리 정보를 외부 디바이스에 제공하는 단계; 및상기 상태 정보에 따라 사용자 단말의 위치 정보를 상기 반려 동물의 위치 정보로 상기 외부 디바이스에 제공하는 단계;를 포함하고,상기 상태 정보가 실종 중임을 나타내는 경우, 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 외부 디바이스에 제공하는 단계;를 더 포함하고,상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 외부 디바이스에 제공하는 단계는분실 시점으로부터 제 1 시간 동안 상기 반려 동물을 찾고 있음을 알리는 메시지를 제 1 영역 내의 동물 병원 및 동물 용품 취급점에 제공할 것을 요청하는 단계;분실 시점으로부터 상기 제 1 시간이 경과하는 경우 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 제 1 영역 내의 일반 회원에게 제공할 것을 요청하는 단계;분실 시점으로부터 상기 제 1 시간보다 큰 제 2 시간이 경과하는 경우 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 제 1 영역보다 큰 제 2 영역 내의 동물 병원, 동물 용품 취급점 및 일반 회원에게 제공할 것을 요청하는 단계;를 포함하는 방법.반려 동물의 정보를 제공하는 디바이스에 있어서,상기 반려 동물의 상태 정보, 특성 정보 및 돌봄 히스토리 정보를 획득하는 수신부; 및공개 설정에 따라 상기 상태 정보, 상기 특성 정보 및 돌봄 히스토리 정보를 외부 디바이스에 제공하고, 상기 상태 정보에 따라 사용자 단말의 위치 정보를 상기 반려 동물의 위치 정보로 상기 외부 디바이스에 제공하는 프로세서;를 포함하고,상기 프로세서는상기 상태 정보가 실종 중임을 나타내는 경우, 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 외부 디바이스에 제공하고,분실 시점으로부터 제 1 시간 동안 상기 반려 동물을 찾고 있음을 알리는 메시지를 제 1 영역 내의 동물 병원 및 동물 용품 취급점에 제공할 것을 요청하고,상기 분실 시점으로부터 상기 제 1 시간이 경과하는 경우 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 제 1 영역 내의 일반 회원에게 제공할 것을 요청하고,상기 분실 시점으로부터 상기 제 1 시간보다 큰 제 2 시간이 경과하는 경우 상기 반려 동물을 찾고 있음을 알리는 메시지를 상기 제 1 영역보다 큰 제 2 영역 내의 동물 병원, 동물 용품 취급점 및 일반 회원에게 제공할 것을 요청하는 디바이스., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

744/1150 Row 744: application_number: 1020200104424, combined_string: invention_title: 반려동물 XR 영상 체험 제공 시스템 및 방법 abstract: 반려동물 XR 영상 체험 제공 시스템이 개시된다. 반려동물에 관한 AR/VR 영상을 출력하는 사용자 단말; 상기 AR/VR 영상을 생성하여 상기 사용자 단말로 제공하는 반려동물 XR 제공 서버; 상기 반려동물 XR 제공 서버로부터 상기 AR/VR 영상을 제공받아 출력하는 헤드 마운트 디스플레이(head mount display)를 구성한다. 상술한 반려동물 XR 영상 체험 제공 시스템에 의하면, 3D 반려동물 AR 캐릭터를 다양한 VR배경 장소에 구현하여 사용자가 직접 체험할 수 있도록 구성됨으로써, 반려동물 사후에도 반려동물이 직접 살아있는 것처럼 시각과 청각을 통해 느낄 수 있는 효과가 있다. XR을 통해 다양한 배경 장소와 생전의 유사한 행동 양태를 구현하여 지금 살아 있는 것처럼 영상 체험을 할 수 있으며, 단순히 동영상이나 이미지처럼 고정된 영상이 아니므로, 지금 같이 있는 것처럼 느낄 수 있는 효과가 있다. claims: 반려동물 정보 및 장소 자료를 입력받고, 해당 장소 상의 반려동물에 관한 AR/VR 영상을 제공받아 출력하는 사용자 단말;상기 장소 상의 반려동물에 관한 AR/VR 영상을 제공받아 출력하는 헤드 마운트 디스플레이;상기 사용자 단말에서 입력받은 반려동물 정보 및 장소 자료에 기반하여 해당 장소 상의 반려동물에 관한 AR/VR 영상을 생성하고, 생성된 AR/VR 영상을 상기 사용자 단말 또는 상기 헤드 마운트 디스플레이로 제공하는 반려동물 XR 제공 서버를 포함하고,상기 반려동물 XR 제공 서버는,상기 반려동물 정보를 상기 사용자 단말로부터 수집하는 반려동물 정보 수집 모듈;상기 반려동물 정보 수집 모듈에서 수집된 반려동물 정보 중 반려동물 이미지가 저장되는 반려동물 이미지 데이터베이스;상기 반려동물 정보 수집 모듈에서 수집된 반려동물 정보 중 반려동물 동영상이 저장되는 반려동물 동영상 데이터베이스;상기 반려동물 정보 수집 모듈에서 수집된 반려동물 정보 중 반려동물 행동 정보가 저장되는 반려동물 행동 데이터베이스;상기 반려동물 정보 수집 모듈에서 수집된 반려동물 정보 중 반려동물 경험 정보가 저장되는 반려동물 경험 데이터베이스;상기 반려동물 이미지 데이터베이스에 저장된 반려동물 이미지, 상기 반려동물 동영상 데이터베이스에 저장된 반려동물 동영상, 상기 반려동물 행동 데이터베이스에 저장된 반려동물 행동 정보 및 상기 반려동물 경험 데이터베이스에 저장된 반려동물 경험 정보를 이용하여 해당 반려동물의 3D 반려동물 AR 캐릭터를 생성하는 반려동물 AR 캐릭터 생성 모듈;상기 사용자 단말로부터 특정 장소의 이미지 또는 동영상을 수집하는 장소 자료 수집 모듈;상기 장소 자료 수집 모듈에서 수집된 소정의 장소의 이미지 또는 동영상이 저장되는 특정 장소 데이터베이스;국내 장소의 이미지 또는 동영상이 미리 저장되는 국내 장소 데이터베이스;국외 장소의 이미지 또는 동영상이 미리 저장되는 국외 장소 데이터베이스;상기 특정 장소 데이터베이스에 저장된 특정 장소의 이미지 또는 동영상, 상기 국내 장소 데이터베이스에 저장된 국내 장소의 이미지 또는 동영상, 상기 국외 장소 데이터베이스에 저장된 특정 장소의 이미지 또는 동영상 중 어느 하나를 이용하여 VR 배경 장소를 구현하는 VR 배경 구현 모듈;상기 사용자 단말 또는 상기 헤드 마운트 디스플레이로부터 사용자 명령을 입력받는 사용자 인터페이스 모듈;상기 사용자 인터페이스 모듈에서 입력받는 사용자 명령에 따라 상기 반려동물 AR 캐릭터 생성 모듈이 3D 반려동물 AR 캐릭터를 생성하도록 제어하고, 상기 사용자 명령에 따라 상기 VR 배경 구현 모듈이 VR 배경 장소를 생성하도록 제어하는 AR/VR 제어 모듈;상기 AR/VR 제어 모듈의 제어에 따라 해당 VR 배경 장소에서 해당 3D 반려동물 AR 캐릭터가 생성되어 동작하는 AR/VR 영상을 구현하여 상기 사용자 단말 또는 상기 헤드 마운트 디스플레이로 제공하는 AR/VR 제공 모듈;상기 AR/VR 제어 모듈의 제어에 따라 가상 장례 빈소를 구현하여 온라인을 통해 제공하며, 장례식 배경 화면에 3D 반려동물 AR 캐릭터를 구현하도록 구성되며, 상기 가상 장례 빈소에는 상주의 빈소 구축, 추모록, 조의금, 안내 메시지 보내기의 기능이 구현되고 조문객의 빈소 입장, 추무록 작성, 조의금 보내기 기능이 구현되는 가상 장례 구축 모듈을 포함하고,상기 반려동물 AR 캐릭터 생성 모듈은,상기 3D 캐릭터에 해당 반려동물의 표정, 움직임, 습관 및 성향을 포함하는 정보가 반영된 움직임 및 동작을 반영하도록 구성되는 것을 특징으로 하는 반려동물 XR 영상 체험 제공 시스템., Ltext: 농업, prediction: '임업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

745/1150 Row 745: application_number: 1020200101331, combined_string: invention_title: 자동으로 개폐되는 사료배식기 abstract: 본 발명은 사료와 물을 내장하여 반려동물 접근시 내장된 사료와 물을 제공할 수 있도록 자동으로 개폐되는 사료배식기에 관한 것으로서, 보다 상세하게는 반려동물의 접근유무에 따라 배식기 본체프레임을 덮는 커버프레임이 자동으로 구동되며, 반려동물 접근시 커버프레임이 개방되어 내장된 사료와 물을 제공할 수 있도록 자동으로 개방되고, 반려동물이 사료나 물을 섭취하지 않는 경우에는 커버프레임이 자동으로 폐쇄되어 외부 이물질로부터 사료 및 물을 보호할 수 있으며, 이를 통해 사료 및 물과 배식기 내부를 청결하게 유지할 수 있는 자동으로 개폐되는 사료배식기에 관한 것이다. claims: 반려동물 접근유무에 따라 자동으로 개폐되는 사료배식기에 있어서,사료가 구비되는 배식볼이 내장되는 본체프레임과, 상기 본체프레임의 상면에 결합되어 회동을 통해 상기 배식볼을 개방 또는 폐쇄시키는 커버프레임으로 구성되는 배식기; 상기 본체프레임과 상기 커버프레임를 결합시키며, 모터에 의해 구동되어 상기 커버프레임를 회전시키는 기어부; 상기 본체프레임 정면측 상면에 구비되어 반려동물의 접근을 감지하는 감지조작부; 및 상기 감지조작부로부터 전달된 센서값을 통해 상기 기어부를 조작하여 반려동물이 상기 배식기로 접근여부에 따라 상기 배식기를 개폐시키는 제어부;로 구성되며,상기 커버프레임의 하면에는 상기 배식볼의 가장자리와 대응되는 형상을 가진 밀착패킹;이 형성되어 상기 본체프레임과 상기 커버프레임간의 틈새를 마감하고,상기 기어부는, 일단이 상기 본체프레임에 내장되어 결합고정되고, 타단이 상기 커버프레임과 결합되는 결합기어; 상기 본체프레임에 내장된 상기 결합기어의 일단을 관통하는 회전봉; 상기 회전봉을 회전시켜 상기 커버프레임을 회동시키는 모터; 및 상기 회전봉에 수평관통결합되며, 상기 모터와 밀착결합되는 회전가이드;로 구성되고,상기 회전가이드는 내각이 상기 커버프레임의 회동반경에 대응되는 부채꼴 형상을 가지며, 상기 모터의 외측과 상기 회전가이드가 기어결합되어 상기 모터 구동시 상기 회전가이드를 통해 상기 회전봉이 회전되며,상기 감지조작부는, 상기 본체프레임에서 상기 배식볼이 인입되는 측에 구비되어 상기 배식볼의 무게를 감지하는 무게감지센서;가 추가로 포함되며, 상기 무게감지센서는 감지된 사료잔존량을 상기 제어부로 전달하고,상기 제어부는, 상기 기어부의 구동여부를 제어하여 상기 배식기의 개폐여부를 조절할 수 있는 제어모듈; 상기 감지조작부로부터 전달받은 센서값을 통해 상기 배식기의 개폐여부 및 사료섭취량을 판단하는 판단모듈; 사용자 단말기와 연결되며, 상기 감지조작부를 통해 상기 배식볼 내부환경을 상기 사용자 단말기로 전달하는 통신모듈; 및 상기 배식기의 개폐여부를 판단하도록 상기 판단모듈이 상기 감지조작부로부터 전달된 센서값과 비교하는 설정값이 기저장되는 저장모듈;로 구성되고,상기 설정값은 일일사료섭취량 및 일정시간 내 사료섭취량을 포함하고, 상기 판단모듈은 상기 센서값이 상기 설정값을 초과하는 경우 반려동물에 접근에도 상기 배식기가 개방되는 것을 방지하도록 상기 제어모듈을 통해 상기 기어부를 제어하는 것을 특징으로 하는 자동으로 개폐되는 사료배식기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

746/1150 Row 746: application_number: 1020200100415, combined_string: invention_title: 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템 및 방법 abstract: 본 발명은 적어도 하나의 판매자 단말기(300) 및 구매자 단말기(200)와 네트워크망(500)을 통해 연결되는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템(100)으로서, 판매자 정보, 구매자 정보, 가축개량정보 및 가축 유전체 정보를 저장하는 데이터베이스부(120); 상기 판매자 단말기(300)에 의해 등록된 가축에 대한 유전정보, 혈통정보 및 번식정보를 수집하여 유전 능력을 분석하고, 가축의 유전능력을 통한 응찰가를 제시하고, 상기 판매자와 구매자가 가격에 합의하면 거래를 성사시키는 서버(110)를 포함한다. 이러한 본 발명의 실시예에서는, 유전체 기반의 정확한 능력 예측 시스템을 통해 고능력 가축과 저능력 가축은 물론, 가축의 유전적 능력에 따른 개량 솔루션을 농가에 제공할 수 있다. claims: 적어도 하나의 판매자 단말기(300) 및 구매자 단말기(200)와 네트워크망(500)을 통해 연결되는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템(100)의 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 방법으로서,상기 판매자 단말기(300)가 접속하면, 서버(110)가 판매를 원하는 가축 정보를 수신하여 등록하는 단계;서버(110)가 등록 가축에 대한 유전정보, 혈통정보 및 번식정보를 수집하는 단계;서버(110)가 수집된 정보를 이용하여 등록가축의 유전 능력을 분석하여 저장하는 단계를 포함하는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 방법.적어도 하나의 판매자 단말기(300) 및 구매자 단말기(200)와 네트워크망(500)을 통해 연결되는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템(100)으로서,판매자 정보, 구매자 정보, 가축개량정보 및 가축 유전체 정보, 농가정보를 저장하는 데이터베이스부(120);상기 판매자 단말기(300)에 의해 등록된 가축에 대한 유전정보, 혈통정보 및 번식정보, 표현형정보를 수집하여 유전능력을 분석하고, 가축의 유전능력를 통한 응찰가를 제시하고, 상기 판매자와 구매자가 가격에 합의하면 거래를 성사시키는 서버(110)를 포함하는 유전능력을 이용한 가축 온라인 거래 플랫폼 서비스 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

747/1150 Row 747: application_number: 1020200098903, combined_string: invention_title: 가축의 건강상태 측정용 가속도 센서의 운용 방법 abstract: 실시예는 가축의 건강상태 측정용 가속도 센서의 운용 방법에 관한 것이다.구체적으로, 이러한 가속도 센서의 운용 방법은 가축의 건강상태 측정장치에 사용되는 제어부가 개체 운동성을 측정하는 가속도 센서와 개체 생체온도를 측정하는 온도 센서와 연동하여 개체 상태를 검출해서 외부의 관리 정보처리장치로 무선 전송함으로써, 가축의 건강상태를 측정할 수 있도록 하는 방법을 전제로 한다.이러한 상태에서, 상기 가속도 센서의 운용 방법은 기준단위 시간 당 고정형태에 따른 횟수의 데이터 수집 여부를 결정하는 샘플링 주기와, 수집된 데이터가 미리 설정된 임계값을 넘는 경우에 알람하도록 하는 인터럽트 값을 미리 설정하는 제 1 단계;초기상태에는 상기 가속도 센서의 절대 위치를 가지고 임계값을 설정하여 고정상태를 확인하고, 고정상태 이후에는 인터럽트 형태를 상대위치 값을 가지고 발생하도록 변경하는 제 2 단계;상기 가속도 센서로부터 인터럽트 값이 감지된 경우에 인터럽트 값이 측정된 상태 이전과 이후의 미리 설정된 시간간격의 값을 상기 가속도 센서로부터 읽어 들여서 유효한 값으로 설정하는 제 3 단계;상기 설정 후에 미리 설정된 시간 경과시마 상기 가속도 센서로부터 각 축의 값을 측정하여 벡터 값으로 변환해서 이전에 측정된 벡터 값과 비교하는 동작을 이후 미리 설정된 시간 동안 인터럽트 값이 연속적으로 발생되지 않을시까지 수행하는 제 4 단계; 및상기 비교 결과를 기반으로 스칼라 값이 가장 큰 벡터를 외부의 관리 정보처리장치로 제공할 데이터로 결정하고, 데이터 수집 주기 내에 다수의 인터럽트가 발생한 경우에는 인터럽트의 발생 횟수와 가장 큰 스칼라 값을 가지는 벡터로 결정함으로써, 개체 운동성을 검출할 수 있도록 하는 제 5 단계; 를 포함하는 것을 특징으로 한다.따라서, 이를 통해 기존에 가축의 건강상태 체크시에 단순히 가속도 센서를 이용해서 가축의 생체 정보를 획득할 경우에 발생하는 여러 문제점을 해결하고(예: 고정상태와 안착상태의 신뢰성 있는 확인, 정확하고 효과적인 개체의 생체정보 획득 등) 보다 효과적으로 가축의 생체 정보를 획득한다. claims: 가축의 건강상태 측정장치에 사용되는 제어부가 개체 운동성을 측정하는 가속도 센서와 개체 생체온도를 측정하는 온도 센서와 연동하여 개체 상태를 검출해서 외부의 관리 정보처리장치로 무선 전송함으로써, 가축의 건강상태를 측정할 수 있도록 하는 방법에 있어서,가축의 위 내에서 캡슐의 고정 상태를 확인하기 위하여 가속도 센서의 기준단위 시간당 데이터 수집 횟수를 결정하는 샘플링 주기와, 수집된 데이터가 미리 설정된 임계값을 넘는 경우에 알람하도록 하는 인터럽트 값을 미리 설정하는 제 1 단계;캡슐이 삽입되는 초기상태에는 상기 가속도 센서의 절대 위치를 가지고 임계값을 설정하여 상기 캡슐이 위 내에 안착한 고정상태를 확인하고, 고정상태 이후에는 인터럽트 형태를 상기 가속도 센서의 상대위치 값을 가지고 발생하도록 변경하는 제 2 단계;상기 가속도 센서로부터 인터럽트 값이 감지된 경우에, 인터럽트 값이 측정된 상태 이전과 이후의 미리 설정된 시간간격의 값을 유효한 값으로서 상기 가속도 센서로부터 읽어 들여 설정하는 제 3 단계;상기 설정 후에 미리 설정된 시간이 경과될 때마다, 상기 가속도 센서로부터 각 축의 값을 측정하여 벡터 값으로 변환해서 이전에 측정된 벡터 값과 비교하는 동작을 미리 설정된 시간 동안 인터럽트 값이 연속적으로 발생되지 않을시까지 수행하는 제 4 단계; 및상기 비교 결과를 기반으로 스칼라 값이 가장 큰 벡터를 외부의 관리 정보처리장치로 제공할 데이터로 결정하고, 데이터 수집 주기 내에 다수의 인터럽트가 발생한 경우에는 상기 관리 정보처리장치로 제공할 데이터를 인터럽트의 발생 횟수와 가장 큰 스칼라 값을 가지는 벡터로 결정함으로써, 개체 운동성을 검출할 수 있도록 하는 제 5 단계; 를 포함하고,상기 제 4 단계 후에,상기 비교 결과를 기반으로 변환된 현재의 벡터 값이 미리 설정된 승가(마운트) 운동에 따른 벡터 값에 해당하는지의 여부를 판별하는 제 5-2 단계; 및상기 판별 결과, 현재의 벡터 값이 상기 승가(마운트) 운동에 따른 벡터 값에 해당하는 경우 발정 상태 알림신호를 관리자 단말기로 제공할 수 있도록 하고, 현재의 벡터 값이 상기 승가(마운트) 운동에 따른 벡터 값에 해당하지 않는 경우 발정 상태 알림신호 자체를 발생하지 않는 제 6 단계; 를 포함하고,상기 제 1 단계 전에,개체에 구비된 자력 센서에 대한 자성체의 근접 여부와, 근접의 지속 시간에 따라 발생하는 상이한 자력 상태를 기반으로 LED램프의 발광 동작을 상이하게 제어함으로써, 측정을 위해 미리 설정된 저전력 대기 모드와 실행 모드를 토글하는 단계; 를 더 포함하고,상기 토글하는 단계는,상기 자력 센서의 신호가 미리 설정된 시간 동안 유지 되는지를 확인하여 유지될 경우, 상기 LED램프를 온시키고, 유지가 되지 않을 경우에는 상기 자력 센서의 신호를 무시하고 다시 대기 모드 상태로 되며,다시 저전력 대기 모드 상태로 변경하기 위해서, 실행 모드에서 상기 자력 센서의 신호를 미리 설정된 시간 동안 유지 시킨 경우에, 상기 LED램프를 깜박이도록 동작시켜서 상기 자력 센서에 의한 파워 오프(Power Off) 절차가 1번 인식되었음을 알리고,다음, 자석을 멀리하여 상기 자력 센서의 신호를 없애고 미리 설정된 시간 이내에 다시 자석을 가까이 하여 상기 자력 센서의 신호를 미리 설정된 시간 동안 유지한 경우에는 상기 LED램프를 깜박이도록 동작시켜서 2번째 절차가 인식되었음을 알리고,상기 절차가 인식되었음을 알리는 동작을 미리 설정된 횟수만큼 반복하여 실행한 경우, 저전력 대기모드 상태로 진입하는 것; 을 특징으로 하는 가축의 건강상태 측정용 가속도 센서의 운용 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

748/1150 Row 748: application_number: 1020200097124, combined_string: invention_title: 축사용 급수장치 abstract: 본 발명은 축사용 급수장치에 관한 것으로서, 가축에게 공급할 물이 유동하도록 구비되는 급수관; 상기 급수관의 내부와 연통되게 결합되면서 상기 급수관 내부의 물이 외부로 배출되도록 상기 급수관의 길이 방향으로 일정 간격마다 형성되는 급수니플; 상기 급수니플이 결합된 급수관의 상부에서 상기 급수관이 견고하게 고정되도록 지지하는 고정관; 상기 급수관의 상기 급수니플들 하부에서 상향 개방되는 관형의 형상으로 형성되어 상기 급수니플을 통해 떨어지는 물을 받을 수 있도록 구비되는 물받이관; 상기 고정관과 상기 급수관과 함께 물받이관을 동시에 축지지하면서 일정 길이의 간격으로 구비되는 밴드 클램프의 결합으로 이루어지게 함으로써 사육장을 보다 위생적으로 유지 관리할 수 있도록 하는 것이다. claims: 가축에게 공급할 물이 유동하도록 구비되는 급수관(10);상기 급수관(10)의 내부와 연통되게 결합되면서 상기 급수관(10) 내부의 물이 외부로 배출되도록 상기 급수관(10)의 길이 방향으로 일정 간격마다 형성되는 급수니플(20);상기 급수니플(20)이 결합된 급수관(10)의 상부에서 상기 급수관(10)이 견고하게 고정되도록 지지하는 고정관(30);상기 급수관(10)의 상기 급수니플(20)들 하부에서 상향 개방되는 원형관 또는 U자형 관형의 형상으로 형성되어 상기 급수니플(20)을 통해 떨어지는 물을 받을 수 있도록 구비되는 물받이관(40);상기 고정관(30)과 상기 급수관(10)과 함께 물받이관(40)을 동시에 축지지하면서 일정 길이의 간격으로 구비되는 밴드 클램프(50);를 포함하되,상기 고정관(30)은 결합되는 상기 밴드 클램프(50)의 회전 방지를 위하여 각형의 관형상으로 이루어지며,상기 밴드 클램프(50)는상단부의 고정관 삽입부(51)와 그 하부의 급수관 삽입부(52) 및 그 하부의 물받이관 삽입부(53)를 형성하고, 물받이관(40)을 감싸는 물받이관 삽입부(53)가 하향 만곡지게 절곡되도록 하면서 상기 물받이관(40)의 주면을 감싸도록 하는 물받이관 삽입부(53)를 기준으로 상기 고정관(30)을 감싸도록 하는 고정관 삽입부(51)의 상호 양측으로 분리되도록 하여 양측이 일정 폭으로 벌어졌다 복원되는 탄성력을 갖도록 하는 것을 특징으로 하는 축사용 급수장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

749/1150 Row 749: application_number: 1020200096506, combined_string: invention_title: 반려 동물 판매 시스템 abstract: 본 발명은 본 발명은 적어도 제1 내지 제6 반려 동물(10, 20, 30, 40, 50, 60)의 실시간 동영상을 전시하는 초기화 화면; 상기 초기화 화면에서 제5 반려 동물(50)을 선택하면, 제5 반려 동물(50))에 대한 동영상(54a) 및 '동영상 확대보기(51aa)', '체험하기(51ab)' 및 '반려 동물 정보 보기(51ac)'를 포함하는 제1 테이블(51a)을 전시하는 제2 페이지(50A); 상기 제1 페이지(50A)에서 동영상 확대 보기(51a)를 선택하면, 전시되는 제5 반려 동물(50)에 대한 확대된 동영상을 전시하는 제2 페이지(50B); 상기 제1 페이지(50A)에서 '체험하기(52a)'를 선택하면 '체험 가능 여부(51Ca)', '현재 체험 상태 정보 (51Cb, 51Cc)', '체험 접수에 대한 정보(51Cd, 51Ce)', '사용자 모드(51Cf)' 및 '구경자 모드'를 포함하는 제2 테이블(51C)이 전시되는 제3 페이지(50C); 제3 페이지(50C)의 상기 제2 테이블(51C)에서 '사용자 모드(51Cf)'가 선택되면, 제5 반려 동물(50)의 특이 사항을 전시하는 제3 테이블(51D), '식사주기', '간식 주기', '산책 요구', '메세지', '장난감 주기' 및 '특별 요청'의 메뉴를 포함하는 제4 테이블(52D) 및 사용자가 직접 기입할 수 있는 블랭크를 구비한 제5 테이블(53D)전시되는 제4 페이지(50D); 를 포함하는 반려 동물 판매 시스템에 관한 것이다. claims: 사용자 단말과 구경자 단말을 포함하는 다수의 구매 예정자 단말이 접속 가능한 반려 동물 판매 시스템에 있어서.상기 반려 동물 판매 시스템은 적어도 제1 내지 제6 반려 동물(10, 20, 30, 40, 50, 60)의 실시간 동영상을 전시하여 상기 접속한 구매 예정자 단말이 상기 적어도 제1 내지 제6 반려 동물(10, 20, 30, 40, 50, 60)중 어느 하나의 선택 신호를 보낼수 있는 초기화 화면을 포함하고,상기 접속한 구매 예정자 단말이 상기 적어도 제1 내지 제6 반려 동물(10, 20, 30, 40, 50, 60)중 어느 하나를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 선택된 반려 동물에 대한 동영상(54a) 및 '동영상 확대보기(51aa)', '체험하기(51ab)' 및 '반려 동물 정보 보기(51ac)'를 포함하는 제1 테이블(51a)을 전시하는 제1 페이지(50A)를 상기 구매 예정자 단말에 전송하고,상기 접속한 구매 예정자 단말이 상기 제1 페이지(50A)에서 '체험하기(51ab)'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 '체험 가능 여부(51Ca)', '현재 체험 상태 정보 (51Cb, 51Cc)', '체험 접수에 대한 정보(51Cd, 51Ce)', '사용자 모드(51Cf)' 및 '구경자 모드'를 포함하는 제2 테이블(51C)을 전시하는 제3 페이지(50C)를 상기 구매 예정자 단말에 전송하고,상기 사용자 단말은 상기 다수의 구매 예정자 단말중 제3 페이지(50C)에서 '체험 접수에 대한 정보(51Cd, 51Ce)'를 통해 사용 예약 신호를 상기 반려 동물 판매 시스템에 보낸 후 상기 반려 동물 판매 시스템에 의해 체험자로 선택된 단말이고, 상기 구경자 단말은 상기 다수의 구매 예정자 단말중 사용자 단말이 아닌 단말이고. 상기 사용자 단말이 상기 반려 동물 판매 시스템에 접속된 경우 상기 '사용자 모드'가 선택가능하게 활성화되고 '구경자 모드'는 비활성화가 되어 선택이 불가능 하고, 상기 구경자 단말이 상기 반려 동물 판매 시스템에 접속된 경우 '사용자 모드'는 비활성화가 되고 '구경자 모드'만 활성화가 되어 선택이 가능하며,상기 사용자 단말이 제3 페이지(50C)의 상기 제2 테이블(51C)에서 '사용자 모드(51Cf)'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 선택된 반려 동물(50)의 특이 사항을 전시하는 제3 테이블(51D), '식사주기', '간식 주기', '산책 요구', '메세지', '장난감 주기' 및 '특별 요청'의 메뉴를 포함하는 제4 테이블(52D) 및 상기 사용자 단말에서 사용자가 직접 기입할 수 있는 블랭크를 구비한 제5 테이블(53D)을 전시하는 제4 페이지(50D)를 상기 사용자 단말에 전송하고,상기 제3 테이블(51D)에는 상기 제5 테이블(53D)의 블랭크를 통해 입력된 정보가 전시되고,상기 사용자 단말이 상기 제4 페이지(50D)의 상기 제4 테이블(52D)에서 '간식 주기'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 제4 테이블(52D), 날짜별로 간식을 준 것과 이에 대한 특이 사항을 전시하는 제6 테이블(51E)과 간식에 관한 사항이 입력될 수 있는 제7 테이블(53E)을 전시하는 제5 페이지(50E)를 상기 사용자 단말에 전송하고,상기 구경자 단말이 제3 페이지(50C)의 상기 제2 테이블(51C)에서 '구경자 모드(51Cg)'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 제4 페이지(50D)의 제3 테이블(51D), '식사 보기', '간식 보기', '산책 보기', '메세지 보내기', '장난감 보기', '관리자 문의'의 메뉴를 구비하는 제15 테이블(152D)을 전시하는 제11 페이지(150D)를 상기 구경자 단말에 전송하고, 상기 구경자 단말은 제15 테이블(152D)에서 '메세지 보내기'를 통해 상기 반려 동물 판매 시스템에 메세지를 전송할 수 있고, 상기 사용자 단말이 상기 제4 페이지(50D)의 제4 테이블(52D)에서 '메세지'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 구경자 단말이 전송한 메세지를 사용자 단말에 전송하고 사용자 단말은 상기 메세지에 대한 답변을 상기 반려 동물 판매 시스템에 전송할 수 있고,상기 구경자 단말이 상기 제15 테이블(152D)에서 '간식 보기'를 선택하는 신호를 상기 반려 동물 판매 시스템에 보내면, 상기 반려 동물 판매 시스템은 상기 제5 페이지(50E)의 제6 테이블(51E), 상기 제15 테이블(152D) 및 나가기(153D) 메뉴를 포함하는 제12 페이지(150E)를 상기 구경자 단말에 전송하는 것을 특징으로 하는 반려 동물 판매 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

750/1150 Row 750: application_number: 1020207027389, combined_string: invention_title: 스마트 애완동물 사육 장치 abstract: 본 발명의 실시예는 스마트 애완동물 사육 장치에 관한 것이다. 상기 장치는 케이지, 제어 센터, 모터, 소독 장치, 제1 적외선 식별 장치, 제2 적외선 식별 장치 및 음성 플레이 장치를 포함하고; 케이지의 각측벽에는 모두 회전축을 통해 전기 제어 변색 유리판이 설치되며; 제1 적외선 식별 장치는 케이지 내에 동물의 존재여부를 모니터링하고, 케이지 내에 동물이 존재하지 않는 것으로 모니터링될 경우, 소독 장치는 케이지 내부를 소독하며; 제2 적외선 식별 장치는 케이지 외부의 기설정 범위 내에 사람 또는 동물의 존재 여부를 검출한다. 본 발명의 실시예에서의 제1 적외선 식별 장치는 케이지 내에 동물의 존재 여부를 식별할 수 있고, 동물이 케이지에 존재하지 않을 경우, 제어 센터는 소독 장치가 작동되어 케이지를 소독하도록 제어함으로써, 세균, 바이러스의 번식을 방지한다. 제2 적외선 식별 장치는 케이지 주위에 사람 또는 동물의 존재 여부를 식별할 수 있음으로써, 음성 플레이 장치를 작동시켜 설정된 내용을 플레이하여 사육 과정에 교류성 및 취미성를 증가시킨다. claims: 케이지, 제어 센터, 모터를 포함하고,상기 케이지의 윗면 및 밑면은 모두 판체이고, 상기 케이지의 4개의 측벽은 격자판이며, 각측벽과 윗면의 교차 위치에는 모두 회전축이 설치되고, 각 상기 회전축은 하나의 모터에 연결되며, 각 회전축에는 모두 상기 케이지의 측벽을 커버하기 위한 전기 제어 변색 유리판이 설치되고;상기 모터는 케이지의 최상부에 장착되며, 전지 또는 교류 전류를 통해 전원을 제공하며;상기 모터는 상기 케이지에 연결되고 상기 제어 센터는 상기 케이지에 설치되는 것을 특징으로 하는 스마트 애완동물 사육 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

751/1150 Row 751: application_number: 1020217001657, combined_string: invention_title: 이중 교반판 사료 투하 구조 및 투하장치 abstract: 본 발명은 애완동물 간식공급장치 부재 기술분야에 속하는 것으로, 기존의 애완동물 간식 투하 효과가 좋지 않고 투하량을 제어할 수 없는 선행기술의 문제점을 해결하는 이중 교반판 사료 투하기구 및 투하장치를 제공하는 바, 상기 이중 교반판 사료 투하기구는 사료 교반 장치 및 구동장치를 포함하고, 상기 사료 교반 장치는 회전축, 상부 사료 교반판 및 하부 사료 교반판을 포함하며; 상기 상부 사료 교반판은 상부 사료 교반편을 포함하고, 상기 하부 사료 교반판은 하부 사료 교반편을 포함하며, 상기 하부 사료 교반편의 개수는 상기 상부 사료 교반편의 개수보다 많으며, 상기 회전축의 외벽에는 장착홈이 설치되고, 상기 하부 사료 교반편에는 장착홈에 적합한 장착 스트립이 설치되며; 상기 투하장치는 사료 저장빈, 트랜지션빈 및 상기 이중 교반판 사료 투하기구를 포함하고; 본 발명은 이중 교반판 사료 투하기구를 통해 애완동물 간식을 효과적으로 투하할 수 있으며, 2단계 투하 방식은 원활한 투하를 확보하는 전제하에 단일 투하량을 효과적으로 제어할 수 있다. claims: 사료 교반 장치 및 구동장치를 포함하되, 여기서,상기 사료 교반 장치는 회전축(322), 상기 회전축(322)에 적층 설치된 상부 사료 교반판(31) 및 하부 사료 교반판(32)을 포함하고, 상기 회전축(322)의 일단은 상기 상부 사료 교반판(31)에 연결되며, 상기 회전축(322)의 타단은 상기 구동장치에 연결되고, 상기 구동 장치는 상기 회전축(322)이 회동하도록 구동시켜 상기 상부 사료 교반판(31)과 상기 하부 사료 교반판(32)이 동기적으로 회동하도록 할 수 있고; 상기 상부 사료 교반판(31)은 적어도 하나의 상부 사료 교반편(311)을 포함하고, 상기 하부 사료 교반판(32)은 적어도 두개의 하부 사료 교반편(321)을 포함하며, 상기 하부 사료 교반편(321)의 개수는 상기 상부 사료 교반편(311)의 개수보다 많고, 상기 회전축(322)의 외벽에는 장착홈(3223)이 설치되며, 상기 하부 사료 교반편(321)의 엣지부에는 장착 스트립(3211)이 설치되고, 상기 장착 스트립(3211)은 상기 장착홈(3223) 내에 삽입 연결된다.는 것을 특징으로 하는 이중 곡물 교반판 배출 기구(3).사료 저장빈(1), 트랜지션빈(2) 및 제 1 항 내지 제 7 항 중 어느 한 항에 따른 이중 교반판 사료 투하기구(3)를 포함하고, 상기 사료 저장빈(1)은 상기 트랜지션빈(2)의 상부에 설치되되, 여기서, 상기 사료 저장빈(1) 내에는 사료 저장 챔버(11)가 설치되고, 상기 트랜지션빈(2)에는 트랜지션 챔버(21)가 설치되며, 상기 사료 저장빈(1)의 바닥부에는 토출구(131)가 설치되고, 상기 사료 저장 챔버(11)는 상기 토출구(131)를 통해 상기 트랜지션 챔버(21)와 연통되며, 상기 트랜지션빈(2)의 바닥부에는 상기 트랜지션 챔버(21)와 연통되도록 가이드구(211)가 설치되고; 상기 상부 사료 교반판(31)은 상기 사료 저장 챔버(11) 내에 설치되어 상기 사료 저장 챔버(11) 내의 애완동물 간식을 상기 토출구(131)를 통해 밀어낼 수 있으며; 상기 하부 사료 교반판(32)은 상기 트랜지션 챔버(21) 내에 설치되고, 상기 하부 사료 교반편(321)은 모두 상기 트랜지션 챔버(21)를 적어도 두개의 트랜지션 유닛으로 분할하며, 상기 토출구(131)를 통해 밀려나온 애완동물 간식은 상기 트랜지션 유닛 내에 떨어져 상기 하부 사료 교반편(321)의 푸시하에 상기 가이드구(211)로부터 밀려 나올 수 있는 것을 특징으로 하는 투하장치.제 6 항에 있어서, 상기 사료 저장빈(1)은 상부 빈 본체(12) 및 하부 빈 본체(13)를 포함하되, 여기서,상기 하부 빈 본체(13)는 상기 상부 빈 본체(12)의 바닥부에 설치되고, 상기 상부 빈 본체(12) 내의 캐비티와 상기 하부 빈 본체(13) 내의 캐비티는 둘러싸여 상기 사료 저장 챔버(11)를 이루며; 상기 하부 빈 본체(13)는 호퍼 형상으로 설치되고, 상기 하부 빈 본체(13)의 구경은 상기 상부 빈 본체(12)로부터 멀어지는 방향을 따라 순차적으로 감소되고; 상기 토출구(131)는 상기 하부 빈 본체(13)의 바닥부에 설치되며, 상기 상부 사료 교반판(31)은 상기 토출구(131)에 근접하는 위치에 설치되는 것을 특징으로 하는 투하장치.제 7 항에 있어서, 상기 트랜지션 챔버(21)의 형상은 원기둥형으로 설치되고, 상기 하부 사료 교반편(321)은 상기 트랜지션 챔버(21)를 적어도 두개의 상기 트랜지션 유닛으로 균등하게 분할하기 위해 모두 상기 회전축(322)에 대해 원주 방향으로 균일하게 설치되는 것을 특징으로 하는 투하장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

752/1150 Row 752: application_number: 1020200084106, combined_string: invention_title: 온도충격 인가형 가축분뇨 스마트 저장조 및 이를 이용한 가축분뇨 저장방법 abstract: 본 발명은 가축 분뇨의 저장방법에 대한 저장시스템 및 방법에 대한 것으로, 가축분뇨 저장조에 수용되는 가축분뇨의 온도 변화를 감지하고, 저장 기준온도와 센싱온도를 감지하여, 저장설정온도까지 저온으로 낮추는 온도충격을 인가하는 방식의 저장방법을 통해, 가축분뇨 저장조에서의 악취 발생을 차단하고, 유기물 분해를 최소화하여 바이오 가스 시설 연계시 메탄생성을 증대할 수 있도록 할 수 있다. claims: 가축분뇨를 저장하는 저장조에 있어서, 가축분뇨를 수용하는 수용부(100); 상기 수용부 내측에 수용되는 가축분뇨를 교반하는 교반부(110); 상기 수용부(100) 내측에 수용되는 가축분료의 온도를 제어하는 냉각기(122)를 포함하는 냉각모듈(120); 상기 수용부(100) 내측의 온도변화를 감지하고, 설정온도로 낮추는 제어신호를 인가하는 제어부(130);를 포함하며,상기 냉각모듈(120)은, 냉각된 유체를 공급하는 냉각기(122);과 상기 냉각모듈(120)에서 공급되는 냉각 유체를 상기 수용부(100)의 내측으로 인가하도록, 수용부 내측에 배치되는 냉각배관(124); 상기 수용부(100)의 내측에 수용되는 가축분뇨의 온도변화를 감지하는 온도센서유닛(126);을 포함하며,상기 제어부(130)는, 상기 온도센서유닛(126)에서 감지되는 분뇨의 온도를 실시간으로 감지하고, 상기 수용부(100) 내부의 가축분뇨에 대한 저장 기준온도(T1)에 도달하는 경우로, 일정시간(t1) 동안 온도 변화의 폭이 10℃ 이상으로 증가하는 경우에, 상기 냉각모듈(120)을 제어하여 온도충격을 인가하도록 하며, 상기 저장 기준온도(T1)에 대하여 저장 설정온도(T2)까지 온도를 낮추도록 하며, 온도충격에 의한 온도변화량(△T=T2-T1)이 10℃ 이상으로 제어하는 제어방식을 지속적으로 유지시키도록 하며,상기 교반부(110)는, 교반모터(111)와 교반축(112), 상기 교반축(112)에 연계하는 블레이드(113) 구조물을 포함하는, 온도충격 인가형 가축분뇨 스마트 저장조., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

753/1150 Row 753: application_number: 1020200080374, combined_string: invention_title: 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 방법, 프로그램, 및 시스템 abstract: 본 발명은 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 방법에 관한 것으로, 수집 장치가 동물의 정보를 수집하는 수집 단계; 수신부가 상기 정보를 수신하는 수신 단계; 분석부가 상기 수신된 정보를 분석하여 메시지로 가공하는 가공 단계; 제1 출력 장치가 상기 메시지를 출력하는 제1 출력 단계; 상기 분석부가 상기 제1 출력 장치로 수신된 답변 메시지를 분석하는 분석 단계; 검색부가 상기 분석부의 상기 답변 메시지의 분석에 대응하는 콘텐츠를 검색하는 검색 단계; 및 제2 출력 장치가 상기 검색된 콘텐츠를 출력하는 제2 출력 단계;를 포함한다. claims: 수집 장치가 동물의 정보를 수집하는 수집 단계;수신부가 상기 정보를 수신하는 수신 단계;분석부가 상기 수신된 정보를 분석하여 메시지로 가공하는 가공 단계;제1 출력 장치가 상기 메시지를 출력하는 제1 출력 단계;상기 분석부가 상기 제1 출력 장치로 수신된 답변 메시지를 분석하는 분석 단계;검색부가 상기 분석부의 상기 답변 메시지의 분석에 대응하는 콘텐츠를 검색하는 검색 단계; 및제2 출력 장치가 상기 검색된 콘텐츠를 출력하는 제2 출력 단계;를 포함하는 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 방법.하드웨어인 컴퓨터와 결합되어, 제1항 내지 제7항 중 어느 한 항의 방법을 실행시키기 위하여 매체에 저장된, 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 프로그램. 동물의 정보를 수집하는 수집 장치;상기 수집 장치에서 상기 정보를 제공받는 서버;상기 서버에서 상기 정보에 대응하는 메시지를 제공받아 출력하고, 답변 메시지를 제공받는 제1 출력 장치; 및상기 답변 메시지에 대응하는 콘텐츠를 출력하는 제2 출력 장치;를 포함하고,상기 서버는상기 수집 장치에서 상기 정보를 제공받는 수신부;상기 정보를 분석하여, 상기 메시지로 가공하여, 상기 제1 출력 장치에 제공하고, 상기 제1 출력 장치로 수신된 상기 답변 메시지를 분석하는 분석부; 및상기 답변 메시지의 분석에 대응하는 상기 콘텐츠를 검색하는 검색부;를 포함하는 동물과의 커뮤니케이션을 이용한 콘텐츠 제공 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

754/1150 Row 754: application_number: 1020200079034, combined_string: invention_title: 반려동물의 성장 관리 시스템 abstract: 본 발명의 반려동물 성장 관리시스템은 반려동물에게 가장 적합한 식이요법을 제공한다. 반려동물의 현재 데이터를 토대로 성장 모델과 비교하여 적절한 목표값을 결정하며, 이를 달성하기 위한 수제 사료를 포함한 정보가 솔루션으로 제공된다. claims: 반려동물을 키우는 사용자의 사용자 기기와 통신하는 반려동물의 성장관리 시스템으로서, 상기 성장 관리 시스템은:사용자가 입력한 반려동물의 종류, 품종, 나이, 성별, 중성화여부, 질병이력 정보, 몸무게, 활동량, 사료급식량 및 물급수량을 저장하는 메모리;메모리의 정보를 토대로 반려동물의 성장 상태를 분석하는 성장상태 분석부; 및성장상태 분석부의 분석 결과를 토대로 성장 관리를 위한 처방을 표시하고 사료를 결정하는 성장관리 처방부;를 포함하며,성장상태 분석부와 성장 상태 처방부는 사료정보 테이블을 참조하고, 사료정보 테이블은 각각의 사료의 이름, 성분, 영양 정보, 적절 연령대의 정보를 포함하며, 사료정보테이블에는 현재 존재하는 상용의 판매 사료 정보가 저장되어 사용자가 사료명을 입력하거나 스캔하는 것으로 현재 동물 상태를 파악할 수 있으며,성장상태 분석부는 메모리의 데이터를 참조로 반려동물의 크기를 분류하고, 입력된 나이를 토대로 성장 단계를 분류하며, 나이, 품종 및 몸무게 데이터를 토대로 해당 반려동물의 성장 곡선과 비교하여 적어도 마름, 정상 및 비만의 어느 한 단계를 표시하고, 사료급식량과 물급수량 데이터를 토대로 반려 동물이 현재 섭취하는 에너지를 계산하여 정상 몸무게 일 경우의 필요 에너지와 비교하며,상기 성장곡선의 모델은 처음에는 동물 별 기초 모델이며, 성장상태 분석부의 분석 데이터 누적에 따라 학습되어 상기 기초 모델을 갱신한 성장 곡선 모델이며,성장관리 처방부는 반려동물 정보, 체형 분석 및 식단 분석을 포함하는 성장관리솔루션리포트를 사용자기기로 전송하고, 성장관리솔류션리포트는 반려동물이 비만인 경우 다이어트 플랜 및 처방전 정보를 포함하는, 성장 관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

755/1150 Row 755: application_number: 1020200079126, combined_string: invention_title: 반려동물 질병진단 정보 기반 구매제품 추천 시스템 abstract: 본 발명은 구매제품 추천 시스템에 관한 것으로서, 보다 구체적으로는 반려동물의 질병이력을 고려하여 반려동물을 키우는데 필수적인 사료, 영양제, 간식, 샴푸 등과 같은 다양한 제품 중에서 전문가에 의해 검증된 제품을 자동 추천함으로써 반려동물을 위한 제품이 질병으로 인해 오히려 유해한 영향을 미쳐 반려동물을 해칠 수 있는 상황을 방지하기 위한 반려동물 질병진단 정보 기반 구매제품 추천 시스템에 관한 것이다.이를 위해 본 발명은, 수신되는 반려동물의 나이를 포함한 질병진단 이력정보를 기초로 구매할 제품을 자동으로 추천하고 추천한 제품을 온라인상에서 구매 가능하도록 하기 위한 구매제품 추천서버와; 상기 구매제품 추천서버로 반려동물 질병진단 이력정보를 송신하여 구매할 제품을 추천받기 위한 고객 단말기와; 상기 질병진단 이력정보에 대응하여 추천 또는 비추천하는 제품에 대한 사유정보를 구매제품 추천서버로 업로드하여 고객 단말기가 확인 가능하도록 하기 위한 동물병원 단말기;를 포함하는 것을 특징으로 한다. claims: 수신되는 반려동물의 나이를 포함한 질병진단 이력정보를 기초로 구매할 제품을 자동으로 추천하고 추천한 제품을 온라인상에서 구매 가능하도록 하기 위한 구매제품 추천서버와;상기 구매제품 추천서버로 반려동물 질병진단 이력정보를 송신하여 구매할 제품을 추천받기 위한 고객 단말기와;상기 질병진단 이력정보에 대응하여 추천 또는 비추천하는 제품에 대한 사유정보를 구매제품 추천서버로 업로드하여 고객 단말기가 확인 가능하도록 하기 위한 동물병원 단말기;를 포함하되,상기 질병진단 이력정보는 영양결핍, 신부전, 심장병, 알러지, 슬개골탈구, 관절염, 치주염, 수술 후 회복, 아토피, 외이도염, 피부병, 디스크, 기관지 협착, 비만, 백내장 및 당뇨 중 적어도 어느 하나 이상을 포함하며,상기 구매제품 추천서버는 반려동물에 대한 나이, 성별, 과거부터 현재까지 진단받은 질병명 및 질병기간을 사전에 마련된 선택란을 통해 고객 단말기가 선택하도록 하여 질병진단 이력정보를 생성하기 위한 질병이력 생성모듈을 구비하며,상기 구매제품 추천서버는 고객 단말기의 요청하에 동물병원 단말기로부터 반려동물의 질병진단서를 수집하고 수집된 문서 형식의 질병진단서를 텍스트 분석모듈을 통해 질병진단 이력정보를 생성하여 고객이 반려동물의 질병진단 이력이 반영된 제품을 추천받도록 하기 위한 질병진단정보 수집모듈을 구비하며,상기 구매제품 추천서버는 고객 단말기가 전송하는 이미지 및 동영상 중 적어도 어느 하나 이상을 CNN(Convolutional Neural Network) 방식을 통한 컨볼루션 레이어들을 통해 특성을 추출하게 되어 추출된 특성을 기반으로 분석하여 반려동물의 질병을 진단하기 위한 영상 분석모듈을 구비하며,상기 구매제품 추천서버는 고객 단말기가 전송하는 반려동물에 대한 텍스트 형식의 질병정보를 분석하여 질병진단 이력정보를 생성하기 위한 텍스트 분석모듈을 구비하며,상기 구매제품 추천서버는 고객 단말기가 전송하는 반려동물에 대한 음성 형식의 질병정보를 인식하여 텍스트화한 다음으로, 텍스트 분석모듈과 연계하여 질병진단 이력정보를 생성하기 위한 음성 분석모듈을 구비하며,상기 텍스트 분석모듈은 형태가 무작위인 텍스트를 형태소 분석, 구문 분석 및 개체명 인식 중 적어도 어느 하나 이상의 방식을 이용한 자연어 처리를 수행한 이후로 질병진단 이력정보만을 미리 정해진 카테고리로 분류, 군집화 및 연관어 분석 중 적어도 어느 하나 이상으로 텍스트를 분석하며,상기 텍스트 분석 중 분류는 질병진단 이력정보를 반려동물 관련한 나이, 성별, 질병명 및 질병에 걸린 기간 중 적어도 어느 하나 이상의 정해진 특정으로 카테고리를 분류하고, 상기 텍스트 분석 중 군집화는 질병진단 이력정보 중 유사한 주제끼리 그룹핑하고, 상기 분류가 학습 과정을 통해 문서를 분류하는 지도 학습에 해당된다면 상기 군집화는 학습 과정 없이 바로 유사 정보끼리 그룹핑을 하는 비지도 학습/자율 학습에 해당되며, 상기 텍스트 분석 중 연관어 분석은 텍스트상에 출현하는 단어 간의 관계를 분석하여 질병진단 이력정보와 관련된 단어 간의 연관성을 찾아내며,상기 구매제품 추천서버는 머신러닝 방식에 의해 상기 질병진단 이력정보를 기초로 반려동물의 과거부터 현재까지의 건강상태가 고려된 사료, 영양제, 간식, 샴푸, 방석, 옷, 장난감, 패드 및 기저귀 중 적어도 어느 하나 이상의 제품을 자동으로 추천하기 위한 제품 추천모듈을 구비하며,상기 구매제품 추천서버는 동일 제품군별 제품 비교정보를 고객 단말기에 제공하기 위한 비교제품정보 제공모듈을 구비하며,상기 구매제품 추천서버는 회원 등록된 수의사 단말기에 교육을 위해 신규제품 정보를 제공하기 위한 신규제품정보 제공모듈을 구비하는 것을 특징으로 하는 반려동물 질병진단 정보 기반 구매제품 추천 시스템., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

756/1150 Row 756: application_number: 1020200079195, combined_string: invention_title: 표준 진료비에 기반한 동물병원 추천 방법 및 시스템 abstract: 표준 진료비에 기반한 동물병원 추천 방법 및 시스템을 개시한다.본 실시예는 복수의 동물병원마다 진료비에 대한 편차가 존재하므로 펫 오너 입장에서 동물병원을 방문하기 전에 표준 진료비를 기준으로 진료비가 높은지 낮은지를 확인할 수 있도록 합리적인 가이드 라인을 제공하는 동시에, 진료비, 위치, 펫의 종류, 질병을 기반으로 동물병원을 추천해주는 표준 진료비에 기반한 동물병원 추천 방법 및 시스템을 제공한다. claims: 자체 조사로 입력된 정보, 동물병원 단말기로부터 입력 받은 정보, 펫 오너 단말기로부터 수신한 정보를 수집하여 표준 진료비를 산정하는 표준 진료비 산정장치;상기 표준 진료비와 상기 동물병원 단말기로부터 입력 받은 각 동물병원별 진료비를 비교하여 임계범위 이내의 편차를 갖는 동물병원만을 추출하여 후보 동물병원으로 선별하고, 상기 후보 동물병원 중 상기 펫 오너 단말기의 위치 및 상기 펫 오너 단말기로부터 수신된 펫 정보를 기반으로 추천 동물병원을 선별하여 상기 펫 오너 단말기로 전송하는 동물병원 추천장치; 및상기 펫 오너 단말기로부터 수신한 상기 추천 동물병원에 대한 예약일자를 기반으로 예약 및 선결제를 진행하는 동물병원 예약장치를 포함하되, 상기 표준 진료비 산정장치는 상기 표준 진료비를 산정할 때,외부로부터 수집된 동물병원의 위치를 기반으로 수도권과 지방으로 구분하고 상기 수도권과 상기 지방에 따른 가중치를 반영하고, 동물병원의 위치를 기반으로 동물병원의 밀집 지역과 비밀집 지역을 구분한 후 동물병원의 밀집 지역에 기 설정된 임계치보다 낮은 가중치, 비밀집 지역에 기 설정된 임계치보다 높은 가중치를 반영하고,동물병원의 위치를 기반으로 지하철에 인접한 위치에 동물병원과 주차장을 보유한 동물병원에 기 설정된 임계치보다 높은 가중치를 반영하고, 지하철로부터 기 설정된 거리 이상으로 이격되어 위치에 동물병원과 주차장을 미보유한 동물병원에 기 설정된 임계치보다 낮은 가중치를 반영하고,펫 종류를 기반으로 펫이 소형, 중형 또는 대형인지를 1차적 판단한 1차 판단 결과를 생성하고, 상기 1차 판단 결과에 상기 펫의 사이즈와 상기 펫의 몸무게를 추가로 반영하여 펫이 소형, 중형 또는 대형인지를 2차적으로 판단한 2차 판단 결과를 생성하며, 상기 2차 판단 결과를 기반으로 펫이 소형으로 판단되면 기 설정된 임계치 보다 낮은 가중치를 반영하고, 상기 2차 판단 결과를 기반으로 펫이 중형으로 판단되면 일반 가중치를 반영하고, 상기 2차 판단 결과를 기반으로 펫이 대형으로 판단되면 기 설정된 임계치 보다 높은 가중치를 반영하고,상기 펫 오너 단말기로부터 수신된 수의사의 평가점수가 기 설정된 임계치보다 높으면 높은 가중치를 반영하고, 상기 수의사의 평가점수가 기 설정된 임계치보다 낮으면 낮은 가중치를 반영하는 것을 특징으로 하는 표준 진료비에 기반한 동물병원 추천 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

757/1150 Row 757: application_number: 1020200075792, combined_string: invention_title: 축산차량 GPS 단말기 개통 시스템 abstract: 본 발명에 따른 GPS 단말기 개통 시스템은 이동통신망을 이용하는 GPS 단말기에 이동통신 서비스를 제공하기 위한 개통을 수행하는 이동통신사 서버; 축산차량의 이동경로를 관리하기 위하여 GPS 단말기에 관리번호를 부여하는 기관단체 서버; 등록 대상자에게 판매되는 상기 GPS 단말기에 대하여 상기 등록 대상자의 등록 대상자 정보를 입력받는 GPS 단말기 판매처 단말기; 및 상기 GPS 단말기 판매처 단말기로부터 상기 GPS 단말기에 대한 정보를 제공받아 개통 및 등록을 수행하는 에이전트 서버;를 포함하고,상기 에이전트 서버는, 상기 GPS 단말기 판매 전 상기 이동통신사 서버에 상기 GPS 단말기의 단말기 정보를 전달하면서 GPS 단말기 관련 개통예정정보를 생성 요청하여 반환받고, 상기 기관단체 서버에 반환된 상기 GPS 단말기의 개통예정정보를 전달하면서 정보 매칭 요청을 하여 매칭 정보를 반환 받아 보유하고, 상기 GPS 단말기 판매처 단말기로부터 상기 GPS 단말기에 대한 개통 요청이 있는 경우 상기 매칭 정보를 반환하고, 상기 이동통신사 서버에 상기 GPS 단말기에 대한 예비 개통 정보를 전달하는 에이전트 서버를 포함한다.본 발명에 따른 축산차량 GPS 단말기 개통 시스템은 축산차량의 단말기 등록과 주관기관에의 등록 절차에 소요되는 시간 및 절차를 최소화함으로써 효율적인 업무의 처리를 가능하도록 하는 효과가 있다. claims: 이동통신망을 이용하는 GPS 단말기에 이동통신 서비스를 제공하기 위한 개통을 수행하는 이동통신사 서버; 축산차량의 이동경로를 관리하기 위하여 GPS 단말기에 관리번호를 부여하는 기관단체 서버;등록 대상자에게 판매되는 상기 GPS 단말기에 대하여 상기 등록 대상자의 등록 대상자 정보를 입력받는 GPS 단말기 판매처 단말기; 및상기 GPS 단말기 판매처 단말기로부터 상기 GPS 단말기에 대한 정보를 제공받아 개통 및 등록을 수행하는 에이전트 서버;를 포함하고,상기 에이전트 서버는,상기 GPS 단말기 판매 전 상기 이동통신사 서버에 상기 GPS 단말기의 단말기 정보를 전달하면서 GPS 단말기 관련 개통예정정보를 전달하여 예비개통을 요청하고, 상기 기관단체 서버에 반환된 상기 GPS 단말기의 개통예정정보를 전달하면서 정보 매칭 요청을 하여 상기 기관단체의 상기 GPS 단말기에 대한 관리번호를 포함하는 매칭 정보를 반환 받아 보유하고, 상기 GPS 단말기 판매처 단말기로부터 상기 GPS 단말기에 대한 개통 요청이 있는 경우 상기 매칭 정보를 반환하고, 상기 이동통신사 서버에 상기 GPS 단말기에 대한 예비개통 정보 및 상기 매칭 정보를 전달하는 에이전트 서버를 포함하는 GPS 단말기 개통 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

758/1150 Row 758: application_number: 1020200071789, combined_string: invention_title: 사물 인터넷 기반의 반려동물 소통기능 제공장치 및 방법, 사용자 단말기 abstract: 본 발명은 반려동물의 욕구를 파악하고 반려동물 욕구를 만족시켜줄 수 있는 기기를 원격 제어하는 사물 인터넷 기반의 반려동물 소통기능 제공장치 및 방법에 관한 것으로 반려동물 욕구 신호를 입력받아 사용자 단말기에서 구동되는 반려동물 소통 전용 앱을 통해 전달하는 욕구신호 전달부, 상기 사용자 단말기에서 구동되는 반려동물소통 전용 앱을 통해 상기 욕구신호 전달부에서 전달한 욕구 신호에 매칭되는 욕구 해소 장치의 원격 제어 신호를 수신하는 원격 제어신호 수신부 및 상기 원격 제어신호 수신부로 수신되는 원격 제어 신호를 욕구 해소 장치로 전달하는 원격 제어신호 전달부를 포함하는 사물 인터넷 기반의 반려동물 소통기능 제공장치. 에 의해 원격지에서도 반려동물의 욕구 내용을 파악하고, 그에 따른 욕구를 충족시켜줄 수 있도록, 사료제공, 간식제공, 놀잇감 제공, 영상 통화와 같은 IoT 기기를 이용한 기능을 제공 가능하여 반려동물과의 친밀감을 더 높일 수 있고, 반려동물의 분리불안해소, 우울증 예방, 운동량 증가 효과를 볼 수 있다는 효과가 도출된다. claims: 욕구해소 장치와 근거리 무선 통신을 수행하는 제어신호 중개장치로부터 반려동물 욕구 신호를 입력받아 사용자 단말기에서 구동되는 반려동물 소통 전용 앱을 통해 전달하는 욕구신호 전달부; 상기 사용자 단말기에서 구동되는 반려동물소통 전용 앱을 통해 상기 욕구신호 전달부에서 전달한 욕구 신호에 매칭되는 욕구 해소 장치의 원격 제어 신호를 수신하는 원격 제어신호 수신부; 및상기 원격 제어신호 수신부로 수신되는 원격 제어 신호를 적어도 하나의 욕구해소 장치와 근거리 무선 통신을 수행하는 제어신호 중개장치를 경유하여 욕구 해소 장치로 전달하는 원격 제어신호 전달부;를 포함하고, 상기 욕구신호 전달부는, 상기 반려동물소통 전용 앱의 채팅 기능을 통해 상기 반려동물 욕구 신호를 구어체로 변환하여 전달하되, 상기 반려동물 욕구신호에 따른 키워드를 파악하고, 기저장된 대화체 문장들 중 상기 키워드를 포함하는 문장을 선별하여 상기 반려동물소통 전용 앱의 채팅 기능을 통해 전달하고, 상기 욕구 해소 장치는 사료 급식기, 간식 급식기, 놀이보조기, 영상통화장치, 스피커 중 적어도 하나이며, 상기 욕구신호 전달부는, 제어신호 중개장치의 칩 인식부로부터 칩 인식 신호를 수신하여 반려 동물의 식별 정보를 함께 사용자 단말기로 전달하고, 상기 반려동물소통 전용 앱의 채팅 기능을 통해 반려 동물의 식별 정보에 따라 해당 반려동물과의 채팅 기능을 제공하는 사물 인터넷 기반의 반려동물 소통기능 제공장치. 제 1 항, 제4항, 제6항 중 어느 한 항에 기재된 사물인터넷 기반의 반려동물소통기능 제공장치가 탑재된 사용자 단말기.욕구 신호 전달부, 제어신호 수신부 및 원격 제어신호 전달부를 포함하는 사물 인터넷 기반의 반려동물 소통기능 제공장치에서 수행되는 사물 인터넷 기반의 반려동물 소통기능 제공방법에 있어서, 욕구 신호 전달부가 반려동물 욕구 신호를 입력받아 사용자 단말기에서 구동되는 반려동물소통 전용 앱을 통해 욕구 신호를 전달하는 단계; 원격 제어신호 수신부가 사용자 단말기에서 구동되는 반려동물소통 전용 앱을 통해 상기 욕구 신호 전달부에서 전달한 욕구 신호에 매칭되는 욕구 해소 장치의 원격 제어 신호를 수신하는 단계; 및원격 제어신호 전달부가 상기 원격 제어신호 수신부로 수신되는 원격 제어 신호를 적어도 하나의 욕구해소 장치와 근거리 무선 통신을 수행하는 제어신호 중개장치를 경유하여 욕구 해소 장치로 전달하는 단계;를 포함하고, 상기 욕구 신호를 전달하는 단계는,상기 반려동물소통 전용 앱의 채팅 기능을 통해 상기 반려동물 욕구 신호를 구어체로 변환하여 전달하되, 상기 반려동물 욕구신호에 따른 키워드를 파악하고, 기저장된 대화체 문장들 중 상기 키워드를 포함하는 문장을 선별하여 상기 반려동물소통 전용 앱의 채팅 기능을 통해 전달하고, 상기 욕구 해소 장치는 사료 급식기, 간식 급식기, 놀이보조기, 영상통화장치, 스피커 중 적어도 하나이며, 상기 욕구 신호를 전달하는 단계는,제어신호 중개장치의 칩 인식부로부터 칩 인식 신호를 수신하여 반려 동물의 식별 정보를 함께 사용자 단말기로 전달하고, 상기 반려동물소통 전용 앱의 채팅 기능을 통해 반려 동물의 식별 정보에 따라 해당 반려동물과의 채팅 기능을 제공하는 사물 인터넷 기반의 반려동물 소통기능 제공방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

759/1150 Row 759: application_number: 1020200065966, combined_string: invention_title: 가축 모니터링을 위한 체결 장치 abstract: 본 발명은 가축 모니터링을 위한 체결 장치에 관한 것으로서, 더욱 상세히는 가축의 몸체에 부착되어 가축의 건강 상태를 모니터링하기 위한 체결 장치에 관한 것이다. 본 발명은 가축의 몸체에 안정적으로 고정 부착되어 센서부를 통해 가축의 건강 상태와 관련된 생체 신호를 수집하여 센싱 정보를 생성하고, 해당 센싱 정보를 다수의 가축을 관리하는 외부 장치에 전송하여, 외부 장치에서 해당 센싱 정보에 포함된 식별자를 기초로 가축을 식별할 수 있도록 지원함과 아울러 해당 센싱 정보의 센싱 신호를 통해 가축의 건강 상태를 체크할 수 있도록 지원함으로써, 방목 중인 다수의 가축별로 건강 상태를 용이하게 파악할 수 있도록 지원하여 가축 관리의 효율성을 높일 수 있도록 지원하는 동시에 가축의 몸체의 다양한 부위에 부착된 센서를 통해 가축의 건강 상태에 대한 더욱 정확한 정보를 제공하는 효과가 있다. claims: 소, 양 또는 말 중 어느 하나인 방목 대상 가축의 아래턱을 감싸도록 상기 가축의 하관 중에서 아래턱을 감싸도록 밀착되는 커버판;상기 커버판의 상단부에 구비되어 상기 가축의 주둥이 일부를 감싸지만 음식 섭취나 되새김질은 가능하도록 걸쳐져 고정되는 제 1 스트랩을 포함하는 제 1 벨트부;상기 커버판의 하단부에 구비되어 상기 가축의 목 둘레를 감싸도록 걸쳐져 고정되는 제 2 스트랩을 포함하는 제 2 벨트부;상기 커버판이 상기 아래턱에 밀착된 상태에서 상기 커버판의 하면에 구성되어 상기 가축의 신체 상태를 센싱하는 제 1 센서부;스트랩 형태로 구성되면서 상기 가축의 몸체 상부에 배치되어, 상단부가 상기 제 2 스트랩이 상기 목 둘레에 걸쳐질 때 상기 제 2 스트랩의 하면과 밀착되어 고정되는 본체부;상기 본체부의 하단부에 구비되어 상기 가축의 몸체 중 배 둘레를 감싸도록 걸쳐져 고정되는 제 3 스트랩을 포함하는 제 3 벨트부;상기 제 3 스트랩에서 상기 가축의 배와 마주보는 면과 반대면에 구성되어 가축의 신체 상태를 센싱하는 제 2 센서부; 및상기 본체부에서 상기 가축의 등과 마주보는 면과 반대면에 구비되며, 외부 장치와 통신망을 통신하는 통신 모듈과 상기 제 1 센서부 및 제 2 센서부와 연결되는 제어 모듈을 포함하여 구성되고, 상기 제어 모듈이 상기 제 1 센서부 및 제 2 센서부로부터 수신된 센싱 신호를 기초로 생성된 센싱 정보를 생성하여 상기 통신 모듈을 통해 상기 외부 장치로 전송하도록 구성되는 제어부를 포함하되,상기 제 1 벨트부의 제 1 스트랩 일부에 구성되고, 상기 제어 모듈과 연결되어 상기 제 1 스트랩의 신장 여부를 진동 센서 또는 스트레인 게이지로 감지하여 생성한 감지 신호를 상기 제어 모듈로 전송하는 제 3 센서부를 더 포함하며,상기 제어 모듈은 상기 감지 신호를 기초로 음식 섭취에 대한 감지 정보를 생성 후 상기 통신 모듈을 통해 상기 외부 장치로 전송하는 것을 특징으로 하는 가축 모니터링을 위한 체결 장치., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

760/1150 Row 760: application_number: 1020200059853, combined_string: invention_title: 반려동물 건강 관리 시스템 abstract: 반려동물 건강 관리 시스템이 개시된다. 일 실시예에 따른 반려동물 건강 관리 방법은, 반려동물 건강 관리 장치가 반려동물의 건강을 관리하는 방법에 있어서, 상기 반려동물에게 장착된 센싱 장치로부터 상기 반려동물의 움직임을 측정한 센서 데이터를 수신하는 단계와, 상기 센서 데이터에 기초하여 상기 반려동물의 행동 데이터를 생성하는 단계와, 상기 행동 데이터에 따라 급식량을 결정하는 단계와, 상기 행동 데이터 및 상기 급식량에 따라 급식된 사료에 대한 상기 반려동물의 식사량에 기초하여 상기 반려동물의 건강 상태를 판단하는 단계를 포함한다. claims: 반려동물 건강 관리 장치가 반려동물의 건강을 관리하는 방법에 있어서,상기 반려동물에게 장착된 센싱 장치로부터 상기 반려동물의 움직임을 측정한 센서 데이터를 수신하는 단계;상기 센서 데이터에 기초하여 상기 반려동물의 행동 데이터를 생성하는 단계;상기 행동 데이터에 따라 급식량을 결정하는 단계; 및상기 행동 데이터 및 상기 급식량에 따라 급식된 사료에 대한 상기 반려동물의 식사량에 기초하여 상기 반려동물의 건강 상태를 판단하는 단계를 포함하는 반려동물 건강 관리 방법.반려동물에게 장착된 센싱 장치로부터 상기 반려동물의 움직임을 측정한 센서 데이터를 수신하는 수신기; 및상기 센서 데이터에 기초하여 상기 반려동물의 행동 데이터를 생성하고, 상기 행동 데이터에 따라 급식량을 결정하고, 상기 행동 데이터 및 상기 급식량에 따라 급식된 사료에 대한 상기 반려동물의 식사량에 기초하여 상기 반려동물의 건강 상태를 판단하는 컨트롤러를 포함하는 반려동물 건강 관리 장치., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

761/1150 Row 761: application_number: 1020200052484, combined_string: invention_title: 가축 급이기의 사료배출장치 abstract: 본 발명은 축사 내부를 따라 설치되며 사료를 이송하는 사료이송관에 설치되며 상기 사료이송관으로 이송중인 사료를 축사 바닥에 설치되어 있는 사료저장통으로 배출하는 가축 급이기의 사료 배출장치에 있어서, 상기 사료이송관의 사료배출구멍에 설치되는 연결관, 상기 연결관에 선단이 연결되고 그 끝단은 사료저장통의 일측 가장자리에 근접하게 위치하도록 하되, 내부에 형성되어 있는 유로로 사료가 흘러갈 수 있도록 선단에서 끝단으로 갈수록 하향으로 점차적으로 기울어지게 배치되는 제 1사료배출관, 상기 제 1사료배출관의 반대편에 위치하며 상기 연결관에 선단이 연결되고 그 끝단은 사료저장통의 타측 가장자리에 근접하게 위치하도록 하되, 내부에 형성되어 있는 유로로 사료가 흘러갈 수 있도록 선단에서 끝단으로 갈수록 하향으로 점차적으로 기울어지게 배치되는 제 2사료배출관, 상기 제 1, 2사료배출관의 하면에 일정간격 떨어진 상태로 연결 설치되며 상기 제 1, 2사료배출관의 유로로 공급된 사료를 상기 사료저장통의 전 구역으로 배출시키는 적어도 하나 이상의 분배관으로 구성함을 특징으로 하는 가축 급이기의 사료배출장치를 제공한다. claims: 축사 내부를 따라 설치되며 사료를 이송하는 사료이송관(10)에 설치되며 상기 사료이송관(10)으로 이송중인 사료를 축사 바닥에 설치되어 있는 사료저장통(60)으로 배출하는 가축 급이기의 사료 배출장치에 있어서,상기 사료이송관(10)의 사료배출구멍(12)에 설치되는 연결관(20);상기 연결관(20)에 선단(30a)이 연결되고 그 끝단(30b)은 사료저장통(60)의 일측(60a) 가장자리에 근접하게 위치하도록 하되, 내부에 형성되어 있는 유로(32)로 사료가 흘러갈 수 있도록 선단(30a)에서 끝단(30b)으로 갈수록 하향으로 점차적으로 기울어지게 배치되는 제 1사료배출관(30);상기 제 1사료배출관(30)의 반대편에 위치하며 상기 연결관(20)에 선단(40a)이 연결되고 그 끝단(40b)은 사료저장통(60)의 타측(60b) 가장자리에 근접하게 위치하도록 하되, 내부에 형성되어 있는 유로(42)로 사료가 흘러갈 수 있도록 선단(40a)에서 끝단(40b)으로 갈수록 하향으로 점차적으로 기울어지게 배치되는 제 2사료배출관(40);상기 제 1, 2사료배출관(30, 40)의 하면에 일정간격 떨어진 상태로 연결 설치되며 상기 제 1, 2사료배출관(30, 40)의 유로(32, 42)로 공급된 사료를 상기 사료저장통(60)의 전 구역으로 배출시키는 적어도 하나 이상의 분배관(50)으로 구성함을 특징으로 하는 가축 급이기의 사료 배출장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

762/1150 Row 762: application_number: 1020200050518, combined_string: invention_title: 반려동물 케어 시스템 abstract: 반려동물 케어 시스템은 반려동물의 소음을 감지하여 현재 위치로부터 소음원에 대한 방향을 측정하는 소음원 감지부와, 소음원 감지부로부터 측정된 방향으로 이동하기 위한 구동력을 제공하는 주행부와, 적외선 센서 및 근접 센서를 구비하여 주행부에 의해 소음원을 향해 이동함에 따라 반려동물의 위치 및 근접 상태를 측정하는 반려동물 감지부와, 미리 결정된 조건에 따라 반려동물에게 먹이를 공급하는 먹이 공급부를 포함한다. claims: 반려동물의 소음을 감지하여 현재 위치로부터 소음원에 대한 방향을 측정하는 소음원 감지부;상기 소음원 감지부로부터 측정된 방향으로 이동하기 위한 구동력을 제공하는 주행부;적외선 센서 및 근접 센서를 구비하여 상기 주행부에 의해 소음원을 향해 이동함에 따라 반려동물의 위치 및 근접 상태를 측정하는 반려동물 감지부; 및미리 결정된 조건에 따라 반려동물에게 먹이를 공급하는 먹이 공급부를 포함하는 반려동물 케어 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

763/1150 Row 763: application_number: 1020200050042, combined_string: invention_title: 반려동물 비문인식 블록체인 플랫폼 abstract: 본 발명은 반려동물 비문인식 블록체인 플랫폼에 관한 것으로서, 보다 상세하게는 동물의 비문 이미지를 촬영하는 촬영부와, 촬영된 이미지로부터 비문데이터를 획득하는 분석부, 획득한 비문데이터를 저장하는 데이터베이스부로 이루어지되, 비문의 조직편을 식별하도록 하여 반려동물의 인식률을 상승시키고, 비문데이터를 ERC-20 기반의 블록체인 네트워크를 이용하여 저장함에 따라 보안성을 향상시키며, 등록 및 검색의 간편화를 기대할 수 있어, 보호자가 손쉽게 데이터를 업로드 및 공유할 수 있도록 고안된 반려동물 비문인식 블록체인 플랫폼에 관한 것이다. claims: 동물의 비문 이미지를 촬영하도록 사용자 단말기(M)에 구비되는 촬영부(SV);촬영된 이미지를 전송받아 비문 데이터를 획득하는 분석부(20);상기 비문 데이터와, 소유주가 입력한 소유주정보가 블록체인 네트워크를 통하여 저장되는 데이터베이스부(10);상기 사용자 단말기를 통해 상기 데이터베이스부에 접속하여, 상기 비문 데이터를 검색 및 출력하는 접속부(40);를 포함하여 이루어지되,상기 데이터베이스부(10)에는비문 데이터를 저장하는 저장하드(H)를 탈착 가능하게 결합 및 연결할 수 있도록 이루어지되,상기 저장하드(H)는 접속단자를 노출시키는 덮개(C1)가 구비되는 케이스(C)에 보관되어 저장하드(H) 내부에 이물질이 유입되는 것을 방지하며,상기 덮개(C1)는 상기 케이스(C)에 탈착수단(70)에 의해 탈착 가능하게 결합되되,상기 탈착수단(70)은상기 케이스(C)에 구비되며 인입부가 구비된 제1블록(71)과, 상기 제1블록(71)의 인입부(713)에 삽입되는 인입바(723)가 구비되어 상기 제1블록(71)에 슬라이딩 결합되도록 덮개(C1)에 구비되는 제2블록(72) 및 상기 제1블록(71)과 제2블록(72)의 결합력을 유지하는 복수의 고정볼(74)을 포함하여 이루어져, 상기 케이스(C)와 덮개(C1)는 원터치 결합 및 분리가 가능하게 이루어지되,상기 케이스(C)의 일단에 구비되는 제1블록(71)은내부에는 수직방향으로 형성되는 낙하공(711A)과, 상기 낙하공의 하부(711Ab)에서 후방 수평방향으로 연통되며 전방에 제1인출공(714)이 연통된 안착공(711B)과, 상기 안착공(711B) 후방과 상기 낙하공(711A) 상부를 연결하는 곡선형의 위치변위공(711D)이 구비되고,상기 제1인출공(714)에는 반구형의 고정체(717)가 인입부(713)로 돌출 가능하게 힌지결합되며,상기 덮개에 구비되는 제2블록(72)의 인입바(723)에는 상기 인입부(713) 방향으로 돌출된 고정체(717)가 삽입되는 고정홈(723A)이 형성되며,상기 복수개의 고정볼(74)이 상기 안착공(711B)에 채워져 상기 고정체(717)의 후단을 지지하여 상기 고정체(717)가 제1블록(71) 내측으로 인입되는 것을 방지하여 제1블록(71)과 제2블록(72)의 고정력을 유지하고,상기 제1블록(71)에는상기 안착공(711B)에 채워진 최후방의 고정볼(74)을 상기 위치변위공(711D)을 통해 낙하공(711A) 상부로 위치이동시켜, 상기 고정체(717)가 제1블록(71) 내측으로 인입되는 것을 허용하여 상기 제1블록(71)과 제2블록(72)을 슬라이딩 결합 및 해정 시킬 수 있도록 하는 위치변위수단(75)이 더 구비되는 것을 특징으로 하는 비문인식 블록체인 플랫폼., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

764/1150 Row 764: application_number: 1020210079993, combined_string: invention_title: 모듈형 다품종 식물 재배를 위한 농장 시스템 및 그 방법 abstract: 본 발명의 일 실시예에 따른 모듈형 다품종 식물 재배를 위한 농장 시스템은, 재배될 식물이 수용되는 재배함, 재배함이 놓여지는 다층의 재배 데스크, 식물의 재배함으로 광을 제공하기 위한 광 제공부, 재배 데스크가 위치한 공간의 온도 및 습도를 유지하기 위한 항온항습부, 식물로 양액을 공급하기 위한 양액공급부, 시스템의 동작을 제어하기 위한 제어부 및 식물의 재배와 관련된 정보가 수집되고 처리되는 서버가 포함되고, 서버는 네트워크를 통하여 타 디바이스와 연결되어 연동 가능하고, 재배함에 수용된 다품종의 식물에 따라 미리 설정된 광이 광 제공부를 통하여 식물로 제공되며, 제어부에서는 재배함별로 통신을 통하여 재배함 내의 식물의 생장 상태정보를 체크하고, 광 제공부, 항온항습부 및 양액공급부 중 적어도 하나를 동작시킬 수 있다. claims: 모듈형 다품종 식물 재배를 위한 농장 시스템으로서, 재배될 식물이 수용되는 복수의 재배함;상기 복수의 재배함이 놓여지는 다층의 재배 데스크;상기 복수의 재배함 중 대응하는 재배함의 상측에 각각 배치되는 복수의 광 제공부;상기 재배 데스크가 위치한 공간의 온도 및 습도를 유지하기 위한 항온항습부;양액을 수용하는 양액탱크, 상기 양액탱크와 연결되고 상기 복수의 재배함 각각에 대응하는 복수의 양액펌프, 상기 복수의 양액펌프에 연결되는 복수의 양액수로관, 및 상기 복수의 양액수로관의 단부에 연결되고 상기 복수의 재배함 각각의 내부에 위치하는 양액노즐을 포함하는 양액공급부;상기 시스템의 동작을 제어하기 위한 제어부; 및상기 복수의 재배함 각각에 대응하는 복수의 서브 제어 모듈을 포함하고,상기 복수의 서브 제어 모듈은, 방수의 함체 내부에 수용되어, 대응하는 재배함에 인접 배치되고,적어도 일부가 데이지 체인 구조로 연결되어 상기 제어부와 신호를 송수신하고, 식물의 생장 상태정보에 기초하여 상기 제어부로부터 수신되는 제어 신호에 기초하여, 인접 배치된 재배함에 대응하는 광 제공부 및 양액펌프의 동작을 제어하고,상기 제어부는,상기 식물의 생장 상태정보에 기초하여 상기 항온항습부의 동작을 제어하는,모듈형 다품종 식물 재배를 위한 농장 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

765/1150 Row 765: application_number: 1020210045649, combined_string: invention_title: 음성인식을 이용한 스마트팜의 제어방법 abstract: 본 발명은 음성인식을 이용한 스마트팜의 제어방법에 관한 것으로, 음성인식을 기반으로 명령을 수행 및 인식할 뿐만 아니라, 누적된 제어 데이터 값 및 주변 환경에 대한 조절인자 값을 분석하여 각 상화 및 시기별로 자동제어 될 수 있게 하기 위한 것이다. 본 발명에 따른 음성인식을 이용한 스마트팜의 제어방법은 미리 정해놓은 시간 간격에 따라 제1 농작물 시설하우스 내부 또는 외부에 설치된 대기온도센서, 지온온도센서, 습도센서, 일사량 측정 센서, CO2 센서를 포함하는 환경센서로부터 수집된 환경정보를 제어부로 전달하는 제1 환경정보 센싱단계; 환경조절모듈이 농작물 시설하우스 내 창 개폐수단, 조명조절수단, 난방수단, CO2 공급수단, 광차폐수단, 천연추출물 제공수단 및 습도조절수단을 포함하는 환경조절수단이 동작하였을 때 예상되는 농작물 시설하우스 내 예상환경정보를 예측하는 환경예측단계; 상기 환경예측단계의 예상환경정보를 사용자 단말기로 전송하는 환경정보제공 단계; 사용자 단말기로부터 음성인식 신호를 수신하여 수신된 신호를 제어부에 전달하고, 미리 정해 놓은 시간 내에 사용자 단말기로부터 수신된 제어신호가 없으면, 의사결정모듈이 상기 환경조절모듈로부터 환경정보를 수신하여 생육작물의 이상적인 환경정보와 매칭시킨 뒤 미리 정해놓은 기준에 따라 제어동작에 의사결정을 하는 의사결정단계; 제어부에서 상기 의사결정모듈에서 제어정보를 수신하여 상기 환경조절수단을 제어하는 제어단계; 상기 제어단계 이후에 미리 정해놓은 시간 간격에 따라 상기 환경센서로부터 수집된 환경정보를 제어부로 전달하는 제2 환경정보 센싱단계를 포함하는 것이다. claims: 미리 정해놓은 시간 간격에 따라 제1 농작물 시설하우스 내부 또는 외부에 설치된 대기온도센서, 지온온도센서, 습도센서, 일사량 측정 센서, CO2 센서를 포함하는 환경센서로부터 수집된 환경정보를 제어부로 전달하는 제1 환경정보 센싱단계;환경조절모듈이 농작물 시설하우스 내 창 개폐수단, 조명조절수단, 난방수단, CO2 공급수단, 광차폐수단, 천연추출물 제공수단 및 습도조절수단을 포함하는 환경조절수단이 동작하였을 때 예상되는 농작물 시설하우스 내 예상환경정보를 예측하는 환경예측단계;상기 환경예측단계의 예상환경정보를 사용자 단말기로 전송하는 환경정보 제공단계;사용자 단말기로부터 음성인식 신호를 수신하여 수신된 신호를 제어부에 전달하고, 미리 정해 놓은 시간 내에 사용자 단말기로부터 수신된 제어신호가 없으면, 의사결정모듈이 상기 환경조절모듈로부터 환경정보를 수신하여 생육작물의 이상적인 환경정보와 매칭시킨 뒤 미리 정해놓은 기준에 따라 제어동작에 의사결정을 하는 의사결정단계;제어부에서 상기 의사결정모듈에서 제어정보를 수신하여 상기 환경조절수단을 제어하는 제어단계;상기 제어단계 이후에 미리 정해놓은 시간 간격에 따라 상기 환경센서로부터 수집된 환경정보를 제어부로 전달하는 제2 환경정보 센싱단계를 포함하는음성인식을 이용한 스마트팜의 제어방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

766/1150 Row 766: application_number: 1020210005447, combined_string: invention_title: 영농 시스템 및 농작업기 abstract: 농작 구획마다 실시되는 농작업의 내용을 비용을 포함시켜 기록하고, 실적 베이스에서 다음 농작업 계획을 세울 수 있는 영농 시스템을 제공한다.영농 시스템은, 농작지를 농작 구획마다 관리하는 농작 구획 관리부(41)와, 농작지에 계시적으로 실시되는 농작업을 나타내는 농작업 이벤트를 그 비용과 함께 농작 구획마다 관리하는 농작업 관리부(42)와, 실시된 농작업 이벤트의 내용과 비용을 농작업 실적으로서 기록하는 데이터 기록부(5)와, 농작업 이벤트의 내용과 비용을 포함하는 농작업 이벤트의 이력을 농작업 실적표로서 출력하기 위한 실적 출력 데이터를 생성하는 실적 출력 데이터 생성부(43)와, 농작업 실적에 기초하여, 계시적으로 실시되어야 할 농작업 이벤트를 표시한 농작업 계획서를 출력하기 위한 계획 출력 데이터를 생성하는 계획 출력 데이터 생성부(44)를 구비하고 있다. claims: 복수의 농작 구획으로 구분된 농작지를, 상기 농작 구획마다 관리하는 농작 구획 관리부와,상기 농작 구획별 농작물의 수득량 데이터 및 식미 데이터가 입력되는 데이터 입력부와,상기 데이터 입력부를 통해 취득한 수득량 데이터 및 식미 데이터를 대응하는 농작 구획에 할당하여 데이터 기록부에 기록하는 수확 평가 관리부와,과거의 시비 작업 계획과 상기 수득량 데이터 및 상기 식미 데이터에 기초하여 시비 작업 계획을 출력하는 계획 출력 데이터 생성부를 구비하고,상기 시비 작업 계획을 표시하는 모니터를 구비하고,상기 모니터는 포장별 수득량과 식미를 표시하는 표시 화면을 표시할 수 있으며, 선택된 농작 구획을 나타내는 포장 정보와 상기 선택된 농작 구획에서의 농작물의 수득량 및 식미를 나타내는 그래프가 상기 표시 화면에 각각 표시되는, 영농 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

767/1150 Row 767: application_number: 1020200179541, combined_string: invention_title: 농업배수의 비점오염원 저감을 위한 관리 시스템 abstract: 본 발명은 농업배수 수위 상태에 따라 물꼬 장치를 제어하기 위해 사물인터넷과 결합하여 모니터링하며, 물꼬 장치를 실시간 원격으로 제어함으로써, 농업배수의 비점오염이 저감되는 비점오염원 원격 관리 시스템에 관한 것이다. claims: 자동 또는 원격으로 농업배수의 비점오염원 배출이 기계식 또는 전기식 중 어느 하나의 방식으로 구동 제어되는 물꼬 장치(10);수위 변화를 검출하기 위해 내부에 상한 수위 센서선과 하한 수위 센서선이 분리된 2선식 검출센서가 포함되어 수위가 측정되는 측정 장치(20);물꼬 장치(10), 측정 장치(20), 서버(40) 및 단말기(50) 간의 통신을 하도록 하는 통신망(30);통신망(30)을 통하여 물꼬 장치(10), 측정 장치(20) 또는 단말기(50) 중 선택되는 어느 하나 이상으로부터 정보를 제공받아 확인, 비교 또는 저장하거나, 자동 제어 정보를 생성하는 서버(40); 및통신망(30)을 통하여 서버(40)로부터 정보를 제공받아 원격 제어 정보를 생성하여 서버(40)로 제공하는 단말기(50);를 포함하며,물꼬 장치(10)는 농업배수를 외부로 배출하거나, 배출을 막기 위한 수로부(120)가 탈착되기 위해 오목한 홈으로 형성된 제1공간부(111)와, 로프(130)가 걸림 고정 되기 위한 고정부재(112), 및 로프(130)가 연결된 수로부(120)의 열림과 닫힘을 제어하는 구동부(140)가 형성되기 위한 제2공간부(113)가 포함되어 논둑에 고정되는 고정부(110);제1공간부(111)에 탈착되어 비관개기에 분리되어 별도로 보관이 가능하며, 구동부(140)에 의해 로프(130)가 당겨지거나 풀려짐에 따라, 가동부(121)가 접히거나 펼쳐져지는 수로부(120); 고정부재(112)에 고정 및 가동부(121)에 관통되고, 구동부(140)에 결합되어 구동부(140)에 의해 당겨지거나, 풀어지는 로프(130); 제2공간부(113)에 배치되어 연결된 로프(130)의 당김과 풀림을 조절하여 가동부(121)를 접거나, 펼쳐 농업배수의 배출 상태를 조절하는 구동부(140);농업배수에 포함된 토사가 유출되는 것을 방지하기 위해 미로와 같은 형상으로 형성되되, 고정부(110)가 맞닿는 면에 유입구(151)가 형성되고, 유입구(151)와 반대되는 면에 배출구(152)가 형성되는 토사유출방지부(150); 및 농업배수에 포함된 비점오염원이 여과 및 흡착되기 위해 토사유출방지부(150)의 수로 부분에 배치되는 여과재(160);를 포함하고,통신망(30)은 사용자가 현장 방문 없이 원격으로 물꼬 장치(10)를 제어하기 위해 LoRa(Long Range modulation technique)가 사용되고,측정 장치(20)에 의해 측정된 수위 변화에 따라 통신망(30)을 통해 서버(40) 또는 단말기(50)로부터 실시간으로 자동 또는 원격으로 물꼬 장치(10)의 열림과 닫힘을 제어하여 농업배수의 비점오염원 배출을 저감시키는 것을 특징으로 하는, 농업배수의 비점오염원 저감을 위한 관리 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

768/1150 Row 768: application_number: 1020200126832, combined_string: invention_title: 기상요인을 고려한 북미 지역의 대두 수확량 예측 방법 abstract: 본 발명은 기상 자료 및 위성 자료를 이용하여 대두의 수율을 추정하고, 이를 기반으로 전체 대두의 수확량을 산정하는 기술에 관한 기술로, 기상 환경에 따른 작물의 수확량을 산출할 수 있는 바, 작황에 따른 가격 등락의 분석으로 생산량 변동에 따른 대책을 수립할 수 있는 효과가 있는 기술이다. claims: 추세 산출 모듈이 대두 수율() 및 대두 수율의 추세()를 산출하는 대두 수율의 추세 산정 단계(S1);상기 대두 수율의 추세 산정 단계에서 산출된 대두 수율()에서 농경 기술 발달에 따른 추세주기 성분()를 제거하고, 기상 요인에 따른 불규칙 성분인 변동 성분()을 추세 제거 모듈이 산출하는 대두 수율의 추세 제거 단계(S2); 미국 농무부에서 제공하는 ASD(Agricultural Statistics District) 단위별 CDL(Cropland Layer Data) 자료의 대두 재배 지역()과, 강수량, 최저기온, 일교차를 포함하는 기상 자료 및 위성 자료의 단위 면적당 시공간을 일치화하여, 평균하여 대상 해의 단위 면적당 대두의 수율을() 수율 예측 모듈이 예측하는 대두 수율 예측 단계(S3);상기 대두 수율의 예측 단계(S3)에서 예측된 대상 해의 단위 면적당 대두의 수율()과 대두 재배 지역으로 대두의 수확량을 수확량 추정 모듈이 추정하는 연간 대두 수확량 추정 단계(S4); 및상기 연간 대두 수확량 추정 단계(S4)에서 추정된 대두의 수확량을 미국 농무부에서 제공하는 직전 년도로부터 6년간의 경작 빈도 중, 대두의 경작 횟수가 1회 또는 2회인 지역 전체에서 대두가 경작될 때의 연간 총 수확량()과, 대두의 경작 횟수가 3회 이상 6회 이하인 지역 전체에서 대두가 경작될 때의 연간 총 수확량()의 앙상블 가중 평균하는 다음의 수학식으로 수확량 산출 모듈이 연간 대두의 총 수확량()을 산출하는 연간 대두의 수확량 산출 단계(S5);를 포함하고,상기 연간 대두의 총 수확량()은의 수학식으로 산출되고,여기서, 는 t년도의 대두 총 수확량, 는 대두의 경작 횟수가 1회 또는 2회인 지역 전체에서 대두가 경작될 때의 연간 총 수확량, 는 대두의 경작 횟수가 3회 이상 6회 이하인 지역 전체에서 대두가 경작될 때의 연간 총 수확량, 는 대두의 경작 횟수가 1회 또는 2회인 지역 전체에서 대두가 경작될 때의 대두 파종 면적, 는 대두의 경작 횟수가 3회 이상 6회 이하인 지역 전체에서 대두가 경작될 때의 대두 파종 면적, 은 상기 대두 수율의 추세 산정 단계(S1)의 대두 수율의 추세()에 대한 상관 계수()의 제곱값이 하위 20%인 ASD 개수()의 평균()이며,상기 대두 수율의 추세 산정 단계(S1)에서 추정하는 상기 대두 수율의 추세()는 최근 10년의 통계를 활용하여 추정하고,상기 대두 수율의 추세 제거 단계(S2)의 추세주기 성분()는 0으로 판단하며,상기 대두 수율의 추세 제거 단계(S2)의 상기 불규칙 성분인 변동 성분()은의 수학식으로 산출되고,여기서, 는 파종 이후부터 예측 시점까지의 16일 간격 순번이고, 는 번째 16일간의 일 최고 기온의 평균, 는 번째 16일간의 일 최저 기온의 평균, 는 번째 16일간의 일 누적 강수량의 평균, 는 번째 16일간의 위성관측 NDVI의 관측값, , , , , 는 회귀 계수, 는 잔차(Residual)인 기상요인을 고려한 북미 지역의 대두 수확량 예측 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

769/1150 Row 769: application_number: 1020200119701, combined_string: invention_title: 시설 운영 이력을 저장할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 스마트팜 운영 시스템은, 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서를 포함하고 상기 환경정보를 포함하는 경작지정보를 생성하는 센서박스; 경작자가 상기 경작지정보를 기반으로 상기 재배환경을 조절하기위해 상기 시설장비를 작동시키는 제어정보를 포함하는 경작정보를 입력하는 경작자 단말기; 상기 제어정보를 기반으로 상기 시설장비를 작동시키는 제어박스; 및, 상기 경작지정보 및 상기 경작정보를 상기 작물의 생육단계에 매칭하여 저장하는 저장부를 가지는 정보서버;를 포함한다. claims: 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서를 포함하고 상기 환경정보를 포함하는 경작지정보를 생성하는 센서박스;경작자가 상기 경작지정보를 기반으로 상기 재배환경을 조절하기위해 상기 시설장비를 작동시키는 제어정보를 포함하는 경작정보를 입력하는 경작자 단말기;상기 제어정보를 기반으로 상기 시설장비를 작동시키는 제어박스; 및,상기 경작지정보 및 상기 경작정보를 상기 작물의 생육단계에 매칭하여 저장하는 저장부를 가지는 정보서버;를 포함하는 시설 운영 이력을 저장할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

770/1150 Row 770: application_number: 1020200119709, combined_string: invention_title: 센서박스 및 제어박스를 다채널로 구성할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 센서박스 및 제어박스를 다채널로 구성할 수 있는 스마트팜 운영 시스템은, 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서 및, 센서 송수신부를 포함하는 복수의 센서박스; 제어정보를 기반으로 상기 시설장비를 작동시키는 제어부 및 제어 송수신부를 포함하는 복수의 제어박스; 센서 송수신부 및 상기 제어 송수신부와 다중통신 방식으로 통신하여 상기 환경정보 및 상기 제어정보를 송수신하되, 상기 복수의 센서박스 및 상기 복수의 제어박스를 각각에 부여된 식별정보로 구분하는 게이트웨이 박스; 및 상기 게이트웨이 박스와 신호 연결되어 상기 환경정보 및 제어정보를 수신하여 저장하는 정보서버;를 포함한다. claims: 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서 및, 센서 송수신부를 포함하는 복수의 센서박스;제어정보를 기반으로 상기 시설장비를 작동시키는 제어부 및 제어 송수신부를 포함하는 복수의 제어박스;센서 송수신부 및 상기 제어 송수신부와 다중통신 방식으로 동시에 통신하여 상기 환경정보 및 상기 제어정보를 송수신하되, 상기 복수의 센서박스 및 상기 복수의 제어박스를 각각에 부여된 식별정보로 구분하는 게이트웨이 박스; 및상기 게이트웨이 박스와 신호 연결되어 상기 환경정보 및 제어정보를 수신하여 저장하는 정보서버;를 포함하는 센서박스 및 제어박스를 다채널로 구성할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

771/1150 Row 771: application_number: 1020200119716, combined_string: invention_title: 재배 이력을 추적할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 재배 이력을 추적할 수 있는 스마트팜 운영 시스템은, 작목이 재배되고 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 감지하여 환경정보를 생성하는 환경센서를 포함하는 센서부; 상기 환경정보를 기반으로 상기 시설장비를 작동시키는 제어정보와 상기 작목의 재배정보 및 상기 경작자의 이력정보를 포함하는 경작자정보를 상기 경작자가 입력하는 경작자 단말기; 상기 환경정보와 상기 제어정보와 상기 재배정보 및 상기 경작자정보를 수신하여 생산이력정보로 저장하는 저장부를 가지고 클라우드(cloud) 컴퓨팅을 기반으로 운영되는 정보서버; 상기 작목에서 재배된 농산품을 판매하는 판매처; 및 상기 농산품의 생산이력정보를 상기 정보서버로부터 수신하여 구매자에게 표시하는 구매자 단말기;를 포함한다. claims: 작목이 재배되고 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 감지하여 환경정보를 생성하는 환경센서를 포함하는 센서부;상기 환경정보를 기반으로 상기 시설장비를 작동시키는 제어정보와 상기 작목의 재배정보 및 상기 경작자의 이력정보를 포함하는 경작자정보를 상기 경작자가 입력하는 경작자 단말기;상기 환경정보와 상기 제어정보와 상기 재배정보 및 상기 경작자정보를 수신하여 생산이력정보로 저장하는 저장부를 가지고 클라우드(cloud) 컴퓨팅을 기반으로 운영되는 정보서버;상기 작목에서 재배된 농산품을 판매하는 판매처; 및 상기 농산품의 생산이력정보를 상기 정보서버로부터 수신하여 구매자에게 표시하는 구매자 단말기;를 포함하는 재배 이력을 추적할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

772/1150 Row 772: application_number: 1020200061185, combined_string: invention_title: 작물 생육정보 모니터링 시스템 abstract: 본발명은 작물을 생산하는 곳에서 작물의 이미지를 촬영하여 생육과정 정보를 모니터링하는 것으로, 로봇기구부(100), 로봇제어부(200), 전원공급부(300), 로봇레일부(400)를 포함하여 형성된 생육측정 주행로봇(1000)과; 싱글보드(500), 3D깊이카메라(600)와 디스플레이(700), 초소형PC(800)가 포함되어 구비되되, 상기 생육측정 주행로봇에 장착되어 자동으로 작물을 촬영하거나 또는 주행로봇에서 분리하여 농업인이 수동으로 작물을 촬영할 수 있도록 형성된 생육관리 싱글보드PC(2000)와; 생육측정 주행로봇(1000)과 농업인이 3D깊이카메라(600)로 촬영된 생육정보를 데이타베이스하는 생육관리PC(3000)를 포함하여 형성되어 전문지식이 없는 농업인이 간편하게 자동 또는 수동으로 간편하게 작물의 생육과정을 측정할 수 있는 현저한 효과가 있다. claims: 작물을 생산하는 곳에서 작물의 이미지를 촬영하여 생육과정 정보를 모니터링하는 것으로, 로봇기구부(100), 로봇제어부(200), 전원공급부(300), 로봇레일부(400)를 포함하여 형성된 생육측정 주행로봇(1000)과; 싱글보드(500), 3D깊이카메라(600), 디스플레이(700), 소형PC(800)가 포함되어 구비되되, 상기 생육측정 주행로봇(1000)에 장착되어 자동으로 작물을 촬영하거나 또는 주행로봇에서 분리하여 농업인이 수동으로 작물을 촬영할 수 있도록 형성된 생육관리 싱글보드PC(2000)와; 상기 생육측정 주행로봇(1000)과 농업인이 3D깊이카메라(600)로 촬영된 생육정보를 데이타베이스화하는 생육관리PC(3000)를 포함하여 형성되는 작물 생육정보 모니터링 시스템에 있어서,상기 로봇기구부(100) 하부에는 하부플랫폼(110)이 형성되고, 상기 하부플랫폼 하부에는 난방용 파이프를 레일로 이용해 이동하는 주행축(120)이 구비되며, 상부에는 상하이동축(130) 그리고 암회전축(140), 로봇의 암 역할을 하는 매니퓰레이터(150), 카메라회전축(160), 카메라 상하틸트축(170)이 순차적으로 연결되며,상기 생육측정 주행로봇(1000)은 로봇운용PC(230)로부터 원점복귀, 위치이동, 자율주행의 지령을 받아 해당 명령을 수행하면서 작물의 측정부위를 촬영을 하는 것이며,상기 로봇제어부(200)는 주위 환경상태를 감지하는 온습도센서, 마그넷센서, 라이다센서, CCTV가 구비된 감지부(210)와, 상기 감지부로 측정된 주위 환경상태에 따라 생육측정 대상작물로 생육측정 주행로봇(1000)이 이동하여 촬영하도록 제어하는 제어부(220)와, 생육측정 주행로봇의 운용을 계획하고 조정하는 로봇운용PC(230)로 구성되고 상기 제어부는 로봇이 메인(main)명령을 수행하게 제어하는 로봇메인제어, 설정치를 추종(servo)하게 제어되는 서보제어, 제어를 단계적(step)으로 하게 하는 스텝제어, 입출력(input, output)을 제어하는 I/O제어를 통하여 로봇동작을 제어하며,로봇운용PC(230)를 통하여 로봇기구부(100)에 이동명령을 주기 위해서 상기 로봇운용PC의 데이타베이스와 생육관리PC(3000) 사이에 데이타베이스를 송수신 가능하게 구비하여, 생육측정 주행로봇(1000)을 현장에 설치 후 이상 발생시 원격에서 컨트롤하고 원격제어하여 정상운행이 가능하게 하며,상기 생육측정 주행로봇(1000)의 자세와 위치 방향 및 주변환경을 모니터링하기 위한 CCTV를 로봇기구부(100)에 설치하여 원격모니터링하며, 로봇운용PC(230)에 스케쥴링시스템을 적용하여 로봇이 예약된 일자에 매일, 매주, 정해진 시간에 무인 자동 운행이 가능하게 구비하며, 또한 온실마다 온실의 폭, 높이가 차이가 나기 때문에 주행로봇 각축의 환경설정을 하여 각축의 이동반경 설정이 가능하게 하고 영상이미지명을 정하여 영상이미지만으로 농장, 온실, 온실동, 작물위치를 알 수 있게 하며,상기 로봇레일부(400)는 온실난방용 파이프를 레일로 사용하여 로봇기구부(100)가 이동되며, 로봇기구부(100)와 로봇제어부(200)의 구동 및 제어에 있어서 레일주행휠(121) 및 보조주행휠(122) 외에 보조휠(123)을 구비하여 라인이설 및 설치작업을 수동으로 조작이 가능하게 하며, 작물라인의 시작점 및 최종점 인식을 위한 근접센서 및 추돌예방을 위한 라이다센서가 형성되고, 또한 모터구동 제어기를 로봇제어부(200) 내에 구비하여 제어하며생육관리 싱글보드PC(2000)는 싱글보드(500)와, 영상을 촬영하는 3D깊이카메라(600)와; 화면을 터치하는 디스플레이와(700); 프로그램을 내장할 수 있는 소형PC(800)가 포함되어 형성되되, 상기 싱글보드(500) 일면 일정부위에는 3D깊이카메라가 형성되고, 타면에는 화면을 터치하여 촬영을 조정하는 디스플레이(700)가 형성되며, 또한 내부에는 PC(800)가 내장되되, 상기 생육측정 주행로봇(1000)의 매니퓰레이터(150)에 장착되어 자동으로 작물을 촬영하거나 또는 주행로봇에서 분리하여 농업인이 수동으로 작물을 촬영할 수 있게 하며, 또한 의복에 센서를 착용한 농업인이 수동으로 온실의 임의위치에서 작물을 촬영한 후 로봇이 촬영할 경우,로봇은 농업인이 촬영한 지점을 온실내의 GPS에 의한 위치인식기반시스템에 의해 인지하여 로봇이 정해진 위치외에도 농업인이 임의로 촬영한 지점도 중복 촬영하여 생육정보를 서로 비교분석할 수 있도록 하고, 또한 촬영한 시간에 의한 빛의 광량에 따라 비교시 차이가 있으므로 사진을 촬영할시의 시각과 나아가 온도도 측정하여 로봇제어부(200)는 기후 및 온도에 따라 사진의 색상을 보정하게 하며,상기 생육관리 싱글보드PC(2000)로 작물을 측정하는 방법은 로봇제어부(200)가 먼저 측정대상 작물의 유인줄 끝에 번호인식표를 붙이고 시각적으로 번호표를 인식하여 대상작물을 찾고 번호표를 좌표 중앙에 위치시킨후 수직으로 내려와 작물 시작점을 찾은 후, 작물의 시작점부터 배지까지 내려오면서 작물의 측정부위의 좌표를 자동설정하고, 설정된 좌표에 의해 생육측정 주행로봇(1000)이 자동 주행하면서 영상 촬영을 하는 것을 특징으로 하는 작물 생육정보 모니터링 시스템, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

773/1150 Row 773: application_number: 1020200045662, combined_string: invention_title: 태양광 발전장치의 기초 구조물 abstract: 본 발명은 태양광 발전장치에 관한 것으로, 더욱 상세하게는 벼농사를 짓는 농지에 설치하여 태양광 발전을 할 수 있도록 하는 영농형 태양광 발전장치의 기초 구조물에 관한 것이다.본 발명의 실시예에 따른 영농형 태양광 발전장치의 기초 구조물는 벼농사를 위한 농지에 설치되는 영농형 태양광 발전장치의 기초 구조물에 있어서, 태양광발전패널; 상기 태양광발전패널을 고정하여 장착하기 위한 고정프레임; 상기 고정프레임을 상기 농지에 고정하기 위한 기초볼트유닛; 및 상기 고정프레임과 상기 기초볼트유닛을 연결하기 위한 연결프레임;을 포함하여 구성되고, 상기 태양광발전패널의 전체 면적은 상기 농지의 전체 면적 대비 70% 이하이고, 상기 태양광발전패널이 상기 고정프레임에 설치되는 높이는 상기 농지의 지면으로부터 2미터 이상이며, 상기 기초볼트유닛은 지지부 및 스크류부로 구성되고, 상기 지지부에는 상기 농지에 고여있는 물에 의한 부식을 방지하기 위한 부식방지부를 포함하는 것을 특징으로 한다.본 발명에 따르면, 기초볼트유닛이 농지에 고여있는 물에 의해 부식되지 않기 때문에 기초볼트유닛의 부식에 의해 태양광 발전장치 구조물의 안전에 문제가 발생하는 것을 방지할 수 있다는 있다. claims: 벼농사를 위한 농지에 설치되는 영농형 태양광 발전장치의 기초 구조물에 있어서,태양광발전패널(100);상기 태양광발전패널을 고정하여 장착하기 위한 것으로, 하부에 원통형 케이스 연결체(210)가 설치되고, 원통형 케이스 연결체(210)의 끝단에는 양측이 경사진 결합용 돌기(210a)가 설치되어 이루어지는 고정프레임(200);상기 고정프레임을 상기 농지에 고정하기 위한 기초볼트유닛(400); 및상기 고정프레임과 상기 기초볼트유닛을 연결하기 위한 연결프레임(300);을 포함하여 구성되고,상기 태양광발전패널의 전체 면적은 상기 농지의 전체 면적 대비 70% 이하이고,상기 태양광발전패널이 상기 고정프레임에 설치되는 높이는 상기 농지의 지면으로부터 2미터 이상이며,상기 기초볼트유닛은 지지부 및 스크류부로 구성되고, 상기 지지부에는 상기 농지에 고여있는 물에 의한 부식을 방지하기 위한 부식방지부를 포함하고;상기 연결 프레임(300)은,최외각에 설치되는 제 1 결합용 몸체(310)와;상기 제 1 결합용 몸체와 일정거리 이격되어 설치되어 공간부를 형성하여 공간부로 결합용 돌기가 진입되도록 하고, 일단에 결합용 홈을 형성하여 결합용 돌기가 삽입 고정되도록 하는 제 2 결합용 몸체(320)와;상기 제 1 결합용 몸체와 제 2 결합용 몸체 사이에 설치되는 제 1 스프링(330)과;상기 제 1 스프링 전단에 설치되어 제 1 결합용 몸체의 결합용 돌기가 진입하면 후퇴하여 제 1 스프링을 압박하고 결합용 돌기가 제 2 결합용 몸체의 결합용 홈에 삽입되면 제 1 스프링의 탄발에 의해 전진하여 결합용 돌기 상부에 위치되는 제 1 스프링 유동부(350)와;상기 제 1 스프링 유동부 후단에 설치되며 탄발 기능을 갖는 제 2 스프링(340)과;상기 제 2 스프링의 외측에 설치되어 제 2 스프링을 구동하는 원통형 형상의 구조체로서 뒤로 후퇴하면서 제 2 스프링을 구동하기 위한 제 2 스프링 유동부(360)와;상기 제 2 스프링의 후단에 설치되어 제 2 스프링의 움직임을 지지하기 위한 제 2 스프링 지지부(370)를 포함하여 구성함을 특징으로 하는 태양광 발전장치의 기초 구조물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

774/1150 Row 774: application_number: 1020200042452, combined_string: invention_title: 농업용 집단 드론 제공 시스템 abstract: 본 발명은 단말기가 드론 서비스를 제공받기 위해 접속하도록 하고, 상기 단말기로부터 드론 서비스의 제공을 위해 필요한 정보를 제공받는 서비스제공시스템; 상기 서비스제공시스템으로부터 상기 정보를 제공받고, 상기 정보에 따른 드론제어정보를 제공하며, 여러 지역에 분포하는 다수의 드론스테이션; 및 상기 드론스테이션 각각에 다수로 배치되고, 상기 드론제어정보에 상응하는 동작을 수행하는 드론;을 포함하도록 한 농업용 집단 드론 제공 시스템에 관한 것이다.본 발명에 따르면, 드론의 집단적인 사용을 가능하도록 하여, 드론의 효용성을 높일 수 있고, 넓은 지역에서의 드론을 효율적으로 사용하기 위한 신뢰성 높은 네트워크의 형성을 가능하도록 함으로써 드론 서비스의 질적인 향상을 가져올 수 있으며, 그 중요성이 점차 확대되고 있는 농업분야에 직접 적용됨으로써 활용도를 높일 수 있다. claims: 단말기가 농업에 필요한 드론 서비스를 제공받기 위해 접속하도록 하고, 상기 단말기로부터 드론 서비스의 제공을 위해 필요한 정보를 제공받는 서비스제공시스템;상기 서비스제공시스템으로부터 상기 정보를 제공받고, 상기 정보에 따른 드론제어정보를 제공하며, 여러 지역에 분포하는 다수의 드론스테이션; 및상기 드론스테이션 각각에 다수로 배치되고, 상기 드론제어정보에 상응하는 동작을 수행하는 드론;을 포함하고, 상기 서비스제공시스템은,상기 단말기가 무선통신망을 통해서 접속하기 위한 웹페이지를 제공하고, 상기 웹페이지를 통해서 상기 단말기로부터 드론을 이용한 작업장소 및 작업목적에 대한 정보를 제공받는 웹서버;상기 웹서버로부터 상기 작업장소 및 작업목적을 제공받고, 상기 드론스테이션에 대한 작업장소까지 거리와 드론 가동대수를 고려하여, 상기 작업목적의 수행을 위해 드론스테이션에 대한 드론의 사용대수 및 이동경로를 산출하는 드론산출부;상기 드론산출부에 의해 산출되는 드론의 사용대수를 해당하는 드론스테이션에게 해당 드론 각각의 이동경로와 함께 제공하는 드론할당부; 및 상기 드론산출부에 산출을 위해 필요한 데이터를 제공하도록 저장하는 데이터베이스부;를 포함하고,상기 드론스테이션은,상기 드론할당부로부터 드론의 사용대수를 제공받은 경우, 해당하는 사용대수의 드론 각각이 제공받은 이동경로를 따라 정해진 작업목적을 수행하도록 설정하는, 농업용 집단 드론 제공 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

775/1150 Row 775: application_number: 1020200030500, combined_string: invention_title: 영농형 스마트 태양광 발전 시스템 abstract: 본 발명은 영농형 스마트 태양광 발전 시스템에 관한 것으로서, 더욱 상세하게는 고정식 구조물에 복수의 회전식 태양광 패널을 설치하되, 링크부를 통해 복수의 태양광 패널이 일률적으로 회전될 수 있도록 설치하고, 고정식 구조물에 작업발판을 설치함으로써, 경작지 공간 효율성을 높여 경작지에 일조량이 충분히 확보될 수 있도록 하고, 태양광 패널 유지 보수 작업에 대한 효율성을 높인 영농형 스마트 태양광 발전 시스템에 관한 것이다.이를 위해, 경작지로부터 상방으로 고정된 지주; 상기 지주의 상단부에 설치된 탑프레임; 상기 탑프레임을 따라 탑프레임에 대하여 수직한 방향으로 설치된 복수의 지지프레임; 상기 각 지지프레임에 등간격으로 복수로 설치되며, 태양광을 따라 회전될 수 있도록 설치된 태양광 패널; 상기 복수의 태양광 패널을 동시에 연동시키는 링크부; 및 상기 링크부를 구동시켜 복수의 태양광 패널이 동시에 일방향으로 움직일 수 있도록 한 구동부:를 포함하며, 상기 링크부는, 상기 탑프레임을 따라 설치되며, 양단부는 상기 지지프레임에 축 결합된 메인축; 상기 지지프레임마다 각 지지프레임에 대응되게 마련된 복수의 연결로드; 상기 메인축과 상기 각각의 연결로드 사이에 설치되며, 상기 메인축의 회전운동을 상기 연결로드의 왕복운동으로 가변시키는 연동브라켓; 상기 연결로드와 상기 태양광 패널 사이에 설치되며, 상기 연결로드의 왕복운동을 태양광 패널의 회전운동으로 가변시키는 가변수단:을 포함하는 영농형 스마트 태양광 발전 시스템을 제공한다. claims: 경작지로부터 상방으로 고정된 지주;상기 지주의 상단부에 설치된 탑프레임;상기 탑프레임을 따라 탑프레임에 대하여 수직한 방향으로 설치된 복수의 지지프레임;상기 각 지지프레임에 등간격으로 복수로 설치되며, 태양광을 따라 회전될 수 있도록 설치된 태양광 패널;상기 복수의 태양광 패널을 동시에 연동시키는 링크부; 및상기 링크부를 구동시켜 복수의 태양광 패널이 동시에 일방향으로 움직일 수 있도록 한 구동부:를 포함하며,상기 링크부는,상기 탑프레임을 따라 설치되며, 양단부는 상기 지지프레임에 축 결합된 메인축;상기 지지프레임마다 각 지지프레임에 대응되게 마련된 복수의 연결로드;상기 메인축과 상기 각각의 연결로드 사이에 설치되며, 상기 메인축의 회전운동을 상기 연결로드의 왕복운동으로 가변시키는 연동브라켓;상기 연결로드와 상기 태양광 패널 사이에 설치되며, 상기 연결로드의 왕복운동을 태양광 패널의 회전운동으로 가변시키는 가변수단:을 포함하는 영농형 스마트 태양광 발전 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

776/1150 Row 776: application_number: 1020200014323, combined_string: invention_title: 토양 상태에 따라 식물의 생장을 예측, 분석하는 방법, 장치 및 프로그램 abstract: 본 발명은 토양 상태에 따라 식물의 생장을 예측, 분석하는 서버에 관한 것으로, 재배 구역 각각의 토양 조건과, 토양의 농작물 재배 이력, 휴경 여부 중 적어도 하나를 포함하는 사용자 조건을 조건 테이블에 시뮬레이션 하여, 각 재배 구역에 대하여 작물 후보군을 도출하고, 재배실력지수와 선호작물 정보를 반영하여 상기 작물 후보군 중 적어도 하나의 추천 작물을 선택해주는 효과가 있다. claims: 복수의 토양 조건과 환경 조건에 따른 농작물 추천 정보가 기록된 조건 테이블이 저장된 데이터베이스;사용자의 토양에 설치된 하나 이상의 센서로부터 센싱된 정보, 및 사용자 단말로부터 입력된 사용자 조건과 토양의 정보를 수집하는 수집부;상기 수집된 정보로부터 토양의 위치별 조건을 체킹하여 사용자의 토양을 구획하고, 사용자 토양의 총 면적을 고려하여 상기 토양을 하나 이상의 재배 구역으로 구획하는 농지 구획부;사용자로부터 입력된 사용자의 농작물 재배 경력, 예산 및 재배 장비를 기초로 하여 사용자의 재배실력지수를 산출하는 산출부; 및상기 구획된 재배 구역 각각의 토양 조건과, 상기 토양의 농작물 재배 이력, 휴경 여부 중 적어도 하나를 포함하는 사용자 조건을 상기 조건 테이블에 시뮬레이션 하여, 상기 각 재배 구역에 대하여 작물 후보군을 도출하고, 재배실력지수와 선호작물 정보를 반영하여 상기 작물 후보군 중 적어도 하나의 추천 작물을 선택하는, 인공지능모듈을 포함하는, 토양 상태에 따라 식물의 생장을 예측, 분석하는 서버.서버에 의해 수행되는 방법으로,사용자의 토양에 설치된 하나 이상의 센서로부터 센싱된 정보, 및 사용자 단말로부터 입력된 사용자 조건과 토양의 정보를 수집하는 단계;상기 수집된 정보로부터 토양의 위치별 조건을 체킹하여 사용자의 토양을 구획하고, 사용자 토양의 총 면적을 고려하여 상기 토양을 하나 이상의 재배 구역으로 구획하는 단계;사용자로부터 입력된 사용자의 농작물 재배 경력, 예산 및 재배 장비를 기초로 하여 사용자의 재배실력지수를 산출하는 단계;상기 구획된 재배 구역 각각의 토양 조건과, 상기 토양의 농작물 재배 이력, 휴경 여부 중 적어도 하나를 포함하는 사용자 조건을 상기 조건 테이블에 시뮬레이션 하여, 상기 각 재배 구역에 대하여 작물 후보군을 도출하는 단계; 및상기 재배실력지수와 선호작물 정보를 반영하여 상기 작물 후보군 중 적어도 하나의 추천 작물을 선택하는 단계를 포함하고,상기 서버는,복수의 토양 조건과 환경 조건에 따른 농작물 추천 정보가 기록된 조건 테이블이 저장된 데이터베이스를 포함하는, 토양 상태에 따라 식물의 생장을 예측, 분석하는 방법.하드웨어인 컴퓨터와 결합되어, 제9항의 방법을 실행시키기 위하여 매체에 저장된, 토양 상태에 따라 식물의 생장을 예측, 분석하는 프로그램., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

777/1150 Row 777: application_number: 1020200001233, combined_string: invention_title: 영농 시스템 abstract: 과거에 행해진 농작업에 관한 데이터가 없어도, 가능한 한 효과적인 포장 작업 계획을 작성할 수 있는 영농 시스템을 제공하는 것이다. 영농 시스템은, 각 포장의 포장 특성 파일, 포장 작업 이력 파일, 포장 수확 파일을 포함하는 포장 파일을 저장하는 포장 파일 저장부(51)와, 포장 파일을 사용하여 지정 포장의 포장 작업 계획을 작성하는 작업 계획 작성부(52)와, 지정 포장을 위한 포장 파일이 포장 파일 저장부(51)에 저장되어 있지 않은 경우, 지정 포장을 위한 모의 포장 파일을 작성하여 작업 계획 작성부(52)에 부여하는 모의 파일 작성부(53)를 구비한다.또한, 예상 작업 실적과 실제 작업 실적 사이의 상이를 간단하게 평가할 수 있는 영농 시스템을 제공하는 것이다. 영농 시스템은, 구획별 포장 작업의 계획을 나타내는 작업 계획 맵을 작성하는 작업 계획 맵 작성부(1052)와, 작업 계획 맵에 기초하여 포장 작업의 시뮬레이션을 행하여 당해 시뮬레이션의 결과로서의 작업 예측 맵을 작성하는 작업 예측 맵 작성부(1053)와, 포장 작업을 실시한 포장 작업기에 의해 생성된 작업 데이터에 기초하여 작업 실적 맵을 작성하는 작업 실적 맵 작성부(1054)와, 작업 계획 맵, 작업 예측 맵, 작업 실적 맵 중 어느 것, 또는 전부를 상호 비교 가능하게 디스플레이(1058)에 표시하는 표시 제어부(1055)를 구비한다. claims: 포장 작업기에 의한 포장 작업을 관리하는 영농 시스템이며,각 포장의 포장 특성 파일, 포장 작업 이력 파일, 포장 수확 파일을 포함하는 포장 파일을 저장하는 포장 파일 저장부와,상기 포장 파일을 사용하여 지정 포장의 포장 작업 계획을 작성하는 작업 계획 작성부와, 상기 지정 포장을 위한 상기 포장 파일이 상기 포장 파일 저장부에 저장되어 있지 않은 경우, 상기 지정 포장을 위한 모의 포장 파일을 작성하여 상기 작업 계획 작성부에 부여하는 모의 파일 작성부를 구비한, 영농 시스템.포장 작업기를 사용하여 복수의 구획으로 구분된 포장을 관리하는 영농 시스템이며,상기 구획별로 포장 작업의 계획을 나타내는 작업 계획 맵을 작성하는 작업 계획 맵 작성부와,상기 작업 계획 맵에 기초하여 상기 포장 작업의 시뮬레이션을 행하여 당해 시뮬레이션의 결과로서의 작업 예측 맵을 작성하는 작업 예측 맵 작성부와,상기 포장 작업을 실시한 포장 작업기에 의해 생성된 작업 데이터에 기초하여 작업 실적 맵을 작성하는 작업 실적 맵 작성부와,상기 작업 계획 맵, 상기 작업 예측 맵, 상기 작업 실적 맵 중 어느 것, 또는 전부를 상호 비교 가능하게 디스플레이에 표시하는 표시 제어부를 구비한, 영농 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

778/1150 Row 778: application_number: 1020200000365, combined_string: invention_title: 딥러닝을 이용한 작물 질병 진단 기반 수확량 예측 시스템 및 방법 abstract: 러닝을 이용한 작물 질병 기반 수확량 예측 시스템 및 방법이 개시된다. 리프 이미지(leaf image)를 수집하여 이미지 프로세싱을 수행하는 이미지 프로세싱 모듈(image processing module, IPM); 상기 이미지 프로세싱 모듈에서 이미지 프로세싱이 수행된 리프 이미지를 이용하여 작물 질병을 진단하는 작물 질병 진단 모듈(crop disease diagnosis module, CDDM); 상기 작물 질병 진단 모듈에서 진단된 작물 질병을 기반으로 딥러닝(deep learning)을 수행하여 작물 수확량을 예측하는 작물 수확량 예측 모듈(crop yield prediction module, CYPM)을 구성한다. 상술한 딥러닝을 이용한 작물 질병 기반 수확량 예측 시스템 및 방법에 의하면, 작물의 드론 촬영 이미지를 이용하여 작물의 질병 발병 여부를 파악하도록 구성됨으로써, 작물의 질병 진단과 대처를 신속하고 정확하게 수행할 수 있는 효과가 있다. 또한, 딥러닝을 이용하여 작물 별로 더 많은 종류의 질병을 진단할 수 있게 됨으로써, 질병에 대한 진단의 정확도를 높이고 그에 대한 신속하고 정확한 대처를 가능하게 하는 효과가 있다. 그리고 작물의 질병에 기반하여 수확량을 예측할 수 있도록 구성됨으로써, 기존의 센서 데이터에 기반한 수확량 예측보다 더 정확한 예측을 할 수 있는 효과가 있다. claims: 인터넷 또는 AI 허브 이미지 네트워크(AI hub image network)에서 리프 이미지(leaf image)를 수집하여 이미지 프로세싱을 수행하는 이미지 프로세싱 모듈(image processing module, IPM);상기 이미지 프로세싱 모듈에서 이미지 프로세싱이 수행된 리프 이미지를 이용하여 CNN(convolutional neural network) 모델을 생성하고, 생성된 CNN 모델을 이용하여 작물 질병을 진단하는 작물 질병 진단 모듈(crop disease diagnosis module, CDDM);상기 작물 질병 진단 모듈에서 진단된 작물 질병을 기반으로 ANN(artificial neural network)을 이용하여 단위 면적당 작물 수확량을 예측하는 작물 수확량 예측 모듈(crop yield prediction module, CYPM)을 포함하고,상기 이미지 프로세싱 모듈은,상기 리프 이미지를 수집하거나 별도로 입력받는 이미지 수집/입력부;상기 이미지 수집/입력부에서 수집되거나 입력된 복수의 리프 이미지를 하나의 단일 리프 이미지로 전환하여 정규화하는 리프 이미지 정규화부;상기 리프 이미지 정규화부에서 정규화된 리프 이미지에 대해 질병명이 확실하게 진단된 이미지는 훈련용 이미지(training image)로 분류하고, 질병명이 확실하게 진단되지 않은 이미지는 테스트용 이미지(test image)로 분류하는 리프 이미지 분류부;상기 리프 이미지 분류부에서 분류된 리프 이미지가 저장되는 리프 이미지 저장부;상기 리프 이미지 저장부에 저장된 각 리프 이미지에 대해 R, G, B의 3채널 이미지로 변환하여 각각 출력하는 3채널 이미지 출력부를 포함하도록 구성되고,상기 이미지 수집/입력부는,AI 허브(hub) 이미지 네트워크를 통해 검색하거나 인터넷 상에서 웹 크롤링(web crawling)을 하여 리프 이미지를 수집하는 리프 이미지 수집부;질병 진단이나 수확량 예측을 위해 소정의 농장에서 드론을 통해 촬영되는 리프 이미지를 별도로 입력받는 리프 이미지 입력부를 포함하도록 구성되고,상기 리프 이미지 정규화부는,상기 복수의 리프 이미지에서 구글(Goolge) 사의 비젼 API(vision API)를 이용하여 단일 리프 영역의 좌측 상단, 우측 상단, 좌측 하단, 우측 하단의 좌표를 각각 리턴하여 하나의 영역인 단일 리프 이미지를 추출하는 단일 리프 이미지 추출부;상기 비젼 API에서 리턴한 좌표를 기준으로 단일 리프 이미지를 128*128 크기로 리사이징하여 정규화하는 리프 이미지 리사이징부를 포함하도록 구성되고,상기 리프 이미지 저장부는,상기 리프 이미지 분류부에서 훈련용 이미지로 분류된 리프 이미지가 저장되는 훈련용 리프 이미지 저장부;상기 리프 이미지 분류부에서 테스트용 이미지로 분류된 리프 이미지가 저장되는 테스트용 리프 이미지 저장부를 포함하도록 구성되고,상기 작물 질병 진단 모듈은,상기 3채널 이미지 출력부에서 출력된 R, G, B의 3채널 이미지를 입력받는 3채널 이미지 입력부;각 작물별로 CNN 모델을 생성하는 CNN 모델 생성부;상기 CNN 모델 생성부에 의해 생성된 CNN 모델에 따른 작물 질병 진단 결과를 출력하는 CNN 모델 출력부를 포함하도록 구성되고,상기 CNN 모델 생성부는,상기 3채널 이미지에 대하여 각각 3회의 CNN 모델을 생성하는 컨벌루션 수행부상기 3채널 이미지에 대하여 각각 3회의 서브-샘플링을 수행하는 서브-샘플링 수행부상기 컨벌루션 수행부 및 상기 서브-샘플링 수행부에 의해 산출된 컨벌루셔널 특징 맵을 이용하여 신경망 모델로 바꾸어 계산하는 CNN 모델 변환부를 포함하도록 구성되고,상기 작물 수확량 예측 모듈은,상기 작물 질병 진단 모듈에서 진단된 작물 질병 데이터를 수신하여 입력하는 작물 질병 데이터 수신/입력부;농장 서버로부터 농장 환경 데이터를 수신하여 입력하는 농장 환경 데이터 수신/입력부;기상 정보 제공 서버로부터 현재 날씨 및 재배/수확기의 예상 날씨를 포함하는 날씨 데이터를 수신하여 입력하는 날씨 데이터 수신/입력부;작물 수확 통계 서버로부터 작물별 수확량 통계 데이터를 수신하여 입력하는 작물별 수확량 통계 데이터 수신/입력부;상기 작물 질병 데이터 수신/입력부로부터 입력되는 작물 질병 데이터, 상기 농장 환경 데이터 수신/입력부로부터 입력되는 농장 환경 데이터, 상기 날씨 데이터 수신/입력부로부터 입력되는 날씨 데이터, 상기 작물별 수확량 통계 데이터 수신/입력부로부터 입력되는 통계 데이터에 기반하여 ANN을 이용하여 농장의 단위 면적당 수확량 및 농장의 면적에 따른 수확량을 산출하는 ANN 수확량 예측부;상기 ANN 수확량 예측부에서 예측된 수확량 예측 결과를 출력하는 수확량 예측 결과 출력부;상기 수확량 예측 결과 출력부에서 출력된 수확량 예측 결과를 상기 농장 서버 또는 농장주 단말로 송신하는 수확량 예측 결과 송신부를 포함하도록 구성되고,상기 컨벌루션 수행부는,상기 3채널 이미지를 n*n 정방 행렬을 이용하여 이미지를 스캔하여 이미지의 특징을 추출하고 그 결과물로서 컨벌루셔널 특징 맵(convolutional feature map)을 출력하며, 4*4 필터를 이용하여 이미지의 특징을 추출하되 첫 연산에서는 20개, 두번째 연산에서는 40개, 3번째 연산에서는 60개를 사용하여 총 3회의 컨벌루션 과정에서 스트라이드는 모두 1을 사용하고 이미지와 필터 사이에 ReLU 함수를 사용하여 컨벌루셔널 특징 맵을 산출하도록 구성되며,상기 서브-샘플링 수행부는,상기 컨벌루션 수행부에서 출력된 컨벌루셔널 특징 맵을 서브-샘플링을 통해 간소화하며, 소정 크기의 이미지 픽셀들 중 가장 특징이 강한 영역을 추출하여 하나의 픽셀로 만드는 2*2 맥스 풀링 기법을 이용하여 컨벌루셔널 특징 맵을 간소화하도록 구성되며,상기 CNN 모델 변환부는,16*16*60의 컨벌루셔널 특징 맵을 n 개의 출력 배열로 전환하되, 풀리 커넥티드 신경망을 이용하여 작물의 질병의 수와 같은 크기의 배열을 생성하며, 상기 n은 작물에서 발생할 수 있는 질병의 수로 구성되며,상기 CNN 모델 출력부는,각 작물의 정상 노드 1개와 각 작물이 가질 수 있는 질병의 수에 따른 n개의 질병 노드로 구성되는 출력 노드가 구비되며, 각 출력 노드를 통해 각 질병에 대한 0 내지 1의 값을 출력하고, 각 출력 노드의 값 중에서 가장 큰 값을 갖는 질병을 해당 작물의 질병으로 규정하도록 구성되는 것을 특징으로 하는 딥러닝을 이용한 작물 질병 진단 기반 수확량 예측 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

779/1150 Row 779: application_number: 1020190177587, combined_string: invention_title: 농업용 기계를 관리하는 방법 및 그 전자 장치 abstract: 본 발명의 다양한 실시 예들은, 농업용 기계를 관리하는 방법 및 그 전자 장치에 관한 것으로서, 전자 장치는, 제1 통신 회로, 제2 통신 회로, 출력 장치, 메모리, 및 상기 제1 통신 회로, 상기 제2 통신 회로, 상기 출력 장치, 및 상기 메모리와 연결된 프로세서를 포함하고, 상기 프로세서는, 상기 제1 통신 회로를 통해 농업용 기계로부터 상기 농업용 기계의 상태 정보를 수신하고, 상기 제2 통신 회로를 통해 상기 농업용 기계의 상태 정보를 서버로 송신하고, 상기 제2 통신 회로를 통해 상기 서버로부터 상기 농업용 기계가 이상 상태임을 나타내는 알림 정보를 수신되면, 상기 농업용 기계가 주행 중인지 여부를 결정하고, 상기 농업용 기계가 주행 중인 경우, 상기 출력 장치를 통해 상기 알림 정보를 출력할 수 있다. 다른 실시 예들도 가능하다. claims: 전자 장치에 있어서,제1 통신 회로;제2 통신 회로; 출력 장치;메모리; 및상기 제1 통신 회로, 상기 제2 통신 회로, 상기 출력 장치, 및 상기 메모리와 연결된 프로세서를 포함하고, 상기 프로세서는,상기 제1 통신 회로를 통해 농업용 기계로부터 상기 농업용 기계의 상태 정보를 수신하고,상기 제2 통신 회로를 통해 상기 농업용 기계의 상태 정보를 서버로 송신하고,상기 제2 통신 회로를 통해 상기 서버로부터 상기 농업용 기계가 이상 상태임을 나타내는 알림 정보를 수신되면, 상기 농업용 기계가 주행 중인지 여부를 결정하고, 및상기 농업용 기계가 주행 중인 경우, 상기 출력 장치를 통해 상기 알림 정보를 출력하는 전자 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

780/1150 Row 780: application_number: 1020190177592, combined_string: invention_title: 농업용 기계를 관리하는 방법 및 그 전자 장치 abstract: 본 발명의 다양한 실시 예들은, 농업용 기계를 관리하는 방법 및 그 전자 장치에 관한 것으로서, 전자 장치는, 제1 통신 회로, 제2 통신 회로, 출력 장치, 메모리, 및 상기 제1 통신 회로, 상기 제2 통신 회로, 상기 출력 장치, 및 상기 메모리와 연결된 프로세서를 포함하고, 상기 프로세서는, 상기 제1 통신 회로를 통해 농업용 기계로부터 상기 농업용 기계의 상태 정보를 수신하고, 상기 제2 통신 회로를 통해 상기 농업용 기계의 상태 정보를 서버로 송신하고, 상기 제2 통신 회로를 통해 상기 서버로부터 상기 농업용 기계가 이상 상태임을 나타내는 알림 정보를 수신하고, 상기 출력 장치를 통해 상기 알림 정보를 출력할 수 있다. 다른 실시 예들도 가능하다. claims: 제1 통신 회로;제2 통신 회로; 출력 장치;메모리; 및상기 제1 통신 회로, 상기 제2 통신 회로, 상기 출력 장치, 및 상기 메모리와 연결된 프로세서를 포함하고, 상기 프로세서는,상기 제1 통신 회로를 통해 농업용 기계로부터 상기 농업용 기계의 상태 정보를 수신하고,상기 제2 통신 회로를 통해 상기 농업용 기계의 상태 정보를 서버로 송신하고,상기 제2 통신 회로를 통해 상기 서버로부터 상기 농업용 기계가 이상 상태임을 나타내는 알림 정보를 수신하고, 및상기 출력 장치를 통해 상기 알림 정보를 출력하는 전자 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

781/1150 Row 781: application_number: 1020190177597, combined_string: invention_title: 인공지능 기반 스마트 작물 재배 관리장치, 및 그 방법 abstract: 본 발명은 스마트 작물 재배 관리장치 및 그 방법에 관한 것으로, 본 발명에 따른 스마트 작물 재배 관리장치는 작물이 생육되는 생육환경 정보를 센싱하는 환경센싱부; 상기 작물의 생육환경과 상기 작물이 양액을 흡수하는 양액 흡수량 간의 상관관계를 규정한 양액흡수모델을 저장하는 양액모델 저장부; 상기 생육환경 정보와 상기 양액흡수모델을 기초로 상기 생육환경에서 상기 작물이 흡수하는 양액 흡수량을 예측하는 흡수량 예측부; 및 예측된 상기 양액 흡수량을 기초로 상기 작물에 공급할 양액의 성분량에 관한 양액 가이드 정보를 제공하는 정보제공부를 포함하는 것을 특징으로 한다.이를 통해 작물의 생장환경, 생장단계, 및 작물의 상태에 맞춤화된 양액 조성과 관수량에 관한 가이드 정보를 제공함으로써 작물 생장을 촉진하고, 과다 공급으로 인한 비용 증대 및 환경오염 문제를 효과적으로 방지할 수 있다. claims: 작물이 생육되는 생육환경 정보를 센싱하는 환경센싱부;상기 작물의 생육환경과 상기 작물이 양액을 흡수하는 양액 흡수량 간의 상관관계를 규정한 양액흡수모델을 저장하는 양액모델 저장부;상기 생육환경 정보와 상기 양액흡수모델을 기초로 상기 생육환경에서 상기 작물이 흡수하는 양액 흡수량을 예측하는 흡수량 예측부; 및예측된 상기 양액 흡수량을 기초로 상기 작물에 공급할 양액의 성분량에 관한 양액 가이드 정보를 제공하는 정보제공부를 포함하는 것을 특징으로 하는 스마트 작물 재배 관리장치.작물의 재배를 관리하기 위한 작물 재배 관리장치를 통하여 수행되는 작물 재배 관리방법에 있어서,작물의 생육환경과 상기 작물이 양액을 흡수하는 양액 흡수량 간의 상관관계를 규정한 양액흡수모델을 저장하는 단계;작물이 생육되는 생육환경 정보를 센싱하는 단계;상기 생육환경 정보와 상기 양액흡수모델을 기초로 상기 생육환경에서 상기 작물이 흡수하는 양액 흡수량을 예측하는 단계; 및 예측된 상기 양액 흡수량을 기초로 상기 작물에 공급할 양액의 성분량에 관한 양액 가이드 정보를 제공하는 단계를 포함하는 것을 특징으로 하는 작물 재배 관리방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

782/1150 Row 782: application_number: 1020190178756, combined_string: invention_title: 생장프로파일(Growth Profiles) 기반의 공장형 버섯재배사 원격 자동 생육제어 방법 및 장치 abstract: 본 발명은 공장형 버섯재배사 냉난방기, 가습기, 급배기팬 등 구동기를 제어하는 생장프로파일을 구성, 궁극적으로 무인 자동제어 환경상태에서 최적의 작물 재배 환경을 구현하기 위한 것이다.최근 버섯 재배환경은 노동 집약적 소규모 재배환경에서 기계화 설비를 통해 품질을 균일화하는 공장형 생산방식으로 변모하고 있다. 특히 ICT 기술을 활용하여 온도, 습도, 이산화탄소(CO2) 농도 등 환경을 비교 분석하여 버섯 성장에 가장 적합한 환경 요건을 조성하는 생장프로파일 제어 방식은 버섯 생산량과 품질 향상의 전환점이 될 것으로 기대되고 있다. 버섯 재배의 수율 극대화를 위해서는 검증된 생장프로파일을 기반으로 버섯재배사를 운영하는 것이 필요하다. 버섯재배사 운영자의 작물재배에 대한 개별 편차를 인정하더라도 적어도 전문가 의해 도출된 최적의 생장 프로파일을 참조하는 것은 작물 수율 극대화에 큰 기여를 할 수 있다. claims: 버섯재배사 관리자의 개별 경험에 따라 작물수확량 편차가 발생하는 경험 위주 재배방식의 비정량화 문제를 해결하기 위해 버섯의 최적 생장을 유도하기 위한 생장 프로파일을 도출한 후 이를 다수의 공장형 버섯재배사에 적용하여 버섯의 생육환경을 원격 자동제어 하기 위한 '생장프로파일 (Growth Profiles) 기반의 공장형 버섯재배 원격 자동 생육제어 방법 및 장치'에 있어서상기 원격장치부 생장프로파일생성부가;작물의 최적 생장을 유도하기 위해 품종별, 재배기간별로 온도, 습도, 이산화탄소(CO2) 등 버섯 생장에 가장 적합한 생육 환경 요건을 정의한 데이터의 집합인 생장프로파일(Growth Profiles)을 생성하는 기능을;로컬장치부 다운로드요청부가;인터넷 등 원격 통신망을 통해 원격장치부 생장프로파일생성부가 생성한 생장프로파일을 다운로드 받는 기능을;로컬장치부 생장프로파일실행부가;원격 다운로드 받은 생장프로파일이 로컬장치부에서 작동될 수 있도록 로컬장치부의 센서, 제어기, 제어로직을 생장프로파일과 연동하는 기능을; 로컬장치부 장치시계부가;인터넷시간서버를 주기적으로 참조하여 시간오류를 수정하며, 이를 기반으로 생장 프로파일 제어 시작 및 종료 시간을 체크하여 제어 시간대를 관리해주는 기능을;로컬장치부 센서수집부가;로컬장치부에 연동된 센서를 주기적으로 체크하여 제어부에 센서값을 전달하는 기능을;로컬장치부 제어부가;센서수집부에서 전달받은 센서값을 기반으로 제어여부를 판단하여 해당 제어 조건일 경우 히팅방식 또는 쿨링 방식 등 해당 제어로직을 통해 구동기를 자동제어하는 기능을;특징으로 하는 생장프로파일(Growth Profiles) 기반의 공장형 버섯재배 원격 자동 생육제어 방법 및 장치, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

783/1150 Row 783: application_number: 1020190176274, combined_string: invention_title: 기상정보를 이용한 토양수분 예측 시스템 abstract: 본 명세서는 토양수분 예측 시스템을 개시한다. 본 발명의 일 실시예에 따르면, 토양수분 예측 시스템은 농지에 설치되어 토양수분 데이터를 수집하는 토양수분 감지센서(110); 상기 농지에 설치되어 기상정보 데이터를 수집하며, 상기 토양수분 감지센서(110)로부터 상기 토양수분 데이터를 수신하는 기상관측장비(120); 상기 기상관측장비(120)로부터 상기 토양수분 데이터 및 상기 토양수분 데이터를 수신하고 이를 분석하여 토양수분 예측 모델을 도출하며, 기상청 서버(200)로부터 동네 예보 정보를 수신하고 상기 예측 모델을 적용하여 상기 동네 여보 정보에 상응하는 토양수분 예측값을 산출하는 시스템 서버(130); 및 상기 시스템 서버(130)로부터 상기 토양수분 예측값을 전송받는 사용자 단말기(140);를 포함한다. claims: 농지에 설치되어 토양수분 데이터를 수집하는 토양수분 감지센서(110);상기 농지에 설치되어 기상정보 데이터를 수집하며, 상기 토양수분 감지센서(110)로부터 상기 토양수분 데이터를 수신하는 기상관측장비(120);상기 기상관측장비(120)로부터 상기 토양수분 데이터 및 상기 토양수분 데이터를 수신하고 이를 분석하여 토양수분 예측 모델을 도출하며, 기상청 서버(200)로부터 동네 예보 정보를 수신하고 상기 예측 모델을 적용하여 상기 동네 여보 정보에 상응하는 토양수분 예측값을 산출하는 시스템 서버(130); 및상기 시스템 서버(130)로부터 상기 토양수분 예측값을 전송받는 사용자 단말기(140);를 포함하는,토양수분 예측 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

784/1150 Row 784: application_number: 1020190173519, combined_string: invention_title: 계층적 구조를 갖는 무선 네트워크를 통한 스마트팜 제어 방법 abstract: 사용하는 상기 온도, 습도, 풍량, 조도 센서 등의 동작 전압과 출력전압 등에 차이가 있어, 사용하는 센서마다 다른 제어프로그램 또는 다른 설정값을 사용한다. 또한, 재배 작물이 달라지면 상기 설정값도 다른 설정값을 사용하여야 한다. claims: 온도, 습도, 풍량, 조도 센서에서 측정된 센서 값을 스마트팜 센서제어기에서 아날로그-디지털 변환하여 디지털 센서 값을 온도, 습도, 풍량, 조도로 변환하지 않고, 상기 디지털 센서 값을 그대로 클라우드 컴퓨팅 서버로 전송하며, 상기 클라우드 컴퓨팅 서버에는 상기 스마트팜 센서제어기에 부여된 코드를 색인으로 하여, 상기 클라우드 컴퓨팅 서버에 구축된 환경센서 데이터베이스로부터 상기 온도, 습도, 풍량, 조도 센서의 메이커와 모델명을 기준으로 상기 온도, 습도, 풍량, 조도 교정데이터를 읽어와, 상기 디지털 센서 값을 온도, 습도, 풍량, 조도를 표시하는 실제 환경변수 값으로 변환하며, 상기 실제 환경변수 값은 온도 센서의 경우 ℃, 습도의 경우 상대습도 %, 조도의 경우 Lux, 풍량의 경우 m/s로 변환된 값이고, 상기 온도, 습도, 풍량, 조도 센서 중 어느 하나 이상의 센서가 바뀌어도 상기 클라우드 컴퓨팅 서버에 구축된 상기 환경 센서 데이터 베이스의 교정된 실제 환경 변수 값을 받아 설정된 설정 값과 비교하여 상기 스마트팜 센서제어기를 동작할 수 있기 때문에, 상기 온도, 습도, 풍량, 조도 센서 중 어느 하나 이상의 센서가 바뀌어도 상기 클라우드 컴퓨팅 서버의 환경 센서 데이터베이스에 센서의 종류를 업데이트하기만 하면 상기 스마트팜 센서제어기의 내장 프로그램의 수정 없이 사용할 수 있고, 상기 스마트팜 센서제어기와 연동된 구동장치의 동작을 위한 상기 설정 값도 재배시기, 작물의 종류, 외기 온도와 습도, 기후의 변화 양상에 따라 상기 클라우드 컴퓨팅 서버에서 설정 값을 바꾸어 상기 스마트팜 센서제어기에 전송할 수도 있고, 상기 스마트팜 센서제어기와 연동된 구동장치의 구동을 위한 센싱 값과 상기 설정 값과의비교를 상기 클라우드 컴퓨팅 서버에서 처리하도록 함으로써 상기 스마트팜 센서제어기에서는 센서 값의 전송과 그 결과로써 구해진 상기 스마트팜 센서제어기와 연동된 구동장치의 구동 동작을 상기 클라우드 컴퓨팅 서버에서 전송받아 구동하는 역할만을 할 수 있으며, 상기 스마트팜 센서제어기에 연결되는 보일러 온오프 또는 온도조절, 조명 온오프, 광조절 차광막, 환기창 개폐, 환풍기 온오프 또는 풍량조절, 내부 순환팬 온오프 또는 회전속도조절 장치의 제어명령은 상기 클라우드 컴퓨팅 서버에 제조사별, 모델별로 제어장치 데이터베이스에 저장하고, 상기 저장된 데이터를 이용하여 상기 스마트팜 센서제어기의 인덱싱번호를 이용하여 제조사와 모델을 상기 스마트팜 센서제어기와 연동함으로써 새로운 출력장치도 상기 스마트팜 센서제어기의 내장프로그램 수정 없이도 구동가능하게 할 수 있으며, 상기 클라우드 컴퓨팅 서버는 태풍, 폭설, 폭우 상황에서 측창의 개폐, 보일러의 온오프, 전원 차단의 원격지원을 제공함으로써 농작물의 피해를 최소화하는 것을 특징으로 하는 클라우드 컴퓨팅과 원격 센서를 이용한 스마트팜 제어방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

785/1150 Row 785: application_number: 1020190170467, combined_string: invention_title: 영농형 태양광 발전장치 abstract: 본 발명은 영농형 태양광 발전장치에 관한 것이다. 이는, 지지력을 제공하는 지지구조체와; 상기 지지구조체에 위치조절 가능하게 설치되며, 태양광을 받아 전력을 생산하는 다수의 불투명태양광패널 및 투명태양광패널을 포함하는 전력생산부와; 상기 불투명태양광패널의 위치를 조절하는 제1패널위치조절부와; 상기 투명태양광패널의 위치를 조절하는 제2패널위치조절부와; 상기 제1,2패널위치조절부를 제어하는 컨트롤러와; 외부의 기상데이터서버로부터 기상상황을 전달받고, 전달받은 기상 상황에 대응하는 제어신호를 컨트롤러로 전송하는 관리자서버를 구비한다.상기와 같이 이루어지는 본 발명의 영농형 태양광 발전장치는, 투명패널과 불투명패널의 이중 구조를 가져, 기상 상황에 따라 투명패널과 불투명패널을 선택적으로 사용할 수 있어 전기에너지의 생산 효율이 양호하고 전력을 생산하면서도 차광을 방지할 수 있다. 또한, 재배작물에 필요한 최적 차광률을 데이터베이스화 하여 작물에 따라 발전시간을 조절할 수 있다. 아울러, 사용자가 외부의 기상데이터서버와 접속하여, 기상정보에 기초한 패널 각도를 조절을 통해, 작물의 성장에 필요한 최적 일사량을 제공할 수 있다. claims: 지지력을 제공하는 지지구조체와;상기 지지구조체에 위치조절 가능하게 설치되며, 태양광을 받아 전력을 생산하는 다수의 불투명태양광패널 및 투명태양광패널을 포함하는 전력생산부와;상기 불투명태양광패널의 위치를 조절하는 제1패널위치조절부와;상기 투명태양광패널의 위치를 조절하는 제2패널위치조절부와;상기 제1,2패널위치조절부를 제어하는 컨트롤러와;외부의 기상데이터서버로부터 기상상황을 전달받고, 전달받은 기상 상황에 대응하는 제어신호를 컨트롤러로 전송하는 관리자서버를 구비하는 영농형 태양광 발전장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

786/1150 Row 786: application_number: 1020190170923, combined_string: invention_title: 농업용 무인 비행체 서비스 시스템 및 그 서비스 방법 abstract: 본 발명은 농업용 무인 비행체 서비스 시스템 및 그 서비스 방법으로, 본 발명의 일 실시예에 따른 무인 비행체 서비스 시스템은, 소정의 지역을 비행하여 해당 지역에 대한 정보 수집 또는 방제 임무를 수행하는 무인 비행체; 상기 무인 비행체와 무선통신망을 통해 통신하며, 상기 무인 비행체를 제어하고, 상기 무인 비행체에서 수집된 정보를 저장하는 서비스 서버; 및 상기 무인 비행체를 유지 및 관리하고 대상 지역의 측량 및 항법위성의 지상국 서비스를 제공하는 드론 기지국; 상기 서비스 서버는, 웹서비스를 통해 사용자의 서비스 요청을 접수하고, 이를 분석하여 상기 무인 비행체에 임무를 전송하며, 수집된 정보 및 수행된 임무 내용을 사용자 단말기에 제공할 수 있다. 본 발명에 의하면, 드론과 같은 무인 비행체를 무선통신망을 통해 누구나 무인 비행체를 이용하여 농업에 이용할 수 있어, 다양한 정보를 수집 및 분석하고, 수집 및 분석된 정보를 농업에 활용함으로써, 농업생산성을 극대화할 수 있는 효과가 있다. claims: 소정의 지역을 비행하여 해당 지역에 대한 정보 수집 또는 방제 임무를 수행하는 무인 비행체;상기 무인 비행체와 무선통신망을 통해 통신하며, 상기 무인 비행체를 제어하고, 상기 무인 비행체에서 수집된 정보를 저장하는 서비스 서버; 및상기 무인 비행체를 유지 및 관리하고, 대상 지역의 측량 및 항법위성의 지상국 서비스를 제공하는 드론 기지국을 포함하며,상기 서비스 서버는,웹서비스를 통해 사용자의 서비스 요청을 접수하고, 이를 분석하여 상기 무인 비행체에 임무를 전송하며, 상기 수집된 정보 및 수행된 임무 내용을 사용자 단말기에 제공하며,상기 수집된 정보를 근거로 농작물의 건강상태, 질병 유무 및 분포에 대한 정보와, 토양상태 및 토양의 수분 함량을 분석하며, 해당 지역의 관개나 농작물의 수정시기 및 농작물의 수확시기를 예측하며,빅데이터 분석을 통해 미리 설정된 기간 동안의 평균적인 농작물의 상태 및 해당 지역의 기후 변화에 대한 정보를 상기 사용자 단말기에 제공하며,상기 무인 비행체는,항법센서, 방위센서, 고도센서, 자이로센서, 속도센서 및 근접센서 중 하나 이상을 포함하는 센서부;상기 해당 지역을 촬영하기 위한 한 종류 이상의 카메라를 포함하는 촬영부;상기 센서부에서 감지된 정보 및 상기 촬영부에서 촬영된 데이터를 저장하는 메모리부;상기 서비스 서버와 무선 통신하는 통신부; 및상기 서비스 서버 측에서 수신된 제어 신호에 따라 상기 해당 지역을 비행하도록 제어하고, 상기 센서부, 상기 촬영부, 상기 메모리부 및 상기 통신부를 제어하는 제어부를 포함하며,상기 촬영부에 포함된 카메라는,해당 지역의 농작물 성장 상태에 따라 각기 다른 음영이나 색체로 표현되는 영상을 촬영하는 적외선 카메라 및, 해당 지역의 농작물의 병충해 여부 및 가뭄 상태를 확인할 수 있는 영상을 촬영하는 멀티 스펙트럼 카메라 중 어느 하나 이상을 포함하며,상기 서비스 서버는,상기 사용자 단말기가 접속하여 서비스를 신청하고, 상기 사용자 단말기에 정보를 제공하는 웹 관리부;상기 무인 비행체의 비행 모드를 고정익 또는 가변익으로 설정하여 상기 무인 비행체의 비행을 제어하는 무인 비행체 제어부;상기 무인 비행체에서 수집된 정보를 분석하는 분석부; 및상기 분석부에서 정보화된 정보를 상기 사용자 단말기로 제공하기 위한 정보로 재생산하는 클라우드부를 포함하며,상기 클라우드부는,상기 무인 비행체를 통해 수집된 정보가 누적될 때, 상기 누적된 정보에 대한 빅데이터 분석을 통해 상기 미리 설정된 기간 동안의 평균적인 농작물의 상태 및 해당 지역의 기후 변화에 대한 정보를 상기 사용자 단말기에 제공하는 클라우드 서버부;상기 분석부에서 정보화된 정보를 디렉토리 구조로 계측화하여 저장하는 블록 스토리지부; 및상기 사용자 단말기의 계정 단위로 파일이나 데이터를 저장하며, 그림이나 영상 또는 문서와 같이 형태와 구조가 다른 구조화되지 않은 비정형 데이터에 대해 메타데이터를 자동으로 생성하여 관리하는 오브젝트 스토리지부를 포함하고,상기 드론 기지국은, 상기 무인 비행체 및 상기 서비스 서버와 각각 통신하고, 상기 서비스 서버에서 송출된 제어신호를 상기 무인 비행체에 전송하고, 상기 무인 비행체에서 전송된 신호를 상기 서비스 서버로 전송하는 무인 비행체 서비스 시스템.제1항에 기재된 무인 비행체 서비스 시스템을 이용한 무인 비행체 서비스 방법이고,사용자 단말기에서 서비스 서버로, 무선통신망을 통해 무인 비행체 서비스에 대한 신청이 이루어지는 단계;상기 사용자 단말기에서 신청된 지역에 대한 정보 수집 또는 방제 임무를 수행하기 위해 해당 지역을 비행하는 무인 비행체에 무선통신망을 통해 상기 서비스 서버에서 제어 명령을 전송하는 단계;상기 무인 비행체에서 상기 신청 지역에 대한 정보 수집 또는 방제 임무를 수행하는 단계;상기 무인 비행체에서 수집된 정보 또는 방제 임무 수행 결과를 무선통신망을 통해 상기 서비스 서버로 전송하는 단계; 및상기 서비스 서버로 전송된 상기 수집된 정보가 상기 사용자 단말기에서 확인할 수 있게 분석 및 저장되는 단계를 포함하며,상기 분석 및 저장되는 단계는,상기 수집된 정보를 근거로 농작물의 건강상태, 질병 유무 및 분포에 대한 정보와, 토양상태 및 토양의 수분 함량을 분석하며, 해당 지역의 관개나 농작물의 수정시기 및 농작물의 수확시기를 예측하는 과정; 및빅데이터 분석을 통해 미리 설정된 기간 동안의 평균적인 농작물의 상태 및 해당 지역의 기후 변화에 대한 정보를 상기 사용자 단말기에 제공하는 과정을 포함하며,상기 서비스 서버에서 상기 무인 비행체로 전송되는 명령은, 상기 무인 비행체를 유지 관리하고, 해당 지역의 측량 및 정밀 GPS 지상국 서비스를 운용하는 드론 기지국을 통해 전송되는 무인 비행체 서비스 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

787/1150 Row 787: application_number: 1020190168707, combined_string: invention_title: 농작물의 소득 예측시스템 및 그의 예측방법 abstract: 본 발명은 농작물을 생산하기 전에 통계 데이터들 및 투입된 인프라 등의 정보를 입력받아 생산량을 예측하고, 이를 수치로 환산하여 생산자나 기관이 얻게 될 예상 수익 등의 경작 계획을 컨설팅 가능하게 하는 농작물의 소득 예측시스템 및 이러한 예측 시스템을 이용한 소득 예측방법에 관한 것이다. 본 발명은 기후정보 및 농작물 생산량을 입력받고 농작물 생산량의 예측정보를 산출하는 제1 예측부와, 재배 비용 정보와 농작물 가격정보를 입력받고 농작물 가격 예측정보를 산출하는 제2 예측부, 재배 비용 정보와 소비자 물가 지수(Consumer Price Index)를 입력받고 재배비용정보를 산출하는 제3 예측부, 상기 농작물 생산량 예측정보와 농작물 가격 예측정보를 이용하여 판매정보를 연산하는 제1 연산부, 및 상기 판매정보와 재배 비용정보를 이용하여 단위면적당 농작물의 순이익 정보를 연산하는 제2 연산부를 포함하며, 예측과정은 기계학습을 통해 반복학습하게 된다. claims: 기후정보 및 농작물 생산량을 입력받고 농작물 생산량의 예측정보를 산출하는 제1 예측부; 재배비용 정보와 농작물 가격정보를 입력받고 농작물 가격 예측정보를 산출하는 제2 예측부; 재배 비용 정보와 소비자 물가 지수(Consumer Price Index)를 입력받고 재배비용정보를 산출하는 제3 예측부; 상기 농작물 생산량 예측정보와 농작물 가격 예측정보를 이용하여 판매정보를 연산하는 제1 연산부; 및 상기 판매정보와 재배 비용정보를 이용하여 단위면적당 농작물의 순이익 정보를 연산하는 제2 연산부를 포함하는 것을 특징으로 하는 농작물의 소득 예측시스템.지역별 강수량 및 온도 정보, 그리고 농작물 생산정보를 이용한 농작물 생산량, 농작물의 재배 비용 정보와 농작물 가격정보를 이용한 농작물 가격, 재배 비용 정보와 소비자 물가 지수(Consumer Price Index)를 이용한 재배 비용정보를 각각 예측하는 예측단계; 상기 예측된 농작물의 생산량정보와 농작물 가격정보를 이용하여 농산물의 판매정보를 연산하는 제1 연산단계; 및 상기 농산물의 판매정보와 재배 비용 정보를 이용하여 단위면적당 농작물의 순이익 정보를 연산하는 제2 연산단계를 포함하는 것을 특징으로 하는 농작물의 소득 예측방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

788/1150 Row 788: application_number: 1020190169096, combined_string: invention_title: 이미지 기반 작물 생육정보 자동계측 시스템 abstract: 본 발명은 이미지 기반 작물 생육정보를 산출하고 연관된 정보를 제공할 수 있는 기술에 대한 것으로, 재배 작물에 대한 이미지를 도출하여 입력하고, 이에 대한 딥러닝 알고리즘을 활용한 이미지 분석기반 작물의 생육정보, 품질 진단을 통해 생육정보에 따른 작물 양액 및 품질관리 , 수확시기 등의 영농정보 제공할 수 있다. claims: 분석대상의 작물의 이미지를 촬영하고 전송하는 이미지 제공모듈(100);상기 이미지 제공모듈(100)에서 제공된 이미지를 입력하고, 딥러닝 기반 작물의 기관별 기관 분류를 수행하며, 상기 이미지에 포함되는 작물의 기관별 물리적 계측정보를 도출하여, 상기 작물의 생육정보를 산출하는 생육정보 산출모듈(200);상기 생육정보산출모듈(200)에서 입력된 상기 이미지에 대한 딥러닝 기반 작물의 기관별 기관 분류를 수행하는 경우 기준이 되는 표준 이미지 정보를 제공하는 기준정보 데이터베이스(300); 및상기 생육정보 산출모듈(200)에서 산출되는 작물의 생육상태정보와 연계하는 작물의 재배기법 관련한 영농정보를 제공하는 영농정보 데이터베이스(400);을 포함하는,이미지 기반 작물 생육정보 자동계측 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

789/1150 Row 789: application_number: 1020190169213, combined_string: invention_title: 스마트팜 데이터 생육연동시스템 abstract: 스마트팜 데이터 생육연동시스템(1)은 미리 설정된 각각의 물리적 통신방식으로 식물의 생장에 관련된 데이터를 수집하는 복수의 내부 통신망과, 데이터 수집을 위해 외부 인터넷 접속을 위한 외부 통신망 사이의 인터페이스 역할을 수행하는 데이터 로거를 포함하는 재배장비 데이터 시스템과, 재배장비 데이터 시스템과 연결되며, 식물의 상태를 모니터링하면서 시계열 모니터링 데이터를 기반으로 생육상태를 자동분석하는 재배영상 데이터 시스템과, 재배장비 데이터 시스템 및 재배영상 데이터 시스템으로부터 데이터를 제공받아 재배장비 데이터 시스템 및 재배영상 데이터 시스템을 제어하는 복합제어시스템을 포함하는 것을 특징으로 한다. claims: 미리 설정된 각각의 물리적 통신방식으로 식물의 생장에 관련된 데이터를 수집하는 복수의 내부 통신망과, 데이터 수집을 위해 외부 인터넷 접속을 위한 외부 통신망 사이의 인터페이스 역할을 수행하는 데이터 로거를 포함하는 재배장비 데이터 시스템; 및상기 재배장비 데이터 시스템과 연결되며, 상기 식물의 상태를 모니터링하면서 시계열 모니터링 데이터를 기반으로 생육상태를 자동분석하는 재배영상 데이터 시스템; 및상기 재배장비 데이터 시스템 및 상기 재배영상 데이터 시스템으로부터 데이터를 제공받아 상기 재배장비 데이터 시스템 및 상기 재배영상 데이터 시스템을 제어하는 복합제어시스템;을 포함하는 스마트팜 데이터 생육연동시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

790/1150 Row 790: application_number: 1020190167540, combined_string: invention_title: 감초재배용 스마트 팜 시스템 abstract: 본 발명의 감초재배용 스마트 팜 시스템은, 고부가가치의 감초를 재배하도록 재배실의 환경을 수집하고 환경조성수단을 이용하여 재배실의 생장조건을 최적으로 조성하여 감초를 재배하는 스마트 팜 시스템이고, 재배실의 건조한 상태가 유지되고 감초가 생장하는 토양을 배수성이 우수한 모래를 이용하여 감초의 생장에 적합한 생장환경이 조성되고, 생장중인 감초의 생장을 촉진시키도록 감초의 생장시기별로 적합하게 조도, 온도, 습도, 통풍을 조절하고, 토양에 공급되는 수분의 적절한 공급량 및 배수성이 유지되도록 하는 발명에 관한 것이다. claims: 감초재배용 스마트 팜 시스템에 있어서,감초를 재배하기 위한 실내공간이 형성되고, 감초의 생장을 위해 필요한 재배 시설물(110)들이 설치되는 재배실(100)과;상기 재배실(100)의 실내공간에 설치되어, 감초 재배에 필요한 환경을 조성하는 환경조성수단(200)과;상기 재배실(100)의 실내공간에 설치되어, 재배실(100)의 환경 상태를 감지하여 환경정보를 생성하고, 재배실(100) 내부를 촬영한 모니터링용 영상정보를 생성하고, 감초 부패를 감지하여 감지정보를 생성하고, 생성된 환경정보, 영상정보, 감지정보를 관리서버(400)로 전송하는 환경수집수단(300)과;상기 환경수집수단(300)이 전송한 환경정보를 이용하여 재배실(100)의 실내공간이 감초 재배에 적합한 환경이 되도록 환경조성수단(200)을 제어하고, 환경수집수단(300)이 전송한 영상정보를 모니터링 화면에 표시하여 관리자가 재배실(100) 내부를 모니터링 할 수 있도록 하고, 환경수집수단(300)이 전송한 감지정보를 이용하여 감초 부패에 관한 이벤트 정보를 생성하여 모니터링 화면에 표시하는 관리서버(400)를 포함하는 것을 특징으로 하는 감초재배용 스마트 팜 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

791/1150 Row 791: application_number: 1020190168130, combined_string: invention_title: 약용작물 재배용 스마트 팜 시스템 abstract: 본 발명은 고부가가치의 약용작물을 재배하도록 재배실의 환경정보를 수집하고 환경조성수단을 이용하여 재배실의 생장조건을 최적으로 조성하여 다양한 약용작물을 재배하는 스마트 팜 시스템에 관한 발명이고, 생장중인 약용작물의 생장을 촉진시키도록 약용작물의 생장시기별로 적합하게 온도, 습도, 통풍을 조절하고, 약용작물별 양분과 수분이 토양에 적절하게 공급되도록 하는 스마트 팜 시스템에 관한발명이며, 약용작물에 대한 생장 시기별 환경정보를 분류 저장하여 약용작물별 최적 생장환경 빅 데이터를 생성하는 스마트 팜 시스템에 관한 발명에 관한 것이다. claims: 약용작물 재배용 스마트 팜 시스템에 있어서,약용작물을 재배하기 위한 실내공간이 형성되고, 약용작물의 생장을 위해 필요한 재배 시설물(110)들이 설치되는 재배실(100)과;상기 재배실(100)의 실내공간에 설치되어, 약용작물 재배에 필요한 환경을 조성하는 환경조성수단(200)과;상기 재배실(100)의 실내공간에 설치되어, 재배실(100)의 환경 상태를 감지하여 환경정보를 생성하고, 재배실(100) 내부를 촬영한 모니터링용 영상정보를 생성하고, 생성된 환경정보, 영상정보를 관리서버(400)로 전송하는 환경수집수단(300)과;상기 환경수집수단(300)이 전송한 환경정보를 이용하여 재배실(100)의 실내공간이 약용작물 재배에 적합한 환경이 되도록 환경조성수단(200)을 제어하고, 환경수집수단(300)이 전송한 영상정보를 모니터링 화면에 표시하여 사용자가 재배실(100) 내부를 모니터링 할 수 있도록 하고, 환경수집수단(300)이 전송한 환경정보를 이용하여 약용작물별 최적 생장환경 데이터를 생성하는 관리서버(400)를 포함하는 것을 특징으로 하는 약용작물재배용 스마트 팜 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

792/1150 Row 792: application_number: 1020190165210, combined_string: invention_title: 클라우드 기반 주간 온실 환경 의사결정지원 서버 및 이를 이용한 주간 온실 환경 의사결정지원 시스템 abstract: 본 발명의 일 실시예에 따른 주간 온실 환경 의사결정지원 서버는 작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단부; 작물 생육상을 기반으로 온실 환경 제어 요소를 결정하는 환경 제어 요소 결정부; 데이터 베이스로부터 작물에 대한 선도 농가 월별 데이터를 수신하는 과거 데이터 수신부; 기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신부; 주간 기상 예보 데이터와 선도 농가 월별 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교부; 및 온도 차 및 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정부를 포함한다. claims: 작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단부;상기 작물 생육상을 기반으로 환경 제어 요소를 결정하는 환경 제어 요소 결정부;데이터 베이스로부터 상기 작물에 대한 과거 기상 데이터와, 이에 대응되는 선도 농가의 과거 온실 데이터를 포함하는 과거 데이터를 수신하는 과거 데이터 수신부;기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신부;상기 주간 기상 예보 데이터와 상기 과거 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교부; 및상기 온도 차 및 상기 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정부를 포함하는 주간 온실 환경 의사결정지원 서버.작물 영상을 촬영하는 작물 영상 촬영 장치;과거 기상 데이터와, 이에 대응되는 선도 농가의 과거 온실 데이터를 포함하는 과거 데이터가 작물의 품목별로 저장되는 데이터 베이스;온실에 제공되어, 온실 데이터를 감지하는 온실 센서;상기 작물 영상 촬영 장치, 상기 데이터 베이스, 및 상기 온실 센서와 데이터 송수신을 통해 주간 환경 제어값을 산출하는 주간 온실 환경 의사결정지원 서버; 및상기 주간 온실 환경 의사결정지원 서버로부터 수신되는 상기 주간 환경 제어값을 기초로 온실 환경을 제어하는 온실 제어기를 포함하며,상기 주간 온실 환경 의사결정지원 서버는,작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단부;상기 작물 생육상을 기반으로 환경 제어 요소를 결정하는 환경 제어 요소 결정부;상기 데이터 베이스로부터 상기 작물에 대한 상기 과거 데이터를 수신하는 과거 데이터 수신부;기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신부;상기 주간 기상 예보 데이터와 상기 과거 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교부; 및상기 온도 차 및 상기 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정부를 포함하는 주간 온실 환경 의사결정지원 시스템.작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단 단계;상기 작물 생육상을 기반으로 환경 제어 요소를 결정하는 환경 제어 요소 결정 단계;데이터 베이스로부터 상기 작물에 대한 과거 기상 데이터와, 이에 대응되는 선도 농가의 과거 온실 데이터를 포함하는 과거 데이터를 수신하는 과거 데이터 수신 단계;기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신 단계;상기 주간 기상 예보 데이터와 상기 과거 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교 단계; 및상기 온도 차 및 상기 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정 단계를 포함하는 주간 온실 환경 의사결정지원 방법.주간 온실 환경 의사결정지원 방법을 실행하기 위한 프로그램을 포함하는 컴퓨터 판독가능 기록매체에 있어서,상기 주간 온실 환경 의사결정지원 방법은,작물 영상 촬영 장치로부터 주간 작물 영상을 수신하여 작물 생육상을 판단하는 작물 생육상 판단 단계;상기 작물 생육상을 기반으로 환경 제어 요소를 결정하는 환경 제어 요소 결정 단계;데이터 베이스로부터 상기 작물에 대한 과거 기상 데이터와, 이에 대응되는 선도 농가의 과거 온실 데이터를 포함하는 과거 데이터를 수신하는 과거 데이터 수신 단계;기상청으로부터 주간 기상 예보 데이터를 수신하는 기상 데이터 수신 단계;상기 주간 기상 예보 데이터와 상기 과거 데이터를 비교하여 온도 차 및 습도 차를 산출하는 기상 데이터 비교 단계; 및상기 온도 차 및 상기 습도 차를 고려하여 환경 제어 수치를 결정하는 환경 제어 수치 결정 단계를 포함하는 컴퓨터 판독가능 기록매체., Ltext: 농업, prediction: '임업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

793/1150 Row 793: application_number: 1020190156664, combined_string: invention_title: 디지털 트윈을 이용한 온라인 수직농장 경영 시스템 abstract: 본 발명에 따른 디지털 트윈을 이용한 온라인 수직농장 경영 시스템은,온라인을 통한 수직농장 경영 시스템으로서, 특정 작물을 재배하기 위해 층별로 구획 처리된 수직농장; 상기한 각 층을 유저에게 분양하고 분양에 대한 대가를 받는 분양 모듈; 작물 경작에 필요한 이론적 경작 정보를 각 작물 별로 유저에게 제공하는 경작 정보 제공 모듈; 유저로부터 작물 재배를 위한 조작 행위를 입력받는 조작부, 상기 입력부를 통해 입력받은 정보를 경작 명령 정보로 저장하는 저장 처리부, 실제 작물의 건강 상태와 성장 현황 및 수직농장의 현재 온, 습도를 입력받아 데이터베이스에 저장하고 가상 농장에 반영하는 생장 데이터 저장부를 포함한 게임 컨트롤 모듈; 센서를 통해 수집한 정보를 처리해 층별 환경 정보 및 작물 상태 정보를 생성, 전달하는 종합 정보 처리부, 수집 및 처리된 모든 상태 정보를 저장하는 데이터베이스; 상기 경작 명령 정보 및 수직농장의 물, 비료, 종자 재고 현황을 파악하여 관리인에게 관리 명령을 내리거나, 유저가 시스템에 대해 오프라인 상태이거나 자동 경작 명령을 내렸을 경우 당시까지의 데이터를 기반으로 자동 경작 시스템을 구동시키는 수직농장 관리 서버;로 구성된 것을 특징으로 한다. claims: 온라인을 통한 수직농장 경영 시스템으로서,특정 작물을 재배하기 위해 층별로 구획 처리된 수직농장;상기한 각 층을 유저에게 분양하고 분양에 대한 대가를 받는 분양 모듈;작물 경작에 필요한 이론적 경작 정보를 각 작물 별로 유저에게 제공하는 경작 정보 제공 모듈;유저로부터 작물 재배를 위한 조작 행위를 입력받는 조작부, 상기 입력부를 통해 입력받은 정보를 경작 명령 정보로 저장하는 저장 처리부, 실제 작물의 건강 상태와 성장 현황 및 수직농장의 현재 온, 습도를 입력받아 데이터베이스에 저장하고 가상 농장에 반영하는 생장 데이터 저장부를 포함한 게임 컨트롤 모듈;센서를 통해 수집한 정보를 처리해 층별 환경 정보 및 작물 상태 정보를 생성, 전달하는 종합 정보 처리부, 수집 및 처리된 모든 상태 정보를 저장하는 데이터베이스;상기 경작 명령 정보 및 수직농장의 물, 비료, 종자 재고 현황을 파악하여 관리인에게 관리 명령을 내리거나, 유저가 시스템에 대해 오프라인 상태이거나 자동 경작 명령을 내렸을 경우 당시까지의 데이터를 기반으로 자동 경작 시스템을 구동시키는 수직농장 관리 서버;로 구성된 것을 특징으로 하는 온라인 수직농장 경영 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

794/1150 Row 794: application_number: 1020190155876, combined_string: invention_title: 농작물의 출하예상가격 산출 시스템 및 방법 abstract: 본 발명은 농작물의 출하예상가격 산출 시스템 및 방법을 제공한다. 상기 농작물 출하예상가격 산출 시스템은, 사용자 단말기를 통해 재배지역, 재배면적, 재배작물 및 재배시기를 입력 받는 인터페이스부, 날씨정보 제공 서버로부터 특정 기간의 날씨정보를 수신하고, 농작물 정보 제공 서버로부터 해당 작물의 수매가격 또는 경매가격에 관한 정보를 수신하는 통신부, 및 특정 작물에 대한 날씨 매칭률 및 재배면적에 대한 정보를 기초로 표준시세를 산출하는 표준시세 산출부를 포함한다. claims: 사용자 단말기를 통해 재배지역, 재배면적, 재배작물 및 재배시기를 입력 받는 인터페이스부; 날씨정보 제공 서버로부터 특정 기간의 날씨정보를 수신하고, 농작물 정보 제공 서버로부터 해당 작물의 수매가격 또는 경매가격에 관한 정보를 수신하는 통신부; 및특정 작물에 대한 날씨 매칭률 및 재배면적에 대한 정보를 기초로 표준시세를 산출하는 표준시세 산출부를 포함하는농작물 출하예상가격 산출 시스템.사용자 단말기를 통해 재배지역, 재배면적, 재배작물 및 재배시기에 대한 데이터를 수신하는 단계; 입력된 상기 재배작물과 상기 재배시기를 기초로 출하시기를 계산하는 단계; 날씨정보 제공 서버로부터 수신된 날씨에 대한 데이터와, 상기 재배지역, 및 상기 재배면적을 기초로 재배작물에 대한 예상 수확량을 산출하는 단계; 농작물 정보 제공 서버로부터 수신된 재배작물의 과거 수확량 및 과거 가격에 대한 데이터를 기초로 수확량과 작물가격에 대한 관계도를 산출하는 단계; 및 산출된 관계도를 기초로 재배작물의 예상 수확량에 따른 표준시세를 계산하는 단계를 포함하는 농작물 출하예상가격 산출 방법.사용자 단말기를 통해 재배지역, 재배면적, 재배작물 및 재배시기에 대한 데이터를 수신하는 단계;상기 재배작물의 최적날씨정보와 상기 날씨정보 사이의 매칭률을 기초로 제1 스코어로 산출하는 단계;상기 재배면적과 미리 정해진 기준면적 간의 차이를 기초로 제2 스코어를 산출하는 단계;상기 재배면적과 상기 재배작물의 전체재배면적 간의 비율을 기초로 제3 스코어를 산출하는 단계; 및,상기 재배작물의 기준가격과 상기 제1 내지 제3 스코어를 기초로 상기 표준시세를 산출하는 단계를 포함하는농작물 출하예상가격 산출 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

795/1150 Row 795: application_number: 1020190155885, combined_string: invention_title: 농작물 추천 정보 제공 시스템 및 방법 abstract: 본 발명은 농작물 추천 정보 제공 시스템 및 방법을 제공한다. 상기 농작물 추천 정보 제공 시스템은, 사용자 단말기를 통해 작물 재배를 위한 지역, 면적, 지난 재배작물 또는 생산시기를 입력 받는 인터페이스부, 날씨정보 제공 서버로부터 특정 기간의 날씨정보를 수신하고, 농작물 정보 제공 서버로부터 각 작물의 수입량, 수매가격 및 저장도에 관한 정보를 수신하는 통신부, 수신된 상기 날씨정보, 상기 수입량, 상기 수매가격 및 상기 저장도에 대한 정보를 기초로, 각 작물에 대한 스코어를 계산하는 스코어 계산부, 및 상기 스코어 계산부에서 계산한 각 작물에 대한 스코어에 가중치를 부여하고, 가장 높은 스코어를 지닌 작물을 추천작물로 선정하는 추천작물 선정부를 포함한다. claims: 사용자 단말기를 통해 작물 재배를 위한 지역, 면적, 지난 재배작물 또는 생산시기를 입력 받는 인터페이스부; 날씨정보 제공 서버로부터 특정 기간의 날씨정보를 수신하고, 농작물 정보 제공 서버로부터 각 작물의 수입량, 수매가격 및 저장도에 관한 정보를 수신하는 통신부; 수신된 상기 날씨정보, 상기 수입량, 상기 수매가격 및 상기 저장도에 대한 정보를 기초로, 각 작물에 대한 스코어를 계산하는 스코어 계산부; 및 상기 스코어 계산부에서 계산한 각 작물에 대한 스코어에 가중치를 부여하고, 가장 높은 스코어를 지닌 작물을 추천작물로 선정하는 추천작물 선정부를 포함하는농산물 추천 정보 제공 시스템.날씨정보 제공 서버로부터 수신된 날씨정보와 각 작물의 최적날씨정보 사이의 날씨매칭률을 기초로 제1 스코어를 산출하는 단계; 농작물 정보 제공 서버로부터 수신된 수입량을 기초로, 각 작물의 제2 스코어를 산출하는 단계; 상기 농작물 정보 제공 서버로부터 수신된 수매가격을 기초로, 각 작물의 제3 스코어를 산출하는 단계; 상기 농작물 정보 제공 서버로부터 수신된 저장도를 기초로 각 작물의 제4 스코어를 계산하는 단계; 및 상기 제1 내지 제4 스코어에 각각의 하고, 가장 높은 스코어를 지닌된 작물을 추천작물로 선정하는 단계를 포함하는 농산물 추천 정보 제공 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

796/1150 Row 796: application_number: 1020190153904, combined_string: invention_title: 관리로봇을 이용한 인공지능 기반의 버섯 재배관리 시스템 abstract: 본 발명은 스마트팜 재배기능과 관리로봇의 자율주행 기능을 이용하여 관리 인건비를 줄여 고부가가치의 버섯을 재배하는 발명에 관한 것으로, 자율주행 기능에 의해 관리로봇이 버섯의 생장상태를 주기적으로 촬영하면, 생장환경통합관리부는 머신러닝 기술을 기반으로 촬영된 버섯의 영상정보를 분석하여 버섯의 생장상태를 판단하고 필요한 작업 이벤트 정보를 사용자단말기로 전송하여 사용자에게 전달하도록 하는 발명이다. claims: 관리로봇을 이용한 인공지능 기반의 버섯 재배관리 시스템에 있어서,버섯을 재배하기 위한 실내공간(110)이 형성되고, 상기 실내공간(110)에는 버섯이 재배되는 복수의 재배단(120)들이 배치되고, 상기 실내공간(110)에는 버섯 재배에 필요한 환경을 조성하는 환경조성수단(130)이 배치되는 재배실(100)과;상기 재배실(100)의 실내공간(110)에서 자율주행으로 이동하며, 재배실(100)내의 환경정보를 감지하여 생장환경통합관리부(300)로 전송하고, 복수의 재배단(120)에서 재배되는 버섯들을 촬영한 버섯의 생장상태 영상정보를 생장환경통합관리부(300)로 전송하는 관리로봇(200)과;상기 관리로봇(200)이 전송한 재배실(100)의 환경정보를 이용해 재배실(100)이 버섯 재배에 적정한 환경이 되도록 재배실(100)에 배치된 환경조성수단(130)을 제어하고, 관리로봇(200)이 전송한 버섯의 생장상태 영상정보를 이용해 버섯의 생장상태를 분석 파악하여 재배단별 버섯생장 상태정보와 재배단별 작업 이벤트 정보를 생성하고, 생성된 재배단별 작업 이벤트 정보를 사용자단말기(400)로 전송하는는 생장환경통합관리부(300))와;버섯 수확이나 부패에 관한 작업 이벤트 정보를 사용자에게 출력 표시하는 사용자단말기(400)를 포함하며,상기 관리로봇(200)은 생장환경통합관리부(300)로 환경정보를 전송 시, 해당 재배실(100)의 고유 아이디 정보를 환경정보에 매칭 시켜 전송하고, 버섯의 생장상태 영상정보 전송 시, 해당 재배단(120)의 고유 식별 정보를 버섯의 생장상태 영상정보에 매칭 시켜 전송하는 것을 특징으로 하는 관리로봇을 이용한 인공지능 기반의 버섯 재배관리 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

797/1150 Row 797: application_number: 1020190153206, combined_string: invention_title: 식물공장 대여 시스템 abstract: 본 발명은 식물공장 시스템에 관한 것으로, 보다 상세하게는 작물을 선택할 수 있는 작물선택, 상기 작물선택의 현황을 볼 수 있는 마이페이지,그리고, 현재 생장 시키고 있는 작물을 확인하며 관리할 수 있는 농장,상기에서 발생하는 문제점을 질문하는 문의, 상기 내 농장에서 키우고 있는 작물에게 필요한 물품을 구매할 수 있는 상점을 포함하고 있는 식물공장 대여 시스템 claims: 작물을 선택할 수 있는 작물선택;상기 작물선택의 현황을 볼 수 있는 마이페이지; 그리고, 현재 생장 시키고 있는 작물을 확인하며 관리할 수 있는 내 농장 ;상기에서 발생하는 문제점을 질문하는 문의상기 내 농장에서 키우고 있는 작물에게 필요한 물품을 구매할 수 있는 상점;을 포함하고 있는 식물공장 대여 시스템, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

798/1150 Row 798: application_number: 1020190151000, combined_string: invention_title: 시스템 에어 환경 조절 장치 abstract: 본 발명은 실내 환경 조절 장치에 관한 것으로서, 기후조건과 재배작물의 종류를 고려하여 그룹화함으로써 우수한 재배작물의 정보를 서로 공유하는 실내 환경 조절 장치에 관한 것이다. 이를 위해 재배작물의 생육을 제어하도록 각 재배지에 설치 운용되며, 설치된 재배지의 기후조건 정보와 그룹핑된 재배작물의 생육데이터 정보를 상위단으로 전송하는 서브 제어기, 및 각각의 서브 제어기에서 전송된 재배지의 기후조건 정보와 재배작물의 생육데이터 정보를 취합하여 각 지역별로 데이터를 그룹핑하고, 서브 제어기의 정보 요청 메시지에 따라 조건에 맞는 재배작물의 생육데이터 정보를 서브 제어기로 전송하는 주 제어기를 포함하는 것을 특징으로 하는 실내 환경 조절 장치가 개시된다. claims: 실내의 에어 환경 조절을 통해 축산물 또는 재배작물의 생육을 제어하도록 각 생육지에 설치 운용되는 서브 제어기, 및각각의 서브 제어기에서 전송된 축산물 또는 재배작물의 생육데이터 정보를 취합하여 지역별로 데이터를 그룹화하고, 상기 서브 제어기의 정보 요청 메시지에 따라 조건에 맞는 상기 생육데이터 정보를 상기 서브 제어기로 전송하는 주 제어기를 포함하는 것을 특징으로 하는 시스템 에어 환경 조절 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

799/1150 Row 799: application_number: 1020190151404, combined_string: invention_title: 작물 재배면적 추출방법 및 프로그램 abstract: 본 발명은 작물 재배면적 추출방법 및 프로그램에 관한 것으로, 고정밀 드론 공간정보 기술 활용의 작업 과정 단순화, 단순화된 공정을 통한 단시간내 광범위지역 드론촬영, RGB센서와 다중분광센서를 통한 영상정보 획득, 지구별 영상촬영조사 시작점 및 운항경로 제시, 촬영지구별 정사영상 및 3D맵 제작을 통한 작물재배면적 산정과 지구별 지형분석이 처리되는 A) 드론을 활용한 영농현황조사 처리과정, 촬영지구에 대한 전수조사 결과를 프로그램에서 제공하는 현황도에 입력하여 작물재배 현황지도 작성, 지구별 대표지점을 선정하여 농가와 연계하며 파악된 작물의 수확량과 생육상태에 대한 정보 입력, 작물의 전수조사 리스트로서 두 지역 이상 분포하는 작물의 경우 숫자로 표기, 특정 지역에서만 재배되는 작물의 경우 알파벳으로 표기되도록 처리되는 B) 전수조사 처리과정, 및 RGB센서에서 획득한 영상을 통한 재배면적 산정과 대표지역의 AI를 통한 작물종류 분류, 다중분광센서에서 획득한 분광정보를 통해 NDVI 지수를 통해 작물의 생육정보 도식화, 국내외 연구사례 조사를 통한 작물판독 증진방안 제시, 간척농지 영농현황조사에 적합한 가이드라인을 제시하는 방식으로 처리되는 C) 촬영결과를 통한 작물판독 검토방안 처리과정을 포함하는 작물 재배면적 추출 방법 및 프로그램 제공에 따라, 미래의 작물 농업에 대한 제반적인 개발 방안을 효과적으로 제시할 수 있다. claims: 고정밀 드론 공간정보 기술 활용의 작업 과정 단순화, 단순화된 공정을 통한 단시간내 광범위지역 드론촬영, RGB센서와 다중분광센서를 통한 영상정보 획득, 지구별 영상촬영조사 시작점 및 운항경로 제시, 촬영지구별 정사영상 및 3D맵 제작을 통한 작물재배면적 산정과 지구별 지형분석이 처리되는 A) 드론을 활용한 영농현황조사 처리과정;촬영지구에 대한 전수조사 결과를 프로그램에서 제공하는 현황도에 입력하여 작물재배 현황지도 작성, 지구별 대표지점을 선정하여 농가와 연계하며 파악된 작물의 수확량과 생육상태에 대한 정보 입력, 작물의 전수조사 리스트로서 두 지역 이상 분포하는 작물의 경우 숫자로 표기, 특정 지역에서만 재배되는 작물의 경우 알파벳으로 표기되도록 처리되는 B) 전수조사 처리과정; 및RGB센서에서 획득한 영상을 통한 재배면적 산정과 대표지역의 AI를 통한 작물종류 분류, 다중분광센서에서 획득한 분광정보를 통해 NDVI 지수를 통해 작물의 생육정보 도식화, 국내외 연구사례 조사를 통한 작물판독 증진방안 제시, 간척농지 영농현황조사에 적합한 가이드라인을 제시하는 방식으로 처리되는 C) 촬영결과를 통한 작물판독 검토방안 처리과정;을 포함하는 것을 특징으로 하는 작물 재배면적 추출 방법.상기 무인기로부터 촬영된 작물 대상지의 영상 정보를 활용하여 작물 종류를 판독하고 상기 영상의 이미지를 편집 수정하여 소정의 표준 데이터로 서버에 저장하는 인공지능 프로그램인 것을 특징으로 하는 작물 재배면적 추출 프로그램., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

800/1150 Row 800: application_number: 1020190151040, combined_string: invention_title: 시설 운영 이력을 저장할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 스마트팜 운영 시스템은, 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서를 포함하고 상기 환경정보를 포함하는 경작지정보를 생성하는 센서박스; 경작자가 상기 경작지정보를 기반으로 상기 재배환경을 조절하기위해 상기 시설장비를 작동시키는 제어정보를 포함하는 경작정보를 입력하는 경작자 단말기; 상기 제어정보를 기반으로 상기 시설장비를 작동시키는 제어박스; 및, 상기 경작지정보 및 상기 경작정보를 상기 작물의 생육단계에 매칭하여 저장하는 저장부를 가지는 정보서버;를 포함한다. claims: 작물이 재배되고 온도 및 습도를 포함하는 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 센싱하여 환경정보를 생성하는 환경센서를 포함하고 상기 환경정보를 포함하는 경작지정보를 생성하는 센서박스;경작자가 상기 경작지정보를 기반으로 상기 재배환경을 조절하기위해 상기 시설장비를 작동시키는 제어정보를 포함하는 경작정보를 입력하는 경작자 단말기;상기 제어정보를 기반으로 상기 시설장비를 작동시키는 제어박스; 및,상기 경작지정보 및 상기 경작정보를 상기 작물의 생육단계에 매칭하여 저장하는 저장부를 가지는 정보서버;를 포함하고, 상기 경작지정보는, 상기 작물의 이미지를 포함하는 작물정보를 더 포함하고, 상기 경작정보는, 상기 경작자가 상기 작물정보를 기반으로 상기 작물의 생육상태를 규정하는 생육정보를 더 포함하고상기 정보서버는, 상기 경작지정보 및 상기 경작정보를 빅데이터 분석방법으로 분석하여 상기 작물의 최적 생육조건을 위한 상기 시설장비를 작동시키는 최적 제어정보를 예측하여 생성하는 예측하는 예측부;를 더 포함하여,상기 작물을 재배하는 상기 경작자의 경험 및 상기 생육 상태에 따른 상기 최적 제어정보를 디지털 정보로 생성할 수 있고,상기 경작지는, 외부와 격리되어 상기 작물이 재배되는 내부를 가지며,상기 센서박스는,상기 경작지의 외부와 내부 각각의 재배정보를 감지하는 내외부 환경감지유닛 및 상기 경작지 내부의 지중 전기전도도와 산도(Ph)와 함수율 및 온도를 포함하는 내부지중 환경감지유닛을 포함하고, 상기 정보서버는, 상기 저장부에 저장된 상기 경작지정보 및 상기 경작정보를 웹(web)형식의 표시정보로 변환하는 변환부를 포함하고,상기 경작자 단말기는,상기 표시정보를 디스플레이하는 디스플레이부를 포함하고, 상기 경작자 단말기는, 스마트폰, 패드 및 탭을 포함하는 개인용 모바일기기 또는 개인용 컴퓨터(PC) 및 노트북을 포함하는 컴퓨터를 포함하고, 상기 표시정보는,반응형 웹(web)형식의 표시 정보이고,상기 경작지정보 및 상기 제어정보는 정형 데이터(structured data)이고, 상기 생육정보는,비정형 데이터(unstructured data)이며,상기 예측부는,상기 생육정보를 비정형 데이터 마이닝 방법으로 분석하고, 상기 경작지정보 및 상기 제어정보를 정형 데이터 마이닝 방법으로 분석하고, 상기 예측부는, 상기 생육정보를 텍스트 마이닝 기법 및 오피니언 마이닝 기법을 복합적으로 사용하여 분석하여, 상기 작물정보와 상기 작물정보를 기반으로 상기 경작자가 판단한 상기 작물의 생육상태 상호간의 연관성을 도출함으로써, 상기 최적 제어정보에 의한 상기 최적 생육조건의 신뢰성을 더욱 향상시킬 수 있는 시설 운영 이력을 저장할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

801/1150 Row 801: application_number: 1020190151135, combined_string: invention_title: 재배 이력을 추적할 수 있는 스마트팜 운영 시스템 abstract: 개시되는 재배 이력을 추적할 수 있는 스마트팜 운영 시스템은, 작목이 재배되고 재배환경을 조절하는 시설장비가 구비되는 경작지; 상기 재배환경을 감지하여 환경정보를 생성하는 환경센서를 포함하는 센서부; 상기 환경정보를 기반으로 상기 시설장비를 작동시키는 제어정보와 상기 작목의 재배정보 및 상기 경작자의 이력정보를 포함하는 경작자정보를 상기 경작자가 입력하는 경작자 단말기; 상기 환경정보와 상기 제어정보와 상기 재배정보 및 상기 경작자정보를 수신하여 생산이력정보로 저장하는 저장부를 가지고 클라우드(cloud) 컴퓨팅을 기반으로 운영되는 정보서버; 상기 작목에서 재배된 농산품을 판매하는 판매처; 및 상기 농산품의 생산이력정보를 상기 정보서버로부터 수신하여 구매자에게 표시하는 구매자 단말기;를 포함한다. claims: 작목이 재배되고 재배환경을 조절하는 시설장비가 구비되는 경작지;상기 재배환경을 감지하여 환경정보를 생성하는 환경센서를 포함하는 센서부;상기 환경정보를 기반으로 상기 시설장비를 작동시키는 제어정보와 상기 작목의 재배정보 및 경작자의 이력정보를 포함하는 경작자정보를 상기 경작자가 입력하는 경작자 단말기;상기 환경정보와 상기 제어정보와 상기 재배정보 및 상기 경작자정보를 수신하여 생산이력정보로 저장하는 저장부를 가지고 클라우드(cloud) 컴퓨팅을 기반으로 운영되는 정보서버;상기 작목에서 재배되어 판매처에서 판매되는 농산품의 생산이력정보를 상기 정보서버로부터 수신하여 구매자에게 표시하는 구매자 단말기;를 포함하고,상기 정보서버는, 상기 농산품이 출하될 때 출하시점과 포장용량과 상기 생산이력정보를 인터넷상에서 검색할 수 있는 좌표정보를 포함하는 고유코드를 생성하여 상기 농산품에 부착하는 재배 이력을 추적할 수 있고,상기 판매처는 상기 농산품이 판매될 때 상기 고유코드가 스캔되면, 상기 농산품의 판매정보를 생성하고,상기 정보서버는 상기 판매정보를 기반으로 하여 상기 농산품의 상기 생산이력정보에 따른 판매량을 포함하는 매출정보를 생성하고,상기 경작자 단말기는 상기 매출정보를 수신하여 상기 경작자에게 표시하고, 상기 구매자 단말기는,상기 구매자가 구매하고자 하는 상기 농산품의 상기 고유코드를 스캔하면 코드 스캔정보를 생성하고, 상기 정보서버에서 상기 코드 스캔정보에 매칭하는 상기 농산품의 상기 생산이력정보를 수신하여 표시하고, 상기 정보서버는,상기 구매자 단말기로부터 상기 농산품의 상기 코드 스캔정보를 수신하면, 상기 농산품에 대한 검색회수를 포함하는 검색정보를 생성하여 상기 농산품에 매칭하여 저장하고,상기 경작자 단말기는, 상기 검색정보를 수신하여 상기 경작자에게 표시하고, 상기 정보서버는,상기 생산이력정보와 상기 매출정보 및 상기 검색정보를 데이터 마이닝 기법으로 분석하여, 상기 농산품의 상기 생산이력정보에 따른 판매량을 포함하는 매출정보 및 상기 검색회수 대비 판매량의 비율인 판매성공률 정보를 생성하는 분석부를 더 포함하고,상기 경작자 단말기는, 상기 매출정보 및 상기 판매성공률 정보를 수신하여 상기 경작자에게 표시하고, 상기 고유코드는 상기 판매처의 위치 및 매장 크기를 포함하는 판매처정보를 포함함으로써, 상기 경작자가 상기 농산품의 상기 매출정보를 상기 판매처별로 관리할 수 있고, 상기 정보서버는,상기 구매자가 관심있는 구매요소를 확인할 수 있도록, 상기 구매자의 상기 구매자 단말기를 이용하여 상기 생산이력정보를 확인할 때, 최종적으로 확인한 생산이력정보의 세부정보를 상기 검색정보에 포함시켜 저장하고,상기 생산이력정보의 세부정보는, 상기 환경정보, 상기 제어정보, 상기 경작자정보 및 상기 재배정보를 포함하는 것을 특징으로 하는, 재배 이력을 추적할 수 있는 스마트팜 운영 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

802/1150 Row 802: application_number: 1020190150427, combined_string: invention_title: 경작지 관리 시스템 abstract: 본 발명은 경작지의 농업용수에 대한 전반적인 관리를 통해 경작물의 안정성과 고품질 및 고수확성을 확보할 수 있어 물을 이용하여 경작물을 재배하는 논, 수경재배 업종에 적용할 수 있는 경작지 관리 시스템에 관한 것으로, 더욱 상세하게는 작동에 대한 제어와 농업용수에 대한 각종 정보, 농업용수의 정보를 토대로 재배 환경을 개선하는 관리제어부, 상기 관리제어부의 관리를 통해 경작지의 농업용수의 양을 조절하는 용수량조절부로 구성하여; 무선통신을 이용하여 자동화방식으로 전원 및 작동을 제어할 수 있어 관리가 편리한 효과가 있다. claims: 벼를 경작하는 경작지의 농업용수의 양을 조절하기 위한 시스템에 있어서,경작지(1)의 일측에 설치되며 전원공급과 작동을 제어하는 컨트롤부(10);상기 컨트롤부(10)의 하부에는 경작지(1)의 농업용수의 수위, 수소이온농도 및 비료성분을 검출하는 검출부(20);상기 컨트롤부(10)의 하부에는 경작지(1)의 담겨진 농업용수에 산성중화제 및 액상비료를 공급하는 약액부(30)로 이루어지는 관리제어부(40); 및상기 경작지(1)의 타측에는 농업용수 담수양을 조절하도록 상기 관리제어부(40)의 신호를 전달받아 작동하는 용수량조절부(50); 를 형성하여,상기 관리제어부(40) 및 용수량조절부(50)를 개인통신기기(60)를 이용하여 작동 및 제어할 수 있도록 구성하며,상기 약액부(30)는 농업용수가 산성도가 증가할 때 산성도를 낮추기 위한 알카리성약액을 저장하는 약액통(31)에 연결되어 경작지(1)에 약액을 배출하도록 경작지(1)의 바닥에 설치하는 약액호스(32); 및농업용수에 영양분을 공급하기 위한 액상비료를 저장하는 비료통(33)에 연결되어 경작지(1)에 액상비료를 배출하도록 경작지(1)의 바닥에 설치하는 비료호스(34); 를 구성하되, 약액호스(32)와 비료호스(34)를 직교 배치로 설치하여 약액과 비료가 동일 지점에서 배출되는 것이 방지되며,상기 용수량조절부(50)는 농업용수가 흘러갈 수 있는 통로(51)가 중앙에 형성되도록 한 쌍의 측판(52)이 바닥판(57)에 연결된 디귿자 형태이며, 상기 측판(52)의 외측으로 경작지(1)에 매립되는 매립단(53)을 각각 형성하는 배수몸체(54);상기 배수몸체(54)의 통로(51)에는 회전방식으로 농업용수를 차단 및 배수하되, 경작지(1)에 담수된 농업용수의 중량에 의해 개폐시 응력이 집중되지 않도록 단면이 휘어진 사각판 형태의 배수조절판(55); 을 형성하고,상기 배수조절판(55)을 작동시키기 위하여 하나의 측판(52) 외측에 설치하는 모터(56)와 체인(58)으로 연결 형성하며,상기 모터(56) 구동을 위하여 자체적으로 전원을 생산 공급하는 태양광셀(SC); 을 구성하는 것을 특징으로 하는 경작지 관리 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

803/1150 Row 803: application_number: 1020190149900, combined_string: invention_title: 기상요인을 고려한 대두 수확량 예측 방법 abstract: 본 발명은 기상정보를 이용하여 작황 환경을 고려한 수확량을 산출하는 기상요인을 고려한 대두 수확량 예측 방법에 관한 기술로, 기상정보 및 수율 예측정보를 산출하기 위해, 최근 10년간의 통계를 활용한 단순 선형 회귀 방법으로 추세제거 수율을 산출하는 추세제거 수율 산출 단계, 수집된 기상 자료를 기반으로, 가공된 기상자료를 생산하는 기상자료 생산 단계, 기간별 다중선형회귀모형을 도출하는 다중선형회귀모형 도출 단계, 회귀모형을 도출하는 회귀모형 도출 단계를 포함하여, 국제 농산물 가격과 곡물에 대한 현황 파악을 통해, 곡물의 생산량 변동에 따른 대책을 수립할 수 있는 효과가 있다. claims: 최근 10년간의 통계를 활용한 단순 선형 회귀 방법으로 추세제거 수율을 산출하는 추세제거 수율 산출 단계;수집된 기상 자료를 기반으로, 가공된 기상자료를 생산하는 기상자료 생산 단계;기간별 다중선형회귀모형을 도출하는 다중선형회귀모형 도출 단계;회귀모형을 도출하는 회귀모형 도출 단계;를 포함하는 기상요인을 고려한 대두 수확량 예측 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

804/1150 Row 804: application_number: 1020190148514, combined_string: invention_title: 군집비행 드론 플랫폼을 이용한 재배현황 및 식생지수 분석 시스템 abstract: 본 발명은 군집비행 드론 플랫폼을 이용한 재배현황 및 식생지수 분석 시스템에 관한 것이다.보다 구체적으로, 관리대상영역에 대한 전체영상을 생성하여 실제면적을 산출하고, 산출된 실제면적을 기준으로 각 슬레이브 드론에서 촬영할 분할영역 및 초기위치를 설정하는 마스터 드론, 상기 마스터 드론으로부터 해당 촬영영역 및 초기위치를 수신하면, 해당 초기위치로 이동하여 기설정된 경로에 따라 군집비행하며 촬영한 분할영상을 생성하는 복수의 슬레이브 드론 및 상기 마스터 드론 및 복수의 슬레이브 드론으로부터 촬영된 영상을 수집하여 상기 관리대상영역의 재배현황 및 식생지수를 파악하는 관리서버를 포함하는 것을 특징으로 하는 군집비행 드론 플랫폼을 이용한 재배현황 및 식생지수 분석 시스템에 관한 것이다. claims: 관리대상영역에 대한 전체영상을 생성하여 실제면적을 산출하고, 산출된 실제면적을 기준으로 각 슬레이브 드론에서 촬영할 분할영역 및 초기위치를 설정하는 마스터 드론;상기 마스터 드론으로부터 해당 촬영영역 및 초기위치를 수신하면, 해당 초기위치로 이동하여 기설정된 경로에 따라 군집비행하며 해당 분할영역을 촬영한 분할영상을 생성하는 복수의 슬레이브 드론; 및상기 마스터 드론 및 복수의 슬레이브 드론으로부터 촬영된 영상을 수집하여 상기 관리대상영역의 재배현황 및 식생지수를 파악하는 관리서버를 포함하는 것을 특징으로 하는 군집비행 드론 플랫폼을 이용한 재배현황 및 식생지수 분석 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

805/1150 Row 805: application_number: 1020190147584, combined_string: invention_title: 스마트 팜 통합관리 플랫폼 시스템 및 이의 운영방법 abstract: 본 발명은 농작물을 재배하고자 하는 생산자에게 해당 농작물의 재배에 필요한 자원을 제공함과 동시에 생산자로부터 획득한 농작물이 소비자에게 원활하게 공급될 수 있도록 하는 스마트 팜 통합관리 플랫폼 시스템 및 이의 운영방법에 관한 것으로, 더욱 상세하게는 소비자에게 공급하기 위한 농작물이 생산자에 의해 재배하는 제어수단와, 적어도 하나 이상의 상기 제어수단에 농작물 재배에 필요한 정보는 물론, 해당 농작물을 재배시에 필요한 인력이나 장치를 제공하며, 통신망을 통해 소비자와 생산자 간에 농작물의 매매가 이루어질 수 있도록 중개하는 통합관리부 및 농작물이 재배되는 상기 제어수단를 운영하는 생산자는 물론, 예비 생산자에게 필요한 농작물 재배에 관한 재배정보를 제공하는 시스템운영부를 포함하되, 상기 시스템운영부는 상기 제어수단이 위치한 지역의 기상변화정보와 병충해정보로 이루어진 재배정보를 실시간으로 제공하는 것을 특징으로 한다. claims: 소비자에게 공급하기 위한 농작물이 생산자에 의해 재배되는 온실운영부(100);네트워크 통신망을 통하여 적어도 하나 이상의 상기 온실운영부(100)에 농작물 재배에 필요한 기술정보, 인력정보 및 장치정보를 제공하는 통합관리부(200); 및 상기 생산자와 소비자 사이에 재배농산물의 판매와 구매에 관한 정보를 제공하는 시스템운영부(300);를 포함하는 스마트 팜 통합관리 플랫폼 시스템에 있어서, 상기 온실운영부(100)는 외기의 영향이 없이 내부에 구비된 토양에서 농작물이 재배될 수 있는 공간을 제공하는 하우스본체(110); 제어수단(170)의 제어를 통해 상기 하우스본체(110)의 실내공기를 외부로 배출하는 유동팬(120); 상기 하우스본체(110)의 내부 온도가 적정온도로 유지할 수 있도록 상기 하우스본체(110)의 실내온도를 유지하기 위한 온도조절부재(130); 상기 제어수단(170)에 의해 제어되되 해당 토양의 영양분을 분석하는 토양정보센서(140); 상기 제어수단(170)의 제어에 의해 농작물 재배에 필요한 물을 해당 토양에 제공하는 관수제공부재(150); 및 상기 하우스본체(110) 내부나 외부에 설치되는 영상제공부재(160);를 포함하되, 상기 토양정보센서에 의해서 분석된 토양의 영양성분에 따라서 필요한 영양성분을 토양에 공급하는 양액기(113)를 더 구비하고,상기 통합관리부(200)는 생산자 및 소비자를 개별적으로 관리할 수 있는 적어도 하나 이상의 관리매장(210);실시간으로 상기 온실운영부(100)의 제어수단(170)로부터 전송된 실시간 생육정보와 시스템 환경으로부터 전송된 운영정보를 수신하여 온실조건DB(270)와 비교하는 생육환경 모니터링모듈(221);농작물을 재배하는데 필요한 영농자원을 예약하고, 비번인 영농자원을 대여하여 필요한 생산자에게 매칭시키고 영농자원DB(230)에 저장하는 모듈(222);기술지원 단말기(310)로부터 등록된 영농자원DB(230)에 대한 리소스 어카운트 정보를 수신하여 저장하고, 영농자원 사용시에 소요되는 비용을 리소스 어카운트 정보를 통해서 처리하는 모듈(223);소정의 시간에 생육환경 모니터링DB(250)로부터 동일 품종별로 축적된 생육정보 및 스마트팜 운영정보를 추출하여 빅데이터 분석 및 데이터마이닝을 통해서 예측정보 및 분석정보를 생성하여 분석DB(260)에 저장하는 데이터 분석모듈(224); 상기 소비자와 생산자 사이에 거래가 발생하면 해당 농산물에 대한 최초 재배부터 수확까지 농산물의 생산이력정보를 생산이력DB(280)로부터 수신받아 소비자 단말기(320)에 송신하고, 소비자 단말기(320)로부터 고객정보를 수신하여 주문정보를 생성하여 판매DB(240)에 저장하고, 생산자 단말기(330) 및 미리 연계된 배송업체에 주문정보를 송신하는 모듈(225); 을 포함하되, 상기 리소스 어카운트는 영농자원DB(230)로부터 수신된 영농자원정보를 기초로 하여 리소스 어카운트 알고리즘에 의해서 산출되며, 개별 생산자마다 보유한 토탈 리소스 어카운트 정보에 누적되어, 영농자원을 사용하면 상기 영농자원에 설정된 리소스 어카운트 만큼 차감되고, 영농자원을 대여해주면 상기 영농자원에 설정된 리소스 어카운트 만큼 증가되는 것이며, 상기 시스템운영부(300)는, 생산자 단말기(330)와; 소비자 단말기(320);을 포함하되, 상기 생산자 단말기(330)는, 온실조건DB(270)에 저장된 생육정보를 조회하거나 직접 입력받아 제어수단(170)을 통해 온실운영부(100)에 있는 센서를 제어할 수 있는 생육조건 입력/조회모듈(331); 생육환경 모니터링DB(270)에 있는 생육정보와 운영정보를 실시간으로 모니터링 할 수 있는 실시간 생장환경 모니터링 모듈(332); 분석DB(260)에서 추출한 예측 및 분석 정보, 즉 동일 품종별로 축적된 생육정보 및 운영정보를 빅데이터 분석 및 데이터마이닝을 통해서 생성된 예측정보 및 분석정보를 제공하는 모듈(333); 농작물을 재배하는데 필요한 영농자원을 조회하고 관리하는 모듈(334); 온실을 영역ID에 따라 분할하고 판매하는 모듈(335); 생산자가 생산한 농산물의 생산이력을 관리하는 모듈(336); 판매할 농산물을 선택하게 하고 주문정보를 생성하여 소비자 단말기에 전송하는 농산물 판매모듈(337); 생산자별로 보유하고 있는 리소스 어카운트 정보를 조회하는 모듈(338);을 포함하고,상기 소비자 단말기(320)는,상기 구매한 영역ID에 따른 온실조건DB(270)에 저장된 생육조건데이터를 조회하거나 직접 입력하여 제어수단(170)을 통해 온실운영부(100)에 있는 센서를 제어할 수 있는 영역 생육조건 입력/조회모듈(321); 영역ID에 따라 분할된 온실을 구매하고 수확량에 따른 목표를 설정하는 모듈(322); 영역ID의 생육환경 모니터링DB(270)에 저장되어 있는 생육정보 및 운영정보를 실시간으로 모니터링 할 수 있는 영역 실시간 생장환경 모니터링 모듈(323); 영역ID의 농작물을 재배하는데 필요한 영농자원을 관리하고 제어하는 모듈(324); 소비자가 선택한 농산물에 대한 생산이력을 조회하는 모듈(325); 생산된 농산물 또는 특정영역의 농산물을 선택하고 구매하고 주문정보를 생산자 단말기로 전송하는 농산물 구매 모듈(326); 예비농민 또는 소비자에게 분석DB(260)에서 추출한 동일 품종별로 축적된 생육정보 및 운영정보를 빅데이터 분석 및 데이터마이닝을 통해서 생성된 예측정보 및 분석정보를 제공하는 모듈(327); 생산 전에 설정된 수확목표량과 현재 수확량을 비교하여 초과되면 초과실적을 기준으로 리소스 어카운트 알고리즘에 따라 리소스 어카운트가 설정되고 정산되는 모듈(328);을 더 포함하는 것을 특징으로 하는 스마트 팜 통합관리 플랫폼 시스템.제1항의 스마트 팜 통합관리플랫폼 시스템의 운영방법에 있어서, 상기 기술지원 단말기(310)를 통해서 영농자원정보를 입력받고 리소스 어카운트 생성모듈(222)에 의해서 영농자원별 리소스 어카운트가 생성되고 설정되는 단계(W1);상기 생산자 단말기(330)를 통해서 온실조건정보를 입력받아 온실조건DB(270)에 저장하고, 온실운영부의 제어수단(170)으로 전송하여 온실의 센서들을 제어하도록 하는 단계(W2);상기 생산자 단말기(330)를 통해서 생육환경을 모니터링하고 이상 데이터 플래그를 체크하고, 이상이 있는 경우 필요한 조치를 취하는 단계(W3);상기 생산자 단말기(330)를 통해서 필요한 영농자원이 선택되고, 영농자원 매칭모듈(223)로 영농자원정보가 전송되어 자원의 사용이 발생되며, 보유한 토탈 리소스 어카운트에 의해서 비용이 정산되는 단계(W4);매월 마다 데이터 분석모듈(224)에 의해 동일한 품종별로 축적된 생육정보 및 스마트팜 운영정보를 추출하여 빅데이터 분석 및 데이터마이닝을 통해서 예측정보 및 분석정보를 생성하여 분석DB(260)에 저장되는 단계(W5);상기 생산자 단말기(330)를 통해서 예측 및 분석정보를 조회하여 최적의 생육정보를 수신받고, 신규 온실조건정보를 제어수단(170)으로 전송하여 온실의 센서들을 제어하도록 하는 단계(W6);상기 생산자 단말기(330)를 통해서 생산한 농산물 생육정보와 농산물 이력정보를 수신받고, 소비자에 의해서 구매가 결정되면 해당 주문정보가 주문정보생성모듈(225)로 전송되는 단계(W7);상기 주문정보생성모듈(225)은 주문정보를 소비자와 배송업체에 전송하여 유통이 시작되도록 알리는 단계(W8);를 포함하는 것을 특징으로 하는 스마트 팜 통합관리 플랫폼시스템의 운영방법.제1항의 스마트 팜 통합관리플랫폼 시스템의 운영방법에 있어서, 상기 소비자 단말기(320)를 통해서 온실하우스의 구획화된 온실영역을 구매하여 영역구매자로 구분되고, 목표수확량을 설정하고, 정해진 토탈 리소스 어카운트를 지급받는 단계(C1);상기 소비자 단말기(320)를 통해서 예측 및 분석정보를 조회하여 최적의 생육정보를 수신받고, 신규 온실조건정보를 제어수단(170)으로 전송하여 온실의 센서들을 제어하도록 하는 단계(C2);상기 소비자 단말기(320)를 통해서 생육환경을 모니터링하고 이상 데이터 플래그를 체크하고, 이상이 있는 경우 필요한 조치를 취하는 단계(C3);상기 소비자 단말기(320)를 통해서 필요한 영농자원이 선택되고, 영농자원 매칭모듈(223)로 영농자원정보가 전송되어 구매된 영역의 온실에서 자원의 사용이 발생되며, 보유한 토탈 리소스 어카운트에 의해서 비용이 정산되는 단계(C4);상기 소비자 단말기(320)를 통해서 영역 구매자가 생산 전에 설정한 수확목표량와 현재 수확량을 비교하여 초과되면 리소스 어카운트 알고리즘에 따라 리소스 어카운트가 설정되고, 토탈 리소스 어카운트에 누적되는 단계(C5);상기 소비자 단말기(320)를 통해서 농산물 구매시, 보유한 토탈 리스소 어카운트를 통해서 결제가 가능하며, 해당 주문정보가 주문정보생성모듈(225)로 전송되는 단계(C6);상기 주문정보생성모듈(225)은 주문정보를 생산자와 배송업체에 전송하여 유통이 시작되도록 알리는 단계(C7);을 포함하는 것을 특징으로 하는 스마트 팜 통합관리 운영방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

806/1150 Row 806: application_number: 1020190147163, combined_string: invention_title: 상생형 병해충 관리 시스템 및 그 방법 abstract: 상생형 병해충 관리 시스템 및 그 방법에 관한 것으로, 상생형 병해충 관리시스템은 사용자 농장의 토양 상태, 병해충 발생 정보, 작물의 특징 정보, 그리고 기상 정보 중에서 하나 이상의 데이터를 수집하고, 인근 농장의 작물 정보, 인근 농장의 병해충 정보를 수집하는 수집부, 데이터를 미리 학습된 머신러닝 알고리즘에 적용하여 사용자 농장에서 발생가능성이 임계치 이상인 병해충을 예측하는 예측부, 그리고 예측된 병해충에 대응하는 방제 방법 중에서 인근 농장에서의 위험 요소를 최소화한 방제 방법을 선별하여 상생형 방제 방법을 추천하는 제어부를 포함한다. claims: 사용자 농장의 토양 상태, 병해충 발생 정보, 작물의 특징 정보, 그리고 기상 정보 중에서 하나 이상의 데이터를 수집하고, 인근 농장의 작물 정보, 상기 인근 농장의 병해충 정보를 수집하는 수집부, 상기 데이터를 미리 학습된 머신러닝 알고리즘에 적용하여 상기 사용자 농장에서 발생가능성이 임계치 이상인 병해충을 예측하는 예측부, 그리고 예측된 상기 병해충에 대응하는 방제 방법 중에서 상기 인근 농장에서의 위험 요소를 최소화한 방제 방법을 선별하여 상생형 방제 방법을 추천하는 제어부를 포함하는 상생형 병해충 관리 시스템.사용자 농장의 토양 상태, 병해충 발생 정보, 작물의 특징 정보, 그리고 기상 정보 중에서 하나 이상의 데이터를 수집하는 단계, 수집한 상기 데이터를 미리 학습된 머신러닝 알고리즘에 적용하여 상기 사용자 농장에서 발생가능성이 임계치 이상인 병해충을 예측하는 단계, 인근 농장의 작물 정보, 상기 인근 농장의 병해충 정보를 수집하는 단계, 그리고 예측된 상기 병해충에 대응하는 방제 방법 중에서 상기 인근 농장에서의 위험 요소를 최소화한 방제 방법을 선별하여 상생형 방제 방법을 추천하는 단계, 를 포함하는 상생형 병해충 관리 시스템의 관리 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

807/1150 Row 807: application_number: 1020190145048, combined_string: invention_title: 농작물 재배 모니터링 시스템 및 이를 이용한 농작물 재배 모니터링 방법 abstract: 본 발명은 농작물을 재배하는 정보의 메타데이터를 통해 자동으로 분류하여 데이터베이스를 구축하고 사용자가 원하는 조건에 따라 농작물재배정보를 추출하여 시각화함으로 인해 사용자가 농작물의 재배과정을 용이하게 분석할 수 있어 농작물의 생산성을 향상시킬 수 있는 농작물 재배 모니터링 시스템 및 이를 이용한 농작물 재배 모니터링 방법에 관한 것이다.본 발명은 농작물이 재배되는 환경을 측정한 환경데이터와, 상기 농작물로 공급되는 양액을 측정한 양액데이터와, 상기 농작물의 성장을 측정한 생육데이터와, 상기 농작물의 수확량을 입력한 생산량데이터와, 상기 농작물의 재배에 소요된 소요비용을 입력한 비용데이터를 메타데이터처리하여 농작물재배정보를 생성하기 위한 다수의 스마트팜(100)과, 상기 다수의 스마트팜(100)으로부터 수신받은 농작물재배정보의 메타데이터를 자동으로 추출하여 미리 설정된 키워드별로 분류하여 데이터베이스로 구축한 후 상기 데이터베이스 중에 사용자가 설정한 조건정보에 따라 데이터를 자동으로 추출하고 그룹화하여 도표화한 재배분석정보를 생성하기 위한 관제서버(200)와, 상기 관제서버(200)로부터 재배분석정보를 수신받아 디스플레이하기 위해 농작물의 재배기간 단위를 포함한 조건을 설정하여 상기 조건정보를 생성하기 위한 사용자단말기(300)를 포함한다. claims: 농작물이 재배되는 환경을 측정한 환경데이터와, 상기 농작물로 공급되는 양액을 측정한 양액데이터와, 상기 농작물의 성장을 측정한 생육데이터와, 상기 농작물의 수확량을 입력한 생산량데이터와, 상기 농작물의 재배에 소요된 소요비용을 입력한 비용데이터를 메타데이터처리하여 농작물재배정보를 생성하기 위한 다수의 스마트팜(100)과, 상기 다수의 스마트팜(100)으로부터 수신받은 농작물재배정보의 메타데이터를 자동으로 추출하여 미리 설정된 키워드별로 분류하여 데이터베이스로 구축한 후 상기 데이터베이스 중에 사용자가 설정한 조건정보에 따라 데이터를 자동으로 추출하고 그룹화하여 도표화한 재배분석정보를 생성하기 위한 관제서버(200)와, 상기 관제서버(200)로부터 재배분석정보를 수신받아 디스플레이하기 위해 농작물의 재배기간 단위를 포함한 조건을 설정하여 상기 조건정보를 생성하기 위한 사용자단말기(300)를 포함하는 농작물 재배 모니터링 시스템.농작물을 원격으로 관리하기 위한 스마트팜(100)에서 농작물이 재배되는 환경을 측정한 환경데이터와, 상기 농작물로 공급되는 양액을 측정한 양액데이터와, 상기 농작물의 성장을 측정한 생육데이터와, 상기 농작물의 수확량을 입력한 생산량데이터와, 상기 농작물의 재배에 소요된 소요비용을 입력한 비용데이터를 생성하는 데이터생성단계와,상기 스마트팜(100)에서 상기 환경데이터와 양액데이터와 생육데이터와 생산량데이터와 비용데이터를 메타데이터처리하여 농작물재배정보를 생성하고 관제서버(200)로 전송하는 메타데이터처리단계와,상기 관제서버(200)에서 수신받은 농작물재배정보의 메타데이터를 추출하는 상기 메타데이터추출단계와,상기 관제서버(200)에서 상기 추출된 메타데이터를 이용하여 미리 설정된 키워드별로 상기 농작물재배정보를 분류하여 데이터베이스로 구축하는 데이터베이스구축단계와,상기 관제서버(200)에서 농작물의 재배를 분석하기 위한 조건을 설정하는 사용자단말기(300)로부터 생성된 조건정보를 수신받는 조건정보수신단계와,상기 관제서버(200)에서 상기 데이터베이스의 메타데이터를 이용하여 상기 데이터베이스 중 조건정보에 대응되는 조건데이터를 추출하는 조건데이터추출단계와,상기 관제서버(200)에서 상기 조건데이터를 그룹핑하고 도표화하여 농작물분석정보를 생성하는 데이터가공단계와,상기 관제서버(200)로부터 생성된 농작물분석정보를 상기 사용자단말기(300)로 출력하는 출력단계를 포함하는 농작물 재배 모니터링 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

808/1150 Row 808: application_number: 1020190144305, combined_string: invention_title: 드론을 이용한 농약방제 시스템 및 그 방법 abstract: 본 발명은 드론을 이용한 농약방제시스템 및 그 방법에 관한 것으로, 더욱 상세하게는 경작자가 농약방제가 필요한 농경지 및 농약 정보와 방제 요청기일 등을 스마트폰을 통해 농약방제 수탁사의 관리서버로 신청할 수 있도록 구성되어 경작자의 스마트폰에 설치되는 농약방제 예약앱(120); 다수의 경작자들로부터 농약방제 예약 및 신청을 받고 관리하기 위한 방제예약 관리부(210)와, 회원으로 등록된 방제사업자들이 소유하고 있는 방제드론을 관리하기 위한 방제드론 관리부(220)와, 경작자의 방제 요청시 지번확인 또는 방제사업자에게 방역용역을 위임할 때 방제사업자가 예약된 농경지를 확인할 수 있도록 경작지 정보등을 제공하기 위한 토지(지리)정보 관리부(230)와, 경작자 또는 방제사업자의 비용입출금 등을 관리하기 위한 비용관리부(240)와, 시기별, 계절별 또는 작물별 발병될 수 있는 병충해정보와 농약정보를 경작자 또는 방제사업자에게 제공할 수 있도록 하는 병충해정보 제공부(250)를 농약방제 수탁사의 관리서버(200); 상기 관리서버에 방제드론의 등록 및 관리서버로부터 농약방제 업무의 송수신과 방제 후 방제내용을 전송하고, 방제 내용에 따라 방제비용을 청구할 수 있도록 구성되어 방제사업자의 스마트폰에 설치되는 농약방제 관리앱(320);을 포함하는 구성으로 이루어진다. claims: 경작자가 농약방제가 필요한 농경지 및 농약 정보와 방제 요청기일 등을 스마트폰을 통해 농약방제 수탁사의 관리서버로 신청할 수 있도록 구성되어 경작자의 스마트폰에 설치되는 농약방제 예약앱(120);다수의 경작자들로부터 농약방제 예약 및 신청을 받고 관리하기 위한 방제예약 관리부(210)와, 회원으로 등록된 방제사업자들이 소유하고 있는 방제드론을 관리하기 위한 방제드론 관리부(220)와, 경작자의 방제 요청시 지번확인 또는 방제사업자에게 방역용역을 위임할 때 방제사업자가 예약된 농경지를 확인할 수 있도록 경작지 정보등을 제공하기 위한 토지(지리)정보 관리부(230)와, 경작자 또는 방제사업자의 비용입출금 등을 관리하기 위한 비용관리부(240)와, 시기별, 계절별 또는 작물별 발병될 수 있는 병충해정보와 농약정보를 경작자 또는 방제사업자에게 제공할 수 있도록 하는 병충해정보 제공부(250)를 포함하는 농약방제 수탁사의 관리서버(200);상기 관리서버에 방제드론의 등록 및 관리서버로부터 농약방제 업무의 송수신과 방제 후 방제내용을 전송하고, 방제 내용에 따라 방제비용을 청구할 수 있도록 구성되어 방제사업자의 스마트폰에 설치되는 농약방제 관리앱(320);을 포함하여 이루어지는 것을 특징으로 하는 드론을 이용한 농약방제 시스템.경작자가 농약방제 수탁업무를 수행하는 농약방제 수탁사의 회원으로 등록하면서 자신이 경작하고 있는 농경지 정보를 입력하고, 농약방제 수탁사가 제공하는 농약방제 예약앱을 자신의 스마트폰에 설치하는 농약방제 예약앱 설치단계(S10);방제드론을 소유한 방제사업자가 농약방제 수탁사의 회원으로 가입하면서 자신이 소유한 방제용드론 정보를 등록하고, 농약방제 수탁사가 제공하는 농약살포 관리앱을 자신의 스마트폰에 설치하는 농약방제 관리앱 설치단계(S20);경작자가 농약방제 예약앱을 통해 농약방제 수탁사의 관리서버에 접속하여 농약방제에 필요한 경작지와 농약정보 및 방제요청 기일을 입력하여 농약방제를 예약하는 단계(S30);농약방제 예약이 접수된 관리서버에서 등록된 방제사업자의 방제드론 중 요청된 예약기일에 농약방제가 가능한 복수의 방제드론을 선별하여 선정하는 방제드론 선별/선정단계(S40);농약방제 수탁사의 관리서버에서 선별된 방제드론을 소유한 방제사업자에게 농약방제를 신청한 예약자의 정보를 전송하여 요청된 방제기일에 농약방제가 가능한지 여부를 확인하기 위한 방제 예약정보 전송단계(S50);방제 예약정보를 수신한 방제사업자가 요청기일에 농약방제가 가능한지 여부를 농약살포 관리앱을 이용하여 농약방제 수탁사에게 통지하는 농약방제 가능여부 통지단계(S60);방제사업자로부터 수신된 방제 가능여부 정보를 토대로 농약방제 수탁사의 관리서버에서 최종 농약방제가 가능한 방제용 드론을 확정, 확정된 방제드론 정보를 경작자 및 해당 방제사업자에게 전송하는 방제드론 확정 통지단계(S70);방제드론 확정정보를 수신한 방제사업자가 해당 기일에 예약자의 농경지에 농약을 방제한 후 농약방제 수탁사의 관리서버로 방제완료 내용 통보 및 방제 비용을 청구하는 방제비용 청구단계(S80);방제사업자로부터 방제완료보고 및 방제비용 청구가 이루어진 경우 농약방제 수탁사의 관리서버에서는 방제내용을 확인하고, 확인된 방제내용을 경작자에게 통지하면서 방제비용에 대해 입금을 요청하는 방제완료 통보 및 방제비용 입금 요청단계(S90);경작자로부터 비용입금이 확인된 관리서버에서 방제사업자에게 방제비용을 지불하는 방제비용 정산단계(S100);로 이루어지는 것을 특징으로 하는 드론을 이용한 농약 방제방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

809/1150 Row 809: application_number: 1020190144501, combined_string: invention_title: 모듈형 식물 재배 시스템 abstract: 인체에 필요한 미네랄을 엽채류에서 용이하게 섭취할 수 있도록 각각의 모듈에서 재배되는 엽채류에 게르마늄, 칼슘 또는 마그네슘의 함유량을 증대시키는 모듈형 식물 재배 시스템에 관한 것으로, 각각 엽채류 식물의 재배 기능을 구비한 다수의 재배 모듈, 상기 재배 모듈의 상태를 관리하는 관리자 단말기, 네트워크를 통해 상기 관리자 단말기로부터 전송된 재배 모듈에 관한 정보를 실시간으로 관리하는 관리 서버를 포함하고, 각각의 재배 모듈은 상기 재배 모듈에서 재배될 엽채류에 양액을 공급하는 양액 조성 조절기, 상기 재배 모듈의 양액조 내에 공급된 양액의 농도를 환산하는 농도 환산부, 상기 재배 모듈에서 재배되는 엽채류의 상태를 감지하는 상태 감지부를 포함하는 구성을 마련하여, 소비자가 인체에 필요한 게르마늄, 칼슘 또는 마그네슘 등의 미네랄이 함유된 엽채류를 용이하게 섭취하게 할 수 있다. claims: 각각 엽채류 식물의 재배 기능을 구비한 다수의 재배 모듈,상기 재배 모듈의 상태를 관리하는 관리자 단말기,네트워크를 통해 상기 관리자 단말기로부터 전송된 재배 모듈에 관한 정보를 실시간으로 관리하는 관리 서버를 포함하고,각각의 재배 모듈은상기 재배 모듈에서 재배될 엽채류에 양액을 공급하는 양액 조성 조절기,상기 재배 모듈의 양액조 내에 공급된 양액의 농도를 환산하는 농도 환산부,상기 재배 모듈에서 재배되는 엽채류의 상태를 감지하는 상태 감지부를 포함하는 것을 특징으로 하는 모듈형 식물 재배 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

810/1150 Row 810: application_number: 1020190141711, combined_string: invention_title: 바지선을 활용한 도서(島嶼)지역용 경작용수 공급시스템 abstract: 본 발명은 바지선을 활용한 도서(島嶼)지역용 경작용수 공급시스템에 관한 것으로, 보다 상세하게는 크고 작은 섬에서 작물을 경작하는데 사용하는 경작용수로 바지선에 저장한 우수(雨水)를 활용하여 부족한 지하수 자원을 보충할 수 있고, 도서(島嶼) 지역의 경작용수 부족에 따른 문제점을 해결할 수 있는 바지선을 활용한 도서(島嶼)지역용 경작용수 공급시스템에 관한 것으로,이를 위해 본 발명은, 우수 및 지하수가 저장된 저류지; 우수를 저장하는 저장공간이 구비된 바지선; 상기 바지선에 저장된 물을 전달 받아 저장하는 물탱크; 상기 저류지 또는 상기 물탱크 또는 상기 바지선에 저장된 물을 사용처로 전달하기 위한 관로; 상기 바지선에 저장된 우수를 상기 관로로 전달하기 위하여 상기 바지선을 상기 관로에 분리 가능하게 결합하는 결합모듈;을 포함한다. claims: 우수 및 지하수가 저장된 저류지(10);우수를 저장하는 저장공간이 구비된 바지선(20);상기 바지선(20)에 저장된 물을 전달 받아 저장하는 물탱크(30);상기 저류지(10) 또는 상기 물탱크(30) 또는 상기 바지선(20)에 저장된 물을 사용처로 전달하기 위한 관로(40);상기 바지선(20)에 저장된 우수를 상기 관로(40)로 전달하기 위하여 상기 바지선(20)을 상기 관로(40)에 분리 가능하게 결합하는 결합모듈(50);을 포함하되,상기 결합모듈(50)은,상기 바지선(20)에 구비된 배출관(51)과,상기 관로(40)에 구비되어 상기 배출관(51)의 단부가 결합하여 상호 연통되는 유입관(52)과,길이 방향으로 연장 형성되어 일단은 상기 배출관(51)측에 배치되고 타단은 상기 유입관(52)측에 배치되어 상기 배출관(51)과 상기 유입관(52)의 결합 부위를 감싸도록 배치되는 커플러(53) 및상기 커플러(53)의 내측에 배치되어 상기 배출관(51)측에서 전달된 이동력을 상쇄하는 레벨유지수단(54)을 포함하고,상기 레벨유지수단(54)은,상기 배출관(51)의 외주면과 상기 커플러(53)의 내주면을 따라 배치되되 상기 배출관(51)의 외주면과 상기 커플러(53)의 내주면에 교호(交互)로 맞닿도록 배치되는 지지부(541)와,한 쌍이 상호 이격된 위치에 배치되며 각각의 일단이 상기 지지부(541)에 결합되며 상호간의 간격을 조절함에 따라 상기 지지부(541)의 곡률을 변화시켜 지지부의 탄성력을 조절하는 탄성조절편(542)과,상기 한 쌍의 탄성조절편(542) 간격을 조절하기 위한 것으로, 상기 한 쌍의 탄성조절편(542)에 각각 형성된 결합공(543)과,상기 결합공(543)에 맞물리게 결합되어 회전 방향에 따라 한 쌍의 탄성조절편(542)의 간격을 조절하는 간격조절볼트(544)와,상기 한 쌍의 결합공(543) 중 어느 하나에 배치되어 상기 간격조절볼트(544)가 맞물리는 고정너트(545)를 포함하고,상기 지지부(541)는,일부가 개구된 C 형태로 이루어지고 연속적인 웨이브 형태로 이루어지는 것을 특징으로 하는 바지선을 활용한 도서(島嶼)지역용 경작용수 공급시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

811/1150 Row 811: application_number: 1020190140830, combined_string: invention_title: 온실 작물 최적생육시스템 abstract: 본 발명은 온실 작물 최적생육시스템에 관한 것으로, 더욱 상세하게는 온실 내외부의 환경정보, 온실의 환경을 조절하는 온실환경조절장치의 작동정보와 이에 따른 생육결과를 이용하여 머신러닝 방식에 의해 최적의 생육조건을 도출하고, 이에 따른 온실환경조절장치의 작동이 이루어지도록 함으로써, 온실 작물의 생산효율을 극대화할 수 있도록 하는 온실 작물 최적생육시스템에 관한 것이다. claims: 작물이 재배되는 온실 내의 환경정보를 측정하는 온실환경측정장치와, 온실 내의 환경을 인위적으로 조절하는 온실환경조절장치와, 온실 내 작물의 생육조건에 맞도록 온실환경조절장치의 작동을 조절하는 관리서버를 포함하고, 상기 관리서버는, 일정 기간 동안 상기 온실환경측정장치로부터 측정되는 온실 내 환경정보, 온실 외부의 환경정보 및 온실환경조절장치의 작동정보를 수집하여 작물의 생육결과와의 상관관계를 분석하고 분석된 상관관계에 따라 생육조건을 설정하여 온실환경조절장치의 작동을 조절하도록 하는 것을 특징으로 하는 온실 작물 최적생육시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

812/1150 Row 812: application_number: 1020210040846, combined_string: invention_title: 간헐적 양액공급방식을 이용한 수경재배장치 abstract: 본 발명은 양액을 이용한 수경재배장치에 관한 것으로, 양액을 간헐적으로 공급되도록 하여 식물의 뿌리가 주기적으로 소정의 시간동안에 공기 중에 노출되도록 하되, 양액의 소비를 줄일 수 있도록 하고, 다양한 식물을 재배할 수 있도록 하고, 양액 공급에 따른 에너지 소비를 최소화 하는 등의 장점을 가질 수 있도록 이루어진 간헐적 양액공급방식을 이용한 수경재배장치이다.이러한, 본 발명의 간헐적 양액공급방식을 이용한 수경재배장치는 양액을 간헐적으로 공급하도록 이루어진 간헐식 수경재배장치에 있어서, 수경재배용 재배베드의 상부에 설치되도록 양측에 재배베드의 상부단과 결합되는 결합부가 형성되고, 재배식물에 따라 베드밑면의 높이를 조절할 수 있는 높이조절형 재배베드덮개와; 상기 수경재배용 재배베드에 공급되는 양액이 설정된 고수위에 도달시 하측에 위치한 다른 수경재배용 재배베드로 설정된 저수위까지 배출하도록 이루어진 양액배출장치를 포함하여, 가장 상부에 위치하는 수경재배용 재배베드에 양액을 간헐적으로 공급하여 하측에 위치하는 다른 수경재배용 재배베드에 순차적으로 양액이 간헐적으로 공급되도록 이루어진 것이다. claims: 양액을 간헐적으로 공급하도록 이루어진 간헐식 수경재배장치에 있어서,소정의 간격을 가지고 다단의 형태로 배치되는 가터(Gutter)형의 수경재배용 재배베드(20, 20')와; 상기 수경재배용 재배베드(20, 20')의 상부에 설치되며 베드밑면(31)의 위치를 조절할 수 있도록 이루어진 높이조절형 재배베드덮개(30)와; 상기 높이조절형 재배베드덮개(30)의 베드밑면(31)에 형성된 다수의 홀더 공(33)에 삽입되어 설치되는 다수의 재배홀더(50)와; 상기 수경재배용 재배베드(20)에 공급되는 양액이 설정된 고수위에 도달시 하측에 위치한 다른 수경재배용 재배베드(20')로 설정된 저수위까지 배출하도록 이루어진 양액배출장치(60)와; 양액탱크(80)에 저장된 양액을 가장 상부에 위치하는 수경재배용 재배베드(20)에 공급하는 양액공급장치(70)와; 상기 양액공급장치(70)의 제어를 포함하는 제어장치(100)를 포함하여,상기 양액공급장치(70)로 가장 상부에 위치하는 수경재배용 재배베드(20)에 양액을 간헐적으로 공급하여 하측에 위치하는 다른 수경재배용 재배베드(20')에 순차적으로 양액이 간헐적으로 공급되도록 이루어지는 한편,상기 높이조절형 재배베드덮개(30)는 단면이 '┎┑' 형태로 형성되고 양측부분에 수경재배용 재배베드(20, 20')의 상부단(22)과 결합되는 결합부(32)가 형성되고, 상기 결합부(32)는 상측과 하측에는 각각 대응되게 상부단(22)이 삽입되는 상측 결합홈(32-1)과 하측 결합홈(32-2)로 형성되어 있어 상기 상부단(22)에 결합되는 상측 결합홈(32-1)과 하측 결합홈(32-2)에 따라 베드밑면(31)의 위치가 조절됨을 특징으로 하는 간헐적 양액공급방식을 이용한 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

813/1150 Row 813: application_number: 1020210040849, combined_string: invention_title: 간헐적 수경재배장치 및 이를 구비한 간헐적 양액공급방식을 이용한 수경재배시스템 abstract: 본 발명은 양액을 이용한 수경재배장치에 관한 것으로, 양액을 간헐적으로 공급되도록 하여 식물의 뿌리가 주기적으로 소정의 시간동안에 공기 중에 노출되도록 하되, 양액의 소비를 줄일 수 있도록 하고, 다양한 식물을 재배할 수 있도록 하고, 양액 공급에 따른 에너지 소비를 최소화 하는 등의 장점을 가질 수 있도록 이루어진 간헐적 양액공급방식을 이용한 수경재배장치이다.이러한, 본 발명의 간헐적 양액공급방식을 이용한 수경재배장치는 양액을 간헐적으로 공급하도록 이루어진 간헐식 수경재배장치에 있어서, 수경재배용 재배베드의 상부에 설치되도록 양측에 재배베드의 상부단과 결합되는 결합부가 형성되고, 재배식물에 따라 베드밑면의 높이를 조절할 수 있는 높이조절형 재배베드덮개와; 상기 수경재배용 재배베드에 공급되는 양액이 설정된 고수위에 도달시 하측에 위치한 다른 수경재배용 재배베드로 설정된 저수위까지 배출하도록 이루어진 양액배출장치를 포함하여, 가장 상부에 위치하는 수경재배용 재배베드에 양액을 간헐적으로 공급하여 하측에 위치하는 다른 수경재배용 재배베드에 순차적으로 양액이 간헐적으로 공급되도록 이루어진 것이다. claims: 양액을 이용하여 식물을 재배하는 수경재배장치에 있어서,가터(Gutter)형의 수경재배용 재배베드(20)와; 상기 수경재배용 재배베드(20)의 상측에 설치되되 베드밑면(31)의 위치가 변경될 수 있도록 이루어진 높이조절형 재배베드덮개(30)와; 상기 높이조절형 재배베드덮개(30)에 형성된 재배판용 홀(33)에 설치되는 다양한 형태의 홀더 공(41, 41', 41)을 제공하도록 하는 재배판(40, 40', 40)과; 상기 재배판(40, 40', 40)에 형성된 홀더 공(41, 41', 41)에 설치되는 재배홀더(50, 50', 50)와; 상기 수경재배용 재배베드(20)에 공급되는 양액이 설정된 고수위에 도달시 하측에 위치한 다른 수경재배용 재배베드로 설정된 저수위까지 배출하도록 이루어진 양액배출장치(60)를 포함하고,상기 높이조절형 재배베드덮개(30)는, 단면이 '┎┑' 형태로 형성되고 양측부분에 상기 수경재배용 재배베드(20)의 상부단(22)과 결합되는 결합부(32)가 형성되고, 상기 결합부(32)는 상측과 하측에는 각각 대응되게 상부단(22)이 삽입되는 상측 결합홈(32-1)과 하측 결합홈(32-2)로 형성되어 있어 상기 상부단(22)에 결합되는 상측 결합홈(32-1)과 하측 결합홈(32-2)에 따라 베드밑면(31)의 위치가 조절되도록 하며,상기 수경재배용 재배베드(20)를 다단으로 설치하여 가장 상부에 위치하는 수경재배용 재배베드(20)에 양액을 고수위까지 공급시 하측에 위치하는 다른 수경재배용 재배베드에 순차적으로 양액이 공급될 수 있도록 함을 특징으로 하는 간헐적 수경재배장치.제1항 또는 제2항으로 이루어진 간헐적 수경재배장치와,상기 간헐적 수경재배장치가 다단으로 설치할 수 있는 재배베드용 프레임(10)과;양액탱크(80)에 저장된 양액을 가장 상부에 위치하는 간헐적 수경재배장치에 공급하는 양액공급장치(70)와;상기 양액배출장치(60)와 양액공급장치(70)를 제어할 수 있는 제어장치(100)를 포함하여,상기 양액공급장치(70)를 이용하여 가장 상부에 위치하는 간헐적 수경재배장치에 양액을 간헐적으로 공급하고, 공급된 양액이 하측에 위치하는 다른 간헐적 수경재배장치에 순차적으로 이동하여 양액이 간헐적으로 공급되도록 이루어짐을 특징으로 하는 간헐적 수경재배장치를 구비한 간헐적 양액공급방식을 이용한 수경재배시스템., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

814/1150 Row 814: application_number: 2020210000600, combined_string: invention_title: 자동급수, 회전식 공중 식물재배장치 abstract: 자동급수, 회전형 공중식물재배장치에 관한 것으로 두개의 기둥에 톱니바퀴를 설치하고 이에 연결된 체인에 다수의 지지봉을 달고 이에 재배상자를 매달아서 회전재배하며 하단에 물 및 양액을 공급하는 통을 설치하여서 회전시 양액통을 통과하여서 양액을 의 낭비를 방지하고 필요한 온도,이산화탄소 농도,생육에 유익한 연풍효과등을 유발하게 하며 좁은 면적에 많은 재배를 하게하는 장치이다. claims: 자동 급수,회전형 공중 식물재배장치로서 재배용기는 공중에 메달려 모터의 구동으로 체인이 움직이고 이 체인을 연결한 봉에 재배상자가 매달려 재배하는 것과 회전 시 급수 통을 통과하여 양액이 자동으로 공급되는 것., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

815/1150 Row 815: application_number: 1020200162170, combined_string: invention_title: 식물의 생장 촉진 기능의 스마트팜 양액 제어 시스템 abstract: 본 발명은 식물의 생장 촉진 기능을 구비한 스마트팜 양액 제어 시스템에 관한 것이다. 보다 구체적으로는, 양액을 수용하여 식물을 재배하는 재배수조(20); 원수를 공급받아 저장하는 원수조(12); 상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14); 상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15); 상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);를 포함하고, 상기 재배수조(20)는, 상부에 위치하여 식물 생장을 촉진하는 파장대의 빛을 발산하는 LED 조명(21)와, 하부에 위치하여 원적외선을 방출하는 바이오 블록(22)을 더 포함할 수 있다. claims: 양액을 수용하여 식물을 재배하는 재배수조(20);원수를 공급받아 저장하는 원수조(12);상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14);상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15);상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);를 포함하고상기 재배수조(20)는,상부에 위치하여 식물 생장을 촉진하는 파장대의 빛을 발산하는 LED 조명(21)와, 하부에 위치하여 원적외선을 방출하는 바이오 블록(22)을 더 포함하는 것을 특징으로 하는 식물의 생장 촉진 기능의 스마트팜 양액 제어 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

816/1150 Row 816: application_number: 1020200162171, combined_string: invention_title: 생육 주기 확인을 통한 스마트팜 양액 제어 시스템 abstract: 본 발명은 생육 주기 확인을 통한 스마트팜 양액 제어 시스템에 관한 것이다. 보다 구체적으로는, 양액을 수용하여 식물을 재배하는 재배수조(20); 원수를 공급받아 저장하는 원수조(12); 상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14); 상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15); 상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16); 상기 재배수조(20)내의 식물의 영상을 획득하는 영상 촬영 장치(23); 및 상기 획득된 영상을 기반으로 상기 LED 조명(21)을 제어하는 조명 제어부(33)를 포함한다. claims: 양액을 수용하여 식물을 재배하는 재배수조(20);원수를 공급받아 저장하는 원수조(12);상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14);상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15);상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);상기 재배수조(20)내의 식물의 영상을 획득하는 영상 촬영 장치(23); 및상기 획득된 영상을 기반으로 상기 LED 조명(21)을 제어하는 조명 제어부(33)를 포함하는 생육 주기 확인을 통한 스마트팜 양액 제어 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

817/1150 Row 817: application_number: 1020200162172, combined_string: invention_title: 스마트팜 양액 공급 장치 abstract: 본 발명은 스마트팜 양액 공급 장치에 관한 것이다. 보다 구체적으로는, 양액을 수용하여 식물을 재배하는 재배수조(20); 원수를 공급받아 저장하는 원수조(12); 상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14); 상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15); 상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16); 상기 재배수조(20)내의 식물의 영상을 획득하는 영상 촬영 장치(23); 및 상기 획득된 영상을 기반으로 상기 LED 조명(21)을 제어하는 조명 제어부(33)를 포함한다. claims: 양액을 수용하여 식물을 재배하는 재배수조(20);원수를 공급받아 저장하는 원수조(12);상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14);상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15);상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);를 포함하는 스마트팜 양액 공급 장치, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

818/1150 Row 818: application_number: 1020200162173, combined_string: invention_title: 생육 주기별 양액 농도 제어가 가능한 스마트팜 제어 시스템 abstract: 본 발명은 식물의 생장 촉진 기능을 구비한 생육 주기별 양액 농도 제어가 가능한 스마트팜 제어 시스템에 관한 것이다. 보다 구체적으로는, 양액을 수용하여 식물을 재배하는 재배수조(20); 원수를 공급받아 저장하는 원수조(12); 상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14); 상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15); 상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16); 상기 재배수조(20)내의 식물의 영상을 획득하는 영상 촬영 장치(23); 및 상기 획득된 영상을 기반으로 상기 LED 조명(21)을 제어하는 조명 제어부(33)를 포함한다. claims: 상부에 위치되는 LED 조명(21)을 통해 식물 생장을 촉진하는 파장대의 빛을 발산하며, 식물 재배를 위한 양액을 수용하는 재배수조(20);원수를 공급받아 저장하는 원수조(12);상기 원수조와 연결되어 양액의 농도를 조절하면서 저장하는 양액조(14);상기 양액조(14)에 식물 영양제를 공급하는 영양제 공급부(17);상기 양액조(14)에서 나오는 양액을 살균하는 저온 플라즈마 발생기(15);상기 양액을 마이크로 버블화시켜 상기 재배수조(20)에 공급하는 마이크로버블 발생기(16);상기 원수조(12)에서 상기 양액조(14)로 공급되는 원수의 양을 조절하는 원수 공급 펌프 밸브(13); 상기 원수 공급 펌프 밸브(13)를 제어하는 밸브 제어기(31); 및 식물의 생육 주기에 따른 양액의 농도, 필요 영양제의 양, 생육 주기별 식물 사진을 저장하고, 저장 정보에 따라 상기 밸브 제어기(31) 및 상기 영양제 공급부(17)를 수시 제어하는 서버(32);를 포함하는 생육 주기별 양액 농도 제어가 가능한 스마트팜 제어 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

819/1150 Row 819: application_number: 1020200110421, combined_string: invention_title: 농약 정보 알리미 시스템 및 그 방법 abstract: 본 발명은 농약허용물질목록관리제도(Positive List System, PLS)를 대비하여 적용대상 약제정보 및 방제정보, 필수표시사항 및 농약과 관련한 종합정보 제공용 스마트시스템을 개발하여 고령 농업인들이 보다 쉽게 접근이 용이한 정보를 전달하고, 보다 안전하고 스마트한 국내 농업환경을 구축할 수 있도록 구현한 농약 정보 알리미 시스템 및 방법에 관한 것으로, 농약 판매 매장에 배치되며, 농약정보, 병해충방제정보, 농약혼용정보 및 농약 종류별 가격정보 중 적어도 하나 이상의 정보검색의 요청을 사용자로부터 입력받아 정보검색을 요청하며, 정보검색 요청에 대응하여 수신되는 검색결과를 표시하며, 사용자로부터 검색결과에 대한 프린트 요청이 있는 경우 해당 검색결과를 프린트하여 사용자에게 제공하는 정보 제공 키오스크 단말기; 및 상기 정보 제공 키오스크 단말기로부터 수신되는 정보검색 요청에 대응하는 정보를 데이터베이스에서 검색하며, 검색된 검색결과를 상기 정보 제공 키오스크 단말기로 전송하는 농약 정보 제공 서버;를 포함한다. claims: 농약허용물질목록관리제도(Positive List System, PLS)를 대비하여 적용대상 약제정보 및 방제정보, 필수표시사항 및 농약과 관련한 종합 정보를 제공하기 위한 농약 정보 알리미 시스템에 있어서,별도의 데이터베이스와 백업서버에 연결되는 농약 정보 제공 서버;농약 판매 매장에 배치되며 농약정보, 병해충방제정보, 농약혼용정보 및 농약 종류별 가격정보 중 적어도 하나 이상의 정보검색의 요청을 사용자로부터 입력받아 정보검색을 요청하며, 정보검색 요청에 대응하여 수신되는 검색결과를 표시하고, 사용자로부터 검색결과에 대한 프린트 요청이 있는 경우 해당 검색결과를 프린트하여 사용자에게 제공하는 정보 제공 키오스크 단말기;를 포함하되, 상기 정보 제공 키오스크 단말기는 키오스크 본체, 상기 키오스크 본체의 전단에 설치되며 농약정보 검색창, 병해충방제정보 검색창, 농약혼용정보 검색창 및 농약 종류별 가격정보를 표시하며,상기 농약 정보 제공 서버로부터 수신되는 검색결과를 표시하는 터치 스크린, 상기 터치 스크린은 화면 상단에 농약 제품 광고 및 공익 광고 영역을 표시하고, 화면 중단에 농약정보 검색, 병충해 방제정보 검색 및 농약 혼용정보 검색 메뉴 영역을 표시하고,상시적 농약 제품의 가격 정보 영역의 하단에 농약 종류별 가격정보 검색 및 가나다순 초성검색 영역을 더 표시하며,상기 농약정보 검색은 사용자로부터 검색창을 통해 농약 제품의 명칭을 직접 입력받거나 상시적 농약 제품의 가격 정보 영역에 나열된 농약 제품 리스트 중에서 선택 입력받아 상기 농약 정보 제공 서버로 해당 농약 제품의 정보 검색을 요청한 뒤, 상기 농약 정보 제공 서버로부터 수신되는 농약정보 상세 내용 구성을 표시하고,상기 농약정보 상세 내용 구성은 적용대상 및 사용량, 해당제품 혼용정보 및 필수표시사항을 포함하며, 필수표시사항은 주요 특성, 주의사항, 경고문구, 해독 및 응급처치요령 및 취급제한기준을 포함하며,상기 농약정보 검색, 농약 혼용정보 검색, 병충해 방제정보 검색 메뉴 영역은 작물명과 해충명의 입력창 하단에 국가농작물 병해충관리시스템에서 제공하는 월별 농작물 병해충 발생정보를 표시하기 위한 이달의 병충해정보를 표시하고,상기 농약 정보 제공 서버는 각 매장에 설치되어 있는 상기 정보 제공 키오스크 단말기의 관리자에게 해당 매장에 비치되어 있는 농약의 가격 및 종류에 따라 상기 정보 제공 키오스크 단말기에 저장되어 있는 농약 가격 데이터 및 농약판매리스트의 변경을 위한 권한을 부여하며, 상기 키오스크 본체의 전단에 설치되어 사용자가 소지하고 있는 농약의 식별코드를 스캔하는 바코드 리더기를 포함하는, 농약 정보 알리미 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

820/1150 Row 820: application_number: 1020200108392, combined_string: invention_title: 축산분뇨를 이용한 바이오 퇴비 제조방법 abstract: 본 발명은 축산분뇨 중 분은 바이오 퇴비로 자원화하고, 뇨는 마이크로 버블로 정화처리하여 가축 샤워 및 축사 청소에 이용할 수 있도록 한 축산분뇨를 이용한 바이오 퇴비 제조방법에 관한 것으로, 축사(1)로부터 생산되는 축산분뇨를 저장하는 분뇨저장조(2)와, 분뇨저장조(2)의 축산분뇨를 교반 및 폭기처리하는 폭기조(3)와, 폭기된 축산분뇨를 고상의 분(糞)과 액상의 뇨(尿)로 분리하는 고액분리기(4)와, 분리된 고상의 분(糞)을 교반 및 건조시키는 제1 교반건조로(5)와, 1차 교반 건조된 고상의 분(糞)을 재차 건조시키는 제2 교반건조로(6)를 포함한다. 상기 건조로(6)에 의해 건조된 바이오 퇴비를 압출하는 펠릿부(7)를 더 포함한다. 상기 고액분리기(4)에 의해 분리된 뇨를 고도로 정화처리하는 마이크로 버블장치(8)와, 정화처리된 정화수를 저장하는 정화수 저장조(9)를 포함한다. 상기 축사(1)에 설치되고 가축을 사워시키고 축사(1) 바닥을 청소하는 정화수 분사노즐(10)을 더 포함한다. 상기 분뇨저장조(2)에는 바이오 에너지워터 또는 바이오 에너지워터와 백토분말이 혼합되어 바이오 퇴비를 얻을 수 있도록 구성된다. 상기 축산분뇨와 바이오 에너지워터의 혼합비는 85~95:15~5 중량부 일수 있다. 상기 바이오 에너지워터가 혼합된 축산분뇨에 1~5중량부의 백토분말이 더 혼합될 수 있다. claims: a) 축사로부터 생산되는 축산분뇨를 분뇨저장조에 저장하는 단계;b) 분뇨저장조에 저장된 축산분뇨와 에너지워터를 폭기조에서 85~95:15~5 중량부로 혼합한 다음 교반 및 폭기 처리하는 단계;c) 폭기된 축산분뇨 중에서 고액분리기로 고상의 분(糞)과 액상의 뇨(尿)로 분리하는 단계;d) 분리된 액상의 뇨(尿)를 마이크로 버블장치로 정화처리하는 단계;e) 정화처리된 뇨(尿) 정화수를 가축의 식수, 샤워수, 바닥청소수로 활용할 수 있도록 정화수 저장조에 저장하는 단계;f) 축사에 설치되는 복수의 분사노즐을 이용하여 정화수 저장조의 뇨(尿) 정화수를 가축에게 샤워시켜 몸에 묻은 분뇨와 이물질을 씻어주고 축사 바닥을 물청소시켜 축사의 악취를 감소시키는 단계; 를 포함하고,상기 b) 단계에서, 바이오 에너지워터가 혼합된 축산분뇨에 1~5중량부의 백토분말을 더 혼합한 다음 교반 및 폭기시켜 축산분뇨의 악취를 탈취하고, 상기 c) 단계에서, 고액분리기로 분리된 고상의 분(糞)을 60~80℃의 온도로 10~40시간 1차 교반 및 건조시켜 함수율이 40~60%의 반건조 바이오 퇴비를 얻고, 1차 교반 및 건조된 분(糞)을 60~80℃의 온도로 10~40시간 2차 교반 및 건조시켜 함수율이 8~15%인 바이오 퇴비를 얻도록 함을 특징으로 하는 축산분뇨를 이용한 바이오 퇴비 제조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

821/1150 Row 821: application_number: 1020200086537, combined_string: invention_title: 식물공장 양액관리 제어시스템 abstract: 본발명은 식물공장 양액관리 제어시스템에 관한 것으로, 양액을 공급하는 공급배관(110)과 폐양액을 회수하는 회수배관(120), 그리고 물을 저장하는 원수탱크(130), 물과 폐양액을 혼합하는 혼합탱크(140), 배수하는 배수탱크(150) 및 밸브(160), 그리고 양액탱크(180)에 설치되어 혼합탱크로부터 공급되는 물과 폐양액 혼합액 및 양액을 공급하는 펌프(170)를 포함하여 구비되는 양액공급수단(100)과;작업자가 재배환경 조건을 입력하는 입력수단(200)과;센서에 의해 입력된 신호에 의해 재배환경을 제어하는 제어기(300)와;디스플레이 출력수단(400)을;포함하는 것으로,본발명은 주위 환경변화에 따라 적정한 양의 양액을 자동으로공급할 수 있도록 제어하고, 또한 외부 기상조건에 영향을 받지 않고 작물을 연중으로 생산할 수 있어 생산성 향상과 인건비가 절감되는 현저한 효과가 있다. claims: 양액을 공급하는 공급배관(110)과 폐양액을 회수하는 회수배관(120), 그리고 물을 저장하는 원수탱크(130), 물과 폐양액을 혼합하는 혼합탱크(140), 배수하는 배수탱크(150) 및 밸브(160), 그리고 양액탱크(180)에 설치되어 혼합탱크로부터 공급되는 물과 폐양액 혼합액 및 양액을 공급하는 펌프(170)를 포함하여 구비되는 양액공급수단(100)과;작업자가 재배환경 조건을 입력하는 입력수단(200)과;센서에 의해 입력된 신호에 의해 재배환경을 제어하는 제어기(300)와;디스플레이 출력수단(400)을;포함하는 식물공장 양액관리 제어시스템에 있어서,상기 입력수단(200)의 입력내용에는 초기화면(221), 관수설정(222), 엽면관수설정(223), 간격/시간제어(224), 엘이디제어설정(225), 환풍기설정(226), 유동팬설정(227), 냉난방기설정(228), 가습기설정(229), 수동작동(230), 시간설정(231), 관수보고(232), 기타설정(233)으로 표시되는 화면들에 제어내용을 입력하며,상기 기타설정(233)에 대한 화면의 양액경보설정은 터치를 반복하여 ‘사용함’, ‘사용 안함’으로 설정할 수 있고, EC상한값 설정은 관수가 설정한 EC상한값 이상이면 경보가 발생되며, pH하한값 설정은 관수가 pH하한값 이하이면 경보가 발생되고, 경보발생시간(초)은 경보음 발생시간을 설정하며, 운전정지시간(초)은 경보음 발생 후 운전정지 시간이 되면 시스템이 정지하게 되고, 양액선택은 질산 또는 알카리를 선택하는 것이며,상기 센서들에 의한 측정값이 설정치 이하일 경우인 양액통 내부의 양액품질이 저하한 경우 혼합탱크의 폐양액에 대한 물 비율을 높혀 양액통 내부의 양액품질을 향상하며, 그럼에도 불구하고 양액통 내부의 양액품질이 정상수치로 돌아오지 않으면, 제어기는 UV살균기 성능을 최대로 높이거나 예비로 설치되는 예비 UV살균기도 같이 동작시키며, 동시에 전자밸브를 개도를 좁게 작동하여 시간당 폐양액공급을 줄이게 되며, 엽채베드들에서 배출되는 폐양액의 센서감지에 의한 양액품질을 각각 측정하여 제어기에서는 종합적인 폐양액의 품질을 관리함으로써 양액탱크내부의 양액품질이 나쁠 경우 여러 개 엽체베드들중 가장 나쁜 것의 자동밸브를 닫아서 공급을 막게되어 양액탱크 내부의 품질을 복원 내지 향상시키는 것을 특징으로 하는 식물공장 양액관리 제어시스템, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

822/1150 Row 822: application_number: 1020200076127, combined_string: invention_title: 효소활성수를 이용한 가축분뇨 소멸화 방법 및 이를 이용한 퇴비 제조방법 abstract: 본 발명은 제조공정이 간단하고 악취발생이 없으며, 단시간에 처리가 가능한 효소활성수를 이용한 가축분뇨 소멸화 방법 및 이를 사용한 퇴비 제조방법에 관한 발명이다. claims: 가축 분뇨를 처리하는 방법에 있어서,상기 가축 분뇨는 축산 농가에서 배출되는 가축의 배설물인 축산분뇨이며, 상기 축산분뇨와 부형재를 교반하되, A) 상기 부형재는 왕겨 및 효소활성수를 혼합하여 제조하는 단계; 및 B) 상기 축산분뇨 및 완성부형재를 배합하는 단계;를 통해 처리하되,상기 효소활성수는 pH7.5 및 40 내지 55℃에서 무가당발효를 통해 숙성시킨 것으로서, 숙성 1단계) 밀감, 포도, 사과, 바나나, 감, 파인애플, 들깨, 현미, 흑미, 보리, 쌀겨, 연근, 당근, 우엉, 야생감자, 고구마, 산마, 양배추, 브로컬리, 콜리플라워, 양상치, 시금치, 자소, 파슬리, 마늘, 양파를 완전히 건조시킨 후 동일한 중량부로 분쇄하여 항아리에 함께 담아 40 내지 55℃에서 30일~40일 동안 숙성시키는 단계;숙성 2단계) 이후 30일~40일 동안 재차 숙성시키되, 10회 공기를 주입하여 폭기시킨 후 액상과 고형물을 분리하여 각각 밀폐된 통에서 보관하되, 액상은 10-11일 동안 5~7회 공기를 주입하여 폭기하고, 고형물은 10-11동안 그대로 보관하여 숙성시키는 단계; 및숙성 3단계) 상기 숙성시킨 고형물로부터 액상을 재차분리하여 상기 숙성 2단계)의 액상과 함께 밀폐된 통에 보관하되, 10-11동안 공기를 주입하여 폭기하는 숙성시키는 단계; 통해 제조되고, 상기 A) 단계는a-1) 상기 왕겨 및 효소활성수를 1: 0.1~0.2의 중량부로 교반기에 투입 및 교반하되, 상기 왕겨는 가축분뇨 처리를 위한 바닥재로부터 분을 분리한 후 수거된 폐왕겨를 재사용하는 것인 조기부형재 형성단계;a-2) 상기 조기부형재에 물을 투입하여, 수분함유량을 50 이상 60% 미만으로 조절하는 수분조절단계;a-3) 상기 수분조절 후 조기부형재의 온도가 70℃ 이상으로 가온될 때까지 교반하는 가온교반단계;a-4) 상기 가온교반단계에서 발생하는 발효열 및 수증기를 배출시켜 건조하고, 산소를 공급하는 공기순환단계; 및a-5) 상기 a-2) 내지 a-5)를 수차례 반복하되, 상기 조기부형재의 온도가 60℃ 미만 및 수분함유량 30% 미만으로 24시간 이상 유지되는 경우 제조되는 완성부형재 제조단계를 포함하는 것을 특징으로 하며, 상기 B) 단계는, b-1) 상기 축산분뇨는 분과 뇨가 혼합된 축산분뇨로서, 상기 축산분뇨 및 완성부형재를 1: 5~6의 중량부로 배합기에 투입하여 1~2시간 배합하는 분산배합단계;b-2) 상기 배합시 전체 수분함유량을 50 이상 60% 미만으로 조절하고, 30~35분 주기로 24시간 동안 배합과 휴식을 반복하여 축산분뇨를 단기간에 분해하는 24시간 분뇨분해단계; 및b-3) 상기 분뇨분해단계에서 발생하는 발효열 및 수증기를 배출시켜 건조시키고, 산소를 공급하는 공기 순환단계를 통하여 축산분뇨를 무기물 및 물로 분해시키고, 유기물 및 물을 증발시키는 축산분뇨 소멸단계를 포함하는 것을 특징으로 하는 가축분뇨 소멸화 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

823/1150 Row 823: application_number: 1020200063983, combined_string: invention_title: 투명 수조를 포함하는 작물 재배 장치 abstract: 투명 수조를 포함하는 작물 재배 장치가 개시된다. 개시된 투명 수조를 포함하는 작물 재배 장치는, 어류 서식을 위한 수조; 및 상기 수조 아래에 배치되며, 상기 수조로부터 각각 유입되는 물을 배양액으로 하여 작물을 재배하는 복수의 재배모듈;을 포함하되, 상기 복수의 재배모듈을 거친 물은 상기 수조로 재유입되어 어류 서식에 이용될 수 있다. claims: 어류 서식을 위한 수조; 및상기 수조 아래에 배치되며, 상기 수조로부터 각각 유입되는 물을 배양액으로 하여 작물을 재배하는 복수의 재배모듈;을 포함하되, 상기 복수의 재배모듈을 거친 물은 상기 수조로 재유입되어 어류 서식에 이용되고,상기 복수의 재배모듈은, 버티컬파밍 방식의 재배모듈, 에어로포닉 방식의 재배모듈, 포그포닉 방식의 재배모듈 및 하이드로포닉 방식의 재배모듈 중 2 이상을 포함하되,상기 복수의 재배모듈은,상기 수조 바로 아래에 나란히 배치되는 버티컬파밍 방식의 재배모듈과 에어로포닉 방식의 재배모듈을 포함하는 제1 재배모듈;상기 제1 재배모듈 바로 아래에 배치되는 포그포닉 방식의 제2 재배모듈;상기 제2 재배모듈 바로 아래에 배치되는 하이드로포닉 방식의 제3 재배모듈을 포함하고,상기 수조와 상기 제1 재배모듈을 연결하여 상기 수조로부터의 물을 상기 제1 재배모듈로 이송하는 제1 유출라인; 상기 수조와 상기 제2 재배모듈을 연결하여 상기 수조로부터의 물을 상기 제2 재배모듈로 이송하는 제2 유출라인;상기 수조와 상기 제3 재배모듈을 연결하여 상기 수조로부터의 물을 상기 제3 재배모듈로 이송하는 이송하는 제3 유출라인; 및 상기 제1 내지 제3 재배모듈들과 상기 수조를 연결하여 상기 제1 내지 제3 재배모듈로부터의 물을 상기 수조로 이송하는 순환라인;을 더 포함하고,상기 제3 재배모듈 바로 아래에 배치되는 순환부;를 더 포함하되, 상기 제1 유출라인은 길이 방향을 따라 일정 간격을 두고 복수의 홈이 형성되고, 상기 홈에 각각 작물이 거치되며, 상기 제1 유출라인 내에 배양액을 머금을 수 있는 부재가 구비되고,상기 순환라인은, 상기 버티컬파밍 방식의 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제1 순환라인;상기 에어로포닉 방식의 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제2 순환라인;상기 제2 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제3 순환라인;상기 제3 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제4 순환라인; 및상기 순환부와 상기 수조를 연결하여 이들간 물을 이송하는 제5 순환라인;을 포함하고,상기 순환부는, 상기 복수의 재배모듈을 거친 물을 상기 수조로 유입시키는 펌프;를 더 포함하며,상기 펌프는 상기 순환라인상에 배치되고,외부로부터 상기 순환부로 물을 유입받는 유입라인;을 더 포함하되,상기 펌프는 상기 유입라인으로부터 유입된 물을 상기 복수의 재배모듈을 거친 물과 함께 상기 수조로 유입시키며,상기 수조의 수위를 감지하는 감지부;를 더 포함하되, 상기 감지 결과 기준치를 미달하는 경우 상기 유입라인에 배치된 밸브의 개폐에 따라 상기 유입라인을 통해 외부로부터 물이 상기 순환부로 유입되는, 투명 수조를 포함하는 작물 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

824/1150 Row 824: application_number: 1020200063982, combined_string: invention_title: 복수의 재배모듈을 포함하는 작물 재배 장치 abstract: 복수의 재배모듈을 포함하는 작물 재배 장치가 개시된다. 개시된 작물 재배 장치는, 어류 서식을 위한 수조; 및 상기 수조 아래에 배치되며, 상기 수조로부터 유입되는 물을 배양액으로 하여 작물을 재배하는 복수의 재배모듈;을 포함하되, 상기 복수의 재배모듈을 거친 물은 상기 수조로 재유입되어 어류 서식에 이용될 수 있다. claims: 어류 서식을 위한 수조; 및상기 수조 아래에 배치되며, 상기 수조로부터 유입되는 물을 배양액으로 하여 작물을 재배하는 복수의 재배모듈;을 포함하되, 상기 복수의 재배모듈을 거친 물은 상기 수조로 재유입되어 어류 서식에 이용되고,상기 복수의 재배모듈은,상기 수조 바로 아래에 배치되는 제1 재배모듈, 상기 제1 재배모듈 바로 아래에 배치되는 제2 재배모듈, 및 상기 제2 재배모듈 바로 아래에 배치되는 제3 재배모듈을 포함하고,상기 제1 재배모듈은 버티컬파밍 방식의 재배모듈과 에어로포닉 방식의 재배모듈을 포함하되, 상기 버티컬파밍 방식의 재배모듈과 상기 에어로포닉 방식의 재배모듈은 서로 좌우측에 나란히 배치되고,상기 제2 재배모듈은 포그포닉 방식의 재배모듈이며,상기 제3 재배모듈은 하이드로포닉 방식의 재배모듈이고,상기 수조와, 상기 제1 재배모듈을 연결하여 이들간 물을 이송하는 제1 유출라인; 상기 제1 재배모듈과 상기 제2 재배모듈을 연결하여 이들간 물을 이송하는 제2 유출라인;상기 제2 재배모듈과 상기 제3 재배모듈을 연결하는 제3 유출라인;상기 제3 재배모듈과 상기 수조를 연결하여 이들간 물을 이송하는 순환라인;상기 제3 재배모듈 바로 아래에 배치되는 순환부;을 더 포함하고,상기 순환라인은, 상기 제3 재배모듈과 상기 순환부를 연결하여 이들간 물을 이송하는 제1 순환라인;상기 순환부와 상기 수조를 연결하여 이들간 물을 이송하는 제2 순환라인;을 포함하며,상기 순환부는, 상기 복수의 재배모듈을 거친 물을 상기 수조로 유입시키는 펌프;를 더 포함하고,상기 제2 유출라인은, 상기 물이 흐를 수 있는 배관으로 구성되고, 상기 제2 유출라인 중 상기 제1 재배모듈과 연결되는 상기 배관의 유입구는, 상기 제1 재배모듈 내 채워져야할 상기 물의 수위를 고려하여 상기 제1 재배모듈의 바닥으로부터 기설정된 높이에 설치되며,외부로부터 상기 순환부로 물을 유입받는 유입라인;을 더 포함하되,상기 펌프는 상기 유입라인으로부터 유입된 물을 상기 복수의 재배모듈을 거친 물과 함께 상기 수조로 유입시키고,상기 수조의 수위를 감지하는 감지부;를 더 포함하되, 상기 감지 결과 기준치를 미달하는 경우 상기 유입라인에 배치된 밸브의 개폐에 따라 상기 유입라인을 통해 외부로부터 상기 순환부로 물이 유입되는, 복수의 재배모듈을 포함하는 작물 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

825/1150 Row 825: application_number: 1020200055941, combined_string: invention_title: 노지용 스마트팜 제어 시스템 및 방법과 이를 위한 컴퓨터 프로그램 abstract: 노지(露地)용 스마트팜(smart farm) 제어 시스템은, 스마트팜의 미리 설정된 관리 지역에 위치한 하나 이상의 센서 노드 장치에 의해 수집된 센서 데이터를 상기 관리 지역에 상응하는 게이트웨이(gateway) 장치로부터 수신하도록 구성된 데이터베이스 서버; 상기 데이터베이스 서버에 저장된 상기 센서 데이터를 분석하여 분석 정보를 생성하도록 구성된 분석 서버; 및 상기 분석 정보를 상기 스마트팜의 사용자의 사용자 장치에서 확인할 수 있도록 상기 사용자 장치에 제공하도록 구성된 웹 서비스 서버를 포함할 수 있다. 상기 데이터베이스 서버는, 상기 게이트웨이 장치로부터 수신된 상기 센서 데이터를 구독(subscribe) 방식으로 선택적으로 수집하여 저장하도록 구성된 시계열 데이터베이스를 포함한다. 상기 시스템에 의하면, 스마트팜의 각 지역별로 구비된 게이트웨이 장치를 통해 지역별 관제를 실현할 수 있고, 구독 방식의 시계열 데이터베이스 관리를 통하여 효율적인 스마트팜 제어가 실현될 수 있고 서버의 부하를 줄일 수 있는 이점이 있다. claims: 스마트팜의 미리 설정된 관리 지역에 위치한 하나 이상의 센서 노드 장치;상기 하나 이상의 센서 노드 장치에 의해 수집된 센서 데이터를 상기 관리 지역에 상응하는 게이트웨이 장치로부터 수신하도록 구성된 데이터베이스 서버; 상기 데이터베이스 서버에 저장된 상기 센서 데이터를 분석하여 분석 정보를 생성하도록 구성된 분석 서버; 및 상기 스마트팜의 사용자의 사용자 장치로부터 상기 스마트팜의 관수 장치를 제어하기 위한 제어 데이터 및 작황에 관련된 사용자 입력을 수신하고, 상기 분석 정보를 상기 사용자 장치에서 확인할 수 있도록 상기 사용자 장치에 제공하도록 구성된 웹 서비스 서버를 포함하되, 상기 데이터베이스 서버는, 상기 게이트웨이 장치로부터 수신된 상기 센서 데이터를 구독 방식으로 선택적으로 수집하여 저장하도록 구성된 시계열 데이터베이스를 포함하고, 상기 하나 이상의 센서 노드 장치 각각은, 상기 센서 데이터를 획득하기 위한 하나 이상의 센서가 구비된 센서 모듈, 상기 게이트웨이 장치와의 통신을 수행하기 위한 통신 모듈, 및 저장 모듈을 수용하도록 구성된 몸체부를 포함하며, 상기 몸체부는 토양 내의 서로 상이한 깊이에 위치하는 복수 개의 층에 걸쳐 연장되도록 토양 내에 삽입되는 연장부를 포함하고, 상기 하나 이상의 센서는 상기 복수 개의 층에 관련된 상기 센서 데이터를 각각 독립적으로 측정하도록 더 구성되며,상기 센서 모듈은 가속도 센서를 포함하고, 상기 저장 모듈은 농작물의 생육 환경에 관련된 미리 설정된 조건에 대한 정보를 저장하도록 구성되며,상기 통신 모듈은, 상기 하나 이상의 센서에 의해 측정된 상기 센서 데이터가 상기 미리 설정된 조건을 벗어나는 경우, 상기 센서 데이터의 조건 이탈에 관련된 정보를 상기 데이터베이스 서버에 전송하도록 더 구성되고,상기 분석 서버는, 상기 가속도 센서에 의해 측정된 가속도의 크기와 방향으로부터 상기 하나 이상의 센서 노드 장치가 지면에 대해 이루는 각도인 기울기를 산출하고, 기울기가 미리 설정된 각도 이상인 센서 노드 장치가 있을 경우 상기 기울기가 미리 설정된 각도 이상인 센서 노드 장치로부터 수신된 상기 센서 데이터를 오류 데이터로 결정하며, 상기 센서 노드 장치의 기울기를 이용하여 상기 오류 데이터에서 상기 복수 개의 층에 관련된 상기 센서 데이터 각각에 상응하는 감지 깊이를 보정하도록 구성된 오류 탐지부; 및상기 센서 데이터, 상기 제어 데이터 및 상기 사용자 입력의 조합에 의해 정의되는 데이터 레코드들을 군집화함으로써, 농작물의 생육에 관련된 조건 및 생육 결과물에 대한 예측값을 포함하는 작물 모델링 데이터를 생성하되, 상기 오류 탐지부에 의해 상기 감지 깊이가 보정된 상기 센서 데이터를 이용하여 상기 작물 모델링 데이터를 생성하도록 구성된 모델링 생성부를 포함하고, 상기 웹 서비스 서버는, 상기 센서 데이터의 조건 이탈에 관련된 정보를 상기 스마트팜의 사용자에게 통지하도록 더 구성된 노지용 스마트팜 제어 시스템. 노지용 스마트팜 제어 방법으로서,노지용 스마트팜 제어 시스템의 데이터베이스 서버가, 스마트팜의 미리 설정된 관리 지역에 위치한 하나 이상의 센서 노드 장치에 의해 수집된 센서 데이터를 상기 관리 지역에 상응하는 게이트웨이 장치로부터 수신하는 단계; 상기 데이터베이스 서버가, 상기 게이트웨이 장치로부터 수신된 상기 센서 데이터를 구독 방식으로 선택적으로 수집하여 상기 데이터베이스 서버의 시계열 데이터베이스에 저장하는 단계; 상기 노지용 스마트팜 제어 시스템의 웹 서비스 서버가, 스마트팜의 사용자의 사용자 장치로부터 상기 스마트팜의 관수 장치를 제어하기 위한 제어 데이터 및 작황에 관련된 사용자 입력을 수신하는 단계;상기 노지용 스마트팜 제어 시스템의 분석 서버가, 상기 데이터베이스 서버에 저장된 상기 센서 데이터를 분석하여 상기 스마트팜의 사용자에게 제공되기 위한 분석 정보를 생성하는 단계; 및 상기 웹 서비스 서버가, 상기 분석 정보를 상기 사용자 장치에 제공하는 단계를 포함하되, 상기 하나 이상의 센서 노드 장치 각각은, 상기 센서 데이터를 획득하기 위한 하나 이상의 센서가 구비된 센서 모듈, 상기 게이트웨이 장치와의 통신을 수행하기 위한 통신 모듈, 및 저장 모듈을 수용하도록 구성된 몸체부를 포함하며, 상기 몸체부는 토양 내의 서로 상이한 깊이에 위치하는 복수 개의 층에 걸쳐 연장되도록 토양 내에 삽입되는 연장부를 포함하고, 상기 센서 데이터는, 상기 하나 이상의 센서에 의하여 상기 복수 개의 층에 대해 각각 독립적으로 측정된 센서 데이터들을 포함하며, 상기 센서 모듈은 가속도 센서를 포함하고, 상기 저장 모듈은 농작물의 생육 환경에 관련된 미리 설정된 조건에 대한 정보를 저장하도록 구성되며,상기 분석 정보를 생성하는 단계는, 상기 분석 서버가, 상기 가속도 센서에 의해 측정된 가속도의 크기와 방향으로부터 상기 하나 이상의 센서 노드 장치가 지면에 대해 이루는 각도인 기울기를 산출하는 단계;상기 분석 서버가, 기울기가 미리 설정된 각도 이상인 센서 노드 장치가 있을 경우 상기 기울기가 미리 설정된 각도 이상인 센서 노드 장치로부터 수신된 상기 센서 데이터를 오류 데이터로 결정하는 단계; 상기 분석 서버가, 상기 센서 노드 장치의 기울기를 이용하여 상기 오류 데이터에서 상기 복수 개의 층에 관련된 상기 센서 데이터 각각에 상응하는 감지 깊이를 보정하는 단계; 및상기 분석 서버가, 상기 센서 데이터, 상기 제어 데이터 및 상기 사용자 입력의 조합에 의해 정의되는 데이터 레코드들을 군집화함으로써, 농작물의 생육에 관련된 조건 및 생육 결과물에 대한 예측값을 포함하는 작물 모델링 데이터를 생성하는 단계를 포함하되, 상기 작물 모델링 데이터를 생성하는 단계는 상기 감지 깊이가 보정된 상기 센서 데이터를 이용하여 수행되며,상기 노지용 스마트팜 제어 방법은, 상기 하나 이상의 센서에 의해 측정된 상기 센서 데이터가 상기 미리 설정된 조건을 벗어나는 경우, 상기 노지용 스마트팜 제어 시스템이 상기 센서 노드 장치로부터 상기 센서 데이터의 조건 이탈에 관련된 정보를 수신하는 단계; 및 상기 노지용 스마트팜 제어 시스템이, 상기 센서 데이터의 조건 이탈에 관련된 정보를 상기 스마트팜의 사용자에게 통지하는 단계를 더 포함하는 노지용 스마트팜 제어 방법. 하드웨어와 결합되어 제5항 내지 제7항 중 어느 한 항에 따른 노지용 스마트팜 제어 방법을 실행하도록 컴퓨터로 판독 가능한 기록매체에 저장된 컴퓨터 프로그램., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

826/1150 Row 826: application_number: 1020200053600, combined_string: invention_title: 동식물 생태 순환형 아쿠아포닉스 시스템 abstract: 본 발명은 수생동물의 생육하는 수조의 물을 재배조에 순환 공급하여, 재배조의 식물이 수조의 물에 혼합된 유기물에서 영양을 섭취하여 수조의 물을 정확하게 하는 동식물 생태 순환형 아쿠아포닉스 시스템에 관한 것으로서, 보다 상세하게는 재배조를 수조의 상하에 다단으로 배치하여도 수조 물을 정량으로 연속 순화시키고, 재배조에서의 영양 섭취량을 최대한 늘리도록 각 재배조에 유로를 형성하고, 관상하기에 적합한 높이에 수조를 배치할 수 있고, 재배조를 인입 인출에 무관하게 순환 생태계를 연속적 및 안정적으로 유지하여, 협소한 공간에 많은 식물을 키울 수 있고, 가정용으로도 적합하며, 식생 관리도 편리하고, 수조의 물을 깨끗하게 유지할 수 있는 동식물 생태 순환형 아쿠아포닉스 시스템에 관한 것이다 claims: 복수 수납공간이 수직 방향으로 배열되어 있는 지지프레임(100); 복수 수납공간 중에 최상단 수납공간을 제외한 어느 하나의 수납공간에 수용되며, 물이 채워진 부분을 갖게 하여 수생동물의 생육 환경을 조성한 수조(200); 나머지 수납공간에 하나씩 수용되어 상하로 다단 배치되며, 바닥면보다는 상대적으로 높은 위치에 유입구(313) 및 배출구(314)를 구비하고 바닥면에 도출시킨 벽체(311)에 의해서 유입구(313)부터 배출구(314)까지 지그재그 형태의 유로(312)를 형성한 저수 상자(310)와, 벽체(311)에 걸쳐지며 유로(312)를 따라 포트홀(321)이 조성된 포트 거치판(320)과, 각 포토홀(321)에 삽입되며 식재한 식물 뿌리가 유로(312) 물에 잠기게 하는 포트(330)를 포함하게 구성되어서, 식물의 수경재배 환경을 조성한 재배조(300-1, 300-2, 300-3); 및 상기 수조(200)의 물을 워터펌프(410)로 취수하여 최상단 재배조(300-1)의 유입구(313)를 통해 공급하고, 최상단 재배조(300-1)에 공급한 물이 최하단 재배조(300-3)까지 순차적으로 흐르도록 배출구(314)와 유입구(313)를 통해 배관 연결되게 하고, 최하단 재배조(300-3)의 물을 배출구(314)를 통해 워터펌프로 취수하여 상기 수조(200)로 회수하되 상기 수조(200)에서의 취수 유량과 동일한 유량으로 회수하는 순환수단(400); 을 포함하되, 상기 워터펌프(410)는 전동 모터(411)와, 전동 모터(411)의 동력으로 회전하여 물을 동일 양수량으로 펌핑하는 2개 펌프(412, 413)로 구성되어, 상기 수조(200)의 물을 어느 하나의 펌프(412)로 취수하여 최상단 재배조(300-1)에 공급되게 하고, 최하단 재배조(300-3)의 물을 다른 하나의 펌프(413)로 취수하여 상기 수조(200)로 회수되게 하는 아쿠아포닉스 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

827/1150 Row 827: application_number: 1020200049113, combined_string: invention_title: 용존산소량 및 양액 농도 조절이 가능한 양액 재배 장치 및 방법 abstract: 본 발명은 층류를 활용한 수경재배용 육묘 장치에 관한 것으로, 양액이 담겨있는 양액통; 하부에 배출구가 형성되어 있고, 상기 배출구로 상기 양액을 배출하는 육묘판; 상기 양액을 상기 육묘판으로 공급하는 공급부; 및 상기 배출구로 배출되는 상기 양액의 레이놀드수가 층류 발생 조건인 2000 이하가 되도록 상기 공급부의 출력을 조절하는 제어부;를 포함한다. claims: 양액이 담겨있는 양액통; 하부에 배출구가 형성되어 있고, 상기 배출구로 상기 양액을 배출하며 식물이 수용되는 재배 베드; 상기 양액통의 양액을 상기 재배 베드로 공급하는 공급부; 상기 양액의 용존산소량에 따라 상기 배출구로 배출되는 상기 양액의 레이놀드수가 층류 발생 조건이 되도록 상기 공급부의 출력을 제어하고, 상기 배출구로 배출되는 상기 양액의 농도와 상기 양액통의 상기 양액의 농도의 농도차에 따라 상기 공급되는 양액의 유량이 늘어나게 상기 공급부의 출력을 제어하는 제어부; 및 상기 제어부가 상기 공급부의 출력을 제어할 때 상기 용존산소량 및 상기 농도차 중 어느 것에 우선순위를 두고 제어해야 하는지 판단하는 판단부;를 포함하는 것 을 특징으로 하는 용존산소량 및 양액 농도 조절이 가능한 양액 재배 장치. 공급부가 양액통의 양액을 재배 베드로 공급하는 제1단계; 용존산소 측정 센서가 상기 재배 베드의 배출구로 배출되는 양액의 용존산소량을 측정하는 제2단계; 양액 농도 측정 센서가 상기 배출구로 배출되는 상기 양액의 농도와 상기 양액통의 상기 양액의 농도를 측정하는 제3단계; 계산부가 상기 배출구로 배출되는 상기 양액의 농도와 상기 양액통의 상기 양액의 농도의 농도차를 계산하는 제4단계; 및 제어부가 상기 측정한 상기 양액의 용존산소량이 저장부에 저장된 용존산소량 기준치 이하일 경우 상기 배출구로 배출되는 상기 양액의 레이놀드수가 층류 발생 조건이 되도록 공급부의 출력을 제어하고, 상기 계산된 농도차가 저장부에 저장된 농도차 기준치 이상일 경우 상기 공급되는 양액의 유량이 늘어나게 상기 공급부의 출력을 제어하는 제5단계;를 포함하되, 상기 제5단계는, 판단부가 상기 측정한 용존산소량이 상기 용존산소량 기준치 대비 이상 또는 이하인지, 상기 계산한 농도차가 상기 농도차 기준치 대비 이상 또는 이하인지 판단하는 제5-1단계; 카메라가 상기 식물의 뿌리를 촬영하는 제5-2단계; 상기 판단부가 상기 제어부가 상기 공급부의 출력을 제어할 때 상기 측정한 용존산소량 및 상기 계산한 농도차 중 어느 것에 우선순위를 두고 제어해야 하는지 판단하는 제5-3단계; 및 상기 판단부가 판단한 우선순위에 따라 상기 제어부가 상기 공급부의 출력을 제어하는 제5-4단계;인 것 을 특징으로 하는 용존산소량 및 양액 농도 조절이 가능한 양액 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

828/1150 Row 828: application_number: 1020200043935, combined_string: invention_title: 식물 뿌리 생육 촉진용 액상비료의 제조방법 및 이에 의해 제조된 액상비료 abstract: 본 발명은 식물 뿌리 생육 촉진용 액상비료의 제조방법 및 이에 의해 제조된 액상비료에 관한 것이다.본 발명에 따른 식물 뿌리 생육 촉진용 액상비료의 제조방법은 물에 메타규산소다, 인산칼륨, 탄산칼륨 및 구연산을 포함하는 재료들을 용해하여 혼합액을 제조하는 혼합액 제조 단계(S100); 버드나무, 도꼬마리, 참쑥, 순비기나무, 소리쟁이, 민들레 및 어성초를 포함하는 천연재료를 준비한 후 혼합하는 천연재료 준비 및 혼합 단계(S200); 상기 혼합된 천연재료를 발효시키는 천연재료 발효 단계(S300); 상기 발효된 천연재료와 상기 혼합액을 혼합한 후 발효를 더 진행시켜 천연추출물을 제조하는 천연추출물 제조 단계(S400); 미생물 활성화제를 제조하는 미생물 활성화제 제조 단계(S500); 및 상기 천연추출물과 미생물 활성화제를 혼합하여 액상비료를 제조하는 액상비료 제조 단계(S600)를 포함한다.상기한 구성에 의해 본 발명에 따른 식물 뿌리 생육 촉진용 액상비료의 제조방법은 원예작물 생산에 중요한 영향을 미치는 규산 및 천연추출물을 이용하여 액상비료를 제조함으로써, 식물의 발근 및 생장 촉진을 유도하고 과실의 비대, 수확량의 증대, 착색 및 당도를 증진시킬 수 있는 액상비료를 제조할 수 있다. claims: 물에 메타규산소다, 인산칼륨, 탄산칼륨 및 구연산을 포함하는 재료들을 용해하여 혼합액을 제조하는 혼합액 제조 단계(S100);버드나무, 도꼬마리, 참쑥, 순비기나무, 소리쟁이, 민들레 및 어성초를 포함하는 천연재료를 준비한 후 혼합하는 천연재료 준비 및 혼합 단계(S200);상기 혼합된 천연재료를 발효시키는 천연재료 발효 단계(S300);상기 발효된 천연재료와 상기 혼합액을 혼합한 후 발효를 더 진행시켜 천연추출물을 제조하는 천연추출물 제조 단계(S400);미생물 활성화제를 제조하는 미생물 활성화제 제조 단계(S500); 및상기 천연추출물과 미생물 활성화제를 혼합하여 액상비료를 제조하는 액상비료 제조 단계(S600)를 포함하는 것을 특징으로 하는 식물 뿌리 생육 촉진용 액상비료의 제조방법.제 2항 또는 제 3항의 제조방법에 의해 제조된 것을 특징으로 하는 식물 뿌리 생육 촉진용 액상비료., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

829/1150 Row 829: application_number: 1020200044337, combined_string: invention_title: 식물 재배장치 abstract: 본 발명에 따른 식물 재배장치는 여러 개를 온실의 폭 방향으로 병렬로 배치하여 식물을 재배할 수 있으면서도 재배식물이 햇빛이나 외부조명을 골고루 받을 수 있도록 할 수 있다. 상기 식물 재배장치는 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임, 한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체, 한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되는 복수의 행거바 및 복수의 상기 행거바에 각각 매달린 복수의 식물재배용기를 포함하는 구성을 한다. claims: 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임;한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체; 및한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고,상기 프레임은 상기 순환지지구의 하부위치로 이동한 상기 행거바에 상기 식물재배용기가 매달린 상태에서 순환되는 것을 허용하는 높이 이상의 높이로 한 쌍의 상기 순환지지구를 지지하는 지지프레임을 가지는 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

830/1150 Row 830: application_number: 1020200041211, combined_string: invention_title: 가축분뇨를 이용한 친환경 비료의 제조방법 abstract: 본 발명은 가축분뇨에 포함된 인(P)이 용출되지 않아 살포되는 농지는 물론, 하천의 녹조 발생을 억제시켜 친환경으로 사용될 수 있고, 비료의 발효시간을 단축함으로써 생산성을 향상시킬 수 있는 친환경 비료의 제조방법과 그로 인해 제조되는 비료에 관한 것이다. 본 발명에 따른 친환경 비료의 제조방법은, 금속이온 용출액에 광물분말을 첨가하여 무기분말을 제조하는 단계와, 무기분말을 소정의 수분이 함유된 가축분뇨와 혼합하여 금속이온이 용출되는 1차 혼합물을 조성하는 단계, 및 1차 혼합물에 다른 가축분뇨를 첨가 혼합하여 2차 혼합물을 조성하여 발효하는 단계를 포함한다. claims: 금속이온 용출액에 광물분말을 첨가하여 무기분말을 제조하는 단계;상기 무기분말을 소정의 수분이 함유된 가축분뇨와 혼합하여 금속이온을 용출시켜 1차 혼합물을 조성하는 단계; 및,상기 1차 혼합물에 다른 가축분뇨를 첨가 혼합하여 2차 혼합물을 조성하여 발효하는 단계;를 포함하는 것을 특징으로 하는 가축분뇨를 이용한 친환경 비료의 제조방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

831/1150 Row 831: application_number: 1020200032510, combined_string: invention_title: 양액 재배 시스템 abstract: 본 발명은 식물의 뿌리 부분에 양액을 에어로졸 형태로 공급하여 양액의 낭비를 줄이고, 양분의 흡수율을 높여 성장 효율을 증가시킨 양액 재배 시스템을 제공하기 위한 것이다.본 발명의 양액 재배 시스템은, 외부에 식물의 줄기 및 잎이 배치되는 수용홈(110)이 형성되고, 내부에 식물의 뿌리부분이 배치되는 공급공간(120)이 형성된 재배대(100); 식물의 성장이 필요한 양액이 저장된 양액통(200); 상기 양액통(200)에 저장된 양액을 상기 재배대(100)의 내부에 공급하는 공급수단(300); 을 포함한다. claims: 외부에 식물의 줄기 및 잎이 배치되는 수용홈(110)이 형성되고, 내부에 식물의 뿌리부분이 배치되는 공급공간(120)이 형성된 재배대(100);식물의 성장이 필요한 양액이 저장된 양액통(200);상기 양액통(200)에 저장된 양액을 상기 재배대(100)의 내부에 에어로졸 형태로 공급하는 공급수단(300); 상기 재배대(100)의 내부 온도를 일정하게 제어하는 제1온도조절수단(400);상기 양액통(200)에 수용된 양액의 온도를 일정하게 제어하는 제2온도조절수단(500); 을 포함하되,수분과 영양분을 일정한 비율로 혼합하여 양액을 생성하여 상기 양액통(200)에 공급하는 양액교반기(600);상기 재배대(100) 내부에 공급된 에어로졸 상태의 양액을 모아 재사용하기 위한 배수장치(700); 를 포함하되,상기 수용홈(110)의 상단 테두리에는 안착부(111)가 돌출 형성되고,상기 수용홈(110)에는 식물이 식재된 모종화분(130)이 삽입 배치되며,상기 모종화분(130)는, 상단 테두리에 상기 안착부(111)에 지지되는 지지부(131)가 돌출 형성되고, 하단이 상기 공급공간(120) 방향으로 하향 경사지게 형성되며,상기 공급수단(300)은 원심형 가습기로 이루어지고,상기 제1온도조절수단(400)은, 상기 재배대(100)의 내부에 구비되는 제1열교환파이프(410);상기 제1열교환파이프(410)에 열교환액을 공급하는 제1냉각기(420); 를 포함하며,상기 제2온도조절수단(500)은,상기 양액통(200)의 내부에 구비되는 제2열교환파이프(510);상기 제2열교환파이프(510)에 열교환액을 공급하는 제2냉각기(520); 를 포함하며,상기 배수장치(700)는 펌프에 의해 상기 재배대(100)의 내부에 모인 액체상태의 양액을 보조양액통(750)으로 인출한 후 영양분을 재혼합한 후 상기 양액통(200)에 공급하는 것을 특징으로 하는 양액 재배 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

832/1150 Row 832: application_number: 1020200025697, combined_string: invention_title: 새싹땅콩 수경재배 장치 abstract: 본 발명은 재배단계를 구분하여 각 단계마다 온도 및 양액 분사량을 최적 조건으로 조절하여 성장률과 품질을 향상시킬 수 있는 새싹땅콩 수경재배 방법 및 그 장치에 관한 것이다.개시된 수경재배장치는, 땅콩씨앗을 파종하여 재배실에 실장하기 위한 다수의 재배모판과, 상기 재배모판에 파종된 땅콩씨앗을 소정 재배조건으로 재배하기 위한 재배실을 제공하는 재배챔버와, 상기 재배챔버의 전면에 장착되어 재배챔버를 조작하고 동작상태를 표시하기 위한 프론트 패널과, 상기 재배실에 양액을 공급하기 위한 양액 공급부와, 상기 재배실의 공기 온도를 조절하기 위한 공기온도 조절부와, 상기 프론트 패널의 조작에 따라 상기 공기온도 조절부를 제어하여 재배실의 온도를 조절하고, 상기 양액 공급부를 제어하여 재배실에 양액을 미스트 분사방식으로 공급하며, 동작 상태를 상기 프론트 패널에 표시하기 위한 컨트롤러를 포함한다. claims: 땅콩씨앗을 파종하여 재배실에 실장하기 위한 다수의 재배모판;양 측벽과 후벽, 천정, 바닥, 및 도어로 구성되고, 양 측벽에는 상기 재배모판을 지지하기 위한 지지 가이드가 다단으로 배치되어 발아실과 촉진실, 성숙실의 재배공간을 제공하는 재배챔버;상기 재배챔버의 전면에 장착되어 재배챔버를 조작하고 동작상태를 표시하기 위한 프론트 패널;상기 재배공간에 양액을 공급하기 위한 양액 공급부;상기 재배공간의 온도를 조절하기 위한 공기온도 조절부;상기 프론트 패널의 조작에 따라 상기 공기온도 조절부를 제어하여 상기 재배공간의 온도를 조절하고, 상기 양액 공급부를 제어하여 상기 재배공간에 양액을 공급하며, 동작 상태를 상기 프론트 패널에 표시하기 위한 컨트롤러를 포함하고,상기 양액 공급부는양액을 저장하기 위한 양액 탱크와, 상기 양액 탱크의 양액 온도를 감지하기 위한 온도센서와,제어신호에 따라 양액의 온도를 일정하게 유지하기 위한 히터와,상기 발아실의 양 측벽에 설치되어 미스트방식으로 양액을 분사하기 위한 발아실 분사노즐과,상기 촉진실의 양 측벽에 설치되어 미스트방식으로 양액을 분사하기 위한 촉진실 분사노즐과,상기 성숙실의 양 측벽에 설치되어 미스트방식으로 양액을 분사하기 위한 성숙실 분사노즐과,상기 양액 탱크의 양액을 재배공간의 분사노즐에서 미스트 방식으로 분사시킬 수 있도록 제어신호에 따라 양액을 가압시키기 위한 분사펌프와,상기 분사펌프에 의해 가압된 양액을 제어신호에 따라 상기 발아실 노즐측으로 개폐하기 위한 발아실 분사밸브와,상기 분사펌프에 의해 가압된 양액을 제어신호에 따라 상기 촉진실 노즐측으로 개폐하기 위한 촉진실 분사밸브와,상기 분사펌프에 의해 가압된 양액을 제어신호에 따라 상기 성숙실 노즐측으로 개폐하기 위한 성숙실 분사밸브로 구성되어새싹땅콩을 배양하기 위한 양액의 온도를 조절할 수 있음과 동시에 온도조절된 양액을 재배모판 위로 미스트방식으로 분사할 수 있는 것을 특징으로 하는 새싹땅콩 수경재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

833/1150 Row 833: application_number: 1020190166912, combined_string: invention_title: 기능성 성분이 증진된 밀싹의 제조방법 abstract: 본 발명은 밀싹을 저온처리하는 단계를 포함하는 기능성 성분이 증진된 밀싹의 제조방법, 상기 방법으로 제조되어 기능성 성분이 증진된 밀싹, 상기 밀싹을 포함하는 식품조성물 및 사료조성물에 관한 것이다. 본 발명에서 제공하는 방법에 의하면, 밀싹의 제조시 특별한 성분을 처리하는 과정 없이도, 밀싹에 포함된 다양한 기능성 성분의 함량을 증진시킬 수 있으므로, 높은 품질의 밀 재배에 널리 활용될 수 있을 것이다. claims: (a) 밀의 종자를 발아시켜서 밀싹을 수득하는 단계; (b) 발아된 밀싹을 저온처리하는 단계; 및, (c) 저온처리된 밀싹을 재배하는 단계를 포함하는, 기능성 성분이 증진된 밀싹의 제조방법.제1항 내지 제5항 중 어느 한 항의 방법으로 제조되어, 기능성 성분이 증진된 밀싹.제6항의 기능성 성분이 증진된 밀싹을 포함하는 식품조성물.제6항의 기능성 성분이 증진된 밀싹을 포함하는 사료조성물., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

834/1150 Row 834: application_number: 1020190165843, combined_string: invention_title: 광추적 시뮬레이션을 이용한 작물의 광합성 속도 분포 계산 장치 및 그 방법 abstract: 본 발명은 광추적 시뮬레이션을 이용한 작물의 광합성 속도 분포 계산 장치 및 그 방법에 관한 것으로, 광합성 속도 분포 계산 장치는 입력받은 작물의 3차원 모델에 광추적 시뮬레이션을 수행하여 작물 표면의 수광 분포를 산출하는 수광 시뮬레이션부, 수집한 작물의 광합성 실측값에 기초하여 광합성 속도 계산 모델을 통해 광합성 속도를 연산하는 광합성 연산부, 그리고 연산된 광합성 속도 계산 모델과 작물 표면의 수광 분포를 이용하여 작물의 수관 위치별 광합성 속도 분포를 제공하는 제어부를 포함한다. claims: 입력받은 작물의 3차원 모델에 광추적 시뮬레이션을 수행하여 작물 표면의 수광 분포를 산출하는 수광 시뮬레이션부, 수집한 상기 작물의 광합성 실측값에 기초하여 광합성 속도 계산 모델을 통해 광합성 속도를 연산하는 광합성 연산부, 그리고 연산된 상기 광합성 속도 계산 모델과 상기 작물 표면의 수광 분포를 이용하여 상기 작물의 수관 위치별 광합성 속도 분포를 제공하는 제어부, 를 포함하는 광합성 속도 분포 계산 장치.입력받은 작물의 성장 단계에 따른 하나 이상의 3차원 모델을 생성하는 단계, 상기 3차원 모델에 광추적 시뮬레이션을 수행하는 작물 표면의 수광 분포를 산출하는 단계, 상기 작물의 수직 위치별, 성장 단계별 중에서 하나 이상의 광합성 실측 값을 수집하는 단계, 상기 작물의 광합성 실측값에 기초하여 광합성 속도 계산 모델을 통해 광합성 속도를 연산하는 단계, 그리고 연산된 상기 광합성 속도 계산 모델과 상기 작물 표면의 수광 분포를 이용하여 상기 작물의 수관 위치별 광합성 속도 분포를 산출하고 제공하는 단계 를 포함하는 광합성 속도 분포 계산 장치의 광합성 속도 계산 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

835/1150 Row 835: application_number: 1020190161961, combined_string: invention_title: 축산용 포유 방지기 abstract: 본 발명은, 아기 가축의 코에 끼워지며 사용자의 쥠동작에 따라 개방되고, 사용자의 해제 동작에 의해 폐쇄되는 이루어지는 코걸림부; 상기 코걸림부의 대향하는 위치에 형성되며, 사용자의 그립 동작에 따라 상기 코걸림부를 개방폐쇄시키는 손잡이부; 및 상기 손잡이부에 형성된 다수의 돌출핀을 포함하는 포유 방지부를 포함하는, 축산용 포유 방지기에 관한 것이다. claims: 아기 가축의 코에 끼워지며 사용자의 쥠동작에 따라 개방되고, 사용자의 해제동작에 의한 복원 탄성력에 의해 자동 폐쇄되도록 이루어지는 코걸림부;상기 코걸림부의 대향하는 위치에 형성되며, 사용자의 그립 동작에 따라 상기 코걸림부를 개방 폐쇄시키는 손잡이부; 상기 손잡이부와 일체로 형성되며 다수의 돌출핀을 포함하는 포유 방지부;상기 코걸림부의 제 1 부와 상기 손잡이부의 제 1 부를 이루는 제 1 본체부;상기 코걸림부의 제 2 부와 상기 손잡이부의 제 2부를 이루는 제 2 본체부;상기 제 1 본체부와 상기 제 2 본체부의 중간에서 회전가능하게 결합시키는 피봇; 및 상기 피봇에 설치되며 상기 손잡이에서의 상기 사용자의 쥠동작시 상기 복원 탄성력을 부여하는 탄성 스프링을 포함하고,상기 제 1 본체부와 상기 제 2 본체부는 X자로 결합되며,상기 제 1 본체부 및 상기 제 2 본체부의 각각의 결합부에는 결합홀이 형성되어서, 상기 피봇이 상기 결합홀에 체결되는, 축산용 포유 방지기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

836/1150 Row 836: application_number: 1020190159695, combined_string: invention_title: 폴리페놀 고함유 쓴 잎 재배방법 abstract: 본 발명은 쓴 잎 재배 시에 발효유황을 사용하여 폴리페놀 함량이 현저히 증가된 쓴 잎 대량재배방법에 관한 것이다. claims: 쓴 잎 줄기를 18 내지 22cm 크기로 잘라 물에 1/3 잠기도록 한 후 실온에서 25일 내지 35일간 정치하여 흰 뿌리가 3-5개 내리도록 하는 쓴 잎 모종 전처리 단계;상기 전처리 단계에서 흰 뿌리가 3-5개 나온 쓴 잎 모종을, 상토:마사토:황토가 1:1:1로 배합된 모종판에 9-11 cm 간격으로 이식하여 물을 충분히 주면서 20~30℃의 온도에서 25 내지 35일간 생육시키는 모종재배단계; 모종재배단계에서 뿌리 내린 쓴 잎을 참나무껍질과 피트모스로 객토된 토양에 30-40cm 간격으로 심은 후, 2-3일 간격으로 25-35일간 지하 80-100cm에서 pH 5.5-6.5인 물을 사용하여 관수하고 그 이후부터는 1개월 간격으로 풀브산을 혼합한 물을 관수하면서 온도 15~25℃로 조절하여 쓴잎을 생육시키는 성장단계로 구성되는 쓴 잎 재배방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

837/1150 Row 837: application_number: 1020190159920, combined_string: invention_title: 영상 이미지를 이용한 작물 성장 진단 시스템 및 방법 abstract: 본 발명은 영상 이미지를 이용한 작물 성장 진단 시스템에 있어서, 상기 작물이 촬영된 상기 영상 이미지로부터 상기 작물의 크기 정보를 산출하는 영상 처리부; 상기 크기 정보 및 상기 작물의 무게 정보를 저장하는 데이터 베이스부; 및 상기 크기 정보와 상기 무게 정보의 관계를 분석하여 관계 모델을 산출하는 관계 모델 생성부를 포함하여 작물을 촬영한 이미지만으로 작물의 크기 및 무게 정보를 산출할 수 있고, 현재 성장 단계를 진단 및 예측하는 것이 가능한 것을 특징으로 한다. claims: 영상 이미지를 이용한 작물 성장 진단 시스템에 있어서,상기 작물이 촬영된 상기 영상 이미지로부터 상기 작물의 크기 정보를 산출하는 영상 처리부;상기 크기 정보 및 상기 작물의 무게 정보를 저장하는 데이터 베이스부; 및상기 크기 정보와 상기 무게 정보의 관계를 분석하여 관계 모델을 산출하는 관계 모델 생성부를 포함하는 것을 특징으로 하는 작물 성장 진단 시스템.영상 이미지를 이용한 작물 성장 진단 방법에 있어서,(a)복수개 작물의 크기 및 무게 데이터를 저장하며, 기 저장된 데이터로 작물의 크기와 무게의 관계를 다중회귀 분석하여 다중회귀 모델을 산출하는 관계 모델 생성단계;(b)조사대상 작물을 촬영하여 영상 이미지를 생성하는 촬영 단계;(c)상기 영상 이미지를 전처리하고 푸리에 변환하는 이미지 처리 단계;(d)변환된 상기 영상 이미지로부터 상기 작물의 크기 정보를 산출하는 산출 단계;(e)상기 크기 정보를 상기 다중회귀 모델에 입력하여 상기 조사대상 작물의 크기 정보에 대한 무게 정보를 산출하는 출력 단계;를 포함하는 것을 특징으로 하는 성장 작물 성장 진단 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

838/1150 Row 838: application_number: 1020190156728, combined_string: invention_title: 축산시설 공기정화 시스템 abstract: 본 발명은 축산시설 공기정화 시스템에 관한 것으로서, 축산시설 내부에서 발생하는 각종 분진 및 악취를 대기중에 배출시키지 않고 공기를 정화하여 재사용할 수 있는 축산시설 공기정화 시스템을 제공하는 것이다.본 발명은 축사로부터 오염된 공기를 수집하여 분진을 제거하는 것으로, 사이클론을 포함하는 분진제거부; 상기 분진제거부를 통해 분진이 제거된 공기에서 습식 세정방식에 의해 악취를 제어하는 것으로, 산성의 세정액으로 악취를 제거하는 세정부와, 염기성 중화액으로 공기중에 함유된 산성 미립자를 중화시키는 중화부를 포함하는 악취제거부;를 포함하여 구성되는 것을 특징으로 한다.또한, 상기 분진제거부는 입자가 큰 분진을 분류하는 사이클론과, 상기 사이클론에서 분류되지 않은 미세분진을 분류하는 백필터집진기를 포함하여 구성되는 것을 특징으로 한다.또한, 상기 중화액은 피톤치드 성분을 포함하는 것을 특징으로 한다. claims: 축사(10) 내부의 오염된 공기를 수집 정화하여 재공급하는 축산시설 공기정화 시스템에 있어서,축사(10)로부터 오염된 공기를 수집하여 분진을 제거하는 것으로, 사이클론(110)을 포함하는 분진제거부(100);상기 분진제거부(100)를 통해 분진이 제거된 공기에서 습식 세정방식에 의해 악취를 제어하는 것으로, 산성의 세정액으로 악취를 제거하는 세정부(210)와, 염기성 중화액으로 공기중에 함유된 산성 미립자를 중화시키는 중화부(220)를 포함하는 악취제거부(200);를 포함하여 구성된 것을 특징으로 하는 축산시설 공기정화 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

839/1150 Row 839: application_number: 1020190157546, combined_string: invention_title: 가정용 작물재배 장치 abstract: 본 명세서에 개시된 내용은 일반 가정에서 직접 작물을 재배 및 섭취할 수 있음은 물론 인삼과 같은 특용 작물의 생육원리와 재배 과정을 체험할 수 있는 자연친화적 교구로 활용할 수 있는 개량된 가정용 작물재배 장치에 관한 것이며, 전방 수납부와 후방 지지부를 포함하는 로어 베이스; 다수의 조작버튼을 포함하는 제어부와 엘이디 모듈을 포함하며, 상기 로어 베이스의 상부에 형성되는 어퍼 다이; 상기 어퍼 다이의 저면에 인접하게 설치되고, 상기 엘이디 모듈로부터 제공되는 빛을 선택적으로 굴절 및 분산시키는 차양기; 다수의 재배포트를 구비하며, 상기 전방 수납부로부터 인출가능하게 설치되는 베드; 및 상기 어퍼 다이 일측에 형성되는 손잡이부를 포함하여 구성된다. claims: 전방 수납부와 후방 지지부를 포함하는 로어 베이스;다수의 조작버튼을 포함하는 제어부와 엘이디 모듈을 포함하며, 상기 로어 베이스의 상부에 형성되는 어퍼 다이;상기 어퍼 다이의 저면에 인접하게 설치되고, 상기 엘이디 모듈로부터 제공되는 빛을 선택적으로 굴절 및 분산시키는 차양기;다수의 재배포트를 구비하며, 상기 전방 수납부로부터 인출가능하게 설치되는 베드; 및상기 어퍼 다이 일측에 형성되는 손잡이부를 포함하여 구성되는 것을 특징으로 하는 가정용 작물재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

840/1150 Row 840: application_number: 1020210121664, combined_string: invention_title: 이탈을 방지한 산림용 묘목 보호 시트 abstract: 본 발명은 이탈을 방지한 산림용 묘목 보호 시트에 관한 것으로서, 보다 상세하게는, 산에 식재된 어린 묘목에 설치하여 위치를 표시하여 용이하게 관리가 가능하고, 바람, 비 등에 의한 이탈 및 손상과 동물들에 의한 피해를 방지할 수 있는 이탈을 방지한 산림용 묘목 보호 시트에 관한 것이다. claims: 묘목에 설치하여 묘목을 용이하게 식별할 수 있는 이탈을 방지한 산림용 묘목 보호 시트에 있어서,절취선(PL) 및 절단선(CL)에 의해 인식부(20)가 재단되며, 접이선(FL)을 따라 상기 묘목(100)을 감싸도록 접이되는 시트지(10)로 이루어지되,상기 시트지(10)는,중앙부분에 형성된 상기 절취선(PL)에 의해 재단되어 상기 묘목(100)에 설치하는 제1인식표(30)와,상기 제1인식표(30)의 양측에 일정간격 이격되어 다수개 배치되며, 수직방향으로 형성된 상기 접이선(FL)과,양측단에서 내측으로 일정간격 이격되어 형성된 상기 절취선(PL)에 의해 재단되어 상기 묘목(100)에 설치하는 제2인식표(40)로 이루어지되,상기 제1인식표(30)는,내부 양측에 수직방향으로 상기 절단선(CL)이 재단된 원형의 중앙부분(31)과,상기 중앙부분(31) 보다 작은 크기의 원형이 상기 중앙부분(31)의 상단에 위치하며, 중앙에 삽입홈(34)이 형성되고 상기 삽입홈(34)에서 일측 방향 하단을 향해 지그재그 방향으로 상기 절단선(CL)이 재단된 상단부분(32)과,상기 중앙부분(31) 보다 작은 크기의 원형이 상기 중앙부분(31)의 하단에 위치하며, 중앙에 삽입홈(34)이 형성되고 상기 삽입홈(34)에서 타측 방향 상단을 향해 지그재그 방향으로 상기 절단선(CL)이 재단된 하단부분(33)으로 이루어지며,상기 시트지(10)의 상단에 수직방향으로 재단된 상기 절취선(PL)을 따라 절취하여 상기 제1인식표(30)의 상기 중앙부분(31)에 재단된 상기 절단선(CL)에 삽입되는 제3인식표(50)가 더 포함되는 것을 특징으로 하는 이탈을 방지한 산림용 묘목 보호 시트., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

841/1150 Row 841: application_number: 1020210077898, combined_string: invention_title: 잡초 배출이 용이한 구근 수확기 abstract: 본 발명은 잡초 배출이 용이한 구근 수확기에 관한 것으로, 제토컨베이어가 회전되게 설치되는 프레임에 고정되게 구비되는 연결바; 연결바에서 전방으로 돌출되게 구비되는 한편 제토컨베이어의 전방에서 그 전단부가 하향 경사지게 구비되는 굴취삽; 굴취삽과 프레임 사이에 형성되어 두둑 또는 고랑의 잡초가 걸리지 않고 통과할 수 있는 공간;을 포함하는 구근 수확기를 제공한다. claims: 제토컨베이어가 회전되게 설치되는 프레임에 고정되게 구비되는 연결바; 연결바에서 지지브라켓을 매개로 전방으로 돌출되게 구비되는 한편 제토컨베이어의 전방에서 그 전단부가 하향 경사지게 구비되는 굴취삽; 굴취삽과 프레임 사이에 형성되어 두둑 또는 고랑의 잡초가 걸리지 않고 통과할 수 있는 공간;을 양측 가장자리에 구비하되, 상기 공간은 굴취삽이 연결바보다 짧은 길이를 갖도록 구비되어, 프레임에 굴취삽의 설치시 굴취삽과 프레임 사이에는 일정 면적으로 형성되도록 한 구근 수확기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

842/1150 Row 842: application_number: 1020210023483, combined_string: invention_title: 시서스의 재배방법 abstract: 본 발명은 시서스의 재배방법에 관한 것으로, 보다 구체적으로는 일정하게 조성된 토양조성물을 사용하여 시서스 모종을 수차례 걸쳐 이식하면서 재배한 후 토양에 정식함으로써 정식 후 농약 살포나 시비 없이도 단기간에 유효성분함량이 높은 시서스를 재배할 수 있는 방법에 관한 것이다. 본 발명의 시서스 재배방법은, 시서스 모종을 준비하는 단계; 시서스 재배용 토양조성물이 담긴 화분에 시서스 모종을 삽목하여 재배하는 화분 삽목 재배 단계; 시서스 재배용 토양조성물이 담긴 더 큰 화분에 1~4차에 걸쳐 이식하면서 재배하는 화분 이식 재배 단계; 화분 이식 재배 단계가 끝난 후 토양에 정식하여 재배하는 토양 재배 단계를 포함한다. claims: 시서스 모종을 준비하는 단계;화산토, 부엽토 발효물 및 팜박 발효물을 포함하는 시서스 재배용 토양조성물이 담긴 화분에 상기 시서스 모종을 이식하여 재배하는 모종 이식 재배 단계;상기 모종 이식 재배한 시서스를 상기 시서스 재배용 토양조성물이 담긴 더 큰 화분에 1회 이상 수차례 이식하면서 재배하는 묘목 이식 재배 단계;상기 묘목 이식 재배 단계가 끝난 후 토양에 정식하여 재배하는 토양 재배 단계를 포함하는 시서스의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

843/1150 Row 843: application_number: 1020200150219, combined_string: invention_title: 플라즈마를 이용한 종자 처리 장치 abstract: 본 발명에 의하면, 수용 공간인 챔버를 제공하는 챔버 하우징; 상기 챔버에 수용되고 플라즈마 방전을 이용하여 종자를 처리하는 복수개의 종자 처리 모듈들; 및 상기 플라즈마 방전을 위하여 상기 복수개의 종자 처리 모듈들 각각으로 전원을 공급하는 전원 공급부를 포함하며, 상기 종자 처리 모듈들 각각은 상기 챔버에 위치하도록 설치되고 상기 플라즈마 방전이 일어나는 플라즈마 방전 유닛과, 상기 플라즈마 방전 유닛과 분리 가능하게 결합되고 처리 대상 종자들이 담기는 트레이 유닛을 구비하는 플라즈마를 이용한 종자 처리 장치가 제공된다. claims: 수용 공간인 챔버를 제공하는 챔버 하우징;상기 챔버에 수용되고 플라즈마 방전을 이용하여 종자를 처리하는 복수개의 종자 처리 모듈들; 및상기 플라즈마 방전을 위하여 상기 복수개의 종자 처리 모듈들 각각으로 전원을 공급하는 전원 공급부를 포함하며,상기 종자 처리 모듈들 각각은 상기 챔버에 위치하도록 설치되고 상기 플라즈마 방전이 일어나는 플라즈마 방전 유닛과, 상기 플라즈마 방전 유닛과 분리 가능하게 결합되고 처리 대상 종자들이 담기는 트레이 유닛을 구비하는,플라즈마를 이용한 종자 처리 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

844/1150 Row 844: application_number: 1020200083976, combined_string: invention_title: 묘목 물공급장치 abstract: 묘목 물 공급장치에 대해 개시된다.본 발명에 따른 묘목 물 공급장치는 상하부가 개구된 하나의 파이프가 길이방향을 따라 동일한 두 개의 부재로 절개된 형상으로 형성되되, 하부가 식재된 묘목 둘레에 소정 깊이로 지면에 삽입되는 제1 부재(100) 및 제2 부재(200);내부에 물을 저장 가능하도록 상기 제1 부재(100)와 제2 부재(200)는 묘목을 둘러싸도록 결합되어 묘목에 물을 공급하는 것을 특징으로 한다. claims: 상하부가 개구된 하나의 파이프가 길이방향을 따라 동일한 두 개의 부재로 절개된 형상으로 형성되되, 하부가 식재된 묘목 둘레에 소정 깊이로 지면에 삽입되는 제1 부재(100) 및 제2 부재(200);내부에 물을 저장 가능하도록 상기 제1 부재(100)와 제2 부재(200)는 묘목을 둘러싸도록 결합되어 묘목에 물을 공급하며,상기 제1 부재(100) 및 제2 부재(200)는,단면이 반원을 이루는 파이프형상으로 형성되되, 동일한 직경으로 수직방향으로 소정의 높이로 형성되며 하단부가 수직 하방향을 향하도록 형성된 원통부(110);상기 원통부(110) 상단에 형성되되, 수직 상방향으로 내경이 점진적으로 증가하는 확관부(120);상기 제1 부재(100)의 일측에는 제1 돌출부(111)가 형성되며 타측에는 제1 결합홈(112)이 형성되고, 상기 제2 부재(200)에는 상기 제1 돌출부(111)에 대향하는 위치에 제2 결합홈(212)이 형성되며, 상기 제1 결합홈(112)에 대향하는 위치에는 제2 돌출부(211)가 형성되어, 상기 제1 돌출부(111)는 제2 결합홈(212)에 결합되고 제2 돌출부(211)는 제1 결합홈(112)에 결합되며,내부에 저장된 물은 수압에 의해 수직 하방향으로 공급됨으로써, 물이 상기 원통부(110)의 외주면 밖으로 유실되지 않아 묘목 뿌리의 수분흡수율을 증가시키는 것을 특징으로 하며,상기 확관부(120)의 상단부에 수평방향으로 절곡되어 형성된 플랜지(140);를 더 포함하며,상기 플랜지(140)는 묘목 물 공급장치를 지면에 삽입하기 위해 가압력을 부가하기 용이하도록 하는 것을 특징으로 하는, 묘목 물 공급장치, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

845/1150 Row 845: application_number: 1020200076397, combined_string: invention_title: 근적외선 흡수스펙트럼을 이용한 식물 종자 생육활성의 비파괴 판별방법 abstract: 본 발명은 저장 및 보관 중인 식물 종자에 대하여 파괴하지 않은 상태로 근적외선 흡수 스펙트럼을 수득한 후 다변량 통계분석을 이용하여 종자의 생육활성을 판별할 수 있으므로 식물 종자의 특별한 전처리가 필요 없고 측정에 사용한 식물 종자의 폐기 없이 종자의 상품성을 평가할 수 있는 장점이 있다. claims: 비파괴 콩 종자 시료에 대하여 1100 내지 2500nm의 범위로 근적외선 흡수 스펙트럼을 얻는 제 1 단계;상기 근적외선 흡수 스펙트럼으로부터 10 내지 100nm 간격으로 흡광도 데이터를 추출하는 제 2 단계;상기 흡광도 데이터를 이용하여 다변량 통계분석(mutivariate statistics analysis)을 수행하여 흡광도에 대한 변동기여도에 따라 주성분 파장을 추출한 로딩 플롯(loading plot)을 수득하고, 상기 로딩 플롯의 주성분 파장을 스코어에 따라 주성분 그룹으로 분리하여 영역으로 표시한 다변량 통계분석 스코어 플롯을 수득하는 제 3 단계; 및상기 비파괴 콩 종자 시료의 다변량 통계분석 결과를 통해 수득한 다변량 통계분석 스코어 플롯의 영역과 비교용 정상 비파괴 콩 종자 시료 및 비교용 비파괴 비정상 콩 종자 시료의 다변량 통계분석 결과를 통해 수득한 다변량 통계분석 스코어 플롯의 영역을 비교하여 상기 비파괴 콩 종자 시료의 생육활성을 판별하는 제 4 단계;를 포함하는 것을 특징으로 하는 식물 종자의 비파괴적 생육활성 판별 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

846/1150 Row 846: application_number: 1020200062470, combined_string: invention_title: 유기산 기체를 이용한 박과 식물 종자의 살균 방법 abstract: 본 발명은 유기산 기체를 이용한 박과 식물 종자의 살균 방법에 관한 것으로, 보다 상세하게는 특정 상대습도와 온도 조건에서 특정 유기산을 자연 기화하도록 유도함으로써 박과 종자의 발아율은 저해하지 않으면서 박과 종자에 존재하는 식물병원균과 식중독균을 멸균시키기 위한 살균 방법에 관한 것이다. claims: 아세트산 기체 또는 프로피온산 기체를 박과 식물 종자에 처리하는 것을 포함하는 박과 식물 종자의 살균 방법.식물병원균 또는 식중독균을 멸균시키는 박과 식물 종자의 살균 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

847/1150 Row 847: application_number: 1020200058048, combined_string: invention_title: 봉투식 버섯종균 자동액체 접종기 abstract: 본 발명은 봉투식 버섯종균 자동액체 접종기에 관한 것으로, 더욱 상세히는 입구측의 형태 유지가 어려운 봉투식 배지용기에 종균액의 자동접종과 뚜껑의 개폐가 용이하도록 상부에 뚜껑이 결합되고 내부에 배지가 충진된 상태인 봉투식 배지용기가 다수 담긴 바구니를 이송하는 이송부(20)와, 이송부에 의해 이송되던 바구니를 종균 접종위치에서 승하강 시키는 바구니승강부(30)와, 상기 바구니승강부의 상측으로 설치되어 다수의 봉투식 배지용기 입구를 고정시키는 용기고정부(40)와, 상기 용기고정부의 상측으로 설치되어 봉투식 배지용기의 뚜껑을 개폐하는 뚜껑개폐부(50)와, 상기 봉투식 배지용기에 종균액을 분사하는 종균분사부(60)와, 상기 이송부, 바구니승하강부, 용기고정부, 뚜껑개폐부, 종균분사부가 설치되는 작업테이블(10)로 구성된다. claims: 상부에 뚜껑이 결합되고 내부에 배지가 충진된 상태인 봉투식 배지용기가 다수 담긴 바구니(2)를 이송하는 이송부(20)와, 이송부에 의해 이송되던 바구니를 종균 접종위치에서 승하강 시키는 바구니승강부(30)와, 상기 바구니승강부의 상측으로 설치되어 다수의 봉투식 배지용기 입구를 고정시키는 용기고정부(40)와, 상기 용기고정부의 상측으로 설치되어 봉투식 배지용기의 뚜껑을 개폐하는 뚜껑개폐부(50)와, 상기 봉투식 배지용기에 종균액을 분사하는 종균분사부(60)와, 상기 이송부, 바구니승강부, 용기고정부, 뚜껑개폐부, 종균분사부가 설치되는 작업테이블(10)로 이루어지는 봉투식 버섯종균 자동액체 접종장치에 있어서,상기 용기고정부(40)는 상부의 승강실린더(40c)에 의해 승하강되고 등간격으로 복수의 용기입구투입공(410)이 형성된 용기고정판(41), ㄴ자로 절곡되며 상기 용기고정판(41)의 상부면에서 각 열의 용기입구투입공(410)을 중심으로 소정간격을 두고 양쪽에 대향하여 설치되고 각 용기입구투입공과 동일 위치에 각 요입홈(420a,420b)이 형성되며 배지용기의 입구를 가압할 수 있게 양측으로 슬라이딩 작동되는 다수의 제1클램프판(42a) 및 제2클램프판(42b)으로 구성되며,상기 뚜껑개폐부(50)는 작업테이블(10)의 양측면에 설치된 승강수단(50c)에 의해 승하강되며 각 용기입구투입공(410)과 대응되는 위치에 통공(510)이 형성되고 통공(510)의 주변으로 다수의 장공(511)이 형성된 뚜껑개폐판(51)과, 상기 뚜껑개폐판(51)의 상측에서 승강실린더(52e)에 의해 승하강되게 설치되며 각 통공(510)으로 수직 관통되고 배지용기의 뚜껑을 가압시키도록 하단부에 원통형의 가압블록(520s)이 구비된 가압봉(520)이 탄성력 있게 설치된 뚜껑가압판(52)과, 상기 뚜껑개폐판(51)과 뚜껑가압판(52)의 사이에 이중구조로 대향되게 설치되며 각 이동실린더(55a,55b)의 작동으로 각각 대향되게 수평이동되어 하단부 ㄴ자 형태의 제1뚜껑클램프(533a)와 제2뚜껑클램프(533b)가 배지용기의 뚜껑을 걸어 개폐시킬 수 있는 제1이동판(53a)과 제2이동판(53b)으로 구성되는 것을 특징으로 하는 봉투식 버섯종균 자동액체 접종기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

848/1150 Row 848: application_number: 1020200042302, combined_string: invention_title: 러그컨베이어의 높이 조절이 가능한 구근류 채굴장치 abstract: 본 발명은 러그컨베이어의 높이 조절이 가능한 구근류 채굴장치에 관한 것으로, 작업 차량의 프레임에 회전가능하게 구비되어 두둑에서 채굴된 작물을 이송시키며 흙을 털어내는 제토컨베이어와, 제토컨베어와 같이 회전되게 구비되어 제토컨베이어에 의해 이송되는 작물을 받쳐 낙하를 방지하는 러그컨베이어를 포함하는 채굴유닛을 갖는 구근류 채굴장치로서, 프레임에 고정되는 한편 일측에는 복수의 고정공이 형성돼 있는 고정브라켓이 구비되고, 일측 단부가 고정브라켓에 회전가능하게 결합되는 한편 타측 단부는 러그컨베이어에 연결되고, 그 표면에는 고정공과 체결부재로 결합되는 복수의 결합공이 형성돼 있는 힌지브라켓이 구비되어, 힌지브라켓이 고정브라켓 상에서 회전됨에 따라 러그컨베이어가 상하로 이동되게 구비되는 구근류 채굴장치를 제공한다. claims: 작업 차량의 프레임에 회전가능하게 구비되어 두둑에서 채굴된 작물을 이송시키며 흙을 털어내는 제토컨베이어와, 제토컨베어와 같이 회전되게 구비되어 제토컨베이어에 의해 이송되는 작물을 받쳐 낙하를 방지하는 러그컨베이어를 포함하는 채굴유닛을 갖는 구근류 채굴장치로서, 프레임에 고정되는 한편 일측에는 복수의 고정공이 형성돼 있는 고정브라켓이 구비되고, 일측 단부가 고정브라켓에 회전가능하게 결합되는 한편 타측 단부는 러그컨베이어에 연결되고, 그 표면에는 고정공과 체결부재로 결합되는 복수의 결합공이 형성돼 있는 힌지브라켓이 구비되어, 힌지브라켓이 고정브라켓 상에서 회전됨에 따라 러그컨베이어가 제토컨베이어의 전면에서 러그컨베이어의 길이방향으로 상하 이동되게 구비되는 구근류 채굴장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

849/1150 Row 849: application_number: 1020200036679, combined_string: invention_title: 산양산삼 재배방법 abstract: 본 발명은 산양산삼 재배방법에 관한 것으로, 보다 구체적으로는 멧돼지, 고라니, 노루, 너구리, 오소리, 들쥐 또는 조류로부터 작물을 보호하기 위한 산양산삼 재배방법에 관한 것으로 본 발명의 실시예는 하부금속그물망에 의해 땅 속에서 침입하는 유해조수로부터 작물의 뿌리를 보호하고 상부금속그물망에 의해 땅 위로 침입하는 유해조수로부터 씨앗과 작물을 보호하며, 하부금속그물망과 상부금속그물망의 연결을 탈부착고리를 이용하여 수확시에는 보호장치를 쉽게 분리하여 편리하게 수확할 수 있으며, 금속선재가 포함된 금속그물망을 이용하여 장기간 별도의 유지보수 없이 사용이 가능하고, 작물이 재배되는 토양공간을 금속그물망으로 폐쇄하므로 경사지의 토사와 작물의 유실을 방지할 수 있고, 금속그물망을 이용하므로 면적에 따라 금속그물망의 크기를 쉽게 적용하여 작물재배할 수 있으므로 소량의 작물재배부터 대량의 작물재배까지 모두 적용이 가능한 효과가 있다. claims: 토양에 작물재배장치를 설치하여 산삼종자를 파종하거나 묘삼을 이식하여 생장시켜 재배하고 수확하는 산양산삼의 재배 방법에 있어서,상기 작물재배장치는 금속선재를 포함하여 쉽게 구부릴 수 있는 피복된 금속그물망으로 형성된 상부금속그물망과 하부금속그물망을 포함하며,상기 하부금속그물망을 토양 아래에 오목하게 설치하여 토양공간을 형성하는 하부금속그물망설치단계와;상기 하부금속그물망 위에 흙을 덮어서 상기 토양공간에 흙을 채우는 제1차복토단계와;상기 제1차복토단계에서 채워진 흙의 표면에 산삼종자를 파종하거나 묘삼을 이식하는 식재단계와;상기 하부금속그물망의 가장자리에 연결되고 토양공간 위를 덮어서 토양공간을 폐쇄하는 판형의 상기 상부금속그물망을 설치하는 상부금속그물망설치단계와;상기 상부금속그물망 위에 흙을 덮는 복토단계와;상기 씨앗의 발아에 의해 발생한 산삼이나 식재된 산삼묘를 재배하는 재배단계와;상기 산양산삼의 재배가 종료된 후 상부금속그물망을 분리하는 분리단계와;상기 산양산삼을 수확하는 수확단계를 포함하며,상기 하부금속그물망설치단계에서 상부금속그물망에 연결되지 않은 말단부인 하부날개를 토양 표면에 배치하고;상기 상부금속그물망설치단계에서 하부금속그물망에 연결되지 않은 말단부인 상부날개를 상기 하부날개위를 덮으며,상기 상부금속그물망과 하부금속그물망이 안쪽의 토양을 폐쇄하는 것을 특징으로 하는 산양산삼 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

850/1150 Row 850: application_number: 1020200032500, combined_string: invention_title: 발효 미생물의 분리, 동정, 종균 관리 및 배양 대행서비스 abstract: 본 발명은 발효 미생물의 분리, 동정, 종균 관리 및 배양 대행서비스에 관한 것으로, 더욱 상세하게는 인터넷을 사용하여 업체 담당자가 전문 연구원과 발효 미생물의 분리, 동정, 종균 관리 및 배양에 대하여 실시간으로 비대면 상담을 실시하고 균주증식 및 관리를 도와 발효생산에 대한 중소기업 기술 지원 및 제품 개발, 그리고 품질 향상에 획기적인 도움을 제공하는 서비스이다.전통적인 자연 접종은 미생물 발효 관리를 작업자의 경험으로 실시하기 때문에, 생산단가의 개선과 품질 관리가 어렵고 이로 인해 소규모 발효 생산은 여전히 전문가에 의한 소량생산에 의존하고 있다. 발효에 사용하는 종균은 대부분 외국에서 상업화한 균을 구매하는데, 균의 관리가 미흡하여 구매한 종균을 재사용하지 못하고 일회용으로 사용하는 경우가 많으며, 종균의 증식을 하지 못해 발효 규모를 키우지 못하여 종균 구매에 지나친 비용이 들어가 원가가 상승하여 경쟁력을 갖추지 못하는 요인이 된다. 발효 생산 업체의 균주 국산화 수요가 높으나 이를 이러한 연구를 의뢰할 기관이 없으며, 종균의 증식 및 재사용을 위한 보관을 위탁 역시 불가능한 상황이다.본 발명은 새로운 비즈니스 모델을 개발하여 발효 미생물 관리 대행 웹사이트를 통해 업체 담당자가 전문 연구원과 발효 미생물의 분리, 동정, 종균 관리 및 배양에 대하여 실시간으로 비대면 상담을 실시하고 균주증식 및 관리를 도와 발효생산에 대한 중소기업 기술 지원 및 제품 개발, 그리고 품질 향상에 획기적인 도움을 제공할 수 있다. claims: 발효 미생물의 분리, 동정, 종균 관리 및 증식 대행 서비스, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

851/1150 Row 851: application_number: 1020200030255, combined_string: invention_title: 사계절 모종 채소 재배기 abstract: 본 발명의 목적은 채소 및 특용작물 그리고 꽃 등의 제반 농작물 등의 어린 식물을 소규모로 효과적으로 재배할 수 있고, 필요에 따라 재배 장소를 이동시킨 후, 그 이동된 위치에서 고정시킬 수 있게 함으로서 농작물 재배를 위한 재배 장소에 구애됨이 없이 간편히 재배할 수 있는 사계절 모종 채소 재배기를 제공한다. 이러한 본 본 발명은, 사계절 모종 채소 재배기로서, 재배기의 바닥을 형성하도록 설치되는 소정 면적을 갖는 베이스부; 상기 베이스부의 테두리를 따라 세워지게 설치되어 재배기의 골조를 형성하는 골조부; 및 상기 골조부를 덮도록 상기 골조부에 탈부착 가능하게 설치되는 비닐부;를 포함하고, 상기 베이스부는: 하부로부터 방수합판, 스치로폼, 전기패널 및 냉난방패널이 순차적으로 적층 설치되는 것이 바람직하다. claims: 사계절 모종 채소 재배기에 있어서, 재배기의 바닥을 형성하도록 설치되는 소정 면적을 갖는 베이스부; 상기 베이스부의 테두리를 따라 세워지게 설치되어 재배기의 골조를 형성하는 골조부; 및 상기 골조부를 덮도록 상기 골조부에 탈부착 가능하게 설치되는 비닐부;를 포함하고, 상기 베이스부는: 하부로부터 방수합판, 스치로폼, 전기패널 및 냉난방패널이 순차적으로 적층 설치되는 것을 특징으로 하는 사계절 모종 채소 재배기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

852/1150 Row 852: application_number: 1020217031148, combined_string: invention_title: 체리모야의 종자 추출물 abstract: 본 발명은 일반적으로 화장품 분야에 관한 것이다. 더욱 구체적으로, 본 발명은 체리모야(Annona cherimola) 식물의 종자 추출물을 포함하는 피부 관리 미용 조성물에 관한 것이다. 본 발명은 이러한 종자 추출물이 피부에 몇가지 이로운 효과를 갖는다는 발견에 기초한다. 이러한 효과로는 체리모야의 종자 추출물이 진정, 완화, 보습 및 가려움 방지 효과를 들 수 있다. 또 다른 측면에서, 본 발명은 따라서, 본 발명의 피부 관리 조성물을 투여하는 것을 포함하는, 대상체에서 피부 외관을 개선시키거나 피부 건조를 감소시키는 방법을 제공한다. 또 다른 측면에서, 본 발명은 본 발명의 피부 관리 조성물을 투여하는 것을 포함하는, 대상체의 자극받은 피부를 진정시키거나(soothing) 자극을 완화하는(calming) 미용 방법을 제공한다. 본 발명은 또한 피부 관리, 특히 자극받은 피부를 진정시키거나 자극을 완화하거나 피부 외양을 개선하거나 피부 건조 및 가려움증을 감소시키기 위한 체리모야의 종자 추출물의 용도에 관한 것이다. claims: 체리모야(Annona cherimola) 식물의 종자 추출물을 포함하는 피부 관리 미용 조성물.대상체에서 피부 외양을 개선하거나 피부 가려움증을 감소시키는 미용 방법으로서, 제1항 내지 제10항 중 어느 하나의 항의 조성물을 상기 대상체의 피부에 투여하는 것을 포함하는, 미용 방법.대상체에서 자극받은 피부를 진정시키거나 자극을 완화하는 미용 방법으로서, 제1항 내지 제10항 중 어느 하나의 항의 조성물을 상기 대상체의 피부에 투여하는 것을 포함하는, 미용 방법.미용 피부 관리를 위한, 제1항 내지 제10항 중 어느 하나의 항의 조성물의 용도.자극받은 피부의 진정, 자극 받은 피부의 자극 완화, 피부 외양 개선 및/또는 피부 건조 감소를 위한, 제1항 내지 제10항 중 어느 하나의 항의 조성물의 용도., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

853/1150 Row 853: application_number: 1020200022611, combined_string: invention_title: 구근류 분류장치 abstract: 본 발명은 제1베이스 프레임; 상기 제1베이스 프레임에 고정되는 구근류 이송부; 상기 구근류 이송부 하부의 제1영역에 위치하고, 상기 구근류 이송부에서 낙하된 제1크기의 제1구근류를 제1측 방향으로 배출하기 위한 제1가이드판; 및 상기 구근류 이송부 하부의 제2영역에 위치하고, 상기 구근류 이송부에서 낙하된 제2크기의 제2구근류를 제2측 방향으로 배출하기 위한 제2가이드판을 포함하는 구근류 분류장치에 관한 것으로, 구근류의 채굴과 동시에 이를 크기별로 분류할 수 있는 구근류 분류장치를 제공할 수 있다. claims: 제1베이스 프레임; 및상기 제1베이스 프레임에 고정되는 구근류 이송부를 포함하고,상기 구근류 이송부는, 제1이송부를 포함하고,상기 제1이송부는, 제1-1이송가이드부; 및 상기 제1-1이송가이드부와 일정 간격 이격하여 배치되는 제1-2이송가이드부를 포함하며,상기 제1이송부는, 상기 제1-1이송가이드부에 배치되는 제1-1지지부; 및 상기 제1-2이송가이드부에 배치되는 제1-2지지부를 더 포함하는 구근류 분류장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

854/1150 Row 854: application_number: 1020200021705, combined_string: invention_title: 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법 abstract: 본 발명은 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법에 관한 것으로, 보다 구체적으로는 용수의 pH 조절, LED 광조사 조절, 자극제 처리를 통한 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법에 관한 것이다.본 발명의 일 실시예에 따른 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법은 보리 종자를 종자 트레이 상에 준비하는 제 1단계; 상기 트레이 상에 위치된 보리 종자에 pH 6 내지 7의 용수를 이용하여 수분을 공급하는 제 2단계; 상기 수분이 공급된 보리 종자를 암처리 및 적색 LED 광처리를 실시하며 발아시키는 제 3단계; 상기 발아된 보리를 청색 LED 광처리를 실시하고, 자극제를 공급하며 재배하는 제 4단계; 상기 LED 광처리 및 자극제의 공급을 수행한 다음 1 내지 3일 이후 보리를 수확하는 제 5단계;를 포함하는 것을 특징으로 한다. claims: 보리 종자를 종자 트레이 상에 준비하는 제 1단계;상기 트레이 상에 위치된 보리 종자에 pH 6 내지 7의 용수를 이용하여 수분을 공급하는 제 2단계;상기 수분이 공급된 보리 종자를 암처리 및 적색 LED 광처리를 실시하며 발아시키는 제 3단계;상기 발아된 보리를 청색 LED 광처리를 실시하고, 자극제를 공급하며 재배하는 제 4단계;상기 LED 광처리 및 자극제의 공급을 수행한 다음 1 내지 3일 이후 보리를 수확하는 제 5단계;를 포함하는 것을 특징으로 하는 식물공장에서의 사포나린 함량이 높은 새싹보리 재배방법, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

855/1150 Row 855: application_number: 1020200018281, combined_string: invention_title: 식물 재배장치 abstract: 본 발명은 종자의 발아는 물론이고 발아된 식물을 한번에 대량으로 재배할 수 있고, 복수개의 층에 각각에서 다수개의 재배판을 용이하게 입출시킬 수 있는 식물 재배장치에 관한 것으로, 종자 또는 식물이 수용되는 재배판(20)이 다수개 수용되어 재배되도록 형성된 재배기본체(10)와, 상기 재배기본체(10) 내부에 다수개의 프레임이 종횡 방향으로 골조를 이루도록 설치되어 복수개의 열을 형성하고, 그 복수개의 열 각각에는 양측 내벽면에 상기 재배판(20)의 양측 하면이 지지된 채로 입출되도록 이동을 안내하는 재배판지지프레임(31)이 다층 구조를 이루도록 설치되며, 각 층에는 상기 재배판(20)이 동일선상에 2개 이상 순차적으로 인입되어 일렬로 배치되도록 재배판인입공간(33)이 형성된 선반(30)과, 상기 재배기본체(10)의 내부 일측에 설치된 물저장탱크(50)로부터 공급받은 물을 상기 재배판(20)의 상면에 분사하도록 형성된 물분사유닛(40)을 포함하고, 상기 선반(30)은 종자를 발아시키기 위한 발아영역(35)과 발아된 식물을 성장시키기 위한 재배영역(36)이 각각 하나 이상 구비되도록 형성되어지되, 상기 발아영역(35)에 형성된 각 재배판지지프레임(31)의 설치높이 간격은 재배영역(36)에 형성된 각각의 재배판지지프레임(31)의 설치높이 간격에 비해 좁게 형성한 것을 특징으로 한다. claims: 종자 또는 식물이 수용되는 재배판(20)이 다수개 수용되어 재배되도록 형성된 재배기본체(10);상기 재배기본체(10) 내부에 다수개의 프레임이 종횡 방향으로 골조를 이루도록 설치되어 복수개의 열을 형성하고, 그 복수개의 열 각각에는 양측 내벽면에 상기 재배판(20)의 양측 하면이 지지된 채로 입출되도록 이동을 안내하는 재배판지지프레임(31)이 다층 구조를 이루도록 설치되며, 각 층에는 상기 재배판(20)이 동일선상에 2개 이상 순차적으로 인입되어 일렬로 배치되도록 재배판인입공간(33)이 형성된 선반(30);상기 재배기본체(10)의 내부 일측에 설치된 물저장탱크(50)로부터 공급받은 물을 상기 재배판(20)의 상면에 분사하도록 형성된 물분사유닛(40);을 포함하고,상기 선반(30)은 종자를 발아시키기 위한 발아영역(35)과 발아된 식물을 성장시키기 위한 재배영역(36)이 각각 하나 이상 구비되도록 형성되어지되, 상기 발아영역(35)에 형성된 각 재배판지지프레임(31)의 설치높이 간격은 재배영역(36)에 형성된 각각의 재배판지지프레임(31)의 설치높이 간격에 비해 좁게 형성된 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

856/1150 Row 856: application_number: 1020200018312, combined_string: invention_title: 고기능성 인삼 속성재배 장치 abstract: 본 발명은 고기능성 인삼 속성재배 장치에 관한 것으로, 뚜껑을 이용하여 밀폐되는 재배조 내에 인삼 씨앗 또는 묘삼을 정식하고, 인삼이 특이점을 가지는 각 생장 기간마다 환경 조건을 다르게 제공함으로써, 인삼이 속성으로 생장할 수 있도록 하는 효과가 있다. claims: 인삼 속성재배 장치로서,인삼 씨앗 또는 묘삼이 정식되는 토양이 수용되는 재배조로서, 상부가 개방되어 있고 상기 토양의 온도를 조절하기 위해 상기 토양에 접하도록 배치된 온도조절 모듈을 포함하는 것인, 재배조;상기 재배조의 상부를 덮어 밀폐 공간을 형성하도록 상기 재배조에 결합 가능한 제1뚜껑으로서, 상기 인삼 씨앗 또는 상기 묘삼에 광을 조사하기 위한 발광 모듈이 장착된 제1뚜껑;상기 재배조의 상부를 덮어 밀폐 공간을 형성하도록 상기 재배조에 결합 가능한 제2뚜껑; 및상기 인삼 속성재배 장치를 제어하는 제어 모듈로서, 상기 재배조에 상기 제1뚜껑이 결합되면 상기 발광 모듈이 발광하도록 제어하고 상기 토양이 제1온도를 유지하도록 상기 온도조절 모듈을 제어하고, 상기 제2뚜껑이 결합되면 상기 토양이 상기 제1온도보다 낮은 제2온도를 유지하도록 상기 온도조절 모듈을 제어하는 것인, 제어 모듈을 포함하는, 인삼 속성재배 장치.뚜껑의 변경없이 인삼을 속성으로 재배하기 위한 장치로서,인삼 씨앗 또는 묘삼이 정식되는 토양이 수용되는 재배조로서, 상부가 개방되어 있고 상기 토양의 온도를 조절하기 위해 상기 토양에 접하도록 배치된 온도조절 모듈을 포함하는 것인, 재배조;상기 재배조의 상부를 덮어 밀폐 공간을 형성하도록 상기 재배조에 결합 가능한 뚜껑으로서, 상기 인삼 씨앗 또는 상기 묘삼에 광을 조사하기 위한 발광 모듈이 장착된 뚜껑;상기 인삼 속성재배 장치를 제어하는 제어 모듈로서, 상기 재배조에 상기 뚜껑이 결합되면 상기 토양이 제1온도를 유지하도록 상기 온도조절 모듈을 제어하는 제어 모듈을 포함하고,상기 제어 모듈은,상기 재배조에 상기 뚜껑이 결합되면 상기 발광 모듈이 백색광을 발광하도록 제어하는 것을 특징으로 하는, 인삼 속성재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

857/1150 Row 857: application_number: 1020200016750, combined_string: invention_title: 식물재배용 팩 및 그 제조방법 abstract: 본 발명은 부직포와 부직포 내측면에 고정되는 흡수포가 원통형으로 길게 구성되고 그 내부에 부엽토가 충전되어 뿌리로 양분을 공급하며, 간편하게 사용할 수 있도록 특정 식물의 씨앗이 휴면 상태로 파종되어 있어 발아(germination) 조건이나 발아 환경이 제공되면 발아 및 생육되도록 한 식물재배용 팩 및 그 제조방법에 관한 것으로, 길이가 긴 원통형 부직포(2)와, 부직포 내측면에 고정되는 흡수포(3)와, 부직포의 양측면에 고정되는 측부재(8)(9)와, 부직포(2) 내부에 충전되는 부엽토(10)와, 부직포(2)와 흡수포(3)의 길이 방향으로 위치에 소정 간격으로 형성되는 복수의 재배공(4)(5)과, 부직포(2)와 흡수포(3)에 사이에 고정되는 소정 폭의 씨앗고정봉지(7)와, 씨앗고정봉지(7)에 적어도 하나 이상 포장되고 부직포의 재배공(5)과 흡수포(3)의 재배공(4)(5) 사이에 위치하는 식물 씨앗(6)과, 부직포(2) 외면에 소정 폭으로 가접착되어 재배공(4)(5)을 막는 테이프(11)를 포함한다.상기 측부재(8)(9) 외면에 고정되는 소정 크기의 벨크로테이프(12)(13)를 더 포함한다. 상기 부직포(2)의 외면에 씌워 포장하는 포장지(14)를 더 포함한다. claims: 길이가 긴 자루형태의 부직포;부직포의 내측면에 고정되는 흡수포;흡수포 내부 공간에 충전되는 부엽토;부직포와 흡수포의 길이 방향 같은 위치에 소정 간격으로 형성되는 복수의 재배공;부직포와 흡수포 사이에 고정되는 소정 폭의 씨앗고정봉지;씨앗고정봉지에 적어도 하나 이상 포장되고 부직포와 재배공에 형성되는 재배공과 같은 위치에 위치하는 식물 씨앗;부직포 외면에 가접착되어 부직포의 재배공을 막는 소정 폭의 테이프;를 포함하는 식물재배용 팩.a) 부직포와 흡수포를 같은 평면적으로 재단하는 단계;b) 부직포와 흡수포의 길이방향 같은 위치에 소정 크기의 재배공을 소정 간격으로 형성하는 단계;c) 적어도 1개 이상의 식물 씨앗이 부직포와 흡수포에 형성되는 재배공 간격과 같은 간격으로 포장 고정되는 씨앗고정봉지를 부직포와 흡수포 사이에 위치시키되 식물 씨앗과 재배공이 같은 위치에 위치시키는 단계;d) 부직포와 흡수포를 접합하는 단계;e) 접합된 부직포와 흡수포를 자루 형태로 접합하는 단계;f) 흡수포 내부에 부엽토를 충전하고 접합을 마무리하는 단계;g) 부직포의 재배공이 막히도록 소정 폭의 테이프로 가접착하는 단계;를 포함하는 식물재배용 팩 제조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

858/1150 Row 858: application_number: 1020200016271, combined_string: invention_title: 버섯 재배 시스템 및 버섯 재배 방법 abstract: 본 발명은 버섯 재배 시스템 및 버섯 재배 방법에 관한 것으로, 본 발명의 버섯 재배 시스템은 외부로부터 공급된 톱밥을 반입하는 프론트로더(100), 상기 프론트로더(100)를 거쳐 반입된 톱밥을 공급 받아 배지 원료를 배합하여 배지를 조제하는 배지원료배합기(200), 상기 배지원료배합기(200)에서 조제된 배지를 전달 받아 비닐에 입봉한 후 설정 온도 및 시간으로 살균하는 배지입봉살균부(300), 상기 배지입봉살균부(300)를 거쳐 살균된 배지를 전달 받아 설정 온도까지 배지를 자연 냉각시키는 냉각실(400), 상기 냉각실(400)을 거쳐 자연 냉각된 배지를 전달 받아 종균을 접종하며, 종균이 접종된 배지를 배양하는 종균접종배양부(500), 상기 종균접종배양부(500)를 거쳐 배양된 배지를 전달 받아 비닐을 제거하는 비닐제거기(600), 상기 비닐제거기(600)를 거쳐 비닐이 제거된 배지에 밀랍을 코팅하는 밀랍코팅장치(700), 상기 밀랍코팅장치(700)를 거쳐 밀랍이 코팅된 배지를 전달 받아 보관하며, 버섯을 생육하는 버섯생육실(800), 및 상기 버섯생육실(800)에서 생육된 버섯을 수확하여 출하하는 버섯출하부(900)를 포함한다. claims: 외부로부터 공급된 톱밥을 반입하는 프론트로더(100);상기 프론트로더(100)를 거쳐 반입된 톱밥을 공급 받아 배지 원료를 배합하여 배지를 조제하는 배지원료배합기(200);상기 배지원료배합기(200)에서 조제된 배지를 전달 받아 비닐에 입봉한 후 설정 온도 및 시간으로 살균하는 배지입봉살균부(300);상기 배지입봉살균부(300)를 거쳐 살균된 배지를 전달 받아 설정 온도까지 배지를 자연 냉각시키는 냉각실(400);상기 냉각실(400)을 거쳐 자연 냉각된 배지를 전달 받아 종균을 접종하며, 종균이 접종된 배지를 배양하는 종균접종배양부(500);상기 종균접종배양부(500)를 거쳐 배양된 배지를 전달 받아 비닐을 제거하는 비닐제거기(600);상기 비닐제거기(600)를 거쳐 비닐이 제거된 배지에 밀랍을 코팅하는 밀랍코팅장치(700);상기 밀랍코팅장치(700)를 거쳐 밀랍이 코팅된 배지를 전달 받아 보관하며, 버섯을 생육하는 버섯생육실(800); 및상기 버섯생육실(800)에서 생육된 버섯을 수확하여 출하하는 버섯출하부(900);를 포함하는 버섯 재배 시스템. 제1항 내지 제9항 중 어느 한 항의 버섯 재배 시스템을 이용한 버섯 재배 방법으로서, 상기 프론트로더(100)에서 외부로부터 공급된 톱밥을 반입하는 단계;상기 배지원료배합기(200)에서 상기 프론트로더(100)를 거쳐 반입된 톱밥을 공급 받아 배지 원료를 배합하여 배지를 조제하는 단계;상기 배지입봉살균부(300)에서 상기 배지원료배합기(200)로부터 조제된 배지를 전달 받아 비닐에 입봉한 후 설정 온도 및 시간으로 살균하는 단계;상기 냉각실(400)에서 상기 배지입봉살균부(300)를 거쳐 살균된 배지를 전달 받아 설정 온도까지 배지를 자연 냉각시키는 단계;상기 종균접종배양부(500)에서 상기 냉각실(400)을 거쳐 자연 냉각된 배지를 전달 받아 종균을 접종하며, 종균이 접종된 배지를 배양하는 단계;상기 비닐제거기(600)에서 상기 종균접종배양부(500)를 거쳐 배양된 배지를 전달 받아 비닐을 제거하는 단계;상기 밀랍코팅장치(700)에서 상기 비닐제거기(600)를 거쳐 비닐이 제거된 배지에 밀랍을 코팅하는 단계; 및상기 버섯생육실(800)에서 상기 밀랍코팅장치(700)를 거쳐 밀랍이 코팅된 배지를 전달 받아 보관하며, 버섯을 생육하는 단계;를 포함하는 버섯 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

859/1150 Row 859: application_number: 1020200003783, combined_string: invention_title: 묘목 생장용 전용포트 및 그 전용포트를 이용한 묘목 생장 방법 abstract: 본 발명은 보관의 편익을 제공하면서 수차례 재사용이 용이함은 물론, 환경이 다른 노지에서 성장이 멈추거나 주춤하지 않고 왕성한 발육이 되도록 하는 묘목 생장용 전용포트 및 그 전용포트를 이용한 묘목 생장 방법에 관한 것으로,전용포트를 이용한 묘목 생장 방법은 바닥면(10)을 구비하면서 바닥면의 상측으로 원형 또는 다각형 형상의 벽면(20)이 바닥면과 일체형으로 형성되어 내부 수용공간(30)을 형성하며, 원터치에 의해 결합이 용이하도록 벽면의 접합면(60)에 각각 형성되는 결합돌기(41)와 결합홈(42) 또는 접합면(60)의 플랜지(43)와 볼트/너트(44) 중 선택된 어느 하나로 구성되는 고정수단(40)에 의해 분리 및 결합 고정이 용이한 좌, 우 대칭구조로 구성되되, 상기 바닥면(10)과 벽면(20)에는 수분과 영양분이 유입되도록 하는 유입홈(50)이 다수 개 형성된 전용포트(S)의 수용공간(30)에 토양을 채우는 토양 채움 단계(S100)와, 상기 수용공간(30)의 내부에 채워진 토양에 묘목용 씨앗을 파종하는 씨앗파종단계(S200)와, 상기 씨앗 파종 후 1 내지 3년 생장을 시킨 다음, 전용포트(S)의 고정수단(40)을 해체하여 좌, 우로 분리 후 노지에 옮겨심기를 하고, 재사용을 위해 수거를 하는 분리/수거단계(S300)로 구성된다. claims: 바닥면(10)을 구비하면서 바닥면의 상측으로 원형 또는 다각형 형상의 벽면(20)이 바닥면과 일체형으로 형성되어 내부 수용공간(30)을 형성하며, 고정수단(40)에 의해 분리 및 결합 고정이 용이하도록 좌, 우 대칭구조로 구성되되, 상기 바닥면(10)과 벽면(20)에는 수분과 영양분이 유입되는 유입홈(50)이 다수 개 형성되는 것을 특징으로 하는 묘목 생장용 전용포트.전용포트를 이용한 묘목 생장 방법은 바닥면(10)을 구비하면서 바닥면의 상측으로 원형 또는 다각형 형상의 벽면(20)이 바닥면과 일체형으로 형성되어 내부 수용공간(30)을 형성하며, 원터치에 의해 결합이 용이하도록 벽면의 접합면(60)에 각각 형성되는 결합돌기(41)와 결합홈(42) 또는 접합면(60)의 플랜지(43)와 볼트/너트(44) 중 선택된 어느 하나로 구성되는 고정수단(40)에 의해 분리 및 결합 고정이 용이한 좌, 우 대칭구조로 구성되되, 상기 바닥면(10)과 벽면(20)에는 수분과 영양분이 유입되도록 하는 유입홈(50)이 다수 개 형성된 전용포트(S)의 수용공간(30)에 토양을 채우는 토양 채움 단계(S100); 와,상기 수용공간(30)의 내부에 채워진 토양에 묘목용 씨앗을 파종하는 씨앗파종단계(S200); 와,상기 씨앗 파종 후 1 내지 3년 생장을 시킨 다음, 전용포트(S)의 고정수단(40)을 해체하여 좌, 우로 분리 후 노지에 옮겨심기를 하고, 재사용을 위해 수거를 하는 분리/수거단계(S300);로 구성되는 것을 특징으로 하는 묘목 생장용 전용포트를 이용한 묘목 생장 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

860/1150 Row 860: application_number: 1020190178590, combined_string: invention_title: 식물 종자의 초기 발아속도 증진용 조성물 및 식물 종자의 초기 발아속도를 증진시키는 방법 abstract: 본 발명은 식물 종자의 크기 증진용 조성물, 식물 종자의 크기를 증진시키는 방법, 식물 종자의 초기 발아속도 증진용 조성물 및 식물 종자의 초기 발아속도를 증진시키는 방법에 관한 것으로서, 상기 pPLAIIIα 유전자가 과발현되면 식물 종자의 크기가 커지고 초기 발아속도가 증진되므로, 이를 효과적으로 식물의 생산성 증대 방법으로 이용할 수 있다. claims: 서열번호 1로 표시되는 아미노산 서열을 갖는 pPLAIIIα(Patatin-related phospholipase A) 단백질 또는 pPLAIIIα 단백질을 코딩하는 핵산 서열을 포함하는 식물 종자의 초기 발아속도 증진용 조성물.서열번호 1로 표시되는 아미노산 서열을 갖는 pPLAIIIα(Patatin-related phospholipase A) 단백질을 코딩하는 핵산 서열의 발현을 증가시키는 조절 단계를 포함하는 식물 종자의 초기 발아속도를 증진시키는 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

861/1150 Row 861: application_number: 1020190171001, combined_string: invention_title: 냉각시스템을 이용한 딸기육묘방법 abstract: 본 발명에 따른 냉각시스템을 이용한 딸기육묘방법은, 기존의 비닐하우스와 같은 장소에서소 실현이 가능하게 되어 고가의 설비가 필요없으면서도 딸기의 꽃눈이 빠르게 분화되게 하기 위하여 딸기의 모주(어미묘)를 정식하고 런너(자묘)의 발생을 촉진하여 자묘를 유인하고 개별 또는 연결포트에 상포를 넣고 뿌리발근을 한후에 40일 ~ 60일간의 생장관리 후에 약 15일 ~ 30일간의 암막/저온처리(16시에서 다음날 10시까지 8 ~ 15℃ 여름기간인 7월 8월 동안의 처리)를 수행하고, 이를 다시 정상적인 처리인 주간 25 ~ 30℃ 로 15일 ~ 30일 정도의 생장처리를 수행하여 딸끼의 조속한 생장을 촉진시켜 조속한 출하를 가능하게 하고 시기적으로 딸기의 2모작이 가능하게 되어 농가소득이 증대되는 것이 가능하다 claims: 냉각시스템을 이용한 딸기육묘방법에 있어서, 상기 냉각시스템을 이용한 딸기육묘방법은, 하우스본체(1)의 상부에 빛이 투광되지 않은 암실커튼(2)이 배치되고, 상기 암실커튼(2)을 작동시키는 구동모터(3)가 하우스본체(1)의 상부에 배치되어 상기 암실커튼(2)을 승강구동시키는 구조를 갖고, 상기 하우스본체(1)의 내부에는 냉각시스템(4)이 설치되어 상기 냉각시스템(4)이 하우스본체(1)의 내부의 온도를 16시에서 다음날 10시까지의 8℃~ 16℃의 저온으로 유지시키는 구조를 갖으며,딸기의 꽃눈이 빠르게 분화되게 하기 위하여 딸기의 모주(어미묘)를 정식하는 단계와, 상기 딸기의 모주에서 런너(자묘)의 발생을 촉진하여 자묘를 유인하고 개별포트 또는 서로 연결된 연결포트에 상토를 넣고 뿌리발근 및 발아 준비를 시키는 뿌리발근 및 발아 준비단계와, 상기 뿌리발근 및 발아 준비단계 후에 주간 25 ~ 30℃ 로 40일 ~ 60일간의 생장관리를 수행하여 뿌리발근과 발아되는 딸기육묘성장단계와, 상기 딸기육묘성장단계 후에 15일 ~ 30일간의 16시에서 다음날 10시까지 암막커튼처리하고 16시에서 다음날 10시까지 8 ~ 15℃ 여름기간인 7월 8월 동안의 야간냉온 처리를 수행하여 꽃눈형성을 촉진시키는 단일야냉처리단계와, 상기 단일야냉처리후에 정상적인 처리인 주간 25 ~ 30℃ 로 15일 ~ 60일의 기간에 수정 및 착과후 딸기의 생장이 완료되는 정상생장처리단계를 포함하는 것을 특징으로 하는 냉각시스템을 이용한 딸기육묘방법, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

862/1150 Row 862: application_number: 1020190167428, combined_string: invention_title: 식물 재배용 트레이 abstract: 본 발명은 식물 재배용 트레이에 관한 것으로서, 씨앗이 수납된 복수의 씨앗캡슐이 마련되는 씨앗캡슐용 키트 및 씨앗이 발아한 모종판이 마련되는 새싹재배용 키트가 선택적으로 착탈되는 하나 이상의 키트 착탈부를 갖는 트레이 본체; 및 상기 트레이 본체가 분리가능하게 안착되는 베이스를 포함하는 것을 특징으로 한다. claims: 씨앗이 수납된 복수의 씨앗캡슐이 마련되는 씨앗캡슐용 키트 및 씨앗이 발아한 모종판이 마련되는 새싹재배용 키트가 선택적으로 착탈되는 하나 이상의 키트 착탈부를 갖는 트레이 본체; 및상기 트레이 본체가 분리가능하게 안착되는 베이스를 포함하는, 식물 재배용 트레이., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

863/1150 Row 863: application_number: 1020190167429, combined_string: invention_title: 씨앗캡슐 abstract: 본 발명은 씨앗캡슐에 관한 것으로서, 씨앗이 수납된 배지를 수용하는 수용부와, 상기 수용부와 연통하며 상기 배지가 인출입하는 인출입구를 형성하는 캡슐 본체; 상기 배지로부터 생장된 식물이 통과하는 통과공을 형성하고, 상기 인출입구를 통해 노출되는 상기 배지를 커버하며 상기 인출입구에 착탈가능하게 결합되는 캡; 및 상기 수용부에 마련되어, 상기 배양액의 유동을 안내하며 상기 배양액을 상기 배지에 균등하게 공급하는 배양액 공급 가이드를 포함하는 것을 특징으로 한다. claims: 씨앗이 수납된 배지를 수용하는 수용부와, 상기 수용부와 연통하며 상기 배지가 인출입하는 인출입구를 형성하는 캡슐 본체;상기 배지로부터 생장된 식물이 통과하는 통과공을 형성하고, 상기 인출입구를 통해 노출되는 상기 배지를 커버하며 상기 인출입구에 착탈가능하게 결합되는 캡; 및상기 수용부에 마련되어, 상기 배양액의 유동을 안내하며 상기 배양액을 상기 배지에 균등하게 공급하는 배양액 공급 가이드를 포함하는, 씨앗캡슐., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

864/1150 Row 864: application_number: 1020190167850, combined_string: invention_title: 딸기 조기 생산을 위한 육묘 방법 abstract: 본 발명은, 딸기 조기 생산을 위한 육묘 방법에 관한 것으로, 본 발명의 일 실시예에 따른 딸기 조기 생산을 위한 육묘 방법은, 딸기의 자묘를 생육하여 런너 발생 환경을 제공하는 단계; 상기 런너가 발생한 자묘를 일시 채묘한 후 육모판에 삽식하는 단계; 및 상기 삽식된 자묘에 화아 분화 환경을 제공하는 단계;를 포함한다. claims: 딸기의 자묘를 생육하여 런너 발생 환경을 제공하는 단계; 상기 런너가 발생한 자묘를 일시 채묘한 후 육모판에 삽식하는 단계; 및상기 삽식된 자묘에 화아 분화 환경을 제공하는 단계;를 포함하는,딸기 조기 생산을 위한 육묘 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

865/1150 Row 865: application_number: 1020190166962, combined_string: invention_title: 씨앗 복원성을 갖는 저온건조방법 abstract: 본 발명은 진공실 내에 씨앗을 진공 및 냉각 처리하는 단계; 및 상기 진공실에서 냉각된 씨앗에 원적외선을 조사하는 단계;를 포함하는 것인, 씨앗건조방법에 관한 것으로, 종래보다 저 비용으로 씨앗 복원을 제공하는 효과, 씨앗의 복원성 향상 및 씨앗 보관 기간 동안 소요비용이 들지 않는 효과를 제공할 수 있다. claims: 진공실에서 씨앗을 진공상태를 유지하고 냉각 처리하는 단계; 상기 냉각된 씨앗에 원적외선을 조사하는 단계; 및상기 씨앗을 건조시키는 단계;를 포함하는, 복원력이 향상된 씨앗건조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

866/1150 Row 866: application_number: 1020190164368, combined_string: invention_title: 자란의 종자 발아율 및 배비대율을 증가시키는 방법 abstract: 본 발명은 자란(Bletilla striata)의 종자 발아율 및 배비대율을 증가시키는 방법에 관한 것으로, 자란의 종자활력, 발아 및 배비대에 영향을 미치는 차아염소산나트륨의 최적 처리조건을 확립함으로써, 향후 희귀식물인 자란의 개체증식과 복원에 매우 유용하게 활용될 수 있다. claims: 표면 살균한 자란 속(Bletilla sp.) 식물의 종자에 차아염소산나트륨(sodium hypochlorite)을 처리하는 단계를 포함하는 자란 속 식물의 종자 발아율 및 배비대율을 증가시키는 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

867/1150 Row 867: application_number: 1020190163019, combined_string: invention_title: 고추 묘목 건조 스트레스 경감용 트라이코더마 속 GL02 곰팡이 및 이의 용도 abstract: 본 발명은 식물의 발아율 증가 및 식물의 건조 스트레스 저감 효과를 가지는 트라이코더마 속(Trichoderma sp.) GL02 곰팡이, 상기 곰팡이의 배양액 또는 이들의 혼합물을 유효성분으로 포함하는 미생물 제제 및 이를 이용한 식물 종자의 발아율 증가 방법과 식물의 건조 스트레스 저감 방법에 관한 것이다. claims: 서열번호 1로 표시되는 ITS 염기서열을 갖는 식물 종자의 발아율 증가 및 식물의 건조 스트레스 저감용 트라이코더마 브레비컴팩텀(Trichodermabrevicompactum) GL02 곰팡이(KACC 93331P).제1항 또는 제2 항에 따른 곰팡이, 상기 곰팡이의 배양액 또는 이들의 혼합물 중 적어도 하나를 유효성분으로 포함하는 미생물 제제.제8 항에 따른 미생물 제제 중 적어도 하나를 식물, 식물 주변 영역, 또는 이들 모두에 처리하는 단계를 포함하는 식물 종자의 발아율 증가 방법.제1 항에 따른 곰팡이, 상기 곰팡이의 배양액 중 적어도 하나 이상을 고추, 고추 묘목 주변 영역, 또는 이들 모두에 처리하는 단계를 포함하는 고추의 건조 스트레스 저감 방법.제7 항에 따른 미생물 제제 중 적어도 하나 이상을 고추, 고추 묘목 주변 영역, 또는 이들 모두에 처리하는 단계를 포함하는 고추의 건조 스트레스 저감 방법.제8 항에 따른 미생물 제제 중 적어도 하나 이상을 고추, 고추 묘목 주변 영역, 또는 이들 모두에 처리하는 단계를 포함하는 고추의 건조 스트레스 저감 방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

868/1150 Row 868: application_number: 1020190152442, combined_string: invention_title: LED 조명을 이용한 육묘 및 재배 장치 및 이를 이용한 육묘 및 재배 방법 abstract: 본 발명은 식물의 발아, 육묘 및 재배를 한꺼번에 수행하는 것이 가능하다. 보다 상세하게는 발아육묘실과 재배실이 인접하게 배치되고, 상기 발아육묘실 및 재배실 각각에 배양액을 공급하는 것이 가능하며, 잔여 배양액을 회수하여 재사용하는 것이 가능한 재배 장치에 관한 것이다. claims: 서랍형태의 구조로 단일 또는 복수의 층을 구성하며, 식물을 발아 및 육묘하는 제1 육묘트레이, 제1 육묘트레이 손잡이, 배양액을 공급하는 배양액 공급호스, 배양액을 배액하는 배액장치 및 상기 배액장치에서 배액되는 배양액을 운반하는 배액파이프가 구비된 발아육묘실;상기 발아육묘실과 인접하게 배치되고, 단일 또는 복수의 층을 구성하며, 식물이 정식되는 제2 육묘트레이 및 상기 제2 육묘트레이가 장착될 수 있는 장착부를 구비한 재배실;상기 발아육묘실에 광을 제공하는 제1 광원부 및 상기 재배실에 광을 제공하는 제 2광원부; 상기 제1 육묘트레이 및 상기 제2 육묘트레이의 근권부 중 적어도 하나에 상기 배양액을 제공하는 배양액 제공부; 및잔여 배양액을 회수하여 상기 배양액 제공부로 보내는 배양액 회수부;를 포함하는 식물의 육묘 및 재배 장치.식물의 육묘 및 재배 장치를 이용한 식물의 발아 및 육묘 방법에 있어서,발아육묘실 내의 제1 육묘트레이에 상기 식물의 씨를 심는 단계;제1 광원부가 상기 제1 육묘트레이에 광을 제공하는 단계;스위치 온 오프 여부에 따라, 배양액 제공부가 상기 제1 육묘트레이에 배양액을 주입하는 방식으로 상기 배양액을 제공하는 단계;상기 제1 육묘트레이에 과잉 주입된 상기 배양액이 배액장치를 통해 배양액 회수부로 회수되어 상기 배양액 제공부로 보내지는 단계; 및상기 배양액 제공부에서 다시 상기 제1 육묘트레이에 상기 배양액을 주입하는 방식으로 상기 배양액을 제공하는 단계를 포함하는 식물의 발아 및 육묘 방법.식물의 육묘 및 재배 장치를 이용한 식물의 재배 방법에 있어서,발아육묘실과 인접하게 배치된 재배실 내의 제2 육묘트레이에 식물을 정식하는 단계;제2 광원부가 상기 제2 육묘트레이에 광을 제공하는 단계;스위치 온 오프 여부에 따라, 배양액 제공부가 상기 제2 육묘트레이에 정식된 식물의 근권부에 배양액을 분사하는 방식으로 상기 배양액을 제공하는 단계;상기 식물의 근권부에 분사된 후, 재배실 바닥으로 떨어진 상기 배양액이 배양액 회수부로 회수되어 상기 배양액 제공부로 보내지는 단계; 및상기 배양액 제공부에서 다시 상기 제2 육묘트레이에 정식된 식물의 근권부에 상기 배양액을 분사하는 방식으로 상기 배양액을 제공하는 단계를 포함하는 식물의 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

869/1150 Row 869: application_number: 1020190150710, combined_string: invention_title: 동절기 토마토 접목묘 육묘 장치 및 그의 재배 방법 abstract: 본 발명은 동절기 토마토 접목묘 육묘 장치 및 그의 재배 방법에 관한 것으로, 밀폐되어 내부에 공간이 마련되는 시설부; 상기 시설부 내부에 식물을 재배할 수 있는 공간이 마련되는 육묘부; 상기 시설부 내부에 마련되며, 상기 시설부 일측에서 공급되는 이산화탄소를 노즐을 통해 상기 육묘부 상부에 분사하는 공급부; 상기 육묘부 일측에 이산화탄소 농도를 측정하는 센서; 상기 센서와 연결되어, 상기 공급부를 개폐를 조절하는 밸브; 상기 시설부 내부에 마련되며 상기 육묘부 상부에 마련되는 보광부; 상기 센서의 이산화탄소 농도에 따라 상기 밸브를 동작하며, 상기 보광부의 동작을 조절하는 제어부;로 구성되는 것을 특징으로 한다. claims: 밀폐되어 내부에 공간이 마련되는 시설부;상기 시설부 내부에 식물을 재배할 수 있는 공간이 마련되는 육묘부;상기 시설부 내부에 마련되며, 상기 시설부 일측에서 공급되는 이산화탄소를 노즐을 통해 상기 육묘부 상부에 분사하는 공급부;상기 육묘부 일측에 이산화탄소 농도를 측정하는 센서;상기 센서와 연결되어, 상기 공급부를 개폐를 조절하는 밸브;상기 시설부 내부에 마련되며 상기 육묘부 상부에 마련되는 보광부;상기 센서의 이산화탄소 농도에 따라 상기 밸브를 동작하며, 상기 보광부의 동작을 조절하는 제어부;로 구성되는 것을 특징으로 하는 동절기 토마토 접목묘 육묘 장치.제 1항에 의해 제조된 동절기 토마토 접목묘 육묘 장치에 있어서,토마토 접목묘를 시설부 내부에 마련되는 육묘부에서 재배하며, 시설부 내부는 100 μmol·m-2·s-1 PPFD 광도의 메탈할라이드등으로 16시간 동안 보광하는 것을 특징으로 하는 동절기 토마토 접목묘 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

870/1150 Row 870: application_number: 1020190117864, combined_string: invention_title: 벼의 친환경 재배방법과 이를 이용한 벼 종자의 채종방법 abstract: 본 발명은 자연순환농법과 미생물을 이용한 유기농법을 이용하여 친환경적으로 벼를 재배할 수 있는 벼의 친환경 재배방법과, 친환경 재배방법을 통해 재배하기에 적합한 벼 종자를 채종할 수 있는 벼 종자의 채종방법에 관한 것이다. 본 발명에 따른 벼의 친환경 재배방법 및 벼 종자의 채종방법은 벼를 수확 후 농지에 녹비작물을 파종하는 녹비작물 파종 단계와, 농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계, 벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계, 상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계, 토양에 모를 이앙하는 모 이앙 단계, 벼의 영양 생장기에 벼의 잎에 존재하는 미네랄 성분을 분석하는 벼의 엽분석 단계, 상기 벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및, 벼를 수확하는 벼 수확 단계를 포함하고, 상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하는 것을 특징으로 한다. claims: 벼를 친환경적으로 재배하는 방법에 있어서,벼를 수확 후 농지에 녹비작물을 파종하는 녹비작물 파종 단계와,농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계,벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계,상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계,토양에 모를 이앙하는 모 이앙 단계,벼의 영양 생장기에 벼의 잎에 존재하는 미네랄 성분을 분석하는 벼의 엽분석 단계,상기 벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및,벼를 수확하는 벼 수확 단계를 포함하고,상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하는 것을 특징으로 하는 벼의 친환경 재배방법.벼를 친환경적으로 재배하는 방법에 있어서,벼를 수확 후 농지에 녹비작물을 파종하는 녹비작물 파종 단계와,농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계,상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계,벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계,벼의 영양 생장기에 벼의 잎에 존재하는 미네랄 성분을 분석하는 벼의 엽분석 단계,상기 벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및,벼를 수확하는 벼 수확 단계를 포함하고,상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하는 것을 특징으로 하는 벼의 친환경 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

871/1150 Row 871: application_number: 1020190117936, combined_string: invention_title: 저광도의 적색 및 청색 LED를 광원으로 이용하는 마이크로튜버 감자 종자의 생산방법 abstract: 직파 가능한 마이크로튜버 감자 종자의 생산성을 높일 수 있는 방법이 제시된다. 본 발명의 방법에 따르면, 감자 줄기의 조직 배양시에 적색 및 청색 LED 광원을 혼합하여 저광도로 조사함으로써, 감자 줄기의 생육을 좋게 하고 복지형성율을 높혀 최종적으로 크기가 큰 마이크로튜버 감자 종자를 다량 생산할 수 있다. claims: (a) MS 배지를 기준으로, 질산 암모늄 함량이 800 내지 1200 mg/L 및 질산 칼륨의 함량이 3000 내지 4000 mg/L이고, 탄소원이 2 내지 4 중량%으로 조정된 배지에 무균 감자 줄기를 치상하여 LED 광원을 광량 20 내지 48 umol/m2/sec로 조사하면서 10 내지 30일 배양하여 증식 줄기를 배양하는 단계; 및(b) 증식 줄기를 커팅 후 남은 하단의 1~3 마디를 MS 배지를 기준으로, 질산 암모늄 함량이 200 내지 800 mg/L, 질산 칼륨 함량이 2500 내지 3000 mg/L이고, 탄소원이 7 내지 10 중량%로 조정된 배지에서 암조건하 70일 내지 100일 배양하는 단계를 포함하는, 마이크로튜버 감자 종자의 생산방법. 제1항의 방법에 의하여 생산된 마이크로튜버 감자 종자., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

872/1150 Row 872: application_number: 1020207017253, combined_string: invention_title: 다기능 육묘장치 abstract: 본 발명은 식물 식재 재배 설비 기술분야에 관한 것으로, 상세하게는, LED 다층 식물 육묘 장치에 관한 것으로, 다품종 식물의 종묘 재배에 적용하여 수경재배, 토양재배, 기질재배 등 재배방식의 수요를 만족시키는 육묘장치에 관한 것이다. 본 발명은 고정적으로 설치된 육묘 베이스와 이동가능식 육묘 층대 차량을 포함하는 데, 상기 육묘 베이스는 하나의 프레임을 포함하고, 상기 프레임에 광원을 설치하며; 상기 이동가능식 육묘 층대 차량은 층판 프레임을 포함하고, 상기 층판 프레임에 적어도 2개의 층판을 설치하며, 상기 층판에 식재판을 설치하고, 층판 프레임 저부에 이동가능식 장치를 설치하며, 상기 층판 프레임의 층판은 육묘 베이스의 광원 위치와 매칭된다. 본 발명은 모듈화, 스마트화, 고효율과 높은 생산액에 달성할 수 있는 종묘재배를 구현하는 입체화의 다기능 스마트 육묘장치를 제공한다. claims: 고정적으로 설치된 육묘 베이스와 이동가능식 육묘 층대 차량을 포함하는 데, 상기 육묘 베이스는 하나의 프레임을 포함하고, 상기 프레임에 광원이 설치되고;상기 이동가능식 육묘 층대 차량은 층판 프레임을 포함하고, 상기 층판 프레임에 적어도 2개의 층판이 설치되고, 상기 층판에 식재판이 설치되고, 층판 프레임 저부에 이동가능식 장치가 설치되고, 상기 층판 프레임의 층판은 육묘 베이스의 광원 위치와 매칭되는 것을 특징으로 하는 다기능 육묘장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

873/1150 Row 873: application_number: 1020190097903, combined_string: invention_title: 수경 재배 장치 abstract: 두릅 또는 엄 나무의 생산을 균일하게 하기 위하여 묘목 대를 일정 기간 동안 냉동 창고에 보관한 후 18℃ 내지 20℃의 온도 및 60%의 습도로 유지된 삼중 하우스에서 물 안개를 분무하면서 재배하여 상품성이 좋은 두릅을 재배하는 수경 재배 장치가 제공된다. 수경 재배 장치는 일정 길이를 갖는 두릅 묘목 대를 다수 획득하여 일정 온도에서 일정 기간 동안 보관한 다수의 묘목 대를 수용하여 재배하는 다수의 재배 틀; 상기 다수의 재배 틀을 각각 둘러싸서 상기 지면과 사이에 작물 재배 공간을 형성하고 상호 인접하게 위치하는 다수의 기본 비닐 하우스; 상기 다수의 기본 비닐 하우스의 상부를 둘러싸는 적어도 하나의 추가 비닐 하우스; 상기 다수의 기본 비닐 하우스 각각의 상단에 일정 거리 간격으로 설치되어 상기 재배 틀에 수용된 다수의 묘목 대에 물을 안개 분무하는 다수의 제1 물 안개 분무기; 상기 다수의 재배 틀 아래 지면에 위치하여 상기 작물 재배 공간의 온도를 일정 온도로 가열하는 난방부; 및 상기 작물 재배 공간의 온도 및 습도가 일정한 범위로 유지하도록 하는 상기 다수의 제1 분무기 및 상기 난방부의 동작을 제어하는 제어부를 포함한다. claims: 일정 길이를 갖는 두릅 묘목 대를 다수 획득하여 일정 온도에서 일정 기간 동안 보관한 다수의 묘목 대를 수용하여 재배하는 다수의 재배 틀;상기 다수의 재배 틀을 각각 둘러싸서 지면과 사이에 작물 재배 공간을 형성하고 상호 인접하게 위치하는 다수의 기본 비닐 하우스; 상기 다수의 기본 비닐 하우스의 상부를 둘러싸는 적어도 하나의 추가 비닐 하우스;상기 다수의 기본 비닐 하우스 각각의 상단에 일정 거리 간격으로 설치되어 상기 재배 틀에 수용된 상기 다수의 묘목 대에 물을 안개 분무하는 다수의 제1 물 안개 분무기; 및상기 다수의 재배 틀 아래 지면에 위치하여 상기 작물 재배 공간의 온도를 일정 온도로 가열하는 난방부;상기 작물 재배 공간의 온도 및 습도가 18℃ 내지 20℃ 및 60%로 각각 유지하도록 하는 상기 다수의 제1 분무기 및 상기 난방부의 동작을 제어하는 제어부; 및1년 동안 자라 1,500mm 내지 2,000mm 길이의 묘목에서 순이 12개 내지 16개로 순 위로 절단 등분한 길이 100 mm 내지 130 mm의 묘목 대를 다수 획득하여 0℃에서 3일 내지 5일 동안 보관하는 냉동 창고를 포함하며,상기 다수의 재배 틀은 각각하단이 상기 지면에 닿고 일정 간격을 두고서 대면하는 폭 1,000mm이고 높이가 900mm인 한 쌍의 기둥;상기 한 쌍의 기둥을 덮도록 설치되어 묘목 대가 수직으로 관통하여 형성되는 그물망;상기 한 쌍의 기둥의 상단으로부터 90 mm의 아래 위치에 상기 그물망에 대해 수평으로 설치되는 철망; 및상기 철망을 덮는 부직포를 포함하며,상기 난방부는 상기 다수의 재배 틀 아래에 매설되어 내부에 난방수가 순환하는 난방 파이프; 및상기 난방 파이프를 통하여 순환하는 상기 난방수를 가열하여 순환하는 전기 보일러를 포함하는 수경 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

874/1150 Row 874: application_number: 1020190097869, combined_string: invention_title: 딸기육묘 재배포트용 흙 공급기 abstract: 본 발명은 딸기육묘 재배포트용 흙 공급기에 관한 것으로, 그 구성은 적어도 하나 이상의 딸기육묘 재배포트의 상부에 적층 배치되는 것으로, 내부에 상기 딸기육묘 재배포트의 각 포트로 공급될 흙이 수용되는 공간이 형성되며, 상부는 개방되는 공급프레임;과, 상기 공급프레임의 하부에 위치되는 상기 딸기육묘 재배포트의 각 포트와 연통되게 형성되어 상기 공급프레임에 수용되는 흙은 상기 포트로 안내하는 것으로, 상기 공급프레임 상에 형성되는 다수의 공급구멍;으로 구성된 것을 특징으로 하는 것으로서, 다수의 딸기육묘 재배포트의 상부에 공급프레임을 적층 배치하고, 그 적층된 공급프레임으로 흙을 투입하여 공급프레임에 형성되는 공급구멍을 통해 다수의 딸기육묘 재배포트의 각 포트로 흙이 간편히 공급 충진되도록 함으로, 작업자는 다수의 딸기육묘 재배포트에 흙을 충진하는 작업에 소요되는 시간 및 인력을 종래의 작업방식에 대비하여 대폭 절감할 수 있어 딸기의 효율적인 재배를 유도할 뿐만 아니라, 공급프레임 내부로 흙이 수용되는 구조로 인해 고가의 흙이 외부로 이탈 유실되는 것을 최소화하여 고가인 흙의 경제적인 사용을 유도할 수 있는 효과가 있다.또한, 공급프레임에 연장 형성되는 보관프레임과 가이드 편을 통해 다른 딸기육묘 재배포트로 공급프레임의 원활한 이동을 유도하여 공급프레임을 통한 딸기육묘 재배포트의 흙 충진 작업이 연속적으로 용이하게 수행되도록 하는 효과가 있다. claims: 적어도 하나 이상의 딸기육묘 재배포트(1)의 상부에 적층 배치되는 것으로, 내부에 상기 딸기육묘 재배포트(1)의 각 포트(1a)로 공급될 흙이 수용되는 공간이 형성되며, 상부는 개방되는 공급프레임(10); 및상기 공급프레임(10)의 하부에 위치되는 상기 딸기육묘 재배포트(2)의 각 포트(1a)와 연통되게 형성되어 상기 공급프레임(10)에 수용되는 흙은 상기 포트(1a)로 안내하는 것으로, 상기 공급프레임 상에 형성되는 다수의 공급구멍(20);을 포함하여 구성되되,상기 공급구멍(20)의 직경(D1)은 상기 포트(1a)의 직경(D2)보다 작게 형성되는 것을 특징으로 하는 딸기육묘 재배포트용 흙 공급기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

875/1150 Row 875: application_number: 1020190096531, combined_string: invention_title: 모세관작용의 재배판을 가진 새싹의 제베기 abstract: 본 발명은 모세관작용의 재배판을 가진 새싹의 재배기에 관한 것으로 다수의 섬유가닥을 접합제와 함께 압착하여 일정한 두께와 넓이를 가진 판체를 새싹의 재배판으로 하고 상기 재배판에 식물의 영양소와 미생물의 살균기능이 있는 특정 양액(nutrion liqid)을 도포한 다음 재배기의 수조에 담긴 물위에 띄우고 상기 재배판에 재배할 종자를 조밀하게 파종하면 재배판의 모세작용으로 작물에 수분이 공급되어, 별도의 동력을 사용하는 수분의 공급수단이 없이, 파종한 싸앗을 새싹작물로 재배할 수 있게 된 것이다.본 발명에 의하면, 새싹의 재배기에 의해 새싹을 재배할 때 재배판에 식물의 무기질 영양소와 살균기능이 있는 양액을 도포하였기 때문에 상기 재배판에 파종된 씨앗이 청정 환경에서 양호하게 성장하여 3~4일정도 재배하면 수확이 가능하고 청정식품으로 식단에 제공할 수 있을 뿐 아니라, 식물에는 아연이나 바나듐과 같은 특정의 지표성분을 함유할 수 있어 환자의 맞춤형 보조식품으로 유용하게 제공할 수 있다. claims: 작물을 재배할 물이 담기는 수조와 덮개로 된 새싹 재배기에 있어서, 다수의 섬유가닥을 접합제와 함께 압착하여 된 일정한 두께와 넓이를 가진 판체를 새싹의 재배판으로 하고 상기 재배판을 상기 수조에 담긴 물위에 띄우고 상기 재배판 위에 씨앗을 파종하여 재배판의 모세관작용으로 수분이 공급되어 재배하게 구성된 것을 특징으로 하는 모세관작용의 재배판을 가진 새싹의 재배기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

876/1150 Row 876: application_number: 1020190094436, combined_string: invention_title: 종자 살균 장치 abstract: 본 발명은 간단한 구조에 의해 모종삼(묘삼)을 비롯한 각종 식물의 종자에 함유된 이물질을 제거하고 확실하게 살균 처리함으로써 이들 종자가 부패하는 것을 방지하고 장기간 보관이 가능하도록 한 종자 살균 장치에 관한 것이다.본 발명의 종자 살균 장치는 망상 또는 다공상의 벨트로 이루어져서 종자를 탑재한 채로 이동하는 컨베이어 벨트; 컨베이어 벨트의 종자 반입부 측에 설치되고, 세척수, 세척수와 공기 혼합물 또는 공기를 분사하여 종자에 묻은 유해 물질을 제거하는 이물질 제거부; 상온 또는 그 이상의 공기를 송풍하여 이물질 제거부를 거친 종자에 함유된 수분을 건조하는 종자 건조부 및 컨베이어 벨트의 상측 및 하측에 각각 설치되고. 종자 건조부를 거친 종자에 자외선이나 플라즈마를 조사하여 종자에 묻은 세균을 죽이는 종자 살균부를 포함하여 이루어진다.전술한 구성에서, 종자의 종류에 따라 컨베이어 벨트의 속도, 세척수나 공기의 분사 압력을 조절할 수 있다. 상기 종자는 묘삼이다. claims: 망상 또는 다공상의 벨트로 이루어져서 종자를 탑재한 채로 이동하는 컨베이어 벨트;컨베이어 벨트의 종자 반입부 측에 설치되고, 세척수, 세척수와 공기 혼합물 또는 공기를 분사하여 종자에 묻은 유해 물질을 제거하는 이물질 제거부;상온 또는 그 이상의 공기를 송풍하여 이물질 제거부를 거친 종자에 함유된 수분을 건조하는 종자 건조부 및컨베이어 벨트의 상측 및 하측에 각각 설치되고. 종자 건조부를 거친 종자에 자외선이나 플라즈마를 조사하여 종자에 묻은 세균을 죽이는 종자 살균부를 포함하여 이루어진 종자 살균 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

877/1150 Row 877: application_number: 1020190093747, combined_string: invention_title: 육묘 재배장치 abstract: 본 발명은 육묘 재배장치에 대한 것으로서, 더욱 상세하게는 모종을 태양광을 골고루 노출시킬 수 있을 뿐만 아니라 공간활용을 높일 수 있는 육묘 재배장치에 대한 것이다.본 발명에 따른 육묘 재배장치는 재배수단 및 복수의 프레임수단을 포함한다. 상기 재배수단은 복수의 장착바와, 모종을 키울 수 있게 상기 모종을 수용할 수 있으며 상기 장착바에 장착가능한 모종받침대를 구비한다. 복수의 상기 프레임수단은 기초프레임과, 상기 기초프레임에 수직으로 장착된 체인과, 상기 체인을 따라 일정한 간격 이격하여 상기 장착바의 일단을 탈착하게 결합시킬 수 있는 고정부와, 상기 장착바가 상하로 회전되도록 상기 체인을 회전시키기 위한 구동부와, 상기 기초프레임을 이동시킬 수 있게 상기 기초프레임의 하단에 장착된 바퀴를 구비하여 상기 장착바의 양단을 지지하도록 일정 간격 이격하여 서로 마주본다. 이 경우 상기 장착바가 상기 재배수단에서 분리되면 상기 복수의 프레임수단 사이에 이격 간격이 없도록 상기 복수의 프레임수단을 이동하여 붙일 수 있다.본 발명에 의하면 육묘 재배장치가 사용되지 아니할 경우 장착바를 고정부에서 분리하여 복수의 프레임수단을 서로 모을 수 있다. 이 경우 육묘 재배장치의 부피를 줄일 수 있으므로 공간을 덜 차지하므로 공간활용도를 높일 수 있 claims: 복수의 장착바와, 모종을 키울 수 있게 상기 모종을 수용할 수 있으며 상기 장착바에 장착가능한 모종받침대를 구비하는 재배수단과,기초프레임과, 상기 기초프레임에 수직으로 장착된 체인과, 상기 체인을 따라 일정한 간격 이격하여 상기 장착바의 일단을 탈착하게 결합시킬 수 있는 고정부와, 상기 장착바가 상하로 회전되도록 상기 체인을 회전시키기 위한 구동부와, 상기 기초프레임을 이동시킬 수 있게 상기 기초프레임의 하단에 장착된 바퀴를 구비하여 상기 장착바의 양단을 지지하도록 일정 간격 이격하여 마주보는 복수의 프레임수단을 포함하며,상기 장착바가 상기 재배수단에서 분리되면 상기 복수의 프레임수단 사이에 이격 간격이 없도록 상기 복수의 프레임수단을 이동하여 붙일 수 있는 것을 특징으로 하는 육묘 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

878/1150 Row 878: application_number: 1020190092866, combined_string: invention_title: 유용성분을 향상시키는 새싹보리의 재배방법 및 새싹보리의 유용성분 추출 방법 abstract: 본 발명은 유용성분을 향상시키는 새싹보리의 재배방법 및 새싹보리의 유용성분 추출 방법에 관한 것이다.본 발명은 페드리 디쉬(petri dish)에 새싹보리 씨앗을 담아 배양시키는 배양단계; 상기 배양단계에 의해 배양된 새싹보리 씨앗을 파종하는 파종단계; 새싹보리 씨앗이 파종된 공간의 온도를 일정하게 유지한 후, 영양분이 포함된 수소수를 공급하는 수소수 공급단계; 상기 새싹보리 씨앗이 파종된 공간으로 광원을 제공하는 광원 제공단계; 및 10~15cm로 성장한 새싹보리를 채취하는 단계;를 포함하는 새싹보리의 재배방법을 통해 재배된 유용성분이 향상된 새싹보리와 에탄올을 아임계 챔버에 투입하는 단계; 상기 아임계 챔버를 가열하여 고온 고압의 조건을 형성하는 단계; 상기 아임계 챔버를 회전시켜 원심분리 방식으로 상기 새싹보리로부터 유용성분이 포함된 액상 시료를 추출하는 단계; 및 상기 액상 사료를 추출 시료 수집조로 이송시켜 새싹보리의 유용성분에 대한 추출물을 추출하는 단계;를 포함하는 유용성분을 향상시키는 새싹보리의 재배방법 및 새싹보리의 유용성분 추출 방법을 제공한다. claims: 페드리 디쉬(petri dish)에 새싹보리 씨앗을 담아 배양시키는 배양단계; 상기 배양단계에 의해 배양된 새싹보리 씨앗을 파종하는 파종단계; 새싹보리 씨앗이 파종된 공간의 온도를 일정하게 유지한 후, 영양분이 포함된 수소수를 공급하는 수소수 공급단계; 상기 새싹보리 씨앗이 파종된 공간으로 광원을 제공하는 광원 제공단계; 및 10~15cm로 성장한 새싹보리를 채취하는 단계;를 포함하는 유용성분을 향상시키는 새싹보리의 재배방법.유용성분이 향상된 새싹보리를 이용한 새싹보리의 유용성분 추출방법에 있어서, 상기 새싹보리와 에탄올을 아임계 챔버에 투입하는 단계; 상기 아임계 챔버를 가열하여 고온 고압의 조건을 형성하는 단계; 상기 아임계 챔버를 회전시켜 원심분리 방식으로 상기 새싹보리로부터 유용성분이 포함된 액상 시료를 추출하는 단계; 및 상기 액상 사료를 추출 시료 수집조로 이송시켜 새싹보리의 유용성분에 대한 추출물을 추출하는 단계;를 포함하는 새싹보리의 유용성분 추출방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

879/1150 Row 879: application_number: 1020190093223, combined_string: invention_title: 스마트 공정육묘 통합관리시스템 abstract: 본 발명의 일 실시 예에 따른 스마트 공정육묘 통합관리시스템은 적어도 하나 이상의 모종이 이송트레이에 담겨진 상태로 육묘 공정이 수행되고, 육묘데이터가 획득되는 스마트팜 및 스마트팜에서 획득된 육묘데이터가 수집되어 처리되는 관리서버가 포함되고, 관리서버에서는 수집된 육묘데이터에 기초하여 이송트레이의 공정 간 이동시점이 예측될 수 있다. claims: 스마트 공정육묘 통합관리시스템에 있어서,적어도 하나 이상의 모종이 이송트레이에 담겨진 상태로 육묘 공정이 수행되고, 육묘데이터가 획득되는 스마트팜; 및상기 스마트팜에서 획득된 육묘데이터가 수집되어 처리되는 관리서버가 포함되고,상기 관리서버에서는 상기 수집된 육묘데이터에 기초하여 상기 이송트레이의 공정 간 이동시점이 예측되는 스마트 공정육묘 통합관리시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

880/1150 Row 880: application_number: 1020190093445, combined_string: invention_title: 열매 씨앗 적출 장치 abstract: 본 발명은 대추나 매실의 씨앗을 손쉽게 적출시키기 위한 장치로서, 보다 구체적으로 본 발명은 열매의 씨앗을 적출하기 위한 장치로서, 몸체부, 상기 몸체부의 일단에 구비되어 열매를 올려놓을 수 있도록 형성된 열매 트레이, 상기 몸체부와 회동결합되는 누름봉, 및 상기 누름봉의 일단에 결합되어 상기 열매로부터 씨앗을 적출하기 위한 적출칼날을 포함하되, 상기 누름봉이 회동됨에 따라 일정 경로를 따라 이동되는 적출칼날이 상기 열매에 꽂히는 형태로 상기 씨앗을 도려내어 적출하는 것을 특징으로 하는, 열매 씨앗 적출 장치에 관한 것이다. claims: 열매의 씨앗을 적출하기 위한 장치로서,몸체부;상기 몸체부의 일단에 구비되어 열매를 올려놓을 수 있도록 형성된 열매 트레이;상기 몸체부와 회동결합되는 누름봉; 및상기 누름봉의 일단에 결합되어 상기 열매로부터 씨앗을 적출하기 위한 적출칼날을 포함하되,상기 누름봉이 회동됨에 따라 일정 경로를 따라 이동되는 적출칼날이 상기 열매에 꽂히는 형태로 상기 씨앗을 도려내어 적출하는 것을 특징으로 하는,열매 씨앗 적출 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

881/1150 Row 881: application_number: 1020210052534, combined_string: invention_title: 녹용유래세포 배양액을 이용한 수경재배 방법 abstract: 본 발명은 녹용유래세포 배양액을 함유하는 재배수에서 식물 또는 식물 종자를 재배하는 것을 특징으로 하는 식물의 수경재배 방법에 관한 것으로, 본 발명에 따라 녹용유래세포 배양액을 재배수로 사용하여 식물을 재배하는 경우, 성장촉진제나 항생제 등의 사용없이도 병해없이 식물을 재배할 수 있어, 안전한 식용작물을 재배할 수 있는 효과가 있다. claims: 식물 수경 재배 방법에 있어서,투관침 또는 외과적 방법으로 획득된 녹용유래세포를 기본배지에서 배양하여 녹용유래세포 배양액을 수득하고, 수득된 배양액을 양액에 첨가하여 식물의 재배 과정에서 주입하는 것을 특징으로 하는 식물 수경 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

882/1150 Row 882: application_number: 1020210025496, combined_string: invention_title: 수경 재배 포트 abstract: 본 실시예들은 수경 재배 포트에 관한 것이다. 수경 재배 포트는 액체를 유통시키는 본체부, 본체부의 위에 위치하고, 제 1 홀을 포함하는 덮개부; 및 덮개부에 포함된 제 1 홀의 아래에 위치하는 필터를 결합하는 필터 결합부를 포함할 수 있다. claims: 황토, 폴리프로필렌(polypropylene) 및 송진을 포함하는 물질로 형성되는 수경 재배 포트로서,액체를 유통시키는 본체부;상기 본체부의 위에 위치하고, 제 1 홀을 포함하는 덮개부; 및상기 덮개부에 포함된 제 1 홀의 아래에 위치하는 필터를 결합하는 필터 결합부를 포함하되,상기 필터 결합부는,상기 덮개부의 아래에 위치하는 필터 결합부의 상부;상기 필터 결합부의 상부로부터 일정 간격 이격된 필터 결합부의 하부;상기 필터 결합부의 상부와 상기 필터 결합부의 하부 사이에 위치하는 필터 결합부의 측부;상기 필터 결합부의 상부, 상기 필터 결합부의 측부 및 상기 필터 결합부의 하부를 관통하는 제 4 홀; 및 상기 필터 결합부의 측부와 상기 제 4 홀을 연결하는 적어도 하나의 제 5 홀을 포함하고,상기 제 5 홀은,필터 결합부의 측부 일부분과 제 4 홀 일부분을 수평 방향으로 관통하여 형성된 관통홀이고, 상기 필터 결합부의 상부에서 상기 필터 결합부의 하부까지 연장되어 형성되며,상기 필터 결합부의 측부는, 테이퍼 형상이고,상기 황토, 폴리프로필렌 및 송진은, 수분이 없는 상태에서 혼합되며,상기 황토는 80 중량%이고, 상기 폴리프로필렌은 15 중량%이며, 상기 송진은 5 중량%인 수경 재배 포트., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

883/1150 Row 883: application_number: 1020210024308, combined_string: invention_title: 식물재배시스템의 지지플레이트 abstract: 본 발명은 재배 환경의 인공적인 제어에서 유지 전력이 감소되고 다품종의 식물 각각에 요구되는 재배 환경을 만족할 수 있는 식물재배시스템의 지지플레이트를 제공하기 위하여, 광을 조사하는 광원의 하측에서 화분을 지지하는 지지플레이트에 있어서, 적어도 하나의 상기 화분이 안착되는 플레이트 본체 및 상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함한다. claims: 광을 조사하는 광원의 하측에서 화분을 지지하는 지지플레이트에 있어서,적어도 하나의 상기 화분이 안착되는 플레이트 본체; 및상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함하는 지지플레이트.제1 항에 있어서,상기 지지플레이트는 온실 내부에 배치되고.상기 광원은 상기 지지플레이트의 상부에서 상기 온실 내부에 지지되는 것을 특징으로 하는 지지플레이트.제5 항에 있어서,상기 온실은상기 화분을 지지하고 있는 지지플레이트를 다층으로 지지하는 다층 생육구조물과,상기 생육구조물의 적어도 일부를 감싸도록 배치되어 상기 온실 내부의 온기 또는 냉기가 온실로부터 배출되는 것을 저지하는 외벽과,상기 온실 내부에 배치되어 상기 온실 내부의 환경을 제어하는 생육환경 유지장치를 포함하는 것을 특징으로 하는 지지플레이트., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

884/1150 Row 884: application_number: 1020210024309, combined_string: invention_title: 식물재배시스템의 온실 abstract: 본 발명은 재배 환경의 인공적인 제어에서 유지 전력이 감소되고 다품종의 식물 각각에 요구되는 재배 환경을 만족할 수 있는 식물재배시스템의 온실을 제공하기 위하여, 적어도 하나의 화분을 지지하는 지지플레이트 및 상기 지지플레이트를 지지하는 다층 생육구조물 및 상기 생육구조물의 적어도 일부를 감싸도록 배치되어 내부의 온기 또는 냉기가 외부로 배출되는 것을 저지하는 외벽 및 상기 지지플레이트 상부에 배치되어 광을 조사하는 광원을 포함하고, 상기 지지플레이트는 상기 화분이 안착되는 플레이트 본체와, 상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함한다. claims: 적어도 하나의 화분을 지지하는 지지플레이트;상기 지지플레이트를 지지하는 다층 생육구조물;상기 생육구조물의 적어도 일부를 감싸도록 배치되어 내부의 온기 또는 냉기가 외부로 배출되는 것을 저지하는 외벽; 및상기 지지플레이트 상부에 배치되어 광을 조사하는 광원을 포함하고,상기 지지플레이트는상기 화분이 안착되는 플레이트 본체와,상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함하는 온실.적어도 하나의 화분을 지지하는 지지플레이트;상기 지지플레이트를 지지하는 다층 생육구조물;상기 생육구조물의 적어도 일부를 감싸도록 배치되어 내부의 온기 또는 냉기가 외부로 배출되는 것을 저지하는 외벽; 및상기 지지플레이트 상부에 배치되어 광을 조사하는 광원을 포함하고,상기 지지플레이트는상기 화분이 안착되는 플레이트 본체와,상기 플레이트 본체의 상부에 균일하게 형성되며 외부로부터 공급되는 미생물이 번식하는 환경을 조성하는 번식홈을 포함하는 생육장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

885/1150 Row 885: application_number: 1020210007302, combined_string: invention_title: 식물 수경재배 시스템 abstract: 본 발명은 식물 수경재배 시스템에 관한 것으로, 컨테이너 하우징; 상기 컨테이너 하우징의 내부에 배치되되, 가로방향, 세로방향 및 높이방향으로 배치되어 상호 연결되는 복수 개의 프레임들에 의해 식물을 재배할 수 있는 하나 또는 복수 개의 재배영역을 형성하는 재배 랙 유닛; 상기 재배 랙 유닛의 길이방향을 따라 연속적으로 배치되도록 복수 개 구비되며, 상기 재배 랙 유닛에 인입되어 상기 재배영역에 배치되거나 상기 재배 랙 유닛에서 인출할 수 있는 팔레트 유닛; 상기 팔레트 유닛에 배치되며, 상기 식물이 성장할 수 있는 공간이 형성된 식물 성장 파우치; 상기 재배 랙 유닛의 일측 또는 타측에 구비되어 상기 팔레트 유닛과 연결되며, 상기 팔레트 유닛으로 물을 공급하여 상기 팔레트의 온도를 조절하는 팔레트 온도조절 유닛; 및 상기 재배 랙 유닛의 일측 또는 타측에 구비되어 상기 팔레트 유닛의 상측에서 상기 팔레트 유닛에 배치된 상기 식물 성장 파우치로 양액을 공급하는 양액 공급 유닛을 포함한다. claims: 컨테이너 하우징;상기 컨테이너 하우징의 내부에 배치되되, 가로방향, 세로방향 및 높이방향으로 배치되어 상호 연결되는 복수 개의 프레임들에 의해 식물을 재배할 수 있는 하나 또는 복수 개의 재배영역을 형성하는 재배 랙 유닛;상기 재배 랙 유닛의 길이방향을 따라 연속적으로 배치되도록 복수 개 구비되며, 상기 재배 랙 유닛에 인입되어 상기 재배영역에 배치되거나 상기 재배 랙 유닛에서 인출할 수 있는 팔레트 유닛;상기 팔레트 유닛에 배치되며, 상기 식물이 성장할 수 있는 공간이 형성된 식물 성장 파우치;상기 재배 랙 유닛의 일측 또는 타측에 구비되어 상기 팔레트 유닛과 연결되며, 상기 팔레트 유닛으로 물을 공급하여 상기 팔레트의 온도를 조절하는 팔레트 온도조절 유닛; 및상기 재배 랙 유닛의 일측 또는 타측에 구비되어 상기 팔레트 유닛의 상측에서 상기 팔레트 유닛에 배치된 상기 식물 성장 파우치로 양액을 공급하는 양액 공급 유닛을 포함하되,상기 재배 랙 유닛은, 상기 재배 랙 유닛의 길이방향을 따라 상기 재배영역을 관통하며 배치되는 레일 프레임과, 상기 레일 프레임 상에 설정 간격 이격되게 설치되어 상기 팔레트 유닛이 상기 재배 랙 유닛의 길이방향을 따라 왕복 슬라이딩 이동할 수 있게 하는 복수 개의 롤러를 포함하고; 상기 팔레트 유닛은, 평면의 플레이트 형태이며, 상기 식물 성장 파우치가 배치될 수 있도록 가로방향 및 세로방향을 따라 설정 간격만큼 이격되는 복수 개의 홀들이 형성된 배치 플레이트와, 상기 배치 플레이트의 상면 또는 하면에 구비되며, 상기 팔레트 유닛으로 공급되는 상기 양액 또는 물을 흡수하여 저장하는 방수 패브릭과, 상기 배치 플레이트의 가로방향 및 세로방향을 따라 배치되어 상기 배치 플레이트를 둘러싸며 상기 배치 플레이트와 연결되는 다수 개의 팔레트 프레임과, 상기 배치 플레이트의 가로방향을 따라 배치되는 상기 팔레트 프레임의 내부에 구비되며, 상기 팔레트 유닛이 설정 온도 범위를 유지할 수 있도록 상기 팔레트 온도조절 유닛에서 공급되는 물이 유동되는 유로 파이프 및, 상기 배치 플레이트의 세로방향을 따라 배치되는 상기 팔레트 프레임에 하나 또는 복수 개 구비되며, 상기 재배 랙 유닛의 길이방향을 따라 연속적으로 상기 팔레트 유닛이 배치될 때 이웃하는 팔레트 유닛들을 서로 연결시키는 자성부재를 포함하며;상기 식물 성장 파우치는, 물 또는 양액을 흡수할 수 있는 소재로 이루어지고, 일측은 차폐되고 타측은 개방되어 있으며, 상기 식물 또는 상기 식물의 씨앗이 저장될 수 있도록 공간을 형성하고 상기 배치 플레이트에 형성된 홀에 삽입되는 식물 저장부와, 상기 식물 저장부의 타측으로부터 연장되어 상기 식물 성장 파우치가 상기 팔레트 유닛에 배치될 때 상기 식물 저장부를 지지하는 날개부를 포함하는 것을 특징으로 하는 식물 수경재배 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

886/1150 Row 886: application_number: 1020200185283, combined_string: invention_title: 특수목 재배용 가이드 케이싱 abstract: 본 발명은 특수목이나 정원수(庭園樹) 등으로 재배하는 식물의 줄기를 인위적인 굴절상태로 재배하기 위한 특수목 재배용 가이드 케이싱을 제공코자 하는 것이다.즉, 본 발명은 단면이 반원호 형태이며, 내부에는 굴곡진 유도로(2)가 형성되고, 양 끝단에는 상, 하부 개구부(4)(3)를 갖는 한 쌍의 통체(1)와; 고정클립(21)을 이용하여 분할된 통체(1)를 결속하기 위해 상기 통체(1)의 외측 끝단에 서로 마주보게 형성되는 복수개의 돌출편(5);을 포함하여, 재배식물(T)의 줄기전체를 내부 유도로(2)에 내장한 상태에서 생육재배가 이루어지게 함을 특징으로 한다. 상기 특수목 재배용 가이드 케이싱을 이용하면, 다양한 수형을 갖는 특수목을 신속하고 용이하게 양산 보급할 수 있다는 장점이 있다. claims: 단면이 반원호 형태이며, 내부에는 굴곡진 유도로(2)가 형성되고, 양 끝단에는 상, 하부 개구부(4)(3)를 갖는 한 쌍의 통체(1);고정클립(21)을 이용하여 분할된 통체(1)를 결속하기 위해 상기 통체(1)의 외측 끝단에 서로 마주보게 형성되는 복수개의 돌출편(5);을 포함하여, 재배식물(T)의 줄기전체를 내부 유도로(2)에 내장한 상태에서 생육재배가 이루어지게 하며, 상기 통체(1)는 불투명 합성수지제로 형성하고, 그 길이방향으로 이격되게 배치되는 보조통공(7)을 천공하며, 상기 보조통공(7)에는 온도, 습도, ph, 전기전도도 및 압력 중 어느 하나 이상의 정보를 검출하기 위한 센서를 결합하여 재배식물의 성장 상태를 원격 검출할 수 있도록 구성됨을 특징으로 하는 특수목 재배용 가이드 케이싱., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

887/1150 Row 887: application_number: 1020200165414, combined_string: invention_title: 수중 재배 및 토양 재배가 가능한 스마트 식물 재배기 abstract: 본 발명에 따르면, 수경재배가 가능하도록 물을 저장할 수 있는 수조를 포함하는 수경재배부 및 토경재배가 가능하도록 내부에 토사를 적재할 수 있는 수용공간을 포함하는 토경재배부를 포함하는 재배부, 재배 작물이 생장할 수 있도록 재배부 일측에 배치되어 재배부 내 재배중인 작물의 광합성에 필요한 광을 조사하는 조명부, 재배부 내 재배중인 식물의 생장에 필요한 수분을 공급하는 토출부, 재배부 내부의 온도, 습도 및 토지의 양분 등을 측정할 수 있는 센서부, 센서부에 의해 측정된 정보를 사용자에게 알릴 수 있도록 측정 정보를 표시하는 디스플레이부, 재배부 내부의 공기를 순환시키는 순환팬 및 스마트 식물 재배기에 필요한 전력을 공급하는 전력부를 포함하는 수경 재배 및 토경 재배가 가능한 스마트 식물 재배기를 제공한다. claims: 수경재배가 가능하도록 물을 저장할 수 있는 수조를 포함하는 수경재배부 및 토경재배가 가능하도록 내부에 토사를 적재할 수 있는 수용공간을 포함하는 토경재배부를 포함하는 재배부; 재배 작물이 생장할 수 있도록 상기 재배부 일측에 배치되어 상기 재배부 내 재배중인 작물의 광합성에 필요한 광을 조사하는 조명부; 상기 재배부 내 재배중인 식물의 생장에 필요한 수분을 공급하는 토출부; 상기 재배부 내부의 온도, 습도 및 토지의 양분을 측정할 수 있는 센서부; 상기 센서부에 의해 측정된 정보를 사용자에게 알릴 수 있도록 측정 정보를 표시하는 디스플레이부;상기 재배부 내부의 공기를 순환시키는 순환팬; 및 스마트 식물 재배기에 필요한 전력을 공급하는 전력부;를 포함하며, 상기 조명부는 재배중인 식물의 종류에 따라 상기 재배부에 조사되는 광량을 조절할 수 있는 광(光)조절부 ; 및 재배중인 식물의 종류에 따라 상기 재배부에 공급되는 수량을 조절할 수 있는 수(水)조절부를 포함하고상기 광조절부 또는 상기 수조절부는유체가 통과할 수 있도록 제1천공홈, 상기 제1천공홈보다 큰 직경을 가지는 제2천공홈 및 상기 제2천공홈보다 큰 직경을 가지는 제3천공홈을 포함하는 천공홈; 및 상기 천공홈 일측에 배치되어 상기 천공홈을 선택적으로 개폐할 수 있도록 패널형상으로 형성되는 개폐부재 를 포함하는 것을 특징으로 하는 수경 재배 및 토경 재배가 가능한 스마트 식물 재배기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

888/1150 Row 888: application_number: 1020200151216, combined_string: invention_title: 식물 재배용 유리블럭 abstract: 본 발명은 식물 재배용 유리블럭에 관한 것으로, 보다 상세하게는, 채광이 어려운 실내에서 식물의 광합성을 유도하도록 인위적인 광을 제공하고, 동시에, 식물을 향해 적절한 바람을 제공하여 식물에서 방출되는 음이온, 피톤치드 등의 유효성분을 주변으로 비산시켜 실내 공기질을 개선할 수 있으며, 식물 자체가 바람에 흩날릴 수 있도록 해 식물의 생장 환경을 보다 자연환경에 가깝게 조성할 수 있어 식물의 성장을 보다 촉진시키고 올바른 성장을 유도할 수 있으며, 특히, 야간 시 뛰어난 시인성 확보와 함께 식물의 입체감 및 표현력을 증대시켜 미감 향상, 은은한 실내 분위기 조성 등 실내 인테리어 효과를 누릴 수 있도록 하는 식물 재배용 유리블럭에 관한 것이다. claims: 복수의 열과 행으로 적층 구성되어 벽체 구조물을 형성하는 식물 재배용 유리블럭에 있어서,투명 또는 반투명 유리재질의 사각 틀 형태로 이루어지며 전후 방향으로 거치공이 관통 형성되고, 거치공 주변으로는 서로 수직으로 접하는 4 개의 내벽이 형성되되, 상기 내벽은 각각 거치공의 상부를 구성하는 상벽, 거치공의 하부를 구성하는 하벽, 거치공의 좌우 측면을 구성하는 측벽으로 이루어지는 케이스;상기 거치공 내부에 거치되는 투명 또는 반투명 유리재질의 화분;상기 거치공의 내벽에 착탈 가능하게 설치되는 발광모듈;상기 거치공의 내벽에 착탈 가능하게 설치되는 팬모듈;상기 거치공의 내벽에 착탈 가능하게 설치되며 상기 발광모듈 및 팬모듈에 전원을 공급하는 배터리모듈; 및투명 또는 반투명 유리재질로 이루어지며 상기 케이스의 전면과 후면에 각각 좌우 방향으로 가로질러 장착되는 스트랩부;를 포함하며,상기 상벽, 하벽 및 측벽마다 발광모듈, 팬모듈 및 배터리모듈 중 적어도 어느 하나가 설치되는 장착홈이 함몰 형성되고, 각각의 장착홈과 상호 연결되어 장착홈과 함께 내벽 상에 하나의 채널을 구성하며 발광모듈, 팬모듈 및 배터리모듈로부터 연장 형성되는 전선을 수용하는 전선수용홈이 함몰 형성되며,상기 전선수용홈의 전후 폭은 장착홈의 전후 폭보다 좁게 형성되며,상기 팬모듈은 식물의 직상방에서 바람을 제공하도록 상벽에 형성된 장착홈에 설치되며,상기 케이스의 전면과 후면에는 스트랩부의 좌우 양단이 삽입 고정되는 고정구가 형성되며,상기 스트랩부는,하부에 배치된 다른 유리블럭에서부터 자라나는 넝쿨식물의 줄기가 유도되도록 중앙으로 갈수록 케이스에서 점진적으로 멀어지는 호 형태로 만곡되는 밴드부재; 및상기 밴드부재의 좌우 양단에서 하방으로 연장 형성되는 막대 형태로 이루어지며 상기 고정구에 상하로 슬라이딩하여 체결되는 체결부재;를 포함하며,상기 고정구는 케이스의 전면에 상하 방향으로 길게 연장되는 홈 형태의 고정홈 및 상기 고정홈의 전면 하단 일부를 폐쇄하는 고정판을 포함하며,고정홈에 삽입되는 체결부재는 고정판에 의해 하부로 가이드되어 고정홈의 하부에 끼움되는 것을 특징으로 하는 식물 재배용 유리블럭., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

889/1150 Row 889: application_number: 1020200146580, combined_string: invention_title: 식물기반 바이오약품 제조를 위한 식물형질전환이 이루어진 기주식물의 재배방법 abstract: 본 발명의 식물기반 바이오약품 제조를 위한 식물형질전환이 이루어진 기주식물의 재배방법은 습도와 온도 및 이산화탄소의 농도가 조절된 제1 실내생육공간에서 양액과 인조광원을 이용하여 기주식물을 재배하는 기주식물 재배단계; 생산하고자 하는 유전자가 조합된 식물발현벡터를 기주식물로 운반할 아그로박테리움에 주입하는 유전자 운반 매개체 준비단계와, 상기 식물발현벡터가 포함된 상기 아그로박테리움을 함유하는 액상의 침윤액을 준비하는 침윤액 준비단계와; 재배된 기주식물의 잎을 포함한 줄기부를 상기 침윤조에 담그고, 뿌리를 포함한 배지가 진공분위기에 노출된 상태에서 침윤액 내의 상기 아그로박테리움이 상기 기주식물로 전달될 수 있도록 하는 침윤단계와; 상기 침윤이 이루어진 기주식물을 습도와 온도 및 이산화탄소의 농도가 조절된 제2 실내생육공간에서 양액과 인조광원을 이용하여 기주식물을 회복시키는 기주식물회복재배단계를 포함한다. claims: 습도와 온도 및 이산화탄소의 농도가 조절된 제1 실내생육공간에서 양액과 인조광원을 이용하여 기주식물을 재배하는 기주식물 재배단계: 생산하고자 하는 유전자가 조합된 식물발현벡터를 기주식물로 운반할 아그로박테리움에 주입하는 유전자 운반 매개체 준비단계와, 상기 식물발현벡터가 포함된 상기 아그로박테리움을 함유하는 액상의 침윤액을 준비하는 침윤액 준비단계와; 재배된 기주식물의 잎을 포함한 줄기부를 침윤조에 담그고, 뿌리를 포함한 배지가 진공분위기에 노출된 상태에서 침윤액 내의 상기 아그로박테리움이 상기 기주식물로 전달될 수 있도록 하는 침윤단계와;상기 침윤이 이루어진 기주식물을 습도와 온도 및 이산화탄소의 농도가 조절된 제2 실내생육공간에서 양액과 인조광원을 이용하여 기주식물을 회복시키는 기주식물회복재배단계를 포함하며,상기 침윤단계는상기 기주식물을 상기 침윤액에 침지시키기 전 기주식물을 진공분위기에 노출시키는 기주식물진공노출단계와,상기 기주식물을 상기 침윤액에 침지시키기 후 진공을 해지하여 기주식물에 압력이 작용하도록하는 기주식물가압단계를 구비한 것을 특징으로 하는 식물기반 바이오약품 제조를 위한 식물형질전환이 이루어진 기주식물의 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

890/1150 Row 890: application_number: 1020200129910, combined_string: invention_title: 원예용 친환경 해충 퇴치제의 제조방법 및 이에 의해 제조된 원예용 친환경 해충 퇴치제 abstract: 본 발명은 원예용 친환경 해충 퇴치제의 제조방법 및 이에 의해 제조된 원예용 친환경 해충 퇴치제에 관한 것이다.본 발명에 따른 재료들을 준비하는 천연 재료 준비 단계(S100); 상기 준비된 재료들을 혼합한 후 추출하여 천연 추출액을 제조하고, 상기 천연 추출액 제조시 분리된 고형분을 건조하고 분쇄하여 분말화함으로써 천연 분말을 제조하는 천연 추출액 및 천연 분말 제조 단계(S200); 상기 천연 추출액 및 천연 분말과 혼합되는 토양 개질제를 제조하는 토양 개질제 제조 단계(S300); 및 상기 천연 추출액, 천연 분말 및 토양 개질제를 혼합하여 해충 퇴치제를 제조하는 혼합 단계(S400)를 포함한다.상기한 구성에 의해 본 발명에 따른 원예용 친환경 해충 퇴치제의 제조방법은 인체에 해가 없으면서 해충 기피 효과가 우수하고 원예용 작물과 토양에 영양분을 공급함과 동시에 원예용 작물에 해충이 모이거나 번식하는 것을 방지할 수 있는 원예용 친환경 해충 퇴치제를 제조할 수 있다. claims: 재료들을 준비하는 천연 재료 준비 단계(S100);상기 준비된 재료들을 혼합한 후 추출하여 천연 추출액을 제조하고, 상기 천연 추출액 제조시 분리된 고형분을 건조하고 분쇄하여 분말화함으로써 천연 분말을 제조하는 천연 추출액 및 천연 분말 제조 단계(S200);상기 천연 추출액 및 천연 분말과 혼합되는 토양 개질제를 제조하는 토양 개질제 제조 단계(S300); 및상기 천연 추출액, 천연 분말 및 토양 개질제를 혼합하여 해충 퇴치제를 제조하는 혼합 단계(S400)를 포함하되,상기 천연 추출액 및 천연 분말 제조 단계(S200)에서 상기 준비된 재료들은 편백나무 5 내지 10 중량부, 자귀나무 3 내지 5 중량부, 어성초 2 내지 4 중량부, 박하 1 내지 3 중량부, 제충국 2 내지 4 중량부, 쿠아시아 1 내지 3 중량부, 은행나무 4 내지 6 중량부, 소태나무 0.5 내지 2.5 중량부 및 쇠비름 1 내지 3 중량부의 중량 비율로 혼합되고,상기 천연 추출액은,편백나무, 자귀나무, 어성초, 박하, 제충국, 쿠아시아, 은행나무, 소태나무 및 쇠비름으로 이루어진 재료들을 준비한 후 상기 재료들을 혼합하고, 상기 혼합된 재료들을 130 내지 160℃ 온도의 수증기로 50 내지 100분 동안 가열하여 증숙하며, 상기 증숙된 재료들을 60 내지 80mbar의 압력 및 60 내지 70℃의 온도에서 10 내지 30분 동안 2.0GHz의 마이크로웨이브를 조사함으로써 건조하고, 상기 건조된 재료들 100 중량부에 대해 발효 미생물 배양액 5 내지 10 중량부를 혼합한 후 38 내지 42℃의 온도에서 20 내지 40일 동안 발효를 진행하되, 상기 발효 미생물 배양액은, 세척된 볏짚을 물이 담긴 용기에 넣고 105 내지 110℃의 온도에서 30 내지 50분 동안 삶아 살균하고, 상기 삶아 살균한 후 용기에 남은 물과 볏짚을 자연 냉각하여 고초균 침출수를 얻으며, 상기 볏짚이 침지되어 있는 고초균 침출수를 65 내지 75℃의 온도로 5시간 동안 유지하여 고초균을 증식시키고, 상기 고초균이 증식된 고초균 침출수로부터 볏짚을 분리하여 제거하고, 상기 고초균 침출수만을 105 내지 110℃의 온도에서 30분 동안 삶아 살균한 후 냉각하는 과정을 거쳐 제조되며, 상기 발효된 재료들에서 상기 편백나무, 자귀나무, 어성초, 박하, 제충국, 쿠아시아, 은행나무, 소태나무 및 쇠비름으로 이루어진 재료들에서 생성된 고형분을 제거하여 발효 침출수를 분리하여 제조되고,상기 천연 분말은, 상기 분리된 고형분을 30 내지 40℃의 온도에서 3 내지 5일 동안 건조한 후 분쇄하여 분말화함으로써 제조되며,상기 토양 개질제 제조 단계(S300)에서 상기 토양 개질제는 패각분말 10 내지 20 중량부, 미세 다공체 5 내지 10 중량부, 인산칼륨(K3PO4) 2 내지 6 중량부, 탄산칼륨 3 내지 7 중량부, 마그네사이트 1 내지 5 중량부, 구연산 2 내지 6 중량부, 아인산 1 내지 3 중량부 및 인광석 5 내지 10 중량부의 중량 비율로 혼합한 후 교반하여 제조하며,상기 패각분말은,전복, 굴, 소라, 꼬막, 바지락, 석화 및 조개로 이루어진 군에서 선택된 어느 하나 이상의 패각을 준비한 후 세척하고, 상기 세척된 패각을 제1 분쇄하여 패각 분쇄물을 제조하며, 상기 패각 분쇄물을 10 내지 20분 동안 혼합액에 침지시키되, 상기 혼합액은 질산 0.5 내지 1.5 중량%, 인산염 화합물 1 내지 2 중량% 및 잔량의 정제수로 이루어지고, 상기 인산염 화합물로는 제1 인산나트륨(NaH2PO4), 제2 인산나트륨(Na2HPO4), 제3 인산나트륨(Na3PO4), 제1 인산칼륨(KH2PO4), 제2 인산칼륨(K2HPO4), 제1 인산암모늄((NH4)H2PO4), 제2 인산암모늄((NH4)2HPO4) 및 제3 인산암모늄((NH4)3PO4)으로 이루어진 군에서 선택되는 어느 하나 이상이 사용되며, 상기 패각 분쇄물을 혼합액에서 분리하여 꺼낸 후 상기 패각 분쇄물을 소성로에 투입한 후 1,400 내지 1,600℃의 온도에서 20 내지 60분 동안 가열함으로써 소성하고, 상기 소성된 패각 분쇄물을 입경이 1 내지 10mm가 되도록 제2 분쇄하는 과정을 거쳐 제조되며,상기 미세 다공체는,미연탄소분 10 내지 15 중량부, 플라이애쉬 8 내지 12 중량부, 황토 2 내지 4 중량부 및 준설토 3 내지 7 중량부의 중량 비율로 준비하여 혼합하고, 상기 미연탄소분, 플라이애쉬, 황토 및 준설토 전체 100 중량부에 대하여 물 30 내지 40 중량부의 중량 비율로 준비하며, 상기 미연탄소분, 플라이애쉬, 황토 및 준설토와 물을 혼합하여 혼합물을 제조한 후 성형하여 성형체를 형성하고, 상기 성형체를 가마에서 가열하여 소성하되, 상기 가마는 내부 온도를 400 내지 450℃의 온도로 유지하고, 상기 가마의 내부에 상기 성형체를 투입한 후 1200 내지 1300℃의 온도까지 높이면서 3 내지 5 시간 동안 소성하며, 상기 소성된 성형체를 가마로부터 꺼낸 후 200 내지 250℃의 온도에서 1 내지 3시간 동안 제1 냉각한 후, 30 내지 50℃의 온도에서 10 내지 12시간 동안 제2 냉각하는 과정을 거쳐 제조되고,상기 혼합 단계(S400)에서 상기 해충 퇴치제는 천연 추출액 10 내지 20 중량부, 천연 분말 5 내지 15 중량부 및 토양 개질제 20 내지 30 중량부의 중량 비율로 혼합되어 제조되는 것을 특징으로 하는 원예용 친환경 해충 퇴치제의 제조방법.제 1항의 방법으로 제조된 것을 특징으로 하는 원예용 친환경 해충 퇴치제., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

891/1150 Row 891: application_number: 1020200123708, combined_string: invention_title: 심지를 이용한 관상용 수경식물 재배 키트 abstract: 본 발명은 관상 식물을 수경재배 방식으로 키울 수 있는 수경식물 재배 키트에 관한 것이다. 본 발명은 흡수심지와 흡수원판을 사용하여 흡수성 섬유에 삽입된 씨앗으로 충분한 물이 공급될 수 있는 조건 및 씨앗의 안정적인 고정상태를 유지할 수 있는 구조 개선등을 하였고, 다공성 인공토을 사용하여 건습 및 다습에 상관없이 씨앗의 발아 및 식물이 성장하는데 최적의 환경을 만들어줄 수 있는 새로운 식물 재배 키트를 구현함으로써, 초보자도 쉽고 간편하게 식물을 건강하게 재배할 수 있다. claims: 식물재배부로 물을 공급하는 물공급부(120)와 식물을 지탱하고 생장할 수 있도록 하는 식물 재배부(110)로 구성되며,식물 재배부(110)와 탈부착이 가능하도록 고정틀(115)이 부착되어 있는 물저장부(140)식물 재배부(110)는 상부에서 하부로 갈수록 넓어지는 구조;식물 재배부(110)의 내부에 삽입되어 씨앗에 물을 공급하는 물공급부(120)와 다공성 인공토(130);물공급부(120)의 일부로서, 아크릴섬유 또는 합성섬유 등의 재질을 압축 성형한 것으로 일부분이 식물 재배부(110)의 하부로 노출되어 수분을 흡수하는 천 재질의 흡수심지(121);식물 재배부(110)의 내부에 삽입된 물공급부(120)의 일부로서, 아크릴섬유 또는 합성섬유 등의 재질을 압축 성형한 것으로 흡수심지(121)에 연결된 납작한 원판의 형태의 흡수원판(122);을 포함하는 심지를 이용한 관상용 수경식물 재배 키트, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

892/1150 Row 892: application_number: 1020200120640, combined_string: invention_title: 연통홀이 형성된 단위 보호유닛을 포함하는 천연잔디 보호매트 abstract: 본 발명에 따른 연통홀이 형성된 단위 보호유닛을 포함하는 천연잔디 보호매트는, 천연잔디가 심어진 지면에 설치되어 천연잔디를 보호하는 천연잔디 보호매트에 있어서, 지면으로부터 소정 높이만큼 기립된 지지프레임을 포함하며, 상기 지지프레임의 내측에는 지면에 심어진 천연잔디가 통과하도록 상하 개구된 통과공간이 형성된 단위 보호유닛을 포함하고, 상기 지지프레임에는, 상기 통과공간과 상기 지지프레임의 외측을 서로 연통시키는 연통홀이 형성된다. claims: 천연잔디가 심어진 지면에 설치되어 천연잔디를 보호하는 천연잔디 보호매트로서,지면으로부터 소정 높이만큼 기립된 지지프레임을 포함하며, 상기 지지프레임의 내측에는 지면에 심어진 천연잔디가 통과하도록 상하 개구된 통과공간이 형성된 단위 보호유닛을 포함하되,상기 지지프레임에는상기 통과공간과 상기 지지프레임의 외측을 서로 연통시키는 연통홀이 상기 통과공간의 둘레를 따라 복수 개가 형성되되, 서로 인접한 한 쌍의 상기 연통홀 사이에는 지면에 접촉되는 기립부가 구비되고,천연잔디의 생육 환경을 향상시키기 위해, 상기 기립부의 내부에는 상기 통과공간으로부터 넘친 물 또는 공기가 유동되는 보조공간이 형성되고, 상기 기립부의 둘레에는 상기 보조공간과 상기 기립부의 외측을 서로 연통시켜 상기 보조공간 내의 물 또는 공기를 외측으로 배수하는 보조홀이 형성되는 것을 특징으로 하는,천연잔디 보호매트., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

893/1150 Row 893: application_number: 1020200090454, combined_string: invention_title: 생장점 배양을 이용한 사과 왜성대목 M.9 및 M.26의 바이러스 무병주 생산방법 abstract: 본 발명은 사과 왜성대목 품종인 M.9 또는 M.26의 액아(Axillary bud)로부터 생장점을 채취하고, 채취한 생장점을 BAP(6-benzylaminopurine), IBA(Indole-3-Butyric Acid), 글라이신(Glycine) 및 글루코오스(Glucose)를 포함하는 제1 MS(Murashige and Skoog basal) 배지에 치상하여 신초를 생육하는 단계; 상기 생육된 신초를 BAP, IBA, 글라이신 및 글루코오스를 포함하는 제2 MS 배지에서 배양하여 유식물체로 분화시키는 단계; 상기 유식물체를 IBA(Indole-3-Butyric Acid)를 포함하는 제3 MS 배지에서 배양하여 발근을 유도하는 단계; 및 상기 발근이 유도된 유식물체를 기외순화시키는 단계; 를 포함하는 사과 왜성대목 품종인 M.9 또는 M.26의 바이러스 무병주 생산 방법에 관한 것으로, 본 발명의 생장점배양방법을 이용한 사과 왜성대목 M.9 및 M.26 품종 무독묘 생산방법은 각 배양 단계에 적합한 배지 및 배양 조건을 이용함으로써, 기본 배지에서 배양하는 경우보다 신초 형성율, 신초 생장, 발근율이 우수하고 낮은 갈변율을 보이므로, 본 발명의 무독묘 생산 방법은 사과 왜성대목의 기내 대량증식에 유용하게 사용될 수 있다. claims: 사과 왜성대목 품종인 M.9 또는 M.26의 액아(Axillary bud)로부터 생장점을 채취하고, 채취한 생장점을 BAP(6-benzylamino purine) 0.8 내지 1.2 mg/L, IBA(indole-3-butyric acid) 0.1 내지 0.5 mg/L, 글라이신(Glycine) 2 내지 6 mg/L 및 글루코오스(Glucose) 25 내지 35 g/L를 포함하는 제1 MS(Murashige and Skoog basal) 배지에 치상하여 신초를 생육하는 단계;상기 생육된 신초를 BAP, IBA, 글라이신 및 글루코오스를 포함하는 제2 MS 배지에서 배양하여 유식물체로 분화시키는 단계;상기 유식물체를 IBA(Indole-3-Butyric Acid)를 포함하는 제3 MS 배지에서 배양하여 발근을 유도하는 단계; 및상기 발근이 유도된 유식물체를 기외순화시키는 단계; 를 포함하는 사과 왜성대목 생산방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

894/1150 Row 894: application_number: 1020200085173, combined_string: invention_title: 에너지 절약 및 작물 발육 보조를 위한 수경재배용 설비 시스템 abstract: 본 발명은 작물을 토양없이 배양액을 이용하여 재배하는 수경재배시설에 관한 것으로, 상세하게는, 농가에서 수경재배농법을 이용한 수경재배시설을 통해 작물을 재배할 때 지하자원(수자원)의 고갈로 인한 자연환경의 파괴를 방지하고, 항온과 항습을 위해 소모되는 많은 전기 사용량으로 인한 농가의 경제적인 부담을 줄일 수 있는 에너지 절약 및 작물 발육 보조를 위한 수경재배용 설비 시스템에 관한 것이다. claims: 온실;상기 온실의 내부에 'ㄹ'자 형상으로 수평으로 번갈아가면서 설치되고, 작물이 생육되는 수평배관을 포함하는 수경재배설비;심정용 모터를 통해 수자원으로부터 끌어올려진 물을 집수하여 저장하고, 저장된 물을 메인배관을 통해 상기 수경재배설비의 수평배관으로 공급하는 집수용 물탱크;상기 수평배관의 종단부 배관에 길이 방향으로 복수 개로 배치되어 상기 수평배관의 종단부로 배수되는 물의 수력을 이용하여 전기를 생산하는 발전기;상기 발전기를 통한 전기 생산시 사용되고 남은 잉여수를 저장하는 보조 물탱크;상기 온실에 설치되고, 항습용 모터에 의해 상기 보조 물탱크로부터 끌어올려진 잉여수를 상기 수평배관에서 생육되는 작물을 포함하여 상기 온실의 내부로 분사하는 스프링 쿨러;상기 온실의 내부에 항온 유지용으로 설치된 복수 개의 라디에이터; 상기 라디에이터와 배관을 통해 연결되고, 상기 보조 물탱크에 저장된 잉여수를 공급받고, 상기 발전기에서 생산된 전기를 공급받아 가동하여 공급받은 잉여수를 가열한 후 상기 라디에이터로 공급하여 상기 온실의 항온을 유지하는 보일러; 및상기 온실의 바닥 지면에 매립 설치되어 상기 스프링 쿨러에서 분사된 물을 지면으로 배수하여 자연환원시키는 잡석;을 포함하고,상기 발전기는, 상기 수평배관의 종단부로 배수되는 물의 수력을 이용하여 전기를 생산하는 수차 발전기;상기 수차 발전기로부터 생산된 교류전압을 승압하는 승압기;상기 승압기로부터 승압된 교류전압을 직류전압으로 변환하는 컨버터;상기 컨버터에 의해 변환된 직류전압을 저장하는 축전지;상기 축전지의 직류전압을 교류전압으로 변환하는 인버터; 및 상기 승압기와 상기 인버터로부터 공급되는 교류전압 중 어느 하나를 선택하여 상기 보일러와 배선을 통해 전기적으로 접속된 분전반으로 공급하는 자동 절환 스위치;를 포함하는에너지 절약 및 작물 발육 보조를 위한 수경재배용 설비 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

895/1150 Row 895: application_number: 1020200082779, combined_string: invention_title: 제설제로부터 화단을 보호하는 장치 abstract: 본 발명은 도로에 인접한 화단 전방에 설치되어 겨울철에 염화캄슐과 같은 제설제가 화단으로 침투하는 것을 방지하는, 제설제로부터 화단을 보호하는 장치에 관한 것이다. 본 발명은 제설제가 화단으로 침투하는 것을 차단하는 복수 개의 차단벽부(10); 상기 복수 개의 차단벽부 사이에 설치되는 복수 개의 롤부(20)로서, 각기 개구(21)를 통해 상기 차단벽부의 일단부가 삽입되어 탄력적으로 권회되도록 구성되며, 상기 개구와 반대측에는 상기 차단벽부의 타단부가 고정되며, 중심에는 관통구멍이 형성된 복수 개의 롤부(20); 상기 롤부의 관통구멍을 통과하고 있고, 하단부는 지면에 박혀 빠져나오기 어려운 형상을 가진 지면 고정체(30); 및 상기 지면 고정체의 하단으로부터 위로 설정된 길이만큼 이격되어 상기 지면 고정체에 대해 직교하는 방향으로 관통하여 배치되어서, 상기 지면 고정체가 상기 롤부로부터 분리되는 것을 방지하는 분리 방지대(33);를 포함한다. claims: 제설제가 화단으로 침투하는 것을 차단하는 복수 개의 차단벽부(10)로서, 기온, 습도 및 적설량을 감지하여 관리자 단말에 제공하는 기온 센서, 습도 센서 및 적설량 센서가 설치되어 있는 복수 개의 차단벽부;상기 복수 개의 차단벽부 사이에 설치되는 복수 개의 롤부(20)로서, 각기 개구(21)를 통해 상기 차단벽부의 일단부가 삽입되어 탄력적으로 권회되도록 구성되며, 상기 개구와 반대측에는 상기 차단벽부의 타단부가 고정되며, 중심에는 관통구멍이 형성된 복수 개의 롤부(20);상기 롤부의 관통구멍을 통과하고 있고, 하단부는 지면에 박혀 빠져나오기 어려운 형상을 가진 지면 고정체(30); 및상기 지면 고정체의 하단으로부터 위로 설정된 길이만큼 이격되어 상기 지면 고정체에 대해 직교하는 방향으로 관통하여 배치되어서, 상기 지면 고정체가 상기 롤부로부터 분리되는 것을 방지하는 분리 방지대(33);를 포함하는, 제설제로부터 화단을 보호하는 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

896/1150 Row 896: application_number: 1020200075948, combined_string: invention_title: 인조잔디식재 및 조립이 용이한 잔디보호매트 abstract: 본 발명은 인조잔디식재 및 조립이 용이한 잔디보호매트에 관한 것이다. 본 발명의 일실시 예에 따른 인조잔디식재 및 조립이 용이한 잔디보호매트는 상면에 인조잔디가 구비되는 인조잔디용 체결유닛 및 이를 잔디보호매트에 조립하기 위한 홀더를 포함함으로써, 천연잔디의 발육에 도움을 주는 인조잔디를 잔디보호매트에 쉽게 식재 가능하다. 따라서 잔디보호와 관련된 잔디보호매트의 신뢰도를 효과적으로 높일 수 있다. claims: 사각형의 외곽프레임을 통해 형성되는 내부공간에 배열된 수직지지기둥;상기 외곽프레임과 각각의 수직지지기둥을 선택적으로 연결하는 외곽연결리브;상기 각각의 수직지지기둥의 중단을 선택적으로 서로 연결할 수 있도록 각각의 수직지지기둥을 중심으로 수평방향으로 형성된 내부연결리브; 및상기 각각의 수직지지기둥의 하단을 선택적으로 서로 연결할 수 있도록 각각의 수직지지기둥의 하단을 중심으로 수평방향으로 형성된 하부구조체;를 포함하며,각각의 상기 하부구조체가 서로 교차하는 중심부에 선택적으로 형성된 링형의 펙고정유닛;상기 펙고정유닛에 상부에서 하부방향으로 체결되어 지면에 삽입되는 유동방지용 펙;상기 각각의 수직지지기둥의 둘레에 선택적으로 돌출 형성된 제1 돌출부, 상기 제1 돌출부와의 사이에 삽입공간이 형성되도록 제1 돌출부와 이격 배치된 제2 돌출부 및 상기 제1,2 돌출부의 상단에 돌출 형성되어 서로 마주보게 배치된 고리부로 구성된 홀더; 및상기 홀더를 통해 내부공간의 상부에 길이방향으로 조립되며, 상면에 인조잔디가 구비되는 인조잔디용 체결유닛;을 더 포함하는 인조잔디식재 및 조립이 용이한 잔디보호매트., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

897/1150 Row 897: application_number: 1020200071098, combined_string: invention_title: 타워형 수경재배장치 abstract: 본 발명은 하는 타워형 수경재배장치에 간한 것으로서, 베이스박스(11)의 상부측으로 연장된 다수의 기둥(12)에 지지되는 루프(13)를 가지는 타워케이스(10)와; 베이스박스(11)에 착탈 가능하게 지지되는 것으로서, 측부에 작물을 재배하기 위한 포트(P)가 끼어지는 다수의 포트홀(22)(22')(22)이 형성된 하나 이상의 재배타워(20)와; 베이스박스(11)에 내장되는 것으로서 재배타워(20)로 공급되는 물이 저장되는 물저장부(30)와; 루프(13)에 설치되어 상기 재배타워(20) 하부측으로 물을 분사하는 분사캡(40)과; 물저장부(30)의 물을 상기 분사캡(40)로 공급한 후 상기 재배타워(20)를 통하여 상기 물저장부(30)로 순환시키는 물순환공급부(50);를 포함하는 것을 특징으로 한다. claims: 베이스박스(11)의 모서리에서 상부측으로 연장된 4 개의 기둥(12)에 지지되는 루프(13)를 가지는 타워케이스(10);상기 4 개의 기둥(12) 내측에서 베이스박스(11)에 착탈 가능하게 지지되는 것으로서, 측부에 작물을 재배하기 위한 포트(P)가 끼어지는 다수의 포트홀(22)(22')(22)이 형성된 하나 이상의 재배타워(20);상기 4 개의 기둥(12) 각각에 지지되어 상기 재배타워(20)로 광을 입체적으로 조사하는 광조사부(70);상기 베이스박스(11)에 내장되는 것으로서 상기 재배타워(20)로 공급되는 물이 저장되는 물저장부(30);상기 루프(13)에 설치되어 상기 재배타워(20) 하부측으로 물을 분사하는 분사캡(40);상기 물저장부(30)의 물을 상기 분사캡(40)로 공급한 후 상기 재배타워(20)를 통하여 상기 물저장부(30)로 순환시키는 물순환공급부(50); 및 상기 재배타워(20)와 물저장부(30) 사이의 결합관(32)에 끼어져 결합되는 것으로서, 상기 재배타워(20)를 통하여 순환되는 물의 부패 및 오염을 방지하기 위하여 구리메쉬(61)(62), 모래층(63) 및 활성탄층(64)으로 이루어지는 필터부(60);를 포함하고;상기 기둥(12)은 L 형태의 단면 구조를 가지며 마주보는 내측면에 확산판끼움홈(12a)이 길게 형성되고;상기 광조사부(70)는, 상기 기둥(12)에 내측에 설치되는 것으로서 다수의 LED(71)가 일정한 간격으로 식립되는 PCB(72)와, 상기 다수의 LED(71)를 덮도록 상기 확산판끼움홈(12a)에 끼어져 결합되어 상기 LED(71)에서 조사되는 광을 확산하는 확산판(73)을 포함하는 것;을 특징으로 하는 타워형 수경재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

898/1150 Row 898: application_number: 1020200071099, combined_string: invention_title: 베드형 수경재배장치 abstract: 본 발명은 베드형 수경재배장치에 관한 것으로서, 베이스박스(11)의 후방측에 지지된 측벽(12)을 가지는 케이스(10)와; 측벽(12)에 지지되는 것으로서, 상부측에 작물을 재배하기 위한 포트(P)가 끼어지는 다수의 포트홀이 형성된 제1,2재배선반(20)(20')과; 베이스박스(11)에 내장되는 것으로서 제1,2재배선반(20)(20')으로 공급되는 물이 저장되는 물저장부(30)와; 물저장부(30)에 저장된 물을 압송하기 위한 압송펌프(40)와; 제1,2재배선반(20)(20') 일측과 연결되는 것으로서 압송펌프(40)에서 압송되는 물이 유입되는 유입관부(50)와; 제1,2재배선반(20)(20') 타측과 물저장부(30)를 연결하는 것으로서 제1,2재배선반(20)(20')을 경유한 물을 상기 물저장부(30)로 배수시키는 배수관부(60);를 포함하는 것을 특징으로 한다. claims: 베이스박스(11)의 후방측에 지지된 측벽(12) 및 상기 측벽(12)의 상부측에 설치되는 루프(14)를 가지는 케이스(10);상기 측벽(12)에 지지되는 것으로서, 상부측에 작물을 재배하기 위한 포트(P)가 끼어지는 다수의 포트홀이 형성된 제1,2재배선반(20)(20');상기 베이스박스(11)에 내장되는 것으로서 상기 제1,2재배선반(20)(20')으로 공급되는 물이 저장되는 물저장부(30);상기 물저장부(30)에 저장된 물을 압송하기 위한 압송펌프(40);상기 제1,2재배선반(20)(20') 일측과 연결되는 것으로서 상기 압송펌프(40)에서 압송되는 물이 유입되는 유입관부(50);상기 제1,2재배선반(20)(20') 타측과 상기 물저장부(30)를 연결하는 것으로서 상기 제1,2재배선반(20)(20')을 경유한 물을 상기 물저장부(30)로 배수시키는 배수관부(60);상기 배수관부(60)와 물저장부(30) 사이에 설치되어 상기 제1,2재배선반(20)(20')을 경유한 물의 부패 및 오염을 방지하는 필터부(70); 및 상기 베이스박스(11)의 모서리측에 지지되어 상기 루프(14)까지 연장된 것으로서, 상기 제1,2재배선반(20)(20')으로 광을 입체적으로 조사하는 4 개의 광조사부(80)를 포함하고;상기 광조사부(80)는, 상기 베이스박스(11)에 모서리측에 지지되는 것으로서 단면이 L 형태이고 마주보는 내측면에 확산판끼움홈(81a)이 형성된 기둥(81)과, 상기 기둥(81)의 내측에 설치되는 것으로서 다수의 LED(82)가 일정한 간격으로 식립되는 PCB(83)와, 상기 다수의 LED(82)를 덮도록 상기 확산판끼움홈(81a)에 끼어지는 것으로서 상기 LED(82)에서 조사되는 광을 확산하는 확산판(84)을 포함하고;상기 물저장부(30)의 물탱크(31)의 상부측에 상기 물탱크(31) 내부와 연통되는 필터수납홈(31a)이 형성되고;상기 필터수납홈(31a)에는 상기 제1,2재배선반(20)(20')을 순환한 후 물저장부(30)로 순환 회수되는 물의 부패 및 오염을 방지하기 위하여 정화시키기 위한 필터부(70)가 착탈 가능하게 설치되고;상기 필터부(70)는 상기 필터수납홈(31a)에 착탈 가능하게 결합되는 것으로서 상부측으로 상기 배수관부(60)의 배수관헤드(63)가 결합되는 헤드결합공(71a)이 형성되고 하방측으로 배수공(71b)이 형성된 필터박스(71)와, 상기 필터박스(71) 내측에 배치되는 필터엘레먼트(72)를 포함하고;상기 필터엘레먼트(72)는, 상기 배수관부(60)를 통하여 순환되는 물의 부패 및 오염을 방지하기 위하여 제1,2구리메쉬(72a)(72b), 상기 제1,2구리메쉬(72a)(72b) 사이에 설치되는 모래층(72c) 및 활성탄층(72d)을 포함하는 것;을 특징으로 하는 베드형 수경재배.제1항에 있어서, 상기 물저장부(30)는, 상기 베이스박스(11)에 설치되는 물탱크(31)와, 상기 물탱크(31)에 저장된 물 온도를 측정하여 대응되는 온도신호(T)를 발생하는 온도센서(32)와,상기 물탱크(31)에 설치되어 물을 가온시키기 위한 히터(33)와, 상기 온도센서(32)에서 발생되는 온도신호(T)에 연동되어 상기 히터(33)의 작동을 제어하는 히터작동부(34)를 포함하는 것을 특징으로 하는 베드형 수경재배장치.제1항에 있어서, 상기 물저장부(30)로 비료성분을 공급하는 비료공급부(90)를 더 포함하는 것을 특징으로 하는 베드형 수경재배장치.제1항에 있어서, 상기 제1,2재배선반(20)(20')은,상기 측벽(12)에 고정된 제1,2선반브라켓(13)(13') 지지되는 것으로서 내부에 물이 수용되는 저수공간이 형성된 제1,2선반박스(21)(21')와, 상기 제1,2선반박스(21)(21')의 상부측에 덮여지는 것으로서 다수의 포트홀(22)(22')이 형성된 제1,2박스커버(23)(23')와,상기 제1,2선반박스(21)(21')의 일측에 형성되어 상기 유입관부(50)와 연결되는 제1,2유입공(24)(24')와, 상기 제1,2선반박스(21)(21')의 타측에 형성되어 배수관부(60)와 연결되는 제1,2배수공(25)(25')를 포함하는 것을 특징으로 하는 베드형 수경재배장치.제1항에 있어서, 상기 제1,2재배선반(120)(120')은,상호 이격되게 배치되는 제1,2,3파이프(121)(122)(123)와; 상기 제1,2,3파이프(121)(122)(123) 각각의 양단에 결합되는 것으로서 관통되는 구멍이 형성되는 제1,2,3캡(124)(125)(126)과;상기 제1,2,3파이프(121)(122)(123)가 지그재그로 연결될 수 있도록, 상기 제1,2,3파이프(121)(122)(123) 일측의 제1,2캡(124)(125)을 연결하는 제1연결관(127) 및 상기 제1,2,3파이프(121)(122)(123) 타측의 제2,3캡(125)(126)을 연결하는 제2연결관(128);를 포함하는 것을 특징으로 하는 베드형 수경재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

899/1150 Row 899: application_number: 1020200066078, combined_string: invention_title: 신규한 건식제분용 벼 품종, 가루미1 및 가루미2 abstract: 본 발명은 건식제분을 이용한 쌀가루 제조에 적합한 분질배유를 포함하면서도, 수발아성이 감소되고, 병해저항성이 우수하며, 만기재배 적응성이 우수한 신규한 벼 품종 가루미1 및 가루미2, 상기 벼 품종의 육종방법, 상기 벼 품종의 재배방법, 상기 벼 품종의 종자를 포함하는 건식제분용 조성물, 상기 벼 품종의 종자를 건식제분하여 수득한 쌀가루 및 상기 벼 품종의 식물 또는 종자를 포함하는 식품 조성물에 관한 것이다. 본 발명에서 제공하는 신규 벼 품종은 분질배유를 포함하여 건식제분을 이용하여 쌀가루를 제조할 수 있을 뿐만 아니라, 우수한 병해저항성 및 만기재배 적응성을 나타내어 재배시 수량성이 우수하고, 수발아성이 감소되어 저장성이 우수하므로, 쌀가루를 이용한 다양한 식품의 개발에 널리 활용될 수 있을 것이다. claims: '수원542호' 품종과 '조평' 품종의 교배에 의해 생산되는 자손품종으로부터 유래되고, 하기의 특성을 나타내는, 건식제분에 적합한 자포니카 벼(Oryza sativa L. sp. Japonica) 계통 식물:(a) 33 내지 34일의 기본영양생장기를 갖는 만기재배 적응성;(b) 1.73 내지 1.81의 장폭비를 갖는 단원형 입형의 종자;(c) '수원542호'의 분질배유 유전자(flo7)의 유전형;(d) '조평'의 흰잎마름병 저항성 유전자(Xa3) 및 줄무늬잎마름병 저항성(Stvbi) 유전자의 유전형;(e) 분질배유 유전자인 cyOsPPDK(cytosolic pyruvate orthophosphate dikinase protein) 유전자의 ORF 내 8번 Exon에 존재하는 SNP의 서열이 A;(f) 흰잎마름병 및 도열병에 대한 저항성;(g) 2.8 내지 2.9kg인 종자의 곡립경도;(h) 81.8 내지 84.5μm의 종자분말의 평균크기;(i) 5.6 내지 6.5%의 종자분말내 손상전분 비율; 및,(j) 종자의 수발아 민감성(1 내지 9): 3 내지 5.제1항에 있어서,상기 자손품종은 F5 개체인 것인, 자포니카 벼 계통 식물.제1항에 있어서,상기 식물은 하기 특징을 갖고, 수탁번호 KACC 98076P로 기탁된 'Oryza sativa 가루미1' 품종인 것인, 자포니카 벼 계통 식물:(a) '수원542호'의 분질배유 유전자(flo7)의 유전형;(b) '조평'의 흰잎마름병 저항성 유전자(Xa3) 및 줄무늬잎마름병 저항성(Stvbi) 유전자의 유전형;(c) 분질배유 유전자인 cyOsPPDK(cytosolic pyruvate orthophosphate dikinase protein) 유전자의 ORF 내 8번 Exon에 존재하는 SNP의 서열이 A;(d) 흰잎마름병 및 도열병에 대한 저항성;(e) 25℃ 기준 33일의 기본영양생장기를 갖는 만기재배 적응성;(f) 1.81의 장폭비를 갖는 단원형 입형의 종자;(g) 2.8±0.11kg인 종자의 곡립경도;(h) 5.19±0.24mm의 현미 길이;(i) 2.88±0.13mm의 현미 너비;(j) 전주 기준 7월 27일의 보통기 재배 출수기;(k) 전주 기준 8월 12일의 이모작 재배 출수기;(l) 전주 기준 8월 24일의 만기 재배 출수기;(m) 84.5±1.55μm의 종자분말의 평균크기;(n) 6.5%의 종자분말내 손상전분 비율;(o) 종자의 수발아 민감성(1 내지 9): 3; 및, (p) 17.1 내지 22.4g의 현미 천립중.제1항에 있어서,상기 식물은 하기 특징을 갖고, 수탁번호 KACC 98077P로 기탁된 'Oryza sativa 가루미2' 품종인 것인, 자포니카 벼 계통 식물:(a) '수원542호'의 분질배유 유전자(flo7)의 유전형;(b) '조평'의 흰잎마름병 저항성 유전자(Xa3) 및 줄무늬잎마름병 저항성(Stvbi) 유전자의 유전형;(c) 분질배유 유전자인 cyOsPPDK(cytosolic pyruvate orthophosphate dikinase protein) 유전자의 ORF 내 8번 Exon에 존재하는 SNP의 서열이 A;(d) 흰잎마름병 및 도열병에 대한 저항성;(e) 25℃ 기준 34일의 기본영양생장기를 갖는 만기재배 적응성;(f) 1.73의 장폭비를 갖는 단원형 입형의 종자;(g) 2.9±0.09kg인 종자의 곡립경도;(h) 4.91±0.27mm의 현미 길이;(i) 2.83±0.14mm의 현미 너비;(j) 전주 기준 7월 26일의 보통기 재배 출수기;(k) 전주 기준 8월 11일의 이모작 재배 출수기;(l) 전주 기준 8월 23일의 만기 재배 출수기;(m) 81.8±1.31μm의 종자분말의 평균크기;(n) 5.6%의 종자분말내 손상전분 비율;(o) 종자의 수발아 민감성(1 내지 9): 5; 및, (p) 16.6 내지 21.2g의 현미 천립중.제1항에 있어서,상기 식물의 종자의 현미는 4.91 내지 5.19mm의 길이와 2.83 내지 2.88의 너비를 갖는 것인, 자포니카 벼 계통 식물.제1항에 있어서,상기 식물의 종자의 현미 천립중은 16.6 내지 22.4g인 것인, 자포니카 벼 계통 식물.제1항에 있어서,상기 SNP는 서열번호 1 및 2의 프라이머 염기쌍을 이용한 PCR에 의해 증폭된 증폭산물의 염기서열 분석에 의해 결정되는 것인, 자포니카 벼 계통 식물.(a) '수원542호' 품종과 '조평' 품종의 교배하여 얻어진 F1 종자를 계통 육종법에 의거하여 F5 세대까지 진전시켜, 분질배유(flo7), 흰잎마름병 저항성(Xa3) 및 줄무늬잎마름병 저항성(Stv-bi) 형질로 고정된 계통을 확립하는 단계; 및 (b) 상기 확립된 계통의 종자들 중, 1.73 내지 1.81의 장폭비를 갖는 단원형 입형 및 수발아 저항성을 갖는 벼 품종을 선별하는 단계를 포함하는, 건식제분에 적합한 자포니카 벼(Oryza sativa L. sp. Japonica) 계통 식물의 육종방법.제1항 내지 제7항 중 어느 한 항의 자포니카 벼 계통 식물을 재배하는 단계를 포함하는, 건식제분에 적합한 자포니카 벼의 재배방법.제1항 내지 제7항 중 어느 한 항의 자포니카 벼 계통 식물의 종자를 건식제분하여 수득한 쌀가루., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

900/1150 Row 900: application_number: 1020200052338, combined_string: invention_title: 고설재배용 포트 및 이를 이용한 고설재배 베드 abstract: 본 발명은 사각판 형태의 방수성 경질 플레이트, 상기 플레이트 상면에 부분적으로 만입되고 하부로 길게 연장되어 작물 재배용 공간을 제공하도록 배치되는 복수의 재배공, 복수의 재배공 사이의 플레이트 상면에 일방향으로 길게 형성된 관수로, 플레이트 측방 끝단에 형성된 고정 고리를 포함하며, 재배공의 깊이를 다르게 하여 재배공의 하부면들에 의해 이루어지는 포트 하부 구조가 측면에서 볼 때 반원 또는 호형인 곡면 구조를 이루는 것을 특징으로 하는 고설재배용 포트를 제공하며, 또한 이 포트를 이용하며 지지 구조물과 천막지 배수라인을 더 포함하는 고설재배 베드를 제공한다. claims: 사각판 형태의 방수성 경질 플레이트,상기 플레이트 상면에 부분적으로 만입되고 하부로 길게 연장되어 작물 재배용 공간을 제공하도록 배치되는 복수의 재배공,복수의 재배공 사이의 플레이트 상면에 일방향으로 길게 형성된 관수로, 플레이트 측방 끝단에 형성된 고정 고리를 포함하며, 재배공의 깊이를 다르게 하여 재배공의 하부면들에 의해 이루어지는 포트 하부 구조가 측면에서 볼 때 반원 또는 호형인 곡면 구조를 이루며,상기 복수의 재배공은 상기 플레이트의 전후 방향 및 좌우방향으로 종횡 배열되고 동일한 종적 배열에서는 동일한 깊이를 갖고, 중앙으로부터 각각 좌우측으로 갈수록 재배공의 깊이가 줄어드는 구조로 형성되고,상기 복수의 재배공은 중앙부의 재배공 평면 면적보다 좌우측의 재배공의 평면 면적이 더 크게 형성되는 것을 특징으로 하는 고설재배용 포트.지면 위에 수평적으로 배치되고, 상호 소정 간격으로 평행하게 이격되어 있는 한 쌍의 제1파이프,상기 한 쌍의 제1파이프 하부에서 각각 제1파이프를 수직 방향으로 지지하는 적어도 한 쌍의 제2파이프,상기 한 쌍의 제1파이프 상면에 일부가 걸쳐진 채로 중앙 하부는 한 쌍의 제1파이프 사이 공간에 제1파이프 높이보다 하방으로 반원 또는 호형을 이루도록 늘어지게 배치되어 고설재배 베드의 배수로로 기능하는 천막지, 및상기 천막지 위에 배치되며, 제1파이프에 양단이 걸친 채로 지면으로부터 이격되어 배치되는 작물 재배용 포트를 포함하며,상기 작물 재배용 포트는 토양과 작물이 삽입되는 복수의 재배공과 재배공 사이에 형성되어 재배공으로 물을 공급하는 관수로를 포함하고, 포트 하부면은 중앙에서 죄우 측부로 갈수록 재배공의 깊이가 줄어드는 곡면 구조로 형성되고,상기 복수의 재배공은 플레이트의 전후 방향 및 좌우방향으로 종횡 배열되고 동일한 종적 배열에서는 동일한 깊이를 갖고, 중앙으로부터 각각 좌우측으로 갈수록 재배공의 깊이가 줄어드는 구조로 형성되고,상기 복수의 재배공은 중앙부의 재배공 평면 면적보다 좌우측의 재배공의 평면 면적이 더 크게 형성되는 것을 특징으로 하는고설재배 베드., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

901/1150 Row 901: application_number: 1020200052439, combined_string: invention_title: 수생식물 재배장치 abstract: 본 발명은 수생식물 재배장치에 관한 것이다.보다 구체적으로는, 콩나물 등 수중에 뿌리를 내려 생육되는 수생식물을 재배하기 위한 재배장치에 관한 것으로서, 일측에 수통을 거꾸로 세워 결합할 수 있는 영역과 상기 영역으로 유입된 물을 공급받아 수생식물을 재배하는 영역을 포함하여 구성된, 수생식물 재배장치에 관한 것이다. claims: 상면 일측에 하방으로 오목하게 형성된 수통삽입부(11)와,상면 다른 일측에 하방으로 오목하게 형성된 재배부(12)를 포함하는 재배장치(10)에 있어서,상기 수통삽입부(11)와 재배부(12)는 상호 연통된 연통영역을 가지고,상기 수통삽입부(11), 재배부(12) 및 연통영역은 바닥에 바닥판(10a)이 구비되며,상기 수통삽입부(11)는 하면 일측에 돌출되도록 형성된 수통고정구(13)가 구비되어, 수통을 거꾸로 세워 결합시켜 고정할 수 있도록 하되,(a) 상기 재배부(12)는,재배부(12)의 바닥판(10a)의 상면에서부터 통 형식으로 구성된 재배통(14)이 구비되되, 상기 재배통(14)의 외면과 재배부(12)의 내면은 일정 간격 이격되도록 형성되어 이격공간을 포함하고,(b) 상기 재배통(14)은,재배부(12)의 바닥판(10a)의 상면에서부터 통 형식으로 구성되고 상면이 개방된 통(14a)과, 상기 통(14a)의 상면을 마감하는 커버(14b)를 포함하여 구성되되,상기 통(14a)의 하단 일측에는 통(14a)의 원주방향을 따라 일정간격 형성되는 복수 개의 홀(14a')이 형성되며,상기 통(14a)의 내면에는 통(14a)을 가로막는 재배판이 구비되되, 상기 재배판은, 다수의 천공을 포함하고, 상기 홀(14a')보다 높은 위치에 구비되며,(c) 상기 수통고정구(13)는,수통삽입부(11)의 바닥판(10a)의 상면에 구비된 베이스(13a)와, 상기 베이스(13a)의 상방으로 돌출된 돌기(13b)와, 상기 베이스(13a)의 일측에서부터 돌기(13b)의 일측까지 연결된 제1 턱(13c) 및 제2 턱(13d)을 포함하되,상기 제1 턱(13c) 및 제2 턱(13d)은,각각 돌기(13b)의 원주 방향을 따라 일정 간격으로 복수 개 형성되고,상호 다른 높이를 가지도록 구성되되, 턱진 영역의 폭이 제1 턱(13c) 및 제2 턱(13d) 간에 다르도록 구성하며, (d) 수통삽입부(11)와 재배부(12)를 연통하는 연통영역에는 수통삽입부(11)와 재배부(12)의 연통된 구조를 차단하고, 재배부(12)에 고인 물을 재배장치(10) 외측으로 배출하는 기능을 수행하는 배출단속장치가 구성되되,상기 배출단속장치는,수통삽입부(11)와 재배부(12)를 연통하는 연통영역의 바닥판(10a)에 재배장치(10)의 하부 외측으로 관통된 홀을 포함하고,상기 홀에는 홀의 크기에 대응되는 크기를 가지는 누름부가 홀에 삽입되며, 상기 홀의 내면에는 2개가 1쌍으로 마주하는 가이드홈이 형성되고,상기 누름부의 가이드홈에 대응되는 일면에는 돌기가 형성되며,상기 돌기는 가이드홈보다 짧은 길이로 형성되어, 상기 돌기가 가이드홈에 삽입된 후, 가이드홈을 따라 돌기가 가이드될 수 있도록 하고,상기 홀의 상측은 뚜껑에 의해 폐쇄되되, 상기 뚜껑은 뚜껑의 측벽이 홀의 내부에 삽입되며, '┌┐'의 형상을 가지고, 측벽이 형성되지 않은 방향으로 경첩을 통해 뚜껑과 바닥판(10a)을 연결하여, 상기 뚜껑이 수직방향으로 개방될 수 있도록 함으로써,상기 누름부가 상승하는 경우, 뚜껑의 하면을 누르면서 상승하여, 뚜껑이 개방될 수 있도록 하고, 상기 누름부는 상방으로 이동되지 않았을 때, 뚜껑을 폐쇄할 수 있는 정도의 길이를 가지도록 하며, 별도의 구조물을 대거나, 손으로 누르는 경우, 누름부가 상승하면서 뚜껑을 개방시키게 되는 것을 특징으로 하는, 수생식물 재배장치., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

902/1150 Row 902: application_number: 1020200041696, combined_string: invention_title: 인조잔디식재 및 조립구조가 개선된 잔디보호매트 abstract: 본 발명은 인조잔디식재 및 조립구조가 개선된 잔디보호매트에 관한 것이다. 본 발명의 일실시 예에 따른 인조잔디식재 및 조립구조가 개선된 잔디보호매트는 천연잔디의 발육에 도움을 주는 인조잔디를 잔디보호매트에 용이하게 식재 가능할 뿐만 아니라 서로 이웃하는 복수의 잔디보호매트를 용이하게 조립할 수 있도록 조립구조를 볼 방식으로 개선함으로써, 숙련자는 물론이고, 초보자도 골프장이나 녹색주차장 또는 공원 등에 잔디보호매트를 쉽게 설치할 수 있다. 따라서 천연잔디를 보호하기 위한 잔디보호매트의 보급률에 크게 기여할 수 있다. claims: 사각형의 외곽프레임;상기 외곽프레임을 통해 형성된 내부공간에 배열된 수직지지기둥;각각의 상기 수직지지기둥과 외곽프레임을 연결하는 외곽연결프레임; 및각각의 상기 수직지지기둥을 중심으로 수평방향으로 형성되는 내부연결프레임;을 포함하며,각각의 상기 내부연결프레임의 상부에 돌출 형성된 제1 돌출부 및 상기 제1 돌출부와의 사이에 삽입공간이 형성되도록 제1 돌출부와 이격 배치된 제2 돌출부로 구성된 홀더; 및상기 홀더를 통해 내부공간의 상부에 길이방향으로 조립되며, 상면에 인조잔디가 식재된 인조잔디용 체결유닛;을 더 포함하는 인조잔디식재 및 조립구조가 개선된 잔디보호매트., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

903/1150 Row 903: application_number: 1020200033640, combined_string: invention_title: 다중의 천연잔디 구장을 분할하여 집중 관제할 수 있는 잔디 관리 시스템 및 방법 abstract: 본 발명의 일 실시예에 따른 잔디 관리 시스템은, 잔디가 마련된 지역에 설치되며, 잔디 상태를 체크하기 위한 다수의 센서와 연결되어 센싱정보를 수집하고, 밸브를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 적어도 하나의 컨트롤러; 상기 컨트롤러와 연결되어 수집된 센싱정보를 전송받아 모니터링하고, 센싱정보를 토대로 상기 컨트롤러 및 밸브를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 중앙관제서버;를 포함할 수 있다. claims: 잔디 관리 시스템에 있어서, 잔디가 마련된 지역에 설치되며, 잔디 상태를 체크하기 위한 다수의 센서와 연결되어 센싱정보를 수집하고, 밸브를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 적어도 하나의 컨트롤러;상기 컨트롤러와 연결되어 수집된 센싱정보를 전송받아 모니터링하고, 센싱정보를 토대로 상기 컨트롤러 및 밸브를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 중앙관제서버;를 포함하되,상기 센서는잔디의 온습도 상태를 확인하기 위하여 잔디가 위치한 지중에 구비된 온습도센서, 강우량을 체크하기 위한 강우센서, 대기센서, 미세먼지센서, 풍향/풍속센서, 낙뢰센서 및 일사량센서를 포함하며,상기 잔디 관리 시스템은,상기 컨트롤러와 연결되어 기상 관측 정보를 체크하기 위해 마련되며, 상기 대기센서, 미세먼지센서, 온습도센서, 강우량센서, 풍향/풍속센서, 낙뢰센서, 일사량센서로부터 센싱정보를 제공받아 기상 관측 정보를 생성하고, 상기 중앙관제서버에 기상 관측 정보를 전송하거나 잔디 주변에 설치된 대형 화면 패널을 통하여 표시하는 기상관측부를 더 포함하며,상기 중앙관제서버는상기 센싱정보를 수집하여 데이터베이스에 저장하여 관리하거나 센싱정보 또는 기상 관측 정보를 로컬 지역에 전송하거나, 스프링클러의 제어신호를 전송하는 역할을 수행하는 관리부;상기 센서의 오차나 오작동에 대한 예측모델을 생성하는 예측부;상기 예측모델을 이용하여 예측 결과를 산출하고, 예측 결과를 토대로 센서의 예측된 허용 오차 범위 내에서 컨트롤러를 통하여 스프링클러의 온/오프 또는 분사량을 제어할 수 있도록 하는 분석부;상기 센싱정보 및 예측결과를 이용하여 학습을 수행하고, 반복된 학습을 통하여 센서의 오차 또는 오작동에 대한 예측모델을 업그레이드하는 학습부를 더 포함하며,상기 분석부는 서포트 벡터 머신을 기반으로 한 예측모델로 예측을 수행하되, 입력변수의 초기값으로 센서의 출하시 제공되는 모델정보를 토대로 설정된 오차 또는 오작동 범위를 입력변수로 하여 예측을 수행하며,상기 중앙관제서버는로컬서버 또는 관리단말에 각각 신분 증명이 가능한, 식별 정보(identification information)를 부여하여, 각 로컬서버 또는 관리단말의 식별 정보를 사설 암호 키(private key)로 활용하는 경량 암호 알고리즘을 수행하여, 상기 로컬서버, 관리단말 및 중앙관제서버 간의 주고받는 센싱정보에 대한 암/복호화를 하며,상기 경량 암호 알고리즘은 상기 관리단말의 환경에서 구현하기 위해 설계된 암호 기술이고, 대칭키 암호 알고리즘인 HIGHT(HIGh security and liht weigHT), LEA(Lightweight Encryption)와 해시함수인 LSH(Lightweight Secure Hash)를 활용하여 암/복호화하는 것을 특징으로 하는 잔디 관리 시스템.잔디 관리 시스템을 이용한 잔디 관리 방법에 있어서,상기 잔디 관리 시스템은 잔디가 마련된 지역에 설치되며 잔디 상태를 체크하기 위한 다수의 센서와 연결된 컨트롤러를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 중앙관제서버에서 상기 센서로부터 센싱정보를 수집하는 단계;상기 중앙관제서버는 상기 센싱정보를 입력변수로 인공지능 기반의 예측모델을 생성하는 단계;상기 중앙관제서버는 상기 예측모델을 이용하여 상기 센서의 오차 또는 오작동 여부를 판단하기 위한 예측을 수행하여, 예측 결과를 산출하는 단계;상기 중앙관제서버는 상기 예측 결과를 토대로 상기 센서의 예측된 허용 오차 범위 내에서 상기 컨트롤러를 통하여 스프링클러의 온/오프 또는 분사량을 제어하는 단계;상기 중앙관제서버는 수집된 센싱정보 및 예측 결과를 예측모델 학습을 위한 빅데이터로 활용하기 위해 데이터베이스에 저장하는 단계;를 포함하되,상기 센서는잔디의 온습도 상태를 확인하기 위하여 잔디가 위치한 지중에 구비된 온습도센서, 강우량을 체크하기 위한 강우센서, 대기센서, 미세먼지센서, 풍향/풍속센서, 낙뢰센서 및 일사량센서를 포함하며,상기 잔디 관리 시스템은,상기 컨트롤러와 연결되어 기상 관측 정보를 체크하기 위해 마련되며, 상기 대기센서, 미세먼지센서, 온습도센서, 강우량센서, 풍향/풍속센서, 낙뢰센서, 일사량센서로부터 센싱정보를 제공받아 기상 관측 정보를 생성하고, 상기 중앙관제서버에 기상 관측 정보를 전송하거나 잔디 주변에 설치된 대형 화면 패널을 통하여 표시하는 기상관측부를 더 포함하며,상기 중앙관제서버는상기 센싱정보를 수집하여 데이터베이스에 저장하여 관리하거나 센싱정보 또는 기상 관측 정보를 로컬 지역에 전송하거나, 스프링클러의 제어신호를 전송하는 역할을 수행하는 관리부;상기 센서의 오차나 오작동에 대한 예측모델을 생성하는 예측부;상기 예측모델을 이용하여 예측 결과를 산출하고, 예측 결과를 토대로 센서의 예측된 허용 오차 범위 내에서 컨트롤러를 통하여 스프링클러의 온/오프 또는 분사량을 제어할 수 있도록 하는 분석부;상기 센싱정보 및 예측결과를 이용하여 학습을 수행하고, 반복된 학습을 통하여 센서의 오차 또는 오작동에 대한 예측모델을 업그레이드하는 학습부를 더 포함하며,상기 분석부는 서포트 벡터 머신을 기반으로 한 예측모델로 예측을 수행하되, 입력변수의 초기값으로 센서의 출하시 제공되는 모델정보를 토대로 설정된 오차 또는 오작동 범위를 입력변수로 하여 예측을 수행하며,상기 중앙관제서버는로컬서버 또는 관리단말에 각각 신분 증명이 가능한, 식별 정보(identification information)를 부여하여, 각 로컬서버 또는 관리단말의 식별 정보를 사설 암호 키(private key)로 활용하는 경량 암호 알고리즘을 수행하여, 상기 로컬서버, 관리단말 및 중앙관제서버 간의 주고받는 센싱정보에 대한 암/복호화를 하며,상기 경량 암호 알고리즘은 상기 관리단말의 환경에서 구현하기 위해 설계된 암호 기술이고, 대칭키 암호 알고리즘인 HIGHT(HIGh security and liht weigHT), LEA(Lightweight Encryption)와 해시함수인 LSH(Lightweight Secure Hash)를 활용하여 암/복호화하는 것을 특징으로 하는 잔디 관리 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

904/1150 Row 904: application_number: 1020200029298, combined_string: invention_title: 스마트기기를 이용한 식물재배시스템 abstract: 본 발명은 스마트 수단을 이용하여 자동으로 식물재배가 가능하며, 일상생활에 필요한 조명까지 종합적으로 함께 이루어질 수 있는 시스템에 관한 것으로서,천장에 고정되며 식물이 배치되는 재배유닛; 및 식물에 양액을 공급하는 공급유닛;을 포함하여 이루어지되,상기 재배유닛은,복수로 구비되며, 식물 뿌리가 위를 향하고 식물 잎이 아래를 향하여 재배될 수 있도록 지지를 하며, 설치 및 교환이 가능하도록 모듈화된 셀 단위로 제공되는 단위모듈; 및 식물에 광에너지를 공급하여 식물재배를 촉진하며, 일상생활에 필요한 조명까지 동시에 제공할 광원설비;를 포함하고,상기 공급유닛은,식물재배를 위한 양액을 저장하는 메인탱크; 및 저장된 양액을 상기 단위모듈에 이송하는 이송관;을 포함하여 이루어진다. claims: 스마트기기를 이용하여 자동으로, 역전된 상태로 재배되는 식물(pl)을 관리하며 동시에, 사무실 및 주거시설에 있어서 필요한 조명까지 함께 제공할 수 있는 스마트기기를 이용한 식물재배시스템으로서 재배유닛(100); 및 공급유닛(200);을 포함하고,재배유닛(100)은 단위모듈(110); 및 광원설비(120);를 포함하여서, 식물이 배치되며 빛을 공급하고,공급유닛(200)은 메인탱크(210); 및 이송관(220);을 포함하여서 식물재배를 위한 양액을 공급하고,단위모듈(110)은 하우징(111); 쳄버(112); 양액통(113); 포그발생장치(114); 기류발생팬(115); 및 재배유닛측 제어계측수단(116);를 포함하고,하우징(111)은 내부를 밀폐하며, 저면에 광원설비(120)의 빛을 반사시킬 반사판(111a)을 함께 구비하고,쳄버(112)는 하우징(111)의 저면에 배치되고, 수직방향으로 개구되어 식물을 고정하고,양액통(113)은 단위모듈(110)의 내부에 구비되어서 메인탱크(210)에 저장된 양액을 이송관(220)을 통하여 전달받아 일시 저장하고,포그발생장치(114)는 단위모듈(110)에 배치된 식물에 양액을 공급하기 위하여, 양액통(113)에 일시 저장된 양액을 양액포그(wa3) 형태로 만들고,기류발생팬(115)은 모터팬으로 제공되고, 외부의 공기를 양액통(113)에 불어넣어 기류를 발생하고, 기류를 따라 양액포그(wa3)가 이동하여 식물 뿌리(pl1)에 양액을 공급하도록 작동하고, 기류발생팬(115)의 강약 조절로 양액포그(wa3)의 공급량이 조절되고,재배유닛측 제어계측수단(116)은 단위모듈(110)에 배치된 식물재배가 용이하도록 온습도를 감지하여 무선네트워크를 통하여 모니터링하고, 식물재배에 필요한 기능제어를 수행하고,광원설비(120)는 광원프레임(121); 및 LED 전등 램프;를 포함하고,광원프레임(121)은 격자 형태를 취해서 단위모듈(110)의 저면과 떨어져 위치되며, 고정대(121a)를 통하여 천장에 고정되고, 광원프레임(121)에 단위모듈(110)이 고정되고,LED 전등 램프는 단위모듈(110)을 향하여 아래에서 위로 빛을 조사하여 식물에 광에너지를 제공하도록 설치되고,메인탱크(210)는 탱크몸체(211); 이송펌프(212); 및 공급유닛측 제어계측수단(213)을 포함하고,탱크몸체(211)는 내부를 밀폐하며 양액을 저장하는 탱크 형태를 취하고,이송펌프(212)는 이송관 일단(222)에 구비되어서 탱크몸체(211)에 저장된 양액을 이송관(220)으로 보내는 동력원의 역할을 수행하고,공급유닛측 제어계측수단(213)은 메인탱크(210)의 기능 상태을 제어하고 메인탱크(210)의 내측벽에 수위 수준을 감지하도록 설치된 센서를 포함하고,이송관(220)은 이송관 몸체(221); 이송관 일단(222); 이송관 타단(223);을 포함하여, 저장된 양액을 단위모듈(110)에 이송하며, 이송관(220)은 건물벽체에 고정브라킷으로 고정되고,이송관 몸체(221)는 파이프 형태를 취하여, 이송펌프(212)의 작동에 의하여 양액을 양액통(113)으로 이송하고,이송관 일단(222)은 파이프 형태의 일단으로서 메인탱크(210)에 위치되어, 이송펌프(212)가 작동하면 저장된 양액이 인입되는 입구의 역할을 수행하고,이송관 타단(223)은 파이프 형태의 타단으로서 단위모듈(110)에 위치되고 이송된 양액이 배출되는,것을 특징으로 하는 스마트기기를 이용한 식물재배시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

905/1150 Row 905: application_number: 1020200029687, combined_string: invention_title: 파종기 abstract: 본 발명은 파종기에 관한 것이다.구성에 있어서, 파이프 형태로 됨과 동시에 종자통의 작용을 하도록 구성된 지주관의 소정위치에 종자공급장치를 장착하고, 그 하부에 작동부와 파종부, 그리고 파종홈의 깊이를 조절할 수 있는 스토퍼부로 이루어진 파종홈 성형장치를 구성하여, 상기 작동부의 하단 베이스를 지면에 대고 손잡이로 누르면 파종부가 하강하면서 오물어진 상태로 지면에 들어가게 되어 자연스럽게 소정깊이의 파종홈을 형성하면서 동시에 종자공급장치도 연동하여 파종부 내부로 종자를 공급할 수 있게 하고, 파종기를 드는 순간 작동부의 복원력에 의해 자연적으로 파종부가 개방되면서 파종부 안으로 낙하된 종자를 파종홈으로 투입할 수 있게 구성함을 특징으로 한다.따라서 본 발명은 각종 종자 파종시 보다 정확하면서도 확실한 파종이 이루어질 수 있으며,구성이 지극히 간단하고 제작이 손쉬워 농가에 저렴하게 공급할 수 있으면서 사용이 편리한 효과가 있다. claims: 상단에 뚜껑(11)과 손잡이(12)가 구비된 파이프 형태로 된 원통형의 종자통(1),상기 종자통(1)의 하부에 장착되며 90°~ 180°로 회전하면서 종자통(1) 내부의 종자를 일정량, 또는 소정 개수만 파종부(2)로 회전 이송시켜 낙하시키는 종자공급장치(6),상기 종자공급장치(6)가 종자를 파종부(2) 안으로 떨어뜨릴 때 통로로 작용하는 지지관(8),상기 지지관(8)의 하부에 장착되어 경운된 지면에 대고 누르면 파종홈(5)을 형성함과 동시에 상기한 종자공급장치(6)를 연동시켜 종자를 파종홈(5)으로 투입시키는 파종홈 성형장치(234)로 이루어진 파종기에 있어서,상기 종자공급장치(6)는상하부에 투입부(60a)와 배출부(60b)가 각각 구비되고 상기 투입부(60a)와 배출부(60b) 사이에 횡방향으로 드럼삽입부(60c)를 형성한 본체(6a)와,상기 드럼삽입부(60c)에 삽입되고, 외주면 상부에 종자홈(67')을 가진 가이드블록(67)를 끼울 수 있도록 가이드 끼움홈(61)이 구비되며, 일 측면에는 피니언(63)이 형성되고, 타 측면에는 본체(6a) 외부에서 측면고정판(66)을 대고 볼트(65)로 체결 조립하여서 된 드럼(6b),그리고 상기 피니언(63)에 치합되어 파종기(100)를 지면에 대고 누를 때 파종부(2)가 파종홈(5)을 형성함과 동시에 드럼(6b)도 회전하여 자동파종이 이루어질 수 있게 한 회전유도부(7)를 포함한 구성으로 이루어지되,상기 회전유도부(7)는 피니언(63)에 치합되는 랙기어(L)와, 상기 랙기어(L) 하부에 길게 연장형성된 연장부(L1), 그리고 상기 연장부(L1)가 지지대(34)를 관통한 뒤 압축스프링(LS)을 개재시키도록 된 스프링받침부(L2)로 이루어지고, 상기 연장부(L1) 하단은 파종부(2)의 승강거리와 드럼(6b)의 회전각도를 감안하여 베이스(31)로부터 소정의 높이만큼 높여 설치 구성함을 특징으로 하는 파종기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

906/1150 Row 906: application_number: 1020200025163, combined_string: invention_title: 식물재배용 조명기구 abstract: 본 발명에 따른 식물재배용 조명기구는 몸체부의 구성이 복잡하지 않고, 제조단가를 낮출 수 있고, 몸체부를 만드는데 필요한 금형의 개수를 줄일 수 있다. 상기 식물재배용 조명기구는 몸체부, 몸체부 내의 장착부에 장착되는 복수의 엘이디 모듈을 가지며, 상기 몸체부는, 바닥부 및 상기 바닥부의 양측 가장자리의 벽부를 가지는 복수의 단위 프레임이 연결수단을 통해 측방으로 서로 연결되되, 이웃하여 배치된 복수의 상기 엘이디 모듈은 상방을 향해 예각으로 꺾이도록 배치된 것을 포함하는 구성을 한다. claims: 제1장착부, 상기 제1장착부의 일측에 형성되는 제2장착부 및 상기 제2장착부의 반대편에 형성되는 제3장착부를 구비하는 몸체부;상기 제1장착부에 장착되어 하방을 향해 제1색깔의 광을 발하는 제1엘이디 모듈;상기 제1엘이디 모듈에 대해 상방을 향해 예각으로 꺾인 상태로 상기 제2장착부에 장착되어 일부만 상기 제1색깔의 광과 중첩되도록 제2색깔의 광을 발하는 제2엘이디 모듈;상기 제1엘이디 모듈에 대해 상방을 향해 예각으로 꺾인 상태로 상기 제3장착부에 장착되어 일부만 상기 제1색깔의 광과 중첩되도록 제3색깔의 광을 발하는 제3엘이디 모듈; 및상기 몸체부에 결합되어 상기 제1엘이디 모듈 내지 제3엘이디 모듈을 보호하는 윈도우를 포함하고,상기 몸체부는,바닥부와 상기 바닥부의 양측 가장자리에서 하방으로 돌출되어 상기 바닥부와 함께 하방으로 개구가 형성된 채널을 형성하며 내면에 상기 제1장착부 내지 상기 제3장착부 중 어느 하나가 형성되는 한 쌍의 벽부를 포함하고, 상기 한 쌍의 벽부의 외면은 상방으로 갈수록 서로 점점 가까워지도록 경사지게 형성되고, 양측 가장자리 상측부에 형성되는 축공을 가지는 회동연결부를 구비하는 단위 프레임 3개가 상기 축공에 결합되는 축을 통해 상호 회동 가능하게 측방으로 연결되어 구성되고,양단이 양측 가장자리의 상기 단위 프레임의 바깥쪽의 상기 벽부에 각각 결합되고 상기 몸체부에 간격을 두고 결합되는 적어도 한 쌍의 결합구;적어도 한 쌍의 상기 결합구의 중앙부에 각각 연결되어 상기 몸체부를 수평 상태로 유지하다가 승강시키기 위한 승강수단; 및상기 축과 적어도 한 쌍의 상기 결합구 사이 또는 양측 가장자리의 상기 단위 프레임의 사이에 설치되어 이웃하는 상기 단위 프레임 간에 꺾임각도를 조절할 수 있도록 하기 위한 각도조절구를 더 포함하고,상기 각도조절구는,ⅰ) 양측 가장자리의 상기 단위 프레임이 상기 축을 중심으로 일정 이상 상방으로 회동되지 않게 상기 축을 상방으로 당겨줄 수 있도록 상기 축에 연결된 축연결부 및 상기 축연결부와 결합되고 상기 결합구의 임의의 위치에 고정될 수 있는 고정구를 구비하여 구성된 것; 및ⅱ) 양측 가장자리의 상기 단위 프레임 사이를 지지하여 양측 가장자리의 상기 단위 프레임이 상기 축을 중심으로 일정 이상 상방으로 회동되지 않도록 하는 회동방지 바를 구비하여 구성된 것; 중 어느 하나를 포함하는 것을 특징으로 하는 식물재배용 조명기구., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

907/1150 Row 907: application_number: 1020200023078, combined_string: invention_title: 애플수박 재배방법 abstract: 본 발명은 적당한 과실비대가 이루어지고 높은 당도를 가지는 상품성이 높은 애플수박을 수확할 수 있는 것은 물론이며, 종래의 재배방법에 비해 수확량이 증가되어 수박농가의 수입증대를 꾀할 수 있는 새로운 방식의 애플수박 재배방법에 대한 것이다. claims: 애플수박 모종을 정식하는 정식단계;정식 후 곁가지가 생기면, 원줄기와 2개의 아들줄기만 남기고 나머지 곁가지를 제거하는 곁가지 제거단계;원줄기와 2개의 아들줄기를 9~10마디가 생길 때까지 유인하여 키우는 1차 재배단계;상기 1차 재배단계에서 키운 원줄기와 아들줄기의 9~10번째 마디에 개화한 암꽃을 수정시키는 1차 수정단계;상기 1차 수정단계 이후에 상기 원줄기와 아들줄기를 18~19마디가 생길 때까지 유인하여 키우는 2차 재배단계;상기 2차 재배단계에서 키운 상기 원줄기와 아들줄기의 18~19번째 마디에 개화한 암꽃을 수정시키고, 다른 마디에 개화한 암꽃은 제거하는 2차 수정단계;상기 1차 및 2차 수정단계에서 착과된 애플수박이 성숙되도록 키우는 3차 재배단계;상기 3차 재배단계에서 숙성된 애플수박을 수확하는 1차 수확단계; 상기 1차 수확단계가 끝난 후 상기 원줄기와 아들줄기를 곁가지를 제거하지 않고 키워서 줄기수를 늘리며, 모든 줄기에서 개화한 암꽃을 수정, 착과시켜서 성숙시키는 방목재배단계; 및 상기 방목재배단계에서 성숙된 애플수박을 수확하는 방목수확단계;를 포함하며,상기 1차 수정단계 및 상기 2차 수정단계에서는 각각 1차 수정단계에서 수정되어 착과된 애플수박과 2차 수정단계에서 수정되어 착과된 애플수박을 구별하기 위해 1차 수정단계에서 수정되어 착과된 수박과 2차 수정단계에서 수정되어 착과된 애플수박에 표시를 하는 것을 특징으로 하는 애플수박 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

908/1150 Row 908: application_number: 1020200022063, combined_string: invention_title: 재배용수 절감을 위한 무농약 친환경 콩나물 재배방법 abstract: 본 발명은 재배용수 절감을 위한 무농약 친환경 콩나물 재배방법에 관한 것으로, 더욱 상세하게는 재배용수 절감을 위한 오존수를 활용한 무농약 친환경 콩나물 재배방법에 있어서, 갈근 및 섬쑥부쟁이를 혼합한 식물 원료를 발효시켜 제조한 재배용수로 콩나물을 재배함으로써 콩나물의 비린내와 저장성을 현저히 개선할 수 있는 재배용수 절감을 위한 무농약 친환경 콩나물 재배방법에 관한 것이다. claims: 콩을 물에 침지시켜 24시간 동안 불린 다음, 상기 불린 콩을 건져내어 4 ~ 6시간 동안 방치하여 발아시키는 단계(S10);갈근 및 섬쑥부쟁이를 동일 비율로 혼합한 후 열수로 추출한 열수 추출액을 제조하는 단계(S20);미생물 배양 배지를 멸균하는 단계(S30);상기 단계에서 얻은 배지를 냉각 후 류코노스톡 메센테로이데스(Leuconostoc mesenteroides) 및 엔테로코커스 패시움(Enterococcus faecium)으로 이루어지는 미생물 복합균을 접종 후 진탕 배양하여 미생물 복합균 배양액을 제조하는 단계(S40);상기 열수 추출액에 효모추출물(yeast extract) 및 포도당을 첨가하여 멸균 후 상기 미생물 복합균 배양액을 첨가 후 진탕배양하여 미생물 복합균 발효액을 제조하는 단계(S50);상기 미생물 복합균 발효액을 물로 희석하여 재배용수를 제조하는 단계(S60);상기 재배용수를 저장탱크에 저장하고, 오존 폭기에 의해 상기 재배용수를 살균 및 정화처리하는 단계(S70);용존 오존이 소량 잔류되어 있는 상태의 상기 재배용수를 노즐을 이용하여 발아된 콩에 살수하는 단계(S80);살수된 상기 재배용수를 물받이를 통하여 집수하고 침전탱크로 회수하는 단계(S90);상기 침전탱크로 회수된 재배용수를 순환펌프에 의해 상기 저장탱크로 이동시키는 단계(S100);상기 저장탱크로 이동된 재배용수를 오존으로 살균하는 단계(S110); 및콩나물의 재배가 완료될 때까지 상기 재배용수를 계속해서 순환시키고 재배를 완료한 후의 재배용수를 용존 오존으로 정화시켜 외부로 배출시키는 단계(S120);를 포함하는 것을 특징으로 하는 재배용수 절감을 위한 무농약 친환경 콩나물 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

909/1150 Row 909: application_number: 1020200015527, combined_string: invention_title: LED를 이용한 새싹삼의 재배 또는 사포닌 함량 증진 방법 abstract: 본 발명은 LED를 이용한 새싹삼의 재배 또는 사포닌 함량 증진 방법에 관한 것이다. 구체적으로, 본 발명에 따른 새싹삼 재배 방법은 새싹삼의 지상부 및 지하부의 생체중 및 엽면적, 지상부의 길이 증가, 지상부 및 지하부의 건물중 증가, 및 엽록소 함량 증가를 촉진할뿐만 아니라, 새싹삼에 포함되는 사포닌 함량을 유의적으로 증가시키므로, 새싹삼을 재배하거나 새싹삼에 포함된 사포닌의 함량을 증진시키는데 유용하게 사용될 수 있다. claims: 광원으로 적색 및 녹색 LED(light emitting diode)를 7:1 내지 9.5:1의 비율로 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 배양방법.광원으로 적색 및 녹색 LED를 7:1 내지 9.5:1의 비율로 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 사포닌 함량 증진방법.광원으로 근적외선을 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 배양방법.광원으로 근적외선을 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 사포닌 함량 증진방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

910/1150 Row 910: application_number: 1020200009991, combined_string: invention_title: 친환경 물공급 기능을 구비한 화단 abstract: 본 발명은 친환경 물공급 기능을 구비한 화단에 관한 것으로, 더욱 상세하게는 사용자가 휴식을 취할 수 있고 태양광패널(221)이 설치된 접이용 의자를 구비하고 접이용 의자의 회전에 의해 물이 펌핑되어 화단에 자동으로 공급할 수 있으며 태양광패널(221)을 통해 생산된 전력은 조명으로 사용될 수 있고, 내부에 단열재(111b)와 부직포(111a)가 다층 구조로 배치되어 물탱크(120)의 물을 화단에 공급할 수 있고 여름철의 습윤 비산 방지와 겨울철의 동해 방지 효과가 있는 친환경 물공급 기능을 구비한 화단에 관한 것이다.이를 위해 본 발명은, 식물이 식재되는 화분틀(110)과, 상기 화분틀(110)의 하단에 설치되는 물탱크(120)와, 상기 물탱크(120)에 저수된 물을 상기 식물 주변으로 공급하도록 상기 물탱크(120)에 장착되어 상기 화분틀(110) 내부로 연장되는 물공급부(130)를 포함하는 화분(100); 상기 화분틀(110)의 외면에 장착되는 의자틀(210)과, 저면이 상향 경사진 상태에서 상면이 수평인 상태로 회전되도록 상기 의자틀(210)에 장착되고 회전에 의해 상기 물공급부(130)를 펌핑하는 의자밑판(220)과, 태양광 발전을 위하여 상기 의자밑판(220)의 저면에 장착되는 태양광패널(221)을 포함하는 의자부(200);를 포함하여 이루어진다. claims: 식물이 식재되는 화분틀(110)과, 상기 화분틀(110)의 하단에 설치되는 물탱크(120)와, 상기 물탱크(120)에 저수된 물을 상기 식물 주변으로 공급하도록 상기 물탱크(120)에 장착되어 상기 화분틀(110) 내부로 연장되는 물공급부(130)를 포함하는 화분(100);상기 화분틀(110)의 외면에 장착되는 의자틀(210)과, 저면이 상향 경사진 상태에서 상면이 수평인 상태로 회전되도록 상기 의자틀(210)에 장착되고 회전에 의해 상기 물공급부(130)를 펌핑하는 의자밑판(220)과, 태양광 발전을 위하여 상기 의자밑판(220)의 저면에 장착되는 태양광패널(221)을 포함하는 의자부(200);를 포함하고,상기 물공급부(130)는,유입구(136)를 통해 물을 공급받는 실린더(131)와, 일단이 상기 화분틀(110) 내의 토양에 설치되고 타단이 상기 실린더(131)에 형성된 배출구(137)에 연결되는 공급호스(132)와, 일단이 상기 의자밑판(220)의 회전축에 결합되는 연결부(133)와, 상기 연결부(133)의 타단에 결합되고 상기 실린더(131) 안에서 왕복 운동하며 상기 의자밑판(220)의 회전에 의해 상기 실린더(131)에 공급된 물을 일측으로 밀어 상기 공급호스(132)로 배출하는 피스톤(134)과, 상기 피스톤(134)이 초기 위치로 복원되도록 상기 피스톤(134)을 타측으로 밀어줄 수 있는 스프링(135)을 포함하며,상기 의자틀(210)의 내측면에는, 상기 태양광패널(221)이 상면을 향한 상태에서 상기 의자밑판(220)의 회전을 제한하는 돌출부(212)가 더 구비되는 것을 특징으로 하는 친환경 물공급 기능을 구비한 화단., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

911/1150 Row 911: application_number: 1020200004636, combined_string: invention_title: 잔디 식재방법 abstract: 본 발명은 잔디 식재방법에 관한 것으로서, 식재에 적합한 잔디를 선별한 후 세척하고, 천연살균제를 이용하여 살균하는 잔디 전처리단계와, 식재지에 포함된 잡석 및 불순물을 제거한 후, 식재지의 사면을 정리하는 식재지 정리단계와, 상기 잔디 전처리단계에서 전처리된 잔디를 상기 식재지 정리단계에서 정리된 식재지에 산포하는 잔디 산포단계와, 상기 산포된 잔디를 덮도록 상기 식재지에 전체적으로 네트를 설치하는 네트 설치단계와, 상기 네트를 덮도록 상기 식재지에 기능성 상토를 뿌려서 투입하는 기능성 상토 투입단계 및 상기 뿌려진 기능성 상토와 상기 산포된 잔디를 일정하게 다져주는 롤링단계를 포함하여 이루어진 것을 특징으로 한다.본 발명에 따르면, 식재를 위한 최상의 상태를 갖는 잔디 및 식재지를 제공함에 따라 빠른 시간 안에 균질한 잔디 활착을 유도하고, 가장 손쉽고 빠르게 시공할 수 있는 효과가 있다. 또한, 골프장, 각종 경기장, 공원, 조경지, 학교, 유치원, 어린이집 등에 적용하기 위하여 인체에 유해한 소독제, 살균제 대신에, 자체적으로 제조한 천연살균제, 토양개량제, 기능성 상토 등을 최적의 비율로 혼합하여 유해독성이 전혀 없으며, 잔디의 안정적인 활착 및 생육을 촉진시킬 수 있는 효과가 있다. claims: 식재에 적합한 잔디(10)를 선별한 후 세척하고, 천연살균제를 이용하여 살균하는 잔디 전처리단계(S10);식재지(20)에 포함된 잡석 및 불순물을 제거한 후, 식재지(20)의 사면을 정리하는 식재지 정리단계(S20);상기 잔디 전처리단계(S10)에서 전처리된 잔디를 상기 식재지 정리단계(S20)에서 정리된 식재지(20)에 산포하는 잔디 산포단계(S30);상기 산포된 잔디(10)를 덮도록 상기 식재지(20)에 전체적으로 네트(30)를 설치하는 네트 설치단계(S40);상기 네트(30)를 덮도록 상기 식재지(20)에 기능성 상토(40)를 뿌려서 투입하는 기능성 상토 투입단계(S50); 및상기 뿌려진 기능성 상토(40)와 상기 산포된 잔디(10)를 일정하게 다져주는 롤링단계(S60); 를 포함하여 이루어진 것을 특징으로 하는 잔디 식재방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

912/1150 Row 912: application_number: 1020200000666, combined_string: invention_title: 저울형 화분받침대 및 화분 abstract: 저울형 화분받침대 및 화분을 개시한다.개시된 저울형 화분받침대 및 화분은, 화분의 화초에 대한 급수시기를 화분의 토양 수분 변화 에 따른 중량 감소의 표시로 알 수 있게 하여, 급수시기를 빠르고, 정확하게 알려주면서 화분 받침대로 사용할 수 있게 하고, 화초에 대한 급수가 일정 기일 동안 유지될 수 있게 한다. claims: 상,하부 케이스가 분리되게 결합되어 상부로는 화초가 식재된 화분을 올려 놓을수 있는 화분 재치부를 제공하고, 또한 내부로는 소정 넓이의 공간을 제공하는 소정 형태의 본체;상기 공간에 내장되어 상기 재치부에 올려지는 상기 화분의 토양에 함유된 수분의 변화에 따른 상기 화분의 중량변화를 측정할 수 있게 하는 전자저울 혹은 스프링 저울; 및상기 본체의 어느 일측에 외부로 노출되게 설치되어 상기 전자 저울 혹은 스프링 저울로부터 측정된 상기 화분의 중량 변화를 화분 사용자들이 알 수 있게 표시하여, 화분 사용자들로 하여금 상기 화분의 중량 변화 표시에 따라 화분에 급수 여부를 실행하게 하는 화분중량 알림 표시부;를 포함하는 저울형 화분받침대.내외부용기로 이루어지며 하부에는 내부용기 측으로 급수되는 물이 배수공을 통하여 배출되어 저장될 수 있는 저수공간을 형성하는 화분 본체; 상기 내부용기의 개구부에 상기 하부용기의 개구부보다 더 크게 형성되어 상기 내부용기가 상기 하부용기에 걸리는 상태로 결합되게 하여 상기 내외부용기의 하부측 사이에 저수공간을 형성할 수 있게 하는 환형턱부; 및상기 내부용기의 중앙에 설치된 흡수공을 구비하고, 상기 외부용기의 내저부에 돌출 설치된 환형돌출턱의 환형홈에 수용된 상태로 지지되면서 상기 흡수공을 통해 상기 내부용기의 내부로 돌출 설치됨에 의해 상기 저수공간으로부터 상기 흡수공을 통하여 상기 내부용기에 위치되게 하는 흡수천을 고정 지지하는 고정 유지구로 이루어진 흡수부;를 포함하는 화분., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

913/1150 Row 913: application_number: 1020200000264, combined_string: invention_title: 바코드로 식물의 정보 관리가 관리되는 무인원격 식물재배 시스템 abstract: 본 발명에 따른 바코드로 식물의 정보 관리가 관리되는 무인원격 식물재배 시스템는, 체인을 타고 승강되는 다수의 식물재배대가 설치된 식물재배장치와, 각 식물재배대에서 현재 재배하고 있는 식물의 종류, 파종일자, 이식일자, 생산자, 관리자, 높이 등 식물에 관련된 정보를 제목과 함께 날짜, 숫자, 문자, 영상, 이미지 등으로 저장하여 재배 중인 식물 정보를 총괄하여 관리할 수 있게 되고, 식물 정보가 저장되는 온라인 서버인 정보 관리서버와 바코드 또는 QR코드를 생성하고 이미지로 출력하는 바코드 발급부와 상기 바코드 또는 QR코드를 적외선 또는 카메라로 리딩하여 식물 정보에 접속할 수 있도록 하는 바코드 리더부와 식물 정보를 화면으로 표시해주는 식물 정보 표시부를 제공하여서 바코드 또는 QR코드를 이용하여 식물 정보에 사용자가 매우 용이하게 접근할 수 있으며, 사용자가 편리하게 식물 정보를 입력, 수정, 삭제, 열람하는 것이 가능하고, 물과 필요한 영양소를 식물재배대에 공급하는 물영양소공급부와, 식물재배대의 온도 및 습도를 측정하는 측정센서부와, 식물의 생장에 바람직한 온도와 습도를 공급하는 식물재배하우스을 포함하여서 식물을 사람의 노동력으로 재배하지 않고 무인원격으로 재배할 수 있다. claims: 바코드로 식물의 이력 등 정보 관리가 가능한 무인원격 식물재배 시스템(A)에 있어서,상기 바코드로 식물의 이력 등 정보 관리가 가능한 무인원격 식물재배 시스템(A)은, 식물재배장치(1)와, 식물관리장치(2)를 포함하고,상기 식물재배장치(1)는, 바닥에는 한쌍의 수직프레임(10)이 소정 간격을 두고 서로 대칭되게 수직으로 설치되고, 상기 수직프레임(10) 사이의 일단부에 회전 가능하게 구동축(21)이 설치되고, 상기 수직프레임(10) 사이의 타단부에 회전 가능하게 종동축(22)이 설치되고, 상기 수직프레임(10)의 외측에는 외측 프레임(11)이 설치되어 식물재배장치(1)의 전체를 지지하고,상기 구동축(21)과 종동축(22)은 이송체인(30)으로 연결되고,상기 이송체인(30)상에 다수의 식물재배대(50)가 설치되고,상기 식물재배대(50)는 상기 이송체인(30)상에 고정수단(40)에 의하여 고정되고,상기 고정수단(40)은 상기 이송체인(30)에 다수의 식물재배대(50)가 일정간격으로 다단으로 설치되고, 상기 식물재배대(50)는 이송체인(30)의 회전에 의해 승,하강 되게 구동되고, 상기 식물재배대(50)의 상기 고정수단(40)에 힌지고정된 힌지축(42)의 단부면에는 바코드 또는 QR코드(51)가 게시되고,상기 고정수단(4)은, 이송체인(30)의 2개 지점에서 힌지고정된 2개의 링크판(41)과, 상기 2개의 링크판(41)이 외측으로 1개의 지점에서 합류되어 힌지부를 이루는 힌지축(42)과, 상기 힌지축(42)의 외측으로 힌지고정되며 연장된 연장부(43)와, 상기 연장부(43)의 단부에 회전되게 고정된 회전롤러(44)와, 상기 회전롤러(44)가 내부에 삽입되어 회전되며 이동이 안내되는 안내홈레일(45)을 포함하고, 상기 안내홈레일(45)은 만곡안내홈판(45a)과 수직안내홈판(45b)으로 구성되고, 상기 고정수단(4)의 힌지축(42)에는 식물재배대(5)가 고정되어 있는 것을 특징으로 하는 바코드로 식물의 이력 등 정보 관리가 가능한 무인원격 식물재배 시스템, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

914/1150 Row 914: application_number: 1020190178893, combined_string: invention_title: 저칼륨 채소 재배를 위한 수경재배장치 abstract: 본 발명은 LED 램프가 설치된 상부 프레임; 상기 상부 프레임의 하측에 배치되되, 상면이 개방된 하부 프레임; 및 상기 하부 프레임의 상부에 배치되되, 식물이 안착될 수 있는 재배홀이 형성된 안착 플레이트;를 포함하되, 상기 하부 프레임에는, 칼륨이 포함된 양액이 수용되는 제1 수용공간과, 상기 제1 수용공간과 분리되어, 칼륨이 포함되지 않은 양액이 수용되는 제2 수용공간이 형성되는 저칼륨 채소 재배를 위한 수경재배장치를 제공할 수 있다. claims: LED 램프가 설치된 상부 프레임;상기 상부 프레임의 하측에 배치되되, 상면이 개방된 하부 프레임; 및상기 하부 프레임의 상부에 배치되되, 식물이 안착될 수 있는 재배홀이 형성된 안착 플레이트;를 포함하되,상기 하부 프레임에는,칼륨이 포함된 양액이 수용되는 제1 수용공간과,상기 제1 수용공간과 분리되어, 칼륨이 포함되지 않은 양액이 수용되는 제2 수용공간이 형성되는 저칼륨 채소 재배를 위한 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

915/1150 Row 915: application_number: 1020190179425, combined_string: invention_title: 분질배유를 지니는 조생종 흑미 신규 계통, 아로마티 및 이를 유효성분으로 함유하는 식품조성물 abstract: 본 발명은 건식제분을 이용한 쌀가루 제조에 적합한 분질배유를 포함하면서도, 안토시아닌을 높은 함량으로 포함하고, 상기 안토시아닌을 용이하게 용출할 수 있는, 신규한 조생종 흑미 계통인 '아로마티', 상기 '아로마티'의 육종방법, 상기 '아로마티'의 종자를 포함하는 건식제분용 조성물, 상기 '아로마티'의 종자를 건식제분하여 수득한 쌀가루 및 상기 '아로마티'의 식물 또는 종자를 포함하는 식품 조성물에 관한 것이다. 본 발명에서 제공하는 '아로마티'는 분질배유를 지니며 생리기능성과 천연색소로서의 장점을 지니는 안토시아닌을 주성분으로 하면서 구수한 향 성분인 2AP를 함유하는 신규한 분질흑미 품종으로, 뜨거운 물을 현미에 첨가하여 항산화물질인 안토시아닌과 더불어 고유의 구수한 향을 내어놓는 양질의 흑미차를 조제할 수 있을 뿐 아니라, 비용이 저렴한 건식제분으로 흑미가루를 용이하게 가공할 수 있어 천연 항산화 색소가 첨가되는 다양한 쌀 가공식품 제조에 활용될 수 있을 것이다. claims: 건식제분에 적합하고, 안토시아닌을 높은 함량으로 포함하며, 수탁번호 KACC 98075P로 기탁된 자포니카 벼 계통의 흑미벼 품종 Oryza sativa 아로마티(AromaT).제1항에 있어서,상기 Oryza sativa 아로마티(AromaT)는 하기 특징을 나타내는 것인, Oryza sativa 아로마티(AromaT):(a) 보통기재배 출수기 (월/일, 전주) : 7/30(b) 이모작재배 출수기 (월/일, 전주) : 8/14(c) 만기재배 출수기 (월/일, 전주) : 8/26(d) 현미 길이 (mm; 만기재배, 전주) : 5.96(e) 현미 너비 (mm; 만기재배, 전주) : 2.73(f) 색소 성분 Cyanidin-3-glucoside 함량 (mg/100g ; 만기재배, 전주) : 570.5(g) 향기 성분 2-acetyl-pyrroline 함량 (μg/g ; 만기재배, 전주) : 1.09.(a) '수원542호' 품종과 '흑진주' 품종을 교배하여 얻어진 F1 종자를 계통 육종법에 의거하여 F6 세대까지 진전시켜, 분질배유(flo7) 형질이 고정되고, Ra와 Rd 유전자 모두가 '흑진주' 품종의 유전자형으로 고정된 계통을 확립하는 단계; 및 (b) 상기 확립된 계통의 종자들 중, 현미의 과피에서 발현되는 안토시아닌 색소의 강도가 일정한 수준을 나타내는 벼 품종을 선별하는 단계를 포함하는, Oryza sativa 아로마티(AromaT)의 육종방법.제1항 내지 제3항 중 어느 한 항의 Oryza sativa 아로마티(AromaT)의 종자를 포함하는 건식제분용 조성물.제1항 내지 제3항 중 어느 한 항의 Oryza sativa 아로마티(AromaT)의 종자를 건식제분하여 수득한 쌀가루.제1항 내지 제3항 중 어느 한 항의 Oryza sativa 아로마티(AromaT)의 식물 또는 이의 종자를 유효성분으로 포함하는 식품 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

916/1150 Row 916: application_number: 1020190178137, combined_string: invention_title: LED 식물재배장치 abstract: 본 발명은 직사광선을 이용하지 않고 LED광원을 통해 식물을 재배 하는 장치에 관한 것으로 LED조명 하부에 있는 식물이 균일한 광량을 조사받음으로써, 식물이 균등하게 생산되어 생산 식물의 전반적인 품질 균일성을 높일 수 있는 효과를 달성할 수 있다. claims: 식물이 재배되는 재배베드;PCB 기판과 상기 PCB 기판에 설치된 복수의 LED 소자를 구비하며, 상기 재배베드 상부에서 상기 재배베드를 향해 광을 조사하는 LED 모듈을 포함하고,상기 복수의 LED 소자에 있어서 소자 사이의 간격은 상기 PCB 기판의 중앙부보다 가장자리에서 더 좁은 것을 특징으로 하는 LED 식물재배장치.식물이 재배되는 재배베드;PCB 기판과 상기 PCB 기판에 설치된 복수의 LED 소자를 구비하며, 상기 재배베드 상부에서 상기 재배베드를 향해 광을 조사하는 LED 모듈을 포함하고,상기 LED 소자는 상기 PCB 기판의 중앙부보다 가장자리에서 광량이 더 큰 것을 특징으로 하는 LED 식물재배장치.식물이 재배되는 재배베드;PCB 기판과 상기 PCB 기판에 설치된 복수의 LED 소자를 구비하며, 상기 재배베드 상부에서 상기 재배베드를 향해 광을 조사하는 LED 모듈을 포함하고,상기 LED 소자는 상기 LED 모듈로부터 이격된 설정 거리에서 단위 면적당 조사되는 광량이 중앙부와 가장자리에서 균일하도록 구비된 것을 특징으로 하는 LED 식물재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

917/1150 Row 917: application_number: 1020210033039, combined_string: invention_title: 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철,분진발생공장에서 발생시키는 비산먼지 제거기능 및 혐오성 냄새 및 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템 abstract: 상측에는 본체 하우징(2000)이 구성되고;상기 본체 하우징(2000)의 내부에는 유입라인(1002)과 다수개의 이송라인(1001,1012)과 배출라인(3000)이 결합 구성되는 구조;상기 유입라인(1002)의 일측에는 유입펌프(1000)가 결합 구성되는 구조;상기 유입라인(1002)의 상측 부분은 건축물 또는 공장 또는 비행기 또는 버스 또는 차량 또는 공연장을 구성시킨 구조의 하우징(8888) 상측부분과 결합 구성되는 구조;상기 유입라인(1002)에는 비중이 가벼운 오염된 공기들을 유입시켜주는 다수개의 유입구(1003)가 구성되는 구조;상기 본체 하우징(2000)의 하측에는 다수개의 수납용 체결구(1004)가 상기 유입라인(1002)과 다수개의 상기 이송라인(1001,1012)과 상기 배출라인(3000)과 결합 구성되는 구조;상기 배출라인(3000)의 일측은 건축물 또는 공장 또는 비행기 또는 버스 또는 차량 또는 공연장을 구성시킨 하우징(8888)의 하단부 바닥부분에 설치되는 구조; 상기 배출라인(3000)의 상부에는 기체성 물질분자들을 분출시켜주는 다수개의 분출구(3003)가 결합 구성되는 구조;상기 이송라인(1001,1012)의 하단부에는 비중이 무거운 유체성 물질분자들은 하측 방향으로 이동시켜 주도록 작용하면서 비중이 가벼운 기체성 물질분자들은 일측 방향으로 이송시켜주도록 작용하는 중력 유도하우징(1007)이 각각 구성되는 구조;상기 중력 유도하우징(1007)의 하단부에는 중력 유도파이프(1005)가 결합 구성되는 구조;상기 중력 유도파이프(1005)의 하단부에는 유체성 물질분자 수집용 하우징(1006,1009)이 각각 구성되는 구조;상기 유체성 물질분자 수집용 하우징(1006,1009)의 일측에는 유체성물질분자 또는 비중이 가벼운 오염물질성 물질분자들을 외부로 배출하여 주는 하단 배출파이프(1010)가 배출조절밸브(1011)와 결합 구성되는 구조;상기 수납용 체결구(1004)의 하단부에는 배출량 조절밸브(3002)와 배출파이프가 결합 구성되어 있는 액체성 필터부재하우징(1,2,3)이 착탈이 용이하도록 상기 수납용 체결구(1004)와 결합 구성되는 친환경 다기능 공기 정화시스템(888888)을 건축물 또는 공장 또는 비행기 또는 버스 또는 차량 또는 공연장을 구성시킨 하우징(8888)에 설치한 후 상기 액체성 필터부재하우징(1,2,3)의 내부에 물 또는 알콜이나 소금물을 구성하고 있는 유체성 물질분자로 구성되어 지는 필터 부재들을 순차적으로 충진시킨 상태에서 상기 유입라인(1002)과 결합 되어 있는 상기 유입펌프(1000)를 이용하여 상기 하우징(8888)의 내부와 상측 부분에 포진하고 있는 비중이 가벼운 오염된 공기들을 포집하여 상기 액체성 필터부재하우징(1,2,3)의 내부로 이송시켜서 상기 액체성 필터부재하우징(1,2,3)의 내부에 충진되어 있는 물 또는 알콜이나 소금물로 구성되어 지는 필터 부재들이 발생시키는 필터링 기능을 이용하여 비중이 무거운 깨끗한 공기와 결합 되어 있는 비중이 가벼운 오염물질성 물질분자로 구성되어 있는 미세먼지들을 제거시켜주는 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 가지는 다기능 공기정화시스템을 이용하여 사람이 거주하는 건축물, 학교, 군대의 막사, 공장, 동물을 사육하는 축사, 사무실에 존재하는 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 공기 정화시스템에 관한 발명이다 claims: 친환경 다기능 공기 정화시스템의 구조는 상측에는 본체 하우징이 구성되는 구조;상기 본체 하우징의 내부에는 유입라인과 다수개의 이송라인과 배출라인이 결합 구성되는 구조;상기 유입라인의 일측에는 유입펌프가 결합 구성되는 구조;상기 유입펌프의 타측에는 살균시스템하우징을 설치한 후 상기 살균시스템하우징의 내부에 -전극과 +전극을 교차 설치하여 유입라인을 통하여 유입되는 미세균들과 바이러스 균들을 살균하도록 구성되는 구조;상기 이송라인의 하단부에는 비중이 무거운 유체성 물질분자들은 하측 방향으로 이동시켜 주도록 작용하면서 비중이 가벼운 기체성 물질분자들은 일측 방향으로 이송시켜주도록 작용하는 중력 유도하우징이 각각 구성되는 구조; 상기 본체 하우징의 하측에는 다수개의 수납용 체결구가 구성되어 상기 유입라인과 다수개의 상기 이송라인과 상기 배출라인을 상호 결합시킨 구조;상기 중력 유도하우징의 하단부에는 중력 유도파이프가 결합 구성되는 구조;상기 중력 유도파이프의 하단부에는 유체성 물질분자 수집용 하우징이 다수개 구성되는 구조;상기 유체성 물질분자 수집용 하우징의 일측에는 유체성물질분자 또는 비중이 가벼운 오염물질성 물질분자들을 외부로 배출하여 주는 하단 배출파이프가 배출조절밸브와 결합 구성되는 구조;상기 수납용 체결구의 하단부에는 배출량 조절밸브와 배출파이프가 결합 구성되어 액체를 투입하도록 구성되는 액체성 필터부재하우징이 착탈이 용이하도록 상기 수납용 체결구와 결합 구성되는 구조;상기 액체성 필터부재하우징의 내부에는 상기 이송라인이 결합 구성되는 구조;액체성 필터부재하우징과 상기 유체성 물질분자 수집용 하우징의 일측 또는 타측에 전자파발생기를 설치하여 중력의 작용에 의해 상기 액체성 필터부재하우징과 상기 유체성 물질분자 수집용 하우징의 내부로 유입되는 기체성 물질분자 또는 액체성 물질분자 또는 비중이 가벼운 유체성 물질분자들을 타격하여 이들 물질분자가 가지고 있는 분자구조를 변형시키도록 구성되는 친환경 다기능 공기 정화시스템을 사람이 거주하는 아파트 또는 사무실이나 학교 또는 군대의 막사 또는 사람이 거주하는 건축물 또는 가축을 사육하는 농장 또는 공장 또는 발전소 또는 제철소 또는 비행기 또는 버스 또는 차량 또는 식물을 재배하는 재배사 또는 공연장의 구조로 구성되는 하우징에 설치한 후 상기 액체성 필터부재하우징와 상기 유체성 물질분자 수집용 하우징의 내부에 향기를 발산시켜주는 향기 발산 부재 또는 물 또는 알콜이나 소금물 또는 바닷물 또는 숯과 물을 희석하여 만든 숯 혼합물로 구성되어 지는 필터 부재들을 순차적으로 충진시킨 상태에서 상기 유입라인과 결합 되어 있는 상기 유입펌프를 이용하여 상기 하우징에서 발생시키는 오염된 공기 또는 상기 하우징의 내부와 상측 부분에 포진하고 있는 비중이 가벼운 오염된 공기들을 포집하여 상기 액체성 필터부재하우징과 상기 유체성 물질분자 수집용 하우징의 내부로 이송시켜서 상기 액체성 필터부재하우징의 내부와 상기 유체성 물질분자 수집용 하우징에 충진되어 있는 물 또는 알콜이나 소금물로 구성되는 필터 부재들이 발생시키는 필터링 기능을 이용하여 비중이 무거운 깨끗한 공기와 결합 되어 있는 비중이 가벼운 오염물질성 물질분자로 구성되어 있는 미세먼지들을 제거시켜주는 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 주도록 구성되는 친환경 다기능 공기 정화시스템을 이용하여 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철,분진발생공장에서 발생시키는 비산먼지 제거기능 및 혐오성 냄새 및 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템친환경 다기능 공기 정화시스템의 구조는 하측에는 본체 하우징이 구성되는 구조;상기 본체 하우징의 상측에는 공기 주입장치(미도시)와 결합 구성되는 유입라인이 일측의 상단부는 ㄱ자 형태이면서 하단부는 ㄷ자 형태로 구성되는 구조;상기 유입라인의 상부에는 착탈식으로 구성되는 수납용 체결구가 상부에 구성되어 있는 제1 여과하우징이 구성되는 구조;상기 제1 여과하우징의 내부에는 광물성 물질이나 바닷물 또는 소금물 또는 민물 또는 화공약품으로 구성되는 유체성 물질분자로 구성된 여과부재(점선으로 표시하였으나 부호는 미도시)를 상기 유입라인의 상층부분 까지 연결 구성되는 제1배출구가 잠기지 않는 위치까지 투입시킨 구조;상기 제1 여과하우징의 다음 단계에는 공기와 결합되어 있는 수분을 분리시켜주도록 작용하는 제1수분 분리하우징이 구성되는 구조;상기 제1 여과하우징과 상기 제1수분 분리하우징의 사이에는 하단부 제1연결 파이프가 상기 제1 여과하우징 방향으로 경사지게 구성되어 상기 제1수분 분리하우징의 내부로 유입되는 유체성 물질분자들을 상기 제1 여과하우징으로 유입시켜주도록 작용하는 구조;상기 제1 여과하우징의 하단부분과 상기 제1수분 분리하우징의 상단부 사이에는 상기 여과부재에 의해 제1 유입구가 잠수된 상태가 되는 위치를 기준으로 상기 제1수분 분리하우징의 상측 부분까지 ㄷ자 형태로 연결하여 2차 연결 파이프가 연결 구성되는 구조;상기 제1수분 분리하우징의 다음 단계에는 수납용 체결구가 상부에 구성되어 있는 제2 여과하우징을 구성시킨 구조;상기 제2 여과하우징의 내부에는 광물성 물질이나 바닷물 또는 소금물 또는 민물 또는 화공약품으로 구성되는 액체로 구성된 유체성 물질분자를 이용하여 구성되는 여과부재(점선으로 표시하였으나 부호는 미도시)를 투입시킨 구조;상기 제1수분 분리하우징의 상측부분과 제2 여과하우징의 하측 부분 사이에는 2차 연결 파이프가 ㄷ자 형태로 연장되어 상기 제2 여과하우징의 내부에 투입되어 있는 여과부재의 상측 부분까지 연결된후 상측 부분에 구성되는 제2 배출구가 여과부재에 잠기지 않고 노출되는 형태로 구성되는 구조; 상기 제2 여과하우징의 다음 단계에는 제2수분 분리하우징이 구성되는 구조;상기 제2 여과하우징과 상기 제2수분 분리하우징의 사이에는 하단부 제2연결 파이프가 상기 제2 여과하우징 방향으로 경사지게 구성되어 상기 제2수분 분리하우징의 내부로 유입되는 바닷물 또는 민물 또는 소금과 희석시킨 소금물을 구성하고 있는 유체성 물질분자들을 상기 제2 여과하우징으로 유입시켜주도록 작용하는 연결 구조;상기 제2 여과하우징의 하단부와 제2 수분 분리하우징의 상단부 사이에는 상기 여과부재에 의해 제2 유입구가 잠수된 상태가 되는 위치를 기준으로 상기 제2수분 분리하우징의 상측 부분까지 ㄷ자 형태로 연결되는 3차 연결 파이프가 결합 구성되는 구조;제2 수분 분리하우징의 다음 단계에는 수납용 체결구가 상부에 구성되어 있는 제3 여과하우징이 구성되는 구조;제2 수분 분리하우징의 상측부분과 제3 여과하우징의 하측 부분 사이에는 3차 연결 파이프가 ㄷ자 형태로 연장되어 상기 제3 여과하우징의 내부에 투입되어 있는 여과부재의 상측 부분에 제3 배출구가 노출되는 형태로 결합 구성되는 구조;상기 제3 여과하우징의 다음 단계에는 제3 수분 분리 하우징이 구성되는 구조;상기 제3 여과하우징과 상기 제3 수분 분리 하우징의 사이에는 하단부 제3연결 파이프가 상기 제3 여과하우징 방향으로 경사지게 구성되어 상기 제3수분 분리하우징의 내부로 유입되는 바닷물 이나 민물 또는 소금을 희석하여 만든 소금물을 구성하고 있는 유체성 물질분자들을 상기 제3여과 하우징으로 유입시켜 주도록 연결시킨 구조;상기 제3 여과하우징의 하단부와 제3 수분 분리하우징의 상단부 사이에는 상기 여과부재에 의해 제3 유입구가 잠수된 상태가 되는 위치를 기준으로 상기 제3수분 분리하우징의 상측 부분까지 ㄷ자 형태로 연결하여 4차 연결 파이프를 결합 시킨 구조;상기 4차 연결 파이프의 일측에는 배출파이프를 결합시킨 자연친화적인 친환경 공기정화시스템을 특징으로하는 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철,분진발생공장에서 발생시키는 비산먼지 제거기능 및 혐오성 냄새 및 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

918/1150 Row 918: application_number: 1020210029442, combined_string: invention_title: 산마늘의 재배방법 abstract: 본 발명은 산마늘의 재배방법에 관한 것으로, 더욱 상세하게는 산마늘 종구를 상토에 식재하는 식재단계, 상기 식재단계를 통해 상토에 식재된 산마늘 종구를 발근시키는 발근단계, 상기 발근단계를 통해 발근된 산마늘 종구를 저온에 적응시키는 온도적응단계, 상기 온도적응단계를 통해 낮은 온도에 적응된 산마늘 종구가 식재된 상토를 냉동하는 냉동단계, 상기 냉동단계를 통해 냉동된 상토를 산마늘 출하 25 내지 30일 전에 해동하는 해동단계 및 상기 해동단계를 통해 해동된 상토에 함유된 산마늘 종구를 생장시키는 생장단계로 이루어진다.상기의 과정을 통해 이루어지는 산마늘의 재배방법은 각종 영양성분이 풍부하게 함유된 산마늘을 계절에 관계없이 상시 재배할 수 있고, 원하는 시기에 맞게 계획생산 할 수 있어 스파트 팜 시스템에 적용 가능한 효과를 나타내며, 키트형태인 상토상자가 적용되어 일반인들도 베란다나 텃밭과 같이 협소한 공간에서도 산마늘을 손쉽게 재배할 수 있도록 하는 효과를 나타낸다. claims: 산마늘 종구를 상토에 식재하는 식재단계;상기 식재단계를 통해 상토에 식재된 산마늘 종구를 발근시키는 발근단계;상기 발근단계를 통해 발근된 산마늘 종구를 저온에 적응시키는 온도적응단계;상기 온도적응단계를 통해 낮은 온도에 적응된 산마늘 종구가 식재된 상토를 냉동하는 냉동단계;상기 냉동단계를 통해 냉동된 상토를 산마늘 출하 25 내지 30일 전에 해동하는 해동단계; 및상기 해동단계를 통해 해동된 상토에 함유된 산마늘 종구를 생장시키는 생장단계;로 이루어지며,상기 상토는 코코피트 100 중량부, 질석 20 내지 30 중량부, 퍼라이트 50 내지 70 중량부, 제올라이트 5 내지 10 중량부 및 액비 5 내지 10 중량부로 이루어지고,상기 온도적응단계는 -1 내지 2℃의 온도에서 6 내지 8일 동안 이루어지며,상기 냉동단계는 -15 내지 -10℃의 온도로 이루어지고,상기 해동단계는 0 내지 15℃의 온도에서 6 내지 16일 동안 이루어지는 것을 특징으로 하는 산마늘의 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

919/1150 Row 919: application_number: 1020210012671, combined_string: invention_title: 용암해수를 활용하여 재배한 병풀을 유효성분으로 포함하는 피부 마이크로바이옴 균형 및 여드름 개선용 조성물 abstract: 본 발명은 용암해수로 활용하여 재배한 병풀(Centella asiatica) 추출물을 포함하는 피부 마이크로바이옴 균형 및 여드름 개선용 조성물 내지 이의 용도에 대한 것이다. 본 발명의 병풀 추출물은 탈염 용암해수로 재배되어 세포독성을 나타내지 않고, 세포 내 NO 생성을 억제하고 항염증 활성을 나타내며, 여드름 피부 개선에서 더 나아가 피부 마이크로바이옴의 균형을 개선하는 효과가 있으므로, 피부 마이크로바이옴 균형 개선용 조성물로서 효과적으로 이용될 수 있다. 특히, 상기 조성물은 작약 추출물을 추가적으로 포함함으로써 피부 마이크로바이옴 균형 개선 효과가 더욱 증가될 수 있다. claims: 탈염 용암해수를 사용하여 재배한 병풀(Centella asiatica) 추출물 및 작약(Paeonia lactiflora) 추출물을 유효성분으로 포함하며, 피부 유해균총의 분포도를 감소시켜 피부 마이크로바이옴 균형을 유지하되, 상기 피부 유해균은 큐티박테리움 아크네스 속(Cutibacterium acnes group) 및 스타필로코커스 아우레우스 속(Staphylococcus aureus group)인 것을 특징으로 하는 여드름 개선용 화장료 조성물.탈염 용암해수를 사용하여 재배한 병풀(Centella asiatica) 추출물 및 작약(Paeonia lactiflora) 추출물을 유효성분으로 포함하며, 피부 유해균총의 분포도를 감소시켜 피부 마이크로바이옴 균형을 유지하되, 상기 피부 유해균은 큐티박테리움 아크네스 속(Cutibacterium acnes group) 및 스타필로코커스 아우레우스 속(Staphylococcus aureus group)인 것을 특징으로 하는 여드름 개선용 건강기능식품 조성물. 탈염 용암해수를 사용하여 재배한 병풀(Centella asiatica) 추출물 및 작약(Paeonia lactiflora) 추출물을 유효성분으로 포함하며, 피부 유해균총의 분포도를 감소시켜 피부 마이크로바이옴 균형을 유지하되, 상기 피부 유해균은 큐티박테리움 아크네스 속(Cutibacterium acnes group) 및 스타필로코커스 아우레우스 속(Staphylococcus aureus group)인 것을 특징으로 하는 여드름 개선용 반려용품 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

920/1150 Row 920: application_number: 1020210011922, combined_string: invention_title: 나노유기게르마늄 및 나노유기셀레늄을 이용한 기능성 작물의 재배방법 abstract: 본 발명은 나노유기게르마늄 및 나노유기셀레늄을 이용한 기능성 작물의 재배방법에 관한 것으로, 유기 게르마늄과 유기 셀레늄을 물리적인 에너지(열 또는 압력)를 부가하는 방법, 전기적인 폭발에너지를 부가하는 방법, 및 화학적 결합 공정 중에서 선택된 하나 또는 두 가지 이상을 수행하여 나노 크기로 제조한 나노 크기의 유기게르마늄과 나노 크기의 유기셀레늄을 작물의 성장 발육이 가장 왕성하게 되는 싯점과 결실을 이루기 위하여 성숙해 가는 시기에 적어도 2회 이상 관주 또는 엽면시비를 수행하는 것으로서, 제조된 나노 크기의 유기게르마늄과 나노 크기의 유기셀레늄은 나노 크기 상태에서 물을 용매로 수분산이 된 1액형의 물질인 것을 특징으로 한다. claims: 나노유기게르마늄 및 나노유기셀레늄을 이용한 기능성 작물의 재배방법에 있어서,유기 게르마늄과 유기 셀레늄을 물리적인 에너지(열 또는 압력)를 부가하는 방법, 전기적인 폭발에너지를 부가하는 방법, 및 화학적 결합 공정 중에서 선택된 하나 또는 두 가지 이상을 수행하여 나노 크기로 제조한 나노 크기의 유기게르마늄과 나노 크기의 유기셀레늄을 작물의 성장 발육이 가장 왕성하게 되는 싯점과 결실을 이루기 위하여 성숙해 가는 시기에 적어도 2회 이상 관주 또는 엽면시비를 수행하는 것으로서,제조된 나노 크기의 유기게르마늄과 나노 크기의 유기셀레늄은 나노 크기 상태에서 물을 용매로 수분산이 된 1액형의 물질인 것을 특징으로 하는 나노유기게르마늄 및 나노유기셀레늄을 이용한 기능성 작물의 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

921/1150 Row 921: application_number: 1020210006688, combined_string: invention_title: 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철에 존재하는 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템 abstract: 본 발명은 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 역사 같이 건축물 형태로 구성되어지는 하우징의 천장에 공기가 유동되도록 구성되는 2중 천장을 추가 구성하여 공기 유통하우징을 구성시킨 구조;상기 2중 천장에는 다수개의 공기 유통구를 구성시킨 구조;상기 공기 유통하우징의 일측에는 공기를 공급하여 주거나 뽑아주도록 작용하는 유입라인과 결합하여 중력의 작용에 의해 하우징의 상층부로 부상하는 오염된 공기를 포집하여 제거하여 주거나 포집시킨 공기를 정화하여 재 주입하도록 구성되는 친환경 다기능 공기 정화시스템에 관한 발명이다 claims: 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 역사 같이 건축물 형태로 구성되어 지는 하우징의 천장에 공기가 유통 되도록 구성되는 2중 천장을 추가 구성하여 공기 유통하우징을 구성시킨 구조;상기 2중 천장에는 다수개의 공기 유통구를 구성시킨 구조;상기 공기 유통하우징의 일측에는 공기를 공급하여 주거나 뽑아주도록 작용하는 유입라인과 결합하여 중력의 작용에 의해 하우징의 상층부로 부상하는 오염된 공기를 포집하여 제거하여 주거나 포집시킨 공기를 정화하여 재 주입하도록 구성되는 친환경 다기능 공기 정화시스템을 특징으로하는 건축물,병원,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 에 존재하는 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 역사 같이 건축물 형태로 구성되어지는 하우징의 상측에 비중이 가벼운 오염된 공기가 비중의 차이와 중력의 작용에 의해 일측 방향에서 타측 방향으로 흐르도록 유도하여 주는 2중 천장을 건축물의 천장 하단부에 경사진 형태로 추가로 구성시킨후 공기가 유통되도록 구성된 공기 유통구가 구성되어 있는 3중 천장을 상기 2중 천장의 하단부에 경사진 형태로 추가로 덧 대어 구성하여 비중이 가벼운 오염된 공기가 중력의 작용에 의해 외부로 자연배출 되도록 작용하는 배출구을 하우징의 일측에 결합 구성시킨 3중 천장의 구조를 이용하여 비중이 가벼운 오염된 공기를 하우징의 외부로 자연배출 시키도록 구성되는 자연친화적인 친환경 다기능 공기 정화시스템을 특징으로하는 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철에 존재하는 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철 역사 같이 건축물 형태로 구성되어 지는 하우징의 상측 코너에 비중이 가벼운 오염물질성 물질분자들을 수집하여 주는 수집구와 결합 되어진 수집라인을 건축물의 일측에 구성되는 공기 정화시스템과 결합 구성하여 중력의 작용에 의해 상기 하우징의 상측 방향으로 자동 부상하는 비중이 가벼운 유해물질성 물질분자들을 상기 수집구와 결합 되어진 수집라인과 상기 공기 정화시스템을 이용하여 상기 하우징의 상층부에 포진하고 있는 비중이 가벼운 오염된 공기를 수집하여 정화하는 친환경 다기능 공기 정화시스템을 특징으로 하는 건축물,병원,학교,군대의 막사,공장,동물을 사육하는 축사,식물을 재배하는 농장,사무실,지하주차장,지하철에 존재하는 비중이 가벼운 유해물질성 물질분자와 미세먼지제거 기능, 세균 및 바이러스 살균기능, 습도조절기능, 산소 및 음이온 발생 기능을 발휘하여 쾌적한 환경을 조성하여주는 자연친화적인 친환경 다기능 공기 정화시스템, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

922/1150 Row 922: application_number: 1020210005768, combined_string: invention_title: 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치 및 그 재배방법 abstract: 본 발명은 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치 및 그 재배방법에 관한 것으로, 보다 상세하게는 엽채 등과 같은 저온 식용식물을 안정적으로 온도관리하여 계속적으로 엽채를 수확할 수 있는 조건을 조성하므로 수확량을 2~5배 증산할 수 있는 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치 및 그 재배방법에 관한 것이다. 본 식용식물 재배장치는 식용식물의 추대방지를 위한 요구온도의 수분이 일정량 요구되는 높이의 수위에 위치하고 그 과잉분량을 회수하기 위한 유출구를 가지고 있으며, 식용식물이 생육하는 용토환경을 제공하는 재배용기와; 상기 재배용기의 요구되는 높이만큼 수용되고, 상기 식용식물의 추대방지를 위한 요구온도의 수분을 흡수하여 점진적으로 배출하는 수분흡수부재와; 상기 수분흡수부재 상에 수평적으로 균등하게 위치하며, 상기 수분을 수분흡수부재의 평판영역에 균등하게 공급하여 보습상태를 유지하여 근권부의 생장을 촉진시키고, 하측의 수분영역과 상측의 식물 식재영역의 생육용토를 분리시키는 부직포분리부재와; 상기 부직포분리부재의 상측에 상기 식용식물을 식재하여 생육환경을 제공하는 생육용토와; 상기 재배용기의 유출구로 과잉분량의 수분을 회수하여 하기 수분냉각교환기로 이송시키는 회수관과; 상기 회수관으로부터 회수되는 수분을 요구되는 온도이하로 열교환하여 상기 수조용기에 수용된 수분이 상기 식용식물의 추대방지를 위한 요구되는 온도를 유지하기 위한 수분냉각교환기와; 상기 수분냉각교환기로부터 열교환으로 냉각된 수분을 상기 점적관수부재로 순환시키는 수분순환관과; 상기 수분순환관의 냉각된 수분을 상기 재배용기 상측에서 점적으로 공급하고 상기 생육용토를 보습상태로 유지하여 생육용토가 근권부의 생육활성화로 추대방지를 위한 요구되는 온도를 유지하면서 식용식물에게 수분을 공급하기 위한 점적출구부재와; 상기 재배용기의 내측면과 외측면 중 어느 일측에 배치되어 있으며, 점적 공급된 수분의 열손실을 최소화하기 위한 재배단열부재를 포함한다. claims: 바닥면이 소정의 높이만큼 융기된 단차를 갖는 평판 융기부와, 상기 평판 융기부의 주위 원주영역에 재배용기의 원주 내경면에 의해 이격공간을 가지며, 식용식물을 식재하는 재배용기와;상기 재배용기의 이격공간에 상기 융기부의 높이만큼 수용되고, 상기 식용식물의 추대방지를 위한 요구온도의 수분을 흡수하여 점진적으로 배출하는 수분흡수부재와;상기 수분흡수부재와 융기부에 균등하게 위치하며, 상기 수분을 융기부와 수분흡수부재의 평판영역에 균등하게 공급하여 보습상태를 유지하여 근권부의 생장을 촉진시키고, 하측의 수분영역과 상측의 식물 식재영역의 생육용토를 분리시키는 부직포분리부재와;상기 부직포분리부재의 상측에 상기 식용식물을 식재하여 생육환경을 제공하는 생육용토와;상기 재배용기의 바닥영역이 잠기도록 배치되어 있으며, 상기 식용식물의 추대방지를 위한 요구온도의 수분 즉 물을 저장하고 있는 수조용기와;상기 수조용기의 수분이 일정량 요구되는 높이에 위치하고 그 수용된 수분의 과잉분량을 회수하는 회수관과;상기 회수관으로부터 회수되는 수분을 요구되는 온도이하로 열교환하여 상기 수조용기에 수용된 수분이 상기 식용식물의 추대방지를 위한 요구되는 온도를 유지하기 위한 수분냉각교환기와;상기 수분냉각교환기로부터 열교환으로 냉각된 수분을 하기 수분공급구로 순환시키는 수분순환관과;상기 수분순환관의 냉각된 수분을 상기 재배용기 상측에서 공급하고 상기 생육용토를 보습상태로 유지하여 생육용토가 근권부의 생육활성화로 추대방지를 위한 요구되는 온도를 유지하면서 식용식물에게 수분을 공급하기 위한 수분공급구와;상기 수조용기의 내측면과 외측면 중 어느 일측에 배치되어 있으며, 수용된 수분의 온도가 열손실없이 유지되도록 한 수조단열부재와;상기 재배용기의 내측면과 외측면 중 어느 일측에 배치되어 있으며, 점적 공급된 수분의 열손실을 최소화하기 위한 재배단열부재와;상기 수조용기와 재배용기 사이에 노출된 영역에서 열손실을 방지하는 노출단열부재를 포함하는 것을 특징으로 하는 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치.재배용기와 수분흡수부재, 수분흡수패드, 생육용토, 회수관, 수분냉각교환기, 수분순환관을 갖는 식용식물 재배장치를 활용한 수확량 유지 및 수확량 조절을 위한 식용식물 재배방법에 있어서;상기 식용식물 재배장치의 재배용기에 수용된 생육용토에 식재된 식용식물이 기후적으로 근권부 생리장애의 방지온도 20℃ 이하에서 그 20℃ 이하의 기후적 온도에 해당하는 수분을 공급하여 자연기후로 생육재배하는 자연적 생육재배단계와;상기 식용식물 재배장치의 재배용기에 수용된 생육용토에 식재된 식용식물에 근권부 생리장애 방지온도 20℃ 이상에서 발생하는 추대를 방지하기 위하여 상기 생육용토에 공급하는 수분의 요구온도를 상기 수분냉각교환기에 의해 15~20℃범위로 조절하고, 이에 따라 식용식물의 근권부 생리장애를 억제하여 추대방지상태의 생육을 유지하는 추대방지 생육재배단계와;상기 추대방지 생육재배단계가 연속적으로 진행되면서 상기 식용식물의 근권부 생리작용이 정상적으로 생육 활성화되고, 이에 따라 추대를 방지하는 생리적 생장이 정상적으로 이루어져 수확기간을 연장 및 증대하는 수확활성화단계와;상기 식용식물 재배장치의 재배용기에 수용된 생육용토에 식재된 식용식물이 기후적으로 자연재배기간에서 생산량이 극대화되어 생산과잉 상태로 판단되면, 상기 식용식물 근권부의 생육용토에 공급하는 수분의 휴면온도를 조성하여 생리적 생육이 정지되도록 그 휴면온도를 상기 수분냉각교환기에 의해 1~3℃범위로 조절하고, 이에 따라 관리자가 원하는 기간동안 휴면재배상태를 유지하는 휴면 생육재배단계를 포함하는 것을 특징으로 하는 수확량 유지 및 수확량 조절을 위한 식용식물 재배방법.식용식물의 추대방지를 위한 요구온도의 수분이 일정량 요구되는 높이의 수위에 위치하고 그 과잉분량을 회수하기 위한 유출구를 가지고 있으며, 식용식물이 생육하는 용토환경을 제공하는 재배용기와;상기 재배용기의 요구되는 높이만큼 수용되고, 상기 식용식물의 추대방지를 위한 요구온도의 수분을 흡수하여 점진적으로 배출하는 수분흡수부재와;상기 수분흡수부재 상에 수평적으로 균등하게 위치하며, 상기 수분을 수분흡수부재의 평판영역에 균등하게 공급하여 보습상태를 유지하여 근권부의 생장을 촉진시키고, 하측의 수분영역과 상측의 식물 식재영역의 생육용토를 분리시키는 부직포분리부재와;상기 부직포분리부재의 상측에 상기 식용식물을 식재하여 생육환경을 제공하는 생육용토와;상기 재배용기의 유출구로 과잉분량의 수분을 회수하여 하기 수분냉각교환기로 이송시키는 회수관과;상기 회수관으로부터 회수되는 수분을 요구되는 온도이하로 열교환하여 상기 재배용기에 수용된 수분이 상기 식용식물의 추대방지를 위한 요구되는 온도를 유지하기 위한 수분냉각교환기와;상기 수분냉각교환기로부터 열교환으로 냉각된 수분을 상기 생육용토에 수분공급구로 순환시키는 수분순환관과;상기 수분순환관의 냉각된 수분을 상기 재배용기 상측에서 점적으로 공급하고 상기 생육용토를 보습상태로 유지하여 생육용토가 근권부의 생육활성화로 추대방지를 위한 요구되는 온도를 유지하면서 식용식물에게 수분을 공급하기 위한 수분공급구와;상기 재배용기의 내측면과 외측면 중 어느 일측에 배치되어 있으며, 점적 공급된 수분의 열손실을 최소화하기 위한 재배단열부재를 포함하는 것을 특징으로 하는 수확량 유지 및 수확량 조절을 위한 식용식물 재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

923/1150 Row 923: application_number: 1020200172622, combined_string: invention_title: 라이조푸스 속 균주와 키토산, 사포닌 및 동물성 아미노산을 포함하여 항비만, 항암, 항당뇨 및 면역력 향상 효과를 갖는 농작물 재배가 가능한 액상 비료 조성물 및 이의 제조방법 abstract: 본 발명은 라이조푸스 속 균주 배양물, 키토산 분해 균주 배양물, 동물성 아미노산 발효물 및 사포닌액을 포함하는 액상 비료 조성물 및 이의 제조방법에 관한 것으로, 이를 이용하여 농작물을 재배하는 경우 농작물의 생육 효과 향상, 병충해 방제, 당도 향상, 농작물 내 조사포닌 함량 증진 효과를 제공할 뿐만 아니라 이를 이용하여 재배된 농작물 섭취 시 항비만, 항암, 항당뇨 및 면역력 향상 효과를 제공한다. claims: 라이조푸스 속(Rhizopus) 균주 배양물 0.01 중량부 내지 20 중량부;키토산 분해 균주를 이용하여 키토산을 분해한 분해물 0.01 중량부 내지 20 중량부;동물성 아미노산 발효물 0.01 중량부 내지 20 중량부; 및 사포닌액 0.01 중량부 내지 10 중량부;를 포함하고, 당, 솔빈산가리(potassium sorbate), 아황산나트륨(sodium sulfite), EDTA(ethylenediaminetetraacetic acid), 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산으로 이루어진 군으로부터 선택된 하나 이상을 포함하며, 상기 동물성 아미노산 발효물은 가축 혈액 80 내지 90 중량부, 브로멜라인 4 내지 6 중량부, 키모트립신 3 내지 4 중량부, 파파인 1 내지 3 중량부, 양파 껍질 분말 2.5 내지 3.5 중량부 및 버섯 분말 0.5 내지 1 중량부를 포함하는 액상 비료 조성물.키토산 분해 균주를 이용하여 키토산을 분해한 분해물을 제조하는 단계, 라이조푸스 균주 배양물을 제조하는 단계, 동물성 아미노산 발효물을 제조하는 단계 및 사포닌액을 준비하는 단계를 각각 순서에 무관하게 수행하는 원료를 준비하는 단계; 상기 키토산 분해 균주를 이용하여 키토산을 분해한 분해물, 상기 라이조푸스 균주 배양물, 상기 동물성 아미노산 발효물, 상기 사포닌액 및 당의 혼합물을 배양하여 배양액을 얻는 단계; 및 상기 배양액에 솔빈산가리, 아황산나트륨, EDTA, 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산으로 이루어진 군으로부터 선택된 하나 이상을 첨가하고 교반하는 단계;를 포함하고, 상기 동물성 아미노산 발효물을 제조하는 단계는, 도축 과정에서 얻어지는 가축 혈액 100 중량부에 대하여 3 내지 5 중량부의 1차 단백질분해효소를 첨가하고 1차 발효시켜 1차 발효물을 얻는 단계 및 상기 1차 발효물 100 중량부에 대하여 5 내지 10 중량부의 2차 단백질분해효소 및 3 내지 5 중량부의 첨가제를 첨가하고 2차 발효시켜 2차 발효물을 얻는 단계를 포함하며, 상기 1차 단백질분해효소는 브로멜라인 및 키모트립신을 1:3~5 중량비로 혼합하여 사용하고,상기 2차 단백질분해효소로 브로멜라인 및 파파인을 1:0.3~0.5 중량비로 혼합하여 사용하며, 상기 첨가제로 양파 껍질 분말 및 버섯 분말을 1:0.1~0.3 중량비로 혼합하여 사용하는, 액상 비료 조성물을 제조하는 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

924/1150 Row 924: application_number: 1020200146554, combined_string: invention_title: 인삼 재배방법 abstract: 본 발명은 인삼 재배방법에 관한 것으로, 보다 상세하게는 광 조사를 통해 인삼의 생육을 증대시킬 수 있는 인삼 재배방법에 관한 것이다.본 발명의 인삼 재배방법은, 싹을 틔운 묘삼을 준비하는 제 1단계; 상기 싹을 틔운 묘삼을 수경 재배시설로 정식하는 제 2단계; 및 상기 정식된 인삼을 성장시키는 제 3단계;를 포함하고, 상기 제 3단계의 인삼을 성장시키는 단계에서는, 상기 인삼에 광을 조사하는 단계 포함하는 것을 특징으로 한다. claims: 싹을 틔운 묘삼을 준비하는 제 1단계;상기 싹을 틔운 묘삼을 수경 재배시설로 정식하는 제 2단계; 및상기 정식된 인삼을 성장시키는 제 3단계;를 포함하되,상기 제 1단계에서 싹을 틔운 묘삼 준비 시,묘삼을 15 내지 20℃ 온도에서 뇌두 부분이 10 내지 80도의 경사로 위로 보게 배치하여 3 내지 5일간 싹을 1 내지 3cm 틔운 묘삼을 준비하고,상기 제 2단계에서 상기 수경 재배 시설의 내부에는 미세 비드를 포함하며,상기 미세 비드는 사이즈 100 내지 400㎛, 굴절율 1.9 내지 2.0인 것이며,상기 수경 재배 시설에서 사용되는 배양액은,온도 16 내지 20℃, pH 5.5 내지 6.5이고,상기 제 3단계의 인삼을 성장시키는 단계에서는,상기 인삼에 광을 조사하는 단계 포함하고,상기 광의 조사는 단계적으로 수행되며,원적외선광 30일, 적색광 및 청색광의 혼합광 30 내지 45일, 청색광 14일 순서로 조사되고,상기 적색광 및 청색광의 혼합광 구성 시 7:3의 비율로 조사되며,상기 인삼 성장 시 유묘기 및 생육기의 온도를 16 내지 20℃로 유지하고,상기 인삼 성장 시 메틸자스모네이트를 공급하는 것을 특징으로 하는 인삼 재배방법, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

925/1150 Row 925: application_number: 1020200137060, combined_string: invention_title: 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템 및 그 방법 abstract: 본 발명은 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템에 관한 것으로, 작물 재배 시설의 환경 구성과 실제 작물의 온도를 비교하여 온도 편차값을 연산한 후 온도 편차값에 따라 관수, 스크린, 보일러, 팬 등을 조절함으로써 작물을 재배하는 시설이 최적의 환경을 유지하도록 하는 것이다.본 발명에 의한 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템은 실제 작물을 재배하는 작물 재배 시설에서 실제 작물과 작물 재배 시설의 환경 구성에 대한 온도 데이터를 측정하는 촬영부와, 촬영부를 통해 측정된 온도 데이터를 화면에 출력하는 디스플레이와, 촬영부를 통해 측정된 온도 데이터를 디스플레이로 전송하는 전송 장치를 포함하는 구성을 가지며, 실제 작물과 작물 재배 시설의 환경 구성에 대한 온도 데이터를 비교하여 연산된 온도 편차값에 따라 작물 재배 시설의 환경 구성에 대한 제어를 하는 것을 특징으로 한다.이와 같은 본 발명에 의하면, 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템은 작물 재배 시설 내 실제 작물들의 생육 상태를 편리하게 파악할 수 있으며, 더불어 실제 작물들이 최적의 환경을 유지할 수 있도록 한다는 장점이 있다. claims: 실제 작물을 재배하는 작물 재배 시설에서 북쪽 방향을 바라보게 남쪽에 설치되어 상기 실제 작물과 상기 작물 재배 시설의 환경 구성에 대한 온도 데이터를 측정하는 촬영부와;상기 촬영부를 통해 측정된 상기 온도 데이터를 화면에 출력하는 디스플레이와;상기 촬영부를 통해 측정된 상기 온도 데이터를 상기 디스플레이로 전송하는 전송 장치를 포함하는 구성을 가지며;상기 작물 재배 시설의 토양, 관수, 난방 파이프, 팬, 스크린, 공기, 온실 구조물 또는 인조 작물을 포함하는 상기 작물 재배 시설의 환경 구성과 상기 실제 작물에 대한 상기 온도 데이터를 비교하여 연산된 온도 편차값에 따라 상기 작물 재배 시설의 환경 구성에 대한 제어를 하되,상기 인조 작물은, 상기 실제 작물과 동일한 방사율 수치를 가지며 방수가 가능한 재질로 이루어진 모형물과; 상기 모형물을 지지하는 지지대;를 포함하여 상기 실제 작물의 높이와 동일한 높이를 유지하고, 그 하단에 무게추가 더 구비되어 유동없이 고정되며,상기 촬영부는, 다수개의 픽셀 구조를 가지며 각각의 픽셀에 해당하는 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 온도를 측정하여 측정된 상기 온도 데이터를 다수개의 픽셀 구조에 추출하는 적외선 센서가 내부에 구비되며, 상기 적외선 센서로 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 상기 온도 데이터를 측정하는 카메라와; 상기 카메라를 지지하는 거치대와; 햇빛을 차단하는 차단판;을 포함하는 한편,상기 디스플레이는, 상기 촬영부를 통해 측정된 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 상기 온도 데이터가 소프트웨어를 통해 상기 화면에 출력되도록 이루어지고,상기 소프트웨어는, 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 온도를 측정하기 위한 범위를 다수개 설정하는 설정 프로그램과; 상기 설정 프로그램을 통해 설정한 온도 범위들 중 상기 온도를 비교하고자 하는 범위를 적어도 두 개 이상 선정 가능한 선정 프로그램과; 상기 선정 프로그램을 통해 선정된 범위에 해당하는 상기 온도 데이터를 실시간으로 추출하는 추출 프로그램과; 상기 추출 프로그램을 통해 추출된 상기 실제 작물의 현재 온도와 상기 작물 재배 시설의 상기 환경 구성의 현재 온도를 비교하여 상기 온도 편차값을 연산하는 연산 프로그램과; 추출 또는 연산된 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 상기 온도 데이터와 상기 온도 편차값을 데이터베이스에 누적하는 누적 프로그램과; 측정 및 연산된 상기 실제 작물과 상기 작물 재배 시설의 상기 환경 구성의 상기 온도 데이터와 상기 온도 편차값을 상기 화면에 출력하는 출력 프로그램을 포함하되,상기 설정 프로그램은, 온도 측정을 원하는 범위를 추가로 설정 및 지정할 수 있는 추가 프로그램과; 상기 온도 측정을 원하는 범위를 변경할 수 있는 편집 프로그램과; 지정한 범위를 삭제할 수 있는 삭제 프로그램과; 임의로 설정한 범위를 이전 상태로 복구할 수 있는 복구 프로그램을 포함하고,상기 선정 프로그램은, 상기 설정 프로그램에서 지정한 범위 중 상기 실제 작물에 해당하는 범위와 상기 작물 재배 시설의 상기 환경 구성에 해당하는 범위를 각각 선정하며,상기 추출 프로그램은, 상기 선정 프로그램을 통해 선정한 지정 범위의 현재 온도 데이터를 실시간으로 추출함과 동시에 전일, 당일 또는 한달 간 측정된 상기 온도 데이터의 최소값, 최대값 및 평균값을 포함하여 상기 디스플레이 상에 출력하고,상기 누적 프로그램은, 상기 온도 데이터와 상기 온도 편차값을 시간별, 날짜별로 상기 데이터베이스에 누적 및 저장하며,상기 출력 프로그램은, 상기 선정 프로그램을 통해 선정한 지정 범위의 현재 온도 데이터와 상기 연산 프로그램에 의해 연산된 온도 편차값을 일정 범위마다 다른 색상으로 표현하여 상기 실제 작물의 생육 상태를 파악할 수 있는 한편,상기 연산 프로그램에서 연산된 상기 인조 작물과 실제 작물의 온도 편차가 2℃ 미만일 경우 낮에는 실제 작물의 상태를 증산 부족, 밤에는 실제 작물의 상태를 정상으로 판단하여, 낮인 경우 창문을 개폐하거나 관수 작동을 중지시키고, 온도 편차가 2~4℃일 경우 실제 작물의 증산이 감소된 상태로 판단하여 작물이 위치한 방향으로 팬을 작동시키며,온도 편차가 4~8℃일 경우 실제 작물의 증산이 최적의 상태로 판단하며, 온도 편차가 8℃를 초과할 경우 실제 작물이 불안정하거나 높은 증산이 이루어지는 상태로 판단하여, 스크린으로 햇빛을 차단하거나 관수 작동 간격을 빈번하게 설정하는 것을 특징으로 하는 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템.제1항의 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 시스템을 이용한 상기 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 방법에 있어서,상기 작물 재배 시설 내에서 상기 촬영부가 북쪽 방향을 바라보게 남쪽에 설치하는 설치 단계와;소프트웨어의 설정 프로그램을 통해 온도 측정을 위한 범위를 설정하는 설정 단계와;상기 설정 단계에서 설정한 범위 중 온도를 비교하고자 하는 범위를 상기 소프트웨어의 선정 프로그램을 통해 적어도 두 개 이상 선정하는 선정 단계와;상기 선정 단계에서 선정한 범위들로부터 상기 실제 작물과 상기 작물 재배 시설의 환경 구성의 온도 데이터를 출력하는 출력 단계를 포함하되,상기 선정 단계는, 상기 작물 재배 시설의 환경 구성에 해당하는 범위와 그와 비교하고자 하는 상기 실제 작물에 해당하는 범위를 선정하고,상기 출력 단계는, 상기 소프트웨어의 추출 프로그램을 통해 추출된 상기 작물 재배 시설의 환경 구성의 상기 온도 데이터와 상기 실제 작물의 상기 온도 데이터를 출력하며, 상기 소프트웨어의 연산 프로그램을 통해 연산된 온도 편차값을 디스플레이에 출력함과 더불어,상기 연산 프로그램에서 연산된 상기 인조 작물과 실제 작물의 온도 편차가 2℃ 미만일 경우 낮에는 실제 작물의 상태를 증산 부족, 밤에는 실제 작물의 상태를 정상으로 판단하여, 낮인 경우 창문을 개폐하거나 관수 작동을 중지시키는 대응 방법을 제시하고,온도 편차가 2~4℃일 경우 실제 작물의 증산이 감소된 상태로 판단하여 작물이 위치한 방향으로 팬을 작동시키는 대응 방법을 제시하며,온도 편차가 4~8℃일 경우 실제 작물의 증산이 최적의 상태로 판단하며, 온도 편차가 8℃를 초과할 경우 실제 작물이 불안정하거나 높은 증산이 이루어지는 상태로 판단하여, 스크린으로 햇빛을 차단하거나 관수 작동 간격을 빈번하게 설정하는 대응 방법을 제시하는 것을 특징으로 하는 작물 재배 시설의 생육 모니터링 및 환경 자동 제어 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

926/1150 Row 926: application_number: 1020200130915, combined_string: invention_title: 감초 및 뿌리식물 재배용 컨테이너 abstract: 본 발명은 감초 및 뿌리식물 재배용 컨테이너에 관한 것으로, 보다 상세하게는 대량의 뿌리식물을 효과적으로 재배할 수 있도록 함은 물론 토양이 채워져 뿌리식물이 재배되는 공간부로 유입된 물이나 약액의 배출을 용이하게 이뤄 뿌리식물이 썩게 되는 것을 방지할 수 있도록 하는 감초 및 뿌리식물 재배용 컨테이너에 관한 것이다. 본 발명은 다수개의 격판이 격자상으로 배치되게 조립되어 각각의 격판 사이에 토양이 채워지는 공간부(130)가 형성된 격판부(100); 상기 격판부(100)를 감싸도록 형성되되 각각의 격판 상단이 끼워질 수 있도록 하는 조립끼움공(210)이 형성되고, 길이방향 측면 하부에 메인배수공(220)이 형성된 메인바디부(200); 상기 메인바디부(200)의 내부 하측에 길이방향을 따라 설치되되 다수개의 이너배수공(410)이 일정간격으로 형성되어 상기 공간부(130)로 유입된 물이나 약액이 상기 이너배수공(410)을 통해 내부로 유입된 후, 상기 메인배수공(220)을 통해 외부로 배출될 수 있도록 하는 배수가이드유닛(400);을 포함하여 구성되는 것을 특징으로 한다. claims: 다수개의 격판이 격자상으로 배치되게 조립되어 각각의 격판 사이에 토양이 채워지는 공간부(130)가 형성된 격판부(100); 상기 격판부(100)를 감싸도록 형성되되 각각의 격판 상단이 끼워질 수 있도록 하는 조립끼움공(210)이 형성되고, 길이방향 측면 하부에 메인배수공(220)이 형성된 메인바디부(200); 상기 메인바디부(200)의 내부 하측에 길이방향을 따라 설치되되 다수개의 이너배수공(410)이 일정간격으로 형성되어 상기 공간부(130)로 유입된 물이나 약액이 상기 이너배수공(410)을 통해 내부로 유입된 후, 상기 메인배수공(220)을 통해 외부로 배출될 수 있도록 하는 배수가이드유닛(400);을 포함하여 구성되고, 상기 격판부(100)의 상측에는 물이나 약액이 유동하는 유동배관유닛(300)이 안착되게 설치되어 상기 유동배관유닛(300)에서 배출되는 물이나 약액이 상기 공간부(130)로 유입될 수 있도록 이루어지며, 상기 유동배관유닛(300)은 물이나 약액이 수용되는 안착바디(310)와, 상기 안착바디(310)의 폭방향 양측으로 연장된 상태로 상기 공간부(130)로 물이나 약액이 배출될 수 있도록 가이드하는 배출가이드구(320)를 포함하여 구성되고, 상기 배출가이드구(320)에는 물이나 약액이 상기 공간부(130)의 상측방향으로 배출될 수 있도록 하는 상방분출공(321)과 물이나 약액이 상기 공간부(130)의 하측방향으로 유동할 수 있도록 하는 하방분출튜브(322)가 마련된 것을 특징으로 하는 감초 및 뿌리식물 재배용 컨테이너., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

927/1150 Row 927: application_number: 1020200124869, combined_string: invention_title: 작물 상태 판단 장치 및 이를 포함하는 작물 재배 정보 서비스 플랫폼 abstract: 본 실시예들은 프로세서 및 프로세서에 의해 실행되는 프로그램을 저장하는 메모리를 포함하는 작물 재배 정보 서비스 플랫폼에 있어서, 프로세서는, 기 설정된 지형 정보와 이륙 지점 및 착륙 지점을 고려하여 형성된 필지에 따른 무인 비행체의 비행 경로를 생성하고, 무인 비행체가 획득한 작물 영상을 전달받아 분석하여 비행 경로에 따른 작물 정보를 획득하며, 작물의 종류 및 작물의 상태를 포함하는 작물 정보를 고려하여 비행 경로에 따른 재배 면적 별 수확 현황 및 재해 현황이 표시되는 작물 지도를 생성하는 것을 특징으로 하는 작물 재배 정보 서비스 플랫폼을 제안한다. claims: 프로세서 및 상기 프로세서에 의해 실행되는 프로그램을 저장하는 메모리를 포함하는 작물 재배 정보 서비스 플랫폼에 있어서,상기 프로세서는,기 설정된 지형 정보와 이륙 지점 및 착륙 지점을 고려하여 형성된 필지에 따른 무인 비행체의 비행 경로를 생성하고,상기 무인 비행체가 획득한 작물 영상을 전달받아 분석하여 상기 비행 경로에 따른 작물 정보를 획득하며,작물의 종류 및 작물의 상태를 포함하는 상기 작물 정보를 고려하여 상기 비행 경로에 따른 재배 면적 별 수확 현황 및 재해 현황이 표시되는 작물 지도를 생성하고,상기 프로세서는, 상기 작물의 종류에 따른 복수의 분류 모델 및 상기 작물의 상태에 따른 복수의 상태 모델을 학습하여 상기 작물 영상을 합성곱 신경망(CNN, Convolutional Neural Network)을 통해 분석하여 작물 별로 분류하여 작물의 종류 및 작물의 상태를 포함하는 상기 작물 정보를 획득하며,상기 프로세서는, 1차적으로 기 설정된 작물에 속하는 제1 작물 영역을 학습하는 제1 분류 모델 및 기 설정된 작물에 속하지 않는 제2 작물 영역을 학습하는 제2 분류 모델을 포함하는 상기 학습된 복수의 분류 모델을 적용하여 상기 작물 영상의 시간값을 입력으로 하여 추출된 특징을 분석하여 작물의 종류를 판단하고, 2차적으로 상기 판단된 작물의 종류에 따라 상기 시간값을 입력으로 하여 상기 학습된 복수의 상태 모델을 적용하여 정상, 결핍 및 고온 피해를 포함하는 상기 작물의 상태를 판단하고, 상기 비행 경로를 기반으로 재배 면적 별로 상기 작물의 종류에 따른 상기 작물의 상태를 표시하여 상기 작물 지도를 생성하는 것을 특징으로 하는 작물 재배 정보 서비스 플랫폼.프로세서 및 상기 프로세서에 의해 실행되는 프로그램을 저장하는 메모리를 포함하는 작물 상태 판단 장치에 있어서,상기 프로세서는,작물의 종류에 따른 복수의 분류 모델 및 상기 작물의 상태에 따른 복수의 상태 모델을 학습하고,비행 경로를 따라 이동하는 무인 비행체가 획득한 작물 영상을 전달받아 합성곱 신경망(CNN, Convolutional Neural Network)을 통해 분석하여 작물 별로 분류하여 작물의 종류 및 작물의 상태를 포함하는 작물 정보를 획득하며,상기 프로세서는, 1차적으로 기 설정된 작물에 속하는 제1 작물 영역을 학습하는 제1 분류 모델 및 기 설정된 작물에 속하지 않는 제2 작물 영역을 학습하는 제2 분류 모델을 포함하는 상기 학습된 복수의 분류 모델을 적용하여 상기 작물 영상의 시간값을 입력으로 하여 추출된 특징을 분석하여 작물의 종류를 판단하고, 2차적으로 상기 판단된 작물의 종류에 따라 상기 시간값을 입력으로 하여 상기 학습된 복수의 상태 모델을 적용하여 정상, 결핍, 고온 피해, 병을 포함하는 상기 작물의 상태를 판단하는 것을 특징으로 하는 작물 상태 판단 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

928/1150 Row 928: application_number: 1020200107029, combined_string: invention_title: 이동식 작물 재배 장치 abstract: 본 발명은 이동식 작물 재배 장치에 관한 것이다.보다 구체적으로는, 수분 공급을 통해 생육되는 식물을 재배할 수 있는 하우스 구조의 이동식 작물 재배 장치에 관한 것이다. claims: 이동식 작물 재배 장치는 하우스 구조로서,지붕을 제외한 외관의 뼈대을 형성하는 외관 프레임과; 상기 외관 프레임의 상측에서 지붕의 뼈대를 형성하는 지붕 프레임과; 상기 외관 프레임의 내측으로 마주하는 벽면에 대하여, 마주하는 방향으로 결합된 2개가 1쌍으로, 적어도 1쌍 이상 상, 하 방향으로 형성된 받침 프레임;을 포함하여 구성되고,상기 이동식 작물 재배 장치의 지붕 내면에는 지붕 가이드레일을 더 포함하고, 상기 지붕 가이드레일을 타고 이동하는 이송수단을 더 포함하되,상기 지붕 가이드레일은 ''의 단면형상을 가지고,상기 이송수단은,상기 지붕 가이드레일의 내측에 상기 지붕 가이드레일의 길이방향을 따라 형성된 제1 몸체와;상기 지붕 가이드레일의 개방된 영역에서부터 외측으로 노출되는 높이를 가지고 상기 지붕 가이드레일의 길이방향을 따라 형성되어 상기 제1 몸체 하측에 위치된 제2 몸체와;상기 제2 몸체를 관통하고 제1 몸체에 내삽된 볼트기둥과;상기 볼트기둥의 노출된 단부에 구성되어 볼트기둥을 회전시키도록 조작되는 회전헤드와;상기 볼트기둥의 외면에 결합되어 회전헤드에 의해 이탈이 방지되는 스프링과;상기 제1 몸체에 축으로 결합되고, 전단에 2개 및 후단에 2개로 구성되어 상기 지붕 가이드레일의 개방된 영역에 길이방향으로 형성된 단턱의 상면에 안착되는 상측 휠과;상기 제2 몸체에 축으로 결합되고, 전단에 2개 및 후단에 2개로 구성되어 상기 지붕 가이드레일의 개방된 영역에 길이방향으로 형성된 단턱의 하면에 맞닿는 하측 휠과;어느 일방향의 전단 및 후단에 형성된 하측 휠 각각에 축으로 연결되어 각각 구비된 기어와;상기 전단 및 후단 각각의 기어를 결합하는 체인과;상기 제2 몸체에서부터 연장되어 다수 절곡되되, 다른 일방향의 전단에 형성된 하측 휠의 외측으로 구성된 지지체와;상기 지지체를 관통하며, 상기 지지체 내측에 위치된 하측 휠에 결합된 축으로 연결되어 회전력을 전달하는 모터와;상기 제2 몸체의 일측에 1개의 볼트를 통해 결합된 2개가 1쌍으로 된 연결판;을 포함하여 구성되는 것을 특징으로 하는, 이동식 작물 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

929/1150 Row 929: application_number: 1020200105327, combined_string: invention_title: 저고도 무인 비행체 및 이를 포함하는 작물 재배 정보 획득 시스템 abstract: 본 실시예들은 기 설정된 지형 정보와 이륙 지점 및 착륙 지점을 고려하여 형성된 필지에 따른 비행 경로를 생성하는 관제 센터 및 비행 경로에 따라 저고도 비행을 수행하며 환경 정보 또는 저고도 작물 영상을 획득하는 저고도 무인 비행체를 포함하고, 관제 센터는 저고도 작물 영상을 분석하여 작물 정보를 획득하고, 작물 정보를 좌표에 따라 표시하여 작물 지도를 생성하는 것을 특징으로 하는 작물 재배 정보 획득 시스템을 제안한다. claims: 기 설정된 지형 정보와 이륙 지점 및 착륙 지점을 고려하여 형성된 필지에 따른 비행 경로를 생성하는 관제 센터; 및상기 비행 경로에 따라 저고도 비행을 수행하며 환경 정보 또는 저고도 작물 영상을 획득하는 저고도 무인 비행체를 포함하고,상기 관제 센터는 상기 저고도 작물 영상을 분석하여 작물 정보를 획득하고, 상기 작물 정보를 좌표에 따라 표시하여 작물 지도를 생성하고,상기 저고도 무인 비행체는,상기 저고도 무인 비행체의 비행을 가능하게 하는 구동력을 발생시키는 구동부;상기 비행 경로를 따라 이동하며 상기 저고도 작물 영상을 획득하는 영상 획득부; 및상기 구동부 및 상기 영상 획득부를 제어하고, 상기 환경 정보와 상기 획득된 저고도 작물 영상을 고려하여 상기 비행 경로를 재설정하는 프로세서를 포함하고,상기 프로세서는,직하방을 향하도록 설정된 상기 영상 획득부에서 획득된 제1 저고도 작물 영상을 분석하여 1차 작물 인식을 수행하고,상기 1차 작물 인식을 통해 작물 정보를 획득하지 못한 경우, 상기 직하방을 향하도록 설정된 영상 획득부의 각도를 기 설정된 각도로 조절하여 획득된 제2 저고도 작물 영상을 전달받아 분석하여 2차 작물 인식을 수행하고,상기 2차 작물 인식을 통해 작물 정보를 획득하지 못한 경우, 상기 제1 저고도 작물 영상 및 상기 제2 저고도 작물 영상을 적대적 생성 신경망(GAN)을 통해 합성하여 합성 영상을 생성하고, 상기 생성된 합성 영상을 분석하여 3차 작물 인식을 수행하는 것을 특징으로 하는 작물 재배 정보 획득 시스템.기 설정된 지형 정보를 고려하여 생성된 비행 경로를 따라 비행을 가능하게 하는 구동력을 발생시키는 구동부;주변의 환경 정보를 획득하는 센서부;상기 비행 경로에 따라 저고도 비행을 수행하며 저고도 작물 영상을 획득하는 영상 획득부;상기 저고도 작물 영상을 분석하여 작물 정보를 획득하고, 상기 작물 정보를 좌표에 따라 표시하여 작물 지도를 생성하는 프로세서; 및상기 획득된 저고도 영상 또는 상기 프로세서에서의 연산 결과를 외부의 통신 가능한 장치로 전달하기 위한 통신부를 포함하고,상기 프로세서는,직하방을 향하도록 설정된 상기 영상 획득부에서 획득된 제1 저고도 작물 영상을 분석하여 1차 작물 인식을 수행하고,상기 1차 작물 인식을 통해 작물 정보를 획득하지 못한 경우, 상기 직하방을 향하도록 설정된 영상 획득부의 각도를 기 설정된 각도로 조절하여 획득된 제2 저고도 작물 영상을 전달받아 분석하여 2차 작물 인식을 수행하고,상기 2차 작물 인식을 통해 작물 정보를 획득하지 못한 경우, 상기 제1 저고도 작물 영상 및 상기 제2 저고도 작물 영상을 적대적 생성 신경망(GAN)을 통해 합성하여 합성 영상을 생성하고, 상기 생성된 합성 영상을 분석하여 3차 작물 인식을 수행하는 것을 특징으로 하는 저고도 무인 비행체., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

930/1150 Row 930: application_number: 1020200088428, combined_string: invention_title: 작물 재배용 베드 어셈블리 abstract: 본 발명은 지면에 베드(10)를 직접 설치할 수 있음과 더불어 시설하우스 내에 비교적 좁은 간격을 유지하는 일측파이프(51) 및 타측파이프(52) 나아가 비교적 넓은 간격을 유지하는 일측지지봉(31) 및 타측지지봉(32) 등으로 베드(10)의 위치 및 작업높이를 자유롭게(호환성 있게) 설치할 수 있도록 하여 시설하우스 현장에서의 조립성과 더불어 작업성까지 보장토록 할 수 있는 작물 재배용 베드 어셈블리에 관한 발명이다. claims: 배수구멍이 뚫린 바닥부를 기준으로 가장자리를 따라 상승된 일측벽 및 타측벽 그리고 전측벽 및 후측벽에 의해 상토를 수용하는 채움공간을 마련하는 베드를 포함하는 작물 재배용 베드 어셈블리에 있어서,상기 바닥부는 상기 일측벽 및 타측벽 사이에서 원호형상의 구배부를 지니고,상기 베드는 상기 구배부를 따라 외향 이격 돌출되면서 중간중간에 일측환기터널 및 타측환기터널을 각각 마련하는 일측돌출부 및 타측돌출부를 더 포함하고,상기 베드는 상기 일측벽 및 타측벽의 상단으로부터 외향으로 연장되어 일측지지봉 및 타측지지봉을 각각 받아들이는 일측날개 및 타측날개를 구비하고,상기 일측지지봉 및 타측지지봉에 각각 감겨져 상기 일측벽 및 일측돌출부 그리고 타측벽 및 타측돌출부를 따라 하향되면서 상기 바닥부로부터 이격되는 하부환기터널을 마련하는 방수커버를 더 포함하는 것을 특징으로 하는 작물 재배용 베드 어셈블리., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

931/1150 Row 931: application_number: 1020200078618, combined_string: invention_title: 휴믹물질을 포함하는 인삼의 수경재배용 양액 조성물 및 상기 양액 조성물을 이용한 인삼의 수경재배 방법 abstract: 본 발명은 휴믹물질을 포함하는 인삼의 수경재배용 양액 조성물 및 상기 양액 조성물을 이용한 인삼의 수경재배 방법에 관한 것이다. 구체적으로, 본 발명에 따른 휴믹물질을 이용하여 수경재배된 인삼은 이에 포함된 잔류농약 및 중금속의 함량이 현저히 감소하면서, 유용한 생리활성 성분인 사포닌 및 미네랄의 함량을 유의적으로 증가시킴으로써, 인삼의 수경재배에 유용하게 사용될 수 있다. claims: 휴믹산(humic acid) 및 풀빅산(fulvic acid)을 포함하는 인삼의 수경재배용 양액 조성물로서,상기 양액 조성물은 인삼 내 사포닌 함량을 증가시키는 양액 조성물.제1항의 양액 조성물을 이용하여 인삼을 수경재배하는 단계를 포함하는 인삼의 수경재배 방법.제9항의 수경재배 방법으로 재배된 인삼.제11항의 인삼을 포함하는 조성물.제1항의 양액 조성물을 이용하여 인삼을 수경재배하는 단계를 포함하는 인삼 내에서 잔류농약 및 중금속으로 구성된 군으로부터 선택되는 어느 하나 이상을 감소시키는 방법.제1항의 양액 조성물을 이용하여 인삼을 수경재배하는 단계를 포함하는 인삼 내에서 사포닌 및 미네랄로 구성된 군으로부터 선택되는 어느 하나 이상을 증가시키는 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

932/1150 Row 932: application_number: 1020200053266, combined_string: invention_title: 작물 재배 또는 육묘용 포트 어셈블리 abstract: 본 발명은 포트플레이트(60)의 포트(61)들 사이의 길이방향으로 뚫려져 연속하여 이어지는 어퍼홈라인(62)에 선형조립수단(70)을 끼워 포트플레이트(60)들을 연속하여 누르면서 일체화시킬 수 있도록 함으로써 바람에 의한 영향이나 작업자의 부딪힘에 의한 영향을 최소화시켜 포트플레이트(60)들을 견고하게 안정될 수 있도록 함과 동시에 작물 재배 완료 후 또는 작물 육묘 완료 후 포트플레이트(60)들을 적층시켜 보관하고자 밧줄로 묶고자 할 때 어퍼홈라인(62)을 경유시킬 수 있도록 함으로써 보관시 묶음처리 상태 역시 더욱 견고하게 실현케 할 수 있고, 특히, 선형조립수단(70)이 어퍼홈라인(62)에 끼워진 상태로 포트플레이트(60)들을 누를 수 있도록 하여 어퍼홈라인(62)으로부터 선형조립수단(70)의 분리현상을 극소화시켜 선형조립수단(70)의 무단이탈에 의한 작물로의 악영향(상처나 훼손)을 철저히 방지하고, 나아가 선형조립수단(70) 및 받침파이프(F1) 상호간의 양끝단의 직접적인 묶음처리로서 프레임(F)에서부터 포트플레이트(60)들에 이르기까지 일체화된 상태를 보장하여 보다 안정감 있게 작물을 재배 및 육묘할 수 있는 특유의 작용을 발휘하는 작물 재배 또는 육묘용 포트 어셈블리에 관한 발명이다. claims: 배수구멍(61a)이 뚫린 포트(61)들을 지니면서 직선상으로 연속하여 이웃하는 포트플레이트(60)들을 포함하는 작물 재배 또는 육묘용 포트 어셈블리에 있어서,상기 포트플레이트(60)들은 상기 포트(61)들 사이의 길이방향으로 뚫려져 연속하여 이어지는 어퍼홈라인(62)을 각각 구비하고,상기 어퍼홈라인(62)들을 따라 끼워져 상기 포트플레이트(60)들을 연속하여 누르면서 일체화시키는 선형조립수단(70)을 포함하고,상기 선형조립수단(70)은 누름파이프(71) 또는 로프(72)인 것을 특징으로 하는 작물 재배 또는 육묘용 포트 어셈블리., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

933/1150 Row 933: application_number: 1020200047518, combined_string: invention_title: 기능성 작물 재배장치 abstract: 본 발명은 기능성 작물 재배장치에 관한 것으로, 보다 상세하게는, 식물 재배 시 자극을 통해 생리활성 물질을 다량 포함할 수 있도록 하는 기능성 작물 재배장치에 관한 것이다. 본 발명에 따른 기능성 작물 재배장치는 센서를 이용하여 재배 환경을 센싱하는 재배환경부; 작물에 따라 기설정된 조건의 자극을 부여하고 조절하는 자극조절부; 상기 자극에 의해 변화된 재배 상태를 검사하고 그에 따른 데이터를 저장하는 상태관리부; 소비자 또는 공급자에게 현재 상태를 전달하기 위한 모니터링 수단을 구비하는 공급확인부; 상기 재배환경부, 자극조절부, 상태관리부 및 공급확인부에 필요한 전원을 부여하기 위한 전원부;를 포함하는 것을 특징으로 한다. claims: 센서를 이용하여 재배 환경을 센싱하는 재배환경부;작물에 따라 기설정된 조건의 자극을 부여하고 조절하는 자극조절부;상기 자극에 의해 변화된 재배 상태를 검사하고 그에 따른 데이터를 저장하는 상태관리부;소비자 또는 공급자에게 현재 상태를 전달하기 위한 모니터링 수단을 구비하는 공급확인부;상기 재배환경부, 자극조절부, 상태관리부 및 공급확인부에 필요한 전원을 부여하기 위한 전원부;를 포함하는 것을 특징으로 하는 기능성 작물 재배장치, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

934/1150 Row 934: application_number: 1020200046371, combined_string: invention_title: 지능형 특수작물 재배기 abstract: 본 발명은, 작물이 수용되는 챔버부; 및 상기 챔버부의 상측에 설치되며, 상기 챔버부에 존재하는 공기를 흡입하여 상측으로 토출시켜, 상기 챔버부로 공기를 순환시키는 휀부;를 포함하는 지능형 특수작물 재배기를 제공한다.본 발명에 따른 지능형 특수작물 재배기에 의하면, 지구상의 모든 천연 자연물의 인공 재배환경을 구현함으로써, 특수한 자연조건에서 자라는 희귀 천연물자원의 보존과 인공재배법을 위하여 농업기술개발에 적극 활용하고 병충해 및 연작피해와 자연재해 등을 회피하며, 대량생산과 청정재배를 실현할 수 있는 농업기술개발에 활용 될 수 있다. 또한, 이러한 본 발명에 의하면, 스마트팜의 특성인 5G, IOT, DB 등과 연동하여 특수작물 재배기 모듈에 다각도로 활용 될 수 있다. claims: 작물이 수용되는 챔버부; 및상기 챔버부의 상측에 설치되며, 상기 챔버부에 존재하는 공기를 흡입하여 상측으로 토출시켜, 상기 챔버부로 공기를 순환시키는 휀부;를 포함하는 지능형 특수작물 재배기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

935/1150 Row 935: application_number: 1020200046226, combined_string: invention_title: 인삼의 생장 촉진 및 내병성 증진용 조성물 및 이를 이용한 인삼의 재배방법 abstract: 본 발명은 인삼의 생장 촉진 및 내병성 증진용 조성물 및 이를 이용한 인삼의 재배방법에 관한 것이다. 본 발명에 따른 인삼의 생장 촉진 및 내병성 증진용 조성물은 유충(幼蟲) 파우더를 포함하는 것일 수 있다. claims: 갈색거저리(mealworm beetle) 유충 파우더 및 귀뚜라미 성충 파우더를 포함하는인삼의 생장 촉진 및 내병성 증진용 조성물.갈색거저리(mealworm beetle) 유충 파우더, 귀뚜라미 성충 파우더 및 물의 혼합물을 제조하는 단계 및 생육되는 인삼에 상기 혼합물을 분사하는 단계를 포함하는 것인인삼의 생장 촉진 및 내병성 증진용 조성물을 이용한 인삼의 재배방법.제 5항에 따른 재배방법으로 생육된 인삼., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

936/1150 Row 936: application_number: 1020200046229, combined_string: invention_title: 인삼의 생장 촉진 및 내병성 증진용 조성물 및 이를 이용한 인삼의 재배방법 abstract: 본 발명은 인삼의 생장 촉진 및 내병성 증진용 조성물 및 이를 이용한 인삼의 재배방법에 관한 것이다. 본 발명에 따른 인삼의 생장 촉진 및 내병성 증진용 조성물은 곤충 파우더를 포함하고 상기 곤충은 성충인 것일 수 있다. claims: 귀뚜라미 성충 파우더 100 중량부, 갈색거저리 유충 파우더 50 내지 200 중량부를 포함하는인삼의 생장 촉진 및 내병성 증진용 조성물.귀뚜라미 성충 파우더 100 중량부, 갈색거저리 유충 파우더 50 내지 200 중량부를 혼합하는 단계;상기 혼합한 파우더를 10배수의 물에 혼합 및 분산하여 혼합물을 제조하는 단계; 및생육되는 인삼의 뿌리 부분에 상기 혼합물을 분사하는 단계를 포함하는, 인삼의 재배방법.제 5항에 따른 재배방법으로 생육된 인삼., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

937/1150 Row 937: application_number: 1020200040821, combined_string: invention_title: 냉난방 시스템에 의한 에너지 절감형 하우스 작물 재배장치 및 그 하우스 작물 재배방법 abstract: 본 발명은 냉난방 시스템에 의한 에너지 절감형 하우스 작물 재배장치 및 그 하우스 작물 재배방법에 관한 것으로 계절에 상관 없이 각종 작물을 재배하는 하우스 내에 작물 재배에 필요한 적정온도와 영양액 공급을 포함한 실내환경을 제공하도록 함과 아울러, 에너지 절감효과를 가지는 지하물탱크를 사용하여 냉온수를 생성공급하여 하우스 내부의 온도를 조절토록 하고, 냉온수 공급 시 용존산소를 부여토록 하며, 지하물탱크를 사용함으로써 에너지 절감효과를 갖도록 하기 위하여, 작물(3) 재배를 위해 설치되는 하우스(2)의 인근 지하에 매설되는 지하물탱크(10); 상기 지하물탱크(10)의 내부에 충진된 사용수를 외부로 이송시키도록 수중가압펌프(12)가 구비되고, 상기 지하물탱크(10)의 상부에 위치되고, 상기 수중가압펌프(12)에 연결된 이동관(14)에 연결되어 이동되는 사용수의 온도를 조절하도록 쿨냉각기와 히트온수기가 구비되는 수온조절부(20); 상기 수온조절부(20)를 통해 요구하는 온도로 조절된 사용수가 저장되도록 지상에 설치되는 지상물탱크(30); 상기 지상물탱크(30)에 연결되는 제1공급관(31)은 하우스(2) 내에서 하우스(2)의 길이방향을 따라 구비되고, 상기 제1공급관(31) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내에 온도 조절된 사용수를 분사토록 하고, 상기 하우스(2)에서 재배되는 작물(3)에 영양분을 공급하도록 지상물탱크(30) 인근 지상에 설치되는 영양액공급탱크(40); 상기 영양액공급탱크(40)에 연결되는 제2공급관(42)은 하우스(2) 내의 제1공급관(31)과 평행하게 구비되고, 상기 영양액공급탱크(40)에 연결되는 제3공급관(43)은 하우스(2) 내의 상부에 제2공급관(42)과 평행하게 구비되며, 상기 제2공급관(42) 및 제3공급관(43) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내의 작물(3)에 영양액을 분사토록 하며, 상기 하우스(2) 내의 지면에서 이격 구비되어 하우스(2)의 길이방향으로 구비되는 다수의 고설베드(50); 상기 고설베드(50)는 작물(3) 재배를 위한 수용홈부(52)가 구비되고, 상기 수용홈부(52) 내에 상기 제1공급관(31)에 연결된 냉온수파이프(60)이 구비되어 작물(3)에 필요한 냉온기를 전달하도록 구성되는 것을 포함하여 이루어짐을 특징으로 한다. claims: 작물(3) 재배를 위해 설치되는 하우스(2)의 인근 지하에 매설되는 지하물탱크(10); 상기 지하물탱크(10)의 내부에 충진된 사용수를 외부로 이송시키도록 수중가압펌프(12)가 구비되고,상기 지하물탱크(10)의 상부에 위치되고, 상기 수중가압펌프(12)에 연결된 이동관(14)에 연결되어 이동되는 사용수의 온도를 조절하도록 쿨냉각기와 히트온수기가 구비되는 수온조절부(20);상기 수온조절부(20)를 통해 요구하는 온도로 조절된 사용수가 저장되도록 지상에 설치되는 지상물탱크(30); 상기 지상물탱크(30)에 연결되는 제1공급관(31)은 하우스(2) 내에서 하우스(2)의 길이방향을 따라 구비되고, 상기 제1공급관(31) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내에 온도 조절된 사용수를 분사토록 하고,상기 하우스(2)에서 재배되는 작물(3)에 영양분을 공급하도록 지상물탱크(30) 인근 지상에 설치되는 영양액공급탱크(40); 상기 영양액공급탱크(40)에 연결되는 제2공급관(42)은 하우스(2) 내의 제1공급관(31)과 평행하게 구비되고, 상기 영양액공급탱크(40)에 연결되는 제3공급관(43)은 하우스(2) 내의 상부에 제2공급관(42)과 평행하게 구비되며, 상기 제2공급관(42) 및 제3공급관(43) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내의 작물(3)에 영양액을 분사토록 하며, 상기 하우스(2) 내의 지면에서 이격 구비되어 하우스(2)의 길이방향으로 구비되는 다수의 고설베드(50); 상기 고설베드(50)는 작물(3) 재배를 위한 수용홈부(52)가 구비되고, 상기 수용홈부(52) 내에 상기 제1공급관(31)에 연결된 냉온수파이프(60)이 구비되어 작물(3)에 필요한 냉온기를 전달하도록 구성되는 것을 포함하여 이루어짐을 특징으로 하는 냉난방 시스템에 의한 에너지 절감형 하우스 고설베드 작물 재배장치.작물(3) 재배를 위해 설치되는 하우스(2)의 인근 지하에 매설되는 지하물탱크(10)를 마련하고, 상기 지하물탱크(10)의 내부에 충진된 사용수를 외부로 이송시키도록 수중가압펌프(12)를 마련하며, 상기 지하물탱크(10)의 상부에 위치되고, 상기 수중가압펌프(12)에 연결된 이동관(14)에 연결되어 이동되는 사용수의 온도를 조절하도록 쿨냉각기와 히트온수기가 구비되는 수온조절부(20)를 마련하되 상기 이동관(14) 상에 용존산소 발생기(16)를 구비하여 이동관(14)을 통해 수중가압펌프(12)에서 수온조절부(20)로 이동하는 사용수의 용존산소량을 증가시키도록 하고, 상기 수온조절부(20)를 통해 요구하는 온도로 조절된 사용수가 저장되도록 지상에 설치되는 지상물탱크(30)를 마련하되 상기 지상물탱크(30)에 연결되는 제1공급관(31)은 하우스(2) 내에서 하우스(2)의 길이방향을 따라 구비되고, 상기 제1공급관(31) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내에 온도 조절된 사용수를 분사토록 하고, 상기 하우스(2)에서 재배되는 작물(3)에 영양분을 공급하도록 지상물탱크(30) 인근 지상에 설치되는 영양액공급탱크(40)를 마련하되 상기 영양액공급탱크(40)에 연결되는 제2공급관(42)은 하우스(2) 내의 제1공급관(31)과 평행하게 구비되고, 상기 영양액공급탱크(40)에 연결되는 제3공급관(43)은 하우스(2) 내의 상부에 제2공급관(42)과 평행하게 구비되며, 상기 제2공급관(42) 및 제3공급관(43) 상에 다수의 노즐이 일정간격 구비되어 하우스(2) 내의 작물(3)에 영양액을 분사토록 하며, 상기 하우스(2) 내의 지면에서 이격 구비되어 하우스(2)의 길이방향으로 구비되는 다수의 고설베드(50)를 마련하되 상기 고설베드(50)는 작물(3) 재배를 위한 수용홈부(52)가 구비되고, 상기 수용홈부(52) 내에 상기 제1공급관(31)에 연결된 냉온수파이프(60)이 구비되어 작물(3)에 필요한 냉온기를 전달하도록 하여, 계절에 상관 없이 하우스(2) 내에 작물(3) 재배에 필요한 적정온도와 영양액을 에너지 절감 가능한 구조로 제공하도록 하여 이루어짐을 특징으로 하는 냉난방 시스템에 의한 에너지 절감형 하우스 작물 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

938/1150 Row 938: application_number: 1020200039235, combined_string: invention_title: 포그 스프레이 시스템을 구비한 수직형 작물 재배 장치 및 방법 abstract: 본 발명은 포그 스프레이 시스템을 구비한 수직형 작물 재배 장치 및 방법에 관한 것으로서, 보다 상세하게는 작물의 발육 상태에 따라 이온화된 드라이 포그와 미스트 포그로 영양액 및 배양액을 분사하여 작물의 온도 및 습도 환경을 제어하여 최적의 발육 상태를 유지하는 포그 스프레이 시스템을 구비한 수직형 작물 재배 장치 및 방법에 관한 것이다. claims: 수직형 작물 재배 장치에 있어서,재배판을 수직으로 적층 하여 작물을 재배할 수 있는 공간을 제공하는 재배부; 상기 재배부에 구비되어 작물의 잎 또는 뿌리에 드라이 포그 및 미스트 포그 중 적어도 하나를 분사하는 분사부; 및상기 분사부의 분사위치, 분사 압력을 제어하는 단말부를 포함하는 포그 스프레이 시스템을 구비한 수직형 작물 재배 장치.수직형 작물 재배 방법에 있어서,재배부의 온도, 습도, pH중 적어도 하나의 정보를 획득하는 단계;상기 획득한 정보에 따라 분사부 제어신호를 생성하는 단계;상기 생성한 분사부 제어신호에 따라 드라이 포그 및 미스트 포그 중 적어도 하나의 분사위치를 결정하는 단계; 및 상기 생성한 분사부 제어신호에 따라 드라이 포그 및 미스트 포그 중 적어도 하나의 분사압력을 결정하는 단계; 를 포함하는 포그 스프레이 시스템을 구비한 수직형 작물 재배 방법.제 4항의 포그 스프레이 시스템을 구비한 수직형 작물 재배 방법을 실행하는 컴퓨터 프로그램이 저장된 컴퓨터가 판독 가능한 기록매체., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

939/1150 Row 939: application_number: 1020200039485, combined_string: invention_title: 작물 재배용 트레이 abstract: 본 발명은 재배하고자 하는 동일한 종류의 작물을 재배하거나 또는 서로 다른 종류의 작물을 유닛(unit) 형태로 분할하여 하나의 트레이 상에서 병행하여 재배할 수 있도록 상부가 개방된 장방형 형태로 길이 방향의 양측에 걸이 부재가 형성되며, 그 길이 방향의 서로 마주보는 내면에 단턱 진 각각의 받침 턱이 형성되는 본체; 및 상기 본체의 내부에 동일한 작물을 유닛 형태로 분할하여 재배하거나 서로 다른 작물을 병행하여 재배할 수 있도록 마련되는 구획부재;를 포함하는 작물 재배용 트레이를 제공한다. 그에 따라 간단한 기술적 구성에 의해 다양한 종류의 작물을 동시에 원활하게 재배할 수 있는 효과를 가진다. claims: 작물 재배시설에서 현수되어 이송 또는 회전되면서 작물을 재배하기 위해 사용되는 작물 재배용 트레이에 있어서, 상기 작물 재배용 트레이는 상부가 개방된 장방형 형태로 길이 방향의 양측에 걸이 부재가 형성되며, 그 길이 방향의 서로 마주보는 내면에 단턱 진 각각의 받침 턱이 형성되는 본체; 및 상기 본체의 내부에 동일한 작물을 유닛 형태로 분할하여 재배하거나 서로 다른 작물을 병행하여 재배할 수 있도록 마련되는 구획부재;를 포함하는 작물 재배용 트레이., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

940/1150 Row 940: application_number: 1020200039486, combined_string: invention_title: 트레이 회전식 작물 재배용 챔버 abstract: 본 발명은 작은 부피를 가지는 챔버에 의해 소량의 작물 재배는 물론 복수 개를 연속배치하여 대량의 작물 재배 또한 원활하게 이루어질 수 있도록 하면서 챔버 내부 조건을 재배하고자 하는 작물에 따라 최적의 조건으로 유지할 수 있도록 베이스 프레임), 작물 재배부, 챔버 하우징, 물 공급 부재, 양액 공급 부재, 온도 센서 및 습도센서, 온풍 공급수단 및 냉풍 공급수단을 포함하는 트레이 회전식 작물 재배용 챔버를 제공한다. 그에 따라 최소한의 설치면적 대비하여 재배 효율성을 극대화할 수 있는 효과와 함께 작물의 재배 양 또한 최대한 증대시킬 수 있는 효과도 가진다. claims: 바닥면에 인출 가능한 받이 트레이를 포함하는 베이스 프레임; 상기 베이스 프레임의 상부에 양측의 받침 프레임 상에서 구동수단에 의해 회전되는 회전축 상에 장착되는 얼레 형태로 양측 측 프레임 사이에 일정 간격의 각각의 행거(hanger) 바가 형성되어 회전되는 회전 프레임, 상기 각 행거 바에 작물을 재배하기 위해 토양이 채워지고 상단 양측에 상기 행거 바에 걸어지는 각각의 고리 부재가 구비되는 각각의 재배 트레이를 포함하는 작물 재배부; 상기 베이스 프레임의 테두리 측에 작물 재배부가 내부에 위치하여 밀폐되도록 적어도 하나 이상의 출입문과 환기창 또는 점검창이 구비되며, 상면에 적어도 하나 이상의 환기 팬이 구비되는 챔버 하우징; 상기 챔버 하우징의 내부 상부에 작물의 광합성(光合成)을 위해 구비되는 광원수단, 수분 공급을 위한 물 공급 부재 및 양액(nutrient) 공급을 위한 양액 공급 부재;를 포함하며, 상기 챔버 하우징의 내부에 온도와 습도를 감지하기 위해 구비되는 온도 센서 및 습도 센서; 및 상기 챔버 하우징의 일측에 상기 챔버 하우징 내부로 온풍 또는 냉풍을 공급하기 위한 온풍 공급수단 및 냉풍 공급수단;을 포함하는 트레이 회전식 작물 재배용 챔버., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

941/1150 Row 941: application_number: 1020200037245, combined_string: invention_title: 공기 순환식 다종 작물 재배 장치 abstract: 본 발명은 공기 순환식 다종 작물 재배 장치 및 방법에 관한 것으로, 본 발명의 공기 순환식 다종 작물 재배 장치는 생장 시 산소를 사용하고 이산화탄소를 배출하는 제1 작물(10)을 생육하도록 외부와 밀폐 형성된 공간을 구비하는 제1 재배 하우징(100), 상기 제1 재배 하우징(100)과 인접 배치되어, 생장 시 이산화탄소를 사용하고 산소를 배출하는 제2 작물(20)을 생육하도록 외부와 밀폐 형성된 공간을 구비하는 제2 재배 하우징(200), 상기 제1 재배 하우징(100) 내의 이산화탄소농도가 높은 공기를 상기 제2 하우징(200)에 공급하는 탄소공급라인(310); 및 상기 제2 재배 하우징(200) 내의 산소농도가 높은 공기를 상기 제1 하우징(100)에 공급하는 산소공급라인(410)을 포함한다. claims: 생장 시 산소를 사용하고 이산화탄소를 배출하는 제1 작물(10)을 생육하도록 외부와 밀폐 형성된 공간을 구비하는 제1 재배 하우징(100);상기 제1 재배 하우징(100)과 인접 배치되어, 생장 시 이산화탄소를 사용하고 산소를 배출하는 제2 작물(20)을 생육하도록 외부와 밀폐 형성된 공간을 구비하는 제2 재배 하우징(200);상기 제1 재배 하우징(100) 내의 이산화탄소농도가 높은 공기를 상기 제2 하우징(200)에 공급하는 탄소공급라인(310); 및상기 제2 재배 하우징(200) 내의 산소농도가 높은 공기를 상기 제1 하우징(100)에 공급하는 산소공급라인(410);을 포함하는 공기 순환식 다종 작물 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

942/1150 Row 942: application_number: 1020200036631, combined_string: invention_title: 인삼 수경 재배용 배드 및 이를 이용한 수경 재배방법 abstract: 본 발명은 인삼 수경 재배용 배드 및 이를 이용한 수경 재배방법에 관한 것으로서, 항바이러스 특성을 갖게 되어 인삼의 수경재배 과정에서 바이러스 감염을 방지하여 인삼의 폐사율을 감소시킴과 함께 안정적인 배양 환경을 제공하여 포낭 형성율을 향상시키기 위한 것이다.이를 실현하기 위한 본 발명은, 인삼의 수경 재배가 이루어지는 배드본체(10)의 상면에는 항바이러스 기능을 위한 보호층(11)과, 상기 보호층(11)의 배드본체 부착력을 강화하기 위한 하도층(12)이 각각 형성되며; 상기 보호층(11)은 오르가노클로로실란, 필러, 안료, 소포제, 증점제, 레벨링제, 분산제, 흐름방지제 및 항바이러스제의 혼합 조성을 이루고; 상기 하도층(12)은 오르가노클로로실란, 증점제, 레벨링제, 흐름방지제의 혼합 조성을 이루는 것을 특징으로 한다. claims: 인삼의 수경 재배가 이루어지는 배드본체(10)의 상면에는 항바이러스 기능을 위한 보호층(11)과, 상기 보호층(11)의 배드본체 부착력을 강화하기 위한 하도층(12)이 각각 형성되며;상기 보호층(11)은 오르가노클로로실란, 필러, 안료, 소포제, 증점제, 레벨링제, 분산제, 흐름방지제 및 항바이러스제의 혼합 조성을 이루고;상기 하도층(12)은 오르가노클로로실란, 증점제, 레벨링제, 흐름방지제의 혼합 조성을 이루는 것을 특징으로 하는 인삼 수경 재배용 배드.청구항 1 내지 청구항 4 중 어느 한 항의 보호층(11) 및 하도층(12)이 배드본체(10)의 표면에 코팅 형성된 수경 재배용 배드를 이용하여 인삼의 수경 재배가 이루어지는 것을 특징으로 하는 인삼 수경 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

943/1150 Row 943: application_number: 1020200033175, combined_string: invention_title: 옥수수대와 사탕수수 줄기박을 이용한 수경재배용 고체배지의 제조방법, 이 고체배지를 포함하는 그로우백 abstract: 본 발명은 옥수수대와 사탕수수 줄기박을 이용한 수경재배용 수경재배용 고체배지의 제조방법 및 상기 방법으로 제조된 그로우백에 관한 것으로서, 상기 방법을 통해 옥수수대와 사탕수수 줄기박, 각종 농축산 부산물/폐기물의 혼합 발효를 통해 다양한 식물의 생육증진 효능이 있는 수경재배용 수경재배용 고체배지와 이를 함유하는 그로우백의 제조가 가능하다. claims: (제1단계) 옥수수대, 사탕수수 줄기박, 볏짚, 밀짚, 콩비지, 쌀막걸리 찌꺼기, 닭축분 및 돼지축분을 혼합하여 원료혼합물을 제조하고, 바실러스 서브틸리스(Bacillus subtilis) 균체 및 아스퍼질러스 니거(Aspergillus niger) 균체를 물에 희석한 발효용 미생물 희석액을 제조하는 단계;(제2단계) 원료 혼합물의 수분함량이 65~70 중량%가 되도록 발효용 미생물 희석액을 원료 혼합물에 첨가하여 발효를 진행하여 발효 배지를 얻는 단계; 및,(제3단계) 상기 발효 배지를 멸균하고 10~30℃에 8~15일간 두어 숙성하는 단계;를 포함하는 것을 특징으로 하는 옥수수대와 사탕수수 줄기박을 이용한 수경재배용 고체배지의 제조방법.제1항의 방법으로 제조된 것을 특징으로 하는 수경재배용 고체배지.제5항의 고체배지를 함유하는 식물 재배용 그로우백., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

944/1150 Row 944: application_number: 1020200029833, combined_string: invention_title: 라이조푸스 속 균주와 키토산 및 사포닌을 포함하는 액상 비료 조성물, 이의 제조방법 및 이를 이용하여 재배된 사과 abstract: 일 양상에 따른 라이조푸스 속 균주 배양물과 키토산 분해 균주 배양물 및 사포닌 액상액을 포함한 액상 비료 조성물, 이의 제조 방법 및 이를 이용하여 재배된 사과를 제공한다. 이에 따르면 키토산 액체 비료를 편리하고 대량으로 생산할 수 있고, 이를 식물 및 토양에 분사하여 식물의 생육을 향상시킬 수 있다. 또한, 농약과 화학비료를 사용하지 않고도 해충이 예방되면서 조사포닌 함량이 증가된 기능성 농작물을 재배할 수 있다. claims: 사과의 조사포닌 함량이 5mg/g 이상 되도록, 사포닌액 0.01 중량부 내지 10 중량부, 0.01 중량부 내지 20 중량부의 라이조푸스 속(Rhizopus species) 균주 배양물, 0.01 중량부 내지 20 중량부의 키토산 분해 균주 배양물의 혼합물을 포함하고,당(sugar), 솔빈산가리(potassium sorbate), 아황산 나트륨(sodium sulfite), EDTA(ethylenediaminetetraacetic acid), 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일 및 아미노산을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물을 이용하여 재배된 사과.사과의 조사포닌 함량이 5mg/g 이상 되도록, 사포닌액 0.01 중량부 내지 10 중량부, 0.01 중량부 내지 20 중량부의 라이조푸스 속(Rhizopus species) 균주 배양물, 0.01 중량부 내지 20 중량부의 키토산 분해 균주 배양물의 혼합물을 포함하고,0.01 중량부 내지 10 중량부의 당(sugar), 0.01 중량부 내지 20 중량부의 솔빈산가리(potassium sorbate), 0.1 중량부 내지 20 중량부의 아황산 나트륨(sodium sulfite), 0.1 중량부 내지 20 중량부의 EDTA(ethylenediaminetetraacetic acid), 0.01 중량부 내지 10 중량부의 붕소, 0.01 중량부 내지 10 중량부의 황산 아연, 0.01 중량부 내지 10 중량부의 피톤치드, 녹차추출물, 천연에센스오일 및 0.5 중량부 내지 60 중량부의 아미노산을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물.키토산, 키토산 분해 균주, 및 곡물의 혼합물을 발효시켜 키토산 분해 균주 배양물을 제조하는 단계;라이조푸스 속 균주를 백색 구균과 복합 면역시킨 곡류를 발효시켜 라이조푸스 균주 배양물을 제조하는 단계;사포닌액을 마련하는 단계;재배하고자 하는 사과의 조사포닌 함량이 5mg/g 이상되도록, 상기 사포닌액을 상기 키토산 분해 균주 배양물, 상기 라이조푸스 균주 배양물 및 당과 혼합하여 마련된 혼합물을 10 분 내지 48 시간 동안 배양하여 배양물을 마련하는 단계; 상기 배양물에 솔빈산가리, 아황산 나트륨, EDTA, 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산을 가하고 10분 내지 48시간 동안 교반하는 단계;를 포함하며, 상기 키토산 분해 균주 배양물을 제조하는 단계는,0.1 중량부 내지 15 중량부의 키토산, 0.1 중량부 내지 15 중량부의 키토산 분해 균주, 0.1 중량부 내지 20 중량부의 당밀, 잔부 미강박 및 기타 불가피한 불순물로 이루어진 키토산 분해 균주 혼합물을 마련하는 키토산 준비과정; 및상기 키토산 분해 균주 혼합물을 발효시키켜 상기 키토산 분해 균주 배양물을 제조하는 키토산 발효과정;을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물을 제조하는 방법.키토산, 키토산 분해 균주, 및 곡물의 혼합물을 발효시켜 키토산 분해 균주 배양물을 제조하는 단계;라이조푸스 속 균주를 백색 구균과 복합 면역시킨 곡류를 발효시켜 라이조푸스 균주 배양물을 제조하는 단계;사포닌액을 마련하는 단계;재배하고자 하는 사과의 조사포닌 함량이 5mg/g 이상되도록, 상기 사포닌액을 상기 키토산 분해 균주 배양물, 상기 라이조푸스 균주 배양물 및 당과 혼합하여 마련된 혼합물을 10 분 내지 48 시간 동안 배양하여 배양물을 마련하는 단계; 상기 배양물에 솔빈산가리, 아황산 나트륨, EDTA, 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산을 가하고 10분 내지 48시간 동안 교반하는 단계;를 포함하며, 상기 라이조푸스 균주 배양물을 제조하는 단계는,0.1 중량부 내지 20 중량부의 당밀과 잔부 미강박 및 기타 불가피한 불순물로 이루어진 라이조푸스 균주 혼합물을 마련하는 라이조푸스 혼합과정; 및상기 라이조푸스 균주 혼합물을 발효시키켜 상기 라이조푸스 균주 혼합물을 제조하는 라이조푸스 발효과정;을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물을 제조하는 방법.쪽파의 조사포닌 함량이 2mg/g 이상 되도록, 사포닌액 0.01 중량부 내지 10 중량부, 0.01 중량부 내지 20 중량부의 라이조푸스 속(Rhizopus species) 균주 배양물, 0.01 중량부 내지 20 중량부의 키토산 분해 균주 배양물의 혼합물을 포함하고,당(sugar), 솔빈산가리(potassium sorbate), 아황산 나트륨(sodium sulfite) EDTA(ethylenediaminetetraacetic acid), 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일 및 아미노산을 포함하며,상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물.키토산, 키토산 분해 균주, 및 곡물의 혼합물을 발효시켜 키토산 분해 균주 배양물을 제조하는 단계;라이조푸스 속 균주를 백색 구균과 복합 면역시킨 곡류를 발효시켜 라이조푸스 균주 배양물을 제조하는 단계;사포닌액을 마련하는 단계;재배하고자 하는 쪽파의 조사포닌 함량이 2mg/g 이상되도록, 상기 사포닌액을 상기 키토산 분해 균주 배양물, 상기 라이조푸스 균주 배양물 및 당과 혼합하여 마련된 혼합물을 10 분 내지 48 시간 동안 배양하여 배양물을 마련하는 단계; 상기 배양물에 솔빈산가리, 아황산 나트륨, EDTA, 붕소, 황산 아연, 피톤치드, 녹차추출물, 천연에센스오일, 및 아미노산을 가하고 10분 내지 48시간 동안 교반하는 단계;를 포함하며, 상기 사포닌액은,인삼추출물(Panax Ginseng Root Extract) 1.0%, 1,3-부탄디올(1,3-Butylene Glycol) 40.0%, 잔부 정제수(Water) 및 기타 불순물을 포함하는 것을 특징으로 하는, 액상 비료 조성물을 제조하는 방법., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

945/1150 Row 945: application_number: 1020200022651, combined_string: invention_title: 열처리된 목재 칩, 질소원 및 발효볏짚을 유효성분으로 함유하는 작물 재배용 인공토양 조성물 abstract: 본 발명은 열처리된 목재 칩, 질소원 및 발효볏짚을 유효성분으로 함유하는 작물 재배용 인공토양 조성물에 관한 것으로, 상기 열처리된 참나무 칩과 질소원으로 이루어진 혼합물 또는 상기 혼합물과 발효볏짚을 유효성분으로 함유하는 조성물은 참외 종자의 발아율 및 엽수를 증가시키고 초장 및 근장의 생장을 향상시키는 효과를 나타내는 것이 확인됨에 따라, 상기 조성물은 일반 토양 및 인공사료를 대체할 수 있는 작물 재배용 인공토양으로 제공될 수 있다. claims: 열처리된 목재 칩과 질소원으로 이루어진 혼합물 및 발효볏짚을 유효성분으로 함유하는 작물 재배용 인공토양 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

946/1150 Row 946: application_number: 1020200023173, combined_string: invention_title: 공기정화용 식물재배장치가 마련된 에어커튼 시스템 abstract: 공기정화용 식물재배장치가 마련된 에어커튼 시스템이 개시된다. 본 발명의 공기정화용 식물재배장치가 마련된 에어커튼 시스템은, 수직 몸체를 이루며, 측벽에 식물이 식재되며 공기를 흡입하여 흡입된 공기에 포함된 미세먼지 및 초미세먼지를 포함한 오염물질을 걸러내는 공기정화 벽부; 지붕을 이루며, 지붕의 테두리를 따라 공기 배출구가 마련되어 상기 공기정화 벽부를 거쳐 오염물질이 걸러진 공기를 공급받아 상기 공기 배출구를 통해 수직 하부로 배출하는 에어커튼 분사부; 및 바닥을 이루며, 바닥의 테두리를 따라 공기 흡입구가 마련되어 상기 에어커튼 분사부의 공기 배출구에서 배출된 공기를 흡입하는 공기흡입부:를 포함하는 것을 특징으로 한다. claims: 수직 몸체를 이루며, 측벽에 식물이 식재되며 공기를 흡입하여 흡입된 공기에 포함된 미세먼지 및 초미세먼지를 포함한 오염물질을 걸러내는 공기정화 벽부;지붕을 이루며, 지붕의 테두리를 따라 공기 배출구가 마련되어 상기 공기정화 벽부를 거쳐 오염물질이 걸러진 공기를 공급받아 상기 공기 배출구를 통해 수직 하부로 배출하는 에어커튼 분사부;바닥을 이루며, 바닥의 테두리를 따라 공기 흡입구가 마련되어 상기 에어커튼 분사부의 공기 배출구에서 배출된 공기를 흡입하는 공기흡입부;상기 에어커튼 분사부의 지붕 상부면에 마련되는 태양광 패널에 의해 생산된 전기를 저장하고 공급하는 축전지부;상기 공기정화 벽부를 거쳐 오염물질이 걸러진 공기를 공급받아 상기 에어커튼 분사부의 공기 배출구로 고압분사하는 분사펌프; 및 상기 공기흡입부에 마련되며, 에어커튼을 형성한 후 하강하는 공기를 상기 공기 흡입구로 흡입하여 상기 에어커튼 분사부로 순환시키기 위한 송풍기와 상기 송풍기를 구동시키는 송풍모터를 포함하는 흡기장치:를 포함하고, 상기 분사펌프 및 송풍모터는 상기 축전지부로부터 전기를 공급받아 구동되는 것을 특징으로 하는 공기정화용 식물재배장치가 마련된 에어커튼 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

947/1150 Row 947: application_number: 1020200021986, combined_string: invention_title: 작물 재배 환경을 모니터링하는 모니터링 장치, 방법 및 컴퓨터 프로그램 abstract: 작물 재배 환경을 모니터링하는 모니터링 장치는 복수의 센서를 이용하여 획득한 환경 이력을 입력받는 환경 이력 입력부, 구동기 동작 이력을 입력받는 구동기 동작 이력 입력부, 상기 환경 이력 및 상기 구동기 동작 이력에 대하여 퍼지화를 수행함으로써 퍼지화 데이터를 생성하는 퍼지화 데이터 생성부, 기구축된 복수의 작물에 대한 재배 지식에 기초하여 퍼지 규칙을 생성하는 퍼지 규칙 생성부 및 상기 퍼지화 데이터 및 상기 퍼지 규칙에 기초하여 작물 재배 환경의 장해 발생 가능성을 판단하는 장해 판단부를 포함한다. claims: 작물 재배 환경을 모니터링하는 모니터링 장치에 있어서,복수의 센서를 이용하여 획득한 환경 이력을 입력받는 환경 이력 입력부;구동기 동작 이력을 입력받는 구동기 동작 이력 입력부;상기 환경 이력 및 상기 구동기 동작 이력에 대하여 퍼지화를 수행함으로써 퍼지화 데이터를 생성하는 퍼지화 데이터 생성부;기구축된 복수의 작물에 대한 재배 지식에 기초하여 퍼지 규칙을 생성하는 퍼지 규칙 생성부; 및상기 퍼지화 데이터 및 상기 퍼지 규칙에 기초하여 작물 재배 환경의 장해 발생 가능성을 판단하는 장해 판단부를 포함하는 것인, 모니터링 장치.작물 재배 환경을 모니터링하는 모니터링 방법에 있어서,복수의 센서를 이용하여 획득한 환경 이력을 입력받는 단계;구동기 동작 이력을 입력받는 단계;상기 환경 이력 및 상기 구동기 동작 이력에 대하여 퍼지화를 수행함으로써 퍼지화 데이터를 생성하는 단계;기구축된 복수의 작물에 대한 재배 지식에 기초하여 퍼지 규칙을 생성하는 단계; 및상기 퍼지화 데이터 및 상기 퍼지 규칙에 기초하여 작물 재배 환경의 장해 발생 가능성을 판단하는 단계를 포함하는 것인, 모니터링 방법.작물 재배 환경을 모니터링하는 명령어들의 시퀀스를 포함하는 매체에 저장된 컴퓨터 프로그램에 있어서,상기 컴퓨터 프로그램은 컴퓨팅 장치에 의해 실행될 경우,복수의 센서를 이용하여 획득한 환경 이력을 입력받고,구동기 동작 이력을 입력받고,상기 환경 이력 및 상기 구동기 동작 이력에 대하여 퍼지화를 수행함으로써 퍼지화 데이터를 생성하고,기구축된 복수의 작물에 대한 재배 지식에 기초하여 퍼지 규칙을 생성하고,상기 퍼지화 데이터 및 상기 퍼지 규칙에 기초하여 작물 재배 환경의 장해 발생 가능성을 판단하도록 하는 명령어들의 시퀀스를 포함하는 것인, 매체에 저장된 컴퓨터 프로그램., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

948/1150 Row 948: application_number: 1020200021094, combined_string: invention_title: 작물 재배 장치 및 이를 이용한 작물 재배 방법 abstract: 본 발명의 일 실시예에 따른 작물 재배 장치는 작물을 수용 가능하도록 내부 공간이 형성되고, 하부 재배지의 상측에 설치되도록 제공되는 재배 상자; 및 상기 하부 재배지에 대한 상기 재배 상자의 상대 높낮이를 조절하기 위해 제공되는 구동부를 포함할 수 있다. claims: 작물을 수용 가능하도록 내부 공간이 형성되고, 하부 재배지의 상측에 설치되도록 제공되는 재배 상자; 및상기 하부 재배지에 대한 상기 재배 상자의 상대 높낮이를 조절하기 위해 제공되는 구동부를 포함하는 작물 재배 장치.제1 항 내지 제11 항 중 어느 한 항에 따른 작물 재배 장치를 이용한 작물 재배 방법에 있어서,상기 하부 재배지에 아스파라거스가 식재되어 있는 상태로 상기 재배 상자에서 아스파라거스 순을 재배하고 수확하는 단계;상기 하부 재배지에서 아스파라거스 순을 재배하고 수확하는 단계; 및상기 재배 상자를 상기 하부 재배지로부터 이격시켜 상기 재배 상자에서 작물을 재배하는 단계를 포함하는 작물 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

949/1150 Row 949: application_number: 1020200016708, combined_string: invention_title: 대차와 ICT 스마트팜 기술을 이용한 인삼 수경 재배 장치. abstract: 본 발명은 공장 건물 내부에 일정 간격으로 정렬 배치되어, 인삼을 재배하는 셀모듈;상기 셀모듈에 구비된 인삼의 성장을 분석하고, 약액 살포 작업의 자동화를 수행하는 자동화 모듈;상기 셀모듈(100)에서 재배되는 인삼의 생육환경을 측정하는 센서모듈;상기 센서모듈의 측정결과에 근거하여, 상기 셀모듈에서 재배되는 인삼의 생육환경을 자동으로 조절하는 생육환경조절모듈;상기 센서모듈, 생육환경조절모듈 및 상기 자동화 모듈과 무선으로 정보를 송수신하는 ICT 단말기;를 포함하여 구성되는 것을 특징으로 하는 대차와 ICT 스마트팜 기술을 이용한 인삼 수경 재배 장치에 관한 것이다. claims: 공장 건물 내부에 일정 간격으로 정렬 배치되어, 인삼을 재배하는 셀모듈(100);상기 셀모듈(100)에 구비된 인삼의 성장을 분석하고, 약액 살포 작업의 자동화를 수행하는 자동화 모듈(200);상기 셀모듈(100)에서 재배되는 인삼의 생육환경을 측정하는 센서모듈(300);상기 센서모듈(300)의 측정결과에 근거하여, 상기 셀모듈(100)에서 재배되는 인삼의 생육환경을 자동으로 조절하는 생육환경조절모듈(500);상기 센서모듈(300), 생육환경조절모듈(500) 및 상기 자동화 모듈(200)과 무선으로 정보를 송수신하는 ICT 단말기(600);를 포함하여 구성되는 것을 특징으로 하는 대차와 ICT 스마트팜 기술을 이용한 인삼 수경 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

950/1150 Row 950: application_number: 1020200013469, combined_string: invention_title: 수조가 마련되는 가정용 수경재배장치 abstract: 본 발명은, 일정크기의 내부공간이 마련되며 전면부위가 개구되는 몸체(11), 개구된 몸체(11)의 전면부위 하측에 마련되는 가이드레일(12), 몸체(11)의 내부 상면부위에 설치되는 엘이디광원(13), 몸체(11)의 내부 일측부위에 설치되는 온습도기구(14)가 구비되는 하우징부; 상측부위가 개구되되 수위감지수단이 마련되어 몸체(11)의 내부공간 하측부위에 안치되는 수경재배통(21), 복수 개의 생육공(23)이 형성되어 개구된 수경재배통(21)의 상측부위를 밀폐하는 지지판(22)이 구비되는 수경재배부; 상측부위가 개구되되 하면부위가 가이드레일(11)을 따라 전후로 슬라이딩하며 몸체(11)의 전면부위를 개폐하는 수조부(30); 제어보드가 마련되어 몸체(11)의 외면 일측부위에 설치되는 제어박스(41), 제어박스(41)의 일측에 내장되는 모터(42), 모터(42)와 연결되어 제어박스(41)의 타측에 내장되는 펌프(43), 일단부위는 펌프(43)의 일측부위에 연결되고 타측부위는 수조부(30) 내부로 연장되는 배수관(44), 일단부위는 펌프(43)의 타측부위에 연결되고 타측부위는 수경재배통(21) 내부로 연장되는 급수관(45)이 구비되는 제어부:를 포함하는 수조가 마련되는 가정용 수경재배장치를 제공한다. claims: 일정크기의 내부공간이 마련되며 전면부위가 개구되는 몸체(11), 개구된 몸체(11)의 전면부위 하측에 마련되는 가이드레일(12), 몸체(11)의 내부 상면부위에 설치되는 엘이디광원(13), 몸체(11)의 내부 일측부위에 설치되는 온습도기구(14)가 구비되는 하우징부;상측부위가 개구되되 수위감지수단이 마련되어 몸체(11)의 내부공간 하측부위에 안치되는 수경재배통(21), 복수 개의 생육공(23)이 형성되어 개구된 수경재배통(21)의 상측부위를 밀폐하는 지지판(22)이 구비되는 수경재배부;상측부위가 개구되되 하면부위가 가이드레일(11)을 따라 전후로 슬라이딩하며 몸체(11)의 전면부위를 개폐하는 수조부(30);제어보드가 마련되어 몸체(11)의 외면 일측부위에 설치되는 제어박스(41), 제어박스(41)의 일측에 내장되는 모터(42), 모터(42)와 연결되어 제어박스(41)의 타측에 내장되는 펌프(43), 일단부위는 펌프(43)의 일측부위에 연결되고 타측부위는 수조부(30) 내부로 연장되는 배수관(44), 일단부위는 펌프(43)의 타측부위에 연결되고 타측부위는 수경재배통(21) 내부로 연장되는 급수관(45)이 구비되는 제어부:를포함하는 수조가 마련되는 가정용 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

951/1150 Row 951: application_number: 1020200012688, combined_string: invention_title: 액비, 그리고 이를 이용하는 인삼 노지 재배 시스템 abstract: 본 발명은 인삼을 노지에서 재배하는 인삼 노지 재배 시스템에 관한 것이다. 본 발명의 일 실시 예에 따른 인삼 노지 재배 시스템은 인삼이 재배되는 노지에 액비를 분사하는 액비 공급부를 포함하되, 상기 액비는, 식물성 한약재를 발효한 발효액; 및 수용성규소(SiO3/Ge/V)를 포함하는 라바(LAVA)수를 포함한다. claims: 인삼이 재배되는 노지에 액비를 분사하는 액비 공급부; 및상기 노지 및 상기 노지에 인접한 외곽 영역에 미산성 차아염소산수를 분사하는 소독 방제부를 포함하되,상기 액비는, 식물성 한약재를 발효한 발효액; 및 수용성규소(SiO3/Ge/V)를 포함하는 라바(LAVA)수를 포함하는 인삼 노지 재배 시스템.액비를 인삼이 재배되는 노지에 분사하되,상기 액비는,식물성 한약재를 발효한 발효액; 및 수용성규소(SiO3/Ge/V)를 포함하는 라바(LAVA)수를 포함하는 인삼 노지 재배 방법.식물성 한약재를 발효한 발효액; 및 수용성규소(SiO3/Ge/V)를 포함하는 라바(LAVA)수를 포함하는 액비., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

952/1150 Row 952: application_number: 1020200010172, combined_string: invention_title: 작물 재배 또는 육묘용 포트 어셈블리 abstract: 본 발명은 포트플레이트(60)의 포트(61)들 사이의 길이방향으로 뚫려져 연속하여 이어지는 어퍼홈라인(62)에 선형조립수단(70)을 끼워 포트플레이트(60)들을 연속하여 누르면서 일체화시킬 수 있도록 함으로써 바람에 의한 영향이나 작업자의 부딪힘에 의한 영향을 최소화시켜 포트플레이트(60)들을 견고하게 안정될 수 있도록 함과 동시에 작물 재배 완료 후 또는 작물 육묘 완료 후 포트플레이트(60)들을 적층시켜 보관하고자 밧줄로 묶고자 할 때 어퍼홈라인(62)을 경유시킬 수 있도록 함으로써 보관시 묶음처리 상태 역시 더욱 견고하게 실현케 할 수 있고, 특히, 선형조립수단(70)이 어퍼홈라인(62)에 끼워진 상태로 포트플레이트(60)들을 누를 수 있도록 하여 어퍼홈라인(62)으로부터 선형조립수단(70)의 분리현상을 극소화시켜 선형조립수단(70)의 무단이탈에 의한 작물로의 악영향(상처나 훼손)을 철저히 방지하고, 나아가 선형조립수단(70) 및 받침파이프(F1) 상호간의 양끝단의 직접적인 묶음처리로서 프레임(F)에서부터 포트플레이트(60)들에 이르기까지 일체화된 상태를 보장하여 보다 안정감 있게 작물을 재배 및 육묘할 수 있는 특유의 작용을 발휘하는 작물 재배 또는 육묘용 포트 어셈블리에 관한 발명이다. claims: 배수구멍(61a)이 뚫린 포트(61)들을 지니면서 직선상으로 연속하여 이웃하는 포트플레이트(60)들을 포함하는 작물 재배 또는 육묘용 포트 어셈블리에 있어서,상기 포트플레이트(60)들은 상기 포트(61)들 사이의 길이방향으로 뚫려져 연속하여 이어지는 어퍼홈라인(62)을 각각 구비하고,상기 어퍼홈라인(62)들을 따라 끼워져 상기 포트플레이트(60)들을 연속하여 누르면서 일체화시키는 선형조립수단(70)을 포함하고,상기 포트플레이트(60)는 상기 어퍼홈라인(62)을 따라 하향 돌출되는 언더볼륨라인(63)을 더 포함하고,상기 포트플레이트(60)의 길이방향의 전측으로부터 폭방향을 따라 돌출된 전측어퍼돌출턱(64)과, 상기 포트플레이트(60)의 길이방향의 후측으로부터 폭방향을 따라 돌출된 후측언더돌출턱(65)을 더 포함하고,상기 포트플레이트(60)들은 직선상으로 연속하여 이웃할 때 상기 후측언더돌출턱(65) 위에 상기 전측어퍼돌출턱(64)이 포개어져 합치되고,상기 전측어퍼돌출턱(64)은 상기 포트플레이트(60)의 길이방향의 전측으로부터 폭방향을 따라 돌출되면서 상기 언더볼륨라인(63)에 대응되는 부분에서 오픈되는 수직홀(64a)을 구비하고,상기 후측언더돌출턱(65)은 상기 포트플레이트(60)의 길이방향의 후측으로부터 폭방향을 따라 상기 언더볼륨라인(63)과 함께 돌출되어 상기 수직홀(64a)을 리커버링하면서 상기 어퍼홈라인(62)들을 연속하여 이어주는 것을 특징으로 하는 작물 재배 또는 육묘용 포트 어셈블리., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

953/1150 Row 953: application_number: 1020200008819, combined_string: invention_title: 수경재배 인삼잎을 이용한 진세노사이드 저배당체 포함 식품 조성물 abstract: 본 발명은 수경재배 인삼잎을 이용한 진세노사이드 저배당체 포함 식품 조성물에 관한 것으로서, 보다 상세하게는 수경재배 인삼잎을 증숙 처리하는 단계를 포함하여 진세노사이드 저배당체 함량이 증가된 인삼잎 농축액을 제조하는 방법, 및 이를 통해 제조된 인삼잎 농축액 및 식품 조성물에 관한 것이다. claims: 물기가 제거된 수경재배 인삼잎을 증숙 처리하는 단계;상기 증숙 처리된 인삼잎을 건조하고 분쇄하는 단계; 및상기 건조 및 분쇄된 인삼잎을 추출하여 농축하는 단계를 포함하는,진세노사이드 1배당체 함량이 증가된 인삼잎 농축액의 제조방법.물기가 제거된 수경재배 인삼잎을 증숙 처리하는 단계;상기 증숙 처리된 인삼잎을 건조하고 분쇄하는 단계; 및상기 건조 및 분쇄된 인삼잎을 추출하여 농축하는 단계를 포함하는,인삼잎 농축액 제조시 진세노사이드 1배당체 함량을 증가시키는 방법.제1항내지 제7항 중 어느 한 항의 방법에 의해 제조된 인삼잎 농축액., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

954/1150 Row 954: application_number: 1020200006549, combined_string: invention_title: 땅콩 나물 재배 방법 abstract: 본 발명은 땅콩 나물 재배 방법에 있어서, 직경이 서로 다른 복수의 톱밥을 혼합 발효한 부토를 재배틀에 담는 단계와, 상기 부토에 땅콩 종자를 파종하는 단계와, 상기 땅콩 종자에 상기 부토를 덮는 단계와, 상기 부토 상에 살수 하는 단계를 포함하는 제1공정과, 상기 제1공정의 시행 이후, 상기 부토에서 생장한 땅콩 나물에 자외선을 일정시간 연속하여 또는 주기적으로 온/오프를 반복하여 조사하는 자외선 조사 단계와, 상기 자외선 조사 단계 이후 상기 땅콩 나물을 수확하는 수확 단계를 포함하는 제2공정으로 이루어지는 땅콩 나물 재배 방법으로서, 본 발명에 따르면 금속성분의 인위적 첨부, 과다한 용수의 사용 및 과다한 시설관리 비용 발생이 없고, 물만으로 재배가 가능하여 무공해 및 유기농이 가능한 땅콩 나물을 높은 수확률로 재배할 수 있으며, 또한, 땅콩의 고유 특성인 레스베라트롤의 함량을 극대화하는 효과를 이룰 수 있다. claims: 땅콩 나물 재배 방법에 있어서,직경이 서로 다른 복수의 톱밥을 혼합 발효한 부토에 땅콩 종자를 파종하는 단계와,상기 땅콩 종자에 상기 부토를 덮는 단계와,상기 부토 상에 살수하는 단계를 포함하는 제1공정과,상기 제1공정의 시행 이후, 생장한 땅콩 나물에 자외선을 일정시간 연속하여 또는 주기적으로 온/오프를 반복하여 조사하는 자외선 조사 단계와,상기 자외선 조사 단계 이후 상기 땅콩 나물을 수확하는 수확 단계를 포함하는 제2공정으로 이루어지는 것을 특징으로 하는 땅콩 나물 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

955/1150 Row 955: application_number: 1020190179745, combined_string: invention_title: 인삼밭을 기반으로 하는 태양광발전장치 및 이를 이용한 인삼의 연작 재배 방법 abstract: 본 발명은 인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법에 관한 것으로서 보다 상세하게는, 인삼을 재배하는 경작지에 최적의 햇볕이 투광할 수 있도록 태양광모듈 사이를 이격시킨 태양광발전장치를 설치하여 발전과 동시에 인삼의 해가림막으로 이용할 수 있고, 태양의 위치 변화에 의해 발생하는 음영부분에 적당량의 햇볕을 전달받거나 반사시킴으로서 적절한 인삼의 생육 환경을 조성할 수 있는 인삼밭을 기반으로 하는 태양광발전장치를 제공하고 이를 이용한 인삼의 연작 재배 방법을 제공하는 것이다. claims: 인삼밭을 기반으로 하는 태양광발전장치에 있어서,상기 인삼밭의 지면위에 경사진 지붕형상으로 일정한 기울기를 갖는 경사프레임(120); 상기 경사프레임(120)의 상부에 설치되는 투명판재(310);상기 투명판재(310)의 상면에 소정의 간격으로 이격시켜 설치되는 복수개의 태양광모듈(200);을 포함하는 것을 특징으로 하는 인삼밭을 기반으로 하는 태양광발전장치.인삼밭을 기반으로 하는 태양광발전장치에 있어서,상기 인삼밭의 지면위에 경사진 지붕형상으로 일정한 기울기를 갖는 경사프레임(120); 상기 경사프레임(120)의 상면에 소정의 간격으로 이격시켜 설치되는 복수개의 태양광모듈(200);이격된 상기 태양광모듈(200)의 사이에 설치되는 투명재질의 투명간격부재(320);를 포함하는 것을 특징으로 하는 인삼밭을 기반으로 하는 태양광발전장치.인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법에 있어서,인삼재배지에서 인삼(400)의 씨앗 또는 묘종을 이용해 재배하는 단계 (S1단계);상기 인삼(400)을 수확하는 단계 (S2단계);상기 인삼(400)의 재배가 끝난 흙을 외부로 걷어내는 단계 (S3단계);새로운 흙에 퇴비 및 비료를 배합하는 단계 (S4단계);상기 새로운 흙을 상기 인삼재배지로 옮긴 후 두둑(410)을 성형하는 단계 (S5단계);를 포함하는 것을 특징으로 하는 인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법.인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법에 있어서,인삼재배지에 인삼(400)의 씨앗 또는 묘종을 이용해 재배하는 단계 (S10단계);상기 인삼(400)을 수확하는 단계 (S20단계);상기 인삼(400)의 재배가 끝난 흙을 외부로 걷어내는 단계 (S30단계);상기 인삼(400)의 재배가 끝난 흙에 인삼 외 타 작물을 재배하여 지력을 회복하는 단계 (S40단계);새로운 흙을 상기 인삼재배지로 옮긴 후 두둑(410)을 성형하는 단계 (S50단계);를 포함하는 것을 특징으로 하는 인삼밭을 기반으로 하는 태양광발전장치를 이용한 인삼의 연작 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

956/1150 Row 956: application_number: 1020200173145, combined_string: invention_title: 참외 수경재배 전용 지면매립형 배지용기 abstract: 참외 농사 연작 재배시에 필수적으로 토양 관리비용을 획기적으로 감소시키고 병충해와 병원균으로부터 이를 원천적으로 차단할 수 있는 참외 수경재배 전용 지면매립형 배지용기에 관한 것이다.참외 연작재배시 토양의 병충해 및 병원균의 전파를 차단하고 토양 유지관리를 개별적으로 관리할 수 있도록 토양의 지면에 일부만을 개토 후 방수포를 깐 후 부분 매립시키는 매립설치수단을 구비한다.따라서 본 발명은 위와 같은 본 발명의 참외 수경재배 전용 지면매립형 배지용기는 전술된 바와 같이, 참외재배의 경우 연작농사시 선택적으로 병원균오염 방지와 병충해 방지를 매립설치수단을 통해 효율적으로 할 수 있는 이점이 있고, 또, 토양 주변 잡초나 병충해 등 주변환경의 뿌리 유입을 원천적으로 차단할 수 있는 이점이 있다. claims: 참외 연작재배시 토양의 병충해 및 병원균의 전파를 차단하고 토양 유지관리를 개별적으로 관리할 수 있도록 토양의 지면에 일부만을 개토 후 방수포를 깐 후 부분 매립시키는 매립설치수단(A)을 구비한 지면매립형 배지용기에 있어서,배수가 용이하게 이루어질 수 있는 탈부착형 배지용기 받침대(10)를 지면에 매립시킬 수 있도록 구비한 것과, 상기 배지용기 받침대(10)의 상측에는 참외작물을 흙과 함께 정식할 수 있는 배지용기(20)를 길이방향으로 하나 이상 연결되도록 구비한 것과,상기 배지용기(20)에는 흙의 내부 온도를 외부 조절장치(미도시)에 냉·온수에 의해 조절할 수 있는 지온호스(30)를 구비한 것과,상기 배지용기(20)는,길이 방향으로 상측으로 개방된 몸체(210)를 구비하되, 그 양측에는 받침판(230)을 구비하고,상기 몸체(210)의 길이방향 양측 끝단에는 서로 겹쳐서 연결될 수 있도록 음각 또는 양각 형태를 갖는 음각걸림턱(218)과 양각걸림턱(219)을 구비하며,상기 몸체(210)의 중심 하부에는 편측 또는 양측에 지온호스 고정용 클램프브라켓(220)을 구비하고,상기 클램프브라켓(220)의 전·후측으로 수개의 배수구멍(216)을 구비하며,상기 몸체(210)의 양측에는 상기 몸체(210)의 내면을 따라 돌출되는 격판 가이드레일홈(211)을 구비하고,상기 양측 격판 가이드레일홈(211)에는 지온호스(30)를 통과시키는 수용홈(212)을 구비한 격판(250)을 탈부착형태로 구비하며,상기 몸체(210)의 하부 저면 양측에는 배지용기 받침대(10)의 받침턱(160)을 고정 지지할 수 있도록 걸림브라켓(215)을 구비한 것을 특징으로 한 참외 수경재배 전용 지면매립형 배지용기, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

957/1150 Row 957: application_number: 1020200140095, combined_string: invention_title: 농약 자동 살포장치 abstract: 본 발명은 농약 자동 살포장치에 관한 것으로, 상세하게는, 혼합탱크에 투입된 액상의 농약(또는 물, 사료, 비료 등)을 전기 스위치를 통해 자동으로 개폐되는 분배기를 통해 각각의 고랑을 따라 설치된 메인호스에 자동 공급하고, 메인호스에 각각 'T'자형 분기구를 설치하여 각 농작물(과수 등)을 따라 분기호스를 연결하여 농약을 자동으로 공급함으로써 병충해 방제작업시 작업자의 안전을 도모하고, 농약 사용량을 줄이면서 작업 편의성을 제공하며, 적절한 시기에 병충해 방제작업을 실시하여 병충해 방제작업의 효율성을 향상시킬 수 있는 농약 자동 살포장치에 관한 것이다. claims: 혼합탱크;상기 혼합탱크에 저장된 액상의 농약, 물, 비료 또는 사료를 공급하는 양수기;상기 양수기를 통해 상기 혼합탱크로부터 공급되는 액상의 농약 또는 물을 분배하는 분배기;상기 분배기에 연결되고, 농작물 재배지의 각 고랑을 따라 바닥에 각각 설치되어 상기 분배기로부터 분배된 액상의 농약 또는 물을 각 고랑으로 이송하며, 농작물 재배지에 식재된 각 농작물에 대응하여 복수 개의 'T'자형 분기구가 설치된 메인호스;상기 메인호스에 설치된 'T'자형 분기구에 착탈 가능하게 결합되고, 해당 농작물을 따라 길게 연장 설치되어 상기 메인호스로부터 공급된 액상의 농약 또는 물을 해당 농작물로 이송하며, 해당 농작물의 각 가지에 대응하여 'T'자형 분기구가 형성된 제1 분기호스;상기 제1 분기호스의 'T'자형 분기구에 착탈 가능하게 결합되고, 해당 농작물의 각 가지를 따라 길게 연장 설치되며, 길이방향을 따라 복수 개의 상향식 분사구가 설치되어 상기 제1 분기호스에서 공급되는 액상의 농약 또는 물을 상측으로 분사하는 제2 분기호스; 및상기 제1 분기호스의 상단부에 착탈 가능하게 결합되고, 상기 제1 분기호스를 통해 공급되는 액상의 농약이나 물을 해당 농작물의 상부에서 하부로 분사하는 분사헤드;를 포함하되,해당 농작물의 가지들 중 지면으로부터 1~1.5m 높이에 있는 가지를 따라 길에 연장 설치되고, 상기 제1 분기호스에 설치된 'T'자형 분기구에 착탈 가능하게 결합되며, 길이방향을 따라 복수 개의 하향식 분사구가 설치되어 상기 제1 분기호스에서 공급되는 액상의 농약(잡초제)을 농작물 재배지의 지면에 자라고 있는 잡초로 분사하여 제거하는 제3 분기호스를 더 포함하는 것을 특징으로 하는 농약 자동 살포장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

958/1150 Row 958: application_number: 1020200131521, combined_string: invention_title: 영농지에 구축된 태양광, 강풍유도용 태양광발전판 abstract: 본 발명은 영농지에 구축된 태양광, 강풍유도용 태양광발전판에 관한 것으로서, 더 상세하게는 과수원이나 비닐하우스, 벼재배 단지와 같은 농지에서, 태풍이나 냉해에 대한 피해를 방지하도록 태양광발전판의 저측단에 연계되는 강풍유도벽을 연결로서 농작물이나 시설물에 대한 강풍이나 냉해 피해 방지하는 발명이다. 일반적으로 과수원에서 외부로 노출된 과수목이나 원예단지에서는, 기후변화로 더 강력해진 강풍으로 발생되는 피해는 농가에 큰 부담이 되고 있는 것이다.고로 농지(70), 비닐하우스로 형성된 원예단지(65)와 같은 경작지의 가장자리에다 기둥(66)과 고정앵글(68)의 설치되면서 강풍유도용으로 구축되도록 좌우 길이방향이면서 이격간격(라) 유지로 설치되는 복수의 태양광발전장치(80)과, 상기 태양광발전장치(80)에는 경사지게 설치된 태양광발전판(83)와,상기 태양광발전판(83)을 형성하는 발전소자인 모듈(86)의 하측에 연결빔(92)이 연장으로 확대된 구간에 형성되는 연결수단(69)이 구비되면서 이격간격(라) 구간을 연결함으로서, 강풍유도하도록 강풍유도판(91)의 가장자리에 구비된 연결용 조립구(77)와, 상기 태양광발전판(83)의 하측단에서 연결로 강풍유도시켜서 이격간격(라)으로 더 확대하여 주는 제2강풍유도판(191)과, 상기 제2강풍유도판(191)의 양측에 돌출로 이격간격(라)을 연결하는 조립구(77)와, 상기 연결수단(69)과 조립구(77)를 조립으로 걸어줌으로서, 태양광발전판(83)의 하측단에 개구된 통과공간(가)과 이격간격(라)을 카버로서 농지(70)로 유입되는 강풍을 공중으로 유도시켜 주도록 제공되는 발명이다. claims: 농지(70), 비닐하우스로 형성된 원예단지(65)와 같은 경작지역(71)의 가장자리에다, 기후변화와 계절의 변화에 따른 경작지의 폭염, 냉해피해를 감소시켜 주면서 신재생에너지 발전을 증대시켜 주도록, 기둥(66)과 고정앵글(68)의 설치로서 저측에 경작지역(71)인 하측공간이 구비되면서 상측에 강풍유도용으로 경사지게 구축되는 태양광발전판(83)이, 좌우 길이방향이면서 이격간격(라) 유지하면서 기둥(66)과 빔(67)으로 경작지역(71)이 조성되는 복수의 태양광발전판(83)이 각각 경사지게 설치된 고정앵글(68)에 조립되는 태양광발전판에 있어서, 상기 태양광발전판(83)의 상측단에서 고정앵글(68)의 연장으로 설치되는 태양광 유입구(87)과, 상기 유입구(87)을 태양광발전판(83)의 배면공간인 경작지역(71)에 반사로 유도시켜 주기 위하여, 태양광반사공간(90)이 형성되도록 만곡으로 조립된 반사대(110)와, 상기 반사대(110)에서 반사로 굴절되는 태양광 반사공간(90)에다, 태양광발전판(83)의 저면에 공정으로 돌출되는 맞추어서, 태양광굴절용 복수의 보조반사대(111)을 태양광발전판(83)의 저측면에 고정시켜 주어서, 태양광이 경작지역(71)에 비춰주고, 상기 복수의 보조반사대(111)에서 태양광발전판(83)의 저면에 가열공간(107)과 통과구(106)의 관통으로, 폭염기간에 경작지역(71)의 고온을 태양광유입공간(90)으로 엮류로 환기시켜 주도록 제공되는 영농지에 구축되는 태양광, 강풍유도용 태양광발전판., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

959/1150 Row 959: application_number: 2020200003252, combined_string: invention_title: 딸기재배용 국소 냉온패드 abstract: 본 고안은 딸기 재배시 물공급을 필요로 하는 모종단계와 생육단계에 계절별로 공급되는 급수온도를 맞추어서 균일한 지열을 제공함으로써 고품질의 딸기를 수확하고, 다분화가 가능하도록 하여 수확시기를 늘려서 수익성을 우수하게 향상시킬 수 있는 딸기재배용 국소 냉온패드에 관한 것이다.본 고안은 냉수 또는 온수가 공급되는 공급호스부 몸체(10,11)가 형성되고, 상기 공급호스부 몸체(10,11)의 중간부분에 배출호스부(12)가 형성되며, 상기 배출호스부(12)와 공급호스부 몸체(10,11)가 융착되어 융착부(14)가 형성되며 다수의 핀공이 형성된 지열호스부(102)와: 상기 융착부(14)에 안착되어 고정되고, 작물에 관수를 공급하기 위한 다수의 노즐공(32)을 구비한 점적호스부(104)와; 상기 융착부에 안착된 점적호스부(104)가 흔들리거나 이탈되지 않도록 고정하는 고정부재(106)를 포함하는 것을 특징으로 한다.이와 같은, 본 고안의 딸기재배용 국소 냉온패드는, 여름이나 겨울 등 계절에 맞게 관수온도를 공급함으로써 딸기의 기형을 방지하고 상품성을 우수하게 향상시킬 수 있는 효과가 있고, 필요한 시기에 관수를 제공하여 적어도 2회 이상의 다분화가 가능함으로써 수확시기를 늘려서 생산성이 크게 향상되는 효과가 있다. claims: 냉수 또는 온수가 공급되는 공급호스부 몸체(10,11)가 형성되고, 상기 공급호스부 몸체(10,11)의 중간부분에 배출호스부(12)가 형성되며, 상기 배출호스부(12)와 공급호스부 몸체(10,11)가 융착되어 융착부(14)가 형성되며 다수의 핀공이 형성된 지열호스부(102)와: 상기 융착부(14)에 안착되어 고정되고, 작물에 관수를 공급하기 위한 다수의 노즐공(32)을 구비한 점적호스부(104)로 이루어지는 딸기재배용 냉온패드에 있어서,상기 융착부(14)에 안착된 점적호스부(104)가 흔들리거나 이탈되지 않도록 고정하는 고정부재(106)를 포함하되,상기 고정부재(106)는, 디귿자(ㄷ)형상 또는 스테플러의 형상으로 이루어져 있고, 상기 점적호스부(104)를 감싸면서 지반에 고정되도록 형성되고,상기 지열호스부(102)는,상기 공급호스부 몸체(10,11)와 배출호스부(12)가 형성되고, 일끝단부가 공급호스부 몸체(10,11)와 배출호스부(12)가 연결되어 관수가 순환되도록 형성되고, 공급호스부 몸체(10,11)로 공급된 관수가 순환하여 상기 배출호스부(12)를 설치하는 것을 포함하되,상기 공급호스부 몸체(10,11)의 끝단부에는 공급되는 관수가 순환되도록 배출호스부(12)와 각각 연결되어 연결배관부(18,20)가 형성되고, 상기 공급호스부 몸체(10,11)의 전단부에는 관수가 공급되는 연결밸브(108)가 설치되어공급된 관수의 온도와 배출시 관수의 온도의 합이 지열호스부(102)의 전단부와 후단부에 이르기까지 호스 전체에 걸쳐서 동일하게 유지되는 것을 특징으로 하는 딸기재배용 국소 냉온패드., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

960/1150 Row 960: application_number: 1020200091622, combined_string: invention_title: 과수 포장지 abstract: 본 발명은 과수의 열매(과실)을 외부 환경, 농약, 해충, 물리적 접촉 등으로부터 보호하고 성장 및 숙지를 돕기 위해 과실에 씌우는 과실 봉지를 위한 과수 포장지에 관한 것으로서, 펄프 및 에폭시 수지를 포함하는 기재: 및 상기 기재에 코팅된 코팅층을 포함하되, 상기 코팅층은 바인더 및 발수제를 포함하는 것이고, 상기 코팅층은 기재의 양쪽 표면 및 내부에 형성되어 있는 것이다. 본 발명의 과수 포장지는 함침 코팅으로 기재 전체 면적에 형성된 코팅층에 의해 내구성이 향상되어 과실 재배 과정에서 비용 절감이 가능하고, 포름알데히드 성분 잔류 위험성이 제거되어 기존의 과실 봉지를 대체할 수 있을 것으로 기대된다. claims: 펄프 및 에폭시 수지를 포함하는 기재, 및상기 기재에 코팅된 코팅층 포함하는 과수 포장지로서,상기 기재에서 펄프와 에폭시 수지는 99.9:0.1 내지 95.0:5.0의 중량비로 혼합되어 있는 것이며,상기 에폭시 수지는 120℃ 내지 180℃에서 열가교에 의해 펄프와 가교 결합된 것이고,상기 코팅층은 바인더 및 발수제로 이루어진 것이고, 발수제 함량이 바인더 100 중량부에 대하여 0.5 내지 8 중량부이며, 기재에 대해 1.0 g/㎡ 내지 7.0 g/㎡의 양으로 기재의 양쪽 표면 및 내부 기공의 표면에 형성되어 있는 것인과수 포장지., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

961/1150 Row 961: application_number: 1020200083394, combined_string: invention_title: 고설베드 재배 장치 abstract: 본 발명은 고설베드 재배 장치에 관한 것으로, 작물의 재배를 위해 뿌리를 심을 수 있도록 소정의 토양이 수용되는 베드본체와, 상기 베드본체를 지면에서 소정의 높이에 위치시키는 다리를 포함하는 고설베드와; 상기 다리의 바깥쪽에 구비되어 소정의 중량을 갖는 과실을 베드본체로부터 재배위치를 분리하는 과실받침대와; 상기 다리에서 상기 베드본체의 상부 방향으로 연장되어 작물의 재배에 따라 상기 베드본체에서 성장하는 줄기가 지탱하여 위로 뻗어 타고 올라갈 수 있도록 지지하는 줄기유인대를 포함하는 구성으로 충분한 광합성을 통해 과실의 품질 및 생산성이 향상될 수 있는 고설베드 재배 장치에 관한 것이다. claims: 작물의 재배를 위해 뿌리를 심을 수 있는 소정의 토양이 수용되는 베드본체(110)와, 상기 베드본체(110)를 지면에서 소정의 높이에 위치시키는 다리(120)를 포함하여 고설베드(100)로 이루어진 고설베드 재배 장치에 있어서,상기 고설베드 재배 장치는,소정의 중량을 갖는 과실을 베드본체(110)로부터 위치를 분리하여 재배할 수 있도록 상기 다리(120)의 바깥쪽에 착탈 가능하게 구비되는 과실받침대(200)와;상기 다리(120)에서 상기 베드본체(110)의 상부 방향으로 연장되어 작물의 재배 시 줄기를 유인할 수 있도록 상기 다리(120)의 바깥쪽에 착탈 가능하게 구비되는 줄기유인대(300)를 포함하고,상기 과실받침대(200)는 접이식으로 구성되며,상기 베드본체(110)의 수평 길이와 동일한 길이로 과실을 받치는 받침프레임(210)과;상기 받침프레임(210)의 하부를 일체로 지지하며, 상기 베드본체(110)의 다리(120) 상측에 회전 가능하게 구비되는 회전프레임(220)과;상기 다리(120) 하측에 회전 가능하게 구비되어 과실을 받칠 수 있도록 상기 받침프레임(210)을 포함한 회전프레임(220)의 수평 위치 시 회전프레임(220)을 지지하는 받침지지대(230)를 포함하며,상기 받침프레임(210)은 두 개의 파이프로 이루어지고, 과실의 크기에 따라 두 파이프의 간격을 조절할 수 있으며, 상기 받침프레임의 길이를 연장하기 위해 상기 파이프를 서로 연결하는 연결구(211)를 구비하고,상기 줄기유인대(300)는,상기 다리(120)와 평행하게 구비되며, 상기 베드본체(110)의 상부까지 소정의 길이를 갖는 메인포스트(310)와;상기 메인포스트(310)에 출몰 가능하게 구비되며, 상기 메인포스트(310)에서 상단으로 길이 방향을 따라 더 연장되는 보조포스트(320)를 포함하며,상기 메인포스트(310)로부터 보조포스트(320)가 주행하여 선택된 높이에서 메인포스트(310)에 구비된 조절노브(340)를 조여 보조포스트(320)의 높이를 조절가능한 것을 특징을 하는 고설베드 재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

962/1150 Row 962: application_number: 2020200001553, combined_string: invention_title: 육묘 포트용 상토 평탄기 abstract: 본 고안은 딸기와 같이 고설 액비 재배를 하는 농작물의 포트내부에 상토를 채움에 있어 신속함은 물론, 포트 외부로 유실되는 상토를 최소화할 수 있는 육묘 포트용 상토 평탄기에 관한 것으로,내부에 상토가 충진되면서 포트(10)의 내부에 상토가 채워질 수 있도록 상, 하면에 개방되며, 4개 면이 플레이트로 일체화된 다각형 형상의 틀(20)이 구비되며, 상기 틀(20)의 상측 끝단부는 틀의 강성유지와 손잡이의 기능을 수행할 수 있도록 적어도 2개소 이상 굽힘가공 처리에 의해 홀더(21)가 형성되고, 진행 방향으로 좌, 우측 플레이트(22,23)의 하단에는 상기 틀(20)이 포트(10)의 상부에서 유동거림 및 이탈을 방지할 수 있도록 리미트 플레이트(24,25)가 형성되고, 상기 좌, 우측 플레이트(22,23)의 하측 내면에는 상기 틀(20)이 포트(10)의 상단면에 안착된 상태에서 프트(10)의 상단을 슬라이딩 할 수 있도록 안착편(26, 27)이 각각 형성되는 한편, 상기 틀(20)의 전, 후면 플레이트(28,29) 하측 끝단부는 진행방향으로 돌출부위가 있는 경우에도 안정적으로 진행이 될 수 있도록 상측 방향으로 1 내지 10°굽힘 가공처리된 가이드플레이트(30,31)가 형성된다. claims: 내부에 상토가 충진되면서 포트(10)의 내부에 상토가 채워질 수 있도록 상, 하면에 개방되며, 4개 면이 플레이트로 일체화된 다각형 형상의 틀(20)이 구비되며, 상기 틀(20)의 상측 끝단부는 틀의 강성유지와 손잡이의 기능을 수행할 수 있도록 적어도 2개소 이상 굽힘가공 처리에 의해 홀더(21)가 형성되고, 진행 방향으로 좌, 우측 플레이트(22,23)의 하단에는 상기 틀(20)이 포트(10)의 상부에서 유동거림 및 이탈을 방지할 수 있도록 리미트 플레이트(24,25)가 형성되고, 상기 좌, 우측 플레이트(22,23)의 하측 내면에는 상기 틀(20)이 포트(10)의 상단면에 안착된 상태에서 포트(10)의 상단을 슬라이딩 할 수 있도록 안착편(26, 27)이 각각 형성되는 한편,상기 틀(20)의 전, 후면 플레이트(28,29) 하측 끝단부는 진행방향으로 돌출부위가 있는 경우에도 안정적으로 진행이 될 수 있도록 상측 방향으로 1 내지 10°굽힘 가공처리된 가이드플레이트(30,31)가 형성되는 것을 특징으로 하는 육묘 포트용 상토 평탄기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

963/1150 Row 963: application_number: 1020200054292, combined_string: invention_title: 포도 화수 정형기 abstract: 본 발명은 포도 재배시 화수의 정형을 신속하고 간편하게 수행할 수 있도록 한 포도 화수 정형기에 관한 것이다.본 발명의 포도 화수 정형기는 이격된 상태로 마주하는 한 쌍의 집게부(110a,110b)와 상기 집게부를 일체로 연결하면서 탄성이격력을 부여하는 탄성손잡이부(120)를 가진 핀셋 형태의 몸체(100)와, 상기 집게부를 합치시킬 경우 원형을 이루면서 포도의 화수 줄기(A)를 감싸도록 각 집게부에 형성된 반구형의 커팅홈(130a,130b)과, 화수 줄기의 손상이 방지되도록 상기 커팅홈의 상단과 하단을 따라 외측을 향해 하향 경사지게 형성된 하는 커팅날(140)과, 재배할 화수(B)의 길이를 측정할 수 있도록 상기 일측의 집게부의 외측면에 형성된 길이측정용 눈금(150)을 포함한다. claims: 이격된 상태로 마주하는 한 쌍의 집게부와, 상기 한 쌍의 집게부를 일체로 연결하면서 탄성이격력을 부여하는 탄성손잡이부를 가진 핀셋 형태의 몸체;상기 한 쌍의 집게부를 합치시킬 경우, 원형을 이루면서 포도의 화수 줄기를 감싸도록 각 집게부에 형성된 반구형의 커팅홈;화수 줄기의 손상이 방지되도록 상기 커팅홈의 상단과 하단을 따라 외측을 향해 하향 경사지게 형성된 커팅날; 및재배할 화수의 길이를 측정할 수 있도록 상기 한 쌍의 집게부 중 일측의 집게부의 외측면에 형성된 길이측정용 눈금;을 포함하되,상기 일측의 집게부의 내측면에는 일정간격을 두고 홈부가 형성되고,상기 일측의 집게부를 따라 전후방향으로 슬라이딩 이동가능하면서 상기 길이측정용 눈금의 위치를 알려주는 지시부재가 상기 일측의 집게부의 상부에 끼워져 결합되며,상기 지시부재는 엄지손가락을 올려 놓을 수 있는 안착부가 형성된 전면부와, 상기 홈부에 끼워지는 위치고정용 돌기가 형성된 후면부와, 상기 전면부와 후면부의 상단을 연결하며 상기 일측의 집게부의 상단에 지지되는 연결부를 구비한포도 화수 정형기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

964/1150 Row 964: application_number: 1020200052437, combined_string: invention_title: 베타글루칸 성분을 증진시키는 배 재배방법 abstract: 본 발명은 배와 영지, 운지, 상황 버섯, 강황, 와송, 귀리를 특정 조건으로 숙성 및 발효시켜 제조한 조성물을 배나무에 살포하여 배의 베타글루칸 성분을 증진시키는 배 재배방법에 관한 것으로, 더욱 상세하게는 (a) 배 126kg를 3개월 동안 용기 내에서 숙성시키는 제 1차 숙성 단계, (b) 상기 제 1차 숙성 단계에서 숙성된 숙성물의 여과액을 1년 동안 용기 내에서 발효시키는 단계, (c) 상기 발효된 발효물에 각각 영지, 운지, 상황 버섯과 강황, 와송, 귀리를 첨가하여 용기 내에서 5개월 동안 숙성시키는 제 2차 숙성 단계, (d) 상기 제 2차 숙성 단계에서 숙성된 숙성물을 각각 여과하는 단계, (e) 상기 여과된 영지, 운지, 상황 버섯이 포함된 조성물 250ml와 강황, 와송, 귀리가 포함된 조성물 250ml를 물 500L에 혼합하는 단계 및 (f) 상기 혼합된 조성물을 배나무 과수원 1652m2 면적에 살포하는 단계를 포함하는 배 재배방법을 제공한다. claims: 베타글루칸 성분을 증진시키는 배 재배방법에 있어서,(a) 배 126kg를 3개월 동안 용기 내에서 숙성시키는 제 1차 숙성 단계;(b) 상기 제 1차 숙성 단계에서 숙성된 숙성물의 여과액을 1년 동안 용기 내에서 발효시키는 단계;(c) 상기 발효된 발효물에 각각 영지, 운지, 상황 버섯과 강황, 와송, 귀리를 첨가하여 용기 내에서 5개월 동안 숙성시키는 제 2차 숙성 단계;(d) 상기 제 2차 숙성 단계에서 숙성된 숙성물을 각각 여과하는 단계;(e) 상기 여과된 영지, 운지, 상황 버섯이 포함된 조성물 250ml와 강황, 와송, 귀리가 포함된 조성물 250ml를 물 500L에 혼합하는 단계; 및(f) 상기 혼합된 조성물을 배나무 과수원 1652m2 면적에 살포하는 단계;를 포함하는 것을 특징으로 하는 베타글루칸 성분을 증진시키는 배 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

965/1150 Row 965: application_number: 1020200033211, combined_string: invention_title: 혼합 배양균을 이용한 농작물 친환경 재배 방법 abstract: 본 발명은 셀레늄을 이용한 농작물의 재배방법과 관련된다. 구조적 특징에 있어서, 셀레늄(Selenium)과 님 케이크 (NEEM-CAKE :분말)을 1 : 1 혼합하여 토양에 1차 시비하는 단계와 ; 상기 1차 시비된 토양에 야채류 또는 과실류를 파 종 또는 모종하는 단계와 ; 셀레늄(Selenium)과 님오일(NEEM-OIL)을 1 : 1혼합한 혼합물과 물을 1 : 500의 비율로 희석 하는 단계와 ; 상기 희석액을 토양에 1차 엽면시비하는 단계와 ; 1차 엽면시 후5내지 6일간격으로 3 내지 4회 엽면시비하 여 병충해 방지 및 성장촉진시키는 셀레늄 및 님(NEEM)성분을 이용한 유기농작물의 친환경 재배방법을 특징으로 한다.셀레늄과 님오일(NEEMOIL) 혼합액과 죽초액을 10 : 1 ~ 2의 비율로 혼합하여 6일 간격으로 2 내지 3회 엽면시비하여 병 충해를 방제 및 성장을 촉진하는 셀레늄 및 님오일을 이용한 유기농작물의 친환경 재배방법을 특징으로 한다.이에 따라 본 발명은, 셀레늄과 님오일(NEEM-OIL) 혼합물을 물과 희석하여 미나리, 토마토, 쑥갓 등의 채소류와 배, 포 도, 딸기 등의 과실류에 엽면 시비하여 셀레늄의 함유량을 높이고, 농약의 살포없이 유기농산물로 재배하여 세척없이도 먹 을 수 있도록 하여 상품성을 높일 뿐 아니라, 세척과정에서 물에 녹는 셀레늄의 소실을 방지함은 물론, 채소 및 과일의 생 장기간을 크게 단축시켜 출하시기를 앞당겨 상품성을 높일 수 있다. claims: 셀레늄을 이용한 농작물의 재배방법에 있어서 :셀레늄(Selenium)과 님 케이크(NEEM-CAKE :분말)을 1 : 1 혼합하여 토양에 1차 시비하는 단계와 ;상기 1차 시비된 토양에 야채류 또는 과실류를 파종 또는 모종하는 단계와 ;셀레늄(Selenium)과 님오일(NEEMOIL)을 1 : 1혼합한 혼합물과 물을 1 : 500의 비율로 희석하는 단계와 ;상기 희석액을 토양에 1차 엽면시비하는 단계와 ;1차 엽면시 후5내지 6일간격으로 3 내지 4회 엽면시비하여 병충해 방지 및 성장촉진시킴을 특징으로 하는 셀레늄 및 님오 일을 이용한 유기농작물의 친환경 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

966/1150 Row 966: application_number: 1020200029841, combined_string: invention_title: 과수재배용 공기 교반기 abstract: 본 발명은 과수재배용 공기 교반기로서, 이를 보다 상세히 설명하면 작물의 주위에 존재하는 공기를 상하 방향으로 원활하게 교반시켜주므로서 작물의 성장촉진과 개화기(開花期)에 꽃망울의 동해(凍害) 예방 효과를 부여할 수 있도록 한 것으로서, 상기 본 발명은 구체적인 수단으로 교반기 통체(10) 내에 모터 (11)에 구동되는 송풍기(12)가 설치되고, 송풍기(12)의 전방으로 삿갓형의 공기 융기부(14)가 형성된 교반통(13)을 고정지지간(17)에 고정되도록 설치한 구성에 있어서, 교반통(13)의 공기 융기부(14) 측면에 수개의 좌우 높낮이가 상이한 경사유도판(16)을 고정착설하여 송풍공기에 대해 와류운동을 일으키도록 형성하고, 상기 교반통(13)의 상부에는 보조덮개(17)를 설치하여 교반통(13)의 요입실(15)과 교반기 통체(100) 내부에 우수가 유입되지 않도록 구성함을 특징으로 하며, 이러한 본 발명에 의해 종래의 직송교반식 공기 교반장치에 비하여 공기의 순환효과와 교반효과가 크게 향상되는 등 다수의 효과를 기대할 수 있는 발명이다. claims: 교반기 통체(10) 내에 모터(11)에 의해서 구동되는 송풍기(12)를 설치하고,송풍기(12)의 전방으로 삿갓형의 공기 융기부(14)가 형성된 교반통(13)을 고정지지간(17)에 고정되도록 설치하며,교반통(13)의 공기 융기부(14) 측면에 수개의 좌우 높낮이가 상이한 경사유도판(16)을 고정착설하여 송풍공기에 대해 와류운동을 일으키도록 형성하고,상기 교반통(13)의 상부에는 보조덮개(17)를 설치하여 교반통(13)의 내부에 우수가 유입되지 않도록 구성함을 특징으로 하는 과수재배용 공기 교반기.교반기 통체(10) 내에 모터(11)에 의해서 구동되는 송풍기(12)를 설치하고,송풍기(12)의 전방으로 삿갓형의 공기 융기부(14)가 형성된 교반통(13)을 고정지지간(17)에 고정되도록 설치하며,교반통(13)의 공기 융기부(14) 측면에 수개의 좌우 높낮이가 동일한 4각형으로 이루어진 4각유도판(16a)을 고정착설하여 송풍공기를 일정하게 확산운동을 일으키도록 형성하고,상기 교반통(13)의 상부에는 보조덮개(17)를 설치하여 교반통(13)의 내부에 우수가 유입되지 않도록 구성함을 특징으로 하는 과수재배용 공기 교반기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

967/1150 Row 967: application_number: 1020200029860, combined_string: invention_title: 신품종 배 및 이의 육종 방법 abstract: 본 발명은 신품종 배 및 이의 육종 방법에 관한 것으로, 모계 품종인 돌배와 부계 품종인 배를 교배시켜 얻어진 본 발명에 따라 육종된 신품종 배는 돌배의 약효인 감기ㅇ해소ㅇ천식 예방 효과 및 소화기능 개선효과를 가지면서도 신맛은 감소되고 단맛이 증대되고 과육이 말랑말랑하여 기호도를 높일 수 있다. 또한, 본 발명의 신품종 배는 3일 내지 6일 동안 후숙시키면 과육이 더욱 말랑말랑해져서 치아가 약학 노약자도 섭취가 가능하며, 과육 크기가 돌배보다 작아서 식이가 용이하여 학교 급식이나 병원식으로도 유용하게 사용될 수 있을 것으로 기대된다. claims: 기탁번호 KCTC14147BP 또는 KCTC14148BP의 신품종 배로서,모계 품종인 돌배와 부계 품종인 배를 교배시켜 얻어지고, 배 껍질이 황색 또는 적색을 띠며, 신맛은 감소되고 단맛은 증대되고, 당도는 10 내지 14˚Bx이고, 산도는 0.03 내지 0.05%이며, 과육이 말랑말랑한 특성을 가지는 신품종 배.제 1 항에 있어서,하기 특성을 가지는 것을 특징으로 하는 신품종 배:(1) 과형이 둥근 원형으로, 모계 품종인 돌배와 크기가 비슷하거나 조금 큼.(2) 과육 껍질은 황색, 적색 또는 부분적으로 황색 및 적색으로 착색되며, 흰색 내지 황색 점이 껍질 전면에 있음.(3) 잎은 달걀모양 타원형이고, 끝은 뾰족하며, 밑은 둥글거나 심장밑 모양이고, 잎 뒷면은 녹색이며 털이 없고 가장자리에 침 같은 톱니가 있음.(4) 꽃은 4∼5월에 백색으로 핌.(5) 과육의 색은 백색임.(6) 과육은 처음에는 모계 품종과 유사하나 상온에서 1주일정도 경과시 갈변하며 모계 품종 및 부계 품종에 비하여 말랑말랑하며, 갈변시 과즙이 많아지고 표피가 얇아지며 당도가 더 높아져 10 내지 14˚Bx이고, 산도는 0.03 내지 0.05% 임.기탁번호 KCTC14147BP 또는 KCTC14148BP의 신품종 배의 육종방법으로서, 하기 단계를 포함하는 것을 특징으로 하는 신품종 배의 육종방법:(S1) 모계 품종인 돌배 품종을 파종하는 단계; (S2) 부계 품종인 배 품종을 파종하는 단계; (S3) 상기 부계 품종인 배 품종의 착과시기에 열매가 열린 가지를 잘라서 부계 품종인 돌배 품종에 인위적으로 교배시키는 단계;(S4) 교배된 개체의 과실에서 종자를 채종하는 단계; (S5) 상기 채종된 종자를 파종하여 배를 재배하는 단계; 및(S6) 상기 재배한 배 중에서 배 껍질이 황색 또는 적색으로 착색되고, 당도는 10 내지 14˚Bx이고, 산도는 0.03 내지 0.05%이며, 과육이 말랑말랑한 특성을 가지는 신품종 배를 육종하는 단계.제 3 항에 있어서,상기 단계 (S3)에서 부계 품종인 배 품종에 열린 배 중 모계 품종인 돌배의 크기보다 작은 열매가 열린 가지를 잘라서 부계 품종인 돌배 품종에 인위적으로 교배시키는 것을 특징으로 하는 신품종 배의 육종방법.제 3 항에 있어서,상기 신품종 배가 하기 특성을 가지는 것을 특징으로 하는 신품종 배의 육종방법.(1) 과형이 둥근 원형으로, 모계 품종인 돌배와 크기가 비슷하거나 조금 큼.(2) 과육 껍질은 황색 또는 적색으로 착색되며, 흰색 내지 황색 점이 껍질 전면에 있음.(3) 잎은 달걀모양 타원형이고, 끝은 뾰족하며, 밑은 둥글거나 심장밑 모양이고, 잎 뒷면은 녹색이며 털이 없고 가장자리에 침 같은 톱니가 있음.(4) 꽃은 4∼5월에 백색으로 핌.(5) 과육의 색은 백색임.(6) 과육은 처음에는 모계 품종과 유사하나 상온에서 1주일정도 경과시 갈변하며 모계 품종 및 부계 품종에 비하여 말랑말랑하며, 갈변시 과즙이 많아지고 표피가 얇아지며 당도가 더 높아짐., Ltext: 농업, prediction: '임업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

968/1150 Row 968: application_number: 1020200021097, combined_string: invention_title: IBA를 이용한 딸기 모주의 측아 발생 억제 및 자묘 생육 증진 방법 abstract: 본 발명은 시설 딸기 육묘시 30~120 mg·L-1의 IBA(indole-3-butyric acid)를 배지관주로 처리하여 딸기 모주의 측아 발생 억제 및 자묘 생육을 향상시키는 방법에 관한 것으로, 본 발명의 방법은 딸기 묘의 생산성 향상에 기여할 수 있을 것이다. claims: 딸기 모주에 IBA(indole-3-butyric acid)를 처리하여 육묘시키는 단계를 포함하는, 딸기 모주의 측아 발생 억제 및 자묘의 생육 증진 방법.30~120 mg·L-1의 IBA(indole-3-butyric acid)를 유효성분으로 함유하는, 시설재배 시 딸기 모주의 측아 발생 억제 및 자묘 생육 증진용 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

969/1150 Row 969: application_number: 1020200016022, combined_string: invention_title: 셀레늄 함유 딸기 재배 방법 및 이를 통해 재배된 딸기를 포함하는 가공식품 abstract: 본 발명은 셀레늄 함유 딸기 재배 방법 및 이를 통해 재배된 딸기를 포함하는 가공식품에 관한 것으로, 상세하게는 EDTA, 수산화물, 산화셀레늄, 및 ATCA를 포함하여 제조된 유기셀레늄 용액을 포함하는 딸기 재배 영양제를 이용한 셀레늄 함유 딸기 재배 방법과 이러한 방법을 통해 재배된 딸기를 이용한 가공식품에 관한 것이다.본 발명은 셀레늄 함유 딸기 재배 방법 및 이를 통해 재배된 딸기를 포함하는 가공식품을 제공함으로써 셀레늄의 함량이 높은 딸기를 재배할 수 있고 딸기 내 항산화, 폴리페놀, 플라보노이드와 같은 생리활성물질이 증가하는 효과를 나타낼 수 있다. 나아가 생리활성물질 및 셀레늄의 함량이 우수한 딸기를 이용하여 다양한 종류의 바이오헬스 식품을 개발할 수 있으며, 이를 쉽게 접할 수 있는 가공식품으로서의 개발이 가능한 효과가 있다. claims: 에틸렌디아민테트라아세트산(ethylendiaminetetracetic acid, EDTA), 수산화물(hydroxide), 산화셀레늄(Selenium oxide, SeO2) 및 아세틸티오프롤린(acetylthioproline, ATCA)를 포함하는 유기셀레늄 용액을 이용하여 딸기 재배 영양제를 형성하는 제 1 단계;상기 딸기 재배 영양제의 시비량 또는 시비횟수를 설정하는 제 2 단계; 및상기 시비량 또는 시비횟수가 설정된 딸기 재배 영양제를 딸기에 시비하는 제 3 단계;를 포함하는 것을 특징으로 하는 셀레늄 함유 딸기 재배 방법.제 1 항에 따른 방법으로 제배된 딸기를 포함하는 것을 특징으로 하는 가공식품., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

970/1150 Row 970: application_number: 1020200015783, combined_string: invention_title: 매실 및 애호박 혼합 발효물을 이용한 기능성이 향상된 애호박의 재배방법 abstract: 본 발명은 (1) 매실 열매와 매실나무 가지를 혼합한 매실 혼합물에 설탕을 혼합한 후 발효하여 매실 발효물을 제조하는 단계; (2) 애호박 순과 애호박 가지를 혼합한 애호박 부산물에 설탕을 혼합한 후 발효하여 애호박 발효물을 제조하는 단계; (3) 상기 (1)단계의 제조한 매실 발효물과 상기 (2)단계의 제조한 애호박 발효물을 혼합한 후 가열한 영양액에 물을 첨가하여 영양 희석액을 제조하는 단계; 및 (4) 애호박 유묘를 식재하고, 상기 (3)단계의 제조한 영양 희석액을 관주 및 엽면처리하는 단계를 포함하는 애호박의 재배방법 및 상기 방법으로 재배된 애호박에 관한 것이다. claims: (1) 매실 열매와 매실나무 가지를 혼합한 매실 혼합물에 설탕을 혼합한 후 발효하여 매실 발효물을 제조하는 단계;(2) 애호박 순과 애호박 가지를 혼합한 애호박 부산물에 설탕을 혼합한 후 발효하여 애호박 발효물을 제조하는 단계;(3) 상기 (1)단계의 제조한 매실 발효물과 상기 (2)단계의 제조한 애호박 발효물을 혼합한 후 가열한 영양액에 물을 첨가하여 영양 희석액을 제조하는 단계; 및(4) 애호박 유묘를 식재하고, 상기 (3)단계의 제조한 영양 희석액을 관주 및 엽면처리하는 단계를 포함하는 애호박의 재배방법.제1항 내지 제3항 중 어느 한 항의 방법으로 재배된 애호박., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

971/1150 Row 971: application_number: 1020200003383, combined_string: invention_title: 과일봉지 abstract: 본 발명은 과일봉지에 관한 것으로서, 보다 상세하게는 사과, 배, 복숭아, 포도, 석류 등의 과수 재배 시 과일 봉지 작업 효율을 증대시킬 수 있는 봉지 결속 기술에 관한 것이다.본 발명에 따른 과일봉지는 종이를 포함한 연질의 재질로 이루어져 과수에 매달린 과일을 덮어 씌우도록 상단에 개구부가 형성되고, 상기 개구부는 상기 과일봉지의 상단 일측이 사선형의 개방구조로 형성되며, 상기 개방구조에는 3 내지 10mm 폭으로 폴리에틸렌코팅부가 형성되고, 상기 폴리에틸렌코팅부는 가열되면서 융착되어 상기 개구부가 접합되는 것을 특징으로 한다. claims: 과수에 달려 있는 과일(F)을 보호하는 과일봉지(100)에 있어서,종이를 포함한 연질의 재질로 이루어져 과수에 매달린 과일(F)을 덮어 씌우도록 상단에 개구부(110)가 형성되고,상기 개구부(110)는 상기 과일봉지(100)의 상단 일측이 사선형의 개방구조로 형성되며,상기 개방구조에는 3 내지 10mm 폭(W)으로 폴리에틸렌코팅부(120)가 형성되고, 상기 폴리에틸렌코팅부(120)는 가열되면서 융착되어 상기 개구부(110)가 접합되는 것을 특징으로 하는 과일봉지., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

972/1150 Row 972: application_number: 1020200002315, combined_string: invention_title: 플라스틱 복층판 abstract: 본 발명은 플라스틱 복층판에 관한 것으로, 보다 상세하게는 유리창 또는 온실 벽체의 단열성 즉, 복사열과 전도열을 필요에 따라 능동적으로 변화시켜 사계절 내내 실내 냉·난방, 조명 에너지 소비를 최소화하고, 특히 그동안 어려웠던 여름철 고온기 딸기 재배 등도 가능하게 하며, 저온기에도 난방비를 최소화하여 제로에너지에 가까운 온실 구현을 위한 온실 외피시스템, 혹은 그러한 에너지 절감형 건물 외피시스템을 구현할 수 있도록 개선된 플라스틱 복층판에 관한 것이다. claims: 태양광에 직접 노출되는 상판(1), 상기 상판(1)과 간격을 두고 평행하게 배치되는 하판(2) 및 상기 상판(1)과 하판(2)을 연결 고정하도록 수직하게 배치 고정되는 수직격판(3)으로 이루어지고, 상기 수직격판(3)에 의해 상기 상판(1)과 하판(2) 사이의 공간은 다수개의 수로(4)로 형성되며, 상기 수로(4)에는 유체가 순환되도록 구성된 플라스틱 복층판에 있어서;상기 유체는 물, 부동수 또는 차광수이며;상기 부동수는 물에 소금 또는 에틸렌글리콜을 7:3의 부피비로 혼합한 것이고;상기 차광수는 물에 적외선흡수액을 0.2부피%로 혼합하되, 적외선흡수액은 검은색 카본블랙, 먹물, 커피액, 염료 혹은 TiO2, ATO 또는 CTO가 분산되어 있는 안료액 중 어느 하나인 것을 특징으로 하는 플라스틱 복층판., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

973/1150 Row 973: application_number: 1020190173950, combined_string: invention_title: 딸기 전동관리기 전용 멀칭기 abstract: 본 발명은 자동화 농업기계가 없거나, 적절한 형태로 개발되지 않았기 때문에 전적으로 인력에 의하여 작물을 재배하는 고설 재배를 생력화 및 자동화하는 기술을 제공하고자하는 것이다.특히, 재배 초기에는 고설 재배 시설을 설치하는 등의 작업이 많아 일손이 매우 부족하다. 이시기에 사용할 수 있는 고설 재배 전용 관리기에 부착하여 사용할 수 있는 멀칭기를 제공하고자 한다.이를 위하여 전방에 상기 딸기 전동관리기 결합부가 구비된 고정프레임; 및상기 고정프레임의 후단에 구비된 한 쌍의 이동바퀴; 및상기 고정프레임의 중단에 수평으로 구비되어 멀칭필름을 거치하는 멀칭필름 거치부; 및상기 고정프레임의 중단 하부에 구비되어 상기 멀칭필름을 고설 재배 장치에 결합하는 멀칭필름 고정부를 구비하는 것을 특징으로 하는 딸기 전동관리기 전용 멀칭기를 제공한다.상기와 같은 수단에 의하여 고설 재배 시설에서도 사용 가능한 가볍고 성능이 우수한 멀칭 비닐을 설치하는 멀칭기를 제공함으로써, 노동력을 절감할 수 있는 효과가 있다. claims: 딸기 전동관리기 전용 멀칭기에 있어서,전방에 상기 딸기 전동관리기 결합부가 구비된 고정프레임; 및상기 고정프레임의 후단에 구비된 한 쌍의 이동바퀴; 및상기 고정프레임의 중단에 수평으로 구비되어 멀칭필름을 거치하는 멀칭필름 거치부; 및상기 고정프레임의 중단 하부에 구비되어 상기 멀칭필름을 고설 재배 장치에 결합하는 멀칭필름 고정부를 구비하는 것을 특징으로 하는 딸기 전동관리기 전용 멀칭기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

974/1150 Row 974: application_number: 2020190005213, combined_string: invention_title: 유실수 나뭇가지 유인용 클립 abstract: 본 고안은 유실수 나뭇가지 유인용 클립에 관한 것이다.본 고안에 따르면 유실수 나뭇가지의 굵기에 따라 선택적으로 유입할 수 있도록 일체형으로 클립을 구성하여 가지의 균형을 유지시켜 원하는 방향으로 자랄 수 있고, 잎눈 또는 꽃눈의 발생이 용이하고 동시에 작업자의 사용이 편리하도록 하였으며, 과실수의 가지 유인 작업을 매우 손쉽고 정확하며 세밀하게 수행할 수 있게 됨에 따라 과수원의 전체적인 가지유인 작업에 소요되는 시간과 경비를 최대한으로 절감시키게 되었으며, 이로 인하여 과실재배농가의 소득증대와 경영수지의 개선 측면에 한층 더 이바지하게 되었고, 또한 클립 몸체에 형성된 돌출핀의 고정홈에 유입되는 나뭇가지와 유인요홈 사이에 공간이 유지됨에 따라 잎눈 또는 꽃눈 발생에 매우 유리하게 되었으며, 또한 클립 몸체에 가지가 유입되면서 휘어지는 각도를 다르게 함에 따라 과수나무의 전체적인 균형을 유지할 수 있는 효과가 제공된다. claims: 직선형의 내측몸체(12)와, 내측몸체(12)의 중앙 및 전후면에 동일 크기로 내측유인요부(2)(3)가 형성되도록 일체로 형성되고, 상하부면에 나뭇가지(1)의 장착성을 높이면서 가지 탈선방지 기능을 갖도록 내,외측돌기부(14a-1,15a-1,16a-1)를 갖는 고정홈(14a)(15a)(16a)이 형성되며, 내측유인요부(2)(3)의 간격이 넓게 유지되어 굵은 나뭇가지의 유인에 적합한 내측돌출핀(14)(15)(16)으로 이루어진 내측클립(10)과; 상기 내측클립(10)의 내측몸체(12) 외측 전후면에 동일 간격을 유지하여 일체로 형성되는 직선형의 외측몸체(22)와, 외측몸체(22)의 중앙 및 전후면에 동일 크기로 외측유인요부(4)(5)가 형성되도록 일체로 형성되고, 상하부면에 나뭇가지의 장착성을 높이면서 가지 탈선방지 기능을 갖도록 내,외측돌기부(24a-1,25a-1,26a-1)을 갖는 고정홈(24a)(25a)(26a)이 형성되며, 외측유인요부(4)(5)의 간격이 좁게 유지되어 굵기가 작은 나뭇가지의 유인에 적합한 외측돌출핀(24)(25)(26)으로 이루어진 외측클립(20)으로 구성되고,상기 고정홈(14a,15a,16a)(24a,25a,26a)은 유입되는 나뭇가지와 내측유인요부(2)(3) 및 외측유인요부(4)(5) 사이에 공간(1a)이 충분히 유지되도록 내측돌출핀(14)(15)(16) 및 외측돌출핀(24)(25)(26)의 상하부면 각각 형성되는 것을 특징으로 하는 유실수 나뭇가지 유인용 클립., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

975/1150 Row 975: application_number: 2020190005027, combined_string: invention_title: 포도 무핵재배용 복합측정기 abstract: 본 고안의 일실시예에 따른 무핵재배용 복합측정기는 판 형상의 본체와, 본체의 테두리에 형성되어 개화전 꽃송이 길이를 측정하는 꽃송이길이 측정유닛과, 본체의 테두리에 설치되고 포도알의 횡경 크기를 측정하는 복수의 홈을 포함하는 포도알크기 측정유닛을 포함할 수 있다. claims: 판 형상의 본체;상기 본체의 테두리에 형성되어 개화전 꽃송이 길이를 측정하는 꽃송이길이 측정유닛; 및상기 본체의 테두리에 설치되고 포도알의 횡경 크기를 측정하는 복수의 홈을 포함하는 포도알크기 측정유닛을 포함하는 포도 무핵재배용 복합측정기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

976/1150 Row 976: application_number: 1020190161554, combined_string: invention_title: 신품종 딸기 베리퀸 및 이의 육종 방법 abstract: 본 발명은 설향을 모본 품종으로 하고 매향을 부본 품종으로 하여 이를 교배시켜 얻어진 것으로서, 과형이 장원추형이며, 모본 품종인 설향이나 부본 품종인 매향에 비해 당산비가 높고 또한 개화시기와 수확시기가 빨라 촉성 재배에 적합한 딸기 신품종 베리퀸과 그 육종방법을 개시한다. claims: 설향 품종을 모본으로 하고, 매향 품종을 부본으로 하여 이를 교배시켜 얻어진 것으로서, 아래 (1) 내지 (11)의 특성을 가지며, 종자 또는 자묘에 의하여 번식하는 딸기 신품종 베리퀸:(1) 잎 표면의 색은 중간 녹색이다;(2) 잎 반엽은 없다;(3) 정단부 소엽 기부의 모양은 뾰족하다;(4) 정단부 소엽 가장자리의 톱니모양은 예거치-둔거치이다;(5) 꽃 수술은 있다;(6) 과실 너비에 대한 상대적 길이는 너비보다 매우 길다;(7) 과실 모양은 장원추형이다;(8) 과실 색은 중간 적색이다;(9) 과실의 과육색은 중간 적색이다;(10) 과실의 과심색은 옅은 적색이다; 및(11) 결실 유형은 1회 개화 결실이다.(a) 모본 품종인 설향과 부본 품종인 매향을 파종하는 단계, (b) 개화 시기에 모본 품종인 설향과 부본 품종인 매향을 인위적으로 교배시키는 단계, (c) 교배된 개체의 과실에서 종자를 채종하는 단계, (d) 종자를 발아·생육시켜 실생 개체를 얻는 단계, (e) 실생 개체 중 초세와 당산비를 선발 기준으로 하여 4~10 계통을 선발하여 자묘에 의하여 증식시키는 단계, 및 (f) 증식된 계통 중 과형과 당산비를 선발 기준으로 하여 최종 1계통를 선발하는 단계를 포함하되,상기 최종 1계통은 아래 (1) 내지 (11)의 특성을 가지는 것을 특징으로 하는 딸기 신품종 베리퀸의 육종 방법:(1) 잎 표면의 색은 중간 녹색이다;(2) 잎 반엽은 없다;(3) 정단부 소엽 기부의 모양은 뾰족하다;(4) 정단부 소엽 가장자리의 톱니모양은 예거치-둔거치이다;(5) 꽃 수술은 있다;(6) 과실 너비에 대한 상대적 길이는 너비보다 매우 길다;(7) 과실 모양은 장원추형이다;(8) 과실 색은 중간 적색이다;(9) 과실의 과육색은 중간 적색이다;(10) 과실의 과심색은 옅은 적색이다; 및(11) 결실 유형은 1회 개화 결실이다., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

977/1150 Row 977: application_number: 1020190160612, combined_string: invention_title: 3자 형상을 갖는 나뭇가지 유인용 클립 abstract: 본 발명은 &amp;quot;3&amp;quot;자 형상을 갖는 나뭇가지 유인용 클립에 관한 것이다.본 발명에 따르면 과실수의 가지 유인 작업을 매우 손쉽고 정확하며 세밀하게 수행할 수 있게 됨으로서 과수원의 전체적인 가지유인 작업에 소요되는 시간과 경비를 최대한으로 절감시키게 되었으며, 이로 인하여 과실재배농가의 소득증대와 경영수지의 개선 측면에 한층 더 이바지하게 되었고, 또한 클립 몸체에 형성된 돌출핀의 고정홈에 유입되는 나뭇가지와 유인요부 사이에 공간이 유지됨에 따라 잎눈 또는 꽃눈 발생에 매우 유리하게 되었으며, 또한 클립 몸체에 가지가 유입되면서 휘어지는 각도를 다르게 함에 따라 과수나무의 전체적인 균형을 유지할 수 있으며,또한 클립 몸체의 외측에 손잡이부를 형성하여 작업자가 안정되게 파지해 작업을 할 수 있어 작업성이 우수한 효과가 제공된다. claims: 내측의 중앙 및 상하부에 유인요부(2)(3)가 형성되도록 일체로 형성되고, 전후면에 나뭇가지(50)의 장착성을 높이면서 탈선방지 기능을 갖는 고정홈(21)(22)(23)이 형성되는 돌출핀(11)(12)(13)으로 이루어진 클립 몸체(10)와; 상기 클립 몸체(10) 외측 중앙 영역에 일체로 돌출 형성되는 손잡이부(30)로 구성된 것을 특징으로 하는 &amp;quot;3&amp;quot;자 형상을 갖는 나뭇가지 유인용 클립., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

978/1150 Row 978: application_number: 1020190141919, combined_string: invention_title: 이동식 비료 살포장치 abstract: 본 발명은 과수원을 포함하는 각종 작물이 재배되는 농경지의 협소한 곳을 자력으로 이동하며 자동으로 비료를 균일하게 살포할 수 있도록 한 이동식 비료 살포장치에 관한 것으로, 그 구성은, 바퀴가 설치된 본체의 전방에 호퍼가 설치되고 그 호퍼에는 비료배출수단과 비료배출양조절수단이 설치되며 상기 비료배출양조절수단의 하부에는 비료살포수단이 설치되고, 그 비료배출수단에는 비료공급수단이 설치되며, 상기 본체의 후방에는 동력발생수단과 조향장치를 설치하여 된 것으로 이루어진다. claims: 전/후방 양측에 각각의 바퀴(110)가 회전축(120)에 설치되고, 상기 각 바퀴는 동력전달수단(130)의 동력을 전달받아 구동하도록 설치하여 된 본체(100);상기 본체의 전방 설치되고, 후방은 상부에서 하부 전방으로 하향 기울기를 갖는 경사면(210)이 형성되며, 전방 상부에는 덮개(220)를 설치하여 된 호퍼(200);상기 호퍼의 전방 내측 바닥면에 설치되어 호퍼에 수용된 비료를 하부로 배출하도록 비료배출구멍(320)을 형성시켜 된 비료배출수단(300);상기 비료배출구멍의 하부에 설치되어 상기 비료배출구멍의 크기를 조절하며 비료배출양을 가감하도록 하는 비료배출양조절수단(400);상기 비료배출양조절수단의 하부에 복수 개의 비료살포가이드(520)가 방사상으로 설치된 회전원판(510)이 설치되고, 그 회전원판의 외곽에는 전방에 개방부(540)가 형성된 격벽(530)을 설치하여 된 비료살포수단(500);상기 덮개, 비료배출수단, 비료배출양조절구, 비료살포수단을 관통하는 회전축(610)이 설치되고 그 회전 축의 상단에 모터(620)가 설치되며, 상기 비료배출수단의 상부 회전축에는 비료교반부재(630)를 설치하여 된 비료공급수단(600);상기 본체의 후방에 설치되어 상기 제1 내지 제3모터로 동력원을 공급하는 동력발생수단(700);상기 동력발생수단의 상부에 위치하도록 설치되어 본체의 이동을 제어하도록 설치된 조향장치(800); 을 포함하는 구성을 특징으로 하는 이동식 비료 살포장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

979/1150 Row 979: application_number: 1020190140419, combined_string: invention_title: ＩＣＴ 및 ＩｏＴ를 이용한 스마트 양묘장 구축 및 운영시스템, 그리고 제어 방법 abstract: 본 발명은 ICT 및 IoT를 이용한 스마트 양묘장 구축 및 운영시스템, 그리고 제어 방법에 관한 것이다. 본 발명은, 수소발생 시스템(100), 네트워크(200), 양묘 및 스마트팜 관리 서버(300)를 포함하는 ICT 및 IoT를 이용한 스마트 양묘장 구축 및 운영시스템에 있어서, 양묘 및 스마트팜 관리 서버(300)는, 송수신부(310); 및 네트워크(200)를 통해 수소발생 시스템(100)의 온실운영 관리단말(140)과 데이터 세션을 연결한 뒤, 온실운영 관리단말(140)에 대한 제어명령 전송하도록 송수신부(310)를 제어하여 수소발생기(110)에 대해서 외부로부터 도시가스(LNG)가 입력배관을 타고 들어와서 수소발생기(110)를 통해 수소가스(H2)가 발생되면 수소저장탱크로 저장하며,수소발생기(110) 상에서 도시가스(LNG)에 대한 사용에 따라 발전된 전기 에너지와, 태양광발전기(120) 및 풍력발전기(130)에서 각각 발전된 전기 에너지를 충전지에 저장하는 발전 제어 모듈(321); 을 포함하는 것을 특징으로 한다.본 발명에 따르면, 스마트팜, 그 중에서도 특히 스마트 양묘장에 대한 에너지 효율을 고려하기 위해 최근에 각광받고 있는 신재생에너지를 활용할 뿐만 아니라, IoT 기반의 센싱 기술을 이용한 에너지 사용 효율을 극대화시킬 수 있고, 신재생에너지에 대한 가공 및 재판매가 가능할 뿐만 아니라, 신재생에너지의 생산시에 발생되는 부수적인 자원을 재활용 에너지원으로 활용할 수 있는 효과가 있다. claims: 수소발생기(110), 태양광발전기(120), 풍력발전기(130), 온실운영 관리단말(140)을 구비하는 수소발생 시스템(100) 외에, 네트워크(200), 양묘 및 스마트팜 관리 서버(300)를 포함하며, 수소발생기(110)는, 수소 분리 발생기, 이산화탄소(CO2)저장탱크, 전기에너지 발전기, 열에너지 저장탱크를 포함함으로써, 수소 분리 발생기에 의해 도시가스(LNG)에서 탄화수소를 취득하고 취득된 탄화수소를 개질하여 수소가스(H2)를 발생시킬 뿐만 아니라, 도시가스(LNG)를 분해하는 과정에서 수소 1kg당 이산화탄소(CO2) 온실가스 9 내지 12kg를 획득하여 이산화탄소(CO2) 저장탱크에 보관하며, 획득된 수소가스(H2)를 전기에너지 발전기를 통해 직접 연소나 연료전지를 이용해 전기에너지로 전환시키며, 전기에너지 전환시 열에너지도 발생시켜서 열에너지 저장탱크에 보관하는 ICT 및 IoT를 이용한 스마트 양묘장 구축 및 운영시스템에 있어서, 양묘 및 스마트팜 관리 서버(300)는, 송수신부(310); 및 네트워크(200)를 통해 수소발생 시스템(100)의 온실운영 관리단말(140)과 데이터 세션을 연결한 뒤, 온실운영 관리단말(140)에 대한 제어명령을 전송하도록 송수신부(310)를 제어하여 수소발생기(110)에 대해서 외부로부터 도시가스(LNG)가 입력배관을 타고 들어와서 수소발생기(110)를 통해 수소가스(H2)가 발생되면 발생된 수소가스를 수소저장탱크로 저장하며, 수소발생기(110) 상에서 도시가스(LNG)에 대한 사용에 따라 발전된 전기 에너지와, 태양광발전기(120) 및 풍력발전기(130)에서 각각 발전된 전기 에너지를 충전지에 저장하는 발전 제어 모듈(321); 각 수소저장탱크 단위에 대해서 각 수소검침센서가 구비되는 경우, 수소저장탱크에 미리 설정된 임계치 이상의 수소가스(H2)가 저장된 것을 온실운영 관리단말(140)로부터 네트워크(200)를 통해 수신하도록 송수신부(310)를 제어한 뒤, 네트워크(200)를 통해 관리자 단말(400)로 저장이 완료된 각 수소저장탱크의 일련번호를 전송하도록 송수신부(310)를 제어함으로써, 관리자 단말(400)에 의해 수소저장탱크 별로 외부에서 수소가스(H2)를 필요로 하는 업체에 판매를 할 수 있도록 하는 에너지 제공 모듈(322); 수소발생기(110)과 비닐하우스(2) 간에는 CO2 배관, 열 배관이 구비된 상태에서 수소발생기(110) 상에서 발생하는 이산화탄소(CO2)가 이산화탄소 저장탱크에 미리 설정된 CO2 임계치를 초과하는 경우 이산화탄소(CO2)를 비닐하우스(2) 내부로 제공하여 과육의 당도를 높이고, 수소발생기(110) 상에서 발생하는 열을 저장하는 열에너지 저장탱크에 열에너지가 미리 설정된 열에너지 임계치를 초과하는 경우 비닐하우스(2) 내부로 제공하기 위한 비닐하우스(2)의 내부 이산화탄소 농도(CO2) 및 온도에 대한 제어 명령을 네트워크(200)를 통해 온실운영 관리단말(140)로 전송하도록 송수신부(310)를 제어하며, 수소발생기(110) 상에서 발생하는 전기 에너지가 충전지에 미리 설정된 전기 에너지 임계치를 초과하는 경우 수소발생기(110)와 제어부(510) 간에 형성되는 전력배선을 이용해 비닐하우스(2)를 관리하는 제어부(510), 센서부(520), CCTV 그룹(530) 및 제어장치부(540)로 전기 에너지를 제공하도록 제어함으로써, CO2 배관을 통해 제공된 CO2를 활용한 제어부(510)에 의한 센서부(520)를 구성하는 CO2 센서(522)의 센싱 정보에 따라 비닐하우스(2) 내부에 재배되고 있는 농작물의 과육의 당도를 높이기 위한 당도가 제어되도록 하며, 열 배관을 통해 제공된 열에 대한 제어부(510)에 의한 센서부(520)를 구성하는 온/습도 센서(521)의 센싱 정보에 따라 비닐하우스(2) 내부에 재배되고 있는 농작물의 미리 설정된 온도 범위로 제어되도록 하며, 제어부(510)에 의해 제어장치부(540)를 구성하는 관수제어기(543)에 대한 제어를 통해 열 배관으로 들어오는 열기를 제어할 뿐만 아니라, 환기팬(541)을 통한 비닐하우스(2) 내부의 환기를 제어하고, 측천장제어기(544)를 외부 온/습도센서(521)와 내부 온/습도센서(521)에 의해 측정된 내부의 온도 및 습도에 기초하여 미리 설정된 온도 및 습도 범위로 제어가 수행되도록 하며, 제어부(510)에 의해 온/난방기(542)를 통해 비닐하우스(2) 내부의 온/습도센서(521)에 의해 측정된 온도 및 습도에 대한 정보를 통해 온열 또는 난방을 미리 설정된 온도 범위 내에서 제어할 수 있도록 하며, 제어부(510)에 의해 유압 실린더 방식으로 제어되는 채광커튼(545)에 대한 제어를 통해 비닐하우스(2)에 대한 일광조건을 제어하도록 하는 에너지 분배 모듈(323); 네트워크(200)를 통해 통합제어기(700)와 데이터 세션을 연결한 뒤, 통합제어기(700)를 통해 비닐하우스(2)의 전면과 후면에 각각 하나씩 형성된 종합감시센서(600)로부터 감시정보를 수신하되, 비닐하우스(2)의 전면과 후면에 각각 하나씩 형성된 종합감시센서(600) 중 적어도 하나로부터 지진, 화재, 출입 중 적어도 하나 이상을 감지한 뒤, 네트워크(200)를 통해 관리자 단말(500)로 비닐하우스(2)의 전면과 후면 중 적어도 하나 이상에서 발생한 지진 감지 정보, 화재 감지 정보, 출입 감지 정보를 실시간으로 제공하며, 네트워크(200)를 통해 통합제어기(700)와 데이터 세션을 연결한 뒤, 통합제어기(700)를 통해 비닐하우스(2)의 외부 및 내부에 미리 설정된 위치에 설치된 CCTV(310)로 구성된 CCTV 그룹(300)으로부터 영상 정보 수신 요청을 전송하도록 송수신부(310)를 제어하는 종합 감시 모듈(324); 을 포함하며, 종합감시센서(600)는, 하나의 모듈 형태의 센서로 전원이 인가되면 전원을 저장하는 배터리, 배터리로부터의 전원 인가 유무에 따라 점멸하는 점등 램프와, 제어 회로부 이외에도, 스피커, 디스플레이 패널, 지진 감지기, 화재 감지기, 출입 감지기, 이동 통신모듈을 포함함으로써, 비닐하우스(2)의 전방 및 후방에서의 출입 감지기를 통한 사람의 출입을 감지하고, 지진 감지기를 통해 비닐하우스(2)의 전방 및 후방에서의 지진을 감지하며, 화재 감지기를 통해서 비닐하우스(2)의 전방 및 후방에서의 화재를 감지한 뒤, 통합제어기(700)를 통해 네트워크(200)와 연결된 양묘 및 스마트팜 관리 서버(300)로 감지 정보를 전송함으로써, 종합 감시 모듈(324)에 의해 감지 정보가 데이터베이스(330)에 저장하도록 하며, 통합제어기(700)와 각 CCTV(310) 간에는 TVWS(TV White Space) 전파에 해당하는 공중파 전파를 이용하여 CCTV 영상을 전송하며, 통합제어기(700)는 CCTV 영상을 네트워크(200)를 통해 다시 종합 감시 모듈(324)로 제공하며,관리자 단말(400)은, 네트워크(200)를 통해 양묘 및 스마트팜 관리서버(300)로 액세스하여 데이터베이스(330)에 저장된 CCTV 그룹(530)을 구성하는 각 CCTV(531) 중 비닐하우스(2) 내부를 찍은 영상 데이터를 통해 비닐하우스 내부의 영상 데이터를 획득한 뒤, 획득된 영상 데이터를 활용해 비닐하우스 내부의 부지에 대한 형상정보를 획득하고, 비닐하우스를 위한 복수의 비닐하우스 요소(element) 정보{농작물(나무, 꽃, 수생농작물을 포함) 요소(element), 비닐하우스 전기/전자 제어장치 요소(element)(환기팬, 온/난방기, 관수제어기, 측천장제어기, 채광커튼 등)}를 네트워크(200)를 통해 양묘 및 스마트팜 관리서버(300)로부터 수신한 뒤, 수신된 비닐하우스 요소 정보 중 추가로 설치하고자 하는 비닐하우스 요소 정보를 선택하고, 비닐하우스 내부 면적 정보, 각 선택된 비닐하우스 요소(element) 정보에 대한 제곱 센치미터(cm2) 기준의 차지하는 면적 정보, 그리고 내부에 이미 설치된 농작물 요소 정보 및 비닐하우스 전기/전자 제어장치 요소가 이미 차지하고 있는 면적 정보 및 위치 정보를 네트워크(200)를 통해 양묘 및 스마트팜 관리서버(300)로부터 수신한 뒤, 추가로 선택된 비닐하우스 요소 정보를 추가하는 경우 비닐하우스 내부 면적 정보 내에 포함되는지 여부를 분석한 뒤, 모두 포함되는 경우 추가된 비닐 하우스 요소 정보가 추가된 비닐하우스(2) 내부의 모델링 정보를 생성하는 것을 특징으로 하는 ICT 및 IoT를 이용한 스마트 양묘장 구축 및 운영시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

980/1150 Row 980: application_number: 1020190139316, combined_string: invention_title: 온실용 조명장치 abstract: 본 발명은 온실의 일측 영역으로 빛을 조사하여 과수류를 수확한 후 분리하여 타측 영역으로 빛을 조사하여 과수류를 수확하며 빛의 조사 각도를 조절하여 과수류를 용이하게 수확할 수 있는 온실용 조명장치에 관한 것이다.이러한 본 발명은 온실에서 재배되는 과수류로 빛을 조사하는 온실용 조명장치에 있어서, 상기 온실의 상부에 전후 방향으로 연결된 가이드레일, 상기 가이드레일을 따라 이동 가능하게 연결된 슬라이더, 상기 슬라이더의 하부에 연결되어 상기 온실의 전후 방향으로 길게 배치되는 행거바, 상기 행거바에 분리 가능하게 거치되도록 훅을 갖는 거치프레임, 상기 거치프레임에 회전 가능하게 연결된 광원프레임, 상기 광원프레임의 회전 각도를 조절하도록 상기 거치프레임에 연결된 조절부재, 상기 광원프레임에 설치되어 상기 온실의 과수류로 빛을 조사하는 광원을 포함한다. claims: 온실에서 재배되는 과수류로 빛을 조사하는 온실용 조명장치에 있어서,상기 온실의 상부에 전후 방향으로 연결된 가이드레일,상기 가이드레일을 따라 이동 가능하게 연결된 슬라이더,상기 슬라이더의 하부에 연결되어 상기 온실의 전후 방향으로 길게 배치되는 행거바,상기 행거바에 분리 가능하게 거치되도록 훅을 갖는 거치프레임,상기 거치프레임에 외측면 방향으로 회전 가능하게 연결된 광원프레임,상기 광원프레임의 회전 각도를 조절하도록 상기 거치프레임에 연결된 조절부재,상기 광원프레임에 설치되어 상기 온실의 과수류로 빛을 조사하는 광원을 포함하는 온실용 조명장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

981/1150 Row 981: application_number: 1020190134934, combined_string: invention_title: 딸기재배포트를 이용한 실내 체험용 화분딸기 재배방법 및 그로부터 수확한 딸기 abstract: 본 발명은 딸기재배포트를 이용한 실내 체험용 화분딸기 재배방법 및 그로부터 수확한 딸기에 관한 것이다. 본원 발명은 딸기가 심겨진 재배포트를 잡아주는 2~4개의 포트지지부(33), 상기 포트지지부의 끝단에는 포트걸이부(29)가 형성되며, 상기 포트걸이부(29)는 고정봉(28)에 고정되어 재배포트(30)가 낙하되지 않도록 고정시키고, 상기 고정봉(28)은 승강로프(27)에 연결되어 있어 모터(21)의 작동으로 회전되는 회전축(26)의 회전에 따라 순차적으로 모터의 동력이 전달되어 승강로프(27)가 승하강하게되며, 상기 승강로프(27)가 승하강됨에 따라 재배포트(30)는 위 또는 아래로 이동하게 된다.그리고 상기 모터(21)가 구동되면 구동체인(22)이 회전되고, 상기 구동체인은 주기어(23)를 회전시키며, 상기 주기어(23)에 장착된 회전축(26)이 회전하면서 회전축(26)에 끼워진 보조기어(24)가 회전하게되면 상기 보조기어(24)가 승강로프(27)가 고정된 회전봉을 회전시켜 재배포트의 승하강 동력을 전달한다.이처럼 본 발명은 딸기의 꽃이 피거나 딸기 열매가 달린 재배포트를 소비자가 직접 구매할 수 있게 되어 농가의 소득을 크게 증대시킬 수 있다. 그리고 딸기 재배포트를 가정의 거실에서 키울 수 있어 화초처럼 딸기를 관상용으로 재배하거나 실내에서 식물이 자라서 꽃을 피우고 열매가 익어가는 과정을 직접 관찰할 수 잇으며, 건조한 늦겨울이나 봄철에 쾌적한 실내 환경을 제공한다. claims: 딸기 재배포트(30)을 이용한 실내 체험용 화분딸기의 재배방법에 있어서,상기 실내 체험용 화분딸기 재배방법은 유리온실 중앙에 온실내부기둥(40)이 온실의 지붕을 중앙에서 지지하게 되며 온실의 지붕은 천장의 내부골조(46)를 지지하게 되고, 상기 내부골조(46)와 일정간격 이격되어 외부골조(47)가 형성되며, 상기 외부골조와 내부골조 사이에는 외부골조를 지지하는 지지물이 형성되고, 상기 외부골조(47)에는 유리를 포함하는 보온커버(60)로 피복하고,모터(21)의 구동에 의해 구동체인(22)이 회전하면서 주기어(23)를 회전시키고 주기어(23)에 장착된 회전축(26)이 회전하며, 상기 회전축(26)에 끼워진 보조기어(24)는 회전축의 회전에 따라 회전하고, 상기 보조기어(24)는 승강로프(27)가 고정된 회전봉을 회전시키며, 상기 회전축(26)에는 겨울철에 보온을 위하여 부직포(50)를 권취하여 상기 모터의 동력에 의해 감아주거나 풀어주고,상기 딸기 재배포트(30)는 2~4개의 포트지지부(33)로 잡아주고, 상기 포트지지부의 끝단에 포트걸이부(29)가 형성되어 있어 상기 포트걸이부(29)가 고정봉(28)에 고정되어 재배포트(30)가 떨어지지 않도록 고정되어 유리온실의 내부에서 일정한 간격으로 배치되어 재배되며,상기 고정봉(28)은 승강로프(27)에 연결되어 있어 모터(21)의 작동으로 회전되는 회전축(26)의 회전에 따라 순차적으로 모터의 동력이 전달되어 승강로프(27)가 승하강되며, 상기 승강로프(27)가 승하강됨에 따라 딸기 재배포트(30)는 위 또는 아래로 이동되고,상기 딸기 재배포트(30)를 승하강 방식으로 재배할 때 딸기 재배포트(30)의 딸기를 관리하거나 딸기를 수확하는 경우에는 지상에서 50~120cm 높이로 딸기 재배포트를 내려서 관리하고, 관리가 끝난 다음에는 상승시켜 재배하며,상기 딸기 재배포트(30)에는 상토를 채우고 재배포트의 포트하부(35)에는 과도하게 관수된 수분이 제거될 수 있도록 수분배출공이 형성되며, 상기 수분배출공은 관수 후 상토의 수분 함량이 70~85% 정도 유지되도록 구멍을 형성시켜 주며,상기 딸기 재배포트(30)에는 상토의 수분 상태가 일정하게 유지될 수 있도록 1일 2~4회 점적관수하는 하며, 1~3일에 1~2회 양액을 상기 딸기 재배포트에 공급하여 딸기 재배포트에 공급되는 딸기 양액의 1일 공급량은 정식 이후 개화초기 까지는 30~60mL, 수확기에는 120~180mL 정도를 공급하는 것을 특징으로 하는 딸기 재배포트를 이용한 실내 체험용 화분딸기의 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

982/1150 Row 982: application_number: 1020190128345, combined_string: invention_title: 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템 abstract: 본 발명은 태양광발전과 과수 작물의 영농 활동을 병행하는 것이 가능하게 하는 것과 함께, 태양광 발전 장치를 설치하기 위해 임야에 대대적인 토목공사를 하는 등의 환경 파괴 및 농작지 파괴를 하지 않음은 물론, 태양광 발전의 발전량을 효율화하는 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템의 구조, 형상, 기능을 제공할 수 있는 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템이 제공된다. 본 발명에 따르면, 태양광 발전과 과수 작물의 영농 활동을 저렴한 비용으로 동시 영위가 가능하며, 농업 병행 발전을 위하여 태양전지 모듈 거치대를 별도로 시공하지 않고 기존의 작물 비가림 하우스 기능을 겸하게 함으로써 경제적인 시스템 구축이 가능하고, 기존의 과수원의 작물이 남향이 아니더라도 태양광 패널의 각도 가변이 가능한 구조물을 통해서 발전량의 최대화가 용이하다. claims: 복수의 태양광 패널(10); 및 상부에 상기 복수의 태양광 패널이 설치되는 시설 구조물;을 포함하는 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템 으로서,상기 시설 구조물은,하단부에 지중 매설용 파일(pile)이 형성되어, 작물 재배지의 면적에 상응하여 행 방향 및 열 방향으로 각각 소정 간격만큼씩 이격되어 수직 설치되는 복수의 파일 지지대(130);상기 파일 지지대(130) 상에 설치되어 상기 작물 재배지의 지붕 역할을 수행하며, 광투과성 재질로 제작되는 복수의 비가림막(140b);상기 복수의 비가림막(140b)이 각각 설치될 영역에 상응하여 마련되어 상기 비가림막(140b)을 안착 지지하는 복수의 비가림막 지지대(114b);상기 비가림막(140b)의 상측에서, 행 방향과 열 방향으로 일렬로 놓인 각각의 파일 지지대(130) 간을 일체로 연결하는 복수의 수평 지지대(110b);일단이 상기 파일 지지대(130)에 결합되고, 타단이 상기 비가림막 지지대(114b)에 결합되어, 각각의 파일 지지대(130)의 좌우 양측에서 사선 방향으로 상기 비가림막 지지대(114b)를 지지하는 복수의 사선 지지대(116);상기 복수의 태양광 패널(10)이 각각 설치될 영역에 상응하여 마련되어 상기 태양광 패널(10)을 안착 지지하며, 상기 수평 지지대(110b)의 상부에 결합되는 복수의 패널 지지대(112b);상기 태양광 패널(10)의 설치 각도의 변경을 수행하는 각도 변경부(50);상기 시설 구조물에 적어도 하나 설치되어, 상기 작물의 식재 공간의 광 세기를 측정하는 조도 센서;를 포함하고,상기 복수의 비가림막(140b)은,상호간에 소정의 경사각을 갖도록 설치되어 지붕 형태를 구성하고, 서로 인접한 비가림막(140b)의 양 끝단 간에 형성되는 소정 간격의 공간에는 빗물받이부(118)가 설치되어, 상기 복수의 비가림막(140b)과 상기 빗물받이부(118)는 상기 작물 재배지를 모두 커버하고,상기 복수의 태양광 패널(10)은,상기 비가림막(140b)의 상부의 복수의 패널 지지대(112b) 상에 안착 지지되며, 상기 각도 변경부(50)에 의해 상기 태양광 패널(10)의 방위각 변경 및 고도각 변경 중 적어도 하나가 실행되어, 상기 작물 재배지의 광 세기를 측정하는 조도 센서의 센싱 결과에 따라, 측정된 광 세기가 작물의 광포화점보다 낮은 값을 갖는 경우, 광차폐 영역이 차지하는 면적 비율을 낮추고, 측정된 광 세기가 작물의 광포화점보다 높은 값을 갖는 경우, 상기 태양광 패널(10)의 광입사면이 태양의 이동 위치를 추적하도록 함과 동시에, 상기 태양광 패널(10)의 고도각을 변경하여 태양의 고도 변화를 추적하도록 제어되는 것을 특징으로 하는, 과수작물 재배 하우스 기능을 수행하는 태양광 발전시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

983/1150 Row 983: application_number: 1020190128416, combined_string: invention_title: 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물 abstract: 본 발명은 태양광발전과 과수 작물의 영농 활동을 병행하는 것이 가능하게 하는 것과 함께, 태양광 발전 장치를 설치하기 위해 임야에 대대적인 토목공사를 하는 등의 환경 파괴 및 농작지 파괴를 하지 않음은 물론, 태양광 발전의 발전량을 효율화하는 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물의 구조, 형상, 기능을 제공할 수 있는 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물이 제공된다. 본 발명에 따르면, 태양광 발전과 과수 작물의 영농 활동을 저렴한 비용으로 동시 영위가 가능하며, 암석이 많은 지반에서도 경제적으로 태양광 구조물의 기초 공사 가능 방법을 제공할 수 있고, 기존의 과수원의 작물이 남향이 아니더라도 태양광 패널의 각도 가변이 가능한 구조물을 통해서 발전량의 최대화가 용이하다. claims: 복수의 태양광 패널; 및 상부에 상기 복수의 태양광 패널이 설치되는 시설 구조물;을 포함하는 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물 로서,상기 시설 구조물은,하단부에 지중 매설용 파일(pile) 이 형성되어, 작물 재배지의 면적에 상응하여 행 방향 및 열 방향으로 각각 소정 간격만큼씩 이격되어 수직 설치되는 복수의 파일 지지대(130); 상기 파일 지지대(130) 상에 설치되어 상기 작물 재배지의 지붕 역할을 수행하며, 광투과성 재질로 제작되는 복수의 비가림막(140b);상기 복수의 비가림막(140b)이 각각 설치될 영역에 상응하여 마련되어 상기 비가림막(140b)을 안착 지지하는 복수의 비가림막 지지대(114b);상기 비가림막(140b)의 상측에서, 행 방향과 열 방향으로 일렬로 놓인 각각의 파일 지지대(130) 간을 일체로 연결하는 복수의 수평 지지대(110b);일단이 상기 파일 지지대(130)에 결합되고, 타단이 상기 비가림막 지지대(114b)에 결합되어, 각각의 파일 지지대(130)의 좌우 양측에서 사선 방향으로 상기 비가림막 지지대(114b)를 지지하는 복수의 사선 지지대(116);상기 복수의 태양광 패널의 각각이 설치될 영역에 상응하여 마련되어 상기 태양광 패널을 안착 지지하며, 상기 수평 지지대(110b)의 상부에 결합되는 복수의 패널 지지대(112b);상기 태양광 패널의 설치 각도의 변경을 수행하는 각도 변경부(50);상기 시설 구조물에 적어도 하나 설치되어, 상기 작물의 식재 공간의 광 세기를 측정하는 조도 센서;를 포함하고,상기 복수의 비가림막(140b)은,상호간에 소정의 경사각을 갖도록 설치되어 지붕 형태를 구성하고, 서로 인접한 비가림막(140b)의 양 끝단 간에 형성되는 소정 간격의 공간에는 빗물받이부(118)가 설치되어, 상기 복수의 비가림막(140b)과 상기 빗물받이부(118)는 상기 작물 재배지를 모두 커버하고,상기 복수의 태양광 패널은,상기 비가림막(140b)의 상부의 복수의 패널 지지대(112b) 상에 안착 지지되며, 상기 각도 변경부(50)에 의해 상기 태양광 패널의 방위각 변경 및 고도각 변경 중 적어도 하나가 실행되어, 상기 작물 재배지의 광 세기를 측정하는 조도 센서의 센싱 결과에 따라, 측정된 광 세기가 작물의 광포화점보다 낮은 값을 갖는 경우, 광차폐 영역이 차지하는 면적 비율을 낮추고, 측정된 광 세기가 작물의 광포화점보다 높은 값을 갖는 경우, 상기 태양광 패널의 광입사면이 태양의 이동 위치를 추적하도록 함과 동시에, 상기 태양광 패널의 고도각을 변경하여 태양의 고도 변화를 추적하도록 제어되며,상기 복수의 수평 지지대 각각은, 수평 방향으로 연장되는 상측 지지대(212); 상기 상측 지지대와 평행하게 연장되는 하측 지지대(214); 상기 상측 지지대(212)와 하측 지지대(214) 사이를 수직 방향에서 지지하기 위해 소정 간격 만큼씩 이격되어 고정 설치되는 복수의 수직 보강빔(216); 상기 상측 지지대(212)와 하측 지지대(214) 사이를 사선 방향에서 지지하기 위해 소정 간격만큼씩 이격되어 고정 설치되는 복수의 사선 보강빔(218)를 포함하는 이중 지지 구조를 갖고,상기 지중 매설용 파일(pile) 은 암석 기반의 지중 시공에도 용이하도록 П자 형상을 갖도록 제작되는 것을 특징으로 하는, 밭작물 재배와 태양광 발전 병행을 위한 태양광 시설 구조물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

984/1150 Row 984: application_number: 1020190127444, combined_string: invention_title: 이동식 수직재배 장치 abstract: 본 발명은 하우스 내에서 재배되는 과일 중 특히 수박을 수직으로 재배할 수 있도록 하는 이동식 수직재배 장치에 관한 것으로, 복수의 가로프레임 및 세로프레임이 상호 결합 가능하여 네 개의 면으로 형성된 측면골조를 이룰 수 있으며, 상기 측면골조의 상부에 복수의 활형프레임이 동일 간격으로 이격 배치되어 결합 가능한 하우스프레임; 및 상기 하우스프레임의 내측에 구비 가능한 재배부를 포함하며, 상기 재배부는 양단이 상기 측면골조의 상부 양측에 각각 결합 가능하고, 상기 하우스프레임의 길이 방향을 따라 등간격으로 상호 이격되도록 구비 가능한 복수의 가이드프레임; 상기 가이드프레임에 결합 가능하여 상기 가이드프레임의 길이 방향을 따라 좌우 이동이 가능한 복수의 가이드롤러; 상기 가이드롤러의 일측에 결합 가능하며, 지면을 향해 수직으로 연장 형성 가능한 제1지지프레임; 및 상기 하우스프레임의 길이 방향으로 복수개가 구비 가능한 상기 제1지지프레임의 일측에 연속되도록 결합 가능하고, 상부에 하우스에서 재배되는 과일이 올려질 수 있는 받침대를 포함하는 것을 특징으로 하여 과일을 지면으로부터 이격시켜 공중에서 재배할 수 있도록 하여, 노동 강도를 저하시켜 작업속도를 향상시키고, 병원균으로부터 감염 확률을 낮춰 고품질의 과일을 생산할 수 있으며, 한정된 하우스 면적으로 밀식재배를 가능하게 하여 과일의 수확량을 증가시키고, 하우스 내의 작업 공간을 자유롭게 활용할 수 있는 이동식 수직재배 장치에 관한 것이다 claims: 복수의 가로프레임 및 세로프레임이 상호 결합 가능하여 네 개의 면으로 형성된 측면골조를 이룰 수 있으며, 상기 측면골조의 상부에 복수의 활형프레임이 동일 간격으로 이격 배치되어 결합 가능한 하우스프레임; 및상기 하우스프레임의 내측에 구비 가능한 재배부를 포함하고,상기 재배부는,양단이 상기 측면골조의 상부 양측에 각각 결합 가능하고, 상기 하우스프레임의 길이 방향을 따라 등간격으로 상호 이격되도록 구비 가능한 복수의 가이드프레임;상기 가이드프레임에 결합 가능하여 상기 가이드프레임의 길이 방향을 따라 좌우 이동이 가능한 복수의 가이드롤러;상기 가이드롤러의 일측에 결합 가능하며, 지면을 향해 수직으로 연장 형성 가능한 제1지지프레임; 및상기 하우스프레임의 길이 방향으로 복수개가 구비 가능한 상기 제1지지프레임의 일측에 연속되도록 결합 가능하고, 상부에 하우스에서 재배되는 과일이 올려질 수 있는 받침대를 포함하며,상기 제1지지프레임에는,상기 받침대를 지지 가능한 지지부재를 더 포함하고,상기 받침대는,상기 하우스프레임의 길이 방향을 따라 동일 선상으로 구비 가능한 상기 제1지지프레임의 일측에 연속 되도록 결합 가능한 제1받침프레임;상기 제1받침프레임과 동일한 길이를 가지며, 상기 제1받침프레임과 일정 간격 이격되도록 구비 가능한 제2받침프레임; 및상기 제1받침프레임 및 제2받침프레임의 사이에 구비 가능하여 양단이 상기 제1받침프레임 및 제2받침프레임의 일측에 각각 수직으로 결합 가능하고, 상기 제1받침프레임 및 제2받침프레임의 길이 방향을 따라 동일 간격 이격되어 결합 가능한 복수의 보조프레임을 포함하며,상기 제1받침프레임은 회전이 가능하도록 상기 제1지지프레임과 제3브라켓(244)에 의해 결합 가능한 것을 특징으로 하는 이동식 수직재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

985/1150 Row 985: application_number: 1020190122401, combined_string: invention_title: 과일의 재배방법. abstract: 본 발명은 과일의 재배방법에 관한 것으로, 과수의 휴면기에 미네랄 분산액을 과수 경작지 토양에 살포하는 단계, 과수의 생육기에 상기 미네랄 분산액을 매월 1회 과수 엽면에 살포하는 단계를 포함하며, 상기 미네랄 분산액은 칼슘염, 마그네슘염, 및 게르마늄염을 함유하는 미네랄 수용액을 제조하는 단계, 상기 미네랄 수용액에 트리에틸아민을 부가하여 미네랄 침전물을 제조하는 단계, 상기 미네랄 침전물에 증류수 및 계면활성제를 부가하고 혼합하여 미네랄 분산액을 제조하는 단계를 포함하여 제조되는 것을 특징으로 한다. claims: 과수의 휴면기에 미네랄 분산액을 과수 경작지 토양에 살포하는 단계;과수의 생육기에 상기 미네랄 분산액을 매월 1회 과수 엽면에 살포하는 단계;를 포함하며,상기 미네랄 분산액은 칼슘염, 마그네슘염, 및 게르마늄염을 함유하는 미네랄 수용액을 제조하는 단계;상기 미네랄 수용액에 트리에틸아민을 부가하여 미네랄 침전물을 제조하는 단계;상기 미네랄 침전물에 증류수 및 계면활성제를 부가하고 혼합하여 미네랄 분산액을 제조하는 단계;를 포함하여 제조되는 것을 특징으로 하는 과일의 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

986/1150 Row 986: application_number: 1020190117314, combined_string: invention_title: 스피루리나를 이용한 딸기 재배용 영양제 또는 비료 조성물 abstract: 본 발명은 스피루리나를 이용한 딸기 재배용 영양제 또는 비료 조성물에 관한 것으로, 더욱 상세하게는 스피루리나의 발효 추출물을 유효성분으로 포함하되, 상기 스피루리나의 발효 추출물은, 스피루리나의 추출물을 바실러스 균주로 발효시킨 것임을 특징으로 한다. 본 발명에 의하면, 딸기의 생장이 촉진되는 것은 물론, 딸기의 콜린, 비타민, 칼슘의 함량이 높으며, 당도가 우수한 딸기의 재배가 가능하다는 장점이 있다. claims: 스피루리나의 발효 추출물을 유효성분으로 포함하되,상기 스피루리나의 발효 추출물은,스피루리나의 추출물을 바실러스 균주로 발효시킨 것임을 특징으로 하는 스피루리나를 이용한 딸기 재배용 조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

987/1150 Row 987: application_number: 1020190115692, combined_string: invention_title: 사과 재배 전용 친환경 비료 및 그 제조방법 abstract: 본 발명은 친환경 발효 숙성 사과 전용 비료를 제조하는 방법에 관한 것으로, 사과의 식품학적 특성을 고려하여 재배 시 사용하는 친환경 비료 제조는 천연물질 및 천연 광물을 재료에 첨단 발효 기술을 접목하여 대량 생산 및 산업화를 위해, 이에 따른 제조 공정으로 제 1단계는 유기성재료 및 유기성부용재의 전(前)처리 제조 단계, 제 2단계는 전(前)처리 유기성재료 및 유기성부용재와 무기성 반응재의 혼합 단계, 제 3단계는 숙성 단계, 제 4단계는 건조 처리 단계, 제 5단계는 살균 처리 단계, 제 6단계는 포장 단계, 제 7단계는 제품화 단계를 포함하여, 사과재를 재배 시 종래의 화학비료 및 농약 사용으로 작물의 수량과 품질저하, 생산력 감퇴 및 토양의 산성화 등의 문제를 해결할 수 있고, 친환경 비료를 통해 실제 사과 재배에 적용되어 소비자의 기호도가 향상된 최종 제품은 시장 경쟁력과 경제적 유익을 제공할 수 있는 유용한 발명이다. claims: 사과 재배 전용 친환경 비료 제조로, 제 1단계는 유기성 재료인 고추씨, 마늘 및 마늘껍질과, 유기성 부용재인 왕겨, 톱밥, 코코넛 화이버, 달걀 껍질 분말을 전처리-&gt;혼합-&gt;발효-&gt;숙성하는 전(前)처리 하는 단계, 제 2단계는 전(前)처리된 유기성 재료와 유기성 부용재 및 무기성 반응재인 바이오 스톤을 혼합하는 단계, 제 3단계는 숙성 단계, 제 4단계는 건조 처리 단계, 제 5단계는 살균 처리 단계, 제 6단계는 포장 단계, 제 7단계는 제품화 단계로 이루어지는 것을 특징으로 하는 사과 재배 전용 친환경 비료 제조 방법. 제 1항 내지 제 8항 중 어느 한 항의 제조방법으로 제조된 것을 특징으로 하는 사과 재배 전용 친환경 비료., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

988/1150 Row 988: application_number: 1020190109473, combined_string: invention_title: 수목재배지 상의 가림막 설치공법 abstract: 본 발명은 기상이변에 신속하게 대응할 수 있는 과수, 채소 재배 노지에 가림막을 설치하는 공법에 대한 것으로, 본 발명의 실시예에 따르면, 노지에서 재배하는 채소, 과실수 등의 수목이 갑작스런 기상이변으로 우박이나 폭우 등으로 입을 수 있는 피해를 간단한 구조물과 가림막을 설치하여 상시적으로 보호할 수 있도록 해, 노지환경에서 과수재배의 안정성을 확보할 수 있다. claims: 수목이 식재된 노지에 수직프레임(10)을 삽입하는 1단계;상기 수직프레임(10) 상단에 가림막을 설치 및 지지하는 가림막 부설모듈(100)을 결합하는 2단계;상기 가림막 부설모듈(100)의 상부에 횡방향으로 결합하는 수평프레임(20)을 결합하는 3단계;상기 1단계 내지 상기 3단계를 다수회 반복하여 상기 노지 상에 상기 수직프레임 및 가림막 부설모듈(100)의 결합체를 복수개가 행과 열을 이루도록 배치형성하는 4단계; 및상기 결합체의 상부에 상기 수평프레임(20)과 직교하는 방향으로 가림막 가이드 와이어(30)를 설치하고, 상기 가림막 가이드 와이어(W)에 끼움 결합되는 가림막(M)을 부설하는 5단계;를 포함하는,수목재배지 상의 가림막 설치공법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

989/1150 Row 989: application_number: 1020190104097, combined_string: invention_title: 3가지 작물 3배 수확용 입체적 스마트 팜 시설 하우스 abstract: 개시되는 3가지 작물 3배 수확용 입체적 스마트 팜 시설 하우스가 수직 기둥 부재와, 외부 비닐 지붕 부재와, 수평 기둥 부재와, 전후 기둥 부재와, 오버 헤드 이동 발판 부재와, 오버 헤드 이동 발판 레일 부재와, 발판 이동 부재와, 2가지 작물 지상 재배 부재를 포함함에 따라, 포도, 키위 등의 줄기 과수, 딸기 및 쌈 채소 3가지의 다양한 작물이 하나의 상기 3가지 작물 3배 수확용 입체적 스마트 팜 시설 하우스에서도 작물 재배의 휴지기가 최소화되면서 함께 재배될 수 있게 되므로, 종래에 비해 같은 면적 상에서도 3가지의 작물의 3배 이상의 소출이 발생될 수 있게 되는 장점이 있다. claims: 설치면에 대해 수직으로 세워지는 수직 기둥 부재;상기 수직 기둥 부재의 상부와 측면을 덮으면서 상기 수직 기둥 부재에 의해 지지되고, 비닐로 이루어지는 외부 비닐 지붕 부재;상기 수직 기둥 부재에 수직으로 연결되고, 상기 설치면에 대해 수평이 되도록 상기 설치면으로부터 소정 높이의 상공 상에 배치되는 수평 기둥 부재;상기 설치면으로부터 소정 높이의 상공 상에 배치되어, 상기 외부 비닐 지붕 부재와 상기 설치면 사이의 공간 중 상기 외부 비닐 지붕 부재에 상대적으로 근접된 상공에서 재배되는 상공 재배 작물의 재배를 위해 작업자가 올라설 수 있는 오버 헤드 이동 발판 부재;상기 오버 헤드 이동 발판 부재의 이동 방향으로 일정 길이로 길게 형성되는 오버 헤드 이동 발판 레일 부재;상기 오버 헤드 이동 발판 레일 부재를 고정시키고, 상기 오버 헤드 이동 발판 부재의 하중을 견디도록 상기 수직 기둥 부재에 부착되는 돌출 부재;상기 오버 헤드 이동 발판 레일 부재를 따라 상기 오버 헤드 이동 발판 부재를 이동시킬 수 있는 발판 이동 부재; 및상기 설치면에 대해 수직으로 세워지고, 상기 수평 기둥 부재의 하측 공간에서 2가지의 지상 재배 작물이 서로 다른 높이로 재배될 수 있도록 하는 2가지 작물 지상 재배 부재;를 포함하는 3가지 작물 3배 수확용 입체적 스마트 팜 시설 하우스., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

990/1150 Row 990: application_number: 1020190087435, combined_string: invention_title: 과수봉지 제조장치의 과수봉지 투입구 밀폐용 접착테이프 접착 장치 및 그 방법 abstract: 본 발명은 나무에서 생산되는 열매인 배, 사과 등 과수 재배에 사용되는 과수봉지의 투입구 밀폐용 접착테이프를 과수봉지를 구성하는 내지의 상단 내측면에 접착하는 과수봉지 제조장치의 과수봉지 투입구 밀폐용 접착테이프 접착 장치 및 그 방법에 관한 것으로, 더욱 상세하게는 과수봉지의 투입구에 삽입되는 과수 줄기의 꼭지가 자유롭게 움직일 수 있도록 하여 과수의 성장을 촉진 시키도록 하고, 과수 줄기의 외측 둘레의 전면 투입부와 후면 투입부를 밀폐시켜 과수 봉지 내부로 빗물 등의 침입을 방지하여 과수의 부패를 방지함과 동시에 신속하고도 수월하게 과수를 씌울 수 있도록 하는 과수봉지의 투입구의 일측 내 측면에 접착시키는 과수봉지의 투입구 밀폐용 접착테이프를 과수봉지를 구성하는 상부 투입구의 후면 투입부 내측면의 상단 중앙에 일정간격을 두고 자동으로 연속 접착하도록 하는 것이다. claims: 박리지(12)의 중간에 비 접착부(11)를 형성하고, 과수봉지의 투입구 밀폐용 접착테이프(10) 외측면에 박리지(12)를 점착하되, 상기 박리지(12) 양단에 박리지 손잡이(12A)가 형성된 과수봉지의 투입구 밀폐용 접착테이프(10)를 과수봉지(30)를 구성하는 상부 투입구(33)의 후면 투입부(33B) 내측면의 상단 중앙에 일정간격을 두고 자동으로 연속 접착하도록 하는 과수봉지 제조장치(100)의 과수봉지 투입구 밀폐용 접착테이프 접착 장치(110)로서, 상기 과수봉지 투입구 밀폐용 접착테이프 접착 장치(110)는 내지(30-1)와 외지(30-2)가 각각 권취된 회전 드럼(111)(112)과; 상기 회전 드럼(111)(112)에 권취된 내지(30-1)와 외지(30-2)를 공급 이송시키면서 상기 내지(30-1)는 제1 안내 롤러(R1)를 거쳐 제1 이송 롤러부(R2)에 의하여 이송되어 내지(30-1)의 표면에 과수봉지의 투입구 밀폐용 접착테이프(10)가 일정 폭으로 절단되면서 일정간격을 두고 내지(30-1)의 중앙 표면에 연속접착되게 하는 과수봉지의 투입구 밀폐용 접착테이프 접착 제조부(110A) 및 박리지 손잡이 형성 제조부(110B);를 포함하여 구성하되, 과수봉지의 투입구 밀폐용 접착테이프 권취용 회전 드럼(113)에 권취된 과수봉지의 투입구 밀폐용 접착테이프(10)를 내지(30-1)의 공급 이송 방향과 역방향으로 이송시켜 과수봉지의 투입구 밀폐용 접착테이프 접착 제조부(110A)측으로 공급되게 구성함을 특징으로 하는 과수봉지 제조장치의 과수봉지 투입구 밀폐용 접착테이프 접착 장치.제1항에 기재된 과수봉지 투입구 밀폐용 접착테이프 접착 방법으로서, 내지(30-1)와 외지(30-2)를 겹쳐 이송시키는 제1 단계(S1)와; 내지(30-1)를 진공 흡착용 회전 드럼(110A-2)의 상부 둘레면과 내지 이송 롤러(100A-4)의 상부 둘레면 사이로 내지(30-1)를 공급시키면서 과수봉지의 투입구 밀폐용 접착테이프 권취용 회전 드럼(113)에 권취된 과수봉지의 투입구 밀폐용 접착테이프(10)를 과수봉지의 투입구 밀폐용 접착테이프 절단용 회전 드럼(100A-3)의 절단 칼(100A-3')에 의하여 일정 폭으로 절단함과 동시에 진공 흡착용 회전 드럼(110A-2)에 흡착시킨 후 이송되는 내지(30-1)의 중앙 표면에 과수봉지의 투입구 밀폐용 접착테이프(10)의 양면테이프(21)(22)의 일측면이 접착되면서 이송되게 하는 제2 단계(S2)와; 상기 제2 단계(S2)에서 얻어진 과수봉지의 투입구 밀폐용 접착테이프(10)의 박리지 손잡이(12A)를 접도록 하는 제3 단계(S3);를 포함하되, 상기 절단된 일정 폭의 과수봉지의 투입구 밀폐용 접착테이프(10)가 내지(30-1)의 중앙 표면에 일정간격을 두고 연속접착되게 함을 특징으로 하는 과수봉지 제조장치의 과수봉지 투입구 밀폐용 접착테이프 접착 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

991/1150 Row 991: application_number: 1020190087436, combined_string: invention_title: 과수봉지의 투입구 밀폐용 접착테이프 제조장치 및 그 방법 abstract: 본 발명은 나무에서 생산되는 열매인 배, 사과 등 과수 재배에 사용되는 과수봉지의 투입구 밀폐용 접착테이프 제조장치 및 그 방법에 관한 것으로, 더욱 상세하게는 과수봉지의 투입구에 삽입되는 과수 줄기의 꼭지가 자유롭게 움직일 수 있도록 하여 과수의 성장을 촉진시키도록 하고, 과수 줄기의 외측 둘레의 전면 투입부와 후면 투입부를 밀폐시켜 과수 봉지 내부로 빗물 등의 침입을 방지하여 과수의 부패를 방지함과 동시에 신속하고도 수월하게 과수를 씌울 수 있도록 하는 과수봉지의 투입구의 일측 내 측면에 접착시키는 과수봉지의 투입구 밀폐용 접착테이프의 제조장치 및 그 방법에 관한 것이다. claims: 과수봉지(30)의 상부 투입구(33)의 밀폐용 접착테이프(10) 중간에 비 접착부(11)를 형성하고, 상기 상부 투입구 밀폐용 접착테이프(10)의 표면에 전이되어 접착된 양면테이프(21)(22)의 외측면에 박리지(12)를 점착하되, 상기 박리지(12) 양단에 박리지 손잡이(12A)를 형성하는 과수봉지의 투입구 밀폐용 접착테이프 권취기(100)로서, 상기 권취기(100)는 하부 지지 프레임(110) 상부에 고정 설치된 권취용 지지판(120)과; 상기 권취용 지지판(120) 일측 후방에 설치된 회전 드럼 구동부(130)와; 상기 회전 드럼 구동부(130)를 구성하는 구동모터(131)의 축(131')에 연결되어 권취용 지지판(120) 전방으로 돌출시킨 밀폐용 접착테이프 권취용 회전 드럼(140)과; 상기 회전 드럼 구동부(130)의 상단에 설치된 상부 풀리(132)의 축(132')에 연결되고 권취용 지지판(120) 전방으로 돌출시킨 폐 박리지 권취용 회전 드럼(150)과; 권취용 지지판(120)의 전방 타측 상방에 설치된 제1 및 제2 접착테이프(21A)(22A)를 권취 시키는 제1 및 제2 회전 드럼(160)(170); 및 제1 회전 드럼(160) 직 하방에 설치된 과수봉지의 투입구 밀폐용 접착테이프(10)의 박리지(12)를 권취 시키는 박리지 회전 드럼(180);을 포함하여 구성하고, 상기 박리지 회전 드럼(180)에 권취된 과수봉지의 투입구 밀폐용 접착테이프(10)의 박리지(12)를 접착제 전이용 회전 롤러(190) 및 제1 안내 롤러(R1)를 거쳐 밀폐용 접착테이프 권취용 회전 드럼(140)에 권취 시키되, 제1 및 제2 회전 드럼(160)(170)에 각각 권취된 제1 및 제2 접착테이프(21A)(22A)의 양면테이프(21)(22)를 접착제 전이용 회전 롤러(190)의 전단 안내 롤러부(191)와 후단 안내 롤러부(192)에 통과시키면서 제1 및 제2 접착테이프(21A)(22A) 각각의 양면테이프(21)(22) 일단을 상기 과수봉지의 투입구 밀폐용 접착테이프(10)의 박리지(12)의 표면에 전이시키고, 양면테이프(21)(22)가 각각 전이된 폐 박리지(21A-1)(22A-1)를 제2 및 제3 안내 롤러(R2)(R3)를 거쳐 폐 박리지 권취용 회전 드럼(150)에 권취 하도록 구성함을 특징으로 하는 과수봉지의 투입구 밀폐용 접착테이프 제조장치.박리지 회전 드럼(180)에 권취된 박리지(12)의 일단을 접착제 전이용 회전 롤러(190) 및 제1 안내 롤러(R1)를 거쳐 밀폐용 접착테이프 권취용 회전 드럼(140)에 걸어 연결 시키는 제1 단계(S1)와; 제1 및 제2 회전 드럼(160)(170)에 권취된 제1 및 제2 접착테이프(21A)(22A)의 일단을 제4 및 제5 안내 롤러(R4)(R5)를 거쳐 접착제 전이용 회전 롤러(190)의 전단 안내 롤러부(191)와 후단 안내 롤러부(192)에 통과시키면서 제2 및 제3 안내 롤러(R2)(R3)을 거쳐 폐 박리지 권취용 회전 드럼(150)에 걸어 연결 시키는 제2 단계(S2)와; 회전 드럼 구동부(130)에 전원을 공급하여 동작하게 하는 제3 단계(S3)와; 상기 제3 단계(S3)에 의하여 밀폐용 접착테이프 권취용 회전 드럼(140) 및 폐 박리지 권취용 회전 드럼(150)을 회전시키는 제4 단계(S4)와; 접착제 전이용 회전 롤러(190)에 의하여 제1 및 제2 접착테이프(21A)(22A)의 양면테이프(21)(22)를 박리지(12)의 표면에 전이시켜 과수봉지의 투입구 밀폐용 접착테이프(10)를 생성하는 제5 단계(S5)와; 폐 박리지(21A-1)(22A-1) 및 과수봉지의 투입구 밀폐용 접착테이프(10)를 폐 박리지 권취용 회전 드럼(150) 및 밀폐용 접착테이프 권취용 회전 드럼(140)에 각각 권취 시키는 제6 단계(S6);를 통하여 권취된 과수봉지의 투입구 밀폐용 접착테이프(10)를 제조함을 특징으로 하는 과수봉지의 투입구 밀폐용 접착테이프 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

992/1150 Row 992: application_number: 1020190086714, combined_string: invention_title: 기름밤나무 및 각종 유실수 재배 기능성 비료 및 토질 제조방법 abstract: 본 발명은 1차로 기름밤나무 등 유실수를 묘목상태에서 또는 임야 등 토지에 옮겨 심을 때 또는 성장기인 1-2년간에 필요한 양분을 제공하며, 2차로는 주택이나 아파트 및 상가 등 실내에서 또는 옥상 등 외부에서 조경용 꽃이나 일반적 채소류 등을 재배할 경우에 필요한 친환경 기능성 조경토 및 그 제조방법에 관한 것으로서, 미세다공을 가진 다공성 물질인 제오라이트, 펄라이트, 화산모래, 피트모스 분말, 천연 무기질 발포입자 등을 포함한 입자 중에서 하나 또는 그 이상을 선택하고(A군);식물의 영양분 종류로서 전분, 젤라틴, 키토산 등의 영양물질 중 하나 또는 그 이상을 선택하여 겔 상태로 형성된 수용액에 혼합 침지 시킨 후(B군);더불어 적어도 1종의 배양된 유산균, 효모균, 고초균 중 1종을 선택하여 발효 배양물을 준비한다(C군).상기 준비한 A. B. C군의 혼합요소 중 A군중 한종류 이상의 분말을 1:1의 중량비로 혼합하고 이중 25-35 중량부와 B군중 한 종류 이상의 추출물과, 물과, C군 중 한 종류를 선택하여 1:6:1의 중량비로 혼합한 혼합액 3 내지 6중량부를 함유하여 혼합액으로 결착시켜 입상형으로 형성하여 조경토를 제조하고 이를 실내. 외부 옥상 조경토 및 토지 개량제로 사용하도록 하여서 식물의 생장을 촉진시키는 효과를 얻는다.[색인어]다공성 물질.입상형.산화칼슘. claims: 혼합물의 조성과정에 있어서 피트모스 분말 등을 3.5:6.5 내지 4:6의 중량비로 혼합하여 70 내지 80 중량부의 혼합물 조성;무기질 발포입자인 펄라이트, 피트모스, 제오라이트 등을 포함하는 다공성 물질의 구성:기능성 조경토 표면에 키토산을 분해하는 분말상의 키토나제를 도포하여 코팅하는 것을 특징으로 하는 친환경 기능성 조경 토 제조방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

993/1150 Row 993: application_number: 1020190074440, combined_string: invention_title: 병충해 피해 방지를 위한 과수봉지용 이산화염소 서방형 키트 abstract: 본원은 과실을 재배하는 과정 중 장기간 병해충으로부터 보호하고, 과실의 외관을 아름답게 하기 위하여 살조력이 우수한 이산화염소(Chlorine dioxide)를 서서히 방충하는 과수봉지 관련 기술이다.본원 기술은 살조력이 우수한 이산화염소(Chlorine dioxide)가 과수봉지 내부에 장기간 방출할 수 있도록 과수봉지용 이산화염소 서방형 키트를 제공하되, 용액상의 아염소산나트륨(NaClO2)이 내장되는 키트인 경우 수용액상의 아염소산나트륨(NaClO2)과 고흡수성수지가 포함되고, 유기산(Organic acid) 공급에 의한 pH 7.0 이하의 산성조건에서 이산화염소의 소스(Source)가 하이드로겔 타입으로 만들어져 적용되므로 이산화염소 가스가 서서히 방출되는 서방형 키트로 적용될 수 있다(A타입), 또는 용액상의 아염소산나트륨(NaClO2)을 포함하는 알칼리의 액상규산염(Liquid silicate)에 유기산(Organic acid)을 공급하여 pH 7.0 이하의 산성조건으로 실리카 졸·겔법을 제공하여 이산화염소 방출 소스(Source)가 실리카의 3차원적 망상구조 타입으로 이루어지도록 구성하여 이산화염소 가스가 천천히 방출되는 서방형 키트로 적용될 수 있다(B타입), 또한, 분말상의 아염소산나트륨(NaClO2)으로 구성되는 키트의 경우에는 세라믹 분말을 100중량부로 기준으로 할 때 아아염소산나트륨(Sodium chlorite, NaClO2)은 50 내지 250 중량%로 혼합되도록 구성되어지고, 유기산(Organic acid)은 알칼리의 아염소산나트륨 pH가 7.0 이하로 제공되는 양이 혼합되도록 구성되어지고, 흡습성 물질은 1.5 ~ 4.5 중량%가 혼합되도록 구성되어지고, 추가로 흡습성 물질의 기능 향상을 위해 하이드로겔 고분자가 0.25 내지는 1.0 중량% 혼합되어 이루어지는 이산화염소 소스의 조성물을 이루고 흡습제에 의한 과수봉지 내부의 습기를 흡수하여 흡습상태의 알칼리 아염소산나트륨과 산(Acid)이 산·염기 반응에 의한 pH 7.0 이하의 산성 분위기로 이루어지도록 구성되어 이산화염소 가스가 서서히 방출되는 서방형 키트(C타입) 중에서 하나가 선택되도록 적용될 수 있는 과수봉지를 통하여 본원의 목적을 달성하고자 하는 기술이다. claims: 과수 재배과정 중 병충해로부터 보호를 받기 위해 과수봉지에 있어서,과수봉지 내부에 장기간 이산화염소 가스를 서서히 배출시키기 위한 서방형 키트(Kit)가 내장되어 과수 재배과정 중 병충해로부터 보호받도록 제공되는 것을 특징으로 하는 과수봉지., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

994/1150 Row 994: application_number: 1020200162931, combined_string: invention_title: 셀레늄 함유 백화고의 재배 방법 abstract: 본 발명은 셀레늄 함유 백화고의 재배 방법에 관한 것이고, 구체적으로 재배 과정에서 셀레늄을 흡수하여 백화고 고유의 맛과 셀레늄의 효능이 유지되도록 하는 셀레늄 함유 백화고의 재배 방법에 관한 것이다. 셀레늄 함유 백화고의 재배 방법은 버섯 종균의 접종을 위한 원료를 배합하여 배지를 형성하는 단계; 배지를 멸균하고 접종을 하는 단계; 종균을 배양시키면서 균사의 성장에 따라 배지에 적어도 하나의 구멍을 형성하는 단계; 배지를 가습시키면서 수직 방향의 층에 따라 서로 다른 온도 조건을 설정하는 단계; 및 배지의 포장을 제거하여 습도를 조절하면서 생육시켜 수확하는 단계를 포함한다. claims: 버섯 종균의 접종을 위한 원료를 배합하여 배지를 형성하는 단계; 배지를 멸균하고 접종을 하는 단계; 종균을 배양시키면서 균사의 성장에 따라 배지에 적어도 하나의 구멍을 형성하는 단계; 배지를 가습시키기 위해 배지가 물에 감긴 상태에서 수직 방향의 층에 따라 서로 다른 온도 조건을 설정하는 단계; 및 배지의 포장을 제거하여 습도를 조절하면서 생육시켜 수확하는 단계를 포함하고, 배지는 10 내지 30 wt%의 밀기울; 0.1 내지 15 wt%의 목화씨 껍질; 1 내지 5 wt%의 석고; 10 내지 5000 ppm의 셀레늄 복합체; 및 전체를 100 wt%로 만드는 톱밥 형태의 잡목 부스러기를 포함하고, 가습은 배지 위쪽으로 수면이 형성되도록 하면서 서로 다른 층을 형성하는 위층의 온도가 아래층에 비하여 높은 온도로 유지되는 것을 특징으로 하는 셀레늄 함유 백화고의 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

995/1150 Row 995: application_number: 1020200156367, combined_string: invention_title: 식물 재배 전용 대형 수경 재배 박스 abstract: 본 발명에 따른 식물 재배 전용 대형 수경 재배 박스는 전면과 후면에 출입구가 형성되고, 실내에 식물을 재배하기 위한 재배실과, 상기 재배실의 온도와 습도를 조정하고 상기 재배실로 공급되는 급수량과 광량을 조정하는 제어 장치가 설치된 제어실이 갖추어진 메인 박스와; 상기 재배실 내부 좌우측에 중앙 복도를 사이에 끼고 복층으로 세워지되 각층에는 식물 재배판이 올려지는 복층 선반; 상기 제어실 내부에 설치된 물탱크; 상기 물탱크에 채워진 양액 또는 물을 상기 재배실 내부에서 재배되고 있는 식물로 공급하는 물 공급 수단; 상기 제어실 내부에 설치되되 상기 물 공급 수단을 통해 상기 식물로 공급되는 급수량을 제어하는 급수량 제어 수단; 상기 재배실안으로 수분 미스트를 살포하는 수분 미스트 공급 수단; 상기 수분 미스트 공급 수단을 제어하여 재배실 내 습도를 조정하는 습도 조정 수단; 상기 재배실 천장과, 상기 복층 선반에 구성된 각층 선반 밑면에 설치되어 식물 재배판에 설치된 식물로 빛을 공급하는 빛 공급 수단; 상기 빛 공급 수단을 제어하여 상기 식물에 공급되는 광량을 조절하는 광량 조정 수단; 상기 재배실 내부의 온도를 조정하는 온도 조정 수단; 및 상기 제어실 내부에 설치되되 상기 온도 조정 수단을 제어하여 상기 재배실 내부의 온도를 조정하는 온도 제어 수단을 포함한다. claims: 전면과 후면에 출입구(D)가 형성되고, 실내에 식물을 재배하기 위한 재배실(GR)과, 상기 재배실(GR)의 온도와 습도를 조정하고 상기 재배실(GR)로 공급되는 급수량과 광량을 조정하는 제어 장치가 설치된 제어실(CR)이 갖추어진 메인 박스(1)와;상기 재배실(GR) 내부 좌우측에 중앙 복도를 사이에 끼고 복층으로 세워지되 각층에는 식물 재배판(GP)이 올려지는 복층 선반(2);상기 제어실(CR) 내부에 설치된 물탱크(3);상기 물탱크(3)에 채워진 양액 또는 물을 상기 재배실(GR) 내부에서 재배되고 있는 식물로 공급하는 물 공급 수단(4); 상기 제어실(CR) 내부에 설치되되 상기 물 공급 수단(4)을 통해 상기 식물로 공급되는 급수량을 제어하는 급수량 제어 수단(5);상기 재배실(GR)안으로 수분 미스트를 살포하는 수분 미스트 공급 수단(6);상기 수분 미스트 공급 수단(6)을 제어하여 재배실(GR) 내 습도를 조정하는 습도 조정 수단(7); 상기 재배실(GR) 천장과, 상기 복층 선반(2)에 구성된 각층 선반(21) 밑면에 설치되어 식물 재배판(GP)에 설치된 식물로 빛을 공급하는 빛 공급 수단(8);상기 빛 공급 수단(8)을 제어하여 상기 식물에 공급되는 광량을 조절하는 광량 조정 수단(9);상기 재배실(GR) 내부의 온도를 조정하는 온도 조정 수단(T1);및 상기 제어실(CR) 내부에 설치되되 상기 온도 조정 수단(T1)을 제어하여 상기 재배실(GR) 내부의 온도를 조정하는 온도 제어 수단(T2)을 포함하며,상기 물 공급 수단(4)은 양수기(51)를 통해 물탱크(3)에 채워진 양액 또는 물을 공급받는 물 공급 메인 배관(41)과, 상기 복층 선반(2)을 구성하는 각층 선반(21)에 각각 설치되고 상기 물 공급 메인 배관(41)으로부터 분기 설치되어 상기 물 공급 메인 배관(41)으로부터 전달된 양액 또는 물을 전달받는 물 공급 분기 배관(42), 상기 물 공급 분기 배관(42)의 측부 둘레면에 형성되어 물 공급 분기 배관(42)을 통해 전달된 양액 또는 물을 상기 물 공급 분기 배관(42) 바깥으로 내보내는 물 배출구(43), 및 상기 물 배출구(43)에 1 대 1로 설치되어 상기 물 배출구(43)의 통로를 개방하거나 폐쇄하여 상기 물 배출구(43)를 통해 양액 또는 물이 배출되도록 하거나 배출되지 않도록 하는 물 공급 밸브(44)를 포함하고,상기 물 공급 분기 배관(42)은 상기 식물 재배판(GP)안으로 물이나 양액을 전달하는 하부 물 공급 분기 배관과, 상기 식물 재배판(GP) 상부에서 상기 식물 재배판(GP)에서 재배되고 있는 식물로 물이나 양액을 공급하는 상부 물 공급 분기 배관을 포함하며,상기 급수량 제어 수단(5)은 상기 물탱크(3)에 채워진 양액 또는 물을 퍼올려 토출구를 통해 상기 물 공급 메인 배관(41)으로 전달하는 양수기(51)와;상기 물 공급 분기 배관(42)의 입구에 각각 설치되어 중앙 급수 제어반(54)의 제어 신호에 따라 상기 물 공급 분기 배관(42)의 입구를 개방하거나 폐쇄하여 상기 물 공급 메인 배관(41)을 통해 전달된 양액 또는 물을 물 공급 분기 배관(42)으로 전달하거나 차단하는 솔레노이드 밸브(52);상기 양수기(51)가 작동되는 시간 간격과 양수기(51) 구동시 양수기(51)가 구동되는 시간을 설정하는 타이머(53)(Timer);및 상기 타이머(53)에 설정된 시간 간격으로 일정 시간동안 양수기(51)를 구동시키고 각각의 물 공급 분기 배관(42)에 설치된 솔레노이드 밸브(52)를 선택적으로 개폐하는 중앙 급수 제어반(54)을 포함하는 것을 특징으로 하는 식물 재배 전용 대형 수경 재배 박스., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

996/1150 Row 996: application_number: 1020200137536, combined_string: invention_title: 복합 제어 스마트팜 시스템 abstract: 본 발명은 복합 제어 스마트팜 시스템에 관한 것이다. 본 발명에 따른 복합 제어 스마트팜 시스템은 스마트팜 운영에 필요한 장치 및 센서로 구성되며, 장치 구역 및 센서 구역으로 독립적으로 분리되는 MCU 클라이언트 및 MCU 클라이언트에 대한 통합 관리를 수행하는 웹 서버를 포함한다. claims: 스마트팜 운영에 필요한 장치 및 센서로 구성되며, 장치 구역 및 센서 구역으로 독립적으로 분리되는 MCU 클라이언트; 및상기 MCU 클라이언트에 대한 통합 관리를 수행하는 웹 서버를 포함하고, 상기 장치 구역으로는 동일한 장치 제어 기능을 수행하지만 장치 장애 극복 시에만 작동하는 구역이 등록되어, 해당 MCU 보드는 평상시 대기 상태의 명령을 받다가 1차 장비에 장애가 발생 시, 2차 장비를 구동시키고,상기 MCU 클라이언트는 상기 장치 구역의 경우, 상기 웹 서버로 농장 ID, 농장 앱키, 장치 구역 ID, 맥 어드레스를 포함하는 장치 구역 정보 요청을 전송하고, 상기 웹 서버로부터 장치 구동에 필요한 장치 ID, 장치 타입, 작동값, 개폐량, 증감치를 포함한 장치 구역 정보 응답을 수신하면 상기 장치 구역 정보 응답을 필터링하여 장치 개수를 판정하고, 장치 ID 일치 여부 확인에 따라 장치 타입 별로 기설정된 스펙에 따라 구동을 수행하고, 농장 ID, 농장 앱키, 장치 구역 ID, 장치 ID, 작동 결과값을 포함하는 상태 정보를 상기 웹 서버의 객체관계형 데이터베이스로 전송하여 업데이트하고,상기 웹 서버는 제1 장비를 제1 시간 이내에 완전 개방시키는 제1 구동 액추에이터와, 제2 장비를 상기 제1 시간보다 긴 시간인 제2 시간 이내에 완전 개방시키는 제2 구동 액추에이터의 구동 여부를 결정함에 있어서, 상기 제1 구동 액추에이터 및 제2 구동 액추에이터의 장비 구동에 관한 능력 정보를 고려하여, 상기 MCU 클라이언트로 목표 완수를 위한 명령 신호를 전송하여 상기 능력 정보가 상대적으로 높은 상기 제1 구동 액추에이터를 구동시키고, 예비적으로 상기 제2 구동 액추에이터를 대기시키며, 상기 제1 구동 액추에이터의 구동 시점으로부터 기설정 시간이 지난 시점에서의 기설정된 목표 달성 추이를 확인하여, 목표 달성 추이가 원만한 것으로 확인하면 상기 제1 구동 액추에이터의 구동을 유지시키고, 상기 제2 구동 액추에이터의 대기를 유지하며, 목표 달성 추이가 원만하지 않은 것으로 확인하면 상기 제1 구동 액추에이터의 구동을 유지시키고, 상기 제2 구동 액추에이터를 구동시키며,상기 웹 서버는 기준 환경값과의 허용되는 차이값인 여유값의 적용 여부에 따라 작동 조건의 만족 여부를 확인한 결과에 따라 장치의 작동 및 대기를 결정하되, 상기 여유값의 적용 여부가 선택되지 않은 경우 상기 기준 환경값을 고려하여 상기 작동 조건의 만족 여부를 확인하는 것인 복합 제어 스마트팜 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

997/1150 Row 997: application_number: 1020200128258, combined_string: invention_title: 푸른곰팡이 발생 저감형 버섯 양압재배사 abstract: 본 발명은 푸른곰팡이 발생 저감형 버섯 양압재배사에 관한 것으로, 보다 상세하게는 내부 환경을 제어하여 푸른곰팡이의 발생을 억제함으로써 버섯의 재배가 용이한 푸른곰팡이 발생 저감형 버섯 양압재배사에 관한 것이다.본 발명의 푸른곰팡이 발생 저감형 버섯 양압재배사는, 냉각수조 및 난방수조가 설치되는 준비실과 재배대가 설치되는 재배실로 구획되는 본체; 상기 재배실 바닥에 설치되고, 상기 냉각수조에 저장되어 있는 냉수에 의해 냉각되는 냉풍 또는 상기 난방수조에 저장되어 있는 온수에 의해 가열된 온풍이 토출되어 상기 재배실의 온도를 조절하는 송풍관; 상기 재배실에 설치되어 상기 재배실 내부공기가 외부로 배출되는 배기구; 상기 배기구에 설치되어 상기 재배실로 외부공기가 유입되는 것을 차단하는 체크밸브; 상기 재배실의 양측 벽면에 설치되고, 상기 재배실 상부 공기를 흡입하여 상기 재배실 하부로 배출시키는 씨형(C-type) 순환장치; 상기 재배실의 습도를 조절하는 복수의 습도조절장치; 상기 재배실 상부에 설치되는 유브이램프를 포함하여 이루어지고, 상기 재배실 내부는 압력 10Pa이상, 온도 20~30℃, 습도 70~90%RH로 유지되는 것을 특징으로 한다. claims: 냉각수조 및 난방수조가 설치되는 준비실과 재배대가 설치되는 재배실로 구획되는 본체;상기 재배실 바닥에 설치되고, 상기 냉각수조에 저장되어 있는 냉수에 의해 냉각되는 냉풍 및 상기 난방수조에 저장되어 있는 온수에 의해 가열된 온풍이 선택적으로 토출되어 상기 재배실의 온도를 조절하는 송풍관;상기 재배실에 설치되어 상기 재배실 내부공기가 외부로 배출되는 배기구;상기 배기구에 설치되어 상기 재배실로 외부공기가 유입되는 것을 차단하는 체크밸브;상기 재배실의 양측 벽면에 설치되고, 상기 재배실 상부 공기를 흡입하여 상기 재배실 하부로 배출시키는 씨형(C-type) 순환장치; 상기 재배실의 습도를 조절하는 복수의 습도조절장치; 및상기 재배실 상부에 설치되는 유브이램프를 포함하며,상기 준비실과 상기 재배실 사이에는 출입을 위한 도어가 설치되어 있고,상기 재배실의 내부는 압력 10Pa이상, 온도 20~30℃, 습도 70~90%RH로 유지되는 것을 특징으로 하는 푸른곰팡이 발생 저감형 버섯 양압재배사., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

998/1150 Row 998: application_number: 1020200120453, combined_string: invention_title: 수경 재배 블록 abstract: 본 발명은 수생 식물을 생육할 수 있는 수경 재배 블록에 관한 것이다. 본 발명에 따른 수경 재배 블록은 바닥판 및 상기 바닥판과 수직하게 형성되며 개구가 형성된 복수의 측면판을 포함하여 내부에 수납 공간이 형성되는 블록 몸체, 블록 몸체의 내부 공간에 바닥판과 수직하게 형성되며, 바닥판을 관통하여 형성되는 복수의 홀을 수용하여, 블록 몸체에 오버플로우된 유체를 복수의 홀로 균등하게 배출하도록 하는 오버플로우 격벽을 포함한다. claims: 바닥판 및 상기 바닥판과 수직하게 형성되며 개구가 형성된 복수의 측면판을 포함하여 내부에 수납 공간이 형성되는 블록 몸체;상기 블록 몸체의 내부 공간에 상기 바닥판과 수직하게 형성되며, 상기 바닥판을 관통하여 형성되는 복수의 홀을 수용하여, 상기 블록 몸체에 오버플로우된 유체를 상기 복수의 홀로 균등하게 배출하도록 하는 오버플로우 격벽; 을 포함하고,상기 바닥판의 하부면에는 상기 복수의 홀로부터 연장되는 중공이 형성되고, 하부로 각각 돌출되어 형성되는 복수의 분배관이 형성되고,상기 복수의 분배관에 결합되어 적어도 하나의 다른 수경 재배 블록에 오버플로우된 유체를 분배하는 배관;을 포함하는 것을 특징으로 하는 수경 재배 블록., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

999/1150 Row 999: application_number: 1020200120454, combined_string: invention_title: 수경 재배 장치 abstract: 본 발명은 수생 식물을 생육할 수 있는 수경 재배 장치에 관한 것이다. 본 발명에 따른 수경 재배 장치는 바닥판 및 상기 바닥판과 수직하게 형성되며 개구가 형성된 복수의 측면판을 포함하여 내부에 수납 공간이 형성되는 적어도 하나의 블록 몸체, 블록 몸체로부터 오버플로우된 유체를 공급받아 저장하고, 최상부에 배치된 블록 몸체에 유체를 공급하는 수조, 블록 몸체의 하부에 결합되며, 수조가 배치될 공간을 형성하는 받침대를 포함한다. claims: 바닥판 및 상기 바닥판과 수직하게 형성되며 개구가 형성된 복수의 측면판을 포함하여 내부에 수납 공간이 형성되는 적어도 하나의 블록 몸체;상기 블록 몸체로부터 오버플로우된 유체를 공급받아 저장하고, 최상부에 배치된 블록 몸체에 유체를 공급하는 수조;상기 블록 몸체의 하부에 결합되며, 상기 수조가 배치될 공간을 형성하는 받침대; 를 포함하고,상기 블록 몸체는 하부면에 상기 받침대와 결합되는 결합부가 형성되고,상기 받침대는 상부면에 상기 결합부와 대응되는 형상으로 제1 결합홈과, 측면 및 저면에는 다른 받침대와의 결합을 위한 제2 결합홈 및 제3 결합홈이 형성되어 상기 블록 몸체에 결합되고,상기 제2 결합홈 또는 상기 제3 결합홈에 결합되어 서로 다른 받침대를 연결하는 연결구;를 포함하는 것을 특징으로 하는 수경 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1000/1150 Row 1000: application_number: 1020200119103, combined_string: invention_title: 다년생 수삼 수경재배장치 abstract: 본 발명은 3~5년생의 다년생 수삼(뿌리)을 묘삼으로 하고, 이를 양액을 사용하여 다량의 유용한 성분을 함유하고 있는 줄기와 잎사귀 키워낼 수 있도록 하기 위한 다년생 수삼 수경재배장치에 관한 것이다.이러한 본 발명인 다년생 수삼 수경재배장치는 소정의 거리로 이동하여 작업자의 이동통로(R)를 변경할 수 있도록 하측에 수조용 프레임 이동수단이 구비된 다수의 수경수조용 프레임과; 상기 수경수조용 프레임에 소정의 간격으로 설치되는 다수의 수삼재배용 수조와, 상기 수삼재배용 수조 상측에 설치되어 다년생 수삼이 재식되는 슬라이더형 수삼재배판과, 상기 수삼재배용 수조 내에 구비되어 재식된 수삼의 뿌리에 양액을 분사하는 양액분사장치를 포함하되, 상기 슬라이더형 수삼재배판이 수삼재배용 수조의 일측으로 슬라이드하여 일부분이 배출될 수 있도록 이루어진 수삼 수경재배용 수조장치와; 상기 양액분사장치에서 양액이 분사될 수 있도록 소정의 압력으로 양액을 공급하도록 이루어진 양액공급장치와; 상기 수삼 수경재배용 수조장치에 재직된 수삼의 성장에 보조역할을 하는 성장보조장치와; 상기 양액공급장치와 성장보조장치를 제어할 수 있는 제어장치를 포함하도록 이루어진다. claims: 소정의 거리로 이동하여 작업자의 이동통로(R)를 변경할 수 있도록 하측에 수조용 프레임 이동수단(120)이 구비된 다수의 수경수조용 프레임(100)과; 상기 수경수조용 프레임(100)에 소정의 간격으로 설치되는 다수의 수삼재배용 수조(240)와, 상기 수삼재배용 수조(240) 상측에 설치되어 다년생 수삼이 재식되는 슬라이더형 수삼재배판(220)과, 상기 수삼재배용 수조(240) 내에 구비되어 재식된 수삼의 뿌리에 양액을 분사하는 양액분사장치(250)를 포함하되, 상기 슬라이더형 수삼재배판(220)이 수삼재배용 수조(240)의 일측으로 슬라이드하여 일부분이 배출될 수 있도록 이루어진 수삼 수경재배용 수조장치(200)와; 상기 양액분사장치(250)에서 양액이 분사될 수 있도록 소정의 압력으로 양액을 공급하도록 이루어진 양액공급장치(300)와; 상기 수삼 수경재배용 수조장치(200)에 재직된 수삼의 성장에 보조역할을 하는 성장보조장치(400)와; 상기 양액공급장치(300)와 성장보조장치(400)를 제어할 수 있는 제어장치(500)를 포함하는 한편,상기 수삼 수경재배용 수조장치(200)는,다년생 수삼(G)을 고정할 수 있는 수삼홀더장치(210)와; 상기 수삼홀더장치에 각각 고정된 다수의 수삼을 소정의 간격을 유지할 수 있도록 다수의 수삼용 재식홀(221a)이 형성된 슬라이더형 수삼재배판(220)과; 상기 슬라이더형 수삼재배판의 양측부분을 이동할 수 있게 지지하도록 이루어진 수삼재배판용 가이드대(230)와; 상기 수삼재배판용 가이드대가 소정의 간격으로 상측에 구비되며, 일측으로 수삼재배판용 가이드대(230)를 따라 이동하는 슬라이더형 수삼재배판의 일부분이 외측으로 출입할 수 있도록 출입용 개구부(241)가 일측면에 형성되어 있는 수삼재배용 수조(240)와; 상기 수삼재배용 수조 내에 위치하여 양액을 분사하여 수삼에 양액을 공급하도록 이루어진 양액분사장치(250)와; 상기 슬라이더형 수삼재배판(220)의 일부분이 출입할 수 있도록 형성된 출입용 개구부(241)를 덮는 한편, 감시창 기능을 하는 측면 덮개판(260)을 포함함을 특징으로 하는 다년생 수삼 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1001/1150 Row 1001: application_number: 1020200119108, combined_string: invention_title: 수경재배용 이산화탄소 공급장치를 구비하는 다년생 수삼 수경재배장치 abstract: 본 발명은 수경재배가 이루어지는 수경재배실 내에 수경재배시 이산화탄소(CO2) 농도가 낮아짐으로써 발생하는 문제점을 해결하고자 적절한 이산화탄소(CO2) 농도가 유지될 수 있도록 이산화탄소(CO2)를 공급할 수 있도록 이루어진 수경재배용 이산화탄소 공급장치 및 이를 구비하는 다년생 수삼 수경재배장치에 관한 것이다.이러한 본 발명인 수경재배용 이산화탄소 공급장치는 탄산솔을 수용할 수 있도록 내부공간을 가지는 외부몸체와; 상기 내부공간에 교체가능하도록 삽설되는 탄산솔을 저장하며, 열전도율이 높도록 금속재질로 이루어지며, 상부가 개구된 형태로 이루어진 탄산솔 저장용기와; 상기 탄산솔 저장용기의 하측부분을 감싸도록 이루어지며, 일측부분에 발열을 위한 발열장치가 형성되어 있는 탄산솔 저장용기 가열부재와; 상기 내부공간의 상부에 설치되어 탄산솔에 태양광을 대신하는 빛을 조사할 수 있도록 이루어진 탄산솔 조명장치를 포함하는 성장보조용 이산화탄소 공급장치로 이루어진다. claims: 수경재배실에 설치되는 다수의 수경수조용 프레임(100)과;상기 수경수조용 프레임(100)에 소정의 간격으로 설치되는 다수의 수삼재배용 수조(240)와, 상기 수삼재배용 수조(240) 상측에 설치되어 다년생 수삼이 재식되는 슬라이더형 수삼재배판(220)과, 상기 수삼재배용 수조(240) 내에 구비되어 재식된 수삼의 뿌리에 양액을 분사하는 양액분사장치(250)를 포함하되, 상기 슬라이더형 수삼재배판(220)이 수삼재배용 수조(240)의 일측으로 슬라이드하여 일부분이 배출될 수 있도록 이루어진 수삼 수경재배용 수조장치(200)와;상기 양액분사장치(250)에서 양액이 분사될 수 있도록 소정의 압력으로 양액을 공급하도록 이루어진 양액공급장치(300)와;상기 수삼 수경재배용 수조장치(200)에 재직된 수삼의 성장에 보조역할을 하는 성장보조장치(400)와;상기 양액공급장치(300)와 성장보조장치(400)를 제어할 수 있는 제어장치(500)를 포함하는 한편,상기 성장보조장치(400)는 탄산솔(422)을 수용할 수 있도록 내부공간(421a)을 가지는 외부몸체(421)와; 상기 내부공간(421a)에 교체가능하도록 삽설되는 탄산솔(422)을 저장하며, 열전도율이 높도록 금속재질로 이루어지며, 상부가 개구된 형태로 이루어진 탄산솔 저장용기(423)와; 상기 탄산솔 저장용기(423)의 하측부분을 감싸도록 이루어지며, 일측부분에 발열을 위한 발열장치(424a)가 형성되어 있는 탄산솔 저장용기 가열부재(424)와; 상기 내부공간(421a)의 상부에 설치되어 탄산솔(422)에 태양광을 대신하는 빛을 조사할 수 있도록 이루어진 탄산솔 조명장치(425)를 포함하는 성장보조용 이산화탄소 공급장치(420)로 이루어지는 수경재배용 이산화탄소 공급장치를 포함함을 특징으로 하는 수경재배용 이산화탄소 공급장치를 구비하는 다년생 수삼 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1002/1150 Row 1002: application_number: 1020200095347, combined_string: invention_title: 식물 재배 장치 abstract: 본 발명은 식물 재배 장치에 관한 것으로, 전기 분사 모듈을 이용하여 양액을 미세 액적 상태로 분사 공급함으로써, 양액 입자의 크기가 매우 미세하고 이온화된 상태로 형성되어 배지에서 재배되는 식물의 뿌리에 대한 흡수량 및 흡수율이 증가하며, 양액 입자의 부유 시간이 증가하여 식물의 뿌리에 지속적으로 흡수되고 이에 따라 외부로 배출되어 버려지는 양을 최소화할 수 있어 더욱 효율적으로 사용 관리될 수 있고, 이온화된 미세 액적에 의한 살균 기능을 통해 메인 케이스 내부 공간에 대한 살균 기능을 수행하여 세균 번식을 억제하고 이끼 및 녹조 발생을 방지하며, 별도의 압력 분사 모듈을 추가하여 이들을 다양한 방식으로 작동 제어함으로써, 양액 공급 기능 및 살균 기능을 동시에 최적의 상태로 수행할 수 있는 식물 재배 장치를 제공한다. claims: 상부에 식물을 재배할 수 있는 배지가 고정 장착되는 메인 케이스;양액 저장 챔버로부터 양액을 공급받고, 공급받은 양액을 전위차에 의한 전기력을 이용하여 상기 메인 케이스의 내부 공간에 미세 액적 상태로 분사하는 전기 분사 모듈;상기 양액 저장 챔버로부터 양액을 공급받고, 공급받은 양액을 압력을 통해 상기 메인 케이스 내부 공간에 분사하는 압력 분사 모듈; 및상기 전기 분사 모듈 및 압력 분사 모듈의 작동 상태를 동작 제어하는 제어부를 포함하고, 상기 제어부는 상기 전기 분사 모듈이 제 1 주기마다 작동하도록 동작 제어하고, 상기 압력 분사 모듈은 상기 제 1 주기와는 다른 제 2 주기마다 작동하도록 동작 제어하며,사용자가 제 1 작동 모드, 제 2 작동 모드 및 제 3 작동 모드를 선택할 수 있도록 별도의 선택 조작부가 구비되고,상기 제 1 작동 모드가 선택된 경우, 상기 제어부에 의해 상기 제 1 주기가 상기 제 2 주기보다 더 길게 설정되고, 상기 제 2 작동 모드가 선택된 경우, 상기 제어부에 의해 상기 제 2 주기가 상기 제 1 주기보다 더 길게 설정되며,상기 제 3 작동 모드가 선택된 경우, 상기 제어부는 상기 제 3 작동 모드가 선택된 시간 동안 상기 전기 분사 모듈이 상기 제 1 주기마다 작동하고 상기 압력 분사 모듈은 작동 정지하도록 동작 제어하는 것을 특징으로 하는 식물 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1003/1150 Row 1003: application_number: 1020200043029, combined_string: invention_title: 수경재배용 배드 조립체 abstract: 본 발명은 길이 방향으로 연장 설치되어 강직도와 물높이를 균일하게 형성할 수 있도록 구현한 수경재배용 배드 조립체에 관한 것으로, 정식판이 안착되기 위한 배양액이 수용될 수 있도록 길이 방향으로 연결 형성되는 적어도 하나 이상의 연결부;를 포함한다. claims: 정식판이 안착되기 위한 배양액이 수용될 수 있도록 길이 방향으로 연결 형성되는 적어도 하나 이상의 연결부;상기 연결부의 전단에 연결 설치되는 제1 마감부; 및 상기 연결부의 후단에 연결 설치되는 제2 마감부;를 포함하며,상기 연결부는,사각 평판 형태로 형성되는 바닥면;내부 공간에 배양액을 수용할 수 있도록 상기 바닥면의 일측 및 다른 일측으로부터 상측 직각 방향으로 절곡되어 연장 형성되는 측면;상기 바닥면의 전단 상측에 형성되어 다른 연결부의 후단 하측에 체결되거나, 상기 제1 마감부의 후단 하측에 체결되는 전단 체결부; 및상기 바닥면의 후단 하측에 형성되어 다른 연결부의 전단 체결부에 체결되거나, 상기 제2 마감부의 전단 상측에 체결되는 후단 체결부;를 포함하며,상기 제1 마감부는,상기 전단 체결부에 체결될 수 있도록 상기 전단 체결부와 대향하는 후단 하측에 상기 후단 체결부와 동일할 형태의 체결 구조를 형성하며,상기 제2 마감부는,상기 후단 체결부에 체결될 수 있도록 상기 후단 체결부와 대향하는 후단 상측에 상기 전단 체결부와 동일할 형태의 체결 구조를 형성하며,상기 전단 체결부는,상기 바닥면의 전단 상측면을 따라 좌우 방향으로 하측으로 단차지도록 연장 형성되는 상부 안착턱;상기 상부 안착턱을 따라 좌우 방향으로 서로 이격되어 다수 개가 형성되는 상부 체결홈; 및상기 상부 체결홈과 다른 상부 체결홈 사이에 상측으로 둔턱 형태로 돌출 형성되는 상부 체결턱;을 포함하며,상기 상부 체결홈은,골과 이랑이 반복하여 형성되는 요철부; 및상기 요철부의 후단을 따라 좌우 방향으로 상기 요철부보다 하측으로 함몰되어 연장 형성되는 걸림부;를 포함하며,상기 후단 체결부는,다른 연결부의 전단 체결부에 안착되어 체결될 수 있도록 다른 연결부의 전단 체결부의 형태에 대응하는 형상으로 상기 바닥면의 후단 하측면이 형성되며, 상기 연결부는,일정한 간격으로 좌우 방향으로 서로 이격되어 다수 개가 형성되며, 상기 바닥면을 따라 전후 방향으로 연장 형성되는 유도홈;일정한 간격으로 전후 방향으로 서로 이격되어 다수 개가 형성되며, 상기 유도홈의 하측면을 통해 상측이 노출될 수 있도록 상측이 상기 유도홈의 하측면과 대향하는 깊이로 상기 바닥면을 좌우 수평 방향으로 관통하고 형성되는 수평 관통홈; 및사각 각관 형태로 형성되어 상기 수평 관통홈 마다 삽입되며, 상측면을 따라 절개홈이 좌우 수평 방향으로 연장 형성되어 상기 유도홈의 하측면을 통해 개방된 상기 수평 관통홈의 상측을 통해 외부 공기 공급 장치를 공해 공급되는 공기를 배출하는 공기 공급관;을 더 포함하며,상기 유도홈의 상측을 따라 다수 개가 설치되며, 상기 공기 공급관을 통해 배출되는 공기를 통해 구동되어 상기 유도홈을 따라 상기 연결부에 수용된 배양액이 흘러가도록 유속을 형성시키는 유속 형성부;를 더 포함하며,상기 유속 형성부는,상기 공기 공급관으로부터 후단으로 이격되어 상기 유도홈의 일측 및 다른 일측 벽체의 상측에서 쌍을 이루며 형성되는 두 개의 체결홈;상기 체결홈에 삽입 체결되는 두 개의 체결블록; 및상기 두 개의 체결블록 사이에 회전 가능하도록 연결 설치되며, 상기 유도홈에 수용되어 있는 배양액이 상기 유도홈을 따라 흐를 수 있도록 상기 공기 공급관을 통해 배출되는 공기를 통해 회전하면서 상기 유도홈에 수용되어 있는 배양액을 저어 주는 물레방아;를 포함하며,상기 제1 마감부 또는 상기 제2 마감부는,상기 유도홈으로부터 연장 형성되는 추가 유도홈; 및상기 유도홈으로부터 상기 추가 유도홈으로 흘러 유입되는 배양액을 상측 방향으로 승강시켜 줄 수 있도록 회전하는 승강 유도 물레방아;를 포함하는, 상기 공기 공급관으로부터 전단으로 이격되어 상기 유도홈의 일측 및 다른 일측 벽체에 각각 설치되며, 상기 물레방아가 회전함에 따라 발생되는 구동력을 이용하여 회전하여 상기 유속 형성부에 의해 상기 유도홈을 따라 흐르는 배양액의 유속을 증가시켜 주는 유속 가속부;를 더 포함하는, 수경재배용 배드 조립체., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1004/1150 Row 1004: application_number: 1020200023077, combined_string: invention_title: 분무경재배용 분무화 수단 및 이를 포함하는 분무경재배 시스템 abstract: 본 발명은 분무경재배에 필요한 양액 및 관수의 액상 물질을 분무화하여 분무경재배 작물의 근부에 안정적이고 지속적이며 효율적으로 제공할 수 있도록 하고, 이에 따라 건강하고 균질한 분무경재배 작물을 양산할 수 있어 농가 소득 향상을 도모할 수 있는 분무경재배용 분무화 수단 및 이를 포함하는 분무경재배 시스템에 관한 것이다. 본 발명에 따르면, 분무경재배 작물이 식재되는 하나 이상의 분무경재배작물 식재부재; 상기 분무경재배작물 식재부재에 식재되는 분무경재배 작물의 근부에 양액 및 수분 중 적어도 하나의 액상 물질을 분무화하여 제공하도록 구성되는 분무화 수단; 상기 분무화 수단에 상기 액상 물질을 공급하도록 구성되는 양액 및 수분 공급 수단; 상기 분무경재배작물 식재부재에 구비되어 분무경재배 작물의 생육에 영향을 미치는 인자를 검출하도록 구성되는 센서 모듈; 및 상기 센서 모듈로부터의 검출 신호를 제공받아 관련 제어를 실행하며, 상기 분무화 수단과 상기 양액 및 수분 공급 수단의 작동을 제어하도록 구성되는 제어반;을 포함하는 것을 특징으로 하는 분무경재배 시스템이 제공된다. claims: 분무경재배용 분무화 장치로서,양액 및 수분 중 적어도 하나의 분무화 할 액상 물질이 공급되는 관형 라인;상기 관형 라인에 소정 간격을 갖고 구비되며, 상기 액상 물질을 분무화하는 진동자를 포함하여 상기 관형 라인 외측으로 분무화하는 초음파 모듈; 및상기 관형 라인 내의 액상 물질을 상기 초음파 모듈의 진동자 측으로 제공하도록 구성되는 양액-수분 전달 수단;을 포함하고,상기 관형 라인은 일단부가 폐쇄되고 타단부는 상기 액상 물질이 공급되는 공급 라인에 연결되는 플렉시블한 튜브형 라인으로 형성되며,상기 양액-수분 전달 수단은 상기 초음파 모듈의 진동자를 구성하되 환형으로 형성되는 환형부 및 상기 환형부의 중앙부를 형성하며 미세 기공이 복수 형성되는 액적 형성부로 이루어지며,상기 액적 형성부는 상기 환형부보다 상대적으로 얇은 다이아프램(diaphragm) 형태로 이루어지는 것을 특징으로 하는분무경재배용 분무화 장치.청구항 제1항에 따른 분무경재배용 분무화 장치를 포함하는 것을 특징으로 하는분무경재배 시스템.분무경재배 작물이 식재되는 하나 이상의 분무경재배작물 식재부재;상기 분무경재배작물 식재부재에 식재되는 분무경재배 작물의 근부에 양액 및 수분 중 적어도 하나의 액상 물질을 분무화하여 제공하도록 구성되는 분무화 수단;상기 분무화 수단에 상기 액상 물질을 공급하도록 구성되는 양액 및 수분 공급 수단;상기 분무경재배작물 식재부재에 구비되어 분무경재배 작물의 생육에 영향을 미치는 인자를 검출하도록 구성되는 센서 모듈; 및상기 센서 모듈로부터의 검출 신호를 제공받아 관련 제어를 실행하며, 상기 분무화 수단과 상기 양액 및 수분 공급 수단의 작동을 제어하도록 구성되는 제어반;을 포함하고,상기 분무경재배작물 식재부재는 원형 또는 다각형의 단면을 갖는 관형 바디, 및 상기 관형 바디에 소정 간격을 갖고 형성되어 분무경재배 작물이 식재되는 식재 구멍으로 이루어지고,상기 분무화 수단은 상기 분무경재배작물 식재부재의 관형 바디 내부를 통과하며 상기 양액 및 수분 공급 수단로부터 공급되는 액상물질을 제공받는 양액 및 수분 공급 관형 라인과, 상기 양액 및 수분 공급 관형 라인에 소정 간격을 갖고 구비되어 상기 액상 물질을 분무화하되, 진동자가 외부로 노출되게 구비되는 초음파 모듈, 및 상기 양액 및 수분 공급 관형 라인 내의 액상 물질을 상기 초음파 모듈의 진동자 측으로 제공하도록 구성되는 양액-수분 전달 수단을 포함하고,상기 양액 및 수분 공급 관형 라인은, 일단부가 폐쇄되고 타단부는 상기 양액 및 수분 공급 수단의 공급 라인에 연결되는 플렉시블한 튜브형 라인으로 형성되며,상기 양액-수분 전달 수단은 상기 초음파 모듈의 진동자를 구성하되 환형으로 형성되는 환형부 및 상기 환형부의 중앙부를 형성하며 미세 기공이 복수 형성되는 액적 형성부로 이루어지며,상기 액적 형성부는 상기 환형부보다 상대적으로 얇은 다이아프램(diaphragm) 형태로 이루어지는 것을 특징으로 하는분무경재배 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1005/1150 Row 1005: application_number: 1020200014021, combined_string: invention_title: 태양의 일출과 일몰을 재현한 재배 장치 abstract: 태양의 일출과 일몰을 재현하기 위한 재배 장치가 제공된다. 실내 수직형 농장에 이용되는 재배 장치는 식물이 배치되어 생장하는 바닥 영역; 상기 바닥 영역에 대면하도록 형성된 천정 영역; 상기 바닥 영역에 대면하도록 상기 천정 영역에 부착된 레일; 상기 레일 상에 부착된 상태로 미리 정해진 방향을 따라 이동하는 광원 어레이; 및 상기 재배 장치를 제어하는 컨트롤러로서, 상기 광원 어레이가 상기 레일 상에서 이동하도록 제어하는 것인, 컨트롤러를 포함하고, 상기 광원 어레이가 상기 레일 상에서 이동함에 따라 상기 광원 어레이로부터 상기 바닥 영역까지의 거리 또는 상기 광원 어레이와 상기 바닥 영역이 이루는 각도 중 적어도 하나가 변경된다. claims: 실내 수직형 농장에 이용되는 재배 장치에 있어서,식물이 배치되어 생장하는 바닥 영역;상기 바닥 영역에 대면하도록 형성된 천정 영역;상기 천정 영역과 상기 바닥 영역 사이에 배치되어 일 방향으로 연장되고, 적어도 일부에 굴곡이 형성되는 레일;상기 천정 영역과 상기 레일 사이를 연결하는 방향으로 연장되어 양 단이 상기 천정 영역과 상기 레일 사이에 각각 결합되고, 그 연장길이가 가변 가능하게 구성되며, 상기 레일의 연장방향 따라 배치되는 복수의 리프터; 상기 레일 상에 부착된 상태로 미리 정해진 방향을 따라 이동하는 광원 어레이; 상기 천정 영역에 인접하게 위치하여 상기 바닥 영역 상의 상기 식물을 촬용하는 카메라 및 상기 식물과의 거리를 측정하는 거리 센서; 및상기 재배 장치를 제어하는 컨트롤러로서, 상기 광원 어레이가 상기 레일 상에서 이동하도록 제어하고, 복수의 상기 리프터 각각의 연장길이를 개별적으로 제어하는 컨트롤러를 포함하고,상기 레일에 형성된 굴곡으로 인하여, 상기 광원 어레이가 상기 레일 상에서 이동함에 따라 상기 광원 어레이로부터 상기 바닥 영역까지의 거리 또는 상기 광원 어레이와 상기 바닥 영역이 이루는 각도 중 적어도 하나가 변경되며,상기 컨트롤러는 상기 카메라의 촬영 결과 또는 상기 거리 센서의 측정된 거리에 기초하여 상기 식물의 생장 정도를 산출하여, 상기 식물의 생장 정도에 따라 상기 레일의 굴곡이 조절되거나 상기 바닥 영역으로부터 상기 레일이 위치한 높이가 조절되도록 복수의 상기 리프터 각각의 연장길이를 개별적으로 제어하고,상기 컨트롤러는 상기 카메라의 촬영 결과에 기초하여 상기 식물의 종류를 파악하여, 상기 파악된 식물의 종류에 따라 상기 광원 어레이의 RGB값을 변경하는 것인, 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1006/1150 Row 1006: application_number: 1020200001487, combined_string: invention_title: 수경재배용 나노복합체 배지 및 이의 제조방법 abstract: 본 발명은 다공성 배지에 수소처리된 광촉매가 코팅된 것을 특징으로 하는 수경재배용 나노복합체 배지 및 제조방법에 관한 것이다. claims: 다공성 배지에 수소처리된 광촉매가 코팅된 것을 특징으로 하는 수경재배용 나노복합체 배지.다공성 배지를 준비하는 단계;광촉매 나노분말을 수소처리하는 단계; 및상기 다공성 배지에 상기 수소처리된 광촉매를 코팅하는 단계를 포함하는 수경재배용 나노복합체 배지의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1007/1150 Row 1007: application_number: 1020190178964, combined_string: invention_title: 조립구조를 갖는 실내용 스마트 수경재배시스템 abstract: 본 발명은 조립구조를 갖는 실내용 스마트 수경재배시스템에 관한 것으로, 보다 상세하게는, 고정수단(10), 광원공급부(20), 수경재배기(30), 고임물통(40), 양액통(50), 연결관(60), 팬(70), 제어부(80), 솔라패널(90)로 구성되어, 실내에 설치하여 식물을 수경재배하되, 제어부를 통해 광원공급, 수분공급, 팬의 작동을 자동적으로 제어함으로써, 스마트하게 식물재배가 가능한 한편, 솔라패널이 보조적인 전력을 공급하도록 하여 주전력원으로부터 전력공급이 되지 않는다고 하더라도 상기 솔라패널을 통해 제어부로 전력을 공급토록 하여, 사용상의 편리성을 극대화할 수 있음은 물론, 수경재배기(30)가 분할된 구조로 상호 결합됨에 따라서 다양하게 가변하여 사용할 수가 있는 유용한 발명이다. claims: 벽면 또는 지면에 설치되어 수경재배기(30)를 고정하기 위한 고정수단(10);상기 고정수단(10)의 상부에 수평 또는 측면에 수직방향으로 설치되어 식물로 광원을 공급하는 광원공급부(20);상기 고정수단(10)의 전면에 설치되고, 다수개로 구성되어 상호 조립 구성되되, 일측이 개방된 형태로 4개의 식재공간(31)이 경사지게 형성되고, 각각의 식재공간(31)의 상측과 하측에 물의 이동을 위해 각각의 홀(33)이 형성되며, 외부 양측에 연결관이 인입되어 고정하기 위한 연결관걸림홀(35)가 각각 형성되는 수경재배기(30);상기 수경재배기(30)의 하부에 구성되어 상기 수경재배기(30)로 공급되어 식물이 먹고 남은 물이 고이도록 하는 고임물통(40);상기 고임물통(40)의 하부에 구성되며 내부에 상기 수경재배기(30)로 물을 공급하기 위한 수중펌프(51)가 구성되는 양액통(50);상기 수경재배기(30)의 식재공간(31)에 식재된 식물로 양액통(50)의 물이 공급될 수 있도록 연결하는 연결관(60);상기 수경재배기(30)의 상부 일측에 설치되어 식재된 식물로부터 발산되는 허브향을 이동시키기 위한 하나 이상의 팬(70);전력원으로부터 전원을 공급받아 작동하되, 누전 발생 시 이를 차단하는 누전차단기(81)와, 상기 광원공급부(20)의 광원공급시간, 양액통(50)의 수분공급시간, 팬(70)의 작동시간을 제어하는 타이머(83)를 포함하며, 상기 광원공급부(20)의 광량, 양액통(50)의 수분공급량을 제어하는 제어부(80); 로 구성되는 것을 특징으로 하는 조립구조를 갖는 실내용 스마트 수경재배시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1008/1150 Row 1008: application_number: 1020190179376, combined_string: invention_title: 심지를 이용한 수경재배장치 abstract: 본 발명은 심지를 이용한 수경재배장치에 관한 것으로, 더욱 상세하게는 심지를 이용한 대량 수경재배에서, 다수의 화분에 손쉽게 심지를 꽂을 수 있도록 하고, 배지에 대해 최적의 수분함량을 일정하게 유지시킬 수 있도록 구조 개선된 심지를 이용한 수경재배장치에 관한 것이다. claims: 양액이 순환 가능하게 저수되는 베드(11); 상기 베드(11) 내부 바닥에 간격을 두고 다열로 배치되는 심지브래킷(12); 상기 양액에 침지된 상태로 하나의 열에 배치되는 각 심지브래킷(12) 상부에 거치되는 하나의 띠 형태로 이루어진 심지(13); 상기 베드(11) 상부에 다열로 안치되는 식물 생장용 화분(14); 을 포함하는 것,을 특징으로 하는 심지를 이용한 식물 수경재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1009/1150 Row 1009: application_number: 1020190174308, combined_string: invention_title: 식물 재배 장치 abstract: 개시되는 내용의 일 실시예에 따른 식물 재배 장치는 본체, 선반, 재배베드 및 재배용기를 포함한다. 본체 내부에 형성되는 재배공간에 선반이 형성되고, 선반위에 재배베드가, 재배베드의 내측에 재배용기가 안착된다.재배베드는 일정량의 물이 수용되는 급수부를 포함한다. 그리고, 선반은 급수부 연직하방에 위치해 급수부 내부에 수용된 물의 양을 계측하는 수위센서를 포함한다. claims: 내부에 재배공간을 형성하고 적어도 일면에 결합된 도어를 통해 상기 재배공간이 열리거나 닫히는 본체;상기 재배공간에 가로놓여 배치되며 수위센서가 구비되는 선반;상기 선반에 올려 놓이고, 내부에 수용공간이 형성되는 상면이 개방된 용기로서, 바닥면에 물이 고여 저장되는 급수부가 형성되는 재배베드; 및상기 재배배드의 급수부 상부에 배치되는 재배용기;를 포함하고,상기 급수부가 상기 수위센서 상부에 위치해 상기 수위센서는 상기 급수부에 저장된 물의 양을 계측하는,식물 재배 장치.제9항에 있어서,상기 재배용기는,하단이 상기 개방구와 인접하게 배치되고, 상단이 상기 재배용기 내부에서 위쪽을 향하도록 배치되며, 다공성 재질로 이루어져 물을 흡수하는 심지;를 포함하는,식물 재배 장치.내부에 재배공간을 형성하고 적어도 일면에 결합된 도어를 통해 상기 재배공간이 열리거나 닫히는 본체;상기 재배공간에 가로놓여 배치되며 수위센서가 구비되는 선반;상기 선반에 올려 놓이고, 내부에 수용공간이 형성되는 상면이 개방된 용기로서, 바닥면에 물이 고여 저장되는 급수부가 형성되는 재배베드; 및상기 재배배드의 급수부 상부에 배치되는 재배용기;를 포함하고,상기 수위센서는 상기 급수부에 저장된 물의 양을 계측하고, 상기 수위센서를 통해 계측된 상기 급수부에 저장된 물의 양이 미리 정해진 양보다 작을 경우 상기 급수부에 물을 공급하는,식물 재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1010/1150 Row 1010: application_number: 1020190174321, combined_string: invention_title: 염분차 발전에 기반한 에너지 자립형 스마트 팜 시스템 abstract: 염분차 발전에 기반한 스마트 팜 시스템이 개시된다. 스마트 팜 시스템은 농작물 재배가 이루어지는 농장 시설과 여과 오폐수, 음식물 폐기물 산 발효액, 이산화탄소 흡수액, 및 여과액비로 이루어진 그룹에서 선택된 적어도 하나를 포함하는 고농도 용액과 상기 고농도 용액보다 농도가 낮은 저농도 용액을 공급받아 상기 고농도 용액과 상기 저농도 용액의 농도차를 이용하여 전기를 생성하고, 상기 농작물의 생장에 사용되는 생장원료를 공급하는 염분차 발전장치를 포함한다. claims: 농작물 재배가 이루어지며, 상기 농작물 재배를 위한 적어도 하나 이상의 농작물 재배용 센서와 전자기계 장치를 포함하는 농장 시설; 음식물 폐기물 산 발효액, 이산화탄소 흡수액, 여과액비 및 비료액으로 이루어진 그룹에서 선택된 적어도 하나를 포함하는 고농도 용액과 상기 고농도 용액보다 농도가 낮은 저농도 용액을 공급받아 상기 고농도 용액과 상기 저농도 용액의 농도차를 이용하여 전기를 생성하고, 상기 농작물의 생장에 사용되는 생장원료를 배출하여 상기 농작물에 공급하는 염분차 발전장치; 상기 염분차 발전장치와 상기 농장 시설 사이에 설치된 생장 원료 희석 공급부로, 상기 생장 원료 희석 공급부는 상기 염분차 발전장치와 상기 농장 시설에 연결 설치된 배관, 상기 배관에 설치된 농도 측정기, 및 상기 농도 측정기에서 농도가 측정된 생장원료가 유입되는 입구, 상기 농장 시설에 연결된 제1 출구와 상기 염분차 발전장치 전단에 상기 고농도 용액의 경로에 연결된 제2 출구를 포함하는 밸브를 포함하고, 상기 농도 측정기의 측정 결과가 설정 범위를 만족하면 상기 제1 출구를 개방하여 상기 생장 원료를 상기 농장 시설에 공급하고, 상기 농도 측정기의 측정 결과가 설정 범위를 만족하지 않으면 상기 제2 출구를 개방하여 상기 생장 원료를 상기 고농도 용액과 섞어 상기 염분차 발전장치로 다시 공급하는 생장 원료 희석 공급부; 및상기 염분차 발전장치에서 생산된 상기 전기를 저장하고, 상기 센서와 상기 전자기계 장치에 상기 전기를 공급하는 에너지 저장 시스템을 포함하는 염분차 발전장치에 기반한 에너지 자립형 스마트 팜 시스템.농작물 재배가 이루어지며, 상기 농작물 재배를 위한 적어도 하나 이상의 농작물 재배용 센서와 전자기계 장치를 포함하는 농장 시설; 음식물 폐기물 산 발효액, 이산화탄소 흡수액, 여과액비 및 비료액으로 이루어진 그룹에서 선택된 적어도 하나를 포함하는 고농도 용액과 상기 고농도 용액보다 농도가 낮은 저농도 용액을 공급받아 상기 고농도 용액과 상기 저농도 용액의 농도차를 이용하여 전기를 생성하고, 상기 농작물의 생장에 사용되는 생장원료를 배출하여 상기 농작물에 공급하는 염분차 발전장치; 고농도 염수와 상기 고농도 용액 중 어느 하나와 상기 저농도 용액을 공급받아 전기를 생성하는 대용량 염분차 발전장치; 및 상기 염분차 발전장치 및 상기 대용량 염분차 발전장치에서 생성된 전기를 저장하고, 상기 센서와 상기 전자기계 장치에 상기 전기를 공급하는 에너지 저장 시스템을 포함하고, 상기 대용량 염분차 발전장치는 수광부를 갖는 제1 면 및 제1 면의 반대방향의 제2 면을 갖는 태양전지 패널; 및 상기 저농도 용액으로 이루어진 제1 용액과 상기 고농도 염수와 상기 고농도 용액 중 어느 하나로 이루어진 제2 용액이 유입하여 염도차 발전을 통해 전기를 생산하기 위한 염도차 발전 유닛을 포함하며,상기 염도차 발전 유닛은, 제1 용액 유입포트 및 유출포트, 제2 용액 유입포트 및 유출포트를 갖는 하우징;하우징 내에 배치되고, 소정간격 떨어져 마련된 애노드 및 캐소드 전극; 및애노드 및 캐소드 전극 사이에 제1 용액이 유동하는 제1 유로 및 제2 용액이 유동하는 제2 유로를 구획하도록 배열된 복수 개의 이온교환막을 포함하고,상기 하우징은, 제1 용액 유입포트 및 제1 유로를 유체 이동 가능하게 연결하는 제1 용액 유입부를 갖고,상기 제1 용액 유입부는 유입된 제1 용액 및 태양전지 패널의 상기 제2 면 사이에 열 교환이 이루어지도록 마련된 에너지 자립형 스마트 팜 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1011/1150 Row 1011: application_number: 1020190171766, combined_string: invention_title: 식물재배기 abstract: 본 발명은 식물재배기에 관한 것이다.본 발명에 따른 식물재배기는, 베이스; 상기 베이스의 상면에 평행한 면을 형성하고, 상기 베이스의 상면으로부터 상측으로 일정간격 이격배치되는 상부커버; 상기 베이스의 상면 둘레를 따라 배치되고, 상기 베이스와 상기 상부커버에 회전가능하게 배치되는 복수의 재배판넬; 상기 베이스의 상면 중심에서 상기 상부커버까지 상측으로 수직하게 연장되며, 상기 복수의 재배판넬이 배치되는 방향으로 빛을 조사하는 조명바를 포함하고, 상기 복수의 재배판넬 각각의 일측면에는, 식물이 삽입되는 복수의 재배홀더가 배치되고, 상기 복수의 재배홀더가 배치되는 상기 복수의 재배판넬 각각의 일측면은, 상기 조명바를 향하는 제1위치 또는 상기 제1위치에 반대방향을 향하는 제2위치로 배치된다. claims: 베이스;상기 베이스의 상면에 평행한 면을 형성하고, 상기 베이스의 상면으로부터 상측으로 일정간격 이격배치되는 상부커버;상기 베이스의 상면 둘레를 따라 배치되고, 상기 베이스와 상기 상부커버에 회전가능하게 배치되는 복수의 재배판넬;상기 베이스의 상면 중심에서 상기 상부커버까지 상측으로 수직하게 연장되며, 상기 복수의 재배판넬이 배치되는 방향으로 빛을 조사하는 조명바를 포함하고,상기 복수의 재배판넬 각각의 일측면에는, 식물이 삽입되는 복수의 재배홀더가 배치되고, 상기 복수의 재배홀더가 배치되는 상기 복수의 재배판넬 각각의 일측면은, 상기 조명바를 향하는 제1위치 또는 상기 제1위치에 반대방향을 향하는 제2위치로 배치되는 식물재배기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1012/1150 Row 1012: application_number: 1020190170371, combined_string: invention_title: 바이오플락 사육수를 이용한 자동식물 생산장치 abstract: 일정높이의 수조외벽이 둘러싸며 상부가 개구되고 내부공간이 형성되는 사육수조; 상기 사육 수조의 수조 외벽 어느 한 측면에는 바이오플락 사육수조와 연결되거나 바이오플락 사육수를 공급할 수 있는 바이오플락 사육수 공급관이 설치되며; 상기 사육수조 중심부에는 회전장치가 수조바닥과 수직하게 설치되며; 상기 회전장치의 최상단에는 상부 배양장치가 설치되고 하단부에는 하부 배양장치가 설치되어 회전장치의 설치방향을 중심축으로 회전하며; 상기 사육수조 내부에 설치되어 저장된 바이오플락 사육수의 수류를 형성하는 수류형성장치로 이루어진 바이오플락 사육수를 이용한 자동식물 생산장치를 제공함으로써, 고부가 가치를 지닌 바이오플락 사육수를 이용하여 자동으로 식물을 재배할 수 있어 기존의 수경재배 시 공급되는 양액의 제공이 필요하지 않고, 바이오플락 양식과 식물 동시에 실시 가능하여 양식 효율성을 높일 수 있는 효과가 있다. claims: 일정높이의 수조외벽이 둘러싸며 상부가 개구되고 내부공간이 형성되는 사육수조의 수조 외벽 어느 한 측면에는 바이오플락 사육수조와 연결되거나 바이오플락 사육수를 공급할 수 있는 바이오플락 사육수 공급관이 설치되며; 상기 사육수조 중심부에는 회전장치가 수조바닥과 수직하게 설치되며; 상기 회전장치의 최상단에는 상부 배양장치가 설치되고 하단부에는 하부 배양장치가 설치되어 회전장치의 설치방향을 중심축으로 회전하며; 상기 사육수조 내부에 설치되어 저장된 바이오플락 사육수의 수류를 형성하는 수류형성장치로 이루어진 것을 특징으로 하는 바이오플락 사육수를 이용한 자동식물 생산장치, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1013/1150 Row 1013: application_number: 1020190171246, combined_string: invention_title: 수경재배용 흡수 배지 및 이를 이용한 재배장치 abstract: 수경재배용 흡수 배지 및 이를 이용한 재배장치가 개시된다. 본 발명의 일 실시예에 따른 수경재배용 흡수 배지 및 이를 이용한 재배장치는 수직프레임 사이에 다수의 수평프레임이 일정 간격을 두고 다단으로 설치되는 지지프레임; 상기 각 단의 수평프레임 상단에 고정되며, 식물의 재배공간이 마련되는 재배 트레이; 상기 수직프레임에 일정 간격을 두고 설치되어 상기 재배 트레이의 식물에 광량을 조사하는 조명부; 상기 각 단의 수평프레임 하단에 설치되어 상기 재배 트레이에 물안개를 분사하는 급수부를 포함하며, 상기 재배 트레이는 상기 급수부에서 분사되는 물을 흡수하는 흡수 배지를 더 포함한다. claims: 수직프레임 사이에 다수의 수평프레임이 일정 간격을 두고 다단으로 설치되는 지지프레임;상기 각 단의 수평프레임 상단에 고정되며, 식물의 재배공간이 마련되는 재배 트레이;상기 수직프레임에 일정 간격을 두고 설치되어 상기 재배 트레이의 식물에 광량을 조사하는 조명부;상기 각 단의 수평프레임 하단에 설치되어 상기 재배 트레이에 물안개를 분사하는 급수부를 포함하며,상기 재배 트레이는,상기 급수부에서 분사되는 물을 흡수하는 흡수 배지를 더 포함하는, 수경재배용 흡수 배지를 이용한 재배장치.식물을 재배하기 위한 흡수 배지로서,수분이 흡수 또는 투과되는 1차 흡수지;상기 1차 흡수지 하단에 결합되는 고흡수성 폴리머 수지; 및상기 고흡수성 폴리머 수지 하단에 결합되어 상기 수분이 흡수 또는 투과되는 2차 흡수지를 포함하는, 흡수 배지., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1014/1150 Row 1014: application_number: 1020190169743, combined_string: invention_title: 식물 재배 장치 abstract: 개시되는 내용의 일 실시예에 따른 식물 재배 장치는 본체, 선반 및 재배용기를 포함하고, 재배용기는 내부에 배지가 형성되며 선반으로부터 물을 공급받는다.구체적으로 본체는 내부에 미리 정해진 크기의 재배공간이 형성되고 재배공간을 열거나 닫는 도어를 포함한다. 선반은 재배공간에 급수 및 배수가 되도록 형성된다. 재배용기는 선반에 놓여 지지되고, 선반으로부터 물을 공급받거나 선반으로 물을 배출할 수 있으며, 내부에 배지가 수용된다.상기 재배용기는 저면에 아래쪽을 향해 돌출되며, 하단에 아래쪽으로 개방되는 개방구를 포함하는 유로가이드 및 유로가이드 내부에 수용되고, 개방구로 유입된 물을 내부로 흡수해 머금는 심지를 포함한다 claims: 내부에 미리 정해진 크기의 재배공간이 형성되고, 상기 재배공간을 열거나 닫는 도어가 형성되는 본체;상기 재배공간에 급수 및 배수가 되도록 형성되는 선반; 및상기 선반에 놓여 지지되고, 상기 선반으로부터 물을 공급받거나 상기 선반으로 물을 배출할 수 있도록 형성되며, 내부에 배지가 수용되는 재배용기;를 포함하고,상기 재배용기는,저면에 아래쪽을 향해 돌출되며, 하단에 아래쪽으로 개방되는 개방구를 포함하는 유로가이드; 및상기 유로가이드 내부에 수용되고, 상기 개방구로 유입된 물을 내부로 흡수해 머금는 심지;를 포함하고,상기 심지는 상기 선반으로부터 공급되는 물을 상기 배지로 전달하는,식물 재배 장치.재배공간을 형성하고 상기 재배공간의 온도 및 습도를 조절하는 본체; 및상기 본체에 수용되는 재배용기;를 포함하고,상기 재배용기는,내측에 제1배지;상기 제1배지의 상면을 덮고 상기 제1배지보다 얇은 두께로 형성되는 파종부; 및상기 파종부의 상면을 덮고 상기 파종부보다 얇은 두께로 형성되는 제2배지;를 포함하는,식물 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1015/1150 Row 1015: application_number: 1020190169837, combined_string: invention_title: 관수스탠드형 수경재배장치 abstract: 본 발명은 바닥면에 대해 수직으로 입설되는 지지체에 트레이고정구를 복수개 구비하고 복수개 구비된 트레이고정구에 복수개 재배트레이를 구비하여 지지체가 설치되는 공간에 많은 양의 식물을 식재하여 재배할 수 있기 때문에 공간활용성을 크게 향상시킬 수 있으며, 복수개 재배트레이에 식물의 성장에 필요한 양액을 순환 공급할 수 있어 식물 재배에 따른 편의성과 재배성을 향상시킬 수 있으며 식물측으로 공기를 공급하여 식물성장에 도움을 줌은 물론 공기 실내 정화작용을 어을 수 있으며 재배되는 식물이 그대로 외부로 노출됨에 따라 실내 인테리어 효과는 물론 실내 거주자들로 하여금 심신 안정과 스트레스 해소를 유도할 수 있으며 간단하고 용이한 설치에 의해 설치작업성을 크게 향상시킴은 물론 구성이 간단하여 설치에 따른 비용부담을 최소화 할 수 있는 관수스탠드형 수경재배장치가 개시된다. claims: 지지체와 상기 지지체에 다단으로 구비되는 복수개 재배트레이와 상기 복수개 재배트레이 중 최상단에 위치되는 재배트레이에 양액을 공급하는 양액공급체를 포함하여 이루어진 수경재배장치에 있어서, 상기 지지체(10)는, 바닥면에 대해 수직 입설되는 제1베이스(11a) 및 상기 제1베이스(11a) 일측 상단으로부터 수직연장되는 제1지지벽(11b)을 갖는 제1스탠드(11)와;상기 제1스탠드(11)와 마주보도록 위치되어 바닥면에 대해 수직입설되는 제2베이스(12a) 및 상기 제2베이스(12a) 일측 상단으로부터 수직연장되는 제2지지벽(12b)을 갖는 제2스탠드(12)와;상기 제1지지벽(11b) 상단과 제2지지벽(12b) 상단을 가로방향으로 연결하는 가로지지구(13)와;상기 제1지지벽(11b)과 제2지지벽(12b)을 가로방향으로 연결하되 제1지지벽(11b)과 제2지지벽(12b) 상부에서 하부측으로 다단으로 연결되어 복수개 재배트레이(20)가 각각 거치되어 연결되는 복수개 트레이고정구(14)와;상기 제1베이스(11a)와 제2베이스(12a)를 연결하여 제1베이스(11a)와 제2베이스(12a) 내측에 수용부(15a)를 구비하는 마감부(15)로 구비되고, 상기 양액공급체(30)는,상기 제1베이스(11a)와 제2베이스(12a) 내측에 구비된 수용부(15a)에 수용되는 양액저장부(31)와;상기 양액저장부(31) 상단에 안착되고 호스관통구멍(32a)과 회수구멍(32b)을 갖는 상판(32)과;상기 상판(32)에 구비된 호스관통구멍(32a)측으로 하단이 관통되고 상단은 상기 복수개 트레이고정구(14) 중 최상단에 위치되는 트레이고정구(14a)에 위치되는 공급호스(33)와;상기 공급호스(33)와 연결되어 복수개 트레이고정구(14)에 고정되는 복수개 재배트레이(20) 중 최상단 재배트레이(20a)와 연결되는 분배호스(34)와;상기 양액저장부(31)에 수용되어 상기 호스관통구멍(32a)측으로 관통된 공급호스(33)의 하단이 연결되고 양액저장부(31)에 저장된 양액을 공급호스(33)를 통해 분배호스(34)측으로 공급하는 순환펌프(35)와;상기 상판(32)의 회수구멍(32b)에 일측이 연결되고 상기 복수개 트레이고정구(14)에 고정되는 복수개 재배트레이(20) 중 최하단에 위치되는 재배트레이(20b)와 연결되는 회수호스(36a)가 구비된 회수관(36)으로 구비되어 이루어지는 것을 특징으로 하는 관수스탠드형 수경재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1016/1150 Row 1016: application_number: 1020190168414, combined_string: invention_title: 식물재배장치 및 그 제어방법 abstract: 본 발명의 일 실시예에 따른 식물재배장치에 있어서, 재배할 식물을 수용할 수 있는 공간을 가지는 식물수용부; 상기 식물을 재배하기 위한 적어도 하나의 환경 요소를 제공할 수 있는 환경제공부; 사용자입력부; 및 상기 식물수용부에 수용된 식물의 재배 가용 특성을 식별하고, 상기 사용자입력부를 통해 수신되는 사용자 입력에 따라 상기 식별된 재배 가용 특성의 범위 내의 목표 특성값을 지정하고, 상기 적어도 하나의 환경 요소 중에서 상기 지정된 목표 특성값에 대응하는 환경 요소값을 가지는 환경 요소가 제공되도록 상기 환경제공부를 제어하는 프로세서를 포함할 수 있다. claims: 식물재배장치에 있어서,재배할 식물을 수용할 수 있는 공간을 가지는 식물수용부;상기 식물을 재배하기 위한 적어도 하나의 환경 요소를 제공할 수 있는 환경제공부; 사용자입력부; 및상기 식물수용부에 수용된 식물의 재배 가용 특성을 식별하고,상기 사용자입력부를 통해 수신되는 사용자 입력에 따라 상기 식별된 재배 가용 특성의 범위 내의 목표 특성값을 지정하고,상기 적어도 하나의 환경 요소 중에서 상기 지정된 목표 특성값에 대응하는 환경 요소값을 가지는 환경 요소가 제공되도록 상기 환경제공부를 제어하는프로세서를 포함하는 식물재배장치.식물재배장치의 제어방법에 있어서,재배할 식물을 수용할 수 있는 공간을 가지는 식물수용부에 수용된 식물의 재배 가용 특성을 식별하는 단계;사용자입력부를 통해 수신되는 사용자 입력에 따라 상기 식별된 재배 가용 특성의 범위 내의 목표 특성값을 지정하는 단계; 및식물을 재배하기 위한 적어도 하나의 환경 요소 중에서 상기 지정된 목표 특성값에 대응하는 환경 요소값을 가지는 환경 요소가 제공되도록 환경제공부를 제어하는 단계를 포함하는 식물재배장치의 제어방법.컴퓨터가 읽을 수 있는 코드로서, 전자장치의 제어방법을 수행하는 코드를 포함하는 컴퓨터 프로그램이 저장된 기록매체에 있어서, 상기 식물재배장치의 제어방법은, 재배할 식물을 수용할 수 있는 공간을 가지는 식물수용부에 수용된 식물의 재배 가용 특성을 식별하는 단계;사용자입력부를 통해 수신되는 사용자 입력에 따라 상기 식별된 재배 가용 특성의 범위 내의 목표 특성값을 지정하는 단계; 및식물을 재배하기 위한 적어도 하나의 환경 요소 중에서 상기 지정된 목표 특성값에 대응하는 환경 요소값을 가지는 환경 요소가 제공되도록 환경제공부를 제어하는 단계를 포함하는 것을 특징으로 하는 컴퓨터가 읽을 수 있는 프로그램이 기록된 기록매체., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1017/1150 Row 1017: application_number: 1020210040803, combined_string: invention_title: 바나듐을 이용한 콩나물의 제조방법 abstract: 본 발명은 바나듐을 이용한 콩나물의 제조방법에 관한 것이다.본 발명의 바나듐 콩나물의 제조방법은, 콩나물용 콩을 유기바나듐 희석액에 18~22℃에서 20~24시간동안 침지시켜 발아한 콩을 제조하는 제1단계, 상기 발아한 콩을 수거한 후 남은 상기 유기바나듐 희석액에 항균활성을 갖는 미생물 배양액을 넣고 혼합하여 혼합액을 제조하는 제2단계, 상기 제1단계에서 발아한 콩을 콩나물 재배통 내부에 안치시킨 후, 상기 제2단계의 혼합액을 살수하는 제3단계 및, 상기 살수처리후 배수되는 혼합액으로 3~4시간마다 5~6일동안 재살수하여 10~15mg/kg의 바나듐 성분을 포함하는 바나듐 콩나물을 제조하는 제4단계를 포함하는 것이 특징이다.본 발명에 의해, 다량의 바나듐 성분을 함유함과 동시에 장기보관이 가능한 바나듐 콩나물의 제조방법이 제공된다. claims: 콩나물용 콩을 물4ℓ당 유기바나듐 20~30㎖를 넣고 제조된 유기바나듐 희석액에 18~22℃에서 20~24시간동안 침지시켜 발아한 콩을 제조하는 제1단계;상기 발아한 콩을 수거한 후 남은 상기 유기바나듐 희석액에 항균활성을 갖는 미생물 배양액과 스테비아 발효추출물을 1 : 0.1~0.5 : 0.1~0.5의 중량비로 넣고 혼합하여 혼합액을 제조하는 제2단계;상기 제1단계에서 발아한 콩을 콩나물 재배통 내부에 안치시킨 후, 상기 제2단계의 혼합액을 살수하는 제3단계 및, 상기 살수처리 후 배수되는 혼합액으로 3~4시간마다 5~6일동안 재살수하여 10~15mg/kg의 바나듐 성분을 포함하며, 냉장상태에서 최대 30일까지 장기보관 가능한 바나듐 콩나물을 제조하는 제4단계;를 포함하는, 바나듐 콩나물의 제조방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1018/1150 Row 1018: application_number: 1020200172543, combined_string: invention_title: 솔잎액 소독을 이용한 콩나물 재배방법 및 상기 방법을 통해 재배된 콩나물 abstract: 본 발명은 솔잎액 소독을 이용한 콩나물 재배방법 및 상기 방법을 통해 재배된 콩나물에 관한 것으로, 보다 구체적으로는, 솔잎 추출물을 포함하는 액상 조성물 및 솔잎 추출물을 물에 희석시켜 포함하는 희석액을 이용하여 콩나물 재배실 및 재배용기를 주기적으로 소독함으로써 콩나물의 생산성을 증가시키고, 생산된 콩나물의 식감을 향상시키며, 콩나물의 재배 과정에서 빈번히 발생하는 짓무름, 부패 등의 문제점을 사전에 방지할 수 있는, 콩나물 재배방법에 관한 것이다. claims: 콩나물 콩을 선별한 후 흐르는 물에 세척하는 단계;상기 세척한 콩나물 콩을 물에 10 분 내지 6 시간 동안 침지하여 불리는 단계;상기 불린 콩나물 콩을 솔잎 추출물을 포함하는 10℃ 내지 25℃의 온도 범위의 액상 조성물에 침지한 뒤 상기 솔잎 추출물을 포함하는 액상 조성물을 반복 분무하여 발아시키는 단계; 및상기 발아한 콩나물 콩을 재배실의 재배용기에 넣고 상기 액상 조성물을 1 시간 내지 4 시간 간격으로 반복 분무하여 3 일 내지 7 일 동안 재배하는 단계; 를 포함하되,상기 액상 조성물은, 상기 액상 조성물 전체 100 중량부를 기준으로, 증류수 50 내지 80 중량부, 솔잎 추출물 1 내지 20 중량부, 오이즙 5 내지 10 중량부, 프락토올리고당 0.01 내지 3 중량부, 및 바나나 농축액 0.1 내지 5 중량부를 포함하며,상기 발아한 콩나물 콩을 재배하는 단계는, 상기 재배하는 중에 상기 재배실의 통풍을 차단한 후 상기 콩나물 콩, 재배용기, 및 재배실에 물과 솔잎 추출물을 1 : 20의 중량비로 혼합하여 제조되는 희석액을 1 일 1 회 간격으로 상기 재배실의 이산화탄소 농도가 1,300 ppm 내지 2,000 ppm이 될 때까지 1 분 내지 60 분 동안 반복 분무하여 소독하는 단계; 및 상기 희석액을 분무한 후 재배실을 환기하는 단계;를 추가 포함하는 것을 특징으로 하는,콩나물 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1019/1150 Row 1019: application_number: 1020200091484, combined_string: invention_title: 콩나물 재배 용기 abstract: 본 발명은 콩나물의 재배, 포장 및 출하를 하나의 용기를 이용하여 수행할 수 있도록 구현한 콩나물 재배 용기에 관한 것으로, 콩나물의 원료가 되는 나물콩을 내부 공간에 수용시킨 뒤 재배하기 위한 용기부; 상기 용기부에 수용된 나물콩이 자라 콩나물이 되면 상기 용기부의 내부 공간으로 빛이 들어가는 것을 방지할 수 있도록 빛이 투과되지 않는 암막으로 형성되어 상기 용기부를 덮는 암막 커버부; 및 상기 암막 커버부로 덮인 상기 용기부의 상부 입구를 덮어 상기 용기부를 밀폐시키는 덮개부;를 포함한다. claims: 콩나물의 원료가 되는 나물콩을 내부 공간에 수용시킨 뒤 재배하기 위한 용기부;상기 용기부에 수용된 나물콩이 자라 콩나물이 되면 상기 용기부의 내부 공간으로 빛이 들어가는 것을 방지할 수 있도록 빛이 투과되지 않는 암막으로 형성되어 상기 용기부를 덮는 암막 커버부; 및상기 암막 커버부로 덮인 상기 용기부의 상부 입구를 덮어 상기 용기부를 밀폐시키는 덮개부;를 포함하며,상기 용기부는,나물콩을 수용하기 위한 내부 공간을 형성하며, 상측이 개방된 컵 형태로 형성되는 용기 본체;나물콩의 생육을 위해 상기 용기 본체의 내부 공간으로 투입되는 물이 고이지 아니하고 외부로 배출될 수 있도록 상기 용기 본체의 하부 바닥면을 관통하고 형성되는 다수 개의 물빠짐홀; 및상기 덮개부의 테두리를 따라 하측 방향으로 절곡되어 형성된 걸림턱에 체결될 수 있도록 상기 용기 본체의 상측 입구가 외측 방향으로 둥글게 절곡되어 형성되는 피걸림턱;을 포함하며,콩나물의 출하를 위해 상기 용기부 다수 개를 열을 지어 안착시키기 위한 용기 트레이;를 더 포함하며,상기 용기 트레이는,사각 평판 형태로 형성되는 베이스 플레이트;상기 용기부가 삽입되어 안착될 수 있도록 상기 베이스 플레이트를 상하 방향으로 상기 용기부의 하부 형태에 대응하는 형상으로 관통하고 열을 지어 다수 개가 형성되는 안착홀; 및상기 안착홀에 안착된 상기 용기부의 하부가 거치될 수 있도록 상기 안착홀의 하측 마다 설치되는 다수 개의 거치 프레임;을 포함하며,상기 거치 프레임은,상하 수직 방향으로 연장 형성되어 상기 안착홀을 따라 설치되는 다수 개의 수직 프레임; 및원형의 링 형태로 형성되며, 테두리를 따라 상기 다수 개의 수직 프레임의 각 하부가 설치되어 상기 베이스 플레이트의 하측에서 거치되며, 상기 안착홀에 안착된 상기 용기부의 하부를 지지하는 지지링;을 포함하며,상기 거치 프레임은,상기 지지링의 내측에 연결 설치되며, 상기 지지링의 내측 공간이 상기 용기부의 하측면보다 커 상기 지지링의 내측 공간으로 상기 용기부의 하부가 통과되는 경우 상기 용기부의 하측을 지지하는 보조 지지부;를 더 포함하며,상기 지지링은,신축성 있는 연질의 재질로 형성되며,상기 보조 지지부는,상기 지지링의 내주면을 따라 동일한 간격으로 서로 이격되어 설치되는 다수 개의 밀착 프레임; 및원판 형태로 형성되며, 테두리를 따라 상기 다수 개의 밀착 프레임의 각 일측이 설치되어 지지되는 지지 원판;을 포함하며,상기 다수 개의 밀착 프레임은,각각의 일측이 상측으로 경사지도록 설치되어 상기 지지 원판이 상기 지지링 보다 상측에 위치되도록 지지하고상기 지지 원판은,상기 용기부가 상측에 안착되면, 상기 용기부의 하중에 의해 하강함에 따라 상기 밀착 프레임의 일측이 하측 방향으로 이동하여 상기 지지링의 상측 위치로부터 상기 지지링의 하측 위치로 이동되어 상기 용기부의 하측을 지지하며, 상기 밀착 프레임은,길이 방향으로 연장 형성되어 일측이 상기 지지 원판의 테두리에 설치되고, 다른 일측이 상기 지지링의 내주면에 설치되는 지지 바아;상기 용기부와 대향하는 상기 지지 바아의 상부면을 따라 길이 방향으로 연장 형성되는 안착홈;상기 안착홈의 길이에 대응하는 길이로 연장 형성되어 일측이 상기 안착홈의 일측에 회동 가능하도록 연결 설치되는 회동 바아;상기 회동 바아의 다른 일측 하측과 상기 안착홈의 다른 일측 사이에 설치되어 탄성력을 이용하여 상기 회동 바아의 다른 일측이 상기 안착홈의 다른 일측의 상측으로 노출되도록 지지하는 지지 스프링; 및곡선 형태로 둥글게 절곡되어 형성되어 상기 지지 바아의 다른 일측에 설치되며, 상기 지지 바아의 일측이 하강하여 상기 회동 바아의 상부면과 상기 용기부 사이의 간격이 줄어듦에 따라 상기 용기부에 밀착되어 상기 용기부를 지지하는 밀착 플레이트;를 포함하는, 콩나물 재배 용기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1020/1150 Row 1020: application_number: 1020200085005, combined_string: invention_title: 아스파라긴산 함량이 증진된 기능성 느타리버섯 재배용 배지조성물 abstract: 본 발명은 느타리버섯 병재배용 배지조성물에 관한 것으로서 보다 상세하게는 배지조성물에 콩나물분말을 혼합함으로써 아스파라긴산의 함량이 증진된 기능성 느타리버섯을 생산하는 배지조성물에 관한 것이다. 본 발명에서는 톱밥 100중량부에 대해서,비트펄프 40~60중량부와, 콩나물분말 20~40중량부를 혼합하여 콩나물혼합배지를 형성하는 것을 특징으로 하며, 일반재배 느타리버섯에 비해서 약 100배이상 아스파라긴산 함량이 증진된 기능성 느타리버섯 재배용 배지조성물을 제공한다. claims: 톱밥 100중량부에 대해서,비트펄프 40~60중량부와, 콩나물분말 20~40중량부를 혼합하여 콩나물혼합배지를 형성하되,상기 콩나물분말은, 콩나물폐기물로부터 수거 후 세척되어 오염물질을 제거시키는 단계(S1);80~100℃에서 1~2시간 가열되어 삶아지고, 콩나물 특유의 냄새가 제거되는 단계(S2);50~60℃에서 5~6시간 교반되어 수분량이 8.5~9.5%가 되는 단계(S3);110-121℃에서 80~90분간 고압 살균되는 단계(S4); 효모균을 접종한 후에 50~55℃에서 2~4일간 발효하는 단계(S5);2~10℃ 상태에서 24시간 냉각되는 상태(S6);평균 입자크기가 3~50메쉬가 되도록 분쇄되어 분말형태로 생성되는 단계(S7);환기시설에서 24시간동안 T-C함량 38~50%, T-N함량 6~8%가 되도록 가스 및 암모니아를 배출하는 단계(S8);에 의해서 제조되며, 상기 콩나물혼합배지 100중량부에 대해서 물 10~15중량부 또는 pH산도조절제 0.3~0.5중량부를 더 포함함으로써, 느타리버섯의 종균을 접종하고 병재배하여 재배된 버섯에서 아스파라긴산 3000 ~ 4000mg/kg이 함유된 것을 특징으로 하는 아스파라긴산 함량이 증진된 기능성 느타리버섯 재배용 배지조성물., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1021/1150 Row 1021: application_number: 1020200050316, combined_string: invention_title: 무전력 자동 콩나물 재배기 abstract: 본 발명은 무전력 자동 콩나물 재배기에 관한 것으로, 최상부에 배치되는 제1용기 및 제1용기의 하부에 배치되는 제2용기를 포함하는 복수의 용기를 포함하며, 제1용기 및 제2용기 각각은 상부가 개방되고 하부는 밀폐된 용기로서, 각 용기의 하부에는 관통공이 형성되며, 제1용기 및 제2용기 각각의 내부에는 공통적으로 배수관 및 배수캡이 설치되고, 배수관은 상부와 하부가 각각 개방된 수직관으로서, 배수관의 하부 외주면에는 나사산이 형성되며, 배수관의 하부가 용기의 관통공을 관통한 후 너트로 고정되고, 배수캡은 용기의 하부에 배치되는 수평부재 및 수평부재의 상부와 결합하는 수직부재를 포함하며, 수평부재는 상부가 밀폐되고 하부가 개방되며, 수직부재는 상부가 밀폐되고 하부가 개방된 수직관으로서, 배수관보다 큰 직경을 가져서 배수관을 내부에 수용하며, 제1용기의 수위가 배수캡의 수직부재를 초과하면, 물은 배수캡의 수평부재 및 수직부재를 거쳐 배수관의 상부로 유입된 후, 배수관의 하부를 통해 제1용기 외부로 배출된 다음, 제2용기로 유입되는 콩나물 재배기를 제공한다. claims: 최상부에 배치되는 제1용기 및 제1용기의 하부에 배치되는 제2용기를 포함하는 복수의 용기를 포함하며,제1용기 및 제2용기 각각은 상부가 개방되고 하부는 밀폐된 용기로서, 각 용기의 하부에는 관통공이 형성되며,제1용기 및 제2용기 각각의 내부에는 공통적으로 배수관 및 배수캡이 설치되고,배수관은 상부와 하부가 각각 개방된 수직관으로서, 배수관의 하부 외주면에는 나사산이 형성되며, 배수관의 하부가 용기의 관통공을 관통한 후 너트로 고정되고,배수캡은 용기의 하부에 배치되는 수평부재 및 수평부재의 상부와 결합하는 수직부재를 포함하며,수평부재는 상부가 밀폐되고 하부가 개방되며,수직부재는 상부가 밀폐되고 하부가 개방된 수직관으로서, 배수관보다 큰 직경을 가져서 배수관을 내부에 수용하며,제1용기의 수위가 배수캡의 수직부재 상단 또는 배수관 상단을 초과하면, 수직부재의 수위가 배수관 상단을 초과하면서 물이 배수관 쪽으로 흘러 넘쳐 배수관의 상부로 유입된 후, 배수관의 하부를 통해 제1용기 외부로 배출된 다음, 제2용기로 유입되는 콩나물 재배기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1022/1150 Row 1022: application_number: 1020200009607, combined_string: invention_title: 콩나물을 생산하는 장치 abstract: 본원 발명은 합성수지, 방습 내수성 재질로서 발아가 되는 선별된 두류(콩, 녹두 등; 260)가 넣어진 봉투 형상의 재배봉투(200)를 이용하는 콩나물을 생산하는 장치로서, 상기 재배봉투(200)의 상부면은 상부에서 살수되는 배양수가 상기 재배봉투(200)의 내부로 입수(入水)될 수 있도록 천공(穿孔)된 평탄면을 구비하며, 상기 재배봉투(200)의 하부 일부면에는 상부에서 입수된 배양수를 배출할 수 있는 배출구가 형성된 콩나물을 생산하는 장치에 관한 것이다. claims: 합성수지, 방습 내수성 재질로서 발아가 되는 선별된 두류(콩, 녹두 등; 260)가 넣어진 봉투 형상의 재배봉투(200)를 이용하는 콩나물을 생산하는 장치로서,상기 재배봉투(200)의 상부면은 상부에서 살수되는 배양수가 상기 재배봉투(200)의 내부로 입수(入水)될 수 있도록 천공(穿孔)된 평탄면을 구비하며,상기 재배봉투(200)의 하부 일부면에는 상부에서 입수된 배양수를 배출할 수 있는 배출구가 형성된 것을 특징으로 하는 콩나물을 생산하는 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1023/1150 Row 1023: application_number: 1020200005871, combined_string: invention_title: 땅콩나물 재배방법 abstract: 본 발명은 땅콩나물 재배방법에 관한 것으로, 보다 상세하게는 수소수와 액상 황, 이산화염소수를 설정량 포함하는 설정수를 땅콩나물의 재배 시 설정에 따라 분무함으로써 성장과정 중 곰팡이 발생을 억제하고 땅콩나물의 생산성 향상과 면역력을 증대시킬 수 있도록 이루어진 땅콩나물 재배방법에 관한 것이다. 이를 위해, 땅콩 선별단계, 재배판 치상단계, 음용수 살수과정과 설정수 안개분무과정을 갖는 새싹 재배단계, 땅콩나물 수확단계를 포함하여 이루어진다. claims: 땅콩을 발아시켜 성장시킨 땅콩나물을 재배하는 방법에 있어서, 발아시킬 땅콩을 선별하는 땅콩 선별단계(S1)와, 선별한 땅콩을 배수가 잘되도록 다수개의 통공(31)을 가진 재배판(30)에 치상하는 재배판 치상단계(S2)와, 상기 재배판(30)에 설정 환경의 암실에서 음용수를 설정 시간 간격으로 살수하는 음용수 살수과정(S31)과, 상기 음용수 살수과정(S31)에 이어서 곰팡이 발생을 억제하도록 수소수와 액상 황과 이산화염소수를 설정의 비율로 포함한 설정수(A)를 설정 시간 간격으로 나노분사기(20)를 이용해 분무하는 설정수 안개분무과정(S32)을 포함하는 새싹 재배단계(S3)와; 상기 새싹 재배단계(S3)를 거치면서 설정 크기로 성장한 땅콩나물(10)을 수확하는 땅콩나물 수확단계(S4);를 포함하여 이루어진 것을 특징으로 하는 땅콩나물 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1024/1150 Row 1024: application_number: 1020190171580, combined_string: invention_title: 이산화염소를 이용한 유통기한이 연장된 콩나물의 재배 방법 abstract: 본 발명의 이산화염소를 이용한 유통기한이 연장된 콩나물의 재배 방법은, 콩나물의 배양 초기부터 미생물의 증식을 억제하는 것을 확인할 수 있었으며, 재배된 콩나물의 조직감 및 색감을 저해시키지 않는 효과를 확인하였다. 또한 수확된 콩나물은 저장 7일까지, 기존의 방법으로 재배된 콩나물보다 10배 가량 낮은 표면 미생물이 확인되어, 기존 콩나물 대비 약 7 내지 10일 이상의 저장성을 증대시켜 관련 산업에 유용하게 이용될 수 있다. claims: 1) 콩을 10 내지 18시간 동안 수화하는 단계;2) 상기 수화된 콩을 16 내지 19℃의 조건으로 발아시키는 단계;3) 상기 발아된 콩에 1 내지 3시간 동안 이산화염소를 주입하는 단계;4) 상기 이산화염소가 주입된 콩에 30분 내지 2시간 동안 이산화염소를 비주입 하는 단계; 및 5) 상기 3) 단계 및 4) 단계를 5 내지 7일 동안 반복하는 단계;를 포함하는, 콩나물의 재배 방법.1) 콩을 10 내지 18시간 동안 수화하는 단계;2) 상기 수화된 콩을 16 내지 19℃의 조건으로 발아시키는 단계;3) 상기 발아된 콩에 1 내지 3시간 동안 이산화염소를 주입하는 단계;4) 상기 이산화염소가 주입된 콩에 30분 내지 2시간 동안 이산화염소를 비주입 하는 단계; 및5) 상기 3) 단계 및 4) 단계를 5 내지 7일 동안 반복하는 단계;를 포함하는, 콩나물의 미생물 억제 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1025/1150 Row 1025: application_number: 1020190146323, combined_string: invention_title: 프로폴리스 콩나물 제조 방법 abstract: 본 발명은 기능성 콩나물 제조 방법에 관한 것으로서, 재배 완료된 콩나물을 채반에 투입하는 침지준비단계(S10); 콩나물이 담긴 채반을 기능성용액이 담긴 제1저수조에 소정 시간 투입하는 제1침지단계(S20); 제1저수조에서 배출된 콩나물을 저온에서 소정 시간 냉장 건조하는 제1건조단계(S30); 건조된 콩나물이 담긴 채반을 염수가 담긴 제2저수조에 넣고 빼기를 반복하는 제2침지단계(S40); 제2저수조에서 배출된 콩나물을 저온에서 소정 시간 냉장 건조하는 제2건조단계(S50); 를 포함한다.본 발명에 따르면, 재배 완료된 콩나물에 기능성 성분을 효과적으로 흡수시켜 다양한 기능성을 가진 콩나물의 신속하고 효율적인 제조가 가능케 되는 효과가 있다. claims: 재배 완료된 콩나물을 채반에 투입하는 침지준비단계(S10);상기 콩나물이 담긴 채반을 기능성용액이 담긴 제1저수조에 소정 시간 투입하는 제1침지단계(S20);상기 제1저수조에서 배출된 콩나물을 저온에서 소정 시간 냉장 건조하는 제1건조단계(S30);상기 건조된 콩나물이 담긴 채반을 염수가 담긴 제2저수조에 넣고 빼기를 반복하는 제2침지단계(S40);상기 제2저수조에서 배출된 콩나물을 저온에서 소정 시간 냉장 건조하는 제2건조단계(S50); 를 포함하는 기능성 콩나물 제조 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1026/1150 Row 1026: application_number: 1020190142050, combined_string: invention_title: 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법 abstract: 본 발명은 (a) 볏짚, 어성초 및 익모초를 태운 재에 황토와 분쇄 볏짚을 혼합한 다음과 물을 넣고 반죽을 한 후에 건조한 후 분쇄하여 볏짚 재 황토 볼을 제조하는 단계; (b) 콩을 불리는 단계; (c) 바닥면에 다수의 통공이 형성되어 있는 콩나물 재배를 위한 옹기 시루에 상기 볏짚 재 황토 볼을 깔고 그 위에 상기 불린 콩을 넣고 다시 콩 위에 볏짚 재 항토 볼로 덮어 콩나물 재배를 준비하는 단계; 및 (d) 재배수을 살수하여 콩나물을 재배하는 단계를 포함하는 것을 특징으로 하는 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법을 제공한다. 상술한 바와 같이 본 발명의 콩나물의 재배 방법은 각종 유효성분을 콩나물을 재배하는 과정에서 지속적으로 콩에 침투시킴으로써 유효성분들이 콩나물에 흡수되어 인체에 유익한 여러 가지 영양을 함유한 영양식 콩나물을 재배할 수 있다. 또한, 발아율을 촉진시킴으로써 미 발아된 썩은 콩으로 인한 비린내, 부패취를 방지할 수 있을 뿐만 아니라, 농약이나 방부제의 사용없이 콩나물 재배시 발생될 수 있는 비린내, 부패취, 썩음병, 검은 반점, 붉은 반점, 갈반 현상, 줄기의 무름병 및 줄무늬 현상 등을 개선하여 질적으로 우수한 콩나물을 재배할 수 있는 효과가 있다. claims: (a) 볏짚, 어성초 및 익모초를 태운 재에 황토와 분쇄 볏짚을 혼합한 다음과 물을 넣고 반죽을 한 후에 건조한 후 분쇄하여 볏짚 재 황토 볼을 제조하는 단계;(b) 콩을 불리는 단계;(c) 바닥면에 다수의 통공이 형성되어 있는 콩나물 재배를 위한 옹기 시루에 상기 볏짚 재 황토 볼을 깔고 그 위에 상기 불린 콩을 넣고 다시 콩 위에 볏짚 재 항토 볼로 덮어 콩나물 재배를 준비하는 단계; 및(d) 재배수을 살수하여 콩나물을 재배하는 단계를 포함하는 것을 특징으로 하는 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1027/1150 Row 1027: application_number: 1020190142059, combined_string: invention_title: 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법 abstract: 본 발명은 (a) 볏짚, 소라 껍질 및 우뭇가사리를 태운 재에 황토와 분쇄 볏짚을 혼합한 다음과 물을 넣고 반죽을 한 후에 건조한 후 분쇄하여 볏짚 재 황토 볼을 제조하는 단계; (b) 콩을 불리는 단계; (c) 바닥면에 다수의 통공이 형성되어 있는 콩나물 재배를 위한 옹기 시루에 상기 볏짚 재 황토 볼을 깔고 그 위에 상기 불린 콩을 넣고 다시 콩 위에 볏짚 재 항토 볼로 덮어 콩나물 재배를 준비하는 단계; 및 (d) 재배수을 살수하여 콩나물을 재배하는 단계를 포함하는 것을 특징으로 하는 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법을 제공한다. 상술한 바와 같이 본 발명의 콩나물의 재배 방법은 각종 유효성분을 콩나물을 재배하는 과정에서 지속적으로 콩에 침투시킴으로써 유효성분들이 콩나물에 흡수되어 인체에 유익한 여러 가지 영양을 함유한 영양식 콩나물을 재배할 수 있다. 또한, 발아율을 촉진시킴으로써 미 발아된 썩은 콩으로 인한 비린내, 부패취를 방지할 수 있을 뿐만 아니라, 농약이나 방부제의 사용없이 콩나물 재배시 발생될 수 있는 비린내, 부패취, 썩음병, 검은 반점, 붉은 반점, 갈반 현상, 줄기의 무름병 및 줄무늬 현상 등을 개선하여 질적으로 우수한 콩나물을 재배할 수 있는 효과가 있다. claims: (a) 볏짚, 소라 껍질 및 우뭇가사리를 태운 재에 황토와 분쇄 볏짚을 혼합한 다음과 물을 넣고 반죽을 한 후에 건조한 후 분쇄하여 볏짚 재 황토 볼을 제조하는 단계;(b) 콩을 불리는 단계;(c) 바닥면에 다수의 통공이 형성되어 있는 콩나물 재배를 위한 옹기 시루에 상기 볏짚 재 황토 볼을 깔고 그 위에 상기 불린 콩을 넣고 다시 콩 위에 볏짚 재 항토 볼로 덮어 콩나물 재배를 준비하는 단계; 및(d) 재배수을 살수하여 콩나물을 재배하는 단계를 포함하는 것을 특징으로 하는 볏짚 재와 옹기 시루를 이용한 콩나물 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1028/1150 Row 1028: application_number: 1020190122497, combined_string: invention_title: 토양에서의 콩나물 재배 방법. abstract: 본 발명은 토양에서 콩나물을 재배하는 방법에 관한 것으로, 상토 조성물을 채워 토양층을 형성한 트레이를 준비하는 단계, 물에 불린 콩을 상기 트레이에 살포하는 단계, 상기 트레이를 25 내지 30℃의 흑암 조건에 두고 2일 1회 상수하는 단계를 포함하며, 상기 상토 조성물은 축분, 대두박, 톱밥, 왕겨, 부엽토 및 황토로 이루어지는 것을 특징으로 한다. claims: 상토 조성물을 채워 토양층을 형성한 트레이를 준비하는 단계;콩을 상기 트레이에 살포하는 단계;상기 트레이를 25 내지 30℃의 흑암 조건에 두고 2일 1회 상수하는 단계;를 포함하며,상기 상토 조성물은,돈분 100 중량부에 대하여, 대두박 60 중량부, 톱밥 5 중량부, 왕겨 5 중량부, 부엽토 150 중량부, 질석 250 중량부 및 황토 60 중량부를 혼합하여 혼합물을 제조하는 단계;상기 혼합물을 30 내지 40℃에서 4주 동안 근권미생물인 슈도모나스 프로테겐스(Pseudomonas protegens)를 이용하여 발효함으로써 발효물을 제조하는 단계;로 제조되며,상기 돈분은 28±2℃의 건조로에서 7일 동안 건조한 후 이를 분쇄 및 살균하여 얻어진 돈분 입자이며,상기 부엽토는 낙엽 및 목분을 1:1 내지 1:0.1의 중량비로 혼합한 후 30℃에서 1개월 간 썩혀 제조된 부엽토이며,상기 발효 전 또는 발효 후에 상기 상토 조성물을 100 내지 300℃로 가열하면서 혼련하여 상기 상토 조성물 내에 분포하는 유해 세균을 제거하며,상기 콩을 상기 트레이에 살포하는 단계는 상기 콩을 토양층 표면에 살포한 후 2 내지 3㎝의 두께로 상기 상토 조성물을 도포하는 것을 특징으로 하는 콩나물 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1029/1150 Row 1029: application_number: 1020190120245, combined_string: invention_title: 구기자를 이용한 고품질 콩나물의 재배방법. abstract: 본 발명은 구기자를 이용한 고품질 콩나물의 재배방법에 관한 것으로 (a) 구기자를 수분함유율 15% 이내로 건조하는 단계; (b) 상기(a)의 구기자를 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 식용수1L당 상기(f)단계의 구기자혼합물을 10g~200g을 혼합하여 80~100℃온도에서 1시간~3시간동안 가열하여 추출하여 여과하는 단계; (h) 상기(g)단계의 구기자추출물에 콩나물재배용 콩을 투입하여 5시간~10시간동안 침지하는 단계; (i) 상기(g)단계의 구기자추출물 : 콩나물재배용수를 1~20 : 80~99를 혼합하여 콩나물재배수를 제조하는 단계; (j)상기(h)단계의 침지완료된 콩을 콩나물재배기에 투입하는 단계; (k) 상기(j)단계의 콩나물재배기에 상기(i)단계의 콩나물재배수를 공급하여 콩나물을 재배하는 단계; (l) 상기(k)단계의 재배가 완료된 콩나물을 포장하여 제품화하는 단계를 포함하여 이루어진다. claims: (a) 구기자를 수분함유율 15% 이내로 건조하는 단계; (b) 상기(a)의 구기자를 100㎛ 내지 1000㎛의 크기로 분쇄하여 준비하는 단계; (c) 식용버섯을 20㎛ 내지 50㎛의 크기로 분쇄하여 준비하는 단계; (d) 상기(b)단계의 구기자 : 상기(c)단계의 버섯분말을 20~60 : 40~80의 중량비로 혼합하여 준비하는 단계; (e) 상기(d)단계의 혼합물에 발효효소를 접종하는 단계; (f) 상기(e)단계의 발효효소를 접종한 구기자혼합물을 20~35℃의 온도에서 3일~5일간 발효하는 단계; (g) 식용수1L당 상기(f)단계의 구기자혼합물을 10g~200g을 혼합하여 80~100℃온도에서 1시간~3시간동안 가열하여 추출하여 여과하는 단계; (h) 상기(g)단계의 구기자추출물에 콩나물재배용 콩을 투입하여 5시간~10시간동안 침지하는 단계; (i) 상기(g)단계의 구기자추출물 : 콩나물재배용수를 1~20 : 80~99를 혼합하여 콩나물재배수를 제조하는 단계; (j)상기(h)단계의 침지완료된 콩을 콩나물재배기에 투입하는 단계; (k) 상기(j)단계의 콩나물재배기에 상기(i)단계의 콩나물재배수를 공급하여 콩나물을 재배하는 단계; (l) 상기(k)단계의 재배가 완료된 콩나물을 포장하여 제품화하는 단계를 포함하는 것을 특징으로 하는 구기자를 이용한 고품질 콩나물의 재배방법.제1항의 재배방법에 의하여 생산된 콩나물., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1030/1150 Row 1030: application_number: 1020190104695, combined_string: invention_title: 긴 뿌리 초록 콩나물 재배방법 abstract: 본 발명에 따른 긴뿌리 콩나물 재배방법은 콩나물 재배용 콩을 물에 담가 일정시간 동안 불리는 불림 단계; 상기 불린 콩을 바닥면에 콩은 통과하지 않고 콩나물의 뿌리가 통과하여 자랄 수 있는 크기를 갖는 다수의 통공이 형성되어 있는 재배용기에 두 층 이하로 담는 적층 단계; 상기 콩이 적층된 재배용기를 재배실의 틀에 적층하고 틀 상부에서 3~4일 동안 일정시간마다 물을 살수하여 상기 재배용기의 통공을 통하여 뿌리가 길게 자라도록 긴뿌리 콩나물로 기르는 살수재배 단계; 상기 각 살수재배된 재배용기를 바닥면의 통공을 통하여 자란 뿌리가 물에 잠기도록 수조에 적재하여 하여 2~3일간 광합성에 필요한 빛을 받을 수 있는 조건하에서 수경 재배하여 초록 콩나물로 재배하는 수경재배 단계; 및 상기 수경재배한 긴뿌리 초록 콩나물을 수확하여 세척한 후 포장하는 포장 단계;를 포함하는 것을 특징으로 하는 긴뿌리 초록 콩나물 재배방법을 개시한다. claims: 콩나물 재배용 콩을 물에 담가 일정시간 동안 불리는 불림 단계;상기 불린 콩을 바닥면에 콩은 통과하지 않고 콩나물의 뿌리가 통과하여 자랄 수 있는 크기를 갖는 다수의 통공이 형성되어 있는 재배용기(10)에 두 층 이하로 담는 적층 단계;상기 콩이 적층된 재배용기를 재배실의 틀(20)에 적층하고 틀 상부에서 3~4일 동안 일정시간마다 물을 살수하여 상기 재배용기의 통공을 통하여 뿌리가 길게 자라도록 긴뿌리 콩나물로 기르는 살수재배 단계;상기 각 살수재배된 재배용기를 바닥면의 통공을 통하여 자란 뿌리가 물에 잠기도록 수조(40)에 적재하여 하여 2~3일간 광합성에 필요한 빛을 받을 수 있는 조건하에서 수경 재배하여 초록 콩나물로 재배하는 수경재배 단계; 및 상기 수경재배한 긴뿌리 초록 콩나물을 수확하여 세척한 후 포장하는 포장 단계;를 포함하는 것을 특징으로 하는 긴뿌리 초록 콩나물의 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1031/1150 Row 1031: application_number: 1020190080029, combined_string: invention_title: 세척 효과가 향상된 콩나물 재배 방법 abstract: 본 발명은 콩나물 재배 방법에 관한 것으로, 특히 세척 효과가 향상된 콩나물 재배 방법에 관한 것이다.이러한 본 발명은 콩을 물에 제1시간동안 불리는 1차 불림 단계, 그리고 첨가물을 투입하여 상기 콩을 물에 상기 제1시간보다 긴 제2시간동안 불리는 2차 불림 단계, 그리고 상기 콩을 재배실에서 재배하여 콩나물을 생성하는 재배 단계, 그리고 상기 콩나물을 투입부에 적재하는 단계, 상기 콩나물이 상기 투입부의 후단에 구비된 제1세척부로 이동되어 와류에 의해 세척되면서 껍질이 분리되는 단계 및 상기 콩나물이 상기 제1세척부의 후단에 구비된 제2세척부로 이동되어 와류에 의해 세척되면서 잔존 껍질이 분리되는 단계를 포함하는 세척 단계, 그리고 상기 콩나물을 소정 시간 동안 숙성시키는 숙성 단계, 그리고 상기 콩나물을 포장하는 포장 단계를 포함한다. claims: 콩을 물에 제1시간동안 불리는 1차 불림 단계(S1); 첨가물을 투입하여 상기 콩을 물에 상기 제1시간보다 긴 제2시간동안 불리는 2차 불림 단계(S2); 상기 콩을 재배실에서 재배하여 콩나물을 생성하는 재배 단계(S3); 상기 콩나물을 투입부에 적재하는 단계, 상기 콩나물이 상기 투입부의 후단에 구비된 제1세척부로 이동되어 와류에 의해 세척되면서 껍질이 분리되는 단계 및 상기 콩나물이 상기 제1세척부의 후단에 구비된 제2세척부로 이동되어 와류에 의해 세척되면서 잔존 껍질이 분리되는 단계를 포함하는 세척 단계(S4); 상기 콩나물을 소정 시간 동안 숙성시키는 숙성 단계(S5); 및 상기 콩나물을 포장하는 포장 단계(S6);를 포함하는 콩나물 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1032/1150 Row 1032: application_number: 1020190080028, combined_string: invention_title: 포장 작업이 개선된 콩나물 재배 방법 abstract: 본 발명은 콩나물을 재배하는 방법에 관한 것으로, 특히 포장 작업이 개선된 콩나물 재배 방법에 관한 것이다.이러한 본 발명은 콩을 물에 제1시간동안 불리는 1차 불림 단계, 그리고 첨가물을 투입하여 상기 콩을 물에 상기 제1시간보다 긴 제2시간동안 불리는 2차 불림 단계, 그리고 상기 콩을 재배실에서 재배하여 콩나물을 생성하는 재배 단계, 그리고 상기 콩나물을 세척부에 투입하고 세척과 동시에 껍질을 분리하는 세척 단계, 그리고 상기 콩나물을 소정 시간 동안 숙성시키는 숙성 단계(S5), 그리고 상기 콩나물을 공급부에 적재하는 단계, 상기 콩나물이 상향 경사를 갖는 이송부를 따라 이송되는 단계, 상기 이송부의 단부에서 상기 콩나물이 낙하하여 계량부에 적재되는 단계, 상기 계량부에 적재된 상기 콩나물의 하중이 기 설정된 임계치에 도달하면 상기 계량부의 하부 배출구가 개방되어 포장부로 낙하되는 단계를 포함하는 포장 단계를 포함한다. claims: 콩을 물에 제1시간동안 불리는 1차 불림 단계(S1); 첨가물을 투입하여 상기 콩을 물에 상기 제1시간보다 긴 제2시간동안 불리는 2차 불림 단계(S2); 상기 콩을 재배실에서 재배하여 콩나물을 생성하는 재배 단계(S3); 상기 콩나물을 세척부에 투입하고 세척과 동시에 껍질을 분리하는 세척 단계(S4); 상기 콩나물을 소정 시간 동안 숙성시키는 숙성 단계(S5); 및 상기 콩나물을 공급부에 적재하는 단계, 상기 콩나물이 상향 경사를 갖는 이송부를 따라 이송되는 단계, 상기 이송부의 단부에서 상기 콩나물이 낙하하여 계량부에 적재되는 단계, 상기 계량부에 적재된 상기 콩나물의 하중이 기 설정된 임계치에 도달하면 상기 계량부의 하부 배출구가 개방되어 포장부로 낙하되는 단계를 포함하는 포장 단계(S6);를 포함하고, 상기 포장부는 상기 계량부에서 낙하된 콩나물이 초기 진입되는 호퍼 및 상기 호퍼 하부에 구비되고 공급된 원통 형태의 포장지의 하단을 밀봉하고 개구된 상부를 상기 호퍼의 하단에 배치하는 포장기를 포함하고, 상기 호퍼는 외면에 구비된 보호막을 포함하되, 상기 보호막은 상기 호퍼의 외면에 접하는 침투층, 상기 침투층의 상부에 구비된 발열층 및 상기 발열층의 상부에 구비된 보호층을 포함하고, 상기 침투층은 폴리에틸렌 100 중량부 대비, 폴리비닐 아세테이트계 저수축제 20 중량부 및 수소첨가 로젠이스테르 수지와 폴리브텐을 포함하는 점착제 50 중량부를 포함하고, 상기 발열층은 이산화루테늄 100 중량부 대비, 은 200 중량부 및 이산화티타늄과 이규화몰리브덴을 포함하는 기능성 결착제 200 중량부를 포함하고, 상기 보호층은 부틸 합성고무 100 중량부 대비, 탄산칼슘과 벤토나이트를 포함하는 충진제 300 중량부, 나프텐 오일 100중량부 및 바륨알루미네이트와 지르코니아를 포함하는 내열제 50 중량부를 포함하는 것을 특징으로 하는 콩나물 재배 방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1033/1150 Row 1033: application_number: 1020190050661, combined_string: invention_title: 콩나물을 이용한 숙취해소음료 abstract: 본 발명은 콩나물을 이용한 숙취해소음료에 관한 것으로, 콩나물 추출물 및 목이버섯 추출물을 포함하는 복합 추출물을 유효성분으로 포함하고, 상기 콩나물 추출물은 황톳물을 이용하여 재배한 것을 특징으로 한다.이에 따라, 별도의 첨가제 없이 천연재료만을 이용하여 콩나물의 비린향을 잡아주고, 숙취해소에 효과적인 콩나물을 효율적으로 활용하여 뛰어난 숙취해소 효과를 가진다. claims: 콩나물 추출물 및 목이버섯 추출물을 포함하는 복합 추출물을 유효성분으로 포함하고,상기 콩나물 추출물은 황톳물을 이용하여 재배한 것을 특징으로 하는 콩나물을 이용한 숙취해소음료., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1034/1150 Row 1034: application_number: 1020190022785, combined_string: invention_title: 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 무공해 콩나물과, 그 재배방법 abstract: 본 발명은 펩타이드 결합 용액을 이용한 칼슘 및 영양성분이 향상된 무공해 콩나물과 그 재배방법에 관한 것으로, 본 발명에 따르면, 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 콩나물을 재배하는 방법에 있어서, 콩나물 콩을 선별한 후 세척하고 물기를 제거하는 세척 단계; 세척된 콩나물 콩을 펩타이드 결합 용액에 침지시켜 불리는 콩불리기 단계 및 불린 콩나물 콩을 재배용기에 넣고 물과 펩타이드 결합용액을 혼합한 희석액을 살포 및 회수하는 방식으로 재배하는 재배 단계를 포함하는 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 무공해 콩나물 재배방법을 제공할 수 있다.이에 따라 재배된 칼슘 및 영양성분이 향상된 무공해 콩나물을 제공할 수 있다. claims: 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 콩나물을 재배하는 방법에 있어서,콩나물 콩을 선별한 후 세척하고 물기를 제거하는 세척 단계;세척된 콩나물 콩을 펩타이드 결합 용액에 침지시켜 불리는 콩불리기 단계; 및불린 콩나물 콩을 재배용기에 넣고 물과 펩타이드 결합 용액을 혼합한 희석액을 살포 및 회수하는 방식으로 재배하는 재배 단계;를 포함하되,상기 펩타이드 결합 용액은,물, 산화칼슘 및 아미노산을 혼합하고 가열교반하여 제1 혼합액을 제조하는 단계;산화칼슘을 정제된 물에 침지시킨 후 여과하여 여과액을 얻는 단계;여과액에 비타민 D를 혼합하고 가열교반하여 제2 혼합액을 제조하는 단계;상기 제2 혼합액에 초음파를 인가하여 입자를 분쇄하는 단계; 및상기 제1 혼합액과 초음파가 인가된 제2 혼합액을 혼합하여 펩타이드 결합 용액을 제조하는 단계;를 통해 제조되는 것을 특징으로 하는 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 무공해 콩나물 재배방법.제2항의 재배방법에 의해 재배된 펩타이드 결합 용액을 이용하여 칼슘 및 영양성분이 향상된 무공해 콩나물., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1035/1150 Row 1035: application_number: 1020190021754, combined_string: invention_title: 재배실과 연통된 외부에 수조가 형성된 하우징, 및 이것을 이용한 콩나물 재배장치 abstract: 본 발명은 재배실과 연통된 외부에 수조가 형성된 하우징을 이용한 콩나물 재배장치에 관한 것으로, 이의 구성은 재배실(3)을 갖는 하우징(1), 상기 재배실(3) 하부에 설치되어 재배통(미도시)을 탑재하여 받침 지지하는 바닥프레임(11), 이 바닥프레임(11) 하부에 배관되고 보일러(14)에서 가열된 온수를 재배실(3)로 안내하여 재배실(3) 바닥에 저장된 재배수(W)의 온도를 높이는 온수파이프(12), 상기 바닥프레임(11) 하부에 배관되고 원수를 재배실(3)로 안내하여 재배실(3) 바닥에 저장된 재배수(W)의 온도를 낮추는 냉수파이프(13), 상기 온수파이프(12)에 온수를 제공하는 보일러(14), 보일러(14)와 재배실(3)에 원수를 공급하는 원수파이프(15), 재배수(W)를 재배통에 분사하는 분사노즐(16), 원수를 재배실(3)에 공급하는 보급파이프(17), 재배실(3) 바닥에 저장된 재배수(W)를 분사노즐(16)로 이송 안내하는 급수파이프(18), 재배실(3) 바닥에 저장된 물을 외부로 배출시키는 배수파이프(19), 재배실(3)에 저장된 물의 수위를 감지하는 수위감지센서(20), 및 재배실(3)에 저장된 재배수(W)의 온도를 감지하는 온도감지센서(21)를 포함한다. claims: 조립된 벽체(2) 내부에 밀폐된 재배실(3)이 구비되고, 이 재배실(3)을 개폐할 수 있도록 벽체(2)에 도어(4)가 장착되며, 재배실(3) 바닥에 저장된 재배수(W)와 연통될 수 있도록 벽체(2) 외부에 외부수조(5)가 형성되는 것을 특징으로 하는 재*실과 연통된 외부에 수조가 형성된 하우징.콩, 녹두를 포함한 재배나물의 원료를 보관하여 재배할 수 있도록 조립된 벽체(2) 내부에 밀폐된 재배실(3)이 구비되고, 이 재배실(3)을 개폐할 수 있도록 벽체(2)에 도l어가 장착되며, 재배실(3) 바닥에 저장된 재배수(W)와 연통될 수 있도록 벽체(2) 외부에 외부수조(5)가 형성되는 하우징(1);재배나물의 원료가 담긴 재배통을 탑재할 수 있도록 상기 하우징(1)의 바닥면 상부에 수평으로 설치되는 바닥프레임(11);상기 바닥프레임(11) 하부에 고르게 배관되고, 그 양단부가 보일러(14)와 연결되어 나물 재배시 하우징(1)의 바닥면상에 저장된 재배수(W)에 잠긴상태에서 이 재배수(W)의 온도를 높일 수 있도록 펌프에 의해 보일러(14)에서 가열된 온수를 순환 안내하는 온수파이프(12); 상기 바닥프레임(11) 하부에 고르게 배관되고 그 양단부가 원수탱크(T)와 연결되어, 나물 재배시 하우징(1)의 바닥면에 저장된 재배수(W)에 잠긴상태에서 이 재배수(W)의 온도를 낮출 수 있도록 펌프에 의해 원수를 순환 안내하는 냉수파이프(13);상기 온수파이프(12)의 양단부와 연결되어 되고, 제어부(22)의 신호에 따라 저장된 물을 가열하여 온수로 만들고 이 온수를 펌프에 의해 상기 온수파이프에 공급하는 순환시키는 보일러(14);상기 원수탱크(T), 보일러(14) 및 재배실(3)과 배관으로 연결되고, 제어부(22)의 신호에 따라 보일러(14)와 재배실(3)에 원수를 공급하는 원수파이프(15);재배실(3)의 천장에 설치되고, 재배실(3) 바닥에 저장된 재배수(W)를 재배나물의 원료가 담긴 재배통에 분사하여 공급하는 분사노즐(16);상기 원수파이프(15)와 재배실(3) 사이에 배관되어 원수를 재배실(3)에 공급하는 보급파이프(17);상기 재배실(3)과 분사노즐(16)에 연결되고, 제어부(22)의 신호에 따라 구동하는 펌프에 의해 재배실(3) 바닥에 저장된 재배수(W)를 분사노즐(16)로 이송 안내하는 급수파이프(18);상기 재배실(3)과 연결되고, 재배실(3) 바닥에 저장된 물을 외부로 배출시키는 배수파이프(19);재배실(3)에 저장된 물이 설정된 수위에 도달하면 제어부(22)의 신호에 의해 펌프의 구동이 정지되어 재배실(3)로 공급된 물을 차단할 수 있도록 재배실(3)에 저장된 물의 수위를 감지하는 수위감지센서(20); 및재배실(3)에 저장된 재배수(W)의 온도를 감지하는 온도감지센서(21);를 포함하는 것을 특징으로 하는 재배실과 연통된 외부에 수조가 형성된 하우징을 이용한 콩나물 재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1036/1150 Row 1036: application_number: 1020190000074, combined_string: invention_title: 만두피에 콩나물 원액 즙을 첨가한 만두 abstract: 우리음식 중에는 만두가 있다. 만두는 만두피 속에 든 내용물에 따라 각기 다른 이름으로 군만두, 물만두, 고기만두, 김치만두, 새우만두, 야채만두 등 다양한 만두가 있다.본 발명은 밀을 빻아 만든 분말가루인 밀가루를 반죽 시 만두피에 다양한 영양성분이 풍부하고 효능이 많은 식재료로 부드럽고 달콤한 맛을 내는콩나물 원액 즙을 적당하게 골고루 첨가하여 만두를 만드는 기술 분야의 발명이다.콩나물과 밀에 포함되어 있는 다양한 영양성분의 효능이 첨가한 만두를 접할 수 있는 기회를 소홀하게 다룰 수 있는 문제점을 해결하고이를 개선하고자 만두피에 콩나물 원액 즙을 첨가한 만두에 대해 연구한 결과 해결하는 수단으로 기술을 발명하게 되였다.다양한 영양성분의 효능이 많은 콩나물 원액 즙을 만두피에 첨가한 만두 제조방법으로콩나물을 깨끗이 통째로 세척한 후에 물기를 제거하고 잘게 분쇄하여 추출기 등을 이용하여 양질의 콩나물 원액 즙을 얻는다.밀을 빻아 만든 분말가루인 밀가루를 만두피를 만들기 위해 반죽에 콩나물 원액 즙을 골고루 적당하게 첨가하여 반죽을 만든다.콩나물 원액 즙을 첨가한 밀가루 반죽을 얇게 적당한 규격으로 만두피를 만든다.콩나물 원액 즙을 첨가한 밀가루 반죽을 얇게 밀어서 만든 만두피에 고기, 야채 등 내용물을 넣어 만든 만두를 접할 수 있는 기회가 주어지는 기술이 포함된 발명이다.농산물인 콩나물과 밀가루 소비증가로 농촌에서 콩나물과 밀을 재배하시는 농민에게 많은 소득을 올릴 수 있으며만두피에 콩나물 원액 즙이 첨가한 만두의 수요증가에 따라 종사자에게 일자리 제공으로 고용창출에 크게 도움이 되는 방법을 제공함으로서산업상 이용가능성이 매우 높은 기술 분야의 발명이다.국민 모두에게 콩나물과 밀에 함유되어 있는 다양한 영양성분의 효능이 포함된 만두피에 콩나물 원액 즙을 첨가한 만두를 편리하게 구입하여 취식할 수 있도록 함으로서국민건강강화에 크게 기여가 매우 높은 기술 분야의 발명이다. claims: 본 발명은 다양한 영양성분이 풍부하고 효능이 많은 식재료로 그늘에서 발아시킨 대두의 뿌리를 자라게 한 콩나물에서 추출한 콩나물 원액 즙을 가장 오래되고 중요한 작물 중의 하나인 밀을 빻아 만든 분말가루인 밀가루에 적당하게 골고루 첨가하여반죽으로 만든 만두피에 콩나물 원액 즙을 첨가한 만두로 만드는 기술 분야의 발명이다.본 발명은 밀을 빻아 만든 분말가루인 밀가루를 반죽 시 다양한 영양성분의 효능을 골고루 갖춘 콩나물 원액 즙을 첨가한 만두를일상생활에서 편리하게 구입하여 취식함으로서 국민건강강화를 유지하는데 크게 기여하는 효과를 가지는 기술이 포함되어 있는 발명이다.다양한 영양성분의 효능이 포함되어 있는 콩나물과 밀로 만든 만두의 소비증가에 따라 콩나물과 밀을 재배하는 농민에게 많은 소득을 올릴 수 있으며만두피에 콩나물 원액 즙을 첨가한 만두의 수요증가에 따라 종사자에게 일자리 제공으로 고용창출에 크게 도움이 되는 방법을 제공함으로서산업상 이용가능성이 매우 높은 기술의 발명이다., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1037/1150 Row 1037: application_number: 1020180128861, combined_string: invention_title: 콩나물, 숙주나물, 및 수경식물 재배용 재순환항온챔버 장치 abstract: 본 발명은 항온챔버, EM(Effective Microorganisms, 유용미생물군) 배양장치, 바이오 흡수·유출 필터를 포함하여 구성되는 콩나물, 숙주나물 또는 수경식물 재배용 재순환 항온챔버 장치에 관한 것이다.본 발명에 따른 콩나물, 숙주나물 또는 수경식물 재배용 재순환 항온챔버 장치는 소량의 용수를 재순환하여 반복적으로 이용할 수 있기 때문에 수자원을 효율적으로 이용할 수 있고, 싹기름 식물의 발아 또는 재배 중 분비되는 유기 분비물이 살수액과 함께 EM(Effective Microorganisms, 유용미생물군) 배양수조로 모여 EM(Effective Microorganisms, 유용미생물군)의 배양에 유용하게 이용될 수 있기 때문에 지표수 또는 지하수의 오염을 획기적으로 감소시킬 수 있으며, EM(Effective Microorganisms, 유용미생물군) 배양액 또는 바이오미네랄 복합체와 숯가루, 규석 또는 망간 등을 사용하여 제조한 바이오 흡수·유출 필터를 사용하기 때문에 별도의 성장촉진제, 농약 또는 영양제 등을 처리하지 않고도 순수 유기 재배법으로 위생적으로 우리 국민들의 다소비 식품인 콩나물, 숙주나물 등을 재배할 수 있으므로, 국민건강증진상 매우 유용한 발명이다. claims: EM(Effective Microorganisms, 유용미생물군) 배양액을 이용한 콩나물, 숙주나물, 및 수경재배식물의 재배 방법에 있어서,(1) 항온, 조명, 기폭장치가 부착된 EM(Effective Microorganisms, 유용미생물군) 배양수조 내에 EM(Effective Microorganisms, 유용미생물군) 배양액을 넣고 다시 배양하는 단계;(2) 상기 EM(Effective Microorganisms, 유용미생물군) 배양수조 내의 EM(Effective Microorganisms, 유용미생물군) 배양액을 EM(Effective Microorganisms, 유용미생물군) 배양수조와 항온챔버를 연결하는 이동 파이프를 통하여 항온챔버의 상부로 끌어 올린 다음 콩나물, 숙주나물, 및 수경재배식물에 살수하는 단계; 및(3) 상기 살수액을 항온챔버 하단의 EM(Effective Microorganisms, 유용미생물군) 배양수조로 회수하여 다시 EM(Effective Microorganisms, 유용미생물군)를 배양하는데 이용하는 단계;를 포함하는 과정을 반복하는 것을 특징으로 하는 EM(Effective Microorganisms, 유용미생물군) 배양액을 이용한 콩나물, 숙주나물, 및 수경재배식물의 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1038/1150 Row 1038: application_number: 1020180121941, combined_string: invention_title: 숨쉬는 콩나물 통 abstract: 이상과 같이 콩나물재배하는데 사시도 제1도 내부와 제2도 내부모양과 같이 하면 (E)에 공기유통과 원통파이프(B)상,하, 옆에 많은 구멍으로 신선한 공기가 통하여 씽씽한 콩나물을 재배하고 장시간 보관하는데 효과가 있은 숨쉬는 콩나물 통임. claims: 청구항 1콩나물 통에 공기유통을 많이 시키는데 하면 터널(H)와 하중앙원통(D)에 원통파이프(B)을 연결하고 콩나물통 하면과 터널 (H)와 원통(D)와 연결한 원통파이프(B)상,하,옆 많은 구멍으로 많은 공기를 제공한 숨쉬는 콩나물통., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1039/1150 Row 1039: application_number: 1020180117507, combined_string: invention_title: 칼라만시를 이용한 콩나물의 재배방법 abstract: 본 발명은 칼라만시를 이용한 콩나물의 재배방법에 관한 것으로서, 보다 구체적으로는 콩나물을 재배하는 과정에 있어서, 적정 수소이온농도를 가진 칼라만시를 재배수로 하여 재배함으로써 칼라만시에 함유된 유효성분을 공급함과 아울러 미생물의 성장을 억제하여 콩나물의 수율을 증대하도록 하는 칼라만시를 이용한 콩나물의 재배방법에 관한 것이다. claims: ⒜ 칼라만시의 과육과 껍질을 가공하여 pH 5.5~6.5의 칼라만시 재배수를 얻는 재배수 제조 단계; 및 ⒝ 정선된 콩에 상기 칼라만시 재배수를 공급하여 온도 18~22℃에서 콩나물을 재배하는 콩나물 재배 단계;를 포함함을 특징으로 하는 칼라만시를 이용한 콩나물의 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1040/1150 Row 1040: application_number: 2020180003688, combined_string: invention_title: 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기 abstract: 본 고안은 가정에서 새싹채소를 재배할 때 사용되는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 관한 것으로써 보다 상세하게는 유통과 포장, 보관이 용이하고 무게가 매우 가볍고 크기가 작은 일회용 새싹용기를 이용하여 적정 용량의 새싹채소를 부력과 모세관현상을 이용한 간단한 방법으로 재배하여 가정에서 저렴한 가격으로 새싹채소를 직접 키워 먹을 수 있도록 하는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 관한 것이다.본 고안은 유통과 구입 및 보관이 용이하도록 콤팩트형 1회용 용기로 제작하여 개당 가격이 수백원에 불과하도록 용기의 제작 단가와 부피를 줄인다. 이러한 용기의 본체는 일반적으로 1회용 용기에 사용되는 얇은 플라스틱 소재로 빛을 차단하기 위한 검정색 소재이며. 본체안에 결합되는 솜 또는 부직포 등 물을 잘 흡수하는 소재의 패드가 물을 흡수 할 수 있도록 하단에 여러개의 구멍(흡수공)이 뚫린 원통의 형태이다. 본체에 원형 링 형상의 스치로폼을 끼우면 본체를 물에 띄울 수 있게 된다. 이러한 본체 안에 물을 잘 흡수하는 소재인 솜 또는 부직포로 된 패드를 결합하고 그 위에 씨앗을 담는다. 이러한 방법으로 스치로폼의 부력을 이용하여 본체를 물위에 띄우면 본체 하단의 흡수공을 통해 본체내부의 솜 또는 부직포로 된 패드가 모세관현상으로 인해 물을 흡수하여 그 위에 담긴 씨앗에 수분이 공급되는 것이다. 또한, 상기 씨앗이 담긴 솜 또는 부직포는 검정색의 충분한 길이를 가진 아주 얇은 염화비닐로 덮여있어 콩나물과 같이 빛을 차단해야 하는 경우 빛을 차단하는 역할을 하며, 씨앗이 자라는 힘에 의해 얇은 염화비닐을 밀고 올라가며 자라도록 한다. 이 염화비닐은 공기구멍을 타공하여 씨앗이 발아하는데 공기가 효율적으로 작용하도록 한다. 보리와 같이 빛이 차단되면 안되는 경우에는 염화비닐이 포함되어 있지 않다.본체의 상단부를 덮는 본 고안의 덮개는 일반적으로 사용되는 비닐로 이루어진 스티커 형식의 비닐캡으로 불투명하여, 유통과정에서 씨앗이 쏟아지지 않도록 하는 역할과 제품의 명칭과 유통기한 및 사용법등을 기재할 수 있도록 하며, 발아 이후 빛이 차단되면 안되는 경우 씨앗발아 과정에서 빛을 차단하는 역할을 하여 씨앗이 발아하고 빛이 유입돼야하는 경우 비닐캡 형태의 덮개를 떼어내서 빛을 유입시키는 것이다. claims: 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 있어서 기존의 다양한 새싹재배기와 달리 1인가구나 1회용 식재료에 적합하도록 용기안에 재배가능한 씨앗을 포함한 콤팩트한 1회용 용기로 제작하여 유통하는 것을 특징으로 하는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기, Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1041/1150 Row 1041: application_number: 2020180003689, combined_string: invention_title: 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기 abstract: 본 고안은 가정에서 새싹채소를 재배할 때 사용되는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 관한 것으로써 보다 상세하게는 유통과 포장, 보관이 용이하고 무게가 매우 가볍고 크기가 작은 일회용 새싹용기를 이용하여 적정 용량의 새싹채소를 부력과 모세관현상을 이용한 간단한 방법으로 재배하여 가정에서 저렴한 가격으로 새싹채소를 직접 키워 먹을 수 있도록 하는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 관한 것이다.본 고안은 유통과 구입 및 보관이 용이하도록 콤팩트형 1회용 용기로 제작하여 개당 가격이 수백원에 불과하도록 용기의 제작 단가와 부피를 줄인다.이러한 용기의 본체는 물에 띄울 수 있고, 가벼운 스치로폼이며, 본체위에 결합되는 솜 또는 부직포 등 물을 잘 흡수하는 소재의 패드가 물을 흡수 할 수 있도록 중앙에 구멍이 뚫린 원형의 형태이다. 이러한 스치로폼 본체 위에 물을 잘 흡수하는 소재인 솜 또는 부직포를 결합하고 그 위에 씨앗을 담는다. 이러한 방법으로 스치로폼의 부력을 이용하여 물위에 띄우면 솜 또는 부직포가 모세관현상으로 인해 물을 흡수하여 그 위에 담긴 씨앗에 수분이 공급되는 것이다. 또한, 상기 씨앗이 담긴 솜 또는 부직포는 검정색의 충분한 길이를 가진 아주 얇은 염화비닐로 덮여있어 콩나물과 같이 빛을 차단해야 하는 경우 빛을 차단하는 역할을 하며, 씨앗이 자라는 힘에 의해 얇은 염화비닐을 밀고 올라가며 자라도록 한다. 이 염화비닐은 공기구멍을 타공하여 씨앗이 발아하는데 공기가 효율적으로 작용하도록 하며, 이러한 방식으로 보리와 같이 빛이 차단되면 안되는 경우에는 빛이 통과하는 투명한 염화비닐로 구성된다. 본 고안의 덮개는 일반적으로 사용되는 비닐로 이루어진 스티커 형식의 비닐캡으로 불투명하여, 유통과정에서 씨앗이 쏟아지지 않도록 하는 역할과 제품의 명칭과 유통기한 및 사용법등을 기재할 수 있도록 하며, 발아 이후 빛이 차단되면 안되는 경우 씨앗발아 과정에서 빛을 차단하는 역할을 하여 씨앗이 발아하고 빛이 유입돼야하는 경우 비닐캡 형태의 덮개를 떼어내서 빛을 유입시키는 것이다. claims: 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기에 있어서 기존의 다양한 새싹재배기와 달리 1인가구나 1회용 식재료에 적합하도록 용기안에 재배가능한 씨앗을 미리 담아서 콤팩트한 1회용 용기로 제작하여 유통하는 것을 특징으로 하는 부력과 모세관현상을 이용한 씨앗이 든 새싹채소 재배용 1회용 콤팩트 용기, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1042/1150 Row 1042: application_number: 1020180078162, combined_string: invention_title: 땅콩나물을 이용한 건강기능성 식품의 제조 방법 abstract: 본 발명은 땅콩나물을 이용한 건강기능식품 제조방법에 관한 것으로서, 보다 상세하게는 1) 땅콩을 수경 재배하여 땅콩나물(새싹땅콩)을 수확하고 세척하는 단계; 2) 상기 세척된 땅콩나물을 1차 건조한 후 증숙하는 단계; 3) 상기 증숙된 땅콩나물을 2차 건조한 후 로스팅하는 단계; 4) 상기 로스팅된 땅콩나물을 분말로 분쇄하는 단계; 및 5) 상기 땅콩나물 분말을 아카시아 꿀로 환 또는 단 형태로 제조하는 단계;를 포함하는 땅콩나물을 이용한 건강기능성 식품의 제조 방법 및 상기 방법에 의해 제조된 땅콩나물을 이용한 건강기능성 식품 조성물에 관한 것이다. 본 발명은 물 없이 씹어서 취식할 때 잘 부서지도록 함과 더불어 씹을 때 맛과 향에 대한 거부감을 줄일 수 있으며, 휴대하면서 손쉽게 복용할 수 있으며 전립선 기능을 강화해줌으로서 휴대하면서 필요시 소변 배출을 원활하게 돕는 건강기능성 식품으로, 전립선이 약한 분들에게서 많은 수요를 창출될 것으로 기대된다. claims: 1) 땅콩을 수경 재배하여 땅콩나물(새싹땅콩)을 수확하고 세척하는 단계;2) 상기 세척된 땅콩나물을 1차 건조한 후 증숙하는 단계;3) 상기 증숙된 땅콩나물을 2차 건조한 후 로스팅하는 단계;4) 상기 로스팅된 땅콩나물을 분말로 분쇄하는 단계; 및5) 상기 땅콩나물 분말을 아카시아 꿀로 환 또는 단 형태로 제조하는 단계;를 포함하는 땅콩나물을 이용한 건강기능성 식품의 제조 방법.제 1항 내지 제 6항 중 어느 한 항의 방법으로 제조된 땅콩나물을 이용한 건강기능성 식품 조성물., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1043/1150 Row 1043: application_number: 1020170162825, combined_string: invention_title: 작두콩나물의 재배방법 및 상기 방법으로 재배된 작두콩나물을 이용한 장아찌 abstract: 본 발명은 (a) 작두콩을 물에 침종시켜 발아시킨 후 재배하여 작두콩나물을 준비하는 단계; (b) 매실, 참당귀, 다래순 및 설탕을 혼합한 후 발효한 발효물을 여과한 후 숙성시켜 약초 발효액을 제조하는 단계; (c) 상기 (b)단계의 제조한 약초 발효액에 물, 간장 및 설탕을 혼합한 간장 혼합물을 졸인 간장 혼합 농축액을 숙성시켜 약초 간장을 제조하는 단계; (d) 간장 및 된장을 혼합한 혼합장에 상기 (a)단계의 준비한 작두콩나물을 넣어 염장한 후 건져내 염장 작두콩나물을 준비하는 단계; (e) 상기 (d)단계의 준비한 염장 작두콩나물에 상기 (c)단계의 제조한 약초 간장을 넣어 1차 숙성시키는 단계; 및 (f) 상기 (e)단계의 1차 숙성시킨 작두콩나물 숙성물에 상기 (b)단계의 제조한 약초 발효액을 추가로 첨가한 후 2차 숙성시키는 단계를 포함하여 제조하는 것을 특징으로 하는 작두콩나물 장아찌의 제조방법 및 상기 방법으로 제조된 작두콩나물 장아찌에 관한 것이다. claims: (a) 작두콩을 물에 침종시켜 발아시킨 후 재배하여 작두콩나물을 준비하는 단계;(b) 매실, 참당귀, 다래순 및 설탕을 혼합한 후 발효한 발효물을 여과한 후 숙성시켜 약초 발효액을 제조하는 단계;(c) 상기 (b)단계의 제조한 약초 발효액에 물, 간장 및 설탕을 혼합한 간장 혼합물을 졸인 간장 혼합 농축액을 숙성시켜 약초 간장을 제조하는 단계;(d) 간장 및 된장을 혼합한 혼합장에 상기 (a)단계의 준비한 작두콩나물을 넣어 염장한 후 건져내 염장 작두콩나물을 준비하는 단계;(e) 상기 (d)단계의 준비한 염장 작두콩나물에 상기 (c)단계의 제조한 약초 간장을 넣어 1차 숙성시키는 단계; 및(f) 상기 (e)단계의 1차 숙성시킨 작두콩나물 숙성물에 상기 (b)단계의 제조한 약초 발효액을 추가로 첨가한 후 2차 숙성시키는 단계를 포함하여 제조하는 것을 특징으로 하는 작두콩나물 장아찌의 제조방법.제1항 내지 제4항 중 어느 한 항의 방법으로 제조된 작두콩나물 장아찌., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1044/1150 Row 1044: application_number: 1020170135519, combined_string: invention_title: 땅콩나물 재배방법 및 재배기 abstract: 본 발명은 땅콩나물 재배방법 및 재배기에 관한 것으로서 더욱 상세하게는 일반 가정에서 톱밥이나 부토,왕겨혼합발효물 등 을 사용하지 않고 인위적인 금속물질,키토산 첨가나 과다한 살수 없이 손 쉽게 친환경 유기농 땅콩나물을 재배하는 방법 및 재배기에 관한 것이다. claims: 땅콩나물 재배방법은 탈피,건조된 땅콩종자를 불림박스(104)에 담긴 자화기(207)에서 생성된 자화수에 침수하여 불림하는 불림단계(S100),상기 불림단계에서 불려진 땅콩을 재배프라스틱박스(300)에 담고 8시간 한번씩 자화수를 살수 하면서 24시간 동안 발아 시키는 발아단계(S110),발아된 땅콩을 펄라이트(301 )가 2cm 두께로 깔린 상기 재배박스(300)에 파종한후 다시 그 위에 펄라이트를 8cm 높이로 편후 25-28℃ 온도에서 재배하는 생장단계(S120),를 포함하는 것을 특징으로 한다.본 발명의 땅콩나물 재배기는 정면에 여닫이문(110)이 설치 되여 있고 상부의 손잡이(111)로 앞으로 당겨 열수 있으며 재배기 오른 쪽에는 온도조절스위치(112),기능조절스위치(113),시간조절스위치(114),사용지시등(115),저수위지시등(116),온도알림판(117),시간알림판(118),재배기받침대(119)로 구성된 본체100)를 특징으로 한다상기 본체(100) 내측 좌우 양면에 단턱(101)이 형성되여 펄라이트(301)가 담긴 전용박스(300)를 얹어 놓을수 있고 상단에는 물이송관(103)과 연결된 물분사관(102)이 설치 된것을 특징으로 하는 재배기.재배기 밑 바닥에는 물저장 겸용으로 사용되는 땅콩나물종자불림박스(104)가 있으며 그 위에는 자동공제부(200)에 연결된 히터(201 Heater)와 온도센서(202),저수위센서(203),온도알림판(115),시간알림판(116),물흡수관(204)에 연결된 물순환펌프(205),자화수이송관(206)에 연결된 자화기(207),수도공급관(208)과 연결된 수도공급연결나트(209)로 이루어 지는 것을 특징으로 하는 재배기상기 재배기에 있어서 자동공제부(200)가 설치되여 있고 본체 외부에 있는 기능조절스위치(113),시간조절스위치(114),온도조절스위치(112)를 통하여 불림기능,발아기능.생장기능을 선택하고 재배온도와 살수시간간격을 자동공제하는 것을 특징으로하는 재배기 이다, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1045/1150 Row 1045: application_number: 1020170107990, combined_string: invention_title: 채소 재배용기 이동용 캐스터바퀴 abstract: 본 발명은 채소 재배용기 이동용 캐스터바퀴에 관한 것으로서, 숙주, 콩나물 등과 같은 채소 재배용기로 부터 흘러내려오는 물이 유입됨으로 인한 캐스터바퀴 연결부의 부식방지를 방지토록 하기 위한 것이다.이를 실현하기 위한 본 발명은, 채소 재배용기(100)의 저면 다리부(10)에 고정플레이트(21)에 의해 결합되는 캐스터프레임(20)과, 상기 고정플레이트(21)와 360도 회전이 가능하게 연결되도록 캐스터프레임(20)의 상부에 구성된 베어링부(22)와, 상기 캐스터프레임(20)의 하단부에 구성되는 이동바퀴(30)로 구성되는 채소 재배용기 이동용 캐스터바퀴에 있어서, 상기 다리부(10)에는 고정플레이트(21) 및 베어링부(22)가 삽입 결합되어질 수 있는 삽입홈(11)이 형성되고; 상기 삽입홈(11) 내에는 고정플레이트(21)의 지지를 위한 지지격벽(12)이 구성되며; 상기 삽입홈(11) 내벽면에는 고정플레이트(21)의 이탈 방지를 위한 지지돌기(13)가 돌출 구비되고; 상기 삽입홈(11)의 입구측에는 고정플레이트(21) 및 베어링부(22)의 외부 노출을 방지하기 위한 마감판(40)이 결합 구성된 것을 특징으로 한다. claims: 채소 재배용기(100)의 저면 다리부(10)에 고정플레이트(21)에 의해 결합되는 캐스터프레임(20)과, 상기 고정플레이트(21)와 360도 회전이 가능하게 연결되도록 캐스터프레임(20)의 상부에 구성된 베어링부(22)와, 상기 캐스터프레임(20)의 하단부에 구성되는 이동바퀴(30)로 구성되는 채소 재배용기 이동용 캐스터바퀴에 있어서,상기 다리부(10)에는 고정플레이트(21) 및 베어링부(22)가 삽입 결합되어질 수 있는 삽입홈(11)이 형성되고;상기 삽입홈(11) 내에는 고정플레이트(21)의 지지를 위한 지지격벽(12)이 구성되며;상기 삽입홈(11) 내벽면에는 고정플레이트(21)의 이탈 방지를 위한 지지돌기(13)가 돌출 구비되고;상기 삽입홈(11)의 입구측에는 고정플레이트(21) 및 베어링부(22)의 외부 노출을 방지하기 위한 마감판(40)이 결합 구성된 것을 특징으로 하는 채소 재배용기 이동용 캐스터바퀴.채소 재배용기(100)의 저면 다리부(10)에 고정플레이트(21)에 의해 결합되는 캐스터프레임(20)과, 상기 고정플레이트(21)와 360도 회전이 가능하게 연결되도록 캐스터프레임(20)의 상부에 구성된 베어링부(22)와, 상기 캐스터프레임(20)의 하단부에 구성되는 이동바퀴(30)로 구성되는 채소 재배용기 이동용 캐스터바퀴에 있어서,상기 다리부(10)에는 고정플레이트(21) 및 베어링부(22)가 삽입 결합되어질 수 있는 삽입홈(11)이 형성되고;상기 다리부(10) 내에는 고정플레이트(21)의 이탈 방지를 위한 지지격벽(12)이 구성되며;상기 다리부(10) 내벽면에는 고정플레이트(21)의 유동을 방지하기 위한 지지돌기(13')가 돌출 구비되고;상기 삽입홈(11)의 입구측에는 베어링부(22)의 외부 노출에 따른 이물질 유입을 방지하기 위한 마감판(40)이 결합 구성된 것을 특징으로 하는 채소 재배용기 이동용 캐스터바퀴., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1046/1150 Row 1046: application_number: 1020170094658, combined_string: invention_title: 면역 증강 효과를 갖는 콩나물 혼합물 abstract: 본 발명은 면역 증강 효과를 갖는 콩나물 혼합물에 관한 것으로, 보다 상세하게는 콩을 발아시킨 후 고농도의 산소수로 재배한 고농도 산소수 콩나물에 표고버섯과 건굴을 혼합하여 동결건조시킴으로써 세포독성을 가지지 않으면서 면역 관련 사이토카인들과 유전자 및 단백질들을 유도하고, 면역세포들을 증식시킴으로써 면역 증진 효능을 갖는 면역 증강 효과를 갖는 콩나물 혼합물에 관한 것이다.본 발명에 따른 면역 증강 효과를 갖는 콩나물 혼합물은, 산소수를 발아된 콩에 살포하여 재배된 콩나물에 표고버섯과 건굴을 혼합하여 동결건조시킨 것을 특징으로 한다. claims: 산소수를 발아된 콩에 살포하여 재배된 콩나물에 표고버섯과 건굴을 혼합하여 동결건조시키되,콩나물 : 표고버섯 : 건굴은 10 : 1 : 1의 중량 비율로 혼합되고,상기 콩나물은 20~30 ℃ 암실에서 2~6시간 간격으로 5~15분씩 용존산소 농도가 10 ppm ~ 20 ppm인 산소수를 발아콩에 5~7일간 살수하여 재배된 것을 특징으로 하는 면역 증강 효과를 갖는 콩나물 혼합물., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1047/1150 Row 1047: application_number: 2020170003646, combined_string: invention_title: 일회용 콩나물 재배용기 abstract: 본 고안의 목적은 기존 재배기의 한계(고가의 제조 비용, 보관 공간의 필요성, 청결 유지 등)을 극복하여, 가정에서 누구나 저가로 간편하게 콩나물 혹은 숙주나물을 용이하게 재배하여 무공해 상태로 먹을 수 있게 한 일회용 콩나물 재배용기를 제공한다. 이러한 본 고안은 일회용 콩나물 재배용기로서, 내부에 콩나물을 재배할 수 있는 수용공간이 마련되도록 상부만이 개구되게 형성됨과 아울러 상부 개구를 개폐할 수 있도록 덮개가 구비되고, 상기 수용공간의 바닥면에는 다수 개의 배수구멍들이 형성된 용기 몸체; 상기 용기 몸체의 수용공간에 마련되어 콩나물을 재배할 수 있는 콩이 안착되는 부직포; 및 상기 부직포에 안착되는 콩을 덮도록 설치되어, 콩나물의 재배를 위해 수용공간에 물이 살수(撒水)될 때 그 살수되는 물에 의해 콩이 움직이지 않도록 하여 콩나물이 곱실거리지 않고 직선상으로 성장하게 하는 천;을 포함한다. claims: 일회용 콩나물 재배용기에 있어서, 내부에 콩나물을 재배할 수 있는 수용공간이 마련되도록 상부만이 개구되게 형성됨과 아울러 상부 개구를 개폐할 수 있도록 덮개가 구비되고, 상기 수용공간의 바닥면에는 다수 개의 배수구멍들이 형성된 용기 몸체; 상기 용기 몸체의 수용공간에 마련되어 콩나물을 재배할 수 있는 콩이 안착되는 부직포; 및 상기 부직포에 안착되는 콩을 덮도록 설치되어, 콩나물의 재배를 위해 수용공간에 물이 살수(撒水)될 때 그 살수되는 물에 의해 콩이 움직이지 않도록 하여 콩나물이 곱실거리지 않고 직선상으로 성장하게 하는 천;을 포함하고, 상기 용기 몸체는: 종이 재질로 컵 형상을 이루게 형성된 종이층; 및 상기 종이층의 내측면에 형성된 코팅층;으로 이루어지되, 상기 코팅층은: 원적외선이 방출되고 항균력이 있는, 은 나노 입자가 함유된 금속으로 상기 종이층의 0.05중량% 이상에서 10중량% 이하의 비율로 코팅되는 것을 특징으로 하는 일회용 콩나물 재배용기. 제1항에 있어서, 상기 배수구멍은: 원형, 장방형, 타원, 삼각형, 사각형, 십자형 중 어느 하나의 형상으로 16~20개의 개수로 형성되는 것을 특징으로 하는 일회용 콩나물 재배용기., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1048/1150 Row 1048: application_number: 1020170076512, combined_string: invention_title: 땅콩나물 재배트레이 abstract: 본 발명은 배수가 원활하게 이루어질 수 있고, 또 재배가 완료된 땅콩나물을 수확할 때 뿌리가 절단되지 않고 수확할 수 있는 땅콩나물 재배트레이에 관한 것이다.본 발명의 땅콩나물 재배트레이는 땅콩이 거치되어 생육되는 다수의 관통홀이 형성된 바닥판과, 상기 바닥판에서 상부로 연장되는 측판을 포함하는 땅콩나물 재배트레이에 있어서, 상기 관통홀 주변으로는 연장홀이 형성된 땅콩나물 재배트레이를 제공한다. claims: 땅콩이 거지되어 생육되는 다수의 관통홀이 형성된 바닥판과, 상기 바닥판에서 상부로 연장되는 측판을 포함하는 땅콩나물 재배트레이에 있어서,상기 관통홀 주변으로는 연장홀이 형성된 땅콩나물 재배트레이., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1049/1150 Row 1049: application_number: 1020170074571, combined_string: invention_title: 양파추출물을 이용한 콩나물 재배 방법 abstract: 본 발명에 따른 방법으로 재배된 콩나물은 특유의 비린내를 제거하여 일반 콩나물에 비해 선호도가 높고 다양한 조리 방법을 적용할 수 있으며, 발육 과정에서 양파추출물에 포함된 페쿠친, 퀘르세틴 등의 플라보노이드 성분을 흡수하여 혈액순환 및 당뇨병 개선의 효과가 있다. 또한 상기 양파추출물 이외에도 쇠무릎, 피막이풀, 섬쑥부쟁이 및 해란초 등의 약초나 감태, 돌미역, 꼬시래기, 모자반, 다시마 등의 해조류를 더 첨가함으로써 콩나물이 가지는 비린내의 원인인 리폭시게나아제의 활성을 저하시켜 특유의 비린내를 더욱 효과적으로 제거할 수 있다. claims: a) 콩을 물에 12 내지 36시간 동안 침지시켜 물에 불린 후, 5 내지 20 농도%의 소금물에 콩을 넣고 2 내지 3분간 교반하여 콩을 선별하고 이를 세척하는 단계;b) 물 100 중량부에 대해 양파 10 내지 50 중량부, 쇠무릎, 피막이풀, 섬쑥부쟁이 및 해란초에서 선택되는 어느 하나 또는 둘 이상의 약초 1 내지 10 중량부 및 감태, 돌미역, 꼬시래기, 모자반 및 다시마에서 선택되는 어느 하나 또는 둘 이상을 포함하는 해조류 1 내지 10 중량부를 투입한 후, 70 내지 100℃에서 1 내지 5시간 동안 가열하며, 가열 중간에 물 10 내지 50 중량부를 1 내지 3회 더 첨가하여 양파추출물을 수득하고, 1 내지 3회 여과하는 단계;c) 상기 양파추출물을 10 내지 15℃, 95 rH%의 습도에서 1 내지 3일간 숙성한 후, 상기 양파추출물 100 중량부에 소금 1 내지 10 중량부를 투입하여 재배액을 제조하는 단계;d) 상기 세척한 콩을 15 내지 25℃의 물에 1 내지 5시간 동안 침윤시킨 후, 15 내지 25℃의 암실에서 1 내지 5시간 동안 건조하는 것을 2 내지 5회 반복한 후, 재배용기에 투입하는 단계; 및e) 상기 재배용기에 상기 재배액을 3 내지 4시간 간격으로 공급한 후, 20 내지 25℃의 암실에서 5 내지 10일간 콩나물을 생육시키는 단계;를 포함하는 양파추출물을 이용한 콩나물 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1050/1150 Row 1050: application_number: 1020170073214, combined_string: invention_title: 땅콩나물 재배장치 abstract: 본 발명은 생장의 효율성을 높일 수 있는 땅콩나물 재배장치에 관한 것이다.본 발명의 땅콩나물 재배장치는 땅콩이 수용되어 생육 가능하도록 형성된 재배트레이; 상기 재배트레이가 다단으로 적재될 수 있도록 이루어진 프레임; 상기 재배트레이에 수용된 땅콩에 물을 공급하기 위한 급수탱크; 상기 급수탱크의 물을 펌프의 구동으로 이송하여 재배트레이의 땅콩에 공급하는 분사부; 상기 급수탱크에 설치되어 분사부를 통하여 재배트레이의 땅콩에 물을 공급할 때 미세한 기포를 같이 공급하는 스파클링 생성장치; 상기 급수탱크에 저장된 급수의 배출 및 상기 스파클링 생성장치를 제어하는 제어부; 를 포함하는 땅콩나물 재배장치를 제공한다. claims: 땅콩이 수용되어 생육 가능하도록 형성된 재배트레이;상기 재배트레이가 다단으로 적재될 수 있도록 이루어진 프레임;상기 재배트레이에 수용된 땅콩에 물을 공급하기 위한 급수탱크;상기 급수탱크의 물을 펌프의 구동으로 이송하여 재배트레이의 땅콩에 공급하는 분사부;상기 급수탱크에 설치되어 분사부를 통하여 재배트레이의 땅콩에 물을 공급할 때 미세한 기포를 같이 공급하는 스파클링 생성장치;상기 급수탱크에 저장된 급수의 배출 및 상기 스파클링 생성장치를 제어하는 제어부;를 포함하는 땅콩나물 재배장치, Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1051/1150 Row 1051: application_number: 1020170036590, combined_string: invention_title: 다목적 팬 핸들링시스템 abstract: 본 발명은 다목적 팬 핸들링시스템에 관한 것으로 하부에 팬이송용콘베이어가 구비된 기틀체의 전/후방 상부와 하부에 각각 특수한 형태로 내,외측체인스플라켓을 배열하고, 이에 소정간격으로 내용물이 넣어진 팬(채반, 트레이)을 받쳐주는 팬받침롤러가 구비되는 이너체인과 아웃터체인으로 형성되는 한쌍의 이송체인을 특수한 방법으로 결합하는 등 종래의 체인결합구조의 획기적인 개선으로 그 구조가 간단하면서도 전,후의 폭을 획기적으로 줄여줄 수 있기 때문에 종래에 설치할 수 없었던 협소한 장소에도 간편하게 설치하여 사용할 수 있도록 하고, 작은 공간에서 내용물을 원하는 용도별, 시간조절, 온/습도조절, 생산량 등에 따라 다수개의 팬(채반, 트레이)을 다양한 형태로 배열하여 외형, 크기, 높이 등에 구애됨이 없이 자유롭게 설계할 수 있도록 하며, 이러한 시스템을 사용용도에 따라 빵반죽의 발효 숙성장치는 물론이고 그 밖의 다른 제품들의 숙성기, 식품건조기, 냉장숙성기, 냉동고, 팬적재함, 증삼기, 스마트농법구현장치, 각종 수경재배장치, 콩나물재배장치 등과 같이 다양한 용도로 활용할 수 있도록 함은 물론, 더욱이 이와 같은 다양한 용도로 사용시 자동 및 연속작업이 가능하므로 별도의 대기 작업시간이 없으며, 작업의 효율성이 극대화되고 적은 인원과 시간으로 품질이 고른 양질의 제품을 얻을 수 있도록 할 수 있는 특수한 구조의 다목적 팬 핸들링시스템을 제공함으로써, 좀 더 편리하게 사용할 수 있도록 하여 주고자 함에 그 목적을 둔 것이다.상기와 같은 목적을 달성하기 위한 본 발명의 다목적 팬 핸들링시스템은 기본적으로 팬(10)을 공급 및 배출하는 팬이송용콘베이어(100)와;상기 팬이송용콘베이어(100) 상부로 수직으로 설치되는 기틀체(200)와;상기 기틀체(200)에 수직으로 연계설치되는 것으로 팬(10)의 상승과 하강이 동시에 이루어지도록 팬받침롤러(310a)(320a)를 구비한 한쌍의 이송체인(300)을 구동시키는 동력전달수단(300')과;상기 팬이송용콘베이어(100) 내측으로 형성되어 한쌍의 이송체인(300)에 구비된 팬받침롤러(310a)(320a) 상면에 팬(10)이 정확하게 안착될 수 있도록 정위치에 팬(10)을 정지시키는 스톱퍼(400)와;상기 스톱퍼(400) 앞쪽에 위치되도록 팬이송용콘베이어(100)에 형성되는 것으로 앞쪽의 팬(10)이 스톱퍼(400)에 닿아 정지되면 이를 감지한 센서의 감지신호에 의해 작동하면서 그 다음번 팬(10)을 측면에서 홀딩하여 주는 홀더(500)와;상기 기틀체(200)의 상부에 형성되어 한쌍의 이송체인(300)에 형성된 팬받침롤러(310a)(320a) 상면에 공급되어 최상부에 이송된 팬(10)을 후방으로 수평이송시키는 팬수평이송장치(600);를 포함하여 구성되어져 팬(10)을 순차적으로 공급→수직승강→수평이동→수직하강→배출할 수 있도록 이루어짐에 그 특징이 있는 것이다. claims: 팬(10)을 공급 및 배출하는 팬이송용콘베이어(100)와;상기 팬이송용콘베이어(100) 상부로 수직으로 설치되는 기틀체(200)와;상기 기틀체(200)에 수직으로 연계설치되는 것으로 팬(10)의 상승과 하강이 동시에 이루어지도록 팬받침롤러(310a)(320a)를 구비한 한쌍의 이송체인(300)을 구동시키는 동력전달수단(300')과;상기 팬이송용콘베이어(100) 내측으로 형성되어 한쌍의 이송체인(300)에 구비된 팬받침롤러(310a)(320a) 상면에 팬(10)이 정확하게 안착될 수 있도록 정위치에 팬(10)을 정지시키는 스톱퍼(400)와;상기 스톱퍼(400) 앞쪽에 위치되도록 팬이송용콘베이어(100)에 형성되는 것으로 앞쪽의 팬(10)이 스톱퍼(400)에 닿아 정지되면 이를 감지한 센서의 감지신호에 의해 작동하면서 그 다음번 팬(10)을 측면에서 홀딩하여 주는 홀더(500)와;상기 기틀체(200)의 상부에 형성되어 한쌍의 이송체인(300)에 형성된 팬받침롤러(310a)(320a) 상면에 공급되어 최상부에 이송된 팬(10)을 후방으로 수평이송시키는 팬수평이송장치(600);를 포함하여 구성되어져 팬(10)을 순차적으로 공급→수직승강→수평이동→수직하강→배출할 수 있도록 이루어짐을 특징으로 하는 다목적 팬 핸들링시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1052/1150 Row 1052: application_number: 1020170021999, combined_string: invention_title: 꼬불이 콩나물 재배기 abstract: 본 발명은 꼬볼이콩나물 재배기에 관한 것으로 더욱 구체적으로는 현재의 꼬불이 콩나물을 재배할 시 재배 노동력을 현저히 감소시키더라도 꼬불이 콩나물을 효과적이면서 능률적으로 대량 재배할 수 있는 재배기를 제공할 수 있도록 한 것이다.즉, 프레임과; 상기 프레임에 회전가능케 지지되고, 상,하부에는 개방부가 형성된 본체와; 상기 본체의 개방부에 각각 결합/고정되는 받침판과; 상기 본체를 회전시키는 회전수단을 포함하여 구성하고, 상기 본체의 양측에 회전지지축을 형성하여 프레임의 지지프레임에 회전가능케 설치하며, 상기 회전수단을 입력축과 출력축을 가진 감속 기어박스로 하여 상기 출력축을 본체의 일 측 회전지지축에 연결한 것을 특징으로 꼬불이 콩나물 재배기를 제공할 수 있도록 한 것이다. claims: 프레임(10)과;상기 프레임(10)에 회전가능케 지지되고, 상,하부에는 개방부(21)(22)가 형성된 본체(20)와;상기 본체(20)의 개방부(21)(22)에 각각 결합/고정되고, 여러 개의 통수구멍(43)이 일정한 간격으로 천공된 타공판 형태의 받침판(40)과;상기 본체(20)를 회전시키는 회전수단(50)을 포함하여 구성한 것을 특징으로 하는 꼬불이 콩나물재배기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1053/1150 Row 1053: application_number: 1020160179954, combined_string: invention_title: 발아율이 높고 상부 생장율이 우수한 땅콩나물의 재배방법 abstract: 본 발명은 발아율이 높고 상부 생장율(vigour index)이 우수한 땅콩나물의 재배방법에 관한 것으로, 보다 상세하게는 땅콩 종자의 배축(hypocotyl) 말단이 아래로 향하게 하며, 수직 방향으로 종자를 파종함으로써 발아율이 매우 높고 상부 생장율이 우수한 땅콩 나물의 재배방법에 관한 것이다.본 발명의 방법에 따라 땅콩 배축 말단이 아래로 향한 수직방향으로 종자를 파종할 경우 종자의 발아율이 매우 우수할 뿐만 아니라, 상부 생장율 및 묘목의 형태학적 특성 또한 매우 우수하여 상품성이 높은 땅콩나물을 생산할 수 있다. claims: 땅콩 종자의 배축(hypocotyl) 말단이 아래로 향하게 하며, 수직 방향으로 종자를 파종하는 것을 특징으로 하는, 발아율(germination rate)이 높고 상부 생장율(vigour index)이 우수한 땅콩나물의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1054/1150 Row 1054: application_number: 1020200030249, combined_string: invention_title: 병해충 예방 기능의 작물 보호제 및 이를 이용한 작물의 병해충 방제 방법 abstract: 본 발명은 살충, 항균 등의 병해충 예방 기능이 있는 작물보호제에 관한 것으로, 보다 상세하게는 오가노 실란을 함유하는 살충, 항균, 항바이러스 등의 병해충 예방 기능이 있는 작물보호제 및 작물의 병해충 방제 방법에 관한 것이다.본 발명은 오가노실란과 물을 혼합하여 조성한 살충, 항균, 항바이러스 등의 병해충 예방 기능이 있는 작물보호제를 제공한다.또한 본 발명은 오가노실란 100중량부에 물 100~20,000 중량부를 혼합하여 조성한 살충, 항균, 항바이러스 등의 병해충 예방 기능이 있는 작물보호제를 제공한다.또한 본 발명은 과채류 모종의 뿌리를 오가노실란 작물보호제로 적시는 과정(1과정),과채류가 심어질 토양에 상기한 오가노실란 작물보호제를 살포하는 과정(2과정),과채류를 심고 나서 작물의 잎에 오가노실란 작물보호제를 초벌 살포 소독하는 과정(3과정),작물의 잎, 줄기, 토양에 오가노실란 작물보호제에 재배 소독하는 과정(4과정),을 포함하는 작물의 병해충 방제 방법을 제공한다. claims: 오가노실란과 물을 혼합하여 조성한 살충, 항균, 항바이러스 등의 병해충 예방 기능이 있는 작물보호제.과채류 모종의 뿌리를 오가노실란 작물보호제로 적시는 과정(1과정),과채류가 심어질 토양에 오가노실란 작물보호제를 살포하는 과정(2과정),과채류를 심고 나서 작물의 잎에 오가노실란 작물보호제를 초벌 살포 소독하는 과정(3과정),작물의 잎, 줄기, 토양에 오가노실란 작물보호제에 재배 소독하는 과정(4과정),을 포함하는 작물의 병해충 방제 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1055/1150 Row 1055: application_number: 1020200021914, combined_string: invention_title: 기능성 장도라지의 재배방법 및 그 재배방법을 이용한 기능성 장도라지 abstract: 본 발명은 기능성 장도라지의 재배방법 및 그 재배방법을 이용한 기능성 장도라지에 관한 것으로, 좀 더 상세하게는 도라지의 길이를 길게 자라도록 함과 동시에 고사목을 이용한 기능성 액비를 주입하여 고사목과 동일한 영양을 갖는 기능성 장도라지를 재배할 수 있는 기능성 장도라지의 재배방법 및 그 재배방법을 이용한 기능성 장도라지에 관한 것이다.본 발명은 본 발명은 도라지를 노지에 파종하여 키우는 노지재배단계와; 상기 노지재배단계에서 자란 뿌리 썩음병을 방지하기 위해 화분에 옮겨심는 화분식재단계와; 상기 화분에 옮겨 심은 후, 상기 도라지의 뿌리가 길게 자랄 수 있도록 고사목이 담긴 화분을 추가하는 고사목화분 공급단계와; 상기 고사목 화분을 공급한 후, 상기 고사목 화분의 하단부에 연결하여 도라지 뿌리에 기능성 액비를 공급하기 위해 액비화분을 연결하는 액비화분 공급단계를 포함하는 것을 특징으로 한다. claims: 도라지를 노지에 파종하여 키우는 노지재배단계와;상기 노지재배단계에서 자란 뿌리 썩음병을 방지하기 위해 화분에 옮겨심는 화분식재단계와;상기 화분에 옮겨 심은 후, 상기 도라지의 뿌리가 길게 자랄 수 있도록 고사목이 담긴 화분을 추가하는 고사목화분 공급단계와;상기 고사목 화분을 공급한 후, 상기 고사목 화분의 하단부에 연결하여 도라지 뿌리에 기능성 액비를 공급하기 위해 액비화분을 연결하는 액비화분 공급단계를 포함하는 것을 특징으로 하는 기능성 장도라지의 재배방법.기능성 장도라지 재배방법으로 재배된 식이유황이 함유된 적어도 50Cm 이상의 장도라지를 특징으로 하는 기능성 장도라지., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1056/1150 Row 1056: application_number: 1020200000320, combined_string: invention_title: 식물 재배 장치용 파드 및 그 포장재 abstract: 본 발명은 운송 및 관리 중 파손이 방지되고 제조 비용이 절감되고, 효율적인 포장이 가능하게 되는 식물 재배 장치용 파드 및 그 포장재에 관한 것이다. claims: 식물 재배 장치의 베드에 교체 가능하게 장착되는 식물 재배 장치용 파드에 있어서, 내부에 재배를 위한 식물의 씨앗과, 해당 식물의 재배를 위한 양분이 포함된 상토가 수용되는 수용 공간을 형성하며, 상기 베드에 안착되는 용기; 및상기 용기의 상면에 부착되며, 상기 수용 공간을 차폐하는 아웃 커버;를 포함하며, 상기 용기는,상면이 개구되어 상기 수용 공간을 형성하며, 하면 일부가 하방으로 돌출되어 상기 베드에 급수되는 물이 유입되는 돌출부를 포함하는 용기 본체부;상기 용기 본체부의 상단에서 외측으로 연장되며, 상기 아웃 커버가 부착되는 상면을 형성하는 용기 상면부; 및상기 용기 상면부의 외측단에서 하방으로 연장되며, 상기 용기 본체부의 둘레와 이격된 공간을 형성하는 용기 테두리부를 포함하는 식물 재배 장치용 파드.판상의 소재가 절곡되어 상기 제 1 항 내지 제 12 항 중 어느 한 항의 파드가 수용되도록 상방으로 개구된 포장 공간;상기 포장 공간의 바닥면을 형성하는 하면부;상기 하면부의 가로 방향 양측단을 따라 상방으로 절곡되며, 상기 포장 공간의 가로 면을 형성하는 한쌍의 가로 측면부; 및상기 하면부의 세로 방향 양측단을 따라 상방으로 절곡되며, 상기 포장 공간의 세로 면을 형성하는 한쌍의 세로 측면부;을 포함하며,상기 하면부는, 상기 하면부에 한쌍이 서로 이격 배치되는 하면 개구; 및상기 하면 개구의 일단에서 상방으로 절곡되며, 상기 파드의 둘레에 형성된 공간에 삽입되어 상기 파드를 지지하는 한쌍의 지지부를 포함하는 식물 재배 장치용 파드 포장재., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1057/1150 Row 1057: application_number: 1020190170799, combined_string: invention_title: 과채류를 이용한 유산균 발효식품 및 이의 제조방법 abstract: 본 발명은 우수한 균주와 이의 최적의 발효 조건을 이용한 유산균 발효식품 및 이의 제조방법, 상기 균주를 함유한 과립형 식품 및 이의 제조방법에 관한 것이다.상기 제조방법을 통해 건강에 유익하고 섭취가 편리한 유산균 함유 발효식품을 효과적으로 제조할 수 있다. 상기 발효식품 제조시, 다양한 과채류를 이용함으로써, 새로운 수요 창출을 일으켜 과채류를 재배하고 있던 농가의 수익 창출에도 도움이 될 수 있다. 또한, 상기 제조방법에 따라 제조된 발효식품은 기능성 성분을 다량 함유하고 언제 어디서나 간편하게 섭취할 수 있어, 건강 증진에 도움이 될 수 있다. claims: 건 과채류 원액을 제조하는 단계;상기 제조된 원액에 물과 당원을 첨가하는 단계; 및락토바실러스 람노서스(Lactobacillus rhamnosus), 락토바실러스 플란타럼(Lactobacillus plantarum), 또는 이의 혼합 유산균을 배지에 접종하여 배양한 후, 상기 물과 당원이 첨가된 원액에 상기 배양된 유산균 균체를 혼합하여 발효시키는 단계;를 포함하는 유산균 발효식품의 제조방법. 제 1 항 내지 제 5 항 중 어느 한 항에 따라 제조된 유산균 발효식품.과채 분말 및 락토바실러스 람노서스(Lactobacillus rhamnosus) 또는 락토바실러스 플란타럼(Lactobacillus plantarum) 유산균, 또는 상기 유산균의 하나 이상을 포함하는 유산균 발효액을 혼합하여 과채 원액을 제조하는 단계; 상기 제조된 과채 원액을 과립화하는 단계; 및상기 과립화된 과채 원액을 건조시키는 단계;를 포함하는 유산균 함유 과립형 식품 제조방법.제 8 항 내지 제 12 항 중 어느 한 항에 따라 제조된 유산균 함유 과립형 식품., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1058/1150 Row 1058: application_number: 1020190146445, combined_string: invention_title: 작물 재배 장치 abstract: 본 기술은 작물 재배 장치에 관한 것이다. 본 기술의 작물 재배 장치는, 복수의 재배 공간들을 정의하는 프레임; 및 상기 프레임에 연결되며, 상기 재배 공간에 대해 작물 생육환경을 조성하는 복수의 공급 라인들을 갖는 공급부;를 포함한다. 본 기술은 작물 재배 환경을 조성하는 각 요소들의 효율적인 배치 방식을 통해서 저비용 및 저전력으로 작물 재배 공간을 제공할 수 있는 작물 재배 장치를 제공할 수 있다. claims: 복수의 재배 공간들을 정의하는 프레임; 및 상기 프레임에 연결되며, 상기 재배 공간에 대해 작물 생육환경을 조성하는 복수의 공급 라인들을 갖는 공급부;를 포함하는 것을 특징으로 하는 작물 재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1059/1150 Row 1059: application_number: 1020190147061, combined_string: invention_title: 파드 및 파드가 구비된 식물 재배장치 abstract: 본 발명의 파드 및 파드가 구비된 식물 재배장치는 파드를 구성하는 용기의 상부를 덮는 패키지를 분리하여 식물재배장치에 안착시키기만 하면 된다. 따라서, 식물재배에 배경지식이 없는 사용자도 손 쉽게 식물을 재배할 수 있게 되는 효과를 가진다. claims: 식물 재배장치에 사용되고, 식물이 자랄 수 있는 토양을 제공하는 파드에 있어서, 식물생장에 필요한 양분을 포함하는 토양을 공급하고, 씨앗 또는 식물이 안착되는 배지; 일측이 개방된 수용공간 내에 상기 배지가 수용되는 용기; 상기 수용공간의 입구를 차폐시키고, 상기 용기의 내부를 보호하는 패키지;를 포함하는 파드.식물이 재배되는 재배실을 제공함과 더불어 이 재배실의 개폐를 위한 개폐도어를 가지는 캐비넷;상기 캐비넷의 재배실 내에 수납되는 베드;상기 베드에 얹혀 식물이 생장하는 파드;상기 재배실 내의 바닥과 상기 재배실 내의 베드 사이에 구비되면서 상기 베드로 공급수를 공급하는 급수모듈;을 포함하고, 상기 파드는 식물생장에 필요한 양분을 포함하는 토양을 공급하고, 씨앗 또는 식물이 안착되는 배지; 일측이 개방된 수용공간 내에 상기 배지가 수용되는 용기; 상기 수용공간의 입구를 차폐시키고, 상기 용기의 내부를 보호하는 패키지;를 포함하여 구성됨을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1060/1150 Row 1060: application_number: 1020190145521, combined_string: invention_title: 율피 발효액 및 이를 이용한 토마토의 재배 방법 abstract: 본 발명은 율피가루 발효액 및 이를 이용한 토마토의 재배 방법에 관한 것이다. 본 발명에 따른 율피가루 발효액은 토마토 재배에 비료로 작용하여 토마토의 기능성을 증진시키는데 큰 도움을 주며 율피가루 발효액 자체가 병원균 등이 없어 인체 안정성이 매우 우수할 뿐만 아니라 자체로 우수한 기능성 성분들을 많이 함유하고 있다는 점에서 우수한 효과를 가진다. claims: (a) 바실러스 서브틸러스(Bacillus subtilis) 균주를 배양하여 바실러스 서브틸러스 균주 배양액을 제조하는 단계; (b) 물 100 중량부에 대해 상기 바실러스 서브틸러스 균주 배양액을 0.6 내지 2.0 중량부 및 율피 6 내지 20 중량부로 하여, 바실러스 서브틸러스 균주 배양액을 물 및 율피와 혼합하여 혼합 용액을 제조하는 단계; (c) 상기 혼합 용액을 20 내지 30 ℃에서 4 내지 14일 동안 배양하여 율피 발효액을 제조하는 단계;(d) 율피 발효액과 물을 1:50 내지 1:150의 부피비로 혼합하여 희석된 율피 발효액을 제조하는 단계; 및 (e) 희석된 율피 발효액을 토마토에 시비하는 단계;를 포함하는 토마토 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1061/1150 Row 1061: application_number: 1020190133473, combined_string: invention_title: 배추수확기용 시뮬레이터 abstract: 본 발명은 기존의 수확기, 특히 배추와 같이 수확에 있어서, 충격이나 흠집에 민감한 채소를 노지에서 수확하는 수확장치를 개발함에 있어, 수확기에만 실험을 할 수밖에 없는 시기적인 제약과 상기 배추를 상하지 않고 수확할 수 있는 조건을 정확하게 찾아내기 위한 배추수확 시뮬레이터가 없어 최적의 배추 수확조건을 알아낼 수 없는 문제가 있어왔다. 본 발명은 상기와 같은 문제를 해결하기 위하여 하기의 수단을 제공한다. 배추수확시뮬레이터에 있어서, 예취부를 전방 하단에 구비한 배추이송컨베이어; 및 상기 배추이송컨베이어가 전후로 회전하는 배추이송 컨베이어회전힌지; 및 상기 배추이송 컨베이어회전힌지가 고정되는 시뮬레이터 이송부; 및 상기 시뮬레이터 이송부를 하부에서 지지하는 이송레일을 포함하는 것을 특징으로 하는 배추수확시뮬레이터를 제공한다.상기와 같은 구성에 의하여 수확기 시뮬레이터의 구동부 동작에 의하여 변화되는 여러 센서의 값을 읽어 동작조건을 모두 기록함으로써 가장 좋은 수확 결과가 나타난 수확조건을 찾아 수확기를 개발할 수 있는 효과가 있다. claims: 배추수확시뮬레이터에 있어서,예취부를 전방 하단에 구비한 배추이송컨베이어; 및상기 배추이송컨베이어가 전후로 회전하는 배추이송 컨베이어회전힌지; 및상기 배추이송 컨베이어회전힌지가 고정되는 시뮬레이터 이송부; 및상기 시뮬레이터 이송부를 하부에서 지지하는 이송레일을 포함하는 것을 특징으로 하는 배추수확시뮬레이터.예취부를 전방 하단에 구비한 배추이송컨베이어; 및상기 배추이송컨베이어가 전후로 회전하는 배추이송 컨베이어회전힌지; 및상기 배추이송 컨베이어회전힌지가 고정되는 시뮬레이터 이송부; 및상기 시뮬레이터 이송부를 하부에서 지지하는 이송레일을 구비한,배추수확시뮬레이터에 있어서,상기 시뮬레이터 이송부 바디프레임의 일측에 상하 길이변경이 가능한 바디회전실린더를 구비하여 상기 배추수확시뮬레이터 전체를 좌우로 흔드는 시뮬레이션을 수행하는 것을 특징으로 하는 배추수확시뮬레이터., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1062/1150 Row 1062: application_number: 1020190134068, combined_string: invention_title: 농작물 재배용 멀칭매트 천공장치 abstract: 본 발명은 각종 재배작물의 씨앗을 파종하거나 유모를 이식하여 재배할 때에 공기와 빗물이 통하고 잡초발생을 억제하여 재배작물을 건강하게 재배할 할 수 있도록 한 농작물 재배용 멀칭매트 천공장치에 관한 것으로, 그 구성은, 멀칭매트를 공급하는 공급부와, 멀칭매트에 식생구멍을 천공하는 천공부와, 천공부를 승/하강시키는 작동부와, 식생구멍이 천공된 멀칭매트를 회수하는 회수부와, 공급부와 회수부를 연통시키는 구동부와, 상기 구성을 제어하는 제어부로 이루어진다. claims: 합성수지재의 가닥을 복수 층을 형성하도록 적층시켜 실로 엮어 공기와 수분은 통하고 햇빛은 통과하지 못하도록 제조된 멀칭매트(M)를 공급하도록 본체(100)의 일측에 설치된 공급부(200);상기 공급부의 출측 본체의 상부에 길이방향을 따라 장홀(370)이 형성되고, 그 장홀에는 일측단에서 타측단까지 일정가격으로 고정볼트(350)를 설치하여 된 승/하강프레임(310)이 설치되고, 그 승/하강프레임에는 150 - 300℃로 발열되고 클램프(360)로 감싸여진 상태에서 상기 고정볼트의 선단에 고정되는 식생구멍천공구(320)가 등 간격으로 설치되며, 상기 승/하강프레임의 내부에는 상기 등 간격으로 설치된 식생구멍천공구로 전기를 공급하는 전선(340)과 상기 각 식생구멍천공구에 전원을 공급 및 차단에는 스위치(330)가 설치되고, 상기 승/하강프레임에는 상기 등 간격으로 설치된 식생구멍천공구 간의 간격을 조정하기 위한 눈금자(380)을 형성하여 상기 멀칭매트에 열을 가하여 녹이면서 재배작물의 식생구멍(H)을 천공하는 천공부(300);상기 천공부와 연결설치되어 천공부를 일정시간 주기로 승/하강시키도록 본체의 최상부에 양측에 설치된 프레임(120)에 각각의 랙 가이드(410)가 고정 설치되고, 그 랙 가이드에는 상기 승/하강프레임의 단부가 설치되는 각각의 랙(420)이 상향 수직되게 설치되며, 상기 각각의 랙에는 각각의 피니언(430)이 결합 설치되고, 상기 각 피니언 간에는 회전축(440)의 단부가 연결 설치되며, 상기 회전축에는 피니언을 회전시키는 회전수단(450)이 설치되고, 랙의 선택된 위치와 본체의 프레임(120) 일 측에 각각의 수광 또는 투광센서 중 어느 하나를 설치하여 된 작동부(400);상기 작동부에 의해 천공부가 승/하강 작동되면서 상기 식생구멍이 천공된 멀칭매트를 회수하는 회수부(500);공급부에서는 공급되는 멀칭매트의 공급양 만큼 회수부에서 회수되도록 본체의 전후방에 설치되는 각 회전 바(210,510)의 일 측단부에 각각의 회전부재(610)가 설치되고, 그 각 회전부재에는 동력전단부재(620)가 연결 설치되며, 상기 각 회전부재 중 일 측의 회전부재에는 모터(630)를 설치하여 된 구동부(600);상기 공급부, 천공부, 작동부, 회수부, 구동부를 제어하는 제어부(700);를 포함하는 구성을 특징으로 하는 멀칭매트의 식생구멍 천공장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1063/1150 Row 1063: application_number: 1020190131343, combined_string: invention_title: 식물 재배장치 및 그의 급수제어 방법 abstract: 본 발명은 식물 재배장치 및 식물 재배장치의 급수제어 방법에 관한 것으로서, 본 발명의 식물 재배장치는 식물을 재배하기 위해 베드에 공급된 공급수의 잔수 여부에 따라 베드로 공급수를 공급하도록 하여 필요 이상의 공급수가 베드로 공급되지 않도록 한다. claims: 적어도 하나 이상의 베드가 수납되면서 식물이 재배되는 재배실을 제공함과 더불어 상기 재배실의 개방된 전면을 개폐하기 위한 개폐도어를 가지는 캐비넷;상기 재배실과는 독립된 공간의 기계실을 제공하는 기계실용 프레임;상기 재배실 내에 구비되며 상기 베드로 공급수를 공급하기 위한 급수모듈;상기 베드로 공급된 공급수의 잔수 여부를 감지하는 잔수감지센서;상기 잔수감지센서에서 수신되는 잔수감지신호에 기초하여 상기 급수모듈을 제어하는 컨트롤러를 포함하는 식물 재배장치.식물재배장치가 동작하면 복수의 베드에 대하여 각각의 잔수감지센서가 상기 각 베드로 공급된 공급수의 잔수 여부를 각각 감지하는 감지단계;컨트롤러가 상기 잔수감지센서에 의해 감지된 잔수여부에 대한 잔수감지신호를 이용하여 잔수 미감지의 베드가 있는지 판단하는 판단단계;상기 컨트롤러는 상기 판단결과 잔수 미감지의 베드가 있으면 상기 베드로 공급수를 급수하는 급수단계;상기 잔수 미감지의 베드로 공급수의 급수가 완료되면 급수를 종료하는 종료단계를 포함하는 식물 재배장치의 급수 제어방법.식물재배장치가 동작하면 잔수감지센서가 베드로 공급된 공급수의 잔수 여부를 감지하는 감지단계;상기 잔수감지센서에 의해 감지된 잔수여부에 대한 잔수감지신호를 이용하여 상기 베드가 잔수 미감지인지를 판단하는 판단단계;상기 잔수 미감지인 베드로 공급수를 급수하는 급수시작단계;상기 공급수를 제1 설정시간 동안 급수한 후 종료하는 급수종료단계;상기 급수가 종료되면 상기 급수의 횟수를 카운트하는 카운트단계;상기 급수에 의해 상기 잔수감지센서에서 제2 설정시간 동안 잔수 감지가 계속 유지되는지를 판단하는 잔수 판단단계;상기 잔수 판단단계에서의 판단결과에 따라 상기 베드의 급수 완료여부를 결정하는 급수완료 결정단계를 포함하는 식물 재배장치의 급수 제어방법.설정시간 동안의 총 급수량 및 1회 급수량을 설정하는 설정단계;컨트롤러가 급수개시요청에 따라 베드로 급수를 개시하는 급수개시단계;상기 설정된 1회 급수량만큼 급수되면 급수를 중단하는 급수중단단계;잔수감지센서에서 상기 베드에서의 잔수를 감지하는 감지단계;상기 잔수가 감지되면 잔수가 감지되지 않을 때까지 대기하고 상기 잔수가 감지되지 않으면 급수량이 상기 총 급수량에 도달했는지를 판단하는 판단단계;상기 총 급수량에 도달하지 않으면 급수량이 상기 총 급수량에 도달할 때까지 상기 급수개시단계부터 반복하는 반복단계를 포함하는 식물 재배장치의 급수 제어방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1064/1150 Row 1064: application_number: 1020190131607, combined_string: invention_title: 식물 재배장치 abstract: 본 발명의 식물 재배장치는 급수모듈을 이루는 워터탱크가 재배실에 구비되면서 사용자의 필요에 따른 취출이나 물 보충 등의 유지 관리가 용이하게 이루어질 수 있도록 한 것이다. claims: 재배실과 이 재배실의 개폐를 위한 도어를 가지는 캐비넷;캐비넷 내의 바닥에 위치되고, 공급수가 저장되는 워터탱크와, 상기 워터탱크의 후방에 위치되어 워터탱크 내의 공급수를 펌핑하는 워터펌프와, 워터펌프에 의해 펌핑된 공급수를 안내하는 급수호스를 포함하여 이루어진 급수모듈;상기 급수모듈의 상측에 위치되며, 상기 급수모듈로부터 공급수를 공급받는 베드;상기 베드의 상면에 안착되며, 양액물질이 포함된 상토를 가지는 파드;상기 캐비넷 내의 베드의 상측에 위치되면서 식물 재배를 위한 조명을 제공하는 조명모듈;상기 캐비넷의 하측에 설치되며, 기계실을 제공하는 기계실용 프레임;을 포함하며,상기 워터탱크는 워터펌프로부터 분리되면서 전방으로 인출 가능하게 구성됨을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1065/1150 Row 1065: application_number: 1020190126949, combined_string: invention_title: 이동식 저온저장 장치 abstract: 채소나 과일을 저온저장하는 저온저장용 컨테이너에 타이어를 갖추고, 이송수단에 연결하여 끌고 다닐 수 있게 구성하므로, 채소나 과일 산지 근처 등 원하는 곳으로 쉽게 이동시켜 편리하게 사용할 수 있다. 특히, 저온저장용 컨테이너에 단열을 위해 사용하는 단열재에 제올라이트를 함유하게 하거나, 패널을 제작할 때 제올라이트를 함께 도포하여 사용할 수 있게 구성하므로, 제올라이트가 가진 다양한 특성, 예를 들어서, 살균·소독·항균·탈취·숙성 그리고 상온 보존 연장 효과를 얻을 수 있다. 또한, 유압 스탠드를 이용하여 저온저장용 컨테이너를 지지할 수 있게 구성하므로, 저온저장용 컨테이너의 수평 상태를 유지하여 안전하게 사용할 수 있고, 특히 지면이 평편하지 않은 곳에서도 쉽게 수평을 맞춰서 편리하게 사용할 수 있다. claims: 패널(110)로 제작하여 내부에 농산물을 저장할 수 있는 저온저장용 컨테이너(100)를 포함하되,상기 저온저장용 컨테이너(100)에는,이송수단에 연결하여 함께 이동하게 하는 견인장치;상기 저온저장용 컨테이너(100)가 움직일 수 있게 안내하는 적어도 두 개의 타이어(120); 및상기 저온저장용 컨테이너(100)의 수평 상태를 유지할 수 있도록 장착한 적어도 2개의 유압 스탠드(130);를 포함하는 것을 특징으로 하는 이동식 저온저장 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1066/1150 Row 1066: application_number: 1020190126089, combined_string: invention_title: 농업용 생분해성 토양 멀칭 피복지 제조방법 abstract: 본 발명은 농업용 생분해성 토양 멀칭 피복지 제조방법에 관한 것으로서, 보다 상세하게는 상기 조개껍데기를 소성하여 곱게 분쇄하여 농업용 멀칭 피복지 제조에 사용함으로써, 식물에 Ca의 성분을 충분히 공급할 수 있도록 하고, 이러한 소성된 조개껍데기의 살균력을 통해 채소작물의 신선도를 유지할 수 있도록 함으로써, 기존의 환경문제를 해결하면서, 썩지않는 멀칭비닐의 기존문제점도 해결할 수 있도록 하는 농업용 생분해성 토양 멀칭 피복지 제조방법에 관한 것이다. claims: 크라프트 원지가 준비되는 단계(S100);코팅용 접착제가 제조되는 단계(S200);토질개량 및 광합성 차단제가 제조되는 단계(S300);상기 코팅용 접착제와 토질개량 및 광합성 차단제에, 열이 가해지면서 상호간 1:1 비율로 혼합되어, 기능성 코팅제가 제조되는 단계(S400);상기 크라프트 원지 상면에 기능성 코팅제가 사전설정 도포량 범위로 도포되는 단계(S500);상기 크라프트 원지 저면에 컬방지 및 발수코팅제가 코팅되어 농업용 멀칭 피복지가 제조되는 단계(S600);상기 농업용 멀칭 피복지가 건조 후, 롤에 권취되어 사전설정길이로 소분된 후, 포장출하되는 단계(S700);를 포함하여 이루어지며,상기 S300단계의 토질개량 및 광합성 차단제는칼슘제공 및 작물의 신선도 유지를 위한 소성된 폐조개가루 50중량%,토양개선과 광합성 차단을 위한 활성탄 및 블랙카본 20중량%,음이온 방출을 통한 토양개선효과에 사용되는 광물질 20중량%,붕사 3중량%,목초액 7중량%의 혼합으로 이루어지는 것을 특징으로 하는 농업용 생분해성 토양 멀칭 피복지 제조방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1067/1150 Row 1067: application_number: 1020190124261, combined_string: invention_title: 송풍 처리에 의한 토마토 접목묘의 도장 억제 방법 abstract: 본 발명은 송풍 처리에 의한 토마토 접목묘의 도장 억제 방법에 관한 것으로, 본 발명은 토마토 접목묘 육묘시 발생하는 도장 현상을 효과적으로 억제할 수 있는 친환경적인 방법으로, 본 발명의 방법을 이용하면 양질의 토마토 접목묘를 대량으로 생산할 수 있을 것으로 기대된다. claims: 토마토 접목묘를 송풍 처리하며 육묘시키는 단계를 포함하는, 토마토 접목묘의 도장을 억제하는 방법.토마토 접목묘를 송풍 처리하며 육묘시키는 단계를 포함하는, 묘소질 변화 없이 도장이 억제된 토마토 접목묘의 재배 방법.제3항 내지 제6항 중 어느 한 항의 재배 방법에 의해 재배된 묘소질 변화 없이 도장이 억제된 토마토 접목묘., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1068/1150 Row 1068: application_number: 1020190113145, combined_string: invention_title: 재배 시스템, 재배 박스 및 그 제어 방법 abstract: 하우징 및 식별 정보를 포함하고, 교체 가능한 재배 박스 및 상기 재배 박스로부터 상기 식별 정보를 획득하고, 센서를 이용하여 상기 재배 박스 내부 또는 상기 재배 박스 주변에 대한 상태 정보를 감지하며, 상기 식별 정보 및 상기 상태 정보에 기초하여 상기 재배 박스 내부로 액체를 분사하는 전자 장치를 포함하는 식물 재배 시스템이 개시된다. 이 외에도 명세서를 통해 파악되는 다양한 실시 예가 가능하다. claims: 전자 장치에 있어서,식물 재배를 위한 재배 박스가 안착되는 지지대;상기 지지대에 상기 재배 박스가 안착됨에 따라서 상기 재배 박스 내부로 삽입되는 노즐;상기 노즐을 통해서 상기 재배 박스 내부로 액체를 분사할 수 있도록 구성된 구동부를 포함하는 액체 공급 장치;상기 재배 박스 내부 또는 상기 재배 박스 주변에 대한 상태 정보를 감지하는 센서;상기 지지대에 상기 재배 박스가 안착됨에 따라서 상기 재배 박스로부터 상기 재배 박스를 식별하는 식별 정보를 획득하는 인식기; 및상기 센서, 상기 액체 공급 장치 및 상기 인식기와 연결된 프로세서를 포함하고,상기 프로세서는,상기 재배 박스가 상기 지지대에 안착된 상태에서, 상기 상태 정보 및 상기 식별 정보에 기초하여 상기 구동부의 동작 상태를 결정하고,상기 동작 상태에 기초하여 상기 재배 박스 내부로 액체가 분사되도록 상기 구동부를 제어하는, 전자 장치.식물 재배를 위한 재배 박스에 있어서,배지;상기 재배 박스를 식별하는 식별 정보를 포함하는 식별자 제공부; 및외부로부터 차단되는 내부 공간을 형성하는 하우징을 포함하고,상기 하우징은,상기 하우징 상단에 형성되어 상기 배지를 수용하는 배지 수용부,노즐을 구비하는 전자 장치에 상기 재배 박스가 안착됨에 따라서 상기 노즐을 수용하는 노즐 수용부, 및상기 전자 장치의 센서를 수용하는 센서 수용부를 포함하는, 재배 박스.식물 재배 시스템에 있어서,하우징 및 식별 정보를 포함하고, 교체 가능한 재배 박스; 및상기 재배 박스로부터 상기 식별 정보를 획득하고, 센서를 이용하여 상기 재배 박스 내부 또는 상기 재배 박스 주변에 대한 상태 정보를 감지하며, 상기 식별 정보 및 상기 상태 정보에 기초하여 상기 재배 박스 내부로 액체를 분사하는 전자 장치를 포함하는, 식물 재배 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1069/1150 Row 1069: application_number: 1020190102547, combined_string: invention_title: 가바 성분을 강화시킨 토마토의 재배방법 abstract: 본 발명은 가바 성분을 강화시킨 토마토의 재배방법에 관한 것으로서, 토마토의 과실에 함유된 가바(GABA: gamma-ammino butyric acid) 성분의 함량을 크게 증대시킬 수 있는 토마토의 재배방법에 관한 것이다.본 발명의 가바 성분을 강화시킨 토마토의 재배방법은 현미를 발아시켜 발아현미를 수득하는 발아단계와, 발아현미를 물과 함께 갈아서 발아현미액을 수득하는 분쇄단계와, 발아현미액을 꾸지뽕 발효액과 혼합하여 혼합물을 수득하는 혼합단계와, 혼합물을 토마토에 시비하여 재배하는 재배단계를 포함한다. claims: 현미를 발아시켜 발아현미를 수득하는 발아단계와;상기 발아현미를 물과 함께 갈아서 발아현미액을 수득하는 분쇄단계와;상기 발아현미액 100중량부에 대하여 꾸지뽕 발효액 50 내지 150중량부와, 초석잠 발효액 20 내지 80중량부를 혼합하여 혼합물을 수득하는 혼합단계와;상기 혼합물을 토마토에 시비하여 재배하는 재배단계;를 포함하고,상기 초석잠 발효액은 초석잠 100중량부에 대하여 유산균 0.5 내지 10중량부와, 설탕 5 내지 20중량부를 혼합하여 10 내지 30일 동안 발효시킨 것을 특징으로 하는 가바 성분을 강화시킨 토마토의 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1070/1150 Row 1070: application_number: 1020190100401, combined_string: invention_title: 유기 게르마늄 마늘 재배방법과 그 유기 게르마늄 마늘을 이용한 흑마늘 가공식품 abstract: 본 발명은 백토가 포함된 바이오 퇴비와 백토가 포함된 지장수 및 수용성 게르마늄이 포함된 기능성 재배수로 마늘을 재배하여 다량의 유기 게르마늄이 함유된 유기 게르마늄 마늘을 얻은 다음 흑마늘로 가공하여 다양한 제품으로 제조함으로써 국민건강증진에 많은 도움을 주고 농가수입 향상에 기여할 수 있도록 한 유기 게르마늄 마늘 재배방법과 그 유기 게르마늄 마늘을 이용한 흑마늘 가공식품에 관한 것으로, 유기 게르마늄 마늘 재배방법은, a) 바이오 퇴비로 지력이 배양된 경작지 약 300㎡에 5㎏의 백토를 골고루 뿌린다음 경운쇄토하여 소정 간격으로 마늘을 파종하는 단계와, b) 2~3월부터 1주일에 1~2회 백토 지장수를 마늘 주변 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계와, c) 4~5월부터 주 2회 이상 백토 지장수를 마늘 주변의 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계와, d) 마늘이 6쪽으로 바뀌는 ��부터 수용성 게르마늄 3~10㏄를 주당 2회 ~ 5회 마늘 주변의 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계와, e) 재배된 마늘을 수확하는 단계를 포함한다.본 발명에서 유기 게르마늄 마늘을 이용한 흑마늘 가공식품은, 흑마늘 건강보조식품, 흑마늘 엑기스, 흑마늘 식품 부재료, 흑마늘 소금일 수 있다. claims: a) 바이오 퇴비로 지력이 배양된 경작지 약 300㎡에 5㎏의 백토를 골고루 뿌린다음 경운쇄토하여 소정 간격으로 마늘을 파종하는 단계;b) 2~3월부터 1주일에 1~2회 백토 지장수를 마늘 주변 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계;c) 4~5월부터 주 2회 이상 백토 지장수를 마늘 주변의 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계;d) 마늘이 6쪽으로 바뀌는 ��부터 수용성 게르마늄 3~10㏄를 주당 2회 ~ 5회 마늘 주변의 토양에 관수시켜 마늘 뿌리가 흡수하도록 재배하는 단계;e) 재배된 마늘을 수확하는 단계;를 포함하는 유기 게르마늄 마늘 재배방법.청구항 1의 재배방법으로 재배 수확된 마늘을 발효 숙성시킨 흑마늘을 건조기에서 60℃ 34~48시간 제리 상태로 건조시켜서 된 유기 게르마늄 마늘을 이용한 흑마늘 가공식품.청구항 1의 재배방법으로 재배 수확된 마늘을 발효 숙성시킨 흑마늘을 발효기에 투입시켜 발효시킨 다음 압착착즙시켜 얻어지는 엑기스를 파우치에 포장하여서 된 유기 게르마늄 마늘을 이용한 흑마늘 가공식품.청구항 1의 재배방법으로 재배 수확된 마늘을 발효 숙성시킨 흑마늘을 70~80% 건조시킨 다음 소정 형상으로 절단 포장하여서 된 유기 게르마늄 마늘을 이용한 흑마늘 가공식품.청구항 1의 재배방법으로 재배 수확된 마늘을 발효 숙성시킨 흑마늘을 분말화한다음 소금을 같은 비율로 혼합시켜서 된 유기 게르마늄 마늘을 이용한 흑마늘 가공식품., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1071/1150 Row 1071: application_number: 1020190094818, combined_string: invention_title: 상추 및 치커리를 포함하는 공영식물 재배 키트 및 이를 이용한 공영식물 재배 방법 abstract: 본 발명은 상추 및 치커리를 포함하는 공영식물 재배 키트, 이를 이용한 공영식물 재배 방법, 상추 및 치커리를 포함하는 공영식물 재배방법 및 이에 의해 재배된 상추 또는 치커리를 제공한다.본 발명의 상추 및 치커리를 포함하는 공영식물 재배 키트 및 공영식물 재배 방법은 친환경 도시농업과 식물공장 분야에서 소규모의 기능성 엽채류 생산 기술로 유용하게 사용될 수 있다. claims: 상추 및 치커리를 포함하는 공영식물 재배 키트.제1항 내지 제3항 중 어느 한 항의 공영식물 재배 키트를 이용한 공영식물 재배 방법.상추 및 치커리를 포함하는 공영식물 재배 방법.제9항 내지의 제12항 중 어느 한 항의 공영식물 재배 방법으로 재배된 상추 또는 치커리., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1072/1150 Row 1072: application_number: 1020190088536, combined_string: invention_title: 작물 생육 중심의 병해충 및 기상장해 정밀관리 시스템과 그 방법 abstract: 본 발명은 작물의 생물계절(phenology)을 기반으로 병해충과 기상장해 발생위험을 군락 내 기상과 토양환경을 수집하여 수식화된 모델을 포함하고 있는 동적 시스템과 이에 대한 방법에 관한 것이다. 본 발명에 따른 작물 생육 중심의 병해충 및 기상장해 정밀관리 시스템 및 그 방법은 현재 기온으로만 위험기상을 판단하지 않고 현재 작물 생육단계가 해당 위험기상에 위험이 있을 경우에만 위험기상으로 판단함으로써 현재 재배하고 있는 작물에 따라 위험기상을 정확하게 예측할 수 있다. 또한, 본 발명에 따른 작물 생육 중심의 병해충 및 기상장해 정밀관리 시스템 및 그 방법은 현재 발생 가능한 병충해만으로 위험 병충해를 판단하지 않고 현재 작물 생육단계가 현재 발생 가능한 병충해에 위험이 있을 경우에만 위험 병충해로 판단하여 현재 재배하고 있는 작물에 따라 위험 병충해를 정확하게 예측할 수 있다. claims: 작물을 생육하고자 하는 지역의 기상 정보와 토양환경 정보를 수집하는 정보 수집 모듈과,상기 기상 정보와 토양환경 정보를 기반으로 상기 작물의 생육단계를 예측하는 생육단계 예측 모듈,상기 기상 정보와 토양환경 정보를 기반으로 발생 가능한 병해충을 예측하는 병해충 예측 모듈,상기 기상 정보를 기반으로 위험기상을 예측하는 위험기상 예측 모듈, 및상기 발생 가능한 병해충과 상기 생육단계가 매칭되거나, 상기 위험기상과 생육단계가 매칭되면 위험 경고를 수행하는 위험 판단 모듈을 포함하며,상기 정보 수집 모듈은, 상기 기상 정보를 수집하는 기상 정보 수집 모듈과, 상기 토양환경 정보를 수집하는 토양환경 정보 수집 모듈을 포함하고,상기 기상 정보는 작물이 재배되고 있는 지점에 설치된 환경계측장비로부터 수집된 기온과 상대습도, 강우량, 일사량, 일조시간, 결로 정보를 포함하며, 상기 토양환경 정보는 작물이 재배되고 있는 지점에 설치된 환경계측장비로부터 수집된 토양온도와 토양수분을 포함하고,상기 위험기상 예측 모듈은, 상기 작물이 노지에서 재배되고 있는 경우, 상기 작물이 재배되고 있는 지점의 일 최고기온이 고온해 기준 이상이거나, 상기 작물이 재배되고 있는 지점의 일 최저기온이 동해와 저온해 기준 이하이며, 상기 노지에서 재배되고 있는 작물의 생육단계가 상기 고온해, 동해 또는 저온해에 피해를 입을 수 있는 생육단계인지 판단하고,상기 위험 판단 모듈은, 상기 작물이 무가온 하우스 내에서 재배되고 있을 경우, 상기 작물이 재배되고 있는 무가온 하우스의 내부 일 최고기온이 고온해 기준 이상이거나, 상기 작물이 재배되고 있는 무가온 하우스의 내부 일 최저기온이 동해와 저온해 기준 이하이며, 상기 작물의 생육단계가 상기 고온해, 동해 또는 저온해에 피해를 입을 수 있는 생육단계일 경우 위험으로 판단하며,상기 위험기상 예측 모듈은, 상기 작물이 무가온 하우스 내에서 재배되고 있는 경우, 상기 작물이 재배되고 있는 지점에 대해서 기상청에서 제공하는 동네예보와 중기예보를 이용하여 연산하고자 하는 i일의 외부 일 누적 일사량과, 상기 작물이 재배되고 있는 무가온 하우스 내부 일 최고기온 및 일 최저기온을 연산하고,상기 i일의 외부 일 누적 일사량은,이며,상기 는 i일의 추정된 일 누적 일사량(MJ/m2),상기 는 i일의 대기외일사량(MJ/m2),상기 a, b, c, d, e, f, g, h, k는 외부 일 누적 일사량을 연산하고자 하는 지점의 최인접 지점의 모델 변수값,상기 는 i일의 일 최고기온-일 최저기온,상기 는 i일 다음 날의 ,상기 는 i일 전 날의 ,상기 는 i일 다음 날의 ,상기 는 i일 전 날의 , 상기 는 i일의 일 누적 강우량이 0.1mm 이상이면 1이고 0.1mm 미만이면 0인 작물 생육 중심의 병해충 및 기상장해 정밀관리 시스템.작물을 생육하고자 하는 지역의 기상 정보와 토양환경 정보를 정보 수집 모듈이 수집하는 단계와,상기 기상 정보와 토양환경 정보를 기반으로 상기 작물의 생육단계를 생육단계 예측 모듈이 예측하는 단계,상기 기상 정보와 토양환경 정보를 기반으로 발생 가능한 병해충을 병해충 예측 모듈이 예측하는 단계,상기 기상 정보를 기반으로 위험기상을 위험기상 예측 모듈이 예측하는 단계, 및상기 발생 가능한 병해충과 상기 생육단계가 매칭되거나, 상기 위험기상과 생육단계가 매칭되면 위험 판단 모듈이 위험 경고를 수행하는 단계를 포함하며,상기 작물을 생육하고자 하는 지역의 기상 정보와 토양환경 정보를 정보 수집 모듈이 수집하는 단계는,상기 기상 정보를 기상 정보 수집 모듈이 수집하는 단계와, 상기 토양환경 정보를 토양환경 정보 수집 모듈이 수집하는 단계를 포함하고,상기 기상 정보는 작물이 재배되고 있는 지점에 설치된 환경계측장비로부터 수집된 기온과 상대습도, 강우량, 일사량, 일조시간, 결로 정보를 포함하며, 상기 토양환경 정보는 작물이 재배되고 있는 지점에 설치된 환경계측장비로부터 수집된 토양온도와 토양수분을 포함하고,상기 기상 정보를 기반으로 위험기상을 위험기상 예측 모듈이 예측하는 단계는,상기 작물이 노지에서 재배되고 있는 경우, 상기 작물이 재배되고 있는 지점의 일 최고기온이 고온해 기준 이상이거나, 상기 작물이 재배되고 있는 지점의 일 최저기온이 동해와 저온해 기준 이하이며, 상기 노지에서 재배되고 있는 작물의 생육단계가 상기 고온해, 동해 또는 저온해에 피해를 입을 수 있는 생육단계인지 상기 위험기상 예측 모듈이 판단하고,상기 기상 정보를 기반으로 위험기상을 위험기상 예측 모듈이 예측하는 단계는,상기 작물이 무가온 하우스 내에서 재배되고 있을 경우, 상기 작물이 재배되고 있는 무가온 하우스의 내부 일 최고기온이 고온해 기준 이상이거나, 상기 작물이 재배되고 있는 무가온 하우스의 내부 일 최저기온이 동해와 저온해 기준 이하이며, 상기 작물의 생육단계가 상기 고온해, 동해 또는 저온해에 피해를 입을 수 있는 생육단계인지 상기 위험기상 예측 모듈이 판단하고,상기 기상 정보를 기반으로 위험기상을 위험기상 예측 모듈이 예측하는 단계는,상기 위험기상 예측 모듈이 상기 작물이 재배되고 있는 지점에 대해서 기상청에서 제공하는 동네예보와 중기예보를 이용하여 연산하고자 하는 i일의 외부 일 누적 일사량과, 상기 작물이 재배되고 있는 무가온 하우스 내부 일 최고기온 및 일 최저기온을 연산하는 단계를 포함하며,상기 i일의 외부 일 누적 일사량은,이며,상기 는 i일의 추정된 일 누적 일사량(MJ/m2),상기 는 i일의 대기외일사량(MJ/m2),상기 a, b, c, d, e, f, g, h, k는 외부 일 누적 일사량을 연산하고자 하는 지점의 최인접 지점의 모델 변수값,상기 는 i일의 일 최고기온-일 최저기온,상기 는 i일 다음 날의 ,상기 는 i일 전 날의 ,상기 는 i일 다음 날의 ,상기 는 i일 전 날의 , 상기 는 i일의 일 누적 강우량이 0.1mm 이상이면 1이고 0.1mm 미만이면 0인 작물 생육 중심의 병해충 및 기상장해 정밀관리 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1073/1150 Row 1073: application_number: 1020190085603, combined_string: invention_title: 수박 일소과 방지 과실덮개 abstract: 본 발명은 하절기 고온기 특히, 수박의 출하를 앞둔 시점에서 수박이 직사광선에 노출되어 일소과로 불리우는 과실데임 현상이 발생하는 문제점과, 과도한 직사광선의 노출에 의한 수박내부의 육질악질변과인 피수박의 발생과 생리장애 수박의 발생을 억제하는 재배방법과 그 재배방법에 사용되는 과실데임 현상 방지를 위한 최적의 과실덮개를 제공하고자 한다.본 발명은 상기와 같은 문제를 해결하기 위하여 하기와 같은 과제해결 수단을 제공한다. 40g/㎡ 또는 50g/㎡의 밀도를 가지는 부직포로 구성된 과실데임 방지를 위한 수박 일소과 방지 과실덮개를 고온기에 수박을 수확 전 10일 간 감싸 재배하는 것을 특징으로 하는 수박의 재배방법을 제공한다.본 발명의 과실데임 현상 방지를 위한 수박 일소과 방지 과실덮개는 노지와 비가림하우스에서 재배하는 수박을 대상으로 고온기에 수박의 직사광선에 의한 일소과 (과실데임)의 발생과 수박 내부의 육질악변과인 피수박과 생리장해 수박의 발생을 억제하는 효과가 있다. 또한, 외부로부터 과실에 영향을 미치는 목화바둑명나방 및 파밤나방 등으로부터 과실을 보호하여 해충의 피해를 줄이는 효과 또한 가지고 있다. claims: 40g/㎡ 또는 50g/㎡ 의 밀도를 가지는 부직포로 구성된 일소과(과실데임) 방지를 위한 수박 일소과 방지 과실덮개를 고온기에 수박을 수확 전 10일 간 감싸 재배하는 것을 특징으로 하는 수박 일소과 방지 과실덮개를 이용한 수박 재배방법일소과(과실데임) 방지를 위한 수박 일소과 방지 과실덮개는 과중이 8~10kg인 대과종 수박생산을 위해 반지름 34~37cm의 40g/㎡ 또는 50g/㎡의 밀도를 가지는 부직포의 가장자리에 주름 만들어 내접원주의 길이가 50~52cm가 되도록 접고, 신축 가능한 고무줄과 바느질로 결합 시키는 것을 특징으로 하는 일소과(과실데임) 방지를 위한 수박 일소과 방지 과실덮개., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1074/1150 Row 1074: application_number: 1020217009183, combined_string: invention_title: 육묘블록 abstract: 본 발명은 육묘블록에 관한 것으로, 종자에게 영양을 제공하는 영양블록(1)을 포함하고 영양블록(1)의 꼭대기부에 종자 투입 홀(2)이 개설되며, 종자 투입 홀(2) 내부에 종자 재배 홀(3)이 개설되고 종자 투입 홀(2)은 위가 크고 아래가 작은 구조로 설치되어 종자가 중력 작용하에 종자 투입 홀의 표면을 따라 종자 재배 홀(3) 내에 떨어져 들어가도록 하며, 종자 재배 홀(3) 내부에는 종자 재배 홀과 멀어지는 방향으로 연장되고 종자가 발아해 나온 뿌리에게 생장 경로를 제공하는 절개구(4)가 개설된다. 해당 육묘블록은 파종 효율을 향상시킬 수 있으며, 종자를 안정되게 고정시키고 적셔줄 수 있으며, 종자 전체의 출아율과 출아 균일도를 향상시킬 수 있어 기계화 파종에 편리하다. claims: 육묘블록에 있어서,종자에게 영양을 제공하는 영양블록(1)을 포함하고, 영양블록(1)의 꼭대기부에 종자 투입 홀(2)이 개설되며, 종자 투입 홀(2) 내부에 종자 재배 홀(3)이 개설되고, 종자 투입 홀(2)은 위가 크고 아래가 작은 구조로 설치되어 종자가 중력 작용하에 종자 투입 홀(2)의 표면을 따라 종자 재배 홀(3) 내에 떨어져 들어가도록 하며, 종자 재배 홀(3) 내부에는 종자 재배 홀(3)과 멀어지는 방향으로 연장되고, 종자가 발아해 나온 뿌리에게 생장 경로를 제공하는 절개구(4)가 개설되는 것을 특징으로 하는 육묘블록., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1075/1150 Row 1075: application_number: 1020190077873, combined_string: invention_title: 식물 재배장치 abstract: 식물 재배장치에 있어서, 상기 식물재배장치는 상부측에 2개의 가로부재와 2개의 세로부재를 4각형 구조로 결합한 상부프레임과; 상기 상부프레임의 모서리 하면 4곳에 결합되어 상부프레임을 수직으로 지지하는 포스트프레임과; 상기 포스트프레임의 하부측에 상부프레임의 폭보다 좁은 폭의 격자구조를 이루며 결합되는 지지대받침프레임과; 상기 식물 재배장치에 결합되어 식물의 줄기 또는 가지를 묶어서 지지하는 지지대와; 상기 상부프레임의 가로부재와 세로부재의 상면과 상부프레임의 세로부재 중간부에 장착되며 상기 지지대의 상부측이 끼워져 결합되는 지지대결합판을 포함하여 형성하는 식물 재배장치에 관한 발명이다. claims: 상부측에 2개의 가로부재와 2개의 세로부재를 4각형 구조로 결합한 상부프레임(1)과; 상기 상부프레임의 모서리 하면 4곳에 결합되어 상부프레임을 수직으로 지지하는 포스트프레임(2)과; 상기 포스트프레임의 하부측에 상부프레임의 폭보다 좁은 폭의 격자구조를 이루며 결합되는 지지대받침프레임(3)과; 상기 식물 재배장치에 결합되어 식물의 줄기 또는 가지를 묶어서 지지하는 지지대(4)와; 상기 상부프레임의 가로부재와 세로부재의 상면과 상부프레임의 세로부재 중간부에 장착되며 상기 지지대의 상부측이 끼워져 결합되는 지지대결합판(5)을 포함하여 형성하는 식물 재배장치에 있어서,상기 상부프레임과 포스트프레임 및 지지대받침프레임은 모두 4각형관재로 형성하고,상기 지지대받침프레임은 포스트프레임의 양측 단부 전후방 포스트를 연결하는 한쌍의 세로대(6)와 상기 한쌍의 세로대의 양측부에 상기 포스트프레임의 폭보다 좁은 간격으로 한쌍의 가로대(7)를 결합하되, 상기 한쌍의 가로대 중앙부에 하나의 간격재(8)로 칸막이를 형성하여 4각형 모양의 격자구조 2개를 형성하고,또한 상기 지지대받침프레임은 포스트프레임의 하단으로부터 25 ~ 40cm 높이에 설치하여, 높이 20cm로 형성되는 식물재배용기 하나를 하나의 4각형 모양의 격자구조 하부에 배치할 수 있도록 하며, 상기 한 쌍의 가로대와 간격재의 4각형관제 상면에는 지지대를 끼워서 설치하는 지지대삽입홀(9) 복수개를 일정간격으로 형성하여, 지지대의 하부가 상기 지지대삽입홀에 끼워지며 지지대의 하단은 지지대삽입홀의 4각형관재 밑면에 받쳐지도록 하고,상기 지지대결합판은 하단부가 상기 지지대받침프레임의 지지대삽입홀에 끼워져 장착되는 지지대의 상부측을 가압하여 고정할 수 있도록 입구는 지지대의 굵기보다 넓고 내측단부는 지지대의 굵기보다 좁은 지지대걸림구(10) 복수개를 일정간격으로 형성하며,상기 지지대 하부를 상기 지지대삽입홀에 끼우고 상부측을 지지대결합판의 지지대걸림구에 결합하여 지지대가 지지대받침프레임으로부터 상향 경사진 상태로 설치되어 상부가 확개되는 식물의 가지를 결합하거나 덩쿨식물을 상향 경사시켜 생장을 유도할 수 있도록 하는 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1076/1150 Row 1076: application_number: 1020190077112, combined_string: invention_title: 토마토 생육촉진 및 황화바이러스 방제를 위한 조성물과 이를 이용한 토마토의 재배방법 abstract: 본 발명은 토마토 생육촉진 및 황화바이러스 방제를 위한 조성물과 이를 이용한 토마토의 재배방법에 관한 것으로서, 더욱 상세하게는 리보플라빈과 백두옹 추출물을 함유하여 토마토의 생육을 촉진시키고 토마토황화바이러스의 방제에 효과가 있는 조성물을 제공함과 동시에 이를 이용하여 토마토를 재배함으로써 토마토의 생육촉진과 함께 과실에 함유된 리보플라빈의 함량을 증대시킬 수 있는 재배방법에 관한 것이다. claims: 리보플라빈 용액 20 내지 80중량%와 백두옹 추출물 20 내지 80중량%를 함유하며,토마토의 생육촉진과 황화바이러스 방제효과를 가지며,상기 황화바이러스는 토마토황화잎말림바이러스(Tomato yellow leaf curl virus; TYLCV)인 것을 특징으로 하는 토마토 생육촉진 및 황화바이러스 방제를 위한 조성물. 제 1항 또는 제 2항의 조성물을 살포하여 토마토를 재배하는 것을 특징으로 하는 토마토의 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1077/1150 Row 1077: application_number: 1020190066966, combined_string: invention_title: 포트 어셈블리 및 이를 이용한 다단식 재배장치 abstract: 본 발명은 포트마다 식재된 작물의 발근과 활착을 균일하게 하고 우수한 품질의 육묘와 재배를 동시에 구현할 수 있는 포트 어셈블리 및 이를 이용한 다단식 재배장치를 제공함에 있다. 이를 위한 본 발명은 길이를 가지며 상부 및 양단부가 개방되는 트레이; 상기 트레이의 양단부에 결합되며, 상기 트레이의 내부에 채워지는 공급액이 배출되는 배출공이 구비되는 측면커버; 상기 트레이의 상부를 향해 삽입하여 배치되며, 작물이 식재되는 복수의 개별포트가 구비되는 육묘포트; 및 상기 육묘포트의 일측에 배치되도록 상기 트레이와 결합되며, 상기 작물과 연결되는 줄기를 유인 및 고정시키기 위한 줄기가이드;를 포함하는 포트 어셈블리 및 이를 이용한 다단식 재배장치의 특징을 개시한다. claims: 길이를 가지며, 상부 및 양단부가 개방되는 트레이;상기 트레이의 양단부에 결합되며, 상기 트레이의 내부에 채워지는 공급액이 배출되는 배출공이 구비되는 측면커버;상기 트레이의 상부를 향해 삽입하여 배치되며, 작물이 식재되는 복수의 개별포트가 구비되는 육묘포트; 및상기 육묘포트의 일측에 배치되도록 상기 트레이와 결합되며, 상기 작물과 연결되는 줄기를 유인 및 고정시키기 위한 줄기가이드;를 포함하는 것을 특징으로 하는 포트 어셈블리.지면으로부터 이격 배치되는 한 쌍의 수평프레임 및 상기 수평프레임의 하측에 배치되며 지면으로부터 상기 수평프레임을 향해 경사지게 배치되는 한 쌍의 경사프레임을 포함하는 프레임유닛;상기 수평프레임에 안착되는 모판;상기 경사프레임에 결합되는 한 쌍의 지지대유닛; 및상기 지지대유닛에 양단부가 지지되는 제1항에 기재된 포트 어셈블리;를 포함하는 것을 특징으로 하는 다단식 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1078/1150 Row 1078: application_number: 1020190066323, combined_string: invention_title: 식물재배용기를 이용한 재배 시스템 abstract: 본 발명은 순환관을 통해 온수 또는 냉수를 공급하여 용기본체 내부의 온도를 작물에 적합한 온도로 유지되게 제어함으로써, 작물의 생장을 촉진하고 과실의 품질을 향상시킬 수 있는 식물재배용기를 이용한 재배 시스템을 제공하기 위한 것이다.본 발명의 식물재배용기는, 상단이 개방되어 내부에 재배할 식물이 수용되며, 하단 폭이 상단 폭 보다 좁게 형성되는 용기본체(110); 상기 용기본체(110)의 양측 상단에 하향 경사지게 연장 형성된 줄기지지대(120); 상기 용기본체(110)의 하단 중심부에 길이 방향으로 개방 형성되며, 상기 용기본체(110)의 내부에 공급된 수분이 배출되는 배수관(130); 상기 용기본체(110)의 하단 양측에 구비되며, 내부에 냉각수 또는 난방수가 공급되는 순환관(140); 을 포함한다. claims: 상단이 개방되어 내부에 재배할 식물이 수용되며, 하단 폭이 상단 폭 보다 좁게 형성되는 용기본체(110); 상기 용기본체(110)의 양단에 하향 경사지게 연장 형성된 줄기지지대(120); 상기 용기본체(110)의 하단 중심부에 길이 방향으로 개방 형성되며, 상기 용기본체(110)의 내부에 공급된 수분이 배출되는 배수관(130); 상기 용기본체(110)의 하단 양측에 구비되며 내부에 냉각수 또는 난방수가 공급되는 순환관(140); 을 포함하는 식물재배용기(100)를 이용한 재배 시스템에 있어서,상기 용기본체(110)에 일정 시간 간격으로 수분을 공급하는 관수장치(200);상기 배수관(130)에 냉풍 또는 온풍을 공급하는 공기공급장치(300); 상기 용기본체(110)의 내부에 장착되는 온도센서(400); 상기 관수장치(200)와 공기공급장치(300)의 작동을 제어하는 제어장치(600); 를 포함하되, 상기 제어장치(600)는 상기 관수장치(200)의 작동시 상기 공기공급장치(300)를 정지시키고, 상기 관수장치(200)가 수분을 공급하고 일정 시간이 경과한 후 상기 공기공급장치(300)를 작동시키도록 제어하는 것을 특징으로 하는 식물재배용기를 이용한 재배 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1079/1150 Row 1079: application_number: 1020190052910, combined_string: invention_title: 식물 재배 장치 abstract: 본 발명의 일 실시예는 재배상을 수직으로 일괄 적층 거치할 수 있도록 함과 동시에 재배환경 내 광 균일성을 확보하여 최대 효율의 광 조사량을 가지도록 하여 치묘 또는 이끼식물 등의 식물을 효율적으로 재배할 수 있도록, 하부에 위치되는 하부받침부; 상기 하부받침부의 상부에 상하 방향으로 겹침 및 펼침 가능하게 적층되는 다수의 재배상거치대들을 가지는 재배상거치부; 및 상기 재배상거치대(210)들을 겹쳐진 상태로 적층시키거나, 서로 상하로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 및 밀착되어 지그 재그 형상으로 펼쳐지도록 지지하는 지지부;를 포함하여 구성되는 식물 재배 장치를 제공한다. claims: 하부에 위치되는 하부받침부;상기 하부받침부의 상부에 상하 방향으로 겹침 및 펼침 가능하게 적층되는 다수의 재배상거치대들을 가지는 재배상거치부; 및상기 재배상거치대(210)들을 겹쳐진 상태로 적층시키거나, 서로 상하로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 및 밀착되어 지그 재그 형상으로 펼쳐지도록 지지하는 지지부;를 포함하여 구성되는 것을 특징으로 하는 식물 재배 장치.상부면의 모서리들에서 서로 대향하는 방향으로 다수의 도르레가 상방향으로 설치되어 하부에 위치되는 하부받침부;상기 하부받침부의 상부에 상하 방향으로 겹침 및 펼침 가능하게 적층되는 다수의 재배상거치대들을 가지는 재배상거치부;저면의 모서리들에 상기 하부받침부에 설치된 상기 다수의 도르레들과 하 방향으로 대향하도록 다수의 도르레들이 설치되어 상기 재배상거치부의 상부에 위치되는 상부고정부; 및상기 하부받침부의 상기 도르레가 설치된 인접 위치들에 일단부가 고정된 후 상기 재배상거치대들에 형성된 재배상 지지부재 삽입홀들에 삽입된 후 상기 상부고정부에 설치된 도르레를 거쳐 상기 하부받침부에 설치된 도르레들에 걸리어져 상기 재배상거치대들을 지지하는 다수의 지지부재(310)들을 가지는 지지부;를 포함하여 구성되어,상기 지지부재들의 자유단부를 당기는 경우, 상기 재배상거치대들의 서로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 및 밀착되어 지그 재그 형상으로 펼쳐지는 것을 특징으로 하는 식물 재배 장치.하부에 위치되는 하부받침부;상기 하부받침부의 상부에 상하 방향으로 겹침 및 펼침 가능하게 적층되는 다수의 재배상거치대들을 가지는 재배상거치부; 및상기 재배상거치대들을 겹쳐진 상태로 적층시키거나, 서로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 및 밀착되어 지그 재그 형상으로 펼쳐지도록 지지하는 지지부;를 포함하는 다수의 단위 식물 재배장치들이,상기 지지부에 의해 상기 재배상거치대(210)들이 서로 대향하는 측부 모서리가 상하 방향으로 교대로 이격 또는 밀착되어 지그 재그 형상으로 펼쳐짐과 동시에 상기 재배상거치대들이 인접된 상기 단위 식물 재배장치들의 재배상거치대들과 마름모 형상을 이루도록 열을 이루며 배치되도록 구성되는 것을 특징으로 하는 식물 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1080/1150 Row 1080: application_number: 1020190051433, combined_string: invention_title: 과실수의 가지유인추 abstract: 본 발명은 가지유인추의 조립이 보다 간편하게 이루어질 수 있고 생산효율을 향상시킬 수 있도록 전체적인 결합구조를 개선한 가지유인추를 제공한다. 본 발명은, 제1중량추 및 제2중량추와, 상기 제1중량추 및 제2중량추의 하단부에 각각 형성된 제1파지부 및 제2파지부와, 상기 제1중량추와 상기 제2중량추의 서로 마주보는 면에 각각 형성되어 서로 접촉결합됨으로써 제1중량추와 제2중량추가 회전하는 중심축의 역할을 하는 제1회전축부 및 제2회전축부와, 탄성스트립 또는 탄성와이어가 절곡되어 형성되는 것으로서, 상기 제1중량추 및 제2중량추의 각 상단부에 양단이 각각 결합되고, 상기 제1중량추와 제2중량추 사이에 상방으로 개방되는 가지수용부가 위치하도록 절곡된 탄성부재를 포함한다. claims: 가지(51)에 걸어 가지(51)가 향하는 방향을 유인하는 과실수의 가지유인추에 있어서,소정의 무게를 가지고 서로 분할된 제1중량추(10) 및 제2중량추(20)와,상기 제1중량추(10)의 하단부와 상기 제2중량추(20)의 하단부에 각각 형성되어 손가락으로 잡는 제1파지부(11) 및 제2파지부(21)와,상기 제1중량추(10)와 상기 제2중량추(20)의 서로 마주보는 면(16,26)에 각각 형성되어 서로 접촉결합됨으로써 상기 제1중량추(10)와 상기 제2중량추(20)가 회전하는 중심축의 역할을 하는 제1회전축부(15) 및 제2회전축부(25)와,탄성스트립 또는 탄성와이어가 절곡되어 형성되는 것으로서, 상기 제1중량추(10)의 상단부와 상기 제2중량추(20)의 상단부에 양단이 각각 결합되고, 상기 제1중량추(10)와 상기 제2중량추(20) 사이에 상방으로 개방되는 가지수용부(31)가 위치하도록 절곡된 탄성부재(30)를 포함하고,상기 탄성부재(30)는, 양 측단에 각각 상하로 연장되도록 형성되어 상기 제1중량추(10)의 상단부와 상기 제2중량추(20)의 상단부의 각 끼움홈(13,23)에 각각 끼워지는 양측 결합부(34a,34b)와, 상기 양측 결합부(34a,34b)로부터 중심부로 각각 연장되어 서로 모이는 양측 연장부(33a,33b)와, 상기 제1회전축부(15) 및 제2회전축부(25)의 상측에 위치하고 중심부에 모인 양측 연장부(33a,33b)가 하측방향으로 연장되어 가지(51)를 둘러싸도록 형성되는 상기 가지수용부(31)를 포함하며,상기 양측 결합부(34a,34b)는 외력이 없는 상태에서 중심부를 향해 모이도록 수직면에 대하여 경사지게 상하방향으로 연장되고, 상기 끼움홈(13,23)은 수직으로 형성되며,상기 제1회전축부(15) 및 제2회전축부(25)는, 그 중 하나가 볼록한 돌출면(15a)을 형성하고 다른 하나가 오목한 수용면(25a)을 형성하여 서로 접촉한 상태로 상기 탄성부재(30)에 의해 결합된 것을 특징으로 하는 과실수의 가지유인추, Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1081/1150 Row 1081: application_number: 1020190048349, combined_string: invention_title: 곧은 뿌리 식물 재배 시스템 abstract: 본 발명은 곧은 뿌리 식물 재배 시스템에 관한 것으로, 구체적으로는 감초(甘草), 적하수오나 백하수오(何首烏), 당삼(堂參), 당귀(當歸), 황기(黃耆), 길경(桔梗) 또는 그 외의 곧은 뿌리(直根) 식물의 재배 용기를 세워진 채로 조밀하게 배치하여 단위 면적 당 재배량을 증가시키고, 수확시 소요되는 노동력을 최소화할 수 있으며, 재배 용기가 쓰러지지 않도록 하여 유지관리에 편리한 곧은 뿌리 식물 재배 시스템에 관한 것이다.본 발명은 내부에 흙이 수용되고, 상단과 하단이 개방되되 상광하협의 통 형태로 이루어지는 재배 용기; 및 상기 재배 용기가 세워진 채로 끼워지도록 복수의 끼움공이 소정 간격으로 이격되어 관통 형성되어 수평으로 배치되는 지지 플레이트와, 상기 끼움공을 통해 끼워진 재배 용기를 지지하도록 상기 지지 플레이트의 저면에서 상기 끼움공 둘레로부터 세로 방향으로 소정 길이로 연장되되 상기 끼움공 둘레를 따라 상호 간 이격되게 복수로 형성되는 지지 리브와, 상기 복수로 연장 형성된 지지 리브의 하단이 결합되되 상기 지지 플레이트의 저면과 평행하게 수평으로 형성되는 받침 플레이트로 구성되는 단위 지지틀;을 포함하고, 상기 단위 지지틀은 복수로 마련되어 상호 착탈 가능하게 이루어지는 것을 특징으로 하는 곧은 뿌리 식물 재배 시스템을 제공한다. claims: 내부에 흙이 수용되고, 상단과 하단이 개방되되 상광하협의 통 형태로 이루어지는 재배 용기; 및상기 재배 용기가 세워진 채로 끼워지도록 복수의 끼움공이 소정 간격으로 이격되어 관통 형성되어 수평으로 배치되는 지지 플레이트와, 상기 끼움공을 통해 끼워진 재배 용기를 지지하도록 상기 지지 플레이트의 저면에서 상기 끼움공 둘레로부터 세로 방향으로 소정 길이로 연장되되 상기 끼움공 둘레를 따라 상호 간 이격되게 복수로 형성되는 지지 리브와, 상기 복수로 연장 형성된 지지 리브의 하단이 결합되되 상기 지지 플레이트의 저면과 평행하게 수평으로 형성되는 받침 플레이트로 구성되는 단위 지지틀;을 포함하고,상기 재배 용기는,제1상단과 제1하단이 개방되되 상광하협의 통 형태로 이루어지는 상부 용기; 및제2상단과 제2하단이 개방되되 상광하협의 통 형태로 이루어지고, 상기 제2상단을 포함하는 제2상부 외면이 상기 상부 용기의 제1하단을 포함하는 제1하부 내면과 면접촉하면서 결합되도록 이루어진 하부 용기;를 포함하며,상기 상부 용기와 하부 용기가 결합된 상태로 상기 끼움공을 통해 상기 하부 용기와 상부 용기가 끼워지는 경우, 상기 하부 용기의 하단은 상기 받침 플레이트와 접촉하고 상기 끼움공의 직경은 상기 상부용기의 제1상부의 직경보다 작게 이루어져 상기 상부 용기의 제1상부는 상기 지지 플레이트의 상부로 노출되며,상기 단위 지지틀은 복수로 마련되어 상호 착탈 가능하게 이루어지되, 상기 단위 지지틀의 지지 플레이트는 소정 두께를 가지는 육면체 형태로 이루어지고, 상기 지지 플레이트의 네 측면에는 소정 형태로 결합 돌기가 돌출 형성되거나 상기 결합 돌기와 대응되게 결합홈이 형성되는 것을 특징으로 하는 곧은 뿌리 식물 재배 시스템., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1082/1150 Row 1082: application_number: 1020190048059, combined_string: invention_title: 줄기 작물 재배용 화분 abstract: 본 발명에 따른 줄기 작물 재배용 화분은, 작물이 심어지는 화분 본체와, 상기 화분 본체에 결합되어 작물이 타고 올라올 수 있게 선형 부재를 지지하는 지지대를 포함하여 구성됨으로써, 간단한 구조로 토마토 등 줄기 작물을 용이하게 재배할 수 있는 효과를 제공한다. claims: 작물이 심어지는 화분 본체와, 상기 화분 본체에 결합되어 작물이 타고 올라올 수 있게 선형 부재를 지지하는 지지대를 포함한 것을 특징으로 하는 줄기 작물 재배용 화분., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1083/1150 Row 1083: application_number: 1020190033229, combined_string: invention_title: 딸기 재배용 화분 배수 받침대 abstract: 본 발명은 딸기 재배용 화분 배수 받침대에 관한 것으로, 그 구성은 평평한 판 형상을 가지며, 양측 각각에는 제1배수패널이 직립되게 세워져 내부에 중앙 배수로를 형성하되, 상기 제1배수패널이 딸기 작물이 재배되는 화분을 지지 고정하여 화분의 하부를 통해 배수되는 물이 자연스럽게 중앙 배수로로 유통되도록 하는 다수의 받침 배수판;과, 상기 받침 배수판과 인접하는 다른 받침 배수판을 서로 연결하여 상기 받침 배수판의 안정적인 연결을 유도하는 연결수단;으로 구성된 것을 특징으로 하는 것으로서, 내부에 중앙 배수로가 형성된 다수의 받침 배수판을 연결수단을 통해 지면에 간편히 연결 설치하고, 그 설치된 받침 배수판 상부에 딸기 재배를 위한 화분을 적층 안치함으로, 딸기의 성장을 위해 화분으로 뿌려지는 물은 화분의 하부를 통해 자연스럽게 중앙 배수로로 유통 배출되어 농양성분이 물과 함께 토양으로 침투하는 것을 안정적으로 방지할 수 있어 토양의 황폐화 및 오염을 효과적으로 예방할 수 있을 뿐만 아니라, 종래와 같이 지면에 골과 같은 배수로를 구축할 필요가 없어 배수로로 구축된 골이 붕괴되어 발생할 수 있는 다양한 문제점을 미연에 방지하여 딸기 작물의 안정적인 재배를 유도할 수 있는 효과가 있다.또한, 받침 배수판에 형성되는 중앙 배수로와 함께 외곽 배수로를 형성함으로 화분을 관통하여 화분 아래로 배출되는 물은 중앙 배수로에서 수집 배수하고 화분을 넘치는 일부의 물은 외곽 배수로에서 수집 배수하여 매우 안정적인 배수성을 확보할 수 있을 뿐만 아니라, 중앙 배수로를 형성하는 제1배수패널은 화분을 지지 고정하는 기능을 수행함으로 화분의 용이한 배치 및 설치를 유도할 수 있어 작업자에게 딸기 재배의 편의성을 제공할 수 있는 효과가 있다. claims: 평평한 판 형상을 가지며, 양측 각각에는 제1배수패널(11)이 직립되게 세워져 내부에 중앙 배수로(12)를 형성하되, 상기 제1배수패널(11)이 딸기 작물이 재배되는 화분(1)을 지지 고정하여 화분(1)의 하부를 통해 배수되는 물이 자연스럽게 중앙 배수로(12)로 유통되도록 하는 다수의 받침 배수판(10); 및상기 받침 배수판(10)과 인접하는 다른 받침 배수판(10)을 서로 연결하여 상기 받침 배수판(10)의 안정적인 연결을 유도하는 연결수단(20);을 포함하여 구성되는 것을 특징으로 하는 딸기 재배용 화분 배수 받침대., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1084/1150 Row 1084: application_number: 1020190033116, combined_string: invention_title: 식물 재배 장치 abstract: 본 발명은 식물 재배 장치에 관한 것이다. 일 측면에 따른 식물 재배 장치는, 내부에 재배실이 구비되며, 일면이 개구되는 몸체; 상기 몸체의 개구된 일면을 차폐하는 도어; 상기 재배실의 하방에 배치되며, 식물이 파종되는 재배 베드; 상기 재배실의 상방에 배치되며, 상기 재배 베드로 광을 조사하는 광원 모듈; 및 상기 재배 베드와 광원 모듈의 사이에서 이동되며, 상기 광원 모듈에서 조사되는 광의 일부가 상기 재배 베드에 파종된 식물의 생장점으로 조사되도록 하는 광 가이드를 포함하는 것을 특징으로 한다. claims: 내부에 재배실이 구비되며, 일면이 개구되는 몸체;상기 몸체의 개구된 일면을 차폐하는 도어;상기 재배실의 하방에 배치되며, 식물이 파종되는 재배 베드;상기 재배실의 상방에 배치되며, 상기 재배 베드로 광을 조사하는 광원 모듈; 및상기 재배 베드와 광원 모듈의 사이에서 이동되며, 상기 광원 모듈에서 조사되는 광의 일부가 상기 재배 베드에 파종된 식물의 생장점으로 전달되도록 하는 광 가이드를 포함하는 식물 재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1085/1150 Row 1085: application_number: 1020190031025, combined_string: invention_title: 딸기 재배용 접이식 육묘 장치 abstract: 본 발명은 딸기 재배용 접이식 육묘 장치에 관한 것으로, 베드 하방을 지지하는 구조물에 연결되며, 판상으로 마련되며 상부가 후방으로 절곡되고 상부에는 원형의 제 1구멍과 하부에는 장공의 제 2구멍이 마련되는 연결부와, 상기 연결부 끝단에 마련되며, 판상으로 상부가 후방으로 절곡되는 지지부와, 상기 연결부와 상기 지지부 사이에 마련되며, 상기 지지부가 접히도록 회전하는 힌지부로 구성되는 것을 특징으로 한다. claims: 베드 하방을 지지하는 구조물에 연결되며, 판상으로 마련되며 상부가 후방으로 절곡되고 상부에는 원형의 제 1구멍과 하부에는 장공의 제 2구멍이 마련되는 연결부;상기 연결부 끝단에 마련되며, 판상으로 상부가 후방으로 절곡되는 지지부;상기 연결부와 상기 지지부 사이에 마련되며, 상기 지지부가 접히도록 회전하는 힌지부;로 구성되는 것을 특징으로 하며,상기 제 2구멍의 가로축은 상기 제 1구멍의 중심을 기준으로 하방으로 일정거리 떨어지고, 좌측으로 회전시켜 얻은 원형의 자취인 것을 특징으로 하며,상기 연결부와 상기 지지부 하부에는 고정부가 더 마련되며, 균등한 간격으로 갈고리 모양의 홈이 마련되는 것을 특징으로 하며,상기 지지부 끝단 상부에 마련되는 돌출부를 더 포함하는 것을 특징으로 하는 딸기 재배용 접이식 육묘 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1086/1150 Row 1086: application_number: 1020190029607, combined_string: invention_title: 딸기모종 분화 촉진방법 abstract: 본 발명은 지하로부터의 지하수를 펌핑하여 지상의 저수통에 보관하는 제1단계와, 지상의 저수통에 보관된 지하수를 냉교반기를 이용하여 냉기를 추출하는 제2단계와, 추출된 냉기를 냉기 공급관을 이용하여 딸기의 모종의 상토에 공급하는 제3단계 및 상토에 구성된 온도 센서의 측정값 일정치 이상이 되면 압력에 의해 냉기가 자동으로 공급되는 제4단계로 이루어지는 것을 특징으로 하며, 딸기 분화촉진을 위하여 상토에 직접 냉풍을 공급하여 상토의 온도를 낮춰주므로 모종의 활력증진으로 딸기의 상품성강화에 따른 농가수확을 증대시킬 수 있는 효과가 있다. claims: 지하로부터의 지하수를 펌핑하여 지상의 저수통에 보관하는 제1단계;지상의 저수통에 보관된 지하수를 냉교반기를 이용하여 냉기를 추출하는 제2단계;추출된 냉기를 냉기 공급관을 이용하여 딸기의 모종의 상토에 공급하는 제3단계;상토에 구성된 온도 센서의 측정값 일정치 이상이 되면 압력에 의해 냉기가 자동으로 공급되는 제4단계로 이루어지는 것을 특징으로 하는 딸기모종 분화 촉진방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1087/1150 Row 1087: application_number: 1020190026718, combined_string: invention_title: 작물 재배 시스템 abstract: 본 발명은 경작자가 파종에서부터 수확에 이르는 전 과정을 특정한 지점에서 일괄적으로 처리할 수 있는 작물재배용기의 순환이동을 통하여 넓은 면적을 이동하지 않고, 허리를 구부리거나 쭈그려 앉는 등의 일체의 노동 없이 영농이 가능하도록 한 작물 재배 시스템에 관한 것으로서, 전후좌우로 이동가능한 판상의 하부프레임(100)과, 상기 판상의 하부프레임(10)의 사각모퉁이에 세워진 사각 기둥 프레임(200)과, 상기 판상의 하부프레임(10)의 상면에 설치되는 작물 재배장치(300)로 이루어진 것을 특징으로 하고, 상기 작물 재배장치(300)는, 서로 대향되게 세워진 한 쌍의 기어프레임(310)과, 상기 한 쌍의 기어프레임(310) 내의 상부 및 하부에 내장되어 모터(M)에 의해 구동되는 스프로킷(320)과, 상기 상부 및 하부 스프로킷(320)에 감겨진 벨트(330)와, 상기 벨트(330)의 내측면에 서로 대칭되게 부착된 수평힌지부재(340)와, 상기 한 쌍의 수평힌지부재(340)의 사이에 회전 가능하게 설치된 회전봉(350)과, 상기 회전봉(350)의 하단에 각각 연결된 작물재배트레이(360)로 이루어진 것을 특징으로 한다. claims: 전후좌우로 이동가능한 판상의 하부프레임(100)과;상기 판상의 하부프레임(10)의 사각모퉁이에 세워진 사각 기둥 프레임(200)과;상기 판상의 하부프레임(10)의 상면에 설치되는 작물 재배장치(300)로 이루어진 것을 특징으로 하는 작물 재배 시스템., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1088/1150 Row 1088: application_number: 1020190013436, combined_string: invention_title: 더덕 재배방법 및 장치 abstract: 본 발명은 더덕을 식재할 수 있도록 성장토를 채워넣는 장치바디와; 상기 장치바디의 외면에 피복하여 외부기온이 성장토로 전달되는 것을 방지하는 외기차단체와; 상기 외기차단체의 외부와 장치바디의 상면에 설치하여 식재된 더덕으로 햇빛이 직접 조사되는 것을 방지하면서 더덕 성장에 방해가 되는 잡초의 성장을 억제하는 마감피복체와; 상기 장치바디를 길이방향으로 길게 연결하여 두둑과 같은 형태를 유지하는 재배라인과; 상기 재배라인의 길이방향으로 식재된 더덕으로 성장에 필요한 성장수를 공급하도록 배설하는 관수라인과; 상기 장치바디와 장치바디 사이에 설치하여 더덕 줄기가 위로 뻗어갈 수 있게하는 줄기유도체를 포함하여 더덕재배장치를 구성하고;상기 더덕재배장치를 조성하는 더덕재배장치조성단계와; 더덕재배장치에 재배하고자 하는 더덕의 씨앗을 파종하거나 종묘를 식재하는 식재단게와; 식재된 더덕에 공급할 액비를 만드는 액비제조단계와; 액비와 수분 등을 더덕으로 주기적으로 공급하여 성장시키는 재배단계와; 재배된 더덕을 수확하는 수확단계로 재배하는 것이 특징이다. claims: 지면에 두둑형태를 유지하는 더덕재배장치(100)를 조성하는 더덕재배장치조성단계(S100)와;조성된 더덕재배장치(100)에 재배하고자 하는 더덕(101)의 씨앗을 파종하거나 종묘를 식재하는 식재단게(S200)와;더덕재배장치(100)에 식재된 더덕(101)에 공급할 액비를 만드는 액비제조단계(S300)와;제조된 액비와 수분 등을 더덕(101)으로 주기적으로 공급하여 성장시키는 재배단계(S400)와;재배된 더덕(101)을 수확하는 수확단계(S500)로 이루어지는 것을 특징으로 하는 더덕재배방법.상부에 더덕(101)을 식재할 수 있도록 상부개방부(102)를 두고 하부는 지면과 연통될 수 있는 하부개방부(103)를 가지고 내부에는 더덕(101)의 성장에 필요한 성장토(104)를 채워넣을 수 있도록 성장토공간(105)을 가지는 장치바디(106)와;상기 장치바디(106)의 외면에 피복하여 외부기온이 성장토(104)로 전달되어 장치바디(106)의 가장자리에 식재된 더덕(101)이 하절기에 열사하고 동절기에 동사하는 것을 방지하는 외기차단체(107)와;상기 외기차단체(107)의 외부와 장치바디(106)의 상면에 설치하여 식재된 더덕(101)으로 햇빛이 직접 조사되는 것을 방지하면서 더덕 성장에 방해가 되는 잡초의 성장을 억제하는 마감피복체(108)와;상기 장치바디(106)를 길이방향으로 길게 연결하여 두둑과 같은 형태를 유지하는 재배라인(110)과;상기 재배라인(110)의 길이방향으로 식재된 더덕(101)으로 성장에 필요한 성장수를 공급할 수 있도록 각각의 더덕(101) 방향으로 분사공(111)을 형성하여 배설하는 관수라인(112)과;상기 장치바디(106)와 장치바디(106) 사이에 고정하는 지주목(113)과, 지주목(113)의 상단에 재배라인(110) 방향의 길이로 연결하는 수평바(114)와, 수평바(114)의 양측에 성장하는 더덕(101)의 줄기가 위로 뻗어갈 수 있도록 연결하는 유도와이어(116)로 구성하는 줄기유도체(117)를 포함하는 것을 특징으로 하는 더덕재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1089/1150 Row 1089: application_number: 1020190012593, combined_string: invention_title: 셀레늄 또는 게르마늄 고함유 프리미엄 작물의 재배 방법 abstract: 본 발명은 셀레늄 또는 게르마늄 강화 작물의 재배 방법에 대한 것으로, 셀레늄 또는 게르마늄의 살포 시기를 최적화하여 셀레늄 또는 게르마늄 함량이 강화된 작물을 제공할 수 있다. claims: 셀레늄, 게르마늄 또는 이들의 조합을 작물에 2회 내지 4회 살포하는 것을 포하는 작물의 재배 방법. 제 1 항 내지 제 11 항 중 어느 한 항의 방법에 의해 재배된 셀레늄 또는 게르마늄 강화 작물., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1090/1150 Row 1090: application_number: 1020210110983, combined_string: invention_title: 기능성이 향상된 메밀싹 및 새싹채소의 재배방법 abstract: 본 발명은 약용식물을 선별하고 가공하는 단계; 상기 가공한 약용식물을 혼합한 후 추출 및 희석하여 약용식물 희석액을 제조하는 단계; 및 메밀종자를 파종한 후, 파종 상토에 상기 제조한 약용식물 희석액을 분무하면서 특정 온도 및 광조건에서 재배하는 단계를 포함하는 메밀싹의 재배방법 및 상기 방법으로 재배한 메밀싹에 관한 것이다. claims: (1) 녹차, 짚신나물, 마디풀 및 소리쟁이를 각각 증열처리하고 건조하여 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이를 제조하는 단계;(2) 상기 (1)단계의 제조한 건조 녹차, 건조 짚신나물, 건조 마디풀 및 건조 소리쟁이와 커피 분말을 혼합하여 약용식물 혼합물을 제조하는 단계;(3) 상기 (2)단계의 제조한 약용식물 혼합물에 물을 첨가하여 추출한 후 여과하여 약용식물 혼합 추출액을 제조하는 단계;(4) 상기 (3)단계의 제조한 약용식물 혼합 추출액에 물을 첨가하여 약용식물 희석액을 제조하는 단계; 및(5) 메밀종자를 파종한 후, 파종 상토에 상기 (4)단계의 제조한 약용식물 희석액을 분무하면서 재배하는 단계를 포함하는 메밀싹의 재배방법.제1항 내지 제3항 중 어느 한 항의 방법으로 재배된 메밀싹., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1091/1150 Row 1091: application_number: 1020210041526, combined_string: invention_title: 수경재배 베드 및 뿌리 생장 정보를 이용한 수경재배 방법 abstract: 본 발명은 수경재배 베드에 관한 것으로, 수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어한다. claims: 수경재배 장치에 사용되는 수경재배 베드에 있어서, 상기 수경재배 장치에서 양액을 공급 받고, 식물이 수용되는 베드; 상기 베드의 측면 상부에 형성되어 상기 양액을 배출하는 제1 배출구; 상기 베드의 하단에 형성되어 상기 양액을 배출하는 제2 배출구; 및 상기 제2 배출구를 통한 상기 양액의 배출 여부를 조절하는 밸브;를 포함하되, 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 제1 배출구 또는 상기 제2 배출구를 통해 배출되도록 상기 밸브를 제어하고, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 1]을 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 수경재배 베드. [수식 1] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.) 수경재배 장치에서 식물이 수용되는 베드로 양액을 공급하는 단계; 및 상기 수경재배 장치가 상기 식물의 뿌리 생장을 판단하여 상기 양액이 상기 베드의 측면 상부에 형성된 제1 배출구 또는 상기 베드의 하단에 형성된 제2 배출구를 통해 배출되도록 밸브를 제어하는 단계;를 포함하되, 상기 뿌리 생장의 판단은, 상기 수경재배 장치가 상기 제1 배출구를 통해 배출될 때의 상기 양액 및 상기 제2 배출구를 통해 배출될 때의 상기 양액에 대한 각각의 식물 뿌리의 이온 흡수율을 아래 [수식 2]를 이용해 분석하여, 상기 분석한 각각의 식물 뿌리의 이온 흡수율의 괴리율을 바탕으로 판단하는 것 을 특징으로 하는 뿌리 생장 정보를 이용한 수경재배 방법. [수식 2] (여기서, 은 뿌리 내부의 ion이라는 이름의 이온의 시간에 따른 조성변화, 은 이온의 물리적 특성으로 는 확산 상수, M은 분자량(단원자 이온의 경우에는 원자량)이며, 는 이온의 전기적 특성, 은 Goldman의 방정식으로 계산되는 식물 뿌리와 주변 사이의 상호 작용에 대한 계수이며, 는 식물종에 대한 계수, S는 이온이 흐르는 표면적으로 식물 성장에 대한 계수이다.), Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1092/1150 Row 1092: application_number: 1020210005654, combined_string: invention_title: 새싹보리순 자동 수확장치 abstract: 본 발명은 적어도 하나의 휠(112)이 장착되며, 구동모듈(114)이 내장되는 베이스프레임(110); 상기 베이스프레임(110) 상에 위치되는 수확모듈(120)로서, 전방을 향해 소정의 기울기를 갖도록 형성된 컨베이어부(122) 및 상기 컨베이어부(122)의 전단부 측에 위치되어 하방의 예취대상물을 예취시키는 예취부(124)를 포함하며, 상기 컨베이어부(122)의 전단부 측으로부터 후단부 측으로 예취물을 이송시키는, 수확모듈(120); 상기 베이스프레임(110) 상에 위치되되, 상기 컨베이어부(122)의 후단부 측에 형성되며, 수거수단이 위치되는 공간을 제공하는 포집공간부(130)로서, 상기 컨베이어부(122)에 의해 이송된 예취물을 상기 수거수단으로 포집시키는, 포집공간부(130); 및 상기 베이스프레임(110)의 후단에 위치되며, 상기 휠(112) 및 수확모듈(120)의 동작을 제어하는 제어모듈(140); 을 포함하는, 자동 수확장치를 제공한다. claims: 폭 방향으로 한 쌍의 휠(112)이 장착되며, 유압펌프(114b) 및 상기 유압펌프(114b)와 연결된 한 쌍의 유압모터(114a)를 구비하는 구동모듈(114)이 내장되는 베이스프레임(110); 상기 베이스프레임(110) 상에 위치되는 수확모듈(120)로서, 전방을 향해 소정의 기울기를 갖도록 형성된 컨베이어부(122) 및 상기 컨베이어부(122)의 전단부 측에 위치되어 하방의 예취대상물을 예취시키는 예취부(124)를 포함하며, 상기 컨베이어부(122)의 전단부 측으로부터 후단부 측으로 예취물을 이송시키는, 수확모듈(120); 상기 베이스프레임(110) 상에 위치되되, 상기 컨베이어부(122)의 후단부 측에 형성되며, 수거수단이 위치되는 공간을 제공하는 포집공간부(130)로서, 상기 컨베이어부(122)에 의해 이송된 예취물을 상기 수거수단으로 포집시키는, 포집공간부(130); 및 상기 베이스프레임(110)의 후단에 위치되며, 상기 휠(112) 및 수확모듈(120)의 동작을 제어하는 제어모듈(140);을 포함하고,상기 베이스프레임(110)에서 포집공간부(130)의 전단에 결합되되, 상기 베이스프레임(110)의 폭방향을 기준으로, 양측 단부에서, 수직방향으로 소정의 길이만큼 연장되는 트러스프레임(150)을 더 포함하고, 상기 트러스프레임(150)의 상부에는, 상기 컨베이어부(122)가 결합되며,상기 컨베이어부(122)는,상기 예취부(124)가 전단 측에서 지면과 인접한 부위에 구비되고, 상기 예취부(124)로부터 후방을 향해 상향 경사로 형성되는 경사컨베이어(122a) 및 상기 경사컨베이어(122a)의 후단으로부터 후방을 향해 수평방향으로 연장 형성되고 상기 트러스프레임(150)에 결합되는 수평컨베이어(122b)로 구분되고,상기 경사컨베이어(122a) 및 상기 수평컨베이어(122b)는 단일의 컨베이어벨트로 형성되며, 상기 단일의 컨베이어벨트는 상기 구동모듈(114)과 연결된 롤러모듈의 회전에 의해 동작되며,상기 베이스프레임(110)의 전방 측은,상기 경사컨베이어(122a)의 경사에 대응되는 경사부(110a)가 형성되며, 상기 경사부(110a)의 상부에는 상기 경사컨베이어(122a)가 위치되되, 상기 경사부(110a)의 전단부 및 상기 경사컨베이어(122a)의 전단부 사이에는 완충장치가 결합된 유압실린더 구조로 형성되고 상기 유압펌프(114b)에 연결되어 동력을 전달받는 리프팅부(116)가 구비되어 지면으로부터 상기 예취부(124)의 높이를 조절하는,자동 수확장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1093/1150 Row 1093: application_number: 1020200158820, combined_string: invention_title: 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치 abstract: 실시예들은 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치에 관련된 것이다. 구체적으로 이 장치는, 작물의 하부에 위치하여 작물을 지지하며, 상부에서 하부로 갈수록 내측 단면적이 증가하는 형태의 지지체를 포함하고, 상기 지지체는 적어도 부분적으로 투명 재질로 구성된다. 본 장치에 의하면 작물의 뿌리 전체에 대한 이미지 데이터를 효과적으로 획득하여 최적의 생장환경을 위한 인공지능 학습 데이터로 활용할 수 있는 이점이 있다. claims: 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치로서,상기 장치는,작물의 하부에 위치하여 작물을 지지하며, 상부에서 하부로 갈수록 내측 단면적이 증가하는 형태의 지지체를 포함하고,상기 지지체는 적어도 부분적으로 투명 재질로 구성되고,상기 지지체 위에 위치하며, 상기 작물의 줄기를 고정시키는 줄기 고정부; 및상기 지지체 아래에 위치하며, 상기 지지체의 내측면을 향해 촬영함으로써 작물의 줄기에 대한 영상을 획득하는 센싱부를 포함하고,상기 지지체는,상단 지지체;상기 상단 지지체 아래에 배치되는 하단 지지체; 및상기 상단 지지체와 상기 하단 지지체사이에 양액이 통과할 수 있는 양액 급수 공간을 포함하고,상기 상단 지지체와 하단 지지체를 연결하고, 상기 양액 급수 공간에 양액을 공급하는 연결부재를 더 포함하되,상기 연결부재는, 상기 상단 지지체에 체결되는 제1 연결부;상기 하단 지지체에 체결되는 제2 연결부; 및상기 제1 연결부와 제2 연결부 사이에 형성되며, 제1 연결부 또는 제2 연결부의 내측에 형성된 급수관을 통해 유입된 양액을 상기 양액 급수 공간으로 가이드하는 가이드부를 포함하는 것을 특징으로 하는 뿌리 촬영용 빗면을 갖는 구조물을 포함하는 수경재배 장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1094/1150 Row 1094: application_number: 1020200106506, combined_string: invention_title: 고구마 재배 방법 abstract: 본 발명은 비닐하우스에서 키운 길이가 25 cm보다 크거나 같고 45 cm보다 작거나 같은 고구마 종묘를 뿌리로부터 첫 번째 마디를 45 도의 각도로 잘라낸 고구마 종묘를 준비하는 고구마 종묘 준비 단계; 상기 고구마 종묘의 줄기 부분을 21 ℃ 온도에서 36 시간 동안 물에 침지시키는 침지 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 고구마 종묘를 심기 전 10일에서 12일 전에 제초제를 살포하여 제초하는 제 1 제초 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 1 ha당 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료 250 ~ 350 kg을 공급하는 복합비료 공급 단계; 상기 물에 침지시킨 고구마 종묘를 심을 토양에 두둑폭 50 ~ 70 ㎝, 두둑높이 50 ~ 60 ㎝ 의 두둑을 형성하는 두둑 형성 단계; 상기 두둑의 상부에 물 또는 영양제를 공급할 수 있는 점적 테이프를 설치하고 상기 두둑 중 인접한 두 개의 두둑과 가운데 고랑을 비닐로 멀칭하고 상기 멀칭된 비닐에 고구마 종묘를 심기 위한 구멍을 뚫는 멀칭 단계; 상기 구멍에 물에 침지시킨 고구마 종묘의 줄기 세 번째 마디에서 다섯 번째 마디까지 삽입하여 고구마 종묘를 심는 정식 단계; 상기 고구마 종묘를 심은 후 제초제를 살포하는 제 2 제초 단계; 및 상기 고구마 종묘를 심은 토양에 1 ha당 150 ~ 250 kg 의 질산암모늄과 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료를 70 ~ 150 kg을 혼합한 혼합비료를 생육기간 중 3회 내지 6회 공급하는 혼합 비료 공급 단계;를 포함하는 사질 토양에서 고구마 재배 방법에 관한 것이다. claims: 비닐하우스에서 키운 길이가 25 cm보다 크거나 같고 45 cm보다 작거나 같은 고구마 종묘를 뿌리로부터 첫 번째 마디를 45 도의 각도로 잘라낸 고구마 종묘를 준비하는 고구마 종묘 준비 단계;상기 고구마 종묘의 줄기 부분을 21 ℃ 온도에서 36 시간 동안 물에 침지시키는 침지 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 고구마 종묘를 심기 전 10일에서 12일 전에 제초제를 살포하여 제초하는 제 1 제초 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 1 ha당 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료 250 ~ 350 kg을 공급하는 복합비료 공급 단계;상기 물에 침지시킨 고구마 종묘를 심을 토양에 두둑폭 50 ~ 70 ㎝, 두둑높이 50 ~ 60 ㎝ 의 두둑을 형성하는 두둑 형성 단계;상기 두둑의 상부에 물 또는 영양제를 공급할 수 있는 점적 테이프를 매립하여 설치하고 상기 두둑 중 인접한 두 개의 두둑과 가운데 고랑을 비닐로 멀칭하고 상기 멀칭된 비닐에 고구마 종묘를 심기 위한 구멍을 뚫는 멀칭 단계;상기 구멍에 물에 침지시킨 고구마 종묘의 줄기 세 번째 마디에서 다섯 번째 마디까지 삽입하여 고구마 종묘를 심는 정식 단계;상기 고구마 종묘를 심은 후 제초제를 살포하는 제 2 제초 단계; 및상기 고구마 종묘를 심은 토양에 1 ha당 150 ~ 250 kg 의 질산암모늄과 질소 : 인 : 칼륨의 중량비가 150 : 80 : 80 인 복합비료를 70 ~ 150 kg을 혼합한 혼합비료를 생육기간 중 3회 내지 6회 공급하는 혼합 비료 공급 단계;를 포함하되, 상기 멀칭 단계에서 멀칭하는 방법은 상기 두둑의 상부를 투명한 폴리에틸렌 재질의 비닐로 멀칭하고, 상기 두둑의 양옆면은 불투명한 폴리에틸렌 재질의 비닐로 멀칭하는 것을 특징으로 하고,상기 정식 단계의 고구마 종묘 1 ha당 40,000 ~ 50,000 개로 심는 것을 특징으로 하며, 상기 고구마 종묘의 종류는 호박고구마 또는 밤고구마인 것을 특징으로 하는,사질 토양에서 고구마 재배 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1095/1150 Row 1095: application_number: 1020200074550, combined_string: invention_title: 식물재배시스템의 차폐지지장치 abstract: 본 발명은 실내에서 식물재배에 필요한 공간의 제약을 해결하고 아울러, 미적감각을 고조하기 위하여, 식물을 천장에 매달아 아래를 향해 자라도록 하는 방법으로 재배 공간을 확보하는 식물재배시스템과 관련한다. 더욱 구체적으로, 식물재배시스템의 쳄버는 식물의 몸체가 수직방향으로 배치될 수 있도록 수직으로 형성된 개구부를 갖고, 상기 개구부에는 식물 줄기가 통과하여 안착될 차폐지지부가 부착되고, 상기 차폐지지부는 차폐지지몸체 및 차폐지지슬롯을 포함하고, 상기 차폐지지부에의 차폐지지몸체에는 조임수단이 구비된다. claims: 식물재배시스템에 구비되는 것으로서, 상기 식물재배시스템은 식물 뿌리를 가두는 쳄버를 포함하고, 상기 쳄버의 개구부에는 식물 줄기가 통과하여 안착될 차폐지지부가 서로 대응하는 형태를 취해서 마주보게 복수 배치되며,상기 차폐지지부는 차폐지지몸체 및 차폐지지슬롯을 포함하되,상기 차폐지지부의 차폐지지몸체에는 조임수단이 구비되고,상기 조임수단은 조임용 돌기 및 조임용 밴드를 포함하고,상기 상기 조임용 돌기는 상기 차폐지지몸체 위에 수직으로 돌출되어 제공되고,상기 조임용 밴드는 탄성력을 갖는 고리 형태로 제공되어서,상기 조임용 돌기에 상기 조임용 밴드가 걸림이 되어 탄성력으로 조일 수 있도록 설치되는 것을 특징으로 하는 식물재배시스템의 차폐지지장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1096/1150 Row 1096: application_number: 1020200019765, combined_string: invention_title: 뿌리 식물 재배 장치 abstract: 본 발명에 따른 뿌리 식물 재배 장치는, 내부에 배양토가 채워지고, 바닥에 배수공이 형성된 바닥 있는 통모양의 육묘 용기; 및 상하 양단부가 개방되어, 상단부는 육묘 용기에 채워진 배양토 위로 노출되고, 하단부는 배양토에 소정 깊이로 박혀서, 상단부로부터 공급되는 물 또는 양액이 하단부로부터 소정 깊이의 배양토 안으로 공급되도록 구성된 급수 파이프를 구비하는 육묘 재배기를 포함한다. 본 발명에 따르면 뿌리 식물의 상품성(뿌리의 직근성과 굵기)을 현저하게 향상시키고, 재배 기간을 획기적으로 단축시킬 수 있다. claims: 내부에 배양토가 채워지고, 바닥에 배수공이 형성된 바닥 있는 통모양의 육묘 용기; 및상하 양단부가 개방되어, 상단부는 상기 육묘 용기에 채워진 상기 배양토 위로 노출되고, 하단부는 상기 배양토에 소정 깊이로 박혀서, 상기 상단부로부터 공급되는 물 또는 양액이 상기 하단부로부터 상기 소정 깊이의 배양토 안으로 공급되도록 구성된 급수 파이프를 구비하는 육묘 재배기를 포함하는 뿌리 식물 재배 장치.내부에 양액이 채워지고, 바닥 있는 통모양의 수경 용기; 및 상기 수경 용기의 상부에 배치되고, 뿌리 식물의 뿌리가 아래로 늘어뜨려져 상기 뿌리의 하단부가 상기 수경 용기에 채워지는 양액에 잠기도록 상기 뿌리의 상단부를 고정하여 지지하는 지지부를 구비하는 수경 재배기를 포함하는 뿌리 식물 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1097/1150 Row 1097: application_number: 1020200019766, combined_string: invention_title: 뿌리 식물 재배 방법 abstract: 본 발명에 따른 뿌리 식물 재배 방법은, 소정 길이의 뿌리를 가지는 뿌리 식물을 재배하는 방법으로서, 뿌리 식물의 뿌리가 아래로 늘어뜨려져 뿌리 식물의 뿌리의 하단부가 수경 용기에 채워지는 양액에 잠기도록 뿌리 식물의 뿌리 상단부를 고정하여 지지한 상태에서, 수경 용기에 양액을 공급함으로써 뿌리 식물의 뿌리를 굵기 성장시키는 수경 재배 단계를 포함한다. 본 발명에 따르면 뿌리 식물의 상품성(뿌리의 굵기)을 현저하게 향상시키고, 재배 기간을 획기적으로 단축시킬 수 있다. claims: 소정 길이의 뿌리를 가지는 뿌리 식물을 재배하는 방법으로서,상기 뿌리 식물의 뿌리가 아래로 늘어뜨려져 상기 뿌리의 하단부가 수경 용기에 채워지는 양액에 잠기도록 상기 뿌리의 상단부를 고정하여 지지한 상태에서, 상기 수경 용기에 양액을 공급함으로써 상기 뿌리를 굵기 성장시키는 수경 재배 단계를 포함하는 뿌리 식물 재배 방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1098/1150 Row 1098: application_number: 1020200018010, combined_string: invention_title: 커피콩 수확용 드럼형 수레 abstract: 본 발명은 내부에 제1수용공간(110)이 형성된 제1드럼바퀴(100); 일면이 상기 제1드럼바퀴(100)의 일면과 마주보도록 이격 배치되되, 내부에 제2수용공간(210)이 형성된 제2드럼바퀴(200); 상기 제1드럼바퀴(100) 및 제2드럼바퀴(200) 사이를 연결하는 연결부(300); 및 상기 연결부(300) 상에 고정되되, 커피콩이 투입되도록 투입구(420)가 형성된 가이드부(400);를 포함하며, 제1드럼바퀴(100) 및 제2드럼바퀴(200)는 상기 연결부(300) 상에서 회전 가능하게 결합되되, 상기 연결부(300)는, 상기 가이드부(400)의 투입구(420)로 투입된 커피콩이 상기 제1드럼바퀴(100)의 제1수용공간(110) 또는 제2드럼바퀴(200)의 제2수용공간(120)으로 이송되도록 분배구(330)가 형성되어, 전체 부피가 줄어 좁은 공간에서도 사용가능하고, 커피콩을 보다 용이하게 보관할 수 있으면서, 많은 양의 커피콩을 수용하는 커피콩 수확용 드럼형 수레(1000)에 관한 것이다. claims: 내부에 제1수용공간(110)이 형성된 제1드럼바퀴(100);일면이 상기 제1드럼바퀴(100)의 일면과 마주보도록 이격 배치되되, 내부에 제2수용공간(120)이 형성된 제2드럼바퀴(200);상기 제1드럼바퀴(100) 및 제2드럼바퀴(200) 사이를 연결하는 연결부(300); 및상기 연결부(300) 상에 고정되되, 커피콩이 투입되도록 투입구(420)가 형성된 가이드부(400);를 포함하며,제1드럼바퀴(100) 및 제2드럼바퀴(200)는 상기 연결부(300) 상에서 회전 가능하게 결합되되,상기 연결부(300)는,상기 가이드부(400)의 투입구(420)로 투입된 커피콩이 상기 제1드럼바퀴(100)의 제1수용공간(110) 또는 제2드럼바퀴(200)의 제2수용공간(210)으로 이송되도록 분배구(330)가 형성되는 커피콩 수확용 드럼형 수레(1000)., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1099/1150 Row 1099: application_number: 1020200005340, combined_string: invention_title: 콩 콤바인의 수확물 이송장치 abstract: 본 발명은 예취장치의 수거포켓에 구비되는 오거드럼의 회전을 통해 유입되는 수확물을 탈곡공간으로 이송시 과도한 수확물의 유입에 따른 이송작업의 중단시에도 상기 과도하게 유입된 작물을 상기 수거포켓의 수거공간으로 역배출하여 이송공간에서 작물의 과도한 수용상태를 해제하도록 함에 따라 안정적으로 수확물의 이송작업을 수행할 수 있도록 함은 물론 수확 과정에서 안전사고의 위험성이 낮아지도록 한 것이다,이를 위해 본 발명은, 콤바인 본체 내부에 시설되는 예취장치의 수거공간과 탈곡장치의 탈곡공간을 공간적으로 연결하는 이송공간이 구비된 이송몸체와; 상기 이송몸체의 이송공간에서 상기 수거공간과 상기 탈곡공간을 경유하는 순환경로를 형성하도록 된 순환수단과; 상기 순환수단을 통해 상기 순환경로를 순환하면서 상기 수거공간에서 투입되는 수확물을 포집하여 상기 탈곡공간으로 가압하면서 이송시키도록 된 이송체들과; 상기 순환수단으로 회전력을 전달하도록 된 주회전축을 선택적으로 역회전시키도록 된 역회전수단;을 포함하여 이루어지는 것을 특징으로 하는 콩 콤바인의 수확물 이송장치를 제공한다. claims: 콤바인 본체 내부에 시설되는 예취장치의 수거공간과 탈곡장치의 탈곡공간을 공간적으로 연결하는 이송공간이 구비된 이송몸체와;상기 이송몸체의 이송공간에서 상기 수거공간과 상기 탈곡공간을 경유하는 순환경로를 형성하도록 된 순환수단과;상기 순환수단을 통해 상기 순환경로를 순환하면서 상기 수거공간에서 투입되는 수확물을 포집하여 상기 탈곡공간으로 가압하면서 이송시키도록 된 이송체들과;상기 순환수단으로 회전력을 전달하도록 된 주회전축을 선택적으로 역회전시키도록 된 역회전수단;을 포함하여 이루어지는 것을 특징으로 하는 콩 콤바인의 수확물 이송장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1100/1150 Row 1100: application_number: 1020200005354, combined_string: invention_title: 새싹보리 재배방법 및 그에 의해 재배된 새싹보리 abstract: 본 발명은 새싹 보리 재배방법에 관한 것으로서, 발아에 적합한 보리를 선별하고 세척하는 선별 및 세척단계와, 상기 선별 및 세척된 보리를 기능성 수용액에 침지시킨 후 불리는 불림단계와, 상기 불린 보리를 발아시키는 발아단계와, 상기 발아된 보리를 식재하여 생육하는 생육단계와, 상기 생육된 새싹 보리를 채취하고 포장하는 채취 및 포장단계를 포함하여 이루어지는 것을 특징으로 한다. 상기의 방법으로 재배된 새싹보리는 한약재, 법제 유황, 천연 항균제가 포함된 기능성 수용액, 기능성 상토를 보리의 발아 및 생육과정에서 사용함에 따라 한약재, 법제 유황 및 천연 항균제의 유효한 성분이 자연스럽게 흡수되어, 새싹 보리를 섭취하는 것만으로도 새싹보리의 유효한 성분과 더불어 한약재, 법제 유황 및 천연 항균제의 유효한 성분을 함께 섭취할 수 있는 장점이 있다. claims: 발아에 적합한 보리를 선별하고 세척하는 선별 및 세척단계(S10); 상기 선별 및 세척된 보리를 기능성 수용액에 침지시킨 후, 15~22℃의 온도에서 60~72시간 동안 불리는 불림단계(S20);상기 불린 보리를 온도 28~30℃, 습도 75~80%의 범위를 유지시키면서, 20~30시간 동안 발아시키는 발아단계(S30);상기 발아된 보리를 식재하여 생육하는 생육단계(S40); 상기 생육된 새싹 보리를 채취하고 포장하는 채취 및 포장단계(S50);를 포함하여 이루어지되, 상기 불림단계(S20)의 기능성 수용액은, 물 100중량부에, 한약재 추출물 20~30중량부, 법제 유황분말 2~3중량부, 천연 항균제 5~7중량부를 혼합하여 제조하되,상기 한약재 추출물은, 가시오가피, 두충, 천궁, 황기, 황궁, 당귀, 작약, 감초, 계피, 갈근, 숙지황, 복령, 백출, 칡, 더덕, 인삼, 홍삼 중에서 선택된 하나 이상을 70~80℃의 온도에서 48~72시간 동안 건조하여 150~200mesh의 크기로 분쇄한 후, 상기 건조 및 분쇄된 혼합물 100중량부에 물 800~1,000중량부를 혼합하고 80~100℃의 온도에서 2~4시간 가열하여 여과한 것이고,상기 법제 유황분말은,(i) 유황을 120~160℃의 온도에서 30~50분 동안 가열하여 용융시키는 용융단계;(ii) 상기 용융된 유황 100중량부에 지장수 300~700중량부, 무즙 10~20중량부, 엄나무 추출물 3~5중량부, 제올라이트 분말 30~50중량부를 혼합하고 100~120℃의 온도에서 1~2시간 동안 가열한 후, 냉각시켜 제독하는 제독단계;(iii) 상기 제독된 유황을 분리하여 건조기에 넣고 함수율이 5% 이하가 되도록 건조하는 분리 및 건조단계;(iv) 상기 i) 용융단계, (ii) 제독단계, (iii) 분리 및 건조단계를 5~10회 반복하는 반복단계;(v) 상기 반복단계를 거쳐 분리 및 건조된 유황을 250~300mesh의 크기로 분쇄하는 분쇄단계;를 포함하여 제조되며,상기 천연 항균제는,백리향 추출물 100중량부, 비자나무 오일추출물 30~50중량부를 혼합한 것이고,상기 생육단계(S40)는, 상기 발아된 보리를 기능성 상토가 수용된 모종판에 식재하여 7~10일 동안 생육하되, 상기 기능성 상토는, 원예용 상토 100중량부에, 상기 불림단계(S20)에서 한약재 추출물 제조시 여과후 남은 한약재 찌꺼기 7~10중량부, 상기 불림단계(S20)에서 제조된 법제 유황분말 2~3중량부, 상기 불림단계(S20)에서 제조된 천연항균제 3~5중량부를 혼합하여 제조되는 것을 특징으로 하는 새싹보리 재배방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1101/1150 Row 1101: application_number: 1020190178145, combined_string: invention_title: 격리부재가 구비된 식물 재배장치 abstract: 본 발명은 식물을 재배하는 재배판이 구비된 장치에 관한 것으로 옆으로 퍼지는 성격의 식물을 재배판에서 키우는 경우에 식물의 줄기가 엉키는 문제를시켜주어 작물의 상품성 저하를 방지할 수 있는 효과를 달성할 수 있다. claims: 복수개의 재배홀을 가지는 재배플레이트와 상기 재배홀에 삽입되어 고정되는 복수의 화분을 포함하는 식물 재배 장치에 있어서,상기 화분은,재배 식물의 뿌리와 상기 뿌리를 고정하는 흙이 위치하여 생장하도록 공간을 제공하는 본체부; 및상기 본체부로부터 하방으로 연장 형성되고 측벽과 바닥면에는 상기 식물의 뿌리가 관통할 수 있는 복수의 관통홀이 형성되며 외벽면의 적어도 일부가 상기 재배홀의 내벽면의 적어도 일부와 이격되며 상기 재배홀로 삽입되어 위치되는 삽입부를 포함하고,상기 식물 재배 장치는, 상기 화분들의 상부 공간을 각 화분마다 구분하여 서로 격리시키는 격리부재를추가로 더 포함하는 것을 특징으로 하는 식물 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1102/1150 Row 1102: application_number: 1020190166976, combined_string: invention_title: 뿌리작물 재배기 abstract: 본 발명은 뿌리작물 재배기에 관한 것으로, 본 발명에 따르면, 물을 배수시킬 수 있도록 배수홀을 포함하는 하판 및 상기 하판에 결합되되, 하나 이상이 적층될 수 있는 재배통을 포함하되, 상기 재배통은 내부가 관통된 통 형상으로 형성된 몸체; 상기 몸체 상부에 형성된 상부 결합부 및 상기 몸체 하부에 형성되어, 다른 재배통의 상부 결합부 또는 상기 하판과 결합되는 하부 결합부를 포함하는 뿌리작물 재배기를 제공할 수 있다. claims: 물을 배수시킬 수 있도록 배수홀을 포함하는 하판 및상기 하판에 결합되되, 하나 이상이 적층될 수 있는 재배통을 포함하되,상기 재배통은,내부가 관통된 통 형상으로 형성된 몸체;상기 몸체 상부에 형성된 상부 결합부 및상기 몸체 하부에 형성되어, 다른 재배통의 상부 결합부 또는 상기 하판과 결합되는 하부 결합부를 포함하고,상기 재배통에 설치되어 토양에서 공간을 확보하고, 뿌리가 성장함에 따라 토압을 조절할 수 있도록 하는 토압 조절부를 포함하며,상기 토압 조절부는,상기 재배통 상측에 설치되는 관거치부 및상기 관거치부에 거치되어 상기 재배통 내부로 설치되는 토압 조절관을 포함하는 뿌리작물 재배기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1103/1150 Row 1103: application_number: 1020190151156, combined_string: invention_title: 뿌리 식물의 다수확 재배용 케이스 및 이를 이용한 뿌리 식물의 다수확 재배방법 abstract: 본 발명은 뿌리 식물의 다수확 재배용 케이스 및 이를 이용한 뿌리 식물의 다수확 재배방법에 관한 것으로, 본 발명은 경사진 경작지에 평행하도록 기울어져 경작지에 매설되고, 뿌리 식물이 길게 성장할 수 있도록 길게 형성되어 뿌리식물의 길이 방향 성장을 가이드하는 저면 플레이트부; 저면 플레이트부의 양 측면에 형성되어 뿌리 식물의 측면 방향 성장을 가이드하는 측면 플레이트부; 경작지의 지면을 향하도록 저면 플레이트부의 일단에서 일정각도만큼 기울어져 형성되어 경작지의 상부에 배치되고, 뿌리 식물의 뿌리가 저면 플레이트부에 닿도록 저면 플레이트부의 길이방향을 따라 뿌리 식물이 배치되어 성장을 시작하는 슬라이드부; 및 저면 플레이트부의 타단에 형성되어 경작지의 하부에 배치되고, 뿌리 식물의 길이 방향 성장을 제한하는 종결부를 포함할 수 있다. claims: 경사진 경작지에 평행하도록 기울어져 상기 경작지에 매설되고, 마, 인삼, 더덕, 칡, 도라지 또는 무인 뿌리 식물이 길게 성장할 수 있도록 길게 형성되어 상기 뿌리 식물의 길이 방향 성장을 가이드하는 저면 플레이트부;상기 저면 플레이트부의 일측면에 형성되는 제1측면 플레이트부와, 상기 저면 플레이트부의 타측면에 형성되는 제2측면 플레이트부로 이루어져 상기 뿌리 식물의 측면 방향 성장을 가이드하는 측면 플레이트부;상기 경작지의 지면을 향하도록 상기 저면 플레이트부의 일단에서 일정각도만큼 기울어져 형성되어 상기 경작지의 상부에 배치되고, 상기 뿌리 식물의 뿌리가 상기 저면 플레이트부에 닿도록 상기 저면 플레이트부의 길이방향을 따라 상기 뿌리 식물이 배치되어 성장을 시작하는 슬라이드부; 및상기 저면 플레이트부의 타단에 형성되어 상기 경작지의 하부에 배치되고, 상기 뿌리 식물의 길이 방향 성장을 제한하는 종결부;를 포함하고,상기 저면 플레이트부, 측면 플레이트부, 슬라이드부 및 종결부는 합성수지로 형성되고,복수 개의 제1엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 저면 플레이트부와 슬라이드부의 일측에 상호 일정간격 이격되어 형성되고,복수 개의 제2엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 저면 플레이트부와 슬라이드부의 타측에 상호 일정간격 이격되어 상기 제1엠보싱에 평행하게 형성되고,복수 개의 제3엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 측면 플레이트부와 저면 플레이트부에 상호 일정간격 이격되어 상기 저면 플레이트부의 길이방향에 수직으로 형성되되, 각각의 상기 제3엠보싱은 상기 제1측면 플레이트부의 단부로부터 한 쌍의 상기 제1엠보싱 사이를 통과하여 상기 제2엠보싱 인근까지 연장되고,복수 개의 제4엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 측면 플레이트부와 저면 플레이트부에 상호 일정간격 이격되어 상기 저면 플레이트부의 길이방향에 수직으로 형성되되, 각각의 상기 제4엠보싱은 상기 제2측면 플레이트부의 단부로부터 한 쌍의 상기 제2엠보싱 사이를 통과하여 상기 제1엠보싱 인근까지 연장되고,복수 개의 제5엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 제1측면 플레이트부에 상호 일정간격 이격되어 상기 제3엠보싱에 평행하게 형성되고,복수 개의 제6엠보싱이 상기 저면 플레이트부의 길이방향을 따라 상기 제2측면 플레이트부에 상호 일정간격 이격되어 상기 제4엠보싱에 평행하게 형성되고,상기 제1엠보싱, 제2엠보싱, 제3엠보싱 및 제4엠보싱에 둘러싸여 사각형태로 구획되는 복수 개의 분할면이 상기 저면 플레이트부의 길이방향을 따라 순차적으로 상기 저면 플레이트부에 형성되고,상기 뿌리 식물의 잔뿌리가 관통할 수 있는 복수 개의 홀이 상기 저면 플레이트부의 길이방향을 따라 상호 일정간격 이격되어 상기 분할면에 형성되는 뿌리 식물의 다수확 재배용 케이스., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1104/1150 Row 1104: application_number: 1020190136074, combined_string: invention_title: 플라보노이드를 함유하는 기능성 콩의 재배방법 abstract: 항바이러스 작용 등을 하는 플라보노이드 성분이 함유된 기능성 콩 및 그 재배방법을 개시한다. 본 발명은 기능성 콩의 재배방법으로서 15~20v%의 혼합농축액, 20~35v%의 양파농축액, 그리고 나머지 콩두유를 혼합한 혼합농축액과 물을 부피비로 1:1로 희석한 희석농축액에 콩을 침장한 후, 침장된 콩을 정식한 다음 상기 희석농축액과 물을 혼합한 관주액으로 관주하여 재배한, 플라보노이드 성분을 160mg/kg 함유하는 것을 특징으로 하는 기능성 콩에 대한 것이다. claims: 기능성 콩의 재배방법으로서,15~20v%의 홍삼농축액, 20~35v%의 양파농축액, 그리고 나머지 콩두유를 혼합한 혼합농축액과 물을 부피비로 1:1로 희석한 희석농축액에 콩을 침장한 후, 침장된 콩을 정식한 다음 상기 희석농축액과 물을 혼합한 관주액으로 관주하여 재배하는 것을 특징으로 하는, 기능성 콩의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1105/1150 Row 1105: application_number: 1020190127935, combined_string: invention_title: 비닐 천공과 파종작업을 동시에 수행할 수 있는 점파식 파종기 abstract: 본 발명은 점파식 파종기에 관한 것으로, 특히 종자공급통(11)의 공급관(12)을 통하여 공급되는 종자를 내부 공간(22)에 수용하고, 지면위를 구름이동하도록 공급관(12)의 선단에 회전가능하게 연결되어 종자 일정량 만큼씩 외부로 배출하는 종자통(20)과, 상기 종자통(20)의 원통형 몸체(21)의 외측벽을 따라 일정한 간격으로 복수개가 구비되고 종자통(20)이 비닐(3)로 멀칭된 두둑(1)을 구름이동할 때, 외측면에 구비된 커터로써 멀칭 비닐(3)을 절개하는 동시에 두둑(1)에 파종홈(1a)을 형성하는 파종구(30)를 구비한 상기 파종구(30)는 파종통(20)의 원통형 몸체(21)에 탈착가능하게 결합되어 고정된 파종구 몸체(31)와, 상기 파종구 몸체(31)의 상측 선단에 힌지핀(38)을 중심으로 회동가능하게 결합되고, 파종통(20) 내부에 구비된 개폐작동기구에 의해 힌지핀(38)을 중심으로 회동하여 파종구 몸체(31)의 종자 수용홈을 개폐하는 파종구 덮개(32)를 포함하고, 상기 커터는, 상기 파종구 몸체(31)에 구비된 전방 커터(34)와, 후방 커터(35)와, 상기 파종구 덮개(32)의 좌측 커터(36)와, 상기 파종구 몸체(31)에 구비된 우측 커터(37)로 이루어져, 파종통(20)이 비닐(3)로 멀칭된 두둑(1)위를 구름이동할 때, 파종구(30)와 파종구(30)에 구비된 4개의 커터(34-37)들이 멀칭 비닐(3)을 '십자형'으로 절개하고 확개하여, 파종된 종자에서 싹이 원활하게 자라날 수 있게 된다. claims: 비닐 천공과 파종작업을 동시에 수행할 수 있는 점파식 파종기로서, 종자공급통(11)의 공급관(12)을 통하여 공급되는 종자를 내부 공간(22)에 수용하고, 지면위를 구름이동하도록 공급관(12)의 선단에 회전가능하게 연결되어 종자 일정량 만큼씩 외부로 배출하는 종자통(20)과, 상기 종자통(20)의 원통형 몸체(21)의 외측벽을 따라 일정한 간격으로 복수개가 구비되고 종자통(20)이 비닐(3)로 멀칭된 두둑(1)을 구름이동할 때, 외측면에 구비된 커터로써 멀칭 비닐(3)을 절개하는 동시에 두둑(1)에 파종홈(1a)을 형성하는 파종구(30)를 구비하고, 상기 파종구(30)는 파종통(20)의 원통형 몸체(21)에 탈착가능하게 결합되어 고정된 파종구 몸체(31)와, 상기 파종구 몸체(31)의 상측 선단에 힌지핀(38)을 중심으로 회동가능하게 결합되고, 파종통(20) 내부에 구비된 개폐작동기구에 의해 힌지핀(38)을 중심으로 회동하여 파종구 몸체(31)의 종자 수용홈을 개폐하는 파종구 덮개(32)를 포함하고, 상기 커터는, 상기 파종구 몸체(31)에 파종방향에 대하여 전방으로 돌출되게 구비되고, 톱니형 날(34a)을 가진 전방 커터(34)와, 상기 파종구 몸체(31)에 파종방향에 대하여 후방으로 돌출되게 구비되고, 톱니형 날(35a)을 가진 후방 커터(35)와, 상기 파종구 덮개(32)에 파종방향에 대하여 좌측으로 돌출되게 구비되고, 톱니형 날(36a)을 가진 좌측 커터(36)와, 상기 파종구 몸체(31)에 파종방향에 대하여 우측으로 돌출되게 구비되고, 톱니형 날(37a)을 가진 우측 커터(37)를 포함하고, 상기 커터(34-37)는 전체적으로 상단에서 하단으로 갈수록 하향 경사지게 형성되며, 상기 커터(34-37)의 날(34a-37a)은 하향 경사진 날부와 상향 경사진 날부가 교대로 형성된 톱니형 날로 구성되며, 상기 파종구(30)의 파종구 덮개(32)는, 파종구(30)가 두둑(1)위의 멀칭 비닐(3)과 접촉하기 시작하는 위치(P1)에서 두둑(1)의 멀칭 비닐(3)을 통과하여 두둑(1)안으로 침입할 때, 상기 커터(34-37)의 날(34a-37a)로써 멀칭 비닐(3)을 '십자(+)형'으로 절개하고, 두둑(1) 안 최대 깊이로 침입한 위치(P2)에서 최대로 개방되어 파종하고, 파종구(30)가 두둑(1)아래에서 외부로 빠져나올 때, 상기 커터(34-37)의 날(34a-37a)로써 '십자(+)형'으로 절개된 멀칭 비닐의 절개부(4)를 외측으로 확개하고, 멀칭 비닐(3)에서 빠져 나온 위치(P3)에서 파종구 덮개(32)가 파종구 몸체(31)의 수용홈을 폐쇄하도록 된 것을 특징으로 하는 비닐 천공과 파종작업을 동시에 수행할 수 있는 점파식 파종기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1106/1150 Row 1106: application_number: 1020190125748, combined_string: invention_title: 커넥터블 연무 재배장치 abstract: 본 발명은 연무를 이용하여 식물을 재배할 수 있도록 하는 커넥터블 연무 재배장치에 관한 것으로, 내부에 마련된 식물이 성장하도록 연무를 발생시켜 공급하는 연무재배기; 및 외부로부터 가해지는 물리적인 힘 또는 식물재배 프로그램에 따라 상기 연무재배기가 연무를 발생시키도록 제어하는 콘트롤장치를 포함한다. 이에, 재배장치를 통해 재배되는 식물의 뿌리에 골고루 수분을 공급하여 재배장치 내의 식물들의 성장이 균일하게 이루어지도록 하는 효과가 있다. claims: 내부에 마련된 식물이 성장하도록 연무를 발생시켜 공급하는 연무재배기; 및외부로부터 가해지는 물리적인 힘 또는 식물재배 프로그램에 따라 상기 연무재배기가 연무를 발생시키도록 제어하는 콘트롤러;를 포함하는 커넥터블 연무 재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1107/1150 Row 1107: application_number: 1020190125613, combined_string: invention_title: 작물 재배용 양액 공급장치 abstract: 본 발명의 일 실시예에 따른 작물 재배용 양액 공급장치는, 복수의 작물이 배치될 수 있도록, 종 방향 및 횡 방향으로 복수의 셀(cell)로 구획된 프레임과 복수의 작물뿌리가 노출된 상기 프레임 하부를 감싸 설치된 하우징으로 이루어진 분무경 양액재배 시스템에 있어서, 배양액을 분사하는 분사부; 상기 프레임 하방으로 노출된 각각의 작물뿌리에 배양액을 공급할 수 있도록, 상기 프레임 하부에 설치되어 상기 분사부를 종 방향 또는 횡 방향으로 이동시키는 이동부; 각각의 작물에 서로 다른 배양액을 분사할 수 있도록, 서로 다른 양액을 상기 분사부에 공급하는 복수 개의 양액 공급부; 및 사전에 입력된 각각의 상기 셀에 배치된 작물정보에 따라, 상기 양액 공급부, 분사부 빛 이동부의 작동을 제어하는 제어부;를 포함한다. claims: 복수의 작물이 배치될 수 있도록, 종 방향 및 횡 방향으로 복수의 셀(cell)로 구획된 프레임과 복수의 작물뿌리가 노출된 상기 프레임 하부를 감싸 설치된 하우징으로 이루어진 분무경 양액재배 시스템에 있어서,배양액을 분사하는 분사부;상기 프레임 하방으로 노출된 각각의 작물뿌리에 배양액을 공급할 수 있도록, 상기 프레임 하부에 설치되어 상기 분사부를 종 방향 또는 횡 방향으로 이동시키는 이동부;각각의 작물에 서로 다른 배양액을 분사할 수 있도록, 서로 다른 양액을 상기 분사부에 공급하는 복수 개의 양액 공급부; 및사전에 입력된 각각의 상기 셀에 배치된 작물정보에 따라, 상기 양액 공급부, 분사부 빛 이동부의 작동을 제어하는 제어부;를 포함하며, 상기 분사부는,복수의 상기 양액 공급부로부터 양액을 공급받아, 하나 이상의 양액이 혼합된 배양액이 수용되는 내부공간이 형성된 분사바디;상기 내부공간에 수용된 배양액을 작물뿌리에 분사하도록, 상기 분사바디에 결합된 분사노즐; 및실시간으로, 현재 위치한 셀에 배치된 작물뿌리의 형상정보를 취득하여 상기 제어부로 전송하는 스캐너;를 포함하고,상기 양액 공급부는,양액 탱크;양단이 각각 상기 양액 탱크와 상기 분사바디에 연통되는 양액 공급라인; 및상기 양액 공급라인 상에 설치되어 상기 분사바디에 공급되는 양액의 량을 조절하는 양액밸브;를 포함하고,상기 제어부는 상기 작물정보에 따라 각각의 상기 양액 공급부를 개별 제어하여, 각각의 작물에 최적의 양액비에 따라 각각의 상기 양액밸브의 작동을 제어하여 배양액을 제조하며,상기 분사노즐은 각각의 작물에 따라 분사되는 배양액의 분사각 및 입도 조절이 가능한 이류체 노즐인 것을 특징으로 하며,상기 제어부는 상기 스캐너로부터 실시간으로 수신되는 작물뿌리의 형상정보에 대응하도록, 상기 분사노즐의 분사각도를 조절하여, 상기 작물뿌리의 형상정보가 폭이 좁고 길이가 길다고 판단된 경우, 상기 분사노즐을 하방으로 이동시키면서 분사각도가 좁아지도록 제어하고, 상기 작물뿌리의 형상정보가 폭이 넓고 길이가 짧다고 판단된 경우, 상기 분사노즐을 상방으로 이동시키면서 분사각도가 증가되도록 제어하는 것을 특징으로 하는, 작물 재배용 양액 공급장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1108/1150 Row 1108: application_number: 1020190122774, combined_string: invention_title: 뿌리식물 공중 재배 장치 abstract: 본 발명에 따른 뿌리식물 공중 재배 장치는 지면으로부터 일정 높이에 고정적으로 설치되는 제1 프레임, 제1 프레임과 평행하게 배치되는 제2 프레임, 제1 프레임과 제2 프레임에 의해 양 단이 지지되어 재배공간을 형성하는 받침패드부, 제2 프레임을 상/하 방향으로 이동시키는 프레임 승강부를 포함하여 이루어진다. 받침패드부는 비닐류 등 유연한 소재로 구성될 수 있으며, 제1 프레임과 제2 프레임의 사이에서 'U' 자 형태의 재배공간을 형성한다. 본 발명에 따르면, 고구마, 감자 등 일정 깊이의 흙 속에서 재배하는 각종 뿌리식물을 땅에서 이격된 공중의 공간에서 재배할 수 있고, 그 아래의 지면도 자유롭게 이용할 수 있으므로, 시설의 공간을 더욱 효율적으로 이용할 수 있다. 특히, 고구마와 감자 등 뿌리식물의 수확이 매우 쉽게 이루어질 수 있다. claims: 지면으로부터 일정 높이에 고정적으로 설치되는 제1 프레임;상기 제1 프레임과 평행하게 배치되는 제2 프레임;상기 제1 프레임과 제2 프레임에 의해 양 단이 지지되고, 뿌리식물을 재배할 재배공간을 형성하는 받침패드부; 및상기 제2 프레임을 상/하 방향으로 이동시키는 프레임 승강부를 포함하는, 뿌리식물 공중 재배 장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1109/1150 Row 1109: application_number: 1020190117867, combined_string: invention_title: 혈당강하와 치매예방 효과가 있는 가바벼의 친환경 재배방법 abstract: 본 발명은 자연순환농법과 미생물을 이용한 유기농법을 이용하여 혈당강하와 치매예방 효과가 있는 가바벼를 효율적으로 재배하기 위한 가바벼의 친환경 재배방법에 관한 것이다. 본 발명의 가바벼 재배방법은 가바벼를 수확 후 농지에 녹비작물을 파종하는 녹비작물 파종 단계와, 농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계, 가바벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계, 상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계, 토양에 모를 이앙하는 모 이앙 단계, 가바벼의 영양 생장기에 가바벼의 잎에 존재하는 미네랄 성분을 분석하는 가바벼의 엽분석 단계, 상기 가바벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및, 가바벼를 수확하는 가바벼 수확 단계를 포함하고, 상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하며, 상기 생물학적 비료는 물과, 가바벼의 볏짚, 어류, 당밀 및 미생물제를 혼합하고 발효시켜 제조하는 것을 특징으로 한다. claims: 가바벼를 친환경적으로 재배하는 방법에 있어서,가바벼를 수확 후 농지를 갈아엎고 써레질을 한 후 녹비작물을 파종하는 녹비작물 파종 단계와,농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계,가바벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계,상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계,토양에 모를 이앙하는 모 이앙 단계,가바벼의 영양 생장기에 가바벼의 잎에 존재하는 미네랄 성분을 분석하는 가바벼의 엽분석 단계,상기 가바벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및,가바벼를 수확하는 가바벼 수확 단계를 포함하고,상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하며,상기 생물학적 비료는 물과, 가바벼의 볏짚, 어류, 당밀 및 미생물제를 포함하는 혼합물을 발효시켜 제조하고,상기 미생물제는 부엽토와 찰밥 및 볏짚을 포함하는 재료를 혼합하고 발효시켜 제조하는 것을 특징으로 하는 혈당강하와 치매예방 효과가 있는 가바벼의 친환경 재배방법.가바벼를 친환경적으로 재배하는 방법에 있어서,가바벼를 수확 후 농지를 갈아엎고 써레질을 한 후 녹비작물을 파종하는 녹비작물 파종 단계와,농지의 토양에 대해 이화학적 분석을 실행하는 토양 분석 단계,상기 토양 분석 결과를 근거로 토양을 개량하는 토양 개량 단계,가바벼의 종자를 소독 및 파종하는 종자의 소독 및 파종 단계,가바벼의 영양 생장기에 가바벼의 잎에 존재하는 미네랄 성분을 분석하는 벼의 엽분석 단계,상기 가바벼의 엽분석 결과를 근거로 생물학적 비료를 엽면 시비하는 엽면 시비 단계 및,가바벼를 수확하는 벼 수확 단계를 포함하고,상기 토양 개량 단계는 상기 녹비작물을 갈아엎고 토양에 상기 생물학적 비료를 살포하며,상기 생물학적 비료는 물과, 가바벼의 볏짚, 어류, 당밀 및 미생물제를 포함하는 혼합물을 발효시켜 제조하고,상기 미생물제는 부엽토와 찰밥 및 볏짚을 포함하는 재료를 혼합하고 발효시켜 제조하는 것을 특징으로 하는 혈당강하와 치매예방 효과가 있는 가바벼의 친환경 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1110/1150 Row 1110: application_number: 1020190116152, combined_string: invention_title: 뿌리식물재배용 조립식 컨테이너 abstract: 본 발명은 뿌리식물재배용 조립식 컨테이너에 관한 것으로, 보다 상세하게는 대량의 뿌리식물을 효과적으로 재배할 수 있도록 함은 물론 뿌리식물의 재배에 필요한 물이나 약액을 효율적으로 공급하여 고품질의 뿌리식물의 재배를 이룰 수 있도록 하는 뿌리식물재배용 조립식 컨테이너에 관한 것이다. 본 발명은 상호 일정간격 이격되게 배치되되 하측단에서 상측방향으로 절개조립라인(110)이 형성된 다수개의 쇼트격판(100); 상기 다수개의 쇼트격판(100)을 가로지르도록 결합되되 상기 절개조립라인(110)에 대응되어 끼워맞춤결합되는 대응조립라인(210)이 일정간격으로 형성된 롱격판(200); 격자상으로 배치되게 조립된 상기 쇼트격판(100)과 롱격판(200)을 수용하도록 이루어지되 보관시에는 접어 보관하다가 상기 쇼트격판(100)과 롱격판(200)을 수용하는 경우에는 펼쳐 직육면체 형상을 갖도록 이루어진 수용바디부(400);를 포함하여 구성되되, 상기 쇼트격판(100)의 길이방향 양측과 상기 롱격판(200)의 길이방향 양측은 걸림안착편(300)을 매개로 상기 수용바디부(400)에 분리가능하게 걸림조립되어 격자상으로 배치된 형태가 유지될 수 있도록 이루어진 것을 특징으로 한다. claims: 상호 일정간격 이격되게 배치되되 하측단에서 상측방향으로 절개조립라인(110)이 형성된 다수개의 쇼트격판(100); 상기 다수개의 쇼트격판(100)을 가로지르도록 결합되되 상기 절개조립라인(110)에 대응되어 끼워맞춤결합되는 대응조립라인(210)이 일정간격으로 형성된 롱격판(200); 격자상으로 배치되게 조립된 상기 쇼트격판(100)과 롱격판(200)을 수용하도록 이루어지되 보관시에는 접어 보관하다가 상기 쇼트격판(100)과 롱격판(200)을 수용하는 경우에는 펼쳐 직육면체 형상을 갖도록 이루어진 수용바디부(400);를 포함하여 구성되되, 상기 쇼트격판(100)의 길이방향 양측과 상기 롱격판(200)의 길이방향 양측은 걸림안착편(300)을 매개로 상기 수용바디부(400)에 분리가능하게 걸림조립되어 격자상으로 배치된 형태가 유지될 수 있도록 이루어지고, 상기 쇼트격판(100)과 상기 수용바디부(400)의 상단에는, 물이나 약액이 유동하는 유동배관유닛(500)이 안착되어 상기 유동배관유닛(500)에서 분출된 물이나 약액이 토양이 채워진 재배공간으로 낙하될 수 있는 안착홈(130)이 형성되며, 상기 유동배관유닛(500)은, 상기 안착홈(130)에 안착된 상태로 내측에 물이나 약액이 위치하는 안착바디(520)와, 상기 안착바디(520)의 폭방향 양측으로 연장되어 상기 안착바디(520)의 길이방향을 따라 일정간격으로 형성된 상태로 상기 안착바디(520)에 위치한 물이나 약액이 유동하여 토양이 채워진 재배공간(150)으로 분출될 수 있도록 안내하는 유체가이드구(530)를 포함하여 구성되고, 상기 유체가이드구(530)에는, 물이나 약액이 상기 재배공간(150)의 상측방향으로 분출될 수 있도록 하는 상방분출공(540)과 물이나 약액이 상기 재배공간(150)의 하측방향으로 유동할 수 있도록 하는 하방분출튜브(570)가 마련된 것을 특징으로 하는 뿌리식물재배용 조립식 컨테이너., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1111/1150 Row 1111: application_number: 1020190115067, combined_string: invention_title: 수동식 파종기 abstract: 본 발명은 수동식 파종기에 관한 것이다.구성에 있어서, 파이프 형태로 된 지주관의 하부에 작동부와 파종부, 그리고 파종홈의 깊이를 조절할 수 있는 스토퍼부로 이루어진 파종홈 성형장치를 구성하여 상기 작동부의 하단 베이스를 지면에 대고 손잡이로 누르면 파종부가 하강하면서 오물어진 상태로 지면에 들어가게 되어 자연스럽게 소정깊이의 파종홈을 형성하게 되고, 파종기를 들면 작동부의 복원력에 의해 자연적으로 파종부가 개방되면서 상기 파종홈에 종자 또는 모종을 파종 또는 식재할 수 있게 한 것이다.따라서 본 발명은 종래 수동식 파종기에 비해 각종 씨앗의 파종이나 모종의 이식이 훨씬 더 편리하게 이루어짐은 물론 사용시 힘이 덜 들어 신뢰성을 극대화시킬 수 있는 등의 효과가 따른다. claims: 지주관(1)의 상단에 깔때기 형태로 된 종자 또는 모종 투입이 가능한 투입부(11)가 구비되고, 상기 투입부(11) 직하부에 손잡이(12)가 구비되며, 지주관(1) 하단에 파종부(2)와 작동부(3), 그리고 스토퍼부(4)로 이루어진 파종홈 성형장치(234)를 장착하여, 상기 작동부(3)의 하단에 구비된 베이스(31)를 지면에 대고 손잡이(12)를 잡은 상태에서 지면 쪽으로 누르기만 하면 간편하면서도 균일하게 소정 크기의 파종홈(5)이 형성되는 수동식 파종기(100)를 구성하되,상기 파종홈 성형장치(234)의 파종부(2)는 지주관(1) 하단에 장착 고정되는 고정형파종삽(21)과, 상기 고정형 파종삽(21)의 일 측 상부에 힌지 조립되는 작동삽(22)으로 구성하는데, 상기 작동삽(22)의 일측 상단에는 예각으로 된 작동간(22')이 일체로 형성되고, 상기 작동간(22') 끝이 후술하는 작동부(3)의 가이드봉(32)에 장착된 승강블록(33)에 연결 구성되어 상기 파종부(2)가 하강할 때는 작동삽(22)이 닫히고 상승할 때는 개방되게 하며,상기 파종홈 성형장치(234)의 작동부(3)는, 파종부(2) 상단에 장착 고정된 지지대(34)와 상기 지지대(34)의 양측 안내관(34')에 관통 설치되며 하단이 베이스(31) 양측에 고정 설치된 가이드봉(32), 그리고 상기 가이드봉(32) 하단에 위치하여 가이드봉(32)이 수직을 유지하도록 지지하는 베이스(31)로 구성되며, 상기 가이드봉(32) 상단은 외향 절곡된 절곡부(32')를 형성하여 상기 절곡부(32')와 지지대(34)를 인장스프링(35)으로 연결 구성하고, 양측 가이드 봉(32) 상측 소정위치에 지지대(34)의 승강거리를 제어하는 스톱돌기(32)를 형성하며, 일 측 가이드봉(32)에는 전술한 작동간(22') 끝이 연결되는 승강블록(33)을 설치하되, 상기 승강블록(33)은 가이드봉(32)에 끼워진 상태에서 상승압력 또는 하강압력을 받았을 때만 승강할 수 있도록 구성한 것이며,스토퍼부(4)는 상기 작동삽(22) 후미에 설치하되, 고정판(41)과 조절판(42)으로 형성하고, 고정판(41)의 외측면에는 짧은 육각축(43')과 나사봉(43)이 일체로 된 결합축(43)을 형성하며, 조절판(42)에는 상기 육각축(43')에 끼워지도록 육각구멍(42')을 형성함으로서 조절판(42)이 다양한 높이로 조절 설치될 수 있게 구성한 것으로, 상기 파종부(2)와 작동부(3), 그리고 스토퍼부(4)가 유기적으로 조절됨에 따라 손잡이(12)를 잡아 누르는 단순한 동작에 의해 종자 파종 및 모종이식이 가능하게 하고, 또 파종홈(5)의 깊이를 간편하게 조절할 수 있게 함을 특징으로 하는 수동식 파종기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1112/1150 Row 1112: application_number: 1020190107445, combined_string: invention_title: 무한궤도형 작물 재배 장치 abstract: 본 발명의 일 실시예에 따른 무한궤도형 작물 재배 장치는, 작물 재배 용기가 무한궤도로 이동하면서 작물이 재배되도록 하는 장치로, 상기 무한궤도를 구현하기 위한 이송궤도; 및 상기 작물 재배 용기가 연결된 채로 상기 이송궤도에 의해 제공되는 내부공간 내에 배치되어 상기 내부공간 내에서 이동되는 이동체인;을 포함하며, 상기 이송궤도는, 상기 이동체인이 높이를 유지한 채 이동하기 위한 수평궤도, 상기 이동체인이 상승하면서 이동하기 위한 상승궤도, 상기 이동체인이 하강하면서 이동하기 위한 하강궤도, 및 상기 이동체인의 이동 방향을 선회시키는 선회궤도를 구비하며, 상기 선회궤도는, 상기 내부공간 내에 배치되는 상기 이동체인의 장력이 느슨해지는 경우, 상기 이동체인의 장력을 증가시켜 상기 이동체인의 이동이 원활하게 되도록, 위치 이동이 가능한 것을 특징으로 할 수 있다. claims: 작물 재배 용기가 무한궤도로 이동하면서 작물이 재배되도록 하는 무한궤도형 작물 재배 장치에 있어서,상기 무한궤도를 구현하기 위한 이송궤도; 및상기 작물 재배 용기가 연결된 채로 상기 이송궤도에 의해 제공되는 내부공간 내에 배치되어 상기 내부공간 내에서 이동되는 이동체인;을 포함하며,상기 이송궤도는,상기 이동체인이 높이를 유지한 채 이동하기 위한 수평궤도, 상기 이동체인이 상승하면서 이동하기 위한 상승궤도, 상기 이동체인이 하강하면서 이동하기 위한 하강궤도, 및 상기 이동체인의 이동 방향을 선회시키는 선회궤도를 구비하며,상기 선회궤도는,상기 내부공간 내에 배치되는 상기 이동체인의 장력이 느슨해지는 경우, 상기 이동체인의 장력을 증가시켜 상기 이동체인의 이동이 원활하게 되도록, 위치 이동이 가능하며,상기 이송궤도는,윤활 기능을 통해 상기 이동체인의 원활한 이동을 구현하기 위한 오일이 상기 내부공간 내에서 정체되는 경우, 외부로 배출되도록 하기 위한 배출홀을 구비하며,상기 배출홀은, 상기 선회궤도와 상기 상승궤도의 경계 부분의 하측 및 상기 선회궤도와 상기 하강궤도의 경계 부분의 하측 중 적어도 하나에 형성되고,상기 배출홀은,커버에 의해 밀폐 가능한 것을 특징으로 하는 무한궤도형 작물 재배 장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1113/1150 Row 1113: application_number: 1020190098998, combined_string: invention_title: 스마트 작물 재배 관리 시스템 및 스마트 작물 재배 관리 방법 abstract: 본 발명의 일 기술적 측면에 따른 스마트 작물 재배 관리 시스템은 작물 재배용 하우스(이하, '하우스'라 칭함)에 설치되어 상기 하우스 내의 작물에 대한 관리를 제공하는 스마트 작물 재배 관리 시스템으로서, 상기 하우스의 토양 온도, 내부 온도 및 외부 온도를 감지하는 온도 센서, 상기 하우스의 내부 습도 및 외부 습도를 감지하는 습도 센서, 상기 하우스 내에 구비되고, 상기 하우스 내의 작물에 급수 또는 양액을 공급하는 급수부 및 상기 온도 센서 및 상기 습도 센서의 출력을 기초로 상기 하우스의 상태 정보를 저장하고, 상기 상태 정보를 참조하여 기 설정된 관리 시나리오에 따라 상기 급수부를 조절하는 관리 장치를 포함할 수 있다. claims: 하우스에 설치되어 상기 하우스 내의 작물에 대한 관리를 제공하는 스마트 작물 재배 관리 시스템으로서,상기 하우스의 토양 온도, 내부 온도 및 외부 온도를 감지하는 온도 센서;상기 하우스의 내부 습도 및 외부 습도를 감지하는 습도 센서;상기 하우스 내에 구비되고, 상기 하우스 내의 작물에 급수 또는 양액을 공급하는 급수부;상기 하우스에 설치되어 상기 하우스에 공기를 순환시키고, 미리 설정된 분사량, 동작 시간, 정지 시간 및 습도 조건에 따라 동작을 제어하는 적어도 하나의 환풍부;상기 하우스에 대한 화재 발생 여부를 감지하는 화재 감지 센서;상기 스마트 작물 재배 관리 시스템에 대한 정전 여부를 감지하는 정전 감지 센서;상기 하우스 외부의 풍향 및 풍속을 측정하는 풍향 센서;상기 하우스 내의 작물에 대한 영상 데이터를 취득하는 카메라부; 및상기 온도 센서 및 상기 습도 센서의 출력을 기초로 상기 하우스의 상태 정보를 저장하고, 상기 상태 정보를 참조하여 기 설정된 관리 시나리오에 따라 미리 설정된 특정 시간에 물이나 양액을 제공하도록 상기 급수부를 조절하며, 상기 화재 감지 센서에서 화재를 감지하거나 또는 상기 정전 감지 센서에서 정전을 감지할 때 이에 대한 비상 알림을 사용자에게 제공하는 관리 장치;를 포함하며,상기 관리 장치는,상기 상태 정보를 참조하여 기 설정된 관리 시나리오에 따라 미리 설정된 시간 동안 환기하도록 상기 환풍부를 조절하며,상기 풍향 센서의 측정치가 상기 하우스의 파손이 우려되는 임계치 이상일 때 비상 알림을 사용자에게 제공하며,상기 카메라부에서 취득한 영상 데이터에 포함된 작물의 생장 변화에 따른 이미지들을 저장하고, 상기 영상 데이터와 작물의 생장 변화에 따른 이미지들을 비교하여 현재 하우스 내의 작물의 생장 상태를 추정하고, 상기 추정된 작물의 생장 상태에 따라 작물에 대한 급수, 배양, 온도 및 습도 중 적어도 하나의 설정을 변경하여 상기 급수부 또는 상기 환풍부의 관리 시나리오를 변경하며,상기 관리 장치는상기 온도 센서 및 상기 습도 센서의 출력을 제공받아 상기 상태 정보를 생성하여 저장하는 저장부;상기 관리 시나리오를 설정하는 시나리오 관리부; 및사용자 단말과 통신 회선을 형성하고, 상기 사용자 단말을 통하여 상기 저장부 또는 상기 시나리오 관리부에 대한 관리 인터페이스를 제공하는 통신 인터페이스 관리부;를 포함하는 것을 특징으로 하는 스마트 작물 재배 관리 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1114/1150 Row 1114: application_number: 1020217005861, combined_string: invention_title: 수경 재배 성장 시스템 및 방법 abstract: 수경 재배 성장 시스템에서 사용되는 장치(100)가 설명된다. 본 장치는 수직 부재(V) 및 일 세트의 성장 탈것(120)이 장착되는 수평 트랙 또는 안내로를 지지하는 수평 부재(H)를 포함한다. 성장 탈것 각각은, 식물 또는 작물이 성장하는 중에 그 식물 또는 작물이 수용되는 다수의 성장 트레이(127)를 포함한다. 본 장치(100)는 수경 재배 성장 시스템 내의 고 케어 시설 내에 위치된다. claims: 지지 구조물, 복수의 가동 지지 탈것 및 구동 유닛을 포함하는 수경 재배 성장 시스템으로서, 상기 지지 탈것은 상기 지지 구조물 상에 장착될 수 있고 또한 사용시 성장하는 작물을 포함하도록 배치되며, 상기 구동 유닛은 식물의 성장 동안에 상기 지지 탈것을 초기 위치로부터 최종 위치로 이동시키도록 배치되는, 수경 재배 성장 시스템.작물을 수경 재배로 성장시키는 방법으로서, 구동 유닛의 작용 하에서 안내로 상에서 이동하도록 지지 구조물에 장착되는 복수의 지지 탈것에서 작물을 성장시키는 것을 포함하고, 상기 방법은 지지 탈것을 초기 위치에 삽입하고 또한 최종 위치에서 그 지지 탈것을 제거하는 것을 포함하고, 상기 작물은 상기 초기 위치와 최종 위치 사이에서 성장하도록 배치되는, 작물을 수경 재배로 성장시키는 방법.컴퓨터 판독 가능한 매체에 있는 컴퓨터 프로그램 제품으로서, 컴퓨터로 실행되면, 그 컴퓨터가 제 13 항 내지 제 15 항 중 어느 한 항에 따른, 작물을 수경 재배로 성장시키는 방법을 수행하게 하는 지시를 포함하는, 컴퓨터 프로그램 제품.장치가 제 13 항 내지 제 15 항 중 어느 한 항에 따른, 작물을 수경 재배로 성장시키는 방법을 수행하게 하는 프로그램. 미리 정해진 작물을 성장시키기 위한 수경 재배 성장 시스템으로서, 전처리(pre-treatment) 부분과 고 케어(high care) 부분을 더 포함하고, 고 케어 부분은 씨를 뿌리고, 발아시키고 작물을 성장시키기 위한 장치를 포함하고, 또한 씨 뿌리기, 발아 및 식물의 성장 동안에 오염을 줄이기 위한 수단을 더 포함하는, 수경 재배 성장 시스템.고 케어 환경에서 작물을 성장시키는 방법으로서, 성장 매체에 씨를 뿌리는 단계; 씨를 발아시키는 단계; 작물을 성장시키는 단계; 및 작물을 수확하는 단계를 포함하고, 상기 작물은 제 18 항 내지 제 23 항 중 어느 한 항에 따른 수경 재배 성장 시스템 내의 고 케어 환경에서 씨 뿌려지고 발아되고 성장되며 또한 수확되는, 고 케어 환경에서 작물을 성장시키는 방법., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1115/1150 Row 1115: application_number: 1020190097827, combined_string: invention_title: 영양액의 안정적 공급과 재사용이 가능한 식물재배용기 abstract: 본 발명은 영양액의 안정적 공급과 재사용이 가능한 식물재배용기에 관한 것으로, 더욱 상세하게는, 심지를 방근시트로 포장하여 식물뿌리가 심지에 부착되는 현상을 방지하고, 심지가 용기 내벽면 고루 설치되어 양수분을 용기 전체에 균일하게 공급함으로써 뿌리를 전 방향으로 발달시킬 수 있도록 하며, 또한, 심지가 용기 외부에 노출되지 않아 미관을 향상시키는 동시에, 자동화 시설에 적합하고 운반 편의성을 향상시킬 수 있도록 개발된 영양액의 안정적 공급과 재사용이 가능한 식물재배용기에 관한 것이다.본 발명은 식물재배용기에 있어서, 내부공간이 마련된 용기본체; 상기 용기본체에 외부와 연통되게 형성된 침습시트설치홀; 및 식물재배에 필요한 양수분을 공급하기 위해, 상기 침습시트설치홀에 일측이 삽입되도록 상기 용기본체 내벽에 배치되는 침습시트;를 포함하는 것을 특징으로 한다. claims: 식물재배용기에 있어서,내부공간이 마련된 용기본체;상기 용기본체에 외부와 연통되게 형성된 침습시트설치홀; 및식물재배에 필요한 양수분을 공급하기 위해, 상기 침습시트설치홀에 일측이 삽입되도록 상기 용기본체 내벽에 배치되는 침습시트;를 포함한 것을 특징으로 하는 식물재배용기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1116/1150 Row 1116: application_number: 1020190093677, combined_string: invention_title: 높이조절이 가능한 수경재배용 포트장치 abstract: 본 발명은, 수경재배용 수조의 수위에 대하여 충수되는 높이를 조절하도록 됨에 따라, 재배물의 육성상태에 적합하게 높이를 조절하여 배치시킬 수 있도록 되어, 재배품질을 극대화하도록;상부가 개구되며 내부에 재배물의 뿌리가 심어진 상토가 수용되고 내외로 관통된 다수의 통수공이 구비된 수용공간을 가지며 수경재배용 물이 충수된 수조의 상부에 배치되어 상기 수조물을 통해 영양분을 상기 통수공들을 통해 인가받아 생육되도록 된 포트본체;를 포함하여 이루어지는 높이조절이 가능한 수경재배용 포트장치에 있어서; 상기 수조의 상부에 구비되는 안치부재의 고정공에 끼움고정되며 상하로 관통된 '관(管;pipe)' 형상의 '관체'로 이루어지고 상단테두리부위에 외측방향으로 연장형성되어 상기 고정공의 테두리부위의 상면에 받침되게 지지되도록 된 지지플랜지부가 형성되며 내주면에 상기 포트본체의 상단테두리부위에 외측방향으로 연장형성된 안치플랜지부가 받침되어 지지되는 지지수단이 구비된 고정관;을 더 포함하여 이루어지되; 상기 지지수단은, 상기 고정관의 내주면에서 수직상 사이간격을 가지면서 내측방향으로 돌출형성된 다수의 지지돌기들과; 상기 안치플랜지부에서 상기 지지돌기들이 관통되면서 안내되도록 된 안내홈;을 포함하여 이루어지는 높이조절이 가능한 수경재배용 포트장치를 제공한다. claims: 상부가 개구되며 내부에 재배물의 뿌리가 심어진 상토가 수용되고 내외로 관통된 다수의 통수공(31)이 구비된 수용공간을 가지며 수경재배용 물이 충수된 수조(11)의 상부에 배치되어 수조물을 통해 영양분을 상기 통수공(31)들을 통해 인가받아 생육되도록 된 포트본체(3)와; 상기 수조(11)의 상부에 구비되는 안치부재(4)의 고정공(41)에 끼움고정되며 상하로 관통된 '관(管;pipe)' 형상의 '관체'로 이루어지고 상단테두리부위에 외측방향으로 연장형성되어 상기 고정공(41)의 테두리부위의 상면에 받침되게 지지되도록 된 지지플랜지부(21)가 형성되며 내주면에 상기 포트본체(3)의 상단테두리부위에 외측방향으로 연장형성된 안치플랜지부(32)가 받침되어 지지되는 지지수단이 구비된 고정관(2);을 포함하여 이루어지는 높이조절이 가능한 수경재배용 포트장치(1)에 있어서;상기 지지수단은,상기 고정관(2)의 내주면에서 수직상 동일한 위치에 형성되는 다수개로 중앙을 중심으로 서로 대칭되는 위치에 각각 배치되어 서로 대면하도록 된 다수의 상기 지지돌기(51)들과; 상기 안치플랜지부(32)에서 상기 지지돌기(51)들이 관통되면서 안내되도록 된 안내홈(52);을 포함하여 이루어지며;상기 고정관(2)의 상단에는,상단에 상기 포트본체(3)의 안치플랜지부(32)가 받침지지되며 상부로 길이를 가지면서 구비되는 보조지지대(6)들이 상기 고정관(2)의 중앙을 중심으로 서로 대칭되는 위치에 각각 구비되고;각각의 상기 보조지지대(6)들의 상단에는,상기 안치플랜지부(32)에 형성된 안내홈(52)이 관통하면서 안내되는 연장돌기(61)가 각각 일체로 형성되는 것을 특징으로 하는 높이조절이 가능한 수경재배용 포트장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1117/1150 Row 1117: application_number: 1020190088012, combined_string: invention_title: 청정 새싹재배장치 abstract: 본 발명은 청정 새싹의 재배장치에 관한 것으로 물을 정화하고 가열하는 다기능성 보일러: 상기 보일러에 의해 멸균되게 가열된 물이 일정한 수위로 채워져 재배의 적정온도를 유지하는, 복수로 배치된 청정 재배조; 상기 재배조의 좌우 양측 가장자리 및 중앙부에 배치되어 가습기에서 생성된 포화안개를 분무(噴霧)하여 가습하는 복수의 분무관(噴霧管); 상기 재배조의 상부 개구부를 외부의 공기와 차단되게 밀폐하여 유해균의 침입(侵入)을 방지하도록 매직테이프로 개폐가능하게 접합된 차광 및 보온성의 덮개막을; 포함하여 구성된 것이다.본 발명에 의하면, 보일러에 의해 100℃로 가열된 온수에 의해 멸균, 또는 미생물의 활성이 억제되게 청정처리 된 상기 재배조에서 식물의 영양과 멸균 또는 미생물의 활동을 억제하는 효능을 가진 양액(Liquid nutrion)을 흡수시킨 재배포(栽培布)를 재배판에 깔고 씨앗을 살포하여 재배조의 물에 떠 있는 부판(浮板)위에 놓고 덮개막에 의해 재배조의 개구부가 밀폐된 청정 환경에서 초음파 가습기에서 생성된 안개를 상기 분무관을 통하여 가습하면서 재배하여, 3 ~ 4일의 극히 단기간에 미생물에 오염되지 않은 청정의 새싹 작물을 수확할 수 있다. claims: 가습기에 의해 가습하는 새싹 재배장치에 있어서,물을 정화하고 가열하는 다기능성 보일러와: 상기 보일러에 의해 가열된 물이 일정한 수위로 채워져 재배의 적정온도를 유지하는 청정 재배조와; 상기 재배조의 좌우 양측 가장자리 및 중앙부에 배치되어 가습기에 의해 생성된 안개를 분무(噴霧)하여 가습하는 복수의 분무관(噴霧管)과 ; 상기 재배조의 상부 개구부를 외부의 공기와 차단되게 밀폐하도록 매직테이프로 개폐가능하게 접합된 차광 및 보온성의 덮개막을; 포함하여 구성된 것을 특징으로 하는 청정 새싹의 재배장치.제2항에 있어서.새싹의 재배판은 재배포에 흡수된 양액에 의해 청정처리 되는 것을 특징으로 하는 청정 새싹의 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1118/1150 Row 1118: application_number: 1020190081411, combined_string: invention_title: 구근류 채굴장치 abstract: 본 발명은 구근류 채굴장치에 관한 것으로, 작업 차량에 연결되어 견인되는 프레임의 전방 하부에 구비되어 두둑 속의 작물을 채굴하는 굴취삽과, 굴취삽에 의해 채굴된 작물과 함께 제공되는 흙을 털어내 제거하여 작물을 이송시키는 제토컨베이어를 포함하는 채굴유니트를 갖는 구근류 채굴장치로서, 굴취삽은 그 선단부가 두둑을 향하도록 하향 경사지게 구비되되, 굴취삽의 후단부는 제토컨베이어의 전방 하부 영역에서 제토컨베이어와 이격된 상태로 제토컨베이어의 하면을 향하는 기울기로 경사지게 구비되어, 굴취삽에 의해 작물과 두둑이 파내어짐과 동시에 제토컨베이어에 접하여 작물과 흙이 분리되도록 한 구근류 채굴장치를 제공한다. claims: 작업 차량에 연결되어 견인되는 프레임의 전방 하부에 구비되어 두둑 속의 작물을 채굴하는 굴취삽과, 굴취삽에 의해 채굴된 작물과 함께 제공되는 흙을 털어내 제거하여 작물을 이송시키는 제토컨베이어를 포함하는 채굴유니트를 갖는 구근류 채굴장치로서, 굴취삽은 그 선단부가 두둑을 향하도록 하향 경사지게 구비되고, 굴취삽의 후단부는 제토컨베이어의 전방 하부 영역 내에서 제토컨베이어와 이격된 상태로 제토컨베이어의 하면을 향하는 기울기인 제토컨베이어의 하면 하단부와 만나는 선을 갖도록 경사지게 구비되어, 굴취삽에 의해 작물과 두둑이 파내어짐과 동시에 제토컨베이어에 접하여 작물과 흙이 분리되도록 하되, 두둑을 향하는 굴취삽의 선단부는 제토컨베이어의 전방 하부 영역을 벗어나 제토컨베이어의 전방으로 돌출되게 구비되는 구근류 채굴장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1119/1150 Row 1119: application_number: 1020190080160, combined_string: invention_title: 수직 재배대의 수평 순환을 이용하는 컨테이너 팜 abstract: 본 발명은 수직 재배대의 수평 순환을 이용하는 컨테이너 팜에 관한 것으로서, 컨테이너 내부의 천정 부근에 폐곡선을 이루도록 설치되는 레일, 레일에 이동 가능하게 결합되는 다수의 이동부재, 재배 식물이 심긴 포트가 장착되는 포트 장착 홈이 일정 간격으로 복수 개 형성된 수직 재배대, 레일에 결합된 이동부재를 이동시키는 이동조절수단을 포함하여 이루어진다. 이동부재 각각에 수직 재배대가 장착되어, 이동부재가 이동함에 따라 각 수직 재배대가 레일을 따라 수평 경로로 순환한다. 컨테이너의 내부 공간을 순환하는 수직 재배대를 이용하여 식물을 재배함에 따라, 컨테이너의 협소한 내부 공간을 최대한 재배 공간으로 활용할 수 있어서 식물 재배 밀도를 높일 수 있다. 또한, 재배 공간에 진입하지 않고 작업 공간에서 모든 식물을 관리할 수 있어서, 작물의 수확과 관리 등 운용이 편리해지며, 적은 인원으로 작물을 재배할 수 있다. claims: 컨테이너 내부의 천정 부근에 폐곡선을 이루도록 설치되는 레일;상기 레일에 이동 가능하게 결합되는 다수의 이동부재;재배 식물이 심긴 포트가 장착되는 포트 장착 홈이, 일정 간격으로 복수 개 형성된, 수직으로 긴 형상의 수직 재배대;상기 레일에 결합된 이동부재를 이동시키는 이동조절수단; 및상기 컨테이너 내부의 재배 환경을 조절하는 재배환경 조절 수단을 포함하여 이루어지고,상기 이동부재 각각에 상기 수직 재배대가 장착되어, 상기 이동부재가 이동함에 따라 상기 각 수직 재배대가 상기 레일을 따라 수평 경로로 순환하며,상기 레일이 형성하는 폐곡선은 외측을 'ㄷ' 형태로 감싸는 경로와, 이 외측을 감싸는 경로의 내부를 2회 이상 왕복하는 직선 경로를 포함하고,상기 각 수직 재배대에는 적어도 수용된 식물 관련 정보가 기록된 전자 코드가 표시되며,상기 재배환경 조절 수단은,상기 수직 재배대에 수용된 식물에 물과 영양분을 공급하는 영양분 공급부;상기 수직 재배대에 수용된 식물에 빛을 공급하는 조명부;상기 컨테이너 내부의 온도를 조절하는 온도 조절부;상기 컨테이너 내부의 습도를 조절하는 습도 조절부;상기 컨테이너 내부로 신선한 공기를 공급하고,상기 컨테이너 내부의 오염된 공기를 배출시키는 공조부;상기 수직 재배대에 표시된 전자 코드를 촬영하는 제1 카메라부;상기 수직 재배대에 수용된 각 식물을 촬영하는 제2 카메라부; 및상기 제1 카메라부에 의해 촬영된 전자 코드 정보와, 상기 제2 카메라부에 의해 촬영된 식물 상태 정보 중 적어도 하나 이상을 이용하여 재배 환경을 조절하는 제어부를 포함하여 이루어지며,상기 수직 재배대는 속이 빈 통의 형태로 구성되고, 상기 영양분 공급부는 상기 빈 통의 상단에서 물과 영양분을 공급하도록 구성되어, 물과 영양분이 상기 수직 재배대의 내부 공간을 따라 흘러내리면서 각 포트에 형성된 구멍을 통해 식물에 공급되는 것을 특징으로 하는, 컨테이너 팜., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1120/1150 Row 1120: application_number: 1020190079446, combined_string: invention_title: 머드 및 솔잎의 유효성분을 함유한 새싹 보리 재배방법 및 이에 의해 재배된 새싹 보리 abstract: 본 발명은 머드 및 솔잎의 유효성분을 함유한 새싹 보리 재배방법에 관한 것으로서, 발아에 적합한 보리를 선별하고 세척하는 선별 및 세척단계와, 머드 및 솔잎추출액을 이용하여 기능성 수용액을 제조하고, 상기 선별 및 세척된 보리를 상기 기능성 수용액에 침지시킨 후 불리는 불림단계와, 상기 기능성 수용액으로 불린 보리를 발아시키는 발아단계와, 상기 발아된 보리를 기능성 상토가 수용된 모종판에 식재하여 생육하는 생육단계 및 상기 생육된 새싹 보리를 채취하고 포장하는 채취 및 포장단계를 포함하여 재배되는 것을 특징으로 한다. 상기의 방법으로 재배된 새싹 보리는 머드 및 솔잎이 포함된 기능성 수용액을 보리의 발아 및 생육과정에서 사용함에 따라 머드 및 솔잎의 유효한 성분이 자연스럽게 흡수되고, 특히, 머드에 함유된 게르마늄이 보리의 발아 및 생육과정에서 자연스럽게 흡수되도록 하여 새싹 보리를 섭취하는 것으로 머드의 유효한 성분을 함께 섭취할 수 있는 장점이 있다. claims: 발아에 적합한 보리를 선별하고 세척하는 선별 및 세척단계(S10);머드 및 솔잎추출액을 이용하여 기능성 수용액을 제조하고, 상기 선별 및 세척된 보리를 상기 기능성 수용액에 침지시킨 후, 15~20℃의 온도를 유지하면서 48~72시간 동안 불리는 불림단계(S20);상기 기능성 수용액으로 불린 보리를 온도 28~30℃, 습도 75~80%의 범위를 유지시키면서, 20~25시간 동안 발아시키는 발아단계(S30);상기 발아된 보리를 기능성 상토가 수용된 모종판에 식재하여 생육하는 생육단계(S40); 및 상기 생육된 새싹 보리를 채취하고 포장하는 채취 및 포장단계(S50);를 포함하여 재배되되, 상기 기능성 수용액은, (i) 머드를 채취하여 이물질을 제거하는 전처리단계;(ii) 상기 전처리된 머드를 세척하여 염분함량을 50% 이하로 낮추는 세척단계;(iii) 상기 세척된 머드를 함수율이 20~30%의 범위가 되도록 건조한 후 입자크기가 0.1~0.2mm가 되도록 분쇄하는 건조 및 분쇄단계;(iv) 상기 건조 및 분쇄된 머드분말을 멸균처리하는 멸균단계; (v) 상기 멸균된 머드분말 100중량부에 정제수 700~800중량부를 혼합하는 혼합단계; 및 (vi) 상기 정제수가 혼합된 머드수 100중량부에 솔잎추출액을 15~20중량부 추가하는 추가단계;를 포함하여 제조되고,상기 솔잎추출액은, 소나무의 잎을 세척 및 건조하고 5~10mm 크기로 분쇄한 후, 상기 분쇄된 솔잎에 물을 중량대비 1 : 3~5의 비율로 혼합하고 90~110℃의 온도에서 2~3시간 동안 가열한 후 여과하여 제조된 것이며,상기 생육단계(S40)의 기능성 상토는,원예용 상토 100중량부에 솔잎분말 5~7중량부, 해조류 추출물 3~5중량부를 혼합하여 제조되되,상기 솔잎분말은 소나무의 잎을 세척 및 건조한 후, 0.5~2mm 크기로 분쇄한 것이고,상기 해조류 추출물은 미역, 다시마, 톳 중 하나 또는 둘 이상을 혼합한 해조류를 세척하고, 수분함량이 5~10%가 되도록 건조한 후, 입자크기가 100~120mesh의 크기로 분쇄한 해조류분말에 정제수를 중량대비 1 : 7~10의 비율로 혼합하여 70~80℃의 온도에서 5~6시간 동안 교반가열하여 액상의 추출물을 수득한 후, 감압농축 및 동결건조한 것이며,상기 생육단계(S40)는,상기 발아된 보리를 생육하는 과정에서 5~7시간 간격으로, 모종판 부피대비 10~15%의 기능성 수용액을 공급하는 것을 특징으로 하는 머드 및 솔잎의 유효성분을 함유한 새싹 보리 재배방법., Ltext: 농업, prediction: '농업' 카테고리

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1121/1150 Row 1121: application_number: 1020190076890, combined_string: invention_title: 작물용 재배장치 및 이를 이용한 재배방법 abstract: 본 발명은 작물용 재배장치 및 이를 이용한 재배방법에 관한 것으로, 토압의 영향을 많이 받는 작물을 재배함에 있어서, 본 발명에 토압 조절부를 포함시킴으로써, 작물용 재배장치에 토양을 채우기 전 토압 조절부에 공기를 주입하여 토양에 공간을 확보하고, 작물이 성장하는 과정에서 토양이 밀려나게 되면 팽창부재에 공기를 유출시켜 팽창부재가 차지하던 공간에 밀려난 토양이 채워질 수 있도록 하여, 작물이 성장하는데 용이하게 공간이 확보될 수 있도록 하는 작물용 재배장치 및 이를 이용한 재배방법을 제공하는데 목적이 있다.상기한 목적을 달성하기 위해 본 발명은, 작물용 재배장치에 있어서, 작물이 재배될 수 있도록 토양이 저장되는 본체 하우징; 상기 본체 하우징에 삽입되는 토압 조절부; 상기 토압 조절부에 공기가 유·출입될 수 있도록 하는 공기 조절부 및 상기 작물에 영양분이 공급될 수 있도록 하는 영양 공급관을 포함하며, 상기 토압 조절부는, 상기 본체 하우징 내부에 삽입되는 다수개의 공기 이동관; 상기 공기 이동관과 공기 이동관이 연결될 수 있도록 하는 연결부재; 상기 다수개의 공기 이동관 중 어느 하나와 결합되는 공기 조절관 및 상기 공기 조절관이 개폐될 수 있도록 하는 밸브를 포함하는 것을 특징으로 하는 작물용 재배장치이다. claims: 작물용 재배장치에 있어서,작물이 재배될 수 있도록 토양이 저장되는 본체 하우징;상기 본체 하우징에 삽입되는 토압 조절부;상기 토압 조절부에 공기가 유·출입될 수 있도록 하는 공기 조절부 및상기 작물에 영양분이 공급될 수 있도록 하는 영양 공급관을 포함하며,상기 토압 조절부는,상기 본체 하우징 내부에 삽입되는 다수개의 공기 이동관;상기 공기 이동관과 공기 이동관이 연결될 수 있도록 하는 연결부재;상기 다수개의 공기 이동관 중 어느 하나와 결합되는 공기 조절관 및상기 공기 조절관이 개폐될 수 있도록 하는 밸브를 포함하는 것을 특징으로 하는 작물용 재배장치.제 1항 내지 제 5항 중 어느 하나인 작물용 재배장치를 이용한 작물 재배방법에 있어서,상기 공기 조절부를 통해 상기 팽창부재에 공기를 유입하는 단계;상기 확장된 팽창부재 사이에 토양을 채우는 단계;상기 채워진 토양에 물을 공급하는 단계;상기 공급된 물은 상기 토양에 흡수되고, 흡수되지 않은 물을 배수하는 단계;상기 팽창부재가 위치된 곳에 작물을 심는 단계 및상기 작물이 성장하는 동안 상기 팽창부재에서 공기를 유출시키는 단계를 포함하는 것을 특징으로 하는 작물 재배방법., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1122/1150 Row 1122: application_number: 1020190072540, combined_string: invention_title: 알곡 선별장치 abstract: 본 발명은 구조가 단순하고 기능적으로 합리적이며, 무동력 자연 낙하방식을 통해 싸라기를 선별스프링의 강선 와이어 사이로 간단하게 낙하시켜 효율적으로 선별할 수 있음은 물론 선별하고자 하는 알곡 및 싸라기의 크기 변화에 적합한 싸라기 낙하 통과 간격을 용이하게 조정 가능하여 매우 편리하고, 제조 및 관리의 편리성과 유지 비용의 경제성을 향상시킬 수 있도록 개량한 알곡 선별장치에 관한 것이다. claims: 알곡(11) 및 싸라기(12)로 이루어지는 도정된 곡물이 유입구(a)로 공급되고, 상기 곡물을 이동시키면서 싸라기(12)를 낙하시키고 알곡(11)만을 배출구(b)로 낙하시켜 분리시키는 단위체인 선별부재(1)를 포함하되;상기 선별부재(1)는 강선 와이어(21)가 나선형으로 권선되어 이루어지는 선별스프링(2)과, 도정된 곡물 유입구(a)가 형성된 전방소켓(3)과, 선별된 알곡(11)을 배출시키는 배출구(b)가 형성된 후방소켓(4) 및 낙하물을 차단하는 차양판(5)으로 이루어지고;상기 선별스프링(2)의 양단은 전방소켓(3) 및 후방소켓(4)에 끼워진 후 고정되면서 강선 와이어(21) 틈새의 간격이 변화될 수 있도록 이루어지며;상기 선별부재(1)는 도정된 곡물이 이동하면서 싸라기(12)를 선별스프링(2)의 강선 와이어(21)의 틈새로 낙하시키고 알곡(11)만이 후방소켓(4)의 배출구(b)로 배출하여 분리 수집할 수 있도록 경사지게 이루어진 것에 있어서,상기 차양판(5)은 상부편(51)과 하부편(52)으로 분할 형성하되, 상부편(51)이 하부편(52)의 상측 일부를 덮을 수 있도록 단차를 이루는 연장부(511)가 형성되어 이루어지고;상기 차양판(5)의 상부편(51)과 하부편(52)에는 걸림돌기(5a, 5b)를 형성하고 전방소켓(3) 및 후방소켓(4)에는 상기 걸림돌기(5a, 5b)가 걸려 고정되도록 걸림홈(31, 41)을 각각 형성하여 고정하거나, 상부편(51)과 하부편(52)이 양단이 전방소켓(3) 및 후방소켓(4)에 나사못(6)의 체결로 고정될 수 있도록 이루어진 것을 특징으로 하는 알곡 선별장치.알곡(11) 및 싸라기(12)로 이루어지는 도정된 곡물이 유입구(a)로 공급되고, 상기 곡물을 이동시키면서 싸라기(12) 및 쭉정이를 낙하시키고 알곡(11)만을 배출구(b)로 낙하시켜 분리시키는 단위체인 선별부재(1')를 포함하여 이루어지는 알곡(11) 선별장치에 있어서,상기 선별부재(1')는 강선 와이어(21)가 나선형 코일스프링 형태로 권선되어 이루어지는 선별스프링(2)과, 도정된 곡물 유입구(a)가 형성된 전방소켓(3)과, 선별된 알곡(11)을 배출시키는 배출구(b)가 형성된 후방소켓(4') 및 낙하물을 차단하는 차양판(5')으로 이루어지고;상기 선별스프링(2)의 일단은 전방소켓(3)에 끼워진 후 고정되며;상기 선별스프링(2)의 타단은 후방소켓(4')으로 유입되어 이동하는 연결관(9)에 끼워진 후 고정되고;상기 차양판(5')은 단일체로 형성되고 양단에 걸림돌기(5c)를 형성하여 전방소켓(3) 및 후방소켓(4')에 형성된 걸림홈(31, 41)에 끼워져 고정되거나, 나사못(6)의 체결로 고정될 수 있도록 이루어지고;상기 연결관(9)의 이동시 선별스프링(2)의 강선 와이어(21)의 틈새가 가변될 수 있도록 이루어지며;상기 선별부재(1')는 도정된 곡물이 자중에 의해 이동하면서 싸라기(12)를 선별스프링(2)의 강선 와이어(21)의 틈새로 낙하시키고 알곡(11)만이 연결관(9)의 배출구(b)로 낙하시키도록 경사를 이루는 것을 특징으로 하는 알곡 선별장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1123/1150 Row 1123: application_number: 1020190070019, combined_string: invention_title: 새싹삼 수경재배장치 및 새싹삼 수경재배방법 abstract: 본 발명은 새싹삼 수경재배장치 및 새싹삼 수경재배방법에 관한 것으로,설치구조가 매우 간단하여 시설투자비가 적게 들고, 장소의 구애됨이 없이 설치가 가능하며, 전문 재배기술이나 많은 경험이 없는 초심자라도 누구나 재배가 가능하며, 토양의 관리에 대한 걱정이 없는 등 관리가 매우 용이함은 물론,가장 핵심적인 것은 묘삼을 꽂아 세우는 방식이 아니라 단순히 머리부분이 상측방향을 향하도록 경사지게 안착시켜 주고 뿌리부분을 덮는 방식으로 구성된 것이어서, 묘삼의 가늘고 연약한 뿌리나 외피(표피) 등의 훼손이 전혀 없으므로 묘삼의 생장에 장애가 되는 요소가 완벽하게 차단되며,묘삼에는 재배 중 수분이 항상 충분하게 공급되어야 하는데 본 발명에서는 바닥면을 구성하는 베이스시트부재가 물을 통과시켜 주기는 하나 어느 정도 물기를 머금을 수 있고 특히, 흡습부재가 물을 장시간 머금은 상태를 유지하므로 종래보다 적은 양을 물을 공급하여 주어도 묘삼에 물을 장시간 지속적으로 공급하여 줄 수 있어서 생장이 촉진되며, 워터펌프의 가동시간 및 횟수를 줄여 줄 수 있으므로 운영단가도 매우 저렴하게 되는 등 결과적으로 적은 비용으로 누구나 간편하고 손쉽게 전체적으로 품질이 균일한 양질의 새싹인삼을 안전하게 대량 재배할 수 있는 것을 그 특징으로 한다. claims: 어린 묘삼(10)을 소정기간동안 키워낼 수 있는 수경재배장치를 구성함에 있어서,다단으로 구획되고, 각각의 구획부(100a) 상측에 스프링클러(110)를 구비한 기틀체(100)와;다단으로 구획된 각각의 구획부(100a) 바닥면을 이루도록 설치되며 섬유, 합성수지재 또는 부직포 중 어느 하나 또는 이들의 혼합물로서 물이 용이하게 통과하도록 망 또는 엉성한 조직을 갖도록 만들어진 베이스시트부재(200)와;상기 베이스시트부재 상에 소정간격으로 안착되며 스펀지(sponge)나 면, 합성수지재, 식물줄기를 재직하거나 부직포, 팰트 형태로 만든 적어도 하나 이상으로서 물기를 흡습하는 흡습부재(300)와;그리고 맨 하단의 베이스시트부재(200) 저면에 설치되어 하측으로 낙하하는 물을 스프링클러(110)와 연계설치되는 워터펌프(510)가 구비된 물저장탱크(500)로 회수하는 물받이(400) 및;상기 워터펌프(510)를 수동 또는 설정된 시간 마다 자동으로 동작시켜 주는 제어부를 포함하여 이루어지되,상기 흡습부재(300)의 안착시 먼저 안착시킨 흡습부재(300)에 묘삼(10)의 머리부분을 올려 놓고 뿌리부분은 베이스시트부재(200)에 안착시켜 전체적으로 머리부분이 상측방향을 향하도록 한다음,다음번 흡습부재(300)를 묘삼(10)의 뿌리부분을 덮어주도록 안착시키는 방법을 반복하여 소정간격으로 대량의 묘삼(10)을 경사지게 안착시키고 스프링클러(110)를 이용하여 물을 공급하여 일부는 흡습부재(300)가 머금어 묘삼(10)의 뿌리가 마르지 않도록 지속적으로 수분을 공급하고,일부는 베이스시트부재(200)를 통과하면서 낙하하여 물받이(400)를 통해 물저장탱크(500)로 회수되어 재활용되면서 새싹삼을 재배토록 이루어짐을 특징으로 하는 새싹삼 수경재배장치.소정폭과 길이 및 높이로 구축한 기틀체(100)에 소정높이로 섬유, 합성수지재 또는 부직포 중 어느 하나 또는 이들의 혼합물로서 물이 통과하도록 만들어진 베이스시트부재(200)를 깔아 바닥면을 형성하는 단계(S1)와;상기 베이스시트부재(200) 상면에 소정간격으로 스펀지(sponge)나 면, 합성수지재, 식물줄기를 재직하거나 부직포, 팰트 형태로 만든 적어도 하나 이상으로서 물기를 흡습하는 흡습부재(300)를 안착시키되,먼저 베이스시트부재(200) 상면에 첫번째 흡습부재(300)를 안착시킨 후 안착시킨 흡습부재(300)에 묘삼(10)의 머리부분을 올려 놓고 뿌리부분은 베이스시트부재(200)에 안착시켜 전체적으로 머리부분이 상측방향을 향하도록 하는 단계(S2)와;상기 첫번째 흡습부재(300)에 머리부분이 올려진 묘삼(10)의 뿌리부분을 두번째 흡습부재를 이용하여 덮어 주는 단계(S3)와;상기 단계(S3)에서 묘삼(10)의 뿌리부분을 덮고 있는 흡습부재(300)에 재차 묘삼(10)의 머리부분을 올려 놓고 뿌리부분은 베이스시트부재(200)에 안착시켜 전체적으로 머리부분이 상측방향을 향하도록 한 다음, 그 다음번 흡습부재(300)를 묘삼(10)의 뿌리부분을 덮어 주는 방법을 연속적으로 반복하여 대량의 묘삼(10)을 경사지게 안착 완료하는 단계(S4)와;상기 단계(S4) 수행 후 제어부를 수동 또는 자동으로 제어하여 워터펌프(510)를 작동시켜 물저장탱크(500)내의 물이나 양액을 스프링클러(110)를 통해 묘삼에 공급하여 일부는 흡습부재(300)가 머금어 묘삼(10)의 뿌리가 마르지 않도록 지속적으로 수분을 공급하고,일부는 베이스시트부재(200)를 통과하면서 낙하하여 물받이(400)를 통해 워터펌프(510)가 구비된 물저장탱크(500)로 회수되어 재활용시키는 단계(S5);를 포함하여 새싹삼을 재배토록 이루어짐을 특징으로 하는 새싹삼 수경재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1124/1150 Row 1124: application_number: 1020190068464, combined_string: invention_title: 유기 바나듐을 함유한 벼의 재배방법 abstract: 본 발명은 유기 바나듐을 함유한 벼의 재배방법에 관한 것으로,바나듐 원료를 300메시 이하의 크기로 파쇄하는 과정과,맥반석, 토루말린, 제오라이트, 견운모 및 황토을 각각 300메시 이하의 크기로 파쇄하여 적어도 하나 이상 동일한 비율로 혼합하는 과정과,파쇄한 바나듐 원료 80~90중량%에 300메시 이하의 크기로 파쇄한 맥반석, 토루말린, 제오라이트, 견운모, 황토의 무기물 10~20중량%를 혼합하여 바나듐 혼합물을 제조하는 과정과,상기의 바나듐 혼합물을 물에 500배 정도 희석하여 바나듐 희석액을 제조하는 과정과,상기의 바나듐 희석액을 비료 주듯이 벼의 이삭이 맺히기 시작하는 시기를 전후하여 2-3회 정도 뿌려주는 과정에 의하여 벼의 이삭에 바나듐 물질이 형성되도록 함으로써 쌀에서 강력한 항산화력으로 활성산소 제거하면서 신체 조직의 노화와 변성을 막거나 속도를 지연시키는 효과가 있는 바나듐 성분이 검출되도록 하고, 무기질에 의한 원적외선과 음이온 등을 발생하여 식물의 생장에 도움을 주도록 함은 물론, 미네랄 종류의 영양제로서 벼가 왕성하게 성장하도록 도와주도록 구성됨을 특징으로 한다. claims: 바나듐 원료를 300메시 이하의 크기로 파쇄하는 과정과,맥반석을 300메시 이하의 크기로 파쇄하는 과정과,토루말린을 300메시 이하의 크기로 파쇄하는 과정과,제오라이트를 300메시 이하의 크기로 파쇄하는 과정과,견운모를 300메시 이하의 크기로 파쇄하는 과정과,황토를 300메시 이하의 크기로 파쇄하는 과정과,상기의 맥반석, 토루말린, 제오라이트, 견운모 및 황토의 무기질을 적어도 하나 이상 동일한 비율로 혼합하는 과정과,파쇄한 바나듐 원료 80~90중량%에 300메시 이하의 크기로 파쇄한 맥반석, 토루말린, 제오라이트, 견운모, 황토의 무기물 10~20중량%를 혼합하여 바나듐 혼합물을 제조하는 과정과,상기의 바나듐 혼합물을 물에 500배 정도 희석하여 바나듐 희석액을 제조하는 과정과,상기의 바나듐 희석액을 비료 주듯이 벼의 이삭이 맺히기 시작하는 시기를 전후하여 2-3회 정도 뿌려주는 과정으로 구성한 것을 특징으로 하는 유기 바나듐을 함유한 벼의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1125/1150 Row 1125: application_number: 1020190068465, combined_string: invention_title: 유기 셀레늄을 함유한 벼의 재배방법 abstract: 본 발명은 유기 셀레늄을 함유한 벼의 재배방법에 관한 것으로,셀레늄 원료를 300메시 이하의 크기로 파쇄하는 과정과,맥반석, 토루말린, 제오라이트, 견운모 및 황토을 각각 300메시 이하의 크기로 파쇄하여 적어도 하나 이상 동일한 비율로 혼합하는 과정과,파쇄한 셀레늄 원료 80~90중량%에 300메시 이하의 크기로 파쇄한 맥반석, 토루말린, 제오라이트, 견운모, 황토의 무기물 10~20중량%를 혼합하여 셀레늄 혼합물을 제조하는 과정과,상기의 셀레늄 혼합물을 물에 500배 정도 희석하여 셀레늄 희석액을 제조하는 과정과,상기의 셀레늄 희석액을 비료 주듯이 벼의 이삭이 맺히기 시작하는 시기를 전후하여 2-3회 정도 뿌려주는 과정에 의하여 벼의 이삭에 셀레늄 물질이 형성되도록 함으로써 쌀에서 암의 예방과 치료, 에이즈 증상 완화, 제2형 당뇨병 억제 등에 효과가 있는 셀레늄 성분이 검출되도록 하고, 무기질에 의한 원적외선과 음이온 등을 발생하여 식물의 생장에 도움을 주도록 함은 물론, 미네랄 종류의 영양제로서 벼가 왕성하게 성장하도록 도와주도록 구성됨을 특징으로 한다. claims: 셀레늄 원료를 300메시 이하의 크기로 파쇄하는 과정과,맥반석을 300메시 이하의 크기로 파쇄하는 과정과,토루말린을 300메시 이하의 크기로 파쇄하는 과정과,제오라이트를 300메시 이하의 크기로 파쇄하는 과정과,견운모를 300메시 이하의 크기로 파쇄하는 과정과,황토를 300메시 이하의 크기로 파쇄하는 과정과,상기의 맥반석, 토루말린, 제오라이트, 견운모 및 황토의 무기질을 적어도 하나 이상 동일한 비율로 혼합하는 과정과,파쇄한 셀레늄 원료 80~90중량%에 300메시 이하의 크기로 파쇄한 맥반석, 토루말린, 제오라이트, 견운모, 황토의 무기물 10~20중량%를 혼합하여 셀레늄 혼합물을 제조하는 과정과,상기의 셀레늄 혼합물을 물에 500배 정도 희석하여 셀레늄 희석액을 제조하는 과정과,상기의 셀레늄 희석액을 비료 주듯이 벼의 이삭이 맺히기 시작하는 시기를 전후하여 2-3회 정도 뿌려주는 과정으로 구성한 것을 특징으로 하는 유기 셀레늄을 함유한 벼의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1126/1150 Row 1126: application_number: 1020190068702, combined_string: invention_title: 수확기 및 콤바인 abstract: 언로더를 사용한 수확물의 배출 시에 수확물에 과잉의 힘이 가해지지 않는 수확기를 제공한다. 또한, 언로더에 큰 부하가 가해지는 것을 피할 수 있는 수확기를 제공한다. 또한, 운전자의 의도대로 예취 곡간의 긁어 넣기가 가능한 콤바인을 제공한다.수확기는, 엔진으로부터의 동력을 사용하여 수확물을 수확물 탱크로부터 기체의 외부로 배출하는 반송 기구를 갖는 언로더와, 반송 기구를 구동하는 온 위치와 반송 기구를 정지하는 오프 위치를 갖는 배출 클러치와, 클러치 온 명령에 기초하여, 배출 클러치를 온 위치로 전환하는 온 동작 신호를 출력하는 배출 클러치 제어부와, 엔진의 회전수를, 아이들링 회전수와 정격 회전수 사이의 배출 회전수로 조절하는 엔진 제어 유닛을 구비하고 있다. 배출 클러치 제어부는, 클러치 온 명령에 기초하여 엔진 제어 유닛에 배출 회전수로의 조절을 요구하고, 엔진의 회전수가 배출 회전수에 도달한 때에 온 동작 신호를 출력한다. 또한, 수확기는, 수확물 탱크로부터 기체의 외부로 수확물을 배출하는 배출 자세와, 기체에 수납 보유 지지되는 수납 자세 사이에서 자세 변경 가능한 언로더의 자세를 검출하는 자세 검출부와, 주행 장치에 대한 거동 요구를 출력하는 주행 조작구와, 주행 장치의 거동을 제어하는 주행 제어 모드로서, 제1 주행 제어 모드와, 주행 시에 상기 언로더에 미치는 관성 부하가 상기 제1 주행 제어 모드보다 적어지는 제2 주행 제어 모드를 관리하는 주행 제어 모드 관리부와, 자세 검출부가 상기 수납 자세를 검출하고 있는 경우에, 상기 제1 주행 제어 모드를 사용하여 상기 거동 요구에 기초하여 상기 주행 장치를 제어하고, 자세 검출부가 수납 자세 이외를 검출하고 있는 경우에, 제2 주행 제어 모드를 사용하여 거동 요구에 기초하여 주행 장치를 제어하는 주행 제어부를 구비한다. 또한, 엔진의 동력에 의해 구동하는 주행 장치와, 기체에 상하 요동 가능하게 지지되어, 엔진의 동력에 의해 구동하고, 포장의 식립 곡간을 예취하여 반송하는 예취부와, 제1 조작구의 조작에 기초하여, 엔진으로부터의 동력을 예취부로 전달하는 전달 상태와, 엔진으로부터의 동력을 예취부로 전달하지 않는 비전달 상태로 전환되는 클러치 기구(2020)와, 예취부가 미리 정해진 설정 높이 H1 이상으로 상승되면, 클러치 기구(2020)를 비전달 상태로 변경하는 자동 전환부(2032)와, 제2 조작구(2054)의 조작에 기초하여, 주행 장치가 정지하면서 예취부가 구동하는 긁어 넣기 상태를 현출하는 긁어 넣기부가 구비되어 있다. 긁어 넣기부는, 자동 전환부(2032)에 의해 클러치 기구(2020)가 비전달 상태로 되어 있는 상태일 때는, 클러치 기구(2020)를 강제적으로 전달 상태로 변경한다. claims: 수확된 수확물을 저류하는 수확물 탱크와,엔진으로부터의 동력을 사용하여 상기 수확물을 상기 수확물 탱크로부터 기체의 외부로 배출하는 반송 기구를 갖는 언로더와,상기 반송 기구를 구동하는 온 위치와 상기 반송 기구를 정지하는 오프 위치를 갖는 배출 클러치와,클러치 온 명령에 기초하여, 상기 배출 클러치를 상기 온 위치로 전환하는 온 동작 신호를 출력하고, 클러치 오프 명령에 기초하여 상기 배출 클러치를 상기 오프 위치로 전환하는 오프 동작 신호를 출력하는 배출 클러치 제어부와,상기 엔진의 회전수를, 아이들링 회전수와, 정격 회전수와, 상기 아이들링 회전수와 상기 정격 회전수 사이의 배출 회전수로 조절하는 엔진 제어 유닛을 구비하고,상기 배출 클러치 제어부는, 상기 클러치 온 명령에 기초하여 상기 엔진 제어 유닛에 상기 배출 회전수로의 조절을 요구하고, 상기 엔진의 회전수가 상기 배출 회전수에 도달한 때에 상기 온 동작 신호를 출력하는, 수확기.주행 장치와, 수확된 수확물을 저류하는 수확물 탱크와,상기 수확물 탱크로부터 기체의 외부로 상기 수확물을 배출하는 배출 자세와, 상기 기체에 수납 보유 지지되는 수납 자세 사이에서 자세 변경 가능한 언로더와,상기 언로더의 자세를 검출하는 자세 검출부와,상기 주행 장치에 대한 거동 요구를 운전자의 조작에 기초하여 출력하는 주행 조작구와,상기 주행 장치의 거동을 제어하는 주행 제어 모드로서, 제1 주행 제어 모드와, 주행 시에 상기 언로더에 미치는 관성 부하가 상기 제1 주행 제어 모드보다 적어지는 제2 주행 제어 모드를 관리하는 주행 제어 모드 관리부와,상기 자세 검출부가 상기 수납 자세를 검출하고 있는 경우에, 상기 제1 주행 제어 모드를 사용하여 상기 거동 요구에 기초하여 상기 주행 장치를 제어하고, 상기 자세 검출부가 상기 수납 자세 이외를 검출하고 있는 경우에, 상기 제2 주행 제어 모드를 사용하여 상기 거동 요구에 기초하여 상기 주행 장치를 제어하는 주행 제어부를 구비한, 수확기.엔진과,상기 엔진의 동력에 의해 구동하는 주행 장치와,기체에 상하 요동 가능하게 지지되어, 상기 엔진의 동력에 의해 구동하고, 포장의 식립 곡간을 예취하여 반송하는 예취부와,제1 조작구의 조작에 기초하여, 상기 엔진으로부터의 동력을 상기 예취부로 전달하는 전달 상태와, 상기 엔진으로부터의 동력을 상기 예취부로 전달하지 않는 비전달 상태로 전환되는 클러치 기구와,상기 예취부가 미리 정해진 설정 높이 이상으로 상승되면, 상기 클러치 기구를 상기 비전달 상태로 변경하는 자동 전환부와,제2 조작구의 조작에 기초하여, 상기 주행 장치가 정지하면서 상기 예취부가 구동하는 긁어 넣기 상태를 현출하는 긁어 넣기부가 구비되고,상기 긁어 넣기부는, 상기 자동 전환부에 의해 상기 클러치 기구가 상기 비전달 상태로 되어 있는 상태일 때는, 상기 클러치 기구를 강제적으로 상기 전달 상태로 변경하는, 콤바인., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1127/1150 Row 1127: application_number: 1020190066519, combined_string: invention_title: 수확기 abstract: 본 발명의 과제는 엔진 보닛의 상방에 배치된 운전 좌석을 가진 수확기에 있어서, 운전부를 대형화하지 않고 배기 가스 정화 장치와 운전 좌석의 기체 상하 방향에서의 겹침을 회피하면서 배기 가스 정화 장치를 엔진 보닛 내의 디젤 엔진의 상방에 설치할 수 있도록 하는 것이다.디젤 엔진(21)의 배기 가스를 도입하여 배기 가스의 정화 처리를 행하는 배기 가스 정화 장치(50)를, 배기 가스 정화 장치(50)의 전체가 운전 좌석(12)에 대해 예취부측으로 치우치고, 또한 배기 가스 정화 장치(50)의 기체 횡방향에서의 일부가 운전부의 예취부측 횡벽(11c)으로부터 예취부측으로 돌출되는 배치로 엔진 보닛(22) 내에 설치하고 있다.본 발명의 과제는 엔진 보닛 내의 디젤 엔진의 상방에 배기 가스 정화 장치를 설치하는 데 있어서, 운전 좌석의 상승을 방지나 억제하면서 설치하는 것을 가능하게 하는 것이다.디젤 엔진(21)의 배기 가스를 도입하여 배기 가스의 정화 처리를 행하는 배기 가스 정화 장치(50)를, 엔진 보닛 내의 디젤 엔진(21)의 상방에 운전 좌석(12)에 대해 기체 횡내측으로 치우치게 하여 설치하고 있다. 엔진 보닛(22)에 있어서의 천장판부(30)의 배기 가스 정화 장치(50)의 상방에 위치하는 정화 장치 상방부(32)가 엔진 보닛(22)에 있어서의 운전 좌석(12)의 하방에 위치하는 좌석 하방부(31)보다 높은 배치 높이에 위치하도록, 천장판부(30)의 형상을 단차 형상으로 하고 있다.본 발명의 과제는 배기 가스 정화 장치에 접속하는 배기관을 유리하게 얻거나 접속 작업하는 것을 가능하게 하면서 배기 가스 정화 장치를 디젤 엔진의 상방에 장비할 수 있도록 하는 것이다.디젤 엔진(21)의 상방에 한 쌍의 지지부(61a, 62a)를 크랭크축 방향과 교차하는 방향으로 나란히 설치하고 있다. 디젤 엔진(21)의 배기 가스를 도입하여 배기 가스의 정화 처리를 행하는 배기 가스 정화 장치(50)를, 길이 방향이 크랭크축 방향과 교차하는 설치 자세로 한 쌍의 지지부(61a, 62a)에 연결하고 있다. claims: 디젤 엔진을 내장하는 엔진 보닛을 구비하고, 상기 엔진 보닛의 상방에 배치된 운전 좌석을 가진 운전부를 구비한 수확기이며,상기 디젤 엔진의 배기 가스를 도입하여 배기 가스의 정화 처리를 행하는 배기 가스 정화 장치를, 상기 엔진 보닛 내의 상기 디젤 엔진의 상방에 상기 운전 좌석에 대해 기체 횡내측으로 치우치게 하여 설치하고,상기 엔진 보닛에 있어서의 천장판부의 상기 배기 가스 정화 장치의 상방에 위치하는 정화 장치 상방부가 상기 엔진 보닛에 있어서의 상기 운전 좌석의 하방에 위치하는 좌석 하방부보다 높은 배치 높이에 위치하도록, 상기 천장판부의 형상을 단차 형상으로 하고 있는, 수확기., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1128/1150 Row 1128: application_number: 1020190057496, combined_string: invention_title: Ａ자형 버킷 컨베이어식 배종장치를 구비한 파종기 abstract: 본 발명은 작물 파종기에 관한 것으로, 상세하게는, 트랙터 등과 같은 견인장치에 의해 견인되어 밭이랑을 따라 이동하면서 호퍼에 담긴 각종 작물의 종자(예컨대, 통감자 등)를 A자형 버킷 컨베이어 배종장치를 매개로 하나씩 이송한 후 이송된 종자를 좌우로 낙하시켜 밭의 두둑에 심어 파종함으로써 종자 배종시 소요되는 노동력을 최소화할 수 있는 A자형 버킷 컨베이어식 배종장치를 구비한 파종기에 관한 것이다. claims: 견인장치에 견인되는 본체;상기 본체의 후단 상부에 설치되고, 내부에 종자가 수용되는 호퍼; 및상기 호퍼로부터 투입되는 종자를 순차적으로 이송하여 밭이랑에 파종하는 컨베이어식 배종장치;를 포함하고, 상기 컨베이어식 배종장치는, 종자가 수용되는 버킷이 일정 간격으로 설치된 2열의 배종라인을 구비하고, 각 배종라인은 상기 호퍼로부터 공급되는 종자를 차례로 이송한 후 밭이랑에 배출하여 파종하되, 상기 2열의 배종라인은 상부측 사이의 간격은 좁고 하부측 사이의 간격이 벌어지도록 배치되고, 상기 배종라인들의 후단부를 연결하는 연결부재가 구비되어, 후면에서 볼 때 'A'자 형태를 이루도록 하며, 상기 2열의 배종라인의 하부측에 설치된 연결부재는 길이방향으로 길이가 가변되는 구조로 이루어지고, 상기 배종라인의 상부측은 힌지부재 또는 볼 조인트를 매개로 본체에 결합되거나 상호 결합되어 배종라인의 하부 간격이 조정되는 방향으로 회전할 수 있도록 구성되어, 하부측은 상부측을 축으로 하여 서로 멀어지는 방향 또는 서로 근접하는 방향으로 유동하여 배출부 사이의 간격을 조정할 수 있도록 하고,상기 2열의 배종라인은 호퍼가 설치되는 후단부측의 높이가 상대적으로 낮은 경사 구조로 배치되는 것을 특징으로 하는 A자형 버킷 컨베이어식 배종장치를 구비한 파종기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1129/1150 Row 1129: application_number: 1020210118072, combined_string: invention_title: 식물포트 이송장치를 가지는 아쿠아포닉스 및 수경 재배 시스템 abstract: 본 발명은 아쿠아포닉스 또는 수경재배를 위한 저수부가 마련되는 수조; 상기 수조 상에서 링형태의 경로를 이동 가능하도록 다수로 배치되고, 식물포트가 상기 저수부의 물이나 양액에 잠기도록 끼워지기 위한 끼움홀이 적어도 하나 이상 형성되는 포트베드; 및 상기 포트베드 각각이 상기 경로를 따라 순차적으로 이동하도록 하는 포트이송부;를 포함하도록 한 식물포트 이송장치를 가지는 아쿠아포닉스 및 수경 재배 시스템에 관한 것이다.본 발명에 따르면, 아쿠아포닉스 및 수경재배에서 식물포트가 장착되는 포트베드가 재배위치로부터 수확위치까지 손쉽게 이동시킬 수 있도록 함으로써, 수확에 소요되는 노력과 인원을 줄여서 인건비 절감 등을 통한 경제적인 재배가 가능하도록 하는 효과를 가진다. claims: 아쿠아포닉스 또는 수경재배를 위한 저수부가 마련되는 수조;상기 수조 상에서 링형태의 경로를 이동 가능하도록 다수로 배치되고, 식물포트가 상기 저수부의 물이나 양액에 잠기도록 끼워지기 위한 끼움홀이 적어도 하나 이상 형성되는 포트베드; 및상기 포트베드 각각이 상기 경로를 따라 순차적으로 이동하도록 하는 포트이송부;를 포함하는, 식물포트 이송장치를 가지는 아쿠아포닉스 및 수경 재배 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1130/1150 Row 1130: application_number: 1020210102742, combined_string: invention_title: LED를 이용한 새싹삼의 재배 또는 사포닌 함량 증진 방법 abstract: 본 발명은 LED를 이용한 새싹삼의 재배 또는 사포닌 함량 증진 방법에 관한 것이다. 구체적으로, 본 발명에 따른 새싹삼 재배 방법은 새싹삼의 지상부 및 지하부의 생체중 및 엽면적, 지상부의 길이 증가, 지상부 및 지하부의 건물중 증가, 및 엽록소 함량 증가를 촉진할뿐만 아니라, 새싹삼에 포함되는 사포닌 함량을 유의적으로 증가시키므로, 새싹삼을 재배하거나 새싹삼에 포함된 사포닌의 함량을 증진시키는데 유용하게 사용될 수 있다. claims: 광원으로 근적외선을 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 배양방법.광원으로 근적외선을 조사하여 새싹삼을 배양하는 단계를 포함하는 LED를 이용한 새싹삼의 사포닌 함량 증진방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1131/1150 Row 1131: application_number: 1020210077846, combined_string: invention_title: 새싹 재배 장치 abstract: 본 발명에 따르는 새싹 재배 장치는 물 분사를 위한 노즐이 회전하여 물이 고르게 분사되고, 온도 조절이 신속하게 이루어지며, 약제와 혼합된 물의 펌핑 과정에서 공기가 흡입되지 않아 새싹으로 약제가 원활하게 분사되며, 발아시와 성장시 등 재배 기간을 분할하여, 각 분할된 회수에 대하여 온도를 설정하여 제어할 수 있으므로, 발아율이 높고, 생육이 빠르며, 발아되지 않아 폐기되는 비율을 낮추는 새싹 재배 장치에 관한 것이다. claims: 내부에 전방으로 개구된 재배공간이 형성된 재배기본체(110)와, 상기 재배기본체(110)의 전방에 구비되어 재배공간을 개폐하는 도어(120)와, 상기 재배기본체(110)의 바닥(111) 상부에 구비된 적치부(130)와, 상기 적치부(130)로부터 상향 이격되어 재배공간의 상부에 구비되어 물이 분사되는 분사부(140)와, 일측은 혼합부(160)로 연결되고 타측은 상기 분사부(140)로 연결되며 모터(155)에 의하여 구동되는 공급펌프(153)가 설치된 공급관(150)과, 약제관밸브(173)가 설치된 약제관(171)으로 혼합부(160)에 연결된 하나 이상의 약제통(170)과, 일측이 상기 혼합부(160)로 연결되며 모터(183)에 의하여 구동되는 직수펌프(181)가 설치된 직수관(180)과, 상기 적치부(130)의 하부로 재배기본체(110)에 연결되며 모터에 의하여 구동되는 냉수펌프가 설치되어 냉수가 공급되는 냉수관(191)과, 상기 적치부(130)의 하부로 재배기본체(110)에 연결되며 모터에 의하여 구동되는 온수펌프가 설치되어 온수가 공급되는 온수관(193)과, 일측이 적치부(130)의 하부로 재배기본체(110)에 연결되며 모터에 의하여 구동되는 배수펌프(1951)가 설치되어 바닥(111) 상에 수용된 물이 배출되는 배수관(195)과, 상기 재배기본체(110)에 설치되어 바닥(111) 상에 수용된 물의 온도가 측정되는 수온센서(103)와, 상기 재배기본체(110)에 설치된 수위센서(101)와, 사용자의 명령이 입력되는 입력부와, 정보가 표시되는 디스플레이부와, 운용프로그램이 저장되는 저장부와, 제어부를 포함하며;상기 입력부와, 디스플레이부와, 저장부와, 공급펌프를 구동하는 모터와, 직수펌프를 구동하는 모터와, 냉수펌프를 구동하는 모터와, 온수펌프를 구동하는 모터와, 배수펌프를 구동하는 모터와, 약제관밸브(173)와, 수온센서(103)와, 수위센서(101)는 제어부에 연결되며;재배기간이 복수 회수로 분할되고 각 회수에서의 재배온도가 제어되어 재배되며;상기 입력부를 통하여 분할된 전체회수가 입력되고, 분할된 각 회수가 디스플레이부에 표시되며, 디스플레이부에 표시된 각 회수에 대한 시간과 재배온도가 입력되어 저장부에 저장되며; 입력부를 통하여 재배 시작 명령이 입력되면, 입력된 각 회수의 시간 및 재배온도 정보와, 수온센서(103)에서 센싱된 재배온도 정보와, 수위센서에서 센싱된 수위 정보가 제어부로 전송되고;냉수펌프를 구동하는 모터와, 온수펌프를 구동하는 모터와, 배수펌프를 구동하는 모터의 구동이 제어부로부터의 제어 명령에 의하여 제어됨으로써 각 회수의 재배온도가 제어되어 재배되며;회수가 선택되고 선택된 회수의 순환기동시간과 순환기대기시간이 입력부를 통하여 입력되어 저장부에 저장되며;제어부로 전송된 상기 순환기동시간과 순환기대기시간 정보에 의하여 제어부로부터의 제어 명령에 의하여 순환대기시간 경과 후 순환기동시간 동안 공급펌프를 구동하는 모터 구동이 제어되어, 혼합부(160)에 수용된 물이 공급관(150)과 분사부(140)를 통하여 재배공간으로 분사되는 것을 특징으로 하는 새싹 재배 장치(100)., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1132/1150 Row 1132: application_number: 1020210070645, combined_string: invention_title: 스마트 팜 방식의 수경재배장치 abstract: 본 발명은 스마트 팜 방식의 수경재배장치로서, 내측에 배양액이 채워질 수 있는 일정한 공간이 형성되어 있는 외측재배베드; 상기 외측재배베드의 내측에 위치되는 내측재배베드; 상기 외측재배베드의 상부에 식재부가 관통되도록 형성된 외측관통공; 및 상기 내측재배베드에 상기 외측관통공을 관통한 상기 식재부가 관통되도록 형성된 내측관통공을 포함하며, 상기 내측재배베드가 상기 외측재배베드의 내측에서 상하이동이 가능하도록 구성된 수경재배장치에 관한 것이다. claims: 내측에 배양액이 채워질 수 있는 일정한 공간이 형성되어 있는 외측재배베드(100); 상기 외측재배베드(100)의 내측에 위치되는 내측재배베드(200);상기 외측재배베드(100)의 상부에 식재부(500)가 관통되도록 형성된 외측관통공(120); 및상기 내측재배베드(200)에 상기 외측관통공(120)을 관통한 상기 식재부(500)가 관통되도록 형성된 내측관통공(220)을 포함하며,상기 내측재배베드(200)가 상기 외측재배베드(100)의 내측에서 상하이동이 가능하도록 구성되며,상기 내측재배베드(200)는 수평 방향으로 형성된 수평식재부지지판(210); 및 상기 수평식재부지지판(210)의 양단에 수직 방향으로 형성된 배양액배수조절판(240)을 포함하며,상기 외측재배베드(100)는 상기 외측재배베드(100)의 내주면 하부에 상기 외측재배베드(100)의 내주면을 따라 홈 형태로 형성되되, 상기 배양액배수조절판(240)의 일단이 삽입되어 장착되도록 형성된 조절판장착홈(150)을 포함하며,상기 수평식재부지지판(210)의 양단에 형성된 배양액배수조절판(240) 각각이 이에 대응하는 각각의 상기 조절판장착홈(150)에 장착됨에 따라, 상기 배양액배수조절판(240)의 사이에서 형성된 상기 외측재배베드(100)의 내측 공간에 일정한 수위로 배양액이 채워진 상태로 유지되며,상기 내측관통공(220)을 관통한 상기 식재부(500)의 하부가 상기 외측재배베드(100)의 내측 공간에 일정한 수위로 채워진 배양액에 잠긴 상태로 위치되며,상기 외측재배베드(100)의 외측면 상에 위치되는 서보모터(252);상기 서보모터(252)에 결합된 상태에서 상기 외측재배베드(100)의 외측에서 내측으로 관통되는 볼스크류(254); 및상기 볼스크류(254)에 장착되어 상기 볼스크류(254)의 회전에 따라 상하이동되는 너트(256)를 더 포함하며,상기 너트(256)가 상기 배양액배수조절판(240)에 결합된 상태에서, 상기 볼스크류(254)가 회전됨에 따라 상기 내측재배베드(200)가 상하이동되며, 상기 볼스크류(254)의 회전으로 상기 배양액배수조절판(240)이 위로 이동됨에 따라, 상기 배양액배수조절판(240)의 일단이 상기 조절판장착홈(150)에서 벗어나는 경우, 상기 외측재배베드(100)의 내측 공간에 일정한 수위로 채워진 배양액이 외부로 배수되는 수경재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1133/1150 Row 1133: application_number: 1020210056152, combined_string: invention_title: 넝쿨작물용 유인 재배장치 abstract: 본 발명은 넝쿨작물용 유인 재배장치에 관한 것으로, 특히 넝쿨작물을 유인줄로 유인 재배하는 과정에서 넝쿨작물의 성장속도에 따라 권취용 드럼에 감긴 유인줄을 하부로 잡아당겨 늘어뜨리는 작업을 매우 용이하게 함은 물론 넝쿨작물용 유인 재배장치의 전체적인 구조를 간소화하여 제조원가를 대폭 절감하는 신개념의 기술에 관한 것이다.종래에 개시된 넝쿨작물용 유인 재배장치는 제조시 초기비용이 많이 들고, 추가부품인 고가의 탄성스프링이 소요되어 조립 공정이 복잡함은 물론 제조원가가 상승하며, 권취용 드럼에 감겨진 유인줄을 풀어 하방으로 늘어뜨리는 작업이 어렵고 불편한 문제점이 야기된다.본 발명은 이러한 문제점을 일소하기 위한 방안으로 권취용 드럼을 회전 가능하게 지지하는 드럼 지지대의 일 측판 내면에 상하로 텐션 가능하게 일체로 돌출 형성된 텐션 락이 상기 권취용 드럼의 락킹을 유지하면서 회전을 방지함과 아울러 상기 텐션 락의 선택적인 누름 조작에 따라 권취용 드럼의 락킹을 일시로 해제하면서 자유롭게 회전할 수 있도록 하는 기술을 강구함을 특징으로 한다. claims: 상, 하판(11)(12)의 양측에 한 쌍의 측판(13)(13a)이 연결됨과 아울러 전후가 개방되고, 상판(11)의 상단에 걸고리(14)가 형성되며, 일 측판(13)(13a)의 하부 내면에 상하로 탄성 가능한 텐션 락(15)이 일체로 돌출 형성된 드럼 지지대(10)와;상기 양 측판(13)(13a)에 형성된 회전축 입출로(16)의 하단에 회전 가능하게 끼움 설치되고, 일측 드럼 플랜지(21)에 돌출 형성된 걸림돌기(24)가 상기 텐션 락(15)에 걸려 회전 정지된 상태를 유지하는 권취용 드럼(20)으로 이루어진 것을 특징으로 하는 넝쿨작물용 유인 재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1134/1150 Row 1134: application_number: 1020210033791, combined_string: invention_title: 튜브형 식물재배 시스템 abstract: 본 발명은 구조가 개선된 튜브형 식물재배 시스템에 관한 것으로써, 유연한 소재로 이루어지고, 일측 또는 다측이 구부려져 형성되는 굴곡부에서 연장된 끝부분에 소정의 간극을 유지하며 대칭되는 길이방향 양쪽 내측 표면이 개방되는 밀착부를 구비하고 그 내부에 공간부가 구비되는 튜브부; 상기 밀착부 내측 양족 표면이 포개지며 상호 탈착되는 벨크로 테이프;를 포함함으로써, 상기 공간부에 식물의 뿌리가 내설되고, 식물의 줄기부분은 밀착부 내측 양쪽 표면의 상기 벨크로테이프에 의해 고정되며, 식물을 재배하는 것을 특징으로 하는 튜브형 식물재배 시스템을 제공한다. claims: 유연한 소재로 이루어지고, 일측 또는 다측이 구부려져 형성되는 굴곡부에서 연장된 끝부분에 소정의 간극을 유지하며 대칭되는 길이방향 양쪽 내측 표면이 개방되는 밀착부를 구비하고 그 내부에 공간부가 구비되는 튜브부;상기 밀착부 내측 양족 표면이 포개지며 상호 탈착되는 벨크로테이프;를 포함함으로써,상기 공간부에 식물의 뿌리가 내설되고, 식물의 줄기부분은 밀착부 내측 양쪽 표면의 상기 벨크로테이프에 의해 고정되며, 식물을 재배하는 것을 특징으로 하는 튜브형 식물재배 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1135/1150 Row 1135: application_number: 1020210028625, combined_string: invention_title: 통신 인터페이스와 인공 지능에 기반한 개인용 식물 재배 장치 및 시스템 abstract: 원격 제어가 가능한 개인용 식물 재배 시스템이 개시된다. 개인용 식물 재배 시스템은 식물을 수경 재배하기 위한 식물 재배 장치, 상기 식물 재배 장치와 유선 또는 통신 인터페이스에 기반하여 연결되는 서버, 및 소정의 어플리케이션을 통해 상기 식물 재배 장치와 연결되고 상기 식물 재배 장치를 제어하기 위한 사용자의 개인 단말기를 포함할 수 있다. 상기 식물 재배 장치는, 상기 식물에 공급되는 양액을 저장하기 위한 수조, 상기 식물 재배 장치의 외부의 공기를 흡입하여 상기 양액에 투입하기 위한 에어 펌프, 재배 환경과 관련된 정보들을 감지하기 위한 센서부, 상기 식물을 촬영하여 영상 데이터를 획득하기 위한 카메라, 상기 재배 환경과 관련된 변수를 조절하기 위한 액추에이터, 및 상기 식물 재배 장치의 동작을 제어하고 유선 또는 무선 통신 인터페이스가 포함된 적어도 하나의 프로세서를 포함할 수 있다. claims: 식물을 수경 재배하기 위한 식물 재배 장치;상기 식물 재배 장치와 유선 또는 통신 인터페이스에 기반하여 연결되는 서버; 및소정의 어플리케이션을 통해 상기 식물 재배 장치와 연결되고 상기 식물 재배 장치를 제어하기 위한 사용자의 개인 단말기를 포함하고,상기 식물 재배 장치는, 상기 식물에 공급되는 양액을 저장하기 위한 수조; 상기 식물 재배 장치의 외부의 공기를 흡입하여 에어 라인을 통해 상기 양액에 투입하기 위한 에어 펌프; 재배 환경과 관련된 정보들을 감지하기 위한 센서부; 상기 식물을 촬영하여 영상 데이터를 획득하기 위한 카메라; 상기 재배 환경과 관련된 변수를 조절하기 위한 액추에이터; 및 상기 식물 재배 장치의 동작을 제어하고 유선 또는 무선 통신 인터페이스가 포함된 적어도 하나의 프로세서를 포함하고,상기 에어 펌프를 통해 흡입되어 상기 에어 라인을 통해 상기 양액에 투입된 공기 중의 미세 먼지는 상기 수조 내부에 침전되거나 상기 식물의 뿌리로 흡수되고,상기 센서부는 온도 센서, 습도 센서, 광 센서, 및 EC(Electric Conductivity) 센서를 포함하고,상기 액추에이터는, 광을 조절하기 위한 LED 광원, 양액의 공급을 조절하기 위한 관수 펌프, 온도를 조절하기 위한 팬이나 펠티어를 포함하고,상기 재배 환경과 관련된 정보, 상기 액추에이터의 동작 정보, 및 상기 영상 데이터 각각은 기준 시간마다 획득되어 상기 서버로 전송되고,상기 액추에이터는 상기 재배 환경과 관련된 정보, 상기 액추에이터의 동작 정보, 및 상기 영상 데이터 중 적어도 하나에 기반하여 생성된 제어 신호 하에 동작하거나 상기 개인 단말기로부터 수신되는 제어 신호 하에 동작하고,상기 사용자는 상기 재배 환경과 관련된 정보, 상기 액추에이터의 동작 정보, 및 상기 영상 데이터를 상기 어플리케이션을 통해 확인할 수 있고,상기 식물의 정식 후 경과일, EC정보, 온도 정보, 조도 정보, 습도 정보, 및 상기 관수 펌프의 동작 여부 정보를 포함하는 6개 타입의 입력 데이터들 각각은 상기 식물의 정식 후에 소정의 시간 구간마다 획득되고,상기 서버는 상기 식물의 정식 후 경과일 동안 획득된 상기 6개 타입의 입력 데이터들을 소정의 단위기간 동안 누적시켜 예측 모델에 입력하고, 상기 예측 모델은 상기 식물의 키 또는 잎면적 지수 정보를 출력하고,상기 예측 모델은, 복수의 식물 재배 장치들로부터 획득된 상기 6개 타입의 입력 데이터들을 입력으로 적용하고 상기 카메라에 의해 획득된 영상 데이터로부터 획득되는 상기 식물의 키 또는 잎면적 지수를 출력으로 적용하는 기계 학습에 기반하여 생성되고,상기 복수의 식물 재배 장치들은 상기 식물 재배 장치과 다른 식물 재배 장치를 포함하는 개인용 식물 재배 시스템., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1136/1150 Row 1136: application_number: 1020210026990, combined_string: invention_title: 식물 재배장치 abstract: 본 발명에 따른 식물 재배장치는 여러 개를 온실의 폭 방향으로 병렬로 배치하여 식물을 재배할 수 있으면서도 재배식물이 햇빛이나 외부조명을 골고루 받을 수 있도록 할 수 있다. 상기 식물 재배장치는 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임, 한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체 및 한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고, 복수의 상기 식물재배용기에 양액을 공급하기 위한 양액공급기를 포함하고, 상기 양액공급기는, 양액 공급용기, 복수의 상기 식물재배용기에 일단이 각각 연결된 복수의 호스 및 복수의 상기 호스의 타단에 연결되어 상기 양액 공급용기의 양액을 복수의 상기 호스를 통해 상기 식물재배용기로 공급하며 상기 순환체의 회전에 따라 회전되는 회전 양액공급관을 포함하는 구성을 한다. claims: 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임;한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체; 및한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고,복수의 상기 식물재배용기에 양액을 공급하기 위한 양액공급기를 포함하고,상기 양액공급기는,양액 공급용기;복수의 상기 식물재배용기에 일단이 각각 연결된 복수의 호스; 및복수의 상기 호스의 타단에 연결되어 상기 양액 공급용기의 양액을 복수의 상기 호스를 통해 상기 식물재배용기로 공급하며 상기 순환체의 회전에 따라 회전되는 회전 양액공급관을 포함하는 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1137/1150 Row 1137: application_number: 1020210026999, combined_string: invention_title: 식물 재배장치 abstract: 본 발명에 따른 식물 재배장치는 여러 개를 온실의 폭 방향으로 병렬로 배치하여 식물을 재배할 수 있으면서도 재배식물이 햇빛이나 외부조명을 골고루 받을 수 있도록 할 수 있다. 상기 식물 재배장치는 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임, 한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체 및 한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고, 상기 순환체를 따라 순환하는 복수의 상기 행거바의 내부에 복수의 상기 식물재배용기에서 재배되는 식물을 향해 빛을 쬐기 위한 조명기구가 설치되는 것을 포함하는 구성을 한다. claims: 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임;한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체; 및한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고,상기 순환체를 따라 순환하는 복수의 상기 행거바의 내부에 복수의 상기 식물재배용기에서 재배되는 식물을 향해 빛을 쬐기 위한 조명기구가 설치되는 것을 포함하는 것을 특징으로 하는 식물재배장치., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1138/1150 Row 1138: application_number: 1020210027000, combined_string: invention_title: 식물 재배장치 abstract: 본 발명에 따른 식물 재배장치는 여러 개를 온실의 폭 방향으로 병렬로 배치하여 식물을 재배할 수 있으면서도 재배식물이 햇빛이나 외부조명을 골고루 받을 수 있도록 할 수 있다. 상기 식물 재배장치는 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임, 한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체 및 한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고, 상기 행거바에 간격을 두고 베어링이 설치되고, 상기 식물재배용기는 상기 베어링에 걸려있는 줄을 통해 상기 행거바에 매달려 있는 것을 포함하는 구성을 한다. claims: 간격을 두고 평행하게 배치되고 순환경로를 각각 제공하는 적어도 한 쌍의 순환지지구를 가지는 프레임;한 쌍의 상기 순환지지구에 순환 가능케 각각 설치된 적어도 한 쌍의 순환체; 및한 쌍의 상기 순환체에 연결되어 설치되고 상기 순환체의 회전 방향으로 간격을 두고 배치되어 식물재배용기를 매달 수 있도록 해주는 복수의 행거바를 포함하고,상기 행거바에 간격을 두고 베어링이 설치되고, 상기 식물재배용기는 상기 베어링에 걸려있는 줄을 통해 상기 행거바에 매달려 있는 것을 포함하는 것을 특징으로 하는 식물 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1139/1150 Row 1139: application_number: 1020210026851, combined_string: invention_title: 농작물용 지주 abstract: 본 발명은 고추, 토마토, 가지와 같은 농작물이 넘어지지 않도록 받치는 지주(支柱)에 관한 것으로 보다 구체적인 것은, 파이프부재로 된 기둥에 결합하여 설치높이를 임의로 조정할 수 있도록 되고, 합성수지로 성형되어 녹슬지 않으며, 지주 사이에 가설되는 지지끈을 쉽게 결속시켜 유지시켜주고, 보조지주를 결합시킬 수 있게 하여 다양하게 활용할 수 있는 편리한 지주가 되게 한 농작물용 지주이다. claims: 금속 또는 합성수지 파이프로 되어 일정길이를 가지는 중심지주(1)와, 중심지주에 상하방향으로 끼워져 위치가 선택되는 지지구(2)와, 지지구(2)를 중심지주(1)에 고정시키는 고정자(3)와, 지지구에 결합되는 보조지주(4)(4a)와, 지지구(2) 및 보조지주(4)(4a) 사이에 설치되는 지지끈(5)으로 이루어지는 농작물용 지주로서, 중심지주(1)는 직경 24mm 되는 아연도강 파이프 또는 합성수지 파이프가 선택되고, 지지구(2)는 합성수지로 성형되어, 중심부에 세로방향으로 중심지주(1)에 끼워지는 중심연결관(20)이 형성되고, 중심연결관(20)은 상단부 직경이 24∼25mm이고, 하단부 직경이 27∼28mm 되는 상협하광형 테이프관체로 형성되며, 중심연결관 양측으로 상단부 폭이 길고, 하단부 폭이 좁아 위가 넓고 하측이 좁은 역사다리꼴의 연결판(21)(22)이 형성되고, 양측 연결판의 좌우측단에는 연결판에 부착되고, 위에서 아래로 경사지며, 중심구멍이 상하로 개방되어 하단 개방부가 중심지주(1) 표면을 향하는 경사연결관(23)(24)이 형성되어 보조지주(4)가 끼워지고, 연결판(21)(22) 상단부와 경사연결관 외주면에는 외측단부에 환상돌출턱(25a)이 형성된 지지끈결속부(25)가 돌출형성되어 지지끈(5)이 결속되며, 연결판(21)(22) 전방에는 관통구멍(26a)(27a)이 횡으로 형성되는 한쌍의 횡연결관(26)(27)을 나란히 형성하여 보조지지대(4a)가 관통되게 끼워지고, 고정자(3)는 합성수지로 성형되는 반분원통체(30)(31)로 형성되어 중심부 직경은 중심지주 외경과 같고, 외경은 위가 좁고 아래가 점차 넓어지는 테이퍼면이 형성되어 중심지주(1)와, 지지구(2)의 중심연결관(20) 사이에 개입되며, 반분원통체(30)(31)의 결합부에 요입홈(30a)(31a)과 돌출편(30b)(31b)이 형성되어 서로 결합하고, 분리할 수 있게 한 구성으로 만든 농작물용 지주., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1140/1150 Row 1140: application_number: 1020200184459, combined_string: invention_title: 수직형 수경재배기 abstract: 본 발명은 수직형 수경재배기에 관한 것으로, 보다 상세하게는 재배포트에 일정한 양의 양액을 지속적으로 공급할 수 있는 수직형 수경재배기에 관한 것이다. 본 발명은 다음과 같은 효과를 발휘한다.즉, 본 발명에 따르면, 재배포트에 일정한 양의 양액을 지속적으로 공급할 수 있기 때문에 식물의 안정적인 생장을 도모할 수 있고, 사용자의 스마트기기(스마트폰, 태블릿 PC 등)와 양방향 통신을 통한 데이터의 송수신이 가능하도록 구성하여 실시간 업데이트가 반영되는 장점이 있다. claims: 사용자의 스마트기기와 양방향 통신이 가능하되, 양액자동제어기(900)의 물 및 양액 상태, 물교체 잔여일자, 양액 추가공급 잔여일자, 물 및 양액의 수위정보, 광조사수단(300) 및 펌프(700)의 동작상태를 포함한 데이터가 스마트기기로 송신되고, 재배된 식물정보, 광 조사시간, 현재 시각을 포함한 데이터가 스마트기기로부터 수신되는 수직형 수경재배기에 있어서,사각 형상의 프레임(100);상기 프레임(100)의 상측에 설치되는 나무 형상의 재배관(200);상기 프레임(100)의 양측에 설치되어, 재배관(200)에 광을 조사하는 광조사수단(300);상기 프레임(100)의 하측에 배치되어, 재배관(200)의 하부관(220)을 통과한 양액(m)이 저장되는 양액탱크(400);상기 양액탱크(400)에 저장된 양액(m)이 재배관(200)의 상부관(210)으로 이동되는 양액이동관(500);상기 광조사수단(300)의 양측에서 재배관(200)을 바라보는 방향으로 형성되어, 광조사수단(300)에서 출력되는 광이 재배관(200) 방향으로 모이도록 유도하는 집광판(600);상기 양액탱크(400) 내부에 형성되되, 양액이동관(500)으로 양액(m)을 펌핑하는 펌프(700);상기 양액탱크(400)에 저장된 양액(m)의 상태를 조절하는 양액자동제어기(900);를 포함하되,상기 재배관(200)은프레임(100)의 상측에 설치되되, 양액이동관(500)으로부터 양액(m)을 공급받는 상부관(210)과,상기 상부관(210)의 하단에 연통되어, 상부관(210)으로부터 양액(m)을 공급받는 하부관(220)을 포함하고,상기 상부관(210)은양액이동관(500)으로부터 양액(m)을 공급받는 제1상부관(211)과,상기 제1상부관(211)에 연통되어, 제1상부관(211)으로부터 양액(m)을 공급받는 제2상부관(212)을 포함하고,상기 제1상부관(211)은제1상부관(211)의 단부에 돌출 형성됨으로써 제2상부관(212)으로 양액(m)이 공급될 때 양액(m)이 두 갈래로 갈라지도록 하여, 제2상부관(212)의 제1유로(212a)와 제2유로(212b)로 양액(m)의 분배를 유도하는 양액분배유도부재(211a)를 포함하고,상기 제2상부관(212)의 내부에는양액이동관(500)으로부터 공급받은 양액(m)이 제1포트삽입관(221a)과 연통되는 지점과 인접한 하부관(220)의 내측벽(A)으로 이동되도록 유도하는 제1유로(212a)와,양액이동관(500)으로부터 공급받은 양액(m)이 제2포트삽입관(221b)과 연통되는 지점과 인접한 하부관(220)의 내측벽(B)으로 이동되도록 유도하는 제2유로(212b)를 포함하고,상기 제1유로(212a)는제2상부관(212)의 내측면을 따라 나선형의 미끄럼틀의 형상으로 형성되되, 제1상부관(211)과 연통되는 지점과 인접한 위치에서 제1포트삽입관(221a)과 연통되는 지점과 인접한 상부관(210)의 내측벽(A)까지 연장 형성되는 것을 특징으로 하고,상기 제2유로(212b)는제2상부관(212)의 내측면을 따라 나선형의 미끄럼틀의 형상으로 형성되되, 제1상부관(211)과 연통되는 지점과 인접한 위치에서 제2포트삽입관(221b)과 연통되는 지점과 인접한 상부관(210)의 내측벽(B)까지 연장 형성되는 것을 특징으로 하고,상기 하부관(220)은하부관(220)의 양측에서 광조사수단(300)을 바라보는 방향으로 연통되고, 식물(1)이 재배되는 재배포트(10)가 설치되는 포트삽입관(221)을 포함하고,상부관(210)으로부터 공급받은 양액(m)을 포트삽입관(221)에 공급하되, 포트삽입관(221)에 공급하고 남은 양액(m)은 양액탱크(400)로 배출되는 것을 특징으로 하고,상기 포트삽입관(221)은하부관(220)의 일측에서 제1광조사수단(310)을 바라보는 방향으로 형성되는 제1포트삽입관(221a)과,하부관(220)의 타측에서 제2광조사수단(320)을 바라보는 방향으로 형성되는 제2포트삽입관(221b)을 포함하고,상기 광조사수단(300)은프레임(100)의 일측에 설치되는 제1광조사수단(310)과,상기 제1광조사수단(310)과 대향되는 프레임(100)의 타측에 설치되는 제2광조사수단(320)을 포함하고,상기 집광판(600)은제1광조사수단(310)의 양측에 형성되는 제1집광판(610)과,제2광조사수단(320)의 양측에 형성되는 제2집광판(620)을 포함하는 것을 특징으로 하는수직형 수경재배기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1141/1150 Row 1141: application_number: 1020200182483, combined_string: invention_title: 유효성분이 강화된 엉겅퀴의 재배방법 abstract: 본 발명은 엉겅퀴를 2년에 걸쳐 재배하면서 엉겅퀴에 함유된 생리활성 물질이 가장 많이 함유되는 시기에 맞추어 부위별로 수확하는 엉겅퀴의 재배방법에 관한 것이다.본 발명의 엉겅퀴 재배방법은 노화잎이 발생되지 않는 양호한 품질의 엉겅퀴 잎을 2년에 걸쳐 여러 번 수확하고 엉겅퀴 꽃에 함유된 유용성분까지 이용할 수 있어서 엉겅퀴의 수확량이 증대되고, 엉겅퀴에 함유된 특정 생리활성 물질이 성분에 따라 부위별로 가장 많이 함유된 시기에 맞추어 수확하므로 엉겅퀴로부터 유효성분을 최대한 생산할 수 있으며, 채취한 씨앗의 발아율이 높다. claims: 엉겅퀴 종자를 파종하여 발아 및 생육시키는 단계;5월 중순~7월 중순에 엉겅퀴 잎을 1차 수확하는 단계;9월 중순~11월 초순에 엉겅퀴 잎을 2차 수확하고 일부 엉겅퀴의 뿌리를 수확하는 단계;이듬해 4월 중순~5월 상순의 2년생 엉겅퀴 꽃이 개화되기 전에 뿌리를 수확하지 않은 엉겅퀴로부터 잎을 3차 수확하는 단계;6월 초순~6월 중순에 측지에서 발생하는 2년생 꽃봉오리를 수확하면서 본줄기의 꽃에 맺힌 종자를 채종하는 단계; 및종자 채종 이후 발생하는 2년생 꽃의 꽃봉오리가 형성되기 시작하는 시점에서 꽃봉오리가 개화하기 직전까지의 엉겅퀴 꽃, 잎 및 줄기를 수확하는 단계;를 포함하는 엉겅퀴의 재배방법., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1142/1150 Row 1142: application_number: 1020200156417, combined_string: invention_title: 모듈형 식물재배장치 및 식물재배장치의 화분모듈 abstract: 본 발명은 화분모듈을 수직으로 직립하게 쌓아 올림으로써 한정된 공간에서 일체화된 디자인의 구현할 수 있는 다층 구조의 식물재배장치에 관한 것으로, 수조를 포함하는 베이스부와, 베이스부의 상단에 장착되는 설치대와, 상기 설치대에 다층 구조로 적층이 이루어지는 화분모듈을 포함하고, 상기 화분모듈에 식물이 식재된 상태에서 수조로부터 공급된 물 또는 양액이 적층된 화분모듈의 상층부로부터 하층부로 순차적으로 경유하면서 양분 공급이 이루어지게 되는 다층 구조의 모듈형 식물재배장치에 있어서, 상기 화분모듈은 모듈본체에 복수의 식재포트를 장착하되, 식재포트를모듈본체의 둘레를 따라서 방사상으로 배열하고, 상기 화분모듈이 다단으로 적층되는 구조를 가지면서 수직으로 적층된 상태를 유지하도록 하기 위하여 모듈본체의 중앙부가 상부로 돌출된 상태에서 그 둘레를 따라서 복수의 식재포트가 외주연측을 향하여 하부측으로 기울어지게 배열되어 화분모듈이 수직으로 다층 배열이 이루어지면서 협소한 공간에서 일체화된 디자인으로 공간활용을 할 수 있도록 함은 물론, 상기 모듈본체는 상,하단에는 각각 연결부와 하향돌출부가 서로 대응하게 형성하여 모듈본체를 수직으로 적층 조립이 가능하도록 하고, 연결부에는 공급로를 하향돌출부에는 층간배수홀을 각각 형성하되, 식재포트에는 공급로 및 층간배수홀과 연통하게 유입공 및 배수구를 각각 형성하여 화분모듈이 다층 구조로 적층된 상태에서 상층부로부터 하층부측으로 물 또는 양액이 순차적으로 경유하면서 양분 공급이 이루어지도록 함으로써 화분모듈간 상호 조립구조로 순차적으로 간단하게 조립 및 분리가 가능하고, 자중에 의하여 간단하게 조립이 가능하며, 수직공간으로 화분을 적층구성하여 설치장소의 제약없이 다양한 공간연출이 가능하도록 한 것이다. claims: 수조(120)를 포함하는 베이스부(100)와,베이스부(100)의 상단에 장착되는 설치대(200)와,상기 설치대에 다층 구조로 적층이 이루어지는 화분모듈(300)을 포함하고, 상기 화분모듈(300)에 식물이 식재된 상태에서 수조(120)로부터 공급된 물 또는 양액이 적층된 화분모듈의 상층부로부터 하층부로 순차적으로 경유하면서 양분 공급이 이루어지게 되는 다층 구조의 모듈형 식물재배장치에 있어서,상기 화분모듈(300)은 모듈본체(320)에 복수의 식재포트(340)가 장착되되, 식재포트(340)는 모듈본체의 둘레를 따라서 방사상으로 배열되고,상기 화분모듈(300)이 다단으로 적층되는 구조를 가지면서 수직으로 적층된 상태를 유지하기 위하여 모듈본체(320)의 중앙부가 상부로 돌출된 상태에서 그 둘레를 따라서 복수의 식재포트(340)가 외주연측을 향하여 하부측으로 기울어지게 배열되어 수직공간으로 화분모듈의 배열이 이루어지고,상기 화분모듈(300)은 모듈본체(320)의 상,하단에 각각 연결부(322)와 하향돌출부(324)가 서로 대응하게 형성되어 화분모듈(300)의 적층 조립이 이루어지되, 상기 연결부(322)에는 공급로(323)가 상기 하향돌출부(324)에는 층간배수홀(305)이 각각 형성되고,상기 식재포트(340)는 공급로(323) 및 층간배수홀(325)과 연통하게 유입공(343) 및 배수구(345)가 형성되어 화분모듈(300)이 다층 구조로 적층된 상태에서 상층부로부터 하층부측으로 물 또는 양액이 순차적으로 경유하면서 양분 공급이 이루어지며,상기 화분모듈(300)은 모듈본체(320)에 형성된 하향돌출부(324)가 모듈본체(320)의 연결부(322)에 조립될 때 모듈본체(320)의 하부가 하향 경사지게 형성되어 하층부의 모듈본체(320)의 상단에 안착되어 조립부속이 없이도 단순 적층 구조로 조립이 가능하면서 조립부위가 외부로 노출되지 않고 식재포트(340)만 노출되어 협소한 공간에서 일체화된 디자인으로 공간활용을 할 수 있게 되는 모듈형 식물재배장치.수직으로 쌓아서 다층 구조로 식물의 식재가 가능하도록 하는 모듈본체(320)와, 모듈본체의 외주연을 따라서 식물을 생육하기 위한 복수의 식재포트(340)가 구비되고,상기 모듈본체(320)의 상,하단에는 각각 연결부(322)와 하향돌출부(324)가 서로 대응하게 형성되어 모듈본체(320)를 수직으로 적층 조립이 가능하게 되며, 상기 연결부(322)에는 공급로(323)가 상기 하향돌출부(324)에는 층간배수홀(325)이 각각 형성되되, 식재포트(340)에는 상기 공급로(323) 및 층간배수홀(325)과 연통하게 유입공(343) 및 배수구(345)가 각각 형성되어 화분모듈(300)이 다층 구조로 적층된 상태에서 상층부로부터 하층부측으로 물 또는 양액이 순차적으로 경유하면서 양분 공급이 이루어지지고,상기 모듈본체(320)는 중앙부가 상부로 돌출된 상태에서 그 둘레를 따라서 복수의 식재포트(340)가 외주연측을 향하여 하부측으로 기울어지게 배열되어 수직으로 화분모듈의 배열이 이루어지면서 협소한 공간에서 일체화된 디자인 공간연출이 가능하게 되며, 상기 화분모듈(300)은 모듈본체(320)를 구성하는 상부체(320a)와 하부체(320b) 및 모듈본체(320)에 탈착 가능하게 구비되는 식재포트(340)로 3단 구조로 조립이 이루어지고, 상기 상,하부체(320a,320b)는 돌출부(302)와 내입부(304)를 구성하도록 덮개부(321a)와 집수정(321b)이 형성되되 덮개부(321a)에 식재포트(340)의 끼움위치를 설정하는 안착대(327)가 형성되어 안착대(327)가 집수정(321b)에 삽입되어 식재포트(340)의 정위치 조립이 가능하게 됨을 특징으로 하는 식물재배장치의 화분모듈., Ltext: 농업, prediction: 농업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1143/1150 Row 1143: application_number: 1020200156653, combined_string: invention_title: 분무식 수경 재배장치 abstract: 본 발명은 본체; 식재된 육묘 뿌리가 아래로 통과하는 다수개의 뿌리통과공이 형성된 재배대가 상기 본체에 상하로 이격되게 다단 배치된 트레이부; 상기 본체에 설치되어 다단 배치된 상기 재배대의 하부에 각각 배치되며 상기 재배대에 식재된 육묘 뿌리로 양액을 분무하는 분무노즐을 포함하는 복수개의 양액분무부; 상기 본체에 복수개가 이격되게 설치되며 상기 재배대로 양액을 분무하는 상기 분무노즐을 포함하는 양액분무부를 지지하는 양액분무부 지지대; 상기 본체에 상하로 다단 배치된 상기 재배대의 상부에 각각 배치되어 상기 재배대에 식재된 육묘로 하나 이상의 파장을 갖는 광을 조사하는 조명장치를 포하하는 복수개의 조명장치부; 및 상기 재배대의 하부에 배치되는 각각의 양액분무부의 하부에 각각 설치되며, 상기 양액분무부로부터 분무된 양액을 회수하여 일측에서 타측으로 이동시키는 복수개의 방수패드를 포함하는 양액회수부를 포함하되, 상기 복수개의 양액분무부 지지대는 상기 본체에 상기 재배대와 상기 방수패드의 사이에 위치하며, 상기 양액분무부 지지대는 막대형상을 가지는 지지몸체와, 상기 지지몸체에 구비되며 상기 지지몸체를 상기 본체에 장착하는 장착고리와, 상기 지지몸체의 하부에 구비되며 상기 분무노즐로 양액을 공급하며 이격되게 위치하는 복수개의 분무노즐을 연결하는 연결호스를 지지하는 지지고리를 포함하고, 상기 장착고리는 상기 지지몸체의 양단에서 외측으로 돌출되게 구비되어 상기 본체에 걸림장착되며, 상기 지지고리는 상기 지지몸체의 하부로 복수개가 상기 지지몸체의 길이방향으로 이격되게 구비되고, 상기 방수패드가 사다리꼴 형상을 가짐으로써 상기 방수패드가 상기 본체에 설치 시 상기 방수패드의 윗변과 아랫변의 높이가 달라져 윗변 보다 아래쪽에 위치하는 아랫변 측으로 양액이 이동되는 것을 특징으로 하는 분무식 수경 재배장치를 제공한다.따라서, 재배대의 하부에 설치되는 분무노즐 및 분무노즐을 연결하는 연결호스를 본체의 가로프레임에 장착되는 양액분무부 지지대에 안착시킴으로써 분무노즐 및 연결호스를 재배대의 하부에 손쉽게 고정할 수 있다. claims: 본체;식재된 육묘 뿌리가 아래로 통과하는 다수개의 뿌리통과공이 형성된 재배대가 상기 본체에 상하로 이격되게 다단 배치된 트레이부;상기 본체에 설치되어 다단 배치된 상기 재배대의 하부에 각각 배치되며 상기 재배대에 식재된 육묘 뿌리로 양액을 분무하는 분무노즐을 포함하는 복수개의 양액분무부;상기 본체에 복수개가 이격되게 설치되며 상기 재배대로 양액을 분무하는 상기 분무노즐을 포함하는 양액분무부를 지지하는 양액분무부 지지대;상기 본체에 상하로 다단 배치된 상기 재배대의 상부에 각각 배치되어 상기 재배대에 식재된 육묘로 하나 이상의 파장을 갖는 광을 조사하는 조명장치를 포하하는 복수개의 조명장치부; 및상기 재배대의 하부에 배치되는 각각의 양액분무부의 하부에 각각 설치되며, 상기 양액분무부로부터 분무된 양액을 회수하여 일측에서 타측으로 이동시키는 복수개의 방수패드를 포함하는 양액회수부를 포함하되,상기 복수개의 양액분무부 지지대는 상기 본체에 상기 재배대와 상기 방수패드의 사이에 위치하며,상기 양액분무부 지지대는,막대형상을 가지는 지지몸체와,상기 지지몸체에 구비되며 상기 지지몸체를 상기 본체에 장착하는 장착고리와,상기 지지몸체의 하부에 구비되며 상기 분무노즐로 양액을 공급하며 이격되게 위치하는 복수개의 분무노즐을 연결하는 연결호스를 지지하는 지지고리를 포함하고,상기 장착고리는 상기 지지몸체의 양단에서 외측으로 돌출되게 구비되어 상기 본체에 걸림장착되며,상기 지지고리는 상기 지지몸체의 하부로 복수개가 상기 지지몸체의 길이방향으로 이격되게 구비되고,상기 방수패드가 사다리꼴 형상을 가짐으로써 상기 방수패드가 상기 본체에 설치 시 상기 방수패드의 윗변과 아랫변의 높이가 달라져 윗변 보다 아래쪽에 위치하는 아랫변 측으로 양액이 이동되는 것을 특징으로 하는 분무식 수경 재배장치., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1144/1150 Row 1144: application_number: 1020200156867, combined_string: invention_title: 버섯 재배용 배지의 스마트 수분공급장치 abstract: 본 발명은 버섯 재배용 배지의 스마트 수분공급장치에 관한 것으로 내부에 소정공간이 형성되며, 상부에는 하나 이상의 버섯배지를 지지하도록 형성된 배지트레이가 안착될 수 있도록 형성된 몸체유닛과 상기 몸체유닛의 상부에 상하로 승강 가능하게 형성되는 이송프레임을 포함하는 이송유닛과 상기 이송프레임에 장착되어 상기 이송프레임과 함께 승하강 되며, 버섯배지에 수분을 공급는 침봉을 포함하는 침봉유닛과 상기 침봉을 통해서 버섯배지에 수분이 공급되도록 상기 침봉유닛으로 물을 공급하는 물공급유닛을 구비하는 것이다.본 발명에 따르면 재배사 전체의 배지에 정량의 물 공급시간을 획기적으로 감축하게 되고 각각의 배지를 일일이 옮겨가며 침봉하지 않아 노동력을 대폭 절감할 수 있으며, 수확중에도 배지에 필요한 수분을 설치된 시스템을 통해 수시로 공급할 수 있어 고품질의 버섯을 생산하며 동시에 발아시기와 수확시기를 비교적 안정적으로 컨트롤 할 수 있게 된다. claims: 버섯배지를 지지하도록 형성된 배지트레이가 안착되는 안착부와, 상기 안착부에 마련되어서 상기 버섯배지에 유입되는 물의 양을 측정하도록 형성된 무게센서를 포함하는 몸체유닛과;상기 몸체유닛의 상부에 상하로 승강 가능하게 형성되는 이송프레임의 하부에 연결되어 승하강하고, 급수를 위한 침봉이 상기 버섯배지에서 삽입 또는 이탈시 상기 버섯배지가 움직이지 않도록 상기 버섯배지의 상부를 가압하는 배지고정판을 포함하는 이송유닛과;상기 이송프레임에 장착되어 상기 이송프레임과 함께 승하강 되며, 버섯배지에 수분을 공급하는 상기 침봉을 포함하는 침봉유닛과;상기 침봉을 통해서 상기 버섯배지에 수분이 공급되도록 상기 침봉유닛으로 물을 공급하는 물공급유닛과;상기 침봉을 세척하도록 상기 배지고정판에 형성되어, 상기 침봉을 향하여 세척수를 분사하는 세척부를 구비하고;상기 배지고정판은 상기 침봉이 상기 배지고정판의 하부에 위치하는 상기 버섯배지로 삽입 가능하도록 상기 침봉이 관통할 수 있는 관통홀이 형성되어 있고, 상기 배지고정판은 상기 이송프레임의 하부에서 하방으로 연장되는 스프링로드를 따라 승강이 이루어질 수 있도록 형성되고, 상기 스프링로드를 감싸며 상단과 하단이 각각 상기 이송프레임과 상기 배지고정판에 지지되는 스프링에 의해서 상기 이송프레임으로부터 멀어지는 방향으로 탄성지지 되고,상기 세척부는상기 배지고정판에 형성되되, 상기 배지고정판의 내부에서 세척수가 이동할 수 있게 형성된 세척수유로와,상기 관통홀의 내주면에 형성되어 상기 관통홀을 통해 승강 또는 하강하는 상기 침봉의 외주면을 향해 세척수를 분사하는 세척노즐을 포함하고,상기 침봉은 상기 물공급유닛으로부터 물이 공급될 수 있게 연결되어 상기 이송프레임에 설치되고, 단부가 상기 버섯배지에 용이하게 삽입될 수 있게 첨예하게 형성되는 것을 특징으로 하는,버섯 재배용 배지의 스마트 수분공급장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1145/1150 Row 1145: application_number: 1020200133095, combined_string: invention_title: 수경재배기 abstract: 본 발명은 수경재배기에 관한 것으로, 보다 상세하게는 양액의 수위를 실시간으로 모니터링할 수 있을 뿐만 아니라, 식물과 광조사부 사이의 거리를 일정하게 유지시킬 수 있는 수경재배기에 관한 것이다.본 발명에 따르면, 양액의 수위를 실시간으로 모니터링할 수 있기 때문에, 사용자의 편의성이 도모되고, 식물과 광조사부 사이의 거리가 일정하게 유지되기 때문에, 광조사부에서 발생되는 열로 인한 식물의 악영향을 미연에 방지할 수 있고, 사용자의 스마트기기(스마트폰, 태블릿 PC 등)와 양방향 통신을 통한 데이터의 송수신이 가능하도록 구성하여 실시간 업데이트가 반영되는 장점이 있다. claims: 사용자의 스마트기기와 양방향 통신이 가능하되, 물교체 잔여일자, 양액 추가공급 잔여일자, 물 및 양액의 수위정보, 광조사부(600) 및 펌프부(300) 동작상태를 포함한 데이터가 스마트기기로 송신되고, 재배된 식물(1) 정보, 광 조사시간, 현재 시각을 포함한 데이터가 스마트기기로부터 수신되는 수경재배기에 있어서,외형을 형성하고 내부를 구획하는 본체부(100);상기 본체부(100)의 상측에 결합되고, 식물(1)이 재배되는 재배포트(10)가 장착되는 덮개부(200);상기 본체부(100)의 내부에 형성되고, 상기 덮개부(200)에 장착된 재배포트(10)로 양액(m)을 공급하는 펌프부(300);상기 본체부(100)의 내부에 형성되고, 재배포트(10)를 통하여 빠져나온 양액(m')의 수위를 감지하는 수위감지부(400);상기 본체부(100)의 일측에 결합되고, 상하로 높이가 조절되는 높이조절부(500);상기 높이조절부(500)의 상측에 결합되고, 재배포트(10)에 재배된 식물(1)에 광을 조사하는 광조사부(600);재배포트(10)에 재배된 식물(1)이 광조사부(600)로부터 기설정된 거리(H) 이내에 접근시 접근을 감지하는 접근감지센서;상기 접근감지센서가 식물(1)을 감지시 식물(1)과 광조사부(600) 사이의 거리를 기설정된 거리(H)만큼 유지되도록 높이조절부(500)의 높이를 조절하는 제어부;를 포함하되,상기 재배포트(10)는하측에서 상측으로 갈수록 외경이 커지는 바스켓 형상을 가지고, 재배부(12)가 거치되는 거치부(11)와,상기 거치부(11)의 내부에 거치되고, 식물씨앗(1')이 수용되는 원기둥 형상의 재배부(12)와,상기 거치부(11)의 상단에서 반경방향 외측으로 돌출형성되는 돌출부(13)와,상기 돌출부(13)의 상측에 결합되는 커버부(14)를 포함하고,상기 거치부(11)는거치부(11)의 하측의 내경(L')이 재배부(12)의 외경(L)과 동일한 크기를 가지도록 형성된 것을 특징으로 하고,상기 거치부(11)는거치부(11)의 측부에 형성되어 양액유로부(222)를 따라 이동된 양액(m)이 재배부(12)로 유입되는 양액유입공(11a)과,거치부(11)의 하단에 형성되어 재배부(12)를 빠져나온 양액(m')이 본체부(100)의 내부로 배출되는 양액배출공(11b)을 포함하고,상기 재배부(12)는재배부(12)의 상단에 형성되고, 식물씨앗(1')이 수용되는 씨앗수용부(12a)를 포함하고,상기 덮개부(200)는덮개부(200)의 상측에 형성되는 상부덮개(210)와,상기 상부덮개(210)의 하측에 결합되는 하부덮개(220)를 포함하고,상기 상부덮개(210)는재배포트(10)의 거치부(11)가 삽입되는 제1포트삽입공(211)과,상기 제1포트삽입공(211)의 외주면에 단턱지게 형성되어 재배포트(10)의 돌출부(13)가 안착되는 단턱부(212)와,상기 단턱부(212)에 함몰형성되어 손가락이 인입되는 손가락인입부(213)를 포함하고,상기 하부덮개(220)는상기 제1포트삽입공(211)에 대응되는 위치에 형성되어 재배포트(10)의 거치부(11)가 삽입되는 제2포트삽입공(221)과,펌프부(300)에서 공급되는 양액(m)이 이동되고, 상기 제2포트삽입공(221)과 연통되는 양액유로부(222)를 포함하고,상기 수위감지부(400)는하측에 양액이동공(411)이 형성되어 양액(m')이 유입되고, 플로터(420)의 수직이동을 가이드하는 가이드부(410)와,상기 가이드부(410)의 내부에 형성되고, 상기 양액이동공(411)으로 유입된 양액(m')의 수위에 따른 부력에 의해 가이드부(410)의 내측면을 따라 승강 가능하게 구비되며, 자기장을 발생시키는 플로터(420)와,상기 가이드부(410)의 하부에 형성되고, 상기 플로터(420)로부터 발생된 자기장을 감지하는 수위센서(430)를 포함하고,상기 플로터(420)는플로터(420)의 하단에 형성되어 자기장을 발생시키는 자석부(421)를 포함하는 것을 특징으로 하는수경재배기., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1146/1150 Row 1146: application_number: 1020200133158, combined_string: invention_title: 분무식 수경 재배장치 abstract: 본 발명은 본체; 식재된 육묘 뿌리가 아래로 통과하는 다수개의 뿌리통과공이 형성된 재배대가 상기 본체에 상하로 다단 배치된 트레이부; 상기 본체에 설치되어 다단 배치된 상기 재배대의 하부에 각각 배치되며 상기 재배대에 식재된 육묘 뿌리로 양액을 분무하는 분무노즐을 포함하는 복수개의 양액분무부; 상하로 다단 배치된 상기 재배대의 상부에 각각 배치되어 상기 재배대에 식재된 육묘로 하나 이상의 파장을 갖는 광을 조사하는 조명장치를 포함하는 복수개의 조명장치부; 상기 재배대의 하부에 배치되는 각각의 양액분무부의 하부에 각각 설치되며, 상기 양액분무부로부터 분무된 양액을 회수하여 일측에서 타측으로 이동시키는 복수개의 방수패드를 포함하는 양액회수부; 및 다단 배치된 상기 복수개의 방수패드의 일측에 구비되며 상기 방수패드로 회수되는 양액에 의해 상기 방수패드에 이슬이 맺히는 것을 방지하는 복수개의 송풍부를 포함하되, 상기 복수개의 방수패드는 윗변과 아랫변이 서로 다른 길이를 가지는 사다리꼴 형상을 가지고, 상기 방수패드의 양측변을 각각의 양액분무부의 하부에 설치 시 상기 방수패드의 윗변과 아랫변의 높이가 달라지며, 윗변 보다 아래쪽에 위치하는 아랫변 측으로 양액이 이동하고, 상기 송풍부가 상기 방수패드에 이슬이 맺히는 것을 방지하여 상기 방수패드에 맺혀진 이슬에 의해 양액이 식물로 필요이상으로 공급되는 것을 방지하는 것을 특징으로 하는 분무식 수경 재배장치를 제공한다.따라서, 방수패드가 사다리꼴 형상을 가짐으로써 방수패드를 양액분무부의 하부에 설치 시 방수패드로 포집되는 양액을 별도의 이동수단을 이용하지 않고 중력을 이용하여 원하는 지점으로 원활하게 이동시킬 수 있고, 이동된 양액을 순환시킴으로써 양액의 낭비를 줄일 수 있다. claims: 본체;식재된 육묘 뿌리가 아래로 통과하는 다수개의 뿌리통과공이 형성된 재배대가 상기 본체에 상하로 다단 배치된 트레이부;상기 본체에 설치되어 다단 배치된 상기 재배대의 하부에 각각 배치되며 상기 재배대에 식재된 육묘 뿌리로 양액을 분무하는 분무노즐을 포함하는 복수개의 양액분무부;상하로 다단 배치된 상기 재배대의 상부에 각각 배치되어 상기 재배대에 식재된 육묘로 하나 이상의 파장을 갖는 광을 조사하는 조명장치를 포함하는 복수개의 조명장치부;상기 재배대의 하부에 배치되는 각각의 양액분무부의 하부에 각각 설치되며, 상기 양액분무부로부터 분무된 양액을 회수하여 일측에서 타측으로 이동시키는 복수개의 방수패드를 포함하는 양액회수부; 및다단 배치된 상기 복수개의 방수패드의 일측에 구비되며 상기 방수패드로 회수되는 양액에 의해 상기 방수패드에 이슬이 맺히는 것을 방지하는 복수개의 송풍부를 포함하되,상기 복수개의 방수패드는 윗변과 아랫변이 서로 다른 길이를 가지는 사다리꼴 형상을 가지고, 상기 방수패드의 양측변을 각각의 양액분무부의 하부에 설치 시 상기 방수패드의 윗변과 아랫변의 높이가 달라지며, 윗변 보다 아래쪽에 위치하는 아랫변 측으로 양액이 이동하고,상기 송풍부가 상기 방수패드에 이슬이 맺히는 것을 방지하여 상기 방수패드에 맺혀진 이슬에 의해 양액이 식물로 필요이상으로 공급되는 것을 방지하는 것을 특징으로 하는 분무식 수경 재배장치., Ltext: 농업, prediction: 임업

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1147/1150 Row 1147: application_number: 1020200133159, combined_string: invention_title: 재배용 포트 abstract: 본 발명은 상하가 개방되고, 높이방향의 축을 따라 아래로 갈수록 단면적이 줄어드는 테이퍼진 형상을 가지며, 장기성 작물의 뿌리가 결착된 인공배지가 삽입되고, 둘레면에는 복수개의 절개홈이 상하방향으로 형성되며 장기성 작물의 뿌리가 성장 시 외측으로 벌어지는 배지결합부; 및 상기 배지결합부의 상단에서 외측으로 수평되게 연장되어 재배베드의 구멍에 걸림고정되며, 상기 재배베드의 형성된 구멍의 빈공간으로 복사선이 통과하는 것을 차단하는 차단부를 포함하되, 상기 배지결합부는 상부단이 상기 차단부와 연결되는 전개 본체와, 상기 전개 본체의 하부단과 연결되며 상기 인공배지가 안착되는 안착 본체를 포함하며, 상기 안착 본체는 복수개의 상기 절개홈에 의해 인접하는 복수개의 안착편으로 구획되고, 상기 복수개의 안착편이 장기성 작물의 뿌리가 성장 시 외측으로 벌어지며, 상기 복수개의 절개홈은 상기 안착 본체를 상하로 절개한 후 상기 전개 본체의 하부단을 절개하고, 상기 안착 본체의 하부단에는 상기 인공배지가 안착되는 안착단이 내부로 돌출되게 구비되며, 상기 안착단에 상기 인공배지가 안착되어 상기 인공배지가 상기 안착 본체의 하부로 이탈되는 것이 방지되는 것을 특징으로 하는 재배용 포트를 제공한다.따라서, 장기성 작물의 뿌리가 수용되는 안착 본체가 뿌리의 성장에 대응하여 벌어지는 구조를 가짐으로써 뿌리의 커진 부위에 경맥경화 현상이 발생하여 뿌리가 썩게 되는 것을 방지할 수 있고, 장기성 작물을 양액재배가 아닌 수경으로도 재배가 가능하도록 한다. claims: 상하가 개방되고, 높이방향의 축을 따라 아래로 갈수록 단면적이 줄어드는 테이퍼진 형상을 가지며, 장기성 작물의 뿌리가 결착된 인공배지가 삽입되고, 둘레면에는 복수개의 절개홈이 상하방향으로 형성되며 장기성 작물의 뿌리가 성장 시 외측으로 벌어지는 배지결합부; 및상기 배지결합부의 상단에서 외측으로 수평되게 연장되어 재배베드의 구멍에 걸림고정되며, 상기 재배베드의 형성된 구멍의 빈공간으로 복사선이 통과하는 것을 차단하는 차단부를 포함하되,상기 배지결합부는,상부단이 상기 차단부와 연결되는 전개 본체와,상기 전개 본체의 하부단과 연결되며 상기 인공배지가 안착되는 안착 본체를 포함하며,상기 안착 본체는 복수개의 상기 절개홈에 의해 인접하는 복수개의 안착편으로 구획되고, 상기 복수개의 안착편이 장기성 작물의 뿌리가 성장 시 외측으로 벌어지며, 상기 복수개의 절개홈은 상기 안착 본체를 상하로 절개한 후 상기 전개 본체의 하부단을 절개하고,상기 안착 본체의 하부단에는 상기 인공배지가 안착되는 안착단이 내부로 돌출되게 구비되며,상기 안착단에 상기 인공배지가 안착되어 상기 인공배지가 상기 안착 본체의 하부로 이탈되는 것이 방지되는 것을 특징으로 하는 재배용 포트., Ltext: 농업, prediction: '농업'

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.

1148/1150 Row 1148: application_number: 1020200121174, combined_string: invention_title: 거치용 식물 재배 장치 abstract: 본 발명에 따른 거치 대상물의 외면에 거치될 수 있는 거치용 식물 재배 장치는, 거치 대상물의 외면을 따라 길이 조절 가능하게 형성되는 하우징 및 상기 하우징의 일측에 배치되는 식물이 식재되는 식재부로 구성된다. claims: 거치 대상물의 외면의 적어도 일부에 거치될 수 있는 거치용 식물 재배 장치로서,상기 거치 대상물의 외면을 따라 길이 조절 가능하게 형성되고, 사각형의 거치대상물에 거치될 수 있도록 적어도 한 부분이 'ㄱ'형상으로 절곡 형성되는 중공의 하우징; 및 식물이 상기 하우징의 내부에서 상기 하우징을 따라 생장가능하도록 상기 하우징의 일측에 배치되는 식재부;를 포함하는 거치용 식물 재배 장치.거치 대상물의 외면의 적어도 일부에 거치될 수 있는 거치용 식물 재배 장치로서,상기 거치 대상물의 외면을 따라 길이 조절 가능하게 형성되고, 사각형의 거치대상물에 거치될 수 있도록 형성되며 적어도 두 부분이 'ㄱ'형상으로 절곡 형성되는 중공의 하우징; 및 식물이 상기 하우징의 내부에서 상기 하우징을 따라 생장가능하도록 상기 하우징의 양 단에 배치되는 식재부;를 포함하는 거치용 식물 재배 장치., Ltext: 농업, prediction: '농업'
1149/1150 Row 1149: application_number: 1020200111002, combined_string: invention_title: 떡차 및 그의 제조 방법 abstract: 본 발명은, 녹차 생엽을 숙성 발효하여 떡처럼 덩어리로 만드는 고형차인 떡차의 제조 방법에 관한 것으로, 녹차 생엽의 채엽 및 선별 단계와, 시들기 위조 단계와, 찌기 단계와, 성형 단계와, 1차 자연 건조 단계와, 황토방 발효 단계와, 2차 자연 건조 단계와, 저장 단계와, 화롯불에 굽는 단계를 포함한다. claims: (a) 녹차 생엽을 채엽하고 선별하는 단계와,(b) 선별된 녹차 생엽을 하룻밤 시들린 후, 찻잎의 막을 벗기는 단계와,(c) 막이 벗겨진 찻잎을 천에 싸서 수증기를 이용하여 찌는 단계와,(d) 쪄낸 찻잎에 감로잎을 혼합한 혼합물을 분쇄하여 차 덩어리로 한 후, 당해 차 덩어리를 떡차 틀을 이용하여 일정한 형태의 떡차로 성형하는 단계와,(e) 성형된 떡차를 하루동안 일광 건조하는 단계와,(f) 일광 건조된 떡차를 볏짚에 접촉시켜 황토방에서 발효시키는 단계와,(g) 황토방에서 발효된 떡차를 통풍이 용이하고 그늘진 곳에서 자연 건조하는 단계와,(h) 상기 자연 건조시킨 떡차를 차 단지에 넣고 한지로 봉하여 저장하는 단계를 포함하고,상기 (d) 단계에 있어서의 상기 혼합물은, 감로잎을 1중량％ 이상 5중량％ 미만으로 배합하고, 또한 죽염을 0.1중량％ 이상 0.5중량％ 미만으로 배합한 것을 특징으로 하는 떡차의 제조 방법.제1항에 기재된 제조 방법으로 제조된 떡차., Ltext: 농업, prediction: 임업

In [68]:
from google.colab import files

# 파일 다운로드
files.download('test_output_ver2.csv')

In [69]:
# CSV 파일 읽기
df = pd.read_csv('test_output_ver2.csv', header=None)

# 값이 동일한지 확인
equal_count = (df.iloc[:, 3] == df.iloc[:, 4]).sum()

# 전체 데이터에서 동일한 값이 차지하는 비율 계산
total_rows = len(df)
equal_percentage = (equal_count / total_rows) * 100

# 결과 출력
print(f"Meta-Llama-3.1-8B-Instruct 모델 예측 결과 정확도 계산('농업','임업', '어업') (프롬프트 튜닝 버전 - Ver2): {equal_percentage:.2f}%")
# Meta-Llama-3.1-8B-Instruct 모델 예측 결과 정확도 계산('농업','임업', '어업') (Base 버전): 42.68%
# Meta-Llama-3.1-8B-Instruct 모델 예측 결과 정확도 계산('농업','임업', '어업') (프롬프트 튜닝 버전 - Ver2): 70.09%

Meta-Llama-3.1-8B-Instruct 모델 예측 결과 정확도 계산('농업','임업', '어업') (프롬프트 튜닝 버전 - Ver2): 22.09%

In [70]:
# 정답이 '임업'일 때
correct_label = '임업'

# 정답이 '임업'일 때 '임업'으로 예측한 비율
correct_forest_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '임업'일 때 '농업'으로 예측한 비율
correct_forest_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '임업'일 때 '어업'으로 예측한 비율
correct_forest_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '농업'일 때
correct_label = '농업'

# 정답이 '농업'일 때 '농업'으로 예측한 비율
correct_agriculture_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '농업'일 때 '임업'으로 예측한 비율
correct_agriculture_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '농업'일 때 '어업'으로 예측한 비율
correct_agriculture_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '어업'일 때
correct_label = '어업'

# 정답이 '어업'일 때 '어업'으로 예측한 비율
correct_fishery_pred_fishery = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '어업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '어업'일 때 '임업'으로 예측한 비율
correct_fishery_pred_forest = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '임업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 정답이 '어업'일 때 '농업'으로 예측한 비율
correct_fishery_pred_agriculture = ((df.iloc[:, 3] == correct_label) & (df.iloc[:, 4] == '농업')).sum() / (df.iloc[:, 3] == correct_label).sum() * 100

# 결과 출력
print(f"정답이 '임업'일 때 '임업'으로 예측한 비율: {correct_forest_pred_forest:.2f}%")
print(f"정답이 '임업'일 때 '농업'으로 예측한 비율: {correct_forest_pred_agriculture:.2f}%")
print(f"정답이 '임업'일 때 '어업'으로 예측한 비율: {correct_forest_pred_fishery:.2f}%")

print(f"정답이 '농업'일 때 '농업'으로 예측한 비율: {correct_agriculture_pred_agriculture:.2f}%")
print(f"정답이 '농업'일 때 '임업'으로 예측한 비율: {correct_agriculture_pred_forest:.2f}%")
print(f"정답이 '농업'일 때 '어업'으로 예측한 비율: {correct_agriculture_pred_fishery:.2f}%")

print(f"정답이 '어업'일 때 '어업'으로 예측한 비율: {correct_fishery_pred_fishery:.2f}%")
print(f"정답이 '어업'일 때 '임업'으로 예측한 비율: {correct_fishery_pred_forest:.2f}%")
print(f"정답이 '어업'일 때 '농업'으로 예측한 비율: {correct_fishery_pred_agriculture:.2f}%")

정답이 '임업'일 때 '임업'으로 예측한 비율: 72.22%
정답이 '임업'일 때 '농업'으로 예측한 비율: 2.78%
정답이 '임업'일 때 '어업'으로 예측한 비율: 0.00%
정답이 '농업'일 때 '농업'으로 예측한 비율: 12.30%
정답이 '농업'일 때 '임업'으로 예측한 비율: 44.46%
정답이 '농업'일 때 '어업'으로 예측한 비율: 0.00%
정답이 '어업'일 때 '어업'으로 예측한 비율: 14.35%
정답이 '어업'일 때 '임업'으로 예측한 비율: 45.65%
정답이 '어업'일 때 '농업'으로 예측한 비율: 0.43%